### ISSUE TITLE
Hook to allow the field layout to be set programatically (by handle)

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1000]
> Created by: Bob Olde Hampsink (b.oldehampsink@itmundi.nl) on 2015/04/30 06:39:01 +0000
> Votes at time of UserVoice import: 6

-----------------------------------

Hook to allow the field layout to be set programatically (by handle)

**Comment by brandonkelly** [comment]
This can be done via `EVENT_INIT` in Craft 3.
