### ISSUE TITLE
There was a Commerce Variants filedtype

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1001]
> Created by: Jeremy Daalder (jd@imagescience.com.au) on 2015/08/17 22:59:59 +0000
> Votes at time of UserVoice import: 6

-----------------------------------

It would be great if there was a Commerce Variants fieldtype that would allow relations to a specific variant rather than the entire product.

Or perhaps an option on the existing Commerce Products fieldtype that let's you choose either a product or a specific variant as the relatable thing.

**Comment by thoughtfulweb** [comment]
+1 for a Commerce Variants fieldtype

**Comment by brandonkelly** [comment]
@thoughtfulweb FFR, please just add 👍 reactions to the original issue post, rather than "+1" comments. Thanks!

**Comment by thoughtfulweb** [comment]
Whoops. I didn’t know about that feature. Thanks for letting me know.

**Comment by bossanova808** [comment]
(This is available in Commerce 2)
