### ISSUE TITLE
limitAutoSlugsToAscii do not work

### ISSUE THREAD

**Issue by jan10** [craftcms/cms#10012]
### Description
I have enabled the following setting in `general.php`:

``` 
 'limitAutoSlugsToAscii ' => true,
```

When I create a new page with "ä", the slug is not converted to "ae":

![image](https://user-images.githubusercontent.com/192557/138884363-3613ccc4-a04f-49c5-98b4-f1492043b76d.png)

### Steps to reproduce

1. Add `'limitAutoSlugsToAscii ' => true,` to config.php
2. Add a new entry with `ä`

### Additional info

- Craft version: 3.7.17.2
- PHP version:  8.0.11
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

Contact Form	2.2.7
Image Resizer	2.1.0
Imager X	v3.5.3
Minify	1.2.10
Redactor	2.8.8
SEO	3.7.4

**Comment by mmikkel** [comment]
Wanted to add a couple of thoughts to this.

Compared to what we can currently achieve with a single line of PHP, custom module settings require a ton of boilerplate – especially if the values need to be exposed to Twig. Don't know if this will be a feasible alternative for most sites.

Using environment variables for everything is also not a particularly good option. If a value is neither sensitive (like an API key) nor truly environment specific (like a local filepath), it probably belongs in version control and not in the `.env` file.

I'm not suggesting this change should be walked back, but I'm wondering if it'd be possible to introduce an additional way of adding custom config values to a project, that more closely matches the current ability. Perhaps a `customValues` array could be added to the general config or something like that?

**Comment by brandonkelly** [comment]
Not a bad idea @mmikkel. How would you feel if it were in its own file though, e.g. `config/custom.php`? Then from your templates you’d just be changing `general` to `custom` whenever accessing `craft.app.config.general.myCustomSetting`.

**Comment by mmikkel** [comment]
@brandonkelly I think a `config/custom.php` file would be the ideal solution, even better than having custom config settings support in `general.php` in the first place 👍

**Comment by brandonkelly** [comment]
Done: #10100

**Comment by mmikkel** [comment]
This is great. Thanks @brandonkelly!
