### ISSUE TITLE
LogoutRedirect

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#1003]
> Created by: James Lindeman (mail@jameslindeman.co.uk) on 2015/12/14 18:57:51 +0000
> Votes at time of UserVoice import: 6

-----------------------------------

As the docs say, ‘The URL Craft uses to log users out, based on the logoutPath config setting. Note that Craft will automatically redirect users to your homepage after going here; there’s no such thing as a “logout page”.’

How about a logoutRedirect for general config settings to specify where users get redirected to after logging out.

**Comment by jan-dh** [comment]
Would be really nice to be able to set the redirectUrl in the template

**Comment by jan-dh** [comment]
Any chance of making it more dynamic, so you could for example redirect the user to the same page but in a logged out state?

**Comment by brandonkelly** [comment]
The `logout` action doesn’t require a `POST` request like other actions that accept a `redirect` param. So no, that wouldn’t make sense here.

However I’ve just updated it to accept a function, so if you really wanted to do that, you could:

```php
'postLogoutRedirect' => function($siteHandle) {
     return Craft::$app->request->getParam('redirect', 'default/path');
},
```

**Comment by madebyspark** [comment]
This is only available in Craft 3, right?

**Comment by brandonkelly** [comment]
@madebyspark correct, wouldn't be easy to replicate the feature in Craft 2 unfortunately.

**Comment by madebyspark** [comment]
No worries - just checking as it comes up often. Thx @brandonkelly
