### ISSUE TITLE
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.

### ISSUE THREAD

**Issue by bencresty** [craftcms/cms#10035]
### Description

Up to date Chromium browsers (both tested in Chrome and in Edge) throw: "Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'." when using Craft. I've seen a thread here that this header is now sent by Craft, but it's either not working, it's too soon to launch as there's no support for it or I am missing information about this to set it up right. Like this it isn't very desirable though.
![image](https://user-images.githubusercontent.com/69322733/139277996-09ae3960-c019-42f3-a31c-ec99a78bbaed.png)

Do we need to do something to set this new header up?

### Steps to reproduce

1. Open a Craft website
2. Look in the console

### Additional info

- Craft version: 3.7.18.2
- PHP version: 8.0.12

**Comment by brandonkelly** [comment]
The header is only understood by Chrome, and only for users who have been added to Google’s FLoC tracking trial (without their knowledge), which is generally considered a bad idea for user privacy and security. Sending that cookie opts your site out of being included in its tracking calculations. See https://amifloced.org/ for more info about it.

We’ve made it configurable via the [permissionsPolicyHeader](https://craftcms.com/docs/3.x/config/config-settings.html#permissionspolicyheader) config setting, so you are free to remove it if you want.
