### ISSUE TITLE
Draft not publishing all changes in multi-site

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#10034]
### Description
Multi-site-lang setup, site A and B.
Site A has translated field changes in a draft and site B hasn't.
When you publish the draft from site B, the translated fields from site A get lost.
The translatable fields have "Translate for each site" and are in a matrix which has "Save blocks to all sites the owner element is saved in"

### Steps to reproduce

1. Have a single (didn't check for channels/structures) in 2 languages, with an existing matrix with translatable fields
2. Create a draft
3. In that draft, translate the fields in site A
4. Now go to site B and publish the draft
5. Translated fields in site A are now lost

### Additional info

- Craft version: 3.7.18.2

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.19 is out now with the fix. Thanks again.
