### ISSUE TITLE
Custom Aliases not working and validation key alert

### ISSUE THREAD

**Issue by KeygenLLC** [craftcms/cms#10038]
I don't know if this is a bug, but I've tried all the ways I could find to change aliases and set my own. 

All I want to do is:
- Change `@web` to my domain url 
- Change `@webroot` to my `/public_html` folder
- Create an alias for `@assetUrl` and `@assetPath` which lives at `/public_html/library`
- Create an alias for `@imageUrl` and `@imagePath` which lives at `/public_html/library/images`
- Create an alias for `@samplesUrl` and `@samplesPath` which lives at `/public_html/library/images/samples`

Spent hours on this, followed the docs, tried examples on StackOverflow, but no matter what I try, I can't get aliases working. I'm also seeing different examples for how to set them and would appreciate a clear example of how to declare them and where.

Some examples say to add paths in the `.env` only. Others say to just put aliases in `general.php`—and some of these say they go inside `'*' => [ ],` and others don't. Others say to add them in `.env` and in `general.php`. The docs show a mix of these. Needless to say, but I'm beyond confused and nothing is working. It either breaks the site so it couldn't find the control panel, or it duplicated my actual assets folder and all subfolders with the name of the aliases when I tried to update asset indexes.

### License Key
I got an alert that the validation key file was deprecated. I followed the instructions and added the key to the `general.php` config and removed the file. Since then the file has reappeared twice which throws the same warning.

Message:
```
The auto-generated validation key stored at /path/storage/runtime/validation.key has been deprecated. Copy its value to the securityKey config setting in config/general.php.
```

Origin:
```
/path/vendor/craftcms/cms/src/services/Config.php:168
```

**Comment by brandonkelly** [comment]
> * Change `@webroot` to my `/public_html` folder
> * Create an alias for `@assetUrl` and `@assetPath` which lives at `/public_html/library`
> * Create an alias for `@imageUrl` and `@imagePath` which lives at `/public_html/library/images`
> * Create an alias for `@samplesUrl` and `@samplesPath` which lives at `/public_html/library/images/samples`

Does your `public_html` folder actually live at the root of the server’s file system? You can know for sure by removing the `@webroot` alias definition from `config/general.php`, then going to **Utilities** → **System Report** in your control panel and searching for `@webroot`. When you haven’t defined it explicitly, Craft will default to whatever the actual server path is to the folder that contains your `index.php` file.

Alternatively, you can just set it relative to the location of `config/general.php`. For example, if your webroot folder is still called `web/` and lives alongside your `config/` folder, this would work:

```php
'aliases' => [
    'webroot' => dirname(__DIR__) . '/web',
    // ...
],
```

> I got an alert that the validation key file was deprecated. I followed the instructions and added the key to the `general.php` config and removed the file. Since then the file has reappeared twice which throws the same warning.

Craft projects have this [solved by default](https://github.com/craftcms/craft/blob/main/config/general.php#L27), with `securityKey` set to `App::env('SECURITY_KEY')`, and your `.env` file should be defining a `SECURITY_KEY` environment variable. If that was deleted, you can generate a new one by running the following command:

```bash
> php craft setup/security-key
```

**Comment by KeygenLLC** [comment]
Yes, `public_html` folder is in the root directory. Just renamed the default `web` folder as my server runs WHM/Cpanel and defaults to that, so I'm in the habit of using that name.

I'll give your code a try for the aliases and see how I fare.

Thanks man
