### ISSUE TITLE
Issue running queue/run via cron job

### ISSUE THREAD

**Issue by danfathom** [craftcms/cms#10039]
### Description

Hi,

I'm having some issues running the queue/run cron job from my cpanel server. I've got the correct path and everything but just can't get it to work. Instead of the queued tasks running using the cron job, they instead run once i've logged into the CMS.

The cron job i've got is this:

```cron
* * * * * /usr/bin/php /home/devdbweb/thestatbible.com/craft queue/run
```

I can confirm that '/home/devdbweb/thestatbible.com/craft' is the correct path to the craft file. I've also made sure the memory_limit on my server is 256M and the max_execution_time is 120.

It's also strange that I have this working on a different project thats hosted on a different server.

Any ideas what might be the issue would be really halpeful.

### Additional info

- Craft version: Craft Pro 3.7.18.2
- PHP version: 7.3.32
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
Feed Me - 4.4.0
Stripe Payments - 3.3.7

**Comment by angrybrad** [comment]
Anything getting logged in Craft's log files?  What if you try to redirect the stdout and stderr of the cron - something like this:

    /usr/bin/php /home/devdbweb/thestatbible.com/craft queue/run  1> ./cronout.txt 2> ./cronerr.txt

**Comment by danfathom** [comment]
Thanks for getting back to me.

Nothing gets logged in the log files until I log in to the CMS and the queue runs that way.

I've just added that cron job you sent. Not sure what to look out for, but nothing has changed in the logs since i've added it. I've set it to run every minuted, and waited a couple minutes to check.

**Comment by angrybrad** [comment]
Are you sure the cron job is actually running? What distro is this?

**Comment by danfathom** [comment]
After many hours I got to the bottom of the issue and it was intact an issue my end. Instead of the cron job being:
-  /usr/bin/php /home/username/public_html/path/to/cron/script
I had to use:
- /usr/local/bin/ea-php74 /home/username/domain_path/path/to/cron/script. 

I seems I had to use the domain specific way, as my project is in a folder outside the main public_html folder.

Thanks for coming back to me with some suggestions :)
