### ISSUE TITLE
Failed to execute 'getComputedStyle' error

### ISSUE THREAD

**Issue by bencresty** [craftcms/cms#10041]
### Description

This error appears in the console when in login screen:

![image](https://user-images.githubusercontent.com/69322733/139582985-33e32af4-62a2-4b19-96cb-85eddc2470e1.png)

Please guys, have a console open while developing to prevent these kind of basic issues that could've been preventing by basic defense programming IMO. It happens pretty often with using Craft there are error messages and warnings in the console not being solved even after a long time after mentioning. This deserves way more attention IMO and is kind of worrying to me as FE dev to be honest.

### Steps to reproduce

1. Go to login screen of Craft 
2. Open dev tools and watch in the console

### Additional info

- Craft version: 3.7.18.2
- PHP version: 8.0.12

**Comment by brandonkelly** [comment]
Already fixed for the next release, via #10036.

**Comment by bencresty** [comment]
@brandonkelly 

Nice. So you have time to fix this one! ;)
Next to it being an issue out there long time without solving, it's poluting the console log quite a lot

![image](https://user-images.githubusercontent.com/69322733/140590355-0883de98-5905-4376-b648-96a0d778b92d.png)
