### ISSUE TITLE
Expected default sort of nested category field

### ISSUE THREAD

**Issue by jep-a** [craftcms/cms#10042]
### Description

When an entry has a category field with a nested category assigned to it and it's being eagerloaded. It's not consistent and/or clear to how this array is being sorted.

I would expect this array to be sorted by hierarchy/`lft` but it is not. Only after manually setting the sort to be `lft` on the eagerload it will do that.

Expecting this:
![image](https://user-images.githubusercontent.com/20326207/139744585-cb508602-df12-4270-883a-142f9b7fc028.png)

To return:
![image](https://user-images.githubusercontent.com/20326207/139745578-0bbd2c99-cfb1-4016-9b07-0f2404658b00.png)

But it is returning this instead:
![image](https://user-images.githubusercontent.com/20326207/139745656-580626e9-bafc-423c-8e47-3de2784ab00e.png)

### Steps to reproduce

1. Make a category field on an entry and limit it to 1 category
2. Make a category that is nested 3 levels deep
3. Assign that category to an entry like this

![image](https://user-images.githubusercontent.com/20326207/139744585-cb508602-df12-4270-883a-142f9b7fc028.png)

4. Eagerload and get the value of that field like this

```php
Craft::$app->getElements()->eagerLoadElements(
  Product::class,
  [$product],
  ['categoryField']
);
```

```php
foreach ($entry->mainProductType as $category) {
  dump([
    'parent' => !empty($category->getParent()->title) ? $category->getParent()->title : 'true',
    'title' => $category->title
  ]);
};
```
5. Examine the order of the categories in your array
6. To make sure it will always return in hierarchical order, I eagerload it like this:
```php
Craft::$app->getElements()->eagerLoadElements(
  Product::class,
  [$product],
  ['categoryField', ['orderBy' => 'lft asc']]
);
```

### Additional info

|  | Version |
| --- | --- |
| Craft | Craft Pro 3.6.16 | 
| PHP | 7.3.30 |
| Database | MySQL 5.7.34 |

| Plugin | Version |
| --- | --- |
| Amazon S3 | 1.2.11 |
| Cookies | 1.1.14 |
| Craft Commerce | 3.3.4 |
| Doxter | 3.5.1 |
| Instant Analytics | 1.1.12 |
| Linkit | 1.1.12.1 |
| oEmbed | 1.3.8 |
| Redactor | 2.8.7 |
| Retour | 3.1.54 |
| SEOmatic | 3.3.43 |
| Similar | 1.1.5 |
| Stripe for Craft Commerce | 2.3.2.1 |

**Comment by brandonkelly** [comment]
Craft 3.7.19 is out now with the fix.
