### ISSUE TITLE
Variable "orientation" does not exist.

### ISSUE THREAD

**Issue by seandelaney** [craftcms/cms#10044]
### Description

Upgraded from 3.7.16 to 3.7.18.2 and now cannot access any entry.

Upgrade went fine. No issues.

I read in the changelog, that orientation option was added. See: https://github.com/craftcms/cms/blob/main/CHANGELOG.md#changed-2

I've cleared cache, wiped storage/runtime folder.

I'm unable to get around this issue. 

![Screenshot 2021-11-02 at 10 18 32](https://user-images.githubusercontent.com/580403/139829042-3f37564d-106c-4282-b29b-5e85f5bea447.png)

### Additional info

- Craft version: 3.7.18.2
- PHP version: 7.4.3

**Comment by andris-sevcenko** [comment]
@seandelaney Do you have any 3rd party field types installed?

**Comment by seandelaney** [comment]
> @seandelaney Do you have any 3rd party field types installed?

I'm using:

- Redactor
- Super Table
- Preparse Field
- SEO Settings (from SEOMatic)
- oEmbed
- VZ URL
- Position Fieldtype

All plugins are using their latest versions.

**Comment by andris-sevcenko** [comment]
Can you look a bit further in the stacktrace and see if it's easy to get an idea where the error is coming from?

**Comment by seandelaney** [comment]
@andris-sevcenko I've already looked through the error stack and saw nothing that stood out.

Will look again.

**Comment by andris-sevcenko** [comment]
@seandelaney that's strange. Can you verify that you have the following line present in code?
https://github.com/craftcms/cms/commit/84ab6803ec0ba201b9cf094cd5158053e5204b47#diff-66d7197e2f3aaa2d815c1015766ea6850213fc682f3795c21e043c4fdb0a189fR229

**Comment by seandelaney** [comment]
@andris-sevcenko 

> Can you verify that you have the following line present in code?

Yes, I have that line but I also found this, so winder if its the SEOMatic plugin field type:
![Screenshot 2021-11-02 at 12 36 31](https://user-images.githubusercontent.com/580403/139847843-ec4736fe-abc6-467f-8a83-1ce0cc5dcd4f.png)

**Comment by andris-sevcenko** [comment]
Do you also, by any chance, have Overflow installed?

**Comment by brandonkelly** [comment]
Is `seoTitle` a custom field?

**Comment by seandelaney** [comment]
![Screenshot 2021-11-02 at 13 12 25](https://user-images.githubusercontent.com/580403/139853361-2f3ba273-9de7-4844-ad55-e8208fc8b921.png)

Its an Overflow field, but literally just found where it was coming from:

https://github.com/experience/overflow.craft-plugin/issues

Closing this issue since I think its plugin related.

**Comment by brandonkelly** [comment]
Aha. Well they shouldn’t be using the Plain Text field’s internal input template. But it’s an easy fix, so I’ve just patched it on Craft’s end.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.18.2"` and run `composer update`.

**Comment by brandonkelly** [comment]
(Sorry, previous commit didn’t include the actual fix accidentally. Definitely fixed now.)

**Comment by seandelaney** [comment]
I can confirm, patch has fixed the issue.

I've pinged the Experience plugin developer to update at his end too.

Thanks guys!

**Comment by brandonkelly** [comment]
Craft 3.7.19 is out now with that fix.
