### ISSUE TITLE
`getFieldValue()` not returning eager-loaded data

### ISSUE THREAD

**Issue by mattsbanner** [craftcms/cms#10047]
### Description
I'm not completely sure if this is intended behaviour or not but when using `with()` on an Entry query to eager-load the relations `getFieldValue()` returns the query, not the eager-loaded results.

This makes it difficult to get the results of all fields with `getFieldValues()`.

If this is intended, is there a way to get all field values including eager-loaded data, without having to use something like `$entry->fields()` to fetch the values individually with `$entry->{$fieldName}`?

### Steps to reproduce
When running this code
```php
$entry = Entry::find()
    ->with([
        'relatedCategories',
        'contentBuilder'
    ])
    ->section('pages')
    ->one();
```

`$entry->relatedCategories` and `$entry->contentBuilder` return the expected eager-loaded results.
```
[
    craft\elements\Category,
    craft\elements\Category
]
```
```
[
    craft\elements\MatrixBlock
]
```

 However, `$entry->getFieldValues()` will return
```
  "relatedCategories" => craft\elements\db\CategoryQuery
  "contentBuilder" => craft\elements\db\MatrixBlockQuery
```

### Additional info

- Craft version: 3.7.19
- PHP version: 7.4
- Database driver & version: MySQL 5.7
- Plugins & versions: None, tested on base install.

**Comment by brandonkelly** [comment]
Agree that’s a little awkward. The change could have some unexpected behavior though, so I just changed in for Craft 4 rather than the next 3.x release.
