### ISSUE TITLE
Homepage slug not working in Reference Tags

### ISSUE THREAD

**Issue by remcoov** [craftcms/cms#10055]
### Description
Hi, I would like to reference to a custom field on my homepage via Reference Tags. When I use the homepage's **slug** as `<Identifier>`, it's not working. When I use the homepage's **ID**, it is working.

So, this works:

`{{ '{entry:3:customFieldName}' | parseRefs }}`

.. and this does **not** work.

`{{ '{entry:homepage:customFieldName}' | parseRefs }}
`

I doublechecked that the homepage slug indeed was 'homepage'. Am I doing something wrong, or is this a bug?

### Additional info

- Craft version: 3.7.18.2
- PHP version: 7.4

**Comment by brandonkelly** [comment]
This turned out to be a docs issue. Entries _must_ be referenced by both their section handle _and_ slug; not just the slug. So this should work:

```twig
{{ '{entry:sectionHandle/homepage:customFieldName}'|parseRefs }} 
```

**Comment by remcoov** [comment]
Hi @brandonkelly. Thanks, this solved my problem! I see you updated the docs accordingly, but I see the same error(s) in the [examples](https://craftcms.com/docs/3.x/reference-tags.html#examples) too, so you might want to fix that as well.

**Comment by mattstein** [comment]
[Just updated](https://github.com/craftcms/docs/commit/b621aa62cf0762fbc4fee200b880dbdd8ff7ad2d) @remcoov, thank you!
