### ISSUE TITLE
Utilities > System messages preview don't match saved value

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#10059]
### Description
If you customise the system messages through the control panel, then go to Utilities > System messages, the previews of the messages do not match the actual messages.

![image](https://user-images.githubusercontent.com/1250017/140502404-1ec2c300-ae3f-403f-9796-9d36132269e6.png)

### Additional info

- Craft version: 3.7.19.1
- PHP version: 8.0.11
- Database driver & version: MySQL

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Is your user account language different from the primary site by chance

**Comment by darylknight** [comment]
Yes. My language is English UK, the Craft site language is normally English US (although in this particular case it's a 4-language multi-site, but I notice it on most sites I work on).

**Comment by brandonkelly** [comment]
Yeah OK, that’s expected then. You haven’t actually changed the system message for the language you’re currently viewing the control panel in, so it just shows the default.

**Comment by darylknight** [comment]
Sorry, I'm confused - Does that mean we need to, for example, change the system message 4 times for a site that has 4 languages? Or that we need to change it for every language a control panel user might set their own control panel to?

**Comment by brandonkelly** [comment]
Apologies, my last message was a little misleading. The System Messages utility will always show the primary site’s messages, regardless of your own account’s preferred language.

> Does that mean we need to, for example, change the system message 4 times for a site that has 4 languages? Or that we need to change it for every language a control panel user might set their own control panel to?

System messages are translatable, yes. When Craft sends a system message, it will load the message in the recipient’s preferred language, or fall back to the current site’s language if they don’t have one (or the primary site’s language if it’s being sent from the control panel).

So if you have four languages, and wish to customize a system message, you will probably want to change it for each language.

**Comment by darylknight** [comment]
Got it, thank you.
