### ISSUE TITLE
Allow users having the  "Administrate users" to require a password reset on next login for other users

### ISSUE THREAD

**Issue by nstCactus** [craftcms/cms#10057]
Wouldn't it make more sense to allow all users having the **Administrate users** permission to set **Require a password reset on next login** checkbox on other users, instead of just the admin?

The tooltip of the administrate user permission says: 
> Includes activating user accounts, resetting passwords, and changing email addresses.

If you're ok with this change, I can make a PR.

https://github.com/craftcms/cms/blob/2f07f450733c6cb7c4df2af5846e5d485011fbdd/src/templates/users/_edit.html#L141

**Comment by brandonkelly** [comment]
Yeah they probably should be able to do that. I think there is more to it than that one line, but will look into it…

**Comment by nstCactus** [comment]
Yep, at least this should change too: 

https://github.com/craftcms/cms/blob/2f07f450733c6cb7c4df2af5846e5d485011fbdd/src/controllers/UsersController.php#L1212

**Comment by brandonkelly** [comment]
Changed for the next release!

**Comment by nstCactus** [comment]
Thanks a lot!
