### ISSUE TITLE
Preview not working properly 3.7.19

### ISSUE THREAD

**Issue by idleog** [craftcms/cms#10056]
### Description
After upgrading to 3.7.19, going into preview of structure entry, the preview is shown correctly. After changing a field, the preview is not shown anymore (only parts of it).
When leaving the preview and coming back, it's still broken.
When leaving the entry edit panel and re-editing the same entry and reopening the preview, it's still broken. 

### Steps to reproduce
1. Open preview
2. Change field of entry on the left preview panel

### Additional info

- Craft version: 3.7.19
- PHP version: 7.4.25
- Database driver & version: MySQL 5.5.5
- Plugins & versions:  Cloner 1.2.2   Control Panel Body Classes 2.2.1   Control Panel CSS 2.4.0   Cookies 1.1.15   Craft Commerce 3.4.6  Feed Me 4.4.0   Incognito Field 1.2.0   Mailchimp Subscribe 3.1.1   Neo 2.11.15   Redactor 2.8.8   Redirect Manager 1.1.1   Site Switcher 2.2.0   Wordsmith 3.3.0.1

**Comment by brandonkelly** [comment]
Not able to reproduce this on my end. Can you please email support@craftcms.com with a database backup, your `composer.json` and `composer.lock` files, as well as your `templates/` folder?

**Comment by idleog** [comment]
sent the files.
i recognized following: it also happens when changing a field in regular edit view and then opening the preview. so it's basically happening when having unsaved changes in the entry.

**Comment by idleog** [comment]
Update: I could reproduce this on a site of another client. 
It seems that the basic layout template is shown, but not the content of a twig block inside it.

**Comment by idleog** [comment]
I did some research. 
Whenever an entry is not saved and I open the preview, the level of the entry is not set. 

In templetes where I refer to `entry.level` to decide what template is loaded, I get null (or empty) for `entry.level` instead of a number and the wrong or no template is loaded. as soon as I save the entry, the `level` is set and the correct templates are loaded. 

So tell me I am doing sth wrong with twig code like that:
`{% if entry.level > 1%}
{{ include('pages/_secondlevel.twig') }}
{% else %}
{{ include('pages/_firstlevel.twig') }}
{% endif %}`

or then I would say that we really have a bug here on unsaved entries which have an undefined level property. 

in all my projects in which the templates are depending on twig code like that the issue happens, in all other projects it does not. 

thanks for your help!

**Comment by brandonkelly** [comment]
Aha, yeah that is a side effect of drafts no longer getting placed within the section’s structure.

Just fixed this for the next release by having drafts/revisions borrow the structure data from their canonical entry when previewed.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.20"` and run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.7.21 is out now with that fix. Thanks for the help!

**Comment by idleog** [comment]
Thanks for the fix!
