### ISSUE TITLE
CustomFieldBehavior integrity with unstable database connection?

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/cms#10052]
### Description

I've only observed this on one of our projects (twice), so forgive the scant details.

In short, I suspect there is some kind of stability issue in `Craft::_generateCustomFieldBehavior()` or `Craft::_autoloadCustomFieldBehavior()`, that is causing an "empty" `CustomFieldBehavior` class to be written to disk.

In trying to write out what the precise series of failures are, I honestly can't picture how the app would both:

1. Successfully bootstrap and load the Info table row to discover the current Field Version (`tvdvydgslhcz`);
2. Fetch an _empty_ array of fields;

The only conditions under which `Craft::_fields()` would return an empty array is either when there are actually no fields, or when Craft thinks it _isn't_ installed—but ~~if the Info row loaded (a prerequisite for writing to `CustomFieldBehavior_tvdvydgslhcz.php`), then Craft would also know it's “installed,” right?~~ Whoa, ~~turns out `->isDbConnectionValid()` is checked every time, so perhaps its return value can differ request-by-request?~~ still wrong, never mind!

In any case—the class file that _looks_ correct (insofar as it has the correct “Field Version”) ends up with zero field properties. On the other hand, the `000000000000` file appears to be from a prior request where Craft was completely unable to connect to the database… no confusion there!

### Footnotes

Filenames, as found on disk. Contents were identical—zero field handle properties.

```
-rw-r--r-- 1 www-data www-data 2512 Oct 25 09:52 CustomFieldBehavior_000000000000.php
-rw-r--r-- 1 www-data www-data 2512 Oct 25 09:52 CustomFieldBehavior_tvdvydgslhcz.php
```

Relevant database connectivity issue, around the same time:

```
2021-10-25 09:52:14 [-][-][-][error][craft\base\ApplicationTrait::getIsDbConnectionValid] There was a problem connecting to the database: Craft CMS can’t connect to the database with the credentials in config/db.php.
Next craft\errors\DbConnectException: Craft CMS can’t connect to the database with the credentials in config/db.php. in /var/www/client-name/releases/70/vendor/craftcms/cms/src/db/Connection.php:173
```

### Additional info

- Craft version: 3.6.16
- PHP version: 7.4.3
- Database driver & version: PostgreSQL 11.13
- Plugins & versions: Below!

Plugin | Version
---- | ----
Blitz	| 3.9.0
Cookies | 1.1.15
DigitalOcean Spaces Volume | 1.1.3
Mailgun | 1.4.3
Redactor	| 2.8.7
SEOmatic | 3.3.43
Twigpack | 1.2.14

**Comment by brandonkelly** [comment]
Beyond the extra PHP files that are left in `storage/runtime/compiled_classes/`, do things kick back into gear once the DB connection is reestablished?

**Comment by brandonkelly** [comment]
Just made the `CustomFieldBehavior` generation code a bit more resilient (f7235152d232af11c797de92bdb76049118c30c1), and wouldn’t be surprised if that ends up fixing this for you. 🤞🏻 

Going to close this for now, but feel free to reopen if you end up seeing it again after updating to 3.7.21+.
