### ISSUE TITLE
Customise element sources link doesn't use a pointer cursor

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#10067]
### Description

In the Entries section, if you hover over the cog wheel, "Customise" used to have the hand pointer icon to indicate a link. Looks like it's now just showing a standard mouse cursor as if it weren't interact-able (it still works though)

![image](https://user-images.githubusercontent.com/1250017/140764850-48613d4b-eb56-42dc-87b9-3a1f69cc6f9c.png)

Chrome, MacOS Montery

### Additional info

- Craft version: 3.7.19.1
- PHP version: 8.0.10
- Database driver & version: MySQL

**Comment by brandonkelly** [comment]
Thanks for pointing that out. Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.21 is out now with that fix. Thanks again!
