### ISSUE TITLE
GraphiQL throws request URI string error when graphQL queries are too long

### ISSUE THREAD

**Issue by toddpadwick** [craftcms/cms#10064]
### Description
GraphiQL stores graphQL mutations or queries as a query string in the URL. Although this sounds like it might be useful, most of the time, as the query strings are almost always longer than the servers allowed length, whenever you refresh or change schema type the page breaks and returns "Request URI too long" and you have to manually strip away the query string from the url and try again.

As the queries are stored in the session or user history anyway, I would suggest ditching the functionality to store query strings in the URL altogether to prevent this problem.

### Steps to reproduce

1. Create a long query (such as one for a matrix field or other long form content)
2. Try refreshing the page, or switching schema type
3. Browser will return this error if url query string is too long:

![Screenshot 2021-11-08 at 10 49 41](https://user-images.githubusercontent.com/36191462/140721065-3531aebd-5e60-4fe1-8eb4-4206c2b93955.png)

### Additional info

- Craft version:Craft Pro 3.7.16

**Comment by andris-sevcenko** [comment]
We can probably ditch that. Just have to come up with nice way to get the URL with the query in it on demand that is a nice UX experience, so it's possible to share queries.

**Comment by andris-sevcenko** [comment]
Just added this for the next Craft 3.7 release.
![Screen Shot 2021-11-11 at 16 25 20](https://user-images.githubusercontent.com/1891118/141314524-565d9c6e-c22c-4cb6-87ac-51249b64bbcd.png)

**Comment by brandonkelly** [comment]
Craft 3.7.21 is out now with that change.
