### ISSUE TITLE
Live Preview has viewport shortcuts

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1006]
> Created by: Andrew Fairlie (andie.fairlie@gmail.com) on 2015/06/09 13:29:36 +0000
> Votes at time of UserVoice import: 6

-----------------------------------

It would be great if a site admin can define a number of viewports so when that when an editor is previewing a new entry they can check how it works on different screen sizes. If a viewport is greater than their screen size, it would be brilliant if it used scaling so they still got a good idea of how it'll look.

Might be better suited to a plugin.

**Comment by brandonkelly** [comment]
This is finally coming in Craft 3.6 ✨ 

![Live Preview in Craft 3.6, with the phone viewport selected](https://user-images.githubusercontent.com/47792/104788975-9096dd00-5748-11eb-96da-3d512e7b59a5.jpg)

Big thanks to @joshangell for helping out with this!

**Comment by brandonkelly** [comment]
Craft 3.6.0 is out now with this ✨

**Comment by leevigraham** [comment]
@brandonkelly FR: Add ability to customise viewports.

**Comment by brandonkelly** [comment]
@leevigraham Can you post a new FR?
