### ISSUE TITLE
"Changes you made may not be saved." confirm dialog after changing the entry type

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#10076]
### Description

After changing the entry type via the entry type dropdown on edit entry pages, Craft will throw up the "Changes you made may not be saved." confirm dialog on page unload, even if the change was in fact auto-saved. 

Curiously, this only happens if the user _does not remove focus_ from the entry type dropdown, before navigating away from the page.

If focus is removed from the dropdown after changing the type, there seems to be an additional autosave occurring immediately after blurring the entry type input. After that, unloading the page does _not_ trigger the confirm dialog.

This feels like a bug, since the entry type change does in fact (auto)save immediately.

### Steps to reproduce

1. Create or edit an entry in a section with multiple entry types
2. Change the entry type via the dropdown
3. Wait for the autosave to finish
4. Without removing focus from the entry type dropdown, reload the page or click the browser's back button

### Additional info

- Craft version: 3.7.20
- PHP version:
- Database driver & version:
- Plugins & versions: none

Latest MS Edge, macOS Monterey

**Comment by brandonkelly** [comment]
Thanks for reporting! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.21 is out now with that fix. Thanks again!
