### ISSUE TITLE
Entries disappeared from control panel after applied project config 

### ISSUE THREAD

**Issue by PublicVar** [craftcms/cms#10072]
### Description

Starting the project, we had a section called Session with multiple custom fields. This sections had some entries. 

Additionally, these entries could be referenced in other section called Report. But this part has not change.

Then, we decided to remove some fields from Session. We removed the fields from the section layout but didn't delete them.

In local there were no problems, but when we pushed on staging, the entries Session disappeared from the control panel in  admin/entries/session. 

We didn't rename section Session nor the handle.

After some investigations in the database we found :

* in the table "content", the entries seem to still be there. 
* in the table  "section", there is 2 lines for session with the same name and handle but different UID.

How can we get the Session entries back to display ?

### Additional info

- Craft version: 3.7.16
- PHP version: 7.4
- Database driver & version: MariaDB 10.4.21
- Plugins & versions:
```json
    "bertoost/craft-mailjet": "1.2.3",
    "besteadfast/craft-preparse-field": "1.2.5",
    "born05/craft-sentry": "1.1.2",
    "craftcms/cms": "3.7.16",
    "craftcms/guest-entries": "2.4.0",
    "craftcms/redactor": "2.8.8",
    "doublesecretagency/craft-cpcss": "2.4.0",
    "ether/seo": "3.7.4",
    "masugadesign/cpfilters": "1.1.3",
    "mildlygeeky/craft-kint": "1.0.0",
    "mmikkel/incognito-field": "1.2.0",
    "mmikkel/retcon": "2.2.3",
    "nystudio107/craft-twigpack": "1.2.15",
    "nystudio107/craft-typogrify": "1.1.18",
    "nystudio107/craft-vite": "1.0.16",
    "putyourlightson/craft-elements-panel": "1.1.1",
    "unionco/calendarize": "1.2.18",
    "verbb/super-table": "2.6.8",
    "vlucas/phpdotenv": "3.6.9",
    "yiisoft/yii2-redis": "2.0.16"
```

**Comment by nickdunn** [comment]
Are you using source control, and what does the diff of the YAML files look like after you made these changes? Can you see a duplicate section being created in these files?

On your local I would try rebuilding project config from your database, which will create a fresh set of YAML files, just in case they didn't serialise to files correctly the first time.

**Comment by brandonkelly** [comment]
> in the table "section", there is 2 lines for session with the same name and handle but different UID.

That means the Session section must have been manually created in each environment, with two different UIDs. So when you applied the project config changes from your dev environment on production, that told Craft to delete whatever section didn’t exist in the new project config, and create a new one based on the UID that came from dev.

It’s exactly the situation we warn about here: https://craftcms.com/docs/3.x/project-config.html#production-changes-may-be-forgotten (just substitute “staging for “production”).

To get your environments back in sync, run through the [environment setup](https://craftcms.com/docs/3.x/project-config.html#environment-setup) instructions, and be sure to disable admin changes from all non-dev environments by disabling [allowAdminChanges](https://craftcms.com/docs/3.x/config/config-settings.html#allowadminchanges) on them.

**Comment by PublicVar** [comment]
@brandonkelly the Session was not manually created in each environnement. The Session was created long ago and existed in all environnement

**Comment by LarkAnspach** [comment]
I hope more calls can be made soon and email is not the greatest tool for me, I think it's my personal opinion.

**Comment by brandonkelly** [comment]
Craft doesn’t just randomly refresh sections’ UIDs though, so there’s not really any other explanation for how you would have two separate Session sections with different UIDs besides that the new one was manually created. Perhaps it all happened on dev, and someone accidentally deleted the Session section and then recreated it. Not sure exactly.

You can try searching your Git history, or your `storage/config-deltas/` folder for an exact retrace of what changes to the project config were made on each environment. If you search for the Session sections’ UIDs, you should be able to find the exact moment that they were deleted/created. Maybe that will give you a clue.
