### ISSUE TITLE
Reverting to a revision on a multi-site Single causes unexpected data loss

### ISSUE THREAD

**Issue by joshuabaker** [craftcms/cms#10073]
### Description

When reverting to an older revision for a Single, all changes made on other sites since that revision are lost. This is despite having fields configured to be saved on a per-site basis.

The expectation here was that revisions are per site, which does seem more logical — the likely number of sites per install is lower than the likely number of revisions, meaning reverting many is lower effort. Currently, if this is intended behaviour, the chances are far greater of larger, unexpected data loss.

### Steps to reproduce

1. Create a Single entry section with a Matrix field configured to not propagate (i.e. “Only save blocks to the site they were created in”) on an install with 2+ Sites configured. 
2. Save some Matrix content to Site 1 and then save different content to Site 2. 
3. Reverting to the first revision will erase all content added to Site 2.

### Additional info

- Craft version: 3.7.20
- PHP version: 8.0.2
- Database driver & version: MySQL 8.0.23

**Comment by joshuabaker** [comment]
Related to #9844

**Comment by brandonkelly** [comment]
This is working a expected. See https://github.com/craftcms/cms/issues/9844#issuecomment-921139555 + https://github.com/craftcms/cms/discussions/8888#discussioncomment-1440078.
