### ISSUE TITLE
An element expiryDate should not be able to be set before a postDate

### ISSUE THREAD

**Issue by samhibberd** [craftcms/cms#10074]
After a quick chat with @brandonkelly regards a scenario where we have been able to set both a `postDate` in the future and an `expiryDate` in the past, we established that this probably shouldn't be possible and should have a validation rule added to prevent it. 

If it remains possible then the status which takes precedence needs to be decided `pending` or `expired`  and the element query would need to be updated to respect this. 

The current status of an element in this scenario is `pending` and an element query incorrectly returns a matching element for both a query for `->status('expired')` and `->status('pending')`.

**Comment by brandonkelly** [comment]
Just fixed this for the next release. Going forward, entries’ default post dates will be set to the day before their expiry dates, if they have one, and entries will validate that their post dates come before their expiry dates when saved as enabled.

**Comment by brandonkelly** [comment]
Craft 3.7.21 is out now with this change.
