### ISSUE TITLE
entry-revisions/save-draft action is not able to create entry along with draft

### ISSUE THREAD

**Issue by ivanBereznev** [craftcms/cms#10089]
### Description
I want to build a dashboard widget that would create entry draft from user input and redirect user to its edit page. So, ideally entry and a provisional draft should be created in one form submission. As far as I can see, [Save Draft action](https://github.com/craftcms/cms/blob/develop/src/controllers/EntryRevisionsController.php#L216) is supposed to handle this situation, however I cannot make it work. The action tries to assign `draftName` to newly created entry and fails with error.

### Steps to reproduce

1. Submit a form with `title`, `slug`, `draftName` and optionally some field values to `entry-revisions/save-draft` action. Do not provide draft ID and entry ID.
2. See error:

```
2021-11-15 16:06:26 [-][3][4accd7dd445d9f9ba5061efd82eddb8a][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Setting unknown property: craft\elements\Entry::draftName in /app/vendor/yiisoft/yii2/base/Component.php:210
Stack trace:
#0 /app/vendor/craftcms/cms/src/base/Element.php(1751): yii\base\Component->__set('draftName', 'Temp Draft Name')
#1 /app/vendor/craftcms/cms/src/controllers/EntryRevisionsController.php(669): craft\base\Element->__set('draftName', 'Temp Draft Name')
#2 /app/vendor/craftcms/cms/src/controllers/EntryRevisionsController.php(220): craft\controllers\EntryRevisionsController->_setDraftAttributesFromPost(Object(craft\elements\Entry))
#3 [internal function]: craft\controllers\EntryRevisionsController->actionSaveDraft()
#4 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /app/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#6 /app/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('save-draft', Array)
#7 /app/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction('entry-revisions...', Array)
#8 /app/vendor/craftcms/cms/src/web/Application.php(596): craft\web\Application->runAction('entry-revisions...', Array)
#9 /app/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#10 /app/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#11 /app/web/index.php(21): yii\base\Application->run()
#12 {main}
```
NOTE: if `draftName` is not provided, it fails because it tries to get this property from Entry.

### Additional info

- Craft version: Craft Pro 3.7.19.1
- PHP version: 7.3.30
- Database driver & version: PostgreSQL 13.4
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting that. Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.21 is out now with that fix. Thanks again!
