### ISSUE TITLE
Uri:s of nested entries aren't updated when changing parent slug

### ISSUE THREAD

**Issue by jimyhse** [craftcms/cms#10094]
### Description
We have a structure section where Entry URI Format is set to '{parent.uri}/{slug}'. When we are changing the slug of a parent entry, the uri:s of the child entries aren't updated. When we're saving the parent entry a second time, the background job "Updating element slugs and URIs" is triggered and the child entry uri:s are updated.

Shouldn't the background job "Updating element slugs and URIs" always trigger when a slug is updated?

### Steps to reproduce
1. Create a Structure section with Entry URI Format is set to '{parent.uri}/{slug}'
2. Create a page structure like this;
![slug1](https://user-images.githubusercontent.com/91942722/141947174-a7b6b865-0a0c-4026-b6b8-3df50db99ce9.png)

3. Change the slug of the parent page. In the following example I changed it from "parent-page" to "parent-page-renamed", and as you can see, the child uri:s aren't updated;
![slug2](https://user-images.githubusercontent.com/91942722/141947430-8ee9ae58-752e-4a6a-833a-63b381f8a5c6.png)

4. Save the parent page (without updating any properties) and the child uri:s will be updated (after the background job "Updating element slugs and URIs" has been run);
![slug3](https://user-images.githubusercontent.com/91942722/141948655-3d39d41d-4bbc-4bfb-a00c-4f9ba0a806b5.png)

### Additional info

- Craft version: 3.7.20
- PHP version: PHP 7.4
- Database driver & version: MariaDB 10.5.3, MySQL 8.0.26
- Plugins & versions: Neo 2.11.17, Redactor 2.8.8

**Comment by brandonkelly** [comment]
Thanks for reporting that. Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.21 is out now with that fix.

**Comment by jimyhse** [comment]
Wow, that was fast. Thank you.
