### ISSUE TITLE
structureId queries for Singles not required

### ISSUE THREAD

**Issue by ostark** [craftcms/cms#10095]
### Description

When querying Singles, Craft queries the `sections` table to get the `structureId`. If I understand the code correctly (maybe I do not), this additional query is not needed. 

Related PR: https://github.com/craftcms/cms/pull/10096

#### Example EntryQuery 
```twig
{% set bikesLanding = craft.entries({ section: 'bikesLanding' }).one() ?? null %}
```

#### Example query with spoke-and-chain demo
```sql
SELECT `structureId`
FROM `sections`
WHERE (`id`='8') AND (`type`='structure')
LIMIT 1
```

### Additional info

- Craft version: 3.6
- PHP version: 8.0
- Database driver & version: Mysql 8.0

**Comment by ostark** [comment]
At least in this scenario `$this->withStructure` becomes `false`

https://github.com/craftcms/cms/blob/develop/src/elements/db/EntryQuery.php#L292-L303

1) Filtered by `section`
2) No value for structureId in section
3) $this->withStructure = false

---

The change saved about 10 queries on the home page of the demo site.

**Comment by brandonkelly** [comment]
Ah right. Well I did add a similar change in my commit (`$this->withStructure !== false`). Better than `=== true` because it can also be set to `null` which is a “maybe”.

**Comment by brandonkelly** [comment]
Craft 3.7.21 is out now with that change.
