### ISSUE TITLE
Entry categorization overhaul

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1009]
> Created by: Christian (seelbach@gmx.de) on 2015/03/09 00:49:13 +0000
> Votes at time of UserVoice import: 5

-----------------------------------

I would really appreciate it if the implementation of the “Entry Type” switch in Edit Entry pages and the categorization of entries in general would get an overhaul.

Maybe the solution could be a new top bar with “Entry Type”, “Locales” and “Revisions” fields. Or a dedicated block in the sidebar for these related selections, as they basically all three allow to switch between versions of an Entry. It’s a bit cluttered currently.

The main purpose for this feature request though is that I’d like to add my own select fields to this as well.

The “Entry Type” switch is usually used to categorize the entries in cases where you need a different field layout. But sometimes you don’t need a different layout and categorize the entries using one or more Categories fields. But the CMS user probably doesn’t care that much what kind of tech is used to categorize the entry, all they want is to define the categories.

Can we please have a unified place in Edit Entry pages for all our categorization needs? Thank you.

**Comment by brandonkelly** [comment]
Closing this in favor of #4175
