### ISSUE TITLE
Error when listing caches using `cache/index`

### ISSUE THREAD

**Issue by nickdunn** [craftcms/cms#10097]
### Description
When using the `cache/index` CLI command (or indeed any of the `cache` commands) I get an errror:

```
$ /usr/local/bin/php /var/www/craft/craft cache/index

Error: Calling unknown method: craft\console\Request::getIsSecureConnection()
2021-11-16 11:33:40 [-][-][-][error][yii\base\UnknownMethodException] yii\base\UnknownMethodException: Calling unknown method: craft\console\Request::getIsSecureConnection() in /var/www/craft/vendor/yiisoft/yii2/base/Component.php:301
Stack trace:
#0 /var/www/craft/vendor/craftcms/cms/src/Craft.php(154): yii\base\Component->__call('getIsSecureConn...', Array)
#1 /var/www/craft/vendor/craftcms/cms/src/helpers/App.php(695): Craft::cookieConfig()
#2 /var/www/craft/config/app.php(70): craft\helpers\App::sessionConfig()
#3 [internal function]: craft\services\Config->{closure}()
#4 /var/www/craft/vendor/yiisoft/yii2/di/Container.php(634): call_user_func_array(Object(Closure), Array)
#5 /var/www/craft/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->invoke(Object(Closure), Array)
#6 /var/www/craft/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Object(Closure))
#7 /var/www/craft/vendor/yiisoft/yii2/base/Module.php(748): yii\di\ServiceLocator->get('session', true)
#8 /var/www/craft/vendor/craftcms/cms/src/console/Application.php(158): yii\base\Module->get('session', true)
#9 /var/www/craft/vendor/yiisoft/yii2/console/controllers/CacheController.php(275): craft\console\Application->get('session')
#10 /var/www/craft/vendor/yiisoft/yii2/console/controllers/CacheController.php(54): yii\console\controllers\CacheController->findCaches()
#11 [internal function]: yii\console\controllers\CacheController->actionIndex()
#12 /var/www/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /var/www/craft/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#14 /var/www/craft/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('index', Array)
#15 /var/www/craft/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('index', Array)
#16 /var/www/craft/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('cache/index', Array)
#17 /var/www/craft/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('cache/index', Array)
#18 /var/www/craft/vendor/yiisoft/yii2/console/Application.php(148): craft\console\Application->runAction('cache/index', Array)
#19 /var/www/craft/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(craft\console\Request))
#20 /var/www/craft/craft(23): yii\base\Application->run()
#21 {main}
```

### Additional info

- Craft version: 3.7.19
- PHP version: 8.0.1
- Plugins & versions: these plugins add caches Blitz (latest), SEOMatic (latest), Retour (latest) but I can't see them mentioned in stack traces

**Comment by nickdunn** [comment]
The context for this is I currently call `clear-caches/all` on each deployment of my Docker container so everything starts fresh. In production this isn't ideal because `all` includes asset caches which mean many thousands of thumbnails get trashed and need to be regenerated each time. 

My workaround is to maintain a list of the caches that I _do_ want to clear. But really I've love the `clear-caches/all` command to accept and "except" or "exclude" list so we can opt out of some...

**Comment by ostark** [comment]
Looks like you have a custom session config in `/var/www/craft/config/app.php`.
If this is required (usually it's not), it should live in `/var/www/craft/config/app.web.php`.

**Comment by brandonkelly** [comment]
Looks like you actually ran `cache/index`, not `clear-caches/index`?

**Comment by nickdunn** [comment]
> Looks like you actually ran cache/index, not clear-caches/index?

Yep, based on https://craftcms.com/docs/3.x/console-commands.html#cache-index-default

> `cache/index`
> Lists the caches that can be flushed.

**Comment by nickdunn** [comment]
@ostark yep I'm using this pretty much untouched as I'm using Redis: https://craftcms.com/docs/3.x/config/#redis-example-2

**Comment by brandonkelly** [comment]
@nickdunn Sorry, it must have been early. I thought you had said `clear-caches/index` :)

Yeah move your `session` component definition over to `app.web.php`.

**Comment by nickdunn** [comment]
Ace, that has solved it, thank you.

I was wrongly expecting `cache/index` to list out the various caches that `clear-caches/all` would clear, but now I understand that it outputs the underlying cache _drivers_.

Instead I will take the values of the checkboxes listed on the `/admin/utilities/clear-caches` page and append them onto  `clear-cache/`so I can omit `asset`.

This should get me to the place I need to be — clearing all of the caches without purging transformed assets.

**Comment by brandonkelly** [comment]
Yep, and `clear-caches` or `clear-caches/index` will give you that list of sub-commands as well.
