### ISSUE TITLE
entry-revisions/save-draft action creates regular draft instead of provisional when no entry is specified

### ISSUE THREAD

**Issue by ivanBereznev** [craftcms/cms#10105]
### Description
When `entryId` is specified and `provisional` is set to `1` this action creates a provisional draft for given entry. But when no `entryId` is specified, then it creates an entry and a regular draft for it ignoring `provisional: 1`.

### Steps to reproduce

1. Submit a form to `entry-revisions/save-draft` with `title`, `provisional` and maybe some other fields but without `sourceId` or `entryId` so it will be supposed to create a new entry.
2. Look at the new entry. It has regular draft created instead of provisional one.

### Additional info

- Craft version: Craft Pro 3.7.21
- PHP version: 7.3.31
- Database driver & version: PostgreSQL 13.5
- Plugins & versions:

**Comment by brandonkelly** [comment]
Just fixed this for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.21"` and run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.7.22 is out now with that fix.
