### ISSUE TITLE
Broken autocompletion for $app property in VS Code

### ISSUE THREAD

**Issue by myleshyson** [craftcms/cms#10109]
### Description
VS Code can't handle autocompletion for the static Craft::$app property since intelephense doesn't fully support the @mixin trait yet (it's supposed to but apparently doesn't work properly for trait properties).

I saw #7057 was closed but it looks like the fix was never introduced to core. Could that fix please be added? Half our team uses VS Code and it would be a huge help not just to us, but to everyone, especially given that [this page on the craft site](https://craftcms.com/docs/getting-started-tutorial/environment/editor.html) recommends VS Code. However since a huge chunk of the Craft api is behind that one `$app` property, not having auto completion on it makes any extending-craft-work very unpleasant.

**Comment by brandonkelly** [comment]
It was added, then removed shortly after (88f264d15a537b8ae4b893636774acec3f783a14) for causing problems with PhpStorm. I don’t remember exactly what.

Does VS Code support stub files? If so, this could probably be fixed using a stub.

**Comment by myleshyson** [comment]
It does. So I generated a stub using https://github.com/php-stubs/generator on the `vendor/craftcms/cms/src/Craft.php` class and just manually added that @property tag in the docblock. After placing that file in the root of the project, intelephense picked it up and autocompletion started working. 

TIL about stubs so thanks for that suggestion. 

I guess this is an ok solution for now. Honestly this is probably more of an intelephense issue not fully using the mixin property.

**Comment by brandonkelly** [comment]
Awesome :)

**Comment by jordikroon** [comment]
I just saw this issue as I recently switched to VSCode. Because PHPStorm started to feel buggy and slow since the recent update. The good news is that the suggested fix still works. But it still feels hacky to do.

Any chance to revise this @brandonkelly? The problem is still relevant and VSCode increased in popularity.
