### ISSUE TITLE
Reverting to a revision does not restore related matrix elements

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#10106]
### Description

We're having trouble with matrix field contents not being correctly restored when reverting to an earlier revision. Previewing a revision shows the earlier state of the matrix field (and the fields within it) correctly. However, once the entry is reverted to that revision, the revision appears to be merged in a weird way with the current state of the entry. In particular:

- The sort order of the matrix blocks is not restored (instead, it uses the sort order of the current version).
- Relations (e.g. in assets fields within Matrix blocks) are not restored at all, instead it uses the relations as they are in the current version.
- Plain (text) fields are sometimes restored, sometimes they aren't.
- SuperTable blocks within matrix blocks not being restored at all, or losing their sort order (maybe this one is a SuperTable issue, not sure).

It's difficult to pin down as the issue is not completely consistent. Sometimes, there's a message that the revision content has been merged with the current changes. However, even when I make sure the current version is 'clean' (no current changes, so no provisional draft), the issues above still crop up.

Another thing I've noticed is that the matrix field as a whole is frequently maked as dirty in the interface, and the revisions dropdown displays unsaved changes, even though the matrix field was not modified at all. Maybe the matrix field incorrectly creates a provisional draft which is then merged with the revision in an unexpected way? Just a thought, no idea if it has anything to do with that bug at all.

### Steps to reproduce

1. Create a matrix field with at least two types (one with a plain text field, one with an assets field) and add it to an entry type.
2. Create a new entry and add two blocks to it (one of each type). Input some text in the text field in the first block and select a couple of assets in the second block. Save the entry.
3. Now change the order of the two blocks, change the related assets (delete some, move some, etc) and change the text in the text field. Save the entry again.
4. Now view the previous revision. It should still show the previous version of the matrix blocks correctly (the previous sort order, the previously selected assets, etc).
5. Click on *Revert entry to this revision* and check the matrix field. The matrix blocks will not reflect the restored revision, instead using the sort order and asset relations of the current version. The text may or may not be restored.

### Additional info

- Craft version: 3.7.21
- PHP version: 8
- Database driver & version: MySQL 8
- Plugins & versions: Smith 1.1.14, Super Table 2.6.8

Here's a screen recording demonstrating the issue:

https://user-images.githubusercontent.com/10146880/142181860-feaa0871-4808-4d1e-a1d5-74094e2ea910.mov

**Comment by brandonkelly** [comment]
Any chance you can send in a database backup and your Composer files for this site? support@craftcms.com

**Comment by MoritzLost** [comment]
@brandonkelly Sending a database dump is difficult for legal reasons, due to GDPR I'm not allowed to send personal information to the US, not sure how much I'd have to clean it up.

However, to make absolutely sure it's not related to anything we're doing with our sites, I tried to reproduce the same error in one of the demo sites. I've requested a europa.museum demo and I can reproduce this error even in the demo installation! Before testing this, I updated the demo to the latest Craft version to make sure it's not a bug in a previous version.

Here's a link to the demo installation: https://moving-redbird-a6a9de7.craftdemos.io/

See the screenrecording here, taken directly in this demo site (sorry for the poor quality, had to compress it a bit to fit in the upload limit):

https://user-images.githubusercontent.com/10146880/142598910-93e82cc8-5fa1-4a4f-9a3d-468e11fc4353.mp4

Note that after restoring the previous revision, the matrix blocks aren't returned to that revision's sort order, and the assets selected in the second block aren't restored as well.

Also, why is it creating a provisional draft as soon as the page is loaded, before I have done anyhing to the content? Is that intended? Maybe it's related to this issue?

**Comment by brandonkelly** [comment]
Thanks, just got this fixed for the next release.

> Also, why is it creating a provisional draft as soon as the page is loaded, before I have done anyhing to the content? Is that intended? Maybe it's related to this issue?

I have seen this with Redactor fields, but haven’t come up with a way to reliably reproduce it yet. Seems like the Redactor editor forgets to wrap the content in `<p>` tags from time to time, and if that’s the case, it will fix that by wrapping the value in `<p>` tags on a subsequent page load. Craft will detect that the field value has changed, and create the provisional draft. If you save it immediately when that happens, the corrected value will get saved to the entry, and it won’t happen anymore (at least for now).

**Comment by MoritzLost** [comment]
@brandonkelly Awesome, my clients will be really happy about that fix! 🚀 

Thanks for the insights regarding the Redactor field. Good to know what's causing this, now I can tell my clients how to avoid this if it crops up. By the way, I've also noticed that sometimes the Redactor output doesn't include a `<p>` tag (not while it's in inline mode). That's a bit difficult to handle in templates, and if it's also causing the issue with provisional drafts – maybe this needs to be fixed in Redactor itself?

Anyway, thanks a lot!

**Comment by brandonkelly** [comment]
> By the way, I've also noticed that sometimes the Redactor output doesn't include a <p> tag (not while it's in inline mode).

That’s exactly the bug I’m seeing, which cases the autosave issue. Looks like it’s already been reported: https://github.com/craftcms/redactor/issues/307

**Comment by brandonkelly** [comment]
Craft 3.7.22 is out now with that fix.
