### ISSUE TITLE
Saving taking a long time

### ISSUE THREAD

**Issue by rstix** [craftcms/cms#10119]
### Description
Our client is recently complaining about saving time for entries. I tested myself and it usually takes around 30 seconds to save after subtle change, also sometimes it exceeds response time and runs into an error. 

I tried to sex max revisions to 0, but it did not help. Also we implemented some events that are fired when saving so I commented those out but it did not help either.

### Steps to reproduce

To reproduce I can send you our DB and composer files. I think it would be easier for you to test it as we also use Neo plugin and have some elements that are nested into other elements. 

### Additional info

- Craft version: 3.7.21
- PHP version: 7.4.21
- Database driver & version: MySQL 5.5.5
- Plugins & versions: 
Calendar Links. 1.0.1
Contact Form	2.2.7
Feed Me	4.4.0
Isolate	1.4.4
Minify	1.2.10
Mix	1.5.2
Neo	2.11.17
reCAPTCHA	1.5.2
Redactor	2.8.8
Retcon	2.3.0
XML Sitemap	1.3.2

**Comment by brandonkelly** [comment]
We often see save times take a while for entries that have complex content models – lots of nested Matrix/Neo/Super Table blocks. And if the entry belongs to multiple sites, that will compound the problem.

There are a couple things you can do that will help improve save times:

- Disable versioning within the section’s settings
- Disable draft auto-saving, by setting `'autosaveDrafts' => false` in `settings/general.php`

We are working on some changes in Craft 4 that will make saving Matrix fields in particular a lot faster. Neo/Super Table should be able to follow suit as well.

**Comment by rstix** [comment]
Thank you for the tips.
