### ISSUE TITLE
Entry queries with descendantOf parameters don't work correctly in previews

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#10122]
### Description

I'm seeing a similar bug to #5021 – element queries that are using `descendantOf` parameters to find children of the current entry produce empty results in previews. This happens both in the live preview displayed in the entry editor and revision views. Maybe related to #10056 and the recent change that revisions are no longer placed within their structure?

I'm using the following code to display a list of child entries. It works fine for the live entry, but gives an empty result both in the live preview and the revision view.

```twig
{% set entries = craft.entries().section(entry.section.handle) %}
{% do entries.descendantOf(entry).descendantDist(1) %}
{% dd entry.all() %} {# [] #}
```

I tried to debug the query by checking the raw SQL, but I'm getting a `Query Aborted Exception`:

```twig
{% dd entries.getRawSql() %}
```

Full strack trace below.

### Steps to reproduce

1. Use the code above in the template for a entry of a structure section with at least one level of hierarchy. The code should display all child entries of the current entry.
2. View the live entry. The query should return all the child entries. Now view a preview (revision view or live preview). Executing the query with `.all()` will return an empty array, while debugging the query with `.getRawSql()` will result in a `QueryAbortedException`.

### Additional info

- Craft version: 3.7.21
- PHP version: 8
- Database driver & version: MySQL 8

Here's the related stacktrace from the log:

```
2021-11-19 11:09:42 [-][16][jkmo4ho58calnjtcerhd3vriut][error][craft\db\QueryAbortedException] craft\db\QueryAbortedException in [...]/vendor/craftcms/cms/src/elements/db/ElementQuery.php:2795
Stack trace:
#0 [...]/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2539): craft\elements\db\ElementQuery->_normalizeStructureParamValue('descendantOf', 'craft\\elements\\...')
#1 [...]/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1539): craft\elements\db\ElementQuery->_applyStructureParams('craft\\elements\\...')
#2 [...]/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#3 [...]/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build(Object(craft\elements\db\EntryQuery))
#4 [...]/vendor/craftcms/cms/src/db/Query.php(249): yii\db\Query->createCommand(Object(craft\db\Connection))
#5 [...]/vendor/twig/twig/src/Extension/CoreExtension.php(1511): craft\db\Query->getRawSql()
#6 [...]/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\db\EntryQuery), 'getRawSql', Array, 'method', false, false)
#7 [...]/storage/runtime/compiled_templates/ed/ed5e2508a929a3d45fabc1ffb46e59fdf6f77994f2d0487c17359cea604adda8.php(75): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\db\EntryQuery), 'getRawSql', Array, 'method')
#8 [...]/vendor/twig/twig/src/Template.php(405): __TwigTemplate_9837c5c34c67c931a42a990f78c3d1dd87f1abb8ea67ff92d33d3b07bf7ae802->doDisplay(Array, Array)
#9 [...]/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#10 [...]/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#11 [...]/vendor/twig/twig/src/Extension/CoreExtension.php(1235): Twig\Template->render(Array)
#12 [...]/storage/runtime/compiled_templates/37/378ddaabb682e433bb4058f06acd94e4ef668c7e5f829e929a4e73d48163d713.php(203): twig_include(Object(craft\web\twig\Environment), Array, 'sections/blocks...', Array, false, true)
#13 [...]/vendor/twig/twig/src/Template.php(405): __TwigTemplate_580f30ab33e71f7f638bbcaeebb92d46ca2c0a72f090a0c6b4ae0dfbc321eab7->doDisplay(Array, Array)
#14 [...]/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#15 [...]/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#16 [...]/vendor/twig/twig/src/Extension/CoreExtension.php(1235): Twig\Template->render(Array)
#17 [...]/storage/runtime/compiled_templates/a2/a2f87bd82fb6c43c89f40d6d4780eb2db426f918f169bffb9820ccd82c8ede7e.php(175): twig_include(Object(craft\web\twig\Environment), Array, 'sections/sectio...', Array)
#18 [...]/vendor/twig/twig/src/Template.php(182): __TwigTemplate_febc4505ba9c07f5b1904e07a496d09d7ef0d38bd633dc1ea4337d8b30f93290->block_content(Array, Array)
#19 [...]/storage/runtime/compiled_templates/af/af3ab68c4cd5aff35c2d6dc540f9abcb21931027e8e3fa7b90ce77768d20cdd5.php(130): Twig\Template->displayBlock('content', Array, Array)
#20 [...]/vendor/twig/twig/src/Template.php(405): __TwigTemplate_9f89bb9617b427ba36a72f0a9252cd7500cbd58e03c5cd9047722b223ce43f44->doDisplay(Array, Array)
#21 [...]/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#22 [...]/storage/runtime/compiled_templates/a2/a2f87bd82fb6c43c89f40d6d4780eb2db426f918f169bffb9820ccd82c8ede7e.php(51): Twig\Template->display(Array, Array)
#23 [...]/vendor/twig/twig/src/Template.php(405): __TwigTemplate_febc4505ba9c07f5b1904e07a496d09d7ef0d38bd633dc1ea4337d8b30f93290->doDisplay(Array, Array)
#24 [...]/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#25 [...]/storage/runtime/compiled_templates/93/93e89fa01f2ac66b5100e4d6811a6e60fe343bb0ad9f050aeab02320c046d6f8.php(43): Twig\Template->display(Array, Array)
#26 [...]/vendor/twig/twig/src/Template.php(405): __TwigTemplate_19a2619bd1e27d69377fbb828e5042af61f1ecb863318a5dbe0c58e4327a1246->doDisplay(Array, Array)
#27 [...]/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#28 [...]/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#29 [...]/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#30 [...]/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#31 [...]/vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render('entries/page', Array)
#32 [...]/vendor/craftcms/cms/src/web/View.php(461): craft\web\View->renderTemplate('entries/page', Array)
#33 [...]/vendor/craftcms/cms/src/web/Controller.php(201): craft\web\View->renderPageTemplate('entries/page', Array, 'site')
#34 [...]/vendor/craftcms/cms/src/controllers/TemplatesController.php(102): craft\web\Controller->renderTemplate('entries/page', Array)
#35 [internal function]: craft\controllers\TemplatesController->actionRender('entries/page', Array)
#36 [...]/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#37 [...]/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#38 [...]/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('render', Array)
#39 [...]/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction('templates/rende...', Array)
#40 [...]/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('templates/rende...', Array)
#41 [...]/vendor/craftcms/cms/src/web/Application.php(272): yii\web\Application->handleRequest(Object(craft\web\Request))
#42 [...]/vendor/craftcms/cms/src/controllers/PreviewController.php(155): craft\web\Application->handleRequest(Object(craft\web\Request), true)
#43 [internal function]: craft\controllers\PreviewController->actionPreview('craft\\elements\\...', 1172690, 1, NULL, 172282, false)
#44 [...]/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#45 [...]/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#46 [...]/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('preview', Array)
#47 [...]/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction('preview/preview', Array)
#48 [...]/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('preview/preview', Array)
#49 [...]/vendor/craftcms/cms/src/web/Application.php(272): yii\web\Application->handleRequest(Object(craft\web\Request))
#50 [...]/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#51 [...]/web/index.php(29): yii\base\Application->run()
```

**Comment by brandonkelly** [comment]
After updating to 3.7.19+, did you run the following command for each of your Structure sections?

```php
php craft utils/repair/section-structure <sectionHandle>
```

**Comment by MoritzLost** [comment]
@brandonkelly Yes, I did – ran it again now, just to make sure, but I'm still seeing the same behaviour. Opening the live preview of a canonical entry works and show the listing with the child entries correctly. But as soon as something is changed, the children are no longer found, so the listing is empty:

![listing-canonical](https://user-images.githubusercontent.com/10146880/142832879-f450e5bf-2b44-44a8-841f-941d1a95bdd1.png)
![listing-provisional-draft](https://user-images.githubusercontent.com/10146880/142832887-2f8b76ff-f2a8-48c8-844f-3311a91be23c.png)

For revisions, the children aren't found either. Any other ideas what might be causing this?

Here's the full code used for the entry query, just in case I'm missing something obvious:

```twig
{% set entries = craft.entries().section(entry.section.handle) %}
{% do entries.descendantOf(entry).descendantDist(1) %}
{% set entries = entries.all() %}
```

I'm seeing the same behaviour when using `level()` instead of `descendantDist()`:

```twig
{% set entries = craft.entries().section(entry.section.handle) %}
{% do entries.descendantOf(entry).level(entry.level + 1) %}
{% set entries = entries.all() %}
```

**Comment by olets** [comment]
I'm seeing something that might be another symptom of the same bug:

I have a template that can use data from a parent:

```twig
{% set baseEntry = entry.level == 2 ? entry.parent : entry %}
```

In live preview, that breaks as soon as I make any change to the content. After making a change, I'll get things like

> Impossible to access an attribute ("title") on a null variable.
> 1. in myfile.twig
> …
> {{ baseEntry.title }}

To clear the error I have to save the entry.

---

3.7.21 after running utils/repair/section-structure on the section

**Comment by brandonkelly** [comment]
Was able to reproduce and get this fixed for today’s release.

@olets Yep that sounds like the same underlying bug.

**Comment by MoritzLost** [comment]
@brandonkelly Awesome, thanks! 🎉 🚀

**Comment by brandonkelly** [comment]
Craft 3.7.22 is out now with that fix. Thanks all!

**Comment by MoritzLost** [comment]
@brandonkelly I just updated to Craft 3.7.22, but I'm still seeing the same issue. Still with the same code above, previews of provisional drafts and revisions get an empty array for the query using `descendantOf` above, while the live version shows the children correctly. Tried clearing all caches and running the repair command again, but that didn't fix it. Could you take another look? Thanks!

**Comment by brandonkelly** [comment]
@MoritzLost Interesting… I was able to reproduce the original issue, and the change in 1cbc35f7a7827764b4dec9041e4c7998f126e8ab fixed it for me.

Any chance you can send your Composer files, database backup, and template files over to support@craftcms.com? We can try to look into it further from there.

**Comment by MoritzLost** [comment]
@brandonkelly I can't send the database dump for this site due to GDPR unfortunately. But I think I know where the issue is now!

The problem is the `entry` variable, which in my code above isn't the draft/revision as provided to the entry template, but the canonical entry. So this is why the query is returning no results, and why the issue was difficult to reproduce.

A bit of background: We're using matrix fields as a content builder. One of those blocks is a navigation menu that displays a list of links to all children of the current entry. However, the matrix block templates don't have access to the outer scope, so we were accessing the entry in the block template like this:

```twig
{% set entry = block.getOwner() %}
```

This always returns the canonical entry, not the draft, even in a preview of a draft/revision. If I instead pass the `entry` variable from the entry template to the matrix block (or access it via `craft.app.getUrlManager().getRouteParams().variables.entry`), the query works correctly even in previews. For now, this is a good solution for my current problem.

Not sure if this behaviour is a bug or intended behaviour. Maybe the matrix blocks should return the draft/revision being previewed for `getOwner()`? Let me know if I should open another issue for this!

**Comment by brandonkelly** [comment]
@MoritzLost How exactly is `block` defined?

**Comment by MoritzLost** [comment]
@brandonkelly Sorry, forgot to mention that. The block variable is a `MatrixBlockElement`:

```twig
{# sections/sections.twig #}
{% set sections = clone(entry.sections).all() %}
{% for block in sections %}
    {{ include('sections/blocks/block--navigation', {
        block: block,
    }) }}
{% endfor %}

{# sections/blocks/block--navigation.twig #}
{% set entry = block.getOwner() %}
```

The `entry` variable here is provided by Craft to the template, so in previews it's a draft or revision. `sections` is the matrix field. Should the blocks accessed through the draft/revision return that same draft/revision for `getOwner()`?

**Comment by brandonkelly** [comment]
Thanks! I was able to reproduce that, and just got it fixed for the next release.

**Comment by MoritzLost** [comment]
@brandonkelly So `block.getOwner()` will return the revision/draft the block belongs to after this change is live? That's great, thanks!

**Comment by brandonkelly** [comment]
`block.getOwner()` is already returning the draft as expected. The problem is that the draft doesn’t actually have any descendants itself; only the canonical entry does. So now `descendantOf` and other structure query params will ensure they are working with the canonical element when a draft is passed to them.

**Comment by MoritzLost** [comment]
@brandonkelly Got it, thanks for the explanation!

**Comment by brandonkelly** [comment]
Craft 3.7.24 is out with that fix. Thanks again!
