### ISSUE TITLE
Error on section delete when section is generated using API

### ISSUE THREAD

**Issue by matfish2** [craftcms/cms#10123]
### Description

I have initially appended this to #5438.
When trying to delete a section, or a category/tag group that was generated using the API, I often get a `Trying to get property of null` error. I get the same result for trying to delete via CP or API.

Error stems from `Sections.php:1136`:

```
$section = $this->getSectionByUid($data['section']);
```

$data is set on line 1130:

```
  $data = $event->newValue;
```

I dumped $event and `newValue` is null

### Steps to reproduce

The issue is inconsistent, so not sure yet what are the exact conditions.
 
1. Create a section using API:

```php
$section = new Section([
            'name' => $name,
            'handle' => $handle,
            'type' => $type,
            'siteSettings' => [
                new Section_SiteSettings([
                    'siteId' => Craft::$app->sites->getPrimarySite()->id,
                    'enabledByDefault' => true,
                    'hasUrls' => true,
                    'uriFormat' => $url,
                    'template' => $template,
                ]),
            ]
        ]);

Craft::$app->sections->saveSection($section);
```
2. Try to delete it via CP or API:
```php
$section = Craft::$app->sections->getSectionByHandle($handle);

if ($section) {
      return Craft::$app->sections->deleteSection($section);
}
```
### Additional info

- Craft version: 3.7.21
- PHP version: 8.0.9
- Database driver & version: MySQL 5.5.5
- Plugins & versions: The plugin I'm writing depends on redactor 2.8.8

**Comment by brandonkelly** [comment]
Are you deleting it within the same request?

If not, is there any code in place that could cause the section-creation request from ending prematurely?

**Comment by matfish2** [comment]
> Are you deleting it within the same request?

No. Section is created in the plugin's `Intsall@safeUp`, and removed when uninstalled on `Install@safeDown`

> If not, is there any code in place that could cause the section-creation request from ending prematurely?

Not that I'm aware of. It is encapsulated within a simple `SectionsService` class:
```php
class SectionService
{

    public function add($name, $handle, $type, $url, $template) : bool
    {
        $section = new Section([
            'name' => $name,
            'handle' => $handle,
            'type' => $type,
            'siteSettings' => [
                new Section_SiteSettings([
                    'siteId' => Craft::$app->sites->getPrimarySite()->id,
                    'enabledByDefault' => true,
                    'hasUrls' => true,
                    'uriFormat' => 'blog' . $url,
                    'template' => 'blogify/' . $template,
                ]),
            ]
        ]);

        return Craft::$app->sections->saveSection($section);
    }

    public function remove($handle) : bool
    {
         $section = Craft::$app->sections->getSectionByHandle($handle);

        if ($section) {
            return Craft::$app->sections->deleteSection($section);
        }

        return false;
    }
}
```
I am not sure if it's relevant but my environment setting is a Laravel Homestead machine with a Windows host.

**Comment by matfish2** [comment]
Closing for now, as I am not able to reproduce. Will revert if necessary.

**Comment by brandonkelly** [comment]
Make sure that the `safeUp()` method is making sure the plugin isn’t already installed in the incoming project config YAML. The plugin could have been installed on another environment already, and the plugin could be getting installed as part of a `project-config/apply` command (along with the section it already created on the dev environment). At that point, if your `safeUp()` method were to try making its own additional changes that impact the project config, it could conflict with those incoming changes. (See  [Project Config Migrations](https://craftcms.com/docs/3.x/extend/project-config.html#project-config-migrations).)

In your case, it should look something like:

```php
public function safeUp()
{
    // Don’t make the same config changes twice
    if (!$this->_pluginExistsInProjectConfig()) {
        $sectionService->add(/* ... */);
    }
}

public function safeDown()
{
    // Don’t make the same config changes twice
    if ($this->_pluginExistsInProjectConfig()) {
        $sectionService->remove(/* ... */);
    }
}

private function _pluginExistsInProjectConfig(): bool
{
    return Craft::$app->projectConfig->get('plugins.<plugin-handle>', true) !== null;
}
```

**Comment by matfish2** [comment]
Thanks. Already had one on `safeUp()` as per docs (https://craftcms.com/docs/3.x/extend/migrations.html#setting-default-project-config-data). Might be a good idea to add `safeDown()` check to docs as well.
