### ISSUE TITLE
Connect matrix blocks to section types

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1012]
> Created by: Pål (peirix@gmail.com) on 2015/07/01 18:09:56 +0000
> Votes at time of UserVoice import: 5

-----------------------------------

A way to allow us to create one matrix field with all our layout modules, but have them be visible for only certain section types. Especially helpful if you have multiple blocks that are common for all section types, and some blocks that are section specific.

**Comment by brandonkelly** [comment]
#1524 addresses the issues here (albeit takes a different direction).
