### ISSUE TITLE
Preview of Un-enabled Page Gives Error

### ISSUE THREAD

**Issue by jimmylorunning** [craftcms/cms#10127]
### Description
When previewing a page that has "enabled" set to off, it gives a 404 not found error.

I'm not sure if this is intentional behavior or not, afterall unenabled pages shouldn't render on a live site. 

However, before the current Craft update, unenabled pages would still show up in preview, and this was useful for my clients, as they could work on a page that is definitely not yet live, but also be able to preview it as they worked on it.

### Steps to reproduce

1. Create a new entry.
2. Under "Enabled", set it so that it is off
3. Click Save entry
4. Open entry again and click Preview

### Additional info

- Craft version: 3.7.21
- PHP version: 7.3.6
- Database driver & version: MySQL 5.7.26
- Plugins & versions:

Control Panel CSS	2.4.0
Control Panel JS	2.4.0
CP Field Inspect	1.2.5
Field Manager	2.2.4
Freeform	3.12.5
Image Resizer	2.1.0
Imager X	v3.5.4
Matrix Field Preview	1.2.3
Redactor	2.8.8
Retour	3.1.67
Snitch	3.0.4.1
Store Hours	2.1.1.1
Super Table	2.6.8
Typogrify 1.1.18

**Comment by brandonkelly** [comment]
This was reported earlier by #10121. Not able to reproduce yet though. If you can add anything to the other issue please do.
