### ISSUE TITLE
The fields setup in my Neo are not indexed by Craft

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#10120]
#### Description
_I am posting this also as a Craft CMS issue. Maybe it could be more related to Craft CMS than to Neo, as the fields used by Neo are just native ones._

The fields setup in my Neo are not indexed by Craft:
- Of course, the fields that are setup in the Neo are searchable (the magnifying glass icon is displaying in each field line of `/admin/settings/fields`);
- This happens both on an old version (`Neo 2.9.7` + `Craft Pro 3.6.14`) than the latest one (`Neo 2.11.18` + `Craft Pro 3.7.21`);
- This happens both on the Craft CP search (from `/admin/entries`) than on my search page on front-end;
- I have resaved all entries twice using `./craft resave/entries` + `./craft resave/matrix-blocks`;
- `optimiseSearchIndexing` setting is untouched from default config;

#### Other information
- Neo version: 2.9.7 & 2.11.18
- Craft version: Craft Pro 3.6.14 & 3.7.21
- Is eager-loading used? No

**Comment by brandonkelly** [comment]
> I have resaved all entries twice using `./craft resave/entries` + `./craft resave/matrix-blocks`

`resave/*` commands will not update the search index by default. You must pass `--update-search-index`.

**Comment by romainpoirier** [comment]
That works 😅 Thank you Brad ! I just still have to figure out why the content isn't automatically indexed while it should (as usual, on Entry save)...

**Comment by brandonkelly** [comment]
It should happen via an “Updating search indexes” job that gets added to the queue after entry save. Are you seeing those?

**Comment by romainpoirier** [comment]
Thank you for pointing this out. I found that I have a cron issue while `runQueueAutomatically` is set to `false`. I have a lot of pending tasks. I'm investigating with the hosting department, and will update later if there's really an issue.

**Comment by brandonkelly** [comment]
Alright, will go ahead and close this for now.
