### ISSUE TITLE
Assets - 'Allow uploading directly to the field' unexpected results

### ISSUE THREAD

**Issue by anchovy** [craftcms/cms#10139]
### Description
By default when adding a new Asset field the option _Allow uploading directly to the field_ is select.
If you upload an image using this direct method '+ Upload a file' and the image already exists in the default location, you don't get prompted to overwrite or rename the new file like you do if you upload a image via the '+ Add an image' option, rather new file is automatically uploaded and renamed.

This can result in multiple images existing for the same image/file causing issues when this needs to be updated across several entries etc.

*Resolution*
a: Default the field to unchecked
b: Allow the default setting to be controlled via a global setting.
c: Use the same logic as per uploading a file via the assets modal where it prompts you to replace of keep both.
 
![image](https://user-images.githubusercontent.com/599005/142966522-2209c5d8-7e3d-4d68-8b0a-adc9a06a9247.png)

### Steps to reproduce

1. Add an asset field, leaving 'Allow uploading directly to the field' checked.
2. On a entry, hit the '+ Add an image' button and upload the file Duke-2.jpg
3. repeat step 2. 
4. View the Asset folder - you'll see the file Duke-2.jpg and the file Duke-2_2021-11-23-031054_hwyw.jpg 
![image](https://user-images.githubusercontent.com/599005/142966030-b4bbd34d-4764-4f6c-bd78-07594b5cc6e3.png).

### Additional info

- Craft version: Craft Pro 3.7.20
- PHP version: 8.0.8
- Database driver & version: MySQL 8.0.27
- Plugins & versions:
Amazon S3	1.3.0
Asset Usage	2.2.1
AsyncQueue	2.3.0
Colour Swatches	1.4.2
Control Panel Nav	3.0.17
CP Field Inspect	1.2.5
Craft Commerce	3.4.6
Feed Me	4.4.0
Field Manager	2.2.4
Freeform	3.12.0
Imgix	2.1.0
LJ Dynamic Fields	3.0.12
Phone Number	1.5.0
Rollbar	1.3.0
Smith	1.1.14
Super Table	2.6.8
Twigpack	1.2.15
Typed link field	1.0.25
User Group Field	1.0.4
Vizy	1.0.8
Width Fieldtype	1.0.7

**Comment by brandonkelly** [comment]
This is working as intended. We can consider adding a “Keep it”/“Replace it” prompt, but will need to think through how permissions play into that. Assets fields make file uploading accessible to users who otherwise may not have permission to upload files to that volume, and allowing them to replace existing files feels like a step too far.

Please [start a new discussion](https://github.com/craftcms/cms/discussions/new?category=ideas) about this and we can discuss the idea from there.
