### ISSUE TITLE
Option to output rgb() and rgba() with opacity from Color Fields

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1013]
> Created by: Visiluna (pjones@visiluna.com) on 2015/06/16 22:04:13 +0000
> Votes at time of UserVoice import: 5

-----------------------------------

Color Fields should have the option to output color values as rgb() and rgba() with an opacity value, not just hexadecimal. 

I currently have to use a plain text field, which introduces an additional margin for error.

**Comment by simonkuran** [comment]
Is this in the works? I think it would be a very useful addition.

**Comment by brandonkelly** [comment]
You can output a `rgb()` value using [getRgb()](https://docs.craftcms.com/api/v3/craft-fields-data-colordata.html#method-getrgb):

```css
background-color: {{ entry.myColorField.getRgb() }};
/* or */
background-color: {{ entry.myColorField.rgb }};
```

**Comment by simonkuran** [comment]
I should have been more specific, is rgba selection support coming anytime soon?

**Comment by brandonkelly** [comment]
No plans currently. Looks like the [Craft Color Picker](https://github.com/lewisjenkins/craft-color-picker) plugin supports alpha though.
