### ISSUE TITLE
Content of Super Table field lost for other site groups on save

### ISSUE THREAD

**Issue by benoitblancquaert** [craftcms/cms#10137]
### Description

I have a multi-language/site Craft CMS setup where the home page uses a Super Table field for the page hero. That field has the following propagation method: "Save blocks to other sites in the same site group".

But unfortunately this doesn't work as it should. The Super Table field is cleared for all other site groups after editing the index section in a site group.

A video to clarify the issue: https://www.loom.com/share/098d0fc13a8843b8ae9d2d0d1f639bb3

Any chance this is a bug in one of the latest versions?

### Steps to reproduce

1. Edit Super Table field (name 'Hero', handle 'fieldHero') and save index entry in site group "A" in language/site "English". (0:00 - 0:25 in Loom video)
2. Check the content of the entry in site group "A", but of the language/site "Dutch".
3. Everything is working as it should. Both languages have their own content. (0:25 - 0:45)
4. Now edit the same entry but in a site/language of another group ("B, C, D, ...") and save it. (0:45 - 1:00)
5. Go back to one of the sites in site group "A" and you will see that the field is empty. (1:00 - 1:20)

### Additional info

- Craft version: 3.7.21
- PHP version: 7.4.25
- Database driver & version: MySQL 8.0.26
- Plugins & versions:
  - Super Table: 2.6.8
  - Other various plugins ...

**Comment by brandonkelly** [comment]
Closing this as it appears to be a Super Table bug report, and I see you already found the proper repo for that (https://github.com/verbb/super-table/issues/436).
