### ISSUE TITLE
Clicking Preview on disabled entries results in a 404

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#10144]
### Description

If you open an entry in the CMS and you don't have an active draft (provisional or otherwise) and that entry is disabled, clicking the "Preview" button or the "View -> Primary entry page" button results in a URL with a token, but is still not accessible and results in a 404.

### Steps to reproduce

1. Create a new entry that's disabled
2. Ensure you're not on a draft and click Preview

### Additional info

- Craft version: Craft CMS 3.7.21
- PHP version: 8.0.10
- Database driver & version: MySQL 5.5.5
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
That was reported by #10121, and we just released Craft 3.7.22 with a fix :)
