### ISSUE TITLE
Create new child action for Categories bug

### ISSUE THREAD

**Issue by olivierbon** [craftcms/cms#10148]
### Description

Create new child action for Categories on **multisite install** seems to be broken.

It generates `/admin/categories/groupHandle/new/siteHandle?parentId=15`
instead of `admin/categories/groupHandle/new?site=siteHandle&parentId=15` as a URL which returns a `404 Template not found: categories/groupHandle/new/default`

### Additional info

- Craft version: 3.7.22

**Comment by brandonkelly** [comment]
Fixed!
