### ISSUE TITLE
Can't create an entry with a / (slash) in the title

### ISSUE THREAD

**Issue by arifje** [craftcms/cms#10146]
Currently you can't create an entry that has a / (slash) in the title. The page returns an error after saving:

![Screenshot 2021-11-23 at 19 51 07](https://user-images.githubusercontent.com/1286410/143086449-4c3d7882-0c3a-4a3b-a6b6-aa22537f4ba2.png)

The entry is created though, but can't be edited.

PHP version | 7.4.12
Linux 5.4.0-52-generic
MySQL 8.0.27
Craft Pro 3.7.18.2

**Comment by brandonkelly** [comment]
What are the exact steps to reproduce this? I’m not sure how to reproduce.

**Comment by arifje** [comment]
![Screenshot 2021-11-23 at 19 50 49](https://user-images.githubusercontent.com/1286410/143130118-c3a20ad1-98e2-4bb6-8626-38e3def21710.png)

This is all :-)

Maybe something with rewriting on server level? Just crossed my mind...

**Comment by brandonkelly** [comment]
What does your Slug get set to when you do that? (The slug is what would end up being part of the edit URL, not the title.)

**Comment by arifje** [comment]
The url and slug of the example entry is: 

```
/cp/entries/media/1915763-test%20entry%20with%20a%20slash%20/%20in%20it?site=default
```

But you pointed me to the cause: we're using a plugin "Slug equals title" (https://github.com/internetztube/craft-slug-equals-title). When I disable it, the issue is gone and everything works fine. 

Will create an issue there. Thanks! :-)

**Comment by brandonkelly** [comment]
Aha, good catch. That plugin must be circumventing slug validation somehow, because Craft won’t let you save a `/` in the slug.
