### ISSUE TITLE
Can't create and edit Image Transform

### ISSUE THREAD

**Issue by JorritDiepstraten** [craftcms/cms#10150]
### Description
Create a new Image Transform. Always the same error message ("That is not an allowed format") appears, even when saving existing Image Transforms.

### Additional info
Craft version: 3.7.22

**Comment by brandonkelly** [comment]
Thanks for reporting that. Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.23 is out now with that fix. Thanks for reporting!
