### ISSUE TITLE
System requirements missing check

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#10152]
### Description
Hi! The system requirements is not checking if set_time_limit is a valid function. If you use for instance runcloud, this function is disabled by default, end this causes some functions from Craft to stop working.

I think it should be added to the systems requirements check.

**Comment by angrybrad** [comment]
> this causes some functions from Craft to stop working.

Did you actually get an error message, or just run into some request timeouts. Craft only calls that method in a few places it suppresses any PHP warnings if it's not available.

Server check already checks if `max_execution_time` is set to 120 seconds or more... was that flagged as a warning for you?

**Comment by lenvanessen** [comment]
@angrybrad it breaks the file upload! Did not check where exactly, but if you toss in a new file, and set_time_limit is in disallowed_functions:
![Schermafbeelding 2021-11-27 om 09 53 10](https://user-images.githubusercontent.com/23024452/143674934-5dc028df-7b9c-45ff-bc42-335b88437ad6.png)

**Comment by angrybrad** [comment]
Thanks for that, @lenvanessen. Fixed it in Craft so that it will gracefully handle if that function is disabled for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.24 is out now with that fix. Thanks again!
