### ISSUE TITLE
Can't specify asset options on a per-file basis as of 3.7.22

### ISSUE THREAD

**Issue by mark-adigital** [craftcms/cms#10154]
### Description
I maintain the Cookie Consent Banner plugin, and as of Craft 3.7.22 there was [an issue](https://github.com/a-digital/cookie-consent-banner/issues/37) reported relating to the plugin's asset bundle conflicting with the new `_updateResourcesPaths()` and `_prependDevServer()` [methods](https://github.com/craftcms/cms/blob/develop/src/web/AssetBundle.php#L49).

The asset bundle includes one CSS and one JS file and has settings for whether these should be pre-loaded or with async/defer respectively, and these options were passed through as `$this->js` and `$this->css` arrays with the first items being the file paths per the [Yii documentation](https://www.yiiframework.com/doc/api/2.0/yii-web-assetbundle#$js-detail). I've patched my plugin to pass the CSS and JS options through as the separate arrays `$this->cssOptions` and `$this->jsOptions` to resolve the issue, though this does mean that all assets have the same options applied (not really an issue in this particular case seeing as there's only one of each).

To minimise potential disruption with and constraints on other asset bundles, I think the new methods would benefit from being amended to check whether `$this->js` or `$this->css` are an array rather than string, and pass the first item to `_prependDevServer ()` if so. Thanks!

**Comment by nfourtythree** [comment]
Hi @mark-adigital 

Thank you for bringing this to our attention!

We have pushed a fix for this to be able to handle all possible scenarios for `$this->js` and `$this->css` as documented by Yii.

This fixed will be included in the next release of Craft. Once that is out you will be able to revert your changes (if you wish), although as you mentioned it doesn't really impact your particular use case.

Thanks!

**Comment by mark-adigital** [comment]
No worries @nfourtythree - thanks for the fix!

**Comment by brandonkelly** [comment]
Craft 3.7.23 is out now with that fix. Thanks again for reporting!
