### ISSUE TITLE
Craft 3.7.22 looking for misspelled craft.css file in cpresources

### ISSUE THREAD

**Issue by marflow** [craftcms/cms#10159]
### Description

Update to 3.7.22 is fine on local Mac but after transfer to live site the Admin can´t find the `craft.css` file. Reason: Craft 3.7.22 is looking for a file `Craft.css`.  Changing the `c` into a `C` on the file name in the cpresources folder is the temporary fix.

**Comment by brandonkelly** [comment]
Hey Wolfram!

The file did actually have a capital `C`: https://github.com/craftcms/cms/blob/92a151c6dfaa74d7fbd843b1b101ffa5cc30abef/src/web/assets/cp/dist/css/Craft.css

The casing had changed in 3.7.22 though, and perhaps something in your workflow prevented the name change from taking place – e.g. perhaps you are committing your whole `vendor/` folder to Git and Git didn’t pick up on the filename change (as it doesn’t by default for case-insensitive file systems).

We’ve just released 3.7.23 with the file renamed it to `cp.css`, so you definitely won’t see it happen going forward.

**Comment by marflow** [comment]
Hi Brandon,

Thanks for the fix and the explanation of the possible error. You are right I was committing the whole git folder / changes, so that could have been a problem. But: I then removed the complete cpresources folder on the live server and the live Craft 3.7.22 system generated everything again with small first letters. Maybe this info was somewhere in a cache? Anyway perfect you made it safe for me :)

**Comment by brandonkelly** [comment]
The file system issue would have occurred within Craft’s source files (`vendor/craftcms/cms/src/web/assets/cp/dist/`), not within the `cpresources/` folder.
