### ISSUE TITLE
GraphiQL explorer empty after update to 3.7.22

### ISSUE THREAD

**Issue by andreasottosson** [craftcms/cms#10153]
### Description
After updating to 3.7.22 today in  GraphiQL the explorer just displays "NO SCHEMA AVAILABLE". It does not matter which shema I choose in the dropdown menu.

Autocompletion works though.

### Steps to reproduce

1. Upgrade to Craft 3.7.22
2. Use the build in GraphiQL tool
3. No schema is available in "Explorer"
4. Downgrade to 3.7.21 solves the issue

### Additional info

- Craft version: 3.7.22
- PHP version: 7.3.31
- Database driver & version: MySQL 5.6.51
- Plugins & versions:
    Cloner 1.2.2
    Donkeytail 2.0.5
    Neo 2.11.19
    Redactor 2.8.8
    Smith 1.1.14
    Sprout Notes 2.2.3
    Tags 1.0.9

**Comment by teamteak** [comment]
Getting the same issue, "NO SCHEMA AVAILABLE"

**Comment by andris-sevcenko** [comment]
Looking into this!

**Comment by andris-sevcenko** [comment]
This has been fixed for the next release.

Also, while at it, we improved the initialization times for the GraphiQL IDE, too!

**Comment by andreasottosson** [comment]
That's great! 👍🏻

**Comment by brandonkelly** [comment]
Craft 3.7.23 is out now with that fix. Thanks for reporting!
