### ISSUE TITLE
GraphiQL schema introspection is broken since 3.7.22

### ISSUE THREAD

**Issue by Zsavajji** [craftcms/cms#10166]
Hi, 
the GraphiQL explorer seems to be not working since the 3.7.22 update. It executes the Introspection Query, and then executes a query with {} as payload, which obviously throws a ` errors: [{message: "No GraphQL query was supplied"}]`.

Thanks

### Steps to reproduce

1. Use GraphiQL explorer to inspect fields
2. Update to 3.7.22
3.  No Schema available in explorer

### Additional info

- Craft version: 3.7.22
- PHP version: 7.4 / 8.0
- Database driver & version: MariaDB  10.3.31 / 10.5

**Comment by andris-sevcenko** [comment]
Thanks for reporting that! This issue has actually already been covered by #10153, and it’s been fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.23 is out now with that fix. Thanks again for reporting!
