### ISSUE TITLE
New field's config yml is deleted after adding that field to a section

### ISSUE THREAD

**Issue by roelvanhintum** [craftcms/cms#10164]
### Steps to reproduce

1. Create a new field (project config yml is created e.g. `config/project/fields/body--945efc10-c515-4abe-8b2c-ed9390f82ab5.yaml`)
2. Add that field to an existing section (the new field's yml is gone, the field is referenced to from section type's yml)
3. After modifying the field, the yml file re-appears

### Additional info

- Craft version: Craft Pro 3.7.22
- PHP version: 8.0
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
  - Asset Usage	2.2.1
  - Buckaroo for Craft Commerce	1.1.0.1
  - Craft Commerce	3.4.7
  - fortrabbit Object Storage Volume	2.1.0
  - Linkit	1.1.12.1
  - Maps	3.9.2
  - Redactor	2.8.8
  - Sentry SDK	1.1.2
  - SEOmatic	3.4.20
  - Super Table	2.6.8
  - Two-Factor Authentication	2.10.0
  - Vite	1.0.17

**Comment by andris-sevcenko** [comment]
Can you try clearing your Craft caches and see if that fixes it?

**Comment by roelvanhintum** [comment]
I haven't seen this happen since.
