### ISSUE TITLE
Structure entries with "level" variable in URI format saved with wrong URI in other sites

### ISSUE THREAD

**Issue by smcyr** [craftcms/cms#10165]
### Description

The suffix specified in the condition `if level == 1` the URI format for a structure section (`{% if level == 1 %}some-base-url{% else %}{parent.uri}{% endif %}/{slug}`) is not there for the other sites of an entry when the entry is saved. The task `Updating element slugs and URIs` seem to be missing the variable "level" for the entry in the other sites. 

I tested on a blank CraftCMS project with only two sites, one structure section and two entries and was able to replicate the same bug that we have on another more complex project. And the error arrives on both MariaDB and PostgreSQL.

Also, the bug seem somewhat recent, as we didn't have the problem with some anterior Craft version.

### Steps to reproduce

1. Create at least two sites
2. Create a structure section with this URI format: `{% if level == 1 %}some-base-url{% else %}{parent.uri}{% endif %}/{slug}`
3. Create an entry with a child entry
4. Save the entry at level 1 in one site with a new slug
5. Switch the site
6. Now, the two entries don't have "some-base-url" at the beginning.

You can see the steps in those screenshots:

![Screenshot 2021-11-25 134500](https://user-images.githubusercontent.com/664920/143489731-f2e7e445-b3f9-44e4-83ef-c1d3abca4d5a.png)
![Screenshot 2021-11-25 134519](https://user-images.githubusercontent.com/664920/143489733-d5038e80-9778-4c84-b0e9-a5f640c67c28.png)
![Screenshot 2021-11-25 134538](https://user-images.githubusercontent.com/664920/143489735-c1a7ce40-c4da-47d1-b785-5db9b871fd65.png)
![Screenshot 2021-11-25 134550](https://user-images.githubusercontent.com/664920/143489737-048cdfbe-1aed-43a5-b984-865304ab81fc.png)
![Screenshot 2021-11-25 134607](https://user-images.githubusercontent.com/664920/143489738-ae6d32c0-a8c7-4fe4-8b90-1902e16d21bf.png)

### Additional info

- Craft version: 3.7.22
- PHP version: 7.4.24
- Database driver & version: PostgreSQL 10.17
- Plugins & versions:

**Comment by smcyr** [comment]
Upon further inspection, the problem seems to come from method `duplicateElement` inside `Elements.php`. The `$siteClone` variable has a `structureId` of null, but it should be `'1'`. If I add this line, it works:
```
$siteClone->structureId = $mainClone->structureId;
```
It's because if the entry has no `structureId`, it won't have the `level` attribute when you do `$object->attributes()` in `renderObjectTemplate`.

**Comment by brandonkelly** [comment]
Thanks for reporting that, and investigating! Just fixed for the next release, which we’ll get out today.

**Comment by brandonkelly** [comment]
Craft 3.7.23 is out now with that fix. Thanks again for reporting!
