### ISSUE TITLE
Entry meta hook is rendered before parent meta

### ISSUE THREAD

**Issue by matfish2** [craftcms/cms#10172]
https://github.com/craftcms/cms/blob/cba3ce84828100b009e1b6f8f4e318cb0b30cce6/src/templates/entries/_edit.html#L137-L141

I think the correct behavior would be to render it after the parent:

```
{% block meta %}
    {{ parent() }}
    {# Give plugins a chance to add other things here #}
    {% hook "cp.entries.edit.meta" %}
{% endblock %}
```

**Comment by brandonkelly** [comment]
Yeah agreed. Not sure why there was a break in consistency there. Also affected the Edit Asset and Edit Category pages, but those were probably just due to copy/pasting template code. Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.24 is out now with that change. Thanks for pointing it out!

**Comment by matfish2** [comment]
Seem to have been removed on Craft 4? Is there an alternative?

**Comment by brandonkelly** [comment]
You can use [EVENT_DEFINE_SIDEBAR_HTML](https://docs.craftcms.com/api/v4/craft-base-element.html#event-define-sidebar-html) to append additional content to element editor sidebars in Craft 4.

```php
use craft\base\Element;
use craft\elements\Entry;
use craft\events\DefineHtmlEvent;
use craft\helpers\Html;
use yii\base\Event;

Event::on(
    Entry::class,
    Element::EVENT_DEFINE_SIDEBAR_HTML,
    function(DefineHtmlEvent $event) {
        $event->html .= Html::tag('div', 'contents...');
    }
);
```
