### ISSUE TITLE
Exception "The file or directory to be published does not exist: /.../yii2-pjax/dist" thrown in Yii debug bar timeline view

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#10176]
### Description

Since Craft 3.7.22, when opening the Yii debug bar's Timeline view (either on the frontend or in the CP) the following exception is thrown:

`The file or directory to be published does not exist: /path/to/project/vendor/craftcms/cms/src/web/assets/yii2-pjax/dist`

The error does not happen on 3.7.21 or lower (the `jquery.pjax.js` asset is published to cpresources as expected).

Full stack trace [here](https://pastebin.com/Ms30NYkR)

### Steps to reproduce

1. Open the Yii debug bar, on the frontend or in the CP
2. Switch to the "Timeline" view

### Additional info

- Craft version: 3.7.22, 3.7.23
- PHP version: 7.4.25
- Database driver & version: MySQL 5.6
- Plugins & versions: none

**Comment by nfourtythree** [comment]
Hi @mmikkel 

Thank you for bringing this to our attention.

We have just pushed an update that fixes this issue. This fix will be included in the next release of Craft.

Thanks!

**Comment by brandonkelly** [comment]
Craft 3.7.24 is out with that fix. Thanks again!
