### ISSUE TITLE
Console commands outputs info logs when ran through a cron

### ISSUE THREAD

**Issue by ryssbowh** [craftcms/cms#10185]
### Description

I updated a site from Craft 3.7.18.1 to 3.7.21 recently and since then I see emails being sent by the server whenever a cron outputs something (every minute in my case).

The output in question seems to be coming from an Craft::info call there : https://github.com/panlatent/schedule/blob/master/src/console/SchedulesController.php#L75 

Is it an intended behavior to have the info logs outputed there ? Ive had these crons running for a long time and has never seen this before, has something changed in Craft that could explain this ? went through the changelog but couldn't find anything.

### Steps to reproduce

1. Add a console command that logs an info
2. Run the command through a cron

### Additional info

- Craft version: 3.7.21
- PHP version: 8.0
- Database driver & version: Mysql 5.7
- Plugins & versions:
  - panlatent/schedule 0.2.2.1

**Comment by brandonkelly** [comment]
`info` logs are only output when [`devMode`](https://craftcms.com/docs/3.x/config/config-settings.html#devmode) is enabled. Just tested locally and verified that is the case.

That only applies to Craft’s own file logs, stored in `storage/logs/`, though. If you have any custom log targets configured in `config/app.php`, you will need to filter which log levels get collected via their `levels` properties.
