### ISSUE TITLE
Exception "A non well formed numeric value encountered" when saving a Numbers field with a very large max value setting

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#10184]
### Description

When saving a Numbers field with a very large max value setting (for example, `999999999999999`), the field initially saves fine, but upon resaving, an exception "A non well formed numeric value encountered" is thrown. The issue appears to be that commas are inserted in the max value input after the initial save:

![CleanShot 2021-11-30 at 11 54 24](https://user-images.githubusercontent.com/298510/144034482-de3b078d-6059-43f0-a9cb-573193f32fb3.png)

The commas do not appear in the actual field settings JSON in the `fields` database column:

```
{"decimals":0,"defaultValue":null,"max":"999999999999999","min":"0","prefix":null,"previewCurrency":"","previewFormat":"decimal","size":null,"suffix":null}
```

### Steps to reproduce

1. Create a Numbers field, and set the "Max Value" setting to `999999999999999`. Save the field.
2. Re-save the field

### Additional info

- Craft version: 3.7.23
- PHP version: 7.4
- Database driver & version:
- Plugins & versions: none

**Comment by brandonkelly** [comment]
That was a bit of a tricky one, but got it fixed for the next release!

**Comment by mmikkel** [comment]
> That was a bit of a tricky one, but got it fixed for the next release!

Great, thanks!

**Comment by brandonkelly** [comment]
Craft 3.7.24 is out now with that fix.
