### ISSUE TITLE
required matrix

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1019]
> Created by: Mat (mat@francisbond.com) on 2015/04/30 01:22:56 +0000
> Votes at time of UserVoice import: 5

-----------------------------------

Make any field in a matrix block type required rather than specific fields required. EG in a block type 'Section Heading' either 'Heading', 'Subheading' or 'Lede' must be used.

**Comment by brandonkelly** [comment]
This will probably be possible via #805.
