### ISSUE TITLE
Wrong orderBy using variable (Entries field) as title

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#10203]
### Description

`{% set entries = craft.entries.section(entry.type.handle).with(['user', 'tags', 'category']).orderBy('company ASC', 'title ASC') %}`

Where `title` is set from `{user.one().fullName ?? null}` as Entry type title (user get first of Users from an Entries field).
The `company` is correctly set alphabetically, but not the `title` (ie. `First Name` + `Last Name`).
It seems randomly set from the `dateCreated` of the user, or something else, but not from the `fullName` (`First Name` + `Last Name`).

### Additional info

- Craft version: 3.7.24
- PHP version: 7.4.16
- Database driver & version: MySQL 5.7.23

**Comment by brandonkelly** [comment]
Are the titles appearing as expected in the control panel? If you sort entries by their title from the Entries index page, does that work?

**Comment by romainpoirier** [comment]
If I filter by _Entry_, yes it is with the correct title ASC order. But if I click on _Company_, the order based on _Company_ ASC is correct, but the _Entry_  column (_Title_) is not.

Example:

> Title: Jean Dupont
> Company: A Great Company
> Title: Vadim John
> Company: A Sample Company
> Title: John Doe
> Company: A Sample Company

Here the first one is correct, (_A Great Company_ before _A Sample Company_). But the second ordering criteria should be the _Title_. Here _John Doe_ should be before _Vadim John_.

I have already done a `./craft resave/entries --update-search-index` in case of something were wrong, but unfortunately with no effect.

**Comment by brandonkelly** [comment]
Sorry, the issue is just with your `search` param syntax. You are passing `title ASC` as a second argument, but `orderBy` only takes one argument. It should be `.orderBy('company ASC, title ASC')`.

**Comment by romainpoirier** [comment]
Yep I have already updated this, sorry for not having updated my ticket also. Unfortunately, this doesn't fix the issue. As explained in my previous message, the issue is also there from the CP view (so no `orderBy` from my side). The Entry (title) is not fully correctly alphabetically ordered as second argument after filtering using _Company_.

**Comment by brandonkelly** [comment]
The CP only lets you order by one thing at a time, so that is behaving as expected.

**Comment by romainpoirier** [comment]
Ok thank you Bandon. Just for my information, what's default criteria(es) are auto used in the CP order after one thing is set at a time? Is it based on the id, the title, or anything else?

**Comment by brandonkelly** [comment]
No backup order was passed, so it was just left to MySQL to decide.

I took a look at the code and realized it wouldn’t be too hard to add multi-sort support to element indexes though, so just went ahead and added it. Craft 3.7.25 is already out with the change :)
