### ISSUE TITLE
Craft 3.7.24 breaks LinkIt

### ISSUE THREAD

**Issue by heymarkreeves** [craftcms/cms#10208]
### Description

This _probably_ isn't your issue to fix, but with over 8,000 LinkIt installs, a number of sites are likely to be broken.

See https://github.com/presseddigital/linkit/issues/92

Looks like it comes from these in LinkIt's template:

```
{{ forms.field({
    errors: field.getErrors('enabledLinkTypes'),
    first: true
}) }}
```

```
{{ forms.field({
    label: groupTitle,
    instructions: "Select and configure the {groupTitle} you would like to make available."|t('linkit', {groupTitle: groupTitle|lower}),
    first: true
}) }}
```

### Steps to reproduce

I attempted to edit a Matrix field that uses LinkIt fields in its blocks. I assume this also happens when editing a LinkIt field.

### Additional info

- Craft version: 3.7.24
- PHP version: 8.0

**Comment by brandonkelly** [comment]
Thanks, just added a safeguard for this.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.24"` and run `composer update`.
