### ISSUE TITLE
Save as new entry applies changes to *current* entry and creates a new one too

### ISSUE THREAD

**Issue by fantasticmachine** [craftcms/cms#10204]
When editing an existing entry and clicking "Save as new entry" the changes are saved to the original entry as well as being used to make a new one.

### Expected behaviour
The new entry should be created with the updated content but the original entry is left untouched

### Steps to reproduce

1. Open an existing entry
2. Make some changes
3. Click "save as new entry" from the save dropdown
4. A new entry will have been created with the changes but the changes

### Additional info

- Craft version: 3.7.23
- PHP version: 7.4.26
- Database driver & version: MySQL 5.7.36
- Plugins & versions:
![Screenshot 2021-12-03 at 10 46 05](https://user-images.githubusercontent.com/827065/144589901-5f367ebd-a3f3-4cb8-b2b2-f9d21e534122.png)

**Comment by fantasticmachine** [comment]
After speaking with Oli I can see that this isn't a bug and is working as intended.
The original entry is getting saved as a draft as the new entry is created and published.

I know the publishing/drafts flow has been subject to considerable back and forth and there have been a lot of opinions on the subject. But this feels very counter-intuitive. In the case of saving as a new entry the author's intention wasn't to update the original entry. Should the draft either not be created, or be deleted automatically? I can't think of a case where an author would want the changes they made for the new entry to apply to the original, else they wouldn't be creating a new entry from it.

**Comment by brandonkelly** [comment]
Correct, this is working as expected. Your changes are initially made to a provisional draft for the entry, and then you are duplicating that into a new entry, but that doesn’t actually affect the provisional draft.

> In the case of saving as a new entry the author's intention wasn't to update the original entry.

Maybe, but maybe not. If you know from the start that you are intending to save the changes as a new entry, I suspect most people are duplicating the entry _first_, then making their changes.

I think the main thing we need to do is make it more obvious that you are editing a provisional draft. (Right now it’s only identified by the “– Edited” label within the revision menu button.) Then it won’t be as confusing as to why you are still seeing those edits, or think maybe they were also saved to the main entry. If you don’t want the edits, discarding them is just a button click away.

**Comment by fantasticmachine** [comment]
Having thought a bit more about this I tend to agree with you @brandonkelly. It would be more logical to create the new entry *before* editing. But yes, also I think it needs to be made more obvious that it's a draft.

**Comment by brandonkelly** [comment]
Changed for Craft 4 (#10467):

<img width="544" alt="Screenshot of the top of an entry form, with a message saying that you are viewing your unsaved changes, and a button to discard them." src="https://user-images.githubusercontent.com/47792/152405424-9484d4c9-6938-4cb5-91fe-133b338e43ef.png">

**Comment by brandonkelly** [comment]
As of Craft 4.3 (released earlier this week), provisional drafts are now discarded after the duplicate entry is created.
