### ISSUE TITLE
Description of migrate/fresh command is misleading

### ISSUE THREAD

**Issue by ivanBereznev** [craftcms/cms#10209]
### Description
`craft help` says that `migrate/fresh` "Drops all tables and related constraints. Starts the migration from the beginning."
This description is inherited from YII2 where this command actually truncates DB and then reapplies all the migrations.
In Craft CMS this command only reapplies migrations, so it would be nice to update description for it.

### Steps to reproduce

1. Run `craft help` console command
2. See description for `migrate/fresh`
3. Run `migrate/fresh` and compare result with description

### Additional info

- Craft version: Craft Pro 3.7.22
- PHP version: 7.3.31
- Database driver & version: PostgreSQL 13.5
- Plugins & versions:

**Comment by brandonkelly** [comment]
Yikes, I somehow missed that that command even existed. I’ve just updated its description to `Not supported.`  and it just outputs `This command is not supported.` when run.

**Comment by brandonkelly** [comment]
Craft 3.7.25 is out with that change.
