### ISSUE TITLE
Duplicate Preview and View links when editing a Category

### ISSUE THREAD

**Issue by martynwhitespace** [craftcms/cms#10215]
### Description
If you specify a URI when creating a new Category Group, then the Preview & View links are duplicated when you edit a Category.

![Screen Shot 2021-12-06 at 14 42 53](https://user-images.githubusercontent.com/29398428/144866054-24c5c928-3769-49b9-a0fa-1b83bf66f02d.png)

### Steps to reproduce

1. Create a new Category Group and specify a Category URI Format
2. Create a new Category
3. Edit newly created Category and notice the duplicate links

### Additional info

- Craft version: 3.7.24
- PHP version: 7.4.2
- Database driver & version: MySQL v5.7.26
- Plugins & versions:
       Feed Me v4.4.1
       Element Relations v1.0.6
       Retour v3.1.67
       SEOmatic v3.4.2
       Super Table v2.7.0

**Comment by brandonkelly** [comment]
I’m not seeing this on my end. Are you doing something with `EVENT_REGISTER_PREVIEW_TARGETS` perhaps?

**Comment by martynwhitespace** [comment]
I'm not. This is a fresh install of v3.7.24 with no custom plugins, just the plugins mentioned above. Also experiencing this on another site we have running v3.7.24 that has the above mentioned plugins plus a few others, but no custom ones.

**Comment by brandonkelly** [comment]
Just created a fresh install with each of those plugins, and still not able to reproduce. However I’m able to reproduce with a module that registers the following event:

```php
Event::on(Element::class, Element::EVENT_REGISTER_PREVIEW_TARGETS, function(RegisterPreviewTargetsEvent $event) {
    $event->previewTargets[] = ['label' => 'test', 'url' => '#'];
});
```

So guessing that’s the culprit… _something_ must be touching `EVENT_REGISTER_PREVIEW_TARGETS` for all elements rather than just entries.

Fixed for the next release.

**Comment by martynwhitespace** [comment]
Thanks @brandonkelly 👍

**Comment by brandonkelly** [comment]
Craft 3.7.25 is out now with that fix.
