### ISSUE TITLE
Add a "Save as Draft" button next to "Save Button"

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1021]
> Created by: Rolf-Juergen Hornasek (rolf.juergen.hornasek@gmail.com) on 2015/08/20 17:49:24 +0000
> Votes at time of UserVoice import: 5

-----------------------------------

Especially for enterprise customers it is common to prepare drafts before publishing them. Now the only way to save a draft is to click on the tiny dropdown next to the save button. If - by accident - the editor clicked on save the content would unintentionally go live. This has to be more clear, e.g. by adding a "Save as Draft" button next to the "Save" button.

This feature should only be available for PRO users.

**Comment by leevigraham** [comment]
Similar confusion to #1556

**Comment by brandonkelly** [comment]
Craft 3.2 will automatically create a draft as you start editing content, and autosave it as you continue editing, so there is no “Save” button anymore—just “Update entry”, which is the new equivalent of the old “Publish draft” button. So this FR isn’t really relevant anymore.
