### ISSUE TITLE
Upgrade to 3.7.24 - Page Content Tabs not working

### ISSUE THREAD

**Issue by bkrsmanovic** [craftcms/cms#10211]
### Description
Clicking on any tab inside page content doesnt work. In structure / single / channel.
I removed all application / localStorage and sessionStorage, tried it in inkognito chrome and firefox, removed runtime/* and still doesnt work.

Maybe it has to do with site being multisite? 
Example url for tab - content: 
**332-about-us?site=nettalliansenStrom#tab-content**
When clicking on sidebar tab:
**332-about-us?site=nettalliansenStrom#tab-sidebar**

![image](https://user-images.githubusercontent.com/15169280/144758257-370ea2ec-6f99-4e77-ad88-d25808d00dcf.png)

No js errors, no ajax, nothing.

EDIT: Looks like javascript is not active at all.
When I manually show Sidebar tab, and in matrix click 'Add Block' for new one, nothing is happening.

### Steps to reproduce

Described above.

### Additional info

- Craft version: 3.7.24
- PHP version: v8.0.12
- Database driver & version: 
- Plugins & versions:

**Comment by brandonkelly** [comment]
Try clearing your `web/cpresources/` folder and browser caches as a starting point. If that doesn’t work, try removing your entire `vendor/` folder and running `composer install`.

**Comment by bkrsmanovic** [comment]
@brandonkelly i tried it, it doesn't fix the problem.

I also did:
- Cleared cookies, local storage and session storage
- Removed cpresources (whole folder)
- Removed vendor
- composer install
- in inkognito, login to admin again

Same issue still remains. :/

**Comment by bkrsmanovic** [comment]
This is fresh install and fresh update to latest patch.
I am clicking Tabs on my home section, but nothing happens (except changing URL part that you cant see).

This is not multisite now, it is normal ordinary site.
This is with disabled plugins and bootstrap commented out. Fresh install.

https://user-images.githubusercontent.com/15169280/145374079-43a6719a-4dd5-4241-b03b-b49dc416dd82.mp4

**Comment by brandonkelly** [comment]
Can you try it in a private/incognito window, and in a different browser entirely?

**Comment by bkrsmanovic** [comment]
Tried it, on firefox and inkognito, same thing...
I really have no idea what's happening. It can be something just for me, since noone else complains, but not sure what it is.

**Comment by brandonkelly** [comment]
Yeah no one else is seeing this. Can you try creating a demo over at https://craftcms.com/demo and see if you can reproduce it there too?

**Comment by bkrsmanovic** [comment]
@brandonkelly I guess you can close it. On demo it works fine after updating. On my local its not, but its probably something on my local machine.

Sorry to waste your time! :+1:

**Comment by brandonkelly** [comment]
I wonder if you have some sort of server software that is removing the `<script>` tags from the response?

**Comment by timkelty** [comment]
@bkrsmanovic if this is remote, it could be an overly-aggressive ISP tampering with network packets, removing script tags.
Can you try on a different network, eg tether to cell phone?

…then again it sounds like it was broken on your local machine, so maybe that doesn't make sense.

**Comment by bkrsmanovic** [comment]
@brandonkelly no, nothing of sorts. Its just happening when I update to any patch after 3.7.24. When I revert back, suddenly it works.

There is just no javascript in backend, i have no idea why.

Anyway, thanks for your help, I will figure it out eventually. :) Sorry to waste your time.

**Comment by brandonkelly** [comment]
What version are you reverting back to?

**Comment by bkrsmanovic** [comment]
@brandonkelly sorry for late response, I got back 2 versions. 
Now I upgraded to latest version and bug seems to go away.

So I will update all our instances to latest version, so far all good.

Thanks for keeping up!

**Comment by brandonkelly** [comment]
Awesome! Still no idea what could have caused it, or fixed it 😅

**Comment by vardumper** [comment]
unfortunately I run into the same problem in Craft 3.9.11 .. 3.9.13 no idea what I can do to fix this. It happens on php8 with and without docker (craftcms/nginx:8.0-*)
