### ISSUE TITLE
Custom Date field sorting doesn't work when assets are in subfolders

### ISSUE THREAD

**Issue by mgambella** [craftcms/cms#10226]
### Description

I have created a Volume in CraftCMS to store a bunch of pdf documents. Then for a better editing experience I have created a new Date field named `documentDate` to store the document date, and I have attached it to the assets, because I wanted to be able to sort the documents when in the Elements Index Table for the assets in the CraftCMS Control Panel.

Everything worked fine i.e. elements got correctly sorted by `documentDate` when clicking on the Date header in the table.

But then I created subfolders inside the assets volume and the sorting stopped working: the ordering by `documentDate` was messed up...

### Steps to reproduce

1. Create a new Assets Volume
2. Create a custom date field
3. Add the custom date field to the assets
4. Populate the assets with some documents and different document dates 
5. Click on the date table header and you can see that the sorting should work
6. Then create a subfolder in the volume
7. Move files in the subfolder
8. Click on the date table header and you can see that the sorting should't be working anymore 

### Additional info

- Craft version: 3.7.24
- PHP version: 7.4.26
- Database driver & version: MySQL 8.0.27

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just released Craft 3.7.25.1 with a fix.
