### ISSUE TITLE
Invalid site error after deleting and changing subties

### ISSUE THREAD

**Issue by ishetnogferre** [craftcms/cms#10223]
### Description
For a client we needed to change a subsite structure. 

Locally we added an another site (C) and pushed it to production. Client informed us that they replaced another subsite (B), which they weren't using anymore and put all the content they wanted on that one. So we deleted the subsite (C) and changed the name and url of subsite (B). Now there's something stuck which prevents from subsite (B) loading when we go to url for this "new subsite" (C). We've already cleared the cache, deleted the runtime folder, run project-config/apply when all references of subsite C were deleted from it.

Later we realised we could transfer the content in the deletion process. So next time we're using that.

### Steps to reproduce

1. Have 2 subsites A and B with their own name, handle and url
2. Add subsite C with their own name, handle and url
3.  Delete subsite C
4. Change name and url of subsite B to name and url of subsite C

### Additional info
We defined the siteUrls in the config/general.php file.
In our setup site B is called designYourCity and site C called montventoux

- Craft version: 3.7.20
- PHP version: 7.4.24
- Database driver & version: MySQL 5.5.5
<img width="1223" alt="Screenshot 2021-12-07 at 20 02 56" src="https://user-images.githubusercontent.com/6649706/145090206-06a7f53b-19d2-4cb4-a09b-a9292a08973e.png">

**Comment by brandonkelly** [comment]
Are you still getting this error, or did you get it sorted already? (Sorry, not clear.) If so, can you please send your database backup and `composer.json` + `composer.lock` files, as well as any custom module/plugin code over to support@craftcms.com, so we can look into it from there?

**Comment by ishetnogferre** [comment]
@brandonkelly sorry for the mixup, it hasn't been sorted yet. I've sent the files over.

Thanks!
