### ISSUE TITLE
Password reset/account activation links use site URL instead of control panel when headless

### ISSUE THREAD

**Issue by devinpitcher** [craftcms/cms#10224]
### Description

When running headless, generating a password reset/account activation link in the control panel for a user always returns the URL of the website/front end rather than a control panel URL. Craft is running at `http://craft.nitro/admin` and my frontend is at `http://localhost:1337`. I have set my site base URL to `http://localhost:1337` and set Craft to in headless mode.

Impersonation URLs point to `http://craft.nitro/admin`, but activation and password reset links point to `http://localhost:1337`.

### Steps to reproduce

1. Set `define('CRAFT_CP', true)` in `web/index.php`
2. Set the following in `config/general.php`:
```
'baseCpUrl' => null,
'cpTrigger' => 'admin',
'headlessMode' => true,
```
3. Set default site `baseUrl` to something other than where Craft is running
4. Copy a password reset or activation link from the control panel

### Additional info

- Craft version: Craft Pro 3.7.24
- PHP version: 8.0.10
- Database driver & version: PostgreSQL 13.2
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Craft will only generate links to the control panel for users who have permission to access it.

Do these users have the “Access the control panel” permission set?

**Comment by devinpitcher** [comment]
They do.

I dug through the code and was able to find this.

https://github.com/craftcms/cms/blob/152d9dab2873c7cef878bcfc2134a8daf59f7f0a/src/config/GeneralConfig.php#L791-L793

Setting `baseCpUrl` to `http://craft.nitro` seems to work. My `baseCpUrl` is set to `null`, and Craft seems to be able to infer the hostname for impersonation URLs. Why not password reset and activation links as well?

>It will be determined automatically if left blank.

Should that be clarified to say that doesn't include if you are in headless mode?

**Comment by brandonkelly** [comment]
Just looked into this. The discrepancy is because activation/verification/password-reset URLs can be generated from the front-end, where we can’t trust the `Host` header. Shouldn’t be a concern for control panel requests though, so just tweaked the behavior for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.26 is out now with that change.
