### ISSUE TITLE
GraphQL: Duplicate entries returned when querying a structure with "type" param ONLY

### ISSUE THREAD

**Issue by FreekVR** [craftcms/cms#10227]
### Description

When I query one of my structures using only the GraphQL type parameter, I get every entry as a duplicated result (see below). If I additionally add the "section" param (as a workaround), the results are no longer duplicated.

### Steps to reproduce

1.
Query a structure like so;
```
{
    news: entries(type: ["news"]) {
       id
        isDraft
        postDate
        enabled
        siteId
        language
        trashed
        dateUpdated
    }
}
```
2.
Results look like this; (notice every ID being duplicated)
```
{
  "data": {
    "news": [
      {
        "id": "169",
        "isDraft": false,
        "postDate": "2021-10-27T12:17:00+02:00",
        "enabled": true,
        "siteId": 1,
        "language": "en-US",
        "trashed": false,
        "dateUpdated": "2021-12-07T10:32:17+01:00"
      },
      {
        "id": "169",
        "isDraft": false,
        "postDate": "2021-10-27T12:17:00+02:00",
        "enabled": true,
        "siteId": 1,
        "language": "en-US",
        "trashed": false,
        "dateUpdated": "2021-12-07T10:32:17+01:00"
      },
      {
        "id": "171",
        "isDraft": false,
        "postDate": "2021-10-27T12:18:00+02:00",
        "enabled": true,
        "siteId": 1,
        "language": "en-US",
        "trashed": false,
        "dateUpdated": "2021-12-02T14:24:15+01:00"
      },
      {
        "id": "171",
        "isDraft": false,
        "postDate": "2021-10-27T12:18:00+02:00",
        "enabled": true,
        "siteId": 1,
        "language": "en-US",
        "trashed": false,
        "dateUpdated": "2021-12-02T14:24:15+01:00"
      },
```

### Additional info

- Craft version: 3.7.24
- PHP version: 7.4
- Database driver & version: MySQL 8
- Plugins & versions: NEO

**Comment by andris-sevcenko** [comment]
What happens if you run an element query `craft.entries().type(["news").all()` in twig? How many results do you get?

**Comment by FreekVR** [comment]
Thanks, I'll have to check, it's a headless site so I need to change some things to be able to debug in Twig haha :)

**Comment by FreekVR** [comment]
I've done some additional checking and am unable to reproduce on a clean database. We're programatically importing entries into this section, so it might be that something there is causing the duplicates to appear.

**Comment by andris-sevcenko** [comment]
Alright. If you ever come up with what caused it and if it was something in Craft, let us know!
