### ISSUE TITLE
User FieldLayout not properly populated

### ISSUE THREAD

**Issue by ryssbowh** [craftcms/cms#10237]
### Description

On a config change event, the user layout fields and tabs are not populated when adding fields for the first time :
```
Craft::$app->projectConfig->onUpdate(Users::CONFIG_USERLAYOUT_KEY, function (ConfigEvent $e) {
       dd(\Craft::$app->getFields()->getLayoutByType(User::class)->fields);
       dd(\Craft::$app->getFields()->getLayoutByType(User::class)->tabs);
});
```
This returns empty arrays even if the layout has fields.
This works properly when saving afterwards, as long as the layout already had fields when it was saved.

### Steps to reproduce

1. Add an event to listen to a change on the config `Users::CONFIG_USERLAYOUT_KEY`
2. Add a field to a empty user layout
3. Save

### Additional info

- Craft version: 3.5.19.1 & 3.6.18 & 3.7.25.1
- PHP version: 7.4
- Database driver & version: Mysql 5.7
- Plugins & versions:

**Comment by andris-sevcenko** [comment]
Thanks for reporting that. The issue was that updating a field layout would not propagate the updated layout to the field layout caches. So, if fetched that same layout from the field service on the same request, it would return the cached version, which did not have tabs/fields preloaded. When accessing fields, it would try to access tabs/fields with outdated relationship links and that would return null.

Just got it fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 3.7.26 is out now with that fix.

**Comment by ryssbowh** [comment]
Hi,

I also see this problem on other places, the fields aren't populated with the changes made in the backend.

Entry types :
```
Craft::$app->projectConfig->onUpdate(Sections::CONFIG_ENTRYTYPES_KEY.'.{uid}', function (ConfigEvent $e) {
    foreach (\Craft::$app->sections->getAllEntryTypes() as $entryType) {
        if ($entryType->uid == $e->tokenMatches[0]) {
            break;
        }
    }
    dd($entryType->fieldLayout->fields);
});
```
Volumes :
```
Craft::$app->projectConfig->onUpdate(Volumes::CONFIG_VOLUME_KEY.'.{uid}', function (ConfigEvent $e) {
    $volume = \Craft::$app->volumes->getVolumeByUid($e->tokenMatches[0]);
    dd($volume->fieldLayout->fields);
});
```

Categories, Globals and Tags are working properly.
