### ISSUE TITLE
Cannot query for multiple statuses using GraphQL

### ISSUE THREAD

**Issue by GustavTaxen** [craftcms/cms#10232]
### Description

I'm trying to use GraphQL to query for all entries that have either status 'live' or 'pending'. Specifying one of them works, e.g.,
```
{
  entries(section: "someSection", status:"pending") {
    ...
  }
}
```

but providing more than one does not, e.g.,

```
{
  entries(section: "someSection", status:"[pending, live]") {
    ...
  }
}
```

### Steps to reproduce

1. Enter the second query above using the GraphQL explorer; it will always produce an empty result.

### Additional info

- Craft version: 3.7.17.1
- PHP version:8.0
- Database driver & version:MariaDB/MySQL
- Plugins & versions:n/a

**Comment by brandonkelly** [comment]
You should be able to do it with a comma-separated list (no square brackets):

```graphql
{
  entries(section: "someSection", status:"pending, live") {
    ...
  }
}
```

**Comment by GustavTaxen** [comment]
Well, it doesn't work for me. :(

**Comment by andris-sevcenko** [comment]
The correct syntax to use would be
```graphql
{
  entries(section: "someSection", status:["pending","live"]) {
    ...
  }
}
```
