### ISSUE TITLE
ActiveRecord causes DB Expression expression values to be JSON encoded

### ISSUE THREAD

**Issue by rob-baker-ar** [craftcms/cms#10239]
### Description

I am extending Craft's `ActiveRecord` class to manage a couple of (MySQL) tables that Craft is unaware of. It's nice to have the automatic management of `dateCreated`, `dateUpdated` and `uid`.

These new tables include geospatial (`POINT`) columns and to get the values from the class into the database, I am overriding `ActiveRecord::beforeSave()` to set a `yii\db\Expression` value on those columns so data inserts / updates as it should. Unfortunately, code in `ActiveRecord::_prepareValue()` calls `craft\helpers\Db::prepareValueForDb()` which assumes my `yii\db\Expression` instance needs JSON encoding - this results in an error when the resulting query is handed off to the database.

### Steps to reproduce

1. Have a class extend `craft\db\ActiveRecord`
2. Add a `POINT` geospatial column to the db table referred to by above (i.e. `coordinates`)
3. Override `craft\db\ActiveRecord::beforeSave()` containing code like:

```php
$this->coordinates = new Expression('POINT(:lat, :lng)', [
    ':lat' => $this->latitude,
    ':lng' => $this->longitude
]);
```

4. Create a record and `save()` it.
5. Notice a database error, the value is a JSON encoded version of the `yii\db\Expression` class

### Additional info

- Craft version: 3.7.18
- PHP version: 7.4.25
- Database driver & version: MySQL 5.5.5
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
Thanks for reporting! Craft 3.7.26 is out now with a fix for this.
