### ISSUE TITLE
Entry has a `duplicateOf` property even if it isn't a duplicate

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#10245]
### Description

I'm trying to create a hook that modifies an entry when it is being duplicated. In particular, I want to make duplicated entries disabled by default. I tried the [approach from this question on Craft.SE](https://craftcms.stackexchange.com/questions/36562/is-it-possible-to-duplicate-an-entry-as-not-enabled-live-from-the-listing-page), but it doesn't seem to work in Craft 3.7 any more.  Here's my hook:

```php
use Craft;
use craft\elements\Entry;
use craft\events\ModelEvent;
use craft\helpers\ElementHelper;

Event::on(
    Entry::class,
    Entry::EVENT_BEFORE_SAVE,
    function (ModelEvent $e) {
        $entry = $e->sender;
        if (ElementHelper::isDraftOrRevision($entry)) return;
        if (!$entry->duplicateOf) return;
        $entry->enabled = false;
    }
);
```

The problem is that saving a provision draft results in this hook being executed fully, so editing and saving an existing entry also disables it. As far as I can tell, provisional drafts have a `duplicateOf` property, so the conditions in the hook don't catch it. I tried to find out what's going on (`Craft::dd([$entry->id, $entry->duplicateOf->id])`) – looks like the provisional draft and the live entry are two seperate entries with different IDs. So maybe the workflow changes in 3.7 resulted in `duplicateOf` not being reliable for this use-case any more?

I'm not sure if this is a bug or intended. If it's intended, how can I reliably detect if an entry is being duplicated in a hook? Maybe `craft\services\Elements::duplicateElement` should trigger a custom event so it's easier to do something with duplicated entries?

As a sidenote, disabling duplicated entries or marking them as a draft should arguably be the default, I've opened a [separate discussion about this](https://github.com/craftcms/cms/discussions/10244).

### Steps to reproduce

1. Put the code above in a site module.
2. Open an existing entry, make some edits and save the entry. The entry will now be disabled.

### Additional info

- Craft version: 3.7.22
- PHP version: 8.0
- Database driver & version: MySQL 8.0

**Comment by brandonkelly** [comment]
Craft duplicates entries when creating drafts and revisions, as well as when merging changes between them, which is what’s causing your issue. You can filter that out by also checking `updatingFromDerivative`:

```php
use Craft;
use craft\elements\Entry;
use craft\events\ModelEvent;
use craft\helpers\ElementHelper;

Event::on(
    Entry::class,
    Entry::EVENT_BEFORE_SAVE,
    function (ModelEvent $e) {
        $entry = $e->sender;
        if (
            ElementHelper::isDraftOrRevision($entry)) ||
            !$entry->duplicateOf ||
            $entry->updatingFromDerivative
        ) {
            return;
        }

        $entry->enabled = false;
    }
);
```

**Comment by MoritzLost** [comment]
@brandonkelly Awesome, thanks! Are those more 'niche' properties documented anywhere? It's only mentioned in the [ElementTrait API reference](updatingFromDerivative), and the explanation doesn't go deep enough to understand the scenario this would be used in without context. I'm often finding it difficult to get special hooks like this to work – Elements in particular come with a lot of properties / methods where it's difficult to understand how to use them. For example, what's the difference between `getModifiedAttributes`, `getDirtyAttributes` and `getOutdatedAttributes`? The documentation is a bit self-referential in this case and even by looking through the source code I don't really understand in which scenarios each of those are used. I was trying to use those methods for a custom diff-view for revisions, but couldn't really figure out which one was the 'correct' one for my use-case.

Anyway, I just realized this is off-topic, sorry. I just wanted to mention that clearer documentation for niche stuff like this might reduce your workload in Github issues … :)

**Comment by brandonkelly** [comment]
Agree! Last week we launched a new [Events](https://craftcms.com/docs/3.x/extend/events.html) page in the docs, with the goal of making it easier to figure this stuff out. Will look into improving clarity around `duplicateOf` there.

**Comment by brandonkelly** [comment]
The `duplicateOf` examples you get from that page are now updated to be the kind of duplicate event people are probably expecting.

If you [go there]() and paste in the following event to the **Selected Event** input:

```
craft\elements\Entry::EVENT_AFTER_SAVE
```

…and then select the **Element is being duplicated to a new element** filter, you will now get the following code example:

```php
use craft\elements\Entry;
use craft\events\ModelEvent;
use yii\base\Event;

Event::on(
    Entry::class,
    Entry::EVENT_AFTER_SAVE,
    function (ModelEvent $event) {
        if (($event->sender->duplicateOf && $event->sender->getIsCanonical() && !$event->sender->updatingFromDerivative)) {
            // ...
        }
    }
);
```

**Comment by MoritzLost** [comment]
@brandonkelly Awesome, thanks! That events page is exactly what I was missing, that's a seriously impressive resource!

The example mentions `$event->sender->getIsCanonical()` is that equivalent to `!ElementHelper::isDraftOrRevision($element)` in this case? Thanks!

**Comment by brandonkelly** [comment]
Checking `getIsCanonical()` is slightly different – that will return `true` for unpublished drafts (what you get when you first create an entry), whereas those would be filtered out by `!ElementHelper::isDraftOrRevision()`.

The docs-suggested code is a bit more future-proof, as we are planning on having the “Save as a new entry” action duplicate entries into unpublished drafts in Craft 4 (#10244).
