### ISSUE TITLE
Craft did not install/enable a plugin when applying the project config

### ISSUE THREAD

**Issue by musicaljoeker** [craftcms/cms#10247]
### Description

Our development team ran a deployment of CraftCMS to our production environment (a 3 node cluster) this morning to install the Blitz plugin. Our project config for this plugin is as follows:

```
blitz:
    edition: standard
    enabled: true
    licenseKey: $BLITZ_LICENSE_KEY
    schemaVersion: 3.10.0
    settings:
      apiKey: $BLITZ_API_KEY
      cacheControlHeader: 'public, s-maxage=31536000, max-age=0'
      cacheDuration: null
      cacheElementQueries: true
      cacheElements: true
      cachePurgerSettings:
        __assoc__:
          -
            - apiKey
            - $BLITZ_CF_API_KEY
          -
            - apiSecret
            - $BLITZ_CF_API_SECRET
          -
            - distributionId
            - $BLITZ_CF_DISTRIBUTION_ID
          -
            - warmCacheDelay
            - '5'
      cachePurgerType: putyourlightson\blitzcloudfront\CloudFrontPurger
      cachePurgerTypes:
        - putyourlightson\blitzcloudfront\CloudFrontPurger
      cacheStorageType: putyourlightson\blitz\drivers\storage\YiiCacheStorage
      cacheWarmerSettings:
        __assoc__:
          -
            - concurrency
            - '3'
      cacheWarmerType: putyourlightson\blitz\drivers\warmers\GuzzleWarmer
      cachingEnabled: '1'
      clearCacheAutomatically: '1'
      customSiteUris: ''
      debug: false
      deployerType: putyourlightson\blitz\drivers\deployers\DummyDeployer
      driverJobPriority: 100
      excludedQueryStringParams:
        - gclid
        - fbclid
      excludedUriPatterns: ''
      includedQueryStringParams:
        - '.*'
      includedUriPatterns:
        -
          __assoc__:
            -
              - uriPattern
              - ''
      injectScriptEvent: DOMContentLoaded
      integrations:
        - putyourlightson\blitz\drivers\integrations\FeedMeIntegration
        - putyourlightson\blitz\drivers\integrations\SeomaticIntegration
      maxRetryAttempts: 10
      mutexTimeout: 1
      outputComments: true
      queryStringCaching: '0'
      queueJobTtr: 300
      refreshCacheAutomaticallyForGlobals: true
      refreshCacheJobPriority: 10
      refreshCacheWhenElementSavedNotLive: false
      refreshCacheWhenElementSavedUnchanged: false
      sendPoweredByHeader: true
      warmCacheAutomatically: '1'
      warmPagesWithQueryStringParams: true
```
We ran the command `craft project-config/diff` and observed the changes from the current state during our deployment steps and saw that Blitz was to be enabled on the Production environment. When we ran `craft project-config/apply`, everything looked like it ran successfully, so I would assume this means that Blitz was installed.

Blitz, however, did not install. We confirmed this by checking the `craft_plugins` database table and by not seeing any of Blitz's CLI tools when running `craft`.

Strangely, when we do a `craft project-config/diff` now it says there are no differences to apply even though project config says it needs to install blitz and the site doesn't have blitz installed.

What can we do? I thought about running a `craft project-config/apply --force` but this seems risky on a Production environment. I also thought about trying to do a `craft plugin/install blitz`, but that will make changes to project config on production without doing a deployment (which is not in our workflow).

Obviously, we are trying to be risk-averse here since it's a production environment. Any help is appreciated.

### Additional info

- Craft version: 3.6.18
- PHP version: 7.4
- Database driver & version: MySQL

**Comment by brandonkelly** [comment]
Was Blitz actually Composer-installed at the time `project-config/apply` was run? If so, maybe it was listed in `disabledPlugins` in `config/general.php`?

**Comment by musicaljoeker** [comment]
Yes, Blitz was composer installed at the time `project-config/apply` was run. I can confirm Blitz is not on the disabled plugins in the general config.

**Comment by brandonkelly** [comment]
Strange. Do you happen to have a database backup from before the deploy? If so could you try creating a new environment with it, and the updated Composer dependencies + `config/project/` files that were deployed, and see if you can reproduce the Blitz issue when running `project-config/apply`?

**Comment by musicaljoeker** [comment]
Yes, we do have a backup prior to the upgrade. I can try to reproduce the issue. I'll follow up here when I have a reproduction attempt.

As an aside, is there anything you'd feel comfortable running in a production environment to try to unstick this issue? Would a `plugin/install blitz` be relatively safe to run on production? (reminder that our production environment has 3 web nodes) I feel less safe about running `project-config/apply --force` on production.

**Comment by brandonkelly** [comment]
It’s not clear what went wrong yet, so I’m not sure that `plugin/install blitz` will actually work, but you are welcome to try it. Maybe make a DB backup first just in case. (`project-config/apply --force` probably won’t do anything because at this point it’s probably already pulled into the internal project config.)

**Comment by brandonkelly** [comment]
Did you try running `plugin/install blitz`?

**Comment by musicaljoeker** [comment]
No I did not, but I do not think that would work since the project config is in read-only mode on our prod server.

**Comment by musicaljoeker** [comment]
OK so I just tried running a `plugin/install blitz` and it actually seemed to work! I tried it first on our Staging environment restoring from a snapshot from our Production environment. Here's the output:

```
$ sudo -u www-data ./craft plugin/install blitz
*** installing blitz
    > create table {{%blitz_caches}} ... done (time: 0.028s)
    > create table {{%blitz_elementcaches}} ... done (time: 0.018s)
    > create table {{%blitz_elementexpirydates}} ... done (time: 0.018s)
    > create table {{%blitz_elementquerycaches}} ... done (time: 0.018s)
    > create table {{%blitz_elementquerysources}} ... done (time: 0.022s)
    > create table {{%blitz_elementqueries}} ... done (time: 0.019s)
    > create table {{%blitz_cachetags}} ... done (time: 0.018s)
    > create table {{%blitz_driverdata}} ... done (time: 0.019s)
    > create unique index craft_idx_uawnengaukdyfuerfhtdyxcdswyzrxssjggh on {{%blitz_caches}} (siteId,uri) ... done (time: 0.033s)
    > create index craft_idx_jltrfkntakzmctdsunhgiqlhhcamfwzonzus on {{%blitz_caches}} (expiryDate) ... done (time: 0.034s)
    > create unique index craft_idx_wnzvxlbivhpvebygygbdlfhcvjdelsxxpnta on {{%blitz_elementexpirydates}} (elementId) ... done (time: 0.032s)
    > create index craft_idx_mqntalkqmfaygbwdhnvsnifnqaqfzjhzxgsl on {{%blitz_elementexpirydates}} (expiryDate) ... done (time: 0.031s)
    > create unique index craft_idx_vdnrherhvhfnxtalknxaavltcqabeviwdxdy on {{%blitz_elementquerycaches}} (cacheId,queryId) ... done (time: 0.030s)
    > create unique index craft_idx_ipvhbjdidbcqvjvpdjykeslahlogwhjvsdua on {{%blitz_elementquerysources}} (sourceId,queryId) ... done (time: 0.032s)
    > create unique index craft_idx_rsjlvtmocctbvkhnqinvdjrfiiojavzvehwd on {{%blitz_elementqueries}} (index) ... done (time: 0.031s)
    > create index craft_idx_hgqtbugzuvcgmjmpbyfnuxvpdftkuiuebivw on {{%blitz_elementqueries}} (type) ... done (time: 0.032s)
    > create index craft_idx_ouujhrhanyprrgjhgshwgxubdpapzbgatmbk on {{%blitz_cachetags}} (tag) ... done (time: 0.034s)
    > add foreign key craft_fk_ikusmskyvkfffcmoohbdbcivnfqlxqzcfsga: {{%blitz_caches}} (siteId) references {{%sites}} (id) ... done (time: 0.057s)
    > add foreign key craft_fk_dvtqjtzgyhkmpqxdvhsaqwslsmoqbjsfgxmb: {{%blitz_elementcaches}} (cacheId) references {{%blitz_caches}} (id) ... done (time: 0.049s)
    > add foreign key craft_fk_whralbqwnqeqgmveomhzhzjzqiyrfvmbfcnk: {{%blitz_elementcaches}} (elementId) references {{%elements}} (id) ... done (time: 0.048s)
    > add foreign key craft_fk_hkcjretxnpkzfnlclubjccjshveyssebmdfr: {{%blitz_elementexpirydates}} (elementId) references {{%elements}} (id) ... done (time: 0.050s)
    > add foreign key craft_fk_qbwyqvqjdphryxxbotogooqlssnbgwhcmcju: {{%blitz_elementquerycaches}} (cacheId) references {{%blitz_caches}} (id) ... done (time: 0.049s)
    > add foreign key craft_fk_indzugnqgbhajnvynhxkvjxksdtqvfqiqwlu: {{%blitz_elementquerycaches}} (queryId) references {{%blitz_elementqueries}} (id) ... done (time: 0.053s)
    > add foreign key craft_fk_uonnzoyhbzhbtfkhxjsgntxlabtwhpfhwnyz: {{%blitz_elementquerysources}} (queryId) references {{%blitz_elementqueries}} (id) ... done (time: 0.051s)
    > add foreign key craft_fk_wvfgjkvkvjolkmcxgdgqmmeeqqqwzrcuaysa: {{%blitz_cachetags}} (cacheId) references {{%blitz_caches}} (id) ... done (time: 0.052s)
*** installed blitz successfully (time: 1.263s)
```

This must not have run during the initial `craft project-config/apply` for some reason. To be clear, I wasn't able to reproduce from the backup _before_ the upgrade. I'm really not a fan of not knowing what originally happened. Do you have any ideas?

**Comment by brandonkelly** [comment]
Great!

> I'm really not a fan of not knowing what originally happened. Do you have any ideas?

Me either. My best guess is maybe the new files weren’t fully in place when `project-config/apply` was run—or perhaps they were, but OPcache got in the way of them. What you saw is in-line with what should happen if the plugin files were not actually present.
