### ISSUE TITLE
Unknown "slug" filter on twig template

### ISSUE THREAD

**Issue by masiorama** [craftcms/cms#10241]
### Description

Hello, I get a `Unknown "slug" filter.` error when trying to use it. The documentation tells it should be included in my current Craft CMS version.
Thanks!

### Steps to reproduce

1. Apply something like  `{% set textToSlug = 'Test test test' | slug %}` to twig template
2. Access the template via url

### Additional info

- Craft version: 3.7.14
- PHP version: 7.4
- Database driver & version: MySQL 5.7
- Plugins & versions: 
    "craftcms/redactor": "2.8.8",
    "ether/seo": "3.7.4",
    "craftcms/aws-s3": "1.2.15",
    "vaersaagod/matrixmate": "1.2.7",
    "xpertbot/craft-wheelform": "2.5.8",
    "craftcms/element-api": "2.8.3",
    "ether/tags": "1.0.7",
    "wrav/simplesharing": "1.0.8",
    "nystudio107/craft-disqus": "1.1.3"

**Comment by brandonkelly** [comment]
Doh, that is a docs bug. Twig’s [slug](https://twig.symfony.com/doc/2.x/filters/slug.html) filter is actually only available via a separate extension.

Craft’s [kebab](https://craftcms.com/docs/3.x/dev/filters.html#kebab) filter might work for your needs, though.
