### ISSUE TITLE
Issue with pushing a job into the queue via an event

### ISSUE THREAD

**Issue by mediabeastnz** [craftcms/cms#10248]
### Description
We're using an event hook to send a job to the queue. This has been working fine until we recently updated the site to the latest version of Craft.

We looked back through the changelogs of Yii, Craft and Commerce but can't see any change that may have caused this issue to arise.

The error is: **"Serialization of 'Closure' is not allowed in /vendor/yiisoft/yii2-queue/src/serializers/PhpSerializer"**

The code looks like this:
```php
Event::on(
    Order::class,
    Order::EVENT_AFTER_COMPLETE_ORDER,
    function(Event $event) {
        $order = $event->sender;
        \craft\helpers\Queue::push(new CompletedOrderJob([
            'order' => $order
        ]));
    }
);

```

`CompletedOrderJob()` triggers a function that is in a service. The function basically just fires of an API request to a 3rd party.
```php
public function execute($queue)
{
    SiteModule::$plugin->shop->createOrder($this->order);
}
```

We know of a work potential workaround but can't figure out why this started throwing an exception.

### Steps to reproduce

1. Install versions listed below
2. Create module with service
3. Create job that calls a function from the service
4. trigger job via an event of some sort (shouldn't matter)
5. see if it throws an exception

### Additional info

- Craft version: 3.7.25.1
- PHP version: 7.4.25
- Database driver & version: MySQL 5.7
- Plugins & versions: Commerce Pro 3.4.8

**Comment by brandonkelly** [comment]
A couple other people have run into this, and for each of them, the issue was that whey were setting an entire, instantiated `craft\elements\Entry` object on their queue job.

Queue jobs get serialized when being stored in the queue, and it’s generally a very bad idea to serialize anything but simple objects in PHP. So, assuming that’s your issue, the solution would be to just set the entry ID on the job, and then re-fetch it from your job’s `execute()` method.

(Closing but happy to reopen if my assumption is wrong.)

**Comment by mediabeastnz** [comment]
Thanks @brandonkelly for the simple solution. 

Do you know what may have changed from an Entry point of view to start that error? Maybe it was related to the custom field change?

**Comment by brandonkelly** [comment]
I believe it was 2519e4c9b68ee44ae02932b73db410abb032f632 – once an entry has been validated, that callback function will be stored directly on the entry’s private `_validators` property. But if it hadn’t been that specific change, it would have ended up being something else down the road.
