### ISSUE TITLE
Sort/Filter Entries by 'Entry Type'

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1024]
> Created by: Dan (dan@switch.je) on 2016/01/21 17:34:21 +0000
> Votes at time of UserVoice import: 5

-----------------------------------

Would be nice if you could sort/filter entries by entry type when viewing them under 'Entries'. If you are looking for a specific type of entry it can be a bit tedious scrolling through hundreds of entries looking for that specific type.

**Comment by KatieMFritz** [comment]
YES

**Comment by brandonkelly** [comment]
@KatieMFritz putting you down for a maybe

**Comment by ccsantos23** [comment]
Would be nice if this plugin was built-in:  https://plugins.craftcms.com/sidebarentrytypes

**Comment by aaronbushnell** [comment]
Was hoping this would be one of the options you could sort by in Craft 3.2 with the sorting changes but it doesn't appear that's the case. Would love to see this in a future update!

**Comment by mihow** [comment]
Is this on the roadmap for a future version?

**Comment by brandonkelly** [comment]
Yep, we will be making this possible in Craft 4.
