### ISSUE TITLE
Matrix blocks are not reverted correctly

### ISSUE THREAD

**Issue by jimyhse** [craftcms/cms#10253]
### Description
Matrix blocks within a Neo field or a Super Table field are not reverted correctly.

### Steps to reproduce

1. Create a Matrix field with a block containing a plain text field
2. Create a Neo field with a block containing the matrix field
3. Create a page entry type with the Neo field
4. Create and save an entry of the new page type with the text set to "Version 1"
5. Update the text to "Version 2" and save the page again
6. Revert the page to the first revision. The text will be set to "Version 2", instead of "Version 1".

Example after revert:
![145591421-74271fef-4a97-4e59-9904-978252d70fb4](https://user-images.githubusercontent.com/91942722/146212303-0b35bfcf-e74c-4b9d-9f47-fa3eb77ec405.png)

### Additional info

- Craft version: 3.7.25.1
- PHP version: 7.4
- Database driver & version: MariaDB 10.5.3, MySQL 8.0.26
- Plugins & versions: Neo 2.11.21, Redactor 2.8.8

This issue was originally reported to the Neo-plugin; spicywebau/craft-neo#527, but @ttempleton was able to reproduce the bug using Super Table fields as well.

**Comment by brandonkelly** [comment]
Thanks for reporting! Craft 3.7.26 is out now with a fix for this.

**Comment by jimyhse** [comment]
Thanks for fixing this so quickly. The fix works great!
