### ISSUE TITLE
User should auto login after resetting password

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1025]
> Created by: Jeremy Daalder (jd@imagescience.com.au) on 2015/08/17 22:59:59 +0000
> Votes at time of UserVoice import: 5

-----------------------------------

I think users should be auto logged in after resetting their passwords rather than forcing them through a login process again.  I see no security benefit to that, and it just seems like needless extra labour for the user...and we all hate work.  

I think this is even the intended behaviour, well according to the bottom you your docs here it is:https://craftcms.com/docs/templating/set-password-form

So not sure if this is a big or a feature request really!

**Comment by brandonkelly** [comment]
This was implemented in Craft 3.1.8 (fafa67c6e4ffd6ded5d64c11b6ed1bda2c35910a).
