### ISSUE TITLE
Preview function returns 404 when viewing unsaved drafts

### ISSUE THREAD

**Issue by j0h4n3s** [craftcms/cms#10257]
### Description
When creating a new entry (in our case a blog post), we normally used the preview function (View button) but that returns a 404 now. It does work when first saving the entry as draft. But this function normally worked with unsaved drafts as well.
We have this problem for a few days now. I hoped it would be solved in Craft 3.7.26 but the problem is still there.

### Steps to reproduce

1. Create a new entry
2. Fill in the title.
3. Click the View button
4. Returns 404
5. Now save the entry as draft
6. Click View button
7. Works now, but should also work with unsaved drafts

### Additional info

- Craft version: Craft Pro 3.7.26
- PHP version: 7.4.26
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Is something in your template fetching the entry on its own perhaps? It should just be using the provided `entry` variable.

**Comment by adrienne** [comment]
I have in the past run into a similar issue when using eager-loading in an entry template, for the record. We had to disable it with a conditional.

**Comment by vitalijalbu** [comment]
I found the bug, this happens when someone changes the slug of section and then tries to add/edit some entries of that section.

**Comment by brandonkelly** [comment]
@vitalijalbu I actually just discovered that a couple days ago when looking into #10343. Fixed for the next release via 1bf19f79109e6c4f5e8738e21e3f90f46129e8f8 :)

**Comment by brandonkelly** [comment]
Craft 3.7.29 is out now with the fix for this.
