### ISSUE TITLE
Issue on config file

### ISSUE THREAD

**Issue by andrelopez** [craftcms/cms#10255]
### Description
Following the config files [docs](https://craftcms.com/docs/3.x/config/config-settings.html#system) if the `*` (all) key is not present in the config file the `dev`, `staging`, etc won't work until the `*` is added. Is this expected? in a craft clean installation, there are no `*` or `dev` keys in the config array, just wondering why the default clean installation config file is not under `*`?.

### Steps to reproduce

1. add a `dev` key array in the config file without the `*` key, the config will be ignored
2.

### Additional info

- Craft version:  3.7.25.1
- PHP version: 8
- Database driver & version: mysql
- Plugins & versions: clean install

**Comment by brandonkelly** [comment]
Correct. The default config is not a multi-environment config. We decided to consider that more of an advanced feature, that isn’t really needed as much as it used to be, thanks to environment variables.
