### ISSUE TITLE
Element search with exclude flag not working with space in search query

### ISSUE THREAD

**Issue by joomkit** [craftcms/cms#10262]
### Description
This might be a syntax issue but seems like a bug too?

Element api has search criteria where query. incoming is two words with a space between. eg "Tower Hamlets"
This returns data fine until an exclude flag is used in front of the title:
eg "-title"
Expected result is everything except Tower Hamlets

### Steps to reproduce

1. Create element criteria search with excluded criteria
`
'api/searchtherest.json' => function () {

            $section_handle = 'openFunding';

            $criteria = [
                'section' => $section_handle,
                'openForFunding' => true,
                'search' => ($q = Craft::$app->request->getParam('query'))
                    ? "-title:*\"{$q}\"*"
                    : null
            ];

            return [
                'elementType' => Entry::class,
                'criteria' => $criteria,
                'paginate' => false,
                'pretty' => false,
                'transformer' => function (craft\elements\Entry $entry) {

                    return [
                        'id' => $entry->id,
                        'title' => $entry->title,
                        'localauthority' => $entry->ladnm,
                        'mapitAreaId' => $entry->mapitAreaId,
                        'fundableRegion' => $entry->fundableRegion,
                        'openForFunding' => $entry->openForFunding,
                        'geojson' => json_decode($entry->geojson),
                        'lsoacode' => $entry->lsoacode
                    ];
                },

            ];
        },

`
2. #Tried solving with Brandon's response here:
https://github.com/craftcms/cms/issues/2702
I realised the cache was working against me. Am inclusive search and excluding search work with one word. But an excluding search with a search term that has a space results in zero data returned

### Additional info

PHP version | 7.4.24
MySQL 5.7.35
Craft Pro 3.7.26

Plugins
AsyncQueue	2.3.0
CodeMirror	1.0.2
CP Field Inspect	1.2.5
Element API	2.8.4
Environment Label	3.2.0
Feed Me	4.4.1.1
Guest Entries	2.4.0
Guest Entries Honeypot	1.0.0
Guest Entries Notification	1.0.1
Icon Picker	1.1.12
ImageOptimize	1.6.38
JSON	1.0.1
Logs	3.0.5
mapitapi	1.0.0
Minify	1.2.10
MobileDetect	1.0.2
oEmbed	1.3.13
pdfthumbnailer	1.0
Position Fieldtype	1.0.17
Redactor	2.8.8
Redirect Manager	1.1.1
Section Field	1.1.0
SEOmatic	3.4.21
Smith	1.1.14
Splashing Images	2.1.8
Super Table	2.7.0
Tags	1.0.9
Twigpack	1.2.15
Typogrify	1.1.18

**Comment by brandonkelly** [comment]
The correct syntax for that would be `-"Tower Hamlets"`.

**Comment by joomkit** [comment]
Nope that does work either;-)
Heres my criteria dump:


array(3) { ["section"]=> string(11) "openFunding" ["openForFunding"]=> bool(true) ["search"]=> string(22) "title:-"Tower Hamlets"" }

**Comment by timkelty** [comment]
@joomkit The dash goes before the field handle, so your [search syntax](https://craftcms.com/docs/3.x/searching.html#supported-syntaxes) should be:

```
-title:"Tower Hamlets"
```

**Comment by joomkit** [comment]
@timkelty see my first post above
` ? "-title:*\"{$q}\"*"`
This doesn't work when a space is present - fine on single word

**Comment by joomkit** [comment]
Doh my bad

`? "-title:*\"{$q}\"*"`
removing the wildcards and we're all good

`? "-title:\"{$q}\""`
