### ISSUE TITLE
iFrame in field instructions

### ISSUE THREAD

**Issue by bengreenbank** [craftcms/cms#10264]
### Description
Including an iFrame in field instructions will attempt to load the iframe. See screenshots. It messes up the layout lots. Although ideally we would never include an iframe in field instructions, it might be worth looking at blocking them from there to stop any unexpected issues.

### Steps to reproduce
1. Go to Settings > Fields > Example Field
2. Add an iFrame embed to the field instructions
3. Create a new entry that includes the example field.
4. The layout will break like the screenshot below.

![Screenshot 2021-12-17 at 11 43 57](https://user-images.githubusercontent.com/61185468/146540277-b1328983-4a48-4593-a73e-6f6f0a4e100a.png)

### Additional info
- Craft version: 3.7.25.1
- PHP version: 7.4
- Database driver & version: MySQL 5.7

**Comment by brandonkelly** [comment]
Thanks for reporting. Just added a `max-width` for the next release. 

> t might be worth looking at blocking them from there to stop any unexpected issues.

Not really possible without getting HTML Purifier involved, which would be overkill and likely end up blocking a lot of other things.

**Comment by bengreenbank** [comment]
Great, thanks very much @brandonkelly.

**Comment by brandonkelly** [comment]
Craft 3.7.27 is out now with that fix.
