### ISSUE TITLE
Control Panel Search not returning entries that exist

### ISSUE THREAD

**Issue by joomkit** [craftcms/cms#10263]
### Description
Hard to reproduce but....
I imported 42K of records from json dataset that I need for a plugin to look up.

The titles are reference numbers referring to losa geography in UK
eg "E01028041"

Craft cant seem to find these consistently if at all. I know the entry is there because i can page through to find it.
I have tried triggering search indexes - and yes the fields and custom fields are searchable - but there is no CLI for search indexing entries only assets.

### Steps to reproduce

1. Import data with titles like "E01028041"
2. Search in control panel - no result

### Additional info

PHP version | 7.4.24
-- | --
Darwin 21.1.0
MySQL 5.7.35
GD 7.4.24
Craft Pro 3.7.26
2.0.43
v2.14.8
7.4.1

**Comment by brandonkelly** [comment]
>  but there is no CLI for search indexing entries only assets.

I suppose you are referring to the [`index-assets`](https://craftcms.com/docs/3.x/console-commands.html#index-assets) command, which is for indexing which files exist within the volume – not for updating their search indexes.

To update search indexes, you can use the [`resave`](https://craftcms.com/docs/3.x/console-commands.html#resave) command, and pass its `--update-search-index` option:

```sh
php craft resave/entries --section mySectionHandle --update-search-index
```

**Comment by joomkit** [comment]
That did the trick
