### ISSUE TITLE
Undefined siteUid index when creating sites programatically

### ISSUE THREAD

**Issue by tekstrand** [craftcms/cms#10266]
### Description
I am trying to create a site in a migration
```
            $site = [
                "baseUrl" => "@site-en-it",
                "groupId" => $defaultSiteGroupId,
                "handle" => "italy",
                "enabled" => false,
                "language" => "en",
                "name" => "Italy",
            ];
            Craft::$app->sites->saveSite(new Site($site));
```

but I get an error `Exception: Undefined index: c08a81d7-4446-49a2-84a4-275fcecc260d (/vendor/craftcms/cms/src/services/Categories.php:366)`

### Steps to reproduce

1. Create a migration and add the above code into safeUp
2. Run the migration

### Additional info

- Craft version: 3.7.25.1
- PHP version: 7.4
- Database driver & version: mysql
- Plugins & versions:

**Comment by tekstrand** [comment]
Something was messed up in the database, pulled a backup and ran again and it is fine.

**Comment by tekstrand** [comment]
Was able to mess up the database again in the same way. If I try to run `$app->getSites()->saveSite` instead of `$app->sites->saveSite` it happens and then I have to restore the db from a backup. Unfortunately when I run `$app->sites->saveSite` it won't actually save the site...

**Comment by brandonkelly** [comment]
`Craft::$app->sites` is an alias of `Craft::$app->getSites()`, so I _highly_ doubt that the way you are accessing the Sites service has anything to do with this.
