### ISSUE TITLE
Nested sources not showing up on initial entry index page load

### ISSUE THREAD

**Issue by myleshyson** [craftcms/cms#10265]
### Description
There's a small UI bug where if nested sources are opened on the entry index page, when the page refreshes the nested sources are gone with the parent arrow remaining in the open position. A little hard to explain so I'm attaching some images. 

### Images Describing the Problem

On initial load, nested sources show up like you'd expect. However when I reload the page...

<img width="1546" alt="Screen Shot 2021-12-17 at 8 37 42 AM" src="https://user-images.githubusercontent.com/11747187/146552814-3763f082-a95d-4693-95ba-8503d6c125b2.png">

Now the nested sources are gone and clicking the arrow  to switch from open to close back to open still doesn't show them.

<img width="1546" alt="Screen Shot 2021-12-17 at 8 39 23 AM" src="https://user-images.githubusercontent.com/11747187/146552966-5add5b92-ffe2-4eec-9cb2-ee28b0c9ac33.png">

Now though if I put the arrow into the closed state _and then_ refresh the page, the nested sources show back up like expected when putting the parent source into open state.  There seems to be something about reloading the page while the parent source is in open state that causes the nested sources to not load properly.

### Steps to reproduce

1. Create nested sources.
2. Open up the nested sources on the entry index page.
3. Reload the page
4. See that the nested sources stay hidden no matter the open state of the parent source.

### Additional info

- Craft version: 3.7.25.1
- PHP version: 8.0
- Database driver & version: Mysql
- Plugins & versions:

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. I tried nesting a custom source within a native one, as well as adding a new custom top-level source with a nested source. Both are still available when I reload the page, whether they are selected or not.

```php
use craft\elements\Entry;
use craft\events\RegisterElementSourcesEvent;
use yii\base\Event;

Event::on(Entry::class, Entry::EVENT_REGISTER_SOURCES, function(RegisterElementSourcesEvent $event) {
    foreach ($event->sources as &$source) {
        if (isset($source['key']) && $source['key'] === 'section:f5969f9a-8d3f-487e-9695-cc4e5fbe5efd') {
            $source['nested'][] = [
                'key' => 'foo',
                'label' => 'Foo',
            ];
            break;
        }
    }
    
    $event->sources[] = [
        'key' => 'bar',
        'label' => 'Bar',
        'nested' => [
            [
                'key' => 'baz',
                'label' => 'Baz',
            ],
        ],
    ];
});
```

Anything else you can think of that I could be missing?

**Comment by myleshyson** [comment]
Ah shoot no i was passing the wrong site id into it 🦆 .  Works likes a charm. Thanks for taking a look into it!
