### ISSUE TITLE
Support for permissions on settings without being admin

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#1026]
> Created by: Mark Goodyear (hello@markgoodyear.com) on 2015/03/17 11:50:44 +0000
> Votes at time of UserVoice import: 5

-----------------------------------

I think allowing a user group to access certain options within the settings panel would be very handy.

For example being able to allow a client to access items such as cache clearing and other general options, whilst restricting them from access anything to do with fields/structures incase they break something.

**Comment by stijnmeysen** [comment]
Definitely an interesting feature.  A lot of customers of us want to administer more than just content.  
But as you mentioned @takobell all rights will definitly break something.

We would love to see this feature for Craft Commerce as well. Where the customer admin can manage promotions but not settings like shipping costs etc.

**Comment by brandonkelly** [comment]
Craft 3 moved the tools out of the Settings page and into a new Utilities section, which non-admins can access if they have the permissions.
