### ISSUE TITLE
Incorrect HSL color value returned for new Color Data object functionality

### ISSUE THREAD

**Issue by tomkiss** [craftcms/cms#10261]
### Description

Hi there, thanks so much for implementing the new [hsl functionality](https://github.com/craftcms/cms/discussions/10235) in the Color Data object. It's really helpful for the project I'm working on currently 🙌

Unfortunately, the method used to produce the HSL value is not quite right, the saturation and lightness values returned appear to be incorrect.

Attached is a screenshot of the hex value `#fbc884`, stored in a color field and output with `getHex()`, `getRgb()` and `getHsl()` as the background color for three repeated HTML elements:

<img width="599" alt="Screenshot 2021-12-16 at 15 34 09" src="https://user-images.githubusercontent.com/183310/146400990-2f4f312d-a9a3-442c-94f0-927d5c51bf68.png">

I ran Craft's `hsl` method independently to verify what's happening. I also found an alternative method for calculating HSL to compare.  I found [this gist](https://gist.github.com/brandonheyer/5254516) and compared the two side by side. 

Given my test value of `#fbc884`, here's the results:

| Source  | HSL |
| ------------- | ------------- |
| Sketch App | `hsl(34, 94%, 75%)` |
| [Gist example](https://gist.github.com/brandonheyer/5254516)  | `hsl(34.29, 94%, 75%)`  |
| Craft 3.7.26  | `hsl(34, 47%, 98%)` |

### Referenced code:

This was the code that I used for the above test, tweaked a little, based on the comments on the gist:

```php
function rgbToHsl( $r, $g, $b ) {
  $r /= 255;
  $g /= 255;
  $b /= 255;

  $max = max( $r, $g, $b );
  $min = min( $r, $g, $b );

  $h;
  $s;
  $l = ( $max + $min ) / 2;
  $d = $max - $min;

  if( $d == 0 ){
    $h = $s = 0; // achromatic
  } else {
    $s = $d / ( 1 - abs( 2 * $l - 1 ) );

    switch ($max) {
      case $r:
        $h = 60 * fmod( ( ( $g - $b ) / $d ), 6 ); 
        if ($b > $g) {
          $h += 360;
        }
        break;

      case $g: 
        $h = 60 * ( ( $b - $r ) / $d + 2 ); 
        break;

      case $b: 
        $h = 60 * ( ( $r - $g ) / $d + 4 ); 
        break;
    }			        	        
  }
  
  return array( round( $h, 2 ), round( $s, 2 ) * 100, round( $l, 2 ) * 100 );
}
```

### Additional info

- Craft version: 3.7.26

**Comment by brandonkelly** [comment]
Doh, sorry about that. I used [this example](https://stackoverflow.com/a/13887939/1688568) which provides the same HSL values Photoshop gives you, but I guess that’s different than web-safe `hsl()` values. Just updated it based on that Gist.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.26"` and run `composer update`.

**Comment by tomkiss** [comment]
Amazing, thanks Brandon! 🙌

**Comment by tomkiss** [comment]
...Actually @brandonkelly , I just realised that the answer which you linked to was entirely correct, but was based on HS**V** values, not HS**L**.

I am by no means an expert and wasn't really aware of [HSV being a different unit](https://en.wikipedia.org/wiki/HSL_and_HSV)! So there's something I learnt today.

(I had checked out your link to StackOverflow in the committed code, I should have been more eagle-eyed!)

**Comment by brandonkelly** [comment]
Ahhh… the more you know!

**Comment by brandonkelly** [comment]
Craft 3.7.27 is out now with that fix. Thanks again!
