### ISSUE TITLE
Create token action fires twice when clicking "Preview"

### ISSUE THREAD

**Issue by david-mcleod** [craftcms/cms#10280]
### Description
When clicking on the live preview button, there are 2 calls to /index.php?p=admin/actions/preview/create-token happening. One returns a 200 status, the other a 500. 

If the 500 returns first, the live preview works as expected and the error goes unnoticed. However, it the 200 response returns first, followed by the 500 error, the preview does not open. After that, nothing on the page functions.

### Steps to reproduce

1. Create an entry, save the entry. 
2. Go back to the entry and make some changes and click "Preview"
3. Notice if there are 2 calls to /index.php?p=admin/actions/preview/create-token in the network panel. Depending on which request returns first the preview will either open as expected or fail to open

### Additional info

- Craft version: Craft Pro 3.7.26
- PHP version: 8.0.14
- Database driver & version: MySQL 5.7.12
- Plugins & versions:
      - Amazon S3 1.3.0
      - Control Panel CSS 2.4.0
      - Control Panel Nav 3.0.17
      - Craft CMS Easy MDE Markdown Editor  0.1.7
      - Feed Me 4.4.1.1
      - Gatsby Helper 1.1.2
      - Healthz v1.0.3
      - Matrix Colors 2.0.1
      - Navigation  1.4.22
      - Redactor  2.8.8
      - Super Table 2.7.0
      - Typed link field  2.0.0-rc.1
      
First request successfully returns token...
![Screen Shot 2021-12-22 at 12 38 53 PM](https://user-images.githubusercontent.com/10202722/147011553-f41c9d3d-2913-4486-89e9-66a18e26c021.png)

Duplicate request fails...
![Screen Shot 2021-12-22 at 12 39 00 PM](https://user-images.githubusercontent.com/10202722/147011546-de875f21-88ea-4d21-90d5-61c641bf3dec.png)

**Comment by david-mcleod** [comment]
Possibly related to this => https://github.com/craftcms/cms/issues/7782

After reading that issue, I've realised that this bug only occurs when their are pending changes. If all changes are saved, the live preview opens as expected

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.27 is out now with that fix. Thanks again.
