### ISSUE TITLE
Email new license key to admin email on creation

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#1028]
> Created by: Steve Adams (pixeljitsu@gmail.com) on 2015/08/05 16:40:23 +0000
> Votes at time of UserVoice import: 5

-----------------------------------

When generating a new license key after purchasing in the CP, there should be an option to send the license.key to the admin email along with the domain name it was activated on.  This would reduce instances of lost licenses and the need for P&T support to manually retrieve them in such cases.

**Comment by sjelfull** [comment]
@takobell Won't this handled by the plugin store / Craftcms.com?

**Comment by takobell** [comment]
> When generating a new license key after purchasing in the CP

A new license.key file isn't generated when a purchase is made.  The existing `craft/config/license.key` is just upgraded to whatever edition is purchased.

> along with the domain name it was activated on

There is an "additional fields" text box where you can enter this domain this purchase was intended for and it will be included on the emailed receipt.  We don't automatically do it, because many people purchase locally on craft.dev or localhost with the intention of moving the license.key file up through staging/production.

> Won't this handled by the plugin store / Craftcms.com?

You'll be able to look up your purchase history and retrieve your license.key files, yes.

Going to go ahead and close this for the above reasons.
