### ISSUE TITLE
After updating to 3.7.13, 'craft' console command produces error: "Cannot use object of type craft\log\FileTarget as array"

### ISSUE THREAD

**Issue by cscomfort** [craftcms/cms#10297]
### Description
In the process of trying to update to the latest version of Craft (3.7.8 -> 3.7.26), the `craft` console command errored out with `Cannot use object of type craft\log\FileTarget as array`. At that point, I began updating with incremental versions -- 3.7.9, 3.7.10, and so on -- until I reached 3.7.13, at which point the error presented.

### Steps to reproduce

1. Ran `./craft update craft:3.7.13`
2. Attempted to run the Craft console command with and without parameters (e.g, `./craft` and `./craft migrate/all`)

### Additional troubleshooting steps

The following all resulted in the same error:

- Require new version directly with Composer: `composer require craftcms/cms:3.7.13`
- Remove all plugins and modules, and then ran Composer require
- Cleared Composer cache, removed vender directory Composer lock file, and then ran Composer require 

### Additional info

- Craft version: 3.7.13
- PHP version: 7.3.29 (as defined by composer.json platform config); 7.3.28 (CLI)
- Database driver & version: MariaDB 10.3

**Comment by timkelty** [comment]
@cscomfort are you using a custom log driver in your `app.php`?

**Comment by timkelty** [comment]
Closed due to inactivity.
