### ISSUE TITLE
Single Entry Drafts are obliterated if any type of save or project config change is made

### ISSUE THREAD

**Issue by mattbloomfield** [craftcms/cms#10307]
### Description
I discovered this because my homepage drafts were getting blown away on deploy. We run `php craft project-config/apply --force` on each deploy. 

If I remove the `--force` the drafts are not erased. However, if I make a change to the Project Config for my homepage section type and then run it without `--force` all drafts are erased. Furthermore, after some testing with mmikkel on Discord we found that even just saving the settings for the Homepage single obliterated the drafts. 

### Steps to reproduce

1. Create a single
2. In that single, create and edit a draft. Save. 
3. Run `php craft project-config/apply --force` OR go to the settings for that draft and resave. 

Video: https://www.loom.com/share/0c413f53e8c54e8eb685b9ccea47aec0

### Additional info

- Craft version: PRO 3.7.26
- PHP version: 7.4.21
- Database driver & version: MySQL 5.7.36
- Plugins & versions:
![image](https://user-images.githubusercontent.com/37582550/148136524-bc135a4d-7be5-4bc4-b6bd-e196d28a4a4c.png)

**Comment by brandonkelly** [comment]
Thanks for reporting this! We just released Craft 3.7.28 with a fix.

**Comment by mattbloomfield** [comment]
Awesome! Thanks @brandonkelly for the quick turnaround!
