### ISSUE TITLE
Craft CMS 3.7.27 Can't Create New User via CP

### ISSUE THREAD

**Issue by kylecotter** [craftcms/cms#10308]
### Description

`/admin/users/new` on Craft CMS 3.7.27 results in 

```
craft\services\Users::getUserPreferences(): Argument #1 ($userId) must be of type int, null given, called in /var/www/vendor/craftcms/cms/src/elements/User.php on line 1312
```

I'd assume due to this [recent change](https://github.com/craftcms/cms/blob/develop/CHANGELOG.md#changed)

### Steps to reproduce

1. Fresh install Craft 3.7.27
2. Upgrade to Pro trial
3. From the users page click "New user"
4. See PHP error

### Additional info

- Craft version: 3.7.27
- PHP version: 8.0.11
- Database driver & version: 8.0.27
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
Thanks for reporting! We just released 3.7.27.1 with a fix for this.
