### ISSUE TITLE
Matrix block query fails with single typeId

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#10315]
### Description
We update a project from 3.6.17 to 3.7.25.1 and are seeing an issue with Matrix Block Querries.
Our query looks like this: 

        $blockType = MatrixBlockType::findOne(["handle" => "date"]);
        $query = MatrixBlock::find();
        $query->typeId($blockType->id);
        $query->fieldId($blockType->fieldId);

And now it throws this error: 

`TypeError: craft\helpers\ArrayHelper::isNumeric(): Argument #1 ($array) must be of type array, int given, called in /Users/jhenckens/Sites/ubgweb/vendor/craftcms/cms/src/elements/db/MatrixBlockQuery.php on line 583 and defined in /Users/jhenckens/Sites/ubgweb/vendor/craftcms/cms/src/helpers/ArrayHelper.php:431`

We can trace it back to this issue https://github.com/craftcms/cms/discussions/9921 and this commit https://github.com/craftcms/cms/commit/0438530c3b51630af8f98d8a129cf624355b2606.

Changing the code to `$query->typeId([$blockType->id])` fixes the problem but if this change is required this feel like breaking problem. 

Can you have a look? Thanks

### Additional info

- Craft version: 3.7.25.1
- PHP version: 8.0.8
- Database driver & version: 5.7.23

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just released 3.7.28 with a fix.

**Comment by janhenckens** [comment]
Great, thanks for the quick update @timkelty @brandonkelly !
