### ISSUE TITLE
Change in saveElement?

### ISSUE THREAD

**Issue by heymarkreeves** [craftcms/cms#10317]
### Description

I have a site that's a few years old now, that contains some plugin code that scrapes a feed URL, via cron task, does an `Entry::find()` to fetch a matching entry based on a field value matching a value in the feed entry, and then creates or updates an entry based on whether there was a match.

Another vendor did some work on the site, and in the process upgraded Craft from 3.6.7 to 3.6.17. Content entry was done on that dev site as well, and so I relaunched the site by swapping that database & codebase for the existing site on the same server, with the cron task continuing to point at the live site's vhost. (The cron task was never running on the dev site, so an issue would not have been apparent there.) The updated database dump file I used for the relaunch was ~66MB. The relaunch was ~12/5/2021. Today the database dump file's size is greater than 3GB.

It seems that `Craft::$app->elements->saveElement($result)` is creating new database records in the `content`, `entries`, and `elements` tables every time it saves a matched entry. Is this expected? I do not see duplicate entries in the control panel, nor do I see revisions when I edit the actual entries. But a small site with 83 press release entries and ~200 career postings now has over 200,000 records in those tables and we're getting bogged down in "pruning revisions" queue tasks—all since early December.

Running a manual test, I see that the search for a matching entry does come back with a result, and we are running the code to update an entry. We're not getting a mismatch and creating new entries when we should not be.

We've used this code across multiple sites, so I have something I need to solve for here, whether I need to change the approach before running Craft updates or abandon this approach. I don't see anything in the docs indicating I need to override this behavior when using `saveElement`. Is there something I'm missing or need to account for?

Thanks!

**Comment by brandonkelly** [comment]
Hey Mark,

If `saveElement()` is being called for an existing element (with an `id` value), it should definitely not be resulting in a new row in the `elements` table.

Mind sharing the code?

**Comment by heymarkreeves** [comment]
Sure thing. This is the chunk that includes the lookup and create or update. Thanks!

```
$result = Entry::find()->section('pressReleases')
            ->where([
                'field_prNasdaqId' => $pressReleaseId
            ])->one();
if (!isset($result)) {
    /*
    ** Create new Craft entry
    */
    echo 'Create new entry<br />';
    /*
    ** Fetch the body of the post
    */
    $postJson = json_decode(file_get_contents($pressRelease->body[0]->link->url));

    $entry = new Entry();
    $entry->sectionId = 2;
    $entry->typeId = 2;
    $entry->authorId = 3;
    $entry->title = $title;
    $entry->postDate = new \DateTime($pressRelease->releaseDate->dateUTC.'+00:00'); // strtotime($pressRelease->releaseDate->dateUTC.'+00:00');
    $entry->setFieldValues([
        'prNasdaqId' => $pressReleaseId,
        'prNasdaqLastUpdated' => new \DateTime($pressRelease->lastUpdatedUTC.'+00:00'),
        'newsBody' => (string)$postJson->data
    ]);
    if(Craft::$app->elements->saveElement($entry)) {
        echo 'Successfully created new entry<br />';
    } else {
        throw new \Exception("Couldn't create new entry: " . print_r($entry->getErrors(), true));
    }
}
else {
    /*
    ** Update existing Craft entry
    ** Fetch the body of the post
    */
    echo 'Entry update<br />';
    $postJson = json_decode(file_get_contents($pressRelease->body[0]->link->url));

    $result->title = $title;
    $result->postDate = new \DateTime($pressRelease->releaseDate->dateUTC.'+00:00');
    $result->setFieldValues([
        'prNasdaqId' => $pressReleaseId,
        'prNasdaqLastUpdated' => new \DateTime($pressRelease->lastUpdatedUTC.'+00:00'),
        'newsBody' => (string)$postJson->data
    ]);
    if(Craft::$app->elements->saveElement($result)) {
        echo 'Successfully updated entry<br />';
    } else {
        throw new \Exception("Couldn't update entry: " . print_r($result->getErrors(), true));
    }
}
```

**Comment by brandonkelly** [comment]
Hm yeah that looks fine.

Are you able to reproduce locally (by triggering the script manually rather than via the cron job)? If so any chance you could send all your files and database backup over to support@craftcms.com? We can try to dig into it from there.

**Comment by heymarkreeves** [comment]
Yeah, I just ran it locally and I see all the "Successfully updated entry" statements and I have 81 new entries in the elements table. I'll reach out via the support address. Thanks!

**Comment by brandonkelly** [comment]
Resolved via support. For posterity, `where()` should have been `andWhere()` – or the custom field’s param method could have been used instead most likely:

```php
->myPressReleaseField($pressReleaseId)
```

And if the section has versioning enabled, it’s expected that a new row(s) would be added when updating an existing element. One for the main revision element, and another per each Matrix/Super Table/Neo block that was duplicated for the revision as well.
