### ISSUE TITLE
There was a problem getting the parent element.

### ISSUE THREAD

**Issue by siebird** [craftcms/cms#10327]
Updated Craft to the most recent version `3.7.27.1` and having issues editing an entry after updating/saving it. After saving and returning to the entry, Craft throws `There was a problem getting the parent element.`

Not sure if this is related to this issue: https://github.com/craftcms/cms/issues/6205

We're using Neo in this case as well.

**Comment by brandonkelly** [comment]
Can you please send a database backup and your Composer files over to support@craftcms.com, as well as steps to reproduce? Can try to look into it from there.

**Comment by siebird** [comment]
Just sent. Thanks @brandonkelly

**Comment by brandonkelly** [comment]
Update: This was most likely caused by changes to Propagation Method settings, and has resolved itself, either via a queue job completing, or the entry in question getting saved from a site where all its content was in-tact.
