### ISSUE TITLE
Color Profile Config does not work properly

### ISSUE THREAD

**Issue by fr-haus** [craftcms/cms#10337]
### Description
`'preserveImageColorProfiles' => true` does not seem to work anymore. When uploading an image, without even applying any transforms, images still get converted to some other color profile even when the config is added to general.php.

### Steps to reproduce

1. New Craft Instance
2. Add `'preserveImageColorProfiles' => true` to general.php
3. Upload Image
4. Notice that the config setting does not change the outcome

### Example
![color-profile-comparison](https://user-images.githubusercontent.com/80354889/148656077-ea8db4bc-c762-4e21-8448-fbd59725875d.jpg)

### Additional info

- Craft version: 3.7.28
- PHP version: 7.4.21
- Database driver & version: MySQL 5.7.34
- Plugins & versions: –

**Comment by andris-sevcenko** [comment]
Do you have Imagick installed and available?

**Comment by fr-haus** [comment]
No, there are no Plugins installed. Stock Craft.

**Comment by andris-sevcenko** [comment]
ImageMagick is a PHP extension that enables enhanced image manipulation (https://craftcms.com/docs/3.x/requirements.html#required-php-extensions) and it's something that should get installed on the server/environment, not Craft itself

Without it, it's not possible to preserve the color profiles, unfortunately.
