### ISSUE TITLE
Parent/Child URI structure incorrect across different sites

### ISSUE THREAD

**Issue by tekstrand** [craftcms/cms#10332]
### Description
- We have a multi-site setup, with a structure who's Entry URI Format is `{parent.uri}/{slug}`.
- There exists 2 entries. `parent` and `child`. `parent` is the parent entry of `child`
- For site 1, the `child` entry's URI is `parent/child`
- For site 2, the `chuld` entry's URI is `child` (incorrect)
- Resaving the entry for site 2, correctly sets the URI for site 2, but breaks the URI for site 1. Site 1 is now set to `child`

### Additional info

- Craft version: 3.7.25.1
- PHP version:7.4
- Database driver & version: mysql 8
- Plugins & versions:

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Couple things to try:

- Update to the latest version of Craft.
- Ensure that your section has the correct Entry URI Format for _both_ sites.

**Comment by tekstrand** [comment]
Verified entry URI format is correct. We've also tried changing them to just `slug` and then back to `parent/slug`. The resaving task fails part way through. We're going to try bumping php memory in case that helps the task run. Next step I can think of is to try using the rebuild section structure `utils/repair/section-structure`

**Comment by brandonkelly** [comment]
> The resaving task fails part way through.

That wouldn’t explain why the entry would end up going from having the correct URI to having an incorrect one.

Did you try updating Craft?  If so and you’re still experiencing this, please send your Composer files and a database backup over to support@craftcms.com and we can look into it from there.

**Comment by tekstrand** [comment]
Updated to 3.7.28, issue persists. Email submitted to support

**Comment by timkelty** [comment]
This turned out to be a corrupted `structureentries` table, where there were multiple versions of the the same `elementId` with different `structureId`s. Pruning those with the incorrect `structureId`s fixed things.
