### ISSUE TITLE
Saving an image as a new asset is confusing.

### ISSUE THREAD

**Issue by bob-pixeldeluxe** [craftcms/cms#10335]
### Description
Hi, I want to make the option to select a different focus point for the mobile header image. However at this moment this is pretty confusing. I added 2 image fields to the section 1 for desktop 1 for mobile. Now when you edit the desktop variant you can easily select the focus point. However once i try to set the mobile variant and i save it as a new asset it does not overwrite the image in the field. It makes a copy of the desktop image and saves that with the correct focus point. I think this is confusing for our customers. It would make sense if this image then becomes the one selected in the field once its saved as a new asset.
Our customers usually edit images from here:

![Screenshot 2022-01-07 at 14 43 01](https://user-images.githubusercontent.com/50947605/148552246-1072cfc9-7192-4830-b432-350a95c2f1f5.png)

Thanks in advance!

### Steps to reproduce

1. select an image in an asset field
2. double click the name of the image and click edit in the popup menu.
3. Now change something and select the option save as a new asset
4. The old image is still the one selected in the field instead of the newly edited asset.

### Additional info

- Craft version: Craft Pro 3.7.13
- PHP version: 7.2.34
- Database driver & version: MySQL 5.7.34

**Comment by brandonkelly** [comment]
This was previously requested by #8974, and we’ve already addressed it for Craft 4 :)
