### ISSUE TITLE
Add an "auto-save as draft" feature

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1034]
> Created by: Martin Graney (martin@nomadsagency.com) on 2016/03/15 18:04:40 +0000
> Votes at time of UserVoice import: 5

-----------------------------------

A lot of CMSs nowadays automatically save the content asynchronously as you are editing it.

It would be nice to automatically save as draft any entry if the mandatory fields have valid content.

That way a content editor that forgets to save as draft before leaving their desk and getting a coffee does not accidentally lose all of their work.

**Comment by leevigraham** [comment]
Rather than drafts could we consider local storage: https://signalvnoise.com/posts/3057-automatically-save-your-work-in-basecamp-highrise-backpack-and-writeboard

**Comment by ChrisCopperfield** [comment]
Thumbs up, we need this feature as soon as possible. For me, this is a basic feature and I'm a little shocked that CraftCMS doesn't include it.

We have already lost several hours of editorial work due to the missing essential feature.

**Comment by leevigraham** [comment]
@ChrisCopperfield  You spent several hours without once saving?

**Comment by ChrisCopperfield** [comment]
@leevigraham In sum - of course not on an article. But if I write 20-30 articles per day and have to rewrite 2 articles due to disconnects or other errors per day, I add up to several hours, yes.

**Comment by brandonkelly** [comment]
This has been added for the next 3.2 Alpha release!
