### ISSUE TITLE
Ability to move matrix blocks up and down on ios/mobile

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1035]
> Created by: Jason Noffsinger (noffsin6@gmail.com) on 2016/01/06 14:57:16 +0000
> Votes at time of UserVoice import: 5

-----------------------------------

The craft control panel works pretty good on mobile but not being able to re-order matrix blocks without deleting and adding them again is frustrating.

I understand that the issue is the way ios and other devices handle drag and drop, not a bug in Craft.

Would it be possible to add a couple of options to the Matrix Block settings dialogue box to move blocks up and down on a page?  This would be a little clunky but it at least it would be functional until a better solution arises.

**Comment by brandonkelly** [comment]
Just added new “Move up” and “Move down” options to Matrix block menus.

**Comment by brandonkelly** [comment]
Craft 3.5 RC6 is out now with this change.
