### ISSUE TITLE
Show field handles in edit forms not working anymore?

### ISSUE THREAD

**Issue by KarelJanVanHaute** [craftcms/cms#10357]
### Description
The option "Show field handles in edit forms" is not showing the controls when checked.

### Steps to reproduce

1. check the box "Show field handles in edit forms" for the user. 
2. Check an entry edit form. No controls are showing up. 

### Additional info

- Craft version:3.7.23
- PHP version:8.0.3

**Comment by brandonkelly** [comment]
Still working on my end. Have you installed any plugins/modules or started injecting any custom CSS/JS that could affect it?

**Comment by KarelJanVanHaute** [comment]
@brandonkelly Sorry for the interruption. It works fine. I was confused with a plugin we had. That's the one that is broken.
