### ISSUE TITLE
Bug: Long Matrix block dropdowns in Safari don't have visible scrollbars even if "Always VisibleScrollbars" system pref is set

### ISSUE THREAD

**Issue by adrienne** [craftcms/cms#10354]
### Description

(This probably affects other long dropdowns as well, but Matrix is where we are seeing it the most.)

As i'm sure you know, scrollbars are hidden systemwide by default on Mac, but there is a system pref you can set for "Always On" to make sure they are always visible. However, in Safari, that system preference isn't respected by long dropdown menus. Obviously you can't do anything about the (terrible, inaccessible) Mac system default, but there's clearly *also* some kind of JS or CSS issue happening here that I'm hoping you *can* fix.

Note that the below screenshots are using Spoon (so the Matrix blocks are divided into sections), but the same behavior occurs without Spoon active.

Here's Firefox on Mac:
![image](https://user-images.githubusercontent.com/89705/149009374-ef85ab7d-301b-429f-a217-eb8d98f87f5b.png)

Chrome on Mac:
![image](https://user-images.githubusercontent.com/89705/149010679-530c2d18-ac1e-4f58-ba00-ef5460d6230e.png)

And here's Safari, where you'll note the main browser window has a scrollbar but the dropdown does not:
![image](https://user-images.githubusercontent.com/89705/149009514-f886f227-cb76-4792-ac42-6d1632a211f2.png)

### Steps to reproduce

1. Set your system-level Scrollbar preference to "Always Visible"
2. Create a Matrix with a whole bunch of different block types
3. Attach the field to a section
4. Using Safari, specifically:
    1. Create a test entry and add a Matrix block
    2. Click the gear menu on the Matrix block to open the dropdown menu
    3. Note that there is no scrollbar

### Additional info

- Craft version: 3.7.28
- PHP version: 7.4.27
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
We are not doing anything to suppress scrollbars there, and they are showing up on my end:

<img width="233" alt="A Matrix block’s settings menu, showing visible scrollbars" src="https://user-images.githubusercontent.com/47792/149209714-8b5a6c46-2143-40f0-a4b8-77ab53f82a9c.png">

Is that actually Matrix though? Looks like maybe a Neo field, or at least there has been some UI customization of Matrix, which could perhaps be at fault here.

**Comment by adrienne** [comment]
@brandonkelly Hm. It is a Matrix field, but we've got Spoon installed. As far as i know Spoon isn't doing anything except adding headers but I'll report this over there as well. Sorry!

**Comment by brandonkelly** [comment]
Can you try disabling it and see if you can still reproduce?
