### ISSUE TITLE
Propagation and search not working correctly in multi-site setup

### ISSUE THREAD

**Issue by sarahschuetz** [craftcms/cms#10358]
### Description

We have a multi-site installation of Craft CMS with three different site groups containing either a german and an englisch site or only a german site. So our site structure looks like this:

**Site Group A:**
- Site A German
- Site A English

**Site Group B:**
- Site B German
- Site B English

**Site Group C:**
- Site C German

Then we have a channel which is enabled for _Site A German_, _Site A English_ and _Site C German_.
The propagation setting is _Save entries to other sites in the same site group_.

When we create entries in this channel for _Site Group A_ (the main language is German, so I guess most of the entries will be created in _Site A German_) the propagation worked fine, but there seems to be a problem with the search indices. We don't get any error message, but most entries are only found on _Site A German_ and not on _Site A English_ when using the search (Frontend and Backend). The entry is enabled for both sites. Once I re-save the entry on _Site A English_ manually, it is also found in the search.

For newer entries the propagation doesn't seem to work at all. I created a new test entry on _Site A German_ which was not created on the _Site A English_ at all. Furthermore, I only have the possibility to enable/disable the entry but no options to enable/disable the entry for specific sites like I am using to from other projects using propagation.

### Additional info

Craft CMS 3.7.24
PHP 7.4.3
MySQL 8.0.22

**Comment by sarahschuetz** [comment]
I just tried resaving the entries to update the search indexes. Is it normal that `php craft resave/entries --section xxx --update-search-index` only resaves the entries from the primary site? I would expect that entries from all sites are resaved if I  do not specify a specific one.

After running `php craft resave/entries --section xxx --update-search-index --site xxx` the search works fine again. How is this possible and how can I make sure that search indexes will always be updated correctly in the future?

**Comment by brandonkelly** [comment]
I can only think of two reasons why that command could have fixed this:

- The “Updating search indexes” background job was never executed for this entry(s) in the first place, which could happen if the queue had been backed up or not configured properly.
- The fields you are searching for were not marked as searchable when they were last edited. (Note that Craft only re-indexes field keywords when the field itself has changed, not just when the entry is re-saved without any changes.)

**Comment by sarahschuetz** [comment]
So far we have not notices any queue problems and the fields were marked as searchable from the beginning (part of the older entries also worked for same fields). For me it's a bit of a mystery. However, since it is working at the time I will leave it for now and keep an eye on it, if the problem turns up again.
