### ISSUE TITLE
Since updating Craft to 3.7.28, GraphiQL no longer autofills query attributes

### ISSUE THREAD

**Issue by toddpadwick** [craftcms/cms#10363]
### Steps to reproduce

1. Go to the GraphiQL editor.
2. Add your query
3. begin typing query attributes
4. Normally, query attributes autofill from the schema. This no longer happens making it very tricky to build queries

### Additional info

I also seem to get the following errors in the response before i even submit a query which presumably means they are global errors with GraphQL. These didn't exist before the update. Some are to do with Formie plugin which [I've submitted as a bug with them here](https://github.com/verbb/formie/issues/714), others are Craft Core (see the last line). These errors are not returned when running the query in Postman or from Apollo in our app. I do not know if these errors are related, I would have thought any errors in the response should not affect the autofill schema attributes.

```
{
  "errors": [
    "Interface field RowInterface.id expected but feedback_KPIs_FormieRepeaterFieldRow does not provide it.",
    "Interface field RowInterface.uid expected but feedback_KPIs_FormieRepeaterFieldRow does not provide it.",
    "Interface field RowInterface.fields expected but feedback_KPIs_FormieRepeaterFieldRow does not provide it.",
    "Interface field RowInterface.id expected but testForm_repeater_FormieRepeaterFieldRow does not provide it.",
    "Interface field RowInterface.uid expected but testForm_repeater_FormieRepeaterFieldRow does not provide it.",
    "Interface field RowInterface.fields expected but testForm_repeater_FormieRepeaterFieldRow does not provide it.",
    "Interface field RowInterface.id expected but testForm_repeaterField_FormieRepeaterFieldRow does not provide it.",
    "Interface field RowInterface.uid expected but testForm_repeaterField_FormieRepeaterFieldRow does not provide it.",
    "Interface field RowInterface.fields expected but testForm_repeaterField_FormieRepeaterFieldRow does not provide it.",
    "Interface field EntryInterface.author expects type UserInterface but testimonials_testimonial_Entry.author is type String."
  ]
}
```

UPDATE:
I have tested on a fresh install which does not have formie installed and GraphiQL still does not autocomplete and I also do not have the above errrors.

- Craft version: 3.7.28

**Comment by andris-sevcenko** [comment]
> others are Craft Core (see the last line)

Seems like you have a custom field called "author", which is a reserved word. Can you check that?

Nothing has changed that should have affected this recently, so the best bet is to resolve these errors first.

Which version of Craft did you update from?

**Comment by toddpadwick** [comment]
Ah okay, yes you're correct it is a custom field. However, I have never had any problem with it before and its been in place for about a year. these errors only appeared just now for the first time. Also if it was a reserved word shouldn't the admin panel have prevented me from creating it in the first place as it does with words like 'title'?

**Comment by brandonkelly** [comment]
@toddpadwick There’s nothing wrong with having an `author` field on element types besides entries. For entries, you will get a validation error when attempting to save an entry type with an `author` field selected, as of 3.5 I believe. Perhaps Formie is not being defensive about it, though.

**Comment by engram-design** [comment]
Does seem unrelated to Formie (maybe!) with `testimonials_testimonial_Entry.author` being on the section/entry type, but maybe it's the Entries field in Formie 🤷‍♂️

**Comment by toddpadwick** [comment]
After further investigation, I think this is two separate bugs. I have created a new craft project for another website, that does not have formie installed, and I can confirm, the query attributes still do not autofill/autocomplete.

**Comment by toddpadwick** [comment]
UPDATE: I tried a different browser (firefox) and it seems to work now 🤷‍♂️

**Comment by andris-sevcenko** [comment]
The HTTP 500 error would seem to indicate a PHP error, too. Probably worth checking your Craft logs!
