### ISSUE TITLE
Query for pending public registrations

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#10361]
### Description

I'm trying to build a list of all unconfirmed public registrations. Public registrations are suspended by default. As far as I can tell, a suspended user created from a public registration is indistinguishable from a user that was suspended by an admin in the backend, correct?

I'm looking for alternatives to find unconfirmed public registrations for a to-do list for admins. Just querying for suspended users also returns every account that was ever suspended, so that's not good enough. Of course, I could use an arbitrary cut-off point and only show users registered in the last x days. Another option would be to check if `lastLoginDate` is empty (suspended public registrations can't have logged in yet), though that will also find every user that was suspended manually that had never logged in (a bit weird, but can happen with imported accounts).

The most reliable indicator seems to be that unconfirmed public registrations are both suspended AND pending. Is there a way to limit a user query to only users that have both of those statuses? According to the documentation, this is supported:

```php
$userQuery->status([User::STATUS_PENDING, User::STATUS_SUSPENDED])
```

But of course that's an OR relationship. Specifying `['AND', User::STATUS_PENDING, User::STATUS_SUSPENDED]` doesn't work at all (empty result).

Am I on the wrong track here? Can a user account have two statuses at once? Checking `$user->suspended` and `$user->pending` is both `1` (true) for new registrations, so this information does exist somewhere in the database, right? In this case, is there a way to query for it? Or more broadly, is there a more reliable way to find unconfirmed public registrations?

---

Just for additional context, the closest I've come is this:

```php
$pendingRegistrations = User::find()
    ->status(User::STATUS_SUSPENDED)
    ->lastLoginDate(':empty:')
    ->orderBy('dateCreated DESC')
    ->all();
$pendingRegistrations = array_filter($pendingRegistrations, fn(User $user) => $user->pending);
```

This returns all suspended users and then filters that list by accounts that are pending, which does work reliably. But is there a way to do this in one query? And this still feels like it's not super reliable.

### Additional info

- Craft version: 3.7.22
- PHP version: 8.0
- Database driver & version: MySQL 8

**Comment by brandonkelly** [comment]
This is a little awkward because users’ statuses are a little unconventional, in that a single user can match multiple `status` params, whereas other element types will typically only match a single one. (An entry is _either_ disabled, pending, live, or expired, but never multiple of those.) Which is why the `status` param doesn’t support beginning with `and`.

The `status` param is really just a shortcut for typing a condition manually using `andWhere()` though, so you could specify the exact condition you want like so:

```php
$pendingRegistrations = User::find()
    ->andWhere([
        'users.pending' => true,
        'users.suspended' => true,
    ])
    ->orderBy('dateCreated DESC')
    ->all();
```

On a related note, I just realized that `status('pending')` was _excluding_ suspended users, which doesn’t really make any sense post-3.5 with the new “Suspend by default” user registration setting. So I just removed that condition for the next release.

**Comment by MoritzLost** [comment]
@brandonkelly Thank you! Works nicely, I just had to add `anyStatus()` to the query to remove the default status condition that excludes pending/suspended users. So this is the final query that appears to be working and only returns users with both statuses:

```php
$pendingRegistrations = User::find()
    ->anyStatus()
    ->andWhere([
            'users.suspended' => true,
            'users.pending' => true,
        ])
    ->lastLoginDate(':empty:')
    ->orderBy('dateCreated DESC')
    ->all();
```

**Comment by MoritzLost** [comment]
@brandonkelly Small follow-up to this issue, I'm trying to update this functionality for Craft 4.2.7. The `Suspend by default` option has been replaced by the `Deactivate users by default` option, so new public registrations are now neither suspended nor pending. As far as I can tell, the only way to query for public registrations (that are deactivated by default) is to limit the query to inactive users that haven't logged in yet:

```php
$pendingRegistrations = User::find()
    ->status('inactive')
    ->lastLoginDate(':empty:')
    ->orderBy('dateCreated DESC')
    ->all();
```

But of course this finds _all_ inactive users that have never logged in, not just public registrations. As far as I can tell, there's no clear way to find only public registrations that are awaiting approval – correct?

For now I've just limited the query to users that were created within the last two weeks, though of course that's only a workaround:

```php
$cutoffDate = sprintf('>= %s', (new DateTimeImmutable())->modify('2 weeks ago')->format(DateTime::ATOM));
$pendingRegistrations = User::find()
    ->status('inactive')
    ->lastLoginDate(':empty:')
    ->orderBy('dateCreated DESC')
    ->dateCreated($cutoffDate)
    ->all();
```

Is there a better way to find public registrations waiting for approval? The only solution I can think of is to keep track of public registrations with a custom field.

**Comment by brandonkelly** [comment]
@MoritzLost I’d suggest creating a user group specifically for publicly-registered members, and set it as the default user group from Settings → Users → Settings. Then you can search for inactive users in that user group.
