### ISSUE TITLE
Error 400 on saving Entries - Request missing required body param - EntryRevisionsController

### ISSUE THREAD

**Issue by iwe-hi** [craftcms/cms#10369]
### Description
When saving an entry, an error 400 (Request missing required body param) occurs. New Drafts can be saved and entries can be created, but new entries can not be activated. It doesn't matter wich fields are filled, even with empty fields the error occurs. 

![image](https://user-images.githubusercontent.com/78907655/149741075-b20bca92-ac9b-414d-819c-7db4a2792e1b.png)

### Steps to reproduce

1. Create a new entry.
2. Save draft
3. Activate Entry

### Additional info

- Craft version: 3.7.28
- PHP version: 7.4.12 & 7.4.26 (both tested)
- Database driver & version: MySQL 5.7.32
- Plugins & versions: none were activated

**Comment by timkelty** [comment]
@iwe-hi this sounds similar to https://github.com/craftcms/cms/issues/9885

Can you reproduce this as an admin, or do you need to be a specific user?

Could you send anything I would need to reproduce this to support@craftcms.com (a database dump, your composer.json/lock files)?

**Comment by iwe-hi** [comment]
We could solve the problem. There were wrong entry uri formats set in the structure settings. Thank you for your help @timkelty
