### ISSUE TITLE
Slow search after v3.7.14 with MariaDB

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/cms#10377]
### Description

Following the upgrade to CMS 3.7.14, search queries are now much slower for our Craft install. On our site search page, this has caused average page load times that are now 3–4 times longer (going from just over 2s to now 6–9s).

I temporarily downgraded to 3.7.13 to confirm the version change was when this started, and the results were noticeable (~200ms queries on 3.7.13 vs. 1000ms+ on 3.7.14). I also did a DB dump and tested 3.7.14 on a MAMP host with MySQL, and the queries were 20–25ms instead of 1000ms+.

It seems like the slow speed we're experiencing with search queries is related to the fact that our production environment is running MariaDB as opposed to regular MySQL.

### Additional info

- Craft version: Pro 3.7.28
- PHP version: 7.4.5
- Database driver & version: MariaDB 10.6.5

**Comment by timkelty** [comment]
@jmauzyk it sounds like we should take the the 2 variables here one at at time (mariadb vs mysql, and 3.7.13 vs 3.7.14).

You're saying you're able to reproduce the query performance degradation locally by going from 3.7.13 vs 3.7.14?

**Comment by timkelty** [comment]
@jmauzyk can you send a db dump and `composer.json/lock` files to support@craftcms.com?

**Comment by timkelty** [comment]
> On a Nitro environment with MariaDB, CP search queries were faster on 3.7.14 than on 3.7.13.

Indeed, there were search performance improvements in 3.7.14.

I'll get back to you after I set up a local test!

**Comment by timkelty** [comment]
From support:

> Running craft db/convert-charset immediately solved the slow queries
