### ISSUE TITLE
Invalid temporary file path

### ISSUE THREAD

**Issue by CharlieGentle** [craftcms/cms#10382]
### Description

Upgraded from Craft 3.7.25.1 to 3.7.27.2. Our module that generates and saves an asset is no longer working. 

Logs show
`[warning][application] Prevented saving /var/www/html/storage/runtime/assets/tempuploads/tempfile-114674.pdf as an asset. It must be located within a temp directory or the project root (excluding system directories).`

This then caused
`Error: Call to a member function saveFileLocally() on null in /var/www/html/vendor/craftcms/cms/src/elements/Asset.php:2242
`
We were using `Craft::$app->getPath()->getTempAssetUploadsPath()` but this no longer counts as a valid path. Changing to `Craft::$app->getPath()->getTempPath()` has fixed it but not sure which we should be using.

### Steps to reproduce

1. Use `Craft::$app->getPath()->getTempAssetUploadsPath()` to generate a temporary file path.
2. Create new `Asset()`
3. Set `$asset->tempFilePath` using this temporary path

### Additional info

- Craft version: 3.7.27.2
- PHP version: 7.3
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

**Comment by brandonkelly** [comment]
Nothing has changed with `getTempAssetUploadsPath()`. Sounds like maybe a file permissions issue, which could be preventing `storage/runtime/assets/tempuploads/` from getting created, or preventing PHP from reading/writing to it.

**Comment by CharlieGentle** [comment]
I'm getting the same error on out live environment and my local set up and both look like they have permissions set up correctly.

Changing the array at https://github.com/craftcms/cms/blob/develop/src/elements/Asset.php#L2321 to include the path from `getTempAssetUploadsPath()` also fixes the problem.

**Comment by brandonkelly** [comment]
Ahh, right, that makes sense. Just added the folder to that array for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.30 is out now with that change.
