### ISSUE TITLE
Desktop mode is broken in live preview

### ISSUE THREAD

**Issue by ivanBereznev** [craftcms/cms#10380]
### Description
When in desktop mode live preview iframe has height of 150px, which hides most part of content.
With Craft 3.7.26 and the same content desktop mode works fine, but after upgrade to 3.7.29 it does not. I suppose that the issue was introduced by https://github.com/craftcms/cms/commit/26d3c8e24191f1c01ebd9bf9e8bfb701d1cea39a

### Steps to reproduce

1. Set up live preview app that will display your content
2. Try to open live preview from CP
3. See that Tablet and Mobile modes seem to work fine, but desktop mode shows only small part of content it should display.

### Additional info

- Craft version: 3.7.29
- PHP version: 7.3.31
- Database driver & version: PostgreSQL 13.5
- Plugins & versions:

**Comment by denisyilmaz** [comment]
same here. it seems the height of the `.lp-device-preview-container` gets overwritten via the `_preview.scss`file:

![image](https://user-images.githubusercontent.com/4189607/150119158-a71a412f-19b7-4c6d-8a75-36cf4e829203.png)

**Comment by brandonkelly** [comment]
Thanks for pointing that out. I had been testing with `useIframeResizer => true` which wasn’t affected by the bug, so missed it. Fixed for the next release, which we’ll get out tomorrow.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.29"` and run `composer update`.

**Comment by brandonkelly** [comment]
3.7.30 is out now with that fix.
