### ISSUE TITLE
Provide 'Save' button at top of Field Layout as well as bottom

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1038]
> Created by: Brendan Underwood (bunderwood@brandagency.com.au) on 2015/09/11 08:36:47 +0000
> Votes at time of UserVoice import: 5

-----------------------------------

Quite often when setting up field layouts when there's quite a lot of fields available for selection, I've backed out of the tab without saving because the 'Save' button is pushed way out of view. Any chance it could also be shown at the top somewhere too.

**Comment by brandonkelly** [comment]
The Save button is always visible in Craft 3.
