### ISSUE TITLE
New category button broken 

### ISSUE THREAD

**Issue by mofman** [craftcms/cms#10399]
### Description

New cateogory button from CMS does not work, nothing happens when the user clicks the button.

### Steps to reproduce

1. Open CMS, go to Categoris
2. Press new category

### Additional info

- Craft version: Craft CMS 3.7.30
- PHP version: 7.4
- Database driver & version:
- Plugins & versions:

**Comment by mofman** [comment]
Seems this is the broken code `<button class="btn submit add icon" href="XXXXX" aria-label="New category">New category</button>`

Entries button works okay

`<a class="btn submit add icon" href="XXXXX" role="button" tabindex="0">New entry</a>`

**Comment by brandonkelly** [comment]
Thanks for reporting that! We just released 3.7.30.1 with a fix.
