### ISSUE TITLE
3.7.30.1 Redis mutex implementation migration error

### ISSUE THREAD

**Issue by DA-HarryCooper** [craftcms/cms#10409]
### Description
When implementing mutex using redis as shown in the docs https://craftcms.com/knowledge-base/configuring-load-balanced-environments#mutex-locks the following error occurs. 
![image](https://user-images.githubusercontent.com/79839672/151025275-548ab584-3ff4-4faf-b534-8f8356c552f6.png)

When implementing as shown this seems to work correctly
![image](https://user-images.githubusercontent.com/79839672/151025461-804da787-ddff-47d2-9d43-292826e14525.png)

### Steps to reproduce
1. Update to Craft 3.70.30.1
2. Add the mutex component as shown below 
'components' => [
        'mutex' => [
            'mutex' => 'yii\redis\Mutex',
        ],
    ],
3. Run migrate all.
### Additional info
We're already running redis and so details were not required within the mutex component.

**Comment by timkelty** [comment]
@DA-HarryCooper that would seem to indicate that you are not actually running the latest code…

> Update to Craft 3.70.30.1

I'm assuming you mean `3.7.30.1`?

Can you double check in the CP (`/admin/utilities/system-report`) to verify your running Craft version?

**Comment by DA-HarryCooper** [comment]
![image](https://user-images.githubusercontent.com/79839672/151136410-b6d25c42-8947-4575-8c1b-45ed99544149.png)

**Comment by timkelty** [comment]
And you have `yiisoft/yii2-redis` required as a composer dependency, yes? And is your redis configured under a component with a key of `redis`?

If you could send over you `composer.json/lock` files and your `config` dir to support@craftcms.com, I can take a deeper look.

**Comment by DA-HarryCooper** [comment]
Hi Tim

Thanks for the fast response, I've e-mailed over the requested information.

All the best
Harry
