### ISSUE TITLE
Prompted twice to "Copy impersonation URL"

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#10423]
The (amazing) feature to "Copy impersonation URL" uses confusing language, and/or involves an unnecessary extra step.

As you'll notice, you will be prompted **twice** to "Copy impersonation URL". This leads to some confusion, because I always believe that the impersonation URL has been copied to my clipboard **the first time I select "copy"**.

<img width="363" alt="step-1@2x" src="https://user-images.githubusercontent.com/5309692/151441060-6cef405b-9183-415b-bed0-30e90232f1d1.png">

Instead, a small modal opens up, with yet another prompt to "copy" the URL. I thought I just did that?

<img width="558" alt="step-2@2x" src="https://user-images.githubusercontent.com/5309692/151441092-591f1bc2-6071-4df9-bbeb-b06a31a0b826.png">

Many (many) times, I begin to navigate away to a new browser window before realizing that I forgot to "copy" the URL a second time. 🤦‍♂️ 

### Steps to reproduce

1. Go to any User other than yourself.
2. Click the gear in the sidebar, and select **Copy impersonation URL**
3. In the modal, notice that you are _again_ being prompted to **Copy the impersonation URL**

### Proposed solution

Either of these would work...

- **Change the verbiage** of the first prompt to say "Get impersonation URL". That is more ambiguous, and leaves room for a follow-up step.
- **Combine them into a single step**, and have the first "copy" prompt _actually_ save it to your clipboard.

I could see a reasonable case for either solution, but the first one is obviously much quicker and easier.

### Additional info

- Craft version: 3.7.29

**Comment by thupsi** [comment]
Hmm, maybe it should say "Show impersonation URL"?

**Comment by brandonkelly** [comment]
Added an ellipsis to the end of “Copy…” actions, so help indicate that there will be an additional step.

<img width="258" alt="A user action menu showing that “Copy password reset URL” and “Copy impersonation URL” action labels end with an ellipsis now" src="https://user-images.githubusercontent.com/47792/151576554-9e2210ce-68d4-4aa4-be82-c5479456a89e.png">

**Comment by lindseydiloreto** [comment]
That works, thanks @brandonkelly! 👍
