### ISSUE TITLE
Invalid site ID when linking to disabled site

### ISSUE THREAD

**Issue by bavodeclercq** [craftcms/cms#10421]
### Description
When you link to an entry from a disabled site you'll get the following error: `Invalid site ID: ` with the site id.

### Steps to reproduce

1. Create two sites with different languages.
2. Add some content to Redactor field and link something (word, sentence, ...) to an entry.
3. Disable site A for the front-end
4. Go the entry on the front-end for site B.

### Additional info

- Craft version: 3.5.16
- PHP version: 7.4.11
- Database driver & version: MySQL 8.0.21

**Comment by andris-sevcenko** [comment]
Here's the relevant stack trace:
```
2022-01-27 03:41:59 [-][2][uqu9pqj3b2552kecn26r4rlnkh][error][yii\base\Exception] yii\base\Exception: Invalid site ID: 5 in /app/repos/craft.37/src/helpers/UrlHelper.php:325
Stack trace:
#0 /app/repos/craft.37/src/base/Element.php(2529): craft\helpers\UrlHelper::siteUrl()
#1 /app/sites/37.craft.nitro/vendor/yiisoft/yii2/base/Component.php(232): craft\base\Element->getUrl()
#2 /app/repos/craft.37/src/base/Element.php(1731): yii\base\Component->__isset()
#3 /app/repos/craft.37/src/services/Elements.php(2981): craft\base\Element->__isset()
#4 /app/repos/craft.37/src/services/Elements.php(2041): craft\services\Elements->_getRefTokenReplacement()
#5 /app/repos/redactor/src/FieldData.php(43): craft\services\Elements->parseRefs()
```

**Comment by brandonkelly** [comment]
Got this fixed for the next Craft release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.30.1"` and run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.7.31 is out now with that fix.
