### ISSUE TITLE
Garnish Modal error (for Vizy WYSIWYG link button)

### ISSUE THREAD

**Issue by engram-design** [craftcms/cms#10428]
I'm getting an error in Vizy due to some changes in Garnish. Not sure if I should be posting at the original location (https://github.com/pixelandtonic/garnishjs/pull/16) or here, as Garnish seems to have been pulled into this repo now.

More detailed issue [here](https://github.com/verbb/vizy/issues/97) but essentially just clicking on the "Add an entry" link in Vizy (which is just about identical to Redactor) triggers the below incorrect code. It's reproducible with minimal effort if you need to check (just create a Vizy field with no blocks - plain WYSIWYG with a link button).

https://github.com/craftcms/cms/blob/5bed2245333005beb0402cd3609cb0698d57bac9/src/web/assets/garnish/src/Garnish.js#L323

This should be `$(element).addClass(Garnish.JS_ARIA_TRUE_CLASS);` as this is otherwise invalid jQuery. I'm not exactly sure why Redactor is fine, and Vizy isn't, as we're both calling `Craft.createElementSelectorModal()` but it is what it is!

Changing this line seems to fix the issue.

**Comment by brandonkelly** [comment]
Craft 3.7.31 is out now with a fix for this. Thanks for reporting!
