### ISSUE TITLE
Dynamic entry title not updated with post date change

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#10425]
### Description
I have set a section's default entry type's title as follows:

`entry.postDate|date("l j M Y")}`

On initial entry creation this works as expected, but if I change the post date and save again, the title is not updated.

I think this used to work differently. Am I missing something?

### Steps to reproduce

1. Set an entry type's title as indicated above
2. Create a new entry of that type.
3. Change the post date and save.
4. Observe that the title is not updated to reflect the new post date

### Additional info

- Craft version: Craft Pro 3.7.30.1
- PHP version: 7.4.14
- Database driver & version: MySQL 5.5.5
- Plugins & versions: 
    - Amazon S3	1.3.0
    - AsyncQueue	2.3.0
    - Bulk Edit	2.0.6
    - Command Palette	3.1.4
    - Knock Knock	1.2.16
    - Obfuscator	1.0.4
    - Preparse Field	1.2.5
    - Redactor	2.8.8
    - Tags	1.0.9
    - Webhooks	 2.4.1

**Comment by timkelty** [comment]
@thupsi `entry` is a defined variable in this context: https://craftcms.com/docs/3.x/entries.html#dynamic-entry-titles

You can use `object` or use the properties of the entry directly:

```
{{ object.postDate|date('"l j M Y"') }}
{postDate|date('"l j M Y"')}
```
