### ISSUE TITLE
SEOmatic Field error Component class 'nystudio107\seomatic\fields\SeoSettings' belongs to a disabled plugin (SEOmatic).

### ISSUE THREAD

**Issue by joepagan** [craftcms/cms#10437]
### Describe the bug

Get this field error:

![image](https://user-images.githubusercontent.com/2337910/151623788-2113102f-2554-4579-b52c-61c116fa0f67.png)

Despite the plugin being enabled:

![image](https://user-images.githubusercontent.com/2337910/151623913-9cd9f7c4-e6a9-4f42-a4bc-71eae4585946.png)

some context, I've had this plugin installed for a while, applied the fields, disabled a little while on a local app, done a couple of craft updates while it was disabled, and a ./craft update on seomatic itself (while disabled).

Let me know if you need more info

Logged this here, but suggested to be a craft issue:
https://github.com/nystudio107/craft-seomatic/issues/1052

### To reproduce
Steps to reproduce the behaviour:

disable/enable - no difference
uninstall/install - no difference

### Expected behaviour

no error when plugin enabled

### Versions
- seomatic version: 3.4.22
- Craft version: 3.7.27.2
- Database driver & version: `mariadb:10.2.31`

**Comment by khalwat** [comment]
Happy to help if this has anything to do with SEOmatic, but I don't think it does. SEOmatic doesn't do anything special in terms of being installed or not, that's handled by Craft.

**Comment by brandonkelly** [comment]
Try running `php craft project-config/rebuild` and see if that helps.

**Comment by joepagan** [comment]
Unfortunately that just applied some minor field changes, plugin is still "installed" but the field claims that it is disabled:

```sh
modified:   cms/config/project/fields/promotions--2c6b99fb-f3e0-4e06-aff8-b93a68ef5aec.yaml
	modified:   cms/config/project/neoBlockTypes/bannerCta--50b41699-5721-412d-a94c-49d8d595fd82.yaml
	modified:   cms/config/project/neoBlockTypes/certifications--62a4959a-67e5-4c98-9b4e-5c4c4db921d5.yaml
	modified:   cms/config/project/neoBlockTypes/copy--49cd7dfa-3cd0-4fd8-8e30-3ad3dd819333.yaml
	modified:   cms/config/project/neoBlockTypes/downloads--a9a5329f-0ab6-4158-9858-eaac755f0914.yaml
	modified:   cms/config/project/neoBlockTypes/fullWidthImage--d729ec4f-52f9-401c-9b6a-62ce82c67244.yaml
	modified:   cms/config/project/neoBlockTypes/imageWCaption--1fedce25-0547-48ca-bd2c-81c08319b547.yaml
	modified:   cms/config/project/neoBlockTypes/products--8a5be010-7736-4d1c-a7e8-276b78e1cd1a.yaml
	modified:   cms/config/project/neoBlockTypes/promotions--1fabfe9a-e921-4bb5-9edd-ddeef82f4616.yaml
	modified:   cms/config/project/neoBlockTypes/recentArticles--db433e67-157c-4d4d-a39c-0139e283fb9a.yaml
	modified:   cms/config/project/neoBlockTypes/splitImageWText--df1a8020-65e7-4497-9d80-f7b75fceeb3e.yaml
	modified:   cms/config/project/neoBlockTypes/summary--34c185a9-80bc-46da-b4f6-68642fd4c357.yaml
	modified:   cms/config/project/neoBlockTypes/table--362aa847-e9da-4d90-809f-5fd5135e310e.yaml
	modified:   cms/config/project/neoBlockTypes/testimonials--5658586f-9d9b-4f9d-9d4d-0952e0fec9ff.yaml
	modified:   cms/config/project/neoBlockTypes/tiles--52bfec7c-9f23-41d2-8442-62cba7a17f02.yaml
	modified:   cms/config/project/project.yaml
```

```diff
diff --git a/cms/config/project/fields/promotions--2c6b99fb-f3e0-4e06-aff8-b93a68ef5aec.yaml b/cms/config/project/fields/promotions--2c6b99fb-f3e0-4e06-aff8-b93a68ef5aec.yaml
index 6d2f5f4..2fdeb55 100644
--- a/cms/config/project/fields/promotions--2c6b99fb-f3e0-4e06-aff8-b93a68ef5aec.yaml
+++ b/cms/config/project/fields/promotions--2c6b99fb-f3e0-4e06-aff8-b93a68ef5aec.yaml
@@ -7,7 +7,7 @@ name: Promotions
 searchable: false
 settings:
   allowSelfRelations: false
-  limit: ''
+  limit: '2'
   localizeRelations: false
   selectionLabel: ''
   showSiteMenu: true
diff --git a/cms/config/project/neoBlockTypes/bannerCta--50b41699-5721-412d-a94c-49d8d595fd82.yaml b/cms/config/project/neoBlockTypes/bannerCta--50b41699-5721-412d-a94c-49d8d595fd82.yaml
index eb26622..56da4ef 100644
--- a/cms/config/project/neoBlockTypes/bannerCta--50b41699-5721-412d-a94c-49d8d595fd82.yaml
+++ b/cms/config/project/neoBlockTypes/bannerCta--50b41699-5721-412d-a94c-49d8d595fd82.yaml
@@ -1,4 +1,4 @@
-childBlocks: ''
+childBlocks: null
 field: e74c84eb-9b44-4981-b6c4-c7fa337b02a8 # Main
 fieldLayouts:
   c3ee2aef-1c1d-491d-bd85-2d2495846bfc:
diff --git a/cms/config/project/neoBlockTypes/certifications--62a4959a-67e5-4c98-9b4e-5c4c4db921d5.yaml b/cms/config/project/neoBlockTypes/certifications--62a4959a-67e5-4c98-9b4e-5c4c4db921d5.yaml
index 5845a40..83f7963 100644
--- a/cms/config/project/neoBlockTypes/certifications--62a4959a-67e5-4c98-9b4e-5c4c4db921d5.yaml
+++ b/cms/config/project/neoBlockTypes/certifications--62a4959a-67e5-4c98-9b4e-5c4c4db921d5.yaml
@@ -1,4 +1,4 @@
-childBlocks: ''
+childBlocks: null
```

**Comment by brandonkelly** [comment]
Strange… not really sure what to make of that. Can you please send your Composer files and a database backup into support@craftcms.com? We can try to look into it from there.

**Comment by joepagan** [comment]
Just shared that with you. Let me know if you need anything else.

**Comment by brandonkelly** [comment]
Just released 3.7.32 which resolves this:

1. If a field was saved while its component type was missing (either because the plugin wasn’t installed or it was disabled), but then you enable the field type and re-access the field’s edit page, Craft will now instantiate a new copy of the field type for you, rather than show you that message about the field type class being missing. Unfortunately that’s the best we can do here – the field type’s content has already been erased, so reinstantiating the original field would result in SQL errors. So…
2. It’s also no longer possible to save a field while its field type is missing, to avoid this whole mess going forward.

**Comment by joepagan** [comment]
Thanks for investigating, fixing and the quick release. That sounds like it'll handle that better.

No worries on the content, nothing of value was lost!

**Comment by joepagan** [comment]
Looks like this is still an issue if it could be re-opened? Sent my latest DB and composer files (post craft-update) on 2022-02-10 let me know if you need anything else.
