### ISSUE TITLE
problem with position of plugin icon and links in rtl plugins page

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#10439]
There are some problem with position of plugin icon and links in rtl plugins page

![1 - Copy (2)](https://user-images.githubusercontent.com/55586085/151676256-0973351b-5541-4224-9637-ec9f55c76055.jpg)

changing [this line](https://github.com/craftcms/cms/blob/0acd19f4dd08a8b84ddf12ad5b3612fd47691e74/src/web/assets/plugins/src/plugins.scss#L24) to padding-left and [this line](https://github.com/craftcms/cms/blob/0acd19f4dd08a8b84ddf12ad5b3612fd47691e74/src/web/assets/plugins/src/plugins.scss#L186) to margin-right only for rtl pages solves the issue

![2 - Copy](https://user-images.githubusercontent.com/55586085/151676263-fd4144e7-74f9-4bbf-be7a-81781a4d0b1a.jpg)

**Comment by timkelty** [comment]
Thanks for reporting, @vnali! Will be fixed with the next Craft release.
