### ISSUE TITLE
Plugin loading order is not deterministic

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#10441]
Currently `services/Plugins` loads plugins with this query:

```php
            $pluginInfo = $this->_createPluginQuery()
                ->indexBy('handle')
                ->all();
```

ref: https://github.com/craftcms/cms/blob/develop/src/services/Plugins.php#L198

Unfortunately, this means that plugin loading order is not deterministic; it depends on in what order plugins are installed. This makes it difficult to track down issues such at this one in SEOmatic, because plugins will load in a different order on Site A than Site B:

https://github.com/nystudio107/craft-seomatic/issues/654#issuecomment-1020308109

...where the issue only happens if SEOmatic is installed _before_ Craft Commerce is installed. So obviously an issue on my end that will be fixed, but I think it would make diagnosing issues such as this easier if plugins were always loaded in a deterministic order, just like MacOS kernel extensions and other such things are.

So I propose changing the query to:

```php
            $pluginInfo = $this->_createPluginQuery()
                ->indexBy('handle')
                ->orderBy(['handle' => SORT_ASC])
                ->all();
```

...so that plugins will always be loaded in a deterministic order, alphabetically by their plugin handle.

While it may seem like it's a breaking change in terms of affecting the loading order of plugins, you're actually making that same breaking change yourself every time you install or uninstall a plugin.

Deterministic loading order across sites is always better than random on a per-site basis, based on a hidden variable (install order)

Related: https://github.com/craftcms/cms/issues/3028

**Comment by brandonkelly** [comment]
Fixed for the next release!

Now we wait for someone to release “AAA SEO”…

**Comment by khalwat** [comment]
Yeah, I know, I know re: "AAA SEO" but at least it'll be the same on every install. I'm with @AugustMiller that plugins should be agnostic about loading order, but this will make it easier to debug when something goes wrong.

Thx @brandonkelly !

**Comment by brandonkelly** [comment]
3.7.31 is out now with that change.
