### ISSUE TITLE
GraphQL get all users using (status: null) does not work in other tool than GraphiQL

### ISSUE THREAD

**Issue by timbertens** [craftcms/cms#10440]
### Description
We're trying to load all users from different in sites into another system.  The GQL that is being used is 
```
query {
            users (status: null) {
              uid
              username
              firstName
              lastName
              email
              preferredLanguage
              status
              dateCreated
              dateUpdated
            }
        }
```
When executing this query in GraphiQL within CraftCMS all is fine.  When executing this exact query from external tool or code this the error response

```
{
	"errors": [
		{
			"message": "Unknown argument \"status\" on field \"users\" of type \"Query\".",
			"extensions": {
				"category": "graphql"
			},
			"locations": [
				{
					"line": 2,
					"column": 9
				}
			]
		}
	]
}
```

Just for sake of completeness, when executing the query without the filter all is fine (but of course only the users with status 'active' are returned)

### Steps to reproduce

1. Execute query in GraphiQL = OK
2. Execute exacte same query in Insomnia = Fail

### Additional info

- Craft version: 3.7.30.1
- PHP version: 7.4.27
- Database driver & version: MySQL 5.7.36

**Comment by andris-sevcenko** [comment]
You have to enable the `Allow listing non-live and otherwise inactive elements` setting for the `status` argument to be available.

We probably should improve wording there.

**Comment by timbertens** [comment]
ok thanks, that solved it!  I believe it might help also if the GraphiQL module would honour these settings too, as the query works there without this setting enabled

**Comment by andris-sevcenko** [comment]
@timbertens you probably have the "Full schema" selected in the Schema dropdown. If you select the right schema, it will respect that :)

**Comment by timbertens** [comment]
@andris-sevcenko you're right ... never program on a Saturday evening ;-)
