### ISSUE TITLE
Cannot restore DB from backup taken from a different instance using PostgreSQL

### ISSUE THREAD

**Issue by ivanBereznev** [craftcms/cms#10443]
### Description
Important note: I use Craft CMS with PostgreSQL.

I have two instances: instance A has some content, and B does not have content yet. I want to move content from instance A to B. Since there is [no import\export yet](https://github.com/craftcms/cms/discussions/9179) the only way I see is to create a DB backup at instance A and then restore it at B.
When restoring DB at B I got a series of errors related to constraint violation, because restore was not able to remove tables and constraints. As a result, when data got restored, DB state was a mix of state from Craft installation at B and content restored from the backup. For example, sections remained in the original state, but entries got restored with section IDs from A instance, which breaks pretty much everything when it comes to content editing and usage.

I think this all happens because of unique constraint names which are generated by PostgreSQL when no name is specified when the constraint is created.

### Steps to reproduce

1. Set up two Craft CMS instances with PostgreSQL and the same project config (with custom fields, sections etc.)
2. Add some entries to the first instance
3. Create a DB backup at the first instance
4. Move the backup to the second instance and restore it

Expected: DB state at the second instance is replaced with the state from the backup file.

Actual: DB state is broken, it contains a mix of backup and original records.

Workaround: workaround here would be to remove all tables and constraints from DB of the second instance (or to re-create the DB and do not install Craft) before restoring the backup.

### Additional info

- Craft version: Craft Pro 3.7.29
- PHP version: 7.3.33
- Database driver & version: PostgreSQL 11.11
- Plugins & versions:

**Comment by ivanBereznev** [comment]
@hiasl well, I did some testing and looks like it does not happen all the time. I see constraint violation errors during restore consistently, but to actually reproduce the error I was talking about backup should contain section IDs different from ones in DB that data is restored to. Not sure how that happens, but I think sections are created when config is being applied and Craft does not really control IDs assigned to them by DB. Probably DB should be in some certain state to reproduce the issue, but I've definitely seen it several times when tried to move data between instances.
As for privileges and public schema, all instances have the same setup and DB user has full access to the DB that Craft uses. Schema is public.

**Comment by hiasl** [comment]
ok, this must be something specific to your installation as we do not get any constraint violations. maybe the P&T team can help.

**Comment by timkelty** [comment]
@ivanBereznev Can you share exactly how you are dumping restoring?

Are you using `craft backup/db` `craft restore/db`, or `pg_dump`, `pg_restore`, or `psql`.

Please share the exact commands with any flags (if using the `craft` commands, confirm if you have set the `backupCommand` or `restoreCommand` config settings.

**Comment by ivanBereznev** [comment]
@timkelty last time the error was reproduced backup was created via [remote sync plugin](https://plugins.craftcms.com/remote-sync) which internally uses `Craft::$app->getDb()->backupTo()` method to create a backup, so should be pretty much equal to `craft db/backup` in terms of the command being executed. And restore was done via `craft db/restore`. There are no custom commands for backup and restore specified in config, so Craft uses default commands.
When I will have time I will do more experiments to figure out what exactly causes the issue.

**Comment by timkelty** [comment]
@ivanBereznev thanks – if you can get reproducible to/from databases, send em along to support@craftcms.com

**Comment by ivanBereznev** [comment]
@timkelty thank you. Just managed to reproduce it once again and sent backups to the support email
