### ISSUE TITLE
Live preview not refreshing for Pending entries

### ISSUE THREAD

**Issue by timprint** [craftcms/cms#10455]
I have a channel section using an entry url and associated template. Live previews are using the same template.

Previews work fine for Live entries but for Pending entries they don't update.
The preview appears OK for Pending entries and it seems to refresh when you make amends to the entry but the amends do not appear on the preview. The preview never changes from how it looks when it is first accessed.

If you go to "Save and continue editing" then Preview again the changes are there.

So you have to save the entry to see any changes to the live preview for Pending entries.

- Craft version: 3.7.28
- PHP version: 7.3.33
- Database driver & version: MySQL 5.7.37
- Plugins & versions:
-- Ad Wizard 3.1.3
-- Cookies 1.1.15
-- Freeform 3.12.11
-- Imager v2.4.0
-- Redactor 2.8.8
-- SEOmatic 3.4.22
-- Sprout Notes 2.2.3
-- Redirect Manager 1.1.1

**Comment by timkelty** [comment]
@timprint Confirm this behavior. Will have a fix out shortly

**Comment by brandonkelly** [comment]
Got this fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.31 is out now with that change.
