### ISSUE TITLE
Craft4 - DB requirements checker, mis match version regexp.

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#10456]
### Description

1. Created a new Craft 4 (alpha) project. 
2. Installer did not recognise MariaDB version

Maria DB was installed with Brew.

`$version = $conn->getAttribute(PDO::ATTR_SERVER_VERSION);` reports: `5.5.5-10.6.4-MariaDB`. 

![Screen Shot 2022-02-01 at 11 35 43 am](https://user-images.githubusercontent.com/25124/151895643-35d2b49c-ebb7-49e1-b5ff-bdb57f727c7f.png)

### Additional info

- Craft version: 4.0-alpha
- PHP version: 8.0.12
- Database driver & version: MariaDB (5.5.5-10.6.4-MariaDB) 
- Plugins & versions:

**Comment by brandonkelly** [comment]
Search `composer.lock` for `"name": "craftcms/server-check"`. What version are you running? Should be 2.0.1.

**Comment by aelvan** [comment]
Same issue, running MariaDB 10.5.8 from homebrew. `"name": "craftcms/server-check"` is `2.0.1`. 

I first got this in the web installer. Then tried installing via the cli, and it went through and everything worked fine. Then a day later while using the CP, this version error popped up:

![image (7)](https://user-images.githubusercontent.com/2675644/152643887-d5532afd-2875-4f28-a916-59a04d4231b4.png)

**Comment by leevigraham** [comment]
@brandonkelly `2.0.0`
![Screen Shot 2022-02-07 at 9 24 42 am](https://user-images.githubusercontent.com/25124/152704030-a72e0768-0800-4323-afb9-df94efaafee3.png)

**Comment by brandonkelly** [comment]
What does this output?

```php
echo Craft::$app->db->pdo->getAttribute(\PDO::ATTR_SERVER_VERSION);
```

**Comment by aelvan** [comment]
For me it returns `5.5.5-10.5.8-MariaDB`.

Today I can log into the CP again without getting the error. In the system report under "Database driver & version" it says "MySQL 5.5.5".

**Comment by leevigraham** [comment]
@brandonkelly 

```
echo Craft::$app->db->pdo->getAttribute(\PDO::ATTR_SERVER_VERSION);
```

outputs: `5.5.5-10.6.4-MariaDB`

**Comment by brandonkelly** [comment]
Thanks! This is fixed now. Run `composer update` and you should be good to go.
