### ISSUE TITLE
problem with position of expand status button in rtl CP pages

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#10459]
![100 - Copy](https://user-images.githubusercontent.com/55586085/152036871-9f23bc34-81a3-4a99-afb6-3448c1775ce6.jpg)

changing [this line](https://github.com/craftcms/cms/blob/783f942bb75587ae0f2efd7ab266149a9564d127/src/web/assets/cp/src/css/_main.scss#L4942) to margin-right for RTL pages solves the issue

![11 - Copy](https://user-images.githubusercontent.com/55586085/152036908-320e0142-5021-45b9-acf2-239aeb125869.jpg)

**Comment by brandonkelly** [comment]
Craft 3.7.31 is out now with those fixes. Thanks!
