### ISSUE TITLE
Global sets aren't being created when applying the project config

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#10458]
### Description

Since one of the latest Craft versions we're experiencing a bug with new global sets not being created when applying the project config. I've confirmed this issue exists in multiple different Craft projects, so it's not project specific or caused by any project-specific hook or something like that.

The issue seems to only occurs when I'm applying a project config and that should create a global set that _has already existed in this installation_ at some point, but was removed. Consider the following situations:

1. My colleague creates a PR including the YAML file for an additional global set. I pull the branch and apply the config, the global set is created correctly and appears in the CMS. However, if I check out a different branch and apply the config (which removes the global set), then go back to the PR branch and apply the config again, the global set is not created and does not appear in the backend.
2. I create a new global set in my test environment, then use `git stash` to remove the YAML file for this global set from the working directory. Now I apply the config, this removes the global set from the backend. Then I restore the YAML file (`git stash pop`) and apply the config again – the global set is not created and does not appear in the background.

I've tried to pin down where the error is occuring. The log messages for `project-config/apply` indicate that Craft does see the new config file and applies it:

```
- updating dateModified ... done
- adding globalSets.4e0f029a-1151-4ac7-b190-5985195502b2.fieldLayouts.ea63e9f8-75d6-453c-8e09-4c441b333e3f.tabs.0.elements.0 ... 
  - adding globalSets.4e0f029a-1151-4ac7-b190-5985195502b2 ... done
  done
- adding globalSets.4e0f029a-1151-4ac7-b190-5985195502b2.fieldLayouts.ea63e9f8-75d6-453c-8e09-4c441b333e3f.tabs.0.elements.1 ... done
- adding globalSets.4e0f029a-1151-4ac7-b190-5985195502b2.fieldLayouts.ea63e9f8-75d6-453c-8e09-4c441b333e3f.tabs.0 ... done
- updating meta.__names__ ... done
Finished applying changes
```

But the global set does not appear in the backend, despite the log message indicating it was added. So it looks like there's something going wrong between storing the project config in the database and actually performing the database changes required for the new global set. The behaviour shown by the write/rebuild commands confirms this:

1. `project-config/write` leaves the config file in place and even adds it back if it's deleted manually. So the global set does exist in the project config stored in the database.
2. `project-config/rebuild` removes the config file for the global set, indicating that the database structure for the global set is missing.

### Steps to reproduce

1. Create a new global set in the backend in a test environment where project config changes are automatically written.
2. Confirm there's a new config file in `config/project/globalSets`.
3. Use `git stash --include-untracked` to remove the file from the working directory (or move it outside the project folder manually).
4. `php craft project-config/apply`
5. Use `git stash pop` to restore the config file (or put it back manually).
6. `php craft project-config/apply` (`--force`)
7. Check the backend – the global set is not available in the backend and trying to access it in the frontend results in a undefined variable error.

### Additional info

- Craft version: 3.7.30.1
- PHP version: 8.1.1
- Database driver & version: MySQL 8.0

**Comment by brianjhanson** [comment]
Are you using Nitro by chance? I've recently run into this (I think), but only when using Nitro.

**Comment by MoritzLost** [comment]
@brianjhanson No, neither Nitro nor docker. We use [Laravel Valet](https://laravel.com/docs/8.x/valet) for our local environments, and create MySQL databases manually.

**Comment by andris-sevcenko** [comment]
Thanks for reporting that! Fixed it for the next release!

**Comment by brandonkelly** [comment]
Craft 3.7.31 is out now with that fix.
