### ISSUE TITLE
Redirecting to `/{cpTrigger}/requestProvider.js.map` on login

### ISSUE THREAD

**Issue by joshuabaker** [craftcms/cms#10476]
### Description

I’ve noticed that a couple of sites are redirecting to `/{cpTrigger}/requestProvider.js.map` when logging into the control panel.

```
yii\web\NotFoundHttpException
Template not found: requestProvider.js.map
```

I can’t figure out where this is coming from.

### Additional info

- Craft version: 3.7.30.1
- PHP version: 8.0.13
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Craft Copy 1.1.0 and Dashboard Begone 1.0.1

**Comment by brandonkelly** [comment]
Hm strange. Most likely the browser was requesting that file for some reason, the request got routed to Craft, and Craft is just remembering that that’s where they were headed so it redirects them back there after login. It’s not a Craft file so I’m not sure how the browser would have requested it to begin with.

Going to close but feel free to reach out to support@craftcms.com if you need further assistance with it.

**Comment by joshuabaker** [comment]
For posterity, this was caused by the Coinbase Wallet Chrome extension. At time of writing the issue remains.

**Comment by nucleare** [comment]
> For posterity, this was caused by the Coinbase Wallet Chrome extension. At time of writing the issue remains.

This proved to be extremely helpful in addressing a similar issue such as this while debugging a website though it had no relation to CMS. Thank you.

Due to this page's relevance in Google search, the Coinbase extensions caused two developer warnings (and with the hope that it adds to the purpose of posterity):

```
DevTools failed to load source map: Could not load content for chrome-extension://hnfanknocfeofbddgcijnmhnfnkdnaad/content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for https://{YOUR_SITE_URL}/requestProvider.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

Upon de-activating the Coinbase Wallet extension, these warnings ceased to exist.

**Comment by KenticoDevTrev** [comment]
Thank you, we ran into the same issue and he had coinbase :P

**Comment by gamaxandre** [comment]
Moi aussi même erreur avec extension Coinbase Wallet Chrome.
