### ISSUE TITLE
Transform on disabled site throwing 404

### ISSUE THREAD

**Issue by bavodeclercq** [craftcms/cms#10498]
### Description
A customer of ours wants to fill in a disabled site. When adding an image that has Craft transforms on it, the images are not shown. The link itself (en/actions/assets/generate-transform?transformId=171) displays the 404 page.

### Additional info

- Craft version: 3.7.29
- PHP version: 7.4.27
- Database driver & version: MySQL 8.0.19

**Comment by andris-sevcenko** [comment]
@bavodeclercq Where are you adding that image, though? Assets aren't site-specific.

**Comment by bavodeclercq** [comment]
@andris-sevcenko Image fields with 'Manage relations on a per-site basis' checked.

**Comment by brandonkelly** [comment]
This is now fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.38 is out now with that fix.
