### ISSUE TITLE
Error sending email: Expected response code 220 but got an empty respons(e)

### ISSUE THREAD

**Issue by dwheeldo** [craftcms/cms#10508]
### Description

Hi,

I have a strange issue with emails failing to send. I'm using Mailjet to send emails over SMTP, and even though my credentials work on local and staging, on production I'm getting an error in `web.log` - `[warning][application] Error sending email: Expected response code 220 but got an empty respons`

This error occurs for both test emails and emails for Express Forms notifications. Looking at the debug bar, it seems the problem's happening in the `yii\swiftmailer\Mailer::sendMessage` event

The server is hosted on Digital Ocean, via Laravel Forge, and its setup is the same as on staging (which is hosted on a separate droplet, but still on Digital Ocean/Forge).

### Steps to reproduce

1. Attempt to send any email
2. Get the error `[warning][application] Error sending email: Expected response code 220 but got an empty respons`

### Additional info

- Craft version: 3.7.30.1
- PHP version: 7.4.26

**Comment by brandonkelly** [comment]
Does the environment have a firewall that could be blocking outgoing traffic on your chosen SMTP port?

**Comment by dwheeldo** [comment]
@brandonkelly I don't believe so. I just ran `wget -qO- portquiz.net:587` on the server, and it returned a success message.

**Comment by brandonkelly** [comment]
Maybe the IP is denylisted on Mailjet’s end?

**Comment by dwheeldo** [comment]
You might be right. Mailjet's dashboard is a bit impenetrable, so maybe I need to give those guys a nudge. Thanks for your help anyway!

**Comment by dwheeldo** [comment]
Turns out the IP _was_ on Mailjet's blacklist! Apparently there's a whole Digital Ocean IP block associated with DDOS attacks, and it included the IP of our server.
