### ISSUE TITLE
Project config saves associative array data and comments inconsistently

### ISSUE THREAD

**Issue by BenParizek** [craftcms/cms#10512]
### Description

I hesitate to post this as I don't have a clean example to recreate the issue, but we've been seeing this cause conflicts regularly on a project for weeks (months?) and in my first complaints to someone outside our project about the problem they quickly said 'yes, I've seen that too'. So, seems like something is going on that I can't explain.

The issue has to do with project config being used within a team. Several different people are making local changes to the schema and pushing up changes on separate branches, as well as pulling down the most recent version of the project and re-syncing it to get the database in sync again. It's possible some of the issue, such as with some conflicts, could be caused by our workflow, but some of the issues just seem to be Craft changing things in different ways that we never intended to touch.

The two main issues I've seen, and can note that at least one other person outside our team has seen on a different projects are:

1. Certain project config update workflows seem to add and remove the appended Field names in the project.yaml. So some updates flip flop between something like:

```
Sometimes:
4f410c45-a39d-48b6-96f1-9df22a0e44fb: 'Text ' # Text Field

Also sometimes:
4f410c45-a39d-48b6-96f1-9df22a0e44fb: 'Text '
```

I haven't noticed this one as recently so maybe a recent update improved it but it was happening for a while and the other person I spoke with also noted it happening to them.

2. The associative array data seems to flip flop between being stored as a numeric array and a non-numeric array. I've described this scenario in this [Stack Exchange post](https://craftcms.stackexchange.com/questions/39024/project-config-keeps-running-into-conflicts-due-to-associative-array-changing-be
).

One thought I had about this scenario was that it may be custom field plugins, like Vizy, implementing the pack/unpack associative array behavior on field save differently than say Craft behaves when we do something like hit the Rebuild button in the Project Config Utility in the CP. But I haven't had time to dig in properly.

I'll try to update this if I get a more specific step-by-step-to-recreate example, but wanted to at least get this out there in case it's a known issue and we just aren't doing something the right way or in case anybody else can add more info from their own experiences.

### Additional info

- Craft version: Craft 3.7.32
- PHP version: 7.4
- Database driver & version: MySQL 5.7
- Plugins & versions: Vizy 1.0.9 and several others but the problem seems to happen around Vizy fields sometimes, at least

**Comment by brandonkelly** [comment]
Possibly related: #10408

**Comment by BenParizek** [comment]
Thanks @brandonkelly.

I've spent a little time digging into the second item and have more info I can share. The problem that we are seeing this regularly with on our project seems to have to do with the custom Vizy field, but I'm not sure where in the workflow or code to fix the issue. Could potentially be a bug in how the custom field gets processed by the project config rebuild command? Or perhaps just a bug in how the custom field was implemented that I should be reporting over there?

## Scenario 1:

If I run `./craft/project-config/rebuild` from the command line or the CP, Craft rebuilds our Project Config and converts the settings in `config/project/fields/articleVizy--ABCD.yaml` from ordinal to non-ordinal. There are more changes than the screenshots below show, but these screenshots represent the types of changes we're seeing throughout the field settings yaml file.

<img width="652" alt="diff" src="https://user-images.githubusercontent.com/309735/153480522-669bb18d-edd5-40ca-b328-4839badbc739.png">

<img width="640" alt="diff" src="https://user-images.githubusercontent.com/309735/153481308-6276bb07-bafa-4967-a85c-a724aec9d982.png">

## Scenario 2:

If I resave the custom Vizy field from the Craft Fields Settings, Craft converts the settings in `config/project/fields/articleVizy--ABCD.yaml` from non-ordinal to ordinal.

<img width="651" alt="diff" src="https://user-images.githubusercontent.com/309735/153481036-1f360a37-b874-4889-b541-c4becb008c87.png">

<img width="641" alt="diff" src="https://user-images.githubusercontent.com/309735/153481177-0f1b0f2a-1ff9-4db1-b495-a46b9ed0ee56.png">

**Comment by brandonkelly** [comment]
Thanks! I had a hunch that the reason for the `-`/`#` swaps were because the arrays were not indexed consecutively all the way down, and it looks like that theory was correct:

![A cropped screenshot of Ben’s project config YAML changes, showing that an array jumps from index 3 to 5, skipping 4](https://user-images.githubusercontent.com/47792/153517517-ac3bcc1a-d9b6-4dfd-ba00-2a5c6b00600b.png).

Something in Vizy must be unsetting whatever was in position `4` there, but not reindexing the array in the process. The Symfony YAML package doesn’t know whether the omitted `4` key was important or not, so it errs on the safe side and outputs the ordinal keys. So that’s a Vizy bug.

**Comment by engram-design** [comment]
This might be a Craft issue still. Vizy's settings for the field look something like the below (cut-down version):

```
[
    'fieldData' => [
        0 => [
            'id' => 'group-wmj2PqnwZb'
            'name' => 'Content'
            'blockTypes' => [
                0 => [
                    'id' => 'type-h78sfEIGgq'
                    'name' => 'Content'
                    'handle' => 'content'
                    'icon' => [
                        'label' => 'Elementor'
                        'value' => 'elementor-brands'
                    ]
                    'template' => null
                    'enabled' => true
                    'layoutUid' => '1af7e1f8-9332-4df3-9b0e-32fdbceecc52'
                    'layoutConfig' => [
                         ...
                    ]
                    'fieldId' => null
                ]
            ]
        ]
    ]
]
```

Which gets converted to the associate array syntax stored in Yaml files:

```
[
    'fieldData' => [
        0 => [
            '__assoc__' => [
                0 => [
                    0 => 'id'
                    1 => 'group-wmj2PqnwZb'
                ]
                1 => [
                    0 => 'name'
                    1 => 'Content'
                ]
                2 => [
                    0 => 'blockTypes'
                    1 => [
                        0 => [
                            '__assoc__' => [
                                0 => [
                                    0 => 'id'
                                    1 => 'type-h78sfEIGgq'
                                ]
                                1 => [
                                    0 => 'name'
                                    1 => 'Content'
                                ]
                                2 => [
                                    0 => 'handle'
                                    1 => 'content'
                                ]
                                3 => [
                                    0 => 'icon'
                                    1 => [
                                        '__assoc__' => [...]
                                    ]
                                ]
                                4 => [
                                    0 => 'template'
                                    1 => null
                                ]
                                5 => [
                                    0 => 'enabled'
                                    1 => true
                                ]
                                6 => [
                                    0 => 'layoutUid'
                                    1 => '1af7e1f8-9332-4df3-9b0e-32fdbceecc52'
                                ]
                                7 => [
                                    0 => 'layoutConfig'
                                    1 => [
                                        '__assoc__' => [...]
                                    ]
                                ]
                                8 => [
                                    0 => 'fieldId'
                                    1 => null
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
    ]
]
```

Which is all fine. However, something in Craft is stripping out `template` and `fieldId` attributes from the associated array, and is failing to re-index it, resulting in what you're seeing with the skipped 4 and 8 index missing. This is part of Craft's `_cleanupConfigValue()` function. After this function fires the associative array is the following:

```
[
    0 => [
        '__assoc__' => [
            0 => [
                0 => 'id'
                1 => 'type-h78sfEIGgq'
            ]
            1 => [
                0 => 'name'
                1 => 'Content'
            ]
            2 => [
                0 => 'handle'
                1 => 'content'
            ]
            3 => [
                0 => 'icon'
                1 => [
                    '__assoc__' => [
                        0 => [
                            0 => 'label'
                            1 => 'Elementor'
                        ]
                        1 => [
                            0 => 'value'
                            1 => 'elementor-brands'
                        ]
                    ]
                ]
            ]
            5 => [
                0 => 'enabled'
                1 => true
            ]
            6 => [
                0 => 'layoutUid'
                1 => '1af7e1f8-9332-4df3-9b0e-32fdbceecc52'
            ]
            7 => [
                0 => 'layoutConfig'
                1 => [
                    '__assoc__' => [
                        0 => [
                            0 => 'tabs'
                            1 => [
                                0 => [
                                    '__assoc__' => [
                                        0 => [...]
                                        1 => [...]
                                        2 => [...]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
    ]
]
```

Indeed, those indexed are missing, because they are stripped out with a `isset()` check. That's all fine, but because this is done at the project config service level, after our field has prepped any settings, there's not much we can do about it from the plugin end.

If I modify the following:

https://github.com/craftcms/cms/blob/0c98687839cdef77bb81eb499580e1772aecee29/src/helpers/ProjectConfig.php#L231-L232

to:

```php
$cleanPackedArray = array_values($cleanPackedArray);
ksort($cleanPackedArray, SORT_NATURAL);
$value[ProjectConfigService::CONFIG_ASSOC_KEY] = $cleanPackedArray;
```

The indexes are correctly reset. `template` and `fieldId` values are missing (but that's fine, and correct - at least to your specifications with Yaml files), and no longer causes a diff.

You'd know this code better than me, but thoughts? I would think this to be a fair change, and good practice to ensure array keys are reset. Or maybe it needs some more smarts to it to prevent associative arrays from loosing their non-numeric keys. I don't _think_ this is a breaking issue because at this point the associative arrays have already been converted to your `__assoc__` syntax.

If you need to reproduce it, you can spin up a Vizy field, and toggle between saving the field through the control panel, and rebuilding the project config.

**Comment by andris-sevcenko** [comment]
Just pushed a fix for this for the next release! Thanks for all the observations and help!

**Comment by bleepsandblops** [comment]
This is still happening to me with Vizy 2.1.19 and Craft 4.9.7

**Comment by rmales** [comment]
This also still happens for me with Vizy 3.0.3 and Craft 5.3.6

**Comment by brandonkelly** [comment]
Just fixed the underlying bug @engram-design pointed out for the next Craft 4 and 5 releases.

**Comment by brandonkelly** [comment]
Craft 4.12.0 and 5.4.0 are out with that fix.
