### ISSUE TITLE
parseBooleanEnv immediately rejects integers

### ISSUE THREAD

**Issue by jaspertandy** [craftcms/cms#10524]
### Description

The app helper, [parseBooleanEnv](https://github.com/craftcms/cms/blob/develop/src/helpers/App.php#L133) incorrectly (in my opinion) rejects anything that isn't already a boolean or a string. That means that bool-y values like 1 and 0 get immediately returned as null, and consequently inferred as false. I've just had this problem when upgrading an install where mailer `useAuthentication` was set to 1 (not '1') and so was getting passed through to this method as an integer, but ending up as false and I really don't think this should be the case. These were project.yamls that were generated from the upgrade process so it's not like it's something I've manually edited. I guess in an ideal world, this value would get saved as '1' and '0' when upgrading, but I feel like this method parsing intval(1) and intval(0) as true and false, respectively, is the correct behaviour for this method.

### Steps to reproduce

1. in an SMTP project.yaml (where the SMTP server requires authentication), set email.transportSettings.useAuthentication to 1 (no quotes)
2. trace a mailer function through to [here](https://github.com/craftcms/cms/blob/develop/src/mail/transportadapters/Smtp.php#L144) and observe that the output of `App::parseBooleanEnv($this->useAuthentication)` is `NULL` when it should be `true`

### Additional info

- Craft version: 3.7.32
- PHP version: 7.4.27
- Database driver & version: mysql
- Plugins & versions:
```
  "require": {
    "craftcms/cms": "^3.7.27.2",
    "vlucas/phpdotenv": "^3.4.0",
    "nystudio107/craft-fastcgicachebust": "^1.0",
    "clubstudioltd/craft-asset-rev": "^6.0",
    "craftcms/contact-form": "^2.3",
    "hybridinteractive/craft-contact-form-extensions": "^1.2",
    "craftcms/redactor": "2.9.1",
    "topshelfcraft/wordsmith": "3.3.0.1",
    "ether/seo": "^3.7"
  },
```

**Comment by brandonkelly** [comment]
Yeah agree, `0` and `1` should be treated as bools. Just changed that for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.33 is out now with this change.
