### ISSUE TITLE
Plugin settings model errors and changed values are lost on 3.7.32

### ISSUE THREAD

**Issue by martinleveille** [craftcms/cms#10533]
With a plugin that has `hasCpSettings` enabled, when you save your settings and there are validation errors, you don't have access to the errors attached to the attributes (fields) of the model.

This issue was introduced by this commit: https://github.com/craftcms/cms/commit/ab8b67d07bbfbf3c16301846a0e4925ff2448066

### Additional info

- Craft version: Craft Pro 3.7.32
- PHP version: PHP 8.0.15
- Database driver & version: MySQL 8.0.23
- Plugins & versions: Sentry Logger 1.2.0

**Comment by brandonkelly** [comment]
Doh, didn’t think about that. Just reverted. Will see if I can come up with a more thorough solution for Craft 4.
