### ISSUE TITLE
Field Handles don't get removed when deleting a field

### ISSUE THREAD

**Issue by mijewe** [craftcms/cms#10538]
### Description

Video description:
https://www.loom.com/share/53e008ce5c514a3c997c8c5a13e5ef87

When deleting a field from Settings -> Fields, the Title column gets updated with the newly removed field having been removed, however the Handles column doesn't get updated, so the rows are out of sync.

### Steps to reproduce

1. Go to Settings -> Fields
2. Delete a field
3. Observer that the handle of the deleted field is still there

### Additional info

- Craft version: Craft CMS 3.7.32
- PHP version: 7.4.24
- Database driver & version: MySQL 5.5.5 (MariaDB)
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting! We’ve fixed this for the next release.
