### ISSUE TITLE
relatedTo returns already deleted relations when using broader query parameters

### ISSUE THREAD

**Issue by akselikap** [craftcms/cms#10557]
### Description

When using relatedTo we get linked content whose link was deleted depending on the specificity of a query. In our case we have entry types location and person. Locations have a field called 'personnel' which is an Entries-field that is allowed to only contain links to Person entries. We are querying for all locations a person is linked to like this:

`craft.entries().section('correctSection').type('location').relatedTo({
		targetElement: entry,
		field: 'personnel',
	}).with(['personnel']).all()`

where entry is the entry of the person in question. We have noticed that in some cases this will return locations which don't contain a link to the person anymore because it was deleted at some point. To further troubleshoot this I checked the query results using pre-tag and dump and noticed that the personnel field of a location contained more personnel than was shown on admin panel (expected 7, got 8). So I tried to get just the location in question and check what I get when doing that. I used this query for that:
`craft.entries().section('correctSection').type('location').slug('correctSlug').with(['personnel']).all()`
And as a result I got 7 personnel instead of the 8 I got with the previous query. So I added the relatedTo to this query as well like this:

`craft.entries().section('correctSection').type('location').slug('correctSlug').relatedTo({
		targetElement: entry,
		field: 'personnel',
	}).with(['personnel']).all()`

and I still got only 7 personnel as a result. If the slug part is dropped then I get 8 personnel in the result and one of those seems to come from a deleted link.

### Steps to reproduce

1. Create entry types described in the description
2. Create multiple person entries
3. Create location entry and link multiple persons to it and save the entry
4. Delete one person from the location entry and save.
5. Use the queries provided in the description and verify that a broader query with relatedTo returns the person whose link was deleted.

EDIT: I'm not sure if this always happens so the reproduction might be tricky.
EDIT2: I'm unable to reproduce this for arbitrary entries.

### Additional info

- Craft version: Craft Pro 3.7.8
- PHP version: 7.4.27
- Database driver & version: MySQL 5.7.30
- Plugins & versions: Not sure if any plugin is related to this

**Comment by brandonkelly** [comment]
Given you’re having trouble reproducing separately, can you please send a database backup and your Composer files over to support@craftcms.com? That way we can look into it right from your install.

**Comment by akselikap** [comment]
Sending over a database backup could be problematic from a privacy perspective. If you don't have any general pointers about what could be causing this, we'll have to think if we are able to send a copy from which all personal data has been removed. Anyway, thanks for the quick reply!

**Comment by akselikap** [comment]
Well, we opted to manually check in twig code if the person actually is linked to the location. This causes 1 or 2 extra database requests per page load as we usually have only 1 or 2 locations per person but it's a very cheap workaround we can live with.

**Comment by brandonkelly** [comment]
I’m a bit stumped unfortunately. If it’s not happening for other entries, that suggests some sort of data corruption issue, though.

**Comment by akselikap** [comment]
Well I think I solved this now. Apparently the relatedTo -query gets its results from other localized versions as well. I didn't mention that the link-field was localized (honestly, I didn't know/notice that). Is this intended behavior? At least I'm very confused :smile:

**Comment by brandonkelly** [comment]
@akselikap Yeah that sounds like it’s working as expected. Sorry I didn’t think to ask about multi-site earlier, but glad you got it sorted!
