### ISSUE TITLE
Can't open actions menu of matrix nested in a neo

### ISSUE THREAD

**Issue by elodiegrondin** [craftcms/cms#10566]
### Description

Hello, I am unable to open the actions menu (to deactivate/delete/copy/… blocks) of a native craft matrix nested in a neo field.
The webpage jumps up to the beginning of neo block and the action menu opens to an absolute position outside the viewport...
I get the following error displayed in the console when the bug happens: Uncaught Can’t remove the base layer. ([removeLayer@UiLayerManager.js](mailto:removeLayer@UiLayerManager.js):60)
[I thought it was a craft-neo issue](https://github.com/spicywebau/craft-neo/issues/541) but it seems that it's a craft bug...
I could downgrade my craft version, because it seems that the issue starts with craft 3.7.31 but I wanted to see if anyone knows how to fix this ? Thanks !

### Steps to reproduce

1. Build a Neo block that contain a matrix field
2. Create some matrix block inside
3. Try to open the actions menu.

### Additional info

- Craft version: 3.7.32
- PHP version: 7.4.21
- Database driver & version: MySQL 5.7.34
- Plugins & versions: Neo version: 2.12.4

**Comment by brandonkelly** [comment]
This is in fact a Neo bug; just submitted a PR to fix (spicywebau/craft-neo#542).
