### ISSUE TITLE
Propagating a Single to a new site populates it with content not from the Primary Site

### ISSUE THREAD

**Issue by thisisjamessmith** [craftcms/cms#10561]
### Description

When propagating a Single section to a newly created site, it appears to prepopulate the fields of that Single entry with content from a site that is not the Primary Site.

### Steps to reproduce

1. Set a particular site as the Primary Site in an existing multisite install (perhaps not the site that was originally set to be the Primary site?)
2. Have a Single section and add some translatable fields to it
3. Populate the Single with unique content per site
2. Create a new site
3. Make your Single section available to the new site
4. See that it gets populated with content from the site that is not the Primary Site

### Additional info

- Craft version: 3.7.32

**Comment by brandonkelly** [comment]
Thanks for reporting that. It was just using whatever the current site was. If the queue was being run from the control panel that should always be the primary site, however that wasn’t a given if the queue was being run from a separate runner.

Just updated the job to be explicit about preferring to pull entries from the primary site, if they exist there.

**Comment by thisisjamessmith** [comment]
I see, thanks for looking into it Brandon. To workaround this I tried accessing the section editing page using the target site's URL (which is a language-specific subdirectory of the main site at example.com/fr), but the problem still persisted after saving.
