### ISSUE TITLE
Trouble populating Plugin Field (Neo) while running through Codeception

### ISSUE THREAD

**Issue by khamer** [craftcms/cms#10574]
### Description

I'm running into an issue where neo fields don't seem to populate while trying to run through Codeception. I've dug into this but haven't nailed down the exact issue; any ideas or help would be most appreciated.

### Steps to reproduce

There's an example repo you should be able to use to replicate the issue here: https://github.com/khamer/craftdemo-custom-fields-with-codeception

You should be able to configure that to run locally based on your development environments. If all is well, you should be able to run the codeception functional test ExampleCest and see "Test redactor in matrix" work but "Test redactor in neo" fail.

Having dug into this for a while, I believe the value isn't even being populated into the Entry even before it's saved. I think that's happening because it looks like for that to work, the generated tests/craft/storage/runtime/compiled_classes/CustomFieldBehavior***********.php file would need to have a reference to the relevant neo field - in this case, neoContent - but I only see bodyContent in the generated file. I think at the time of generating this file, for whatever reason the neo fields aren't within the fields table yet; and that's as far I've gotten.

It doesn't seem to be an issue for Matrix fields or the craftcms/redactor plugin's fields. I'll ask the spicyweb guys too, but I'd love to get this solved because this blocks us being able to do automated testing on sites using Neo, and I'm not sure if they're using Neo with codeception anywhere yet.

### Additional info

- Craft version: 3.7.30.1
- PHP version: 8.0
- Database driver & version: mariadb 15.1
- Neo plugin version: 2.12.4

### Update
Spicy Web thinks this is a Craft issue. Just adding more things I've seen that aren't within the repo used to replicate the issue.

I do think this is a timing thing to do with the test being run before the custom fields are entirely set up from projectConfig. I'm not sure how that's possible, but I can see in the logs on another project that the INSERT statements into `fields` are happening after the `SELECT` query within Craft.php that's used to generate the CustomFieldBehavior class. I don't know whether I'm pulling on the right thread or not, and would appreciate any guidance you can offer.

On the original project I was working on, I was only able to replicate the issue with `dbSetup: { clean: true, setupCraft: true }` - if I changed that to `dbSetup: { clean: false, setupCraft: false }` and nothing else, the test would complete. Here, the test fails either way which seemed more useful for troubleshooting, but I figured I'd mention this in case it suggests a cause to you.

I accidentally opened this issue against the wrong project initially ([over here](https://github.com/craftcms/craft/issues/76)) so I'm moving it over here.

**Comment by ttempleton** [comment]
Related Neo issue: https://github.com/spicywebau/craft-neo/issues/538

At this stage I don't know if this is Craft's or Neo's doing. What I found in https://github.com/spicywebau/craft-neo/issues/538#issuecomment-1034718432 looked like a potential Craft issue to me, but then what I found in https://github.com/spicywebau/craft-neo/issues/538#issuecomment-1036173042 made it look like there could be something Neo's doing to cause it. I haven't yet found anything that Neo's doing wrong to cause it, though.

**Comment by angrybrad** [comment]
@khamer this is still on my list, but with the Craft 4 beta launch coming up, we've been slammed. Will carve out some time for it once that settles.

**Comment by khamer** [comment]
Hey @angrybrad - while I'm sure you're still plenty busy, just figured I'd check with Craft 4 released. We're hoping to start using more automated testing but the combination of this bug and Neo not working right in Craft 4 yet really limits what we can do. I might move towards some kind of test setup that just works off of a SQL dump instead of using the craft codeception things.

**Comment by ttempleton** [comment]
> Neo not working right in Craft 4 yet

@khamer, if you're having issues with Neo on Craft 4, please [report them](https://github.com/spicywebau/craft-neo/issues/new).

**Comment by khamer** [comment]
@ttempleton I will, sorry - I don't any issue to report right now but haven't got much runtime on Craft 4 yet. Didn't mean to disparage Neo.

**Comment by ttempleton** [comment]
I've been able to dig into it far enough and have determined that this was a Neo bug. I'm going to keep the related Neo issue open for now, until the next Neo 2 release, but from a Craft issue perspective this can be closed now.
