### ISSUE TITLE
Update enshrined/svg-sanitize to version > 0.15.0

### ISSUE THREAD

**Issue by sfsmfc** [craftcms/cms#10570]
### Description
Due to a security issue in enshrined/svg-sanitize in version  < 0.15, we should update the dependency to allow a version greater than ~0.14.

### Steps to reproduce

1. Update dependency for enshrined/svg-sanitize in order to allow also version 0.15.x.

### Additional info

- Craft version: 3.7.x

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/cms/pull/10563/files
