### ISSUE TITLE
Unexpected data loss in Matrix field

### ISSUE THREAD

**Issue by benjamin-smith** [craftcms/cms#10571]
### Description

Our client reported an entry (single) that had all matrix rows removed, but it wasn't clear what user action might have caused this. This was a large "modules" field, effectively wiping out all content on the page. There were about a dozen or so rows, each with a number of fields; these pages are very data heavy.

When attempting to restore the entry from a previous draft or version, we are able to do so, but it appears all asset fields lose their values. The assets are still present in the Assets section, they are just no longer associated with the fields in this particular entry. 

Note that there is no "recent" version that represents a change when the data was lost. I.e. we can't go back to the version immediately proceeding the current version and recover all data; there were more changes in Current that are not represented in version history, leading me to believe the data loss was not the result of a save/publish operation.

We had `autosaveDrafts` turned on when this occurred (have since turned it off).

The site is a multi-site, with about 25 or so active sites. The page with data loss had a version in each of these sites, all of them had their matrix rows wiped out. This matrix field is used in other sections as well, but there was no data loss on any other entries.

### Steps to reproduce

Unable to say.

### Additional info

- Craft version: 3.7.27.1
- PHP version: 7.4.27
- Database driver & version: mysqlnd 7.4.27 / Azure Database for MySQL flexible server 5.7
- Plugins & versions:

**Comment by hatzipanis** [comment]
We are also a facing an issue where the site is taking a long time to save and then timing out. We disabled `autosaveDrafts` based on advice in other discussions and we have reduced `maxRevisions` to `5` but that hasn't improved anything. We have 37 sites in this one installation 😩.

**Comment by brandonkelly** [comment]
@hatzipanis See my previous comment w/r/t revisions being a likely culprit. Also worth checking out #9802 + #10577.

**Comment by benjamin-smith** [comment]
Certainly makes sense that timeouts would cause unexpected behavior. I'll test with versions disabled and see if there are gains.

**Comment by hatzipanis** [comment]
Thanks @brandonkelly, disabling revisions has dramatically improved saving times so that's a great first step. Will this be resolved in Craft 3? Our clients need revisions.

**Comment by brandonkelly** [comment]
@hatzipanis It will be faster in Craft 4: #10589

**Comment by benjamin-smith** [comment]
Thanks for all the quick feedback on this.
