### ISSUE TITLE
Entry and category editor modals should link to their full edit pages

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1057]
> Created by: Brandon Kelly (brandon@pixelandtonic.com) on 2015/03/06 03:54:45 +0000
> Votes at time of UserVoice import: 4

-----------------------------------

It would be nice if entry/category edit modals (such as the ones that appear when double-clicking on the elements in Entries and Categories fields) would show links to the entry/category's full edit page in the CP.

**Comment by ryanpcmcquen** [comment]
@brandonkelly, any movement here?

**Comment by brandonkelly** [comment]
Closing this in favor of #3448.
