### ISSUE TITLE
Getting PHP Notice error

### ISSUE THREAD

**Issue by Eddie-Silva** [craftcms/cms#10572]
### Description

Getting PHP Notice – [yii\base\ErrorException](http://www.yiiframework.com/doc-2.0/yii-base-errorexception.html)
I have not made any updates to the site -- this error just came out of no where. It's causing my app not to load.

Any ideas how I can fix the issue?

### Additional info

- Craft version:3.2.8
- PHP version:PHP 7.3.7
- Database driver & version: xampp/mysql/Apache 2.4.39 (Win64) 

### Stack trace

```
yii\base\ErrorException: unserialize(): Error at offset 0 of 42 bytes in C:\xampp\htdocs\craft\vendor\yiisoft\yii2\caching\Cache.php:138
Stack trace:
#0 C:\xampp\htdocs\craft\vendor\craftcms\cms\src\web\ErrorHandler.php(81): yii\base\ErrorHandler->handleError(8, 'unserialize(): ...', 'C:\\xampp\\htdocs...', 138)
#1 [internal function]: craft\web\ErrorHandler->handleError(8, 'unserialize(): ...', 'C:\\xampp\\htdocs...', 138, Array)
#2 C:\xampp\htdocs\craft\vendor\yiisoft\yii2\caching\Cache.php(138): unserialize('kh\xB4k[8\xD4,Z\x9A\x9Aa\xB5\xDA\x1C...')
#3 C:\xampp\htdocs\craft\vendor\craftcms\cms\src\services\ProjectConfig.php(1238): yii\caching\Cache->get('9813d5c7ffecbfb...')
#4 C:\xampp\htdocs\craft\vendor\craftcms\cms\src\services\ProjectConfig.php(493): craft\services\ProjectConfig->_areConfigFilesModified()
#5 C:\xampp\htdocs\craft\vendor\craftcms\cms\src\web\Application.php(224): craft\services\ProjectConfig->areChangesPending()
#6 C:\xampp\htdocs\craft\vendor\yiisoft\yii2\base\Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#7 C:\xampp\htdocs\craft\web\index.php(21): yii\base\Application->run()
#8 {main} 
```

**Comment by angrybrad** [comment]
Try clearing out your Craft `storage/runtime/cache` folder.

**Comment by Eddie-Silva** [comment]
@angrybrad Thanks! This fixed my issues. 

Why can cached files cause issues?

**Comment by angrybrad** [comment]
@Eddie-Silva have seen it happen a handful of times, but not sure of the root cause. A cache file gets corrupted somehow. I probably should have had you grab the contents of that folder and it over to support@craftcms.com before you nuked it. If it happens again, please do that and we'll see what we can find!
