### ISSUE TITLE
4.0 Field Layout editor slideouts don’t dismiss on subsequent outside clicks

### ISSUE THREAD

**Issue by mattstein** [craftcms/cms#10586]
### Description

Field layout editor slideouts close/dismiss if you click anywhere outside the slideout—but only the first time. If you re-open the slideout and click outside it again, expecting it to close, it does not. (You have to press <kbd>esc</kbd> or **Apply** instead.)

https://user-images.githubusercontent.com/2488775/154340088-42a3cb2e-961f-4ee3-9136-18b98c5ce4c0.mp4

The problem may be limited to the field layout editor specifically; slideouts opened from entry listing views do _not_ exhibit the issue and work as expected.

### Steps to reproduce

1. Pick an entry type to edit. (**Settings** → **Sections** → [any **Edit entry type**].)
2. Click the gear icon next to any field in the **Field Layout** editor.
3. Once the slideout is open, click anywhere outside it and watch it close / slide away.
4. Click the same gear icon again from step 2.
5. Attempt to repeat step 3 and click outside the slideout. Observe that it does not go away.
6. Press <kbd>esc</kbd> or **Apply** to dismiss the slideout.

You can follow those steps with any field, and/or refresh the page to have a fresh go at it.

### Additional info

- Craft version: 4.0.x-dev (decee1422ca2b93efc3d0ebec93c4eff04523111)
- PHP version: 8.0.11
- Database driver & version: MySQL 8.0.26
- Plugins & versions: Redactor 3.0.x-dev
- Browsers: Safari 15.2 (17612.3.6.1.6), Edge 98.0.1108.55, Firefox 97.0

**Comment by brandonkelly** [comment]
This is a slideout bug that also affects Craft 3, so fixed for the next 3 + 4 releases!

**Comment by brandonkelly** [comment]
Craft 3.7.38 and 4.0.0-beta.4 are out with the fix for this.
