### ISSUE TITLE
GraphQL API broken because of string cast

### ISSUE THREAD

**Issue by boudewijn-zicht** [craftcms/cms#10580]
### Description

The commit below, introduced in version 3.7.32, casts `$contentField` into a string.  This causes the test `!method_exists($elementQuery, $contentField)` to check on the _label_ instead of the _handle_ of `$contentField`.

This label is influenced by the translations in `translation/<LANG>/site.php`.  We happen to have one of the fields translate into 'Status', and that causes this field to be removed from the Graphql API arguments.

Bug introduced in: https://github.com/craftcms/cms/commit/cb59bde049e82c6d5a029f60dd4dc396ec2a9a3b

### Steps to reproduce

1. Translate a field handle into 'Status'
2. Try to access it as an argument though the GraphQL api, i.e. `entries (section: "foo", fieldHandle: "foo")` where `fieldHandle` corresponds with the field that is translated into `Status` in the CMS.

### Additional info

- Craft version: 3.7.32
- PHP version: 7.4

**Comment by brandonkelly** [comment]
Craft 3.7.34 is out with the fix for this. Thanks again for reporting1

**Comment by boudewijn-zicht** [comment]
And thanks for fixing :+1:
