### ISSUE TITLE
mysqldump fails on external db and mysql not locally installed

### ISSUE THREAD

**Issue by espensgr** [craftcms/cms#10596]
### Description
We have a server with only PHP and Nginx, and a separate server with mysql (Digital Ocean Databases).
When we run composer install on live the `backupOnUpdate` is default to `true` so i guess Craft should check if mysqldump is installed before trying to run a dump that forces the install to fail.

### Steps to reproduce

1.Run composer install with a separate db and mysql not installed on server

### Additional info

- Craft version: 3.7.33
- PHP version: 8.0.15
- Database driver & version: Mysql 8
- Plugins & versions:

**Comment by brandonkelly** [comment]
Craft calls the configured [backupCommand](https://craftcms.com/docs/3.x/config/config-settings.html#backupcommand) when creating a DB backup. You can override that and set it to whatever you want from `config/general.php`.

**Comment by espensgr** [comment]
Yeah i know about the config for that, but shouldn't Craft check if it is installed and do a graceful skip of the dump instead of get an error and cancel the install?
This is more a suggestion than a bug i guess 🤷‍♂️

**Comment by espensgr** [comment]
That make sense, didn't think of it with the `backupCommand` and the possible problems with that.
Thanks for clarifying .
