### ISSUE TITLE
Thumbnails of images in overview list and entry detail where bigger (adjustable in size)

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1059]
> Created by: Tim Bertens (tim@bene.be) on 2015/09/10 09:31:18 +0000
> Votes at time of UserVoice import: 4

-----------------------------------

Make the thumbnails of images appear much larger (or adjustable in size) in the control panel entries (both in the detail of the entry and in the overview list using the new customisable columns in 2.5). 

The standard preview of the images is so small it hardly is visible to control panel users.

**Comment by theskyfloor** [comment]
A slider like macOS would be awesome!

<img width="140" alt="screen shot 2017-01-31 at 2 15 35 pm" src="https://cloud.githubusercontent.com/assets/8887839/22482727/e26c50d0-e7bf-11e6-90da-381764be4dd6.png">
