### ISSUE TITLE
Craft Date field isn't respecting region format

### ISSUE THREAD

**Issue by jamiematrix** [craftcms/cms#10602]
Running  3.7.30.1 I noticed when setting a date in a standard date field the format is being set to the m/d/yy format. The timezone for the site is set to GMT.
Outputting the field in a template shows the date correctly, but it's odd that it's shown different with /admin.

I had a quick look through the changelog and can't see a fix that's been applied to this fix (there are 3 Craft updates available - and they're all in the m/d/y format too)

**Comment by brandonkelly** [comment]
Dates are formatted in the control panel per the user’s Formatting Locale user preference. Go to `/myaccount` and check what that’s set to.

**Comment by jamiematrix** [comment]
That did it! Thanks. Didn't think to look there - makes sense that it's a 'personal' setting.
