### ISSUE TITLE
Matrix action menus get cut off in preview

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#10601]
### Description

Since Craft 3.7.31, Matrix action menus are horizontally cut off in preview (possibly introduced by #10480?).

![CleanShot 2022-02-17 at 15 09 47@2x](https://user-images.githubusercontent.com/298510/154498744-2e05359f-8f75-4ecd-9c2e-49c8417eb8ad.png)

### Steps to reproduce

1. Add a Matrix field to a section
2. Open an entry in preview
3. Add a block and click the cogwheel button to open the action menu

Issue is reproducible across different sites on Craft 3.7.31, 3.7.32 and 3.7.33, using the latest MS Edge (98.0.1108.55) on macOS 12.2. Issue does not occur on Craft 3.7.30.1.

### Additional info

- Craft version: 3.7.31+
- PHP version: 7.4
- Database driver & version: MySQL 5.7
- Plugins & versions: None

**Comment by brandonkelly** [comment]
Craft 3.7.34 is out now with the fix for this.
