### ISSUE TITLE
CpScreenResponseFormatter trying to convert closure to string

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#10607]
### Description
XHR Requests to `admin/actions/edit` fail, as it is trying to convert `$behavior->content`, which can be a closure, to a string; https://github.com/craftcms/cms/blob/4.0/src/web/CpScreenResponseFormatter.php#L70-L80

### Steps to reproduce

1. Add a new filesystem from the dropdown when creating a volume
<img width="532" alt="CleanShot 2022-02-17 at 16 01 46@2x" src="https://user-images.githubusercontent.com/18329/154570228-21802390-7279-4210-a9ce-ec739e16928b.png">

### Additional info

- Craft version: `4.0` branch

**Comment by brandonkelly** [comment]
Fixed
