### ISSUE TITLE
Assets: missing arrow if folder is focuesd (or clicked)

### ISSUE THREAD

**Issue by ammannbe** [craftcms/cms#10617]
### Description

If a folder in the assets view is focused, the arrow on the left side disappears.
The folder gets automatically focused, if I click on it.

This is misleading for a lot of people, because a lot of people first click on the folder, and then look if there is a subfolder.

| ![Subfolder without focus](https://user-images.githubusercontent.com/26964239/154941348-429221ca-698c-4f93-af91-841de92419d2.png) | ![subfolder focused](https://user-images.githubusercontent.com/26964239/154941351-71934482-d8c8-428e-ab59-75294ff78353.png) |
|---|---|

### Steps to reproduce

1. Create a new assets volume
2. Create a subfolder in this volume
3. Select the created folder

### Additional info

- Craft version: 3.7.32
- PHP version: 7.4.27
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

|  |  |
|---|---|
| Colour Swatches | 1.5.0.4 |
| Control Panel CSS | 2.4.0 |
| Field Manager | 2.2.4 |
| HOMM Icons | 0.0.2 |
| HOMM XML Sitemap | 0.0.5 |
| Logs | 3.0.5 |
| Minify | 1.2.10 |
| Navigation | 1.4.24 |
| Postmark | 2.1.0 |
| Redactor | 2.10.0 |
| Redactor nofollow link plugin | 1.0.1 |
| Redirects | 3.0.9.1 |
| Super Table | 2.7.1 |
| Typed link field | 1.0.25 |

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just released Craft 3.7.34 with a fix.
