### ISSUE TITLE
Querying entries of deactivated sites in GraphQL

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/cms#10610]
### Discussed in https://github.com/craftcms/cms/discussions/10609

<div type='discussions-op-text'>

<sup>Originally posted by **mihob** February 18, 2022</sup>
It looks like you can query entries of a sites even though the site itself is disabled.

For example:

```
query {
  entries(id:1,siteId:2) {
    id
  }
}
```

This query would still return a result even though the site with ID 2 would be disabled. Is this working as intended? 
I would expect that entries belonging to disabled sites would not be available to the public.
</div>

**Comment by andris-sevcenko** [comment]
cc @mihob

**Comment by brandonkelly** [comment]
Craft 4.0.0-beta.4 is out now with that change.
