### ISSUE TITLE
UX: Escape key closes multiple states at once

### ISSUE THREAD

**Issue by domstubbs** [craftcms/cms#10623]
### Description

The escape key exits both preview mode and the asset selection modal in one key press.

### Steps to reproduce

1. Open an entry in live preview mode
2. Open a file selection modal for any assets field
3. Hit the escape key

The same behaviour occurs with entry selection modals.

### Expected behaviour

Pressing escape should only close the most recently triggered state, i.e. press once to close the asset selector and a second time to close the live preview.

### Additional info

- Craft version: 3.7.33
- PHP version: 7.4
- Database driver & version: N/A
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just released Craft 3.7.34 with a fix.
