### ISSUE TITLE
Impossible to translate setPasswordPath when headless mode is on

### ISSUE THREAD

**Issue by jornwildenbeest** [craftcms/cms#10631]
### Description

I am runnig Craft 3.6.15 with headless mode on.
It's a multisite with a different URL's for each language.

With headless mode on, Craft only accepts absolute URL's for the setPasswordPath.

Right now i've set the setPasswordPath to an absolute URL like this:
```
        'setPasswordPath' => 'https://example-url.nl/aanmelden/wachtwoord-resetten',
```
This is working fine except i would like to have a different setPasswordPath per site based on the users language.

Is this possible?

### Additional info

- Craft version: 3.6.15
- PHP version: 7.4

**Comment by brandonkelly** [comment]
`setPasswordPath` can be set to an associative array that defines a separate value for each site:

```php
'setPasswordPath' => [
    'siteHandleA' => 'https://example-url.nl/aanmelden/wachtwoord-resetten',
    'siteHandleB' => '...',
],
```

Or if you need even more flexibility, you can set it to an anonymous function:

```php
'setPasswordPath' => function(string $siteHandle) {
    // ...
    return 'https://example-url.nl/aanmelden/wachtwoord-resetten';
},
```

**Comment by jornwildenbeest** [comment]
Thanks @brandonkelly,

Not sure if this is a bug in Craft or in the authentication plugin i'm using (https://github.com/jamesedmonston/graphql-authentication).

But I can't get this to work.. It always returns the default sitehandle url.

in the sendPasswordResetEmail() method https://github.com/craftcms/cms/blob/f5f440942e54093500ffb418bd0557ae3c704d78/src/services/Users.php#L389 it's not possible to give an siteHandle as param. 

So in the user service, the getSetPasswordPath can never know which site to use right?

In the user service https://github.com/craftcms/cms/blob/f5f440942e54093500ffb418bd0557ae3c704d78/src/services/Users.php#L435

It calls the function getSetPasswordPath(), but without an siteHandle so the siteHandle param is always null, so it always returns the default.

**Comment by brandonkelly** [comment]
It should depend on which site you are sending the GraphQL API request to.

**Comment by jornwildenbeest** [comment]
It's 1 Craft site with multiple headless frontend websites..

So the requests always go to the same Craft installation

**Comment by brandonkelly** [comment]
You began by stating,

>  It's a multisite with a different URL's for each language.

By “multisite” I assumed you meant you have created multiple sites in **Settings** → **Sites**. Is that not the case?

**Comment by jornwildenbeest** [comment]
Ah yes sorry, let me explain. 

We have 1 Craft installation running with headless mode = true.

We did created multiple sites in **Settings -> Sites**.

These sites all have different urls, and are build with Nuxt.

So all the Nuxt sites communicate with the Craft installation and query data through graphql depending on the siteID.

People can login and register on the Nuxt sites through JWT tokens using the https://github.com/jamesedmonston/graphql-authentication plugin.

But for some reason with this setup, when trying to send a "reset password mail", the primary site is always selected and it is not possible to get the "setPasswordPath" for the other sites.

And maybe it's because there is no option to set the siteID in the "sendPasswordResetEmail" function.. 
But i'm not sure if that is the case or there is another reason it's not working.

**Comment by brandonkelly** [comment]
Yeah OK, just wanted to make sure I had originally understood you correctly.

You can configure Craft to be set to a specific site by passing a `site` query param set to the site handle. Then from your `web/index.php` file, you can check if a `site` param was sent, and if so, use it to define a `CRAFT_SITE` PHP constant:

```php
// ...

if (isset($_GET['site'])) {
    define('CRAFT_SITE', $_GET['site']);
}

// Load and run Craft
// ...
```

If you do that, you can optionally stop including the `siteId` params in your GraphQL queries, as element queries will always default to returning content for the current site.

**Comment by jornwildenbeest** [comment]
This would require to change the web/index.php right? Don't think I like that option since we are using CI/CD to deploy the Craft website.

**Comment by jornwildenbeest** [comment]
Could not get this to work in a proper way, so for now i made an if statement in de email template.

So it works for now

**Comment by brandonkelly** [comment]
Correct it would have been a change to `web/index.php`, which is part of your project, not Craft, so not sure what you mean about CI/CD. Glad you found a workaround though.

**Comment by jornwildenbeest** [comment]
Ah yes sorry, you are right about the web/index.php.

But the workaround will do fine for now, thanks for the help!
