### ISSUE TITLE
Error showing user dropdown - not able to logout.

### ISSUE THREAD

**Issue by zzseba78** [craftcms/cms#10639]
### Description
Error showing user dropdown, it show only user and logout button it´s down, you have to scroll the dropdown.

### Steps to reproduce

Click on user thumbnail on the top right, this happens on latest update.
** Confirmed in Firefox, Chrome and Safari ( all latest ) ** 

### Additional info

- Craft version: Craft CMS 3.7.34

### Screeshot

<img width="335" alt="Captura de Pantalla 2022-02-23 a la(s) 22 21 43" src="https://user-images.githubusercontent.com/5558563/155439250-c9167dcb-af6f-41b3-b68f-d094a7d0277b.png">

Sometimes it shows nothing

<img width="294" alt="Captura de Pantalla 2022-02-23 a la(s) 22 24 56" src="https://user-images.githubusercontent.com/5558563/155439374-92e032fd-bfa4-49fc-b8f6-220ee924eca4.png">

**Comment by bencresty** [comment]
Confirmed here. Not only the layout is disturbed, AFAIK there's no way to log out the user anymore now as there is no log out button in the dropdown (checked with dev tools; no log out element found). 

Seen on Ms Edge (Chromium):

![issue-user-menu](https://user-images.githubusercontent.com/69322733/155546319-90e3598b-9608-44b5-ae21-887706bd33ec.jpg)

**Comment by brettburwell** [comment]
Just updated to `3.7.34` and seeing the same issue that @bencresty reported.

In case it's helpful, when peeking at dev tools, it looks like the `#account-menu` has `max-height: 61px` set on it. Increasing that reveals the missing menu options for me.

**Comment by bencresty** [comment]
> Increasing that reveals the missing menu options for me.

You're right. It does here too. I thought the log in button was also missing, but I made a mistake; overlooked it in dev tools. It's here too.

**Comment by wsydney76** [comment]
Can confirm this behavior for latest Chrome on Windows.

The sign out button is reachable by pressing the arrow down or arrow right key though (while waiting for a fix).

Seems to work correctly when no user photo is assigned.

Btw. you can also logout via <yourdomain>/logout

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Are you getting any JS errors? Any plugins that could be messing with the CSS?

**Comment by bencresty** [comment]
> I’m not able to reproduce this. Are you getting any JS errors? Any plugins that could be messing with the CSS?

That's weird. I see it happening in two different projects on both localhost as well as on different hosting server in both chrome based as well as firefox browsers. 

There are no issues in the console.log.

**Comment by thupsi** [comment]
I can confirm this bug too, in Windows Chrome

**Comment by zzseba78** [comment]
@brandonkelly Hi! It´s an inline style that set max-height to 61 pixels.

<img width="858" alt="Captura de Pantalla 2022-02-25 a la(s) 11 03 18" src="https://user-images.githubusercontent.com/5558563/155728430-c600f5af-4368-4936-9cc0-a9f1be688cd0.png">

If this is removed it work as it should:

<img width="895" alt="Captura de Pantalla 2022-02-25 a la(s) 11 04 37" src="https://user-images.githubusercontent.com/5558563/155728549-33c2e61c-557e-411a-8f37-d397296e3615.png">

On this case i´m using some plugins that i don´t use frequently, but i try updating other site with some updates ahead and same plugins that i always use same problem happen: 

#### Before

<img width="429" alt="Captura de Pantalla 2022-02-25 a la(s) 11 06 27" src="https://user-images.githubusercontent.com/5558563/155729084-4351ae39-fa40-4523-bac5-ef6893b52b42.png">

#### After

<img width="344" alt="Captura de Pantalla 2022-02-25 a la(s) 11 07 20" src="https://user-images.githubusercontent.com/5558563/155729218-8c63a56d-dc43-4172-adcd-bed6ea6da431.png">

**Comment by brettburwell** [comment]
I just disabled every plugin and am still seeing the same thing (but am not seeing any js errors reported). The menu visibility also appears to change over a series of clicks—which is odd. 

@brandonkelly Here's a video so you can see exactly what's happening. If I can pass along any other info that'd be helpful just shout. 

https://user-images.githubusercontent.com/1228671/155734363-d3b85ae1-4c63-4d15-8f89-e84abbbaba6f.mp4

**Comment by bencresty** [comment]
> @brandonkelly Hi! It´s an inline style that set max-height to 61 pixels.

Here it's not set to 61, but 49 pixels. Most probably because I'm using the 'Environment Label' plugin that only shows a message in which environment we're in on top of the 'content panel'.

This means that the 61px is not set hardcoded, but dynamic with javascript.

**Comment by gcamacho079** [comment]
Working to reproduce this as well. Is this happening on any screens in particular or throughout the entire control panel?

**Comment by brettburwell** [comment]
@gcamacho079 I'm seeing it consistently throughout the CP.

**Comment by brandonkelly** [comment]
We got this fixed for the next release!

**Comment by brettburwell** [comment]
Bravo. Thanks, y'all!

**Comment by bencresty** [comment]
@brandonkelly  I see you guys fixed this. Nice. Just in case (was I can't see the update yet); I just found out during the starting of a new project the issue started happening from when the user got a profile picture uploaded.
