### ISSUE TITLE
draft and entry not propagated correctly in certain conditions

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#10634]
yesterday some issues mentioned on discord.
there are some paths to reproduce those:

**Entry not found error**
1. create a section with propagate to all sites method for site 1
2. click +new entry, add title, leave editing entry or even click save draft 
3. add another enabled site -site2- for that section
4. click to edit that entry and go to site 2. 
it throws entry not found error

**entry -current state- not propagated**
1. create a section with propagate to all sites method for site 1
2. click +new entry, add title, create entry
3. edit that entry, change the title, then leave the entry
4. add another enabled site -site2- for that section
5. click to edit that entry for site1, you can't see enabled status for site2 on site status on right side
6. click to edit that entry for site2, you can see enabled status for both site

**only draft for an entry not propagated**
1. create a section with propagate to all sites method for site 1
2. click +new entry, add title, create entry
3. edit that entry, change the title, click create draft
4. add another enabled site -site2- for that section
5. you can see current status is propagated correctly
6. you can see that draft is not propagated for site2

also with changing path to create entry (applying draft/creating draft/leaving without saving and ...), we can see similar behaviors for drafts, revisions and ...

**Additional info**

- Craft version: 3.7.33

**Comment by timkelty** [comment]
@vnali Thanks for reporting!
Fixed for the next release: https://github.com/craftcms/cms/commit/681b3425c111ac3e04198dc1e9139bb2f47f7cea

**Comment by vnali** [comment]
@timkelty thanks. i applied and tested this fix on local and it works for all 3 mentioned scenarios but if i go further i can't see revisions propagated too:

1. create a section with propagate to all sites method for site 1
2. click +new entry, add title, create entry
3. edit that entry, change the title, click create draft and apply draft, again edit and change title -with or without clicking create draft-
4. add another enabled site -site2- for that section
5. you can see current status and drafts are propagated correctly
6. you can see the revisions are not propagated for site2

**Comment by timkelty** [comment]
@vnali Revision are addressed in Craft 4, but is a breaking change.

For the next Craft 3 release, we've [added a `--revisions` flag](https://github.com/craftcms/cms/commit/3e213d2679f219a8ef0dd5bd9d77d8b57dfe23fa) to the `resave/entries` cli command, so following your section changes, you can run:

```
craft resave/entries --section=my-section --revisions
```

**Comment by vnali** [comment]
@timkelty it throws 'Skipped resaving .... because it's a revision' which it is related to third argument [here](https://github.com/craftcms/cms/blob/3e213d2679f219a8ef0dd5bd9d77d8b57dfe23fa/src/console/controllers/ResaveController.php#L456) explicitly set to true.

**Comment by timkelty** [comment]
@vnali d'oh…try now :)

**Comment by vnali** [comment]
It works. thanks!
