### ISSUE TITLE
Stampede of requests to `queue/get-job-info`

### ISSUE THREAD

**Issue by nickdunn** [craftcms/cms#10632]
### Description
I'm debugging a server event which brought down a site.

In the logs I'm seeing a large number of requests matching `POST /index.php?p=cms/actions/queue/get-job-info&limit=50&dontExtendSession=1`, which is the UI checking the status of the queue. I seem to get a stampede of requests in quick succession over the course of a couple of minutes.

e.g.

![image](https://user-images.githubusercontent.com/39560/155361275-09fe6afc-c34d-4a11-a96a-ffa4c7958eae.png)

When a save event occurred and jobs were added to the queue, the AJAX requests are fired to monitor progress. This would yield maybe 3–5 AJAX requests in the current tab, one every 500ms or so until the queue is complete a few seconds later.

My further suspicion is the CMS user may have had many dozens of Craft entries open (potentially more, who knows, trying to find this in the logs too!) and that all of these tabs would have then fired AJAX requests too, checkin the queue, even though they're not the active browser tab.

My suspicion is backed up with the fact that I'm also seeing a number of `GET /index.php?p=cms/actions/users/session-info&dontExtendSession=1` throughout this stampede of requests, suggesting maybe they've had a load of tabs open for some time.

1. Is it possible to configure the polling frequency of the endpoint, say to once per second, to reduce the number of requests?
2. Is it possible that having a lot of tabs open would have caused a stampede of requests? Sometimes the queue gets stuck and the sidebar shows "Failed", and I don't know if that means page views are always issuing more requests to check the queue status.
3. If 2 above is a possibility, could/should https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilityState be used to prevent a stampede?
4. Is there anything else that could be issuing a large number of these internal requests?

### Additional info

- Craft version: 3.7.28
- PHP version: 8.0.1
- Using the Async Queue plugin

**Comment by brandonkelly** [comment]
I wasn’t aware of `document.visibilityState`! Looks like we should be able to avoid these polling requests with that.

**Comment by nickdunn** [comment]
Can you conform my assumption... that if you have multiple tabs open, if a queue job is started, will all open tabs start polling? Does this also happen if the sidebar shows the "Failed" queue state?

**Comment by brandonkelly** [comment]
I had hoped to get this into 4.0, but couldn’t get to it in time. It’s done for 4.1 now though!

If you want to test, you can change your `craftcms/cms` requirement in composer.json to `4.1.x-dev`, and run `composer update`.
