### ISSUE TITLE
Option to toggle name and handle on every page

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1063]
> Created by: Michael Jackson (craftcms@cuvox.de) on 2016/08/04 13:37:58 +0000
> Votes at time of UserVoice import: 4

-----------------------------------

I really think that this should be some core feature because of its importance when developing. I think it would be enough and simple enough if you have some trigger (shift+click or something like this) and every text get's replaced with its handle. on another click it toggles and the name is visible again.

**Comment by brandonkelly** [comment]
Think this is basically asking for the same thing as #5833, so will mark this as a duplicate.
