### ISSUE TITLE
Call to a member function saveFileLocally() on null

### ISSUE THREAD

**Issue by sarahschuetz** [craftcms/cms#10633]
### Description
Manually creating and saving assets in custom module fails with error: `Call to a member function saveFileLocally() on null` since update to Craft 3.7.34.

The code for creating and saving the asset is:
```
$folder = VolumeFolder::find()->where(['name' => self::DOCUMENT_ASSET_VOLUME_NAME])->one();
$asset = new Asset();
$asset->tempFilePath = $path;
$asset->newFolderId = $folder->id;
$asset->volumeId = $folder->volumeId;
$asset->avoidFilenameConflicts = true;
$asset->filename = basename($path);
$result = \Craft::$app->elements->saveElement($asset);
```
The file is stored outside the project root folder and exists at the given path.

The exact code causing the problem is 
```
$oldFolder = $this->folderId ? $assetsService->getFolderById($this->folderId) : null;
$oldVolume = $oldFolder ? $oldFolder->getVolume() : null;
```
in `src/elements/Asset.php`. `$oldVolume` is null which finally throws the error in line 2255.
Everything worked fine before updating. (Previous version: 3.6.11.2)

### Additional info

- Craft version: 3.7.34
- PHP version: 7.4

**Comment by Anubarak** [comment]
@sarahschuetz Just as a quick fix for you. The difference is: Craft stores the file in a tmpPath "Volume".
```PHP
// exception
 $asset->tempFilePath = $uploadedFile->tempName;

// all good
$asset->tempFilePath  = $uploadedFile->saveAsTempFile()
```

Something like this will at least prevent the exception for the time being
```PHP
$uploadedFile = UploadedFile::getInstanceByName('file');
if($uploadedFile){
    $folder = VolumeFolder::find()->where(['name' => self::DOCUMENT_ASSET_VOLUME_NAME])->one();
    $tempPath = $uploadedFile->saveAsTempFile();
    $filename = Assets::prepareAssetName($uploadedFile->name);

    $asset = new Asset();
    $asset->tempFilePath = $tempPath;
    $asset->filename = $filename;
    $asset->newFolderId = $folder->id;
    $asset->setVolumeId($folder->volumeId);
    $asset->uploaderId = Craft::$app->getUser()->getId();
    $asset->avoidFilenameConflicts = true;
    $asset->setScenario(Asset::SCENARIO_CREATE);
    $result = Craft::$app->getElements()->saveElement($asset);
}
```

**Comment by sarahschuetz** [comment]
Thanks @Anubarak!

My Problem was, actually, that I didn't upload the file directly. It was already on the server (generated by another application). However, the file was located outside the project root folder, which didn't seem to be an issue in previous Craft versions but is now. Your answer pointed me in the right direction, though!

I now move the file to `runtime/temp` folder manually before creating the asset and everything works as expected again. 🎉

@brandonkelly / @andris-sevcenko I still think there might be some problem with the `_relocateFile` method in Asset.php.

**Comment by andris-sevcenko** [comment]
@sarahschuetz it's not handling it very gracefully, indeed. I'll update this on Monday!

**Comment by andris-sevcenko** [comment]
Added this and forgot to update the changelog. This has been addressed in yesterday's release and a more explicit error message will be thrown from now on!
