### ISSUE TITLE
Blank screen after updating phpdotenv to 5.4.0 in a 3.7.34 install

### ISSUE THREAD

**Issue by jeromecoupe** [craftcms/cms#10645]
### Description

Upgraded Craft to 3.7.34 and upgraded plugins (Feedme 4.4.1.1 and Redactor 2.10.4). Everything was fine.
Then proceeded to upgrade `phpdotenv` from 3.4.0 to 5.4.0
All upgrades were done via composer

Blank page after that on the front-end and CP. 
Reverted `phpdotenv` to 3.4.0 and back to normal

- created a craft project from scratch and noticed that `web/index.php` had changed and that there was a new `./boostrap.php` file in the root dir.
- replaced `web/index.php` with the new version of the file and copied `./boostrap.php` over 
- upgraded  `phpdotenv` to 5.4.0
- everything seems to work fine

**My questions are:** 

- did I miss something in previous upgrades ?
- should I also copy over the ./craft executable from the new install ?
- is there any other files I should worry about ?

### Steps to reproduce

1. Upgrade craft install and leave phpdotenv to 3.4.0 
2. Blank pages
3. Copy web/index.php and boostrap.php and everything seems ok

### Additional info

- Craft version: 3.7.34
- PHP version: 7.4.21 (mamp)
- Database driver & version: MySQL 5.7.34
- Plugins & versions: Feedme 4.4.1.1 and Redactor 2.10.4

**Comment by angrybrad** [comment]
`phpdotenv` 5.x initializes itself differently than how 3.x did.

Here's the 5.x syntax Craft uses in the shared bootstrap: https://github.com/craftcms/craft/blob/main/bootstrap.php#L13-L16

Older versions of https://github.com/craftcms/craft had phpdotenv loading in both public index.phd the craft executable.

Recent ones have moved to the shared bootstrap model so it only has to be maintained in one place.

Regardless, sounds like if you copy the public index.php, `craft` executable and the shared bootstrap, you'll be good to go.

**Comment by jeromecoupe** [comment]
That sounds clear enough. Thanks for chiming in @angrybrad 

My main goal was to make sure I understood what was going on and that I was not missing anything in terms of what I should pay attention to. All good.
