### ISSUE TITLE
Element::getFieldValue() always returns null on 3.7.33

### ISSUE THREAD

**Issue by matfish2** [craftcms/cms#10652]
### Description

Since version 3.7.33 When calling `getFieldValue` on an element (`Element.php:3342`) the method returns `null` rather than the actual value.
I've downgraded to 3.7.32 and it works as expected.

### Steps to reproduce

1. Fetch an element, e.g `$el = craft\Elements\Entry::find(1071)->one()`
2. Call `$el->getFieldValue('customFieldHandle')`

### Additional info

- Craft version: 3.7.33
- PHP version: 8.0.9
- Database driver & version: MySQL (same for Postgres)
- Plugins & versions:

**Comment by brandonkelly** [comment]
Strange… nothing changed to `getFieldValue()` between those versions, and all custom field retrieval goes through `getFieldValue()` so if there was a problem with it we would have heard a _lot_ of reports about it.

Did you try 3.7.34?

**Comment by matfish2** [comment]
Seem to be resolved in 3.7.35. Might have been some local issue. Closing, thanks.
