### ISSUE TITLE
Global Variables cause downtime while creating a new Draft

### ISSUE THREAD

**Issue by internetztube** [craftcms/cms#10662]
### Description
When creating a Draft or a Provisional Draft the whole Craft CMS Instance gets unresponsive. I dug my way through all the installed plugins and I found out that `image-optimize` and `seomatic` are causing this problem.

I "resolved" the issue by commenting out the initialization of SeomaticVariable in SeomaticTwigExtension. 
**However, Andrew thinks it could be a problem with Craft, which could be exacerbated by plugins.**

I sent our project and our database dump to support.

#### Related Issues:
https://github.com/nystudio107/craft-seomatic/issues/1071

#### Bypasses:
https://github.com/nystudio107/craft-imageoptimize/pull/317
https://github.com/internetztube/craft-seomatic/commit/3c07280b8d45acd1ded214a768c6b4db908d548b

#### To reproduce

1. Go to an entry with many matrix/neo blocks, so creating a draft takes a while.
2. Change an input value to trigger the creation of a provisional draft -or- click "Create a Draft".
3. While the loading spinner is spinning, try to open a different page like Dashboard or Utilities.
4. Those pages don't load until the draft saving process is complete.

### Additional info

- Craft version: 3.7.30.1 (Pro)
- PHP version: 7.3.33
- OS version: Linux 5.13.0-28-generic
- Database driver & version: PostgreSQL 10.6
- Image driver & version: Imagick 3.7.0 (ImageMagick 7.1.0-16)
- Plugins & versions: 
    - Amazon S3 1.3.0
    - Asset Usage 2.2.1
    - CodeMirror 1.0.2
    - Control Panel CSS 2.4.0
    - Control Panel JS 2.4.0
    - CP Field Inspect 1.2.5
    - Element Relations 1.3.3
    - Feed Me 4.4.1.1
    - Field Manager 2.2.4
    - Icon Picker 1.1.12
    - ImageOptimize 1.6.41
    - Linkit dev-master
    - Neo 2.12.4
    - Redactor 2.8.8
    - SEOmatic 3.4.23
    - Smith 1.1.14
    - Snitch 3.0.4.1
    - Super Dynamic Fields 1.0.6
    - Super Table 2.7.1
    - Translations v2.1.2
    - UI Element fields 1.0.0
    - Workflow 1.6.6

**Comment by internetztube** [comment]
I'm not sure if this is really a web server limitation. The problem also exists when two different deployments access the same database. The database also has enough resources.
Also, I'm not sure right now what exactly I should optimize on the web server (nginx, php-fpm) in order to overcome the problem. 😔

Regarding Craft 4. I've been thinking for a long time whether it's an option for us to upgrade to the Craft 4 beta, which should be released in late March, I guess. 
However, I have doubts whether it is really that smart to install a beta on a production system.  

@brandonkelly

**Comment by brandonkelly** [comment]
Upon further investigation, we found that Craft’s `UPSERT` statements for the `resourcepaths` table can cause this, when executed within an entry-save DB transaction.

Fixed for the next release, by deferring all `UPSERT` statements which aren’t particularly time sensitive off to the end of the request.

**Comment by brandonkelly** [comment]
3.7.40 is out now with that change.

**Comment by internetztube** [comment]
I can confirm, that this issue is resolved.

**Comment by Antimated** [comment]
> 3.7.40 is out now with that change.

So to get this update from version 3.7.39 we have to do update the `composer.json` with the new craft `3.7.40` version and run `composer update` right? I mostly update via the control panel or via the `craft update {pluginhandle}` command.

**Comment by brandonkelly** [comment]
@Antimated If you’re only going from Craft 3.7.39 → 3.7.40, there won’t be any new migrations to run, so `composer update` will be enough.
