### ISSUE TITLE
craft\elements\Entry::EVENT_BEFORE_VALIDATE should be passed a craft rather than the base yii ModelEvent

### ISSUE THREAD

**Issue by samhibberd** [craftcms/cms#10672]
Was working with validation events and it looks like the EVENT_BEFORE_VALIDATE event is being sent `yii\base\ModelEvent` where as I think it needs to be passed `craft\events\ModelEvent` if it's possible to access the `$e->isNew` property.

Docs suggest the following which i'm not sure will work?

<img width="489" alt="Screenshot 2022-03-03 at 11 22 47" src="https://user-images.githubusercontent.com/1846063/156555254-c749cd26-df04-4024-ac26-268db745da13.png">

**Comment by brandonkelly** [comment]
We don’t know definitively what `isNew` would need to be set to from there, since it’s not something that gets passed to `validate()`.

**Comment by samhibberd** [comment]
Cool, no worries, moved the logic into the beforeSave.

That something easily reflected in the event builder as that suggests that `$e->isNew` would be available in `yii\base\ModelEvent`

**Comment by brandonkelly** [comment]
@samhibberd Doh, docs bug. Fixed now!
