### ISSUE TITLE
[3.7.35] Migration error when upgrading from Craft 2

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#10685]
### Description

Since Craft 3.7.35, the following migration error is consistently thrown when attempting to upgrade from Craft 2.9.2:

```
*** applying m180411_102218_fix_db_routes
Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'configVersion' in 'field list'
The SQL being executed was: SELECT `configVersion`
FROM `craft_info`
LIMIT 1
```

The issue does not occur on Craft 3.7.34 or earlier.

From looking at [the full stack trace](https://pastebin.com/eDtXTFBe), it appears that b39ce7b59df364b248da82be5ec026be1e43bd43 could be the culprit?

### Steps to reproduce

1. Have a Craft 2.9.2 database at the ready
2. Install Craft 3.7.35+
3. Run `php craft migrate/up --track craft`

### Additional info

- Craft version: 3.7.35
- PHP version: 7.4.27
- Database driver & version: MySQL 5.7.37
- Plugins & versions: none

**Comment by MatMc** [comment]
Migrating from 2.x to 3.7.34, and then to 3.7.35+ is a work around.

**Comment by mmikkel** [comment]
It just occurred to me that this issue would probably also occur for sites upgrading from Craft 3.0.x to 3.7.35+, assuming Craft 3.1.0 is when that `configVersion` was added. I haven't tested that though.

**Comment by brandonkelly** [comment]
Thanks @mmikkel. Just fixed for the next release.

**Comment by akukral** [comment]
Which update is this fixed in? Im still encountering the same error updating from 2.9.2. -> 3.7.36

Are there steps I'm missing to ameliorate the issue when making the update?

`Database Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'configVersion' in 'field list'
The SQL being executed was: SELECT configVersion
FROM craft_info
LIMIT 1`

**Comment by MatMc** [comment]
@akukral 3.7.36 is the current release, it will be fixed in the upcoming 3.7.37 release. The workaround for now is upgrading to 3.7.34 first, and then to 3.7.36

**Comment by brandonkelly** [comment]
Craft 3.7.37 is out now with this fix.

**Comment by brandonkelly** [comment]
@JayBox325 That’s a slightly different error so please post as a new issue, along with the stack trace leading up to the error, which you should be able to find in your logs (`storage/logs/`).

**Comment by JayBox325** [comment]
Ok, I've actually downgraded the site to 3.5 along with all the plugins to relevant levels then done what someone suggested on StackOverflow and squashed my vendor/composer.lock to start fresh at that level. Seemed to resolve it! That or not trying to do this at 3am helped. Appreciate you getting back to me. If it comes up again, I'll log a new ticket.

**Comment by brandonkelly** [comment]
Feeling attacked :)

<img width="182" alt="Screenshot of my macOS system clock, showing the current time is 2:50am" src="https://user-images.githubusercontent.com/47792/163360620-2141c83c-f205-4867-b68a-36190c9c27cf.png">
