### ISSUE TITLE
4.0 problem with top site menu for custom element types

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#10693]
first of all, i should say i love the way new element editor gives custom element types ability to have site status on the right side like custom propagation for section does for entries.

 **Description**
- testing custom element type, i noticed site name won't show up in menu button on top of edit pages - same for entries related to sections with custom propagation method.
- on editing custom element type, adding a new site from right side bar and changing top site menu to edit content of that site, removes first site from site status list on the right.

Thanks

**Additional info**
- Craft version: 
Craft 4 alpha 1

**Comment by vnali** [comment]
sorry @brandonkelly . i should have mentioned this is related to multi site. 
![Untitled - Copy](https://user-images.githubusercontent.com/55586085/157493051-a7240ede-505e-4ffc-94b6-d3c88ce00f66.png)

for second issue, it happens only for custom elements. 
currently depending on what hasRevisions and canCreateDrafts returns, i see different behavior from my plugin.
as you mentioned on discord maybe we should wait for plugin migration guide for 4 and see how it goes.

**Comment by vnali** [comment]
just an update @brandonkelly 

> * testing custom element type, i noticed site name won't show up in menu button on top of edit pages - same for entries related to sections with custom propagation method.

I misunderstood your last reply 
still, there is a problem with the custom propagation method even though entry is enabled for two sites
my previous comment shows how the site name doesn't appear on the menu button

> * on editing custom element type, adding a new site from right side bar and changing top site menu to edit content of that site, removes first site from site status list on the right.

That was my fault. I should add these lines when getting $currentsites on the getSupportedSites function of that element type
```
...
->drafts(null)
->provisionalDrafts(null)
...
```

**Comment by brandonkelly** [comment]
Hey @vnali, can you please send your Composer files, a database backup, and your plugin code over to support@craftcms.com? I can take a look at it from there.

**Comment by vnali** [comment]
Hi @brandonkelly 
i don't have a problem with right side site selector anymore 
but top site menu problem with custom propagation method actually happens without any plugin. 
there is a video on fresh latest craft 4 dev without any plugin - sorry, i should have done that in the first place -


https://user-images.githubusercontent.com/55586085/161790844-e89a661c-be28-48fd-967e-83da7104c328.mp4

**Comment by brandonkelly** [comment]
Ahhh, got it. Just fixed that for the next release!

**Comment by brandonkelly** [comment]
Craft 4.0.0-beta.4 is out now with that fix.
