### ISSUE TITLE
Missing variables in the error template

### ISSUE THREAD

**Issue by darrylhein** [craftcms/cms#10697]
### Description

[In the documentation](https://craftcms.com/docs/3.x/routing.html#accessing-named-parameters-in-your-controllers) it says that the variables `message`, `code`, `file`, etc will be available in the template file. I've created the templates (`templates/error.twig` and `templates/404.twig`) and they are accessible at the correct URLs, but when I attempt to use any of the variables, I receive an error about them not existing.

In addition, when I set `'errorTemplatePrefix' => '_',` inside my config and then rename the templates prefixing the names with an underscore (`templates/_error.twig` and `templates/_404.twig`) the templates no longer load and I receive an error that the template cannot be found. It says it's looking for the non-underscore version. Renaming the template without the underscore results in it working again. (Thus, config says to include the underscore while it's loading the non-underscore version.) Also, if I try to go to `/_error` I get a 404 from Craft, but nothing about the template missing.

I've only tried this on the dev site.

It's possible I'm just misunderstanding the docs.

### Additional info

- Craft version: 3.7.36
- PHP version: 7.4.28
- Database driver & version: MySQL 5.7.37
- Plugins & versions:
  - Asset Rev	6.0.2
  - Contact Form	2.3.0
  - Contact Form Extensions	1.2.8
  - Contact Form Honeypot	1.0.2
  - Craft CMS Easy MDE Markdown Editor	0.1.7
  - oEmbed	1.3.13
  - Redactor	2.10.5

**Comment by timkelty** [comment]
@darrylhein Those variables will only be available when the templates are triggered from an actual error.
This means that if you simply request `/404/`, it will load `templates/404.twig` as a non-error page.

To trigger it as an error, you'd need to request an actual 404, eg `/foobar/`.

However, when you have [`devMode`](https://craftcms.com/knowledge-base/what-dev-mode-does) enabled, as it sounds like you do, error templates are overridden (including 404s).

If you try your second approach with `errorTemplatePrefix` set, and `devMode` set to false, you should see the templates rendered with the variables available.

**Comment by darrylhein** [comment]
@timkelty How is one to test if their error templates are working correctly while in dev mode? It seems that if I wanted to create a generic error page and use the variables, I'll receive and undefined error and be unable to view the page. What's your recommended workaround?

Might I recommend updating the documentation so this is clear?

**Comment by timkelty** [comment]
> How is one to test if their error templates are working correctly while in dev mode? 

Easiest way is to turn off `devMode`.

You're right, this could definitely be clearer in the docs! We will improve them.
