### ISSUE TITLE
EVENT_DEFINE_ASSET_URL never triggered in Craft 4

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#10692]
The `EVENT_DEFINE_ASSET_URL` event is never triggered, because the `getAssetUrl` method is not called from anywhere. My guess is that this method is being bypassed when the asset URL is being generated in `Asset::getUrl()`, but this results in the event being unusable by plugins.
https://github.com/craftcms/cms/blob/a8bace4230763cbe5b3f7dde1df0bf0821861b42/src/services/Assets.php#L593-L614

### Additional info

- Craft version: 4.0.0-alpha.1

**Comment by andris-sevcenko** [comment]
This will be resolved in the beta. I'm currently reworking the events and adding a few more things for 4.0. I plan to PR those changes on Monday (08.03.22).
