### ISSUE TITLE
4.0 console error on save a draft and create a draft 

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#10704]
saving a draft or creating a draft throws a console error but it seems draft saves correctly

![error](https://user-images.githubusercontent.com/55586085/157095906-eff92494-4339-41e2-afc6-4558c656a5f5.jpg)

 **Additional info**
- Craft version: 4.0x-dev

**Comment by timkelty** [comment]
@brandonkelly Removing this `reject` [here](https://github.com/craftcms/cms/blob/4.0/src%2Fweb%2Fassets%2Fcp%2Fsrc%2Fjs%2FElementEditor.js#L926) fixes this, but I'm not familiar with the `Queue.js` stuff, so I wasn't 💯 this was the right fix.

**Comment by brandonkelly** [comment]
Fixed for the next release! Thanks for reporting @vnali

**Comment by brandonkelly** [comment]
Craft 4.0.0-beta.2 is out now with that fix. Thanks again!
