### ISSUE TITLE
Duplicate doesn't duplicate titles of multi-site entries and products

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#10702]
### Description
When on the overview page of entries or products, and you select an entry, you click on the gear icon on top and select "Duplicate". The entry is duplicated and all fields are duplicated in the correct language if you have a multi-site. Only the title is in the "Default site" title with "copy" added to the end. It is not the translated title for all languages.

For example and entry with these titles:
- en-US: Craft CMS EN
- nl-NL: Craft CMS NL
- de-DE: Craft CMS DE
becomes after duplicate in all languages "Craft CMS EN copy".

But if you are on an entry page and you select "Save as new entry", the title are saved in all languages. 

- Craft version: 3.7.36

**Comment by brandonkelly** [comment]
This has been fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 3.7.38 is out now with the fix for this.
