### ISSUE TITLE
Yii is not loading errors properly.

### ISSUE THREAD

**Issue by clse** [craftcms/cms#10712]
### Description
Instead of the typical craft error rendering, when an error occurs, it renders a blank page with plain text inside a `pre` tag (rather than styled divs and markup). Using latest craft config settings.

<img width="1456" alt="Screen Shot 2022-03-08 at 8 15 24 PM" src="https://user-images.githubusercontent.com/2072498/157314334-e32fd572-ef9c-47a8-82b4-c1801cbc4545.png">

```
An Error occurred while handling another error:
ValueError: Path cannot be empty in /Users/redactedUser/RedactedPathToProject/vendor/yiisoft/yii2/web/ErrorHandler.php:304
Stack trace:
#0 /Users/redactedUser/RedactedPathToProject/vendor/yiisoft/yii2/web/ErrorHandler.php(304): file('')
#1 /Users/redactedUser/RedactedPathToProject/vendor/craftcms/cms/src/web/ErrorHandler.php(232): yii\web\ErrorHandler->renderCallStackItem('', 27, NULL, NULL, Array, 1)
#2 /Users/redactedUser/RedactedPathToProject/vendor/yiisoft/yii2/web/ErrorHandler.php(336): craft\web\ErrorHandler->renderCallStackItem('', 28, NULL, NULL, Array, 1)
#3 /Users/redactedUser/RedactedPathToProject/vendor/yiisoft/yii2/views/errorHandler/exception.php(441): yii\web\ErrorHandler->renderCallStack(Object(Twig\Error\RuntimeError))
#4 /Users/redactedUser/RedactedPathToProject/vendor/yiisoft/yii2/base/View.php(347): require('/Users/redactedUser/...')
#5 /Users/redactedUser/RedactedPathToProject/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/Users/redactedUser/...', Array)
#6 /Users/redactedUser/RedactedPathToProject/vendor/yiisoft/yii2/web/ErrorHandler.php(270): yii\base\View->renderFile('/Users/redactedUser/...', Array, Object(craft\web\ErrorHandler))
#7 /Users/redactedUser/RedactedPathToProject/vendor/yiisoft/yii2/web/ErrorHandler.php(127): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#8 /Users/redactedUser/RedactedPathToProject/vendor/craftcms/cms/src/web/ErrorHandler.php(192): yii\web\ErrorHandler->renderException(Object(Twig\Error\RuntimeError))
#9 /Users/redactedUser/RedactedPathToProject/vendor/yiisoft/yii2/base/ErrorHandler.php(135): craft\web\ErrorHandler->renderException(Object(Twig\Error\RuntimeError))
#10 /Users/redactedUser/RedactedPathToProject/vendor/craftcms/cms/src/web/ErrorHandler.php(71): yii\base\ErrorHandler->handleException(Object(Twig\Error\RuntimeError))
#11 [internal function]: craft\web\ErrorHandler->handleException(Object(Twig\Error\RuntimeError))
#12 {main}
Previous exception:
```

### Additional info

- Craft version: 3.7.36
- PHP version: 7.4
- Plugins & versions: yiisoft/yii2-shell": "^2.0.3

Using laravel valet locally.

**Comment by brandonkelly** [comment]
This happens when an error occurs in the error reporting view itself.

Just fixed this particular case, for the next release. Thanks for reporting!

**Comment by clse** [comment]
Thank you @brandonkelly ! Is there anything I can do in the meantime to get it working? When are you thinking the next release will go out? :)

**Comment by brandonkelly** [comment]
You can see the actual error in that second error output that starts after `Previous exception:`.

Looks like you’re referencing an `intentionallyBrokenVariable` somewhere—probably within a setting.

**Comment by clse** [comment]
@brandonkelly Sorry, I meant is there any way to fix the broken styling. The `intentionallyBrokenVariable` is something I broke intentionally for demonstration purposes for this issue!

**Comment by brandonkelly** [comment]
Ah sorry. To get the fix early, change your `craftcms/cms` constraint in `composer.json` to `"dev-develop as 3.7.36"`, then run `composer update`.

**Comment by clse** [comment]
Ahh fantastic, that worked perfectly! Thank you again, @brandonkelly

**Comment by brandonkelly** [comment]
Craft 3.7.37 is out now with this fix.

**Comment by clse** [comment]
Thanks so much Brandon!
