### ISSUE TITLE
4.0 Re-ordering Sections, Volumes etc doesn't persist

### ISSUE THREAD

**Issue by engram-design** [craftcms/cms#10715]
When re-ordering certain things, the order seems to change and a success message shown, but it doesn't seem to persist once you reload the page. This can be seen for Sections, Entry Types and Volumes. Likely something project config?

**Comment by andris-sevcenko** [comment]
This will be resolved once #10709 gets merged. You might have to do a `./craft project-config/rebuild` beforehand, though, as the data in the DB might not match what's in the PC storage.
