### ISSUE TITLE
Potential typo in the "Mutex Locks" section of the Load Balancer article in the Knowledge Base?

### ISSUE THREAD

**Issue by aaronbushnell** [craftcms/cms#10720]
This may not be a typo, but should the code example in the ["Mutex Locks" section of the Load Balancer article in the Knowledge Base](https://craftcms.com/knowledge-base/configuring-load-balanced-environments#mutex-locks) use `class` as the array key for the `yii\redis\Mutex` reference? Or is the duplicative usage of `mutex` correct?

```diff
return [
    'components' => [
        'mutex' => [
-            'mutex' => 'yii\redis\Mutex',
+            'class' => 'yii\redis\Mutex',
        ],
    ],
];
```

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed now.

**Comment by aaronbushnell** [comment]
You bet, @brandonkelly!

**Comment by aaronbushnell** [comment]
Hey @brandonkelly — I recently needed to implement this but noticed the KB still has the duplicative `mutex` array key. Is that correct? I noticed the Yii docs use `class`. 

![25FB516B-BBAD-4768-B197-086FC508513E](https://user-images.githubusercontent.com/315202/182269241-b0fc92ad-2957-4077-a4f9-e367f69320cb.jpeg)


https://www.yiiframework.com/extension/yiisoft/yii2-redis/doc/api/2.0/yii-redis-mutex

**Comment by brandonkelly** [comment]
Yeah looks like it was reverted back, because it was correct to begin with. As the page says right before the code block:

> To configure a custom mutex driver in **Craft 3.7.30 or later**, you should leave the main `mutex` component in-tact, and configure its nested `$mutex` property instead.

**Comment by aaronbushnell** [comment]
Thanks!
