### ISSUE TITLE
Assets are erroneously eager-loaded when previewing auto-saved version of entry, causing Twig errors

### ISSUE THREAD

**Issue by michaelrog** [craftcms/cms#10728]
When Previewing an auto-saved version of my entry (in the live Preview, or via the sharable View URL), an asset field appears to be erroneously eager-loaded — i.e. its value comes back as an array — which causes a Twig Runtime Error in the entry template. (The template expects to invoke `.one()` on an `AssetQuery`.)

### Steps to reproduce

1. Open entry with asset field, in current version — Version dropdown shows "Current"
2. Open the entry **Preview** and see it rendered in its template as expected.
3. **Close Preview**
4. Make some change — Version dropdown updates to "Current — Edited"
5. Open the entry **Preview** and see an error from asset field usage: `Impossible to invoke a method ("one") on an array.`

### Additional info

- Craft CMS 3.7.36
- PHP version: 7.4

**Comment by brandonkelly** [comment]
Craft doesn’t do any of its own eager-loading on the front end, so pretty sure this is going to be due to something you’re doing, either in a template or perhaps a plugin/module.

**Comment by michaelrog** [comment]
That was my first thought, as well... but the same template works fine when rendered on the live site, and when previewing a saved entry.

It's only in Live Preview, when viewing a _provisional (auto-saved) draft_, that the error occurs. I'm definitely not doing anything in my template to differentiate those situations.

I'll try to package up a minimal demo to reproduce this... but in the meantime, could you suggest any common gotchas I might also look for?

**Comment by brandonkelly** [comment]
You could put a breakpoint on this line, with a `$handle === 'myAssetsFieldHandle'` condition:

https://github.com/craftcms/cms/blob/1bcf1e9170f0024b888251dd204958989aca296b/src/base/Element.php#L3655

When it hits, you should be able to look at the backtrace and figure out where it’s coming from.
