### ISSUE TITLE
Redactor bug inserting links in unordered lists destroys other links

### ISSUE THREAD

**Issue by joomkit** [craftcms/cms#10721]
### Description
Adding links into a line item in an unordered list destroys other links in adjacent line items

### Steps to reproduce

1. Create an unordered list of 5 text line items in a redactor field
2. Create a link in the line item text by inserting a link to an asset or an entry from the link button
3. The second or third time you add a link into the text of the line item, the links in the line items above are destroyed 

### Additional info
-Redactor 2.10.5
- Craft version: 3.7.36

**Comment by andris-sevcenko** [comment]
This has already been reported here: https://github.com/craftcms/redactor/issues/374

Currently, there's not much we can do and I've already reached out to Imperavi for some guidance on this matter.

I'll close this, so we have a single issue to keep track of this!

**Comment by joomkit** [comment]
Thanks! I did search redactor issues honest :)

**Comment by andris-sevcenko** [comment]
Haha, no worries :)
