### ISSUE TITLE
[4.0.0-beta.1] Entry conditions missing in field layout designer

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#10723]
### Description

Great to see conditional fields, however the slide out for field settings only show 'Current User Condition' and no 'Entry Condition'

![image](https://user-images.githubusercontent.com/60010597/157616698-bd997ae4-c9f8-4cec-93d5-c3c2aa849565.png)

PS.
Looks like once you clicked inside the slide out, you can't close it by clicking outside anymore. A `Cancel` button would be great.

### Steps to reproduce

1. Edit an entry type
2. Open field settings

### Additional info

- Craft version: 4.0.0-beta.1 (Fresh install)
- PHP version: 8.0.15
- Database driver & version:
- Plugins & versions: none

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release. (Was caused by #10695.)

**Comment by brandonkelly** [comment]
Craft 4.0.0-beta.2 is out now with that fix. Thanks again!
