### ISSUE TITLE
[4.0.0-beta.1] Translatable title/custom fields are not propagated on fresh entries

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#10724]
### Description

Unlike in 3.7, title and translatable fields are not properly propagated to other sites on fresh entries when saving or switching sites.

Matrix and non translatable fields look ok at first glance.

### Steps to reproduce

1. Two sites (en/de), title and a plaintext field are translatable
2. Create fresh entry, fill in title/text field in de
3. Set status = disabled for both sites
4. Create entry: `craft\helpers\ElementHelper::generateSlug(): Argument #1 ($str) must be of type string, null given, called in E:\craft\craft4_beta\vendor\craftcms\cms\src\validators\SlugValidator.php on line 71`
5. Switch site to en: Title/Textfield/Slug are empty, leaving the editor without any clue what to translate

### Additional info

- Craft version: 4.0.x-dev
- PHP version: 8.0.15
- Database driver & version:
- Plugins & versions: none

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release.

**Comment by wsydney76** [comment]
@brandonkelly Thanks. looks good in full page edit mode.

However, if you add a new entry in a slideout window, title/translatable fields are still empty in the second site.

Entries field -> Add an entry -> New entry -> Fill in title/fields -> Save -> Switch site

![image](https://user-images.githubusercontent.com/60010597/158135668-f8dd8d0b-3758-4d76-98d6-9f1c1cdd9016.png)

**Comment by brandonkelly** [comment]
Doh thanks, fixed that as well.

**Comment by wsydney76** [comment]
@brandonkelly Thanks again, works in slideouts, but now fails again in full page mode:

![image](https://user-images.githubusercontent.com/60010597/158342412-51e4f385-c953-46ca-ac64-3f1beb0c7f63.png)

Change site:

![image](https://user-images.githubusercontent.com/60010597/158342647-6ff558bf-a78e-4f72-b489-3b098c0bc37a.png)

Beginning to loose trust in myself, but pretty sure it worked after the first fix.

**Comment by brandonkelly** [comment]
Craft 4.0.0-beta.2 is out now with those fixes. Thanks for the help!
