### ISSUE TITLE
Multi site URL slug bug with Singles

### ISSUE THREAD

**Issue by bradleyw92** [craftcms/cms#10727]
### Description

- Site is a multi-site config
- We have a craft single called Location Overview
- Default site is English with additional sites Finland and Italy.

### Steps to reproduce

- Default location overview slug is set to locations
- Finland slug of location overview single is toimipisteet
- Italy slug of location overview single is uffici-di-noleggio
- On the Finland locations page we can access with either /locations or the Finnish url of toimipisteet
- Interestingly you can’t access it by uffici-di-noleggio which is the Italian one.

Is there a bug where you can access by the parent / default slug also?

Interestingly I can access the default locations overview page with no slug and disabling it on the Finland version.

### Additional info

- Craft version: 3.7.25.1
- PHP version: 8.0.13
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
What is the section’s template path set to, for each of these sites?

**Comment by bradleyw92** [comment]
@brandonkelly they are set to locations/index

Interestingly if I disable the single called locations overview the page still displays so I wonder if there is either a bug in this area or whether there used to be a /locations page/post where it displays. 

I obviously can't see anything there but what I would say is if I go to create a page with the URL of locations it does indeed appear instead of the single. And if I delete it the single then appears again.

Any ideas?

**Comment by brandonkelly** [comment]
What’s happening is, the template is being accessed directly on the non-default sites, rather than the Single entry.

If you rename your template to `_locations/index` and update your section settings, `locations` will no longer resolve to a public template.
