### ISSUE TITLE
GraphQL returns entries in random ID order instead of the order in which they were specified

### ISSUE THREAD

**Issue by GustavTaxen** [craftcms/cms#10722]
### Description

When querying entries with IDs via GraphQL, Craft seems to return them in random order instead of the order in which the IDs were specified.

### Steps to reproduce

1. Create 3-4 entries and note their IDs.
2. Open the "Explore the GraphQL API" tab from the Control Panel.3. 
3. Enter the following query (replacing the IDs with the ones on your server):

```
{
  entries(id:["313629", "313599", "313647"]) {
    id
  }
}
```

Expected: Entries are returned in the same order as they are specified in the list of IDs.
Actual result: Entries are returned in seemingly random order:

```
{
  "data": {
    "entries": [
      {
        "id": "313599"
      },
      {
        "id": "313629"
      },
      {
        "id": "313647"
      }
    ]
  }
}
```

I've tried shuffling the ID list in various ways but I cannot find a pattern in the way the result is returned.

### Additional info

- Craft version: 3.7.26
- PHP version: 8.0.16
- Database driver & version: MySQL 10.6.5
- Plugins & versions: Feed Me 4.4.1.1, Redactor 2.8.8

**Comment by Wiejeben** [comment]
I believe Underlying it is doing a WHERE query on the database, this also wouldn't return results back in the same order. Personally I'd look into trying to make the results be reordered in the frontend if that was a possibility.

**Comment by andris-sevcenko** [comment]
You should be also passing `fixedOrder: true` in your query, similar to how [you would have to do it for element queries](https://craftcms.com/docs/3.x/entries.html#fixedorder).
