### ISSUE TITLE
[4.0.0-beta.1] Files get uploaded to wrong location?

### ISSUE THREAD

**Issue by jowhannez** [craftcms/cms#10725]
### Description

Maybe I have misunderstood something here. When you add a filesystem to a volume and then upload a file to the volume, it gets placed in the root folder of the filesystem instead of the volume folder.

### Steps to reproduce

1. Create file system
2. Create volume
3. Add file to volume
4. File should appear in web/filesystem/ instead of web/filesystem/volume/

### Additional info

- Craft version: 4.0.0-beta.1
- PHP version: 8.0.16
- Database driver & version: MySQL 10.5.9
- Plugins & versions: Redactor 3.0.0-beta.1

![Screenshot 2022-03-10 at 14 24 26](https://user-images.githubusercontent.com/5490109/157670790-dd6d1f0d-b8d6-463f-bd2b-0fadd5ca642a.png)

**Comment by jowhannez** [comment]
I forgot to mention that I've set the following on my filesystem:

primary url:
@web/uploads

base path:
@webroot/uploads

**Comment by jowhannez** [comment]
I'd assume it would be placed in the folder with the handle of the volume, "images" in this case. Why would the folder exist if the files don't end up there?

**Comment by jowhannez** [comment]
Looks like the folders were artifacts from my template, I tried making a new volume now and it didn't make a new folder. Oops!

**Comment by andris-sevcenko** [comment]
Glad it's working, then! Cheers!
