### ISSUE TITLE
[4.0.0-beta.1] Slideout Editor: Columns can become too narrow

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#10726]
### Description

When opening an entry in the slideout editor, columns can become to narrow, e.g. when set to 25% width:

![image](https://user-images.githubusercontent.com/60010597/157681720-c82773bb-bc5d-4969-8efd-5aeefe5ba42c.png)

### Steps to reproduce

1. See above
2.

### Additional info

- Craft version: 4.0.x-dev
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just limited field grids to two columns within slideouts.

**Comment by brandonkelly** [comment]
Craft 4.0.0-beta.2 is out now with that fix. Thanks again!
