### ISSUE TITLE
[4.0.0-beta.1] type error on empty author

### ISSUE THREAD

**Issue by JansenLukas** [craftcms/cms#10734]
### Description
When creating an entry through code and you don't pass in an author, or through the CP panel and you remove the author, the entry is getting created without author but when you than want to update the entry again in the CP you get a typeError that the author needs to be en int|user|null but an empty string is passed

### Steps to reproduce

1. Create an entry, remove the author and resave

### Additional info

- Craft version: 4.0.0-beta.1

**Comment by brandonkelly** [comment]
Craft 4.0.0-beta.2 is out now witht hat fix. Thanks again!
