### ISSUE TITLE
not able to login: Unable to verify your data submission

### ISSUE THREAD

**Issue by mdoorschodt** [craftcms/cms#10733]
### Description

On a pretty frequent basis (multiple times a week) we cannot login to the cms. After filling in the username and password, we get the following message:

Bad Request
Unable to verify your data submission.

Even in an anonymous window we are not able to login
The only way to fix this in chrome is to completely wipe the browser cache and restart chrome

### Steps to reproduce

1. logging in to CMS

### Additional info

PHP version | 7.4.28
-- | --
Linux 4.19.0-18-amd64
MySQL 8.0.25
GD 7.4.28
Craft Pro 3.7.30.1

**Comment by mdoorschodt** [comment]
Hello Brad,

Yes, the login issues are indeed happening on a load-balanced web server.
Though both (I believe there are two Craft instances running) are using the
same Redis instance for cache and sessions.  We applied the example found
here: https://craftcms.com/docs/3.x/config/#redis-example-2

Regards,
Boudewijn

**Comment by tomkiss** [comment]
I was also seeing this on a Nitro instance. 

FWIW it occurs when you access the site over `http` and not `https`. 

It's a bit annoying as the browser will default to http if you just type in the hostname on its own. It's really easy to miss, just spent 45 minutes trying to figure out what was happening.

Might be nice if nitro forwarded http by default? If that's not too aggressive.

**Comment by brandonkelly** [comment]
Yeah this has been known to happen when you access a site via HTTPS and then later access it via HTTP. If you want to stick with HTTP, you may have to clear out your browser cookies.

**Comment by BenMenking** [comment]
We ran into the "unable to verify data submission" and it turned out that someone set the "defaultCookieDomain" in config/general.php to ".ddev.site" which broke any environment not using .ddev.site as a domain.
