### ISSUE TITLE
Collapse All & Expand All non-functional on Matrix Blocks

### ISSUE THREAD

**Issue by mattbloomfield** [craftcms/cms#10730]
### Description

Matrix blocks have the option to Collapse/Expand all. That button isn't working anymore. It also doesn't work if you select all and use the Collapse/Expand Selected (in the same menu). 

![image](https://user-images.githubusercontent.com/37582550/157727279-26d8c051-ebb3-4b70-8b5c-37705999bee2.png)

However, if you select all and then use the dropdown on a matrix item to collapse it, it will collapse all (which is a good workaround). 

### Steps to reproduce

1. Create a matrix block with multiple elements
2. Add it to an entry type
3. Create a new entry of that type
4. Add several blocks to the matrix
5. Use the context menu to "Collapse All"
6. Note that nothing happens (no console errors)

### Additional info

- Craft version: Craft Pro 3.7.35
- PHP version: 8.0.13
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

![image](https://user-images.githubusercontent.com/37582550/157727544-4b3232de-af95-4cf9-9448-e26ba5b93ac9.png)

**Comment by brandonkelly** [comment]
That’s not a native feature. Perhaps it’s getting added from that “Matrix Toolbar” plugin?

**Comment by mattbloomfield** [comment]
Oh whoops, I inherited this site and didn't realize it. Thanks.

**Comment by mattbloomfield** [comment]
For anyone in the future: https://github.com/monachilada/craft-matrixtoolbar/issues/7
