### ISSUE TITLE
[4.0.0-beta.1] Rogue status above meta fields

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#10738]
A rogue status is appearing above the meta fields on the category edit page in the latest 4.0 commit.

<img width="866" alt="Screenshot 2022-03-12 at 13 35 57" src="https://user-images.githubusercontent.com/57572400/158020109-b293235e-4e78-4b00-a9b0-5aa13d85816c.png">

**Comment by bencroker** [comment]
On closer inspection, this may be a feature, not a bug. Nevertheless, I'd like to suggest considering whether multiple `Status` headings make sense here.

**Comment by brandonkelly** [comment]
Yeah it’s an intentional heading. Just tweaked the styling a bit to make the double “Status” less awkward:

<img width="381" alt="Screenshot of an Edit Entry page sidebar" src="https://user-images.githubusercontent.com/47792/158074614-8ead0497-d9ea-4ab8-b66e-d3126f84bd59.png">

**Comment by bencroker** [comment]
Perfect, thanks!

**Comment by brandonkelly** [comment]
Craft 4.0.0-beta.2 is out now with that change.
