### ISSUE TITLE
[4.0.0-beta.1] - Volume folder not created when volume is

### ISSUE THREAD

**Issue by DowleyDeveloped** [craftcms/cms#10744]
### Description

When you create a volume inside of the CMS, the folder is not created locally until you add assets. This causes the Asset Index to error as it can't find the folder.

### Steps to reproduce

1. Add Volume in CMS
2. Look at local path and see it's not there

### Additional info

- Craft version: 4.0.0-beta.1
- PHP version: 8.0

**Comment by andris-sevcenko** [comment]
Thanks for reporting that! I resolved that for the next release by dealing with the thrown exception, as creating a directory there might be presumptuous, given that the file system and volume division was introduced for multiple environment solutions where only some filesystems would actually be in use per environment.
