### ISSUE TITLE
 [4.0.0-beta.1] View button is hidden

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#10747]
The `View` button (`.share-btn`) is being hidden by some CSS styles on element edit pages.

<img width="863" alt="Screenshot 2022-03-14 at 20 36 33" src="https://user-images.githubusercontent.com/57572400/158257255-ff6683d8-30b3-4613-a8b2-12c42ce64987.png">

**Comment by brandonkelly** [comment]
I wasn’t able to reproduce that exact behavior, but I did notice a couple other bugs with the View button/menu, which are now fixed. If you update to `4.0.x-dev` locally, does it resolve your issue?

**Comment by bencroker** [comment]
This turned out to be a CSS style added by the Adblock Plus extension for Firefox. Apparently it doesn't like `.share-btn` and gives it `display: none !important;`. Maybe changing that class name could prevent others from having the same issue, plus it is less descriptive now than it used to be.

**Comment by brandonkelly** [comment]
Aha… it used to be `#share-btn`, but swapped to a class name for Craft 4. Just renamed to `.view-btn` – can you see if that fixes it for you?

**Comment by bencroker** [comment]
That fixes it, thanks!

**Comment by brandonkelly** [comment]
Craft 4.0.0-beta.2 is out now with that change.
