### ISSUE TITLE
Nested asset subfolders disappear when dragging

### ISSUE THREAD

**Issue by gioppe** [craftcms/cms#10745]
### Description
When dragging a folder inside another folder all (or some) target folders in the sidebar disappear. This happens in desktop and mobile views. But, if the source folder is selected this issue does not occur. Tested on Chrome, Firefox both Mac and Windows.

### Additional info

- Craft version: 3.7.36

https://user-images.githubusercontent.com/1929797/158159762-0014d224-6bff-496c-a6e3-3005eb9111fe.mov

**Comment by brandonkelly** [comment]
It’s expected that dragging a folder would include any of its subfolders. What wasn’t expected here is that the selected subfolder (and any of its nested subfolders) would tag along for the drag-n-drop, even if it wasn’t the folder that was actually clicked on for the drag. That’s been fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.38 is out now with that fix.
