### ISSUE TITLE
Upgrading craftcms causes the cms system to load and save very slowly

### ISSUE THREAD

**Issue by dsfofwuc** [craftcms/cms#10759]
### Description
We upgraded from craftcms3.4 and craft-neo2.5.10 to craftcms3.7.30 and neo2.12.5 and found some problems. After the upgrade，but the craftcms page is very slow to load, save data is also very slow and save Entries 504 time out,We have set php.ini memory_limit=-1, max_execution_time=120.
### Steps to reproduce
1.upgrade craftcms
### Additional info

- Craft version:3.7.30
- PHP version:7.3.4
- Database driver & version:5.5.0+
- Plugins & versions:    "craftcms/aws-s3": "1.3.0",
    "craftcms/cms": "3.7.30",
    "craftcms/redactor": "2.10.2",
    "creativeorange/craft-article": "1.0.5.1",
    "fruitstudios/validateit": "1.0",
    "spicyweb/craft-neo": "2.12.5",
    "vlucas/phpdotenv": "3.4.0"

**Comment by brandonkelly** [comment]
Draft and revision creation is known to slow the entry editing experience down a bit – see the discussion at #9802. You can opt out of automatic draft creation by disabling the [autosaveDrafts](https://craftcms.com/docs/3.x/config/config-settings.html#autosavedrafts) config setting. And you can also consider disabling versioning from your sections’ settings, if it’s not necessary.

Good news is that both draft and revision creation are _much_ faster in Craft 4 (see #10577 + #10589). It’s currently in beta, and the first stable release will be in just a few weeks, on May 4.

**Comment by dsfofwuc** [comment]
@brandonkelly 
When saving the entry, 504 will appear in about 1 minute, and it will be refreshed and saved, which will affect our work efficiency; this has always been the case after I upgraded, and I have tried various php and nginx configurations. suggestion, thanks

**Comment by angrybrad** [comment]
@dsfofwuc If you want to write into support@craftcms.com, we can try to help you get past the 60-second timeout in your environment as a stop-gap until you're able to upgrade to Craft 4.

**Comment by dsfofwuc** [comment]
@angrybrad  Can you give me some ways online? The project is now online, it is very urgent, thank you

**Comment by brandonkelly** [comment]
@dsfofwuc It is going to depend on your environment. Please email support@craftcms.com.
