### ISSUE TITLE
4.0 Save Draft and Delete draft are shown even if canCreateDrafts is set to false for custom element type

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#10755]
i know we technically should have a draft and pass it to elements/edit to use unified element editing but i don't understand why when canCreateDrafts is set to false, end user still see 'delete draft' and 'save draft' action buttons.
actually i see a use case for delete draft - maybe as 'back to index page' to remove background draft quickly - buy i don't understand why there is save draft button action.

**Comment by brandonkelly** [comment]
`canCreateDrafts()` only dictates whether drafts can be _created_. If a draft already exists, then it’s up to `canSave()` / `canDelete()` as to whether the draft can be saved/deleted.

**Comment by vnali** [comment]
@brandonkelly currently if i want a user to create an element for an element types without draft and revision support, still that user sees 'delete draft' and 'save draft' actions,
what is the solution to hide these action buttons?

**Comment by brandonkelly** [comment]
@vnali Don’t create a draft in the first place.

**Comment by vnali** [comment]
@brandonkelly sorry for bothering you again. as you mentioned [here](https://github.com/craftcms/cms/pull/10467#issuecomment-1055778061), isn't creating a draft the only way to use unified element editing?
