### ISSUE TITLE
Uncaught SyntaxtError: Unexpected token ',' (draftId)

### ISSUE THREAD

**Issue by FrDH** [craftcms/cms#10750]
### Description
A JS error shows in the console when first saving an entry

![Screenshot 2022-03-15 at 11 53 15](https://user-images.githubusercontent.com/1387163/158366269-efa79974-fa8e-45b8-bfa9-a70b13ce502c.png)

### Steps to reproduce
Create a new entry and try to save (ctrl + S)

### Additional info

- Craft version: 3.7.30.1
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
This was fixed in Craft 3.7.31 (554542e5450).

**Comment by FrDH** [comment]
my apologies, i was under the impression craft was updated to the latest version, apparently it was funnen 3.7.30
