### ISSUE TITLE
Multi-site entries in multi-site structures can't be ordered independently per-site

### ISSUE THREAD

**Issue by timeverts** [craftcms/cms#10758]
### Description
I have a multi-site setup in Craft 3 where I have an entries structure (section) that exists on both sites. Some of the entries within the structure exist on both sites (i.e. are enabled for both sites), while others do not. I am trying to reorder some of those shared entries within the structure on one of the sites in relation to the non-shared entries. But each time I move them in the structure, this impacts the order of those shared entries in the structure on the other site too (usually moving them to the top or bottom of the other site's structure). What I would like to have is independent ordering of the entries within the structures of each site.

I would have thought the ordering of the entries in the structure would be maintained per-site and was surprised it was not, especially considering that the `siteId` is sent as a request param to the `StructuresController` actions. I can see now that the `structureelements` database table does not even store the `siteId` against each record, so per-site structure ordering is clearly not supported right now. So this might even be more relevant as a feature request.

### Additional info

- Craft version: 3.7.34
- PHP version: 8.1
- Database driver & version: mySQL 5.7
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
This is working as intended; Structure sections only have a single “structure” for their entries, regardless of which site(s) those entries exist in. It would be a pretty involved (and probably generally undesired) change to create additional structures for each site, but you are free to request it by [posting a new discussion about it](https://github.com/craftcms/cms/discussions/new?category=ideas).
