### ISSUE TITLE
[4.0.0-beta.2] "Related to" filter condition not working in entry index

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#10769]
### Description
When I select "related to" from the filtering UI in the entries index, the spinning loader comes up and I'm not able to select anything. Also the system becomes unresponsive and I have to restart my local server instance, so maybe some background job gets stuck?

Screen recording:
https://www.loom.com/share/438d6522787e41ae8584774c7eb12c6d

### Steps to reproduce

1. Create some entries
2. Go to the entries index
3.  Try to filter entries with a "related to" condition

### Additional info

- Craft version: 4.0.0-beta.2
- PHP version: 8.1.3
- Database driver & version: MySQL 8.0.23
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed now for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.0-beta.3 is out now with the fix.
