### ISSUE TITLE
Craft 4: `sources:` value of `[]` no longer works to specific all sources for `elementSelect`

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#10766]
### Description

So I was diagnosing why the Asset Selects in SEOmatic no longer work... here's the Twig:
```twig
                {{ forms.elementSelect({
                    id: "seoImageIds-" ~ random(),
                    name: "seoImageIds",
                    viewMode: "large",
                    elements: seoImageElement,
                    elementType: elementType,
                    criteria: {
                        kind: ["image"],
                    },
                    jsClass: 'Craft.AssetSelectInput',
                    selectionLabel: "Select SEO Image"|t("seomatic"),
                    sources: [],
                    limit: 1,
                    warning: false,
                    errors: metaBundleSettings.getErrors("seoImageIds"),
                }) }}
```

They just bring up an empty window with no assets listed:

https://user-images.githubusercontent.com/7570798/158685385-c5202dfb-f708-454b-a6a4-3d1fa122b66b.mov

What I found for values for `sources:` is:

Doesn't work: 
```php
                    sources: [],
```
Doesn't work: 
```php
                    sources: ['*'],
```
Works:
```php
                    sources: '*',
```
Works:
```php
                    sources: null,
```

So while I'm happy to fix that and change it to one of the values that works (which I already did)... it's also likely to break for a bunch of other people too, so could consider allowing `[]` to be set to `null` or such

### Steps to reproduce

See above

### Additional info

- Craft version: 4.0.0-beta.1
- PHP version: 8.0.13
- Database driver & version: n/a
- Plugins & versions: Mostly n/a but SEOmatic 4.0.0-beta.4

**Comment by brandonkelly** [comment]
This is working as intended. Craft 3 was just not sending `[]` to the server because the form was getting serialized and sent as HTTP query data – so it was effectively the same as not setting `sources` at all. Whereas now we send a JSON request body, so `[]` gets passed.
