### ISSUE TITLE
Usability issues with drag & drop on Field Layout Designer

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#1076]
> Created by: Timothy Kelty (timkelty@gmail.com) on 2015/04/02 12:33:05 +0000
> Votes at time of UserVoice import: 4

-----------------------------------

Dragging a field to the top through a scrolling page can be a challenge when you have many fields and field groups.

**Comment by brandonkelly** [comment]
Closing due to similar issue, even though this one came first. (#1076)

**Comment by brandonkelly** [comment]
For posterity, this is resolved in 5.6.0 via #16374 🎉
