### ISSUE TITLE
[4.x]: Labels/fields are getting stuck on drag and cannot be removed.

### ISSUE THREAD

**Issue by yellostudio** [craftcms/cms#10778]
### Steps to reproduce

When adding fields to tabs and dragging them away trying to remove them they get stuck on the screen where you release the mouse.

### Expected behaviour

I am trying to remove labels e.t.c from the tabs.

### Craft CMS version

Craft CMS 4.0.0-beta.1

### PHP version

8

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
I’m not able to reproduce. Try updating to 4.0.0-beta.3. If you’re still experiencing it, check to see if you’re getting any JavaScript errors on the page.

**Comment by ttempleton** [comment]
I'm seeing this happen when trying to remove UI elements that already existed on the tab when the page loaded. The JavaScript error is:

```
Uncaught TypeError: can't access property "type", this.$draggee.data(...) is undefined
    onDragStop FieldLayoutDesigner.js:1058
    e Base.js:69
    stopDragging BaseDrag.js:162
    stopDragging Drag.js:185
    e Base.js:69
    _handleMouseUp BaseDrag.js:386
    addListener Base.js:146
    jQuery 3
FieldLayoutDesigner.js:1058:87
```

**Comment by brandonkelly** [comment]
@ttempleton Can you please send a DB backup + composer files to support@craftcms.com, and point me to where that error is occurring?

**Comment by codebarista** [comment]
Same here after a fresh install v3 latest and composer update to 4.0.0-beta.4. Unlike UI Elements, Fields can be removed.

<img width="720" alt="Craft-UI-Elements-TypeError" src="https://user-images.githubusercontent.com/19738505/163724658-5172bcfd-94cc-4d25-9a7f-d81a7396d450.png">

Application Info
PHP version	8.1.4
OS version	Linux 5.10.104-linuxkit
Database driver & version	MySQL 10.5.15
Image driver & version	Imagick 3.7.0 (ImageMagick 7.1.0-16)
Craft edition & version	Craft Pro 4.0.0-beta.4
Yii version	2.0.45
Twig version	v3.3.10
Guzzle version	7.4.2

**Comment by brandonkelly** [comment]
Sorry, I missed that this was happening for UI elements. Able to reproduce now, and I’ve fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with this fix.
