### ISSUE TITLE
[4.0.0-beta.2] Issues with condition builder

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#10772]
### Description

Can confirm #10769.

In addition:

1.) If you select an entries field in the condition builder and choose `is related to` it does not show a possibility to select a related element:

![image](https://user-images.githubusercontent.com/60010597/158776044-d0a49236-455a-42c0-acff-451b9a4f4be0.png)

Error in Ajax call:

`craft\base\conditions\BaseElementSelectConditionRule::setElementId(): Argument #1 ($elementId) must be of type string|int, null given, called in E:\craft\craft4_beta\vendor\yiisoft\yii2\base\Component.php on line 180`

Fun fact:

Choose another relational field while 'related to' is still selected and the 'Choose' button appears and works. 

2.)

Select 'Entry Type' and select a section: The second dropdown (entry type) is not refreshed.

`Trying to access array offset on value of type null  in E:\craft\craft4_beta\vendor\craftcms\cms\src\controllers\ConditionsController.phpat line 36`

3.)

Bug or expected? Relational fields have `has a value / is empty` options, but i miss those on plain text/number etc field types. Would be great to have those for improving content quality.

### Additional info

- Craft version: 4.0.x-dev 84bb08d
- PHP version: 8.0.15
- Database driver & version:
- Plugins & versions: none

**Comment by brandonkelly** [comment]
This has been fixed for the next release. (36913f3367fa616ccec4e7c914b933322ab32b68)

**Comment by simonkuran** [comment]
Has item 3.) on the list above been addressed?

> Bug or expected? Relational fields have `has a value / is empty` options, but i miss those on plain text/number etc field types. Would be great to have those for improving content quality.

I'm running v4.0.3 and I don't have `has a value` or `is empty` options for plain text fields. This would be extremely useful.

**Comment by brandonkelly** [comment]
@simonkuran See #11070 for an existing feature request for that.
