### ISSUE TITLE
[4.0.0-beta.2] Breadcrumb link for current section broken in entry edit screen

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#10770]
### Description
The current section breadcrumb link in the entry edit screen uses the **section name** instead of the **section handle**, so the link leads to a "template not found" screen.

### Steps to reproduce

1. Create a section, let's say with the name `My section` and handle `mySection`
2. Create an entry in this section and go edit that entry.
3. The full breadcrumbs are like so: `Entries > My section` . Observe that the breadcrumb `My section` has a link url with `My section` as the last segment. It should be `mySection`. (e.g `https://mysite.test/diax/entries/My%20section` instead of `https://mysite.test/diax/entries/mySection`)

### Additional info

- Craft version: 4.0.0-beta.2
- PHP version: 8.1.3
- Database driver & version: MySQL 8.0.23
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.0-beta.3 is out now with the fix.
