### ISSUE TITLE
Unaccessible color-picker in field type table

### ISSUE THREAD

**Issue by vebjorn** [craftcms/cms#10775]
### Description
Column-type "Color-picker" in Field Type "Table" isn't clickable.
The input for storing the HEX-value has a left-padding which overlays the input type color (picker)

![Skjermbilde 2022-03-17 kl  14 15 14](https://user-images.githubusercontent.com/4727251/158817228-e19ce734-d79e-4334-891f-9e4c23596d7d.png)

### Steps to reproduce

1. Create a field with the table field type
2. Set one of the columns to type "Color"
3. Try to click on the color-picker

A higher z-index on the input type color would fix the problem in its entirety

### Additional info

- Craft version: 3.7.37
- PHP version: 7.4.25
- Database driver & version: MySQL 5.5.5
- Plugins & versions: -

**Comment by Mathias-Syversen** [comment]
+1

**Comment by brandonkelly** [comment]
Thanks for reporting! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.38 is out now with the fix for this. Thanks again!
