### ISSUE TITLE
[4.0.0-beta.2] Slideout editor closes on field change

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#10771]
### Description
When I open the slideout editor to edit an entry, the first time I change a field without saving and I click outside the slideout, there is a warning `Are you sure you want to close this screen? Any changes will be lost.`.

- I'm not sure if that warning should be there, since there is a provisional draft.
- When I open the same entry slideout editor, and I make a change to any field, the changes are saved to the provisional draft, and the **editor closes by itself**

### Steps to reproduce

1. Open a slideout editor for an entry.
2. Make some changes to trigger a provisional draft but **dont' save**. Instead close the editor by clicking outside.
3. Re-open the editor and make a further change on any field.
4. The editor closes by itself.

### Additional info

- Craft version: 4.0.0-beta.2
- PHP version: 8.1.3
- Database driver & version: MySQL 8.0.23
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting that! I’d seen the page roload unexpectedly when editing an element, but assumed it was related to HMR.

**Comment by brandonkelly** [comment]
Craft 4.0.0-beta.3 is out now with the fix.
