### ISSUE TITLE
Required lightswitch fields for a user are not validated

### ISSUE THREAD

**Issue by handplant** [craftcms/cms#10773]
### Description

Required lightswitch fields for a user are not validated.

![screenshot](https://user-images.githubusercontent.com/2598962/158787103-eca13a73-dbfd-4f1c-abf4-1156547fa707.png)

### Steps to reproduce

1. Create a lightswitch field
2. Attach it to userfields (/admin/settings/users/fields) and make it required
3. Edit a user and save

### Additional info

- Craft version: Craft Pro 3.7.36
- PHP version: 7.4.23
- Database driver & version: MySQL 8.0.26
- Plugins & versions: -

**Comment by brandonkelly** [comment]
Lightswitch fields really shouldn’t have been requirable to begin with, since there’s no way to submit them without a value (on or off).

I’ve just removed the “Required” setting from Lightswitch fields within field layout designers, for the next Craft 4 Beta release.

**Comment by Mosnar** [comment]
> Lightswitch fields really shouldn’t have been requirable to begin with, since there’s no way to submit them without a value (on or off).
> 
> I’ve just removed the “Required” setting from Lightswitch fields within field layout designers, for the next Craft 4 Beta release. ([ab70e6a](https://github.com/craftcms/cms/commit/ab70e6a0326b54e91ddeea2df173e6aac4e23e69))

I agree with your assessment, but with that in mind, what is the suggested approach for checking if a "compliance"-style lightswitch field is checked on a frontend form? A custom validator, as outlined in the docs [here](https://craftcms.com/docs/3.x/extend/extending-system-components.html#custom-validation-rules)? It's a very common use-case, so it might be worth specifically documenting.

**Comment by brandonkelly** [comment]
@Mosnar Yeah a custom validator would do the trick. Eventually we will start venturing into content governance, at which point I could see it being possible to define a custom validation rule for this, within the control panel.

**Comment by brandonkelly** [comment]
Craft 4.0.0-beta.4 is out now with that change.
