### ISSUE TITLE
[4.x]: Category draft preview error

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#10788]
Previewing a fresh category draft results in a 404 error.

<img width="950" alt="Screenshot 2022-03-20 at 09 31 15" src="https://user-images.githubusercontent.com/57572400/159156313-d4733f6e-cd14-4391-9020-058265062669.png">

### Steps to reproduce

1. Create a category group with a URI format (`category/{slug}` above) and template.
2. Create a new category.
3. Before saving, click on "Preview".

### Craft CMS version

4.0.0-beta.2

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.0-beta.3 is out now with the fix.
