### ISSUE TITLE
[4.x]: Title field missing in condition builder

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#10785]
### What happened?

The `Title` field appears to be missing in the condition builder, when adding a filter, adding a custom source, and everywhere else I've seen it. I assume this is unintentional, since adding conditions on an element's title seems like a common use-case.

<img width="716" alt="Screenshot 2022-03-19 at 09 48 38" src="https://user-images.githubusercontent.com/57572400/159116382-2187efd3-7284-476a-b29f-2500828a0f2b.png">

### Craft CMS version

4.0.0-beta.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for pointing that out! We overlooked that one. Added in 4.0.0-beta.3.
