### ISSUE TITLE
[4.x]: Checking for updates on beta doesnt work

### ISSUE THREAD

**Issue by yellostudio** [craftcms/cms#10780]
### Description

When checking for updates to beta on the craft 4 beta, the circle whirls around constantly "Checking for updates…"

### Steps to reproduce

1.

### Craft CMS version

Craft CMS 4.0.0-beta.1

### PHP version

8

### Installed plugins and versions

-

**Comment by piotrpog** [comment]
I had this problem with beta 1, but it seems to be gone in beta 2.

**Comment by brandonkelly** [comment]
Yep this was fixed in Beta 2 (61a937420eed5cf02cef8439a79ff50cfa110a1f).
