### ISSUE TITLE
[3.x]: Global sets are not deleted via project config

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#10798]
### Steps to reproduce

1. Delete a global set in dev environment and confirm that its YAML file got deleted
2. Deploy changes to staging environment
3. Run `php craft project-config/apply`
4. As step 3 didn’t remove the global set, try to run `php craft project-config/apply --force`

### Expected behavior

Global sets get deleted via project config changes.

### Actual behavior

Global sets are not deleted via project config changes.

### Craft CMS version

3.7.37

### PHP version

7.4.28

### Database type and version

MySQL 5.7.37

**Comment by andris-sevcenko** [comment]
I was unable to reproduce this locally.

1) What's the output when you run `./craft project-config/apply`? 
2) What happens when you run `./craft project-config/apply --force`

**Comment by carlcs** [comment]
@andris-sevcenko I’m sorry! Now that you say that, I’m thinking it is an issue with our deployment. I’ll have to check if we’re using the delete flag with rsync.
