### ISSUE TITLE
[4.x]: Javascript error on deleting users in overview page

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#10793]
### Description
When trying to remove a user from the Users overview we are getting a javascript error on [this line](https://github.com/craftcms/cms/blob/4.0/src/elements/actions/DeleteUsers.php#L106) because `id` is undefined. Looks like it should be `ids` instead of `id`

### Craft CMS version

4.0.0-beta.2

### PHP version

8.0.14

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.0-beta.3 is out now with the fix.
