### ISSUE TITLE
[4.x]: Strict typing error in `redactIfSensitive `

### ISSUE THREAD

**Issue by mattgrayisok** [craftcms/cms#10792]
### Description

During a site migration from latest 3 to 4.0.0-beta.2 I'm seeing the following:

```
[2022-03-21T12:44:13.733214+00:00] web.WARNING: Unable to send log via yii\debug\LogTarget: Exception 'TypeError' with message 'craft\services\Security::redactIfSensitive(): Return value must be of type array|string, null returned' 

in /var/www/html/vendor/craftcms/cms/src/services/Security.php:190

Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/services/Security.php(184): craft\services\Security->redactIfSensitive('route', NULL)
#1 /var/www/html/vendor/craftcms/cms/src/debug/RequestPanel.php(26): craft\services\Security->redactIfSensitive('', Array)
#2 /var/www/html/vendor/yiisoft/yii2-debug/src/LogTarget.php(61): craft\debug\RequestPanel->save()
#3 /var/www/html/vendor/yiisoft/yii2-debug/src/LogTarget.php(136): yii\debug\LogTarget->export()
#4 /var/www/html/vendor/yiisoft/yii2/log/Dispatcher.php(194): yii\debug\LogTarget->collect(Array, true)
#5 /var/www/html/vendor/yiisoft/yii2/log/Logger.php(226): yii\log\Dispatcher->dispatch(Array, true)
#6 /var/www/html/vendor/yiisoft/yii2/base/ErrorHandler.php(137): yii\log\Logger->flush(true)
#7 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(63): yii\base\ErrorHandler->handleException(Object(craft\web\ServiceUnavailableHttpException))
```

From what I can see, an array is being passed into the Log which has `['route' => null]`. This is passed to `redactIfSensitive`. The  `null` doesn't match against either of the `if()`s inside `redactIfSensitive` so it's dropping through to `return $value;` which then doesn't match the return constraint `array|string` throwing the Exception.

### Steps to reproduce

1. Try to `Craft::error(['something' => null])`

### Expected behavior

In `redactIfSensitive`, either the input param `mixed $value` needs to be stricter, the output `array|string` needs to be looser, or everything needs coercing into a string before returning. 

### Craft CMS version

4.0.0-beta.2

### PHP version

8.1.2

### Operating system and version

Alpine3.15

### Installed plugins and versions

-

**Comment by mattgrayisok** [comment]
It looks like this might be complicated a bit more by the strict typing here too:

https://github.com/craftcms/cms/blob/30bb0c60a76c2072cf372674dcf42697de1af9c1/src/debug/RequestPanel.php#L26

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release.
