### ISSUE TITLE
[4.0.0-beta.2]: Entry not enabled when created inside module

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#10796]
### Description
When you create an entry within a module or plugin by doing it like [this](https://docs.craftcms.com/api/v4/craft-services-elements.html#method-saveelement), the entry shows up enabled in the cp, but now post date is set on the entry by default. Because in the [beforeValidate](https://github.com/craftcms/cms/blob/4.0/src/elements/Entry.php#L1816) function the `$this->scenario = "default"` so the function to set the post date is skipped. When you now want to query for the entry this entry, it isn't returning by default, unless you query with `->status(null)` 

### Craft CMS version

4.0.0-beta.2

### PHP version

8.0.14

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just widened that check to include the `default` scenario as well, for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.0-beta.3 is out now with that change.
