### ISSUE TITLE
[4.x]: Image preview in CP displays transformed image

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#10802]
### Description
When previewing an image in the CP, the source of the image is set to a resized version of the original (with the default compression applied? not sure), so some details and overall quality are harder to judge for image critical applications. As far as I can tell, this behaviour differs from Craft 3, where the preview modal displays the original image. I'm not sure if this is (or should be) expected.

If this is on purpose there should be, in my opinion, an easy way to inspect the original file (for now, one can copy the url and paste it in a new window).

### Steps to reproduce

1. Upload an image in the assets page.
2. Preview the image.
3. Inspect the source, or open the image in a new tab. Observe that it's a transformed/resized version.

### Expected behavior
Editors should be able to inspect the original image

### Actual behavior
The CP preview displays a compressed and resized version of the original

### Craft CMS version

4.0.0 - beta.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
There’s always been a max size that the image editor wants to load the asset in, however Craft 4 was transforming the image to that size regardless of whether it was smaller or larger. Just fixed that for the next release.

**Comment by thupsi** [comment]
Is there however a config setting for this max size? It seems to be different from Craft 3 because the same image that remained intact is being transformed to a smaller size than the original in Craft 4.

**Comment by brandonkelly** [comment]
It hasn’t changed in Craft 4 – it’s based on the viewport size.

**Comment by brandonkelly** [comment]
Craft 4.0.0-beta.4 is out now with that fix.
