### ISSUE TITLE
Use a specific template for Live Preview

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#1080]
> Created by: MattP (mattpavid@gmail.com) on 2016/01/11 18:32:18 +0000
> Votes at time of UserVoice import: 4

-----------------------------------

Would like to be able to configure a specific (or multiple) templates for use in Live Preview. 

Use cases may vary - ours involves being able to render an entry 'surrounded' by mobile phone hardware thereby giving the client/content admin a good idea of what it would look like 'in-hand'

Completely appreciate that mobile responsive templates will cater for 90% of this, but asking a client to resize their browser is a step too far for some. 

Happy to discuss and develop the idea...

**Comment by carlcs** [comment]
@miralize that's not true, you can't get LIve Preview to work without enabling "Entires have a URL" in section settings.

**Comment by brandonkelly** [comment]
Closing this because #1489 makes a better case for the same general idea.
