### ISSUE TITLE
[4.x]: Matrix block order not maintained on Save

### ISSUE THREAD

**Issue by mattstein** [craftcms/cms#10803]
### Description

When I reorder Matrix blocks without changing their content, that order is maintained for the provisional draft but reverted (or discarded?) when I choose **Save**:

https://user-images.githubusercontent.com/2488775/159741317-8095d371-05fb-4829-93bd-8e38b878f7e0.mp4

This works as expected when I change the value in each field—it’s only an issue when I don’t make any changes to the Matrix fields but reorder the blocks.

### Steps to reproduce

1. Pick an entry that has several Matrix blocks and change their order.
2. While _“Showing your unsaved changes.”_ is present, refresh the page or navigate elsewhere and come back. Observe that the order from step 1 is maintained.
3. Now press **Save** or <kbd>⌘</kbd> + <kbd>S</kbd>. Observe that the Matrix block order has reverted to whatever it was prior to step 1.

### Expected behavior

Order I establish is maintained as long as Craft is storing my changes.

### Actual behavior

Order is maintained _until_ I press **Save**.

### Craft CMS version

4.0.0-beta.3

### PHP version

8.0.15

### Operating system and version

macOS 12.3

### Database type and version

MySQL 8.0.26

### Image driver and version

Imagick 3.6.0

### Installed plugins and versions

No plugins are enabled.

**Comment by ademers** [comment]
I've noticed the same issue.

**Comment by mattstein** [comment]
Full credit to @ademers for discovering the issue, I just swooped in and GitHubbed it. 🙂

**Comment by brandonkelly** [comment]
Fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 4.0.0-beta.4 is out now with that fix.
