### ISSUE TITLE
[4.x]: Cannot see uploaded image assets, error in Asset editing screen.

### ISSUE THREAD

**Issue by mauricioarangoosorio** [craftcms/cms#10809]
### Description
I can upload image assets. However it is not possible to preview them anywhere in the CP, and when I try to see the added image in `Assets > Uploads > Default > entry_name`  an error screen shows up.

### Steps to reproduce

1. Create a file system location
2. create a asset field and add it to an entry
3. create a new entry and upload an image

### Expected behavior
1. The image is added to the location indicated on your field settings (this is working, I can see the image in the indicated directory)
2. The image thumb should show up in the editing screen and other places in the CP
3. I should be able to access the images from the CP's Assets menu

### Actual behavior

1. There isn't any thumb preview of the uploaded image. Instead a blank rectangle shows up. Even though, I can see the created thumbnails in the uploads directory
2. When I try to access the image from `Assets > Uploads > Default > entry_name` I get the following error:
```
An Error occurred while handling another error:
Error: Typed property craft\events\AssetPreviewEvent::$previewHandler must not be accessed before initialization in /app/vendor/craftcms/cms/src/services/Assets.php:884
```
![Screen Shot 2022-03-23 at 6 41 54 PM](https://user-images.githubusercontent.com/41710299/159820310-2c44b006-f7b3-4c97-95c4-6d8cedb52b76.jpg)

### Craft CMS version

4.0.0-beta.3

### PHP version

8.1.3

### Operating system and version

Macos 11.5.2

### Database type and version

mysql-8.0

### Installed plugins and versions

-  "craftcms/redactor": "3.0.0-beta.1",
- "spatie/craft-ray": "2.0",

**Comment by andris-sevcenko** [comment]
Thanks! Just fixed it for the next release!

**Comment by mauricioarangoosorio** [comment]
Awesome! Thank you so much!!

___________________________

**Comment by brandonkelly** [comment]
Craft 4.0.0-beta.4 is out now with that fix.

**Comment by moesyzlack8** [comment]
PHP Version =  8.0.21
OS Version =  Linux 5.10.109-0-virt
Database driver & version =  MySql 10.4.25
Image driver & version =  Imagick 3.6.0 (ImageMagick 6.9.11-60)
Craft edition & version = Craft Solo 4.2.3
Yii version = 2.0.45
Twig version = v3.3.10
Guzzle version = 7.5.0

This is still happening for me, how do i fix this?

**Comment by moesyzlack8** [comment]
> @moesyzlack8 Most likely there’s an issue with your filesystem’s URL setting.

the .env file:

PRIMARY_SITE_URL=https://wpcoleman.ddev.site/
ASSET_BASE_URL=https://wpcoleman.ddev.site/web/uploads
ASSET_BASE_PATH=/var/www/html/web/uploads

**Comment by DarioDiGiacomo** [comment]
Have the same problem, i've been working with Wampserver for setting up an localhost

![image](https://github.com/craftcms/cms/assets/114081282/3a429c62-5961-4d12-aed8-580e61215ad6)

The local url is based on the web folder of the project, so maybe i've to change something in the  URL or PATH but idk

**Comment by brandonkelly** [comment]
@DarioDiGiacomo Neither of those are valid URLs. They should either be root-relative:

```sh
PRIMARY_SITE_URL=/
ASSET_BASE_URL=/uploads
```

Or absolute:

```sh
PRIMARY_SITE_URL=https://schoonbeekBeverst.craftcms.be/
ASSET_BASE_URL=https://schoonbeekBeverst.craftcms.be/uploads
```
