### ISSUE TITLE
[4.x]: Infinity spinner next to Category field

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#10801]
### Steps to reproduce

1. Fresh install of Craft 4 beta 3.
2. Create a Category Group
3. Add a category to it.
4. Create a section, add a Category field to the field layout.
5. Add an entry to the section.
6. Notice the permanent spinner next to the field.

![CleanShot 2022-03-22 at 12 49 15](https://user-images.githubusercontent.com/61869/159564720-47f60178-812d-4572-ac82-40286e031fe4.gif)

There are no JS errors in the console. Only seems to happen on Category field - tested Entry field and did not experience it.

### Expected behavior

No Infinity spinner.

### Actual behavior

Infinity spinner.

### Craft CMS version

4.0.0 beta 3

### PHP version

8.1

### Operating system and version

macOS

### Database type and version

MySQL 8

### Image driver and version

n/a

### Installed plugins and versions

None.

**Comment by brandonkelly** [comment]
Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.0-beta.4 is out now with this fix.
