### ISSUE TITLE
[4.x]: Empty Money field value gets marked as changed

### ISSUE THREAD

**Issue by mattstein** [craftcms/cms#10804]
### Description

When I’ve got an empty Money field in a Matrix block and I reorder the blocks, that Money field gets visual treatment that indicates it’s changed even though I didn’t touch its value:

https://user-images.githubusercontent.com/2488775/159745093-bf8d6f2e-6d17-4444-b390-396bb2c5ed19.mp4

Its Plain Text peers (in this case) don’t behave like that; empty and reordered != changed:

https://user-images.githubusercontent.com/2488775/159745849-33d04dfa-995c-483d-a56f-6e400daa1e8a.mp4

Matrix doesn’t have anything to do with it though. I can add a Money field directly to the entry field layout, and changing any one thing will have the same result:

https://user-images.githubusercontent.com/2488775/159746501-826721a8-34ab-4b06-9716-bb73519357aa.mp4

I regret that I could not think of a dirty money joke to work in here.

### Steps to reproduce

1. Add a Money field to any field layout.
2. Create and save a new entry with that field layout, leaving the Money field empty.
3. Edit any field _other than_ that empty Money field so that “Showing your unsaved changes.” appears.
4. Observe that the Money field indicates its value has changed. 

### Expected behavior

I would expect the Money field to indicate its value has changed when its value has changed.

### Actual behavior

The Money field indicates its value has changed when _anything else_ in its field layout has changed—even if it remains empty.

### Craft CMS version

4.0.0-beta.3

### PHP version

8.0.15

### Operating system and version

macOS 12.3

### Database type and version

MySQL 8.0.26

### Image driver and version

Imagick 3.6.0

### Installed plugins and versions

No plugins are enabled.

**Comment by nfourtythree** [comment]
@mattstein @brandonkelly This behaviour looks like it is consistent with some other field types (Number and Date Time). Not that I am saying it is the correct behaviour but those three are all similar to each other, so maybe there is some underlying issue?


https://user-images.githubusercontent.com/266453/166420714-bc13341b-79dd-414a-aeb6-997959de50b9.mp4

**Comment by brandonkelly** [comment]
Yeah ok, this ended up being the culprit:

https://github.com/craftcms/cms/blob/fb4e04ff1ee8d08279ec2598ae55e15480b2a6b5/src/templates/_includes/field.twig#L17-L19

That’s there for things like Dropdown fields, which will have a value in the form right on page load, even if the field doesn’t have a stored value, so we don’t forgot to include its value in the delta submission.

Date, Number, and Money fields are now explicitly overriding their initial delta values based on what the actual initial input values will be when empty, which fixes this.

I think at some point (probably Craft 5) we should ditch JS-based delta save support, in favor of back-end field value comparisons. Field types themselves should be the ones deciding whether it looks like the posted data has changed compared to its existing value; not the JS.

**Comment by brandonkelly** [comment]
3.7.40 + 4.0.0-RC3 are out now with these fixes.
