### ISSUE TITLE
[3.x]: `useEmailAsUsername` causes duplicate errors with public registration if email already taken

### ISSUE THREAD

**Issue by iamkeir** [craftcms/cms#10805]
### Description

If you set `useEmailAsUsername` to `true` in Craft config and try to complete a public registration with an email address that is already taken, you receive a duplicate error. I am assuming this is because it is validating the username, followed by the email, rather treating them as one.

<img width="469" alt="screenshot_182" src="https://user-images.githubusercontent.com/539615/159781579-0a311c33-bb4e-45d8-839b-4240cf338f4b.png">

### Steps to reproduce

1. Set `useEmailAsUsername` to `true` in config
2. Create a public registration form with error output in Twig (using `name="email"` field, not username field) 
3. Attempt to register with an email address already taken in Craft users
4. Observe duplicate errors

### Temporary workaround

FWIW we have worked around it for now with the following:
```
{% for error in errors if error != current_error ?? null %}  
  <li>{{ error }}</li>
  {% set current_error = error %}
{% endfor %}
```

### Craft CMS version

Craft Pro 3.7.37

### PHP version

8.0.8

### Installed plugins and versions

-

**Comment by iamkeir** [comment]
This _might_ be due to having a site that used usernames, and then later switched to `useEmailAsUsername`, where existing usernames do not get overwritten by the email address - possibly a different bug entirely in that case.

**Comment by iamkeir** [comment]
No, I take that back, if you unset `useEmailAsUsername`, and update the old username to match the email, you get even more duplication: <img width="411" alt="screenshot_191" src="https://user-images.githubusercontent.com/539615/160014015-bc79d7af-b42a-4245-8f55-b17e66c43c84.png">

(The redacted text all equal the same email address)

**Comment by brandonkelly** [comment]
`useEmailAsUsername` will just copy the `email` value over to `username`, so it’s expected you‘d get two separate validation errors.

> This _might_ be due to having a site that used usernames, and then later switched to `useEmailAsUsername`, where existing usernames do not get overwritten by the email address - possibly a different bug entirely in that case.

After enabling that setting, you should run the following command so that existing usernames are overwritten with users’ emails:

```php
php craft utils/update-usernames
```

> No, I take that back, if you unset `useEmailAsUsername`, and update the old username to match the email, you get even more duplication:

That additional error is coming from the `unverifiedEmail` attribute.

You can work around both of these by only fetching errors for the specific attributes you care about:

```twig
{% set errors = user.getErrors(['email', 'newPassword']) %}
```

**Comment by iamkeir** [comment]
> `{% set errors = user.getErrors(['email', 'newPassword']) %}`

For benefit of others, I have not had success with this - it returns `TypeError - Illegal offset type in isset or empty`. 

If I output `user.getErrors`, I get:
```
array(2) {
  ["email"]=>
  array(1) {
    [0]=>
    string(22) "Email cannot be blank."
  }
  ["username"]=>
  array(1) {
    [0]=>
    string(25) "Username cannot be blank."
  }
}
```
So instead I've used `| filter((v, k) => k != 'username')` as per https://stackoverflow.com/a/58901053/923785

**Comment by brandonkelly** [comment]
@iamkeir Where does it show that that error is coming from? (Enable Dev Mode if it’s not already enabled.)

**Comment by iamkeir** [comment]
@brandonkelly 

```
TypeError: Illegal offset type in isset or empty in /Users/iamkeir/Sites/tsg/build/craft/vendor/yiisoft/yii2/base/Model.php:589
Stack trace:
#0 /Users/iamkeir/Sites/tsg/build/craft/vendor/twig/twig/src/Extension/CoreExtension.php(1566): yii\base\Model->getErrors(Array)
#1 /Users/iamkeir/Sites/tsg/build/craft/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\User), 'getErrors', Array, 'method', false, false)
#2 /Users/iamkeir/Sites/tsg/build/craft/storage/runtime/compiled_templates/81/8138a69e4d112ea2117844fc11521c189dcd40a48272bb17c78eba1b581b604c.php(49): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\User), 'getErrors', Array, 'method')
#3 /Users/iamkeir/Sites/tsg/build/craft/vendor/twig/twig/src/Template.php(405): __TwigTemplate_40c4bc928199d869d044a3e7d3d86e3ccbc183dcd9b0e0d6774fc989a23276fd->doDisplay(Array, Array)
#4 /Users/iamkeir/Sites/tsg/build/craft/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#5 /Users/iamkeir/Sites/tsg/build/craft/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#6 /Users/iamkeir/Sites/tsg/build/craft/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#7 /Users/iamkeir/Sites/tsg/build/craft/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#8 /Users/iamkeir/Sites/tsg/build/craft/vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render('_accounts/regis...', Array)
#9 /Users/iamkeir/Sites/tsg/build/craft/vendor/craftcms/cms/src/web/View.php(461): craft\web\View->renderTemplate('_accounts/regis...', Array)
#10 /Users/iamkeir/Sites/tsg/build/craft/vendor/craftcms/cms/src/web/Controller.php(201): craft\web\View->renderPageTemplate('_accounts/regis...', Array, 'site')
#11 /Users/iamkeir/Sites/tsg/build/craft/vendor/craftcms/cms/src/controllers/TemplatesController.php(102): craft\web\Controller->renderTemplate('_accounts/regis...', Array)
#12 [internal function]: craft\controllers\TemplatesController->actionRender('_accounts/regis...', Array)
#13 /Users/iamkeir/Sites/tsg/build/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /Users/iamkeir/Sites/tsg/build/craft/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#15 /Users/iamkeir/Sites/tsg/build/craft/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('render', Array)
#16 /Users/iamkeir/Sites/tsg/build/craft/vendor/craftcms/cms/src/web/Application.php(293): yii\base\Module->runAction('templates/rende...', Array)
#17 /Users/iamkeir/Sites/tsg/build/craft/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#18 /Users/iamkeir/Sites/tsg/build/craft/vendor/craftcms/cms/src/web/Application.php(278): yii\web\Application->handleRequest(Object(craft\web\Request))
#19 /Users/iamkeir/Sites/tsg/build/craft/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 /Users/iamkeir/Sites/tsg/build/public_html/index.php(26): yii\base\Application->run()
#21 {main}
```

**Comment by iamkeir** [comment]
@brandonkelly btw, I tried running `php craft utils/update-usernames` but received `Exception 'craft\errors\SiteNotFoundException' with message 'No primary site exists'` which is odd as I do have a primary site set in the admin. Any ideas? Can create a new issue if preferred.

**Comment by brandonkelly** [comment]
@iamkeir Do you mind sending your database backup, Composer files, and template files that we can use to reproduce each of these errors, into support@craftcms.com?

**Comment by iamkeir** [comment]
@brandonkelly sure thing, I'll see what I can do.
