### ISSUE TITLE
[4.x]: 'Uncaught TypeError: this.$addElementBtn is undefined' on entry page with tag field

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#10814]
### What happened?

**Description**
after fixing wrong types reported in [this issue](https://github.com/craftcms/cms/issues/10808) manually, still there is an console error on entry page with tag field, preventing tag field to work:
`'Uncaught TypeError: this.$addElementBtn is undefined'`
[related to this line ](https://github.com/craftcms/cms/blob/f1fef63615ff55e026a4a489980389eddda377c9/src/web/assets/cp/src/js/BaseElementSelectInput.js#L164)

### Craft CMS version

4.0.x-beta3

**Comment by brandonkelly** [comment]
Thanks for reporting! This is now fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.0-beta.4 is out now with that fix.
