### ISSUE TITLE
[3.x]: Eager loading leads to deprecation warnings

### ISSUE THREAD

**Issue by MetaDevelopment** [craftcms/cms#10815]
### Description
When eager-loading a field with multiple items (for example an assets field with multiple images) and then looping through that eager-loaded field, you should not use ".all()" since the field is now an array. However, this generates the following depreciation warning: 
**"Looping through element queries directly has been deprecated. Use the all() function to fetch the query results before looping over them."**
When using ".all()" as instructed in the warning, the code throws an error as expected (**"Impossible to invoke a method ("all") on an array."**). 

### Steps to reproduce

1. Eager-load a field with multiple elements (assets or matrix blocks) 
2. Loop through that eager-loaded field that is now an array 
3. Check the Depreciation Warnings

### Expected behavior

No Depreciation Warning is generated. 

### Actual behavior

A Depreciation Warning is generated. 

### Craft CMS version

3.7.37

### PHP version

7.4.15

### Operating system and version

Darwin 20.5.0

### Database type and version

MySQL 5.7.12

### Image driver and version

Imagick 3.4.4 (ImageMagick 7.0.11-1)

### Installed plugins and versions

N/A

**Comment by brandonkelly** [comment]
Thanks! I’d already fixed this for Craft 4, but really should have fixed in Craft 3. Didn’t think about the deprecation errors.

**Comment by brandonkelly** [comment]
Craft 3.7.38 is out now with the fix for this.
