### ISSUE TITLE
[4.0.0-beta.3]: Categories are missing their parent select button

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#10819]
### Steps to reproduce

1. Install Craft 4 beta 3.
2. Create Category Group
3. Add Category
4. Notice there is no way to select the parent (picture is from Craft 3.7)

![CleanShot 2022-03-24 at 16 27 14@2x](https://user-images.githubusercontent.com/61869/160026302-97771a19-2789-43ee-8f6f-c1ea66524c5b.png)

You can still drag/drop to change the hierarchy/order from the Category index page.

### Craft CMS version

4.0.0-beta.3

### PHP version

8.0

### Operating system and version

n/a

### Database type and version

n/a

### Image driver and version

n/a

### Installed plugins and versions

n/a

**Comment by brandonkelly** [comment]
Craft 4.0.0-beta.4 is out now a fix for this (f778fcd3b4a5d854fb0fea7fc4be338e65b4ac7a).
