### ISSUE TITLE
[4.x]: Autosave removes conditional field (?)

### ISSUE THREAD

**Issue by mauricioarangoosorio** [craftcms/cms#10816]
### Description

When editing an entry with versioning enabled, sometimes the fields are cleared and reverted to the last saved version, loosing all the unsaved information. I've only seen this on a page with conditions enabled for the field.

### Steps to reproduce

1. Create an entry type with multiple fields. Add some conditions for the displaying of those fields.
2. Make sure autosaveDrafts and versioning are on
3. create a new entry, do not save, make sure you meet the condition to display the fields is met. Then click on the conditional field.

### Expected behavior

Fields should be left untouched

### Actual behavior

When I click on the conditional field, all the conditional fields are removed.

### Craft CMS version

Craft Solo 4.0.0-beta.3

### PHP version

8.1.3

### Operating system and version

Linux 5.10.76-linuxkit

### Database type and version

MySQL 8.0.26

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-16)

### Installed plugins and versions

- spatie/craft-ray
- craftcms/redactor

**Comment by brandonkelly** [comment]
This is generally working on my end. Can you please send in a database backup and your Composer files to support@craftcms.com, and point out some specific steps to reproduce on your install? We can look into it from there.

**Comment by mauricioarangoosorio** [comment]
Thank you. This happened to me for 2 days in a row. But I haven’t been able to reproduce the issue today. I’ll keep an eye on it, and if I see it happening once again I’ll reach out with all the details.

Mauricio

**Comment by mauricioarangoosorio** [comment]
Hi, I was able to consistently reproduce the issue. I emailed the files to @support, and added a video illustrating how it happens. Thanks!

**Comment by brandonkelly** [comment]
Thanks for the help @mauricioarangoosorio! We just got this fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with this fix.

**Comment by mauricioarangoosorio** [comment]
I was able to recreate the issue again. I’m sending you an email with more details.
