### ISSUE TITLE
[3.7.37]: Deprecation warning on Graphql matrix mutation

### ISSUE THREAD

**Issue by pnpaes** [craftcms/cms#10811]
### What happened?

I have a mutation for an entry and that mutation is adding new matrix element to my matrix field.
But then I get this in the deprecation warnings:

`
28 - Deprecation error: The id field will be required when mutating Matrix fields as of Craft 4.0.Called from /var/www/html/vendor/craftcms/cms/src/gql/types/input/Matrix.php:131
`

The problem is that this is a new matrix item, not an updated one. So there is no existing ID that can be used.
In the sortOrder i use an array with ["new:1", "new:2", ...]

Sample:
`"orderedProducts" => ["sortOrder" => ["new:1", "new:2"], "blocks" => [["lineItem" => ["product" => [8688], "quantity" => 5]], ["lineItem" => ["product" => [8698], "quantity" => 15]]]]`

Will this become an issue when craft 4 is released? If yes, how can I achieve the same result?

### Craft CMS version

3.7.37

### PHP version

8.0.1

### Operating system and version

Linux 5.10.76-linuxkit

### Database type and version

MySQL 5.5.5

### Image driver and version

Imagick 3.4.4 (ImageMagick 6.9.10-23)

### Installed plugins and versions

DigitalOcean Spaces Volume 1.1.3
Feed Me 4.4.1.1
Jason 2.0.1
Redactor 2.10.5
Super Table 2.7.1

**Comment by andris-sevcenko** [comment]
@pnpaes you should be setting the `id` fields on the new blocks, too - use the same `new:x` format for new blocks.

This ensures that the order is deliberate and does not rely on "the first block defined will probably be `new:1`"
