### ISSUE TITLE
[4.x]: Asset Location upload path

### ISSUE THREAD

**Issue by mauricioarangoosorio** [craftcms/cms#10828]
### Description
This might be a mistake on my end ... but, for what is worth:

I'm creating a generic asset location field that I plan on using for different types of entries. If a set a dynamic path for the **Asset Location** input, Craft ignores some of the twig commands

### Steps to reproduce

1. Create a new Assets field
2. Enter any of the following paths:
a. `{owner.slug}} ?? 'Default'`
b. `{owner.slug}} ?? ':Default:'`
c. `{owner.slug}} | default('Default')`
d. `{{ {owner.slug}} ?? 'Default' }}`

### Expected behavior
A. If if am uploading **1.jpg** to an structure type entry with the slug **project**, I was hoping to get the file added to this location: 
`project/1.jpg`

B. If I add **1.jpg** to a Global group
`Default/1.jpg`

### Actual behavior
For each of the options described in 'Steps to reproduce', I get:
A. When adding **1.jpg** to the **project** entry
a. `project-Default/1.jpg`
b. `project-Default/1.jpg`
c. `project-defaultDefault/1.jpg`
d. The entry page doesn't load, and I get this error: 
``` 
An Error occurred while handling another error:
Twig\Error\SyntaxError: Unexpected "}" in "__string_template__e2bb06f694a1c1bc686ab706b6aa8f77" at line 1. in /app/vendor/twig/twig/src/Lexer.php:338
```

B. When adding **1.jpg** to the field in the Global group:
a. `Default/1.jpg`
b. `Default/1.jpg`
c. `defaultDefault/1.jpg`
d. I get this error:
```
Twig Syntax Error – [Twig\Error\SyntaxError](http://twig.sensiolabs.org/api/2.x/Twig/Error/SyntaxError.html)
Unexpected "}" in "__string_template__e2bb06f694a1c1bc686ab706b6aa8f77" at line 1.
```

### Craft CMS version

4.0.0-beta.3

### PHP version

8.1.3

### Operating system and version

Linux 5.10.76-linuxkit

### Database type and version

MySQL 8.0.26

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-16)

### Installed plugins and versions

- Ray | 2.0
- Redactor 3.0.0-beta.1

**Comment by brandonkelly** [comment]
> * Enter any of the following paths:
>   a. `{owner.slug}} ?? 'Default'`
>   b. `{owner.slug}} ?? ':Default:'`
>   c. `{owner.slug}} | default('Default')`
>   d. `{{ {owner.slug}} ?? 'Default' }}`

None of those are valid syntax. Do one of these instead:

```twig
{{ owner.slug ?? 'Default' }}
{{ owner.slug ?? ':Default:' }}
```
