### ISSUE TITLE
Add permission for managing Commerce settings

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1082]
> Created by: Timothy Kelty (timkelty@gmail.com) on 2015/04/02 12:33:05 +0000
> Votes at time of UserVoice import: 3

-----------------------------------

Currently you have to be an admin.

I've had a couple situations where I wanted to grant clients access to manage commerce settings, but not be full admins.

**Comment by Coalescent** [comment]
Add me to this... the exact same scenario - client needs to be able to edit Tax and Shipping Rates.

**Comment by smockensturm** [comment]
Please. This is quite a shock after we go to great pains in setting up client user groups permissions, all for naught. There are many, many settings here that are best configured by a client, not a developer.

**Comment by brandonkelly** [comment]
This belongs in the Craft Commerce feedback forum. And looks like @smockensturm already posted the FR there: https://craftcms.uservoice.com/forums/295386-commerce/suggestions/32822248-open-settings-to-user-groups
