### ISSUE TITLE
[4.x]: Editing an exisiting image transform or creating a new one causes an error

### ISSUE THREAD

**Issue by mauricioarangoosorio** [craftcms/cms#10826]
### Description

I tried to change the exiting height of an image transform, this generated an error

### Steps to reproduce
1. Edit an existing image transform or create a new one. Then click save.

### Expected behavior
Confirmation of the change or creation of a new image transform.

### Actual behavior

I get this error:
```
Unknown Property – [yii\base\UnknownPropertyException](http://www.yiiframework.com/doc-2.0/yii-base-unknownpropertyexception.html)
Setting unknown property: craft\events\ImageTransformEvent::assetTransform
```

### Craft CMS version

Craft Solo 4.0.0-beta.3

### PHP version

8.1.3

### Operating system and version

Linux 5.10.76-linuxkit

### Database type and version

MySQL 8.0.26

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-16)

### Installed plugins and versions

- Ray | 2.0  
- Redactor | 3.0.0 - beta 1

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by mauricioarangoosorio** [comment]
Awesome, thank you!

**Comment by brandonkelly** [comment]
Craft 4.0.0-beta.4 is out now with that fix.
