### ISSUE TITLE
[3.x]: Disabled entry not giving status

### ISSUE THREAD

**Issue by katiasmet** [craftcms/cms#10833]
### Description
I think the status of an entry is not available when you connect the entry to another one.

### Steps to reproduce

1. Create a new entry of type A fe. 'pages'
2. Create a new entry of type B fe. 'posts'
3. Connect a post to a page with an entries field. 
4. Disable the post / Edit the status of the post
5. Go to the graphql playground and try to get the status of the post within a page query. The status is still live even though the 'dot' is not coloured green. It looks like the status is not right. 

<img width="273" alt="Screenshot 2022-03-28 at 16 38 34" src="https://user-images.githubusercontent.com/5981440/160422976-cdbb2f4e-c324-4964-ae4a-c8ca377b4933.png">

Json output from graphql
```
{
  "data": {
    "route": [
      {
        "poi": [
          {
            "id": "5",
            "title": "[TEST] Begijnhof",
            "status": "live",
            "enabled": true,
            "isDraft": false,
            "isUnpublishedDraft": false,
            "isUnsavedDraft": false,
            "isRevision": false,
            "trashed": false
          },
          {
            "id": "285",
            "title": "[TEST] Begijnhof - kopie",
            "status": "live",
            "enabled": true,
            "isDraft": false,
            "isUnpublishedDraft": false,
            "isUnsavedDraft": false,
            "isRevision": false,
            "trashed": false
          }
        ]
      }
    ]
  }
}
```

### Expected behavior
The status or the 'enabled' value should be false. 

### Actual behavior
The status of the 'enabled' is true. And status is live. 

### Craft CMS version

3.7.37

### PHP version

8.0.16

### Operating system and version

Linux 4.19.0-17-amd64

### Database type and version

PostgreSQL 13.6

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-16)

### Installed plugins and versions

 "craftcms/cms": "3.7.37",
"craftcms/redactor": "2.10.5",
"ether/simplemap": "3.9.3",
"vaersaagod/dospaces": "1.1.3",

**Comment by brandonkelly** [comment]
If this is a multi-site install, it may only be disabled for the current site, but still enabled globally. Try outputting its `enabledForSite` property in GraphQL.
