### ISSUE TITLE
[4.x]: Unable to add rows to a Table field

### ISSUE THREAD

**Issue by superextinct** [craftcms/cms#10835]
### Description
Table fields are currently not being shown in the entry editor:

![Bildschirmfoto 2022-03-29 um 11 59 01](https://user-images.githubusercontent.com/41620375/160587585-1be6bacb-4068-4c9c-af3b-e7a2989e2787.png)

The table itself has a `hidden` class applied to it, upon removal you can see the header columns:

![Bildschirmfoto 2022-03-29 um 11 59 50](https://user-images.githubusercontent.com/41620375/160587727-2743ac8a-2633-4077-9d48-d288fa00b243.png)

The table's default rows and the button to add a row are however not parsed. Believe this has to do with https://github.com/craftcms/cms/pull/10163 as this PR conditionally renders the Add-Button depending on `allowAdd` (which is not an option during field creation). 

### Steps to reproduce

1. Create a new table field
2. Add newly created field to a section
3. Edit an entry of said section

### Expected behavior

See table headers, row values and button to add a new row. 

### Actual behavior

Only the field's label is being shown.

### Craft CMS version

Craft Solo 4.0.0-beta.3

### PHP version

8.1.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.0-beta.4 is out now with that fix.
