### ISSUE TITLE
[4.x]: Deprecation not logged in Variable method

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#10840]
### Description

I just ported [Site Switcher](https://plugins.craftcms.com/site-switcher) over to Craft 4, and deprecated the ability to use a Variable.

**EXAMPLE** - Linking to the Spanish version of your Entry...

```twig
{# Using the Twig Extension (GOOD, MODERN) #}
{{ siteSwitcher('spanish', entry) }}

{# Using the Variable (OLD, DEPRECATED) #}
{{ craft.siteSwitcher.url('spanish', entry) }}
```

However, that deprecation message does not get logged normally...

https://github.com/doublesecretagency/craft-siteswitcher/blob/v2-dev/src/variables/SiteSwitcherVariable.php#L36

Strangely, the site still throws a hard deprecation error when the site is in "hard mode"...

```php
// config/app.php
'components' => [
    // Throw hard errors on deprecation warnings
    'deprecator' => ['throwExceptions' => YII_DEBUG]
]
```

✅ Throws hard errors in "hard mode".
❌ Doesn't log deprecation message normally.

### Steps to reproduce

1. Install Site Switcher (for Craft 4).
2. Use the deprecated `craft.siteSwitcher.url` Variable.
3. Notice that the deprecation message isn't logged. 🤔 
4. Activate "hard mode".
5. Notice that the deprecation message is (correctly) thrown as an error.

### Expected behavior

A [deprecation message](https://github.com/doublesecretagency/craft-siteswitcher/blob/v2-dev/src/variables/SiteSwitcherVariable.php#L36) should be logged when the `craft.siteSwitcher.url` Variable is used.

### Actual behavior

Nothing happens (unless you activate "hard mode").

### Craft CMS version

4.0.0-beta.3

### PHP version

8.0.16

**Comment by lindseydiloreto** [comment]
Just tested this in a Twig Extension, and got the same behavior...

❌ Doesn't log deprecation messages normally.
✅ Throws deprecation message in "hard mode".

It seems this issue extends beyond just Variables (and probably beyond Twig Extensions).

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by lindseydiloreto** [comment]
Sweet, thanks @brandonkelly! 👍

**Comment by brandonkelly** [comment]
Craft 4.0.0-beta.4 is out now with that fix.
