### ISSUE TITLE
Allow searching by ID

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1084]
> Created by: Timothy Kelty (timkelty@gmail.com) on 2015/04/02 12:33:05 +0000
> Votes at time of UserVoice import: 3

-----------------------------------

There is currently no way to search by ID.
Using "field searching", e.g. id::"123" doesn't work either.

http://craftcms.stackexchange.com/questions/17433/search-by-id-in-the-cp

**Comment by terryupton** [comment]
Is this planned for anytime soon?

**Comment by brandonkelly** [comment]
Yes, actually, it’s in the works :)

**Comment by espensgr** [comment]
Any progress on this? i'm having this request from some of our costumers as well
