### ISSUE TITLE
[3.x]: Table field with a lot of columns overflows from page + performance issues in craft when editing the field settings

### ISSUE THREAD

**Issue by mikesnoeren** [craftcms/cms#10849]
### Description
I recently needed a table field with a lot of columns (20+) and noticed that a table this size isn't displayed properly. 

When editing an entry the table overflows to the right, without the ability to scroll to it so I can't fill the last columns, nor delete or reorder rows. The table field will also overlap the right hand panel containing the entry slug and post date etc. Making it unable to change those too.

When editing the field itself (settings -> fields -> table field) something similar is happening, however, that's not all: there's a performance issue that makes editing the field really, really slow. When I write a column name, add a new column or remove a column it can take upwards to 10 seconds for my changes to appear on the screen.

### Steps to reproduce
1. Create a table field with a lot of rows
2. Add the field to a section and create an entry for that section
3. Notice how it doesn't fit.

### Expected behavior
One of the below:
- Make the table itself responsive, by allowing users to scroll within the table.
- Make the page itself scrollable, so the user defined fields are within their own container which allows horizontal scrolling when needed. (This would fix more issues, I have seen matrix fields overflowing too)

### Craft CMS version

3.7.37

### PHP version

8.1.4

### Operating system and version

Linux 5.10.47-linuxkit

### Database type and version

MySQL 8.0.19

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- Express Forms 1.1.2
- Field Manager 2.2.4
- Kint 1.0.0
- Redactor 2.10.5
- SEO 3.7.4
- Super Table 2.7.1

**Comment by mikesnoeren** [comment]
I haven't checked if this issue has been fixed in Craft 4, and unfortunately don't have the time to do so..
So this might, or might not, have to be fixed for both versions.

**Comment by thupsi** [comment]
Can confirm that I have some overflowing table fields on mobile, so even with not so many columns this can be an issue.

**Comment by brandonkelly** [comment]
Fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 3.7.38 is out now with that fix.
