### ISSUE TITLE
[3.x]: RelatedTo links to relations not on the current site

### ISSUE THREAD

**Issue by DanielDarrenJones** [craftcms/cms#10847]
### Description
If you have a multi-site install and a translatable field that lets you select a category then, when you try to use a relatedTo query to get all of the entries or products for a category it will match any relations across all of the sites.

For example if you have an entry on two sites and on "Site 1" it's linked to "Category A" and on "Site 2" it's linked to "Category B" the relatedTo query will return the entry for either category on both sites.

### Steps to reproduce

1. Create multi-site craft install
2. Create field to link to a category
3. Make field translatable
4. Create two categories
5. Create an entry which is shared across both installs
6. On your first site link the entry to one category
7. On the second site link the entry to the other category
8. Perform a relatedTo query `productsQuery.relatedTo(category)`

### Expected behavior
Should only return entry for the relations set on the current site.

### Actual behavior
Returns relations across all sites.

### Craft CMS version

Craft CMS 3.7.34

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
You can lock the `relatedTo` param down to a single site via the `sourceSite` criteria.

```twig
{% set products = productsQuery.relatedTo({
    targetElement: category,
    sourceSite: currentSite.id
}) %}
```
