### ISSUE TITLE
[4.x]: Project Config apply fails due to 'Undefined array key "section"' error

### ISSUE THREAD

**Issue by cweiper** [craftcms/cms#10855]
### Description
The _project-config/apply_ command simply fails with the error "Undefined array key 'section'".

### Steps to reproduce

1. Change project config in development environment via control panel, no issues.
2. Commit changes to project config to repo
3. Deploy changes onto production server
4. Run _project-config/apply_

### Expected behavior
System should successfully apply project config changes

### Actual behavior
The process fails due to an error. Trying to run _utils/repair/project-config_ does not help and neither does attempting to rebuild the project config

### Craft CMS version

4.0.0-beta.1

### PHP version

8.1.0

### Operating system and version

Linux x86_64 GNU/Linux

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 4.0.0-beta.4 is out now with that fix.
