### ISSUE TITLE
[3.x]: craft.users.email(null).one() returns the first user

### ISSUE THREAD

**Issue by pixelmachine** [craftcms/cms#10859]
### What happened?

Calling `craft.users.email(null).one()` returns the first user in the system which is I assume is unintentional and can result in unexpected behaviour.

For example from the Commerce example templates:
```
{% set userExists = craft.users.email(cart.email).one() %}
```
This will always be true even if there is no `cart.email` yet and would return the wrong user's name if `{{ userExists }}` is displayed.

### Craft CMS version

Latest

**Comment by brandonkelly** [comment]
This is working as expected – the default `email` param value is `null`, so calling `email(null)` has no effect.

We’ll update the Commerce example templates. Thanks for pointing that out.

**Comment by lukeholder** [comment]
@pixelmachine 

The latest example templates redirect the user if there is no email present on the cart just before the line OP posted:

```
{% if not cart.email %}
  {% redirect 'shop/checkout/email' %}
{% endif %}
```

Thus preventing the issue you are seeing.

Having said that, I have also gone ahead and modified the query in our examples to ensure no user is returned with this technique:

```twig
{% set user = craft.users.email(cart.email ?? 'NULL').one() %}
```

Passing string `NULL` (which no user could have) will force no user being returned.

Hope that helps.

**Comment by pixelmachine** [comment]
@brandonkelly I still think it's unintuitive, isn't it? 

User 1 is called "Admin":
```php
{{ craft.users.email(cart.email).one() }} -> "Admin" // where cart.email == null
{{ craft.users.email('').one() }} -> "Admin" // empty string
{{ craft.users.email('NotAnEmailAddress').one() }}` -> "" // non-matching string*
```
*Luke used the string `"NULL"` as a dirty workaround it but that could be confused for a real `null` value.

I think I would generally err on the side of caution and not output a user's name if that user hasn't been specifically targeted.

**Comment by brandonkelly** [comment]
All the user query knows is that you’re passing in an empty value to `email()`, which is telling it “I don’t want you to filter based on the email address”. It has no way of knowing how the value was generated, or that you were _expecting_ a value to be passed in.
