### ISSUE TITLE
[4.x]:  User group, User field layout not updated when applying project config

### ISSUE THREAD

**Issue by aodihis** [craftcms/cms#10865]
### Description
I have set the user field layout and user group, then when I want to applying this on another pc from fresh install db of craft 4,   the user field layout, and user group not get updated. But after that process if I manually change something in the project yaml file like change the tab name then do apply changes again, the user field is applied.

This work fine on craft 3.

### Steps to reproduce

1. Create the user group and add some field in user field.
2. Save them all.
3. The project yaml will changes.
4. Drop our current database and use fresh install database.
5. Do the project config apply.
6. The config finish, but the user field and user group is not showing as expected.
7. Try to update manually the project yaml file for the user field and user group, example change the title both for user field and user group.
8. Do the project config apply again.
9. Now the user field and user showing correctly.

### Expected behavior
in step `#6` should be the user field and group is showing.

### Actual behavior
In step `#6` the user field and user group there is no changes, even if we do touch project-config to update the dateModified, look there is no changes.

### Craft CMS version

4.0.0-beta-3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. I’ve tried with a fresh Craft install using project config YAML that contains a user group and a couple custom fields added to the user layout, and all were present once the installer was finished.

I’ve also tried applying incoming YAML changes that adds a new user group and adds a couple user custom fields, and that was applied successfully as well.

If you are able to reliably reproduce this, can you please send your Composer files and `config/project/` folder into support@craftcms.com?

**Comment by aodihis** [comment]
@brandonkelly, sure Thank you.

**Comment by andris-sevcenko** [comment]
Thank you for reporting this - fixed for the next release!

There was an issue with project config where it might skip over some additions _if_ the same parent key also had changes. This is only an issue for Craft 4, though.

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with this fix.
