### ISSUE TITLE
[4.x]: Numeric environment variables missing from autosuggest field options

### ISSUE THREAD

**Issue by mattstein** [craftcms/cms#10873]
### Description

It looks like environment variables having numeric values aren’t suggested in Craft 4’s autosuggest field. Tested here with SMTP port after @ademers raised the issue [in Discord](https://discord.com/channels/456442477667418113/456442867163070466/961314613453004820), but I’m seeing the same behavior in other random environment-variable-friendly fields I’ve tried.

Tested in Craft 3.7.37 and can confirm this is only an issue in Craft 4.

### Steps to reproduce

1. Add two new new environment variables to your project’s `.env`:
    ```
    MY_TEST_STRING="foobar"
    MY_TEST_NUMBER="12345"
    ```
2. In the control panel, navigate to **Settings**  → **Email**.
3. For **Transport Type**, select “SMTP”.
4. Click on the **Port** field and type “MY_TEST_”. 
5. Observe that `$MY_TEST_STRING` is included in the suggestions, but `$MY_TEST_NUMBER` is not.
6. Edit `.env` with `MY_TEST_NUMBER="baz"`.
7. Refresh the page and repeat step 4, and observe now that both `$MY_TEST_STRING` and `$MY_TEST_NUMBER` are included in the suggestions.

**BONUS STEP!**
Repeat using Craft 3 and observe that `$MY_TEST_STRING` and `$MY_TEST_NUMBER` are suggested no matter what value they have.

### Expected behavior

Both environment variables would be suggested as they are in Craft 3. (Or only the numeric one since we’re looking for a port number here.)

### Actual behavior

The environment variable with the numeric value is ignored and not available as a suggestion.

### Craft CMS version

4.0.0-beta.3

### PHP version

8.0.15

### Operating system and version

macOS 12.3.1

### Database type and version

MySQL 8.0.26

**Comment by brandonkelly** [comment]
Fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with this fix.
