### ISSUE TITLE
[3.x]: Required custom fields are not validated during frontend user registration

### ISSUE THREAD

**Issue by goraxan** [craftcms/cms#10870]
### Description
A user with required custom fields can be registered in a frontend form without filling them.
I think this is because the `skipOnEmpty` attribute from the `yii\validators\Validator` is set as true by default, so the `yii\validators\RequiredValidator` is not triggered during a frontend user registration. If you try to edit an existing user from the CP, the `skipOnEmpty` flag is set to false and it forces you to fill it.

Why is this happening?

### Steps to reproduce

1. Create a custom field, attach it to the user element and mark it as required.
2. Create a registration form and submit a request without filling the required custom field.

### Expected behavior
An error from the user validator should be thrown telling the user to fill in the required field.

### Actual behavior
The user can be registrated without entering required fields

### Craft CMS version

3.7.37

### PHP version

7.4.16

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
This is the intended default behavior:

https://github.com/craftcms/cms/blob/1bcf1e9170f0024b888251dd204958989aca296b/src/controllers/UsersController.php#L1242-L1245

If you want full validation on public registration, go to **Settings** → **Users** → **Settings**, and tick the “Validate custom fields on public registration” checkbox.

<img width="513" alt="Screenshot of the “Validate custom fields on public registration” user setting" src="https://user-images.githubusercontent.com/47792/162036647-4baa3966-9201-438f-b6e4-20e12825d65d.png">

**Comment by goraxan** [comment]
You're right, thanks! And sorry for not seeing this.

**Comment by brandonkelly** [comment]
No worries!
