### ISSUE TITLE
[3.7.37]: Config YAML deleted the content after adding 1 field

### ISSUE THREAD

**Issue by Radu033** [craftcms/cms#10876]
### Description
I have added 1 field to my local env in a super table, uploaded the config to the server, run the new changes ( no errors appeared) went to the entries, and got an internal server error, checked the fields on the server and they were completly empty, reuploaded the config, run YAML again and I got all the fields + the new one but the old content is all gone, and when I check the revisions it is saying "No Blocks" 

### Steps to reproduce

1. change field locally
2. upload config to server
3. The content is gone

### Expected behavior
The old content should remain

### Actual behavior
The old content got deleted.

### Craft CMS version

3.7.37

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Yikes. First thing’s first—do you have a recent database backup you can restore, to get your content back? Most hosts will create backups automatically on a schedule, even if you don’t have one you created yourself.

It sounds like Craft may have completely deleted your custom fields in the first YAML apply, which would end up deleting their content as well, which unfortunately is a permanent change, so the only way to get the content back would be with a database backup.

Besides that, we can help look into what went wrong exactly, if you send us a database backup from before the first YAML apply, as well as the Composer files and new YAML files that were deployed when things went wrong. You can send those to support@craftcms.com.

**Comment by Radu033** [comment]
Hey @brandonkelly  thanks for the quick reply.

There should be a recent backup as our server backups MySql daily, the problem is that this is a website under development, and the content that was added to it during the day might get deleted if I restore the backup. I will try to SSH to the server and look for a backup.

We are using the CraftCMS for some years now and for over 30 clients of ours and never had this issue in the past, this is very weird. 

Now the content department realised that some global fields are also empty even though my only change was to add 1 new field in for a specific section.

**Comment by brandonkelly** [comment]
Yeah something must not have gone right. We really need that backup + Composer files + incoming `config/project/` folder to diagnose, though.
