### ISSUE TITLE
[3.x]: Matrix blocks sharing field handles only return data for first created block for multi-column fields

### ISSUE THREAD

**Issue by Tam** [craftcms/cms#10884]
### Description
If a matrix block is created with two block types and those blocks share multi-column fields that have the same handle, only the data in the first created matrix block (regardless of type) will be returned when saved. The data is saved to the database correctly.

### Steps to reproduce

1. Create a matrix field
2. Add a block type with a date field, enable timezones.
3. Add another block type, again with a date field as above, giving it the same name and handle.
4. Add the field to a section
5. Create an entry in that section and add content to the matrix field using both block types.
6. Save
7. View the saved entry.

### Expected behavior

The data should be returned for both fields in both matrix blocks.

### Actual behavior

Only the data saved in the first created matrix block is returned.

### Craft CMS version

3.7.38

### PHP version

8.1.3

### Operating system and version

Linux 5.10.104-linuxkit

### Database type and version

MySQL 8.0.28

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-16)

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-release/3.7.39 as 3.7.38"` and run `composer update`.

**Comment by brandonkelly** [comment]
Just released 3.7.39 with the fix for this.
