### ISSUE TITLE
[3.x]: Overflow or z-index issue with matrix settings popup

### ISSUE THREAD

**Issue by mikesnoeren** [craftcms/cms#10883]
### Description
When having a matrix field at the top of your entry the menu will 'overflow' below the top of the page. This issue is in the cms since this commit: e968965e42daf46bc8c4e592b6a1428eb9eebe8f. This commit solved this issue: #10849

I'm guessing it's a simple z-index issue, but has quite high priority as the inaccessible settings are used quite a lot.

Screenshot of the issue:
![this popup does not work](https://user-images.githubusercontent.com/52166423/162411278-b64ded5d-36a0-4f6e-ba71-31b3f9e2e1c3.png)

When adding a block the popup works fine:
![this popup works](https://user-images.githubusercontent.com/52166423/162411171-73d64fbf-8aa4-4c22-ab7f-232fe968ce01.png)

### Steps to reproduce

1. Add a matrix field with a bunch of types in the top of an section.
2. Create entry within section.
3. Press the settings icon on the matrix field

### Craft CMS version

3.7.38

**Comment by brandonkelly** [comment]
Just released 3.7.39 with the fix for this.
