### ISSUE TITLE
[3.x]: ElementQueryInterface title method does not return exact match

### ISSUE THREAD

**Issue by joepagan** [craftcms/cms#10891]
### Description

Hey, am I missing something on this query? 

I am trying to search for a category name `Couches, Plinths & Treatment Chairs`, however a category with the title of `Couches` is returned and I don't think it should be because the `title` method on [ElementQueryInterface](https://docs.craftcms.com/api/v3/craft-elements-db-elementqueryinterface.html#method-title) looks to use an exact match unless an asterisk character is used which it is not here.

```php
$category = Category::find()
          ->title($categoryTitle)
          ->groupId($categoryGroupId)
          ->descendantOf($parentCategoryId)
          ->descendantDist($parentCategoryId ? 1 : null)
          ->one();
```

Here is my editor on a request with xdebug showing the variable values I describe:

<img width="969" alt="image" src="https://user-images.githubusercontent.com/2337910/162484720-a7af6816-38a5-4e9e-9ed6-5d7d4ae93e7e.png">

### Steps to reproduce

1. use above query

### Expected behavior

`$category` should equal `null` as there is no matching category currently.

### Actual behavior

`$category` is returned as a Category element with a title of `Couches`.

### Craft CMS version

3.7.32

### PHP version

8.0

### Operating system and version

alpine

### Database type and version

maria10

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
`title()` interprets values with commas arrays, e.g. `['Couches', 'Plinths & Treatment Chairs']`. You can disable this feature by passing the value through [`craft\helpers\Db::escapeParam()`](https://docs.craftcms.com/api/v3/craft-helpers-db.html#method-escapeparam):

```php
$category = Category::find()
          ->title(\craft\helpers\Db::escapeParam($categoryTitle))
          ->groupId($categoryGroupId)
          ->descendantOf($parentCategoryId)
          ->descendantDist($parentCategoryId ? 1 : null)
          ->one();
```

(The same can be done within a template using the [`|literal`](https://craftcms.com/docs/3.x/dev/filters.html#literal) filter.)

**Comment by joepagan** [comment]
Thanks for the explanation missed the arguments for `string[]`. 
I think it would be helpful and more clear to at least reference this behaviour on the table of examples for `title()` https://docs.craftcms.com/api/v3/craft-elements-db-elementqueryinterface.html#method-title

**Comment by brandonkelly** [comment]
Yeah that’s fair. It happens via `craft\helpers\Db::parseParam()`, which is where support for all of those additional param syntaxes comes from (`Foo*`, `not *Foo*`, etc.). The vast majority of params that use that method aren’t working with values that allow commas in the first place, so it’s reasonable to interpret values with commas as arrays.

I’ve just gone ahead and started escaping commas by default for `title` for Craft 4 though, as well as `firstName` and `lastName` for user queries, as those technically also allow commas. (It’s a breaking change so I don’t want  to make it before Craft 4.)

**Comment by joepagan** [comment]
Cheers for getting back, yeah appreciate that it could break a lot of people's apps if it was to change so that's reasonable to do it that way. I'll do my best to remember that in any future craft4 apps I work with.

I would appreciate a change to [the docs to reference the `escapeParam` requirement](https://docs.craftcms.com/api/v3/craft-elements-db-elementqueryinterface.html#method-title) where appropriate as suggesting a string is ok in your docs is still confusing imo.

**Comment by brandonkelly** [comment]
@joepagan Yeah good call. I’ve added a warning, which will show up when the next release goes out.
