### ISSUE TITLE
[4.x]: server error on disabling/deleting sources on some conditions

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#10899]
### What happened?

 **Description**

- disabling all sources causes server error:

https://user-images.githubusercontent.com/55586085/162763599-44078bc4-dfcf-47d1-98f6-250756300241.mp4

- disabling/removing on some conditions causes server error for example: deleting a custom source then without saving disabling entry type source and then save causes error even though there is 'all entries' source available

https://user-images.githubusercontent.com/55586085/162764324-e307c8f3-1f26-4652-a8e3-fc713d1d2055.mp4

### Craft CMS version

4.0.x-dev

### Installed plugins and versions

fresh install

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with this fix.
