### ISSUE TITLE
[4.x]: UFO abducts database backup dump

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#10901]
### Description

Due to a logic error using the UFO operator, database backups are deleted immediately if you have > `$generalConfig->maxBackups` existing backups.

In Craft 3, the comparison was:

```php
            // Sort them by file modified time descending (newest first).
            usort($files, static function($a, $b) {
                return filemtime($a) < filemtime($b);
            });
```
ref: https://github.com/craftcms/cms/blob/develop/src/db/Connection.php#L300

In Craft 4, someone has gotten jiggy with the UFO operator `<=>`:

```php
            // Sort them by file modified time descending (newest first).
            usort($files, static function($a, $b) {
                return filemtime($a) <=> filemtime($b);
            });
```

ref: https://github.com/craftcms/cms/blob/4.0/src/db/Connection.php#L272

So whereas before the anonymous function would return `1` if `filemtime($a) < filemtime($b)` it will now return `-1` in the same situation, using the [UFO operator](https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.spaceship-op)... causing the resulting file list to be sorted by the opposite of what was intended, _ascending_ (oldest first) order.

This results in the following lines immediately deleting the new backup, causing it to throw an error.
```php
            if (count($files) >= $generalConfig->maxBackups) {
                $backupsToDelete = array_slice($files, $generalConfig->maxBackups);

                foreach ($backupsToDelete as $backupToDelete) {
                    FileHelper::unlink($backupToDelete);
                }
            }
```

Looks like it could be a victim of PHPstan: https://github.com/craftcms/cms/commit/0e30a8ff93d501afa98d64031200edb2c307160d#diff-61f94e4b1825f1dc2ece99a882e0787dbd2a0ebe311fcb4b75ca865b6e1d0002R272

### Steps to reproduce

1. Have at least `$generalConfig->maxBackups` backups in place
2. Issue a backup command

### Expected behavior

The database would be backed up properly

### Actual behavior

The database gets backed up, but then is immediately deleted, so an error is thrown

### Craft CMS version

4.0.0-beta.4

### PHP version

8.0.11

### Operating system and version

macOS Monterrey 12.3.1 (21E258)

### Database type and version

n/a

### Image driver and version

n/a

### Installed plugins and versions

n/a

**Comment by brandonkelly** [comment]
Doh… missed the `descending (newest first)` part of the comment right there. Fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with this fix.
