### ISSUE TITLE
[4.x]: Duplicate key when saving user's volumes permissions

### ISSUE THREAD

**Issue by JeanLucEsser** [craftcms/cms#10909]
### Description

On user permission, for assets volumes, "Save assets uploaded by other users" option is listed twice.
It generates a duplicate key database error (Integrity constraint violation) when saving.

Only way around it for now is to not select either one of the listed option for "Save assets uploaded by other users".

### Craft CMS version

4.0 beta 4 latest dev

### Database type and version

MariaDB

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with this fix.
