### ISSUE TITLE
[4.x]: Default dev mode logging configuration should at least have a max file size

### ISSUE THREAD

**Issue by tremby** [craftcms/cms#10903]
### Description

In my opinion the default logging configuration is not reasonable. I've only been working on this new site, in local dev mode only, for a few days and my logs directory was over 11 gigabytes.

```
$ ls -lh storage/logs
total 11G
-rw-r--r-- 1 bjn bjn 490K Apr  5 18:02 console-2022-04-06.log
-rw-r--r-- 1 bjn bjn 142K Apr 11 15:36 phperrors.log
-rw-r--r-- 1 bjn bjn  26M Apr  5 19:49 queue-2022-04-06.log
-rw-r--r-- 1 bjn bjn 5.8M Apr  7 16:42 queue-2022-04-07.log
-rw-r--r-- 1 bjn bjn  78M Apr  8 13:54 queue-2022-04-08.log
-rw-r--r-- 1 bjn bjn  62M Apr 11 15:36 queue-2022-04-11.log
-rw-r--r-- 1 bjn bjn 1.8G Apr  7 16:58 web-2022-04-07.log
-rw-r--r-- 1 bjn bjn 3.5G Apr  8 16:59 web-2022-04-08.log
-rw-r--r-- 1 bjn bjn 1.5G Apr  9 16:59 web-2022-04-09.log
-rw-r--r-- 1 bjn bjn 1.5G Apr 10 16:59 web-2022-04-10.log
-rw-r--r-- 1 bjn bjn 2.7G Apr 11 15:38 web-2022-04-11.log
```

Multi-gigabyte log files with only one user within a few days? I ran `tail -f storage/logs/* >just-one-thing.log` and ran a single interaction, and the resulting file was 15M!

### Steps to reproduce

1. Develop with Craft, in development mode.
2. Check logs directory

### Expected behavior

Logs have a sane maximum size. I would have suggested 10 megabytes or so but after seeing a single interaction blow that out of the water, I guess more might be necessary if the default verbosity stays so high.

### Actual behavior

Multi-gigabyte log files. Paging through them, it looks like the vast majority is SQL queries. The average developer does not need to see the exact SQL queries Craft is running under the hood.

### Opinions

I understand that detailed logs are good for super-low-level optimization or debugging. I also understand that the default verbosity in production mode is rather lower. But when developing, generally you want warnings and errors to be obvious -- a high signal-to-noise ratio -- and the finer details only matter when a problem actually occurs. In that situation you were generally the user making the interactions with your app, so you can recreate the problem, and if the logs aren't giving enough clues you can gradually turn up the verbosity when you need it. You only need to leave the app running with high verbosity logging if you're waiting for some hard-to-replicate error to show up, or if you're doing super low level optimization or debugging.

For general development, the default logs are *far* too verbose. I am not going to dig through 15 megabytes of text just after a single interaction to see what happened, especially if I don't know what the message I'm looking for might look like.

For both development and production, I think a maximum file size, at the very least, would be a huge improvement. Have you ever had a linux server unexpectedly run out of disk space? Weird, horrible things happen. That is a very real possibility if there's no file size limit like this.

I suggest the defaults are changed to have much lower default verbosity (at least in dev mode), a reasonable maximum size for log files, and ideally some better documentation with examples on how to adjust it.

### Craft CMS version

4.0.x-dev at 6e466a0

### PHP version

8.1.2

### Operating system and version

Linux 5.13.0

### Database type and version

Mysql 8.0.27

### Installed plugins and versions

- Control Panel CSS v2.x-dev
- Formie dev-craft-4
- Navigation dev-craft-4
- Redactor 3.0.0-beta.2
- Retour 4.0.0-beta.4
- SEOmatic 4.0.0-beta.7
- Typed link field 2.1.0-rc
- Vizy dev-craft-4
- Workflow dev-craft-4

**Comment by timkelty** [comment]
@tremby You definitely have a point about the defaults being too verbose. Obviously 15M for a single request is excessive and may require some more scrutiny.

Fortunately, while we consider changing defaults – you have a number of tools in the configuration to tame this:


The following `config/app.php` shows how to configure the default log level. In this case, I am setting it to `LogLevel::INFO` in `devMode` (the default is `LogLevel::DEBUG`. For even less verbosity, you could just set it to `LogLevel::WARNING`.

```
<?php
use Psr\Log\LogLevel;

return [
    'components' => [
        'log' => [
            'monologTargetConfig' => [
                // Remove `debug` messages in `devMode`
                'level' => YII_DEBUG ? LogLevel::INFO : LogLevel::WARNING,
            ],
        ]
    ]
];
```

You can also selectively disable the logging of database [queries](https://craftcms.com/docs/4.x/config/db-settings.html#enablelogging) and **[profiling](https://craftcms.com/docs/4.x/config/db-settings.html#enableprofiling)** in your `config/db.php`.

Finally, it is worth mentioning that you can completely forgo file logging by setting [CRAFT_STREAM_LOG](https://craftcms.com/docs/4.x/config/#craft-stream-log). This is pipe logs to `STDOUT`/`STDERR` so they can be monitored in real time.

---

Try those options out and let me know how it goes. In the meantime I'll start a discussion about addressing the defaults.

**Comment by tremby** [comment]
@timkelty, thanks for your response.

That's exactly the sort of thing I'd love to see in one single easy-to-find place in the Craft documentation -- "these are the settings to look for, in these couple of different files, and here are a couple of examples for turning up/down verbosity". When I do a Google search right now for "craft cms logging", the only result which looks vaguely official and relevant is [this one](https://craftcms.com/knowledge-base/locating-error-logs-and-database-backups). I personally never fully trust knowledgebase articles like this (or blog posts) since they tend to get out of date.

I'm glad to hear you'll start a discussion about the defaults. Hopefully having a maximum log file size will be part of that discussion.

**Comment by khalwat** [comment]
Potentially related: https://github.com/craftcms/cms/issues/10913

**Comment by khalwat** [comment]
Here's the redone logs for Craft 4:

<img width="1167" alt="Screen Shot 2022-04-19 at 3 01 49 PM" src="https://user-images.githubusercontent.com/7570798/164077880-9d90f857-be95-4306-8c32-d84d8d9ed5bd.png">

When look at a log, you care about WHEN it happened, WHAT happened, and WHERE it happened.

The first two are clearly visible, the last, WHERE, is buried in a JSON blob, and not easily readable like it was in the Craft 3.x logs.

I can't see the benefits of this change, and the downsides are that the WHERE is obscured, making it more difficult to trace the application's flow using log files.

Hopefully you'll consider revisiting that.

**Comment by michaelrog** [comment]
> I'd also love to see the new log formats match the old Craft 3 log formats as closely as possible, unless there's a good reason for the change in formatting.

The good reason is [a vast improvement in machine-readability](https://github.com/craftcms/cms/pull/10659). Log parsers/aggregators interpret each log file line as a new log event, and the multi-line logging in Craft 3 (traces, context vars, query logs, all spanning multiple lines) made it impossible to machine-parse. The new single-line format is more standard and requires less fenageling to hook up to stuff that monitors STDOUT/STDERR, and JSON-encoding makes parsing that data more efficient and deterministic.

**Comment by timkelty** [comment]
Another side of the argument might be that old logs assume you know the format, and that the information output in that particular spot is the "category". With is as json, we have the luxury of a key.

**Comment by michaelrog** [comment]
> You definitely have a point about the defaults being too verbose. Obviously 15M for a single request is excessive and may require some more scrutiny. ... Fortunately, while we consider changing defaults...

15M of log data _is_ awfully hefty for a single request, and there may be some defaults adjustments in order... but also... maybe the _most_ sensible default is to just _not_ be in `devMode` unless you really _need_ to be.

And maybe at some point it makes sense to separate "dev mode" into separate concepts: normal/explicit modes for error handling, and normal/verbose/debug modes for logging. 🤔

**Comment by timkelty** [comment]
FWIW – the issue here was 2 fold:
- We were logging in a too-permissive default for `devMode` (`LogLevel::debug` instead of `LogLevel::info`), which let in everything (profiling, etc)
- _Each log message_ contained the request context (global vars, etc), instead of only once per-request.

**Comment by khalwat** [comment]
Making the logs good by default for both humans to read and also for machines to process seems like a pretty reasonable thing. I don't think it has to be one or the other, it can and should be both.

**Comment by michaelrog** [comment]
Agreed.

> That said, moving the category to be the first field in the JSON blob (rather than being placed after the memory reading and trace) might be a simple enough way to improve human-readability in the way you're looking for.

Wanna take this PR? ☝🏼

**Comment by timkelty** [comment]
> Hopefully, we're not approaching this from the perspective that logs will only ever be parsed by machines, via log aggregators

We're definitely not, and theres been a concerted effort to improve things for both machines and humans. You'll notice, eg, that stack traces and context var output is still multiline in `devMode`, but formatted as single-line json in production.

**Comment by timkelty** [comment]
It is also worth noting that it is quite easy to customize this, or any other formatting tweaks on the app-level: https://gist.github.com/timkelty/c0530983c3fb450c15a5f136fb388d3d#file-app-php-L26-L29

**Comment by khalwat** [comment]
I'm not concerned about customizing it, I'm sure it'll be something I can do.

I'm concerned about what will be provided by default to people who may not feel comfortable customizing it.

In addition, I will be sent logs from people who do not have things customized to be human-readable and will be logging into systems that are not mine that have logs that are not customized to be human-readable.

**Comment by timkelty** [comment]
> That said, moving the category to be the first field in the JSON blob (rather than being placed after the memory reading and trace) might be a simple enough way to improve human-readability in the way you're looking for.

Any thoughts on @michaelrog's suggestion as a middleground?

**Comment by khalwat** [comment]
It's better than not doing so, but I doubt it'd have the same readability as breaking it out of the JSON blob. Having it before the message makes it read more like a stack trace.

Anyway, I've raised the issue, not much more to discuss here really. We'll see what you end up with.

**Comment by wbrowar** [comment]
I like the idea of going from CONTEXT to CONTENT to help you figure out where you are before you read what the message is. I can see why the JSON stuff would be helpful, but I feel like a good compromise here could be something like:
```
[2022-04-19 18:51:54][nystudio107\\seomatic\\Seomatic::init] web. INFO: SOmatic plugin loaded {"trace": [], "memory":5340248}
```
Unless there's a time where a category isn't present (which could still just be set as `[]`), isn't this just as machine parsable?

**Comment by brandonkelly** [comment]
We’ve adjusted the format for the next release (#10959).

Going to close this, as the underlying issue has definitely been solved for the next release – log file sizes will be trastically smaller.

**Comment by tremby** [comment]
While I'd still very much like to see a maximum log file size (and enabled by default), I recognize that the danger is significantly lower now. Thanks to all who participated!

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with the logging improvements.

**Comment by timkelty** [comment]
@tremby FWIW, we were getting max file size support via Yii's FileTarget, which we are no longer using. The log file rotation we're using from Monolog isn't meant to be a fully-featured solution:

> Logs records to a file and creates one log file per day. It will also delete files older than $maxFiles. You should use [logrotate](https://linux.die.net/man/8/logrotate) for high profile setups, this is just meant as a quick and dirty solution.

**Comment by timkelty** [comment]
@rob-baker-ar We're working on getting more of these customizations officially documented, but in the meantime, I added an example of how to do that [here](https://gist.github.com/timkelty/c0530983c3fb450c15a5f136fb388d3d#file-app-php-L86-L103).

To do what you're describing, you need to replace the default rotating Monolog handler with `StreamHandler`, which logs to a single file. Let me know if you have any trouble implementing as shown in the gist.
