### ISSUE TITLE
[4.x]:  custom fields don't appear on custom sources attributes list on create/edit

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#10900]
### What happened?

**Description**

- For entries, we can't see custom fields when creating/editing custom sources, which is kind of understandable because custom fields are not available on all entry type layouts. 

https://user-images.githubusercontent.com/55586085/163713189-99977cb3-dc66-4058-a474-a3a39ecab222.mp4

- when creating a custom source for the user element type, custom fields won't appear on the table attributes list. but on editing that custom source, they show up on the table attributes list, which i can't understand because there is only one layout for all users, and we already know if custom fields are available or not.

https://user-images.githubusercontent.com/55586085/163713214-903527e8-558e-419d-bb0a-f0b307ed659d.mp4

### Craft CMS version
4.0.0-beta4

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Both are fixed for the next release. (Entries just have _all_ custom fields that are associated with an entry type field layout, available to them.)

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with this change.
