### ISSUE TITLE
[4.x]: Craft 4 is very slow in local dev with `devMode` on

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#10913]
### Description

Craft 4 in local dev with `devMode` on is significantly slower than the same Craft 3 site in local dev with `devMode` on.

Here's a video showing the difference:

https://user-images.githubusercontent.com/7570798/163231673-de1decff-c93a-4d3c-80ad-a076f2307e72.mov

The video above shows loading an SEOmatic page, but I've tested this across various parts of the CP, and it's equally slow everywhere.

The last reload is me disabling `devMode` in the Craft 4 site to see the difference, and it's significantly better, so potentially could have something to do with logging, and perhaps the sheer quantity of information that's being logged (it looks like the Request object is serialized for every log item?)

I took Tim's suggestion here: https://github.com/craftcms/cms/issues/10903#issuecomment-1096717962

...and removed the `debug` messages with `devMode` on (which seems a little counter-intuitive), and it did speed things up a bit, but still not up to speed with Craft 3:

https://user-images.githubusercontent.com/7570798/163232063-5ff148c4-a273-4f0d-8173-842d17ad588e.mov

### Steps to reproduce

1. Use Craft 4 in local dev with `devMode` enabled
2. Compare the speed to Craft 3 in local dev with `devMode` enabled

### Expected behavior

Craft 4 should be at least as speedy as Craft 3 in local dev with `devMode` on, and the same information being logged for debug purposes.

### Actual behavior

Craft 4 is significantly slower than Craft 3 in local dev with `devMode` enabled.

### Craft CMS version

4.0.0-beta.4

### PHP version

8.0.11

### Operating system and version

macOS Monterrey 12.3.1 (21E258)

### Database type and version

n/a

### Image driver and version

n/a

### Installed plugins and versions

n/a

**Comment by brandonkelly** [comment]
This appears to be due to all the additional logging Craft 4 is doing.

**Comment by khalwat** [comment]
This is fixed with the changed in the `4.0.x-dev`, to be released as `4.0.0-beta.5`
