### ISSUE TITLE
[3.x]: Image thumbnails within inactive tabs don't load when their tab is activated

### ISSUE THREAD

**Issue by knufri** [craftcms/cms#10918]
### Description
Image thumbnails within inactive tabs don't load when their tab is activated.

### Steps to reproduce

1. Created a Section with multiple tabs including an asset field in the second tab.
2. Upload an image to the asset field on the second tab.
3. Switch back to the first tab and reload the page.
4. Switch to the second tab, the image thumbnail won't be loaded.

Maybe it is related to https://github.com/craftcms/cms/issues/7890 seems it breaks again with update to Craft 3.7.37 or 3.7.38 and also in Craft 4.0.0-beta.4 - there is no error in the console and the div with the preview data-src ist available. Looks like the trigger to load the preview images is not fired. Works only after reload.

![Bildschirmfoto 2022-04-14 um 14 53 46](https://user-images.githubusercontent.com/2785206/163394640-668116d4-e2cc-43dd-8f71-7006c0c3fb67.png)

![Bildschirmfoto 2022-04-14 um 14 53 56](https://user-images.githubusercontent.com/2785206/163394659-19cd7a35-f0e5-4bd3-8a61-ae7a2d75093e.png)

I've tried without any plugins and a fresh install, always the same. In normal assets fields and matrix blocks.

### Craft CMS version

3.7.38

### PHP version

7.4

### Operating system and version

Darwin 21.4.0

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by knufri** [comment]
Wow! That was really fast. Thanks @brandonkelly for fixing so that. Craft CMS is awesome 💪🏼

**Comment by brandonkelly** [comment]
Craft 3.7.39 is out with the fix for this.
