### ISSUE TITLE
[4.x]: Possible to create custom element source without a label

### ISSUE THREAD

**Issue by mattstein** [craftcms/cms#10915]
### Description

While it’s possible this was a secret feature and I ruined the surprise, it seems odd that I can create a custom element source without a label:

<img width="295" alt="Screen Shot 2022-04-13 at 02 53 20 PM@2x" src="https://user-images.githubusercontent.com/2488775/163276852-49ba47a9-d306-445c-a38c-4f0b75ed3d4c.png">

It’s impossible to know that it’s there unless it’s highlighted or you happen to mouse over it, which seems like a UX issue.

If it _should_ be possible to have an unlabeled ninja source, I would expect it to say “(BLANK)” in the customization modal just like unlabeled separator.

### Steps to reproduce

1. Navigate to **Entries** and click **Customize (gear icon)**.
2. From the lower-left dropdown menu (+), choose **New custom source**.
3. Leave the **Label** field empty and press **Save**.
4. Paw around the Entries source menu to find your new element source.

### Expected behavior

A validation error would prevent me from saving, or the draggable Customize modal menu would at least show “(BLANK)” to indicate an intentionally-unlabeled custom element source.

### Actual behavior

I’m allowed to save an unlabeled custom element source and there are no hints that it was a sensible idea.

### Craft CMS version

4.0.0-beta.4

### PHP version

8.0.15

### Operating system and version

macOS 12.3.1

### Database type and version

MySQL 8.0.26

### Image driver and version

Imagick 3.6.0 (ImageMagick 6.9.11-60)

**Comment by brandonkelly** [comment]
We don’t have any sort of validation happening in that modal currently, and not really thinking it’s worth the effort to add just for this, so I went ahead and added “(blank)” as a fallback value for the time being.
