### ISSUE TITLE
[4.x]: Uploading certain SVGs causes error

### ISSUE THREAD

**Issue by mark-reactor15** [craftcms/cms#10923]
### Description

Uploading certain SVG images (I assume ones with non-integer viewboxes or sizes) results in an the upload bar hanging.

### Steps to reproduce

1. Upload an SVG with a non-integer size.

### Expected behavior

SVG should still uploads successfully.

### Actual behavior

Error from the AJAX request in the console shows:
`{"message":"Cannot assign float to property craft\\elements\\Asset::$_width of type ?int"}`

### Craft CMS version

4.0.0-beta.4

### PHP version

8.0.17

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting! This is now fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with this fix.
