### ISSUE TITLE
[4.x]: Calling unknown method: craft\web\View::renderTemplateMacro() 

### ISSUE THREAD

**Issue by jan-dh** [craftcms/cms#10921]
### Description
I have a custom module where I create a twig function:

```
new TwigFunction('x', function (...$args) {
    return \Craft::$app->getView()->renderTemplateMacro(
        '_macros/x',
        'icon',
        $args
    );
}, ['is_safe' => ['html']]),
```

After updating to Craft 4 I get an error saying:

```
yii\base\UnknownMethodException: Calling unknown method: craft\web\View::renderTemplateMacro() in /var/www/html/vendor/yiisoft/yii2/base/Component.php:300
```

### Steps to reproduce

1. Create a custom Module
2. try to call the method `renderTemplateMacro`

### Expected behavior

The Twig function should render the macro template

### Actual behavior

Throws an error

### Craft CMS version

Craft CMS 4.0.0-beta.4

### PHP version

8.1.3

### Operating system and version

MacOS Monterey 12.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
That’s because the method has been removed. It relied on a deprecated Twig feature that was removed in Twig 3.0.

**Comment by jan-dh** [comment]
Aha, makes sense. Should this also be mentioned in the [upgrading guide](https://craftcms.com/docs/4.x/upgrade.html#preparing-for-the-upgrade)? Also, is there any way to implement similar behaviour with Twig 3.0?

**Comment by mattstein** [comment]
Added a note to the [plugin update guide](https://craftcms.com/docs/4.x/extend/updating-plugins.html#templates) @jan-dh, thank you! There are helpers specifically for rendering Craft’s form components, but you’ll otherwise have to move macros to their own templates.
