### ISSUE TITLE
[4.x]: site default status is always enabled

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#10926]
### What happened?

**Steps to reproduce**

1. create a section with default status set to disable
2. go to create entry page for that section
3. default status is set to enable

### Craft CMS version

4.0.x-beta4

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with this fix.
