### ISSUE TITLE
[4.x]: Search with title produces error

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#10927]
### What happened?

In Craft 3 it was possible to search within the `title` of an element. In Craft 4.0.0-beta.4, it throws an exception.

> yii\\base\\ErrorException : Array to string conversion

### Steps to reproduce

1. Run the following Twig code.

```twig
{% set entries = craft.entries.search('title:article').all() %}
```

The stack trace points to the following line:
https://github.com/craftcms/cms/blob/1e084470fe8ed697341180c86393d49dec51c323/src/services/Search.php#L579

My guess is that this is a bug, otherwise it should probably be documented in the Craft 4 upgrade guide.

### Craft CMS version

Craft 4.0.0-beta.4

### PHP version

8.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with this fix.
