### ISSUE TITLE
[4.x]: new entry menu doesn't update, shows unavailable sections for selected site

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#10928]
### What happened?

**Description**
when new entry button remains open, it doesn't refresh on changing site, and shows unavailable sections for that selected site - obviously clicking on that section throws a console error 'Uncaught TypeError: s.data(...) is undefined on line 133 of EntryIndex.js'-

https://user-images.githubusercontent.com/55586085/163688748-e2a33755-8ec9-4465-9817-2ca6282f4148.mp4

### Craft CMS version

4.0.x-dev

**Comment by brandonkelly** [comment]
Thanks for the report! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with this fix.
