### ISSUE TITLE
[4.x]: Not able to override mainAttributes or mainFormAttributes in _layouts/cp.twig using unified element editor

### ISSUE THREAD

**Issue by BenParizek** [craftcms/cms#10924]
### What happened?

In Craft 3, I was able to extend the base cp.twig class and add custom attributes via `mainAttributes` and `mainFormAttributes`.

### This used to add custom attributes to the form element but no longer does in 4.x:

```
{% extends "_layouts/cp" %}

{% set mainFormAttributes = {
  'custom-attribute' => true
} %}
```

----

As I try to move toward using the unified element editor, I now use a custom route instead of a template extending this base template and it seems I lose the ability to do some things in the template. I think this came up once before with the ability to add custom assets bundles as well.

```
'sprout/forms/edit/<elementId:\d+>' =>
                'elements/edit',
```

It seems some of those things we used to override in the template are now supported on the element class, such as `public function getCrumbs(): array` but I can't seem to find away to add custom attributes without reverting to overriding with my own template. Am I missing anything? Is it likely these other attributes will be supported by the unified element editor route?

### Craft CMS version

4.0.0-beta.2

### PHP version

8

### Operating system and version

Macos

### Database type and version

MySQL

### Installed plugins and versions

Plugins in development

**Comment by brandonkelly** [comment]
Just added support for those for the next release. You can set them from your element’s `prepareEditScreen()` method:

```php
public function prepareEditScreen(Response $response, string $containerId): void
{
    $response->mainAttributes = [
        // ...
    ];
    $response->formAttributes = [
        // ...
    ];
}
```

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with this.
