### ISSUE TITLE
[4.x]: updating field layout and craft\helpers\StringHelper::encodeMb4(): Argument #1 ($str) must be of type string, null given

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#10929]
### What happened?

**Steps to reproduce**

https://user-images.githubusercontent.com/55586085/163689408-c5fd760e-36a2-4f89-bf98-a3f50ec56f60.mp4

### Craft CMS version

4.0.x-beta4

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for the report! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with this fix.
