### ISSUE TITLE
[3.x]: Matrix fields with minimum block limit but no max limit throwing message format error when entry saved.

### ISSUE THREAD

**Issue by icreatestuff** [craftcms/cms#10922]
### Description
In a matrix field that has a minimum block limit of 1 and no maximum (Max blocks field left empty) I see the following message format error thrown when saving an entry that uses the matrix field.

```php
2022-04-14 14:14:57 [-][1][6ifrt862e0882c9k0puj7l4ubr][error][yii\base\NotSupportedException] yii\base\NotSupportedException: Message format 'number' is only supported for integer values. You have to install PHP intl extension to use this feature. in /var/www/vhosts/domain.com/httpdocs/vendor/yiisoft/yii2/i18n/MessageFormatter.php:373
Stack trace:
#0 /var/www/vhosts/domain.com/httpdocs/vendor/yiisoft/yii2/i18n/MessageFormatter.php(277): yii\i18n\MessageFormatter->parseToken(Array, Array, 'en-GB')
#1 /var/www/vhosts/domain.com/httpdocs/vendor/craftcms/cms/src/i18n/MessageFormatter.php(32): yii\i18n\MessageFormatter->fallbackFormat('{attribute} sho...', Array, 'en-GB')
#2 /var/www/vhosts/domain.com/httpdocs/vendor/yiisoft/yii2/i18n/I18N.php(115): craft\i18n\MessageFormatter->format('{attribute} sho...', Array, 'en-GB')
#3 /var/www/vhosts/domain.com/httpdocs/vendor/yiisoft/yii2/i18n/I18N.php(95): yii\i18n\I18N->format('{attribute} sho...', Array, 'en-GB')
#4 /var/www/vhosts/domain.com/httpdocs/vendor/craftcms/cms/src/i18n/I18N.php(343): yii\i18n\I18N->translate('app', '{attribute} sho...', Array, 'en-GB')
#5 /var/www/vhosts/domain.com/httpdocs/vendor/yiisoft/yii2/BaseYii.php(538): craft\i18n\I18N->translate('app', '{attribute} sho...', Array, 'en-GB')
#6 /var/www/vhosts/domain.com/httpdocs/vendor/craftcms/cms/src/fields/Matrix.php(813): yii\BaseYii::t('app', '{attribute} sho...', Array)
```

The message indicates it might be an issue with the intl extension but this is installed. Tracing through it appears to be a problem related to validating the matrix field and specifically (in this case at least) when running the `tooMany` check in `craftcms/cms/src/fields/Matrix.php` ~ line 813. Commenting out that array item for example allows the entry to save correctly. 

```php
if (
    $element->getScenario() === Element::SCENARIO_LIVE &&
    ($this->minBlocks || $this->maxBlocks)
) {
    $arrayValidator = new ArrayValidator([
        'min' => $this->minBlocks ?: null,
        'max' => $this->maxBlocks ?: null,
        'tooFew' => Craft::t('app', '{attribute} should contain at least {min, number} {min, plural, one{block} other{blocks}}.', [
            'attribute' => Craft::t('site', $this->name),
            'min' => $this->minBlocks, // Need to pass this in now
        ]),
        'tooMany' => Craft::t('app', '{attribute} should contain at most {max, number} {max, plural, one{block} other{blocks}}.', [
             'attribute' => Craft::t('site', $this->name),
                'max' => $this->maxBlocks, // Need to pass this in now
        ]),
        'skipOnEmpty' => false,
    ]);

    if (!$arrayValidator->validate($blocks, $error)) {
        $element->addError($this->handle, $error);
    }
}
```

To caveat all this, I don't see this same behaviour on a different environment (same site) that is using a different version of PHP and the INTL extension.

As reported from utilities > PHP info:

- Works with PHP 8.0.15, intl (ICU version 69.1) >> local/dev environment
- **Doesn't work with** PHP 7.3.25, intl (ICU version 4.2.1) >> live/production environment

Unfortunately I'm not able to update the environment that is showing the issue at the moment but I believe it meets Craft's requirements.

### Expected behavior

Entry should save without issue.

### Actual behavior

Error exception thrown and entry not saved.

Many thanks,
Matt

### Craft CMS version

Pro 3.7.38

**Comment by brandonkelly** [comment]
Thanks for reporting! I was able to reproduce with the Intl extension disabled, so it does seem like it’s not installed properly for you.

Fixed for the next release!

**Comment by icreatestuff** [comment]
Interesting, I'll see what our hosting company has to say about the Intl extension. Thanks for jumping on a fix for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.39 is out with the fix for this.
