### ISSUE TITLE
[3.x]: Unable to use php craft setup in non interactive mode 

### ISSUE THREAD

**Issue by matt9mg** [craftcms/cms#10920]
### Description
When running the command:

```sh
usr/local/bin/docker exec -i my_docker_container bash -c "cd /var/www/html && DB_DRIVER=pgsql DB_SERVER=db DB_PORT=5432 DB_USER=my_user DB_PASSWORD=my_password DB_DATABASE=my_databse DB_TABLE_PREFIX=app_ php craft setup"
```

The programme exists

### Steps to reproduce

1. run the above command in the description or access a web server and run on a fresh install
2. you will be exited

The offending line seems to be here service/vendor/craftcms/cms/src/console/controllers/SetupController.php - L116 -L118

```php
if (!$this->interactive) {
    return ExitCode::OK;
}
```

### Expected behavior
I should be able to pass everything to run the installer in a non-interactive mode, this is really useful for automated installs

### Actual behavior
Program exits

### Craft CMS version

3

### PHP version

8.1

### Operating system and version

ubuntu 20.04 LTS

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
The `setup` command is just an interactive wrapper for the `setup/app-id`, `setup/security-key`, `setup/db-creds`, and `install` commands, each of which support being run non-interactively:

```sh
php craft setup/app-id
php craft setup/security-key
php craft setup/db-creds --driver=pgsql --server=db --port=5432 --user=my_user --password=my_password --database=my_database --schema=public --table-prefix=app
php craft install --email=a@b.com --username=admin --password=x --site-name="My Site" --site-url=http://example.com --language=en-US
```

**Comment by matt9mg** [comment]
@brandonkelly That is wonderful news, I would perhaps make this more clear in the documentation as this is super handy information. Thank you for coming back to me.
