### ISSUE TITLE
[4.x]: Entry Type Switcher has no effect

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#10933]
### Description
When I switch within my Entries the Entry type nothing happens. 

### Steps to reproduce

1. Create a new entry
2. Switch entry type via dropdown

### Expected behavior
When I switch the field Layout should change

### Actual behavior
Nothing happens

### Craft CMS version

Craft CMS 4.0.0-beta.4

### PHP version

8.1

### Operating system and version

MacOS 12.3

### Database type and version

MySQL 8

### Installed plugins and versions

![CleanShot 2022-04-17 at 13 24 13](https://user-images.githubusercontent.com/764292/163712288-fbe03d0d-b50a-4f57-b18b-452958aef3ad.png)

**Comment by brandonkelly** [comment]
Do you have the `autosaveDrafts` config setting disabled?

**Comment by davidhellmann** [comment]
Hey Brandon, 

yes, it is false. Never gave them some attention but if it is false how I can apply the entry type change? have to save the entry and that's it?

**Comment by brandonkelly** [comment]
I meant to deprecated that setting before the beta. Just did it now for the next release (aea04a70aa62f1c6b1a218e5c3f3056ba6609cc4). It’s not really necessary anymore, and entry type switching relies on draft autosaves now.
