### ISSUE TITLE
[4.x]: Images are not uploading properly

### ISSUE THREAD

**Issue by mauricioarangoosorio** [craftcms/cms#10937]
### Description
When adding an image to en entry, it looks like it has uploaded. But then the preview thumb is empty. And in the Assets manager, there's a record of the entry but when I clicking on the image it shows a black rectangle only.

![Screen Shot 2022-04-18 at 7 56 58 AM](https://user-images.githubusercontent.com/41710299/163811609-17ee83f3-073c-4c7c-adac-d3b40541009f.jpg)

### Steps to reproduce

1. Add an image to an entry

### Expected behavior

1. Should see a thumb in the entry page
2. Should see a preview of the image in the assets manager

### Craft CMS version

Craft Solo 4.0.0-beta.4

### PHP version

8.1.3

### Operating system and version

Linux 5.10.76-linuxkit

### Database type and version

MySQL 8.0.26

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-16)

### Installed plugins and versions

- Ray | 2.0
- Redactor | 3.0.0-beta.2

**Comment by brandonkelly** [comment]
If you open your browser’s Network tab and reload the page, do you see any failed image requests?

**Comment by mauricioarangoosorio** [comment]
As soon as I open the 'entries' page, I see this errors (I have a column for thumbs):
```
GEThttps://slayed.local/office/actions/assets/generate-transform?transformId=311&v=1648075727
[HTTP/2 500 Internal Server Error 1069ms]
Image Transform Error – craft\errors\ImageTransformException
Failed to generate transform with id of 311.```

And then inside an entry page I see a similar error.

When I try to add a new image, this is what I get (not sure why PRIMARY_SITE_URL) is there in the middle of the URL:
```
GET https://slayed.local/office/PRIMARY_SITE_URL/assets/uploads/Default/test-textile-2-4/_171x240_crop_center-center_none/13.jpg
[HTTP/2 404 Not Found 867ms]
```

Thank for looking into this!!

**Comment by brandonkelly** [comment]
Those could be related. Sounds like your filesystem’s base URL begins with `PRIMARY_SITE_URL`.

If you want to set it to an environment variable, it must begin with `$`, and cannot contain a trailing path afterward (e.g. `$PRIMARY_SITE_URL/assets/uploads` would not be allowed).

Otherwise you can set it to an [alias](https://craftcms.com/docs/4.x/config/#aliases), which can contain a subpath.

**Comment by mauricioarangoosorio** [comment]
What is strange is that I have the `$` in the filesystem base URL.

![Screen Shot 2022-04-18 at 6 47 24 PM](https://user-images.githubusercontent.com/41710299/163894154-23d56d12-9cc4-4dcd-9786-a793e3e1c888.jpg)

**Comment by brandonkelly** [comment]
As I said,

> If you want to set it to an environment variable, it must begin with `$`, and cannot contain a trailing path afterward (e.g. `$PRIMARY_SITE_URL/assets/uploads` would not be allowed).

**Comment by mauricioarangoosorio** [comment]
Sorry, need to find my glasses at this time of the day. Ok, thanks for the patience explaining this to me. I'll work on it.

**Comment by brandonkelly** [comment]
Going to close this for now, but let me know if you continue experiencing this issue after fixing the base filesystem URL.

**Comment by mauricioarangoosorio** [comment]
Brandon, your input solved my issue. Thank you so much!

**Comment by brandonkelly** [comment]
Glad to hear that!
