### ISSUE TITLE
[4.x]: a server error occurred on custom source save

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#10934]
### Description
on latest Craft 4 dev -no error on Beta 4-, clicking on 'save' button on custom source modal, throws a CP error 'a server error occurred', probably by [this line](https://github.com/craftcms/cms/blob/93a247720380509993801e0d53f0e4ff27099e54/src/web/assets/cp/src/js/CustomizeSourcesModal.js#L295)

### Craft CMS version

4.0.x-dev

**Comment by brandonkelly** [comment]
Doh, little typo. Thanks for reporting! Fixed now.
