### ISSUE TITLE
[4.x]: Project-config-created Singles missing from element queries until first save

### ISSUE THREAD

**Issue by mattstein** [craftcms/cms#10939]
### Description

Immediately after installing Craft and applying project config, query behavior for Singles differs between Craft 3 and Craft 4.

This element query returns the homepage entry as expected in Craft 3, but returns `null` in Craft 4:

```php
Entry::find()->slug('home')->one();
```

To have the entry returned in Craft 4, you can either...

- add `->status(null)`; `Entry::find()->slug('home')->status(null)->one()` **or**
- visit the entry in the control panel and press **Save**.

The initial state of the entry in the control panel—before any content migration or re-save—differs.

Craft 3:

<img width="1072" alt="craft-3" src="https://user-images.githubusercontent.com/2488775/163846735-86746abb-d570-4cfd-b08c-3acb2d1d798c.png">

Craft 4:

<img width="1072" alt="craft-4" src="https://user-images.githubusercontent.com/2488775/163846885-5f66494b-5901-4d1b-9ffb-8f78caa059ee.png">

Notice how the status is “Enabled” and “Live” in Craft 3 and “Enabled” + “Enabled” in Craft 4. The latter immediately changes to “Live” after you press **Save**.

### Steps to reproduce

1. Check out https://github.com/craftcms/starter-blog at its main branch, establish an environment for it, and run `php craft install`. (Project config should automatically be applied.)
2. Run the [included content migration](https://github.com/craftcms/starter-blog/blob/main/migrations/m210104_175929_sample_content.php), which should proceed successfully.
3. In the control panel, go to **Entries** → **Singles** → **Home** and observe that the **Site Introduction** Redactor field has content in it.
4. Wipe your database and repeat step 1 with the [feature/craft-4](https://github.com/craftcms/starter-blog/tree/feature/craft-4) branch.
5. Edit the [included content migration](https://github.com/craftcms/starter-blog/blob/feature/craft-4/migrations/m210104_175929_sample_content.php), to remove `->status(null)` [here](https://github.com/craftcms/starter-blog/blob/feature/craft-4/migrations/m210104_175929_sample_content.php#L193).
6. Run `php craft up` and notice the content migration fails with the message “Home is missing.”.

### Expected behavior

Homepage element query and migration should work identically in Craft 3 and Craft 4 since we’ve got an enabled and presumably live single.

### Actual behavior

Element query requires `->status(null)` in Craft 4, and the entry itself changes status on save with no edits.

### Craft CMS version

4.0.0-beta.4

### PHP version

8.0.15

### Operating system and version

macOS 12.3.1

### Database type and version

MySQL 8.0.26

### Image driver and version

Imagick 3.6.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- Asset Rev dev-feature/craft-4
- Gatsby Helper 2.0.x-dev
- Redactor 3.0.x-dev
- Typogrify v4.x-dev

**Comment by brandonkelly** [comment]
Fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with this fix.
