### ISSUE TITLE
[4.x]: primary site is always selected on edit entry page

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#10938]
### Description

**Steps to reproduce**
1. create a section with site1 -as primary- and site2 enabled
2. on element index page, change to site2
3. go to entry edit page
4. site1 is selected as default for edit page

**another case with 500 error:**
1. create a section with only site2 enabled
2. on element index page, change to site 2
3. click on create entry type
4. it throws a 500 error complaining about section is not enabled for site 1

### Craft CMS version

4.0.x-beta4

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
These are both working fine on my end.

In the URL, is the `site` query string param getting set to the correct site handle? Perhaps your query string params are getting discarded (e.g. via an `.htaccess` file redirect). A quick way to test would be to go to `/admin/utilities/php-info` and add `?foo=bar` to the URL. Then try searching the page for `$_GET['foo']`. Is it showing up, and set to `bar`?

**Comment by vnali** [comment]
yes @brandonkelly  it set to bar

and actually my first description about issue was not correct and
this video shows how changing site on site menu doesn't affect selected site on edit page:

also i tried craft4 beta1 and worked fine. after updating to beta 2 i can see the issue so i guess something changing on beta 2 make this happens.

https://user-images.githubusercontent.com/55586085/164050387-3284019c-35b0-4a18-89a6-54a28c386930.mp4

**Comment by brandonkelly** [comment]
Whoops, looks like f9b7e19a7d1cb0019b8c65f012151ec402a9463a actually broke this a bit. Fixed now for the next release. Thanks for reporting!

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with this fix.
