### ISSUE TITLE
A config setting to disable "Backup Database" tool

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1093]
> Created by: Ben Parizek (ben@barrelstrengthdesign.com) on 2015/03/12 23:19:32 +0000
> Votes at time of UserVoice import: 3

-----------------------------------

At some point a database becomes too large for the database backup tool and trying to backup your database this way times out.

I'm not sure what the best solution is and I'm not clear on the technical limitations are.  I also don't understand why when this happens I can switch to another database program and export things successfully.

But, in the case this continues to happen and if there is no way for Craft to throw an error informing the user of what's going on, it might be nice to have a config setting that allows that tool to be disabled so it doesn't appear as an option for users to get frustrated with.

**Comment by brandonkelly** [comment]
This was resolved in Craft 3, by moving DB backup creation to `mysqldump` / `pg_dump`, which don’t suffer from the same resource issues that our PHP-based backup script did in Craft 2.
