### ISSUE TITLE
[3.x]: Syteminfo set to 100% height making control panel look weird in Safari.

### ISSUE THREAD

**Issue by aeu** [craftcms/cms#10930]
### Description
There's a 100% height set on element ID #system-info that is is breaking the panel in Safari v 13.1.  Tested on multiple different Craft sites.

### Steps to reproduce

1. Login to the panel in Safari

### Expected behavior
The System info should not be 100% of the screen height.

### Actual behavior
The System info is 100% of the screen height.

### Craft CMS version

Craft Pro 3.7.37

### Installed plugins and versions

none.
-

**Comment by aeu** [comment]
![1](https://user-images.githubusercontent.com/2225377/163695640-281650d2-c03a-4250-bf09-898d2d483dc8.png)
![2](https://user-images.githubusercontent.com/2225377/163695642-05cf2a8b-b462-4426-ab0b-9d6f7015f71d.png)

**Comment by brandonkelly** [comment]
Thanks for reporting that. It should be fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.39 is out with the fix for this.
