### ISSUE TITLE
[4.x]: unverifiedEmail not updated when user is being saved with current email

### ISSUE THREAD

**Issue by Nellyaa** [craftcms/cms#10931]
### Description

This might be more of a feature request, not sure if this is intended.
As of right now, when you update a users email address (e.g. current email 'one@example.org'), the 'unverifiedEmail' of this user gets populated (e.g. 'two@example.org'), until the user verifies that email, which is fine. 
But if said user never verifies that email and starts to fill out the email field again, with their current active email ('one@example.org'), the unverifiedEmail doesn't become null or even one@example.org and stays on the last unverified input forever ('two@example.org'). Of course, a verification email to one@example.org isn't being sent, which is fine, since it is the current email and therefore valid by definition.
I expect the unverifiedEmail field to become null, once the user enters their current email. 

Use case for this: We want to show users whether they have an unverified email that is currently awaiting verification. But as of right now, the result is unexpected when the unverifiedEmail contents never go away, even when you try to 'un-make' that change, from a users standpoint.

### Steps to reproduce

1. Have a frontend form for users to change their email akin to something like https://craftcms.com/knowledge-base/front-end-user-accounts#user-profile-form
2. Have the setting 'users must verify their email address' active in the backend
3. Input another email as currently in use and submit form
4. Input the current email (not the unverified one) and resubmit the form
5. See that the user.unverifiedEmail still has the old value from Step 3

### Expected behavior

unverifiedEmail field becomes null, when the currently active email is being submitted on the save user form.

### Actual behavior

unverifiedEmail field stays with the value from before the submit, when the currently active email is being submitted on the save user form.

### Craft CMS version

4.0.0-beta.4

### PHP version

8.1.3

### Operating system and version

Linux 5.10.16.3-microsoft-standard-WSL2

### Database type and version

MySQL 10.7.3

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

**Comment by brandonkelly** [comment]
This is working as intended. If you save a user with the same email as their current one, the `users/save-user` action just assumes that the field was left unchanged. (Consider that the control panel’s Edit User page always shows an Email field, set to whatever the current active email is, regardless of what’s pending.)

If we were to change the behavior, it would mean that any time you save a user account, the pending email address would get wiped away, which would lead to a lot of frustration.

That said, you can change the behavior from a module if you want. Create a bootstrapped module and add this to its `init()` method:

```php
use craft\elements\User;
use craft\events\ModelEvent;
use yii\base\Event;

Event::on(
    User::class,
    User::EVENT_BEFORE_SAVE,
    function(ModelEvent $event) {
        /** @var User $user */
        $user = $event->sender;
        $request = Craft::$app->getRequest();

        // If they submitted their current email, clear out the unverified one
        if (
            $request->getIsSiteRequest() &&
            $request->getBodyParam('email') == $user->email
        ) {
            $user->unverifiedEmail = null;
        }
    }
);
```

**Comment by Nellyaa** [comment]
That makes sense, thank you!
