### ISSUE TITLE
[3.x]: Color field in table field not opening color picker

### ISSUE THREAD

**Issue by kevinmu17** [craftcms/cms#10945]
### Description
When making a table field there is the possibility to add a color field which normally opens a color picker, but the color picker isn't working within a table field.

### Steps to reproduce
1. Add a table field
2. Add column type color
3. Try to open the color picker from within the table

### Expected behavior
It should open the color picker when clicking on the color dot

### Actual behavior
Not opening the color picker and requiring the user to fill the HEX code themselves

### Craft CMS version

3.7.22

### PHP version

8.0.18

### Operating system and version

macOS Monterey 12.3.1

### Database type and version

MySQL 10.3.34

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-24)

### Installed plugins and versions

N/A

**Comment by remcoov** [comment]
I think this is a z-index issue?

**Comment by kevinmu17** [comment]
I've inspected the issue a little closer, the issue is that the type text input is overlapping the type color input. When using z-index on the color input it works fine

**Comment by kevinmu17** [comment]
never mind: see that this has been updated in #10775
