### ISSUE TITLE
[3.x]: Re-saving a User does not correctly re-index fields

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#10943]
### Description

Re-saving a User (or bulk re-saving all Users) does not correctly re-index fields.

If a field was previously non-searchable, but changed to searchable, it should get indexed when the Users are re-saved. However, this does not happen. Re-saving the User has no impact on the newly searchable field, unless you explicitly change the field value.

### Steps to reproduce

1. Create a Plain Text field that is **not searchable**.
2. Add the field to Users.
3. Create a few Users... **Be sure to populate the non-searchable Plain Text field.**
4. Change the field to now be searchable.
5. Bulk-resave the Users... notice that the Plain Text field was not added to the `searchindex` table.
6. Save a single User (without changing anything)... notice that the field isn't added to `searchindex`.
7. **Change the value of the field** and re-save.
8. Notice that the field was only added to the `searchindex` once you physically changed that field value.

### Expected behavior

Re-saving (or bulk re-saving) the User would index the newly searchable field.

### Actual behavior

Re-saving does not index the field. You must change the field value for it to get indexed.

### Craft CMS version

3.7.38

### PHP version

7.4.13

**Comment by brandonkelly** [comment]
Agree it would be ideal for Craft to remember whether fields were recently marked as searchable, but there’s currently no record of when that change took place. And we only reindex the keywords of fields whose values actually changed for a given update.

For “bulk re-saving”, are you referring to the `resave/users` command? `resave/*` commands can in fact reindex the search keywords, however you have to pass `--update-search-index`.

**Comment by lindseydiloreto** [comment]
Ahh, interesting! I didn't know about the `--update-search-index` flag, that was the missing piece. I (wrongly) assumed that it would update the search index by default.

All good now, thanks @brandonkelly! 👍
