### ISSUE TITLE
[4.x]: No longer possible to regenerate slug based on entry title

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#10949]
### Description

In Craft 3 (and 2), clearing out the slug field for an existing entry and re-saving the entry will make Craft generate a new slug based on the current value of the entry's title field.

In Craft 4.0.0-beta.4, clearing out the slug field and saving the entry does not generate a new slug; instead the slug field simply reverts to its previously saved (i.e. current) value.

Not sure if this is intended behaviour or a bug, but I couldn't find anything about it in the changelog. FWIW the old behaviour is something we've always made sure clients knew about, and I know many of them use it often (it's especially useful after duplicating an entry and changing its title).

### Steps to reproduce

1. Open an existing entry, and edit its title
2. Clear the current value from the slug field
3. Save the entry

### Expected behavior

The slug should be regenerated based on the current value in the entry's title field.

### Actual behavior

The slug reverts to its previous/current value (I'm assuming the empty value passed to the controller is interpreted as `null`, i.e. "no change").

### Craft CMS version

4.0.0-beta.4

### PHP version

8.1.4

### Operating system and version

macOS 12.3.1

### Database type and version

MySQL 5.7.37

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Whoops, that wasn’t intentional. Thanks for reporting! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with this fix.
