### ISSUE TITLE
[4.x]:  Fails updating missing assets in the CP 

### ISSUE THREAD

**Issue by mauricioarangoosorio** [craftcms/cms#10947]
### Description
If I got to Utilities → Asset Indexes → Update Asset Indexes → confirm deletion the indexes are not updated

### Steps to reproduce

1. Manually delete assets from your assets directory
2. Try to update the assets index manually in the CP: got to Utilities → Asset Indexes → Update Asset Indexes → confirm deletion

### Expected behavior
the indexes should be removed

### Actual behavior
I get the following error in the browsers console and nothing gets updated:
```json
|XHRPOSThttps://slayed.local/index.php?p=office/actions/asset-indexes/finish-indexing-session&v=1650374857153
[HTTP/2 500 Internal Server Error 816ms]
	
error	"craft\\services\\Assets::getFolderById(): Argument #1 ($folderId) must be of type int, string given, called in /app/vendor/craftcms/cms/src/services/Assets.php on line 293"
exception	"TypeError"
file	"/app/vendor/craftcms/cms/src/services/Assets.php"
line	388
trace	[ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]

```

### Craft CMS version

Craft Solo 4.0.0-beta.4

### PHP version

8.1.3

### Operating system and version

Linux 5.10.76-linuxkit

### Database type and version

MySQL 8.0.26

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-16)

### Installed plugins and versions

- Ray 2
- Feed Me 5 beta 1
- Redactor 3 beta 2

**Comment by brandonkelly** [comment]
Thanks for reporting! This is now fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with this fix.
