### ISSUE TITLE
[4.x]: 

### ISSUE THREAD

**Issue by mauricioarangoosorio** [craftcms/cms#10942]
### What happened?
Custom fields disappear on CP when editing and entry and Auto Save Draft is set to true

### Description

I have conditional fields that should only appear in child pages. When I click on the field to edit it, the page reloads, and all the conditional fields disappear. 
This only happens when in `general.php`, autosave drafts is set to true `'autosaveDrafts' => true`. When it is set to false it doesn't happen.

### Steps to reproduce

1. Create a conditional field that should  only show on child pages
2. Set autosaveDrafts to true
3. Try to edit the conditional fields on the child page.

### Additional info
This was reported before and was apparently resolved for the release of Craft4 Beta 4. But after the update, and the clearing of the `cpresources` folder I still see the issue

### Expected behavior
1. The conditional fields shouldn't disappear

### Actual behavior
1. Fields are disappearing

### Craft CMS version

Craft Solo 4.0.0-beta.4

### PHP version

8.1.3

### Operating system and version

Linux 5.10.76-linuxkit

### Database type and version

MySQL 8.0.26

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-16)

### Installed plugins and versions

- Ray 2
- Feed Me 5.0.0-beta.1
- Redactor 3.0.0-beta.2

**Comment by brandonkelly** [comment]
Thanks for the report. As you might remember, we’ve already fixed this for the next release, per #10816 :)
