### ISSUE TITLE
[4.x]: on changing site menu, selected source and new entry items don't update correctly

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#10954]
### What happened?

**Steps to reproduce**
on Craft4 beta 4 and latest dev, when a entry type source is selected, on changing site menu, selected source and new entry menu do not correctly updated

https://user-images.githubusercontent.com/55586085/164236727-8a3ad474-1884-4cc2-84b6-de1b24a5ea54.mp4

### Craft CMS version

4.0.x-beta4

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with this fix.
