### ISSUE TITLE
[4.x]: Updating elements via modal does not reflect in main window

### ISSUE THREAD

**Issue by JeanLucEsser** [craftcms/cms#10969]
### Description

When making change to an element (typically an asset's title) from within an entry via the modal edit window, the change is not reflected in the main entry window in real time, the page needs to be refreshed.

### Craft CMS version

4.0.x-dev 701d1a2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release – and then some :)

https://user-images.githubusercontent.com/47792/164566341-4b3a130e-4a01-44a3-ab92-6d9ff9ca64ff.mp4
