### ISSUE TITLE
[3.x]: Matrix block modal chopped off when there are several blocks at the top of an entry

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#10962]
### Description

A picture is worth some words.

![CleanShot 2022-04-20 at 16 07 59](https://user-images.githubusercontent.com/61869/164339381-f651419a-2d28-42b5-a38f-cf1ef83cfcf5.png)

### Steps to reproduce

1. Create a fresh Craft install
2. Create a Matrix field with 4-5 blocks.
3. Add a plain text field to each.
4. Add it to a section.
5. Create an entry and add a block.
6. Click the icon in the picture.
7. Notice the top of the modal gets chopped so you can't see all of the blocks.

### Craft CMS version

3.7.38

### PHP version

8.0

### Operating system and version

n/a

### Database type and version

n/a

### Image driver and version

n/a

### Installed plugins and versions

None.

**Comment by brandonkelly** [comment]
Already reported by #10883 and fixed for the next release.
