### ISSUE TITLE
[3.x]: Column suffixes are removed for existing Matrix sub fields when the parent field is saved

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#10973]
### Description

Whenever a Matrix field is saved, the column suffixes for any and all existing sub fields are removed.

This sort of sounds like what is happening in #9836, except on my end it happens consistently and for Matrix sub fields (I'm able to reproduce this on a fresh 3.7.38 install, without any plugins).

Not sure if this is a bug or intended/expected behaviour, but seemed odd enough to report.

### Steps to reproduce

1. Create a Matrix field with a block type and a sub field (Plain Text). Save it.
2. Confirm that the newly created sub field has a column suffix
3. Re-save the Matrix field (with or without changes, it doesn't matter)
4. Confirm that the sub field's column suffix is now `null`

### Expected behavior

The column suffix for existing sub fields should be retained when the Matrix field is re-saved.

### Actual behavior

The column suffixes for any and all existing sub fields are removed when the parent Matrix field is re-saved.

### Craft CMS version

3.7.38

### PHP version

8.0.17

### Operating system and version

macOS 12.3.1 (Laravel Valet 3.1.6)

### Database type and version

MySQL 5.7.37

### Installed plugins and versions

- None

**Comment by brandonkelly** [comment]
Definitely not intended! Thanks for reporting – fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.39 is out with the fix for this.
