### ISSUE TITLE
[4.x]: Asset alt text field is not available in GraphQL schema

### ISSUE THREAD

**Issue by tremby** [craftcms/cms#10976]
### Description

Though custom fields on asset types appear in the GraphQL schema and can be retrieved, if the native `alt` field is included in the asset type, it does not appear in the corresponding GQL schema. The only way to retrieve it over GQL at present is by selecting the `img` field and parsing it out of the resulting HTML.

### Steps to reproduce

1. Make a new type of asset
2. Include the native `alt` field
3. Optionally include some other custom field
4. Look at the GQL schema, such as by looking at the explorer view in Graphiql. Note `alt` is nowhere to be seen. The custom field, if included, is present

### Expected behavior

I can query for the asset's alt text, if it has an alt field.

### Actual behavior

There is no alt field on the asset schema.

### Craft CMS version

4.0.x-dev at a59b90e

### PHP version

8.1.2

**Comment by brandonkelly** [comment]
Added for the next release!
