### ISSUE TITLE
[4.x]: Bug in `Craft::$app->getAssets()->findFolders()`

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#10975]
### Description

The `Craft::$app->getAssets()->findFolders()` method is broken in Craft 4.

If you don't pass a parameter, it sets the default to `null`. This causes problems down the line... the default should be an empty array (`[]`).

❌  `Craft::$app->getAssets()->findFolders()` (passing nothing, defaults to `null`)
✅  `Craft::$app->getAssets()->findFolders([])` (passing an empty array)

This screenshot of the stack trace covers it pretty well...

![findFolders](https://user-images.githubusercontent.com/5309692/164512393-9253670c-fa65-4af0-8b57-416064e39127.png)

### Steps to reproduce

1. Use `Craft::$app->getAssets()->findFolders()` with no parameters.

### Expected behavior

Just works.

### Actual behavior

Throws an error.

### Craft CMS version

4.0.0-beta.4

### PHP version

8.0.16

**Comment by brandonkelly** [comment]
Doh thanks! Fixed for the next release.

**Comment by lindseydiloreto** [comment]
Sweet, thanks @brandonkelly!

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with this fix.
