### ISSUE TITLE
[4.x]: Cannot set new filename for asset

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#10981]
### Description

Entering a new filename in the asset editor page does not rename the file

### Steps to reproduce

1. Open editor for existing file
2. Change filename
3. Save

### Expected behavior

File should be renamed

### Actual behavior

The old filename appears again

/by Aylin

### Craft CMS version

4.0.x-dev 3cdc412

### PHP version

8.0.15

### Operating system and version

Windows 10

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with this fix.
