### ISSUE TITLE
[3.x]: Incorrect Asset field locations in slideout editors

### ISSUE THREAD

**Issue by yoannisj** [craftcms/cms#10987]
### What happened?

When two elements share the same asset field, and the asset field has a **templated** default folder (default upload folder or restricted to a single folder) with reference to one of the element's attributes (e.g. `{slug}/images`), then that default folder will always be resolved based on the current element editing page.

This is incorrect when that element has a relation field which accepts another element using the same asset field, and that related element is edited/created via a slideout editor.

### Steps to reproduce

Preparation:
1. Create an entry type "Post" and another entry type "Collection"
2. Create an Assets field named "Files", with setting "Restricted assets to single folder" set to `{slug}/files`
3. Add the "Files" asset field to the field layout of both entry types "Post" and "Collection"
4. Create an Entries field named "Related Posts" which allows selecting entries of type "Post"
5. Add the "Related Posts" field to the field layout of the "Collection" entry type

Reproduce Behaviour:
6. Create a new Collection entry, give it a title and wait for the first draft save*
7. Click on "Files > Add an Asset > Upload Files" and upload a file for the collection
8. Click on "Related Posts > Add an Entry > Create new Post Entry"  to open a slideout editor for Post entry
9. Give the new Post entry a title and wait for the first draft save*
10. In the slideout editor, Click on "Files > Add an Asset"
11. You can see the files uploaded in step 7

This means that the Files folder for the Post entry resolved to the same folder as for the Collection Entry

*This wait is just so Craft generates a recognizable slug which helps verifying the issue.

### Expected behavior vs. Actual behavior
When creating or editing related elements in a slideout editor, Twig expressions in the Asset field folder settings should always resolve based on that element (the Post entry in the example steps above). Currently the behavior of Asset fields' with such settings is not consistent across the slideout editor and the full page editor.

### Craft CMS version
3.7.32

### PHP version
8.0.16

### Operating system and version
Linux 5.10.76-linuxkit (Nitro 2)

### Database type and version
MySQL 8.0.28

### Image driver and version
Imagick 3.7.0 (ImageMagick 7.1.0-16)

### Installed plugins and versions
(I don't think this is relevant, but happy to share if the issue can not be reproduced without any plugins)

**Comment by brandonkelly** [comment]
> This means that the Files folder for the Post entry resolved to the same folder as for the Collection Entry

Are you sure about that? More likely, the asset is still in the temporary uploads folder, and hasn’t been relocated to the slug-based folder yet. When you are at this point, try going to the Assets index page, and checking to see where the asset actually lives.

**Comment by yoannisj** [comment]
@brandonkelly you are right: that was a hasty assumption, and it appears the uploaded files were all in the temporary uploads folder. I tested again with 3 levels deep (edit page > slideout editor > slideout editor) and for slideout editors all files get uploaded in the temporary uploads folder and then relocated to the dynamic folder path once the elements are saved for the first time.

---

However, while testing again I noticed that the behaviour was slightly different when uploading files through the edit page vs. slideout editors. Indeed, when on the edit page the files are directly uploaded in the dynamic folder instead of in the temporary folder and this may lead to a minor issue:

If the asset field's location uses the `{slug}` placeholder, creating new elements and uploading a file before the element is given a title (or if the element's title is changed after the file is uploaded) results in an empty folder left behind after relocating the files upon first save. This _does not happen_ in when creating new elements _in the slideout editor._ Please see the following screen-recordings illustrating this


https://user-images.githubusercontent.com/3032696/165603110-8ba5c719-b4b2-4a4b-a716-bd739a2b4baa.mp4

_File uploaded before title is given: leaves an empty `temp_xxx` folder behind after save (if the title is changed, an empty folder based on the original title is left behind)._

I would say this a minor issue, since the files are correctly relocated once the element is saved; but still thought I would share my findings here.

**Comment by brandonkelly** [comment]
Yeah the full page editor and slideout editor are drastically different in Craft 3 behind the scenes, but they’ve been unified for Craft 4.
