### ISSUE TITLE
[4.x]: matrix field validation when there is no block type or no field

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#10989]
### What happened?

working on a matrix field, noticed two validation problem with that
- when a matrix field is created, if there is no field inside of the block type, matrix can be saved but that matrix can not be deleted
- when only block type of matrix is deleted, after saving matrix field it returns saved, but that block type still exists inside the matrix

https://user-images.githubusercontent.com/55586085/164744748-c3474f6b-9f3f-47f0-964d-ff3aa3ce1bed.mp4

### Craft CMS version

4.0.x-beta4 and latest dev

### PHP version

8.0.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting! Both are fixed for the next release.

The bug where removing all block types had no effect on save was present in Craft 3, so fixed it there as well.

**Comment by brandonkelly** [comment]
Craft 3.7.39 and 4.0.0-RC1 are out with these fixes.
