### ISSUE TITLE
[3.x]: Gifs causing 504's on front-end and back-end entries.

### ISSUE THREAD

**Issue by jhealey5** [craftcms/cms#10986]
### What happened?

We have a client site that has recently started throwing 504's on certain pages with certain gifs. I'm not sure when this first started as the pages aren't high traffic pages.

The entry 504's when accessing it either via cp or the front-end. If I delete the gif from the assets panel then the page loads again. The asset does show up fine inside assets though, and when uploading to the entry prior to saving.

I've checked a few different gifs out, they're all animated but with sizes ranging from 200k to 1mb, it doesn't seem to make a different. I've tried to look through the logs but couldn't find anything related. 

I realise the above isn't a lot to go on but let me know if you require anything else / have any suggestions where to look.

### Craft CMS version

Craft Pro 3.7.38

### PHP version

8.0.18

### Operating system and version

Linux 5.4.0-109-generic

### Database type and version

MySQL 10.3.34

### Image driver and version

Imagick 3.6.0 (ImageMagick 6.9.10-23)

### Installed plugins and versions

Only one with any relevance I believe:

Amazon S3 | 1.3.0

**Comment by brandonkelly** [comment]
Sounds like maybe ImageMagick isn’t configured with a high enough memory limit to handle the image, so it’s getting stuck trying to transform it. Transforming animated GIFs can be a particularly demanding task.

One easy workaround is to just disable GIF transforms altogether, via the [transformGifs](https://craftcms.com/docs/3.x/config/config-settings.html#transformgifs) config setting.

If that doesn’t work for you, you can reach out to support@craftcms.com and we can try to help with your ImageMagick config.
