### ISSUE TITLE
[3.x]: Widgets add their full namespace value as a CSS class

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/cms#10998]
### Description

Widgets add their full namespace as a CSS class, however I'm not sure that's a valid value to use as a class value, given the namespace path uses the backslash character, perhaps if it was just the widget name as a lowercase handle i.e. `recententiries` that would be cleaner.

![image](https://user-images.githubusercontent.com/8067792/164886916-40225017-a24d-4044-9aaf-2cb4a62d86bc.png)

### Steps to reproduce

1. Add one of the default widgets e.g. Recent Entries
2. View the class value on the element that provides the data attributes `data-type` and `data-id`
3. Observe the full namespace has been added as CSS class value e.g. `widget craft\widgets\recententries last`

### Expected behavior

Cleaner CSS class name?

### Actual behavior

Potentially invalid CSS class value, I'm not sure this could be selected by `document.querySelector()` or a DOM path.

### Craft CMS version

3.7.28

### PHP version

7.4

### Operating system and version

Ubuntu Linux 20.04 LTS (WSL2)

### Database type and version

MySQL 8

### Image driver and version

N/A

### Installed plugins and versions

N/A

**Comment by brandonkelly** [comment]
Agree that would have been nicer, but backslashes (and any other non-space unicode character) are valid within class names, and changing it would be a breaking change. Some widgets may be specifically styling themselves based on this class.

**Comment by jamesmacwhite** [comment]
Well there you go, I didn't know backslash was valid under the CSS specification, so I've learnt something either way! Thanks!
