### ISSUE TITLE
[3.x]: RedirectController security breach

### ISSUE THREAD

**Issue by jlachancekffein** [craftcms/cms#10994]
### Description
craft\controllers\RedirectController actionIndex allows you to redirect to any site from any Craft site.

Example: https://craftcms.com/actions/redirect?url=https://google.com

I would be curious to know why this controller action exists.

### Craft CMS version

> 3.5.15

**Comment by bencroker** [comment]
This does indeed appear to be a security concern:
https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html

**Comment by brandonkelly** [comment]
Thanks for bringing that to our attention! We’ve resolved this for the next release.

Next time you find a security vulnerability, please report it privately via [our website](https://craftcms.com/contact), per our [security policy](https://github.com/craftcms/cms/security/policy).
