### ISSUE TITLE
[4.x]: JavaScript error "Element editors may only be used with forms" when viewing entry revisions

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#10990]
### Description

When viewing an entry revision, the following JavaScript exception is thrown:

```
jquery.js?v=1650094043:2 
        
Uncaught Element editors may only be used with forms.
(anonymous) @ jquery.js?v=1650094043:2
setTimeout (async)
w.readyException @ jquery.js?v=1650094043:2
(anonymous) @ jquery.js?v=1650094043:2
l @ jquery.js?v=1650094043:2
c @ jquery.js?v=1650094043:2
setTimeout (async)
(anonymous) @ jquery.js?v=1650094043:2
u @ jquery.js?v=1650094043:2
fireWith @ jquery.js?v=1650094043:2
fire @ jquery.js?v=1650094043:2
u @ jquery.js?v=1650094043:2
fireWith @ jquery.js?v=1650094043:2
c @ jquery.js?v=1650094043:2
setTimeout (async)
(anonymous) @ jquery.js?v=1650094043:2
u @ jquery.js?v=1650094043:2
fireWith @ jquery.js?v=1650094043:2
fire @ jquery.js?v=1650094043:2
u @ jquery.js?v=1650094043:2
fireWith @ jquery.js?v=1650094043:2
ready @ jquery.js?v=1650094043:2
B @ jquery.js?v=1650094043:2
```

Presumably this is because Craft instantiates the `Craft.ElementEditor` on a form `#main-form`, but there's not actually a form with that ID in the DOM.

### Steps to reproduce

1. View a revision

### Expected behavior

No errors.

### Actual behavior

There is an error.

### Craft CMS version

4.0.0-beta.4

### Operating system and version

macOS 12.3.1, Edge 100.0.1185.44

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with this fix.
