### ISSUE TITLE
Weird lazy loading behavior when you have a lot of sources on element index page

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#11]
#### Environment:

- Craft version: 3.x
- PHP version: 7.x
- Database driver & version: n/a 
- Plugins & versions:

#### Description:

I ran into a situation where the ElementIndex doesn't fetch more elements when you have more sources (asset folders in this case) than elements per call. If you look at the attached image:  you'll see that I've seen the latest asset, but I have to scroll all the way down to load more, because of all the folders I have on the left side.

![image 2015-02-27 at 9 32 47 am](https://cloud.githubusercontent.com/assets/61869/22400189/0fe32296-e563-11e6-8d48-83ac46f42035.png)

**Comment by brandonkelly** [comment]
Guessing this was fixed via b012155d556446656799fb7964469777d1286724
