### ISSUE TITLE
[3.x]: Forgotten password flow can be used to enumerate usernames

### ISSUE THREAD

**Issue by nickdunn** [craftcms/cms#11006]
### Description
It doesn't meet the criteria in https://github.com/craftcms/cms/security/policy#scope as a full security vulnerability report. But  a manual audit of a client's site yielded:

> it was possible to enumerate valid versus invalid user accounts via the forgotten password functionality. This issue could allow a malicious attacker to enumerate registered users and attempt brute force password guessing attacks against valid accounts. It should be noted that there appears to be a 5-minute lockout in force after 5 consecutive failed login attempts. Based on this mitigating control the issue has been downgraded from Medium to Low severity. However, the issue should be raised with the supplier as this behaviour is not considered best practice. 

### Expected behavior
Ideally this wouldn't be the case and instead of "Invalid username or email." Craft would use a generic message stating the reset link has been sent if a matching account has been found?

### Craft CMS version

3.7.37

### PHP version

8

**Comment by angrybrad** [comment]
You can mitigate this by setting https://craftcms.com/docs/3.x/config/config-settings.html#preventuserenumeration to `true`.

**Comment by nickdunn** [comment]
🤦🏻‍♂️ Rtfm. Thank you.
