### ISSUE TITLE
[3.x]: Unable to deploy Craft CMS applications

### ISSUE THREAD

**Issue by MrHesus** [craftcms/cms#11008]
### Description

Due to vulnerability in `composer/composer` I can't deploy my application without enabling `allow_failure`. 

### Actual behavior

`a Missing input validation can lead to command execution via VcsDriver::getFileContent() package has known vulnerabilities
`

### Craft CMS version

^3.6

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Composer has been updated for the next release (83e91724c77204004f96068233a80043f6b73727).
