### ISSUE TITLE
[4.x]: Table column type of Dropdown - Can't edit settings

### ISSUE THREAD

**Issue by chadcrowell** [craftcms/cms#11002]
### Description
Clicking table field gear for column type dropdown opens modal for settings but I can't add options.

### Steps to reproduce

1. Make a table field with a column type of dropdown2. 
2. Click gear to try to add options

### Expected behavior

Modal opens and I can add options

### Actual behavior

Modal opens and I can not add options - https://d.pr/v/snzzTw

### Craft CMS version

4.0 Beta 4

### PHP version

8.0.17

### Operating system and version

Monterey 12.3.1

### Database type and version

Maria 10.5.15

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-16)

### Installed plugins and versions

- Feedme 5 beta

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.0-RC1 is out now with this fix.
