### ISSUE TITLE
[4.x]: Adding new entry from slide out should clear any previous search

### ISSUE THREAD

**Issue by JeanLucEsser** [craftcms/cms#11015]
### Description

This is between a bug and discussion but I'll vote for bug.

Adding a new entry via the slide out modal should either clear or update the search in the selection modal.

### Steps to reproduce

1. Let's say we're creating or editing an element with an entries field
2. We're opening the selection modal to select our entry (or entries)
3. At that point, more often than not, before eventually creating a new entry because it does not exist in the list, we're searching for it, so that we don't end up with a duplicate
4. Search finds nothing so we decide to create a new entry from here ; the slide out appears
5. We fill in the fields and save
6. We're back to the selection modal

### Expected behavior

The just created entry should be pre-selected so that we can just click "add", in the same way as if we didn't perform a search first.

Either with the search field cleared and showing all entries (preferred), or with the search still active but updated to reflect the newly created entry (which in all logic should correspond to the search terms).

### Actual behavior

We have to clear the search field first to show all entries, find the newly created entry and click add.

### Craft CMS version

4.0 beta 4 latest dev

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Good call. Made that change for the next Craft 3 and Craft 4 releases (both imminent).

Entry and asset selection modals will also start changing the selected sort to Date Created (descending), to ensure the new element floats right to the top.

**Comment by brandonkelly** [comment]
Just released 3.7.39 (and 4.0.0-RC1) with this change.
