### ISSUE TITLE
[3.x]: 

### ISSUE THREAD

**Issue by CDRO** [craftcms/cms#11014]
### Description

`craftcms/cms` depends on `composer/composer:2.1.9` which has known security vulnerabilities.

### Steps to reproduce

No need to reproduce, the behaviour can be seen in any composer.json file of `craftcms/cms`.

### Expected behavior

Craft should depend on the newest version of composer 2.

### Actual behavior

Craft depends on `composer/composer:2.1.9`.

### Craft CMS version

3 and 4

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Already updated for the next release :) 83e91724c77204004f96068233a80043f6b73727
