### ISSUE TITLE
[3.7.38]: Matrix Fields with a Minimum Blocks Value Set Cannot Be Saved

### ISSUE THREAD

**Issue by theAdhocracy** [craftcms/cms#11012]
### Description

After updating to the latest version of Craft (3.7.38) any Entry type with a Matrix field that requires a minimum number of blocks returns an Internal Server Error when the Save or Create buttons are pressed.

Entries will still save changed automatically and drafts are created, but you cannot properly save or create new entries.

Removing the minimum block limit fixes the issue and everything behaves as normal.

### Steps to reproduce

1. Create a new Matrix field with at least one block type and a Plain Text field
2. Set the "Min blocks" value to 1; leave "Max blocks" blank; all other settings as default
3. Create a new Entry type and add the new Matrix field to it
4. Try to create a new entry within that new Entry type

### Expected behavior

Entry is created as normal.

### Actual behavior

Entry appears to save during editing, but then crashes to an Internal Server Error message when the actual button is pressed (or Ctrl+S shortcut is used).

Yii log shows the following warning:

![image](https://user-images.githubusercontent.com/7009462/165183887-f886506a-84c2-40b3-a7f2-e1a83309afa4.png)

Followed immediately by the following error:

![image](https://user-images.githubusercontent.com/7009462/165184100-6f2cdaad-ac5e-442f-abfb-309804a8c6f7.png)

Unfortunately the logging bar on the actual error page is unresponsive.

### Craft CMS version

Craft 3.7.38

### PHP version

7.3.33

### Operating system and version

Linux 4.18.0-305.10.2.2.lve.el7h.x86_64

### Database type and version

MySQL 10.3.34

### Image driver and version

Imagick 3.5.1 (ImageMagick 7.1.0-20)

### Installed plugins and versions

Bulk Edit	2.0.6
Child Me!	1.3.0
Control Panel CSS	2.4.0
Control Panel JS	2.4.0
Control Panel Nav	3.0.17
Date Range Field	2.5.0
Do It Yourself widget	2.1.0
Element API	2.8.4
Feed Me	4.5.0
Field Manager	2.2.4
Image Resizer	2.1.1
Maps	3.9.3
nethooks	1.1.2
Reasons	2.2.6
Redactor	2.10.6
Sidebar Entry Types	1.0.3
Single Cat	1.2.1
Super Table	2.7.1
Tags	1.0.9
Webhooks	2.4.1

**Comment by brandonkelly** [comment]
It’s hard to tell from the screenshot, but this could be related to #10922. Can you try changing your `craftcms/cms` requirement in `composer.json` to `"dev-release/3.7.39 as 3.7.38"` and running `composer update`?

If that doesn’t fix it, please send a database backup and your Composer files over to support@craftcms.com, and we can try to reproduce it from there.

**Comment by theAdhocracy** [comment]
@brandonkelly Sorry for the extremely slow response, I've had issues getting back around to this. We have just updated to the latest version of Craft 3 (3.7.44) and I can no longer replicate this issue. Sorry I can't be any more specific; it's possible rerunning `composer` was enough, or possibly updating one of the plugins we use fixed it, but either way it seems to no longer be an issue.

**Comment by brandonkelly** [comment]
Good to hear!
