### ISSUE TITLE
[4.x]: Vertical positioning of icons

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#11025]
The move icon's vertical positioning could use some adjusting to make it vertically centred (minor annoyance). While you're there, the remove icon might need a tiny amount of adjusting too.

<img width="780" alt="Screenshot 2022-04-27 at 09 40 02" src="https://user-images.githubusercontent.com/57572400/165478824-21f764dd-83d1-4903-be5c-0b38e1f05c12.png">

### Craft CMS version

Craft CMS 4.0.0-RC1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next release.

**Comment by brandonkelly** [comment]
4.0.0-RC2 is out now with that fix.
