### ISSUE TITLE
[4.x]: some attributes are not translated on error messages

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#11029]
### What happened?

on these pages, attributes like name and handle are not translated on error messages like '....can not be blank'

- admin/settings/fields/new
- admin/settings/globals/new
- admin/settings/filesystems/new
- admin/settings/assets/volumes/new

### Craft CMS version

4.0.0-RC1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for fields, global sets, and volumes, for the next Craft 3 release, and for filesystems as well for the next Craft 4 release.

**Comment by brandonkelly** [comment]
4.0.0-RC2 is out now with those fixes.

**Comment by brandonkelly** [comment]
3.7.40 is out now as well.
