### ISSUE TITLE
[3.7.39]: dump() throws error

### ISSUE THREAD

**Issue by rene-haefliger** [craftcms/cms#11027]
### What happened?

I get a Call to undefined function error when using dump() in my plugin code.

### Craft CMS version

3.7.39

### PHP version

8.0.17

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
`dump()` is only available when Dev Mode is enabled, because it is registered via a special Debug extension for Twig.

You can use the [`{% dd %}`](https://craftcms.com/docs/3.x/dev/tags.html#dd) tag regardless of Dev Mode though.
