### ISSUE TITLE
[4.x]: JS error, conditional rule buttons on field layout element settings slideout not working for Commerce variants, Neo block types

### ISSUE THREAD

**Issue by ttempleton** [craftcms/cms#11026]
### Description

When opening the field layout element settings for a field on a Craft Commerce variant's field layout, a JavaScript error occurs, and the buttons to add conditional rules based on the user and variant don't work. I'm opening the issue on the Craft CMS repo rather than Commerce, because this is also happening with Neo block types, and I assume they both have the same cause in the CMS itself.

The JavaScript error:

```
Uncaught TypeError: can't access property "closest", e is null
    initNode htmx.min.js:1
    processNode htmx.min.js:1
    <anonymous> cp.js:1
    createSlideout FieldLayoutDesigner.js:235
    createSettings FieldLayoutDesigner.js:656
    init FieldLayoutDesigner.js:613
    jQuery 8
    init FieldLayoutDesigner.js:611
    constructor Base.js:20
    constructor Base.js:32
    constructor Base.js:32
    initElement FieldLayoutDesigner.js:459
    init FieldLayoutDesigner.js:295
    constructor Base.js:20
    constructor Base.js:32
    constructor Base.js:32
    initTab FieldLayoutDesigner.js:128
    init FieldLayoutDesigner.js:60
    constructor Base.js:20
    constructor Base.js:32
    constructor Base.js:32
    <anonymous> new:1578
    jQuery 13
htmx.min.js:1:24817
```

### Steps to reproduce

1. Install Craft CMS 4.0.0-RC1 and Craft Commerce 4.0.0-beta.2
2. Create a new product type, and set it to have multiple variants
3. With the variant field layout tab open, open the settings slideout for the Title field
4. See that the console has logged an error and the user/variant rule buttons don't work

### Expected behavior

No JavaScript error when opening the field layout element settings slideout, and working conditional rule buttons.

### Actual behavior

JavaScript error when opening the field layout element settings slideout for Commerce variants and Neo block types, and non-working conditional rule buttons.

### Craft CMS version

4.0.0-RC1

### PHP version

8.1.4

### Operating system and version

macOS Monterey 12.3.1

### Installed plugins and versions

- Commerce 4.0.0-beta.2
- Neo 3.0.0-RC1

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
4.0.0-RC3 is out now with this fix.
