### ISSUE TITLE
[3.x]: redundant line in translation files

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#11038]
### What happened?

on develop branch there is one [redundant line](https://github.com/craftcms/cms/blob/26678d376277e579f4c1bde6951199307f0b22e6/src/translations/en/app.php#L685) in source translation file and other languages, and also on [4.0 branch](https://github.com/craftcms/cms/blob/c34eddcf4f7573d3d0eea7b30df73b05afe57cc9/src/translations/en/app.php#L703)

### Craft CMS version

3.7.39

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Removed for the next release.
