### ISSUE TITLE
[4.x]: plugin store link is broken on multi site

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#11031]
### What happened?

on multi site install, the Plugin Store link is broken.

https://user-images.githubusercontent.com/55586085/165584409-639d47e6-4e80-4363-93d2-0641b9787447.mp4

### Craft CMS version

4.0.0-RC1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
4.0.0-RC2 is out now with that fix.
