### ISSUE TITLE
[3.x]: Matrix blocks are opening upwards and getting hidden underneath the header bar

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#11036]
### Description

We have a matrix page builder field with a decent number of blocks. It looks like the list would fit if it opened downwards, but it's opening up, and the z-index of the page's title bar is covering the top of the matrix popup, so I can't delete the block

![image](https://user-images.githubusercontent.com/1250017/165687166-23457c73-f580-4cac-be5b-511f1f1c459e.png)

### Steps to reproduce

1. Add lots of matrix block types
2. Open a block's cogwheel on an edit page
3. Sometimes it opens upwards and gets stuck under the title bar

### Expected behavior

The matrix cog wheel menu should either open downwards in this situation, or / and update the z-index of the title bar so I can see the top of the menu.

### Craft CMS version

3.7.38

### PHP version

8.0.18

### Operating system and version

Ubuntu 20.04

### Database type and version

MySQL

### Installed plugins and versions

![image](https://user-images.githubusercontent.com/1250017/165687523-0bd618ea-a541-4124-9035-7924d473cb13.png)

**Comment by brandonkelly** [comment]
This was fixed in yesterday’s 3.7.39 release :)

**Comment by darylknight** [comment]
Ah, sorry! Thank you :)
