### ISSUE TITLE
Improve design of field layouts

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1103]
> Created by: Tom (t@klepl.com) on 2015/04/20 17:54:59 +0000
> Votes at time of UserVoice import: 3

-----------------------------------

It's great that we can group input fields into Tabs... but sometimes a Tab isn't the right way to present the fields to a content editor. It would be helpful to be able define sections (with titles) and have the ability to group fields into columns as additional ways of organizing the layout of an input form. This would allow us to enhance the input & editing experience for people.

On a similar note, the visual hierarchy of fields and their parent elements as presented to an editor could be improved. Right now all the text is the same size, colour, and weight and is a little hard to scan.

**Comment by brandonkelly** [comment]
The next Craft 3.5 release features a new field layout designer with the ability to add headings, tips, and warnings, among other things. (See #1138 and #4647.)
