### ISSUE TITLE
[3.X]: Dimensions photoeditor don't match image dimensions

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#11046]
### Description
When uploading an image (JPG) and edit it in the image editor of Craft CMS the pixel dimensions shown in photo editor do not match with the dimensions of the original file.
<img width="1431" alt="Screenshot 2022-04-29 at 15 11 42" src="https://user-images.githubusercontent.com/22771556/165952555-a6126e0f-8ba3-4b7a-a0be-c6e59b91ddd0.png">
<img width="1127" alt="Image Editor result" src="https://user-images.githubusercontent.com/22771556/165952564-995d53e8-a978-4789-93b8-6ff66a2f2c58.png">

### Steps to reproduce

1. Upload a large image in the assets
2. Edit the image
3. If you try to crop the image, you see the dimensions of the image in your screen. Not the actual image dimensions.

### Craft CMS version

3.7.38

### PHP version

7.4.25

### Image driver and version

Imager-X with Imagix

### Installed plugins and versions

- Imager X -> v3.5.6.1

**Comment by brandonkelly** [comment]
Just removed that dimensions text box from the crop tool altogether, since there’s not really any point to it. Ultimately the image is going to (likely) get transformed before being shown on the front end anyway.

**Comment by brandonkelly** [comment]
3.7.40 is out now with that change.
