### ISSUE TITLE
[4.x]: Typo "Filesytem Type" in filesystem edit pages

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#11043]
### Description

There's a typo "Filesytem Type" in filesystem edit pages:

![CleanShot 2022-04-29 at 08 38 50](https://user-images.githubusercontent.com/298510/165895917-26622b12-865f-402d-8248-57346cc01e61.png)

### Steps to reproduce

1.

### Craft CMS version

4.0.0-RC2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Doh, thanks!
