### ISSUE TITLE
[3.x]: getEntryTypes result when used as the type parameter fails in Craft 3 but works in Craft 2.

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/cms#11057]
### Description

I'm not sure about this but I'm debugging a project which is having a problem with a specific template under Craft 3 but works in Craft 2.

I've narrowed down the error to be related to an entry query and the type parameter, it seems to be related to the behaviour of the `getEntryTypes()` return value called on a section in a Twig template.

Under Craft 2, `craft.sections.getSectionByHandle('handle').getEntryTypes()`

Produces an array result like this:

![image](https://user-images.githubusercontent.com/8067792/166158402-147ae320-f239-4e7c-92ee-25c59e037710.png)

Under Craft 3 `craft.app.sections.getSectionByHandle('handle').getEntryTypes()` with the section.

![image](https://user-images.githubusercontent.com/8067792/166153394-acd47095-ba57-456d-b9fe-9c18ef7ed3e3.png)

The array syntax might just be Kint thing, so possible red herring, however the result of `getEntryTypes()` is being used in a `craft.entries` query assigned to the type parameter and under Craft 3, it appears to be bugging out.

```
yii\base\ErrorException: strtolower() expects parameter 1 to be string, array given in /app/vendor/craftcms/cms/src/helpers/Db.php:471
Stack trace:
#0 {main}
```

It makes me think it's possibly due to the fact the array output is indexed 0,1,2,3,4 etc, not flattened like in Craft 2. I am however not sure if that's the real issue here, but it seems to be the main difference.

The value passed which the DB helper is breaking on

```
^ array:1 [▼
  0 => 43903
]
```

If this isn't a bug, I do apologise, but struggling to see what else is different given it works fine on Craft 2.

### Craft CMS version

3.7.39

### PHP version

7.4

### Operating system and version

Ubuntu Linux 20.04

### Database type and version

MySQL 8

### Image driver and version

N/A

### Installed plugins and versions

N/A

**Comment by brandonkelly** [comment]
Craft 3 did indeed drop support for passing an array of entry types into the `type` param.

You can fetch the IDs from each of them and pass them to the `typeId` param, though;

```twig
.typeId(entryTypes|column('id'))
```

**Comment by jamesmacwhite** [comment]
@brandonkelly Thanks for confirming and providing an alternative. Wondering if it's worth documentation that on the Craft 2 to 3 changes doc somewhere. I couldn't find any mention of getEntryTypes dropping support for this pattern, but if it is already documented, I apologise.

**Comment by jamesmacwhite** [comment]
> Craft 3 did indeed drop support for passing an array of entry types into the `type` param.
> 
> You can fetch the IDs from each of them and pass them to the `typeId` param, though;
> 
> ```
> .typeId(entryTypes|column('id'))
> ```

Although just to clarify, I believe supplying an array of entry type handles is still valid per:

https://craftcms.com/docs/3.x/entries.html#type

It's just the output of .getEntryTypes() can no longer used be used to feed the type parameter I guess. Although, I could replace this with my own twig variable which provides the handles as a replacement to mimic the Craft 2 logic.

**Comment by brandonkelly** [comment]
> It's just the output of .getEntryTypes() can no longer used be used to feed the type parameter I guess. Although, I could replace this with my own twig variable which provides the handles as a replacement to mimic the Craft 2 logic.

`getEntryTypes()` returns an array of entry type _models_ (`craft\models\EntryType` objects), not their handles. Which is why in my initial response, I suggested swapping them out with their IDs (`entryTypes|column('id')`)` and passing that to the `typeId` param instead. Or, you could stick with the `type` param if you mapped them to their handles instead:

```twig
.type(entryTypes|column('handle'))
```

Although that wouldn’t be as performant as the `typeId` route, because Craft needs to normalize them to their IDs under the hood.

That said, I just went ahead and [re-added support](https://github.com/craftcms/cms/commit/54a3959cf6aaf88d40a3919507a09c3cd6ef804d) for passing an array of entry types into entry queries’ `type` params, for the next release. So going forward this will be possible (again):

```twig
.type(entryTypes)
```

If you’d like to test that ahead of the next release (coming later this week), you can edit your `craftcms/cms` requirement in `composer.json` to `"dev-release/3.7.40 as 3.7.39"`, and then run `composer update`.

**Comment by jamesmacwhite** [comment]
@brandonkelly Thanks for the clarification and re-implementing support for it!

In this case, due to how the template logic is constructed, there are conditions which overwrite the entryTypes with the relevant handles. `getEntryTypes()` was just being used to not hard code all of the handles I believe, so typeId would be harder to maintain, however since you've allowed this to be possible again, I don't have to!

I'll give it a test now for you and feedback!

**Comment by brandonkelly** [comment]
> In this case, due to how the template logic is constructed, there are conditions which overwrite the entryTypes with the relevant handles.

Your debug output screenshot for Craft 4 clearly shows an array that is set to an array of `craft\models\EntryType` objects. So I suspect something is wrong with your conversion logic.\

**Comment by jamesmacwhite** [comment]
The template logic is roughly this currently:

```
{% set entryTypes = craft.app.sections.getSectionByHandle('sectionName').getEntryTypes() %}

{% if something %}
    {% set entryTypes = ['handle', 'handle2']
{% elseif something else %}
    {% set entryTypes = ['anotherHandle']
{% endif %}
```

Basically, if none of the conditions match the default is for all entryTypes to be passed to the type parameter, otherwise an array of handles would be passed which works fine. So it's basically the array of entry models change between Craft 2 to 3 which was failing, although I have just tested this and it works with Entry models (the original getEntryTypes() call after your change, so thank you!

**Comment by brandonkelly** [comment]
3.7.40 is out now with those changes.

**Comment by jamesmacwhite** [comment]
Thank you!
