### ISSUE TITLE
[4.x]: sort option doesn't work for custom field

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#11051]
### Steps to reproduce

1. add a custom field to entry type field layout
2. add custom field to entry type source
3. go to element index for that source
4. added custom field is not sortable -sort button is not available-

### Craft CMS version

4.0.0-RC2

**Comment by brandonkelly** [comment]
Only certain field types are sortable. Out of the box, that’s Time, Plain Text, Number, Money, Lightswitch, Dropdown, Radio Buttons, and Date. Is the field type you added one of those?

**Comment by vnali** [comment]
@brandonkelly yes, i checked with plain text field and number field

**Comment by brandonkelly** [comment]
Is this for a native source, or a custom source?

**Comment by vnali** [comment]
both of them @brandonkelly 
uploaded a video:

https://user-images.githubusercontent.com/55586085/166223495-22f2f8a6-d848-441b-84d2-9bfeaa64018a.mp4

**Comment by brandonkelly** [comment]
Ah thanks, the bug was just that it wasn’t possible to click on the table headers to sort the columns. Sorting via the sort menu was still possible.

Fixed for the next release!

**Comment by brandonkelly** [comment]
4.0.0-RC3 is out now with this fix.

**Comment by vnali** [comment]
@brandonkelly is it normal that on sorting by custom field, page URL updated with field uid instead of field handle?
for example /admin/entries?sort=**field%3Abf4adfaa-6ad4-478e-8d47-bc27dc756e98**-asc

**Comment by brandonkelly** [comment]
@vnali Yeah. It has to match the same attribute key that gets stored in the source’s list of visible table columns, which must be the field’s UID so the column doesn’t get removed whenever the handle changes.
