### ISSUE TITLE
Field, Block & Label Hierarchy

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1105]
> Created by: Jason Mayo (jason@bymayo.co.uk) on 2015/10/05 14:38:23 +0000
> Votes at time of UserVoice import: 3

-----------------------------------

A few of our clients who now run on Craft have struggled to *scan* the page to find a particular field or a matrix block etc.

We think this is down to the hierarchy of the headings above blocks, fields and field labels. They are all the same size and weight (Granted, a slightly different colour)...

Making these more distinguished will make scanning a long page to find a certain bit of content a lot easier.

**Comment by brandonkelly** [comment]
Lots of readability improvements have been made for Craft 3.
