### ISSUE TITLE
[4.x]: Image field label spacing is tight

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#11068]
### What happened?

This is inside neo / matrix but I'm pretty sure it affects normal image inputs

Neo:
![Screen Shot 2022-05-03 at 6 35 54 pm](https://user-images.githubusercontent.com/25124/166425361-f794efe0-fd72-4df0-bc73-816afc9cb155.png)

Matrix:
![Screen Shot 2022-05-03 at 6 46 57 pm](https://user-images.githubusercontent.com/25124/166426500-f6977822-6a1a-4c09-87cc-c3eb3ab47778.png)

### Craft CMS version

5b4997120f78dad12ae1f948a35d25e7ec336a66 (dev-main)

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Fixed, thanks!
