### ISSUE TITLE
[3.7.38][GraphQL] orderBy RAND() regression

### ISSUE THREAD

**Issue by adrienpicard** [craftcms/cms#11063]
### Description
I understand  cb59bde049e82c6d5a029f60dd4dc396ec2a9a3b fixes a vulnerability issue but it also means we can't orderBy RAND() anymore with GQL queries. 

Would be great to know if there's any work around.

### Steps to reproduce
Write a GQL query with orderBy: "RAND()"

### Expected behavior
It returns random results

### Actual behavior
It throws an `Illegal value for  orderBy argument` error

### Craft CMS version

3.7.38

### PHP version

7.4.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Sorry, we overlooked that, but it should be allowed.

Just fixed this for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-release/3.7.40 as 3.7.39"` and run `composer update`.

**Comment by brandonkelly** [comment]
3.7.40 is out now with that fix.

**Comment by adrienpicard** [comment]
Amazing. Thanks for the quick fix @brandonkelly

**Comment by davidwebca** [comment]
I just got reported a bug about that and found this issue. Glad I just need to update to have the fix already 😂  Thanks for the quick fix!

**Comment by katiasmet** [comment]
It looks broken again in 3.7.44.

**Comment by brandonkelly** [comment]
@katiasmet Just tested and it’s still working on my end. That’s a SQL error though – so `RAND()` is making it into the query but it’s being used incorrectly. What’s your full GraphQL query?
