### ISSUE TITLE
[4.x]: Duplicate slug does not show error message

### ISSUE THREAD

**Issue by JeanLucEsser** [craftcms/cms#11064]
### Description

If you disable automatic slug increment via `"maxSlugIncrement" => 1`, then creating a second entry with the same slug does not show an error message. Entry stays (or becomes) inactive but there is no visual indication as to why.

### Steps to reproduce

1. Add `"maxSlugIncrement" => 1` to general config
2. Create 2 entries with the same slug
3. Try to save the second entry as active

### Expected behavior

Should generate an error message and set the entry as inactive.

### Actual behavior

Set the entry as inactive without any error message.

### Craft CMS version

4.0 RC2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
This is the same behavior as Craft 3, fwiw. Agree it’s awkward though.

**Comment by brandonkelly** [comment]
@jesuismaxime What is the section’s entry URI format?

**Comment by jesuismaxime** [comment]
There wasn't one, this section is not "expose" and called with GraphQL, so I add one base on `{id}-{slug}` and make the api call using `uri` instead of `slug` to avoid any issues. Shouldn't slugs be unique even if there's no URI format?

**Comment by brandonkelly** [comment]
@jesuismaxime Got it, so this is actually working as expected. Craft will only ensure slugs are unique if needed to achieve a unique URI for the element.

**Comment by jesuismaxime** [comment]
The uri format `{id}-{slug}` allows me to avoid any further issues. 50 entries with the same slug is actually quite an issue when you fetch entries by slug using GraphQL, that is why I added an uri format based on the `id`, because all the slugs of the 50 entries are the same, now their URI is not. 

Anyway, I still think this is an issue - at least hide the 'Slug' input when the URI is not in use or add an CLI command/option to resave entries and reformat the slug based on the title could be a nice feature!

**Comment by yoannisj** [comment]
> Anyway, I still think this is an issue - at least hide the 'Slug' input when the URI is not in use or add an CLI command/option to resave entries and reformat the slug based on the title could be a nice feature!
Hmm, from looking at other similar issues here in the craftcms/cms repository, I understand there is some confusion as to when Craft care about unique slugs and increment them to achieve this uniqueness. However, I often use slugs for entries that don't have URLs. Not for querying, but for example for deep-linking or to populate the `id` attribute on HTML tags in templates (useful for example, to point to these tags for a11y with `aria-labelledby`).

Therefore, I don't think Craft should go the route of hiding the slug field for elements without URIs. Maybe improving the documentation about the built-in incrementing of slugs, or add a setting to entry sections where admins can explicitly choose whether slugs should be unique or not.
