### ISSUE TITLE
[4.x]: UX glitch when using a long title (action button out of screen)

### ISSUE THREAD

**Issue by JeanLucEsser** [craftcms/cms#11061]
### Description

Small UX glitch here, when the entry title is too long it pushes the action buttons to the right, as seen in this screen capture:

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/14908712/166197530-e161de66-97df-43a5-906b-b59cb221a36e.png">

### Steps to reproduce

1. Create an entry with a long title.

### Expected behavior

Use ellipsis (or allow for the title to use 2 lines).

### Actual behavior

See attached image.

### Craft CMS version

4.0 RC2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.
