### ISSUE TITLE
[4.x]: Setting a focal point for an image does not refresh live preview

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#11060]
### Description

In Live Preview, the preview window is not refreshed when the focus point of an image is updated.

### Steps to reproduce

1. Edit an entry
2. Open Preview
3. Open image preview, set new focal point, close image preview

### Expected behavior

Preview refreshes and shows the updated image transform

### Actual behavior

It does not.

/Mel

### Craft CMS version

4.0.x-dev a598210

### PHP version

8.0.15

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-18)

### Installed plugins and versions

none

**Comment by brandonkelly** [comment]
It’s refreshing on my end. Also confirmed that the asset’s modification date is getting updated as expected, so the revved transform URL is getting updated when [revAssetUrls](https://craftcms.com/docs/3.x/config/config-settings.html#revasseturls) is enabled.

Can you try enabling that config setting? If it’s still not working, please send a database backup, and your Composer files, over to support@craftcms.com.

**Comment by wsydney76** [comment]
@brandonkelly `revAssetUrls` is already enabled.

Maybe my description was misleading: the asset is updated correctly, only the iframe containing the live preview is not reloaded automatically when the image preview modal is closed by pressing the ESC key or clicking outside. (no js error)

When the iframe is manually reloaded, the new transformation is displayed correctly.

**Comment by brandonkelly** [comment]
For me it is getting reloaded the instant the image editor is closed.

**Comment by wsydney76** [comment]
@brandonkelly 

Sorry, (I need to learn the correct wording), i'm referring to the new Craft 4 thing: `It’s now possible to edit images’ focal points from their preview modals`, the one that opens when you click once on the image in the asset field:

![image](https://user-images.githubusercontent.com/60010597/166336399-035b1c6b-c913-486f-ac9d-a67914f60373.png)

Tested on latest Chrome/Edge/Firefox on Windows 10.

The old way "double click on title -> slide out -> Edit -> Focal Point -> Save" works correctly as ever.

/Mel

**Comment by brandonkelly** [comment]
Aha! Thanks for clarifying. Fixed now for the next release.

**Comment by wsydney76** [comment]
@brandonkelly  Thanks and sorry again for my lack of clarity.

Updated to 4.0.x-dev 27edf1e and that works fine now.

However, it looks like other changes (adding images, updating text, etc.) no longer trigger a reload of the live preview frame.

/Mel

**Comment by brandonkelly** [comment]
@wsydney76 doh, thanks. Got a little carried away with that last commit. Fixed now (f37c83366158d23059b3ada7b852ddb2f5cfc910)
