### ISSUE TITLE
[3.x]: Fields are duplicated with both site's content visible after enabling multi-site

### ISSUE THREAD

**Issue by lukastransom** [craftcms/cms#11067]
### Description
After enabling multi-site for different languages, some fields (not all) are now showing themselves as duplicates in the page (section) view.

![craft-multisite-matrix](https://user-images.githubusercontent.com/60360044/166416505-2e88becb-7d98-4f6d-8912-99cd3594420c.png)

Matrix blocks are duplicated... not a big deal because they can be easily removed.

![craft-multisite-supertable](https://user-images.githubusercontent.com/60360044/166416399-4c8f1dae-216b-44af-ac12-a10c48267982.png)

As you can see in the screenshot, with my "EN" site selected ① a single field ② has multiple Super Tables ③ ④ inside of it with the "JA" field values ④ visible... which I don't think is normally possible. I can't remove multiple fields from a single field area. Switching to the "JA" site still shows two fields inside of one field area.

### Steps to reproduce
1. Create a new language as a site.
2. Set fields to "Translate for each language"
   - Super Tables and Matrix fields are set as "Save blocks to all sites the owner element is saved in"
   - Text fields _within_ Super Table or Matrix fields are saved as "Translate for each language"

### Expected behavior

A site's field content should be visible only while that site is selected.

### Actual behavior
A site's content is visible while another site is selected.

### Attempted solutions
Tried running `php craft resave/entries` as mentioned in another multi-site related issue #4064.
Is there anything else that can be done to re-propagate fields?

### Craft CMS version

3.7.39

### PHP version

8.0.18

### Operating system and version

Ubuntu 20.04.4 LTS

### Database type and version

MySQL 8.0.27

### Image driver and version

Imagick 3.6.0 (ImageMagick 6.9.10-23)

### Installed plugins and versions

```json
"craftcms/ckeditor": "^1.1",
"craftcms/cms": "^3.7",
"craftcms/feed-me": "^4.4",
"craftcms/postmark": "^2.1",
"craftcms/redactor": "^2.10",
"doublesecretagency/craft-inventory": "^2.1",
"ether/tags": "^1.0",
"mmikkel/retcon": "^2.2",
"mutation/translate": "2.7.1",
"nystudio107/craft-imageoptimize": "^1.6.33",
"nystudio107/craft-minify": "^1.2",
"nystudio107/craft-retour": "^3.1",
"nystudio107/craft-seomatic": "^3.3.32",
"nystudio107/craft-vite": "^1.0",
"pennebaker/craft-architect": "^2.4",
"putyourlightson/craft-blitz": "^3.10",
"sebastianlenz/linkfield": "^2.0.0@beta",
"vaersaagod/dospaces": "^1.1",
"verbb/formie": "^1.4",
"verbb/navigation": "^1.4.13",
"verbb/super-table": "^2.6.7",
"vlucas/phpdotenv": "^3.4.0",
"yiisoft/yii2-redis": "^2.0.6"
```

**Comment by brandonkelly** [comment]
Were there multiple sites to begin with? Or was there originally just one site?

**Comment by lukastransom** [comment]
Originally just one with more languages (sites) added after the first was finished.

**Comment by brandonkelly** [comment]
In that case, you must have modified your Matrix/Super Table fields’ Propagation Method settings after adding the site, and then you likely started editing content before all queue jobs had completed.

Any time you edit a section’s enabled sites or Propagation Method setting, or edit a Matrix/relation field’s Propagation Method setting, most of the actual work is performed by a queue job that must go through and resave all of the affected elements. If you try to edit content before that’s done, you’ll get some unexpected behavior like you’re seeing here.

Do you have a database backup from before you made the change? If so, can you try restoring that, recreating the change, waiting for all queue jobs to finish, and then check to see if the problem persists?

**Comment by lukastransom** [comment]
Your proposed timeline and actions taken sound in-line with what was done setting up these new site.
(Adding content to the new sites before propagation tasks had finished seems to be the likely cause, indeed).

I do have a backup I can revert to, though that'll be a lot of work recreating the new language sites 😢 
Removing/re-adding the fields to the sections doesn't remove the duplicates, either.

It sounds like there's no way to manually re-issue these propagation tasks after-the-fact?
Or a database script to clean it up?
Are there any preventative measures to be taken to prevent this in the future other than confirming the queue is cleared of all tasks before editing?

**Comment by brandonkelly** [comment]
> It sounds like there's no way to manually re-issue these propagation tasks after-the-fact?

That would just cause even more duplicated blocks.

The good news is, the problem should only be limited to whatever entries were manually edited before the job was completed. You should be able to order your entries by Date Updated (descending) and jump through them, deleting any unexpected duplicates.

**Comment by lukastransom** [comment]
Because the affected Super Tables were set as 'static', I was caught up in thinking they couldn't be edited to remove duplicates 'fields'. It turns out (thanks to your comment making me re-think of the situation), if I just uncheck the 'static' setting from the affected Super Tables, I can go in and remove these duplicates 'fields' as if they were repeater rows in Super Table (because they are!).

So, rather than restoring from a DB backup, I think I'll take this approach of _make field into repeater_ → _remove duplicate Super Table rows_ → _re-enable field as 'static'_ to cleanup the existing DB.

Thanks!

If there's no other advice or actions for preventative measures, I think this issue safe to close, now.
