### ISSUE TITLE
[4.x]: Modifying a field causes other empty fields to get marked as modified

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#11078]
### Description

There is some bug in the "tagging" behaviour of modified fields in entry drafts (the blue highlight on the left)

### Steps to reproduce

1. Set up some fields
2. Go to the entry edit page
3. Publish entry
4. Modify a field (e.g type something in a text field)

### Expected behavior

A provisional draft is created and the modified field is marked as modified

### Actual behavior

A provisional draft is created and most other fields are also marked as modified. I have not done extensive testing but I have an asset field, a matrix field, a text field and a lightswitch. A change on each of them makes the others get marked as modified, except for the lightswitch. 

I didn't have time to make a screen recording but I can if you have trouble reproducing!

### Craft CMS version

Craft Pro 4.0.0-RC3

### Installed plugins and versions

-

**Comment by thupsi** [comment]
Upon further investigation, only **empty fields** are marked as modified.

**Comment by thupsi** [comment]
Possibly related to [this issue](https://github.com/craftcms/cms/issues/10804)?

**Comment by brandonkelly** [comment]
Doh, this was caused by the fix for #10804 (should have tested other field types to make sure they still worked as expected). Just released 3.7.40.1 with a fix, and that’s merged into the `4.0` branch for the next release.
