### ISSUE TITLE
[3.7.39]: htmlpurifier custom configs not visiable

### ISSUE THREAD

**Issue by Joobs** [craftcms/cms#11073]
### Description
I've created a new `Custom.json` in `config/htmlpurifier/` copied over the default settings. 
When I go to a Redactor/CKEditor field to the HTML Purifier Config settings, the dropdown only shows Default. Even if I rename `Default.json` -> `something.json` it still only show Default.

### Expected behavior
I should see Default and Custom as options

### Actual behavior
No config options are show, only Default.

### Craft CMS version

3.7.39

### PHP version

8.1.3

### Operating system and version

Linux 5.10.76-linuxkit

### Database type and version

MySQL 5.7.37

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-16)

### Installed plugins and versions

CKEditor | 1.3.0
Redactor | 2.10.7
...

**Comment by brandonkelly** [comment]
Just tested and this is still working as expected on my end.

Perhaps it’s a permissions thing? PHP may not have permission to read the file. Try setting `config/htmlpurifier/` and all its contents to `777`.

**Comment by Joobs** [comment]
Can confirm, problem was my end. It's working as expected now.

If Nitro has been running for a long time, i seem to get some random issues like this where the state of the server seems to not update (I think there is a port conflict with another program).

**Comment by brandonkelly** [comment]
Ah yeah… that can happen with Docker from time to time.
