### ISSUE TITLE
[4.x]: Entry page seems to get refreshed twice when applying a draft

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#11084]
### Description

When a draft gets applied there is a weird behaviour where the page seems to get refreshed twice.

### Steps to reproduce

1. Apply a draft

### Expected behavior

Draft gets applied

### Actual behavior

Draft gets applied but the page seems to get refreshed twice, almost like the entry is saved two times in a row.

Possibly related to #11083

### Craft CMS version

Craft Pro 4.0.0-RC3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.1 is out now with the fix for this.
