### ISSUE TITLE
[3.x]: Plugins can't be updated through panel after 3.7.39

### ISSUE THREAD

**Issue by dgsiegel** [craftcms/cms#11080]
### Description

With Craft 3.7.38 I could just update every plugin individually through the panel (`/admin/utilities/updates`). However since 3.7.39 this does not work anymore, as all plugins are still listed as outdated.

When pressing the "Update" button, Craft actually does upgrade the plugin, it just displays the outdated version, e.g.

![image](https://user-images.githubusercontent.com/4396895/166683854-68773afd-92c3-4b86-a128-2d227698930e.png)

But `vendor/craftcms/contact-form/composer.json` tells another story:

```
{
  "name": "craftcms/contact-form",
  "description": "Add a simple contact form to your Craft CMS site",
  "version": "2.5.1",
  "type": "craft-plugin",
  "keywords": [
    "cms",
    "craftcms",
    "contact",
    "form",
    "yii2"
  ],
...
```

`compose.json` also lists the correct version:

`    "craftcms/contact-form": "2.5.1",`

And here's the `composer.lock` section:

```
        {
            "name": "craftcms/contact-form",
            "version": "2.5.1",
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/craftcms/contact-form/zipball/93a31d4c95aba5109fb1cb2461d450bf1771ae51",
                "reference": "93a31d4c95aba5109fb1cb2461d450bf1771ae51",
                "shasum": ""
            },
            "require": {
                "craftcms/cms": "^3.4.0"
            },
            "type": "craft-plugin",
            "extra": {
                "name": "Contact Form",
                "handle": "contact-form",
                "documentationUrl": "https://github.com/craftcms/contact-form/blob/v2/README.md",
                "components": {
                    "mailer": "craft\\contactform\\Mailer"
                }
            },
            "autoload": {
                "psr-4": {
                    "craft\\contactform\\": "src/"
                }
            },
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Pixel & Tonic",
                    "homepage": "https://pixelandtonic.com/"
                }
            ],
            "description": "Add a simple contact form to your Craft CMS site",
            "keywords": [
                "cms",
                "contact",
                "craftcms",
                "form",
                "yii2"
            ],
            "support": {
                "email": "support@craftcms.com",
                "issues": "https://github.com/craftcms/contact-form/issues?state=open",
                "source": "https://github.com/craftcms/contact-form",
                "docs": "https://github.com/craftcms/contact-form/blob/v2/README.md",
                "rss": "https://github.com/craftcms/contact-form/commits/v2.atom"
            },
            "time": "2022-05-02T22:23:57+00:00"
        },
```

### Steps to reproduce

1. Use Craft 3.7.38
2. Wait for some outdated plugins to appear
3. Update to Craft 3.7.39
4. Update an individual plugin
5. Notice that the backend still displays the old version, even though the new one is installed

### Craft CMS version

3.7.38/3.7.39

### PHP version

PHP 8.0.18

### Installed plugins and versions

- Happens with any plugin

**Comment by brandonkelly** [comment]
This is due to a Composer 2.3 bug we are investigating. Yesterdays we released Craft 3.7.40 which downgrades Composer to 2.2, which doesn’t have the bug.

Unfortunately the Composer bug will affect your ability to update Craft as well, so you’ll need to update to 3.7.40 using the terminal. First open `composer.json` and ensure your `craftcms/cms` constraint begins with an `^` or `~`, or manually change it to `3.7.40`. Then run the following command:

```sh
composer update craftcms/cms
```

**Comment by dgsiegel** [comment]
I've manually set Craft's version to `3.7.40` in `composer.json`, then ran `composer update craftcms/cms`. (I had to delete `composer.lock` due to dependency errors and re-created it with `composer update`).

Now I've updated to `3.7.40` but still got the same problem. 

Btw, my system version is composer is `Composer version 2.3.5 2022-04-13 16:43:00`

**Comment by brandonkelly** [comment]
Sorry… you will need to run `composer update` without the `craftcms/cms` arg.

**Comment by brandonkelly** [comment]
Search for `"name": "craftcms/contact-form"` in `composer.lock`. What version does it say there?

**Comment by dgsiegel** [comment]
> Search for `"name": "craftcms/contact-form"` in `composer.lock`. What version does it say there?

```
        {
            "name": "craftcms/contact-form",
            "version": "2.5.1",
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/craftcms/contact-form/zipball/93a31d4c95aba5109fb1cb2461d450bf1771ae51",
                "reference": "93a31d4c95aba5109fb1cb2461d450bf1771ae51",
                "shasum": ""
            },
            "require": {
                "craftcms/cms": "^3.4.0"
            },
...
```

**Comment by brandonkelly** [comment]
Seems like the right version got pulled in then. But the control panel is showing 2.5.0?

**Comment by dgsiegel** [comment]
Yes, that's seems to be the issue with all plugins. But as I said before, this only started to appear with 3.7.39.

**Comment by brandonkelly** [comment]
Very strange. Maybe try just nuking your entire `vendor/` folder, and running `composer install`.

**Comment by brandonkelly** [comment]
Aha… does your `composer.json` file have this in it? If not, you’ll need to add it:

```json
{
  "config": {
    "allow-plugins": {
      "yiisoft/yii2-composer": true,
      "craftcms/plugin-installer": true
    }
  }
```

**Comment by dgsiegel** [comment]
I do have both of these lines, but both with `false`

```
{
  "config": {
    "allow-plugins": {
      "yiisoft/yii2-composer": false,
      "craftcms/plugin-installer": false
    }
  }
```

I never intentionally changed them, they seem to have been added some time ago by a plugin installation according to my git log.

Anyway, changing both to `true` seems to fix my problem.

**Comment by brandonkelly** [comment]
Ah yeah, so `allow-plugins` was added in Composer 2.2. At some point you (or someone else with access to the repo) must have updated their local Composer, and run `composer update`, and answered `n` at the prompts for whether those plugins should be allowed.
