### ISSUE TITLE
[3.x]: Can't update from 3.7.39 to 3.7.40

### ISSUE THREAD

**Issue by andyra** [craftcms/cms#11092]
### Description

I'm attempting to update from Craft 3.7.39 → 3.7.40 (so that I can upgrade to 4.0!). The Updates page in the Craft control panel suggests I need to update via Composer ("If you are currently running Craft 3.7.39, you will need to perform this update with Composer.")

I went to my project directory and ran `php craft update craft`; this is the output:

```
Fetching available updates ... done
Performing one update:

    - craft 3.7.39 => 3.7.40.1

Create database backup? (yes|no) [yes]:
Backing up the database ... done
Performing update with Composer ... error: Composer\Util\Filesystem::filePutContentsIfModified(): Argument #2 ($content) must be of type string, bool given, called in /vendor/composer/composer/src/Composer/Repository/FilesystemRepository.php on line 165

Output:

Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Lock file operations: 0 installs, 7 updates, 0 removals
  - Downgrading composer/composer (2.3.5 => 2.2.12)
  - Downgrading composer/pcre (3.0.0 => 1.0.1)
  - Upgrading craftcms/cms (3.7.39 => 3.7.40.1)
  - Upgrading symfony/console (v5.4.8 ffe3aed => v5.4.8)
  - Upgrading symfony/finder (v5.4.8 9b630f3 => v5.4.8)
  - Upgrading symfony/process (v5.4.8 597f3ff => v5.4.8)
  - Upgrading symfony/string (v5.4.8 3c061a7 => v5.4.8)
Writing lock file
Installing dependencies from lock file
Package operations: 0 installs, 7 updates, 0 removals
  - Upgrading symfony/process (v5.4.8 597f3ff => v5.4.8): Extracting archive
  - Upgrading symfony/finder (v5.4.8 9b630f3 => v5.4.8): Extracting archive
  - Upgrading symfony/string (v5.4.8 3c061a7 => v5.4.8): Extracting archive
  - Upgrading symfony/console (v5.4.8 ffe3aed => v5.4.8): Extracting archive
  - Downgrading composer/pcre (3.0.0 => 1.0.1): Extracting archive
  - Downgrading composer/composer (2.3.5 => 2.2.12): Extracting archive
  - Upgrading craftcms/cms (3.7.39 => 3.7.40.1): Extracting archive


Revert the Composer changes? (yes|no) [yes]:
```

Composer is on the latest version: 2.3.5

### Steps to reproduce

1. Install Craft  3.7.39
2. Run `php craft update craft`

### Expected behavior

Should update to 3.7.40

### Actual behavior

Asks to revert the Composer changes

### Craft CMS version

3.7.39

### PHP version

8.1.4

### Operating system and version

Darwin 21.4.0

### Database type and version

MySQL 8.0.28

### Image driver and version

GD 8.1.4

### Installed plugins and versions

- Control Panel Nav: 3.0.17
- DigitalOcean Spaces Volume: 1.1.3
- Feed Me: 4.5.0
- GraphQL Authentication: 1.12.3
- Reasons: 2.2.6
- Redactor:  2.10.7
- Super Table: 2.7.1

**Comment by thupsi** [comment]
You actually have to change the craft version to 3.7.40 in your `composer.json` and then run `composer update`

**Comment by zzseba78** [comment]
Question, i someone doesn´t use composer there isn´t a way to update from 3.7.39 to newer versions?

**Comment by japo32** [comment]
> You actually have to change the craft version to 3.7.40 in your `composer.json` and then run `composer update`

This should be in the release notes. The only warning in the release notes is `If you are currently running Craft 3.7.39, you will need to perform this update with Composer.` which isn't really clear.

**Comment by brandonkelly** [comment]
`craft update` uses the same (broken) internal version of Composer that the web installer uses, so the only way to update from 3.7.39 is to use `composer update`.

We’ll get this added to the docs and link the warning in the release notes, but for now, here’s what you need to do:

1. Ensure Composer is installed (run `which composer`). If you don’t have it, you can find installation instructions [here](https://getcomposer.org/download/).

2. Open `composer.json` and check your `craftcms/cms` requirement. It should be set to one of these:

- Something that begins with `^` (e.g. `^3.7.0`, meaning “any version equal to or after 3.7.0, and less than 4.0.0”)
- Somethnig that begins with `~` (e.g. `~3.7.0`, meaning “any version equal to or after 3.7.0, and less than 3.8.0”)
- A specific version number (e.g. `3.3.39`).

If the latter, adjust the constraint to `3.7.40.1`.

Then run `composer update`.

If Craft is installed within a VM or Docker container, you may need to add `--ignore-platform-reqs` so Composer doesn’t error out over an environmental conflict, like a required PHP version mismatch.

**Comment by japo32** [comment]
Thanks @brandonkelly

**Comment by andyra** [comment]
Thanks, @brandonkelly!
