### ISSUE TITLE
`Element::getIsEditable()` no longer available [4.x] 

### ISSUE THREAD

**Issue by johndwells** [craftcms/cms#11094]
### Description

On C3 we conditionally show an "Edit this page" on the front-end for logged in users. To check if the user has access to the current element, we can simply use `element.getIsEditable()`, which is powered by [Element::getIsEditable()](https://github.com/craftcms/cms/blob/release/3.7.41/src/base/Element.php#L2593-L2603).

Unfortunately it appears that this method (as well as [`Element::getIsDeletable()`](https://github.com/craftcms/cms/blob/release/3.7.41/src/base/Element.php#L2616-L2626), their underlying protected methods, as well as some [defined events](https://github.com/craftcms/cms/blob/release/3.7.41/src/base/Element.php#L336-L348)) are all gone in Craft4.

Is this change on purpose? Is there another way to conveniently check for this general permission in C4?

### Craft CMS version

4.0.0.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Yeah it was removed as part of the unified element editor refactor, for being too vague. You can use `element.canSave(currentUser)` instead in Craft 4.
