### ISSUE TITLE
[3.x]: Incorrect timezone when using asArray() in entries query

### ISSUE THREAD

**Issue by ctmaloney** [craftcms/cms#11099]
### Description

When querying entries with [asArray](https://craftcms.com/docs/3.x/entries.html#asarray) the timestamps returned show UTC values but the timezone is set to the Craft timezone.

### Steps to reproduce

1. entry post date = May 4, 2022 11:59pm America/Chicago
2. {% set entry = craft.entries().asArray().one() %}

### Expected behavior

{{ entry["postDate"]|date("M j, Y g:i e") }} == 2022-05-05 04:59 UTC

### Actual behavior

{{ entry["postDate"]|date("M j, Y g:i e") }} == 2022-05-05 04:59 America/Chicago

### Craft CMS version

3.7.37

**Comment by brandonkelly** [comment]
This is working as intended. When you call `asArray()` you’re going to get the raw database data back without any alterations, and Craft stores all dates in UTC.

**Comment by ctmaloney** [comment]
The **timezone** is wrong in the returned value. It isn't set to UTC. So I'm expecting UTC but that isn't want is being returned.

**Comment by brandonkelly** [comment]
Sorry, following you now.

The raw timestamp you get back from the database doesn’t explicitly specify its UTC time zone, so Twig will assume it’s in the system time zone.

You can work around this by appending `UTC` to the DB-provided date:

```twig
{{ "#{entry['postDate']} UTC"|date('M j, Y g:i e') }}
```

That will still return a date in the system time zone by default, but it will at least be the accurate time.

If you want the date returned in UTC, you can use the `timezone` param:

```twig
{{ "#{entry['postDate']} UTC"|date('M j, Y g:i e', timzeone='UTC') }}
```
