### ISSUE TITLE
[4.x]: ErrorHandler doesn't render error and content-type while in devMode

### ISSUE THREAD

**Issue by jordikroon** [craftcms/cms#11108]
### Description

Twig Syntax errors result in errors not as HTML

### Steps to reproduce

1. Add a twig template file
2. Add `{{ dump('test') }` (note missing closing bracket) 

### Expected behavior

![image](https://user-images.githubusercontent.com/2232811/166953873-5112ded8-908d-4491-907c-a17671868e24.png)

### Actual behaviour

![image](https://user-images.githubusercontent.com/2232811/166954070-f0588f4f-764f-4276-9579-5a8081151fea.png)

### Proposed fix

Since the error that is catched in `TemplateResponseFormatter` is only limited to `RuntimeError`, try use the parent class `Error`.

However I don't quite understand why the Format `template` is used. Because the format is "template", it results in the default behaviour of not having a content-type, and the parent class (line 192) not rendering the error. This is due to the fact that the format is not HTML or JSON.

### Craft CMS version

4.0.0.1

### PHP version

8.0

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.1 is out now with the fix for this.

**Comment by jerome2710** [comment]
@brandonkelly I am currently experiencing this issue in 4.0.3 again as well.

**Comment by brandonkelly** [comment]
Craft 4.0.4 is out now with that fix.
