### ISSUE TITLE
[3.x]: Setting unknown property: craft\models\MailSettings::tempVolumeUid

### ISSUE THREAD

**Issue by mijewe** [craftcms/cms#11102]
### Description

I went to the Commerce System Settings page (/admin/commerce/settings/general), and I get an error:
`Setting unknown property: craft\models\MailSettings::tempVolumeUid`

The same error occurs when I go to the Email Settings page (/admin/settings/email)

### Steps to reproduce

1. go to the Email Settings page (/admin/settings/email)
2. see the error message

### Craft CMS version

3.7.40.1

### PHP version

8.0.17

### Operating system and version

Linux 5.10.104-linuxkit

### Database type and version

MySQL 10.3.34

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-16)

### Installed plugins and versions

Blitz	3.12.4
CP Field Inspect	1.4.2
Craft Commerce	3.4.14
Formie	1.5.16
Imager X	v3.5.8
Maps	3.9.3
oEmbed	1.3.15
PayPal Checkout for Craft Commerce	1.3.2.1
Phone Number	1.5.0
Postmark	2.1.0
Redactor	2.10.8
Retour	3.1.71
Sentry SDK	1.1.2
SEOmatic	3.4.30
Super Table	2.7.1
Typed link field	1.0.25
Xero 1.0.4.1

**Comment by brandonkelly** [comment]
Please search for the error in `storage/logs/web.log`, and post the stack trace that is logged after it.

**Comment by mijewe** [comment]
Looks like this was due to a dodgy yaml merge which caused the `tempVolumeUid` field to be somewhere it shouldn't be
