### ISSUE TITLE
[4.x]: Asset Filesystem Slideouts cannot be saved.

### ISSUE THREAD

**Issue by dreamseeker** [craftcms/cms#11103]
### Description

When creating a new asset volume, the Asset Filesystem Slideouts does not display input fields such as "Base Path".
So, it cannot be saved.

However, when I close and reopen Slideouts, it appears.

### Steps to reproduce

1. Install Craft CMS 4.0.0.1.
2. Create a new volume.
3. Select "Create a new filesystem..." from the "Asset Filesystem" select menu.
4. Turn on the "Files in this filesystem have public URLs" toggle switch in the Slideouts.
5. "Base URL" and "Base Path" input fields are not displayed.

<img width="1350" alt="CleanShot 2022-05-05 at 18 31 45@2x" src="https://user-images.githubusercontent.com/548326/166897077-59e90579-d6b9-4dfa-aeb6-f08d52a57cda.png">

### Craft CMS version

Craft Pro 4.0.0.1

### PHP version

8.1.5

### Operating system and version

Linux 5.10.104-linuxkit

### Database type and version

MySQL 8.0.27

### Image driver and version

GD 8.1.5

### Installed plugins and versions

No plugins are enabled.

**Comment by brandonkelly** [comment]
It’s working on my end. Are you getting any JavaScript errors?

**Comment by dreamseeker** [comment]
Yes.
The following JavaScript error was displayed.

```
ReferenceError: Can't find variable: Vue
```

![CleanShot 2022-05-06 at 16 00 54@2x](https://user-images.githubusercontent.com/548326/167082988-68fd9465-8b30-4169-860c-6ed0f779ef1d.png)

And the error only occurred if I had defined different subdomains for "resourceBasePath" and "resourceBaseUrl" in `config/general.php`.

```
  'aliases' => [
    '@web'     => 'https://craft4.test/',
    '@webroot' => '/var/www/html'
  ],

  'resourceBasePath'  => 'https://cpresources.craft4.test/',
  'resourceBaseUrl'   => '/var/www/cpresources',
```

There was no error when the "cpresources" directory was created in the same domain.

**Comment by brandonkelly** [comment]
Probably due to crossdomain restrictions. Do you see any console warnings before that?

**Comment by dreamseeker** [comment]
No, there are no other warnings.
And I have already set Access-Control-Allow-Origin.

However, I would like to close this issue as it seems to be a problem dependent on my environment.

If I can determine the cause of the problem, please let me discuss it again.

Thanks.
