### ISSUE TITLE
Garnish menu btn still active even with `disabled` attribute in admin table

### ISSUE THREAD

**Issue by BenParizek** [craftcms/cms#11128]
### What happened?

Just a minor bug to note in the latest Commerce 4.0.0:

## /admin/commerce/promotions/sales

![CleanShot 2022-05-06 at 11 33 13@2x](https://user-images.githubusercontent.com/309735/167165196-eb94d127-2bc8-4a2f-9add-af54f47a58e3.png)

### Craft CMS version

4

### Craft Commerce version

4

### PHP version

8

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
@nfourtythree There aren’t any references to `disabled` in `Garnish.CustomSelect` or `Garnish.DisclosureMenu`, so this is probably a case of Commerce setting the `disabled` class on the button, which will give it the reduced-opacity styling we apply across the board via `.disabled`, though the component itself has no support for it. So probably more of a Commerce bug, or you can PR support for `disabled` to the component in use.
