### ISSUE TITLE
[3.7.38]: Asset Restrict Files no longer supports CSV

### ISSUE THREAD

**Issue by DowleyDeveloped** [craftcms/cms#11125]
### Description

Previously I was able to select an Assets field and restrict the File Kind to 'Excel' which also allowed the upload of CSV files. However this no longer seems to be the case. I have a plugin which converts CSV to Tables for one of my clients and they can no longer really use it.

### Steps to reproduce

1. Create an Assets Field and Restrict the File Kind to Excel.
2. Try and Upload a CSV file

### Expected behavior

CSV File should be selectable/uploaded

### Actual behavior
Error displays

### Craft CMS version

3.7.38

### PHP version

8

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Pretty sure we’ve never had an “Excel” file kind.

You can define custom file kinds using the [extraFileKinds](https://craftcms.com/docs/3.x/config/config-settings.html#extrafilekinds) config setting, though. Maybe you’ve used that to create an “Excel” one?

**Comment by DowleyDeveloped** [comment]
Apologises I meant File Type! There is an Excel Option here:
<img width="242" alt="Screenshot 2022-05-07 at 11 20 55" src="https://user-images.githubusercontent.com/24968042/167250201-8058373a-3b16-4dc6-8b41-69e34687c5cf.png">
 
Which did used to accept CSV but nothing seems to accept these anymore. I was wondering if this was a security feature?

**Comment by brandonkelly** [comment]
Sorry, not sure how I missed that 🙃 

Although I just looked at the Git history for `craft\helpers\Assets::_buildFileKinds()` and we never included `csv` in there, dating back to 3.0.

**Comment by DowleyDeveloped** [comment]
Oh that’s really odd, as they definitely could select CSVs before. I can probably work around this so it’s not a deal breaker, thank you!
