### ISSUE TITLE
[3.x]: A lot of field are not translated in fr-CA

### ISSUE THREAD

**Issue by stephanedemotte** [craftcms/cms#11139]
### What happened?

A lot of fields are not translated in fr-CA

https://github.com/craftcms/cms/blob/develop/src/translations/fr-CA/app.php

We still have the english version, Can we force user cp to use the FR instead of the FR-Canada ?

We have set the default panel language to 'fr_CA' but now we prefere to use the 'fr' version because of this missing fields, can we change language by 'user group' ?

Thank you !

### Craft CMS version

3.7.41

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Looks like a couple of languages’ translations had been prematurely approved before they were actually translated. New round of translations has been ordered to fill in the gaps. I‘ll update this once they’re in.

**Comment by brandonkelly** [comment]
This is resolved now for the next v3 and v4 releases (#11270, #11271).
