### ISSUE TITLE
[4.x]: Single column asset field overlaps adjacent columns

### ISSUE THREAD

**Issue by pixelmachine** [craftcms/cms#11133]
### What happened?

An asset field limited to a single column will overlap instead of wrapping:

![Screen Shot 2022-05-06 at 16 59 19](https://user-images.githubusercontent.com/1082223/167216175-c2bba6b1-3565-484e-bb01-17db14c1cc52.png)

![Screen Shot 2022-05-06 at 16 59 05](https://user-images.githubusercontent.com/1082223/167216232-3f0ddfa3-97dd-4185-8467-f0d967b827dc.png)

### Craft CMS version

4.0.1

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.2 is out now with the fix for this.
