### ISSUE TITLE
[4.x]: Missing category name in user permissions

### ISSUE THREAD

**Issue by pixelmachine** [craftcms/cms#11132]
### What happened?

User permissions selects don't show category group names, instead:
`Category Group - {name}`

![cats](https://user-images.githubusercontent.com/1082223/167215335-d8edc7cd-3e01-4144-a310-619272510e3f.png)

This happens in individual user prefs and in category group settings.

### Craft CMS version

4.0.1

**Comment by brandonkelly** [comment]
Whoops, thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.2 is out now with the fix for this.
