### ISSUE TITLE
[4.x]: Logs with web.WARNING when devMode is disabled

### ISSUE THREAD

**Issue by martinleveille** [craftcms/cms#11141]
### What happened?

With `devMode` enabled, you normally get these lines for each page load in the log files:

```
2022-05-07 14:01:11 [web.INFO] [yii\db\Connection::open] Opening DB connection: mysql:host=127.0.0.1;dbname=craft40;port=3306 {"memory":1604768}                                                                  
2022-05-07 14:01:11 [web.INFO] [yii\web\Session::open] Session started {"memory":2396792}                                                                                                                         
2022-05-07 14:01:11 [web.INFO] [application] Request context:
```

But when you disable `devMode`, you get a single `web.WARNING` line for each page load:

```
2022-05-07 14:06:21 [web.WARNING] [application] Request context:
```

Should this line be a `web.INFO` when `devMode` is disabled ?

### Craft CMS version

4.0.1

### PHP version

8.0.18

### Operating system and version

Darwin 21.4.0

### Database type and version

MySQL 8.0.28

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-30)

### Installed plugins and versions

No plugins

**Comment by mattgrayisok** [comment]
As this context message is being logged for every request (and it's also a WARN so it's being logged twice for `CRAFT_STREAM_LOG=1` due to https://github.com/craftcms/cms/issues/11189) it's creating a lot of log noise for high traffic sites.

I imagine it just needs removing altogether when devMode is false.

**Comment by martinleveille** [comment]
@timkelty Thanks for your answer and gist examples, but I've just done a clean install and only get `[web.WARNING] [application] Request context:` lines without anything else when `devMode` is disabled.

https://user-images.githubusercontent.com/534656/167962115-ed8e4da5-38b4-4e67-aed5-b63a43232800.mp4

**Comment by timkelty** [comment]
Thanks for the video @martinleveille. You're absolutely right. I did some further debugging with @mattgrayisok and am able to reproduce.

We'll have a fix out asap!

**Comment by timkelty** [comment]
@martinleveille @mattgrayisok I have this fixed [here](https://github.com/craftcms/cms/pull/11216)

If you could try `dev-fix-log-filtering` and confirm it it fixed for you, that would be appreciated!

**Comment by brandonkelly** [comment]
Craft 4.0.3 is out now with that fix.
