### ISSUE TITLE
[4.x]: Empty query string in preview target URLs

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#11159]
### Description

Preview target URLs will always have an `?` (i.e. an empty query string) appended to them, even if there isn't a query string in the "URL Format" setting for that preview target.  

### Steps to reproduce

1. Create a section and add a preview target to it with a "URL Format" that doesn't include a query string – for example, `{url}`
2. Create an entry in that section
3. Click the "View" button in entry's edit page to open the preview target URL in a new browser tab
3. Observe that the URL has an empty query string (i.e. `?`) appended to it

### Expected behavior

No question mark appended to the URL unless the preview target's URL format has a query string.

### Actual behavior

There's a question mark appended to the URL even if there isn't a query string in the preview target's URL format.

### Craft CMS version

4.0.1

### PHP version

8.1.4

### Operating system and version

macOS 12.3.1

### Database type and version

MySQL 5.7.37

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.2 is out now with the fix for this.
