### ISSUE TITLE
Show modal to confirm saving of new entries in order to prevent accidental initial publication

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1116]
> Created by: Rolf-Juergen Hornasek (rolf.juergen.hornasek@gmail.com) on 2015/08/20 17:49:24 +0000
> Votes at time of UserVoice import: 3

-----------------------------------

Editors can accidently publish an entry without knowing. "Save" can be misleading as it may publish an entry depending on other attributes such as status, publication and expiration date. When the "Save" is about to trigger a publication notify the user that the entry is about to go live. This is especially important when working with confidential information

**Comment by sev-signal** [comment]
hi @angrybrad did you implement any workaround for this?

**Comment by brandonkelly** [comment]
The publishing experience has changed quite a bit since that FR was posted 5 years ago. There’s an active discussion about how the current UX can be improved in Craft 4: #5661
