### ISSUE TITLE
[3.7.41]: Trying to save a number field with a comma (,) in language "Deutsch (Schweiz)" leads to "is not a numeric value" exception

### ISSUE THREAD

**Issue by benediktblank** [craftcms/cms#11164]
### Description
When the user account is setup with language "Deutsch (Schweiz)" and you try to save a number field with a number like "900,00" you get an exception "'900,00' is not a numeric value."

### Steps to reproduce

1. Create a new section with a number field.
![image](https://user-images.githubusercontent.com/69143768/167438437-949f58aa-4dff-4d80-85f8-c390604165da.png)

2. Change the language of your backend user to "Deutsch (Schweiz)"
![image](https://user-images.githubusercontent.com/69143768/167438576-64a309c7-5306-4720-b390-2179d6992911.png)

3. Try to save a new entry with 900,00 as value in the number field
![image](https://user-images.githubusercontent.com/69143768/167439025-fd435748-5afb-489e-b9e9-8b80d6e66daa.png)
You can see here already, that the draft auto save also already failed.

5. You get an exception "Invalid Argument – yii\base\InvalidArgumentException" and "'900,00' is not a numeric value."
![image](https://user-images.githubusercontent.com/69143768/167438750-23693207-9d96-470d-ac8d-7f3fbd826213.png)

### Expected behavior
Either the error is displayed as a regular error with form/field validation or it's just saved without any issues. But a system breaking exception is not the desired outcome.

### Actual behavior
The site breaks on save and a stack trace with error message is shown.

### Craft CMS version

3.7.41

### PHP version

8.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.
