### ISSUE TITLE
[4.x]: Not possible to expand the children of a draft category

### ISSUE THREAD

**Issue by gcamacho079** [craftcms/cms#11186]
### Description
When a (draft) category parent is collapsed, I'm unable to expand to see the child categories again unless I reload the page.

I've tested with other categories and am able to expand the children without issues. It only seems to happen when the parent category is a draft.

### Steps to reproduce
To recreate:

1. Create a new draft category
2. Go to the category index (with the **Structure** view) and create a child category under the draft category
3. Collapse the category, then try expanding it again

### Expected behavior
The children rows should load underneath the parent category

### Actual behavior
A loading spinner will appear, but no additional rows will be loaded underneath.

<img width="786" alt="Screenshot showing an expanded parent category with no children underneath" src="https://user-images.githubusercontent.com/17525979/167708313-afc395bd-ce1c-43c7-8914-676c9a879dca.png">

The response object shows that all the HTML values in the `data` key are empty:
```
"data": {
  "html": "",
  "headHtml": "",
  "bodyHtml": ""
},
```

### Craft CMS version

4.01

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Was also able to reproduce this on Structure sections (in Craft 3 + 4). Fixed for the next v3 and v4 releases.
