### ISSUE TITLE
[3.x]: Unable to eager load multiple transforms with srcsets

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/cms#11209]
### Description
Update: I made a pull request https://github.com/craftcms/cms/pull/11210.

Essentially what I'm trying to do is to eager load 3 different transforms with a `2x` srcset:
* `cardIndexLarge` with `2x`
* `cardIndexMedium` with `2x`
* `cardIndexSmall` with `2x`

In order to eager load the base transforms I wrote the following:
```twig
{% set query = craft.entries.section('blogArticles').orderBy('postDate').limit(8).with([
    ['coverImage', {withTransforms: ['cardIndexLarge', 'cardIndexMedium', 'cardIndexSmall']}],
]) %}
```

As far as I'm aware, the current transform eager loading implementation only supports a single transform when combined with eager loading srcsets. This is to us the last step to achieving full eager loading!

When I add `2x` as the last item in the transforms array it will only eager load `cardIndexSmall` with 2x. However if I add the srcset after `cardIndexLarge` it will actually overwrite `cardIndexMedium` and `cardIndexSmall` to the `cardIndexLarge 2x` variant.

The overwrites happen because the `$sizeValue, $sizeUnit` at 461 are being remembered from the previous loop:
https://github.com/craftcms/cms/blob/a7b735321468a6cf7d73a0eb582aa610eb5fc390/src/services/AssetTransforms.php#L

In order to fix this I added `unset($sizeValue, $sizeUnit);` to the end of the foreach loop, this would allow me to apply srcset eager loading to multiple transforms like this:
```twig
{% set query = craft.entries.section('blogArticles').orderBy('postDate').limit(8).with([
    ['primaryImage', {withTransforms: ['cardIndexLarge', '2x', 'cardIndexMedium', '2x', 'cardIndexSmall', '2x']}],
]) %}
```

Apart from the `format` it would eager load all srcsets correctly (that might be a different issue?):
<img width="418" alt="Screenshot 2022-05-11 at 20 58 17" src="https://user-images.githubusercontent.com/2922378/167925706-9a5d6f19-95ae-447c-a7e2-1ad38bccbbf4.png">

Unless the format is applied from the base transform during eager loading the srcset transforms will still be requested in every loop:
<img width="401" alt="Screenshot 2022-05-11 at 20 58 55" src="https://user-images.githubusercontent.com/2922378/167925817-7dc28558-016e-475b-a1f8-4778db3b51dd.png">

I have validated this fix will continue to work even when adding multiple srcsets like this:
```twig
{% set query = craft.entries.section('blogArticles').orderBy('postDate').limit(8).with([
    ['primaryImage', {withTransforms: ['cardIndexLarge', '2x', '3x', 'cardIndexMedium', '2x', 'cardIndexSmall', '2x']}],
]) %}
```

### Craft CMS version

3.4.41

### PHP version

8.0.17

### Operating system and version

Linux 5.10.104-linuxkit

### Database type and version

MySQL 8.0.28

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-16)

**Comment by brandonkelly** [comment]
This is already possible. You just need to add `2x` after each of the normal transforms:

```twig
{% set query = craft.entries()
  .section('blogArticles')
  .orderBy('postDate')
  .limit(8)
  .with([
    ['coverImage', {
      withTransforms: ['cardIndexLarge', '2x', 'cardIndexMedium', '2x', 'cardIndexSmall', '2x']
    }],
  ]) %}
```

**Comment by Wiejeben** [comment]
Unfortunately that doesn't seem to work:

Twig:
```twig
{% set query = craft.entries.section('blogArticles').orderBy('postDate').limit(8).with([
    ['primaryImage', {withTransforms: ['cardIndexLarge', '2x', 'cardIndexMedium', '2x', 'cardIndexSmall', '2x']}],
]) %}
```

After that I `dd()` the `$indexCondition` variable that is used to query for the indexes:
![image](https://user-images.githubusercontent.com/2922378/168235837-e3ed38c5-8b05-4702-bd15-11cec2131f25.png)

This happens because the `AssetsHelper::parseSrcsetSize($transform);` fails on `cardIndexMedium`, however `$sizeValue` and `$sizeUnit` still exist from the previous iteration.

**Comment by brandonkelly** [comment]
Sorry, there was a bug that prevented this from working as intended. Fixed now for the next v3 and v4 releases.

**Comment by brandonkelly** [comment]
3.7.43 and 4.0.3 are out now with that fix.
