### ISSUE TITLE
[4.x]: Table - Hide delete row button when min rows = max rows + default

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#11211]
### Description

I created a table for some settings for a site alert. The table has minRows = 1, maxRows = 1 with a default row.

In this case the delete button should not be shown because the current number of rows = minRows

Entry Field:

![Screen Shot 2022-05-12 at 11 29 11 am](https://user-images.githubusercontent.com/25124/167973843-32ff2ee6-3be8-4301-aa96-3eeca8fac30c.png)

Field Config:

![image](https://user-images.githubusercontent.com/25124/167973912-099f7cc1-756b-421d-895c-94cfae5e86b5.png)

### Craft CMS version

4.0.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
This was a v4 regression. Fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 4.0.3 is out now with that fix.
