### ISSUE TITLE
[4.0.2]: File systems do not evaluate alias @webroot correctly

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#11219]
### Description

We have file systems set up with a `@webroot` alias, which worked in 4.0.1, but stopped working in 4.0.2

A base path is entered as `@webroot/files/images`, and is now converted to backslashes on save, which is probably wrong.

![image](https://user-images.githubusercontent.com/60010597/168265781-fd313575-d1e7-4fd4-ba30-d7334ba8a024.png)

New images get created in a `@webroot` folder.

![image](https://user-images.githubusercontent.com/60010597/168266217-1994d2e8-6b79-4c48-b374-ddb6ca3c9f61.png)

### Steps to reproduce

On Windows:

1. Set up a file system with a base path starting with `@webroot` 
2. Upload an image
3. Inspect web folder

### Expected behavior

Like before...

### Actual behavior

Files are stored in a wrong location

/Mel

### Craft CMS version

4.0.2

### PHP version

8.1.5

### Operating system and version

Windows 10 Pro

### Database type and version

MySQL 5.7.14

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-18)

### Installed plugins and versions

None

**Comment by angrybrad** [comment]
@wsydney76 Pretty sure the fix here https://github.com/craftcms/cms/tree/feature/fix-asset-index-windows will resolve this issue as well if you want to test.

To get it early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-feature/fix-asset-index-windows as 4.0.2",
  "...": "..."
}
```

Then run `composer update` and let me know how you get along.

**Comment by wsydney76** [comment]
@angrybrad Just tested and all went well.

Thanks, closing.

**Comment by sprngLf** [comment]
> ```json
> "craftcms/cms": "dev-feature/fix-asset-index-windows as 4.0.2"
> ```

Thanks! I had the same problem.

**Comment by brandonkelly** [comment]
That PR has been merged for the next release. Until then, you can use `dev-develop as 4.0.2` an your `craftcms/cms` requirement.

**Comment by brandonkelly** [comment]
Craft 4.0.3 is out now with that fix.
