### ISSUE TITLE
Allow for Rich Text Blocks to be RTL even with locales are turned off

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#1121]
> Created by: Keith Mancuso (keith@familiar-studio.com) on 2015/03/11 01:23:26 +0000
> Votes at time of UserVoice import: 3

-----------------------------------

We are working on a yiddish studies journal site and they are planning to write blog posts in english but that would feature translated texts as matrix blocks

see a snippet from the comp here:
https://www.dropbox.com/s/6t0abycgb3xxnbj/Screenshot%202015-06-29%2012.49.47.png?dl=0

It didnt seem to make sense to use the built in locales and translating as we arent having the rest of the article translated (or any other elements on the site)

I was hoping i could just add direction: 'rtl' to a redactor config and then set a field that uses that config but it seems thats being overwritten by default the Craft.orientation settings.

Not a common use case for sure but would be nice if it were possible.  Seems like for now im going to setup a plugin with a custom redactor based fieldtype

**Comment by mark-chief** [comment]
+1

**Comment by brandonkelly** [comment]
This is already possible. Just add the following to your Redactor config:

```json
"direction": "rtl"
```

(cc @keithmancuso)
