### ISSUE TITLE
[4.x]: Custom entry title required error thrown on default title

### ISSUE THREAD

**Issue by JeanLucEsser** [craftcms/cms#11227]
### Description

Let's say you have a custom title for an entry: {firstname} {lastname}
Both fields being required.

Try saving the entry with both fields empty, and the error is thrown on the default entry title making it visible.

### Steps to reproduce

1. Design an entry with a custom title {firstname} {lastname}
2. Create a new entry with both fields empty
3. Save the entry to throw the error message

### Expected behavior

Shows required error on both firstname and lastname fields only.

### Actual behavior

Shows required error on all required fields including the hidden default title making it visible to the author.

### Craft CMS version

4.02

### PHP version

8.1.3

### Operating system and version

MacOS

### Database type and version

MariaDB

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
There’s not really a clear understanding of what your Title Format actually means – it’s a Twig template that is parsed by Twig, and basically a black box outside of Twig. So Craft has no way of knowing _why_ the Title field was blank; it only knows that it is blank and should be set to something. So in the event that there’s a validation error, we just temporarily show the Title field (read-only).

I think in the long run, this will be solved if we have a place to show a full error summary, separately from the individual field UIs. At that point we could list “Title is required” there, and continue to not show the Title field.
