### ISSUE TITLE
[3.x]: Cannot create Craft project with composer

### ISSUE THREAD

**Issue by lthurston** [craftcms/cms#11223]
### Description

Running `composer create-project craftcms/craft . X` with any 3 version  replacing the X fails with: Could not find package craftcms/craft with version X. This seems like a Composer bug, but I wanted to bring it to your attention in case you have any control over it.

### Steps to reproduce

1. Run the above command in Composer 1 or Composer 2

### Expected behavior

Composer can located the package version and install Craft 3

### Actual behavior

```
> [project_craft stage-0 11/11] RUN composer create-project craftcms/craft . v3.x-dev     && cp composer.json composer.base:
#0 0.497 Creating a "craftcms/craft" project at "./"
#0 0.856 Info from https://repo.packagist.org: #StandWithUkraine
#0 0.973
#0 0.977 In CreateProjectCommand.php line 438:
#0 0.977
#0 0.977   Could not find package craftcms/craft with version v3.x-dev.
```

### Craft CMS version

3.x

### PHP version

7.3

### Operating system and version

OSX

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
`craftcms/craft` is a different package than `craftcms/cms`, and is versioned separately. Version 1.x will give you Craft 3; version 2.x will give you Craft 4.
