### ISSUE TITLE
[4.x]: Not possible to add custom fields as table columns in asset element index sources

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#11222]
### Description

It's not possible to add custom fields (or the new native Alternative Text field) to asset element index sources, only asset model attributes.

<img width="1236" alt="CleanShot 2022-05-14 at 00 27 02@2x" src="https://user-images.githubusercontent.com/298510/168397023-6f3a7e4d-c358-4416-8eee-c0c2e0dc849c.png">

### Steps to reproduce

1. Add a (previewable) custom field to a volume
2. Select the volume in the assets element index.
3. Click the "Customize" cogwheel
4. Notice that the custom field is not in the "Table Columns" checkbox group

### Expected behavior

The "Table Columns" checkbox group for asset sources should include previewable custom and native fields.

### Actual behavior

The "Table Columns" checkbox group for asset sources does not include previewable custom and native fields, only attributes native to asset elements.

### Craft CMS version

4.0.2

### PHP version

8.14

### Operating system and version

macOS 12.3.1

### Database type and version

MySQL 5.7.37

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-29)

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Thanks for pointing those out! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.3 is out now with that fix.
