### ISSUE TITLE
[4.x]: Upload Button not Displayed in Asset Selection Modal

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#11228]
### Description
Upload button not displayed on file selection modal.

### Steps to reproduce

1. Create a new filesystem
2. Create a new volume that references the filesystem
3. Create a new field that points to the volume
4. Add the new field to a globalset (uncheck "Allow uploading directly to the field")
5. Navigate to the global set and click on the "Selection Label" to select files
6. Modal is displayed without the upload button in the bottom left

To get the button to appear....
1. Manually upload a file (e.g. image file) to the filesystem location
2. Go to utilities and click on "asset indexes" and reindex the associated volume
3. Return to the globalset and and click on the "Selection Label" to select files 
4. Modal is displayed now with the option to upload 

### Expected behavior
Upload button should be displayed in the file selection modal

![CleanShot 2022-05-15 at 23 31 54@2x](https://user-images.githubusercontent.com/2505643/168475524-5da68240-4f37-40ac-a3d2-78c14817a8f0.png)

### Actual behavior
Upload button is not displayed in the file selection modal

<img width="596" alt="CleanShot 2022-05-15 at 23 14 28@2x" src="https://user-images.githubusercontent.com/2505643/168475202-c6f84185-1c6d-4a38-bf59-9f19b56420bd.png">

### Craft CMS version

4.0.2

### PHP version

8.1

### Installed plugins and versions

-

**Comment by richhayler** [comment]
I had a incorrectly formed twig variable in the sub folder path configured for the field. Once this was correctly the modal worked as expected.

**Comment by brandonkelly** [comment]
Glad you got it sorted!
