### ISSUE TITLE
[4.x]: Edit element hooks

### ISSUE THREAD

**Issue by ryssbowh** [craftcms/cms#11224]
### Description

I see the template/view to edit elements has been rewritten in Craft 4. I don't see a way to add custom content to the sidebar details anymore, I used `cp.categories.edit.details` before for example.

Is there another alternative now ? I can see the new hook `cp.elements.element` [there](https://craftcms.com/docs/4.x/extend/template-hooks.html#control-panel-template-hooks) but that only allows to modify context right ? Does that mean we can't do that anymore ?

Thank you

### Craft CMS version

4.0.1

### PHP version

8.0.15

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
The [ElementsController::EVENT_DEFINE_EDITOR_CONTENT](https://docs.craftcms.com/api/v4/craft-controllers-elementscontroller.html#event-define-editor-content) event can be used instead.

(Mentioned in the plugin upgrade guide [here](https://craftcms.com/docs/4.x/extend/updating-plugins.html#template-hooks).)

**Comment by ryssbowh** [comment]
@matfish2 I looking to add to metadata also, managed through this :

```
Event::on(Entry::class, Element::EVENT_DEFINE_SIDEBAR_HTML, function(DefineHtmlEvent $e) {
      $e->html .= 'hello';
});
```
If that helps.

This works for `Entry`, `Category` and `Asset`.

It doesn't for `User` though ?

I was also using `cp.globals.edit.content` to edit a global content area in Craft 3, I tried the [ElementsController::EVENT_DEFINE_EDITOR_CONTENT](https://docs.craftcms.com/api/v4/craft-controllers-elementscontroller.html#event-define-editor-content) event on globals but it's not triggered.

**Comment by ryssbowh** [comment]
And for Users and Globals, the hooks from Craft 3 are still there :

```
Craft::$app->view->hook('cp.users.edit.details', function (array &$context) {
    return \Craft::$app->view->renderTemplate('themes/cp/element-shortcuts', [
        'element' => $context['user'],
        'showBlocks' => false
    ]);
});
Craft::$app->view->hook('cp.globals.edit.content', function (array &$context) {
    return \Craft::$app->view->renderTemplate('themes/cp/element-shortcuts', [
        'element' => $context['globalSet'],
        'extraClass' => 'globals',
        'showBlocks' => false
    ]);
});
```

**Comment by mmikkel** [comment]
@ryssbowh It's because globals and users aren't using the Craft 4 unified element editor yet. They probably will, at some point, but for now you'll need to use those template hooks.

@matfish2 There's also the `Element::EVENT_DEFINE_META_FIELDS_HTML` event, which I use in my [CP Field Inspect plugin](https://github.com/mmikkel/CpFieldInspect-Craft/blob/master/src/CpFieldInspect.php#L143).

**Comment by tudorradubarbu** [comment]
@mmikkel Your solution really works! Thank you! This should defo be in the documentation
