### ISSUE TITLE
[4.x]: Invalid utility ID: upgrade

### ISSUE THREAD

**Issue by lopugit** [craftcms/cms#11232]
### Description
I upgraded a Craft 3 project to Craft 4 by updating all composer dependencies to their versions liststed in the Craft 4 Upgrade guide utilities page, then set craftcms/cms to v ^4.0.0 and ran composer update. 

When logging into site.site/admin I got the error 

![Screen Shot 2022-05-16 at 3 01 05 pm](https://user-images.githubusercontent.com/13629190/168522887-1a6ddf09-85a4-4666-9373-3b993e586f1c.png)

I uninstalled codemirror and nethooks before updating

![Screen Shot 2022-05-16 at 10 22 13 am](https://user-images.githubusercontent.com/13629190/168522958-e2c783ab-0917-4942-9388-0733db9f8138.png)

### Steps to reproduce

1. Have a craft 3 project, update all dependencies based on Craft 4 Update guide versions
2. Run composer update and go to /admin login

### Expected behavior
Craft 4 is installed

### Actual behavior
Invalid utility ID: upgrade error

### Craft CMS version

4.0.0

### PHP version

8.1.5

### Operating system and version

OSX 11.4

### Database type and version

MySQL 8.0.27

### Installed plugins and versions

-
```
        "craftcms/aws-s3": "2.0.0",
        "craftcms/cms": "^4.0.0",
        "craftcms/redactor": "3.0.0",
        "sebastianlenz/linkfield": "2.1.3-rc",
        "spicyweb/craft-neo": "3.0.4",
        "studioespresso/craft-scout": "3.0.0",
        "verbb/field-manager": "3.0.0-beta.1",
        "verbb/navigation": "2.0.0",
        "verbb/super-table": "3.0.0-beta.3",
        "vlucas/phpdotenv": "^5.4.0"
```

**Comment by brandonkelly** [comment]
Sounds like you are trying to go to `/admin/utilities/upgrade` (the URI for the Craft 4 Upgrade utility in Craft 3), which isn’t available in Craft 4. Just change the URI in your browser to `/admin/dashboard` to visit the Dashboard.
