### ISSUE TITLE
[4.x]: Base URL is not a valid URL

### ISSUE THREAD

**Issue by jan-dh** [craftcms/cms#11234]
### Description
Trying to update the Base URL on a site. I have this set in my `.env` file with the value `https://website.ddev.site/` but I can't save this because I get an error: 
```Base URL is not a valid URL. ( https://website.ddev.site/)```

### Steps to reproduce

1. Set the .env variable $BASE_URL to `https://website.ddev.site/`
1. Try to save the site.

### Expected behavior
Site being saved

### Actual behavior
I get an error. Funny thing is, when trying to put the value directly in the input (not using the .env file), this works (meaning, I can save the site entry).

### Craft CMS version

4.0.2

### PHP version

8.1.5

### Operating system and version

Linux 5.10.104-linuxkit

### Database type and version

MySQL 10.3.34

### Image driver and version

Imagick 3.6.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Looks like maybe there’s an extra space before the `$`.

**Comment by jan-dh** [comment]
Ok, I'm dumb. That was indeed the issue, thanks!
