### ISSUE TITLE
[4.x]: Matrix field with one block type and minimum and maximum block types doesn't work as expected

### ISSUE THREAD

**Issue by mikesnoeren** [craftcms/cms#11233]
### Description
When setting the minimum and maximum blocks for a matrix field with only one block type in Craft 4 they will not work as expected and completely renders the field useless.

### Steps to reproduce

1. Create a Matrix field with one block type
2. Set the minimum and maximum blocks to 1
3. Add the field to a section
4. Navigate to the section and see for yourself.

### Expected behavior
I would expect my matrix field to just be a 'static' field when there's only one block type available. This is the same behaviour the matrix fields have in Craft 3.

### Actual behavior
When only having one block type available it doesn't show that block by default, it also doesn't show the block selection menu, rendering the field useless.

### Craft CMS version

4.0.2

### PHP version

8.1.5

### Operating system and version

Linux 5.10.47-linuxkit

### Database type and version

MySQL 8.0.19

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- Dumper 3.0.0
- Elements Panel 2.0.0
- Redactor 3.0.0
- SEO 4.0.0

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.3 is out now with that fix.
