### ISSUE TITLE
[4.x]: Can't recreate entry permissions like in 3.7

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#11249]
### Description

We have permissions for a user set up like this in Craft 3.7:

![image](https://user-images.githubusercontent.com/60010597/168826088-92920ad4-5e4c-447d-a9f1-078a894d666a.png)

which allows a user to create a (public) draft for other authors entries, but not publish them, needing review/publish by the original author.

![image](https://user-images.githubusercontent.com/60010597/168826678-60c93903-0330-4827-b95d-d97ab101e9f8.png)

Could not recreate that in 4.0, there is no `Edit other authors’ entries` permission any more.

This setup:

![image](https://user-images.githubusercontent.com/60010597/168827014-b5c711f1-d524-4570-aa1b-4ae10d088d1e.png)

leads to a completely locked edit screen without any possible actions

this:

![image](https://user-images.githubusercontent.com/60010597/168828689-92c25450-0074-425a-a40b-5b0149d6df49.png)

allows publishing the entry

![image](https://user-images.githubusercontent.com/60010597/168828788-51158891-b3a7-44d6-af10-1994b74488f5.png)

### Steps to reproduce

see above

### Expected behavior

like in 3.7, allow editors to create a craft, but not to publish it

### Actual behavior

Don't see a chance to support that workflow in 4.0

/Mel

### Craft CMS version

4.0.2

### PHP version

8.1.5

### Operating system and version

Windows 10

### Installed plugins and versions

none

**Comment by brandonkelly** [comment]
The plan was to let view-only users create drafts of the entry, which another user with save permissions could review and apply to the entry. I could have sworn that was already in place, but apparently not. Just fixed that for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.3 is out now with that change. Thanks again!
