### ISSUE TITLE
[4.x]: When I was installing Craft 4 locally using MAMP I was not asked for the database connection information. I had to find the required docs then, provide the necessary data to the .env file so the install could finally install properly. I'm guessing that there needs to be more work on the error checking for the database connection during the install process. 

### ISSUE THREAD

**Issue by Copula-tech** [craftcms/cms#11245]
### Steps to reproduce

1.

### Craft CMS version

4.0.2 (Solo)

### PHP version

8.0.8

### Operating system and version

Darwin 21.4.0

### Database type and version

MySQL 5.7.34

### Image driver and version

GD 8.0.8

### Installed plugins and versions

-

**Comment by Wiejeben** [comment]
Craft should redirect you to the setup screen automatically when going to your CP url (default is /admin), this will provide you with a setup to apply database credentials etc.

**Comment by brandonkelly** [comment]
What @Wiejeben said.

**Comment by wsydney76** [comment]
@brandonkelly Can confirm that going to /admin does NOT ask for database connection details.

The sequence is: 

* Install Craft CMS ->
* Confirm License
* Create your account
* Setup your site
* Install failed

/Mel

**Comment by brandonkelly** [comment]
@wsydney76 It will only ask for DB credentials if a DB connection couldn’t be established to begin with. Just tested that’s still working as expected. Maybe your `.env` file already had the correct settings in place?

Search your latest `storage/logs/web-XXXX-XX-XX.log` file for `[web.ERROR]`. It should explain why the install failed for you.

**Comment by wsydney76** [comment]
@brandonkelly 

.env is just the copy of .env.example

```
CRAFT_DB_DRIVER=mysql
CRAFT_DB_SERVER=127.0.0.1
CRAFT_DB_PORT=3306
CRAFT_DB_DATABASE=
CRAFT_DB_USER=root
CRAFT_DB_PASSWORD=
CRAFT_DB_SCHEMA=public
CRAFT_DB_TABLE_PREFIX=
```

These are by chance the exact settings that Laragon uses by default, so a connection could be established, but there is no database selected:

```
2022-05-19 17:37:57 [web.INFO] [craft\db\MigrationManager::migrateUp] Applying Install {"memory":1586000} 
2022-05-19 17:37:57 [web.ERROR] [craft\db\MigrationManager::migrateUp] Failed to apply Install (time: 0.001s). Output:
    > create table {{%addresses}} ...Exception: SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected
```

Using invalid settings like `CRAFT_DB_PORT=3309` or `CRAFT_DB_USER=noroot`:

![image](https://user-images.githubusercontent.com/60010597/169363398-b9582dbf-a475-4d3f-b6a6-b3ff211a0dde.png)

**Comment by brandonkelly** [comment]
Aha! There was indeed a bug, where the DB connection screen wouldn’t show if a connection could be established but no database was specified.

Fixed for the next v3 and v4 releases!

**Comment by wsydney76** [comment]
@brandonkelly Thanks.

Updated to dev-develop, calling `/admin` now throws an error:

![image](https://user-images.githubusercontent.com/60010597/169475467-0f86a09f-8d35-4541-97c0-c2fc4a1e2c81.png)

Looks like this is rethrown after `_canControlDbConfig()` fails.

If i replace this check with `$showDbScreen = true`, the installs completes successfully.

**Comment by brandonkelly** [comment]
Sorry, try running `composer update` once more.

The issue was that the `_canControlDbConfig()` method (which determines whether Craft actually has control over the database connection settings) was still assuming that the environment variable values would get pulled in via `config/db.php`. But the whole point of the new `CRAFT_*`-prefixed environment variables is that they will override whatever `config/db.php` returns, if there even is one. So that file doesn’t matter anymore, as far as the installer should be concerned.

**Comment by wsydney76** [comment]
@brandonkelly Thanks, just tested and works fine now for me.

/Mel

**Comment by brandonkelly** [comment]
3.7.43 and 4.0.3 are out now with these fixes.
