### ISSUE TITLE
[4.x] & [3.x]: `GeneralConfig::maxBackups` ignores zipped SQL files

### ISSUE THREAD

**Issue by rob-baker-ar** [craftcms/cms#11241]
### What happened?

_Same issue exists on `4.x` and `3.x`._

### Description

As part of our deployment process we do a database backup command similar to:

```
./craft db/backup --zip=1
```

This correctly produces a `*.sql.zip` file in the `storage/backups` directory. We also have the `GeneralConfig::maxBackups` unset in `config/general.php` meaning it should be set at it's default of `20`: https://craftcms.com/docs/3.x/config/config-settings.html#maxbackups.

The code responsible for limiting the number of backup files kept has this line: 

https://github.com/craftcms/cms/blob/46bb9edda436b6dc6851b263fedbb5895e63edd1/src/db/Connection.php#L268

This ignores the files with names ending `.zip`, so we have some old `.sql` files in that directory (20 of them!) but hundreds of `.zip` files.

### Expected behavior

Zipped SQL files should be limited to the count defined in `GeneralConfig::maxBackups`, either treating `.sql` and `.zip` files as grouped together or as 2 separate groups.

### Actual behavior

Only files ending `.sql` are counted.

### Craft CMS version

3 or 4

**Comment by brandonkelly** [comment]
Thanks for pointing that out. Just made a change for the next release that should make it better.

If you’d like to get the change early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 4.0.3"` and run `composer update`.

**Comment by brandonkelly** [comment]
Agree this is probably a more desired behavior, but considering you have to explicitly opt into backups being stored as a zip file via the `db/backup` command, I don’t really consider this a bug. So I’ve made the change for Craft 4.1 instead of the next 4.0.x release (607d1e0ea1d96cf168d2dd3e04eb40fc379fd441).

**Comment by brandonkelly** [comment]
Craft 4.1 is out with this change ✨
