### ISSUE TITLE
Create a "Link/Button" field

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1125]
> Created by: Ryan (rswhite@gmail.com) on 2015/06/27 22:53:39 +0000
> Votes at time of UserVoice import: 3

-----------------------------------

Sometimes on a page it's necessary to give the client the option to add a button and/or customize button text, url, if the url should pull from an existing entry, if url should open in new tab, add a button class via a dropdown, etc.

Right now, you can easily do this with a Matrix block and restrict it to a max 1 block, but then the user has to "add the block" and it seems like an unnecessary step. Also, if you're needing to add a customizable link/button inside a matrix field, you can't add ANOTHER matrix field, so you'd have to create all those fields individually. It would be cool to see some way of grouping all of these things together into one field and just choose all the details you want associated with the link/button.

**Comment by brandonkelly** [comment]
I could see us adding a generic Link field once #1662 is implemented.

**Comment by jsunsawyer** [comment]
Is this still something you're considering?

**Comment by brandonkelly** [comment]
@jsunsawyer it’s a possibility down the road, but definitely not a priority for us right now.

**Comment by bfopma** [comment]
@brandonkelly we've used LinkIt heavily in our projects; with recent conversation in Discord about LinkIt ceasing to be under active development, is there opportunity to revisit this as a built-in field type in Craft?

I'm not sure if this pain point is exclusive to us, but we've both relied heavily on LinkIt and have been burned by it during Craft upgrades. A first party link fieldtype would be a very welcome addition. Thank you for considering.

**Comment by jsunsawyer** [comment]
@brandonkelly It seems that this issue got closed, but not moved to discussions along with some other things. This is something that I'd still really love to have as a core Craft field.
