### ISSUE TITLE
[4.0.2]: Order of lightswitch field labels should be reversed in field configuration to be consistent with order displayed in entry edit form

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#11259]
### Description
The labels for the opposing lightswitch states in the field configuration page are opposite to how the field is presented in an entry form. The order of the labels should be reversed in the field configuration page to be consistent.

In the example below the field options put the "on" state before the "off" state but when the toggle is presented within an  entry edit page the "off" state is presented before the "on" state.

<img width="411" alt="CleanShot 2022-05-18 at 20 36 14@2x" src="https://user-images.githubusercontent.com/2505643/169021190-a2261ff2-be3b-4d7b-80e3-f96c0339f2b7.png">

<img width="137" alt="CleanShot 2022-05-18 at 20 34 21@2x" src="https://user-images.githubusercontent.com/2505643/169019787-6975b5c1-689c-4c95-92a1-e9387255c196.png">

### Craft CMS version

4.0.2

**Comment by brandonkelly** [comment]
Changed for the next v3 and v4 releases.

**Comment by brandonkelly** [comment]
3.7.43 and 4.0.3 are out now with that change.
