### ISSUE TITLE
[3.x]: srcset eager loading does not apply format from base transform

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/cms#11264]
### Description

As discovered while writing https://github.com/craftcms/cms/issues/11209#issuecomment-1125754835, I noticed when eager loading the srcset it does not copy over `format` from the base transform. Because of this it would still create additional database queries on every iteration. 

### Steps to reproduce

1. Create a transform with a specific format (I picked `webp`)
2. Eager load the transform with srcsets:
```twig
{% set query = craft.entries.section('blogArticles').orderBy('postDate').limit(8).with([
    ['primaryImage', {
        withTransforms: ['cardIndexLarge', '2x', 'cardIndexMedium', '2x', 'cardIndexSmall', '2x']
    }],
]) %}
```
3. Loop over the entries and create the images with the 2x srcset.

### Expected behavior

It to copy over the specific `webp` format when building the `$indexCondition` inside `\craft\services\AssetTransforms::eagerLoadTransforms`. For example what I created in my previous pull request: https://github.com/craftcms/cms/pull/11210/commits/bd2152abd0e99fa8db1238c32d6f78cea6d21bee#diff-2f35fc9ed1a9b42586a3436850479f719301f07e8052655f4311ace1ae061864R478).

### Actual behavior

This query would run on every iteration because it did not properly eager load the 2x srcset. Notice the \`format\`='webp':
<img width="401" alt="Screenshot 2022-05-11 at 20 58 55" src="https://user-images.githubusercontent.com/2922378/167925817-7dc28558-016e-475b-a1f8-4778db3b51dd.png">

### Craft CMS version

3.4.41

### PHP version

8.0.17

### Operating system and version

Linux 5.10.104-linuxkit

### Database type and version

MySQL 8.0.28

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-16)

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next v3 and v4 releases.

**Comment by brandonkelly** [comment]
3.7.43 and 4.0.3 are out now with that fix.
