### ISSUE TITLE
[3.6.10]: Multisite domain connection

### ISSUE THREAD

**Issue by Radu033** [craftcms/cms#11263]
### Description

I have a main website, and now I created a smaller website using the same components / templates.

- Server IP ( 157.xxx.xxx.xxx) 
- My main website is connected to the domain: **main.com** 
- My small website should be connected to the domaine: **small.com**

The **small.com** domain has an A record pointing to the Server IP and it shows the content of the main website. Even though in the settings the Base url is set to **small.com**

How can I point the **small.come** to show the contents of the small website?
Is this a bug in Craft or a misconfiguration?

### Expected behavior

The small.com domain should point to the smallWebsite handle

### Actual behavior

The small.com domain shows the main website.

### Craft CMS version

3.6.10

### Installed plugins and versions

-

**Comment by angrybrad** [comment]
Sounds like a misconfiguration - I'd suggest giving the Craft multi-site docs a once over.  You can come back with specific questions if you can't get it resolved after that https://craftcms.com/docs/4.x/sites.html#setting-up-a-new-site

**Comment by brandonkelly** [comment]
Try going to `https://small.com/admin/utilities/php-info` and search for `$_SERVER['HTTP_HOST']`. Is it set to `small.com` or `main.com`?

**Comment by Radu033** [comment]
Hey Brandon,

Thanks for your email.

I actually solved the issue. The problem was that both of the websites had
in "Base Url" @web and @greensteel (small web) and I have an alias attached
to them in config.

Once I wrote the domain name by hand in the field  without aliases,
everything works fine.

This ticket can be closed.

Have a good day,
Radu

**Comment by brandonkelly** [comment]
Glad you got it sorted!
