### ISSUE TITLE
[4.x]: Cannot drop table 'craft_entryversions' while updating to Craft 4

### ISSUE THREAD

**Issue by k7y6t5** [craftcms/cms#11276]
### What happened?

I'm following the [Craft 4 update instructions](https://craftcms.com/docs/4.x/upgrade.html#performing-the-upgrade) and have hit a snag while running `php craft/migrate-all`.

```
> dropping {{%entryversions}} if it exists ...Exception: SQLSTATE[HY000]: General error: 3730 Cannot drop table 'craft_entryversions' referenced by a foreign key constraint 'craft_import_entries_versionId_fk' on table 'craft_import_entries'.
```

### Craft CMS version

3.7.42

### PHP version

8.0.18

### Operating system and version

Ubuntu 20.04.4 LTS

### Database type and version

MySQL 8.0.29

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.10-23)

### Installed plugins and versions

Asset Usage 2.2.1
Cookies 1.1.15
Feed Me 4.5.2
Redactor 2.10.8
Super Table 2.7.2

**Comment by brandonkelly** [comment]
`craft_import_entries` is not a native table. It must have come from a formerly-used plugin, or a custom module. Try to track down whether it’s needed anymore, and if not, delete that table first.
