### ISSUE TITLE
[3.7.42]: Querying for an element ID adds an ambiguous `siteId` to the query

### ISSUE THREAD

**Issue by gustavs-gutmanis** [craftcms/cms#11275]
### Description

Querying for an element ID adds an ambiguous `siteId` to the query, so if there are any other joined tables using `siteId` as column names, the query fails saying that the `siteId` column in the `SELECT` expression isn't specific enough.

This happens on multi-page sites using the [Solspace Calendar](https://github.com/solspace/craft-calendar) plugin. 
https://github.com/solspace/craft-calendar/issues/130
https://github.com/solspace/craft-calendar/issues/132

### Steps to reproduce

1. Set up a multi-site Craft install
2. Install [Solspace Calendar](https://github.com/solspace/craft-calendar)
3. Create an Event (should succeed)
4. Edit an existing Event and try to re-save it

You should now see an exception stating that an SQL error happened:

```
Integrity constraint violation – [yii\db\IntegrityException](http://www.yiiframework.com/doc-2.0/yii-db-integrityexception.html)
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'siteId' in field list is ambiguous
The SQL being executed was: SELECT `elements`.`id`, `siteId`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`
FROM `elements` `elements`
INNER JOIN `calendar_events` `calendar_events` ON `calendar_events`.`id` = `elements`.`id`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `content` `content` ON (`content`.`elementId` = `elements`.`id`) AND (`content`.`siteId` = `elements_sites`.`siteId`)
INNER JOIN `calendar_calendars` ON `calendar_calendars`.`id` = calendar_events.`calendarId`
LEFT JOIN `users` ON `users`.`id` = calendar_events.`authorId`
WHERE (`elements_sites`.`siteId`=2) AND (`elements`.`id`=33657) AND (`elements`.`archived`=FALSE) AND (`elements`.`dateDeleted` IS NULL) AND (`elements`.`draftId` IS NULL) AND (`elements`.`revisionId` IS NULL)
ORDER BY `startDate`) `subquery`
INNER JOIN `calendar_events` `calendar_events` ON `calendar_events`.`id` = `subquery`.`elementsId`
INNER JOIN `elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `content` `content` ON `content`.`id` = `subquery`.`contentId`
INNER JOIN `calendar_calendars` ON `calendar_calendars`.`id` = calendar_events.`calendarId`
LEFT JOIN `users` ON `users`.`id` = calendar_events.`authorId`
ORDER BY `startDate`
Error Info: Array
(
    [0] => 23000
    [1] => 1052
    [2] => Column 'siteId' in field list is ambiguous
)
↵
Caused by: PDOException
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'siteId' in field list is ambiguous
in /home/httpd/vhosts/tanzhaus-zuerich.ch/core/vendor/yiisoft/yii2/db/Command.php at line 1302
```

### Expected behavior

`Element::ids()` should add the `siteId` column by specifying also the table it should be fetched from.

### Actual behavior

`Elements::ids()` attaches a `siteId` column without specifying the talbe it should be fetched from.

### Craft CMS version

3.7.42

### PHP version

7.4.29

### Database type and version

MySQL 5.5.5

### Installed plugins and versions

- Solspace Calendar v3.3.11

**Comment by brandonkelly** [comment]
`ids()` explicitly limits the `select` clause to just `elements.id`:

https://github.com/craftcms/cms/blob/3f7e0e30d049be9976db94ba9cf9826a8245b883/src/elements/db/ElementQuery.php#L1728

So something else (either the element query class or something getting involved via an event) must be adding `siteId` to the mix after that. It’s not coming from Craft though.
