### ISSUE TITLE
[4.0.2]: Unable to eager-load image with srcset transforms

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#11274]
### Description

I'm trying to preload an image with multiple transforms for usage with the `srcset` method. I'm not sure if I'm seeing a bug or I'm just getting the syntax wrong, probably the latter. I wasn't able to find a complete example for eager-loading transforms for srcsets, so hopefully someone can tell me what I'm doing wrong or if there's actually a bug there.

Here's what I have so far

```twig
{% set baseTransform = { width: 100, height: 100, mode: 'crop', } %}
{% set srcsetTransform = [120, 180, 240, 360] %}

{% set wells = craft.entries()
    .section('well')
    .orderBy('title')
    .image(':notempty:')
    .with([
        ['image', { withTransforms: [baseTransform, srcsetTransform] }]
    ])
    .limit(5)
    .all()
%}

{% for well in wells %}
    {% set image = well.image.first() %}
    {% set url = image.getUrl(baseTransform) %}
    {% set srcset = image.getSrcset(srcsetTransform) %}
{% endfor %}
```

Now this gives me the following exception:

> Setting unknown property: craft\models\ImageTransform::0

I also tried defining the srcset like this, but it doesn't change anything:

```twig
{% set srcsetTransform = ["120w", "180w", "240w", "360w"] %}
```

Any ideas?

### Craft CMS version

4.0.2

### PHP version

8.1

### Operating system and version

macOS

### Database type and version

MySQL 8.0

**Comment by Wiejeben** [comment]
I think you're applying the srcset transforms incorrectly to the `withTransforms` array.

`[baseTransform, srcsetTransform]` would result in `[{ width: 100, height: 100, mode: 'crop'}, [120, 180, 240, 360]]` while it must be flat like this `[{ width: 100, height: 100, mode: 'crop'}, 120, 180, 240, 360]`.

I think this would give the desired outcome (untested):
```twig
        ['image', { withTransforms: [baseTransform]|merge(srcsetTransform) }]
```

**Comment by MoritzLost** [comment]
@Wiejeben Thanks! I tried this out, but it doesn't work. There's no exception with this code, but the preloading is still not working. I'm seeing 40 additional queries in the debug toolbar with the additional `image.getSrcset(srcsetTransform)`. So two queries for each individual transform in the srcset (5 entries * 4 sizes/entry = 20 sizes). So either the syntax is still not correct or it's a bug I guess?

Adjusted example for reference:

```twig
{% set baseTransform = { width: 100, height: 100, mode: 'crop', } %}
{% set srcsetTransform = [120, 180, 240, 360] %}

{% set wells = craft.entries()
    .section('well')
    .orderBy('title')
    .image(':notempty:')
    .with([
        ['image', { withTransforms: [baseTransform]|merge(srcsetTransform) }]
    ])
    .limit(5)
    .all()
%}

{% for well in wells %}
    {% set image = well.image.first() %}
    {% set url = image.getUrl(baseTransform) %}
    {% set srcset = image.getSrcset(srcsetTransform) %}
{% endfor %}
```

I tried the same thing with the string syntax (`"120w"` instead of `120`), makes no difference.

**Comment by Wiejeben** [comment]
Ah I might have found something else, essentially the `getSrcset` is not aware of the base transformed set by `getUrl`. For that you need `setTransform()`.

Give this a try:
```twig
{% for well in wells %}
    {% set image = well.image.first() %}

    {% do image.setTransform(baseTransform) %}
    {% set url = image.url %}
    {% set srcset = image.srcset(srcsetTransform) %}
{% endfor %}
```

**Comment by brandonkelly** [comment]
That’s correct. `getUrl()` and `getSrcset()` each have their own independent transform support.

**Comment by MoritzLost** [comment]
@Wiejeben @brandonkelly Thank you both! Not it's working and all the transforms are being built without additional queries. Final working code below in case someone needs it.

```lang-twig
{% set baseTransform = { width: 100, height: 100, mode: 'crop', } %}
{% set srcsetTransform = [120, 180, 240, 360] %}

{% set wells = craft.entries()
    .section('well')
    .orderBy('title')
    .image(':notempty:')
    .with([
        ['image', { withTransforms: [baseTransform]|merge(srcsetTransform) }]
    ])
    .limit(5)
    .all()
%}

{% for well in wells %}
    {% set image = well.image.first() %}
    {% do image.setTransform(baseTransform) %}
    {% set url = image.getUrl() %}
    {% set srcset = image.getSrcset(srcsetTransform) %}
{% endfor %}
```
