### ISSUE TITLE
[4.x]: Prune revisions with Matrix destroys entries

### ISSUE THREAD

**Issue by vandres** [craftcms/cms#11285]
### Description
When having Matrix blocks, upon calling `utils/prune-revisions`, the Matrix blocks get destroyed

### Steps to reproduce

1. Setup Craft 4
2. Create a Matrix block and assign it to a section
3. Don't know if it is relevant, but it's a multi site setup
4. Create some content in that section entry
5. Call `utils/prune-revisions` with 0
6. Try to save the entry again

I've setup a repo to display the issue https://github.com/vandres/craft4-prune-revisions-matrix

In the `sql` folder, you have a db dump before and after the prune.

<img width="685" alt="Bildschirmfoto 2022-05-20 um 09 12 23" src="https://user-images.githubusercontent.com/1436383/169465559-50fae119-5fae-4f7b-b8e1-994f8541c599.png">
<img width="895" alt="Bildschirmfoto 2022-05-20 um 09 12 33" src="https://user-images.githubusercontent.com/1436383/169465563-de9ede92-d631-482d-98cf-3d370e4dbd49.png">

### Expected behavior

All but 1 revisions are gone. It should be still possible to save new revisions.

### Actual behavior

Saving entries after the prune is no longer possible. 

### Craft CMS version

4.0.2

### PHP version

8.0

### Operating system and version

Debian 11

### Database type and version

MariaDB 10.3

### Installed plugins and versions

None - blank default setup

**Comment by brandonkelly** [comment]
This is the same underlying issue as #11155, which has been fixed for the next release (imminent).

**Comment by brandonkelly** [comment]
Craft 4.0.3 is out now with that fix.

**Comment by vandres** [comment]
Thank you very much!Will it fix existing records or only future ones? Sent from my Galaxy
-------- Original message --------From: Brandon Kelly ***@***.***> Date: 20/05/2022  19:57  (GMT+03:00) To: craftcms/cms ***@***.***> Cc: Volker Andres ***@***.***>, Author ***@***.***> Subject: Re: [craftcms/cms] [4.x]: Prune revisions with Matrix destroys entries (Issue #11285) 
Craft 4.0.3 is out now with that fix.

**Comment by brandonkelly** [comment]
There was nothing to fix, actually. `utils/prune-revisions` just doesn’t completely erase the revision data (which is sortof a bug, but something that garbage collection will take care of so not a big deal), but the partial remaining revision data was confusing a part of Craft’s revision creation process into thinking a revision existed when it didn’t.
