### ISSUE TITLE
[4.x]: No option to select and delete files from temporary uploads folder within the Control Panel

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#11293]
### Description
Navigating to the "temporary uploads" folder via the Control Panel > Assets section list a number of temporary files but there is no option (checkbox to the left of each file) to select and delete them. 

<img width="244" alt="CleanShot 2022-05-22 at 16 03 38@2x" src="https://user-images.githubusercontent.com/2505643/169681286-ceb1e569-ddb7-476e-bd61-1f137887a58b.png">

### Craft CMS version

4.0.3

**Comment by brandonkelly** [comment]
Craft 4.0.4 is out now with that fix.
