### ISSUE TITLE
[4.x]: Unable to create custom aliases in general config

### ISSUE THREAD

**Issue by martinleveille** [craftcms/cms#11292]
### What happened?

Custom aliases defined in the `aliases` general config setting are discarded. For example:

```
'aliases' => [
    '@web' => 'https://craft40.test/',
    '@hello' => 'test test test',
]
```

The `@hello` alias will not be available.

### Craft CMS version

4.0.3

### PHP version

8.0.18

### Operating system and version

Darwin 21.4.0

### Database type and version

MySQL 8.0.28

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-30)

### Installed plugins and versions

No plugins

**Comment by brandonkelly** [comment]
Working fine on my end. Are you literally setting the value to something similar to `test test test`? Alias values must either be a file path or a URL.

**Comment by brandonkelly** [comment]
Alright, well let me know if you find anything worth addressing on our end.

**Comment by JayBox325** [comment]
@martinleveille, I know this is old but can you share your full general config file for me? I'm on a craft 4 site and the general config file includes:

```
<?php
/**
 * General Configuration
 *
 * All of your system's general configuration settings go in here. You can see a
 * list of the available settings in vendor/craftcms/cms/src/config/GeneralConfig.php.
 *
 * @see \craft\config\GeneralConfig
 */

use craft\config\GeneralConfig;
use craft\helpers\App;

$isDev = App::env('CRAFT_ENVIRONMENT') === 'dev';
$isProd = App::env('CRAFT_ENVIRONMENT') === 'production';

return GeneralConfig::create()
    // Set the default week start day for date pickers (0 = Sunday, 1 = Monday, etc.)
    ->defaultWeekStartDay(1)
    // Prevent generated URLs from including "index.php"
    ->omitScriptNameInUrls()
    // Enable Dev Mode on the dev environment (see https://craftcms.com/guides/what-dev-mode-does)
    ->devMode($isDev)
    // Only allow administrative changes on the dev environment
    ->allowAdminChanges($isDev)
    // Disallow robots everywhere except the production environment
    ->disallowRobots(!$isProd)
;
```

So it's quite different to how it used to be on Craft 3 and I'm getting errors when I add the aliases definition like how you've done it there. Thanks!

**Comment by martinleveille** [comment]
@JayBox325 I will not send you a config file, but you can still use the Craft 3 format.

**Comment by brandonkelly** [comment]
@JayBox325 If you want to stick with the fluent config format, setting the `aliases` config setting would look like:

```php
return GeneralConfig::create()
    // ...
    ->aliases([
        '@name' => 'value',
        // ...
    ])
;
```

**Comment by JayBox325** [comment]
Oh, @martinleveille wasn't expecting to be shown anything vulnerable! Just wanted to see the format as the Craft 4 one is very different.

That's perfect @brandonkelly, thanks for that! Great stuff as usual.
