### ISSUE TITLE
[4.x]: Entries view: cannot disable all columns

### ISSUE THREAD

**Issue by MetaDevelopment** [craftcms/cms#11291]
### Description
In the entries view, when changing the columns to show and unticking all columns so that only the entry title will show, the system will switch back to a default view, showing the columns "Entry", "Post Date", "Expiry Date", "Author" and "Link". You have to select/tick at least one column for the changes to actually work. 

### Steps to reproduce
1. Install craft 
2. Create a section
3. Go to the Entries view 
4. Customize the view via the settings icon at the bottom of the section list 
5. Untick all table columns 
6. Save 

### Expected behavior
Only the column "Entry" will show. 

### Actual behavior
The columns "Entry", "Post Date", "Expiry Date", "Author" and "Link" will show. 

### Craft CMS version

4.0.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.4 is out now with that fix.
