### ISSUE TITLE
[4.x]: Multi-site enabled label inconsistent wording

### ISSUE THREAD

**Issue by turnstylerj** [craftcms/cms#11307]
### Description

Referencing this [older issue](https://github.com/craftcms/cms/issues/2899#issuecomment-573332126) (and looking at one of our Craft 3 multi-site installs), it looks like the first site in the expanded list is now missing "Enabled for" before its name in Craft 4, making the naming convention read a bit strange.

From my current install:

![Screen Shot 2022-05-24 at 4 27 59 PM](https://user-images.githubusercontent.com/42223501/170148248-bc5f4653-a75f-47ac-8f5b-3e9c5b75d948.png)

### Steps to reproduce

1. Set up multiple sites on Craft 4 and enable them for a section
2. Create a new entry in that section and expand the "Status" panel
3. Add more than one site

### Expected behavior

All enabled sites are listed as "Enabled for <site name>"

### Actual behavior

The first site listed is missing "Enabled for"

### Craft CMS version

4.0.3

### PHP version

8.0.8

### Operating system and version

Darwin 21.3.0

### Database type and version

MySQL 5.7.34

### Image driver and version

GD 8.0.8

### Installed plugins and versions

craftcms/aws-s3: 2.0.1
craftcms/feed-me: 5.0.3
craftcms/redactor: 3.0.0
doublesecretagency/craft-cpcss: 2.5.0
internetztube/craft-element-relations: 2.0.0-beta.2
mmikkel/retcon: 2.4.2
nystudio107/craft-imageoptimize: 4.0.0-beta.3
nystudio107/craft-minify: 4.0.0-beta.2
nystudio107/craft-seomatic: 4.0.0
percipioglobal/craft-colour-swatches: 4.0.5
spicyweb/craft-neo: 3.0.5
verbb/field-manager: 3.0.0-beta.1
vlucas/phpdotenv: ^5.4.0

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.4 is out now with that fix.
