### ISSUE TITLE
[3.x]: 

### ISSUE THREAD

**Issue by market-south** [craftcms/cms#11308]
### Description

When using the where condition with the field handle on 'Entry::find()' gets a catch error of column not found.  On inspecting the error seems like there are some random strings added as suffixes to the column name. 

Can you please advise whether this is related to the CMS or related to the plugin?

### Steps to reproduce

1. Create new fields and add them to the entry types to an existing section. 
2. Try to use Entry::find() to get the entry details using the where clause on a new field type

### Expected behavior
 Entry::find() should find and return the matching entry from the CMS

### Actual behavior
Getting error message as column not found

```
$entries = Entry::find()
        ->section('usersAccount')
        ->where(['field_customerEmailAddress' => [ '=', $email]])
        ->one();
```

### Craft CMS version

7.4.27

### PHP version

7.4

### Operating system and version

Linux 5.4.0-51-generic

### Database type and version

MySQL 5.7.32

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.10-23)

### Installed plugins and versions

   "craftcms/cms": "3.7.42",
        "craftcms/element-api": "2.8.5",
        "craftcms/redactor": "2.10.8",
        "dolphiq/redirect": "1.1.1",
        "fruitstudios/linkit": "1.1.12.1",
        "nystudio107/craft-seomatic": "3.4.30",
        "ostark/craft-async-queue": "2.3.0",
        "pennebaker/craft-architect": "2.4.3",
        "spicyweb/craft-neo": "2.13.9",
        "utakka/redactor-anchors": "1.4.0",
        "verbb/field-manager": "2.2.4",
        "verbb/navigation": "1.4.26",
        "vlucas/phpdotenv": "^3.4.0",
        "windsor/windsor-login": "^1.0",
        "windsor/windsor-products": "^1.0",
        "xpertbot/craft-wheelform": "2.7.2"

**Comment by brandonkelly** [comment]
Closing as we’re helping you via support.
