### ISSUE TITLE
[4.x]: Use pluginfactory.io to create your module’s scaffolding with just a few clicks

### ISSUE THREAD

**Issue by remcoov** [craftcms/cms#11313]
### Description
In the Craft [module docs](https://craftcms.com/docs/4.x/extend/module-guide.html) there is being referenced to the fact that you can use pluginfactory.io for scaffolding, but pluginfactory is not uptodate with 4.X plugins and or modules.

### Craft CMS version

4.0.3

### PHP version

8.0.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Just submitted a PR that adds Craft 4-compatible templates (nystudio107/generator-craftplugin#113). Will update this issue when it’s live.
