### ISSUE TITLE
[3.x]: Control Panel not updated after database restore

### ISSUE THREAD

**Issue by bencresty** [craftcms/cms#11327]
### Description
When restoring a database with `php craft db/restore {dbfile}` the database gets restored alright, but the CMS is still showing entries that were removed in the restored database file and so should be gone. This was not caused by a browser cache.
A Craft clear cache (not sure which, I used `php craft clear-caches/all` which did the job) was needed after the database restore call to update the CMS view. IMO the restore database command should automatically refresh the Control Panel/CMS after a db restore.

### Steps to reproduce

1. Have a production environment and a development environment up with using the same database (with some entries)
2. Open the Control Panel on the production environment and remove one or more entries
3. Backup the database from the production environment to a local sql-file
4. Rename the sql file to use the name of the development database 
5. Open the development control panel and see all entries are still there
6. Call the craft db/restore-command on the development environment from the command line to import the renamed production db sql file to use in the development environment
7. ctrl-F5 in the browser to refresh the development Control Panel
8. See that the removed entries are still there, eventhough the database is imported from the production environment where some entries were removed (also still visible when removing cookies etc. in the browser)
9. Clear all Craft caches on development: php craft clear-caches/all
10. ctrl-F5 in the browser to refresh the development Control Panel
11. See that now the changed database is actually visually visible, so the removed entries are gone now in the control panel

Notes:
- The removed entries were set to 'offline' before they were removed and the database was backupped.
- It's a multi locales/sites setup

### Expected behavior

Control panel should always be in sync with the actual database.

### Actual behavior

Control panel is not representing the actual database state after a db restore

### Craft CMS version

3.7.43

### PHP version

8.0.12

### Operating system and version

Windows 10

### Database type and version

MariaDb 10.4.21

### Image driver and version

-

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Just added a `Clear data caches?` prompt to the end of the `db/restore` command for the next release, which will call `clear-caches/data` internally if responded with `yes` (the default).

**Comment by bencresty** [comment]
@brandonkelly  Great solution for everybody. Thanks for the quick action

**Comment by bencresty** [comment]
@brandonkelly  Uh... one question tho now that I think about it...

How can we say `yes` to this popup question when the restore command is being called from a script (we're using it like that to deploy/update databases to a server)?

**Comment by brandonkelly** [comment]
@bencresty You can just start calling `clear-caches/data` immediately after, from the same script.

**Comment by bencresty** [comment]
@brandonkelly  thanks. I understand that in that case we can use the other command, but isn't the first command still waiting for an anwer to clear caches from the terminal in that case, because now the restore db command has this extra question?

**Comment by brandonkelly** [comment]
@bencresty It was just added as a convenience for when the command is being run interactively. If it’s not interactive, it’s not considered.

**Comment by brandonkelly** [comment]
Craft 3.7.44 and 4.0.4 are out now with that change.
