### ISSUE TITLE
[4.x]: 404 page only with redirect tag does not work

### ISSUE THREAD

**Issue by tarmooo** [craftcms/cms#11336]
### Description

When 404 page has only tag
`{% redirect "/" %}`
then browser will not open the page and will not redirect to "/"
(in craft 3 it did work)

### Steps to reproduce

1. create 404 template only with redirect tag and try to enter a page that does not exist

### Expected behavior
template would work and redirect user to given url

### Actual behavior

browser gets nothing: HTTP ERROR 500

### Craft CMS version

4.0.3

### PHP version

8.1.6

### Operating system and version

Linux 5.10.104-linuxkit

### Database type and version

PostgreSQL 12.7

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.4 is out now with that fix.
