### ISSUE TITLE
[3.x]: siteUrl/actionUrl function removes equals sign at the end of a value

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/cms#11334]
### Description

This is a minor thing but I ported a template which was originally from Craft 2 and found an interesting but small behaviour difference with siteUrl, actionUrl etc which had me head scratching for a bit, until I noticed the issue.

In a template several data attributes are being added to the outer container of a field these are `data-chain`, `data-chain-endpoint` and `'data-chain-target`. These values in twig are like so:

```
'data-chain: '',
'data-chain-endpoint': siteUrl(craft.config.get('actionTrigger') ~ '/my/controller/route?param='),
'data-chain-target': '.field-for-select',
```

Ignoring the use of siteUrl() when you could use actionUrl() for a second, note the ?param= part at the end of `data-chain-endpoint`, this is important because in this case, some JS will append a specific param value after the `=` and fire a HTTP request to the controller when an option is selected to load new values onto another field, so the param value might be "Option1" if option one was selected, Option2 etc.

Interestingly when using siteUrl() or actionUrl() it would appear under Craft CMS 3, the hanging equals sign is removed entirely, which breaks this chained JS function. This however doesn't happen on Craft CMS 2, using the same function calls.

With some experimenting, I found this works in Craft CMS 3 to provide the same value needed, which is admittedly cleaner anyway.

```
actionUrl('my/controller/route', { 'param=': '' })
```

Just flagging it as something potentially for the docs or a not so obvious behaviour difference?

### Craft CMS version

3.7.43

### PHP version

7.4.19

### Operating system and version

Ubuntu 20.04 (WSL2)

### Database type and version

MySQL

**Comment by brandonkelly** [comment]
Yeah this changed in 3.5.12, per #6900. The URL parameters get normalized during URL generation, and we end up losing track of whether they originally had an `=` or not. PHP treats both `?foo` and `?foo=` the same, so we sided with removing the `=` when there’s no value, as it looks cleaner for situations where you want something like `?thanks` appended to the URL.

> With some experimenting, I found this works in Craft CMS 3 to provide the same value needed, which is admittedly cleaner anyway.
>
> ```twig
> actionUrl('my/controller/route', { 'param=': '' })
> ```

I wouldn’t recommend that – it’s a hack that I can’t promise will work forever.

The most future-proof way you might want to do this is to give the param a temporary value that gets replaced by your JavaScript code:

```twig
actionUrl('my/controller/route', { param: '__PARAM__' })
```

```js
chainEndpoint.replace('__PARAM__', paramValue)
```

**Comment by jamesmacwhite** [comment]
@brandonkelly Thank you for linking the previous change behind this, explains the difference.

I'll look refactoring this in the JavaScript side so the actionUrl function isn't doing a hack!
