### ISSUE TITLE
[4.x]: No-cache headers for all web-requests

### ISSUE THREAD

**Issue by jerome2710** [craftcms/cms#11346]
### Description
Commit cf6a4cf broke [the check](https://github.com/craftcms/cms/commit/cf6a4cf918fca3c76f82b364ad764d7572bb0c40#diff-6fc826f1dff4d52781b01cdf3b1d4422ab3bf4d3784c107a13bd2cedc2ca73b9L1368) if the current web-request is a CP-request. Now all web-requests, either CP or site, will get no-cache headers.

### Craft CMS version

4.0.3

### PHP version

8.1.6

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release (going out tomorrow).

**Comment by brandonkelly** [comment]
Craft 4.0.4 is out now with that fix.
