### ISSUE TITLE
Rename Save Button to Publish and make Save as Draft option more visible

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1135]
> Created by: Rolf-Juergen Hornasek (rolf.juergen.hornasek@gmail.com) on 2015/08/20 17:49:24 +0000
> Votes at time of UserVoice import: 3

-----------------------------------

Save doesn't say what it does. Does it publish an entry? Does it save a draft? For those who are used to saving drafts they could accidently publish an entry by clicking on save, especially since you have to click a tiny dropdown to open the "Save as Draft" menu. "Save as Draft" should be a separate button before the publish button to give you the option to either save a draft or publish an entry...

**Comment by brandonkelly** [comment]
Craft 3.2 will automatically create a draft as you start editing content, and autosave it as you continue editing, so there is no “Save” button anymore—just “Update entry”, which is the new equivalent of the old “Publish draft” button. So this FR isn’t really relevant anymore.
