### ISSUE TITLE
[4.x]: Asset Thumbnails not Reliably Appearing in Control Panel Asset, Entry and Entries Listing Pages

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#11350]
### Description
Asset thumbnails are not reliably appearing for all entries within the control panel (e.g. entry page, entries listing and assets section) despite the transforms existing for these in the relevant folder.

Using the web inspector I have checked the data-srcset links to the asset thumbnails in the control panel and have verified these exist (I can open the image in a seperate browser tab). It seems it may have something to do with asset file names that contain a space.

<img width="951" alt="CleanShot 2022-05-31 at 11 42 43@2x" src="https://user-images.githubusercontent.com/2505643/171076440-9a456d18-30b3-4b63-895e-2ea7095adcc5.png">

### Steps to reproduce
If images have originally been uploaded via FTP (instead of via the control panel) and contain spaces in the filename it seems these thumbnails are not being displayed in the control panel. Despite the thumbnails existing (following asset indexing being run via CP utilities to pick up these files).

I can see that when an asset is uploaded via the control panel Craft by default converts the file to lower case and replaces spaces with a hyphen (kebab case). It would be nice to have a console cmd to convert all uploaded files to lower case kebab. Some thing like: [https://craftcms.com/docs/4.x/config/config-settings.html#convertfilenamestoascii](https://craftcms.com/docs/4.x/config/config-settings.html#convertfilenamestoascii)

For example the following thumbnail is not being displayed:
```/_34x34_crop_center-center_none/Barefoot Sunset.jpg 34w```

But this one is being displayed:
```/_34x34_crop_center-center_none/Bayside.jpg```

<img width="539" alt="asset-thumbnails" src="https://user-images.githubusercontent.com/2505643/171076199-e0c09fe5-6d6a-46b5-b490-b9970c14ff61.png">

<img width="939" alt="CleanShot 2022-05-31 at 11 41 58@2x" src="https://user-images.githubusercontent.com/2505643/171076357-7e1f3dca-7958-400e-a05b-596dcfca7ea4.png">

### Craft CMS version

4.0.3

### PHP version

8.1

**Comment by richhayler** [comment]
If I edit the asset via the control panel and replace the space with a hyphen the thumbnail is correctly shown.

<img width="520" alt="CleanShot 2022-05-31 at 11 45 29@2x" src="https://user-images.githubusercontent.com/2505643/171076705-e9c9a072-4efe-4f44-9749-46b609e1e8c8.png">

**Comment by brandonkelly** [comment]
Are you getting any JavaScript errors, or are there any requests listed in your browser’s Resources tab that aren’t completing?

**Comment by brandonkelly** [comment]
Craft 4.0.4 is out now with that fix.
