### ISSUE TITLE
[3.x]: Wrong results checking dirty field in after save event 

### ISSUE THREAD

**Issue by philipboomy** [craftcms/cms#11353]
### Description

In EVENT_BEFORE_SAVE and EVENT_AFTER_SAVE these 3 below gives wrong results:
```
$user->isAttributeDirty('billingEmail')); 
$user->isFieldDirty('billingEmail'));
$user->getDirtyAttributes());
```

They return:
```
False
True
[]
```

They return the same where I change the field or not.

It seems to be happening with custom fields only. The default that appears on a user seems to work e.g. user email and first name etc.

Unless I am mistaken about what these "dirty" functions do then I believe this is a bug.

### Steps to reproduce

1. Add a custom field 'billingEmail' to a user
2. Change the field and see the results in an Event
3. Change a default user field only and see the same result in an Event

### Expected behavior

When changing "billingEmail" I expect this:

```
True
True
[ 
   0 => "billingEmail"
]
```

When **not** changing "billingEmail" I expect this:

```
False
False
[ 
    0 => "some-other-field-was-changed-and-then-saved"
]
```

### Actual behavior

```
False
True
[]
```

### Craft CMS version

3.7.43

### PHP version

8.0.19

### Database type and version

PostgreSQL 13.7

**Comment by brandonkelly** [comment]
`isAttributeDirty()` and `getDirtyAttributes()` are specifically for the element type’s native attributes. If `billingEmail` is a custom field, the relevant methods are `isFieldDirty()` and `getDirtyFields()`.

**Comment by philipboomy** [comment]
Thanks for replying however my example above did include `$user->isFieldDirty('billingEmail'));` and its returning "true" even when I haven't edited that field. Other fields are working correctly. Could it because its an email field?

**Comment by brandonkelly** [comment]
is `billingEmail` using the built-in Email field type?

**Comment by philipboomy** [comment]
That is correct. The default email field - https://share.getcloudapp.com/DOudgAE5 - Not from any plugin. A plain text field I have on the user is working correctly.

**Comment by philipboomy** [comment]
Ok - Thanks for investigating.
