### ISSUE TITLE
[3.x]: Intermittent failures for Updating search indexes: Craft can’t connect to the database

### ISSUE THREAD

**Issue by KarlBishop** [craftcms/cms#11368]
### What happened?

I am often seeing failed Queue Jobs for "Updating search indexes" after editing entries.

The reported error messages are like:

    The command "'/opt/php/8.0/bin/php' 'craft' 'queue/exec' '2501' '300' '1' '8485' '--color='" failed.
    Exit Code: 1(General error) 
    Working directory: /srv/app/mydirectory/htdocs
    Output: ================ [0m
    Craft can’t connect to the database. 
    Check your connection settings. [0m
    Error Output: ================
    Database Connection Error: Craft CMS can’t connect to the database with the credentials in config/db.php.`

The job data looks like this:

    {
        "elementType": "craft\\elements\\MatrixBlock",
        "elementId": 6161,
        "siteId": "*",
        "fieldHandles": [
            "label",
            "required",
            "width"
        ],
        "description": null
    }

The db credentials are set automatically by our hosting provider via environment variables. They say everything appears fine at their end. And the db is working fine in all other respects.

If I retry the queue jobs then they succeed.

Any idea why the db connection would fail intermittently like this?

### Craft CMS version

3.7.42

### PHP version

8.0.16

### Operating system and version

Linux 4.15.0-163-generic

### Database type and version

MySQL 8.0.23

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-26)

### Installed plugins and versions

- Asset Lockdown	1.0.0
- AsyncQueue	2.3.0
- CodeMirror	1.0.2
- Copy	1.2.1
- Dashboard Begone	1.0.1
- MatrixMate	1.4.3
- Matrix Toolbar	1.0.6
- Reasons	2.2.6
- Redactor	2.10.8
- Relax	1.0.1
- Retcon	2.4.2
- SCSS	1.0.0

**Comment by angrybrad** [comment]
Sounds like either random database connection issues or MySQL is killing the connection because it's hitting a "MySQL server has gone away" or a similar error.

I'd Check Craft's logs as well as MySQL's logs for connection-related MySQL errors.

**Comment by angrybrad** [comment]
Going to go ahead and close this, but comment back and we can re-open if you find anything useful in the logs.

**Comment by angrybrad** [comment]
@KarlBishop yes, 10 seems like a very low limit that your host is enforcing.

https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_max_user_connections

MySQL defaults to 0, which means unlimited.

**Comment by KarlBishop** [comment]
I've raised this with the host again because it's been reported by another user on a different Craft site.

The host responded:

> Yes, we limit the max connections to a fairly small number. The idea behind it: In theory, a PHP process can only create a single MySQL connection, unless there is something wrong with the design of the application. This setup is fairly balanced, which means the limit for MySQL connections is slightly higher than the number of PHP processes we provide.

Does this fit with how Craft works?

The two affected sites have:

1. 4 PHP processes and 10 max_user_connections
2. 8 PHP processes and 15 max_user_connections

Should this be plenty of resources to handle a single User creating a new Entry in the Control Panel?

**Comment by KarlBishop** [comment]
The other site is using Craft 3.7.51 FYI, although I can see the error also occurred in a web.log from about 4 months ago when they were on Craft 3.7.38 (that's as far back as records go).

**Comment by brandonkelly** [comment]
@KarlBishop If you have the [`useUnbufferedConnections`](https://craftcms.com/docs/3.x/config/db-settings.html#useunbufferedconnections) database connection setting enabled, then each request could create two MySQL connections.

Besides that, control panel requests can stick around after the request is over (and retain their database connection) so they can work on running the queue. You can prevent that behavior by disabling the [`runQueueAutomatically`](https://craftcms.com/docs/3.x/config/config-settings.html#runqueueautomatically) config setting, but you will need to come up with another way to run the queue in its stead (e.g. a cron job that runs the `craft queue/run` action every minute).
