### ISSUE TITLE
[3.x]: Bug: New matrix blocks are added to all sites, eventhough 'Only save blocks to sites they were created in' is set

### ISSUE THREAD

**Issue by bencresty** [craftcms/cms#11366]
### Description

Using a website that's up for quite some time now without change to this matrix block, 'suddenly' (meaning after keeping Craft up to date) when creating a new entry and adding matrix blocks to a matrix field, these blocks also get added to other sites on the multisite/multilocale setup.
Eventhough 'Only save blocks to sites they were created in' is set in the matrix field.

This wasn't an issue before; before these blocks only got added to the current site/locale.

### Steps to reproduce

1. Create a new entry (content) which holds a Matrix Field on a multisite/-locale setup, where Matrix field is set to 'Only save blocks to sites they were created in'
2. Add a new block to the matrix field
3. Go to another locale/site on that setup
4. Be surprised that the matrix block also appears there, eventhough it shouldn't be there

### Expected behavior

As before: when 'Only save blocks to sites they were created in' is set matrix blocks shouldn't be added to other sites/locales.

### Actual behavior

See above

### Craft CMS version

3.7.43

### PHP version

8.0.12

### Operating system and version

Windows 10

### Database type and version

MariaDb

### Image driver and version

-

### Installed plugins and versions

-

**Comment by bencresty** [comment]
> This is the intended behavior

Thanks for your response. After writing my edit response I was afraid of that. Nice to see it's not a changed thing. To me I don't get this decision tho as it's confusing that the workings are different when saving for the first time compared to saving on a later time. It's also basically not what the setting of the block field says it will do. These type of decisions aren't only confusing and so could be prone to errors, but how can we explain this to clients?! Why not always treat it the same and make it logical and do what it's saying it will do?

**Comment by brandonkelly** [comment]
It did not change in Craft 4. You’re welcome to open a discussion about it, and we can certainly reconsider it for a future release, though.

FWIW, some version of this behavior should almost certainly not change. For example, when you create a new entry, I’m fairly confident the Title field should be duplicated across all sites as a starting point. So it’s more of a question of where we draw the line.

**Comment by jornwildenbeest** [comment]
Hi @brandonkelly, is is possible this behavior changed in Craft 4.3.6.1?

Our client always used this feature to easily translate content after the update it does not work anymore.

**Comment by brandonkelly** [comment]
@jornwildenbeest Doh, just tested and apparently this did change in 4.0—unintentionally. Just fixed that for the next release.

**Comment by jornwildenbeest** [comment]
@brandonkelly That would be great, thanks a lot!

**Comment by brandonkelly** [comment]
Craft 4.3.7 has been released with that fix.
