### ISSUE TITLE
[4.x]: Migration exception on PHP 8.0.2

### ISSUE THREAD

**Issue by leigeber** [craftcms/cms#11361]
### What happened?

It appears that Symfony 6.1 has a PHP 8.1 requirement and as a Craft dependency migrations fail in a PHP 8.0 environment. Here's the first error coming from some unpacking in https://github.com/symfony/finder/blob/6.1/Finder.php#L588.

```
Error: syntax error, unexpected token ")"
```

Flagging to understand if PHP 8.1 will be the new lower limit for Craft 4 instead of the currently documented 8.0.2?

### Craft CMS version

4.0.3

### PHP version

8.0.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Craft’s `symfony/finder` requirement is `^2.8.52 || ^3.4.35 || ^4.4 || ^5.0 || ^6.0`. So yes it will pull in v6, but only if the environment allows.

You most likely ran `composer update` on an environment with PHP 8.1 installed, so `symfony/finder` v6 was pulled in. Then deployed to an environment running PHP 8.0, causing the PHP syntax error.

The best way to prevent this is to specify your target PHP version in `composer.json` (`config.platform.php`), [like we do](https://github.com/craftcms/craft/blob/main/composer.json#L40-L42) by default in the `craftcms/craft` starter project. Set it to the lowest PHP version that’s being used across all your environments. Then run `composer update`.
