### ISSUE TITLE
[4.x]: Asset Update Indexes broken - indexing hidden transform subfolders

### ISSUE THREAD

**Issue by damienbuckley** [craftcms/cms#11362]
### Description

Asset indexing seems to be trying to index all images and transforms

### Steps to reproduce

1. Utilities > Asset Indexes > Update asset indexes

### Expected behavior

Index all images, not hidden transforms directories

### Actual behavior

Index count is in thousands, clearly trying to index everything in the asset volumes, including transform sub-directories

### Craft CMS version

4.0.3

### PHP version

8.0.8

### Operating system and version

OSX 12.4

### Database type and version

MySQL 5.7.34

### Image driver and version

	Imagick @PACKAGE_VERSION@ (ImageMagick 6.9.6-2)

### Installed plugins and versions

- CKEditor 2.0.0
- Environment Label 4.0.0
- Field Manager 3.0.0-beta.1
- Freeform Pro 4.0.0-beta.9
- ImageOptimize 4.0.0-beta.3
- Mailgun 3.0.0
- Navigation 2.0.1
- Retour 4.0.1
- SEOmatic 4.0.1
- Sherlock 4.0.1
- Sprig 2.0.1
<img width="778" alt="Screen Shot 2022-06-03 at 3 48 43 pm" src="https://user-images.githubusercontent.com/728153/171795080-5ebc5e85-29b9-4477-802c-735a86530846.png">

**Comment by maxfrischknecht** [comment]
Had the same issue

**Comment by mmikkel** [comment]
@brandonkelly Yeah, files in directories beginning with an underscore are skipped, i.e. Craft will not create assets for them.

The issue is that files in underscored folders are even included in the index list, which makes indexing a lot slower because the AssetIndexer needs to chew through a ton more files (seemingly for no good reason as they are indeed "skipped"). This wasn't the case in Craft 3 (https://github.com/craftcms/cms/blob/v3/src/services/AssetIndexer.php#L131). It's actually also not the case when indexing assets on Craft 4 via the `index-assets` CLI command, only via the utility, which makes this feel like an unintended change?

**Comment by damienbuckley** [comment]
I actually didn’t get that far - just saw 1/1000~ and cancelled the index assuming it was a bug and not wanting to wait. Suspect I’m not the only one given this didn’t happen in Craft 3.

**Comment by maxfrischknecht** [comment]
Yes @brandonkelly all the transforms are listed as skipped in the finished dialogue. But it still takes time to "index" them as the screenshot shows. I only yet uploaded a handfull of images (maybe 20-30) and defined two transforms but the system is indexing over 400 images.

![Bildschirmfoto 2022-06-03 um 10 33 49](https://user-images.githubusercontent.com/38426074/171819530-e4867272-ba9c-4e92-8499-349fc9690f82.png)

**Comment by mmikkel** [comment]
@maxfrischknecht Yeah, asset thumbnails/previews are generated as transforms in Craft 4.

(A workaround for this issue is to use a separate filesystem for transforms, but I doubt that's something most sites will do.)

**Comment by damienbuckley** [comment]
@mmikkel I was actually trying that once I saw what happened but at this stage, ImageOptimize isn't working with that either. So currently I have a completely broken install…

**Comment by brandonkelly** [comment]
Fixed for the next release thanks to @mmikkel’s PR #11384 🙏🏻

**Comment by damienbuckley** [comment]
Legendary 👏🏻

**Comment by brandonkelly** [comment]
Craft 4.0.5 is out now with that fix.
