### ISSUE TITLE
[4.x]: Assets in entry can't be reordered

### ISSUE THREAD

**Issue by maxfrischknecht** [craftcms/cms#11364]
### Description

The order of selected assets in an asset field in an entry can no longer be done by drag & drop. 

### Steps to reproduce

1. Create an asset field in an entry
2. Upload at least 2 images
3. Try to reorder the images with drag & drop

### Expected behavior

A point cursor appears and let's the user reorder the images with drag & drop

### Actual behavior

The «Enable focal point» dialogue opens. (Maybe this is intended behaviour, but it leaves the question on how to create an order of images).

### Craft CMS version

4.0.3

### PHP version

8.1.5

### Operating system and version

Linux 3.10.0-962.3.2.lve1.5.52.el7.x86_64

### Database type and version

MySQL 5.7.37

### Image driver and version

Imagick 3.5.1 (ImageMagick 7.1.0-2)

### Installed plugins and versions

- Redactor 3.0.0

**Comment by wsydney76** [comment]
The images can be moved by clicking on the title and not on the image...

I think (hope) better UI is on the way, e.g. #10763

**Comment by brandonkelly** [comment]
It should have still been possible to drag assets by clicking on their thumbnails. Fixed that for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.4 is out now with that fix.
