### ISSUE TITLE
[4.x]: Skip to content button, hidden in login screen

### ISSUE THREAD

**Issue by remcoov** [craftcms/cms#11375]
### Description
When you are in the login screen (f.e. admin/login) and tab through the inputs, you end up focusing on a 'Skip to content' button, which seems like an error being there (?)

<img width="569" alt="Screenshot 2022-06-02 at 12 01 40" src="https://user-images.githubusercontent.com/48018834/171606402-e221bd0b-99aa-4653-b185-bee3ed05bbe4.png">

### Craft CMS version

4.0.2

### PHP version

8

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next Craft 3 and 4 releases.

**Comment by brandonkelly** [comment]
Craft 3.7.44 and 4.0.4 are out now with that fix.
