### ISSUE TITLE
[4.x]: DatePicker has no year selection option

### ISSUE THREAD

**Issue by drilonmaloku** [craftcms/cms#11380]
### Description
I am having a problem where I need to set an entry birth date which can be 1960 and on the datepicker there is no fast way to do that other than change on the text

### Steps to reproduce

1. Just install Craft 4.0.3 and add a date field

### Expected behavior

There must a be year option where you select the year

### Craft CMS version

4.0.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
This is definitely expected behavior right now. Feel free to post a [feature request](https://github.com/craftcms/cms/discussions/categories/ideas) for using a better date picker library that has a year selector, though.
