### ISSUE TITLE
Provide a method of grouping fields (other than tabs)

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1138]
> Created by: Timothy Kelty (timkelty@gmail.com) on 2015/04/02 12:33:05 +0000
> Votes at time of UserVoice import: 3

-----------------------------------

Solutions like SuperTable are very tempting in common situations where technically, you really want a number of fields, but from a UI perspective, it doesn't cut it.

Example:
Client requests a place to attach "Social Media Usernames" to an entry.

The 2 native options are:
1. create a new field for each type (instagram, twitter, etc)
2. create a matrix field with 2 fields:
    - dropdown to select "type"
    - text input for username

From a technical standpoint, option 1 is really what you want, because you don't want the user to be able to enter 2 rows with the same "type". However, the display of that many text small fields doesn't seem to cut it for our clients.

It would be great if, in the entry layout, you could group sets of fields, maybe give them a heading, and adjust their layout (horizontal, vertical).

This would make using third party options like SuperTable much less appealing.

**Comment by brandonkelly** [comment]
As of the next Craft 3.5 release, it will be possible to add custom headings, tips, warnings, instructions, and horizontal rules to field layouts, which should resolve this :)

<img width="343" alt="A custom Heading within a field layout" src="https://user-images.githubusercontent.com/47792/87213148-b47bf080-c2d7-11ea-861a-95cae2f2513c.png">
