### ISSUE TITLE
switch between versions of Craft

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#1139]
> Created by: Joe Pagan (joepagan@gmail.com) on 2015/03/19 11:45:37 +0000
> Votes at time of UserVoice import: 3

-----------------------------------

Sometime plugins break when updating to the latest craft, sprout forms being a good example.

Would be nice to be able to switch back to an older version of craftCMS if a new one doesn't like a plugin which is essential to a website's needs, or if there is an issue with that particular update.

I know we can roll back changes with a backed up db & files on git, but sometimes the issues don't present themselves until clients have logged in and made enough changes to the database to make it impossible to roll back that far.

So a select somewhere which would change the tables around & update/downdate the files to a particular version would be nice.

**Comment by brandonkelly** [comment]
This would require us to start creating “down” migrations, which is a big time suck, and often times not even possible.
