### ISSUE TITLE
[4.x]: Inline asset editing double click inconsistent

### ISSUE THREAD

**Issue by petenice** [craftcms/cms#11424]
### Description

Double click assets field sometimes shows preview modal, sometimes opens HUD, sometimes errors.
Uncaught TypeError: Cannot read properties of null (reading '$container')

[View screencast](https://www.screencast.com/t/vFrn9fak)

Also, cannot select text inside of HUD fields.

[Another screencast](https://www.screencast.com/t/27HpQnd4)

### Steps to reproduce

1. Upload an image to an assets field
2. Save entry
3. Double click thumbnail 
4. Sometimes it opens modal, sometimes it opens HUD

### Expected behavior

I would expect that single click opens modal, double click opens HUD

### Actual behavior

VM4716:4 Uncaught TypeError: Cannot read properties of null (reading '$container')
    at <anonymous>:4:83
    at m (jquery.js?v=1654555688:2:867)
    at Pe (jquery.js?v=1654555688:2:48866)
    at w.fn.init.append (jquery.js?v=1654555688:2:50070)
    at Object.appendBodyHtml (cp.js?v=1654555688:2:236162)
    at cp.js?v=1654555688:2:375619
(anonymous) @ VM4716:4
m @ jquery.js?v=1654555688:2
Pe @ jquery.js?v=1654555688:2
append @ jquery.js?v=1654555688:2
appendBodyHtml @ cp.js?v=1654555688:2
(anonymous) @ cp.js?v=1654555688:2
Promise.then (async)
loadAsset @ cp.js?v=1654555688:2
init @ cp.js?v=1654555688:2
e @ garnish.js?v=1654555688:2
constructor @ garnish.js?v=1654555688:2
s.constructor @ garnish.js?v=1654555688:2
s.constructor @ garnish.js?v=1654555688:2
s.constructor @ garnish.js?v=1654555688:2
_loadPreview @ cp.js?v=1654555688:2
openPreview @ cp.js?v=1654555688:2
(anonymous) @ cp.js?v=1654555688:2
dispatch @ jquery.js?v=1654555688:2
v.handle @ jquery.js?v=1654555688:2
11:47:44.744 VM4716:10 Uncaught TypeError: Cannot read properties of null (reading 'settings')
    at resizePreviewImage (<anonymous>:10:92)
    at HTMLImageElement.onload (3-test-entry-one:1:1)

### Browser

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

### Craft CMS version

4.0.4

### PHP version

8.0.18

### Operating system and version

Mac OS / Laravel Mix

### Database type and version

mySQL 8

### Installed plugins and versions

        "carlcs/craft-redactorcustomstyles": "4.0.1",
        "carlcs/craft-uielementfields": "^2.0",
        "craftcms/cms": "4.0.4",
        "craftcms/feed-me": "5.0.4",
        "craftcms/redactor": "^3.0.0",
        "craftcms/simple-text": "^3.0",
        "doublesecretagency/craft-matrixcolors": "^2.1",
        "ether/seo": "^4.0",
        "mmikkel/retcon": "^2.4.2",
        "nystudio107/craft-retour": "^4.0",
        "percipioglobal/craft-colour-swatches": "^4.1",
        "putyourlightson/craft-sprig": "2.0.1",
        "rynpsc/craft-phone-number": "2.0.1",
        "sebastianlenz/linkfield": "2.1.3-rc",
        "spicyweb/craft-neo": "^3.0",
        "verbb/navigation": "^2.0",
        "verbb/super-table": "3.0.0-beta.4",
        "vlucas/phpdotenv": "^5.4.0"

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed now for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.5 is out now with that fix.
