### ISSUE TITLE
[4.x]:  Backups not working

### ISSUE THREAD

**Issue by thisanimus** [craftcms/cms#11426]
### Description
Cannot do a backup or restore via the CLI or the UI utility in the admin area.

### Steps to reproduce

1. Attempt a backup using the cli command: `./craft db/backup` or via the backup utility at /admin/utilities/db-backup

### Expected behavior

Working backup/restore.

### Actual behavior

Errors out with: " Could not create backup: Database not backed up because the backup command is false."

### Craft CMS version

4.0.3

### PHP version

8.1.7

### Operating system and version

Ubuntu 21.10

### Database type and version

MySQL 8.0.29

### Image driver and version

Imagick 3.6.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

nothing as of yet

**Comment by angrybrad** [comment]
You've go this set to `false` in your `config/general.php` file, which disabled backups: https://craft-docs.netlify.app/docs/4.x/config/config-settings.html#backupcommand
