### ISSUE TITLE
[4.x]: Remote temp upload directories recreated on every asset field render

### ISSUE THREAD

**Issue by mattgrayisok** [craftcms/cms#11427]
### Description

Debugging some slow CP requests in a client project we found that whenever an Asset Field is rendered within a template, and the 'temp' directory for assets is set to a volume, Craft will try to recreate the directory structure for the temp path on every page load.

This was causing significant slowdowns for this particular project because the temp directory was set to a remote S3 FS and it had multiple path parts resulting in several sequential API calls to the remote storage to create directories, each taking a non negligible amount of time.

I profiled and tracked it down to this line:

https://github.com/craftcms/cms/blob/264e1aa410ed6a29e3868e8a98ca7cf951f3c85e/src/services/Assets.php#L799

Being called from:

https://github.com/craftcms/cms/blob/264e1aa410ed6a29e3868e8a98ca7cf951f3c85e/src/services/Assets.php#L922

This is a particularly pronounced issue because most remote object storage platforms don't even need the directories to be created. Maybe it's worth allowing filesystems to define whether they need directories to be pre-created? Then object-key stores can opt out and save a load of API calls.

### Steps to reproduce

1. Use a remote object storage volume
2. Set the temp upload path to use this volume
3. Add an asset field to a control panel page
4. Pages will now load slowly

### Expected behavior

Humm, I guess it'd be nice if Craft didn't try to recreate the directories during field render, but instead during the actual upload which would use the temp directory. Alternatively allow remote filesystems to opt-out of directory pre-creation (maybe this is something flysystem should be doing?)

### Craft CMS version

4.0.4

### PHP version

8.0

### Installed plugins and versions

-

**Comment by mattgrayisok** [comment]
I should add that we fixed the issue for the time being by simply changing the temp upload directory to the local temp dir instead of the volume

**Comment by brandonkelly** [comment]
How is the Assets field configured?

And what do you mean by “Craft will try to recreate the directory structure for the temp path”? Is it creating more than just the one user’s temp folder?

**Comment by brandonkelly** [comment]
This should be resolved for the next Craft 3 and 4 releases. Thanks for reporting!

**Comment by brandonkelly** [comment]
Craft 3.7.45 and 4.0.5 are out now with this change.
