### ISSUE TITLE
[3.x]: pashto (ps) is not recognized as rtl language

### ISSUE THREAD

**Issue by mihob** [craftcms/cms#11428]
### Description

pashto (ps) is not recognized as rtl language in the control panel

### Steps to reproduce

1. Try to edit a text field in a site that has pashto as language.

### Expected behavior

The text should be aligned from right to left.

### Actual behavior

The text is aligned from left to right

### Craft CMS version

Craft Pro 3.7.44

### PHP version

8.1.6

### Operating system and version

Linux 5.10.104-linuxkit

### Database type and version

MySQL 8.0.29

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-35)

### Installed plugins and versions

CP Field Inspect 1.4.4
Incognito Field 1.3.0
MatrixMate 1.4.3
Redactor 2.10.8
Sentry Logger 1.2.3

**Comment by brandonkelly** [comment]
Go to Utilities → PHP Info and search for “Intl”. Do you see any references to it?

**Comment by mihob** [comment]
The extension is installed and all locales are present. That is not the problem. Pashto is not displayed by the cms in the control panel as rtl language.

If you look here https://github.com/craftcms/cms/blob/develop/src/i18n/Locale.php in line 225 you see that "ps" is missing in the array $_rtlLanguages. 

```
/**
 * @var array The languages that use RTL orientation.
 */
private static array $_rtlLanguages = ['ar', 'he', 'ur', 'fa'];
```

**Comment by brandonkelly** [comment]
Ah sorry, I forgot that Craft was the one identifying the RTL languages and thought that info came from Intl.

Fixed for the next Craft 3 and 4 releases.

**Comment by brandonkelly** [comment]
Craft 3.7.45 and 4.0.5 are out now with that fix.
