### ISSUE TITLE
[4.x]: Error when calling the `help` command for any resave action defined via the event 

### ISSUE THREAD

**Issue by rynpsc** [craftcms/cms#11423]
### Description

When calling `help` against a commerce resave sub-command an exception is thrown. This happens for all elements, the error is not present for Craft core element resave commands.

```
php craft help resave/carts
php craft help resave/orders
php craft help resave/products
```

```
Exception 'TypeError' with message 'craft\console\Controller::getActionMethodReflection(): Return value must be of type ReflectionMethod, ReflectionFunction returned'

in /var/www/html/vendor/craftcms/cms/src/console/Controller.php:330
```

### Steps to reproduce

1. From the command line run the help command with any of the commerce sub-commands .e.g. `php craft help resave/orders
`

### Expected behavior

Help is displayed.

### Actual behavior

An exception is thrown.

### Craft CMS version

4.0.4

### Craft Commerce version

4.0.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Fixed for the next Craft release!

**Comment by brandonkelly** [comment]
Craft 4.0.5 is out now with that fix.
