### ISSUE TITLE
[4.x]: Environment variables being parsed as integers

### ISSUE THREAD

**Issue by alexmglover** [craftcms/cms#11422]
### Description

I have created a couple of environment variables that are being converted to integers, which is causing the value to be incorrectly converted.

For example: 

"0123" becomes "123" 
"+17777777777" becomes "17777777777"

### Expected behavior

I would expect the value to be output as "0123" and "+17777777777" when I use `App::env`.

### Actual behavior

Value is output as "123" and "17777777777"

### Craft CMS version

4.0.4

Here is the code causing the issue: https://github.com/craftcms/cms/blob/develop/src/helpers/App.php#L88

**Comment by brandonkelly** [comment]
Thanks for reporting that. Just tightened this up a bit for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.5 is out now with that fix.
