### ISSUE TITLE
[4.x]: If or if else statement with nothing set inside throws error

### ISSUE THREAD

**Issue by johnwbaxter** [craftcms/cms#11420]
### Description

Create an "if" statement with nothing set inside throws error *if* this is done outside the {% block content %} tag.

### Steps to reproduce

Create a if or ifelse and return nothing in one of the conditions

```
{% extends "_layouts/_layout.twig" %}

  {% if craft.app.request.segment(2) != "" %}
  
    {% else %}
       {%  set foo = "bar" %}
  {% endif %}

{% block content %}
 {# IT DOESN'T MATTER WHAT'S IN HERE #}
{%endblock %}
```

or without the {% else %}

```
{% extends "_layouts/_layout.twig" %}

{% if craft.app.request.segment(2) != "" %}

{% endif %}

{% block content %}
   {# IT DOESN'T MATTER WHAT'S IN HERE #}
{%endblock %}

```

### Expected behavior

Not to see an error

### Actual behavior

![image](https://user-images.githubusercontent.com/338729/173064705-95e4cd47-4a21-4de7-8ac8-3ba5ab8e9afa.png)

### Craft CMS version

4.0.4

### PHP version

8.0.19

### Operating system and version

Linux - 22.04 - Nitro

### Database type and version

mysql-5.7

### Installed plugins and versions

![image](https://user-images.githubusercontent.com/338729/173064982-113540e7-bad4-400a-b472-195e999a46f2.png)

**Comment by brandonkelly** [comment]
I’m not able to reproduce with your first example, and you second example contains two syntax errors:

- There is no `foo` tag. Should be `{% set foo = "foo" %}`
- You can’t have an `elseif` tag without a condition. Maybe should be `else`?

**Comment by johnwbaxter** [comment]
Sorry, in my haste to log this, I made some crap errors.

I'm going to edit the original post to make some bloody sense this time.

**Comment by brandonkelly** [comment]
Thanks. I’m able to reproduce with your new examples, however this appears to be a Twig bug. You can report over at https://github.com/twigphp/twig/issues.

**Comment by johnwbaxter** [comment]
Cool cool, thx! I've reported it and they on it - https://github.com/twigphp/Twig/issues/3715
