### ISSUE TITLE
[4.x]: Cannot update progress from queue jobs

### ISSUE THREAD

**Issue by GustavTaxen** [craftcms/cms#11434]
### Description
After migrating our site to Craft 4, our Queue jobs cannot run. Queueing a job throws this php exception:

`Typed property craft\queue\BaseJob::$_progress must not be accessed before initialization`

The relevant code in our module is:

```
  public function execute($queue): void
  {
   ...
    foreach ($this->entryIds as $entryId) {
      // Update progress spinner in Craft control panel.
      $this->setProgress(
        $queue,
        $i / $total,
        Craft::t('app', 'Entry {step, number} of {total, number}', [
            'step' => $i,
            'total' => $total,
        ])
      );
     ...
    }
  }
```
Removing the call to `setProgress` allows the job to run.

### Steps to reproduce

1.

### Craft CMS version

Craft Pro 4.0.4

### PHP version

8.0.16

### Operating system and version

Linux 5.10.104-linuxkit

### Database type and version

MySQL 10.6.7

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-16)

### Installed plugins and versions

- Feed Me | 5.0.4

**Comment by brandonkelly** [comment]
`_progress` is set from `BaseJob::init()`. Maybe you are overriding the `init()` method in your job, but not calling `parent::init()` from it?

**Comment by GustavTaxen** [comment]
No, but I do have a `__construct()`. Calling `parent::init()` from that seems to have solved the problem. Thank you!

**Comment by brandonkelly** [comment]
If you are overriding the constructor, you should call `parent::__construct()` from it, not `parent::init()`.
