### ISSUE TITLE
Force the trailing slash OFF

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1143]
> Created by: Joe Pagan (joepagan@gmail.com) on 2015/03/19 11:45:37 +0000
> Votes at time of UserVoice import: 3

-----------------------------------

Currently the config setting: "addTrailingSlashesToUrls" allows us to force the trailing slash ON when set to "true" but what if you want it off?

Currently you need to set the config setting to false then force it on at server level.

I would like this config setting to have 3 options: 
1. force on 
2. force off 
3. either is cool

**Comment by MGxpwr** [comment]
I would love to see this happening so you don't have to force this on server level.

**Comment by bryantAXS** [comment]
Running into this issue now as well pertaining to some SEO related redirects. Would love to be able and force a non-trailing slash.

**Comment by brandonkelly** [comment]
Rather than forcing it for SEO purposes, just define a [rel=canonical](https://support.google.com/webmasters/answer/139066?hl=en) link tag in your layout. If running Craft 3.5 or later, you can do this from your entry template:

```twig
{% html at head %}
{{ tag('link', {rel: 'canonical', href: entry.url}) }}
{% endhtml %}
```
