### ISSUE TITLE
[4.x]: Conditional fields' visibility not getting updated when in preview mode

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#11432]
### Description
When in `preview mode`, changing a field that controls the visibility of another field, does not have the expected result of toggling the second field's visibility.

### Steps to reproduce

1. Add a `field condition`. Let's say have a `text field` that should be visible when a `lightswitch field` is activated.
2. Open an entry with those fields and enter `preview mode`.
3. Toggle the `lightswitch field`

### Expected behavior

The text field should be visible

### Actual behavior

The text field remains hidden (It becomes visible though when the user exits `preview mode`)

### Craft CMS version

Craft Pro 4.0.4

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
This is a known issue, but not one we can fix immediately, unfortunately. Most likely will have to wait until Craft 5.

**Comment by thupsi** [comment]
Ok, no big deal. Good to know it's in your radar!

**Comment by ItagMichael** [comment]
I just noticed this issue in a big way on a very condition-heavy section. I don't suppose it would be easy to have the live preview version of the form show all fields regardless of conditions? This would at least mean that no fields are inaccessible in live preview.

**Comment by brandonkelly** [comment]
Unfortunately no, as any fields that are “hidden” due to conditionals are not present in the form at all – not simply hidden via `display: none`.

**Comment by amphibian** [comment]
Any update on this one in the roadmap? Just got bit by it today.

**Comment by brandonkelly** [comment]
This will be resolved in Craft 5.2 :tada: (#15112)

**Comment by brandonkelly** [comment]
Craft 5.2.0-beta.1 is out with those changes.
