### ISSUE TITLE
[4.x]: Deleting a user profile image also removes the interface buttons

### ISSUE THREAD

**Issue by timmyomahony** [craftcms/cms#11436]
### Description

After uploading a profile image in the control panel, if you then delete the image the thumbnail and action buttons also get deleted.
### Steps to reproduce

https://user-images.githubusercontent.com/615149/173547870-fd1fd1fa-ab4b-4de4-9ca8-445bb64fbf09.mp4

1. Visit your profile (`/admin/myaccount?site=default`)
2. Upload a new profile image
3. Once uploaded, hit "delete photo"

### Expected behavior

The photo thumbnail and interface buttons should remain.

### Actual behavior

The photo deletes but the interface disappears. 

### Craft CMS version

4.0.4

### Potential Fix

The issue seems to be with the `Craft.ImageUpload` JavaScript class. In particular the `refreshImage` function here:

https://github.com/craftcms/cms/blob/2eac9249964ccc553bf841c79b9ee44d58f16b61/src/web/assets/cp/src/js/ImageUpload.js#L81

The `response` object that is passed to this function looks like:

```js
{
  config: { ... }
  data: {
    html: "..."
  }
  headers:  { ... }
  request:  { ... }
  status:  { ... }
  statusText: { ... } 
}
```

So the `refreshImage` function should look like this instead:

```js
refreshImage: function (response) {
  $(this.settings.containerSelector).replaceWith(response.data.html);
  this.settings.onAfterRefreshImage(response);
  this.initImageUpload();
},
```

(using `response.data.html` not `response.html`)

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.0.5 is out now with that fix.
