### ISSUE TITLE
[4.x]: Javascript error in the admin causing unexpected behavior

### ISSUE THREAD

**Issue by hatyi** [craftcms/cms#11446]
### Description
Hi I'm developing a brand new Craft 4.0.4 project, and I'm constantly facing unexpected behaviors in the admin.

I'm seeing this error in my console:
`jquery.js?v=1654604143:2 Uncaught TypeError: Cannot read properties of null (reading '$container')`
I'm just guessing this is the cause of some random errors I'm opening the ticket about.

- I can't add new blocks inside a matrix block which is assigned to an entry's field layout in some scenarios. Clicking on the "+" icon when editing an entry does nothing.

### Steps to reproduce

1. I have 2 blocks with the same name / handle, one is placed inside a matrix and the other one is a Supertable type which should be in a separate field group, they have slightly different fields.

### Expected behavior

No JS issue in the console, admin works as always in Craft 3

### Actual behavior

I have 3 field groups for an entry type (Settings, Content, Hero) If I place the "standalone / supertable" hero block into the "Settings" or "Content" groups, I can not use the matrix block inside "Content", clicking on the "+" icon doesn't work, but if I create a new field group and put this hero block there, the matrix block starts working inside "Content". 

Also if I change the order of the field groups, so let's say "Content" changes with the new "Hero" so it will be like "Settings", "Hero", "Content" the issue with the matrix block appears again.

### Craft CMS version

4.0.4

### PHP version

8.1.6 cli

### Operating system and version

Ubuntu 20.04

### Database type and version

MySQL 8.0

### Installed plugins and versions

```
        "craftcms/cms": "^4.0.0.1", (locked to 4.0.4)
        "craftcms/redactor": "3.0.0",
        "verbb/navigation": "2.0.2",
        "verbb/super-table": "3.0.0-beta.4",
        "vlucas/phpdotenv": "^5.4.0" (locked to 5.4.1)
```
copied from my composer.json

![nortura test_admin_settings_fields_edit_17_site=default](https://user-images.githubusercontent.com/6324479/173833131-536b2dd3-2616-4a3a-a76f-7c29ee8fafbb.png)

![nortura test_admin_settings_fields_edit_1_site=default](https://user-images.githubusercontent.com/6324479/173833143-443ef797-5432-4f98-b4d6-e4dd3a2da3f8.png)

![Screenshot from 2022-06-15 14-47-48](https://user-images.githubusercontent.com/6324479/173833188-3065359a-0b68-4378-b407-e47bb1faafdf.png)

![Screenshot from 2022-06-15 14-36-23](https://user-images.githubusercontent.com/6324479/173833196-ec689290-ccbd-49b2-809f-c751b2c4292f.png)

**Comment by brandonkelly** [comment]
Looks like the error is coming from Super Table. Is that plugin up-to-date?
