### ISSUE TITLE
[4.x]: `$tooEarly` expects string, null given.

### ISSUE THREAD

**Issue by michtio** [craftcms/cms#11454]
### Description

Sometimes when cache is involved and setup on a site and something changes, when re-visiting the page the following error shows, this happens if one of the fields linked to SEOMatic which are important to parse the metadata have been changed.

```
TypeError: Cannot assign null to property craft\validators\DateTimeValidator::$tooEarly of type string in /home/xx/releases/20220519111253/vendor/yiisoft/yii2/caching/Cache.php:138
Stack trace:
#0 /home/xx/releases/20220519111253/vendor/yiisoft/yii2/caching/Cache.php(138): unserialize()
https://github.com/nystudio107/craft-seomatic/issues/1 /home/xx/releases/20220519111253/vendor/yiisoft/yii2/caching/Cache.php(603): yii\caching\Cache->get()
https://github.com/nystudio107/craft-seomatic/issues/2 /home/xx/releases/20220519111253/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(271): yii\caching\Cache->getOrSet()
```

After some deeper diving, I do think the issue might come from here, it would make sense if `$tooEarly` and `$tooLate` should be able to be nullable.

https://github.com/craftcms/cms/blob/develop/src/validators/DateTimeValidator.php#L46

### Craft CMS version

4.0.4

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
This should be fixed for the next release!
