### ISSUE TITLE
[4.x]: DateTimeValidator::$tooEarly and DateTimeValidator::$tooLate should be nullable

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#11455]
### What happened?

It looks like serialized, cached models can have `null` values for the `DateTimeValidator::$tooEarly` and `DateTimeValidator::$tooLate` properties:

https://github.com/nystudio107/craft-seomatic/issues/1145

This is without ever having passed in a value to either of them in the validator rules:

https://github.com/nystudio107/craft-seomatic/blob/develop/src/models/MetaBundle.php#L279

I'm thinking these properties should be nullable?

https://github.com/craftcms/cms/blob/develop/src/validators/DateTimeValidator.php#L42

```php
    /**
     * @var string user-defined error message used when the value is earlier than [[min]]
     * @since 3.5.12
     */
    public ?string $tooEarly;

    /**
     * @var string user-defined error message used when the value is later than [[max]]
     * @since 3.5.12
     */
    public ?string $tooLate;
```

### Craft CMS version

4.0.3

### PHP version

8.1

### Operating system and version

n/a

### Database type and version

MySQL 8

### Image driver and version

n/a

### Installed plugins and versions

-
SEOmatic

**Comment by brandonkelly** [comment]
Just made that change for the next release (7c925504d9700dbda58b25184702054769c011e9).
