### ISSUE TITLE
[4.0.4]: No `init` event available for the console application

### ISSUE THREAD

**Issue by geertvansoest** [craftcms/cms#11456]
### What happened?

Since upgrading to Craft 4, we receive the warning "Twig instantiated before Craft is fully initialized" after each page request. 

We developed a couple of plugins to get even more out of Craft CMS and the mentioned warning is triggered because one of those plugins. In the plugin's `init()` we register some of our own Twig extensions:

```
protected function registerTwigExtensions()
{
    $view = \Craft::$app->getView();
    $originalTemplateMode = $view->getTemplateMode();

    $view->setTemplateMode($view::TEMPLATE_MODE_SITE);
    $view->twig->addExtension(new CacheExtension());

    $view->setTemplateMode($view::TEMPLATE_MODE_CP);
    $view->twig->addExtension(new CacheExtension());

    $view->setTemplateMode($originalTemplateMode);
}
```

In Craft 3 there was no problem (and our site still works in Craft 4), but the check that prompts the warning has been added in Craft 4: 

https://github.com/craftcms/cms/commit/50f6d35d4d8297d8f7e961f498d8301805c8a06f#diff-8a3b4e5060318a461c465cc3ee7ae599aec16da92400781a9eae4377230a2f1f

We truly understand why this check has been added. And we don't want it being removed. In stead, we want to register the Twig extensions in our plugin just right after the application has been fully initialized using an event. The problem is, there is an event available in the `craft\web\Application`, but it's not in `craft\console\Application`. 

Is there a special reason for that? And is it possible to add that event for the console application too?

For now, we fixed our plugin by using the web event, even in the console, but as you can imagine this is a bit a "messy" way to solve our problem:

```
protected function registerTwigExtensions()
{
    Event::on(
        \Craft::$app->getRequest()->getIsConsoleRequest() ? ConsoleApplication::class : WebApplication::class,
        WebApplication::EVENT_INIT,
        function (Event $event) {
            $view = \Craft::$app->getView();
            $originalTemplateMode = $view->getTemplateMode();

            $view->setTemplateMode($view::TEMPLATE_MODE_SITE);
            $view->twig->addExtension(new CacheExtension());

            $view->setTemplateMode($view::TEMPLATE_MODE_CP);
            $view->twig->addExtension(new CacheExtension());

            $view->setTemplateMode($originalTemplateMode);
        },
    );
}
```

### Craft CMS version

4.0.4

### PHP version

8.0.20

**Comment by brandonkelly** [comment]
The `init` event is triggered centrally by `craft\base\ApplicationTrait`, which is shared by both `craft\web\Application` and `craft\console\Application`:

https://github.com/craftcms/cms/blob/623f8899b25aa957be7ec1f59cad7a11e0599499/src/base/ApplicationTrait.php#L1475-L1478

Traits aren’t allowed to define their own constants, so we just had to choose a place to define the `EVENT_INIT` constant, and chose `craft\web\Application`. It’s perfectly fine to reference that constant for console requests as well though.

Here’s all your event code needs:

```php
Craft::$app->on(Application::EVENT_INIT, function() {
    // ...
});
```
