### ISSUE TITLE
[4.x]: CP Sidenav Structure

### ISSUE THREAD

**Issue by forcehobbit** [craftcms/cms#11460]
### Description

New Sections are not correctly categorized by section type in the entries CP sidebar.

### Steps to reproduce

1. Customize the table columns to be displayed in the entries view.
2. Create a new section (no matter which type)

### Expected behavior

The newly created section should be correctly categorized in the entries CP sidebar.

### Actual behavior

The newly created section is not correctly categorized in the entries CP sidebar.

![image](https://user-images.githubusercontent.com/11943087/174535265-7550d166-b652-4a57-ad07-5cf805b50b36.png)

### Craft CMS version

4.0.4

### PHP version

8.0.18

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
That’s what Craft will do by default, but once you’ve opened the “Customize…” modal and saved it, the source order is considered user-defined, and the default order will stop being used.
