### ISSUE TITLE
[3.x]: Assets added with dynamic paths remain in temporary uploads

### ISSUE THREAD

**Issue by anita-chouhan** [craftcms/cms#11462]
### Description
We’re facing an issue with the dynamic Asset location paths. We have an Asset field in a _Vizy_ block that is inside a Matrix block. If we try to upload an Asset file while adding/editing an entry after adding the Matrix field to an entry type, it remains in the *Temporary Uploads* folder instead of transferring to the correct location. I tried the *Default Asset Location* dynamic path values as `{owner.slug}` , `{owner.owner.slug}`  and `{now|date('Y')}` . None of these worked.

I performed some tests and found that the issue does not exist when using *Craft CMS* version 3.7.13. I think that changes made in later versions of *Craft CMS* had an impact on the dynamic path construction for *Assets*.

I have reported the [[issue](https://github.com/verbb/vizy/issues/80)](https://github.com/verbb/vizy/issues/80) with the _Vizy_ plugin as well.

### Craft CMS version

3.7.44

### PHP version

7.4.27

### Operating system and version

Darwin 20.6.0

### Database type and version

MySQL 5.7.37

### Image driver and version

GD 7.4.27

### Installed plugins and versions

- Vizy Plugin: 1.0.15

**Comment by brandonkelly** [comment]
Craft 3.7.45 and 4.0.5 are out now with that fix.

**Comment by anita-chouhan** [comment]
After upgrading to Craft 3.7.45, it worked. Thank you for providing the fix.

**Comment by anita-chouhan** [comment]
**Update**

I performed some tests and found that when we upload an asset for the **first time** into the Asset field (inside *Vizy* block in *Matrix* field) and the *Default Asset Location* has a dynamic path value, an error message stating "Asset can’t be blank." appears.

After another try, everything is fine. See the image 
<img width="428" alt="error" src="https://user-images.githubusercontent.com/30666052/175231552-2c457edc-a6de-4547-9a98-d63eb69a284f.png">
below:
