### ISSUE TITLE
[3.x]: Autosave Merge Issues with Localized Fields

### ISSUE THREAD

**Issue by sidedwards** [craftcms/cms#11466]
## 🐛 Bug description

When "Autosave" is enabled, localized blocks and fields often get reverted or duplicated when applying drafts after the current Entry is unintentionally autosaved.

In both instances, clicking "Discard changes" seems to correct the issue.

### Demo 1

1. Given an Entry with localized Matrix blocks, click "Create a draft"
2. Remove the localized blocks and add two new blocks
3. Click "Save draft"
4. Open the original Entry and click on a field while the page is loading to trigger the draft autosave
5. Open up the recently created draft and click "Apply draft"
6. See error. Localized blocks from both the draft and original Entry are present

### Demo 2

1. Given an Entry with localized Matrix blocks, click "Create a draft"
2. Update the values within the existing localized blocks
3. Click "Save draft"
4. Open the original Entry and click on a field while the page is loading to trigger the draft autosave
5. Open up the recently created draft and click "Apply draft"
6. See error. The localized fields from the draft are reverted to their original values even though no changes were made in the current Entry.

### Demo 1

https://user-images.githubusercontent.com/11489608/174638982-084e56e4-87d1-4b8d-af53-eabd6c9e8908.mp4

### Demo 2

https://user-images.githubusercontent.com/11489608/174641190-8408791f-55ed-46e4-aa83-3b3712df9301.mp4

## 🔗 References

- #9962

### Craft CMS version

3.7.44

**Comment by brandonkelly** [comment]
I’m seeing two issues here, which are probably related.

1. When you go back to the “Current” revision, a provisional draft should **not** be getting autosaved just by clicking on the form. Drafts are only autosaved when a form value has actually changed.
2. The provisional draft is showing that all fields have been edited (the blue lines), when none of their values should have changed.

Can you try disabling your Grammarly browser extension, and see if those issues persist?

**Comment by sidedwards** [comment]
Hey @brandonkelly, thanks for the quick response. I disabled Grammarly and tested again.

1. I noticed that autosave is triggered if you click within the form before the page is completely loaded. The example below has the propagation method "Save entries to all sites enabled" and a localized plain text field.
2. I noticed the same, but I'm not sure what is causing that issue.

Let me know if there is any other information that I can provide to help debug.

### 📚 Resources

https://user-images.githubusercontent.com/11489608/175044576-5dc00870-1a12-45dd-9159-0b2d5383d4e2.mp4

**Comment by brandonkelly** [comment]
Is “Localized Plain Text” a Vizy field by chance?

**Comment by sidedwards** [comment]
Nope, just a standard text field. Although, I also noticed that Vizy would trigger an autosave without clicking into any fields.

I also tested without the localized plain text and could still trigger the autosave by clicking on the localized "Title" field before the page finished loading.

### 📚 Resources

https://user-images.githubusercontent.com/11489608/175055102-9a412af8-992c-4c9a-a6b8-d959e989e408.mp4

**Comment by brandonkelly** [comment]
If you disable Vizy (even though it’s not in use) does this still occur?

**Comment by brandonkelly** [comment]
Managed to reproduce, and just released Craft 3.7.45.1 and 4.0.5.1 with a fix.

**Comment by sidedwards** [comment]
Awesome, thanks @brandonkelly 🙌
