### ISSUE TITLE
[3.x]: Searching in Matrix field doesn't work

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#11478]
### Description

Searching in matrix blocks doesn't work. I have a single that has a matrix.

### Steps to reproduce

1. Create a single with a matrix block, and fill it (in my case i have a FAQ matrix with a question and answer field)
2. Make sure matrix field and subfields are searchable, and search index is generated
3. `{% set questions = craft.entries.section('serviceFaq').one().serviceFaq.search("*#{query}*").orderBy('score').all() %}` returns zero results
4. `{% set questions = craft.entries.section('serviceFaq')search("*#{query}*").orderBy('score').all() %}` also returns zero results

### Expected behavior

`{% set questions = craft.entries.section('serviceFaq').one().serviceFaq.search("*#{query}*").orderBy('score').all() %}` should return the matrix blocks

Also, `{% set questions = craft.entries.section('serviceFaq').one().serviceFaq.orderBy('score').all() %}` DOES work (no searching)

### Actual behavior

No results are returned

### Craft CMS version

Pro 3.7.45

### PHP version

8.1.7

### Operating system and version

Ubuntu 20 (Linux 5.10.104-linuxkit)

### Database type and version

PostgreSQL 12.7

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.10-23)

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
I’m still unable to reproduce this. Even tried truncating the `searchindex` table, verifying I wasn’t getting any results, then rebuild the search indexes, and verified I’m getting expected results.

Try running the following commands, and see if that helps:

```sh
php craft resave/entries --update-search-index
```

```sh
php craft clear-caches/data
```

If it still doesn’t work after that, I’d guess that a plugin or module may be getting involved in search keyword indexing, and possibly preventing Matrix content from getting indexed properly.

**Comment by boboldehampsink** [comment]
@brandonkelly resave/entries did the trick! I tried resaving in the cp - but that didn't work. I found out that that only worked when altering a field (probably due to the delta updates)
