### ISSUE TITLE
[4.0.5]: Category titles displayed as category ID following selection of "create and add another" (Multi-Site Setup)

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#11476]
### Description
The category ID appears to be displayed in place of the category title (for categories listed on the categories listing page) when switching to a different site (than the site that was originally selected when the category was created), if the category was originally created following selection of the create category option "create and add another" instead of clicking on "create category".

### Steps to reproduce

1. Create an initial category (e.g. named "test 1"), and then select "create and add another" from the create category dropdown
2. For the second category (e.g. named "test 2"), add the title and then click "create category"
3. When viewing the two categories for the selected site they display as expected
4. When selecting a different site from the dropdown (on the categories page) the second category created is displayed as the category ID and not the title, i.e. "test 2"
5. This is also the case when switching back to the original site (the category ID is displayed as the title instead of "test 2")

If you then click on the category (i.e. test 2) which has the ID as the title, it opens the edit category page but nothing is displayed for the category title or slug.

What is also interesting is when originally creating the categories, if you don't select the "create and add another" but instead click the button "create category" (for test 1 and test 2) then these titles display correctly when switching to a different site.

<img width="1186" alt="CleanShot 2022-06-22 at 13 04 04@2x" src="https://user-images.githubusercontent.com/2505643/174934662-1e6d0f8e-ced9-4c23-b48a-ffe92adf99b5.png">

<img width="1185" alt="CleanShot 2022-06-22 at 13 04 54@2x" src="https://user-images.githubusercontent.com/2505643/174934729-7796c594-b9a3-4bad-a6dc-b966dddcc031.png">

<img width="384" alt="CleanShot 2022-06-22 at 13 05 17@2x" src="https://user-images.githubusercontent.com/2505643/174934768-3d6fafd3-5640-4cd7-ba11-d72394dd71c1.png">

<img width="365" alt="CleanShot 2022-06-22 at 13 05 38@2x" src="https://user-images.githubusercontent.com/2505643/174934842-db28122e-71fb-43b2-819b-caee3c99a35a.png">

### Craft CMS version

4.0.5

### PHP version

8.1

**Comment by brandonkelly** [comment]
Thanks for reporting! That’s fixed now for the next release.
