### ISSUE TITLE
[3.x]: __HOME__ entry does not show preview

### ISSUE THREAD

**Issue by joshwalsh** [craftcms/cms#11487]
### Description

If you have an entry, which is not a single, which acts as the homepage using the `__home__` url slug, the live preview does not function.   It gives you a 404 within the preview window.

### Steps to reproduce

1. Create an section, which is not a single. 
2. Create an entry within that section with the slug `__home__`
3. Open the entry and click the preview button

# Expected behavior

If you change the slug to something not `__home__` you see the appropriate preview.  I would expect it to work the same way with the home slug.

### Actual behavior

404

### Craft CMS version

3.7.44

### PHP version

8.1.5

### Database type and version

Mysql

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
What is the section’s Entry URI Format?

**Comment by joshwalsh** [comment]
Just simply `{slug}`

![Screen Shot 2022-06-22 at 4 25 11 PM](https://user-images.githubusercontent.com/19155/175129597-b2d8cb63-18c9-4eef-baf0-7139f47830d3.png)

**Comment by brandonkelly** [comment]
And what’s the preview target’s URL format?

**Comment by joshwalsh** [comment]
Hey @brandonkelly, the same, just `{slug}`

<img width="1140" alt="Screen Shot 2022-06-23 at 1 28 34 PM" src="https://user-images.githubusercontent.com/19155/175359177-89e962f1-da4d-4765-9902-263caa68336f.png">

**Comment by brandonkelly** [comment]
That’s your issue. Change it to `{url}` and it should start working as expected.
