### ISSUE TITLE
[4.x]: search not working on commerce product categories

### ISSUE THREAD

**Issue by acalvino4** [craftcms/cms#11497]
### Description
Making a field searchable doesn't seem to actually make entries searchable by that field.

### Steps to reproduce
Using the demo SpokeAndChain site, check the box on a custom field (such as Colors Category) to make it searchable, and save.
![image](https://user-images.githubusercontent.com/43254861/175382870-bf011e25-3bed-4ada-a0c9-7edc4af0f90b.png)

For good measure, run `php craft resave/entries --update-search-index` to ensure indexes are updated.
Go to Commerce>Products and search for a color, such as Orange or Black

### Expected behavior
See search results populate with any bikes that have the Orange or Black category 

### Actual behavior
I get no results
![image](https://user-images.githubusercontent.com/43254861/175382755-9607f293-b200-4597-874a-9f8589d956bd.png)

### Craft CMS version

Craft Pro 4.0.5.1

### PHP version

8.1.6

### Operating system and version

Linux 5.10.104-linuxkit (Nitro)

### Database type and version

MySQL 8.0.27

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-16)

### Installed plugins and versions

"php": ">=8.0.2",
"craftcms/aws-s3": "^2.0.0",
"craftcms/cms": "^4.0.0",
"craftcms/commerce": "^4.0.0",
"craftcms/redactor": "^3.0.0",
"craftcms/store-hours": "^3.0.0",
"craftcms/yii2-dynamodb": "^2.0.0",
"fakerphp/faker": "^1.9",
"mead-steve/mono-snag": "^4.1",
"nystudio107/craft-seomatic": "^4.0.0-beta.8",
"nystudio107/craft-twigpack": "^4.0.0-beta.2",
"oberon/starfield": "^2.0",
"putyourlightson/craft-sprig": "^2.0.0-beta.1",
"solspace/craft-freeform": "4.0.0-beta.12",
"verbb/default-dashboard": "^2.0.0-beta.1",
"vlucas/phpdotenv": "^3.4.0"

**Comment by brandonkelly** [comment]
> For good measure, run `php craft resave/entries --update-search-index` to ensure indexes are updated.

Close! You do need to run this command to get the search index updated for existing products after you change the fields’ Searchable settings, however in this case it needs to be `resave/products`, not `resave/entries`, since Commerce products are what needs to be updated.
