### ISSUE TITLE
[3.x]: `canonical` should be a reserved field handle

### ISSUE THREAD

**Issue by rungta** [craftcms/cms#11503]
### Description

It appears that elements now have a `canonical` property (added in 3.7?). This results in unexpected behaviour if the project also has a field with the handle `canonical` added to it. In some cases `entry.canonical` returns whatever the field is set to, in other cases it points to, as the docs say, _the canonical element, if one exists for the current site_.

### Steps to reproduce

1. Create a field with the handle `canonical`, say of type _Plain Text_.
2. Add it to one or more entry types
3. Try accessing `entry.canonical` in the Twig templates across a mixture of entries with the field and without the field.

### Expected behavior

Since canonical is a public property of the base Element class we should probably not be permitted to create fields with that handle. 

### Craft CMS version

3.7.45.1

### PHP version

7.4.28

### Operating system and version

Darwin 20.6.0

### Database type and version

MySQL 5.7.34

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-27)

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just made that change for the next Craft 3 and 4 releases (07af564fb53dd3ed3b055d6cc277ee96abd4b5e1).

**Comment by brandonkelly** [comment]
Craft 3.7.46 and 4.0.6 have been tagged with that change.
