### ISSUE TITLE
how can I edit the alt text, change the description by image in craft4?

### ISSUE THREAD

**Issue by DianyelaMaldonado** [craftcms/cms#11504]
### What happened?

Before in craft 3, when wanting to change the alt to the image, the field of my image double-clicked it and the option to edit the alt appeared, in craft 4 where can I see the option to edit?

### Craft CMS version

4

### Installed plugins and versions

-

**Comment by DianyelaMaldonado** [comment]
The answer is that now it is by clicking on the title and not on the image :D

**Comment by brandonkelly** [comment]
4.0.0 introduced a bug where double-clicking on an asset’s thumbnail was showing the preview modal, rather than its slideout editor (#11424). Fixed in 4.0.5, released a couple days ago!
