### ISSUE TITLE
[4.0.5.2]: Caching issue - queries

### ISSUE THREAD

**Issue by DenyEs** [craftcms/cms#11508]
### Description

I noticed when I switch from dev mode to production, my number of queries according to debug bar increases instead of decreasing. I have cache tags around navigation loop on header and footer of the website. On craft 3, number of queries, coming from dev to production, significantly dropped. I do have 'enableTemplateCaching' set to false on dev mode and set to true on production mode.

### Steps to reproduce

1. Create some entries
2. Create a loop to go over those entries in the template.
3. Check number of queries in dev mode
4. Switch to production mode
5. Check queries again

### Expected behavior
Queries will decrease and site should feel / be quicker

### Actual behavior
Performance is more or less the same and number of queries goes up by around 20.

### Craft CMS version

4.0.5.2

### PHP version

8.1.5

### Operating system and version

macOS 12.4

### Database type and version

MySQL 8.0.28

**Comment by brandonkelly** [comment]
> I do have 'enableTemplateCaching' set to false on dev mode and set to true on production mode.

Maybe double-check that you don’t have it backwards (setting `enableTemplateCaching` to `true` for Dev Mode rather than for production). And make sure that Craft is properly identifying which environment is which.

**Comment by DenyEs** [comment]
> > I do have 'enableTemplateCaching' set to false on dev mode and set to true on production mode.
> 
> Maybe double-check that you don’t have it backwards (setting `enableTemplateCaching` to `true` for Dev Mode rather than for production). And make sure that Craft is properly identifying which environment is which.

Solved! Thank you Brandon! It turned out that for some reason my .env file had ENVIRONMENT in it instead of CRAFT_ENVIRONMENT, therefore it didn't properly identify it. Apologies for that.

**Comment by brandonkelly** [comment]
No worries :) Glad you got it sorted!
