### ISSUE TITLE
[3.x]: Slow save times on entries with revisions enabled

### ISSUE THREAD

**Issue by tekstrand** [craftcms/cms#11501]
### Description
We're seeing very slow entry save times when entry revisions are enabled for a section that has a Neo field in the field layout. Our field has 42 blocks, and some entries will use upwards of 200 total blocks. Save times range from 20-120+ seconds. Turning revisions off shortens the save time to under 10 seconds.

### Steps to reproduce

1. Create a neo field with some blocks
2. Create a section, enable revisions, add the neo field to it
3. Create an entry in your new section, add lots of blocks to this entry, and save it. Somewhere around 60-100 blocks for us (it will vary based on number of fields, type of field, in each block) we start seeing timeouts on our production servers at 60 seconds of execution time.
4. Turn revisions off for the section
5. Resave the entry and note the difference in save time

### Expected behavior
Enabling revisions for entries should not dramatically impact save times

### Actual behavior
Save times appear to be 15-30x when revisions are enabled

### Craft CMS version

3.7.x

### PHP version

7.4

### Database type and version

mysql 8

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
We significantly improved revision performance in Craft 4 – see #10589. Unfortunately the change involved breaking changes under the hood, so the same improvements cannot be made to 3.x.
