### ISSUE TITLE
The directory doesn't exist [3.7.45.1]: 

### ISSUE THREAD

**Issue by kaspar-allenbach** [craftcms/cms#11500]
### Description
- Pushed a craft project via github actions to the server
- Loacally everything is fine and dandy (as always).

### Steps to reproduce

1.b Copy a working project onto the server

### Expected behavior
The Site is suposed to run

### Actual behavior
The site shows the following error:

```
yii\base\InvalidConfigException: The directory does not exist:  in /public_html/atelier-shop/vendor/yiisoft/yii2/web/AssetManager.php:232
Stack trace:
#0 /public_html/atelier-shop/vendor/yiisoft/yii2/web/AssetManager.php(542): yii\web\AssetManager->checkBasePathPermission()
#1 /public_html/atelier-shop/vendor/craftcms/cms/src/web/AssetManager.php(123): yii\web\AssetManager->publishDirectory('/...', Array)
#2 /public_html/atelier-shop/vendor/yiisoft/yii2/web/AssetManager.php(474): craft\web\AssetManager->publishDirectory('/...', Array)
#3 /public_html/atelier-shop/vendor/craftcms/cms/src/web/AssetManager.php(35): yii\web\AssetManager->publish('/...', Array)
#4 /public_html/atelier-shop/vendor/craftcms/cms/src/web/AssetManager.php(67): craft\web\AssetManager->publish('@nystudio107/tw...')
#5 /public_html/atelier-shop/vendor/nystudio107/craft-twigfield/src/services/AutocompleteService.php(94): craft\web\AssetManager->getPublishedUrl('@nystudio107/tw...', true)
#6 /public_html/atelier-shop/vendor/nystudio107/craft-twigfield/src/Twigfield.php(98): nystudio107\twigfield\services\AutocompleteService::getTwigfieldPublishUrl()
#7 /public_html/atelier-shop/vendor/nystudio107/craft-twigfield/src/Twigfield.php(78): nystudio107\twigfield\Twigfield->configureModule()
#8 /public_html/atelier-shop/vendor/yiisoft/yii2/base/Application.php(295): nystudio107\twigfield\Twigfield->bootstrap(Object(craft\web\Application))
#9 /public_html/atelier-shop/vendor/craftcms/cms/src/web/Application.php(116): yii\base\Application->bootstrap()
#10 /public_html/atelier-shop/vendor/yiisoft/yii2/base/Application.php(271): craft\web\Application->bootstrap()
#11 /public_html/atelier-shop/vendor/craftcms/cms/src/web/Application.php(93): yii\base\Application->init()
#12 /public_html/atelier-shop/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#13 /public_html/atelier-shop/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct(Array)
#14 [internal function]: yii\base\Application->__construct(Array)
#15 /public_html/atelier-shop/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#16 /public_html/atelier-shop/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#17 /public_html/atelier-shop/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#18 /public_html/atelier-shop/vendor/craftcms/cms/src/Craft.php(61): yii\BaseYii::createObject(Array, Array)
#19 /public_html/atelier-shop/vendor/craftcms/cms/bootstrap/bootstrap.php(247): Craft::createObject(Array)
#20 /public_html/atelier-shop/vendor/craftcms/cms/bootstrap/web.php(51): require('/...')
#21 /public_html/atelier-shop/www/index.php(31): require('/...')
#22 {main}
```

I don't think there is any folder missing.

1. I can delete the vendor folder and execute `composer install` on the server without any errors, and it still doesn't work.

### Craft CMS version

3.7.45.1

### PHP version

7.4.29

### Installed plugins and versions

-

**Comment by thupsi** [comment]
Doublecheck your environment variables, aliases and PHP constants in production. Specifically ``CRAFT_BASE_PATH`` or the ``@vendor`` alias, or something related to those. From the output it seems that Craft is looking for the ``vendor`` folder inside the ``public_html`` folder, which _might_ be a clue that something is amiss, although that depends on your hosting provider folder structure.

**Comment by brandonkelly** [comment]
Looks like maybe `nystudio107/craft-twigfield` didn’t get fully installed for some reason. Maybe try running `composer update` locally and redeploy.

**Comment by brandonkelly** [comment]
Just came across nystudio107/craft-twigfield#2, which looks like the same issue, and a fix has been tagged. So `composer update` will fix that for sure.

**Comment by khalwat** [comment]
Here's the fix details:

I'm really sorry about this, we didn't catch it in local dev because it apparently rears its ugly head only right after first install/update.

Addressed in: https://github.com/nystudio107/craft-twigfield/commit/ba5a1044af3d49217f801d04316fd40626d991aa

Released as Twigfield 1.0.8: https://github.com/nystudio107/craft-twigfield/releases/tag/1.0.8

You should be able to do:

```
composer update nystudio107/craft-twigfield
```

...and it'll pull down the latest version of Twigfield (1.0.8 is the version with the fix in it). If for some reason it gets stubborn, you can do:

```
composer require nystudio107/craft-twigfield "^1.0.8"
```

If you're able to verify for me that the above fix works for you, I'd appreciate it!

**Comment by khalwat** [comment]
If you still have this issue, check to see if you see a line like this after doing `composer update nystudio107/craft-twigfield`:

```
Do you trust "yiisoft/yii2-composer" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] 
```

If so, you need to update the `allow-plugins` in your `composer.json` as per:

https://github.com/craftcms/cms/issues/11500#issuecomment-1165688915

Also you should say `y` to the question it's asking, otherwise Twigfield can't be properly installed.

**Comment by kaspar-allenbach** [comment]
Yes. It is fixed when I execute `composer update`. Thanks for your efforts. 🙏
