### ISSUE TITLE
[4.1]: Running craft install in non-interactive mode with existing project-config fails

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#11513]
### Description

Taking a quick look into 4.1 dev, using a starter project. 

We used to run this command:

`php craft install --interactive=0 --username=admin --password=password --email=admin@example.com`, which fails now:

![image](https://user-images.githubusercontent.com/60010597/176136555-68affd1c-2b98-48ec-8e8e-420fb64ec39a.png)

Confused: Name of what? Site Name I guess?

Those params should not be mandatory if already defined in existing project config

### Steps to reproduce

1. Run craft install -interactive=0 with project config present

### Expected behavior

Should not require siteName/language.

### Actual behavior

Both are required params even if already defined in project config.

Error message does not match actual parameter (Name - siteName)

/Aylin

### Craft CMS version

4.1.x-dev

### PHP version

8.1.5

### Operating system and version

Windows 10

### Database type and version

MySQL 5.7.14

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-18)

### Installed plugins and versions

none

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just fixed for the next release.
