### ISSUE TITLE
[4.x]: error thrown when applying conditions 

### ISSUE THREAD

**Issue by magnessjo** [craftcms/cms#11518]
### Description

Error: Call to a member function getConfig() on null in craftcms/cms/src/base/FieldLayoutComponent.php:213

### Steps to reproduce

1. Create a condition field - Make a dropdown field with multiple options.  Make an additional field - have the field be conditional based on the dropdown fields value. 

### Craft CMS version

4.1.0.1

### Installed plugins and versions

- Neo, custom module, calendar, feed me.

**Comment by brandonkelly** [comment]
Sorry about that, I can see how that could have happened. Just released Craft 4.1.0.2 with a fix.
