### ISSUE TITLE
[4.x]: Upgrading from Craft 4.0.6 to 4.1.0 - 502 Bad Gateway

### ISSUE THREAD

**Issue by magnessjo** [craftcms/cms#11514]
### Description

server throwing a 502 after upgrade

### Steps to reproduce

1. Update all plugins and craft to the latest before 4.1.0
2. Then run update for Craft 4.1.0

### Craft CMS version

4.1.0

### PHP version

8.1.6

### Operating system and version

OS

### Database type and version

Mac 13.0 beta v2

### Image driver and version

GD 8.1.6

### Installed plugins and versions

-

NEO 3.1.5

**Comment by magnessjo** [comment]
@brandonkelly - it's not the module (technically a plugin in this repo).  I have removed it, cleared cache, did a rain dance and the error persists.  

The project experiencing the issue is still in early draft state (mostly only front end development).  Other production sites with much more complexity (custom module, OAuth, etc) are able to be updated to 4.1 without issue.  

Happy to provide any code/db/etc but don't want to lead you down a rabbit hole.  I'll still crossing things off my list but confident that it's not local env or module.

**Comment by RyanRoberts** [comment]
Same problem here, no custom module but I do have various plugins installed.

**Comment by brandonkelly** [comment]
We were able to reproduce with someone’s database, and just released Craft 4.1.0.1 with a fix. Thanks everyone!

**Comment by RyanRoberts** [comment]
> We were able to reproduce with someone’s database, and just released Craft 4.1.0.1 with a fix. Thanks everyone!

This was the problem I was having, updating fixed it indeed.
