### ISSUE TITLE
[4.x]: Uploaded assets producing a large character name

### ISSUE THREAD

**Issue by moondawg69** [craftcms/cms#11530]
### Description

Uploading an asset now changes the title of the image to a long string of characters, not respecting the file name, as was the usual result.

### Steps to reproduce

1. Upload a .jpg directly on to a field. File was called: start-up-facts.jpg

### Expected behavior

Asset title respects the name of the file as near as.

### Actual behaviour

Asset named to on upload: Asset62bdb8e47b94c0 11786851

### Craft CMS version

4.1.0.2

### PHP version

8.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting! This is fixed for the next release (via #11529).

**Comment by brandonkelly** [comment]
@tommysvr Can you post a new GH issue about that?
