### ISSUE TITLE
Make "Date Modified - Descending" the default sort order for assets

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1153]
> Created by: Christian (seelbach@gmx.de) on 2015/03/09 00:49:13 +0000
> Votes at time of UserVoice import: 2

-----------------------------------

**Comment by iamcyberio** [comment]
This definitely addresses one specific issue of finding and selecting your most recently uploaded assets but I would suggest this along with a setting to change the default sorting in settings. This would target the main concern I'm sure most people working in craft have but also give a tool that could solve any developers issue with asset/field sorting.

**Comment by samjoneill** [comment]
@angrybrad This is something we've had clients request. Is there any chance of it being implemented?

**Comment by brandonkelly** [comment]
Added for the next release! Going with Date Uploaded rather than Date Modified, though. (Worth mentioning that indexes will always remember your last-selected setting though, so if you don’t like the default, all you have to do is change it, and it will stay that way each time you reload.)

**Comment by jamiewade** [comment]
@brandonkelly @angrybrad Can we also introduce this for Entries / Users?

For users who haven't sorted items yet, and therefore won't have a default set yet, I would assume the vast majority would want to see the most recent items first. However when you click the Date Modified / Last Login column, the first sorting order is oldest first. As a default I'm not sure how useful that is?

**Comment by brandonkelly** [comment]
@jamiewade Good point. Entries’ Channel section sources were already sorted by Post Date - Descending by default, but only until a new sort option was selected. Going forward, all built-in element types’ date sort options will sort themselves in descending order by default when manually clicked on.

**Comment by brandonkelly** [comment]
Craft 3.5.9 is out now with this change.
