### ISSUE TITLE
[4.x]: Unable to get categories group title from GraphQL

### ISSUE THREAD

**Issue by tomascordero** [craftcms/cms#11535]
### Description
When running a query on categories I'm able to get the `groupId` as well as the `groupHandle` for each category. However it appears that there's no way to get the group's title (ex: `groupTitle`). 

### Steps to reproduce

1. Create a GQL query for categories
2. Return `groupTitle` for the categories

```GraphQL
query Categories {
  categories {
    id
    title
    uri
    groupTitle
    groupHandle
  }
}
```

### Expected behavior
I'd expect to be able to get `groupTitle` from GraphQL same as getting the title for any other type.

### Actual behavior
`groupTitle` returns an error `"message": "Cannot query field \"groupTitle\" on type \"CategoryInterface\". Did you mean \"groupHandle\" or \"groupId\"?",`

### Craft CMS version

4.1.0.2

### PHP version

8.1.2

### Operating system and version

Linux 5.4.0-91-generic

### Database type and version

PostgreSQL 13.5

### Image driver and version

Imagick 3.5.1 (ImageMagick 6.9.10-23)

**Comment by brandonkelly** [comment]
Not a bug… `groupTitle` is not a supported category group property. In general the GraphQL API only exposes content, not structural info about the project.
