### ISSUE TITLE
[4.1.0.2]: New Categories Created and "Enabled for One Site" Show the Category Title as Category ID for Other Sites

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#11546]
For a Multi-Site setup...

### Steps to reproduce

1. Create a category
2. Toggle "Enabled for All Sites" to "Off"
3. Toggle "On" for a single site
4. Save the category

When in the category listing section and toggling other sites the new category title is displayed as ID for every other site other than the site it was enabled for.

### Craft CMS version
4.1.0.2

**Comment by richhayler** [comment]
This was definitely happening in my case. I was giving the category a title and this title was only being displayed for the site I had "Enabled" if on. For all other sites, where the category was not enabled, the title of the category was its ID. Having said that I reran the scenario now and I also can't reproduce the problem. Happy for this to be closed. If I can get it to reoccur I will capture a video to demonstrate the issue. Thanks for looking into this.

**Comment by brandonkelly** [comment]
Maybe just a recurrence of #11476 on a site you hadn’t updated to 4.0.5.1+ yet?

**Comment by richhayler** [comment]
Thanks for the question @brandonkelly. It was definitely on a Multisite setup running 4.1.0.2.

**Comment by brandonkelly** [comment]
Alright, well I’ll close this for now, but let me know if you can come up with steps to reproduce.
