### ISSUE TITLE
[4.x]: Uploading asset in a matrix or Neo field loses file title and sets to fallback

### ISSUE THREAD

**Issue by zizther** [craftcms/cms#11541]
### Description
I have only noticed this issue since updating from 4.0.6 to 4.1.0.2
I have asset fields within matrix and Neo fields. When I upload a file by any form of upload (drag and drop or via the modal) it will not use the file name as the title, it instead fallbacks to something like `Asset62bf3a589a9a66 52087915`

Asset fields outside of matrix and Neo save the asset with the title using the file name, it is only the asset fields within matrix or Neo fields I am having issues with.

Additionally uploading an asset via the Asset section work fine.

### Craft CMS version

4.1.0.2

### PHP version

8.1.1

### Database type and version

MySQL

### Installed plugins and versions

-
Neo 3.1.5

**Comment by brandonkelly** [comment]
This was also reported by #11530 and fixed for the next release :)

**Comment by brandonkelly** [comment]
For posterity, Craft 4.1.1 is out now with that fix.
