### ISSUE TITLE
[4.x]: Status filtering not working for element with custom statuses

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#11545]
### Description
We have a custom element type that has it's on statuses but when trying to filter on it in the cp, the filter doesn't work.
If I look to the POST request that is getting send to get the elements `index.php?p=start/actions/element-indexes/get-elements` 
the status criteria that is getting passed is always null, doesn't matter what status I select.
```JSON
{
  "context": "index",
  "elementType": "white\\translate\\elements\\Translation",
  "source": "*",
  "criteria": {
    "siteId": 1,
    "search": null,
    "offset": 0,
    "limit": 100,
    "status": null,
    "locale": "en-US"
  },
  "disabledElementIds": [],
  "viewState": {
    "mode": "table",
    "order": "translate_translations.key",
    "sort": "asc",
    "orderHistory": [
      [
        "translate_translations.dateCreated",
        "asc"
      ]
    ]
  },
  "paginated": 1
}
```
Except the filtering the statuses does work correctly and the elements are getting mapped correctly to the right status
### Steps to reproduce

1.have an element type with custom statuses
2. try to filter on a status in the cp
3. elements aren't getting filtered and it keeps showing all the elements

### Expected behavior
When filtering only the items with the specific status should be shown

### Craft CMS version

4.x

### PHP version

8.0/8.1

**Comment by brandonkelly** [comment]
Does your element’s `defineSources()` method include `status` in its sources’ `criteria` values?

**Comment by WHITE-developer** [comment]
Hi Brandon,
No we don't include status in our defineSources().
```PHP
protected static function defineSources(string $context = null): array
    {
        $sources = [
            [
                'key' => '*',
                'label' => 'All translations',
                'criteria' => []
            ],
            [
                'heading' => 'Categories'
            ],
        ];

        $categories = (new Query())
            ->distinct(true)
            ->select(['category'])
            ->from(['{{%translate_translations}}'])
            ->orderBy('category')
            ->all();
        $categories = array_column($categories, 'category');
        
        foreach ($categories as $category) {
            $sources[] = [
                'key' => $category,
                'label' => $category,
                'criteria' => [
                    'category' => $category,
                ]
            ];
        }
        
        return $sources;
    }
```
Maybe also good to know that it is a plugin we migrated from Craft 3, and there we don't have this problem.

**Comment by brandonkelly** [comment]
Is this happening on a template that extends `_layouts/elementindex`, or a JavaScript modal?

Is any custom `status` being set wherever it’s being initialized?

Also try outputting `Craft.defaultIndexCriteria` from your browser console. Does it include a `status` property?

**Comment by WHITE-developer** [comment]
Thanks Brandon,
Found the issue, the status was set when i initialized the elementindex.
