### ISSUE TITLE
[4.x]: Updates Widget on Dashboard not working correctly

### ISSUE THREAD

**Issue by olsp** [craftcms/cms#11552]
### What happened?

When I log in, there is the "Updates" widget on the dashboard. It then looks for updates and after some seconds, it says "Congrats, you're up to date." and in the same moment, next to the "Utilities" nav item, a number appears which indicates that updates are available. After a refresh, the widget also tells me that updates are available.

### Craft CMS version

4.0.5.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Hi, please write into support@craftcms.com and we can help look into this from there.

**Comment by richhayler** [comment]
I have noticed this same behaviour. I'm currently on v4.1.1 so will lookout for the next plugin or CraftCMS update and will upload a screenshot to demonstrate. This was happening for me in previous v4.0.X versions.
