### ISSUE TITLE
[3.7.47.1]: Empty "scripts" in composer.json causes error during craft update

### ISSUE THREAD

**Issue by alexroper** [craftcms/cms#11564]
### Description

While performing an update from the command line with `php craft update`, a composer.json file that includes an empty "scripts" config or no "scripts" at all, fails with the error:

> Performing update with Composer ... error: ".../craft/composer.json" does not match the expected JSON schema

### Steps to reproduce

1. Create a Craft 3 site with `composer create-project craftcms/craft test ^1`. 
2. After that installation completed, I removed the "scripts" section from the composer.json file: 

```php
{
  "require": {
    "craftcms/cms": "^3.7.26",
    "vlucas/phpdotenv": "^5.4.0"
  },
  "require-dev": {
    "yiisoft/yii2-shell": "^2.0.3"
  },
  "autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  },
  "config": {
    "allow-plugins": {
      "craftcms/plugin-installer": true,
      "yiisoft/yii2-composer": true
    },
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "7.2.5"
    }
  },
  "scripts": {}
}
```

3. Try to install the Redactor plugin thru the Plugin Store. I get the "does not match the expected JSON schema" error. 

### Expected behavior

The "scripts" config block should remain unchanged/empty object.

```
{
    ...
    "scripts": {}
}
```

### Actual behavior

In `composer.json` the "scripts" has been changed from an object to an array:

```
{
    ...
    "scripts": []
}
```

### Craft CMS version

Craft Solo 3.7.47.1

### PHP version

7.4.30

### Operating system and version

Linux 5.10.104-linuxkit

### Database type and version

MySQL 5.5.5

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-35)

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next Craft 3 and 4 releases.
