### ISSUE TITLE
[4.x]: 

### ISSUE THREAD

**Issue by jesuismaxime** [craftcms/cms#11572]
### Description

Single sections don't appear in specific user role user Entries CP page.

### Steps to reproduce

1. Create a new userrole with specific permissions (that includes at least one Single section)
2. Create a user with this userrole
3. Visit the **CP › Enties** page and look at the **Source** column

### Expected behavior

Seeing all allowed sections.

### Actual behavior

Not seeing Single sections

EDIT: Accessing the section with the direct link is working; ex. `.../admin/entries/home/7-home`

### Craft CMS version

Craft CMS 4.1.0.2

### PHP version

8.0.8

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you please send a database backup and your Composer files over to support@craftcms.com, and point out which user is unable to see the Singles entry source?

**Comment by thupsi** [comment]
I'm not certain, but think I recently stumbled upon this when using the [Expanded Singles](https://plugins.craftcms.com/expanded-singles) plugin.

**Comment by brandonkelly** [comment]
Looks like there’s an existing issue for it already, and has been fixed for the next release: https://github.com/verbb/expanded-singles/issues/31

@jesuismaxime Do you have that plugin installed?

**Comment by jesuismaxime** [comment]
Yes I have, but disabled all plugins (except Neo - and especially Expanded Singles since the issue only affect Single sections) and retest before submitting an issue here. I looked into the issue in verbb repo and the setup is already using their branch.

I'll do some tests on Monday and move my issue un verbb repo if needed. Thx!
