### ISSUE TITLE
Deleting an asset scrolls the page to the bottom of the assets field

### ISSUE THREAD

**Issue by shoored** [craftcms/cms#11577]
### Description
When deleting an asset from an assets field where multiple assets are allowed, the page scrolls to an unspected position, losing your scroll position.

### Steps to reproduce
1. Go to an entry with an assets field with no limit on the number of assets
2. Upload a large amount of assets and save the entry. Make sure all the assets cannot fit into view
3. Edit the entry and delete assets from the top of the field. 

### Expected behavior
To keep the current scroll position after deleting an asset from an assets field

### Actual behavior
The page scrolls to a unsuspsected position after deleting an asset from the assets field.

It looks like it scrolls to where the bottom of the field seems to be at 50% of the window height. This is frustrating when you're cleaning up assets and deleting them one by one because you have to scroll back after each action.

It seems to happen when there are a lot of assets in the field and the bottom of the field cannot fit in in the viewport height. When I delete an asset in the top rows of the field and the bottom of the field is not in view, the page scrolls down to where the bottom is indeed in view.
When I scroll down to where the bottom of the field is in view and delete an asset in the last row, the scrolling thing does not occur.

### Additional info
- Craft 3.7.45.1
- This also happens on Craft 4.1.0.2
- Happens in Chrome, Brave and Firefox on macOs and Chrome and Firefox on Windows 10

[Video of the scrolling effect](https://www.loom.com/share/547b734378f94b8fa4614eaae625406a)

**Comment by brandonkelly** [comment]
This was happening because tho focus was moved to the “Add” button when an element was removed. Just tweaked it for the next Craft 3 and 4 releases. Going forward, focus will be moved to the following element’s “Remove” button instead, if there is one.

**Comment by brandonkelly** [comment]
Craft 3.7.48 and 4.1.4 are out with the fix for this.
