### ISSUE TITLE
[4.x]: Entry columns and headings settings cog missing when in production mode

### ISSUE THREAD

**Issue by sunscreem** [craftcms/cms#11580]
### Description

Clients are unable to change the columns shown in a list of entries in Craft 4. 

### Expected behaviour

Cog to be shown.

### Actual behaviour

Cog only shown in dev mode.

![image](https://user-images.githubusercontent.com/7523595/178105471-1ce8a61b-a529-4dbf-87a7-a2ec4b95a564.png)

### Craft CMS version

4.1.3

### Installed plugins and versions

-

**Comment by thupsi** [comment]
It's not a bug, see here: https://github.com/craftcms/cms/discussions/11355

**Comment by sunscreem** [comment]
@thupsi Thanks :(
