### ISSUE TITLE
[3.x]: craft\services\Users::EVENT_AFTER_VERIFY_EMAIL event fires when it shouldn't

### ISSUE THREAD

**Issue by benjaminkohl** [craftcms/cms#11585]
### Description

I've been writing a module for a client that relies on the `craft\services\Users::EVENT_AFTER_VERIFY_EMAIL` event and I've noticed that this event fires even when the user has not verified the email address _yet_. The event fires when the user loads either the admin user's set password form or when a non-admin user loads our custom set password form.

I _believe_ the offending code can be found on line 531 of the UsersController, right after it is determined the request is _not_ a POST request and the `_processTokenRequest()` method is called which is where that event is triggered (line 2131). I have not yet determined if loading the set password form is the only time where this event is triggered when it shouldn't be.

### Expected behavior

I believe the Users::EVENT_AFTER_VERIFY_EMAIL event should only ever be triggered immediately after the user verifies an email address via the verification URL and not when loading the set password form. Maybe an email address shouldn't be considered verified when the user submits the set password form either? It's been a little tricky for me to diagnose exactly what's going on every time this occurs.

### Actual behavior

At the very least, it appears the event is fired when the set password form loads AND when the person submits it. 

### Craft CMS version

3.7.47.1

### PHP version

7.4

### Operating system and version

Darwin 20.6.0

### Database type and version

MySQL 5.7.34

### Image driver and version

Imagick 3.4.4 (ImageMagick 6.9.6-2)

### Installed plugins and versions

CP Field Inspect 1.4.4
CP Filters 1.3.0
Craft Commerce 3.4.15
Feed Me 4.5.3
Guest Entries 2.4.0
Imager X v3.6.1
Inventory 2.1.1
Lab Reports 1.0.0
Linkit 1.1.12.1
Link Vault 3.2.0
LJ Dynamic Fields 3.0.12
Minify 1.2.11
Password Policy 1.2.0
Redactor 2.10.10
Twigpack 1.2.17

**Comment by brandonkelly** [comment]
The event will only get triggered if the request contains a valid user verification token, which is what Craft needs in order to consider the email valid. (The user would only have the URL with the right token in it if they actually had access to the email address on file.)

Maybe `craft\services\Users::EVENT_AFTER_ACTIVATE_USER` would be a better fit for your use case? That will only get triggered once the user account is fully activated, which happens after they’ve set their password.

**Comment by benjaminkohl** [comment]
Okay, I see. The activation event won't work in our scenario because part of what we're doing is hijacking the usual user approval flow. A simplified description of what we're trying to do is:

- User registers for the site using front-end form. They enter the system as **pending** and **unverified**.
- They verify their email by clicking the email verification link. We prevent them from being activated. They are now **pending** and **verified** which means they'll show up in a list view in a custom module where the admin user can approve or decline the user (triggering emails). Admin users also receive an email when the user becomes pending/verified. Presently, multiple emails are being sent for each user because of how often the event gets triggered.
- Once per year, users must change their password and reverify their email addresses. After a few ignored reminders to do so, the accounts get deactivated (suspended status). There's a whole mess of console commands run by cron jobs to facilitate all this.

Everything seems to be working pretty well except figuring how to only verify the email address once during the flow of setting passwords or clicking the verification URL.

I'm thinking I may stick with the current event but I just need to figure out how to limit our code to firing only one time during the flow of initial email verification or any time someone sets a new password after clicking a password reset link. Otherwise, maybe there are other events I am overlooking. Like "after set password" or "visits verification URL". Things like that. I've been trying to avoid cramming more things into the User element save events because of a few instances where the elements would get updated again resulting in infinite recursion. I changed many of those element updates to SQL queries to avoid that problem.

**Comment by brandonkelly** [comment]
Do you have a custom field that tracks whether users are verified? Or are you just basing it on the existence of a verification code on the user record?

**Comment by benjaminkohl** [comment]
Users aren't allowed to change their own email addresses on the site. They have to submit a request to the admin to do it for them. If I remember correctly, an admin user changing another user's email doesn't set it to unverified by default so I added a custom user action that initiates the email verification process and instructed the client admin to use that when changing a user's email.

It's been quite the project getting all these account security features in place. It's a bit excessive, in my opinion. I'm sure I'll get locked out of my account a few times. Ha.

I think it is fine to close this issue. What you described about when that event triggers makes sense to me and I think I have some better conditionals now for handling our custom code. Thanks for the help!
