### ISSUE TITLE
[4.x]: getRootFolderByVolumeId returns a random folder

### ISSUE THREAD

**Issue by ishitatsuyuki** [craftcms/cms#11593]
### Description

`getRootFolderByVolumeId` returns a random folder that is not necessarily the root.

### Steps to reproduce

1. Create a bunch of subfolders (maybe it depends on DBMS in what order the query results are returned)?
2. Create an asset field and set the default upload location to empty (=root folder). Try to upload add see it to select the wrong folder.

### Expected behavior

`getRootFolderByVolumeId` should return the root folder, with its `parentId` being null.

### Actual behavior

```
>>> $assetsService->getRootFolderByVolumeId(1);
=> craft\models\VolumeFolder {#2855
     +id: 34,
     +parentId: 33,
     +volumeId: 1,
     +name: "01",
     +path: "wp-uploads/2020/01/",
     +uid: "accbf1fe-58ff-4473-9fad-224ba1434076",
   }
```

It looks like `parseField` doesn't handle `null`s and expects an `:empty:` instead?

### Craft CMS version

4.1.4

### PHP version

8.1.6

### Operating system and version

Linux 5.18.10-arch1-1 (ddev)

### Database type and version

MySQL 10.3.35

**Comment by brandonkelly** [comment]
Doh, thanks for reporting that! Just released Craft 4.1.4.1 with a fix.
