### ISSUE TITLE
[3.x]: Getting deprecation errors after upgrade that doesn't seem to make sense?

### ISSUE THREAD

**Issue by bencresty** [craftcms/cms#11595]
### Description

After upgrading to the last Craft 3.x version (from at most 3 minor-versions ago) the utilities panel of a working website without deprecation issues is now full of deprecation issues on each of the upgraded sites:

Edit: looking in the git log it seems like we went from Craft 3.7.46 to Craft 3.7.48, so only 2 minor versions up. Before, so in 3.7.46, we didn't see these deprecation messages ,so they started appearing in either 3.7.47 or 3.7.48

It says in loop: 
`"Treating element queries as arrays has been deprecated. Use exists() to determine if an element query will yield any results, or all() to fetch the results."`

But everywhere in the code we use `.all()` on each of our loops for months as that was already needed back then when we build the website.

I can't find a change log here on github to check what have been changed and what is causing these deprecation issues.

Could somebody please tell us what exactly changed that caused this and that there really is something changed intentially in this regard and this is not a newly introduced issue? (And where to find the change logs) As I stated above, we use '.all()' before all our loops, also in the code the message seems to be triggered from. So can't see anything wrong in the templates.

### Steps to reproduce

1. Upgrade Craft
2. Tenths to hundreds deprecation messages appear in the utilities panel

### Expected behavior

No deprecation messages.

### Actual behavior

Deprecation messages.

### Craft CMS version

3.7.48

### PHP version

8.1.7

### Operating system and version

Apache

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
3.7.48 fixed a bug where deprecation warnings weren’t always getting logged in cases when element queries were treated like arrays (8fa998cd00105544a67bdcfb99cbb6adef8302cd). Support for that has been completely removed in Craft 4, so it’s important that these issues get addressed.

You should be able to get a better idea of where they’re occurring by inspecting the warning’s Stack Trace, which should be available both from the Debug Toolbar on pages they occur, and from the Deprecation Warnings utility.

Just this morning someone in Discord mentioned seeing these crop up and traced them back to SEOmatic, so if you have that installed, there’s a chance that’s the culprit.

**Comment by bencresty** [comment]
@brandonkelly  Thanks for your quick response. Could it be that this was the issue / was not allowed and is now logged? Is this the right way to use `exists()`?

Wrong?

```
{% set social_media_pages = social_media_pages|default(null) %}
```

Right (added `exists()`?

``` 
{% set social_media_pages = exists(social_media_pages)|default(null) %}
```

**Comment by brandonkelly** [comment]
What is `social_media_pages` set to before this line?

**Comment by bencresty** [comment]
> What is `social_media_pages` set to before this line?

It's a Table Field

**Comment by bencresty** [comment]
@brandonkelly  I'm having a case I don't get here now tho: it's with assets.

This is the original code (throwing the deprecation warning), where 'thumbnail' is an Assets Field (limited to 1 item):

```
{% set image_asset = entry.thumbnail[0]|default(null) %}
```

But it's throwing in the warnings for that exact line:
![image](https://user-images.githubusercontent.com/69322733/178955506-6ca3fd5a-df49-4697-b5a9-e6526e7574fe.png)


When I change this line into...

```
{% set image_asset = entry.thumbnail.one() %}
```

...to my surprise I'm getting as an error message on the page telling me `.one()` is not possible on arrays:

![image](https://user-images.githubusercontent.com/69322733/178954357-1c251db7-9a1a-4c85-a78e-cbd0ef73cac6.png)

![image](https://user-images.githubusercontent.com/69322733/178954300-31c955f0-f37b-497a-9196-c71cbf5ef778.png)

So it seems like the thumbnail field (= assets field) is an array, and so I wouldn't expect the deprecation message to appear on the original code as this IS an array. Also in other include files, which are using the exact same original construction for this `thumbnail` field, this doesn't throw deprecation warnings for some reason.

I don't get this:
- Is it true that assets fields (eventhough set to limit to 1 item) return arrays?
- Why is this construction working without deprecation warnings in most include, but not working when used in another include? What am I missing?
- What is the right way to do this, since the above doesn't work?

Thanks in advance!

**Comment by brandonkelly** [comment]
@bencresty My first guess would be that that template line is getting executed multiple times, and in some cases `thumbnail` is an array (e.g. it was eager-loaded), and other times it’s an element query.

As of the next release, deprecation warnings’ stack traces will start to show the actual source template path and line number, rather than the compiled template path/line, which should make it easier to identify how the deprecation warning occurred (cc2ee65193c7ffc5c43ab6f9f98985ce913b65d8).

Try the following:

1. Change your `craftcms/cms` constraint in composer.json to `dev-develop as 3.7.48`
2. Run `composer update`
3. Revert your template code back to `[0]` instead of `.one()`
4. Trigger the deprecation warning

Then go to **Utilities** → **Deprecation Warnings** and inspect the stack trace. Perhaps the updated stack trace will give you a better clue of _when_ it’s happening.
