### ISSUE TITLE
[4.x]: After changing field handle, GraphQL no longer returns field contents

### ISSUE THREAD

**Issue by GustavTaxen** [craftcms/cms#11592]
### Description
After changing the handle of a field, the GraphQL API now returns empty results for that field.

The section is included in the public schema. If I enter the following query on the GraphiQL util page:

```
{
  entries(section: "navigation", status: ["live", "pending"]) {
    ... on navigation_default_Entry {
      title
      slug
      internalAccessPassesCache {
        title
        slug
      }
    }
  }
}
```

I get the correct result:

```
{
  "data": {
    "entries": [
      {
        "title": "Courses",
        "slug": "navigation-courses",
        "internalAccessPassesCache": [
          {
            "title": "London bass guitar show lifetime",
            "slug": "ap-london-bass-guitar-show-lifetime"
          },
         ...
```
But when I post the same query via Postman:

```
{
    "query": "{entries(section: \"navigation\", status: [\"live\", \"pending\"]){... on navigation_default_Entry {title slug internalAccessPassesCache { title slug }}}}"
}
```

the field is empty:

```
{"data":{"entries":[{"title":"Courses","slug":"navigation-courses","internalAccessPassesCache":[]},{ ...
```

### Steps to reproduce

Not entirely certain that this is what reproduces the error, but I upgraded from Craft 3 to Craft 4 and then renamed the handle of the field from "internalUserGroupsCache" to "internalAccessPassesCache".

### Craft CMS version

Craft Pro 4.1.3

### PHP version

8.0.20

### Operating system and version

Linux 5.10.104-linuxkit

### Database type and version

MySQL 10.6.7

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-35)

### Installed plugins and versions

- FeedMe 5.0.4
- Redactor 3.0.2

**Comment by GustavTaxen** [comment]
Forgot to mention that the field is a `categories` field, and with the name change I also changed the field to point to a different category.

**Comment by GustavTaxen** [comment]
Never mind, it's another type of error. My bad! Apologies!

**Comment by brandonkelly** [comment]
Hah, glad you got it sorted!
