### ISSUE TITLE
[4.1.4.1]: Filesystem name being prefixed on Base Path

### ISSUE THREAD

**Issue by RetroChaos** [craftcms/cms#11608]
### Description
I've recently tried migrating our CraftCMS instance from 3.7.37 to 4.1.4.1.
Bearing a few snags at the start in migrating, all seems well now. Our CraftCMS instance is currently setup to be multi-site, and a few of these sites have quite a lot of assets (over 5000 across all sites). I've tried to reindex our Asset Index to make sure all entries still match-up, however Craft is currently reporting that all these assets are missing (even though they are still thankfully mapped to entries). 
When looking at the error, it seems to be that Craft is prefixing the Base Path with the name (not handle) of the Filesystem, which is weird and undesirable. 
Is there any way to stop this occurring? 

### Steps to reproduce

1. Create a Filesystem
2. Create a Volume
3. Create an entry and tie an asset to a field in it.
4. Reindex the Asset Volumes

### Expected behaviour

All Assets are found correctly

### Actual behaviour

Files and folders can't be found because the filesystem name is being prefixed at the start of each path.

### Attached photos for reference

![Capture](https://user-images.githubusercontent.com/1346654/179196133-49886738-a12d-46fb-bf3b-4163e38b2f5a.PNG)
![Capture1](https://user-images.githubusercontent.com/1346654/179196136-b45917b5-c08b-484c-aedf-bb46df226e01.PNG)

### Craft CMS version

4.1.4.1 Pro

### PHP version

8.1.8

### Operating system and version

Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-189-generic x86_64)

### Database type and version

MariaDB 10.1.48

### Image driver and version

GD 8.1.8

### Installed plugins and versions

- CP Field Inspect 1.4.4
- Contact Form 3.0.0
- Contact Form Extensions 4.0.0-beta.3
- Feed Me 5.0.4
- Field Manager 3.0.0
- Font Awesome for Redactor 2.0.0
- Redactor 3.0.2
- Smith 2.0.0

**Comment by brandonkelly** [comment]
The first segment is just the volume name. However the volume name should be followed by the path to the missing folder/file, relative from the root of the volume’s filesystem, whereas these look like absolute server paths.

I’m guessing that this is actually working as expected, and the issue is that somehow these absolute paths got indexed at some point previously.

If you scroll down the list, do you see any actual files listed, or are they all folders? 

It should be perfectly safe to allow it do delete any missing folders.

**Comment by RetroChaos** [comment]
Hi, sorry for the delay in reply over the weekend.

I have changed the paths to relative and scrolled down and it is picking up all the files to be removed in the reindex, even though they exist there in the filesystem (both relative and absolute paths are correctly identified by Craft).

And yes, Craft 3.7 had no index issues prior to upgrading.

I took a snapshot of the system and hit reindex and all my asset fields in the entries broke, so unsure what's going on here.

![Capture](https://user-images.githubusercontent.com/1346654/179504665-ef23cafb-0496-4c1c-b7da-9adda764f136.PNG)
![Capture1](https://user-images.githubusercontent.com/1346654/179504669-1e098b22-137a-476f-ba6a-7c991cb159af.PNG)
.

**Comment by brandonkelly** [comment]
> I have changed the paths to relative and scrolled down and it is still picking up all the files to be removed in the reindex, even though they exist there in the filesystem (both relative and absolute paths are correctly identified by Craft).

I wasn’t suggesting you should change the setting to relative.

My point is just that the folders in your first screenshot didn’t look like they should have been in the index to begin with.

It looks like the path to your “Global” volume’s filesystem _should_ be set to `/var/www/craft/web/assets/global/`, however at some point it was just set to `/` instead (assuming `/var/` is at the root of the system’s filesystem). And so all of your system files/folders starting at `/` got indexed, rather than just the files/folders within `/var/www/craft/web/assets/global/`.

**Comment by RetroChaos** [comment]
Ah I see. Sorry for the confusion. 

PICNIC error, nothing wrong with the indexer it seems. Thanks for your support. I'll mark as closed, and as a non-bug issue.

**Comment by RetroChaos** [comment]
Hi @maxfrischknecht, I actually haven't really had a chance to really have a look into the issue further as I've been working on other more pressing issues for my employer (one man team can stretch you out thin at times). I just assumed it was me being daft and I was going to look into it later today / tomorrow. Looks like we're experiencing the same issue so as soon as I find out anything I'll share it here. 

Out of interest has this suddenly become an issue after migrating up from Craft 3 -> Craft 4?

**Comment by RetroChaos** [comment]
Don't worry, solved it. It is the absolute path in the .env file.

I was under incorrect assumption that since the aliases were already pre-defined, they should just work, however it seems that they do in fact need to be overridden in general.php according to the docs here: https://craftcms.com/docs/4.x/config/#aliases

Only thing I can think of for ease of use is to include this in `general.php`

`    'aliases' => [
      '@web' => App::env('PRIMARY_SITE_URL'),
      '@webroot' => dirname(__DIR__) . '/web',
      '@assetBaseUrl' => '@web/assets',
      '@assetBasePath' => '@webroot/assets',
    ],
 `
 
or include a note that relative paths are no longer working in filesystems under https://craftcms.com/docs/4.x/upgrade.html#volumes. 

 and yes, I did eventually notice that under each asset volume that Craft had basically duplicated the folder structure of the webroot eg. `/var/www/craft/web/assets/global` then inside I had `var/www/craft/web`.
 
 Thanks for having a look and getting back to me @maxfrischknecht

**Comment by maxfrischknecht** [comment]
> @maxfrischknecht Did you set `WEBROOT_PATH` in your .env as an absolute path eg. `/var/www/craft/web`?

Yes, I defined an absolute path. And yeah, I was also under the assumption that aliases are pre-defined. 
However, nice that we managed to work it out 👍
