### ISSUE TITLE
[4.x]: MonologTarget sensitive data not masked if linebreaks are allowed 

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#11618]
### Description

Your condition in your [Monologtarget](https://github.com/craftcms/cms/blob/develop/src/log/MonologTarget.php#L135-L139) is kinda strange

```php
        if ($this->allowLineBreaks) {
            $message .= "\n" . trim(parent::getContextMessage());
        } else {
            $vars = $this->logVars;
        }
```

it basically says: 
- if linebreaks are allowed, then insert the context directly without masking vars and print all passwords nicely formatted into the log
- else do not print them with linebreaks but mask sensitive data

currently `allowLineBreaks` is default -> all passwords and tokens are logged directly in all log files. Please fix that as soon as possible.

Previously your logger used `LogTargetTrait` that has it's  [custom mask part](https://github.com/craftcms/cms/blob/develop/src/base/LogTargetTrait.php#L105-L114) but your `MonologTarget` does not use this trait.

### Steps to reproduce

1. just call a URL in Craft
2. see all passwords are logged in your log files

### Expected behavior

1. passwords should be masked

### Craft CMS version

4.X

### PHP version

8.1

### Step to fix

-  add a `use LogTargetTrait`  into `MonologTarget`

### Installed plugins and versions

-

**Comment by timkelty** [comment]
@Anubarak thanks for the report! Indeed, looks like a bug.
[Fixed here](https://github.com/craftcms/cms/pull/11635) for the next release.

> currently allowLineBreaks is default

`allowLineBreaks` is only set to `true` by default when `devMode` is `true`, which should only be the case in local dev environments.

**Comment by brandonkelly** [comment]
Craft 4.2.0 is out now with that fix.
