### ISSUE TITLE
Add onBeforeAuthenticateUser event to UserSessionService

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1161]
> Created by: Chris Comfort (elcritt@gmail.com) on 2016/10/28 21:16:02 +0000
> Votes at time of UserVoice import: 2

-----------------------------------

It would be helpful to have the ability to step into the normal CP login process ahead of authentication in order to do something like check the credentials against a third party service (e.g. LDAP).

**Comment by bertoost** [comment]
So needed! And so easy to add this, but unfortunate no new features are going to be added to v2, since v3 is coming

**Comment by bertoost** [comment]
@brandonkelly This isssue can be closed ;-)
