### ISSUE TITLE
[4.x]: asset.getImg() for image with only a transform url returns null

### ISSUE THREAD

**Issue by codebarista** [craftcms/cms#11614]
### Description

I store images without URL in storage and only define a URL for the transforms. In Twig when I call the function `asset.getImg('existing_transform')` it returns NULL.

### Steps to reproduce

1. Create filesytem "Images" w/o public URL and Base Path @storage/assets/images
2. Create filesytem "Transforms" with public URL and Base Path @webroot/assets/images
3. Create Assets Volume "Images" with Asset Filesystem "Images" and Transform Filesystem "Transforms"
4. Create Image Transforms, e.g. "large"
5. Add an image to an entry
6. Call `asset.getImg('large')` in a Twig template

### Expected behavior
Return the image tag with image transformation.

### Actual behavior
Returns `null`

### Dirty Quick Fix
In `elements/Asset.php` line **1195** add the following:
```
if (!$volume->getFs()->hasUrls && !$transform) {
    return null;
}
```

### Craft CMS version

Craft Pro 4.1.4.1

### PHP version

8.1.7

### Operating system and version

Linux 5.10.104-linuxkit

### Database type and version

MySQL 8.0.29

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-35)

### Installed plugins and versions

- Redactor 3.0.2

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed now for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 4.1.4.1"` and run `composer update`.

**Comment by brandonkelly** [comment]
Craft 4.2.0 is out now with that fix.
