### ISSUE TITLE
[4.x]: Unable to use matrix fields in entry condition

### ISSUE THREAD

**Issue by DavidLaridon** [craftcms/cms#11620]
### Description

Trying to add an entry condition that checks if a matrix field is empty or not. Exactly the same for Neo fields but I don't know if this is currently even possible. 

Trying to add conditions to the fields of a Neo block also doesn't work (Which probably just isn't a feature yet?) 

If non of this is possible right know, is there an alternative to achieve this?

### Steps to reproduce

1. Make a Matrix and/or Neo field and add it to the entry type of a section
2. Try to add an entry rule to a text field to only show it if the matrix or neo field is empty 

### Expected behavior

To have an option to select the matrix or neo field

### Actual behavior

Not seeing the option

### Craft CMS version

4.1.4.1

### PHP version

8.0.20

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Craft 4.2.0 is out now, with support for referencing Matrix fields in conditions ✨
