### ISSUE TITLE
[3.x]: Validation error when propagating tags with same name and different case to another site

### ISSUE THREAD

**Issue by jdsdev** [craftcms/cms#11627]
### Description

Unable to propagate tags to a new site, with error `Couldn’t propagate element to other site.` -> `[craft\services\Elements::_saveElementInternal] Element not saved due to validation error`.

### Steps to reproduce

1. Create two tags with same name but different case (e.g. "Associations", "associations").
2. Add a new site and save.

### Expected behavior

Successfully propagate tags, or don't allow invalid tags to be created.

### Actual behavior

Status *Failed*, Couldn’t propagate element to other site.

### Craft CMS version

Craft CMS 3.7.48

### PHP version

8.1.8

### Operating system and version

Linux 5.10.104-linuxkit

### Database type and version

MySQL 8.0.29

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
It shouldn’t have been possible to create both of those tags to begin with.

<img width="295" alt="A Tags field with “pizza” already selected (lowercase “p”), and “Pizza” (capital “P”) entered into the new tag input. The input’s selection menu shows that the existing “pizza” tag is already selected, and doesn’t give the option to create a new capital-P “Pizza” tag." src="https://user-images.githubusercontent.com/47792/180611084-835265cc-b55c-4776-88a3-21663380d81d.png">

Are you still able to create identical tags somehow? Or perhaps these were added via a prior Craft version that incorrectly allowed it.

Either way, you should be able to merge the identical tags together using the [Tags](https://plugins.craftcms.com/tag-manager) plugin.

**Comment by jdsdev** [comment]
It looks like the tags were created in an earlier version of Craft. It would be nice if the tags were handled gracefully instead of throwing an error, but the Tags plugin seems to have resolved the issue. Thanks!
