### ISSUE TITLE
[3.x]: User enumeration is possible for non-admin CP users

### ISSUE THREAD

**Issue by hiasl** [craftcms/cms#11624]
### Description
Our security consultants reported the following potential security problem: 
CP Users without permission to manage Craft users can enumerate Craft users and find out, if a user with a certain ID exists

### Steps to reproduce

1. Log into the CP with a user who does not have permission to manage Users.
2. Now try to open the details page in user administration of a user which exists and then open the same URL but modify the userId to something non-existing: https://my.host.com/admin/users/<userid>
3. In the first case Craft will give you a 404 and in the second case an "unauthorized" (403 I guess)

### Expected behavior
Craft should first check the CP user's permission to manage users and then if the user exists or not. Not the other way around.

### Actual behavior
Craft exposes the information if the user exists or not by outputting different HTTP responses.

### Craft CMS version

3.7.37

### PHP version

7.4.19

### Operating system and version

Linux 4.18.0-348.12.2.el8_5.x86_64

### Database type and version

Postgres 12.4

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
All control panel users have at least some amount of visibility into every element in the system, including their IDs. It is necessary for Users fields to function, etc. So changing these to pretend that  the user exists wouldn’t actually make a difference. If you don’t trust your users enough to even want them to know whether a given user ID exists, you probably shouldn’t be giving them access to the control panel in the first place.

(And FFR, please report any security-related issues privately from https://craftcms.com/contact. Thanks!)

**Comment by hiasl** [comment]
fine with me :-) Thanks
