### ISSUE TITLE
[4.x]: Required property always returns null from getFieldById()

### ISSUE THREAD

**Issue by antcooper** [craftcms/cms#11633]
### Description
We have a module that parses Neo/Matrix blocks and the `required` property is `null` in all cases, even when the field has been set as required in the CMS.

### Steps to reproduce

```
            $fieldIds = \Craft::$app->getFields()->getFieldIdsByLayoutIds([$fieldLayoutId]);

            $fields = [];
            foreach ($fieldIds[$fieldLayoutId] as $fieldId) {
                $field = \Craft::$app->getFields()->getFieldById($fieldId);
                array_push($fields, $field);
            }

            $requiredFields = array_filter($fields, fn($f) => $f->required);
            $optionalFields = array_filter($fields, fn($f) => !$f->required);
```

### Expected behavior

[required](https://docs.craftcms.com/api/v4/craft-records-fieldlayoutfield.html#public-properties) property should reflect the correct status as a boolean value.

### Actual behavior

For a valid `$fieldLayoutId` this code should retrieve all the fields and provide two arrays for required and optional fields. Currently returning all as optional, even when required is checked in the CMS. Dumping out the `fields` array shows `[required] => null` in all cases. Worked OK in Craft 3.

### Craft CMS version

Craft CMS 4.1.4.1

### PHP version

8.0.20

### Operating system and version

Linux 5.15.0-41-generic

### Database type and version

MySQL 8.0.29

### Image driver and version

GD 8.0.20

### Installed plugins and versions

-

**Comment by Anubarak** [comment]
That will never work since your required attribute is set in the layout and not in the field itself.
Grabbing it via `\Craft::$app->getFields()->getFieldById($fieldId);` will return your base field without the required property.
You need to grab it from the Elements Fieldlayout instead

```php
foreach ($element->getFieldLayout()->getCustomFieldElements() as $field){
    echo "<pre>";
    var_dump($field->getField()->handle);
    var_dump($field->required);
    echo "</pre>";
}
```

The required attribute is even marked as deprecated
```
    /**
     * @var bool|null Whether the field is required in the field layout it was fetched from
     * @deprecated in 4.1.4. [[\craft\fieldlayoutelements\BaseField::$required]] should be used instead
     */
    public ?bool $required = null;
```

**Comment by antcooper** [comment]
Thanks for pointing that out @Anubarak. I'd missed that it was deprecated. It worked fine in Craft 3. I'd found a way around it  getting all the fields at once with

```
$fields = \Craft::$app->getFields()->getLayoutById($fieldLayoutId)->getCustomFields();
