### ISSUE TITLE
[4.x]: js error when removing category tree

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#11641]
### Description

Js error at BaseElementSelectInput.js:441:10

### Steps to reproduce

1. Have a (matrix) field with a category selector
2. Add a multilevel category
3. Remove the level 1 category so the other levels get removed too
4. Js error

### Expected behavior
No error ;) and just do the autosave

### Actual behavior
After the js error, autosaving stops working

### Craft CMS version

4.1.4.1

### PHP version

8.1

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed now for the next Craft 3 and 4 releases.

**Comment by brandonkelly** [comment]
Craft 3.7.49 and 4.2.0 are out now with this fix.
