### ISSUE TITLE
[4.x]: Upgrade from 3.7.48 to 4.1.4.1 Fails: QLSTATE[42S22]: Column not found: 1054 Unknown column 'settings' in 'field list'

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [craftcms/cms#11644]
### Description

When attempting to upgrade from 3.7.48 to 4.1.4.1 I receive this error:

![Screen Shot 2022-07-20 at 12 06 28 PM](https://user-images.githubusercontent.com/39201467/180053046-b7083b76-12b9-4652-98e8-8d2a74744000.png)

When I look at that table I see this:

![Screen Shot 2022-07-20 at 12 13 05 PM](https://user-images.githubusercontent.com/39201467/180053179-eab3bbd9-6e27-4501-a7af-fa8ef207fc29.png)

Which is a Globals set tab of Elements and has 4 Static Super Table fields like so:

![Screen Shot 2022-07-20 at 12 07 06 PM](https://user-images.githubusercontent.com/39201467/180053293-9821b273-b9cf-46ef-b171-fa402f6a8e8b.png)

### Steps to reproduce

Will send project.yml, composer.json, composer.lock, and pre-upgraded database to support@craftcms.com

### Expected behavior

A clean upgrade.

### Actual behavior

Error:

![Screen Shot 2022-07-20 at 12 14 40 PM](https://user-images.githubusercontent.com/39201467/180053450-d4b4c439-fb74-4c16-ade7-851178f2dec0.png)

### Craft CMS version

3.7.48 to 4.1.4.1 

### PHP version

8.0.2

### Database type and version

MySQL 8

### Installed plugins and versions

"craftcms/aws-s3": "^2.0.1",
        "craftcms/cms": "^4.1.4.1",
        "craftcms/feed-me": "^5.0.4",
        "craftcms/mailgun": "^3.0.0",
        "craftcms/redactor": "^3.0.2",
        "hybridinteractive/craft-position-fieldtype": "^4.0.0-beta.3",
        "hybridinteractive/craft-width-fieldtype": "^4.0.0-beta.3",
        "mmikkel/retcon": "^2.4.2",
        "nystudio107/craft-eagerbeaver": "^4.0.1",
        "nystudio107/craft-fastcgicachebust": "^4.0.0-beta.1",
        "nystudio107/craft-imageoptimize": "^4.0.2",
        "nystudio107/craft-minify": "^4.0.0-beta.2",
        "nystudio107/craft-retour": "^4.0.2",
        "nystudio107/craft-seomatic": "^4.0.6",
        "nystudio107/craft-templatecomments": "^4.0.0",
        "nystudio107/craft-typogrify": "^4.0.0",
        "nystudio107/craft-vite": "^4.0.2",
        "percipioglobal/craft-colour-swatches": "^4.2.0.1",
        "presseddigital/linkit": "^4.0.0",
        "putyourlightson/craft-blitz-recommendations": "^2.1.1",
        "topshelfcraft/wordsmith": "^4.0.1",
        "vaersaagod/matrixmate": "^2.0.2",
        "verbb/cloner": "^2.0.0",
        "verbb/field-manager": "^3.0.0",
        "verbb/formie": "^2.0.2",
        "verbb/icon-picker": "^2.0.0-beta.5",
        "verbb/super-table": "^3.0.0-beta.6",
        "verbb/tablemaker": "^4.0.0",
        "vlucas/phpdotenv": "^3.4.0",
        "yiisoft/yii2-redis": "^2.0.6"

**Comment by tomjrjones** [comment]
@DynamiteGoesBoom I am getting the same, I also have some supertable globals. Let me know how you get on with this as I am in the same boat! 

Thanks

**Comment by brandonkelly** [comment]
Guessing this is happening before migrations get run, so the `settings` column hasn’t had a chance to be created yet. Just made that query more defensive for the next release.

You can test by changing your `craftcms/cms` requirement in composer.json to `dev-develop as 4.1.4.1` and running `composer update`.

**Comment by DynamiteGoesBoom** [comment]
@brandonkelly Righteous! I'll give this a go and hope it clears up that issue! Thanks again to the team for helping with this one!

**Comment by DynamiteGoesBoom** [comment]
@brandonkelly the same error occurs. I replied back to Support and hopefully can figure this tricky one out. Thanks again for staying on top of this 👍

**Comment by brandonkelly** [comment]
@DynamiteGoesBoom Doh sorry, just definitely fixed it. Run `composer update` again and you’ll be good to go.

**Comment by DynamiteGoesBoom** [comment]
@brandonkelly Haha we’ve all been there before! That seems to be the ticket! I was thinking earlier that one line of code for the fix was a bit ambitions :)

Thanks again!

**Comment by brandonkelly** [comment]
Craft 4.2.0 is out now with that fix.
