### ISSUE TITLE
[3.x]: Dropdown fields in collapsed Matrix blocks show `base64:[gibberish here]` instead of their content preview

### ISSUE THREAD

**Issue by proimage** [craftcms/cms#11659]
### Description
When an entry has a Matrix block with dropdown fields, and that block is collapsed, the content preview of those dropdown fields shows `base64:[gibberish here]` instead of the selected option.

Block expanded with two dropdown fields:
![image](https://user-images.githubusercontent.com/1027523/180427618-3cdfdd34-1110-40ce-a7fd-97ae6cd4f8e8.png)

Block collapsed, showing broken dropdown field content preview:
![image](https://user-images.githubusercontent.com/1027523/180427632-40bb6ef1-f7ec-4a37-abfe-39862972a338.png)

### Steps to reproduce

1. Create a Matrix field
2. Add a block to that field
3. Add a dropdown field to that block
4. Give it some options
5. Assign the Matrix field to a Section
6. Create an entry in that Section
7. Add a block to the Matrix field
8. Collapse said block

### Expected behavior
I would expect to see the (super-useful!) content previews of the fields in the collapsed Matrix block.

### Actual behavior
I get `base64:[gibberish]`.

### Craft CMS version

Craft CMS 3.7.46

### PHP version

7.4.30

### Database type and version

Craft CMS 3.7.46

### Installed plugins and versions

- Architect	2.4.3
- Asset Rev	6.0.2
- Bulk Edit	2.0.6
- Button Box	3.1.0
- Colorit	1.1.2.1
- Colour Swatches	1.6.0
- Cookies	1.1.15
- DigitalOcean Spaces Volume	1.1.3
- Entry Instructions	1.0.7
- Feed Me	4.5.3
- Field Manager	2.2.4
- Freeform	3.13.14
- Icon Picker	1.1.13
- Image Resizer	2.1.1
- Inventory	2.1.1
- Linkit	1.1.12.1
- LJ Range Slider	1.0.0
- Maps	3.9.3
- Mix	1.5.2
- Neo	2.13.12
- oEmbed	1.3.18
- Postmark	2.1.0
- Redactor	2.10.10
- Redactor Custom Styles	3.0.4
- SEO	3.7.4
- Simple Text	2.0.2
- Super Table	2.7.2
- Table Maker	3.0.0
- Template Select	2.0.2

**Comment by chattervast** [comment]
Same issue. Craft and all plugins up to date.

**Comment by ttempleton** [comment]
This is happening with Craft 4.1.4.1 as well. Looks like it started happening after https://github.com/craftcms/cms/commit/a3831d596f5d048839226e6404c49a59fa4c9f02.

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just fixed for the next Craft 3 and 4 releases.

**Comment by brandonkelly** [comment]
Craft 3.7.39 and 4.2.0 are out now with the fix for this! Now preview text will include the selected option label(s) whenever possible.
