### ISSUE TITLE
[4.x]: Console commands has different defaults when non-interactive

### ISSUE THREAD

**Issue by ishitatsuyuki** [craftcms/cms#11650]
### Description

All `confirm()` calls in console commands default to true if 1. the controller doesn't manually check for interactivity and 2. interactive = false (pipe stdin or CLI option).

### Steps to reproduce

1. Run `php craft users/create --email email@example.com --username User --groups Group --interactive 0`
2. The result is an activated, admin user, which is different from the prompt's default (not activated since no password specified, not admin).

This is due to a bad behavior in Yii's console helper: when non-interactive, `confirm` will always return `true` instead of the specified default value. I don't think this is desirable for Craft, so it might makes sense to create a helper in Craft's controller class that does not have this behavior.

### Craft CMS version

4.1.4.1

**Comment by brandonkelly** [comment]
Agree that’s not ideal. It’s a slight behavior change so I’ve just started ignoring certain `confirm()`s for non-interactive shells, for Craft 4.2 (imminent).

**Comment by brandonkelly** [comment]
Craft 4.2.0 is out now with those CLI changes.
