### ISSUE TITLE
Ability to rearrange Control Panel entries side menu

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#1165]
> Created by: Rheal (rheal@mf1.ca) on 2015/03/18 18:18:15 +0000
> Votes at time of UserVoice import: 2

-----------------------------------

I would love a way to be able to organize the side menu in the entries tab of craft's back end. When I hand over the site to my clients I typically have to spend 15 - 30 mins explaining what singles, categories and structures are. I would rather organize my sections by what I believe will be intuitive to the client. ﻿

**Comment by brandonkelly** [comment]
This was added in 2.5 or 2.6 (with exception of singles)
