### ISSUE TITLE
[4.x]: Unable to edit Dropdown options in Table Cell.

### ISSUE THREAD

**Issue by a-am** [craftcms/cms#11654]
### Description

When creating a table input with a Dropdown Column Type there is no cog button to add dropdown options.

### Steps to reproduce

1. Create Input & select Table as Field Type
2. Add a Column & select Dropdown as Type
3. Try to add Dropdown options and you will see there is no cog button.

### Expected behavior

When adding Dropdown Column Type a cog icon should appear next to select to add Dropdown options.

### Actual behavior

There is no cog to add dropdown options.

<img width="309" alt="Screen Shot 2022-07-21 at 2 49 16 PM" src="https://user-images.githubusercontent.com/976370/180313419-a082ec32-341e-47c8-b433-e909b476683e.png">

### Craft CMS version

4.1.4.1 (Pro)

### PHP version

8.0.20

### Operating system and version

Darwin 21.5.0

### Database type and version

MySQL 8.0.27

### Image driver and version

GD 8.0.20

### Installed plugins and versions

- Amazon S3 2.0.1
- Feed Me 5.0.4
- Formie 2.0.3
- Minify 4.0.0-beta.2
- Mix 1.6.0
- Navigation 2.0.3
- Neo 3.1.8
- Position Fieldtype 4.0.0-beta.3
- Redactor 3.0.2
- Retour 4.0.2
- SEOmatic 4.0.6
- Typed link field 2.1.3-rc

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Are you getting any JavaScript errors on the page?

**Comment by a-am** [comment]
@brandonkelly I restarted my computer and restarted Laravel Valet and now I see the gear icon. No console errors, everything looks fine.  Not sure what that was about? We are good here.

**Comment by brandonkelly** [comment]
Weird! Glad it’s working for you now :)
