### ISSUE TITLE
[4.x]: Validation of Element always fails if custom fields are set

### ISSUE THREAD

**Issue by tonioseiler** [craftcms/cms#11663]
### Description
In our plugin, we set fieldvalues from request.. When calling ->saveElement, the validation always fails, saying field "fieldname" must be string. If i turn of valdation mith the methods param, the element is saved.

### Steps to reproduce

1.

### Expected behavior

Should save..

### Actual behavior

Validation error is thrown

### Craft CMS version

4.0.0.1

### PHP version

8

### Operating system and version

0sx

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Sounds like the field value isn’t getting set to a string.

**Comment by tonioseiler** [comment]
they are a string, as you can see in the screenshot[
<img width="1070" alt="grafik" src="https://user-images.githubusercontent.com/4467443/184873715-9a37052c-8704-428c-9252-b1fc54cd83f3.png">
](url) and they can also be saved if i turn of validation in the save method....

**Comment by brandonkelly** [comment]
What type of fields are these? Maybe there’s a bug in their validator(s)?

**Comment by tonioseiler** [comment]
This is very strange. I delted all teh fields and created a new simple textfield. and it still does not work.
<img width="463" alt="grafik" src="https://user-images.githubusercontent.com/4467443/185478015-5b2dc066-9f02-4d87-a256-42bf304e21f3.png">
<img width="1057" alt="grafik" src="https://user-images.githubusercontent.com/4467443/185478078-6b1f04b7-44ca-423d-abf7-6985246d7c94.png">
<img width="994" alt="grafik" src="https://user-images.githubusercontent.com/4467443/185478190-f53def44-c005-4395-8564-a9cb70c5c21e.png">

Log saying:
Element not saved due to validation error:  {"memory":1927888} 
'fields' => [
        'bla' => 'eqw'
    ]

**Comment by tonioseiler** [comment]
do i need to pass a site id?

**Comment by tonioseiler** [comment]
Any ideas

**Comment by brandonkelly** [comment]
Can you post all of your PHP code around where `saveElement()` is called?

**Comment by tonioseiler** [comment]
`public function actionUpdate()
    {
        $this->requirePostRequest();
        $request = Craft::$app->getRequest();
        $itemId = $request->getBodyParam('itemId');
        $item = MuseumplusItem::find()
            ->id($itemId)
            ->one();

        // Set the title
        $item->title = $request->getBodyParam('title', $item->title);

        //set the custom fields
        $fieldsLocation = $request->getParam('fieldsLocation', 'fields');
        $item->setFieldValuesFromRequest($fieldsLocation);

        //dd($request->getBodyParams());

        $item->setScenario(\craft\base\Element::SCENARIO_DEFAULT);

        // Save it
        // TODO: why does validation always fails
        if (!Craft::$app->getElements()->saveElement($item, true)) {
            if ($request->getAcceptsJson()) {
                return $this->asJson([
                    'errors' => $item->getErrors(),
                ]);
            }

            Craft::$app->getSession()->setError(Craft::t('museum-plus-for-craft-cms', 'Couldn’t save item.'));

            Craft::$app->getUrlManager()->setRouteParams([
                'item' => $item
            ]);

            return null;
        }

        if ($request->getAcceptsJson()) {
            $return = [];

            $return['success'] = true;
            $return['id'] = $item->id;
            $return['title'] = $item->title;

            if (!$request->getIsConsoleRequest() && $request->getIsCpRequest()) {
                $return['cpEditUrl'] = $item->getCpEditUrl();
            }

            $return['dateCreated'] = DateTimeHelper::toIso8601($item->dateCreated);
            $return['dateUpdated'] = DateTimeHelper::toIso8601($item->dateUpdated);

            return $this->asJson($return);
        }

        Craft::$app->getSession()->setNotice(Craft::t('museum-plus-for-craft-cms', 'Item saved.'));

        return $this->redirectToPostedUrl($item);

    }`

**Comment by brandonkelly** [comment]
Hm, seems fine. Do you mind sending your Composer files, custom module files, and database backup over to support@craftcms.com? We can look into it from there.

**Comment by tonioseiler** [comment]
I appreciate it…





–––––––––––––––––––
Tonio Seiler
Dipl. Ing. FH Informatik
***@***.*** ***@***.***>

Furbo GmbH
Rüdigerstrasse 10
8045 Zürich

+41 44 501 85 65
www.furbo.ch <http://www.furbo.ch/>

Abwesenheit: Mittwochs

> Am 22.08.2022 um 17:17 schrieb Brandon Kelly ***@***.*** ***@***.***>>:
> 
> ending your Comp



–––––––––––––––––––
Tonio Seiler
Dipl. Ing. FH Informatik
***@***.*** ***@***.***>

Furbo GmbH
Rüdigerstrasse 10
8045 Zürich

+41 44 501 85 65
www.furbo.ch <http://www.furbo.ch/>

Abwesenheit: Mittwochs

**Comment by tonioseiler** [comment]
–––––––––––––––––––
Tonio Seiler
Dipl. Ing. FH Informatik
***@***.***

Furbo GmbH
Rüdigerstrasse 10
8045 Zürich

+41 44 501 85 65
www.furbo.ch

Abwesenheit: Mittwochs

**Comment by brandonkelly** [comment]
Yes, we’ve received the files, thanks! You should have received a couple auto-responders and a new reply from me, coming from support@craftcms.com.

**Comment by brandonkelly** [comment]
This ended up being due to the custom element type overriding the `__get()` method, which is responsible for returning custom field values.

**Comment by tonioseiler** [comment]
Thank you very much. I can easily solve this now.

–––––––––––––––––––
Tonio Seiler
Dipl. Ing. FH Informatik
***@***.***

Furbo GmbH
Rüdigerstrasse 10
8045 Zürich

+41 44 501 85 65
www.furbo.ch

Abwesenheit: Mittwochs
