### ISSUE TITLE
[4.x]: change in `without` filter behaviour

### ISSUE THREAD

**Issue by jeromecoupe** [craftcms/cms#11695]
### What happened?

After upgrading an old project to Craft 4, the behaviour of the `without` filter changed for me. 

### Description

I used to be able to remove an entry id from an array of element ids directly. This not work anymore because `entry.id` is of type `int` while the elements ids returned by the query are of type `string`. I now have to make an extra query or convert the `int` value into a string using interpolation, which didn't seem to be the case prior to the update.

Here is a reduced use case: on a news entry page, I want the 5 most recent news excluding the current news

```twig
{% set recentNewsIds = craft.entries()
  .section('news')
  .orderBy('postDate desc')
  .limit(6)
  .ids() %}

{% set newsIds = recentNewsIds|without(entry.id)|slice(0,5) %}
```

Now I have to write

```twig
{% set recentNewsIds = craft.entries()
  .section('news')
  .orderBy('postDate desc')
  .limit(6)
  .ids() %}

{% set newsIds = recentNewsIds|without("" ~ entry.id)|slice(0,5) %}
```

OR 

```twig
{% set recentNewsIds = craft.entries()
  .section('news')
  .orderBy('postDate desc')
  .limit(6)
  .ids() %}

{% set currentNewsId = craft.entries()
  .section('news')
  .id(entry.id)
  .ids() %}

{% set newsIds = recentNewsIds|without(currentNewsId)|slice(0,5) %}
```

### Expected behavior

I would expect the without filter to not be affect by the type or to have a note in the docs to clarify this if this is expected behaviour.

### Craft CMS version

4.1.4.1

### PHP version

8.1.3

### Operating system and version

Linux 4.15.0-163-generic

### Database type and version

MySQL 8.0.23

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-26)

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for pointing that out! I’ve just made `|without` and `craft\helpers\ArrayHelper::removeValue()` (the method used under the hood) use non-strict value comparisons by default for Craft 4.2, and they both have a new `$strict` argument which can be passed `true` if strict comparisons should be enforced.

(Also worth noting that the actual value type returned for `ids()` will vary depending on the version of MySQL. If you’re running MySQL 8.1+, you will get integers back.)

**Comment by brandonkelly** [comment]
Craft 4.2.0 is out now with those changes ✨

**Comment by jeromecoupe** [comment]
Updated to 4.2.0. I can confirm it works like a charm. Thanks for the swift fix, Brandon.
