### ISSUE TITLE
[4.x]: "className is not defined" js error when switching between sites

### ISSUE THREAD

**Issue by webrgp** [craftcms/cms#11709]
### Description

After updating Craft from 4.1.4.1 to 4.2.0.1, I notice that, when  using the site switcher (for example, in the Entries section):

![Screen Shot 2022-07-27 at 10 24 22 AM](https://user-images.githubusercontent.com/994788/181272437-7542a437-1c3f-489a-b96c-4f20d8c32570.png)

I get the following javascript error in the console, which is preventing the "site--${site.handle}" to be added to the document body.

<img width="1165" alt="Screen Shot 2022-07-27 at 10 22 56 AM" src="https://user-images.githubusercontent.com/994788/181271815-aca70f7a-29b2-4081-8469-b6869b24ef6a.png">

### Craft CMS version

4.2.0.1

### PHP version

8.1.7

### Operating system and version

Mac OS 12.4

### Database type and version

MySQL 10.5.13

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-35)

### Installed plugins and versions

- BlurHash: 2.0.3
- Calendar: 4.0.0-beta.6
- Control Panel Body Classes: 2.3.0
- Control Panel CSS: 2.5.0
- Empty Coalesce: 4.0.0-beta.1
- Mailgun: 3.0.0
- Mix Manifest: 1.0.1
- Navigation: 2.0.3
- Redactor: 3.0.2
- Relax: 2.0.0
- Retcon: 2.4.2
- Retour: 4.0.2
- SEOmatic: dev-develop-v4
- Smith: 2.0.0
- Store Hours: 3.0.0
- Super Table: 3.0.0
- Typed link field: 2.1.3-rc
- Typogrify: 4.0.0
- Video Utils: 2.0.2
- YouTube Live Embed: 4.0.0-beta.1

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just released Craft 4.2.0.2 with a fix.
