### ISSUE TITLE
[4.x]: Condition builder keeps using old site slug when switching between sites

### ISSUE THREAD

**Issue by FlorisDerks** [craftcms/cms#11719]
### Description

When you have a Craft CMS environment that contains multiple sites, the 'site' query parameter that is sent to the `admin/actions/conditions/render` action when opening the condition builder isn't updated when switching between sites, unless you refresh the page after switching.

### Steps to reproduce

1. Login to a CMS installation with multiple sites
2. Go to Entries
3. Select a different site using the dropdown
4. Open the filter condition-builder in the search bar at the top of the screen
5. You'll see in the network-tab that https://craftcms.test/index.php?p=admin/actions/conditions/render&site=default will be called, instead of it containing the slug of the secondary site
6. When trying to select a filter that uses site-specific data, it will refer to the wrong site
7. Only when the page is refreshed so that it loads with the newly selected site it works as expected

### Expected behavior

The condition builder should take into account the currently selected site, even when that has changed without a hard refresh of the entries-overview page. That means the condition builder should empty & reload when the site changes.

### Actual behavior

The site slug that was active at the time of loading stays active in conditionbuilder-related requests, even when the entries-overview shows a different site. Also, the search query stays active when switching from one site to another, while this isn't the case when switching between entry types.

### Craft CMS version

4.2.0.2

### PHP version

8.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Just fixed this for the next release. Now filters are managed for each site, so the condition builders will be completely site-specific.

**Comment by brandonkelly** [comment]
Craft 4.2.1 is out now with that change.
