### ISSUE TITLE
[3.x] [4.x]: Yii's static translations not working for Norwegian

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#11712]
### Description

When using Norwegian for the CP "Language" setting (either "Norwegian Bokmål" `nb` or "Norwegian Nynorsk" `nn`), static translations using the `'yii'` category are not translated from the source English.

One example is a common field validation error message like `'{attribute} cannot be blank.'`, which will render in English for authors having selected Norwegian as the language in their user preferences.

[Yii does have translations for Norwegian](https://github.com/yiisoft/yii2/blob/master/framework/messages/nb-NO/yii.php) (albeit _Bokmål_ only), so I assume the issue is that the locales doesn't match, i.e. Craft's `nb` and `nn` vs. Yii's `nb-NO`.

For front end requests this isn't a huge issue (at least for not content in _Norwegian Bokmål_) as sites can be set to use the proper locale `nb-NO` and have the Yii translations working. But since it's not possible to select `nb-NO` as the user preference language, it's impossible to have the Control Panel render in Norwegian with Yii's strings properly translated.

TBH, I'm not actually sure if this is a Craft issue or a Yii issue (or just that Norway is weird), but it's been a bit of a PITA for a long time, in cases where we otherwise make sure that everything inside the CP is properly translated for Norwegian clients. 

So, if there's any way to somehow have Yii's `nb-NO` translations render for `nb` and `nn` locales, that'd be much appreciated 🙏 (perhaps there's something we can stick in a custom module or `config/app.php` if this isn't something that is feasible to fix in core?)

### Steps to reproduce

I guess lots, but one example:  

1. Change the "Language" setting for the logged-in user to either "Norwegian Bokmål" (`nb`) or "Norwegian Nynorsk" (`nn`).
2. Save an entry with a blank required field (for example, the title field)
3. Confirm that the error message for the required field is in English (`{attribute} cannot be blank.`), not the Norwegian translation (`{attribute} kan ikke være tomt.`).

### Expected behavior

Static translations coming from Yii should use the Norwegian Bokmål translations if the user has selected Norwegian Bokmål (and ideally, Norwegian Nynorsk as well since even the wrong flavor of Norwegian is better than _no_ flavor of Norwegian) as their language.

### Actual behavior

All static translations using the `yii` category is rendered in the source English when using "Norwegian Bokmål" or "Norwegian Nynorsk" as the CP language.

### Craft CMS version

3.7.50 and 4.2.0.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Was also an issue for `de-CH`, `fr-CA`, and `zh`. Fixed for the next Craft 3 and 4 releases.

**Comment by brandonkelly** [comment]
Craft 4.2.1 is out with that fix.
