### ISSUE TITLE
[4.x]: CRAFT_CP_TRIGGER can not be overwritten in general.php?

### ISSUE THREAD

**Issue by Joobs** [craftcms/cms#11713]
In my `general.php` I sometimes use an operator to set a default value if the `.env` variable is missing or empty.

In the example below, i can access the CP at `/fallback`

```
.env
CONTROL_PANEL_TRIGGER=
```
```
general.php
'cpTrigger' => App::env('CONTROL_PANEL_TRIGGER') ?: 'fallback',
```

However `CRAFT_CP_TRIGGER` seems to be special constant in some way. If it exists in my `.env` and is empty I can't access the CP at all, and the operator has no effect. If it has a value, that values is always used even if I overwrite it in `general.php`.  In the below example I can't access the CP at all, `/fallback` doesn't work.

```
CRAFT_CP_TRIGGER=
```
```
'cpTrigger' => App::env('CRAFT_CP_TRIGGER') ?: 'fallback',

// or even this doesn't work:

'cpTrigger' => 'fallback',
```

An example of my use case: In the past I've had issues during site launches where content editors accidentally log into the development site (which is outdated content) instead of the production/staging site about to go live. I like to explicitly set a different CP trigger for each environment to try and make this less likely to happen.

```
'*' => [
       // obfuscate production admin for security
        cpTrigger' => App::env('CRAFT_CP_TRIGGER'),
],
'dev' => [
        // Reduce the chance the developers accidentally editing the wrong environment
        'cpTrigger' => 'dev-admin',
],
```

I like to keep empty vars in my development version of `.env` to keep track of everything. The `CRAFT_CP_TRIGGER=` in the `.env` overrides the `dev-admin` setting in the above example (on development environment).

I realise this is pretty edge case, and I could also use another `.env` var to set the cp trigger or remove it entirely. But i like to use the "correct" variable where possible. 
 

### Craft CMS version
4.2.0

**Comment by brandonkelly** [comment]
This is happening because `CRAFT_<SETTING_NAME>` environment variables take precedence over whatever `config/general.php` returns (which is why we refer to them as “environment _overrides_”).

If you want `config/general.php` to pull in an environment variable and have a fallback value, you will need to choose a different environment variable name.
