### ISSUE TITLE
[4.x]: Limited functionality when using tableDataEndpoint and VueAdminTable

### ISSUE THREAD

**Issue by rynpsc** [craftcms/cms#11724]
### Description

When using Craft.VueAdminTable and `tableDataEndpoint` it would appear that functionality is limited. In my testing special slots such as `__slot:menu` and `__slot:detail` do not appear to function yet loading the same data using `tableData` does.

### Steps to reproduce

1. Create a basic Craft.VueAdminTable with a `__slot:detail` and try outputing the same using data with`tableData` and `tableDataEndpoint` 

### Expected behavior

Special slots function with both methods of loading data.

### Actual behavior

Special slots such as detail render in the UI however are non functional e.g. detail doesn't expand when clicking.

### Craft CMS version

Craft Pro 4.2.0.2

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
HI @rynpsc 

Thank you for bringing this to our attention. We have pushed up a fix for this which will be included in the next release of Craft.

To get this early, change your `craftcms/cms` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/cms": "dev-develop#416162098523a9fdb383d3206a4b9308c6a36c34 as 4.2.0.2",
  "...": "..."
}
```

Then run `composer update`.

Thanks!
