### ISSUE TITLE
[3.x]: ProjectConfig does not create entries for existing single section but newly assigned multisites

### ISSUE THREAD

**Issue by hiasl** [craftcms/cms#11721]
### Description
Craft does not seem to create entries needed for single sections in newly added and section-enabled multisites when applying project config (Postgres)

### Steps to reproduce

Status on our staging system before `craft up`:
1. System with 2 multisites
2. A single section ABC assigned to the 2 multisites

ProjectConfig contains the following changes:
- adds some more multisites
- enables the single section ABC for some of the newly added multisites. the section itself is not new.

Status on our staging system after `craft up`:
- the new multisites are added
- the single section is enabled for the newly added multisites
- the entries necessary for the single section are missing for the newly added multisites.  When you click on "Entries > Singles" in one of the newly enabled multisites, the list of entries is empty, although there should be an entry ready to be used (you can not manually create the entry for a single section).

### Expected behavior
- For all newly enabled multisites "Entries > Singles" must contain an entry to be used.

### Actual behavior
 "Entries > Singles" ist empty for those multisites, that 
- were created and 
- enabled in the single section ABC
with `craft up` / Project Config

### Craft CMS version

Craft Pro 3.7.38

### PHP version

7.4.19

### Operating system and version

RHEL: Linux 4.18.0-372.16.1.el8_6.x86_64

### Database type and version

PostgreSQL 12.10

### Installed plugins and versions

-

**Comment by carlcs** [comment]
This might be related to https://github.com/craftcms/cms/issues/9567?

**Comment by hiasl** [comment]
Thanks @carlcs for referencing this. I tried a `project-config/apply --force` which in fact solved the issue for now (mentioned in the referenced ticket), but it needs to stay open.

**Comment by brandonkelly** [comment]
The entry won’t be fully enabled for the newly-added site until the queue is run. Just tested locally and I was able to reproduce the behavior you described, until the ResaveEntries job is executed. Then the entry is fully propagated to the new site, and editable within the control panel.

**Comment by hiasl** [comment]
I will check, but there should be a `queue/listen` active. My vacation will delay the response.

**Comment by brandonkelly** [comment]
This very well may have been related to #9567, which is now fixed in Craft 3.7.51. Going to close this for now, but let me know if you can still reproduce it on future deployments after updating to 3.7.51+.

**Comment by hiasl** [comment]
I updated and it works now. We can keep this closed. Thanks!
