### ISSUE TITLE
[4.x]: Long docblock comments for config fluent model setters

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#11723]
### The Problem

The original [pull request](https://github.com/craftcms/cms/pull/11591) for adding fluent model methods to config classes had the same docblock comments for the fluent setter methods that the original properties have.

While this results in some duplication of comments, I found in my testing that this was the only way to deliver the DX of full documentation for the properties in the editor (I did try `@see` as well):

<img width="914" alt="fluent-config-documentation" src="https://user-images.githubusercontent.com/7570798/181756687-e20ddc98-b723-4c55-a52b-d9b7e50e8357.png">

This was replaced with a 1 line description and the `@see` annotations, which results in a disparity between the long documentation you see for the properties, and a 1 liner for the fluent setter methods:

<img width="762" alt="Screen Shot 2022-07-28 at 7 39 17 PM" src="https://user-images.githubusercontent.com/7570798/181756935-c87b66db-cb8a-4a1a-8292-b98ff03c9482.png">

This makes it less useful, because the documentation is no longer easily available. In PhpStorm you then have to click on "See also" link, which unfortunately also does not render well:

<img width="762" alt="Screen Shot 2022-07-28 at 7 41 19 PM" src="https://user-images.githubusercontent.com/7570798/181757137-3d6ef2c3-1488-4d96-a662-65f5913a932e.png">

Additionally, other editors such as VS Code don't handle `@see` links at all, so all you get is this:

<img width="516" alt="Screen Shot 2022-07-28 at 8 27 54 PM" src="https://user-images.githubusercontent.com/7570798/181757241-f49e9de4-1d12-41d0-bb18-3f35252bbb42.png">

The more documentation provided in situ, the better, imo. It seems consistent to have the properties and the setters both display the same documentation. Easier to keep them in sync, too.

### The Resolution

Use the long comments from the original PR that match the docblock comments for the properties, 

### Craft CMS version

4.2.0

### PHP version

n/a

### Operating system and version

n/a

### Database type and version

n/a

### Image driver and version

n/a

### Installed plugins and versions

n/a

**Comment by michaelrog** [comment]
I agree — The value prop of the original PR seems largely diminished here. 🤔 

Also, I imagine that long-term, it'd actually be _less_ work overall to keep the docblock contents identical between property and methods (less cognitive overhead, easier copy/paste), rather than to have to translate between two different styles/schemes.

**Comment by brandonkelly** [comment]
Brought the long descriptions back for the next release 😅
