### ISSUE TITLE
[4.x]: Filter-hud uses wrong vertical position when window.scrollY > 0 during opening

### ISSUE THREAD

**Issue by FlorisDerks** [craftcms/cms#11739]
### Description

It seems that there's a problem with the vertical positioning of the filter-hud when it's opened if the main scrollposition of the page is not all the way to the top. The further you scroll down before opening the filter-hud, the lower it will show.

### Steps to reproduce

1. Go to the edit-form of an entry
2. Scroll down the page a bit
3. Choose a new author (or any other relation-field that can be reached when scrolled down)
4. Click the filter-icon in the search-bar of the element-selector modal
5. The filter-hud will be shown at the incorrect position (too low on the page, or not visible at all when scrolled down too far)
6. Try the same when scrolled all the way to the top, the filter-hud will now show correctly

### Expected behavior

The filter-hud should always align vertically with the search-bar which initialized it, both in the entry-overview and when selecting a relation inside the edit-form.

### Actual behavior

The filter-hud is shown too low on the page when `window.scrollY` it something different than zero. See https://prnt.sc/GqPkcLfub4-J for an example. It becomes worse the further you're scrolled down.

### Craft CMS version

4.2.0.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
This is an intentional change in Craft 4, mentioned in a couple of the release notes – rather than `success` keys, JSON responses will now either have a `200` or `400` status depending on whether it was successful (see the discussion at #8631).

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.2.1 is out with that fix.
