### ISSUE TITLE
[4.x]: Controller actions not returning a success key in JSON response

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#11738]
### Description
When calling a controller action through AJAX the response JSON isn't containing a success key anymore, on a quick look it looks like this is the case for all the controller actions 

### Steps to reproduce

1. call the users/save-user controller action for example
2. the response body is only containing the ID but no success param as per the docs (https://craftcms.com/docs/4.x/dev/controller-actions.html#with-json-request-header-3)

### Expected behavior
Response body should contain a success key (as in Craft 3)

### Craft CMS version

4.2.0.2

### PHP version

8.1

### Operating system and version

ubuntu 20

**Comment by brandonkelly** [comment]
This is an intentional change in Craft 4, mentioned in a couple of the release notes – rather than `success` keys, JSON responses will now either have a `200` or `400` status depending on whether it was successful (see the discussion at #8631).
