### ISSUE TITLE
Offer "gettext style" procedures for static copy.

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1173]
> Created by: Howard Roark (howie@codingcoop.org) on 2015/08/11 14:11:50 +0000
> Votes at time of UserVoice import: 2

-----------------------------------

In the past I have used what I would describe as "gettext style" procedures.   The basic idea is that on the "first go" you fill your template with the intended copy and translation tags (which is already the case with Craft). After you finish up a parsing tool combs through to find all the places where they exist and generates a ".pot" file.  This file is basically a translation template for your copy which works with a variety of GUI editors.  A translator take the file, fill in all the copy of a desired locale and pass it back as a key/value store ".po" file.

The reason this is great is because it allows you to place all of your copy over time and then get it all back when you wrap up.  Currently you have to build your own static translation file with Craft.

As I see it there are two options...

1. Build in a proper standardized gettext setup for static translations.

2.  Instead of keeping static translations in a file, store them in the db.  Then offer a cms page specifically specifically for entering translations using the same methodology.

**Comment by kruncher** [comment]
The above plugin is not compatible with Craft 3.

**Comment by brandonkelly** [comment]
Enupal Translate might be a suitable substitute? https://plugins.craftcms.com/enupal-translate
