### ISSUE TITLE
[4.x]: Setting database config via url doesn't work

### ISSUE THREAD

**Issue by mikejpeters** [craftcms/cms#11735]
### Description

Trying to set the database config using `url` results in a database connection error,
even when the URL is specified correctly.

### Steps to reproduce

1. Create a local MySQL database named `test`
1. Create `config/db.php` with contents:
    ```php
    return [
      'url' => 'mysql://127.0.0.1/test'
    ];
    ```

### Expected behavior

Craft should be able to connect to the database given the `url`.
Database config properties like `server` and `dsn` should be calculated from the `url`.

### Actual behavior

Craft cannot connect to the database, and the resulting database config has no value for `server`.

### Craft CMS version

4.2.0.2

**Comment by brandonkelly** [comment]
Thanks for reporting that. Just fixed for the next release.

To get the release early, change your `craftcms/cms` requirement in composer.json to `dev-develop as 4.2.0.2` and run `composer update`.

**Comment by mikejpeters** [comment]
I'd considered that as a fix, but I think because the individual properties aren't being set from the url (only the dsn), if you use the `DbConfig` to first set `url()` and then some other property, e.g. `database`, all other properties will be cleared and you'll have an invalid DSN again.

For example, with simply removing the `_updateDns()` this test will fail:

```php
$config = DbConfig::create()
  ->url('pgsql://127.0.0.1:5432/db')
  ->database('db2');
$this->assertEquals('db2', $config->database);
$this->assertEquals("pgsql:host=127.0.0.1;dbname=db2;port=5432", $config->dsn);
```

**Comment by brandonkelly** [comment]
Good point – fixed that as well. Originally with something closer to your PR (except only calling `dsn()`), but then realized it could be more performant if `url2config()` just returns the `driver`, `server`, `port`, and `database` keys in the returned config array, as it already has those parsed out of the URL.

**Comment by brandonkelly** [comment]
Craft 4.2.1 is out with that fix.
