### ISSUE TITLE
[4.x]: Changing Entry Type doesn't update layout.

### ISSUE THREAD

**Issue by belkin** [craftcms/cms#11742]
### Description

Changing entry type doesn't update layout with associated fields. Also there are no console errors or messages.
Tried with different browsers and disabled plugins but the result is same.

### Steps to reproduce

1. Have section with multiple entry types.
2. Start creating new entry.
3. Change entry type.

### Expected behavior

Entry layout to be updated with associated fields.

### Actual behavior

Entry layout doesn't update and stays same as the first entry type from the list.

### Craft CMS version

4.2.0.2

### PHP version

8.1

### Operating system and version

macOS 12.4

### Installed plugins and versions

-

**Comment by belkin** [comment]
I found the problem and it was due to a deprecated option of general config.

If I remove 'autosafeDrafts' from general config file the update of Entry Type works.

**Comment by brandonkelly** [comment]
Yeah entry type switching and Live Preview both rely on `autosaveDrafts` being enabled in Craft 4, and the reason it was added in the first place was for performance reasons that aren’t really relevant anymore.
