### ISSUE TITLE
[3.x]: Unable to pick parent when creating new categories from Categories field modal/slideout

### ISSUE THREAD

**Issue by jamiepittock** [craftcms/cms#11745]
### Description

When creating a new category via the Categories field modal / slideout, I'm unable to select a parent for the category. This results in all categories created this way to be level 1.

If this isn't a bug or is a deliberate omission, a workaround for us would be the ability to selectively remove the "+ New  category" action from the Categories field modal, forcing editors to create new categories from the Categories index.

![Screenshot 2022-08-04 at 15 47 40](https://user-images.githubusercontent.com/35454/182879364-dfef6027-2a57-4c7e-9a85-c87bd1a8a39e.png)

![Screenshot 2022-08-04 at 15 50 08](https://user-images.githubusercontent.com/35454/182879378-0024d4a4-fc98-4e90-87bf-a3eaa062fad0.png)

### Craft CMS version

3.7.48

### PHP version

8.0.17

### Installed plugins and versions

-

**Comment by jamiepittock** [comment]
I can see this has been fixed in Craft 4. Any chance of it being ported back to 3.7?

**Comment by brandonkelly** [comment]
It was “fixed” as part of completely rewriting how element editor slideouts work in Craft 4 (#10467), so not something that could be backported to Craft 3 unfortunately.
