### ISSUE TITLE
[4.x]: "Related To" unavailable for field conditions

### ISSUE THREAD

**Issue by turnstylerj** [craftcms/cms#11740]
### Description

When adding field conditions in the field layout designer, "Related To" is not available in the list of rule categories.

![Screen_Shot_2022-07-01_at_11 39 00_AM](https://user-images.githubusercontent.com/42223501/182719936-25ddc296-844f-4bea-bd26-176191530db7.png)

This was [discussed on Discord](https://discord.com/channels/456442477667418113/456442477667418115/992500907709304883) and according to Brandon, is happening because Craft never added support for using Related To in conditions that get stored in the project config. He mentioned this would be added to the 4.2 list, but I'm still not seeing it.

### Steps to reproduce

1. Create a section
2. Add a field
3. Open the dropdown to choose field display conditions

### Expected behavior
"Related To" will be an option.

### Actual behavior
"Related To" is missing from the list.

### Craft CMS version

4.2.0.2

### PHP version

8.0.1

### Operating system and version

Darwin 21.3.0

### Database type and version

MySQL 5.7.34

### Image driver and version

GD 8.1.1

### Installed plugins and versions

"craftcms/aws-s3": "2.0.1",
"craftcms/feed-me": "5.0.4",
"craftcms/redactor": "3.0.2",
"doublesecretagency/craft-cpcss": "2.5.0",
"internetztube/craft-element-relations": "2.0.0",
"mmikkel/retcon": "2.4.2",
"nystudio107/craft-imageoptimize": "4.0.2",
"nystudio107/craft-minify": "4.0.0-beta.2",
"nystudio107/craft-seomatic": "4.0.7",
"percipioglobal/craft-colour-swatches": "4.2.0.1",
"spicyweb/craft-neo": "3.2.5",
"verbb/field-manager": "3.0.1",
"vlucas/phpdotenv": "^5.4.0",
"weareferal/matrix-field-preview": "4.0.2"

**Comment by brandonkelly** [comment]
Just made it possible to use “Related To” conditions in custom sources and field layout conditions, for the next release. In each case the condition will be stored in the project config, so we can’t use a normal element select – you will need to enter the related element ID manually (or ideally, use an environment variable since the ID is likely to be different on other environments).

<img width="716" alt="A condition with a “Related To” rule, set to relate an entry with the ID determined by an “$ABOUT_ENTRY_ID” environment variable" src="https://user-images.githubusercontent.com/47792/183296789-4ff8aac1-c4ec-480b-baf2-ebb0f92be370.png">

**Comment by Mosnar** [comment]
> Just made it possible to use “Related To” conditions in custom sources and field layout conditions, for the next release. In each case the condition will be stored in the project config, so we can’t use a normal element select – you will need to enter the related element ID manually (or ideally, use an environment variable since the ID is likely to be different on other environments).
> 
> <img alt="A condition with a “Related To” rule, set to relate an entry with the ID determined by an “$ABOUT_ENTRY_ID” environment variable" width="716" src="https://user-images.githubusercontent.com/47792/183296789-4ff8aac1-c4ec-480b-baf2-ebb0f92be370.png">

What do you think about supporting reference tags here? The above example could then be:

`{entry:pages/about:id}`

and you wouldn't need to fuss with environment variables

**Comment by brandonkelly** [comment]
Possibly, although that only really makes sense for singles. And I suppose singles are the exception to the rule – we could find a way to safely create a UI for selecting them in a project config-safe way.

**Comment by brandonkelly** [comment]
Craft 4.2.1 is out with that change.

**Comment by bencroker** [comment]
> In each case the condition will be stored in the project config, so we can’t use a normal element select – you will need to enter the related element ID manually (or ideally, use an environment variable since the ID is likely to be different on other environments).

This tripped me up when explaining the condition builder to a class of students who have no idea what project config is. I myself don't quite understand why having the condition _stored_ in project config means that that element cannot be _selected_ using an element select field – can you please explain this @brandonkelly?

**Comment by brandonkelly** [comment]
@bencroker Because we can’t assume that any two environments have the same content. An element ID `100` in one environment might be for Entry X, whereas it could be Matrix Block X or User X in other environments.

**Comment by bencroker** [comment]
> An element ID 100 in one environment might be for Entry X, whereas it could be Matrix Block X or User X in other environments.

Wouldn't storing the element’s UID allow you to get around environmental discrepancies?

**Comment by brandonkelly** [comment]
I’m not sure how that would help? The only time an element’s UID will be the same across environments is if the database was copied over from one to the other, after the element was created. The ID would work just as well in that case.

And if you definitely know that the UID/ID is safe, you are welcome to enter it manually within the condition rule. We just don’t want to show an element selector and give the false impression that selecting an element (and thus storing its ID) it’s a safe thing to do in general.

**Comment by bencroker** [comment]
Ah right, my bad, I was confusing an element's UID (not stored in project config) with an element type's UID (stored in project config). Thanks for helping me understand!
