### ISSUE TITLE
More status colors

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1174]
> Created by: Bob Olde Hampsink (b.oldehampsink@itmundi.nl) on 2015/04/30 06:39:01 +0000
> Votes at time of UserVoice import: 2

-----------------------------------

Now we have blank, orange, red and green status indicators. I'd like to see more colors,as they can be used for more than just these.

**Comment by brandonkelly** [comment]
This was resolved in 2.5.0 / 3.0.0
