### ISSUE TITLE
[3.7.29]: Db backup/restore commands do not work when DB password contains a dollar sign

### ISSUE THREAD

**Issue by ivanBereznev** [craftcms/cms#11750]
### Description
When there is a `$` sign in the DB password, `craft db/backup` and `craft db/restore` commands fail because of authorization error `password authentication failed for user testuser`

### Steps to reproduce

1. Create a DB user with username `testuser` and password `test$test`
2. Configure Craft CMS to use these credentials
3. Install Craft CMS
4. Try to create a DB backup by running `craft db/backup` from command line

### Expected behavior
Database backup is created

### Actual behavior
Database backup is not created because of authorization error.

Looks like that the reason is that [this line](https://github.com/craftcms/cms/blob/develop/src/db/Connection.php#L454) escapes the backslash which is supposed to escape the `$` symbol and  the password gets represented as `test\\$test`, whereas it should be `test\$test`. 
The reversed order of operations works properly, i.e. changing that line to
```
'{password}' => str_replace('$', '\\$', addslashes($password))
```
produces a correctly escaped password.

### Craft CMS version

3.7.29

### PHP version

7.3.33

### Operating system and version

Debian GNU/Linux 11

### Database type and version

PostgreSQL 13.6

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that, and for the suggested fix! Applied that fix for the next Craft 3 and 4 releases.

**Comment by brandonkelly** [comment]
Craft 3.7.51 and 4.2.1 are out with the fix.
