### ISSUE TITLE
[3.x]: Warning from `getUserTemporaryUploadFolder` due to null user

### ISSUE THREAD

**Issue by chrismlusk** [craftcms/cms#11751]
### Description

Our error monitoring logs are showing thousands of the following ErrorException message:

> Warning: Attempt to read property "id" on null

Per the stack trace, this is happening when the [getUserTemporaryUploadFolder](https://github.com/craftcms/cms/blob/3.7.50/src/services/Assets.php#L1084) method is called.

```php
    public function getUserTemporaryUploadFolder(User $user = null)
    {
        if ($user === null) {
            // Default to the logged-in user, if there is one
            $user = Craft::$app->getUser()->getIdentity();
        }

        if (isset($this->_userTempFolders[$user->id])) { # <-- issue happens here
            return $this->_userTempFolders[$user->id];
        }
```

The `getIdentity` method can return null, hence the warning about reading the `id` property.

Although I marked this as a Craft 3 bug, it looks like it might affect 4.x as well.

### Craft CMS version

3.7.50

### PHP version

8.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next Craft 3 and 4 releases.

**Comment by brandonkelly** [comment]
Craft 3.7.51 and 4.2.1 are out with the fix.

**Comment by chrismlusk** [comment]
Hi Brandon, it looks like this issue is still happening when there is no logged-in user. There are two additional attempts to access `$user->id` later on in the method:
* [line 1110](https://github.com/craftcms/cms/blob/3.7.51/src/services/Assets.php#L1110)
* [line 1141](https://github.com/craftcms/cms/blob/3.7.51/src/services/Assets.php#L1141)

**Comment by brandonkelly** [comment]
Doh, thanks. Fixed now.

**Comment by brandonkelly** [comment]
Craft 3.7.52 and 4.2.2 are out now with those fixes.
