### ISSUE TITLE
View Entries by Author in Control Panel

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1176]
> Created by: Visiluna (pjones@visiluna.com) on 2015/06/16 22:04:13 +0000
> Votes at time of UserVoice import: 2

-----------------------------------

I frequently need to view all the entries by a particular author, but there doesn't appear to be any way to do this currently.

Would be great to put something like "author:name" in the entries search box. Or in the user's record, have a link to "view all entries by this author."

There are any number of ways this could be implemented. Any of them would be appreciated.

**Comment by janhenckens** [comment]
Bumping this one. In this case I have a search on the front-end of a site and searching for the author name doesn't return their own entries.
