### ISSUE TITLE
[4.x]: cp.elements.element in a weird place

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#11762]
### Description
Just upgraded a project from 3 to 4 and I noticed that the `cp.entries.edit.details` is no longer working. When looking at the docs & the code, I see a code called `cp.elements.element` that could fix this but that ends in between the slug and the author...

### Steps to reproduce

1. Add this template hook:
```
Craft::$app->view->hook('cp.elements.element', function (array &$context) {
    echo "Good afternoon";
});
```

2. Open an entry detail view:
![Screenshot 20220811-163554-rhZwuhVt](https://user-images.githubusercontent.com/755428/184158935-4a60b811-88ab-4f22-bf1b-fc4e997ee284.png)

### Expected behavior
Pre Craft 4 this was displayed below the other items on the right sidebar, in the current version it ends up between the slug and the author, which feels like a strange place to inject something

### Craft CMS version

4.2.1.1

### PHP version

8.1.8

### Operating system and version

Linux 5.10.104-linuxkit

### Database type and version

MySQL 10.4.25

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
That hook was removed as part of the move to a unified element editor (#10467).

You can use the `craft\base\Element::EVENT_DEFINE_SIDEBAR_HTML` event instead, though:

```php
use craft\elements\Entry;
use craft\events\DefineHtmlEvent;
use yii\base\Event;

Event::on(
    Entry::class,
    Entry::EVENT_DEFINE_SIDEBAR_HTML,
    function(DefineHtmlEvent $event) {
        /** @var Entry $entry */
        $entry = $event->sender;
        $event->html .= '...';
    }
);
```

**Comment by janhenckens** [comment]
Ha, neat, thanks for the clarification!
