### ISSUE TITLE
Unable to login due to session_start(): Failed to read session data: files (path: /var/lib/php/session) [3.x]: 

### ISSUE THREAD

**Issue by danfathom** [craftcms/cms#11769]
### What happened?

Hi,

We are having an issue of not being able to login to the admin dashboard on our site. This is only happening on our client server as they are wanting to host the site. We previously had it on our server and it was fine.

When trying to login, it tries but does nothing. I'm getting logs in the storage/logs folder that mention "session_start(): Failed to read session data: files (path: /var/lib/php/session)". 

I'm unsure how I got about fixing this?

I've attached the web.log folder below
[web.log](https://github.com/craftcms/cms/files/9315677/web.log)

thanks,
Dan

### Craft CMS version

Craft Solo 3.7.50

### PHP version

7.4.30

### Operating system and version

Unsure as can't login to see system report

### Database type and version

Unsure as can't login to see system report

### Image driver and version

Unsure as can't login to see system report

### Installed plugins and versions

-

**Comment by angrybrad** [comment]
It sounds like whatever user:group your client's webserver is configured to run PHP as, doesn't have permissions to read/write to `/var/lib/php/session`, which is where PHP is configured to store its session files on that box.

Correct that, and it should resolve the error.
