### ISSUE TITLE
[4.x]: Can't see children in structure when picking a parent

### ISSUE THREAD

**Issue by DowleyDeveloped** [craftcms/cms#11760]
### Description

When trying to select a child page as a parent, the dropdown in the popup is empty.

### Steps to reproduce

1. Create a new entry
2. Click Add a Parent
3. Try and select a child

### Expected behavior

The child should display

### Actual behavior

No Children Display

<img width="527" alt="Screenshot 2022-08-11 at 15 21 58" src="https://user-images.githubusercontent.com/24968042/184155597-ac9cf111-2236-4190-891b-030bc1a11418.png">

### Craft CMS version

4.2.1.1

### PHP version

8.0.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
It is expected that all descendants of the current entry are not available to be selected. Not really clear how existing parent-child relationships should react if such a selection would be made.

https://github.com/craftcms/cms/blob/520908d923bae2fafa3c151bd828cc4383672b03/src/elements/Entry.php#L1726-L1736

**Comment by DowleyDeveloped** [comment]
@brandonkelly my query isn’t related to the above, there is no parent attached and I’m trying to add one but none are showing?

**Comment by brandonkelly** [comment]
Sorry, you said “children” which I took to mean “children of the entry”. I guess you just meant “existing entries”.

**Comment by DowleyDeveloped** [comment]
Ah apologies!

**Comment by brandonkelly** [comment]
I’m not able to reproduce. Can you please send your database backup and `composer.json` + `composer.lock` files into support@craftcms.com so we can look into it for you?

**Comment by olivierbon** [comment]
Solved in support. The reason was that this particular section had a **Max Levels** set to `2` meaning that only level 1 entries would show in the modal.
