### ISSUE TITLE
[4.x]: Restore button is missing from Asset index

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#11761]
### Description

The asset restore button is not present on the asset element index - only the Permanently Delete button is shown. This is true regardless of whether the original file was kept or discarded.

### Steps to reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### Craft CMS version

4.2.1.1 Pro

### PHP version

8.0

### Installed plugins and versions

N/A

**Comment by brandonkelly** [comment]
> This is true regardless of whether the original file was kept or discarded.

There’s no option to keep the files when deleting assets, though. Which is why there’s no “Restore” button – there’s never going to be a file to restore.

**Comment by Mosnar** [comment]
> > This is true regardless of whether the original file was kept or discarded.
> 
> There’s no option to keep the files when deleting assets, though. Which is why there’s no “Restore” button – there’s never going to be a file to restore.


@brandonkelly there is if you use it programmatically:
https://github.com/craftcms/cms/blob/c659d09db949909b8e0631e384bdd58129a330bc/src/elements/Asset.php#L699-L704

For context, I was looking at making adjustments to the S3 plugin to make use of S3's version history, which allows files to be marked as deleted without permanently deleting them, thus allowing me to implement a "restore" function.

**Comment by brandonkelly** [comment]
Ah good point.

**Comment by brandonkelly** [comment]
Made it possible to restore soft-deleted assets in Craft 4.3, provided they were programmatically deleted with `$keepFile == true`.
