### ISSUE TITLE
[3.7.51]: Unable to Purchase Plugins in Production 

### ISSUE THREAD

**Issue by brettburwell** [craftcms/cms#11764]
### Description
Unless I'm misremembering, previously admin users could purchase a license for Craft and all paid plugins directly in the production environment (even with `allowAdminChanges` set to `false`). Craft would even automatically add everything to the plugin store cart for you, which was a nice touch. 

In recent releases we're no longer seeing that functionality. Instead, we can purchase a Craft license, but are unable to purchase licenses for paid plugins. When visiting the plugin's page in the the Plugin Store section of the control panel, we can see the plugin marked as a trial, but there's not an option / button to purchase a license. 

### Steps to reproduce
Purchase a plugin license by clicking the "Buy Now" button in the "There are trial licenses that require payment" nag alert or via that plugin's page in the Plugin Store section of the control panel.  

### Expected behavior
Clicking the "Buy Now" button automatically fills your cart with a Craft license and any paid plugins. When visting the plugin's page in the control panel there's an "Add to cart" button you can use to purchase the plugin. 

### Actual behavior
When clicking "Buy Now" in the nag alert only the Craft license is added. When visiting the plugin's page there is no "Add to Cart" button. 

Temporally toggling the `allowAdminChanges` config option to `true` allows us to purchase plugins, but I swear that didn't used to be necessary (and is less than ideal with project config enabled).

### Craft CMS version

3.7.51

### PHP version

8.0.19

### Operating system and version

Linux 5.4.0-107-generic

**Comment by brandonkelly** [comment]
Thanks for pointing that out! There was an API bug that was preventing the Plugin Store from knowing about your currently-active trials. Fixed now!

**Comment by brettburwell** [comment]
Awesome. Thanks Brandon!
