### ISSUE TITLE
[3.x]: Preview requests get the iframe resizer asset script registered

### ISSUE THREAD

**Issue by jamiepittock** [craftcms/cms#11778]
### What happened?

We've noticed preview requests get the iframe resizer asset script registered. The injected script is causing an issue for us that we're having to workaround. Note, there's nothing wrong with the actual script.

Should this be happening? I thought this script would only be needed for live preview requests?

### Craft CMS version

3.7

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Doh, thanks for pointing that out! It also shouldn’t have been getting included at all, unless the [`useIframeResizer`](https://craftcms.com/docs/4.x/config/config-settings.html#useiframeresizer) config setting was enabled. Just fixed that for the next Craft 3 and 4 releases.

**Comment by brandonkelly** [comment]
Craft 3.7.52 and 4.2.2 are out with that fix.
