### ISSUE TITLE
[3.x]: Template UI Elements are not translatable

### ISSUE THREAD

**Issue by mikesnoeren** [craftcms/cms#11770]
### Description
When using a 'template' field on an entry you would expect static translations to still work, even though the template is being used in the cms. But this doesn't happen.

I suspect the reason for this is because translations in the cms are looking for a different tranlsation file. I am however including part of my front-end into the back-end to display the result to the user.

### Steps to reproduce

1. Make a twig template that uses a static translation.
2. Add said template to a section or global. (edit entry type -> UI Elements -> Template)
3. Navigate to the entry/global and see that this doesn't work as expected?

### Craft CMS version

3.7.51 (Pro)

### PHP version

7.3.33

### Operating system and version

Linux 5.10.109-0-virt

### Database type and version

MySQL 5.7.38

### Image driver and version

Imagick 3.6.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- Back In Stock 1.4.4
- Craft Commerce 3.4.16
- Feed Me 4.5.3
- Instagram Feed 1.1.8
- Kint 1.0.0
- MatrixMate 1.5.0
- Mollie for Craft Commerce 3.0.1
- Navigation 1.4.28
- Preparse Field 1.4.0
- Redactor 2.10.10
- SEOmatic 3.4.37
- Super Table 2.7.2
- SVG Placeholder 1.0.3
- Typed link field 1.0.25

**Comment by mikesnoeren** [comment]
@mmikkel pointed out the following on Discord:

> One detail is that, like all static translations inside the CP (regardless of category) Craft will use the current user's "Language" setting for the translation – not the language for the element's site

Turns out translations do work, but are account setting specific. 
Wouldn't it be a good idea to be able to opt-out of that when defining my translations?

```twig
{{ 'translate_me'|t({
  cmsUserSpecificTranslations: false,
})
```

**Comment by wsydney76** [comment]
You override this default behavior by passing the language you want to the `t` filter https://github.com/craftcms/cms/blob/c659d09db949909b8e0631e384bdd58129a330bc/src/web/twig/Extension.php#L339

`'some text'|t(null, null, element.site.language)`

/Mel

**Comment by mikesnoeren** [comment]
Great, thanks! @wsydney76

**Comment by brandonkelly** [comment]
Glad you got it sorted :)
