### ISSUE TITLE
[3.6.5]: Couldn’t save the public token. (GraphQL)

### ISSUE THREAD

**Issue by mar-veloper** [craftcms/cms#11779]
### Description
Whenever I click graphql from the sidemenu I get this Error.

![Screenshot 2022-08-15 at 14 27 13](https://user-images.githubusercontent.com/42553243/184639261-6f69d758-d5f2-4ac8-9b23-2ddbe56493fc.png)

### Craft CMS version

3.6.5

### PHP version

7.4

**Comment by brandonkelly** [comment]
There have been a couple bug fixes related to GraphQL token generation in more recent versions of Craft. Please try updating to the latest (currently 3.7.51), and see if that resolves it.

**Comment by mar-veloper** [comment]
Upgrading to v3.7.51 didn't help. But I managed to solve it by manually deleting graphql token and schema in the database.

**Comment by mar-veloper** [comment]
@brandonkelly upgrading to v3.7.51 didn't help. But I managed to solve it by manually deleting graphql token and schema in the database.
