### ISSUE TITLE
[4.x]: Matrix block titlebars have lost their border-radius

### ISSUE THREAD

**Issue by thisisjamessmith** [craftcms/cms#11783]
### What happened?

Hard to spot, but the matrix block titlebars have lost their border radius in Craft 4:

<img width="29" alt="image" src="https://user-images.githubusercontent.com/2416106/184838284-e0c18de6-7b01-483a-977c-b87fbaae8158.png">

Caused by:

<img width="608" alt="image" src="https://user-images.githubusercontent.com/2416106/184838367-2b7b12d3-f11b-4a82-a60c-de1e8af597e2.png">

I only spotted it because I sometimes use the the CP CSS plugin to invert the background colour on those titlebars to make them more prominent, where it becomes more obvious:

<img width="518" alt="image" src="https://user-images.githubusercontent.com/2416106/184839109-0f37c693-652c-4ac2-ac68-8c0230dbf61b.png">

### Craft CMS version

4.2.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next release.
