### ISSUE TITLE
[4.x]: Changing section from "channel" to "structure" doesn't work 100%

### ISSUE THREAD

**Issue by vandres** [craftcms/cms#11786]
### Description

I am having a section, which was planned as channel. It then was required to make it sortable manually, so I changed it to a structure. Unfortunately, the "cross" icon is not showing up and I cannot resort the entries.

Am I missing something here?

![image](https://user-images.githubusercontent.com/1436383/184847860-2d2dbf6e-0fc0-4802-8649-76b6a9266acd.png)

![image](https://user-images.githubusercontent.com/1436383/184847766-74f96b8c-719e-4507-9112-0c56385645ae.png)

![image](https://user-images.githubusercontent.com/1436383/184848137-4d92226c-9a72-4bbf-8e3e-fb149ed6c7dc.png)

### Steps to reproduce

1. Create a new section of type channel
2. Create some entries
3. Change the type to structure

### Expected behavior

Entries are sortable.

### Actual behavior

Entries still behave like channels

### Craft CMS version

4.2.1.1

### PHP version

8.1

### Operating system and version

MacOS, Debian Docker

### Database type and version

MariaDB 10.5

### Image driver and version

-

### Installed plugins and versions

```json
  "require": {
    "craftcms/cms": "^4.2.0.2",
    "craftcms/commerce": "^4.1",
    "craftcms/redactor": "^3.0",
    "firephp/firephp-core": "^0.5.3",
    "mmikkel/cp-field-inspect": "^1.4",
    "nystudio107/craft-vite": "^4.0",
    "php-http/curl-client": "^2.2",
    "spicyweb/craft-neo": "^3.2",
    "typesense/typesense-php": "^4.8",
    "vaersaagod/geomate": "^2.0",
    "verbb/expanded-singles": "^2.0",
    "verbb/field-manager": "^3.0",
    "verbb/tablemaker": "^4.0",
    "verbb/wishlist": "^2.0",
    "vlucas/phpdotenv": "^5.4.0"
  },
  "require-dev": {
    "roave/security-advisories": "dev-master",
    "deployer/deployer": "^7.0",
    "yiisoft/yii2-shell": "^2.0.3"
  },
```

**Comment by thupsi** [comment]
Try changing the sorting option on the top right from "title" to "structure".

**Comment by vandres** [comment]
Oh boy, thanks a lot!
