### ISSUE TITLE
[4.x]: Environment variables not available in some site settings

### ISSUE THREAD

**Issue by russback** [craftcms/cms#11785]
### Description
Not able to select an environment variable for settings such as System Status.

### Steps to reproduce

1. Add a variable to `.env` file: `SITE_ONLINE=1`
2. Go to admin panel and click on System Status dropdown.

### Expected behavior
`$SITE_ONLINE` variable should be available to select.

### Actual behavior
`$SITE_ONLINE` variable is not available to select.

### Craft CMS version

4.2.1.1

### PHP version

8.0

### Operating system and version

Ddev v1.20.0

### Database type and version

Ddev Mariadb v10.4

### Installed plugins and versions

- None - bare install

**Comment by brandonkelly** [comment]
The **System Status** setting can be configured via the [`isSystemLive`](https://craftcms.com/docs/4.x/config/config-settings.html#issystemlive) config setting, which can be set either directly from `config/general.php` or via a `CRAFT_IS_SYSTEM_LIVE` environment variable:

```php
'isSystemLive' => true,
```

```sh
CRAFT_IS_SYSTEM_LIVE=true
```

Or if you really want to go with `SITE_ONLINE`, you can pull that environment variable value in from `config/general.php`:

```php
use craft\helpers\App;

return [
    // ...
    'isSystemLive' => App::env('SITE_ONLINE'),
];
```
