### ISSUE TITLE
[4.x]: yii\base\UnknownMethodException: Calling unknown method: craft\models\FieldLayoutTab::getFields() in /var/www/html/vendor/yiisoft/yii2/base/Component.php:300

### ISSUE THREAD

**Issue by sjeng** [craftcms/cms#11793]
### Description
Missing method definition `getFields` in `FieldLayoutTab` since Craft 4. It looks the similar `getFields` methods in other classes got renamed to `getCustomFields` according to the changelog, but the method for `FieldLayoutTab` just got flat out removed with no replacement. 

### Craft CMS version

4.2.1.1

### PHP version

8.1.0

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Looks like that was overlooked for the 4.0.0 release notes, so just retroactively added it—thanks.

What’s your use case for wanting it back though?

**Comment by sjeng** [comment]
We built a reverse relation module that lists out all the entries across all the sections that are related to the current entry on the CP edit page. The items in the list contains links to their respective edit pages.  The relationships for some of the entries are defined in tabs, so for QoL we try to link directly to the corresponding tab. 

We used the `getFields()` method to find which tab contains the entry field so we can create the direct link. It's not really a mission critical code at all, so we can remove that piece of functionality if the method can't be added back in.

**Comment by brandonkelly** [comment]
Gotcha. It was removed because there’s no need for it in Craft anymore.

You could add your own logic to find which tab a field belongs to though, probably more efficiently than you’d do it with a `FieldLayoutTabs::getCustomFields()` method:

```php
use craft\base\FieldInterface;
use craft\fieldlayoutelements\CustomField;
use craft\models\FieldLayout;
use craft\models\FieldLayoutTab;

function findField(FieldLayout $fieldLayout, FieldInterface $field): ?FieldLayoutTab
{
    foreach ($fieldLayout->getTabs() as $tab) {
        foreach ($tab->getElements() as $element) {
            if ($element instanceof CustomField && $element->getField()->id === $field->id) {
                return $tab;
            }
        }
    }
    
    // The field couldn't be found
    return null;
}
```
