### ISSUE TITLE
[4.x]: Alias not working in Category URI

### ISSUE THREAD

**Issue by angelokeirsebilck** [craftcms/cms#11806]
### Description
I am trying to set the URI of a category dynamically with an alias.

I have setup an .env var PREVIEW_URL and an alias '@previewUrl' => craft\helpers\App::env('PREVIEW_URL')

Reading in the docs you can use aliases in the URI.

In the category settings I try to set the URI of the category to {{alias(@previewUrl)}}/{slug} but on save I get an error:
Unexpected character "@" in "__string_template__

### Steps to reproduce

1. Setup a alias.
2. Create a category and use the alias in the URI.

### Expected behavior

Uri of the category when using preview or view should contain the value of the .env var.

### Actual behavior

URI contains ' alias(@previewUrl)}} ". Alias did not get parsed.

### Craft CMS version

4.2.1.1

### PHP version

8.1.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
You can do that like so:

```twig
@previewUrl/{slug}
```
