### ISSUE TITLE
[4.x]: Default table values not displaying in a global

### ISSUE THREAD

**Issue by murtaugh** [craftcms/cms#11804]
### Description

I'm new to Craft so hopefully I'm not just missing something: I set up my first global, and created a table field for it. I defined default values for the table field, which has worked in other entry types, but the default values don't show up in the global.

### Steps to reproduce

1. Create a table field (the native version) with some default values. (I have 7 rows predefined.)
2. Assign it to a global
3. Edit the global

### Expected behavior

The default values to appear.

### Actual behavior

They do not appear.

### Craft CMS version

4.2.1.1

### PHP version

8.0.8

### Operating system and version

Mac OS 13.0 Beta (22A5321d)

### Database type and version

MySQL 5.7.34

### Installed plugins and versions

<img width="929" alt="Screenshot 2022-08-19 at 1 15 32 PM" src="https://user-images.githubusercontent.com/308752/185672497-17f6808d-17c1-4d20-a978-af3de578d9cb.png">

**Comment by brandonkelly** [comment]
Table fields’ Default Values settings will only affect newly-created elements. For global sets, that means that the Table field would need to be set on the field layout at the time the global set is initially created. The setting is is really more for entries, where it’s much more likely to actually have an effect, as new entries will be created over time.
