### ISSUE TITLE
[4.x]: The selected asset isn't replaced when saving new assets edited in image editors opened via Asset fields

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#11805]
### Description

Since https://github.com/craftcms/cms/discussions/8974 was implemented in https://github.com/craftcms/cms/commit/6764c9ab5404f1384dd2fac539e3d47740e124be, saving an edited image as a new asset via an image editor opened via a selected image in an assets field, is supposed to replace the original, selected asset in that field.

This feature was apparently [broken at some point during the beta](https://github.com/craftcms/cms/discussions/8974#discussioncomment-2379404), then fixed for Craft 4.0.0-beta.3 via https://github.com/craftcms/cms/commit/40cc20ec689eca15bc298741fde0785288b4c1b1 – but it still doesn't appear to actually work as of Craft 4.2.1.1.

Unfortunately I couldn't get Craft 4.0.0-beta.3 to work, but I did test on Craft 4.0.0-RC1 and it was the same there – so not sure if this has ever worked reliably? :)

### Steps to reproduce

1. Upload an image to a volume. The volume uses a filesystem with URLs, in case that matters.
2. Add an assets field to an entry type field layout.
3. Create an entry, and add the image to the assets field. Save the entry.
4. In the entry's edit page; double-click the selected asset in the assets field. Then, click the "Edit Image" button on top of the thumbnail image in the asset slideout.
5. Edit the image (e.g. by rotating it) in the Image Editor, then click "Save as a new asset".

### Expected behavior

When the image editor closes after saving the new asset, the originally selected asset in the assets field should be swapped out with the newly-saved, edited image (and a provisional draft should be created/saved for the entry containing the field).

(Sidenote: I guess ideally the asset slideout should also be updated to edit the newly-saved, edited image instead of the original asset – otherwise authors might be confused if they continue editing custom fields, alternative text etc. and it saves to the asset that is no longer selected in the field.)

### Actual behavior

The original asset is retained in the asset field and slideout; i.e. it still works just like in Craft 3. No JS errors in the dev console.

### Craft CMS version

4.2.1.1

### PHP version

8.1.8

### Operating system and version

macOS 12.4

### Database type and version

10.8.3-MariaDB

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-29)

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Doh, this feature has had a history :)

It was originally added via 6764c9ab5404f1384dd2fac539e3d47740e124be, but then had to be re-implemented for the new unified element editor via 40cc20ec689eca15bc298741fde0785288b4c1b1, but then I accidentally [removed a critical part of it](https://github.com/craftcms/cms/commit/2aafe7a66bb407356ee78c65c2c60546b90130a2#diff-f730b61ee624355843725541b9528c566301126744cbd7a1ac7a53e5165382deL303) when implementing element auto-refreshing.

Brought that line back for the next release, and now it’s working as intended now.

**Comment by brandonkelly** [comment]
4.2.2 is out now with that fix.
