### ISSUE TITLE
[4.x]: Cloned block does not have enable option on the cog + after saving the page, disabled block gets enabled

### ISSUE THREAD

**Issue by azad6026** [craftcms/cms#11802]
### Description

I have encountered this issue today in a Craft CMs 4 project. 
Simple explanation for issues:
1. If you clone an enabled block or even copy and paste it in the page, there is no way to enable it again within the cog.
2. If you save the page, the disabled block(or any other disabled block) get enabled. (This is a temporary way I could enable the block from the item 1, but this is not the correct way).

### Steps to reproduce

1. Clone a block or copy and paste it within the page
2. The block will be disabled once cloned. Now try the cog for the block and you see no option to enable it. 
3. If you save the page, block gets enabled afterwards.

### Expected behavior

1. Clone a block or copy and paste it within the page
2. The block will be disabled once cloned. If you try the cog , there should be the enable button to enable it.
3. If you save the page, there should not be any change in blocks status (enable / disable status). If it is disabled, it has to remain disabled

### Actual behavior

1. Clone a block or copy and paste it within the page
2. The block will be disabled once cloned. If you try the cog , there is no option to enable it.
3. If you save the page, blocks status (enable / disable status) all changes to enabled even if they are disabled.

**Note: No matter how you create a block , if you disable them, once you save the page, they get enabled.**

### Craft CMS version

4.2.1.1

### PHP version

8.1

### Database type and version

mysql 5.7.34

**Comment by brandonkelly** [comment]
Craft doesn’t have the ability to duplicate a block in core, so that must be provided by a plugin – maybe [Smith](https://plugins.craftcms.com/smith?craft4)?

**Comment by azad6026** [comment]
Thank you for the tip. We use Neo in our end. So I think we need to report it there. We can close this one then and I will report this one on Neo plugin.
