### ISSUE TITLE
[4.x]: User content is not getting saved through slideout

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#11810]
### Description
When trying to edit User data in the backend through a slideout, the content isn't getting saved altough I do get a success message.

I do see some js errors in the console:

1. When opening the slideout:
`Uncaught TypeError: s is undefined => AddressesInput.js:50:22`

2. When saving the slideout:
`Uncaught TypeError: this.$container.data(...) is undefined => cp.js:2:250777`

### Steps to reproduce

1. try to edit a user though a slideout
2. edited content is not getting saved

### Expected behavior
edited data should be getting saved

### Craft CMS version

4.2.1.1

### PHP version

8.1

### Operating system and version

ubuntu 20

### Database type and version

MySQL 8.0.27

**Comment by brandonkelly** [comment]
Thanks for reporting that! Was able to reproduce for users with existing addresses. Fixed now for the next release.

**Comment by brandonkelly** [comment]
Craft 4.2.2 is out now with that fix.
