### ISSUE TITLE
[3.x]: Missing user permission to publish live changes for assets

### ISSUE THREAD

**Issue by chrismlusk** [craftcms/cms#11818]
### Description

I have an asset volume with a few fields included in the field layout. I want to update a certain user group to permit those users to edit the fields on assets in this volume, but the client does not want these users to be able to create/delete files.

I tried the following settings:

<img width="365" alt="Screen Shot 2022-08-23 at 12 19 47" src="https://user-images.githubusercontent.com/5922913/186223837-f87513fa-a965-4e28-aadb-d4352565044a.png">

However, when I test it, I can load an asset's edit route, but the fields are all disabled and there is no "Save" button.

This particular user group has a similar permission setup for certain sections (they can only edit existing entries), and that works no problem. I notice the available permissions are slightly different though, particularly the "Publish live changes" option. Could that be a clue?

<img width="408" alt="Screen Shot 2022-08-23 at 12 28 02" src="https://user-images.githubusercontent.com/5922913/186225517-3c920aa0-7b51-4612-a08d-9bdd51d081ef.png">

### Craft CMS version

3.7.51

**Comment by brandonkelly** [comment]
Craft 3.7.53 is out with that fix. Thanks for reporting!
