### ISSUE TITLE
[4.x]: CpSlideout Errors not handled

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#11812]
### Description

Returning `return $this->asModelFailure($form);` from a Controller method when submitted via a CPSlideOut throws an error.

This is because the `submit()` method calls `this.handleSubmitError();` without a parameter.

https://github.com/craftcms/cms/blob/develop/src/web/assets/cp/src/js/CpScreenSlideout.js#L484

<img width="1295" alt="Screen Shot 2022-08-23 at 7 12 21 am" src="https://user-images.githubusercontent.com/25124/186020003-3cf1e464-7599-4afe-afea-d704f6fcc6e6.png">

<img width="931" alt="Screen Shot 2022-08-23 at 7 14 30 am" src="https://user-images.githubusercontent.com/25124/186020494-576376bf-bc38-493c-ad4c-2d3ed2ecd60b.png">

### Steps to reproduce

1. Create a controller with a simple Form
2. Load the controller in a CPScreenSlideout
3. Submit the form with validation errors
4. return `$this->asModelFailure()` from the controller method

### Expected behavior

Form should be updated with errors

### Actual behavior

Throws console error

### Craft CMS version

Craft CMS 4.2.1.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release.

**Comment by brandonkelly** [comment]
4.2.2 is out now with that fix.
