### ISSUE TITLE
[3.x]: Paginate PageInfo encoded URLs are unencoded

### ISSUE THREAD

**Issue by jamiepittock** [craftcms/cms#11827]
### What happened?

We noticed if we have URLs such as `https://my.domain/page?monkey%5B%5D=3`, Craft's paginator unencodes them so paginated page urls look like `https://my.domain/page?monkey[0]=3`

You can reproduce it by building a url with the same query string as the current request.

    {# current request is 'https://my.domain/page?monkey%5B%5D=3' #}
    {{ url(craft.app.request.absoluteUrl, craft.app.request.getQueryStringWithoutPath()) }}
    {# outputs 'https://my.domain/page?monkey[0]=3 #}

The request is still handled correctly, but our cache is treating them as two different urls and therefore caching them separately. 

### Craft CMS version

3.7.51

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Alright, will go ahead and close this.
