### ISSUE TITLE
[4.x]: Cannot reorder selected categories from a category field

### ISSUE THREAD

**Issue by philipboomy** [craftcms/cms#11828]
### Description
After selecting categories in a category field I cannot change the order. It's possible with the entry field.

### Craft CMS version

4.2.1.1

### PHP version

8.0

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
This is currently working as intended, since Categories fields will preserve the order and hierarchy defined by the category group. See #8748 for a feature request to make that optional, and we are reviewing a pull request that will make it possible for Craft 4.3 (#11749).
