### ISSUE TITLE
[3.x]:  Issues with hosting with firewall

### ISSUE THREAD

**Issue by teachmeter** [craftcms/cms#11831]
### Description
Recently we've installed our craft 3 project on an Isolated hosting with very strict firewall rules.
We've tried to step by step debug a lot of issues with cookies, sessions, connections made in the backend but we are still encountering such issues.
Especially the problems are connected to CSRF feature enabled (can't login to admin, always results in 400 response and the token being invalid)
And in the backend in random places we get an error like 

```
BaseElementIndex.js:2121 Uncaught TypeError: Craft.appendFootHtml is not a function
    at s.constructor._createTriggers (BaseElementIndex.js:2121:13)
    at s.constructor.showActionTriggers (BaseElementIndex.js:811:14)
    at s.constructor.updateActionTriggers (BaseElementIndex.js:946:16)
    at s.constructor._handleSelectionChange (BaseElementIndex.js:1668:12)
    at s.constructor.onSelectionChange (BaseElementIndexView.js:345:21)
    at s.constructor.<anonymous> (Select.js:822:25)
```

My question is is there any kind of guide that would allow us to properly set everything in the firewall security rules or what can cause the beforementioned JS errors?

### Craft CMS version

Craft Pro 3.7.51

### PHP version

8.0.13

### Operating system and version

Linux 4.18.0-348.el8.x86_64

### Database type and version

MySQL 5.5.5

### Image driver and version

GD 8.0.13

### Installed plugins and versions

Blitz: 3.12.6
Field Manager: 2.2.5
Imager X: v3.6.2
Navigation: 1.4.28
Redactor: 2.10.10
Redactor Custom Styles: 3.0.4
Retcon: 2.4.3
SEO: dev-develop
Super Table: 2.7.2
Tags: 1.0.9
Typed link field: 1.0.25

**Comment by angrybrad** [comment]
@teachmeter having a hard time picturing how firewall rules might cause CSRF issues. Usually, when you see CSRF issues, it's a load-balancing problem. Is this a load-balanced environment?

**Comment by teachmeter** [comment]
I think it is.
Would you have a general list or sth what needs to be open and allowed for such and loadbalancer/firewall stack to be enabled?

It can be also some source code i can look into to forward it to that Firewall administrator.

**Comment by angrybrad** [comment]
@teachmeter give this a whirl: https://craftcms.com/knowledge-base/configuring-load-balanced-environments

Usually with CSRF and load balanced environments, it's PHP session related.

**Comment by teachmeter** [comment]
Thanks i will look into that and close this issue
