### ISSUE TITLE
[plugin store]: changelog not loading

### ISSUE THREAD

**Issue by nettum** [craftcms/cms#11856]
### Description
The changelog gives http 500 on https://plugins.craftcms.com/ (both ajax call and full page load). Same if you try to access the changelog for a plugin from an craft installation.

### Steps to reproduce

1. Go to changelog tab for a plugin on the plugin store (https://plugins.craftcms.com/commerce/changelog?craft4)

### Expected behavior
Should see changelog

### Actual behavior
Page / ajax call gives http 500.

### Craft CMS version

3.x

**Comment by brandonkelly** [comment]
Doh, thanks for reporting that! Fixed now.
