### ISSUE TITLE
[3.x]: last matrix block is not being deleted 

### ISSUE THREAD

**Issue by clarisse-catacutan** [craftcms/cms#11851]
### Description
We have a Matrix with multiple types that are all category fields and can be edited on the frontend. When there are multiple types that are populated and we empty one, it gets deleted. But if we empty the last matrix block, it's not being deleted. It keeps all the field values too. 

### Steps to reproduce
1. Create a form with checkbox to be able to empty your Matrix fields.
2. Try to empty one matrix block (it will remove the block).
3. Try to empty the last remaining block (it will retain its values and block).

### Expected behavior
It should empty the Matrix field instead of keeping the last remaining Matrix and its values.

Couldn't find any answers on stackoverflow so I'll try my luck here.

### Craft CMS version

3.7.52

### Installed plugins and versions

-

**Comment by clarisse-catacutan** [comment]
I've figured out that it's because of the [sortOrder] array:

```twig
{% for blockId in clone(channelPicker).anyStatus().ids() %}
      {{ hiddenInput('fields[channelsPicker][sortOrder][]', blockId) }}
 {% endfor %}
```

But if I add an if statement in the for loop, it doesn't retain the matrix block.

```twig
{% for blockId in clone(channelPicker).anyStatus().ids() if blockId != cityBlock.id %}
      {{ hiddenInput('fields[channelsPicker][sortOrder][]', blockId) }}
 {% endfor %}
```

My expected behavior is that it should retain the matrix block when the users add values to the fields, but delete the block when it's empty.

**Comment by brianjhanson** [comment]
[Here are the docs for saving matrix fields](https://craftcms.com/docs/4.x/matrix-fields.html#saving-matrix-fields). 

> `sortOrder` should be submitted as an array of all the block IDs you wish to persist (as well as any new block IDs), in the order they should be saved.

So this is working as expected. 

If you'd like a block to be deleted you'll need to remove it from the `sortOder` input, if you'd like it to be retained, you'll need to keep it in there. 

One other thing to note: 
> Outputting form fields for existing blocks is completely optional. As long as the block IDs are listed in the `sortOrder` array, they will persist even if they are missing from the form data.
