### ISSUE TITLE
[3.x]: Craft does not serve custom error templates for 50x error codes when the database is empty or does not exist

### ISSUE THREAD

**Issue by aaronbushnell** [craftcms/cms#11855]
### Description

When Craft is unable to make a connection to the database or the database contents are emptied/being imported from scratch (causing a 500/503 error) the custom error templates are not rendered.

When using a hosting provider with the ability to restore a database backup (Servd is one such host) the database is emptied and then the backup is imported to take its place. 

During this time, even with a `500.twig`, `503.twig`, `offline.twig`, and `error.twig` none of these templates will be shown during this process. Instead you receive (what seems to be) Yii's general error message:

> An internal server error occurred.

### Steps to reproduce

1. Create an `error.twig` template
2. Set invalid database credentials
3. Disable dev mode
4. Visit site and see that the `error.twig` template is not rendered

### Expected behavior

The `error.twig` template should display

### Actual behavior

A general "An internal server error occurred." is shown

### Craft CMS version

3.7.x (and 4.x)

### PHP version

8.0.22

### Operating system and version

Darwin 21.6.0

### Database type and version

MySQL 5.7.38

### Image driver and version

GD 8.0.22

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
This should be fixed for the next release! (#11859)

**Comment by aaronbushnell** [comment]
Thank you, @brianjhanson and @brandonkelly!

**Comment by brandonkelly** [comment]
Craft 3.7.54 and 4.2.4 are now tagged with that fix.
