### ISSUE TITLE
[4.x]: Wrong field layout for preview if changing entry types and opening preview before provisional draft is done saving

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#11858]
### Description

After changing an entry's entry type, if the author opens preview _while the provisional draft_ is still saving, the preview pane will use the previously active entry type's field layout. Also in such cases the following behavior happens:

- Editing the fields inside preview will not trigger an iframe refresh
- Any and all edits inside preview are not saved, and lost when preview is closed

There are no JS errors in the console.

_Possibly the easiest fix is disabling the preview button whenever a provisional draft is currently being saved or applied?_

### Steps to reproduce

1. Create a section with two different entry types 
2. Edit an entry in that section
3. Change the entry's entry type
4. While the provisional draft is saving the entry type change (i.e. the spinner is visible); click the Preview button

### Expected behavior

The preview should use the field layout for the entry type the author just switched to, and editing fields inside preview should trigger auto-saves and iframe refresh as normal.

### Actual behavior

The preview uses the field layout for the previously active type, because preview was opened before the provisional draft had a chance to save the new type ID. Auto-save and -refresh doesn't work.

### Craft CMS version

4.2.3

### Installed plugins and versions

- None

**Comment by brianjhanson** [comment]
Thanks for reporting! A fix for this has been merged for 4.3 🎉

**Comment by brandonkelly** [comment]
Craft 4.3 was released earlier this week with this fix.
