### ISSUE TITLE
Add impersonation user permission

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1186]
> Created by: Anonymous (gijs@itmundi.nl) on 2015/03/16 11:59:50 +0000
> Votes at time of UserVoice import: 2

-----------------------------------

Currently only super admins are able to use impersonate, but its also useful to other users.

**Comment by webburo-spring** [comment]
Seems not added in Craft 3. Is it still a feature request?

**Comment by brandonkelly** [comment]
Yeah we haven’t added this yet. Would be open to a PR if you really need it soon though.

**Comment by brandonkelly** [comment]
Closing this in favor of #3501.
