### ISSUE TITLE
[4.2.3]: Use of ‘<tag>’ syntax in field name breaks field config UI

### ISSUE THREAD

**Issue by watershed** [craftcms/cms#11861]
### Steps to reproduce

1. I had a couple of fields with SEO oriented `name` values of **SEO <title> text** and **Add <title> suffix**
    - (Initially they were **SEO `<title>` text** and **Add `<title>` suffix** but then I realised that Markdown syntax is inactive in a field’s `name` field.)
3. Their respective field `handle`s were `seoTitle` and `seoSuffix`

### Expected behavior

Nothing. They’re just field name strings.

### Actual behavior

- I could no longer edit the configuration of a Matrix field lower down the `Settings > Fields` list.
- I could view the field and its list of block types but the definitions of the first block type in the list was not present.
- And clicking on a block type **cog** icon would do nothing – no block type `name|handle` popup layer would appear.

### Sit and stew

- Tear hair out for a bit (if you have any)
- Then realise the  presence of `<` and `>` might be an issue.

### Rejoice

Removing those characters means I can edit my Matrix fields again :)

### Craft CMS version

4.2.3

### Installed plugins and versions

-

**Comment by watershed** [comment]
I can quite imagine that entering code characters in a field `name` is a no-no, so this may be regarded as a feature rather than a bug. Which would be fine by me, but I’ve recorded it here in case it trips up anyone else.

**Comment by brianjhanson** [comment]
I'm having trouble replicating this one. Could you send your `composer.json` and `composer.lock` files, along with a
database backup to [support@craftcms.com](mailto:support@craftcms.com)? If you have any custom modules, those files would also be helpful in tracking this down.

**Comment by brandonkelly** [comment]
Can’t reproduce either.

**Comment by brandonkelly** [comment]
After looking into this further, I was able to reproduce in another context. Should be fixed now for the next release. (5d0ea5b598f6fb319b5290fe472b2525dd63e08c)

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 4.2.3"` and run `composer update`.

**Comment by watershed** [comment]
Sorry for the non-response the last few days. Thanks for finding and fixing Brandon.
