### ISSUE TITLE
[4.x]: View button on private assets

### ISSUE THREAD

**Issue by okolvik-avento** [craftcms/cms#11860]
### Description
The view button should not be shown (404), or should have a cp-link, on assets that have no public url.
https://github.com/craftcms/cms/blob/89a8762b7a9f4809b504db2d797b74d1d7b38284/src/elements/Asset.php#L1077

### Craft CMS version

4.2.3

### PHP version

8.0

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! We’ve fixed this for the next release.

**Comment by brandonkelly** [comment]
Craft 4.2.4 is tagged with that fix.
