### ISSUE TITLE
[4.x]: Assets index does not refresh elements or display queued prompts, if the last file fails to upload

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#11866]
### Description

When uploading multiple files to assets, if the _last_ file uploaded fails to save, the asset index will not refresh the elements after the upload completes – even if there were files prior to it that uploaded successfully.

This is disorienting to the user, as it gives the impression that _none_ of the files were successfully uploaded.

Additionally, if there are any queued prompts (i.e. for resolving name conflicts with successfully uploaded files prior to the last one), those prompts will not appear.

_Here's a screen capture demonstrating the issue:_

https://user-images.githubusercontent.com/298510/188011302-71d7a529-7a62-494c-b24c-71b4ae0b76ac.mp4

I'm pretty sure that the reason for this behavior is that the Craft uploader will only trigger its `fileuploaddone` event for _successful_ uploads. This means that if the _last_ upload fails, [the below logic in the AssetIndex JS class](https://github.com/craftcms/cms/blob/develop/src/web/assets/cp/src/js/AssetIndex.js#L974) will never run (snippet below is edited for brevity): 

```js
_onUploadComplete: function (event, data) {
    
    ...

    // For the last file, display prompts, if any. If not - just update the element view.
    if (this.uploader.isLastUpload()) {
      this.progressBar.hideProgressBar();
      this.setIndexAvailable();

      if (this.promptHandler.getPromptCount()) {
        this.promptHandler.showBatchPrompts(this._uploadFollowup.bind(this));
      } else {
        this._updateAfterUpload();
      }
    }
  },
```

### Steps to reproduce

1. Upload multiple files via the asset index, making sure the very last one causes some kind of server side error. 

This can either be a validation error (Craft doesn't validate assets on upload, but plugins or modules might set an error on the model in an `Asset::EVENT_BEFORE_VALIDATE` event handler or the like – which is what I'm doing in the above screen capture), or a bona fide exception of some kind.

2. Close the JavaScript `alert()` that appears when the last uploaded file fails to upload.

3. Confirm that the asset index does not refresh its elements or display any queued prompts after closing the alert, even if there were successfully uploaded files in the set.

### Expected behavior

The asset index should always refresh elements and display queued prompts, if at least 1 file is successfully uploaded, regardless of whether some of the uploads failed.

### Actual behavior

If the last file being uploaded fails to upload, the asset index doesn't refresh the elements or display queued prompts – even if there were files that uploaded successfully prior to it.

### Craft CMS version

4.2.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release.

**Comment by mmikkel** [comment]
Awesome! Thanks a lot.

**Comment by brandonkelly** [comment]
Craft 3.7.54 and 4.2.4 are now tagged with that fix.
