### ISSUE TITLE
[3.x]: Transient CSRF invalid token errors on POST requests

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/cms#11878]
### Description

We are seeing random CSRF related errors on requests that send data to controllers or form submit action requests i.e. Sprout Forms. We do have CSRF protection enabled but the issue is these errors are not constant and only happen sometimes from random clients. There is no correlation between devices from what I can tell. I cannot reliably replicate a CSRF invalid condition myself from my own testing with previous examples of when one was triggered.

Here's is an example CSRF related error that has triggered a 400 bad request error.

https://sentry.io/share/issue/a2b9408ff3974d7e9ab616ccf2590c24/

All forms performing POST actions have `{{ csrfInput() }}`, I have looked through the template code and cannot see anywhere where the CSRF token is being cached.

It suggests it's related to the CSRF token as the condition in the stack trace has highlighted that likely `$this->request->validateCsrfToken()` was false.

```php
 if ($this->enableCsrfValidation && Yii::$app->getErrorHandler()->exception === null && !$this->request->validateCsrfToken()) {
    throw new BadRequestHttpException(Yii::t('yii', 'Unable to verify your data submission.'));
}
```

### Steps to reproduce

1. I cannot reliably reproduce this error, but can see the events tracked by Sentry, showing it is happening.

### Expected behaviour

POST actions to not throw a 400 error.

### Actual behaviour

Random instances of 400 bad request errors related to POST actions, but not consistently happening for all requests.

### Craft CMS version

3.7.53

### PHP version

8.0

### Operating system and version

Ubuntu 20.04 LTS (WSL 2)

### Database type and version

MySQL 8

### Image driver and version

N/A

**Comment by brandonkelly** [comment]
There are a couple reasons why CSRF tokens may become invalidated:

- The user agent string changes
- It’s a load-balanced environment, and the servers are not properly configured to share the same PHP session storage. (See the [PHP Sessions](https://craftcms.com/knowledge-base/configuring-load-balanced-environments#php-sessions) section of our [Configuring Craft for Load-Balanced Environments](https://craftcms.com/knowledge-base/configuring-load-balanced-environments#php-sessions) KB article.)

Take a look into those (particularly the latter). If you’re still having trouble, please contact support@craftcms.com and we can try to help from there.
