### ISSUE TITLE
[4.x]: Assets - Image - Focal point can NOT be adjusted after saving new asset

### ISSUE THREAD

**Issue by gliving-pw** [craftcms/cms#11875]
### Steps to reproduce

1. Go to Assets and Edit an Image
2. Click focal point
3. Click crop
4. Crop image so focal point is outside cropped area
5. Hit "Save as New Asset" (works if you just hit save)
6. You're no longer able to move focal point

### Expected behavior
You should be able to move focal point

### Actual behavior
You cannot move focal point

### Craft CMS version

Craft Pro 4.2.2

### PHP version

8.0.20

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting! That’s now fixed for the next Craft 3 and 4 releases.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 4.2.3"` and run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.7.54 and 4.2.4 are now tagged with that fix.
