### ISSUE TITLE
[4.x]: Wrong lastname after saving an address

### ISSUE THREAD

**Issue by billmn** [craftcms/cms#11871]
### Description
If in the `fullName` field of an address I enter "Luca Dal Dosso" and this was saved in database with:

- firstName: Luca
- lastName: Dosso

So, in the CP or using the `|address` filter the wrong full name is shown: **"Luca Dosso"**

This is wrong, as the firstname is "Luca" and the lastname is "Dal Dosso".
In Italy it is quite common to have lastnames with a prefix (eg Dal Borgo, De Battisti, Di Riesto, ...).

In other cases (eg "Di Riesto") the lastname is saved as "di Riesto" while the correct one is "Di Riesto" (capital initial).

### Steps to reproduce

1. Create a news Address using the "Luca Dal Dosso" as Full Name

### Expected behavior
With the full name "Luca Dal Dosso" I expect the lastname to be "Dal Dosso" and not "Dosso"
With the full name "Luca Di Riesto" I expect the lastname to be "Di Riesto" and not "di Riesto"

### Craft CMS version

4.2.3

### PHP version

8.0.21

### Operating system and version

macOS 12.5.1

### Database type and version

MariaDB 15.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Ultimately these should probably be fixed in the name parsing library ([theiconic/name-parser](https://github.com/theiconic/name-parser)), however I’ve just worked around the bug for Carft 4.3, by replacing “given name + family name” in generated address formats with the full name exactly as originally entered from the address.

**Comment by brandonkelly** [comment]
We’ve also just addded new `extraLastNamePrefixes`, `extraNameSalutations`, and `extraNameSuffixes` config settings for Craft 4.3, which can be used to add support for the `Dal` last name prefix, so the `lastName` property gets set to `dal Dosso`. (There’s still the casing bug, but I don’t think that’s something we’ll be able to fix on our end.)

```php
->extraLastNamePrefixes(['Dal'])
```

**Comment by billmn** [comment]
Great news, can't wait to try it with 4.3 🚀

Thank you!

**Comment by brandonkelly** [comment]
Went ahead and avoided the original PR (#11893) since it was hacky and the name parser config settings should make it possible to fully eliminate any undesired default behavior.
