### ISSUE TITLE
[4.x]: Unable to middle click / cmd+click the "new entry" button anymore

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#11870]
### Description
I used to be able to middle click / cmd+click the "New entry" button to create multiple new entries at once, then ctrl+tab through them all. It looks like this button behaviour has been re-written and it now shows a small loading indicator when you click it instead of working immediately. Please consider changing this back to how it worked before.

### Steps to reproduce

1. Middle click the New entry button

### Expected behavior
A new tab should open with the New Entry page.

### Actual behavior
The current tab changes to the new entry page, and no longer opens a new tab

### Craft CMS version

4.2.3

### PHP version

8.1.7

### Operating system and version

MacOS 12.5.1

### Database type and version

MySQL 8

### Installed plugins and versions

- None

**Comment by brandonkelly** [comment]
Just brought back support for <kbd>Ctrl</kbd>/<kbd>Command</kbd>/middle-clicking on **New entry** and **New category** buttons, for the next release.

**Comment by brandonkelly** [comment]
Craft 4.2.4 is tagged with that change!

**Comment by darylknight** [comment]
Awesome, thank you :)
