### ISSUE TITLE
[3.x]: Unable to transform GIF to animated WebP

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/cms#11889]
### Description

Currently I'm trying to transform an animated GIF to an animated WebP through Craft, however I'm unable to get this to work with both the latest Craft 3 and the latest Craft 4. The WebP rendered only contains the first frame.

Converting GIF to WebP manually via the ImageMagick CLI command `convert WT-circle-animation-2.gif WT-circle-animation-2.webp`  can successfully produce animated WebP's with the expected lower file size (See: https://webtraders.nl/upload/images/WT-circle-animation-2.webp).

### Steps to reproduce

1. Get a sample GIF image (You can use mine: https://webtraders.nl/upload/images/WT-circle-animation-2.gif)
2. Upload it to Craft
3. Select the image to be displayed on a page
4. Apply a transform with `webp` as format

### Expected behavior

To render animated WebP images.

### Actual behavior

Static WebP images based on the first frame.

### Craft CMS version

3.7.43

### PHP version

8.0.20

### Operating system and version

Custom Docker image based on php:8.0-fpm-alpine3.15

### Database type and version

MySQL 8.0.28

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-16)

`convert -version` dump:
```
Version: ImageMagick 7.1.0-16 Q16-HDRI x86_64 2021-11-21 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules 
Delegates (built-in): bzlib cairo fontconfig freetype gslib heic jng jpeg lcms ltdl lzma png ps rsvg tiff webp x xml zlib
Compiler: gcc (10.3)
```

### Related

https://github.com/craftcms/cms/issues/7544

**Comment by brandonkelly** [comment]
Thanks for reporting! That’s been fixed for the next Craft 3 and 4 releases, via #11920.

**Comment by brandonkelly** [comment]
Craft 3.7.54 and 4.2.4 are now tagged with that fix.

**Comment by Wiejeben** [comment]
Thanks for the update! We are seeing that the transforms are being generated incorrectly:

Source: https://webtraders.nl/upload/images/WT-circle-animation-3.gif

GraphQL output:
```json
[
	{
		"title": "WT circle animation 3",
		"url": "https://webtraders.nl/upload/images/_multipleImagesLarge/44668/WT-circle-animation-3.webp",
		"focalPoint": [
			0.5,
			0.5
		],
		"mimeType": "image/gif",
		"srcset": "https://webtraders.nl/upload/images/_multipleImagesLarge/44668/WT-circle-animation-3.webp, https://webtraders.nl/upload/images/_1296x1296_fit_center-center_82_none/44668/WT-circle-animation-3.webp 2x"
	},
	{
		"title": "WT circle animation 3",
		"url": "https://webtraders.nl/upload/images/_multipleImagesMedium/44668/WT-circle-animation-3.webp",
		"focalPoint": [
			0.5,
			0.5
		],
		"mimeType": "image/gif",
		"srcset": "https://webtraders.nl/upload/images/_multipleImagesMedium/44668/WT-circle-animation-3.webp, https://webtraders.nl/upload/images/_644x644_fit_center-center_none/44668/WT-circle-animation-3.webp 2x"
	},
	{
		"title": "WT circle animation 3",
		"url": "https://webtraders.nl/upload/images/_multipleImagesSmall/44668/WT-circle-animation-3.webp",
		"focalPoint": [
			0.5,
			0.5
		],
		"mimeType": "image/gif",
		"srcset": "https://webtraders.nl/upload/images/_multipleImagesSmall/44668/WT-circle-animation-3.webp, https://webtraders.nl/upload/images/_504x504_fit_center-center_82_none/44668/WT-circle-animation-3.webp 2x"
	}
]
```

The incorrect mimeType is still an issue from https://github.com/craftcms/cms/issues/10126.

**Comment by brandonkelly** [comment]
> The incorrect mimeType is still an issue from #10126.

@Wiejeben Did you see Andris’ reply about that?

> 1. The `mimeType` returned is for the original asset and is not even supposed to change to a different value for transforms. Same goes for the `size` field. Related: #8993

**Comment by brandonkelly** [comment]
Craft 3.7.55 and 4.2.5 are out with an additional fix for animated WebP images.
