### ISSUE TITLE
Set users permission to user groups

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1188]
> Created by: Mohammed Alshehri (m@dralshehri.com) on 2015/04/30 12:45:12 +0000
> Votes at time of UserVoice import: 2

-----------------------------------

Wouldn't be nice to be able to allow the user to edit other users and assign them to groups that he has permission to?

Case: Let's assume that we have three user groups; first, second and third. We have a superuser and admin. The admin gave the superuser all users permissions but gave him permission to only first and second groups. Then the superuser can register and edit users and assign them permission and user groups but within groups he has permission to.

I attached a proposed permission structure,
where assigning groups is separated from assigning permissions,
and user groups permissions added.

**Comment by Emkaytoo** [comment]
I'd appreciate a feature like this as well. In my head it worked like this: the entry itself was owned by a group and not an individual user, and as long as I'm a member of that group, I can access and edit the entry based on the permissions the group has.

I could be a member of multiple groups and edit content belonging to multiple groups, and any workflows that kick off would be related to that group. 

By having a role hierarchy within the group permissions, one could set up workflows for editing and publishing.

**Comment by brandonkelly** [comment]
Craft 2.6.2996 added specific permissions for assigning each individual user group, which I think is the right approach.
