### ISSUE TITLE
[4.2.3]: Entry filters don't work after switching sources

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#11880]
### Description

After switching sources in the entries list, the dropdown to add filters to the current view doesn't work properly. Clicking on any field in the filter dropdown doesn't do anything. No error appears in the JS console. The following screen recording demonstrates the issue:

https://user-images.githubusercontent.com/10146880/188459175-6287f6ce-fd47-42f0-b64f-2c2f0ca45709.mov

I'm not completely sure if switching sources is the thing causing this issue, I've experienced it a couple of times. But by switching between custom sources I can reliably reproduce it.

### Steps to reproduce

1. Open the entries list.
2. Switch between one custom source to another one.
3. Open the filters popup and try to add a filter through the dropdown.

### Expected behavior

The filters should be added normally.

### Actual behavior

No filter is added and there's no visual feedback that something happened at all, and also no error message.

### Craft CMS version

4.2.3

### PHP version

8.1

### Database type and version

MySQL 8

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by MoritzLost** [comment]
@brandonkelly Thanks! 🚀

**Comment by brandonkelly** [comment]
Craft 4.2.4 is tagged with that fix.
