### ISSUE TITLE
Allow multiple URL formats per Entry Type (Entries, Categories)

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#1189]
> Created by: Timothy Kelty (timkelty@gmail.com) on 2015/04/02 12:33:05 +0000
> Votes at time of UserVoice import: 2

-----------------------------------

It can be desirable to have sections and category groups occupy multiple URL formats.

A common example of this is 2 sections that share the same category group.

- `section1/category1/category1-2`
- `section1/entry`
- `section2/category1/category1-2`
- `section1/entry`

The main reason for this feature request would be to handle the validation of the slugs/uris when saving entries. This is currently not possible if you want a URL structure like this.

An added bonus would be the {entry} and {category} variables populated on all the urls you defined, without having to pluck them out of the request.

Stack Exchange: http://craftcms.stackexchange.com/questions/16377/multiple-url-formats-per-element-type-entries-categories

**Comment by timkelty** [comment]
I think the UI for this would be pretty close what is already there for "Site Settings" when you create a Section.

Instead of just having a locked # of rows equal to your # of sites, you could add rows and create multiple URI formats.

**Comment by brandonkelly** [comment]
Entry URI Format fields accept full Twig templates, so while it won’t look super pretty, you could do something like:

```twig
{% if object.myCategoriesField.exists() %}uri/format/1{% else %}uri/format/2{% endif %}
```

Advantage of this is, you can put whatever you want in those conditions, so you can have special case URI formats based on anything you’d ever need.

**Comment by timkelty** [comment]
@brandonkelly twig conditionals cover the _conditional_ URI format, but I'm lobbying for _multiple_.

Example:
One might want to use a category group in more than one URI scheme:
- `/people/colors/blue/`
- `/food/colors/blue/`

In the example I want to use a single "Colors" category group, but it has more than one URI. To do this today I have to pick one as my "main" URI, and then use routes to make the rest work.

Another example for entries would be if you had multiple URI schemes representing a single entry:

- `/my-entry-uri`
- `/my-entry-uri/more-info`
or
- `/people/my-entry-slug`
- `/animals/my-entry-slug`

In this case I'd want to be able define the schemes in the section and have the route work and route variable defined.

**Comment by brandonkelly** [comment]
Ah gotcha. So elements would actually get multiple URLs.

Hm, I dunno… feel like Craft should only care about the canonical URL for elements (if any). If your element doesn’t have a single obvious canonical URL (like in your color category example), then just disable URLs for that section/category group, and set up the routes yourself.

For the `/my-entry-uri` vs `/my-entry-uri/more-info` example, the former would most likely still be considered your canonical URL, and the latter could be set up as a route.

**Comment by timkelty** [comment]
> For the /my-entry-uri vs /my-entry-uri/more-info example, the former would most likely still be considered your canonical URL, and the latter could be set up as a route.

Yeah that's not as good of an example.

I'm fine dealing with this myself with routes - honestly it sprung back into mind when I saw the v3 "Site Settings" and thought that was what I was picturing for the UI.
