### ISSUE TITLE
[3.x]: Entry query title "does not contain" with underscore in string

### ISSUE THREAD

**Issue by benjaminkohl** [craftcms/cms#11898]
### Description

I feel like this used to work but there is an entry query where we are trying to omit entries where the title contains `_CLEAN`. We set up the title parameter like so:

```
.title('not *_CLEAN*')
```

The query result is omitting all entries that have "CLEAN" so it is like the underscore doesn't matter. I even tried adding a whole bunch more underscores to that parameter string and it still omits all entries where "CLEAN" is in the title. To sanity check myself, I changed the string to "CLLEAN" and all the entries showed up again.

### Expected behavior

The underscore character should not be ignored.

### Actual behavior

It appears that the underscore is irrelevant and so are any other underscores added to that string.

### Craft CMS version

3.7.30.1, 3.7.53.1

### PHP version

7.3

### Operating system and version

Darwin 20.6.0

### Database type and version

MySQL 5.7.34

### Image driver and version

Imagick 3.4.4 (ImageMagick 6.9.6-2)

### Installed plugins and versions

Amazon S3	1.3.0
Cookies	1.1.15
CP Field Inspect	1.2.5
Craft Commerce	3.4.13
Imager X	v3.5.5
Inventory	2.1.1
Lab Reports	1.0.0
Linkit	1.1.12.1
Link Vault	3.2.0
Redactor	2.9.0
Relabel	2.0.2
Typogrify	1.1.18

**Comment by angrybrad** [comment]
Craft has always normalized search indexes and search query terms:

https://github.com/craftcms/cms/blob/develop/src/services/Search.php#L338

Part of that normalization process is removing punctuation:

https://github.com/craftcms/cms/blob/develop/src/helpers/Search.php#L54-L56

To which the underscore belongs:

https://github.com/craftcms/cms/blob/develop/src/helpers/Search.php#L147

Similar issues have been brought up before:

https://github.com/craftcms/cms/issues?q=is%3Aissue+search+normalize+keywords+is%3Aclosed

We have a long-standing FR to have the option to replace the core search provider from the native database-backed one to something like Algolia that I think is the ultimate fix for these:

https://github.com/craftcms/cms/discussions/8111

**Comment by angrybrad** [comment]
@benjaminkohl completely missed it was `.title()` and assumed it was `.search()` 🤦🏼 

my bad

**Comment by benjaminkohl** [comment]
Ah, okay. I already deployed an alternative "andWhere" condition to the queries involved but that's cool that the underscores won't be an issue if it comes up again. Thanks!

**Comment by brandonkelly** [comment]
That works too!

Craft 3.7.54 and 4.2.4 are now tagged with the fix.
