### ISSUE TITLE
[4.x]: URL fields always considered as modified

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#11908]
### Description

Fields of type URL are instantly considered as modified as soon as you update any field in the field layout.

### Steps to reproduce

1. Have an entry type with an URL field, and in my case multiple other URL fields, an assets field, Redactor field and a couple of text fields.
2. Open an existing entry of this type and make a change to trigger auto save.
3. See how all URL fields have the blue indicator.

### Craft CMS version

4.2.3

### PHP version

8.0.20

### Database type and version

MySQL 10.8.3

### Installed plugins and versions

- Redactor

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next Craft 3 and 4 releases.

**Comment by brandonkelly** [comment]
Craft 3.7.54 and 4.2.4 are now tagged with that fix.
