### ISSUE TITLE
[4.x]: Command-S opens save webpage dialog instead of saving entry if a menu button is focused

### ISSUE THREAD

**Issue by ttempleton** [craftcms/cms#11919]
### Description

When editing an entry and a menu button is focused, such as the ones for entry save options or changing sites/revisions, pressing command-S to save the entry instead opens the browser's save webpage dialog.

I was able to reproduce this on Craft 4.2.3 using Chrome 105.0.5195.102, Firefox 105.0b9, and Safari 15.6.1. On Craft 3.7 it works as expected.

### Steps to reproduce

1. Edit an entry
2. Click on the save options menu button
3. (Optionally) click somewhere else on the page to close the menu
4. Press Command-S

### Expected behavior

That the above steps would save the entry.

### Actual behavior

The above steps open the browser's save webpage dialog.

### Craft CMS version

4.2.3

### PHP version

8.1.10

### Operating system and version

macOS Monterey 12.5.1

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Thanks for reporting that! We just tagged Craft 4.2.4 with a fix for this.
