### ISSUE TITLE
[4.x]: `FieldLayout::createFromConfig()` ignores `type` param from config

### ISSUE THREAD

**Issue by michaelrog** [craftcms/cms#11929]
### What happened?

[FieldLayout::createFromConfig()](https://docs.craftcms.com/api/v4/craft-models-fieldlayout.html#method-createfromconfig) ignores the `type` property in the config argument, so I have to do some weird rigmarole to make sure the correct `type` is attached — Otherwise, my element's native fields won't be included...

For example, this _doesn't_ work:
```
$config = [
    'type' => Link::class,
    'tabs' => ...
];

$fieldLayout = FieldLayout::createFromConfig($config);

// $fieldLayout->type is null  :(
```

...but this does:

```
$tabsFromConfig = FieldLayout::createFromConfig($config)->getTabs();

$fieldLayout = new FieldLayout([
    'type' => Link::class,
]);
$fieldLayout->setTabs($tabsFromConfig);

// $fieldLayout->type is correct  :/
```

`EVENT_DEFINE_NATIVE_FIELDS` gets fired from inside of `setTabs()`, so the `type` needs to be in place _before_ `createFromConfig()` invokes `setTabs()`.

### Expected behavior —

This should work:

```
$config = [
    'type' => Link::class,
    'tabs' => ...
];
$fieldLayout = FieldLayout::createFromConfig($config)
```

### Actual behavior —

As currently implemented, `createFromConfig()` instantiates tabs using `$config['tabs']` and _ignores all other properties in the `$config`_.

### Craft CMS version

4.2.3

### PHP version

8.0.2

**Comment by brandonkelly** [comment]
Fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 4.2.4 is tagged with that fix.
