### ISSUE TITLE
[4.x]: 

### ISSUE THREAD

**Issue by djrees** [craftcms/cms#11930]
### Description

When using Safari or Chrome on macOS with a British keyboard layout, the password input on the main Craft CMS login screen has an unexpected behaviour when trying to enter a password with an '#' or '€' character. 

On a macOS with a British keyboard layout, the '#' character is created by typing 'alt+3' and '€' via 'alt+2'. However, when you press the alt key on the password input, it quickly reveals your plain text password.

If you're password contains one of these characters and you're entering your password quickly, pressing alt+3 can often replace the entire password with a single '#' or puts the '#' at the start of the password.

This does not happen in Firefox.

### Steps to reproduce

1. Goto the login page of a CraftCMS 3 or 4 instance
2. Type in the password: 'pass#word'. 
3. Get frustrated. 

### Expected behavior

The password field should not be using the alt key for password revealing the plain text version

### Actual behavior

Password field uses the alt key to reveal the password and causes issues whilst typing '#' or '€' on macOS British keyboard layout

### Craft CMS version

3 & 4

### Operating system and version

macOS 12.5.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
That’s a good point, thanks for reporting that! I just removed the <kbd>Alt</kbd> press behavior for the next Craft 3 and 4 releases.

**Comment by brandonkelly** [comment]
Craft 3.7.54 and 4.2.4 are now tagged with that change.

**Comment by djrees** [comment]
Thanks very much!
