### ISSUE TITLE
[4.x]: "View" button missing in asset edit pages for certain file types

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#11936]
### Description

For certain file types (for example videos and Word documents) the "View" button is missing from asset edit pages.

### Steps to reproduce

1. Create a volume linked to a filesystem with the "Files in this filesystem have public URLs" setting enabled. Set the "Transform Filesystem" to "Same as asset filesystem".
2. Upload an mp4 video file, and navigate to its edit page. Notice that the "View" button is missing from the top of the edit page.

### Expected behavior

The "View" button should always display for assets in filesystems with public URLs enabled.

### Actual behavior

The "View" button is only visible for certain filetypes, such as images and PDFs.

### Craft CMS version

4.2.3, 4.2.4

### PHP version

8.1.8

### Operating system and version

macOS 12.4

### Database type and version

10.8.3-MariaDB

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-29)

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Yeah looks like we never had a file type restriction for the “View” button in Craft 3. Not sure why I added it in Craft 4. Removed for the next release!

**Comment by brandonkelly** [comment]
Craft 4.2.5 is out with that fix.
