### ISSUE TITLE
[4.x]:  errors twig variable undefined even though errors are being generated

### ISSUE THREAD

**Issue by ul8** [craftcms/cms#11933]
### Description

I’ve run into an issue with twig and the built-in users controller - the errors variable is not defined in twig even though I can see (via xdebug) that errors are being generated in UsersController::actionSendPasswordResetEmail()

### Steps to reproduce

1.  Make sure that email sending does not work correctly so we can generate an error.
2. Paste the twig in this link https://craftcms.com/knowledge-base/front-end-user-accounts#reset-password-forms into a new template. Enter a user name and submit.

### Expected behavior

Error messages being rendered

### Actual behavior

No error messages shown, “error” variable in twig remains undefined.

Xdebug shows an error is caught (this is expected, the email setup is not working)
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/589744/190069736-d3793755-928f-4c13-b1e6-5e3146370f05.png">

### Craft CMS version

Craft Pro 4.2.1.1 (recently upgraded from 3.4)

### PHP version

PHP 8.1.10

### Operating system and version

Ubuntu 20.04

### Database type and version

Postgres 13

### Installed plugins and versions

<img width="709" alt="image" src="https://user-images.githubusercontent.com/589744/190069864-18b7bc4a-0663-4182-8b6a-aaeaac080c62.png">

**Comment by brandonkelly** [comment]
Do you have the [`preventUserEnumeration`](https://craftcms.com/docs/4.x/config/general.html#preventuserenumeration) config setting enabled? If so, errors will get logged but not shown in the response.

https://github.com/craftcms/cms/blob/d27e480afce05193d3ec253970b7807b011d752e/src/controllers/UsersController.php#L519-L525

**Comment by ul8** [comment]
@brandonkelly Thanks but no, that's not it. The setting is not enabled, and also the step debugger did move past that code block on to 
https://github.com/craftcms/cms/blob/d27e480afce05193d3ec253970b7807b011d752e/src/controllers/UsersController.php#L532

**Comment by brandonkelly** [comment]
Doh, the controller was just forgetting to pass the errors along to the template. Fixed now for the next release!

**Comment by ul8** [comment]
Great, thanks! This was picked up by our codeception test suite. Would never have found it otherwise :)

**Comment by brandonkelly** [comment]
Craft 4.2.5 is out with that fix. Thanks again!
