### ISSUE TITLE
[4.x]: Fluent DbConfig not working properly (inconsistent with previous behavior)

### ISSUE THREAD

**Issue by khamer** [craftcms/cms#11941]
### Description

The Fluent DbConfig isn't working properly - it seems to require more values or not use the screaming snake overrides properly.

### Steps to reproduce

1. config/db.php:
```php
return DbConfig::create()->driver('pgsql');
```
.env
```
CRAFT_DB_SERVER="something"
CRAFT_DB_DATABASE="something"
```

This will fail with an error showing that it didn't pick up the dbname or host, whereas if we change config/db.php to the older version:
```php
return [ 'driver' => 'pgsql' ];
```
It works fine.

[error-snippet.log](https://github.com/craftcms/cms/files/9569193/error-snippet.log)

### Craft CMS version

4.2.4

### PHP version

8.0.13

### Operating system and version

Debian 10

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.2.5 is out with that fix.
