### ISSUE TITLE
[4.x]: Slow page load times

### ISSUE THREAD

**Issue by hassanmah** [craftcms/cms#11943]
### Description
Page loads are over 1000ms, debug bar shows these large db queries on every page. 

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/3025707/190270629-bd656d89-1cd1-43de-898c-fa95c8532aa0.png">
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/3025707/190270670-489a11a9-2f69-4683-b5ed-7e44893fecae.png">
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/3025707/190270693-d8671a36-a1bd-46e8-b6b1-40f266702f7d.png">

### Craft CMS version

4.2.4

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
As a starting point, try running the following command:

```sh
php craft db/convert-charset
```

That will ensure that each of your database tables are using the same charset. If that wasn’t already the case, it has a significant effect on performance.

If you’re still having issues after that, please write into support@craftcms.com with a database backup and your Composer files, and we can help look into it from there.
