### ISSUE TITLE
[4.x]: Dynamic subfolders are said to be missing when updating asset indexes

### ISSUE THREAD

**Issue by jammid** [craftcms/cms#11949]
### Description
We are using dynamic subfolders with our S3 bucket in Craft.
When we update the asset indexes crafts gives a prompt saying those folders are missing when they're not.

### Steps to reproduce

1. Create an asset field that uses an asset volume with a S3 filesystem.
2. Make the asset location dynamic e.g. {slug}
3. Upload an asset using the asset field
4. Update the asset indexes for the asset volume

### Expected behavior

Asset indexes are updated successfully and dynamic folders are found.

### Actual behavior

Craft gives a prompt saying the dynamic folders are missing

### Craft CMS version

4.2.4

### PHP version

8.1.9

### Operating system and version

Linux 4.19.0-21-cloud-amd64

### Database type and version

MySQL 10.4.25

### Image driver and version

GD 8.1.9

### Installed plugins and versions

- Amazon S3
- Control Panel CSS
- Expanded Singles
- Feed Me
- Field Manager
- Redactor

**Comment by brandonkelly** [comment]
You shouldn’t ever have to update asset indexes to pull in folders/files that were created by Assets fields in the same Craft install. 

When you upload new files to your Assets field, are they showing up anywhere within the Assets index page – without going through the Asset Indexes utility?

**Comment by jammid** [comment]
Yes, when the files are uploaded they show up in the assets page as expected.

Those were just the steps to reproduce the issue.

I thought it was possible to update the data indexes and delete assets from the index, that are actually missing in the bucket - without deleting the dynamic subfolders from the index as well. As it is now I have to manually deselect them, even though they aren't actually missing.

**Comment by brandonkelly** [comment]
Can you show a screenshot of the indexer when it says they’re missing?

**Comment by jammid** [comment]
Sure. Here is a screenshot where one file is missing from the bucket but the folder is not.

![missing-folder](https://user-images.githubusercontent.com/1822023/190616353-7ff44051-60df-4bcd-8253-bfcd4346f993.jpg)

Asset location

![field](https://user-images.githubusercontent.com/1822023/190616979-98f4f500-b796-4f0a-a7ee-e00d6f7bb5c9.jpg)

Slug

![slug](https://user-images.githubusercontent.com/1822023/190617085-8c9d2bf5-c52a-40b1-b2a0-833c2022d308.jpg)

Bucket

![bucket](https://user-images.githubusercontent.com/1822023/190617149-e30d0b77-5c81-43c5-9312-67c8f8785391.jpg)

**Comment by brandonkelly** [comment]
Are there any files within `not-missing-folder/` on S3?

**Comment by jammid** [comment]
Yes. Here is the folder contents

![folder-content](https://user-images.githubusercontent.com/1822023/190652044-6dbc00b2-21a4-4f7a-98bc-2e9133abf410.jpg)

**Comment by brandonkelly** [comment]
Can you try reverting to Craft 4.2.3 and see if that fixes this? Change your `craftcms/cms` constraint in composer.json to `4.2.3` (no `^` or `~`) and run `composer update`.

**Comment by jammid** [comment]
This happened in Craft 4.2.3. I updated to 4.2.4 to see if it would fix this

**Comment by brandonkelly** [comment]
Thanks! We’ve fixed this for the next release. Should go out tomorrow.

**Comment by jammid** [comment]
That's great! Thank you.

**Comment by brandonkelly** [comment]
Craft 4.2.5 is out with that fix. Thanks again!
