### ISSUE TITLE
[4.x]: `BaseMultiSelectConditionRule` mutates "New" option in select list

### ISSUE THREAD

**Issue by nfourtythree** [craftcms/cms#11946]
### Description
When extending the `BaseMultiSelectCondtionRule` if there is a set of selectable options that include `'new' => 'New'` the output of this value is mutated and an add icon is added.

![](https://p191.p3.n0.cdn.getcloudapp.com/items/Jru86xAP/03e6aa02-509f-4fcc-aa64-d53ae06c98d1.png?v=3aa039427fe0f54c33af1bdb92325921)

### Craft CMS version

4.2

### PHP version

8.0

**Comment by brandonkelly** [comment]
Here’s the culprit:

https://github.com/craftcms/cms/blob/fa36930173af958ec437ce043837ea9f22454d71/src/web/assets/cp/src/css/_main.scss#L6243-L6251

We’re not actually taking advantage of that anywhere in core, but it’s being used by Commerce, e.g. when creating a new tax rate:

<img width="559" alt="The Tax Category setting when creating a new tax rate in Craft Commerce. The input is a Selectize menu, currently expanded, with “General” and “New tax category…” options." src="https://user-images.githubusercontent.com/47792/190462907-1662e973-0f17-4027-8c13-97ce0485a886.png">

I’m going to remove those styles in Craft 5. Anything still taking advantage of them should switch over to the `_includes/forms/selectize.twig` template (or `craft\helpers\Cp::selectizeHtml()` / `selectizeFieldHtml()`), and pass `addOptionFn` and `addOptionLabel` values to it. (See the [`_includes/forms/fs.twig`](https://github.com/craftcms/cms/blob/develop/src/templates/_includes/forms/fs.twig) template for an example.)

In the meantime, you will need to try to avoid using `new` as an option value. Ideally, a UID could be used instead, as handles can be fickle.
