### ISSUE TITLE
"Suggested" soft limit for text field max-length

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1195]
> Created by: Josh (josh@transom.design) on 2016/04/04 18:17:27 +0000
> Votes at time of UserVoice import: 2

-----------------------------------

It would be great to give clients a "Soft Limit" on how much text content they can add to a field. 

Sometimes a page design will degrade if too much copy is added to a section. 

A soft limit on text fields would show clients they are nearing the ideal length of text, without explicitly preventing them from writing the last few words of their content.

**Comment by RitterKnightCreative** [comment]
Was just thinking about this the other day. Would be really handy for things like SERP meta descriptions and read more/entry excerpts where you want users to stay around a certain range. 

It would also be handy to set a minimum and hard limit in addition so basically someone would need to enter at least X characters and then the limiter would indicate that "hey you're going over the limit, it's OK but watch it punk..." and then impose the hard limit sometime after.

**Comment by carlcs** [comment]
Can this please be considered for Craft 4?
