### ISSUE TITLE
[3.x]: Twig placeholder number format is not translated

### ISSUE THREAD

**Issue by dgsiegel** [craftcms/cms#11966]
### Description
 According to both Craft as well as Yii docs, you can use placeholder values in the `t()` filter (https://www.yiiframework.com/doc/guide/2.0/en/tutorial-i18n#number). However, when trying to translate a number format it will not be translated, but the English default will be displayed, e.g.

`{{ "We have {count,number} objects"|t({count: 123456789}) }}` will display `"We have 123,456,789 objects"` instead of `"We have 123.456.789 objects"` on a site with a German locale.

Interestingly, `Craft::t('site', 'We have {count,number} objects', [ 'count' => 123456789 ], null, 'de');` will result in the same output.

However {{ "We have {count} objects"|t({count: 123456789|number}) }} works fine.

### Craft CMS version

3.7.54

### PHP version

PHP 8.0.18

### Operating system and version

Linux

### Database type and version

MySQL

### Installed plugins and versions

-

**Comment by wsydney76** [comment]
I think formatting only works if there is a matching string in your translation file `translations/de/site.php`, something like

 `'We have {count,number} objects' => 'Wir haben {count,number} Objekte',`

This will output `Wir haben 123.456.789 Objekte`

/Mel

**Comment by brandonkelly** [comment]
@dgsiegel Can you confirm whether you have an existing translation for the message in German?

If the German translation doesn’t exist, then Craft won’t do any German-specific formatting for it, as @wsydney76 said.

**Comment by dgsiegel** [comment]
> I think formatting only works if there is a matching string in your translation file `translations/de/site.php`

Yes, you're right. Adding the translation to that file fixes the formatting.

As our primary site is set up to use the German locale, I thought such a translation won't be necessary as the app language is set to German and not English.

**Comment by brandonkelly** [comment]
Currently the `site` source language is hard-coded to `en-US`. Making it the primary site language isn’t a bad idea, though.
