### ISSUE TITLE
Missing permissions for adding widgets [3.x]: 

### ISSUE THREAD

**Issue by FrDH** [craftcms/cms#11967]
### Description
A user without permission to add or edit forms by freeform, can add a freeform widget. Same goes for all other widgets. I looked but couldn't find any settings that allow/disallow a user to add widgets or even view the dashboard.

### Steps to reproduce

1. Create a usergroup without any permissions except for opening the CP
2. Create a user and assign it to this new usergroup.
3. Open the Dashboard and start adding widgets

### Expected behavior
- A setting to not be allowed to open the dashboard
- Not being able to add widgets for plugins you don't have access to.

### Actual behavior
Any user can add all available widgets, see screenshot.
![Schermafbeelding 2022-09-19 om 09 17 50](https://user-images.githubusercontent.com/1387163/190967313-499de933-45fd-40a3-90ab-5366437ff141.png)

### Craft CMS version

 3.7.53.1

### Installed plugins and versions

- freeform
- linkit
- retour
- seomatic
- supertable

**Comment by brandonkelly** [comment]
Widgets should be doing their own permission checks – so this is a Freeform bug.

For example, the Craft Support widget only makes itself selectable for admin users:

https://github.com/craftcms/cms/blob/bb8f10e50327f1ed4b6ecba66287b1f40eb582e7/src/widgets/CraftSupport.php#L34-L38

And the Updates widget is only selectable for users with the `performUpdates` permission:

https://github.com/craftcms/cms/blob/bb8f10e50327f1ed4b6ecba66287b1f40eb582e7/src/widgets/Updates.php#L33-L37
