### ISSUE TITLE
[4.x]: Save asset button is visibly hidden when Craft debug toolbar is on

### ISSUE THREAD

**Issue by samueldraper** [craftcms/cms#11965]
### Description

When editing an asset in the control panel (e.g. crop image), the save button is located bottom right of the browser window.
If the Craft Debug toolbar is on, the save button is completely obscured and cannot be clicked.

### Suggestion

Change UI to move anything in the bottom 'row' of the control panel offset by the depth of the Craft Debug toolbar.

### Craft CMS version

4
<img width="344" alt="Screenshot 2022-09-16 at 22 48 46" src="https://user-images.githubusercontent.com/2412282/190846234-60c4de85-6887-4c09-9d17-d9a1ea3a3e37.png">

**Comment by brandonkelly** [comment]
Craft 3.7.55 and 4.2.5 are out with that fix.

Ended up doing something similar for slideouts as well.
