### ISSUE TITLE
[4.2.4]: Changing channel to structure doesn't actually turn it into a structure

### ISSUE THREAD

**Issue by johnwbaxter** [craftcms/cms#11978]
### Description
Changed an existing channel to a structure and there is no field to choose a parent item and you can't drag entries up or down in order as there is no icon.

However, if you look at the section config page, it lists it as a structure.

### Steps to reproduce

1. Have channel with entries in it. Then change to structure.

### Expected behavior

For the section to now be a structure with the functionality of a structure.

### Actual behavior

Still seems to be a channel.

### Craft CMS version

4.2.4

### PHP version

8.0.19

### Operating system and version

Linux 5.19.0-76051900-generic

### Database type and version

MySQL 5.7.38

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-16)

### Installed plugins and versions

-
Embedded Assets 	3.0.5
Express Forms 	2.0.0-beta.2
Mix Manifest 	1.0.2
Postmark 	3.0.0
Redactor 	3.0.2
Retcon 	2.5.0
SEO 	v4.0.3
Super Table 	3.0.1
Template Comments 	4.0.0
Typed link field 	2.1.4

**Comment by brianjhanson** [comment]
I'm having trouble replicating this one. Is there anything useful in the `storage/logs/queue-*.log` files? Depending on the number of entries in the channel you're converting, I also wonder if you caught the UI before all the elements had been resaved.

**Comment by johnwbaxter** [comment]
@brianjhanson There are like 10 entries in the section! It's a really small site!

Nothing exciting in the logs. This is the relevant log output from the change I made.

```
2022-09-21 09:07:58 [queue.INFO] [craft\queue\QueueLogBehavior::beforeExec]  [18] t9n:["app","Resaving {section} entries",{"section":"People"}] (attempt: 1, pid: 24) - Started {"memory":23257032} 
2022-09-21 09:07:58 [queue.INFO] [craft\queue\QueueLogBehavior::afterExec]  [18] t9n:["app","Resaving {section} entries",{"section":"People"}] (attempt: 1, pid: 24) - Done (time: 0.317s) {"memory":30546456} 
2022-09-21 09:07:58 [queue.INFO] [application] Request context:
$_GET = [
    'p' => 'admin/actions/queue/run'
    'v' => '1663751277989'
]

```

**Comment by brianjhanson** [comment]
I'm guessing none of the other logs have anything exciting in them either? Also just want to double check that "Structure" is selected in the sort field (if it is available)?
![CleanShot 2022-09-21 at 09 06 11](https://user-images.githubusercontent.com/1843073/191526424-2eb92d5c-5772-44a1-85bc-400fe6c88645.png)

If there's nothing else in the logs, could you send a database backup and your composer files to support@craftcms.com?

**Comment by johnwbaxter** [comment]
No, nothing in the logs at all of any note.

I've changed it back to a channel and saved it, and then changed it to a structure again and saved it and it is now a structure with the "parent" field and the drag handle.

I'm now just slightly nervous about pushing this out to production!! :-|

**Comment by brandonkelly** [comment]
Is it possible that the first time you converted the section to a structure, you had the “Max Levels” setting set to `1`?

**Comment by johnwbaxter** [comment]
Only if that value is the default when you change it, i literally just changed it to structure and hit save.

I've deployed it to prod and it's all as it should be *phew!*

I guess it must have been some one off weirdness.

**Comment by brandonkelly** [comment]
Alright, will go ahead and close this then.
