### ISSUE TITLE
Grapqhl schema is empty [4.2.5]:  

### ISSUE THREAD

**Issue by vitalijalbu** [craftcms/cms#11979]
### Description

My graqhql schema is empty, also i created a new one but still empty.
Using craft pro 4.2.5, don't have a license key because still in development on a third-domain (https://demo.resthotels.it/)

### Expected behavior
I came from version 3 where graphql worked fine, but now in version 4 cannot access to graphql. Maybe is due to the license key=?!
Would be better to add a option of a third-domain development env where users can test their websites, without completely buying the license.

### Actual behavior
Graqhql schema is empty.

### Craft CMS version

4.2.5

### PHP version

8.0.23

### Operating system and version

	Linux 3.12.18-clouder0

### Database type and version

mysql

### Image driver and version

GD 8.0.23

### Installed plugins and versions

Image Resizer | 3.0.2

Maps | v4.0.3

<img width="419" alt="Schermata 2022-09-21 alle 11 45 01" src="https://user-images.githubusercontent.com/40239902/191474006-b4eea0ec-c1fd-4713-95cf-0da7e41522cd.png">

<img width="811" alt="Schermata 2022-09-21 alle 11 52 10" src="https://user-images.githubusercontent.com/40239902/191474073-53772885-6b12-4dab-9df9-8d85812c7924.png">

**Comment by giorgiopogliani** [comment]
Same problem with a fresh install using `composer create-project craftcms/craft`

**Comment by giorgiopogliani** [comment]
Forcing `webonyx/graphql-php` at version `14.11.5` seems to fix the problem

**Comment by vitalijalbu** [comment]
yes, i think so because just saw they released new version of graphql, so what should i do? by myself or wait for craft team? @brandonkelly thanks.

**Comment by brandonkelly** [comment]
Looks like webonyx/graphql-php 14.11.7 contained breaking changes that were intended for 15.0.0, and a fix for 14.x is imminent – https://github.com/webonyx/graphql-php/issues/1221#issuecomment-1253521906

**Comment by brandonkelly** [comment]
Just released Craft 3.7.55.1 and 4.2.5.1, which mark webonyx/graphql-php 14.11.7 as a conflicting package/version, so they can’t be used together.
