### ISSUE TITLE
[4.2.5]: New Category buttons missing from UI after update

### ISSUE THREAD

**Issue by vanburenx** [craftcms/cms#11977]
### Description
Currently unable to create Categories because the **New Category** button has disappeared from the main Categories menu and on the modal for individual Entries. This happened after updating from v4.2.4 to v4.2.5

 See image.

![craft-4 2](https://user-images.githubusercontent.com/15201797/191404975-17fc68d0-a1b5-4520-931f-69a6c08ae3d1.jpg)

### Steps to reproduce

1. Update from v4.2.4 to v4.2.5

### Expected behavior
Ability to add Categories as usual on Categories page or on individual Entries.

### Actual behavior
New Category button is gone so Categories cannot be created inside the UI.

### Craft CMS version

Craft Solo 4.2.5

### PHP version

8.1.8

### Operating system and version

Ubuntu 20Linux 5.15.0-48-generic

### Database type and version

PostgreSQL 14.5

### Image driver and version

Imagick 3.6.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- Amazon S3	2.0.1
- Amazon SES	2.0.1
- Colour Swatches 4.2.0.1
- Image Resizer 3.0.2
- Imager X 4.1.4
- Minify 4.0.0-beta.2
- oEmbed 2.2.2
- Read Only 1.0.5
- Redactor 3.0.2
- SEOMate 2.0.3
- Template Comments 4.0.0
- Typogrify 4.0.0

**Comment by AlexShearcroft** [comment]
To follow on with this bug raised, we too are also experiencing the same issue but with an update to the latest Craft CMS 3 version **Craft CMS 3.7.55**

**Comment by darylknight** [comment]
Happening to me too

4.2.4:
![image](https://user-images.githubusercontent.com/1250017/191507111-43d2a8ae-ee8e-4b81-85b3-29ba3c707d68.png)

4.2.5:
![image](https://user-images.githubusercontent.com/1250017/191507052-a5af9df7-9197-4a5b-9c1b-6b921589af16.png)

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 3.7.55.1 and 4.2.5.1 are out with a fix.
