### ISSUE TITLE
[4.x]:  baseCpUrl not working

### ISSUE THREAD

**Issue by mihob** [craftcms/cms#11989]
### Description

In the config under general.php the value for baseCpUrl is explicitly set. However, URLs from the control panel sometimes use the frontend url of the main page, such as the impersonation url.

### Steps to reproduce

1. Go to Users
2. Choose a User
3. Copy the impersonation url

### Expected behavior

Url should lead to the control panel with the login token (https://backend.example.com?token=XYZ)

### Actual behavior

Url leads to the frontend with the login token (https://example.com/de?token=XYZ)

### Craft CMS version

Craft Pro 4.2.5.1

### PHP version

8.1.9

### Operating system and version

Linux 5.10.124-linuxkit

### Database type and version

MySQL 8.0.30

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-35)

### Installed plugins and versions

CP Field Inspect  1.4.4
Expanded Singles 2.0.0
Field Manager 3.0.2
ImageOptimize 4.0.2
Incognito Field 1.3.0
Neo 3.3.9
Redactor 3.0.2
Redactor Anchors 1.4.0
Reverse Relations 2.0.0
Schedule 0.4.0
Sentry Logger 4.1.1
SEOmatic 4.0.8
Typed link field 2.1.4

**Comment by brianjhanson** [comment]
Does the user you're impersonating have the "Access the control panel" permission? The impersonation link will use the frontend link when the user doesn't have access to the CP.

**Comment by mihob** [comment]
Oh sorry, you're right. I have accidentally selected a user who does not have the necessary rights. This can be closed
