### ISSUE TITLE
[4.x]: Changing an asset in a relationship field slideout, in a matrix is not always saved

### ISSUE THREAD

**Issue by sm-md-lg** [craftcms/cms#11988]
### Description

When **uploading** an asset in a slideout, that is in a matrix field, the image is not saved.  The image is uploaded, but it is not saved to the field.  

This happens when clicking the upload button in the entries field _and_ in the asset selector dialog.

This **only** happens when editing an asset field in a matrix in a slideout.  When editing the entry with a matrix directly, everything works properly.

Note, there is also a bug where text in a text field in the same setup as an asset field will intermittently get truncated and not saved properly, but it feels like it is related to this asset bug.  This one is harder to describe so if necessary I'll add a video.

### Steps to reproduce

1. Create a channel with a matrix field that has an asset field in it.
1. Create a channel with a entries field that points to the previous channel.
1. Create an entry in each one.
1. Go to the channel with the entries field and double click the entries field and select an entry with the matrix field.
1. Click the upload button for the asset and upload a new image.
1. Save and look at the slideout again and the image you selected won't be there.

### Craft CMS version

4.2.3

### PHP version

8.0.21

### Operating system and version

Linux

### Database type and version

mysql:8.0

**Comment by brianjhanson** [comment]
I'm having trouble replicating this, but it like it could be related to #11854. Any chance you could send a database backup and your `composer.json` and `composer.lock` files to support@craftcms.com?

**Comment by sm-md-lg** [comment]
Here is a db and a zip file of two videos showing the bug in action.

- [asset-text-field-not-saving.sql.gz](https://github.com/craftcms/cms/files/9735619/asset-text-field-not-saving.sql.gz)
- [asset-and-text-field-videos.zip](https://github.com/craftcms/cms/files/9735638/asset-and-text-field-videos.zip)

This db has two entries, 
1. one with a matrix with an asset field and a text field
2. another entry with a matrix with an entries field.

In the assets-field.mp3 video, when I edit the asset field in a slideout, the second time, the image is not saved.

In the text-field.mp3 video, when I edit the text field the second time and add the z's, the z's at the end do not get saved, but the z's at the beginning do get saved.

If there is anything else I can give you to help, please let me know.

**Comment by sm-md-lg** [comment]
This looks like the same bug as #12058.

**Comment by brandonkelly** [comment]
Sure does look like the same bug. We just got that fixed for the next release (#12073). Thanks for the help!

**Comment by brandonkelly** [comment]
Craft 4.2.6 is out with that fix.
