### ISSUE TITLE
[4.x]: Can't copy-paste square meter symbol in Plain Text fields

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#11993]
### Description
I can't copy-paste square meter symbol in Plain Text fields. They're automatically converted to m2 (so the 2 is not written as a superscript text). Otherwise, this is working fine in Redactor fields.

### Expected behavior

Add the text as a superscript text.

### Actual behavior

Text converted to a non-superscript text.

### Craft CMS version

4.2.5.1

### Installed plugins and versions

-

**Comment by brianjhanson** [comment]
Plain text fields don't render HTML so this is working as expected. In the Redactor field, it's actually outputting `m<sup>2</sup>` and the field renders that to superscript.
