### ISSUE TITLE
[4.x]: Trying to create a new entry

### ISSUE THREAD

**Issue by MaartenWaegeman** [craftcms/cms#11990]
### Description

I have a fresh craft install. I'm trying to create a new entry and I get an error.
![afbeelding](https://user-images.githubusercontent.com/7084691/191624361-bf3b314b-7399-49e2-afd8-c7e40cae5dac.png)

As far as I can see, the element should be in the database
![afbeelding](https://user-images.githubusercontent.com/7084691/191624810-c02fc256-beac-4118-9810-f8837518cbc2.png)
![afbeelding](https://user-images.githubusercontent.com/7084691/191624887-f4bb81e3-7d8c-4957-84aa-b72638a36a9b.png)

### Actual behavior
![afbeelding](https://user-images.githubusercontent.com/7084691/191624511-98093364-df96-4ee3-b523-f00c423498d8.png)
![afbeelding](https://user-images.githubusercontent.com/7084691/191624552-f524a1c8-f336-42c5-b833-7a3b5f594680.png)

### Stacktrace
yii\web\BadRequestHttpException: Invalid element ID: 51 in /var/www/blob.be/craft/vendor/craftcms/cms/src/controllers/ElementsController.php:1552
Stack trace:
#0 /var/www/blob.be/craft/vendor/craftcms/cms/src/controllers/ElementsController.php(242): craft\controllers\ElementsController->_element()
#1 [internal function]: craft\controllers\ElementsController->actionEdit()
#2 /var/www/blob.be/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#3 /var/www/blob.be/craft/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#4 /var/www/blob.be/craft/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#5 /var/www/blob.be/craft/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction()
#6 /var/www/blob.be/craft/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#7 /var/www/blob.be/craft/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest()
#8 /var/www/blob.be/craft/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#9 /var/www/blob.be/craft/web/index.php(12): yii\base\Application->run()
#10 {main}

### Craft CMS version

4.2.5.1

### PHP version

8.1.2

### Operating system and version

Linux 5.15.0-41-generic

### Database type and version

MySQL 5.5.5

### Image driver and version

magick 3.6.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-Redactor 3.0.2

**Comment by brianjhanson** [comment]
That looks like a lot of elements already in the DB for a fresh install. How did you run the install? Did anything odd happen during that process?

**Comment by MaartenWaegeman** [comment]
@brianjhanson That was just me trying to create a new entry over and over 😓. I've since dropped my database, cleared my projectconfig and also removed my vendor folder, but I still have the same issue.

**Comment by brianjhanson** [comment]
Oh boy, I can see the frustration 😅 Have you also cleared all your caches with the `craft clear-caches/all` command or the Utility in Utilities > Caches? It might also be worth deleting the `storage/runtime` folder for good measure.

Are there any JS errors in the console? 

It's definitely odd behavior because your stack trace is coming from the `ElementsController` but that button should be hitting the `EntriesController` so it seems like a wire is getting crossed somewhere.

**Comment by MaartenWaegeman** [comment]
@brianjhanson Yeah, I have cleared the caches and also removing the storage/runtime didn't work. I suspect it being a configuration issue somewhere. I have setup a docker configuration locally and there everything works as expected. So it's probably an 'it works on my machine issue'.

**Comment by brianjhanson** [comment]
Alright, in that case I'm going to close this, but feel free to re-open if you find more evidence to support a bug here. Also still happy to answer questions if they come up.

**Comment by brandonkelly** [comment]
Most likely the error occurred because the entry was missing a row in `content` or `elements_sites`. No idea why that would be the case though. If it crops up again, please send a database backup and your Composer files into support@craftcms.com and we can try to investigate from there.
