### ISSUE TITLE
[4.x]: Craft Element index looks sub-optimal at smaller responsive sizes

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#11999]
### Description

The element index display looks sub-optimal at smaller responsive sizes:

https://user-images.githubusercontent.com/7570798/191822746-71ae78a0-686d-48e4-bda6-ab2420163604.mov

### Craft CMS version

Craft CMS 4.2.5.1

### PHP version

n/a

### Operating system and version

macOS Monterrey 12.5.1 (21G83)
Google Chrome Version 105.0.5195.125

### Database type and version

n/a

### Image driver and version

n/a

### Installed plugins and versions

n/a

**Comment by brandonkelly** [comment]
Turns out this was already fixed for Craft 4.3 via #11963 🎉
