### ISSUE TITLE
Upload progress bar position is off when there is a scrollable list of assets

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#12]
#### Environment:

- Craft version: 3.x
- PHP version: 7.x
- Database driver & version: n/a 
- Plugins & versions:

#### Description:

Have enough Assets in the manager that you can scroll down a few pages.

Drag and drop a file to upload it.

The progress bar as up at page 1.

**Comment by benjamindavid** [comment]
Fixed by 1700e94cfe4d10e647a58df9f1300b06f7bea833.

**Comment by benjamindavid** [comment]
Fixed by 59b4e64aecdbf3af8bf5a5ff6783e555f4c85a23.
