### ISSUE TITLE
[4.x]: Deleting Site doens't delete it from database.

### ISSUE THREAD

**Issue by thomascoppein** [craftcms/cms#12006]
### Description

When removing a site from a multi site setup, the row is not deleted from the database. Which causing problems with the SEO Sitemap plugin who gets all sites from sites table.

### Steps to reproduce

1.Remove site from Settings > Sites

### Expected behavior

Site is deleted from databae.

### Actual behavior

The deleted_date column is set, but the row remains in the database.

### Craft CMS version

Craft Pro 4.2.3

### PHP version

8.1.6

### Installed plugins and versions

- SEO

**Comment by brianjhanson** [comment]
Yeah, site are soft deleted. They should be removed from the DB based on your [`softdeleteduration `](https://craftcms.com/docs/4.x/config/general.html#softdeleteduration) config setting. 

If you want to remove them earlier you can use the [`gc`](https://craftcms.com/docs/4.x/console-commands.html#gc) command, but beware that will also clean out any other trashed items you have in the DB.

**Comment by brandonkelly** [comment]
Seems like a bug worth reporting to the SEO Sitemap plugin though. If it’s going to look at the `sites` table directly (as opposed to `Craft::$app->sites->getAllSites()`), it should be including `->where(['dateDeleted' => null])`.

**Comment by frederikvdbe** [comment]
I was having the same issue but on my project the `deleted_at` column isn't even set after I delete a site.

**Comment by brandonkelly** [comment]
@frederikvdbe By `deleted_at` you mean `dateDeleted`?

**Comment by frederikvdbe** [comment]
@brandonkelly Yes, but for some reason I can delete my websites now without problems ^^
