### ISSUE TITLE
[3.x]: Freeform stays disabled after update

### ISSUE THREAD

**Issue by HannahDeWachter** [craftcms/cms#12009]
### Description
I just tried updating the [Freeform](https://github.com/solspace/craft-freeform) plugin to 3.7.4 with composer. Now the plugin is disabled and when I try to enable it through the backend (admin/settings/plugins) it stays disabled and there are no errors, not even in the log files.

### Steps to reproduce

1. Run `composer require solspace/craft-freeform 3.7.4` in terminal.
2. Freeform is not visible in the sidebar of the backend.
3. Go to admin/settings/plugins, Freeform is disabled.
4. Click on Enable.
5. Freeform stays disabled.

### Expected behavior
Freeform should be enabled and accessible in the sidebar.

### Craft CMS version

3.4.29.1

### PHP version

7.3.29

### Database type and version

MySQL 5.7.34

### Installed plugins and versions

-

**Comment by brianjhanson** [comment]
I'm having trouble replicating this one. Are you able to update to the latest 3.X version of Craft to see if the issue persists there?

If not, are you able to send you `composer.json`, `composer.lock` and project config files over to support@craftcms.com so I can dig deeper?
