### ISSUE TITLE
Craft cms select options doesn't allow symbols [4.2.5.1]: 

### ISSUE THREAD

**Issue by vitalijalbu** [craftcms/cms#12013]
### Description

<img width="954" alt="Schermata 2022-09-27 alle 16 34 43" src="https://user-images.githubusercontent.com/40239902/192555912-af20a1b1-7764-4de8-a4df-9fafb81fea02.png">

### Steps to reproduce

1.create a field as select menu, if you put some symbols (in my case energy ratings) it won't add a+, a++ and so on

### Expected behavior
expected must be a+, a++, b++ and so on

### Craft CMS version

4.2.5.1

### Installed plugins and versions

-

**Comment by i-just** [comment]
By default, Craft will generate your values to not contain any special characters (same behaviour as when a handle for a section is generated etc). You can change the values to contain symbols like +. Once you've given your option a Label, Value is autogenerated, and you can go into that cell and type in any adjustments.

![Screenshot 2022-10-05 at 13 57 17](https://user-images.githubusercontent.com/4500340/194066757-b728ec75-04f9-4ad9-a7a3-21f15661946b.png)

Hope this helps!
