### ISSUE TITLE
[3.7.x]: Setting event not valid in custom validation results in "Entry not found"

### ISSUE THREAD

**Issue by LeoWie93** [craftcms/cms#12015]
### Description
We have a couple of websites that use their own custom validation on fields that we need to handle separately from Craft. It works perfectly on already present entries. But while creating new ones craft fails to show errors and load the edit entry view.

#### Things to notice
- **This is tested on a fresh install**

##### Crafts validation triggers first
-  [Crafts validation triggers and returns before our custom validation](https://user-images.githubusercontent.com/29427760/192598296-42106b61-4702-43a3-9119-158dadde209c.png)

##### Custom validation triggers second
- [Custom validation triggers as expected](https://user-images.githubusercontent.com/29427760/192598648-f45399c6-4cec-4902-809b-2759072cbcb6.png)

#### BUT
it only works on already saved entries. Entries that are created new will return an `NotFoundHttpException`:  [Entry not found](https://user-images.githubusercontent.com/29427760/192597164-9b802a2d-cc77-4f9d-90d5-22ef9f19bb29.png)

#### Custom validation to reproduce:
![image](https://user-images.githubusercontent.com/29427760/192599155-0cc00473-7831-4062-a447-afbfade0e9e3.png)

### Steps to reproduce

1. create a Module/Plugin
2. implement a custom validation (like my example above)
3. try to create and save a new entry that is being validated by the custom validation

### Expected behavior
- setting `$event->isValid = false;` will tell Craft that this element is not valid and return to the corresponding element edit page.

### Actual behavior
- Craft throws an `NotFoundHttpException`: [Entry not found](https://user-images.githubusercontent.com/29427760/192597164-9b802a2d-cc77-4f9d-90d5-22ef9f19bb29.png)

### Craft CMS version

3.7.55.2

### PHP version

7.4.30

### Operating system and version

Linux 5.15.70-1-lts

### Database type and version

MySQL 8.0.30

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.10-23)

### Installed plugins and versions

- just my own to demonstrate a custom validaiton

**Comment by brandonkelly** [comment]
Thanks for reporting that! We’ve fixed this for the next Craft 3 release via #12067.

**Comment by i-just** [comment]
In addition to Brandon's comment above, please note that once released, you can use the following code as a starting point:
```
Event::on(
    Entry::class,
    Element::EVENT_BEFORE_VALIDATE,
    function (ModelEvent $e) {

        /* @var Entry $entry */
        $entry = $e->sender;

        if (ElementHelper::isDraftOrRevision($entry)) {
            return;
        }

        if (strstr($entry->title, 'valid')) {
            return;
        }

        $entry->addError('customValidated', 'This is my error');
        $e->isValid = false;
    }
);
```

**Comment by brandonkelly** [comment]
Craft 3.7.56 and 4.2.6 are out with the fix for this.
