### ISSUE TITLE
[3.x]: "Unable to save entry as a draft: URI is not a valid URI"

### ISSUE THREAD

**Issue by readtedium** [craftcms/cms#12011]
### Description

I recently upgraded my site to Craft Pro and am finding that on the default site on my multi-site build, I cannot save new posts or update existing posts due to a “URI is not a valid URI” error. My secondary site can handle new posts just fine, and I can add pages on the default site. It only seems to be an issue when adding new post entries.

I am not running into this issue with my local build.

### Steps to reproduce

1. I recently upgraded to Craft Pro, and also updated to Craft 3.7.55.2 at same time

### Expected behavior

New entries in my “Posts” section get created; old posts save.

### Actual behavior

I get the URI is not a valid URI error, and when creating new posts, I receive a 500 error. The system log produces this error message in the system:

```
yii\base\Exception: Unable to save entry as a draft: URI is not a valid URI in /srv/app/tedium/htdocs/vendor/craftcms/cms/src/controllers/EntryRevisionsController.php:170
Stack trace:
#0 [internal function]: craft\controllers\EntryRevisionsController->actionCreateDraft(Object(craft\models\Section), Object(craft\models\Site))
#1 /srv/app/tedium/htdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /srv/app/tedium/htdocs/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#3 /srv/app/tedium/htdocs/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction(‘create-draft’, Array)
#4 /srv/app/tedium/htdocs/vendor/craftcms/cms/src/web/Application.php(293): yii\base\Module->runAction(‘entry-revisions...’, Array)
#5 /srv/app/tedium/htdocs/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction(‘entry-revisions...’, Array)
#6 /srv/app/tedium/htdocs/vendor/craftcms/cms/src/web/Application.php(278): yii\web\Application->handleRequest(Object(craft\web\Request))
#7 /srv/app/tedium/htdocs/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#8 /srv/app/tedium/htdocs/web/index.php(21): yii\base\Application->run()
#9 {main}
```

### Craft CMS version

Craft Pro 3.7.55.2

### PHP version

8.1.3 (I also tried downgrading to PHP 8.0.16, same issue)

### Operating system and version

Linux 4.15.0-163-generic

### Database type and version

MySQL 5.7.33

### Image driver and version

Imagick 3.7.0

**Comment by readtedium** [comment]
Hi, I was able to resolve this issue on my own. The problem seems to be an unrelated issue I’m running into that auto-curls quotes in certain fields.

**Comment by brandonkelly** [comment]
Glad you got it sorted!
