### ISSUE TITLE
[3.x]: Cookies not persisting on Chrome : Unable to verify your data submission

### ISSUE THREAD

**Issue by ryssbowh** [craftcms/cms#12021]
### Description

I'm developing a website with a payment process going to an external page for a 3D secure check. Because of that I have to set the config `sameSiteCookieValue` to `None` or the session is not maintained when the user comes back from the 3D check.

I'm unable to login on the CP on Chrome (105.0.5195.125) while developing locally on http, the CRSF check fails and I receive a 500 "Unable to verify your data submission".

It does work if I set the `sameSiteCookieValue` to `Lax` or if I work on https.

That must have to do with Chrome allowing "None" only for secure environments (https://developers.google.com/search/blog/2020/01/get-ready-for-new-samesitenone-secure) and I'm guessing the CMS can't do anything about it, my question was more if it was possible to set the `sameSiteCookieValue` for some requests only, which would solve http problems and make the site a bit more secure I suppose.
I've tried responding to the event `Application::EVENT_BEFORE_REQUEST` but it seems the session is already opened at that stage.

Would you have any suggestions ?

### Steps to reproduce

1. Set `sameSiteCookieValue` to `None` on a non-https environment
2. Try to login on Chrome

### Craft CMS version

3.7.54

### PHP version

8.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Could this be solved by using SSL locally? If so, I’d suggest you just go that route, as the closer your dev environment can mimic production, the better. We’ve been recommending using [DDEV](https://ddev.com/) for local development, which is cross-platform, super reliable, and supports SSL out of the box.

**Comment by ryssbowh** [comment]
Yes it's solved by using a SSL locally. It's just that the 'None' cookie setting is set for all requests even though it's only needed on one, but I guess there's no way around it.
