### ISSUE TITLE
[3.x]: Can't enable entry in any site (error with drafts/propogation)

### ISSUE THREAD

**Issue by modelesque** [craftcms/cms#12034]
### Description
I have a structure of entries. Each entry has:
1. title (not translatable)
2. custom text field (not translatable)
3. custom matrix field (translatable by language)

Each matrix block has 2 required text fields and 1 redactor field (all translatable by language). There's a minimum of 1 block and a max of 3.

I have 6 sites (3 countries, 2 languages per country). Every entry is a sibling of each other in the structure and has no parent.

I created a new entry and started editing it. Early on, I accidentally hit `command + s`, which saved the entry and showed validation errors all over the page. I added all my content, saved again, everything was fine. I then went on to the other languages and added content. Saving was all fine.

When I returned to the listing page, I saw that this one entry was disabled in every site, unlike the entry I just created before it. When I tried to enable the entry from the listing page, a flash error says `Could not update status due to validation error`.

I go back to this entry's edit page. All the required fields were filled out correctly. If I save again without any changes, it's fine. If I edit the `title`, for example, I get a `400 Bad Request: Request missing required body param`. The 2nd step in the stack trace shows me this code is throwing the error `$draftId = $this->request->getRequiredBodyParam('draftId');` in `craftcms/cms/src/controllers/EntryRevisionsController::actionPublishDraft` (line `421`).

If I try to enable the entry in any of the sites, the tooltip error next to the draft dropdown says:

> The draft could not be saved. Couldn’t propagate element to other site.

I checked the entry in all sites and there is no draft; everything is current. When I check my logs, it says:

> Couldn’t propagate element to other site due to validation errors:

But after the colon, there is no list of errors. The error message is simply that.

I go back to the entry and edit the title. It saves with no errors this time. I enable the entry in the site I'm currently viewing, and now I get this error:

![TypeError](https://user-images.githubusercontent.com/13842870/193301280-5d9f735c-2ed3-4497-954c-cc24a0c79451.png)

### Craft CMS version

3.7.55.2

### PHP version

8.0.19

### Operating system and version

Linux 4.19.0-17-amd64

### Database type and version

MySQL 10.6.8

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-16)

### Installed plugins and versions

-

**Comment by modelesque** [comment]
Also, now when I create another entry in the structure, they are immediately disabled in all sites upon saving them. So it seems all future entries being made will be forced to be disabled.

**Comment by i-just** [comment]
So that I can try to replicate this, could you please let me know what propagation method you're using for this section and whether you have the default status for entries in this section turned on for all the sites that are using it? What's the propagation method set for that matrix field? 

It would also be helpful to know how your sites are grouped (all in one group, grouped by country, grouped by language or any other option) and if you have `autosaveDrafts` turned off (it's on by default, so if you haven't changed it to be off in `config/general.php` then it's on)?

**Comment by modelesque** [comment]
Hi @i-just: 

The structure's propagation method is set to `all` ("Save entries to all sites enabled for this section"). Each site's `enabledByDefault` ("Default Status") is `true`.

The matrix field's propagation method is set to 'all' ("Save blocks to all sites the owner element is saved in").

Each site group is a country.

`autosaveDrafts` is not set in my config, so it's on.

**Comment by i-just** [comment]
Hi @modelesque,

I'm having trouble replicating this one. Are you able to send your `composer.json`, `composer.lock` and database backup over to support@craftcms.com, so I can dig deeper?

**Comment by modelesque** [comment]
Hi @i-just sorry to respond 2 weeks later. I removed some obsolete entry types from the section and it appears that fixed my problem. Now all the remaining entries are able to be enabled/disabled.

**Comment by i-just** [comment]
Thank you for the update. Glad to hear it's all working now!
