### ISSUE TITLE
[4.x]: Tag Fields, Field Layout Tag Condition not responding in flyout menu

### ISSUE THREAD

**Issue by petenice** [craftcms/cms#12039]
### Description

I have a contextual field in my "Field Layout" however when I view and edit the field in the flyout panel, the condition isn't being honored.

I did a screencast which details the issue, viewable here at this unlisted video:
https://youtu.be/CpNFDFT8-3o

Thank you for your time and effort

### Craft CMS version

Craft CMS 4.2.5.1

### PHP version

8.2

### Operating system and version

Mac OS / Laravel Mix

### Database type and version

mySQL 8

**Comment by brianjhanson** [comment]
The auto updating feature is currently only available to elements that support drafts (entries, categories, etc.). That will change in Craft 5, but for now you'll have to save and re-open the slide out when working with tags.
