### ISSUE TITLE
[3.x]: Vulnerability in twig/twig 2.14.3

### ISSUE THREAD

**Issue by mihob** [craftcms/cms#12033]
### What happened?

There seems to be a vulnerability in the currently used twig version

![image](https://user-images.githubusercontent.com/48485580/193271965-0ac2e7b7-502f-4818-aca9-eb0f3cdb9f78.png)

This should also affect version 4.x of Craft, where version 3.3.0 of twig is used.

### Craft CMS version

Craft Pro 3.7.55.2

### PHP version

8.0.22

### Operating system and version

Linux 5.4.0-126-generic

### Database type and version

MySQL 10.5.16

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-35)

### Installed plugins and versions

- Control Panel CSS - 2.4.0
- CP Field Inspect - 1.4.4
- Default Dashboard - 1.0.8
- Enforce password - 1.0.4.2
- Expanded Singles - 1.2.0
- Field Manager - 2.2.5
- ImageOptimize - 1.6.48
- Incognito Field - 1.3.0
- LJ Range Slider - 1.0.0
- Logs - 3.0.5
- Maps - 3.9.4
- Neo - 2.13.15
- Redactor - 2.10.10
- Sentry SDK - 1.1.2
- SEO & Social - 3.4.38

**Comment by angrybrad** [comment]
Craft doesn't use Twig's native filesystem loader, so we're not affected by this.

Security scanners won't be aware of this, however.

For Craft 3, if you `composer update`, it'll bring in the latest Twig release, which should satisfy the scanners.

For Craft 4, we'll bump the Twig version to `~3.4.0` for the next release, which will also satisfy them.

**Comment by brandonkelly** [comment]
Just released Craft 3.7.55.2 and 4.2.5.2 with fixes for this.

Craft 3.7.55.2 now requires Twig `~2.15.3` (previously it was `~2.14.3` which wouldn’t have allowed updating to 2.15.x).

Craft 4.2.5.2 now requires Twig `~3.4.3` (previously `~3.3.0`).
