### ISSUE TITLE
Allow HTML in Label-type Fields and Field Instructions

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1206]
> Created by: Kristen Grote (kristen@madewithloveco.com) on 2015/12/01 23:48:33 +0000
> Votes at time of UserVoice import: 2

-----------------------------------

Sometimes I need to add a link to a field's instructions where the editor can get more information about how to use the field (for example, a link to a time zone converter tool for a date field).

Currently Craft does not allow HTML inside field instructions or label-type fields. I would like to be able to use some basic html, like <b>, <em>, and <a>. Markdown or some other markup language would be fine also.

**Comment by lindseydiloreto** [comment]
Having Markdown in field instructions is great... but doesn't solve all of the problems. It would still be really helpful for the instructions to be able to _fully parse HTML_.

**EXAMPLE:** Links in Markdown `[label](url)` are incapable of opening in a new window. You need to use a standard `<a>` tag for your link to open in a new window.

**Comment by lindseydiloreto** [comment]
To be clear, is the automatic new window thing planned for a future release? Or should we be opening up a separate feature request for it?

There's definitely value in opening outbound links in a new window, I wouldn't want that FR to get lost.

**Comment by lindseydiloreto** [comment]
Brilliant, thanks @brandonkelly!

**Comment by mark-chief** [comment]
This doesn't appear to be a thing in Craft 3.1.15.

`[Create a new form here](/admin/freeform/forms/new).`

**Comment by brandonkelly** [comment]
@mark-chief where are you adding that?

**Comment by knynkwl** [comment]
Is there a status update to this? My links are currently not opening in a new window. I am entering into the `field instruction`

Craft 3.6.6

`[focus point](https://craftcms.com/docs/3.x/assets.html#focal-points)`

**Comment by brandonkelly** [comment]
@knynkwl Just tested locally and it was generally working as expected, with the exception of the info icon tooltips that field instructions are tucked into, when you are editing an element from an element editor HUD. That’s fixed now, and the fix made it into today’s 3.6.7 release.
