### ISSUE TITLE
Copy and Paste into table field

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1207]
> Created by: Keith Mancuso (keith@familiar-studio.com) on 2015/03/11 01:23:26 +0000
> Votes at time of UserVoice import: 2

-----------------------------------

I realize this may be very difficult but if there way anyway to copy from a spreadsheet like google sheets into a table field in craft that would be a huge timesaver.

We've often avoided using table fields because the existing data is already in a long spreadsheet so we'll use a rich text field instead and lose the added functionality of the table field.

Maybe it means i should build a plugin fieldtype based on something like this http://handsontable.com/  which has copy and paste functionality but also other excel like options.  But i would love to see some of this built into the native table field

**Comment by texasbaptists** [comment]
This would save my content manager so much time as we get things in spreadsheets all the time.

**Comment by northamerican** [comment]
need for same reasons! if craft detected cell and row endings accordingly it would be a huge help for content editors.

**Comment by okkedek** [comment]
Yes +1, this would make life much easier for our content managers as well.

**Comment by gertst** [comment]
+1, would help us a lot!

**Comment by keyurshah** [comment]
Hi! Wondering if this can be considered for the future or if there is a plugin that can do this. (With super table as well)

**Comment by brandonkelly** [comment]
Just added this for the next release :)

**Comment by keyurshah** [comment]
That’s great news!! Would it work with supertable as well?

**Comment by brandonkelly** [comment]
No, ST is a separate beast. Not sure it will be easily possible for them to add paste support, since it just renders normal field types within its cells, so no control over how they should handle importing data in the UI.

**Comment by keyurshah** [comment]
Makes sense. Figured that would be trickier
