### ISSUE TITLE
[4.2.5.2]: Table fields not remembering their Default Values row

### ISSUE THREAD

**Issue by dan3e** [craftcms/cms#12071]
### Description

Table fields don’t save deleted rows for their Default Values setting.

### Steps to reproduce

1. Create a Table field
2. Delete the first row of the Default Values settings
3. Save the field

### Expected behavior

Remove the first row of the Default Values.

### Actual behavior

The first row comes back everytime I save

### Craft CMS version

4.2.5.2

### PHP version

8.0.8

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, Thanks for reporting this. It looks like the saving part is working as expected - as in it's actually saving the fact that you don't want any default values to show, but the feedback you get when creating/editing a field is confusing as it always shows at least one default row. I've created a pull request to action this.

**Comment by brandonkelly** [comment]
#12079 has been fixed for the next release!
