### ISSUE TITLE
[3.x]: Error running codeception Acceptance tests with module setting in config/app.php

### ISSUE THREAD

**Issue by yoannisj** [craftcms/cms#12088]
### Description
Running Codeception acceptance tests with modules defined in `config/app.php` throws error `[TypeError] get_class(): Argument #1 ($object) must be of type object, string given`.

To make sure this is not an issue with my project's module configuration, I tried with a fresh Craft-CMS 3.7 install, and could reproduce the error.

### Steps to reproduce

1. Get a fresh Craft-CMS 3.7 installation
_I downloaded the zip file from the [Installation Instructions](https://craftcms.com/docs/3.x/installation.html#downloading-an-archive-file-manually) to get up and running inside a DDEV project._
2. Install Codeception ^4.1 with `composer require codeception/codeception:^4.1 --dev`
_Codeception ^3.1 is not compatible with PHP 8, and I did not manage to setup Craft-CMS tests with Codeception ^5.0._
3. Follow steps to [Setup Tests](https://craftcms.com/docs/3.x/testing/testing-craft/setup.html) for Craft-CMS from the documentation
_To run the example unit test  (steps 4-5), I had to run `composer require codeception/module-yii2:^1.1 --dev` first_
4. Add an example Acceptance test in `tests/acceptance/ExampleCest.php` like so:
```
<?php
namespace yournamespace\tests\acceptance;

class ExampleCest
{
    public function testExample( \AcceptanceTester $I )
    {
        // when
        $I->amOnPage('/admin/login');

        // then
        $I->seeInTitle('Login');
    }
}
```
5. run `php vendor/bin/codecept run acceptance`

### Expected behavior

The acceptance test should run and pass.

### Actual behavior
The `[TypeError] get_class(): Argument #1 ($object) must be of type object, string given` error is thrown.

The `[TypeError] get_class(): Argument #1 ($object) must be of type object, array given` error is thrown if I define the module as an array in `tests/_craft/config/app.php`:
```
   'modules' => [
       'my-module' => [ 'class' => \modules\Module::class ],
   ],
```

The test runs and passes if I comment out the `'modules'` setting altogether in `tests/_craft/config/app.php`.

### Craft CMS version

3.7.55.3

### PHP version

8.0.21

### Operating system and version

Linux 5.10.124-linuxkit (DDEV v1.20.0)

### Database type and version

MySQL 10.4.25 (MariaDB 10.4)

### Image driver and version

Imagick 3.6.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- Element API 2.8.6.1
- codeception/codeception 4.2.2
- codeception/module-yii2 1.1.5
- codeception/module-asserts 1.3.1
- codeception/module-phpbrowser 1.0.3

**Comment by yoannisj** [comment]
I just followed the steps above on a Craft 4.2 insallation, and confirm this is also happening for Craft-CMS 4.x.

**Comment by brianjhanson** [comment]
@yoannisj do you have the `bootstrap` line in your `app.php` file within the `_tests` folder?

The full file should look similar to the following
```php
<?php

use craft\helpers\App;

return [
    'id' => App::env('APP_ID') ?: 'CraftCMS',
    'modules' => [
        'my-module' => \modules\Module::class,
    ],
    'bootstrap' => ['my-module'],
];
```

That being said, not including `bootstrap` in there shouldn't break things (because it doesn't break a normal install). I've opened a PR to address that piece.

**Comment by yoannisj** [comment]
@brianjhanson , no I removed the `'bootstrap' => [ 'my-module' ]` line.

Yes, it does not throw an error in a normal app and I also figured that one might want to define/configure a module that gets loaded inside a test without bootstrapping it.

**Comment by brianjhanson** [comment]
@yoannisj just wanted to note if you add back the `bootstrap` line things should work until #12093 is merged and released. The change over there is super simple so you can also patch it yourself for the time being.

**Comment by brandonkelly** [comment]
This is fixed for the next Craft 3 and 4 releases, via #12093.

**Comment by brandonkelly** [comment]
Craft 3.7.57 and 4.2.8 are out now with the fix. Thanks again!
