### ISSUE TITLE
Craft can’t fetch the `info` table row.

### ISSUE THREAD

**Issue by ostark** [craftcms/cms#12101]
### Description

After running `craft db/restore seed.sql` on a empty database (no tables) I see the following error output:

```
Restoring database backup ... done
Clear data caches? (yes|no) [yes]:yes

Craft can’t fetch the `info` table row.

Clearing cache: Data caches
```

The table actually exists after running the command - further actions work without any issues, but the error message is not the best DX.

### Additional info

- Craft version: 4.2
- PHP version: 8.1
- Database driver & version: mysql 8

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release via #12107.
