### ISSUE TITLE
Translation issue for ITALIAN language 

### ISSUE THREAD

**Issue by vitalijalbu** [craftcms/cms#12108]
### What happened?

Hi, using latest craft cms version, wanted to tell you that there's a translation issue on the bottom of the page
<img width="921" alt="Schermata 2022-10-13 alle 00 01 07" src="https://user-images.githubusercontent.com/40239902/195456579-36d0d8ad-f22e-41f8-adb4-fbcb230b741e.png">

There's: **Aggiornato** which means **Updated** to...
Must be **Aggiorna** (have no pro version yet), meaning **Update** it
So the correct one is : _**Aggiorna a Craft Pro**_

### Craft CMS version

4.2.7

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks! Fixed for the next Craft 3 and 4 releases.

If you’d like to contribute translation edits directly, you can do so from https://translate.craftcms.com/.
