### ISSUE TITLE
Craftcms Website broken link 

### ISSUE THREAD

**Issue by tigerchick** [craftcms/cms#12100]
### What happened?

Not an issue with Craft itself but just a heads up that there's a broken link on the craft website:
On the "Taxes & Shipping" item here: https://craftcms.com/features#build-and-manage-your-store it links to https://craftcms.com/features/all#tax-shipping-apis
That anchor doesn't exist (and so should probably be this instead: https://craftcms.com/features/all#taxes-shipping)
Apologies if this is the wrong place to post this.

### Craft CMS version

4

### Installed plugins and versions

-

**Comment by kennethormandy** [comment]
[This is fixed now!](https://craftcms.com/features#build-and-manage-your-store) Thanks for catching that, and opening the issue.
