### ISSUE TITLE
[4.x]: "Your session has ended." modal appearing when logged out

### ISSUE THREAD

**Issue by flynnt** [craftcms/cms#12121]
### Description
On a completely fresh Craft install, I noticed that the "Your session has ended." modal is appearing even though I am fully logged out. Attempts to enter the admin password in the form within that modal lead to a "Request missing required body param" error, presumably because there's not actually a session.

It appears that the `admin/actions/users/session-info&dontExtendSession=1` is being called every 60 seconds, which is normal when a user is logged in, but in this case it's being called when a user is logged out as well.

### Steps to reproduce

1. Install Craft 4 via `composer create-project craftcms/craft`.
2. Accept the prompts to initialize and install Craft.
3. Go to the admin URL.
4. Wait 60 seconds.
5. See modal.

I tested this on a fresh install in DDEV as well as Valet.

### Expected behavior
The session expiration modal does not appear for users that are not logged in.

### Actual behavior
The session expiration modal appears even when a user it not logged in.

### Craft CMS version

4.2.7

### PHP version

8.1.10

### Operating system and version

macOS Monterey 12.6

### Database type and version

MySQL 5.7.23

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-48)

### Installed plugins and versions

None.

**Comment by brandonkelly** [comment]
Thanks for reporting! This is fixed for the next Craft 3 and 4 releases via #12129.

**Comment by brandonkelly** [comment]
Craft 3.7.57 and 4.2.8 are out now with that fix. Thanks again!
