### ISSUE TITLE
[4.x]: Non-required money fields can't store zero

### ISSUE THREAD

**Issue by tremby** [craftcms/cms#12122]
### Description

I have an optional ~~number~~ money field. Craft seems to refuse to store zero -- it stores and returns null instead.

I find this unexpected because the UI shows blank and zero as different states (blank vs 0.00), and even offers a control (a little x) to turn a number back into the blank state.

It also means I need to add a separate boolean field if I need to distinguish between 0 and null.

In case it's important, this number field is part of a Neo block.

### Steps to reproduce

1. Make an optional number field
2. Edit an entry which uses that field
3. See its default state is totally blank. Save like this or get back to this state by clicking the little x in there.
4. Get field contents from Graphql or wherever -- result A
5. Click in it and see 0.00. Save like this or get back to this state by typing a zero.
6. Get field contents from Graphql or wherever -- result B
7. Go to edit the field again, see that it is once again totally blank.

### Expected behavior

- Result A is `null`
- Result B is `0`

### Actual behavior

Both results are `null`.

### Craft CMS version

4.2.5.1

### PHP version

8.1.10

### Operating system and version

Linux

### Database type and version

Postgres 14

### Image driver and version

n/a

### Installed plugins and versions

- Amazon S3 2.0.1
- Control Panel CSS 2.5.0
- Embedded Assets 3.0.5
- Feed Me 5.0.4
- Formie 2.0.12
- Imager X 4.1.5
- Maps 4.0.3
- Navigation 2.0.6
- Neo 3.3.9
- Redactor 3.0.2
- Retour 4.1.3
- SEOmatic 4.0.8
- Scout 3.0.0
- Sentry Logger 4.1.1
- Typed link field 2.1.4
- Workflow 2.0.0-beta.7

**Comment by i-just** [comment]
Hi, thanks for reaching out. I'm having trouble replicating this problem. In step 7, do you mean that once you go back to edit the entry that contains this number field, the field value is showing to you as blank, even though you have previously inputted 0 and saved the entry with that value?

**Comment by tremby** [comment]
Yes. If I save a zero, then go to edit again, it's a blank.

**Comment by i-just** [comment]
Thanks for clarification. I still can't replicate it, even with all the plugins you're using installed. Just to confirm, when you edit the entry, do you do that in the control panel or via your own application?

**Comment by brandonkelly** [comment]
> I find this unexpected because the UI shows blank and zero as different states (blank vs 0.00), and even offers a control (a little x) to turn a number back into the blank state.

Number fields don’t have an `x` button.

<img width="260" alt="A Number field using the built-in field type, with a value of 0 entered. There is only a text input, with no added UI" src="https://user-images.githubusercontent.com/47792/195884766-777665f6-402c-410c-ac0b-ca06b20a1b37.png">

Maybe you’re using something besides the built-in Number field type?

**Comment by tremby** [comment]
> Number fields don’t have an `x` button.
> 
> <img alt="A Number field using the built-in field type, with a value of 0 entered. There is only a text input, with no added UI" width="260" src="https://user-images.githubusercontent.com/47792/195884766-777665f6-402c-410c-ac0b-ca06b20a1b37.png">
> 
> Maybe you’re using something besides the built-in Number field type?

Ah, you're right! Sorry about that. Another developer on the team set this field up and I blindly assumed it was a standard number field.

It's a "money" field.

> Just to confirm, when you edit the entry, do you do that in the control panel or via your own application?

Control panel.

**Comment by i-just** [comment]
Perfect, thank you for the update. I can certainly replicate this issue now. I've pushed a PR for this.

**Comment by brandonkelly** [comment]
Fixed for the next release via #12132!

**Comment by brandonkelly** [comment]
Craft 4.2.8 is out now with that fix.

**Comment by tremby** [comment]
Thank you all.
