### ISSUE TITLE
[3.x]: An internal server error occurred.

### ISSUE THREAD

**Issue by handplant** [craftcms/cms#12133]
### Description
After I updated Craft CMS 3, I get the following PHP error in CP

```
The file or directory to be published does not exist:
/vendor/craftcms/cms/src/web/assets/focusvisible/dist in vendor/yiisoft/yii2/web/AssetManager.php:467
```

### Craft CMS version

3.7.56

### PHP version

7.4.29

### Installed plugins and versions

-

**Comment by handplant** [comment]
Downgrade to version 3.7.55.3 and it works again.

**Comment by brandonkelly** [comment]
Thanks for reporting that. I’m not able to reproduce but suspect it has something to do with CP resource caching. Should be fixed for the next release.

If you’d like to test, change your `craftcms/cms` requirement in `composer.json` to `v3.x-dev as 3.7.56` and run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.7.57 and 4.2.8 are out now with that fix.
