### ISSUE TITLE
[4.x]: Assets being renamed on non-primary sites

### ISSUE THREAD

**Issue by tommysvr** [craftcms/cms#12142]
### Description
After uploading an asset via 'Upload Files' or dragging it directly on the field, the asset is renamed to a string like `Asset634de...` on non-primary sites. Similar to #11530, but specifically now affecting multisite.

### Steps to reproduce

1. Upload an asset directly to the field [either on the primary site or a secondary site]
2. View the asset in the non-primary site and the asset will have been renamed

### Expected behavior
Asset is not renamed and is the same name across all sites

### Actual behavior
Asset is renamed on non-primary sites

### Craft CMS version

4.2.7

### PHP version

8.1

### Database type and version

Maria DB 10.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Fixed via #12145

**Comment by brandonkelly** [comment]
Craft 4.2.8 is out now with that fix.
