### ISSUE TITLE
[3.x]: Public User Registration Default Group not Assigned

### ISSUE THREAD

**Issue by cherrykoda** [craftcms/cms#12143]
### Description

When using the built-in settings to assign public user registrants to a default group, the group is not being assigned and the user is left in the primary list. 

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/3789834/196329092-d6ea4f53-14ad-4692-9633-8561d842b163.png">

<img width="744" alt="image" src="https://user-images.githubusercontent.com/3789834/196329125-3b4530d6-bea2-465f-8c19-85d28a658edf.png">

### Steps to reproduce

1. Setup public registration in Settings > Users
2. Assign a user group
3. Create a frontend form for registration using username, pw (we also have some custom fields, ex. pronouns)
4. register a new user
5. Check the user's assignment in the users panel

### Expected behavior

The user should be inside of the specified group for public registrants.

### Actual behavior

The user is not assigned to any group.

### Craft CMS version

3.7.56

### PHP version

8.1.11

### Operating system and version

Mac OS (latest)

### Database type and version

MariaDB (MySQL 10.8.3)

### Image driver and version

GD 8.1.11

### Installed plugins and versions

<img width="623" alt="image" src="https://user-images.githubusercontent.com/3789834/196329265-933f8af4-178f-4668-bfba-57fdc5e89d32.png">

**Comment by i-just** [comment]
Hi, thanks for getting in touch. The only way I can replicate it, is if I try to publicly register while also logged into admin in the same browser. Could you please confirm if this still happens if you log out of admin or use private window to publicly register?

**Comment by cherrykoda** [comment]
yup, just confirmed this is happening if already signed in as an admin. Would it make sense to make the form consistently assign the group? I'm not sure why it behaves differently if the form is used by an admin. This is less of an issue as it only really impacted testing, but I could see an admin trying to help a new user get setup and forgetting they're logged in.

**Comment by i-just** [comment]
Thanks for confirming. It is working as expected then. Craft only differentiates between normal registration and public registration based on whether someone is already logged in.
