### ISSUE TITLE
[3.x]: Entry search very slow

### ISSUE THREAD

**Issue by dgsiegel** [craftcms/cms#12147]
### Description

Our site has about 20.000 entries currently. More are planned and we're soon looking towards 200.000 entries. 

About 19.000 entries (section `object`) are quite similar and feature similar keywords. In our example one of those keywords is e.g. `Bleiplakette` which most entries have in their title or in a body field.

Searching with an arbitrary keyword is quite slow, but bearable (3-4s). But if we search for `Bleiplakette` searching takes well over 200 seconds.

This is a minimal example of our search page (we're also using pagination, but it doesn't seem to make a difference whether that is enabled or not):

```
{% set searchQuery = craft.app.request.getParam("q", null) %}

{% set pageEntries = craft.entries()
  .search(searchQuery)
  .orderBy("score")
  .all()
%}

{% for entry in pageEntries %}
  {{ entry.title}}<br>
{% endfor %}
```

We have 2 sites in our Craft installation. Our `searchindex` has 777250 records.

Interestingly, using the search box at /admin/entries/object is comparably quite fast with 5-6 seconds.

Looking at the profiling tools I can see that the actual database search takes about 5-6 seconds:

```
SELECT *
FROM `searchindex`
WHERE ((`keywords` LIKE '% bleiplakette%')) AND (`siteId`=1) AND (`elementId` IN (SELECT `elements`.`id`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`, `structureelements`.`structureId`
FROM `elements` `elements`
INNER JOIN `entries` `entries` ON `entries`.`id` = `elements`.`id`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `content` `content` ON (`content`.`elementId` = `elements`.`id`) AND (`content`.`siteId` = `elements_sites`.`siteId`)
LEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `elements`.`id`) AND (EXISTS (SELECT *
FROM `structures`
WHERE (`id` = `structureelements`.`structureId`) AND (`dateDeleted` IS NULL)))
WHERE (`elements_sites`.`siteId`=1) AND (`elements`.`archived`=FALSE) AND (((`elements`.`enabled`=TRUE) AND (`elements_sites`.`enabled`=TRUE)) AND (`entries`.`postDate` <= '2022-10-18 13:19:59') AND ((`entries`.`expiryDate` IS NULL) OR (`entries`.`expiryDate` > '2022-10-18 13:19:59'))) AND (`elements`.`dateDeleted` IS NULL) AND (`elements`.`draftId` IS NULL) AND (`elements`.`revisionId` IS NULL)) `subquery`
INNER JOIN `entries` `entries` ON `entries`.`id` = `subquery`.`elementsId`
INNER JOIN `elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `content` `content` ON `content`.`id` = `subquery`.`contentId`
LEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `subquery`.`elementsId`) AND (`structureelements`.`structureId` = `subquery`.`structureId`)))
```
However there is another query which takes about 190-200 seconds. Strange enough this query lists all 19.000 entry id's: 
[long-query.txt](https://github.com/craftcms/cms/files/9811193/long-query.txt)

Both [#986](https://github.com/craftcms/cms/issues/9867) as well as https://github.com/craftcms/cms/issues/11403 seem to be related, but all suggested solutions do not seem to improve the speed:

- The table engine for the `searchindex` table is already InnoDB
- `OPTIMIZE TABLE searchindex` takes a long time and then prints the following, but does not improve the speed:
```
+-----------------+----------+----------+-------------------------------------------------------------------+
| Table           | Op       | Msg_type | Msg_text                                                          |
+-----------------+----------+----------+-------------------------------------------------------------------+
| bnm.searchindex | optimize | note     | Table does not support optimize, doing recreate + analyze instead |
| bnm.searchindex | optimize | status   | OK                                                                |
+-----------------+----------+----------+-------------------------------------------------------------------+
```
- `mysqlcheck -u user -p pwd -o --all-databases` does the same as the command above
- Using the following config does not seem to make a difference:
```
return [
    'components' => [
        'search' => [
            'useFullText' => false,
        ],
    ],
];
```
- I've attached the output of `SHOW VARIABLES` here: [mysql-variables.txt](https://github.com/craftcms/cms/files/9811023/mysql-variables.txt)

I am out of ideas... What else is there left to try? Happy to share my db if it helps!

### Steps to reproduce

1. Add 20.000 entries with similar keywords
2. Use the twig code above to search for such a keyword
3. Wait

### Expected behavior

A search as fast as the backend one

### Actual behavior

Takes a long time.

### Craft CMS version

Craft Pro 3.7.56

### PHP version

8.1.11

### Database type and version

mysql  Ver 15.1 Distrib 10.5.16-MariaDB, for Linux (x86_64) using  EditLine wrapper

**Comment by brandonkelly** [comment]
Any chance you can send a database backup and your Composer files into support@craftcms.com?

**Comment by dgsiegel** [comment]
> Any chance you can send a database backup and your Composer files into [support@craftcms.com](mailto:support@craftcms.com)?

Sure, just sent it.

Another thing I just noticed is that the search query seems to be executed twice: 
![image](https://user-images.githubusercontent.com/4396895/196524083-f38f7a5f-27a5-4404-bea7-d5ff539c2499.png)

 Only `postDate` and `expiryDate` seem to differ - could that be a reason why the huge query gets executed?

**Comment by vitalijalbu** [comment]
> On further investigation, I've found that adding `limit()` to the query will speed up the search:
> 
> ```
> {% set pageEntries = craft.entries()
>   .search(searchQuery)
>   .orderBy("score")
>   .limit(N)
>   .all()
> %}
> ```
> 
> Where N:
> 
> * 100: ~3-4s
> * 1000: ~5-6s
> * 10000: ~5-6s
> * 100000: ~11-12s (we have less than 20.000 entries)
> 
> Removing `limit()` will result in over 200 seconds.
> 
> However adding pagination like this
> 
> ```
> {% paginate craft.entries()
>   .search(searchQuery)
>   .orderBy("score")
>   .limit(1000)
>     as pageInfo, pageEntries
> %}
> ```
> 
> will also result in over 200 seconds, hence we can't really use this approach on our site.

really curious about 10k entries, lol. in my craftcms 29 entries takes 4secs, but 10k how much will be? :D

**Comment by brandonkelly** [comment]
@vitalijalbu Sounds like there’s something wrong with your setup. No way Craft should be taking 4 seconds for an install that only has 29 entries!

**Comment by dgsiegel** [comment]
@angrybrad  @brandonkelly I've played around with the different slow queries, and here are a few interesting findings. I've focused e.g. on this one:

```
SELECT COUNT(*)
FROM (SELECT distinct `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`
FROM `elements` `elements`
INNER JOIN `entries` `entries` ON `entries`.`id` = `elements`.`id`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `content` `content` ON (`content`.`elementId` = `elements`.`id`) AND (`content`.`siteId` = `elements_sites`.`siteId`)
WHERE (`entries`.`sectionId`=8) AND (`elements_sites`.`siteId`=1) AND (`elements`.`archived`=FALSE) AND (((`elements`.`enabled`=TRUE) AND (`elements_sites`.`enabled`=TRUE)) AND (`entries`.`postDate` <= '2022-10-24 10:50:59') AND ((`entries`.`expiryDate` IS NULL) OR (`entries`.`expiryDate` > '2022-10-24 10:50:59'))) AND (`elements`.`dateDeleted` IS NULL) AND ((`elements_sites`.`uri` NOT LIKE 'press/%') AND (`elements_sites`.`uri` NOT LIKE 'presse/%')) AND (`elements`.`draftId` IS NULL) AND (`elements`.`revisionId` IS NULL) AND (`elements`.`id` IN (130178, 129625, 130091, [10k more id's...]))) `subquery`
INNER JOIN `entries` `entries` ON `entries`.`id` = `subquery`.`elementsId`
INNER JOIN `elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `content` `content` ON `content`.`id` = `subquery`.`contentId`;
```

This query needs about 45 seconds on different systems I've tried it on. One way to optimize it is to have less `id`s in the subquery (kind of what `limit` does as described here https://github.com/craftcms/cms/issues/12147#issuecomment-1282893549). That's obviously not the goal.

The other interesting finding is that just running the subquery alone is very fast (e.g. `9259 rows in set (0.088 sec)`). However the 4 joins at the end (`INNER JOIN entries entries ON entries.id = subquery.elementsId ...`) make it very slow. Hence removing those will also make the query very fast (and also give the same result, as it's just a simple `COUNT(*)`.

So it seems to boil down to comparing a large subquery without indexes with joined tables. 

Just for fun I've added a `DISTINCT` to the subquery:

```
SELECT COUNT(*)
FROM (SELECT DISTINCT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`
FROM `elements` `elements`
INNER JOIN `entries` `entries` ON `entries`.`id` = `elements`.`id`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `content` `content` ON (`content`.`elementId` = `elements`.`id`) AND (`content`.`siteId` = `elements_sites`.`siteId`)
WHERE (`entries`.`sectionId`=8) AND (`elements_sites`.`siteId`=1) AND (`elements`.`archived`=FALSE) AND (((`elements`.`enabled`=TRUE) AND (`elements_sites`.`enabled`=TRUE)) AND (`entries`.`postDate` <= '2022-10-24 10:50:59') AND ((`entries`.`expiryDate` IS NULL) OR (`entries`.`expiryDate` > '2022-10-24 10:50:59'))) AND (`elements`.`dateDeleted` IS NULL) AND ((`elements_sites`.`uri` NOT LIKE 'press/%') AND (`elements_sites`.`uri` NOT LIKE 'presse/%')) AND (`elements`.`draftId` IS NULL) AND (`elements`.`revisionId` IS NULL) AND (`elements`.`id` IN (130178, 129625, 130091, [...]))) `subquery`
INNER JOIN `entries` `entries` ON `entries`.`id` = `subquery`.`elementsId`
INNER JOIN `elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `content` `content` ON `content`.`id` = `subquery`.`contentId`;
```

This will also run very fast (`1 row in set (0.176 sec)`). So I've added a `->distinct()` to the subquery builder in https://github.com/craftcms/cms/blob/develop/src/elements/db/ElementQuery.php#L1297 and can confirm that the minimal search example in the first post will run fast again (total page processing time 1-2 seconds without any caches). Obviously I have no idea what else will break by adding that line...

**Comment by khalwat** [comment]
related: https://github.com/MariaDB/mariadb-docker/issues/478

**Comment by dgsiegel** [comment]
I finally have found the culprit thanks to the nice folks over at https://github.com/MariaDB/mariadb-docker/issues/478. On our systems we hadn't touched  `character-set-server` and `collation-server` which were set to the default values of  `character-set-server=latin1` and `collation-server=latin1_swedish_ci`.

By setting `character-set-server=utf8mb4` and `collation-server=utf8mb4_general_ci`, the query time of 200 seconds will reduce itself to a few seconds: `22004 rows in set (1,787 sec)`

Docker had set those values automatically and so the query inside DDEV or any other Docker environment would be quite fast.

Thanks for all the help!

**Comment by angrybrad** [comment]
Fantastic debugging @dgsiegel and @RitterKnightCreative!
