### ISSUE TITLE
[4.x]: discard provisional draft from the element you're duplicating with "save as a new {type}"

### ISSUE THREAD

**Issue by i-just** [craftcms/cms#12165]
### Description
If you edit existing entry (create a provisional draft) and then click “Save as a new entry”, it should apply your changes to the new entry and discard them from the existing one

### Craft CMS version

4.x

### Installed plugins and versions

-

### Related issues
#11959 
#12102 
#10204

**Comment by brandonkelly** [comment]
#12167 has been merged for 4.3 🎉
