### ISSUE TITLE
[4.x]: Generate Pending Image Transform task will keep trying to regenerate broken images

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#12170]
### Steps to reproduce

1. Fresh install of Craft 4.2.8.
2. Add a local filesystem and volume.
3. Go to Settings->Users->Settings in the control panel and make sure the User Photo Location is set to the local volume.
4. Go to `admin/myaccount` and upload a user photo
5. On your local filesystem, delete the file you just uploaded and remove the generated transform folders to force Craft to try to re-generate them.
6. Browse different pages in the control panel (Settings, Utilities, Assets, Dashboard, etc.) and notice that a "Generate Pending Image Transform" job gets added to the queue on every request.

This is a simple example, but broken thumbnails for entries, assets, etc., can cause the queue to back up.

### Expected behavior

Failed transforms won't try to keep re-generating.

### Actual behavior

Failed transforms try to re-generated on every request.

### Craft CMS version

4.2.8

### PHP version

8.0

### Operating system and version

n/a

### Database type and version

n/a

### Image driver and version

Imagick

### Installed plugins and versions

None.

**Comment by brianjhanson** [comment]
👋 This was already requested in #11970 and fixed as of 4.3 via 0583fd3536eb63573a5874734ebe75dda4d72ffc.
