### ISSUE TITLE
When an image is deleted but used in Entries [4.x]: 

### ISSUE THREAD

**Issue by jomotion11** [craftcms/cms#12172]
### Description
A client was editing content and deleted an image from Assets that was being used across a few page entries. This was not good because the image field was important so the page errored because the image was missing.

### Expected behavior
It would be good to have a message or warning before an image is deleted. It could prompt saying 'replace with another image' 

### Actual behavior
No warning, it goes ahead with the deletion 

### Craft CMS version

4.2.2

### PHP version

8.0.19

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-16)

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, We are planning something in that area for Craft 5. You can follow the discussion here: #11934
