### ISSUE TITLE
[4.x]: Drafts with custom propagation doesn't work

### ISSUE THREAD

**Issue by bartutt** [craftcms/cms#12176]
### Description
Custom propagation method for matrix blocks doesn't work after update to Craft 4. We have section with matrix blocks with custom propagation key:

{section.handle == 'contact' ? site.handle : ''}

It works fine as long as you don't save entry (f. eks "ctrl + s").

![craft4](https://user-images.githubusercontent.com/72630492/197469358-8ea7318b-bd08-4089-adcd-bbc5475046e1.gif)

### Steps to reproduce

1. Create matrix field with some blocks.
2. Add custom propagation to it.
3. Create entry and add block, save it and try edit again.

### Expected behavior
Matrix block should be saved.

### Actual behavior
Matrix block are not saved.

### Craft CMS version

4.2.8

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks! We were able to track this down, and it’s now fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 4.3.0"` and run `composer update`.

**Comment by brandonkelly** [comment]
Craft 4.3.1 has been released with a fix for this.
