### ISSUE TITLE
[4.x]: Mutex configuration for redis doesn't respect namePrefix

### ISSUE THREAD

**Issue by jishi** [craftcms/cms#12181]
### Description
I have configured redis as mutex store and verified that I indeed get mutex keys momentarily. However, I re-use my redis cluster for multiple installs, and want to separate installs via database, and each database should use prefixes for keys to separate different type of data (sessions and mutex locks)

### Steps to reproduce

1. configure mutex via redis using:

```
'mutex' => [
            'mutex' => 'yii\redis\Mutex',
            'namePrefix' => 'mutex_',
        ],
```

### Expected behavior
Keys for mutex locks should be prefixed

### Actual behavior
Keys are not prefixed, they only consists of some guid/uuid

### Craft CMS version

4.2.8

### PHP version

8.0.22

### Operating system and version

Linux 5.10.124-linuxkit

### Database type and version

Redis (latest ElastiCache in AWS)

### Installed plugins and versions

- Amazon S3 2.0.1
- Control Panel CSS 2.5.0
- Redactor 3.0.2
- Redactor Custom Styles 4.0.2
- Super Table 3.0.1
- Typed link field 2.1.4

**Comment by brandonkelly** [comment]
Your `namePrefix` is getting included when defining mutex keys, but `yii\redis\Mutex` is running the whole thing through `md5()`, so it’s getting obfuscated. Two separate installs should still be getting two separate keys though, so long as each has a unique `namePrefix`.

Alternatively, `yii\redis\Mutex` has its own [`keyPrefix`](https://www.yiiframework.com/extension/yiisoft/yii2-redis/doc/api/2.0/yii-redis-mutex#$keyPrefix-detail) property, which will get applied [before the `md5()`-d key](https://github.com/yiisoft/yii2-redis/blob/master/src/Mutex.php#L163), so if you use that instead, it will be much more obvious that each install is getting its own set of mutex locks.

```php
'mutex' => [
    'mutex' => [
        'class' => 'yii\redis\Mutex',
        'keyPrefix' => 'mutex_',
    ],
],
```
