### ISSUE TITLE
[4.3.0]: Datepicker-zh.js 404 (Not Found) when the language is Chinese

### ISSUE THREAD

**Issue by ivesho** [craftcms/cms#12194]
### Description
Datepicker-zh.js can't find, when user's language is Chinese.
![image](https://user-images.githubusercontent.com/48641341/197931056-7218f4ce-77b6-4640-b599-1fc661f189cc.png)
![image](https://user-images.githubusercontent.com/48641341/197929385-e8507af2-c265-4d61-bd5b-d0261511ca7f.png)
![image](https://user-images.githubusercontent.com/48641341/197930880-edd3b386-279b-46d1-a6f9-786c794d5440.png)

### Steps to reproduce
1.Change control panel language to chinese.

### Expected behavior
Datepicker-zh.js should be found

### Actual behavior
Datepicker-zh.js not found

### Craft CMS version

Craft Pro 4.3.0

### PHP version

8.1.8

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.59 and 4.3.1 have been released with that fix.
