### ISSUE TITLE
[4.x]: Numbers in a plain text field on an element index page get numeric formatting applied

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#12205]
### Steps to reproduce

1. Use a fresh install of the latest 4.3.0 release.
2. Create a Plain Text field... let's call it `SKU`
3. Create a channel section... let's call it `Product`
4. Add `SKU` to `Product`'s field layout.
5. Create an entry in `Product` and give the `SKU` a numeric value: `356041`
6. Save the entry
7. Add `SKU` to the entry index view via a custom source
8. Notice local-specific numeric formatting is applied

![CleanShot 2022-10-26 at 16 35 29](https://user-images.githubusercontent.com/61869/198158347-c546d55e-38f1-4844-9682-82eb5280f36f.png)

If you add a letter (i.e. 356a041) numeric formatting doesn't get applied.

This doesn't happen on the latest Craft 3.7 release, so this is a regression.

### Expected behavior

Numeric formatting does not get applied to plain text fields on element index pages for plain text fields.

### Actual behavior

It does get applied.

### Craft CMS version

4.3.0

### PHP version

8.1

### Operating system and version

macOS

### Database type and version

MySQL 8.1

### Image driver and version

n/a

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Fixed in 4.3.1

**Comment by yingban** [comment]
@brandonkelly Thanks!
