### ISSUE TITLE
Use Illuminate\Support\Collection (e.g. for ElementCriteriaModel, Element queries)

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1220]
> Created by: Timothy Kelty (timkelty@gmail.com) on 2015/04/02 12:33:05 +0000
> Votes at time of UserVoice import: 2

-----------------------------------

https://laravel.com/api/5.1/Illuminate/Support/Collection.html

Collections (use Illuminate\Support\Collection) are really great to work with. I use this in lieu of native array functions for the readability, consistency, and the fluid interface in any Craft plugins I write.

I would be cool if Craft returned these for things like ElementCriteriaModel results and other array-like results.

**Comment by brandonkelly** [comment]
Closing this in favor of #2112
