### ISSUE TITLE
[3.x]: Custom module returns: Not instantiable – yii\di\NotInstantiableException Failed to instantiate component or class "modules\controlpanelmodule\ControlPanelModule".

### ISSUE THREAD

**Issue by bwatabu55** [craftcms/cms#12215]
### Description
I have an existing Craft CMS 3 site already running fine with one module installed. I tried to add a second module by duplicating the file structure of the previous module and renamed the namespace and class name. Then I added the new `psr-4` record in the `composer.json` file, and the new bootstrap record in `config/app.php` file. After running `composer dump-autoload`, I receive the errors:

```
Not instantiable – yii\di\NotInstantiableException Failed to instantiate component or class "modules\controlpanelmodule\ControlPanelModule".

Caused by: ReflectionException
Class modules\controlpanelmodule\ControlPanelModule does not exist
```

### Steps to reproduce

1. ControlPanelModule.php
![Screen Shot 2022-10-27 at 7 55 18 PM](https://user-images.githubusercontent.com/60369957/198513681-6abb2d0d-3c09-44df-9caf-5ca8b2beca8c.png)

2. composer.json

```
	"autoload": {
		"psr-4": {
			"modules\\bdimodule\\": "modules/bdimodule/src/",
			"modules\\controlpanelmodule\\": "modules/controlpanelmodule/src/"
		}
	},
```
3. app.php

```
    'modules' => [        
        'bdi-module' => [
            'class' => \modules\bdimodule\BDIModule::class,
        ],
        'control-panel-module' => [
            'class' => \modules\controlpanelmodule\ControlPanelModule::class,
        ],    
    ],
    'bootstrap' => ['bdi-module', 'control-panel-module'],
```
4. modules folder
![Screen Shot 2022-10-27 at 8 05 37 PM](https://user-images.githubusercontent.com/60369957/198515088-e695f10f-1b05-4ddf-9957-d79a2f1280a2.png)

### Expected behavior
- ControlPanelModule class supposed to load after running `composer dump-autoload` similar to BDIModule if its using similar structure/setup

### Actual behavior

- The "BDIModule" functions/loads fine
- Removing 'control-panel-module' in bootstrap line removes error

### Craft CMS version

3.7.26

### PHP version

7.4.28

### Database type and version

mysql

### Installed plugins and versions

"angellco/spoon": "3.6.1",
"barrelstrength/sprout-fields": "3.8.5",
"barrelstrength/sprout-forms": "3.13.8",
"barrelstrength/sprout-forms-google-recaptcha": "^1.4",
"barrelstrength/sprout-reports": "1.5.12",
"clearbold/craft-campaignmonitor-service": "1.0.13",
"craftcms/aws-s3": "1.3.0",
"craftcms/cms": "3.7.26",
"craftcms/commerce": "3.4.9.3",
"craftcms/feed-me": "4.4.1.1",
"craftcms/redactor": "2.8.8",
"digital-pros/commerce-authorize": "1.5.1",
"doublesecretagency/craft-smartmap": "3.3.6",
"lukeyouell/craft-sentry": "1.5.1",
"nystudio107/craft-cookies": "1.1.15",
"nystudio107/craft-retour": "3.1.68",
"nystudio107/craft-vite": "^1.0.17",
"olivierbon/craft-squeeze": "1.1.2",
"topshelfcraft/environment-label": "3.2.0",
"verbb/super-table": "2.7.0",
"viget/craft-sidebar-toggle": "3.0.2",
"viget/craft-video-embed": "1.2.1",
"viget/craft-viget-base": "2.0.0",
"viget/dimensions": "2.0.0",
"viget/pricing-tiers": "1.1.0",
"vlucas/phpdotenv": "^3.4.0",
"yiisoft/yii2-redis": "^2.0"

**Comment by i-just** [comment]
Hi, thanks for reaching out. This can happen if there's a type-o somewhere in your module or if the `ControlPanelModule.php` is not located in `modules/controlpanelmodule/src/` (where you told composer it should be). I don't see any type-os or anything out of order in the info you provided, but my first suggestion would be to tripple check that it all matches in your source code.

**Comment by brandonkelly** [comment]
Closing for now but let us know if you need further assistance, @bwatabu55!

**Comment by bwatabu55** [comment]
Thanks @brandonkelly, I am still experiencing the mentioned issues above. Is there anything else other than the `app.php` and the `composer.json` files that need to be updated? 

I even tried to take the working `bdi-module` in my example above and tried to install it into another working local Craft project with other custom modules that functions proplery. I tried to mimic the configurations made in the `app.php` and the `composer.json` files for the `bdi-module`, but still experience the `NotInstantiableException` exception.
