### ISSUE TITLE
[4.x]: Site status not reflected in site switcher

### ISSUE THREAD

**Issue by olsp** [craftcms/cms#12217]
### Description
I have two site groups with two sites in them each to represent different languages. In one of the groups, one language should not be available yet. Therefore I set the status for it to "inactive". In the list of the sites this site has now a white circle next to it while the others have green ones.

When editing an entry, I have the option to switch site  with the button next to the tile. When I click it, I get a list of sites sorted by group. Next to the name of the site is also the status indicator. But it shows a green circle for all the sites, also the one which I set to inactive.

### Craft CMS version

4.3.1

**Comment by i-just** [comment]
Hi, thanks for reaching out. This is actually working as intended. The statuses in the sites dropdown you see when editing an entry, reflect status of that entry for each site that's allowed to have that entry. For example, if you were to to disable the entry you're editing for one of the sites, save it and then look at the sites dropdown again, you'll see that the indicator will change to "disabled" (white circle).

Hope this helps!
