### ISSUE TITLE
[4.x]: Layout issues when asset fields have many elements

### ISSUE THREAD

**Issue by samueljonasson** [craftcms/cms#12230]
### Description
Layout issues when asset fields have many elements

### Steps to reproduce
Add enough elements to an asset field so that they can't fit in one row 

### Expected behavior
Elements should properly arrange themselves in a grid layout.

### Actual behavior
![layout-issues](https://user-images.githubusercontent.com/1074267/199056937-b2304755-a909-46ae-a291-ffd2df47a381.png)

### Craft CMS version

4.3.1

### PHP version

8.1.9

### Operating system and version

Linux 4.19.0-21-cloud-amd64

### Database type and version

MySQL 10.4.25

### Image driver and version

GD 8.1.9

**Comment by brandonkelly** [comment]
Thanks for reporting! That’s now fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.3.2 is out with that fix.
