### ISSUE TITLE
[4.x]: Overflow issues with non-truncated asset filenames

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#12237]
### Description

Non-truncated asset file titles (introduced in Craft 4.3.0) overflow the thumbnail container for assets with titles generated from long filenames without spaces, in assets fields with the "Large Thumbnails" view mode.

![CleanShot 2022-11-01 at 00 47 27](https://user-images.githubusercontent.com/298510/199130083-83ae7af9-c82c-40b5-9f74-cd1c70b9d512.png)

### Steps to reproduce

1. Upload some assets with filenames like `01-8_00b7bee5f0ccc56c92ea1d9feec27651.jpg`, `01-1_c614d82f9bafa22f923dcd8bc8073adc.jpg` or `01-3_1ae57606c450a364805c3d61f5581833.jpg`, and add them to an Assets field with its View Mode setting set to "Large Thumbnails".

### Craft CMS version

4.3.1

### PHP version

8.1.1

### Installed plugins and versions

- None

**Comment by brandonkelly** [comment]
Fixed for the next release, thanks for reporting!

**Comment by brandonkelly** [comment]
Craft 4.3.2 is out with that fix.
