### ISSUE TITLE
[4.3]: element index footer not visible when debug toolbar enabled 

### ISSUE THREAD

**Issue by lukas-jansen** [craftcms/cms#12242]
### Description
Now that the footer on the element indexes is fixed to the bottom it isn't visible/clickable when you have the debug toolbar enabled in the CP

### Steps to reproduce

1. Enable the debug toolbar for the CP
2. Go to an element index page

### Expected behavior
Some extra padding should be added when the debug toolbar is enabled

### Craft CMS version

4.3.1

### PHP version

8.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release via #12244.

**Comment by brandonkelly** [comment]
Craft 4.3.2 is out with that fix.
