### ISSUE TITLE
[4.x]: Sorting element indexes does nothing when the search has been used

### ISSUE THREAD

**Issue by FlorisDerks** [craftcms/cms#12256]
### Description

Since v4.3 it seems that sorting an element does not work when it's within the results of a keyword search.

### Steps to reproduce

1. Go to a element index
2. Search for some term in the search bar
3. Try to order the results by publication-date (by using the dropdown in het top-right or by clicking the column header)
4. See that the order did not change from the initial search-score

### Expected behavior

The selected order should be honored, even when in a search result instead of a normal element index.

### Actual behavior

The selected order is ignored when a keyword search is active.

### Craft CMS version

4.3.1

### PHP version

8.0

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch. Sorting while searching element index table in CP has been removed in v4.3. When searching, your results are ordered by score descending (how well the results match what you were searching for). That being said, the UI doesn't really make this clear. I've created a PR with adjustments that make it clear that sorting is not possible while searching and that results are ordered by score descending.

**Comment by thupsi** [comment]
That's a pity @i-just, sorting while searching is pretty useful sometimes. Is there any chance of bringing back this ability in the future?

**Comment by FlorisDerks** [comment]
Bummer... this has been a very useful feature if you want to for example get recent articles which contain a certain word. With this function removed we now get years old content as the first results, just because it matches the search query better, but obviously isn't what we were looking for.

**Comment by brandonkelly** [comment]
Found a clean-ish way to bring back support for changing the sort attribute while searching, so this is fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 4.3.2 is out with support for reordering search results.
