### ISSUE TITLE
[4.x]:  Elements when eager loaded are null

### ISSUE THREAD

**Issue by martinherweg** [craftcms/cms#12251]
### Description

I have a query like this
```twig
{% set newsQuery = craft.entries.section('news').with(['heroImage', 'topics', 'category']).limit(4).all() %}
{% for news in newsQuery %}
  {{ d(news.topics.one()) }}
{{ d(news.category.one() }}
{% endfor %}
```

The result of the dump is null for all elements, the topics are Entries and are surely set on these elements and the category for example works fine when eager loaded.
If I remove topics from the .with() I get results as wished.

I also have two different environments and it works on one and not on the other.

### Expected behavior
`news.topics.one()`  should return the element when eager loaded

### Craft CMS version

4.3.1

### PHP version

8.0.25

### Operating system and version

Linux 5.10.0-0.bpo.15-amd64

### Database type and version

MySQL 10.3.36

### Installed plugins and versions

   - Control Panel CSS 2.5.0,
    - Empty Coalesce 4.0.0,
    - Feed Me 5.0.4,
    - Formie 2.0.14,
    - Image Resizer 3.0.3,
    - Imager X 4.1.7,
    - MatrixMate 2.1.1,
    - Navigation 2.0.10,
    - Preparse Field 2.0.0,
    - Quick Field 2.0.2,
    - Redactor 3.0.2,
    - Retour 4.1.4,
    - SEOmatic 4.0.10,
    - Smith 2.0.0,
    - Super Table 3.0.5,
    - Typed link field 2.1.4,
    - Videos dev-v3-develop,
    - Vite 4.0.3

**Comment by brianjhanson** [comment]
Just for a sanity check, do you get the same output when using Craft's native [`dump`](https://twig.symfony.com/doc/3.x/functions/dump.html) function or [`dd`](https://craftcms.com/docs/4.x/dev/tags.html#dd) tag?

Assuming the output is the same, do you have any custom code that might be interfering with eager loading? Could you also specify the field type of each of the eager loaded elements (`heroImage`, `topics`, and `category`)?

**Comment by martinherweg** [comment]
@brianjhanson Yes same for `dump` or `dd` tag

I test this on a new template without any block nor extending anything so it's solely the query because that was my first assumption as well that there is something getting in the way.

`heroImage` is an assets field
`category` is an Entries field
`topics` is an Entries field

I want to say again that it works fine in another envrionment, so it might be something with the database?
The company I'm working at also has a support plan so I could open a case there and send you a database there.

**Comment by brianjhanson** [comment]
That'd be great. If it works somewhere it definitely sounds like an environment issue.

**Comment by martinherweg** [comment]
👍  Thanks brian I'll do that tomorrow.

**Comment by brianjhanson** [comment]
Sounds like the one and only @olivierbon helped you get things back on track. 

For other's wandering into this thread, the issue ended up being two fields with the same handle. The fix was to remove one of the fields and manually fix things up.
