### ISSUE TITLE
[3.x]: Using `->toArray()` with `->setFieldValues()` is faulty for `SingleOptionFieldData` fields

### ISSUE THREAD

**Issue by modelesque** [craftcms/cms#12252]
### Description
I have a custom field called `occasion`, which is a dropdown `SingleOptionFieldData` field. I noticed that if I do something like:

```
$customFieldsArray = $entry->toArray([
   'occasion',
   // other fields...
]);
```
and then output that variable like `Craft::dd($customFieldsArray);`, then I see this:

```
[
    'occasion' => [
        'label' => 'Anniversary'
        'value' => 'anniversary'
        'selected' => true
        'valid' => true
    ],
   // other fields...
]
```

Then, sometime later, if I were to apply those values to another entry, like:

```
$otherEntry->setFieldValues($customFieldsArray);
```

everything looks fine except for my `occasion` `SingleOptionFieldData` field. Outputting the field via `Craft::dd($otherEntry->occasion);` shows me this:

```
craft\fields\data\SingleOptionFieldData#1
(
    [craft\fields\data\SingleOptionFieldData:_options] => [
        0 => craft\fields\data\OptionData#2
        (
            [label] => 'Choose'
            [value] => ''
            [selected] => false
            [valid] => true
        )
        1 => craft\fields\data\OptionData#3
        (
            [label] => 'Birthday'
            [value] => 'birthday'
            [selected] => false
            [valid] => true
        )
        2 => craft\fields\data\OptionData#4
        (
            [label] => 'Anniversary'
            [value] => 'anniversary'
            [selected] => true
            [valid] => true
        )
        3 => craft\fields\data\OptionData#5
        (
            [label] => 'Meeting'
            [value] => 'meeting'
            [selected] => false
            [valid] => true
        )
        4 => craft\fields\data\OptionData#6
        (
            [label] => 'Party'
            [value] => 'party'
            [selected] => false
            [valid] => true
        )
        5 => craft\fields\data\OptionData#7
        (
            [label] => 'Other'
            [value] => 'other'
            [selected] => false
            [valid] => true
        )
    ]
    [label] => null
    [value] => 'Anniversary'  <--------- Notice that the value is being set as the label, while the label is null
    [selected] => true
    [valid] => false
)
```
I would expect the selected `[label]` and `[value]` to be set respectively to the array produced from `->toArray()`, like:

```
craft\fields\data\SingleOptionFieldData#1
(
    [craft\fields\data\SingleOptionFieldData:_options] => [
         // etc....
    ]
    [label] => 'Anniversary'
    [value] => 'anniversary'
    [selected] => true
    [valid] => false
)
```

---

Is this a bug or am I misunderstanding something about `->setFieldValues()`? I noticed that it works fine for other types of fields like `DateTime` fields, where `->toArray()` gives you a value that can automatically be set via `->setFieldValues()`.

### Craft CMS version

3.7.58

### PHP version

7.4.26

### Operating system and version

Linux 5.10.104-linuxkit

### Database type and version

MySQL 8.0.31

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out.
 
I don't actually think that's a bug. That being said, `toArray()` has a `$recursive` argument which is `true` by default, which is why the `SingleOptionFieldData` is becoming an array. You could consider calling it via `$entry->toArray([...], [], false)` and check if that gives you what you need. 

Or you can consider using `$entry->getFieldValues()` instead and then pass the result to `setFieldValues()`.

**Comment by brandonkelly** [comment]
What @i-just said!
