### ISSUE TITLE
[4.x]: Migration almost worked

### ISSUE THREAD

**Issue by loqus** [craftcms/cms#12264]
### Description

I'm getting a good front-end,  but the CP gives: Setting unknown property: craft\fieldlayoutelements\entries\EntryTitleField::fieldUid

### Steps to reproduce

1. Migrate to v4

### Craft CMS version

Craft Pro 3.7.55.2 to 4

### PHP version

8.0.25

### Operating system and version

CentOs 7

### Database type and version

MariaDb 10.5.17

### Installed plugins and versions

-

**Comment by brianjhanson** [comment]
Do you have any more of a stack trace you can provide to help narrow down where that error would be coming from? Do you see it when running the migrations or after they're all done?

**Comment by loqus** [comment]
![error-dashboard (1)](https://user-images.githubusercontent.com/421837/200116203-0aae3c23-8361-4700-8756-5f120d16d3f5.jpg)

**Comment by loqus** [comment]
So what I did was uninstall all non compatible plugins, ran the step by step updating guide. All went well.
The front-end shows well. The login page for the cp also works. After logging in I get this error.

**Comment by loqus** [comment]
I got a little further, I looked into the differences in the composer file from a clean install and the current install. The differences were: 
`"require-dev": {
        "yiisoft/yii2-shell": "^2.0.3"
    },`
and
`"vlucas/phpdotenv": "^5.4.0",` <= mine was set to a version ^2.4

After updating composer got a new error in the dashboard

`Fatal error: Uncaught TypeError: Dotenv\Dotenv::__construct(): Argument #1 ($store) must be of type Dotenv\Store\StoreInterface, string given, called in /web/index.php on line 201 and defined in /vendor/vlucas/phpdotenv/src/Dotenv.php:60 Stack trace: #0 /web/index.php(201): Dotenv\Dotenv->__construct() #1 {main} thrown in /vendor/vlucas/phpdotenv/src/Dotenv.php on line 60`

It seems to be coming from these lines in index.php

`if (file_exists(CRAFT_BASE_PATH.'/.env')) {
    (new Dotenv\Dotenv(CRAFT_BASE_PATH))->load();
}`

**Comment by brianjhanson** [comment]
Our recommendations on the [entry scripts](https://craftcms.com/docs/4.x/upgrade.html#entry-script) have been updated a bit in four. I'd recommend checking your configuration against the [Craft starter project](https://github.com/craftcms/craft). Based on the lines you've shared here, you'll at least want to update the `index.php` to 

```php
// Load dotenv?
if (class_exists(Dotenv\Dotenv::class)) {
    // By default, this will allow .env file values to override environment variables
    // with matching names. Use `createUnsafeImmutable` to disable this.
    Dotenv\Dotenv::createUnsafeMutable(CRAFT_BASE_PATH)->safeLoad();
}
```

However, I think that might be unrelated to the other issue. Can you run a `project-config/apply --force` to see if that clears up your issue? I have a feeling it might be the same issue as #11925

**Comment by brandonkelly** [comment]
Sounds to me like there was a Git merge conflict on one of your entry types’ project config YAML files at some point (`config/project/entryTypes/...`), which wasn’t resolved correctly.

- Entry Title fields are represented by `craft\fieldlayoutelements\entries\EntryTitleField`, however that class doesn’t have a `fieldUid` property.
- Custom fields are represented by `craft\fieldlayoutelements\CustomField`, which do have a `fieldUid` property.

I’m not sure why this error wouldn’t show up until your Craft 4 upgrade, as this is all the same code as in Craft 3.

I suspect you could resolve it by running the following command in Craft 3, prior to upgrading:

```sh
> php craft project-config/rebuild
```

**Comment by loqus** [comment]
Ok I'll try that first before updating

**Comment by loqus** [comment]
It's a shit load of work, but maybe it's best to re-create the website starting with a blank craft 4 slate. Unless I can somehow easily export and import some things (but most is based on matixes)

**Comment by brandonkelly** [comment]
Can you try increasing your `memory_limit` PHP setting?

**Comment by loqus** [comment]
I went from 128 to 512 and that seemed to do the trick. I'll try updating to 4 tomorrow

**Comment by loqus** [comment]
Amazing @brandonkelly @brianjhanson !
With your help it worked out perfectly. Thanks so much.
![craft-4](https://user-images.githubusercontent.com/421837/200513014-2c498a73-d73e-400b-ad13-45b49722d0f1.png)

**Comment by brandonkelly** [comment]
Glad to hear it!
