### ISSUE TITLE
[4.x]: Multisite loading always site handle of primary site

### ISSUE THREAD

**Issue by tibedaniel** [craftcms/cms#12260]
### Description
After upgrading from Craft Pro 3.7.43 to Craft Pro 4.3.1 the application loads always the site handle of the primary site.

I could fix it temporarily with a hack in .env.php by setting define('CRAFT_SITE',  'http://subdomain.mysite.test' ); if the current site is equql $_SERVER['HTTP_HOST'].

### Steps to reproduce

Usual update due to the migration guide.

### Expected behavior

Craft should load the corret site handle without hack.

### Craft CMS version

4.3.1

### PHP version

8.0.22

### Operating system and version

Ubuntu 20.04.4 LTS

### Database type and version

Maria db

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out. Let me clarify if I get this correct first.

Since migration, you can see all your sites in the control panel > settings > sites and they all have the desired `Base URLs` against them? 

> the application loads always the site handle of the primary site

Do you mean it always loads the primary site even if you access the URL for another site you have on this installation? Craft will do that if it can't find the site you're after - it will default to the primary site.

First thing to check would be to see if you have correct base URLs specified against each of your sites.

**Comment by tibedaniel** [comment]
Yes, in the admin area under settings all sites are shown correctly a la 

- http://mysite.test (primary)
- http://subdomain1.mysite.test
- http://subdomain2.mysite.test
- http://subdomain3.mysite.test

But on the frontend Craft only loads the primary site even if I calling http://subdomain2.mysite.test or  http://subdomain3.mysite.test

**Comment by i-just** [comment]
> The urls of each subdomain is rendered by an alias i.e. @web_subdomain2

Sorry, what do you mean by that. Do you have the following in your `general.php` config 
```
aliases' => [
        '@web' => 'http://mysite.test',
        '@web_subdomain1' => 'http://subdomain1.mysite.test',
        '@web_subdomain2' => 'http://subdomain2.mysite.test',
        '@web_subdomain3' => 'http://subdomain3.mysite.test',
    ],
```

and then in CP > settings > sites, for subdomain2 site you have base URL set to `@web_subdomain2`?

**Comment by tibedaniel** [comment]
Yes, the aliases er in the config.php. 

>>The urls of each subdomain is rendered by an alias i.e. @web_subdomain2

I mean with that in CP > settings > sites => subdomain2 field "primary url"
There I use @web_subdomain2 and so I see that Craft is rendering the alias to the correct url http://subdomain2.mysite.test.

In the backend everything is fine, only the fronend can not differ between the domains.

**Comment by i-just** [comment]
OK. This is something to do with your configuration and not actually a bug with Craft 4. 

Are you defining `CRAFT_SITE` anywhere (e.g. `web/index.php` or `.env` file)? Having it set to the handle of the primary site can cause the URL to show as http://subdomain2.mysite.test, but the site being served to be the primary one. 

It might be worth you having a look at: https://craftcms.com/docs/4.x/config/#environment-overrides as that's new to C4.

**Comment by tibedaniel** [comment]
What is wrong with the configuation?

**Comment by tibedaniel** [comment]
Yes, you wrote that i has to do with my configuration, so I thought you know whats wrong with it.
The config-file is edited as its recommended on https://craftcms.com/docs/4.x/upgrade.html

There was no need to set CRAFT_SITE in Craft 3. I only use it as a hack to make the installation work with Craft 4.

Without using CRAFT_SITE craft will always load the primary site

**Comment by i-just** [comment]
I found a very old ticket with a similar issue: https://github.com/craftcms/cms/issues/2853. Could you please try the first 3 things that Brandon asked about on that ticket and let me know the outcome:

1. Go to `http://subdomain2.mysite.test/admin/utilities/php-info` (replace `admin` with your CP trigger, if you’ve changed it to something else). Then search for `$_SERVER['HTTP_HOST']` and `$_SERVER['SERVER_NAME']`. Are they both set to `subdomain2.mysite.test`?
2. Try duplicating your `index.php` file as `scratch.php`, and comment out the `$app->run();` line, and add this afterwards: 
```Craft::dd($app->sites->currentSite->handle);``` 
Then go to `http://subdomain2.mysite.test/scratch.php`. What gets output? 
3. Replace that `Craft::dd()` line from step 2 with this - what does it give you?
`Craft::dd($app->request->hostName);`

The `siteUrl` general config setting no longer applies in Craft 4, but in a similar fashion, it would be good to know how exactly do you set up your aliases in `general.php` (copy and paste of the relevant code snippet would be best).

**Comment by brandonkelly** [comment]
> Yes, the aliases er in the config.php.

What are the exact aliases you are defining? Can you share that code?

**Comment by tibedaniel** [comment]
That is the config/general.php


return [
    '*' => [
        'securityKey'                      => getenv('SECURITY_KEY'),
        'pageTrigger'                      => 'p/',
        'errorTemplatePrefix'              => 'errors/_',
        //max 10 MB
        'maxUploadFileSize'                => 10485760,
        'maxRevisions'                     => 3,
        'defaultWeekStartDay'              => 1,
        'omitScriptNameInUrls'             => true,
        'limitAutoSlugsToAscii'            => true,
        'convertFilenamesToAscii'          => true,
        'generateTransformsBeforePageLoad' => true,
        'defaultSearchTermOptions'         => [
            'subLeft'  => true,
            'subRight' => true,
        ],
    ],
    'dev' => [
        'aliases' => [
            "@web_grong" => "http://grong.mydomain.test",
            "@web_verdal" => "http://verdal.mydomain.test",
            "@web_trondheim" => "http://trondheim.mydomain.test",
            "@web_malmefjorden" =>"http://malmefjorden.mydomain.test",
            "@web_alesund"=> "http://alesund.mydomain.test",
            "@web_vestfold"=> "http://vestfold.mydomain.test",
            "@web_skien" =>  "http://skien.mydomain.test",
            "@web_mohagen" =>  "http://mohagen.mydomain.test",
            "@web_ostfold" => "http://ostfold.mydomain.test",
            "@web_heistad"=> "http://heistad.mydomain.test",
            "@web_sunnmore"=> "http://sunnmore.mydomain.test",
            "@web_volda"=> "http://volda.mydomain.test",
            "@web_stryn"=> "http://stryn.mydomain.test",
            "@web_steinkjer"=>  "http://steinkjer.mydomain.test",
            "@web_melhus"=> "http://melhus.mydomain.test",
            "@web_bergen"=> "http://bergen.mydomain.test",
            "@web_outlet"=> "http://outlet.mydomain.test",
        ],

        'enableTemplateCaching' => false,
        'devMode' => true
    ],
    'staging' => [
        'devMode'               => true,
        'enableTemplateCaching' => false,
        'allowAdminChanges'     => false
    ],
    'production' => [
        'allowAdminChanges' => false
    ],
];

**Comment by brandonkelly** [comment]
When you updated to Craft 4, did you happen to update your `web/index.php` and `bootstrap.php` files based on the [latest](https://github.com/craftcms/craft/blob/main/web/index.php) [ones](https://github.com/craftcms/craft/blob/main/bootstrap.php)?

We have seen some cases where people have done that, but didn’t also update their `ENVIRONMENT` environment variable to `CRAFT_ENVIRONMENT`, which is what Craft is expecting. If that’s the case here, then Craft is not getting set to use the `dev` environment key in the first place, so your aliases aren’t getting defined.

(Craft never actually had direct support for `ENVIRONMENT`; that was something that `bootstrap.php` [checked for on its own](https://github.com/craftcms/craft/blob/c041b543fdad1b85785b5c61035d0bc286bd89d8/bootstrap.php#L22).)

**Comment by tibedaniel** [comment]
Yes, I can confirm that the files are identical.

**Comment by brandonkelly** [comment]
As in they didn't change when you upgraded, or they are identical with the latest default files in the `craftcms/Craft` starter project?

**Comment by tibedaniel** [comment]
They are identical with https://github.com/craftcms/craft/blob/main/web/index.php and https://github.com/craftcms/craft/blob/main/bootstrap.php

**Comment by i-just** [comment]
And you updated `ENVIRONMENT` environment variable to `CRAFT_ENVIRONMENT`?

Another way I'm able to replicate this behaviour is if I have my primary site use `@web` alias in settings > sites, but don't define it in the config file. Double check if your primary site uses an alias that's on the list you've posted (you have to go to the site settings to see this, as on the list of all sites you will only see what the aliases are resolved to).

**Comment by tibedaniel** [comment]
Yes, craft is able to differ between the environments (test, staging, production). So I think, the envirmonment variable is not the issue.

**Comment by i-just** [comment]
And how about this?

> Another way I'm able to replicate this behaviour is if I have my primary site use `@web` alias in settings > sites, but don't define it in the config file. Double check if your primary site uses an alias that's on the list you've posted (you have to go to the site settings to see this, as on the list of all sites you will only see what the aliases are resolved to).

**Comment by brandonkelly** [comment]
> Yes, craft is able to differ between the environments (test, staging, production). So I think, the envirmonment variable is not the issue.

`test` or `dev`? Your config file says `dev`.

**Comment by brandonkelly** [comment]
If you go to Utilities → System Report, are you seeing each of your aliases listed out there with the expected values?

**Comment by tibedaniel** [comment]
If the primary site is part of the aliases, the issuee is still present.

Yes, locally the environment is called "dev", but the same behaviour is present on staging and prod.


As mentionend in the backend everything looks good its only the frontend.
See screenshots 

- System report
https://capture.dropbox.com/XA4Lnza3mJ6u6rqm

- site settings
https://capture.dropbox.com/dVYYgipnfABphIeJ

And the entry urls under /admin/entries/singles?site=tellusMalmefjorden&source=singles are also correct.

**Comment by i-just** [comment]
Could you also please provide a screenshot of the Settings > Sites > Tellus (default) site, so that I can see how your `Base URL` is set in there?

**Comment by brandonkelly** [comment]
> If the primary site is part of the aliases, the issue is still present.

Is the primary site set to just `@web`? If so that’s your issue. `@web` should always be set to the **current** web root URL, regardless of which site is selected. So if it’s set correctly (which it is automatically by default), then having the primary site set to `@web` will basically tell Craft that it should always be served.

**Comment by tibedaniel** [comment]
Yes, the primary site is only @web. I will try to change the alias of the primary site to @default tomorrow and send a feedback.

**Comment by brandonkelly** [comment]
Alright, going to close this as that’s definitely the issue. Feel free to reply if you need additional help though!
