### ISSUE TITLE
[3.7.59]: Editing Dropdown field labels or values with an existing default causes a blank option to display in the list.

### ISSUE THREAD

**Issue by KettyLezama** [craftcms/cms#12262]
### Description
Editing Dropdown field labels or values with an existing default causes a blank option to appear as the first option in the list in an entry that already exists. 

This only happens on existing components; if I create a brand new component with this field, the blank value does not show. This doesn't cause problems when a field is optional, but as soon as the field is mandatory, authors are forced to select a value and resave. With so many entries already using this field, you can see how tedious this can be.

Is there a way to avoid this from happening?

### Steps to Reproduce
1. Let's say I had this as my original Dropdown field, with a default option set:
<img width="1012" alt="Old Dropdown Field" src="https://user-images.githubusercontent.com/3981398/200016075-ceac87d0-7704-4716-afdc-eb91e94b8766.png">

This is how the author sees the field, and this is exactly what I want.
<img width="284" alt="Old Dropdown" src="https://user-images.githubusercontent.com/3981398/200016046-180fdf15-0174-42ac-a429-6be11d13662a.png">

2. But then I need to update the value of the dropdown options, as such:
<img width="1004" alt="New Dropdown Field" src="https://user-images.githubusercontent.com/3981398/200016322-97be8870-fc40-49be-8be4-e9cf60ef9792.png">

This is what the author now sees on existing entry pages that are using this field:
<img width="272" alt="New Dropdown" src="https://user-images.githubusercontent.com/3981398/200016664-eb2a6e25-cd11-4ed2-8ba8-533a472d6cdd.png">

### Expected Behavior
I would expect the dropdown options to display the same way they were originally -- without a blank option.

### Actual Behavior
The first option displayed (and selected) is now blank (null).

### Craft CMS version

3.7.59

### PHP version

7.4.30

### Operating system and version

macOS Monterey 12.6

### Database type and version

MySQL 5.7

### Installed plugins and versions

- "ext-zip": "^1.15",
- "born05/craft-twofactorauthentication": "2.6.1",
- "composer/composer": "2.2.15",
- "craftcms/aws-s3": "1.3.0",
- "craftcms/cms": "3.7.55.3",
- "craftcms/element-api": "2.8.6.1",
- "craftcms/feed-me": "4.5.3",
- "craftcms/plugin-installer": "1.5.6",
- "craftcms/redactor": "2.10.10",
- "ether/tags": "1.0.9",
- "internetztube/craft-element-relations": "1.3.10",
- "jalendport/craft-readtime": "^1.6",
- "nystudio107/craft-imageoptimize": "1.6.48",
- "nystudio107/craft-imageoptimize-imgix": "1.2.4",
- "nystudio107/craft-retour": "3.2.3",
- "nystudio107/craft-seomatic": "3.4.39",
- "nystudio107/craft-similar": "1.1.5",
- "nystudio107/craft-twigpack": "1.2.17",
- "presseddigital/linkit": "3.0.2",
- "putyourlightson/craft-sprig": "1.13.0",
- "quickbase/matrix-finder": "1.1.0",
- "quickbase/quickbase-process": "1.0.13",
- "simplygoodwork/craft-donkeytail": "2.0.7",
- "sunra/php-simple-html-dom-parser": "1.5.2",
- "topshelfcraft/canary": "^3.0",
- "topshelfcraft/environment-label": "3.2.0",
- "utakka/redactor-anchors": "1.4.0",
- "vaersaagod/geomate": "v1.3.1.2",
- "vaersaagod/matrixmate": "1.5.0",
- "verbb/calendar-links": "^2.0",
- "verbb/field-manager": "2.2.5",
- "verbb/icon-picker": "1.1.14",
- "verbb/smith": "1.2.3",
- "verbb/super-table": "2.7.3",
- "verbb/workflow": "1.7.5",
- "vlucas/phpdotenv": "2.6.5",
- "wbrowar/guide": "3.1.2",
- "workingconcept/craft-cloudflare": "1.1.0",
- "wrav/simplesharing": "1.0.8",
- "yiisoft/yii2": "^2.0.42",
- "yiisoft/yii2-queue": "^2.3.0"

**Comment by brianjhanson** [comment]
Thanks for reaching out! This is currently working as expected, although I understand how it's not ideal. 

When you update the values of the dropdown field, the values already in the database aren't affected. That means when you come back to the page, the value of the field getting rendered to the template will be the old `text-align--center` and not the new `text-align-center` value until you select a new value and save the field. The blank space occurs because the old value is no longer an available option for the select field.

To avoid having to migrate all the old values by hand, you can use the [`craft resave/entries`](https://craftcms.com/docs/4.x/console-commands.html#resave-entries) command to set all the values.  It gets a little long in your case, but something like this should do it:

```
./craft resave/entries --section mySection --type myEntryType --set dropdown --to "fn(\$element) => \$element->getFieldValue('textAlign')->value === 'text-align--center' ? 'text-align-center' : \$element->getFieldValue('textAlign')"
```

I definitely recommend taking a backup and testing that locally before running anything on production since I'm not able to test against your full data set, but if it's good, you can just repeat that same command with the other values.

You could do something similar with a content migration if you're more comfortable with taking that route.

**Comment by KettyLezama** [comment]
Hi Brian! Thanks for getting back to me!

Yikes, so we are definitely using this field in 275+ entries in our company's website under many, many different sections. I attempted to start with our `main` and `empowerPages` sections; but not ALL entries under those sections use this `textAlign` field. Therefore I end up with an error like this:

<img width="1566" alt="Screen Shot 2022-11-06 at 6 52 41 PM" src="https://user-images.githubusercontent.com/3981398/200202407-d0c6a5b8-2e99-4cfb-8ed6-d6ca9c526631.png">

`Resaving 49 entries ...
    - [1/49] Resaving Video Demo Library (4452684) ... An Error occurred while handling another error:`

At least in part of the error, I see it's trying to resave the `textAlign` field in the `Video Demo Library` page, but this entry does not use this field. The entry is, however, a part of the `main` section so I assume that's why it's trying to be resaved.

So my follow-up questions are:

1. Would we need to run this resave command per every section utilizing the `textAlign` field?
2. Is there a way to run a `resave/entries` command and ignore all entries that do not use this field?

***I'm curious if the faster solution for now (although a little painstaking) could be to delete this field entirely and recreate it in the component we're using. Thoughts?***

**Comment by brandonkelly** [comment]
@KettyLezama Whoops, that’s a bug. Setting an invalid field handle should not have bailed the whole command like that. I’ve just fixed that for the next Craft 3 and 4 releases.

As you’re on Craft 3, you can pull that fix in a little early by changing your `craftcms/cms` requirement in `composer.json` to `"v3.x-dev#fe70e3b9ca9454f396df7d5f14e686edba61c8e4 as 3.7.59"`, and running `composer update`.

**Comment by KettyLezama** [comment]
@brandonkelly Thank you for fixing that command! I'll give it a try for sure.

@brianjhanson @brandonkelly What do you both think about my first follow-up question, by the way? Our company has many, many sections. So am I right in saying that we would need to run this command per every section utilizing that field? Or is there a way to just run it for all sections now that it would just skip the entry if it doesn't have the field?

**Comment by brandonkelly** [comment]
@KettyLezama Correct, if it’s for a Matrix field you should use `resave/matrix-blocks`. What happens when you run that command?

**Comment by KettyLezama** [comment]
@brandonkelly This:

<img width="1569" alt="Screen Shot 2022-11-07 at 1 29 12 PM" src="https://user-images.githubusercontent.com/3981398/200387126-dd1f32d0-05b4-4eed-a3da-d7531d65948d.png">

**Comment by brianjhanson** [comment]
It looks like you might have forgotten to update the `--set` parameter from `dropdown` to your field handle. From the screenshot it looks like the command would be

```
./craft resave/matrix-blocks --field components --type textSpan --set textAlign --to "fn(\$element) => \$element->getFieldValue('textAlign')->value === 'text-align--center' ? 'text-align-center' : \$element->getFieldValue('textAlign')"
```

**Comment by brandonkelly** [comment]
Craft 3.7.60 and 4.3.2 are out with that fix where `resave/*` commands were completely bailing when an invalid field value was being set.

**Comment by brandonkelly** [comment]
Craft 4.5.0 is out with an improvement to Dropdown field behavior: now if a Dropdown field’s value is invalid, and the field contains an explicit Default option, the default option will be auto-selected, and the field will be marked as changed. (#13540)
