### ISSUE TITLE
[4.x]: 

### ISSUE THREAD

**Issue by mattcdavis1** [craftcms/cms#12265]
### Description
I am seeing a double UI rendering in the Field Layout area of Craft CMS fairly frequently. [See screenshot here](https://capture.dropbox.com/NDPGYm8x38g5KhYa).

### Steps to reproduce

1. Not sure. Intermittent.

### Expected behavior

A UI element that is intented to only render once would render only once in it's proper location.

### Actual behavior
The Fields and Content sections render twice

### Craft CMS version

Craft Solo 4.3.1

### PHP version

8.0.25

### Operating system and version

Mac OS

### Database type and version

MySQL 8

### Image driver and version

Imagick

### Installed plugins and versions

Amazon S3 2.0.1
Formie 2.0.14
Neo 3.4.0
Redactor 3.0.2
Super Table 3.0.5
Typed link field 2.1.4

**Comment by brandonkelly** [comment]
Is it always within a Neo field?

**Comment by mattcdavis1** [comment]
@brandonkelly - I think so yeah. So maybe I need to create this ticket w/Neo

**Comment by brandonkelly** [comment]
Yeah sounds like it 👍🏻
