### ISSUE TITLE
[4.x]: Redirect to Posted URL doesn't always decode the hashed URL param for front-end user registration

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#12273]
### Description

We've followed this guide to create a registration form:
https://craftcms.com/knowledge-base/front-end-user-accounts

It works like a charm, except the users sometimes get redirect to b756e71e528394aec061ed71da07ec933fb7288753e3969e9c59552bc9c53764c1e068d80bff1b39be949724e7069765e90cd404a25443fc27fe260359b21da48f91902f6d6d37879fb589b46fcfa1c82caea0d797678dc5bd47c6713b593b822f3b522fcb5cacd8406205b261a195c0ad3d0e25906b01043875c6c4c64cd85fmy/activate

Rather than to the actual url /my/activate. What we've found is that it happens when the users registration didn't save the first time, but the form returned an error (email exists, something wrong with the password). The user gets redirected back to the sign-up form where the error has displayed, and the next time they submit they end-up in the wrong place.

The HTML
```
<form method="post" accept-charset="UTF-8">
    {{ csrfInput() }}
    {{ actionInput('users/save-user') }}
    {{ redirectInput('my/activate') }}

    {% if craft.app.request.getParam('redirect') %}
        {{ redirectInput(craft.app.request.getParam('redirect')) }}
    {% endif %}
    
    <div class="auth__form">
        <h3>{{ 'Register'|t }}</h3>

        {% if errorMessage is defined %}
            <ul class="errors"><li>{{ errorMessage }}</li></ul>
        {% endif %}

        <div class="auth__detail">
            <label>{{ 'Email'|t }}</label>

            {% if user is defined %}
                {{ helpers.errorList(user.getErrors('email')) }}
            {% endif %}

            <div class="auth__input">
                <i class="icon-mail"></i>

                {{ input('text', 'email', craft.app.user.rememberedUsername, {
                    id: 'email',
                    placeholder: 'Email'|t,
                    class: 'form-control auth__field'
                }) }}
            </div>
        </div>

        <div class="auth__detail">
            <label>{{ 'Password'|t }}</label>

            {% if user is defined %}
                {{ helpers.errorList(user.getErrors('password')) }}
            {% endif %}

            <div class="auth__input">
                <i class="icon-lock"></i>

                {{ input('password', 'password', null, {
                    id: 'password',
                    placeholder: 'Password'|t,
                    class: 'form-control auth__field'
                }) }}

                {# not allowed by most browsers #}
                {% if false %}
                    <span class="auth__show-password js-toggle-password"><span class="icon-eye"></span></span>
                {% endif %}
            </div>
        </div>

        <div class="auth__detail">
            <button type="submit" class="btn btn-primary auth__login-btn" aria-label="Register">{{ 'Register'|t }}</button>
        </div>


        <div class="auth__signup text-center">{{ 'Already got an account?'|t }} <a href="{{ craft.entries.section('login').one.url }}">{{ 'Sign in here'|t }}</a></div>
    </div>
</form>
```
### Steps to reproduce

1. Create a registration form using html above
2. make an obvious mistake that will return a error when signing up (too short password, wrong email)
3.  Correct your mistake and submit agan.

### Expected behavior
Get redirected to /my/activate and not the hashed value.

### Actual behavior
You get redirected to the hashed parameter.

### Craft CMS version

4.3.2

### PHP version

8.0

### Operating system and version

MacOS, Linux

### Database type and version

Mysql 8.0

### Image driver and version

GD

### Installed plugins and versions

- seomatic "4.0.12",
- retour  "4.1.5",
- blitz 4.2.3 (disabled)
- linkfield 2.1.4
- dukt/social 3.x-dev

**Comment by i-just** [comment]
Hi, thanks for reaching out. It's happening because the second time you try, you have 2 register inputs in your code, caused by this:
```
{{ redirectInput('my/activate') }}

{% if craft.app.request.getParam('redirect') %}
    {{ redirectInput(craft.app.request.getParam('redirect')) }}
{% endif %}
```
And then the `redirectInput` in the `if` statement is actually double hashed. Consider if you actually need that if statement with the second redirect input, and if you don't, just remove it.

**Comment by lenvanessen** [comment]
Yes, silly me. Didn't realize, the redirect was bound to the request after the initial call. Just changed it to
` {{ actionInput(craft.app.request.getQueryParam('redirect') ?: 'my/activate') }}`

And it works like a charm
