### ISSUE TITLE
[4.x]: Stray debugging console log in the CP

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#12285]
### Description

From `ElementEditor.js:344`: https://github.com/craftcms/cms/blob/develop/src/web/assets/cp/src/js/ElementEditor.js#L344

```js
        if (this.isFullPage) {
          const heightDiff = $('#content').height() - initialHeight;
          console.log(heightDiff);
```

### Steps to reproduce

1. Edit an entry, and look at the developer tools log

### Expected behavior

No debugging logging

### Actual behavior

`heightDiff` gets logged

### Craft CMS version

4.3.1

### PHP version

n/a

### Operating system and version

n/a

### Database type and version

n/a

### Image driver and version

n/a

### Installed plugins and versions

n/a

**Comment by brandonkelly** [comment]
Thanks for pointing that out!
