### ISSUE TITLE
[4.x]: Status condition rule has no effect for entry type field also missing on entry index page

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#12289]
### What happened?

Status rule has no effect on results
**Steps to reproduce**
1. create an entry type (type1) with status rule set to enabled entries
2. add that field to a field layout for another entry type (type2)
3. try to create a type2 entry
4. open that entry type field 
5. you can see all type1 entries  (disabled, enabled, ...)

also maybe related issue:
Status condition rule is missing on entry index page

### Craft CMS version

4.3.1

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out. I'm able to replicate this and I've created a PR to for this.

**Comment by brandonkelly** [comment]
It shouldn’t have been possible to select “Status” there to begin with, just like it’s not when filtering elements within an element index, or when defining custom sources. Fixed that for the next release.

**Comment by brandonkelly** [comment]
Craft 4.3.2 is out with that fix.
