### ISSUE TITLE
[4.3.1]: .status-badge.modified CSS issue

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#12287]
### Description

When in preview, the `.status-badge.modified` div in certain matrix fields is missing a `left:-15px` rule

How it looks now:

<img width="639" alt="preview_craft4" src="https://user-images.githubusercontent.com/19857599/200927884-2ae28bb7-cf0e-4b1a-ae97-9508d59148ae.png">

How it should look:

<img width="641" alt="preview_craft3" src="https://user-images.githubusercontent.com/19857599/200928048-5e1004b4-7829-407c-aef2-816a28413668.png">

### Steps to reproduce

1. Edit a text field in a matrix block
2. Open the preview

### Expected behavior

The modified badge should be more to the left

### Actual behavior

It sticks to the left hand side of the text field and looks wrong

### Craft CMS version

4.3.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Hah, I just noticed that a couple days ago. Fixed for the next release via 0bfaf6ded2ee27f09a502ef5a11c72ce553efd3f.

**Comment by brandonkelly** [comment]
Craft 4.3.2 is out with that fix.
