### ISSUE TITLE
[4.3.1]: Unable to move element in a structure - Mutation

### ISSUE THREAD

**Issue by DTesch-Reem** [craftcms/cms#12291]
### Description
When trying to move an Element with a mutation this error occurs.

Seems to happen on multisite-Setup because the siteId is not passed to this function:

```
/**
     * Get the related element.
     *
   * @param int $elementId
   * @return ElementInterface
   */
  protected function getRelatedElement(int $elementId): ElementInterface
  {
      $relatedElement = Craft::$app->getElements()->getElementById($elementId);

      if (!$relatedElement) {
          throw new Error('Unable to move element in a structure');
      }

      return $relatedElement;
  }
```

### Steps to reproduce

Querry:

```graphql
mutation saveEntry($id: ID = "", $title: String, $slug: String, $authorId: ID, $appendTo: ID) {
  save_bueroseiten_ch_default_Entry(id: $id, title: $title, slug: $slug, authorId: $authorId, appendTo: $appendTo, siteId: 4, appendToRoot: true) {
    title
    slug
    authorId
    parent {
      id
    }
  }
}
```

Variables: 

```json
{
  "title": "Gin and Tonic",
  "slug": "gin-tonic",
  "appendTo": 158427
}
```

### Expected behavior
Move specified element to structure position

### Actual behavior
Error Message: Unable to move element in a structure

### Craft CMS version

4.3.1

### PHP version

8.0.11

### Operating system and version

Unix

### Database type and version

mysql 8

### Installed plugins and versions

- Embedded Assets       embeddedassets        spicyweb/craft-embedded-assets   3.1.0   
    Feed Me               feed-me               craftcms/feed-me                 5.0.4   
    Incognito Field       incognito-field       mmikkel/incognito-field          1.3.0    
    Isolate               isolate               trendyminds/isolate              dev-craft-4  Yes        Yes    
    Matrix Field Preview  matrix-field-preview  weareferal/matrix-field-preview  dev-main   
    MatrixMate            matrixmate            vaersaagod/matrixmate            2.1.1      
    Redactor              redactor              craftcms/redactor                3.0.2     
    Redactor Anchors      redactor-anchors      utakka/redactor-anchors          1.4.0     
    Smith                 smith                 verbb/smith                      2.0.0         
    Super Table           super-table           verbb/super-table                3.0.5        
    Table Maker           tablemaker            verbb/tablemaker                 4.0.3        
    Typed link field      typedlinkfield        sebastianlenz/linkfield          2.1.4       
    Webhooks              webhooks              craftcms/webhooks                3.0.4

**Comment by brianjhanson** [comment]
Thanks for reporting and for the PR! I ended up implementing something similar yesterday but didn't get a chance to fully test it out until this morning. That's in [up for review now](https://github.com/craftcms/cms/pull/12302). I'm going to close out the other PRs, but I do appreciate them.

**Comment by brandonkelly** [comment]
This is fixed for the next Craft 3 and 4 releases via #12325.

**Comment by brandonkelly** [comment]
Craft 3.7.60 and 4.3.2 are out with that fix.
