### ISSUE TITLE
[4.3.1]:  Preview function is acting up

### ISSUE THREAD

**Issue by Leadstar-Johan** [craftcms/cms#12292]
### Description

Preview function doesnt work unless you go in to it before editing a entry,

### Steps to reproduce

1. Edit a entry 
2. Press preview

### Expected behavior

To get into previewmode 

### Actual behavior

Just keeps loading forever

### Craft CMS version

4.3.1

### PHP version

8.1.10

### Operating system and version

Linux 5.15.0-1020-aws

### Database type and version

MySQL 8.0.31

### Image driver and version

GD 8.1.10

### Installed plugins and versions

![image](https://user-images.githubusercontent.com/85494803/201132097-48791aa8-1067-46aa-9d90-71b2a4b93f9a.png)

**Comment by i-just** [comment]
Hi, thanks for reaching out. Do you have autosaving drafts turned off (e.g. via `autosaveDrafts => false` in `config/general.php`)? Live Preview is disabled with autosaving drafts turned off: https://craftcms.com/docs/4.x/config/general.html#autosavedrafts

**Comment by Leadstar-Johan** [comment]
Hey, Yes i have `autosaveDrafts => false`

**Comment by i-just** [comment]
Thanks for confirming. In that case it's working as expected, because disabling autosaving drafts also disables Live Preview.
