### ISSUE TITLE
[4.x]: `inputHtml()` called a second time with extra namespace if error/exception occurs

### ISSUE THREAD

**Issue by ttempleton** [craftcms/cms#12308]
### Description

If a PHP error or exception occurs during a call to a field's `inputHtml()` method, `inputHtml()` is called a second time with extra added to the current namespace, e.g. if the original value of `Craft::$app->getView()->getNamespace()` was `fields`, then the second time it will be `fields[fields]`.

Clearly this happening would indicate that there is a bug somewhere else, but it can have undesired effects on element editing in some cases. For instance, if a field causing an error is a subfield of a Matrix field, the element editor page still loads, but the Matrix field's new block buttons don't work.

A current example of a bug that has this type of effect on Matrix fields is the oEmbed plugin bug https://github.com/wrav/oembed/issues/125 which causes a PHP error - but the below steps to reproduce will instead use a modified plain text field.

### Steps to reproduce

1. Replace the existing `craft\fields\PlainText::inputHtml()` with the following, to make it throw an exception the first time it's called:

```php
private $_inputHtmlException = null;

/**
 * @inheritdoc
 */
protected function inputHtml(mixed $value, ?ElementInterface $element = null): string
{
    if ($this->_inputHtmlException === null) {
        throw $this->_inputHtmlException = new \Exception(Craft::$app->getView()->getNamespace());
    }

    $oldNS = $this->_inputHtmlException->getMessage();
    $newNS = Craft::$app->getView()->getNamespace();
    return "inputHtml called again with namespace $newNS after exception thrown with namespace $oldNS";
}
```

2. Add a plain text field to a single section's field layout
3. Go to edit the single's entry
4. See that the plain text field shows the message "inputHtml called again with namespace fields[fields] after exception thrown with namespace fields"

**Optional extra steps:**

5. Create a Matrix field with one block type, with one plain text subfield
6. Remove the plain text field from the single section's field layout, and add the Matrix field
7. Go to edit the single's entry
8. Try to create a new Matrix block and see that the new block buttons don't work

### Expected behavior

`inputHtml()` to not be called a second time if an error/exception occurs

### Actual behavior

`inputHtml()` is called a second time with extra namespace added if an error/exception occurs

### Craft CMS version

4.3.1

### PHP version

8.1.12

### Operating system and version

macOS Monterey 12.6

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next release.
