### ISSUE TITLE
[4.3.1]: Custom fields not working in GraphQL

### ISSUE THREAD

**Issue by mmorkt** [craftcms/cms#12301]
### Description
Just upgraded a site from [3.7.47.1] to [4.3.1]. Everything seems to work, except the way we query custom fields in GraphQL. 

In version 3 we were able to set custom fields directly in `entry`, now in version 4 we have to place them inside the `... on pages_pages_Entry`. We got more then 15 Entry Types. it would demand a lot more code. 

### This does work but require a lot more code

```
query ($uri: [String]) {
  entry(uri: $uri) {
    title
    ... on pages1_pages_Entry {
      metaDescription
     + a lot more  fields
    }
    ... on pages2_pages_Entry {
      metaDescription
     + a lot more  fields
    }
    ... on pages3_pages_Entry {
      metaDescription
     + a lot more  fields
    }
    ... on pages4_pages_Entry {
      metaDescription
     + a lot more  fields
    }
    ... on pages5_pages_Entry {
      metaDescription
     + a lot more  fields
    }
    ... on pages6_pages_Entry {
      metaDescription
     + a lot more  fields
    ...........
```

### Steps to reproduce
Call a custom field
```
query ($uri: [String]) {
  entry(uri: $uri) {
    metaDescription
    # metaDescription is a "CUSTOM FIELD"
    title
  }
}

```

### Expected behavior
Get data from custom field
```
{
  "data": {
    "entry": {
      "metaDescription": "Result",
      "title": "Page title"
    }
  }
}
```

### Actual behavior
```
{
  "errors": [
    {
      "message": "Cannot query field \"metaDescription\" on type \"EntryInterface\". Did you mean to use an inline fragment on \"produkter_product_Entry\", \"produkter_kategori_Entry\", \"pages_standard_Entry\", \"pages_nyheter_Entry\", or \"pages_kunskap_Entry\"?",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ]
    }
  ]
}
```

### Craft CMS version

4.3.1

### PHP version

8

### Operating system and version

MacOs

### Database type and version

MariaDB 10.4

**Comment by brianjhanson** [comment]
The validation that's running and throwing that error will [only run when in devMode](https://github.com/craftcms/cms/blob/a013b085e3dfca069009dd6cda0cff0e07b1293f/src/services/Gql.php#L416-L422) so when that's off, things on 4 should work like they did in 3. 

I would recommend using the fragments in the future though, you're missing out on some of the benefits of having a strongly typed schema with this method.

I'm going to close this for now, but feel free to follow up if you have any other questions.
