### ISSUE TITLE
[4.x]: User Account firstName and lastName Field Data Getting Modified and Dropped

### ISSUE THREAD

**Issue by ryanmasuga** [craftcms/cms#12305]
### Description
We are seeing what we think is very inconsistent behavior with Craft's Full Name field, and how First Name and Last Name fields are being saved and rendered on the front end. First and Last name are completely messing with name output.

Examples:
Craft Admin Full Name: Oliver Hazard Peregrine Falcon Jr.
`{{ currentUser.firstName|e }} {{ currentUser.lastName|e }}` template output: Oliver Falcon

The name is a little fanciful, but here is another very real example:

Registered with First Name: T.M., Last Name: Stevens
Full Name in Craft CP: T.M. Stevens
First/Last Output: T Stevens
In the DB (users table): 
fullname: T.M. Stevens
firstName: T
lastName: Stevens

(This firstName _was_ T.M. in the DB when first registered, but changed to just a "T"  - I believe when their account was updated from a pending status to active.)

One more: 
Registered with First Name: Mary Rose, Last Name: Smith
Full Name in Craft CP: Mary Rose Smith
First/Last Output: Mary Smith
In the DB (users table): 
fullname: Mary Rose Smith
firstName: Mary
lastName: Smith

This person's name is Mary Rose..._not_ Mary. 

### Steps to reproduce

1. Have a name that is more than a simple two word first name / last name, or without punctuation or suffixes, and it will not be correct when using firstName and lastName variables. 

### Expected behavior
The contents of the firstName and lastName fields in the DB should be populated as a user entered them. We should be able to reliably use those fields for newsletter or account greetings or edit account pages with First and Last Name fields, allowing them to update their own name without apparent data loss.

### Actual behavior
Name data getting dropped and chopped. fullName field appears fine, but we can't allow users to edit first and last names separately. 

Are we doing something incorrectly? Is it no longer advised to offer First Name and Last Name fields on the front end? We have sites on Craft 3 that have account edit forms with First and Last name fields on the front end with many thousands of users, so we're hesitant to update any of these sites to Craft 4 after seeing this behavior. Would it be advisable for us to make our own First and Last name custom fields for users and use those instead?

### Craft CMS version

4.3.1

### PHP version

8.1.0

### Operating system and version

Darwin 21.6.0

### Database type and version

MySQL 5.7.34

### Image driver and version

Imagick 3.5.1 (ImageMagick 6.9.6-2)

### Installed plugins and versions

-
CP Field Inspect	1.4.4
Craft Commerce	4.2.2
Guest Entries	3.0.1
Imager X	4.1.7
LJ Dynamic Fields	4.0.3
Minify	4.0.0-beta.2
Password Policy	4.0.0
Redactor	3.0.2
Twigpack	4.0.0-beta.4

**Comment by ryanmasuga** [comment]
I was _really_ hoping a straightforward route like a config var to bypass would be a viable solution.

**Comment by ryanmasuga** [comment]
My only suggestion would be to make sure it is clear in the docs to use your own fields for future devs wondering why built-in firstName and lastName fields are sometimes incorrect.

**Comment by brianjhanson** [comment]
Yep, definitely. We're going to update the [knowledge base article](https://craftcms.com/knowledge-base/front-end-user-accounts) and add a note in the Craft 4 upgrade documentation.
