### ISSUE TITLE
[4.x]: Entries filter not working with long field names

### ISSUE THREAD

**Issue by HannahDeWachter** [craftcms/cms#12311]
### Description
When trying to add a filter for entries, only a white rectangle is visible. (see screenshot)
<img width="1206" alt="Screenshot 2022-11-14 at 16 19 46" src="https://user-images.githubusercontent.com/55497252/201698566-51463139-9d66-445c-8a26-a01b01c1f1ab.png">
This is because there are long field names. When zooming out the browers, all fields are visible.

### Steps to reproduce

1. Go to entries
2. Add filter via the funnel in the search bar

### Expected behavior
Being able to use the filter without having to zoom out.

### Craft CMS version

4.3.1

### PHP version

8.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! It’s been fixed for the next release via #12320.

**Comment by brandonkelly** [comment]
Craft 4.3.2 is out with that fix.
