### ISSUE TITLE
[3.x]: isEditable requires publishPeerEntries permission to edit own entry

### ISSUE THREAD

**Issue by samhibberd** [craftcms/cms#12315]
### Description
`entry.isEditable` returns `false` when editing entry owned by currently logged in user, looks to have been introduced by the following commit, as a part of the 3.7.56 release and related to the `publishPeerEntries` permission.

https://github.com/craftcms/cms/commit/ba5875bcae1cbff2bd768351d7f69be523b39aa0

Downgrading to Craft 3.7.55.3 fixes also.

### Steps to reproduce
1. Upgraded to latest Craft 3.7.59 from a version before Craft 3.7.56.
2. Used `entry.isEditable` in a twig template that the currently logged in user is the author of.
3. Current user permissions for that entry include only `editEntries`, `createEntries` & `publishEntries` permissions
4. `entry.isEditable` returns `false`
5. Add in the `editPeerEntries` & `publishPeerEntries` permissions
6. `entry.isEditable` returns `true`

### Expected behavior
Should return `true` at 4 above?

### Craft CMS version

3.7.56

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next Craft 3 release.

**Comment by brandonkelly** [comment]
Craft 3.7.60 is out with that fix.
