### ISSUE TITLE
Easy Craft version download from the updates page

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#1232]
> Created by: Jamie Wade (hello@jamiewade.co.uk) on 2015/03/09 12:18:41 +0000
> Votes at time of UserVoice import: 1

-----------------------------------

From the updates page: /admin/updates

It would be nice if you could click on the build number and that version of Craft would download.

We of course use this: http://buildwithcraft.com/help/download-previous-versions, but it would be nice if downloading a specific version of Craft can be done from the control panel.

**Comment by brandonkelly** [comment]
Not exactly what was requested, but in Craft 3, installing a specific version can be done with Composer:

    composer require craftcms/cms:X.Y.Z
