### ISSUE TITLE
[3.x]: strtolower() in craftcms/cms/src/web/twig/Extension.php is preventing FeedMe from running

### ISSUE THREAD

**Issue by KarlBishop** [craftcms/cms#12334]
### What happened?

I'm not sure if this is an issue with FeedMe or Craft itself, but just discovered that the FeedMe plugin has completely stopped working and the error is being thrown by a file within the `craftcms` vendor folder.

See details of the issue here: [FeedMe completely stopped working #1204](https://github.com/craftcms/feed-me/issues/1204)

### Craft CMS version

Craft Pro 3.7.60

### PHP version

7.4.28

### Operating system and version

Linux 4.15.0-163-generic

### Database type and version

MySQL 8.0.28

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-26)

### Installed plugins and versions

- Asset Usage	2.3.1
- Blitz	3.12.6
- Bulk Edit	2.0.6
- Cloner	1.2.2
- Control Panel Nav	3.0.17
- Cookiebot	1.0.9
- Copy	1.2.4
- Dashboard Begone	1.0.1
- Element API	2.8.6.1
- Embedded Assets	2.11.3
- Feed Me	4.5.3
- fortrabbit Object Storage Volume	2.1.0
- Freeform	3.13.21
- Image Resizer	2.1.1
- Minify	1.2.11
- Patrol	4.0.2
- Redactor	2.10.10
- Relax	1.0.1
- Retcon	2.6.0
- Sentry Logger	1.3.1
- SEOmatic	3.4.42
- Sherlock	3.1.4
- Super Table

**Comment by boboldehampsink** [comment]
@brandonkelly seeing this too

<img width="828" alt="Screenshot 2022-11-17 at 07 53 51" src="https://user-images.githubusercontent.com/378974/202377171-cf4589fa-a3f4-43b2-9b3b-2753477b340f.png">

I'm using the twig sort filter with an arrow function which is a closure, so this fails

**Comment by brandonkelly** [comment]
Sorry about this! Craft 3.7.61 and 4.3.3 are out with a fix for this.
