### ISSUE TITLE
[4.3.2]: Sort filter no longer accepts closure

### ISSUE THREAD

**Issue by johndwells** [craftcms/cms#12338]
### Description

Given this snippet of twig:

```
{% for e in exhibitionsQuery|sort((a, b) => b.startDate|date('Ymd') <=> a.startDate|date('Ymd')) %}
    {{ basicExhibitionLink( e, 'full' ) }}
{% endfor %}
```

Results in a "TypeError" being thrown:

> strtolower(): Argument #1 ($string) must be of type string, Closure given

And it points to this line (https://github.com/craftcms/cms/blob/develop/src/web/twig/Extension.php#L492):

```
if (strtolower($arrow) === 'system') {
...
```

The entire sortFilter function appears to have been added in 4.3.2: if (strtolower($arrow) === 'system') {

### Craft CMS version

4.3.2

### PHP version

8.1

### Installed plugins and versions

-

**Comment by michaelrog** [comment]
Related: https://github.com/craftcms/cms/pull/12335

**Comment by i-just** [comment]
Thanks for reporting! There's a PR for it for both v3 and v4 now.

**Comment by brandonkelly** [comment]
Sorry about this! Craft 3.7.61 and 4.3.3 are out with a fix for this.
