### ISSUE TITLE
[4.3.3]: Fields in entry missing after deploy 

### ISSUE THREAD

**Issue by AnnaZLinka** [craftcms/cms#12347]
### Description
I created some fields on the local, after deploy to production they are not visible (to be used) in entry.

### Steps to reproduce
1. Add a lightswitch field
2. Works locally in entry, both in CMS and front-end
3. After deploy can't find it (in entry) on production. 

###  Other
*Production env is set to "production" so I don't have a possibility to check it in Settings.
The config file with that field exists in the code (for production). 

### Craft CMS version

4.3.3

### PHP version

8.1.7

### Operating system and version

Mac Big Sur 11.7

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi Anna, I assume you've applied the project config changes on production? 

If you did and the field is still not showing, you can try running: `./craft project-config/apply --force`. Alternatively, you can go to the control panel > Utilities > Project Config and click the "Reapply everything", which should do the same thing.

The `--force` part tells Craft to re-apply everything in `project.yaml` – not only the things that it thinks have changed.

**Comment by AnnaZLinka** [comment]
Hello I-just. Yes, config files changes are applied to production. I made as you suggested with "Reapply everything" (eve though there were no changes "waiting"), so it fixed the issue. Thank you for the advice :)
Although a bit weird at it doesn't apply all with deploy. (some changes are applied, some not). Is that a Craft 4.x.x bug?

**Comment by i-just** [comment]
Not a problem :) Glad to hear it's resolved! No, I wouldn't say that's a bug. It can occasionally happen due to e.g. caching.

**Comment by brandonkelly** [comment]
@AnnaZLinka There was a bug where this could occur if Craft or a plugin tried to make project config changes while other changes were being applied. If you send your `composer.json` and `composer.lock` files into support@craftcms.com we can take a look and see if any plugins you have installed are still doing that.
