### ISSUE TITLE
[4.x]: Conditional fields not auto-refreshing on users/globals/orders etc

### ISSUE THREAD

**Issue by CharlieGentle** [craftcms/cms#12348]
### Description
Conditional fields don't work properly when on an element type that doesn't auto save. Elements must be manually saved for the fields to display.

### Steps to reproduce

1. Add lightswitch field to user.
2. Add conditional field that is conditional on the lightswitch
3. Go to a user and switch on/off the lightswitch

### Expected behavior
Conditional field should show/hide based on switch.

### Actual behavior
Conditional field doesn't show/hide until user is saved.

### Craft CMS version

4.3.1

### PHP version

8.1

### Installed plugins and versions

-

**Comment by CharlieGentle** [comment]
This is fine for elements that autosave but the problem is that Globals, Users and Orders can't autosave.

**Comment by brianjhanson** [comment]
Yeah, that's a limitation with the current implementation. In Craft 5 we plan to consolidate Globals and Singles which will enable support on that front. Orders and users are a bit more complicated and will require another solution.

**Comment by Michael-Paragonn** [comment]
I just wasted a bunch of time troubleshooting why my conditional fields were not updating, finally arriving here after almost reporting this as a bug with a 3rd-party plugin. 🥴 

@brandonkelly Request: 🙏 If _Auto-Save Drafts_ is disabled for a site/environment, add a little notice in the field conditions side panel noting that _Auto-Save Drafts_ is needed for conditional fields to dynamically update... something like this:
![image](https://github.com/craftcms/cms/assets/118922451/29ddaadd-d8a1-4849-9718-6803659fb65b)
Thanks!

**Comment by brandonkelly** [comment]
Good suggestion @Michael-Paragonn! Just released Craft 4.5.6 with that: (77930eece6d481660354c82c37a70b76822caaf1)

<img width="586" alt="An Entry Condition setting, with a warning saying that `autosaveDrafts` must be enabled for the condition to take effect automatically." src="https://github.com/craftcms/cms/assets/47792/fc43a110-5f6c-449f-82db-539b14ef3a49">
