### ISSUE TITLE
[4.x]: Related To is giving no results on Element Index View

### ISSUE THREAD

**Issue by belkin** [craftcms/cms#12356]
### Description
Filter entries with Related To field.  

### Steps to reproduce

1. Create entry on Section A.
![image](https://user-images.githubusercontent.com/3419659/203252170-31a54bb1-3a6d-42dd-874e-61f54b190317.png)

2. Create entry on Section B with Entries field on Matrix block linked to the Entry on Section A.
![image](https://user-images.githubusercontent.com/3419659/203252748-c7a193e8-60c3-46d2-a8a2-2a9834aa82ff.png)
![image](https://user-images.githubusercontent.com/3419659/203252803-dc82acb2-0884-452f-b74b-4e928a21b725.png)

3. Filter view on Section A with Related To field to Entry from Section B.
![image](https://user-images.githubusercontent.com/3419659/203254050-87195d22-b0c3-489e-a64b-29155d767aba.png)
![image](https://user-images.githubusercontent.com/3419659/203254068-6d8d170d-9711-4caf-8167-ae0cb7191534.png)

### Expected behavior
Expected behavior is to see filtered view on Section A which are related to selected Entry from Section B.
I'm also using Element Relations plugin [https://plugins.craftcms.com/element-relations?craft4](url) to see the Relations.

### Actual behavior
There is no results on Apply.

### Craft CMS version

4.3.1

### PHP version

8.1.11

### Database type and version

MySQL: 8.0.27

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out. It's currently working as expected. If your relation is “nested” in a matrix field, you can’t use it in conditionals or filter by it in the CP. You can query those relations via a plugin or in a template, but you would have to be explicit about it: https://craftcms.com/docs/4.x/relations.html#going-through-matrix
