### ISSUE TITLE
[4.x]: user can't restore disabled source because source action button is hidden

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#12369]
### What happened?

when all custom sources are deleted and native sources are disabled, the source action button is not showing up so the user can't restore sources again.

actually for entries index page, there is a way which is creating new section so source action button appear again
but for custom element types with one native source,  after disabling that native source the user can't restore that source again

### Craft CMS version

4.3.3

**Comment by i-just** [comment]
That's a good catch! Thanks for reporting. I've just submitted a PR for it.

**Comment by brandonkelly** [comment]
Fixed via #12377 for the next release.

**Comment by brandonkelly** [comment]
Craft 4.3.4 is out with that fix.
