### ISSUE TITLE
[4.x]: Can't login to CP anymore after updating from 4.3.1 to 4.3.3 

### ISSUE THREAD

**Issue by mudechs** [craftcms/cms#12372]
### Description

After updating a clients craft 4.3.1 installation to 4.3.3 via the CP i got logged out and re-login stopped working. This is a showstopper and very critical to me. On this webserver i can not use composer because i dont have access via the terminal. I always have to update via the CP functionality.

### Steps to reproduce

1. enter the websites url to the login page
2. enter the correct credentials
3. press the login button

### Expected behavior
Login and get redirected to the dashboard

### Actual behavior
Page just refreshes and no redirect to dashboard happens. Neither the console nor the network diagnosis encounters a error.

### Craft CMS version

4.3.3

### PHP version

8.1

### Database type and version

10.3-MariaDB

### Installed plugins and versions

-  "craftcms/redactor": "3.0.2",
- "elleracompany/craft-cookie-consent": "4.0.4",
- "ether/seo": "v4.0.3",
- "leowebguy/device-detect": "1.0.1",
- "marionnewlevant/twig-perversion": "3.0.0",
- "masugadesign/linkvault": "4.0.1",
- "mmikkel/cp-field-inspect": "1.4.4",
- "putyourlightson/craft-sprig": "2.3.0",
- "solspace/craft-freeform": "4.0.8"

**Comment by mudechs** [comment]
Update: even clients can't login on the websites frontend. When i try to login, i get redirected now to the cp login url instead of "/members" wich is a site on the frontend.

**Comment by mudechs** [comment]
Update: i just downgraded back to 3.3.1 and it works like before. Now i have time to wait for a fix.

**Comment by i-just** [comment]
Hi, thanks for reaching out. I'm having trouble replicating this issue. Are you able to access the application logs (`storage/logs/web*.log`)? There are plugins that allow you to access them from the control panel. Is there anything in the logs that could suggest what's happening?

**Comment by mudechs** [comment]
hi @i-just. Thx for your reply. It is very difficult to get a idea what can be wrong in the log, but i see is, that i'm getting a lot of the following messages:

`2022-11-24 12:00:13 [web.WARNING] [craft\elements\db\ElementQuery::prepare] Element query executed before Craft is fully initialized. {"memory":1824696} `

I will now make a copy of the website, disable plugins, update to 4.3.3 and then step by step reactivate my plugins. Since there are sensitive data in the log files i can't post the entire here. Is there another way you can look into it?

**Comment by i-just** [comment]
Thanks for an update. To cover all the basics, could you try (or have you already tried) clearing all the cookies or using a private/incognito mode? Disabling all the plugings, updating to 4.3.3 and testing if you can login before re-enabling any plugins is also a good idea.

I understand you not wanting to post sensitive data from the logs. If you get stuck, would you be willing to send your database backup (pre update), `composer.json` and `composer.lock` to support@craftcms.com so that we can dig deeper?

**Comment by mudechs** [comment]
i have tested it now on a dev environment and disabled the plugins by setting:

`->disabledPlugins('*')`

then i updated from 4.3.1 to 4.3.3 and the same issue happens. event on deleting cookies or surfing private/incognito

its very strange.....

**Comment by brandonkelly** [comment]
@mudechs Are you able to send your Composer files and a database backup over to support@craftcms.com? We can try to replicate the issue from there.

**Comment by mudechs** [comment]
@brandonkelly Tyvm for your reply Brandon. I sent the requested files to you.

**Comment by mudechs** [comment]
solved: i had two users where had "enabled" = 0 in the elements table. That was the reason why i could not log in anymore after the update. Big shadout to the craft support team @i-just @brandonkelly who figured this out!
