### ISSUE TITLE
Required fields not showing inside tabs when trying to edit from modal.

### ISSUE THREAD

**Issue by vitalijalbu** [craftcms/cms#12378]
### Description
I have a entry and when want to edit from modal and publish it it shows error, that's because inside the tab i have a required field which is empty.
So is missing the error tab UI inside the modal.

### Steps to reproduce

1. Create a draft entry
2. Must have a required field
3. Publish the draft without input nothing inside the field
4. Error toast

### Actual behavior
![Screenshot 2022-11-24 alle 13 41 09](https://user-images.githubusercontent.com/40239902/203787328-824494da-e83c-469e-b5ba-f4a9ce1efdf3.png)

![Screenshot 2022-11-24 alle 13 45 03](https://user-images.githubusercontent.com/40239902/203787811-5b8ff340-a47f-4b71-84be-a89a1e27223e.png)

### Craft CMS version

last

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out. We are aware of this problem and have an issue created for it already: #12290. You can follow the updates there.
