### ISSUE TITLE
[4.x]: Duplicate entries not working

### ISSUE THREAD

**Issue by jlachancekffein** [craftcms/cms#12370]
### Description
Since updating Craft 3 to version 4, duplicating entries no longer works.

Clicking on the Duplicate button calls the elements/save action -> `actionSave()` instead of calling the `actionDuplicate()` method.

So, a new entry is created, but all the fields is empty.

To test, I dump the $_POST variable in the `actionSave` method of `ElementsController`. Here is an example of the dump:

```php
[
    'CRAFT_CSRF_TOKEN' => 'K9qpUkqplhN7TS1t33n5kxsIlY0euu8IkxeUZZ_uR8RqoLwoB0LC4gbf5039W0w8vDaPbfh_5NLrzgWS9o4pmbi0MeFNdMG62YMgTuCeqJ9YIcvLkjgzg14sjh7oVxmgfgwMJ3T7QAmGrp_fb0XqiSjYTSb0T0BEd509HBYJK1WgJOzkJXWsHQVhotj56lSOelnrT-yRGRzdo1sKdVQshRWm_HZ9pL9S045F3V3OMPOcDZw8-fN_RDuXrHq90ynFbioMjgLpDM1KgOra_D2kkrgZrt3RANAvR_SKvbJEf9b_yvo6Fvmqql0F5mpPvyvQY3qXRmhqFEefdWzlyqnnJBOevGCpdV-1FSwbGPBILSRFQjTtaqa-cBneV103-5euqS3bNCXa'
    'title' => '10 box office bombs that have aged surprisingly well'
    'elementId' => '10281051'
    'siteId' => '1'
    'action' => 'elements/save'
    'redirect' => 'fe40f9c71ef4850a54cebf555dcc37aa10f85552a5ca01bff64bbeec17c0ab83http://espresso-msn.kffein/admin/entries/msn_articles_channel#'
    'slug' => 'top-10-box-office-bombs-that-aged-well-5-1-2-1-5'
    'authorId' => '5377983'
    'enabled' => '1'
    'notes' => ''
    'addAnother' => '1'
]
```

To make sure that the problem does not come from my side, I
- Disable all plugins
- Disable all modules
- Delete the cpresources folder
- Delete the storage/runtime folder

Also I have no js error.

### Steps to reproduce

1. Go to the detail of a channel entry.
2. Click on the duplicate button

### Craft CMS version

4.3.3

### PHP version

8.0.13

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out. Can you please help me clarify a few things? Are you on the entry edit page (where you edit individual entry) or on the entries index page (where you see the list of the entries). Which button are you using to trigger duplication? The reason I ask is because you've mentioned a "duplicate" button in the context of "details of a channel entry" and there is no duplicate button on the entry edit page, just "save as a new entry".

**Comment by jlachancekffein** [comment]
Hello, you are completely right, the problem was the translation of the fields in the `src/craftCMS/translations/fr/app.php` file. -> `'Save and add another' => 'Duplicate`

So the button displayed `Duplicate` instead of `Save and add another`.

I checked everything else except the translation file that we never modify, except for this client.

Anyway, sorry for the inconvenience.

**Comment by i-just** [comment]
Ah, that's a good catch! Glad you got to the bottom of it :)
