### ISSUE TITLE
[4.3.3]: Image transforms: automatically generated directories

### ISSUE THREAD

**Issue by idleog** [craftcms/cms#12374]
### What happened?

Can anyone explain this: a lot of directories appearing in the assets directory (see screenshot)

<img width="606" alt="Bildschirm­foto 2022-11-24 um 09 43 08" src="https://user-images.githubusercontent.com/870071/203742305-4dba8a97-29f9-4403-bbfc-708cbafacec3.png">

Cheers
Peter

### Craft CMS version

4.3.3

### PHP version

8.1.10

### Operating system and version

MAMP6.6.4 on MacOS13

### Database type and version

Mysql

### Installed plugins and versions

"craftcms/cms": "4.3.3",
    "craftcms/feed-me": "5.0.4",
    "craftcms/redactor": "3.0.2",
    "doublesecretagency/craft-cpbodyclasses": "2.3.0",
    "doublesecretagency/craft-cpcss": "2.5.0",
    "idleog/craft-goeldi": "^4.0",
    "nystudio107/craft-cookies": "4.0.0",
    "sebastianlenz/linkfield": "2.1.4",
    "verbb/cloner": "2.0.3",
    "vlucas/phpdotenv": "^5.4.0"

**Comment by i-just** [comment]
Hi, thanks for reaching out. Craft CMS creates transforms based on: the transforms you specify in settings > assets > image transforms, the transforms you specify in your codebase (if you choose to do that) and also, based on what it needs for the control panel. The control panel transforms will be used on the assets index page or in the entry editor if you're adding images to your entry. 

For example, I have 2 images specified in my volume (square one and rectangular one). If I then visit assets listing page and have my assets show in a table, I see 4 new transform folders created. If I switch that page to show thumbnails, another 4 transform folders are created.

<img width="365" alt="Screenshot 2022-11-24 at 14 14 24" src="https://user-images.githubusercontent.com/4500340/203805518-8b984912-2785-4067-b918-5f1870599c69.png">

Hope this helps clear things up!

**Comment by idleog** [comment]
Hi, thanks for the quick answer!
I wonder if this is the right place for these transform-directories? 
cheers
Peter

**Comment by i-just** [comment]
It's the default place. You can specify where the transforms should be created in your volume settings though (settings > assets > volumes > <your volume>. You can change a transform filesystem and/or subpath, so that it's more suited to your needs/liking.

**Comment by idleog** [comment]
Ok, that's new in Craft4 then.
I think it would be nice if places of CP-Transforms and Frontend-Transforms could be seperated. But not really a big issue.

Thanks a lot
Peter
