### ISSUE TITLE
[4.x]: Missing entry template hooks from Craft 3

### ISSUE THREAD

**Issue by ddnetters** [craftcms/cms#12385]
### Description
Craft 3 offered a wide range of [template hooks](https://craftcms.com/docs/3.x/extend/template-hooks.html#control-panel-template-hooks). Especially the [cp.entries.edit](https://github.com/craftcms/cms/blob/v3/src/templates/entries/_edit.html#L41) was of great use to display context dependent, content related warnings to CMS users. One of our craft projects used that hook to encourage user into structuring entries a certain way without making it a hard requirement by blocking save's. For example, it was used to display a notification if an entry contained less than X video embed based on the article's length.

Craft 4 greatly reduced the number of [hooks](https://craftcms.com/docs/4.x/extend/template-hooks.html#control-panel-template-hooks). 

### Steps to reproduce

1. Register an old view hook
```php
        Craft::$app
            ->view->hook('cp.entries.edit', new SomeHandler);
```
2. Nothing 

### Expected behavior

1. Register a view hook
```php
        Craft::$app
            ->view->hook('cp.entries.edit', new SomeHandler);
```
2. `SomeHandler::_invoke` gets called.  

### Actual behavior

1. Register a view hook
```php
        Craft::$app
            ->view->hook('cp.entries.edit', new SomeHandler);
```
2. Nothing happens because the hook doesn't exist

### Craft CMS version

4.4.x

### PHP version

Not relevant

### Operating system and version

Not relevant

### Database type and version

Not relevant

### Image driver and version

Not relevant

### Installed plugins and versions

Not relevant

**Comment by i-just** [comment]
Hi, thanks for getting in touch. Yes, in Craft 4, element specific CP template hooks have been removed, but you can refer to this plugin upgrade guide: https://craftcms.com/docs/4.x/extend/updating-plugins.html#template-hooks to see how you can make your functionality work for v4.

**Comment by tudorradubarbu** [comment]
This is basically just a horrible implementation. It gets too complex to edit a big HTML loaded as a string.

**Comment by brandonkelly** [comment]
@tudorradubarbu Entry edit pages are defined as “control panel screens” now, which are declarative as opposed to a big Twig template. It makes them capable of being used as both a full page editor, or used within a slideout modal (like when you double-click on an entry’s status icon). So they don’t actually have their own template anymore, hence no more template hooks.

**Comment by leogenot** [comment]
Hi @tudorradubarbu did you manage to upgrade to this new implementation? The doc is not helpful regarding this topic and I can't figure out how to upgrade my plugin...

**Comment by ddnetters** [comment]
@leogenot here's some rough code to inject html into the control panel: https://gist.github.com/ddnetters/a33f9c72cefa2a68fea63a04ded905ef
