### ISSUE TITLE
[4.3.3]: Update to Craft 4 Send email SSL routines:ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by ivesho** [craftcms/cms#12387]
### Description

After updating from Craft Pro 3.7.61 to Craft Pro 4.3.3, the email system get problem.
Error message :

```
"Connection could not be established with host "ssl://{HOST}:465": stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:1408F10B:SSL routines:ssl3_get_record:wrong version number"
```

![image](https://user-images.githubusercontent.com/48641341/204448250-d95be692-2150-4dbb-9fa3-3503fd2251ec.png)

I tried to fix it , change the setting on operating system or PHP, still not work.
I do not know why, the operating system and PHP is same, it's fine in Craft Pro 3.7.61, but Craft 4 can't send the email.

Thank you!

### Steps to reproduce

1.Transport Type: SMTP
2. Use authentication: false
3. Encryption Method: tls
4. Timeout: 60

### Steps to reproduce

1.

### Craft CMS version

Craft Pro 4.3.3

### PHP version

8.1.11

### Operating system and version

Windows Server 2019 IIS10

### Installed plugins and versions

-

**Comment by brianjhanson** [comment]
Craft uses [Symfony Mailer](https://symfony.com/doc/current/mailer.html) as of [4.0](https://craftcms.com/docs/4.x/extend/updating-plugins.html#symfony-mailer) which could be the culprit here. Can you share your mail configuration?

It also looks like that error is sometimes thrown when the email server doesn't speak TLS. Were you using TLS previously? Or is that a new piece to the config?

**Comment by ivesho** [comment]
My mail configuration:
1.Transport Type: SMTP
2. Use authentication: false
3. Encryption Method: tls
4. Timeout: 60

Yes, I am using TLS until now, because the mail server I used need starttls.

In craft 4, when I set encryption method null or SSL, got the same error message, but in craft 3 return someting about need to use TLS message.

**Comment by brianjhanson** [comment]
Do you have any custom mail configuration settings in your `app.php` file? Do the log files in `storage/logs` have any additional information that might be helpful?

Is there any additional information you can provide about what email server you're connecting to so I can try to reproduce the issue? 

This is sounding like a configuration issue over a Craft core issue. I did some quick googling and it seems like you may need to [set the `verify_peer` option to `false`](https://github.com/laravel/framework/discussions/41385) (that's a bout Laravel, but the issue is possibly the same). Updating that option would require [customizing the mailer configuration](https://craftcms.com/docs/4.x/config/app.html#mailer).

**Comment by ivesho** [comment]
I don't have custom mail setting.
![image](https://user-images.githubusercontent.com/48641341/204703498-ce11675d-c0aa-4ee7-81da-9b0bcad35141.png)

When I send the test email from cp email settings, I got this log :
(P.S. I blank the host value string on the log)
> 2022-11-30 04:07:14 [web.INFO] [yii\db\Connection::open] Opening DB connection: mysql:host=192.168.100.30;dbname=MOC-Artist;port=3306 {"memory":8909584} 
> 2022-11-30 04:07:14 [web.INFO] [yii\web\Session::open] Session started {"memory":11875288} 
> 2022-11-30 04:07:14 [web.INFO] [modules\artistmodule\ArtistModule::init] Artist module loaded {"memory":13135776} 
> 2022-11-30 04:07:14 [web.INFO] [yii\mail\BaseMailer::send] Sending email "This is a test email from Craft" to "ivesho@utron.com.tw" {"memory":22826432} 
> 2022-11-30 04:07:14 [web.ERROR] [yii\symfonymailer\Mailer::sendMessage] Connection could not be established with host "ssl://edm.moc.gov.tw:465": stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
> error:1408F10B:SSL routines:ssl3_get_record:wrong version number {"memory":22907136} 
> 2022-11-30 04:07:14 [web.INFO] [application] Request context:
> $_GET = [
>     'p' => 'admin/settings/email'
> ]
> 
> $_POST = [
>     'CRAFT_CSRF_TOKEN' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
>     'action' => 'system-settings/test-email-settings'
>     'redirect' => '91c8c922f9cf010d27c827a728b472d67efc87e74177ac68c8e6eb1a62aeb4ddsettings'
>     'fromEmail' => 'artistsys@moc.gov.tw'
>     'replyToEmail' => ''
>     'fromName' => 'MOC'
>     'template' => ''
>     'transportType' => 'craft\\mail\\transportadapters\\Smtp'
>     'transportTypes' => [
>         'craft\\mail\\transportadapters\\Sendmail' => [
>             'command' => '/usr/sbin/sendmail -bs'
>         ]
>         'craft\\mail\\transportadapters\\Smtp' => [
>             'host' => '•••••.•••••.gov.tw'
>             'port' => '465 '
>             'useAuthentication' => '0'
>             'username' => '$USERNAME'
>             'password' => '•••••••••'
>             'encryptionMethod' => 'tls'
>             'timeout' => '60'
>         ]
>         'craft\\mail\\transportadapters\\Gmail' => [
>             'username' => ''
>             'password' => ''
>             'timeout' => '10'
>         ]
>     ]
> ]

Sorry, I don't have any information about email server, I only know how to connect, because it's governmental.

**Comment by ivesho** [comment]
I tried to customize the mailer configuration like this

![image](https://user-images.githubusercontent.com/48641341/204771052-e230eaa1-6f14-4c45-a2cf-56519047871e.png)


It got the same error message.
I'm not sure my customized configuration was right or not

![image](https://user-images.githubusercontent.com/48641341/204772451-d2acab3f-d9e6-48cf-8c8e-7f709f67f644.png)

**Comment by brianjhanson** [comment]
I think you're pretty close, but digging through the code it looks like you might have to set `verify_peer` via `don` only (there's probably another way, but I wasn't able to find it easily). 

Give this a try:

```php
'components' => [
    'mailer' => function() {
        $config = App::mailerConfig();

        $adaptor = \craft\helpers\MailerHelper::createTransportAdapter(
            \craft\mail\transportadapters\Smtp::class,
            [
                'host' => '{HOST}',
                'port' => {PORT},
                'useAuthentication' => false,
                'timeout' => 60,
                'encryptionMethod' => 'tls'
            ]
        );

        $config['transport'] = [
            'dsn' => 'smtp://{HOST}:{PORT}?verify_peer=0'
        ];

        return Craft::createObject($config);
    }
]
```

**Comment by angrybrad** [comment]
As @brianjhanson noted, setting `verify_peer` to false effectively disables SSL validation. While it will probably work around the error, it's a potential security issue.

My guess is that the SSL certificate on the server your trying to connect to is misconfigured, or (more likely), the server doesn't know how to respond to TLS traffic.

I'd start by verifying the SSL config on the SMTP server and checking the email server's logs for clues.

**Comment by brandonkelly** [comment]
@ivesho Any luck with this? Can the issue be closed?

**Comment by ivesho** [comment]
I set verify_peer to false still not work. 
The email server provider can't give me more information, they think this problem is from my website, but it was fine when used my own email server. 

It's fine, I can keep using Craft 3.

Thank you all so much for helping !

**Comment by jrrdnx** [comment]
> In craft 4, when I set encryption method null or SSL, got the same error message, but in craft 3 return someting about need to use TLS message.

@ivesho I'm finding that the Encryption Method dropdown isn't showing for me on a fresh install of Craft 4.3.8.2 (screenshot below), so I'm curious if it's not taking the config setting into account and using SSL despite having this set to TLS.

Apologies if this is unrelated.

![Screenshot 2023-02-15 at 16 00 02](https://user-images.githubusercontent.com/4584671/219165559-cb4548ac-9da6-4cd6-a4f3-4c311634975a.png)
![Screenshot 2023-02-15 at 16 00 13](https://user-images.githubusercontent.com/4584671/219165578-4c590ba7-a677-44e4-ac23-be756950e6e8.png)

**Comment by brandonkelly** [comment]
@jrrdnx Symfony Mailer wasn’t respecting the Encryption Method setting to begin with, which is why it was removed. TLS verification will be performed [by default](https://symfony.com/doc/current/mailer.html#tls-peer-verification).

**Comment by mark-chief** [comment]
Apologies to open this again, - but what is the fix for this? 
I have a Craft 3->4 site that is no longer sending mail, using an SMTP server.

Thanks

**Comment by brandonkelly** [comment]
@mark-chief Please reach out to support@craftcms.com. We should be able to help look into it from there.
