### ISSUE TITLE
[4.3.3]: Plain Text Field in CP (Asset Layout Field) - representation

### ISSUE THREAD

**Issue by thomasbendl** [craftcms/cms#12391]
### Description
Plain Text Field Type ignores the no line break setting in Asset Field Layout. Always shown the line break version in CP.

### Steps to reproduce

1. create a simple Plain Text Field (Name: Alternative Text, handle: alt, Allow line break: no)
2. ad it to an existing Media Asset Field Layout

### Expected behavior
should show a simple Input Field

### Actual behavior
shows an Input Field with line breaks allowed

### Craft CMS version

4.3.3

### PHP version

8.1.1

### Operating system and version

macOS Monterey 12.4

### Database type and version

mysql, 5.7

### Image driver and version

Imagick 3.6.0

### Installed plugins and versions

- Redactor 3.0.2
- Redirect Manager 2.0.0
- SEOmatic 4.0.15
- Vite 4.0.3

**Comment by i-just** [comment]
Hi, thanks for reaching out. 

It sounds like the `alt` field you're seeing when editing an asset is the native field that ships with Craft CMS, and that field allows for line breaks.

You are not actually allowed to assign a field with handle `alt` to volume's field layout as `alt` is a reserved word in that context. If you change your field handle to e.g. `alternativeText` and assign it to the the volume field layout, the 'Allow line breaks' setting will be respected.

Hope this helps!

**Comment by thomasbendl** [comment]
thank you - I just implemented it!
