### ISSUE TITLE
[4.3.4]: This plugin isn't compatible with your version of Craft

### ISSUE THREAD

**Issue by mind63** [craftcms/cms#12401]
### Description
Seems like with Craft 4.3.4 an old problem came up again, see [#5299](https://github.com/craftcms/cms/issues/5299)
I can not install any Plugins any more: "This plugin isn't compatible with your version of Craft"

With 4.3.3 ist was working.

### Craft CMS version

4.3.4

### Installed plugins and versions

-

**Comment by timkelty** [comment]
This was due to an issue with a Plugin Store deployment, but should be resolved now.

Thanks for reporting!
