### ISSUE TITLE
[4.x]: Checking keycodes in JavaScript for input validation on the Number and Money fields isn't the best.

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#12412]
### Description

Checking keycodes for JavaScript input validation on the Number and Money fields isn't the best.

### Steps to reproduce

1. On macOS, swap the keyboard layout to Hungarian.
2. On US-based QWERTY keyboards, the layout will look like this:

![CleanShot 2022-11-30 at 12 02 39](https://user-images.githubusercontent.com/61869/205169062-aa87b570-3627-4eed-bbb7-782ee263d76a.png)

3. On non-US QWERTY keyboards, it'll look closer to:

![Screenshot 2022-11-30 at 22 33 21](https://user-images.githubusercontent.com/61869/205169212-a2a538a1-b6c0-45fb-bd6c-d5a36f8ca856.png)

4. Notice that the `0` is to the left of `1` on non-US QWERTY keyboards and doesn't exist on US QUERTY keyboards.

5. Trying to type the `0` on a non-US QUERTY keyboard won't input anything in a Number or Money field.

6.  Typing CTRL-Option-0 is a workaround for both non-US and US QWERTY keyboards to get it to enter a `0` successfully.

7. Typing the three keys immediately to the right of 9 (on either a non-US or US QWERTY keyboard) will incorrectly let ö, ü, and ó pass validation and be entered into those fields (even though server-side validation fails because they are not numeric).

Relying strictly on keycodes in JavaScript isn't reliable across different keyboard layouts.

https://github.com/craftcms/cms/blob/develop/src/fields/Number.php#L258-L280

https://github.com/craftcms/cms/blob/develop/src/fields/Money.php#L254-L276

Probably worth checking the codebase for anywhere else we're checking for keycodes that need to consider localization.

### Craft CMS version

4.3.4

### PHP version

8.0

### Operating system and version

macOS

### Database type and version

n/a

### Image driver and version

n/a

### Installed plugins and versions

none

**Comment by brandonkelly** [comment]
Fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 3.7.62 and 4.3.5 are out with that fix.
