### ISSUE TITLE
[4.3.x]: GraphQL live preview broken

### ISSUE THREAD

**Issue by jan-thoma** [craftcms/cms#12420]
### Description
We use a headless setup with graphql. When we want to get a preview of a entry we pass along the token from we get in the query params as `'x-craft-token'` header in the grapqhl request we send to backend. This seems to broken from 4.3.x on.

### Expected behavior
Get the data of the draft/preview via graphql

### Actual behavior
Get an empty response

### Craft CMS version

4.3.3

### PHP version

8.1

### Operating system and version

Docker

### Database type and version

MySQL

### Image driver and version

gd

### Installed plugins and versions

-

**Comment by brianjhanson** [comment]
I'm having trouble replicating this one (but on a very simple project). Are you using a framework to power the front end of this? If so, which one are you working with? 

Are there any other details you can provide about your setup so I can try to replicate?

**Comment by jan-thoma** [comment]
> 



> I'm having trouble replicating this one (but on a very simple project). Are you using a framework to power the front end of this? If so, which one are you working with?
> 
> Are there any other details you can provide about your setup so I can try to replicate?

Let's get more into detail.

We use Vue.js with SSR based on Vite as the frontend driver for this project.

When a live preview is called from the panel with the preview button. We route it to the frontend. There we read out the query parameters to see if we get a `x-craft-preview `or `x-craft-live-preview` query parameter.

If it's a preview request we add the token as `x-craft-token' to the header when we make a graphql-reqest to the backend. This worked nice but stopped to work somewhere around 4.3.x.

As mentioned in the reply above. When i use the `id` parameter i a graphql reuqest together with the `x-craft-token` in the request header craft can't find the corresponding entry an gives me back an empty array. If i omit the `id` it is able to return the entry together with all entries and the correct preview data.

**Comment by jan-thoma** [comment]
I can provide a database if it's help

**Comment by jan-thoma** [comment]
Dug a little bit deeper. I Think the problem can reproduced this way.

**Reproduction**
1. Create an entry, save and publish the entry.
2. Make a change to this entry and don't publish it.
3. Now via GraphQL and the preview token supplied in the header as `x-craft-token` get the ID of the changed entry by it's slug

```
{
    entry(slug: "my-slug") {
        title
        id
    }
}
```
4. Use the id from the query result to retrieve the entry in another query
```
{
    entry(id: "556") {
        title
        id
    }
}
```
5. Now the result should be `null`
```
{
    "data": {
        "entry": null
    }
}
```

I our scenario we are dependent to retrieve the entries ID bootstrap the routes in the frontend. Then the matched route will be fetched by it's id in the next step. This lead to the behavior mentioned above.
