### ISSUE TITLE
descendants property missing for graphql queries of category

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#12427]
### Description
I noticed that we can query for `children` of category, but we cannot query for `descendants` - using graphql.

### Craft CMS version

4.3.4

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
We’ve added `ancestors` and `descendants` category fields for 4.4 :tada: (#12437)

**Comment by brandonkelly** [comment]
4.4 is out!
