### ISSUE TITLE
[4.x]: Can't Disable Welcome page

### ISSUE THREAD

**Issue by matthewstick** [craftcms/cms#12428]
### Description

You can't disable the welcome page that lives at /index .

I get that's an important page, but we should be able to have a setting that doesn't show this.  In production mode, this isn't something you want to reveal to users, expose to bots, or have show up in search results.

I think simplest to have /index disabled in production mode - aka, only show it in dev mode.  Or have the ability to not show it in the global config file.

We see in our server logs a lot of hits on /index - probably bots looking to hack it.

Right now as a work around I had to make an index page and set it to load the 404.

### Steps to reproduce

1. go to /index 

### Expected behavior

An error 404 (at least if in mode production, or not specifically enabled in production for settings)

### Actual behavior

Shows the craft welcome page

### Craft CMS version

3 and 4

### PHP version

N/A

### Operating system and version

N/A

### Database type and version

N/A

### Image driver and version

N/A

### Installed plugins and versions

-
N/A

**Comment by i-just** [comment]
Hi, thanks for reaching out. I’m not sure if I understand the problem correctly. Is it that you don’t want anyone to be able to see the welcome page that ships with a fresh installation of Craft CMS if they visit either <your_domain> or <your_domain>/index?

**Comment by matthewstick** [comment]
That's right!  I like the page, but it should be disable-able, especially in production mode.  My security team flagged it as a risk.

**Comment by i-just** [comment]
Thanks for clarifying. You should replace the contents of the `templates/index.twig` file that ships with Craft with whatever you want, or you can remove it entirely if you have, e.g. a “singles” section set up to serve as a homepage and you configure it to use a different template file (or even a hidden template file). You can find more info on templating at https://craftcms.com/docs/4.x/dev/.

**Comment by matthewstick** [comment]
Please don't mark this as closed. Your note above is solving something different.

So there is no templates/index.twig in my sites.  The welcome page gets shown even by a lack of templates/index.twig.

**Comment by thupsi** [comment]
What you are describing should not be possible. Something weird is happening. The welcome page definitely is just the default index.twig in the templates folder. Are you using some kind of caching maybe?
