### ISSUE TITLE
[4.x]: login form returns HTTP 400 error when submitting with wrong credentials (and async)

### ISSUE THREAD

**Issue by arifje** [craftcms/cms#12433]
### Description

When I submit the login form with Axios (async), and wrong username/password combination is entered, I am getting a http 400 error returned, instead of a readable response message.

### Steps to reproduce / example

```
<script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>

<form method="post" accept-charset="UTF-8" id="loginForm">

  {{ csrfInput() }}
  {{ actionInput('users/login') }}

  <label for="loginName">Username or email</label>
  {{ input('text', 'loginName', craft.app.user.rememberedUsername, {
    id: 'loginName',
    autocomplete: 'username'
  }) }}

  <label for="password">Password</label>
  {{ input('password', 'password', null, {
    id: 'password',
  }) }}

  <label>
    {{ input('checkbox', 'rememberMe', '1') }}
    Remember me
  </label>

	<button>Login</button>

  {% if errorMessage is defined %}
    <p>{{ errorMessage }}</p>
  {% endif %}

</form>

<script>
$(function() {
	$('#loginForm').on('submit', function(e) {
	
    	e.preventDefault();
    	var formData = $(this).serialize();

    	$.ajax({
        	url: '/',
        	contentType: "application/x-www-form-urlencoded",
        	dataType: "json",
        	type:'POST',
        	data: formData,
        	success: function(result) {
            	console.log(result);
        	}
    	});
 	});
});
</script>
```

### Expected behavior

200 response with error message

### Actual behavior

Retuns a http 400 error, sets error message in session.

### Craft CMS version

4.3.3

### PHP version

8.1.12

### Operating system and version

Ubuntu

### Database type and version

MariaDB

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out. `users/login` is returning 400 on purpose in this case. What you can do is catch this error in your JavaScript and process it as you wish:
```
success: function(result) {
    console.log(result);
},
error: function(result) {
    console.log(result.responseJSON);
}
```

example response JSON: 
`{ errorCode: "invalid_credentials", message: "Invalid username or password." }`

Hope this helps!
