### ISSUE TITLE
[4.x]: email/username uniqueness shouldn't factor inactive users

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#12431]
- [x] need to validate user when activating (username, email)
- [x] make sure we aren't relying on a single/first user when querying for users (eg with `getUserByUsernameOrEmail`)

**Comment by stephanedemotte** [comment]
A User cannot rollback to an old email, if he a user change his email the old email become a inactive user... When he try to rollback he get `has already been taken.`

**Comment by timkelty** [comment]
@stephanedemotte can you elaborate on your use-case?

One way I could see this happening is:
- foo@example.com has an active account
- changes email to bar@example.com
- Something creates an inactive user for foo@example.com (e.g. user is logged out and creates a guest cart in Commerce with a foo@example.com email)
- At this point, the user is not able change their email back to foo@example.com, as there is an existing (inactive) user

**Comment by timkelty** [comment]
Closed in favor of #12712

**Comment by brandonkelly** [comment]
Fixed for Craft 4.4 via #12712.
