### ISSUE TITLE
[4.x]: Upgrading to v4 Migration errors (Integrity constraint violation)

### ISSUE THREAD

**Issue by FabioIaderosa** [craftcms/cms#12434]
### Description

Upgrading from Craft 3 to 4. 
After run php craft migrate/all came this error message

Integrity constraint violation: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`varaxose_gsdevcraft4`.`craft_matrixblocks_owners`, CONSTRAINT `craft_fk_bpyjmdyzhklbrwsnmpjfgirursanuobuhctv` FOREIGN KEY (`ownerId`) REFERENCES `craft_elements` (`id`) ON DELETE CASCADE)
The SQL being executed was: INSERT INTO `craft_matrixblocks_owners` (`blockId`, `ownerId`, `sortOrder`) 
SELECT `id`, `ownerId`, COALESCE(`sortOrder`, 1) 
FROM `craft_matrixblocks`

Migration: craft\migrations\m220213_015220_matrixblocks_owners_table

Output:

    > dropping {{%matrixblocks_owners}} if it exists ... done (time: 0.005s)
    > create table {{%matrixblocks_owners}} ... done (time: 0.005s)
    > add foreign key craft_fk_uivfaripplpoasgwsdovkhizacerpwfljpxj: {{%matrixblocks_owners}} (blockId) references {{%matrixblocks}} (id) ... done (time: 0.009s)
    > add foreign key craft_fk_bpyjmdyzhklbrwsnmpjfgirursanuobuhctv: {{%matrixblocks_owners}} (ownerId) references {{%elements}} (id) ... done (time: 0.009s)
    > execute SQL: INSERT INTO {{%matrixblocks_owners}} ([[blockId]], [[ownerId]], [[sortOrder]]) 
SELECT [[id]], [[ownerId]], COALESCE([[sortOrder]], 1) 
FROM {{%matrixblocks}} ...Exception: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`varaxose_gsdevcraft4`.`craft_matrixblocks_owners`, CONSTRAINT `craft_fk_bpyjmdyzhklbrwsnmpjfgirursanuobuhctv` FOREIGN KEY (`ownerId`) REFERENCES `craft_elements` (`id`) ON DELETE CASCADE)
The SQL being executed was: INSERT INTO `craft_matrixblocks_owners` (`blockId`, `ownerId`, `sortOrder`) 
SELECT `id`, `ownerId`, COALESCE(`sortOrder`, 1) 
FROM `craft_matrixblocks` (/home/varaxose/www/dev.gastrosocial.ch/varaxose.myhostpoint.ch/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /home/varaxose/www/dev.gastrosocial.ch/varaxose.myhostpoint.ch/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `cr...')
 /home/varaxose/www/dev.gastrosocial.ch/varaxose.myhostpoint.ch/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('INSERT INTO `cr...')
 /home/varaxose/www/dev.gastrosocial.ch/varaxose.myhostpoint.ch/vendor/yiisoft/yii2/db/Migration.php(219): yii\db\Command->execute()
 /home/varaxose/www/dev.gastrosocial.ch/varaxose.myhostpoint.ch/vendor/craftcms/cms/src/migrations/m220213_015220_matrixblocks_owners_table.php(36): yii\db\Migration->execute('INSERT INTO {{%...')
 /home/varaxose/www/dev.gastrosocial.ch/varaxose.myhostpoint.ch/vendor/craftcms/cms/src/db/Migration.php(49): craft\migrations\m220213_015220_matrixblocks_owners_table->safeUp()
 /home/varaxose/www/dev.gastrosocial.ch/varaxose.myhostpoint.ch/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
 /home/varaxose/www/dev.gastrosocial.ch/varaxose.myhostpoint.ch/vendor/craftcms/cms/src/db/MigrationManager.php(149): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m220213_015220_matrixblocks_owners_table))
 /home/varaxose/www/dev.gastrosocial.ch/varaxose.myhostpoint.ch/vendor/craftcms/cms/src/services/Updates.php(245): craft\db\MigrationManager->up()
 /home/varaxose/www/dev.gastrosocial.ch/varaxose.myhostpoint.ch/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(493): craft\services\Updates->runMigrations(Array)
 /home/varaxose/www/dev.gastrosocial.ch/varaxose.myhostpoint.ch/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
 [internal function]: craft\controllers\UpdaterController->actionMigrate()
 /home/varaxose/www/dev.gastrosocial.ch/varaxose.myhostpoint.ch/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
 /home/varaxose/www/dev.gastrosocial.ch/varaxose.myhostpoint.ch/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
 /home/varaxose/www/dev.gastrosocial.ch/varaxose.myhostpoint.ch/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('migrate', Array)

/home/varaxose/www/dev.gastrosocial.ch/varaxose.myhostpoint.ch/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('updater/migrate', Array)
 /home/varaxose/www/dev.gastrosocial.ch/varaxose.myhostpoint.ch/vendor/craftcms/cms/src/web/Application.php(712): craft\web\Application->runAction('updater/migrate')
 /home/varaxose/www/dev.gastrosocial.ch/varaxose.myhostpoint.ch/vendor/craftcms/cms/src/web/Application.php(238): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
 /home/varaxose/www/dev.gastrosocial.ch/varaxose.myhostpoint.ch/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
 /home/varaxose/www/dev.gastrosocial.ch/varaxose.myhostpoint.ch/web/index.php(22): yii\base\Application->run()
 {main}

### Steps to reproduce

1. After run php craft migrate/all

### Craft CMS version

4.0.0

### PHP version

8.1

### Database type and version

mysql

### Installed plugins and versions

- Expanded Singles
- Freeform
- Neo
- Redactor
- Redirect Manager
- SEOmatic
- String Urldecode
- Two-Factor Authentication
- Typogrify

**Comment by i-just** [comment]
Hi, thanks for reaching out. I’m having trouble replicating this on a fresh Craft installation (with some matrix fields and content added). Would you please be able to send your `composer.json`, `composer.lock` and database backup of your Craft 3 version to support@craftcms.com so that I can dig deeper?

**Comment by FabioIaderosa** [comment]
done, thanks

**Comment by i-just** [comment]
For anyone coming across this, the issue was down to missing foreign key. Installing the [Fix FK plugin](https://plugins.craftcms.com/fix-fks) and flushing orphaned blocks with those queries solved the problem.

```
DELETE FROM matrixblocks WHERE id NOT in (SELECT id FROM elements);
DELETE FROM matrixblocks WHERE ownerId NOT in (SELECT id FROM elements);
```
