### ISSUE TITLE
[4.x]: Symfony\Component\Mailer issue: Argument #5 ($port) must be of type ?int

### ISSUE THREAD

**Issue by ArnoMoqo** [craftcms/cms#12435]
### Description
We use SMTP to send emails, this used to work as aspected. When updating anything with the `./craft update` or `composer` command we run into a issue where we get the following error:

```
Symfony\Component\Mailer\Transport\Dsn::__construct(): Argument #5 ($port) must be of type ?int, string given, called in /data/sites/web/**domain**/apps/staging/releases/17/vendor/yiisoft/yii2-symfonymailer/src/Mailer.php on line 122
```

Reverting to the old composer.json does not resolve the issue. example: mailer works as aspected, we update anything with composer -> mailer stops working -> reverting composer.json & composer.lock -> issue still appears.

### Steps to reproduce

1. Send test email with Craft -> works as aspected
2. Run any update with composer
3. Run test email again -> get error

### Expected behavior

When updating Craft CMS the mailer should just keep working

### Actual behavior

The mailer does not work anymore

### Craft CMS version

Craft CMS 4.3.3 - Pro

### PHP version

8.1.11

### Operating system and version

Linux 5.15.68-0-virt

### Database type and version

MySQL 10.4.26

### Image driver and version

Imagick 3.6.0 (ImageMagick 6.9.11-60)

**Comment by i-just** [comment]
Hi, thanks for reaching out. It sounds like your `port` setting is being changed to something interpreted as a `string` and not `int`.  I can replicate this issue if I manually change my `port` setting to something invalid (like “10 25” instead of 1025), but I can’t trigger this change to happen on the composer update. 

Are you defining the email port via an environment variable? Is the port value visibly changing after the update? Do you have any custom commands specified in your `composer.json` file?

**Comment by ArnoMoqo** [comment]
> 

hey @i-just, we load in the values from our ENV like so:
(we also tried to just adding the values straight into the input fields)

<img width="1031" alt="Screenshot 2022-12-09 at 11 40 32" src="https://user-images.githubusercontent.com/117268595/206684092-362a4f76-6790-4354-a5c4-e9218fd93251.png">

Than in our .env we have:

`SITE_NAME=siteName
FROM_NAME=siteName
FROM_EMAIL=no-reply@domain.be
SMTP_HOST=host
SMTP_PORT=25
SMTP_USERNAME=email@domain.be
SMTP_PASSWORD=ourpass`


Inside composer.json we do not add anything special, I think:

`{
    "name": "ourname/clientname",
    "description": "New website for ***",
    "version": "1.0.0",
    "type": "website",
    "require": {
      "craftcms/cms": "4.3.3",
      "craftcms/feed-me": "^5.0",
      "craftcms/redactor": "3.0.2",
      "doublesecretagency/craft-googlemaps": "dev-v4-dev",
      "enupal/translate": "3.0.1",
      "marionnewlevant/picture": "3.0.0",
      "mmikkel/cp-field-inspect": "1.4.4",
      "mmikkel/incognito-field": "1.3.0",
      "nystudio107/craft-cookies": "4.0.0",
      "nystudio107/craft-emptycoalesce": "4.0.0",
      "nystudio107/craft-minify": "4.0.0-beta.2",
      "nystudio107/craft-retour": "4.1.8",
      "nystudio107/craft-seomatic": "4.0.16",
      "nystudio107/craft-vite": "4.0.3",
      "putyourlightson/craft-sprig": "^2.3",
      "sebastianlenz/linkfield": "2.1.5",
      "spicyweb/craft-neo": "3.5.10",
      "symfony/var-dumper": "^5.3",
      "verbb/expanded-singles": "^2.0",
      "verbb/formie": "2.0.19",
      "verbb/smith": "2.0.0",
      "verbb/super-table": "3.0.6",
      "vlucas/phpdotenv": "^5.4.0",
      "moqo/whise": "1.0"
    },
    "minimum-stability": "dev",
    "repositories": [
        {
            "type": "path",
            "url": "config/plugins/whise"
        }
    ],
    "require-dev": {
      "deployer/deployer": "^6.3",
      "yiisoft/yii2-shell": "^2.0.3"
    },
    "autoload": {
      "psr-4": {
        "modules\\": "modules/"
      }
    },
    "config": {
      "allow-plugins": {
        "craftcms/plugin-installer": true,
        "yiisoft/yii2-composer": true
      },
      "sort-packages": true,
      "optimize-autoloader": true,
      "platform": {
        "php": "8.0.2"
      }
    },
    "scripts": {
      "post-root-package-install": [
        "@php -r \"file_exists('.env') || copy('.env.example.dev', '.env');\""
      ]
    }
  }
  `

**Comment by i-just** [comment]
Thanks for the info. This is happening because you don’t have `"prefer-stable": true,` in your `composer.json` and one of the packages installed on `composer update` is triggering this error. It’s one of the dependencies of the packages you have in your `composer.json` that triggers this issue, so just locking them to a stable version without `"prefer-stable": true,` won’t fix this.

I hope this helps!
