### ISSUE TITLE
[3.x]: Unpredictable Javascript error when entry auto-saves causes regular save to fail

### ISSUE THREAD

**Issue by andersaloof** [craftcms/cms#12445]
### Description
Sometimes when editing fields inside a matrix, auto-save triggers a warning that in turn makes saving impossible.

The triggered error is the following:
![image](https://user-images.githubusercontent.com/1235821/207289477-8b04e8d7-fb85-43aa-8af5-3a3dff5e6fb1.png)

This error is triggered because `nestedNames` inside `_filterFieldInputName()` (https://github.com/craftcms/cms/blob/3.8/src/web/assets/cp/src/js/DraftEditor.js#L1289) returns null (I haven't been able to determine why this returns null).

The first time the error is triggered, it is caught by https://github.com/craftcms/cms/blob/3.8/src/web/assets/cp/src/js/DraftEditor.js#L890 and logged as a warning to the console, and the auto-save icon turns into an endless spinner.

When the first warning has occured, an error will be triggerd if the user then tries to save the entry.

### Steps to reproduce

I've not been able to reproduce this error in a consistant manner, but it has been triggered sometimes following these steps.

1. Create a new matrix field with 1 block containing 3 fields; one text field for title, one URL field for the url and one lightswitch.
2. Create new entry type containing the new matrix field.
3. Create a new entry of the new type and add some blocks to the new matrix and save the entry.
4. After saving the entry, reload the page, and open developer tools.
5. Edit one of the fields (either the title or the URL field), by either adding or removing content. Try to do this at various input sppeds as this has increased my chances of triggering the error.
6. When autosave triggers, check for the console warning "Couldn't save draft" and the endless spinner icon. If the warning was not triggered, continue editing other fields in the entry, or reload the page again to start over. Eventually the error will be triggered.
7. If warning has been triggered, try to save with CTRL + S and observe error in console.

### Expected behavior

Update of content should work as expected.

### Actual behavior

Javascript error is triggered causing auto-save and save to fail.

### Craft CMS version

3.7.61

### PHP version

7.4.3

### Operating system and version

Linux 5.10.102.1-microsoft-standard-WSL2

### Database type and version

MySQL 8.0.29

### Image driver and version

GD 7.4.30

### Installed plugins and versions

- Amazon S3	1.3.0
- Asset Rev	6.0.2
- Cookies	1.1.15
- CP Field Inspect	1.4.4
- Craft Youtube	1.0.23
- Dumper	2.0.0
- Expanded Singles	1.2.0
- Feed Me	4.5.3
- Imageshop	1.0.21
- Imgix	2.1.0
- Navigation	1.4.31
- Redactor	2.10.10
- Retour	3.2.4
- SEOMate	1.1.13
- Super Table	2.7.3
- Typed link field	1.0.25

**Comment by brandonkelly** [comment]
Thanks for reporting that! We just released Craft 3.7.62 and 4.3.5 with updates to that logic to be a bit more defensive. Now if `_filterFieldInputName()` comes across an input name it wasn’t expecting, a warning will be logged out to the console.

If you don’t mind, it would be great if you could attempt to reproduce on 3.7.62 with your browser console open, and let me know what the warning message is, so we can fix the bug at the source.

**Comment by andersaloof** [comment]
I'll give it a go and see if I can reproduce the error, but can't seem to find the 3.7.62 release, only see the 4.3.5, and this project isn't updated to Craft 4 (yet).

**Comment by andersaloof** [comment]
Testing on the 3.7.62 release I was not able to reproduce the endless spinner and subsequent error log, as the added throw/catch fixes this, instead I got the new console warnings:

I did notice that when the "Unexpected input name" warning appears, ANY content changes done, including the one that triggered that warning, will be lost when the document is saved. This wasn't an issue earlier, as saving would not work anymore when the error had occured, but now an editor would assume everything is OK, even when it's not.

![image](https://user-images.githubusercontent.com/1235821/207565121-9d29849f-ec4c-4154-bf51-43ddf24216ea.png)

A little breakdown of what steps I did the for the screenshot above:
1. Loaded the relevant entry
2. Did a content change to one field, this triggered the first network request for `save-draft` (see screenshots below)
3. Did 3 further content changes to various input fields, all of them triggering a network request (see screenshots below) and also a a warnings for "Unexpected input name" (screenshot above)
4. Saved the entry with `ctrl + s`
5. Verified that the 3 content changes that was done was NOT saved (screenshots below)

Updated entry content before saving
![image](https://user-images.githubusercontent.com/1235821/207563389-f9097c67-c386-4eec-a2db-86c76bbbe575.png)

Loaded entry content after save (only the first of the content changes was saved)
![image](https://user-images.githubusercontent.com/1235821/207565037-93743f53-06eb-43e0-81c4-d3662c0f4965.png)

Screenshot of all network requests, payload and response preview

Request #1
![image](https://user-images.githubusercontent.com/1235821/207564202-669c1796-01a6-4a5f-9db9-94c28595da3e.png)
![image](https://user-images.githubusercontent.com/1235821/207564264-78e9eba6-2e79-43f3-b33d-a62a583b6ac6.png)

Request #2
![image](https://user-images.githubusercontent.com/1235821/207564407-967ab55b-243f-44c4-ae51-779b787ee385.png)
![image](https://user-images.githubusercontent.com/1235821/207564440-b2159ff6-0eb2-45bb-9956-76a15a7d5f3e.png)

Request #3
![image](https://user-images.githubusercontent.com/1235821/207564518-25515de1-1104-4cc3-ac3b-8e554b7ad8df.png)
![image](https://user-images.githubusercontent.com/1235821/207564567-01be7a84-2911-4022-86aa-4da40f7c40da.png)

Request #4
![image](https://user-images.githubusercontent.com/1235821/207564709-21acb3e8-d67e-4854-ba24-165c770732bd.png)
![image](https://user-images.githubusercontent.com/1235821/207564732-cdfb82ec-9319-4b5b-afea-12bf921e97fc.png)

**Comment by brandonkelly** [comment]
We were able to track down the underlying culprit, and just released Craft 3.7.63.1 and 4.3.6.1 with a fix 🎉

**Comment by andersaloof** [comment]
Thanks for fixing this! 🥳

I can confirm that I'm not able to trigger this error and loose content anymore.
