### ISSUE TITLE
[4.x]: Duplicate cp image transforms

### ISSUE THREAD

**Issue by SHoogland** [craftcms/cms#12453]
### Description

![image](https://user-images.githubusercontent.com/2057831/207576249-705108d9-bbb7-48c8-9c46-6329d0ce4e82.png)

Somehow 2 of the same transform indexes have been created. and the queue job (generating pending image transforms) keeps iterating over the duplicate items. 

In the job finding the correct image transform and assuming its already there (which it is) but not cleaning up the duplicate.

Looking at the affected transformString its a control panel transform.

I don't really know how to reproduce this yet. but maybe some of you recognize this behavior?

### Craft CMS version

4.3.4

### PHP version

8.1.12

### Operating system and version

Linux 5.10.0-0.bpo.15-amd64

### Database type and version

MySQL 10.6.8

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-50)

### Installed plugins and versions

Amazon S3	2.0.1
Asset Rev	7.0.0
Blitz Recommendations	2.1.1
CP Field Inspect	1.4.4
Dumper	3.0.1
Elements Panel	2.0.0
Expanded Singles	2.0.0
Feed Me	5.0.4
Field Manager	3.0.4
Freeform	4.0.9
Mailgun	3.0.0
Redactor	3.0.2
Redactor Tweaks	3.0.0
Retour	4.1.9
SEOmatic	4.0.16
Servd Assets and Helpers	3.2.0
Super Table	3.0.7
Typed link field	2.1.5

**Comment by brianjhanson** [comment]
Any chance you're in a multi-server situation? In general, we [only recommend a single queue worker](https://github.com/craftcms/cms/issues/12047#issuecomment-1267811301) to avoid these kinds of issues.

**Comment by SHoogland** [comment]
No, and I don't think it has to do with the queue 🤔 I looked at that issue as well. But I think somehow two of the same transforms are created, and that never gets resolved. which puts the queue in a loop.

**Comment by brianjhanson** [comment]
Are there any clues in the `storage/log` files?

If not, can you send your `composer.json`, `composer.lock`, and a copy of your DB to support@craftcms.com?
