### ISSUE TITLE
[4.x]: Date field condition ':notempty:' throws error

### ISSUE THREAD

**Issue by nilsenpaul** [craftcms/cms#12457]
### Description

In a custom element source, with the condition of a date field set to 'empty' or 'not empty', an error gets thrown:

`craft\fields\conditions\DateFieldConditionRule::elementQueryParam(): Return value must be of type ?array, string returned`

### Steps to reproduce

1. Create a custom element source on an element with a date field
2. Set a condition 'not empty' or 'empty' on the date field
3. Try to load the element index. It doesn't work (for me)

`elementQueryParam` must return null or an array, but it gets its input from `BaseDateRangeConditionRule`, which returns a string if 'empty' or 'not empty' was requested.

### Craft CMS version

4.3.4

### PHP version

8.1

**Comment by i-just** [comment]
Thanks for reporting! I created a PR to fix this.

**Comment by brandonkelly** [comment]
This is fixed for the next release via #12461.

**Comment by brandonkelly** [comment]
Craft 4.3.6 is out with the fix for this.
