### ISSUE TITLE
[4.x]: Console migrations: pending migrations not clear

### ISSUE THREAD

**Issue by rauwebieten** [craftcms/cms#12454]
### Description

difference between craft migrate/up and migrate/all

### Steps to reproduce

When I run `php craft migrate` the system says: 

```
Checking for pending content migrations ...
No new migrations found. Your system is up-to-date.
```

When I run `php craft migrate/all`, there are 24 new migrations found.

```
Checking for pending migrations ...
Total 24 new Craft migrations to be applied:
    - m210121_145800_asset_indexing_changes
    - m210624_222934_drop_deprecated_tables
    - m210724_180756_rename_source_cols
    - m210809_124211_remove_superfluous_uids
    - m210817_014201_universal_users
    - m210904_132612_store_element_source_settings_in_project_config
    - m211115_135500_image_transformers
    - m211201_131000_filesystems
    - m220103_043103_tab_conditions
    - m220104_003433_asset_alt_text
    - m220123_213619_update_permissions
    - m220126_003432_addresses
    - m220209_095604_add_indexes
    - m220213_015220_matrixblocks_owners_table
    - m220214_000000_truncate_sessions
    - m220222_122159_full_names
    - m220223_180559_nullable_address_owner
    - m220225_165000_transform_filesystems
    - m220309_152006_rename_field_layout_elements
    - m220314_211928_field_layout_element_uids
    - m220316_123800_transform_fs_subpath
    - m220317_174250_release_all_jobs
    - m220330_150000_add_site_gql_schema_components
    - m220413_024536_site_enabled_string

Apply the above migrations? (yes|no) [no]:
```

This happens after a fresh install.
I'm running Craft 4.3.5 on PHP 8.1

It seems these migrations need not to be run, as I am installing the latest craftcms version.
(also, when I try to run them, the first one fails because of a index that cannot be removed)

When I look at the first 2 suggested migrations, it seems that the database operations in these migrations are not needed.
(assetindexdata table is already up-to-date, deprecated tables are not present in my db)

### Craft CMS version

Craft 4.3.5

### PHP version

8.1.13

### Operating system and version

Linux 5.15.79.1-microsoft-standard-WSL2

### Database type and version

MySQL 10.3.34

### Image driver and version

GD 8.1.13

**Comment by i-just** [comment]
Hi, thanks for reaching out.

`craft migrate` runs the default command: `craft migrate/up`. By default, it will try to apply content migrations (there aren’t any shipped with a fresh Craft installation).

`craft migrate/all` runs all pending Craft, plugin, and content migrations.

What are the contents of your `migrations` table? Do you see an Install migration there followed by 24 other migrations (so 25 in total)? Did you encounter any errors when installing Craft?

If this is a fresh installation, you can always back up your database, run `php craft db/drop-all-tables` and `php craft setup` to set things up again from scratch, and see if the issue reoccurs?

**Comment by rauwebieten** [comment]
Hi,
Thanks, we managed to fix it another way. Thanks for the info on migration types.
