### ISSUE TITLE
[4.x]: Indexed keywords of sentences/words with single quotes/apostrophes are not correct in some cases

### ISSUE THREAD

**Issue by ReedBe** [craftcms/cms#12467]
### Description

I have noticed that the search indexation is not working correctly when the search query includes words with single quotes or apostrophes, such as "l'orange" or "l'espace" in French. These words should be indexed as "orange" and "espace", but they are being indexed as "lorange" and "lespace" instead.

Upon investigation, I believe the issue may be related to this line of code: https://github.com/craftcms/cms/blob/develop/src/helpers/Search.php#L87.

An easy fix would be to give the the possibility to define a custom $asciiPunctuation variable to allow for better handling of these types of characters in search queries. This would greatly improve the usability of the search feature for users who speak languages that make use of single quotes or apostrophes.

### Steps to reproduce

1. Create an entry with this sentence `Bienvenue de l'espace`

### Expected behavior

Keywords in the database should be `bienvenue dans espace`

### Actual behavior

Keywords in the database are `bienvenue dans lespace`

### Craft CMS version

4.x

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting! This has been fixed for the next Craft 3 and 4 releases via 5524417aaaa570f04719cb8632b64f4e41d1a661.

**Comment by brandonkelly** [comment]
Craft 3.7.63 and 4.3.6 are out with that fix.
