### ISSUE TITLE
[4.x]: Feed Widget is blank after clearing caches

### ISSUE THREAD

**Issue by tommysvr** [craftcms/cms#12460]
### Description
The Feed Widget is blank after clearing caches.
There are no errors in the browser console.

### Steps to reproduce

1. Add a Feed Widget to the dashboard (https://craftcms.com/blog.rss)
2. Feed items should show
3. Clear caches from Utilities
4. Head back to the dashboard; the feed should be blank
5. Refresh the page, and items will show again

### Expected behavior
The feed will still show items without needing to be refreshed.

https://user-images.githubusercontent.com/867566/207812489-9cb0255c-9144-4f57-a7d8-4ea811cfc3aa.mp4

### Craft CMS version

4.3.5

### PHP version

8.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Fixed for the next release via #12463.

**Comment by brandonkelly** [comment]
Craft 4.3.6 is out with that fix.
