### ISSUE TITLE
[4.x]:  Control Panel JS not loading on some structure section entry pages

### ISSUE THREAD

**Issue by robinbeatty** [craftcms/cms#12473]
In the CP, for several sections (all of which are structures), the cp js fails to load beyond installHook.js, so edit page functionality is inoperable.

Spent several days trying to track down why this would be, have cleared all caches, resaved all entries, repaired section structures, reinstall craft, everything I can think of. Can't see what the offending entry types have in common in terms of fields or section settings, that other sections which do load don't have.

If I create a new entry within any of these sections, even then the js doesn't load.

There are no errors in the console.
No unexpected behaviours on the frontend.

The db has been migrated up from circa Craft 2.5 but latest upgrade to v4.x has resulted in this problem. As I've only just noticed it (having been building on 4.x locally for last few weeks) I can't be sure the upgrade caused the problem, but it may have done. 

I have also tried the same DB on a remote staging env (on a clean install of craft) and same problem there too.

Wondering if anyone can help?

### Craft CMS version

4.3.5

### PHP version

8.1.11

### Operating system and version

Linux 5.15.49-linuxkit

### Database type and version

MariaDB 10.4

### Image driver and version

Imagick 3.6.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-    "clubstudioltd/craft-asset-rev": "^7.0",
-    "craftcms/aws-s3": "^2.0",
-     "craftcms/cms": "4.3.5",
-     "craftcms/mailgun": "^3.0.0",
-     "craftcms/redactor": "^3.0.2",
-     "enupal/stripe": "^5.0",
-     "jamesedmonston/graphql-authentication": "^2.1",
-     "kinoli/groupie": "dev-master#e7abdf81a185fa614b9d6385dc587fd994f111f3 as 2.0.0",
-     "mmikkel/retcon": "^2.5",
-     "nystudio107/craft-cookies": "^4.0",
-     "nystudio107/craft-seomatic": "4.0.16",
-     "nystudio107/craft-vite": "^4.0",
-     "ostark/craft-async-queue": "^3.1",
-     "putyourlightson/craft-campaign": "dev-develop as 2.3.1",
-     "spicyweb/craft-embedded-assets": "^3.0",
-     "spicyweb/craft-quick-field": "^2.0",
-     "topshelfcraft/wordsmith": "4.2.0",
-     "verbb/comments": "^2.0",
-     "verbb/field-manager": "^3.0",
-     "verbb/image-resizer": "^3.0",
-     "verbb/super-table": "3.0.7",
-     "vlucas/phpdotenv": "^3.4.0"

**Comment by brandonkelly** [comment]
Where is `installHook.js` coming from? Craft doesn’t have a file called that.

**Comment by robinbeatty** [comment]
Solved. It was being caused by authors pasting a <script> tag into a plain text field on the affected entries. Some external widget that then injects a bunch of other scripts which were playing havoc with the craft scripts. I hadn't considered that a script tag in a text field this would get evaluated on the frontend. Is this the expected behaviour?

**Comment by brianjhanson** [comment]
Glad you got it sorted! I'm going to close this for now as the original issue is resolved.

`script` tags in plain text fields shouldn't be executing within the CP and I'm not able to replicate that behavior myself. Is there anything else (plugins, custom code, etc.) about your setup that might be causing this?

**Comment by brandonkelly** [comment]
There must be somewhere in your templates where you’re outputting the plain text field using the `|raw` filter – which would prevent `<script>` and other HTML tags from getting escaped, as they do by default.

If there’s a reason for using `|raw`. you could pass it through `|purify` first, to cleanse the field value via HTML Purifier.

Ideally you would do that within a `{% cache %}` tag, so HTML Purifier isn’t getting run on each request:

```twig
{% cache %}
  {{ entry.myPlainTextField|purify|raw }}
{% endcache %}
```

**Comment by robinbeatty** [comment]
In the templates yes, but this was getting evaluated in the cp, which seemed odd. Does the input value get rendered at any point?

**Comment by brandonkelly** [comment]
In general they shouldn’t. If you send a database backup over to support@craftcms.com and point out where you were seeing this happen, we can look into it from there.
