### ISSUE TITLE
[4.x]: Assets table column view is broken in subfolders

### ISSUE THREAD

**Issue by jammid** [craftcms/cms#12477]
### Description
When I try to add/remove table columns in an asset subfolder view the following happens.
Every column gets unchecked and the columns gets added/removed.
If I then select another column it becomes the only column displayed.
Pressing 'Use defaults' restores the default view but no columns get checked.

### Steps to reproduce

1. Create an asset subfolder
2. Add/remove table column in the view dropdown
3. Repeat step 2

### Expected behavior
The table columns get added/removed and checked/unchecked correctly.

### Actual behavior
See description.

### Craft CMS version

Craft Pro 4.3.5

### PHP version

8.1.9

### Operating system and version

Linux 4.19.0-22-cloud-amd64

### Database type and version

MySQL 10.4.25

### Image driver and version

GD 8.1.9

### Installed plugins and versions

- Amazon S3 - 2.0.1
- Control Panel CSS - 2.6.0
- Expanded Singles - 2.0.0
- Feed Me - 5.0.4
- Field Manager - 3.0.4
- Redactor - 3.0.2

**Comment by brandonkelly** [comment]
Thanks for reporting that! It’s fixed now for the next release.

**Comment by brandonkelly** [comment]
Craft 4.3.6 is out with this fix.
