### ISSUE TITLE
[3.x]: Craft CMS 3.7.62 is marked as released but isn't picked up in composer

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/cms#12472]
### Description

The latest Craft CMS 3 version according to the CHANGELOG is 3.7.62, but this release is not picked up by composer with the appropriate requirements. 

If I explicitly set the version to 3.7.62, it is pulled in as:

```
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading craftcms/cms (3.7.61 => v3.x-dev a705dda)
```

This is likely because minimum stability is set as "dev".

If I set it to something like `^3.7.26` (minimum requirement for our project), it doesn't see it and continues with 3.7.61 as no update.

Is it in fact released?

### Craft CMS version

3.7.61

### PHP version

8.0

**Comment by jamesmacwhite** [comment]
The 3.7.62 release is also not showing on Packagist: https://packagist.org/packages/craftcms/cms

**Comment by brandonkelly** [comment]
Doh! Thanks for pointing that out. Fixed now.

**Comment by jamesmacwhite** [comment]
Thanks, I can confirm composer now pulls in 3.7.62
