### ISSUE TITLE
[4.x]: Retrying a queue job pushes it to the proxy queue, but retry all does not

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#12471]
### Description

Queue::retry pushes a job to the proxy queue but Queue::retryAll does not

### Expected behavior

Queue::retryAll should push all jobs to the proxy queue

### Actual behavior

It does nothing

### Craft CMS version

4.3.5

### PHP version

8.1

### Installed plugins and versions

-

**Comment by boboldehampsink** [comment]
It would be nice to have these actions fire events (such as Queue::EVENT_AFTER_PUSH) so we can do custom things as well

**Comment by brandonkelly** [comment]
Added support for retrying all proxy queue jobs for the next release. Can you post whatever events you‘re hoping for in a discussion?

**Comment by brandonkelly** [comment]
Craft 4.3.6 is out with the retry-all fix.
