### ISSUE TITLE
[4.x]:  Button labels inconsistent between slideout editor and regular editor

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#12487]
### Description

Editing via the slideout editor becomes more popular, using `Craft.createElementEditor` in modules/plugins.

There is some confusion about the button labels and what happens when pressing them. Because labels are different from the regular edit pages.

Editing a
* provisional draft:  `Save` <-> `Save`  (ok)
* new unpublished entry: `Save`<-> `Create entry` (unclear what happens. The entry is published/created, while the user just expected to save the draft.)
* regular draft: `Save` <-> `Apply draft` + `Save draft` (unclear what happens. Here the draft is saved)

### Steps to reproduce

1. Open entries in slideout editor and in regular edit pages

### Expected behavior

Button labels and triggered actions are consistent between both editors, and between unpublished entries/regular drafts.

### Actual behavior

They are not.

/Klara

### Craft CMS version

4.3.5

### PHP version

8.0.26

### Operating system and version

Linux 5.15.79.1-microsoft-standard-WSL2

### Database type and version

MySQL 10.3.37

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 4.3.6 is out with a fix, via #12502.
