### ISSUE TITLE
[3.x]: Copy pasting urls with unicode characters

### ISSUE THREAD

**Issue by ryssbowh** [craftcms/cms#12480]
### Description

We're making a website in chinese, with chinese characters in urls.

Everything working great until the client tries to copy paste a url that has chinese characters in it, when pasted it turns into something like this : https://site.com/blog/%E5%8A%A0%E6%8B%BF%E5%A4%A7%E5%8D%87%E5%AD%B8

It's still working though but it doesn't look good. to be fair a chinese person copy pasting a url would expect the characters to come as unicode.

I'm not sure this comes from Craft but I've tried copy pasting from other websites and it doesn't do this.

Any idea why that would be and if there's a way around ?

### Steps to reproduce

1. Add unicode characters in a slug
2. copy paste the url

### Craft CMS version

3.7.59

### PHP version

8.0

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Where exactly are you copying the URLs from?

**Comment by ryssbowh** [comment]
From the browser, tried Friefox and Chrome

**Comment by brandonkelly** [comment]
But where exactly are you copying the URL from? The world icons within the Entries index page, for example?

**Comment by ryssbowh** [comment]
Ha yeah sorry, from the browser url bar on the frontend

**Comment by brandonkelly** [comment]
Sorry, I’m not following. Are you saying that if you go to the entry’s page on the front end, the URL will look correct in the browser’s address bar, but then the unicode characters get encoded when you copy it?

**Comment by brandonkelly** [comment]
Maybe a screenshot would help explain?

**Comment by i-just** [comment]
It sounds like you’re experiencing this: http://xahlee.info/js/url_encoding_unicode.html, and this behaviour is coming from the browser (and differs between browsers). 
Here’s more info on the IRI: https://en.wikipedia.org/wiki/Internationalized_Resource_Identifier and https://www.w3.org/International/articles/idn-and-iri/

Craft has a setting that allows you to limit auto-generated slugs to ASCII (https://craftcms.com/docs/4.x/config/general.html#limitautoslugstoascii), but that won’t work with the Chinese characters, and it only works with auto-generated slugs, so there’s nothing to stop a user from amending the slug to contain non-ASCII characters.

**Comment by ryssbowh** [comment]
Yeah you're right. Got mislead by the client who said that doesn't happen on other websites which it does.
Thanks
