### ISSUE TITLE
Single asset edit form pages

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1249]
> Created by: Benjamin Kohl (benjamin.h.kohl@gmail.com) on 2016/10/06 16:52:43 +0000
> Votes at time of UserVoice import: 1

-----------------------------------

I'd like to take advantage of being able to add custom fields to Asset elements but many fields tend to look squished in the modal edit form for assets. This usually results in us making a channel where content administrators choose one asset then the channel entry type has all the custom field data. If there were a single asset edit page, we wouldn't need to make channels with entries for each asset.

It doesn't necessarily have to replace the modal edit form for assets because that is useful in many cases too.

**Comment by brandonkelly** [comment]
Edit Asset pages are now a thing in the Craft 3.4 Beta!

![An Edit Asset page](https://user-images.githubusercontent.com/47792/71027610-6e074000-20c0-11ea-91e7-a10f58b97ab5.png)

**Comment by mattstein** [comment]
Complete with a download button _and_ uploader reference! 😎

**Comment by brandonkelly** [comment]
There’s “Preview” and “Edit” buttons when you hover over the thumbnail, too :)
