### ISSUE TITLE
[4.x]: composeFromKey() don't get the forced localized version

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#12493]
### Description
In a multi-sites setup, emails sent using composeFromKey are sent using the first site locale (which is not the Primary site) instead of the forced one.
User's language are set from a custom field (`userLanguage`) which is passed using `$mail->language`.

File: custom module
```
<?php

Event::on(
    Elements::class,
    Elements::EVENT_AFTER_SAVE_ELEMENT,
    function (Event $event) {
        if ($event->element instanceof Entry) {
            $entry = $event->element;

            if (ElementHelper::isDraftOrRevision($entry)) return false;

            $language = $event->element->language;
            $users = User::find()->status('active')->userNotifications(true)->userLanguage($language);

            foreach ($users->all() as $user) {
                $mail = Craft::$app->getMailer()
                    ->composeFromKey('article_notification', [
                        'entry' => $entry,
                        'user' => $user
                    ])
                    ->setTo($user);
                $mail->language = $language;
                $mail->send();
            }
        }
    }
);

Event::on(SystemMessages::class, SystemMessages::EVENT_REGISTER_MESSAGES, function(RegisterEmailMessagesEvent $event) {
    $event->messages = array_merge($event->messages, [
        [
            'key' => 'article_notification',
            'heading' => Craft::t('app', 'article_notification_heading'),
            'subject' => Craft::t('app', 'article_notification_subject'),
            'body' => Craft::t('app', 'article_notification_body'),
        ]
    ]);
});

Event::on(
  Mailer::class,
  Mailer::EVENT_BEFORE_PREP,
  function (MailEvent $event) {
    if ($event->message instanceof Message && isset($event->message->variables['user']->userLanguage->value)) {
      $event->message->language = $event->message->variables['user']->userLanguage->value;
    }
  }
);
```

File: `translations/en/app.php`
```
<?php

return array (
  // English
  'article_notification_heading' => 'When a new article is published:',
  'article_notification_subject' => '[ENGLISH] An article has been published on {{ systemName }}',
  'article_notification_body' => "[ENGLISH] Hi {{user.friendlyName|e}},\n\n" .
        "A new article \"{{ entry.title }}\" has been published on \"{{ systemName }}\".\n\n" .
        "{{entry.url}}",
);
```

File: `translations/nl/app.php`
```
<?php

return array (
  // Module | Forum Admin Notification
  'article_notification_heading' => 'When a new article is published:',
  'article_notification_subject' => '[NEDERLANDS] An article has been published on {{ systemName }}',
  'article_notification_body' => "[NEDERLANDS] Hi {{user.friendlyName|e}},\n\n" .
        "A new article \"{{ entry.title }}\" has been published on \"{{ systemName }}\".\n\n" .
        "{{entry.url}}",
);
```

I can confirm that if I exit `$user->userLanguage->value` (so first gotten value), it outputs `nl`.

Whenever the email is sent, it's always: _[ENGLISH] An article has been published on Site Name_
The same happens for the content, which is always in _[ENGLISH] (...)_, but where `{{entry.url}}` is outputted in the correct localized version.

So why `{{entry.url}}` is correctly translated, but not the content? Am I missing something to pass the locale, or is it a bug?

When using `setHtmlBody()` instead of `composeFromKey()`, it gets the correct localized content from the translations files, but the variables are not processed (because it's read as a translation file).

### Craft CMS version

4.3.5

### PHP version

8.1.0

### Database type and version

MySQL 5.7.34

### Installed plugins and versions

-

**Comment by romainpoirier** [comment]
I've finally found out that the translations texts in `/admin/utilities/system-messages` were not saved correctly and were overriding the translations files 🙈 I can confirm that this is working fine, as expected.

**Comment by romainpoirier** [comment]
I've finally found out that the translations texts in `/admin/utilities/system-messages` were not saved correctly and were overriding the translations files 🙈 I can confirm that this is working fine, as expected.

**Comment by brandonkelly** [comment]
Glad you got it sorted!
