### ISSUE TITLE
[4.x]: Live preview doesn't maintain scrollX on refresh

### ISSUE THREAD

**Issue by realjoshharrison** [craftcms/cms#12504]
### Description

When using live preview on a page which can scroll horizontally, the page's `scrollX` is always 0 when live preview refreshes. `scrollY` is maintained as expected.

### Steps to reproduce

1. Set up horizontally scrolling template (minimal example code below) on an entry type which has any field on it (in order to trigger live preview refresh)
2. Edit the entry and enter live preview
3. Scroll to e.g. box 24 at the bottom right
4. Edit a field and observe how when live preview refreshes, `scrollY` is maintained at the bottom of the page, but `scrollX` has reset to 0.

### Expected behavior

scrollX is maintained as well as scrollY.

### Actual behavior

scrollX is ignored, scrollY is maintained. 

### Example template code:

```twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Craft Test</title>
    <style>
      html {
        overflow-x: auto;
        font: 20px/1.2 sans-serif;
      }
      .boxes {
        display: flex;
        flex-wrap: wrap;
        width: 4000px;
      }
      .box {
        width: 500px;
        height: 75vh;
        background: #eee;
        border: 5px solid #fff;
        padding: 20px;
        flex-shrink: 0;
        box-sizing: border-box;
      }
    </style>
</head>
<body>

  <div class="boxes">
    {% for i in 1..24 %}
      <div class="box">Box {{ i }}</div>
    {% endfor %}
  </div>

</body>
</html>
```

### Browser

Google Chrome 108.0.5359.124 (Official Build) (arm64) 
Reproducible with all extensions disabled
MacOS Ventura 13.0.1

### Craft CMS version

4.3.6

### PHP version

8.0.8

### Operating system and version

MAMP Pro, Darwin 22.1.0

### Database type and version

MySQL 5.7.34

### Image driver and version

ImageMagick 6.9.6-2

### Installed plugins and versions

- None

**Comment by brianjhanson** [comment]
👏 Thank you for the detailed reproduction steps! They were incredibly helpful. I've opened a PR to fix this up.

**Comment by brianjhanson** [comment]
You can get the fix early by changing your `craftcms/cms` requirement in `composer.json` to "dev-bugfix/cms-12504-reset-scroll-x as 4.3.6" and running `composer update`. 

I'd recommend getting that back to a standard constraint as soon as possible, but it should get you by until the fix is released.

**Comment by brandonkelly** [comment]
That fix is now pulled in for the next Craft 3 and 4 releases.

@realjoshharrison  If you were pulling in the PR branch, you can change your `craftcms/cms` requirement to `dev-develop as 4.3.6.1`.

**Comment by brandonkelly** [comment]
Craft 3.7.64 and 4.3.7 have been released with that fix.
