### ISSUE TITLE
[4.x]: Public Registration Default User Group gets set after User::EVENT_AFTER_SAVE

### ISSUE THREAD

**Issue by mijewe** [craftcms/cms#12514]
### Description
- In my project, 90% of new users should be in Group A, and 10% should be in Group B.
- I set the Default User Group (in admin/settings/users/settings) to Group A.
- I wrote a custom module to instead set some new users to Group B, by hooking onto the `User::EVENT_AFTER_SAVE` event and running `Craft::$app->users->assignUserToGroups()`
- However, this didn't work and all users were set to Group A.
- This is because Craft was assigning the User to the Default User Group _after_ the `EVENT_AFTER_SAVE` event.

(I solved the issue by not using the Default User Group, and instead having my module set both groups)

### Steps to reproduce

1. Create two groups
2. Set Group A as the Default User Group in admin/settings/users/settings
3. Create a module that assigns new users to Group B on EVENT_AFTER_SAVE
4. Create a new user via a public registration form
5. Note that the User is still assigned to Group A

### Expected behavior

The user should be assigned to Group B after a sign up, respecting the EVENT_AFTER_SAVE logic over setting the default user group

### Actual behavior

The user is assigned to the Default User Group

### Craft CMS version

Craft Pro 4.3.5

### PHP version

8.1.13

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out. This is an intentional behaviour at the moment, but we will discuss it internally in relation to another issue: #12283.

For what you’re describing, you could also explore using `craft\services\Users::EVENT_BEFORE_ASSIGN_USER_TO_DEFAULT_GROUP` or `craft\services\Users::EVENT_AFTER_ASSIGN_USER_TO_DEFAULT_GROUP` events.

**Comment by i-just** [comment]
Just a quick note to say that there's a PR open to tweak the public registration logic, but it won't affect what's described here. Using the 2 events I mentioned before is the way to go.

**Comment by markusgabriel** [comment]
Hi @mijewe, I am having similar issues. But I am not even able to attach a user to a single group via my custom module. I also disabled the default user group setting. If you have a second to look into this small module. Do you see any mistake on my side?

`<?php
namespace usergroup;

use yii\base\Event;
use craft\base\Element;
use craft\elements\User;
use craft\events\ModelEvent;
use Craft;

/**
 * Custom module class.
 */
class UserGroup extends \yii\base\Module
{
  public function init()
  {
    Craft::setAlias('@usergroup', __DIR__);
    if (Craft::$app->getRequest()->getIsConsoleRequest()) {
        $this->controllerNamespace = 'usergroup\\console\\controllers';
    } else {
        $this->controllerNamespace = 'usergroup\\controllers';
    }
    parent::init();

    Event::on(
      User::class,
      User::EVENT_AFTER_SAVE,
      function (ModelEvent $event) {
        $element = $event->sender;
        Craft::$app->users->assignUserToGroups($event->sender->id, [1]);
      }
    );
  }
}`

Thanks in advance for any help.

**Comment by masiorama** [comment]
@markusgabriel 1 is the id of your user group?

**Comment by markusgabriel** [comment]
> @markusgabriel 1 is the id of your user group?

yes

**Comment by markusgabriel** [comment]
@masiorama yes, it is.

**Comment by masiorama** [comment]
@markusgabriel sorry I have not access to my laptop right now.
Does this help you? https://craftcms.stackexchange.com/questions/39086/add-user-to-group-based-on-registration-form-field

**Comment by markusgabriel** [comment]
@masiorama that is definitely an interesting post on this issue. Thank you! I disabled the default group after reading this initial post here, but I only tested the saving process in the CP, which didn't add the saved user to the usergroup. But it works now in the frontend form! 

The linked stack post helps me to make this more defensive and add some conditionals.

Thanks for your help!
