### ISSUE TITLE
[4.x]: Filter "slug" is not available

### ISSUE THREAD

**Issue by MattWilcox** [craftcms/cms#12515]
### Description

According to [the docs](https://craftcms.com/docs/4.x/dev/filters.html) "The following filters are available to Twig templates in Craft", and "slug" is listed, seemingly as a [Twig built-in](https://twig.symfony.com/doc/3.x/filters/slug.html).

However, this does not work.

![slug-filter](https://user-images.githubusercontent.com/814039/211546683-b094df93-d51a-41a0-8f06-0c2068af5bfd.jpg)

I assume this is because Craft is not requiring the `twig/string-extra` package or enabling it `require twig/extra-bundle` (see the Note on the Twig reference page)

### Steps to reproduce

1. Attempt to use the slug filter

### Expected behaviour

The slug filter should be applied

### Craft CMS version

4

### PHP version

8.0

### Operating system and version

DDEV

**Comment by brandonkelly** [comment]
That was a documentation bug. While it’s worth pulling in Twig’s StringExtension (which provides the `|slug` field), their concept of a “slug” doesn’t quite match Craft’s, so I don’ think we should do it without finding a way to reconcile those differences.
