### ISSUE TITLE
[4.x]: ResaveController ignores --offset when displaying element count in CLI output

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#12526]
### Description

Total number of elements shown in CLI output does not change when using offset

Without `--offset`:

![image](https://user-images.githubusercontent.com/25124/211907237-d84e1d49-ff9b-4cb3-93e0-78657085f22f.png)

With `--offset`:

![image](https://user-images.githubusercontent.com/25124/211907421-630a1a66-6a74-45fb-a94e-bf2f47614af9.png)

### Steps to reproduce

1. Run `./craft resave/entries` to get the correct count of total entries being saved
2. Run `./craft resave/entries --offset=10`

### Expected behavior

The second run should show 10 less entries than the first

### Actual behavior

Total entries is not updated… however the number of entries saved is correct

### Notes

I think this might be an issue with Yii `count` method. 

### Craft CMS version

4.3.6.1

### PHP version

8.1

### Operating system and version

OSX

### Database type and version

Postgres

### Installed plugins and versions

-

**Comment by brianjhanson** [comment]
Looks like this is traced back to the same yii2 issue reported by a familiar face in [#6036](https://github.com/craftcms/cms/issues/6036). I've opened a PR to address it by switching `$query->count()` to `count($query->all())`.

**Comment by leevigraham** [comment]
@brianjhanson Ha… I thought it was familair.

**Comment by brandonkelly** [comment]
Fixed for the next Craft 3 and 4 releases via #12542.

**Comment by brandonkelly** [comment]
Craft 3.7.64 and 4.3.7 have been released with that fix.
