### ISSUE TITLE
[4.x]: Assets::getAllDescendantFolders returns the `$parentFolder` folder in result

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#12536]
### Description

`Assets.php` calls `$this->getAllDescendantFolders($folder)` on line 330 and passes in the `$folder`.

<img width="1471" alt="Screenshot 2023-01-15 at 9 32 45 pm" src="https://user-images.githubusercontent.com/25124/212535798-23879367-aa3e-4034-9c68-097b71518af9.png">

`getAllDescendantFolders($folder)` creates a query using the same `path` as the parentFolder

<img width="1471" alt="Screenshot 2023-01-15 at 9 35 27 pm" src="https://user-images.githubusercontent.com/25124/212535940-073d7b4a-7cee-416a-9ca1-0d6cc062a8b5.png">

As a result the parent is returned in the descendants:

<img width="1683" alt="Screenshot 2023-01-15 at 9 41 13 pm" src="https://user-images.githubusercontent.com/25124/212536169-fa31dea2-3674-4a9a-b1f3-5f143cd40a95.png">

### Expected behavior

`$parentFolder` should not be included in the returned results.

### Actual behavior

`$parentFolder` is included in the returned results.

### Craft CMS version

4.3.6.1

### PHP version

8.1

### Operating system and version

13.1 (22C65)

### Database type and version

MySQL

**Comment by leevigraham** [comment]
@brandonkelly If you're looking at this Folder `155401` has the same path (weird duplicate) which is why it's also returned in the results.

**Comment by brandonkelly** [comment]
This seems to be currently working as intended, as everything within Craft that calls the method is expecting the parent folder to be included in the results.

It’s obviously a bad method name though. To make amends. I’ve just given it a new `$withParent` argument for the next Craft 3 and 4 releases, which is `true` by default, but if you pass `false` it will omit the parent folder from the results.

**Comment by brandonkelly** [comment]
Craft 3.7.64 and 4.3.7 have been released with that change.
