### ISSUE TITLE
[4.x]: Default value of Dropdown fields are not saved when using "resave/entries" CLI option

### ISSUE THREAD

**Issue by mikesnoeren** [craftcms/cms#12548]
### Description
When using the "resave/entries" CLI option to resave entries in Craft CMS, entries that have a dropdown field with a default value set and have never been saved after the field was added do not have the default value saved to the database. This is likely due to the CLI not taking default values into account, unlike the web UI which automatically selects the default value because a form is used to save the entry.

It is possible that this issue may also occur for other fields where a default value is set, but this has not been confirmed as this behavior has only been observed with dropdown fields by me personally.

### Steps to reproduce

1. Create a new dropdown field in Craft CMS with a default value set.
2. Add the field to a section with existing entries.
3. Use the "resave/entries" CLI option to resave all entries.
4. Check the value of the new dropdown field for the entries within said section, they won't be filled with the defaults.
5. Navigate to an entry and click save without making changes, the default value will now be filled.

### Expected behavior
The new dropdown field should have the default value saved to the database.

### Actual behavior
The new dropdown field does not have the default value saved to the database.

### Craft CMS version

4.3.5

### PHP version

8.0.26

### Operating system and version

Linux 5.15.82-0-virt

### Database type and version

MySQL 5.7.38

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

The version of any installed plugins does not seem to be relevant to this issue, and due to the lack of an easy way to copy and paste this information from the CMS, it will not be included in this bug report

**Comment by brandonkelly** [comment]
Craft 4.5.0 is out with an improvement to Dropdown field behavior: now if a Dropdown field’s value is invalid, and the field contains an explicit Default option, the default option will be auto-selected, and the field will be marked as changed. (#13540)
