### ISSUE TITLE
[4.x]: Sorting Assets by "Date Updated" triggers "Date Uploaded" Sorting.

### ISSUE THREAD

**Issue by internetztube** [craftcms/cms#12543]
### Description
When trying to sort an Asset Overview Listing by "Date Updated," it has no effect and highlights "Date Uploaded". So it triggers the wrong column. 

### Steps to reproduce

1. Show "Date Uploaded" and "Date Updated" on Assets Overview Listing.
2. Try to sort by "Date Updated".

### Expected behavior
Being able to sort by "Date Updated".

### Craft CMS version

4.3.6.1 (Pro)

### PHP version

8.1.13

### Operating system and version

Linux 4.14.301-224.520.amzn2.x86_64

### Database type and version

PostgreSQL 10.21

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-50)

### Installed plugins and versions

- Amazon S3 2.0.1
- Control Panel CSS 2.6.0
- Control Panel JS 2.6.0
- CP Field Inspect 1.4.4
- Element Relations 2.0.2
- Feed Me 5.0.5
- Guide dev-3.x-craft-4
- Icon Picker 2.0.12
- ImageOptimize 4.0.3
- Linkit dev-master
- Navigation 2.0.16
- Neo 3.5.16
- Redactor 3.0.3
- SEOmatic 4.0.19
- Super Dynamic Fields 2.0.0
- Super Table 3.0.7
- Translations v3.2.0
- Typed link field 2.1.5
- Workflow 2.0.3

**Comment by i-just** [comment]
Hi, thanks for reaching out. I’m having trouble replicating this one. Sorting by “Date Updated” and “Date Uploaded” (and other columns) works as expected for me in v4.3.6.1 (and in some previous versions too). Would you please be able to disable all the plugins (except for Amazon S3, as I assume you’re using that in your filesystem) and see if you’re still experiencing this issue?

**Comment by brandonkelly** [comment]
Closing this due to inactivitiy. @internetztube feel free to reply if you have more info.
