### ISSUE TITLE
[4.x]: Cannot save User fields that don't match CMS conditional

### ISSUE THREAD

**Issue by mijewe** [craftcms/cms#12540]
### Description
- I have a tab of fields on a User that I only want to display to Admin accounts.
- I set this tab to only show to admins using the Current User Condition setting.
- Now when posting to `users/save-user`, the admin-only fields will not save, and are not returned in the User object.
- Maybe this is expected behaviour, but I would have thought the Current User Condition only affects how things are displayed in the CMS, and not affect whether or not the currentUser can write to the field.

### Steps to reproduce

1. create a plain text field, Text.
2. put Text in a new tab on the User fields, Tab
3. set the Current User Condition on Tab to be Admins only.
4. submit a form to `users/save-user`, trying to save a new value into Text.
5. notice that it won't update the field.

### Expected behavior
The field would be updated.

### Actual behavior
The field is not updated.

### Craft CMS version

Craft Pro 4.3.5

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out. 

User conditions are not only affecting how things are displayed but are also a functionality/security feature. This is why you are not able to save the field value and retrieve it when you post to `users/save-user` as non-admin. I hope this clears things up!
