### ISSUE TITLE
[4.x]: Craft Image Transforms WebP Support Problems

### ISSUE THREAD

**Issue by handplant** [craftcms/cms#12556]
### What happened?

I have the following scenario:

**Local Valet with PHP 8.1.11, GD 8.1.11**

- craft.app.images.supportsWebP() is true
- webp images are generated by the native Craft Image Transforms

**Live Linux with PHP 8.1.11, Imagick 3.7.0 (ImageMagick 6.9.7-4)**

- craft.app.images.supportsWebP() is false
- no webp images are generated

But on the same server is still running a Craft 3 installation with Imager. 

- craft.imager.serverSupportsWebp() is true
- webp images are generated by imager

```
convert -list delegate
webp =>  "dwebp' -pam '%i' -o '%o"
```

```
dwebp -h
Usage: dwebp in_file [options] [-o out_file]
Decodes the WebP image file to PNG format [Default]
```

What is going wrong here?

### Craft CMS version

4.3.6.1

### PHP version

8.1.11

### Operating system and version

Linux 4.15.0-197-generic

### Database type and version

MySQL 5.7.40

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.7-4)

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out. In your live environment, if you go to Control Panel > Utilities > PHP Info, do you see `webp` listed as a supported format under `ImageMagick supported formats`?

**Comment by handplant** [comment]
No, webp is not listed.

And I just see that the Craft 3 is running on the same server with GD 7.4.32. For whatever reason! :D

So I have to do what? Update ImageMagick?

**Comment by i-just** [comment]
If `webp` is listed on that server under Control Panel > Utilities > PHP Info > gd > WebP Support, you could switch to GD for this website too. 

If that’s not an option for you, then you might decide to update ImageMagick or see if you can enable webp support for it - if I remember correctly, not all versions come with webp support turned on by default.

Another option might be to install the `libwebp`/`libwebp-tools` package(s). You can find more about them, e.g. here: https://developers.google.com/speed/webp/docs/precompiled

The exact details of what you can do will depend on your circumstances, but hopefully, this will help you figure out the next steps.

**Comment by i-just** [comment]
I’m going to go ahead and close this now. If you run into any more problems, please feel free to get in touch again.
