### ISSUE TITLE
[3.x]: Can't connect to database when using CLI via MAMP in Windows 11 

### ISSUE THREAD

**Issue by ejaedesign** [craftcms/cms#12551]
### Description
I'm using CLI via PowerShell/Cmder on Windows 11, using MAMP. Although all access & privileges have been given to both "root" and "ODBC" (guest) users, I still can't connect to the database. 

Paths have been correctly added for both PHP & MySQL. 

### Steps to reproduce

1. Launch MAMP/MAMP PRO
2. Launch PowerShell/Cmder 
3. CD over to the project directory
4. Run commands php craft help/list and/or any other php craft commands

### Expected behavior
Connect to the database and run various tasks via CLI

### Actual behavior
Shell outputs "Craft can’t connect to the database. Check your connection settings." error. 
When running the php craft help/list command, it does properly outputs the list of commands after the error message.

### Craft CMS version

3.7.63.1

### PHP version

7.4.16

### Operating system and version

Windows 11

### Database type and version

MySQL 5.7.24

### Installed plugins and versions

-

**Comment by brianjhanson** [comment]
Thanks for reaching out! Are you able to connect to MySQL directly via the command line? Did you double check the port settings are correct? I know MAMP on Mac sets the default MySQL ports to non-standard ports to avoid conflicts.

**Comment by angrybrad** [comment]
@ejaedesign probably worth giving https://craftcms.com/knowledge-base/mamp-with-composer-and-mysql-on-the-command-line a once-over

**Comment by ejaedesign** [comment]
> Thanks for reaching out! Are you able to connect to MySQL directly via the command line? Did you double check the port settings are correct? I know MAMP on Mac sets the default MySQL ports to non-standard ports to avoid conflicts.

> @ejaedesign probably worth giving https://craftcms.com/knowledge-base/mamp-with-composer-and-mysql-on-the-command-line a once-over

Thanks for the quick replies. 

Yes, I can access MySQL through the command line. Also checked GRANT and ACCESS privileges for both the root and guest (shows as "ODBC") users. 

I can also verify that both the PHP and MYSQL paths are added to the Windows environments/PATH settings as shown:

![windows_env_paths](https://user-images.githubusercontent.com/132996/213529712-5e928cb4-72c9-4d69-a2eb-44f728f3949d.png)

**Comment by brianjhanson** [comment]
It definitely seems like you have everything configured correctly. How are you setting the username & password for MAMP? 

On a default Craft 3 install, using `.env` variables you should have something like the following. 

```
DB_DATABASE="db_name"
DB_USER="root"
DB_PASSWORD=""
```

Is this a new DB or did you import it from somewhere? The other thing that can trip things up is if you've imported a DB that has a prefix and haven't set the `CRAFT_DB_TABLE_PREFIX` environment variable correctly. 

If it's not either of those, are there any other details about this project you can share?

**Comment by ejaedesign** [comment]
@brianjhanson here are some more info:

- Using the default MAMP passwords of root/root
- Also tried creating another superuser without a password
- Craft's .env file does have the correct DB settings & the site runs fine
- I can run tasks via CP's Utilities (or Feed Me's) even though CLI isn't connecting to the database
- The same thing happens on a new, fresh install as well as an imported site
- The tables do not have a prefix (neither a fresh install nor the imported one)
- CLI behaves the same way on a project that's been worked on locally 

Some other info. As it could be that the right credentials aren't being used by CLI, I followed these steps:

1. Logged to MYSQL via $mysql command
2. Once in, viewed access via MySQL>SHOW GRANTS; command
3. Output shows the user "ODBC" (guessing this is what MAMP on Windows use as the default) has GRANT OPTION on all local databases

Is there a way to force the CLI to use a specific user/password? Instead of the "ODBC" user, I'd like to see if I can get it going with the "root" user. 

Thanks again!

**Comment by brianjhanson** [comment]
Thanks for the info! It sure sounds like the CLI and Craft are running against different MySQL instances with the web pointing to MAMP using root/root and the CLI pointing towards another MySQL with the user ODBC. 

Do you have any different luck if you're more specific and make sure you're running from MAMP's PHP?
```
C:\MAMP\bin\php\php7.4.16 ./craft
```

You can specify different connection info for the CLI by creating a `config/app.console.php` file and overriding the `db` component. 

```php
<?php
use craft\helpers\App;

return [
    'components' => [
        'db' => function() {
            $config = App::dbConfig();
            $config['username'] = 'username';
            $config['password'] = 'password';
            $config['dsn'] = 'mysql:host={HOST};dbname={DBNAME};port={PORT}';

            return Craft::createObject($config);
        }
    ]
];

```

**Comment by ejaedesign** [comment]
@brianjhanson Thanks, Brad!

I tried both and so far no go. First, tried the more specific path:

![windows_php_path_craft](https://user-images.githubusercontent.com/132996/213603666-3316d1eb-1352-458a-aa86-bd299b6dc08a.png)

I assume it's simply not finding the root folder of the project folder. 

Then I created a new app.console.php file in the config folder. It's still not recognizing the DB:

![app_helper_file](https://user-images.githubusercontent.com/132996/213603754-77b14fcf-41e4-465b-8741-d703f41049c4.png)

Just for comparison, here's my .env file's DB credential:

![env_db](https://user-images.githubusercontent.com/132996/213603955-0aa89fc0-0aa3-45e2-874c-711cf30fb4b8.png)

So puzzling but really appreciate helping me through this!

**Comment by brianjhanson** [comment]
The same error message with `DB_USER` and `DB_PASSWORD` blank makes sense to me. Craft is just letting you know it can't connect to the DB, it's not very specific about why. 

A bit of a shot in the dark, but have you tried `127.0.0.1` instead of `localhost` for `DB_SERVER`?

**Comment by ejaedesign** [comment]
Yup. Tried:

`DB_SERVER=127.0.0.1`
$config['dsn'] = 'mysql:host=127.0.0.1;dbname=tow_craft_local;port=3306';`

In the .env and app.console files. Is there a trace I can run?

**Comment by ejaedesign** [comment]
By the way, the need for CLI is to import about 15k entries from EE via JSON files. I can't get my local set up to import more than 50-100 entries at a time, despite going through a number of MAMP adjustments (PHP memory, execution time, etc.)

**Comment by angrybrad** [comment]
@ejaedesign if you run `SET` from your terminal, it'll dump out all of the env vars that the CLI sees. Do you see the MAMP paths you added in the GUI under the `Path` variable?

**Comment by ejaedesign** [comment]
@angrybrad I do. After running `SET` from the command line, I get the following in the `PATH` variables:

`OLD_PATH=C:\Program Files\cmder\vendor\git-for-windows\cmd;C:\Program Files\cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\Program Files\cmder\vendor\conemu-maximus5;C:\Program Files\cmder\vendor\conemu-maximus5\ConEmu;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\Oppa\AppData\Local\Microsoft\WindowsApps;C:\Program Files\dotnet\;C:\Program Files\PowerShell\7\;C:\Program Files\PuTTY\;C:\ProgramData\chocolatey\bin;C:\Program Files\OpenSSL\binC:\ProgramData\ComposerSetup\bin;C:\Program Files\Git\cmdC:\Program Files\Docker\Docker\resources\bin;C:\MAMP\bin\mysql\bin;C:\MAMP\bin\php\php7.4.16;C:\Users\Oppa\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Oppa\.dotnet\tools;C:\Users\Oppa\AppData\Roaming\Composer\vendor\bin;C:\Program Files\cmder\vendor\git-for-windows\mingw64\bin;C:\Program Files\cmder\vendor\git-for-windows\usr\bin;C:\Program Files\cmder\vendor\bin
OneDrive=C:\Users\Oppa\OneDrive
OneDriveConsumer=C:\Users\Oppa\OneDrive
OS=Windows_NT
Path=C:\Program Files\cmder\vendor\git-for-windows\cmd;C:\Program Files\cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\Program Files\cmder\vendor\conemu-maximus5;C:\Program Files\cmder\vendor\conemu-maximus5\ConEmu;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\Oppa\AppData\Local\Microsoft\WindowsApps;C:\Program Files\dotnet\;C:\Program Files\PowerShell\7\;C:\Program Files\PuTTY\;C:\ProgramData\chocolatey\bin;C:\Program Files\OpenSSL\binC:\ProgramData\ComposerSetup\bin;C:\Program Files\Git\cmdC:\Program Files\Docker\Docker\resources\bin;C:\MAMP\bin\mysql\bin;C:\MAMP\bin\php\php7.4.16;C:\Users\Oppa\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Oppa\.dotnet\tools;C:\Users\Oppa\AppData\Roaming\Composer\vendor\bin;C:\Program `

**Comment by angrybrad** [comment]
@ejaedesign hrm... and if you run `php -v`, you get version 7.4.16 back?

I'll install MAMP on a Windows box today and see what I can find.

**Comment by ejaedesign** [comment]
@angrybrad I do:

![mysql_php_versions](https://user-images.githubusercontent.com/132996/214177480-2238b619-819d-4c8c-b510-15e3123dbc1b.png)

Really appreciate staying with this issue. Running W11 + MAMP is certainly a much smaller number of dev environments than working on a Linux or a Mac!

**Comment by angrybrad** [comment]
@ejaedesign man... spent a good deal of time trying to make this work on the latest MAMP Pro without much luck.

Best I can tell, the underlying issue is that the php.ini file that the CLI version of PHP that MAMP uses doesn't load the same php.ini file that the web version of PHP uses.

![web](https://user-images.githubusercontent.com/61869/214210233-08c81108-2817-4ff0-86f0-7eaa5c16bf50.jpg)
![cli](https://user-images.githubusercontent.com/61869/214210240-a7aefecf-53d5-46de-b2f9-864d9cd4df1f.jpg)

MAMP's documentation on the topic is non-existent and didn't have any luck with Google searches.

**Comment by ejaedesign** [comment]
@angrybrad Boy, I'm sorry for taking up so much of your time on this. I think I have a few options. 

I'll definitely migrate over to DDEV on the Windows side first and get this project going there, as it's most urgent. 

Then, finally set up that new MacBook Pro for development that I've been putting off. It's obvious things run smoother on the other side and have more support/solutions there. 

Lastly, I'll email MAMP folks and see what's going. It seems this is an issue they should be aware of, even if nothing comes of it. 

Much thanks for you & others for helping out!

**Comment by angrybrad** [comment]
@ejaedesign no worries at all - it's also weird that you have to manually create an ODBC user for the CLI to use to connect to the database (and that's not documented), but I wonder if that's because of the CLI php.ini weirdness.

Going to go ahead and close this one out, but reach out if you have questions about DDEV on macOS or Windows.
