### ISSUE TITLE
[4.x]: isTransparent always returning 1 in Craft 4.3.6

### ISSUE THREAD

**Issue by tomkiss** [craftcms/cms#12565]
### Description

Whilst attempting to use [isTransparent](https://docs.craftcms.com/api/v4/craft-base-image.html#public-properties) in a Craft module, I'm seeing true returned for all images.

### Steps to reproduce

In order to access the property in twig, I have a module set up something like this:

```php
public function getFunctions()
{
    return [
        new TwigFunction('isTransparent', [$this, 'getIsTransparent']), 
    ];
}

public function getIsTransparent(Asset $asset) 
{
    if (!isset($asset)) {
        return null;
    } else {
        $images = Craft::$app->getImages();
        $localCopy = ImageTransforms::getLocalImageSource($asset);
        $image = $images->loadImage($localCopy, true);
        return $image->getIsTransparent();
    }
}
```
The isTransparent property can then be accessed in twig via something like:
```twig
{% set myAsset = craft.assets.id(123).one() %}
{{isTransparent(myAsset)}}
```

### Expected behavior

I am expecting that transparent images such as pngs, gifs or webp that contain an alpha channel would return 1. Anything opaque, such as any jpg would return null.

### Actual behavior

It will **always** return 1. Regardless of whether or not it has an alpha channel, or if its transparent or not.

Having looked at this for a while now I'm wondering if this might be a bug. Loading imagemagick directly, within the module, and running its `getImageAlphaChannel()` method returns the expected result.

**NOTE: If I downgrade to Craft CMS 4.3.5 I do not see this issue.**

See attached module as example of my test: [imagehelpers-module.zip](https://github.com/craftcms/cms/files/10481698/imagehelpers-module.zip)

### Craft CMS version

4.3.6.1

### PHP version

8.1.12

### Operating system and version

MacOS with DDev

### Image driver and version

imagick 3.7.0 / gd 2.3.3

**Comment by brianjhanson** [comment]
Thanks for the report! We've tracked this down to an issue in the underlying Imagine library. It looks like in version 1.3 they [introduced a change](https://github.com/php-imagine/Imagine/pull/798) that will result in `isTransparent` returning `true` when `$palette->supportsAlpha()` is true (which happens [to be the case for the RGB palette](https://github.com/php-imagine/Imagine/blob/c10ea7f80e5b93473e2390515adc3057b85e26a2/src/Image/Palette/RGB.php#L74-L77) that most things will use). 

I've opened an [issue over there](https://github.com/php-imagine/Imagine/issues/842) but I'm also going to see if we have a good way to work around it. I just wanted to provide an update for future travelers (and before I forget the result of our digging)

**Comment by brianjhanson** [comment]
This one was quite the journey! Thanks to [the library authors](https://github.com/php-imagine/Imagine/issues/842#issuecomment-1402748019) I've opened a PR that replaces the `isTransparent` value with something more reliable for the next 3 and 4 releases.

**Comment by tomkiss** [comment]
Aha, nice sleuthing! 
Thanks for the quick response Brian, and the PR 🙌

**Comment by brandonkelly** [comment]
This is fixed for the next Craft 3 and 4 releases, via #12571.

**Comment by brandonkelly** [comment]
Craft 3.7.64 and 4.3.7 have been released with that fix.
