### ISSUE TITLE
[3.x]: setPasswordPath based on User Group

### ISSUE THREAD

**Issue by HannahDeWachter** [craftcms/cms#12561]
### Description
Our site contains 3 different sites, on different URLs (sites A, B and C). In site B there are frontend users, which sits in a seperate User Group. When a user is created in the backend and their permission is set to this User Group, they receive an activation email with a link to set their password. This links to the Primary Site (site A) and after setting a password this also redirects to the "activateAccountSuccessPath" on the Primary Site. However, this can be confusing for the user because this is a totally different website.

Therefore, in the General Config, we would like to set the "setPasswordPath" and/or "activateAccountSuccessPath" based on a user's Permissions/Group.

Maybe you have an other suggestion on how to solve this. We would love to hear your view on this.

### Steps to reproduce
1. Create a User
2. Set Permissions to a User Group
3. Receive activation mail with link to Primary Site
4. Set password
5. Redirects to Primary Site

### Expected behavior
It would be nice to set different "setPasswordPath" and/or "activateAccountSuccessPath" based on a user's Permissions/Group.

### Craft CMS version

3.6.17

### PHP version

7.4

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out. There are multiple ways to achieve this, and which one to choose will depend on your circumstances. Here are a few examples:

In terms of the activation link, you could, for example, edit the message template and include something like this:
```
{% if user.isInGroup('group2') %}
    <{{link|replace('<primarySiteBaseUrl>', '<groupSiteBaseUrl>')}}>
{% else %}
    <{{link}}>
{% endif %}
```
or you can have a look at the `EVENT_BEFORE_PREP` to manipulate the message
```
use craft\mail\Mailer;
use yii\base\Event;
use yii\mail\MailEvent;

Event::on(
    Mailer::class,
    Mailer::EVENT_BEFORE_PREP,
    function (MailEvent $event) {
        // ...
    }
);
```

In terms of `activateAccountSuccessPath`, you specify the path via `config/general.php`:
```
'activateAccountSuccessPath' => [
    'default' => '<primarySiteBaseUrl>/path-for-site1',
    'site2' => '<groupSiteBaseUrl>/path-for-site2,
]
```
For the `activateAccountSuccessPath` to work as you would like it to, the account activation needs to take place from the same site (e.g. if a user activates their account on site2, then `activateAccountSuccessPath` for site2 will be used.

I hope this helps. I will close this now, but please feel free to reply to this thread.

**Comment by HannahDeWachter** [comment]
Hi @i-just ,
Thank you for this information! We tried it and it works!
