### ISSUE TITLE
[4.x]: Entries CP Menu Order and CSS

### ISSUE THREAD

**Issue by mark-chief** [craftcms/cms#12573]
### Description
I've noticed the Entries menu has bigger spacing/ missing headings and incorrect order. 

I created a new channel and it appeared at the bottom of the list.

<img width="580" alt="Screenshot 2023-01-25 at 09 09 31" src="https://user-images.githubusercontent.com/18699249/214524163-7771d040-8f1b-415c-b211-009b2ded94e5.png">

### Craft CMS version

4.3.6.1

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out. If you click on the cog icon underneath the “Team Members” and then choose “Customise sources”, in there, you can change the order, add/edit/remove headings etc. I suspect there are empty headings above the “Singles” and “Team Members” sections, which are causing those large gaps. You can delete them if you don’t need them.

Now, if you never customised sources and you add a new section, it will be placed at the end of its default group (under structures for a new structure, under channels for a new channel etc.). However, once you’ve customised sources, we can no longer follow that default behaviour, so new sections are placed at the end of the list. An empty heading is then purposefully added above a new section if that section was added after sources were customised.

I hope this helps. I’m going to go ahead and close this, but if you have any further questions, you can still reply to this issue.

**Comment by mark-chief** [comment]
Ah.. thats a neat feature. I obviously overlooked that in the docs. Thanks for the heads up.
