### ISSUE TITLE
BETA subdomain has CORS problem [4.3.6.1]: 

### ISSUE THREAD

**Issue by vitalijalbu** [craftcms/cms#12574]
### Description
Hi, I have 2 sites that I will use as api backend:
1 - https://beta.resthotels.it/api/v1. (which cors are blocked)
2 - https://francescos85.sg-host.com/api/v1/
For frontend I'm using react + nextjs
I think subdomain beta is the problem, but online (codesandbox) it works well
Here is a demo: https://codesandbox.io/s/using-graphql-request-forked-ryg26x

### Steps to reproduce

1. Create a beta subdomain and try to fetch data from localhost, it will return cors-error-blocking, even if using proxy

### Expected behavior

Must work as a normal domain

### Actual behavior

beta subdomain

![Screenshot 2023-01-24 alle 11 10 11](https://user-images.githubusercontent.com/40239902/214538524-886a1e1e-e7e5-475e-841c-129998767b02.png)

normal domain

![Screenshot 2023-01-25 alle 11 25 55](https://user-images.githubusercontent.com/40239902/214539384-95de0d5c-ca86-4e70-a5dc-f9f1b3102dfc.png)

### Craft CMS version

4.3.6.1

### PHP version

8

### Database type and version

mysql

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
@vitalijalbu Take it you got this sorted?
