### ISSUE TITLE
[4.x]: # Fieldname keeps getting added and removed in project config files

### ISSUE THREAD

**Issue by CMeldgaard** [craftcms/cms#12576]
### What happened?

When the project config gets build or updated with new fields, we some times get a lot of changes because it keeps adding and removing #fieldName etc (see image). 
![image](https://user-images.githubusercontent.com/14794642/214566460-fca71bdf-0721-4251-82e9-8e38dbff079d.png)

### Craft CMS version

4.3.6

**Comment by i-just** [comment]
Hi, thanks for reaching out. I created a PR that improves how the names in comments are handled in Craft 4. 

Also, you can find more info on this issue here: https://github.com/craftcms/cms/issues/10512#issuecomment-1035056362.

**Comment by brandonkelly** [comment]
This is resolved for the next Craft 3 and 4 releases, via #12582 and #12581.

**Comment by brandonkelly** [comment]
Craft 3.7.64 and 4.3.7 have been released with that fix.
