### ISSUE TITLE
[4.x]: Eager Loading Matrix Field with no Rows in a Global causes 500 error on Error Template

### ISSUE THREAD

**Issue by mike-moreau** [craftcms/cms#12570]
### Description

We have a Global with a Matrix field named Code Blocks, handle "codeBlocks"

The Matrix field has no rows presently.

When attempting to eager load this matrix field in the base layout template, the error template breaks. The error template extends the base layout template by including an "entries" template as shown here:

```
{% set entry = craft.entries.slug(statusCode).section('error').one() %}

{% if entry %}
    {% include 'entries/_index' %}
{% else %}
    <p>
        {{ statusCode }}
    </p>
{% endif %}
```

### Steps to reproduce

1. Attempt to Eager load matrix field in global with the following code

```
{% do craft.app.elements.eagerLoadElements(
    className(code),
    [code],
    ['codeBlocks']
) %}
{% set codeBlocks = (code ?? null) and (code.codeBlocks ?? null) ? code.codeBlocks : [] %}
```

2. Visit a url that should throw a 404 error, such as example.com/___random___

### Expected behavior

Error template loads.

### Actual behavior

An error occurs and the error template is not used.

- In `dev` mode a 404 Template not found error is shown
- In `staging` the word Internal Server Error are shown

If the matrix is not eager loaded, the error template loads and renders as expected.

```{% set codeBlocks = (code ?? null) and (code.codeBlocks ?? null) ? code.codeBlocks.all() : [] %}```

### Craft CMS version

4.3.6.1

### PHP version

8.1

### Operating system and version

Mac OS

### Database type and version

Mysql 5.7

### Installed plugins and versions

Amazon S3	2.0.1
AsyncQueue	3.1.0
Blitz Recommendations	2.1.1
CMS Guide	4.0.0
Colour Swatches	4.2.1
Copy	2.2.0
Embedded Assets	3.1.1
Formie	2.0.20
Icon Picker	2.0.12
Neo	3.5.16
Redactor	3.0.3
Redirects	4.1.9
SendGrid	2.0.1
SEO	4.0.19
Smith	2.0.0
Typed link field	2.1.5

**Comment by brianjhanson** [comment]
Thanks for reaching out! 

Do you have a route set up (either in `routes.php` or via the CP) to make sure the `/random` request will get resolved to the base template? Without that, Craft will assume you're trying to render `templates/random.twig` and throw a 404 when it's not found. [Here are the docs on routing in case that's helpful](https://craftcms.com/docs/4.x/routing.html). 

I do note that you said in `staging` an Internal Server Error is thrown, do you have the actual error thrown handy? Or can you provide the stack trace for that error from the `storage/logs` file?

**Comment by mike-moreau** [comment]
Thanks for the reply @brianjhanson,

We dot not have a route to resolve `/random` so a 404 is expected. In fact, a 404 is exactly what I would like to occur, as I'm working on styling the custom error page template.

<details>
<summary>Trying to reach error template by visiting `/random` in dev mode</summary>
<img width="1299" alt="Screen Shot 2023-01-25 at 8 33 28 PM" src="https://user-images.githubusercontent.com/92817780/214745630-ae6267b3-27c6-442d-b407-56fa954f7ac5.png">
</details>

<details>
<summary>PHP error from logs visiting `/random` in staging mode</summary>
<code>
[25-Jan-2023 20:34:01 America/Chicago] An Error occurred while handling another error:
TypeError: get_class(): Argument #1 ($object) must be of type object, int given in /Users/mike/Sites/mostlyserious/iepworldwide/storage/runtime/compiled_templates/2d/2dc1ef7db8faf9a8f8e7288da5406cea.php:49
Stack trace:
#0 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/twig/twig/src/Template.php(394): __TwigTemplate_e5ef0e2258f8ebe5d384151c59fc87a1->doDisplay(Array, Array)
#1 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#2 /Users/mike/Sites/mostlyserious/iepworldwide/storage/runtime/compiled_templates/81/81e49def2f63d9dcc74af5ee96657702.php(45): Twig\Template->display(Array, Array)
#3 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/twig/twig/src/Template.php(394): __TwigTemplate_e37de3d6af8adea2b33e36361ec7ebfe->doDisplay(Array, Array)
#4 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#5 /Users/mike/Sites/mostlyserious/iepworldwide/storage/runtime/compiled_templates/b8/b8eddecca98f09711a05a0a447867ae1.php(50): Twig\Template->display(Array, Array)
#6 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/twig/twig/src/Template.php(394): __TwigTemplate_76a4848e07c1433d5252db0ae3e41869->doDisplay(Array, Array)
#7 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#8 /Users/mike/Sites/mostlyserious/iepworldwide/storage/runtime/compiled_templates/fd/fd006a86b9869ba80b19fb856848cc44.php(46): Twig\Template->display(Array)
#9 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/twig/twig/src/Template.php(394): __TwigTemplate_3d371a74813bd050df7766753eb43652->doDisplay(Array, Array)
#10 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#11 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#12 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#13 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#14 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/craftcms/cms/src/web/View.php(451): Twig\Environment->render('_error', Array)
#15 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/craftcms/cms/src/web/View.php(504): craft\web\View->renderTemplate('_error', Array)
#16 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(56): craft\web\View->renderPageTemplate('_error', Array, 'site')
#17 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/yiisoft/yii2/web/Response.php(1098): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#18 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/craftcms/cms/src/web/Response.php(286): yii\web\Response->prepare()
#19 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#20 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#21 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/craftcms/cms/src/web/ErrorHandler.php(192): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#22 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/yiisoft/yii2/base/ErrorHandler.php(152): craft\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#23 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/craftcms/cms/src/web/ErrorHandler.php(66): yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#24 [internal function]: craft\web\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#25 {main}
Previous exception:
yii\web\NotFoundHttpException: Template not found: random in /Users/mike/Sites/mostlyserious/iepworldwide/vendor/craftcms/cms/src/controllers/TemplatesController.php:97
Stack trace:
#0 [internal function]: craft\controllers\TemplatesController->actionRender('random', Array)
#1 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#3 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('render', Array)
#4 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('templates/rende...', Array)
#5 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#6 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#7 /Users/mike/Sites/mostlyserious/iepworldwide/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#8 /Users/mike/Sites/mostlyserious/iepworldwide/web/index.php(12): yii\base\Application->run()
#9 /Users/mike/.composer/vendor/laravel/valet/server.php(234): require('/Users/mike/Sit...')
#10 {main}
</code>
</details>

The relevant portion of the compiled twig template when eager loading:
````
        // line 4
        craft\helpers\Template::attribute($this->env, $this->source, craft\helpers\Template::attribute($this->env, $this->source, craft\helpers\Template::attribute($this->env, $this->source, ($context["craft"] ?? null), "app", []), "elements", []), "eagerLoadElements", [0 => get_class(        // line 5
($context["code"] ?? null)), 1 => [0 =>         // line 6
($context["code"] ?? null)], 2 => [0 => "codeBlocks"]], "method");
        // line 9
        $context["codeBlocks"] = ((((($context["code"]) ?? (null)) && (((craft\helpers\Template::attribute($this->env, $this->source, ($context["code"] ?? null), "codeBlocks", [], "any", true, true) &&  !(null === craft\helpers\Template::attribute($this->env, $this->source, ($context["code"] ?? null), "codeBlocks", [])))) ? (craft\helpers\Template::attribute($this->env, $this->source, ($context["code"] ?? null), "codeBlocks", [])) : (null)))) ? (craft\helpers\Template::attribute($this->env, $this->source, ($context["code"] ?? null), "codeBlocks", [])) : ([]));
        // line 11
````

Our `_error.twig` template will load correctly if I do not eager load the global code blocks matrix.

Happy to provide further details if it would be helpful.

**Comment by brianjhanson** [comment]
Ah, sorry! I missed the fact that you are using custom error templates initially. Since that's the case, it's expected that you will see the exception view with Dev mode on. [Custom templates are only used when dev mode is `false`](https://craftcms.com/docs/4.x/routing.html#error-templates). 

The other issue looks to be a conflict between your global with the handle `code` and the `code` context variable supplied to the error template. If you give your global a new handle, things should work as expected. I'll close this out, but I'll re-open it if that doesn't solve the issue.
