### ISSUE TITLE
[4.x]: `siteId` should be a reserved word

### ISSUE THREAD

**Issue by siebird** [craftcms/cms#12577]
### What happened?

I stumbled across this one as we were using `siteId` as a custom field in Burrow and was wondering why generated titles `{siteId}_{date}` was using `1` instead of the value in that field entry. 

### Craft CMS version

4.3.6.1

**Comment by brandonkelly** [comment]
We’ve added a [whole bunch of new reserved field handles](https://github.com/craftcms/cms/pull/12579/files) for the next Craft 3 and 4 releases, to avoid additional conflicts with `craft\base\Element` properties.

**Comment by brandonkelly** [comment]
Craft 3.7.64 and 4.3.7 have been released with that change.

**Comment by leevigraham** [comment]
@brandonkelly How does adding new reserved field names effect existing fields which already have a reserved field name?

**Comment by brandonkelly** [comment]
@leevigraham You’d get a validation error the next time you try to save the field.
