### ISSUE TITLE
[4.x]: Asset index after emptying folder via FTP

### ISSUE THREAD

**Issue by mark-chief** [craftcms/cms#12585]
### Description
Back in Craft 3, when you deleted an Asset volume folder on the server, you could go to utilities and update the Asset Index and it would update the volume in the CP. 

But in Craft 4, after you delete all assets from a volume via FTP and then go to Utlities > Asset Index > Update asset index, it says there's nothing to index and the volume still shows all the assets as broken images as they obviously dont exist.

### Craft CMS version

4.3.6.1

### PHP version

8.1

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch. This is an expected behaviour in Craft 4. It will only occur if there's absolutely nothing (no files and no folders) under the base path of the filesystem used by the volume you're indexing. That being said, we are going to make the message clearer in 4.4.

**Comment by mark-chief** [comment]
Thanks for checking. So even though all the empty subfolders dont exist on the server you still have to manually delete all of them  via the craft CP? Seems counterintuitive, unless I have missed something completely obvious?

**Comment by i-just** [comment]
Ok, I understand what you're after a bit better now. 

Yes, that's correct - at the moment, you'd have to delete them manually. Though it's not so much that the Asset Index doesn't pick it up; it's that it's not getting that far if there's absolutely nothing under your FS base path. 

You can "bypass" that if you have even one empty folder under your FS base path location.

We'll talk about this behaviour internally, and I'll update this issue once we've done that.

**Comment by mark-chief** [comment]
Thank you

**Comment by i-just** [comment]
We’ve discussed this, and I created a PR to change the current behaviour so that a list of missing files and folders is shown even if there’s nothing in the FS root folder.

**Comment by brandonkelly** [comment]
This is resolved for Craft 4.4 via #12604 🎉
