### ISSUE TITLE
Translatable dropdown field labels

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1258]
> Created on 2016/11/14 20:53:51 +0000
> Votes at time of UserVoice import: 1

-----------------------------------

Dropdown field labels shoudl be translatable from admin panel.

Right now i can just set different value for each language version of entry, but this what i need.

I need each dropdown option have different labels for each locale.

By the way i know that this s doable using translate filter from inside twig markup.

**Comment by fbnntt** [comment]
+1 for this

**Comment by brandonkelly** [comment]
Dropdown/Checkboxes/Multi-Select/Radio Button fields’ option labels are already translatable, for both Craft 2 and Craft 3.

**Comment by fbnntt** [comment]
Having a bit of trouble setting the label option for a german site — only ever seems to appearing in English?
