### ISSUE TITLE
[4.x]: Unable to login in backend without handling index.php

### ISSUE THREAD

**Issue by alexgit2k** [craftcms/cms#12588]
### Description

[omitScriptNameInUrls](https://craftcms.com/docs/4.x/config/general.html#omitscriptnameinurls) can be used for omitting `index.php` in URLs in the frontend which allows to completely ignore requests to index.php(/...). However in the backend the login-page /admin/login is sending the form-data to /index.php?p=admin/actions/users/login&v=... which leads to a 404 and the message "undefined".

The target-URL is generated by _craftData:
https://github.com/craftcms/cms/blob/77c4e9e3cf7a5d41341448ea47fa65fd6ee44c67/src/web/assets/cp/CpAsset.php#L383
which calls actionUrl without parameters, so therefore index.php is added:
https://github.com/craftcms/cms/blob/77c4e9e3cf7a5d41341448ea47fa65fd6ee44c67/src/helpers/UrlHelper.php#L377-L380

**Workaround**
Replacing in `src/web/assets/cp/CpAsset.php`, line 383:
`'actionUrl' => UrlHelper::actionUrl(),`
by
`'actionUrl' => UrlHelper::actionUrl('',null,null,false),`

### Steps to reproduce

1. Use nginx and ignore direct request to php-files
2. CRAFT_OMIT_SCRIPT_NAME_IN_URLS=1 (see https://craftcms.com/docs/4.x/config/general.html#omitscriptnameinurls)
3. Log in at /admin/login

### Expected behavior

Successful login

### Actual behavior

- HTTP-code 404 for the POST-request
- Error-Message "undefined"

### Craft CMS version

4.3

### Installed plugins and versions

-

**Comment by michtio** [comment]
@alexgit2k I think this is rather an issue with your nginx config file, as `omitScriptNameInUrls` is working as expected, and doesn't throw any errors while login in or using Craft forms for that matter ( tested on 4.3 ).

It could be useful to share your nginx config.

**Comment by alexgit2k** [comment]
@michtio At `/admin/login` the HTML-code says
`window.Craft = {..."actionUrl":"https:\/\/example.com\/index.php?p=admin\/actions\/",...}`.
The `index.php` is always shown here regardless if `omitScriptNameInUrls` / `CRAFT_OMIT_SCRIPT_NAME_IN_URLS` is set or not. How does this `actionURL` at the login-page look like on your side?

As far as I see `_createUrl` in [src/helpers/UrlHelper.php](https://github.com/craftcms/cms/blob/77c4e9e3cf7a5d41341448ea47fa65fd6ee44c67/src/helpers/UrlHelper.php) would respect `omitScriptNameInUrls` by default, but is overridden because `actionUrl` is called without the `showScriptName`-parameter (and path-parameters exist), so therefore `_createUrl` is called with `showScriptName` set to `true`.

I am using Symfony's nginx-configuration: https://symfony.com/doc/current/setup/web_server_configuration.html#nginx
Please note that because of the `internal`-directive in the index.php-location-block, a direct call to `index.php` matches only the last location-entry and therefore returns 404. That's why I am unable to login at the backend.

And of course `CRAFT_WEB_URL` does not contain the `index.php`.

**Comment by brandonkelly** [comment]
Why exactly is including `index.php` there a problem? Craft does intentionally include it for some form action URLs, which aren’t particularly user-facing, as a safeguard.

> [omitScriptNameInUrls](https://craftcms.com/docs/4.x/config/general.html#omitscriptnameinurls) can be used for omitting index.php in URLs in the frontend which allows to completely ignore requests to index.php(/...).

This isn’t actually true – the setting will only determine whether `index.php` should be included in more user-facing URLs; it doesn’t affect how Craft will handle requests that include `index.php`.

**Comment by alexgit2k** [comment]
> Why exactly is including `index.php` there a problem? Craft does intentionally include it for some form action URLs, which aren’t particularly user-facing, as a safeguard.

The problem is that direct calls to `index.php` do not get executed with Symfony's nginx-configuration and return a 404 instead. Why should using `index.php` instead of nice-URLs be a safeguard for forms?

> > [omitScriptNameInUrls](https://craftcms.com/docs/4.x/config/general.html#omitscriptnameinurls) can be used for omitting index.php in URLs in the frontend which allows to completely ignore requests to index.php(/...).
> 
> This isn’t actually true – the setting will only determine whether `index.php` should be included in more user-facing URLs; it doesn’t affect how Craft will handle requests that include `index.php`.

The documentation for [omitScriptNameInUrls](https://craftcms.com/docs/4.x/config/general.html#omitscriptnameinurls) let me assume that this is for all Craft-URLs, it does not say that there is a different handling between action URLs  and more user-facing URLs.

**Comment by michtio** [comment]
@alexgit2k I don't see the issue really why you would want to hide the `index.php` bit in URL's for forms and other.

For me again this doesn't seem like an issue neither a problem from Craft. Rather an issue with the Symfony nginx configuration ( which I'm wondering why do you stick on using that? Rather than just changing the nginx config specifically focused for Craft? )

Symfony !== Craft CMS/Yii

**Comment by alexgit2k** [comment]
@michtio The problem with allowing `index.php` is, that then the frontend is accessible under `domain/niceurl` AND `domain/index.php/niceurl`. This causes problems with e.g. Google and duplicate content. I want only nice urls everywhere.

Can you please point me to the Craft's nginx-config, I haven't found one at https://craftcms.com/docs/. Therefore I was using Symfony's nginx configuration, which I was using successfully for many years now.

**Comment by michtio** [comment]
You can find ( in my personal opinion ) the best nginx config here: https://github.com/nystudio107/nginx-craft 

In case of SEO I never had an issue with duplicate content because of the "index.php" being available as well. The crawler will not automatically start adding `index.php` if it has no idea it exists or not.

**Comment by alexgit2k** [comment]
Thanks for the config! As form-action URLs in the frontend also contain `index.php` crawlers may very easily get their attention to `index.php`.

**Comment by brandonkelly** [comment]
> Why should using index.php instead of nice-URLs be a safeguard for forms?

Some Apache setups aren’t capable of routing traffic to `index.php` without it being explicitly requested, and use a `.htaccess` redirect to forward traffic to it. However those internal redirects aren’t capable of passing POST data to it. So by including `index.php` in action URLs, Craft avoids that issue altogether (no need for the redirect if the URL is already pointing to `index.php`).

That said, you can force Craft to stop including `index.php` if you set your [`pathParam`](https://craftcms.com/docs/4.x/config/general.html#pathparam) config setting to `null` in `config/general.php`.

**Comment by alexgit2k** [comment]
`pathparam` sounds perfect and now I understood the `index.php`-handling. Thank you very much!

Maybe you can mention at the documentation of [omitScriptNameInUrls](https://craftcms.com/docs/4.x/config/general.html#omitscriptnameinurls) that it does not omit `index.php` in all generated URLs (because of the Apache-safeguard) and `pathparam` can be used additionally to achieve that. That would make it much more clearer.

**Comment by brandonkelly** [comment]
@alexgit2k Good call. Added a note which will get published the next time we tag a release. (ae1b3d774e064d5b320a5eaf140fafdf9854cd04)
