### ISSUE TITLE
[4.x]: Page trigger is reset on CP requests

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#12598]
### What happened?

The page trigger is reset on CP requests, meaning that plugins cannot check its actual value.

https://github.com/craftcms/cms/blob/9b483fafa5deaf1cd3df73a636ec73a908295204/src/web/Request.php#L307-L311

This leads to an inaccurate value when plugins fetch it, as reported in the Blitz issue at https://github.com/putyourlightson/craft-blitz/issues/469

```php
// Returns `p` instead of `?p=`
$pageTrigger = Craft::$app->getConfig()->getGeneral()->getPageTrigger();
```

Would it be possible to simply ensure that the page trigger doesn't have a trailing slash, as the code comment suggests? Alternatively, could the check for a page trigger only happen for site requests?

### Craft CMS version

4.3.6.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
I don’t want to move away from the control panel forcing the page trigger to be `p`, however we can do that without overriding the `pageTrigger` config setting. I’ve submitted a PR for Craft 3 which does that (#12614). Let me know if that will work for your needs @bencroker!

**Comment by bencroker** [comment]
That's perfect, thanks @brandonkelly!

**Comment by bencroker** [comment]
@brandonkelly I just noticed that this wasn't added to any of the the Craft 4 branches, did I miss it or is it pending review first?

**Comment by brandonkelly** [comment]
Just wanted to make sure it was going to work for you first. The change is now merged in for the next Craft 3 and 4 releases.

**Comment by bencroker** [comment]
Thanks!

**Comment by brandonkelly** [comment]
Craft 3.7.64 and 4.3.7 have been released with that change.
