### ISSUE TITLE
[3.x]: There was a problem backing up your database. Please check the Craft logs.

### ISSUE THREAD

**Issue by KarlBishop** [craftcms/cms#12609]
### What happened?

We've started seeing this error message flash up when trying to do Database Backups via the Control Panel:
"There was a problem backing up your database. Please check the Craft logs."

In the logs, I can't see a specific reason but these error messages have appeared:

```
apache_error   [02/Feb/2023:01:36:06 +0000] [client 122.58.46.142] AH01067: Failed to read FastCGI header
apache_error   [02/Feb/2023:01:36:06 +0000] [client 122.58.46.142] (104)Connection reset by peer: AH01075: Error dispatching request to :
apache_access  122.58.46.142 - - [02/Feb/2023:01:35:31 +0000] "GET /index.php HTTP/1.1" 503 1682 "https://www.mywebsite.com/admin/utilities/db-backup" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
```

Is this anything to do with Craft or should I just raise it with our hosting provider?

### Craft CMS version

Craft Pro 3.7.63.1

### PHP version

7.4.28

### Operating system and version

Linux 4.15.0-1146-aws

### Database type and version

MySQL 8.0.31

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-26)

### Installed plugins and versions

- Asset Usage	2.3.1
- Blitz	3.12.8
- Bulk Edit	2.0.6
- Cloner	1.2.2
- Control Panel Nav	3.0.17
- Cookiebot	1.0.9
- Copy	1.2.4
- Dashboard Begone	1.0.1
- Element API	2.8.6.1
- Embedded Assets	2.11.3
- Feed Me	4.5.4
- fortrabbit Object Storage Volume	2.1.0
- Freeform	3.13.22.1
- Image Resizer	2.2.0
- Minify	1.2.11
- Patrol	4.0.2
- Redactor	2.10.11
- Retcon	2.6.0
- Sentry Logger	1.3.1
- SEOmatic	3.4.48
- Sherlock	3.1.7
- Super Table	2.7.4

**Comment by brianjhanson** [comment]
Thanks for reaching out! Those look almost like server logs, are there any hints in the `storage/log` files?

I thought maybe you were running into #12557 but that should only effect 8.0.32.

**Comment by KarlBishop** [comment]
> Those look almost like server logs, are there any hints in the storage/log files?

Yes, we can't access log files in storage/logs because of our hosting.

We can see live output from all log sources over an ssh command like `ssh mywebsite@log.eu2.frbit.com tail` which is where I found those lines.

Besides that, we use the `Sentry Logger` plugin to capture Craft logs on sentry.io. But there wasn't anything logged there in response to this issue.

**Comment by KarlBishop** [comment]
The Sentry log may not be comprehensive though... because we're not using the [advanced configuration](https://github.com/diginov/craft-sentry-logger/blob/main/README.md#advanced-configuration).

But I'm not sure how to edit `app.php` to combine the sentry log target with the [custom log target advised by fortrabbit](https://help.fortrabbit.com/craft-tune#toc-logging).

E.g. this doesn't work:
```
<?php
use craft\helpers\App;
use diginov\sentrylogger\log\SentryTarget;

return [
    'id' => App::env('APP_ID') ?: 'CraftCMS',
    'modules' => [
        'my-module' => \modules\Module::class,
    ],
    'components' => [
        'log' => [
            'targets' => [
                function () {
                    return new class() extends \craft\log\FileTarget
                    {
                        public function init()
                        {
                            $this->setLevels(
                                YII_DEBUG === true
                                    ? ['trace', 'warning', 'error']
                                    : ['warning', 'error']
                            );
                        }

                        public function export()
                        {
                            $text = implode(PHP_EOL, array_map([$this, 'formatMessage'], $this->messages));
                            // revert to php defaults & log
                            ini_set('error_log', 'syslog');
                            error_log($text . PHP_EOL);
                        }
                    };
                },
                'sentry' => function() {
                    if (!class_exists(SentryTarget::class)) {
                        return null;
                    }

                    return Craft::createObject([
                        'class' => SentryTarget::class,
                        'enabled' => App::env('CRAFT_ENVIRONMENT') !== 'dev',
                        'anonymous' => false,
                        'dsn' => App::env('SENTRY_DSN'),
                        'release' => App::env('SENTRY_RELEASE'),
                        'environment' => App::env('SENTRY_ENVIRONMENT'),
                        'levels' => ['error', 'warning'],
                        'exceptCodes' => [403, 404],
                        'exceptPatterns' => [],
                    ]);
                },
            ]
        ]
    ],
];

**Comment by angrybrad** [comment]
@KarlBishop Looks like you're on Fortrabbit - you should be able to SSH into the instance and access Craft's logs in `storage/logs` https://help.fortrabbit.com/craft-tune#toc-logging

That should have a more helpful error message as to why it's failing. Pretty sure `ssh mywebsite@log.eu2.frbit.com tail` is just giving you the system logs.

**Comment by KarlBishop** [comment]
Thanks for coming back @angrybrad 

We can't access Craft logs in `storage/logs` because we're on the Fortrabbit Pro Stack which is an ephemeral multi-node environment. (Listing contents of `storage/logs` over SSH shows an empty folder - the "frontend nodes" where real-time logs are created are not accessible to us).

Instead we're using the custom log target Fortrabbit advises under "To access php_error logs on the Professional Stack..."
https://help.fortrabbit.com/craft-tune#toc-logging

^I thought that meant all the things that normally appear in `storage/logs` are included in `ssh mywebsite@log.eu2.frbit.com tail` but sounds like I could be wrong..?

**Comment by brianjhanson** [comment]
Can you reach out to Fortrabbit and see if they have any info on the error? The particular message you're getting comes from the front end, which means the real error is only surfaced in the logs. My guess is that the issue is environmental, though.

**Comment by KarlBishop** [comment]
Hi @brianjhanson thanks for coming back...

Ahh, it looks like it is simply our server config. We have PHP `max_execution_time` set to 30 seconds. This is per Fortrabbit's recommendation for PHP response time, so that PHP processes will never be blocked for too long.

So presumably our database became too large to download within 30 seconds. And the execution timeout prevents even the logs being written..?

**Comment by brianjhanson** [comment]
Yeah, that sounds pretty reasonable to me. Glad you got it sorted out! I'm going to close out this issue, but don't hesitate to reach out if you have any more questions.
