### ISSUE TITLE
[4.x]: Plugin Development, Element Type does not render getEditorHtml anymore

### ISSUE THREAD

**Issue by tonioseiler** [craftcms/cms#12605]
### Steps to reproduce

1. We created a new element type in a plugin, the detail page to edit shows up, but if I try to addfields via getEditorHtml, it seems like this method is not called anymore.

### Expected behavior

It should be possible to add fields like this.

### Actual behavior
only shows custom fields from fieldlayout

### Craft CMS version

4.3.5

### PHP version

8.1

### Operating system and version

OSX

### Database type and version

MYSQL

### Installed plugins and versions

-

**Comment by i-just** [comment]
In Craft 4.0.0, `craft\base\ElementInterface::getEditorHtml()` was removed. Element edit forms are now exclusively driven by their field layout.

The last code snippet in this section: https://craftcms.com/docs/4.x/extend/updating-plugins.html#field-inputs, shows how to utilise a field layout if you don’t want to make the field layout designer available or support custom fields.

I hope this helps!

**Comment by tonioseiler** [comment]
This helped a lot! Thank you.
