### ISSUE TITLE
[4.3.6.1]: Tab doesn't show,  when the tab name in chinese

### ISSUE THREAD

**Issue by ivesho** [craftcms/cms#12602]
### Description
Tab doesn't show,  when the tab name in chinese.
![image](https://user-images.githubusercontent.com/48641341/216006655-b9d095a0-ae9e-45af-b5d6-dbf3571153ca.png)
![image](https://user-images.githubusercontent.com/48641341/216006883-2e069eb0-8e43-4fef-b310-d8bf30e9cb00.png)

### Steps to reproduce

1.

### Craft CMS version

Craft Pro 4.3.6.1

### PHP version

8.1.8

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting! This is fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.3.7 has been released with that fix.
