### ISSUE TITLE
[4.3.6.1]: Empty row/columns in searchindex table

### ISSUE THREAD

**Issue by philipboomy** [craftcms/cms#12619]
### What happened?

Not sure if this is a bug but I got more than 3 million rows in my searchindex and I got lots of empty rows/columns. I am wondering if this is on purpose? Normally not an issue but today I had to roll back after a failed migration and it took a long time to import the database mainly due to the search index.

See here for example https://share.getcloudapp.com/YEuD0JOe

### Craft CMS version

4.3.6.1

### PHP version

8.0

### Database type and version

PostgreSQL 12.13

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
It’s expected if your fields are marked as searchable, as empty values are still meaningful – it’s how we support searching for empty values via `-myFieldHandle:*` syntax.

**Comment by philipboomy** [comment]
I see. That makes sense. Just a shame as so many inactive carts blows up the search index with empty rows. I can't personally see why I would ever query for empty billing last name etc but perhaps others would. 

Thanks for quick reply. Appreciated.

**Comment by philipboomy** [comment]
Follow up question. I got some (lots) rows in the searchindex that is referencing an elementid that does not exist anymore in the "elements" table. They are all orders I think. I tried "php craft resave/orders" but that didn't clear the rows from searchindex.

**Comment by brandonkelly** [comment]
You can clear those up by running `craft gc`. That should run automatically roughly once per 1,000 requests, or you can ensure it runs on a regular schedule by setting up a cron job that runs `craft gc` once per day or so.

**Comment by philipboomy** [comment]
Thanks. I did run craft gc earlier but it was purging inactive carts after "deleting orphaned search indexes" so I ran it again. Got rid of of around 2million rows. Have a nice weekend.

**Comment by brandonkelly** [comment]
Nice! That sounds like it should make a dent on the DB size.
