### ISSUE TITLE
[4.3.7]: Inconsistent saving of fields inside Matrix Blocks

### ISSUE THREAD

**Issue by stevecomrie** [craftcms/cms#12623]
### Description

The best way I can describe this is something in 4.3.7 is preventing the first edit to a field inside a matrix block from saving -- unless you make an edit to a field outside of the matrix block field first (or you change the same field inside the matrix block TWICE).

It doesn't matter if you save the entry with CTRL+S or with the save button.

All fields save normally if you're making changes to a Draft. I have only observed this happening when you are making changes to the Current entry.

### Steps to reproduce

1. Create a Matrix block field with 3 fields: A dropdown, radio inputs, and plain text.
2. For the dropdown and radio inputs, create 5 or so options and just number them 1-5
3. Attach this field to a section
4. Create a new entry in the section, add a block to the matrix and set all the values to: 1 (including just writing 1 in the plain text)
5. The first save of the entry, everything should work fine.
6. But when you edit the entry and try to make changes to the fields, the first field you edit in the matrix block will not save, unless you change the first field twice.

### Expected behavior

All the fields to save when you edit them.

### Actual behavior

The first field you change does not get saved when you save the entry. The only exception is if you change the value of the first field, then change another field, and then change the first field again.

This was not happening in 4.3.6

https://user-images.githubusercontent.com/684903/216802033-32240e60-dc5a-4fad-a43a-4c5f601560e0.mp4

### Craft CMS version

4.3.7

### PHP version

8.0.2

### Installed plugins and versions

I used Andrew Welch's new spin-up-craft repo with no changes or the addition of other plugins.

https://github.com/nystudio107/spin-up-craft/blob/master/composer.json

The only change I made was bumping Craft to 4.3.7

**Comment by mmikkel** [comment]
I'm seeing the same thing. Looks like https://github.com/craftcms/cms/pull/12607/commits/4bf2fdaa5ebb8535a5c6db4b8c166dc9c7978940 could be the culprit; I'm not able to reproduce the behavior when I revert that change.

**Comment by JMKelley** [comment]
Seeing the same thing.

**Comment by brandonkelly** [comment]
Thanks for reporting! Craft 4.3.7.1 is out now with a fix.

**Comment by khalwat** [comment]
version was never updated: https://github.com/craftcms/cms/blob/develop/src/config/app.php#L6

**Comment by khalwat** [comment]
In case anyone else comes across this, the bug also seems to affect SuperTable fields as well (and potentially other block-type fields like Neo as well). So update to get the fix!
