### ISSUE TITLE
[4.3.7]: Asset Location setting has an invalid subpath (“{owner.id}”)

### ISSUE THREAD

**Issue by arifje** [craftcms/cms#12624]
### What happened?

Updated to 4.3.7 yesterday, getting the following error when saving existing entries:

![Screenshot 2023-02-05 at 15 45 51](https://user-images.githubusercontent.com/1286410/216826397-674a2859-5efd-4cc3-b895-548b88dc5848.png)

We've been using the {owner.id} as a subfolder for a long time like this;
 
![Screenshot 2023-02-05 at 15 39 35](https://user-images.githubusercontent.com/1286410/216826444-cf402e54-42ac-4e75-a763-5fc88e7c9704.png)

**Update**: it only seems to happen on entries that are ENABLED. When I disable an entry, the error is gone. When it's enabled, it's there again.

Craft 4.3.7
PHP 8.1.13
MariaDB
Imagick 3.7.0 (ImageMagick 6.9.10-23)

**Comment by brandonkelly** [comment]
Thanks for reporting! Just released Craft 3.7.64.1 and 4.3.7.1 with a fix.

It’s actually a bit of a fluke that this was ever working in the first place though. You only need that `owner` bit in there for Assets fields that are nested within Matrix/Super Table/Neo fields, where `owner` references the block’s “owner element” (the entry).

So even with the fix, you’d  be better off changing that subpath setting to just `/{id}/` or `{id}` (leading/trailing slashes are optional and meaningless).

**Comment by arifje** [comment]
Thanks!

**Comment by arifje** [comment]
Back again! 

Is it possible this has changed on CraftCMS 5? I am setting up a new site in Craft 5 and getting this error when saving a Asset field (thumbnails) when saving the entry. 

```
The Thumbnails field’s Asset Location setting has an invalid subpath (“{owner.id}”).
```

Asset location path:
![Image](https://github.com/user-attachments/assets/3a49de57-48e1-407d-980d-fa10588406fa)

It does work on an asset field that is a child of a Matrix field, but not on the an asset field, which is a direct child of the entry.

{id} works, but this does not seem to be the real entry ID, which we need to store the related assets.

**Comment by i-just** [comment]
Hi, thanks for getting in touch! 

> It does work on an asset field that is a child of a Matrix field, but not on the an asset field, which is a direct child of the entry.

When using dynamic subfolder paths, you should consider using separate fields for nested and non-nested elements’ field layouts. See the warning in [this section of the docs](https://craftcms.com/docs/5.x/reference/field-types/assets.html#dynamic-subfolder-paths).

> {id} works, but this does not seem to be the real entry ID, which we need to store the related assets.

When this field is part of, e.g. a section’s entry (root entry), the {id} will refer to that root entry’s ID. When the field is part of a matrix, it’ll refer to the nested entry’s (formerly called matrix block) ID.

**Comment by arifje** [comment]
Ah check, so I can use {owner.id} for fields in Matrix fields, and {id} for standalone fields in the entry.
Thanks!
