### ISSUE TITLE
[4.x]: manual sorting and moving entries in a structure is not working

### ISSUE THREAD

**Issue by nordentwickler** [craftcms/cms#12627]
### Description

After upgrading from 3.7.63.1 to 4.3.7 the functionality of sorting entries in a structure is broken. Applying the migrations and config files worked fine. All in all, the complete upgrade worked like a charm - no errors, no problems. Noting in the logs, no js-issues in the control panel. Upgrading to 4.3.7.1 wasn't on option yet, cause of an mismatching schema version 🤷

### Steps to reproduce

This sounds like a problem with this project and i think it is not easy do reproduce with a blank project. 

1. make the upgrade
2. try to sort entries in a structure (of course, change view to "structure")

### Expected behavior

The move button should appear, for changing the position of an entry inside of a structure.

### Actual behavior

![Bildschirm­foto 2023-02-06 um 12 40 03](https://user-images.githubusercontent.com/26166873/216963130-067ba9d0-f0c6-4df1-aff7-7b0cec344610.png)

No move button appears in a new or present structure.

### Craft CMS version

4.3.7

### PHP version

8.0.24

### Operating system and version

Linux 5.15.49-linuxkit (ddev loca)

### Database type and version

MySQL 5.7.38

### Image driver and version

Imagick 3.6.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- "craftcms/cms": "^4.3.7",
- "vlucas/phpdotenv": "^3.4.0",
- "craftcms/redactor": "3.0.3",
- "doublesecretagency/craft-inventory": "2.2.0",
- "verbb/expanded-singles": "2.0.0",
- "ether/logs": "4.0.0",
- "dolphiq/redirect": "2.0.0",
- "craftcms/contact-form": "3.0.0",
- "putyourlightson/craft-snaptcha": "4.0.1",
- "nystudio107/craft-seomatic": "4.0.19",
- "hybridinteractive/craft-contact-form-extensions": "4.2.2",
- "hybridinteractive/craft-position-fieldtype": "4.0.0-beta.3",
-  "besteadfast/craft-preparse-field": "2.0.2",
- "webhubworks/craft-ohdear": "4.0.2"

**Comment by i-just** [comment]
Hi, thanks for reaching out. You are right; it’s not easy to reproduce. Can you send over your database backup, `composer.json` and `composer.lock`, to support@craftcms.com so we can dig deeper?

**Comment by nordentwickler** [comment]
@i-just thank you!

**Comment by olivierbon** [comment]
`"minimum-stability": "dev"` in `composer.json` cause the update to go to `4.4.x-dev` rather than `4.3` highlighting an issue we'll be fixing shortly.

Re-running the upgrade to `4.3.7.1` fixed the problem.
