### ISSUE TITLE
[4.x]:  Disabled All Sources on Element Listing Page

### ISSUE THREAD

**Issue by darinlarimore** [craftcms/cms#12634]
### Description
Disabling all sources on an element listing page breaks page upon reload.

### Steps to reproduce

1. Open an elements listing page. (Entires, Assets, Categories, products all seem to be effected)
2. Click Customize Sources gear icon.
3. Disable all sources and save.
4. Elements listing page will not show any results.
<img width="1290" alt="Screenshot 2023-02-06 at 11 06 05 AM" src="https://user-images.githubusercontent.com/20300635/217039138-37078830-b0a9-4b5b-802a-84d7f238c9a1.png">
<img width="1292" alt="Screenshot 2023-02-06 at 11 05 45 AM" src="https://user-images.githubusercontent.com/20300635/217039161-5a6d354c-4388-46aa-80c9-6af46d9a7d98.png">

### Expected behavior
- A default view should always display
- A gear icon could alway be present allow for reconfiguration

### Actual behavior
- Elements list view doesn't show any items, and stuck loading.

### Craft CMS version

4.3.6.1

### PHP version

8.2.0

### Operating system and version

OSX Version 13.2

### Database type and version

MySQL 8.0.19

### Installed plugins and versions
Reproducible on a barebones site with just:
"craftcms/cms": "4.3.6.1",
"craftcms/commerce": "4.2.4",

**Comment by i-just** [comment]
Hi, thanks for reporting. I created a PR to fix this.

**Comment by brandonkelly** [comment]
Craft 4.3.8 is out with a fix for this, via #12642.
