### ISSUE TITLE
[4.x]: Null-values in .env are not correctly interpreted

### ISSUE THREAD

**Issue by alexgit2k** [craftcms/cms#12632]
### Description

Some configuration-values can be set to `null` accordingly to the documentation like:
- [pathParam](https://craftcms.com/docs/4.x/config/general.html#pathparam)
- [phpSessionName](https://craftcms.com/docs/4.x/config/general.html#phpsessionname)
- [cpTrigger](https://craftcms.com/docs/4.x/config/general.html#cptrigger)

However, if `null` in the `.env`-file is used it is interpreted as string and not as `null`-value. Which leads to `null`in URLs (PathParam) or `null`as session-name (phpSessionName).

Applies to [src/config/GeneralConfig.php](https://github.com/craftcms/cms/blob/4.4/src/config/GeneralConfig.php) and [docs/4.x/config/general.md](https://github.com/craftcms/docs/blob/main/docs/4.x/config/general.md).
### Steps to reproduce

1. Use `CRAFT_PATH_PARAM=null` in `.env`

### Expected behavior

Action-URLs should be https://example.com/admin/actions/...

### Actual behavior

Action-URLs are https://example.com/index.php?null=admin/actions/...

### Workarounds

- `CRAFT_PATH_PARAM=` in `.env`-file
- `CRAFT_PATH_PARAM=false` in `.env`-file
- `->pathParam(null)` in config

### Craft CMS version

4.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! This was actually a documentation bug. The correct way to specify null values is just an empty value:

```sh
CRAFT_PATH_PARAM=
```
