### ISSUE TITLE
[3.x]: Slowness after upgrading to 3.7.64.1 from 3.7.63.1

### ISSUE THREAD

**Issue by eduardoalonsoalbella** [craftcms/cms#12645]
### Description

Sorry for not being able to give more information

A few articles, with lots of children started to load in prod (timeout in nginx), craft seems to be able to perform the request, but now it takes a lot more time than in previous versions

We fixed it by downgrading to our previous version (3.7.63.1)

<img width="1355" alt="Captura de pantalla 2023-02-08 a las 12 32 11" src="https://user-images.githubusercontent.com/90317987/217521373-55ad9b49-4f52-4136-bdda-1cc668d17c4c.png">
Memory usage lowered after downgrading

### Steps to reproduce

1. Upgrade to 3.7.64.1
2. Requests take longer

### Expected behavior

At least the same speed

### Actual behavior

Slower

### Craft CMS version

3.7.64.1

### PHP version

8.1

### Operating system and version

Apache/2.4.53 (Debian) 

### Database type and version

MySQL 5.7.38

### Installed plugins and versions

- neo, matrix, supertables all in their latest version

**Comment by brandonkelly** [comment]
This is almost certainly caused by a bug where element attributes weren’t getting eager-loaded properly in 3.7.64 and 3.7.65. We just released 3.7.65.1 with a fix for that, via #12646.

**Comment by brandonkelly** [comment]
Note that if you updated to 3.7.65 already, you will be affected by [this bug](https://github.com/craftcms/cms/issues/12647), which was also fixed in 3.7.65.1. If so you will need to run `composer update` to fix.

**Comment by eduardoalonsoalbella** [comment]
ok, thanks!!
