### ISSUE TITLE
[4.x]: Revision Notes not working

### ISSUE THREAD

**Issue by olsp** [craftcms/cms#12641]
### What happened?

I tried to use the revision notes for entries but everytime I change field value, write something in the revision note field and save, the text in the revision notes are gone.

In my template I already prepared the code to display the notes on the frontend like this `{{ entry.revisionNotes }}`, but then I get an error: "`Invalid Call – yii\base\InvalidCallException Getting write-only property: craft\elements\Entry::revisionNotes`"

Are the revision notes not meant to be used like this?

### Craft CMS version
4.3.6.1

### PHP version
8.0.14

**Comment by brianjhanson** [comment]
Thanks for reporting! At the moment `revisionNotes` are `protected` which means you can't access them with other entry properties. We may end up making those more public (potentially in the process of implementing #12610). If you need to get at them in the meantime, you are able to access them the same way [we do for the entry table](https://github.com/craftcms/cms/blob/ce9ca3370de2a43833547a6f339c5ed0e2ca1338/src/elements/Entry.php#L1537-L1547).

```twig
{% set revision = entry.currentRevision %}  
{% if revision %}  
    {% set behavior = revision.getBehavior('revision') %}  
    {% if behavior %}  
        {{ behavior.revisionNotes }}  
    {% endif %}  
{% endif %}
```

**Comment by brandonkelly** [comment]
> I tried to use the revision notes for entries but everytime I change field value, write something in the revision note field and save, the text in the revision notes are gone.

This should be fixed now, in Craft 4.3.8. Revision notes that were set on the input weren’t being retained when you reloaded the entry edit page.

**Comment by olsp** [comment]
Thanks for looking into this. I updated to 4.3.8 and now the revision notes are saved while an entry is a draft but as soon as I save the entry, the revision notes are gone. When writing a new revision note for a published entry, they disappear as soon as I save the entry.

**Comment by brandonkelly** [comment]
The current revision’s notes should show up within the meta info, below the editable note input:

<img src="https://user-images.githubusercontent.com/47792/217518954-ce402646-2922-47c0-acfd-d35791095960.png" width="355" height="182" alt="Screenshot of entry metadata">

**Comment by olsp** [comment]
Am I doing something wrong? They don't show up for me.
![revision-notes](https://user-images.githubusercontent.com/1073442/217578833-596793a9-4de9-4291-8760-b485d47936f8.gif)

**Comment by brianjhanson** [comment]
Very odd. I'm not seeing the same behavior on a clean install. Is there anything in `storage/logs` that might provide a clue?

**Comment by brandonkelly** [comment]
@olsp Does your section have versioning enabled?

**Comment by olsp** [comment]
Yes, I do see versions. I just created a new version with a revision note. When I switch to the previous version, I do see the "old" revision note. So it seems like the only the current revision note isn't visible.

**Comment by olsp** [comment]
@brianjhanson here is what I have added to the config:
```
'limitAutoSlugsToAscii' => true,
'convertFilenamesToAscii' => true,
'maxUploadFileSize' => 335544320,
'maxRevisions' => 0,
'sendPoweredByHeader' => false,
'postLoginRedirect' => 'dashboard',
'setPasswordRequestPath' => 'reset-password'
```

I don't really know what to look for in the logs. Do you have a hint what to look into?

**Comment by brianjhanson** [comment]
Can you send over a database dump, `composer.lock` and `composer.json` files to support@craftcms.com, and we can dig in a bit more?

**Comment by brandonkelly** [comment]
All fixed for the next Craft 3 and 4 releases, via #12661. Thanks for bearing with us @olsp!

**Comment by brandonkelly** [comment]
Craft 3.7.66 and 4.3.9 are out with that fix!
