### ISSUE TITLE
[4.x]: Duplicate entry from one site to another in channel with propagation method Let each entry choose which sites it should be saved to

### ISSUE THREAD

**Issue by widewebpro** [craftcms/cms#12657]
### Description

Hello,

I have a craft cms multisite, have channels with entries propagation method "Let each entry choose which sites it should be saved to"

I try to duplicate entry from one site to another, by "save as new entry" in entry edit page in admin panel, with choose site in sidebar. But craft was moved entry on new site, and duplicated in first site.

### Steps to reproduce

1. Go to entry in channel with entries propagation method "Let each entry choose which sites it should be saved to"
2. Open Entry
3. Change status in sidebar disable for current site and enabled for another site.
4. Click "Save as new entry"

### Craft CMS version

4.3.5

### PHP version

8.1.13

### Operating system and version

Linux 4.15.0-197-generic

### Database type and version

MySQL 10.3.27

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.7-4)

### Installed plugins and versions

-
![image](https://user-images.githubusercontent.com/66615356/217760024-92bd6355-8949-4949-afbc-b713274d97f5.png)

**Comment by brianjhanson** [comment]
This is currently working as expected, although I realize it can be a little awkward. When you select "Save as new entry" a new entry will be created from your current draft, and the current draft will be discarded (as of [#12165](https://github.com/craftcms/cms/issues/12165)). That means you end up with two entries, one as the entry was before you edited it on the original site, and a duplicate with the changes you made on both sites. 

I may not completely understand what you're going for, but it sounds like just selecting "Add a site.." from the sidebar may handle your use case. That will take all the current values and propagate them to the new site on save. After that, you'll have an entry on each site that can be edited or enabled/disabled independently. 

I'm going to close out this issue, but we're happy to answer any additional questions.
