### ISSUE TITLE
[4.3.9]: PHP error in CP when using S3 for assets and transforms in same volume

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#12678]
### Description
Just installed the 4.3.9 update and I get an error when I try to access the control panel. 

There is the below error in `phperrors.log` : 

```[14-Feb-2023 22:20:44 Europe/Athens] PHP Fatal error:  Nesting level too deep - recursive dependency? in /var/www/html/vendor/craftcms/cms/src/helpers/Assets.php on line 137```

I presume the error has to do with the fix for https://github.com/craftcms/cms/issues/12663

It also probably has to do with the fact that I'm not using a local file system: I use an S3 Bucket via the official plugin.

### Steps to reproduce

1. Update a Craft project with an Amazon S3 filesystem to 4.3.9
2. Try to access the control panel

### Expected behavior

You can actually access the control panel😊

### Actual behavior

A php error occurs 😥

### Craft CMS version

4.3.9

### PHP version

8.2

### Installed plugins and versions

 Amazon S3	2.0.1

**Comment by angrybrad** [comment]
@thupsi I'm not able to reproduce this on a fresh 4.3.9 install with the S3 plugin. Any chance you can send a database dump and your composer.json/lock files over to support@craftcms.com and reference this ticket? We’ll dig into it more from there.

**Comment by thupsi** [comment]
@angrybrad Just sent them over!

**Comment by thupsi** [comment]
Still investigating this with the help of @angrybrad. Just updated the title of the issue to clarify and reflect newest findings.

**Comment by brandonkelly** [comment]
Thanks for the help, @thupsi! We’ve managed to reproduce and fix this. I’ll get a hotfix release out soon with the fix, but for now you cat test by changing your `craftcms/cms` requirement in `composer.json` to `"dev-develop as 4.3.9"`, and run `composer update`.

**Comment by brandonkelly** [comment]
Craft 4.3.10 is out with the fix for this.
