### ISSUE TITLE
[4.x]: Search not working in Table date field

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#12670]
### Description

Entries query is prepared for pagination with eager loading:

```
{% set entriesQuery = craft.entries.section('events').with(['cover']) %}
{% set dates = 'dates:2023-02-13 OR dates:2023-02-14' %}
{% do entriesQuery.search(dates) %}
{% set entriesQuery = entriesQuery.limit(limit) %}
```

I'm trying to search matching dates in the `dates` field (and specifically inside the `date` field date column, but that I think that can't specify in the search terms).

`defaultSearchTermOptions` are set like this:
```
'defaultSearchTermOptions' => array(
	'subLeft'  => true,
	'subRight' => true
)
```

Of course, the `dates` field is set to `Use this field’s values as search keywords`, and entries have been resaved using `./craft resave/entries --section=events --update-search-index`.

I have also tried to reduce the query to one date only, but without getting result:
`{% set dates = 'dates:2023-02-13' %}`.

I have also tried to search more widely by the use of `::` instead of `:`, but without getting result:
`{% set dates = 'dates::2023-02-13' %}`.

FYI, this search was working previously fine in a Craft 2 website.

### Steps to reproduce

1. Prepare a search query that look up for dates within a table field (date field column)

### Expected behavior
Give results.

### Actual behavior
No results.

### Craft CMS version

4.3.8.2

### PHP version

8.1.0

### Database type and version

MySQL 5.7.39

### Installed plugins and versions

-

**Comment by romainpoirier** [comment]
Thank you! I'm now using this method to get the `<fieldName>`:

```
{% set datesField = craft.app.fields.getFieldByHandle('dates') %}
{% set ElementHelper = create('craft\\helpers\\ElementHelper') %}
{% set datesColumn = ElementHelper.fieldColumnFromField(datesField) %}
{% do entriesQuery.where(['like', datesColumn, '2023-02-14']) %} 
```

Where `datesColumn` = `field_dates_uckrdnbg`.

In which table of the database can I retrieve `field_dates_uckrdnbg` and check the matched content?

Unfortunately, I'm still not getting the expected result.

**Comment by i-just** [comment]
That field will be in the `content` table.

**Comment by romainpoirier** [comment]
I the `craft_content` table, I have searched on the `field_dates_uckrdnbg` field where value is `LIKE` `2023-02-13`, but I don't get any result while I have a few entries with this date set (using the Date field within the Table field).

I can confirm that with reduced test, within another template, and without the eager-loading / pagination query parameters, this is also not working:

```
{% set date = '2023-02-13' %}
{% set datesField = craft.app.fields.getFieldByHandle('dates') %}
{% set ElementHelper = create('craft\\helpers\\ElementHelper') %}
{% set datesColumn = ElementHelper.fieldColumnFromField(datesField) %}
{% set entries = craft.entries.section('events').where(['like', datesColumn, date]) %}

{{ d({
	date: date,
	total: entries.count()
}) }}

<ul>
	{% for entry in entries.all() %}
		<li>
			<h4>
				{{ entry.title }}
			</h4>
			<p>
				{{ 'From {from} to {to}' | t({
					from: entry.from | date('Y-m-d'),
					to: entry.to | date('Y-m-d')
				}) }}
			</p>
		</li>
	{% endfor %}
</ul>
```

It is filtering entries, but while I have updated the search index (`--update-search-index`) I get a lot of entries where the date `2023-02-13` is not registered in the table columns.

Furthermore, I anticipate my next question: how to order these entries by date table field value using `orderBy`?

**Comment by romainpoirier** [comment]
I can see in my table that the content is formatted like that:
`[{"col1":"2023-03-04 23:00:00","col2":"2023-02-13 10:00:00","col3":"2023-02-13 18:00:00","col6":null}]`

Are you sure that a query like below is appropriate? Because it doesn't work.
`{% set entries = craft.entries.section('events').where(['like', datesColumn, '2023-02-13']) %}`

**Comment by i-just** [comment]
When you use `like` in the `where` condition, Craft will add the `%` for you.
 
You can check what the actual query is with `.rawSql()`, e.g.: `{{ craft.entries.section('events').where(['like', datesColumn, '%2023-02-13%']).rawSql() }}`

DateTime fields haven’t been included in the search index since Craft 3.

**Comment by romainpoirier** [comment]
I have first tried without the `%`, and was getting incorrect results, that's why I tried the `%` after:
`{% set entries = craft.entries.section('events').where(['like', 'field_dates_uckrdnbg', '2023-02-14']) %}`

So using this (without the `%`) in combination with `.rawSql()`, I get the following:

> SELECT `elements`.`id`, `elements`.`canonicalId`, `elements`.`fieldLayoutId`, `elements`.`uid`, `elements`.`enabled`, `elements`.`archived`, `elements`.`dateLastMerged`, `elements`.`dateCreated`, `elements`.`dateUpdated`, `elements_sites`.`id` AS `siteSettingsId`, `elements_sites`.`slug`, `elements_sites`.`siteId`, `elements_sites`.`uri`, `elements_sites`.`enabled` AS `enabledForSite`, `entries`.`sectionId`, `entries`.`typeId`, `entries`.`authorId`, `entries`.`postDate`, `entries`.`expiryDate`, `content`.`id` AS `contentId`, `content`.`title`, `content`.`field_accessibilityId_emrukfah`, `content`.`field_activity_fbuxsoln`, `content`.`field_addresses_vzqrqfuv`, `content`.`field_userNotificationsArticles_vddnrqci`, `content`.`field_artist_pdxmxaem`, `content`.`field_body_vbyuaoyo`, `content`.`field_proRegisterRequestBody_xkeaiyhm`, `content`.`field_weekschema1BreakFrom_gviuxtgw`, `content`.`field_weekschema2BreakFrom_esizulte`, `content`.`field_weekschema3BreakFrom_douamuxs`, `content`.`field_weekschema4BreakFrom_bjxtkyyq`, `content`.`field_weekschema5BreakFrom_nxegqtte`, `content`.`field_weekschema6BreakFrom_eslizizn`, `content`.`field_weekschema7BreakFrom_elwrfwie`, `content`.`field_weekschema1BreakTo_ugstrmal`, `content`.`field_weekschema2BreakTo_smrnfnau`, `content`.`field_weekschema3BreakTo_sgldeixn`, `content`.`field_weekschema4BreakTo_xzmxcftf`, `content`.`field_weekschema5BreakTo_vhwsjvln`, `content`.`field_weekschema6BreakTo_oitkuvzi`, `content`.`field_weekschema7BreakTo_ttoznlpx`, `content`.`field_newsletterButton_uczpxwpa`, `content`.`field_bodyCaption_bxpbkfbd`, `content`.`field_caption_qnwrpgff`, `content`.`field_weekschema1Closed_en_tdxnhcpb`, `content`.`field_weekschema1Closed_fr_obhoycfe`, `content`.`field_weekschema1Closed_nl_smuogwpn`, `content`.`field_weekschema2Closed_en_wzkeuxfb`, `content`.`field_weekschema2Closed_fr_ptgvfdku`, `content`.`field_weekschema2Closed_nl_zteasloc`, `content`.`field_weekschema3Closed_en_ofjjmstm`, `content`.`field_weekschema3Closed_fr_anctendh`, `content`.`field_weekschema3Closed_nl_ngvltxrt`, `content`.`field_weekschema4Closed_en_hnmgltfg`, `content`.`field_weekschema4Closed_fr_ynkjadhc`, `content`.`field_weekschema4Closed_nl_jsrgtcvj`, `content`.`field_weekschema5Closed_en_alzqduyr`, `content`.`field_weekschema5Closed_fr_hihvuijt`, `content`.`field_weekschema5Closed_nl_yitdkoce`, `content`.`field_weekschema6Closed_en_naebxbfx`, `content`.`field_weekschema6Closed_fr_enanxxin`, `content`.`field_weekschema6Closed_nl_itsqtqra`, `content`.`field_weekschema7Closed_en_xsweyjnf`, `content`.`field_weekschema7Closed_fr_dquzeyrz`, `content`.`field_weekschema7Closed_nl_trtkwyog`, `content`.`field_weekschemaClosingDays_yxgmxjni`, `content`.`field_userNotificationsComments_qfmsdasa`, `content`.`field_credits_pakttins`, `content`.`field_notificationDate_ihthzwvk`, `content`.`field_dates_uckrdnbg`, `content`.`field_jobsDeadline_emhbbzqk`, `content`.`field_footerDescription_neqdciyy`, `content`.`field_seoDescription_guwallkx`, `content`.`field_proRegisterRequestEmail_hwwhbtub`, `content`.`field_emails_wrpskyzs`, `content`.`field_weekschemaExceptionDays_hwnviuji`, `content`.`field_weekschemaExceptionDaysTable_nhjypner`, `content`.`field_externalLink_acgkoiqm`, `content`.`field_idsFacebookApp_hvfhwjys`, `content`.`field_idsFacebookPixel_bypqieho`, `content`.`field_userNotificationsForum_ymgziuyo`, `content`.`field_freeInfos_en_attfjqjs`, `content`.`field_freeInfos_fr_xfgdlysm`, `content`.`field_freeInfos_nl_vwhmgpps`, `content`.`field_weekschema5_wcltlfwk`, `content`.`field_from_hiqacusr`, `content`.`field_highlightedOnAgendaCampaignFrom_pleodrig`, `content`.`field_highlightedOnHomepageCampaignFrom_hbjlngoi`, `content`.`field_weekschema1From_fougzosw`, `content`.`field_weekschema2From_rngskbie`, `content`.`field_weekschema3From_ypnoobcp`, `content`.`field_weekschema4From_nyohpixl`, `content`.`field_weekschema5From_nrydtdoj`, `content`.`field_weekschema6From_fgonelaw`, `content`.`field_weekschema7From_euvzagbo`, `content`.`field_idsGoogleAnalytics_hkooofij`, `content`.`field_bodyGrid_zcdclsdl`, `content`.`field_highlighted_zsnqikyb`, `content`.`field_bodyHtml_pfcsjrax`, `content`.`field_projectsIcon_gtzaozze`, `content`.`field_accessibilityIcons_bqgdrchl`, `content`.`field_artworksID_miqspfzs`, `content`.`field_importId_ztafyrnp`, `content`.`field_accessibilityInfos_xtjmtaoj`, `content`.`field_introduction_hygnifeg`, `content`.`field_isFree_bcckufhw`, `content`.`field_userNotificationsJobs_amymlzqs`, `content`.`field_entryLanguage_yfmcguuc`, `content`.`field_userLanguage_qpbrhesq`, `content`.`field_importLastUpdate_rzchxihs`, `content`.`field_life_lsftclop`, `content`.`field_jobsLink_gfsxfeid`, `content`.`field_newsletterLink_czmtqzjf`, `content`.`field_socialNetworksLinks_fterrylp`, `content`.`field_map_zavubiqs`, `content`.`field_bodyMode_ziulejik`, `content`.`field_weekschema1_gkwqzyur`, `content`.`field_userNotificationsMuseum_tpnojknr`, `content`.`field_museumId_ggnsxoyv`, `content`.`field_highlightedOnAgenda_flvfbcbx`, `content`.`field_highlightedOnHomepage_bsfkdxrt`, `content`.`field_period_pmsqahoa`, `content`.`field_phoneNumbers_dbskcfii`, `content`.`field_placeName_ogokfnft`, `content`.`field_postCode_etcswgip`, `content`.`field_price_hiwhacup`, `content`.`field_bodyQuote_zccvhpeg`, `content`.`field_redactionalTitle_tjrbxnhl`, `content`.`field_weekschema6_cluqqukw`, `content`.`field_notificationSent_xnpryyfx`, `content`.`field_bodySize_fjkllejy`, `content`.`field_socialNetworks_ztzqjefa`, `content`.`field_proRegisterBodySteps_djiallmx`, `content`.`field_proRegisterRequestSubject_kyhlckuy`, `content`.`field_agendaExhibitionsEventsSubtitle_ozmwdtgp`, `content`.`field_agendaHighlightsSubtitle_ktvobcxi`, `content`.`field_homepageArticlesSubtitle_ybsaxhju`, `content`.`field_homepageEventsSubtitle_xiljnanx`, `content`.`field_homepageNewsSubtitle_qfrbjssj`, `content`.`field_homepageProjectsSubtitle_djvqusze`, `content`.`field_newsAdvicesSubtitle_toxtvwyx`, `content`.`field_newsNewsSubtitle_eidssjzc`, `content`.`field_proDashboardFilesSubtitle_kswqgwhx`, `content`.`field_proDashboardPagesSubtitle_hjrnlnmm`, `content`.`field_weekschema7_cqoiauvg`, `content`.`field_importTargetId_emdvvsxh`, `content`.`field_bodyText_viniopnp`, `content`.`field_weekschema4_yptqohoh`, `content`.`field_ticketing_msbuvyho`, `content`.`field_idsTikTokPixel_gamrzuzq`, `content`.`field_agendaExhibitionsEventsTitle_swhvanfl`, `content`.`field_agendaHighlightsTitle_ikrajbcc`, `content`.`field_bodyTitle_uzllsiin`, `content`.`field_homepageArticlesTitle_asndwjwg`, `content`.`field_homepageBannerTitle_umjzlanp`, `content`.`field_homepageEventsTitle_bqncnqxk`, `content`.`field_homepageNewsTitle_awlfnkrg`, `content`.`field_homepageProjectsTitle_etjjajij`, `content`.`field_newsAdvicesTitle_arfjnacd`, `content`.`field_newsletterTitle_fnkfqltm`, `content`.`field_newsNewsTitle_uedlayoc`, `content`.`field_proDashboardFilesTitle_rzfqxgmq`, `content`.`field_proDashboardPagesTitle_ewonkxpd`, `content`.`field_proRegisterBodyTitle_ehukkgjj`, `content`.`field_seoTitle_nebnuhyo`, `content`.`field_socialNetworksTitle_beurgtmt`, `content`.`field_highlightedOnAgendaCampaignTo_tnipjzid`, `content`.`field_highlightedOnHomepageCampaignTo_ymzzbfap`, `content`.`field_to_uienhxgn`, `content`.`field_weekschema1To_tdjyeptx`, `content`.`field_weekschema2To_fxrkyoin`, `content`.`field_weekschema3To_gmiywown`, `content`.`field_weekschema4To_xvbqgaty`, `content`.`field_weekschema5To_flhigtpy`, `content`.`field_weekschema6To_lkwplced`, `content`.`field_weekschema7To_fiqvscjo`, `content`.`field_translation_nyqhnxqe`, `content`.`field_weekschema2_iplgcsvx`, `content`.`field_importUrl_woakwyit`, `content`.`field_videos_rtatngri`, `content`.`field_visibleInFilter_ydkhaxpb`, `content`.`field_websites_gdsyxhpg`, `content`.`field_weekschema3_pacbdgcj` FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId` FROM `craft_elements` `elements` INNER JOIN `craft_entries` `entries` ON `entries`.`id` = `elements`.`id` INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id` INNER JOIN `craft_content` `content` ON (`content`.`elementId` = `elements`.`id`) AND (`content`.`siteId` = `elements_sites`.`siteId`) WHERE (`entries`.`sectionId`=8) AND (`field_dates_uckrdnbg` LIKE '%2023-02-14%') AND (`elements_sites`.`siteId`=2) AND (`elements`.`archived`=FALSE) AND (((`elements`.`enabled`=TRUE) AND (`elements_sites`.`enabled`=TRUE)) AND (`entries`.`postDate` <= '2023-02-14 08:17:59') AND ((`entries`.`expiryDate` IS NULL) OR (`entries`.`expiryDate` > '2023-02-14 08:17:59'))) AND (`elements`.`dateDeleted` IS NULL) AND (`elements`.`draftId` IS NULL) AND (`elements`.`revisionId` IS NULL) ORDER BY `entries`.`postDate` DESC) `subquery` INNER JOIN `craft_elements` `elements` ON `elements`.`id` = `subquery`.`elementsId` INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId` INNER JOIN `craft_entries` `entries` ON `entries`.`id` = `subquery`.`elementsId` INNER JOIN `craft_content` `content` ON `content`.`id` = `subquery`.`contentId` ORDER BY `entries`.`postDate` DESC

Like said before, it gives me results, but almost 1 of 2 is incorrect. For those who are not corrects, they have `2023-02-15` in their dates, while I'm trying to get the ones with `2023-02-14`.

Looks like a timezone error: any idea how to fix it?

FYI, in my `general/config.php` file, timezone is set like this: `'timezone' => 'Europe/Brussels'`

**Comment by romainpoirier** [comment]
I'm also facing another issue with the `.where()` method.

I need to search for several dates at once, but a succession of dates does not work:
`2023-02-14 OR 2023-02-15 OR 2023-02-16 OR 2023-02-17 OR 2023-02-18 OR 2023-02-19`

The above does not give any result, while one `2023-02-14` or `2023-02-15` does.

This is working:
`{% set entries = craft.entries.section('events').where(['like', 'field_dates_uckrdnbg', '2023-02-14']) %}`

This is not working:
`{% set entries = craft.entries.section('events').where(['like', 'field_dates_uckrdnbg', '2023-02-14 OR 2023-02-15 OR 2023-02-16 OR 2023-02-17 OR 2023-02-18 OR 2023-02-19']) %}`

**Comment by brandonkelly** [comment]
@romainpoirier Date fields use DATETIME columns, regardless of whether you are showing the time. So their values are in the format `YYYY-MM-DD HH:MM:SS`, not just `YYYY-MM-DD`. Your `like` query is working because it basically makes it a fuzzy value search, where there could be additional data on either side of the `2023-02-14` bit.

The following query should work:

```twig
{% set entries = craft.entries()
  .section('events')
  .where(['or',
    ['like', 'field_dates_uckrdnbg', '2023-02-14'],
    ['like', 'field_dates_uckrdnbg', '2023-02-15'],
    ['like', 'field_dates_uckrdnbg', '2023-02-16'],
    ['like', 'field_dates_uckrdnbg', '2023-02-17'],
    ['like', 'field_dates_uckrdnbg', '2023-02-18'],
    ['like', 'field_dates_uckrdnbg', '2023-02-19'],
  ])
  .all() %}
```

Or you could specify a range, which doesn’t require that you specify the time values:

```twig
{% set entries = craft.entries()
  .section('events')
  .where(['and',
    ['>=', 'field_dates_uckrdnbg', '2023-02-14'],
    ['<', 'field_dates_uckrdnbg', '2023-02-20'],
  ])
  .all() %}
```

You could do the same using the `dates` field’s element query param as well:

```twig
{% set entries = craft.entries()
  .section('events')
  .dates(['and', '>= 2023-02-14', '< 2023-02-20'])
  .all() %}
```

(See [Querying Elements with Date Fields](https://craftcms.com/docs/4.x/date-time-fields.html#querying-elements-with-date-fields).)

**Comment by romainpoirier** [comment]
Thank you @brandonkelly, I have tested these cleaner queries and can confirm that in my case the first one (`or`) is working but not the second one (`and`).

As explained by @i-just, the last one with `.dates(['and', '>= 2023-02-14', '< 2023-02-20'])` won't work here as it's a Date field within a Table field.

Do you have any idea about how to fix the [`timezone` issue](https://github.com/craftcms/cms/issues/12670#issuecomment-1429317543)?

**Comment by i-just** [comment]
By default, MySQL uses UTC as its timezone. UTC is the same as GMT. 

Europe/London is currently in GMT.
Europe/Brussels is currently in GMT+1.

If I set the system timezone to Europe/London and select a date: 2023-02-06 - it’s stored in the DB as: `[{"col1":"2023-02-06 00:00:00"}]`

If I set the system timezone to Europe/Brussels and select a date: 2023-02-06 - it’s stored in the DB as: 
`[{"col1":"2023-02-05 23:00:00"}]`

Assuming your database uses UTC, what you could do is make sure that the date you’re searching for is converted to UTC; 

for example: if I set the system timezone in Craft to `Europe/Brussels` and then print this in my template `{{ '2023-02-06'|date('Y-m-d H:i:s', "UTC") }}`, the result is: `2023-02-05 23:00:00`. 

So, you could modify your query to look like this: `craft.entries.section('events').where(['like', datesColumnName, '2023-02-06'|date('Y-m-d', "UTC")])`.

**Comment by romainpoirier** [comment]
Thank you very much for your clear explanations.

It works, as I have only correct entries, I mean all entries are within the range of the date. However, it's missing some entries, because before to apply the `timezone` setting + `|date('Y-m-d', "UTC")` I was getting a few more total of entries.

Do you understand why this solution still miss some entries? Is it because entries should be resaved and/or updated in DB after this timezone edit?

**Comment by i-just** [comment]
I would double-check the dates in the control panel for the entries that your query is missing.

**Comment by romainpoirier** [comment]
Thank you, after double-check it looks like that the additional entries I was getting before were not legit.
For now, I can confirm that your fix is working. I'll update here if I get any unexpected result.
