### ISSUE TITLE
[4.x]: Asset thumbnails are not centered in asset field element thumbs

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#12682]
### Description

Not sure when this started happening, but in recent 4.3.x versions asset thumbnails are no longer centered in element thumbs in asset fields:

<img width="416" alt="CleanShot 2023-02-15 at 11 26 52@2x" src="https://user-images.githubusercontent.com/298510/219002140-15c33344-f412-4157-975c-9e38681aa4e3.png">

It's only in asset fields, though – element thumbs in asset indexes seem fine:

<img width="344" alt="CleanShot 2023-02-15 at 11 29 14@2x" src="https://user-images.githubusercontent.com/298510/219002461-d7975281-2b34-414e-b510-ba94b64bbf1f.png">

### Steps to reproduce

1. Select an asset in an assets field, and select/focus it
2. Note that the thumbnail isn't centered within the .elementhumb container

### Craft CMS version

4.3.9

### Operating system and version

macOS 12.6, observed on MS Edge 109.0.1518.78

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Craft 4.3.10 is out with the fix for thsi.
