### ISSUE TITLE
[4.x]: Clicking the scrollbar when trying to add a new matrix block closes the popup

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#12681]
### Description

We have a lot of Matrix blocks, enough that a scrollbar appears when you want to add a new block above another block. Video attached of trying to add a new matrix block above an existing one, then clicking the scrollbar to scroll down. It closes the box.

https://user-images.githubusercontent.com/1250017/218960058-14e78481-9698-4a27-b62c-e9fda28f3da6.mov

### Expected behavior
You should be able to click the scrollbar to scroll it down

### Actual behavior
The box closes

### Craft CMS version

4.3.8.2

### PHP version

8.1.15

### Operating system and version

MacOS (with normal mouse)

### Database type and version

MySQL 8.0.32

### Image driver and version

GD 8.1.15

### Installed plugins and versions

Admin Bar	3.2.0
Dashboard Begone	2.0.0
Formie	2.0.22
Redactor	3.0.3
Retcon	2.6.0
Retour	4.1.10
SEOmatic	4.0.20
Sherlock	4.3.0
Sprig	2.5.1
Super Table	3.0.7
Twigpack	4.0.0-beta.4
Typed link field	2.1.5
Wishlist	2.0.4

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed now for the next Craft 3 and 4 releases.

**Comment by brandonkelly** [comment]
Craft 3.7.67 and 4.3.10 are each out with the fix for this.
