### ISSUE TITLE
[4.3]: Assets in subfolders only sortable by title

### ISSUE THREAD

**Issue by dr-codswallop** [craftcms/cms#12688]
### Description
When viewing the assets library in the CP, only those assets which exist in the root of the volume are sortable by various columns : id, title, file-kind, file-name, file-size, date-uploaded, date-modified, file-modified. Whereas assets which are in subfolders are only sortable by title. 

This seems to have crept in from Craft 4.3^. It's not happening on any of my sites still on 4.2.x

### Steps to reproduce

1. Upload files to the root of an asset volume - sort asc/desc on various columns - works as expected
2. Create a subfolder in that asset volume
3. Upload or move files to the subfolder - try sorting these assets asc/desc on various columns - only works for sorting title column

### Expected behavior
Assets should be sortable on all sortable columns regardless of if they're in subfolder

### Actual behavior
Only assets which are not in subfolders are sortable by anything other than title.

### Craft CMS version

4.3.1 - 4.3.9

### PHP version

8.2.0

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting! Craft 4.3.10 is out with a fix for this (via #12693).
