### ISSUE TITLE
[3.7.59]: Additional fields for assets not saved when temporary asset location in Local Temp Folder and permanent location in AWS Bucket until the whole entry is saved

### ISSUE THREAD

**Issue by mnlmaier** [craftcms/cms#12695]
### Description
We have defined several additional fields for assets, including a text field for image credits. Assets are stored in an S3 Bucket. The issue occurs when uploading images directly via the "Upload a file" button while using a temporary asset folder which is stored locally.
![image](https://user-images.githubusercontent.com/15020024/219698785-49d25fdb-7a9e-4d6f-9bc6-d52f99cec69d.png)
![image](https://user-images.githubusercontent.com/15020024/219699772-e50e1bb5-2812-472c-83e7-7bac47030198.png)

After the image is uploaded, double click the image **without saving the ** entry first to edit it. Note that the image will still be stored in the temporary location, which is expected.
![image](https://user-images.githubusercontent.com/15020024/219700570-b2983a89-5537-4f06-a689-3c8e083826fb.png)

Note and fill the custom text field:
![image](https://user-images.githubusercontent.com/15020024/219700833-49e76530-7915-4218-85a7-269024dd8ced.png)

Save the asset using the button on the bottom right, re open-the asset again (without saving the entry first) and note that the custom field will be empty.
![image](https://user-images.githubusercontent.com/15020024/219701312-a5e527c9-7774-4aa8-bffe-5e12be3578be.png)

### Steps to reproduce

1. Assets should be stored in S3 Bucket
2. Temporary Asset location should be set to Local
3. Open a page and add a module which uses the Asset Upload
4. Make sure assets use custom fields besides `title`
5. Upload an asset using the direct upload functionality
6. Wait for the asset to be uploaded successfully
8. **Do not save the entry**, this is a crucial step!
9. Double click on the asset and note that it is still stored in the temporary asset folder
10. Insert value into custom field
11. Save the asset, which causes the modal to close.
12. Double-Click the asset again.
13. Custom Text Field will be empty

**This behavior does not occur when the entry is saved before editing the asset.** Once the Save Event has moved the asset into the AWS bucket, everything works as expected.

### Expected behavior
Additional asset fields will be stored reliably no matter of the temporary asset folder's location

### Actual behavior
Additional asset fields are only stored reliably after the entry has been saved at least once, seemingly after the asset has been moved to its permanent destination.

Note that there are no errors on the console (so no JS issue) and the POST request when saving the asset seems to be firing correctly.

Also note that this behavior **does not occur** when the Temporary asset location is set to AWS as well.

### Craft CMS version

3.7.59

### PHP version

7.4.33

### Operating system and version

Linux 5.10.0-0.deb10.19-amd64

### Database type and version

MySQL 5.5.5

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.10-23)

### Installed plugins and versions

Amazon S3 v. 1.3.0

**Comment by brandonkelly** [comment]
I’m not able to reproduce this.

Do you have an explicit volume selected for Settings → Assets → Settings → Temp Uploads Location?

Does that volume have the same custom fields as the target volume for the Assets field?

**Comment by mnlmaier** [comment]
@brandonkelly thanks for your quick response and sorry for getting back to you with a little delay. we didn't set a specific Volume to use as the temporary asset location. This is what's set in the settings:

<img width="676" alt="image" src="https://user-images.githubusercontent.com/15020024/222662201-ab94c541-ab2f-42a9-8966-45fa51100708.png">

Is there a way to provide further information which might help you investigate?

**Comment by brandonkelly** [comment]
The curious thing to me about this is why any custom fields would be shown to begin with. Custom fields are added via the _volume’s_ field layout, so if Temp Uploads Location isn’t set to a volume, I would expect that no custom fields would be available on the assets yet.

**Comment by i-just** [comment]
In terms of reproducing this issue:
I have:
- `autosaveDrafts` set to `false`, 
- settings > assets > settings > temporary uploads location set to “in the local temp folder” 
- Matrix field with an assets field in it (as per your screenshot, though tried with a standalone Assets field, too), and that has “Sources” set to an S3 volume and “Default Asset Location” set to that S3 volume too

Whenever I upload a file via a direct upload, it gets moved from temporary uploads straight to the S3 bucket without saving the entry. Then the flow is correct, and additional layout fields get saved as expected.

Now, if in the assets field, I have “Sources” set to “All” or I have “Show unpermitted volumes” checked, if I create a new entry (without saving), click “Add an asset” > click **“Temporary uploads”** from the sources sidebar (or if you have selected that before, this choice is remembered), click “Upload files”, and then follow the steps to reproduce, I can replicate this behaviour, including additional fields being shown but not getting saved, until the entry is saved and the file is moved to the S3 bucket.

I created a PR for this.

**Comment by brandonkelly** [comment]
Just released 3.8.8 with a fix!

Worth noting that this feature (assigning a field layout to temporary assets based on the field’s default upload location) did not carry over to Craft 4. So in Craft 4, if the asset is sitting in the local temp folder, it won’t get a field layout until it has been moved into an actual volume.
