### ISSUE TITLE
[4.x]: After creating a new category, the modal content is hidden below the bottom bar

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#12708]
### Description

When you open the modal window to add a category to a category field, create a new category in the slideout. Close the modal window. When you open it again next time (like if you need to add another category), the list is hidden behind the grey bar at the bottom of the modal window, which means you can't see the last item. It doesn't happen when you first open it, only after creating a new category.

![image](https://user-images.githubusercontent.com/1250017/220321678-f3d56f65-7f77-4d94-b776-2951c8d9640d.png)

https://user-images.githubusercontent.com/1250017/220323626-4f7052e1-6e2d-4095-8611-dd62550690e2.mov

### Craft CMS version

4.3.6.1

### PHP version

8.1.13

### Operating system and version

MacOS (with mouse)

### Database type and version

MySQL 8

### Image driver and version

GD 8.1.13

### Installed plugins and versions

Admin Bar	3.2.0
Dashboard Begone	2.0.0
Feed Me	5.0.5
Guest Entries	3.0.1
Redactor	3.0.3
Retcon	2.6.0
SEOmatic	4.0.19
Sherlock	4.3.0
Super Table	3.0.7
Twigpack	4.0.0-beta.4
Typed link field	2.1.5

**Comment by i-just** [comment]
Hi, thanks for reporting. I created a PR to fix this.

**Comment by brandonkelly** [comment]
Fixed for the next release, via #12726!

**Comment by brandonkelly** [comment]
Craft 4.3.11 is out with this fix.
