### ISSUE TITLE
[4.x]: Cannot query matrix blocks by custom fields

### ISSUE THREAD

**Issue by goraxan** [craftcms/cms#12707]
### Description
I have a Matrix field with 2 blocks (called entry and image), each one with one field called element. The element field is an EntryField or an AssetField depending on the block it belongs to.

I can't make a query to get a matrix block by my custom field "element".

### Steps to reproduce

- Create a MatrixField with this configuration
![image](https://user-images.githubusercontent.com/8337784/220303588-00717bec-3082-4e85-aa32-d1525fefd9b8.png)
- Try to query by "element" like this: `MatrixBlock::find()->type('entry')->element([$elementId])->ownerId($boardId)->one();`

### Expected behavior
I should get the MatrixBlock

### Actual behavior
No matter what value I put in the "element" filter, the first MatrixBlock of the specified type and owner is returned. Looks like filters by custom fields are ignored.

### Craft CMS version

4.3.6.1

### PHP version

8.0.26

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
For Matrix queries, you must specify the [`fieldId`](https://craftcms.com/docs/4.x/matrix-blocks.html#fieldid) param in order to add custom field params:

```php
$field = Craft::$app->field->getFieldByHandle('myMatrixFieldHandle');

$block = MatrixBlock::find()
  ->fieldId($field->id)
  ->type('entry')
  ->element([$elementId])
  ->ownerId($boardId)
  ->one();
```

Alternatively, if you already have the owner element (and not just its ID), you could do this:

```php
$block = $board->myMatrixFieldHandle
  ->type('entry')
  ->element([$elementId])
  ->one();
```
