### ISSUE TITLE
[4.x]: Small UI layout glitch in element index "View" dialog, for table column options with long field names

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#12717]
### Description

Table column options for custom fields with long field names break on a separate line relative to their move handles, which looks a bit broken:

![CleanShot 2023-02-22 at 14 15 18](https://user-images.githubusercontent.com/298510/220631025-a2ae4ea6-23e6-4642-888c-9c63a252bb7a.png)

Screenshot is from MS Edge 110.0.1587.50 on MacOS 12.6.

### Steps to reproduce

1. Create a custom field with a very long name, and add it to a section
2. Pop open that section's "View" menu in its element index

### Craft CMS version

4.3.10

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release.

**Comment by brandonkelly** [comment]
4.3.11 is out with that fix. (And a similar fix has also been made to the Customize Sources modal, for 3.7.68 and 4.3.11.)
