### ISSUE TITLE
[4.4.0-beta.2]: Dropdown Fields overlap if not set to full width 

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#12728]
### Description

We have three dropdown fields set to 25% width.

They overlap now:

![image](https://user-images.githubusercontent.com/60010597/220953670-62d26f11-2ef9-415c-8916-5286952db80b.png)

EDIT:

Dropdowns do not work in Live Preview, only text input possible.

### Steps to reproduce

See above.

### Expected behavior

Do not overlap.

### Actual behavior

See image

### Craft CMS version

4.4.0-beta-2

### PHP version

8.1.13

### Operating system and version

Linux 5.15.79.1-microsoft-standard-WSL2

### Database type and version

MySQL 10.4.27

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I created a PR to address both issues.

**Comment by brandonkelly** [comment]
Fixed now for the next release, via #12734!

**Comment by brandonkelly** [comment]
4.4.0-beta.3 is out with that fix.
