### ISSUE TITLE
[4.x]: `$fs->getRootUrl()` does not check for slashes when adding folders

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#12725]
### Description

When combining the Filesystem Base URL and Subfolder there should be a check for a slash when concatenating values

![image](https://user-images.githubusercontent.com/25124/220800342-5d8e3183-7452-4625-9432-b5af436a28ef.png)

### Steps to reproduce

1. Create a new filesystem
2. Set the Base URL to be: `https://example.com`
3. Set the Subfolder to be `assets`

### Expected behavior

`$fs->getRootUrl()` should be `https://example.com/assets`

### Actual behavior

`$fs->getRootUrl()` is `https://example.comassets`

### Craft CMS version

4.4.0-beta-1

### PHP version

8.2

### Operating system and version

OSX

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks! Just released 4.4.0-beta.2 with a fix for this.
