### ISSUE TITLE
[4.x]: Image thumbnails within inactive tabs don't load when their tab is activated

### ISSUE THREAD

**Issue by knufri** [craftcms/cms#12720]
### What happened?

Description
Image thumbnails within inactive tabs don't load when their tab is activated.

Steps to reproduce
Created a Section with multiple tabs including an asset field in the second tab.
Upload an image to the asset field on the second tab.
Switch back to the first tab and reload the page.
Switch to the second tab, the image thumbnail won't be loaded.

<img width="537" alt="Bildschirm­foto 2023-02-22 um 17 27 36" src="https://user-images.githubusercontent.com/2785206/220693686-9d2e16cc-daad-473e-8a88-1fdaf6361880.png">

This bug was reported from me some time ago, see: https://github.com/craftcms/cms/issues/10918

It's a bit weird, sometimes the images load and sometimes they don't 🤔 sometimes they appear when you scroll or switch between the tabs. There are no js errors in the console.

### Craft CMS version

4.3.10

### PHP version

8.1

### Installed plugins and versions

-

**Comment by knufri** [comment]
Hello @i-just, thank you for the very fast reply 👍 looking forward to the fix.

Best Regards
Jan

**Comment by brandonkelly** [comment]
This is fixed for the next Craft 3 and 4 releases, via #12727!

**Comment by brandonkelly** [comment]
Craft 3.7.68 and 4.3.11 are out with that fix.
