### ISSUE TITLE
[4.4.0-beta.2]: moving a folder to the current folder's path causes errors

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#12738]
### Description

Moving a folder to the current path of that folder causes some problems. 
maybe fix is to not allow this action but i uploaded some videos and what is happening, depending on folder being empty or not and what user choose.

 move to current folder when folder is empty 1

https://user-images.githubusercontent.com/55586085/221170196-6a1610c8-eb30-4794-bc4f-d1e22bb1b838.mp4

------

 move to current folder when folder is empty 2

https://user-images.githubusercontent.com/55586085/221170258-060c85a0-1f4f-4766-bdb7-6cbe9eef2aad.mp4

-----

 move to current folder when folder has file inside 1

https://user-images.githubusercontent.com/55586085/221170322-522af632-ea6c-4d9c-a63b-4aac91bd93d0.mp4

-----

move to current folder when folder has file inside 2

https://user-images.githubusercontent.com/55586085/221170354-a35112f4-fd3c-40ae-b430-8cddf1dd6c12.mp4

### Craft CMS version

4.4.0-beta.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next Craft 3.8 and 4.4 releases.

**Comment by brandonkelly** [comment]
3.8.0-beta.2 and 4.4.0-beta.3 are out with that fix.
