### ISSUE TITLE
[4.x]: Screenshots made on Dutch MacOS cannot be uploaded due to invisible 'soft-hyphen' in filename

### ISSUE THREAD

**Issue by FlorisDerks** [craftcms/cms#12741]
### Description

When you make a screenshot on the Dutch language version of MacOS, you get a filename on your desktop named `Scherm­afbeelding 2023-02-20 om 14.49.57.png`. The issue however is that there is a invisible unicode character between 'Scherm' and 'afbeelding', called a 'soft hyphen' (unicode 00ad).

This used to be fine in older 4.x versions, until recently (was still working in 4.3.8.2 iirc, but broken in 4.3.10). Now when i try to upload a file that contains the `<00ad>` character the following error is returned:

```
{               
        "name": "Filesystem Error",
        "message": "Unable to check if Scherm<00ad>afbeelding-2023-01-23-om-10.42.30.png exists",
        "code": 0,
        "error": "Unable to check if Scherm<00ad>afbeelding-2023-01-23-om-10.42.30.png exists",
        "exception": "craft\\errors\\FsException",
        "file": "/Users/floris/Sites/cms/vendor/craftcms/flysystem/src/base/FlysystemFs.php",
        "line": 151,
        "previous": {
                "message": "Corrupted path detected: Scherm<00ad>afbeelding-2023-01-23-om-10.42.30.png",
                "exception": "League\\Flysystem\\CorruptedPathDetected",
                "file": "/Users/floris/Sites/cms/vendor/league/flysystem/src/CorruptedPathDetected.php",
                "line": 11
        }
}
```

### Steps to reproduce

1. Create/download a image which contains the soft-hyphen `<00ad>` in the filename
2. Try to upload the file to Craft CMS
3. Receive a JS alert() containing an error stating the uploaded file does not exist (as seen above)
4. The soft-hypen can be seen in the Network console response of request `/index.php?p=admin%2Factions%2Fassets%2Fupload&site=default`, when looking in the 'Response' tab (invisible in the 'Preview' tab)
5. Remove only the soft-hypen from the filename and try again
6. The file can now be uploaded without problem

### Expected behavior

The filename should be correctly filtered as before.

### Actual behavior

Something goes wrong which causes the file to not exist correctly directly after uploading.

### Craft CMS version

4.3.10

### PHP version

8.0

### Installed plugins and versions

- Fortrabbit Object Storage Volume v3.0.0

**Comment by i-just** [comment]
Hi, thanks for reporting. A PR to address this has been created.

**Comment by brandonkelly** [comment]
Fixed for the next release! (via #12759)

**Comment by brandonkelly** [comment]
Craft 4.3.11 is out with this fix.

**Comment by brandonkelly** [comment]
Craft 3.8.6 has been released with the same fix backported.
