### ISSUE TITLE
[4.4.0-beta.3]: a volume get indexed by 'all' option, even if that volume is not listed by EVENT_LIST_VOLUMES

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#12749]
### Description
because 'all' option is always available in volumes list in the asset index utility page,  by selecting that option, all volumes are getting indexed, even if a volume is not passed by EVENT_LIST_VOLUMES

**Comment by i-just** [comment]
Hi, thanks for reporting! I created a PR to address this.

**Comment by mmikkel** [comment]
Thanks a lot @i-just! 🙌

**Comment by brandonkelly** [comment]
4.4.0-beta.4 is out with the fix for this, via #12762.
