### ISSUE TITLE
[3.x]: Propagating global sets fails for new sites

### ISSUE THREAD

**Issue by shoored** [craftcms/cms#12748]
### Description
After adding 3 new sites, Craft's "Propagating global sets" queue jobs fail for all 3 sites.

The Job Data is as follows:
```
{
    "description": null,
    "elementType": "craft\\elements\\GlobalSet",
    "criteria": {
        "siteId": 1,
        "status": null
    },
    "siteId": XXX (new site ID's here)
}
```
The error in the Queue manager is the same for each of the 3 sites:
`Invalid owner ID: 314`

### Steps to reproduce

1. Add new sites
2. See the "Propagating global sets" queue jobs fail

### Versions
Craft 3.7.65
PHP 8.2.1
PostgreSQL 11.15

**Comment by i-just** [comment]
Hi, thanks for reaching out. I’m unable to replicate it on a clean install. If you can please send your `composer.lock`, database export (before applying project config) and `config/project` folder to support@craftcms.com, we can dig deeper into what’s happening.

**Comment by shoored** [comment]
Hello, thanks for the quick response. I was able to "fix" this by saving the global sets in the CP from the primary site. Then all global sets appeared for all new sites (and even for some existing ones). I'm guessing it's something specific for this site with some field setup. I'm good with closing this.

**Comment by brandonkelly** [comment]
Glad you got it sorted, @shoored. Let us know if something similar crops up again.
