### ISSUE TITLE
[4.x]: Image Transforms are Forcing Slow Queue Jobs

### ISSUE THREAD

**Issue by markhuot** [craftcms/cms#12750]
### Description

We inherited a project from another CMS and had to import 1MM assets in to the asset library. Everything went fine with Craft 3.7.x at the time. One note: because of the large library we never tried to re-index all assets to generate thumbs for everything during import. We let the raw image import and were letting Craft 3.7.x generate transforms on-demand as pages were loaded/needed.

In Craft 4.3 there is a call to _deferredTransformUrl in getTransformUrl located in the [ImageTransformer class](https://github.com/craftcms/cms/blob/aad45b7d4c7005a0ac4809f32e135c6eadec7062/src/imagetransforms/ImageTransformer.php#L82). That wasn't there in 3.7.x.

This is affecting us because we're now [kicking off queue jobs](https://github.com/craftcms/cms/blob/aad45b7d4c7005a0ac4809f32e135c6eadec7062/src/imagetransforms/ImageTransformer.php#L162) that are trying to generate the 500,000+ pending image transforms that have not been generated yet and that's backing up our queue as it works through that backlog. Is there any way to stop the GeneratePendingTransforms queue job? We're happy to have everything generated on demand in this case.

In 3.7.x this didn't happen, to the best of my knowledge.

One quick fix I could think of for our particular use case: is it safe to delete any`fileExists=0 and inProgress=0` asset transforms out of the `imagetransformindex` table? They'll be re-added/re-created when needed and that will cut down on what Craft thinks it needs to generate, right?

### Steps to reproduce

1. Inherit an asset library with a number of transforms that are not generated
2. Interact with the site for a while on 3.7 and the asset index gets built up with a bunch of pending image transforms
3. Upgrade to Craft 4.3.10 and now Craft wants to generate all those pending image transforms, slowing down your queue

### Expected behavior

It would be nice if there was a way to disable that queue job with a configuration option

### Actual behavior

The `GeneratePendingTransforms` queue job is hard coded and can not be skipped/stopped.

### Craft CMS version

4.3.10

### PHP version

8.2

### Operating system and version

ubuntu, latest

### Database type and version

MySQL 8

### Image driver and version

ImageMagick

**Comment by markhuot** [comment]
fwiw, I got some additional info and was able to solve a lot of this by setting `generateTransformsBeforePageLoad` to `true` in my config. That kept a lot of those queue jobs out of the queue because images were generated with the page load, not after the fact. Slightly slower page load but more consistent experience (image URLs).

The only downside is that I found [one place in the CP that still has a forced `false` on the `$immediately` param](https://github.com/craftcms/cms/blob/aad45b7d4c7005a0ac4809f32e135c6eadec7062/src/services/Assets.php#L646) which means that the pesky queue job keeps coming back. Specifically, this gets called in the following stack trace.

```
#0 /var/www/html/vendor/craftcms/cms/src/imagetransforms/ImageTransformer.php(82): craft\imagetransforms\ImageTransformer->_deferredTransformUrl()
#1 /var/www/html/vendor/craftcms/cms/src/elements/Asset.php(1592): craft\imagetransforms\ImageTransformer->getTransformUrl()
#2 /var/www/html/vendor/craftcms/cms/src/elements/Asset.php(1513): craft\elements\Asset->_url()
#3 /var/www/html/vendor/craftcms/cms/src/services/Assets.php(646): craft\elements\Asset->getUrl()
#4 /var/www/html/vendor/craftcms/cms/src/elements/User.php(1256): craft\services\Assets->getThumbUrl()
#5 /var/www/html/vendor/craftcms/cms/src/helpers/Cp.php(347): craft\elements\User->getThumbUrl()
#6 /var/www/html/vendor/craftcms/cms/src/elements/Entry.php(1524): craft\helpers\Cp::elementHtml()
#7 /var/www/html/vendor/craftcms/cms/src/base/Element.php(4308): craft\elements\Entry->tableAttributeHtml()
#8 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1607): craft\base\Element->getTableAttributeHtml()
```

**Comment by brandonkelly** [comment]
That `immediately: false` arg has been removed for the next release.

**Comment by markhuot** [comment]
Thank you! Tested locally and it worked perfectly. Will feel good to get my ugly hack out of there.

**Comment by brandonkelly** [comment]
Craft 4.3.11 is out with that change.
