### ISSUE TITLE
[4.4.0-beta.3]: Assets preview does not show and can't select assets in assets field

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#12755]
### Description

https://user-images.githubusercontent.com/25124/221716486-dea0f68a-5ceb-4fed-89e8-1930f4a18b85.mov

### Steps to reproduce

Repro:: https://leevigraham-redesigned-space-system-vrp77xx42wpgp-8050.preview.app.github.dev/admin/entries/test/418-test U: `admin` P: `project`

### Expected behavior

Can see and select assets

### Actual behavior

Can't see asets

### Craft CMS version

[4.4.0-beta.3]

### PHP version

8.2

### Operating system and version

OSX

### Database type and version

postgres

**Comment by leevigraham** [comment]
@brandonkelly  Rolling back to beta.2 fixes the issue.

**Comment by brandonkelly** [comment]
Thanks for reporting! 3.8.0-beta.3 and 4.4.0-beta.4 are out with a fix for this.
