### ISSUE TITLE
[4.x]: Content table columns for custom fields with a "MissingField" type are dropped when project config YAML changes are applied

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#12760]
### Description

Ran into this one on a recent Craft 2 -> 4 migration, and it caused a bit of data loss and backtracking:

When applying project config changes, Craft will delete the content database column for custom fields with a `type` attribute set to `craft\fields\MissingField` in the field's YAML file.

Aside from causing irreversible data loss, this also leaves things in a bit of a weird state, since the actual field is still retained in the database, but its content column is now gone.

### Steps to reproduce

1. Install a plugin that provides a custom field type with a content column (for example `craftcms/redactor`)

2. Create a (global) field using that custom field type. Confirm that the field now has a column in the `content` table.

3. Uninstall or disable the plugin.

4. Rebuild the project config YAML files (`php craft project-config/rebuild`). Confirm that the field's `type` is now set to `craft\fields\MissingField` in its YAML file.

5. Apply the project config (`php craft project-config/apply --force`). 

6. Confirm that the field's type has been changed to `craft\fields\MissingField` in the `fields` column, and that its content table column is now deleted.

### Expected behavior

Craft should retain custom fields' content table columns even if their fieldtype is currently "missing".

### Actual behavior

If a custom field has its `type` changed to `craft\fields\MissingField` in the project config YAML, applying that change will delete its content column.

### Craft CMS version

4.3.10 and 3.7.67

### PHP version

8.1.12

### Database type and version

10.9.3-MariaDB

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next Craft 3 and 4 releases, via #12761.

**Comment by brandonkelly** [comment]
Craft 3.7.68 and 4.3.11 are out with that fix.
