### ISSUE TITLE
[4.x]: Cannot select self asset even the allow self relations setting is active

### ISSUE THREAD

**Issue by aodihis** [craftcms/cms#12769]
### Description
I have asset volume that has an asset field inside it and I set to allow self relations to true. But when I click to an asset I cannot choose the same asset it self.

### Steps to reproduce

1. Create volume asset with asset field to allow select same volume with allow self relations to true.
2. Add an asset.
3. Click the asset and select the field to select same asset.

### Expected behavior
Can select same asset.

### Actual behavior
The same asset is disabled.

### Craft CMS version

4.3.10

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Fixed for the next Craft 3 and 4 releases via #12779.

**Comment by brandonkelly** [comment]
Craft 3.7.68 and 4.3.11 are out with that fix.
