### ISSUE TITLE
[4.x]: when re-saving a section via the CLI command, the date in the title entries lost their local attribute

### ISSUE THREAD

**Issue by scandella** [craftcms/cms#12780]
### Description
Re-saving a section with CLI do not save date with their local in the entries titles

### Steps to reproduce

1. Create a section with a date field, include this date in the title section.
2. The date is displayed in the current local
3. Resave the section via the CLI command ` ./craft resave/entries --section aSection`
4. The date local is lost in the entries titles

### Expected behavior
The date in the title entries should conform to the local.

### Actual behavior
When re-saving the section via the CLI command, the date in the title entries lost their local attribute.

### Craft CMS version

Craft Pro 4.3.10

### PHP version

8.1.13

### Installed plugins and versions

Calendriers 4.0.7
Control Panel CSS 2.6.0
CP Field Inspect 1.4.4
Default Dashboard 2.0.0
Eager Beaver 4.0.2
Elements Panel 2.0.0
Field Manager 3.0.5
Formulaires 4.0.17
Neo 3.7.0
Redactor 3.0.3
Super Table 3.0.7

**Comment by brandonkelly** [comment]
Thanks for reporting that! This is fixed for the next Craft 3 and 4 releases.

**Comment by brandonkelly** [comment]
Craft 3.7.68 and 4.3.11 are out with that fix.
