### ISSUE TITLE
[4.4.0-beta.4]: Subfolder actions menu missing

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#12790]
### Description

For a user with all permissions:

![image](https://user-images.githubusercontent.com/60010597/222896093-b8d9b61b-18dd-4ae5-a45b-768fa5192b43.png)

the subfolder actions menu does not appear:

![image](https://user-images.githubusercontent.com/60010597/222896166-cbc883cc-1e49-43b6-a482-3a86dac822f9.png)

### Steps to reproduce

1. Log in as a non-admin user with sufficient permissions.

### Expected behavior

Be able to perform folder actions.

### Actual behavior

The actions menu is missing.

/Mel

### Craft CMS version

4.4.0-beta.4

### PHP version

8.1.13

### Operating system and version

Linux 5.15.90.1-microsoft-standard-WSL2

### Database type and version

MySQL 10.4.27

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
4.4.0-beta.5 is out with that fix.
