### ISSUE TITLE
The option so set a Entry Field width in the Craft UI

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1279]
> Created by: Anonymous (alexander.buergin@wskomm.ch) on 2016/06/14 12:29:02 +0000
> Votes at time of UserVoice import: 1

-----------------------------------

It wood be nice to have the option to order Fields in cols. 

Like this

**Comment by brandonkelly** [comment]
Entry fields are always shown in columns as of Craft 2.5 or so.
