### ISSUE TITLE
[4.4.0-beta.4]: Empty folder reappears on 'Missing or empty folders' list

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#12791]
### What happened?

https://user-images.githubusercontent.com/55586085/222917071-922c8e41-1f38-4455-9f8f-05f1fbac16e9.mp4

### Craft CMS version

4.4.0-beta.4

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi. That’s a sneaky little one. Thanks for reporting! It’s happening because the folder is deleted from the index, but the directory is not actually removed, so the next time you index, the folder is recreated.

I created a PR that addresses this (and one more thing I found).

**Comment by brandonkelly** [comment]
Fixed for the next 4.4 release, via #12811.
