### ISSUE TITLE
[4.3.10]: sidebarTemplate() method - sidebar template is injected on the right of content instead on the left

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#12795]
### Description

When i use `$this->asCpScreen()->sidebarTemplate()` method in the controller, sidebar template is injected on the right of content instead of the left side, like when i use `{% block sidebar %}` with regular control panel templates that are not rendered using `asCpScreen`.

### Craft CMS version

4.3.10 

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I created a PR to fix this.

**Comment by brandonkelly** [comment]
This is actually working as expected. `sidebar` in the CP screen context means the right-and sidebar, whether within a slideout modal, or a full edit page (as those two sidebars should generally be consistent).

We should probably introduce new `leftSidebar` functionality though.

**Comment by piotrpog** [comment]
@brandonkelly 
Would be great if you added that. I wanted to switch my plugin control panel pages to `asCpScreen` so they work as standalone pages and also in slideouts, but right now i cannot use sidebar properly with this method.

**Comment by piotrpog** [comment]
@brandonkelly by the way - maybe there could be option for using `asCpScreen ` for pages that are not a form that can be submitted? Because unless i omitted something, every page rendered this method has its content injected into form.

**Comment by piotrpog** [comment]
@brandonkelly thanks for adding this. althought i hoped it would get to 4.4.

**Comment by brandonkelly** [comment]
It required a little internal discussion, and we didn’t have a chance to do that until post-4.4.

**Comment by brandonkelly** [comment]
Craft 4.5.0 is out with this.
