### ISSUE TITLE
[4.4.0-beta.6]: Inconsistent behavior when clicking folder thumbnails 

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#12802]
### Description

On assets element index and element selection modals:

Clicking a folder thumbnail does not behave consistently: 

* sometimes (I suspect the first three folders ?) it opens the subfolder, 
* sometimes it just selects the folder. Double clicking the folder thumbnail does nothing.
* It is possible to select folders in a selection modal and add them to an assets field (they disappear after saving)

![image](https://user-images.githubusercontent.com/60010597/223088319-123e8fb4-6580-41e6-9994-496f38b1747f.png)

### Steps to reproduce

1. Have a greater number of subfolders.
2. Click / double click the thumnail.

### Expected behavior

Single click: select subfolder. (a 'rename folder' action would be helpful here)
Double click: open subfolder
Don't be able to add folders to asset fields

### Actual behavior

See above.

### Craft CMS version

4.4.0-beta.6

### PHP version

8.1.13

### Operating system and version

Linux 5.15.90.1-microsoft-standard-WSL2

### Database type and version

MySQL 10.4.27

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by wsydney76** [comment]
@brandonkelly Thanks!

Is it intentional that double clicking a folder thumbnail does not open the subfolder? Not a big deal, but I think that is what users would expect to happen, especially when 'Display as thumbnails' is active.

**Comment by brandonkelly** [comment]
Yeah. Originally I had added support for it, but then realized it would cause problems with the new folder selector modals (shown when moving assets/folders to a new location), because within them, like all other element selector modals, double-clicking on items is a shortcut for selecting them and closing the modal.

If we let people get in the habit of double-clicking on folders within the Assets index page to navigate into them, they‘ll be more likely to accidentally select the wrong folder in folder selector modals, when they meant to navigate into it.

**Comment by wsydney76** [comment]
@brandonkelly Ah, ok, I see.

Still think it's worth fixing that double clicking a folder in an asset fields selection modal adds the folder thumbnail to the field, as shown in the image above. It does no harm as the input field is empty, but it is quite confusing.

**Comment by brandonkelly** [comment]
Doh, missed that part. That has been fixed for the official 3.8.0 and 4.4.0 releases, which are now tagged!

**Comment by wsydney76** [comment]
@brandonkelly Thanks!

Just updated our starter to 4.4.0, and, maybe because of this change, it is not possible to select a folder by clicking the checkbox on the assets index page. The checkbox also does not get a keyboard focus.

PS.
Didn't pay attention when it happened that the displayed folder names include the name of the primary site:

![image](https://user-images.githubusercontent.com/60010597/223978081-af1b5fa2-4d7e-46c9-81c1-f964786e669f.png)

Is this intentional?

**Comment by brandonkelly** [comment]
@wsydney76 Doh, nope not intentional. Just released 3.8.1 and 4.4.1 with a fix!
