### ISSUE TITLE
[4.4.0-beta.6]: Issues with assets/entries field on Windows/Chrome, unable to open slideouts/focal point preview

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#12801]
### Description

This is a stopper for now:

Cannot (reliably) open slideouts/focal point preview for elements in assets/entries fields.

* Seems to work fine in Firefox browser, but doesn't in Chrome/Edge/Brave (i.e. Chromium based browsers).
* Seems to work fine for fields with max relations=1
* Other: Clicking an image does nothing.
* Double clicking an image selects it, but does not open the slideout.
* In rare cases it works, unable to reproduce consistently, suspect there may be a timing factor, e.g. clicking two images quickly one after the other.
* There is no JS error.
* Tested with Chrome 110.0.5481.178 on Windows 10, also in incognito mode, i.e. without browser extensions.

### Steps to reproduce

1. Use a Chromium based browser (on Windows?). 
2. Have a relational field (assets/entries) with no max relations restiction

### Expected behavior

Like in 4.3. (Hello #10763!)

### Actual behavior

See above.

### Craft CMS version

4.4.0-beta.6

### PHP version

8.1.13

### Operating system and version

Linux 5.15.90.1-microsoft-standard-WSL2

### Database type and version

MySQL 10.4.27

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Just tested on Win 11 + Edge, and not able to reproduce. Are you seeing this consistently across multiple computers?

**Comment by wsydney76** [comment]
@brandonkelly Yes, all Windows 10 though.

Just created a fresh install with just one assets field, updated to 4.4-x.dev, and its reproducable for me. Works on Firefox, fails on Chrome.

**Comment by brandonkelly** [comment]
Ok, I can reproduce on Win 10 + Chrome. Win 10 + Edge is working for me though. Weird… will see if I can track it down.

**Comment by wsydney76** [comment]
@brandonkelly 

Just noticed that Chrome has updated itself to 111.0.5563.65, and we are no longer able to reproduce this consistently.

Some sporadisch fails though, but once you click somewhere outside the field it continues to work.

On Brave (Version 1.48.171 Chromium: 110.0.5481.177) and Edge (110.0.1587.63), the error is still there.

So it's probably a (not completely fixed) Chromium bug in 110.something? (and earlier?)

/Karla

**Comment by brandonkelly** [comment]
Spent way longer than I care to admit looking into this today, and finally tracked it down. 3.8.0-beta.6 and 4.4.0-beta.7 are both out with a fix now!

**Comment by wsydney76** [comment]
@brandonkelly Great, thanks! Can confirm that it works now for me!
