### ISSUE TITLE
[4.4.0-beta.6]: Typo in Plugin Store

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#12809]
### Description
When going to the plugin store through Craft there is a typo in the Craft console link

![image](https://user-images.githubusercontent.com/22771556/223139937-440b0a0b-c6bc-4510-b13a-e6fddee3a8d0.png)

### Craft CMS version

4.4.0-beta.6

**Comment by brandonkelly** [comment]
Thanks! This affects Craft 4.3 as well. Fixed for the next release via 148fd988c16d392f7ddba45b6bc365b83ee40b3f.
