### ISSUE TITLE
[3.8.0-beta.5]: Unable to search in subfolders

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#12808]
### Description
Unable to search in subfolders, the checkbox doesn't appear. Although I saw it at some point when creating the screenshot, I'm unable to find it again
![image](https://user-images.githubusercontent.com/22771556/223139436-18d1b0d5-251d-4adb-869f-824740cfb66d.png)

### Craft CMS version

3.8.0-beta.5

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next Craft 3.8 release.

**Comment by brandonkelly** [comment]
3.8.0-beta.6 is out with the fix.
