### ISSUE TITLE
[4.4.0-beta.6]: Broken UI in search

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#12807]
### Description
The UI breaks when starting searching, the icons are shifting when the "Search in subfolders" appears
![image](https://user-images.githubusercontent.com/22771556/223136166-b03cf95f-a2f9-46c5-b841-c73a13cfa752.png)

### Craft CMS version

4.4.0-beta.6

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.
