### ISSUE TITLE
[3.8.0-beta.5]: UI focus issue when browsing subfolders

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#12810]
### Description
When a subfolder is selected in this case "Duits" and you select an other subfolder "Engels", the selected folder isn't grayed out. If you are quick enough, you can still go to "Duits"
![image](https://user-images.githubusercontent.com/22771556/223141386-f945bb27-706d-419e-af30-c7a36b8a6368.png)

### Craft CMS version

3.8.0-beta.5

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next 3.8 and 4.4 releases.

**Comment by brandonkelly** [comment]
3.8.0-beta.6 and 4.4.0-beta.7 are out with that fix.
