### ISSUE TITLE
[4.x]: selectize text hidden on hover

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#12829]
### Description

<img width="1415" alt="Screenshot 2023-03-08 at 10 27 26 pm" src="https://user-images.githubusercontent.com/25124/223702119-6beafcc1-4d43-4170-8141-1b731fd02850.png">
<img width="654" alt="Screenshot 2023-03-08 at 10 25 50 pm" src="https://user-images.githubusercontent.com/25124/223702145-1d172925-35ee-4274-af92-3bc4c71e5781.png">
<img width="655" alt="Screenshot 2023-03-08 at 10 25 44 pm" src="https://user-images.githubusercontent.com/25124/223702149-d3e6bcf9-dc75-4a2c-b055-97364771d988.png">

### Steps to reproduce

1. Enter a `env` var into any selectize field

### Expected behavior

Value should be visible

### Actual behavior

Value is not visible

### Possible solution

Change `.light` class to `opacity: .75` so it works on all backgrounds.

<img width="665" alt="image" src="https://user-images.githubusercontent.com/25124/223702633-ddb93f34-4d85-49a0-b197-441120816189.png">

### Craft CMS version

4.4.0

### PHP version

8.2

**Comment by i-just** [comment]
Thanks for reporting!

**Comment by brandonkelly** [comment]
Fixed in the official 4.4.0 release, via #12831 🎉

**Comment by leevigraham** [comment]
@i-just Thanks for sneaking this into the 4.4 release :)
