### ISSUE TITLE
[4.4]: All singles hidden from non-admin user

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#12838]
### Description
All single sections are hidden when logged-in as a non admin user that has permissions for those singles.

**Admin view of sinlges:**

![singles](https://user-images.githubusercontent.com/19857599/223966799-834ebfc2-0267-4b48-aab5-8625f5762b56.png)

**Non-admin user permissions for "contact" single (the same for all other singles):**

![permissions](https://user-images.githubusercontent.com/19857599/223967142-5b1b5d47-0b54-4783-aa58-16d58b2491fa.png)

**Non-admin user view of singles:**

![singles_non_admin](https://user-images.githubusercontent.com/19857599/223967004-a51e89ab-5b22-47a7-a71b-a636e6f8d175.png)

### Steps to reproduce

1. Create some singe sections
2. Create a non-admin user and either assing them to a group with full permissions for the singles, or give same permissions to the user directly.
3. Go to the entries index and select the "singles" source

### Expected behavior
The singles should be visible to the user

### Actual behavior
The "singles" source appears empty

Temporary workaround: Create a custom source that shows the singles. The user then can see them.

### Craft CMS version

Craft Pro 4.4.0

### PHP version

8.2.3

### Operating system and version

Linux 4.19.128-microsoft-standard

### Database type and version

MySQL 8.0.31

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- Dashboard Begone 2.0.0
- Field Manager 3.0.5
- Quick Field 2.0.3
- Redactor 3.0.3

**Comment by i-just** [comment]
Thanks for reporting. I created a PR for this.

**Comment by DenyEs** [comment]
> Thanks for reporting. I created a PR for this.

Have you got any idea as to where we can expect this to be merged and released? Thank you

**Comment by twitcher07** [comment]
I'm experiencing this issue after updating a site to Craft 4.4.0.

Here is the single entries for an admin:
![image](https://user-images.githubusercontent.com/8517321/224080391-5930377f-12c2-4da2-8c80-09a17cb0f513.png)

And then here is the same single entries logged in as a user that should have permissions for the same single entries:
![image](https://user-images.githubusercontent.com/8517321/224080631-61a3ed0f-e1ea-476b-a636-27bc55de7872.png)

The permissions for the user group that the user is assigned to has these permissions:
![image](https://user-images.githubusercontent.com/8517321/224081030-f3f46361-cb94-46a3-ab4c-8797b1882cbf.png)

**Comment by brandonkelly** [comment]
Thanks all! Craft 4.4.1 is out with a fix for this, via #12841.
