### ISSUE TITLE
[4.3.1]: Adding entry from slide out returns unknown server error, saves as draft

### ISSUE THREAD

**Issue by jannisborgers** [craftcms/cms#12830]
### Description
Our client is using an entries field inside of a matrix block and wants to create new entries „inline“. When choosing „Save“ in the slide out, a server error popup is displayed in the CP UI. 

* Unfortunately, no errors are logged so I have no idea what causes the error (`web.log` shows no new errors)
* The error only occurs on the production server which runs Apache. On my local nginx environment, the entry saves and is related correctly in this configuration.

### Steps to reproduce

1. Add section A
2. Add section B with a entries field to relate to section A entries inside a matrix field
3. Open section B entry, add a matrix block, choose relate button for Section A
4. Choose to create new entry
5. Add info for new entry in Section A
6. Choose „Save“ in slide out

### Expected behavior

Entry in section A is saved and related to the entries field inside section B entry matrix block

### Actual behavior

Checkmark at the top right of the slide out shows that changes were saved. When choosing „Save“, an error `„A server error occurred.“` is displayed as a popup. Dismissing the slide-out and going to section A, the entry was indeed saved as a draft.

### Craft CMS version

Craft Pro 4.3.1

### PHP version

8.1.14

### Operating system and version

Linux 4.18.0-425.13.1.el8_7.x86_64

### Database type and version

MySQL 10.4.28

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.12-72)

### Installed plugins and versions

- Contact Form 3.0.0
- Contact Form Extensions 4.2.1
- Contact Form Honeypot 2.0.0
- Dumper 3.0.1
- Element API 3.0.1.1
- HOMM XML Sitemap 1.0.1
- Redactor 3.0.2
- Vite 4.0.3

**Comment by jannisborgers** [comment]
I just realized that the drafts that Craft saves do not have a slug.

**Comment by brandonkelly** [comment]
I’m not able to reproduce that error locally (following the same steps), and entries created within Matrix fields are getting a slug. So it’s likely due to a plugin or module that is interfering with the save somehow.

Could you please send a database backup, your Composer files, and any custom plugins/modules your site has, over to support@craftcms.com? We can try to look into it from there.

**Comment by jannisborgers** [comment]
I’m happy to report that this was fixed with help from the excellent CraftCMS support (thank you very much, Tommy!)

It turns out we had an old redirect rule in `.htaccess` left over from the inital Craft 2 installation that forced trailing slashes on a server level and clashed with the CP request. I replaced the redirect with `addTrailingSlashesToUrls` in the config, which makes the redirect unnecessary for front end links.
