### ISSUE TITLE
[4.x]: Undefined column: 7 ERROR: column "licenseKeyStatus" does not exist

### ISSUE THREAD

**Issue by jlcharette** [craftcms/cms#12836]
### Description

I am trying to upgrade to Craft 4 from a fresh Craft 3 installation.

I am getting the following error at the last step `php craft migrate/all`.

![image](https://user-images.githubusercontent.com/44408591/223826959-522a5620-bf2a-4ec4-be2f-b2ba3ec125dd.png)

### Steps to reproduce

1. Install CraftCMS following the documentation.
2. Upgrade from Craft 3 to 4 following the documentation.
3. The database migration crash with the error in the screenshot above.

### Expected behavior

The database migrations work.

### Actual behavior

The databse migrations don't work.

### Craft CMS version

Craft Solo 3.8.0

### PHP version

8.1.2

### Operating system and version

Linux 5.15.90.1-microsoft-standard-WSL2

### Database type and version

PostgreSQL 15.2

### Image driver and version

Imagick 3.6.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

Fresh installation. No plugins.

**Comment by brandonkelly** [comment]
I’m not able to reproduce this, but I suspect it’s because you were updating to Craft 4.3.x. We _just_ released both 3.8.0 and 4.4.0 today, and if you’re coming from 3.8, you will need to update straight to 4.4.

**Comment by jlcharette** [comment]
I was able to make it work by updating straight to 4.4... thank you!
