### ISSUE TITLE
[4.4]: Customise Sources Modal loses headings and litters project config

### ISSUE THREAD

**Issue by MattWilcox** [craftcms/cms#12840]
### Description

If you make a new Heading in the Customise Sources modal, but there are no Sources placed beneath it, you click "save" and nothing seems to have happened.

Going back into the Customise Sources reveals that the heading does not exist there.

Looking into the Project config, there are details in there for it.

1. You can end up with a lot of headings in proj conf that are totally inaccessible in the CMS
2. Explicitly creating a heading and having it not save _feels_ like a bug
3. The same "heading tossed to the ether" happens if you ever move a heading to the bottom ... which is the default placement!

While I understand the reasoning that headings without content beneath them should not be visible in the main UI; they _should_ still appear in the Customise Sources modal. They do not.

Saving this seems to result in nothing happening...
<img width="877" alt="Screenshot 2023-03-09 at 10 58 30" src="https://user-images.githubusercontent.com/814039/224009255-942edd36-00a0-4d76-996b-0dd8741cfa82.png">

This is the result (though I understand why, it's "weird" behaviour)
<img width="223" alt="Screenshot 2023-03-09 at 11 12 09" src="https://user-images.githubusercontent.com/814039/224009328-98c7954a-00d4-4691-adc9-2cf36360ae00.png">

But the heading _should be here_ when you go to edit sources again, and it isn't.
<img width="225" alt="Screenshot 2023-03-09 at 11 12 32" src="https://user-images.githubusercontent.com/814039/224009481-3e84b371-db9c-453e-b5e9-254a85b2938a.png">

### Craft CMS version

4.4.0

### PHP version

8.1

**Comment by i-just** [comment]
Hi, thanks for reporting. I created a PR for this.

**Comment by brandonkelly** [comment]
Craft 4.4.1 is out now with the fix!
