### ISSUE TITLE
[4.4]: Can't delete structure section created via entrify/categories

### ISSUE THREAD

**Issue by RyanRoberts** [craftcms/cms#12842]
### Description

Unable to delete the (empty) structure section created by `ddev craft entrify/categories news`.

See video: https://media.yep.digital/BxzV4kZy Also happens for the section above that one (News Categories).

### Steps to reproduce

1. Run `ddev craft entrify/categories news`
2. Enter name and handle and yes to versioning
3. Enter email of the author that the entries should have… *but* it borked here and gave me `Exception 'yii\base\InvalidArgumentException' with message 'Malformed UTF-8 characters, possibly incorrectly encoded'` and `Failed to run craft entrify/categories news: exit status 1` - should have typed the email, my bad.

The new category structure *is* created though no entries exist within it.

### Expected behavior

Able to delete the section.

### Actual behavior

Can't delete it.

### Craft CMS version

4.4

### PHP version

8.2.3

### Operating system and version

macOS 13.2.1

### Database type and version

MySQL 5.7.41

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- AsyncQueue 3.1.0
- CP Field Inspect 	1.4.4
- DigitalOcean Spaces Filesystem 	2.0.0
- Formie 	2.0.24
- Hyper 	1.1.1
- Knock Knock 	2.0.8
- Logs 	4.0.0
- MatrixMate 	2.1.2
- Minify 	4.0.0-beta.2
- Redactor 	3.0.3
- Redactor Tweaks 	3.0.0
- Relax 	2.0.1
- SEOMate 	2.1.1
- Super Table 	3.0.7
- Typed link field 	2.1.5
- UI Element fields 	2.0.2

**Comment by i-just** [comment]
Hi, thanks for reaching out. I need help replicating this. Would you please be able to send your `composer.lock` and database backup (after entrification) to support@craftcms.com so that we can dig deeper?

**Comment by i-just** [comment]
Actually, you can ignore my last comment. I’ve managed to replicate this by not finishing the entrification process.

**Comment by RyanRoberts** [comment]
> Actually, you can ignore my last comment. I’ve managed to replicate this by not finishing the entrification process.

Cool ok, happy to send anything over if you still need it though.

**Comment by RyanRoberts** [comment]
@i-just Thanks, that worked 👍

**Comment by brandonkelly** [comment]
Craft 4.4.1 is out now with the fix! Thanks again.
