### ISSUE TITLE
[4.4.0]: search field in entry modal loses focus after search results are shown

### ISSUE THREAD

**Issue by arifje** [craftcms/cms#12846]
### What happened?

When searching for entries results are shown after a keystroke, but focus is lost too. As a result you have to click on the input field again to change the keyword. If you're typing too slow, this gets really annoying ;-p

Screencast: https://streamable.com/9y8a20

### Craft CMS version

4.4.0

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 3.8.1 and 4.4.1 are out with a fix.
