### ISSUE TITLE
[3.x]: Retrieving Globals from a Custom Field `init()` creates endless recursion

### ISSUE THREAD

**Issue by sobkulir** [craftcms/cms#12847]
### Description
I'm trying to populate a Custom Field with values from the Globals. I'm querying the Globals in the Custom Field's init() as below:
```php
class SphColorField extends Dropdown
{
    public function init()
    {
        parent::init();

        // Creates endless loop.
        $globals = Craft::$app->globals->getSetByHandle('globalTest');
        // ....
    }

    public static function displayName(): string
    {
        return 'SphColorField';
    }
}

class CustomFieldsModule extends Module {
  public function init()
  {
      parent::init();
      Craft::setAlias('@modules', __DIR__);

      Event::on(
          Fields::class,
          Fields::EVENT_REGISTER_FIELD_TYPES,
          function (RegisterComponentTypesEvent $event) {
              $event->types[] = SphColorField::class;
          }
      );
  }
}
```

Here is the stack trace: https://pastebin.com/QNCqk4KZ

### Steps to reproduce
I created a minimal project that shows the bug: https://github.com/sobkulir/craftcms-bugreport

1. Try to query a GlobalSet from Custom Field's `init()` method.

### Expected behavior
Retrieve the data from the Globals.

### Actual behavior
Endless recursion.

### Craft CMS version

3.8.0

### PHP version

7.4.33

### Database type and version

mysql-8

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Fetching globals creates an element query. Element queries need to fetch all custom fields to give them a chance to modify the query.

So it would make sense that a custom field that triggers an element query from `init()` would cause an infinite recursion bug.

Instead, you should hold off on fetching the globals until a point where you know the application has been fully initialized. The easiest way to do that would be to hold off on fetching that info until it’s actually needed, from `settingsHtml()`, `inputHtml()`, etc.

Otherwise, you could register an event handler from `init()` that loads the globals on application init:

```php
if (Craft::$app->isInitialized) {
    $this->loadGlobals();
} else {
    $this->on(WebApplication::EVENT_INIT, function() {
        $this->loadGlobals();
    });
}
```

I know you said this is for a Craft 3 project, but worth noting that Craft 4.3.5 added an `onInit()` method that would make that code even simpler:

```php
Craft::$app->onInit(function() {
    $this->loadGlobals();
});
```

**Comment by sobkulir** [comment]
Thanks! I'm very new to CraftCMS as I've recently become a maintainer of a project. What I'm trying to achieve is to have my custom field (`colorField`) populated from the Table (`entries`) in the same GlobalsSet.
![image](https://user-images.githubusercontent.com/14258647/224306362-95d36863-d7bf-4edd-bf48-5d96cf88a8b8.png)

I had a go at your suggestions and placing the query into `inputHtml()` did work, but then the field could not be saved because it didn't pass the validation. So I tried placing it into `init()` as you suggested:
```php
class SphColorField extends Dropdown
{    
    private static $globalsState = "NotFetched";
    private static $globalTest = null;

    private function loadGlobals() {
        switch (SphColorField::$globalsState) {
            case "NotFetched":
                SphColorField::$globalsState = "Fetching";
                SphColorField::$globalTest = Craft::$app->globals->getSetByHandle('globalTest');
                break;
            case "Fetching":
                SphColorField::$globalsState = "Fetched";
                return;
            case "Fetched":
                break;
        }

        foreach (SphColorField::$globalTest->entries as $entry) {
            $this->options[] = [
                'label'=> $entry['title'],
                'value' => $entry['title']
            ];
        }
    }

    public function init()
    {
        if (Craft::$app->isInitialized) {
            $this->loadGlobals();
        } else {
            $this->on(craft\web\Application::EVENT_INIT, function() {
                $this->loadGlobals();
            });
        }
        parent::init();
    }
}
```

Note that in order to prevent the infinite recursion I had to add some state handling, which is quite hacky. The above code doesn't work, `SphColorField::$globalTest->entries ` is undefined, I'm not sure why. Note that when I move the `colorField` to a new Global Set, the code above works, i.e., `SphColorField::$globalTest->entries ` contains the table entries as expected.

Nevertheless, it still feels hacky, because this way the `$this->options` are not guaranteed to be filled before the `parent::init()` call.

Maybe the best option would be to fetch the data in the table directly from the database using a custom `Query`, but in my actual use case, it's a table within a table that I need to fetch and I didn't look into the schema that CraftCMS uses. In case you find this the best option, could you please point me to a resource to save some time?

Thank you for having a look and please let me know if you have any ideas. I feel like someone had to face this before.

**Comment by brandonkelly** [comment]
I think this would be a lot less hacky if you don’t extend `Dropdown`, since that wasn’t written expecting the options to be dynamically fetched.

Here’s how I would go about a field type like that:

```php
use craft\base\ElementInterface;
use craft\base\Field;
use craft\helpers\Cp;

class SphColorField extends Field
{
    /**
     * @var array
     */
    private $options;

    protected function inputHtml($value, ElementInterface $element = null): string
    {
        return Cp::selectFieldHtml([
            'id' => $this->getInputId(),
            'describedBy' => $this->describedBy,
            'name' => $this->handle,
            'value' => $value,
            'options' => $this->options(),
        ]);
    }

    private function options(): array
    {
        if (!isset($this->options)) {
            $this->options = [];
            $global = Craft::$app->globals->getSetByHandle('globalTest');
            if ($global) {
                foreach ($global->entries->all() as $entry) {
                    $this->options[] = [
                        'label' => $entry['title'],
                        'value' => $entry['id']
                    ];
                }
            }
        }

        return $this->options;
    }
}
```

Note I’d have the option values be the related entry IDs rather than their titles, in case the titles end up changing. You can fetch the actual entries on the front end based on the selected ID:

```twig
{% if entry.mySphColorField %}
  {% set sphColorEntry = craft.entries().id(entry.mySphColorField).one() %}
  {% if sphColorEntry %}
    {{ sphColorEntry.title }}
  {% endif %}
{% endif %}

**Comment by sobkulir** [comment]
Thank you for writing all the code up, I highly appreciate it and everything works as expected now!

One small unrelated thing is that I wanted Checkboxes instead of Dropdown so I tried:
```php
protected function inputHtml($value, ElementInterface $element = null): string
{
    return Cp::checkboxSelectFieldHtml([
        'id' => $this->getInputId(),
        'describedBy' => $this->describedBy,
        'name' => $this->handle,
        'values' => $value,
        'options' => $this->options(),
    ]);
}
```

However, the field becomes required with this option, i.e., at least one option needs to be selected. This makes sense for its sole use case in `Url` field, but it would be nice to have it be a part of the config maybe, `required` option or `allowEmpty`. I ended up using:
```php
protected function inputHtml($value, ElementInterface $element = null): string
{
    $config = [
        'id' => $this->getInputId(),
        'describedBy' => $this->describedBy,
        'name' => $this->handle,
        'values' => $value,
        'options' => $this->options(),
    ];
    return Cp::fieldHtml('template:_includes/forms/checkboxGroup', $config);
}
```
