### ISSUE TITLE
[4.4]: Queue batches error and duplicates 

### ISSUE THREAD

**Issue by Mathias-Syversen** [craftcms/cms#12848]
### Description
This might not be noticeable when resaving or updating small amounts of entries, but with large amounts, the new batch system seems to make a large (infinite?) amount of duplicate jobs. 

### Steps to reproduce

1. Trigger resave of a large amount of entries.
2. Craft divides this up in xx amount of batches.

### Expected behavior
459 batches creates 459 queue jobs, resaving the entries.

### Actual behavior
Each "batch" is replicated an uncountable amount of times (uncountable because it just keeps spawning jobs, i can clear the entire queue table and it still continues spawning jobs for the resave).

![Screenshot 2023-03-09 at 15 58 19](https://user-images.githubusercontent.com/53942798/224067815-f077264a-0d82-4e61-9ab3-6ae15c6afa8f.png)

I've been stuck on 90 out of 459 for the last hour, watching each batch save the same 100 entries, triggering 100 index queue jobs, and 100 blitz refresh jobs. So far the resave has been going for 7 hours, total of 250 000+ jobs has spawned from resaving these ~50 000 entries. And we are no where close to finished.

Trying to resave a smaller section with the console command gives me a lot of this error:
``error: Calling unknown method: craft\console\Request::getSegment() in "__string_template__xxxx" at line 2``

### Craft CMS version

4.4

### PHP version

8.1

### Installed plugins and versions

- Blitz 4.4.2

**Comment by Mathias-Syversen** [comment]
I ended up stopping apache and truncating the queue table to be able to stop this.

**Comment by brandonkelly** [comment]
Something’s not right here. Additional batches shouldn’t be getting added until the very end of the current batch.

Do you have a custom `queue` config in `config/app.php`? Can you share it?

**Comment by clebuchegger** [comment]
+1 first time there are so many problems... was 4.4 tested?

**Comment by brandonkelly** [comment]
There was a two-week public beta, and no one reported any queue issues. Same question to you @clebuchegger – do you have a custom `queue` config?

**Comment by brandonkelly** [comment]
We’re planning on releasing 4.4.2 tomorrow, and it would be great if we could get this resolved before then. @Mathias-Syversen @clebuchegger is there any additional detail you can add?

@Mathias-Syversen From your screenshot, it looks like you somehow had the same job being executed multiple times simultaneously. Do you have multiple queue runners that could be overlapping on job executions?

**Comment by Mathias-Syversen** [comment]
No custom queue here.
I have not run into this again, the commit i pulled updated craft to 4.4 and triggered resave (some other changes to fields) at the same time, maybe that had something to do with it?

**Comment by brandonkelly** [comment]
@Mathias-Syversen Do you have the Async Queue plugin installed? And how is your queue getting executed? (Do you just leave `runQueueAutomatically` enabled, and let it run during control panel requests? Or do you have a daemon/cron job, etc.?)

You could trigger that resave queue job by running the following command:

```sh
php craft resave/entries --section=mySectionHandle --queue
```

(Replace `mySectionHandle` with your actual section handle.)

**Comment by Mathias-Syversen** [comment]
I have no async plugin, out of the box craft queue, no config changes or custom stuff.
I'm running resave again now, I'l update you later on how it goes.

**Comment by Mathias-Syversen** [comment]
My local machine is at batch 150 out of 390 atm, everything seems to work smoothly.
It also dont accumulate jobs, but spawns 100 ish "refresh cache jobs" per batch, they get executed before next batch is started, keeping the queue at around 100-150 at any time.

I dont know it it was the queue being triggered by the same deploy that installed 4.4, but I can not seem to replicate this locally anymore.

**Comment by brandonkelly** [comment]
> but spawns 100 ish "refresh cache jobs" per batch

Hm, that must be coming from a plugin/module; Craft doesn’t have any jobs in core related to cache clearing.

Glad it’s working smoothly now though! I’ll go ahead and close this for now, but we’ll keep an eye out for it.
