### ISSUE TITLE
[4.x]: Null dropdown fields no longer show default value as selected in edit pages

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#12844]
### Description

Dropdown fields with a default option no longer show that default option as selected when no option is selected, in element edit pages.

![CleanShot 2023-03-09 at 14 53 19](https://user-images.githubusercontent.com/298510/224046336-9c1b8eba-0ab6-47c4-9d53-aa361d05f9f3.png)

![CleanShot 2023-03-09 at 14 52 52](https://user-images.githubusercontent.com/298510/224046211-1461f301-48b6-4839-85b7-3a44721bc45e.png)

### Steps to reproduce

1. Create a dropdown field, give it a default option and add the field to an entry
2. Create a new entry; observe that the field doesn't display its default option as selected

### Expected behavior

Dropdown fields with a default option should always display that default as selected when no option is selected.

### Actual behavior

Dropdown fields don't display their default option as selected when the field is empty.

### Craft CMS version

4.4.0

### Database type and version

10.9.3-MariaDB

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
@mmikkel Working as expected for you now?

**Comment by mmikkel** [comment]
@brandonkelly Yeah, I jumped the gun a little bit on this one. Sorry for the noise!
