### ISSUE TITLE
[4.4]: Image thumbnails within slideouts and within inactive tabs don't load when their tab is activated

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#12859]
### Description
Basically the same as https://github.com/craftcms/cms/issues/12720 BUT for slideouts

### Steps to reproduce

1.

### Craft CMS version

4.4

### Installed plugins and versions

-

**Comment by i-just** [comment]
Thanks for reporting! I created a PR for it.

**Comment by brandonkelly** [comment]
Fixed for the next release via #12863!

**Comment by brandonkelly** [comment]
4.4.2 is out with that fix.
