### ISSUE TITLE
[4.4]: Default site name appended to subfolder names in asset index

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#12852]
### Description

After the 4.4 update all subfolders in a volume have the site name appended when viewed in the asset index, like this:

`subolder - site name ` 

I have this replicated in multiple installs.

### Steps to reproduce

1. Have a volume with subfolders
2. Update to 4.4
3. Go to the asset index

### Expected behavior
See the subfolder names as they where before the update

### Actual behavior
The subfolders' name have the default site name appended

### Craft CMS version

4.4

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 4.4.1 is out now with a fix.
