### ISSUE TITLE
[4.4]: Non admin cannot go into subfolder to select an asset

### ISSUE THREAD

**Issue by loqus** [craftcms/cms#12851]
### Description
A non admin cannot go into subfolders to select an asset.
The modal opens up fine and you can see the structure to the left and the folders in the center part, but those folders are not clickable. User has full rights on the folder.

User gets JS errors:
AssetIndex.js:585: Uncaught (in promise) TypeError: Cannot read properties of null (reading 'on')
    at s.constructor._onUpdateElements (AssetIndex.js:585:31)
    at s.constructor.onUpdateElements (AssetIndex.js:570:12)
    at s.constructor.e [as onUpdateElements] (Base.js:76:36)
    at s.constructor._updateView (BaseElementIndex.js:2776:12)
    at BaseElementIndex.js:1329:18

BaseElementIndexView.js:173 Uncaught This view is not selectable.

If I change the user permissions to admin it works.

### Steps to reproduce

1. Update to 4.4.0

### Expected behavior

User can click into the subfolder to select an asset.

### Actual behavior

Js errors, no behaviour on screen in the modal

### Craft CMS version

Craft CMS 4.4.0 Pro

### PHP version

8.0.25

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just released Craft 3.8.1 and 4.4.1 with a fix.
