### ISSUE TITLE
[4.1.1]: Placeholder and Value shown at once in Filesystem Input Fields (on Chrome Dev 113.0.5638.0)

### ISSUE THREAD

**Issue by maxstrebel** [craftcms/cms#12860]
### Description

I just was upgraded to 4.1.1 and when I open up a filesystem, the placeholder and value are both shown.

### Steps to reproduce

1. Create a new filesystem and add configuration
2. Revisit the configuration
3. Placeholder and Value are shown twice

_I did not test a new install yet. I was updated by installing a plugin via the backend. I first got an error and then was redirected to the migration page (I was on 4.3.10 and installed navigation plugin)._

### Expected behavior

You just see the value of the field when it is set.

### Actual behavior

- Placeholder and Value are shown in Input Fields (Base Path / Base Url)
- When you click in the field and out, the placeholder is gone

### Screenshot

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/910594/224287864-0606ac65-e3c9-47a1-a776-e3ac2e6135ab.png">

### Craft CMS version

4.1.1

### PHP version

8.0

### Operating system and version

Chrome, Ventura 13.2.1

### Installed plugins and versions

- Asset Rev | 7.0.0
- Formie | 2.0.24
- Imager X | 4.1.11

**Comment by brandonkelly** [comment]
That’s got to be a browser bug. We’re just using the standard `placeholder` input attribute – nothing fancy. The browser is only supposed to show that when there’s no input value.

(And I’m unable to reproduce in Firefox or Edge on Ventura.)

**Comment by maxstrebel** [comment]
Hey Brandon, you're right. Today worked in contentful – and they also have an input field where this happens. Sorry for that. I did not see it in any other form, yet. It is not only placeholder & input. But I also cannot see what might cause it to happen yet.

So just FYI, I'm on Chrome Dev – Version 113.0.5638.0 (Official Build) dev (arm64).

**Comment by brandonkelly** [comment]
Just tested on Chrome Dev 112 (112.0.5582.0) / Ventura via BrowserStack, and can’t reproduce there either. Maybe they’ve fixed it?

**Comment by maxstrebel** [comment]
Yes. This is a Chrome issue. Closing it. Sorry Brandon.
