### ISSUE TITLE
[4.x]: 

### ISSUE THREAD

**Issue by arentsen** [craftcms/cms#12867]
### Description
Someone in the team of my client moved assets from one folder to another. The first folder was automatically created when uploading assets (by using {owner.slug} in the , but with a spelling mistake. The new folder did not have the spelling mistake, so they wanted the assets in the wrong folder be moved to the new one. This all works fine, but when using a pick Asset field, these old items are greyed out and they cannot be picked. It seems Craft sees that these images were not originally in that folder, but there is nowhere to change that. How to update these images so they can be picked? I have admin rights, so I don't think it can be a user rights issue. Thanks
 
<img width="1452" alt="Screenshot 2023-03-09 at 17 30 49" src="https://user-images.githubusercontent.com/7302698/224437466-c95f9c65-98b0-470a-a224-ff5512b7bb62.png">
<img width="1112" alt="Screenshot 2023-03-09 at 22 44 19" src="https://user-images.githubusercontent.com/7302698/224437683-9fb8b2ad-ec99-45fb-a3bd-6e86ac6e483d.png">

I just saw the Craft 4.4.1 update and was hoping the asset fixes would fix this, but unfortunately.

### Craft CMS version

4.4

### PHP version

8.0.1

### Operating system and version

MacOS Montery 12.6.3

### Installed plugins and versions

Any idea?

**Comment by brandonkelly** [comment]
Assets will only be grayed out in the selector modal if they are already selected by the Assets field.

**Comment by arentsen** [comment]
Thanks, how could we miss that....
