### ISSUE TITLE
[4.4.1]: Rebuilding project config removes transform upscale attributes

### ISSUE THREAD

**Issue by domstubbs** [craftcms/cms#12879]
### Description

When I updated from 4.3.X to 4.4.1 I noticed `upscale: false` values were added to my project config files, but those values are being removed when I run subsequent rebuilds. If I try to apply the rebuilt config without the `upscale` values I get an SQL error.

### Steps to reproduce

1. Have a working env with `upscale: true|false` values inside `imageTransforms` YAML files
2. Run `craft project-config/rebuild`
3. Upscale attributes are removed
4. Bonus points: run `craft project-config/apply --force`

### Expected behavior

Rebuilding the config should retain upscale values and applying the config should work without issue/error.

### Actual behavior

Values are lost and attempts to apply the now-incomplete config generate an SQL error:

````
- updating imageTransforms.9f574de2-546e-451a-bd02-c9ae9bcad72e ... 
error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'upscale' cannot be null
The SQL being executed was: UPDATE `craft_imagetransforms` SET `upscale`=NULL, `parameterChangeTime`='2023-03-13 16:42:19', `dateUpdated`='2023-03-13 16:42:19' WHERE `id`=7
````

### Craft CMS version

4.4.1

### PHP version

8.1

### Database type and version

MySQL 8.0

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
4.4.2 is out with that fix.

**Comment by domstubbs** [comment]
Great, thanks Brandon.
