### ISSUE TITLE
[4.x]: Error clearing cache Control panel resources: The dir argument must be a directory

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#12873]
### Description
When running `./craft clear-caches/all`, I get this error:
```
Clearing cache: Asset caches
Clearing cache: Asset indexing data
Clearing cache: Asset transform index
Clearing cache: Compiled classes
Clearing cache: Compiled templates
Clearing cache: Control panel resources
Error clearing cache Control panel resources: The dir argument must be a directory: https://website.local/cpresources
```

While I didn't get this error prior the recent Craft updates.

Adding this (where `ROOT_URL=https://website.local`) does not fix the error:
```
->aliases([
	'@webroot' => App::env('ROOT_URL')
])
->resourceBasePath('@webroot/cpresources')
```

### Steps to reproduce

1. Run `./craft clear-caches/all`

### Craft CMS version

4.4.1

### PHP version

8.1.0

### Installed plugins and versions

-

**Comment by romainpoirier** [comment]
Finally found out the error on my behalf:
```
->aliases([
	'@webroot' => dirname(__DIR__)
])
->resourceBasePath('@webroot/htdocs/cpresources')
```

**Comment by i-just** [comment]
Glad to hear you got it sorted :) 
More info on pre-defined aliases can be found here: https://craftcms.com/docs/4.x/config/#aliases

**Comment by romainpoirier** [comment]
Thank you. However, prior to this error and edit, my Imager X were correctly saved in `/htdocs/imager` and they are now saved at the root of the project, so in the wrong folder.

I'm using this plugin since a long time, and was also not using the `@webroot` alias without any incidence until the recent Craft update.

Do you know why this breaking change appears just recently and how to fix the path for the plugins?

**Comment by i-just** [comment]
Based on the information you provided, it sounds to be down to how you’ve set up your `@webroot`. It should contain the path to the folder containing the `index.php` file, and `dirname(__DIR__)` is probably not it. If you set your `@webroot` to the path where the `index.php` file lives, it should start working as expected.

For example, if your `index.php` file lives in `/var/www/html/htdocs`, then you need to set your `@webroot` to `/var/www/html/htdocs`.

**Comment by romainpoirier** [comment]
Thank you very much, I was able to fix it using this:
`'@webroot' => dirname(__DIR__) . '/htdocs'`
Where `/htdocs` was missing from the path.
