### ISSUE TITLE
[4.4]: Optimizing image tasks throws error: "fclose(): supplied resource is not a valid stream resource"

### ISSUE THREAD

**Issue by RobinWithouck** [craftcms/cms#12878]
### What happened?

The Optimizing image tasks (from the ImageOptimize plugin) throws an error: "fclose(): supplied resource is not a valid stream resource".
Our file system is of type "Google Cloud Storage".
We think it started after the update to Craft 4.4. We changed the filesystem to local to test and this works.

We allready filled an bug report on the [ImageOptimize plugin](https://github.com/nystudio107/craft-imageoptimize/issues/371).

### Craft CMS version

4.4.1

### PHP version

8.1

### Installed plugins and versions

- ImageOptimize: 4.0.4
- Google Cloud Storage: 2.0.0

**Comment by tomfischerNL** [comment]
Same issue here. Also with Google Cloud Storage. When updating from 4.3.11 to 4.4.0 or 4.4.1/4.4.2, this occurs.

**Comment by i-just** [comment]
Thanks both. Just wanted to say that we are aware of this and are working on a solution. I'll update again once I have more info.

**Comment by i-just** [comment]
Thanks for your patience. A PR to fix this has been submitted.

**Comment by brandonkelly** [comment]
4.4.3 is out now with the fix for this!
