### ISSUE TITLE
[4.x]: Getting unknown property: craft\fields\Dropdown::optgroups since migrating from Craft 3

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#12888]
### Description
After upgrading from Craft `3.7.45.2` to `^4.0.0` I now get this error:
`Getting unknown property: craft\fields\Dropdown::optgroups`

If I dump my `field.optgroups` variable, I can see that the data are available:
<img width="354" alt="Capture d’écran 2023-03-14 à 17 12 17" src="https://user-images.githubusercontent.com/4634192/225071331-a9eb04eb-8552-4c3d-af18-e07e72bc8d8d.png">

However, this is not available from Twig, like if it's only private.

I tried to add this before the query:
`field.addSelect(['optgroups'])`
But this is not allowed.

How to make this data available from Twig template, like it was in Craft 3?
I didn't find out remarks about that in the Craft migration documentation.

### Steps to reproduce

1. Upgrade from Craft `3.7.45.2` to `^4.0.0`
2. Load field using `{% set field = craft.app.fields.getFieldByHandle(handle) %}`
3. Query `field.optgroups`
4. Get the error

### Expected behavior
Get the `optgroups` value.

### Actual behavior
Error

### Craft CMS version

4.4.1

### PHP version

8.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
That property shouldn’t even change; it would only be `true` for `Dropdown` and `MultiSelect` fields, and just tells the field settings that it’s OK to allow some rows in the Options table to be marked as an optgroup.

So I guess you could use the [`instance of`](https://craftcms.com/docs/4.x/dev/tests.html#instance-of) test to check if it’s a `Dropdown` or `MultiSelect` field:

```twig
{% if field is instance of 'craft\\fields\\Dropdown' or field is instance of 'craft\\fields\\MultiSelect' %}
```

**Comment by romainpoirier** [comment]
Thank you. I think that I was using this to check if there's at least one `optgroup` setup in this field, and get the total of `optgroups`.

I understand that the correct way would be to filter the options: `field.options | filter(item => item.optgroup is defined) | length`. Please let me know if that isn't safe to use.

**Comment by brandonkelly** [comment]
Yeah that works, and will be more reliable. `optgroups` would have been `true` for _every_ Dropdown and Multi-Select field in Craft 3, not just the ones that actually contain optgorups.
