### ISSUE TITLE
[4.x]: Element action buttons are not centered if the source has no exporters

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#12885]
### Description

#12793 improved element action buttons' visibility by increasing color contrast and centering the buttons in the index footer.

However if a source has no element exporters defined, the action buttons are not centered:  

![CleanShot 2023-03-14 at 09 55 08](https://user-images.githubusercontent.com/298510/224947908-a16d7e73-28e2-45a5-ac8e-908f56f329b2.png)

### Steps to reproduce

1. Add a section and some entries
2. Add a custom module and remove all core element exporters with the following:

```php
Event::on(
    Element::class,
    Element::EVENT_REGISTER_EXPORTERS,
    static function (RegisterElementExportersEvent $event) {
        $event->exporters = [];
    }
);
```

### Expected behavior

Element action buttons should always be centered in the element index footer.

### Actual behavior

Element action buttons are only centered if the "Export..." button is visible; i.e. there is at least 1 element exporter defined for the current element index source.

### Craft CMS version

4.4.1

### PHP version

8.1.12

### Operating system and version

macOS 12.6

### Database type and version

10.9.3-MariaDB

### Installed plugins and versions

Plenty, but have tested with `'disabledPlugins' => '*',` as well.

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release.

**Comment by brandonkelly** [comment]
4.4.2 is out with that fix.
