### ISSUE TITLE
[4.x]: `attr` filter double-encoding existing `class` and `style` attributes

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#12887]
### Description

If the `attr` filter is applied to a tag that already had its attributes encoded, any exploded attributes like `class` and `style`, will become double-encoded.

The reason seems to be that `Html::parseTagAttributes()` doesn't account for exploded attributes: https://github.com/craftcms/cms/blob/2c347e18b58cba7de4eefa53b0235f0b0c756432/src/helpers/Html.php#L361

Related: #12886 

### Steps to reproduce

Applying multiple `|attr` filters to the same tag will double encode ampersands (i.e. to `&amp;amp;` instead of the expected `&amp;`) in the class attribute:

```twig
{% apply attr({ disabled: true })|attr({ type: 'button' }) %}
    <button class="[&[disabled]]:opacity-50">
{% endapply %}
```

The double-encoding also happens if a tag is rendered using the `{% tag %}` tag or `tag()` function, and then has the `attr` filter applied to it:

```twig
{{ tag('button', { class: '[&[disabled]]:opacity-50' })|attr({ disabled: true }) }}
```

### Expected behavior

The `attr` filter should never double-encode existing attributes.

### Actual behavior

The `attr` filter will double-encode certain existing attributes, such as `class` and `style`.

### Craft CMS version

4.4.1

### PHP version

8.1.12

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Thanks for reporting! Craft 3.8.2 and 4.4.2 are out now with a fix.

**Comment by mmikkel** [comment]
Awesome, thanks a lot Brandon 🚀
