### ISSUE TITLE
[4.4.1]: Twig\Error\RuntimeError: Calling unknown method: craft\elements\Entry::isNew()

### ISSUE THREAD

**Issue by readtedium** [craftcms/cms#12883]
### What happened?

A runtime error while saving database entries such as new posts or template settings.

### Description

When saving a new item in the database or updating an existing one (I ran into this while attempting to set up my multisite in a DDEV environment), I get a show-stopping error that I can’t seem to get past.

The information does appear to save, but it pushes this error every time I hit. I will note that I ran into this in the midst of a large site migration with roughly 1k distinct post entries (only local at this time).

```
Twig\Error\RuntimeError: Calling unknown method: craft\elements\Entry::isNew() in "__string_template__9832bcb82d09d48a2e5ad38cb217854322f8bd01d79f6e0803f12d3a02c6cd14" at line 16 in /var/www/html/vendor/craftcms/cms/src/helpers/Template.php:152
Stack trace:
#0 /var/www/html/storage/runtime/compiled_templates/cb/cb1e67b16c75a74b7a22f36716e7d458ded77891bcaa57116e2b987747db4bd7.php(54): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\Entry), 'isNew', Array)
#1 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_3276d0ddf49dd38cb526f85c193045f706521f0141d7a4a0451bf22dca00a741->doDisplay(Array, Array)
#2 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#3 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#4 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#5 /var/www/html/vendor/craftcms/cms/src/web/View.php(545): Twig\TemplateWrapper->render(Array)
#6 /var/www/html/vendor/craftcms/webhooks/src/Plugin.php(157): craft\web\View->renderString('{% set entry = ...', Array)
#7 [internal function]: craft\webhooks\Plugin->craft\webhooks\{closure}(Object(craft\events\ModelEvent))
#8 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\ModelEvent))
#9 /var/www/html/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('craft\\elements\\...', 'afterSave', Object(craft\events\ModelEvent))
#10 /var/www/html/vendor/craftcms/cms/src/base/Element.php(4935): yii\base\Component->trigger('afterSave', Object(craft\events\ModelEvent))
#11 /var/www/html/vendor/craftcms/cms/src/elements/Entry.php(1931): craft\base\Element->afterSave(false)
#12 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(3127): craft\elements\Entry->afterSave(false)
#13 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1063): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), false, true, true, Array, false)
#14 /var/www/html/vendor/craftcms/cms/src/services/Drafts.php(375): craft\services\Elements->saveElement(Object(craft\elements\Entry), false)
#15 /var/www/html/vendor/craftcms/cms/src/services/Drafts.php(317): craft\services\Drafts->removeDraftData(Object(craft\elements\Entry))
#16 /var/www/html/vendor/craftcms/cms/src/controllers/ElementsController.php(1352): craft\services\Drafts->applyDraft(Object(craft\elements\Entry))
#17 [internal function]: craft\controllers\ElementsController->actionApplyDraft()
#18 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#19 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#20 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('apply-draft', Array)
#21 /var/www/html/vendor/craftcms/cms/src/web/Application.php(302): yii\base\Module->runAction('elements/apply-...', Array)
#22 /var/www/html/vendor/craftcms/cms/src/web/Application.php(627): craft\web\Application->runAction('elements/apply-...', Array)
#23 /var/www/html/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#24 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#25 /var/www/html/web/index.php(12): yii\base\Application->run()
#26 {main}
```

### Steps to reproduce

1. Migrate database from Craft 3 to Craft 4
2. Save a post or other database entry

### Expected behavior

Posts save to the site with no issues.

### Actual behavior

The posts appear to save but every save leads to a calling unknown method error.

### Craft CMS version

Craft Pro 4.4.1

### PHP version

8.0.28

### Operating system and version

Linux 5.15.49-linuxkit (containerized via DDEV, MacOS 12.6.2)

### Database type and version

MariaDB 10.4.28

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- Amazon S3	2.0.1
- Amplify	2.0.0
- Blitz	4.4.2
- Blitz Recommendations	2.1.1
- Bulk Edit	4.0.1
- Cloner	2.0.3
- CodeMirror	2.0.0
- Control Panel CSS	2.6.0
- Copy	2.3.0
- Doxter	5.0.4
- Embedded Assets	3.1.1
- Feed Me	5.0.5
- Imgixer	2.1.2
- Minify	4.0.0-beta.2
- MJML	2.0.0
- oEmbed	2.3.0
- Patrol	5.0.1
- Redirect Manager	2.0.0
- Retcon	2.6.1
- Scout	3.1.0
- SEO	v4.0.3
- Shield	3.0.1
- Style Inliner	3.0.0
- Tags	2.0.0
- TDE Emoji text	2.0.0
- Twitter	v4.x-dev
- Webhooks	3.0.4
- Wordsmith	4.2.0

**Comment by brandonkelly** [comment]
Per the stack trace, the error is coming from one of your webhook templates, via the `craft\elements\Entry::EVENT_AFTER_SAVE` event (or perhaps `craft\base\Element::EVENT_AFTER_SAVE`.

I can see that the template starts with `{% set entry =`, but that’s all that is shown in the estack trace.

**Comment by readtedium** [comment]
Good eye on that—I am going to dig into the webhook call shortly just to make sure it’s not something deeper. Turning it off does seem to stop the error.

I’ll leave open for now just in case but will come back to within the next day; if I find that the issue is resolved after messing with the webhook code I’ll close.
