### ISSUE TITLE
[4.x]: Migration failure for add_image_transform_fill due to project config read-only mode

### ISSUE THREAD

**Issue by mattgrayisok** [craftcms/cms#12898]
### Description

A client is experiencing an exception during the m221027_160703_add_image_transform_fill migration:

```
 *** applying m221027_160703_add_image_transform_fill
> add column fill string(11) NULL DEFAULT NULL AFTER `interlace` to table {{%imagetransforms}} ... done (time: 0.036s)
> add column upscale boolean NOT NULL DEFAULT TRUE AFTER `fill` to table {{%imagetransforms}} ... done (time: 0.038s)
> alter column mode in table {{%imagetransforms}} to enum('stretch','fit','crop','letterbox') NOT NULL DEFAULT 'crop' ... done (time: 0.034s)
Exception: Changes to the project config are not possible while in read-only mode. (/var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php:504)
#0 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(476): craft\services\ProjectConfig->_setInternal('imageTransforms...', Array, NULL, true, false)
#1 /var/www/html/vendor/craftcms/cms/src/migrations/m221027_160703_add_image_transform_fill.php(53): craft\services\ProjectConfig->set('imageTransforms...', Array) 
```

I assume a relaxation needs adding in to work around for any < 4.4.0.3 to latest upgrades.

### Steps to reproduce

1. Be on Craft < 4.4.0.3
2. Run migrations in an environment with `allowAdminChanges=false`

### Expected behavior

Good upgrade times

### Actual behavior

Bad upgrade times

Cheers!

### Craft CMS version

From 4.3.6.1 To 4.4.2

### PHP version

8.0.25

### Operating system and version

Alpine

### Database type and version

MariaDB 10.6

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
They must be updating on production directly then, as opposed to deploying an update that was already performed locally.

All migrations that modify the project config are defensive about only making project config changes if Craft is being updated to the target version _for the first time_, which should be on an environment that allows project config changes.

(See [Project Config Migrations](https://craftcms.com/docs/4.x/extend/project-config.html#project-config-migrations) for an explanation of how it’s supposed to work.)

> Be on Craft < 4.4.0.3

`4.4.0.3` was the _schema version_ that the migration was added for (see https://github.com/craftcms/cms/pull/12214/files). The _Craft_ version that the migration was added in was `4.4.0-beta.1`.
