### ISSUE TITLE
[4.x]: Key "heading" for array with keys "editNodes:1" does not exist.

### ISSUE THREAD

**Issue by FrDH** [craftcms/cms#12892]
### Description
After updating from Craft 3.7 to 4.4.1, We get the following error when going to a user-page (where user permissions are listed):
> Key "heading" for array with keys "editNodes:1" does not exist.

It's in this template:
```
 <div class="user-permissions">
    <h3>{{ group.heading }}</h3>
    <div class="select-all"></div>
    {{ permissionList(subject, groupPermissions ?? [], group.permissions) }}
</div>
```

There are no pending migration.
Any idea's on how to fix this?

Thanks.

### Craft CMS version

4.4.1

**Comment by FrDH** [comment]
Probably a Freeform issue

**Comment by brandonkelly** [comment]
Sounds related to this 4.0 change: #7771
