### ISSUE TITLE
[4.x]: Element index settings are lost when clicking outside the modal

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#12895]
### Description

When editing the element index settings, clicking outside the modal closes it. This means you lose all pending changes you've been working on. One mis-click means you have to start over. See the video for demonstration:

https://user-images.githubusercontent.com/10146880/225334128-499a4fa5-06db-449d-b223-6cd474cc3ad5.mov

### Steps to reproduce

1. Go to the entries index and click on _Customize sources_.
2. Make some changes in the modal.
3. Click outside the modal to close it.
4. When opening the modal again, any unsaved changes are lost.

### Expected behavior

It's unfortunate that an accidental click outside the modal causes you to lose any changes you've done. I can think of two possible improvement:

1. Don't allow the modal to be closed by clicking outside it.
2. The modal could retain the pending state on the current page, so that clicking _Customize sources_ again will return it to the last state.

### Craft CMS version

4.4.2

### PHP version

8.2

**Comment by brandonkelly** [comment]
Agree, that modal is a little too easy to close. Just tweaked it for the next Craft 3 and 4 releases, so <kbd>Esc</kbd> key presses and clicks outside the modal no longer cause it to be hidden/removed.

**Comment by MoritzLost** [comment]
Thanks @brandonkelly !

**Comment by brandonkelly** [comment]
3.8.3 and 4.4.3 are out with that change!
