### ISSUE TITLE
[4.x]: Categories converted to a section get a default preview target, even if the categories have no URL

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#12897]
### Description

After running `entrify/categories`, the section created by the command includes a default preview target, even if the category doesn't have a URL. This doesn't make sense, as categories without a URL don't have frontend pages in most cases, so the preview target will only show a 404 page.

### Steps to reproduce

1. Convert an existing category without a URL to a section using `entrify/categories`.
2. Check the section settings, it will include a preview target.

### Expected behavior

If the category / newly created section doesn't have a URL, it also shouldn't have a preview target. If this presents technical problems, the new sections could just be created without any preview targets by default.

### Craft CMS version

4.2.2

### PHP version

8.2

**Comment by brandonkelly** [comment]
Good call. As of the next release, a “Primary entry page” preview target will only be added if the section is sourced from a category group with URLs.

**Comment by MoritzLost** [comment]
@brandonkelly Great, thanks!

**Comment by brandonkelly** [comment]
4.4.3 is out with that change!
