### ISSUE TITLE
[4.x]: Plain Text Field strips out em dash character on save.

### ISSUE THREAD

**Issue by myleshyson** [craftcms/cms#12905]
### Description
Noticed today that the plain text field strips out the em dash character on save because when it serializes the value it passes the value through `LitEmoji::unicodeToShortcode`.  This is a problem because we're using a text field with a drop down to construct a title for a particular entry type, and the text field should allow em dashes (and probably other utf-8 charachters) like the native title field. Em dashes _are_ persisted when used in the native title field. 

### Steps to reproduce
1. Create a plain text field.
2. Put some text in it with an em dash character.
3. Save the entry and see that the em dash character is removed.

### Expected behavior
Em dashes (and probably other unicode characters) should not be filtered out when saving a plain text field.

### Actual behavior
Em dashes are filtered out when saving a plain text field.

### Craft CMS version

4.4.1

### PHP version

8.1.7

### Database type and version

Mysql 8.0.31

### Installed plugins and versions

-

**Comment by i-just** [comment]
Thanks for reporting. Various other punctuation characters are also affected by this. There’s also an open issue for this in `elvanto/litemoji` GitHub ([link](https://github.com/elvanto/litemoji/issues/36)). We’ll discuss options internally, and once I have more info, I’ll update this issue again.
