### ISSUE TITLE
[4.x]: Select field in Matrix field with empty value

### ISSUE THREAD

**Issue by arentsen** [craftcms/cms#12902]
### Description
When adding a select field in a Matrix field with an option that has an empty value, it does only show up the first time in the CMS as an option to choose. After you choose another value, you can no longer go back to the option with value "".

<img width="881" alt="Screenshot 2023-03-15 at 17 27 26" src="https://user-images.githubusercontent.com/7302698/225375981-c3c329b7-8a55-410c-9683-94ffe91057c0.png">

<img width="419" alt="Screenshot 2023-03-15 at 17 30 06" src="https://user-images.githubusercontent.com/7302698/225376667-b4e57db9-faf1-471d-a20f-2319824d9811.png">

### Craft CMS version

4.4

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
This was fixed in 4.4.2, via de5ed75b1450563c0acffaea69ad94f5e976c609.
