### ISSUE TITLE
[4.1.1]: Missing file system handle-error when uploading an asset in a newly created matrix field

### ISSUE THREAD

**Issue by arifje** [craftcms/cms#12901]
### What happened?

I remember bumping into this issue a long time ago, then it was solved, but apparently it found his way back!

The error:

![Screenshot 2023-03-15 at 17 11 42](https://user-images.githubusercontent.com/1286410/225374612-61a42daa-0660-4964-ab21-d8079928ba7c.png)

The logs:

![Screenshot 2023-03-15 at 17 13 31](https://user-images.githubusercontent.com/1286410/225374877-4d03d581-6028-4af4-b17a-5098b1880af7.png)

Reproduce:

1) create a new entry
2) create a new matrix field
3) drag/upload an asset (image in my case)

How to "solve" it: save the entry first after creating the matrix field, then the upload works fine.

### Craft CMS version

4.1.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
This should be fixed in yesterday’s 4.4.2 release, via ac5c4bbed4c. Will close this for now, but let me know if you’re still seeing the error after updating to 4.4.2.
