### ISSUE TITLE
[4.x]: Blocks within Matrix field lose layout when being dragged and dropped

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/cms#12909]
### Description

When fields within a matrix field have been assigned a layout width (1,2, or 3 columns), when being dragged and dropped they lose their defined layout.

https://user-images.githubusercontent.com/2373940/225620190-31b43998-1e15-4a9c-9978-3b95e4440442.mp4

### Steps to reproduce

1. Create a matrix field
2. Add 4 text fields to it and assign the column width to 1 for each field so the 4 fields appear in 1 row
3. Assign the field to an entry
4. Add 4 or 5 rows and drag and drop the fields around
5. Layout is lost whilst dragging (they take up 4 columns)

### Expected behavior

Layout to be preserved when dragging and dropping blocks within matrix fields

### Actual behavior

Layout is not preserved when dragging and dropping blocks within matrix fields

### Craft CMS version

v4.4.2

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting. I created PRs to adjust this for both Craft 3 and 4.

**Comment by brandonkelly** [comment]
3.8.3 and 4.4.3 are out with the fix!

**Comment by jonleverrier** [comment]
@i-just @brandonkelly Super! Thanks for the fast turn around.
