### ISSUE TITLE
[4.x]: entries selection modal applies search string from previous invokation (but does not show it)

### ISSUE THREAD

**Issue by freder** [craftcms/cms#12900]
### Description
- I have a matrix field with an _entries_ subfield
- after filtering entries, the next time the modal is opened the same search/filter is still applied, but the search input field is empty

### Steps to reproduce

1. <img width="1011" alt="01" src="https://user-images.githubusercontent.com/724844/225370753-55ad062e-5f86-4fa3-9ff6-020ce2d06b69.png">
2. <img width="933" alt="02" src="https://user-images.githubusercontent.com/724844/225370872-f42172f8-f8c7-4f0f-b080-2031a9189b91.png">
3. <img width="833" alt="03" src="https://user-images.githubusercontent.com/724844/225370931-eb7671a8-4d30-4271-8de7-3cf6c79b2697.png">
4. <img width="1027" alt="04" src="https://user-images.githubusercontent.com/724844/225370996-a402ab73-0a1e-4c3e-83bc-d53ec15ff35b.png">
5. <img width="913" alt="05" src="https://user-images.githubusercontent.com/724844/225371105-7d34c075-5181-4261-881f-90d32fb4e28c.png">
6. <img width="947" alt="06" src="https://user-images.githubusercontent.com/724844/225371193-b06169d0-6118-40ba-9a00-37aaf2110d64.png">

### Expected behavior
list should not be filtered when opening the modal
OR: search field should show the search term

### Actual behavior
see steps above

### Craft CMS version

4.4.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed now for the next release.

**Comment by brandonkelly** [comment]
4.4.3 is out now with that fix!
