### ISSUE TITLE
[4.x]: Plugin store cart modal doesn't show selected plugin edition

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#12910]
### Description

The "add to cart" modal should show which edition of a plugin you have in the cart, like the Craft CMS lineitem does.

<img width="828" alt="image" src="https://user-images.githubusercontent.com/3810939/225631850-783a874b-96d3-4cc7-a199-01a20a0e5147.png">

### Craft CMS version

4.3.11

### PHP version

8.1

**Comment by brandonkelly** [comment]
Thanks for reporting that! 3.8.3 and 4.4.3 are out with a fix for this!
