### ISSUE TITLE
Duplicate a content tree within a Structure

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1291]
> Created by: Phil Chairez (phillip.chairez@ideapublicschools.org) on 2015/07/27 18:12:44 +0000
> Votes at time of UserVoice import: 1

-----------------------------------

I'm creating a website for a charter school with multiple schools. I've created an Entry for each school with its sub-pages within that. Every school follows the exact same format. There needs to be a way to "Duplicate" a top level Entry with all of its sub-entries included. Right now I'm going entry by entry "saving as a new" and having to move it down to a new school's top-level entry. Surely there's a much easier way. Craft, please make this happen. Tonight would be awesome. ;)

**Comment by pgrzyb** [comment]
Hi there! Is this ever going to happen? Or maybe did someone figure out a workaround that could help me not pull out all my hair while duplicating those entries manually? :)

**Comment by brandonkelly** [comment]
Jut made this possible for today’s release :)
