### ISSUE TITLE
[4.x]: Multiple tabs with the same name are not displaying correctly when editing an element

### ISSUE THREAD

**Issue by bertoost** [craftcms/cms#12928]
### Description

When I accedentally added two of the same tabs to a category field layout. Just one is appearing on the edit page. 

Probably this also occurs on other field layouts

### Steps to reproduce

1. Add a category
2. Define two tabs with the same name
3. Save it.
4. Start editing

### Expected behavior

I expect Craft to add 1 or 2 or to throw an error when I try to save duplicate names on tabs

### Actual behavior

I saves without warning and not displaying the second tab with the same name.

### Craft CMS version

4.4.1

### PHP version

8.2.3

**Comment by i-just** [comment]
Hi, thanks for reporting! I created a PR to address this.

**Comment by brandonkelly** [comment]
Craft 4.4.5 is out now with a fix for this, via #12939 🎉
