### ISSUE TITLE
[4.x]: Error occures when moving an asset to a folder where a copy exists already

### ISSUE THREAD

**Issue by yingban** [craftcms/cms#12920]
### Description
in an asset folder, I have the following:
-- file1
-- folder/fle1

I tried to move the file1 to folder1, got the prompt with 
- replace it
- keep both

I got the following error with both choices:
Uncaught TypeError: Cannot read properties of undefined (reading 'folderId') in handleConflictChoice function

### Steps to reproduce
1. create a subfolder with the same file as in parent folder
2. try to move the file in parent folder to subfolder
3. click "keep both" or "replace it"

### Expected behavior
The move file should be moved

### Actual behavior
Nothing happens and error in console occures

### Craft CMS version

4.4.3

### PHP version

8.0.28

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next Craft 3 and 4 releases.

**Comment by brandonkelly** [comment]
Craft 3.8.4 and 4.4.4 are out with that fix. Thanks again!
