### ISSUE TITLE
[4.x]: PostgreSQL dump uses `--column-inserts` by default

### ISSUE THREAD

**Issue by ccchapman** [craftcms/cms#12937]
This is a question or potential change request.

We recently had a scenario where we needed to restore a Craft provided DB dump using `craft db/restore`.  The `craft db/backup` action uses `--column-inserts` by default (https://github.com/craftcms/cms/commit/05a6796772b9a66fab987bf103779e2b6fd485de) when using PostgreSQL.  Here is the `pg_dump` documentation on that flag:

> Dump data as INSERT commands with explicit column names (INSERT INTO table (column, ...) VALUES ...). This will make restoration very slow; it is mainly useful for making dumps that can be loaded into non-PostgreSQL databases. Any error during restoring will cause only rows that are part of the problematic INSERT to be lost, rather than the entire table contents.

The import for a 450 MB DB with `--column-inserts` from an EC2 to RDS took 80 minutes.  A DB created _without_ the flag is only 130 MB and imports significantly quicker.  (15 seconds on my local.)

We are looking at using the `backupCommand` config to override this behaviour.  However, we are curious what Craft's reason for passing the flag by default is or if there is caution against not having it.

**Comment by angrybrad** [comment]
@ccchapman I guess that it was added for backward compatibility reasons - i.e. a dump was made using pg_dump on a newer version of Postgres, then restored with an older version of Postgres.

I’d love to verify that, but I’ve looked through our support internally and through public Github issues, and I can’t find what originally prompted it, though. :-/

If you want to override it using `backupCommand`, here is the full command Craft generates by default:

```
pg_dump --dbname=mydb --host=myhost --port=5432 --username=myuser --if-exists --clean --no-owner --no-privileges --no-acl --file="/path/to/dump.sql" --schema=public --column-inserts --exclude-table-data 'public.assetindexdata' --exclude-table-data 'public.assettransformindex' --exclude-table-data 'public.sessions' --exclude-table-data 'public.templatecaches' --exclude-table-data 'public.templatecachequeries' --exclude-table-data 'public.templatecacheelements' --exclude-table-data 'public.cache' --exclude-table-data 'public.templatecachecriteria'
```

Or, consider using `--format=custom` (https://www.postgresql.org/docs/12/app-pgdump.html), which is a binary dump, and will likely be much smaller and make `--column-inserts` less of an issue (completely untested, though).

It’s on my list to look into making that the default for Craft 5, too.

**Comment by ccchapman** [comment]
Thanks for the insight and tips!  👍

**Comment by ccchapman** [comment]
If anyone comes across this, you can add the below to `config/general.php` for the default backup _except_ no `--column-inserts`.

```php
->backupCommand(
    "PGPASSWORD=\"{password}\"" .
        " pg_dump" .
        " --dbname={database}" .
        " --host={server}" .
        " --port={port}" .
        " --username={user}" .
        " --if-exists" .
        " --clean" .
        " --no-owner" .
        " --no-privileges" .
        " --no-acl" .
        " --file=\"{file}\"" .
        " --schema={schema}" .
        " --exclude-table-data '{schema}.assetindexdata'" .
        " --exclude-table-data '{schema}.imagetransformindex'" .
        " --exclude-table-data '{schema}.resourcepaths'" .
        " --exclude-table-data '{schema}.sessions'" .
        " --exclude-table-data '{schema}.cache'"
)
```
