### ISSUE TITLE
[4.x]: `entrify/categories` command discards disabled categories

### ISSUE THREAD

**Issue by dlindberg** [craftcms/cms#12945]
### Description

Running `entrify/categories` does not migrate categories that are not enabled at the time of the transfer

### Steps to reproduce

1. Create a Category in a category structure that is disabled.
2. Update to Craft 4.4 (category structure is flattened by this update?)
3. run `craft entrify/categories` on a category with disabled categories
4. Anything disabled will disappear

### Expected behavior

Categories, even if disabled, will be transferred and their enabled / disabled state will be retained.

### Actual behavior

Disabled categories are deleted.

### Craft CMS version

Moving from 4.3.x to 4.4.x

### PHP version

8.1

### Database type and version

mysql

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just released Craft 4.4.5 with a fix.
