### ISSUE TITLE
[3.x]: Lightswitch labels are not being translated

### ISSUE THREAD

**Issue by 7ochem** [craftcms/cms#12942]
### Description

I added a lightswitch to a matrix block in the control panel. I added a field label and added on and off labels. Now I can add translations to translations/nl/site.php for the label, but the on and off switch labels stay untranslated.

### Steps to reproduce

1. Add a lightswitch in the control panel
2. Add a field label
3. Add on and off labels
4. Add translations to translations/nl/site.php for the label and the on and off switch labels

### Expected behavior

The field label and on and off labels will get translated.

### Actual behavior

The field label is being translated, but the on and off labels are not.

I checked `vendor/craftcms/cms/src/templates/_includes/forms/lightswitch.html` and there's no `|t('...')` on the on and off labels.

This happens in Craft CMS v3 and also in v4.

### Craft CMS version

3.7.53.1

### PHP version

8.1.0

### Operating system and version

Ubuntu 18.04.1

### Database type and version

MariaDB 10.5

### Image driver and version

?

### Installed plugins and versions

- craftcms/element-api      2.8.6.1
- craftcms/feed-me          4.5.3
- craftcms/html-field       1.0.9
- craftcms/oauth2-craftid   1.0.0.1
- craftcms/plugin-installer 1.5.7
- craftcms/redactor         2.10.10
- craftcms/server-check     1.2.4

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just released Craft 3.8.5 and 4.4.5 with a fix.

**Comment by 7ochem** [comment]
Thank you for the super fast response! 🚀
