### ISSUE TITLE
[4.x]: When viewing entry revisions assets are always displayed in list view mode

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#12948]
### Description
When viewing revisions of an entry, any asset fields display their related assets as a list, even when `Large Thumbnails` is selected in the field's settings' `View mode`.

### Steps to reproduce

1. Create an asset field with `View mode` set to `Large thumbnails` and assign it to an entry type.
2. Add some images to an entry of this type
3. Edit this entry so there are some revisions.
4. Go to any of the past revisions.

### Expected behavior
The assets should display as `Large thumbnails`

### Actual behavior
The assets always display as a `List`

### Craft CMS version

4.4.5

### Installed plugins and versions

-

**Comment by i-just** [comment]
Thanks for reporting. I submitted a PR to adjust this.

**Comment by brandonkelly** [comment]
Fixed for the next Craft 3 and 4 releases via #12953.

**Comment by brandonkelly** [comment]
Craft 3.8.6 and 4.4.6 are out with that fix 🎉
