### ISSUE TITLE
[4.4.4]: UX: Moving of assets not possible

### ISSUE THREAD

**Issue by mfell** [craftcms/cms#12957]
### Description
It's not possible to move assets.

### Steps to reproduce

1. Choose an asset
2. Try to move it into another folder
3. the button (in German "Verschieben") is disabled

Tested under **macOS 12.6.x** and **Chrome**.

### Expected behavior
An enabled button.

### Actual behavior
Button disabled.

https://user-images.githubusercontent.com/6691773/226971340-2ab0346e-f72b-4cc4-97d5-d2118e979c41.mov

### Craft CMS version

Craft Pro 4.4.4 (first recognition of topic)

### PHP version

8.1.13

### Operating system and version

Linux 5.15.49-linuxkit (DDEV)

### Database type and version

MySQL 5.7.38

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

```
		"carlcs/craft-redactorcustomstyles": "4.0.3",
		"craftcms/cms": "4.4.5",
		"craftcms/redactor": "3.0.4",
		"doublesecretagency/craft-cpcss": "2.6.0",
		"nystudio107/craft-seomatic": "4.0.22",
		"nystudio107/craft-templatecomments": "^4.0",
		"nystudio107/craft-vite": "4.0.5",
		"sebastianlenz/linkfield": "2.1.5",
		"spicyweb/craft-embedded-assets": "3.1.1",
		"spicyweb/craft-neo": "3.7.3",
		"verbb/user-group-field": "3.0.1",
		"vlucas/phpdotenv": "^5.4.0",
		"xpertbot/craft-wheelform": "3.1.5"
```

**Comment by i-just** [comment]
Hi, thanks for reaching out. This happens in 3.8 and 4.4 and is related to the Embedded Assets plugin. If you disable the plugin, moving will work as expected. Alternatively, you can also move assets via drag & drop. 

Selecting an asset and using the cog > Move riggers a modal. That modal doesn’t have the “Upload files” button, which Embedded Assets seem to rely on to add their “Embed” button: https://github.com/spicywebau/craft-embedded-assets/blob/main/src/assets/main/src/scripts/main.ts. This causes a JS error which then causes the “Move” button not to be enabled.

It would be best to raise this issue with The Spicy Web team: https://github.com/spicywebau/craft-embedded-assets/issues

**Comment by mfell** [comment]
@i-just Thanks a lot, Iwona ... I'll do.

**Comment by mfell** [comment]
[just to get an refer link](https://github.com/spicywebau/craft-embedded-assets/issues/227)
