### ISSUE TITLE
[4.x]: UX issue with address country field / selectize dropdown 

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#12950]
### Description

I'm seeing an issue where the width of the country dropdown menu in the native user addresses form shrinks to the width of the currently selected option, being too small to see any of the options when nothing is selected. Even while _United States_ is selected, longer country names are cut off, which is not ideal. See the following video:

https://user-images.githubusercontent.com/10146880/226887583-1e58f54d-cd22-430d-8859-48a7fd4ef018.mov

### Steps to reproduce

1. On any user account, click on _Add an address_
2. Open the _Country_ dropdown and hit backspace to delete the selected option.

### Expected behavior

The dropdown should have a minimum width or be sized dynamically to always fit the longest option in the dropdown, to ensure the options are always visible.

### Actual behavior

The dropdown shrinks to a very narrow width, making the options illegible.

### Craft CMS version

4.4.4

### PHP version

8.2

**Comment by i-just** [comment]
Hi, thanks for reporting! I submitted a PR to adjust this.

**Comment by brandonkelly** [comment]
Fixed for the next release via #12959.

**Comment by brandonkelly** [comment]
Craft 4.4.6 is out now with that fix 🎉
