### ISSUE TITLE
[4.4.5]: Using "Field Limit" after creating new "Plain Text Field" -> Database Exception

### ISSUE THREAD

**Issue by mfell** [craftcms/cms#12954]
### Description
Got a Database Exception when using "Field Limit" of a just created and saved new "Plain Text Field".

```
Database Exception – [yii\db\Exception](https://www.yiiframework.com/doc-2.0/yii-db-exception.html)
SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
The SQL being executed was: ALTER TABLE `content` ADD `field_assetDownloadName_hdmffqxr` varchar(200)
Error Info: Array
(
    [0] => 42000
    [1] => 1118
    [2] => Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
)
↵
Caused by: PDOException
SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
in /var/www/html/vendor/yiisoft/yii2/db/Command.php at line 1302
```

### Steps to reproduce

1. Create a new "Plain Text Field"
2. Safe 
3. Set the option "Field Limit" (in my case 50)

### Expected behavior

no Database Exception

### Actual behavior

- Database Exception
- Reload after Database Exception, see pdf

[Database Exception – yii_db_Exception.pdf](https://github.com/craftcms/cms/files/11040945/Database.Exception.yii_db_Exception.pdf)

Can send you config.json and DB, if needed.

### Craft CMS version

Craft Pro 4.4.5

### PHP version

8.1.13

### Operating system and version

Linux 5.15.49-linuxkit (DDEV)

### Database type and version

MySQL 5.7.38

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- "carlcs/craft-redactorcustomstyles": "4.0.3",
- "craftcms/cms": "4.4.4",
- "craftcms/redactor": "3.0.4",
- "doublesecretagency/craft-cpcss": "2.6.0",
- "nystudio107/craft-seomatic": "4.0.22",
- "nystudio107/craft-templatecomments": "^4.0",
- "nystudio107/craft-vite": "4.0.5",
- "sebastianlenz/linkfield": "2.1.5",
- "spicyweb/craft-embedded-assets": "3.1.1",
- "spicyweb/craft-neo": "3.7.3",
- "verbb/user-group-field": "3.0.1",
- "vlucas/phpdotenv": "^5.4.0",
- "xpertbot/craft-wheelform": "3.1.5"

**Comment by brandonkelly** [comment]
That error occurs when the `content` table has grown too large, and MySQL can’t allow any additional columns to be added.

Plain Text fields will choose their column type automatically by default, based on the Field Limit setting. `50` would result in `varchar(200)`, which is actually more taxing on MySQL’s row size limit than `text` despite having a significantly smaller storage allocation, because `text` columns’ content gets stored on disk rather than directly within the table, internally. So if your `content` table was already right on the edge of the max row size, changing a `text` column to `varchar(200)` could push it over.

Plain Text fields do let you choose their column types, via their “Column Type” settings under “Advanced”. So as a temporary workaround you could go through and force some of your Plain Text fields to use `text` columns.

We are working on a long-term solution for Craft 5. I’ll keep this open and follow-up when that’s done.

**Comment by mfell** [comment]
Ok...if I understand correctly, the problem is the **length** of the `content` table and **not the number** of fields?

If so, sounds better to use a `light switch` for `boolean` and **not a drop down field** (null, yes, no) - like I do.

**Comment by mfell** [comment]
Just a suggestion / idea: The **dropdown field** (e.g.) has no setting "Advanced" and is a `VARCHAR(255)` in database.

In my case I use this field type mostly (99%) for setting classes and even not, this field is way too big for me.

Having the option to switch this field to `TEXT` would reduce the row size enormously in my projects.

**Comment by brandonkelly** [comment]
> Ok...if I understand correctly, the problem is the **length** of the `content` table and **not the number** of fields?

Right :)

> Having the option to switch this field to `TEXT` would reduce the row size enormously in my projects.

`text` columns can help with the row size, but also come with a significant performance hit, especially if you ever need to query against the column in an element query or entry condition.

It may make sense for Dropdown (and Radio Buttons) fields to use dynamically-sized columns though, e.g. `varchar(3)` if we know `yes` is the longest possible value. That would lead to a SQL error if the column already contains any data that’s longer than three characters, though (e.g. if you edit an existing Dropdown field and delete a preexisting option with a longer value). So we would need to couple that with a bit of cleanup code as well, to ensure all rows are set to one of the current field options, or `null`.

**Comment by mfell** [comment]
@brandonkelly Thank you so much, to put this topic on the roadmap!

> Smart Dropdown/Radio Button column lengths

May I suggest to think about this for the checkbox field, too?
For me this looks like an identical topic.

![Bildschirmfoto 2023-04-01 um 10 34 10](https://user-images.githubusercontent.com/6691773/229275595-098882b4-235c-4255-89b1-09edb492d3ed.png)

![Bildschirmfoto 2023-04-01 um 10 34 56](https://user-images.githubusercontent.com/6691773/229275439-344e33dd-daad-42fb-aa31-dbd082eff224.png)

**Comment by brandonkelly** [comment]
Checkboxes and Multi-select fields already do use smart column sizes, based on how many bytes would be needed if *all* options were selected.

**Comment by brandonkelly** [comment]
Made the Dropdown/Radio Buttons changes for 4.5 (#13025) 🎉

**Comment by mfell** [comment]
> Made the Dropdown/Radio Buttons changes for 4.5 (#13025) 🎉

GRRRRREEEEAT! 🎉

And thank you so much!🍻

**Comment by brandonkelly** [comment]
Craft 4.5.0 is out now with those changes.
