### ISSUE TITLE
[4.4.5]: Cant save global set if it contains a dropdown field

### ISSUE THREAD

**Issue by Mathias-Syversen** [craftcms/cms#12965]
### What happened?

Adding a dropdown field to a global sets results in an error when saving.

### Steps to reproduce

1. Create or use an existing drowpdown field
2. Add it to a global set
3. Save

### Expected behavior

Global set is saved

### Actual behavior

Error occurs, "Could not save global set".
No errors in web.log or phperrors.log

### Craft CMS version

4.4.5

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting. This happens when you want to add a dropdown that doesn’t have an empty value to a global set. I submitted a PR for this.

**Comment by brandonkelly** [comment]
Fixed for the next release via #12970.

**Comment by brandonkelly** [comment]
Craft 4.4.6 is out now with that fix 🎉
