### ISSUE TITLE
Integrity constraint violations in userpermissions table when running migrations upgrading from 3.8.5 [4.x]: 

### ISSUE THREAD

**Issue by michaelfromtheoutfit** [craftcms/cms#12966]
### Description
I'm attempting to upgrade from 3.8.5 to the latest version of 4 and getting the following integrity constraint violations when upgrading to Craft 4.

```
Integrity constraint violation: 1062 Duplicate entry 'deleteassets:[UID REDACTED]' for key 'userpermissions.userpermissions_name_unq_idx'
```

This is happening when running the following migration: `m220123_213619_update_permissions`

### Steps to reproduce

1. Upgraded successfully to Craft 3.8.5 from 3.7.x
2. Upgraded all libraries in composer.json and ran composer update
3. Ran migrations, and it fails when getting to the `m220123_213619_update_permissions` migration

### Expected behavior
Expected migrations to complete without error.

### Actual behavior
Migrations caused an error.

### Craft CMS version

4.4.5

### PHP version

8.1

### Database type and version

MySQL 8.0.19

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out. I’m having trouble replicating this on a fresh Craft installation going from 3.7 > 3.8.5 > 4.4.5. 

Would you be able to send your `composer.lock` and database export from version 3.8.5 to support@craftcms.com so that we can dig deeper?

**Comment by michaelfromtheoutfit** [comment]
Thanks @i-just! Sent it your way.
