### ISSUE TITLE
[4.x]: UX issue in preview/slideout if a selectize dropdown is the last field

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#12976]
### Description

If a selectize dropdown field is the last field in live preview or slideout, the menu area is cut off.

![image](https://user-images.githubusercontent.com/60010597/227483774-90e0ba1e-c522-4120-bf69-7445ad2b066d.png)

### Steps to reproduce

1. Have a field layout long enough  to see scrollbars in live preview.
2. Have a dropdown field in last position.
3. Open menu, try to select an item with 'arrow down' key.

### Expected behavior

Menu area incl. selected item is fully visible.

### Actual behavior

See screenshot.

### Craft CMS version

4.4.5

### PHP version

8.1.13

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting. I submitted a PR to adjust this.

**Comment by brandonkelly** [comment]
Fixed for the next release via #12984.

**Comment by brandonkelly** [comment]
Craft 4.4.6 is out now with that fix 🎉
