### ISSUE TITLE
Add route/template details to Profiling Summary Report

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#1297]
> Created by: Russ Back (russ@rallyagency.co.uk) on 2015/03/24 08:31:58 +0000
> Votes at time of UserVoice import: 1

-----------------------------------

It would be useful if the console showed how a route was resolved (i.e. entry from a section, plugin, direct template directory/file match etc) and also what template files have been parsed to parse to produce the view you are currently looking at.

**Comment by brandonkelly** [comment]
This is now possible from the Routing section of the Debug toolbar in Craft 3.
