### ISSUE TITLE
[4.4.x]: Assets folder loading indicator not visible

### ISSUE THREAD

**Issue by jwb009** [craftcms/cms#12972]
### Description
When opening an asset folder on a slow connection, the loading indicator (spinning circle graphic) is often not visible if you have a long container. This is because the loading indicator is placed in the vertical middle of the container, which is often out of the viewport. As a result, you just see a transparent white background over the folders and files, and it appears that nothing is happening.

### Steps to reproduce

1. Open an asset folder which has many assets on a slow connection

### Expected behavior
The loading indicator should reside in the viewport regardless of how many assets are in the folder

### Actual behavior
The loading indicator is out of the viewport, as in this screenshot:
<img width="1203" alt="SCR-20230323-krva" src="https://user-images.githubusercontent.com/7241260/227277759-8b4b11c5-a3dc-43a7-b17f-567ffd46857f.png">

### Craft CMS version

4.4.X

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting. I submitted PRs to adjust this for Craft 3 and Craft 4.

**Comment by brandonkelly** [comment]
Fixed for the next Craft 3 and 4 releases, via #12993 and #12994.

**Comment by brandonkelly** [comment]
Craft 3.8.6 and 4.4.6 are out with that fix 🎉
