### ISSUE TITLE
[4.x]: UX Tab issue: No error indication for fields in tabs under tab dropdown.

### ISSUE THREAD

**Issue by myleshyson** [craftcms/cms#12971]
### Description
One of our content editors today reported not being able to save an entry. When we looked deeper into it, he had an error on a field or two but in tabs that were hidden by the tab dropdown (he was on a smaller screen). However because he couldn't immediately see where the error occurred he was confused as to why the entry wasn't saving.

What he sees when there is a field error.
![Screen Shot 2023-03-23 at 11 41 23 AM](https://user-images.githubusercontent.com/11747187/227263839-67c50d00-c7ac-4aab-9ecf-be652e91c2ed.png)

Where the errors actually are.
![Screenshot 2023-03-23 at 11 48 23 AM](https://user-images.githubusercontent.com/11747187/227263862-1dbb7fed-5e62-49bc-a508-6f771c6667b2.png)

I think adding _something_ to indicate where the error occurs, without having to hunt for it, would offer a benefit. Could be something as small as adding an alert icon to the menu button to show errors exist in the hidden tabs. Maybe something like this?

<img width="703" alt="Screenshot 2023-03-23 at 9 23 41 AM" src="https://user-images.githubusercontent.com/11747187/227269592-a43c935d-3057-4d19-9c98-2eedc57673b7.png">

Even better would be a high contrast list of errors at the top. When you have a lot of fields, or a lot of matrix blocks, it can be hard to find the red outline/text that contains the error. That's a pretty big UX change for errors though. 

What do ya'll think? 

### Steps to reproduce
1. Create enough tabs so that some are hidden in the tab dropdown.
2. Add fields to the tabs that are hidden.
3. Save the entry ensuring a validation error on one of the hidden tabs.
4. See a pop-up message that the entry couldn't be saved, but nothing more.

### Expected behavior
1. Some kind of visual indication as to where the errors might be located. 

### Actual behavior
1. No immediate indication to where the error occurred.

### Craft CMS version

4.4.3

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting. I have submitted PRs for Craft 3 and Craft 4 for this. 

We also plan to release an ‘errors summary’ feature soon (#12125), which should further improve the authoring experience in cases like this.

**Comment by brandonkelly** [comment]
Craft 3.8.6 and 4.4.6 are out with those improvements 🎉
