### ISSUE TITLE
[4.x]: Revision Notes and Last Edited By columns are displayed as empty string if the entry is disabled

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#12981]
### Description
When an entry is disabled, 'Revision Notes' and 'Last Edited By' columns are displayed as empty strings on entry index page.

### Craft CMS version

4.4.5

**Comment by i-just** [comment]
Hi, thanks for reporting. I raised a PR to address this.

**Comment by brandonkelly** [comment]
Fixed for the next Craft 3 and 4 releases via #12989.

**Comment by brandonkelly** [comment]
Craft 3.8.6 and 4.4.6 are out with that fix 🎉
