### ISSUE TITLE
[4.4.5]: ControlPanel loading times are slow 

### ISSUE THREAD

**Issue by LeoWie93** [craftcms/cms#12987]
### Description

After upgrading our CMS the navigation inside the ControlPanel became extremly slow.

Here are the loadtimes for the settings page:
![image](https://user-images.githubusercontent.com/29427760/227945813-dfacad24-9b59-4b10-892f-47209a70658b.png)

![image](https://user-images.githubusercontent.com/29427760/227945929-05516959-78b3-4ef7-b6b7-970cec7fea89.png)

Please tell me what further informationes you would need of me.

Thank you for your help and insight in advance

### Craft CMS version

4.4.5

### PHP version

8.2

### Operating system and version

Linux 6.1.21-1-lts

### Database type and version

MySQL 8.0.32

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

Element API
3.0.1.1

Redactor
3.0.4

Super Table
3.0.7

Typed link field
2.1.5

**Comment by brandonkelly** [comment]
What version were you updating from?

As a starting point, you can try running `composer dump-autoload -o`.

**Comment by LeoWie93** [comment]
## Local Dev
@brandonkelly we were upgrading from 3.7.x to 4.4.x. At first i did not pay much attention to this issue because my workstation is not the best and is getting slower.

These particular loading times made me author this issue but where improved after completely deleting and setting up this project again on my local machine.

## Environments
On other environments it is not that bad. But it is more an inconvenience.
For example, not loading of icons or the content of a redactor fields. It sometimes takes half a second for them to load which degrades the user experience.

![image](https://user-images.githubusercontent.com/29427760/229449230-69520c1f-2bf2-4343-a407-fe785ee828b6.png)


Other projects do not have this issue. Of course this project is much bigger with more entries.
I am not sure if my expectations are unreasonable or maybe the hardware is to weak. But all recommendations are met.

`composer dump-autload -o` did not really improve the loading time of js files etc.

**Comment by LeoWie93** [comment]
@brandonkelly thank you.
I've found the problem: 
![image](https://user-images.githubusercontent.com/29427760/229749804-1ec19fe1-c5e3-431d-b292-1829db67ee2b.png)

While upgrading to Craft 4 and using the `GeneralConfig` class this overwrite must have sneaked in and all the ressources where always newly generated.

Sorry for taking away your time with an issue like that. And we greatly appreciate your help.

**Comment by brandonkelly** [comment]
Glad you got it sorted!
