### ISSUE TITLE
[4.x]: Update on the vulnerability report.

### ISSUE THREAD

**Issue by retrymp3** [craftcms/cms#12982]
### Description

I reported a vulnerability on craft cms on huntr.dev. It was a day ago wanted to know wether there are any updates on this.
 My username on huntr is retrymp3.

**Comment by angrybrad** [comment]
Please read our security policy on how to report potential issues: https://github.com/craftcms/cms/security/policy

We don’t use or monitor reports from 3rd party security platforms, especially those we never signed up for and have asked to be removed from multiple times.

If you think you have a legitimate security report within scope, please report it via https://craftcms.com/contact or directly to support@craftcms.com.

**Comment by retrymp3** [comment]
I have reported it as per the security policy.
