### ISSUE TITLE
[4.x]: Loosing Field Values

### ISSUE THREAD

**Issue by DavidKabelitz** [craftcms/cms#12998]
### Description
I have an issue at a couple of Craft 4 projects. Both are different but maybe they belong.

Some fields loose randomly the default value. Most of them are DropDowns. It's needed to set the default value back on at the settings. Another problem is loosing data from fields while adding an entry. We have tabs with different fields, categories, tags, dropdowns and so on. While adding an entry we need to fill fields mostly two times because values are lost after the first attempt of adding the entry.

### Steps to reproduce

1.

### Craft CMS version

Craft Pro 4.4.5

### PHP version

8+

### Installed plugins and versions

-

**Comment by jonleverrier** [comment]
I've noticed strangeness with dropdown fields and default values since 4.4. Here's an issue I reported with a dropdown field and commerce https://github.com/craftcms/commerce/issues/3115#issuecomment-1470886328

**Comment by i-just** [comment]
@DavidKabelitz Hi, thanks for reaching out. I can’t replicate this behaviour, so I have a few questions.

> Some fields loose randomly the default value. Most of them are DropDowns. It's needed to set the default value back on at the settings.

- Is this happening in one environment or across multiple environments (e.g. when you push changed from dev to qa)?
- Could you let me know if you’re using project config? 
- Is it happening when you try to save, e.g. an entry or under different circumstances?
- Is there anything in the logs `storage/logs/web.log` that could suggest what’s happening?

> Another problem is loosing data from fields while adding an entry. We have tabs with different fields, categories, tags, dropdowns, etc. While adding an entry we need to fill fields mostly two times because values are lost after the first attempt of adding the entry.

- Do you see any errors after the first save?
- Is there anything in the logs `storage/logs/web.log` that could suggest what’s happening?
- Are there any errors in the console when this happens?

@jonleverrier I can’t replicate the issue you raised with Commerce on the CMS, and I can see it was fixed within Commerce.

**Comment by DavidKabelitz** [comment]
It's the same issue like @jonleverrier describes. yaml files are changing on it own and changed some drop downs to what he described: null or label N/A. I see lot's of yaml files are changed at different environments without a change or push from our side.

So it's happening randomly without a direct push before, usually we recognized it while adding or editing content. It feels it always related to the process of saving something and usually creating a new entry instead of editing a new one.

Related to the second one, yes always first save. Because those fields are mandatory fields it just displays the normal error message, nothing else.

**Comment by DavidKabelitz** [comment]
At the moment at all enviroments allowAdminChanges is on true.
Those are also not updated from 3 ones, we started them from scratch with Craft 4.

> Could you please share a list of plugins you’re using?

Sure here is the list, it's a lot because we created a website builder that is used for a couple of projects:

    "craftcms/cms": "4.4.5",
    "craftcms/redactor": "3.0.4",
    "nystudio107/craft-imageoptimize": "4.0.4",
    "nystudio107/craft-minify": "4.0.0-beta.2",
    "nystudio107/craft-retour": "4.1.11",
    "nystudio107/craft-seomatic": "4.0.22",
    "nystudio107/craft-similar": "4.0.0",
    "nystudio107/craft-typogrify": "4.0.1",
    "ostark/craft-async-queue": "3.1.0",
    "putyourlightson/craft-blitz": "4.4.3",
    "sebastianlenz/linkfield": "2.1.5",
    "utakka/redactor-anchors": "1.4.1",
    "vaersaagod/dospaces": "2.0.0",
    "verbb/formie": "2.0.25.1",
    "verbb/navigation": "2.0.17",
    "verbb/super-table": "3.0.7",
    "verbb/vizy": "2.0.12",
    "vlucas/phpdotenv": "v5.4.1",
    "wrav/oembed": "2.3.0",
    "yiisoft/yii2-redis": "~2.0.0"

**Comment by i-just** [comment]
Perfect, thank you!

The first thing you should do is review the steps here: https://craftcms.com/docs/4.x/project-config.html. 
For the project config to work as expected, you need `allowAdminChanges` to be set to `false` everywhere except your dev environment. If that doesn’t fix your issues, please let me know.

**Comment by DavidKabelitz** [comment]
ok but that makes not much sense for us, especially when we work local on a project to finish content. Even when this helps for Stage and Production, how will it remove the problems locally? After launching a project those are set to false, but this is just a workaround and not a solution. I don't get it.

**Comment by i-just** [comment]
OK, maybe I’m misunderstanding some of what you described. To simplify this issue, let’s discuss what’s happening with just the dev environment. 

You are experiencing the issues you described in the dev environment. 
The dropdown default values are randomly lost on saving an entry without changing the field (via project-config/apply or manual edit via settings > fields)?

**Comment by DavidKabelitz** [comment]
> You are experiencing the issues you described in the dev environment.
Yes at local and stage but both had "allowadminchanges" on, so not much difference between stage and dev.
Some projects we fully finish on local, so needs to work even at dev environment.

**Comment by i-just** [comment]
Could you please send your `composer.json`, `composer.lock`, `config/project` and database export to support@craftcms.com so we can try to replicate it and dig deeper?

**Comment by DavidKabelitz** [comment]
Sure i will do it, thanks for that

**Comment by DavidKabelitz** [comment]
@i-just  message was blocked of your email server cause of the config files.

**Comment by i-just** [comment]
Does it still get blocked if you zip it all up?

**Comment by DavidKabelitz** [comment]
yes tried it two times, all in zip files... i will use wetransfer ok?

**Comment by DavidKabelitz** [comment]
hm even wetransfer blocked the database dump to send...crazy...so it worked with two parts. Composer and Config files via wetransfer and db with email
