### ISSUE TITLE
[4.x]: Problems backing up database

### ISSUE THREAD

**Issue by pnpaes** [craftcms/cms#12996]
### What happened?

I am using docker for local development. It has 2 containers, 1 for linux+nginx and another for the database (maria:focal).
When I try to backup my database i have a problem with the  `table unknown: 'column-statistics'`.
Seems that the validation that checks for the support int he Schema.php file is not working with my setup.

In the vendor/craftcms/cms/src/db/mysql/Schema.php file, if I force the `$defaultArgs .= ' --skip-column-statistics';` on line 239, then the backup works just fine.

### Craft CMS version

4.4.5

### PHP version

8.1.7

### Operating system and version

Linux 5.15.49-linuxkit

### Database type and version

MariaDB 10.5.8

### Image driver and version

Imagick 3.6.0 (ImageMagick 6.9.10-23)

### Installed plugins and versions

-

**Comment by angrybrad** [comment]
Does your linux/nginx container have `mysqldump` installed, too? If so, and you run `mysqldump --version` what version does it return?

If not and you run the same command against your maria container, what does that return?

**Comment by pnpaes** [comment]
Sorry for the delay.
`mysqldump  Ver 10.19 Distrib 10.8.3-MariaDB, for debian-linux-gnu (aarch64)`

**Comment by angrybrad** [comment]
Which one of those is the container that Craft is running in?

**Comment by pnpaes** [comment]
I have a couple of local projects. Some have the first version and some have that second version. 
In both cases it fails, that is why i posted both versions. The same problems occurs...

**Comment by angrybrad** [comment]
The error happens when a database dump is made using a newer 8.x version of `mysqldump` against an older MySQL 5.x server.

https://serverfault.com/questions/912162/mysqldump-throws-unknown-table-column-statistics-in-information-schema-1109

Craft actually tries to be smart in this scenario (as you’ve discovered) and automatically adds the `--skip-column-statistics` flag when it thinks this is the case: https://github.com/craftcms/cms/blob/develop/src/db/mysql/Schema.php#L184-L206

But maybe there’s a bug in that logic when using MariaDB.

If you SSH into a box where you’re getting this error, then run:

    > php craft shell
    > \craft\helpers\App::normalizeVersion(\Craft::$app->getDb()->getSchema()->getServerVersion())

What does it return?

**Comment by pnpaes** [comment]
Adding this before your check `isMySQL5` seems to do the trick here (but notices that i had to adapt the regexp as well. the original one from the requirements.php file wasn't returning a match.
so I changed this `'/[\d.]+-([\d.]+)-\bMariaDB\b/'` to this `'/[\d.]+-\bMariaDB\b/'`.
My server version output is `10.8.3-MariaDB-1:10.8.3+maria~jammy`
`
        $reqCheck = new RequirementsChecker();
        $dbConfig = Craft::$app->getConfig()->getDb();
        $reqCheck->dsn = $dbConfig->dsn;
        $reqCheck->dbDriver = $dbConfig->dsn
            ? Db::parseDsn($dbConfig->dsn, 'driver')
            : Connection::DRIVER_MYSQL;
        $reqCheck->dbUser = $dbConfig->user;
        $reqCheck->dbPassword = $dbConfig->password;

        $conn = $reqCheck->getDbConnection();
        $isMaria = false;

        switch ($reqCheck->dbDriver) {
            case 'mysql':
                $version = $conn->getAttribute(PDO::ATTR_SERVER_VERSION);
                if (preg_match('/[\d.]+-\bMariaDB\b/', $version, $match)) {
                    $isMaria = true;
                }
                break;
        }

        // If the server is MariaDB, skip support for column-statistics
        if ($isMaria) {
            $defaultArgs .= ' --skip-column-statistics';
        // If the server is MySQL 5.x, we need to see what version of mysqldump is installed (5.x or 8.x)
        } elseif ($isMySQL5) {`

**Comment by pnpaes** [comment]
Hi @angrybrad,
Do you have an update on this?

**Comment by angrybrad** [comment]
@pnpaes Can you give https://github.com/craftcms/cms/pull/13095/ a whirl?

In my testing (against MySQL 5 and 8 and different MariaDB server versions vs. different `mysqldump` versions), I don't think your fix is a complete one.

**Comment by angrybrad** [comment]
@pnpaes correct the develop branch is currently 4.4.x.

**Comment by angrybrad** [comment]
@pnpaes did that PR end up working for you?

**Comment by brandonkelly** [comment]
Should be fixed via #13095.

**Comment by pnpaes** [comment]
@brandonkelly and @angrybrad 
Sorry for the delay, i had some short deadlines and didn't have time to follow up previously.
I tested it out and tit works as expected. Backing up the database on the same environment that I mentioned above works fine now.
Thank you for the support and quickly acting on the issue!

**Comment by brandonkelly** [comment]
Thanks for testing @pnpaes! We just released Craft 3.4.8 with the fix.

**Comment by pnpaes** [comment]
@brandonkelly
Project updated and tested.
Thank you!
