### ISSUE TITLE
Live Preview will show any disabled Matrix blocks

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#13]
#### Environment:

- Craft version: 3.x
- PHP version: 7.x
- Database driver & version: n/a
- Plugins & versions:

#### Description:

If you have a template that loops over Matrix blocks and some of those Matrix blocks are disabled, they will show up on a Live Preview request (but they won't show up on a normal, front-end request).

**Comment by brandonkelly** [comment]
Nothing we can really do about this. On Live Preview requests, the Matrix field is set to whatever blocks were posted in the request, as if they had been eager-loaded.

If it is undesired, the template would just need to be updated to check the blocks' statuses before displaying them.

There is an argument that it *could* be desired though - in the same way you would expect Live Preview to show you the entire entry you are editing, even if that entry is disabled.

**Comment by brandonkelly** [comment]
Ugh fine, I ended up talking myself into this.

**Comment by narration-sd** [comment]
Good man ;)
