### ISSUE TITLE
[3.x]: View is a button element rather than link, making it hard to share links in a headless setup

### ISSUE THREAD

**Issue by sgtpenguin** [craftcms/cms#13003]
### Description
I develop NextJs front ends using Craft headless.  As such, preview targets an api route in next with the `sourceUid` of the entry draft.  This route sets preview cookies for next and then redirects you to the url for the page you're requesting which can now request the correct draft data for the page.

This all works in general.  The problem is editors are unable to easily copy this preview link to share with others.  In the admin panel, "View" is a `<button>` element instead of an `<a>`.  To obtain the preview link they must click it and quickly copy the url to the api route in next (e.g. /api/preview?sourceUid=XXXXXXX) before being redirected.  

At least if it was an a tag instead of a button, I could instruct them to right click and copy the url.  I believe this would be more semantically correct markup as well as it is a link to another document and not an in page interaction.

### Craft CMS version

3.7.13

### Installed plugins and versions

-

**Comment by sgtpenguin** [comment]
Actually just checked a newer site I'm working on and it looks like in Craft 4 it is an `<a>`

**Comment by brandonkelly** [comment]
Yep :)
