### ISSUE TITLE
Make log redactions configurable

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#1301]
> Created by: Michael (michael@michaelrog.com) on 2015/03/11 15:06:07 +0000
> Votes at time of UserVoice import: 1

-----------------------------------

In Craft 3, the `Logging` helper includes a method that redacts passwords from log messages before they're filed.

However, this helper method only redacts password-y attributes that Craft knows/cares about.

It'd be great if the patterns were configurable so that we could add other attributes, such as sensitive environment variables, to the collection of things that should be redacted.

**Comment by michaelrog** [comment]
Bravo! 👏🏼
