### ISSUE TITLE
[4.x]: Inconsistant user experience / interface for asset related errors

### ISSUE THREAD

**Issue by WilliamIsted** [craftcms/cms#13024]
### Description

When using the assets control panel interface the user is given feedback by notifications appearing in the bottom left of the page. However, some actions which are prevented from completing by a returning error within the XHR causes a window alert to show instead.

### Steps to reproduce

**Scenario A:**
    1. For example: Set user permissions to disallow "Delete assets" to a volume.
    2. Upload a file to that volume within the control panel assets page.
    3. Upload the same file to that volume clicking "Cancel" when prompted that the file already exists.
    4. Receive window alert stating "User is not authorized to perform this action."
    5. Set user permissions to disallow "Save assets".
    6. Upload a file to that volume within the control panel assets page.
    8. Receive window alert stating "User is not authorized to perform this action."

![Screenshot 2023-03-31 at 23 38 35](https://user-images.githubusercontent.com/5830878/229244880-254960a8-4926-4ab5-b5f9-c4f2a32bc3ad.png)

**Scenario B:**
    1. Use business logic or other installed plugin (i.e. Remote Asset Protect) to prevent assets being created or moved by listening to `Asset::EVENT_BEFORE_SAVE`.
    2. Set `isValid` to false and throw `Exception` to return a message.
    3. Receive window alert stating error message thrown.

![Screenshot 2023-03-31 at 23 40 50](https://user-images.githubusercontent.com/5830878/229245132-1b27ee88-0a9d-4662-a3ca-6dec74df581e.png)

### Expected behavior

Scenario A and B should use the same notification UI as Scenario C and general success notifications.

### Actual behavior

**Scenario C:**
    1. Use business logic or other installed plugin (i.e. Remote Asset Protect) to prevent assets being created or moved by listening to `Asset::EVENT_BEFORE_DELETE`.
    2. Set `isValid` to false and throw `Exception` to return a message.
    3. Receive expected notification in bottom left of page with the error message thrown.

![Screenshot 2023-03-31 at 23 42 02](https://user-images.githubusercontent.com/5830878/229245302-d911a159-833d-4a80-813a-f57ffab2215d.png)

### Craft CMS version

4.4.5

### PHP version

8.1.13

### Installed plugins and versions

- Remote Asset Protect (2.0.2)

**Comment by brandonkelly** [comment]
Thanks for the nudge. All `alert()` calls have now been replaced with error notifications, for the next Craft 3 and 4 releases.

**Comment by brandonkelly** [comment]
Craft 3.8.6 and 4.4.6 are out with that change 🎉
