### ISSUE TITLE
[4.x]: Duplicated fields on Craft UI

### ISSUE THREAD

**Issue by gateszies** [craftcms/cms#13035]
### What happened?
Fields become randomly duplicated in Craft from time to time without a clear reason.

### Description
Over the past 6 months, we've been noticing that unique fields in Craft will randomly get duplicated without any specific reason. This causes field data to get wiped or unlinked. Typically the issue comes up when we're deploying large changes to the YAML files tracked in the project config. The deployed changes aren't related to the duplicated field in question - typically we'll be working on something else and notice that an unrelated field gets duplicated.

<img width="1465" alt="Screen Shot 2023-04-03 at 1 02 10 PM" src="https://user-images.githubusercontent.com/66807975/229591451-d569c223-ce71-4165-9060-21761eaf09df.png">

This field is _not_ duplicated in our YAML files. It seems something on the Craft end thinks that it exists twice.

### Steps to reproduce
We don't have a solid way to reproduce this behavior as we're unsure why it happens in the first place. However, we do have a database backup where this behavior can currently be seen. I'm happy to send over that DB backup and our composer files if that's helpful. 

Note that we are currently running on the latest Craft version, but because this issue is difficult to reproduce this DB backup is a snapshot of the environment we were running at the time (Craft 4.3.6.1).

### Expected behavior
There shouldn't be any duplicated fields with the same field ID in Craft. If for some reason a field gets duplicated due to a miscommunication between our DB and Craft, those duplicated fields should be pruned. 

### Actual behavior
You can see in the Field Settings that our field `Video Cover Image` is listed twice with the same field name and field ID. Deleting one deletes both of the fields.

### Craft CMS version

4.3.6.1

### PHP version

8.1.17

### Operating system and version

Linux 5.15.49-linuxkit

### Database type and version

MySQL 8.0.29

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-50)

### Installed plugins and versions

<img width="868" alt="Screen Shot 2023-04-03 at 1 11 12 PM" src="https://user-images.githubusercontent.com/66807975/229592080-fe9cb675-d391-49d2-9e13-bc8dbae13ef9.png">

**Comment by brandonkelly** [comment]
The only way this could happen that I’m aware of is if the project config YAML specified two identical fields, e.g. if a Git merge conflict wasn’t resolved properly. I know you said that’s not the case, but I don’t see how else it would happen. Craft would ordinarily prevent duplicate field names/handles during validation, but validation only occurs when fields are initially saved. Once it’s in the YAML, Craft trusts that it has already passed validation.

Couple things you could check to troubleshoot:

- Do all your fields in the `fields` table have unique `uid` values?
- Try running `php craft project-config/rebuild` to ensure your project config data is fully in sync with what’s in the database

And if you can come up with a way to reproduce it, such as when applying your latest project config changes to an old DB backup, we can definitely look into it from there.

**Comment by gateszies** [comment]
We are seeing two copies of the field in our database both tied to the same UID. Our YAML files include only one field and one unique UID. I also ran a `project-config/rebuild` but the duplicated field in the Craft field settings remained.

I should note that upon further digging, we found that the field has been duplicated in our database for several months. However, it hasn't appeared as duplicated in the Craft field settings until last week when I merged in a handful of project config changes. 

Do you have any recommendations for fixing the field being duplicated in Craft? Let me know if there's any additional information that would be helpful.

**Comment by brandonkelly** [comment]
Do the fields have the same handle as well? Do they both have content that is needed, or would it be safe to delete one of them?

**Comment by gateszies** [comment]
Yeah, they have the same handle and UID. We have a large amount of content contained in the field, but we've already lost it once so could potentially lose it again if necessary. Note that deleting one of the fields will delete both of them.

**Comment by brandonkelly** [comment]
Yeah I think your best bet would be to delete the extra row directly from the `fields` table.

Once you do that, run the following command, which _should_ get all your field layouts back in order in case any were effected:

```sh
php craft project-config/apply --force
```

**Comment by gateszies** [comment]
With the instructions above we have successfully removed the duplicated field. However, we're still curious about how the bug happened in the first place. We've run into this a few times now - a field being duplicated in the DB but not in the YAML files. 

Any thoughts or recommendations for preventing this from happening in the future?

**Comment by brandonkelly** [comment]
I’m completely stumped on how that would happen, unfortunately. Do you have a staging server? If so it might make sense to start deploying changes there as a starting point, and verify there aren’t any duplicated fields before deploying to production.

Either way, if you keep an eye on it and see it happen again, please email a database backup over to support@craftcms.com along with the deployed project config changes, and we should be able to look into it further from there.
