### ISSUE TITLE
[4.x]: Missing 'Delete' translation for title in x icon in control panel

### ISSUE THREAD

**Issue by simplegr** [craftcms/cms#13030]
### Description

In control panel pages such as settings/fields, settings/sections, settings/globals, settings/categories, settings/filesystems, settings/assets the translation for x button is missing. `Craft.translations["app"]["Delete"]` is there if you inspect view source, but translation it's missing in control panel.

### Expected behavior

x icon title in control panel should be translated.

### Actual behavior
x icon title in control panel is not translated.

### Craft CMS version

4.4.5

### PHP version

8.1

### Operating system and version

Windows

### Database type and version

MySQL

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Fixed for the next release via #13032.

**Comment by brandonkelly** [comment]
Craft 4.4.6 is out now with that fix 🎉
