### ISSUE TITLE
Settings link missing on mobile screens

### ISSUE THREAD

**Issue by vitalijalbu** [craftcms/cms#13033]
### Description

Settings link missing on mobile screens
![IMG_9318](https://user-images.githubusercontent.com/40239902/229558451-a82d3f95-565e-4aca-bb3d-73d599860f20.png)

### Steps to reproduce

1.

### Craft CMS version

4.4

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
`allowAdminChanges`?
