### ISSUE TITLE
[3.x]: License "nag" shows in development environments

### ISSUE THREAD

**Issue by MattWilcox** [craftcms/cms#13042]
### What happened?

The "nags" that should be showing on live are also showing on known dev domains (*.ddev.site).

- Have cleared all caches
- Have ensured that the .env is set to `ENVIRONMENT=dev`

<img width="704" alt="Screenshot 2023-04-04 at 14 19 26" src="https://user-images.githubusercontent.com/814039/229808933-e80b3cb9-503f-4aa4-9da5-6af489b292c0.png">

Just makes working on updates prior to go-live (and subsequent purchase of renewals) a bit frustrating. Especially as these styles are done via inline HTML property values, which means they can not be overridden by user stylesheets.

### Craft CMS version

3.8.5

### PHP version

7.4

**Comment by MattWilcox** [comment]
Added context:

We have a live site that's got some updates pending but we are also doing new dev work - so I've just pulled the database down from live, got it running locally, and done updates on my local.

We aren't likely to renew the licenses until after the work is done and the client's ready to go live.

**Comment by brandonkelly** [comment]
Dev environments have never allowed running an updated Craft/plugin version beyond what you’re licensed to use. Once the licenses have been purchased (and in theory the site has gone live), if a license expires and you want to update it, you’re expected to pay for the renewal, even if it’s only being used in development.

> Especially as these styles are done via inline HTML property values, which means they can not be overridden by user stylesheets.

That was the point!

**Comment by MattWilcox** [comment]
But clients don't want to pay for a renewal before they need to. The license already paid for covers use of the existing versions indefinitely, and that's what they want to do. Renewing only when they actually need to pay for the new versions - which they only need to when new features go live.

**Comment by brandonkelly** [comment]
To be clear, we are now debating the _policy_ as opposed to a specific UI feature.

The _policy_ is that license trials are allowed when first installed, up until they’ve been deployed to production. This is specifically meant to be an _evaluation_ feature; not a general hall pass to do whatever you want locally in perpetuity.

My understanding is that you think Craft/plugin licenses and renewals do not warrant a payment until they are _client-facing_. I disagree for a couple reasons:

- Several commercial plugins have no client interaction whatsoever, such as Blitz, Imager X, and ImageOptimize. I hope we can agree they warrant payment regardless.
- Your client is gaining value out of a license update/renewal even if it’s only updated locally: they get a **smoother launch**. By updating software locally, you are able to test it,  implement code that takes advantage of its new features, and get support from the developer while doing so, all of which will help you avoid last-minute deployment snags and unforseen bugs in production.

But let’s just say we decide to change the policy: only pay for things that are client-facing(-ish). By that rule of thumb, we would start disallowing licenses on staging environments, as they are very likely to be client-facing. Guessing that would not be very well-received.

> However unlikely that is for any real world end user.

Happens much more frequently then you’d think, and usually via the CP CSS plugin (which gets deployed to production for all users) as opposed to a browser-specific override.
