### ISSUE TITLE
[4.x]: Update yiisoft/yii2-debug from ~2.1.19.0 to ~2.1.20

### ISSUE THREAD

**Issue by ddnetters** [craftcms/cms#13058]
### Description
Please see: https://github.com/sebastian-lenz/craft-linkfield/issues/225

Can we bump `yiisoft/yii2-debug` to `~2.1.20`? It's a minor update but it contains a bug fix that would resolve the aforementioned issue.

### Craft CMS version

4.x

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Done for the next release!

**Comment by brandonkelly** [comment]
Craft 4.4.7 is out now with that update.
