### ISSUE TITLE
[4.x]: Matrix fields - the minimum number blocks behaviour has changed in 4.4

### ISSUE THREAD

**Issue by sunscreem** [craftcms/cms#13059]
### Description

In Craft 4.3, when you have a matrix with a minimum of, say, 2 blocks, you could add the two blocks, set them to disabled, and still save the entry. In Craft 4.4, if the blocks are disabled, you can no longer save. I this was a bug in Craft 4.3 I think the fix is possibly a breaking change in 4.4.

### Steps to reproduce

1. Create a matrix field with min of 2 blocks.
2. Add to an entry.
3. Go to that entry and add two blocks.
4. Disable one or both blocks and try to save:

### Expected behaviour

The entry would pass validation and save.

### Actual behaviour

You now get an error:

![image](https://user-images.githubusercontent.com/7523595/230454736-55919ac0-9f59-4bb7-aeee-09716e23c95e.png)

### Craft CMS version

4.4.6

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
I was able to reproduce this same bug in Craft 3 as well, so I’ve fixed it for the next Craft 3 and 4 releases.

**Comment by brandonkelly** [comment]
Craft 3.8.7 and 4.4.7 are out now with this fix. Thanks for reporting!
