### ISSUE TITLE
[4.x]: Can't drag and drop in entryTypes panel

### ISSUE THREAD

**Issue by jan-dh** [craftcms/cms#13062]
### Description
When accessing the Entry types view (where you drag & drop the fields to your UI) for a blogs channel on

`https://.../admin/settings/sections/2/entrytypes/....`

I'm confronted with a jquery error:

`Uncaught TypeError: this.designer.config.tabs.find is not a function`

I'm unable to drag and drop anything for this specific section.

### Steps to reproduce

1. I'm only having this on a channel with the handle `blog` with an entry type `blogPost`

### Expected behavior

To have drag and drop enabled

### Actual behavior

Can't move anything.

### Craft CMS version

4.4.6.1

### PHP version

8.1.11

### Operating system and version

MacOS 13.0.1

### Database type and version

mariadb:10.3

### Installed plugins and versions

Error log: 

```
Uncaught TypeError: this.designer.config.tabs.find is not a function
    at get config [as config] (FieldLayoutDesigner.js:495:44)
    at get config [as config] (FieldLayoutDesigner.js:780:27)
    at s.constructor.initUi (FieldLayoutDesigner.js:675:52)
    at s.constructor.init (FieldLayoutDesigner.js:666:10)
    at s.constructor.constructor (Base.js:20:15)
    at s.constructor (Base.js:32:21)
    at new s.constructor (Base.js:32:21)
    at s.constructor.initElement (FieldLayoutDesigner.js:484:12)
    at s.constructor.init (FieldLayoutDesigner.js:302:12)
    at s.constructor.constructor (Base.js:20:15)
    ```

**Comment by brandonkelly** [comment]
I’m unable to reproduce this, even after manually editing an entry type’s field layout to remove the `tabs` array and applying the change.

Any chance you can send in your Composer files and a database backup to support@craftcms.com?

**Comment by jan-dh** [comment]
Sent! Thought it was a browser thing so tried it out in several browers, all the same results, cache clear (browser & CMS also didn't help).

**Comment by brandonkelly** [comment]
Got to the bottom of this. It occurred if you had a tab that only contained one field, and that field was deleted. We weren’t filtering that tab out properly when initializing the field layout designer.

Fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 4.4.7 is out now with that fix!
