### ISSUE TITLE
Issue with X-Robots-Tag response header set to none [3.x]: 

### ISSUE THREAD

**Issue by asethii** [craftcms/cms#13063]
### Description

We are running craft 3.7 and all of our pages' response header include x-robots-tag: none. We are trying to find out how to remove this, or set it to all, so our page can get indexed by crawlers.

In general.php, we have disallowRobots => geten('DISALLOW_ROBOTS'). And DISALLOW_ROBOTS is set to false

Please let me know if you need more information

### Steps to reproduce

1. Load any front end craft page
2. Observe response header.
3. look for X-Robots-Tag:none

### Expected behavior

1. X-Tobots-Tag value should not appear, or be set to "all"

### Actual behavior
Header response value is X-Robots-Tag:none

### Craft CMS version

3.7

### PHP version

7.4.16

### Operating system and version

entOS 7

### Database type and version

MySQL version 8.0.29

### Installed plugins and versions

- SEO version 3.7.4 (Ether Creative)
the only customization on this plugin, is under the robots tab, which is
{# Sitemap URL #}
Sitemap: {{ url(seo.sitemapName ~ '.xml') }}

User-agent: *
Disallow: /cpresources/

**Comment by brandonkelly** [comment]
This is almost certainly being added by your Ether SEO plugin.

Make sure you have an `ENVIRONMENT` environment variable defined, and set to `production`.

**Comment by tgupta-adc** [comment]
Our .env file is setting it to production. We have this line added to .env ENVIRONMENT="production"

**Comment by asethii** [comment]
To add to what @tgupta-adc has said, we do have the environment variable defined. We also tried disabling the SEO plugin in our test environment to see if that would resolve the issue, with no luck.

Is there any other information I can give to help troubleshoot this issue?

**Comment by brandonkelly** [comment]
Is the browser cached with Cloudflare, etc., which could be serving old content?

**Comment by tgupta-adc** [comment]
No, we cleared cache couple of times. Also we have been using Craft for more than 2 years and it has always been set to none.

**Comment by brandonkelly** [comment]
What happens if you remove the `disallowRobots` config setting in `config/general.php`?

**Comment by brandonkelly** [comment]
> DISALLOW_ROBOTS is set to false

Do you mean like this?

```sh
DISALLOW_ROBOTS=false
```

That would just result in it getting set to the string `'false'` in Craft 3, as `getenv()` doesn’t have any special handling for `false` values.

Which means this condition:

https://github.com/craftcms/cms/blob/d26195509ce043426f55753e38c91535965525d0/src/web/Application.php#L184-L191

would end up _passing_, because it would effectively be:

```php
if (
    'false' ||
    // ...
```

Which would equate to `true`.

You should either not be setting `DISALLOW_ROBOTS` in `.env`, or setting it to `0` or an empty string:

```sh
DISALLOW_ROBOTS=0
```

In Craft 4, however, `false` is supported, but only if you pull in the environment variable via `craft\helpers\App::env()`.

```php
'disallowRobots' => craft\helpers\App::env('DISALLOW_ROBOTS'),
```

**Comment by brandonkelly** [comment]
In case that was the culprit, I’ve gone ahead and made Craft more defensive of those values for the next Craft 3 release (b4c6f95513db0396a5ff38f24ad8f14cac74b206).

**Comment by brandonkelly** [comment]
Should go out tomorrow! You can update earlier by changing your `craftcms/cms` requirement in `composer.json` to:

`dev-develop as 4.4.6.1`

then run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.8.6 is out now. Going to close this, assuming it was in fact the issue.
