### ISSUE TITLE
[4.x]: folder not visible on scroll in "move to" modal folders nav 

### ISSUE THREAD

**Issue by yingban** [craftcms/cms#13074]
### Description
Hi,

on one of our 4.4.x websites, we have many assets folders, more than 38.
In the "move to" modal, the last folder is not fully visible on scroll. 

On the screenshot below, the scroll is at the maximum value.
<img width="1590" alt="Screenshot 2023-04-11 at 20 19 06" src="https://user-images.githubusercontent.com/3421450/231255147-0e4a323a-32e7-47e6-982b-32492476bdfc.png">

### Steps to reproduce

1. Create 39 assets folders
2. Try to move an asset to the 39th folder or more

### Actual behavior

39th folder is not fully visible

### Craft CMS version

4.4.5

### PHP version

8.0.28

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 3.8.7 and 4.4.7 are out now with a fix for this.
