### ISSUE TITLE
Revert entry to Version failing

### ISSUE THREAD

**Issue by JeremyEnvoy** [craftcms/cms#1307]
### Description
When reverting an entry in the admin, it causes the error `No element exists with the ID '3'`

The database is storing the entry types in the elements table as `craft\elements\Entry`. Upon loading the revision the Element object provided is of class type `craft\models\EntryVersion`. 

The error originates from the code around line 380 in services/Elements.php, specifically

`
$elementRecord = ElementRecord::findOne([
                    'id' => $element->id,
                    'type' => get_class($element)
                ]);
`

### Steps to reproduce

1. Create section with entry type
2. Save it multiple times to create different versions
3. Select an old version from dropdown
4. Click `Revert entry to this version`

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Fixed for next release, thanks!
