### ISSUE TITLE
[4.x]: The uploader name overflows in asset modal windows

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#13099]
### Description

When opening a model window for a related asset, the uploader's name or email address overflows and is cut off by the window if it is longer than the window:

![Screenshot 2023-04-19 at 15 09 12](https://user-images.githubusercontent.com/10146880/233085664-817eda5f-d49b-478f-82dc-becc67aee49c.png)

This happens with long email addresses (if the account doesn't have a name), but also with very long names. If the name includes spaces, it can break into a new line, but a single word overflows.

### Steps to reproduce

1. Set the name of an account to a long string without spaces.
2. Open an asset uploaded by that account in a modal window.

### Expected behavior

The email should either be forced to break into a new line, or be cut off in a way that looks more intentional – for example, by using `text-overflow: ellipsis;`.

### Craft CMS version

4.4.4

### PHP version

8.2

**Comment by brandonkelly** [comment]
This is now fixed for the next Craft 3 and 4 releases. Thanks again!

**Comment by brandonkelly** [comment]
Craft 3.8.8 and 4.4.8 are out with the fix for this.
