### ISSUE TITLE
[3.x][4.x]: Default Asset Location allows incompatible assets

### ISSUE THREAD

**Issue by pixelmachine** [craftcms/cms#13092]
### Description

I have an asset volume for Video files and an asset volume for Images each with format-specific fields. Images have an Alt and maybe a caption. Videos have metadata fields and UI settings for controls. Etc.

I have a single Media asset field that allows Images or videos to be added to the page. The field settings _require_ a default asset location to be set meaning I have to choose Images _or_ Videos to be the default.

If the opposite type of media is dragged to the page it will have the wrong fields available and will be missing certain metadata that is required and in the case of video added automatically after upload. And obviously it will be in the wrong Volume though that's easy to deal with.

There are obviously workarounds (different fields for different formats and so on) but those come with significant additional overhead. 

### Steps to reproduce

1. Setup at least two volumes with different requirements and fields
2. Setup an asset field that allows uploads to both volumes
3. Drag and drop a type of file that is not supposed to for the Default Asset Location
4. Media is assigned incorrect data

### Expected behavior

Assets are uploaded to the correct location, or not allowed to be dragged and dropped.

### Possible options?

Simple: 
Allow a setting for the Default Asset Location of None which would disable the drag and drop 

Complex:
Allow the Default Asset Location setting to be controlled with Twig rules like the path, or perhaps (Craft 4 only I guess) with condition builder (based on file type or whatever).

Other:
Allow volumes to restrict which type of files can be uploaded to them just like an asset field can? This is probably a separate feature request but it would also stop and dragged and dropped assets from being uploaded to the incorrect volume.

### Craft CMS version

3.8.7, 4.4.7.1

### PHP version

8.1

Vaguely related to #13072

**Comment by i-just** [comment]
Hi, thanks for getting in touch. You can disable uploading files directly into the field (drag and drop) if you uncheck the “Allow uploading directly to the field” for your Assets field. I hope this helps!

**Comment by pixelmachine** [comment]
I can't believe I've never spotted that setting @i-just !

Putting that perfect workaround aside is there anything on the roadmap (like my suggestions) that would allow drag and drop to be used with different volumes/file types?

> Allow the Default Asset Location setting to be controlled with Twig rules like the path, or perhaps (Craft 4 only I guess) with condition builder (based on file type or whatever).
> 
> Allow volumes to restrict which type of files can be uploaded to them just like an asset field can? This is probably a separate feature request but it would also stop and dragged and dropped assets from being uploaded to the incorrect volume.

**Comment by i-just** [comment]
We’ll discuss this internally, and I’ll update again afterwards.

**Comment by i-just** [comment]
We’ve discussed this internally, and at the moment, there are no plans for what you suggested. You can create a discussion, though, and we’ll assess the interest in such a feature.
