### ISSUE TITLE
[4.x]: Queue handled event fires before release

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#13096]
### Description

When a queue job is executed (or errored), the EVENT_AFTER_EXEC or EVENT_AFTER_ERROR event fires. But the job only gets released after firing these. So when listening to these events, there is always a job left in the queue that is about to be deleted. I'd rather have these events fired after the job has been released, so the status of the queue is more actual.

### Steps to reproduce

See function craft\queue\Queue::executeJob:

```php
        if ($this->handleMessage($payload['id'], $payload['job'], $payload['ttr'], $payload['attempt'])) {
            $this->release($payload['id']);
        }
```

### Expected behavior

Job gets released, then event gets fired

### Actual behavior

Event gets fired, job is not released yet

### Craft CMS version

4

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Just added a new `EVENT_AFTER_EXEC_AND_RELEASE` event there, after a successfully-executed job is released.

**Comment by brandonkelly** [comment]
Craft 4.4.8 is out with that new event.
