### ISSUE TITLE
[4.4.7.1]: Assets - Moving folder into itself deletes that folder and all assets

### ISSUE THREAD

**Issue by gregorterrill** [craftcms/cms#13118]
### Description
I was trying to move a bunch of photos into a subfolder and misclicked the top breadcrumb dropdown instead of using the "Move" from the gear dropdown at the bottom. I was doing this quickly but ended up accidentally deleting about 30 photos by moving the folder into itself. This is a very destructive action and one that it seems like it would be very easy for any client to do (especially because the gear dropdown you are supposed to use to move things is not labeled).

### Steps to reproduce

1. Create a subfolder called "test"
2. Upload two images into the "test" folder
3. From the dropdown in the breadcrumb next to "test", click "Move folder"
7. Select the greyed out "test" folder in the modal
8. Click "Move"
9. The "test" folder and any images within are deleted with no way to recover

### Expected behavior
Should see the "The folder cannot be found" error message like what happens when you select multiple images and a folder, then use the gear dropdown to try to move into that same folder (although this still deletes the folder, which I feel like maybe it shouldn't?).

### Actual behavior
The "test" folder and any images within are deleted with no way to recover.

### Craft CMS version

4.4.7.1

### PHP version

8.1.5

### Database type and version

MySQL 5.7.37

### Installed plugins and versions

CKEditor 3.2.1
Element API 3.0.1.1

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for tomorrow’s Craft 3 and 4 releases.

**Comment by brandonkelly** [comment]
Craft 3.8.8 and 4.4.8 are out with that fix. Thanks again!
