### ISSUE TITLE
Creating a new user triggers a TypeError exception: Argument 1 passed to craft\services\Users::getUserPreferences() must be of the type integer, null given

### ISSUE THREAD

**Issue by tijsvanerp** [craftcms/cms#1311]
### Description
Creating a new user triggers a TypeError exception:

```
TypeError

Argument 1 passed to craft\services\Users::getUserPreferences() must be of the type integer, null given, called in /home/forge/default/vendor/craftcms/cms/src/elements/User.php on line 1081
1. in /home/forge/default/vendor/craftcms/cms/src/services/Users.php at line 292
2. in /home/forge/default/vendor/craftcms/cms/src/elements/User.php at line 1081 – craft\services\Users::getUserPreferences(null)
3. in /home/forge/default/vendor/craftcms/cms/src/elements/User.php at line 1097 – craft\elements\User::getPreferences()
4. in /home/forge/default/vendor/craftcms/cms/src/elements/User.php at line 1109 – craft\elements\User::getPreference('language')
5. in /home/forge/default/vendor/twig/twig/lib/Twig/Extension/Core.php at line 1552 – craft\elements\User::getPreferredLanguage()
6. in /home/forge/default/vendor/craftcms/cms/src/helpers/Template.php at line 68 – twig_get_attribute(craft\web\twig\Environment, Twig_Source, craft\elements\User, 'getPreferredLanguage', ...)
```

### Steps to reproduce

1. Enable pro version
2. Go to users and create a new user

### Additional info

- PHP version: 7.1.1-1+deb.sury.org\~xenial+1
- Database driver & version: MySQL 5.7.17-0ubuntu0.16.04.1
- Plugins & versions: none

**Comment by aaron-envoy** [comment]
For what it's worth, I get a different error with these steps, but only if I do not select permissions while creating the user.
`Argument 2 passed to craft\services\UserPermissions::saveUserPermissions() must be of the type array, string given, called in /var/www/craft-test/vendor/craftcms/cms/src/controllers/UsersController.php on line 1704`

### Steps to reproduce

1. Enable pro version
2. Go to users and create a new user without selecting any permissions

### Additional info

- Craft version: 3.0.0-beta.1
- PHP version: 7.0.8 (MAMP PRO)
- Database driver & version: MySQL 5.5.42
- Plugins & versions: None

**Comment by apicht** [comment]
For what it's worth, I get a different error with these steps, but only if I do not select permissions while creating the user.
`Argument 2 passed to craft\services\UserPermissions::saveUserPermissions() must be of the type array, string given, called in /var/www/craft-test/vendor/craftcms/cms/src/controllers/UsersController.php on line 1704`

### Steps to reproduce

1. Enable pro version
2. Go to users and create a new user without selecting any permissions

### Additional info

- Craft version: 3.0.0-beta.1
- PHP version: 7.0.8 (MAMP PRO)
- Database driver & version: MySQL 5.5.42
- Plugins & versions: None
