### ISSUE TITLE
[4.x]: 'Delete element for this site' removes the element for all sites in some conditions

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#13116]
### Description
'Delete element for this site' removes the element for all sites if all the other remaining sites are disabled or draft

It seems where the Craft ['Separate the multi-site elements from the single-site elements'](https://github.com/craftcms/cms/blob/cdb88c1e082b53d0101f3a9b5190c9b6aedf027e/src/services/Elements.php#L2079), it doesn't check for disabled items and drafts with `->status(null)->drafts(null)`, so Craft thinks it is single-site element and delete it completely if all other sites are disabled or drafts.
Another problem, i think, it is [$firstElement::find()->id($multiSiteElementIds)->site('*')->unique()](https://github.com/craftcms/cms/blob/cdb88c1e082b53d0101f3a9b5190c9b6aedf027e/src/services/Elements.php#L2117) , where the Craft doesn't check disabled and drafts again, when try to create query and pass for resaving element and cache invalidation.

### Craft CMS version

4.4.7.1

**Comment by brandonkelly** [comment]
Thank you for reporting that! Fixed now for the next release.

**Comment by brandonkelly** [comment]
Craft 4.4.8 is out with that fix. Thanks again!
