### ISSUE TITLE
[4.4.7.1]: Can't disard stuck asset index process

### ISSUE THREAD

**Issue by RyanRoberts** [craftcms/cms#13114]
### Description
I ran "Update asset indexes", it got to 72 of 74 assets and then stalled. The Discard button does nothing. https://media.yep.digital/jQxwpdBj

When I view the debug bar I notice the POST requests are constantly increasing: https://media.yep.digital/KjzcFPrz

If I try to view the error logs in here I get an error: https://media.yep.digital/33hCtvyL

I've restarted the server itself multiple times, also mysql, nginx, php, and re-run the asset indexing on the CLI which completes happily.

Assets are on DigitalOcean Spaces and I'm using the DigitalOcean Spaces Filesystem plugin (v2.0.0).

### Steps to reproduce

1. Run "Update asset indexes"
2. Wait

### Expected behavior

Either to complete the indexing or allow me to discard.

### Actual behavior

Can't discard.

### Craft CMS version

4.4.7.1

### Installed plugins and versions

https://media.yep.digital/9t33DJj2

**Comment by i-just** [comment]
Hi, thanks for reaching out. When this happens, are there any errors in the logs (storage/logs/web.log) or in the console?

**Comment by RyanRoberts** [comment]
It's since cleared, I don't know what fixed it but I remember there were no relevant errors in the browser console.

I'm struggling to find anything specific I can pull out of the various logs so I'll clear them and try to replicate the issue this evening and report back.

For what it's worth someone else had the same problem with what appears to be a very similar setup: https://craftcms.stackexchange.com/questions/40394/asset-indexing-is-frozen-and-i-cant-discard-the-task

**Comment by RyanRoberts** [comment]
Sooo, I can't replicate the issue again 🤦

**Comment by i-just** [comment]
I’m glad it’s all working now. If you run into it again and can replicate it, please get in touch.
