### ISSUE TITLE
Imagemagick required for image edits

### ISSUE THREAD

**Issue by thechrisroberts** [craftcms/cms#1312]
### Description
Attempting to edit an image fails in a vagrant box with gd but not imagemagick installed, despite requirements showing either one as an option. Relevant log message:

2017-02-01 08:16:55 [192.168.0.1][1][2mc0jja49fkabbegdtudos6dl4][error][Error] Error: Call to undefined method Imagine\Gd\Image::getImagick() in /home/hive/craft3/vendor/craftcms/cms/src/image/Raster.php:389
Stack trace:
#0 /home/hive/craft3/vendor/craftcms/cms/src/controllers/AssetsController.php(684): craft\image\Raster->rotate(0)

### Steps to reproduce

1. Install Craft 3 beta in an environment with gd but not imagemagick
2. Attempt to save an edited image

### Additional info

- Craft version: 3 Beta
- PHP version: 7.0
- Database driver & version: MySQL 5.6
- Plugins & versions: None, clean Craft 3 install

**Comment by andris-sevcenko** [comment]
All set for the next release.
