### ISSUE TITLE
[4.x]: ® character is being stripped from the entry title on save

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#13125]
### Description

We have a client website based around medical devices in the US. On each entry title, the product (not commerce)

Sometime between the 31st January (an entry was saved on this date appearing correctly) and the 18th April (the next time it was saved, with the ® symbol gone), something has changed that means entries now strip out the ® symbol from the entry title when you save it. I can add the symbol to the title, save the entry, it saves correctly, and it strips out the ® symbol at the same time.

Any ideas?

### Steps to reproduce

1. Save an entry with ® in the title
2. It saves, and removes the symbol

### Expected behavior
Entry titles should keep the ® symbol when they are saved

### Actual behavior
The ® symbol is stripped out on save

### Craft CMS version

4.4.1

### PHP version

8.0.28

### Operating system and version

Linux 5.4.0-117-generic (Ubuntu 20.04)

### Database type and version

MySQL 8.0.32

### Image driver and version

GD 8.0.28

### Installed plugins and versions

![image](https://user-images.githubusercontent.com/1250017/234667968-b389b01f-6ea0-4461-a2bd-9fa5471e61ec.png)

**Comment by brandonkelly** [comment]
Just tested this locally and am unable to reproduce. Can you try disabling those plugins, and remove any modules you may have installed?

**Comment by darylknight** [comment]
Hi Brandon,

Not sure which version of Craft you tested with (I noted this was 4.4.1 in the issue), but it looks like this could very well have been https://github.com/craftcms/cms/issues/12905 which was fixed in 4.4.3. I updated Craft this morning, and the issue is resolved. Thanks :)

**Comment by brandonkelly** [comment]
Oh, yeah, forgot about that. Gotta be the same bug!
