### ISSUE TITLE
[4.4]: Focus stays on related elements

### ISSUE THREAD

**Issue by linusschwab** [craftcms/cms#13123]
### Description

When you select a related element or an asset, you can't unselect it anymore. Even if you click next to it, the focus stays. This is only a minor visual thing, but still looks like a bug. It happens since the 4.4 update.

![image](https://user-images.githubusercontent.com/5487502/234542431-99df9eb2-5774-4f32-96bb-1ed1bba875c6.png)

### Steps to reproduce

1. Add an element to a related entry or asset field
2. Click on it to focus it

### Expected behavior

The focus/selection can be removed by clicking on it again or by clicking outsite of it.

### Actual behavior

The focus stays and can no longer be removed, without reloading the page.

### Craft CMS version

4.4.8

### PHP version

8.1.15

### Operating system and version

Linux 5.10.47-linuxkit

### Database type and version

MySQL 8.0.23

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-52)

### Installed plugins and versions

- Element API 3.0.1.1
- Google Cloud Storage 2.0.0
- Redactor 3.0.4
- Super Table 3.0.8.1

**Comment by brandonkelly** [comment]
The only thing that changed in 4.4 here is the styling – previously the selection style was much more subtle.

You can deselect an element by Command/Ctrl-clicking on it or pressing <kbd>Space</kbd> while the element is focused.

I’ve just tweaked this for Craft 4.5 though – going forward, when you click outside of a relational field, any element selections within the field will be deselected. (c5094894440d3649200653675232b006302a6044)

**Comment by brandonkelly** [comment]
Craft 4.5.0 is out now with that change. Thanks for bringing it up!
