### ISSUE TITLE
[3.x]: Categories Field Not Returning Selected Categories

### ISSUE THREAD

**Issue by mortscode** [craftcms/cms#13122]
### Description
I know Categories are on their way out, but recently I've noticed that using `entry.categoryField.all()` stopped returning my long-standing categories. We use categories to organize our recipes into categories (dinner, breakfast, low-carb, gluten free, etc), so this is a very important piece of our puzzle.

I have figured out a work around for the time being, but I never had to do it before.

### Steps to reproduce

1. On an entry with a Categories Field, select some categories and Save.
2. In the template, render the selected categories using `entry.categoryFieldHandle.all()` and then use a `for` loop to display the categories.

### Expected behavior
The categories would render on the frontend of the website.

### Actual behavior
The `entry.categoryFieldHandle.all()` query returns an empty array.

### Workaround
I noticed that `entry.title` and `entry.id` return the correct values. I've found that if I reference the entry by id, then it works as expected:
```
{% set entryRef = craft.entries.id(entry.id).one() %}
<ul>
  {% for cat in entryRef.categoryFieldHandle.all() %}
      <li>{{ cat.title }}</li>
  {% endfor %}
</ul>
```

### Craft CMS version

3.8.8

### PHP version

8

### Installed plugins and versions

- "craftcms/cms": "3.8.8",
- "vlucas/phpdotenv": "^2.4.0",
- "clubstudioltd/craft-asset-rev": "6.0.2",
- "craftcms/redactor": "2.10.12",
- "sebastianlenz/linkfield": "1.0.25",
- "craftcms/contact-form": "2.5.2",
- "craftcms/contact-form-honeypot": "1.0.3",
- "nystudio107/craft-seomatic": "3.4.52",
- "craftcms/postmark": "2.1.0",
- "craftcms/element-api": "2.8.6.1",
- "servd/craft-asset-storage": "2.8.6",
- "mortscode/feedback": "^1.0",
- "nystudio107/craft-retour": "3.2.10"

**Comment by i-just** [comment]
Hi, thanks for reaching out. I cannot replicate this behaviour. Would you be able to send your composer files and database backup to support@craftcms.com so we can dig deeper? If you do that, could you also please mention which entry this is happening for (so that it’s easier for us to replicate)?

**Comment by brandonkelly** [comment]
> I've found that if I reference the entry by id, then it works as expected:

How exactly is `entry` getting defined in the first place? It seems like it isn’t fully in-tact from the outset.

**Comment by mortscode** [comment]
First of all, I appreciate all of you. Thanks for Craft and all that you do. Ok, let's get into it.

## Backstory
This site has been on Craft since 2013 and we've stayed up-to-date as best we can. I have 1 custom plugin that I need to update for us to migrate to Craft 4, and it's high on my priority list. We've been rendering Categories on this `postEntries` page for quite a few years in this fashion, so I'm not sure what changed, or perhaps how long I've been doing this incorrectly.

## The Entry (Channel)
`postEntreis` is a Channel that provides all of the recipe blog posts on our website. We have ~970 recipes at this point. Here is how the Channel is defined in the CP:
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/3239582/234671626-3edc3796-4517-4a36-8ea1-b930e9290dc7.png">
The entrypoint template is found at `craft/templates/post-entry/index.twig`

## The Field (Field Type: Categories)
We use this Category set to define the categories of our recipes (course, season, dietary needs, convenience, etc). Here's how the field is set up in the CP:
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/3239582/234672806-f41b02f7-f43b-431a-af41-f9b93575d202.png">
Here is an example of the field within a `postEntries` entry in the CP:
<img width="363" alt="image" src="https://user-images.githubusercontent.com/3239582/234673070-ccd0d72d-404e-4158-bd99-d21dd304b8b4.png">

## An Update
1. I commented out all of the code in `craft/templates/post-entry/index.twig` and the following worked as expected:
```
{% set testCats = entry.postCategories.all() %}
    <h1>Cats</h1>
    <ul>
    {% for item in testCats %}
        <li>{{ item.title }}</li>
    {% endfor %}
    </ul>
```
2. I started moving the original code back in a bit at a time including the `_layout` extension and I started having the issue again when I un-commented the following line:
```
{% set isRoundup = entry.postCategories.slug('roundups').exists() %}
```
This line exists so I can provide some front-end and SEO differences if the post is a "roundup", for example "60 Best Chicken Recipes". I got this line from someone in the Craft Discord. Is there a better way to approach that `isRoundup` boolean?

**Comment by mortscode** [comment]
For the record, when I dump & dive the `entry.postCategories.slug('roundups').exists()` value, it seems to only return `true` or `false`. I'm not sure why it's emptying out the `entry.postCategores` query for the rest of the page.

**Comment by mortscode** [comment]
The following works as expected. It's a bummer to create that little array, but it leaves my category field in tact:
```
{% set categorySlugs = entry.postCategories|map(cat => cat.slug) %}
{% set isRoundup = 'roundups' in categorySlugs %}
```

**Comment by mortscode** [comment]
Makes total sense. Thanks @brandonkelly
