### ISSUE TITLE
[4.x]: Matrix Block Migration Errors - going from Craft v3.8.8 to v4

### ISSUE THREAD

**Issue by matthaltuch** [craftcms/cms#13121]
### Description
I am trying to update from craft 3.8.8 to v4 and am running into a Matrix Block Migration Error that I cannot get past.

I have tried installing the Fix FKs plugin in v3.8.8 to fix prior to the update to v4 but cannot get the repo to spin up to be able to fix any DB issue that may be related to this - in the Craft v3 everything is working and I can spin up the site with no issues.

Once I update the composer dependencies to craft v4, php v8.0.2 and related plugins to the craft v4 compatible versions and try to start the project up I run into the following output

`craft_1  | 
craft_1  | *** failed to apply m220213_015220_matrixblocks_owners_table (time: 0.641s)
craft_1  | 
craft_1  | 12 from 52 migrations were applied.
craft_1  | 
craft_1  | Migration failed. The rest of the migrations are canceled.
craft3_craft_1 exited with code 1`

I have found a few suggestions for the fix to this based on responses to this or similar problems but I am using docker and since I cannot get the docker instance to spin up I am having difficulty getting the DB to be accessible to try and run any sql commands

### Steps to reproduce

1. Current v4 plugins being used
`    "require": {
        "born05/craft-assetusage": "^3.1.0",
        "craftcms/cms": "^4.0.0",
        "craftcms/redactor": "3.0.4",
        "craftcms/fix-fks": "2.0.0",
        "ether/simplemap": "4.0.3",
        "ether/tags": "2.0.0",
        "nystudio107/craft-retour": "4.1.12",
        "nystudio107/craft-templatecomments": "^4.0.0",
        "nystudio107/craft-twigpack": "^4.0.0",
        "nystudio107/craft-vite": "4.0.5",
        "putyourlightson/craft-blitz": "4.4.4",
        "putyourlightson/craft-sprig": "^2.6.0",
        "solspace/craft-freeform": "4.0.22",
        "topshelfcraft/environment-label": "^4.0.2",
        "verbb/comments": "2.0.7",
        "verbb/navigation": "2.0.17",
        "verbb/super-table": "3.0.8.1",
        "vlucas/phpdotenv": "^3.6.0"`

`    "config": {
        "sort-packages": true,
        "optimize-autoloader": true,
        "platform": {
            "php": "8.0.2"
        },
`
### Expected behavior

Migrations would complete on the update from v3.8.8

### Actual behavior

The terminal output snippet from error

``craft_1  | 
craft_1  | *** applying m220213_015220_matrixblocks_owners_table
craft_1  |     > dropping {{%matrixblocks_owners}} if it exists ... done (time: 0.026s)
craft_1  |     > create table {{%matrixblocks_owners}} ... done (time: 0.049s)
craft_1  |     > add foreign key fk_mmupxkcsfvrlvwiwesagnvnidxaxzyygayuz: {{%matrixblocks_owners}} (blockId) references {{%matrixblocks}} (id) ... done (time: 0.118s)
craft_1  |     > add foreign key fk_wlelzaasdbekpnqxdmukkwfmvbuabpqnbkmf: {{%matrixblocks_owners}} (ownerId) references {{%elements}} (id) ... done (time: 0.120s)
craft_1  |     > execute SQL: INSERT INTO {{%matrixblocks_owners}} ([[blockId]], [[ownerId]], [[sortOrder]]) 
craft_1  | SELECT [[id]], [[ownerId]], COALESCE([[sortOrder]], 1) 
craft_1  | FROM {{%matrixblocks}} ...Exception: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`craft`.`matrixblocks_owners`, CONSTRAINT `fk_wlelzaasdbekpnqxdmukkwfmvbuabpqnbkmf` FOREIGN KEY (`ownerId`) REFERENCES `elements` (`id`) ON DELETE CASCADE)
craft_1  | The SQL being executed was: INSERT INTO `matrixblocks_owners` (`blockId`, `ownerId`, `sortOrder`) 
craft_1  | SELECT `id`, `ownerId`, COALESCE(`sortOrder`, 1) 
craft_1  | FROM `matrixblocks` (/var/www/src/vendor/yiisoft/yii2/db/Schema.php:676)
craft_1  | #0 /var/www/src/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `ma...')
craft_1  | #1 /var/www/src/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('INSERT INTO `ma...')
craft_1  | #2 /var/www/src/vendor/yiisoft/yii2/db/Migration.php(219): yii\db\Command->execute()
craft_1  | #3 /var/www/src/vendor/craftcms/cms/src/migrations/m220213_015220_matrixblocks_owners_table.php(33): yii\db\Migration->execute('INSERT INTO {{%...')
craft_1  | #4 /var/www/src/vendor/craftcms/cms/src/db/Migration.php(49): craft\migrations\m220213_015220_matrixblocks_owners_table->safeUp()
craft_1  | #5 /var/www/src/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
craft_1  | #6 /var/www/src/vendor/craftcms/cms/src/console/controllers/MigrateController.php(358): yii\console\controllers\BaseMigrateController->migrateUp('m220213_015220_...')
craft_1  | #7 [internal function]: craft\console\controllers\MigrateController->actionAll()
craft_1  | #8 /var/www/src/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
craft_1  | #9 /var/www/src/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
craft_1  | #10 /var/www/src/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
craft_1  | #11 /var/www/src/vendor/craftcms/cms/src/console/ControllerTrait.php(87): yii\console\Controller->runAction('all', Array)
craft_1  | #12 /var/www/src/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction('all', Array)
craft_1  | #13 /var/www/src/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
craft_1  | #14 /var/www/src/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('migrate/all', Array)
craft_1  | #15 /var/www/src/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
craft_1  | #16 /var/www/src/vendor/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest(Object(craft\console\Request))
craft_1  | #17 /var/www/src/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
craft_1  | #18 /var/www/src/craft(22): yii\base\Application->run()
craft_1  | #19 {main}
craft_1  | *** failed to apply m220213_015220_matrixblocks_owners_table (time: 0.641s)
craft_1  | 
craft_1  | 
craft_1  | 12 from 52 migrations were applied.
craft_1  | 
craft_1  | Migration failed. The rest of the migrations are canceled.
craft3_craft_1 exited with code 1``

### Craft CMS version

4

### PHP version

8.0.2

### Operating system and version

WIndows 11 using WSL2

### Database type and version

MSQL

### Installed plugins and versions

-
        "born05/craft-assetusage": "^3.1.0",
        "craftcms/cms": "^4.0.0",
        "craftcms/redactor": "3.0.4",
        "craftcms/fix-fks": "2.0.0",
        "ether/simplemap": "4.0.3",
        "ether/tags": "2.0.0",
        "nystudio107/craft-retour": "4.1.12",
        "nystudio107/craft-templatecomments": "^4.0.0",
        "nystudio107/craft-twigpack": "^4.0.0",
        "nystudio107/craft-vite": "4.0.5",
        "putyourlightson/craft-blitz": "4.4.4",
        "putyourlightson/craft-sprig": "^2.6.0",
        "solspace/craft-freeform": "4.0.22",
        "topshelfcraft/environment-label": "^4.0.2",
        "verbb/comments": "2.0.7",
        "verbb/navigation": "2.0.17",
        "verbb/super-table": "3.0.8.1",
        "vlucas/phpdotenv": "^3.6.0"`

**Comment by brandonkelly** [comment]
Thanks for reporting that! I’ve added a guard against this issue for the next release.

To try again with the fix:

1. Restore your database using a Craft 3 backup.
2. Change your `craftcms/cms` requirement in `composer.json` to `dev-develop#c3e370073d6440111849df8645422578f4ed5ffb`.
3. Run `composer update`.

**Comment by matthaltuch** [comment]
Thank you for the assistance - that helped me get past the issue with the migrations and it looks like everything with that was able to complete.

As a follow up should I be able to revert the  `craftcms/cms` requirement in `composer.json` back to `"^4.0.0"` ?

When I changed that back to v4 and tried to spin it back up im getting the following output and error

```
craft_1  | Your project config files were created for different versions of Craft and/or plugins than what’s currently installed.
craft_1  | 
craft_1  | Redirects is installed with schema version of 3.0.11 while 3.0.10 was expected.
craft_1  | 
craft_1  | Try running `composer install` from your terminal to resolve.
craft3_craft_1 exited with code 1
```

This was unexpected because my composer version has `"nystudio107/craft-retour": "4.1.12",` as the only redirect plugin and prior to that for craft 3 the version that was installed was v3.2.10 - when the project exits it kills the docker container so I cannot run the composer install against the project to try and fix

If I remove this plugin and get things to spin up and re-install the plugin would that effect any of the data in the DB if the plugin is removed and reinstalled with the current compatible craft 4 version?

**Comment by brandonkelly** [comment]
I’d go with `^4.4.8` just so there’s no chance Composer gives you an older version, but yes, it’s safe to change it.

It sounds like running `composer update` gave you an updated version of `nystudio107/craft-retour`, and then you ran `craft project-config/apply`, which won’t work until after any new migrations are run. You should be able to resolve by running either `craft migrate/all` or `craft up`.

**Comment by brandonkelly** [comment]
Craft 4.4.9 is out with that migration fix.

**Comment by matthaltuch** [comment]
Thanks for the heads up on v4.4.9

Using ^4.4.9 in my composer.json I am still running into a migration error that is killing the entire update

`
craft_1  |      `branch_locations_dynamic_45` text
craft_1  | ) ENGINE = InnoDb DEFAULT CHARACTER SET = utf8 (/var/www/src/vendor/yiisoft/yii2/db/Schema.php:676)
craft_1  | #0 /var/www/src/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE `f...')
craft_1  | #1 /var/www/src/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('CREATE TABLE `f...')
craft_1  | #2 /var/www/src/vendor/yiisoft/yii2/db/Migration.php(322): yii\db\Command->execute()
craft_1  | #3 /var/www/src/vendor/solspace/craft-freeform/packages/plugin/src/migrations/m220330_111857_SplitSubmissionsTable.php(118): yii\db\Migration->createTable('{{%freeform_sub...', Array)
craft_1  | #4 /var/www/src/vendor/solspace/craft-freeform/packages/plugin/src/migrations/m220330_111857_SplitSubmissionsTable.php(85): Solspace\Freeform\migrations\m220330_111857_SplitSubmissionsTable->createFormTable(1, 'contact_us', Array)
craft_1  | #5 /var/www/src/vendor/craftcms/cms/src/db/Migration.php(49): Solspace\Freeform\migrations\m220330_111857_SplitSubmissionsTable->safeUp()
craft_1  | #6 /var/www/src/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
craft_1  | #7 /var/www/src/vendor/craftcms/cms/src/console/controllers/MigrateController.php(358): yii\console\controllers\BaseMigrateController->migrateUp('m220330_111857_...')
craft_1  | #8 [internal function]: craft\console\controllers\MigrateController->actionAll()
craft_1  | #9 /var/www/src/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
craft_1  | #10 /var/www/src/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
craft_1  | #11 /var/www/src/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
craft_1  | #12 /var/www/src/vendor/craftcms/cms/src/console/ControllerTrait.php(87): yii\console\Controller->runAction('all', Array)
craft_1  | #13 /var/www/src/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction('all', Array)
craft_1  | #14 /var/www/src/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
craft_1  | #15 /var/www/src/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('migrate/all', Array)
craft_1  | #16 /var/www/src/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
craft_1  | #17 /var/www/src/vendor/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest(Object(craft\console\Request))
craft_1  | #18 /var/www/src/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
craft_1  | #19 /var/www/src/craft(22): yii\base\Application->run()
craft_1  | #20 {main}
craft_1  | *** failed to apply m220330_111857_SplitSubmissionsTable (time: 0.011s)
craft_1  | 
craft_1  | 
craft_1  | 0 from 17 migrations were applied.
craft_1  | 
craft_1  | Migration failed. The rest of the migrations are canceled.
ccpl-craft3_craft_1 exited with code 1
`

I'm wondering if this is related to an existing freeform submission with some non utf8 characters in an entry that it is trying to update/create a new table with in the migration ... or is this pointing to something different based on the stack trace?

Thanks for the help!
M

**Comment by brandonkelly** [comment]
@matthaltuch you’re missing the actual error message so hard to see what the issue is there, but it’s coming from Freeform’s `m220330_111857_SplitSubmissionsTable` migration, so you’re going to need to report it over at https://github.com/solspace/craft-freeform/issues.
