### ISSUE TITLE
[4.x]: 

### ISSUE THREAD

**Issue by Mixxey** [craftcms/cms#13129]
### Description

Since we updated from 4.4.5 to 4.4.7.1 files uploaded to a local volume work fine in a logged-in browser but usually (not always, though) return 404 in incognito tabs, unknown browsers etc.

### Steps to reproduce

1. Upload file to https://hero-software.de/assets/data (or other local volume; file type doesn't matter) - I uploaded https://hero-software.de/assets/data/test.txt for testing

Volume settings:
![image](https://user-images.githubusercontent.com/71216279/234792221-e5f9946c-5f2b-4370-b809-4608381868ec.png)
![image](https://user-images.githubusercontent.com/71216279/234792289-1cb2094b-fd88-4978-94f1-67f3d91dab2e.png)

3. Check file while logged in
4. Check file in incognito tab or random other browser

### Expected behavior

The file is always displayed (we use this for Lottie JSON animations, but I also tested it with images and text files - same effect)

### Actual behavior

The file often (but not always) returns a 404 
![image](https://user-images.githubusercontent.com/71216279/234789363-9d23b7a4-c32b-488f-b3a7-e2847d299682.png)
![image](https://user-images.githubusercontent.com/71216279/234789520-721175db-4e9d-4379-b2fe-70e5c69b5abf.png)

The problem occurs in prod and staging environment but not in local. I also updated Craft and plugins to the latest version today, which didn't fix the problem. I tried creating other local volumes before and after that update, which all show the same behavior (tested on staging).

Some help or advice would be much appreciated :)

### Craft CMS version

Craft Pro 4.4.7.1

### PHP version

8.0.28

### Operating system and version

Linux 4.15.0-206-generic

### Database type and version

MySQL 5.7.41

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.10-23)

### Installed plugins and versions

- Asset Usage 3.1.0
- Autologin 3.0.0
- Blitz 4.4.4
- Cloudflare 2.0.0
- Control Panel CSS 2.6.0
- CP Clear Cache 1.3.0
- CP Field Inspect 1.4.4
- Craft JWT Auth dev-develop-craft-4
- Dumper 3.0.1
- Elements Panel 2.0.0
- Embedded Assets 3.1.5
- Field Manager 3.0.5
- Google Cloud Storage 2.0.0
- ImageOptimize 4.0.4
- Instagram Feed 2.1.0
- Logs 4.0.0
- Minify 4.0.0-beta.2
- Navigation 2.0.17
- Neo 3.7.6
- Redactor 3.0.4
- Remote Backup 4.1.3
- Retour 4.1.12
- Sentry SDK 2.0.1
- SEOmatic 4.0.23
- Smith 2.0.0
- Sprig 2.5.1.
- Twigpack 4.0.0-beta.4
- Vite 4.0.5
- Wordsmith 4.2.0

**Comment by i-just** [comment]
Hi, thanks for reaching out. I can’t replicate it on a clean installation, but I wonder if this would still be the case if you specified a `Base URL` with an alias (that points to the base URL for this site) or an absolute path. For example: `@web/assets/data` or `https://my-staging-site.com/assets/data` (replace my-staging-site.com with the actual base URL for your staging site). Could you please try that in the staging environment (where you’re also experiencing this issue) and let me know if the problem persists?

**Comment by Mixxey** [comment]
Hey, thanks for getting back to me! Sadly, the ideas you proposed result in the same behavior. However, I looked into the commit history again, and I must correct my initial statement: the error occurred before the last update, so I guess it might be a coincidence that the oldest files work. Or at least I can't seem to find any other changes that might have caused this error.

**Comment by i-just** [comment]
Are you in a load-balanced environment by any chance?

**Comment by Mixxey** [comment]
Oh, yes we are.

**Comment by i-just** [comment]
Right. This will likely have something to do with your setup. 

I assume that when you log in to admin, you are “locked” to a specific network in your load-balanced environment (e.g. via a sticky session). From the moment you log in, you are always routed to the same instances. However, when you log out, or that session expires, or when you use an incognito mode or a different browser, you might get connected to a different instance, and that instance might not have the file you uploaded via the Control Panel. This explains why you can sometimes view the file and sometimes not - it depends on where you’re routed via the load balancer.

I’d check that the location where the files are uploaded is available from all the load-balanced instances or if the replication scripts (if you’re using them) are working as expected. There can sometimes be a delay in files getting replicated across your network (again, it depends on your setup and configuration), so the files might not be available immediately but start working after some time has passed. 

I hope this will help you (or your hosting provider) figure out how to fix this problem!
