### ISSUE TITLE
[4.x]: Migration errors when upgrading  to V4

### ISSUE THREAD

**Issue by andyg242** [craftcms/cms#13136]
### Description

While running the php craft migrate/all command after updating composer to Craft 4 I get the following error:

> truncate table {{%assetindexdata}} ... done (time: 0.175s)
    > drop column sessionId from table {{%assetindexdata}} ... done (time: 0.027s)
    > add column sessionId integer NOT NULL AFTER `id` to table {{%assetindexdata}} ... done (time: 0.028s)
    > add column isDir boolean DEFAULT FALSE AFTER `timestamp` to table {{%assetindexdata}} ... done (time: 0.028s)
    > add column isSkipped boolean DEFAULT FALSE AFTER `recordId` to table {{%assetindexdata}} ... done (time: 0.021s)
    > dropping {{%assetindexingsessions}} if it exists ... done (time: 0.007s)
    > create table {{%assetindexingsessions}} ... done (time: 0.012s)
    > add foreign key craft_fk_lnunaqycakhibpfckznunnjibubcuzquzcdw: {{%assetindexdata}} (sessionId) references {{%assetindexingsessions}} (id) ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1142 REFERENCES command denied to user 'uugrhpj_db171638'@'localhost' for table 'craft_assetindexingsessions'
The SQL being executed was: ALTER TABLE `craft_assetindexdata` ADD CONSTRAINT `craft_fk_lnunaqycakhibpfckznunnjibubcuzquzcdw` FOREIGN KEY (`sessionId`) REFERENCES `craft_assetindexingsessions` (`id`) ON DELETE CASCADE (/home/uugrhpjmpxg7/domains/montsurfaces.com/vendor/yiisoft/yii2/db/Schema.php:676)

### Steps to reproduce
 run php craft migrate/all

### Expected behavior
Migrations applied to Craft

### Actual behavior
Error message and no migrations applied

### Craft CMS version

4.0.0

### PHP version

8.1

### Operating system and version

Linux

### Database type and version

MySQL 5.7.39-cll-lve

### Installed plugins and versions

-

**Comment by andyg242** [comment]
Craft version information 

craftcms/cms                       4.4.8     Craft CMS
craftcms/html-field                2.0.7     Base class for Craft CMS field types with HTML values.
craftcms/oauth2-craftid            1.0.0.1   Craft OAuth 2.0 Client Provider for The PHP League OAuth2-Client
craftcms/plugin-installer          1.6.0     Craft CMS Plugin Installer
craftcms/redactor                  3.0.4     Edit rich text content in Craft CMS using Redactor by Imperavi.

**Comment by brandonkelly** [comment]
The actual error there is `1142 REFERENCES command denied to user` – which is saying that the MySQL user you’re connecting with doesn’t have permission to create foreign keys.

Here’s the full list of required permissions Craft requires that the MySQL user has: https://craftcms.com/docs/4.x/requirements.html#mysql-mariadb

Once you’ve fixed that, import a database backup from before you attempted the upgrade, and try again.
