### ISSUE TITLE
[4.x]: Element save notification blown out with long title

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#13137]
### Description

The control panel user notification for saved elements gets blown out when the title is too long.

### Steps to reproduce

1. Edit an entry with a long title.
2. Save the entry.

<img width="583" alt="Screenshot 2023-04-30 at 13 42 18" src="https://user-images.githubusercontent.com/57572400/235370739-b1bedb14-655d-48f8-a436-aace8c874f9d.png">

### Craft CMS version

4.4.8

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by bencroker** [comment]
Thanks!

**Comment by brandonkelly** [comment]
Craft 4.4.9 is out with a fix for that.
