### ISSUE TITLE
[4.x]: Asset modals don't remember the subfolder anymore

### ISSUE THREAD

**Issue by sebastian-lenz** [craftcms/cms#13147]
### Description

Craft has changed the way asset folders are displayed to the user, they no longer appear in the sidebar and instead are now displayed next to the files in the list section of the asset modal dialog. Since this change the asset select layers no longer remember the subfolder the user was working in previously, instead they now always start at the root level.

This issue belongs to my comment [here](https://github.com/craftcms/cms/pull/12558#issuecomment-1523233037).

### Steps to reproduce

1. Create an asset reference field.
2. Edit an entry with that field, select a file from a subfolder.
3. Edit another entry, open the file select dialog.

### Expected behavior

Previously the modal remembered the subfolder the user was in and reopened that location, even after navigating around in the control panel. 

![Bildschirmfoto 2023-05-02 um 12 10 49](https://user-images.githubusercontent.com/2273359/235642162-8c7b8f9c-b9df-4bc9-bde6-2693e14bb5d1.png)

### Actual behavior

Now the modal always displays the root folder.

![Bildschirmfoto 2023-05-02 um 12 17 00](https://user-images.githubusercontent.com/2273359/235642188-ac590cad-9340-4e22-8bd2-a57954a5fc29.png)

### Craft CMS version

4.4.8

### PHP version

8.2.5

### Operating system and version

Linux 5.10.0

### Database type and version

MariaDB 10.5.18

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Just looked into this. It’s unfortunately not easily possible to bring the nested location memory back, since the data required to establish the nested path is a lot more than we’d want to store in `localStorage`. Will keep this open and keep it in the back of my head, though.

**Comment by johndwells** [comment]
Just to add that a client of ours has noticed this feature is gone and are desperate to have it back. They have judiciously organized their assets into tidy folders within folders, and having to navigate through them every time is a real time suck.

**Comment by johndwells** [comment]
@sm9 Yes this issue is also pretty glaring - I've wondered about making a separate feature request to toggle the visibility of folders, to overcome that exact issue.

**Comment by brandonkelly** [comment]
Good news! I was able to come up with a way to “bring back” selected subpath memory, and today we released Craft 3.8.12 and 4.4.12 with it.

**Comment by sebastian-lenz** [comment]
That‘s great news, thanks a lot for taking care of this issue!

**Comment by sm9** [comment]
That's great, thanks for this Brandon. 👍🏻
