### ISSUE TITLE
[4.4.x]: Validation error if Dropdown has invalid value

### ISSUE THREAD

**Issue by aleksei-kadeikin** [craftcms/cms#13146]
### Description
When trying to save an old entry, it fails if an invalid value is selected in the dropdown.
Appeared after updating from 4.3.x -> 4.4.x.
Only happens with old entries.

We understand that this is expected behaviour. Happens because old values have been deleted, but manually re-selecting values takes too much time. Also adding options with `''` value to all dropdowns is not OK for us.
(All our dropdowns have default values).

So is it possible to make Craft set a default value if the value is `invalid`? Maybe you have some kind of setting for this?

[This](https://github.com/craftcms/cms/commit/de5ed75b1450563c0acffaea69ad94f5e976c609) did not help
### Steps to reproduce
1. Create an entry with dropdown, where non-existing option is selected.
2. Try to save.

### Expected behaviour
Entry successfully saved with default value

### Actual behaviour
Validation error thrown.
![image](https://user-images.githubusercontent.com/48591943/235642403-19502cdf-6d42-402a-9362-ae9428f9344b.png)

### Craft CMS version

Craft Pro 4.4.8

### PHP version

8.0.28

**Comment by i-just** [comment]
Hi, thanks for reaching out. We will be talking (internally) about the dropdown field behaviour soon. In the meantime, maybe you’ll find this helpful: https://github.com/craftcms/cms/issues/12548#issuecomment-1386960310

Also, more info can be found here: https://github.com/craftcms/cms/issues/12262.

**Comment by aleksei-kadeikin** [comment]
Thank you for your quick response!
Will take a look and hopefully a solution will be live soon 🤞 🙏

**Comment by aleksei-kadeikin** [comment]
Hey, @i-just! I am really sorry for disturbing you, but are there any dates for updates on this topic?
This issue affects our content team really much and they will be more than happy to have the resolution for that problem 😟

**Comment by i-just** [comment]
Hi @aleksei-kadeikin, it’s on our todo list, but no hard deadline for when it will be changed yet. The command I linked to should help in the meantime (or adding an empty value to the affected dropdowns if a selection doesn’t have to be made).

**Comment by darylknight** [comment]
Subscribing to this. Our content authors are also frustrated that old entries no longer allow them to save when they haven't changed those fields.

**Comment by chuckneely** [comment]
also subscribing to this as we are currently being affected by this issue, old entries can't be saved unless content editors manually select an option from the field (even though a "default" is set in the field settings)

**Comment by brandonkelly** [comment]
Craft 4.5.0 is out with an improvement to Dropdown field behavior: now if a Dropdown field’s value is invalid, and the field contains an explicit Default option, the default option will be auto-selected, and the field will be marked as changed. (#13540)

**Comment by darylknight** [comment]
I tried the beta and it solved this issue, thank you!
