### ISSUE TITLE
'redis' not actually available as a cache method

### ISSUE THREAD

**Issue by ghost** [craftcms/cms#1314]
### Description
In the comments in the config files, it mentions redis as a cache option, but it's coming back as an unsupported cache type.

Missing in https://github.com/craftcms/cms/blob/develop/src/config/components/common.php#L129

### Steps to reproduce

1. Set cache type in configs as "redis"
2. Get `\InvalidArgumentException`

### Additional info

- Craft version: Craft3 Beta
- PHP version: 7.0+
- Database driver & version: MySQL 5.6+
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Turns out Redis support was removed from Yii 2, and moved into a separate [extension](https://github.com/yiisoft/yii2-redis). It should be possible to Composer-install that extension yourself and make the application config adjustments it requires via [`config/app.php`](https://github.com/craftcms/docs/blob/master/en/configuration.md#application-config), so I just updated the `cacheMethod` comment to not include `redis` anymore.

**Comment by rsanchez** [comment]
@brandonkelly FYI, you can't use that Redis Yii extension because Craft validates the cacheMethod [here](https://github.com/craftcms/cms/blob/develop/src/config/GeneralConfig.php#L764-L767):

```php
// Validate cacheMethod
if (!in_array($this->cacheMethod, [self::CACHE_METHOD_APC, self::CACHE_METHOD_DB, self::CACHE_METHOD_FILE, self::CACHE_METHOD_MEMCACHE, self::CACHE_METHOD_WINCACHE, self::CACHE_METHOD_XCACHE, self::CACHE_METHOD_ZENDDATA], true)) {
    throw new InvalidConfigException('Unsupported cacheMethod value: '.$this->cacheMethod);
}
```

Any chance of making redis an first-class option again?

**Comment by brandonkelly** [comment]
There’s no need to change the `cacheMethod` value. Your `config/app.php` file will be completely overriding Craft’s [`cache` component definition](https://github.com/craftcms/cms/blob/006c9f65037f36f397d57df377d4cb7599a1c153/src/config/app/main.php#L196-L254), which is the only place that checks the `cacheMethod` setting.

Here’s what your `config/app.php` might look like:

```php
return [
    'components' => [
        'cache' => [
            'class' => yii\redis\Cache::class,
            'redis' => [
                'hostname' => 'localhost',
                'port' => 6379,
                'database' => 0,
            ],
        ],
    ],
];
````
