### ISSUE TITLE
[3.x]: Remote filename unchanged when resaving with `resave/assets --set`

### ISSUE THREAD

**Issue by kennethormandy** [craftcms/cms#13149]
### Description

Changing asset filenames in bulk with `craft resave/assets --set` doesn’t seem to update filenames on the remote S3 remote asset volume.

This all works as expected through the control panel, of course: if you update the filename, the filename is also updated on the remote S3 bucket too. The issue only happens with the `resave` command. It’s possible this is specific to the S3 plugin, but I’m not clear on that yet.

### Steps to reproduce

With Craft 3 or 4, configured with S3 for remote assets:

```sh
# Change a specific asset to have a lowercase filename
./craft resave/assets --elementId=1234 --limit=1  --set="filename" --to '={filename|lower}' --touch
```

This will correctly update the filename in Craft, but they will remain unchanged on S3.

### Expected behavior

The remote filename would also be updated on S3, so the asset doesn’t 404.

This would also make it possible for `resave` commands to trigger any S3 Event Notifications configured on the bucket.

### Actual behavior

The resource returns a 404 after running the command, because the asset has only been updated in Craft.

Here’s the error you get if you try and download the renamed asset through the control panel, after running that resave command:

> Filesystem Error – craft\errors\FsException
> Unable to read file from location: example.jpg. ↵
>
> Caused by: League\Flysystem\UnableToReadFile
> Unable to read file from location: example.jpg.
>
> in /var/www/html/vendor/league/flysystem/src/UnableToReadFile.php at line 24 ↵
> Caused by: Aws\S3\Exception\S3Exception
> Error executing "GetObject" on "https://example-bucket.s3.us-west-2.amazonaws.com/example.jpg"; AWS HTTP error: Client error: `GET https://example-bucket.s3.us-west-2.amazonaws.com/example.jpg` resulted in a `404 Not Found` response:

### Craft CMS version

4.4.7.1 and 3.7.68

### PHP version

8.0 and 8.1

### Operating system and version

Debian GNU/Linux 11 (bullseye)

### Database type and version

PostgreSQL 10 and PostgreSQL 13

### Installed plugins and versions

- craftcms/aws-s3 v1.3.0 and v2.0.3

**Comment by brandonkelly** [comment]
To change an asset’s filename, set its `newFilename` property instead.
