### ISSUE TITLE
[4.x]: Saving single with the "save and add another" button causes single to save as a new undeletable single

### ISSUE THREAD

**Issue by kevinmu17** [craftcms/cms#13157]
### Description
After editing a Single, i noticed the chevron next to the save button. When clicked on Save and add another it created a complete corrupted single entry with no possibility to delete.

<img width="260" alt="Screenshot 2023-05-04 at 22 43 39" src="https://user-images.githubusercontent.com/8747373/236325214-1da3ff7f-4ec4-44d4-8295-df446e542345.png">

### Steps to reproduce
1. Create a single
2. Edit the single
3. Save and add another

### Expected behavior
This option not to be available :)

### Actual behavior
Adding a corrupt single entry

### Craft CMS version

Craft Pro 4.4.9

### PHP version

8.1.16

### Operating system and version

Linux 5.15.49-linuxkit

### Database type and version

MariaDB 10.3.38

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- N/A

**Comment by i-just** [comment]
Hi, thanks for reporting! I created a PR to fix this.

**Comment by brandonkelly** [comment]
Fixed for the next release, via #13160.

**Comment by brandonkelly** [comment]
Craft 4.8.10 is out now with that fix.
