### ISSUE TITLE
[4.x]: Home Page Entry Missing

### ISSUE THREAD

**Issue by MalcolmJohnston** [craftcms/cms#13154]
### Description

This is a bit of an odd one, but for some reason the home page entry is missing on my site in the control panel.
I am not aware of any particular action that has caused this, as it was reported to me by a user.

This is not affecting the home page on the site which is still being rendered correctly, but without it being available no edits can be made.

So far I have tried the following steps to mitigate the issue:

1. Updated Craft and all Plugins to latest versions
2. Cleared the Caches (apart from Blitz)
3. Cleared the Data Caches

I have also had a look in the database and the entries are there and they are enabled.  The SQL I used to ascertain that is below.  

`select * 
from entries e
	inner join entrytypes et on e.typeid = et.id
    inner join elements el on e.id = el.id
    inner join elements_sites es ON es.elementId = el.id
where e.sectionId = 8 and es.slug = '__home__'
order by e.dateCreated desc;`

### Steps to reproduce

Unknown.

### Expected behavior

Home page to appear in the Entries section of the CMS control panel.

### Actual behavior

Home page does not appear in the Entries section in the CMS control panel.  I have tried searching, or navigating to the correct sections and it does not appear.

### Craft CMS version

Craft Pro 4.4.9

### PHP version

8.0.28

### Operating system and version

Linux 4.4.0-210-generic

### Database type and version

MySQL 5.7.33

### Image driver and version

GD 8.0.28

**Comment by brandonkelly** [comment]
Do you see the section listed in the `sections` table? Does it have a `dateDeleted` value (indicating the section was soft-deleted)?

**Comment by brandonkelly** [comment]
Ah ok, I thought maybe it was a Single section.

Can you send a database backup and your Composer files into support@craftcms.com? We can look into it from there.

**Comment by brandonkelly** [comment]
For posterity, it sounds like the homepage entry ended up losing its `__home__` slug.
