### ISSUE TITLE
[4.x]: First save of a multisite entry with Matrix blocks orphans the blocks from the primary site

### ISSUE THREAD

**Issue by aaronbushnell** [craftcms/cms#13155]
### What happened?

I'm seeing an issue on a Craft site where a handful of Matrix blocks are being orphaned in the database and lost on my primary site when saving the "Home" single in my newly created site.

Here are the steps I'm performing:

### 1. Add a new Site

![Screenshot 2023-05-03 at 9 49 34 AM](https://user-images.githubusercontent.com/315202/235935578-167e4dc7-6333-4e7d-b8c4-157521f43554.png)

### 2. Change my Matrix field's "Propagation Method" so blocks are only on the site they were created in

![Screenshot 2023-05-03 at 9 53 05 AM](https://user-images.githubusercontent.com/315202/235936436-afc716e0-cf0c-4ab4-b09c-24462f59d3f5.png)

### 3. Enable the Home single for the Spanish site

![Screenshot 2023-05-03 at 9 56 33 AM](https://user-images.githubusercontent.com/315202/235937362-6ef2e573-eec6-4f96-bc70-793d8bb331dc.png)

### 4. Visit the Spanish version of the Home single and then save it

**Note:** It appears that the primary site's blocks are in this view already. I _thought_ this would normally be empty because of step 2, but I could be mistaken.

![Screenshot 2023-05-03 at 9 59 37 AM](https://user-images.githubusercontent.com/315202/235938215-242a9a92-3650-454f-856b-58d6d7d7140d.png)

### 5. The primary site Home single has had all but one block removed

![Screenshot 2023-05-03 at 10 00 57 AM](https://user-images.githubusercontent.com/315202/235938732-6f09c478-f775-418d-a618-a4bf71a31667.png)

## Database note
I've attached a screenshot of the blocks with the `ownerId` of `4` (the Home single) before I saved the Home single and after (step 4). You can see that a number of these drop off.

![Screenshot 2023-05-03 at 10 05 13 AM](https://user-images.githubusercontent.com/315202/235940546-d6de336e-ad87-4e0d-8949-2a89d29172ac.png)

I was able to find one of the blocks that had dropped off to see where it went and here's what I found. It looks like that block was assigned a new `ownerId` and it points to a draft entry.

![Screenshot 2023-05-03 at 10 11 04 AM](https://user-images.githubusercontent.com/315202/235941582-9ef863d8-881d-4095-a05c-7a8339ca871d.png)

Let me know if you need me to send anything!

### Craft CMS version

Craft Pro 4.4.8

### PHP version

8.1.17

### Operating system and version

Darwin 22.4.0

### Database type and version

MySQL 5.7.41

### Image driver and version

GD 8.1.17

### Installed plugins and versions

- **Amazon S3**: 2.0.3
- **Blitz**: 4.4.4
- **Calendar**: 4.0.9
- **Design Tokens**: 1.0.3
- **Feed Me**: 5.1.3
- **Formie**: 2.0.28
- **Navigation**: 2.0.17
- **Palette**: 3.1.3
- **Ray**: 2.0
- **Redactor**: 3.0.4
- **Retour**: 4.1.12
- **SEOmatic**: 4.0.24
- **Sprig**: 2.6.2
- **Super Table**: 3.0.8.1
- **Typed link field**: 2.1.5
- **UI Element fields**: 2.0.3

**Comment by brandonkelly** [comment]
After creating the new site, did you wait until the “Applying new propagation method to [section name] entries” queue job had completed before editing the entry?

**Comment by aaronbushnell** [comment]
I did! When I saw that pop in I made sure to let that process entirely before proceeding

**Comment by brandonkelly** [comment]
Quick update – I was able to reproduce this today, and looking into it.

**Comment by brandonkelly** [comment]
Got to the bottom of it, and this is now fixed for the next release!

**Comment by aaronbushnell** [comment]
Thanks, @brandonkelly!

**Comment by brandonkelly** [comment]
Craft 4.8.10 is out now with that fix.
