### ISSUE TITLE
[4.x]: URI Format containing entry.slug of another entry is not updated

### ISSUE THREAD

**Issue by sander-lameco** [craftcms/cms#13151]
### Description
When changing the `slug` of the entry that is included in the `URI format` of another entries section it does not automatically update the URLs of said entries.

### Steps to reproduce

1. Create a multisite Craft environment (with at least 2 sites). 
2. Create a `single` section type with title `News Overview Page` and the handle `newsOverviewPage`.
3. Set the `URI format` to `{slug}`
4. Create a `structure` section type with the handle `newsPages`.
5. Set the `URI format` to `{{craft.entries().section('newsOverviewPage').one().slug}}/{slug}`
6. Create a new entry in the `newsPages` section with the title `Test Article` and slug `test-article`.
7. Change the slug of the `newsOverviewPage` section (currently `news-overview-page`) to something else like `news`.

### Expected behavior
Craft should resave/regenerate the URLs for the entries in `newsPages` since the `slug` of `newsOverviewPage` has been changed. The `newsPage` URL should change from `news-overview-page/test-article` to `news/test-article`.

### Actual behavior
The URL for the `newsPage` is still `news-overview-page/test-article` instead of `news/test-article`. But the URL for the `newsOverviewPage` actually is changed from `news-overview-page` to `news`.

### Craft CMS version

4.4.7.1

### PHP version

8.1

**Comment by i-just** [comment]
Hi, thanks for reaching out. Saving a single won’t trigger an update of any other entries URIs, but you can run a console command to re-save your `newsPages` section and get the URIs to update: `php craft resave/entries --section=newsPages`.

Automatic update of slugs and URI only happens for Structures - for example, if a parent element was saved or moved, Craft will check if descendants URIs should change too.

**Comment by sander-lameco** [comment]
Hi @i-just thanks for the command, I wasn't aware that was a possibility.
Would there be a trigger when saving the `newsOverviewPage` single entry to run said command?

I know setting a cronjob would also be a possibility but maybe there is another way since we halve multiple sections (~3) working this way.

**Comment by i-just** [comment]
Not a problem :)

The simplest solution would be to consider if your `newsOverviewPage` could be the parent element in the `newsPages` and not a single entry.

Or you could hardcode the `newsOverviewPage` single URI to be `news`, and then the `newsPages` could simply use `news/{slug}` as the URI. That way, even if someone changes the `newsOverviewPage` slug, the URI for that page won’t change, and you won’t have to worry about updating the `newsPages` URIs. Whether that’s a good option depends on your circumstances.

Alternatively, you could also play with writing code that would meet your needs. As a starting point, you could have a look here: https://craftcms.com/docs/4.x/extend/events.html and search for `craft\elements\Entry::EVENT_AFTER_SAVE`. For example, if `newsOverviewPage` was saved, trigger the `ResaveElements` job for the `newsPages`.

Hope this helps!

**Comment by brandonkelly** [comment]
Here’s an example of what that code might look like. You can place this within a private plugin or bootstrapped module’s `init()` method. (Use [Craft Generator](https://github.com/craftcms/generator/) to create the plugin/module if you don’t already have one.)

```php
use craft\elements\Entry;
use craft\events\ModelEvent;
use craft\helpers\ElementHelper;
use craft\helpers\Queue;
use craft\queue\jobs\ResaveElements;
use yii\base\Event;

Event::on(
    Entry::class,
    Entry::EVENT_AFTER_PROPAGATE,
    function(ModelEvent $event) {
        /** @var Entry $entry */
        $entry = $event->sender;

        if (
            !ElementHelper::isDraftOrRevision($entry) &&
            $entry->getSection()->handle === 'newsOverviewPage' &&
            $entry->slug !== Craft::$app->cache->get('news-overview-page-slug')
        ) {
            // re-save all newsPages entries
            Queue::push(new ResaveElements([
                'elementType' => Entry::class,
                'criteria' => [
                    'section' => 'newsPages',
                ]
            ]));
            // cache the new slug for a year
            Craft::$app->cache->set('news-overview-page-slug', $entry->slug, 60 * 60 * 24 * 365);
        }
    }
);
```

**Comment by sander-lameco** [comment]
Is hardcoding the preferred way?

We use the `{{craft.entries().section('newsOverviewPage').one().slug}}/{slug}` variant to give the end-user flexibility into changing the slugs whenever they feel like it.

@brandonkelly thanks for the example code.

**Comment by brandonkelly** [comment]
@sander-lameco If you want it all to be customizable by the author, then yeah this is a good choice!
