### ISSUE TITLE
[4.x]: Element labels are vertically off-center

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#13168]
### Description

Since Craft 4.4.8, element labels look slightly off-center vertically, relative to their status dot/icon:

<img width="198" alt="CleanShot 2023-05-08 at 15 46 30@2x" src="https://user-images.githubusercontent.com/298510/236840803-e6af59aa-07b9-405a-94f0-6a6e19a0ac1f.png">

Labels are also off-center on Craft 3.8.8+:

<img width="216" alt="CleanShot 2023-05-08 at 15 47 16@2x" src="https://user-images.githubusercontent.com/298510/236840954-e98ff491-17dd-47a4-9cd1-642b1fd1cdd8.png">

### Steps to reproduce

1.

### Craft CMS version

4.4.8, 4.4.9, 3.8.8, 3.8.9

### Installed plugins and versions

- None

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.8.10 is out now with that fix.

**Comment by mmikkel** [comment]
Thanks for the quick fix @brandonkelly!

As mentioned above, the issue seems to affect Craft 3.8.8+ as well; if possible it'd be great if the fix could be backported :) 

Screenshot below is from 3.8.10.2:

![CleanShot 2023-05-15 at 14 53 32](https://github.com/craftcms/cms/assets/298510/765082de-dc5d-4d98-940c-6bc874546286)

**Comment by brandonkelly** [comment]
Sorry, missed that! Done (29c2a8e76502911c94d230539516ae8bdba1a196).

**Comment by brandonkelly** [comment]
Craft 3.8.11 is out with that fix.
