### ISSUE TITLE
[4.x]: Timezone field not useable

### ISSUE THREAD

**Issue by approached** [craftcms/cms#13167]
### Description
I want select a Timezone but if i open the select box, than i can nothing read. Just look the screeenshot.

### Steps to reproduce

1. open the select box of timefield

### Actual behavior

<img width="426" alt="Screenshot 2023-05-08 at 11 55 54" src="https://user-images.githubusercontent.com/3439330/236794655-0ed20f4d-ddae-4aec-afb9-4bd519a99fb6.png">

### Craft CMS version

4.4.9

### PHP version

8.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed now for the next release.

I’ve also fixed some styling issues when the field is set to 25% width.

<img width="270" alt="A date field that shows the time and time zone, set to 25% width" src="https://user-images.githubusercontent.com/47792/236964363-d3d84865-0edc-4d5c-b256-a776a6cfbdd9.png">

**Comment by brandonkelly** [comment]
Craft 4.8.10 is out now with those fixes.
