### ISSUE TITLE
[4.x]: Javascript error when matrix block insert in entry since 4.4.10

### ISSUE THREAD

**Issue by yingban** [craftcms/cms#13178]
### What happened?

Cannot add a matrix block anymore in entry

### Description

Cannot add a matrix block in entry.
Javascript error in console 

```
jquery.js?v=1683705366:2 Uncaught TypeError: Cannot read properties of undefined (reading 'ownerDocument')
    at se.contains (jquery.js?v=1683705366:2:13526)
    at s.constructor.<anonymous> (MenuBtn.js:112:16)
```

Matrix blocks are not copied when an entry is translated.

### Steps to reproduce

1. assign matrix field to an entry type
2. try to add a matrix block

### Craft CMS version

4.4.10

### PHP version

8.0

**Comment by brandonkelly** [comment]
For posterity, Craft 3.8.10.2 and 4.4.10.1 are out with a fix for this.

**Comment by yingban** [comment]
Thanks @brandonkelly, but there is still an issue regarding matrix field.
I created another issue https://github.com/craftcms/cms/issues/13181
