### ISSUE TITLE
[4.4.10]: Clear button wrapping in editable table field

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#13182]
It looks like the changes made in https://github.com/craftcms/cms/commit/9d3ba64253c97ad05f81c6193956e98e77b67c29 are causing the clear button to wrap around to the next line in `datewrapper` and `timewrapper` classes, which get a width of `100%` when inside an editable table field.

<img width="802" alt="Screenshot 2023-05-10 at 15 44 12" src="https://github.com/craftcms/cms/assets/57572400/64bee444-3a5e-4568-930f-e204af6ac825">

### Steps to reproduce

1. Create a date field inside of an editable table field.

### Craft CMS version

4.4.10

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by bencroker** [comment]
Thank you, @i-just!

**Comment by brandonkelly** [comment]
Craft 4.4.11 is out with the fix for this.
