### ISSUE TITLE
[4..4.10]: Matrix blocks not propagated when entry is translated/enabled into another website since

### ISSUE THREAD

**Issue by yingban** [craftcms/cms#13181]
### Description

When a entry is enabled to another website, the matrix blocks are not propagated, even if the propagation method is set to 'Save blocks to other sites in the same site group".

### Steps to reproduce

1. Create a matrix field with different block types.
2. Assign it to an entry
3. Create blocks inside entry
4. Enable entries into another website

### Expected behavior

The matrix blocks should be copied and 1:1 between the two different versions.

### Actual behavior

Matrix field is empty and the blocks are not propagated.

### Craft CMS version

4.4.10.1

### PHP version

8.1

**Comment by i-just** [comment]
Hi, thanks for raising a separate issue! I created a PR for this.

**Comment by weotch** [comment]
@i-just, I tried out [your PR](https://github.com/craftcms/cms/pull/13185) and it didn't fix the issue for me.  

Here's a video showing how I experience this:

https://github.com/craftcms/cms/assets/77567/791d318a-46ed-495b-bef7-b042635261c8

One thing I've noticed is that setting the `'autosaveDrafts' => false,` config option fixes this.  Here's the same steps with that setting enabled:
 
https://github.com/craftcms/cms/assets/77567/ff6aeef4-13e7-475f-afed-b4cabadbe79f

I also don't experience this when `'autosaveDrafts' => true` if I save the entry after adding the new site super quickly, like before the autosave completes.

**Comment by i-just** [comment]
@weotch, is your “Blocks” field a matrix or a neo? What is that field’s propagation method set to?

**Comment by weotch** [comment]
It is Matrix (though we're using [Spoon](https://plugins.craftcms.com/spoon?craft4) with it).  

Propagation is set to "Save blocks to other sites with the same language"

**Comment by brandonkelly** [comment]
This is fixed now for the next release. We should be getting a hotfix out later today, but if you want to test before then, you can change your `craftcms/cms` requirement in composer.json to `dev-develop#c575444a6e7243e8fb7655c68b8ce44569c74f99 as 4.4.10.1` and run `composer update`.

**Comment by brandonkelly** [comment]
Craft 4.4.11 is out now with the fix.

**Comment by yingban** [comment]
@brandonkelly thanks for fixing

**Comment by weotch** [comment]
4.4.11 did _not_ fix [my issue](https://github.com/craftcms/cms/issues/13181#issuecomment-1544975639).  @yingban did it work for you?

**Comment by yingban** [comment]
@weotch 
it does work well with blocks which does not contains super table fields.
There were a PR in another thread about it, but did not have time to test it yet.

**Comment by brandonkelly** [comment]
Yeah my Super Table PR (verbb/super-table#519) has been [merged](https://github.com/verbb/super-table/commit/3c91ac3e9ae841a157e03f61196e60ccc4a0960f), but not released yet.

You should be able to test the fix ahead of release by changing your `verbb/super-table` constraint in composer.json to `dev-craft-4`, and running `composer update`.

**Comment by weotch** [comment]
Huh, even with the Super Table update, I'm still encountering that same issue.  Here's the versions I'm running

![image](https://github.com/craftcms/cms/assets/77567/d3f2ff05-8ba4-4092-8433-b90e27119677)

**Comment by brandonkelly** [comment]
@weotch Can you send a zip of your `composer.json`, `composer.lock`, and `config/project/` directory over to support@craftcms.com, and point us to the section that is happening in?
