### ISSUE TITLE
[4.x]: Password reset: cannot send mail if profile / field validation fails

### ISSUE THREAD

**Issue by WBTMagnum** [craftcms/cms#13191]
### Description

Password reset for users with invalid data in fields fails because of field validation.

### Steps to reproduce

1. create of find a user profile with a field that does not validate (e.g. link)
2. try to create the password reset link via the craft admin or use a password reset form
3. the craft admin will show a flash, e.g. "Link ist keine gültige URL."

### Expected behavior

The password reset should work, even if single fields are invalid. The only exception would be the e-mail field.

### Actual behavior

Users with an invalid profile cannot reset their password.

### Craft CMS version

4.4.7.1

### PHP version

8.1.18

### Operating system and version

Linux 5.10.0-22-amd64

### Database type and version

PostgreSQL 13.11

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

* Asset Rev: 7.0.0
* CKEditor: 3.1.0
* Element API: 3.0.1.1
* Feed Me: 5.1.2
* Super Table: 3.0.8.1

**Comment by i-just** [comment]
Hi, thanks for reaching out! This was fixed in version 4.4.8.

**Comment by WBTMagnum** [comment]
Thanks for the quick heads-up. So this is a duplicate of #13060.
