### ISSUE TITLE
[4.x]: Cannot Access Plugin Store

### ISSUE THREAD

**Issue by ambidustrious** [craftcms/cms#13199]
### Description
The Plugin Store will not load from the control panel

### Steps to reproduce

1. Visit the Plugin Store from the control Panel

### Expected behavior

The Normal Plugin Store should load

### Actual behavior

The plugin store never loads - I just get the spinning graphic with the message "Loading Plugin Store..."

When I look at the network request... I get a 404 on the following file request:
https://domain.com/index.php?p=admin%2Factions%2Fapp%2Fget-plugin-license-info&site=default&v=1684162622643

It's requested from axios.js

When I load the request directly in the browser it's returned correctly without error.

### Craft CMS version

Craft CMS 4.4.10.1

### PHP version

8.028

### Operating system and version

Linux 6.0.10-x86_64-linode158

### Database type and version

MySQL 8.0.29

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.12-50)

### Installed plugins and versions

Amazon S3
2.0.3

Blitz
4.4.4

Cookies
4.0.0

Feed Me
5.1.3.1

Freeform
4.0.23

Google Maps
4.3.3

Icon Picker
2.0.13

ImageOptimize
4.0.4

Imager X
4.1.13

Navigation
2.0.17

Neo
3.7.8

oEmbed
2.3.0

Phone Number
2.1.0

Postmark
3.0.0

Redactor
3.0.4

Retour
4.1.12

SEOmatic
4.0.24

Super Table
3.0.8.1

Table Maker
4.0.6

Tags
2.0.0

Typed link field
2.1.5

Videos
3.0.0-beta.1

**Comment by angrybrad** [comment]
@ambidustrious can you share the domain you're getting that error on? If you don't want to share it publicly, can you send to support@craftcms.com and reference this issue?

**Comment by ambidustrious** [comment]
@angrybrad Sent

**Comment by angrybrad** [comment]
Closing the loop on this - it seems to be hosting-specific, and it randomly started working after lots of debugging, so ¯\_(ツ)_/¯.
