### ISSUE TITLE
[3.x]: Uncaught TypeError: Cannot read properties of undefined (reading 'on') Matrix Blocks

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/cms#13194]
### Description

Since updating to 3.8.10.2 I am unable to click on block within a matrix field which has several types, but not enough to display the add a block menu.

> Uncaught TypeError: Cannot read properties of undefined (reading 'on')
    at s.constructor.init (MatrixInput.js:122:36)
    at s.constructor.constructor (Base.js:20:15)
    at s.constructor (Base.js:32:21)
    at new s.constructor (Base.js:32:21)
    at HTMLDocument.<anonymous> (922094-restaurant:2091:19)
    at l (jquery.js?v=1684142192:2:30361)
    at c (jquery.js?v=1684142192:2:30663)

The following JS console error is raised upon clicking on any block.

This seems related to https://github.com/craftcms/cms/issues/13177 but the reverse problem.

### Steps to reproduce

1. Update to Craft CMS 3.8.10.2
2. Try and click on a block on a matrix field with several options
3. The block is not added and a JavaScript console error is raised

None of these blocks work in a site.

![image](https://github.com/craftcms/cms/assets/8067792/55d31ec4-2ce5-4a1c-89fd-dff94d41d4fb)

If a matrix field has many blocks which displays the "Add a block" menu, this works.

### Expected behavior

To be able to add a block from any Matrix field.

### Actual behavior

No matrix block can be added

### Craft CMS version

3.8.10.2

### PHP version

8.0

### Operating system and version

WSL2 Ubuntu Linux

### Database type and version

MySQL 8

**Comment by i-just** [comment]
Hi, thanks for reaching out. I can’t seem to replicate this behaviour on a clean Craft 3.8.10.2 installation. 
Any chance you can check if it also happens when all your plugins are disabled? If so, can you please send over your composer files and `config/project` directory to support@craftcms.com so we can investigate further?

**Comment by jamesmacwhite** [comment]
@i-just. Thanks, I've just sent over our composer.json and config/project contents.

**Comment by i-just** [comment]
@jamesmacwhite, thanks for sending over the files; I can now reproduce it on a clean Craft 3 installation. 
It’s only happening if you have (at least) 2 matrix fields on a page, and one of them only has one block and min and max blocks for this field are both set to `1`. I'm looking into it now.

**Comment by jamesmacwhite** [comment]
Ah good find! I'm glad you could produce this because I was going crazy!

**Comment by jamesmacwhite** [comment]
@i-just Thanks for the quick PR on this. As this has unfortunately gone onto our production environment, do we have an estimate of a new point release?

**Comment by brandonkelly** [comment]
The PR is merged in. We’ll get a fix out shortly!

**Comment by jamesmacwhite** [comment]
Amazing, thank you for rapid response and release.

**Comment by brandonkelly** [comment]
Craft 3.8.11 is out with the fix :)

**Comment by jamesmacwhite** [comment]
Awesome, thank you
