### ISSUE TITLE
[4.x]: Server Error Occurred when trying to save asset field on fly out

### ISSUE THREAD

**Issue by jude86-7** [craftcms/cms#13196]
### Description

I can't saved information in asset field (Alternative text and image caption) when I double click on an image and access the 'flyout' edit form. I get an error stating 'server error occurred'.
Note if I edit the asset directly it works. I only get the error when I'm on the flyout window.

### Steps to reproduce

1. Double click an image within an entry. 
2. Add text to the 'alternative text' field
3. Save
4. Error saying server error occurred

### Expected behavior

The alternative text or image caption would save

### Actual behavior

I get an error and the changes won't save

### Craft CMS version

4.4.10.1

### PHP version

8.1.18

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
You should see the full error reported in `storage/logs/`. Search the `web-XXXX-XX-XX.log` files for `[web.ERROR]`. Can you post the full error details including the stack trace?

**Comment by jude86-7** [comment]
Hello,
Thank you, just going into the image within an entry and editing doesn't seem to cause an error log. However the following error log was triggered when I edited via assets. Hopefully this helps?
[web-2023-05-21.log](https://github.com/craftcms/cms/files/11524098/web-2023-05-21.log)

**Comment by brandonkelly** [comment]
Sounds like that asset is corrupted in some way. Can you try replacing its file?

**Comment by jude86-7** [comment]
Thank you, it seems like these errors are coming up no matter which asset I choose. Is it likely all images have become corrupted in some way? Is there a way I can regenerate these or is it a case of re-uploading all images?

**Comment by jude86-7** [comment]
Thanks, I've altered the local filesystem permissions with no luck. It's odd how an error occurs when I'm trying to edit on the fly out edit screen but it works when I open the edit screen in a new tab.

**Comment by brandonkelly** [comment]
Try the following:

1. Sign in with an admin account
2. Go to `/admin/myaccount`
3. Go to the **Preferences** tab
4. Enable the “Show full exception views when Dev Mode is disabled” setting
5. Press **Save**
6. Open your browser’s **Network** tab
7. Reproduce the error
8. Find the 4xx or 5xx request in the **Network** tab, and post the response details here.
