### ISSUE TITLE
[4.4.10-11]: Matrix blocks with Super Table field not propagated when entry is translated/enabled to a new added website since #13181  

### ISSUE THREAD

**Issue by yingban** [craftcms/cms#13207]
### Description

Hello, 

i am not sure if it is a Craft CMS issue or a Super Table issue @engram-design, but it reminds me this issue https://github.com/craftcms/cms/issues/12858 that Tommy opened after my email to Craft support.

When a entry is added to new website, if a matrix block is containing a Super Table field, even if the propagation method is set to 'Save blocks to other sites in the same site group", as well in the field. The rows in the block are not propagated.

Anyone else is facing this issue?

I tried multiple times locally, and downgrade to 4.4.9, where it works.

### Steps to reproduce

1. Create a matrix field with  a super table field.
2. Assign it to an entry
3. Create blocks inside entry
4. Enable entries into another website

### Expected behavior

The matrix blocks and Super Table rows should be copied and 1:1 between the two different versions.

### Actual behavior

Super Table rows are empty and not propagated.

### Craft CMS version

4.4.11

### PHP version

8.1

### Installed plugins and versions

Super Table 3.0.8.1

**Comment by brandonkelly** [comment]
Just PR’d a fix for this to Super Table (verbb/super-table#519).

**Comment by brandonkelly** [comment]
Today we released Craft 4.4.12 with a fix for Craft’s end of this bug. Now waiting on Super Table and Neo releases.

**Comment by engram-design** [comment]
Updated in [Super Table 3.0.9](https://github.com/verbb/super-table/releases/tag/3.0.9)

**Comment by yingban** [comment]
thanks @brandonkelly and @engram-design!
