### ISSUE TITLE
[4.x]: Disallow "Cache remote images" in ephemeral environments

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#13202]
### What happened?

<img width="849" alt="CleanShot 2023-05-15 at 14 07 50@2x" src="https://github.com/craftcms/cms/assets/18329/11e5f674-7c47-4b3b-ac11-6d7a29db8cb4">

### Craft CMS version

4.5

### Installed plugins and versions

-

**Comment by i-just** [comment]
PR submitted @tim
