### ISSUE TITLE
[4.x]: From `asErrorJson()`  to `asFailure()`, getting an unexpected error: `Return value must be of type yii\web\Response, null returned`

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#13218]
### Description

I have a custom module controller setup like this:

```
public function actionView(string $email): Response
{
    $response = User::find()
        ->email($email)
        ->one();

    if (empty($response)) {
        return $this->asErrorJson(Craft::t('site', 'ERROR'));
    }

    return $this->asJson($response);
}
```

As `asErrorJson` is [deprecated since > 4.0.0](https://docs.craftcms.com/api/v4/craft-web-controller.html#method-aserrorjson), I've updated it to `asFailure`.

However, while it was working previously, I now get this error when `$response` is empty:
`::actionView(): Return value must be of type yii\web\Response, null returned`

It looks like an unexpected breaking change. How to fix this error, to make `asFailure` behave like `asErrorJson`?

### Craft CMS version

4.4.10.1

### PHP version

8.0.20

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out. 

Here’s how the `asFailure` method works: https://github.com/craftcms/cms/blob/develop/src/web/Controller.php#L246C6-L265. If the request doesn’t accept JSON, `null` will be returned. 

You can `$this->requireAcceptsJson();` at the beginning of your method to ensure it’s not run for requests that don’t accept JSON. 
Or you can check if the request accepts JSON with: `Craft::$app->getRequest()->getAcceptsJson()`, and use `asFailure` if it does and a different approach if it doesn’t. (You could even do what `asErrorJson` used to do: https://github.com/craftcms/cms/blob/develop/src/web/Controller.php#L637-L640.)

I hope this helps.

**Comment by romainpoirier** [comment]
Thank you for the clarifications.

Is there an equivalent of [asSuccess()](https://docs.craftcms.com/api/v4/craft-web-controller.html#method-assuccess) but for errors? So that the error message is catch, but not returned as a JSON.

**Comment by i-just** [comment]
Not that I can think of. But you can still do whatever you’re after in your method. For example, if the request doesn’t accept JSON, you can `setFailureFlash` and redirect (or do something else).

**Comment by romainpoirier** [comment]
Thank you. As `setFailureFlash` doesn't exist, are you talking about [`setError()`](https://docs.craftcms.com/api/v4/craft-behaviors-sessionbehavior.html#method-seterror) and/or [`addFlash()`](https://www.yiiframework.com/doc/api/2.0/yii-web-session#addFlash()-detail)?

**Comment by i-just** [comment]
Sorry, typed too quickly. I meant `setFailFlash`.
