### ISSUE TITLE
[4.x]: GraphQL mutation cannot set 'enable' state of entry to 'true'

### ISSUE THREAD

**Issue by ellukesmith** [craftcms/cms#13212]
### Description

GraphQL mutation is unable to re-enable a disabled entry. Strangely, I am able to disable an enabled entry via GraphQL, but I cannot re-enable that entry once it has been disabled.

I am running this on a multi-site install, so the only difference to my examples below is that I am passing in a valid siteId argument.

### Steps to reproduce

1. Open GraphQL explorer
2. Enter the following mutations (update the ID to a valid 'enabled' entry ID and replace the 'entryname' text with the name of your entry in the two 'save_entryname_default_Entry' lines)
```
mutation enableEntry{
  save_entryname_default_Entry(title:"This entry should be ENABLED", id:1234, enabled:true) {
    title
    enabled
  }
}

mutation disableEntry {
  save_entryname_default_Entry(title:"This entry should be DISABLED", id:1234, enabled:false) {
    title
    enabled
  }
}
```
3. Run the **disableEntry** mutation from the explorer. You should get a successful response stating that the entry was disabled. The entry title will have been updated.
4. Run the **enableEntry** mutation from the explorer. You should get a successful response, but the entry will still be disabled. The entry title will have been updated.

### Expected behavior

The entry modified in the **enableEntry** mutation should have it's state changed from disabled to enabled.

### Actual behavior

The entry is modified, but the entry's state remains disabled.

### Craft CMS version

4.4.10.1

### PHP version

8.2

**Comment by i-just** [comment]
Hi, thanks for reaching out. There are 2 things going on here:
1. If your entry was globally disabled, you couldn’t enable it for a specific site.
2. There’s a difference between the `enabled` and `enabledForSite` attributes in a multi-site scenario. If you disable an entry, the `enabled` value can still be `true`, but `enabledForSite` will be `false`. It’s not very clear in GraphQL, though.

I submitted a PR that fixes item 1 and added support for `enabledForSite` value to be returned too.

<img width="1407" alt="Screenshot 2023-05-17 at 10 06 58" src="https://github.com/craftcms/cms/assets/4500340/9e5205ba-4bd6-4503-a06d-803928736a60">

<img width="1427" alt="Screenshot 2023-05-17 at 10 23 39" src="https://github.com/craftcms/cms/assets/4500340/fb779409-5218-4803-b23c-ff82e5a03c88">

**Comment by ellukesmith** [comment]
Thanks for the response.

In my case, the section is only available to a single site and the propagation method is set to "only save entries to the site they were created in". Am I right in assuming that disabling an entry in a section that is only available to a single site causes that entry to be globally disabled, since it's no longer enabled for any sites?

I figured this may be the case, as I am passing in a `siteId` for both the enable and disable mutations, but I am still unable to re-enable the entry.

**Comment by i-just** [comment]
> Am I right in assuming that disabling an entry in a section that is only available to a single site causes that entry to be globally disabled, since it's no longer enabled for any sites?

Yes, that’s correct.

> I figured this may be the case, as I am passing in a siteId for both the enable and disable mutations, but I am still unable to re-enable the entry.

It will be possible after the PR I raised yesterday gets merged and released. For now, if your section is only available for a single site, you could run the query without the `siteId` parameter.

**Comment by ellukesmith** [comment]
I actually tried that, but running the mutation without a `siteId` returns an error response: `No such entry exists`. I assume it has to do with the propagation method set for the section.

This isn't a mission critical issue for us at the moment, as it's mostly to catch an edge case scenario - so I'm cool with waiting for the PR you raised to be merged through.

Thanks for your assistance on this one.

**Comment by brandonkelly** [comment]
Craft 4.4.12 is out with a fix for this. Thanks again for reporting!
