### ISSUE TITLE
[4.x]: Post Date & Expiry Date meta fields' date and time inputs render on separate lines

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#13216]
### Description

The date and time inputs for entries' Post Date and Expiry Date fields render on separate lines, which looks a bit clunky.

This started happening in Craft 4.4.10, possibly a side effect of https://github.com/craftcms/cms/commit/9d3ba64253c97ad05f81c6193956e98e77b67c29?

<img width="389" alt="CleanShot 2023-05-17 at 20 20 11@2x" src="https://github.com/craftcms/cms/assets/298510/f03e12c8-d59a-46d7-92f9-a5004b7d0a08">

### Steps to reproduce

1.

### Craft CMS version

4.4.11

### Operating system and version

macOS 12.6, MS Edge 113.0.1774.35

### Installed plugins and versions

None

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR to adjust.

**Comment by brandonkelly** [comment]
Craft 4.4.12 is out with a fix for this.
