### ISSUE TITLE
[4.x]: Missing 'Required' translation for lightswitch label in field settings

### ISSUE THREAD

**Issue by simplegr** [craftcms/cms#13230]
### Description

Missing 'Required' translation for lightswitch label in field settings at /settings/sections/xx/entrytypes/xx

![craft-missing-required-translation](https://github.com/craftcms/cms/assets/47791082/d0cc7b79-c2b4-46f4-98fc-060944e780ad)

### Craft CMS version

4.4.11

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Craft 4.4.12 is out with a fix for this.
