### ISSUE TITLE
[4.x]: Cancel button in widget settings not working

### ISSUE THREAD

**Issue by HigumaSan4050** [craftcms/cms#13239]
### Description
cancel widget settings does not work on saved widget.

### Steps to reproduce

1. add a widget with settings. for instance "Recent Entries". Save with the default settings.
2. reload the dashboard!
3. open the settings page for the widget again
4. missing event on the cancel button

### Craft CMS version

4.4.12

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Craft 4.4.13 is out with a fix for this. Thanks again!
