### ISSUE TITLE
Feature Request: Edit/Transform Assets From Asset Field

### ISSUE THREAD

**Issue by theskyfloor** [craftcms/cms#1324]
### Description

I would love it if I could activate the fancy new edit image asset modal from the asset field on the entry edit page in the backend.

### Steps to reproduce

1. Select asset from asset field

### Additional info

- Craft version: 3.0 beta 1

**Comment by TomDeSmet** [comment]
Yes, I second this request! Seems logical.

**Comment by brandonkelly** [comment]
@andris-sevcenko This would also give users a way to edit their profile photos

@benjamindavid Can you comp this up?

**Comment by andris-sevcenko** [comment]
@brandonkelly user photo editing works from the user profile (provided that profile image editing works, which does not at the moment). I think, though, that this ties together with the element editor factory that we talked about a few months back that would allow for Craft to have a distinctively different element quick-editor for each element type so this might require a bit more discussion and planning.

**Comment by rensverschuren** [comment]
Seems logical. On the other hand, people expect certain functionality to be applied in their current context only. So for example: 2 blog entries are using the same image. You edit the image in the edit of entry 1, then you won’t expect the image to be changed in entry 2 (I suppose). 
Because the asset manager is ‘global’, people expect the changes they do in the asset manager to be applied globally.

**Comment by TomDeSmet** [comment]
@rensverschuren That's true, but I don't think a lot of clients use the Asset Manager in their standard workflow. I think they often just upload their preferred asset in an entry and never care about where it sits in the Asset Manager.

**Comment by andris-sevcenko** [comment]
@rensverschuren While I agree with your train of thought here, I think that, however, the argument applies here that you can already edit the file name and all the meta data which affects the selected Asset across all entries.

@TomDeSmet support ticket history shows that while people that care where the Asset sits in the folder hierarchy might be the minority, they are a rather vocal minority :)

**Comment by theskyfloor** [comment]
@rensverschuren I guess when I envisioned this functionality it was more along the lines of clicking a gear icon or the like next to the uploaded image, that would activate the image editor modal so that you can crop, flip, or pick a focal point (ideally maybe that is configurable from the asset field settings, so you can pick only focal point, etc) when you are done editing you would select "Save as new asset" thereby avoiding an overwrite of the image if used elsewhere. Obviously it starts adding some crazy complication but it could be conditional and display a warning if you try and replace the asset (this asset is used in another entry are you sure you want to Replace Asset) or it could just not have that option altogether... or finally that could be configurable so that I could make it so that the asset field never allows the replace button to show when editing from the entry form. It could also be accomplished through saving metadata related to crop and focal point (i.e. non destructive editing). Obviously I understand these would all be choices that P&T have to make but it seems like there are plenty of graceful ways to handle this.

**Comment by leevigraham** [comment]
Related: #1727

**Comment by MattWilcox** [comment]
+1 for this; The "Assets" tab is somewhere our clients never visit for a couple of reasons, and thinking about it neither do we. Almost all interaction with any asset is done through an Asset field somewhere; for us and our clients.

Not being able to quickly set a focal point or enter the Image Editor from an asset field is likely to make the Image Editor and focal point features essentially pointless; they'll never be found.

Clients don't tend to find the Assets tab, fortunately - but when they do we discourage them from using it. Too many went trigger happy deleting "junk files" that were actually in use on Entries... guess what didn't work properly after? The entries.

**Comment by RitterKnightCreative** [comment]
+1 for this. 

To @MattWilcox's point, now that Craft 3 has image editing/cropping ability, being able to do some of those things would be really helpful right from that window.  

You can jump into related entries, being able to crop and view the asset in question could be helpful.

**Comment by brandonkelly** [comment]
This will be a thing starting with Craft 3 RC7 🎉

<img width="461" alt="screen shot 2018-01-20 at 6 35 52 am" src="https://user-images.githubusercontent.com/47792/35184685-bc431f1a-fdad-11e7-86ff-992567f99435.png">

**Comment by theskyfloor** [comment]
Love the display/interface choices!!

**Comment by TomDeSmet** [comment]
Superb!
