### ISSUE TITLE
[3.x]: Asset modal not usable on mobile devices

### ISSUE THREAD

**Issue by anita-chouhan** [craftcms/cms#13240]
### Description
In the Craft CMS control panel we have a Redactor field. The Redactor type fields have an option to insert image. If you try to insert image on small screen devices the available buttons inside the Asset modal window are not visible properly making it unusable.

**Other information**
<img width="390" alt="Screenshot 2023-05-24 at 2 43 35 PM" src="https://github.com/craftcms/cms/assets/30666052/ec60cbed-416f-4ff0-b089-3eddb036b1d0">

Field Settings
<img width="703" alt="Screenshot 2023-05-24 at 1 31 31 PM" src="https://github.com/craftcms/cms/assets/30666052/60fd5203-6edb-42c5-90a1-e75512e131a1">

### Steps to reproduce

1. Add a *Redactor* field to any entry type with image transform options.
2. Try to insert an image inside this field using a mobile device.

### Expected behavior
All the buttons should be visible inside the Asset modal window.

### Actual behavior
The buttons are cut at the bottom of the Asset modal window.

### Craft CMS version

3.8.12

### PHP version

7.4

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
We’ve fixed this in Craft 4, however we weren’t able to make the same change in Craft 3 due to backwards-compatibility issues.
