### ISSUE TITLE
[4.5.x]: Table with static/default rows doesnt initialize in already existing entries

### ISSUE THREAD

**Issue by FoxtrotCZ** [craftcms/cms#13245]
### Description
I am trying to create new table with static rows and row headings defined in default values as shown in this PR https://github.com/craftcms/cms/pull/13231
But table doesnt create it's rows and row headings when added to already existing entry/entry type.

### Steps to reproduce

1. Create or have some already existing entry type and entry.
2. Create new table field with static rows and some default values. For example row headings.
3. Add this new table field to the entry type.
4. Open your entry.

### Expected behavior
New table should appear in my entry with predefined default values. In this case predefined row headings.
![image](https://github.com/craftcms/cms/assets/10333810/2cbdcd93-aa0d-417c-8f59-25f01347540f)

### Actual behavior
Empty table created.
![image](https://github.com/craftcms/cms/assets/10333810/cad1bec7-d308-4da2-ad3d-716c1668df27)

### Workaround
When empty table is created you can go back to table field and disable static rows.
In entry add some rows, one is enough and no need to fill them. You just need to initialize the table.
Again go to table field and reenable static rows.
Now your entry should populate with correct number of default rows and row headings if defined.

### Craft CMS version

4.5.x-dev

### PHP version

8.1.16

### Operating system and version

Linux 5.15.0-72-generic

### Database type and version

MariaDB 10.6.12

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for testing and reporting that! This is now fixed on the `4.5` branch.
