### ISSUE TITLE
[4.x]: Uploaded image size are a little bit different that before upload

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#13257]
### Description
I have a front-end form where users can upload pictures.
When picture are selected in the file input, I'm immediately returning the file size to the view using this:

> const i = Math.floor(Math.log(size) / Math.log(1000));
> return (
> 	(size / Math.pow(1000, i)).toFixed() * 1 +
> 	" " +
> 	["{{ 'B' | t }}", "{{ 'KO' | t }}", "{{ 'MO' | t }}", "{{ 'GO' | t }}", "{{ 'TO' | t }}"][i]
> );
> 

At this point, I can see that the returned value is similar to the file size on my computer.
However, after submit, sometimes the returned files in Craft have a little bit difference of 1 KB.
I can see this when I download the just uploaded files in the Assets volumes.

In the context of my form, I have a confirmation page before submit where I'm querying the file size using the [filesize](https://craftcms.com/docs/4.x/dev/filters.html#filesize) filter. That's where I'm querying using Craft's Twig instead of JS.

Is it a bug? Why file size are chaning after upload? How can I get my image sizes untouched after upload?

### Craft CMS version

4.4.13

### PHP version

8.0.20

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out. When asset is uploaded to Craft, they are being processed (and not uploaded "as is"). This processing can account for some changes in filesize. Some info can be found in this stackexchange thread: https://craftcms.stackexchange.com/questions/35335/uploading-assets-png-changed-from-72-dpi-to-96

**Comment by romainpoirier** [comment]
Thank you. As pointed in the stackexchange thread, this would be useful to mentioned in the Craft documentation.

As Craft is doing asset's name transformations to prevent duplicated names, why Craft would not save somewhere the "real" file size as it was before the upload? That would be a solution for me to present the "correct" initial file size as it was uploaded.

If you don't think it's a good idea, what solution would you recommend, storing the "real" file size before the file is being processed? This could be store in a custom field on the asset, but I'm not sure of when/how to catch the file size and store it. Would it be available on `EVENT_BEFORE_SAVE` or another event?

**Comment by i-just** [comment]
You could pass the filesize you grabbed with JS as another value in your form.
