### ISSUE TITLE
[4.4.13]: Cli command 'craft resave/entries' make neo blocks loose their nesting

### ISSUE THREAD

**Issue by Tim-Wils** [craftcms/cms#13256]
### Description
We're busy with a Craft 3 to 4 update for our client.
Almost everything went really smooth, until we arrived at the point where we had to resave all the entries.

Doing php craft resave/entries affects entries neo blocks tomake them loose their nesting. 

### Steps to reproduce

1. Do php craft resave/entries and all the blocks loose their nesting.

Screen before:
![image](https://github.com/craftcms/cms/assets/90032/3468ccee-463b-41e6-8e65-073d2100fe3a)

Screen after doing: php craft resave/entries --element-id 25867
![image](https://github.com/craftcms/cms/assets/90032/8785c688-ebc6-4eca-af36-efa5028e622e)

### Craft CMS version

Craft Pro 4.4.13

### PHP version

8.1.3

### Operating system and version

Linux 5.15.90.1-microsoft-standard-WSL2

### Database type and version

MariaDB 10.2.44

### Installed plugins and versions

-
Neo is on dev-main with this fix from Brandon Kelly to try and if this will fix it, but it doesn't: https://github.com/spicywebau/craft-neo/commit/7232a308ab9cf0266dc008f62514ea93489e8f75

**Comment by i-just** [comment]
Hi, thanks for reaching out. I'm having trouble replicating this issue. Any chance you can send your `composer.json`, `composer.lock` and database export from before you run the resave command to support@craftcms.com so that we can dig deeper?

**Comment by i-just** [comment]
@Tim-Wils, thanks for sending over the files. I’ve narrowed it down to a conjunction of Preparse Field and Neo. I’ll update again once I know more.

**Comment by i-just** [comment]
Not a problem at all. Glad you managed to make it work!
