### ISSUE TITLE
[4.4.13]: Thumbnails not loading when quickly switching between entry sources

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#13253]
### Description

Asset thumbnails not loading when quickly switching between entry sources

### Steps to reproduce

1. Have multiple sections with an asset field that is displayed as a thumb in the entry index.
2. Quickly switch between the corresponding sources/sections in the entry index. Do this multiple times and try to do it pretty fast, so there is not enough time to load all the thumbs before you switch.

### Expected behavior
All thumbnails should load.

### Actual behavior
Thumbnails stop appearing/loading. 
The following error appears in the console:

<img width="923" alt="image" src="https://github.com/craftcms/cms/assets/19857599/398c593e-91cf-47c2-9070-33d5cb9c6090">

If the user refreshes the page the thumbs reappear.

### Craft CMS version

4.4.13

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out. Is it only happening when the transforms are being generated for the first time?

**Comment by thupsi** [comment]
At first I thought so, but no. It happens even if transforms have been generated.

**Comment by thupsi** [comment]
The issue seems to be a bit more widespread. It also sometimes happens in asset select modals without the editor frantically switching sources. Sorry for being vague, haven't had time to isolate the exact conditions, but there have been similar reports in Discord.

**Comment by brandonkelly** [comment]
Craft 4.4.14 is out with a fix for this. Thanks again for reporting!
