### ISSUE TITLE
[4.x]: Using asSuccess() rather than asModelSuccess() for successful ajax responses on the users/save-user action

### ISSUE THREAD

**Issue by samhibberd** [craftcms/cms#13267]
### Steps to reproduce

1. Save a user using the users/save-user endpoint via ajax

### Expected behavior

Return via the `asModelSuccess()` method so that the json result includes the `redirect`, `modelName` and model properties.

This [line](https://github.com/craftcms/cms/blob/82629eef9b40a923471ae681ef8896865b3ee1bf/src/controllers/UsersController.php#LL1571C1-L1572C1) should be:

`return $this->asModelSuccess($user, data: $return);`

### Actual behavior

Json result just includes the id `{ id: USERID }`

### Craft CMS version

4.4.11

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Craft 4.4.14 is out with this change. Thanks for pointing it out!
