### ISSUE TITLE
[4.x]: "Available updates" excludes Craft/plugins with expired licenses

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#13274]
### Description
Below is a screenshot of the available updates page for a live client site I'll be running maintenance on soon. I email them in advance with a list of the updates to be made, and noticed that this says "3 available updates" even though there are actually 5 sets of updates available. Only thing I can think of is that two of the licenses have expired, which I am letting them know they need to renew before I run maintenance.

![image](https://github.com/craftcms/cms/assets/1250017/a6310460-cf4c-4e5e-aa39-04234f469f8e)

While I kind of understand how this could be deliberate, surely it's important for clients and us to know there are updates available even if the licenses have expired?

### Craft CMS version

4.4.8

Update: The badge in Utilities correctly shows 5, it's just the text at the top of the updates page

![image](https://github.com/craftcms/cms/assets/1250017/bf5573ff-062b-4b38-96a2-79a5bc412e36)

**Comment by i-just** [comment]
Hi, thanks for reaching out. I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 4.4.14 is out with a fix for this.
