### ISSUE TITLE
[4.x]: Dropdown Field not working in Preview Mode

### ISSUE THREAD

**Issue by pau-ker** [craftcms/cms#13271]
### Description
Dropdown Fields are not selectable when i switch to "Preview-Mode". 
Outside of "Preview-Mode" they do work.

Tested in Firefox and Chrome.

### Actual behavior
https://github.com/craftcms/cms/assets/20379982/e4063f10-d03a-4ccb-bf38-8d067d7b2f8d

### Craft CMS version

4.4.13

### PHP version

8.2.6

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out. I’m having a hard time reproducing this error. Are there any errors in the console when this happens?

**Comment by brandonkelly** [comment]
Have you made any control panel CSS customizations?

**Comment by pau-ker** [comment]
I apologize, it was my fault. I was trying to get fancy with CP-CSS. You are right Brandon. Sorry for bothering.
