### ISSUE TITLE
[4.x]: Delete Section - Site Relationship after Site deletition

### ISSUE THREAD

**Issue by HigumaSan4050** [craftcms/cms#13279]
### Description
After Deleting a Site, a relation entry in the database table 'sections_sites' is still there
cause InvalidConfigException, when we want to access section.getSiteSettings()

### Steps to reproduce

1. create a additional site
2. assign section to this site
3. delete the site
4. access section.getSiteSettings() of the section in a twig file

### Expected behavior
delete the relation between section and site in the table 'sections_sites'

### Craft CMS version

4.4.13

### PHP version

8.2

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out.

By default, Craft will do a soft delete and keep the site around for another 30 days (or the value you specified in [`softDeleteDuration`](https://craftcms.com/docs/4.x/config/general.html#softdeleteduration)). Once the soft delete duration has passed, the garbage collection will remove the rows from the database. As `sites` and `sections_sites` are linked with a foreign key constraint, once the site row is deleted, so is the corresponding row in the `sections_sites` (or you can trigger the garbage collection ahead of time via CLI command: `php craft gc/run`).

Hopefully, that clears things up, but please let me know if I missed your point.

**Comment by HigumaSan4050** [comment]
thanks for explanation
