### ISSUE TITLE
[4.x]: Selectable assets/entries conditions

### ISSUE THREAD

**Issue by torgeirbeyer** [craftcms/cms#13276]
### Description
It is not possible to have and/or between the conditions you set on assets/entries on fields. It would be very nice to be able to use these for for example show entries by currentUser.id OR from some website editor group. 

### Steps to reproduce

1. 

### Expected behavior
One should be able to select multiple conditions without them being chained with AND

### Craft CMS version

4.4.13

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out. This is currently working as expected, but there’s a discussion opened with the same idea: https://github.com/craftcms/cms/discussions/11287. Feel free to add your thoughts/follow along there!
