### ISSUE TITLE
[4.4.13]: Sections List sorted incorrectly

### ISSUE THREAD

**Issue by ivesho** [craftcms/cms#13275]
### Description
Sections List sorted incorrectly.
![entries](https://github.com/craftcms/cms/assets/48641341/b72dea91-365d-41e2-a223-78b9dce17abe)

![sections](https://github.com/craftcms/cms/assets/48641341/e781bd03-97d0-45b1-bc0a-3f23dabe038b)

### Steps to reproduce

1.

### Craft CMS version

Craft Pro 4.4.13

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out.

I suspect it’s the same as this issue: https://github.com/craftcms/cms/issues/12573.

In a nutshell: if you never customised sources and you add a new section, it will be placed at the end of its default group (under “Structures” for a new structure, under “Channels” for a new channel etc.). However, once you’ve customised sources, we can no longer follow that default behaviour, so new sections are placed at the end of the list after a blank heading.

You can adjust the order again by going to Entries > Customize sources.

I hope this helps. I will close this now, but please feel free to reach out again if I missed your point.
