### ISSUE TITLE
Sensitive credentials viewable from control panel

### ISSUE THREAD

**Issue by dmlogic** [craftcms/cms#1328]
### Description

The use of DotEnv means sensitive credentials are viewable in plain text in the CMS.

This is bad as someone who has admin access to the CMS should not necessarily know things like db passwords and API keys.

It should be possible to disable this output, ideally via another .env setting

### Steps to reproduce

1. Log in to CMS as admin
2. Go to Utilities >PHP Info

### Additional info

- Craft version: 3.0.0-beta.1
- PHP version: 7.1.0-2+deb.sury.org~xenial+1
- Database driver & version: mysqlnd 5.0.12-dev - 20150407
- Plugins & versions: None

**Comment by themccallister** [comment]
@dmlogic that is a really solid point to make out, I know a lot of developers that forget`phpinfo()` dumps out everything in the environment. Having the ability to hide those items would be ideal. 

On the other side of the discussion, if you are giving a user admin access to the CMS there is a lot more harm that could be done.

**Comment by michaelrog** [comment]
Revealing env vars to CMS admins is *technically* unavoidable — Even if Craft doesn't display that info in the Utils, it would be trivial for an Admin to install a plugin that reveals the `phpinfo` data.

However, it's a good idea to try to prevent Craft from displaying sensitive info _haphazardly_, or _accidentally_.

This issue is potentially related to my request in #1301 (to make log redactions more configurable).

**Comment by dmlogic** [comment]
> it would be trivial for an Admin to install a plugin that reveals the phpinfo data

that's an extremely good point. I guess it's just a little scary seeing the credentials on screen. Providing that access to this screen is only granted to those with permission to install plugins then I guess it becomes a case of strong user permission management.

**Comment by takobell** [comment]
Ultimately, I think #1301 is the right solution here. But in the meantime, is omitting all environment variable output from `utils/phpinfo` too heavy handed?  We already do some skipping of other phpinfo output on that page.

**Comment by dmlogic** [comment]
> is omitting all environment variable output from utils/phpinfo too heavy handed

I don't think it is heavy handed. I take the point that an admin _could_ install a plugin but that's still a bigger barrier than just clicking on a menu item - possibly on an unattended desk. I can't think of a single good reason why `$_ENV` vars need to be exposed on screen like this.

**Comment by ostark** [comment]
Obfuscation of output for $_ENV values for keys with this pattern *PASSWORD* || *SECRET* || *KEY*, should cover most cases. Laravel's debugbar introduced obfuscation [after we blogged about that topic](https://blog.fortrabbit.com/how-to-keep-a-secret).

https://github.com/barryvdh/laravel-debugbar/commit/89a88cfcb8744da93c98f00a7576ab8115373a07
