### ISSUE TITLE
[4.x]: Missing Info on Element hard_delete on Event EVENT_AFTER_DELETE_ELEMENT

### ISSUE THREAD

**Issue by HigumaSan4050** [craftcms/cms#13280]
### Description
When event EVENT_AFTER_DELETE_ELEMENT is fired the hardDelete Flag is always false. Even on "Delete permanently"

### Steps to reproduce

1. create a entry
2. delete the entry
Event EVENT_AFTER_DELETE_ELEMENT fired. event->element->hardDelete = false
3. switch status button to "Trashed"
4. "Delete permanently" the entry
Event EVENT_AFTER_DELETE_ELEMENT fired. event->element->hardDelete = false

### Expected behavior
when the element is permanently deleted, property 'hardDelete' should be true

### Craft CMS version

4.4.13

### PHP version

8.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Craft 4.4.14 is out with the fix for this. Thanks again!
