### ISSUE TITLE
[4.x]: editable table - select column type does not show optgroups text when adding the new row

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#13298]
### Steps to reproduce
- Add editable table widget to control panel page
- Widget must have select type column and select data must have optgroups
- When adding the new row, optgroups are without text. If widget is initialized with rows already present, optgroups in these rows show normally.

### Craft CMS version

4.4.13 

### PHP version

8.1

### Installed plugins and versions

-

**Comment by i-just** [comment]
@piotrpog I think I’m missing something here. Could you please provide a bit more info on this one? Are you referring to the native Table field type or something else?

**Comment by piotrpog** [comment]
@i-just 
I am refering to twig macro used by plugin developers to create admin pages.
https://github.com/craftcms/cms/blob/develop/src/templates/_includes/forms/editableTable.twig

**Comment by i-just** [comment]
Perfect, thank you!

**Comment by i-just** [comment]
I’ve tracked it down. Thanks for reporting! PR submitted.

**Comment by brandonkelly** [comment]
Craft 4.4.14 is out with the fix for this. Thanks again!
