### ISSUE TITLE
[4.x]: Field conditions, not all fields visible

### ISSUE THREAD

**Issue by lennonpuype** [craftcms/cms#13296]
### Description
When you have multiple fields with the same name (I know this is not the way to go 😉  ) You have an issue with the field conditions that when there are with the same name, only 1 field with that name is visible.

It is just a bug I came across, but nothing urgent. I just didn't saw why it would work, but then eventually did 😉 

### Steps to reproduce

1. Have a field you want to hide for example when a toggle is checked
2. Make fields with the same name, but different handles. For example "Toggle" with handle "toggle" and "Toggle" with handle "toggle2"
3. Add this field to a structure or neo block (plugin field) or any other thing to add this to
4. Set the condition of the field you want to hide and you see that only 1 toggle (the one with handle "toggle") will be visible to use as condition, but I want to use "Toggle" with handle "toggle2"

### Expected behavior
I want both fields with the same name to be checked in the condition. So not title related like it is now, but handle related.

![Screenshot 2023-06-08 at 12 57 29](https://github.com/craftcms/cms/assets/30866096/fc83a22c-6738-43b3-b0e4-f4c1dccf90e6)

### Actual behavior
Only 1 field of the same name is now visible

![Screenshot 2023-06-08 at 12 58 21](https://github.com/craftcms/cms/assets/30866096/5f52f81b-5f00-4e86-9b27-c7500fbda9b8)

### Craft CMS version

4.3.10

### PHP version

8.0

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting and for the clear description! I raised a PR to adjust this.

**Comment by brandonkelly** [comment]
Craft 4.6.0 was just released with a fix for this. Now custom fields’ condition rule options will start showing the field handle as well, for admins with the “Show field handles in edit forms” preference enabled. So those option labels will no longer be duplicates of each other.

(Non-admin users will still have no way of selecting duplicate condition rules though. If that’s a problem, you will need to give your fields unique names.)
