### ISSUE TITLE
[4.5]: Changing table field column type settings stringifies Date object

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/cms#13303]
### Description

`[object Object]` is sometimes output when switching between column types in Table field settings.

### Steps to reproduce

See video!

https://github.com/craftcms/cms/assets/1895522/96ea294c-843c-484c-b907-650adaea3c5e

1. Create a new column in a Table field's settings;
2. Set it to **Date**;
3. Add one or more rows to the **Default values** table;
4. Change the column type to **Single-line text** or any other plain textual type
5. Observe `[object Object]` output in default field;

Additionally, switching from a **Date** column type to **Checkbox** causes the default to be _checked_. Similarly, switching from **Date** to **Color** causes a JS error. 🚨

### Expected behavior

Incompatible column type data is discarded when switching

### Actual behavior

Undesirable default value is inserted into the default rows, or a JS error occurs.

### Craft CMS version

4.5

### PHP version

8.0.28

### Operating system and version

macOS 13.1

### Database type and version

MariaDB 10.4.28

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

None!

**Comment by brandonkelly** [comment]
Craft 4.4.14 is out with a fix for this.
