### ISSUE TITLE
[4.x]: SVGs in local filesystem without public URLs aren't loading in the Control Panel

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#13306]
### Description

We're seeing an issue where the CP doesn't show preview images for any SVG assets. JPG images work fine. SVGs can be uploaded normally and the asset shows up in the asset list, but the small thumbnail doesn't show up, neither in the asset index nor as a preview in image fields:

![Screenshot 2023-06-12 at 17 25 00](https://github.com/craftcms/cms/assets/10146880/beb0d350-a0fc-4099-afaf-9aa0b3495b78)

The first image is a JPG, the others are SVGs.

![Screenshot 2023-06-12 at 17 25 20](https://github.com/craftcms/cms/assets/10146880/e00ca45c-6481-468d-9a7c-1fdf5d8bdf44)

The asset volume uses a local filesystem that doesn't have public URLs, though the target folder _is_ inside the web root:

![Screenshot 2023-06-12 at 17 22 39](https://github.com/craftcms/cms/assets/10146880/0b9e20e8-61ee-4bcb-95c2-70d13e73613c)

![Screenshot 2023-06-12 at 17 22 54](https://github.com/craftcms/cms/assets/10146880/304ef563-eee7-4d29-a552-44ee5092281d)

The `@webroot` alias is defined as follows in the `config/general.php`:

```php
'aliases' => [
    '@webroot' => dirname(__DIR__) . '/web',
    '@web' => App::env('PRIMARY_SITE_URL') ?: '/',
],
```

I can see on the filesystem that uploaded files are stored in the correct path (`web/cms-assets/productAttributes`).

I've checked the network tab to see what's going on. For JPG and other bitmap images, the preview image is loaded from an action URL like this:

```
/admin/actions/assets/generate-fallback-transform?assetId=228&transform=a64e7847592d45a7ae7e2c30f7b6f415b9594fd456c896418a9e617c41d32f0834x22_crop_center-center_none_ns&site=de_DE
```

However, for the SVGs, Craft tries to load the thumbnails using their filename from the webroot:

```
/admin/undraw_engineering_team_a7n2.svg?v=1686583192
```

This URL returns a 404 response, since the direct path relative to the webroot for this file would be `cms-assets/productAttributes/undraw_engineering_team_a7n2.svg`.

I don't think it's a configuration issue, since JPGs in the same asset volume work fine. Is loading the file directly a fallback if Craft assumes it can't generate thumbnails for SVGs? Or is it not allowed to turn off the public URL setting if the base folder is inside the webroot?

### Craft CMS version

4.4.13

### PHP version

8.2

### Operating system and version

OS X and Linux

### Database type and version

MySQL 8.0.32

### Image driver and version

GD 8.2.4

**Comment by i-just** [comment]
Hi, thanks for reaching out. It looks like you’re using a separate Filesystem for the transforms “Bildtransformationen”? Would you mind sharing the config of that FS?

**Comment by i-just** [comment]
Excellent, thank you @MoritzLost!

Do you have [`transformSvgs`](https://craftcms.com/docs/4.x/config/general.html#transformsvgs) set to `false`? 
I can replicate what you’re describing, only with that setting set to `false`. The SVG thumbs are not showing, and the 404 is triggered for them with the path referring to `/admin/<filename>.svg`.

**Comment by MoritzLost** [comment]
@i-just Yes, `transformSvgs` is set to `false`! We never want SVGs to be transformed, so we always keep that setting off. I assumed this just influenced the frontend, didn't realize it would impact the backend like this as well.

But the fallback behaviour (`admin/file.svg`) is still a bug, right? If transform SVGs is false, shouldn't Craft just load the original image to use as a thumbnail (either directly using it's URL if it's inside a webroot, or using a Controller method)? Or maybe just ignore the `transformSvg` setting for thumbnail generation in the backend?

**Comment by i-just** [comment]
Ah, glad we got to the bottom of it!

Yes, I’d say that’s still a bug. I’m looking into it now. I believe the intended behaviour is to show the fallback icon with the file extension (see the image below), but I’ll confirm that with the rest of the team before creating a PR.

<img width="1253" alt="Screenshot 2023-06-13 at 12 09 44" src="https://github.com/craftcms/cms/assets/4500340/d2e7957a-a439-4d49-81db-a3568d2d59e9">

**Comment by MoritzLost** [comment]
@i-just Thanks, sounds good!
So just to confirm, seeing the fallback icon would be the expected behaviour because Craft can't load the original image because of the public URL setting, and can't create a thumbnail because of the `transformSvgs` setting?

I don't quite understand why the `hasUrls` setting of the filesystem is even be considered to decide whether to display the asset in the backend?

**Comment by i-just** [comment]
I’ll double-check with the rest of the team on that and get back to you once we had a chance to discuss.

**Comment by i-just** [comment]
We’ve discussed it internally, and the correct behaviour should be: even if the transform FS is set not to have public URLs or the asset is an SVG or GIF, and `transformSvgs` or `transformGifs` is set to `false`, respectively, in the Control Panel, we still show the thumbnail image (via adjusted fallback transform) for anything that can be manipulated as an image. The fallback icon (a file “silhouette” with the extension text) should be used for assets that can’t be manipulated as images.

PR has been raised and is currently targeting Craft 4.5.

**Comment by brandonkelly** [comment]
Craft 4.5.0 is out with that change.
