### ISSUE TITLE
[4.x]: Preloading singles doesn't work inside macros

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#13312]
### Description

I'm seeing an issue where accessing a single section implicitly by section handle in Twig using the `preloadSingles` config doesn't work inside macros. I have a single section `form_settings` with a field `security_question`.

In a regular template, this works fine – the variable `form_settings` automatically gives me the correct entry without having been defined manually:

```lang-twig
{{ form_settings.security_question }}
```

But inside a macro, I'm getting an error:

```lang-twig
{% macro security_question() %}
    {{ form_settings.security_question }}
{% endmacro %}
```

> Twig Runtime Error – [Twig\Error\RuntimeError](http://twig.sensiolabs.org/api/2.x/Twig/Error/RuntimeError.html)
> Variable "form_settings" does not exist.

Note the macro lives in a _different_ template than the one I'm calling it from. Not sure if that's relevant.

### Steps to reproduce

1. Create a single section (`form_settings`) with a text field (`security_question`).
2. Set `preloadSingle` to `true` in `config/general.php`.
3. Put the macro in the code above in a template and execute it (from another template).

### Expected behavior

Preloading singles should work the in the same way inside macros as it does outside them.

### Actual behavior

Preloading singles doesn't work inside macros.

### Craft CMS version

4.4.13

### PHP version

8.2

**Comment by brandonkelly** [comment]
Thanks for reporting that! fixed for the next release.

**Comment by MoritzLost** [comment]
Great, thanks @brandonkelly!

**Comment by brandonkelly** [comment]
Craft 4.4.15 is out with a fix for this. Thanks again for reporting!
