### ISSUE TITLE
[4.x]: Temporary folders are being created when using {slug} in Asset field

### ISSUE THREAD

**Issue by jimirobaer** [craftcms/cms#13311]
### Description

Folders are being created when a new entry containing an Asset field, that has been configured to use the `{slug}` as the Default Upload Location, is created.

The folders are named after the draft, ex. `temp_sftzbaeqedinubfrccouaofyfyyintwesbod`. These folders are automatically created, even before an asset is uploaded on the field. The field just needs to be present on the entry type.

### Steps to reproduce

1. Create an Asset field and add `{slug}` to the Default Upload Location.
2. Add the field to an entry type which has drafts enabled.
3. Create a new entry using the entry type.

### Expected behavior

No folders linked to the draft to be created on each new entry.

### Actual behavior

Folders linked to the draft being created on each new entry.

<img width="849" alt="Screenshot 2023-06-13 at 14 46 52" src="https://github.com/craftcms/cms/assets/8984769/8532234b-1cac-4b8e-a6e1-3c6137770ef8">

### Craft CMS version

4.4.13

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 4.4.15 is out with a fix for this. Thanks again for reporting!

**Comment by sandrodunkel** [comment]
Since this fix, Default Upload Location does not seem to work for me anymore. Does not work with a dynamic path (e.g. `{slug}` or `{section}`) and does not work with a fixed path (e.g. "/pages"). Worked perfectly on Craft 4.4.12.

<img width="745" alt="image" src="https://github.com/craftcms/cms/assets/102292752/8aa79188-1874-4196-9196-8465503ba7ac">

**Comment by i-just** [comment]
@sandrodunkel, I just did a quick test and the “Default Upload Location” works as expected when uploading directly into an assets field (via the “Upload files” button).
<img width="303" alt="Screenshot 2023-07-21 at 13 36 26" src="https://github.com/craftcms/cms/assets/4500340/b20ff666-6db8-48ea-a0af-3f05cfdba689">

When using the “Add an asset” button, the user can choose the location to upload to (within what’s allowed by the field).

**Comment by sandrodunkel** [comment]
You're right—my bad. Thanks @i-just
