### ISSUE TITLE
[4.x]: Invalid token message pane

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#13316]
### Description

As of Craft 4.4.14, an “Invalid token” message pane is being output and displayed when using a preview link (with a valid token). The page displays as expected, but the message pane is overlaid (and CSS styling seems to be off too).

![Screenshot 2023-06-14 at 12 59 06](https://github.com/craftcms/cms/assets/57572400/807d308a-1948-48f8-9bf7-93389995d682)

![Screenshot 2023-06-14 at 12 59 52](https://github.com/craftcms/cms/assets/57572400/4bf4a519-6207-45eb-ab21-d47362eae143)

### Steps to reproduce

1. Modify an entry in the CP.
2. Click the “View” button to preview the changes.

### Craft CMS version

4.4.14

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Strange, I’m not able to reproduce that. Looks like somehow the control panel CSS is getting included in your front-end as well. Can you try setting a conditional breakpoint `yii\web\View::registerAssetBundle()` where `$name === 'craft\web\assets\cp\CpAsset` and see what’s registering it for front-end requests?
