### ISSUE TITLE
Reserved words "value" "type"

### ISSUE THREAD

**Issue by nexflo** [craftcms/cms#1331]
Seems a couple of words are allowed - but they are translated within the control panel to other languages - which is confusing....

I would add "type", and "value" to this list.

protected static $baseReservedWords = array('id', 'dateCreated', 'dateUpdated', 'uid', 'this', 'true', 'false', 'y', 'n', 'yes', 'no', 'classHandle', 'handle', 'name', 'attributeNames', 'attributes', 'attribute', 'rules', 'attributeLabels', 'fields', 'content', 'rawContent', 'section');

**Comment by brandonkelly** [comment]
Agreed and added. Thanks!
