### ISSUE TITLE
[4.x]: Incorrect (duplicate) fields and UI elements when creating an entry and switching entry type

### ISSUE THREAD

**Issue by thijskaspers** [craftcms/cms#13314]
### Description

We have a section with 3 entry types. Each entry types has a different field set and some UI elements (headers, tips, etc.). 

When we create a new entry in that section and switch between entry types, the fields aren't correctly updated. When switching from entry type 1 to entry type 2, we still see fields and elements from entry type 1, they get mixed up.

Something seems to be wrong with hiding/showing fields after changing the entry type. If you change it and then refresh the page, it then does show the correct fieldset.

### Steps to reproduce

1. Create a section with multiple entry types, each with different fields and UI elements
2. Create a new entry for that section
3. Switch entry types, and check the fields

### Craft CMS version

4.4.14

### PHP version

8.1.18

### Operating system and version

Linux 6.3.6

### Database type and version

MariaDB 10.6.12

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-50)

**Comment by i-just** [comment]
Hi, thanks for reaching out. It sounds like it could be similar to this one: https://github.com/craftcms/cms/issues/11746. Can you please try the command Brandon mentioned on that issue (`craft utils/fix-field-layout-uids`) and see if it fixes it?

**Comment by thijskaspers** [comment]
Thanks Iwona, you're right! Running the command fixed it. The issue probably happened to us because of using Verbb's "Cloner" plugin to clone entry types, and then make some changes. That will give fields and UI elements the same UUID's.

**Comment by i-just** [comment]
Great news! Glad it’s all working as expected now :)

**Comment by thijskaspers** [comment]
@engram-design just tagging you here for the sake of it. Apparently cloning entry types can result in this "bug" happening, because the UUID's will be copied. Maybe there's something that can be done when cloning with Cloner. Not sure if it's desirable though to change the cloning behaviour. Perhaps having different UUID's might lead to other issues (or not?), unsure about the consequences.

**Comment by engram-design** [comment]
@thijskaspers if you’d be able to mention this as an issue on the https://github.com/verbb/cloner and I can maybe follow up there?

**Comment by brandonkelly** [comment]
Submitted a PR to fix that: verbb/cloner#15

**Comment by engram-design** [comment]
Thanks @brandonkelly 🤩

**Comment by thijskaspers** [comment]
Awesome, thanks @brandonkelly and @engram-design!
