### ISSUE TITLE
[4.x]: Matrix field is incorrectly labelled as translatable with custom propagation key format

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#13329]
### Description

I'm seeing an issue where a matrix field gets the little icon to indicate a translatable field (_This field is translatable_) even though it isn't translatable in that context.

![Screenshot 2023-06-16 at 12 43 06](https://github.com/craftcms/cms/assets/10146880/965798c8-420a-4fd5-9eac-eb43efa0877f)

### Steps to reproduce

1. Create a Matrix Field, set the _Propagation Method_ to _Custom…_ and use the following template:  
`{{ section.type == 'single' ? site.handle }}`
2. Add the Matrix Field to one Single section and one Channel or Structure section.
3. Open the entry form for an entry in both sections. The field will be labelled as translatable in both, even though it should only do so for the entry in the Single section.

### Expected behavior

We want the matrix blocks to propagate between sites in Structure or Channel sections, but we _don't_ want them to propagate in Single sections. The field should only be marked as translatable on entries in Single sections.

### Actual behavior

The actual propagation behavior is correct (blocks are propagated between sites on Structure and Channel sections, but not on Single sections). However, the field is labelled as translatable in Structure and Channel sections, even though it isn't translatable in those contexts.

We use the same template for the _Translation Key Format_ for regular text fields, this works correctly and the icon only shows up in the appropriate context.

### Craft CMS version

4.4.10.1

### PHP version

8.2

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR.

**Comment by brandonkelly** [comment]
Craft 4.4.15 is out with a fix for this. Thanks again for reporting!
