### ISSUE TITLE
Date/Time Field throws exception when saving an entry

### ISSUE THREAD

**Issue by my2ter** [craftcms/cms#1332]
### Description

Date/Time Field throws exception when saving an entry

### Steps to reproduce

1. Add a field Date\Type to an entry
2. Edit the entry and add a date
3. Save the entry

Throws **Object of class DateTime could not be converted to string** in **src/helpers/StringHelper.php:843**

### Additional info

- Craft version: 3.0.0-beta.1
- PHP version: 7.1.1-1+deb.sury.org~xenial+1
- Database driver & version: MySQL 5.7.17
- Plugins & versions:
  -craftcms/aws-s3 1.0.1

**Comment by brandonkelly** [comment]
(commit feec18fde5bc3092a01865cb28675c60bbc5323e referenced this by mistake. Was really fixed in 7eb0681f4ae542968bda79fd26f5d90e7d2b49c0)
