### ISSUE TITLE
[4.x]: Transforming animated Gif to webp creates memoryleak

### ISSUE THREAD

**Issue by CMeldgaard** [craftcms/cms#13326]
### Description
We were experience issues, where a single process was using up all the memory on the server and all the swap memory. We tracked it down to that, is was a gif, which was animated, was beeing converted to webp. The creates som sort of memoryleak, that crashes the entire server.

### Steps to Reproduce
Upload image to server
Try to transform to webp
Server memory spikes out, until server craches

### Craft CMS version

4.4.8

### PHP version

8.0

### Operating system and version

64bit Amazon Linux 2/3.5.8

### Database type and version

Maria DB

### Image driver and version

ImageMagick 7.1.0-50

**Comment by brandonkelly** [comment]
This is a known issue with ImageMagick, and unfortunately not something we can do anything about. It’s why there’s a [`transformGifs`](https://craftcms.com/docs/4.x/config/general.html#transformgifs) config setting, which can be set to `false` to disable GIF transforms entirely.
