### ISSUE TITLE
[4.x]: Please limit the number of tags in tag fields responses / start search only after x chars

### ISSUE THREAD

**Issue by kringkaste** [craftcms/cms#13322]
### Description

When you have a huge list of tags (our customer has >40.000 tags) in a tag group and you are typing in a tag field, the search starts after the first character. The backend responses very fast, but the browser (on a normal business desktop) is not able to render the dropdown and crashes with "page unresponsive". 

Yes, you can have different opinions about the usefulness of 40.000 tags :) But the customer is using this heavily with his > 100.000 assets.

It would be very helpful to either limit the number of returned elements or to let the search start only after x characters. Preferably both only configurable for use cases like this.

### Craft CMS version

4.4.13

### PHP version

8.1

**Comment by brandonkelly** [comment]
Thanks for the feedback. Just limited Tags fields to only show up to 5 suggestions, for the next release.

**Comment by brandonkelly** [comment]
Craft 4.4.15 is out with a fix for this.
