### ISSUE TITLE
[4.x]: Urls with encodings don't match custom routes

### ISSUE THREAD

**Issue by danbrellis** [craftcms/cms#13323]
### Description

I have a custom route to handle some legacy file redirects from an old system. The route take any url that starts with "documents" and then passes it to a controller that processes the path and redirects to the file. However, if I pass a url that contains an encoded value (eg `%20`) the route isn't captured and the controller isn't loaded.

### Steps to reproduce

1. Create a custom route in config/routes.php: `documents/<any:.*>' => 'my-module/routes/documents'`
2. Set up an `actionDocuments($any)` function in a RoutesController.php in your module and `var_dump($any)`.
3. Visit a URL with an encoded value, eg /documents/some%20file.pdf

I've confirmed this isn't an issue with setting up my routes, because if I visit /documents/some-file.pdf or even /documents/some+file.pdf it works perfectly.

### Expected behavior

The custom route should capture and load the controller.

### Actual behavior

I get a 403 Forbidden request.

### Craft CMS version

4.4.13

### PHP version

8.1.19

### Operating system and version

Linux 4.14.314-237.533.amzn2.x86_64

### Database type and version

MySQL 5.7.12

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.10-97)

**Comment by i-just** [comment]
Hi, thanks for reaching out. A routing order could cause this behaviour. Here’s some info on the routing order of events: https://craftcms.com/docs/4.x/routing.html 

Does the `documents` directory exist, and does it contain `some file.pdf` file? If that’s the case, then point 0 from the documentation could be applicable.

**Comment by i-just** [comment]
Right, thanks for confirming, @danbrellis! I’m unable to reproduce this behaviour. No matter what encoding I use, the requests go to the controller.

<img width="1121" alt="Screenshot 2023-06-15 at 15 41 18" src="https://github.com/craftcms/cms/assets/4500340/666a56f7-f5f9-4901-abf2-2d02970a5bb2">


Could you please start by verifying that the `/documents/some%20file.pdf` request starts going through Craft, and we’ll take it from there? Either set a breakpoint in `web/index.php` on the line that reads `$app->run()` or dump and die something just above it, visit `/documents/some%20file.pdf` and let me know what the outcome is?

**Comment by danbrellis** [comment]
Thanks @i-just for confirming you couldn't replicate the issue and for the troubleshooting advice. I did what you said and found that my request was not going to `web/index.php` so my next thought was `.htaccess` and I found from [this stack exchange](https://webmasters.stackexchange.com/a/141827) that adding the [`B` flag](https://httpd.apache.org/docs/2.4/rewrite/flags.html#flag_b) to the final rewrite rule solved it.

My working `.htaccess`, matches the one from the [Craft starter project](https://github.com/craftcms/craft) but with different flags in the last line (`[B,QSA,L]`):
```
# Send would-be 404 requests to Craft
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !^/(favicon\.ico|apple-touch-icon.*\.png)$ [NC]
RewriteRule (.+) index.php?p=$1 [B,QSA,L]
```

Apparently this is relevant to Apache version 2.4.56 (and up) which I am running. Maybe it's not applicable to nginx?

Thanks again for your help. Maybe a PR should happen to add the `B` flag into the starter project? Happy to do that if you think it's appropriate.

**Comment by i-just** [comment]
Thanks for sharing the insights! Glad you got to the bottom of it :) 

We’ll discuss this internally and decide whether/how to proceed.

**Comment by angrybrad** [comment]
@danbrellis did some basic tests, and I don’t think this applies to Nginx. Given that Craft doesn’t do any Apache version checks (and it seems a relatively niche use case), I don’t think adding it as a default to our stock .htaccess starter project is warranted.

Appreciate the debugging and will keep in this mind for future issues/tickets, though!
