### ISSUE TITLE
[3.x,4.x]: `relatedToCategories` errors when passed to `next`

### ISSUE THREAD

**Issue by Tam** [craftcms/cms#13334]
### Description
To ensure the filtering of a child page matches its index, we need to pass `relatedToCategories` to the `next` and `previous` fields of the entry in GraphQL. The introspection schema suggests that this is possible. But when we do we get this error:

```
Setting unknown property: craft\\elements\\db\\EntryQuery::relatedToCategories
```

Related stack question: https://craftcms.stackexchange.com/questions/38712/graphql-next-does-not-accept-relatedtocategories

### Steps to reproduce

Query the `next` field on an element, passing `relatedToCategories`:

```graphql
{
  entry (
    section: "company"
    slug: ["example"]
  ) {
    next (
      section: "company"
      relatedToCategories: [{
        group: "status"
        slug: ["active"]
      }]
    ) { url }
  }
}
```

### Expected behavior

It should correctly get the next element based off the filtering.

### Actual behavior

It throws an error.

### Craft CMS version

3.8.14, 4.4.14

### PHP version

8.1.20

### Operating system and version

Linux 5.15.49-linuxkit

### Database type and version

MySQL 8.0.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.1-10)

### Installed plugins and versions

Name | Version (Craft 3) | Version (Craft 4)
--- | --- | ---
DigitalOcean Spaces Volume | 1.1.3 | 2.0.0
Formie | 1.6.27 | 2.0.31
Logs | 3.0.5 | 4.0.0
Navigation  | 1.4.33 | 2.0.18
Redactor | 2.10.12 | 3.0.4
SEO | 3.7.5 | 4.1.2
Super Table | 2.7.5.1 | 3.0.9
Utility Belt | dev-main | 4.1.0

**Comment by Tam** [comment]
Updated to include same error in Craft 4

**Comment by i-just** [comment]
Hi, thanks for reporting. I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 3.8.15 and 4.4.15 are out with a fix for this. Thanks again for reporting!
