### ISSUE TITLE
[3.x]: All Craft CMS 3 versions are being marked as vulnerable once again by composer with roave/security-advisories

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/cms#13336]
### Description

https://github.com/Roave/SecurityAdvisories/commit/f928c4960ce91bfd266db27fa15679341cd3525d

A recent advisory has marked all Craft CMS 3 versions as insecure again.

### Craft CMS version

3.8.14

**Comment by angrybrad** [comment]
I’m confused by this one.

https://github.com/Roave/SecurityAdvisories/commit/f928c4960ce91bfd266db27fa15679341cd3525d

The last `< 4.2.1` appears to be the culprit, but that was there before the referenced commit, too.

It’s for a CVE for `react/http` (https://github.com/FriendsOfPHP/security-advisories/commit/df06cd2f78ffbde6b8b527e9638a9b2bcde66e42), but from what I can tell checking a fresh Craft 3 composer.lock file, that’s not even a sub-dependency of Craft (much less a direct one).

Originally advisory here: https://github.com/advisories/GHSA-95x4-j7vc-h8mf

Github/Dependabot hasn’t flagged this for Craft 3 installs, so it appears to be limited to Roave.

**Comment by jamesmacwhite** [comment]
Yeah to be honest, I've gave up with roave, obviously it's important to prevent being able to pull composer packages with vulnerabilities, but multiple CVEs keep marking all of Craft CMS 3.x releases as vulnerable regularly recently, it just blocks normal composer actions and becomes counter productive.

However at the moment, anyone including the roave dependency in their Craft CMS 3 project is now going to be blocked by this.

**Comment by angrybrad** [comment]
@jamesmacwhite yup - i created an issue for some guidance https://github.com/Roave/SecurityAdvisories/issues/117

**Comment by angrybrad** [comment]
@jamesmacwhite PR with the fix here: https://github.com/github/advisory-database/pull/2443

Going to go ahead and close this out, but it should be resolved once they merge in.

**Comment by jamesmacwhite** [comment]
Thank you for your continued PRs on these advisories. I am probably not going to include roave/security-advisories in our project anyway now. The CVE process has flaws which can cause negative impact which is somewhat ironic given the intended purpose of them and being used in sofware like roave. There are no safeguards for CVEs to be validated when potentially marking major versions of software and that is a problem in my eyes.
