### ISSUE TITLE
[4.x]: Image asset height is null, when transformed height is not an integer

### ISSUE THREAD

**Issue by realjoshharrison** [craftcms/cms#13335]
### Description

An image asset's `height` property is null when, after transforming with only a width specified, the resulting proportionately calculated height is not an integer. This only happens when `upscale` is false for the transform. And it happens with both named and template-defined transforms. Took a while to track this down... thank you for your time looking into it.

### Steps to reproduce

1. Upload the attached image into a clean Craft install. It is 1000 x 700px (70% ratio). 
![placeholder](https://github.com/craftcms/cms/assets/3930056/d8bfd824-7cd6-42b4-8c4c-2e3080180441)

2. Make a template with this, and view it:

```twig
  {% set asset = craft.assets.one() %}

  {% do asset.setTransform({
    mode: 'crop',
    width: 501,
    upscale: false,
  }) %}

  <img src="{{ asset.url }}"
       width="{{ asset.width }}"
       height="{{ asset.height }}">
```

### Expected behavior

Height should be `"351"`, rounded from 350.7px, as occurs when the `upscale` option is true.

### Actual behavior

Height is null.

### Craft CMS version

4.4.14

### PHP version

8.0.8

### Operating system and version

MAMP Pro, Darwin 22.5.0 (MacOS Ventura 13.4)

### Database type and version

MySQL 5.7.34

### Image driver and version

Imagick (ImageMagick 6.9.6-2)

### Installed plugins and versions

- None

**Comment by brandonkelly** [comment]
Craft 4.4.15 is out with a fix for this. Thanks again for reporting!
