### ISSUE TITLE
[4.x]: Craft sets the timezone too late for localised logs (I think!)

### ISSUE THREAD

**Issue by bossanova808** [craftcms/cms#13341]
### Description

Goal: I am trying to get my Craft log files to log in local time rather than UTC time.  This makes it drastically easier to follow logs.  I know not everyone will want this, of course - e.g. with auto log procesing things, might require UTC time.  But I suspect a lot of folks would find it helpful.

My own modules log in local time via a self-built logger write to file thing (which I may move to Monolog later)...which further increases the disparity as I have one set of logs in UTC, and others in local.  I suppose I could convert my own logger to use UTC time to at least have them consistent with each other, but it's just so much easier for me to look at e.g. the local time a Commerce order came in and check against times in the same timezones in the log for what might have caused a warning/error.

Craft already has a general setting for timezone (I use `CRAFT_TIMEZONE=Australia/Melbourne` - and Craft seems to respect this basically everywhere, but it seems like it's happening a bit late in the bootstrapping for the Monolog logger to get set up.

I'd have thought Yii (or PHP) would fall back to the system timezone (which is set correctly), but apparently not:

![image](https://github.com/craftcms/cms/assets/731309/d7ce7138-c878-45c9-89a8-87883f85b613)

In solving this, I worked out that setting the Yii timezone in app.php results in the change I want:

`'timeZone' => App::env('CRAFT_TIMEZONE'),`

...but I am nervous about possible side effects.  

Unfortunately, I was not able to work out a method of doing the equivalent on just the Monolog component via config - which would have been my preferred option.

So - I am running with the app.php change, and seems ok so far, but would like to get the Craft official view on this.

### Craft CMS version

4.4.14

### PHP version

8.2

### Operating system and version

Ubuntu 22.04 (Forge)

### Database type and version

MySQL 8

### Image driver and version

not relevant

### Installed plugins and versions

not relevant

**Comment by timkelty** [comment]
@bossanova808 setting `timeZone` in `app.php` should be a perfectly acceptable solution.

Setting `timeZone` in `app.php`, `date.timezone` in your `php.ini`, and `timeZone` `config.php` in [Craft's `config.php`](https://github.com/craftcms/cms/blob/4.4/src/config/GeneralConfig.php#L2785) all have the same effect: they set [PHP's internal default timezone](https://www.php.net/manual/en/function.date-default-timezone-set.php).

That said, we do want to expose the Monolog `Logger` object via config, so if you preferred, you would be able to call `Logger::setTimezone` in `app.php`. That is on my list for 4.5 – I'll post an update here when I know more!

**Comment by timkelty** [comment]
@bossanova808 @i-just I'm going to close this, as configuring timezone as described is advisable.

Allowing for full configuration of the Monolog logger from `app.php` will happen with other improvements in Craft 5.

**Comment by brandonkelly** [comment]
As of the next Craft 4 release, it will be possible to configure `MonologTarget` via Yii’s dependency injection container. So for example, you could put this at the top of `config/app.php`:

```php
use craft\log\MonologTarget;
use yii\di\Container;

Craft::$container->set(MonologTarget::class, function(Container $container, array $params, array $config) {
    $target = new MonologTarget($config);
    $target->getLogger()->setTimezone(new DateTimeZone('Australia/Melbourne'));
    return $target;
});
```

We’ll discuss whether it makes sense to start setting the logger to the system time zone by default for Craft 5, as well.

**Comment by brandonkelly** [comment]
We realized today that this is actually a regression in Craft 4; previously logs were in fact output using the system time zone. So we’ve adjusted them to do that by default again starting in Craft 4.7.

**Comment by brandonkelly** [comment]
Craft 4.6.1 is out with support for changing this via the DI container.

**Comment by brandonkelly** [comment]
Craft 4.7.0 is now tagged, with logs defaulting to the system time zone once again 🎉
