### ISSUE TITLE
[4.x]: URI autofilled when creating new SINGLE section

### ISSUE THREAD

**Issue by remcoov** [craftcms/cms#13350]
### Steps to reproduce

1. Create a new section
2. Fill with a name (and thus handle)
3. Change section to a SINGLE
4. The URI is empty (you can even do an extra backspace or delete to be sure) - which is what I want
5. When saving the SINGLE the URI gets filled anyway

### Craft CMS version

4.4.14

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch. I have raised a PR for this. 

For now, if you edit the single section again, you will be able to remove the URI.

**Comment by brandonkelly** [comment]
Craft 4.4.15 is out with a fix for this. Thanks for reporting!
