### ISSUE TITLE
[4.4.14]: Calling unknown method: craft\console\Request::validateCsrfToken()

### ISSUE THREAD

**Issue by DTesch-Reem** [craftcms/cms#13358]
### Description
Can't call my Controller Actions because of this error:
Calling unknown method: craft\console\Request::validateCsrfToken()
Calling the action through http seems to work just fine.
The Action is called with Craft::$app->runAction().

Disabling CSRF-Protection leads to this Error:
Calling unknown method: craft\console\Request::hasValidSiteToken()

### Steps to reproduce

1.Call an Action inside a Module or through the Console

### Expected behavior
Run Action

### Actual behavior
Calling unknown method: craft\console\Request::validateCsrfToken()

### Craft CMS version

4.4.14

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out. Could you please provide more info on how to reproduce this issue?

**Comment by i-just** [comment]
So you have the `isolate-permissions` module with the `IsolatePermissions` console controller and the `actionSetSitePermissions()` method in that console controller, which calls a web controller using `Craft::$app->runAction()` - is that correct?

If that’s the case, then the error you’re getting doesn’t sound like a bug to me. You’re running a console command, meaning the Request is a console request. From that command, you’re triggering a web controller action, and those are subject to CSRF checks, but the request that initiates this chain of events is a console request. Based on my understanding of the information you provided, it sounds like maybe the logic you’re trying to execute from a web controller could be moved to, e.g. a service method. That way, you wouldn’t have to call the web controller from the console controller.

Please let me know if I misunderstood any of the info you provided.

**Comment by DTesch-Reem** [comment]
Actually I don't have a console controller, I'm just using one controller class for handling everything.
Is it true, that a controller not living in "module/console/controller" automatically is treated as a HTTP-Controller?

I'm kind of new to the whole Yii and Craft-Plugindevelopment.
The service method is a great idea, thanks!

**Comment by i-just** [comment]
> Is it true, that a controller not living in "module/console/controller" automatically is treated as a HTTP-Controller?

The convention is to have the web controllers in `module/controllers` and console controllers in `module/console/controllers`, but that’s a convention, and it can be changed.

> Actually I don't have a console controller, I'm just using one controller class for handling everything.

Ok, what class is this controller class extending? `craft\console\Controller`, `craft\web\Controller` or something else?

You can find more info on writing Craft modules here: https://craftcms.com/docs/4.x/extend/module-guide.html.

The generator makes it easier to get the scaffolding for what you’re after: https://github.com/craftcms/generator.

And here are also some Knowledge Base articles on extending Craft: https://craftcms.com/knowledge-base/extending-craft.

**Comment by DTesch-Reem** [comment]
My bad, the controller class is extending "craft\web\Controller".
Now I can see why it isn't working.

Thanks!

**Comment by i-just** [comment]
Not a problem. Glad you got to the bottom of it!
