### ISSUE TITLE
[4.x]: Unlimited dragging in field layout

### ISSUE THREAD

**Issue by remcoov** [craftcms/cms#13351]
### Steps to reproduce

1. Go to a field layout of a section
2. Grab one of the fields (doesn't matter which one)
3. Keep grabbing it and move mouse to the right of the screen
4. You'll have unlimited scrolling to the right
5. I thought It might've been a secret Super Mario Bros. level, but it wasn't.

### Craft CMS version

4.4.14

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 4.4.15 is out with a fix for this. Thanks for reporting!
