### ISSUE TITLE
[4.x]: Selectize doesn't respect default values on old entries

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#13363]
### Description

Since Craft moved to use Selectize for dropdown fields instead of native select elements, we're running into issues with default values. Previously, if you had an entry saved, and you added a new Dropdown field with multiple options, and you marked one of them as "Default", then the next time you saved that entry, it would just use that default value.

Since 4.4, we have created new Dropdown fields and made sure that they have an option marked as "Default", but if you try to edit an entry that already exists (before the new field was created), you get an error that Craft is unable to save because the new field has an invalid value.

![image](https://github.com/craftcms/cms/assets/1250017/700c2570-529d-4ab1-9534-8f3eac6a4ffe)

Comment from one of our content editors:

![image](https://github.com/craftcms/cms/assets/1250017/44672764-84c6-4edc-a86b-ffce7abb43da)

### Steps to reproduce

1. Save an entry
2. Add a new Dropdown field with a default value
3. Try to save the old entry. Craft fails to save

### Expected behavior
Old entries should use the "default" value of the new field when you save them

### Actual behavior
Craft throws an error that it can't save the entry because a value is invalid, even though the user hasn't changed that field.

### Craft CMS version

4.4.14

### PHP version

8.2

### Database type and version

MySQL 8

**Comment by i-just** [comment]
Hi, thanks for getting in touch. This was raised before, most recently here: https://github.com/craftcms/cms/issues/13146, and we have plans to adjust this behaviour. You might also find the information under this similar issue helpful: https://github.com/craftcms/cms/issues/13133.

For now, you might want to use the command to update the existing entries with the default value for the new dropdown: 
`php craft resave/entries --section mySection --set myDropdown --to "=opt2"`
You can also add `--if-empty` to that command if you only want to set the value only if there’s nothing there already.

I hope this helps! 

I’ll close this now, but you can follow along under #13146.
