### ISSUE TITLE
Revert entry to version lost asset field

### ISSUE THREAD

**Issue by lboaretto** [craftcms/cms#1336]
### Description

When I revert to a previous version, Asset is lost.

### Steps to reproduce

1. Create a new Entry with Asset and Title
2. Change Title (v2), change again (v3)
3. Revert to v2: Asset lost.

### Additional info

- Craft version: 3.0.0-beta.2
- PHP version: 7.0.13
- Database driver & version: MySQL 5.6.34
- Plugins & versions: None

**Comment by brandonkelly** [comment]
@lboaretto I'm not able to reproduce this. If you're able to reliably reproduce this, can you please send a DB backup to support@craftcms.com and reference this issue? Thanks!

**Comment by lboaretto** [comment]
Sent. Thank you!

**Comment by brandonkelly** [comment]
This has been fixed for the next release.

**Comment by lboaretto** [comment]
Thanks!
