### ISSUE TITLE
[4.x]: \craft\log\ContextProcessor not filtering variables correctly

### ISSUE THREAD

**Issue by myleshyson** [craftcms/cms#13360]
### Description
Looking at the comments for `yii\log\Target`, and you should be able to specify not only root level global keys to log but nested keys as well.

```php
    // yii\log\Target line 17

    /**
     * @var array list of the PHP predefined variables that should be logged in a message.
     * Note that a variable must be accessible via `$GLOBALS`. Otherwise it won't be logged.
     *
     * Defaults to `['_GET', '_POST', '_FILES', '_COOKIE', '_SESSION', '_SERVER']`.
     *
     * Since version 2.0.9 additional syntax can be used:
     * Each element could be specified as one of the following:
     *
     * - `var` - `var` will be logged.
     * - `var.key` - only `var[key]` key will be logged.
     * - `!var.key` - `var[key]` key will be excluded.
     *
     * Note that if you need $_SESSION to logged regardless if session was used you have to open it right at
     * the start of your request.
     *
     * @see \yii\helpers\ArrayHelper::filter()
     */
    public $logVars = [
        '_GET',
        '_POST',
        '_FILES',
        '_COOKIE',
        '_SESSION',
        '_SERVER',
    ];
```

However `craft\log\ContextProcessor::filterVars` is only filtering by root level keys using `in_array`, making nested key filtering impossible.

Line 96 in `ContextProcessor` can be updated to
 ```php
$filtered = Collection::make(ArrayHelper::filter($GLOBALS, $vars));
``` 
to allow proper variable filtering. I'm a little rusty on Laravel collections so I couldn't find a clean way to get the same functionality as `ArrayHelper::filter`. 

This is important for us in our production environment. We want to filter to a few server variables so that our log files are a lot easier to parse. The option right now is either all context or no context in logs. 

### Steps to reproduce

1. In app.php, add something like 
```php
'log' => function () {
            return Craft::createObject([
                'class' => Dispatcher::class,
                'monologTargetConfig' => [
                  'logVars' =>  ['_SERVER.REQUEST_URI']
                ],
            ]);
        },
```
2. Visit a page on the site with logging enabled.
### Expected behavior
Expect only to see `_SERVER.REQUEST_URI` information in the log context.

### Actual behavior
Nothing appears at all for context.

### Craft CMS version

4.4.14

### PHP version

8.2

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting and doing all the hard work! I just tested your suggestion and raised a PR with it.
