### ISSUE TITLE
Support for multiple log targets

### ISSUE THREAD

**Issue by ostark** [craftcms/cms#1337]
Yii 2 supports multiple built-in [log targets](http://www.yiiframework.com/doc-2.0/guide-runtime-logging.html#log-targets) like `file`, `db`, `email` and `syslog`. It would be nice to get more control of these targets via configuration. With a config option `logTargets = []` in `config/general.php`, that overwrites Craft's default logging behaviour, we could leverage Yii's flexibility.

Moreover, other log targets like [streamlog](http://www.yiiframework.com/extension/yii2-streamlog/) or  [sentry](https://github.com/notamedia/yii2-sentry) could be configured that way.

Are you interested in a PR?

--

The issue ID must be a sign 😁

**Comment by brandonkelly** [comment]
Already possible via `config/app.php` - just overwrite the `log` component (default config defined in `vendor/craftcms/cms/src/config/components/common.php`).

```php
<?php

return [
  'components' => [
    'log' => [
      'targets' => [
        [
          'class' => 'yii\log\DbTarget',
          'levels' => ['error', 'warning'],
        ],
        ],
      ],
    ],
  ],
];
```

**Comment by ostark** [comment]
Thanks!
