### ISSUE TITLE
[4.x]: StringHelper returns null when field contains paragraph tags with attributes

### ISSUE THREAD

**Issue by carolinecblaker** [craftcms/cms#13372]
### Description

String Helper stripHtml is returning null on non-null content that contains `<p dir="ltr">`

### Steps to reproduce

1. Add Rich Text content to a field (`$entry->body`) that has  `<p dir="ltr">`
2. Call it to the Element API, use `$body= StringHelper::stripHtml( substr($entry->body, 0,350)).'...';` 
3. Enjoy your 500 error.

### Expected behavior

Expecting to get content of $entry->body with no HTML

### Actual behavior

`[craft\elementapi\controllers\DefaultController::actionIndex] Error resolving Element API endpoint: craft\helpers\StringHelper::stripHtml(): Return value must be of type string, null returned {"memory":6989416} `

### Craft CMS version

4.3.4

### PHP version

8.1

### Operating system and version

NGINX / Serverpilot

### Database type and version

MySQL 8 

### Installed plugins and versions

-
Element API

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Tested on PHP 8.0 and 8.1:

```
> craft\helpers\StringHelper::stripHtml(substr('<p dir="ltr">', 0, 350))
= ""
```

The only time `preg_replace()` (what `stripHtml()` calls internally) would return `null` is if an error occurred.

What is the full value of `$entry->body`?

**Comment by carolinecblaker** [comment]
> `<p dir="ltr">Grace Chen (she/her/hers) is an Intern Therapist at The Center for Growth from June 2023 to June 2024. Grace is working towards a Master’s in Mental Health Counseling from the University of Pennsylvania’s Graduate School of Education. Previously Grace has worked in the financial services industry for about four years with a master’s degree in Accounting from George Washington University and a bachelor’s degree in Economics from Lafayette College. Prior to her work with the Center for Growth, Grace completed her first-year internship in family therapy, working with children, adolescents, and families by providing CBT and behavioral therapy services. Grace works with clients in a variety of areas, including trauma, life transitions, eating disorders, self-esteem and self-love, depression, anxiety, relationship issues, grief & loss, and so on.</p>`

The string quoted in the error is:`craft\\helpers\\StringHelper::stripHtml('<p dir=\"ltr\">Gr...')"`
I don't know how it decides what to show here, but it pretty clearly hates the first few characters.

This makes me wonder if it's these slashes? Could that just be error output? I never replicated seeing the slashes in the rich text in the body field. I also know it's not a case of "just save it again" because I moved the text around, saving it a couple of times, and only removing these attribute-value pairs solved it. Then again, I left one in by accident and it didn't trigger the error.

I strongly wonder if this text was copy-pasted and there was some other offending invisible character. The world may never know.

**Comment by brandonkelly** [comment]
The issue is that `substr()` will return a _byte sequence_ from the passed-in string; it’s not specifically concerned with which acutal characters. Which can be problematic for strings with multi-byte characters such as yours.

In this case, 350 bytes into the string is right in the middle of the `’` character within `master’s degree`. So it’s returning a binary string, as it’s no longer valid unicode.

If you really just want the first 350 _characters_, use [mb_substr](https://www.php.net/manual/en/function.mb-substr.php) instead:

```php
$body = StringHelper::stripHtml(substr($entry->body, 0, 350)) . '...';
```

**Comment by brandonkelly** [comment]
> I don't know how it decides what to show here, but it pretty clearly hates the first few characters.

It’s just truncating the input there.
