### ISSUE TITLE
Site name in CP header

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#1338]
### Description

I named my sites "English" and "German", to make the sites switch on edit element pages looks like the old locales switch in Craft 2.

<img width="351" alt="bildschirmfoto 2017-02-03 um 11 03 56" src="https://cloud.githubusercontent.com/assets/7516543/22587132/a8cca436-ea00-11e6-89f6-804f1df6dad4.png">

Unfortunately, this also makes the top-most site name to be used in the CP header, where "English" doesn’t make a whole lot of sense.

<img width="244" alt="bildschirmfoto 2017-02-03 um 11 05 52" src="https://cloud.githubusercontent.com/assets/7516543/22587173/db80fad0-ea00-11e6-9682-e32d90d564a8.png">

### Additional info

- Craft version: 3.0.0-beta.1
- PHP version: 7.0.15
- Database driver & version: MySQL 5.5.5
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just added the concept of a “System Name” that resolves this.
