### ISSUE TITLE
[4.x]: Eager-loaded categories from Categories field are returned in wrong order

### ISSUE THREAD

**Issue by thomas-dm** [craftcms/cms#13394]
### Description

Hi 👋

I’ve just stumbled upon a bit of an odd behavior:

When eager-loading categories from a `Categories` field assigned to an entry, they seem to be returned in their CP order instead of their order of selection in said field. When I don’t use eager-loading and query the field directly (`->all()`), however, the categories are returned in their selection order as expected.

This might very well be intended behavior (?), but in that case, how could I preserve their selection order while still using eager-loading? I know how to sort by specific keys when using eager-loading, but not how to keep a selection order.

Thank you!

### Craft CMS version

4.4.15

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! That’s a bug, and I raised a PR to adjust it.

**Comment by brandonkelly** [comment]
Craft 4.4.16 is out with the fix for this. Thanks again!
