### ISSUE TITLE
500 error for images preview in CP on Windows - GD

### ISSUE THREAD

**Issue by fcaron** [craftcms/cms#1340]
### Description
After uploading images in Craft CP, I see them in my folder web/images, but the thumbnails in the CP are not working and when I edit the image, I don't see it either. When I check the url Craft try to load, it says that there is a 500 Internal Server Error:
http://craftcms3.dev.localtest.me/admin/resources/resized/8/30?d=1486129361
The image “http://craftcms3.dev.localtest.me/admin/resources/resized/8/30?d=1486129361” cannot be displayed because it contains errors.

I'm on PHP 7 on IIS Windows 10 with the image driver GD.

### Additional info

- Craft version: 3.0 beta 2
- PHP version: 7.14
- Database driver & version: MySQL
- Plugins & versions: No plugins

Thank you for your great CMS :)

**Comment by andris-sevcenko** [comment]
Can you shoot an email to support@craftcms.com and include the contents of your craft/storage/logs folder?

**Comment by fcaron** [comment]
I see that it works when I remove "set_time_limit" in "disable_functions" from php.ini.
But it would probably be a good idea to catch the error or alert the user in the CP to enable set_time_limit.

Thanks

**Comment by andris-sevcenko** [comment]
Alerting the user in the CP would be of little use if the user was a content editor with no idea what "php.ini" is at all. This is a great middle ground, as you get the error logged in the log files and you also get a nice red HTTP 500 error in your browser console to alert you that something definitely is wrong.
