### ISSUE TITLE
[4.x]: Lightswitch can overflow on 1/4 field width

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#13419]
### Description

On smaller desktop viewports, the lightswitch can overflow if the field is set to 1/4 width. Also, the background area of the lightswitch track can become smaller, which makes it harder to identify as a lightswitch:

![Screenshot 2023-07-12 at 17 24 39](https://github.com/craftcms/cms/assets/10146880/61219800-cb1a-425a-a97b-397705a76eb6)

Maybe if the space becomes too narrow, the labels should move above / below the light switch? Or maybe the labels should be truncated with an ellipsis or forced to break into a new line with `overflow-wrap: break-word`.

### Craft CMS version

4.4.15

**Comment by i-just** [comment]
Hi, thanks for reporting! I’ve put together a potential solution for this. I want to run it past a few more people before requesting approval.

**Comment by brandonkelly** [comment]
Craft 4.4.16 is out with the fix for this. Thanks again!
