### ISSUE TITLE
[4.x]: Search seems to be broken

### ISSUE THREAD

**Issue by jan-dh** [craftcms/cms#13426]
### Description
When I'm trying to find a specific blog entry from the search and I enter the exact title, I get 0 results. However, if I use the filter element and I'm looking for a specific value of the `old_id` field, I do find the entry. The entry was seeded from another Craft site and the old id value is unique.

### Expected behavior

The title would provide me a result

### Actual behavior

I get 0 results

### Craft CMS version

4.4.15

### PHP version

8.1.17

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out. Can you please run the following command: `php craft resave/entries --update-search-index=1`, and once it’s finished, search again and let me know if it now finds the result as expected?

**Comment by jan-dh** [comment]
Yep, have run that from the CLI, can see the tasks running, but the results is still the same.

**Comment by i-just** [comment]
> can see the tasks running, but the results is still the same

Do you mean the results are the same after the command has finished with all the entries?

**Comment by jan-dh** [comment]
I perform the same actions as initially and I still have the same results as initially.

**Comment by i-just** [comment]
Thanks for confirming! 
Since I'm not able to replicate this behaviour after updating search indexes, could you please send your `composer.json`, `composer.lock` and database export to support@craftcms.com so that we can dig deeper? Also, please provide the `title` and `old_id` you’re using to test.

**Comment by jan-dh** [comment]
Hmm, another rerun worked. My bad

**Comment by i-just** [comment]
Glad to hear it’s working 🙂  Thanks for the update!
