### ISSUE TITLE
[4.x]: Matrix-field $value can be instance of Collection -> method craft\\elements\\ElementCollection::setCachedResult does not exist

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#13421]
### Description

`$value` in your relation / Matrix fields can always be instance of `Collection` instead of `ElementQueryInterface`
https://github.com/craftcms/cms/blob/develop/src/fields/Matrix.php#L822-L825
```PHP
if (!$allBlocksValidate) {
    // Just in case the blocks weren't already cached
    $value->setCachedResult($blocks);
}
```

->
```PHP
if (!$allBlocksValidate && $value instanceof ElementQueryInterface) {
    // Just in case the blocks weren't already cached
    $value->setCachedResult($blocks);
}
```

### Steps to reproduce

1. use eager loading
2. save the matrix block

### Craft CMS version

4.4.5

### PHP version

8.2.0

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 4.4.16 is out with a fix for this.
