### ISSUE TITLE
Css bug for buttons / loading in CP on Firefox Windows

### ISSUE THREAD

**Issue by fcaron** [craftcms/cms#1342]
### Description
On a page like "/admin/utilities/clear-caches", the div.utility-status is on top of the submit button in last version of Firefox. So you can't click on the button except on the far left. Here is a screenshot:

![craftcms3-cp-bug-css](https://cloud.githubusercontent.com/assets/1786126/22596609/37096326-e9fa-11e6-8bc2-ede61fba818a.JPG)

On Chrome, it works fine though. The problem seems to come from the "float: left;" on the button, because it works fine when I remove it.

### Additional info

- Craft version: 3 beta 2
- PHP version: 7
- Database driver & version:
- Plugins & versions:

Thanks!

**Comment by benjamindavid** [comment]
Thanks @fcaron !
