### ISSUE TITLE
Mail settings as config

### ISSUE THREAD

**Issue by stevieg83** [craftcms/cms#1344]
Not all environments use the same config setting for email.

Would be great to have the ability to set these as environment variables.

**Comment by brandonkelly** [comment]
Assuming this is for v3. To be clear the [environmentVariables](https://craftcms.com/docs/config-settings#environmentVariables) config setting is no longer a thing, but I just managed to make `config/app.php` application config file capable of being a [multi-environment config](https://craftcms.com/docs/multi-environment-configs).
