### ISSUE TITLE
[4.x]: Issue with any slideout modals saving, no way to debug

### ISSUE THREAD

**Issue by mediabeastnz** [craftcms/cms#13455]
### Description
When using the slide-out modals (popout) to quickly edit content, upon saving any piece of content an error is returned and the content isn't saved.

No errors appear in any of our logs or the console, which makes this very tricky to debug.
This also only happens in production and not on UAT or a local copy.

Are there ways to debugging these requests?

### Steps to reproduce

1. Double click entry/content to op slide out modal
2. click save
3. see error

### Expected behavior
Content is saved.

### Actual behavior
Content is not saved

### Craft CMS version

4.4.15

### PHP version

8.1.11

### Operating system and version

Linux 5.4.0-51-generic

### Database type and version

MySQL 5.7.32

### Image driver and version

Imagick (ImageMagick 6.9.10-23)

### Installed plugins and versions

Embedded Assets	3.1.3
Feed Me	5.1.1.1
Freeform	4.0.21
Navigation	2.0.17
Neo	3.8.2
Redactor	3.0.4
SEOmatic	4.0.23
Typed link field	2.1.5

**Comment by i-just** [comment]
Hi, thanks for getting in touch. 
When you save the same elements but not in a slide-out, do they save correctly?
When you say error is returned, what error is it exactly? Is it “Couldn’t save entry.” or something else? 
Did you look in the developer tools network tab? Maybe there’s something in the request or response when you save a slide-out that could provide more info?

**Comment by mediabeastnz** [comment]
Elements save fine when not using the slide-out.

Example of error
![Screenshot 2023-07-25 at 4 52 51 PM](https://github.com/craftcms/cms/assets/909749/bdbefd8c-6542-4633-b868-a674eb2b280e)

Nothing is reported in developer tools at all.

**Comment by i-just** [comment]
Great, thanks for confirming!

So there are no XHR calls with status 400 or 500 in the dev tools network tab?

I purposefully triggered a 500 error when trying to save content in a slide-out and got the following response:
<img width="2288" alt="Screenshot 2023-07-25 at 11 52 01" src="https://github.com/craftcms/cms/assets/4500340/c4e08088-df0e-4f37-924e-17aa39e45399">

I opened the element from which I wanted to trigger the slide-out to open  > dev tools > Network tab > make sure XHR is selected (I cleared the list before triggering the slideout as it’s easier to see what’s going on) > double-click on the element to open the slide-out > make a change > let it autosave > press save => there’s a generic-looking post request, 3rd from the top in my screenshot; 

What does it show you when you do the same?

**Comment by mediabeastnz** [comment]
I see this
<img width="1402" alt="Screenshot 2023-07-26 at 9 29 10 AM" src="https://github.com/craftcms/cms/assets/909749/4746db60-f70a-4365-a446-339b83c45b79">

**Comment by i-just** [comment]
That helps - thanks!

So from the start, we knew that this is something configuration or environment related as it’s only happening in one of your 3 environments.

It looks like something is triggering a redirect or that particular request is not being recognised as accepting JSON response (in which case it would be Craft triggering the redirect instead of a json response https://github.com/craftcms/cms/blob/develop/src/web/Controller.php#L277-L303). 

I’d review the configuration that is unique for the production site, including any Nginx or Apache config.

**Comment by mediabeastnz** [comment]
Strange as this is the same setup as all our other builds. Maybe I'll contact our hosting provider to see if there maybe something misconfigured.

Any other tips of what might cause this would be much appreciated.

Do you think this error maybe related? (Web.log).
I can see some graphQL in there so I'm thinking it's not related though.

```
[26-Jul-2023 20:22:14 Pacific/Auckland] An Error occurred while handling another error:
yii\web\BadRequestHttpException: Invalid JSON data in request body: Control character error, possibly incorrectly encoded in /container/application/apps/backend/vendor/yiisoft/yii2/web/JsonParser.php:60
Stack trace:
#0 /container/application/apps/backend/vendor/yiisoft/yii2/web/Request.php(591): yii\web\JsonParser->parse('{"query":"\\n   ...', 'application/jso...')
#1 /container/application/apps/backend/vendor/craftcms/cms/src/web/Request.php(832): yii\web\Request->getBodyParams()
#2 /container/application/apps/backend/vendor/craftcms/cms/src/web/Request.php(877): craft\web\Request->getBodyParams()
#3 /container/application/apps/backend/vendor/craftcms/cms/src/web/Request.php(1056): craft\web\Request->getBodyParam('dontExtendSessi...')
#4 /container/application/apps/backend/vendor/craftcms/cms/src/web/User.php(479): craft\web\Request->getParam('dontExtendSessi...')
#5 /container/application/apps/backend/vendor/yiisoft/yii2/web/User.php(199): craft\web\User->renewAuthStatus()
#6 /container/application/apps/backend/vendor/craftcms/cms/src/web/ErrorHandler.php(268): yii\web\User->getIdentity()
#7 /container/application/apps/backend/vendor/craftcms/cms/src/web/ErrorHandler.php(187): craft\web\ErrorHandler->_showExceptionView()
#8 /container/application/apps/backend/vendor/yiisoft/yii2/base/ErrorHandler.php(152): craft\web\ErrorHandler->renderException(Object(yii\web\BadRequestHttpException))
#9 /container/application/apps/backend/vendor/craftcms/cms/src/web/ErrorHandler.php(66): yii\base\ErrorHandler->handleException(Object(yii\web\BadRequestHttpException))
#10 [internal function]: craft\web\ErrorHandler->handleException(Object(yii\web\BadRequestHttpException))
```

**Comment by brandonkelly** [comment]
@mediabeastnz That definitely seem suspicious. Is there any chance you could send your Composer files and a database backup to support@craftcms.com so we can test on our end?

**Comment by mediabeastnz** [comment]
We replaced our docker container on production and resolved the issue. A strange one indeed.
Thanks for the assist anyways!

**Comment by brandonkelly** [comment]
Glad you got it sorted!

**Comment by aaronbushnell** [comment]
I actually have this exact issue and it's due to an NGINX config setting where I'm attempting to force trailing slashes:
```nginx
# Force trailing slashes
rewrite ^([^.]*[^/])$ $1/ permanent;
```

Is there a way for Craft to cooperate with this type of enforcement when using a slide-out for editing? Editing entries directly works without issue.

**Comment by aaronbushnell** [comment]
FWIW it seems like changing my config to the following allows this to work, but still hoping Craft has a way to route the simpler approach if possible!

```nginx
#- Send would-be 404 requests to the cache path or Craft
location / {
    # Force trailing slashes on URLs
    if ($request_uri ~ ^([^.\?]*[^/])$) {
        return 301 $1/;
    }

    try_files $uri $uri/ /index.php?$query_string;
}
```

**Comment by brandonkelly** [comment]
@aaronbushnell Are you seeing anything in your Craft logs for the save requests? If not, the request isn’t making it to Craft in the first place, so nothing Craft could do.

**Comment by aaronbushnell** [comment]
@brandonkelly — Yeah, that's a good point. I did enable devMode and fired the request in a fresh set of logs. Here's what Craft output (with noise removed):
```log
2023-09-12 13:16:12 [web.INFO] [yii\db\Connection::open] Opening DB connection: mysql:host=127.0.0.1;dbname=REDACTED;port=3306 {"memory":781624} 
2023-09-12 13:16:12 [web.INFO] [yii\web\Session::open] Session started {"memory":7512752} 
2023-09-12 13:16:12 [web.INFO] [nystudio107\codeeditor\CodeEditor::bootstrap] CodeEditor module bootstrapped {"memory":7553304} 
2023-09-12 13:16:12 [web.INFO] [nystudio107\retour\Retour::init] Retour plugin loaded {"memory":7966336} 
2023-09-12 13:16:12 [web.INFO] [nystudio107\seomatic\Seomatic::init] SEOmatic plugin loaded {"memory":8296528} 
2023-09-12 13:16:12 [web.INFO] [application] Request context:
$_GET = [
    'v' => '1694524572594'
]

$_POST = []

$_FILES = []
```

Seems like a redirect is occurring and it's converting the POST request for the saved entry in the slide-out to a GET request? Is that what's going on here?

**Comment by brandonkelly** [comment]
I think those logs are just messages that those plugins are logging on every request when initialized.

Are you able to step through the request with Xdebug?
