### ISSUE TITLE
[4.4.16]: Lightswitch fields do not stretch to the width of their on/off value

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/cms#13452]
### Description

Not sure if this is a Commerce issue or not, but since updating to Craft CMS 4.4.16, lightswtich fields that are attached to "Order Fields" no longer stretch to the width of their content. It was fine before this update.

<img width="290" alt="Screenshot 2023-07-18 at 21 37 48" src="https://github.com/craftcms/cms/assets/2373940/93d6d055-780b-40a0-a62f-f54f12212b50">

### Steps to reproduce

1. Create a lightswtich field and set the "On" value to "Yes"
2. Add lightswtich field to "Commerce > System Settings > Order Fields"
3. Allow the field to span across 4 columns
4. View order, and notice that the "On" value does not have enough width for it to display correctly (see screenshot above)

### Craft CMS version

v4.4.16

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting and sorry about that! I just raised a PR to fix this.

**Comment by brandonkelly** [comment]
Craft 4.4.16.1 is out with the fix for this. Thanks again for reporting!
