### ISSUE TITLE
[4.x]: Vuetable - using data mode, until data loads "No data available" is shown instead of some kind of preloader

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#13459]
### Description
By vue table, i mean component that is used to create lists in the "settings" section, like for example section list. As far as i know data mode (enabled by `tableDataEndpoint` option) is not used anywhere in craft right now, but im using it for my plugin.

"No data available" is the same message that shows if there is no data at all reurned by controller, so it is misleading.

### Craft CMS version

4.4.16.1

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @piotrpog 

Thank you for bringing this to our attention.

There is now a PR in progress to address the point you raised.

Thanks!

**Comment by brandonkelly** [comment]
Craft 4.4.17 is out with the fix for this. Thanks again!
