### ISSUE TITLE
[3.x]: "Out of range" MySQL error on structure elements

### ISSUE THREAD

**Issue by martinhellwagner** [craftcms/cms#13474]
### Description

We're getting an "Out of range" MySQL error when trying to reorder structure elements. This might be due to the fact that we have _a lot_ of structures and structure elements in our Craft already. The error occurs when running the following MySQL query:

```
UPDATE `structureelements` SET `lft`=`lft`-172, `dateUpdated`='2023-07-24 12:31:44' WHERE (`lft` >= 35) AND (`root`=304)
```

The error (which is reported into `storage/logs/web.log` as well on my SQL client when running the query directly) looks like this:

```
BIGINT UNSIGNED value is out of range in '(`bistum`.`structureelements`.`lft` - 172)'
```

### Steps to reproduce

1. Try to reorder structure items

### Expected behavior

Structure items are reordered correctly

### Actual behavior

Structure items are not reordered correctly, "Server error" occurs

### Craft CMS version

3.7.59

### PHP version

7.4

### Database type and version

MySQL 8.0.33

**Comment by i-just** [comment]
Hi, thanks for getting in touch! It sounds like the structure data could have gotten misaligned at some point. 

I’d take a backup and then run the following command: `php craft utils/repair/section-structure <structureHandle>` and once it’s finished, check if you can re-order the element that was triggering this error. You can also run this command with a `--dry-run` option first to see what would change without actually applying those changes.

**Comment by martinhellwagner** [comment]
@i-just

Just tried that, and it worked flawlessly. Thanks a lot! 🚀
