### ISSUE TITLE
[4.x]: Export of content does not include disabled matrix blocks

### ISSUE THREAD

**Issue by sg-modlab** [craftcms/cms#13496]
### Description

Using the out of the box "Expanded" exporter to json seems to not include matrix blocks that are disabled. 

### Steps to reproduce

1.

### Expected behavior

We can export entries that are disabled so I would expect that disabled matrix blocks could be included as well, this or make it an option. Seems destructive to omit this content.

### Actual behavior

See above

### Craft CMS version

4.4.15

### PHP version

8.1

### Operating system and version

Mac

### Database type and version

MySQL 8.0

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Craft 4.5.10 is out, which now includes any disabled nested/related elements when using the “Expanded” export type. (Note that this is not recursive, though. If a Matrix block contains a Super Table field with disabled rows, those rows wouldn’t be included, for example.)
