### ISSUE TITLE
[4.x]: `null | purify` throws a `500 server error` 

### ISSUE THREAD

**Issue by maxfenton** [craftcms/cms#13495]
### Description

Most of the time, I'm careful enough to check content before piping it to `| purify` like

```
{{ body ? tag('div', {
    class: 'rich-text text-size-body',
    html: body | purify('BodyCopy'),
}) }}
```

... but the following will cause a `500 Error` on a site where `devMode` is false

```
{% set exampletext = somethingThatDoesNotExistOrIsEmpty ??? null %}
{{ exampletext | purify('BodyCopy') }}
```

and throw this error if `devMode` is true:

```
TypeError
craft\web\twig\Extension::purifyFilter(): Argument #1 ($html) must be of type string, null given, called in /var/www/site/production/shared/storage/runtime/compiled_templates/40/****.php on line 73
```

### Steps to reproduce

1. Run any null variable through the `| purify` filter

### Expected behavior

I would expect a little more forgiveness from the `| purify` filter to return `null` if it receives `null` rather than TypeError what amounts to an empty `$html` parameter.

### Actual behavior

TypeError above or 500 Error

### Craft CMS version

4.4.16.1

### PHP version

8.2.6

### Operating system and version

Linux 5.15.0-1036-aws

### Database type and version

MySQL 8.0.28

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.10-23)

**Comment by i-just** [comment]
Hi, thanks for reporting! We’ve made the `purify` filter more forgiving. If a `null` value is provided to the `$html` parameter, it will return it immediately instead of throwing an error.

**Comment by maxfenton** [comment]
> Hi, thanks for reporting! We’ve made the `purify` filter more forgiving. If a `null` value is provided to the `$html` parameter, it will return it immediately instead of throwing an error.

Thank you so much! 

I've recently made the switch from Redactor to CKeditor and (as part of that change) just started creating HTML Purifier configurations that match each CKeditor configuration.

**Comment by brandonkelly** [comment]
Craft 4.4.17 is out with the `purify` change. Thanks again!
