### ISSUE TITLE
[4.4.16.1]: In Asset filesystem Base URL doesnt work if environment variable used

### ISSUE THREAD

**Issue by FoxtrotCZ** [craftcms/cms#13498]
### Description
If you set environment variable and use it for setting Base URL of Asset filesystem it will not work and images will not show.

### Steps to reproduce

1. Create environment variable $PRIMARY_SITE_URL in .env and set to your website URL.
2. Have some working Asset filesystem with public URL and working uploaded images.
3. In your Asset filesystem set Base URL for example to $PRIMARY_SITE_URL/assets/images
4. Save and go to look at your images in admin panel.

### Expected behavior
You should see your images.

### Actual behavior
Images are not displayed because URL is not correctly resolved.
For example for website "Example.com" and image "MyImage.jpg" the URL in View button in Assets edit page is: "http://example.com/admin/$PRIMARY_SITE_URL/assets/images/MyImage.jpg"

### Craft CMS version

4.4.16.1

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch!

If you want to use a predefined value with an additional path, you can either define the whole thing as an environment variable or use an alias and append a further path to it.

In other words, either set an environment variable like so: `$UPLOADS_BASE_URL=<your_base_url>/assets/images` and use just `$UPLOADS_BASE_URL` as the Base URL for your filesystem, or you can use an alias, e.g. `@web/assets/images`.

Here’s a bit more info on the subject: https://craftcms.com/docs/4.x/config/#control-panel-settings. Most importantly: “_Whenever you see this UI, you can provide a valid alias or environment variable name, in addition to plain values. [...] Aliases have the extra benefit of allowing extra path segments, so @web/uploads is a perfectly valid setting._”
