### ISSUE TITLE
[4.x]: Simply cannot remove old plugin

### ISSUE THREAD

**Issue by bossanova808** [craftcms/cms#13506]
### Description

I simply cannot work out how to get rid of an old plugin:

![image](https://github.com/craftcms/cms/assets/731309/b07e3c74-2c57-4133-b8b9-f6226a1b0517)

I have:

- Released the license in Craft Console
- Tried re-installing and uninstalling again.
- Made sure it's not in `composer.json` or my `vendor` folder

(I'm now using the new GA4 version of this)

How in the holy can I get rid of this Zombie plugin???

### Steps to reproduce

Load the plugins page, initially this is not shown, but after a few seconds it appears at the bottom of the list.
_(Also it would be great if there was an easy cut and paste bit in the CP to give you all that version info you want below in one go!! - add a copy button to that 'System Report' page in Utilities and...wa la, correctly filled out bug reports forever more, right??)_

### Craft CMS version

Craft Pro 4.4.16.1

### PHP version

8.2.8

### Operating system and version

Linux 5.15.0-78-generic (Ubuntu 22.04)

### Database type and version

MySQL 8.0.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

![image](https://github.com/craftcms/cms/assets/731309/0c7d8d08-e0b0-4b18-9bdb-5c9df0a33777)

**Comment by brandonkelly** [comment]
It’s uninstalled. “Missing” means that Craft sees that the plugin license exists, and is tied to the current Craft license, so it’s listed in case you want to install it.

To fully wipe it from that page, you can reclaim it in Console, and then detach it from the Craft license.

**Comment by bossanova808** [comment]
Not exactly intuitive...but thanks!  That worked... (I'd asked several times in Discord etc to no avail, so definitely not a well known thing!)
