### ISSUE TITLE
[4.x]: NotFoundHttpException: Page not found

### ISSUE THREAD

**Issue by nickyichov** [craftcms/cms#13504]
### What happened?

Updated craft to  4.4.16.1 and now exception is thrown

### Description

After updating to craft 4.4.16.1 I have the following error

```
Next yii\web\NotFoundHttpException: Page not found. in /var/www/html/vendor/craftcms/cms/src/web/Application.php:611
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/web/Application.php(283): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#1 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#2 /var/www/html/web/index.php(25): yii\base\Application->run()
#3 {main}
```

The website works as expected. However, the error appears on every page. I have `'devMode' => true` so I can follow the error. 

I tried fixing it with this [issue](https://github.com/craftcms/cms/issues/4876) but it didn't work for me.

### Steps to reproduce

1. Update craft to 4.4.16.1

### Expected behavior

Functioning without error.

### Actual behavior

Error 404 appears on every page

### Craft CMS version

4.4.16.1

### PHP version

8.0.19

### Database type and version

MySQL 8.0.34

### Image driver and version

GD 8.0.19

**Comment by brandonkelly** [comment]
That error output should be followed by a previous exception output. Can you post that?

**Comment by nickyichov** [comment]
Yes, the whole error message is this:

```
yii\base\InvalidRouteException: Unable to resolve the request "formie/csrf/input". in /var/www/html/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/web/Application.php(304): yii\base\Module->runAction('formie/csrf/inp...', Array)
#1 /var/www/html/vendor/craftcms/cms/src/web/Application.php(607): craft\web\Application->runAction('formie/csrf/inp...', Array)
#2 /var/www/html/vendor/craftcms/cms/src/web/Application.php(283): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#3 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#4 /var/www/html/web/index.php(25): yii\base\Application->run()
#5 {main}

Next yii\web\NotFoundHttpException: Pagina niet gevonden. in /var/www/html/vendor/craftcms/cms/src/web/Application.php:611
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/web/Application.php(283): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#1 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#2 /var/www/html/web/index.php(25): yii\base\Application->run()
#3 {main}
```

I thought it is more plugin raleted than craft related, therefore I didn't post it. However, it seems that I found the problem causing it. The code for refreshing the CSRF token was outdated. After changing it with the new one, the 404 error is gone as well. 

My error was noticed [here](https://github.com/verbb/formie/issues/1519) and I used this [documentation ](https://verbb.io/craft-plugins/formie/docs/template-guides/cached-forms)to fix it.

**Comment by brandonkelly** [comment]
Glad you got it sorted!
