### ISSUE TITLE
Color form include is missing a closing ')' and asset load order

### ISSUE THREAD

**Issue by wbrowar** [craftcms/cms#1352]
### Description
`/craftcms/cms/src/templates/_includes/forms/color.html` is missing a closing`)` on line 12

UPDATE: fixing this leads to another issue. In the browser console, it says `Uncaught ReferenceError: jQuery is not defined` on `colorpicker.min.js:1`. Looking at the page source, it looks like `color picker.min.js` is loaded before `jquery.js`:
<img width="658" alt="google chrome_018" src="https://cloud.githubusercontent.com/assets/2158662/22628259/eb201012-eb9e-11e6-8050-33ab88313a1b.png">

### Steps to reproduce

1. In CP Settings template, include the form template:
```
{% import "_includes/forms" as forms %}

{{ forms.colorField( ... ) }}
```

### Additional info

- Craft version: Craft CMS 3.0.0-beta.2
- PHP version: 7.0.13
- Database driver & version: MySQL 5.6.34
- Plugins & versions: none

**Comment by takobell** [comment]
Not able to reproduce this locally.  Don't see a missing ) on `/craftcms/cms/src/templates/_includes/forms/color.html` and if I:

```
{% import "_includes/forms" as forms %}

{{ forms.colorField( ... ) }}
```

Then the color field displays as I'd expect.

**Comment by takobell** [comment]
Looks like this was fixed in https://github.com/craftcms/cms/issues/1354
