### ISSUE TITLE
[4.x]: Add button to edit or delete volume Asset Filesystem

### ISSUE THREAD

**Issue by vitalijalbu** [craftcms/cms#13523]
### Description
I created 2 Asset Filesystem but they are wrong, so I'd like to update or delete them. How to do that? 

![Screenshot 2023-08-08 alle 16 38 12](https://github.com/craftcms/cms/assets/40239902/38908cae-79ab-4e3b-b9c1-6a62ff106795)

### Steps to reproduce

1. Create empty file apth for volume

### Craft CMS version

4+

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
You can edit existing filesystems from **Settings** → **Media** → **Filesystems**.
