### ISSUE TITLE
[4.x]: Markdown extra incorrect Special Attributes behaviour

### ISSUE THREAD

**Issue by pixelmachine** [craftcms/cms#13537]
### What happened?

I have a plain text field which uses Markdown Extra e.g. `{{ copy | markdown('extra', false) }}` which works fine except  Markdown Extra's "Special Attributes" fail for certain formatting.

This works:
`[Google](http://www.google.com){attr=value}`
Output:
`<p><a href="http://www.google.com" attr="value">Google</a></p>`

As do classes and IDs like this `{.class #id}`.

This does NOT work:
`[Google](http://www.google.com){target=_blank}`
Output:
`<p><a href="http://www.google.com">Google</a>{target=_blank}</p>`

### Expected behavior

According to the [Dingus](https://michelf.ca/projects/php-markdown/dingus/) on the Markdown Extra site, this formatting should be valid. 

Dingus output:
`<p><a href="http://www.google.com" target="_blank">Google</a></p>`

Presumably the _ is causing the failure. 

### Craft CMS version

Craft CMS 4.3.6.1

### PHP version

8.1.17

**Comment by brandonkelly** [comment]
That should be reported over at https://github.com/cebe/markdown (the library that’s currently used for Markdown parsing in Craft). However it’s mostly abandoned, so we’re planning to switch to [league/commonmark](https://github.com/thephpleague/commonmark) in Craft 5.

**Comment by pixelmachine** [comment]
@brandonkelly as I said the formatting does work using PHP Markdown Extra and that can be tested via the link. It only doesn't work in Craft's implementation.

Commonmark doesn't support this syntax sadly.

**Comment by pixelmachine** [comment]
Ah wait I see what you're saying

**Comment by brandonkelly** [comment]
@pixelmachine Ah good catch.
