### ISSUE TITLE
[4.x]: GraphQL returns wrong url, when the slug of a related section is part of the Entry URI Format

### ISSUE THREAD

**Issue by martin-coded** [craftcms/cms#13531]
### Description

In my case I have different modules and categories which are both `sections` with the type `channel`. Every module has one category. 

The module section `Entry URI Format` contains the correlating category. It looks like this.

```twig
de/lernen/kategorie/{{learningCategory.one().slug}}/modul/{slug}
```

When I change the slug of a category, the url of the modules are not updates as you can check with a simple GraphlQL request. The output for the part `{{learningCategory.one().slug}}` is the old slug.

```graphql
{
  moduleEntries {
    ... on module_default_Entry {
      id
      url
    }
  }
}
```

As a workaround I can resave the module. I hoped  deleting the caches could work, but unfortunately this doesn't help.

### Expected behavior

Updating the category slug should also update the url of the module.

### Actual behavior

The returned url of the module section is the old one, which results in 404 errors.

### Craft CMS version

Craft Pro 4.4.13

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
An entry’s URI is only updated when the _same_ entry is saved. You can automate keeping the module entries’ URIs updated by writing a [Craft module](https://craftcms.com/docs/4.x/extend/module-guide.html) which listens for `learningCategory` entry saves, and triggers the other entries’ saves:

```php
use craft\base\Event;
use craft\elements\Entry;
use craft\events\ModelEvent;
use craft\helpers\ElementHelper;
use craft\helpers\Queue;
use craft\queue\jobs\ResaveElements;

Event::on(Entry::class, Entry::EVENT_BEFORE_SAVE, function(ModelEvent $event) {
    /** @var Entry $entry */
    $entry = $event->sender;

    // is this a learningCategory entry, and is its slug changing?
    if (
        $entry->getSection()->handle === 'learningCategory' &&
        !ElementHelper::isDraftOrRevision($entry) &&
        $entry->slug !== Entry::find()->id($entry->id)->siteId($entry->siteId)->status(null)->one()?->slug
    ) {
        // resave the module entries via a queue job, after the save is complete
        $entry->on(Entry::EVENT_AFTER_SAVE, function() use ($entry) {
            Queue::push(new ResaveElements([
                'elementType' => Entry::class,
                'criteria' => [
                    'section' => 'moduleSectionHandle',
                    'siteId' => $entry->siteId,
                ],
            ]));
        });
    }
});
```

**Comment by martin-coded** [comment]
Thank you very much for this solution! It works perfectly.
