### ISSUE TITLE
[4.5-beta]: `MoveElementEvent::getTargetElement()` queries by structure element ID when moving entries in a structure

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#13552]
### Description

I'm playing around with the new cancellable behavior for the `Structures::EVENT_BEFORE_MOVE_ELEMENT` event (introduced in https://github.com/craftcms/cms/pull/13429) and noticed that the new [`MoveElementEvent::getTargetElement()`](https://github.com/craftcms/cms/blob/4.5/src/events/MoveElementEvent.php#L53) method often throws an exception `'Invalid target element ID'`.

Digging into it, `MoveElementEvent::getTargetElement()` is supposed to return, and does query for, an `ElementInterface` element. However, when this event is constructed in the `Structures::_doIt()` method, the `MoveElementEvent::$targetElementId` attribute used in that element query [appears to be set to the structure element record ID](https://github.com/craftcms/cms/blob/a84324c98557bcf6c60d1aa465831116a2fc1226/src/services/Structures.php#L535C69-L535C88), instead of the actual target element ID.

### Craft CMS version

4.5.0-beta.1

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting and providing the solution! I raised a PR for it.

**Comment by brandonkelly** [comment]
4.5.0-beta.2 is out with that fix. Thanks again @mmikkel!
