### ISSUE TITLE
[4.5.0-beta.1]: Unable to click on ENV autocomplete in settings

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#13553]
### Description
When trying to setup the settings with ENV variables, the input fields do autocomplete the ENV variables when typing, but when clicking an a value, it isn't getting added

### Steps to reproduce

1. Go to a setting page (eg. General settings)
2. Try to set the System name to an ENV variable
3. start typing and try to select a suggested value
4. nothing happens

### Craft CMS version

4.5.0-beta.1

### PHP version

8.2.8

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR to adjust this.

**Comment by brandonkelly** [comment]
4.5.0-beta.2 is out with that fix. Thanks again!

**Comment by WHITE-developer** [comment]
Hi @brandonkelly,
On normal pages it's working fine now, but when in a slideout (ex. creating a filesystem from inside the assets) it has the same bug

**Comment by i-just** [comment]
> Looks like in slideout (ex. creating a filesystem from inside the assets) it has the same bug.

@WHITE-developer, can you please provide a bit more info? It works fine in a slideout on 4.5.0-beta.2 (except for the aws s3 bucket manual).

> Also for example if using the AWS S3 plugin, when trying to set the bucket manual, on these manual fields it’s also not working, for the other fields it is working

Yup, if you choose the bucket: manual, then the bucket and region fields don’t autocomplete well - thanks for reporting!

**Comment by WHITE-developer** [comment]
https://github.com/craftcms/cms/assets/22771556/b57af1cb-37cf-40d9-b016-969f9553c204

**Comment by WHITE-developer** [comment]
![image](https://github.com/craftcms/cms/assets/22771556/1cfb8939-9eec-4691-8615-2c648cbf8d8f)
Here I can't select any value

**Comment by i-just** [comment]
Thanks! It’s not happening consistently, but I’ve encountered it twice and know what's causing it.

**Comment by i-just** [comment]
I raised a new PR for this with a different approach. I have also tested that this was an issue in previous versions, but it was difficult to trigger (it only happened in a slideout and after a specific sequence of clicks). Changes made in 4.5 made this issue much more visible.

Thanks again for reporting!
