### ISSUE TITLE
[4.5.0-beta.2]: Cannot edit freshly uploaded images with required custom fields 

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#13566]
### What happened?

I (Klara) have inherited the job to keep track of open issues for this (mostly dead) account, this issue probably refers to #11569 / #12125

### Description

Setup:

* Two sites, en/de
* An asset volume with a required custom field `altText`, translatable by language.
* A section with a required custom field `featuredImage`, set to `Validate related assets`

### Steps to reproduce

1. Upload an image.
2. Edit image (via Assets menu), fill in an alt text and save.
3. 'Couldn't save asset'

![image](https://github.com/craftcms/cms/assets/60010597/2d57f230-50fe-4d5f-a5f6-a700520fe7c2)

4. However, switching to site 'Deutsch' and saving gives the same error (probably because there is no such thing as a provisional draft for assets and the edit from step 2 was never saved?)

Creating an entry, uploading an image directly to the assets field and editing/saving it via slideout, also gives the 'Couldn't save asset' error, but without a hint that the error comes from an other site, and leaves this:

![image](https://github.com/craftcms/cms/assets/60010597/f20de4e6-164c-4f9e-bd91-32d90d3b4321)

I assume something similar (no helpful error message) would happen when editing a related entry with errors on other sites via slideout. (#12488 would also be helpful...)

### Expected behavior

Be able to edit new images.

### Actual behavior

Not yet...

### Craft CMS version

Craft Solo 4.5.0-beta.2

### PHP version

8.1.21

### Operating system and version

Linux 5.15.90.1-microsoft-standard-WSL2

### Database type and version

MariaDB 10.4.30

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

None

**Comment by i-just** [comment]
Hi, thanks for reporting! I have raised a PR to adjust this.

**Comment by brandonkelly** [comment]
This has been fixed in Craft 4.5.0 (stable), released today.
