### ISSUE TITLE
[4.x]: Edit Image gives endless spinner; console shows error `e.image.getHeight is not a function`

### ISSUE THREAD

**Issue by proimage** [craftcms/cms#13573]
### Description
When trying to edit an image via the Craft backend, the full-screen image editor UI shows up, and the spinner spins in the middle, but the image never loads in. From this point, clicking "Cancel" does nothing, either, and the tab needs to be reloaded.
![image](https://github.com/craftcms/cms/assets/1027523/cf470db5-25c6-4e5b-95e0-babbe0ebac95)

AFAIK we don't have image loading issues anywhere else in the site, frontend or back.

The console shows this:
![image](https://github.com/craftcms/cms/assets/1027523/03e1d406-899b-4e05-9a99-576b76fb69bd)

### Steps to reproduce

1. No idea.

### Expected behavior
I'd expect the image to appear for editing in the editor.

### Actual behavior
The image fails to load.

### Craft CMS version

Craft Pro 4.4.17

### PHP version

8.1.2

### Operating system and version

Linux 6.2.0-1009-azure

### Database type and version

MySQL 8.0.32

### Image driver and version

Imagick 3.6.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- Azure Blob Storage 2.0.0
- Batch Actions 1.3.0
- Button Box dev-craft-4
- Cloudflare 2.0.0
- Colorit 4.0.0
- Color Mixer 3.0.0
- Cookies 4.0.0
- CP Field Inspect 1.4.4
- Field Manager 3.0.6
- Freeform 4.1.6
- Icon Picker 2.0.13
- Inventory 3.1.0
- LJ Range Slider 4.0.1
- Navigation 2.0.18
- Neo 3.7.9
- oEmbed 2.3.0
- Postmark 3.0.0
- Redactor 3.0.4
- Retour 4.1.12
- SEOmatic 4.0.30
- Sidebar Entry Types 2.0.1
- Social Share 1.0.1
- Sprig 2.6.2
- Super Table 3.0.9
- Twigpack 4.0.0-beta.4
- Typed link field 2.1.5
- Vizy 2.1.6
- Wordsmith 4.2.0

**Comment by brandonkelly** [comment]
Something must be messed up with that particular asset record, or the file.

Are you able to send a database backup along with the problematic file over to support@craftcms.com?

**Comment by proimage** [comment]
It's not just one file, it's every image. I've tested a few random images via Assets in the sidebar. It happens for JPG, PNG, and WEBP (i.e. all images).

It happened when the images were being stored locally; I thought it was probably some server configuration thing that would be rectified when the cloud storage was set up, but now that the images are on Azure Blob Storage, it's still happening.

**Comment by brandonkelly** [comment]
Hm, maybe a plugin is interfering somehow, then. Could you send a database backup and your Composer files over to support@craftcms.com?

**Comment by proimage** [comment]
Update; it looks like it was a plugin after all... the BugHerd browser extension, to be precise! https://chrome.google.com/webstore/detail/bugherd-visual-feedback-t/popigpemobhbfkhnnkllkjgkaabedgpb?hl=en

Can you recreate the issue with that installed? Note that it happens to me in both Craft 3.x and 4.x.

**Comment by brandonkelly** [comment]
Glad you figured it out! Sounds like something you should report to BugHerd – browser plugins shouldn’t be interfering with web apps.
