### ISSUE TITLE
Entry title not added to search index

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#1357]
### Description

It looks like the entry title is not being added to the search index.

### Steps to reproduce

1. create new entry with title "testtitle"
2. go to entry index page and search for "testtitle"

### Additional info

- Craft version: 3.0.0-beta.2
- PHP version: 7.0.15
- Database driver & version: MySQL 5.5.5
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Working on my end. If this persists for you, send a DB backup to support@craftcms.com and point us to the section that you’re seeing this issue on.
