### ISSUE TITLE
[4.x]: Intermittent slow site search queries after Craft 4 upgrade

### ISSUE THREAD

**Issue by tidy** [craftcms/cms#13578]
### Description
Since upgrading to Craft 4, front-end site searches hang intermittently. The server monitor shows slow database queries involving the searchindex table which result in 100% CPU usage.

The rest of the site usually still seems to load ok somehow with this issue, but any site search will hang and not load results.

The searchindex table has 43K rows, 4.5m data length and 4.5m index length. Running optimize on the table did not help.

### Steps to reproduce

The problem is intermittent but I have 2 search forms:
1) a simple keyword search form which fetches results from 1 structure and 1 channel (separately)
2) a form combining several single category filters with a keyword search which fetches results from 1 structure

Example slow query (intermittent): 
SELECT * FROM `searchindex`WHERE ((`keywords` LIKE '%red%') AND (`keywords` LIKE '%11%') AND (`keywords` LIKE '%womens%')) AND (`elementId` IN (SELECT `elements`.`id`FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`FROM `elements` `elements`INNER JOIN `entries` `entries` ON `entries`.`id` = `elements`.`id`INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`INNER JOIN `content` `content` ON `content`.`elementId` = `elements`.`id`LEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `elements`.`id`) AND (`structureelements`.`structureId`=1)WHERE (`entries`.`sectionId`=2) AND (((`elements`.`enabled`=1) AND (`elements_sites`.`enabled`=1)) AND (`entries`.`postDate` <= '2023-08-18 16:48:59') AND ((`entries`.`expiryDate` IS NULL) OR (`entries`.`expiryDate` > '2023-08-18 16:48:59'))) AND (`elements`.`archived`=0) AND (`elements`.`dateDeleted` IS NULL) AND ((`elements`.`id` IN (SELECT `targets696`.`sourceId`FROM `relations` `targets696`WHERE (`targets696`.`targetId`=318) AND ((`targets696`.`sourceSiteId` IS NULL) OR (`targets696`.`sourceSiteId`=1)))) AND (`elements`.`id` IN (SELECT `targets697`.`sourceId`FROM `relations` `targets697`WHERE (`targets697`.`targetId`=391) AND ((`targets697`.`sourceSiteId` IS NULL) OR (`targets697`.`sourceSiteId`=1)) AND (`targets697`.`fieldId`='23'))) AND (`elements`.`id` IN (SELECT `targets698`.`sourceId`FROM `relations` `targets698`WHERE (`targets698`.`targetId`=303) AND ((`targets698`.`sourceSiteId` IS NULL) OR (`targets698`.`sourceSiteId`=1)))) AND (`elements`.`id` IN (SELECT `targets699`.`sourceId`FROM `relations` `targets699`WHERE (`targets699`.`targetId`=308) AND ((`targets699`.`sourceSiteId` IS NULL) OR (`targets699`.`sourceSiteId`=1)))) AND (`elements`.`id` IN (SELECT `targets700`.`sourceId`FROM `relations` `targets700`WHERE (`targets700`.`targetId`=43986) AND ((`targets700`.`sourceSiteId` IS NULL) OR (`targets700`.`sourceSiteId`=1))))) AND (`elements`.`draftId` IS NULL) AND (`elements`.`revisionId` IS NULL)) `subquery`INNER JOIN `elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`INNER JOIN `entries` `entries` ON `entries`.`id` = `subquery`.`elementsId`INNER JOIN `content` `content` ON `content`.`id` = `subquery`.`contentId`LEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `subquery`.`elementsId`) AND (`structureelements`.`structureId`=1))) AND (`siteId`=1);

Has much changed re searching entries in Craft 4? 
Thanks for your time,
Janine.

### Craft CMS version

4.4.17

### PHP version

8.0.30

### Database type and version

MariaDB 10.4.20

### Installed plugins and versions

-

**Comment by angrybrad** [comment]
@tidy If you're`searchindex` table is using the MyISAM storage engine, convert it to `InnoDB` and that should help.

Also verify that all of your database tables are using a consistent character set and collation. i.e. something like `utf8mb4` and `utf8mb4_general_ci`. The important bit is that they are consistent across all tables.

**Comment by tidy** [comment]
Thanks a lot Brad. All tables use utf8_general_ci but the searchindex table was the only MyISAM one (in both Craft 3 & 4), so I've converted it to InnoDB now. Since it's an intermittent problem, I don't know if it's helped yet but fingers crossed.

**Comment by angrybrad** [comment]
My guess is that’ll solve it, but comment back here if it doesn’t, and we can re-open the issue.
