### ISSUE TITLE
[4.x]: reserved handles should include Account Status handles

### ISSUE THREAD

**Issue by Liv-Tarot** [craftcms/cms#13579]
### Description
The Account Status handles are not included in the list of reserved handles (found in cms/src/base/Field.php), which causes issues when creating new fields.

### Steps to reproduce

1. Use any of the account status handles ("Active", "Pending", "Suspended", "Locked", "Inactive") when creating a new field handle.
2. No error pops up to warn the dev that these cannot be used, they are able to be created and used throughout the site.

### Expected behavior
They should not be able to be used as field names since they reference specific user attributes that are hard coded into the CMS.

### Actual behavior
The fields work as intended by the dev in most of the CMS, but issues arise when these field names are referenced in relation to account holders. At that point (when referencing users), they work as intended by the CMS (referencing the account status) instead of as intended by the dev.

### Craft CMS version

craft4

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Just added the following to the list of reserved user field handles, for Craft 4.5:

- `active`
- `addresses`
- `admin`
- `email`
- `friendlyName`
- `locked`
- `name`
- `password`
- `pending`
- `suspended`
- `username`

(You’ll still be able to create custom fields with those handles; you just won’t be allowed to use them within the _user_ field layout.)

**Comment by brandonkelly** [comment]
Craft 4.5.0 is out with that change.
