### ISSUE TITLE
[4.x]: Field still in database after deleting and GC

### ISSUE THREAD

**Issue by loqus** [craftcms/cms#13581]
### Description
I removed a field that was obsolete (first removed it from section, then deleted it) from a multi-language site.
But in the content field the field was still in the table. 
The section the field was in is a "structure". Versioning is enabled and the section was set to Save entries to all sites enabled for this section.
I pruned all revisions before deleting the field via the CMS and did a garbage collection

### Expected behavior
Field deleted from the CMS + garbage collection results in content table not having this field.

### Actual behavior
Field is still there (some with contents)

### Craft CMS version

4.4.17 Pro

### PHP version

8.0.25

### Operating system and version

Linux 3.10.0-1160.76.1.el7.x86_64

### Database type and version

MariaDB 10.5.22

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.10-68)

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Field columns are dropped immediately when a field is removed. Guessing it just looked like it was still around due to your MySQL client’s schema cache.
