### ISSUE TITLE
[4.5-beta.2]: Error typing issue when drag/dropping image on an assets field.

### ISSUE THREAD

**Issue by michtio** [craftcms/cms#13585]
### Description
When dragging an image to the image upload field, an error is thrown:

<img width="617" alt="Screenshot 2023-08-22 at 15 25 16" src="https://github.com/craftcms/cms/assets/5818021/61fb4d4f-5657-410d-8eb0-2deefc90d370">

### Steps to reproduce

1. Create an assets field for image uploads
2. Don't click on upload image, but take a local image, and drag and drop it onto the asset fields
3. Typing error displays

### Craft CMS version

4.5-beta.2

### PHP version

8.2

### Database type and version

MySQL 8

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just ran into the same error earlier this morning :) Fixed for the next release.

**Comment by brandonkelly** [comment]
4.5.0 (stable) is out now with that fix.

**Comment by michtio** [comment]
> 4.5.0 (stable) is out now with that fix.

Awesome thanks @brandonkelly 
Just was playing around with it and it popped up 😅
