### ISSUE TITLE
[4.x]: Save as new Entry not propagating new entry to other sites

### ISSUE THREAD

**Issue by BlizzardWizzard** [craftcms/cms#13599]
### Description
When saving a modified existing entry as a new entry, the new entry does not propagate to other sites, even though the section has set the propagation method to "Save entries to all sites enabled for this section".
The modified entry is enabled in all sites before saving as a new Entry.

### Steps to reproduce

1. Create minimal Craft install
2. Create multiple sites
3. Create a section (structure/channel) that is active in these sites
4. Save an entry in said section
5. Edit entry and wait for draft to save
6. Save as new Entry

### Expected behavior
The entry is saved as a new entry in all sites.

### Actual behavior
The entry is saved as a new entry only in the same site.

### Craft CMS version

4.5.1

### PHP version

8.1.21

### Operating system and version

Linux 5.15.90.1-microsoft-standard-WSL2

### Database type and version

MySQL 8.0.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

**Comment by wmdhosting** [comment]
As much i know that works that way. for quite some time.  It only copy to all sites first time you publish..  not after you edit..

Thats way there  is https://plugins.craftcms.com/site-copy-x?craft4 that can help you..

**Comment by BlizzardWizzard** [comment]
Sorry, maybe I should've been clearer.

I do *not* mean that the changes from a draft should be propagated to the same entry in different sites when saving the entry.
And by "draft" I do *not* mean an entry explicitly saved as a draft by the user, I mean the draft that Craft automatically saves while editing an entry in the control panel. I'm sorry if that's the wrong terminology.

I mean that when I have an *automatically saved draft* of an entry and try to save that draft as a new entry (using the "Save as new entry" button), the draft is saved as a new entry in the same site as the draft, *but the new entry is not propagated to the other sites*.

In my eyes, this clashes with the section's propagation setting "Save entries to all sites enabled for this section".

**Comment by brandonkelly** [comment]
Agree this sounds like a bug. Will look into it soon.

**Comment by brandonkelly** [comment]
Craft 4.5.3 is out now with a fix for this. Thanks for reporting!
