### ISSUE TITLE
[4.5]: New Entries do not reflect default disabled status from Section setting + Disabled entries are enabled upon edit. 

### ISSUE THREAD

**Issue by philperusse** [craftcms/cms#13595]
### Description
1. New Entries status do not reflect the section default status when this default is disabled
2. Status field will be set as Enabled when editing existing disabled entries

### Steps to reproduce

1. Brand new Craft 4.5 installation
2. Create an section with a default disabled status.
3. Create an entry within that section : the status field will be enabled
4. Switch the status to disable and save.
5. Edit that disabled entry, switch will be back to disabled

### Expected behavior
1. Status should reflect default behaviour set in the Section Settings
2. Status should not be enabled when editing disabled entries

### Actual behavior
1. Status is always set to enabled.

### Thoughts
Not 100% sure but looks like these changes could be the culprits.

https://github.com/craftcms/cms/pull/13265/commits/403187289ffb3582943d4cfdc1baeec51bff4fd0
https://github.com/craftcms/cms/pull/13265/commits/403187289ffb3582943d4cfdc1baeec51bff4fd0#diff-aee2e79d39f0844ff1b3633c4c8ad09b7f6a18ff355d1242b07f7d8041431d54R110
https://github.com/craftcms/cms/pull/13265/commits/403187289ffb3582943d4cfdc1baeec51bff4fd0#diff-aee2e79d39f0844ff1b3633c4c8ad09b7f6a18ff355d1242b07f7d8041431d54L1767-R1764

### Craft CMS version

4.5

### PHP version

8.1

### Installed plugins and versions

- None.

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 4.5.1 is out now with a fix.
