### ISSUE TITLE
[4.5]: Notification gets stuck on entry edit page and prevents further entry save via shortcut

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#13591]
### Description

When editing an entry and hitting `save and continue editing` the notification is not automatically discarded if the user continues editing the entry (thus taking the focus away from the notification).

A further complication, which is also new to 4.5: 
While the notification is open, the shortcut for `save and continue editing` becomes inactive and instead `ctrl+s` triggers the native browser functionality of trying to save the web page. That's a big gotcha, because, due to the first issue, the notification is very likely to have stayed open without the author noticing.

### Steps to reproduce

1. Open an entry.
2. Update a field
3. Do a ''save and continue editing' action either via shortcut or the save button.

### Expected behavior
A notification appears and is discarded after the amount of time set in the user preferences.

### Actual behavior
The notification is only automatically discarded if you don't click anywhere before it disappears.

### Craft CMS version

4.5

### Installed plugins and versions

-

**Comment by arifje** [comment]
Also experiencing this after we upgraded this morning.

In addition we are also experiencing the status button is always toggled to ENABLED, even when the entry is disabled.

And, conditional fields aren't toggling anymore.

Javascript issue?

**Comment by thupsi** [comment]
I just found [this comment](https://github.com/craftcms/cms/issues/13574#issuecomment-1684484471
) by @brandonkelly in a [related issue](https://github.com/craftcms/cms/issues/13574).

So it seems that the second part of the issue (blocked shortcuts) is kind of intended behaviour. 

I would argue though that shortcuts **should not be blocked when the focus is not on the notification**, eg. when the user continues editing the entry.

It's not unusual for an author to make a change, save, realise that he wants another change, do that, and save again. Right now he is presented with a 'save web page' screen. I predict this will be frustrating for many. At least _I_ stumbled upon it almost immediately.

**Comment by aelvan** [comment]
Also running into this immediately after upgrading to 4.5. Extremely frustrating behaviour.

**Comment by brandonkelly** [comment]
Craft 4.5.1 is out now with a fix for this. Now UI layers can be configured to allow shortcuts to bubble up to their parent layers, and we’re taking advantage of that for CP notifications. So they can add their <kbd>Esc</kbd> shortcut without interfering with previously-registered ones.

**Comment by thupsi** [comment]
@brandonkelly Thanks for fixing the blocked shortcut issue on such a short notice! The first part though remains as described above (the notification gets stuck if the user clicks outside of it).

**Comment by brandonkelly** [comment]
Sorry, overlooked that. Fixed now for the next release.

**Comment by brandonkelly** [comment]
Craft 4.5.2 is out with a fix for the `blur` behavior.
