### ISSUE TITLE
[4.5.0]: Matrix serializeValue() fields closure

### ISSUE THREAD

**Issue by lukasNo1** [craftcms/cms#13592]
### Description
Since craft 4.5.0 the Matrix serializeValue() returns the fields a closure rather than an array of fields like in 4.4.*
https://github.com/craftcms/cms/blob/develop/src/fields/Matrix.php#L578

My use case goes something like this:
1. We serialise a MatrixBlockQuery with $field->serializeValue()
2. We use $entry->setFieldValue('fieldname', $serializedValue) to copy the matrix Block to a different matrix field (of the same type)

Since 4.5.0 the setFieldValue doesnt work anymore. The matrix fields gets created, but the fields are just blank as this function is expecting an array of fields and cannot read the closure

### Craft CMS version

4.5.0

### PHP version

8.2

**Comment by lukasNo1** [comment]
I saw the change was added to provide lazy loading to graphQl queries.

I am implementing a workaround for now with looping through the response from serializeValue() and executing the fields closure, but i would appreciate it if you could make the serializeValue() compatible with the setFieldValue() function. Maybe with an additional parameter $lazyLoad = true in the serializeValue() function?

**Comment by brandonkelly** [comment]
Sorry, that was not an intended change! Craft 4.5.1 is out with `Matrix::serializeValues()` reverted to how it was before.
