### ISSUE TITLE
[4.x]: Front end user registration not returning proper errors. User gets added even if expected to fail.

### ISSUE THREAD

**Issue by sprngLf** [craftcms/cms#13596]
### Description
Front end user registration not returning proper errors.
Only returns the error for password field.

### Steps to reproduce

1. Copy code from [https://craftcms.com/knowledge-base/front-end-user-accounts#registration-form](https://craftcms.com/knowledge-base/front-end-user-accounts#registration-form)
2. Click 'Register' button

### Expected behavior
This should at least return `Username is required`, `Email is required` and `New Password* should contain at least 6 characters.`.
And not add the user to system since it's a failed registration.

### Actual behavior
Only returns `New Password* should contain at least 6 characters.`.
User gets added to the system even if a failed registration.

### Craft CMS version

Craft Pro 4.4.17 to Craft Pro 4.5.1

### PHP version

8.0.29

### Operating system and version

Linux 6.2.0-26-generic

### Database type and version

MariaDB 10.3.39

### Installed plugins and versions

-

**EDIT**:
only happens when `Deactivate users by default` is checked and password is provided in the registration form.

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 4.5.2 is out with a fix.

**Comment by sprngLf** [comment]
Thank you for the quick fix.
