### ISSUE TITLE
[4.x]: Editing a saved entry via slideout triggers a double-save

### ISSUE THREAD

**Issue by engram-design** [craftcms/cms#13604]
### Description
I'm trying to isolate an [issue](https://github.com/verbb/navigation/issues/366) with Navigation, and I _think_ this might be related. At the very least, I wanted to check if this was correct.

I'm seeing that when I use the element slide-out to edit an entry, it's triggering a new `save-draft` action the first time I make a change.

Here's a video to illustrate it - no custom fields, just the title. https://share.cleanshot.com/JKFKvPrd

1. Create a new entry in a section. No custom fields required.
2. Save and head back to the entry index
3. Double-click the entry to open up the element slide-out
4. Make a change to the title. Once stopped typing, notice the draft is being autosaved
5. Click-off the title field, anywhere else in the slide-out. This blur event triggers another save event

### Craft CMS version

4.5.2

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.5.3 is out now with a fix for this. Thanks again!
