### ISSUE TITLE
User (admin) not permitted to edit global set in another language [4.x]: 

### ISSUE THREAD

**Issue by leowebguy** [craftcms/cms#13606]
### Description

CP language switch doesn't work on Globals
Craft won't allow admin user to access globals in another language

### Steps to reproduce

1: I can access and edit https://aaa.org/admin/globals/configs (english) but CP language switch doesn't work (bug 1)

2: Go to entries, switch to another language and go back to globals >> https://aaa.org/admin/globals/configs?site=spanish ... I get the message:

Unauthorized
User not permitted to edit global set

### Expected behavior

Allow admin user to access globals in another language

### Actual behavior

![Screenshot 2023-08-25 at 8 55 58 AM](https://github.com/craftcms/cms/assets/8460020/1d0a57fa-2968-4ae3-bfe2-5ff6a60e95ef)

### Trace

```
yii\web\ForbiddenHttpException: User not permitted to edit global set in /media/data/www/aaa.org/vendor/craftcms/cms/src/controllers/GlobalsController.php:166
Stack trace:
#0 [internal function]: craft\controllers\GlobalsController->actionEditContent()
#1 /media/data/www/aaa.org/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#2 /media/data/www/aaa.org/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#3 /media/data/www/aaa.org/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#4 /media/data/www/aaa.org/vendor/craftcms/cms/src/web/Application.php(304): yii\base\Module->runAction()
#5 /media/data/www/aaa.org/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#6 /media/data/www/aaa.org/vendor/craftcms/cms/src/web/Application.php(289): yii\web\Application->handleRequest()
#7 /media/data/www/aaa.org/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#8 /media/data/www/aaa.org/web/index.php(12): yii\base\Application->run()
#9 {main}
```

### Craft CMS version

4.5.1

### PHP version

8.1

### Operating system and version

linux/ddev

### Database type and version

mariadb 10.4

### Installed plugins and versions

Element API 3.0.1.1
Logs 4.0.0
Maps 4.0.4
Mix Manifest 1.0.3
Redactor 3.0.4
Site Switcher 2.3.0

**Comment by brandonkelly** [comment]
This was fixed in 4.5.2! (See #13603)
