### ISSUE TITLE
[4.5.1^]: JavasScript console errors in CP pages on any keypress

### ISSUE THREAD

**Issue by gustavs-gutmanis** [craftcms/cms#13605]
### Description

Whenever I press any key at all (alphanumeric, modifier, esc, doesn't matter), I get a console error:

![image](https://github.com/craftcms/cms/assets/709181/6de1d0f8-edc1-4291-84b3-67b258395adb)

This seems to be happening in the [UILayerManager.js](https://github.com/craftcms/cms/blob/develop/src/web/assets/garnish/src/UiLayerManager.js#L168) file

```js
// UILayerManager.js

triggerShortcut: function (ev, layerIndex) {
  if (typeof layerIndex === 'undefined') {
    layerIndex = this.layer;
  }
  const layer = this.layers[layerIndex];
  const shortcut = layer.shortcuts.find(
    (s) =>
      s.shortcut.keyCode === ev.keyCode &&
      s.shortcut.ctrl === Garnish.isCtrlKeyPressed(ev) &&
      s.shortcut.shift === ev.shiftKey &&
      s.shortcut.alt === ev.altKey
  );

  if (shortcut) {
    ev.preventDefault();
    shortcut.callback(ev);

  // <-- `.bubble` is causing the error
  } else if (layer.options.bubble && layerIndex > 0) {
    this.triggerShortcut(ev, layerIndex - 1);
  }
},
```

### Steps to reproduce

1. Open the Craft CMS CP panel (any page)
2. Open dev-tools
3. Press any key
4. See the error in the console

### Expected behavior

There should be no errors when pressing keys.

### Actual behavior

There are errors when pressing keys.

### Craft CMS version

4.5.1

### PHP version

8.1.13

### Operating system and version

MacOS 13.4.1

### Database type and version

MySQL 5.7.39

### Image driver and version

GD 2.1.0

### Installed plugins and versions

- No plugins

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.
