### ISSUE TITLE
[4.5.2]: Customize Sources relatedTo via Twig Template isn't working

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#13617]
### Description
I use a custom source with a `relatedTo` criteria. 
There is a  hint: `This can be set to an environment variable or a Twig template that outputs an ID.`

I tried different ways to use a twig template here, but it didn't work. My twig templates are within the `template` folder, and this is the code:

```twig
{{ '4674022' }}
```

![image](https://github.com/craftcms/cms/assets/764292/3600bc22-34e1-45c6-9107-61a8775b6632)

I can't set env vars in my case so the twig templates is the way to go for me. 

### Craft CMS version

4.2.2

### PHP version

8.2

### Operating system and version

Mac OSX

### Database type and version

Postgres

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Sorry yeah, it means you can put Twig code in there, not a template file.

If you really want to keep the code in a file, you could use an `{% include %}` tag.

```twig
{% include 'sessions_2023.twig' %}
```

**Comment by davidhellmann** [comment]
Short follow up question @brandonkelly 

This is working when putting to the field: `{{ craft.entries().siteId([46,47,48,49]).section('dteEventSeries').title('*2023*').ids()|join(',') }}`

This not: `{{ craft.entries().siteId(currentSite.id).section('dteEventSeries').title('*2023*').ids()|join(',') }}`

Is that expected because `currentUser` is working `currentSite` not?

**Comment by brandonkelly** [comment]
`currentSite` will always be the primary site for control panel requests, even if you’re editing an element on a different site.

`siteId` should work though, which will be the edited element’s `siteId` property value.

```twig
{{ craft.entries().siteId(siteId).section('dteEventSeries').title('*2023*').ids()|join(',') }}
```

**Comment by davidhellmann** [comment]
Nope, looks like that didn't work.

Do it this way now:
```twig
{% set sites = craft.app.sites.getAllSites()
    | filter(site => 'events_' in site.handle)
    | map(site => site.handle) %}

{{ craft.entries().site(sites).section('dteEventSeries').title('*2024*').ids()|join(',') }}
```

But of course, with the `siteId` it would be a bit smarter :)
