### ISSUE TITLE
[4.x]: Settings->Email SMTP credentials UI bug

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#13613]
### What happened?

Fresh 4.5.2 install.

Go to Settings->Email and select SMTP.

![CleanShot 2023-08-28 at 09 45 52](https://github.com/craftcms/cms/assets/61869/a3070cf3-13dd-4572-a9f0-4baeec881819)

"Use authentication" is selected, but there is no input for a username/password.

Click "save" to cause a validation error and the fields display.

![CleanShot 2023-08-28 at 09 46 55](https://github.com/craftcms/cms/assets/61869/58be293b-7289-424f-bc59-8288ab14cbfa)

### Craft CMS version

4.5.2

### PHP version

8.1

### Database type and version

n/a

**Comment by olivierbon** [comment]
Something is still wrong with those.

I have:

```
OUI=1
NON=false
```

In Craft 4.4, I see this which is correct:

![oli_G6g0g6hq@2x](https://github.com/craftcms/cms/assets/146041/71018568-5332-4a1f-bbb9-99e70016798b)

From Craft 4.5, I see this which is wrong. The values are honoured but the display is off:

![oli_NzNbmHGv@2x](https://github.com/craftcms/cms/assets/146041/f57934b7-15b9-40d6-94d3-fb82bd552419)

**Comment by thisisjamessmith** [comment]
I bumped into this today on Craft 5.4.1. I can't reproduce it now. Worked around it by saving and getting the validation error, after which the username and password fields reappear.
