### ISSUE TITLE
Customized setting not assessable in plugin's init function 

### ISSUE THREAD

**Issue by johnfmorton** [craftcms/cms#1361]
### Description

Accessing a plugin's settings in the init function of a plugin will only return the default values, not the ones that have been saved to the database by a user who's customized them. Specifically, I was trying to let a user rename the plugin in the control panel but don't seem to be able to do this.

### Steps to reproduce

1. Check out this sample plugin that isolates the issue: https://github.com/johnfmorton/craft3settingsTestPlugin
2. Have devMode on and the Yii2 panel available. 
3. Check the log for 'trace' commands for the "settingtest" plugin. Notice the traces in the init command. 
4. Then go to the settings panel for the "settingtest" plugin and change "Some Default" to something else.
5. Go back to any page, for example the plugin's home page, and notice the trace logs again. Although you'll see the customized setting in the trace of the whole object, you'll still get the default value when you try to access it directly `SettingTest::$plugin->getSettings()->someField`. 

The JSON has been accessed from the database for the plugin, but the settings model doesn't seem to be populated with that data yet in the init function. Perhaps there is a better way to do this that I'm not aware of though but it does seem like the settings should be available in the init function of the plugin.

### Additional info

- Craft version: Craft CMS 3.0.0-beta.3
- PHP version: 7.1
- Database driver & version: MySQL 5.0.12
- Plugins & versions: only the plugin referenced about in Step #1

**Comment by brandonkelly** [comment]
Thanks for building that example plugin! Fixed now.

To clear things up, previously plugin settings didn't actually get set until *after* the plugin had finished initializing.  So at the time this was called from your sample plugin’s `init()` method:

```php
Craft::trace($this->settings, __METHOD__);
```

...the DB-stored values hadn’t actually been set on the Settings model yet. But at that point all you’re really doing is logging a reference to the model – and the model wasn’t getting serialized until the end of the request, so it only *looked* like it had the DB-stored value at the time you call `Craft::trace()` whereas in reality that value wasn’t getting added until a bit later on.

Anyway, not an issue anymore.
