### ISSUE TITLE
[4.5.3]: typeId appearing under Entry Type label

### ISSUE THREAD

**Issue by RyanRoberts** [craftcms/cms#13627]
### What happened?

When `Show field handles in edit forms` is enabled a copy text button with `typeId` appears below the Entry Type label. Maybe it's intentional, but doesn't feel intentional.

![Google Chrome - 2023-08-30--11-47-20@2x](https://github.com/craftcms/cms/assets/108874/62deb27e-b955-463a-a887-d795f264279b)

### Steps to reproduce

1. Enable Show field handles in edit forms in user profile
2. Make sure you have more than one entry type so the Entry Type label appears in the sidebar

### Expected behavior

Either not to appear at all, or not to break label layout.

### Craft CMS version

4.5.3

### PHP version

8.2

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR to adjust this.

**Comment by brandonkelly** [comment]
Craft 4.5.4 is out with that fix. Thanks again!
