### ISSUE TITLE
Lightswitch UI bug when only one on/off label exists

### ISSUE THREAD

**Issue by RyanRoberts** [craftcms/cms#13629]
### Description

The lightswitch field is missing some padding between the container edge and the toggle button itself when only one of the on or off labels exists. Best shown with this screenshot:

<img width="130" alt="Google Chrome - 2023-08-31--12-55-56@2x" src="https://github.com/craftcms/cms/assets/108874/1055b73f-ecb8-4a7b-830d-fc979b293ad9">

Solution would be to either move the padding from the labels to the container with the border, or move the margins from the labels to the button itself.

### Steps to reproduce

1. Create a lightswitch field with only one text label in either the on or off field.

### Expected behavior

Padding to the left or right of the toggle button.

### Actual behavior

Missing padding to the left or right of the toggle button.

### Craft CMS version

4.5.3

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR to adjust this.

**Comment by brandonkelly** [comment]
Craft 4.5.4 is out with that fix. Thanks again!
