### ISSUE TITLE
[4.x]: Photos are not restored after the revision is restored

### ISSUE THREAD

**Issue by iZerus** [craftcms/cms#13626]
### Description

I created a record, added photos to it. Then I deleted the photos. But when I decided to restore the previous version (where there were photos), the photos never recovered. 
P.S. When deleting photos, photos remain in assets

### Steps to reproduce

1. Create a section with the Assets field (with versioning control)
2. Create an entry in this section and attach photos to it
3. Save it
4. Delete photos from entry and save
5. Try to restore the version with photos

### Expected behavior

Photos must be present in the entry

### Actual behavior

Photos are missing

### Craft CMS version

 4.5.3

### PHP version

8.1

### Installed plugins and versions

- Redactor 3.0.4
- Site Switcher 2.3.0

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR to adjust this.

**Comment by brandonkelly** [comment]
Craft 4.5.4 is out with that fix. Thanks again!

**Comment by olivierbon** [comment]
There might be a part two to this. It also happens with Matrix Blocks.


https://github.com/craftcms/cms/assets/146041/079987fb-49eb-4def-8244-0a26b2b30f32

**Comment by brandonkelly** [comment]
Thanks @olivierbon! Fixed for the next release via #13740.

**Comment by brandonkelly** [comment]
Craft 4.5.6 is out now with that fix.
