### ISSUE TITLE
[3.x]: Calling unknown method: craft\console\Request::getBodyParam()

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#13623]
### What happened?

There is a condition in Craft that makes a console command sometimes call Request::getBodyParam(). 

Here is the stack trace:
https://morskieft-ontwerpers.sentry.io/share/issue/24ed1df7903b451d9df6e0b4ffb94722/

<img width="981" alt="Screenshot 2023-08-30 at 10 51 03" src="https://github.com/craftcms/cms/assets/378974/c7f3f665-63a8-40e0-bcd7-48202a2099dc">

### Craft CMS version

3.9.1

### PHP version

8.2.7

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR to adjust this.

**Comment by brandonkelly** [comment]
Fixed for the next release via #13647!

**Comment by brandonkelly** [comment]
Craft 3.9.2 is out with that fix.
