### ISSUE TITLE
[4.x]: Regex replace not working as expected with slashes in pattern

### ISSUE THREAD

**Issue by seb-enovate** [craftcms/cms#13638]
### Description

We are trying to use the `replace` Twig filter that Craft provides to remove a path segment from a URL, *including* the surrounding forward slash characters. So for example we are trying to go from `https://example.com/a/` to `https://example.com`, but can't seem to get it to work.

We have tried testing out our regex pattern on regex101 and it seems to match correctly - [find that here](https://regex101.com/r/1UThRw/1).

### Steps to reproduce

Add the following Twig code to any template and observe the `dd` output:

```twig
    {% set url = 'https://example.com/a/' %}

    {% set urlWithoutPath = url|replace('/\/a\//', '') %}

    {% dd urlWithoutPath %}
```

### Expected behavior

The string `"https://example.com"` is output by `dd`

### Actual behavior

The string `"https://example.com/a/"` is output by `dd`

### Craft CMS version

4.5.3

**Comment by mtwalsh** [comment]
Just adding a link to the change that was made on the discussion as I just hit this issue on another project:

https://github.com/craftcms/cms/discussions/13642
