### ISSUE TITLE
[3.x]: Sidebar scrolling is a bit confusing/difficult

### ISSUE THREAD

**Issue by KarlBishop** [craftcms/cms#13637]
### What happened?

When editing entries that have a lot of stuff in the sidebar, at first glance it appears that some content is not accessible.

This happens when the sidebar is taller than the screen height. And is exacerbated because I'm slightly motor-impaired.

My motor-impairment means I tend to use the visible scrollbar at the side of the browser window (because clicking and dragging is easier than using a scroll-wheel).

When I click and drag the scrollbar, the sidebar docks to the right-hand-side of the screen and does not scroll. This means sidebar content beyond the screen height cannot be reached using this method.

I tried using middle-click scrolling (aka auto-scrolling) and found the same behaviour, even when the middle-click is engaged while hovering over the sidebar.

At this point I thought it was not possible to reach the lower sidebar content at all but then, kind of by accident, I found that if I middle-click scroll to the bottom of the page, then release and re-engage the middle-click whilst hovering over the sidebar, I can at last scroll it. But I reckon this is a bit tricky to figure out. It might be better if, when the sidebar is taller than screen-height, it did not dock to the side and just scrolled with the main content 🤔🤷‍♂️

### Craft CMS version

Craft Pro 3.8.11

### PHP version

8.1.19

### Operating system and version

Linux 5.10.0-0.deb10.17-amd64

### Database type and version

MariaDB 10.11.5

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.1-8)

**Comment by brandonkelly** [comment]
Thanks for pointing that out!

I’ve just improved the scrolling behavior for detail panes and left-hand page sidebars for the next Craft 3 and 4 releases: they now scroll along with the page up until the bottom of their containers are reached, at which point they will stick to the bottom of the viewport.

**Comment by KarlBishop** [comment]
Fantastic, thanks @brandonkelly !

**Comment by brandonkelly** [comment]
Craft 3.9.2 and 4.5.4 are out with that change!

**Comment by jamesmacwhite** [comment]
I think this has had a negative impact. This is an example of our Formie submissions screen. We have a lot of forms and hence items in the sidebar, but we can no longer scroll and see all submissions in the left hand colour under 3.9.2

![image](https://github.com/craftcms/cms/assets/8067792/13567414-da51-4d8e-a84d-7879314571f6)

**Comment by jamesmacwhite** [comment]
I think it goes further than form, when the content panel has little information, another example

![image](https://github.com/craftcms/cms/assets/8067792/6d657f23-7c3f-494d-ba4e-ea669736fe9d)

When the left column has more length than the main content area, this change isn't ideal.

**Comment by jamesmacwhite** [comment]
Thank you!

**Comment by KarlBishop** [comment]
I just got around to trying 3.9.2 and realised it didn't solve my issue yet. Now when I scroll to the bottom of the screen, the sidebar remains cut off - I can only scroll as far as the main content goes - and it's no longer possible to use a middle-click to scroll the sidebar further.

Probably the same cause as @jamesmacwhite's issue but here's a screenshot of my scenario too, fwiw:

![image](https://github.com/craftcms/cms/assets/2892126/0fe2c50a-55a7-4126-a63f-9d243da493e4)

**Comment by brandonkelly** [comment]
Craft 3.9.3 and 4.5.5 are out with an additional fix that should solve these.

**Comment by KarlBishop** [comment]
The scrolling issue is fixed for me on 3.9.3!

But it looks like the version number didn't increment properly - my control panel still thinks it's on 3.9.2

**Comment by brandonkelly** [comment]
Whoops, sorry about that. 3.9.3 has been re-tagged with the updated version number 🤦🏻

**Comment by KarlBishop** [comment]
No probs, thanks for you work! 🙌

**Comment by jamesmacwhite** [comment]
Thanks for the quick release to fix this!

**Comment by chris78er** [comment]
See video of current scrolling behavior in Craft 4.5.5 (Google Chrome 117, macOS):

https://github.com/craftcms/cms/assets/49327719/56bdc8d1-e0d8-482b-a17c-e015632552e3

**Comment by brandonkelly** [comment]
@chris78er Yikes. Not able to reproduce that on my end. Is it happening at all window sizes?

**Comment by chris78er** [comment]
I have noticed that it only flickers during scrolling if the right column is longer than the content column:

<img width="1290" alt="Bildschirmfoto 2023-09-26 um 18 04 53" src="https://github.com/craftcms/cms/assets/49327719/26434773-2097-4cb8-a9ec-af2fd5373e44">

On a longer page, the entry type gets cut off and is hidden when scrolling down:

<img width="1282" alt="Bildschirmfoto 2023-09-26 um 18 16 19" src="https://github.com/craftcms/cms/assets/49327719/1b421e71-ec15-4a1e-aac5-c0e60bd6cc52">

Same in all browsers.

**Comment by brandonkelly** [comment]
Thanks, I found a way to reproduce. Fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 4.5.6 is out now with that fix.
