### ISSUE TITLE
[4.x]: <em> tag added to all error message {attribute} values

### ISSUE THREAD

**Issue by samhibberd** [craftcms/cms#13640]
### Description

The following PR (https://github.com/craftcms/cms/pull/12125) wraps the `{attribute}` part of all validation error messages with asterisks `*{attribute}*`, representing an `<em>` tag when parsed as markdown.

As I understand it this is an enhancement for the CP and the new error summary stuff.

It maybe just us, but this is not the correct behavior for the front end, where we would now need to include a markdown parser to handle / display any validation error messages that contain markdown.

Ideally messages for our front end would not be modified, not sure if this is configurable or might require a change or setting, but either way I have been unable to find docs or details on the change anywhere.

### Craft CMS version

4.5.3

### PHP version

8.2.*

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR to only emphasise error message attribute names in the Control Panel.

**Comment by samhibberd** [comment]
Fantastic, thanks @i-just.

**Comment by brandonkelly** [comment]
Craft 4.5.4 is out with that fix.
