### ISSUE TITLE
Wonky sidebar nav behavior

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/cms#1364]
### Description

When you are on a page where the sidebar height is greater than the main content height, the sidebar will become about 70 pixels too short when you first start scrolling down the page.

### Steps to reproduce

1. Go to /admin/utilities/find-replace
2. Make the window shorter until scrollbars appear
3. Scroll down a bit (less than 70 pixels)

You'll see the sidebar immediately jump to be 70 pixels too short:

<img width="342" src="https://cloud.githubusercontent.com/assets/47792/22759974/59d61fd0-ee09-11e6-8204-dc71ef89c5fa.png">

### Additional info

- Craft version: 3.0.0-beta.3

**Comment by brandonkelly** [comment]
This doesn’t appear to be completely resolved yet.

<img width="438" alt="screen shot 2017-05-03 at 9 43 38 am" src="https://cloud.githubusercontent.com/assets/47792/25671536/4474dad2-2fe5-11e7-9428-94747198d059.png">

**Comment by Chrisedmo** [comment]
Can also confirm that I have this issue (latest 3.0.0-beta.17 + Safari latest) when there are minimal fields on the right.

![screen shot 2017-05-17 at 11 58 43](https://cloud.githubusercontent.com/assets/255639/26150850/475ee36e-3af8-11e7-98af-5d4ea83f56db.png)
