### ISSUE TITLE
[4.x]: Delete For Site behavior for multi-site entries is inconsistent (hard-/soft-deletion)

### ISSUE THREAD

**Issue by michaelrog** [craftcms/cms#13645]
### What happened?

The _Delete For Site_ behavior appears to be inconsistent with respect to soft-/hard-deletion:
- If I delete an entry that is only enabled in one site, the entry is soft-deleted and appears in _Trashed_.
- If I delete a multi-site-enabled entry that is currently only active on one site, the entry is soft-deleted and appears in _Trashed_.
- **If I delete a multi-site-enabled entry that is currently active on multiple sites, the entry (for that site) is hard-deleted and cannot be restored.**

This behavior is confusing; It feels like a bug.

**As a content editor, I would *expect* that, if soft-deletes are enabled for entries, an entry I delete from a site should be recoverable from Trashed, no matter how many sites it's active in at the time of deletion.**

### Steps to reproduce

1. Accidentally Delete-For-Site an entry that is only enabled in one site. See that you can restore the entry from Trashed.
2. Accidentally Delete-For-Site an entry that is enabled in multiple sites. See that it's irrecoverably gone. Cry. 😢 

---

Craft CMS 4.5.3
PHP 8.1.20
MySQL 8.0

**Comment by michaelrog** [comment]
(Apologies, this should have been tagged `craft4`. Although I suspect the same issue affects `craft3`, too.) 😬

**Comment by i-just** [comment]
Hi, thanks for getting in touch! 

Deleting an entry for a site when that entry exists for other sites doesn’t go through the same delete mechanism as in other cases. When you delete a multi-site element for just one site, it still exists for the other sites. That’s why it behaves differently.

We'll discuss this one internally and I'll get back to you once I have an update.

**Comment by brandonkelly** [comment]
Yeah this is currently working as intended, and it would take some schema changes to make this possible. Going to close, but feel free to open up a discussion requesting soft deletion for site-specific entry content.
