### ISSUE TITLE
[3.x]: craft\helpers\Db::parseDateParam doesn't like DateTimeImmutable

### ISSUE THREAD

**Issue by msbit** [craftcms/cms#13656]
### What happened?

Consider the following:

```
>>> craft\helpers\Db::parseDateParam("column", new DateTimeImmutable());
=> [
     "column" => [
       "2023-09-07 02:52:10",
       "1970-01-01 00:00:03",
       "",
     ],
   ]
```

vs:

```
>>> craft\helpers\Db::parseDateParam("column", new DateTime());
=> [
     "column" => "2023-09-07 02:52:16",
   ]
```

This appears to be due to the following checks against `DateTime` specifically:

https://github.com/craftcms/cms/blob/3.9.1/src/helpers/Db.php#L1253
https://github.com/craftcms/cms/blob/3.9.1/src/helpers/DateTimeHelper.php#L87

https://github.com/craftcms/cms/blob/4.5.3/src/helpers/Db.php#L1586
https://github.com/craftcms/cms/blob/4.5.3/src/helpers/DateTimeHelper.php#L91

I haven't checked 4.x, but in 3.x changing these to check directly against `DateTimeInterface` gives me the correct result in the first example.

### Craft CMS version

3.8.9

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Just added support for `DateTimeImmutable` for the next Craft 4 release.

We’re generally no longer maintaining Craft 3, save for security fixes and some other bug fixes when it makes sense, at our discretion. In this case, the fix involves [`DateTime::createFromImmutable`](https://www.php.net/manual/en/datetime.createfromimmutable.php) which was added in PHP 7.3. So until you are ready to update to Craft 4, you will have to ensure you’re passing a `DateTime` instance into the param.
