### ISSUE TITLE
getSrcset missing fill option[4.x]: 

### ISSUE THREAD

**Issue by johannesSolvr** [craftcms/cms#13650]
### Description
When using letterbox and fill with getSrcset, the fill option is not used for transform.  the bug comes from the getUrlsBySize function in src/Elements/Asset.php where there is defined an array from the transform that is missing the fill key. Adding this key fixes the problem

$sizeTransform = $transform ? $transform->toArray([
                'format',
                'height',
                'interlace',
                'mode',
                'position',
                'quality',
                'width',
                **'fill'**
            ]) : [];

### Craft CMS version

4.5.3

### PHP version

8.0

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting and providing a solution! I raised a PR for it.

**Comment by brandonkelly** [comment]
Craft 4.5.4 is out with that fix. Thanks again!
