### ISSUE TITLE
[4.x]: Active Trials in Cart doesn't display plugins

### ISSUE THREAD

**Issue by DowleyDeveloped** [craftcms/cms#13661]
### Description

When going to purchase plugins within the store, the popup only shows Craft CMS and not the plugins. 

Can still add these individually through the plugin settings, but is a bit of a pain.

### Steps to reproduce

1. Go to plugin Store
2. Click on Cart Icon in top right
3. See Active Trials in Popup

<img width="897" alt="Screenshot 2023-09-07 at 09 14 23" src="https://github.com/craftcms/cms/assets/24968042/67ddc832-99a6-46e2-8952-4d27f86e6aee">

### Expected behavior

It should show all trials including plugins

### Actual behavior

Only displays Craft

### Craft CMS version

4.5.3

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR to adjust this.

**Comment by brandonkelly** [comment]
Craft 3.9.2 and 4.5.4 are out with a fix for this. Thanks again!
