### ISSUE TITLE
[4.x]: Infinite loop when overriding an element route to users/set-password

### ISSUE THREAD

**Issue by nstCactus** [craftcms/cms#13660]
### Description

I'm trying to make the set-password page editable in the CP, using an entry. 

### Steps to reproduce

1. in `config/general.php`, set the `setPasswordPath` property to the URL of the entry
2. add a `templates/setpassword.twig` file with the set-password form template
3. in a module, listen to the `\craft\base\Element::EVENT_SET_ROUTE` event to override the entry route, like so:
````php
Event::on(\craft\elements\Entry::class, \craft\base\Element::EVENT_SET_ROUTE, static function (\craft\events\SetElementRouteEvent $e) {
    /** @var craft\elements\Entry $entry */
    $entry = $e->sender;

    $setPasswordFormEntryId = 1234; // how I get the entry id isn't relevant
    if ($entry->id === $setPasswordFormEntry->id) {
        $e->route = 'users/set-password';
       $e->handled = true;
    }
});
````
4. request a password reset
5. click the set-password link in the mail
6. watch the browser loading indicator spin forever

### Expected behavior

The `\craft\controllers\UsersController::actionSetPassword()` method get called, does its thing and then renders the `templates/setpassword.twig` template.

### Actual behavior

The `\craft\controllers\UsersController::actionSetPassword()` method get called, does its thing and then enters an infinite loop when trying to determine which template should be rendered.

Here is a screenshot of the stacktrace showing the loop:
![image](https://github.com/craftcms/cms/assets/353843/86baf95b-99be-46f4-a637-873779539f0d)

### Additional info

- Yii version: 2.0.48.1

### Craft CMS version

4.5.3

### PHP version

8.2.8

### Operating system and version

ddev version v1.22.1 running on macOS 13.5

### Database type and version

MariaDB 10.2.44

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

| Plugin name | version |
| --- | ---: |
| Asset Usage | 3.2.0 |
| Color Extractor | 3.0.0 |
| Contact Form | 3.0.1 |
| Contact Form Extensions | 4.2.2 |
| Contact Form Honeypot | 2.0.0 |
| CP Field Inspect | 1.4.4 |
| Disk usage dashboard widget | 2.3.0 |
| Embedded Assets | 3.1.8 |
| Field Manager | 3.0.7 |
| Locale selector field | 1.0.0 |
| Mailchimp Transactional | 2.0.1 |
| Neo | 3.8.6 |
| Newsletter | 2.2.0 |
| Quick Field | 2.0.5 |
| Redactor | 3.0.4 |
| Retour | 4.1.13 |
| Sentry | 2.0.1 |
| SEO | 4.0.30 |
| Super Table | 3.0.9 |
| tarteaucitron.js | 3.0.1 |
| Twigpack | 4.0.0-beta.4 |
| Typed link field | 2.1.5 |

**Comment by brandonkelly** [comment]
Those requests are expected to get routed twice – the first time, `users/set-password` is supposed to set some variables on the routing params, and then re-route the request with those variables in place, and let the original template get routed instead, with those in place.

Your route is blocking the second route from getting applied correctly. You can fix that by only getting involved if a `variables` route param hasn’t been set yet:

```php
use Craft;
use craft\base\Element;
use craft\elements\Entry;
use craft\events\SetElementRouteEvent;
use yii\base\Event;

Event::on(Entry::class, Element::EVENT_SET_ROUTE, static function (SetElementRouteEvent $e) {
    // If we're coming from users/set-password, don't change anything
    if (isset(Craft::$app->urlManager->getRouteParams()['variables'])) {
        return;
    }
    
    /** @var Entry $entry */
    $entry = $e->sender;

    $setPasswordFormEntryId = 1234; // how I get the entry id isn't relevant
    if ($entry->id === $setPasswordFormEntry->id) {
        $e->route = 'users/set-password';
        $e->handled = true;
    }
});
```
