### ISSUE TITLE
[4.x]: project-config/rebuild wipes out custom condition rule in custom source

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#13679]
### Description

For our starter project https://github.com/wsydney76/craft4-ddev-starter, there is a custom condition rule https://github.com/wsydney76/craft4-ddev-starter/blob/main/modules/main/conditions/HasDraftsConditionRule.php, attached to a custom element index source, (showing all drafts, regular and provisional, created by the current author):

![image](https://github.com/craftcms/cms/assets/60010597/c9102af4-281a-4c3c-873a-e33a2977b31d)

Seems to work fine, but we got reports that this condition disappears once in a while.

Looks like it is reproducable by running `craft project-config/rebuild`, resulting in this compare from `project.yaml` :

![image](https://github.com/craftcms/cms/assets/60010597/971fb570-7752-45c9-b6bd-7d01d490cdc8)

(The code was obviously created back then without in-depth knowledge/docs, so something may be wrong. Should not result in such an error anyway.)

/Karla

### Steps to reproduce

1. Create a custom condition rule type and attach it to a custom element index source
2. or install our starter :-)
3. run `craft project-config/rebuild`

### Expected behavior

Nothing changes

### Actual behavior

The condition is gone.

### Craft CMS version

4.5.3

### PHP version

8.1.21

### Operating system and version

Linux 5.15.90.1-microsoft-standard-WSL2

### Database type and version

MariaDB 10.4.30

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- Code Field 4.0.10
- Contact Form 3.0.1
- Element Map 4.1.1 (custom)
- Seo Mate 2.1.2
- Sprig 2.6.2
- Vite 4.0.6

**Comment by wsydney76** [comment]
Ah, looks like this happens because the Condition Rule Type was only registered for CP requests.

Going to close (assuming this behavior is intentional...)

/Karla

**Comment by brandonkelly** [comment]
Yeah, you’d probably want to adjust that to include it for console requests as well.
