### ISSUE TITLE
[4.x]: setCacheHeaders is missing public directive on overwrite

### ISSUE THREAD

**Issue by roelvanhintum** [craftcms/cms#13676]
### Description
When using `Craft::$app->getResponse()->setCacheHeaders()` with overwrite, the public directive is missing. Non-overwrite does include `public, `
https://github.com/craftcms/cms/blob/f88ae66292189f780ddec3f31f906ef78795d603/src/web/Response.php#L128

### Steps to reproduce

1. Use `Craft::$app->getResponse()->setCacheHeaders()` (it defaults to 1 year and overwrite) Response has no `Cache-Control: public, `
3. Use `Craft::$app->getResponse()->setCacheHeaders(31536000, false)` Response has `Cache-Control: public, `

### Expected behavior

Responses with a max-age should look like `Cache-Control: public, max-age=31536000`

### Actual behavior

Responses look like `Cache-Control: max-age=31536000` unless `overwrite` is false on the `setCacheHeaders` method.

### Craft CMS version

4.5.3

### PHP version

8.1.23

### Operating system and version

Linux 5.15.49-linuxkit-pr

### Database type and version

MySQL 8.0.34

### Image driver and version

GD 8.1.23

### Installed plugins and versions

- Asset Usage 3.2.0
- Buckaroo for Craft Commerce 2.1.1
- Craft Commerce 4.2.11
- fortrabbit Object Storage Volume 3.0.0
- ImageOptimize 4.0.5
- Linkit 4.0.4.1
- Maps 4.0.4
- Redactor 3.0.4
- Sentry SDK 2.0.1
- SEOmatic 4.0.30
- Super Table 3.0.9
- Two-Factor Authentication 3.3.1
- Vite 4.0.6

**Comment by brandonkelly** [comment]
Thanks for pointing that out. We decided to remove `public` when `$overwrite` is `false`, rather than ensure it’s always included, as it was a change in behavior in 4.5, and could have unintended security implications.
