### ISSUE TITLE
[4.x]:  AdminTable pagination not work

### ISSUE THREAD

**Issue by aodihis** [craftcms/cms#13677]
### Description
I have a module that show the data using Admin Vue table with API mode, previously working fine but after I update to version 4.5 the pagination doesn't work anymore. The next and previous button not woking anymore.

I realize on the query params when we click the next button / previous button, it doesn't inculde the perPage. sort and page params anymore.

### Steps to reproduce

1. Create a page that using Admin vue table with API mode.
2. Click on next button

### Expected behavior

The next page will reload

### Actual behavior
Stack on page 1.

### Craft CMS version

4.5

### Installed plugins and versions

-

**Comment by aodihis** [comment]
btw If I put these event code, it will working fine.
```
onQueryParams: function(params) {
            return params;
        }
```

**Comment by brandonkelly** [comment]
Thanks for reporting that! We’ve fixed this for the next release, so specifying an `onQueryParams` callback won’t be necessary anymore.

**Comment by brandonkelly** [comment]
Craft 4.5.6 is out now with that change.
