### ISSUE TITLE
[4.x]: Folder icons disappeared in Assets Section - Safari 

### ISSUE THREAD

**Issue by thomasbendl** [craftcms/cms#13685]
### Description

Since I have updated to Craft CMS 4.5.3 no folder icons are displayed in the CP Assets section in Safari Browser.
Tested with Safari 16.6

### Quickfix
```
.elementthumb:not(:empty) svg {
  width:100%;
  .
  .
  .
  .
}
```

### Craft CMS version

4.5.3

### PHP version

8.0.28

### Operating system and version

Linux 5.15.49

### Database type and version

MariaDB 10.4.28

### Image driver and version

Imagick 3.7.0

### Installed plugins and versions

CKEditor | 3.5.1
SpaceControl  | 1.0.2
Vite | 4.0.6

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Craft 4.5.4 is out with a fix.
