### ISSUE TITLE
Access to a volume’s Flysystem API

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#1368]
### Description

Could you please change `craft\base\Volume::filesystem()` visibility to public, so plugins can easily use the Flysystem API.

https://github.com/craftcms/cms/blob/develop/src/base/Volume.php#L336

I would like to access it like so:

```PHP
$filesystem = $asset->getVolume()->filesystem();
```

**Comment by andris-sevcenko** [comment]
What would you be using that for that you can't use the Assets service for?

**Comment by carlcs** [comment]
Just using the nice API to access the stream, specifically for using it with `stream_copy_to_stream` to grab some bytes of an asset.

**Comment by andris-sevcenko** [comment]
This is going to be addressed. I'll close this when it's implemented.

**Comment by andris-sevcenko** [comment]
Added `craft\elements\Asset::getStream()` with 27691f9
