### ISSUE TITLE
[4.5.4]: Entries field on multisite project could not be saved in site 1 if it's made in site 2.

### ISSUE THREAD

**Issue by mazaalai** [craftcms/cms#13699]
### Description
I have multisite project and I wanted to link entry made in site 2 to entry field in site 1 but I am getting a error. My colleague has tested the same set up in Craft 3 it seems to work as intended. 

My propagation method is 'Let each entry choose which sites it should be saved to' and Section Type is 'Structure'.

### Steps to reproduce

1. Create a mutlisite project named site 1 and site 2.

2. Make a section with Section Type 'Structure' and Propagation Method 'Let each entry choose which sites it should be saved to'

3. Create a section only in site 1 and other one in site 2.

3. Make a field with Field Type 'Entries' and select Section that you made from last step

4. Select site 1 and make a new field from a field that you made from last step and select section that you made from site 2.

### Expected behavior

- Selecting a entry from site 2 in field in site 1. 

### Actual behavior

- Found 1 error
[Destination should contain at least 1 selection.]"
![image](https://github.com/craftcms/cms/assets/15675633/3adca092-22c6-4a99-a3ab-a475c2d3e1f3)

### Notes
Apologies if I'm missing something, if this is expected behavior, or if it's more of a feature request. Happy to provide additional details if needed.

### Craft CMS version

4.5.4 and 4.5.5

### PHP version

8.1.6

### Operating system and version

macOS Venture 13.4.1 

### Database type and version

MySQL 5.7.34

### Image driver and version

Imagick 3.5.1 (ImageMagick 6.9.6-2)

### Installed plugins and versions

- Controle Panel CSS - 2.6.0
- Control Panel Nav - 4.0.10
- Expanded Singles - 2.0.5
- Freeform - 4.1.7
- Neo - 3.8.6
- SEO - 4.2.1

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed now for the next release.

If you’d like to get the fix early, you can change your `craftcms/cms` requirement in composer.json to `"dev-develop#de84c2413dd766cc0808e610cfcf89e8ea5ca942 as 4.5.5"`, then run `composer update`.

**Comment by mazaalai** [comment]
Thanks for the fast fix. 

I have other problem now. When I select the entry from site 2 in the field from site 1, I can select it now. When I click on the entry field, I am sent to the entry related to site 2, but it's an entry in site 1.

Is it possible to send the user from the site 1 entry field to an entry made in site 2 ?

**Comment by brandonkelly** [comment]
> When I click on the entry field, I am sent to the entry related to site 2, but it's an entry in site 1.

What do you mean by “click on the entry field”?

Relations aren’t actually site-specific. The “Relate entries from a specific site” setting will set the selector modal to use the chosen site, in case there are entries in there  which aren’t available in the current site. And it will cause the field’s entry queries to default to the selected site in your templates. But the relations themselves don’t actually keep track of which site the element was selected in.

**Comment by brandonkelly** [comment]
Craft 4.5.6 is out now with that initial fix.

**Comment by mazaalai** [comment]
Thank you 👍
