### ISSUE TITLE
[4.5.4]: Dropdown field menu items cannot have empty values

### ISSUE THREAD

**Issue by croxton** [craftcms/cms#13695]
### Description
Given a dropdown menu field where the first menu item has been assigned an empty value, it is no longer possible to select that item with the empty value after a another menu item has been chosen and the entry saved. As soon as you click anywhere on the screen the value reverts to the previous selected value. 

### Steps to reproduce

1. Create a Dropdown field called 'Aspect ratio' with label : values as follows:

None :
1:1 : 100%
4:3 : 75%
16:9 : 56.25%
21:9 : 42.86%

Note that the value for 'None' is left empty and set as the default for the field. 

2. Add the field to a section. The field is not set to be mandatory.

3. Create a new entry in the section that uses the field and select a value such as '4:3'. Save the entry.

4. Return to the entry and select 'None'. If you click anywhere on the page the 'None' changes back to '4:3', making it impossible to change the value to 'None'.

5. A workaround is to use the ⌘+S keyboard shortcut to save the entry immediately after changing the select value. Then the value of the select menu is blank (not 'None', just blank).

### Expected behavior

It should be possible to select 'None' without it reverting to the previous value.

### Craft CMS version

4.5.4

### PHP version

8.2

### Operating system and version

Mac

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 4.5.5 is out with a fix.
