### ISSUE TITLE
[4.x, 3.x]: Craft 4.5.5 claiming to be 4.5.4, 3.9.3 claiming to be 3.9.2

### ISSUE THREAD

**Issue by ttempleton** [craftcms/cms#13697]
### Description

After updating to Craft 4.5.5, the control panel footer shows Craft CMS 4.5.4, and the updates section shows that version 4.5.5 is available.

### Steps to reproduce

1. Craft 4.x install prior to 4.5.5
2. composer update to 4.5.5

### Expected behavior

Not to see an available update to the currently installed version.

### Actual behavior

Seeing an available update to the currently installed version.

### Craft CMS version

4.5.5

### PHP version

8.1

### Installed plugins and versions

-

**Comment by evanwarner** [comment]
Can confirm, `/src/config/app.php` still says `'version' => '4.5.4',`

**Comment by ttempleton** [comment]
Similarly Craft 3.9.3 is showing 3.9.2.

**Comment by brandonkelly** [comment]
Whoops, sorry about that. 3.9.3 and 4.5.5 have been re-tagged with the updated version numbers 🤦🏻
