### ISSUE TITLE
[4.x]: Slideout of Filesystems cannot be dismissed and prompts to save changes

### ISSUE THREAD

**Issue by engram-design** [craftcms/cms#13707]
### Description
There's two issues here with editing a volume and the filesystem related to it, and both are about the slide-out functionality. It's probably going to affect other things that use the slide-out too (I initially was trying to solve this for [Hyper](https://github.com/verbb/hyper) which uses the slide-out to edit fields).

Firstly, when you go to create a new filesystem, and make no changes, it prompts you with the usual unload warning like you _have_ made a change, but you haven't. It probably shouldn't show this unless you've made a change?

https://share.cleanshot.com/8rjFY9qJ

Secondly, I can't seem to actually dismiss the slide-out anymore. After clicking the Cancel/Okay button on the browser unload prompt, I then try to click anywhere else on the page, and it just re-opens the slide-out.

https://share.cleanshot.com/zGWksssv

### Craft CMS version

4.5.5

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR to adjust this.

**Comment by engram-design** [comment]
Thanks as always!

**Comment by brandonkelly** [comment]
Craft 4.5.6 is out now with that fix.
