### ISSUE TITLE
Plugin Store

### ISSUE THREAD

**Issue by robinbeatty** [craftcms/cms#13701]
### What happened?

When making an upgrade purchase from the plugin store in control panel (e.g. from lite -> pro edition), the cart shows the price difference as a discount. If the auto-renew lightswitch is changed, the discount is removed (don't think this should happen) and doesn't return even when auto-renew is returned to its previous state. 

### Craft CMS version

4.5.5

### PHP version

8.1.11

**Comment by timkelty** [comment]
Thanks for the report! I'll look into this today and get back to you.

**Comment by brandonkelly** [comment]
Going to close this since it’s not actually a Craft CMS issue – it’s a Console bug. (Toggling auto-renew within the in-app Plugin Store cart is retaining the upgrade discount as expected.)

We’ll still update this issue once it’s fixed on Console though.
