### ISSUE TITLE
[4.x]: Division by zero

### ISSUE THREAD

**Issue by kringkaste** [craftcms/cms#13712]
### Description

If you have an image with a very small and a very large side at the same time (like 1x200px), the `Image::calculateMissingDimension()` creates a targetWidth of 0 and then the `Raster::scaleAndCrop()` generates a Division by Zero on line 330 (Craft 4.4.17). The `round()` function in `Image::calculateMissingDimension()` produces a 0 and it should always return a minimum of 1.

### Steps to reproduce

1. Upload an image of 1x200px or something like that to a folder and the thumbnail generation produces the error.

### Expected behavior

A thumbnail of the image or a fall back image.

### Actual behavior

Division by zero.

### Craft CMS version

4.4.17

### PHP version

8.1

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR to adjust this.

**Comment by brandonkelly** [comment]
Fixed for the next release via #13719.
