### ISSUE TITLE
[4.x]: opcache reported as not enabled — when it is ON?!

### ISSUE THREAD

**Issue by MattAppleton** [craftcms/cms#13711]
### Description

Installing a new Craft 4 site...

### Steps to reproduce

1. Site installed, pushed to remote server
2. remote install reports a new warning in the system report

`The [OPcache](https://php.net/manual/en/book.opcache.php) extension is recommended in production environments.`

### Expected behavior

No Opcache warning!

### Actual behavior

We get a warning about opcache!

Opcache is definitely switched on — I checked our LInode / Serverpilot setup
opcache.ini is set to

```
zend_extension=opcache.so
opcache.memory_consumption=128
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=4000
opcache.revalidate_freq=0
opcache.validate_permission=1
opcache.huge_code_pages=1
```

  (tried this on local install via MAMP also, same inconsistency)

### Craft CMS version

4.5.5

### PHP version

8.2

### Operating system and version

Mac OSX 13.5.2

### Database type and version

MySQL 8.0.34

### Image driver and version

GD 8.2.0

### Installed plugins and versions

-

Amazon S3	2.0.3
Redactor	3.0.4
Remote Backup	4.1.3
Remote Sync	4.1.1

**Comment by angrybrad** [comment]
This is fixed in https://github.com/craftcms/server-check/pull/25 and will be included in the next release (likely tomorrow).
