### ISSUE TITLE
[4.x]: Long entry titles included in `.element.small` do not wrap, cause visual and AX issues

### ISSUE THREAD

**Issue by gbowne-quickbase** [craftcms/cms#13718]
### Description
We have a long entry title contained within a supertable block and it floats behind the last column of the entry. Users can't get to the [x] to remove the entry. This was fixed for another situation in https://github.com/craftcms/cms/issues/13382 but this one remains.

### Steps to reproduce

1. Create a table or supertable with several columns and put an entry in the last one. We're using `presseddigital/linkit` for our links
2. Pick a really long title for your entry
3. See it go off the edge of the table

### Expected behavior
The entry title would wrap within the space

### Actual behavior
The entry title goes behind other content on the page
![image](https://github.com/craftcms/cms/assets/39066452/603994d7-68b8-4792-983a-6555a82be779)

### What we found
If we add `text: wrap` to the span contained in the label, it fixes itself. This seems to be in the `_main.scss` file but we added it in the inspector and it seemed to fix the problem. This is the parent element in the control panel css file:  https://github.com/craftcms/cms/blob/72122c099e702529756d2f0a3bc5a582d632cd90/src/web/assets/cp/src/css/_main.scss#L3383
![image](https://github.com/craftcms/cms/assets/39066452/a446db2d-2eea-48d0-a9be-4a41dd44137e)
![image](https://github.com/craftcms/cms/assets/39066452/419c7778-bee5-4b60-9425-16e86c918d76)

### Craft CMS version

4.5.3

### PHP version

8.2.8

### Operating system and version

MacOs 13.5.1 (developers) and Centos Linux 7 (staging/production)

### Database type and version

MySQL 5.7

### Installed plugins and versions

- Linkit 4.0.4.1
- Supertable 3.0.9

**Comment by brandonkelly** [comment]
Fixed for the next release via #13722.

**Comment by brandonkelly** [comment]
Craft 4.5.6 is out now with that fix.
