### ISSUE TITLE
[4.x]: ./craft index-assets/all --delete-missing-assets removes all asset-entries from db

### ISSUE THREAD

**Issue by stefanfriedrich** [craftcms/cms#13726]
### Description

When you run ./craft index-assets/all --delete-missing-assets all assets are removed from the database.

### Steps to reproduce

1. upload an asset in the cp
2. run ./craft index-assets/all --delete-missing-assets
3. file will be removed:
One recorded asset is missing its file:
- images/test.jpg (9085570)
Deleting the missing asset record ... done

### Expected behavior

Only db-entries for assets that are not in the filesystem should be removed.

### Actual behavior

All db-entries for assets that are removed.

### Craft CMS version

4.5.5

### PHP version

8.1

### Installed plugins and versions

-

**Comment by stefanfriedrich** [comment]
works in craft 3.

**Comment by i-just** [comment]
Hi, thanks for reaching out. Could you let me know what filesystem(s) you use (e.g. local, Amazon S3, Azure Blob Storage, etc.)?

**Comment by stefanfriedrich** [comment]
Local

Iwona Just ***@***.***> schrieb am Fr. 22. Sept. 2023 um
16:02:

**Comment by stefanfriedrich** [comment]
No, only via cli.

Iwona Just ***@***.***> schrieb am Fr. 22. Sept. 2023 um
17:14:

**Comment by stefanfriedrich** [comment]
Was fixed on dot all by Luke. (@webroot was missing, worked ob Craft 3 without it)

**Comment by davidhellmann** [comment]
@stefanfriedrich missing as alias? or where? 😅

**Comment by stefanfriedrich** [comment]
@davidhellmann missing in the config (general.php) and in the asset path.

Fun fact: worked in craft 3 and works in craft 4 in the cp without it.

**Comment by davidhellmann** [comment]
Thanks! Yep my webrootpath in the `.env` was set to `./` I think that's a leftover from playing with DDEV.
