### ISSUE TITLE
[4.x]: changing entry type of a section does not update input layout

### ISSUE THREAD

**Issue by HigumaSan4050** [craftcms/cms#13747]
### Description
changing entry type of a section does not update input fields for the selected entry type.
neither in the main-content view nor in the slideout view

### Steps to reproduce

1. create a section with multiple entry types. each entry type should have an individual field layout.
2. when creating a new entry or edit an existing entry in this section and switching the entry type the field layout only updates, when you use ctrl + s

### Expected behavior
layout should change, when the user is changing the entry type. but should not save.

### Craft CMS version

4.5.5

### PHP version

8,2

**Comment by i-just** [comment]
Hi, thanks for getting in touch. 
Do you, by any chance, have [`autosaveDrafts`](https://craftcms.com/docs/4.x/config/general.html#autosavedrafts) set to `false`?

**Comment by HigumaSan4050** [comment]
Setting "autsaveDrafts" was set to false. 
Thanks for the hint.
