### ISSUE TITLE
Can't access/upload assets with entry Assets field

### ISSUE THREAD

**Issue by marjorg** [craftcms/cms#1374]
### Description
When I click to add a file through the Assets field in an entry, the pop up shows up without any of the previously uploaded assets and the "Upload file" button is missing. If I try to drag and drop an image it just opens fullscreen in the browser tab.

Adding assets through the Assets menu works fine. I can not see any errors in the console.

[Popup](http://i.imgur.com/w7dO9sJ.png)
[Assets menu](http://i.imgur.com/sZo9Uum.png)

**EDIT: After some further testing I figured out that unchecking "Restrict uploads to a single folder?" in the field settings fixes the issue.**

### Steps to reproduce

1. Create a section with a Asset field type
2. Go to assets and upload a file
3. Go to entry and try to upload a file or select previously uploaded file

### Additional info

- Craft version: Craft CMS 3.0.0-beta.3
- PHP version: 7.0.13
- Database driver & version:
- Plugins & versions: None
- Run on localhost with MAMP 4.1 (5367)

**Comment by andris-sevcenko** [comment]
@marjorg by any chance does this happen only for Assets fields with a Single Upload Folder setting set?

**Comment by marjorg** [comment]
@andris-sevcenko As far as I can see, yes.
