### ISSUE TITLE
[4.5.5]: Excluding entries from query by their IDs

### ISSUE THREAD

**Issue by DenyEs** [craftcms/cms#13748]
### Description
I have a following entry query which outputs 7 entries.

{% set ourProducts = craft.entries.section('pages').type('product').level(1) %}

If I change it to the following query below, I am still getting 7 entries back.

{% set excludedIds = [1677, 1679] %}
{% set ourProducts = craft.entries.section('pages').type('product').level(1).id('not ' ~ excludedIds|join(', not ')) %}

However if I only pass it a sigle ID in an array as per below, I will get 6 entries.

{% set excludedIds = [1677] %}

### Steps to reproduce

1. Create an array of IDs to exclude
2. Write an entry query that would exclude previsouly defined entries by their IDs in an array
3. Check the amount of entries you're receiving back

### Expected behavior
Entries should get exluded from entry query and I should get back 5 entries instead of 7.

### Actual behavior
Nothing got exluded and I am still getting all results.

### Craft CMS version

4.5.5

### PHP version

8.2.8

### Operating system and version

macOS Ventura 13.5.2

### Database type and version

MySQL 8.0.33

**Comment by i-just** [comment]
Hi, thanks for getting in touch. 

You need to specify that you want to join all those “nots” with an “and”. In other words, the query you want, in plain text, is: `and, not 1677, not 1679`.

`craft.entries.section('pages').type('product').level(1).id('and, not ' ~ excludedIds|join(', not '))`

A bit more info on this can be found, e.g. here: https://craftcms.stackexchange.com/questions/1758/what-is-the-best-way-to-exclude-an-array-of-entries

I hope this helps!

**Comment by brandonkelly** [comment]
You can also specify an array that begins with `'not'`, followed by all of the IDs to exclude:

```twig

{% set excludedIds = [1677, 1679] %}
{% set ourProducts = craft.entries()
  .section('pages')
  .type('product')
  .level(1)
  .id(['not']|merge(excludedIds))
  .all()
%}
```


There’s an example of this in the docs [here](https://craftcms.com/docs/4.x/entries.html#id).

**Comment by DenyEs** [comment]
I have no clue how I missed that! My bad, thank you guys.
