### ISSUE TITLE
[4.5.6]: Wrong site loaded when 'Relate entries from a specific site?' is enabled

### ISSUE THREAD

**Issue by tommysvr** [craftcms/cms#13750]
### Description
With 'Relate entries from a specific site?' enabled on an Entries field, the entries from the wrong site are displayed when the modal is first opened. Closing and re-opening the modal then loads the expected site.

### Steps to reproduce

1. Create an Entries field with 'Relate entries from a specific site?' enabled, with Site B as the site selected to relate from
2. On any entry, click 'Add an entry'; entries from Site A will be displayed in the modal
4. Close the modal, reclick 'Add an entry'
5. Entries from Site B will be displayed

### Expected behavior
Entries from the selected site to relate from are displayed each time

### Actual behavior
The very first time the modal loads, the wrong entries are displayed. This happens each time the entry is saved.

https://github.com/craftcms/cms/assets/867566/1f0280a8-f026-47a6-9188-2da7da7ae8c6

### Craft CMS version

4.5.6

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
I’m not able to reproduce this on my end. The modal is consistently showing entries in the chosen site. Are you seeing this on a fresh install?

**Comment by brandonkelly** [comment]
Nevermind, worked it out with @i-just. We are seeing the opposite of what you described though: the modals are showing the correct site initially, but not on subsequent opens. That’s now fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.5.7 is out now with that fix.
