### ISSUE TITLE
[4.x]: Bootstrap doesn't respect defaultDirMode

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#13756]
### Description

Craft bootstrap always uses chmod 0755, even when defaultDirMode is set to something else.

### Steps to reproduce

1. Set `defaultDirMode` to `0777` for example
2. Start Craft
3. Folders like `storage/runtime` are still created with `0755`

### Expected behavior

I expect these folders to be created with chmod 0777

### Actual behavior

They are always created with 0755

See https://github.com/craftcms/cms/blob/develop/bootstrap/bootstrap.php#L32-L39 where this happens.

### Craft CMS version

3 and 4

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next v3 and v4 releases.

**Comment by brandonkelly** [comment]
Craft 3.9.5 and 4.5.7 are out with a fix for this!
