### ISSUE TITLE
[3.x/4.x]: craft\web\Request::accepts() doesn't deal with wildcards

### ISSUE THREAD

**Issue by msbit** [craftcms/cms#13759]
### What happened?

When submitting a request with the header:

```
Accept: */*
```

`craft\web\Request::accepts('application/json')` will return `false` as it's explicitly checking for the existence of `application/json`.

From my understanding of the [header][1], it should return `true`, as it should for `application/*` (and `*/*`, trivially 😀).

This is the case both on [Craft 3][2] and [Craft 4][3].

Reproduction:

```
$request = new \craft\web\Request();
$request->setAcceptableContentTypes($request->parseAcceptHeader('*/*'));
var_dump($request->accepts('application/json'));
var_dump($request->accepts('application/*'));
var_dump($request->accepts('*/*'));
```

outputs:

```
bool(false)
bool(false)
bool(true)
```

[1]: https://www.rfc-editor.org/rfc/rfc9110#name-accept
[2]: https://github.com/craftcms/cms/blob/3.9.4/src/web/Request.php#L1288
[3]: https://github.com/craftcms/cms/blob/4.5.6.1/src/web/Request.php#L1289

### Craft CMS version

3.8.9

**Comment by brandonkelly** [comment]
This is resolved for the next Craft 4 release, via #13802.

Supporting `*/*` seems a little dangerous, as we currently check `accepts('application/json')` when determining whether we should send JSON responses back, and I’m worried we’d start getting some false positives with `*/*`.

**Comment by msbit** [comment]
@brandonkelly yep, that check (`Request::getAcceptsJson`) is what brought be to this issue.

> I’m worried we’d start getting some false positives with */*

Unfortunately I'd say that's likely, though it depends on how "false" you'd rate those positives; if a user agent specifically says they will `Accept` anything (`*/*`) I'd say it's on them.

Perhaps the call-sites need work then, or a change in the stated intent (`getAcceptsJson` -> `getAcceptsStrictlyJson` ?) along with `getAcceptsImage` (to `getAcceptsAnyImage` ?).

**Comment by brandonkelly** [comment]
Craft 4.5.7 is out with that change.



> Perhaps the call-sites need work then, or a change in the stated intent (`getAcceptsJson` -> `getAcceptsStrictlyJson` ?) along with `getAcceptsImage` (to `getAcceptsAnyImage` ?).

Maybe that would be more semantic, but would be a pretty big breaking change too, and `getAcceptsJson()` was originally added as a more semantic/reliable replacement for `getIsAjax()` (which relies on a nonstandard `X-Requested-With: XMLHttpRequest` header).

I’d be more inclined to add a new `getAcceptsAny()` method you could call in addition to `getAcceptsJson()` etc. Feel free to post a new discussion for that, if you feel there’s a need for it.
