### ISSUE TITLE
[4.x]: GraphQL schema changed, causing SEOmatic query issue

### ISSUE THREAD

**Issue by joshuabaker** [craftcms/cms#13758]
### Description

At some point [between 4.5.3 and 4.5.6.1](https://github.com/craftcms/cms/compare/4.5.3...4.5.6.1) the SEOmatic GraphQL piggyback became unavailable on the `ElementInterface` type.

### Expected behavior

Previously we could share a single fragment between all element types.

```gql
fragment seo on ElementInterface {
  seomatic(asArray: true) {
    metaTitleContainer
    metaTagContainer
    metaLinkContainer
    metaScriptContainer
    metaJsonLdContainer
    metaSiteVarsContainer
  }
}
```

### Extra Context

Initially reported on the SEOmatic repo: nystudio107/craft-seomatic#1360

### Craft CMS version

4.5.6.1

### SEOmatic version

4.0.31

**Comment by i-just** [comment]
Hi, thanks for getting in touch!

I tested this against `4.4.17`, `4.5.2`, `4.5.3`, `4.5.4` and `4.5.6.1`, and in all cases, it behaves consistently. 

In all those versions, it works as expected when the `devMode` is set to `false`, and it throws an error (`Cannot query field \"seomatic\" on type \"ElementInterface\". Did you mean to use an inline fragment on...`) if the `devMode` is `true`.

Do you have a broader example that works with a seomatic fragment on `4.4.17` but doesn’t on `4.5.6.1` (with the same `devMode` setting for both)?

**Comment by joshuabaker** [comment]
@i-just Why would this behave differently when toggling `devMode`? That in itself sounds like a bug.

**Comment by i-just** [comment]
@joshuabaker I’m not saying it’s not, but let’s focus on what you initially reported. Can you please help me replicate the issue you started having after updating from 4.5.3 to 4.5.6.1?

Once we’re clear on that, we can move on to a different issue, which is toggling `devMode`.

**Comment by joshuabaker** [comment]
Clearing the GraphQL cache appears to have resolved this issue. I now cannot replicate the issue so assume that something was cached incorrectly.

We can adjust our update process to ensure that we always clear caches on `composer install`.

Unclear why that would’ve been an issue as there doesn’t appear to be commits impacting any of this (between the versions noted). Likewise, a difference between `devMode` being on or off seems wrong, but could be explained by cache differences.
