### ISSUE TITLE
[4.x]: Uncaught TypeError: Craft.MatrixInput is not a constructor and similar

### ISSUE THREAD

**Issue by superflausch** [craftcms/cms#13752]
### Description
Recently (my guess is since the Update from 4.5.3) we get JS errors on different fields as soon as they are added to an newly created entry (doesn't seem to affect existing entries). Those field are nested in a NEO field, maybe this is NEO specific.

Here are some examples:

```
VM4487:376 Uncaught TypeError: Craft.MatrixInput is not a constructor
    at <anonymous>:376:19
    at m (jquery.js?v=1695796812:2:867)
    at Pe (jquery.js?v=1695796812:2:48869)
    at w.fn.init.append (jquery.js?v=1695796812:2:50073)
    at s.constructor.initUi (Block.js:342:18)
    at s.constructor.addBlock (Input.js:314:11)
    at e (Input.js:1110:12)
    at Input.js:1149:9
```

```
VM4506:60 Uncaught ReferenceError: CKEditor5 is not defined
    at <anonymous>:60:3
    at <anonymous>:61:3
    at m (jquery.js?v=1695796812:2:867)
    at Pe (jquery.js?v=1695796812:2:48869)
    at w.fn.init.append (jquery.js?v=1695796812:2:50073)
    at s.constructor.initUi (Block.js:342:18)
    at s.constructor.addBlock (Input.js:314:11)
    at e (Input.js:1110:12)
    at Input.js:1149:9
```

The errors prevent some fields to work properly. After saving the entry, it can be edited without an issue and without those errors. 

This happens on multiple sites which share a similar setup with a NEO field running CraftCMS >4.5.3. I just installed the latest update 4.5.6 which does not resolve this. I noticed some similar issues with similar errors posted here, which should be resolved with this update ([#13715](https://github.com/craftcms/cms/issues/13715)). Not this one.

### Steps to reproduce

1. Create a new entry (which uses this field setup)
2. Add a new or multiple blocks
3. Console throws those errors, some field don't work properly

### Expected behavior

No errors, fields work properly

### Actual behavior

Mentioned errors, some fields won't work properly (missing icons, missing modals)

### Craft CMS version

4.5.6

### PHP version

8.2.10

### Operating system and version

Misc (ex. Linux 3.10.0-1160.92.1.el7.x86_64)

### Database type and version

MariaDB 10.6.14

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-54)

### Installed plugins and versions

AsyncQueue	3.1.0
Button Box	4.2.0
CKEditor	3.6.0
Control Panel CSS	2.6.0
Element Relations	2.0.2
Field Manager	3.0.7
Formie	2.0.37
GeoMate	2.1.1
Imager X	4.2.3
Maps	4.0.4
Minify	4.0.0-beta.2
Neo	3.9.2
No-Cache	3.0.0
PathTools	4.0.0-beta.1
Patrol	5.0.2
Redirects	4.1.13
Retcon	2.7.3
SEO	4.0.31
Vite	4.0.6

**Comment by brandonkelly** [comment]
Thanks for reporting! We looked into it and it’s actually a [Neo bug](https://github.com/spicywebau/craft-neo/issues/790), introduced in Neo 3.9.0. Followed up on that issue with some findings.

**Comment by superflausch** [comment]
Thanks for looking into this @brandonkelly. I will follow up there.
