### ISSUE TITLE
[4.x]: Update to CraftCMS 4.5.6 Breaks "Bulk Edit" Plugin

### ISSUE THREAD

**Issue by adrianjean** [craftcms/cms#13751]
### What happened?

After installing CraftCMS update 4.5.6, the Bulk Edit Plugin stopped working. Selecting some entries and choosing to bulk edit seems to initiate a process, but the modal window with configuration never appears.

I tested this on two sites I upgraded to CrafCMS 4.5.6

I tried seeing if the logs record anything but for some reason don't show any errors.

CraftCMS: 4.5.6
Bulk Edit: 4.0.1
PHP:  8.2.10
MySQL: 5.7.8

### Craft CMS version

4.5.6

### PHP version

8.2.10

### Operating system and version

MacOS 14.0 / Chrome 117.0.5938.92 / Safari

### Database type and version

MySQL: 5.7.8

### Installed plugins and versions

Bulk Edit: 4.0.1

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 4.5.6.1 is out with a fix.
