### ISSUE TITLE
[5.0.0-alpha]: Using a native title field in a matrix field triggers error

### ISSUE THREAD

**Issue by ishetnogferre** [craftcms/cms#13766]
### Description
We tried a matrix with an entry type "Text" and added the native title field. This field is required. When filled in on an entry using the matrix field, the title field gets cleared and the generic "Title cannot be blank." error is shown.

### Steps to reproduce

1. Create an entry type e.g. "Text"
2. Add the native title field (required)
3. Create a matrix field and add the Text entry type
4. Make a Entry Type e.g. "Page" and add the matrix field
5. Create a Page entry 
6. Add a "Text" via the matrix field and fill in the title field 
7. Save either via the button or Ctrl + S

### Expected behavior
The title to be saved

### Actual behavior
The title field get's cleared and the corresponding error is shown.

### Craft CMS version

5.0.0-alpha

### PHP version

8.2

### Operating system and version

MacOS Ventura

### Database type and version

MySQL 5.7.41

### Image driver and version

Imagick 3.7.0

### Installed plugins and versions

- Just the developer preview of Craft 5

<img width="833" alt="Screenshot 2023-10-03 at 11 08 46" src="https://github.com/craftcms/cms/assets/6649706/ac1da003-30bd-4b97-9a52-dee4d5f4172e">
_note: I re-added the "test" value after the error showed_

**Comment by brandonkelly** [comment]
Fixed via #13775!
