### ISSUE TITLE
[4.x]: changedfields table becomes very large when resaving entries

### ISSUE THREAD

**Issue by dgsiegel** [craftcms/cms#13761]
### Description

We've got a quite large section called `object` (with an entry type called `object` as well) that currently has about 25k entries. All of the entries in this section are imported and updated via a FeedMe import. As we ran into performance issues with Craft's native search we were trying to make less fields available to the search index. So we reduced the number of searchable fields and ran

`craft resave/entries --update-search-index --section object --limit 10000` (The limit of 10.000 was just a test, we are planning to run the same command for all entries).

Before calling this command we ran this SQL query to get the sizes of all tables to compare before and after.

```
> SELECT
    table_name as "Table",
    table_rows as "Rows",
    data_length as "Length",
    index_length as "Index",
    round(((data_length + index_length) / 1024 / 1024),2) as "Size (mb)"
FROM information_schema.TABLES
WHERE table_schema = '%%NAME OF YOUR CRAFT DB%%'
ORDER BY `Size (mb)` DESC;
+----------------------------+--------+-----------+----------+-----------+
| Table                      | Rows   | Length    | Index    | Size (mb) |
+----------------------------+--------+-----------+----------+-----------+
| searchindex                | 714985 | 103481344 | 37339136 |    134.30 |
| content                    | 122278 |  80330752 | 12140544 |     88.19 |
| changedfields              | 278828 |  12075008 | 27328512 |     37.58 |
| elements_sites             | 130086 |  14172160 | 18432000 |     31.09 |
| elements                   |  64341 |   7880704 | 19038208 |     25.67 |
[...]
```

After the command finished, we ran the query again:

```
> SELECT
    table_name as "Table",
    table_rows as "Rows",
    data_length as "Length",
    index_length as "Index",
    round(((data_length + index_length) / 1024 / 1024),2) as "Size (mb)"
FROM information_schema.TABLES
WHERE table_schema = '%%NAME OF YOUR CRAFT DB%%'
ORDER BY `Size (mb)` DESC;
+----------------------------+--------+-----------+----------+-----------+
| Table                      | Rows   | Length    | Index    | Size (mb) |
+----------------------------+--------+-----------+----------+-----------+
| searchindex                | 438577 | 103464960 | 37257216 |    134.20 |
| changedfields              | 534244 |  38354944 | 62029824 |     95.73 |
| content                    | 122278 |  80330752 | 12140544 |     88.19 |
| elements_sites             | 130086 |  14172160 | 18432000 |     31.09 |
| elements                   |  64341 |   7880704 | 19038208 |     25.67 |
[...]
```

As you can see, the `changedfields` table grew with a factor of 2.5x. If we had resaved all of the entries in this section we would easily have come up with a table of over 200mb in size.

Now we were interested to see what fields are saved in the `changedfields` table:

```
> SELECT COUNT(*) as num_search_entry, f.handle
FROM changedfields c, fields f
WHERE c.fieldId = f.id
GROUP BY f.handle
ORDER BY num_search_entry DESC;
+------------------+-----------------------------+
| num_search_entry | handle                      |
+------------------+-----------------------------+
|            37552 | objectImages                |
|            23916 | objectInventory             |
|            23916 | objectId                    |
|            23915 | objectArtist                |
|            23622 | objectRelation              |
|            23622 | objectLiterature            |
|            23622 | objectOnDisplay             |
|            23622 | objectDateStart             |
|            23622 | objectDateEnd               |
|            20599 | objectDescription           |
|            20597 | objectDate                  |
|            20597 | objectLocality              |
|            20597 | objectDimensions            |
|            20597 | objectAcquisition           |
|            20597 | objectMaterial              |
|            20597 | objectLocation              |
|            20308 | objectProvenance            |
|            20303 | objectPlacement             |
|            20303 | objectTerm                  |
|             1645 | linkField                   |
|             1579 | description                 |
[...]
```

As you can see, all of those fields are used for this entry type. `linkField` and `description` are two fields used for other sections/entry types.

We couldn't find much information about what the `changedfields` table actually does and whether it is safe to truncate it.

Any help is appreciated.

### Craft CMS version

4.5.6.1

### PHP version

8.0/8.2

### Database type and version

MariaDB

### Installed plugins and versions

- FeedMe

**Comment by i-just** [comment]
Hi, thanks for getting in touch!

`changedfields` is used to track which fields have been modified - in the Control Panel, that powers that blue line that indicates a modified field; it also serves as a basic audit trail; examples:
- if you go to an entry and change a field value - a provisional draft is created, the field you just changed is added to the changedfields table with the draft’s `elementId`
- if you were to discard that draft - the row added to the `changedfields` table will be deleted
- if you were to apply that draft (save entry) - the row would start referencing the canonical element id, not the draft id and it will stay in that table

That being said, we probably shouldn’t be updating the `changedfields` table when resaving, so I raised a PR to change this.

There’s no way to clear that table outside of manually truncating it; however, that can have negative repercussions, so it’s not advised.

**Comment by brandonkelly** [comment]
Craft 4.5.7 is out now with the fix for this.

**Comment by dgsiegel** [comment]
Thanks @i-just & @brandonkelly. How would we go about removing existing entries that certainly don't have a draft/changes that we need, for example entries imported via FeedMe?

**Comment by brandonkelly** [comment]
Unfortunately there’s no clean solution to that. You could truncate the table, but that will cause drafts to get a little wonky.

I would recommend just leaving it alone. The table size isn’t going to cause any issues besides taking up extra space on disk.

**Comment by dgsiegel** [comment]
> Unfortunately there’s no clean solution to that. You could truncate the table, but that will cause drafts to get a little wonky.

Right, this is something we'd like to avoid.

> I would recommend just leaving it alone. The table size isn’t going to cause any issues besides taking up extra space on disk.

As you've seen, this table is already half the size of our db, hence we'd really like to get rid of useless information stored in the db. In our case we know that all fields starting with `object` (e.g. `objectImages`) will be imported by FeedMe. Would it be safe to execute something like the following query which only deletes those fields?

```
DELETE changedfields
FROM changedfields
JOIN fields ON changedfields.fieldId = fields.id
WHERE fields.handle LIKE "object%";
```

Or is there a way to remove all current drafts? We could certainly notify all editors to save their work before doing something like this.

**Comment by brandonkelly** [comment]
Both of those approaches would be fine.
