### ISSUE TITLE
Provide User Permissions for Entries by User Group

### ISSUE THREAD

**Issue by mattcdavis1** [craftcms/cms#1376]
### Description
For example, take an organization that has about 100 chapters.  Each chapter needs to have it's own channel blog, news, events etc.  It would be a real pain to create separate channels for each chapter and for the super admin there wouldn't be a way to see all entries of one type (blog, news) together.  One way of accomplishing this would be via the multi-site functionality.  Each chapter could be treated as a site and share the same channel but access could be limited based on site. 

The problem with this approach is that the UI for multisite doesn't seem well suited for large numbers of sites.

Ideally, there would be a permission similar to "Edit other authors’ drafts" except it would be "Edit other authors’ drafts in same user group" and then the existing permission would change to "Edit other authors’ drafts in all user groups"

Optionally, if this isn't implemented it would be helpful to add adequate events for developers to handle this themselves. Currently, the only event i see in ElementsIndexController is in the actionPerformAction method but that doesn't seem to fire on an /admin/actions/element-indexes/get-elements request (which returns channel listing data).

**Comment by brandonkelly** [comment]
I don’t think this should be a core feature, because it’s pretty niche, adds UI complexity, and is something that could be done with a plugin.
