### ISSUE TITLE
[4.x]: Money field breaks Save and Continue on users

### ISSUE THREAD

**Issue by CharlieGentle** [craftcms/cms#13760]
### What happened?

When there is a Money field visible in a user profile, it breaks the Save and Continue functionality. Clicking on the arrow next to save just saves instantly and takes you back to the index. Cmd + S also saves but takes you back to the index.

### Steps to reproduce

1. Create a money field
2. Add the money field to a user profile.
3. Go to the user and try to Save and Continue.

### Expected behavior
- Clicking on the save dropdown should show the dropdown
- Cmd + S should Save and Continue

### Actual behavior
- Clicking on the arrow next to save just saves instantly and takes you back to the index.
- Cmd + S also saves but takes you back to the index.

### Craft CMS version

4.5.5

### PHP version

8.0.28

### Operating system and version

Linux 5.10.104-linuxkit

### Database type and version

MariaDB 10.4.28

**Comment by CharlieGentle** [comment]
The CMD + S issue is happening on one site which has more complex fields with Money fields inside a Super Table. On a test site with just a money field, CMD + S is working ok but the save dropdown is still broken.

**Comment by i-just** [comment]
Hi, thanks for reporting and for all the details! I can see what's happening, and I'm working on a solution.

**Comment by brandonkelly** [comment]
Craft 4.5.7 is out now with a fix for this. Thanks again for reporting!
