### ISSUE TITLE
[4.x]: Static translations of site content in CP apply according to CP language instead of site language

### ISSUE THREAD

**Issue by FoxtrotCZ** [craftcms/cms#13763]
### Description
This issue originates from this discussion https://github.com/craftcms/cms/discussions/13703
and applied improvement https://github.com/craftcms/cms/commit/9f4bf6e59f3f8cd7a1c791c60d9959bed4c84c1b

Before this Static Row Headings were not translated in CP. Now they are but target language is decided by CP language instead of site language.

Because Static Row Headings are content defined by Default Values I would expect it to be the same language as content of the site I am editing. It should not depend on language of CP.

For example if you use CP in English and want to edit site/entry in other language you want Static Row Headings to be displayed in the other language, not English.

### Steps to reproduce

Lets say you are Czech site author with primary site language in Czech but you still use English in CP because all guides and support is in English and you prefer English.

1. Create 2 sites. Each different language, for example Czech (primary) and English.
2. Have CP set to English.
3. Create Table field with Static Row Headings in Czech language. Field should be set as translatable.
4. Use this field in some entry and output Row Headings in frontend.
5. Create translations/en/site.php file and translate Static Row Headings from Czech to English. Dont forget to add translation filter to Twig template |t('site').
6. Check frontend and backend. In frontend you should see Czech table headings for Czech site and English ones for English site. In backend CP you should see only English headings for both Czech and English sites.

### Expected behavior
I would expect that content translation depends on language of the site. So for Czech site I would see Czech headings as set during Field creation and for English site translated headings as defined in translations/en/site.php

### Actual behavior
But the static translation instead depends on CP language. So if you use English CP you will see English translation for both sites and if you switch to Czech you will see only Czech.

### Craft CMS version

4.5.6.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
This doesn’t seem right to me. Every other control panel UI message is translated based on the user’s language, not the content language.

**Comment by FoxtrotCZ** [comment]
@brandonkelly 
Thanks, for answer. Let me specify it better to make sure we dont misunderstand each other.
I made example site where CP is in English and site content is translated from English to Czech.

Original English content. First is regular table, second is table with predefined row headings. Looks good, all is in English as it should be.
![image](https://github.com/craftcms/cms/assets/10333810/2731195f-e692-49e1-811b-417c94b3b9af)

Frontend English output, looks good.
![image](https://github.com/craftcms/cms/assets/10333810/50329ecb-797b-4571-b83f-5c80b8d6c53f)

Now lets look at translated content.
First, this is my site.php file which manages translation of Table Row Headings from English to Czech.
![image](https://github.com/craftcms/cms/assets/10333810/ac22a7ae-eca1-416b-9b72-d83d70dbc7c0)

Now look at backend of Czech translated page. This looks bad. While my regular table is manually translated in content editor, my table with row headings still has original English words. I hoped site.php will translate it to Czech but it doesnt.
![image](https://github.com/craftcms/cms/assets/10333810/7f1b22fb-136b-4b5b-a761-878cc8456c8d)

And Czech frontend. This is good, row headings from second table are translated by site.php into Czech language.
![image](https://github.com/craftcms/cms/assets/10333810/658e465a-4efa-4bbb-afb8-bc1064393858)

Can you now see that is doesnt work is it should?
I need to use table with predefined row headings (because many entries repeat the same headings), but this table is not translated by site.php in backend.
The result is that backend content doesnt match frontend which is wrong.

Thanks.

**Comment by brandonkelly** [comment]
Yeah I’m following you. In your second example, `heading`, `value`, `length`, `width`, and `height` are each considered UI messages, not content – because they are part of the UI, not author-editable fields. So, like all other UI messages, they will be translated according to the logged-in user’s preferred language, not the content language.

**Comment by FoxtrotCZ** [comment]
Ok, thanks for clarification.
So I will either use it this way or try to find some workaround.

If you can maybe in the future find some solution, that would be great.

But thanks for answer.
