### ISSUE TITLE
[5.0.0-alpha] Double clicking an element doesn't always select it 

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#13770]
### Description
When selecting an asset or an entry from the element select modal, the behaviour when you double -click is different from Craft 4. Double clicking checks & unchecks the selection but doesn't confirm the selection. Clicking it multiple times sometimes works but not consistently. 

I've attached a screenrecording below:

https://github.com/craftcms/cms/assets/755428/e500b97b-1ebb-4518-8745-e0b854585dd3

### Expected behavior
When double clicking a single entry I expected it to confirm my selection, close the modal and take me back to my entry.

### Craft CMS version

5.0.0-alpha

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Fixed now :)
