### ISSUE TITLE
[5.0.0-alpha]: on the fly entry type fieldlayout: dragging the title outside a tab removes field from list

### ISSUE THREAD

**Issue by jripmeester** [craftcms/cms#13776]
### Description
When your creating a entry type "on the fly" (while creating a section or matrix field) and you start editting the fieldlayout in the slide-over screen. Dragging the title outside of a tab removes the field from the field list on the right.

### Steps to reproduce

i've uploaded a video to show the behaviour. With some scenarios.

https://github.com/craftcms/cms/assets/432051/4b25960c-2c87-4fa1-8fa6-80aab90a23af

### Expected behavior
You expect the title field to move back to the list on the right like the rest of the fields.

### Craft CMS version

5.0.0-alpha

### PHP version

8.2

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Fixed via #13826!
