### ISSUE TITLE
[5.0.0-alpha]: Cannot save matrix entries that have URL enabled

### ISSUE THREAD

**Issue by mattbloomfield** [craftcms/cms#13771]
### Description

When trying to save an entry that has a matrix field and the field has URLs enabled, you get an error saying `slug cannot be blank`

### Steps to reproduce

1. Create a matrix field
2. Add a path for the URL
3. Add the matrix field to an entry type
4. Add the entry type to a section
5. Create a new entry in that section
6. Add a block to the matrix
7. Save

### Expected behavior

It would save. I am curious how I would know the slugs for the matrix blocks after save. 

### Actual behavior

It gives the error: 

<img width="810" alt="image" src="https://github.com/craftcms/cms/assets/37582550/61b22b58-7c65-492b-bd82-a3715234135f">

### Craft CMS version

Craft Solo 5.0.0-alpha

### PHP version

8.2.10

### Operating system and version

MacOS Sonoma 14.0

### Database type and version

ddev standard

### Image driver and version

ddev standard

### Installed plugins and versions

- NONE

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
This is fixed now! Thanks again.
