### ISSUE TITLE
[5.0.0-alpha]: When adding a title field, its automatically required 

### ISSUE THREAD

**Issue by michtio** [craftcms/cms#13773]
### Description

Even tho we aren't required to add a title field to the entry types, when using the native title field - it's automatically required without any option to make it "optional".

It would be clean if you can add the title field to the entry type, with the ability to make it required/not-required rather than creating a specific field for it.

### Steps to reproduce

1. Drag and drop the title field onto the entry type
2. The title field is available, and is by default required.
3. There exists no option to make it not-required

### Expected behavior

Make sure the title field, even when it's in the entry type, can also be made non-required.

### Craft CMS version

5.0.0-alpha

### PHP version

8.2

**Comment by brandonkelly** [comment]
What’s the use case? It seems like if you’re going to include titles, there shouldn’t be a middle ground.

**Comment by michtio** [comment]
Actually related to @13766 @brandonkelly 

Not an issue anymore
