### ISSUE TITLE
checkboxSelect doesn't display the first item in the array

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#1378]
### Description

`templates/_includes/forms/checkboxSelect.html` has the following line of code in it that causes the first element in the checkbox array to never display:

```
        {% if not showAllOption or optionValue != allValue %}
```

Interestingly, if you do `{{ 0 != '*' }}` that evaluates to nothing (false) somehow. That's what causes it to fail, the first time through the loop, `optionValue` is `0` and `allValue` is `*`

Some weirdness in Twig 2.x...?

**Comment by khalwat** [comment]
This evaluates to nothing (false) on Twig 1.x too. Which makes me wonder how it ever worked. Which makes me think I'm doing something wrong...

**Comment by khalwat** [comment]
Aha: http://stackoverflow.com/questions/6843030/why-does-php-consider-0-to-be-equal-to-a-string

**Comment by michaelrog** [comment]
Yup, tricky stuff. That conditional probably needs to be `0 same as '*'` (the Twig equivalent of `0 !== '*'`).

(Technically, I think `'*' != 0` would work — because the right-hand is type-cast based on the type of the left-hand — but the identity comparison is definitely the 'more correct' way to go.)

**Comment by khalwat** [comment]
This is tested, and works:

```
        {% if not showAllOption or not optionValue is same as(allValue) %}
```

**Comment by brandonkelly** [comment]
@khalwat Can you provide some template code that illustrates the issue? I'm not able to reproduce with this:

```twig
{% extends "_layouts/cp" %}
{% set title = "Form Tests" %}
{% import "_includes/forms" as forms %}

{% block content %}
    {{ forms.checkboxSelect({
        options: [
            { value: 'one', label: 'One' },
            { value: 'two', label: 'Two' },
            { value: 'three', label: 'Three' },
        ]
    }) }}
{% endblock %}
```

**Comment by brandonkelly** [comment]
Nevermind, was able to reproduce with this:

```twig
{% extends "_layouts/cp" %}
{% set title = "Form Tests" %}
{% import "_includes/forms" as forms %}

{% block content %}
    {{ forms.checkboxSelect({
        options: [
            { value: 0, label: 'Zero' },
            { value: 1, label: 'One' },
            { value: 2, label: 'Two' },
        ]
    }) }}
{% endblock %}
```

Option values are supposed to be strings, so in this case I’d say the bug is in this test template, not the macro. But still, I’ll update Craft to guard against this by casting the value to a string before the `optionValue != allValue` condition.
