### ISSUE TITLE
[5.0.0-alpha]: Reduced performance saving entries compared to Craft 4

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#13791]
### Description

I started doing some benchmarks comparing Craft 4 to Craft 5 and came across particularly poor performance when programmatically saving entries.

<img width="1169" alt="image" src="https://github.com/craftcms/cms/assets/3810939/b014ab29-1d10-4be6-a3cb-527cc6390f50">

### Steps to reproduce

I created two basic fresh Craft sites in DDEV with these properties:

1. MySQL 8
2. PHP 8.2
3. Single plugin installed: CKEditor
4. Add plain text field, CKEditor field, and Dropdown field
5. Create section called "Articles" and corresponding entry type with previously created fields
6. Run script to create 200 entries with identical content on Craft 4 and Craft 5. Fill all fields with valid values.

Code I used for benchmarking: https://gist.github.com/Mosnar/357f6184a00363b7e7a4b6a506b0bb4f

### Craft CMS version

5.0.0-alpha

### PHP version

8.2

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Culprit ended up being 9cd4b280931fd542a04af573c3d38d5b24ca490f, which is now semi-reverted to avoid the performance hit when not necessary.

Also spotted an easy win for improving element save performance in Craft 4 (c1e4a33176abe56187965a230ebf544fac0c409c), which brought your test down from 14.5s to 9.76s.

**Comment by Mosnar** [comment]
Confirmed, much faster! Awesome work tracking that down!
