### ISSUE TITLE
[4.x]: Odd caching behavior, cache is persisting in browser

### ISSUE THREAD

**Issue by jannisborgers** [craftcms/cms#13804]
### Description
On the homepage of the affected site, we have a list of featured news posts coming from an entries field in the homepage single. We cache the results inside the loop like so:

```twig
{% for newsEntry in news %}
  {# Datetime for debugging #}
  {{ now|datetime() }}
  {% cache using key newsEntry.slug ~ now|date("short") ~ 'homepageTeaser' %}
    {# Datetime for debugging #}
    {{ now|datetime() }}
    {# newspost content… #}
  {% endcache %}
{% endfor %}
```

I can’t pinpoint the source of the caching behavior I’m seeing here:

When I change entries in that field, the result is shown as expected. Changing it back to the original selection, the browser still shows the old content. 

Clearing the cache and invalidating the template cache does not affect the situation directly. 

A hard-refresh of the browser tab (CMD+SHIFT+R in Firefox), or opening the dev tools while loading the page, shows the correct content. A follow-up normal refresh of the tab (without dev tools) sometimes reverts back to the outdated content, and sometimes shows the updated content.

When I view the source of the page, the correct news entries show. The DOM shows old content.

Relevant response headers read as follows (we don’t set headers explicitly in the templates):

```
cache-control: no-store, no-cache, must-revalidate
expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
```

Using Browserstack for further testing, the page shows outdated content as well, mirroring the behavior described above. So it’s not restricted to my browser and could have something to do with the server or Craft.

Maybe someone can point me in the right direction?

### Steps to reproduce

1. Would gladly share access to the installation if needed.

### Expected behavior

The template above always shows the correct content, at least when emptying and invalidating the cache.

### Actual behavior

Shows outdated content and can only be resolved when clearing and invalidating the cache and clearing the browser cache as well.

### Craft CMS version

4.5.5

### PHP version

8.1.24

### Operating system and version

AlmaLinux 8.8 (Sapphire Caracal)

### Database type and version

MySQL 8.1.24

### Installed plugins and versions

Contact Form 3.0.1
Contact Form Extensions 4.2.2
Contact Form Honeypot 2.0.0
Dumper 3.0.1
Element API 3.0.1.1
HOMM XML Sitemap 1.0.3
Redactor 3.0.4
Vite 4.0.6

**Comment by brandonkelly** [comment]
Is this happening locally or on production? If on production, is the site behind Cloudflare or any other proxies that could be serving cached responses?

**Comment by jannisborgers** [comment]
Hi @brandonkelly – this is happening in production. It's a simple setup, so my first guess is no. But I'll check with the client's IT to find out if the site is proxied.

**Comment by brandonkelly** [comment]
Are you able to reproduce the behavior on the same site locally?

**Comment by jannisborgers** [comment]
I checked again and no, the problem only occurs on the production server. Locally, I make sure that template caching is active, change the entries selection and reload the browser: it works as expected. So I can verify that.

One thing I did notice is that caching using `now` as part of the key isn’t useful. I changed that to use `entry.dateUpdated`. I also made sure to expand the `cache` tag to include the whole loop:

```twig
{% cache using key entry.dateUpdated|datetime() ~ 'newsHomepageTeaser' %}
  {% for newsEntry in news|slice(1) %}
    {# … #}
  {% endfor %}
{% endcache %}
```

Still the news entries only update correctly when I empty the browser cache by doing a hard-refresh. Otherwise, it’s either the old or the new, totally chaotic.

I asked about potential proxying or caching on the server side and am waiting for a response. I’ll answer here once I have more info.

**Comment by jannisborgers** [comment]
Hi @brandonkelly — in lieu of a response from the client’s IT, I have brought a fresh SQL backup from the live site to our own staging environment to replicate the problem. Our staging server is a Hetzner VPS and deployed via Laravel Forge, while the client’s webserver is shared hosting and I can only access it via SFTP.

I cannot reproduce the problem at all on a proper server. Everything works as expected, mirroring what I see locally.

I’ll advise the client to switch to a VPS to get rid of the problem. This isn’t the first time that the webserver has caused problems for this site, so I guess all other solutions would be way to complicated and unreliable.

**Comment by brandonkelly** [comment]
Thanks for testing that @jannisborgers!
