### ISSUE TITLE
[4.x]: Issue on dropdown in Matrix field

### ISSUE THREAD

**Issue by andrelopez** [craftcms/cms#13817]
### Description
When adding a dropdown inside a matrix field if I add a long text on the label it will overflow

### Steps to reproduce

1. Create a matrix field
2. add a dropdown
3. add a long label
4. add the field to an entry

### Actual behavior
<img width="2199" alt="Screenshot 2023-10-11 at 8 15 38 pm" src="https://github.com/craftcms/cms/assets/875476/e6f4b3de-c056-4db5-9ddb-664b93f71931">

### Craft CMS version

4.5.6.1

### PHP version

8.1.22

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR to adjust this.

**Comment by brandonkelly** [comment]
Fixed via #13818!

**Comment by brandonkelly** [comment]
Craft 4.5.7 is out now with the fix for this. Thanks again for reporting!
