### ISSUE TITLE
[4.x]: Entry URI Format  does not respect the original site URI

### ISSUE THREAD

**Issue by jan-dh** [craftcms/cms#13812]
### Description
When using a dynamic Entry URI Format like so: `{{ craft.entries.section('pages').type('blog').one().uri }}/{slug}` in a multi-site setup the logic does not respect the site relation.

### Steps to reproduce

1. Create a multi-site env. with a blog channel in both sites
2. Create section pages (which is a structure)

### Expected behavior

I would expect the following
Site A: 
- entry with page type blog in pages structure has uri: `blog`
- blog entries start with `blog/{slug}`

Site B:
- entry with page type blog pages structure has uri: `blabla`
- blog entries start with `blabla/{slug}`

### Actual behavior
Site A: 
- entry with page type blog in pages structure has uri: `blog`
- blog entries start with `blog/{slug}`

Site B:
- entry with page type blog pages structure has uri: `blabla`
- blog entries start with `blog/{slug}`

Resaving entries in the multiple channels/structures doesn't seem to do anything (both from CMS as CLI); caches cleared as well; moving the entry within the pages structure with the type blog around to trigger a resave also doesn't work.

### Craft CMS version

4.5.6.1

### PHP version

8.1

### Operating system and version

MacOS 13

### Database type and version

MariaDB 10.3

**Comment by jan-dh** [comment]
Passing the `{{currentSite.id}}` also doesn't work, 

`{{ craft.entries.section('pages').type('blog').siteId(currentSite.id).one().uri }}/{slug}`

Only explicitly setting the siteId seems to work

`{{ craft.entries.section('pages').type('blog').siteId(4).one().uri }}/{slug}`

**Comment by brandonkelly** [comment]
Thanks for reporting that! This is fixed for the next release via #13816.

**Comment by i-just** [comment]
@jan-dh one thing to add is that once the fix is released, you’ll need to add the `.siteId(siteId)` to the uri format, so it looks like this: `{{ craft.entries.section('section1').type('blog').siteId(siteId).one().uri }}/{slug}`

**Comment by jan-dh** [comment]
Okido, maybe best to update the docs to mention this somewhere because this used to work without the explicit set. Any reason for this? I would assume queries are run on the same site by default?

**Comment by jan-dh** [comment]
@i-just this is not really a fix right? If you still need to explicit define the current site?

**Comment by brandonkelly** [comment]
When was it working for you? The only change since 1.0 I can think of that would have affected this is how we sometimes perform cross-site validation in 4.5, but if anything that would have made the behavior _better_, not worse (because URIs are set on elements via a validation rule). Before that, we simply never ran validation on elements when propagating them.

**Comment by jan-dh** [comment]
Hmm nvm, must've been they shared the same URI and I thought this was just working. Any reason why you explicitly need to pass the siteId?

**Comment by jan-dh** [comment]
Clear, thanks for the info!

**Comment by brandonkelly** [comment]
Craft 4.5.7 is out now with the fix for this. Thanks again for reporting!
