### ISSUE TITLE
[4.x]: enabledForSite seems broken

### ISSUE THREAD

**Issue by jan-dh** [craftcms/cms#13811]
### Description
I have a multi-site setup; 8 different sites. A blog channel with the propagation method set to: `Let each entry choose which sites it should be saved to`.  I have a test entry that I enabled for all other sites. 

Outputting this:

{{entry.enabledForSite(2)}}
{{entry.enabledForSite(3)}}
{{entry.enabledForSite(4)}}
{{entry.enabledForSite(5)}}
{{entry.enabledForSite(6)}}
{{entry.enabledForSite(7)}}
{{entry.enabledForSite(8)}}
{{entry.enabledForSite(9)}}

only returns 1 for the actual site I'm on.

### Expected behavior

This should return 1 for every site

### Actual behavior

only returns 1 for the actual site I'm on.

### Craft CMS version

4.5.6.1

### PHP version

8.1

### Operating system and version

MacOS 13.0.1

### Database type and version

mariadb 10.3

**Comment by i-just** [comment]
Hi, thanks for getting in touch!

`getEnabledForSite()` returns whether the element is enabled for the current site.

I’m guessing you need a way to check on which sites the current entry is enabled for? You can do that with, e.g. `entry.localized().all()`, which will return an array containing the same entry in other locales.

There’s also `entry.getSupportedSites()`, which will return an array of all sites supported by the current entry (element), but it won’t take into consideration whether the entry is enabled on each of the returned sites.

I hope this helps. I’m going to close this now, but please don’t hesitate to get in touch if you run into any more problems.
