### ISSUE TITLE
[4.x]: CP list multi-select toggle behaviour when right clicking link

### ISSUE THREAD

**Issue by robinbeatty** [craftcms/cms#13823]
### What happened?

Only a very minor one: When in a cp elements list view, (e.g. in my case assets) it's often useful to right click the item's link icon (blue globe) to 'copy link address'. However this triggers the multi-select toggle, which doesn't seem like it should be the correct behaviour. Does it need a preventDefault on the globe icon (or pointerevents:none etc on the item row on globe hover etc)? 

### Craft CMS version

4.5.5

### PHP version

8.0

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! I was able to reproduce when Ctrl-clicking in Edge and Safari (but not Firefox). Fixed now for the next release.

**Comment by brandonkelly** [comment]
Craft 4.5.7 is out now with the fix for this. Thanks again for reporting!
