### ISSUE TITLE
Make it possible to eager-load structure elements' ancestors and siblings

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/cms#1382]
It’s possible to eager-load structure elements’ descendants and children, so we should add ancestors and siblings to the mix.

`ElementInterface::getAncestors()` and `getChildren()` are already set up with `@return` types that account for the results possibly being an array of `ElementInterface` objects.

**Comment by scottwakefield** [comment]
Hi @brandonkelly,

I've run into the need to eager-load ancestors today on a Craft 2 project. Is this likely to be introduced at some point? 🤞

**Comment by brandonkelly** [comment]
@scottwakefield Almost certainly not for Craft 2 at this point.

**Comment by scottwakefield** [comment]
Thanks for the reply @brandonkelly – I knew it was a long shot! 👍

**Comment by billythekid** [comment]
Will this be coming soon? Noticed eager loading 'ancestors' gives me an empty array still?

**Comment by brandonkelly** [comment]
I’ll put it on the 3.4 list and see if we can get to it for that, though can’t promise anything.

**Comment by Friksel** [comment]
+1 for eager loading these. If available would have used eager loading for the previous and next page on a structure 'page'. Seems like a situation happening a lot with page navigation, so would be nice!

**Comment by brandonkelly** [comment]
Just added support for passing `ancestors` and `parent` to `with()`.

Eager-loading elements’ siblings would be just about as expensive as loading their parents with their children (e.g. `with('parent.children')`, so I’m going to skip `siblings` support for now.
