### ISSUE TITLE
[4.x]: Hidden Entries causing slugs to increment

### ISSUE THREAD

**Issue by adrianjean** [craftcms/cms#13829]
### Description
When creating a new entry whose slug would match the first part of another entry's slug (that isn't identical), the new entry slug is incorrectly incremented.

**Example:**
- Existing Entry Slug:   `dinosaur-valley-excavation`
- New Entry Slug:  `dinosaur-valley`

Right now, instead of saving the New Entry with that slug, CraftCMS counts the existing entry as a duplicate (false positive) because the first part of it matches the new slug's entry, and then increments the slug. So we end up with:

`dinosaur-valley-1`

... as the slug for the New Entry when we should simply have had:

`dinosaur-valley`

... as the New Entry's slug.

### Steps to reproduce

1. Create an entry with a hyphenated slug of multiple words.
2. Create a second entry with a hyphenated slug with at least the two first words of the previous entry.
3. Note that CraftCMS increments the slug of the new entry thinking the second entry is a duplicate of the first.

### Expected behavior

CraftCMS shouldn't incrementing the slug of entries whose slugs only partially match others.

### Craft CMS version

Craft Pro 4.5.6.1

### PHP version

8.2.11

### Operating system and version

Linux 5.15.0-86-generic

### Database type and version

MySQL 8.0.30

### Image driver and version

GD 8.2.11

### Installed plugins and versions

-

**Comment by adrianjean** [comment]
.... Ok — seems it's only an issue for a few entries on **my** specific install. It's as if there are some "ghost" entries in the system that are matching new entries causing the slugs to be incremented.

Is the incremented number saved somewhere in CraftCMS? 

Is it possible that there are some hidden entries floating around in the system that I can't see that are preventing me from having these slugs increment?

**Comment by brandonkelly** [comment]
Slugs are only incremented in service of finding a unique _URI_ for the element/site.

So if your URI format is `foo/{slug}`, and you have an existing element with the URI `foo/bar`, and you create an entry with the slug `bar`, Craft will see that `foo/bar` is already taken, and increment the slug until it can find a unique URI (e.g. `bar-1` → `foo/bar-1`).

**Comment by adrianjean** [comment]
Is there a way to list all the slugs / URIs in the system? 
I can't seem to find any entry that would cause these new entries to be incremented.

**Comment by adrianjean** [comment]
Ok! Right great idea. That helped me find the "other" entry. Thank you!!
I used craft cli to delete it based on the ID.

I did notice a handful more entries like this. Two entries exist but only one is visible. 
Any thoughts on why this is happening or how to make them visible? (I know... sort of impossible without seeing it)

**Comment by brandonkelly** [comment]
Theoretically the entries were created intentionally by an author?

**Comment by adrianjean** [comment]
They were.... but I also have FeedMe content coming in as well, tho these entries were not FeedMe entries. I'll keep an eye on it. 

I've never seen this behaviour in all the CraftCMS sites I've built so I think it's a one off.
I think we can close this issue since your solution to find the entries helps.

Thanks again!!

**Comment by adrianjean** [comment]
Hmm... I spoke too soon. 

I found more of these hidden entries and realized they were actually categories that were converted using the `entrify/categories` feature.

**Comment by adrianjean** [comment]
Ok I have a bit of an update on this finally.
I compared two entries. One that is visible, and one that is not, which is causing the incremented slug. 
Here are the differences:

```
Hidden Entry:
Url: newsletter
ID: 25413
Type:
Title: Newsletter
Site: English
Status: enabled
```
```
Visible Entry:
Url: newsletter-2
ID: 136238
Type: page
Title: Newsletter
Site: English
Status: live
```

You'l notice the `type` is blank and the `status` is "enabled" on the hidden entry. 
I don't know how the first entry was created, but it's not visible in the CP.
I am using your suggested method to find these one by one, but it's really strange.

**Comment by adrianjean** [comment]
Scratch that — looks like the "Hidden" element is actually a Campaigns Plugin: Mailing List.

**Comment by brandonkelly** [comment]
Ah so not entries to begin with. That explains the lack of author and `enabled` status (which entries should never return).

**Comment by adrianjean** [comment]
Yup exactly. 
Strange thing is the original problem was on a site that didn't have the Campaigns plugins installed but I haven't seen the issue surface again, nor on any other sites, so I chalk it up to oddness.
