### ISSUE TITLE
[4.x]: Craft Support desktop widget wonkiness

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#13835]
If you click the “send to Developer Support” link that’s visible from the initial Craft Stack Exchange and Github feedback links, the titles for Stack Exchange and Github still appear at the top, giving you the confusing impression that what you’re about to do will end up at either Stack Exchange or Github, when it's emailing support.

![CleanShot 2023-10-16 at 15 04 44](https://github.com/craftcms/cms/assets/61869/269cd7de-e30c-497f-a2d0-5767dc857f5d)

![CleanShot 2023-10-16 at 15 07 19](https://github.com/craftcms/cms/assets/61869/70f7249d-855f-4bdd-98e0-4315e96053e5)

![CleanShot 2023-10-16 at 15 08 30](https://github.com/craftcms/cms/assets/61869/437fa2c8-116c-42a7-bc93-77b8d8bc69a0)

Not an issue on Craft 3.

### Craft CMS version

4.5

### PHP version

n/a

### Operating system and version

n/a

### Database type and version

n/a

### Image driver and version

n/a

### Installed plugins and versions

None

**Comment by i-just** [comment]
Thanks Brad! PR raised.

**Comment by brandonkelly** [comment]
Fixed via #13838
