### ISSUE TITLE
Support for caching `registerMetaTag`

### ISSUE THREAD

**Issue by olivierbon** [craftcms/cms#13832]
### Description

Caching for  `registerMetaTag` ([docs](https://www.yiiframework.com/doc/api/2.0/yii-web-view#registerMetaTag()-detail)) isn't supported.

### Steps to reproduce

Add the below to a template. The tag will print on first load but disappear on subsequent refresh.

```
{% cache %}
    {% do view.registerMetaTag({'name': 'title', 'content': 'metaContent'}) %}
{% endcache %}
```

### Craft CMS version

^4.0.0

### Installed plugins and versions

-

**Comment by i-just** [comment]
Thanks for helping me replicate it Oli! PR raised.

**Comment by brandonkelly** [comment]
Craft 4.5.8 is out now with support for `registerMetaTag()` + `{% cache %}` (via #13845) :tada:
