### ISSUE TITLE
[4.x]: Foreign Key Constraints and Tests with MySQL 8 not working correctly

### ISSUE THREAD

**Issue by benediktblank** [craftcms/cms#13849]
### Description
I've migrated from MySQL 5.7 to 8.0.

All went well at first but then I noticed my Unit Tests failing. They are being run on a separate Test DB that is being filled and emptied by Craft and Codeception.

When it runs the cleanseDb function in vendor/craftcms/cms/src/test/TestSetup.php to clean the Test DB it fails when dropping certain tables. It fails with foreign key constraints.

I noticed that it happened, for example, on the "drafts" table.
There were still foreign key constraints with the "elements" table. They were supposed to be dropped via the dropAllForeignKeysToTable function in vendor/craftcms/cms/src/helpers/Db.php.
But for the elements table, it was only deleting 2 out of 4 foreign keys. The other two were not "found" anymore.

The reason for it being the findConstraints function in vendor/craftcms/cms/src/db/mysql/Schema.php.
It runs the query:
```
SELECT
    `kcu`.`CONSTRAINT_NAME` AS `constraint_name`,
    `kcu`.`COLUMN_NAME` AS `column_name`,
    `kcu`.`REFERENCED_TABLE_NAME` AS `referenced_table_name`,
    `kcu`.`REFERENCED_COLUMN_NAME` AS `referenced_column_name`,
    `rc`.`DELETE_RULE`,
    `rc`.`UPDATE_RULE`
FROM `information_schema`.`REFERENTIAL_CONSTRAINTS` AS `rc`
JOIN `information_schema`.`KEY_COLUMN_USAGE` AS `kcu` ON
    (
        `kcu`.`CONSTRAINT_CATALOG` = `rc`.`CONSTRAINT_CATALOG` OR
        (`kcu`.`CONSTRAINT_CATALOG` IS NULL AND `rc`.`CONSTRAINT_CATALOG` IS NULL)
    ) AND
    `kcu`.`CONSTRAINT_SCHEMA` = `rc`.`CONSTRAINT_SCHEMA` AND
    `kcu`.`CONSTRAINT_NAME` = `rc`.`CONSTRAINT_NAME`
WHERE `rc`.`CONSTRAINT_SCHEMA` = database() AND `kcu`.`TABLE_SCHEMA` = database()
AND `rc`.`TABLE_NAME` = :tableName AND `kcu`.`TABLE_NAME` = :tableName1
```
And for "elements" it only returns 2 foreign keys not all 4. The "drafts" one is missing but still present.
The reason being that the constraint is present in `information_schema`.`REFERENTIAL_CONSTRAINTS` but not in `information_schema`.`KEY_COLUMN_USAGE`.

The thing is, these foreign keys are created fresh on the Test DB via the addForeignKeys function in vendor/craftcms/cms/src/migrations/Install.php right before the tests are created.
```
$this->addForeignKey(null, Table::ELEMENTS, ['canonicalId'], Table::ELEMENTS, ['id'], 'SET NULL');
$this->addForeignKey(null, Table::ELEMENTS, ['draftId'], Table::DRAFTS, ['id'], 'CASCADE', null);
$this->addForeignKey(null, Table::ELEMENTS, ['revisionId'], Table::REVISIONS, ['id'], 'CASCADE', null);
$this->addForeignKey(null, Table::ELEMENTS, ['fieldLayoutId'], Table::FIELDLAYOUTS, ['id'], 'SET NULL', null);
```
Only the revisionId and the fieldLayoutId ones are being found by the query. The other two not anymore.
So even some newly created foreign keys are not being found anymore by that function on MySQL 8.

### Steps to reproduce

1. Setup Craft on MySQL 8.
2. Setup the Craft tests
3. Run the tests via php vendor/bin/codecept run
4. It should fail after the first set of tests (when it tries to clean the DB for the first time)

### Expected behavior

Foreign keys are created as before with references in the required MySQL tables.

### Actual behavior

Something is wrong with the foreign keys.

### Craft CMS version

4.5.5

### PHP version

8.1

### Installed plugins and versions

-

**Comment by benediktblank** [comment]
Seems to be related to Mysql 8.0.0
8.0.34 works.

**Comment by brandonkelly** [comment]
Glad you got it sorted! FWIW I’ve been running tests without this issue using MySQL 8.0.33.
