### ISSUE TITLE
Asset field in inline editing pane is wrong height

### ISSUE THREAD

**Issue by klepl** [craftcms/cms#1384]
### Description
Image fields don't have enough space when inline editing.

### Steps to reproduce

1. Create 2 entries, (A) simple entry (B) entry with an image and some more fields below it
2. Associate entry B with entry A
3. Edit entry A
4. Double click entry B to edit it inline
5. Observe how the image field overlaps the field below it

![image](https://cloud.githubusercontent.com/assets/11430201/23041798/4011fbee-f464-11e6-967f-049925814a2f.png)

### Additional info

- Craft version: Craft CMS 2.6.2959
- PHP version: 5.6.11
- Plugins & versions: CP Sortable Custom Columns 1.1.1, Embedded Assets 0.3.4, Hacksaw 2.0.0, Oauth 2.0.3, Twitter 1.1.2, VZ URL 1.0.3
- Chrome Version 56.0.2924.87 (64-bit)

**Comment by takobell** [comment]
Thanks, @klepl!

**Comment by benjamindavid** [comment]
I've been unable to replicate this. Closing this as a lot of CSS changes have happened since then. Feel free to reopen if it's still an issue for you.

**Comment by klepl** [comment]
I can confirm that this was fixed somewhere between v2.6.2992 and v2.6.3003. Thanks.
![image](https://user-images.githubusercontent.com/11430201/34846294-a9d7d7e0-f6e5-11e7-8beb-dd2bacce3c53.png)
