### ISSUE TITLE
[4.x]: Latest update breaks selecting multiple entries in entry fields using ctrl/cmd + click

### ISSUE THREAD

**Issue by ddnetters** [craftcms/cms#13853]
### Description

It seems the latest update breaks selecting multiple entries in entry fields using ctrl/cmd + click. Previously, entry fields that allowed for multiple entries had a feature where you could ctrl/cmd click all entries you want to add. I haven't looked into the code yet but I assume it's related to this change https://github.com/craftcms/cms/issues/13823.

### Steps to reproduce

1. Add an 'entry field' to an entry that allows selection of multiple entries
2. Open the entry
3. Click on the entry field to add entries
4. Try to select multiple entries using ctrl/cmd + click
5. Nothing happens

### Expected behavior

At step 5 the clicked entries get selected.

### Actual behavior

Step 4 has no effect.

### Craft CMS version

4.5.7

### PHP version

8.1

### Installed plugins and versions

-

**Comment by philipboomy** [comment]
I have run into this "bug" too.

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.
