### ISSUE TITLE
"Table" fieldtype data erased when data exceeds "TEXT" character limit in MySQL

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#1385]
### Description

Using a Table field type with 15 columns.

Took around 135 rows of data to exceed the MySQL TEXT character maximum of 65,535 characters.

### Steps to reproduce

1. Create a Table field type and add it to an entry type's field layout.
2. Add enough data to fill 65,535 characters.
3. Save entry.

### Additional info

- Craft version: 2.x and 3.x
- PHP version: N/A
- Database driver & version: MySQL (not an issue for PostgreSQL)
- Plugins & versions: N/A

**Comment by takobell** [comment]
Similar to FR #1381.

**Comment by brandonkelly** [comment]
This isn’t limited to Table - a Plain Text field could have the same issue.

What’s the right solution here? Give Table and Plain Text their own Column Type settings, a la Rich Text?

**Comment by takobell** [comment]
Yeah... Table and Plain Text get their own setting, but they should all be hidden from PostgreSQL. See: https://github.com/craftcms/cms/issues/1413

**Comment by brandonkelly** [comment]
Resolved via 40e62c9d4e3222f7b8d75c752eaa30ecbc4d7942, d32ae86c38a18e1bf1c0a28bf923cc2b06459b0d, and 615f09cdadcf095a1ec42dd7d39c5e801e7657e4.
