### ISSUE TITLE
[4.x] Disabled/Static Dropdown fields are back, but illegible

### ISSUE THREAD

**Issue by amphibian** [craftcms/cms#13850]
### Description

Dropdown fields on completed orders are [no longer hidden](https://github.com/craftcms/cms/issues/13753), but their disabled state makes them almost invisible, and thus not very useful for admins looking to see which options might have been selected via these fields.

<img width="397" alt="Screenshot 2023-10-18 at 4 20 06 PM" src="https://github.com/craftcms/commerce/assets/53333/caa6d401-c13a-40c3-ae1a-9819f4c39bcd">

### Craft CMS version

4.5.7

### Craft Commerce version

4.3.1

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
This is resolved in Craft 4.5.8, via #13857 :tada:
