### ISSUE TITLE
[5.x]: Matrix workflow is cumbersome and requires you to frequently leave the field context compared to <4.x

### ISSUE THREAD

**Issue by aaronbushnell** [craftcms/cms#13868]
### Description
I apologize if this is the wrong spot for it, but I wanted to share some workflow confusion I see with the new 5.x approach to Matrix. 

My biggest concern is that, previously, fields and block types could be created directly from Matrix without leaving that context. You could create something as complex as this without leaving the field:

- **Block:** Rich Text
  - **Field:** Body
- **Block:** Accordion
  - **Field:** Heading
  - **Field:** Body
  - **Field:** Accordion Item (Super Table)
    - **Field:** Body

**⚠️ Disclaimer** I recognize the performance, authoring, and other negative experiences with this approach. I'm just pointing out the flexibility and "freeness" originally part of this field.

However, with the recent Matrix changes, it's not (yet?) possible to create this type of setup without frequently leaving the Matrix context. And this is the part that feels like a step backwards to me.

Again, I recognize the changes to Matrix make it _far_ more performant. I **love** this switch and don't think it should be reverted! I just want to point out the cumbersome aspects of working with this in today's version of Craft 5.

### Steps to reproduce

For this, I've created a video of what my experience is like using the new Matrix fieldtype in Craft 5 and the types of things I notice when using it.

https://github.com/craftcms/cms/assets/315202/ad4a45e6-faf8-43c2-8179-455190836172

### Craft CMS version

Craft Solo 5.0.0-alpha

### PHP version

8.2.11

### Operating system and version

Darwin 23.0.0

### Database type and version

MySQL 5.7.41

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.1-18)

### Installed plugins and versions

None

**Comment by leevigraham** [comment]
@aaronbushnell my guess is the new entries block plugin for CKEditor will be the recommended way of creating "content block builders".

**Comment by brandonkelly** [comment]
The UI for Matrix field / entry type creation is still very much a WIP for Craft 5. It will be much improved by the time the Beta is released.
