### ISSUE TITLE
[4.x]: Asset browser - web browser back button does not work

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#13877]
### Description

Changing directory in asset browser changes web browser url, but when uuse back browser button, i do not end up on previous asset directory, but on previous web page (for example on dashboard).

### Craft CMS version

 4.5.6.1 

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
This is currently working as intended. See #12826 for an existing discussion on it.
