### ISSUE TITLE
[3.x]: Content workflow leads to unexpected changes on other sites

### ISSUE THREAD

**Issue by cdccairns** [craftcms/cms#13908]
### Description

Our installation contains multiple Sites in one language and a Single section with numerous fields (Assets, Entries, Matrix, and Plain Text). All of these fields are translated for each site or, in the case of the Matrix blocks, are saved only to the site in which they are created. Revisions are disabled for the Single section.

Content managers are assigned to a group with unrestricted permissions for the Single section. Site permissions are set on the individual level: some content managers have permission to edit multiple sites, some only one site.

The purpose of this setup is to allow content managers to make changes to the Single section on the site(s) for which they have permission without affecting other sites. However, we have received reports of unexpected changes to content such as empty Plain Text and Assets fields and missing/additional Matrix blocks, presumably brought about by a flaw (or bug) in the content workflow which is allowing content managers to unknowingly overwrite one another's changes.

### Steps to reproduce

Our working theory is that this is related to the saving and publication of draft entries, but despite various tests we have been unable to reproduce exactly the described behaviour.

### Expected behavior

Changes are saved/published only to the currently-edited site.

### Actual behavior

Content on other sites is unexpectedly overwritten.

### Craft CMS version

3.7.63.1

### PHP version

7.4

**Comment by brandonkelly** [comment]
Without specific steps to reproduce, there’s nothing for us to go on here.

Craft 3 is also no longer actively supported, beyond security issues, so as a starting point you should look into upgrading to Craft 4. There have been a couple improvements to how site propagation works in Craft 4, so it’s possible that by upgrading you will solve the underlying issue.

**Comment by cdccairns** [comment]
@brandonkelly Understood, thanks all the same. We will try to resolve this with minor amendments to the editorial workflow and upgrade to Craft 4 as soon as we can.
