### ISSUE TITLE
[4.x]: ini_set calls warning in System Report while ini_set are editable

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#13903]
### Description
I'm still getting a warning for ini_set calls` in the System Report.
However, I can confirm that that calls to ini_set should be working, as per this test done successfully:
```
if (ini_set('max_execution_time', 60) !== false) {
    echo "Modifying max_execution_time was successful!";
} 
```

Why, and how to not get this warning?

### Steps to reproduce

1. Go to `/utilities/system-report`
2. Check `ini_set calls`

### Expected behavior
No warning

### Actual behavior
Warning

### Craft CMS version

4.5.9

### PHP version

8.1.24

### Installed plugins and versions

-

**Comment by angrybrad** [comment]
If you take this PHP code and put it in a test.php in your public web folder, then load yoursite.com/test.php in a browser, what do you get for the output?

```
<?php

$oldValue = ini_get('memory_limit');

$setValue = '442M'; // A random PHP memory limit value.

if ($oldValue !== '-1') {
    $bytes = getByteSize($oldValue) + getByteSize('1M');
    $setValue = sprintf('%sM', $bytes / (1024 * 1024));
}

$result = ini_set('memory_limit', $setValue);
$newValue = ini_get('memory_limit');

echo "<ul>";
echo "<li>oldValue: ".$oldValue;
echo "<li>setValue: ".$setValue;
echo "<li>newValue: ".$newValue;
if ($result === null) {
    echo "<li>result: null";
} else if ($result === false) {
    echo "<li>result: false";
} else if ($result === '') {
    echo "<li>result: ''";
} else {
    echo "<li>result: ".$result;
}
echo "</ul>";

function getByteSize($value)
{
    // Copied from craft\helpers\App::phpConfigValueInBytes()
    if (!preg_match('/(\d+)(K|M|G)/i', $value, $matches)) {
        return (int)$value;
    }

    $value = (int)$matches[1];

    // Multiply!
    switch (strtolower($matches[2])) {
        case 'g':
            $value *= 1024;
        // no break
        case 'm':
            $value *= 1024;
        // no break
        case 'k':
            $value *= 1024;
        // no break
    }

    return $value;
}
```

**Comment by angrybrad** [comment]
@romainpoirier good question. Any chance this is on a publicly accessible box and we could get some Craft control panel and SSH access to? If so, could you send those credentials over to support@craftcms.com and reference this issue?

**Comment by brandonkelly** [comment]
Glad you got this resolved!
