### ISSUE TITLE
[4.x]: Entry field in matrix making entries in the CP very slow.

### ISSUE THREAD

**Issue by johanneshakonsen** [craftcms/cms#13904]
### Description
I have a project with around 2000 entries, and a "content blocks" matrix field on the entry. The entries use all the blocks to a certain extent, including the ones with entry fields in them. A new entry edit page takes about 200ms to load, there's about 150 database queries and 2000 events according to the Yii debug toolbar.

When I add a matrix block with an entry field, however, the loading time increases to about 6000ms, there's now 4000 database queries and 60000 events. This does not happen when I add a matrix block without an entry field, it also doesn't happen if I introduce a completely new block to the matrix field with only an entry field and add that to the entry. Therefore I am assuming it is related to the fact that many entries are using the matrix blocks with entry fields and that reduces the time they take to render somehow.

### Steps to reproduce

1. Make a section.
2. Add a matrix field with a block that has an entry field on it
3. Make 2000 entries and add matrix blocks with entry fields and add entries to them
4. Make a new entry (observe fast load speeds)
5. Add matrix block with entry field (observe slow load speeds)

### Expected behavior
I am not sure why the amount of entries should matter when rendering the edit-page of an entry in the CP. The expected behaviour would be the same amount of load and similar amounts of db-queries/events happening even if I have a matrix block with an entry added to an entry.

### Actual behavior
When I add an entry to a matrix block with an entry field my CP editing experience slows down by about 6 seconds every time I open a new entry or save an existing one.

### Craft CMS version

4.5.9

### PHP version

8.0.30

### Operating system and version

Linux 5.15.68-0-virt

### Database type and version

MariaDB 10.4.31

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

None (I disabled them all to test this out)

**Comment by brandonkelly** [comment]
Do you have any custom module code or an installed plugin that might be getting involved with those fields?

Simply adding a new Matrix block that contains an Entries field shouldn’t come with any tangible performance impact, no matter how many entries there are, so long as you aren’t actually selecting all 2,000 entries.

**Comment by johanneshakonsen** [comment]
Even with every plugin disabled it still slows down from about 150ms to 3.5 seconds.

I've done some more testing, and it seems that the slowdown only triggers if the selected entry also has some entry field on it. It could be that the edit entry page ends up doing a ton of queries because entries in entry field have entries in entry fields that has... and that just keeps going? If so, would it be possible to limit this to query the first child instead the entire tree of relations?

**Comment by olivierbon** [comment]
Do you have _Validate related entries_ checked on the Entries field on your block?

**Comment by johanneshakonsen** [comment]
Yes I did! All over the place actually. Removing "validate related entries" from every entry field fixed my issue. Is this intended behaviour of the feature? That it validates entries all the way down I mean?

**Comment by brandonkelly** [comment]
> Is this intended behaviour of the feature? That it validates entries all the way down I mean?

It was intended, but clearly a little problematic, and also probably a little confusing, performance aside.

Craft 4.5.10 is out now, which does away with recursive relation validation. “Validate related [type]” settings now only apply when the source element is being saved/validated directly.

**Comment by johanneshakonsen** [comment]
Thanks!
