### ISSUE TITLE
[4.x]: If many tabs in a field layout, the tab switcher is not consistent 

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/cms#13911]
### Description

Since updating to Craft CMS 4.5.0, I have seen the tab switcher drop down menu for the first time, if the Order field layout has too many tabs for the current width of the screen. 

The thing is, it looked like there was enough space for my tabs to display comfortably, but the tab switcher still displayed. When interacted with, it didn't work well (it disappeared, and there was a flash of content that appeared on the left hand side of the screen)

https://github.com/craftcms/commerce/assets/2373940/aeb43d44-8c1f-42ba-92b0-6010701af409

### Steps to reproduce

1.

### Craft CMS version

4.5.x

### Craft Commerce version

4.2.11

### Installed plugins and versions

-

**Comment by i-just** [comment]
@jonleverrier any chance you remember which version you updated to Craft CMS 4.5.0 from?

**Comment by jonleverrier** [comment]
@i-just Unfortunately, I made my initial commit for this particular project starting from Craft`v4.5.6.1`. 

But if I was to guess, I would say either from `v4.4.16.1` or `v4.4.17`, as I was updating regularly at the time!

**Comment by i-just** [comment]
Thank you!

**Comment by nfourtythree** [comment]
Hi @jonleverrier 

Thank you for bringing this to our attention. We have pushed a fix which will be included in the next release of Commerce.

Thanks!
