### ISSUE TITLE
[4.x]: Unnecessary UpdateSearchIndex jobs

### ISSUE THREAD

**Issue by MangoMarcus** [craftcms/cms#13917]
### Description

We have a multisite and noticed that an excessive amount of UpdateSearchIndex (ie. "Updating search index") jobs are being queued.

After some investigation I've realised that it's triggering these jobs regardless of if any searchable fields or attributes have been updated.

Please let me know if I've misunderstood anything here

### Steps to reproduce

1. Save an existing entry without changing any fields or attributes, and it queues a new UpdateSearchIndex job even though no searchable fields have been updated
2. Save an existing entry and only change non-searchable fields, and it queues a new UpdateSearchIndex job even though no searchable fields have been updated
3. Save an existing entry and only change a translatable field (searchable or otherwise), and it propagates to other sites and queues a new UpdateSearchIndex for job even though no searchable fields have been updated for those sites

### Expected behavior

Only queue an UpdateSearchIndex job if the element has updated searchable fields or searchable attributes

### Actual behavior

Unnecessary UpdateSearchIndex jobs are queued and clogs up the queue

### Suggested solution

Perhaps add an additional check [here](https://github.com/craftcms/cms/blob/5cca4dbea2111ad5a8f5ecb99fd5a43730c5cccb/src/services/Elements.php#L3470) by filtering `$element->getDirtyFields()` and `$element->getDirtyAttributes()` to `$searchableDirtyFields` and `$searchableDirtyAttributes`, and skip the indexing if they're both empty. You'd then pass `$searchableDirtyFields` to `new UpdateSearchIndex()` instead of `$element->getDirtyFields()`. This doesn't account for the multisite aspect though in step 3.

### Workaround (WIP)

I started a solution for this using `EVENT_BEFORE_UPDATE_SEARCH_INDEX` but hit a wall

```php
use Craft;
use craft\events\ElementEvent;
use craft\helpers\ElementHelper;
use craft\services\Elements;
use yii\base\Event;

// Skip indexing if none of the fields or attributes are searchable
Event::on(
    Elements::class,
    Elements::EVENT_BEFORE_UPDATE_SEARCH_INDEX,
    function (ElementEvent $event) {
        $el = $event->element;
        $root = ElementHelper::rootElement($el);

        $fieldLayout = $el->getFieldLayout();
        if (!$fieldLayout) {
            return;
        }

        // Check for searchable dirty fields
        $dirtyFields = $el->getDirtyFields();
        $searchableDirtyFields = array_filter(
            $dirtyFields,
            function (string $fieldHandle) use ($fieldLayout): bool  {
                $field = $fieldLayout->getFieldByHandle($fieldHandle);
                return !$field || $field->searchable;
            },
        );
        if (count($searchableDirtyFields)) {
            return; // Allow the job to be queued even though some of the fields might not be searchable
        }

        // Check for searchable dirty attributes (eg. title, slug)
        $dirtyAttributes = $root->getDirtyAttributes();
        // Get the searchable attributes using the same logic as \craft\services\search::indexElementAttributes()
        $searchableAttributes = array_flip($root::searchableAttributes());
        $searchableAttributes['slug'] = true;
        if ($root::hasTitles()) {
            $searchableAttributes['title'] = true;
        }
        $searchableAttributes = array_keys($searchableAttributes);
        $searchableDirtyAttributes = array_intersect($dirtyAttributes, $searchableAttributes);
        if (count($searchableDirtyAttributes)) {
            return; // Allow the job to be queued even though some of the attributes might not be searchable
        }

        // Skip indexing if none of the fields or attributes are searchable
        Craft::warning('Skipping indexing of non-searchable fields or attributes', __METHOD__);
        $event->isValid = false;
    }
);
```

This mostly does the job but it doesn't work as expected when changing an attribute like the title or slug, in this case `$dirtyAttributes` is still empty and the job is incorrectly prevented.

This doesn't address unnecessary propagation to other sites but it does prevent those site entries from being queued, as they have no dirty searchable fields / attributes.

There might be other things I haven't considered too, any suggestions are welcome

### Craft CMS version

4.5.10

### PHP version

8.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for bringing that up!

While looking into it, I realized that “Updating search indexes” jobs are getting queued when saving nested element revisions, like Matrix blocks, which should never have been the case. So that’s now fixed for the next release.

Starting in Craft 4.6, we will stop indexing search keywords for any element type that supports change tracking, when it reports no changed attributes or fields.

**Comment by brandonkelly** [comment]
Craft 4.5.11 is out with the first part of that fix.

**Comment by MangoMarcus** [comment]
@brandonkelly Awesome, thanks for the speedy fix!!

Sorry for the noob question, but are matrix block search indices used for anything aside from the query [search param](https://craftcms.com/docs/4.x/matrix-blocks.html#search)? Just wondering if it'd be safe to prevent _all_ search index jobs for matrix blocks in my case, as I won't be using that query param

Also just RE the change in 4.6, shouldn't it only add the job if any _searchable_ dirty attributes/fields have been changed? Presently it adds the job regardless of if the changed fields/attributes are actually used in the search index, which leads to some unnecessary work updating the index in `craft\services\Search::indexElementAttributes` (correct me if I'm wrong!)

**Comment by brandonkelly** [comment]
> Sorry for the noob question, but are matrix block search indices used for anything aside from the query [search param](https://craftcms.com/docs/4.x/matrix-blocks.html#search)?

Correct.

> Also just RE the change in 4.6, shouldn't it only add the job if any _searchable_ dirty attributes/fields have been changed?

Good point. It’ll be a little more effort to take that into account, but probably worth it…

**Comment by MangoMarcus** [comment]
Thanks @brandonkelly . I tried a [solution for a PR](https://github.com/MangoMarcus/craftcms/commit/4b161a548b06dd57c1760e060ff116d5ce25c786) which I _could_ be an improvement. I'm not familiar enough with the internals of propagation though to address the remaining discrepancies.

I did a few tests before and after applying my change, using an entry with 5 multisite versions and no matrix fields.

This table shows the number of search index jobs which are added to the queue for each test. For each test I logged the number of jobs when a provisional draft is created, when an existing provisional draft is updated, and when an entry is saved (ie. the provisional draft is applied).

Some of the "expected" values may be an understanding on my part where they don't line up with the results. Hope it helps.

| Action                   | Translatable | Searchable | Expected | Before | After | Notes |
| ---                      | ---:         | ---:       | ---:     | ---:   | ---:  | ---   |
| **No change**            |              |            |          |        |       |       |
| Save entry               | N/a          | N/a        | 0        | 5 ❌   | 0 ✅︎  |       |
|                          |              |            |          |        |       |       |
| **Change field**         |              |            |          |        |       |       |
| Create provisional draft | No           | No         | 5        | 10 ❌  | 5 ✅  | Even though there's no changable fields we still expect a new search index for new provisional drafts in each site.  |
| Update provisional draft | No           | No         | 0        | 5 ❌   | 0 ✅︎  |       |
| Save entry               | No           | No         | 0        | 10 ❌  | 5 ❌  | Are the entries in each site re-created from the provisional drafts? This would explain a new index being created for each site. |
|                          |              |            |          |        |       |       |
| Create provisional draft | Yes          | No         | 5        | 10 ❌  | 5 ✅︎  |       |
| Update provisional draft | Yes          | No         | 0        | 5 ❌   | 0 ✅︎  |       |
| Save entry               | Yes          | No         | 0        | 10 ❌  | 1 ❌  | Is the entry re-created from the provisional draft? This would explain a new index being created. |
|                          |              |            |          |        |       |       |
| Create provisional draft | No           | Yes        | 5        | 10 ❌  | 5 ✅︎  |       |
| Update provisional draft | No           | Yes        | 5        | 5 ✅︎   | 0 ❌  | Does the searchable keyword only need to be updated when the entry is saved? If so then this may be correct. |
| Save entry               | No           | Yes        | 5        | 5 ✅︎   | 5 ✅︎  |       |
|                          |              |            |          |        |       |       |
| Create provisional draft | Yes          | Yes        | 5        | 5 ✅︎   | 5 ✅︎  |       |
| Update provisional draft | Yes          | Yes        | 1        | 5 ❌   | 0 ❌  | Does the searchable keyword only need to be updated when the entry is saved? If so then this may be correct. |
| Save entry               | Yes          | Yes        | 1        | 10 ❌  | 1 ✅︎  |       |
|                          |              |            |          |        |       |       |
| **Change attribute**     |              |            |          |        |       |       |
| Create provisional draft | No           | No         | 5        | 10 ❌  | 5 ✅︎  |       |
| Update provisional draft | No           | No         | 0        | 5 ❌   | 0 ✅︎  |       |
| Save entry               | No           | No         | 0        | 10 ❌  | 0 ✅︎  |       |
|                          |              |            |          |        |       |       |
| Create provisional draft | Yes          | No         | 5        | 5 ✅︎   | 5 ✅︎  |       |
| Update provisional draft | Yes          | No         | 0        | 5 ❌   | 0 ✅︎  |       |
| Save entry               | Yes          | No         | 0        | 10 ❌  | 0 ✅︎  |       |
|                          |              |            |          |        |       |       |
| Create provisional draft | No           | Yes        | 5        | 10 ❌  | 10 ❌  |       |
| Update provisional draft | No           | Yes        | 5        | 5 ✅︎   | 5 ✅︎   | ⚠️ One of the jobs is for all sites (ie.  `'siteId' => '*'`), even though each site has its own job anyway. |
| Save entry               | No           | Yes        | 5        | 10 ❌  | 0 ❌   |       |
|                          |              |            |          |        |       |       |
| Create provisional draft | Yes          | Yes        | 5        | 10 ❌  | 6 ❌   | An extra job is added for all sites (ie.  `'siteId' => '*'`), even though the other sites have their own job anyway. |
| Update provisional draft | Yes          | Yes        | 1        | 5 ❌   | 1 ✅︎   | ⚠️ Although only one site has been updated and only one job is added, it's added for all sites (ie.  `'siteId' => '*'`). |
| Save entry               | Yes          | Yes        | 1        | 10 ❌  | 0 ❌   | Is this skipped because the index is re-used from the provisional draft above? If so then this may be correct. |

**Comment by brandonkelly** [comment]
Impressive work! Just made similar changes for 4.6 (27cf3440f6322706246a81efe3fcbda94fecc679).

**Comment by MangoMarcus** [comment]
Looks great, thanks @brandonkelly !

**Comment by brandonkelly** [comment]
Craft 4.6.0 is out with those improvements. Thanks again @MangoMarcus!
