### ISSUE TITLE
[4.x]: Option from selectbox can't be translated for field table.

### ISSUE THREAD

**Issue by Megafry** [craftcms/cms#13914]
### Description
Selectbox-option from the field type table can't be translated.

### Steps to reproduce

1. Create a new field of the type table.
2. Add a new field from the type Dropdown to a column.
3. Add a option with the label `option-to-translate`
4. Add the label to the translation file `translations/en/site.php`

### Expected behavior
The option is translated with the text from the translation file.

### Actual behavior
Nothing happens 

This is odd because other selectbox can be translated without issue.
 
I tried to change the code to use selective.twig, but that didn't work either. 
[code](https://github.com/craftcms/cms/blob/4.5/src/templates/_includes/forms/editableTable.twig#L156)
 

### Craft CMS version

4.5.10

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR to adjust this.

**Comment by brandonkelly** [comment]
Craft 4.5.11 is out with the fix for that. Thanks again!

**Comment by Megafry** [comment]
I just updated my installation, works flawlessly, Thanks.
