### ISSUE TITLE
[4.x]: Entry Query Id()  Invalid numeric value: Array

### ISSUE THREAD

**Issue by lukasNo1** [craftcms/cms#13919]
### What happened?

Hello, I recently updated a project from Craft 3 to 4 and now the following query doesn't work anymore:
Entry::find()->id(['not', [1,2]])->all();

I also tried ->id(['not', 1,2]) which doesn't work either.

Is this intentionally that we cannot pass an array of ids anymore?

`[web.ERROR] [yii\base\InvalidArgumentException] Invalid numeric value: Array {"trace":["#0 /var/www/backend/vendor/craftcms/cms/src/helpers/Db.php(856): craft\\helpers\\Db::parseParam('[elements.id](http://elements.id/)', Array, '=', false, 'integer')","#1 /var/www/backend/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1417): craft\\helpers\\Db::parseNumericParam('[elements.id](http://elements.id/)', Array)","#2 /var/www/backend/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\\elements\\db\\ElementQuery->prepare(Object(craft\\db\\mysql\\QueryBuilder))","#3 /var/www/backend/vendor/yiisoft/yii2/db/Query.php(157): yii\\db\\QueryBuilder->build(Object(craft\\elements\\db\\EntryQuery))","#4 /var/www/backend/vendor/yiisoft/yii2/db/Query.php(249): yii\\db\\Query->createCommand(Object(craft\\db\\Connection))","#5 /var/www/backend/vendor/craftcms/cms/src/db/Query.php(247): yii\\db\\Query->all(NULL)","#6 /var/www/backend/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1581): craft\\db\\Query->all(NULL)","#7 /var/www/backend/modules/project/src/services/TemplateService.php(627): craft\\elements\\db\\ElementQuery->all()","#8 /var/www/backend/vendor/twig/twig/src/Extension/CoreExtension.php(1607): project\\services\\TemplateService->searchElements('tou', NULL, NULL)","#9 /var/www/backend/vendor/craftcms/cms/src/helpers/Template.php(129): twig_get_attribute(Object(craft\\web\\twig\\Environment), Object(Twig\\Source), Object(project\\services\\TemplateService), 'searchElements', Array, 'method', false, false)","#10 /var/www/backend/storage/runtime/compiled_templates/be/be8ff3162323e8f5947cbc89a8e33f47.php(49): craft\\helpers\\Template::attribute(Object(craft\\web\\twig\\Environment), Object(Twig\\Source), Object(project\\services\\TemplateService), 'searchElements', Array, 'method')","#11 /var/www/backend/vendor/twig/twig/src/Template.php(394): __TwigTemplate_706527e5221612736d93af474a0c86ba->doDisplay(Array, Array)","#12 /var/www/backend/vendor/twig/twig/src/Template.php(367): Twig\\Template->displayWithErrorHandling(Array, Array)","#13 /var/www/backend/storage/runtime/compiled_templates/39/3944f7b32b935456dc2abb9c80c1af63.php(38): Twig\\Template->display(Array)","#14 /var/www/backend/vendor/twig/twig/src/Template.php(394): __TwigTemplate_b0842c33b640f04933dbed0bbcdd3456->doDisplay(Array, Array)","#15 /var/www/backend/vendor/twig/twig/src/Template.php(367): Twig\\Template->displayWithErrorHandling(Array, Array)","#16 /var/www/backend/vendor/twig/twig/src/Template.php(379): Twig\\Template->display(Array)","#17 /var/www/backend/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\\Template->render(Array, Array)","#18 /var/www/backend/vendor/twig/twig/src/Environment.php(277): Twig\\TemplateWrapper->render(Array)","#19 /var/www/backend/vendor/craftcms/cms/src/web/View.php(482): Twig\\Environment->render('_templateLoader', Array)","#20 /var/www/backend/vendor/craftcms/cms/src/web/View.php(535): craft\\web\\View->renderTemplate('_templateLoader', Array)","#21 /var/www/backend/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\\web\\View->renderPageTemplate('_templateLoader', Array, 'site')","#22 /var/www/backend/vendor/yiisoft/yii2/web/Response.php(1100): craft\\web\\TemplateResponseFormatter->format(Object(craft\\web\\Response))","#23 /var/www/backend/vendor/craftcms/cms/src/web/Response.php(337): yii\\web\\Response->prepare()","#24 /var/www/backend/vendor/yiisoft/yii2/web/Response.php(340): craft\\web\\Response->prepare()","#25 /var/www/backend/vendor/yiisoft/yii2/base/Application.php(390): yii\\web\\Response->send()","#26 /var/www/public/index.php(14): yii\\base\\Application->run()","#27 {main}"],"memory":33796056,"exception":"[object] (yii\\base\\InvalidArgumentException(code: 0): Invalid numeric value: Array at /var/www/backend/vendor/craftcms/cms/src/helpers/Db.php:605)"}`

### Craft CMS version

4.5.9

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch!

Passing multiple IDs is still possible. The correct notation is: `->id(['not', 1, 2])`, and I’ve confirmed that it still works as expected.

I can trigger the same error if I call `Entry::find()->id(['not', 'Array'])->all()`, so maybe double-check what’s the actual value being passed to the `id()`?

I’m going to close this now, but please feel free to reach out again if you have any further questions.
