### ISSUE TITLE
[4.5.10]: Mysql is using 100%+ CPU even without website access

### ISSUE THREAD

**Issue by pnpaes** [craftcms/cms#13925]
### What happened?

I inherit a very old project running on craftcms 3.4.x and updated it to the latest version of craft [4.5.x] following all the necessary steps. I have done that a couple of times so the process is not new to me.
After the update the test server is freezing because mysql is using 100%+ of CPU.
I tried to revise all larger queries in the project, including adding eager loading when possible.
I ran all the craft optimization and cleanup commands via console as well.
Nothing seems to help.

This is what I get when I ran `top` in my ubuntu server:
  PID       USER     PR  NI    VIRT           RES        SHR      S   %CPU   %MEM     TIME+         COMMAND                                            
  70465  mysql    20   0      1571248   557852  24144   S   112.3     6.9            320:51.18   mariadbd 

And if I run `mysqladmin version` i get this.
mysqladmin  Ver 9.1 Distrib 10.6.12-MariaDB, for debian-linux-gnu on x86_64
Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Server version		10.6.12-MariaDB-0ubuntu0.22.04.1
Protocol version	10
Connection		Localhost via UNIX socket
UNIX socket		/run/mysqld/mysqld.sock
Uptime:			9 hours 17 min 23 sec

Threads: 43  Questions: 17853553  Slow queries: 1  Opens: 2008  Open tables: 1064  **Queries per second avg: 533.850**

This project is in a test server and there is no access to it.
And it still outputs **Queries per second avg: 533.850**

Sometimes when I check the queue there are 50.000+ items running there for imagem transformations.
But even when the queue i empty mysql is still eating the  CPU...

### Craft CMS version

4.5.10

### PHP version

8.1.2

### Operating system and version

Linux 5.15.0-76-generic

### Database type and version

MariaDB 10.6.12

### Image driver and version

Imagick 3.6.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

Contact Form | 3.0.1
Contact Form Honeypot | 2.0.0
Redactor | 3.0.4
SuperSort | 4.0.0
Typed link field | 2.1.5

Original project had SEOMatic but I removed it.

**Comment by brandonkelly** [comment]
Can you try restarting the web server?

**Comment by pnpaes** [comment]
@brandonkelly 
restarted mysql, php and nginx... plus did the turn off/on in the VM.
the thing is that even without anybody accessing this test site, it goes crazy on the mysql CPU. it is as if it is runnings soming.
I even created a fresh new server, changed from mysql to mariadb, but no effect.
the live site using craft 3.4 is working properly without any of this side effects.
live site with old craft is detandreteatret.no while the one with craft 4.5 is detandreteatret.daytwo.no
my local environment on docker+mariadb is working fine as well.
not sure what could be causing this issue in the VM. mysql error logs don't have anything related to this.

**Comment by angrybrad** [comment]
@pnpaes any chance we could get some Craft control panel and SSH access to this test box? If so, could you send the creds over to support@craftcms.com and reference this issue?

**Comment by pnpaes** [comment]
@angrybrad you sure can....
could you send me your public key and I can add it to the server?
if more than one person needs access, you can send all the keys.

**Comment by angrybrad** [comment]
@pnpaes sure thing - my public key is here: https://github.com/angrybrad.keys

**Comment by pnpaes** [comment]
thanks @angrybrad 
I will send the details to the support email!

**Comment by angrybrad** [comment]
This ended up being caused by some DDOS/spike in traffic.
