### ISSUE TITLE
[4.x]: Live Preview won't load for Single entry with unsaved changes to Current version

### ISSUE THREAD

**Issue by benjaminkohl** [craftcms/cms#13921]
### Description

A client reported to me the Live Preview button was spinning and the preview wouldn't load if she made changes to the Single (homepage) entry prior to clicking the Preview button. I did a lot of testing locally and seem to have narrowed down the behavior a bit so I hope this information helps. Here are some of the facts:

- Live Preview **fails** to load if I am editing the Current version of the Single entry and I do _not_ save my changes prior to clicking Preview.
- Live Preview **loads** if I create a new draft, make _unsaved_ changes, then click "Preview".
- Live Preview **loads** if I edit the Current version, _save_ the changes, then click "Preview".

In all these tests, the changes I made were adding my name to a rich text field nested in a Matrix. `maxRevisions` is set to 10 on this site. It does appear at least that many drafts/revisions are saved to this entry.

I do not see anything being logged to any of the Craft logs. I do see some browser console warnings about setInterval timeout violations. They look like this:

```
[Violation] 'setTimeout' handler took 137ms    injected.js:4 
[Violation] 'setTimeout' handler took 143ms    injected.js:4 
[Violation] 'setTimeout' handler took 155ms    injected.js:4 
[Violation] 'setTimeout' handler took 157ms    injected.js:4 
[Violation] 'setTimeout' handler took 139ms    injected.js:4 
[Violation] 'setTimeout' handler took 149ms    injected.js:4 
[Violation] 'setTimeout' handler took 134ms    injected.js:4 
```

### Steps to reproduce

1. Open the Homepage Single entry, add one word to a rich text field in a Matrix (maybe that is relevant?), click the "Preview" button.

This results in a spinner animation appearing on the button itself as well as next to the version history selector.

### Expected behavior

Control Panel should switch to Live Preview mode without having to save the temporary changes made to the entry's Current version **OR** if manually creating a new draft is expected/required, perform more graceful error handling when user doesn't do that.

### Actual behavior

Spinner animation persists on Live Preview button and next to the version selector. Live Preview doesn't load.

### Craft CMS version

4.5.10

### PHP version

8.1

### Operating system and version

Linux 5.15.0-67-generic

### Database type and version

MariaDB 10.6.15

### Image driver and version

GD 8.2.10

### Installed plugins and versions

Cookies 4.0.0
Element API 3.0.1.1
Feed Me 5.2.0
Freeform 4.1.11
Imager X 4.2.3
Inventory 3.1.1
Linkit 4.0.4.1
Minify 4.0.0-beta.2
Neo 3.9.8
Redactor 3.0.4
Retour 4.1.14
SEOmatic 4.0.33
Super Table 3.0.12

**Comment by i-just** [comment]
Hi, thanks for getting in touch! 

Do you, by any chance, have an `autosaveDrafts` general config set to `false` on this project?

**Comment by jonleverrier** [comment]
I'm on Craft CMS `v4.5.11` btw!

**Comment by i-just** [comment]
@jonleverrier live preview only works if you have `autosaveDrafts` set to `true`: https://craftcms.com/docs/4.x/config/general.html#autosavedrafts.

**Comment by jonleverrier** [comment]
@i-just This makes sense.

Why does the Live Preview button still show on entry pages, if `autosaveDrafts = false` disables it? That could be the problem here.

**Comment by jonleverrier** [comment]
Also, when `autosaveDrafts = false` Live Preview still kind of works under these conditions:

> * Live Preview **loads** if I create a new draft, make _unsaved_ changes, then click "Preview".
> * Live Preview **loads** if I edit the Current version, _save_ the changes, then click "Preview".

**Comment by i-just** [comment]
We're discussing this internally. I'll get back to you once I have more info.

**Comment by benjaminkohl** [comment]
```
Do you, by any chance, have an autosaveDrafts general config set to false on this project?
```

I missed the notifications for the responses here. Sorry! Yes, the site does have autosaveDrafts set to false.
