### ISSUE TITLE
[4.x]: Project Config File Apply Bug

### ISSUE THREAD

**Issue by krizzzly** [craftcms/cms#13939]
### Description

```
$ craft project-config/rebuild
Rebuilding the project config from the current state ... done

$ craft project-config/apply
Your project config files were created for different versions of Craft and/or plugins than what’s currently installed.

Internal Assets is installed with schema version of 1.0.0 while 2.0.0 was expected.

Try running `composer install` from your terminal to resolve.
```
I tried alot, composer clearcache, composer update, composer install.
I dont know where the that 1.0.0 is coming from:

db plugin table says: schemaVersion "2.0.0"
projectconfig table says: schemaVersion "2.0.0"
project yaml files say: schemaVersion "2.0.0"

It prevents me from actual applying an updated project config.

### Craft CMS version

4.5.11

### PHP version

8.1.13

### Operating system and version

macOS

### Database type and version

mariaDB 10.3

### Installed plugins and versions

-
Internal Assets

**Comment by brandonkelly** [comment]
It’s saying that the plugin’s actual PHP files are saying the schema version that is Composer-installed is `1.0.0`.

It [looks like](https://github.com/tikiatua/internal-assets-plugin/blob/craft4/src/Plugin.php) the plugin isn’t actually declaring a schema version, and `1.0.0` is the default.

So I guess the question is, why is it set to `2.0.0` for you?

**Comment by krizzzly** [comment]
thx alot, that pointed me to the right direction.

**Comment by krizzzly** [comment]
thx alot, that pointed me to the right direction.
