### ISSUE TITLE
slight mishap on way to the plugin forum

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1393]
### Description
System Report is showing two of one plugin, one of another, instead of all three. Film attached, System Report and database craft_plugins records for ground truth. Settings/plugins listing is ok.

### Steps to reproduce

1. Have three plugins
2. Look at System Report for plugins

pictures are here:

![systemreportshows](https://cloud.githubusercontent.com/assets/247945/23052677/06d7f026-f488-11e6-9cad-623349f872e3.png)
![plugins-database-shows](https://cloud.githubusercontent.com/assets/247945/23052685/1106c5cc-f488-11e6-9caa-0d44b45d7a37.png)

### Additional info

- Craft version: Craft CMS 3.0.0-beta.3
- PHP version: 7.0.15-1+deb.sury.org~xenial+1
- Database driver & version: MySQL 5.7.17-0ubuntu0.16.04.1
- Plugins & versions: Bactrin, Trimmer, StandardsAgent (all narrationsd)

**Comment by brandonkelly** [comment]
Not able to reproduce this. What happens if you disable Trimmer (the real one) and Standards Agent? Does Bactrin show up correctly?

**Comment by narration-sd** [comment]
Hmm, well, I had done something uncool – apparently copied the getName() function from Trimmer to Bactrian when scaffolding the C3 upgrade, and in a hurry, forgot to change  it appropriately.

Fixed code, problem gone. Saving you the trail – I had tried some removals before, but not the right one, apparently.

Close, bitte (please)
