### ISSUE TITLE
[4.5.11]: User Impersonation not working for users without CP access

### ISSUE THREAD

**Issue by RevaCo** [craftcms/cms#13940]
### Description
User Impersonation Link works for users with CP access but is failing for users _without_ CP access

### Steps to reproduce

1. User -> Copy impersonation URL -> Paste copied URL into private browsing window

### Expected behaviour

Login as impersonated user

### Actual behaviour

Displays index page _without_ logging the user in

**Note:** 

1. 'Sign in as user' works as expected 
2. Issue first seen in Craft 4.5.10

### Craft CMS version

4.5.11

### PHP version

8.1 (R14.2)

### Operating system and version

Linux 6.1.27-3-virt (Servd)

### Database type and version

MariaDB 10.6.8

### Installed plugins and versions

Color Mixer | 3.0.0
CP Field Inspect | 1.4.4
Feed Me | 5.2.0
Formie | 2.0.42
Image Resizer | 3.0.8
Inventory | 3.1.1
MatrixMate | 2.1.4
Navigation | 2.0.22
oEmbed | 2.3.0
Preparse Field | 2.1.0
Redactor | 3.0.4
Send Password Reset | 2.0.6
SEO | 4.0.35
Servd Assets and Helpers | 3.5.4
Socializer | 2.0.4
Super Table | 3.0.12
Table Maker | 4.0.7
Typed link field | 2.1.5
Upvote | 2.3.2
Video Utils | 2.0.2
Vite | 4.0.6

**Comment by i-just** [comment]
Hi, thanks for getting in touch. 

A similar issue was [raised here](https://github.com/craftcms/cms/issues/13621), and someone suggested that [clearing all cookies and logging back in fixed this for them](https://github.com/craftcms/cms/issues/13621#issuecomment-1709549021).
Could you please try that and see if that helps? 

If not, could you please confirm if the URL you see after going to User -> Copy impersonation URL (for a user that doesn’t have control panel access) is pointing to the front end or the control panel?

**Comment by RevaCo** [comment]
Hello Iwona

We use an incognito/private browsing window for impersonation urls so that will take cookies out of the equation, also tried in multiple browsers and all had the same issue.

I looked at the impersonation url for both a user with CP access and once without, the CP access user pointed to the control panel as expected: _https://domain.com/admin?token=abcEasyAs_123..._ but the non CP access user didn't _https://domain.com/?token=abcEasyAs_123..._

Thanks
John

**Comment by i-just** [comment]
Thanks for confirming. That’s the expected behaviour.

For clarity, the impersonation URL won’t work if you try to use it more than once, if the token expired (they’re valid for 1h), or if the token is deemed invalid.

I’m unable to replicate this behaviour on a clean instance. Would you be able to send your `composer.json`, `composer.lock`, database export and `config` directory to support@craftcms.com so that we can dig deeper?
