### ISSUE TITLE
[4.x]: Field changes on local don't propagate onto other dbs

### ISSUE THREAD

**Issue by gbowne-quickbase** [craftcms/cms#13950]
### Description
We've had issues crop up in the past few weeks where a developer's yaml file matrix field changes will not be applied when they are deployed and `./craft up` is run on integration or staging servers, and are only applied by running a `./craft project-config/apply --force` which seems to break the contract of being able to use a dev's yaml files to affect change on other machines. We had to abort a release because the changes we re-did didn't make it onto the staging machine.

Similarly, if we take a fresh db from our production server, and put it on local and run the same `./craft up`, we don't see the changes. This makes me think that some of the field `uid` or `changedFieldIndicator` lines in the yaml files are db or machine specific. 

Additionally, when we've had a merge conflict or even a normal Pull Request, it's near impossible to know whether the work is correct, or which line to keep in a conflict because the `uid` lines exist only in their respective files.

<img width="704" alt="Screenshot 2023-11-20 at 10 40 37 AM" src="https://github.com/craftcms/cms/assets/39066452/bd0bf270-949b-41ff-95e9-79e0ea0d6b23">

Some more details:
We deleted some matrix fields. The yaml files don't have the fields in them anymore, yet applying the yaml changes to a fresh database do not delete those fields, and when we re-do the work, we do see changedFieldIndicators changes in the file now on every field save.

When we redid the work, this is what we now see (below), but there's no confidence that this will affect things when we push to other servers.

![image](https://github.com/craftcms/cms/assets/39066452/69647e60-2f35-4e30-91fb-58775debb79e)

### Steps to reproduce
1. Apply changes to a matrix field on a database locally
2. Have another developer make other changes to the matrix field
3. commit both sets of changes
4. Apply the first developer's changes to the second developer's machine

### Expected behavior
1. Both sets of changes would be present
2. Field changes like dropdown lists or added fields show up

### Actual behavior
1. Adjusted fields are not there or not changed

### Craft CMS version

4.5.9

### PHP version

8.2.12

### Operating system and version

Linux 3.10.0 and MacOs 14.x

### Database type and version

MySQL 5.7

### Image driver and version

GD 8.2.12

### Installed plugins and versions

Relevant Plugins
- MatrixMate 2.1.3
- Supertable 3.0.12
- Field Manager 3.0.8

Also running SEO Matic, Retour... because we're not monsters

**Comment by i-just** [comment]
Hi, thanks for getting in touch!

As far as the `changedFieldIndicator` goes, that looks to be related to the Super Table plugin. Here’s:
- a stack exchange link: https://craftcms.stackexchange.com/questions/40401/changedfieldindicator-change-on-every-commit 
- an issue from the Super Table repo: https://github.com/verbb/super-table/issues/500
- a discussion about it: https://github.com/craftcms/cms/discussions/12597


In terms of the changes not being applied when running `./craft up`, this should happen if:
- the `dateModified` timestamp in the yaml file is the same as the one in the cache (in the environment you’re trying to apply the changes to): https://github.com/craftcms/cms/blob/develop/src/services/ProjectConfig.php#L662
- or if the content of the config files is deemed not to have changed: https://github.com/craftcms/cms/blob/develop/src/services/ProjectConfig.php#L673


> This makes me think that some of the field uid or changedFieldIndicator lines in the yaml files are db or machine specific.

Before we go further, can you please confirm if you have the `allowAdminChanges` config setting set to `false` in all but development environments?

**Comment by gbowne-quickbase** [comment]
Thanks for the quick reply @i-just ! 
I just re-ran my fresh db and ./craft up on that server after changing `allowAdminChanges` to false  and I can see it's set because the "Settings" part of the nav is no longer there. I can see the new field I'd expect to be added within the appropriate `yaml` file but I don't see that field when I look at that component, and similarly, fields which we deleted continue to show in the component.

**Comment by i-just** [comment]
Not a problem @gbowne-quickbase!

> on that server after changing allowAdminChanges to false

Does that mean that you didn’t have `allowAdminChanges` set to `false` in all non-local-development environments before? (That can certainly cause some unexpected results.)

**Comment by gbowne-quickbase** [comment]
We had it turned on in case of emergencies if we weren't able to run a full release, but needed to make a configuration change. We've not had this sort of yaml file change failure ever though.

**Comment by i-just** [comment]
It’s not advised to have `allowAdminChanges` set to `true` in any but local dev environments.

Could you please send the `composer.json`, `composer.lock` and zip of the `config/project` folder from the environment that has the changes (e.g. the first developer’s machine from your steps to reproduce) and the `composer.json`, `composer.lock` and database export from the environment you want the changes to be applied to (e.g. the second developer’s machine from your steps to reproduce) to support@craftcms.com so that we can try to replicate this and have a closer look? 
Please also point out what changes don’t get applied but should after you `./craft up` (e.g. field A not added, field B not removed, field C should have config X but still has Y). I don’t need them all, but just a handful will be helpful.

**Comment by gbowne-quickbase** [comment]
We eventually did the work over several separate releases and were able to get the changes through. We think a dev didn't add all the lines in the project config that were necessary to get the changes to propagate
