### ISSUE TITLE
[4.x]: Markdown in UI elements: Quotes inside inline code are incorrectly escaped

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#13959]
### Description

Not sure if this is an issue in the Markdown engine or in Craft. I'm talking about UI Elements like the Tip in Field Layouts. Single or double quotes inside inline code (marked up with backticks) are converted to entities, but the entities are visible in plaintext to the end user.

### Steps to reproduce

1. Add a Tip to any Field Layout with the following content:

```
`"Double Quotes"` or `'Single Quotes'`
```

Then open the entry form, the text displays like this:

```
&quot;Test&quot; &#039;Test&#039;
```

![Screenshot showing the incorrectly escaped tip contents](https://github.com/craftcms/cms/assets/10146880/9a0b611b-80c5-4cba-b83a-b8245019ac3b)

### Expected behavior

The quotes should be displayed as quotes instead of entities, as shown in the first example above.

### Actual behavior

The quotes are output as HTML entity shortcodes to the page.

### Craft CMS version

4.5.11

### PHP version

8.2

**Comment by brandonkelly** [comment]
Craft 4.5.13 is out with a fix for this. Thanks again!
