### ISSUE TITLE
[5.0.0-alpha]: User specific sidebar missing from user detail

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#13966]
### Description

I created a new user and when viewing the detail page (eg: /admin/users/10), the user specific sidebar options seem to be missing.
![Screenshot 20231123-201931-F5PsioV7](https://github.com/craftcms/cms/assets/755428/78cbfc04-c7be-4488-b6a6-f890d0dcdd9c)

The do still show up in the slide-out version of the user.

### Craft CMS version

5.0.x-dev

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
They’ve been moved to the action menu in the global header, if that’s what you’re referring to.
