### ISSUE TITLE
[4.x]: canView checked directly on element rather than running though the elements service?

### ISSUE THREAD

**Issue by samhibberd** [craftcms/cms#13981]
### What happened?

Testing our custom permissions logic and when using the elements/save controller to save elements the canView method is called directly on the element rather that going via the elements service:

https://github.com/craftcms/cms/blob/da1a32b7b52be15bf6fa7286ffbade2d0d11f14e/src/controllers/ElementsController.php#L1905

Needs to be updated to:

```php
if (!$elementsService->canView($element, static::currentUser())) {
    throw new ForbiddenHttpException('User not authorized to edit this element.');
}
```
Similar to https://github.com/craftcms/commerce/issues/3285

### Craft CMS version

4.5.11

### PHP version

8.2

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for it.

**Comment by brandonkelly** [comment]
Craft 4.5.12 is out with the fix for this. Thanks again!

**Comment by samhibberd** [comment]
Thanks @brandonkelly perfect timing, launching tomorrow 🥳
