### ISSUE TITLE
[4.x]: Selectable Entries Condition doesn't work in a matrix field

### ISSUE THREAD

**Issue by d13creative** [craftcms/cms#13980]
### Description

Selectable Entries Condition doesn't work in a matrix field

### Steps to reproduce

1. Add an "entries" field to a block within a matrix field
2. Set the "Selectable Entries Condition". In my case I set the Entry Type to be "one of" a type. However, I also tested with other conditions

### Expected behavior

On the entry editing page when selecting the entry I expected to only see the entry types specified in the field setting.

### Actual behavior

All entry types from the sources were displayed.

I tested with a single "entries" field which worked as expected, this issue seems to be limited to just entries fields within matrix blocks.

### Craft CMS version

4.5.11

### Installed plugins and versions

-

**Comment by d13creative** [comment]
![Screenshot 2023-11-30 at 15 24 56](https://github.com/craftcms/cms/assets/1433528/c18845a5-bb27-4528-9759-2223c3343f45)
![Screenshot 2023-11-30 at 15 29 11](https://github.com/craftcms/cms/assets/1433528/e885840d-5f6e-4f0e-8cab-8263e8da96f3)


Screenshot 2023-11-30 at 15 24 56
Screenshot 2023-11-30 at 15 25 23

Yes, that's pretty much it. I have a "widgets" section with different entry types and a matrix block with a block which you can select a widget from.

**Comment by i-just** [comment]
Thanks! Unfortunately, we’re still unable to replicate this. 

Could you please send your `composer.json`, `composer.lock` and the database export to support@craftcms.com so we can dig deeper?

**Comment by d13creative** [comment]
Very sorry, my mistake, I had two similar blocks with the same entries field and I was setting the condition on the wrong one🤯🙈
