### ISSUE TITLE
Globals not available from renderObjectTemplate()

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#14]
#### Environment:

- Craft version: 3.x
- PHP version: 7.x
- Database driver & version: n/a 
- Plugins & versions:

#### Description:

Custom global variables don't work in the "Title Format" field to set up dynamic / auto-generated entry titles.

Example:
`{{ globalSet.globalFieldHandle }} - {{ object.postDate }}`

**Comment by brandonkelly** [comment]
This is working in 3.0.0-beta.2. Probably fixed by 28d3995a3e0e9d347566c929d38d02137e53ed4a.
