### ISSUE TITLE
[4.x]: The conflict dialog for asset uploads is too easy to dismiss accidentally

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#14002]
### Description

When uploading an asset with a filename that already exists on the server, you get this warning:

![craft-conflict-warning](https://github.com/craftcms/cms/assets/10146880/c448d21a-7c5d-4a9f-a4da-21ae9d209651)

This modal window is very important, especially when you've uploaded multiple files. Using the _Keep both_ option will result in duplicate files, so this should require explicit confirmation.

At the moment, clicking outside the modal window will dismiss it and choose the _Keep both_ option, without any indicator as to what happened. The duplicate asset is only shown after reloading the page manually, as dismissing the dialog doesn't trigger a refresh of the asset index. So any user would wrongly assume that clicking outside the window is equivalent to the _Cancel_ button, where the duplicate is discarded.

This just happened to me, I had uploaded a bunch of optimized images to replace previous uploads and done something else in the meantime. When the upload was finished, I clicked on the browser window to return focus to it, but this accidentally dismissed the dialog. Now I have to manually search and delete a bunch of duplicates 🤷 

### Steps to reproduce

1. Go to _Assets_ in the CMS, select any asset volume and upload a file. Upload the same file again.
2. When the modal window comes up, click outside it. 

### Expected behavior

Clicking outside the modal window should not dismiss it. The conflict should require a selection, either by selecting and confirming one of the two options, or by clicking on _Cancel_.

On a related note, I found it not quite clear what the _Canel_ button would do. I would prefer a third option _Abort upload_ (or something similar) instead.

### Craft CMS version

4.5.11.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Craft 4.5.12 is out with that change!
