### ISSUE TITLE
somehow cached lockout via plugin

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1400]
### Description
This is a good one, and it's happened to me twice now. I made great advance on my complex database agent plugin; can see how it's understandably taken a while for Craft 3. I lit up some code that wasn't acceptable, after lots that had been made so. I got an error saying config couldn't find my pluginname category. Ok, except that then the CP generally said the same thing. I had to delete the plugin's row from the database, get back in, and then after re-installing, all was again well.

Without getting further into specifics, what caching goes on besides what is in craft/storage/runtime folders? I cleared all those, and it didn't help. So I guess some area in the database caches some (compiled?) templates or code. i seem to have memory of this?? I don't think it's the templatecacheXXXd tables, as they're empty, and I'm not using programmed caching. 

Maybe it's not caching, but something else stuck, so that the plugin config can no longer be read -- the error. Where is plugin information stored, besides in the plugin table, that might affect this?

### Steps to reproduce

1. hit some bad code, not sure what, but quite possibly it tried to get config without specifying the plugin monicker as category, since its C2 code.
2. Get an error about not finding the plugin category. Maybe not from the same place, then.
3. Can't recover; all of Craft now gives this error, urls not in the plugin UI included.
4. Found by trying, disabling the plugin didn't help, but  removing its row in craft_plugins removed the problem.
5. Afterwards, installing the plugin was fine; didn't bring back the error, and what works in the plugin and its elaborate UI works again as it has for hours of improving wori.

### Additional info

- Craft version: beta4, but last happened on beta3

PHP version	7.0.15-1+deb.sury.org~xenial+1
Database driver & version	MySQL 5.7.17-0ubuntu0.16.04.1
Image driver & version	GD 7.0.15-1+deb.sury.org~xenial+1
Craft edition & version	Craft Personal 3.0.0-beta.4
Yii version	2.0.11.1
Twig version	2.1.0
Guzzle version	6.2.1
Imagine version	0.7-dev

Plugins

Trimmer	1.0.0
Patrol	3.0.1
Bactrian	1.0.0
Standards Agent	2.0.1

**Comment by brandonkelly** [comment]
Thanks for the report, but w/out specific code to reproduce the error, or knowing the exact wording of the error message you received, we don’t have enough info to look into this.

**Comment by narration-sd** [comment]
Thanks, Brandon -- I kind of anticipated this was wht you might need to say. I only hoped for some idea I wasn't thinking of where state might be held across invocations, thus to home in on the problem better here.

Of course I'll keep eyes open, and surely capture logs etc.  - was just in the late night momentum to unwind this at the times.

In fact now that i think of it, the config mechanism has seemed fragile under other errors, becoming again unreachable for the plugin signatture; kind of wondering about this. Quite a rapid advance through brringing up this large code, so maybe I'll come across another clue. But also happy the situation is a little in your guys' thinking caps, where deep knowledge can connect, as it does here for things I actually know about....cheers.
