### ISSUE TITLE
Feature Request: Change 404 in error logs

### ISSUE THREAD

**Issue by nexflo** [craftcms/cms#1401]
404 errors are eating up quite a bit of log space inside craft.log and make "real" errors not too clear.
I recommend several things in treading 404's:

1) Log the the false path being trigged inside the message, the TemplateController.php being logged right now is quite obvious.
2) Move 404 errors into a separate 404.log file - as these are not debuggable errors but 404's.
3) To make it stringent all HttpExceptions might as well go into their own 404/503/etc.log  files.

**Comment by nexflo** [comment]
Well just saw...changed in C3 anways...(with the Yii debug bar etc.)

**Comment by brandonkelly** [comment]
Yep, 404s are logged in a `web-404s.log` file in Craft 3.
