### ISSUE TITLE
[4.x]: Cmd+S on entry edit pages stops working after creating a related entry inline

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#14011]
### Description

After creating a new entry via an entries field on an entry edit page, the Cmd+S shortcut to save the entry no longer works – i.e. hitting Cmd+S will prompt the browser's "Save page as..." dialog, instead of actually saving the entry.

### Steps to reproduce

1. Create an entry type with an entries field in it
2. From an existing entry, click "Add entry" in the entries field. Proceed to create a new entry via the element selector modal.
3. After saving the new entry via its slideout, click "Select" in the element selector modal to select the new entry.
4. After the element selector modal closes, attempt to save the entry using the Cmd+S shortcut.
5. Observe that the browser's native "Save page as..." dialog is triggered, instead of the entry being saved as expected.

I figured this might be a focus-related problem as focus seems to be on the new-ish notification toast-thingie after the slideout closes, but even after focusing a different field in the entry's field layout, the shortcut no longer works.

Here's a video demonstrating the issue:

https://github.com/craftcms/cms/assets/298510/a178f93f-c729-4aa5-923b-fff91b3a1025

_Also worth mentioning:_ I'm actually seeing the same behaviour (i.e. Cmd+S being broken) after other actions as well, such as after selecting an asset in an assets field, or sometimes if I'm too fast to hit the shortcut after making a content change (i.e. while the draft is still being auto-saved). This is happens quite frequently, but it's intermittent. So far, the issue as described above is the only scenario I can *reliably reproduce*, so I decided to focus on that.

### Expected behavior

Entries being saved.

### Actual behavior

The browser triggers the "Save page as..." dialog.

### Craft CMS version

4.5.11.1

### Operating system and version

macOS 12.6, MS Edge 119.0.2151.97

### Installed plugins and versions

- None

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.5.12 is out with the fix for this. Thanks again!
