### ISSUE TITLE
[4.x]: Invalid `project.yaml` file due to auto-created public GQL schema missing from meta names array

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#14018]
### Description

Context: I recently had a deployment fail in production due to an error `Changes to the project config are not possible while in read-only mode.` I tracked this down to a public GQL schema missing its `meta:__names__` key in `project.yaml`. 

_To figure out why that meta name key was missing, I did some digging and here's what I found:_

1. When running `project-config/rebuild` in a project without any public GQL tokens or schemas, Craft will output an empty `publicToken` definition to the `project.yaml` file (via [`ProjectConfig::_getGqlData()`](https://github.com/craftcms/cms/blob/60aa666b8876ab0056e67e050d3ea0001856d2cd/src/services/ProjectConfig.php#L2129)). 

Here's what that looks like:

```yaml
graphql:
  publicToken:
    enabled: false
    expiryDate: null
```

2. Later, if the project config files w/ the above `publicToken` are re-applied using `project-config/apply --force`, *in an environment where admin changes are allowed* and there are no public schemas, Craft will automatically create a default, public GQL schema (probably via [`Gql::_createPublicToken()`](https://github.com/craftcms/cms/blob/60aa666b8876ab0056e67e050d3ea0001856d2cd/src/services/Gql.php#L845)?), and save it to the `config/project/graphql/schemas` folder. 

**However, and crucially, this schema will not have an entry created in the `meta:__names__` section in `project.yaml`.**

3. The missing meta name leads to the `Changes to the project config are not possible while in read-only mode.` error, when attempting to apply the YAML files in an environment where admin changes are disallowed.

_Additional context: I don't use GraphQL and the project has been bootstrapped with the `enableGql` setting set to `false`. That's not directly relevant to the issue (it happens with or without GraphQL enabled), but I thought it was worth mentioning (ideally, I think Craft shouldn't create that public schema in the first place, when GQL is disabled?)._

### Steps to reproduce

1. Bootstrap a new Craft project using the official [quick-start directions](https://craftcms.com/docs/4.x/installation.html#quick-start)
2. Do *not* visit the GraphQL section in the CP
3. Run `ddev craft project-config/rebuild` to rebuild YAML files. Observe that Craft has created an empty `publicToken` in `project.yaml`.
4. Run `ddev craft project-config/apply --force`. Observe that a public schema has been created, but with no entry in `meta:__names__`.
5. Disable `allowAdminChanges`, and run `ddev craft project-config/apply --force` again. (Alternatively; push and run `project-config/apply` in a production environment). Observe the `Changes to the project config are not possible while in read-only mode` error.

### Craft CMS version

4.5.11.1

### PHP version

8.1.26

### Operating system and version

macOS 12.6, DDEV v1.22.5

### Database type and version

Tested on both MariaDB 10.5.21 (DDEV default) and MySQL 8.0.33

### Installed plugins and versions

- None

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just added some code to guard against updating `meta.__names__` when in read-only mode, for the next release.

**Comment by brandonkelly** [comment]
Craft 4.5.12 is out with the fix for this.
