### ISSUE TITLE
Indefinitely caching with 'cacheDuration' config

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#1402]
### Description

Setting `'cacheDuration' => 0` does not cache templates indefinitely, but the doc block from src/config/defaults/general.php says so.

```PHP
/**
 * The length of time Craft will keep things cached in `storage/runtime/`.
 *
 * Set to '0' to cache things indefinitely.
 *
 * @see http://www.php.net/manual/en/dateinterval.construct.php
 */
'cacheDuration' => 'P1D',
```

### Additional info

- Craft version: Craft CMS 3.0.0-beta.4

**Comment by brandonkelly** [comment]
Yeah template caching doesn’t support indefinite caching, so if `cacheDuration` is `0`, then it will default to a year. Clarified this behavior in f02747bf7eb8da1c12ad444b6d07fdaa5879e30e.
