### ISSUE TITLE
[4.x]: Duplicate fields when entry type changes and fields in first tab don't match

### ISSUE THREAD

**Issue by angieherrera** [craftcms/cms#14030]
### Description
I have several entry types for a Resources section:
![CleanShot 2023-12-12 at 19 04 39](https://github.com/craftcms/cms/assets/442434/89aa4daa-f90b-49ed-9c3d-15d73ae2873d)

For context, the Blog entry type has these fields:
![CleanShot 2023-12-12 at 19 04 48](https://github.com/craftcms/cms/assets/442434/4cf279b0-f98a-49ed-96c5-8f8b4cd42348)

And a few of the other entry types has these fields (Product Briefs shown here):
![CleanShot 2023-12-12 at 19 05 07](https://github.com/craftcms/cms/assets/442434/4a3e8af7-a083-4b5b-8464-904209be3233)

When creating a new entry in the Resources section, the default selected entry type is Blog (which is fine). That loads the fields as expected:
![CleanShot 2023-12-12 at 19 05 19](https://github.com/craftcms/cms/assets/442434/e945a46e-9cff-4d26-bb84-8288d492d5a4)

But if I switch the entry type to Product Briefs, for example, I get duplicate fields like so which only resolve on page reload or entry/draft save:
![CleanShot 2023-12-12 at 19 05 28](https://github.com/craftcms/cms/assets/442434/1916cb79-27dd-433e-887f-b35e83bc6d3c)

### Steps to reproduce

1. Create a section with more than one entry type.
2. Have each entry type have slightly different fields.
3. Create an entry and switch to the non-default entry type.

### Expected behavior
No duplication of fields in the first tab.

### Craft CMS version

4.5.11.1

### PHP version

8.1.24

**Comment by i-just** [comment]
Hi, thanks for reaching out!

It sounds very similar to this issue: https://github.com/craftcms/cms/issues/11746
Could you please run the `craft utils/fix-field-layout-uids` command and let me know if the issue persists?

**Comment by angieherrera** [comment]
Yep, that did the trick. Thanks!
