### ISSUE TITLE
[4.x]: Umlauts 'äöü' get rendered as 'aou'

### ISSUE THREAD

**Issue by freder** [craftcms/cms#14031]
### Description
Umlauts `äöü` get rendered as `aou` when they appear in a field value.

### Steps to reproduce / Actual behavior
- create a plain-text and a redactor field and save `äöüß` in them
- render: 
```twig
{{ "äöüß" }} {# renders `äöüß` ✅ #}
{{ entry.plainTextField }} {# renders `aouß` ❌ #}
{{ entry.redactorField }} {# renders `aouß` ❌ #}
```

### Expected behavior
should all render as `äöüß`

### Craft CMS version

4.5.12

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch!

Can you please clarify: are they shown as umlauts in the Control Panel but are replaced with the plain equivalents when rendered in your template?

**Comment by freder** [comment]
@i-just yes, that's right

**Comment by i-just** [comment]
Thanks! I can’t think of anything in Craft itself that would do that, and I can’t replicate it on a clean installation, either. Are you using any plugins or custom modules?

**Comment by freder** [comment]
turns out the typeface I am using has no diacritics 🤦‍♂️
my bad.

**Comment by i-just** [comment]
Glad you got to the bottom of it!
