### ISSUE TITLE
[4.x]: User with two firstName will saved as one word.

### ISSUE THREAD

**Issue by aodihis** [craftcms/cms#14037]
### Description
We are having an issue with a user who has two first names (in two different words).
But the user.firstName now only shows the first word. It will works on first save but when we resave it, it got updated.
In our case it happens on Craft Commerce when we add the billing address with firstName have two words, but since it looks like the issue come from the `prepareNamesForSave` function on address, so we will report it here.
Is there any solution or work around to avoid this?

### Steps to reproduce

1. Create a billing address for Cart with first name (ex: John Doe) has two words. [ Can be replaced by create an address for user ].
2. Complete cart/make payment/ do an update on cart. [Can be replaced by re-save the address on cms that created on step 1].

### Expected behavior
The first name will alway John Doe. 

### Actual behavior
On step 2 it will updated by John.

As we check on this code, because on the next save the fullName already fulfill, then it will automatically update the first Name and Last Name. So any suggestion to avoid this?

 ```
if ($this->fullName !== null) {
            $generalConfig = Craft::$app->getConfig()->getGeneral();
            $languages = [
                // Load our custom language file first so config settings can override the defaults
                new CustomLanguage(
                    $generalConfig->extraNameSuffixes,
                    $generalConfig->extraNameSalutations,
                    $generalConfig->extraLastNamePrefixes,
                ),
                new English(),
                new German(),
            ];
            $name = (new NameParser($languages))->parse($this->fullName);
            $this->firstName = $name->getFirstname() ?: null;
            $this->lastName = $name->getLastname() ?: null;
        } elseif ($this->firstName !== null || $this->lastName !== null) {
            $this->fullName = trim("$this->firstName $this->lastName") ?: null;
        }
```

### Craft CMS version

4.5.11.1

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch. It sounds like the same issue as described here: https://github.com/craftcms/cms/issues/12933. We have a [PR](https://github.com/craftcms/cms/pull/13302) open to improve this behaviour, but it hasn’t been reviewed yet.

**Comment by aodihis** [comment]
@i-just I see, thank you for the confirmation.

**Comment by i-just** [comment]
Not a problem. I don’t think I have a suggestion on how to avoid this particular case, but there’s more info on the subject in [#12305](https://github.com/craftcms/cms/issues/12305) and [#11871](https://github.com/craftcms/cms/issues/11871).

I’m going to close this now, but feel free to reply if you run into further issues.
