### ISSUE TITLE
Can't change category data for each site in multisite mode

### ISSUE THREAD

**Issue by Bronskiy** [craftcms/cms#1403]
### Description
Checkbox on the right is stuck on the first website.

### Steps to reproduce

1. Create category group in multisite mode
2. Create new category
3. Change category title for each website

### Additional info

- Craft version: Craft 3 beta 4
- PHP version: 7.1.2
- Database driver & version: MySQL 5.6.33-0ubuntu0.14.04.1-log 
- Plugins & versions: no plugins

**Comment by Bronskiy** [comment]
Doesn't work in beta 5 too

**Comment by takobell** [comment]
Confirm still an issue. Clicked on "Site 2", the URI changes properly, but "Craft3" site is still selected in the UI.

![2017-02-27_11-04-01](https://cloud.githubusercontent.com/assets/61869/23375263/881119fe-fcdc-11e6-81d2-bd5b24da11f0.png)
