### ISSUE TITLE
[5.0.0-alpha.2]: JavaScript errors in matrix and custom sources (related??)

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#14049]
### Description

Maybe related, may be not, yet error message sounds a bit similar.

a) Editing an entry with a matrix field, there is this error:

![image](https://github.com/craftcms/cms/assets/60010597/dd755e7e-f16d-404e-bdaf-73debf8f6038)

Select fields are not displayed at all, the context menu of an asset field does not open.

![image](https://github.com/craftcms/cms/assets/60010597/c97dcf38-c5e2-492a-8f32-602f9591984c)

b) Editing a custom source on entry index page:

![image](https://github.com/craftcms/cms/assets/60010597/211e4949-6a85-47ad-afe4-742848126b4e)

Criteria for the custom source can't be edited.

/Karla

### Craft CMS version

Craft Solo 5.0.0-alpha.2

### PHP version

8.2.13

### Operating system and version

Linux 5.15.133.1-microsoft-standard-WSL2

### Database type and version

MySQL 8.0.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Craft 5.0.0-alpha.3 is out with a fix for this. Thanks for reporting!
