### ISSUE TITLE
[4.5.13]: Unknown argument "encode" for filter "md(flavor, inline_only)".

### ISSUE THREAD

**Issue by cgdurha2** [craftcms/cms#14048]
After updating to version 4.5.13, I'm getting an error anytime I try to edit an asset field or visit the deprecation warnings page:
Unknown argument "encode" for filter "md(flavor, inline_only)".

Any ideas how to fix this?

### Craft CMS version

4.5.13

**Comment by bob-pixeldeluxe** [comment]
I also get this error. For me it happens once I empty the smtp information in the email settings and save.

**Comment by simonleadbetter** [comment]
We have just stumbled across this and it was caused by a field validation error when creating a new entry.  We have downgraded to 4.5.12 to avoid the error.

**Comment by j-add** [comment]
I'm encountering this issue on `/admin/utilities/deprecation-errors`. 

In my case, this is caused by incompatible methods in the Wordsmith plugin (v4.3.0)- the `markdown` & `md` methods in `WordsmithService` do not currently accept an `encode` argument. [I have opened an issue on the Wordsmith repo](https://github.com/TopShelfCraft/Wordsmith/issues/57).

```Twig\Node\Expression\CallExpression::getArguments([TopShelfCraft\Wordsmith\services\WordsmithService, 'md'], [Twig\Node\Expression\ConstantExpression, Twig\Node\Expression\ConstantExpression])```

**Comment by DynamiteGoesBoom** [comment]
I just hit this snag too. A client turned off all of their entries, and now I can't turn any of them back on. Has anyone found a fix for this?

**Comment by DynamiteGoesBoom** [comment]
Looks like reverting to `4.5.11.1` fixes it

**Comment by brandonkelly** [comment]
Wordsmith should not be overriding Craft’s Twig filters, especially for Control Panel requests. Will talk to Michael about limiting the Twig extension to site templates.

**Comment by karlmacklin** [comment]
We are getting crashes on our client's site as well after this update.
We are also using Wordsmith.

**Comment by michaelrog** [comment]
✅ Wordsmith 4.4.0 is out with a change to avoid conflicting w/ Craft's filters in the CP.

Wordsmith's `markdown` and `md` are now deprecated, and I'll remove them in Wordsmith 5.0, since Craft now provides this functionality natively.

**Comment by DynamiteGoesBoom** [comment]
Thanks @michaelrog 👍
