### ISSUE TITLE
Migration createTable doesn't add the audit columns

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1404]
### Description
A \craft\db\Migration insert{} gives the optionablel default of writing the three audit columns - dateCreated, dateUpdated, uid. createTable() doesn't however, so you have to add them manually.

### Steps to reproduce

1. create a Migration
2. fill in with a createTable()
3. run  the Migration, and observe no audit columns

### Additional info

PHP version	7.0.15-1+deb.sury.org~xenial+1
Database driver & version	MySQL 5.7.17-0ubuntu0.16.04.1
Image driver & version	GD 7.0.15-1+deb.sury.org~xenial+1
Craft edition & version	Craft Personal 3.0.0-beta.4
Yii version	2.0.11.1
Twig version	2.1.0
Guzzle version	6.2.1
Imagine version	0.7-dev
Plugins

Trimmer	1.0.0
Patrol	3.0.1
Bactrian	1.0.0
Minify	1.2.2
Standards Agent	2.0.4

**Comment by brandonkelly** [comment]
Correct, we decided to remove that functionality from `createTable()`, since it’s easy enough to specify them manually, so wasn’t worth the cost of having it be “automagic” (cost = less clear what’s happening at first glance).

**Comment by narration-sd** [comment]
Ok take your word for that – would suspect deserves a highlight in the doco, esp. given the behavior of your defaulted update addition. 

 

I know someone will be on it ;)
