### ISSUE TITLE
[5.x]: Dropdown not working when used in globals

### ISSUE THREAD

**Issue by mei-lu** [craftcms/cms#14053]
### Description
When a matrix field using an entry type containing a dropdown is used in globals, the dropdown does not display. However, when that entry type is used in a standalone entry, it works fine.

Entry using entry type containing dropdown field:
![image](https://github.com/craftcms/cms/assets/52755821/a500ea81-d818-4168-bcd4-e85e42a86011)

Matrix using entry type in globals, but the dropdown field is missing:
![image](https://github.com/craftcms/cms/assets/52755821/a4be008a-da9a-4839-93f6-1311a240d58e)

### Steps to reproduce

1. Create an entry type containing a dropdown field
2. Create a field of type matrix with that entry type
3. Create a new global using the matrix field
4. Try to make an entry in the global

### Expected behavior

Dropdown menu displays.

### Actual behavior

Dropdown menu does not appear.

### Craft CMS version

5.0.0-alpha.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Craft 5.0.0-alpha.3 is out with a fix for this. Thanks for reporting!
