### ISSUE TITLE
[5.x]: Duplicated field handles after upgrade from Craft 4 to 5

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#14052]
### Description
After upgrade from Craft 4 to 5 i have fields with duplicated handle.

### Steps to reproduce
- create a text field with text1 handle and add it to an entry type layout.
- create a matrix field, block type and create a text field with text1 handle in it and add that matrix to another entry type layout.
After upgrade there are two text fields with text1 handle.
![5 - Copy](https://github.com/craftcms/cms/assets/55586085/512851f5-0ac4-4cf3-a231-914b37b2a046)

### Expected behavior
I am not sure about the logic of field migration but i think there shouldn't be duplicated field handles and this is a bug.

### Craft CMS version

5.0.0-alpha.2

### PHP version

8.2

**Comment by brandonkelly** [comment]
Craft 5.0.0-alpha.3 is out with a fix for this. Thanks for reporting!
