### ISSUE TITLE
[5.x]: Matrix field (card view mode) - Action to add a row

### ISSUE THREAD

**Issue by magnessjo** [craftcms/cms#14058]
### Description

Missing menu/button to add a row. 

### Steps to reproduce

1.Create a section
2. Create an associated entry type
3. Create a field with CKEditor
4. Create a matrix field with the CKEditor field on it
5. Add matrix field to entry type created in #2

### Expected behavior

The expected outcome is a menu/button to create a row. 

### Actual behavior

Empty field (see attached). 

<img width="756" alt="Screenshot 2023-12-19 at 11 09 20 AM" src="https://github.com/craftcms/cms/assets/856595/36e910c1-51b9-4feb-9b4e-2cbb4aaf9d00">

### Craft CMS version

Craft Pro 5.0.0-alpha.2

### PHP version

8.2.10

### Operating system and version

Mac 14.2.1

### Database type and version

MySQL 8.1.0

### Image driver and version

GD 8.2.10

### Installed plugins and versions

CKEditor - 4.0.x-dev

**Comment by brandonkelly** [comment]
Craft 5.0.0-alpha.3 is out with a fix for this. Thanks for reporting!
