### ISSUE TITLE
[5.0.0-alpha.2]: Preview missing in Craft Solo

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#14050]
### Description

The Preview/View buttons are missing in Craft Solo.

Craft 4:

![image](https://github.com/craftcms/cms/assets/60010597/52ed4771-fd64-4759-8eea-5d3ca55b5c76)

Same entry in Craft 5:

![image](https://github.com/craftcms/cms/assets/60010597/81f6a1a9-df03-4543-9eac-c1d8452b4963)

### Steps to reproduce

1. Edit an entry

### Expected behavior

Be able to preview the edited entry.

### Actual behavior

Nope.

/Klara

### Craft CMS version

Craft Solo 5.0.0-alpha.2

### PHP version

8.2.13

### Operating system and version

Linux 5.15.133.1-microsoft-standard-WSL2

### Database type and version

MySQL 8.0.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

None

**Comment by bencroker** [comment]
The View button has been moved into the bredcrumb bar, see https://github.com/craftcms/cms/pull/13902. 

The Preview button, however, is no longer appearing.

![Screenshot 2023-12-20 at 10 47 12](https://github.com/craftcms/cms/assets/57572400/c01837a5-cc6a-4ea8-9461-c6332c322720)

**Comment by brandonkelly** [comment]
Craft 5.0.0-alpha.3 is out with a fix for this. Thanks for reporting!

**Comment by wsydney76** [comment]
@brandonkelly Thanks, unfortunately not working on my side. 

Just done this:

1. Fresh install of alpha.3 as described in the [upgrade guide](https://pixelandtonic.notion.site/Craft-5-Plugin-Upgrade-Guide-df00b6c1c7604f47b0b8892e272eeeef)
2. Created a section: No Preview/View buttons
3. Switch to Craft Pro: Preview/View appear, pointing to the entry url, although no preview targets are defined.
4. Define some nonsense preview targets in the section setup: buttons do not respect this settings, still one preview target to entry  url.
5. Switch back to Solo: Now the preview targets defined in step 4 appear:
![image](https://github.com/craftcms/cms/assets/60010597/34285f19-b902-4b72-a4ef-0d5805854342)

Looks like the behaviors of Solo/Pro are reversed.

Suspect? https://github.com/craftcms/cms/blob/f695b783b21baec0be708c3b6f2effb116f4eb62/src/elements/Entry.php#L1138

/Karla

PS.
Slightly confused about having 
* a 'View in new tab' action in the breadcrumb bar (to entry url without preview tokens, so leading to 'page not found' for unpublished entry, or probably showing published content)
* the 'View' button (also opens a new tab, but with tokens)

Wording?

**Comment by brandonkelly** [comment]
Doh, thanks! This is now fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 5.0.0-alpha.4 is out with a fix for this. Thanks again!
