### ISSUE TITLE
[5.x]: Matrix field (card view mode) - JS error when selecting the menu 

### ISSUE THREAD

**Issue by magnessjo** [craftcms/cms#14059]
### Description

See attached for JS error

<img width="527" alt="Screenshot 2023-12-19 at 11 04 03 AM" src="https://github.com/craftcms/cms/assets/856595/f7bbb9b0-598e-4cd3-862c-6b24b35bcebf">

### Steps to reproduce

1. Create a section
2. Create an associated entry type
3. Create a field with CKEditor
4. Create a matrix field with the CKEditor field on it
5. Add matrix field to entry type created in step 2

Note: Currently, the ability to add a row is [broken](https://github.com/craftcms/cms/issues/14058); You need to toggle between view modes to inline block  to add the rows. 

### Expected behavior

Menu of options provided. 

### Craft CMS version

Craft Pro 5.0.0-alpha.2

### PHP version

8.2.10

### Operating system and version

MacOS 14

### Database type and version

MySQL 8.1.0

### Image driver and version

GD 8.2.10

### Installed plugins and versions

CKEditor - 4.0.x-dev

**Comment by brandonkelly** [comment]
Craft 5.0.0-alpha.3 is out with a fix for this. Thanks for reporting!
