### ISSUE TITLE
[5.x]: Unknown column in 'field list' on Craft 4 to Craft 5 migration

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#14067]
### Description
On updating craft 4 to craft 5, i got an error "Unknown column 'c.field_liveStart_**tz**_shgpxssk' in 'field list'".
the exact column name on craft 4 is field_liveStart_shgpxssk which is a date time field.
maybe not related but i have two custom element types which i try to migrate via craft\base\BaseContentRefactorMigration and this field is used on those custom element types layout and entries too.

### Craft CMS version

5.0.0-alpha.2

### PHP version

8.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that. Fixed now for the next release via 64f9b746bc70347380c77eaed8d4dac20605615a.

**Comment by brandonkelly** [comment]
Craft 5.0.0-alpha.3 is out with that fix. Thanks again!
