### ISSUE TITLE
migrations don't seem to run on fresh plugin install

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1406]
### Description

I have another question about state in Craft 3, consequent of what I was really trying to do including /vendor, but that is not relevant to this.

I completely freshened by composer remove and require the massive agent plugin. I had first backtracked its version code, while leaving the schema version where it was.

I then took out the plugins record, the single table previously installed, and the migration record from the Craft database. All the evidence, right?

[16:26]  
I then brought up the CP fresh, and installed the plugin. The migrations didn't run. That is a problem for user installs, because the added tables and a record need to be there. I used to do this with Records' create ability and the main plugin class's after-install hook, which seems to be missing, hence the migrations.

I know how to get the migrations to run -- up the composer.json version number, composer update, etc.. , push the result, and then Craft will call for an update dialog. But this is not the thing for a customer install.

### Steps to reproduce

1. as above
2.

### Additional info

PHP version	7.0.15-1+deb.sury.org~xenial+1
Database driver & version	MySQL 5.7.17-0ubuntu0.16.04.1
Image driver & version	GD 7.0.15-1+deb.sury.org~xenial+1
Craft edition & version	Craft Personal 3.0.0-beta.4
Yii version	2.0.11.1
Twig version	2.1.0
Guzzle version	6.2.1
Imagine version	0.7-dev
Plugins

Trimmer	1.0.0
Patrol	3.0.1
Bactrian	1.0.0
Minify	1.2.2
Standards Agent	2.0.4

**Comment by narration-sd** [comment]
Ok, the solution per Brandon of using a multipart Install.php migration worked a treat:  [https://github.com/craftcms/docs/blob/master/en/plugin-migrations.md#install-migrations](https://github.com/craftcms/docs/blob/master/en/plugin-migrations.md#install-migrations) .

I did notice one funny while clearing things out prior to re-installing the plugin.

It seems the prior install had entered the available migrations into the craft_migrations table, even though it had not apparently run them. 

Could be a bug?  Naturally I cleaned before, and the Install migration is in the table  after.

**Comment by narration-sd** [comment]
Also, the install ran or at least php compiled a Service, which failed and thus failed the install, at first. I corrected from web.log evidence, and then the installl ran fine.

Imagining this funny would be due to the way Services are now components according  to composer.json...

**Comment by brandonkelly** [comment]
To clarify, the only migration that should run when a plugin is installed is its [Install Migration](https://github.com/craftcms/docs/blob/master/en/plugin-migrations.md#install-migrations). Any other migrations that exist on the plugin at the time of installation should be ignored. The only non-Install migrations that should ever run on a given Craft project are any migrations that are added to the plugin *after* it was installed.

> It seems the prior install had entered the available migrations into the craft_migrations table, even though it had not apparently run them.

This is intended. When you install a plugin, Craft will A) run its Install migration (if there is one), and B) make a record of any non-Install migrations that existed on the plugin at that point in time. So in the future Craft will *think* it has already run those migrations, even though technically it hadn’t, and not attempt to “re”-run them.

**Comment by brandonkelly** [comment]
> Also, the install ran or at least php compiled a Service, which failed and thus failed the install, at first. I corrected from web.log evidence, and then the installl ran fine.
>
> Imagining this funny would be due to the way Services are now components according to composer.json...

Not sure I’m following you here. Plugin components (services) should be set on Plugins each time they are instantiated, even if they are in the process of being installed. If that wasn’t the case, can you create a new issue with whatever error you get (if any) and some example plugin code to demonstrate the bug?
