### ISSUE TITLE
[4.x]: Asset field is cleared after saving entry draft copy created from another site

### ISSUE THREAD

**Issue by birdkiwi** [craftcms/cms#14065]
### Description
Asset field is cleared after saving entry draft copy created from another site.

Video of demonstration: https://youtu.be/BYmDdkw7htM
[![Video](https://img.youtube.com/vi/BYmDdkw7htM/0.jpg)](https://www.youtube.com/watch?v=BYmDdkw7htM)

### Steps to reproduce

1. Create a channel section with `propagationMethod`: custom (Let each entry choose which sites it should be saved to)
2. Create asset field with `localizeRelations` setting turned on (Manage relations on a per-site basis)
3. Add asset field to section entry type, make it required
4. Add one more site
5. Create a test entry in this section on default site, fill asset field, save
6. Open the entry again, click "Add a site…" in the right sidebar and select another site
7. Switch to the new entry draft on that site. Asset field is already filled with the image, that's OK.
8. Press Save, reopen entry. Asset field is now empty!

### Expected behavior

Asset field shouldn't be cleared after saving draft.

### Actual behavior

Somehow assets relations are deleted from DB after saving draft. Unfortunately I don't have enough time to investigate further.

Craft 4.5.9 on video, also tested with 4.5.12 — behavior is the same.

### Craft CMS version

4.5.12

### PHP version

8.1.26

### Operating system and version

Docker (craftcms/nginx:8.1-dev)

### Database type and version

MySQL 8.0.30

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.1-13)

### Installed plugins and versions

Amazon S3	2.0.3
Blitz	4.7.1
CP Field Inspect	1.4.4
Dumper	3.0.1
Embedded Assets	3.1.8
ImageOptimize	4.0.5
Mailgun	3.0.0
Navigation	2.0.22
Retour	4.1.14
Sentry Logger	4.1.3
SEOmatic	4.0.33
Typed link field	2.1.5
Vite	4.0.6
Yournextagency Utilities	v1.0.24

**Comment by Romanavr** [comment]
Just to confirm I have the same issue

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.5.14 is out with that fix. Thanks again.
