### ISSUE TITLE
[5.x]: Matrix field (inline-block mode) - Nested fields silently fail to load a row

### ISSUE THREAD

**Issue by magnessjo** [craftcms/cms#14060]
### Description

Error when trying to add a row to a nested matrix field. 

### Steps to reproduce

1. Create a section
2. Create an associated entry type for the section
3. Create a field with CKEditor using the simple config
4. Create a field with CKEditor using another config
5. Create an entry type with the title enabled (level 1)
6. Create a matrix field based on the level 1 entry type
7. Create an entry type with the title disabled and the CKEditor fields (level 2)
8. Create a matrix field with the level 2 entry type
9. Assocate the matrix filed with the level 1 entry type. 

See attached for field type model example

<img width="732" alt="Screenshot 2023-12-19 at 11 38 38 AM" src="https://github.com/craftcms/cms/assets/856595/bebcc055-4442-4ff4-820d-52dc6e7fe943">

### Expected behavior

Row with associated field should appear 

### Actual behavior

Row doesn't appear

### Craft CMS version

Craft Pro 5.0.0-alpha.2

### PHP version

8.2.10

### Operating system and version

Mac 14.1

### Database type and version

MySQL 8.1.0

### Image driver and version

GD 8.2.10

### Installed plugins and versions

CKEditor - 4.0.x-dev

**Comment by brandonkelly** [comment]
Craft 5.0.0-alpha.3 is out with a fix for this. Thanks for reporting!
