### ISSUE TITLE
[5.0.0-alpha.3]: Can't create local volume: This filesystem has been reserved for temporary asset uploads.

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#14071]
### Description

Created a file system like this:

![image](https://github.com/craftcms/cms/assets/60010597/2265f5c8-7421-4db2-b87c-5e36db8ed783)

and tried to create a volume:

![image](https://github.com/craftcms/cms/assets/60010597/772c3ec5-9af2-410c-bdd5-e7094da8ce6d)

I saw the new `tempAssetUploadFs` config, however, the docs say 'A local temp folder will be used by default.', so I assume this is purely optional and should work without this setting?

/Karla

### Craft CMS version

Craft Solo 5.0.0-alpha.3

### PHP version

8.2.13

### Operating system and version

Linux 5.15.133.1-microsoft-standard-WSL2

### Database type and version

MySQL 8.0.33

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Have you set the `tempAssetUploadFs` config setting to that same volume’s handle? (Or an environment variable that refers to it?)

**Comment by wsydney76** [comment]
@brandonkelly No, there is no such setting in `general.php`. It's actually the unchanged config from the Craft 5 starter repo.

If I add `->tempAssetUploadFs('files')`, the file system is (as expected) not selectable when creating a volume.

**Comment by i-just** [comment]
Thanks for reporting! I just raised a PR to adjust this.

**Comment by brandonkelly** [comment]
We just released Craft 5.0.0-alpha.4 with the fix for this. Thanks again!
