### ISSUE TITLE
[5.x]: Feed Widget Title

### ISSUE THREAD

**Issue by magnessjo** [craftcms/cms#14079]
### Description

[commit ref](https://github.com/craftcms/cms/commit/3b2959ed730b9fe4bc66ae1cd78b353c70780926#diff-b51823c5d79db942c8775187077f31b47b7f5f61170e4b3e052e2de6217fda34) - I'm not sure if this is/was on purpose or not but wanted to report it so you know. 

<img width="359" alt="Screenshot 2023-12-28 at 3 07 55 PM" src="https://github.com/craftcms/cms/assets/856595/f41dc5af-a51b-48c5-ab41-68d3f37a4ac5">

### Craft CMS version

Craft 5 alpha 3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Doh, thanks for pointing that out! Fixed for the next release.
