### ISSUE TITLE
Switching from Structure to Channel and back again doesn't recreate structure elements.

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#1407]
### Description

See title

### Steps to reproduce

1. Create new structure
2. Publish entry
3. Change structure to channel
4. Entry will appear in channel
5. Change channel to structure
6. Entry doesn't appear in structure, entry appears in all entries, structureelements table is empty

### Additional info

- Craft version: Craft CMS 3.0.0-beta.4
- PHP version: 7.1

**Comment by narration-sd** [comment]
Leevi, if I've understood you, isn't this something that's always been verboten, with a warning?

I find the same warning on the Section page:

```
Section Type
What type of section is this?
Careful—changing this may result in data loss.
```

**Comment by brandonkelly** [comment]
@narration-sd That is mainly just there for converting Channels/Structures to Singles, where all but the first entry will be deleted.

**Comment by leevigraham** [comment]
@narration-sd @brandonkelly, I know you shouldn't do it but I'm pretty sure it worked in v2 (channels <-> structures).

We generally start with channels for content and then if the client requests sub-pages switch to a structure.

**Comment by narration-sd** [comment]
interesting -- note from Brandon on this, where the hurt comes.

If not in your case, a good thing to document once it works again, no?

**Comment by ahockemeyer** [comment]
Im running into this on craft 3.9
