### ISSUE TITLE
Need a way to customized filename when an asset is uploaded

### ISSUE THREAD

**Issue by aelvan** [craftcms/cms#1409]
As I talked to @andris-sevcenko about in the Craft slack, it would be really useful if it was possible to change the filename of an uploaded asset before it's saved to the db and written to the volume. Andris pointed out that this could be done with `EVENT_BEFORE_UPLOAD_ASSET`, if it wasn't for the fact that validation has already been done at that point, and that the `$uriPath` has been set.

To give a little (tiny) bit more context, I'm working on a custom Volume Type where I need to ensure that a jpg file has the extension `.jpg` in Craft, not `.jpeg`, `.JPG` or something.  Silly, I know.

**Comment by andris-sevcenko** [comment]
This is now doable in Craft 3.0 beta-8 with the use of `craft\elements\Asset::EVENT_BEFORE_HANDLE_FILE` event,
