### ISSUE TITLE
[4.x]: Monolog 3.x support

### ISSUE THREAD

**Issue by LeoWie93** [craftcms/cms#14099]
### Description
Not sure if this type of issue is the right way but ill try. Today we stumbled over the restriction that Craft requires Monolog `^2.3`. One of our custom packages requires Monolog `^3.x`

Are their plans to update to Monolog 3 soon or are their topics/discussions that oppose this support?

### Craft CMS version

4.5.14

### PHP version

8.2

### Operating system and version

Linux

### Database type and version

MYSQL 8

**Comment by i-just** [comment]
Hi, thanks for getting in touch! Monolog 3 requires PHP 8.1, and Craft CMS 4 has a minimum requirement of 8.0.2. 
We’ll review updating it for Craft 5, though!
