### ISSUE TITLE
[4.x]: DateTimeHelper nextYear/lastYear typo

### ISSUE THREAD

**Issue by d--j** [craftcms/cms#14109]
### Description

https://github.com/craftcms/cms/blob/5e7e66d22c305284b8ebcc261a8f434f65a6fba3/src/helpers/DateTimeHelper.php#L462-L477

These functions should call `thisYear` instead of `thisMonth`.

### Craft CMS version

Craft Pro 4.5.14

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.5.15 and 4.6.0 are out with that fix. Thanks again!
