### ISSUE TITLE
[5.x]: Nested Matrix field conditionals 

### ISSUE THREAD

**Issue by magnessjo** [craftcms/cms#14101]
### Description

Dropdown field conditional logic doesn't work when fields are nested.  Could be a duplicate of [ticket](https://github.com/craftcms/cms/issues/13772) - but that is tagged as Craft 4

### Steps to reproduce

1. Create a section (test)
2. Create two different field types that aren't dropdowns (for example, plain text and checkbox)
3. Create two dropdown field types 
4. Configure entry type so dropdowns control the visibility (requirement) of the field type. 

### Expected behavior

Conditional fields will dynamically change based on conditional logic. 

### Actual behavior

User needs to save the component and reopen it. 

### Visual Example 

<img width="611" alt="Screenshot 2024-01-03 at 12 43 36 PM" src="https://github.com/craftcms/cms/assets/856595/958dfd29-0ef4-4d3f-88e3-f1109c7ff975">

### Craft CMS version

Craft 5 - Alpha 4

### PHP version

8.2.10

### Operating system and version

Mac 14.1

### Database type and version

MySQL 8.1.0

### Installed plugins and versions

-

**Comment by thupsi** [comment]
@wmdhosting The roadmap item in your screenshot refers to https://github.com/craftcms/cms/discussions/11287, so not actually related to the issue here.

**Comment by wmdhosting** [comment]
OK: thx for info..

**Comment by brandonkelly** [comment]
Craft 5.0.0-alpha.9 was just tagged, with live conditional field support :tada:
