### ISSUE TITLE
SQL/Server Error on "Require a password reset on next login"

### ISSUE THREAD

**Issue by marjorg** [craftcms/cms#1411]
### Description
I get an Internal Server Error when trying to use the "Require a password reset on next login". Tested on both localhost and a remote server with three different Craft 3 installations. Two were installed on localhost and then uploaded to remote host, the other were installed directly on the remote server.

Full debug console error: http://pastebin.com/raw/86Ld6tmm

### Steps to reproduce

1. Go to a user
2. Check "Require a password reset on next login" and save
3. Error appears

### Additional info
Local/Remote
- Craft version: Craft CMS 3.0.0-beta.4 & Craft CMS 3.0.0-beta.3
- PHP version: 7.0.13 & 7.0.16
- Database driver & version: MySQL 5.6.34 & MySQL 5.7.10
- Plugins & versions: None

**Comment by takobell** [comment]
Fixed in https://github.com/craftcms/cms/commit/f64a4d7c41667f1855520bc555277fc5447c63d6.   Thanks!
