### ISSUE TITLE
[4.x]: Assets "Default Upload Location" UI not working as before

### ISSUE THREAD

**Issue by degraaf** [craftcms/cms#14112]
### Description

As per Craft 3 issue #2778. The Default Upload Location is no longer opening the asset modal to the configured volume/path but is loading the last known location.

We've been on Craft 4 for some time but a client has noticed the asset modals with dynamic paths no longer open in the expected location.

### Steps to reproduce

1. Create an asset field and set a dynamic Default Upload Location (e.g. based on entry slug)
2. Add to existing entry type
3. Create/edit an entry
4. Open select asset modal

### Expected behavior

Should open to the volume/path configured for the field

### Actual behavior
 
Opens to the previous folder location that was used (e.g. on different entry)

EDIT.. noticed a local storage setting that appears to be taking precendence `Craft...BaseElementIndex.craft\elements\Asset.modal`
When localStorage is cleared, the modal opens to the default location, but local storage setting is used from that point.

### Craft CMS version

4.5.6.1

### PHP version

8.1.13

### Operating system and version

Linux 6.4.16-linuxkit

### Database type and version

MariaDB 10.7.3

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-52)

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Craft 4.5.15 and 4.6.0 are out with a fix.
