### ISSUE TITLE
[4.x]: [web.ERROR] [yii\db\Exception] SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction

### ISSUE THREAD

**Issue by DTesch-Reem** [craftcms/cms#14113]
### Description
When updating an Entry, with lots of Neo fields (with children), via a mutation I get this error:
[web.ERROR] [yii\db\Exception] SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction

It happens mainly when making the request twice, before the initial request is finished.

Edit: It happens only when the session component is set to redis-Driver.
Edit: It also happens when I call the GraphQL Endpoint from my Nuxt-App.

### Steps to reproduce

1. GraphiQL Playground
2. Set session component to redis-Driver.
3. Mutate/Update an entry with lots of Neo fields (with children)
4. Hit the play button 2-3 times fast
5. Error: [web.ERROR] [yii\db\Exception] SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction
6. The process/lockfile seems to only get released when I restart the server

### Expected behavior

Saving the entry after lock file releases.

### Actual behavior
[web.ERROR] [yii\db\Exception] SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction

### Craft CMS version

4.5.14

### PHP version

8.0.11

### Operating system and version

Unix

### Database type and version

mysql 8

### Installed plugins and versions

- Neo 4.0.2

**Comment by brandonkelly** [comment]
Can you post the full stack trace for the error? (It should be in `storage/logs/web-XXXX-XX-XX.log`.)

**Comment by DTesch-Reem** [comment]
> Can you post the full stack trace for the error? (It should be in `storage/logs/web-XXXX-XX-XX.log`.)

2024-01-08 06:53:26 [web.ERROR] [PDOException] PDOException: SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction in /var/www/html/backend/vendor/yiisoft/yii2/db/Command.php:1302
Stack trace:
#0 /var/www/html/backend/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /var/www/html/backend/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('INSERT INTO `ch...')
#2 /var/www/html/backend/vendor/craftcms/cms/src/helpers/Db.php(1053): yii\db\Command->execute()
#3 /var/www/html/backend/vendor/craftcms/cms/src/services/Elements.php(3522): craft\helpers\Db::upsert('{{%changedfield...', Array)
#4 /var/www/html/backend/vendor/craftcms/cms/src/services/Elements.php(1097): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false, true, Array, false, false)
#5 /var/www/html/backend/vendor/craftcms/cms/src/gql/base/ElementMutationResolver.php(163): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#6 /var/www/html/backend/vendor/craftcms/cms/src/gql/resolvers/mutations/Entry.php(85): craft\gql\base\ElementMutationResolver->saveElement(Object(craft\elements\Entry))
#7 /var/www/html/backend/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(623): craft\gql\resolvers\mutations\Entry->saveEntry(NULL, Array, Array, Object(GraphQL\Type\Definition\ResolveInfo))
#8 /var/www/html/backend/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(550): GraphQL\Executor\ReferenceExecutor->resolveFieldValueOrError(Object(GraphQL\Type\Definition\FieldDefinition), Object(GraphQL\Language\AST\FieldNode), Array, NULL, Object(GraphQL\Type\Definition\ResolveInfo))
#9 /var/www/html/backend/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(474): GraphQL\Executor\ReferenceExecutor->resolveField(Object(GraphQL\Type\Definition\ObjectType), NULL, Object(ArrayObject), Array)
#10 /var/www/html/backend/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(857): GraphQL\Executor\ReferenceExecutor->GraphQL\Executor\{closure}(Array, 'save_angebote_d...')
#11 [internal function]: GraphQL\Executor\ReferenceExecutor->GraphQL\Executor\{closure}(Array, 'save_angebote_d...')
#12 /var/www/html/backend/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(859): array_reduce(Array, Object(Closure), Array)
#13 /var/www/html/backend/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(490): GraphQL\Executor\ReferenceExecutor->promiseReduce(Array, Object(Closure), Array)
#14 /var/www/html/backend/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(263): GraphQL\Executor\ReferenceExecutor->executeFieldsSerially(Object(GraphQL\Type\Definition\ObjectType), NULL, Array, Object(ArrayObject))
#15 /var/www/html/backend/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(215): GraphQL\Executor\ReferenceExecutor->executeOperation(Object(GraphQL\Language\AST\OperationDefinitionNode), NULL)
#16 /var/www/html/backend/vendor/webonyx/graphql-php/src/Executor/Executor.php(156): GraphQL\Executor\ReferenceExecutor->doExecute()
#17 /var/www/html/backend/vendor/webonyx/graphql-php/src/GraphQL.php(162): GraphQL\Executor\Executor::promiseToExecute(Object(GraphQL\Executor\Promise\Adapter\SyncPromiseAdapter), Object(GraphQL\Type\Schema), Object(GraphQL\Language\AST\DocumentNode), NULL, Array, Array, 'editAngebot', NULL)
#18 /var/www/html/backend/vendor/webonyx/graphql-php/src/GraphQL.php(94): GraphQL\GraphQL::promiseToExecute(Object(GraphQL\Executor\Promise\Adapter\SyncPromiseAdapter), Object(GraphQL\Type\Schema), 'mutation editAn...', NULL, Array, Array, 'editAngebot', NULL, Array)
#19 /var/www/html/backend/vendor/craftcms/cms/src/services/Gql.php(514): GraphQL\GraphQL::executeQuery(Object(GraphQL\Type\Schema), 'mutation editAn...', NULL, Array, Array, 'editAngebot', NULL, Array)
#20 /var/www/html/backend/vendor/craftcms/cms/src/controllers/GraphqlController.php(195): craft\services\Gql->executeQuery(Object(craft\models\GqlSchema), 'mutation editAn...', Array, 'editAngebot', true)
#21 [internal function]: craft\controllers\GraphqlController->actionApi()
#22 /var/www/html/backend/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#23 /var/www/html/backend/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#24 /var/www/html/backend/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('api', Array)
#25 /var/www/html/backend/vendor/craftcms/cms/src/web/Application.php(305): yii\base\Module->runAction('graphql/api', Array)
#26 /var/www/html/backend/vendor/craftcms/cms/src/web/Application.php(606): craft\web\Application->runAction('graphql/api', Array)
#27 /var/www/html/backend/vendor/craftcms/cms/src/web/Application.php(284): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#28 /var/www/html/backend/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#29 /var/www/html/backend/web/index.php(12): yii\base\Application->run()
#30 {main} {"memory":29989184,"exception":"[object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction at /var/www/html/backend/vendor/yiisoft/yii2/db/Command.php:1302)"} 

Is this enough?

**Comment by DTesch-Reem** [comment]
That was fast.

Thank you! 😃

**Comment by brandonkelly** [comment]
Craft 4.5.15 and 4.6.0 are out with a fix for that: now we ensure the entire element save process is protected by a mutex lock, like we do for non-GraphQL save requests already.

Thanks for reporting!
