### ISSUE TITLE
“Unknown error” in Control Panel

### ISSUE THREAD

**Issue by alambc** [craftcms/cms#1412]
### Description
I am having an odd issue with craft, when I am navigating the admin panel or making an update for that matter, i usually get an "Unknown error" flashing at the top, when that occurs my index page crashes, all the other pages work fine but the index doesn't load, unless i go to http://website.com/index

Below is the track trace, note there are tons of these with errors this is just one of them. 

```
2017/02/22 17:15:54 [error] [exception.Craft\HttpException.404] exception 'Craft\HttpException' in /home/site/public_html/system/craft/app/controllers/TemplatesController.php:59
Stack trace:
#0 [internal function]: Craft\TemplatesController->actionRender('403.shtml', Array)
#1 /home/site/public_html/system/craft/app/framework/web/actions/CAction.php(109): ReflectionMethod->invokeArgs(Object(Craft\TemplatesController), Array)
#2 /home/site/public_html/system/craft/app/framework/web/actions/CInlineAction.php(47): CAction->runWithParamsInternal(Object(Craft\TemplatesController), Object(ReflectionMethod), Array)
#3 /home/site/public_html/system/craft/app/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/site/public_html/system/craft/app/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/site/public_html/system/craft/app/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/site/public_html/system/craft/app/framework/web/CWebApplication.php(282): CController->run('render')
#7 /home/site/public_html/system/craft/app/framework/web/CWebApplication.php(141): CWebApplication->runController('templates/rende...')
#8 /home/site/public_html/system/craft/app/etc/web/WebApp.php(290): CWebApplication->processRequest()
#9 /home/site/public_html/system/craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
#10 /home/site/public_html/system/craft/app/index.php(62): CApplication->run()
#11 /home/site/public_html/index.php(19): require_once('/home/site...')
#12 {main}
REQUEST_URI=/
```

### Additional info

- Craft version: 2.6.2961

**Comment by takobell** [comment]
This will end up being a hosting environmental issue.  Craft doesn't have a `403.shtml`, but some hosts will automatically try to redirect to a `errorStatusCode.shtml` file when an underlying error occurs, whether it's generated from the web server or from an application (like PHP/Craft).  That `403.shtml` file gets picked up by Craft routing, Craft sees it doesn't exist, then throw the 404 that you're seeing.

Check your web server's log files for the underlying error message and/or contact your host and let them know the behavior you're seeing.  Maybe they have a way to stop this auto-redirect to error template from happening to begin with.

**Comment by narration-sd** [comment]
Great thinking, Brad. This has been a continuing annoyance, though not in any way critical.

I’ll have a look and find it, thanks.

 

Thinking ‘great’ over and over as I convert UI, accesses to Elements, etc., on C3…

 

C.

**Comment by alambc** [comment]
The issue turned out to be a template stalled caching issue, resolved by doing the following:
https://craftcms.com/support/stuck-tasks
