### ISSUE TITLE
[4.x]: Calling unknown method: craft\models\FieldLayout::getFields() on users/save-user from the CP

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#14123]
### Description
When creating a new user in the CP via `/admin/users/new`, I am encountering the following error:

```
Twig Runtime Error – [Twig\Error\RuntimeError](http://twig.sensiolabs.org/api/2.x/Twig/Error/RuntimeError.html)
Calling unknown method: craft\models\FieldLayout::getFields() in "__string_template__9e1e754f05d83ae28ec00638f3807f6d" at line 10
```

However, I am in the CP and do not have any events that call `getFields`.

I have executed `project-config/apply`, `project-config/rebuild`, `utils/fix-field-layout-uids/index`, and `utils/repair/project-config` just in case, but without success.

### Craft CMS version

4.5.11.1

### PHP version

8.1.0

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch!

Can you please try clearing caches, either via `clear-caches/all` or Control Panel > Utilities > Caches? If that doesn’t help, can you please post the full stack trace from the logs?

**Comment by i-just** [comment]
Thanks for all the info! `craft\models\FieldLayout::getFields()` has been renamed to `getCustomFields().`

There’s also `getVisibleCustomFields()`, which returns the visible custom fields included in the layout, taking conditions into account.

I hope this helps!
