### ISSUE TITLE
Using PostgreSQL, setting a Rich Text field's column type to "mediumtext" throws a database exception

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#1413]
### Description

> SQLSTATE[42704]: Undefined object: 7 ERROR: type "mediumtext" does not exist
The SQL being executed was: ALTER TABLE "content" ALTER COLUMN "field_richText" TYPE mediumtext

This is because there is no concept for medium or long text in PostgreSQL.  There is `text` which is an unlimited length data type.

That setting should just be hidden/removed for PostgreSQL installs.

### Steps to reproduce

1. Use PostgreSQL.
2. Create a Rich Text field with the column type set to "mediumtext".
3. Save.
4. Weep for humanity.

### Additional info

- Craft version: 3.x
- PHP version: 7.x
- Database driver & version: PostgreSQL 9
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
This was resolved by 1b1f48d0d40f18e7e1cbd82cc32f37effc7658de.
