### ISSUE TITLE
[4.6]: Dropdown Options inside a Table field are not saved

### ISSUE THREAD

**Issue by tommysvr** [craftcms/cms#14134]
### Description

Dropdown Options inside a Table are not saved since upgrading to 4.6

### Steps to reproduce

1. Create a Table field with one column being a Dropdown field
2. Add Dropdown Options -> Done
3. Save Table field
4. View Droption Options, which will be empty

### Expected behavior
Dropdown Options are saved

### Actual behavior
Dropdown Options are not saved

![screenshot_2024_01_15 _09 48](https://github.com/craftcms/cms/assets/867566/3a7872f5-a659-4222-a045-c98ae51d2ed2)

### Craft CMS version

4.6

### PHP version

8.2

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi Tommy! It looks like they are being saved but are not displayed back. I’m looking into it.

**Comment by brandonkelly** [comment]
That was a pretty tricky one, so I spared you @i-just :)

**Comment by i-just** [comment]
Much appreciated @brandonkelly! :)

**Comment by brandonkelly** [comment]
Craft 4.6.1 is out now with that fix.
