### ISSUE TITLE
[4.x]: Migration::renameTable does not take into account custom db

### ISSUE THREAD

**Issue by ryssbowh** [craftcms/cms#14131]
### Description

When running a migration that renames a table on a db that is not the default one, the db is not taken into account and it fails.

The db is not passed as a parameter to `craft\helpers\Db::renameTable` in https://github.com/craftcms/cms/blob/develop/src/db/Migration.php#L391C28-L391C28

### Steps to reproduce

1. Create a new custom connection
3. Create a new migration that uses that connection
4. Rename a table in that migration

### Expected behavior

Table is renamed in the specified db

### Actual behavior

Getting a db error saying the table being renamed doesn't exist.

### Craft CMS version

4.5.14

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by ryssbowh** [comment]
I may have to get that fix sooner than the release date, could you let me know what version I should require in composer ?

**Comment by brandonkelly** [comment]
No need, Craft 4.5.1 is out with that fix now :)
