### ISSUE TITLE
[5.x]: Asset thumbnails are stacked when inside asset fields with "display as large thumbnail" mode 

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#14138]
### Description
Asset thumbnails are stacked when inside asset fields with "display as large thumbnail" mode 

### Steps to reproduce

1. Create an asset field and select the  "display as large thumbnail" mode"
2. Assign this field to an entry type
3. Create an entry with this entry type.
4. Add some assets to this field.

### Expected behavior
The asset thumbnails should fit in rows according to available space.

### Actual behavior
The asset thubmnails display stacked (one below the other).

![image](https://github.com/craftcms/cms/assets/19857599/ab59c843-45eb-4199-b46b-c0f68a2ee029)

### Craft CMS version

Craft CMS 5.0.0-alpha.5

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR to adjust this.

**Comment by brandonkelly** [comment]
Craft 5.0.0-alpha.7 is out now with a fix for this. Thanks again!
