### ISSUE TITLE
[4.x]: Custom element source labels are not translated in the CP

### ISSUE THREAD

**Issue by yoannisj** [craftcms/cms#14137]
### Description

The labels of element sources created via the control-panel are not translated to the user's preferred language. I am reporting this a as bug because this is different from custom headings and native element sources, which seem to all be translated using the 'site' translation category.

### Steps to reproduce

1. Log into the CP and navigate to the /entries page
2. Click on the Gear icon under the sources list to create a custom source (selected conditions are irrelevant)
3. Click on the Gear icon under the sources list to create a custom source heading
3. Add a site translation for the new source's label and source heading in another language (for example german in `translations/de/site.php`).
3. Navigate to /myaccount in the CP, change your preferred language to that language (german in our case) and save
4. Navigate back to the /entries page

### Expected behavior

Both the custom source heading and the custom source label should be translated in the user's preferred language, as per the contents of `site/<language>.php` file.

### Actual behavior

Only the custom heading is translated. The custom source label is always displayed in the original language, i.e. whatever was entered when creating the source.

### Craft CMS version

4.5.13

### PHP version

8.2.11

### Operating system and version

Linux 5.10.124-linuxkit

### Database type and version

MariaDB 10.6.15

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- Date Range Field `3.0.1`
- Embedded Assets `3.1.9`
- Hyper `1.1.19`
- Imager X `4.2.3`
- Linkit `4.0.4.1`
- LJ Range Slider `4.0.1`
- Mailjet Adapter `1.0.4`
- Neo `3.9.11`
- Preparse Field `2.0.2`
- Retour `4.1.14`
- SEO `4.0.37`
- Vizy `2.1.14`
- Wordsmith `4.2.0`

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.6.1 is out with that fix.
