### ISSUE TITLE
[4.x]: pcntl missing from the system report

### ISSUE THREAD

**Issue by jeffreyzant** [craftcms/cms#14145]
### Description
Today I've spent a while debugging why the queue/listen command would not gracefully shutdown in combination with supervisor. As it turns out I was missing the pcntl extension. 

### Expected behavior
Might be nice if the Craft system report in the admin displays pcntl as a favourable extension.

### Actual behavior
There are no warnings or errors thrown and the dependency is not included in the system report. 

### Craft CMS version

4.5.13

### PHP version

8.3.1

### Installed plugins and versions

-

**Comment by angrybrad** [comment]
It looks like the `yii\queue\cli\Signal`class (which `queue/listen` ultimately uses) does use some `pcntl` methods if the extension exists and gracefully skips it if it doesn’t.

https://github.com/yiisoft/yii2-queue/blob/master/src/cli/Signal.php#L30

I don’t think this case warrants adding it as a new extension requirement, but we can certainly add a note/tip in the docs for this! https://craftcms.com/docs/4.x/queue.html#daemon

Will get that done.
