### ISSUE TITLE
[4.x]: Custom Field Module 

### ISSUE THREAD

**Issue by handplant** [craftcms/cms#14157]
### What happened?

I have built a custom checkboxGroup field. It is displayed correctly and also saved properly.
However, after saving, I receive the error message "Field name is invalid." As mentioned, after reloading the page, the data is saved correctly.

What could be the reason for this?

```
<?php
namespace webworker\fields;

use Craft;
use craft\base\ElementInterface;
use craft\fields\BaseOptionsField;
use craft\fields\data\MultiOptionsFieldData;
use craft\helpers\ArrayHelper;

class SectionsField extends BaseOptionsField
{
    public static function displayName(): string
    {
        return Craft::t('app', 'Sections');
    }

    public static function valueType(): string
    {
        return sprintf('\\%s', MultiOptionsFieldData::class);
    }

    protected bool $multi = true;

    public function useFieldset(): bool
    {
        return true;
    }

    public function inputHtml(mixed $value, ?ElementInterface $element = null): string
    {
        $sections = Craft::$app->sections->getAllSections();
        $options = array_map(
            function ($section) use ($value) {                 
                return [
                    'label' => Craft::t('site', $section->name),
                    'value' => $this->encodeValue($section->handle)
                ];
            },
            $sections
        );

        return Craft::$app->getView()->renderTemplate('_includes/forms/checkboxGroup.twig', [
            'describedBy' => $this->describedBy,
            'name' => $this->handle,
            'values' => $this->encodeValue($value),
            'options' => $options,
        ]);
    }

    protected function optionsSettingLabel(): string
    {
        return Craft::t('app', 'Sections Options');
    }
}
```

![Bildschirmfoto 2024-01-18 um 13 00 09](https://github.com/craftcms/cms/assets/2598962/8667b294-7b0e-4e04-8c82-b2d562d107d6)

### Craft CMS version

Craft Pro 4.6.1

### PHP version

8.2.14

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch! 

When you save a `BaseOptionsField` value, the selected values are validated against the options defined in the field itself (e.g. in Control Panel > Settings > Fields > {your field}). If there’s a mismatch, the “is invalid” error will be returned.

You can declare available options in the `__construct()` method. Something along the lines of:
```
public function __construct($config = []) 
{
    // TODO: change this to get the options that you actually want to be available for this field, 
    // e.g. all section names and handles (not translated and not encoded)
    $options = [
        [
            'label' => 'One',
            'value' => 'one',
        ],
        [
            'label' => 'Two',
            'value' => 'two',
        ],
    ];
    
    $config['options'] = $options;
    parent::__construct($config);
}
```
Then you should remove defining options from your `inputHtml()` and instead just render the template. Instead of calling `'options' => $options,`, you can call `'options' => $this->translatedOptions(true, $value, $element),` to get the labels translated and values encoded.

Hopefully, you’ll find this to be a helpful starting point.

I’ll close this now, but please let me know if you run into any further issues.

**Comment by handplant** [comment]
Ok, thank you. Now it's working.

However, I have another question. I don't want to output all sections, but only those for which the currentUser has viewEntries permissions! Unfortunately, `$user = Craft::$app->getUser()->getIdentity()` is not available in the constructor!

Is there a way to solve the problem elegantly? You're welcome in advance!

```
public function __construct($config = []) 
{
    $sections = Craft::$app->sections->getAllSections();
    $user = Craft::$app->getUser()->getIdentity();

    $filteredSections = array_filter($filteredSections, function ($section) use ($user) {
        return Craft::$app->userPermissions->doesUserHavePermission($user->id, "viewEntries:{$section->id}");
    });
    
    $options = array_map(
        function ($section) {
            return [
                'label' => $section->name,
                'value' => $section->handle,
            ];
        },
        $filteredSections
    );
    
    $config['options'] = $options;
    parent::__construct($config);
}
```

**Comment by i-just** [comment]
You could define all sections as valid options in the constructor, as you do now, and then filter them in the `inputHtml()`. That way, the user only sees and can choose the options they have access to. 

You could then enhance it further and add custom validation by implementing the `getElementValidationRules()` in your field’s class. It should return an array of rules, and a rule can be a closure. You can have a look at how CKEditor implements such validation here: https://github.com/craftcms/ckeditor/blob/main/src/Field.php#L201.

**Comment by handplant** [comment]
Thank you. Next issue. After that, I'll stop, I promise! :D

The following works for the admin but not for a user in another group, even though the permissions are correct, and the user can see the section and its entries in the CP sidebar.

`$currentUser = Craft::$app->getUser()->getIdentity();`

Neither
`$currentUser->can('viewEntries:{$section->uid}')`

nor
`Craft::$app->userPermissions->doesUserHavePermission($currentUser->id, "viewEntries:{$section->id}");`

**Comment by i-just** [comment]
In our first attempt, you seem to have used the wrong quotes. Use double quotes or change how you concatenate `viewEntries:` with the section’s uid, and it’ll work.

In the second one, you’ve used section `id`, and you should use the `uid`.

Hope this helps!

**Comment by handplant** [comment]
Thank you very much. I have now switched from `BaseOptionsField` to a regular `Field`, which makes it easier for me. Here's my functional field in case another PHP newbie needs something similar!

```
<?php
namespace webworker\fields;

use Craft;
use craft\base\ElementInterface;
use craft\base\Field;

class SectionsField extends Field
{
    public static function displayName(): string
    {
        return Craft::t('app', 'Sections');
    }

    public function getInputHtml($value, ElementInterface $element = null): string
    {
        $currentUser = Craft::$app->getUser()->getIdentity();
        $sections = Craft::$app->sections->getAllSections();
        
        $filteredSections = array_filter($sections, function ($section) {
            return strpos($section->handle, 'article') === 0;
        });
     
        $filteredSections = array_filter($filteredSections, function ($section) use ($currentUser) {
            return $currentUser->can("viewEntries:{$section->uid}");
        });

        $options = array_map(
            function ($section) {
                return [
                    'label' => $section->name,
                    'value' => $section->handle,
                ];
            },
            $filteredSections
        );      

        return Craft::$app->getView()->renderTemplate('_includes/forms/checkboxGroup.twig', [
          'describedBy' => $this->describedBy,
          'name' => $this->handle,
          'values' => $value,
          'options' => $options
      ]);
    }    
}
```
