### ISSUE TITLE
[4.x]: Entry listing page not loading

### ISSUE THREAD

**Issue by karthikkstar** [craftcms/cms#14155]
### Describe the bug

The following pages are not working after upgrading Craft 3.9.5 to Craft 4.6.0
admin/formie/forms?site=uk
admin/formie/submissions?site=uk

I noticed a console error.

> Uncaught SyntaxError: Invalid or unexpected token (at submissions?site=uk:1050:32)

`Craft.elementIndex = Craft.createElementIndex('verbb\\formie\\elements\\Form', $('#page-container'), {
        elementTypeName: 'Form',
        elementTypePluralName: '
Elements',
        context: 'index',
        storageKey: 'elementindex.verbb\\formie\\elements\\Form',
        criteria: Craft.defaultIndexCriteria,
        toolbarSelector: '#toolbar',
        defaultSource: null,
        defaultSourcePath: null,
        canHaveDrafts: false,
    });`
    
Whitespace added before the `elementTypePluralName: ' Elements'. `

![Screenshot from 2023-12-08 17-00-41](https://github.com/verbb/formie/assets/85233749/4d265ee2-a75f-4698-ba20-1fe15f64244e)

**NOTE**   Sent notifications and settings page is working fine.
   Same issue for the Workflow plugin (https://github.com/verbb/workflow)

### Steps to reproduce

After upgrading from  Craft 3.9.5 to Craft  4.6.0

### Expected behavior

 Should list all the entries

### Actual behavior
Getting JS error on page load

### Craft CMS version

Craft CMS Pro 4.6.0

### PHP version

8.1.27

### Operating system and version

Linux 5.4.0-120-generic

### Database type and version

MySQL 48

### Image driver and version

GD 8.1.27

### Installed plugins and versions

Amazon S3	2.0.3
AsyncQueue	3.1.1
Blitz Recommendations	2.1.3
Cloner	2.0.4
Control Panel Body Classes	2.3.0
Default Dashboard	2.0.1
Device Detect	2.0.1
Feed Me	5.3.0
Fetch	2.0.0-beta.1
Formie	2.1.2
GeoMate	2.1.1
Maps	4.0.4
Myproperties	1.8.7
Password Policy	4.1.0
Redactor	3.0.4
SEOmatic	4.0.37
Site Switcher	2.3.0
Social	3.0.0-beta.1
Sprig	2.7.3
Typed link field	2.1.5
Workflow	2.0.7

**Comment by i-just** [comment]
Hi, thanks for getting in touch! 

Like @engram-design, I also don’t quite see how this could happen (https://github.com/verbb/formie/issues/1654).

I can only trigger the same error if I manipulate the template file to not escape for `js`: https://github.com/craftcms/cms/blob/a1d75421115bcd7308d1648821c4f2afc506a09b/src/templates/_layouts/elementindex.twig#L68

and then add, e.g. `'Elements' => "\nElementy-app",` to `translations\app.php` file. But I cannot trigger this error without manipulating the `elementindex.twig` template.

Do you have any custom translations defined for this project?

**Comment by karthikkstar** [comment]
@i-just 
Following custom code in the translation file.
`<?php 
    return [
        'User saved.'=>"profile saved."
    ];`

After removing the translation file, Its working.
Thanks
