### ISSUE TITLE
[4.5.4]: Element source ordering on element indexes after switching a section from channel to structure

### ISSUE THREAD

**Issue by rob-baker-ar** [craftcms/cms#14158]
### Description

If an existing channel is converted to a structure (in the CMS interface with admin changes enabled) then the position of the element source (i.e. in this case: section name) does not change in the element source panel.

Looking at the source code, in this case, the element sources panel ordering is defined by the ordering in `config/project.yaml` under the `elementSources.craft\elements\Entry` key. Notice there are `type`s of `heading` and `type`s of `native`. When a section's type is changed as per this issue's title, the ordering of this project config key is not changed, the effect being the transitioned sections stays where it was instead of where it should be.

When clicked, the section otherwise behaves as a structure based one should.

### Steps to reproduce

1. Create several channel sections & a structure section
2. Change a channel to a structure
3. See the element index and the sections under the channel / structure headings

### Expected behavior

Position of section that transitioned to a structure should appear under the structure heading.

### Actual behavior

It still appears under the channel heading.

### Craft CMS version

4.5.4

### PHP version

N/A

### Operating system and version

N/A

### Database type and version

N/A

### Image driver and version

N/A

### Installed plugins and versions

N/A

**Comment by rob-baker-ar** [comment]
I should have added the manually adjusting the ordering in `config/project.yaml`, nudging the `dateModified` key on and syncing project config fixes the ordering, so if that could happen in code when a section transitions type, that would fix this.

**Comment by i-just** [comment]
Hi, thanks for getting in touch and all the details!

This is related to #12573 and #13275; you can find further explanation there. 

In a nutshell, once you’ve customised sources, we no longer follow the default behaviour of placing new sections under their type heading. Only once you customise your sources for entries, the `elementSources.craft\elements\Entry` key gets stored in the `project.yaml`. So, only if you haven’t customised your entry sources would your section have been moved under the Structures heading automatically.

I hope this clears things up.

I will close this now, but please feel free to reply if you have any more questions.
