### ISSUE TITLE
Inconsistent behavior with sections that have a space in the Entry URL format.

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#1416]
### Description

If you create a Single with a space anywhere in the Entry URL Format's settings, it will successfully save, but if you go to edit that single, it will never show up in the list.

If you create a Channel or a Structure with a space anywhere in the Entry URL Format's settings, it will successfully save _and_ you can create a new entry in them, but when you go to save, you are sent to a 404.

A space in the URI is technically valid, since it would just get `%20` encoded, so probably shouldn't be a validation fix when saving the section's settings.

### Steps to reproduce

1. Create a Single/Channel or Structure with a space anywhere in the Entry URL format.
2. Go to edit the entry.
3. If it's a Single, you can't. If it's a Channel or Structure, save a new one and hit a 404.

### Additional info

- Craft version: 3.x
- PHP version: n/a
- Database driver & version: n/a
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Also fixed via ee851685b0b3c5a57a4319757f82f0c2874ec5c4 and 2549afa1ff3ad6a9a30d74f741fab1797d908126
