### ISSUE TITLE
[4.x]: Issue with table prefix from cli migration tasks

### ISSUE THREAD

**Issue by seanconn** [craftcms/cms#14171]
### Description
Site connects to the database and yaml updates can be run successfully through the cms but migrations run in the command line fail to connect to db.
The table prefix is "ma_" and is stored as a variable in the .env and referenced in the config/db.php file.

### Steps to reproduce

1. Run craft updates through the cli with "php craft update craft" or run any other migrate task

### Expected behavior

Migration should occur

### Actual behavior
When I run a task that requires a migration through the cli (eg: updates) the updates seem to run normally until it reaches the point of migrating the db and then I get the message:

```
Exception 'yii\db\Exception' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydatabasename.cr_info' doesn't exist
The SQL being executed was: SELECT `version`
FROM `cr_info`
LIMIT 1'

in /var/www/vendor/yiisoft/yii2/db/Schema.php:676

Error Info:
Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'mydatabasename.cr_info' doesn't exist
)

Caused by: Exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydatabasename.cr_info' doesn't exist'
```

I have no idea where the cr_ prefix is coming from here as the database connection seems to work for every task other than migrate and even migration seems to work fine when it is done through the cms admin panel instead of the cli. I've cleared the storage and cpresources folders and rebuilt the site with composer install, I've run setup/db-creds again and the connect details worked and were re-added to .env but I still can't run migrations through the cli. I don't understand why the migrate command looks for a different table prefix than every other task performed by the site

### Craft CMS version

4.6.1

### PHP version

8.1.15

### Operating system and version

Debian GNU/Linux 11

### Database type and version

mysql 5.7

### Installed plugins and versions

-
Twigpack
4.0.0-beta.4

Super Table
3.0.12

SEOmatic
4.0.37

Redactor
3.0.4

Element API
3.0.1.1

**Comment by brandonkelly** [comment]
Check your `craft` executable file. You may be setting environment variables differently from there than web requests.

Ideally, `craft` and `web/index.php` should both mostly resemble the starter project:

- https://github.com/craftcms/craft/blob/main/craft
- https://github.com/craftcms/craft/blob/main/web/index.php

They should both be loading a [`bootstrap.php`](https://github.com/craftcms/craft/blob/main/bootstrap.php) file which centralizes the environment variable loading, etc., which will help avoid different configurations between CLI and web requests.

Is that the case for you?

**Comment by brandonkelly** [comment]
Try searching **Utilities** → **PHP Info** for `cr` and see if anything jumps out.

**Comment by seanconn** [comment]
Hi Brandon,

I found the source, we had added some code to the module.php and there was a migrate event there looking for cr_info table

Thanks

**Comment by brandonkelly** [comment]
Glad you found it!
