### ISSUE TITLE
[5.x]: Can't delete CKEditor rich text entry drafts in Matrix

### ISSUE THREAD

**Issue by mei-lu** [craftcms/cms#14176]
### Description
After creating multiple drafts of an entry type containing a rich text field used by a matrix field, there appears to be an error with deleting their contents "Invalid elementId param". This issue resolves upon refresh. I suspect that somehow the draft is somehow corrupted. It doesn't happen with every draft - the first one I select to be deleted works but the subsequent ones error.

After trying to delete
![image](https://github.com/craftcms/cms/assets/52755821/3587866d-fbd0-4bd1-b598-39412c60b414)

Double clicking on the draft to edit shows blank
![image](https://github.com/craftcms/cms/assets/52755821/594b3046-37ae-4b47-87c9-f16f6a97da70)

Entry type used by matrix
![image](https://github.com/craftcms/cms/assets/52755821/b8b56847-d4e9-451b-85cc-53717edce9d4)

### Steps to reproduce

1. Field: Create a Matrix field ("Matrix Field"), create a ckeditor rich text field ("Rich Text Field")
2. Entry: Create an entry type containing the "Rich Text Field" ("Entry Type A")
3. Putting it together: Add "Entry Type A" to the "Matrix Field", and use this entry type in a section
4. Create an entry ("My Entry") in the section and try to add a multiple rich text fields to it. Only add a title and don't save any of them, let them be drafts. I usually create 3 drafts.
5. Refresh "My Entry" and the drafts should appear
7. Try to delete the drafts

https://github.com/craftcms/cms/assets/52755821/e582aea5-3691-4e13-aac9-e0c7be5b7cd9

### Expected behavior

When an entry is created using the matrix field, it can be deleted successfully.

### Actual behavior
First deletion succeeds, but subsequent deletion fails with "Invalid elementId param". When clicking in to try and edit the rich text entry, it is blank. But the problematic rich text entry disappears upon refresh.

### Craft CMS version

5.0.0-alpha.6

### Installed plugins and versions

- CKEditor ^4.0

**Comment by brandonkelly** [comment]
Before I dig into this, do you mind updating to `5.0.0-alpha.8` and checking if the issue is resolved there? We fixed a couple bugs related to Matrix fields.

**Comment by mei-lu** [comment]
@brandonkelly Hi Brandon, I updated and this seems to have been resolved. Thank you!

**Comment by brandonkelly** [comment]
Awesome, thanks for testing!
