### ISSUE TITLE
[5.x]: Debug toolbar icon error

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/cms#14183]
### What happened?

When enabling the debug toolbar, the Craft logo can't be read from disk and produces an error.

Offending line is [here](https://github.com/craftcms/cms/blob/5.0/src/web/Application.php#L420)! Replacing the assignment of `$svg` with `rawurlencode(\craft\helpers\Cp::iconSvg('c-debug'));` appears to fix the issue.

### Craft CMS version

5.0.0-alpha.7

### PHP version

8.2.11

### Operating system and version

Docker/DDEV

### Database type and version

MySQL

**Comment by brandonkelly** [comment]
Doh thanks! 5.0.0-alpha.8 is out with a fix.
