### ISSUE TITLE
[5.x]: Plugin icons display oddly in the CP Settings page

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#14186]
### Description

The icons for SEOmatic & Retour (which have settings) display oddly in the CP Settings page:

<img width="1612" alt="Screenshot 2024-01-23 at 10 57 31 PM" src="https://github.com/craftcms/cms/assets/7570798/af0677ce-a802-42f0-b704-a8304b4ea104">

I'm pretty sure they displayed properly as of `craftcms/cms` `5.0.0-alpha.5`, or at least I don't recall noticing this prior to updating to `5.0.0-alpha.8`

Interestingly, they display fine on the Plugins page:

<img width="1612" alt="Screenshot 2024-01-23 at 10 58 19 PM" src="https://github.com/craftcms/cms/assets/7570798/915787ce-a1ef-4cd2-91ec-122fae0fbdaa">

### Steps to reproduce

1. Install SEOmatic 5.0.0-beta.2
2. Click on Settings in the Craft CP

### Expected behavior

The icons would display properly on the Settings page

### Actual behavior

The icons display as a blue solid-filled outline

### Craft CMS version

5.0.0-alpha.8

### PHP version

8.2

### Operating system and version

n/a

### Database type and version

n/a

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.1-13)

### Installed plugins and versions

- SEOmatic `5.0.0-beta.1`

**Comment by brandonkelly** [comment]
Thanks, fixed for the next release!
