### ISSUE TITLE
Numeric/percentage progress bar for Update Asset Indexes tool

### ISSUE THREAD

**Issue by JayBox325** [craftcms/cms#1418]
### Description

Could be quite nice to see a more descriptive progress bar. Such as `24%` or `12/348`.

<img width="267" alt="screen shot 2017-02-24 at 14 29 50" src="https://cloud.githubusercontent.com/assets/13233809/23307837/e621cbda-faa0-11e6-854e-8fab5201cf4e.png">

**Comment by timkelty** [comment]
Note: #2934 has a similar discussion

**Comment by brandonkelly** [comment]
Doh, should have marked that as a duplicate. Will close this one though, as the new one has more activity.
