### ISSUE TITLE
[5.x]: Error when deleting "draft" user element after navigation

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/cms#14199]
### What happened?

I tried deleting a "draft" user with the disclosure menu in the breadcrumbs after switching between tabs.

1. Navigate to `/admin/users`
2. Click **+ New user**
3. Move to a secondary tab like **Addresses** or **Permissions**
4. Open the breadcrumb disclosure menu and click **Delete draft**
5. Observe 400 error “Invalid element ID: `X`” from the `elements/delete-draft` controller

Seems like the `draftId` param getting dropped from the query string on the secondary pages causes the element actions to not submit all the required data?

### Craft CMS version

5.0.0-alpha.8

### PHP version

8.2.x

**Comment by brandonkelly** [comment]
Thanks! Fixed for the next release.
