### ISSUE TITLE
[4.x]: Can't set asset field value in EVENT_BEFORE_HANDLE_FILE when uploading from an entry

### ISSUE THREAD

**Issue by thomasjonas** [craftcms/cms#14209]
### Description

I want to extract metadata from a file before uploading it to a AWS S3 bucket. I use the `Asset::EVENT_BEFORE_HANDLE_FILE` hook to extract all the metadata. In assumed I could just use the `setFieldValue` function to save the metadata in some custom fields but I cannot get anything to work...

### Steps to reproduce

1. Create an asset type with a custom field `duration` (type number)
2. Create a new entry type that has a field where you can add the asset type from the previous step.
3. Create a plugin with the event hook (see code below)
5. Now, create a new entry and save it
6. In the saved entry, press the "Upload a file" button and upload a mp3 file
7. When it has finished uploading double click the asset so it will open in the sidebar

### Expected behavior

I would have expect the duration field to have the value 123. When you upload not from an entry, but directly from the assets page it actually works.

### Actual behavior

The duration field is empty when uploading an asset from an entry.

### Hook
```
Event::on(
            Asset::class,
            Asset::EVENT_BEFORE_HANDLE_FILE,
            function (AssetEvent $event) {
                $asset = $event->asset;
                if ($asset->extension === 'mp3' && $asset->tempFilePath) {
                    $asset->setFieldValue('duration', 123);
                }
            }
        );
```

### Craft CMS version

4.5.14

### PHP version

8.2.9

### Operating system and version

Linux 6.4.16-linuxkit

### Database type and version

PostgreSQL 14.9

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

Amazon S3	2.0.3
Cloudflare	2.0.2
Control Panel CSS	2.6.0
Enforce password	2.0.0
Feed Me	5.3.0
Formie	2.1.1
ImageOptimize	4.0.5
Jason	3.0.1
Mixed Data (JSON-backed fields)	4.0.0-beta.1
Navigation	2.0.24
NEMO specifics	dev-develop
Redactor	3.0.4
Reverse Relations	2.0.0
SEO	4.2.1
Super Table	3.0.12
Two-Factor Authentication	3.3.2
Workflow	2.0.7

**Comment by i-just** [comment]
Hi, thanks for reaching out! I’m having trouble replicating this problem. The `duration` custom field gets populated with the content even if I upload the file via the entry’s Assets field. Is it the exact same file you’ve tested with via the Assets page and an entry? The only thing I can think of right now is that maybe the extension isn’t exactly “mp3” in one of your tests? (Even having the extension uppercased would already cause the condition to fail.)

**Comment by thomasjonas** [comment]
@i-just Thank you so much for having a look at it! I just tried reproducing the issue on a clean Craft install, and much to my surprise it actually works. So there must be something else causing this problem. Sorry for opening this issue!
