### ISSUE TITLE
[5.x]: Entry-type dropdown overlaps with arrow

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#14203]
### Description

The dropdown arrow for the entry type switcher is overlapping the label
![image](https://github.com/craftcms/cms/assets/3810939/25f53307-5bea-41f2-8ff7-eb0309689126)

### Craft CMS version

5.0.0-alpha.8

**Comment by i-just** [comment]
Thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.0.0-alpha.9 was just released with a fix for this. Thanks again!
