### ISSUE TITLE
Fuzzy Searching in Craft 3

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#1420]
There were a lot of requests for fuzzy searching in Craft 2, and in response, you guys added the following to the config settings:

    'defaultSearchTermOptions' => array(
        'subLeft' => true,
        'subRight' => true,
    )

Which is awesome! Adding that exact code enables fuzzy searching across the CP.

**Would it be possible to make this the _actual_ default behavior in Craft 3?** As in, we wouldn't need to change the config settings to allow it?

I think far more people would expect searching to be naturally fuzzy.

**Comment by takobell** [comment]
Would you expect fuzzy searching on the left and right or just on the right?  Some quick Google testing seems to show they maybe they only do fuzzy on the right by default.

**Comment by lindseydiloreto** [comment]
That's interesting... I would expect both (I think).

I'm thinking more of an Algolia search (over Google). Their results are super fuzzy, even capturing typos and everything. Ultimately, I'd probably say "the more the merrier" for search results.

Curious if others feel differently.

**Comment by narration-sd** [comment]
might be tougher, but with a little thought, I would suspect both is the nicest answer. 

I've noticed various apps doing both recently, and appreciated it. With all the name spaghetti recently, sometimes you think of one part of a phrase, not the beginning.

And we know Craft wants to do the nicest things...

For those who feel more comfortable with right only, an option out of both default?

**Comment by AugustMiller** [comment]
I think we're talking about two different things… one being a simple default config option update, the other being an entirely new search algorithm. Partial-word matching is a whole different game from true "fuzzy searching." 😭

Unless I've misunderstood what these options do?

**Comment by narration-sd** [comment]
not sure the distinction you're trying to make -- between stem-basis and concept basis?

Craft may have a lot of concepts inside, but I don't think it goes as far as AI frames -- yet.

**Comment by lindseydiloreto** [comment]
To be clear, I'm not looking for a rewrite of the search engine. I don't need typo-detection (as cool as that would be). When I say "I'm thinking of Algolia", I simply mean a search engine which is willing to provide _more_ results, rather than _fewer_ results.

All I'm suggesting is that these values become the universal Craft default:

    'defaultSearchTermOptions' => array(
        'subLeft' => true,
        'subRight' => true,
    )

That's it. :)

**Comment by narration-sd** [comment]
and if we want Algolia, we bake it in -- Squarebit SearchPlus -- fine software both...

**Comment by lindseydiloreto** [comment]
Exactly, I've used Algolia on the front-end of several sites now, and the results are spectacular.

Baking Algolia into the CP would probably be an enormous undertaking... I don't expect anyone (not P&T, nor Squarebit) to take on that challenge any time soon.

**Comment by takobell** [comment]
Add your vote/thoughts to https://github.com/craftcms/cms/issues/833 if you'd like plugins to be able to swap out the search provider.  Definitely on our radar similar to how we added custom volume support for plugins in Craft 3.

**Comment by takobell** [comment]
Fixed in https://github.com/craftcms/cms/commit/17ba61e272c6eab2c6469e7b6ed712e255ce88b3.

Just did `subRight`, though. `subLeft` just seems weird as a default option.

**Comment by lindseydiloreto** [comment]
Brilliant, thanks @takobell!

I have mixed feelings about `subLeft` getting left out, but it's definitely an improvement. Thanks man!

**Comment by takobell** [comment]
@lindseydiloreto no doubt it's an infinitely more complex algorithm, but doing some random google searches, if you discount their "did you mean ..." corrections, it appears they favor subRight instead of subLeft.

**Comment by lindseydiloreto** [comment]
Fair enough, hard to argue against Google's search techniques.

I'm sure time will prove me wrong. :)
