### ISSUE TITLE
[5.x]: "Created At" field probably shouldn't be visible for empty drafts

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#14204]
### Description

When creating a brand new entry, the right-hand panel with details shows an ID, Created at, and Updated at

While this is technically valid, it's a little weird when nothing has been entered into the form - the only action taken was clicking "New entry". 

I don't feel strongly about this, it just stuck out to me as a little odd.

### Craft CMS version

5.0.0-alpha.8

**Comment by brandonkelly** [comment]
Agreed. Just released Craft 4.7.1 and 5.0.0-alpha.9 with “Created at” and “Updated at” removed for unpublished drafts.
