### ISSUE TITLE
[5.x]: Plugin development: `getContentColumnType()` -> `dbType()` condundrum

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#14225]
### Description

This is a Craft 4 -> Craft 5 plugin porting question, not a bug.

The [Code Field](https://github.com/nystudio107/craft-code-field) plugin mimicked what Craft did in the PlainText field, in that if you were using MySQL, it would let you pick from `text` or `mediumtext` for the content column type, so that if you had a huge amount of code you wanted to dump into it, it'd work.

Therefore, the `getContentColumnType()` method would [return a value based on the field settings](https://github.com/nystudio107/craft-code-field/blob/develop-v4/src/fields/Code.php#L259) for the content column type.

The [Craft 5 Plugin Upgrade Guide](https://pixelandtonic.notion.site/Craft-5-Plugin-Upgrade-Guide-df00b6c1c7604f47b0b8892e272eeeef) says to change `getContentColumnType()` to the `static` method `dbType()` which is fine but... since it's a static method, it can't access the non-static properties that are the field settings.

For guidance on what to do here, I looked at the Craft 5 `PlainText` field, but it doesn't override the `static` method `dbType()` at all, which left me scratching my head.

I also searched the entire Craft 5 codebase on `mediumtext` but only saw it used in a scant few places so...

* Are you just no longer supporting `mediumtext`, `longtext` and other MySQL-specific text column types in favor of just `Schema::TYPE_TEXT` given that the `PlainText` field has settings for it?
* Or does the version of MySQL that is now required for Craft 5 simply have much larger `TEXT` column types by default?
* Are settings-based (or otherwise dynamic) values implicitly no longer allowed for the `dbType()` since it's a `static` method that can't access its own public properties (settings)?

### Craft CMS version

5.0.0-alpha.8

### PHP version

8.2

### Operating system and version

n/a

### Database type and version

MySQL 8.0.32

### Image driver and version

n/a

### Installed plugins and versions

n/a

**Comment by khalwat** [comment]
@engram-design made me realize I was thinking about this wrong.

Because there's no actual db column anymore, but rather just a field in a JSON blob (for which the column is presumably massive), this is all a moot point.

Closing her up!

**Comment by brandonkelly** [comment]
Yep! The only reason that was an instance method was because the column type might differ depending on settings. In v5 there’s just `dbType()` which is there to help optimize the scalar JSON queries; not used when actually storing the values.
