### ISSUE TITLE
[5.x]: Error renaming plaintext handles in globals

### ISSUE THREAD

**Issue by mei-lu** [craftcms/cms#14221]
### Steps to reproduce

1. Create a new global and add a plaintext field to it
2. Try to rename the handle of the plaintext field
3. Save

### Expected behavior

Save without error

### Actual behavior

Invalid field handle: myNewHandle

### Craft CMS version

Craft Pro 5.0.0-alpha.8

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.0.0-alpha.9 was just released with a fix for this. Thanks again!
