### ISSUE TITLE
[5.x]: Matrix, Entries and Assets fields not multi-instance

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#14237]
### Description
I'm not sure if this is currently a known limitation, but as of `5.0.0-alpha.9`,  "Matrix", "Entries" and "Assets" fields can only be included once in a field layout.

### Craft CMS version

5.0.0-alpha.9

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
This is expected. Only fields that store content in the main `content` column can be multi-instance.

**Comment by thupsi** [comment]
Ah, ok, makes sense! Thanks for clarifying!
