### ISSUE TITLE
[4.x]: Chromium browsers rendering thumbnails at low resolution

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#14244]
### Description

Chrome and Edge on windows always use the lowest resolution source in thumbnails (120px vs 240px), resulting in blurry asset thumbs, even on high res screens.

This happens everywhere where thumbnails are used (and also in card view thumbnail images in Craft 5).

Firefox behaves as expected, choosing the high res source where appropriate.

Have yet to test this in Safari iOS, I will update probably later today.

Update: Safari iOS also behaves as expected.

Comparison of Chrome (left) vs Firefox (right):

![image](https://github.com/craftcms/cms/assets/19857599/e46a9e40-025c-4361-82a3-c0a41d9518f5)

### Craft CMS version

Craft 4.6.1

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

**Comment by thupsi** [comment]
Upon further investigation it appears to be a "feature" of Chromium, that manifests under certain scaling and zoom settings. When I change my scaling to a larger percentage, or zoom in the browser, the higher resolution source is loaded. It is annoying though, because I can clearly see the difference at my (windows recommended) scaling.

Anyway, I'm closing this and will update if I can come up with any meaningfull recommendation/fix.

**Comment by brandonkelly** [comment]
Well that’s gross. Thanks for looking into it.
