### ISSUE TITLE
[5..alpha.9]: Custom field values not displayed in element index if handle was changed

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#14245]
### Description

Values from fields with changed handles are not display in entries index:

![image](https://github.com/craftcms/cms/assets/60010597/b9d320da-b8d9-4a6e-9652-d994114bb728)

### Steps to reproduce

1. Create generic fields like singleLineText
2. Select them in an entry type, change name + handle
3. Select those fields in entries index

### Expected behavior

Should show values.

### Actual behavior

Does not

### Craft CMS version

Craft Solo 5.0.0-alpha.9

### PHP version

8.2.13

### Operating system and version

Linux 5.15.133.1-microsoft-standard-WSL2

### Installed plugins and versions

none

**Comment by brandonkelly** [comment]
Thanks for reporting that! 5.0.0-alpha.10 was just tagged with a fix.
