### ISSUE TITLE
[4.5.15]: Delayed logging and high memory usage in Console Controller

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#14242]
### Description
I'm experiencing issues with delayed logging and high memory usage in a Craft CMS console controller. The issue arises while handling a large feed with over 40,000 elements, segmented into pages of 5 elements each. The logs are only written after the entire script execution is complete, leading to inaccurate timestamps and excessive memory consumption. In cases where the script is abruptly stopped, no logs are recorded.

### Steps to Reproduce
1. Create a console controller in Craft CMS `4.5.15`.
2. The controller fetches JSON data from an external Element API.
3. Use `do { while }` for pagination and `foreach` for processing the data.
4. During and after the script execution, observe issues with delayed logging and memory usage.

### Expected Behavior
I expected the logs to be written immediately or at more frequent intervals for accurate timestamping. Additionally, the memory usage should be optimized to handle the high volume of data without causing controller crashes.

### Actual Behavior
The actual behavior observed was a significant delay in log writing, resulting in inaccurate timestamps. If the script execution was interrupted, no logs were recorded at all. When processing the large volume of elements, the high memory usage led to crashes of the controller.

### Question
I'm aware of the `reset()` function in Monolog, for handling long-running processes and avoiding memory leaks ([Monolog documentation](https://github.com/Seldaek/monolog/blob/main/doc/01-usage.md#long-running-processes-and-avoiding-memory-leaks)), that maybe could help. Is there a similar functionality available in Craft CMS that can help in managing log writing more effectively?

### Code Sample
```
<?php

use yii\helpers\Console;
use yii\console\ExitCode;

public function actionImport($url, $page = 1)
{
    $client = new \GuzzleHttp\Client();
    $maxAttempts = 10;

    do {
        $currentAttempt = 0;
        $apiUrl = "{$url}?page={$page}";

        do {
            try {
                $response = $client->get($apiUrl);
                $data = json_decode($response->getBody(), true);

                $meta = $data['meta'];
                $pagination = $meta['pagination'];

                // Verify 'data' node in response
                if (isset($data['data']) && is_array($data['data'])) {
                    foreach ($data['data'] as $item) {
                        $this->stdout($data['title']."\n");
                    }
                }

                Craft::info([
                    'message' => "Page {$page} finished"
                ], 'migration');

                // Update the page for pagination
                $page++;

                // Update the loop condition to exit the loop
                $currentAttempt = $maxAttempts;
                break; // Exit the attempt loop on success
            } catch (\GuzzleHttp\Exception\RequestException $e) {
                $currentAttempt++;

                // Pause before retry
                if ($currentAttempt == 1) {
                    sleep(10);
                } else if ($currentAttempt > 1 && $currentAttempt <= 5) {
                    sleep(60);
                } else {
                    sleep(300);
                }

                if ($currentAttempt >= $maxAttempts) {
                    // Return the error in the console
                    $message = "Error encountered on page {$page} after {$maxAttempts} attempts: " . $e->getMessage();
                    $this->stderr("{$message}\n", Console::FG_RED);

                    // Save error to log file
                    Craft::error([
                        'message' => $message
                    ], 'migration');

                    // Break loop to process next page
                    break;
                }
            }
        } while ($currentAttempt < $maxAttempts);

    } while (isset($pagination['links']['next']) && !empty($pagination['links']['next'])); // Check for the 'next' pagination link

    return ExitCode::OK;
}
```

### Craft CMS version

4.5.15

### PHP version

8.1.13

**Comment by timkelty** [comment]
@romainpoirier are you able to privately share the URL, so I can reproduce exactly what you're seeing?
You can share with me on Discord (timkelty) or to support@craftcms.com

**Comment by timkelty** [comment]
@romainpoirier a couple things to try:

Within your loop, add:

```
// Flush in-memory logs to targets (Monolog)
Craft::$app->getLog()->getLogger()->flush();
```

I suspect this will help with the memory consumption.

Also, instead of replacing `Craft::error`, you can try calling `reset()` directly on the Monolog logger already in use, like so:

```
        /** @var MonologTarget $logTarget */
        $logTarget = Craft::$app->getLog()->targets[Dispatcher::TARGET_CONSOLE]
        $logTarget->getLogger()->reset();
```

**Comment by timkelty** [comment]
@romainpoirier Just following up – were you able to test any of that?

**Comment by timkelty** [comment]
Closing, but let me know if you're still having issues.

**Comment by timkelty** [comment]
@romainpoirier Craft's default loggers use Monolog log targets, so either way you're using Monolog.
Using monolog directly wouldn't be going through Yii at all, so you wouldn't get any of the log filtering Yii provides.
