### ISSUE TITLE
XML route sending text/html content-type

### ISSUE THREAD

**Issue by leigeber** [craftcms/cms#1424]
### Description

XML templates don't return the correct content-type when the route is defined in routes.php, haven't checked other types or routing scenarios. I've tried setting the suffix separately with no change. This was working automatically with V2, was there something else needed for V3?

### Steps to reproduce

1. Create sample XML template
2. Add the following route value

```
return [
	'corp/sitemaps/index' => [
		'template' => '_sitemaps/index.xml',
		'suffix' => '.xml'
	]
];
```

### Additional info

- Craft version: 3.0.0-beta.4
- PHP version: 7.1.1
- Database driver & version: MySQL 5.7.17
- Plugins & versions: None

**Comment by takobell** [comment]
Not sure if the issue is Craft is ignoring Yii's `'suffix'` (http://www.yiiframework.com/doc-2.0/guide-runtime-routing.html) key for routes or not, but even a simple:

    return [
	'foo' => ['template' => 'bar.xml',
    ];

will set a text response header.  Looking into it.

**Comment by brandonkelly** [comment]
Looks like Craft is _never_ returning anything besides `text/html` right now, even if a `.xml` template was loaded directly via the URL, or even if a `{% header %}` tag explicitly sets the `content-type` header.
