### ISSUE TITLE
[5.x]: Page navigation on subfolder click in asset selector modals

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#14250]
### Description

When clicking a sub folder inside an asset selector modal, the browser navigates to the subfolder's URL instead of just opening the folder inside the modal.

### Steps to reproduce

1. Create a volume and a filesystem 
2. Create a sub folder in the volume
3. From an assets field, click "Add an asset"
4. Inside the asset selector modal, click on a subfolder

### Expected behavior

The sub folder should open inside the modal, allowing the author to select images in that folder.

### Actual behavior

The browser navigates to the sub folder's URL, e.g. `/admin/assets/images/subfolder`.

https://github.com/craftcms/cms/assets/298510/a6c15ab9-3e31-453f-9ff8-7a84b33c0ac3

### Craft CMS version

5.0.0-alpha.9

### PHP version

8.2

### Operating system and version

macOS 12.6, MS Edge 121.0.2277.83

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 5.0.0-alpha.10 was just tagged with a fix.
