### ISSUE TITLE
[4.x]: graphql filtering on related category return unespected elements

### ISSUE THREAD

**Issue by vettndr** [craftcms/cms#14258]
### Description
I'm filtering records based on a category using graphql and I'm not able to understand why I'm receiving items that not match the id of that category.

### Steps to reproduce

![craft-query](https://github.com/craftcms/cms/assets/50450003/c715ffd9-0102-4e93-a4f9-cde50f415c1f)

### Expected behavior
I'm expecting to receive only records that have category with id: 20

### Actual behavior
Other elements are retrieved.

### Craft CMS version

4.7.1

### PHP version

8.1.27

### Database type and version

MariaDB 10.6.16

### Installed plugins and versions

![craft-plugins](https://github.com/craftcms/cms/assets/50450003/6affa164-e784-4574-829b-168a90b9c4b0)

**Comment by vettndr** [comment]
> Hi, thanks for getting in touch!
> 
> It sounds like a duplicate of: #12740
> 
> For now, you can get the results you’re after if you use `relatedToCategories` instead of `offerCategories`, like so:
> 
> ```
> query getOffers {
>   OfferEntries(siteId: "1", relatedToCategories: {id: "20"}) {
>     ... on Offer_Entry_Entry {
>       title
>       offerCategories {
>         ... on Offer_Category {
>           id
>         }
>       }
>     }
>   }
> }
> ```

Hi @i-just ,
thank you for your reply.

I tried also as you suggested me before to create this issue.
Is still not working as should it be.

![craft-query-2](https://github.com/craftcms/cms/assets/50450003/ea905dce-d35c-4084-83ec-eb99766e7b37)

**Comment by i-just** [comment]
The initial issue (querying by related category in a multi-site setup) was fixed in `4.7.3`, so I’ll close this now.

@vettndr, if you’re still getting unexpected results when using `relatedToCategories`, please send the requested files to support, and we’ll have a look into it.

**Comment by brandonkelly** [comment]
Craft 4.8.0 was just released with a fix for this. Thanks for your help!
