### ISSUE TITLE
[4.x]: craft\elements\actions\Delete relies on Craft::$app->getElementSources()->getSources, so entries of a disabled entry type are undeletable through this function

### ISSUE THREAD

**Issue by jamie-s-white** [craftcms/cms#14257]
### Description

[4.x]: craft\elements\actions\Delete relies on Craft::$app->getElementSources()->getSources, so entries of a disabled entry type are undeletable through this function

### Steps to reproduce

1. We have set up a custom field which makes a call to:

craft\elements\actions\Delete

With parameters:

          context:             'index',
          criteria:              { status: null, siteId: this.siteId, limit: 0 },
          elementType:    'craft\\elements\\Entry',
          source:              this.source

Which works absolutely fine.

2. We then disable that entry type via /admin/entries -> clicking on the cog -> customising sources _> choosing the entry type and disabling it (which we are doing to remove that entry type from the list and making the sole method of managing these entries through our custom field). This results in an update to config/project/project.yaml for that entry type:

      disabled: false

3. We then call craft\elements\actions\Delete again, we then we get a BadRequestHttpException thrown “Element action is not supported by the element type”.

Debugging this, I have tracked this back to the call:

        foreach (Craft::$app->getElementSources()->getSources($elementType, $this->context) as $source) {

Line 291 in ElementIndexesController.php.

Our Entry type is no longer on the list of sources when the entry type is disabled, and so the actions array never gets populated, and so Craft doesn’t think we can delete this element and throws the error.

This is inconsistent, because this entry type still appears in the “all entries” list, we can click on those entires, and delete them from here.

(As a quick aside, the breadcrumbs for these entries will also still link back to /admin/entries/entry-handle, but clicking on this will just redirect you back to /admin/entries, as it has been disabled).

### Expected behavior

Being able to delete the entry

OR

Consistent behaviour with the rest of the Craft CMS interface.

We are utilising the "disabled" property of entries to remove them from /admin/entries, and just edit them through our own custom plugin (otherwise the volume of elements added to this entry type is overwhelming and simply not usable for our admins). This used to work in Craft 3.8.17, but has broken since the migration to Craft 4.

However, we may simply be misunderstanding the intent behind enabling/disabling entry types, and instead simply want to show/hide them when an admin navigates to /admin/entries, and then we can continue to content manage these entries purely through our own plugin. The current behaviour feels wrong because of the inconsistency.

### Actual behavior

Get an exception thrown, and the entry is not deleted

### Craft CMS version

4.6.1

### PHP version

8.2

### Operating system and version

Servd

### Database type and version

MySQL 5.7

### Installed plugins and versions

		"clubstudioltd/craft-asset-rev": "^7.0",
		"craftcms/ckeditor": "^3.6",
		"craftcms/cms": "4.6.1",
		"craftcms/feed-me": "^5.0",
		"craftpulse/craft-colour-swatches": "^4.0",
		"craftpulse/craft-typesense": "^5.0",
		"doublesecretagency/craft-cpcss": "^2.4.0",
		"enovatedesign/craft-style-inliner": "^3.0",
		"mmikkel/cp-field-inspect": "^1.4.4",
		"nystudio107/craft-retour": "^4.0",
		"putyourlightson/craft-blitz-recommendations": "2.1.3",
		"sebastianlenz/linkfield": "^2.0",
		"spicyweb/craft-odds-and-ends": "^4.0",
		"servd/craft-asset-storage": "^3.0",
		"studioespresso/craft-scout": "^3.0",
		"supercool/connect": "^4.0",
		"supercool/dates-and-times": "^4.0",
		"supercool/event-manager": "^4.0",
		"supercool/fetch": "^4.0",
		"supercool/scheduler": "^4.0",
		"supercool/spektrix-fields": "^4.0",
		"topshelfcraft/wordsmith": "^4.0",
		"verbb/buttonbox": "^4.0",
		"verbb/color-mixer": "^3.0",
		"verbb/default-dashboard": "^2.0",
		"verbb/super-table": "^3.0",
		"verbb/tablemaker": "^4.0",
		"vlucas/phpdotenv": "^5.5.0",
		"vaersaagod/matrixmate": "^2.1"

**Comment by i-just** [comment]
Hi Jamie, thanks for getting in touch!

This is an expected behaviour. Actions can only be performed on the enabled sources. If it fits your needs, you could call that action on the ‘All Entries’ source, create a custom source and call the action for it, or roll your own action.

I hope this helps!
