### ISSUE TITLE
Issue setting offset with pagination

### ISSUE THREAD

**Issue by leigeber** [craftcms/cms#1425]
### Description

I have a channel with 2 test entries. When setting pagination with an offset of 1, which was working in V2, there are now no results. If I set the offset to 0 there are 2 results.

### Steps to reproduce

1. Create channel with 2 entries
2. Paginate with something like `craft.entries.section('blog').offset(1).limit(12)`

### Additional info

- Craft version: 3.0.0-beta.4
- PHP version: 7.1.1
- Database driver & version: MySQL 5.7.17
- Plugins & versions: None

**Comment by takobell** [comment]
Can you update to the latest beta.5 and try again?  I'm not able to reproduce, but it might have already been fixed.

If I have 2 entries in a section and do:

    {{ craft.entries.section('test1').offset(1).limit(12)|length }}

I get the expected output of `1`.

**Comment by leigeber** [comment]
I get "1" for the length using that as well but not when paginating like the following, I get "0".

```
{% paginate craft.entries.section('blog').offset(1).limit(12) as entries %}
{{ paginate.total }}
```

**Comment by takobell** [comment]
Sorry... missed that it was in a paginate tag.  Looking into it.
