### ISSUE TITLE
[5.x]: Deleting entry type results in JS error

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/cms#14262]
### Description

When I delete an entry type, it appears to be successful, but the response doesn't contain information that the front-end requires to unlock the table view. Refreshing the page makes it possible to delete another entry type.

### Steps to reproduce

1. Create an entry type
2. Delete it using the table in **Settings** &rarr; **Entry Types**;
3. Observe table’s locked state;

### Expected behavior

I should be able to delete multiple entry types without refreshing (or, maybe they just get deleted with a normal `<form>` POST request and the page is refreshed normally).

### Actual behavior

A JS error occurs, presumably when handling the empty response. It appears to stem from a "formatting" method, potentially used when rendering the toast?

### Craft CMS version

5.0.0-alpha.9

### PHP version

8.2.13

### Operating system and version

Docker/Linux 6.5.0-15-generic

### Database type and version

MariaDB 10.4.32 (Oops!)

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

None

**Comment by i-just** [comment]
Looks like Nathaniel fixed: https://github.com/craftcms/cms/pull/14261

**Comment by brandonkelly** [comment]
Yep! Retroactively pointed the fix release note to this issue though.

**Comment by brandonkelly** [comment]
5.0.0-alpha.11 is now tagged with the fix.
