### ISSUE TITLE
[4.x]: Missing url encode in control panel files image elementthumb preview

### ISSUE THREAD

**Issue by knufri** [craftcms/cms#14266]
### Description
I have uploaded images that contain a hash # in the file name. In the element thumb preview in the backend the character is not encoded and I get a 404 error for the image url. In the preview or image editing the character is encoded correctly. Here is one example:
Preview url: http://domain.tld/uploads/images/properties/795751-kurz%23scho%CC%88nes_Einfamilienhaus_2_Musterfoto.jpg?v=1706801067
Image edit url: http://domain.tld/uploads/images/properties/795751-kurz%23scho%CC%88nes_Einfamilienhaus_2_Musterfoto.jpg?v=1706801067
Thum Preview url: http://domain.tld/uploads/images/properties/_240x180_crop_center-center_none/795751-kurz?v=1706801067

The link is broken because of the unescaped # character.

<img width="400" alt="Bildschirmfoto 2024-02-01 um 17 16 15" src="https://github.com/craftcms/cms/assets/2785206/897615fa-2ac8-40dd-9415-6815fe9f96d6">

<img width="1327" alt="Bildschirmfoto 2024-02-01 um 17 16 40" src="https://github.com/craftcms/cms/assets/2785206/08b27b9a-efa9-43aa-b06e-bb471027589e">

### Steps to reproduce

1. Upload an image with # in the filename, e.g. 749684-kurz#Grundstück_Wiese_2_Musterfoto.jpg then go to assets -> images and (not)see the broken preview 🏞️

### Expected behavior

Preview is shown

### Craft CMS version

4.6.1

### PHP version

8.1.26

**Comment by brandonkelly** [comment]
Craft removes `#` characters from filenames on upload. Are you sure you uploaded the file via Craft? (Alternatively, it may have already existed in the folder/S3 bucket/etc., and it got indexed via the Asset Indexes utility.)

**Comment by knufri** [comment]
Hello @brandonkelly thanks for the fast reply. Indeed I copied the images in the volume folder and used the asset indexes utility afterwards.
Greetings 👋🏼

**Comment by brandonkelly** [comment]
So yeah Craft won’t tamper with filenames that already existed on the filesystem. But `#` should definitely not have been used within the filename to begin with, as it’s not a valid character in a URL.
