### ISSUE TITLE
[5.x]: Creating a Matrix within a Matrix using the inline field editor throws `'$defaultColumnsContainer' has already been declared` error

### ISSUE THREAD

**Issue by aaronbushnell** [craftcms/cms#14268]
### Description
I'm trying to create a Matrix field within an existing Matrix field using the new inline editor added to 5.0.0-alpha.11 and as soon as I select the "Matrix" type I get the following error in my console:
```
Uncaught SyntaxError: Identifier '$defaultColumnsContainer' has already been declared
```

### Steps to reproduce

1. Create a Matrix field (Page Builder)
2. Use the new inline field editor to add a new field that has a type of "Matrix"
3. Check the console

### Craft CMS version

5.0.0-alpha.11

### PHP version

8.3

### Operating system and version

macOS 14.3

### Database type and version

MySQL 8.0.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.1-21)

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.0.0-alpha.12 is out with the fix for that. Thanks again!

**Comment by aaronbushnell** [comment]
Thanks, Brandon!
