### ISSUE TITLE
[5.x]: Matrix entries with visible titles show validation error upon creation in inline mode

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#14273]
### Description

If an entry type with the "Show the Title Field" setting enabled is added to a Matrix field, any entries with that entry type will show a validation error (`Title cannot be blank`) upon creation, in Matrix fields using the "As inline-editable blocks" view mode.

Curiously, the nested entry has also been given a default "New entry" title. So actually, the nested entry _does_ have a title (and can be re-saved without issues), but shows the validation message regardless.

https://github.com/craftcms/cms/assets/298510/7b5d5265-4744-4e9e-a0b2-fa4cf0cb07c5

### Steps to reproduce

1. Create an entry type with the "Show the Title Field" setting enabled
2. Create a Matrix field, add the entry type and set the View Mode to "As inline-editable blocks"
3. Add the Matrix field to an entry field layout
4. Create an entry and add a Matrix entry using the entry type with titles enabled

### Expected behavior

Titles should be handled the same way as required custom fields, i.e. no validation errors until the author actually has a chance to edit them, and attempts to save the entry.

(Ideally, I think it should be possible to configure per entry type whether or not the title field is actually required or not, but I'm guessing that's no feasible).

The "New entry" default title is also awkward; it'd be great if a default title could be avoided.

### Actual behavior

Unlike other required fields, Craft immediately shows a validation error for the title field as soon as the nested entry has been created.

### Craft CMS version

5.0.0-alpha.11

### PHP version

8.2

### Database type and version

10.5.21-MariaDB

### Installed plugins and versions

None

**Comment by i-just** [comment]
Hi, thanks for reporting! Looks like [Brandon already fixed it](https://github.com/craftcms/cms/commit/1be21f7500e93fcdb6fdbb4217ac6a223de18389), but it’s not released yet.

**Comment by brandonkelly** [comment]
For posterity, this was fixed in [5.0.0-alpha.12](https://github.com/craftcms/cms/releases/tag/5.0.0-alpha.12).
