### ISSUE TITLE
[4.x]: 4.6.2 needs a release, 4.6.1 vulnerable

### ISSUE THREAD

**Issue by soulseekah** [craftcms/cms#14288]
### Description

<img width="908" alt="image" src="https://github.com/craftcms/cms/assets/685880/ebb63ebe-4a11-49e9-ab53-f1e9cd0dfca8">

### Steps to reproduce

1. Go to packagist.org craftcms

<img width="908" alt="image" src="https://github.com/craftcms/cms/assets/685880/df4860f4-b788-45ed-a6e8-9f868134453e">

There is no 4.6.2 :(

### Expected behavior

4.6.2 should be made available for an update of dependencies via Composer.

### Actual behavior

4.6.1 is the latest one available at packagist.

```bash
~ composer update craftcms/craft
Loading composer repositories with package information
Package "craftcms/craft" listed for update is not locked.
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating optimized autoload files
```

### Craft CMS version

4.6.1

### PHP version

8.3

### Installed plugins and versions

-

**Comment by angrybrad** [comment]
The Github Security Advisory is incorrect (content-wise as well as technically) and we’re disputing the assigned CVE with Mitre, too.

They were confusing Feed Me versions with Craft versions and tagged a Craft version that didn't exist.

It's a whole process, but once we hear back from Mitre, we can contact Github to remove the GHSA.

For now, it's safe to ignore.
