### ISSUE TITLE
[4.x]: Craft isn't picking up the Chinese translation file

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#14287]
### Description

On a fresh Craft 4 install, if you select Chinese (zh) as the site language, the Craft control panel does not appear to pick up the translation file, but every other language works.

### Steps to reproduce

1. Make a fresh install of Craft 4.
2. During installation, select “Chinese” as the system language.
3. Finish install.
4. Swap to Craft Pro.
5. Click Users => New User
6. Without filling anything in, click the save user button
7. Notice most of the validation error is in English.

![CleanShot 2024-02-04 at 21 48 37@2x](https://github.com/craftcms/cms/assets/61869/48cab2f7-ae2e-4648-a145-84905ca883e9)

Repeat the same steps, but select “French” during installation, and you get the fully translated validation message.

![CleanShot 2024-02-04 at 21 52 04@2x](https://github.com/craftcms/cms/assets/61869/56ff78d5-539c-4160-8170-8f53b6e7506d)

### Craft CMS version

4.7.1

### PHP version

8.2

### Operating system and version

n/a

### Database type and version

MySQL 8

### Image driver and version

n/a

### Installed plugins and versions

None

**Comment by i-just** [comment]
It looks like Yii moved their translation file from `zh-CN` to plain `zh`, which means we should no longer adjust the language id mapping for Chinese. PR raised.

**Comment by brandonkelly** [comment]
Fixed in 4.7.2.
