### ISSUE TITLE
Site logo and login image don't respect dimensions of uploaded image.

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#1428]
### Description

Uploaded a simple logo: 

![image](https://cloud.githubusercontent.com/assets/25124/23328623/2414843a-fb7a-11e6-99cb-1e0e0448e036.png)

Dimensions are all screwy:

![image](https://cloud.githubusercontent.com/assets/25124/23328617/ef38b6c8-fb79-11e6-804a-186c6d054cb8.png)
![image](https://cloud.githubusercontent.com/assets/25124/23328619/f78bcf4a-fb79-11e6-8aed-4a78ab4e8c0d.png)

**Comment by andris-sevcenko** [comment]
This was a conscious decision (@brandonkelly), but we're open for suggestions.

**Comment by leevigraham** [comment]
As in the user chooses which image size to upload? If that's the case shouldn't there still be a max-width with some responsive image css?

**Comment by andris-sevcenko** [comment]
Probably? (cc @benjamindavid)
