### ISSUE TITLE
Add additional attributes to form macros

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#1430]
### Description

I want to add autocomplete attributes to my field forms for phone, address etc. Currently there's no way to pass custom attributes through to fields eg: `templates/_includes/forms/textarea.html`

This could also be useful for hooking up vue properties.

Symonfy has this covered in their twig / form macros: http://symfony.com/doc/current/reference/forms/twig_reference.html#form-variables-reference

`attr: A key-value array that will be rendered as HTML attributes on the field.`

    {%- block widget_attributes -%}
        id="{{ id }}" name="{{ full_name }}"
        {%- if disabled %} disabled="disabled"{% endif -%}
        {%- if required %} required="required"{% endif -%}
        {%- for attrname, attrvalue in attr -%}
            {{- " " -}}
            {%- if attrname in ['placeholder', 'title'] -%}
                {{- attrname }}="{{ translation_domain is same as(false) ? attrvalue : attrvalue|trans({}, translation_domain) }}"
            {%- elseif attrvalue is same as(true) -%}
                {{- attrname }}="{{ attrname }}"
            {%- elseif attrvalue is not same as(false) -%}
                {{- attrname }}="{{ attrvalue }}"
            {%- endif -%}
        {%- endfor -%}
    {%- endblock widget_attributes -%}

**Comment by brandonkelly** [comment]
The `{{ dataAttributes }}` tag in `_includes/forms/fields.html` should be replaced with a `{{ block('attributes') }}` call, and then we can follow this pattern in other form includes as well.

**Comment by brandonkelly** [comment]
Implemented this for Craft 3 RC1.
