### ISSUE TITLE
[5.x]: Craft CMS Matrix Blocks Reappear After Deletion and Fail to Render UI Elements

### ISSUE THREAD

**Issue by bavodeclercq** [craftcms/cms#14303]
### Description

Two issues are presenting with inline-editable matrix blocks in Craft CMS:

1. Resurfacing of Last Deleted Block: When all blocks within a matrix are deleted and the entry is saved, the last block that was removed reappears with its previously entered content, as if the deletion was not acknowledged.
2. Non-rendering of UI Elements in Entry Types: Matrix fields tied to entry types that include UI elements are failing to render any of the fields, leaving the expected interface incomplete.

[Video](https://share.cleanshot.com/3c5tn6bW)

**Matrix settings**

- Propagation Method: Only save entries to the site they were created in
- Min Entries: empty
- Max Entries: empty
- View Mode: As inline-editable blocks

**Entry types**

- [Default](https://share.cleanshot.com/tYw6mM9F)
- [Test](https://share.cleanshot.com/ttPz70w3)

### Steps to reproduce

1. Persistent Last Block on Deletion:
- Create a matrix field with entry types.
- Add multiple blocks to the matrix.
- Delete all the blocks.
- Save the entry.
- Observe that the last deleted block reappears.

2. UI Elements Not Rendering in Entry Types:
- Establish a matrix field linked to an entry type that includes UI elements.
- Add block to the matrix.
- Notice the absence of all fields and UI elements.

### Expected behavior

1. After deleting all matrix blocks and saving, no blocks should reappear.
2. Fields and UI elements in entry types should render correctly.

### Actual behavior

1. Despite deleting all matrix blocks, the last deleted block reappears upon saving the entry.
2. Fields and UI elements within matrix blocks tied to entry types are not rendering.

### Craft CMS version

Craft Pro 5.0.0-alpha.12

### PHP version

8.2.13

### Operating system and version

Linux 6.5.13-orbstack-00121-ge428743e4e98

### Database type and version

MySQL 8.0.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- CP Field Inspect 2.0.0-alpha.4
- Retour 5.0.0-beta.1
- SEOmatic 5.0.0-beta.2
- Translations 3.1.0
- Vite 5.0.0-beta.2

**Comment by brandonkelly** [comment]
Thanks for reporting that! The last block deletion has been fixed for the next release.

There was a bug that caused a PHP error whenever UI elements were used. That must have been getting swallowed for you, but that’s likely why they weren’t showing up within Matrix blocks for you. Fixed now for the next release.

**Comment by brandonkelly** [comment]
Craft 5.0.0-alpha.13 is out with those fixes.
