### ISSUE TITLE
[5.x]: Card view for matrix fields should more clearly indicate block/entry type

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#14305]
### Description

When viewing matrix blocks as cards, it's not clear what block type is associated with the card.

![CleanShot 2024-02-06 at 08 57 38](https://github.com/craftcms/cms/assets/3810939/3a16f847-7d3a-4d71-901f-ed5d9813c1e1)

Opening a card in a slide-out is equally opaque. I imagine the entry type icon should be displayed somewhere as well.

### Craft CMS version

5.0.0-alpha.12

**Comment by brandonkelly** [comment]
Added for the next release!

<img src="https://github.com/craftcms/cms/assets/47792/38f7653e-f65b-4b06-8a04-4d93a16d892e" width="443" alt="An entry card, with a blue “T” icon indicating it has the “Text” entry type.">

**Comment by brandonkelly** [comment]
5.0.0-alpha.13 was just tagged with that change.
