### ISSUE TITLE
[4.x]: Codeception Unit tests "No primary site exists" error, but Functional and Acceptance tests will run.

### ISSUE THREAD

**Issue by tommydaltondev** [craftcms/cms#14311]
### Description

Codeception throws "No primary site exists" only when running unit tests. Functional and acceptance tests continue to work as they did. Not a multi-site craft install and site handle is default. 

Codeception 4.2.2 (PHPUnit 9.6.16) and Craft CMS Pro 4.7.0 PHP version 8.1.26.

### Craft CMS version

Pro 4.7.0 

### PHP version

8.1.26

### Operating system and version

Linux 6.5.11-linuxkit

### Database type and version

MariaDB 10.4.32

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

**Comment by leowebguy** [comment]
In Sites.php line 512:
No primary site exists  
                   
![Screenshot 2024-02-06 at 3 10 49 PM](https://github.com/craftcms/cms/assets/8460020/2723aafe-330d-4c34-9027-12763d2328eb)

**Comment by i-just** [comment]
Hi, thanks for getting in touch! As a starting point, could you please share the contents of your `codeception.yml`?

**Comment by leowebguy** [comment]
```
actor: Tester
paths:
    tests: tests
    log: tests/_output
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
bootstrap: _bootstrap.php
params:
  - tests/.env
settings:
  colors: true
  memory_limit: 2048M
extensions:
  enabled:
    - Codeception\Extension\RunFailed
modules:
  config:
    \craft\test\Craft:
      configFile: 'tests/_craft/config/test.php'
      entryUrl: 'https://mysite.ddev.site'
      entryScript: 'index.php'
      projectConfig: {
        folder: 'config/project',
        reset: false # should not modify projectConfig
      }
      migrations: []
      plugins: []
      cleanup: true
      transaction: true
      dbSetup: {
        clean: false,
        setupCraft: false,
        applyMigrations: false
      }
      fullMock: false

```

**Comment by i-just** [comment]
Thanks! Since you have 
```
dbSetup: {
  clean: false,
  setupCraft: false,
  applyMigrations: false
}
```
Is it possible that in the database used for testing, in the `sites` table, none of the sites have `1` in the `primary` column? 
I can replicate this when I set the `primary` to `0` for the one site I have in my setup.

**Comment by leowebguy** [comment]
It uses the same local db and it has primary set as 1, same in config/project/sites...

![Screenshot 2024-02-07 at 8 09 14 AM](https://github.com/craftcms/cms/assets/8460020/108459c4-70bb-4df1-b443-df2b5370d9a3)

I've remove the `dbSetup` config ... no success.
Matter of fact I've tweaked around `codeception.yml`, same result.

**Comment by i-just** [comment]
And is it all the unit tests that fail or just some? Any chance you could share a unit test file with a failing test? Feel free to send it to support@craftcms.com if you prefer to keep it off here.

**Comment by leowebguy** [comment]
I don't think it gets there... any basic unit test fails.
But the API tests run just fine.

I found those issues related to this ... [11984](https://github.com/craftcms/cms/issues/11984) and [7412](https://github.com/craftcms/cms/issues/7412) maybe something bounced back.

```<?php

namespace unit;

use Codeception\Test\Unit;
use aaa\bbb\Mailer;
use UnitTester;

class SampleTest extends Unit
{
    protected $tester;

    public function testMailerIsInstalled()
    {
        $isInstalled = Mailer::getInstance()->isInstalled ?? false;
        $this->assertTrue($isInstalled);
    }
}```

**Comment by i-just** [comment]
Could you please send your `config/project` to support@craftcms.com so I can try to replicate it on our end?

**Comment by leowebguy** [comment]
@i-just turns out `"nystudio107/craft-autocomplete": "^1.12",` was the cause of this problem.

after removing it, unit tests run fine

**Comment by i-just** [comment]
Thanks for letting me know! Glad it’s working as expected now.

**Comment by khalwat** [comment]
@leowebguy I have Craft Autocomplete installed in my `require-dev` and don't see it failing any of my unit tests.

If you like, create an issue with details and steps to reproduce on the repository https://github.com/nystudio107/craft-autocomplete/issues

Looking at the code, it's a bit hard to see how it could be causing an issue, but you never know!
