### ISSUE TITLE
Question: about Craft 3

### ISSUE THREAD

**Issue by trsh** [craftcms/cms#1431]
Not sure if this is the right place to ask, but here we go.

How far/safe is Craft 3 Beta right now?
Can I use it for production with minor risks?
How much is suspected to change until R.C?
If I plan to finish my project in 2 month, would it not be smart to use 3 version?
Will the price remain the same for pro version?

**Comment by narration-sd** [comment]
Hello again trsh -- P&T can answer as they want to, but I can probably fill in a bit here, as these are questions asked by many. Taking your points in order:

- Beta is beta, and this is early beta. It is not reasonable for more than experiments, getting a run on plugin updating, and bug reporting.
- No, in no way should you think of using it for production. I am quoting the CEO and CTO, many times over.
- Hard to say. The basis is there, but lots of feature talk besides possible consequences of things not implemented yet or bugs. Think please.
- There's no release date, but I think the horizon is circa six months. Of course this can lengthen, as software projects do. So no, smart it would not be, pretty clearly.
- Price - ask the principals.

How do you get close to the hot information, and ask principals?

Log into Craft Slack, and follow the  #craft3d session. Many do.

You might like to be aware that among many fine things, they keep Craft 2 hot and constantly updated. It is excellent software. I would use it.

**Comment by trsh** [comment]
@narration-sd thanks!

**Comment by narration-sd** [comment]
Ok, and one other thing I can say, is that updating a site's templates shouldn't be a large amount of trouble. A medium-complexity, auto-laying out workup site I have would just run, at every stage of Craft 3 alpha and beta. if memory serves. 

There are changes, but these are presented as deprecations -- and automatically listed for you on the Craft 3 control panel, in their own screen. Quality work, as ever.

**Comment by trsh** [comment]
@narration-sd thanks again for the info.

**Comment by brandonkelly** [comment]
What @narration-sd said.

> Will the price remain the same for pro version?

Probably, we have no plans to change pricing at this time.

**Comment by psren** [comment]
Is it possible to migrate a site from v2 to v3 later on somehow?

**Comment by takobell** [comment]
@psren Yes. Upgrade guide is here: https://github.com/craftcms/docs/blob/master/en/upgrade.md
