### ISSUE TITLE
[5.x]: Entry types created inline can be selected twice

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#14320]
### Description

If I create an entry type inline, such as when editing a Section, the new entry type is added automatically; however, it can also be added a 2nd time through the dropdown.

In this example, I created a new entry type called "Call to Action" - you can see I was able to add it from the selector dropdown after it was automatically selected, resulting in two instances showing up. If I remove one instance, it's added back to the dropdown.

![CleanShot 2024-02-07 at 11 30 46](https://github.com/craftcms/cms/assets/3810939/844773a1-a2df-449b-93b1-2aff74f3b2ad)

### Craft CMS version

5.0.0-alpha.13

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Fixed in 5.0.0-beta.1!
