### ISSUE TITLE
[4.x]: Base URL for primary site not respected

### ISSUE THREAD

**Issue by MatthiasBrodelet** [craftcms/cms#14327]
### Description
I live in Belgium and we mostly build multi language sites.
When I create a multi language website with Craft I create multiple sites, each with their own locale. (nl-BE, fr-BE, ...)
Often these website use the same domain which would mean that we need to add the locale in the URL like this.
- my-company.be/nl
- my-company.be/fr

We can achieve this URL setup by setting a base URL for each site.
However when we add a locale to the base URL of the primary site this site is available on both my-company.be and my-company.be/nl.

This is an issue because every page will have 2 different possible URL's.
- my-company.be/nl/contact
- my-company.be/contact

### Steps to reproduce

1. Create multiple sites with the same domain
2. Change the base URL for each site to include the locale

### Expected behavior
I would expect my-company.be to redirect to my-company.be/nl since this is the primary base URL.
Pages like my-company.be/contact should throw a 404 because only my-company.be/nl/contact should be available.

### Actual behavior
Both my-company.be/contact and my-company.be/nl/contact are valid pages which will create issues for google search console since they are the same page with a different URL.

### Craft CMS version

4.7.1

### PHP version

8.1.18

### Operating system and version

Linux 6.3.13-linuxkit

### Database type and version

MySQL 5.7.29

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

**Comment by i-just** [comment]
Hi, thanks for getting in touch!

Let’s say you have your primary site’s base URL set to `https://www.my-company.be/nl` and a second site URL set to `https://www.my-company.be/fr`. 

In the [documentation on routing](https://craftcms.com/docs/4.x/routing.html), point 0 mentions that your web server first determines whether the request should be handled via Craft, and if yes, it will use the `index.php` file to handle the requests. From that point on, Craft gets involved. 

When you access `https://www.my-company.be/nl`, it serves the primary site; when you access `https://www.my-company.be/fr`, it serves the second site; and when you access `https://www.my-company.be`, it falls back onto the [default behaviour](https://craftcms.com/docs/4.x/sites.html#primary-site) where if it can’t find a matching site, it’ll serve the primary one. 

If you want to change this behaviour, you’ll have to do that via your web server configuration.

I hope this helps. I’ll close this now, but feel free to reach out again if you have any further problems.

**Comment by MatthiasBrodelet** [comment]
Hi Iwona,

Thanks for taking the time to respond.

How would you recommend changing this in the .htaccess file?

I can easily redirect `https://www.my-company.be` to `https://www.my-company.be/nl`.
But what should I do with routes like `https://www.my-company.be/contact` and `https://www.my-company.be/about`?
I would like both routes to either show a 404 or redirect to `https://www.my-company.be/nl/contact` and `https://www.my-company.be/nl/about`.
Obviously I don't want to hardcode these redirects so I'm a little lost on how to handle this.

For example: `https://www.belgium.be/nieuws` will redirect to `https://www.belgium.be/nl/nieuws`.

I know this a grey area and that it might not be Craft's responsibility.
However since the main routes for the website are created in Craft it would be really nice if there was a way to improve the multi language experience.

In the past our strategy was to not show a locale in the URL for the primary site. This 'fixes' the issue but creates another issue where not all languages have the same url structure.

**Comment by i-just** [comment]
Hi Matthias,

Not a problem. You could add something like this to rewrite all the URIs that don’t start with `/nl/` or `/fr/` to the NL URL. 
```
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !^/(nl|fr)/?
RewriteRule (.*) https://www.my-company.be/nl/$1 [QSA,L]
```
Please note that it needs to be placed before the rule that makes sure the requests are routed to Craft. Out of the box, that block looks like this:
```
# Send would-be 404 requests to Craft
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !^/(favicon\.ico|apple-touch-icon.*\.png)$ [NC]
RewriteRule (.+) index.php?p=$1 [QSA,L]
```

The idea here is to enforce all URLs that don’t start with your sites’ base URLs to get rewritten to the primary site and then let Craft figure out which page to serve (if any).

I hope this is a good starting point for adjusting to your needs.

**Comment by MatthiasBrodelet** [comment]
It sure is.
Thank you for your help!
