### ISSUE TITLE
[4.x]: GraphQL queries bypass read replicas and go straight to primary DB

### ISSUE THREAD

**Issue by ericdrosas87** [craftcms/cms#14324]
### Description
I set up cross-region read replicas in Google Cloud for a headless v4 Craft CMS à la the documentation and it seems to have been configured correctly. We're seeing traffic to the read replicas, but for graphQL queries the request goes all the way to the primary DB instance.

I saw this in the code, which states that read/write splitting is disabled for POST requests (graphQL requests are sent as POST requests):

```
    // Disable read/write splitting for POST requests
    if (
        $request->getIsPost() &&
        !in_array($request->getActionSegments(), [
            ['element-indexes', 'count-elements'],
            ['element-indexes', 'data'],
            ['element-indexes', 'export'],
            ['element-indexes', 'get-elements'],
            ['element-indexes', 'get-more-elements'],
            ['element-indexes', 'get-source-tree-html'],
        ])
    ) {
        $this->getDb()->enableReplicas = false;
    }
```

This became apparent to us as we have read replicas in a South American region with the primary DB instance in a U.S. region, causing a significant latency in response times for all GQL requests. I am seeing this for queries (we don't use GQL mutations in our client.)

### Steps to reproduce

1. Configure Craft CMS for read replicas
2. Make graphQL query to API endpoint
3. Check DB traffic to read replica

OR

Do what I did and modify the `/src/web/Application.php` function `handleRequest()` as such:

```
        if (!$skipSpecialHandling) {
            // Process resource requests before anything else
            $this->_processResourceRequest($request);

            // Disable read/write splitting for POST requests
            if (
		    $request->getIsPost() &&
                !in_array($request->getActionSegments(), [
                    ['element-indexes', 'count-elements'],
                    ['element-indexes', 'data'],
                    ['element-indexes', 'export'],
                    ['element-indexes', 'get-elements'],
                    ['element-indexes', 'get-more-elements'],
                    ['element-indexes', 'get-source-tree-html'],
                ])
	    ) {
		Craft::info("Got into the IF block!!!", "erosas-debug");
                $this->getDb()->enableReplicas = false;
	    } else {
		Craft::info("Got into the ELSE block!!", "erosas-debug");
	    }
```

And then `tail -f` the Craft web log.

### Expected behavior

A non-mutation graphQL query is sent to read replicas.

### Actual behavior

A non-mutation graphQL query is sent to the primary DB instance.

### Craft CMS version

4.5.4

### PHP version

8.1.10

### Operating system and version

Linux (php:8.1-apache)

### Database type and version

Postgres 13.7

### Installed plugins and versions

-

**Comment by ericdrosas87** [comment]
While testing I did confirm that adding `!request->getIsGraphql() &&` to the `if` block fixed the issue, but while chatting with @khalwat also realized that this would also let mutations through.

**Comment by khalwat** [comment]
Without knowing the underlying architecture, my thought that an additive way to solve this might be to have an additional read-only endpoint for GraphQL in Craft that then passes the check for the appropriate action segment (as per the `element-indexes` above), and allows the read replicas to work.

Granted, you'd be taking their word for it that they aren't sending in a mutation, but you could always throw an exception down the line when the GraphQL is actually parsed, if an actual mutation is attempted while `enableReplicas` is set to `true`.

So it might be a way people could opt-in to the read-only endpoint, without breaking the existing APIs. Just a thought!

**Comment by ccchapman** [comment]
Curious to hear if checking the `POST` body for `mutation` and sending that to a replica could have consequences. We use a Varnish caching layer which will cache these requests (and serve stale) unless the body contains that keyword. It has seemed fine in our use of it.

**Comment by ericdrosas87** [comment]
I do wonder if something like this could be a good stopgap solution for the next minor release?:

```
        $body = json_decode($request->rawBody);
        $graphQlQueryInBody = property_exists($body, "query");
        if (!$skipSpecialHandling) {
            // Process resource requests before anything else
            $this->_processResourceRequest($request);
            // Disable read/write splitting for POST requests
            if (
		    $request->getIsPost() &&
		    !$graphQlQueryInBody &&
                !in_array($request->getActionSegments(), [
                    ['element-indexes', 'count-elements'],
                    ['element-indexes', 'data'],
                    ['element-indexes', 'export'],
                    ['element-indexes', 'get-elements'],
                    ['element-indexes', 'get-more-elements'],
                    ['element-indexes', 'get-source-tree-html'],
                ])
	    ) {
                $this->getDb()->enableReplicas = false;
	    }
```

This admittedly would not make use of `Request->getIsGraphql()` as that checks to see if the `Content-Type: application/graphql` of the header and the code above relies on `Content-Type: application/json`, but as I understand it that is how many graphQL client libraries send requests by default.

**Comment by ericdrosas87** [comment]
Another option is relying on some custom headers, headers are already being retrieved just after the `if` block. Something like `X-Force-Read-Replica: true` or some such could also work.

**Comment by brandonkelly** [comment]
Fixed for the next release, for any requests that explicitly point to the `graphql/api` action, or include the `Content-Type: application/graphql` header.

Mutations aren’t really a concern. `INSERT`/`UPDATE`/`DELETE` queries will always go to the primary connection. The `enableReplicas = true` code is just an optimization to avoid an extra DB connection to the replica, in cases where it will most likely not be needed.

**Comment by khalwat** [comment]
Not seeing the check for `Content-Type: application/graphql` in the patch above?

**Comment by brandonkelly** [comment]
@khalwat 

https://github.com/craftcms/cms/blob/066857df5a2d5f426f45b93384db05ccb23a2077/src/web/Application.php#L176

**Comment by ericdrosas87** [comment]
Thank you @brandonkelly ! Do you have any rough ETA on when you will be cutting that release?

**Comment by brandonkelly** [comment]
Craft 4.7.3 is out now with that change.
