### ISSUE TITLE
[5.x]: eagerly() not working?

### ISSUE THREAD

**Issue by smcyr** [craftcms/cms#14334]
My comprehension of `.eagerly()` is that it automatically eager loads fields without the need to specify each individual field with `.with()`. So I tried it with Craft 5 beta and it doesn't seem to reduce the number of queries. 

For example, I have this query on my homepage:

```twig
{% for page in craft.entries.section("pages").all() %}
```

The debug toolbar reports 99 database queries. If I try with `eagerly()`:

```twig
{% for page in craft.entries.section("pages").eagerly().all() %}
```

It still reports 99 queries. But if I use `.with()`:

```twig
{% for page in craft.entries.section("pages").with([
                    "testMatrix",
                    "testMatrix.testEntryType1:testNestedMatrix",
                    "testMatrix.testEntryType1:testMatrix2"
]).all() %}
```

It reports 45 database queries.

Can you clarify how to use it and what it does exactly please.

Thank you

**Comment by brandonkelly** [comment]
> My comprehension of .eagerly() is that it automatically eager loads fields without the need to specify each individual field with .with().

Not quite. It can be used on the _nested queries_ that would normally have been eager-loaded ahead of time via `with()`.

```twig
{% for page in craft.entries.section("pages").all() %}
  {% for block in page.testMatrix.eagerly().all() %}
    {% for nestedBlock in block.testNestedMatrix.eagerly().all() %}
      ...
    {% endfor %}
  {% endfor %}
{% endfor %}
```

**Comment by smcyr** [comment]
Ok, it makes sense, thank you for the clarification, it is a really nice addition!

**Comment by agosman** [comment]
How would I define `eagerly` when fetching an entry with a Matrix field that has an entry type with an assets field inside? 
I can't seem to find it anywhere in the GraphQL API documentation.

Thanks.
