### ISSUE TITLE
[4.x]: Relations not being removed when a site is being delete for a single site

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#14347]
### Description

When using the **Delete for site** action, the relations table is not updated to remove relations for that particular site. This is the case when **Manage relations on a per-site basis** is activated (haven't checked if this also happens without this setting). This is causing problems, because the relations are "leaking" to other sites in some cases – I'll open a separate issue for that.

### Steps to reproduce

1. Create an entry in a section with custom propagation and propagate it to multiple sites.
2. In an entries field with the option mentioned above turned on, select some entries (in every site the entry is propagated to).
3. Use the **Delete entry for this site** action to delete the entry in some sites (but not all of them).
4. Check the `relations` table in the database. It will still contain the relations for the deleted sites.

### Expected behavior

Deleting a propagated entry for a single site should remove all its relations from the `relations` table, so they can't interfere with entry queries.

### Actual behavior

Relations for deleted propagated entries are remaining the `relations` table and causing problems.

Related to #13956

### Craft CMS version

4.7.2.1

### PHP version

8.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 4.7.3 is out with a fix.

**Comment by jakobhaerter** [comment]
Thanks @brandonkelly and @i-just on behalf of @MoritzLost. This seems to have fixed the issue 🙏

**Comment by brandonkelly** [comment]
Thanks for checking!
