### ISSUE TITLE
[5.x]: Super Table fields don't get unique names/handles

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#14344]
### Description

It appears that during the content migration, fields that were used in SuperTable were not given unique names or handles.

![CleanShot 2024-02-09 at 11 33 12](https://github.com/craftcms/cms/assets/3810939/14593163-c76b-445b-b888-da82c4071939)

As a side note, I think it would be smart to make the migration's console output a bit more verbose to show which fields are migrated, what their old and new handles are, etc.

### Craft CMS version

5.0.0-beta.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
We only require field handles to be unique within a certain context. In that screenshot, each of the fields listed have a unique context.

My understanding is that the Craft 5 port of Super Table is going to be entrifying the nested ST rows, so they will end up getting renamed to something unique for the `global` context during its upgrade migration.

**Comment by Mosnar** [comment]
> We only require field handles to be unique within a certain context. In that screenshot, each of the fields listed have a unique context.
> 
> 
> 
> My understanding is that the Craft 5 port of Super Table is going to be entrifying the nested ST rows, so they will end up getting renamed to something unique for the `global` context during its upgrade migration.

Does it make sense that these are showing up in the field entry list in the control panel? That's what I'm currently seeing that prompted me to open this issue.

**Comment by brandonkelly** [comment]
5.0.0-beta.2 is out now with that fix.
