### ISSUE TITLE
[5.x]: Tags field breaks functionality of other fields

### ISSUE THREAD

**Issue by marcusgaius** [craftcms/cms#14356]
### Description
Adding a tags field to an entry type breaks modal loading and other functionalities for most subsequent fields.

### Steps to reproduce

1. Add a Tag group and a tags field
2. Add the field to a field layout
3. Add multiple different fields to the layout before and after the field

### Expected behavior
All fields work as intended

### Actual behavior
Any fields added in front of the tags field works normally, _any_* fields added after the tags field don't work.
Removing the Tags field again restores the functionality of all subsequent fields.

#### Not working
* Country
* Entries
* Assets
* Table
#### Working
* Lightswitch

### Craft CMS version

5.0.0-beta.1

### PHP version

8.2.13

### Operating system and version

Debian GNU/Linux 11 (bullseye) (ddev 1.22.6)

### Database type and version

MariaDB 8.0.33

### Image driver and version

ImageMagick 6.9.11-70 | GD 2.3.3

### Installed plugins and versions

- no plugins installed

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
5.0.0-beta.2 is out now with that fix.
