### ISSUE TITLE
[5.x]: Disclosure menus stacking

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#14354]
### Description

Open disclosure menus generally auto-close if the user clicks anywhere outside the disclosure menu container, **except** if the thing clicked is another disclosure menu trigger. This feels a bit odd – especially with element cards, as multiple open disclosure menus in close proximity can become "stacked":

https://github.com/craftcms/cms/assets/298510/ec40376d-a806-418d-a3ef-d4b667d3b506

### Steps to reproduce

1. Click on a disclosure menu trigger
2. Without closing the disclosure menu or clicking anywhere else on the page, click a different disclosure menu trigger

### Expected behavior

Open disclosure menus should close when the user clicks outside the disclosure menu.

### Actual behavior

Open disclosure menus are generally closed when clicking outside their container, but not when clicking on a different disclosure menu trigger.

### Craft CMS version

5.0.0-beta.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Fixed for the next release!

**Comment by brandonkelly** [comment]
5.0.0-beta.2 is out now with that fix.
