### ISSUE TITLE
Redactor 2.2 unordered list not showing bullets

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#1435]
### Description

The proper markup is generated when viewing source, but no bullets are showing in the front-end view.

![2017-02-27_11-09-54](https://cloud.githubusercontent.com/assets/61869/23375477/662d421c-fcdd-11e6-87c4-c20803141c07.png)

### Steps to reproduce

1. Run Redactor 2.2
2. Create an unordered list.
3. Revel in the nothingness.

### Additional info

- Craft version: 2.x and 3.x
- PHP version: n/a
- Database driver & version: n/a
- Plugins & versions: n/a

**Comment by paulgoodfield** [comment]
Looks like this same bug might have been reintroduced on Redactor 2.7.2? Again, the proper markup is being generated but the bullets are not displaying inside the Redactor field.

<img width="550" alt="Screenshot 2020-08-28 at 09 48 26" src="https://user-images.githubusercontent.com/1381838/91541121-bf382680-e913-11ea-9905-d26003d7df7b.png">

If I inspect the ul inside the field I can see it's picking up a `list-style: none` style from the `/cpresources/be50c637/css/cp/src/css/_reset.scss` file.

### Setup info

- Craft version: 3.5.7
- Plugins:
-- Colour Swatches: 1.3.3
-- Redactor: 2.7.2
-- Super Table: 2.6.2
