### ISSUE TITLE
[5.x]: Invalid field handle error is thrown on matrix fields who's handle has been updated/changed on an entryType

### ISSUE THREAD

**Issue by brionwolf** [craftcms/cms#14350]
### Description

Invalid field handle error is thrown on matrix fields who's handle has been updated/changed on an entryType

### Steps to reproduce

1. Create a matrix field _(ie: `My Favorite Matrix Field`)_.
2. Set the Matrix Field View Mode to "As inline-editable blocks".
3. Add the matrix field to another entryType associated with a section, global or category _(ie: `parent - Entry Type Alpha`)_.
4. From the field's settings menu on the parent entry type, update the matrix field's handle _(ie: `myFavoriteMatrixField` → `fooBar`)_
5. Attempt to create a new entry for the associated parent entry type _(Section, Global, or Category)_.
6. Attempt to add a block for the matrix field created/added in steps 1 to 4.

### Expected behavior

- The associated form of input fields associated with the entry type of the matrix field should appear and allow a content editor to update it.

### Actual behavior

The page loads, indicates the field has been updated _(bold blue border along the left edge)_, but no block is added. YII/Craft console indicate a 500 error has been thrown with the following trace:

```
craft\errors\InvalidFieldException: Invalid field handle: blocksHeroSingle in craft/vendor/craftcms/cms/src/base/Element.php:5846
Stack trace:
#0 craft/vendor/craftcms/cms/src/base/Element.php(4603): craft\base\Element->normalizeFieldValue('blocksHeroSingl...')
#1 craft/vendor/craftcms/cms/src/controllers/MatrixController.php(128): craft\base\Element->getFieldValue('blocksHeroSingl...')
#2 [internal function]: craft\controllers\MatrixController->actionCreateEntry()
#3 craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 craft/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#5 craft/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('create-entry', Array)
#6 craft/vendor/craftcms/cms/src/web/Application.php(315): yii\base\Module->runAction('matrix/create-e...', Array)
#7 craft/vendor/craftcms/cms/src/web/Application.php(616): craft\web\Application->runAction('matrix/create-e...', Array)
#8 craft/vendor/craftcms/cms/src/web/Application.php(294): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#9 craft/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 craft/web/index.php(12): yii\base\Application->run()
#11 {main}
```

In my example I tried renaming the handle for the matrix field `blocksHeroSingle` to `hero` when I added it to another entry type related to a page.

![animated gif of the invalid field handle error in the craft control panels](https://github.com/craftcms/cms/assets/5532234/3211adae-59c7-45cb-96c1-d33a42b1ee50)

### Workaround:

- Don't rename or change the handle name of the matrix field when adding it to another entry type. This is only an issue if you want to utilize two versions of the same matrix field on a single entry type _(which is rare)_.
- _**OR**_ Use either "As Cards" or "As an Element Index" as the matrix field View mode.

### Craft CMS version

Craft Pro 5.0.0-beta.1

### PHP version

8.3.1

### Operating system and version

MacOS Sonoma 14.3 (23D56)

### Database type and version

MySQL 8.2.0

### Image driver and version

GD 8.3.1

### Installed plugins and versions

- CKEditor | 4.0.x-dev

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

> This is only an issue if you want to utilize two versions of the same matrix field on a single entry type

Matrix fields don’t actually support multiple instances in the first place, since their content storage is much more involved than getting a value stored in the element’s `content` JSON blob.

**Comment by brandonkelly** [comment]
5.0.0-beta.2 is out now with that fix. Thanks again!

**Comment by brionwolf** [comment]
Thanks @brandonkelly !

**Comment by sleithart** [comment]
i'm running into a similar error on version 4.8.4:
```
2024-03-22 13:32:08 [queue.ERROR] [craft\queue\QueueLogBehavior::afterError]  [73198] t9n:["neo","Saving Neo block structures for duplicated elements"] (attempt: 1, pid: 2526) - Error (time: 13.209s): Invalid field handle: pageBuilder {"memory":222279024} 
2024-03-22 13:32:08 [queue.ERROR] [craft\errors\InvalidFieldException] craft\errors\InvalidFieldException: Invalid field handle: pageBuilder in /var/www/html/vendor/craftcms/cms/src/base/Element.php:5340
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/base/Element.php(4173): craft\base\Element->normalizeFieldValue('pageBuilder')
#1 /var/www/html/vendor/spicyweb/craft-neo/src/jobs/ResaveFieldBlockStructures.php(62): craft\base\Element->getFieldValue('pageBuilder')
#2 /var/www/html/vendor/yiisoft/yii2-queue/src/Queue.php(243): benf\neo\jobs\ResaveFieldBlockStructures->execute(Object(craft\queue\Queue))
#3 /var/www/html/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage('73198', 'O:40:"benf\\neo\\...', '300', 1)
#4 /var/www/html/vendor/craftcms/cms/src/queue/Queue.php(191): yii\queue\cli\Queue->handleMessage('73198', 'O:40:"benf\\neo\\...', '300', 1)
#5 /var/www/html/vendor/craftcms/cms/src/queue/Queue.php(166): craft\queue\Queue->executeJob()
#6 [internal function]: craft\queue\Queue->craft\queue\{closure}(Object(Closure))
#7 /var/www/html/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func(Object(Closure), Object(Closure))
#8 /var/www/html/vendor/craftcms/cms/src/queue/Queue.php(174): yii\queue\cli\Queue->runWorker(Object(Closure))
#9 /var/www/html/vendor/craftcms/cms/src/controllers/QueueController.php(82): craft\queue\Queue->run()
#10 [internal function]: craft\controllers\QueueController->actionRun()
#11 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#13 /var/www/html/vendor/yiisoft/yii2/base/Module.php(553): yii\base\Controller->runAction('run', Array)
#14 /var/www/html/vendor/craftcms/cms/src/web/Application.php(341): yii\base\Module->runAction('queue/run', Array)
#15 /var/www/html/vendor/craftcms/cms/src/web/Application.php(642): craft\web\Application->runAction('queue/run', Array)
#16 /var/www/html/vendor/craftcms/cms/src/web/Application.php(303): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#17 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /var/www/html/web/index.php(12): yii\base\Application->run()
```

this happens when i try to update the translation propagation for an existing neo field on my site. is this related?

**Comment by brandonkelly** [comment]
@sleithart That’s going to be unrelated to this issue, which only affected Craft 5.

You might want to start by posting on the [Neo repo](https://github.com/spicywebau/craft-neo) since it looks like a Neo-specific error.
