### ISSUE TITLE
[5.x]: Orphaned matrix block entry when using "Save as New Entry" from the edit in a new tab view

### ISSUE THREAD

**Issue by brionwolf** [craftcms/cms#14378]
### Description

Orphaned matrix block entry when using "Save as New Entry" from the edit in a new tab view.

### Steps to reproduce

1. Create a matrix field with at least one entry type, and add it to a layout.
2. Add an block entry to the matrix field, and save.
3. Click to edit the new block and open it in a new tab.
4. From the Save button dropdown select "Save as a new entry"
5. Make any minor change to the the new block entry, and save it.
6. Return to the parent entry with by navigating back to the previous tab, or clicking from the parent entry from the global header breadcrumb list.

### Expected behavior

See the previously created block in the matrix field as well as the newly created block.

### Actual behavior

Only see the previously created block, the new one is not in the matrix field block list. It is not accessible unless that tab where it was created is still accessible.

- Issue occurred both in pro and solo
- Issue occurred using inline, card, or index matrix views

![Animated gif of attempting to create a matrix entry from a new tab](https://github.com/craftcms/cms/assets/5532234/cce3723b-3daa-4485-bdf4-bc7c6369b517)

### Craft CMS version

Craft Pro 5.0.0-beta.1

### PHP version

8.3.1

### Operating system and version

MacOS Sonoma 14.3.1 (23D60)

### Database type and version

MySQL 8.2.0

### Image driver and version

GD 8.3.1

### Installed plugins and versions

- CKEditor | 4.0.x-dev

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brionwolf** [comment]
Thanks @i-just! thanks @brandonkelly!
