### ISSUE TITLE
[4.x]: Creating a number field with decimal points over 30 causes a database error

### ISSUE THREAD

**Issue by peteluffman** [craftcms/cms#14370]
### Description

Creating a number field with decimal points over 30 causes a database error that bricks the site and admin because a DB column is missing.

### Steps to reproduce

1. Create and save new number field 
2. Add field to an entry type (not 100% sure if this step is required)
3. Amend decimal point above 30 (I used 99)
4. Save field

### Expected behavior

Field validation should prevent the SQL query being run.

### Actual behavior

SQL error saying the column could not be created with a length above 30. 

Subsequently, the admin and public facing website becomes fully broken because it can't find the field column in the content table. To recover, I had to manually run a SQL query to create the missing column with a decimal type.

 

### Craft CMS version

4.7.1

### PHP version

8.1.26

### Database type and version

MySQL 8.0.33

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 4.7.3 is out with the fix for this. Thanks again!
