### ISSUE TITLE
[4.x]: Site disabled on multisite page

### ISSUE THREAD

**Issue by idleog** [craftcms/cms#14383]
### Description
I have a multisite with tree different languages (en,de,fr). fr is disabled permanently for the moment, en and de is enabled. 
Now it happened fot the second time that the german site  is disabled without doing anything in the settings dashboard (it's only me with acces to the settings).

The only idea I have is that it's because it's still a trial pro version, as the project is in staging phase. 

### Craft CMS version

CraftCMS 4.7.2

### PHP version

8.2.13

### Operating system and version

Linux 3.10.0-962.3.2.lve1.5.79.el7.x86_64

### Database type and version

MySQL 5.7.41

### Image driver and version

magick 3.7.0 (ImageMagick 7.1.1-19)

### Installed plugins and versions

Cloner 2.0.4
Control Panel Body Classes 2.3.0
Control Panel CSS 2.6.0
Cookies 4.0.0
Field Manager 3.0.8	
Goeldi 4.0.0 (own plugin)
Incognito Field 1.3.0
Redactor 3.0.4
Redirect Manager 2.0.1
Site Switcher 2.3.0
Super Table 3.0.12
Typed link field 2.1.5

**Comment by brandonkelly** [comment]
Nothing in Craft would automatically disable a site without being told to do so.

Perhaps someone is deploying with the German site disabled from `config/project/sites/`, and so the site is getting disabled when the project config YAML files are being applied?

**Comment by idleog** [comment]
Ok... thanks, and 'someone' could mean myself :)
Cheers!
