### ISSUE TITLE
[3.x]: Upload of multiple assets over existing ones is buggy when confirming individually

### ISSUE THREAD

**Issue by hiasl** [craftcms/cms#14405]
### Description
- When uploading multiple files over existing ones, Craft 3's behavior is buggy. Generally you have 2 options when uploading files over existing ones: 
- keeping both
- replace the existing ones
There is also an option (checkbox) to apply the behavior to all files uploaded or each by each.
If the checkbox is checked, everything works as expected. But with the checkbox NOT being checked, it does not work. 

I also tried it in Craft 4, here everything works.

See below:

Bugs:
<img width="417" alt="Bildschirmfoto 2024-02-16 um 12 22 04" src="https://github.com/craftcms/cms/assets/800026/8a8b7b20-bc2a-4faa-8688-50720d9d6191">
- IS: After clicking OK, all files are kept, uploaded files get new names, only one confirmation appears for the first file, and the asset overview does not refresh
- SHOULD: After clicking OK only the first file should be kept, additional confirmations should appear for the other files, finally  the asset overview should reload

<img width="415" alt="Bildschirmfoto 2024-02-16 um 12 28 38" src="https://github.com/craftcms/cms/assets/800026/6fdd1ea0-64cf-4f2b-aee6-f644c71a5c62">

- IS, same as above: After clicking OK, all files are kept, uploaded files get new names (instead of actually being replaced as chosen), only one confirmation appears for the first file, and the asset overview does not refresh
- SHOULD: After clicking OK only the first file should be replaced, additional confirmations should appear for the other files, finally the asset overview should reload

### Steps to reproduce

1. Take 2 or more files and drag them into an asset volume
2. Take the same files and try again, either choose keep or replace, but do NOT check the checkbox to apply to all remaining assets.

### Craft CMS version

3.9.10

### PHP version

8.1.26

### Operating system and version

DDEV / Linux

### Database type and version

MySQL 8

### Image driver and version

IM 3.7

### Installed plugins and versions

- none

**Comment by brandonkelly** [comment]
Thanks for reporting that. For some reason we had assumed that bug was introduced in 4.0 and didn’t check v3.

Just backported the fix for the next v3 release. Can’t tell you when that will be though. So to get the fix early, change your `craftcms/cms` requirement in composer.json to `v3.x-dev as 3.9.10`, and run `composer update`.

**Comment by brandonkelly** [comment]
3.9.11 isou t now with that fix.
