### ISSUE TITLE
[4.x]: Setting a URL field to have a max length of '99999' will break your database

### ISSUE THREAD

**Issue by jamiepepper** [craftcms/cms#14408]
### Description

Setting a URL field to have a max length of '99999' will break your database

### Steps to reproduce

1. Add a URL field.
2. Set the Max Length to 99999 and click save

### Expected behavior

I should be warned for an upper limit for the field max size

### Actual behavior

It causes the DB to break

https://github.com/craftcms/cms/assets/144788054/89669fdf-31d4-4983-815f-f874ece99833

### Craft CMS version

4.7.2.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.
