### ISSUE TITLE
Paginate always return a total page of 1

### ISSUE THREAD

**Issue by my2ter** [craftcms/cms#1440]
### Description

Paginate always return a total page of 1. Let's say you have 5 pages in total and display 10 entries per page:

```
    {% set criteria = craft.entries({
        section: 'products',
        limit: null
    })%}

{% if paginate.currentPage < paginate.totalPages %}
<a href="{{ url(paginate.lastUrl, queryString) }}">{{ paginate.totalPages }}</a>
{% endif %}
```

The output will never display the link for the last page because currentPage = totalPages.

### Steps to reproduce

1. Create a section with 10 entries
2. Paginate following the example

### Additional info

- Craft version: 3.0.0-beta.5
- PHP version: 7.1
- Database driver & version: Mysql 5.7 
- Plugins & versions:

### Related ticket

Might be the same https://github.com/craftcms/cms/issues/1425

### Solution

I fixed the problem and will submit a PR soon but not sure it's the right way. Basically it is down to `helpers/Template.php::78` and its `paginateCriteria` and how the limit is set.

**Comment by brandonkelly** [comment]
Looks like the same underlying issue as #1425

**Comment by brandonkelly** [comment]
Ever so slightly different so will keep this open.
