### ISSUE TITLE
[3.x]: All plugins are missing

### ISSUE THREAD

**Issue by arlingga** [craftcms/cms#14400]
### Description

We have develop some minor update to our project which run in Craft CMS. The deployment to staging server is completed but somehow we got internal server error. We do some checking and we found that no plugins are available to Craft CMS. We see the deployment log and see the `composer install` actually run properly. They got the plugins downloaded and installed.

Additional information. We did some deployment test to our other projects which turns out facing the same issue. We use docker to build the image. Some environment we are using are AWS using bitbucket pipelines, Azure using Azure pipelines.

### Steps to reproduce

1. Do deployment to server

### Expected behavior

The website running properly

### Actual behavior

The website showing internal server error caused by plugins throwing null error (seems like the plugin is not available and not accessible).

<img width="935" alt="Screenshot 2024-02-16 at 1 54 58 PM" src="https://github.com/craftcms/cms/assets/1292039/c98abd82-f553-4963-bb67-ba5ea1776367">
<img width="287" alt="Screenshot 2024-02-16 at 1 54 27 PM" src="https://github.com/craftcms/cms/assets/1292039/28f2f8cf-634c-4958-b717-f6da469619f5">
<img width="946" alt="Screenshot 2024-02-16 at 1 28 16 PM" src="https://github.com/craftcms/cms/assets/1292039/ec433e80-7a93-4b98-915c-679e57c6831a">

### Craft CMS version

3.9.10

### Installed plugins and versions

-

**Comment by arlingga** [comment]
Sorry guys, this is not Craft issue. It was between PHP and Composer. For now we choose to downgrade the Composer to 2.6.6. I put the link here from Composer issue page, just in case someone havinge similar issue. Cheers

https://github.com/composer/composer/issues/11839

**Comment by arlingga** [comment]
Hi @sschamp yap we have tried the `COMPOSER_ALLOW_SUPERUSER=1` but the issue still persist. We have planned to upgrade the PHP and CraftCMS also, and we stick to Composer 2.6.6 to fix the issue at the moment.

**Comment by danbrellis** [comment]
I used to install and run composer as root in my dockerfile, but updated the relevant section below and it deploys to AWS Beanstalk now:

```
# Install composer (composer.json resides in /var/www)
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin/ --filename=composer
RUN chown -R www-data:www-data /var/www
RUN chmod -R 774 /var/www

USER www-data

RUN composer install
```

**Disclaimer**- I'm no security expert, so if anyone sees a security issue, please let me know.
