### ISSUE TITLE
[5.x]: badge count overflow issue

### ISSUE THREAD

**Issue by lukeholder** [craftcms/cms#14406]
### Description

Overflow issue with double digit numbers in source badge count.

![CleanShot 2024-02-16 at 20 10 57@2x](https://github.com/craftcms/cms/assets/133571/09dddc64-f120-48e6-8cf0-17c1b90eeec2)

Also, the data attributes for the badge count default to calling it a "notification". Maybe in the element `Element::defineSources()` we could pass a name for the badge count?

![CleanShot 2024-02-16 at 20 14 03@2x](https://github.com/craftcms/cms/assets/133571/dd8bb666-44e7-47ff-b5ce-562f80743862)

### Craft CMS version

5.x

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Both of those are resolved for the next release via #14409 and #14410.
