### ISSUE TITLE
[4.x]: Asset Browser crashes when quickly switching between sources with different upload permissions

### ISSUE THREAD

**Issue by mnlmaier** [craftcms/cms#14403]
### Description
When quickly changing asset sources in the Control Panel's Asset Browser, JS crashes occur when permissions need to be adjusted for the upload functionality.

The Error Stack Trace in the JS Console looks as follows:
```
jquery.js?v=1702329863:2 Uncaught Error: cannot call methods on fileupload prior to initialization; attempted to call method 'option'
    at Function.error (jquery.js?v=1702329863:2:2623)
    at HTMLButtonElement.<anonymous> (jquery-ui.js?v=1702329863:2:2391)
    at Function.each (jquery.js?v=1702329863:2:3002)
    at w.fn.init.each (jquery.js?v=1702329863:2:1482)
    at t.fn.<computed> [as fileupload] (jquery-ui.js?v=1702329863:2:2129)
    at s.constructor.setParams (Uploader.js:43:21)
    at s.constructor.e [as setParams] (Base.js:76:36)
    at s.constructor.onSourcePathChange (AssetIndex.js:296:24)
    at s.constructor.e [as onSourcePathChange] (Base.js:76:36)
    at set sourcePath (BaseElementIndex.js:914:12)
```

I am pretty sure that the solution might just be to check for `this.uploader` before calling `this.uploader.fileupload()`, e.g. by calling it via `this.uploader?.fileupload()` and waiting for it until it's actually defined. still, i'm pretty sure that some more measures need to be taken care of.

In the code: https://github.com/craftcms/cms/blob/develop/src/web/assets/cp/src/js/Uploader.js#L43

### Steps to reproduce
1. Create two asset sources / volumes in the Asset browser
2. Assign the following permissions to a test user: Can upload in volume 1, can only view volume 2
3. Quickly switch between the volumes / sources several times while observing the JavaScript console
4. Notice that the script is crashing and the "upload files" button will not change its `disabled` state
5. Notice that this behavior does not happen when changing sources more slowly.

(Please note that this will be relevant for users which share the same permissions across all asset sources).

### Expected behavior
Permissions for the upload button are adjusted on the fly, including its `disabled` state.

### Actual behavior
`this.uploader.fileupload` will be called in `Uploader.js` while `this.uploader` actually not being defined, which leads to completely crashing the JavaScript.

### Craft CMS version

Craft Pro 4.5.5

### PHP version

8.3.2

### Operating system and version

Darwin 23.2.0

### Database type and version

MySQL 8.0.27

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.1-27)

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.7.4 is out with that fix.

**Comment by mnlmaier** [comment]
Thanks a lot @brandonkelly
