### ISSUE TITLE
[4.x]: Cannot use [null, 1] value in "level" element query method if i querying for entries from channel sections

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#14419]
### Description

Recently when working on php module, i needed to query entries. I did not knew if element query would contain channel sections or structure sections, or mix of both (depends on user input). I wanted to query for all channel entries, or in case of structure, only for level 1 entries.

That's why i wanted to do something like this: ` ->level([null, 1])` - since level on channel entries equals `null`. This however returned zero entries, if queried for entries from channel sections. If i queried for entries from structure sections only, it worked fine.

### Craft CMS version

4.7.2.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Just made this possible for Craft 4.8 (1140ea3fc4b8c5aa6cffbb0f7e620cbb5b81b064).

To get on the `4.8` branch before it’s released, change your `craftcms/cms` requirement in composer.json to `4.8.x-dev as 4.8.0-alpha`, and run `composer update`.

**Comment by brandonkelly** [comment]
Craft 4.8.0 is tagged now, with that change.
