### ISSUE TITLE
[5.0.0-beta.2]: Is a `config/project/fieldGroups` folder expected after a fresh install?

### ISSUE THREAD

**Issue by kylecotter** [craftcms/cms#14412]
### Description
After fresh installing 5.0.0-beta.2 the project config folder contains a `fieldGroups` folder with the Common group setup. Is this still expected with field groups going away?

### Steps to reproduce

1. Install Craft 5 fresh
2. Look at output project config folder

### Craft CMS version

5.0.0-beta.2

### PHP version

8.2.15

### Operating system and version

Linux 6.6.12-linuxkit

### Database type and version

MySQL 8.0.30

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.1-13)

**Comment by brandonkelly** [comment]
Nope that was overlooked. Thanks for pointing it out!
