### ISSUE TITLE
[5.x]: Earth icon not localised in element index pages

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#14415]
### Description

The Earth icon is not being localised in element index pages.

### Steps to reproduce

1. Have a multi site setup.
2. Set the system time zone to GMT.
3. Visit the Entry index page.

### Suggestion

The earth icon output in Twig templates should go through the `Cp::earthIcon()` method.

The Entry index page shows the Americas:

![Screenshot 2024-02-16 at 21 39 12](https://github.com/craftcms/cms/assets/57572400/3cf008f6-c59b-4edf-a7f5-f5433003f621)

The Entry edit page shows Europe:

![Screenshot 2024-02-16 at 21 39 30](https://github.com/craftcms/cms/assets/57572400/f875c7bf-bb11-4193-849c-1c8e89b107dc)

### Craft CMS version

5.0.0-beta.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 5.0.0-beta.3 is out with that fix. Thanks again!
