### ISSUE TITLE
[5.x]: Matrix Title missing in serializeValue()

### ISSUE THREAD

**Issue by lukasNo1** [craftcms/cms#14428]
### Description

Matrix Blocks can now have a title field in the entry types, but this field is lost when using craft\fields\Matrix->serializeValue()

https://github.com/craftcms/cms/blob/5.0.0-beta.2/src/fields/Matrix.php#L740

I added 'title' => $entry->title, to this line locally and then it worked as expected. 

My usecase is for the sitecopy plugin where we use serializeValue to copy the matrix block over to another entry, but with the title not being serialized, we loose that value.
https://github.com/Goldinteractive/craft-sitecopy/blob/master/src/services/SiteCopy.php#L329

### Craft CMS version

5.0.0-beta.2

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.0.0-beta.3 is out with the fix for this. Thanks again!
