### ISSUE TITLE
Cannot edit Post Date, saving entry resets to time of last save.

### ISSUE THREAD

**Issue by ChanceArthur** [craftcms/cms#1442]
### Description

After editing some older entries I noticed the order of entries on the front-end of my development website was wrong. It turns out that after every save, an entry has its post date reset to the time the last save occurred. Attempting to specify a different post date does not work. For example, I've tried to set a post date to Feb 15 at 12:00 AM. I click "Save", and then when I view the entry in the entires list, the post date instead displays the time that I last saved my edit.

### Steps to reproduce

1. Create or edit an entry.
2. Attempt to specify a post date.
3. Click "Save".
4. Return to list of entries and see post date has been reset to time of last saved edit.

### Additional info

- Craft version: 3.0.0-beta.5
- PHP version: 7.0.16
- Database driver & version: MariaDB 10.1.21
- Plugins & versions: Doxter	3.0.6, Minify 1.2.2, Rich Variables 1.0.6

**Comment by takobell** [comment]
I'm not able to reproduce this using MySQL or PostgreSQL. If I create a new entry on beta 5, specify a post date of 4/7/2017, save the entry, then the entry index page properly shows 4/7/2017 in the post date column for that entry.

If you're entry index listing is on the front-end of the site, you sure it's not just a templating problem?
