### ISSUE TITLE
[5.x]: Keyboard shortcut for "Preview file" quick action working only when the title of the thumbnail is focused.

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#14420]
### What happened?

On the relase notes for Craft 5 there is the following item:

> Selected assets within Assets fields no longer open the file preview modal when their thumbnail is clicked on. The “Preview file” quick action, or the Shift + Spacebar keyboard shortcut, can be used instead.

Having selected a thumb, I tried to use the shortcut to no avail and initialy I thought it wasn't working at all. Upon further investigation I realised that the thumbnail's title must be focused for the shortcut to take effect.

Is this intentional? I does feel awkward.

### Craft CMS version

5.0.0-beta.2

### Installed plugins and versions

-

**Comment by thupsi** [comment]
@brandonkelly The shortcut still doesn't work in Craft 5:

- Select an image thumbnail in an asset field. The thumbnail is focused.
- Press `Shift` + `Spacebar`. Nothing happens.
- Press `tab`. The thumbnail's _title_ is focused.
- Press `Shift` + `Spacebar`. The preview opens.

**Comment by brandonkelly** [comment]
Sorry, I was only testing with keyboard navigation. Fixed now for the next release.

**Comment by thupsi** [comment]
Works perfectly now, thanks!

**Comment by brandonkelly** [comment]
5.0.0-beta.4 is out now with that fix. Thanks again!

**Comment by carlcs** [comment]
@brandonkelly Is this also intended to work on the assets index page? Additionally, I'd like to make a feature request to allow keyboard navigation to the next/previous asset, similar to how you can do with Quicklook on a Mac.
