### ISSUE TITLE
[5.0.0-beta.2]: Sort order of matrix blocks (card view) not retained after edit in slideout

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#14427]
### Description

Matrix field with View Mode: Cards

![image](https://github.com/craftcms/cms/assets/60010597/525f3351-d2b3-48c7-bd1f-f63bfa7b0087)

After editing a matrix block via slideout, it looks correct at first:

![image](https://github.com/craftcms/cms/assets/60010597/d31082c7-92e3-422a-9dbc-172d64e8afc2)

After refreshing the page, the sort order has changed:

![image](https://github.com/craftcms/cms/assets/60010597/8fe2a5bf-045f-4267-b976-1cf8967ac636)

### Steps to reproduce

1. Have a matrix field with View mode: Cards
2. Create an entry with a number of blocks.
3. Edit and save matrix block in slideout. (No provisional draft created for the main entry)
4. Refresh page

### Expected behavior

Sort order is retained.

### Actual behavior

It is not.

### Craft CMS version

5.0.x-dev as 5.0.0-beta.2

### PHP version

8.2.13

### Operating system and version

Linux 5.15.133.1-microsoft-standard-WSL2

### Database type and version

MySQL 8.0.33

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.0.0-beta.3 is out with that fix. Thanks again!
