### ISSUE TITLE
[4.x]: wrong type annotation in generated CustomFieldBehavior

### ISSUE THREAD

**Issue by d--j** [craftcms/cms#14421]
### Description

https://github.com/craftcms/cms/blob/c51f7309cf66dc13f20ffa2943400c160da51fc5/src/behaviors/CustomFieldBehavior.php.template#L31-L34

the type annotation `string[]` is wrong here. What gets generated is a `bool[]` or more specifically an `array<string,bool>`:
```php
    public static $fieldHandles = [
        'field1' => true,
        'field2' => true,
        'field3' => true,
    ];
```

PHPStan (level 5) trips over this.

A stub file like this

```php
<?php

namespace craft\behaviors;

class CustomFieldBehavior
{
    /**
     * @var array<string,bool>
     */
    public static $fieldHandles = [];
}
```

fixes this but you might just want to use the correct type annotation in the first place so this stub is not necessary anymore.

### Craft CMS version

4.7.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.7.4 is out with that fix. Note you’ll need to run `php craft clear-caches/compiled-classes` to regenerate `CustomFieldBehavior`.
