### ISSUE TITLE
[5.0.0-beta.2]: asset field instances

### ISSUE THREAD

**Issue by samuelbirch** [craftcms/cms#14437]
### Description
Asset fields are able to be reused like a text field is in the field layout designer

### Craft CMS version

5.0.0-beta.2

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, can you please provide the expected and actual behaviour and replication steps for this?

**Comment by samuelbirch** [comment]
Hi,

Expected behaviour: be able to reuse an asset field multiple times in a field layout designer, like with a text field.

Actual behaviour: after using the field once, it no longer appears in the fields list so therefore can not be reused.

Recreation steps:
1. create an asset field
2. use it within a field layout designer
3. try to use it again.

**Comment by i-just** [comment]
Thanks for clarifying! That’s expected behaviour. There’s additional info about it here: https://github.com/craftcms/cms/issues/14237.
