### ISSUE TITLE
[5.x]: Unable to update the label/handle on multiple instances of Colour fields on entry types.

### ISSUE THREAD

**Issue by milesjbland** [craftcms/cms#14435]
### Description

When adding fields to an entry type, I'm able to add multiple instances of the same field. For example, a single Plain Text field can be added twice, and I can rename the label and handle on each.

However, this doesn't seem to work with Colour fields. When I rename the label or handle, it does it for all instances of the field. And, it even saves it on the underlying field itself.

### Steps to reproduce

1. On a fresh install, create a single Colour field. E.g. `Colour`/`colour`
2. Add at least 2 instances of it to an entry type.
3. Rename the label and/or handle on one instance. E.g. `Background Colour`/`backgroundColour`

### Expected behavior

The label and/or handle should only update for that instance of the field.

### Actual behavior

It updates the label and handles across all instances of the field, and it also updates it on the underlying field itself.

### Craft CMS version

5.0.0-beta.2

### PHP version

8.2

### Operating system and version

macOS 14.2.1

### Database type and version

mysql 8.0

### Installed plugins and versions

None

**Comment by milesjbland** [comment]
Ah yes, it was my fault! I was going **cog icon > edit field** in this instance. Thanks for your help!

**Comment by i-just** [comment]
Not a problem! Glad it’s clear now :)
