### ISSUE TITLE
[3.x]: Variable "name" does not exist in 

### ISSUE THREAD

**Issue by hassanmah** [craftcms/cms#14444]
### Description
Hi, I get this error after updating to 3.13.34

`Variable "name" does not exist in "__string_template__95d30eea6234fe79658fe25f6903d9ea1ffb2a4772c10e998882c6ee581566d3" at line 1.`

### Steps to reproduce

1. Submit a form

### Expected behavior
Form should submit

### Actual behavior
Twig Runtime Error - `Variable "name" does not exist in "__string_template__95d30eea6234fe79658fe25f6903d9ea1ffb2a4772c10e998882c6ee581566d3" at line 1.`

### Craft CMS version

3.9.10

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
This is going to be an issue with a Twig template within the project. String templates (`__string_template__x`) usually correlate to section’s entry URI formats, etc. You could try searching `storage/compiled_templates/` for `__string_template__95d30eea6234fe79658fe25f6903d9ea1ffb2a4772c10e998882c6ee581566d3` and see what it’s for.
