### ISSUE TITLE
[4.x]: GraphQL entry revision not returning Matrix fields

### ISSUE THREAD

**Issue by ph1lb4** [craftcms/cms#14448]
### Description
Querying an entry and its revision does only return Matrix fields for the entry but not its revisions.

### Steps to reproduce

1. Create an entry type with a Matrix.
2. Query all revisions for this entry type.
3. The revisions will not have the Matrix values attached, only the "normal" entry has.

### Expected behavior
The revisions return the Matrix fields with the value at the time of the revision

### Actual behavior
The revisions return no Matrix fields at all

<img width="1364" alt="image" src="https://github.com/craftcms/cms/assets/6817230/91b694c5-e701-46d3-b237-69672a74467e">

### Craft CMS version

4.7.3

### PHP version

8.1.27

### Operating system and version

Linux 6.3.13-linuxkit

### Database type and version

MariaDB 10.4.32

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- Amazon S3	2.0.3
- Redactor

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.8.0 is out now with that fix.

**Comment by ph1lb4** [comment]
That was fast @brandonkelly, thanks for the fix - and already confirmed it is working now!
