### ISSUE TITLE
[5.x]: Matrix fields not reusable in field layout designer

### ISSUE THREAD

**Issue by turnstylerj** [craftcms/cms#14443]
### Description
In the field layout designer where fields can now be re-used with custom handles, Matrix fields still disappear when they're dragged into the field layout.

### Steps to reproduce
1. Add a Matrix field to an entry type's field layout

### Expected behavior
Matrix field persists in the available field options and is able to be re-used with a new handle.

### Actual behavior
Matrix field disappears from available field options.

### Craft CMS version

5.0.0-beta.2

### PHP version

8.2.13

### Operating system and version

Linux 5.15.68-0-virt

### Database type and version

MySQL 8.0.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

"craftcms/ckeditor": "4.0.0-beta.6"
"nystudio107/craft-seomatic": "5.0.0-beta.5"

**Comment by brandonkelly** [comment]
That’s expected. Only fields that store content in the `content` table are reusable within a field layout.

**Comment by satcreative** [comment]
This is also the case with CKEditor fields. Are they also not expected to be reuseable?

**Comment by brandonkelly** [comment]
CKEditor 4.0.0-beta.8 is out now with multi-instance support 🎉

**Comment by MattWilcox** [comment]
Just to clarify, as I'm have been getting myself into knots with fields/entry-type/matrix since going deeper into scaffolding out Craft5... this fix is for CKeditor re-use, and not Matrix? So we can not pull in multiple instances of a single matrix-field into an Entry Type still?

**Comment by brandonkelly** [comment]
@MattWilcox Correct. Just mentioning it here since it came up in the discussion.

**Comment by dolphiq-allard** [comment]
First off, Craft 5 has some great improvements such as which reusing fields.

In regards to not being able to reuse matrix fields: same goes for the `entries` field. It would be great if these could be reused as well. I tend to allow our clients to select entries for e.g. the Contact page, privacy statement and disclaimer for use in various templates. If the entries field would be reusable this would save me creating separate fields for these items.

**Comment by humandevs** [comment]
+1 for this feature. This would be super awesome!

Content reuse is a big selling point of other "expensive" Composable CMS platforms such as Contentful, and even Enterprise Content Management systems like MadCap or Paligo. This follows the DRY (Don't Repeat Yourself) principle. Being able to find (search for) and insert nested, re-useable, atomic (matrix/neo fields) content in the GUI, would be great, and could let us keep one of our growing projects in Craft where this has been a consistent pain point for content creators dealing with knowledge-base content for related products.

For some examples/ideas from the "super duper expensive" CCMS/ECM platforms, here's how Contentful content re-use works: https://training.contentful.com/student/page/792577-reusing-content-across-compose
And Paligo: https://paligo.net/content-reuse/ (although this is a deep-copy and not a true instance)

**Comment by brandonkelly** [comment]
@dolphiq-allard @humandevs See https://github.com/craftcms/cms/discussions/8497#discussioncomment-9525050.
