### ISSUE TITLE
[5.x]: Expanding and collapsing structured entries not working

### ISSUE THREAD

**Issue by nickmerrill** [craftcms/cms#14453]
### Description
Entries aren't expanding and collapsing as expected.

### Steps to reproduce

1. Create multiple entries within a structure
2. Nest entries within parent entries at different levels
3. FYI, I added icons to each entry type

### Expected behavior
Parent entries expand and collapse to show and hide children entries

### Actual behavior
It's wonky :)

### Craft CMS version

5.0.0-beta.2

### PHP version

8.2

### Operating system and version

Darwin 23.2.0

### Database type and version

MySQL 8.0.29

### Image driver and version

GD 8.2.16

### Installed plugins and versions

None.

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.0.0-beta.4 is out with this fix. Thanks again!
