### ISSUE TITLE
[5.x]: Slideout sidebar collapses when fields in the content pane are clicked

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#14460]
### Description

The new ability to toggle slideout sidebars regardless of screen width (#14418) is cool. 

However, currently the sidebar automatically collapses if a field in the content pane is clicked, which I assume isn't intentional behavior: 

https://github.com/craftcms/cms/assets/298510/430cf3fd-d625-434d-bf58-311033f07dff

### Steps to reproduce

1. Open a slideout and click a field.

### Expected behavior

The sidebar should stay expanded.

### Actual behavior

The sidebar collapses every time a field is clicked (specifically clicked; focusing fields w/ the keyboard does nothing).

### Craft CMS version

5.0.0-beta.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 5.0.0-beta.4 is out with this fix. Thanks again!
