### ISSUE TITLE
[5.x]: Sidebar collapses when hitting the Escape key to close slideout

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#14461]
### Description

If attempting to close an open slideout with a visible/expanded sidebar, the sidebar will collapse, and the user needs to hit the Escape key a second time to actually close the slideout.

On Craft 4, this only happens on narrow screens, and feels like wanted behavior because the sidebar has necessarily been actively expanded by the user.

On Craft 5.0.0-beta.3, slideout sidebars are toggleable on all screen widths (#14418) and on wider screens the behavior feels less wanted, considering the user hasn't necessarily "expanded" the sidebar:

https://github.com/craftcms/cms/assets/298510/7619ee82-67a7-42e5-8c13-dd2dc65196f4

As far as I can tell this happens regardless of where the focus currently sits inside the slideout.

### Steps to reproduce

1. Open a slideout in a wide viewport, and hit the Escape key

### Expected behavior

The slideout should immediately close unless the user has actively expanded it.

### Actual behavior

The sidebar always collapses when hitting the Escape key. When the sidebar is collapsed, the Escape key closes the slideout.

### Craft CMS version

5.0.0-beta.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 5.0.0-beta.4 is out with this fix. Thanks again!
