### ISSUE TITLE
[5.x]: Page not found for nested entry when template column in site setting is not set for a matrix field

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#14464]
### What happened?
Craft throws a 'Page not found' error for nested entries inside matrix field when template column in site setting is not set, but Entry URI Format is set.

### Steps to reproduce

1. Create a matrix field
2. For nested entries, set only the Entry URI Format
3. Add matrix field to a layout and create a nested entry
4. Visiting nested entry page, throws a Page not found error

### Expected behavior
I guess this is an unintended behavior because for not nested entries, when template setting is empty, we see the index page as fallback not 'page not found'

### Craft CMS version

 5.0.0-beta.3

### Installed plugins and versions

Super Table - dev version for Craft 5

```[tasklist]
### Tasks
```

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR to keep this behaviour consistent with the not nested entries.

**Comment by brandonkelly** [comment]
Craft 5.0.0-beta.4 is out with this fix. Thanks again!
