### ISSUE TITLE
[5.0.0-beta.3]: Thumb image missing in 'My Drafts' dashboard widget

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#14486]
### Description

In the 'My Drafts' widget, thumbnail images are not shown:

![image](https://github.com/craftcms/cms/assets/60010597/6a9c0b8b-f846-4376-81d6-79e48ba42925)

This is how a part of the html markup looks like (present in all cardlets):

```html
<div class="thumb" data-sizes="calc(30rem/16)" data-srcset="https://craft50.ddev.site/files/images/featured/_30x16_crop_center-center_none/Schneewittchen-Remake1.jpg?v=1698323264%2C0.7724%2C0.3285 30w, https://craft50.ddev.site/files/images/featured/_60x33_crop_center-center_none/Schneewittchen-Remake1.jpg?v=1698323264%2C0.7724%2C0.3285 60w"></div>
```

There is no JavaScript error.

### Steps to reproduce

1. See image

### Expected behavior

Images are shown (I suspect...)

### Actual behavior

They are not.

### Craft CMS version

5.0.x-dev as 5.0.0-beta.3

### PHP version

8.2.13

### Operating system and version

Linux 5.15.133.1-microsoft-standard-WSL2

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.0.0-beta.4 is out with this fix. Thanks again!

**Comment by wsydney76** [comment]
Thanks, However, thumbs still don't load on initial page load for me:

![image](https://github.com/craftcms/cms/assets/60010597/517f4e03-156d-4a38-add0-dcfb13ae765d)

After editing and saving settings, they appear:

![image](https://github.com/craftcms/cms/assets/60010597/990d8610-3e62-4b56-b5ff-8fecef7284d2)

5.0.0-beta.4, no active plugins, no JS error.

**Comment by brandonkelly** [comment]
Doh… that was fixed in @i-just’s original PR, but I removed the change thinking the real issue was after saving settings. I guess it was a two-part bug and both fixes were needed. Just brought her change back for the next release.

**Comment by brandonkelly** [comment]
5.0.0-beta.5 is out with the second half of the fix.
