### ISSUE TITLE
[5.x]: Email field not showing when creating users with non-admin permissions

### ISSUE THREAD

**Issue by mei-lu** [craftcms/cms#14485]
### Description
The email field is missing when creating a new user as a non-admin.

### Steps to reproduce

1. Create a user group with the following permissions:
![image](https://github.com/craftcms/cms/assets/52755821/bc88839a-fa85-43fb-97cd-b3052b1a512a)

2. Impersonate a user in that user group and try to make a new user:
![image](https://github.com/craftcms/cms/assets/52755821/212c7392-047b-4439-ae2d-29e7cfed5c5b)

### Expected behavior
The email field appears and the user can be created.

### Actual behavior
Email field missing and errors.

### Craft CMS version

Craft Pro 5.0.0-beta.3

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.0.0-beta.4 is out with that fix. Thanks again!
