### ISSUE TITLE
[5.0.0-beta.3]: Nested entries disappear/reappear within inline Matrix block

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#14493]
### Description
There is a bug with nested entries inside inline Matrix blocks when disabling and enabling, with saves in between.

### Steps to reproduce

1. The entry looks like this:

![image](https://github.com/craftcms/cms/assets/19857599/7fde98b4-aadd-4360-90da-0723d30410a2)

2. Disable the "Section" block, then _save the entry_

3. Enable the same block, _save again_. You get this:

![image](https://github.com/craftcms/cms/assets/19857599/50034b44-734b-4712-ba42-dfd35277e047)

4. Refresh the page. The nested entries reappear:

![image](https://github.com/craftcms/cms/assets/19857599/f0114801-bccf-487a-a39e-0d199b077608)

### Craft CMS version

5.0.0-beta.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! 5.0.0-beta.4 is out with a fix.
