### ISSUE TITLE
[5.x]: Beta 3: "blocks" in Matrix getting re-ordered when editing a block's content.

### ISSUE THREAD

**Issue by MattWilcox** [craftcms/cms#14491]
### Description

The order of Blocks in a populated Matrix field spontaniously changes when the contents of a Block is edited from the slide-out pane.

### Steps to reproduce

Initial field:

<img width="844" alt="Screenshot 2024-02-28 at 14 18 43" src="https://github.com/craftcms/cms/assets/814039/6686df6b-3526-4b9b-b5dc-5d7e8c1c9d15">

Double click the Image at top and edit the content.

<img width="1216" alt="Screenshot 2024-02-28 at 14 19 36" src="https://github.com/craftcms/cms/assets/814039/acba52a1-026c-43f3-b137-edf1040807be">

Save the pane - rendered output on the front end is immediately out of order, and a refresh of the page here now shows a new order for the blocks:

<img width="844" alt="Screenshot 2024-02-28 at 14 19 51" src="https://github.com/craftcms/cms/assets/814039/c474e1bb-110b-4c9b-baad-e0a9a0554171">

Included a DB export in case that's helpful...
[buggy-matrix.zip](https://github.com/craftcms/cms/files/14435329/buggy-matrix.zip)

### Craft CMS version

5.0 Beta 3

### PHP version

8.2

### Operating system and version

DDEV

### Installed plugins and versions

- SEOmatic Beta
- CKEditor Beta

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR to tweak the previous fix.
