### ISSUE TITLE
at beta 5, defining siteUrl in general.php blows things up

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1449]
### Description
You notice that the site link in the upper left corner of the CP gives a bad url: http://site.tlc/site.tlc. 

Later you notice that image transformed files aren't being generated, always receiving the generate-me code. 

There are probably other consequences to Craft's internal view of its site url being bogus.

### Steps to reproduce

1. Make a clean or use an already inited standard Craft 3 site. This doesn't happen with an upgraded Craft 3 site.
2. Check the generated Site in the CP. You get site.tlc, looks good
3. being complete, check and edit the generated config/general.php file, so that siteUrl in the first definition is pointing 'properly' at your site.tlc.
4. watch the blowups as above. Make an image transform and use it in a Twig template, for the full effect.
5. comment out the config/general.php siteurl definition
6. watch the site working properly now, transforms included.
7. for various reasons, this can be particularly fun with Vagrant
8. for more details, see #1437

### Additional info

PHP version	7.1.2-3+deb.sury.org~xenial+1
Database driver & version	MySQL 5.7.17-0ubuntu0.16.04.1
Image driver & version	GD 7.1.2-3+deb.sury.org~xenial+1
Craft edition & version	Craft Personal 3.0.0-beta.5, plus Andris's $1434 and #1437 patches
Yii version	2.0.11.2
Twig version	2.1.0
Guzzle version	6.2.1
Imagine version	0.7-dev
Plugins: none

**Comment by brandonkelly** [comment]
There is no `siteUrl` in the [default `.env` file](https://github.com/craftcms/craft/blob/master/.env.example). Can you post exactly what you have in your `.env` file, and how you’re applying the value in `config/general.php`?

**Comment by narration-sd** [comment]
Good catch -- it wasn't the .env, but rather the general.php, which looked similar at that time of night. 

I'm editing the issue title and texts above to fit.

I just did a fresh composer create-project in a dummy folder, and the default general.php has siteUrl, but it is set to null.  It's that null I changed -- waiting to happen.

You may have  a reason for allowing a double definition of siteUrl (vs. the default Site, etc.), perhaps something to do with multi-Site, but think it shouldn't combine in the form that happened here: //site.url/site.url.

If so, I guess a 500 mentioning both components plus stack trace would be the thing if someone tries improperly, but you know that.

Here's  the file you asked for -- general.php rather than .env ,and thanks, Brandon:

[vetted_general.php.txt](https://github.com/craftcms/cms/files/817347/vetted_general.php.txt)

**Comment by narration-sd** [comment]
and for completeness, here's the generated config/general.php:

[generated_general.php.txt](https://github.com/craftcms/cms/files/817359/generated_general.php.txt)

**Comment by brandonkelly** [comment]
Issue here is that you’re not setting `siteUrl` to a valid URL – it must begin with either `//`, `http://`, or `https://`.

**Comment by narration-sd** [comment]
Ok, I see -- the value in general.php sets up the default Site's url. 

I put //google.com in, and besides seeing it in Settings, got there from the site url.

I guess we will always see a bit diffently about resilient outward-facing code, also its saving also on support harassment and costs, but that's ok. 

A slightly clearer description in that default file could also help, at low price.

Cheers, Brandon.

**Comment by narration-sd** [comment]
p.s. one thing I like about C3 in this vein is that over-riding values in site scripts show up and in fact force values seen/entered in the CP. 

A note there as to who over-rode would be in keeping with my resiliency point of view.

**Comment by narration-sd** [comment]
Semanics again: if the comment in the general.php was like this, it would cover a lot of territory. After all, there is no such thing as 'Base site' anymore, right?

```// Sets up the default Site's url -- such as http://site.com, https://site.com, or flexibly via //site.com```

Could it be also that the default if this isn't set should prefer //site.com, rather than http://site.com?

C.
