### ISSUE TITLE
[5.x]: Server error on Element overview pages

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#14505]
### Description
When viewing an element overview page, a server error occurs
https://github.com/craftcms/commerce/issues/3395

### Craft CMS version

5.0.0-beta.4

**Comment by i-just** [comment]
Hi, thanks for reaching out! I cannot replicate this issue on a clean Craft 5 + Commerce 5 installation. Do you have any plugins installed (apart from Craft Commerce)? If so, could you please list them? Any custom modules you’re using?

**Comment by WHITE-developer** [comment]
:thinking: Disabled all installed plugins and removed the bootstrapping of my modules but now I can't even login 
![image](https://github.com/craftcms/cms/assets/22771556/29cae353-3586-4263-bf69-8c6245fba386)

I see that the POST request for the login goes to `localhost//index.php?p=admin/actions/users/login` and do it's redirected to a GET request

Same as https://discord.com/channels/456442477667418113/456442477667418115/1213036176886210590

After downgrading to beta.3 everything works again, but when I upgrade again to beta.4 I can't login, or when I'm already logged in I get the erros on all overview pages

**Comment by WHITE-developer** [comment]
I guess It has to do something with this https://github.com/craftcms/cms/commit/965c1a6ec9288d1f319732edc0fd26c78feb088d#diff-7e5dfa5743abfcbe9b8e746535052dfe704e490f6b43510082246d1a3760e132R634

**Comment by i-just** [comment]
Thanks for more info! Yes, that’s my suspicion too. I’ll reply once I have more info.

**Comment by davidhellmann** [comment]
I have the same issue on two installations.

![image](https://github.com/craftcms/cms/assets/764292/5f0a3acd-f13c-4c18-874b-1381e65ce899)
![image](https://github.com/craftcms/cms/assets/764292/eef2b0d9-e980-4da2-ae1d-2b5b12f57e8d)
![image](https://github.com/craftcms/cms/assets/764292/09944e7c-5d71-4d6e-976e-81447dc70950)

**Comment by brandonkelly** [comment]
Just pushed a fix for that double-slash bug (`localhost//index.php…`). Can one of you pull that down and see if it resolves the issue for you? You can do that by changing your `craftcms/cms` requirement in composer.json to `5.0.x-dev as 5.0.0-beta.4` and running `composer update`.

**Comment by brandonkelly** [comment]
(sorry, the fix didn’t push to GH successfully earlier, so if either of you have actually tried updating in the past 8 minutes, try again.)

**Comment by WHITE-developer** [comment]
@brandonkelly Both the login as the element indexes are working again :+1:

**Comment by brandonkelly** [comment]
@WHITE-developer Sweet! Thanks for testing. We’ll get that released today.

**Comment by brandonkelly** [comment]
5.0.0-beta.5 is out with that fix.
