### ISSUE TITLE
[5.x]: Fields with "-" char in handle make everything crash 

### ISSUE THREAD

**Issue by plcdnl** [craftcms/cms#14508]
### Description
As described in title when i try to create a field in entry types with "-" char craft save it but then it's impossible to use

### Expected behavior
Is better to not permit to create this and only allow camelCase

<img width="1665" alt="image" src="https://github.com/craftcms/cms/assets/32842043/e3031f9a-cb1f-4740-ac09-aba17e481594">

### Craft CMS version

5.0.4

### PHP version

8.2

### Operating system and version

DDEV

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.0.0-beta.5 is out with a fix for this. Note that there’s no workaround if you’ve already saved the field handle override with a malformed handle. You’ll need to resave it with a valid handle. (If you can’t even access the field layout designer, you may need to fix it directly in `config/project/` and run `php craft project-config/touch` + `php craft project-config/apply`.)
