### ISSUE TITLE
[5.x]: Asset "cards" don't respect settings in the "View > Columns" configuration.

### ISSUE THREAD

**Issue by MattWilcox** [craftcms/cms#14503]
### Description

Unsure if this is a bug (because of what the UI implies) or feature request (because of what the UI implies)...

When viewing Assets we are able to set what properties of the asset should be displayed in the Table Columns; that is accessed via a button "View". We are able to see and set these via the View button regardless of whether the display style is a table or not. This implies it should effect the currently active View mode.

These properties are only respected in the default table view however - but given the setting remain accessible in all views, and given that Entries Cards can expose chosen properties, I would expect card views here in Assets to expose the desired properties as well as the table view. Really, only Thumbnail view should not expose additional details (and should also likely hide the View button)?

Asset table...
<img width="1222" alt="Screenshot 2024-02-29 at 21 44 39" src="https://github.com/craftcms/cms/assets/814039/8e4a38a8-096b-4b7a-9688-bfe673942b1e">

Asset "Cards"
<img width="1105" alt="Screenshot 2024-02-29 at 21 44 24" src="https://github.com/craftcms/cms/assets/814039/aeb58b6c-a8de-450c-b652-3c3c8b4c76cd">

Entry "Cards"
<img width="797" alt="Screenshot 2024-02-29 at 21 55 17" src="https://github.com/craftcms/cms/assets/814039/9f901ba8-0e1a-4bc6-b6c0-55f861eb4eb6">

### Craft CMS version

5.0 b3

**Comment by i-just** [comment]
Hi, thanks for reporting and clear description! You shouldn’t see the “Table Columns” checkboxes if you’re not in a table (or structure) view - just like the “Sort by” fields are not visible when in a structure view. I raised a PR for this.

> given that Entries Cards can expose chosen properties, I would expect card views here in Assets to expose the desired properties as well as the table view.
You can still choose which custom fields should be visible in Asset Cards so they do behave consistently with the Entry Cards. That being said, assets have extra properties that could be useful to show in cards. We’ll discuss that internally.

**Comment by brandonkelly** [comment]
Craft 5.0.0-beta.5 is out, which no longer shows the “Table Columns” setting when the card view is selected. (It still might be worth us giving card view a similar setting, but I think it would make sense for it to be labeled and managed separately, since you’re likely to want to surface different info depending on the view mode.)
