### ISSUE TITLE
[5.x]: SORT_LOCALE_STRING not working out of the box

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#14509]
### Description

Maybe a bug, maybe not, just wondering how to handle this.

Now that nested entries owners are eager-loadable, I tried this in order to avoid more complex/additional db queries:

```twig
{% set roles = craft.entries
    .type('roles')
    .relatedTo(person)
    .with(['owner'])
    .collect
%}

{% set rolesSortedByFilmTitle = roles.sortBy('owner.title', SORT_LOCALE_STRING) %}

{% for role in rolesSortedByFilmTitle %}
    {{ role.owner.title }}: {{ role.roleName }}
{% endfor %}
```

With `craft.app.locale.id` set to `de-DE`, I expected entries to be sorted with locale specific rules (the ÄÖÜäöüß thing), but that isn't the case.

Looks like that you have to call `setlocale(LC_COLLATE, str_replace('-', '_', Craft::$app->locale->id));` in PHP yourself first (note the underscore).

Could write a Twig extension/Collection makro for now, but don't like to introduce new syntax.

Also hesitating to set this globally in a module's init method, might have side effects??

### Craft CMS version

Craft 5.0.0-beta.4

### PHP version

8.2.13

### Operating system and version

Linux 5.15.133.1-microsoft-standard-WSL2

### Database type and version

MySQL 8.0.33

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
This has been resolved for 4.9 (WIP) and 5.0.0-beta.6 (out now).
