### ISSUE TITLE
[5.x]: Conditional fields returns to me 403 error

### ISSUE THREAD

**Issue by plcdnl** [craftcms/cms#14512]
### What happened?

https://github.com/craftcms/cms/assets/32842043/cc0d1fea-b8f9-4216-baee-9c49b36e5c14

### Craft CMS version

5.0.4-beta

### Installed plugins and versions

-

**Comment by plcdnl** [comment]
Solved: [](https://github.com/craftcms/cms/issues/14505#issuecomment-1973188168)

**Comment by plcdnl** [comment]
Sorry that fix doesn't solve my problem!

**Comment by i-just** [comment]
Thanks, Tommy! I raised a PR for it.

**Comment by brandonkelly** [comment]
Craft 5.0.0-beta.6 is out with that fix.
