### ISSUE TITLE
[5.x]: Element indexes with long element titles do not wrap, lowering index usability with horizontal scrolling

### ISSUE THREAD

**Issue by chadcrowell** [craftcms/cms#14514]
### Description
I have a section for an FAQ, where the question is the element title, so some of them are pretty long.

### Expected behavior
Long titles wrap or truncate so that subsequent columns in the element index remain visible.

### Actual behavior
Long titles do not wrap or truncate, pushing subsequent columns off the screen.
[Video Example](https://d.pr/v/3ZYnfS)

### Craft CMS version

Craft CMS  5.0.0-beta.5 (also showed in beta.4)

### PHP version

8.2.15

### Operating system and version

macOS

### Database type and version

DDEV

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
This has been resolved in 5.0.0-beta.6 🎉
