### ISSUE TITLE
[5.x]: Long author name display bug

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#14517]
### What happened?

When the author name is long, it causes some UI glitches on the sidebar of the entry edit view:

<img width="255" alt="image" src="https://github.com/craftcms/cms/assets/19857599/2a0f787f-90e5-4eb6-bcf2-4c1600cd58cc">

### Craft CMS version

5.0.0-beta.5

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
5.0.0-beta.6 is out now with a fix for this (via #14502).
