### ISSUE TITLE
[5.x]: GraphQL errors are pretty lean on details

### ISSUE THREAD

**Issue by engram-design** [craftcms/cms#14527]
### Description
Is there a reason there's very little detail in GraphQL queries in the explorer? Only a message is shown, with `devMode` enabled.

![image](https://github.com/craftcms/cms/assets/1221575/72926b94-629a-4837-9391-5517958ceae8)

If I comment out the `try/catch` found here https://github.com/craftcms/cms/blob/8766bc9278133d522cc94e80eea4fd2ced4f4d5f/src/controllers/GraphqlController.php#L189-L205

I get a full error as I'd expect.

![image](https://github.com/craftcms/cms/assets/1221575/ecc1bc82-c901-4921-9792-8a19bb12297f)

### Craft CMS version

5.0.0-beta.5

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Yeah agree it’s a bit sparse. As of 4.9 and 5.0.0-beta.6 (out now), the full exception details are now pulled in when Dev Mode is enabled, or for admin users who have the “Show full exception views” preference enabled.
