### ISSUE TITLE
Make C3 focal point more visible

### ISSUE THREAD

**Issue by johanneslamers** [craftcms/cms#1452]
### Description
Try to spot the focal point in this image.

![schermafdruk 2017-03-03 19 29 06](https://cloud.githubusercontent.com/assets/4696315/23563620/bd37801e-0047-11e7-851c-2b5a330f4538.png)

Yes it's hard. So it would be nice to make the focal point a bit more visible / stand out. A bit bigger, or maybe a subtile pointer animation. 

### Additional info

- Craft version: 3.0.0-beta.6
- PHP version: 7.1

**Comment by narration-sd** [comment]
or maybe/also color settable? Yellow would have worked for this sort of image, for example.

**Comment by andris-sevcenko** [comment]
I improved this for bright images, but this is quite something else, I must say, @johanneslamers.

@narration-sd I don't think manually setting the color would be an option here. I have some ideas and the front-runner revolves around reading the dominating color under the square area occupied by the focal point and then coloring the focal point in the opposite color to make it stand out, but that might also be easily lost on, uhh, chaotic and colorful images, so we'll see how that pans out.

I hope to circle around to all image editor related things in two weeks.

**Comment by narration-sd** [comment]
Well, and that's a much nicer solution I thought of first, but didn't want to suggest for the work that could be involved, Andris. 

Good on you. 

And, I also waltzed around that settting a chosen color would want to be very dynamic, a right-mouse thing so you could choose it when in different areas of the picture.  But, you'd have to see the cursor, thus move it, and anyway automatic would be much better.  Cheers.

**Comment by johanneslamers** [comment]
Great solution @andris-sevcenko! in combination with a little subtile animation it would really "pop-out"!

**Comment by steveooo9** [comment]
Why not use some white icon with a dark shadow/outline around it?

The dark shadow around it creates some cut from the image. This dark outline is like the black window frame on a notebook display.

**Comment by andris-sevcenko** [comment]
@steveooo9 a very sensible suggestion. I'll try some options out sometime this week!
