### ISSUE TITLE
[5.x]: Assets field with handle 'images' not displaying within Matrix field

### ISSUE THREAD

**Issue by handplant** [craftcms/cms#14530]
### What happened?

I have an EntryType called "Gallery" with an inner field called 'Images' which can be uses in a Matrix field.
When I output only the images in a page, they appear correctly, but they are not displaying within the Matrix field.

Entry Type: Page
```
{% set gallery =  craft.entries.id(1456).one() %}
{{ gallery.id }}
{{ dump(gallery.images.all()) }}

{{ entry.matrixContent.render() }}
```

Entry Type: Gallery
```
{% set images = entry.images.all() ?? null %}
{{ entry.id }}
{{ dump(entry.images.all()) }}
```

![Bildschirmfoto 2024-03-05 um 15 08 53](https://github.com/craftcms/cms/assets/2598962/6cac10a0-a098-4036-9abf-748623cae793)

If I rename the handle of the field 'images' to something else, everything works as expected! What could be the issue?

### Craft CMS version

Craft Solo 5.0.0-beta.5

### PHP version

8.2.16

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Would you mind sending your database backup, Composer files, and relevant template files over to support@craftcms.com?
