### ISSUE TITLE
[4.x]: Category created through modal is not immediately searchable

### ISSUE THREAD

**Issue by ammannbe** [craftcms/cms#14548]
### Description

When I create a new category through the modal, the created one is not searchable afterwards.
This is especially useful for deeply structured categories with a lot of entries.

### Steps to reproduce

1. Edit a normal entry with a field of type "Category"
2. Click on the field ("Add category")
3. Klick on "+ New XXX category"
4. Create and save the category
5. Back in the modal, search for the created category

### Expected behavior

The just created category should appear while typing in the search.

### Actual behavior

The category is visible in the list, but when I search for it, it does not appear in the filtered view.

### Craft CMS version

4.7.3

### PHP version

8.2.16

### Operating system and version

CentOS 7.9.2009 (Core)

### Database type and version

MariaDB 10.2.43

**Comment by brandonkelly** [comment]
That’s expected; new elements don’t get indexed immediately, until the “Updating search indexes” queue job has completed.
