### ISSUE TITLE
[5.x]: No longer able to log in to control panel when using custom baseCpUrl

### ISSUE THREAD

**Issue by bfopma** [craftcms/cms#14547]
### Description
We use a separate subdomain for access to the control panel that differs from `@web`. It looks like changes introduced in [this commit](https://github.com/craftcms/cms/commit/965c1a6ec9288d1f319732edc0fd26c78feb088d#diff-7e5dfa5743abfcbe9b8e746535052dfe704e490f6b43510082246d1a3760e132R382) have changed the way that `actionUrl` is generated, and result in a CORS error when the login form is submitted (POSTing to a different URL than the CP uses). 

Specifically, setting the `$useRequestHostInfo` value to `true` ends up setting the `$baseUrl` to use `@web`, whereas it was previously using the value of `static:baseCpUrl()`.

### Steps to reproduce

1. Configure a `baseCpUrl` that differs from the front end site URL.
2. Attempt to log in to the CP

### Expected behavior

Successful login

### Actual behavior

CORS error since the domain for the `actionUrl` doesn't match the CP's domain

### Craft CMS version

5.0.0-beta.6

### Installed plugins and versions

-

**Comment by roelvanhintum** [comment]
Same goes for Craft CMS 4.8.1 (4.8.0 works fine).

**Comment by brandonkelly** [comment]
> We use a separate subdomain for access to the control panel that differs from `@web`.

`@web` should always be set to the **current** URL you are accessing Craft from. It is not meant to represent the front-end site URL. So the issue here is that you are setting `@web` incorrectly.

**Comment by mrog-pbs** [comment]
I'm running into this as well.

I guess I can 'fix' it by adjusting `@web` to match `baseCpUrl`, and creating another ad-hoc alias for front-end site URLs... but I feel like I'm missing something:

If `@web` is meant to _always_ reflect the current CP URL, and _not_ the front-end site URL, what's the point of customizing `baseCpUrl` at all? (i.e. When would divergence between `baseCpUrl` and action URLs be desirable?)

**Comment by brandonkelly** [comment]
@mrog-pbs There’s not really any point in setting `@web` at all, since Craft will infer it automatically.

Setting `baseCpUrl` is only useful if your control panel should be accessed from a different base URL than your site.

If your site is located at `example.com` and your control panel is `cms.example.com`, with no trailing URI segment, then you’d need to set `baseCpUrl` to `'https://cms.example.com'` and `cpTrigger` to `null`, so Craft knows to treat `cms.example.com` requests as control panel requests.
