### ISSUE TITLE
[5.x]: Translatable fields in newly added matrix blocks not propagated after save/site switch

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#14540]
### Description

In a multi-site setup with a matrix field, the content of translatable fields in newly added blocks  is not propagated to the other site when saving the entry or switching the site.

### Steps to reproduce

1. Create a multi-site setup with sites de/en
2. Create a section with a matrix field  set to 'Save entries to all sites the owner element is saved in', with a required plain text field set to 'translate for all languages'
3. New entry in site 'en' -> add block -> fill in some text
4a) Press 'Create entry' -> entry is saved without validation error, although the field on the other site is empty.
4b) Switch to site 'de' -> the text field is empty

### Expected behavior

Like in v4.

### Actual behavior

Fields are empty, causing invalid content or disrupted editing workflow.

### Craft CMS version

Solo 5.0.0-beta.6

### PHP version

8.2.13

### Operating system and version

Linux 5.15.133.1-microsoft-standard-WSL2

### Database type and version

MySQL 8.0.33

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 5.0.0-beta.7 is out now with that fix. Thanks again!
