### ISSUE TITLE
[5.0.0-beta.6]: Global header overflows on mobile

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#14549]
### Description

The global header overflows on mobile pushing revisions and the account menu off screen.

![310610814-41ae8e2e-7541-47ab-b3bc-43674fec24ea](https://github.com/craftcms/cms/assets/19857599/40a80b19-de23-4f0c-bcbd-11b55df5c942)

Stole the screenshot from Aaron in [this discussion](https://github.com/craftcms/cms/discussions/14538)

### Craft CMS version

5.0.0-beta.6

### Installed plugins and versions

-

**Comment by brianjhanson** [comment]
Thanks for reporting! I've opened #14558 to address this.

**Comment by brandonkelly** [comment]
Craft 5.0.0-beta.7 is out now with a fix for this. Thanks again!
