### ISSUE TITLE
[5.x]: Undefined constant craft\services\Utilities::EVENT_REGISTER_UTILITY_TYPES

### ISSUE THREAD

**Issue by russback** [craftcms/cms#14553]
### Description
This error is thrown when registering a plugin utility in an event listener.

### Steps to reproduce

1. Create an event listener to register a plugin utility as follows

```php
Event::on(
    Utilities::class,
    Utilities::EVENT_REGISTER_UTILITY_TYPES,
    static function(RegisterComponentTypesEvent $event) 
    {
        $event->types[] = FooUtility::class;
    }
);
```

### Expected behavior

Utility registered.

### Actual behavior

```php
Error
Undefined constant craft\services\Utilities::EVENT_REGISTER_UTILITY_TYPES
```

### Craft CMS version

5.0.0-beta.6

### PHP version

8.2

### Installed plugins and versions

- Custom plugin with support for Craft ^4.0.0|^5.0.0
- No other plugins

**Comment by wsydney76** [comment]
Just had that an hour ago, this is now renamed to `Utilities::EVENT_REGISTER_UTILITIES`

**Comment by russback** [comment]
Hmm... how to handle on a plugin that's compatible with both 4 and 5. A property exists check or a dependency version check?

**Comment by KlingeSean** [comment]
> Hmm... how to handle on a plugin that's compatible with both 4 and 5. A property exists check or a dependency version check?


Use this:
`if (version_compare(Craft::$app->getVersion(), '5.0.0-beta.1', '<'))`

To make changes that you only want to make for version lower than Craft 5.0.0.-beta.1

**Comment by brandonkelly** [comment]
Yeah, the constant was renamed in v5.

Here’s the easiest way to support both without maintaining a Craft 5-specific version of your plugin:

```php
use craft\base\Event;
use craft\events\RegisterComponentTypesEvent;
use craft\services\Utilities;

$eventName = defined(sprintf('%s::EVENT_REGISTER_UTILITY_TYPES', Utilities::class))
    ? Utilities::EVENT_REGISTER_UTILITY_TYPES // Craft 4
    : Utilities::EVENT_REGISTER_UTILITIES; // Craft 5+

Event::on(Utilities::class, $eventName, function(RegisterComponentTypesEvent $event) {
    // ...
});
```

**Comment by russback** [comment]
@brandonkelly any thoughts on phpstan handling for this scenario? I'm currently getting this in phpstan output:

```
Line   helpers/Events.php                                                                
 ------ ---------------------------------------------------------------------------------- 
  64     Access to undefined constant craft\services\Utilities::EVENT_REGISTER_UTILITIES.  
```

**Comment by brandonkelly** [comment]
You would need to put that comment directly above the offending line:

```php
$eventName = defined(sprintf('%s::EVENT_REGISTER_UTILITY_TYPES', Utilities::class))
    ? Utilities::EVENT_REGISTER_UTILITY_TYPES // Craft 4
    /** @phpstan-ignore-next-line */
    : Utilities::EVENT_REGISTER_UTILITIES; // Craft 5+
```
