### ISSUE TITLE
[5.x]: Migration problem with date fields

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#14551]
### Description

The content of a date field (inside a matrix block in case that matters) gets stored in the JSON column like this:

```json
"54d4154b-41c3-4369-8d7e-f5107ffe8d5a": "2023-09-22 22:00:00",
```

while a manually edit entry looks like this:
```json
"54d4154b-41c3-4369-8d7e-f5107ffe8d5a": {"date": "2024-03-22 23:00:00"},
```

It is queried like this, producing invalid results for migrated content:

```sql
CAST((`elements_sites`.`content`->>'$.\"54d4154b-41c3-4369-8d7e-f5107ffe8d5a\".\"date\"') AS DATETIME)
```

### Steps to reproduce

1. Have a date field in Craft 4
2. Migrate to Craft 5

PS:
Looks like `craft resave/entries` solves this???

### Craft CMS version

5.0.x-dev as 5.0.0-beta.6

### PHP version

8.2.13

### Operating system and version

Linux 5.15.133.1-microsoft-standard-WSL2

### Database type and version

MySQL 8.0.33

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.0.0-beta.7 is out with the fix for this. Thanks again!
