### ISSUE TITLE
[4.x]: Users can update non-translatable multisite entries they don't have permission to edit

### ISSUE THREAD

**Issue by turnstylerj** [craftcms/cms#14572]
### Description
If you have an entry enabled on multiple sites in a multi-site install that contains a non-translatable field, and a user who only has permission to edit content on one of the sites, they can still edit the field and change content on the site they don't have access to.

### Steps to reproduce
1. Create a Craft CMS multisite instance with an entry type enabled on both sites with at least one non-translatable field.
2. Create a user group with permission only to edit one of the two sites and assign it to a user.
3. Impersonate that user and change content in the non-translatable field you have access to.

### Expected behavior
Field is disabled or a validation error is returned and the entry cannot be saved as is.

### Actual behavior
Entry is saved and content is updated on the site the user doesn't have permission to update.

### Craft CMS version

4.5.12

### PHP version

8.2.15

### Operating system and version

Linux 6.5.0-15-generic

### Database type and version

MariaDB 10.4.32

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

"craftcms/ckeditor": "3.6.0",
"doublesecretagency/craft-cpcss": "^2.6",
"internetztube/craft-element-relations": "^2.0",
"mmikkel/retcon": "2.7.5",
"nystudio107/craft-imageoptimize": "4.0.5",
"nystudio107/craft-retour": "4.1.14",
"nystudio107/craft-seomatic": "4.0.37",
"percipioglobal/craft-colour-swatches": "4.3.0",
"putyourlightson/craft-sherlock": "4.4.1",
"servd/craft-asset-storage": "3.5.6",
"spicyweb/craft-neo": "3.9.11",
"vaersaagod/matrixmate": "2.1.4",
"verbb/field-manager": "3.0.8",
"verbb/image-resizer": "3.0.9",

**Comment by brandonkelly** [comment]
This is expected behavior.

If you don’t want a user to be able to edit a field, you can hide it from them by setting a User Condition on the field within the field layout.

**Comment by turnstylerj** [comment]
If we set user permissions to hide the field, they wouldn't be able to see the field even if the entry only existed on the site they have access to. Is there a way to allow the user/group to see the field if the entry only exists on the site they have permission to edit, but not if it exists on sites they don't have permission to edit?

**Comment by brandonkelly** [comment]
That’s not currently possible in core, sorry. You could pull it off by registering a new condition rules, which takes full control over when the field should be visible.

Condition rule:
```php
use Craft;
use craft\base\conditions\BaseLightswitchConditionRule;
use craft\base\ElementInterface;
use craft\elements\conditions\ElementConditionRuleInterface;
use craft\elements\db\ElementQueryInterface;
use yii\base\NotSupportedException;

class IsFreshConditionRule extends BaseLightswitchConditionRule implements ElementConditionRuleInterface
{
    public function getLabel(): string
    {
        return 'Is fresh';
    }

    public function matchElement(ElementInterface $element): bool
    {
        return (
            $element->getIsFresh() === $this->value ||
            (
                Craft::$app->getUser()->getIsAdmin() ||
                Craft::$app->getUser()->getIdentity()?->isInGroup('groupName')
            )
        )
    }

    public function getExclusiveQueryParams(): array
    {
        return [];
    }

    public function modifyQuery(ElementQueryInterface $query): void
    {
        throw new NotSupportedException();
    }
}
```

```php
Event::on(EntryCondition::class, BaseCondition::EVENT_REGISTER_CONDITION_RULES, function(RegisterConditionRulesEvent $event) {
    $event->conditionRules[] = IsFreshConditionRule::class;
});
```
