### ISSUE TITLE
[5.x]: Right to Left subnav issues

### ISSUE THREAD

**Issue by lukeholder** [craftcms/cms#14589]
### Description

1) While in RTL mode, dots on the subnav are not right-aligned.

2) Main nav highlight bar is also not right aligned.

3) Utility counter badge also not rendering number correctly.

![CleanShot 2024-03-14 at 11 10 27@2x](https://github.com/craftcms/cms/assets/133571/c1b96112-fe4c-429b-9f8f-7cca2eeb544e)

### Craft CMS version

5.0.0.beta-7

### Browsers

Issue seen in Firefox and Chrome

**Comment by brandonkelly** [comment]
Fixed in 5.0.0-beta.8
