### ISSUE TITLE
[5.x]: Invalid draft ID error when navigating back after creating a new entry

### ISSUE THREAD

**Issue by russback** [craftcms/cms#14587]
### Description
Error displayed when traversing back in browser history.

### Steps to reproduce

1. Create a new entry.
2. Hit the back button in the browser when the entry is created.

### Expected behavior
No error.

### Actual behavior
```php
[HTTP 400 – Bad Request](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#400) – [yii\web\BadRequestHttpException](https://www.yiiframework.com/doc-2.0/yii-web-badrequesthttpexception.html)
Invalid draft ID: 7
```

. in /var/www/html/vendor/craftcms/cms/src/controllers/ElementsController.phpat line 2062

### Craft CMS version

5.0.0-beta.7

### PHP version

8.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next Craft 4 and 5 releases.

**Comment by brandonkelly** [comment]
Craft 4.8.3 and 5.0.0-beta.8 are out with that fix. Thanks again!
