### ISSUE TITLE
[5.x]: Some buttons inside element action menus aren't translated

### ISSUE THREAD

**Issue by gcamacho079** [craftcms/cms#14583]
### Description
See title

### Steps to reproduce

1. Add an asset field to a field layout
2. Change language to Spanish or another non-English language
3. Add an asset to the field, and open the action menu

Some actions, like "Show in Folder," "Open in Image Editor," and "Move backward"/"Move forward" aren't translated

### Expected behavior
These buttons should also be translated into the user's preferred language

### Actual behavior
<img width="258" alt="Open action menu with several buttons in English, while the CP language is set to Spanish" src="https://github.com/craftcms/cms/assets/17525979/987aeefa-813a-4b38-853a-a7038249a482">

### Craft CMS version

5.0.0-beta.6

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
They will be! We just haven’t ordered new translations for Craft 5 quite yet.
