### ISSUE TITLE
[4.x]: Running Craft on a subpath generates invalid index.php action urls

### ISSUE THREAD

**Issue by LeoWie93** [craftcms/cms#14592]
### Description
We are trying to fully run craft under a subpath. For Example:
- Frontend: `example.com/path`
- CP:             `example.com/path/admin`

For this to work we are currently running the Following configuration:

#### ENV
`PRIMARY_SITE_URL='http://example.com/path/'`

#### General
```php
  ->aliases([
        '@web' => App::env('PRIMARY_SITE_URL'),
        '@webroot' => dirname(__DIR__) . '/web/path',
    ])
    ->baseCpUrl(App::env('PRIMARY_SITE_URL'))
```

#### Web Folder
```
web/
       index.php
       path/
                 assets/
                 cpressources/
                 etc.
```
### Expected Behavior
The axios.js action urls are generated with the `path`.

### Actual Behavior
Everything except the Action axios requests work. Thei MISS the /path/ and without out it, it points to the wrong application.
![image](https://github.com/craftcms/cms/assets/29427760/54dcb798-29c9-4080-ab62-e05fbc7a5e48)

This effects:
- logging in
- viewing entries
- transform generation

Did we miss something in the documentation or is this expected behavior?

### Craft CMS version

4.8.2

### PHP version

8.2

### Operating system and version

Linux

### Database type and version

mysql 8

### Image driver and version

-

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
If you want Craft to run from `path/`, you need to move `index.php` into that folder.

It’s not clear where your `bootstrap.php` file and `vendor/` folder live. Are they alongside `web/`?

```
bootstrap.php
vendor/…
web/…
  path/…
```

Assuming that’s the case, after moving `index.php` into `web/path/`, you should change [this line](https://github.com/craftcms/craft/blob/8b56598dde738e4de18b710d4a5061fea175099b/web/index.php#L7) in `index.php` to:

```php
require dirname(__DIR__, 2) . '/bootstrap.php';
```

(The `2` tells `dirname()` to go up two directory levels from `web/path/`.)

**Comment by brandonkelly** [comment]
Can you create a `test.twig` file within your `templates/` folder, with the following?

```twig
{{ dump(craft.app.request.getScriptUrl()) }}
{{ dump(alias('@web')) }}
```

Then visit `example.com/path/test`. What does it output?

**Comment by LeoWie93** [comment]
@brandonkelly this is the response:
![image](https://github.com/craftcms/cms/assets/29427760/0c331903-9207-456b-8539-f3631c4cd834)

**Comment by brandonkelly** [comment]
Pushed a change yesterday that I think will solve this (c8718f629d2a5b07637938a19fdc9056bea39a79). Can you test and let me know?

To test, change your `craftcms/cms` requirement in composer.json to `dev-develop as 4.8.2`, and run `composer update`.

**Comment by LeoWie93** [comment]
@brandonkelly yes with this version the url is build as expected.
![image](https://github.com/craftcms/cms/assets/29427760/590ab9a8-a1d2-4624-a113-2392f9a119a1)

Though now my nginx.conf seems not to be perfect. Ill figure it out.
Thank you for your time and help @brandonkelly :+1:
