### ISSUE TITLE
[4.x]: `users/save-user` returns username and email error when email address is in use by a user whilst `useEmailAsUsername` is true 

### ISSUE THREAD

**Issue by andrewhawkes** [craftcms/cms#14597]
### Description

When using an existing email address whilst registering, the following errors are returned:

![image](https://github.com/craftcms/cms/assets/4975742/1e215c68-6763-4600-a1eb-3815408bc861)

Username X has been taken
Email address X has been taken

This is with the `useEmailAsUsername` general config setting is set to `true`.

I'm not sure if this is "expected" but the Username error isn't relevant from a UX perspective as the username field does not exist. 

I understand Craft still stores a username etc but I feel like this error shouldn't be shown when `useEmailAsUsername` is true.

### Steps to reproduce

1. Set `useEmailAsUsername` to `true`
2. Register a user using an existing email address used for a user
3. See both error messages shown

### Expected behavior

Just the email address error should be shown.

### Actual behavior

Both username and email address errors shown.

### Craft CMS version

4.8.2

### PHP version

8.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Yeah this is expected, as we’re not sure which attribute you are going to be displaying errors for.

You can clear out the `username` errors to prevent them from showing up in your form:

```twig
{% do user.clearErrors('username') %}
```

**Comment by andrewhawkes** [comment]
@brandonkelly okay, thanks for clarifying
