### ISSUE TITLE
Section handle changes not propagating

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1459]
## Description
After changing a Section's name and handle from original, site.url/originalhandle is still operating, showing the page.

### Steps to reproduce
1. Have a Section you made
2. Edit the section, and change the handle; name too for sanity
3. browse site.url/originalhandle: you get the  page instead of a 404
4. I fixed the craft_entrytypes lack of propagation in the pics below, but the problem is deeper than that. I also found and fixed craft_elements_i18n and craft_entryversions records that stll held the 'home' key, but site.url/home still merrily gets the templates/lang page. Craft cache and browser clearing was naturally done.
5. Only way out with this situation at present seems to be to drop the Section and recreate it with desired name. Easy enough in this ultrasimple test site, but.
6. Side note: beta6 is still defaulting _entry for the Site Settings/template(s) on Singles -- this works for templates in templates/folders, but not for homepage templates in root of templates. I suspect you'd be best to default to index if the url is blank, as you suggest is right for homepages.

Here are database and Sections page, with beginning clues. Original name/handle was Home/home; new name/handle is Language/lang. But that doesn't seem to have fully happened:

![section-language-lang](https://cloud.githubusercontent.com/assets/247945/23582417/8ce6cc70-00de-11e7-91f0-26fdfc81dd0a.png)

![entrytype-language-home](https://cloud.githubusercontent.com/assets/247945/23582421/991f03fe-00de-11e7-84ae-2dbbe9c6f412.png)

This is in regards a test page whose template folder was changed to match  the Section definition change, so there is templates/lang  now, but no templates/home, even though it browses. This  part probably due to my Sites definitions pointing to the templates/lang etc., part of the actual experimenting..

### Additional info

PHP version	7.1.2-3+deb.sury.org~xenial+1
Database driver & version	MySQL 5.7.17-0ubuntu0.16.04.1
Image driver & version	GD 7.1.2-3+deb.sury.org~xenial+1
Craft edition & version	Craft Personal 3.0.0-beta.6
Yii version	2.0.11.2
Twig version	2.1.0
Guzzle version	6.2.1
Imagine version	0.7-dev
Plugins: none

**Comment by brandonkelly** [comment]
Sections don’t automatically get “index page” routes. If site.url/originalhandle is working for you, it’s because you have a `originalhandle.html`/`originalhandle/index.html` template, or something like that, not because you have a section with the handle `originalhandle`.

**Comment by brandonkelly** [comment]
> Side note: beta6 is still defaulting _entry for the Site Settings/template(s) on Singles -- this works for templates in templates/folders, but not for homepage templates in root of templates. I suspect you'd be best to default to index if the url is blank, as you suggest is right for homepages.

This is intended. We decided to stick with `_entry` even for Singles 1) for consistency, and 2) because it’s still semantically correct – even though it’s only one entry, it’s still an entry. And there’s still a good reason to have that template be private (begin with `_`) : so it can’t be accessed in other ways (e.g. `/about.html`), which would result in a Twig error about how the variable `entry` doesn’t exist.
