### ISSUE TITLE
[5.x]: Please fix sidebar nav overscroll effects on main content area

### ISSUE THREAD

**Issue by AndrewMac** [craftcms/cms#14611]
### What happened?

If the sidebar nav has a lot of entries (for example, small vertical height or a lot of plugins) and thus overflows, if you scroll to the bottom of the nav and continue to scroll (overscroll), the content area on the right begins to scroll.

To stop this unwanted behaviour, I have updated the sidebar nav CSS with an 'overscroll-behavior' declaration:

.global-sidebar__nav {
    overscroll-behavior: contain;
}

If that works for you, could you please consider adding that … or coming up with a better solution to stop the unwanted scrolling effects.

See https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior for more info.

Thanks heaps!

### Craft CMS version

Craft CMS 5.0.0-beta.8

### PHP version

8.3.2

### Operating system and version

macOS Sonoma 14.4

### Installed plugins and versions

-

**Comment by brianjhanson** [comment]
Thanks for reporting! I've opened #14614 to address this.

**Comment by brandonkelly** [comment]
5.0.0-beta.10 is out with that fix. Thanks again!
