### ISSUE TITLE
[5.x]: Matrix is broken since beta 8

### ISSUE THREAD

**Issue by stevendierick** [craftcms/cms#14615]
### Description

Since the release of beta 8, Matrix functionality is kind of broken. Panels fail to load when using cards or element index views, updating a field's content triggers JS errors (though still seems to work), and deleting entries/blocks also results in JS errors (but still seems to work). Also, there's an invalid element ID error when opening the entry. And, a nested Matrix fails to load in all three modes.

I've recorded these issues with all three Matrix view modes:

https://share.cleanshot.com/24dbCHJzjpvq0kZ4JBvM

### Craft CMS version

5.0.0-beta.8

### Installed plugins and versions

- CKEditor 4.0.1

**Comment by davidhellmann** [comment]
I think I run into the same issue. Wasn't possible to save entries.

**Comment by i-just** [comment]
Hi, thanks for reporting! Looks like it was fixed in `5.0.0-beta.9` (more info can be found here: #14610).
