### ISSUE TITLE
[4.x]: retryDuration no longer available as general config setting 

### ISSUE THREAD

**Issue by timbertens** [craftcms/cms#14617]
### Description
While upgrading from Craft 3 to 4 we noticed that this settings appears to be no longer available, although it is still mentioned in the documentation (see https://craftcms.com/docs/4.x/console-commands.html#off)  and we still use it ...

### Steps to reproduce

1. Add 'retryDuration' => 30 to general.config

### Expected behavior

Site loading normally and when the site is put online, every 30 seconds the waiting page reloads

### Actual behavior

Following error occurred
An Error occurred while handling another error:
yii\base\UnknownPropertyException: Invalid general config setting: retryDuration. You can set custom config settings from config/custom.php. in /var/www/html/vendor/craftcms/cms/src/config/GeneralConfig.php:3189
Stack trace:

### Craft CMS version

4.8.3

### PHP version

8.3.0

### Operating system and version

Linux 6.6.12-linuxkit

### Database type and version

MariaDB 10.4.32

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

CodeMirror	2.0.0
CP Field Inspect	1.4.4
Do It Yourself widget	3.0.0
Feed Me	5.4.0
Field Manager	3.0.8
GeoField	1.0.0
Incognito Field	1.3.0
Knock Knock	2.0.11
Linode Object Storage	2.0.1
No-Cache	3.0.2
QRCode	2.1.0
Redactor	3.0.4
SEOMate	2.2.0
Site Switcher	2.3.0
Static Files Autoversioning	2.2.0
Super Table	3.0.12
Table Maker	4.0.9
Typed link field	2.1.5
Wheel Form	3.1.8
Wheelform Helper	1.0.0
Wordsmith	4.4.0

**Comment by brandonkelly** [comment]
Whoops, that’s a docs bug. There has never been a `retryDuration` _config setting_; it’s a general setting, shown in Settings → General.
