### ISSUE TITLE
[4.x]: Automatic CraftCMS Installation via Craft PHP Script: Password Input Error

### ISSUE THREAD

**Issue by frkngksl** [craftcms/cms#14626]
### Description
Hi I want to fully automate CraftCMS Installation. After using docker-compose with the yaml file that you provided from your docker repo, we need to still complete the setup by using either index.php?p=admin/install or using craft php script. I'm trying to use Craft php script, and I wrote the required answers (like db driver input, email input, username input etc.) in a txt file and tried to redirect the file content to the php interpreter to avoid user interaction during the installation script. However, when the script wants password by using hiddencliprompt, it doesn't accept this redirection and returns the following error.

``` Password: stty: standard input: Not a tty ```

Is there any other way to complete this setup process without user interaction? Navigating to Setup Wizard through the browser and using this GUI interface is also hard to automate.

### Steps to reproduce

1. Start the Docker Environment that is given for Craft CMS
2. Put CraftCMS that you downloaded from Releases tab
3. Arrange permissions, and run this command from docker exec: php craft setup < prompt.txt (prompt.txt contains inputs that are asked during the setup script execution)

### Craft CMS version

4.4.9

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
You can automate the installation using the `php craft install` command, which has options for all the values that will need to be entered, such as `--password`.
