### ISSUE TITLE
View asset error

### ISSUE THREAD

**Issue by aqeelfikree** [craftcms/cms#1462]
### Description

Viewing an asset leads to Page Not Found

### Steps to reproduce

1. In CP go to Assets
2. Click any volume
3. Check an image
4. Gear icon > View asset

### Additional info

- Craft version: 3 Beta 6
- PHP version:
- Database driver & version:
- Plugins & versions:

<img width="217" alt="view asset" src="https://cloud.githubusercontent.com/assets/7760013/23635272/8376e4da-0283-11e7-92c7-4236a1e46265.png">

<img width="347" alt="page not found" src="https://cloud.githubusercontent.com/assets/7760013/23635312/c9f1a1de-0283-11e7-8a28-b177338a8ef2.png">

**Comment by brandonkelly** [comment]
@aqeelfikree What is your volume’s Base URL? Most likely that needs to be corrected.

**Comment by aqeelfikree** [comment]
`images/blog/`

**Comment by brandonkelly** [comment]
Yeah that should be either an absolute, protocol-relative, or root-relative URL. Try changing it to `@web/images/blog`.
