### ISSUE TITLE
[5.x]: Craft 5 use the old field handle in the matrix after Craft 5 content migration

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#14624]
### What happened?

After upgrade to 5, the fields inside a matrix is moved to global context and if there is a field with same handle, Craft adds a number to end of that field handle and if I understand it correctly Craft should use that field with new handle in the related layout -even if the field with new handle has same config with the current field with the old handle-

The problem is the matrix entry type's layout still use the old field -although editing the field in the layout open the new generated field-

In the screenshot below, after Craft5 migration, the 'text22' field related to 'bt2' matrix is created -because 'text2' is taken somewhere else- ,but 'bt2' entry type still use 'text2' instead of 'text22' -editing 'text2' opens 'text22' though-

![craft5 - Copy](https://github.com/craftcms/cms/assets/55586085/bcdb9f32-8ae9-4bf9-bef7-840bece8ebf9)

### Craft CMS version

5.0.0-beta.9

### PHP version

8.2

### Database type and version

MariaDB 10.6.7

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
This is working as expected. When globalizing your Matrix sub-fields, the Craft 5 migration will ensure they have a unique handle globally, and then override their handles within the entry type (former block type)’s field layout, so that your templates will continue to work, still referencing the field by its original handle.

**Comment by vnali** [comment]
Thanks @brandonkelly  this backward compatibility is awesome
but it seems it works different for fields inside a super table inside a matrix.

- below screenshot shows after migration to 5, there is 'txt2' field pointing to 'txt22'.
in Craft 4, the field inside super table was 'txt'. I expect that field inside super table remains `txt` and point to 'txt2' -because 'txt' is taken in another layout-

![st-in-matrix - Copy](https://github.com/craftcms/cms/assets/55586085/da081e9f-b16f-470c-a152-61919eab5414)

![st-in-matrix - Copy2 - Copy](https://github.com/craftcms/cms/assets/55586085/9048d8ff-7cdf-4553-8d46-04c0d4d4ca22)

**Comment by brandonkelly** [comment]
Any chance you can send a database backup and Composer files to support@craftcms.com?

**Comment by vnali** [comment]
@brandonkelly i just sent an email to support@craftcms.com.

**Comment by brandonkelly** [comment]
Thanks! I was able to reproduce with those files, and tracked down the bug. Fixed now for the next release (afe70d1350c477cc408a58dff2668cd02d64760e), and PR’d a similar fix to Super Table (verbb/super-table#550).

**Comment by brandonkelly** [comment]
5.0.0-RC1 is out with that fix.
