### ISSUE TITLE
Cannot access 'Assets' page when a custom CP url has been set

### ISSUE THREAD

**Issue by jamiepepper** [craftcms/cms#14636]
### Description
I'm running a CraftCMS powered multisite. There's 2 websites being controlled via 1 backend. Each site has a custom URL, as does the CMS. Everything works as expected, apart from trying to access the 'Assets' page, using the left-hand side menu item. When I click this menu item, I get a 'You don't have permission to access this resource.' error.

### Steps to reproduce

1. Set up Craft multisite
2. Have the CMS serve from a custom domain, rather than `/admin`
3. Set the cpTrigger to 'null', and set the baseCpUrl
4. Click 'Assets' in the left-hand menu

### Expected behavior

It should show the folder structure, and the assets.

### Actual behavior

It gives me a permissions error 'You don't have permission to access this resource.'

### Craft CMS version

5.8.0

### PHP version

8.1

### Operating system and version

macOS - 13.5.2 (22G91)

### Database type and version

mysql - 8.1

### Installed plugins and versions

-

**Comment by ccchapman** [comment]
Does your project have a `web/assets` directory? Your webserver is probably looking there, and then not finding an index file inside it. If so one solution is to rename that e.g. prepend an underscore.

**Comment by jamiepepper** [comment]
Exactly right @ccchapman  - Thank you.
