### ISSUE TITLE
[5.0.0-beta.10]: User photo "upload a photo" and Asset index "Upload files" button are broken

### ISSUE THREAD

**Issue by kylecotter** [craftcms/cms#14638]
### Description
Two issues, seemingly related.

When trying to upload a user photo, the button does not do anything.

When trying to upload files to a volume from the asset index page, the "Upload files" button does not work. Dragging a file in works.

### Steps to reproduce

1. Click the "upload a photo" button on a user account
2. Click "upload files" on a volume

### Expected behavior
A file modal opens

### Actual behavior
Nothing happens

### Craft CMS version

5.0.0-beta.10

### PHP version

8.2.17

### Operating system and version

Linux 6.6.16-linuxkit

### Database type and version

MySQL 8.0.30

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.1-13)

### Installed plugins and versions

- All plugins disabled

**Comment by i-just** [comment]
Hi, thanks for getting in touch! I’m unable to replicate this. Could you please let me know the following:
- can you see any errors in the console
- what’s your Settings > Users > Settings > User Photo Location set to
- your Filesystem and Volume settings

**Comment by kylecotter** [comment]
So, was able to track this down to just being an issue in Chrome - Safari worked fine. Weird part was there was no console logs or any indication of an error.

After realizing I had a Chrome update available (though the version of Chrome this was happening on was not very out of date) and updating, everything started working. So, guess we're good - sorry to waste your time!

**Comment by brettburwell** [comment]
Hey y'all. Came here with the same issue (I'm on Craft 4.7.4). 

Nothing changed on the site, and seemingly overnight the ability to upload files stopped working. And similar to @kylecotter, dragging and dropping to upload still works. 

As a quick test, I tried using a different browser (Firefox), and it magically worked. So I believe the issue is actually with a recent Chrome release.

**Comment by brettburwell** [comment]
@kylecotter beat me to it. Jinx!
