### ISSUE TITLE
[5.x]: Minor styling issue with queue job in sidebar

### ISSUE THREAD

**Issue by kennethormandy** [craftcms/cms#14645]
### Description

There’s some slightly low-contrast styling / styles that seem leftover from the dark background sidebar, when queue jobs are running.

This might have already been fixed, I was looking at v5.0.0-beta.9 at the time:

<img width="256" alt="Screenshot 2024-03-20 at 1 53 38 AM" src="https://github.com/craftcms/cms/assets/1581276/5169c331-4dfb-47ff-bb88-a0a600473f51">

This is definitely the case in v5.0.0-beta.10—when you hover, you get white text only, no background colour like all the other nav items. Seems like it should either have the background and be entirely white including the icon, or maybe not have the hover colour at all?

<img width="344" alt="Screenshot 2024-03-21 at 12 58 07 PM" src="https://github.com/craftcms/cms/assets/1581276/7228a43a-3152-4ff8-9cb6-8d772b1efde1">

### Craft CMS version

v5.0.0-beta.10

**Comment by brandonkelly** [comment]
Fixed in 5.0.0-beta.11 via #14656 🎉
