### ISSUE TITLE
[5.x]: Unable to inline edit assets with folder in v5.0.0-beta.10

### ISSUE THREAD

**Issue by kennethormandy** [craftcms/cms#14646]
### Description

In v5.0.0-beta.9, I was able to bulk inline edit assets, but was seeing the fields show up even for folders:

<img width="1050" alt="Screenshot 2024-03-20 at 9 53 32 AM" src="https://github.com/craftcms/cms/assets/1581276/0b04e727-bc5f-44e7-9403-2029478f9b8a">

I was double-checking that on v5.0.0-beta.10, to see if I should still file it, and now I’m not able to bulk edit at all if there is a folder or subfolder in the element index.

https://github.com/craftcms/cms/assets/1581276/ad352319-860d-40ad-936f-a319536aaee9

If I have no folder, it works. If I add a folder in the index, I get a server error notification instead.

### Steps to reproduce

1. Go to assets
2. Press “Edit”
3. See that it works
4. Add a folder (or subfolder) in that view
5. It doesn’t appear to work anymore

### Craft CMS version

v5.0.0-beta.10

### Installed plugins and versions

-

**Comment by i-just** [comment]
Thanks Kenneth! I raised a PR for both issues (server error and editing fields showing for the folders).

**Comment by brandonkelly** [comment]
Fixed in 5.0.0-beta.11 🎉
