### ISSUE TITLE
[5.x]: Lightswitch in card view is unclear what field its from

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#14655]
### Description
![image](https://github.com/craftcms/cms/assets/22771556/1420469a-d02a-4caa-b4a6-b6e172ea331d)
When you enable a lightswitch field to be visible inside a cart view, it's unclear what the lightswitch field is for, I think it would be clearer if the field label would be added as text next to the checkbox

### Craft CMS version

5.0.0-beta.10

### PHP version

8.3.2

### Operating system and version

Ubuntu 22.04

### Database type and version

mysql 8.0.32

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.0.0-beta.11 is out now with the fix for this. Thanks again!
