### ISSUE TITLE
[4.x]: Not possible to upload files in General settings and account page

### ISSUE THREAD

**Issue by samuel-clara** [craftcms/cms#14651]
### Steps to reproduce

1. Go to Settings → General and click on "Upload logo" or "Upload icon"
2. Go to My Account and click on "Upload a photo"

### Expected behavior

Allow user to select a file from device

### Actual behavior

Nothing happens

### Craft CMS version

4.8.4

### PHP version

8.3

### Operating system and version

MacOS 14.4

### Database type and version

Mysql 8.0

### Installed plugins and versions

- no plugins, new install

**Comment by i-just** [comment]
Hi, thanks for getting in touch. Are you experiencing this issue in Chrome? If so, please try updating to the latest version (more info can be found here: #14638).

**Comment by i-just** [comment]
Not a problem. Glad to hear it's working as expected :)
