### ISSUE TITLE
[4.x]: Entry URI not updated after username changed & correct URL results in a 404

### ISSUE THREAD

**Issue by vonscriptor** [craftcms/cms#14658]
### Description
I have a section whose Entry URI Format is: `u/{author.username}/portfolio/{slug}`. When the author's username is changed the entry URI is not updated.

### Steps to reproduce
1. Create a section that uses {author.username} in its Entry URI Format
2. Create an entry in that section
3. Change that entry author's username
4. Entry's URI is not updated

### Expected behavior
Changing usernames should update entry URI's that include them.

### Actual behavior
Changing usernames does not update entry URI's that include them in the CP or in entry queries.

### Craft CMS version

4.8.2

### PHP version

8.0.21

### Operating system and version

MacOS Sonoma 14.3.1

### Database type and version

MySQL 8.0.30

**Comment by vonscriptor** [comment]
Building the URL myself e.g. `{% set projectUrl = siteUrl ~ 'u/' ~ project.author.username ~ '/portfolio/' ~ project.slug %}` which then uses the correct username returns a 404.

**Comment by brandonkelly** [comment]
Entry URIs are only updated automatically when the entry itself is saved. You’d have to automate updating authors’ entries’ URIs when they are saved via a module.

Something like:

```php
use craft\elements\Entry;
use craft\elements\User;
use craft\events\ModelEvent;
use craft\helpers\Queue;
use craft\queue\jobs\ResaveElements;
use yii\base\Event;

Event::on(User::class, User::EVENT_AFTER_SAVE, function(ModelEvent $event) {
    /** @var User $user */
    $user = $event->sender;

    // if the user has any portfolio entries, update their URIs via a queue job
    if (Entry::find()->section('portfolio')->authorId($user->id)->exists()) {
        Queue::push(new ResaveElements([
            'elementType' => Entry::class,
            'criteria' => [
                'section' => 'portfolio',
                'authorId' => $user->id,
            ],
        ]));
    }
});
```

**Comment by vonscriptor** [comment]
Thank you, @brandonkelly—that was helpful! I believe I got it working. I did add `'updateSearchIndex' => true` too as it seemed that some entries' links to the portfolios were not updated, but are now with that line. I also am using a dedicated queue runner so that they will be run immediately.

It'd probably be good to only resave elements if the username is changed. I tried but can't seem to get it working with: `if (array_key_exists('username', $user->getDirtyAttributes())) {` I guess it wouldn't be dirty because it was already saved at that point. (I don't have much experience with PHP and modules.) Any suggestions?

**Comment by brandonkelly** [comment]
Craft doesn’t make it easy, unfortunately, but here’s how you could do that:

```php
use craft\elements\Entry;
use craft\elements\User;
use craft\events\ModelEvent;
use craft\helpers\Queue;
use craft\queue\jobs\ResaveElements;
use yii\base\Event;

Event::on(User::class, User::EVENT_BEFORE_SAVE, function(ModelEvent $event) {
    // ignore if it's a new user
    if ($event->isNew) {
        return;
    }

    /** @var User $user */
    $user = $event->sender;

    // ignore if their username isn’t changing
    $oldUsername = User::find()->id($user->id)->select('username')->scalar();
    if ($user->username === $oldUsername) {
        return;
    }
    
    // ignore if they don't author any portfolio entries
    if (!Entry::find()->section('portfolio')->authorId($user->id)->exists()) {
        return;
    }

    $user->on(User::EVENT_AFTER_SAVE, function() use ($user) {
        Queue::push(new ResaveElements([
            'elementType' => Entry::class,
            'criteria' => [
                'section' => 'portfolio',
                'authorId' => $user->id,
            ],
        ]));
    });
});
```
