### ISSUE TITLE
[5.x]: Elements are "selected" when interacting with buttons and links inside element index cards and rows

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#14669]
### Description

In Craft 5's element indexes, elements are _selected_ when clicking anywhere inside their row (or card) – as opposed to having to specifically click the "Select" checkbox, in previous versions of Craft.

This is a very good feature/change! However the current implementation feels a little bit too aggressive to me, as elements are *always* selected, even when the user clicks on interactive items inside rows (or cards), such as structure entry move handles, or even links (like the URI globe).

As an example: after re-arranging some structure entries via the structure move handles, the user ends up with the user having "selected" multiple entries, that they probably did not actually intend to select:

https://github.com/craftcms/cms/assets/298510/f2c2fc9a-f97f-40b7-95e4-0355caa9f19e

In my opinion, this feels like unintended/unwanted behaviour: if the user clicks on an interactive node (i.e. button or link) inside an element index row or card, their intent is most likely not to "select" that element, but to achieve whatever action the interactive element they clicked provides. As such, I think it'd make sense to prevent elements from being selected when the user interacts with a button or link inside element index rows or cards.

### Steps to reproduce

1. 

### Craft CMS version

5.0.0-beta.11

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next release.

**Comment by brandonkelly** [comment]
5.0.0-RC1 is out with that fix.

**Comment by mmikkel** [comment]
Looks like there has been a regression for this fix, and as of Craft 5.0.5 the pre RC1 behavior is back:

https://github.com/craftcms/cms/assets/298510/48f05c98-6fc1-430d-87a2-093085a85596

I went back and tested some previous versions (5.0.0-RC1, 5.0.0 and 5.0.1) and FWIW, it looks like 5.0.1 is when the fix stopped working.

**Comment by brandonkelly** [comment]
Thanks @mmikkel. That’s fixed in 5.0.6.
