### ISSUE TITLE
[5.x]: Missing Level 2 Entries and Branch Limit Settings for entry fields in 5

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#14674]
### Description
After upgrade to Craft5, I noticed that i missed level 2 of selected entries for some entries fields.
I tried to replicate this on a new fresh site and it seems it only happens for some entries fields when Branch Limit is set -in my case set to 1- in Craft 4.
I also noticed that Branch Limit settings is missed in 5 when Maintain hierarchy is enabled.

### Craft CMS version

5.0.0-beta.11

### PHP version

8.2

### Database type and version

MariaDB 10.6.7

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR to fix both issues (missing branch limit field and missing 2+ level relations).

**Comment by brandonkelly** [comment]
5.0.0-RC1 is out with the fix for both of those issues. Thanks again!
