### ISSUE TITLE
[5.x]: Minor styling issue in CSS arrow in `<craft-tooltip>`

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#14672]
### Description

...this _could_ be an artistic choice, but the borders for the CSS arrows in the new `<craft-tooltip>` component look a little bit off 🙂

![CleanShot 2024-03-24 at 23 17 14@2x](https://github.com/craftcms/cms/assets/298510/33d42e39-a002-4e18-a549-5e112fd53613)

### Steps to reproduce

1.

### Craft CMS version

5.0.0-beta.11

### Operating system and version

macOS 14.3.1, Edge 122.0.2365.92

### Installed plugins and versions

-

**Comment by brianjhanson** [comment]
Thanks for reporting! This will be fixed up once #14677 gets merged.

**Comment by brandonkelly** [comment]
5.0.0-RC1 is out with that fix.
