### ISSUE TITLE
[5.x]: Impossible to filter matrix entries by custom field

### ISSUE THREAD

**Issue by plcdnl** [craftcms/cms#14671]
### Description
Hi, I do not know if it is a bug or is not planned for the future. But if i have a matrix field, i can't filter it for custom field as it happens in a normal entry query in graphql. 

<img width="1081" alt="image" src="https://github.com/craftcms/cms/assets/32842043/ec58b553-a66d-46d4-8079-52b966c4cacf">

<img width="1333" alt="image" src="https://github.com/craftcms/cms/assets/32842043/a1088d48-e28e-4bfb-986b-de7f752dac7f">

### Craft CMS version

5.0.0-beta.11

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed now for the next release.

**Comment by brandonkelly** [comment]
5.0.0-RC1 is out with that fix.
