### ISSUE TITLE
[4.8.3]: Login request sent to wrong host when using `baseCpUrl` to host CP on separate domain

### ISSUE THREAD

**Issue by klaus-gsma** [craftcms/cms#14676]
### Description

Since CraftCMS 4.8.3 the `actionUrl` is wrong when using 

It may be related to this:

```
Fixed a bug where action URLs weren’t respecting the subpath specified by the @web alias, if it wasn’t present in the local URL to index.php.
```

### Steps to reproduce

1. Set up site with `baseCpUrl` set to a different domain from default site's URL.
2. Go to `/admin/login` (assuming `cpTrigger` = admin)
3. View source
4. See:

```
 window.Craft = {
        ...,
        "actionUrl": "{{default site url}}/index.php?p=admin\/actions\/",
        ...
 }
```

5. This means that the login request (and others) are sent to the wrong domain, potentially (e.g. in our case) leading to CORS issues.

### Expected behavior

```
 window.Craft = {
        ...,
        "actionUrl": "{{CP URL}}/index.php?p=admin\/actions\/",
        ...
 }
```

### Actual behavior

```
 window.Craft = {
        ...,
        "actionUrl": "{{default site url}}/index.php?p=admin\/actions\/",
        ...
 }
```

### Craft CMS version

4.8.3

### Installed plugins and versions

-

**Comment by klaus-gsma** [comment]
https://github.com/craftcms/cms/pull/14679

**Comment by brandonkelly** [comment]
Are you explicitly setting your `@web` alias? If so, make sure it’s always getting set correctly.

It should be set to the URL where `index.php` lives (but not including `index.php`).

So if `index.php` lives at `https://cp.domain.com/index.php`, then `@web` should be `https://cp.domain.com/`.

Alternatively you can just stop setting `@web` explicitly. Craft is perfectly capable of figuring out what it should be set to on its own. There’s only a security concern there if you are using `@web` in a site base URL. But if you have multiple sites or your CP is located on a different domain, you definitely should not be using `@web` for site base URLs.

**Comment by mattbloomfield** [comment]
We just got locked out of our site with this same bug - luckily you can jump back to 4.8.0 to avoid it...

**Comment by mattbloomfield** [comment]
> Are you explicitly setting your `@web` alias? If so, make sure it’s always getting set correctly.
> 
> It should be set to the URL where `index.php` lives (but not including `index.php`).
> 
> So if `index.php` lives at `https://cp.domain.com/index.php`, then `@web` should be `https://cp.domain.com/`.
> 
> Alternatively you can just stop setting `@web` explicitly. Craft is perfectly capable of figuring out what it should be set to on its own. There’s only a security concern there if you are using `@web` in a site base URL. But if you have multiple sites or your CP is located on a different domain, you definitely should not be using `@web` for site base URLs.

This is really interesting and not how we rely on `@web` in code... I had understood it to be the base URL of the site, not the CP... May take us a while to untangle that.

**Comment by mattbloomfield** [comment]
I worry that by setting `@web` to our cp domain we will end up with CORS issues on front-end requests... don't image transforms hit index.php?

**Comment by brandonkelly** [comment]
@mattbloomfield It should be set to the correct base URL for each request. If your front-end and control panel access `index.php` differently, then `@web` should be set correctly for each of those.

**Comment by brandonkelly** [comment]
In general you should **not**:

- be using `@web` in your base site URLs(s)
- be setting `@web` explicitly

If you stick with avoiding `@web` and explicitly setting your base site URLs, Craft will define `@web` automatically based on the actual requested URL to `index.php`, and all will be fine.

**Comment by klaus-gsma** [comment]
For some reason we were setting `@web` to `"/"` (someone before me...). This worked well until `4.8.3`. I have now removed the `@web` alias and things are working again - thank you.

**Comment by klaus-gsma** [comment]
One question please @brandonkelly - how does the advice to not set `@web` mix with the advice in the [docs](https://craftcms.com/docs/4.x/config/#aliases)? 

>To prevent a variety of security issues, we recommend explicitly setting the `@web` alias with a fully-qualified URL, either via a configuration file (see below) or [environment variable](https://craftcms.com/docs/4.x/config/#env).

**Comment by brandonkelly** [comment]
@klaus-gsma Thanks for pointing that out. We’ll adjust that. There are exceptions that make setting it manually more complicated (like when you are using multi-site, or the CP base URL is different than the front-end), so really we should just be recommending against using `@web` for base site URLs, and leave it at that.

**Comment by klaus-gsma** [comment]
Thanks for your quick help on this. Think we can close this now.
