### ISSUE TITLE
[5.x]:  Matrix in matrix with hidden field label has extra padding in live preview

### ISSUE THREAD

**Issue by ZapaNOR** [craftcms/cms#14703]
### Description
If you have a matrix field inside a matrix field, and that field's title / label is hidden, you get an extra padding when using live preview.

<img width="703" alt="Screenshot 2024-03-26 at 22 13 55" src="https://github.com/craftcms/cms/assets/53942798/2a8cb612-5591-4fce-9c1f-52d207d8ec73">

### Steps to reproduce

1. Put matrix in matrix, hide labels

### Expected behavior
Same padding as when not in live preview

### Craft CMS version

5.0.0

### PHP version

8.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release via #14712.

**Comment by brandonkelly** [comment]
Craft 5.0.1 is out now with that fix. Thanks again!
