### ISSUE TITLE
[5.0]: JS error in element index - Double-instantiating a checkbox select on an element

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#14707]
### Description
When navigating in any element index there is an error in the console:
`CheckboxSelect.js:18 Double-instantiating a checkbox select on an element`

### Craft CMS version

5.0.0

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! This should be harmless, but I've raised a PR to prevent it from happening.

**Comment by thupsi** [comment]
Thanks, I have another issue that maybe is related to this one, so I'm waiting for this fix to test further.

**Comment by brandonkelly** [comment]
That’s fixed for the next 4 and 5 releases.

You can pull the fix in early by changing your `craftcms/cms` requirement to `5.x-dev as 5.0.0` and running `composer update`.

**Comment by brandonkelly** [comment]
Craft 4.8.7 and 5.0.1 are out with that fix.
