### ISSUE TITLE
[5.x]: View in a new tab for drafts opens different urls

### ISSUE THREAD

**Issue by samuel-clara** [craftcms/cms#14705]
### Description
Is it desired that by clicking on "View in a new tab" from the version indicator of a draft, the current entry url is displayed and not the draft url (as rightly happens via the "view" button placed near the "preview" button)?

Screenshot from the europa.museum demo
![meteorit 2024-03-26 at 23 38 16@2x](https://github.com/craftcms/cms/assets/11197191/5312392a-d834-463d-ad5b-a51cd19fa82e)

### Steps to reproduce

1. create a draft and click on "View in a new tab" from the version indicator
2. create a draft and click on "View" → "Primary entry page"

### Expected behavior

For me it would be more obvious that both button open the draft url

### Actual behavior
One button opens the entry url and the other with similar label opens the draft url.

### Craft CMS version

5.0.0

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 5.0.1 is out now with that fix. Thanks again!
