### ISSUE TITLE
[3.x]:  Queue Manager got stuck during "Resaving products" operation

### ISSUE THREAD

**Issue by devmansky** [craftcms/cms#14717]
### Description

The task 'Resaving products' exceeded the default MySQL timeout of 3600 seconds, causing it to enter a loop as the queue couldn't remove it from the queue list.

Our immediate solution was to extend the timeout. Is it recommended to increase the timeouts

### Craft CMS version

Craft Pro 3.9.5

### PHP version

8.1.27

### Database type and version

MariaDB 10.5.23

### Installed plugins and versions

Craft Commerce	3.4.23

**Comment by brandonkelly** [comment]
If you have a larger site and start hitting queue job timeouts, you should consider disabling the [runQueueAutomatically](https://craftcms.com/docs/3.x/config/config-settings.html#runqueueautomatically) config setting, and setting up a [different queue runner](https://craftcms.com/docs/5.x/system/queue.html#queue-runners) that works over CLI requests where there’s no max execution time.
