### ISSUE TITLE
[5.x]: Element cards overflow inside matrix fields in live preview

### ISSUE THREAD

**Issue by ZapaNOR** [craftcms/cms#14710]
### What happened?

If the edit part of the live preview gets too narrow, the element cards inside matrix fields overlap them:
![Screenshot 2024-03-27 at 12 38 09](https://github.com/craftcms/cms/assets/53942798/af484982-2511-4243-9311-336f8a64defe)

### Craft CMS version

5.0.0

### Installed plugins and versions

-

**Comment by brianjhanson** [comment]
I'm having trouble replicating this one. Can you provide a few more details about how your fields are set up so I can reproduce the issue?

**Comment by ZapaNOR** [comment]
This image shows an **Asset** field inside a **column** matrix field inside a **section** matrix field.
All of these fields have the label hidden.

It does not happen on bigger screens. Only on on smaller windows, or if you resize the sidebar to be a bit smaller.

**Comment by brianjhanson** [comment]
Thanks @Mathias-Syversen! The key turned out to be that it only happens when the cards are set to display as a grid. I've opened #14718 to fix this up.

**Comment by brandonkelly** [comment]
Craft 5.0.1 is out now with that fix. Thanks again!
