### ISSUE TITLE
[4.x]: Front-end registration password error message is not editable

### ISSUE THREAD

**Issue by vonscriptor** [craftcms/cms#14714]
### Description
Front-end user registration error message for the password field always returns "New Password should contain at least 6 characters." There is no apparent way to edit this message. It conflicts with modified password requirements.

### Steps to reproduce

1. Use https://craftcms.com/knowledge-base/front-end-user-accounts#registration-form or a plugin like Freeform to set a user's password.
2. Click 'Register' button.

### Expected behavior
Make the user password error message editable (config setting) and/or a way to toggle it off.

### Actual behavior
Seems to be hardcoded somehow.

### Craft CMS version

4.8.2

### PHP version

8.1.27

### Operating system and version

MacOS Sonoma 14.3.1

### Database type and version

MySQL 8.0.30

### Installed plugins and versions

- Freeform Pro v4.1.13

**Comment by brandonkelly** [comment]
How are you setting a different minimum password length? That’s not currently configurable.

**Comment by vonscriptor** [comment]
The scenario is if left blank it'll say min 6, so they do that but then it says the actual requirements.

![image](https://github.com/craftcms/cms/assets/1682225/0da0ec8f-0872-46f9-b195-c78b5d209221)

![image](https://github.com/craftcms/cms/assets/1682225/1ed3a3ca-f80e-4a63-aa21-c8591f3f6f9d)

**Comment by brandonkelly** [comment]
But how are you setting the 12 character minimum?

**Comment by vonscriptor** [comment]
I'm using: https://github.com/craftpulse/craft-password-policy

**Comment by brandonkelly** [comment]
OK, so that plugin should be removing Craft’s built in password validation, if it’s providing its own. Craft has no way of knowing that something else is going to be overriding its own password requirements.
