### ISSUE TITLE
[5.x]: Queue Manager Entries not discernible as links

### ISSUE THREAD

**Issue by olsp** [craftcms/cms#14716]
### What happened?

I was just wondering that the entries in the Queue Manager aren't links any longer. Visually it seems like it's just text. Also the cursor doesn't change on hover. Turns out they are links though.

### Craft CMS version

5.0.0

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.0.1 is out now with that fix. Thanks again!
