### ISSUE TITLE
[5.x]: Order sort options alphabetically

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#14725]
### Description

Both the sort options and table columns should be ordered alphabetically for improved user experience.

A possible additional enhancement is to have the element attributes first and custom fields ordered in a second option group.

![Screenshot 2024-03-29 at 06 42 06](https://github.com/craftcms/cms/assets/25124/bfcf743f-b70b-42c9-8060-4ee17aecd3f3)
![Screenshot 2024-03-29 at 06 42 02](https://github.com/craftcms/cms/assets/25124/c2730952-5695-4f36-ad9c-505b1d8e44f1)

### Craft CMS version

5

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Made both of those changes for 4.9 and 5.1 🎉

**Comment by brandonkelly** [comment]
Craft 4.9 and 5.1 are out now with that fix.
