### ISSUE TITLE
Plugin config file and translation category casing is inconsistent.

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/cms#1473]
### Description

Plugin config files must be all-lowercased versions of the plugin handles (e.g. `config/elementapi.php`), but plugin translation categories must be identically cased to the actual plugin handle (e.g. `translations/elementApi.php`).

We should probably be consistent with these by forcing translation categories to be lowercase as well.

**Comment by carlcs** [comment]
Sounds good, especially because if installed manually the plugin has to be lowercase as well `plugins/elementapi/`.

**Comment by carlcs** [comment]
`plugins/elementapi/`
`config/elementapi.php`
`translations/en/elementapi.php`
`translations/de/elementapi.php`

…nice!
