### ISSUE TITLE
[5.x]: Double clicking a link in an element index opens slideout AND triggers browser navigation

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#14736]
### Description

Links inside element index rows and cards respond to **double clicking** BOTH by opening a slideout AND navigating to the link target.

### Expected Behavior
It would be expected that only one of the above actions would be triggered (slideout OR navigation).

FWIW, personally I'm in favour of the slideout, since it still suffers from low discoverability and would benefit from a larger click/tap target.

### Actual Behavior
As an example, when the user double-clicks on the element title, a slideout opens momentarily and then follows a browser navigation to the element edit screen.

### Craft CMS version

5.0.0

### Installed plugins and versions

-

**Comment by i-just** [comment]
Thanks for reporting! I raised a PR for it.

**Comment by brandonkelly** [comment]
Craft 5.0.1 is out now with that fix. Thanks again!
