### ISSUE TITLE
[5.x]: Alternate "Grid" icons for entry types do not appear

### ISSUE THREAD

**Issue by amphibian** [craftcms/cms#14740]
### Description

When selecting any of the numbered grid icons for an entry type (e.g., grid-2, grid-4, grid-5), the icon does not appear outside of the setting screen for that entry type. The standard "grid" icon works as expected.

### Steps to reproduce

1. Create an entry type.
2. Select any of grid-2, grid-4, or grid-5 icons.

### Expected behavior

The proper icon displays alongside the entry type.

### Actual behavior

No icon is displayed.

<img width="509" alt="Screenshot 2024-04-02 at 9 21 54 AM" src="https://github.com/craftcms/cms/assets/53333/444fd9dd-2c65-4781-9f6b-1d92af7df94c">

### Craft CMS version

5.0.0

### PHP version

8.2.15

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.0.1 is out now with that fix. Thanks again!
