### ISSUE TITLE
[5.x]: Changing a channel to a structure does not seem to work

### ISSUE THREAD

**Issue by amphibian** [craftcms/cms#14741]
### Description

When converting an existing channel withe entries (created on a fresh Craft 5 install), the section is correctly marked as a structure but has none of a structure's features.

### Steps to reproduce

1. Create a new channel.
2. Add some entries (not sure if this is required to reproduce the bug).
3. Convert that channel to a structure.

### Expected behavior

The structure shows up with a proper element index (nesting, reorder handles).

### Actual behavior

The structure still appears as a channel.

### Craft CMS version

5.0.0

### PHP version

8.2.5

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch! Did you switch to the structure mode once the background tasks have finished? (First button next to the search bar on the entries index page)?
<img width="1506" alt="Screenshot 2024-04-02 at 15 55 57" src="https://github.com/craftcms/cms/assets/4500340/46ce0408-4c2a-4b6a-a997-69648f5def41">

**Comment by amphibian** [comment]
Ah, no I did not. That did it, thanks.

**Comment by i-just** [comment]
Cool, glad it’s working!
