### ISSUE TITLE
[4.x]: Users not removed from the database when removed from dashboard.

### ISSUE THREAD

**Issue by JamieC24** [craftcms/cms#14746]
### Description

Hello! 

We've come across a bug while working on a client site recently where a client needed to have an account reinstated which they had previously removed by way of the admin system.

When they set up the new account with the same credentials as their previous one, the activation url just brings them to the homepage of the site, as if their user account is already set up.

We had a look in the database and it looked like, even though the user had been removed from the admin system, its entry seemed to still exist in the craft_users table. Once we removed the database entry, the activation url worked as expected in our tests.

Is this intended functionality? Or was it something that was patched in a later version of Craft?

### Steps to reproduce

1. Create a fresh Craft install on version 4.5.9
2. Log in to the admin dashboard
3. Create a user with an email you have access to and activate the user account.
4. Remove that user in the admin system.
5. Check the craft_users table to see if the user is still there (it was for us)

### Expected behavior

Once a user is removed from the admin system, it gets removed from the database.

### Actual behavior

When a user is removed from the Craft admin system, their craft_user entry still exists

### Craft CMS version

4.5.9

### PHP version

8.1

### Operating system and version

MacOS Sonoma 14.4.1

### Database type and version

MySQL 5.7.39 (UTF 8 encoding)

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch! 

When you delete a user (or any other Element), they are marked as deleted in the `elements` table thanks to the soft delete feature. You can customise how long elements stay soft deleted before being cleared out by the garbage collection via [`softDeleteDuration`](https://craftcms.com/docs/4.x/config/general.html#softdeleteduration) setting.

It’s also worth noting that the activation URL won’t work if it was used before, if the token expired, or if it is deemed invalid.

I hope this helps!

I will close this one, but feel free to reply if you run into any more problems.
