### ISSUE TITLE
[5.x]: Issue with Selecting Entries in Related Entries Modal - Clicking Entry Title Does Not Select Column

### ISSUE THREAD

**Issue by iuscare** [craftcms/cms#14751]
### Description
In the current CraftCMS 5.0 version, there's a changed behavior observed: when attempting to select an entry within the modal that opens for a related entries field, a column is not selected when clicking on the title of the specific entry. To have the click recognized, one must either click the checkbox or a white space between the columns.

### Steps to reproduce

1. Navigate to a related entries field within any content section in CraftCMS 5.0.
2. Click on the button to open the modal for selecting related entries.
3. Try to select an entry by clicking directly on the title of the entry within the modal.

### Expected behavior
When clicking on the title of an entry in the modal, the corresponding column should be selected, indicating that the entry has been chosen. This action should be equivalent to clicking the checkbox or the white space between the columns for selection purposes.

### Actual behavior
Clicking directly on the title of an entry within the modal does not result in the column being selected. The only way to select an entry is by clicking on the checkbox or the white space between the columns. This behavior deviates from the expected user interaction, making it less intuitive to select related entries.

https://github.com/craftcms/cms/assets/33871309/48724c3e-60f9-416a-ae49-5d53a1391951

### Craft CMS version

5.0

### PHP version

8.3

### Operating system and version

MacOS 14.1.1 (23B81) / Arc Browser

### Database type and version

Mysql 8.0

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 5.0.1 is out now with a fix.
