### ISSUE TITLE
[5.x]: Unable to create matrix child from graphql mutation

### ISSUE THREAD

**Issue by plcdnl** [craftcms/cms#14750]
### What happened?

Description
Is it possible to create a matrix child from graphql mutation? I'm able to fill all fields and graphql say to me that everything is correct but i can't see the field filled

Steps to reproduce
![image](https://github.com/craftcms/cms/assets/32842043/1901a564-dfb2-496a-bba3-06c84eee3077)

In craftcms entries i'm able to see the new entry but matrix field "overview" is empty

DDEV Local development

### Craft CMS version

 5.0.0

### PHP version

8.2

### Installed plugins and versions

-

**Comment by olivierbon** [comment]
Received in support.
