### ISSUE TITLE
[5.x]: Impossible to create new matrix child after upgrade to craft 5.0.1

### ISSUE THREAD

**Issue by plcdnl** [craftcms/cms#14754]
### Description
If i downgrade to 5.0.0 everything works.

<img width="1680" alt="image" src="https://github.com/craftcms/cms/assets/32842043/9463dd7a-969f-46eb-a4bd-590315e8a06d">

### Craft CMS version

5.0.1

**Comment by plcdnl** [comment]
Thank you @i-just. Could you also answer this question for me? I can't migrate most of the content from the old site to the new site. 
https://github.com/craftcms/cms/issues/14750

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.0.2 is out with that fix. Thanks again!
