### ISSUE TITLE
[5.x]: siteStatusesForElement does not return site status for a trashed and enabled element

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#14753]
### Description
Hi.
I noticed that `ElementHelper::siteStatusesForElement` returns `false` for a site when an element is `disabled` and element is `trashed`.
but if an element is `trashed` and its status is `enabled` for a site, `siteStatusesForElement` returns nothing for that site,
so I guess this is a bug.
Thanks!

### Craft CMS version

5.0.0, 4.8.6

### PHP version

8.2

### Database type and version

MariaDB 10.6.7

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed in 5.0.2.

**Comment by brandonkelly** [comment]
4.8.8 is also out with a fix for that.
