### ISSUE TITLE
[5.x]: Can't delete a existing global set

### ISSUE THREAD

**Issue by mudechs** [craftcms/cms#14757]
### Description
As of the fact, that globals will be merged to entries in the future i wanted to delete a existing global set and refactor it as a structure section. If i try to delete the global set i get a error that it can not be deleted. This installation is a new one and not a updated site from a older craft version.

### Steps to reproduce
Settings -> Globals -> delete a existing set

### Expected behavior
Delete set

### Actual behavior
- not deleted
- popup with the msg: Couldn’t delete “Firmendaten”.

### Craft CMS version

5.0.1

### PHP version

8.2.17

### Operating system and version

FreeBSD 13.2-RELEASE-p11

### Database type and version

MariaDB 10.6.16

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-62)

### Installed plugins and versions

- CKEditor 4.0.3
- Social Share 2.0.0-beta.1
- Sprig 3.0.0-beta.2

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.0.2 is out with that fix. Thanks again!
