### ISSUE TITLE
New custom fields in `content` table get positioned after the `uid` column

### ISSUE THREAD

**Issue by BenParizek** [craftcms/cms#1475]
### Description

When you create a new field, in Craft 2, the field's column in the db would be placed between the `title` and `dateCreated` columns in the db. In Craft 3, it appears the field now gets placed after all other fields:
http://share.barrelstrength.co/3e1V2h383Z1x

This could be by design, but I found it to be more intuitive while looking through the db to find custom fields between the `title` and `dateCreated` column.

### Steps to reproduce

1. Create a new field
2. Look for it in the content table of the db

### Additional info

- Craft version: Craft CMS 3.0.0-beta.6
- PHP version: 7
- Database: MySQL
- Plugins & versions: none

**Comment by takobell** [comment]
This is a side-effect of adding support for databases other than MySQL.  The `ALTER COLUMN AFTER/BEFORE` syntax isn't in the ANSI SQL code so MySQL's implementation of it is proprietary.
