### ISSUE TITLE
[5.x]: Global set reordering does not stick when using Safari

### ISSUE THREAD

**Issue by amphibian** [craftcms/cms#14752]
### Description

When reordering global sets with Safari (17.4.1), a javascript error prevents the reorder from saving.

### Steps to reproduce

1. Create two or more global sets.
2. Reorder those sets using Safari.
3. Reload the page.

### Expected behavior

The sets are in the new order.

### Actual behavior

The sets are still in the old order.

### Craft CMS version

5.0.0

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.8.8 and 5.0.3 are out with the fix for this. Thanks again!
