### ISSUE TITLE
[5.x]: Performance issues in element index when entry thumb is displayed

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#14760]
### Description

When navigating to an entry index with entry thumbs enabled (_via the entry type settings_) performance is abnormaly slow.

### Testing parameters
Structure with 154 entries, 76 of them with thumbnail, display mode "structured table" (plain table is about the same, cards is even slower)

### Performance of "get-elements" action:

**No thumbnails:**
Processing time: 293 ms
Peak memory: 6.386 MB
Query count: 134

**With thumbnails:**
Processing time: 1,824 ms
Peak memory: 32.676 MB
Query count: 555

_And now for a surprise..._
**"With thumbnails" but also with an additional column showing the same image thumbnail:**
Processing time: 465 ms
Peak memory: 9.988 MB
Query count: 	374

### Comments

- The "with thumbnails" timings are about 6x of "no thumbnails"
- The "with thumbnails" timings are much lower when a column with the same image is added to the table. This clearly demonstrates that something fishy is going on!

### Craft CMS version

5.0.1

### PHP version

8.3.2

### Database type and version

MySQL 8.0.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

**Comment by thanasispsarros** [comment]
### Additional testing

**No entry thumbnail, but using additional column with image**
Processing time: 410 ms
Peak memory: 8.859 MB
Query count: 258


### Also I checked the DB queries for each of the above cases and filtered with "assets":

**With entry thumbnail:**

![thumb_only](https://github.com/craftcms/cms/assets/159689562/3da53310-971f-4c32-a5e4-c02fb8b8a596)

**With entry thumbnail and image column:**

![thumb_and_img_column](https://github.com/craftcms/cms/assets/159689562/d9c435c8-af87-4757-8b2f-1e36aa58bd5a)

**Image column only:**

![img_column_only](https://github.com/craftcms/cms/assets/159689562/057471e8-dc20-428f-a189-fa93f96b1ff7)

(With no thumbnail and no image oclumn there obviously where no duplicated queries nor queries with the word 'assets')

**Comment by thupsi** [comment]
### Additional testing
**No entry thumbnail, but using additional column with image**
Processing time: 410 ms
Peak memory: 8.859 MB
Query count: 258

### Also I checked the DB queries for each of the above cases and filtered with "assets":

**With entry thumbnail:**

![image](https://github.com/craftcms/cms/assets/19857599/45cd9edf-46b6-4701-87c4-c3e119c55dad)

**With entry thumbnail and image column:**

![image](https://github.com/craftcms/cms/assets/19857599/9841378e-451a-4960-8e2e-f6d61b9e46ac)

**Image column only:**

![image](https://github.com/craftcms/cms/assets/19857599/1aabb393-1095-4667-b7a0-0ba780ea0feb)


(With no thumbnail and no image column there obviously where no duplicated queries nor queries with the word 'assets')

**Comment by thupsi** [comment]
Hey @brandonkelly! I see that you pushed [d6a3117](https://github.com/craftcms/cms/commit/d6a31171e6178af5a20de62786899cdee220d244) that addresses this issue. ~~Just a heads up: With that fix in place, when I switch a structure's view to plain table or card view, the thumbnails dissapear.~~

**Comment by thupsi** [comment]
Whoops! Scratch that last comment, it works just fine: Due to the table sorting the entries with no thumbnail where displayed at the top! 🤪

**Comment by brandonkelly** [comment]
Yep! Just pointed that release note to this issue though.

**Comment by brandonkelly** [comment]
5.1.4 is out with that fix!
