### ISSUE TITLE
image transforms regeneration not triggered when "replace"ing an image asset

### ISSUE THREAD

**Issue by olets** [craftcms/cms#1476]
### Description

"Replacing" an image asset doesn't trigger a rerun of that asset's transformations.

### Steps to reproduce

1. Create an image asset field
1. Set up image transformations
1. Add it to an entry
1. Edit the entry, and upload that image. Save.
1. Set up a template that displays one of the transformed copies of that entry's image
1. Load the page, see the expected image.
1. Edit the entry > edit the image asset > upload a new image with the same file name as the old one. Say "replace". Save.
1. Reload the page, see the old image

### Additional info

- Craft version: 2.6.2794
- PHP version: 5.4.45
- Database driver & version: mysql 5.0.10, sqlite 3.8.10.2, pgsql 8.4.22
- Plugins & versions:
    - PHP plugins:  mysqlnd 5.0.10, example, debug_trace, auth_plugin_mysql_native_password, auth_plugin_mysql_clear_password
    - CMS plugins: cacheclear, disqus, oauth, sitemap, twitter, videos

**Comment by andris-sevcenko** [comment]
Not able to reproduce this. Maybe you're using some caching that's not getting invalidated properly? If you can reproduce this reliably, get in touch via support@craftcms.com and we'll take it from there.

**Comment by olets** [comment]
Finally solved this! Noticed this problem was happening on a server set up with GD but wasn't happening on a different server set up with Imagemagick. Switching the problem server from GD to Imagemagick resolved the issue.

Might be a GD problem, but it might be a Craft-with-GD problem - haven't done any further experimentation.

cc @andris-sevcenko

**Comment by olets** [comment]
scratch that, QA error. this is not solved @andris-sevcenko
