### ISSUE TITLE
[5.x]: Required Field Indicator missing from title fields

### ISSUE THREAD

**Issue by brionwolf** [craftcms/cms#14773]
### Description

- Required field indicator missing from title fields.
- This is especially confusing if the title field label has been renamed.
- _Apologies if this is a nitpick or a feature request. If so, I'll re submit as such, Thanks!_

### Steps to reproduce

1. Create Entry Type and assign to a section, or matrix field on a section.
2. Keep the title field enabled and visible for users.
3. Create a new entry that uses that entry type.

### Expected behavior

- The title field includes the red "required"  asterisk _[*]_, as with other _required_ fields.

### Actual behavior

- No asterisk appears on the title field.

### Screenshots

<img width="610" alt="screenshot of an entry with a title field" src="https://github.com/craftcms/cms/assets/5532234/22c0b884-e73a-4526-a973-0829e419fe95">

<img width="1242" alt="screenshot of an entry with a title field that has been relabeled" src="https://github.com/craftcms/cms/assets/5532234/5de632be-42f4-4281-9745-40ae1961447b">

### Craft CMS version

Craft Pro 5.0.2

### PHP version

8.3.4

### Operating system and version

MacOS Sonoma 14.4.1 (23E224)

### Database type and version

MySQL 8.3.0

### Image driver and version

GD 8.3.4

### Installed plugins and versions

- CKEditor => 4.0.3

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.0.3 is out with that fix. Thanks again!

**Comment by brionwolf** [comment]
Tiny little change, but really helps our Content editors. Thanks all! Looks good to me!
