### ISSUE TITLE
[5.x]: Card view in matrix field and entries field are different (and confusing in entries field)

### ISSUE THREAD

**Issue by idleog** [craftcms/cms#14778]
### What happened?

I have an asset field (image) in an entry type and I use the same entry type within a matrix field and for a channel section.

Now, the view for the entry type as a card in the matrix field is different than the entry type as a card in the entries field. 
Within the entries field it's very confusing showing the reorder icon twice (even max assets is set to one).

Here are the screenshots:
In matrix field:
<img width="803" alt="matrix_field" src="https://github.com/craftcms/cms/assets/870071/bd620e9e-9b04-4284-8ecf-917c73f29205">

In entries field:
<img width="796" alt="emtry_field" src="https://github.com/craftcms/cms/assets/870071/402d224c-cb22-4c80-8440-3662d7f23829">

### Craft CMS version

5.0.2

### PHP version

8.3.2

### Operating system and version

MacOS 14.4.1

### Database type and version

MySQL 8.0.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 5.0.3 is out with a fix.
