### ISSUE TITLE
[5.x]: Asset deletion when moving folders

### ISSUE THREAD

**Issue by thomasvantuycom** [craftcms/cms#14770]
### Description

I've developed a plugin that integrates a Cloudinary filesystem into Craft CMS. During testing, I encountered an issue where moving folders resulted in the deletion of assets contained within them. After investigating, I identified and addressed a bug on my end. However, I've hit a roadblock with Craft's behavior, which is hindering me from fully resolving the issue.

Craft's process for moving folders involves compiling a list of files to move and [setting the `force` parameter to `true`](https://github.com/craftcms/cms/blob/b343f03dd8ab6061908ff21a2451223902b8d33c/src/helpers/Assets.php#L322) for each asset relocation. Subsequently, the `AssetsController` verifies for any conflicting assets and [deletes the original asset if none are found](https://github.com/craftcms/cms/blob/b343f03dd8ab6061908ff21a2451223902b8d33c/src/controllers/AssetsController.php#L665). Only then does Craft invoke the `moveAsset` method of the assets service. However, Cloudinary executes asset movements by either renaming or copying the original asset. Since Craft has already deleted the asset by this point, Cloudinary cannot execute the move operation. I anticipate that other remote filesystems might encounter a similar obstacle.

As a potential solution, I wonder if there could be an event or an option to either opt out of the `force` parameter or prevent asset deletion within the controller. This would offer flexibility for users facing similar challenges with remote filesystem integrations.

### Craft CMS version

5.0.2

### PHP version

8.2

**Comment by brandonkelly** [comment]
The filesystem should not have actually moved the original asset at that point.

The line of code you linked to is there to make sure there’s no conflicting file at the target location, even though we don’t have a record of one (e.g. if a file was placed there some other way than uploaded via Craft).

**Comment by thomasvantuycom** [comment]
That's the crux of the problem: the filesystem has yet to move the asset, but it proceeds to delete the asset at its original location, making it impossible to move thereafter.

**Comment by brandonkelly** [comment]
It’s deleting a file (if one happens to exist – unlikely) at the _target_ location, not the asset’s original location.

**Comment by thomasvantuycom** [comment]
Now I understand. In Cloudinary, especially in dynamic folders mode, assets are distinguished solely by their filenames. This implies that `image.png` and `folder/image.png` are essentially treated as the same. Consequently, when attempting to move `image.png` to `folder`, Craft request to delete `folder/image.png`, which in Cloudinary translates to deleting `image.png`. This brings me back to my initial question: is there a method to prevent the `force` parameter from being applied to asset moves triggered by folder relocations?

**Comment by brandonkelly** [comment]
Yikes, that is going to lead to a lot of bugs, as Craft doesn’t have any restriction preventing multiple files from having the same name in different folders. Maybe you need to be telling Cloudinary that the filenames are actually the full folder path + filename? I believe that’s effectively how S3 works.

> This brings me back to my initial question: is there a method to prevent the force parameter from being applied to asset moves triggered by folder relocations?

This doesn’t seem like the right approach, considering the root issue.

**Comment by thomasvantuycom** [comment]
Previously, Cloudinary operated on the basis of using filenames as folder paths followed by the filename itself. However, they are transitioning to a different mode, as I described. I'm currently working on supporting both modes of operation. While it may seem error-prone, everything functions properly, except for the movement of folders. Interestingly, even that works when I comment out the if-block triggered when `force` is set to true, prompting my inquiry. Moving individual assets functions smoothly because `force` is not set. If there are no plans to include such an option, feel free to close the issue. However, I'm curious if it's possible to interface with the UI's JavaScript code as an alternative solution.

**Comment by brandonkelly** [comment]
> While it may seem error-prone, everything functions properly, except for the movement of folders.

So if you create two subfolders, and upload two separate files with the same filename to each of them, the second one doesn’t end up overriding the first?

**Comment by robinbeatty** [comment]
Could the plugin enforce unique file names for the volume, and would that be a pathway forward?  I believe cloudinary has an option to enforce that at their end.

**Comment by brandonkelly** [comment]
I’m not sure how we’d go about that, since you can change a filesystem’s type/settings after creation, and after the assets already exist within it.

**Comment by robinbeatty** [comment]
Though could it be a plugin scope thing, i.e. it checks for asset filename before procedure, one more db hit but achieve same thing?

**Comment by brandonkelly** [comment]
I’m not following you there. You mean give the filesystem a way to prevent itself from being used by a volume, if any assets have duplicate filenames?

Filesystems could be swapped out via environment variables, so there’s not necessarily a point where they are registered to a volume.

**Comment by robinbeatty** [comment]
I see what you mean. In this use case I think @thomasvantuycom is now working on another solution. Thanks

**Comment by brandonkelly** [comment]
Alright, going to go ahead and close this.
