### ISSUE TITLE
[5.x]: Sorting of Structures/Entries does not work

### ISSUE THREAD

**Issue by philipschilling** [craftcms/cms#14780]
### Description

The sorting of Structure Entries does not work for me. The sorting element disappears after the selection of a value (e.g. Title) from the dropdown. The sorting does not change. I tested it in the latest Chrome and Safari browser on Mac.

<img width="986" alt="Screenshot 2024-04-09 at 14 06 45" src="https://github.com/craftcms/cms/assets/4956295/06cc517a-af22-44c7-82b2-fd9279897e47">

For the Channels Entries the sorting does work for me.

### Steps to reproduce

1. Open Entries tab
2. Open "Structures"
3. Click "View" button"
4. By default the sorting elements are not shown
5. Click on Channels
6. Click again on Structures
7. Now the sorting elements are shown but they disappear once selected and the sorting does not change

### Expected behavior

The sorting elements shall not disappear + the entries shall be sorted by the selected field.

### Actual behavior

See description.

### Craft CMS version

5.0.2

### PHP version

8.2.17

### Operating system and version

Mac OS 14.4.1

### Database type and version

MariaDB 10.4.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.1-29)

### Installed plugins and versions

-

**Comment by thupsi** [comment]
I think the bug here is that the sorting options should not be visible while you have 'structure' view selected.

**Comment by i-just** [comment]
Hi, thanks for reporting! Yes, the bug is that you shouldn’t see the sorting options when in the `structure` view mode (like you couldn’t see them in Craft 4); more precisely, when you switch to a channel and then structure again, the sorting options are not hiding properly. PR to follow.

**Comment by brandonkelly** [comment]
Got that fixed for the next release.

**Comment by philipschilling** [comment]
Awesome. Thank you.

**Comment by brandonkelly** [comment]
Craft 4.8.8 and 5.0.3 are out with the fix for this. Thanks again!
