### ISSUE TITLE
[5.x]: Only the first 100 assets shown when choosing an assets from a field

### ISSUE THREAD

**Issue by olsp** [craftcms/cms#14790]
### Description

I have currently about 300 assets uploaded. When I want to assign one of them (via the overlay) to an asset field, I can only browse through the list of the first 100 assets. There is no option to show more assets. When using the search I can find the asset.

### Steps to reproduce

1. Upload more than 100 assets
2. Create an asset field and assign it to an entry type
3. Create an entry and try to select an asset that comes after the first 100 in the list

### Expected behavior

The next assets should show up either via "lazy loading" or a pagination should be added

### Craft CMS version

5.0.4

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.0.5 is out with that fix. Thanks again!
