### ISSUE TITLE
Remove restrictions on the context to use index actions

### ISSUE THREAD

**Issue by nateiler** [craftcms/cms#1479]
The context/source can be a pretty powerful combination, however elementIndex actions are only available to 'index' context types.  I have been experimenting with a user elementIndex and a custom context (I do not want to register actions/sources for all user indexes, just my plugins view).  Everything seems to work well except actions are not available... they never show up because the context is not 'index'.

Aren't actions only returned based on context and therefore a 'modal' context would not have actions?  This would eliminate the need to do a bunch of context == 'index' conditionals.

**Comment by brandonkelly** [comment]
If I'm reading this right, you're just asking for us to remove `context == 'index'` conditionals from the JS for action-related things – correct?

**Comment by nateiler** [comment]
Yes.  Or change them to context != 'modal' ... (if there is a reason for them that I'm not seeing).

There are also references in the ElementIndexController.

Would you like a pull request?
