### ISSUE TITLE
[5.x]: Clicking through matrix tabs quickly triggers double-click handler

### ISSUE THREAD

**Issue by jamesedmonston** [craftcms/cms#14791]
### Description

When a matrix block has tabs, clicking through them quickly triggers the double-click handler and minimises the block.

https://github.com/craftcms/cms/assets/4851924/96b3a95e-5c6f-4e7c-b50b-4d5b7b159dc2

### Steps to reproduce

1. Create a matrix field with tabs
<img width="1153" alt="Screenshot 2024-04-11 at 11 46 21" src="https://github.com/craftcms/cms/assets/4851924/ea04543d-c4af-470a-8b40-61b721307a4d">

### Expected behavior

Clicking through the tabs at any speed should change the active tab.

### Actual behavior

Clicking through the tabs quickly triggers the double-click handler, minimising the matrix block.

### Craft CMS version

5.0.3

### PHP version

8.2.11

### Operating system and version

Linux 4.15.0-213-generic

### Database type and version

MySQL 8.3.0

### Installed plugins and versions

- CKEditor 4.0.3
- DigitalOcean Spaces Filesystem	3.0.0-beta.1
- Hyper 2.0.0-beta.7
- Navigation 3.0.0-beta.2
- SEO v5.0.0-rc1

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.0.5 is out with that fix. Thanks again!
