### ISSUE TITLE
[4.x]: Changing existing field to Lightswitch is broken

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#14792]
### Description

```
SQLSTATE[42701]: Duplicate column: 7 ERROR: column "field_productOnlineStock_quskocqc" of relation "content" already exists
The SQL being executed was: ALTER TABLE "content" ADD "field_productOnlineStock_quskocqc" boolean
```

### Steps to reproduce

1. Create a number field, for example
2. Save it
3. Change to Lightswitch type

### Expected behavior

It changes to Lightswitch type

### Actual behavior

Error (as above)

### Craft CMS version

4.8.8

### PHP version

8.3

### Database type and version

PostgreSQL

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 4.8.10 is out with the fix for this. Thanks again!
