### ISSUE TITLE
[5.x]: Typed property craft\widgets\QuickPost::$entryType must not be accessed before initialization

### ISSUE THREAD

**Issue by d13creative** [craftcms/cms#14794]
### Description

The dashboard home page is not accessible due to this error after upgrading from Craft 4 Solo to Craft 5.

This project has been upgraded several times from version 2 -> 3 -> 4 over the years

### Steps to reproduce

1. Upgrade from Craft 4 to Craft 5
2. Added bootstrap.php to root
3. Updated craft file in root
4. Updated index.php in webroot
5. Initially had an error saying there was an issue with a cookie which was resolved by adding a security key using `php craft setup/security-key `

### Expected behavior

The dashboard should be accessible

### Actual behavior

It throws an internal server error on the dashboard page. The front end is fully functional as is the rest of the backend (e.g. entries, assets etc.).
![Screenshot 2024-04-11 at 13 07 54](https://github.com/craftcms/cms/assets/1433528/a519a339-0019-42e4-939f-ce50bf79fecd)
 

### Craft CMS version

Craft Solo 5.0.4

### PHP version

8.2

### Operating system and version

Ubuntu 22.04

### Database type and version

MariaDB 10.11.7

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

CKEditor 4.0.3

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

You can get the fix now by changing your `craftcms/cms` requirement in `composer.json` to `5.x-dev as 5.0.4`, and then run `composer update`.

> This project has been upgraded several times from version 2 -> 3 -> 4 over the years

Might go even further back then that! The only way (as far as I can tell) this could have happened is if you had a Quick Post widget that hadn’t been saved since before v1.2!

**Comment by d13creative** [comment]
Great, thanks, very possible it was version 1 initially!

I’m always a bit apprehensive posting an issue on github in case it’s just
me being a numpty so glad that wasn’t the case on this occasion!🤣

Regards,
Dylan

**Comment by brandonkelly** [comment]
Craft 5.0.5 is out with that fix. Thanks again for reporting!
