### ISSUE TITLE
[5.x]: Alphabetic table column sorting for custom fields in Control Panel's entries view

### ISSUE THREAD

**Issue by philipschilling** [craftcms/cms#14806]
### Description

It is not a bug but a nice-to-have improvement.

### Steps to reproduce

1. Open Control Panel
2. Click "Entries" from left sidebar
3. Click on "View" button at the top right (Case 1) or click on the three dots at the left below the section names (Case 2)

<img width="689" alt="Screenshot 2024-04-13 at 00 47 17" src="https://github.com/craftcms/cms/assets/4956295/5621f214-80a4-4876-8244-bb27cf4bf77b">
<img width="689" alt="Screenshot 2024-04-13 at 00 47 39" src="https://github.com/craftcms/cms/assets/4956295/3a7b7a5b-efd1-457d-9305-ab4d3b11384f">
<img width="409" alt="Screenshot 2024-04-13 at 00 50 07" src="https://github.com/craftcms/cms/assets/4956295/c078acb7-a305-4677-8ac3-0cb982107431">

### Expected behavior

If you have many fields, it can become confusing and would be easier to scroll through an alphabetic list (especially for the custom fields).

### Actual behavior

The custom fields for the table sorting in the Control Panel's entries view are currently sorted in the order of ID or Create Date I assume.

### Craft CMS version

Craft Solo 5.0.4

### PHP version

8.2.17

### Operating system and version

Mac OS X 14.4.1 Sonoma

### Database type and version

MariaDB 10.4.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.1-29)

### Installed plugins and versions

CKEditor	4.0.3
Embedded Assets	5.0.1
Formie	3.0.0-beta.5
SEOmatic	5.0.2
UTM Tracker	3.0.0

**Comment by brandonkelly** [comment]
Already added for 5.1 🎉  (#14725)
