### ISSUE TITLE
[5.x]: Matrix field shown twice in Entry Criteria dropdown when customizing sources

### ISSUE THREAD

**Issue by philipschilling** [craftcms/cms#14809]
### Description

I am not sure if that should be the normal behaviour but for me it is strange. When I create in the Control Panel in the Entries area a new view, I can see twice the name "Matrix field" as Entry Criteria. This happens only when I follow the steps below tested on the europa.museum Craft Demo.

<img width="840" alt="Screenshot 2024-04-13 at 02 24 05" src="https://github.com/craftcms/cms/assets/4956295/9053e66d-6655-4059-abcd-e2aa116dea76">

### Steps to reproduce

1. Open Settings > Fields
2. Rename the matrix-type field name "Content Blocks" to "Content Blocks 2" and handle from "ContentBlocks" to "ContentBlocks2"
3. Create a new matrix-type field name "Content Block" and handle "ContentBlock"
4. Open from left sidebar "Entries"
5. Click on the three dots "Customize Sources"
6. Click on plus sign to add "New custom source"
7. Open dropdown "Entry Criteria" where the Matrix field is listed twice

When I create a completely new, additional matrix field, there will not appear another Matrix field option in the "Entry Criteria" dropdown. Maybe it is related to the fact that the original field "Content Block" has been connected to an entry type and that an entry has been created for an entry type including that field.

### Expected behavior

I would assume that the "Matrix field" is shown only once in the dropdown because it is the type of the field and not the name.

### Actual behavior

The Matrix field is shown twice in the Entry Criteria dropdown as described above.

### Craft CMS version

Craft Solo 5.0.4

### PHP version

8.2.17

### Operating system and version

Mac OS X 14.4.1 (23E224) Sonoma

### Database type and version

MariaDB 10.4.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.1-29)

### Installed plugins and versions

CKEditor	4.0.3
Embedded Assets	5.0.1
Formie	3.0.0-beta.5
SEOmatic	5.0.2
UTM Tracker	3.0.0

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 5.0.5 is out with that fix. Thanks again!
