### ISSUE TITLE
[5.x]: Site breadcrumb link has no URL, if there are multiple site groups

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#14802]
### Description

In a multi-site Craft 5 install with multiple site groups, the site breadcrumb link is missing its `href` attribute:

![CleanShot 2024-04-12 at 20 38 54@2x](https://github.com/craftcms/cms/assets/298510/ba284ece-8dab-4137-b7a1-bc0c8156992c)

### Steps to reproduce

1. Create at least two site groups.
2. Visit `/admin/entries`, and confirm that the site crumb doesn't have a `href` attribute.

### Expected behavior

The site crumb link should probably link to the active site, regardless of the number of site groups.

### Actual behavior

The site crumb link only has a `href` attribute when there is only a single site group.

### Craft CMS version

5.0.4

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 5.0.5 is out with that fix. Thanks again!
