### ISSUE TITLE
[5.x]: Translated spelling is not idiomatic in some languages

### ISSUE THREAD

**Issue by panlatent** [craftcms/cms#14800]
### Description

Translated spelling is not idiomatic in some languages.

In Chinese (zh), people are used to using Arabic numerals instead of spelling format `2`, which represents the quantity, is not translated (extra, it should not be translated as "二", it should be "两"). Craft uses the following code:

```php
Craft::t('app', '{count, spellout} {count, plural, =1{plugin} other{plugins}}', [
    'count' => $count,
]);
```

### Expected behavior

 2 => 2 

### Actual behavior

2 => 二

### Craft CMS version

5.0

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
@panlatent The translation for that message can be found in [src/translations/zh/app.php](https://github.com/craftcms/cms/blob/5.x/src/translations/zh/app.php#L2065). Can you please submit a PR with the corrected translation?

**Comment by panlatent** [comment]
@brandonkelly I will submit a PR next. The problem is not as simple as I thought. Changing `{count, spellout}` to `{count}` will cause the message to be inconsistent with the translation: In the Chinese environment, Intl will complain about plural and throw an exception, causing a fallback to the original translation.

**Comment by panlatent** [comment]
PR #14810 
Finish. Cannot write `{var} {var xxx}`.
yiisoft/yii2#11767
