### ISSUE TITLE
Allow BaseElementIndex.js to easily extend the POSTed endpoints

### ISSUE THREAD

**Issue by nateiler** [craftcms/cms#1480]
Can the POSTed action paths be configurable via the settings so one could point to their own controller without having to override the entire method.

This would apply to the following method: 
- updateElements
- submitAction
- refreshSources

**Comment by brandonkelly** [comment]
I don't see why not!

**Comment by nateiler** [comment]
I can make a pull request if you would like ... let me know.

**Comment by brandonkelly** [comment]
Resolved w/ ceffc96655bea651f4239af9b481d53ae61468b1
