### ISSUE TITLE
[5.x]: How to do eager loading of asset inside Matrix field entry type?

### ISSUE THREAD

**Issue by agosman** [craftcms/cms#14819]
### Description

When fetching a Matrix field via GraphQL, how would one also fetch nested asset fields inside of one of its entry types? 
Currently,  an empty array is returned. I suppose this has to do with having to define eager loading, but I can't find anything on it in the GraphQL API.

Thanks.

### Craft CMS version

5.0.4

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Can you post the GraphQL query you’re using?

**Comment by agosman** [comment]
Sure. The actual query is more elaborate and uses nested fragments but for the sake of simplicity, this query also returns an empty array:

```
query homepage {
  entry(section: "home") {
    id
    title
    ...on home_Entry {
      modulesMatrix {
        ...on visualModule_Entry {
          id
          visual {
            id
            url
          }
        }
      }
    }
  }
}

**Comment by brandonkelly** [comment]
Thanks! I was able to reproduce, and fixed for the next release.

You can pull in the fix ahead of time by changing your `craftcms/cms` requirement in `composer.json` to `"5.x-dev as 5.0.4"` and running `composer update`.

**Comment by agosman** [comment]
Thanks!

**Comment by brandonkelly** [comment]
Craft 5.0.5 is out with that fix. Thanks again!
