### ISSUE TITLE
Error when running `craft db/convert-charset`

### ISSUE THREAD

**Issue by tommysvr** [craftcms/cms#14815]
### Description
```
General error: 3780 Referencing column 'shopifyId' and referenced column 'shopifyId' in foreign key constraint 'fk_pxtdskovbiwpklhsqlvihxtbgoastdqcwxmz' are incompatible.'
```

### Steps to reproduce

1. Install Shopify plugin
2. Run `php craft db/convert-charset`
3. Proceed with the defaults `utf8` & `utf8_unicode_ci`

### Additional info

- Craft version: 4.8.9
- PHP version: 8.2
- Database driver & version: MySQL 5.7 / 8.0
- Plugins & versions: Shopify 4.1.1

**Comment by brandonkelly** [comment]
Thanks for reporting that! It’s been fixed for the next Craft release.

You can get the fix ahead of time by changing your `craftcms/cms` requirement in composer.json to `"4.x-dev as 4.8.9"`, and running `composer update`.

**Comment by brandonkelly** [comment]
Craft 4.8.10 and 5.0.5 are out with that fix.
