### ISSUE TITLE
OAuth 2 client

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/cms#1481]
Craft needs an OAuth 2 client in order to securely connect user accounts to Craft IDs on craftcms.com

**Comment by nateiler** [comment]
Out of curiosity, are you planning on leveraging https://github.com/yiisoft/yii2-authclient?

**Comment by takobell** [comment]
Using https://github.com/thephpleague/oauth2-client

**Comment by nateiler** [comment]
Whoot Whoot!

Are you planning on having an admin interface and it being extensible for plugin developers or will it be strictly for the plugin store?

**Comment by brandonkelly** [comment]
No reusable admin interface, but there's an `oauth_tokens` table that is generic enough for plugins to take advantage of if they want.

**Comment by nateiler** [comment]
Good to know.  Thanks.
