### ISSUE TITLE
Port Commerce to C3

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/cms#1482]

**Comment by yellowmamba** [comment]
Hi there, is there a rough timeline that Commerce will be supported in Craft 3?

**Comment by brandonkelly** [comment]
@yellowmamba No ETA, sorry. Commerce 2 is going to include some new features and refactoring as well, so it’s more involved than a simple port.

**Comment by russback** [comment]
@brandonkelly any update on this? I heard that Omnipay may be dropped in Commerce 3 and we're currently developing Commerce/Omnipay integration with 2 new offsite gateways for a site launch in Q1, so would like to make sure the client is prepared for any need for additional development.

**Comment by lukeholder** [comment]
@russback

Commerce 2 will be out for plug-in developers to review and test early next year, with a release on April 4th 2018 along with Craft 3 as preciously announced. 

Omnipay will not be required to provide a gateway to Commerce 2, but nothing stopping you developing an omnipay driver for your gateway - it will make it easier to provide that gateway to Commerce 2 when wrapping it in a plugin.

**Comment by russback** [comment]
Thanks @lukeholder. So to be clear, you're saying that existing Omnipay drivers will still work on Commerce 2?

**Comment by lukeholder** [comment]
We used the Ominpay gateway interface as a starting point, but extended it and added features. We will provide multiple example gateway plugins that wrap Omnipay gateways, it will not be a large amount of work to get an existing Omnipay gateway working with Commerce 2, just like Commerce 1.x. @russback

**Comment by angrybrad** [comment]
Late follow-up, but Commerce 2 works on Craft 3.
