### ISSUE TITLE
[5.x]: Order by custom fields groups entries by section

### ISSUE THREAD

**Issue by olivierbon** [craftcms/cms#14821]
### Description
When querying  multiple sections at once, (`.section(['galaxies','planets'])`), ordering by custom field returns a list of entries grouped by section.

Ordering by `postDate`, `title` works fine, problem only occurs with custom fields.

This works fine in Craft 4.

### Craft CMS version

5+

### Installed plugins and versions

-

**Comment by timohinze** [comment]
thanks for reporting @olivierbon 
btw: the same happens when you use two element types in one section

**Comment by i-just** [comment]
Thanks for all the info, Oli! ~~It looks to be affecting MySQL and not PgSQL~~. Looking into it!

**Comment by brandonkelly** [comment]
Fixed for 5.1 via 798b9d7ecbf8aa0b295d3450872fc304b77eff82

**Comment by brandonkelly** [comment]
Craft 5.1 is out with that fix.
