### ISSUE TITLE
[5.x]: Clicking username email address 404s

### ISSUE THREAD

**Issue by iamtompickering** [craftcms/cms#14830]
### Description
I have just noticed that clicking the users email in the right side panel takes me to a URL formatted as:

```
https://website.local/admin/mailto:hello@myemailaddress.co.uk
```

Which then returns a 404 page not found. Am I missing something here which is causing this error?

### Craft CMS version

5.0.4

### PHP version

8.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 5.0.5 is out with that fix. Thanks again!
