### ISSUE TITLE
[5.x]: Matrix fields set to display as cards but not in a grid will display in a grid when initially populated

### ISSUE THREAD

**Issue by amphibian** [craftcms/cms#14840]
### Description

When creating a Matrix field set to display in card view, but stacked (not in a grid), the initial entry creation inside of that field will nonetheless display the newly-added entries in a grid. After saving, the cards will display correctly (stacked).

### Steps to reproduce

1. Create a Matrix field, with its view set to cards (but not grid).
2. Assign that field to an Entry Type and  create a new entry with that Entry Type, then add some new entries to the new Matrix field inside that entry.

### Expected behavior

The entries added to the Matrix field display as stacked cards.

### Actual behavior

The entries added to the Matrix field display in a grid.

### Craft CMS version

5.0.4

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 5.0.5 is out with that fix. Thanks again!
