### ISSUE TITLE
[5.x]: Can't remove selected categories from entries

### ISSUE THREAD

**Issue by chadcrowell** [craftcms/cms#14843]
### Description

Nothing fancy going on here that I can tell... I have a Categories field in an Entry Type. I can add categories to the entry, but can't remove them. This is an admin account with all permissions. 

### Steps to reproduce

Here's the category field settings: https://d.pr/i/8GxSm5
Entry type settings: https://d.pr/i/BR1nTK
Entry: https://d.pr/i/1jU6Pv (missing the Remove option)

### Craft CMS version

5.0.4

### PHP version

8.2.15

### Operating system and version

Current MacOS

### Database type and version

MySQL 8.0.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

Amazon S3	2.2.1
Child Me!	2.0.0
CKEditor	4.0.3
Colour Swatches	5.0.0
Control Panel CSS	3.0.0
CP Field Inspect	2.0.1
Default Dashboard	3.0.0-beta.1
Expanded Singles	3.0.0-beta.2
Feed Me	6.0.0
Formie	3.0.0-beta.8
Hyper	2.0.0-beta.8
Image Resizer	4.0.0-beta.1
LJ Range Slider	5.0.0
Navigation	3.0.0-beta.3
oEmbed	3.0.8
Redirects	5.0.0
Section + Product Type	2.0.8
Securi Cache Clear	5.0.1
SEO	5.0.2
Smith	dev-craft-5
Table Maker	5.0.0-beta.2
Template Selector	5.0.1
Typogrify	5.0.0

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.0.5 is out with that fix. Thanks again!

**Comment by mmikkel** [comment]
Unfortunately, it looks like the "Remove" action is still missing from selected entries/categories at levels >1, on Craft 5.0.5:

https://github.com/craftcms/cms/assets/298510/1e2bee61-5a5f-41dc-ac50-26b95e73cd94

**Comment by brandonkelly** [comment]
Fixed in 5.0.6!
