### ISSUE TITLE
[5.x]: Cannot create more than one active user when trialling Craft Pro

### ISSUE THREAD

**Issue by amphibian** [craftcms/cms#14841]
### Description

After upgrading a local install of Craft to a Craft Pro Trial, I am unable to create users in a state other than "Inactive," with no way to activate them.

### Steps to reproduce

1. Install Craft.
2. Install Craft Pro as a trial.
3. Create a new user.

### Expected behavior

The new user is pending activation, and can be manually activated, have their password reset URL copied, etc.

### Actual behavior

The new user is inactive, and cannot be activated.

### Craft CMS version

5.0.4

### PHP version

8.2

### Installed plugins and versions

- Formie 3.0.0-beta.8

**Comment by olivierbon** [comment]
You should find those actions under the contextual menu at the top of your page.

 
![oli_8HiIhEJJ@2x](https://github.com/craftcms/cms/assets/146041/86298d5d-2bec-4cdd-8604-7806aa408daf)

**Comment by amphibian** [comment]
Ah, thank you! That is ... not very discoverable UI!

**Comment by thupsi** [comment]
> Ah, thank you! That is ... not very discoverable UI!

I agree. I like what they did with the "fancy breadcrumbs" but IMO some important actions got burried in that menu.

**Comment by jannisborgers** [comment]
Could this maybe find its way into the user index view? Until I found this thread (thanks @amphibian for asking and thanks @olivierbon for answering), I was sure that this was a bug from the RC to 5.0.0 migration, because I found no way to activate the inactive users I had just created.
