### ISSUE TITLE
[5.x]: Field Types Order in Dropdown not consistent

### ISSUE THREAD

**Issue by olsp** [craftcms/cms#14858]
### Description

When creating a new field, the order of the field types is alphabetically in the current language (German in the screenshot). When editing a field, the order is alphabetically in English.

<img width="215" alt="new-field" src="https://github.com/craftcms/cms/assets/1073442/68d0110d-b2be-4d4f-829e-ceb09198d103">
<img width="244" alt="edit-field" src="https://github.com/craftcms/cms/assets/1073442/520422a2-6328-4bb8-aa9e-b9349c96b6e8">

### Craft CMS version

5.0.5

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.0.6 is out now with that fix. Thanks again!
