### ISSUE TITLE
[5.x]: Field indicators are displayed twice in the field layout editor when the field label is hidden

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#14859]
### Description

In the field layout editor, when a field's label is hidden, the small icons (like the conditional field indicator, the thumbnail indicator etc) are displayed twice.

![image](https://github.com/craftcms/cms/assets/19857599/b0794693-518b-46e6-a8b3-ce6431b0d05f)

### Craft CMS version

5.0.5

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 5.0.6 is out now with a fix.
