### ISSUE TITLE
[5.x]: Site settings' "Entry URI Format" column in editable table changes font size on focus

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#14857]
### Description

For some reason, the "Entry URI Format" editable table column input uses a larger font size until it (or the "Template" column input in the same row) receives focus, at which point the font size is decreased.

I didn't manage to catch it on tape, but sometimes editable table column _widths_ actually change as the font size changes, which can feel a bit disorienting.

https://github.com/craftcms/cms/assets/298510/4d98c2d4-f6ab-4abd-b64b-b1fead4be46f

### Steps to reproduce

1. Open section's setting page, and scroll down to the "Site settings".
2. Click the "Entry URI Format" input and notice that the font changes.

### Craft CMS version

5.0.5

### Operating system and version

macOS 14.3.1, MS Edge 123.0.2420.97

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next v4 and v5 releases.

**Comment by brandonkelly** [comment]
Craft 4.8.11 and 5.0.6 are out with that fix. Thanks again!
