### ISSUE TITLE
Unit testing framework

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/cms#1485]

**Comment by YP28** [comment]
To be able to test properly, you need to be able to mock dependencies. And to be able to do that, quite some code has to be changed to implement dependency injection.

Is there a plan to implement this and make proper unit testing possible?

**Comment by dougstjohn** [comment]
Do you have more information on what we can expect in the 3.0 GA for this testing framework? We're adding unit, API, and end-to-end testing to several Craft plugins and client projects. What can we expect in this initial release?

**Comment by boboldehampsink** [comment]
@YP28 not necessarily. In Yii2 you can override components, and thus mock them.

**Comment by dougstjohn** [comment]
Will be interesting to see the impact of Yii2.1 also which changes routing, adds dependency injection, adds middleware, etc. Details here https://github.com/yiisoft/yii2/milestones/2.1.0

**Comment by boboldehampsink** [comment]
Here is a Craft 3 plugin that uses the Codeception testing framework and is able to mock services: https://github.com/nerds-and-company/schematic

**Comment by martinherweg** [comment]
Still no news on that? Would love to be able to develop modules or plugins test driven :)

**Comment by cmalven** [comment]
I'm very interested in using Craft as an application development framework, but the lack of an officially-supported story for testing plugins and modules makes it a tough sell.

**Comment by gtettelaar** [comment]
As of Craft [3.2 BETA-1](https://github.com/craftcms/cms/blob/3.2/CHANGELOG-v3.md#320-beta1---2019-06-04), there is now a formalized testing Framework for Craft. Based on Codeception with support for sites, modules and plugins in various testing styles.
