### ISSUE TITLE
[5.x]: Asset thumbnails distorted and blurry images in element cards

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#14866]
### Description

Asset thumbnails are not always keeping their aspect ratio and thus are sometimes distorted. Tested on Windows Chrome.

![image](https://github.com/craftcms/cms/assets/19857599/0e3da869-56ea-4c45-9ca8-2615b12cb21a)

![image](https://github.com/craftcms/cms/assets/19857599/c1b42d73-fe85-4b8d-b539-65a9233c98d9)

A simple solution would be to add `object-fit: contain;` to the `img` tag.

### Craft CMS version

5.0.5

### Installed plugins and versions

-

**Comment by thupsi** [comment]
Also just saw that on element cards the image is set to `object-fit: cover;`, which results in a blurry image if the original aspect ratio does not fit the given area. 

![image](https://github.com/craftcms/cms/assets/19857599/76925339-e5c5-48bf-9d59-0d68d7adf0f9)

A possible solution here would be to use a transform that is set to the exact aspect-ratio of the card image area.

**Comment by brandonkelly** [comment]
@brianjhanson The aspect ratio bug was caused by #14834.

The card view screenshot is expected. We want the image to fill the space. If the image is smaller than that space, it’s going to be a little blurry, regardless of whether the browser or a transform is upscaling it.

**Comment by thupsi** [comment]
It is expected if you don't control the area of the image in the card _or_ the size (width and height) of the image source. Since you control both, you can make them match and therefore avoid unnecessary scaling. Of course if the _original_ image is smaller, _then_ scaling is unavoidable. But that's not the case here.

**Comment by thupsi** [comment]
@brandonkelly To make the above comment more clear, I think in element cards the transform ratio should be 1:1 (set to crop), since that is the ratio of the rendered image area. 

This way:
- No wasted kb, what you download is what you render.
- No unnecessary scaling or blurriness, the transformed image fits the designated area in both axes, no matter its original ratio.

**Comment by brandonkelly** [comment]
Yeah sorry, was being a little thick yesterday. I assumed the source image was smaller to begin with.

We’ve fixed the aspect ratio bug for the next release (#14876), and the upscaling bug for Craft 5.1 as well (b122c625f4886ff91b310cdcea9004f4235047f3).

**Comment by brandonkelly** [comment]
5.0.6 is out with that aspect ratio fix.

**Comment by brandonkelly** [comment]
5.1 is out with the card view fix.
