### ISSUE TITLE
[4.x]: Regression in display of disabled item in Vue AdminTable

### ISSUE THREAD

**Issue by elivz** [craftcms/cms#14861]
### Description

[This commit](https://github.com/craftcms/cms/commit/97170c6a41a5395ef4df3498cd148030a6960d67) switched from checking for the _presence_ of a `status` attribute to checking for the coerced boolean value of that attribute. As a result, rows with `status: false` now display in bold without the empty/white status indicator. This issue is present throughout most of the tables in Commerce, which use that Vue component. It causes those disabled items to have a weird and confusing display. I haven't found any instances in Craft core where a status is set on a VueAdminTable.

<img width="443" alt="Screenshot 2024-04-25 at 12 08 26 PM" src="https://github.com/craftcms/cms/assets/62592/be958722-adc3-465b-b0dc-8e2c16b9be8e">

### Steps to reproduce

1. Create a disabled discount, sale, or shipping method in Craft Commerce
2. View the index page for that item type

### Expected behavior

The disabled item should display with normal font weight and an empty circle next to the name, indicating that it is disabled.

### Actual behavior

It is in bold font, with no indicator circle, and the left margin is misaligned.

### Craft CMS version

4.8.10

### PHP version

4.5.4

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 4.8.11 and 5.0.6 are out with that fix. Thanks again!

**Comment by elivz** [comment]
Looks great now. Thanks Brandon!
