### ISSUE TITLE
[5.0.5]: Matrix block becomes disabled after parent entry is saved

### ISSUE THREAD

**Issue by kylecotter** [craftcms/cms#14868]
### Description
When using a Matrix field with its own Entry URIs within a section, and where the available Entry Types for the Matrix field all have the Status field disabled, initially adding Matrix blocks will save them as enabled, but once you save the parent entry they are being used in, the matrix block becomes disabled on the first save.

### Steps to reproduce

1. Create a Matrix field
2. Create Entry Types for that Matrix field (in our case the Entry Types contained a nested Page Builder Matrix Field)
3. "Show the status field" is disabled for each entry type
4. On the matrix field settings, we use the following uri format `{owner.uri}/{type|kebab}`
5. Create a section/entry type to add this Matrix field to
6. Create a new entry in the section
7. Add a matrix block in our matrix field
8. Save the matrix block
9. You should see the UI show the block as enabled
10. Save the parent entry
11. The matrix block is now disabled

### Expected behavior
Saving of parent entries shouldn't affect the status of children 

### Actual behavior
Matrix blocks are being disabled.

### Craft CMS version

5.0.5

### PHP version

8.2.18

### Operating system and version

Linux 6.6.16-linuxkit

### Database type and version

MySQL 8.0.30

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.1-13)

### Installed plugins and versions

Amazon S3	2.2.1
Blitz	5.1.4
CKEditor	4.0.4
CP Field Inspect	2.0.1
Elements Panel	3.0.0
Expanded Singles	3.0.0-beta.2
Google Maps	5.0.2
Hyper	2.0.0-beta.8
Imager X	5.0.0
Many to Many	4.0.0-beta.2
Palette	5.1.0
Retcon	3.0.0
SEOMate	3.0.0-beta.6
Retour	5.0.0
Sprig	3.0.1
Timber	2.0.0-beta.2
Vite	5.0.0

**Comment by kylecotter** [comment]
Digging in to this a bit more, it seems there are entries (matrix blocks) in the `elements_sites` table for a given entry, but they're not showing up within the entry's matrix field.

So I think it's some type of validation that's disabling the entry because `{owner.uri}/{type|kebab}` ends up not generating a unique uri, because an entry for it already exists in the database despite not visually seeing it in the CP.

This tracks with some of our content editors saying content has just randomly disappeared on them.

**Comment by brandonkelly** [comment]
What view mode is your Matrix field set to?

**Comment by kylecotter** [comment]
Section -> Matrix with URIs (Cards) -> Content Builder Matrix (Cards)

**Comment by brandonkelly** [comment]
Thanks! I’m able to reproduce, but it is working as expected, because the entry isn’t passing live validation due to the duplicate URI.

**Comment by kylecotter** [comment]
> So I think it's some type of validation that's disabling the entry because {owner.uri}/{type|kebab} ends up not generating a unique uri, because an entry for it already exists in the database despite not visually seeing it in the CP.

Sorry, to clarify, in our case the URI should have validated as unique because there was only one block of that type added in the matrix field.

And the editor UI only ever showed that one block.

However, going into the database I found multiple entries of this matrix block type associated with the parent entry. Running garbage collection didn't help.

So, from what was actually in the DB, I get why validation failed, but a) the content editor didn't actually add multiple blocks of the same type so not sure what those entries were and b) the CP UI never showed the multiple block entries.

Will try and get some more concrete notes this week.
