### ISSUE TITLE
[4.x]: Querying for entries with `after` parameter is inclusive of the given date

### ISSUE THREAD

**Issue by pixleight** [craftcms/cms#14875]
### Description

Querying for an entry `after` a date returns an entry **on** that date.

While I'm not sure this is actually a "bug" since the docs describe this behavior as returning an entry _on or after_ the date (https://craftcms.com/docs/4.x/entries.html#after), but in the table showing possible values describes it differently as being _after_ the date:

![CleanShot 2024-04-26 at 14 04 24](https://github.com/craftcms/cms/assets/1278274/e6842164-c5b8-43aa-bb5f-2ebbb7aa3161)

Some examples of this using the GraphQL API:

![CleanShot 2024-04-26 at 13 36 33](https://github.com/craftcms/cms/assets/1278274/688ffe95-fd88-4dc8-ad60-51e92fef7a7e)

Incrementing the timestamp by 1 second returns the expected entry:

![CleanShot 2024-04-26 at 13 41 25](https://github.com/craftcms/cms/assets/1278274/526f8be1-4a97-43ce-87ce-b66836f42ab2)

### Steps to reproduce

1. Create some entries with varying `postDate`s
2. Query for those entries with the `after` parameter, using the `postDate` of one of those entries as the value

### Expected behavior

Similar to `before` returning results that are actually _**before**_ a given date, I think `after` would return results _**after**_ a date, rather than inclusive of the date.

### Actual behavior

Querying for entries `after` a date may return results _**on**_ that given date.

### Craft CMS version

4.5.12

### PHP version

8.3.4

### Operating system and version

Linux 5.4.0-1110-kvm

### Database type and version

MySQL 8.0.36

### Image driver and version

Imagick (ImageMagick 6.9.11-60)

### Installed plugins and versions

- Amazon S3 - 2.0.3
- CKEditor - 3.5.1
- CP Field Inspect - 1.4.4
- Environment Label - 4.0.3
- Expanded Singles - 2.0.5
- Feed Me - custom patch (based on 5.2.0)
- Formie - 2.0.36
- Hyper - 1.1.27
- Many to Many - 3.0.4
- MatrixMate - 2.1.3
- Navigation - 2.0.23
- Palette - 3.2.2
- Quick Field - 2.0.5
- SEO Redirects - 4.1.13
- UI Element fields - 2.0.3

**Comment by brandonkelly** [comment]
Thanks for pointing that out! It is intended to mean “on or after”. Fixed the example docs for the next release.
