### ISSUE TITLE
Allow support for interlaced images via Asset Transforms

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#1487]
The `Imagine` library that Craft uses supports creating interlaced images, which crucially results in progressive JPEGs, which are very important for optimal image loading on the web.

Adding support for it should be as simple as doing:

```
imgageInstance = new Imagine\Image;
imageInstance->interlace(VAL);
```

Where `VAL` is one of:

```
    const INTERLACE_NONE = 'none';
    const INTERLACE_LINE = 'line';
    const INTERLACE_PLANE = 'plane';
    const INTERLACE_PARTITION = 'partition';
```

(`line` is typically what you want)

If it's just a config option, that's fine, but exposing this in some way would be very useful.

**Comment by andris-sevcenko** [comment]
Ah, interlaced images. Some people love them, some people hate them.

Config option sounds like a solution everyone can agree on.

**Comment by khalwat** [comment]
Well, pretty much every performance testing tool for the web wants progressive JPEGs... because on low bandwidth connections, the image will appear a whole lot sooner.

Thank you for the config option. :)

**Comment by brandonkelly** [comment]
A general config setting seems too heavy-handed. I think making it a transform setting would make more sense.
