### ISSUE TITLE
[5.x]: Axios "CanceledError" error in entries select modal

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#14882]
### Description

In a multi-site install, if an Entries field is configured to use a single section for the "Sources" setting, the field's entry select modal will fire a barrage of uncaught Axios `CanceledError` exceptions, _when opened via the "Add an entry" button in a site where that section is disabled._

When this happens, the browser tab essentially freezes and has to be closed.

![CleanShot 2024-04-27 at 20 43 10@2x](https://github.com/craftcms/cms/assets/298510/84e19ac3-1180-42dd-a5c8-228eb3885fbb)

### Steps to reproduce

The bug can be reliably reproduced by having a single-source Entries field, and then clicking the field's "Add an entry" button in an active site that does not have that source enabled.
 
1. Have at least 2 sites, "Site A" and "Site B".
2. Create a section (e.g. "News"). Leave the section _disabled_ for "Site A".
4. Create an Entries field, and configure it to use the "News" section as its only source. All other settings can be left at their defaults (I had the "Show site menu" setting enabled, but it doesn't appear to matter).
5. Create another section (e.g. "Pages"), and add the Entries field to it.
6. Create a "Site A" entry in the "Pages" section, and click the "Add an entry" button for the entries field.

### Craft CMS version

5.0.5

### Installed plugins and versions

None

**Comment by i-just** [comment]
Hi, thanks for reporting and for the clear replication steps! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.0.6 is out now with that fix. Thanks again!
