### ISSUE TITLE
Expose the Imagine _instance in the EVENT_GENERATE_TRANSFORM

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#1488]
The events that are trigged via `EVENT_GENERATE_TRANSFORM` just gives you the transform, asset, and image.

Unfortunately the `image` in this case is either `craft\image\Raster` or `craft\image\Svg`

To be able to do some of the really interesting things that the `Imagine` library allows for, we'd need access to the `craft\base\Image` private variable `_instance` (perhaps via a `getInstance()` method?) so we can do things like interlace images, apply advanced filters, and so on.

If this was provided, all of the very cool effects that the Imager plugin provides would be possible to do via plugin, and more.

Otherwise, the things that can be done in the `EVENT_GENERATE_TRANSFORM` event are somewhat limited in scope.

**Comment by khalwat** [comment]
Referenced in the discussion here by @aelvin https://github.com/craftcms/cms/issues/845#issuecomment-277818238

**Comment by andris-sevcenko** [comment]
@khalwat what about SVG tranforms? Not dissing, just looking for suggestions :)

**Comment by brandonkelly** [comment]
Andrew said I can close this.

**Comment by khalwat** [comment]
So I hate to be all full of lament and such, but some people are now asking for things like a sharpen filter on scaled images. Which can't really be done through the Craft transform interface without access to the Imagine instance...

**Comment by bossanova808** [comment]
I would definitely like to see this added.

Control over transforms can really impact the visual quality of the resulting images substantially - in particular, the lack of sharpening of transforms routinely makes images look very soft (when starting with a big master and creating thee huge variety of transforms needed from that for a fullr responsive site).  

For product/commerce-y sites in particular, where looks = sales , this is a real shame.

We currently use Imager to do this (very effectively, thanks @aelvin!) - but it would be great if there was a more 'native' way to do it...and @khalwat's new addon looks pretty wonderful but without access to sharpening...it's not gonna fly for us.

**Comment by khalwat** [comment]
You're the best, @andris-sevcenko !
