### ISSUE TITLE
[5.x]:  Preview issue: using own entry's Entry ID to fetch information returns null when editing existing entry

### ISSUE THREAD

**Issue by fermincreative** [craftcms/cms#14895]
### Description
I have a sprig component that requires an Entry ID to be passed which is then used to fetch the current entry. This works fine when browsing the site and opening the preview when there are no changes. It also works fine when creating a new entry and previewing that - it breaks however as soon you have an already published entry and start making changes to that.  The preview pane does not seem to be able to retrieve the information from the new draft.  Note that this breaks regardless of whether Sprig is used or not. 

### Steps to reproduce

1. Create an entry and save it.
2. Use an include to pass the entryId, eg. ` {% include 'components/portfolio/index' with {'entryId': entry.id} %}`, then fetch the entry using said ID, e.g.  `{% set entryQuery = craft.entries.id(entryId) %}`  and fetching said query, e.g.  `{% set entry = entryQuery.one() %}`
3.  Make any changes to the entry and hit 'Preview'
4.  
### Expected behavior
CraftCMS preview window should work, just like it does in this case when previewing a new entry, or an entry that doesn't have any pending changes. 

### Actual behavior
Error: 'Impossible to access an attribute on a null variable' for whatever item is fetched first. 
![twigerror](https://github.com/craftcms/cms/assets/24222196/831ae760-851c-4ef6-a193-525d69f31a0d)

### Craft CMS version

5.0.5

### PHP version

8.2.15

### Operating system and version

Ubuntu 22.04

### Database type and version

MySQL 8

### Image driver and version

Imagick

### Installed plugins and versions

- Button Box
- CKEditor
- Field Manager
- Little Layout
- SEO
- Smith
- Sprig
- Super Table
- oEmbed
- SEOmatic

**Comment by brandonkelly** [comment]
Why not just reference the current entry using the provided `entry` variable?

**Comment by fermincreative** [comment]
That'd be preferable, but you cannot pass an entry variable into a sprig component, making this workaround necessary. See https://putyourlightson.com/plugins/sprig#component-variables .

**Comment by i-just** [comment]
It looks like someone already asked this question in the Sprig repository: https://github.com/putyourlightson/craft-sprig/issues/318 and the solution is to use `entry.canonicalId`.

Hope this helps!
