### ISSUE TITLE
[5.x]: Deselecting elements in element indexes is sluggish

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#14896]
### Description

It feels like there's some kind of minor UI performance issue when deselecting elements in Craft 5's element indexes (and element select modals).

I don't know if it's possible to tell from the screencast below, but in reality there's a very noticeable and consistent ~>0.5s delay from clicking a selected element, to the element actually appearing as deselected/selectable:

https://github.com/craftcms/cms/assets/298510/64c1b722-da89-4a01-a417-8302852960bd

*Selecting* elements is instant, and the UI in general feels very performant, which makes the slower deselect action all the more noticeable. 

I tested this on a few different browsers (including the latest Chrome and Edge) on a couple of different Macs (including an M1) and FWIW the behavior and performance seems pretty much the same everywhere.

Obviously this isn't the biggest problem in the world. Deselecting elements is a very common action though, so it'd be nice if it felt as spiffy as everything else 😊

### Steps to reproduce

1. Select an element in an element index or select modal
2. De-select the element

### Expected behavior

Deselecting elements should be instant.

### Actual behavior

The action of deselecting elements is noticeably slower than selecting elements, giving the impression that there's some kind of JS performance issue under the hood.

### Craft CMS version

5.0.5

### Operating system and version

macOS 14.3.1, Edge 124.0.2478.67

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
This is an intended delay, as it helps us rule out double-clicks.

**Comment by mmikkel** [comment]
Fair enough! And I'll live with it 🙂

...if you'll bear with me though, I'm not sure I understand how exactly the timeout is helpful? AFAIK, the only double-clickable things in element indexes (in core) are element pills, thumbs and cards, and double-clicking them (i.e. to open slideouts) will still end up deselecting the the selected element:

https://github.com/craftcms/cms/assets/298510/8488be09-c915-4cb4-b8d8-56b56ffcf89d

If the intent is to avoid selected elements being unintentionally deselected due to the element being double-clicked (i.e. to edit in a slideout), possibly that isn't working correctly. But regardless, potentially it'd be possible to prevent the deselection without a timeout by preventing event propagation in element pill/thumb/card components?

**Comment by brandonkelly** [comment]
I think it’s just more a casualty of abstraction, since we use the same selection library in other contexts where double-clicking is needed. I’ll reopen and look into whether we can explicitly avoid the delay when we know it’s not needed…

**Comment by mmikkel** [comment]
Cool. It's not a huge deal, just feels to me like that this little bit of lag in a commonly used/encountered UI action adds some unfortunate slowness to the UI that I think would probably be worthwhile to try and avoid, if possible 🙂

**Comment by brandonkelly** [comment]
Alright, removed the lag for Craft 5.2, except within element selection modals where double-clicking is a shortcut for selecting the element(s), which is why it was added in the first place (#13770).

**Comment by mmikkel** [comment]
> …within element selection modals where double-clicking is a shortcut for selecting the element(s)

Ah, of course! Nevertheless, great to have the delay removed elsewhere 👏 Thanks Brandon!

**Comment by brandonkelly** [comment]
Craft 5.2.0-beta.1 is out with that change.
