### ISSUE TITLE
[5.x]: Project Config Apply YAML Changes - Empty object

### ISSUE THREAD

**Issue by stephanedemotte** [craftcms/cms#14909]
### Description

Every time i make some changes on settings i've got this message `Your project config YAML files contain pending changes`
But the change is simple a empty object

### Steps to reproduce

Make change on section or entry types or fields etc...

### Expected behavior

No message

### Actual behavior

<img width="537" alt="Screenshot 2024-04-30 at 13 07 19" src="https://github.com/craftcms/cms/assets/2158130/21837f93-414c-4bf2-a29b-ed0b995f20f0">

<img width="536" alt="Screenshot 2024-04-30 at 13 02 49" src="https://github.com/craftcms/cms/assets/2158130/4b45e93f-efbd-4c74-afba-6ad7b331c3e7">

### Craft CMS version

5.0.6

### PHP version

8.3.3

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out! Similar behaviour has been reported before and tracked down to hidden folders in the `project/config` directory. As a starting point, could you please check if there are any hidden files/folders in your `project/config` directory, delete them if there are any, and check if it stops this behaviour?

**Comment by stephanedemotte** [comment]
<img width="759" alt="Screenshot 2024-05-02 at 06 07 28" src="https://github.com/craftcms/cms/assets/2158130/410a7db1-1d93-4e39-929f-a4f6bdeda63c">

I have removed `._0bd`, `._QOG` and `._wwL` and yes, no more messages

**Comment by i-just** [comment]
Great news, thanks for confirming!

I’ll close this now, but feel free to reach out if you run into any further problems.

**Comment by stephanedemotte** [comment]
@i-just i have not created the hidden folders, Craft generate hidden folder.

Sometime the hidden folder "re-appear" I think the bug is not resolved, if someone don't search on github to find this issues, he will keep this message forever. This bug should not exist...

**Comment by i-just** [comment]
@stephanedemotte Nothing in Craft is (intentionally) generating those files. More info can be found under #9617 (especially the last two comments) and #7323. I hope this helps!

**Comment by stephanedemotte** [comment]
@i-just yes but Craft generate this files anyway not intentionally but files are created...

**Comment by adrianjean** [comment]
I get these errors all the time on almost every craft project.
They go away if I rebuild the project config, but then return after a time, often as I am making changes to fields and such. 
The offending element is always empty. 

For me it was 
```
campaign {
  campaignTypes {
  }
}
```
