### ISSUE TITLE
[5.x]: UI and layout issues with cp header and sidebar

### ISSUE THREAD

**Issue by mlathrom** [craftcms/cms#14900]
### Description
I think the layout of the header and sidebar on control panel pages could be cleaner. There are also some spacing inconsistencies in at different breakpoints.

### Expected behavior
- Clean layout at all resolutions
- Skip to Entries button should remain in sidebar element
- Toolbar should always line up with main content

### Actual behavior
- "Skip to Entries" button is out of the sidebar on mobile
- Toolbar, action buttons, and show sidebar interface is a bit clunky in it's layout
- The toolbar doesn't line up with the main content in tablet resolution

#### Mobile Layout
Lots of vertical space used.

![mobile-layout](https://github.com/craftcms/cms/assets/373889/93d5a249-8f04-40ae-aad1-8460c93cb562)

#### Mobile Layout
Skip to entries button out of sidebar container.

![mobile](https://github.com/craftcms/cms/assets/373889/0deff251-9e92-4edd-951a-19e581b9ea52)

#### Tablet layout
Toolbar is not aligned with main content. Strange spacing.

![tablet](https://github.com/craftcms/cms/assets/373889/7be26e91-74ec-4538-8813-9e4b4241b5a1)

#### Desktop Layout
Odd spacing for Skip to Entries button

![desktop](https://github.com/craftcms/cms/assets/373889/1647bd13-b748-4374-9017-fced573f6aca)

### Craft CMS version

5.05

### PHP version

8.2

### Installed plugins and versions

-

**Comment by mlathrom** [comment]
@brianjhanson I've created a fix for this. Hope it helps.

#14901

**Comment by brandonkelly** [comment]
Craft 5.10.0-beta.1 is out with changes from #14901 and #14910. Thanks for the feedback and PR!
