### ISSUE TITLE
[5.x]: Matrix with a minimum of 1 and maximum of 1, blocks can be deleted

### ISSUE THREAD

**Issue by BAM-Dennis** [craftcms/cms#14904]
### Description

The block appears, but i am able to delete it

### Steps to reproduce

1. create a matrix field with a minimum of 1 block and maximum of 1 block
2. associate it to some entry
3. create a new entry of this kind
4. delete matrix block
5. dead end. i now can no longer add a new block nor can i save the entry. Only thing i can do is reload

### Expected behavior
if i can delete the block, i should be able to add a new one OR
i cannot delete it (compared to a static matrix field like in a supertable)

### Actual behavior
i can delete it and i can't add a new block

### Craft CMS version

5.05

### PHP version

8.2

### Operating system and version

linux

### Database type and version

pgsql

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
What view mode is your Matrix field set to?

**Comment by ttempleton** [comment]
I can reproduce this using inline blocks on 5.1.0.

![Screenshot 2024-05-01 at 10-48-00 (First draft)](https://github.com/craftcms/cms/assets/19421878/fa3f259f-df0d-4046-99f6-ba9942c9d4b7)
![Screenshot 2024-05-01 at 10-49-00 (First draft)](https://github.com/craftcms/cms/assets/19421878/89d90c7e-963e-4bcd-a096-dc287c292705)

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.1.1 is out with that fix. Thanks again!
