### ISSUE TITLE
[5.x]: Small tag styling issue

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#14916]
### Description
The content of tag element chips in tag fields is not vertically centered

![image](https://github.com/craftcms/cms/assets/19857599/f9f69996-0d14-4fb9-9cd7-642361c94311)

### Craft CMS version

5.1.0

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.1.1 is out with that fix. Thanks again!
