### ISSUE TITLE
[5.x]: "allowedGraphqlOrigins" option not working with String [] || Headless Craft

### ISSUE THREAD

**Issue by The-Dan-Main** [craftcms/cms#14917]
### Steps to reproduce

1. Newest Craft Version in Headless mode (graphql enabled)
2. Sveltekit as Frontend via GraphQl

### Expected behavior

/config/general.php
    ->allowedGraphqlOrigins(['*'])

This would allow all urls, within the string array and do not set the cors header if not mentioned within the array.

### Actual behavior
Since Craft 5, i get following error, as the CORS headers are not set properly:

Error: CORS error: No 'Access-Control-Allow-Origin' header is present on the requested resource at universal_fetch...

Values "null" and "false" are working as intended and the default is "null" as per documentation.

Either the support for " * " is not working or the function is not working in general. I could not test official URL's yet and only tested it locally yet.

### Craft CMS version

5.1.0

### PHP version

8.3

### Operating system and version

Debian 22 (plesk obsidian)

### Database type and version

MariaDB 10.5.23

### Image driver and version

-

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
That setting has never supported being set to `['*']`, and the code that references it hasn’t changed in Craft 5.

Both Craft 4 and 5 allow it to just be set to `null` (which it is by default), which will result in `Access-Control-Allow-Origin: *` being set on the response.
