### ISSUE TITLE
[5.x]: Very minor styling bug with author/user menu on entries

### ISSUE THREAD

**Issue by andrewhawkes** [craftcms/cms#14924]
### Description

Sorry, a bit of a nitpick...

When a username of an author is too long the menu button is overflowing the container:

See below:

<img width="384" alt="image" src="https://github.com/craftcms/cms/assets/4975742/8de9589d-cc09-47b4-b10e-c782bc3cedc2">

### Craft CMS version

5.1.0

### Installed plugins and versions

-

**Comment by brianjhanson** [comment]
Thanks for reporting! I've opened #14961 to address this.

**Comment by brandonkelly** [comment]
Craft 5.1.3 is out with a fix for this. Thanks again.
