### ISSUE TITLE
[4.x]: UnknownPropertyException when Upgrading from Craft 3 to 4

### ISSUE THREAD

**Issue by jamiematrix** [craftcms/cms#14926]
### Description

Updating a very early (3.0 I believe) Craft site to 4. The composer process went without an issue (with a few plugins in there to update).

When getting to `php craft migrate/all` I get the error:
`Exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: craft\models\Info::edition'`

Every `php craft` command produces this error.

I've tried reverting back to Craft 3 and trying again. Still the same outcome. At a guess I need to update to a later version of Craft 3 first?

### Steps to reproduce

1. Follow upgrade guide for Craft 3.x to 4.x. 
2. Get stuck on `php craft migrate/all`

### Expected behavior
Follow upgrade guide and have a smooth experience.

### Actual behavior
The opposite.

### Craft CMS version

4.9

### PHP version

8.3

### Operating system and version

Windows 10

### Database type and version

MySQL 5.7

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
> At a guess I need to update to a later version of Craft 3 first?

Yes – the first step in the [Craft 4 upgrade guide](https://craftcms.com/docs/4.x/upgrade.html) is to update to the latest version of Craft 3.
