### ISSUE TITLE
[4.x]: New entry button on entry selection modal is available for not supported sites.

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#14923]
### Description
New entry button on entry selection modal is available for not supported sites.

### Steps to reproduce

- Create a new section `section1` with `en` and `en2` as supported sites
- Create a new section `section2` with `en` as supported site
- Create an entry field with `section2` as source and add it to `section1` entry type

**Show the site menu for that entry field is not checked**
- Craft 4: When create a new `section1` entry for `en2` site, on selecting that entry field, there is new entry button that clicking on that throws an error.
- Craft 5: it seems handles this by redirecting user to supported site.

**Show the site menu for that entry field is checked**
- Craft 4: When create a new `section1` entry, on selecting that entry field, the new entry button is displayed even if `en2` is selected on site menu on modal and clicking on that throws an error.
- Craft 5: Changing site menu on modal to `en2` throws an error.

### Expected behavior
I guess the correct behavior is to hide create new entry button for not supported sites and not to list not supported sites on modal.

### Craft CMS version

4.9.0, 5.1.0

### PHP version

8.0.2, 8.2

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 4.9.2 and 5.1.2 are out with that fix. Thanks again!
