### ISSUE TITLE
[5.x]: Back button after clicking into assets sub folder takes you back to the previous page in the CMS not the previous assets folder

### ISSUE THREAD

**Issue by terryupton** [craftcms/cms#14936]
### Description
When clicking into Assets and then navigating into a subfolder, the uRL in the address bar changes to that sub folder e.g.
https://domain.com/cms/assets/files/datasheets 

However, if you then click the back button it takes you back to the previous page in the CMS, not the previous assets folder. its a bad UX AX and frustrating. 

The is not a 5.X exclusive bug, it affects other versions too. 

### Steps to reproduce

1. Click on Assets
2. Click onto an asset source with a sub folder
3. Click on the sub folder
4. Click the browser back button

### Expected behavior
1. Back button should take you back to the previous assets folder view (parent folder) 

### Actual behavior
1. The back button takes you back to the previous page viewed on the CMS.
E.G if I navigated to Assets from Utilities > System Report, the back button will take me back to https://domain.com/cms/utilities/system-report

### Craft CMS version

Craft Pro 5.1.1

### PHP version

8.2.18

### Operating system and version

Linux 5.15.0-101-generic

### Database type and version

MySQL 8.0.36

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

**Comment by thupsi** [comment]
There's a [discussion](https://github.com/craftcms/cms/discussions/12826) about this issue.
