### ISSUE TITLE
Asset preview keyboard shortcut not working on the Assets index page

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/cms#14943]
> @brandonkelly Is this also intended to work on the assets index page? Additionally, I'd like to make a feature request to allow keyboard navigation to the next/previous asset, similar to how you can do with Quicklook on a Mac.

_Originally posted by @carlcs in https://github.com/craftcms/cms/issues/14420#issuecomment-2095388960_

**Comment by brandonkelly** [comment]
@carlcs Looks like it’s working when you click on an asset to select it first, but not when you <kbd>tab</kbd> into an asset. Will fix.

**Comment by brandonkelly** [comment]
Fixed those (and a couple other preview modal-related bugs) for the next Craft 4 and 5 releases 🎉

**Comment by carlcs** [comment]
Oh wow, Brandon! Thanks, I can’t wait to update.

**Comment by brandonkelly** [comment]
Craft 4.9.2 and 5.1.2 are out with those fixes. Thanks for reporting!
