### ISSUE TITLE
should avoid using CRAFT_SITE if defined on Craft (re-)install

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1494]
### Description
I zeroed my database as somehow it was reporting one or more tables corrupt, and INNODB  s apparently unrepairable according to Navicat. This has never  happeed before, but possibly a result of a week's troubleshooting. 

On Craft attempting a new install, since this was the safest way esp. with an easy site setup afterwards, it bombed talking about the now-missing Sites table. 

After zeroing all in storage, thinking it was a cached template, I realized it was from CRAFT_SITE being defined in web/index.php (as 'default', as part of tracking down recent Sites issues). Which is probably not required or desired, but you probably want to defend against it.

### Steps to reproduce
- as above

### Additional info

PHP version	7.1.2-3+deb.sury.orgxenial+1
Database driver & version	MySQL 5.7.17-0ubuntu0.16.04.1
Image driver & version	GD 7.1.2-3+deb.sury.orgxenial+1
Craft edition & version	Craft Personal 3.0.0-beta.7
Yii version	2.0.11.2
Twig version	2.1.0
Guzzle version	6.2.1
Imagine version	0.7-dev
Plugins: none

**Comment by takobell** [comment]
Don't think I'm following... did you get a specific error?  What's `CLASS_PATH`?  It's not a PHP constant that Craft defines.

**Comment by narration-sd** [comment]
my goodness - fixed the title, which looks like a spell checker produced it. Maybe I wrote this from iPad or phone. i haven't touched a Java CLASSPATH in donkey's years. And no underscore either.

I can't quite figure what i was saying here either, probably more evidence of a late-night or bus-riding report, but the bailout of the install was real.

As I piece this back together, I suspect it was actually db config not found, due to the CRAFT_PATH being in there. But that doesn't quite fit. Let me look more into this.

**Comment by takobell** [comment]
Fair enough... going to go ahead and close, but just comment if you find anything else and I can re-open as needed.

**Comment by narration-sd** [comment]
Ok, I did make this come back, and this time since devMode was set, got a picture much as I expected from earlier mangled report, immediately on screen.

- have a site that works (this time my bare basic Composer project installed basis, used and with section only for Asset/Sites verifying)
- hive off the database sql, and remove all the tables
- insert this above the autoloader line in web/index.php

`define('CRAFT_SITE', 'default');`

- attempt to run website.url in the browser
- get a nice 'splode, per picture below
- note that the reason is, Craft is trying to use that CRAFT_SITE on a database table that wouldn't exist before it completed the install trajectory. 
- waaaayyy down in a quite deep stack trace, you can note that this is happening as Craft tries to render the install page. I now recall this from the original blow-up also. Memory is funny that way...
- solution then is probably to condition Sites not to act if Craft not fully installed. 
- justification if req'd (I keep remembering childhood A.A. Milne, or was that Kenneth Grahame; Shepard illustrations anyway) As per the title, I concern that others will do as I did, clear a db where they have been doing Sites on the site, and become unable to re-install. This would only occur after a db fault as I had, or in early stages of a project restart, but worth saving anxiety there, would think...if you do...

Ok, the pic, and done: Cheers as you know, Brad.

![site-splode](https://cloud.githubusercontent.com/assets/247945/24732906/f0a0412a-1a28-11e7-9359-44178a481f27.png)

**Comment by narration-sd** [comment]
Looks good, my man -- thanks!

**Comment by takobell** [comment]
Thank you!
