### ISSUE TITLE
[5.x]: Array Helper methods' documentation doesn't match behavior

### ISSUE THREAD

**Issue by elivz** [craftcms/cms#14944]
### Description

This is a relatively minor quibble, but wanted to point out that several Array Helper methods are documented as returning `null if $array isn’t an array, or is empty`. However the parameter is typed strictly as being an array so in fact PHP throws a TypeError if you pass anything other than an array.

https://github.com/craftcms/cms/blob/740d265868b1bbffceafb4bc21d4a21fa58c5576/src/helpers/ArrayHelper.php#L352-L385

This appears to be present in all v4 & v5 versions.

### Craft CMS version

4.0.0+

### PHP version

8.1

**Comment by brandonkelly** [comment]
Sorry, forgot to reply, but this was fixed in 4.9.2 and 5.1.2. Thanks for reporting!
