### ISSUE TITLE
Nested entry status dots are duplicated on save

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#14958]
### Description

Nested entries displaying element chips in their cards, have their status dots duplicated when they are saved:

https://github.com/craftcms/ckeditor/assets/298510/a9353c5e-3c27-40cb-b917-6db419873796

### Steps to reproduce

1. Create an entry type with a relational field (e.g. Entries). Check the _Show in element cards_ option for the related field. 
2. Create a CKEditor field, and add the entry type to it.
3. Create a nested entry using the entry type from step 1; make sure to add an element to the relational field.
4. Double-click the nested entry and save it from the slideout, a couple of times
5. Confirm that the nested entry card now has way too many status dots.

### Additional info

- Craft version: 5.1.1
- PHP version: 
- Database driver & version:
- Plugins & versions: CKEditor 4.0.4

**Comment by i-just** [comment]
Hi, thanks for reporting! As this also affects, e.g., a matrix field with an entries field showing in the card, I’m transferring it to the CMS repo.

**Comment by i-just** [comment]
A PR has been raised for this. Thanks again!

**Comment by brandonkelly** [comment]
Craft 5.1.3 is out with a fix for this. Thanks again.
