### ISSUE TITLE
[5.x]: Element select modals shows all site entries when switching to a site without any sources

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#14956]
### Description

It looks like the fix for https://github.com/craftcms/cms/issues/14923 might have introduced (or exposed?) a different bug:

In element select modals, when switching to a site that has no sources, the element index will become populated with (as far as I can tell) _every single entry in that site_, including nested entries.

In the screencast below, I have a section called "Pages" that is only enabled for the site "Craft 5", and an entries field that has "Pages" as its only source. In the entry select modal for that entries field, I switch the site from "Craft 5" to "Another site" (which doesn't have the "Pages" section enabled and hence, no sources to display entries from). At that point, Craft outputs all entries from that site.

https://github.com/craftcms/cms/assets/298510/e0a4e2ef-48af-45bf-ae65-ada22503c543

The above behaviour does not occur if the entry select modal has the site without sources active when it opens – it specifically happens when using the site menu to switch to a site without sources:

https://github.com/craftcms/cms/assets/298510/339bb1a6-358d-40f0-9e24-65eb6c3da02a

### Steps to reproduce

1. Create two sites, "Site A" and "Site B"
2. Create a section "Foo" that is only enabled for Site A
3. Create an entries field that has the "Foo" section as its only source. _Enable the "Show site menu" setting._
4. Add the entries field to a field layout and create an entry with that field layout, _with "Site A" active._
5. In that entry, click the "Add an entry" button in the entries field.
6. In the entry select modal that appears, switch the site from "Site A" to "Site B"

### Expected behavior

No entries should display for sites without any sources, which is the case in Craft 4.

(Ideally, I wish that element select modal site menus excluded sites without sources, but I'm aware that this has never been the case - maybe a FR 🙂).

### Actual behavior

When switching to a site without sources, the element select modal lists all entries from that site.

### Craft CMS version

5.1.2

### Installed plugins and versions

None

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for it. (BTW, it was not related to #14923.)

**Comment by brandonkelly** [comment]
Craft 5.1.3 is out with a fix for this. Thanks again.
