### ISSUE TITLE
[4.x]: Poor contrast on selected items in modal

### ISSUE THREAD

**Issue by CustomCodeIT** [craftcms/cms#14963]
### Description

When selecting entries, products etc. from a field that supports selecting multiple items, the UI shows which items have already been selected (good). However, it's almost impossible to read what the selected items are which makes reasoning about what you have and have not added to the list quite tedious.

### Steps to reproduce

1. Add an entry field to your layout
2. Select a few items
3. Check the modal and try reading what you selected

### Expected behavior

The contrast needs to be bumped up here while still making it clear that this item has been selected.
As you can see in the screenshot below, the "Section" and "Post Date" columns have a much more acceptable and readable contrast whereas the "Entry" column does not

### Actual behavior

<img width="725" alt="image" src="https://github.com/craftcms/cms/assets/66106520/d2b18023-585a-4cfd-849d-b1e778af2de6">

### Craft CMS version

4.9.1

### PHP version

8.3

### Operating system and version

MacOS

### Database type and version

MariaDB

### Installed plugins and versions

N/A

**Comment by brandonkelly** [comment]
Thanks for pointing that out. Fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 4.9.3 is out with that fix. Thanks again.
