### ISSUE TITLE
[3.x]: 

### ISSUE THREAD

**Issue by camelskyscraper** [craftcms/cms#14966]
### Description
Ack, don't know if this is actually a bug or my error (and I am posting in the wrong place), but here goes...
A custom Set Password form works normally, but a redirectInput value is not recognized in favor of the postLoginRedirect set in general config. Auto login after account activation is true, if that matters.

### Steps to reproduce

1. set a `postLoginRedirect` value in `config/general.php`
2. set `autoLoginAfterAccountActivation` to `true` in `config/general.php`
3. set a `redirectInput` on a Set Password form

### Expected behavior

After submitting the Set Password form, go to the `redirectInput` value.

### Actual behavior

After submitting the Set Password form, goes to the `postLoginRedirect` value.

### Craft CMS version

3.9.13

### PHP version

8.1.28

### Operating system and version

Linux 3.10.0-1160.108.1.el7.x86_64

### Database type and version

MySQL 8.0.37

### Image driver and version

GD 8.1.28

### Installed plugins and versions

-

**Comment by camelskyscraper** [comment]
My redirect field on the Set Password form for "register/43297" looks like `<input type="hidden" name="redirect" value="8a6a279b9a241f5aef18af512470d0936ca9b09ea50daf1680a8168bfda598d0register/43297">`

**Comment by i-just** [comment]
Hi, thanks for getting in touch! Not factoring in the redirect input is the expected behaviour in this case. With `autoLoginAfterAccountActivation` set to `true`, after successfully setting the password, the user who doesn’t have access to the Control Panel will be sent to either `activateAccountSuccessPath` or `setPasswordSuccessPath` (depending on whether they have just activated their account by setting the password or if was already active and they’ve changed their password).

I hope this helps!

I’ll close this now, but feel free to reach out if you run into any further issues.

**Comment by camelskyscraper** [comment]
Thanks for that detail!
I'm trying to think of a workaround for what we want to accomplish: we want to feed in a variable that will have the viewer end up on a different page depending on where they initiated the "reset password" process. So far we have a variable going through the set password email and back to the set password page, which is where we were trying to use `redirectInput`. Is there some other Craft-y way we can get them to that variable page, given that the URL is known on the set password page?

**Comment by camelskyscraper** [comment]
Digging into the UsersController I see the `actionSetPassword` function. I was hoping maybe we could set an additional User attribute through the Set Password form, but it doesn't look like that is possible. Is that right? I was thinking maybe we could have `setPasswordSuccessPath` go to a template that then redirects the User to an appropriate page based on if they have an attribute set or not. I figure that conditional redirecting must be possible _somehow_ but I don't know how we can do that if the User isn't logged in yet. As mentioned before, I have the variable value passed all the way through to the Set Password form but am missing the last piece to the puzzle. Can you help point me in a direction?

**Comment by i-just** [comment]
The `actionSetPassword()` method is used for both account activation and to reset forgotten password, so what exactly happens during `actionSetPassword` depends on that.

> I was hoping maybe we could set an additional User attribute through the Set Password form, but it doesn’t look like that is possible.

You’re right, that’s not possible via the form, but the `Users` service (https://github.com/craftcms/cms/blob/3.x/src/services/Users.php) has `EVENT_BEFORE_ACTIVATE_USER` and `EVENT_AFTER_ACTIVATE_USER` events which might help you do what you’re after. Those events are only fired when activating a user, not when resetting a forgotten password. You can discover more events here: https://craftcms.com/docs/3.x/extend/events.html#event-code-generator

You could set both `activateAccountSuccessPath` and `setPasswordSuccessPath` to the same template. If you have `autoLoginAfterAccountActivation`, then the user will be logged in when they reach that page, and you can choose to redirect them based on their characteristic.

Or, you could consider setting a session flash or a cookie when they land on the set password page. After they’ve successfully set/changed their password, you could read the session flash or cookie value and act upon it.
 
For example, you could set the flash value on the set password form page: `{% do craft.app.session.setFlash('mySetPasswordData', 'my set password value') %}` and then once the user sets their password and is redirected to the page you’ve specified, you can read that flash via `craft.app.session.getFlash('mySetPasswordData')` and proceed depending on the value.


Also, those two issues are somewhat related and might help you choose the best way forward:
https://github.com/craftcms/cms/issues/13051
https://github.com/craftcms/cms/issues/12561

I hope this helps!

**Comment by camelskyscraper** [comment]
That is fantastic, thank you! I went with the flash value — a concept I hadn't ever used before. It seems to be working as desired and we'll see how it does when it gets more widely used. Thank you for all the super helpful detail!
