### ISSUE TITLE
[5.x]: Matrix Blocks - As Cards - Disappear/Removed when the block is disabled and the parent entry is saved

### ISSUE THREAD

**Issue by terryupton** [craftcms/cms#14973]
### Description
I have a matrix field that I have set to present as cards rather than inline as I feel the UI is cleaner and easier for the content author to manage and use. 

<img width="2120" alt="Screenshot 2024-05-10 at 17 01 00" src="https://github.com/craftcms/cms/assets/5698596/7b1e332c-58f8-4a77-86b7-cf494485bdbb">

<img width="2120" alt="Screenshot 2024-05-10 at 17 01 37" src="https://github.com/craftcms/cms/assets/5698596/404d1d12-7eee-44f6-9010-858597fb0b31">

The problem I am facing is there is no way to disable the matrix blocks like you can if they are inline. 
Instead you have to go into the entry (slide-out) and disable the block from there (set status to disabled). 
this works fine. Although I would like to suggest the ability to disable this like the in-line method with a checkbox etc.

<img width="2120" alt="Screenshot 2024-05-10 at 17 09 39" src="https://github.com/craftcms/cms/assets/5698596/a50f36bb-e5e7-45d1-beb6-62c42f47ba20">
<img width="1384" alt="Screenshot 2024-05-10 at 17 10 06" src="https://github.com/craftcms/cms/assets/5698596/eb03fd36-dc4a-49fd-8cdd-b2e8acacfff0">

The problem arises is when you save the page, the disabled block is then removed, with no way to access it to re-enable it.

<img width="1394" alt="Screenshot 2024-05-10 at 17 10 25" src="https://github.com/craftcms/cms/assets/5698596/d256cf90-ee2f-4352-850b-283fc01bc3be">

I assume the content is still in the system, but I can not find a way to re-access this and this is certainly going to be a huge challenge for the average content author. 

### Steps to reproduce

1. Edit a block in the matrix.
2. Change the status of the block to disabled.
3. The block shows as disabled. 
4. Resave the page
5. The block is removed. 

### Expected behavior

1. Edit a block in the matrix.
2. Change the status of the block to disabled.
3. The block shows as disabled. 
4. Resave the page
6. The block remains in the matrix builder and continues to show as disabled, so it can be removed or re-enabled. 

### Actual behavior

1. Edit a block in the matrix.
2. Change the status of the block to disabled.
3. The block shows as disabled. 
4. Resave the page
5. The block is removed. 

### Craft CMS version

Craft Pro 5.1.1

### PHP version

8.2.15

### Operating system and version

Linux 6.7.11-orbstack-00143-ge6b82e26cd22

### Database type and version

MySQL 8.0.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR to keep showing the cards for disabled nested entries in matrix fields.

**Comment by brandonkelly** [comment]
Craft 5.1.3 is out with a fix for this. Thanks again.
