### ISSUE TITLE
[5.x]: Missing CP route for `myaccount/permissions` in Team edition

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/cms#14976]
### Description

When using the Team edition, URLs to your own user element/account work (`admin/myaccount`), but `admin/myaccount/permissions` results in a 404.

### Steps to reproduce

1. Install Craft;
2. Begin a Team edition trial;
3. Navigate to Users &rarr; [Your User];
4. Click **Permissions** in the sidebar;

This line covers normal user routes like `admin/users/1/permissions`, but not the special `myaccount` path:

https://github.com/craftcms/cms/blob/6a13d279272e81fec9cd919aba58c497a2febd78/src/config/cproutes/team.php#L8

The base routes presumably don't include this static/non-parameterized route because Solo edition doesn't use the Permissions tab at all!

### Craft CMS version

5.1.2 (Team)

### PHP version

8.2

**Comment by i-just** [comment]
Thanks August! I raised a PR for this.

**Comment by brandonkelly** [comment]
Fixed in 5.1.3!
