### ISSUE TITLE
[5.x]: Command key no longer works as expected when selecting elements in modals

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#14979]
### Description

In Craft 4's element select modals, the Shift and Command (⌘) keys both work similarly to their behavior when selecting files in macOS' Finder: Holding down Shift when clicking will select _sequences_ of elements, and holding down Cmd will _add_ or _remove_ that specific element to/from the selection.

In Craft 5, the Shift key still works as expected when selecting elements in select modals. 
However, the Cmd key does not, in two ways:

1. Cmd-clicking an element that is not selected, will select that element, but all previously selected elements will be deselected. The expected behavior is that other selected elements are retained, and the Cmd-clicked element added to the existing selection.  
2. Cmd+clicking _an already selected_ element will not unselect that element. If there are multiple elements selected, all elements _except_ the Cmd+clicked one will be deselected. The expected behavior is that the Cmd+clicked element will be deselected, and any other selected elements retained.

_Essentially, in Craft 5 selecting/deselecting with the intention of adding or removing them from a selection of elements work as expected when the Cmd key is **not** pressed, which feels counter-intuitive, and the inverse of how Mac and Windows file explorers work._

(...this is obviously written from a Mac user's point of view, I have not tested this on Windows, and I forget what the Windows equivalent to the ⌘ key is 🙃)

### Steps to reproduce

1. Open up an element select modal. Select a sequence of elements by holding down Shift and clicking a few of them.
2. Hold down the Command key and try to select additional elements, or to deselect specific elements from the selection.

### Expected behavior

Holding down the Command key when clicking elements should ideally function similarly to how it works when clicking files in macOS Finder and Windows, and how it works in Craft 5's element indexes and select modals when the Command key is _not_ pressed.

### Actual behavior

Craft 5's element modals seem to ignore the Command key when elements are clicked.

### Craft CMS version

5.1.2

### Installed plugins and versions

-

**Comment by thupsi** [comment]
Partially related [discussion](https://github.com/craftcms/cms/discussions/14379)

**Comment by brandonkelly** [comment]
This is working as expected, since element selection modals now have checkboxes in Craft 5, so they now use the same checkbox selection behavior Craft uses everywhere else (see https://github.com/craftcms/cms/discussions/14379#discussioncomment-9435507).

**Comment by mmikkel** [comment]
Thanks for clarifying that, Brandon. It'll take some muscle memory rewiring, but I guess that's a fair trade-off for consistency.
