### ISSUE TITLE
[5.x]: "Allow thumbsview chip content to span whole width" doesn't work in asset fields

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#14993]
### Description
https://github.com/craftcms/cms/pull/14972 does not work when displaying thumbnails in asset fields:

![image](https://github.com/craftcms/cms/assets/19857599/79ea953b-2303-43fe-b243-0db3eafebf7b)

### Craft CMS version

5.1.3

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR to adjust this.

**Comment by brandonkelly** [comment]
Craft 5.1.4 is out with a fix for this. Thanks again!
