### ISSUE TITLE
[5.x]: Infinite element loading borked

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#14992]
### Description

Video probably describes it best

https://github.com/craftcms/cms/assets/25124/a8516c99-130c-4e19-a954-bb77b54484da

### Expected behavior

Elements should load when scrolling the main panel

### Actual behavior

They don't until you scroll the viewport which then triggers continuous loading

### Craft CMS version

Main: d6a31171e6178af5a20de62786899cdee220d244

### PHP version

8.3

### Operating system and version

ddev

### Installed plugins and versions

-

**Comment by bfopma** [comment]
Seconding this issue! We are experiencing the same on 5.1.3.

**Comment by brandonkelly** [comment]
Thanks for reporting! Craft 5.1.4 is out with a fix for this.
