### ISSUE TITLE
[4.x]: Column not found: 1054 Unknown column 'kcu.CONSTRAINT_NAME' in 'on clause'

### ISSUE THREAD

**Issue by DarioDiGiacomo** [craftcms/cms#15009]
### Description
I wanted to work in Craft CMS v5. When I looked into the documentation for upgrading to v5, I was a bit scared cus I don't trust myself with such important tasks without any supervision. My next plan was to start a new project with v5 installed. I connected the same DB as i had in the v4. The v5 didn't work so i deleted it from VS code and i wanted to work further in the v4 project. When I reloaded the project i got this error.

### Steps to reproduce

1. look at the description i would say

### Craft CMS version

4

### PHP version

8.0.2

### Operating system and version

Windows 11

### Database type and version

sql?

### Image driver and version

I don't know

### Installed plugins and versions

-

**Comment by tommysvr** [comment]
Hi @DarioDiGiacomo, what are you using for your local development environment? From that error, it sounds like there might be an issue with that setup. When you setup the Craft 5 site, did you run the database migrations?

**Comment by DarioDiGiacomo** [comment]
Hi @tommysvr I use wampserver. The problem is that the error i get is on the first project, the project i was already working on. The second project i started was a v5 the only thing i did was use the same db.

**Comment by tommysvr** [comment]
Thanks for the reply. If you restore a Craft 4 backup from before you setup the Craft 5 site, does that work?

**Comment by DarioDiGiacomo** [comment]
I didn't make a back up on my own so I hope it does it itself. Where could i find it?

**Comment by tommysvr** [comment]
Are you able to take a new backup from your production site? Otherwise, you might be able to find a backup under `storage/backups` inside your Craft files.

**Comment by DarioDiGiacomo** [comment]
In my storage folder ins't a folder named backups..

I do have a composer-backup?

**Comment by tommysvr** [comment]
Do you have a production version of the site? Can you take a backup from there?

If you'd like to email support@craftcms.com, that might be a better place to support you with this one.
