### ISSUE TITLE
[5.x]: CP: CSS: CKEditor Field Settings: Entry Types: ".chip-content" title wrapping

### ISSUE THREAD

**Issue by adrianjean** [craftcms/cms#15000]
### Description
This is verrry low priority... but a small css tweak.
Not sure if this is a CraftCMS or CK Editor Plugin issue.

In the settings for a CK Editor field, under "Entry Types" the entry type "chip" titles wrap:

---
<img width="435" alt="Screenshot 2024-05-15 at 11 07 52 AM" src="https://github.com/craftcms/cms/assets/3161182/bdcfbda3-33b8-4704-ad78-f2f393508935">

---

Looks like maybe a `white-space: nowrap;`  in `main.scss` might help: 

```
.chip:has(.thumb) .chip-content {
    white-space: nowrap;
}
```

That would clean up the look of the chips:

---
<img width="442" alt="Screenshot 2024-05-15 at 11 08 07 AM" src="https://github.com/craftcms/cms/assets/3161182/8e1347c4-40fa-44f9-8aeb-d2386573e88e">

---

### Craft CMS version

5.1.3 (Solo)

### PHP version

8.3.6

### Operating system and version

Linux 5.15.0

### Database type and version

MySQL 8.0.30

### Image driver and version

GD 8.3.6

### Installed plugins and versions

- CKEditor 4.0.5

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.1.5 is out with that fix. Thanks again!
