### ISSUE TITLE
[4.x]: Change in ElementQuery::count effecting `EVENT_BEFORE_PREPARE` events

### ISSUE THREAD

**Issue by myleshyson** [craftcms/cms#15001]
### Description
We noticed that after updating to Craft 4.9, one of our queries wasn't running properly. The logic for this particular query depends on the `EntryQuery::EVENT_BEFORE_PREPARE` event. In particular, in depended on the `orderBy` property to be null for for count queries to run properly.

Now however, because of [this](https://github.com/craftcms/cms/commit/0ff4796abd9d073d8c3d15a934e381f90cb403fc) change, the `orderBy` property is not being nulled like it was before with `yiii\db\Query::queryScaler` method.

I'm not sure if this was on purpose? Either way would it be possible to either:
a) keep the queryScaler logic from `yiii\db\Query::queryScaler` for scalar queries (count, min, max, etc) so that things run like they did before the change OR
b) add a property to ElementQuery, something like `queryMethod`, so that events can add that logic back if the query is a scalar query? 

### Craft CMS version

Craft 4.9.0

### PHP version

8.2

**Comment by yannkost** [comment]
I have also noticed that the .count() function does not return the right value for some queries. 

```
{% set searchQuery = craft.entries({ type: availableEntryTypes}).search(query).orderBy('score').limit(5) %}
```
This sample code does return the limit of 5 and not the number of the entries.

**Comment by yannkost** [comment]
Just checked and without the `orderBy('score')` the function call returns the correct number.

**Comment by i-just** [comment]
@myleshyson, in your case, the `EntryQuery::EVENT_BEFORE_PREPARE` used to rely on the `$event->sender->orderBy` returning `null`, but since 4.9, it’s returning an empty string.

@yannkost, in your case, it’s the combination of `search`, `limit` and `orderBy('score')`. 

I raised a draft PR, and we’ll discuss this internally.

**Comment by brandonkelly** [comment]
Craft 4.9.5 and 5.1.5 are out with a fix that covers both of these issues. Thanks for reporting!

**Comment by lindseydiloreto** [comment]
This fix seems to have broken proximity searches for both the [Google Maps](https://github.com/doublesecretagency/craft-googlemaps/issues/111) and [Maps](https://github.com/ethercreative/simplemap/issues/391) plugins.

I've been digging around through the plugins and Craft itself, but can't figure out exactly:
- What benefit did these changes provide?
- How should our proximity search plugins be adjusted accordingly?

Do you have any recommendations?

**Comment by brandonkelly** [comment]
@lindseydiloreto Can you write into support@craftcms.com with Composer files and a database backup for a site that demonstrates the issue?

**Comment by lindseydiloreto** [comment]
@brandonkelly Certainly, I'll send it over. Thanks!

**Comment by amici-infotech** [comment]
We are using Maps plugin in multiple projects and it seems to be broken after both craft 4 and 5 upgrades.

**Comment by brandonkelly** [comment]
Craft 4.10.2 and 5.2.2 are out with a fix for Google Maps and Maps. Thanks for reporting @lindseydiloreto!

**Comment by lindseydiloreto** [comment]
Sweet, no problem! Thanks for getting it sorted out so quickly! 🍺
