### ISSUE TITLE
[4.x]: Disabled Matrix Blocks Unclickable

### ISSUE THREAD

**Issue by mightyfineyall** [craftcms/cms#15002]
### Description

Updating to 4.9.3 causes disabled matrix blocks to be unclickable. Confirmed by updating granularly via the CLI, it only occurred in 4.9.3. Seems to be related to https://github.com/craftcms/cms/pull/13897

### Steps to reproduce

1. Update to 4.9.3
2. Disable matrix block

### Expected behavior
Disabled matrix blocks should be clickable

### Actual behavior
Disabled matrix blocks are unclickable

### Craft CMS version

4.9.3

### PHP version

8.2.12

### Operating system and version

Linux 4.15.0-213-generic

### Database type and version

MySQL 5.7.42

### Image driver and version

GD 8.2.12

### Installed plugins and versions

Agent	5.0.0
Button Box	4.2.4
Colour Swatches	4.4.0
Contact Form	3.1.0
Contact Form Extensions	4.2.2
Hyper	1.1.29
Navigation	2.0.27
Read-only Field	2.0.1
Redactor	3.0.4
SEOmatic	4.0.48
SuperSort	4.0.0
Super Table	3.0.14
Typed link field	2.1.5

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by darylknight** [comment]
Also running into this. You also can't click the cog wheel to re-enable it.

**Comment by brandonkelly** [comment]
Craft 4.9.4 is out with a fix for this. Thanks again!

**Comment by jaydensmith** [comment]
@brandonkelly this bug still seems to affect variants on Craft Commerce.

**Comment by brandonkelly** [comment]
@jaydensmith Thanks! Commerce 4.6.1 is out with a fix.
