### ISSUE TITLE
Asset field 'Target Site' feels mis-set by default, and otherwise fails in entertaining ways

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1501]
### Description

There are serious problems with understanding this label and its choices, detailed in updated #1499.

The  primary fault to be expressed here, which generated now-withdrawn #1498, would be that the setting for 'Target Site' on a fresh Asset field defaults to 'Same as Source'. This fails in two ways:

- you actually see the non-transformed Asset coming through from the default site, if addressed, rather than including the addressed Site's handle in the  url as expected for  'Same as Source'

- a tranform of the image, however, faults out as its url _will_ include the Site's handle, pointing then to where there are probably not assets save in special cases.

Apart from the semantics discussed i #1499, I think you don't want to default to having Assets read from the home folder of each separate Site, as they likely exist only on the default site. 

And, if  a particular Site is chosen as basis, then  it isn't pointed to at present for the non-transformed image, which is in error, no?

What should you default the choice to? One might think the default site, but that changes, doesn't it, if the order of Sites does. See #1499 for a better suggestion.

As noted below, there are real problems getting a change in 'Target Site' to be actually recognized and shown -- should this be improved to avoid support issues, especially with the mostly-unwary?

### Steps to reproduce

1. Usual test page with asset image, transformed version, and any debug of urls and/or translatable text you like to help keep track.
2. Leave the default setting for an Asset Field's 'Target Site' to 'Same as Source'
3. Try the page on the default site, and note you get both image and tranformed correctly
4. Try the page on a non-default site, and  note:
- You get the primary image, which you shouldn't, because you don't have the resource on your non-default site, do you.  Note its url addresses teh default site incorrectly.
- You don't get the transformed image, because its url is pointing to the non-default site root, where there is no resource.

N.b. and felt as additional fault:  Trying out the transforms part of this fault  with changes in 'Target Site' setting on the Field can be, actually, quite trying... 

You have to do a sequence of operations to get any change to show. I believe by now that this is as followd, hopefully to be improved:
- change the 'Target Site'setting and save the Field definition.
- resave at least the Entry using the asset (only one?????? if you have many????)
- Utilities clear Caches
- Utilities (re-) index Assets
- at least on Chrome, also force full reload

That second step is what can be referred to as 'a honey', if true. I don't think it is always necessary, but sometimes seems to be, possibly specifically when changing from 'Same as Source' to a specific Site. I have a feeling that if any of this sequence is true, it may have to do with after-Submit Tasks and/or their event causing execution (seen as timing), but that is unproven intuition only.

### Additional info

PHP version	7.1.2-3+deb.sury.orgxenial+1
Database driver & version	MySQL 5.7.17-0ubuntu0.16.04.1
Image driver & version	GD 7.1.2-3+deb.sury.orgxenial+1
Craft edition & version	Craft Personal 3.0.0-beta.7
Yii version	2.0.11.2
Twig version	2.1.0
Guzzle version	6.2.1
Imagine version	0.7-dev
Plugins: none

**Comment by brandonkelly** [comment]
This should be fixed in Beta 7.
