### ISSUE TITLE
A fix likely needed as well as early doc-ing: how to properly set up a Home Page

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1502]
### Description
Kind of fundamental, isn't it. But also quite different from previous  Crafts, and likely to bite unless you help the unwary. There's also a coding/ui error, so I'm reporting this here, as it doesn't only have to do with communication and doc.

Doing Home Page setup  what is apparently the 'right' way makes things smooth as ever with Craft, and actually is better sense as well as safer than the previous pattern.

What the doc needs to say, available now:
- setting up Home Pages is different
- you indicate a Home Page by leaving the url field _blank_ in the Section definition. (n.b. coding fault -- the idea to do this is at present hidden, as you default home-page into the url field/s)
- if the Section has Site alternates, do the same for each Site's url field
- note that the template field has 'home-page/_entry' as default. This is surely a good idea for Single Home Pages, as it causes the 'entry' Twig variable to be set for you. So create your conceivedhome page _entry,html template in folder home-page, rather than at the top of the templates folder, as it was in Craft 2.
- [fill in what you actually think here] If the home page is fundamentally a listing page of some kind, then you will want rather to change the template field/s to home-page/index, and provide that template.
- [if you like this idea] However, in many cases it may be cleaner and more flexible to make the Home Page a Single with its _entry template, and provide any listing of Channels or Structures explicitly via Twig.

### Steps to reproduce

1. - 
2.

### Additional info

PHP version	7.1.2-3+deb.sury.orgxenial+1
Database driver & version	MySQL 5.7.17-0ubuntu0.16.04.1
Image driver & version	GD 7.1.2-3+deb.sury.orgxenial+1
Craft edition & version	Craft Personal 3.0.0-beta.7
Yii version	2.0.11.2
Twig version	2.1.0
Guzzle version	6.2.1
Imagine version	0.7-dev
Plugins: none

**Comment by brandonkelly** [comment]
UI bug should be fixed in Beta 8. Suggestions to clarify how homepages work already covered by #1455.
