### ISSUE TITLE
[5.x]: Alt Text Field Does Not Expand With Content

### ISSUE THREAD

**Issue by theAdhocracy** [craftcms/cms#15026]
### Description
Regular Plain Text fields all auto-expand as you type into them, ensuring that content isn't hidden from view or behind a scrollbar. The new Alternative Text field appears to be locked at two/three rows, and does not expand beyond that, making content harder to read.

### Steps to reproduce

1. Create any Asset with the Alternative Text field enabled
2. Type into the box until you exceed the existing height.
3. A vertical scroll bar will appear; text area does not expand.

### Expected behavior

Text area to expand to fit the content, in the same way that Plain Text fields do.

### Actual behavior

![image](https://github.com/craftcms/cms/assets/7009462/9fea9028-3b49-4c0e-a6b7-d39e2661f158)

### Craft CMS version

5.1.4

### PHP version

8.2

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 4.9.5 and 5.1.5 are out with a fix for this. Thanks again!
