### ISSUE TITLE
[5.x]: Fields / labels wrapping in inline editable mode

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#15040]
### Description

When doing inline editing in an element index there is some unexpected wrapping:

![image](https://github.com/craftcms/cms/assets/19857599/e4cdf39f-9a3a-4579-90d4-1051f9eefa58)

### Craft CMS version

Craft CMS 5.1.4

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR to adjust this a bit.

**Comment by brandonkelly** [comment]
Craft 5.1.5 is out with that fix. Thanks again!

**Comment by thupsi** [comment]
@i-just Thanks for the quick fix, however I still get some wrapping in a number field, with a prefix of `€`.

![image](https://github.com/craftcms/cms/assets/19857599/7985fab1-4f87-4417-b710-455aa7d2b299)

**Comment by i-just** [comment]
Hi @thupsi, I’m not able to replicate that. I assume you tried clearing caches? Which browser and OS are you seeing this on?

**Comment by thupsi** [comment]
Aah, sorry, I had temporarily rolled back to `5.1.4` due to https://github.com/craftcms/cms/issues/15065. All fixed now!

**Comment by i-just** [comment]
No worries! Glad to hear it's all working as expected :)
