### ISSUE TITLE
[5.1.4]: Sticky scrollbar stops working when switching between sources

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#15047]
### Description
The new [sticky scrollbar](https://github.com/craftcms/cms/pull/15010) has a bug when switching between sources, where it works only on the first source where it appears.

### Steps to reproduce

1. Go to an element index and switch to a source where the sticky scrollbar is displayed.
2. Switch to another source.

### Expected behavior

The scrollbar either disappears, or is updated and attached to the new source.

### Actual behavior

The scrolllbar does not update according to the current source, and:
- Does not control (scroll) the newly selected source.
- Stays visible even when not needed.

### Craft CMS version

5.1.4

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed in Craft 5.1.5.
