### ISSUE TITLE
[5.x]: Nested element chip title turns white on card focus/select

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#15044]
### Description

If an element chip is displayed in a card that sits inside an inline-editable Matrix field (phew!), the title/link color for the chip turns white on a light gray background when the card is selected, which looks like a bug and makes the chip title pretty much unreadable:

https://github.com/craftcms/cms/assets/298510/b71db791-9023-4eff-a0ce-d28c872b2ab0

### Steps to reproduce

1. Create a Matrix field with the "As inline-editable blocks" view mode.
2. Create an Entries field using the "Cards" view mode
3. Add an entry type to the field that includes the Entries field. Check the "Show in element cards" field layout setting for the Entries field.
4. Create a nested Matrix entry and add an entry to the Entries field. Then, click the card to select it.

### Craft CMS version

5.1.4

### Operating system and version

macOS 14.3.1, MS Edge 124.0.2478.80

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Fixed in 5.1.5! Thanks.
