### ISSUE TITLE
Structure parent collapse arrow duplicate entries in the popup view.

### ISSUE THREAD

**Issue by juliencharette** [craftcms/cms#1505]
### Description
When selecting a structure entry parent, clicking on the "collapse" arrows on the left appends a new item to the view.

![structure parent select bug](https://cloud.githubusercontent.com/assets/2778687/23866269/afb09f4e-07ee-11e7-9c0b-bd160c1bd6f6.png)

### Steps to reproduce

1. When creating a new structure entry, click on "Parent"
2. Click on an arrow to collapse a section.

### Additional info

Running on latest Laravel Valet.

- Craft version:  2.6.2967
- PHP version: 7.0.9
- Database driver & version: mysqlnd 5.0.12-dev - 20150407
- Plugins & versions:

a&m nav 1.8.0
Button Box 1.3.2
Solspace Calendar 1.8.3
Control Panel Nav 1.7.6
Dump 0.3.0
Elixir 1.0.7
Field Manager 1.5.3
Freeform 1.4.1
Link It 2.3.4
Neo 1.4.1
Reasons 1.0.8
Redirects 1.0.19
Select2 1.0.1
SEOmatic 1.1.43
Simple Map 1.3.0
Simple Text 1.1
Stringy 1.0.0
Super Table 1.0.3
Tools 1.10.0
Workflow 0.9.4

**Comment by brandonkelly** [comment]
Hey @juliencharette, unfortunately I’m unable to reproduce this locally. Can you please send in a support request to support@craftcms.com and include a database backup (or just send in a ticket from your Dashboard’s Get Help widget)? Please reference this issue (`#1505`) and point us to exactly which section and Entries field you’re seeing this bug in. Thanks!

**Comment by juliencharette** [comment]
Sure, I can also send you a quick screencast of the issue if it helps?

**Comment by takobell** [comment]
@juliencharette couldn't hurt!
