### ISSUE TITLE
[5.x]: Not possible to select Entry as type in Selectable Entries Condition

### ISSUE THREAD

**Issue by thomascoppein** [craftcms/cms#15058]
### Description
When adding conditions to Entries Field there is an option to add a Related To condition. 
The placeholder of this when selecting is Entry ID while the selected value in the dropdown is Asset.

### Steps to reproduce

1. Add new field
2. Select Field Type Entries
3. Add a Related To condition

### Expected behavior
I would expect that it is possible to select Entry as type in the dropdown.

### Actual behavior
![Screenshot 2024-05-23 at 11 48 12](https://github.com/craftcms/cms/assets/58168425/85f3f03e-d78e-41cc-bfa0-346fdfbc1288)

### Craft CMS version

5.1.4

### PHP version

8.2

### Operating system and version

macOS Sonoma 14.2.1

### Database type and version

mysql

### Installed plugins and versions

- CKeditor
- Sherlock
- SEOMatic
- Retour
- Field Manager
- Feed Me

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.1.6 is out with a fix for this. Thanks again!
