### ISSUE TITLE
[5.x]: GraphQL Introspection schema tripled in size

### ISSUE THREAD

**Issue by cornedor** [craftcms/cms#15068]
### Description

This headless website already had a schema of 11MB, that took ~2 sec to generate. While not ideal, this works fine for its usecase. However, after upgrading to CraftCMS 5 the size more than tripled to 38MB, and now takes more than 8 seconds to generate. I've also had to increase the PHP memory limit in order for it to finish.

While I do not know how the inner workings of an introspection schema work, it looks like it has a lot of duplicates. I searched for a field in the schema, that is only present in a single entry, and I found 1100 results. In the screenshot below you can also see the density of the results by looking at the sidebar. Only in the bottom there is a small part where the field name is not found.

<img width="1340" alt="image" src="https://github.com/craftcms/cms/assets/570297/8a2017c9-bbfb-457b-afaa-87cb59bfe0c7">

### Steps to reproduce

1. In a CraftCMS 4 site, open GraphiQL with the network tab open, and lookup the introspection call
2. Upgrade to CraftCMS 5, and repeat step 1.

### Expected behavior

Introspection schema is a reasonable size.

### Actual behavior

Exceeded memory limits and very large introspection schema

### Craft CMS version

5.1.6

### PHP version

8.2.19

### Operating system and version

Linux 3.10.0-1160.24.1.el7.x86_64

### Database type and version

MySQL 8.0.36-28

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- Feed Me 6.0.1
- Redactor 4.0.0
- Redactor Anchors 1.5.0
- SEO v5.0.0-rc2
- Super Table 4.0.0
- Typed link field devedis/craft-linkfield
- Webhooks 3.1.0

**Comment by thomasjonas** [comment]
We are having similar issues. Did you manage to find a solution for this @cornedor? Or at least a way to improve the situation?

**Comment by cornedor** [comment]
No, sadly not. Trying to merge entries only increased the schema size. It works just about well enough for us, but our gateway has to work hard starting up.

**Comment by thomasjonas** [comment]
Thanks for replying!  Ah, that's a pity :( I hope GraphQL will get some love soon. For us requests are also quite slow. Way slower than getting the same data via a REST request. But I think that's more related to [this discussion](https://github.com/craftcms/cms/discussions/8968)

**Comment by brandonkelly** [comment]
Spent some time today looking into this, and managed to significantly reduce the schema size for Craft 5.6 by pruning out custom field arguments for entry queries wherever they’re clearly not needed. (#16326)

**Comment by cornedor** [comment]
@brandonkelly i’ve tested this today, and indeed reduced my schema by ~8MB. Thanks for your work on this issue!

But it is still ~30MB, which is still very large and hard to work with. I already switched to Apollo Router, but this still takes a long time to boot. We use Apollo to combine CraftCMS with other services like Magento. There still seems to be a lot of duplication in the schema. Coincidentally I was planning this week to analyse the schema, but didn’t got to it. I will try to do that soon and find out what is duplicated.

This issue is better, but not resolved imho.

**Comment by brandonkelly** [comment]
Yeah, understand, but there’s not much more that can be done to significantly reduce the size at this point without introducing breaking changes to the API. The remaining places where all fields are being pulled in could be used by existing queries.

**Comment by brandonkelly** [comment]
Just found another opportunity to reduce the schema size, for all but the Full Schema: 20b1be753130eacd6ea998e91be185862c4e4ca1

**Comment by brandonkelly** [comment]
Craft 5.6.0 is out with those changes 🚀

**Comment by cornedor** [comment]
thanks!

**Comment by thomasjonas** [comment]
@cornedor Just out of curiosity, did you see any improvements with the release of Craft 5.6?
