### ISSUE TITLE
[5.x]: HTML IDs should be allowed to begin with a number

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#15066]
### Description

The `craft\helpers\Html::id()` function was recently updated to strip out numbers at the beginning as a follow-up to #13943

The justification was that HTML IDs aren't allowed to begin with numbers. However, this was only the case in HTML 4. In HTML 5, [there is no such restriction](https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute).

We're using this function to generate unique IDs for sections in our page builder matrix field. Those look like `123-section-name`, where `123` is the entries' (previously matrix block's) ID and `section-name` is the headline. This string is truncated to a specific character length, so to ensure the entry ID is always part of the section ID, it needs to be at the start.

### Steps to reproduce

1. Call `craft\helpers\Html::id('123-custom-string')`

### Expected behavior

2. The function should not strip out numbers at the beginning, as there is no reason for doing so to be standard-compliant.

### Actual behavior

The function unexpectedly strips out numbers at the beginning.

### Craft CMS version

5.1.6

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Doh, you’re right. Not sure how I missed that I was looking at the HTML4 spec.

Fixed for the next release.

**Comment by MoritzLost** [comment]
@brandonkelly Thanks Brandon!

**Comment by brandonkelly** [comment]
Craft 5.1.8 is out with that fix.

**Comment by AugustMiller** [comment]
Just a heads up that while HTML5 allows numerals at the beginning of `id` attributes, [CSS identifiers do not](https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier):

```twig
{% set id = '123-custom-string' | id %}

<div id="{{ id }}">Hello, world!</div>

{% css %}
  /* This block won't be applied to our div: */
  #{{ id }} {
    color: red;
  }
{% endcss %}
```
