### ISSUE TITLE
[5.x]: Native attribute don't show up in the field layout editor when a tab is deleted

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#15064]
### Description

In the field layout editor for any element type, deleting a tab with some fields in it returns those fields to the list of fields on the right (if they were single-instance fields to begin with). But this _doesn't_ happen for native attributes. If I delete a tab with a native attribute in it, the attribute is gone from the list and can't be added until the page is reloaded.

### Steps to reproduce

1. Open the field layout editor for an asset volume.
2. Create a new tab and drag the native `alt` attribute into it.
3. Delete the tab.

### Expected behavior

Native properties should appear in the list when it's removed from the field layout editor by removing the containing tab.

### Craft CMS version

5.1.6

### PHP version

8.2

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.1.8 is out with that fix. Thanks again!
