### ISSUE TITLE
[5.x] New user workflow feels broken

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/cms#15079]
IMO, the UX when creating new users from the CP feels pretty broken on Craft 5 and the fact that those activation actions are a bit hidden away in that breadcrumb disclosure menu is only part of the problem.

I think the biggest issue is that the profile info and permissions have been moved into dedicated edit pages (along with addresses). Since changes in these edit pages isn't persisted between pageloads, the new user has to be saved (or "created") after entering info in each one. 

Compared to the tabbed interface in previous versions of Craft, this implementation makes the previously straight-forward _enter name and email, assign permissions, send activation email_ workflow a lot more complicated.

Crucially, if the author isn't a power user and clicks the primary Create/Save button instead of Cmd+S (or the "Create and continue editing" action), _they will be redirected back to the user index after each of those saves_, and have to track down the new user in the index to continue "creating" it. At this point, it's not unlikely that the state of the new user is somewhat unclear to the author, and it's also not guaranteed that the user is even included in the specific index source the author is redirected back to. This can be the experience even more confusing.

Finally, after saving the user 2 or 3 times, the author has to remember to send an activation email, and where that action is found – which I agree is probably not in the most intuitive spot 🙂

**I do think the new UI works well enough for editing existing users**, but hopefully the flow for creating new users specifically, can be improved.

Adding auto-save capabilities to the user edit pages, as well as making the activation actions more easily discoverable – or, have them available _in some form_ right inside the editing view when creating new users, similarly to the "Send an activation email now" checkbox in Craft 4 – would probably help a lot.

_Originally posted by @mmikkel in https://github.com/craftcms/cms/discussions/14913#discussioncomment-9549457_

**Comment by robzor** [comment]
I was just about to come here to post this. I created a user account for someone else at the agency and I couldn't for the life of me find the Impersonate/Password Reset URL etc links. When it comes to 'slide out cards' I feel like they should be the same info as when you click 'into' the entry. 

E.G.

![CleanShot 2024-06-06 at 10  42 51](https://github.com/craftcms/cms/assets/704032/740582ac-dffa-4758-8b82-e8c08883c617)

**Comment by brandonkelly** [comment]
@robzor That’s what #14913 is pointing out, which has been resolved for 5.2 via #15070 :)

**Comment by brandonkelly** [comment]
This is now resolved for Craft 5.3: #15079

**Comment by mmikkel** [comment]
#15356 is a huge improvement, thanks a lot Brandon!
