### ISSUE TITLE
[5.x]: upgrading from 4.9.5 to 5 with ckeditor 3.8.3: requirements could not be resolved

### ISSUE THREAD

**Issue by masiorama** [craftcms/cms#15073]
### Description
Cannot upgrade to craft 5 following the official instruction due to requirements not met.

### Steps to reproduce

1. Upgrade to latest v4 version (4.9.5)
2. Upgrade to laster ckeditor version (3.8.3)

### Actual behavior
![Screenshot 2024-05-26 104604](https://github.com/craftcms/cms/assets/731916/d9f2ac21-dfee-40ef-837e-694a27f0193f)

### Craft CMS version

4.9.5

### PHP version

8.2

### Operating system and version

wsl2

### Database type and version

mysql 8.0

### Installed plugins and versions

- ckeditor 3.8.3 (recently migrated from redactor)

**Comment by brandonkelly** [comment]
CKEditor 3 isn’t compatible with Craft 5, but CKEditor 4 is. Change your `craftcms/ckeditor` requirement in `composer.json` to `^4.0.0` and try again.

If you have other plugins, they might need to be updated as well. See the “Craft 5 Upgrade” utility in your Craft 4 install – it will list each of the installed plugins and their latest Craft 5-compatible version (if they have one).

**Comment by masiorama** [comment]
Hi @brandonkelly thank you very much for the support, I already followed the docs but somehow I was missing that step. I mean, once seeing the craft panel section that listed the plugins ready for migration I assumed plugins were _already_ at the correct version, but didn't match with the version installed. Once I got that I managed to proceed.

I have to stress a thing, though: I tested the upgrade on a dev env, and all was ok, but when I replicated on production env there was an issue with migrations which didn't let me proceed (I had to restore db backup something like 10 times of try-error-repeat). In detail, the issue was with this two migrations:

- vendor/craftcms/commerce/src/migrations/m240308_133451_tidy_shipping_categories.php
- vendor/craftcms/commerce/src/migrations/m240313_131445_tidy_shipping_methods.php

To make `php craft up` works properly I had to invert rows `$this->addForeignKey(...` and `$this->alterColumn(...` in both those migrations, because there was an irreversible error. Once edited, I was able to successfull migrate.

Why the issue was only on prod environment? Maybe some differences in mysql server (some different constraints)? Questions I got no answers to, but I hope my workaround doesn't mean I introduced any more issues. 
This is why I decided to report this, I bet you can point me to right direction.

Hope this makes sense somehow, and if necessary I can properly open an issue to better investigate the matter.

**Comment by brandonkelly** [comment]
@masiorama Any chance you can share a production database backup, from before those migrations were run? If so, please send to support@craftcms.com along with your `composer.json` and `composer.lock` files, and we’ll see if we can reproduce + fix.

**Comment by masiorama** [comment]
@brandonkelly done, thanks!
