### ISSUE TITLE
Removing many relations takes too many clicks

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/cms#15078]
One other small issue I noticed which feels like a downgrade from craft 4 is removing assets/entries from and asset or entry field. Its now a two click process to open the menu and click remove where as it used to just be a single click cross...this is pretty annoying when you have 30 assets or so in a gallery and need to remove them all...maybe there is a better way!?
<img width="339" alt="screenshot_1464" src="https://github.com/craftcms/cms/assets/25520763/8f90f5a3-04b2-46ce-abcc-6b70c6b68a72">

_Originally posted by @splendidrob in https://github.com/craftcms/cms/discussions/14913#discussioncomment-9539245_

**Comment by brandonkelly** [comment]
Just resolved this for Craft 5.2. Going forward, the “Remove” element action will remove all selected elements, if the target element itself is selected.


https://github.com/craftcms/cms/assets/47792/f8b022b6-f149-4466-a72c-58d9b758d717

**Comment by splendidrob** [comment]
This is awesome!! Thanks so much 😍

**Comment by brandonkelly** [comment]
Craft 5.2.0 is out now 🎉
