### ISSUE TITLE
[5.x]: Fix `Typed property craft\base\FieldLayoutComponent::$elementType must not be accessed before initialization` error with Kint and element queries

### ISSUE THREAD

**Issue by engram-design** [craftcms/cms#15074]
### What happened?

Refer to https://github.com/verbb/kint/issues/8 but since Craft 5, the plugin cannot dump `ElementQuery` objects anymore. This is due to an error: `Typed property craft\base\FieldLayoutComponent::$elementType must not be accessed before initialization`.

To reproduce this, add an Entries field to an Entry, then use Kint to output the **ElementQuery** (not an element collection or single element): `{{ d(craft.entries.id(123).one().entriesField) }}`

Disregarding the Kint factor here, I feel like this might be a Craft issue.

Taking a deep-dive into things, this seems to be due to the `craft\fieldlayoutelements\CustomField` (our Entries field) doesn't have an `elementType` associated with it yet. It's also during this investigation that I've found when [settings elements](https://github.com/craftcms/cms/blob/9d48deb548e0e7ec3aff78c7a9b4cc3bfe1c9092/src/models/FieldLayoutTab.php#L272) on a `FieldLayoutTab` that it's own `elementType` isn't set.

I'm not _110% sure_, but shouldn't the `elementType` for the `FieldLayoutTab` and resulting `CustomField` objects be inherited from the `FieldLayout::type` property? The element type that the field layout is for?

```diff
public function setElements(array $elements): void
{
    $fieldsService = Craft::$app->getFields();
    $pluginsService = Craft::$app->getPlugins();
    $this->_elements = [];

+    // Set the element type based on the field layout's element type
+    $this->elementType = $this->layout->type;
+
    foreach ($elements as $layoutElement) {
        if (is_array($layoutElement)) {
            try {
+               // Ensure that layout elements know which element type this is for
+               $layoutElement['elementType'] = $this->elementType;
                $layoutElement = $fieldsService->createLayoutElement($layoutElement);
```

Which seems to fix my issue. I didn't do a PR, purely because I'm not really sure if this is right, expected behaviour or otherwise.

### Craft CMS version

5.1.7

### PHP version

8.2.0

### Operating system and version

MacOS 14.1

### Database type and version

MySQL 8

### Installed plugins and versions

- Kint 4

**Comment by brandonkelly** [comment]
This is definitely a Kint bug. Replacing `d()` with `dump()` works fine, and shows the `elementType` property is set as expected for the relational query:

![The output of a dump() function on a relational field’s element query](https://github.com/craftcms/cms/assets/47792/23b748dc-e497-4f14-9200-21d11c04f0ea)

To be extra sure, I installed Kint and set a breakpoint in the `d()` handler, and `elementType` is definitely set at the time the query is passed to the function:

![PhpStorm screenshot showing that the element query’s elementType property is set when the `d()` function is first called](https://github.com/craftcms/cms/assets/47792/cf7875f3-907a-4021-9de3-173b7449276d)

The field layout/tab/element’s `elementType` property has nothing to do with the element query; that is identifying the element type the field layout was created for. The element query’s `elementType` property is the element type the relational field’s element query is meant to fetch (e.g. `craft\elements\Asset` if it’s an Assets field).

**Comment by engram-design** [comment]
So the `elementType` not being set is actually on the custom field's `layoutElement` inside the element query, not on the element query itself - which you've shown is set correctly. It's hard to show in a single screenshot without it being massive, but you can check in the tree:

![CleanShot 2024-05-28 at 09 32 19@2x](https://github.com/craftcms/cms/assets/1221575/3071dac6-9d91-44e5-b676-fb32a2da3b64)

That's me just calling `{% dd craft.entries.id(123).one().entries %}` in a template.

It's the `eagerLoadSourceElement`, the `entries` field (my Entries custom field) and the field's `layoutElement`

I'm keenly aware that this is probably a "my problem" sort of issue, as `dump()` and event the similar `s()` (in Kint) function works correctly. It's clearly something to do with how Kint treats objects.

**Comment by brandonkelly** [comment]
Ah ok, sorry, got confused. I just set that property to `null` by default, which fixes that error. However now the page is timing out, so guessing there’s an infinite recursion bug or something. I’ll leave that to you :)

**Comment by engram-design** [comment]
Thanks for that, yeah probably my issue to figure out now. It's likely all to do with the [kint-twig](https://github.com/kint-php/kint-twig) package just being stupid, but that's my problem now 😄

**Comment by brandonkelly** [comment]
Craft 5.1.8 is out with that fix.
