### ISSUE TITLE
[5.x]: Entry type names include section name in conditionals builder Selectize input

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#15075]
### Description

Entry type names appearing in conditional builders are prefixed with the name of the section (or, _one of the sections_) they have been added to.

This doesn't make sense on Craft 5, considering entry types have been decoupled from sections (and have unique names), and it's especially confusing in cases where a single entry type has been added to multiple sections.

The issue appears to affect conditional builders in both entry index filters and field layout designer slideouts:

![CleanShot 2024-05-27 at 15 07 14](https://github.com/craftcms/cms/assets/298510/ab794924-c789-4aac-8317-2c53a4cd6dfe)

![CleanShot 2024-05-27 at 15 05 31](https://github.com/craftcms/cms/assets/298510/c02c731c-1e38-441d-aa96-9ee5241470af)

### Steps to reproduce

1.

### Expected behavior

Entry type names should display in conditional builders without the name of any associated section prefixed.

### Actual behavior

Conditional builder Selectize fields prefixes entry type names with (one of) the section(s) that entry type has been added to.

### Craft CMS version

5.1.7

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Doh! Thanks, fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 5.1.8 is out with that fix. Thanks again!
