### ISSUE TITLE
[5.x]: "Author cannot be blank" in entry after saving

### ISSUE THREAD

**Issue by modelesque** [craftcms/cms#15082]
### Description

Today I updated to Craft 5 from v4 and everything went smoothly. I changed some data in an entry and saved it, but a validation error appeared: `Author cannot be blank.` (The error message is also a hyperlink that doesn't go anywhere btw) 

I'm the only user in the system. There doesn't seem to be a place in the entry to edit the author, and I didn't see anything in the new entrytypes settings page.

### Steps to reproduce

1. Create an entry in a Craft 4 project and save it with you as the author.
2. Update to Craft 5 as per the instructions.
3. Revisit the entry and save it with some info.

### Expected behavior

My user account should already be the author of the entry, so this validation error shouldn't appear.

### Actual behavior

This validation error appears: `Author cannot be blank.`

### Craft CMS version

Craft Solo 5.1.7

### PHP version

8.2.15

### Operating system and version

Linux 6.7.12-orbstack-00201-g2ddb8f197a46

### Database type and version

MySQL 8.0.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Weird. Any chance you can send us a database backup and your Composer files? If so, please send them to support@craftcms.com, and point out an entry you’re seeing this on.

**Comment by modelesque** [comment]
Hi @brandonkelly I sent the files you requested.

**Comment by brandonkelly** [comment]
Craft 5.1.8 is out with a fix for this. Thanks for reporting!
