### ISSUE TITLE
[5.x]: 

### ISSUE THREAD

**Issue by yannkost** [craftcms/cms#15086]
### Description
As some plugins are not maintained anymore, we would like to link to a local repo where we can "simulate" the compatibility to craft-5 in the composer.json of the local repo. (And then testing if there is breaking beheaviour etc..) But even when linking to a copy of a plugin folder, where the composer.json has been updated, the "Upgrade to Craft-5" utility does show "not ready" in the status column. 

How can we simulate the compatibility to Craft-5 for a plugin, that's no longer maintained? Are there some specific tests that are made in the background that determine if a plugin is ready for craft-5 except the composer.json? (In another project, I managed to simulate this with the composer.json, but it was for another plugin)

PhpStan did not return an error for the plugin in question.

### Steps to reproduce

1. Update the path of a outdated plugin to use a local folder by declaring it of type path and creating the symlink with composer update

In the main composer.json
```
....
 "repositories": {
        "read-only": {
            "type": "path",
            "url": "plugins/read-only"
        },
...
```

In the composer.json of the plugin

```
...
 "require": {
        "craftcms/cms": "^4.0.0|^5.0.0"
    },
...
```

`ddev composer update`

### Expected behavior

The "Update to craft-5" utility shows the update button

### Actual behavior

The plugin is shown as "Not ready" in the update utility.

### Craft CMS version

4.9.5

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch! Information on whether a plugin is compatible with Craft 5 comes from the Plugin Store API. That being said, if you have your own versions of those plugins, you can perform the upgrade by following the [upgrade guide](https://craftcms.com/docs/5.x/upgrade.html) and adjusting your `composer.json` file accordingly.

I hope this helps!
