### ISSUE TITLE
[5.x]: Can't Add Asset Sub-Directories in Arc browser (Windows)

### ISSUE THREAD

**Issue by christopherhealey** [craftcms/cms#15084]
### Description
Can not create a sub-directory for assets using Arc on windows. Works as expected in chrome. Appears the Alert window used for some things like this doesn't work in Arc.

### Steps to reproduce

1. Open the Arc browser on windows
2. Navigate to Assets
3. Attempt to create a sub-directory

### Expected behavior
Modal appears to allow naming of sub-directory

### Actual behavior
Browser window freezes, must be refreshed to do anything again.

### Craft CMS version

5.1.7

### PHP version

8.2

### Operating system and version

Windows 11

### Database type and version

Postgres

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
We’re able to reproduce this, but it’s clearly an Arc/Windows bug, and nothing we can do about it. Simply entering `prompt('foo')` in the JS console has the same effect – no prompt is shown, and the browser freezes up.

**Comment by brandonkelly** [comment]
We couldn’t find an official bug report for it, but found https://www.reddit.com/r/ArcBrowser/comments/1d0bkkv/prompt_boxes_not_showing_up/ documenting the same bug.

I’ve reported it via their [contact form](https://resources.arc.net/hc/en-us/requests/new).
