### ISSUE TITLE
[4.x]: `Element::EVENT_DEFINE_ADDITIONAL_BUTTONS` not working for `User` elements

### ISSUE THREAD

**Issue by olivierbon** [craftcms/cms#15095]
### Description

The event is never triggered on user edit pages only. Works fine for other element types.

### Craft CMS version

4.9.5

### PHP version

8.2

### Installed plugins and versions

-

**Comment by i-just** [comment]
Thanks Oli! I raised a PR for this.

**Comment by brandonkelly** [comment]
Fixed in 4.9.6!
