### ISSUE TITLE
[5.x]: Ability to update slugs in inline-editable matrix entries

### ISSUE THREAD

**Issue by jannisborgers** [craftcms/cms#15092]
### Description
Using matrix fields, the slugs of it’s entries follow the same logic that entries in sections use: The slug is only created once. In the entry types, I checked „Show the slug field“, but the field does not show up when I choose „As inline-editable blocks“ as the matrix field’s view mode.

For most of the entry types in my matrix field, I’m using an object template to determine the title, which in turn creates the slug. I’m using this slug as an `id` attribute for each block, so that blocks on the page are linkable. However, without a way to update the slugs, their value persist even when the displayed title changes.

### Steps to reproduce
1. Add a matrix field, set view mode to "As inline-editable blocks"
2. Add an entry type, leave "Show the slug field" lightswitch on
3. Add an entry to the matrix field, notice there is no slug field
4. Output the slug in the template
5. Change the title of the entry and re-save

### Expected behavior
a) Maybe: outputted slug should be updated if not showing the slug field is intentional
b) Otherwise: authors should be able to see and update the slug field

### Actual behavior
Outputted slug stays the same and there is no way to change it.

### Craft CMS version

5.0.5

### PHP version

8.3.7

### Operating system and version

Linux 5.15.0-107-generic

### Database type and version

MariaDB 10.6.16

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

–

**Comment by brandonkelly** [comment]
This is working as expected, consistent with section entries. Slugs don’t ever get regenerated unless the Slug field value is cleared out.

Inline-editable block view doesn’t show the slug field inline, but it’s still accessible if you go into the nested entry’s full edit page via the “Open in a new tab” action.

<img src="https://github.com/craftcms/cms/assets/47792/4f46c4cc-c590-4804-b896-57243722d0ef" width="294" height="339" alt="An inline-editable Matrix block’s action menu, with the “Open in a new tab” option highlighted">

**Comment by jannisborgers** [comment]
Hi Brandon,

thanks for the quick reply. Indeed, I hadn’t seen the Open in new Tab function.

That being said, I still find the solution unintuitive when using the inline-editable view mode. It’s not that the authors have to leave the editing flow, but more that the entry type has a „Show the Slug field“ setting that only works as expected in full entry views.

**Comment by brandonkelly** [comment]
Typically slugs are only needed for content that has its own URI. If your nested Matrix entries are getting their own URIs, it would probably make more sense to your authors if you switched your Matrix field to the Cards or Element Index view mode, no? Then the nested entries would be edited within slideouts, which seems more appropriate for content that is going to have its own front-end page. (And slideouts do include all meta fields, including Slug.)

**Comment by jannisborgers** [comment]
You're right. The reason I use the slugs is that they are perfect as id attributes on the content block and I can avoid another field for all entry types that specifically sets those.

I will instead use title with ascii and kebab filters like described here: https://github.com/craftcms/cms/issues/5369

**Comment by brandonkelly** [comment]
Ah ok. Alternatively you could add a module that clears out the slug before your Matrix entries get validated, so they get regenerated each time.

```php
use craft\elements\Entry;
use yii\base\Event;
use yii\base\ModelEvent;

Event::on(Entry::class, Entry::EVENT_BEFORE_VALIDATE, function(ModelEvent $event) {
    /** @var Entry $entry */
    $entry = $event->sender;
    // Always regenerate the slug for Matrix entries
    if ($entry->getField()?->handle === 'myMatrixField') {
        $entry->slug = '';
    }
});
```

**Comment by jannisborgers** [comment]
That's what I'll do, thanks Brandon!
