### ISSUE TITLE
[5.x]: Redirection after editing nested elements in a new tab/window

### ISSUE THREAD

**Issue by mattias78** [craftcms/cms#15101]
### Description

Editing and hitting save on a Matrix entry from within a Global returns the user to all Entries, not globals.

### Steps to reproduce

1. Edit a matrix entry within a global.
2. Hit save

### Expected behavior

User should be returned to /admin/globals/?

### Actual behavior

User is returned to /admin/entries/

### Craft CMS version

5.1.7

### PHP version

8.2.18

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.1.8 is out with that fix. Thanks again!
