### ISSUE TITLE
[5.x]: Unable to use the alias handle of a field when using the relatedto parameter

### ISSUE THREAD

**Issue by noregt** [craftcms/cms#15106]
### Description
I'm using this code:
          {% set var = craft.entries({
              section: 'mySection',
              relatedTo: {
                  targetElement: entry,
                  field: 'myFieldAliasHandle' 
              }
          }).all() %}

But it won't work until I use the original field handle. Confusing, since in the CP UI it does use this alias. 

### Steps to reproduce

1. use the relatedto parameter on an alias field

### Expected behavior

The alias should work

### Actual behavior

I need to use the original handle. For now that's fine, but might not work after an update. 

### Craft CMS version

5.1.6

### PHP version

8.2

### Operating system and version

Mac OSX

### Database type and version

MySQL MariaDB 10.5

### Installed plugins and versions

- CKeditor
- imager
- Dashboard Begone
- Field Manager
- Splashing Images

**Comment by i-just** [comment]
Hi, thanks for getting in touch!

The `relatedTo.field` element query param needs to be set to the field’s original handle (not the overridden instance handle). The change was made here: https://github.com/craftcms/cms/releases/tag/5.0.0-beta.8.

There’s a bit more info about this here: #15042.

We’ll add that to the docs!
