### ISSUE TITLE
[5.x]: Entry URI Format can't get section slug

### ISSUE THREAD

**Issue by thomascoppein** [craftcms/cms#15108]
### Description
When adding a Entry URI Format to categories or entries it's not possible to add the slug of a section.
After some investigation I noticed that the problem appears when this section is not enabled for the primary site.
While I only need this section in another site.

### Steps to reproduce

1. Add a new section/category
2. Set a custom Entry URI Format
3. Set value: `{{ craft.entries().section('sectionHandle').one().slug }}/{slug}`
4. Go to entry/category with custom URI

![image](https://github.com/craftcms/cms/assets/58168425/65652440-e797-4b01-8765-a09df0de1f3a)

### Expected behavior
www.site.test/section-handle-slug/slug-of-entry

### Actual behavior
www.site.test/slug-of-entry

### Craft CMS version

5.1.7

### PHP version

8?2

### Operating system and version

macOS Sonoma 14.2.1

### Database type and version

mysql

### Installed plugins and versions

- Asset Rev 8.0.0
- CKEditor 4.0.6
- CP Clear Cache 2.0.1
- Dashboard Begone 3.0.0
- Feed Me 6.1.0
- Formie 3.0.0-beta.13
- Retour 5.0.0
- SEOmatic 5.0.3
- Sprig 3.0.2

**Comment by i-just** [comment]
Hi, thanks for getting in touch! 

If you want to get an entry from a section for a particular site, you can add the `.siteId(<id>)` to the query.

I’ll close this now, but feel free to reply if I misunderstood what you were after!

**Comment by thomascoppein** [comment]
Hi, if I have site 1 and site 2, and I only enable two sections on site 2 but not on site 1, it seems logical to me that when I use the slug of section 1 in section 2's Entry URI Format, it should work without needing to add the site ID, right?

**Section 1** 
<img width="1214" alt="Screenshot 2024-05-31 at 09 21 52" src="https://github.com/craftcms/cms/assets/58168425/ce73a2e2-726a-4490-ae0b-f0b3e80ad255">

**Section 2**
<img width="1222" alt="Screenshot 2024-05-31 at 09 33 08" src="https://github.com/craftcms/cms/assets/58168425/916b94e1-f890-41f2-87a5-c23e804994c2">

Result URL of section 2: www.site.test/slug-section-2
While I expect: www.site.test/slug-section-1/slug-section-2

**Comment by i-just** [comment]
When figuring out the entry’s URI based on the section’s Entry URI Format, your `{{ craft.entries.section("newsIndex").collect().first().slug }}` query is executed in the context of the Control Panel, meaning that if you don’t specify the site ID, it will be executed in the context of the primary site. (Here’s a bit more explanation from Brandon on a similar issue from a while back: https://github.com/craftcms/cms/issues/13812#issuecomment-1759596944).

To be clear, you don’t have to pass the site ID statically. You can use `.siteId(object.siteId)` or even just `.siteId(siteId)`. In this context, `object` is the entry this URI is for.

It’s also worth mentioning that with the setup you’re after, the URI of the entry from section 2 won’t be automatically updated when you change the slug of the entry in section 1. Here’s a bit more info on that: https://github.com/craftcms/cms/issues/13151.

I hope this helps!

**Comment by thomascoppein** [comment]
Thanks for your clear and detailed answer. Everything is clear to me now.

**Comment by samuel-clara** [comment]
This should definitly be added to the documentation:
https://craftcms.com/docs/5.x/reference/element-types/entries.html
