### ISSUE TITLE
[5.x]: Multiple conditional fields behave peculiarly when the condition of one assesses the state of the other

### ISSUE THREAD

**Issue by JamieC24** [craftcms/cms#15104]
### Description

I have created an Entry Type that uses an Entries field and a URL field.

The Entries field is conditionally set to appear only when the URL field is empty.

The URL field is conditionally set to appear only when the Entries field is empty.

Both fields are visible to begin with (as expected, as both are empty at this point)

When I populate the URL field, the Entries field disappears (as expected)

When I remove the content from the URL field, the Entries field reappears (as expected)

When I select an Entry from the Entries field, the Entries field disappears and the URL field reappears with the content it had before I removed the content from it.

If I refresh the page, neither of the fields are visible (presumably because the state of both is 'has a value' and the fields are both set to appear only when the other has a state of 'is empty')

### Steps to reproduce

1. Log in to any Craft 5.1.7 install
2. Create an Entry Type
3. Save the Entry Type
5. Create a couple of Entries that use the Entry Type you created
7. Edit your Entry Type using Settings -> Entry Types -> [Your Entry Type]
8. Create an Entries field and add it to the "Content" tab of your Entry Type
9. Create a URL field and add it to the "Content" tab of your Entry Type
10. Edit the settings of your Entries field by clicking on the three dots on the far right of the field box and selecting "Settings"
11. Use the "Entry Condition" section to add a rule that maps to your URL field and checks that it "is empty" (the dropdown for this shows as 'relates to' by default)
12. Repeat this process for the URL field, mapping its conditional rule to the Entries field.
13. Save your Entry Type
14. Go to one of the two Entries you created and put something in the URL field (e.g https://www.google.ie/)
15. Remove the text you've just added by highlighting "https://www.google.ie/" and pressing the backspace key
16. Your Entries field should reappear now. Click the "Add an entry" button on it, select the other entry you created and click "Select"

### Expected Behaviour
When you press "Select", a small representation of the entry you chose should appear under the heading for your Entries field, and the URL field should not be visible

### Actual Behaviour
When you press "Select", the Entries field disappears and is replaced by the URL field that has repopulated itself with whatever you populated it with previously (e.g https://www.google.ie/).
If you refresh the page and scroll to where your field was, you should no longer be able to see the Entries field nor the URL field.

### Craft CMS version

Craft CMS Pro 5.1.7

### PHP version

8.2.0

### Operating system and version

MacOS Sonoma 14.5

### Database type and version

PostgreSQL 15.8

### Installed plugins and versions

- CKEditor 4.0.5
- Feed Me 6.1.0
- Postmark 3.1.0

**Comment by i-just** [comment]
Hi, thanks for getting in touch! I’m not able to reproduce this behaviour. Do you see any errors in the console when editing this entry?

**Comment by JamieC24** [comment]
I just retested this on my local following the steps above and it seems like this doesn't happen when you first set it up, but if you populate the URL field, then save it, then refresh the entry, then do steps 13 and 14, that's when the problem happens!

Would you be able to test this happens for you as well?

**Comment by i-just** [comment]
Thanks for the update. Unfortunately, I’m still not able to replicate this. I take it you don’t see anything in the console when this happens for you?

**Comment by JamieC24** [comment]
How strange!

I'm not seeing any errors in the console, but there are a few warnings - I've attached a screenshot of the warnings I'm getting below:
![Screenshot 2024-05-30 at 12 06 32](https://github.com/craftcms/cms/assets/122913995/7e6a2a0a-7aa6-462a-888c-35decff4a848)

I'm happy to demonstrate the issue I'm getting on a call if that's helpful?

**Comment by i-just** [comment]
Thanks for confirming! Would you be able to send your `composer.json`, `composer.lock` and database export to support@craftcms.com and point out which entry should be edited as per your instructions so that we can reproduce and dig deeper?

**Comment by JamieC24** [comment]
Sure! I'll do that now ☺️

**Comment by i-just** [comment]
Thanks! The missing piece of the puzzle was that the fields are part of a matrix field which has inline-editable blocks view mode. Looking into it.

**Comment by brandonkelly** [comment]
Craft 5.1.8 is out with that fix. Thanks again!
