### ISSUE TITLE
[5.x]: Entry type Title Format custom field too long for SQL

### ISSUE THREAD

**Issue by mattias78** [craftcms/cms#15102]
### Description

When using a custom field in the Title Format for an Entry Type it can exceed the SQL character limit causing the entry not to save.

### Steps to reproduce

1. Create an Entry Type with a Title Format such as My Title: {my_custom_field}. In my case the custom field was a CK Editor field to show the user a preview of the content.
2. Create an entry and attempt to save it.

### Expected behavior

The title format should be truncated.

### Actual behavior

The entry doesn't save.

### Craft CMS version

5.1.7

### PHP version

8.2.18

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! 

I raised a PR to ensure we're validating the title, even if the title field is set to be hidden and the title format is used. This will not truncate the title but will show the validation error in the error summary. 

If you prefer to have the title truncated, you can do so via the Title Format input. For example: `{myPlainTextField|truncate(255, '')}` will limit the auto-generated format to a maximum of 255 characters, without ellipsis at the end and without splitting whole words.

**Comment by brandonkelly** [comment]
Craft 5.1.8 is out with that fix. Thanks again!
