### ISSUE TITLE
[5.x]:  Globals without field layout cannot be deleted.

### ISSUE THREAD

**Issue by panlatent** [craftcms/cms#15123]
### Description

Globals without field layout cannot be deleted.

### Steps to reproduce

1. New a globals (Not add field layout)
2. Save
3. Delete it

### Expected behavior

Deleted.

### Actual behavior

Exception:  craft\\services\\Fields::getLayoutById(): Argument #1 ($layoutId) must be of type int, null given, called in /var/www/html/vendor/craftcms/cms/src/services/Globals.php on line 509

### Craft CMS version

5.1.7

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.1.8 is out with that fix. Thanks again!
