### ISSUE TITLE
[5.2.0-beta.1]: Relations for entries w/ unsaved changes aren't saved

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#15129]
### Description

If an entry with unsaved changes is added to an entries field, the selection will not persist (i.e. the selected entry will disappear when the page is reloaded or if the entry is saved).

https://github.com/craftcms/cms/assets/298510/5816d29b-197a-4277-af7f-c3f61183d0d7

### Steps to reproduce

1. In an entries field, select an entry that has unsaved changes (i.e. tagged with a blue "Edited" pill)
2. Save the entry

### Expected behavior

It should be possible to create relations to elements regardless of whether or not they have unsaved changes.

### Actual behavior

Relations to elements w/ unsaved changes does not persist.

### Craft CMS version

5.2.0-beta.1

### Installed plugins and versions

None

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.2.0-beta.2 is out with that fix. Thanks again.
