### ISSUE TITLE
[5.2.0-beta.1]: "Create entry" doesn't close slideout

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#15128]
### Description

Clicking "Create entry" in a slideout triggered via an entries field does create the new entry, but the slideout stays open instead of closing, and the new entry isn't added to the field.

Inspecting the network panel reveals the following:

- Upon editing a field, the provisional draft is properly created
- Clicking the "Create entry" button results in 200 response from the `elements/apply-draft` controller action.
- Subsequent clicks on the "Create entry" button after that results in a 500 error to the same endpoint. [Stack trace here](https://pastebin.com/Nv4Rkhj0)

Edit: Also seeing similar behavior when attempting to "Save" changes to existing entries via slideouts; changes are saved, but the slideout doesn't close.

https://github.com/craftcms/cms/assets/298510/030b00fe-70c0-4e38-9a20-3e833bb5a695

### Steps to reproduce

1. Create a new entry via an entries field slideout

### Expected behavior

When clicking the "Create entry" button, the slideout should close and the newly created entry should be selected in the field.

### Actual behavior

The new entry is created, but the slideout stays open and the newly created entry is not selected in the field.

### Craft CMS version

5.2.0-beta.1

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next beta release.

**Comment by brandonkelly** [comment]
Craft 5.2.0-beta.2 is out with that fix. Thanks again.
