### ISSUE TITLE
[5.2.0-beta.1]: Impossible to delete entries with unsaved changes

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#15130]
### Description

If an entry has unsaved changes, it's not possible to delete it:

https://github.com/craftcms/cms/assets/298510/5b7ca665-e42f-4024-8624-8cbce6e47a12

### Steps to reproduce

1. Select an entry tagged "Edited" in an entry index, and attempt to delete it via the element action

### Expected behavior

The entry should be deleted.

### Actual behavior

The entry isn't deleted, even though Craft's success toast claims it has been 🙂

### Craft CMS version

5.2.0-beta.1

### Installed plugins and versions

None

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.2.0-beta.2 is out with that fix. Thanks again.
