### ISSUE TITLE
[5.x]: Error thrown during upgrade - Setting unknown property: craft\records\EntryType::slugTranslationMethod

### ISSUE THREAD

**Issue by johnrich85** [craftcms/cms#15133]
### Description

Deploying the craft 5 upgrade to a fresh db throws the following error: Exception: Setting unknown property: craft\records\EntryType::slugTranslationMethod (/var/www/html/vendor/yiisoft/yii2/base/Component.php:209)

I've tried deleting my vendor dir and reinstalling  & can see a reference to the problematic property in the EntryType class:
![image](https://github.com/craftcms/cms/assets/1577555/9b36f55c-6fb6-42a6-9351-00c7caf9eb12)

### Steps to reproduce

1. Upgrade to craft 5 locally
2. Rebuild the config
3. Deploy the changes (apply to a yet upgraded db)

### Expected behavior

Craft successfully upgrades to v5

### Actual behavior

The above exception is thrown

### Craft CMS version

4/5

### PHP version

8.2.19

### Installed plugins and versions

-

**Comment by johnrich85** [comment]
If anyone else comes across this issue: i was initially on an outdated version of 4.x. I'd upgraded to the latest version and then upgraded to v5 in a single branch. I fixed this by separating these out and releasing incrementally.

**Comment by brandonkelly** [comment]
Thanks for reporting! The minimum Craft 4 version the upgrade should have allowed is 4.5.0, but it was incorrectly set to 4.4.0 instead. Just fixed that for the next release, so going forward you would have at least gotten a more clear error message.

**Comment by brandonkelly** [comment]
Craft 5.1.9 is out now with that fix.
