### ISSUE TITLE
[5.x]: Bulk edits are too easy to accidentally discard 

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#15139]
### Description

When bulk editing, the _Save_ and _Cancel_ buttons are right next to each other with very little space between them:

![bulk-edit-action-buttons](https://github.com/craftcms/cms/assets/10146880/4bbd45de-d9c7-4375-b4ad-3ad81f529ebe)

Clicking on _Cancel_ **immediately** discards all pending edits and closes the bulk editing interface, with no way to undo this action. An accidental misclick a few pixels too far to the right might discard a bunch of edits that the author put some time into.

### Steps to reproduce

1. In an element index, click on _Edit_.
2. Edit some fields.
3. Click on _Cancel_.

### Expected behavior

- The buttons should be spaced farther apart to prevent accidental misclicks.
- The _Cancel_ button should prompt for confirmation before discarding your edits.

### Actual behavior

Clicking on Cancel accidentally is very easy, and there is no confirmation prompt.

### Craft CMS version

5.1.8

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.2.0-beta.2 is out with that change. Thanks again for pointing that out!
