### ISSUE TITLE
[4.x]: revisions/versions are showing up, while disabled

### ISSUE THREAD

**Issue by GerbenKR** [craftcms/cms#15135]
### Description
We have a Craft multi-site setup with 10+ sites. For all single sections, we have disabled the versions option (screenshot 1). The versions option is disabled, but the versions dropdown is still showing up for all users (screenshot 2). A user can also select a versions/revision. But when I click the 'view all revisions' button, I get an error (screenshot 3).

### Steps to reproduce

1. Setup a Craft CMS project (4.5.5)
2. Create 2 users (e.g. user1 and user2)
3. Create a single section with revisions disabled
4. Fill the single section with user1 and save
5. Make some changes to the data inside the single section with user1
6. Fill the single section with user2 and save
7. User2 can see and select the revisions of user1

### Expected behavior

When revisions are disabled for a single section, the revision dropdown is not shown

### Actual behavior

The revision dropdown is shown, despite revisions are disabled for the single section

### Secreenshots
**Screenshot 1**
![image](https://github.com/craftcms/cms/assets/69906150/907b339d-ac84-4f91-aa29-f2350b481f8a)

**Screenshot 2**
![image](https://github.com/craftcms/cms/assets/69906150/277babbd-8c4f-4f5a-aa30-d485df5fe50e)

**Screenshot 3**
![image](https://github.com/craftcms/cms/assets/69906150/3a7347cc-66e2-45d1-aa18-cf3ff70fc342)

### Craft CMS version

4.5.5

### PHP version

8.2.19

### Operating system and version

Darwin 23.5.0

### Database type and version

MySQL 8.0.27

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.1-32)

### Installed plugins and versions

Blitz	4.5.4
Embedded Assets	3.1.8
Expanded Singles	2.0.5
Imager X	4.2.2
Mailgun	3.0.0
Minify	4.0.0-beta.2
Navigation	2.0.21
Palette	3.2.2
Position Fieldtype	4.0.0
reCAPTCHA	2.0.2
Redactor	3.0.4
Retour	4.1.13
SEO	4.0.43
Super Table	3.0.9
Typed link field	2.1.5
Vite	4.0.7

**Comment by i-just** [comment]
Hi, thanks for getting in touch! This was fixed in `4.5.10`.
