### ISSUE TITLE
[5.x]: Internal server issue when bulk editing an unpublished canonical draft without a title

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#15138]
### Description

When I make any changes to an unpublished canonical draft that doesn't have a title yet, I get a generic _A server error occured_ notification and my changes aren't saved.

### Steps to reproduce

1. Click on create a new entry (using any entry type with a visible title field and without a title format)
2. Enter content in any field but the title, so an unpublished draft is created, but don't save yet
3. Return to the entry index and start bulk editing. Edit any field except the title and try to save.

### Expected behavior

My bulk edit should still work, even if some required fields are missing. Other validation errors don't prevent the bulk edit from applying, but a missing title seems to be a special case. But when bulk editing, the expectation is always that my edits are applied even if there are errors in other fields.

If it's not possible to save the entry for any reason, the error message should be more specific and actionable, to allow me to recover from the error and still save all the other entries I may have edited. Otherwise, those edits are lost and have to be redone.

### Actual behavior

Edits are not applied (to any elements, including those that don't cause an error), and the error doesn't tell me what's wrong. There is no clear path to recovering from this error and still applying the pending changes.

### Craft CMS version

5.1.8

### PHP version

8.2

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.1.9 is out now with that fix. Thanks again!
