### ISSUE TITLE
[5.x]: Address filter returns incorrect "given name" if first name contains periods.

### ISSUE THREAD

**Issue by TheFunkyMonk** [craftcms/cms#15146]
### Description

I go by R.J. LaCount, and when I'm registered in Craft under that full name, outputting my address info on the front end of a site with the `|address` filter, my name is split into `given-name` and `family-name` elements. Those together return my name as "R LaCount" instead of "R.J. LaCount".

Honestly, this happens in tons of systems so I'm used to it. But it'd be nice if we could include periods in names without strange front end formatting like this.

### Steps to reproduce
1. Create a user with periods in their first name
2. Output that user's address info on the front end with the `|address` filter

### Expected behavior
User's full name appears

### Actual behavior
Users first name is truncated to everything before the first period

### Craft CMS version

5.1.8

### PHP version

8.2.19

### Operating system and version

Linux 6.5.0-15-generic

### Database type and version

MySQL 8.0.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

CKEditor 	4.0.6
Colour Swatches 	5.0.0
Control Panel CSS 	3.0.0
Craft Commerce 	5.0.8
Default Dashboard 	3.0.0
Field Manager 	4.0.0
Guide 	4.0.0-beta.1
ImageOptimize 	5.0.1
Image Resizer 	4.0.0
Neo 	5.0.0
No-Cache 	3.0.2
PayPal Checkout for Craft Commerce 	3.0.0
Redirects 	5.0.0
Retcon 	3.0.0
SEO 	5.0.3
Servd Assets and Helpers 	4.0.3
Stripe for Craft Commerce 	5.0.1

**Comment by brandonkelly** [comment]
Name parsing is handled by [theiconic/name-parser](https://github.com/theiconic/name-parser), so you should report this over there. It feels obviously wrong in this case, so hopefully they can fix.

As a temporary workaround, you can enable the [showFirstAndLastNameFields](https://craftcms.com/docs/5.x/reference/config/general.html#showfirstandlastnamefields) config setting, which will replace the “Full Name” field with distinct “First Name” and “Last Name” fields.
