### ISSUE TITLE
Security bulletin for yiisoft/yii2 <2.0.50 Update dependency in Craft 4 and craft 5

### ISSUE THREAD

**Issue by sfsmfc** [craftcms/cms#15148]
### Description
 According to https://github.com/advisories/GHSA-cjcc-p67m-7qxm and https://github.com/advisories/GHSA-qg5r-95m4-mjgj, the dependency "yiisoft/yii2": "~2.0.48.1" should be adjusted, because an updated to version 2.0.50 will be blocked with this dependency. Update the dependency to "yiisoft/yii2": "~2.0.48" should also work.

### Craft CMS version

4.9.x und 5.x

**Comment by i-just** [comment]
Hi, thanks for getting in touch! 

Looks like this is a duplicate of https://github.com/craftcms/cms/issues/15124 - you can find more info about it there. 
In a nutshell, it’s already resolved in `4.10.0-beta.1` and `5.2.0-beta.1`.
