### ISSUE TITLE
[5.2.0-beta.3]: "Date Created" entry index column is labelled "Date Uploaded"

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#15155]
### Description

The "Date Created" attribute in entry index columns reads "Date Uploaded":

![CleanShot 2024-06-05 at 23 15 13@2x](https://github.com/craftcms/cms/assets/298510/c6c6a657-4d98-48d6-b2d5-4442ce0a31cf)

![CleanShot 2024-06-05 at 23 16 46@2x](https://github.com/craftcms/cms/assets/298510/57c5b773-a6f6-4c1d-928f-e0f59a064239)

### Steps to reproduce

1.

### Craft CMS version

5.2.0-beta.3

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Doh, thanks for reporting. Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 5.2.0-beta.4 is out now with that fix.
