### ISSUE TITLE
[4.x]: Database backup broken on Windows

### ISSUE THREAD

**Issue by oliver-graetz** [craftcms/cms#15151]
### Description
The change in 4.9.3 `Fixed a bug where the db/backup command would fail if the destination path contained a space.` breaks database backup on Windows systems. The bug still persists in Craft 4.9.6.

### Steps to reproduce

1. `php craft db/backup`

### Expected behavior

A database backup is created.

### Actual behavior

(error message anonymized)

`Backing up the database ... error: The shell command "mysqldump "--defaults-file"="C:\Users\xxx\AppData\Local\Temp\xxx.cnf" "--add-drop-table" "--comments" "--create-options" "--dump-date" "--no-autocommit" "--routines" "--default-character-set"="utf8" "--set-charset" "--triggers" "--no-tablespaces" "--no-data" "--result-file"="C:\xxx.sql" "xxx" && mysqldump "--defaults-file"="C:\Users\xxx\AppData\Local\Temp\xxx.cnf" "--add-drop-table" "--comments" "--create-options" "--dump-date" "--no-autocommit" "--routines" "--default-character-set"="utf8" "--set-charset" "--triggers" "--no-tablespaces" "--no-create-info" "--ignore-table"="xxx.assetindexdata" "--ignore-table"="xxx.cache" "--ignore-table"="xxx.imagetransformindex" "--ignore-table"="xxx.resourcepaths" "--ignore-table"="xxx.phpsessions" "--ignore-table"="xxx.sessions" "xxx" >> 'C:\xxx.sql'" failed with exit code 1.`

Running the command directly gives more info on the error:

    The filename, directory name, or volume label syntax is incorrect

Changing the single quotes for the very last filename path to double quotes resolves the problem.

### Craft CMS version

4.9.3

### PHP version

8.1.2

### Operating system and version

Windows 10 22H2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting @oliver-graetz! This was previously brought up by #15090, and it’s fixed now for the next release.

You can get the fix ahead of time by changing your `craftcms/cms` requirement in composer.json to `4.x-dev as 4.9.6` and running `composer update`.

**Comment by oliver-graetz** [comment]
Oh, wow. It's not that I hadn't searched for a duplicate. Thanks for fixing this.
