### ISSUE TITLE
[5.x]: eagerly() sometimes not working in matrix

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#15164]
### Description
I have a matrix with 2 block types, let's say "image" and "image wide". Both have asset field using the handle `image`  but are not required. 
Now create an entry and with those 2 blocks: image --> empty and image wide --> some image.

Looping through the matrix blocks and outputting the image
```twig
{% set blocks = entry.contentBlocks.collect() %}

{% for block in blocks %}
  {% if block.type == 'image' %}
    {% set img = block.image.eagerly().one() %}
    {{ dump(img) }}
  {% elseif block.type == 'imageWide' %}
    {% set img = block.image.eagerly().one() %}
    {{ dump(img) }}
  {% endif %}
{% endfor %}
```

### Expected behavior
The image from the "image wide" block is eagerloaded and outputted

### Actual behavior
Both images output `null`

### Craft CMS version

5.1.9 & 5.2.0-beta.3

### PHP version

8.3.7

### Database type and version

MySQL 8.0.37

**Comment by brandonkelly** [comment]
Are both of your `image` fields the same Assets field? Or two different ones?

**Comment by WHITE-developer** [comment]
They are different, one is renamed to `image`, sorry for missing that in the example

**Comment by brandonkelly** [comment]
In that case, you will need to pass a custom eager-loading handle to `eagerly()` for at least one of the calls, if not both, so one eager-loading result doesn’t override the other.

```php
{% set blocks = entry.contentBlocks.collect() %}

{% for block in blocks %}
  {% if block.type == 'image' %}
    {% set img = block.image.eagerly('image').one() %}
    {{ dump(img) }}
  {% elseif block.type == 'imageWide' %}
    {% set img = block.image.eagerly('imageWide').one() %}
    {{ dump(img) }}
  {% endif %}
{% endfor %}
```
