### ISSUE TITLE
[5.x]: Requests to `admin/login` when logged in, no longer redirect to CP

### ISSUE THREAD

**Issue by engram-design** [craftcms/cms#15168]
### Description
Looks like a change in behaviour compared to Craft 4. If you're logged in, head to `/admin/login` and you'll be shown the login screen despite being logged in. In Craft 4, you were redirected to the Dashboard.

Related to https://github.com/verbb/social-login/issues/28

### Craft CMS version

5.1.9

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! I removed the code to handle that case in #13000 for some reason, but [the commit](https://github.com/craftcms/cms/commit/d75367d2714b7c0d40ec51350c512fb26c2f79a6) doesn’t exactly say why.

Just released 5.2.0-beta.5 with that logic returned.
