### ISSUE TITLE
[5.x]: Matrix in card view doesn't show validation errors from card

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#15161]
### Description
When saving an entry with a matrix in card view and one of the cards has a validation error, there is no indication which card has the error 
![image](https://github.com/craftcms/cms/assets/22771556/4b2bf453-4e6c-41ff-99be-f98747d4559c)
![image](https://github.com/craftcms/cms/assets/22771556/6c8b5ae8-ed34-40e8-ba88-9de74f2f7d88)

### Steps to reproduce

1. Matrix in Card view
2. Have it saved correctly
3. Make a field required in the matrix
4. Try resaving the entry

### Expected behavior
Some indication where the error is

### Actual behavior
No indication except on which tab the error is

### Craft CMS version

5.1.9 & 5.2.0-beta.3

### PHP version

8.3.7

### Database type and version

MySQL 8.0.37

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for pointing that out! This is now resolved for Craft 5.2, which will start displaying entry cards in an error state when they contain validation errors:

<img src="https://github.com/craftcms/cms/assets/47792/2ba3fff3-7568-485d-b8d9-6c77b4cd7d18" width="844" height="192" alt="A Matrix field that contains a nested entry that identifies it has validation errors">

**Comment by WHITE-developer** [comment]
This seems not to work when in a x levels deep slideout, just getting a "Couldn’t save entry." message there, but I guess it's in progress for 5.3?

**Comment by brandonkelly** [comment]
@WHITE-developer Can you post a new issue with full steps to reproduce + expected/actual results?
