### ISSUE TITLE
[4.x]: 400 Error on "save-user" controller (AJAX)

### ISSUE THREAD

**Issue by zadro** [craftcms/cms#15170]
### What happened?

When saving a user profile via Ajax to the "save-user" endpoint, a status code 200 is returned when there are no errors. All good here. 

**However, the controller returns with a 400 status code if _any_ field returns an error.** 

JSON data is returned in either event, so this behavior appears to be a bug. 

Response from NON field error (200 status):

```
{
	"id": 1,
	"modelName": "user",
	"user": {
		.....
	},
	"message": "User saved."
}
```

Response with any field error (400 status):

```
{
	"modelName": "user",
	"user": {
		.....
	},
	"errors": {
		"currentPassword": [
			"Incorrect current password."
		],
		"newPassword": [
			"New Password should contain at least 6 characters."
		]
	},
	"message": "Couldn’t save user."
}
```

My Ajax uses jQuery and a basic `$.post();` method. 

Please let me know if there's anything else I can provide. 

### Craft CMS version

4.9.6

### PHP version

8.2.20

### Operating system and version

Linux 6.1.0-18-amd64

### Database type and version

MariaDB 10.11.8

### Installed plugins and versions

CKEditor 	3.8.3
Super Table 	3.0.14

**Comment by i-just** [comment]
Hi, thanks for getting in touch! The status 400 is returned on purpose if there are validation errors. It was changed to work this way in Craft 4, and there’s a bit more info about it here: https://github.com/craftcms/cms/discussions/8631 and here: https://github.com/craftcms/cms/issues/11738.

I’ll close this now, but feel free to reply if I misunderstood your point!

**Comment by zadro** [comment]
Thank you for letting me know!
