### ISSUE TITLE
[5.x]: Not finding "memo" icon with search terms like "text" or "document"

### ISSUE THREAD

**Issue by droemmelbert** [craftcms/cms#15174]
### Description
When using the text search on an entry to add an icon representing the entry, I tried to find an icon like the _memo_ icon but failed to find it for a while, since it did not show up when using search terms like "text" or "document".

### Steps to reproduce

1. Go to settings
2. Go to entry types
3. Add new entry type
4. Under "icon" click "choose"
5. Use search bar (e.g. "text")
6. Do not find "memo" icon

### Expected behavior
I can find the memo icon (and others potentially) with more keywords than just "memo"

### Actual behavior
I have to type in "memo", "paper" or "note" in order to find the "memo" icon.

### Craft CMS version

5.1.10

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
The icon keywords come from Font Awesome’s icon metadata. [Searching for `text` on fontawesome.com](https://fontawesome.com/search?q=text&o=r) doesn’t show the `memo` icon there either. You might be able to PR keyword changes to them, and then they’ll end up in Craft, though.
