### ISSUE TITLE
[5.x]: `Element::getIsFresh()` not working in 5.2.0 beta

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#15179]
### What happened?

Calling `Element::getIsFresh()` on a fresh element returns `false` in 5.2.0-beta.5.

This is causing an error in the Campaign plugin, since `getIsFresh()` returns an incorrect value here:
https://github.com/putyourlightson/craft-campaign/blob/13cb2426aab1268f241896f168a1f88b78386f3b/src/elements/MailingListElement.php#L544

### Steps to reproduce

1. Create a fresh draft of an element.
2. Inspect the result of calling `getIsFresh()` on the element.

### Expected behavior

Calling `getIsFresh()` on a fresh draft of an element should return `true` and does so in Craft 5.1.10.

### Actual behavior

Calling `getIsFresh()` on a fresh draft of an element returns `false` in Craft 5.2.0-beta.5.

### Craft CMS version

5.2.0-beta.5

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 5.2.0-beta.6 is out with a fix.
