### ISSUE TITLE
[5.x]:  Cannot query authors via Graphql on Craft Team license

### ISSUE THREAD

**Issue by ajoliveau** [craftcms/cms#15187]
### Description

When using Craft with the Team license, you have full access to the whole multi-users feature set, including assigning one (or multiple) authors, but the authorId and author graphql attributes are not available in the schema.

### Steps to reproduce

1. Use the Team license
2. Check the Graphql Schema (at /admin/graphql/schemas/public) and note you don't see the options to query Users
3. Check graphiql and see you have no authors field anywhere
4. Switch to the Pro license
5. Check that you can see and check the Users query options
![image](https://github.com/craftcms/cms/assets/3447717/577904ba-c4a2-4008-a725-49e004f98413)
6. Confirm you can query Author information `{ entries { authorId } }`
7. Bonus : Switch back to the Team license, and even though you can't see the Users query options in the schema, you still can query users

### Expected behavior

I don't actually know. According to the [pricing page](https://craftcms.com/pricing), Team and Pro licenses should give the same permissions related to users (but Pro as unlimited users) ?
But according to the [documentation](https://craftcms.com/docs/5.x/reference/element-types/entries.html#editing-entries) some authors functionality like "Choose the entry’s Authors" is gated to the Pro license ? But I guess that's just old doc that wasn't updated when the Team plan was introduced

### Actual behavior

With a Team license, I'm not able to query authors for entries using Graphql

### Craft CMS version

5.1.9

### PHP version

8.2.19

### Operating system and version

Linux 6.9

### Installed plugins and versions

```
 Name                Handle              Package Name                Version        Installed  Enabled
    ------------------  ------------------  --------------------------  -------------  ---------  -------
    Expanded Singles    expanded-singles    verbb/expanded-singles      3.0.0          Yes        Yes    
    Field Manager       field-manager       verbb/field-manager         4.0.0          Yes        Yes    
    Formie              formie              verbb/formie                3.0.0-beta.14  Yes        Yes    
    Navigation          navigation          verbb/navigation            3.0.0          Yes        Yes    
    Neo                 neo                 spicyweb/craft-neo          5.0.1          Yes        Yes    
    Redactor            redactor            craftcms/redactor           4.0.0          Yes        Yes    
    SEOmatic            seomatic            nystudio107/craft-seomatic  5.0.3          Yes        Yes    
    Translations admin  translations-admin  mutation/translate          4.0.2          Yes        Yes    
```

**Comment by i-just** [comment]
Hi, thanks for reporting!

> According to the [pricing page](https://craftcms.com/pricing), Team and Pro licenses should give the same permissions related to users (but Pro as unlimited users) ?

That’s correct. It’s an oversight, and I raised a PR for it.

> But according to the [documentation](https://craftcms.com/docs/5.x/reference/element-types/entries.html#editing-entries) some authors functionality like "Choose the entry’s Authors" is gated to the Pro license ? But I guess that's just old doc that wasn't updated when the Team plan was introduced

And you’re right here, too. The docs need to be updated. I [raised an issue ](https://github.com/craftcms/docs/issues/623)for this in the docs repo.

**Comment by brandonkelly** [comment]
Craft 5.2.1 is out with that fix to GraphQL schemas. Thanks again!

**Comment by ajoliveau** [comment]
Good to know, thank you for the quick fix !
