### ISSUE TITLE
[5.2]: Small styling bugs in collapsed navbar

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#15186]
### Description

When the CP navbar is collapsed, the newly introduced darkened background is not aligned with the nav item separators and looks a bit wonky. Also, the arrows for the subnavs are not horizontaly aligned with the icon (in the collapsed state):

![image](https://github.com/craftcms/cms/assets/19857599/cedeb957-0aeb-4b73-9951-017ae42eec75)

Sorry for the nitpicks, 5.2 looks good!

### Craft CMS version

5.2.0

### Installed plugins and versions

-

**Comment by brianjhanson** [comment]
Thanks @thupsi! I've opened a PR to clean this up a bit.

**Comment by brandonkelly** [comment]
Craft 5.2.1 is out with that fix. Thanks again!
