### ISSUE TITLE
[5.x]: Field Groups missing

### ISSUE THREAD

**Issue by alisonweirsmith** [craftcms/cms#15191]
### Description
In your documentation you show field groups:
https://craftcms.com/docs/5.x/system/fields.html

In my installation of Craft5, all shiny and new, there is no field groups to be seen.
These are quite useful to group fields for specific channels etc so they don't get lost in the many fields that happen. How can I get field groups back?

### Steps to reproduce

1. Install Craft5
2. Create a field and attempt to add it to a field group
3. No option exists

### Expected behavior
https://craftcms.com/docs/5.x/system/fields.html

### Actual behavior
<img width="722" alt="Screenshot 2024-06-13 at 1 52 41 PM" src="https://github.com/craftcms/cms/assets/31128856/386cc4be-b532-4e11-849d-7737c5362ab4">

### Craft CMS version

5.1.10

### PHP version

8.2.0

### Operating system and version

Mamp, MacOs

### Database type and version

MySQL 8

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch!

Field groups were removed in Craft 5. More info on that can be found here: https://github.com/craftcms/cms/discussions/14083.

Thanks for pointing out that the documentation still mentions them for v5. We’ll get that updated!
