### ISSUE TITLE
[5.x]: Element chips and cards show other users' provisional drafts

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#15208]
### Description

If there's a provisional draft for an entry, that provisional draft is exposed to other users in chips and cards for that entry:

![CleanShot 2024-06-15 at 20 26 08@2x](https://github.com/craftcms/cms/assets/298510/b05e3890-c16c-4473-8a57-5633e2d49815)

### Steps to reproduce

1. Have two different users
2. Log in as user 1, and edit an existing entry. Don't "Save" the edits, i.e. leave it as a provisional draft
3. Log in as user 2. Confirm that edits made in user 1's provisional draft, as well as the "Edited" tag, displays in element chips and cards for that entry.

### Craft CMS version

5.2.0

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 5.2.1 is out with a fix.
