### ISSUE TITLE
[5.x]: UX issue with Password Reset dialog. No way to close dialog box.

### ISSUE THREAD

**Issue by johnfmorton** [craftcms/cms#15202]
### Description

I was showing a client how to copy a "Password reset URL..." when a dialog box asking for the password popped up. Since I was only demonstrating the process, I wanted to exit the dialog box and return to the conversation. Unfortunately, there is no "close button," and hitting ESC does not dismiss the dialog box. Addressing this would be a good UX update to the control panel.

### Craft CMS version

5.2.0

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 5.2.1 is out with that fix. Thanks again!
