### ISSUE TITLE
[5.x]: Email fields aren't showing

### ISSUE THREAD

**Issue by ishetnogferre** [craftcms/cms#15200]
### Description
When trying to edit the email settings locally, the fields aren't showing.

### Steps to reproduce

1. Open the Email Settings

### Expected behavior
Have fields to fill in

### Actual behavior
<img width="884" alt="Screenshot 2024-06-14 at 15 21 27" src="https://github.com/craftcms/cms/assets/6649706/9446c2fd-9a97-418e-9b7e-944a1075b6a4">

### Craft CMS version

5.2.0

### PHP version

8.2

### Operating system and version

Mac OS

### Database type and version

MySQL 8+

### Image driver and version

/

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch! Craft doesn’t have a `searchable.js` file. Could you disable all your plugins and modules and check if the problem persists?

**Comment by ishetnogferre** [comment]
Ah yes, apologies, it was the Searchable plugin 😇

**Comment by i-just** [comment]
No worries! Glad you got to the bottom of this.
