### ISSUE TITLE
[4.9.7]: Calling unknown method: craft\web\Response::getIsDraft()

### ISSUE THREAD

**Issue by yingban** [craftcms/cms#15211]
### Description

When saving a entry (new or existing), I have the following fatal error.
I updated to 4.10.0 to see if it was fixed, but it is still there.

"Calling unknown method: craft\web\Response::getIsDraft()"

I tried to reproduce after disabling all plugins, but the issue remains.

![Screenshot 2024-06-17 at 10 40 16](https://github.com/craftcms/cms/assets/3421450/86b01b66-bb44-473e-bc37-4a0e30708f57)

### Craft CMS version

4.10.0

### PHP version

8.2.15

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 4.10.1 is out with that fix. Thanks again!
