### ISSUE TITLE
[5.x]: Replace File assets - UI doesn't provide enough feedback to authors

### ISSUE THREAD

**Issue by LauraMontgomery** [craftcms/cms#15217]
### What happened?

My apologies if this is directly related to [this Feature Request](https://github.com/craftcms/cms/issues/2842)
Or indeed if it should more appropriately full under FR.

When using Replace File on an asset within an entry, there's no feedback that an upload has happened, and the thumbnail doesn't update when the action is complete. It was only after saving and refreshing that I was sure the replacement actually occurred.

When replacing the file through assets, again there is no feedback that anything is happening until the sidebar image updates. So if you don't have the sidebar open, you don't see this happening. Also the small thumbnail in the breadcrumb doesn't update. Again, saving and refreshing was the only way I was sure this action actually occurred.

![1 assets](https://github.com/craftcms/cms/assets/3043327/1c6ad922-4835-48da-a78d-fb298a4afb96)
![2 on a page](https://github.com/craftcms/cms/assets/3043327/87a737c5-ef8b-4c1f-b9a0-0cbeca835dfc)

### Craft CMS version

5.1.6

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thank for pointing that out @LauraMontgomery! We just released Craft 5.2.2 which improves the Replace File behavior a bit: now the asset’s thumbnail will be refreshed wherever it appears on the page after upload.

Craft 4.11 and 5.3 will improve on that further, by displaying a “New file uploaded.” success message after the file has been replaced.

**Comment by LauraMontgomery** [comment]
@brandonkelly thank you so much for sorting it so quickly! And great to hear that it'll be even better in upcoming versions :) thank you again
