### ISSUE TITLE
[5.x]: Level indentation broken for entries with status label in structured sections

### ISSUE THREAD

**Issue by svale** [craftcms/cms#15214]
### Description
With 5.2 the indentation that visualise the structured hierarchy breaks for entries that have a status label.

### Steps to reproduce

1. Create a Structure section
2. Add entries on different levels (with parent-child relation) 
3. Edit child entries without publishing changes (state: edited)
4. See entries in the entries index 

### Expected behavior
The entries index should preserve the structured hierarchy 
![image](https://github.com/craftcms/cms/assets/5339180/05f116f9-9bb1-413b-8d14-b92deec8279a)

### Actual behaviour
All entries are left aligned with no hierarchy
![image](https://github.com/craftcms/cms/assets/5339180/73a11a93-d24c-47d7-bf44-7b4b56946a71)

### Craft CMS version

5.2.0

### PHP version

8.2

### Operating system and version

Craft Cloud and Ddev on MacOs 14.6

### Database type and version

mariadb:10.11 and mysql 8

### Installed plugins and versions

Plugin | Version
-- | --
Amazon S3 | 2.2.1
Asset Usage | 4.0.0
CKEditor | 4.1.0
Embedded Assets | 5.1.0
Expanded Singles | 3.0.0
Feed Me | 6.1.0
Field Manager | 4.0.0
Formie | 3.0.0-beta.15
Hyper | 2.0.2
Imager X | 5.0.0
Many to Many | 4.0.0
Retcon | 3.1.1
SEO | 5.0.4
Sprig | 3.0.2
Vite | 5.0.0

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 5.2.1 is out with a fix.
