### ISSUE TITLE
[5.x]: a11y issue with status indicators

### ISSUE THREAD

**Issue by MattWilcox** [craftcms/cms#15213]
### Description

I have my user profile set to "Use shapes to represent statuses", but the shape for Live and Disabled are both circles, adding to the problem the tone of the grey and green are such a close match that I literally can not see a difference - so at the moment it's very hard to see what Entries are disabled and what aren't.

<img width="227" alt="Screenshot 2024-06-17 at 10 21 18" src="https://github.com/craftcms/cms/assets/814039/aa472867-98ff-4acc-bb6b-62c1941c887c">

<img width="292" alt="Screenshot 2024-06-17 at 10 30 22" src="https://github.com/craftcms/cms/assets/814039/0eb754d4-598c-4bda-9a30-6d2ddfbc273a">

### Steps to reproduce

1. Use the setting, be colour blind.

### Expected behavior

The setting should use different shapes for all the statuses.

### Actual behavior

Does not diferentiate statuses by shape; the colours are far too close.

### Craft CMS version

5.2.0

### Installed plugins and versions

-

**Comment by thupsi** [comment]
https://github.com/craftcms/cms/pull/15206

**Comment by MattWilcox** [comment]
Agh! Thanks @thupsi - closing this issue as it's a duplicate (sort of, I'd still like the shapes to actually be different)

**Comment by brandonkelly** [comment]
Craft 5.2.1 is out with that change.
