### ISSUE TITLE
[5.x]: Float numbers in GraphQL weird behaviour

### ISSUE THREAD

**Issue by ishetnogferre** [craftcms/cms#15222]
### Description
We're using the number fields to store longitude and latitude because we only need these values. In the front-end we us GraphQL to query between two numbers.

### Steps to reproduce

1. Have a Numbers field, set to 16-20 decimals
2. Query the exact number
3. Query between 2 numbers with decimals

### Expected behavior
In case 2: have the exact entry returned
In case 3: have the entry and others returned

### Actual behavior
1. When using the exact number, an error show we can only use string, integer or boolean.
![Screenshot 2024-06-18 at 10 29 27](https://github.com/craftcms/cms/assets/6649706/df59d4d3-1b12-49d7-9f4e-45367640fcca)
<img width="1159" alt="Screenshot 2024-06-18 at 10 29 20" src="https://github.com/craftcms/cms/assets/6649706/8fb02a7d-d4c4-474e-9482-d7ce666b6f32">

2. When using a simple comparison (>= or <=), it show the correct entry and more
<img width="1003" alt="Screenshot 2024-06-18 at 10 30 47" src="https://github.com/craftcms/cms/assets/6649706/26d1d2c9-518a-4b9e-b811-c9574484abff">

3. When using a range, it shows none
<img width="944" alt="Screenshot 2024-06-18 at 10 30 58" src="https://github.com/craftcms/cms/assets/6649706/9c30eae8-f353-4e91-a7c9-e488a7a4f04e">

**Extra**
Don't know if this is expected behaviour but the filter input doesn't incorporate the decimal setting from the Number field.
<img width="681" alt="Screenshot 2024-06-18 at 10 39 56" src="https://github.com/craftcms/cms/assets/6649706/03fdc6cb-1e2e-4f50-9922-270844fc285e">

### Craft CMS version

Craft 5.2.0

### PHP version

8.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting those! Craft 4.10.2 and 5.2.2 are out with a fix for the condition rule bug (6b370d3ca6723beeb2865e572b7f5ea3cba9443c) and 5.2.2 also includes a fix for the query param handling (#15227).
