### ISSUE TITLE
[5.x]: Error on the edit page for created assets by asset index utility from files with spaces in filename

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#15236]
### Description
- If a file has spaces in filename, the asset created from the file by Asset Indexes utility can not be edited on full edit page and there is an error shown to the user: `Forbidden, You don't have permission to access this resource.`.

### Steps to reproduce

1. Upload a file which has spaces in the filename.
2. Use Asset index utility to index the file.
3. Go to the edit page and click on the title of file.
4. There is an error: You don't have permission to access this resource.

### Craft CMS version

5.2.0

### PHP version

8.2

### Operating system and version

Ubuntu 20

### Database type and version

MariaDB 10.6.7

### Installed plugins and versions

- commerce
- digital product

**Comment by brandonkelly** [comment]
I’m not able to reproduce that, and nothing in Craft/Yii will produce that specific error. Is it a Craft-styled error message? If so it’s probably coming from a plugin or module; otherwise from your server/infrastructure.

**Comment by vnali** [comment]
@brandonkelly I recorded a video that shows how i reproduced the error with fresh 5.2.3 without any plugin.
in this video the problem is with the 'with space.txt' file not 'without-space.txt' file.

https://github.com/craftcms/cms/assets/55586085/1933b81d-7a84-41fd-ab85-3e6f6f73f1a1

**Comment by brandonkelly** [comment]
Just tested with those exact two filenames + Craft version, and it works fine for me.

![Screenshot of the control panel editing a “with space.txt” asset](https://github.com/craftcms/cms/assets/47792/c4978eed-4178-4243-ada0-c1408a09b826)

That error is coming from Apache, not Craft. So something about your Apache configuration is probably intercepting the request and blocking it with that forbidden error. Perhaps you have a security module like Suhosin installed, which doesn’t like something about the requested URL or Craft’s response.

**Comment by vnali** [comment]
thanks @brandonkelly 
I will check the apache settings but one thing that seems weird to me is if i go to view the asset page -`http://craft5-2.test/fs1/with space.txt`-, i can see the asset correctly.  
if you look at the title of page it seems space is encoded correctly with `%20` but i don't know why it does not do that with the edit page url.  
and i have a question that why asset index utility does not replace the space with `-` in filename  but direct asset upload does.?

![Untitled - Copy](https://github.com/craftcms/cms/assets/55586085/8f306111-b146-4f92-b0df-9625d83166c2)

**Comment by brandonkelly** [comment]
> I will check the apache settings but one thing that seems weird to me is if i go to view the asset page -`http://craft5-2.test/fs1/with space.txt`-, i can see the asset correctly.

That’s a separate request that Apache is able to handle directly, by reading out the contents of the referenced file path. Whatever security rule is tripping up the Edit Asset page isn’t affected by it. The Edit Asset page isn’t actually loading or reading out the contents of the file, so these two requests have no technical relation to each other, as far as Apache is concerned.

> if you look at the title of page it seems space is encoded correctly with `%20` but i don't know why it does not do that with the edit page url.

`%20` and a space are the same thing. Not sure why the browser would show `%20` in one case and not the other, but the actual URL to the Asset’s edit page should include `%20` if you output it in the console:

<img src="https://github.com/craftcms/cms/assets/47792/d42322fe-caae-4b4b-861e-10bb64149083" width="450" height="41" alt="Screenshot of console output showing that the space is encoded in my `with space.txt` asset’s edit page URL">

> and i have a question that why asset index utility does not replace the space with `-` in filename but direct asset upload does.?

Because the utility is not meant to modify filenames; only ensure that the asset elements match what’s on the filesystem, treating the filesystem as the source of truth. When you upload an asset, Craft is the one placing the file into the filesystem to begin with, so it’s safe to modify its name to make it more web-friendly in that case.

**Comment by vnali** [comment]
Thank you for your time @brandonkelly 
I put some information here maybe that is helpful for someone else.
I had this error in apache error log: `[rewrite:error]  AH10411: Rewritten query string contains control characters or spaces`

It seems after a security fix patched in apache 2.4.56 -and backported to older versions like 2.4.41-4ubuntu3.17 in my Ubuntu 20 test server, all rewrite requests via .htaccess files that contain spaces or control characters in backreferences, [will result in 403 error messages as these characters will not be escaped correctly before being transformed/rewritten.](https://www.icdsoft.com/en/kb/view/1148_urls_with_space_characters_return_403_forbidden_error) and it causes breaking some other CMSs and it applies only to query string part -in this case id-filename passed to elements/edit page i think- so this is why i get the error only in edit page not the view page.

Some workarounds are changing `RewriteRule (.+) index.php?p=$1 [QSA,L]`  line in .htaccess file to `RewriteRule (.+) index.php?p=$1 [BCTLS,QSA,L]` or `RewriteRule (.+) index.php?p=$1 [B,QSA,L]`.
I was not able to use `BCTLS` because it was introduced in 2.4.57 but with using `B` i was able to view the asset edit page but i am not sure if it makes trouble with other pages or not.

**Comment by brandonkelly** [comment]
Ah interesting.

**Comment by brandonkelly** [comment]
Oh interesting, I didn’t consider it could be a problem with the `index.php` rewrite rule, but that makes sense. I’ve just tweaked the asset edit page URL for the next Craft 5 release, so any spaces will be replaced with hyphens.

**Comment by brandonkelly** [comment]
Craft 5.2.4 is out with that fix. Thanks for reporting and bearing with me!
