### ISSUE TITLE
[5.x]: Unusable Icons Displayed in Icon Field

### ISSUE THREAD

**Issue by droemmelbert** [craftcms/cms#15242]
### Description
I want to use the icon field to select icons for display on the front end. However, as a non-paying customer of _fontawesome_, I can only use a limited number of icons. It would be great if the icon field had the option to display only those icons that are free to use. This would prevent confusion for users who might select icons that do not display on the front end.

### Steps to reproduce

1. Install the fontawesome icons as web fonts as desribed in the CraftCMS icon field [documentation](https://craftcms.com/docs/5.x/reference/field-types/icon.html)
2. Implement an icon field and configure it to display icons on the front end
3. Select "gear" icon --> displayed on the front end as expected ✅
4. Select "rectangle-history" icon --> not displayed in front end ⚠️

### Expected behavior
All icons selectable through the icon menu should be displayed on the front end.

### Actual behavior
Some selected icons, such as the "rectangle-history" icon, are not displayed on the front end because they are premium icons.

### Craft CMS version

5.2.0

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
I just addressed this for Craft 5.3, by adding a new “Include Pro icons” setting to Icon fields (#15249). Going forward you’ll be able to disable that setting if you don’t want authors to be able to select icons that are exclusive to Font Awesome Pro.

If you’d like to test 5.3 with the new setting before it’s released, change your `craftcms/cms` requirement in composer.json to:

```json
"craftcms/cms": "5.3.x-dev as 5.3.0-alpha",
```

Then run `composer update`.

**Comment by droemmelbert** [comment]
@brandonkelly Thank you for the quick fix!!!
Do you have an ETA on when version 5.3 will be released?

**Comment by brandonkelly** [comment]
@droemmelbert Probably no later than late July/early August.

**Comment by brandonkelly** [comment]
Craft 5.3.0-beta.1 is out with that new “Include Pro icons” setting 🎉

We’re targeting August 6 for the GA release. If you’d like to test ahead of time, change your `craftcms/cms` requirement in composer.json to:

```json
"craftcms/cms": "^5.3.0-beta.1",
```

and then run `composer update`.

**Comment by zdimaz** [comment]
How to add new custom icons ?

**Comment by brandonkelly** [comment]
@zdimaz That’s not possible using the built-in Icon field. But you’re welcome to request that we add something!

**Comment by AmsalSugihan** [comment]
Hi @brandonkelly ,
i've try to activate Include Pro icons to my field, but after that there some icons still not showing on icon picker modal, example like facebook icon, instagram icon (that actually pro icon). is there any things that i need to added so those icons can show or picked ?

**Comment by brandonkelly** [comment]
Facebook and Instagram icons were both just added today in the 5.5.0 release.

**Comment by paulcripps** [comment]
I'd really like it so that we can add our own custom FontAwesomeKitt icons URL in the config for this, for example:

`https://kit.fontawesome.com/XXABC1234.js`

We are currently working on a project where an icon picker is essential, and we've created our own custom font awesome icons for this. 

Feels like a great opportunity to get this added.

**Comment by paulcripps** [comment]
> How to add new custom icons ?

I'm up for this all will vote, we really need them, did you find a workaround?

**Comment by brandonkelly** [comment]
There’s a bunch of [prep work](https://github.com/craftcms/cms/blob/5.x/scripts/copyicons.php) that we do to make our kit searchable, and icons are distributed with the app itself as individual SVG files, pulled from the npm package. Repurposing that for a custom kit would be a bit of a lift, and would require you to start adding your kit as an npm dependency that either gets published as an asset bundle, or is exclusively used as `<svg>` tags.
