### ISSUE TITLE
[5.x]: Dropdown field marked as dirty when opening slideout

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#15245]
### Description
In some particular matrix entries, when I open them in a slideout, the first dropdown field gets marked as dirty and the (matrix) entry as `edited`. It doesn't matter if I discard changes or save, this keeps happening whenever I reopen the slideout.

I had this only happen to the production enviroment of a project, and the dev environment was ok. I transfered the prod DB to dev and the issue then also appeared in that (dev) environment. Unfortunately this means that you may not be able to easily reproduce. In that case I can send over some config files etc.

I'm attaching a screen recording: 

https://github.com/craftcms/cms/assets/19857599/60176fdd-1212-4b30-839e-903ec94eaf67

### Steps to reproduce

1. Double click on a matrix field card to open slideout. Close it without editing.

### Expected behavior

Nothing changes.

### Actual behavior

The first dropdown field in the nested entry is marged as dirty, and the entry as `edited`.

### Craft CMS version

 5.2.3

### PHP version

8.3.8

### Database type and version

MySQL 8.0.36

### Installed plugins and versions

Amazon S3 2.2.1
CKEditor 4.1.0
Control Panel Body Classes 3.0.0
Control Panel CSS 3.0.0
CP Field Inspect 2.0.1
Field Manager 4.0.1
Knock Knock 3.0.0
Mailjet Adapter 2.0.1
Palette 5.1.1
Vite 5.0.0
Webhooks 3.1.0

**Comment by i-just** [comment]
Hi @thupsi, I can replicate a part of this, but it’s not the part that allows me to see what’s really going on in your case. Could you please send your database export, `composer.json` and `composer.lock`, to support@craftcms.com so we can dig deeper?

**Comment by thupsi** [comment]
Done! Check your email 🙂

**Comment by i-just** [comment]
Thanks 🙂  Looking into it!

**Comment by i-just** [comment]
Thanks again for reporting and sending over the files. 
I was able to reproduce this on a fresh install and raised a PR. (Details of why this happened are on the PR.)

**Comment by thupsi** [comment]
I _thought_ it might have to do with the focus! Thank you!

**Comment by brandonkelly** [comment]
Craft 4.10.3 and 5.2.4 are out with a fix for this. Thanks again!
