### ISSUE TITLE
[5.x]: Sidebar overlap with entry index in some screen widths

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#15253]
### Description
There's an issue where in some small screen widths, when the sidebar is collapsed by default, but not in mobile mode, the sidebar can overlap with the entry index when scrolling and triggering the sticky header.

<img width="442" alt="image" src="https://github.com/craftcms/cms/assets/19857599/4abc08bd-808c-4928-aa15-4a87b29dba01">

https://github.com/craftcms/cms/assets/19857599/189bdcfc-1f01-498a-9ad0-c2ea7148bc14

### Craft CMS version

5.2.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Craft 5.2.4 is out with a fix for this. Thanks for reporting!
