### ISSUE TITLE
Disappearing Assets

### ISSUE THREAD

**Issue by bluestormdesign** [craftcms/cms#15259]
### Description
I have a files directory with folders of files within. If I drag one folder into the other all files in that folder disappear

### Expected behavior
All files remain in folders when dragged into a different folder.

### Craft CMS version

4.10.2

### PHP version

8.1

### Operating system and version

Ubuntu 22.04.3

### Database type and version

MySQL 8

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch! I’m having trouble replicating this. Could you please provide more information on how to replicate it?

**Comment by bluestormdesign** [comment]
Hi, thanks for looking into this. The file location is S3, not local storage.

Folder structure is like the attached. Some of these have subfolders. If you drag one folder into the other the files disapper.

Thanks
![Screenshot 2024-07-09 at 13 10 48](https://github.com/craftcms/cms/assets/25588084/ffa442f0-706b-4c37-9daa-a3cdf07f6248)

**Comment by brandonkelly** [comment]
What type of filesystem does the volume use?

**Comment by bluestormdesign** [comment]
> What type of filesystem does the volume use?

Amazon S3

**Comment by brandonkelly** [comment]
And you’re not having any issues with new file uploads, correct?

**Comment by bluestormdesign** [comment]
Correct.

**Comment by bluestormdesign** [comment]
> Correct.

So say i have a folder at route level called test-1 with two images in and an other folder at route called text-2 with two images in. I drag test 2 into test 1. In test 1 is now a sub folder called test-2 but no images in side. The original test two folder remains at route with the original two images in.

Thinking more about this, because it's S3 do you think it is anything to do with the policy attached to the bucket?

**Comment by bluestormdesign** [comment]
I can confirm that this issue was caused by the policy attached to the S3 bucket for the volume. Sorry we hadn't spotted this sooner.

**Comment by brandonkelly** [comment]
Glad you got it sorted!
