### ISSUE TITLE
Utilize ElementQuery::setCachedResult() more thoroughly 

### ISSUE THREAD

**Issue by nateiler** [craftcms/cms#1526]
It seems `setCachedResult` should be called if `ElementQuery::all()` makes a database query.  Unless I'm missing something, a DB query is made each time `ElementQuery::all()` is called even if the criteria has not changed.  I'm thinking something along the lines of:

```
/**
 * @inheritdoc
 */
public function all($db = null)
{
    $cachedResult = $this->getCachedResult();

    if ($cachedResult !== null) {
        return $cachedResult;
    }
    
    $elements = parent::all($db);
    
    $this->setCachedResult($elements);

    return $elements;
}
```

**Comment by brandonkelly** [comment]
That’s sortof how it worked in Craft 2, but it leads to a *ton* of unneeded caches taking up space in memory for no reason. So in Craft 3 if you want to cache the results, you should just do it manually by setting the results to a variable.

**Comment by nateiler** [comment]
Got it.  I'll proceed with the assumption that we'll manually set the cache.

Thanks.
