### ISSUE TITLE
[5.x]: GraphQL type name collision

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/cms#15269]
### What happened?

When GraphQL mutation names are generated for nested entries and sections, a collision is possible for `_Draft`s.

Mutations for Matrix field entry drafts omit the `Field` segment, meaning they will receive the same name as the mutation for drafts _in a section that shares a handle with the field_.

https://github.com/craftcms/cms/blob/5.x/src/gql/mutations/Entry.php#L285

## Steps to Reproduce

1. Create an entry type named _Stop_ (with handle `stop`);
1. Create a section named _Tours_ (with handle `tours`) and an entry type named _Tour_ (with handle `tour`) — the naming here is immaterial and doesn’t contribute to the bug… we just need a place to stick the field, semantically;
1. Create a Matrix field named _Stops_ that uses the _Stop_ entry type, and attach it to the _Tour_ entry type’s field layout;
1. Create a section named _Stops_ (also with handle `stops`) that uses the _Stop_ entry type;

(This last step is contrived—most developers are probably _not_ creating deliberately ambiguous content types like this!)

The resulting GraphQL schema would produce these four mutations:

- `save_stops_stop_Entry` — Save a _Stop_ entry to the _Stops_ section
- `save_stops_stop_Draft` — Save a _Stop_ entry draft to the _Stops_ section
- `save_stopsField_stop_Entry` — Save a nested _Stop_ entry into the _Stops_ Matrix field
- `save_stops_stop_Draft`  — Save a nested _Stop_ entry into the _Stops_ Matrix field

The second and third `_Draft` type names are the same! Currently, Craft appears to only acknowledge the latter (or… whichever one is created _second_?)

### Craft CMS version

5.0.0+

**Comment by brandonkelly** [comment]
Fixed for 5.3 (8fdd6e0608f6b1fd9789e43ee2f477fef968ca03).
