### ISSUE TITLE
[5.x]: Entry Condition not working properly on Matrix fields.

### ISSUE THREAD

**Issue by belkin** [craftcms/cms#15260]
### Description
The "Entry Condition" for fields in a Matrix does not work correctly when setting the condition to "Section -> Is one of -> 'Desired section'". This issue was tested on the latest Craft CMS version (5.2.3) and the demo version (europa.museum 5.1.9), both exhibiting the same problem.

### Steps to reproduce

1. Create a Matrix field with several block types.
2. Set an Entry Condition on a field within one of the block types using the following settings:
- Entry Condition -> Section -> Is one of -> "Desired section"
<img width="1199" alt="image" src="https://github.com/craftcms/cms/assets/3419659/0243a48a-eb14-4cb8-aec6-d8de20ec8607">

3. Navigate to a section where the Matrix field is used. The field will not be visible in any section, including the "Desired section" specified in the condition.
<img width="1173" alt="image" src="https://github.com/craftcms/cms/assets/3419659/995297ed-9049-4476-8378-b9a8e306f3ac">

### Expected behavior
The field should be visible only in the selected section when editing an entry.

### Actual behavior
The field does not appear in any section, including the specified "Desired section".

### Craft CMS version

5.2.3

### PHP version

8.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Matrix entries belong to their owner element, not a section, which is why the Section condition rule doesn’t work for them.

I don’t think it would make sense to loosen the condition rule up to include entries whose root-level owner is an entry that belongs to the selected section, for two reasons:

- It would be a breaking change in behavior, as some conditions could be using the same entry type for section entries _and_ Matrix/CKEditor entries, and expecting that the condition rule would exclude the Matrix/CKEditor entries.
- It would open a can of worms, as Matrix/CKEditor fields can be added to other element types besides entries. What if you wanted to show a field based on whether the Matrix field is within a certain category group? Or a certain global set? Etc.

We’ll keep the use case in mind as we explore ways to improve conditions/conditional fields down the road, but in the meantime, I just [added a new event](https://github.com/craftcms/cms/commit/f7bdda8aa749f4fe3a31d4b9a5736f353c8ed761) for Craft 5.3, which you can use to supply your own conditional logic from a custom module:

```php
use craft\base\FieldLayoutComponent;
use craft\elements\Entry;
use craft\events\DefineShowFieldLayoutComponentInFormEvent;
use craft\fieldlayoutelements\CustomField;
use yii\base\Event;

Event::on(
    CustomField::class,
    FieldLayoutComponent::EVENT_DEFINE_SHOW_IN_FORM,
    function (DefineShowFieldLayoutComponentInFormEvent $event) {
        /** @var CustomField $layoutElement */
        $layoutElement = $event->sender;
        if (
            $layoutElement->field->handle === 'narrowWidth' &&
            $event->element instanceof Entry &&
            $event->element->field?->handle === 'contentBlocks'
        ) {
            $owner = $event->element->getOwner();
            if ($owner instanceof Entry) {
                $event->showInForm = $owner->section?->handle === 'exhibits';
            }
        }
    }
);
```

If you want to test that out, you can change your `craftcms/cms` requirement in composer.json to:

```json
"craftcms/cms": "5.3.x-dev as 5.3.0-alpha",
```

Then run `composer update`.

**Comment by mmikkel** [comment]
...I was taking the 5.3.x branch for a spin, and I'm getting the below exception on all element edit pages, which seems related to this change. I apologise for the noise in case this is already on your radar; I'm aware 5.3 isn't even a beta at this point 😌 

```
Error: Typed property craft\base\FieldLayoutComponent::$_layout must not be accessed before initialization in /var/www/html/vendor/craftcms/cms/src/base/FieldLayoutComponent.php:332
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/models/FieldLayout.php(915): craft\base\FieldLayoutComponent->showInForm(Object(craft\elements\Entry))
#1 [internal function]: craft\models\FieldLayout->_elements(Object(Closure), Object(craft\elements\Entry))
#2 /var/www/html/vendor/craftcms/cms/src/models/FieldLayout.php(717): iterator_to_array(Object(Generator))
#3 /var/www/html/vendor/craftcms/cms/src/models/FieldLayout.php(673): craft\models\FieldLayout->_customFields(Object(craft\elements\Entry))
#4 /var/www/html/vendor/craftcms/cms/src/base/Element.php(6055): craft\models\FieldLayout->getVisibleCustomFields(Object(craft\elements\Entry))
#5 /var/www/html/vendor/craftcms/cms/src/base/Element.php(4924): craft\base\Element->fieldLayoutFields(true)
#6 /var/www/html/vendor/craftcms/cms/src/controllers/ElementsController.php(2306): craft\base\Element->setFieldValuesFromRequest('fields')
#7 /var/www/html/vendor/craftcms/cms/src/controllers/ElementsController.php(267): craft\controllers\ElementsController->_applyParamsToElement(Object(craft\elements\Entry))
#8 [internal function]: craft\controllers\ElementsController->actionEdit(Object(craft\elements\Entry), 45)
#9 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#11 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('edit', Array)
#12 /var/www/html/vendor/craftcms/cms/src/web/Application.php(349): yii\base\Module->runAction('elements/edit', Array)
#13 /var/www/html/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('elements/edit', Array)
#14 /var/www/html/vendor/craftcms/cms/src/web/Application.php(317): yii\web\Application->handleRequest(Object(craft\web\Request))
#15 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#16 /var/www/html/web/index.php(12): yii\base\Application->run()
#17 {main}
```

**Comment by mmikkel** [comment]
@brandonkelly On further inspection, the exception seems related to the `craft\debug\Module` module; it only happens if the "Show the debug toolbar in the control panel" admin preference is enabled.

**Comment by brandonkelly** [comment]
@mmikkel Thanks! Fixed via 82524c29a6a23a7258f4b23bb18e61a456454dfa.

**Comment by russback** [comment]
@brandonkelly Finding we're hitting this use case a fair amount now. Would it be practical to have another condition in the UI where you can choose the Owner Entry section (where the layout is attached to an Entry element)?

**Comment by chasegiunta** [comment]
Having the option to choose Owner Entry section and entry type would be incredibly helpful

**Comment by mikesnoeren** [comment]
Hi, has there been any progress on this? Been running into this for a Craft 5.9 project.

**Comment by mmikkel** [comment]
@mikesnoeren You could try creating a generated field `ownerSection` on your nested entry's entry type, with the following template:

```twig
{rootOwner.section.handle|default}
```

Then, you can add an Entry Condition on that generated field, e.g.

[Owner Section] [equal to] [yourOwnerSectionHandle]

**Comment by mikesnoeren** [comment]
@mmikkel That's a good solution, thanks for the idea. Will keep this in mind for the future.

I however ended up going for a slightly modified version of what was suggested by @brandonkelly earlier:
```php
Event::on(
    CustomField::class,
    FieldLayoutComponent::EVENT_DEFINE_SHOW_IN_FORM,
    function (DefineShowFieldLayoutComponentInFormEvent $event) {
        $layoutElement = $event->sender;

        if (
            $layoutElement->field->handle !== 'modal'
            || !$event->element instanceof Entry
        ) {
            return;
        }

        $owner = $event->element->getRootOwner();

        if (
            $owner instanceof Entry
            && $owner->section?->handle === 'modals'
        ) {
            $event->showInForm = false;
        }
    }
);
```
