### ISSUE TITLE
[5.x]: Sidebar toggle broken for several items in 5.2.4

### ISSUE THREAD

**Issue by turnstylerj** [craftcms/cms#15266]
### Description

After updating to Craft 5.2.4, the main sidebar is inconsistently opening for several items (Commerce, SEOmatic, Guide). Seeing the following error in the console:

![2024-06-27 at 16 22 40](https://github.com/craftcms/cms/assets/42223501/e4d36691-2075-439d-b4d2-a184d8434f44)

### Steps to reproduce

1. Update to Craft 5.2.4
2. Open and close/navigate to plugins with collapsible sidebar items

### Expected behavior

Sidebar opens and closes

### Actual behavior

Error is output into console

### Craft CMS version

5.2.4

### PHP version

8.2.19

### Operating system and version

Linux 6.5.0-15-generic

### Database type and version

MySQL 8.0.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

CKEditor 	4.1.0
Colour Swatches 	5.0.0
Control Panel CSS 	3.0.0
Craft Commerce 	5.0.11.1
Default Dashboard 	3.0.0
Element Relations 	3.0.4
Field Manager 	4.0.1
Guide 	4.0.0-beta.1
ImageOptimize 	5.0.2
Image Resizer 	4.0.0
Multi Translator 	2.5.2
Neo 	5.0.4
No-Cache 	3.0.2
PayPal Checkout for Craft Commerce 	3.0.1
Redirects 	5.0.2
Retcon 	3.1.1
SEO 	5.0.4
Servd Assets and Helpers 	4.0.3
Stripe for Craft Commerce 	5.0.1.1

**Comment by turnstylerj** [comment]
The dashboard is also broken in all environments

![2024-06-27 at 16 26 56](https://github.com/craftcms/cms/assets/42223501/5c8f8fcd-e4d5-4510-97cc-2d469cf1e76d)
![2024-06-27 at 16 27 05](https://github.com/craftcms/cms/assets/42223501/10d5325e-7a96-42e7-b0c4-f5ff5c78b720)

**Comment by brandonkelly** [comment]
Doh, thanks for reporting that. Just released 5.2.4.1 with a fix.
