### ISSUE TITLE
[5.x]: asErrorJson() is deprecated but asFailure() does not behave the same

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/cms#15279]
### Description

I'm currently porting some code that was originally written for Craft CMS 3, but updating it to work for Craft CMS 5. I've come to a controller which is using asErrorJson() when a certain query parameter was not present in the request to the controller.

This is the Craft CMS 3 controller code snippet:

```php
$param = $this->request->getQueryParam('paramkey');

if (!$param) {
    return $this->asErrorJson('No param was provided for the request.');
}
```

`asErrorJson()` is marked as deprecated and `asFailure()` is suggested to be used instead. 

However updating the code to use `asFailure()`, does not behave the same. 

When using `asErrorJson()`, a response error is thrown:

```json
{
    "error": "No param was provided for the request."
}
```

When using `asFailure()` a response is not returned. Instead, it appears no response is thrown when using `asFailure()`, which does not catch the error like the above.

I think this might be due to `asFailure()` being related to model validation but `asErrorJson()` being more general. Is there a way to get the equivalent of `asErrorJson()` in Craft CMS 5 without using the deprecated call?

### Steps to reproduce

See code example snippet above to describe the scenario.

### Expected behavior

A response error to be thrown.

### Actual behavior

No response is thrown, appears to be null.

### Craft CMS version

 5.2.4.1

### PHP version

8.2

### Operating system and version

Linux

### Database type and version

MySQL 8

### Image driver and version

N/A

### Installed plugins and versions

None.

**Comment by brandonkelly** [comment]
A response is definitely returned by `asFailure()`; it’s just marked with a `400` status code. So you will need to update your client-side logic to handle non-2xx responses.

Alternatively, if you don’t want to change the response behavior, you can start calling `asJson()` and pass in the `error` key yourself (which is all that `asErrorJson()` was doing):

```php
return $this->asJson([
    'error' => 'No param was provided for the request.',
]);
```

**Comment by jamesmacwhite** [comment]
@brandonkelly Thanks for the info. The main area I was highlighting was when making a HTTP request to the controller when it was hitting the condition to essentially return a response, with `asErrorJson()` it was returning the error, with `asFailure()` it just threw a 404 error, didn't return the message set. I'm aware, that the `asFailure()` doesn't return the error key, but the 404 response seemed odd.

**Comment by brandonkelly** [comment]
@jamesmacwhite Did you delete the `return` statement in the process by chance? You still need to be returning the response:

```php
if (!$param) {
    return $this->asFailure(...);
}
```

**Comment by jamesmacwhite** [comment]
@brandonkelly Nope, I was still returning the result. It is odd. I must be missing something obvious, but if I replace asErrorJson() with asFailure() it just doesn't return a 400 response it seems.

**Comment by brandonkelly** [comment]
Are you 100% sure that that line of code is actually getting executed? Maybe try throwing an exception there instead, and verify that a 500 response comes back.

**Comment by jamesmacwhite** [comment]
100% sure, here's the controller example:

```php
public function actionMyAction(): ?Response
{
  $param = $this->request->getQueryParam('param');
  if (!param) {
      return $this->asFailure('Missing parameter.');
  }
}
```

I've done a `dd()` in the condition where the return statement and confirmed it is being hit. However if I use `asFailure()` the response ends up being null and 200 OK.

Compared to `asErrorJson()` which returns the message, but noticed it's not actually a 400 in checking developer tools console, it's a 200 still...

```php
public function actionMyAction(): ?Response
{
  $param = $this->request->getQueryParam('param');
  if (!param) {
      return $this->asErrorJson('Missing parameter.');
  }
}
```

There's something funky going on with my Craft setup I think...

I could throw a 400 error exception, but I think I'm missing something fundamental, considering the code works on Craft CMS 3.

Ah just noticed the status being 200 is expected per: https://github.com/craftcms/cms/issues/3890, but the mystery remains on the asFailure() message not being returned.

**Comment by brandonkelly** [comment]
> Compared to `asErrorJson()` which returns the message, but noticed it's not actually a 400 in checking developer tools console, it's a 200 still...

That’s expected; `asErrorJson()` has always returned a 200 response, which is part of the reason we’ve deprecated it and stopped using it in favor of `asFailure()`.

What happens if you do this:

```php
return $this->asErrorJson('Missing parameter.')->setStatusCode(400);
```

**Comment by jamesmacwhite** [comment]
That works and throws a 400. I know there's also a hack you can use an event to make it a 400, but changing setStatusCode() is fine.

A bit more debugging, dumping:

`dd($this->asErrorJson('Missing Parameter'))` returns:

```
craft\web\Response {#226 ▼
  -_events: []
  -_eventWildcards: []
  -_behaviors: null
  +exitStatus: 0
  +format: "json"
  +acceptMimeType: null
  +acceptParams: []
  +formatters: array:5 [▶]
  +data: array:1 [▶]
  +content: null
  +stream: null
  +charset: "UTF-8"
  +statusText: "OK"
  +version: "1.1"
  +isSent: false
  -_statusCode: 200
  -_headers: yii\web\HeaderCollection {#225 ▶}
  -_cookies: null
  +defaultFormatters: []
  -_isPrepared: false
}
```

`dd($this->asFailure('Missing parameter'))` returns

```
null
```

This is in a controller for a site request. I'm wondering if that has anything to do with the behaviour being different?

**Comment by brandonkelly** [comment]
OK, so the issue is that there’s no `Accept: application/json` header, which is required for `asFailure()` to return a JSON response.

When you say this is a site request, do you mean you’re accessing the controller action directly from the main browser window? If so, and you are expecting to get a JSON response, and just have that be output in the browser window, you’ll need to call `return $this->asJson()` yourself, and pass an array with an `error` key [as suggested earlier](https://github.com/craftcms/cms/issues/15279#issuecomment-2203206345). You can optionally chain on `->setStatusCode(400)` if you want a 400 response code, too.

```php
return $this->asJson([
    'error' => 'No param was provided for the request.',
])->setStatusCode(400);
```

Or, if this **is** an Ajax request, then you just need to start sending an `Accept: application/json` header.

```js
const response = await fetch(url, {
  headers: {
    accept: 'application/json',
  },
  // ...
});
```

**Comment by jamesmacwhite** [comment]
@brandonkelly Ah that's what I'm missing my pattern is off since the changes. `asJson()` is fine with passing an error key to replicate the same behaviour that asErrorJson() would do. Thanks for taking the time to explain and sticking with me!

**Comment by brandonkelly** [comment]
Glad that helped! Sorry, I should have thought about that difference between `asFailure()` and `asJson()`/`asErrorJson()` earlier 🤦‍♂️
