### ISSUE TITLE
[5.2.5]: Broken verification link in activation mail

### ISSUE THREAD

**Issue by cookie10codes** [craftcms/cms#15289]
### Description
When a user registers on my frontend, the user gets an activation mail but the link is broken. It says `</verifyemail?code=TKS5cZCpmbWlAQFlG4Wov7L6vLX3ciUg&id=d58db635-26ef-4f42-840e-91f5bdfa8650>`

The strange thing is, when a user submits on the password forgot form, the link shows as should.

### Craft CMS version

5.2.5 Pro

### PHP version

8.3.7

### Operating system and version

Linux 5.15.0-1028-aws

### Database type and version

MySQL 8.0.37

**Comment by brandonkelly** [comment]
In your `systemmessages` table, do you have a row(s) where the key is `account_activation`? What is the `body` value?

**Comment by cookie10codes** [comment]
@brandonkelly sorry for my late reply, I was on holiday. Seems the wrong system address was set. Weirdly, it only was an issue on the activation URL and not on the password reset.

But it's fixed
