### ISSUE TITLE
[5.2.4.1]: Unable to create passkey on Windows Chrome

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#15280]
### Description
Not sure from what version this started happening, but I'm not able anymore to create passkeys on Windows Chrome. Edge and Firefox work as expected.

### Steps to reproduce

1. Go to `My account` -> `Passkeys` and click `add a passkey`.
2. Fill your password in the pop up.
3. Enter the name for the passkey in the system dialog.

### Expected behavior

The passkey is created.

### Actual behavior

An error notification appears with the message: `
The operation either timed out or was not allowed. See: https://www.w3.org/TR/webauthn-2/#sctn-privacy-considerations-client.
`

### Craft CMS version

5.2.4.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Just tested this on Windows/Edge and it worked fine. Do you mind testing in Edge and seeing if that works for you? If so then I’ll suck it up and install Chrome to look into it further.

**Comment by thupsi** [comment]
Yes, it's working fine in Edge and Firefox. You missed that in my original description, but it's ok 🙂

**Comment by brandonkelly** [comment]
Doh, yeah missed that. OK, will test Chrome…

**Comment by brandonkelly** [comment]
@thupsi Just tested on Chrome/Windows using 1Password as the passkey provider, and it worked fine, and I’m able to login with the passkey.

What passkey provider does Chrome use for you, when you sign into other sites with passkeys?

**Comment by thupsi** [comment]
Hi @brandonkelly, sorry for the late response.

It seems to have been an issue on my specific Windows install: I cleared all related passkeys from within the Windows UI and that seems to have fixed it. 

I apologize for the false alarm!
