### ISSUE TITLE
Element::saveEntry takes twice the time, if validation set _off_...

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1529]
### Description
Beginning a raft of potential speedups for the slowest task in my database agent, I just for fun set the runValidation flag ofo Element::saveElement() to false. Consistently, time for adding a set of 50 medium-size entries to Craft went from 6-8 seconds to 12-16 seconds(!). All on a laptop.

However, I think it actually is doing validations when the flag is true. Craft 3 seems a little more persnickety there, and caught a record that attempted a null title. Stack trace says, anyway, and  it is possible my helper failed so that this could happen, with this very inconsistent customer dataset. So a good catch to improve that. This factoid only to say I think validations themselves run ok, in spite of the reversed speed.

### Steps to reproduce

1. Well, as above
2. Try timing to save a sized batch of new Entries, with Element::saveElement($entry, true);.
3. Try timing to save a sized batch of new Entries, with Element::saveElement($entry, false);.
4. Note the timings seem reversed.

Code fragment:

```		try
		{
			if (!Craft::$app->elements->saveElement($entry, true))
			{
                            // etc.
```
### Additional info

PHP version	7.1.2-3+deb.sury.orgxenial+1
Database driver & version	MySQL 5.7.17-0ubuntu0.16.04.1
Image driver & version	GD 7.1.2-3+deb.sury.orgxenial+1
Craft edition & version	Craft Personal 3.0.0-beta.7
Yii version	2.0.11.2
Twig version	2.1.0
Guzzle version	6.2.1
Imagine version	0.7-dev
Plugins: some, including the StandardsAgent c3 upgrade being tested

**Comment by narration-sd** [comment]
Closing this, as it was a canard -- which you may have suspected.

The problem here was interesting. Craft 3 and php 7.1 is fast -- so fast, that some delay sleepsI put in to regularize the human presentation of the agent could become dominant. And then, the positioning of the sleep call determines how long it will actually be. Changing that validations were or weren't wrong shifted the delay to become more apparent for the push phase of the agent. With the delays smaller or taken out, indeed the maximum 50 Entry saves in a cycle are very fast, validations or not. Finis.

**Comment by brandonkelly** [comment]
Just checked on my machine, and verified validation definitely adds more processing time, as expected, and the opposite of what this issue suggests.

Tested resaving all entries with and without validation, on a Happy Lager install.

- With validation: 3.408s
- Without validation: 2.715s

Maybe you had an active Xdebug session when running without validation? That tends to slow everything down quite a bit.

**Comment by narration-sd** [comment]
Brandon, thanks. 

Xdebug was in there, but  I think not active. A more complicating factor was actually some Unix sleeps I had in there from long ago to slow down the rapid task segments so that they would remain visible on your task notifier. These led to a combination of self-synchronization and pushing over the edge of successive time blocks, so that each phase after the first gained an extra second of dead time.  At least this was a big contributor.

It's working now as you see it, and as one would suspect. Thanks again...

**Comment by narration-sd** [comment]
Just so you see it, if reading only emails: Also in there -- devMode logging, use of debug bar for doing the timing that time, etc..
