### ISSUE TITLE
[5.x]: Element card thumbnail image disappears after saving parent entry

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#15299]
### Description
This will probably be difficult to reproduce, again (Sorry about that!) 🙂. I'm facing a weird issue where I'm saving an entry, and the card thumbnail image from a certain entry type in a matrix field goes missing. 

Here's a screen recording:

https://github.com/craftcms/cms/assets/19857599/3ba9769e-9123-492f-88c9-6709b0b8aab6

Here are the settings of this martix field:

![image](https://github.com/craftcms/cms/assets/19857599/58459c42-ad82-4390-9ec7-79bf3a73532f)

And the settings of the entry type of the entry that is represented by the card:

![image](https://github.com/craftcms/cms/assets/19857599/3b7ab074-5e24-4f6c-85ad-0bb70b92f695)

### Craft CMS version

5.2.5

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I was able to reproduce this one, and I raised a PR.

**Comment by brandonkelly** [comment]
Craft 5.2.6 is out now with that fix. Thanks again!
