### ISSUE TITLE
[5.x]: Cannot delete some entries. Error: Invalid owner ID

### ISSUE THREAD

**Issue by handplant** [craftcms/cms#15290]
### What happened?

I have a multisite with three sites. In the primary site, I cannot delete some entries as admin. I get the error: Invalid owner ID. It also does not work via a console command. The problem occurs both locally and in production.

How can I fix this?

![Bildschirmfoto 2024-07-03 um 13 28 50](https://github.com/craftcms/cms/assets/2598962/b9785182-4a38-45bd-be56-83dab5af09d6)

### Craft CMS version

Craft Pro 5.2.5

### PHP version

8.2.20

### Database type and version

MySQL 8.3.0

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Are these top-level section entries within the control panel? Or within a Matrix field?

**Comment by handplant** [comment]
Yes, it is a top-level section entry type.

![Bildschirmfoto 2024-07-04 um 08 30 16](https://github.com/craftcms/cms/assets/2598962/0a6f76d1-dc7c-4b98-9618-a28b875ab9d7)
![Bildschirmfoto 2024-07-04 um 08 30 32](https://github.com/craftcms/cms/assets/2598962/28c10d15-f6ec-49a0-b3b4-7e17c9e50909)

**Comment by brandonkelly** [comment]
It looks like somehow, the entry has its `primaryOwnerId` attribute set to itself. That attribute should only be set for nested elements like Matrix entries.

You can clear it out if you run the following SQL statement:

```sql
UPDATE entries SET primaryOwnerId = null WHERE id = 2811;
```

Not sure how it would have gotten into that state to begin with, besides some manual fiddling with DB data.

**Comment by handplant** [comment]
Hello Brandon,

I checked the database. The entries that cannot be deleted already have `primaryOwnerId = null`.

![Bildschirmfoto 2024-07-08 um 09 59 41](https://github.com/craftcms/cms/assets/2598962/50be7777-99f8-4fc0-85c8-b14ef7b5e7ec)

**Comment by brandonkelly** [comment]
Any chance you can send your database backup and Composer files into support@craftcms.com?

**Comment by handplant** [comment]
I have sent the data to the support team. Thank you.

**Comment by handplant** [comment]
Are there any updates? I have been waiting for 3 weeks now and keep getting put off via email.

**Comment by brandonkelly** [comment]
@handplant Looks like we’ve been waiting on you to send in a fresh production DB backup, which was requested two weeks ago.

**Comment by handplant** [comment]
I sent the data by email on July 9th. Since then, I've been in contact with Oli and Tommy via email. The last email was: "I'll check in with Brandon to see if there's anything to share and get back to you."

**Comment by brandonkelly** [comment]
Apologies… Oli did in fact DM me about this on the 9th, and I guess I completely missed it 😞 

He was able to track down the issue, and it’s now fixed for the next release.

You can get the fix early by changing your `craftcms/cms` requirement in composer.json to;

```json
"craftcms/cms": "5.x-dev as 5.2.9",
```

or if you are running the 5.3 beta:

```json
"craftcms/cms": "5.3.x-dev as 5.3.0-beta.1",
```

then run `composer update`.

**Comment by handplant** [comment]
No problem, Brandon. Thank you for fixing it.

**Comment by brandonkelly** [comment]
Craft 5.2.10 is out with that fix. Thanks for bearing with me!
