### ISSUE TITLE
[5.x]: Sorting bugs in entries index

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#15297]
### Description
While trying to sort some entries by a custom field of `number` type I came across the following:

1. The sorting was inorrect when sorting by a number field:

![image](https://github.com/craftcms/cms/assets/159689562/fbbeaac8-279e-4cc1-95d4-ba2206844249)

2. The sorting was still incorrect when switching to a plain text field (either with textual or numeric content):

![image](https://github.com/craftcms/cms/assets/159689562/8c28c74d-3d78-497b-bb92-a8452de8c9bb)

3. The sorting changes when I click `edit` to bulk edit those entries:

![image](https://github.com/craftcms/cms/assets/159689562/7b7a07e6-b39c-415f-8e58-d72923e60b61)

### Craft CMS version

5.2.5

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi @thupsi, thanks for getting in touch! I’m having trouble replicating this. Any chance you could send your composer files and database export to support@craftcms.com so that we can dig deeper?

**Comment by thupsi** [comment]
Ok, I just sent them, thanks!

**Comment by i-just** [comment]
Thanks! The trick to replicating was that entries have to be singles, and I tried this with channel and structure. I’m looking into it!

**Comment by brandonkelly** [comment]
Fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 5.2.6 is out now with that fix. Thanks for reporting!
