### ISSUE TITLE
Make 'author' field handle a reserved word

### ISSUE THREAD

**Issue by JayBox325** [craftcms/cms#1530]
### Description
I set up an author field on a build which should have been useable as `article.author`, as my authors field relates to a Team Members channel that isn't linked into the logged in user. But when I tried to use it in the template `article.author` was returning 'Admin' on the front end.

I feel `author` should be on the list of reserved words if it is being used by Craft out the box.

**Comment by takobell** [comment]
A duplicate of https://github.com/craftcms/cms/issues/918.  Feel free to comment/upvote on that issue.
