### ISSUE TITLE
[5.x]: `ElementHelper::isDraft` not working for nested elements

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#15303]
### What happened?

When a nested entry in a matrix field is modified, a draft is automatically created. When the draft is saved, however, calling `ElementHelper::isDraft($element)` returns `false`.

This appears to be caused due to `getIsDraft()` being called on the root element, rather than on the element itself.

https://github.com/craftcms/cms/blob/37356eba5ce40938bcf3cc907ca4efedf78697c7/src/helpers/ElementHelper.php#L490

I imagine this could be solved as follows:

```php
return $element->getIsDraft() || static::rootElement($element)->getIsDraft();
```

Note that the `ElementHelper::isDraftOrRevision()` and possibly also the `ElementHelper::isRevision()` method should be updated accordingly.

### Steps to reproduce

1. Listen for a save event on a nested entry in a matrix field.
2. Modify the nested entry so that it automatically creates a draft (without hitting the save button).
3. Check the value of `ElementHelper::isDraft($element)`.

### Expected behavior

`ElementHelper::isDraft($element)` should return `true`.

### Actual behavior

`ElementHelper::isDraft($element)` returns `false`.

### Craft CMS version

5.2.5

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next Craft 4 and 5 releases.

**Comment by brandonkelly** [comment]
Craft 4.10.5 and 5.2.6 are out now with that fix. Thanks again!
