### ISSUE TITLE
[5.x]: When customizing sources "Delete heading" has not a pointer when hovering

### ISSUE THREAD

**Issue by webkp** [craftcms/cms#15317]
### Description

"Delete heading" has not a pointer when hovering.
Tested with Chrome and Firefox

### Steps to reproduce

![image](https://github.com/craftcms/cms/assets/11754639/8b477215-7dd4-439e-a265-500e41aa5274)

### Expected behavior

Seeing a pointer when hovering "Delete heading"

### Actual behavior
"Delete heading" has not a pointer when hovering.

### Craft CMS version

5.2.5

### Installed plugins and versions

- CKEditor	4.1.0
- CP Field Inspect	2.0.1
- Expanded Singles	3.0.0
- fortrabbit Object Storage Volume	4.0.0
- Hyper	2.0.2
- Vite	5.0.0

**Comment by brianjhanson** [comment]
Thanks for reporting! I've opened https://github.com/craftcms/cms/pull/15318 to address this.

**Comment by brandonkelly** [comment]
Craft 5.2.6 is out now with that fix. Thanks again!
