### ISSUE TITLE
[5.x]: Structure max level limit ignored when dragging collapsed structure

### ISSUE THREAD

**Issue by rogerdawkins** [craftcms/cms#15310]
### Description
NOTE: This issue affects Craft 4 and Craft 5

I have created a Structure with Max Levels set to 2. If a top level entry (level 1) has a child entry it should not be possible to drag it below another level 2 item as it will generate a third level. As per the image below if Top B is dragged below Top A it is blocked correctly.

<img width="558" alt="Screenshot 2024-07-05 at 18 22 44" src="https://github.com/craftcms/cms/assets/42376821/995a9eec-8f4e-4a98-932e-7f0ee81018af">

However, if on the above scenario, the Top A entry is collapsed, as per the image below, then it can be moved.

<img width="527" alt="Screenshot 2024-07-05 at 18 29 58" src="https://github.com/craftcms/cms/assets/42376821/c1e31681-893b-4080-b99c-14bbe9ab9fc7">

This then results in a Structure that is 3 levels deep which should not be allowed. Subsequently a 3 levels collapsed structure can be dragged again to create a 4 level deep structure, etc.

<img width="575" alt="Screenshot 2024-07-05 at 18 31 58" src="https://github.com/craftcms/cms/assets/42376821/7cc4a466-83b8-4db3-888a-61de2a60626c">

### Steps to reproduce

1. Create a Structure with Max Levels = 2
2. Follow the images above to reproduce the issue.

### Expected behavior
It should not be possible to create a 3 level deep structure by dragging. The Move should be blocked.

### Actual behavior
Multiple levels can be created by dragging a collapsed structure.

### Craft CMS version

5.2.5

### PHP version

8.2.20

### Operating system and version

Linux 6.5.0-42-generic

### Database type and version

MySQL 8.0.36

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next Craft 4 and 5 releases.

**Comment by brandonkelly** [comment]
Craft 4.10.5 and 5.2.6 are out now with that fix. Thanks again!
