### ISSUE TITLE
Plugins cause missing translations file errors

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#1531]
### Description

Craft throws an error if a plugin is installed that doesn’t come with a translations file for the language used in the CP.

> The message file for category 'assetmetadata' does not exist:
> /Users/Christian/Dev/craft-assetmetadata/src/translations/de/assetmetadata.php

### Additional info

- Craft version: 3.0.0-beta.7
- PHP version: 7.0.15
- Database driver & version: MySQL / MariaDB 10.1.21
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Not able to reproduce that error. Can you tell me more?

- Is this in the CP or front-end?
- What is the user’s preferred language (if CP) or the site’s language (if front-end)?
- What is the plugin’s `sourceLanguage` set to?
- Which languages does the plugin provide translations for (if any)?

**Comment by carlcs** [comment]
I just noticed that it’s not only a problem with plugin translation categories as I am also getting error for the `site` category.

> The message file for category 'site' does not exist: /Users/Christian/Dev/t9ntest/translations/de/site.php

To rule out any issues with my Craft 3 test install, I reproduced the error on a fresh installation running beta 7. Here’s what I did:

- In the installer I selected "en" language for the primary site.
- Created a new site with "de" language.
- Edited my user account to use German / "de" as the "Preferred Language".

The above was enough to reproduce the error in the CP. But let me answer your questions real quick.

- Error is in the CP
- "Preferred Language" is "de"
- I am not setting a `sourceLanguage`, so plugin uses the "en_us" default
- The plugin does not provide any translations

**Comment by brandonkelly** [comment]
So to be clear you are saying you can reproduce it without any plugins installed? Which page in the CP are you getting this error?

**Comment by carlcs** [comment]
Sorry, just noticed that I didn't say that it's just an error log in the debug toolbar. And it gets logged on any CP page.

**Comment by brandonkelly** [comment]
Ahhhh, yes this is known. And I think, warranted? Seems like something you’d want to know, especially on the front end, but in the Control Panel too, as a constant reminder to plugin developers that they should be translating their plugins.

The one exception is the errors about missing `site` translations in the Control Panel. Basically any user-defined Control Panel strings (e.g. section names) are translated with the `site` category. But maybe it would be better to move those to something like `cp`, and we could explicitly check for that category and skip the error log in that one case. Thoughts?

**Comment by carlcs** [comment]
Well, if it would only be shown to the plugin developers, I would agree with what you said. But as a plugin user, I can't really do much about it and I am constantly shown the red error indicator in the toolbar.

It would be nice if plugins did support more languages, but there are many plugins which are only used by admins and translated instructions and settings pages are not really necessary. P&T’ Contac Form plugin is a good example.

**Comment by brandonkelly** [comment]
True, nothing you can do about it as an end user. We are working to make it easier and cheaper for plugins to support translations, but not realistic to expect every plugin to be translated into every language.

**Comment by nilsnh** [comment]
Has there been any development on this issue? I just installed an [admin bar plugin](https://github.com/wbrowar/craft-3-adminbar) and then got this error in the dashboard:

```
Invalid Configuration – yii\base\InvalidConfigException
Unable to locate message source for category 'adminbar'.
```

We need the dashboard locale to be Norwegian but we do not need this plugin to be in Norwegian. This is a showstopper for us at the moment. 

Is there a way to define a general fallback locale hierarchy? Then, craft could try the plugins against 

1. Language 1
2. Language 2
3. Finally, try finding the first and best plugin locale and show that.

?

**Comment by carlcs** [comment]
@nilsnh I don’t think your error has anything to do with the issue discussed here. You’re likely seeing this because Admin Bar is not yet (fully) compatible with beta version 20 and above, see https://github.com/wbrowar/craft-3-adminbar/pull/3

**Comment by neris** [comment]
Just to let you guys know, and also to bump the issue a little, this is really a problem in production. Logs get flooded by the `The message file for category '...' does not exist` errors and log files became absolutely useless. I mean, a new entry is being created in the log file for each request. On a relatively active website our error logs are being stored for 6 hours max (literally right now we have the oldest entry in the oldest rotated log file dated 6 hours back from the current time). So now we have to set up external log system to just be able to see yesterday's error logs.

I don't think this is acceptable, the easiest solution I can think of is log those warnings in a different file, don't just dump everything into poor `web.log`. Or at least log these messages only if the dev mode is on, but not in production!

**Comment by brandonkelly** [comment]
@neris Yeah I can see how that would be annoying. As of the next release we won’t log those errors when Dev Mode is disabled.

**Comment by brandonkelly** [comment]
@patrikalienus Feel free to open a new [discussion](https://github.com/craftcms/cms/discussions/new?category=ideas) about it and we can consider better ways to mitigate it.
