### ISSUE TITLE
[5.x]: Poor contrast for selected entry

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#15315]
### Description

In entry modals, selecting an entry results in a poor contrast between the dark background and the dark title:

![entry-modal-selection](https://github.com/craftcms/cms/assets/10146880/d8b4b194-3e9d-4752-aaa4-943c770f4682)

The title _Allgemein_ is barely readable. In this case, the entry type has the color _Yellow_, but this happens with all colors.

### Steps to reproduce

1. Select an entry in an entry modal.

### Expected behavior

The title should always be clearly readable and have enough contrast.

### Actual behavior

Contrast is poor.

### Craft CMS version

5.2.5

### PHP version

8.3

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.2.7 is out with that fix. Thanks again!
