### ISSUE TITLE
[5.x]: Poor contrast for field handle in field condition builder on hover

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#15316]
### Description

The field layout builder shows field handles in the dropdown for entry conditions as long as the user has the option to show field handles enabled. When an option is hovered, the title of the option is inverted to contrast with the hover background, but the field handle is not, resulting in poor contrast:

![condition-normal](https://github.com/craftcms/cms/assets/10146880/75d34bda-3c6e-43f5-9bc5-f22735086bba)

![condition-hover](https://github.com/craftcms/cms/assets/10146880/b5ae3858-1665-456e-9368-9719d724abad)

### Steps to reproduce

1. Set the user account to show field handles.
2. Hover over a field in a field condition selection dropdown.

### Expected behavior

The label should always be readable.

### Actual behavior

The label is hard to read on hover.

### Craft CMS version

5.2.5

### PHP version

8.3

### Installed plugins and versions

-

**Comment by brianjhanson** [comment]
Thanks for reporting! I've opened #15319 to address this.

**Comment by brandonkelly** [comment]
Craft 5.2.6 is out now with that fix. Thanks again!
