### ISSUE TITLE
[5.x]: Deleting fields that other fields have conditions on causes errors

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#15328]
### Description

In the field layout editor, deleting a field causes issues if you have another field that has a condition that depends on the deleted field. After deleting the field, double-clicking the field with the condition (or using `… → Settings`) shows an error notification:

> Invalid field layout element UUID: <uid>

![invalid-field-layout-element](https://github.com/craftcms/cms/assets/10146880/c852617a-512f-4879-af18-ede6a83e2965)

### Steps to reproduce

1. Add two fields to an entry field layout.
2. In the settings of the second field, add any condition that points to the first field.
3. Delete the first field and save the field layout.
4. Try to open the settings for the second field.

### Expected behavior

Deleting a field should either:

- automatically delete any conditions that other fields have in relation to the deleted field, and display a corresponding warning/info message.
- prevent the deletion of the field until all conditions that depend on the field are removed manually.

### Actual behavior

The field layout ends up in an erroneous state with no clear path to recover from the error.

### Craft CMS version

5.2.5

### PHP version

8.3

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 5.2.6 is out now with that fix. Thanks again!

**Comment by MoritzLost** [comment]
@brandonkelly Thanks, Brandon!
