### ISSUE TITLE
[5.x]: Checkbox functionality regression

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#15326]
### Description
In Craft 4, when working with a matrix field, you used to be able to click the checkbox for a block, then hit `ctral+a` to select all of the blocks on the entry. This allowed you to disable all blocks at once, or collapse them all at once etc.

In Craft 5, clicking a block's checkbox, then pressing `ctrl+a` just selects all the text on the page.

### Steps to reproduce
1. Click a matrix block's checkbox, then press `ctrl+a` (or mac equivalent)

### Expected behavior
Should select all the other blocks in that Matrix field

### Actual behavior
Selects all the text in the browser window

### Craft CMS version

5.2.5

### PHP version

8.2.20

### Operating system and version

Windows 11, Chrome

### Database type and version

MySQL 8

### Installed plugins and versions

- CKEditor

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just brought <kbd>Command</kbd>/<kbd>Ctrl</kbd> + <kbd>A</kbd> support back for Craft 5.3 (#15330).

**Comment by darylknight** [comment]
Awesome, thank you :)
