### ISSUE TITLE
[4.x]: Image 'Preview' and 'Edit image' is not working correctly with Imgix

### ISSUE THREAD

**Issue by nodoxi** [craftcms/cms#15327]
### Description

After editing an image using the built-in Editor in Craft CMS, the 'Preview' and Editor continue to display the old version of the image, despite successful edits.
I use Imgix and purge image after resaving asset.
![1](https://github.com/craftcms/cms/assets/2776595/bfde4ad0-ca35-415a-8d23-24ded47d2b33)

### Steps to reproduce

1. Upload an image on Local filesystem where public URL is set through Imgix.
2. Open the image in the built-in Editor
3. Make changes to the image and save
4. Attempt to re-edit the same image

### Expected behavior
The Editor and Preview should display the most recent version of the edited image without any caching.

### Actual behavior
- The Editor and Preview show the old, unedited version of the image.
- However, when clicking 'Open image in new tab' in the Preview, the correct (edited) version of the image is displayed.
![image](https://github.com/craftcms/cms/assets/2776595/ddcd4183-98a7-41df-854f-12c080845995)

### Craft CMS version

4.9.5

### PHP version

8.2

**Comment by i-just** [comment]
Hi, thanks for getting in touch. You mentioned that you “purge image after resaving asset” - do you also ensure that all the transformed images are refreshed in Imgix?

While testing this:
- I created a local filesystem with the Base URL set to the imgix source URL and the Base Path set to my local folder. I also created an Asset Volume that uses this Filesystem and has a Transform Filesystem set to “Same as asset filesystem.”
- I uploaded an image to the volume and checked that it and its control panel transform were showing in the imgix. 
- Then, I edited this image via Craft’s native “Edit image” feature and saved it. At this point, I see the “old” image in the Control Panel and imgix. 
- If I purge the image in Imgix (and wait for that request to complete successfully), then clicking “Edit image” brings up the “new” (correct) image, but the thumbnails are still “old”. 
- I have to purge/refresh the transformed images, too to have them show as updated in the Control Panel. 

Is that what you’re experiencing too?

**Comment by nodoxi** [comment]
#Is that what you’re experiencing too?

No.
After purging and waiting - clicking "Edit image" brings up the "old" image.

I think I fixed it by changing Imgix settings.
Now it works as intended.
