### ISSUE TITLE
[4.10.4]: Select all not working on asset slide out panel in entry

### ISSUE THREAD

**Issue by yeboJoseph** [craftcms/cms#15325]
### What happened?

After clicking on an asset field to edit the image, I tried to select all to copy to sites but it didn't select all. Works as expected when I'm in Assets. 
<img width="1308" alt="Screen Shot 2024-07-09 at 22 51 56" src="https://github.com/craftcms/cms/assets/71687785/fa0600be-75ef-4e5e-afe4-a58781e8be04">

### Craft CMS version

4.10.4

### PHP version

8.1.28

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
“Copy to side” isn’t a native Craft feature, so you’ll need to figure out which plugin is providing it, and report it there.
