### ISSUE TITLE
[5.x]: Elements won't autocomplete customfields after first field in PHPStorm

### ISSUE THREAD

**Issue by myleshyson** [craftcms/cms#15336]
### Description
Not sure if this is a bug per se, but would be nice to address. Been noticing that custom fields won't autocomplete after the first call even though they have a "static" return type in the `CustomFieldBehavior`. 

I noticed [this](https://github.com/craftcms/cms/commit/46bb9edda436b6dc6851b263fedbb5895e63edd1) commit switched the method return types back from `\$this` to `static`. 

When testing locally if I use `self` instead of `static` i'm able to chain just fine.

I'm using PHPStorm 2024.1.4

### Steps to reproduce

1. Open up a craft installation in php storm.
2. Type the following: 
```php
$entry = new Entry();
$entry->someField('value')->anotherField('value');
```

### Expected behavior
`anotherField` should show up in the method completion window.

### Actual behavior
after typing `someField`, nothing else shows up in the completion window.

### Craft CMS version

5.2.4.1

### PHP version

8.2

**Comment by brandonkelly** [comment]
I’m able to reproduce this. Even `$this` isn’t working quite right though – PhpStorm thinks the `CustomFieldBehavior` instance will be returned in that case, rather than the element.

Reported to JetBrains: https://youtrack.jetbrains.com/issue/WI-78254/static-and-this-return-types-not-working-properly-in-mixins

**Comment by brandonkelly** [comment]
On second look, `$this` is working for me now, so it must have been a fluke that it wasn’t. Switched to that for the next Craft 4 and 5 releases.

**Comment by brandonkelly** [comment]
Craft 4.10.6 and 5.2.7 are out now with that change. Thanks for pointing it out!
