### ISSUE TITLE
[5.x]: Two-step verification set-up key has extra whitespace at the end when copied

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/cms#15349]
### Description

When being provided a seed for two-step verification to input into an authenticator app, if using the setup key, copying this either through the copy button or manually in the field itself, contains whitespace at the end of the value. While I think many authenticator apps will be able to handle this and remove the input, it may be worth ensuring there is no extra data in setup key value.

### Steps to reproduce

1. Start the two-step verification process
2. Copy the setup key value using either the copy button or manually.

### Expected behavior

No whitespace to be present, the last character of the setup key should be the end of the value.

### Actual behavior

Whitespace is copied from the provided value.

### Craft CMS version

5.2.6 Solo

### PHP version

PHP 8.3

### Database type and version

MySQL 8

**Comment by brandonkelly** [comment]
Fixed for the next release, thanks.

**Comment by jamesmacwhite** [comment]
Thank you!
