### ISSUE TITLE
[5.x]: Adding Two-Step Verification with a Permissions-Policy that does not allow synchronous requests

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/cms#15348]
### Description

When attempting to enable two-step verification on a production environment, when verifying a one-time code from the generated seed, the verify action did not provide any success or fail message and returned back to the user screen with the two-step verification option showing as "set-up".

Looking in the console, there were two errors raised, one around synchronous requests being blocked by the Permissions-Policy set and another related to Uncaught Type error.

> jquery.js?v=1720878074:2  [Violation] Permissions policy violation: Synchronous requests are disabled by permissions policy.
send @ jquery.js?v=1720878074:2
ajax @ jquery.js?v=1720878074:2
T._evalUrl @ jquery.js?v=1720878074:2
_e @ jquery.js?v=1720878074:2
append @ jquery.js?v=1720878074:2
(anonymous) @ Craft.js:1973
u @ Craft.js:2
(anonymous) @ Craft.js:2
(anonymous) @ Craft.js:2
as @ Craft.js:2
s @ Craft.js:2
(anonymous) @ Craft.js:2
(anonymous) @ Craft.js:2
(anonymous) @ Craft.js:1974
(anonymous) @ Craft.js:1993
u @ Craft.js:2
(anonymous) @ Craft.js:2
(anonymous) @ Craft.js:2
as @ Craft.js:2
s @ Craft.js:2
(anonymous) @ Craft.js:2
(anonymous) @ Craft.js:2
(anonymous) @ Craft.js:1994
(anonymous) @ AuthMethodSetup.js:51
h @ AuthMethodSetup.js:2
(anonymous) @ AuthMethodSetup.js:2
(anonymous) @ AuthMethodSetup.js:2
n @ AuthMethodSetup.js:2
s @ AuthMethodSetup.js:2
Promise.then (async)
n @ AuthMethodSetup.js:2
s @ AuthMethodSetup.js:2
(anonymous) @ AuthMethodSetup.js:2
(anonymous) @ AuthMethodSetup.js:2
(anonymous) @ AuthMethodSetup.js:68
Promise.then (async)
(anonymous) @ AuthMethodSetup.js:48
onHide @ ElevatedSessionManager.js:117
onHide @ Modal.js:219
hide @ Modal.js:214
onLogin @ ElevatedSessionManager.js:104
(anonymous) @ LoginForm.js:167
Promise.then (async)
onSubmit @ LoginForm.js:162
(anonymous) @ Base.js:162
o @ jquery.js?v=1720878074:2
dispatch @ jquery.js?v=1720878074:2
v.handle @ jquery.js?v=1720878074:2

> VM2264:8  Uncaught TypeError: Cannot read properties of undefined (reading 'METHOD')
    at <anonymous>:8:44
    at m (jquery.js?v=1720878074:2:867)
    at _e (jquery.js?v=1720878074:2:46232)
    at T.fn.init.append (jquery.js?v=1720878074:2:47441)
    at Craft.js:1973:13
    at u (Craft.js:2:1)
    at Generator.<anonymous> (Craft.js:2:1)
    at Generator.next (Craft.js:2:1)
    at as (Craft.js:2:1)
    at s (Craft.js:2:1)

I don't know if there's a more friendly way to identify this, given I had to go into Developer Tools to get an idea to know something was wrong.

### Expected behavior

Some form of error to indicate an issue.

### Actual behavior

Fails silently.

### Craft CMS version

5.2.6 Solo

### PHP version

8.3

### Database type and version

MySQL 8

**Comment by brandonkelly** [comment]
What is the `Permissions-Policy` header value being sent with control panel requests?

**Comment by jamesmacwhite** [comment]
@brandonkelly It was due to not including `sync-xhr` with self i.e `sync-xhr=(self)`, which is fine. The issue is more of a UI/UX one where by there was no obvious error/indication or failure when verifying the token. When the XHR request failing inputting a verify token just dismissed the slideout panel with no confirmation.

I don't know if there's a way to catch any XHR exception to know it failed.

**Comment by brandonkelly** [comment]
There might be, but the underlying issue here—that synchronous XHR isn’t allowed—would impact several areas in the control panel, not just 2FA setup. For example, if you open an entry’s editor slideout from the Entries index page, any JS required for that entry’s fields wouldn’t get loaded (such as CKEditor JS).

I’ve just made a change for Craft 4.11 and 5.3, so Craft only sets the `Permissions-Polity` header for site request responses, not control panel responses. (0cc699eafdf5a34987bc4c81ac631b0d14803f3c)
