### ISSUE TITLE
[5.x]: Modified matrix entries don't get updated after adding or deleting an entry to the matrix (Copy of #15069)

### ISSUE THREAD

**Issue by Liamm3** [craftcms/cms#15353]
### Description
On May 24 2024 I created an issue regarding problems when [saving modified matrix blocks](https://github.com/craftcms/cms/issues/15069). Today I encountered the same problem again. 
When modifying an existent matrix block, adding a new block and then saving the entry, all the data in the modified matrix block gets lost.

### Steps to reproduce
1. Create a new matrix field
2. Add some entry types (e.g. 'Plain Text') 
3. Disable the title field and generate the title from the plaintext field 
![area_813](https://github.com/user-attachments/assets/e10c9dd0-8e99-4907-be10-5c25676d50b6)
4. Add the matrix field to a section
5. Create a new entry in the section
6. Add an entry to the matrix 
![area_816](https://github.com/user-attachments/assets/226f329f-92e6-43d0-b297-7e579a03bf49)
7. Save the entry using Ctrl+S
8. Modify the created matrix block
9. Add a new entry to the matrix 
![area_817](https://github.com/user-attachments/assets/6a054725-8e27-460f-b74f-44cdc6224d75)
10. Save again
11. All the changes are lost
![area_818](https://github.com/user-attachments/assets/e88f5b9c-02a9-477a-af2a-3b6de678af6c)

### Expected behavior
The modified matrix entry should be saved after saving the entry.

### Actual behavior
Changes on a modified entry are lost, after adding a new entry to the matrix.

### Craft CMS version

5.2.6

### PHP version

8.3

### Operating system and version

Linux using ddev

### Database type and version

MariaDB 10.6

### Installed plugins and versions

- ether/seo v5.0.0-rc4
- craftcms/ckeditor 4.1.0

**Comment by i-just** [comment]
Hi, thanks for getting in touch! I’m unable to replicate this on v5.2.6. Do you see any errors in the console when this happens?

**Comment by Liamm3** [comment]
No, I don't see any errors. But I just noticed that I have `'autosaveDrafts'` set to `false` in `general.php`. When I set it to `true`, everything works as expected.
