### ISSUE TITLE
[5.x] / [4.x]: CP Slow with two or more users logged in 

### ISSUE THREAD

**Issue by adrianjean** [craftcms/cms#15351]
### Description
- In one browser (Chrome for example) When logged into the CP, I can use my 4.x or 5.x site normally and the interface is snappy. 
- In another browser (Safari for example), if I log into a different account, the CP takes a long time to load initially but then becomes snappy.
- If I switch back to the browser with my first logged in account and refresh, the CP takes a long time to load, but then subsequent use is snappy...

Going back and forth between users (in different browsers) that "lag" of the CP feels like CraftCMS has to do something between the two CP users and when one uses the site, the other is forced to experience that slow-down again.

I have seen this with users on different computers in different regions on the same site as well. I'm also now seeing it on CraftCMS 5.x, so I'm reporting it here.

### Steps to reproduce

1. In one browser (Chrome for example), create User A, log-into the CP. Notice how fast the CP is as normal.
2. In one browser (Safari for example), create User B. Log-into the CP in a different browser. Notice a short lag before the CP loads. Once it loads notice how fast the CP is, as normal.
3. Switch back to the browser with User A, and refresh the page. Notice the lag in the CP loading?. Once it loads notice how fast the CP is, as normal.
4. Switch back to the browser with User B, and refresh the page. Notice the lag in the CP loading?. Once it loads notice how fast the CP is, as normal.
5. ... etc. etc. 

The larger the site, the more content on the site, the longer the lag between user accounts. I have a CraftCMS 4.x site with 10k visitors per day, 3 authors, +18,000 entries, and the lag can be quite long.

### Craft CMS version

Craft Pro 5.2.5

### PHP version

8.3.9

### Operating system and version

Linux 5.15.0-113-generic

### Database type and version

MySQL 8.0.30

### Image driver and version

GD 8.3.9

### Installed plugins and versions

- AsyncQueue	4.0.0
- Button Box	5.0.0
- Campaign	3.4.0
- CKEditor	4.1.0
- Code Field	5.0.0
- Control Panel CSS	3.0.0
- Control Panel Nav	5.0.1
- Cookies	5.0.0
- Dashboard Begone	3.0.0
- Expanded Singles	3.0.0
- Feed Me	6.2.0
- Field Manager	4.0.1
- Formie	3.0.0-beta.16
- Icon Picker	3.0.0
- Knock Knock	3.0.0
- Neo	5.0.5
- SendGrid	3.0.0
- SEO	5.0.4
- Single Cat	4.0.0
- Sprig	3.0.2
- Timber	2.0.1

**Comment by brandonkelly** [comment]
Is this happening on production or locally?

If locally, what is your environment setup? And do you have Xdebug enabled?

**Comment by adrianjean** [comment]
It's happening on production.
I don't have Xdebug enabled on these boxes.

Environment: 
- Apache + PHP-FPM
- MySQL: Digital Ocean hosted DB (on another box)

Happy to try some troubleshooting steps?

**Comment by angrybrad** [comment]
@adrianjean any chance we could get some SSH and Craft Control Panel to investigate? If so, could you send them to support@craftcms.com and reference this issue?

**Comment by adrianjean** [comment]
Will do.

**Comment by angrybrad** [comment]
For posterity, this seems to be related to the [Control Panel Nav](https://plugins.craftcms.com/cp-nav?craft5) plugin that was installed. Disabled that and the performance issues resolved.
