### ISSUE TITLE
[5.x]: Error in CraftCMS: prepareForJsonColumn() Argument Type Mismatch in FindAndReplace.php

### ISSUE THREAD

**Issue by alexanderbuergin** [craftcms/cms#15355]
### What happened?

An error occurs when executing the search and replace function in CraftCMS. The issue appears to stem from an invalid argument passed in the prepareForJsonColumn() call within the FindAndReplace.php file.

Steps to reproduce
Perform a search for the term "ABC" and replace it with "XYZ" using the respective function in CraftCMS.

### Error

```
craft\helpers\Db::prepareForJsonColumn(): Argument #1 ($value) must be of type array, null given, called in /home/xxx/public_html/xxx/xxx/xxx/vendor/craftcms/cms/src/queue/jobs/FindAndReplace.php on line 63
```

 
<img width="2043" alt="Bildschirmfoto 2024-07-15 um 12 19 44" src="https://github.com/user-attachments/assets/09f20367-6062-4169-ac4b-199e7d362236">

### Craft CMS version

5.1.5

### PHP version

8.2

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch! If you update to v5.2.3 or later, this should no longer be a problem.
