### ISSUE TITLE
Response Headers Ignoring Header Tags [4.x]: 

### ISSUE THREAD

**Issue by MacroFabMktg** [craftcms/cms#15366]
### Description
Craft seems be ignoring header modifications for caching.

### Steps to reproduce
This code has been in production since implementing CloudFront this year.  Suddenly is being ignored:
`
% set expiry = now|date_modify('+30 days') %}
{% header "Cache-Control: max-age=" ~ expiry.timestamp %}
{% header "Pragma: cache" %}
{% header "Expires: " ~ expiry|date('D, d M Y H:i:s', 'GMT') ~ " GMT" %}
`

### Expected behavior
Should send response headers as written

### Actual behavior
![image](https://github.com/user-attachments/assets/de7e338d-37ae-4c5c-b114-ac45c23951ac)

### Craft CMS version

Craft Pro 4.10.5

### PHP version

8.1.29

### Operating system and version

Linux 6.2.0-1012-aws

### Database type and version

MySQL 8.0.35

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.1-33)

### Installed plugins and versions

-
Copy	2.4.4
Field Manager	3.0.8
HOMM XML Sitemap	1.0.3
Mix	v1.7.1
PDFThumb	2.0.0
Redirect Manager	2.0.1
Tags	2.0.0

**Comment by brandonkelly** [comment]
Are you calling `csrfInput()` or otherwise generating/loading a CSRF token on the page?

**Comment by MacroFabMktg** [comment]
@brandonkelly No. Not directly.  I have a JS Ajax call that gets the CSRF token and populates where needed.  It was an adjustment I had make early this year when we started using CloudFront so the token would be fresh.

    csrf: {
        get: function () {
            $.ajax('/actions/form/form/csrf/', {
                type: 'GET',
                dataType: 'JSON'
            }).done(function (Response) {
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': Response.csrf
                    },
                    cache: false
                });
                $('meta[name="csrf-token"]').attr({
                    'content': Response.csrf
                });
                $('#FormCSRF').val(Response.csrf);
            });
        }
    },`
`

**Comment by MacroFabMktg** [comment]
Here's some additional info: If I try to reset the header info I want into the .htaccess file, It will only add to the response headers.  This is from my dev machine, but it does the same on staging and production.
`
Header unset Pragma
Header unset Cache-Control
Header set Cache-Control "max-age=31536000, public"
Header set Pragma "cache"
`
![image](https://github.com/user-attachments/assets/3f5ececb-0b7b-429d-bbc2-a28f23b226c6)

**Comment by MacroFabMktg** [comment]
Also, tried following these instructions: https://craftcms.com/knowledge-base/cloud-static-caching

**Comment by MacroFabMktg** [comment]
Found one line of code calling for CSRF in the meta tag.  Removed and is now acting as expected.

**Comment by brandonkelly** [comment]
Glad you got to the bottom of it!
