### ISSUE TITLE
[5.x]: Setting field values in Entry::EVENT_BEFORE_SAVE doesn't work when $firstSave is true

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#15369]
### Description

I have an Entry::EVENT_BEFORE_SAVE event in which I do:

```
$entry->setFieldValues([
    'latitude' => $coords['lat'],
    'longitude' => $coords['lng'],
]);
```

This works when updating entries, but not for the case where `$entry->firstSave` is `true`.

### Steps to reproduce

1. Create an event listener that sets entry field values.

### Expected behavior

It should work on first save.

### Actual behavior

The first time saving it doesn't work, on updating it does.

### Craft CMS version

5.2.6

### PHP version

8.3

### Database type and version

PostgreSQL 16

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Craft 5.2.9 is out with a fix for this. Thanks for reporting!
