### ISSUE TITLE
[4.x]: error: Undefined array key "label"

### ISSUE THREAD

**Issue by leowebguy** [craftcms/cms#15365]
### Description

Getting this error on multiple environments whenever the "hide" label global option is active or inactive.

<img width="1046" alt="Screenshot 2024-07-16 at 3 02 26 PM" src="https://github.com/user-attachments/assets/0732f346-c045-4e8a-bd1e-ce2b961c679e">

```
Applying changes from your project config files ...
- updating globalSets.3a69ae7a-a2cc-4b47-80ef-a8353308ad6f.fieldLayouts.ea7ff35d-55b1-459a-8e1b-79a1a38bfd85.tabs.0.elements.0 ... 
  - updating globalSets.3a69ae7a-a2cc-4b47-80ef-a8353308ad6f ... 
error: Undefined array key "label"
Failed to execute command php ./craft project-config/apply: exit status 1
```

same happens in cp when I swith "hide" on or off and try to save it

<img width="912" alt="Screenshot 2024-07-16 at 3 05 18 PM" src="https://github.com/user-attachments/assets/2da8cf69-bd36-4b89-8e65-756b383b145c">

```
PHP Warning – [yii\base\ErrorException](https://www.yiiframework.com/doc-2.0/yii-base-errorexception.html)
Undefined array key "label"
```

### Steps to reproduce

1. create a field
2. add to a global set
3. select "hide" label option
4. save it

### Expected behavior

No error and config/project should reflect that change.

### Actual behavior

Applying changes from your project config files ...
- updating globalSets.3a69ae7a-a2cc-4b47-80ef-a8353308ad6f.fieldLayouts.ea7ff35d-55b1-459a-8e1b-79a1a38bfd85.tabs.0.elements.0 ... 
  - updating globalSets.3a69ae7a-a2cc-4b47-80ef-a8353308ad6f ... 
error: Undefined array key "label"
Failed to execute command php ./craft project-config/apply: exit status 1

### Craft CMS version

4.10.5

### PHP version

8.1.16

### Operating system and version

RHEL8

### Database type and version

MySQL 10.4

### Installed plugins and versions

  Blitz 4.19.0
  Code Field 4.0.12
  Device Detect 2.0.1
  Empty Coalesce 4.0.0
  Healthfirst Email Me dev-main
  Healthfirst Guide dev-main
  Healthfirst Leads dev-main
  Healthfirst Logs dev-main
  Healthfirst Mailer dev-main
  Healthfirst Utils dev-main
  Hyper 1.1.32
  Logs 4.0.1
  Lorem Ipsum 1.0.0
  Mix Manifest 1.0.3
  Navigation 2.0.28
  Neo 3.9.11
  Redactor 3.1.0
  Retour 4.1.18
  SEO 4.1.0
  Super Table 3.0.14
  Table Maker 4.0.11
  User Activity 2.4.1

**Comment by brandonkelly** [comment]
Looks like that error is coming from the [User Activity](https://plugins.craftcms.com/activity?craft4=) plugin, based on the file shown in the exception view.
