### ISSUE TITLE
[5.x]: Pagination info on overview page not updating after bulk editing with filter applied

### ISSUE THREAD

**Issue by white-lukas** [craftcms/cms#15367]
### Description
When filtering an element overview page (eg. category is empty) and using the bulk editing function to add categories to the element, after saving the changes. the overview page is updating but the pagination/element count won't update

### Steps to reproduce

1. go to an element overview page
2. apply a filter
3. bulk edit elements so that they won't match the filter anymore
4. pagination/element count is not updating

### Expected behavior
Element count should update

### Actual behavior
Element count stays the same as it was before the bulk edit

### Craft CMS version

5.2.6

### PHP version

8.3.8

### Operating system and version

Ubuntu 24.04

### Database type and version

mysql 8.0

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.2.8 is out with that fix. Thanks again!
