### ISSUE TITLE
Revisions for singles - Remove other sites from the author view (multisite) 

### ISSUE THREAD

**Issue by magnessjo** [craftcms/cms#15361]
### Description

When using multisite, singles display revisions from other sites. This may need to be part of a bigger refactor to create separation (encapsulation) between sites or expected as multisite where created from translations. Still, we wanted to flag it as a weird workflow for content authors. 

### Steps to reproduce

1.Make a multisite instance with revisions enabled for a single.
2. Make an entry in user without permissions admin permissions for each site. 
3. Have each user submit an update to their site’s single. 

### Expected behavior

 Reivisions would be filtered to show only the current site (unless the content is translated between other entries). 

### Actual behavior

Each user can see revisions for all submissions listed in the dropdown

### Craft CMS version

Craft Pro 5.2.5

### PHP version

8.2.19

### Operating system and version

AMI 2

### Database type and version

MariaDB 10.5.25

### Image driver and version

GD 8.2.19

### Installed plugins and versions

CKEditor 4.10
Postmark 3.1
Shellcraft (our plugin - used to sync YAML) - 0.5.4

**Comment by brandonkelly** [comment]
Every time an entry is saved, it is saved across all sites. That’s necessary because there are always certain values, such as untranslated custom fields, which need to be copied across all sites. So even if the entry wasn’t explicitly saved for the selected site for each individual revision, something about it probably changed for each site, for each revision.

**Comment by magnessjo** [comment]
@brandonkelly - Thank you for the context on the logic and the mechnisms for how an entry revisions are stored. It makes sense why a revision would be stored in the DB has a change across sites. 

For consideration: Content authors often don't know the existence of other sites or changes in a content model (mapping of fields). Having a interface downdown with information that is unfamiliar to them isn't ideal for UX or AX. Could there be a toggle option added to user permissions to only show them revisions based related to them selves, group or site?

**Comment by brandonkelly** [comment]
> Could there be a toggle option added to user permissions to only show them revisions based related to them selves, group or site?

Not sure what you mean by that?

**Comment by magnessjo** [comment]
I was proposing to add a user setting for the groups that modifies the revisions UI on entries. An additional option in the UI below allows users to view other users’ revisions. In addition, a global toggle in the user settings will enable user groups to view revisions per site. 

Controlling how revision history is displayed to authors would be valuable for those who want revisions and don’t allow cross-site authoring. It’s not urgent for us, but it occasionally comes up with our users. For the time being, we will remove revisions from singles. 

Thank you for consideration and feedback. 

<img width="359" alt="Screenshot 2024-07-16 at 12 20 37 PM" src="https://github.com/user-attachments/assets/3b0ddbf7-62cf-4f74-82c2-b7d9dacb547c">

**Comment by brandonkelly** [comment]
Ahh, sorry, following you now.

**Comment by brandonkelly** [comment]
Can you please post that suggestion as a new discussion?
