### ISSUE TITLE
"Cooming Soon" font lacks in Polish characters

### ISSUE THREAD

**Issue by tu5** [craftcms/cms#1537]
### Description

"Cooming Soon" font lacks in Polish characters.
![coomingsoon](https://cloud.githubusercontent.com/assets/18059922/23985887/b3f2bcec-0a21-11e7-9585-16ccb966b9a7.png)

### Steps to reproduce

1. Switch language to Polish (in testing phase now)
2. Voila!

### Additional info

- Craft version: 2.6.2967
- PHP version: 7.1.2

**Comment by brandonkelly** [comment]
@benjamindavid we should probably just use the normal sans-serif font the rest of the CP uses here.
