### ISSUE TITLE
[5.x]: Custom field conditions in element queries are case-sensitive now

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#15370]
### Description

I just encountered one surprising change when updating from Craft 4 to Craft 5 that I haven't seen a mention of in the docs or in the changelog (though of course it's possible that I missed it). All custom field conditions are case-sensitive now, even when using a case-insensitive collation. At least in MySQL, can't speak to PostgreSQL.

I _think_ that's because the content is now stored in a JSON column. Apparently, extracted JSON columns are always treated as `utf8mb4_bin` by default, so all comparisons are binary, i.e. case-sensitive. We're always using `utf8mb4_0900_ai_ci`, so this was a bit surprising.

In Craft 4 this always worked, regardless of whether the `first_name` was `Dwight` or `dwight`:

```twig
{% set = craft.entries()
    .first_name('dwight')
    .one()
%}
```

In Craft 5, this will not work if the first name is `Dwight` with a capital `D`.

This does not affect the search index (`.search()`) since the search terms are always lowercased. But it does affect all custom field conditions against fields that store their content in the `content` column, as far as I can tell.

### Steps to reproduce

1. Use a lowercase value in a custom field condition when the field has capital letters in it.

### Expected behavior

If possible, the built-in fields should handle this edge-case automatically. Maybe `modifyElementsQuery` for the built-in fields can be adjusted to do a case-insensitive comparison? Though this might be bad for performance, not sure.

In any case, the current behaviour was pretty surprising since we're already using a case-insensitive collation. If this behaviour can't be changed, it should be mentioned in a couple of places in the docs. At the very least:

- In the Craft 4 -> Craft 5 upgrade guide.
- In the documentation on element queries.

### Actual behavior

The breaking change from Craft 4 to 5 is mostly undocumented and unexpected.

### Craft CMS version

5.2.6

### PHP version

8.3

### Database type and version

MySQL 8

**Comment by brandonkelly** [comment]
Thanks for pointing that out. The intent has always been for element query params (besides `search`) to be case-sensitive, but that wasn’t possible with MySQL, so it’s only worked as intended with Postgres.

I hadn’t thought to test it again now that custom field values are being stored in JSON, but you’re right, so this is an undocumented change in behavior for MySQL installs.

I’ve just added support for specifying case-insensitive params for Craft 5.3, by setting the field param value to an array with `value` and `caseInsensitive` keys (#15404).

5.3 will be out soon, and we’ll make sure the change and new workaround are documented at that point.

**Comment by MoritzLost** [comment]
@brandonkelly Thanks, that's a good addition!

**Comment by palomamtnez** [comment]
Thanks @brandonkelly, how would you apply that on PHP though? 

This is an example that comes from the guide:
https://craftcms.com/docs/5.x/upgrade.html#advanced-queries

```
use Craft;
use craft\elements\Entry;

$entryType = Craft::$app->getEntries()->getEntryTypeByHandle('post');
$fieldLayout = $entryType->getFieldLayout();
$sourceField = $fieldLayout->getFieldByHandle('sourceMedia');

$entriesFromPhysicalMedia = Entry::find()
  ->section('news')
  ->andWhere([
    'or like',
    $sourceField->getValueSql(),
    ['print', 'paper', 'press'],
  ])
  ->all();
```

Where should I add the `caseInsensitive` param?

**Comment by brandonkelly** [comment]
@palomamtnez Same as how you’d do it in Twig, using the field’s query param:

```php
Entry::find()
    ->section('news')
    ->sourceMedia([
        'value' => ['print', 'paper', 'press'],
        'caseInsensitive' => true,
    ])
    ->all();
```

It’s only available to certain field types though. See [Case Sensitivity](https://craftcms.com/docs/5.x/development/element-queries.html#case-sensitivity).
