### ISSUE TITLE
[5.x]: Entry types that were converted from Matrix block types should have the slug hidden by default

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#15379]
### Description

During the upgrade to Craft 5, all matrix block types are converted to entry types. Entry types have options to show the title and slug fields, which matrix blocks don't have. By default, the option _Show the Slug field_ is active for the converted entry types, which doesn't make sense. Slugs aren't used for those entry types (yet), since they didn't exist before. So showing the slug field by default is just confusing and doesn't add anything useful.

### Steps to reproduce

1. Upgrade a site with a matrix field to Craft 5 and check the converted matrix blocks (entry types).

### Expected behavior

The conversion should turn off the option to show the slug field, similar to the option to show the title.

### Actual behavior

The option to show the slug field is turned off for the converted entry types.

### Craft CMS version

5.6.8

### PHP version

8.3

**Comment by brandonkelly** [comment]
Good call, just made that change for Craft 5.3.
