### ISSUE TITLE
[4.x]: `Element:: EVENT_DEFINE_SIDEBAR_HTML ` not working for `User` elements

### ISSUE THREAD

**Issue by tommysvr** [craftcms/cms#15388]
### Description

`EVENT_DEFINE_SIDEBAR_HTML` isn't triggered on User elements, but it works on other elements.

### Steps to reproduce

You can test with:

```
Event::on(User::class, Element::EVENT_DEFINE_SIDEBAR_HTML, static function (DefineHtmlEvent $event) {
  \Craft::dd('User sidebar');
});
```

### Expected behavior

When you load a User you'll see the dd output

### Actual behavior

User page loads as normal

### Craft CMS version

4.10.6

### PHP version

8.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
This is expected because Edit User pages don’t use the new element editor in Craft 4 (whereas user slideouts do).

For Craft 4, you can inject additional HTML into Edit User page sidebars via the `cp.users.edit.details` [template hook](https://craftcms.com/docs/4.x/extend/template-hooks.html).
