### ISSUE TITLE
[5.x]: no option to change element index view on mobile and export button missing

### ISSUE THREAD

**Issue by white-lukas** [craftcms/cms#15387]
### Description
On mobile there is no option to switch the view between table and card view, it defaults to the card view, which doesn't have the quick edit function, and the export button is also not available 
![Screenshot_2024-07-19-10-45-58-98_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/4d4b5a24-6e41-44e5-85dc-94eb79edbb3a)

### Steps to reproduce

1.login to the control panel on mobile
2. Go to the entries overview

### Expected behavior
You should be able to switch view mode and the export button should be shown

### Actual behavior
Only the card view is available,
And no export button

### Craft CMS version

5.2.7

### PHP version

8.3

**Comment by brandonkelly** [comment]
Both of these are intentional. Table views have always been very awkward on mobile, so I removed it for mobile at the same time card view was added (0a38a7e9032).

Exporting has never been available on mobile, but that could be something we reevaluate now that phones have filesystems (like iCloud Drive) to store things. Feel free to open up a discussion for that.

**Comment by pimago** [comment]
Especially for orders the card view is not very useful on mobile. It just shows the reference which doesn't give me any info if I quickly want to check the orders on mobile. Any plans on adding something more useful here?

**Comment by i-just** [comment]
@pimago, yes - there’s [a PR](https://github.com/craftcms/cms/pull/15283) (currently targeting v5.5) that will allow for further card customisation, including selecting which attributes should appear in cards and controlling the order in which selected fields and attributes show. (Currently you can choose which custom fields should show in cards.)

**Comment by pimago** [comment]
Cool, thank you for the quick reply!

**Comment by brandonkelly** [comment]
Craft 5.5.0 is out with better card view customization (#15283) 🎉
