### ISSUE TITLE
[5.x]: Table entries cannot be drag/dropped to re-order on touch devices

### ISSUE THREAD

**Issue by iparr** [craftcms/cms#15382]
### Description

Using a standard table provides a 'grab handle' to re-arrange rows works well on desktop, but on touch-screen mobile I can't find anything to grab!

In my example, I use this field to list out an events music programme - with one column for the composer and one column for the piece. It's a reasonably nice interface - I know I could use a matrix field here, but that would be a bit more fiddly / visually noisy for my content editors. This works perfectly on desktop / non-touch devices.

I know that there was a similar problem with Matrix fields that was fixed using a drop-down menu (#8490). I understand that this is a problem that hasn't necessarily been fixed well in other software.

### Steps to reproduce

1. Create a table field and begin to add some rows. Try to re-arrange them on a touch device (I've tested Android Chrome on physical hardware and iOS Safari on a simulator).

### Expected behavior

Holding down to drag will re-order - or some other mechanism available to re-order these on mobile.

### Actual behavior

Can't drag / drop to move these.

### Craft CMS version

5.2

### PHP version

8.3

### Database type and version

MySQL

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for pointing that out! We need to get around to supporting drag-n-drop on mobile, but in the meantime, we’ve added “Move up” and “Move down” disclosure menu options for Craft 5.3 (#15385).

**Comment by iparr** [comment]
Crackin' turn around, team. Can't wait to try this out and update my client.
