### ISSUE TITLE
Change calendar navigation to arrows

### ISSUE THREAD

**Issue by tu5** [craftcms/cms#1538]
### Description

When a month name is long in some languages, it jumps to next line and scroll appear. That doesn't look good. Maybe use arrows instead?
![calendar](https://cloud.githubusercontent.com/assets/18059922/23986073/9d2d8324-0a22-11e7-857f-4eacbf8c7e11.png)

### Steps to reproduce

1. Change language to, i.e., Polish (testing phase now)
2. Voila!

### Additional info

- Craft version: 2.6.2967
- PHP version: 7.1.2

**Comment by brandonkelly** [comment]
Agree, arrows would be better.
