### ISSUE TITLE
[5.x]: Smith.js console.log error breaks Dashboard Matrix functionality

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [craftcms/cms#15398]
### Description

It looks like there's an issue with Smith.js:

```
TypeError: Cannot read properties of undefined (reading '$actionMenu')
```

![Screenshot 2024-07-22 at 11 04 07 AM](https://github.com/user-attachments/assets/28e3a590-840a-40cc-958c-4653ab4f3f63)

### Steps to reproduce

1. Go to an entry with a matrix field
2. Interact with the field
3. Fields disappear

### Expected behavior

No console errors and fields don't disappear

### Actual behavior

Console errors and fields disappear

### Craft CMS version

5.2.8

### PHP version

8.3

### Installed plugins and versions

-

**Comment by brianjhanson** [comment]
It looks like this is likely an issue with [Batch Actions](https://github.com/spicywebau/craft-batch-actions/tree/main) which includes [Smith](https://plugins.craftcms.com/smith). Can you report the issue [over there](https://github.com/spicywebau/craft-batch-actions/issues)?

**Comment by DynamiteGoesBoom** [comment]
Doh, sorry about that @brianjhanson and I'll report it over there instead.
