### ISSUE TITLE
[5.x]: Section - Previewlink URL not taking .env parameter

### ISSUE THREAD

**Issue by The-Dan-Main** [craftcms/cms#15391]
### Description
When trying to add `@web` or f.Ex. `$PREVIEW_SITE_URL` as part of my preview Link URL-Format, it does not resolves the value and creates a long link:

(I have replaced my actual url of the craft with project-craftdomain.com)

https://project-craftdomain.com/index.php?p=craft-login%2Factions%2Fpreview%2Fcreate-token&elementType=craft%5Celements%5CEntry&canonicalId=22&siteId=1&revisionId=&previewToken=YgZVq5pPWszikR6W_HphbHEUb4pGWCv0&redirect=https%3A%2F%2Fproject-craftdomain.com%2F%24PREVIEW_SITE_URL%2F__home__%3Fx-craft-preview%3DrjQB8mQ0pe%26token%3DYgZVq5pPWszikR6W_HphbHEUb4pGWCv0

instead of "https://whateverIHaveSetUpInMyENVVariable.com/"

### Steps to reproduce

1. Set a ENV variable as URL-Format for a section

### Expected behavior

to use this variable, so i can make one change in the .ENV file instead of changing it on several occasions within craft.

### Actual behavior

it skips the variable and takes first character: $PREVIEW_SITE_URL/{uri} --> / , which then creates this long URL.

### Craft CMS version

5.2.8

### PHP version

8.3.7

### Operating system and version

Plesk Obsidian with Debian Base

### Installed plugins and versions

many, but the issue is craft core related.

**Comment by brandonkelly** [comment]
Aliases like `@web` will work, however if you wish to use an environment variable, **only** the environment variable can be passed in. So `$PREVIEW_SITE_URL` is OK, but `$PREVIEW_SITE_URL/{uri}` is not.

To get the result you want, you can define a `@previewSiteUrl` alias based on the `PREVIEW_SITE_URL` environment variable:

```php
// config/general.php

use craft\config\GeneralConfig;
use craft\helpers\App;

return GeneralConfig::create()
    ->aliases([
        '@previewSiteUrl' => App::env('PREVIEW_SITE_URL'),
        // ...
    ])
    // ...
;
```

Then reference that alias combined with the URI in your preview target URL (`@previewSiteUrl/{uri}`).

**Comment by The-Dan-Main** [comment]
Thats awesome and worked like a charm! Thank you!
