### ISSUE TITLE
[5.x]: Minor spacing issue on 'slideout-container' > 'so-sidebar details' when slug is hidden.

### ISSUE THREAD

**Issue by garycrane** [craftcms/cms#15405]
### What happened?

So, so sorry, I _know_ this is such a minor issue but my OCD is doing cartwheels over it 😂😩  I think it makes the slideout look as though content might be missing. I don't need the slug field to be visible/editable by the client on any of my Matrix blocks, hence seeing this issue quite frequently.

<img width="1339" alt="Screenshot 2024-07-24 at 12 47 47" src="https://github.com/user-attachments/assets/ab0d769a-a4ab-4102-adf6-1e1fcb3ece13">

### Steps to reproduce
1. Disable 'Show the Slug field' lightswitch in an entry type associated with a Matrix field (view mode 'As Cards').
2. Create new entry and add a new matrix row.
3. Slideout appears but looks a bit broken.

### Suggestion
<img width="1389" alt="Screenshot 2024-07-24 at 17 02 07" src="https://github.com/user-attachments/assets/b340acde-beb4-4eb4-9898-b0709c1cdd04">

### Craft CMS version

5.2.8

### PHP version

8.2.20

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 5.2.9 is out now with that fix. Thanks again!

**Comment by garycrane** [comment]
> Craft 5.2.9 is out now with that fix. Thanks again!

No problem at all. Thank you!
