### ISSUE TITLE
[5.x]: Custom sources in entry indexes forget selected sites and cause errors

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#15406]
### Description

Just ran into a curious issue. When editing a custom source on the entry indexes page, clicking on the settings for an existing custom source will 'forget' which sites were selected:

![Screenshot 2024-07-24 at 17 56 41](https://github.com/user-attachments/assets/3d55860e-f916-4008-8c15-bee91e8de6ca)

The custom source is active for _Site 1_, but the checkbox is missing after opening and closing the settings modal.

Saving the modal with no sites selected for the custom will redirect and then throw an error, preventing you from changing this setting again:

> array_map(): Argument #2 ($array) must be of type array, false given

![Screenshot 2024-07-24 at 17 59 00](https://github.com/user-attachments/assets/9ac73b0e-3101-467e-9046-12773cf6a4e8)

I had to hack a workaround into `ElementSources::getSources()` to be able to load the page again and fix the setting. Re-opening the custom source settings wipes the selected sites again. 

### Steps to reproduce

1. Create a second site in the settings.
2. In the entry index, create a custom source that is active in only one site and save the settings.
3. Reopen the settings for the custom source and save it again.

### Expected behavior

- The custom source should not forget which sites are selected.
- Having no sites selected should not result in an unrecoverable error.

### Actual behavior

See above.

### Craft CMS version

5.2.8

### PHP version

8.3

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 5.2.9 is out now with that fix. Thanks again!
