### ISSUE TITLE
[5.x]: Minor issue with revision spinner

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#15409]
### Description
This is happening in only a single project of mine, and it's very minor (basically a non-issue), just wanted to report here cause I haven't got a clue where to start looking:

Each time I open an entry the revision spinner is immediately triggered that is normaly displayed next to the entry title with each save:

https://github.com/user-attachments/assets/875bb7c3-f914-4c1e-98cc-4e474a080f7f

This happens on all entries.

### Craft CMS version

Craft Pro 5.2.8

### PHP version

8.3.8

### Database type and version

MySQL 8.0.36

### Installed plugins and versions

-

**Comment by thupsi** [comment]
Update: Just realised that this not isolated to one project: It's on all Pro and Team projects and is not visible only in Solo!

**Comment by thupsi** [comment]
Still minor though 🙂

**Comment by brandonkelly** [comment]
This is happening because the page is checking if any other authors are working on the entry. If you pay close attention, it will do it every 15 seconds.

**Comment by thupsi** [comment]
Aha, since my last comment I actually was thinking about that being the reason! Thanks for confirming!
