### ISSUE TITLE
[5.x]: Money field UI issues

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#15412]
### Description

I've encountered a couple UI / UX issues with the money field in the Control Panel.

It's not possible to change the first digit for the cents individually. If I highlight the first cents digit and hit a number key, it's instead inserted as the second digit instead, overwriting the first one:

https://github.com/user-attachments/assets/909e0175-edfc-496c-bb0a-17efeb008df8

Another issue that is not major but could be improved: Showing the currency symbol (EUR €) _before_ the input makes sense in English, because prices are usually formatted with the currency symbol before the amount (e.g. `$ 100`). In most other languages, though, the currency symbol comes after the number (`100 €`). In those cases, showing the currency symbol after the input would be preferable. Maybe the order could depend on the language of the current site or the _Formatting Locale_ of the user?

### Steps to reproduce

1. In a numbers field, highlight the tens digit of the cents amount and input any digit.

### Craft CMS version

5.2.5

**Comment by nfourtythree** [comment]
Hi @MoritzLost 

Thank you for your feedback. The money input uses an input mask library which enforces this behaviour based on the number of sub-units for the specific currency. This is to ensure that the value entered always conforms.

Unfortunately, the library has no options that would allow Craft to override the behaviour. There are some issues related to this on the library's GitHub so we can monitor these to see if there are any updates in the future.

Hope this explanation helps, thanks!

**Comment by MoritzLost** [comment]
@nfourtythree Fair enough, thanks for the explanation. Can you link those issues so I can follow those as well? Thanks!
