### ISSUE TITLE
[5.x]: Horizontal scroll in live preview (on iPad)

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#15419]
### Description
While working on an iPad, I noticed a little bit of horizontal scrolling while in live preview mode - cause by the dual buttons on the top asset field

![image](https://github.com/user-attachments/assets/4eea527e-5222-4fcd-a621-6208a454554e)

### Craft CMS version

5.2.

### PHP version

8.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 5.2.9 is out now with that fix. Thanks again!
