### ISSUE TITLE
[5.x]: Switching from a plain text field to a Money field causes an unrecoverable error everywhere

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#15413]
### Description

We had to convert a Plaintext field to a money field. Those fields are not compatible, so you are warned about the potential for data loss when switching the field type. That's fine and I expected to have to re-enter all the values. What I did not expect is that this is basically impossible, because the money field throws errors everywhere:

- The entry editing form throws an error if the field has an unexpected value.

![Screenshot 2024-07-25 at 12 43 21](https://github.com/user-attachments/assets/d481a9df-2ca6-4cbb-b7dd-cd9c6a76cc81)

- The element indexes don't load any more if the field is displayed as a column, because the controller returns a 500 response.
 
![Screenshot 2024-07-25 at 12 44 46](https://github.com/user-attachments/assets/b123e6b0-0643-4e7a-bf94-28e9d5b6d4b6)

- I tried to resave the entries to clear the field, but that causes an error as well.

![Screenshot 2024-07-25 at 12 44 08](https://github.com/user-attachments/assets/c56ba467-d112-4300-a1b4-5479b7f36742)

This makes it very hard to fix the content issues. The only thing I can think of is to either manually fix the values in the database, or switch the field back to Plaintext, empty it out and then switch to a Money field again.

### Steps to reproduce

1. Create a plain text field, add it to an entry type, and create some entries with arbitrary values in the field.
2. Switch the plain text field to a money field.
3. Try to edit an entry, view the element index (with the field visible as a column) or resave the entries using the `resave/entries` command.

### Expected behavior

Invalid values should be handled more gracefully and allow a normal author to fix the incorrect value.

### Actual behavior

Invalid values throw an error with no way to fix it through normal means.

### Craft CMS version

5.2.5

### PHP version

8.3

**Comment by brandonkelly** [comment]
Craft 5.2.9 is out now with a fix for this. Thanks for reporting!
