### ISSUE TITLE
[5.x]: More than one default can be selected for Dropdown fields

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#15415]
### Description

When editing an existing Dropdown field, I can have more than one option selected as the default. After selecting a third option, the second one will be cleared out. And after deselecting the previously saved option, only one option is active at the time. But after reloading the page, I can select an additional default option, and save the field like that.

https://github.com/user-attachments/assets/e766f6f1-d14d-41a7-912b-dbb3cf2779ab

### Steps to reproduce

1. Create a radio field, define some options and select a default.
2. Save and reload the page. Mark another option as default.

### Expected behavior

Only one default option should be selectable.

### Actual behavior

After a page reload, I can have two default options active at the same time.

### Craft CMS version

5.2.8

### PHP version

8.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next Craft 4 and 5 releases.

**Comment by brandonkelly** [comment]
Craft 4.10.7 and 5.2.9 are out with that fix. Thanks again!
