### ISSUE TITLE
[5.x]: "Temporary uploads" volume not hidden for all users when disabled

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#15424]
### Description
When I disable the "Temporary Uploads" asset source, it is hidden for me (the admin) but still visible to other users.

Am I misunderstanding the way this should work?

### Steps to reproduce

1. In a dev enviroment go to "assets"
2. Choose "customize sources"
3. Select "Temporary Uploads" and disable it

### Expected behavior
The "Temporary Uploads" source is hidden for all users in the CP.

### Actual behavior
The "Temporary Uploads" source is hidden only for the admin.

### Craft CMS version

5.2.8

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for Craft 5.3 (2b7f1188a4faf12df9e919aaac7e120a605dffa4).

**Comment by JayBox325** [comment]
I'm sorry this is an old post, but how do you disable the Temporary Uploads volume? I can't see the flow you've taken:

- In a dev enviroment go to "assets"
- Choose "customize sources"
- Select "Temporary Uploads" and disable it

**Comment by thupsi** [comment]
@JayBox325 The "customize sources" action is in the "source actions" (the 3 dots):

<img width="140" alt="Image" src="https://github.com/user-attachments/assets/c2812fc7-a296-4b48-9d59-933cff4b7570" />

**Comment by JayBox325** [comment]
Legend. Thanks! I kept looking at Assets in the Settings area. Durr. Thanks!
