### ISSUE TITLE
[5.2.8]: Tab menu button icon centering

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#15422]
### Description

Greetings from the department of nitpicks 😜

<img width="533" alt="image" src="https://github.com/user-attachments/assets/3d55ba3c-0d52-48b4-bc79-f190e9a6b818">

### Craft CMS version

5.2.8

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next Craft 4 and 5 releases.

**Comment by brandonkelly** [comment]
Craft 4.10.7 and 5.2.9 are out with that fix. Thanks again!
