### ISSUE TITLE
[5.x]: Update error messages for users/send-password-reset-email when useEmailAsUsername is enabled

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#15425]
### Description

In Craft CMS 5, the `users/send-password-reset-email` action returns the following error messages:
- `Craft::t('app', 'Username or email is required.')`
- `Craft::t('app', 'Invalid username or email.')`

However, when the `useEmailAsUsername` configuration is enabled, referencing the username in the front-end is no longer relevant.

Can the messages be adapted to the following when `useEmailAsUsername` is true?
- `Craft::t('app', 'Email is required.')`
- `Craft::t('app', 'Invalid email.')`

### Steps to reproduce

1. Enable the `useEmailAsUsername` configuration.
2. Attempt to use the `users/send-password-reset-email` action.

### Expected behavior

The error messages should only reference the email when `useEmailAsUsername` is true.

### Actual behavior

The error messages reference both the username and email, which is not relevant when `useEmailAsUsername` is true.

### Craft CMS version

5.2.8

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for Craft 4.11 and 5.3.
