### ISSUE TITLE
[5.x]: Sorting element index by custom field only works on first click

### ISSUE THREAD

**Issue by tommysvr** [craftcms/cms#15434]
### Description
Sorting the entries index by a custom field only works the first time.

### Steps to reproduce

1. Add a custom Date/Number field to a channel
2. Click on the column header to sort
3. First sorting works, subsequent clicks have no affect
4. The same is true when using the View dropdown

### Expected behavior
Clicking again will change the sorting order to ascending/descending.

### Actual behavior
Only the initial sort using custom fields works. Sorting based on the title works as expected. No errors are produced in the logs/browser console.

Likely related to https://github.com/craftcms/cms/issues/15335 / https://github.com/craftcms/cms/issues/15297 and https://github.com/craftcms/cms/commit/29d55d86b1dbd5f51483f904b832e4c8a354f50f

https://github.com/user-attachments/assets/52f6e9c7-4419-44ff-a4d4-78cf0a0b3dd9

### Craft CMS version

5.2.8

### PHP version

8.2

### Database type and version

MySQL 8.0

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks Tommy! Fixed for the next release.
