### ISSUE TITLE
[4.x]: baseCpUrl makes other sites completely inaccessible when CRAFT_LIVE is set to 0

### ISSUE THREAD

**Issue by chrismou** [craftcms/cms#15437]
### Description

When enabled on a multi-site instance, baseCpUrl disables CMS access to all sites other than the one you've set, causing a 404.  So for example if you have `a.com` and `b.com` and you set `baseCpUrl` to `a.com`, then `a.com/admin` becomes the only admin site you can access. `b.com/admin` throws a 404.

We have two sites which historically are in different site groups (I'm not sure this was the right choice by the original devs or even if it makes a difference here, but mentioning just in case) and we prevent access to our staging & UAT sites by setting `CRAFT_LIVE` to `0` in the '.env' which still allows admins to view the sites after logging in.

However, they're required to log into each site individually before they can view it - so, ie, to view a.com they need to log into a.com/admin, then to view b.com they also need to log in to b.com/admin.

But now baseCpUrl is set to a.com, b.com's login page is disabled, effectively making the b.com staging site completely inaccessible as noone is able to access b.com's login page.

I can't work out if this is a bug or if I'm missing something. Is there a workaround for this that I'm missing?

Sorry if this isn't clear, let me know if you need anything clarifying.

### Steps to reproduce

1. Creates 2 sites in differerent site groups
2. Set `CRAFT_LIVE=0` in .env
3. Set `baseCpUrl` to one of the sites in general config

### Expected behavior

If `baseCpUrl` being set disables logins on all other sites, then logging in to the enabled one should authenticate the user with all of them so admins can still view all sites

### Actual behavior

Admin can only view the site they've logged in to, the other is inaccessible

### Craft CMS version

4.9.5

### PHP version

8.2

### Operating system and version

Ubuntu Linux

### Database type and version

Mysql

**Comment by brandonkelly** [comment]
We have always recommended picking a single point of entry for the control panel. Craft’s licensing enforcement requires it; otherwise you will end up getting nag alerts about using your Craft license on the wrong domain.

So this is (not) working as intended.

**Comment by chrismou** [comment]
@brandonkelly This is what we're trying to enforce, but this feels like two craft config settings conflicting with each other. On one hand we have the site set to offline so that only admins can access when logged in, but on the other the baseCpUrl setting is making it impossible to log in to any of our sites. There's even an explicit user permission allowing it, but again it's not actually possible

![image](https://github.com/user-attachments/assets/655e5580-180d-430f-b0fd-0f9ce910a383)

Is there any workaround for this that you can think of, or do we have to rethink our staging site testing strategy?

As a more general point, if its recommened to have a single point of entry, should the checks for `CRAFT_LIVE` check that you're authenticated on the primary site, not the site you're trying to access?

**Comment by brandonkelly** [comment]
That’s a good question. In the past you could handle it by adding a [front-end login form](https://craftcms.com/knowledge-base/front-end-user-accounts#login-form), but that’s not as practical in Craft 5 until we make it easier to add 2FA/passkey support to the front end.

Is there a reason you’re setting `baseCpUrl` in the first place? It’s usually only used for headless sites where the control panel lives on its own dedicated host name, like `cms.example.com`. As long as you’re accessing the control panel via `/admin` (or whatever your CP trigger is set to), you don’t need to set it.
