### ISSUE TITLE
[5.x]: 'Author' label in Entry details meta CP view doesn't respect translations

### ISSUE THREAD

**Issue by jonnykates** [craftcms/cms#15443]
### Description
I'm working on a site where I would like to relabel what Craft describes as an Entry's 'Author' to its 'Owner'. This is displayed and defined in the top right details container when editing an entry:

![Screenshot 2024-07-30 at 16 24 08](https://github.com/user-attachments/assets/82540dfb-cc1a-405b-9765-354fd9b4cbaf)

This label however doesn't appear to be respecting a translation that I've set up;

```
<?php

return [
	'Author' => 'Owner',
];
```

### Steps to reproduce

1. Define a static message translation as described in the docs [here](https://craftcms.com/docs/5.x/system/sites.html#static-message-translations) for the string 'Author'
2. View an Entry edit screen in the CP
3. The 'Author' string is unaffected by the translation

### Expected behavior
I would expect this string to be translated to the value defined in (for example) `/translations/en-GB/app.php`.

### Actual behavior
The string 'Author' is unaffected when in this `.details-container` metadata set.

### Craft CMS version

Craft Pro 5.2.9

### PHP version

8.2.20

### Operating system and version

Linux 6.6.32-linuxkit

### Database type and version

MariaDB 10.6.18

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

<table class="data fullwidth fixed-layout" dir="ltr">
            <tbody>
                                    <tr>
                        <th class="light">Admin Bar</th>
                        <td>5.0.0-beta.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Asset Rev</th>
                        <td>8.0.0</td>
                    </tr>
                                    <tr>
                        <th class="light">CKEditor</th>
                        <td>4.1.0</td>
                    </tr>
                                    <tr>
                        <th class="light">Control Panel CSS</th>
                        <td>3.0.0</td>
                    </tr>
                                    <tr>
                        <th class="light">CP Field Inspect</th>
                        <td>2.0.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Dashboard Begone</th>
                        <td>3.0.0</td>
                    </tr>
                                    <tr>
                        <th class="light">Expanded Singles</th>
                        <td>3.0.0</td>
                    </tr>
                                    <tr>
                        <th class="light">Field Manager</th>
                        <td>4.0.2</td>
                    </tr>
                                    <tr>
                        <th class="light">Hyper</th>
                        <td>2.0.3</td>
                    </tr>
                                    <tr>
                        <th class="light">Image Resizer</th>
                        <td>4.0.0</td>
                    </tr>
                                    <tr>
                        <th class="light">Navigation</th>
                        <td>3.0.3</td>
                    </tr>
                                    <tr>
                        <th class="light">Obfuscator</th>
                        <td>1.2.0</td>
                    </tr>
                                    <tr>
                        <th class="light">Password Policy</th>
                        <td>5.0.0-beta1</td>
                    </tr>
                                    <tr>
                        <th class="light">PDF Transform</th>
                        <td>5.0.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Redirects</th>
                        <td>5.0.2</td>
                    </tr>
                                    <tr>
                        <th class="light">SEO</th>
                        <td>5.1.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Typogrify</th>
                        <td>5.0.1</td>
                    </tr>
                            </tbody>
        </table>

**Comment by brandonkelly** [comment]
“Author” is translated using the `app` translation category, since it is a Craft-defined word. So you would need to put the translation in `translations/en/app.php` rather than `site.php`.

**Comment by jonnykates** [comment]
Hey @brandonkelly - I _am_ putting the translation in `app.php` rather than `site.php` yet the instance of the string is not translated in the CP;

`translations/en/app.php`:
```
<?php

return [
    'Author' => 'Owner',
    'Authors' => 'Owners'
];
```

![image](https://github.com/user-attachments/assets/934d664f-d48d-499c-b58d-b30a0f6dc4ec)

The **column heading** in the Entries table is affected by the translations just not in the Entry upper-right meta data on a specific Entry edit view.

<img width="536" alt="Screenshot 2024-08-05 at 12 21 20" src="https://github.com/user-attachments/assets/77dd5757-07dc-4cb6-a633-65ce3ddc6654">

**Comment by i-just** [comment]
Hi @jonnykates, the translation string for this Author/Authors label is: [`'{max, plural, =1{Author} other {Authors}}'`](https://github.com/craftcms/cms/blob/5.2.9/src/elements/Entry.php#L2024), so you’ll have to use something along the lines of: 
`'{max, plural, =1{Author} other {Authors}}' => '{max, plural, =1{Owner} other {Owners}}',` for it to work.

Hope this helps!

**Comment by jonnykates** [comment]
Ah @i-just perfect, thank-you!
