### ISSUE TITLE
[5.x]: dropdown field issue - all option values must be unique condition

### ISSUE THREAD

**Issue by alanski66** [craftcms/cms#15442]
### Description
Editing dropdown field items will not save as ux feedback insists that each value be different - ie "all option values must be unique."
AFAIK html5 spec does not require unique values in a dropdown by happy to be corrected

### Steps to reproduce

1. add dropdown field and add same values
2. Field will not save

### Expected behavior
Add same values and save field

### Actual behavior
Error warning given "all option values must be unique condition"

### Craft CMS version

5.29

### PHP version

8.3

### Operating system and version

Cloud linux

### Database type and version

Mysql 8

### Image driver and version

na

### Installed plugins and versions

na

**Comment by brandonkelly** [comment]
What is the use case? Even if we allowed it, there’s no way the inputs could remember which of the duplicate options had been selected, and it would always show the first one as selected when loading edit forms.

**Comment by alanski66** [comment]
My use case :)
Product postcode delivery price list as in attached image.
It was allowed in Craft 2 and now we are on Craft 5 we cant edit or save the existing field. I'm sure putting the 'label' in the value solves it but it means a bit more js work to strip the price out.

![Screenshot 2024-08-01 at 16 39 46](https://github.com/user-attachments/assets/7e9fab9f-1269-4b05-af96-72af107aa53b)

**Comment by brandonkelly** [comment]
I’m not seeing any duplicate values in there (ignoring the prices).

**Comment by alanski66** [comment]
Sorry should have been clearer I couldn't post the html. The values are numbers - the same but for different area codes
Label BN1 £4.95. value 4.95
Label BN2 £4.95. value 4.95
Label BN41 £4.95. value 4.95
etc

**Comment by brandonkelly** [comment]
That seems like it would be pretty confusing to authors, no? If an author selects “BN2 - £4.95” and saves, and comes back to the entry to find that “BN1 - £4.95” is now selected, they’re going to assume there was a bug.

Why not change the labels to “£4.95 (BN1, BN2, BN3)” etc.?

**Comment by alanski66** [comment]
It would be but the assumption is that authors are using this field and they are not - its a global list of prices included on a product page (not Craft Commerce). Labels solution is nice - thx! - but harder to read from UX perspective and less width friendly. I see the rationale:) I think I'll change the values to match.
