### ISSUE TITLE
[4.x]: upgrade vulnerable axios 0.27.2

### ISSUE THREAD

**Issue by d--j** [craftcms/cms#15448]
### Description

axios 0.27.2 has these two vulnerabilities:

- https://github.com/axios/axios/issues/6131
- https://github.com/advisories/GHSA-wf5p-g6vw-rhxx

Please upgrade axios to [0.28.1](https://www.npmjs.com/package/axios/v/0.28.1)
https://github.com/craftcms/cms/blob/4b05a2ff9b6c179276cf84a12529f519a57509b2/package.json#L36

At least  https://github.com/advisories/GHSA-wf5p-g6vw-rhxx has been fixed in there. https://github.com/axios/axios/issues/6131 has only been fixed in 1.6.3 but upgrading to this version would probably be a breaking change and it is "only" a ReDoS attack.

### Steps to reproduce

1. Navigate to the following URL: https://example.com/admin/login
2. Open the browser's built in developer tools
3. Enter the following string into the JavaScript console: `axios.VERSION`
4. Note that the application includes a version of Axios 0.27.2 which has known security issues associated with it

### Craft CMS version

4.10.7

**Comment by brandonkelly** [comment]
Thanks for reporting that! I’ve updated Axios to 0.28.1 for the next Craft 4 release. (Craft 5 is already running 1.6.5.)
