### ISSUE TITLE
[5.x]: Unexpected behaviour with relation fields in a multi-site context

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#15459]
### Description

Follow-up to #15458 and also #14347 and #14348.

We had a persistent issue for a while where queries with relation parameters where returning more results than expected. Just found out that it's due to some unexpected behaviour when entries are propagated, and relation queries not taking the site into account.

### Steps to reproduce

1. Create two sites, `Site A` and `Site B`.
1. Create a section `Target` (with a new empty type) that's active in both sites and set the propagation method to _Only save entries to the site they were created in_.
2. Create an Entries field `Relation` that allows selecting entries from the `Target` section with the following settings:
    1.  Relate entries from a specific site? **No**
    2. Show the site menu: **No**
    3. Manage relations on a per-site basis: **Yes**
4. Create another section `Source`, with an entry type that has the `Relation` field and set the propagation method to _Let each entry choose which sites it should be saved to_.
5. Create an entry in the `Target` section in `Site A`.
6. Create an entry in the `Source` section in `Site A` and set the `Relation` to the entry created in the previous step.
7. Propagate the entry to `Site B`.
8. Go back to `Site A` and remove the relation to the newly created entry.

Now the propagated entry in `Site B` has a relation to an entry that only exists in `Site A`, despite the field being configured to only allow selecting entries from the same site as per the above options. This messes with element queries. If I have query for relations of the entry in the `Target` section in `Site A`, it will return the entry created in step 6, even though the entry in `Site A` is _not_ related to that entry any more. This can even be seen in the entry index: Add a condition on `Relation` field with `is related to` and then select the target entry. This will show one entry, even though the entry is not related to that entry in this site any more.

### Expected behavior

I think two things are going wrong here:

1. Propagation should not result in invalid states. In step 7, the relation to the entry in `Site A` is propagated as-is, even if the field settings don't allow the author to select that entry. During propagation, the relation should be changed to the target entry _in the target site of the propagation_. If the related entry does not exist in that site (as is the case in the example above), it should be removed from the Entries field for the propagated entry.
2. I don't think this is the only way to arrive at this invalid state. To prevent issues like this (this isn't the first time we ran into this problem, see the issues linked above), relationship queries should always take the target site of the query into account.

### Actual behavior

- The propagation resulted in an invalid state that an author would not be able to create manually. The author has to notice this and fix it manually to prevent errors that are extremely hard to debug.
- Element queries should always take target/source site into account, to prevent this type of issue.

### Craft CMS version

5.2.8

### PHP version

8.3

### Database type and version

MySQL 8

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
This is _technically_ working as expected.

> 1. During propagation, the relation should be changed to the target entry _in the target site of the propagation_.

Relations don’t actually keep track of the target element’s site; only the target element’s ID.

That said, I agree it’s awkward that existing relations can be automatically propagated to sites where the relation couldn’t have been created to begin with. So I just adjusted the behavior for Craft 4.11 and 5.3 (54cf12e6b8d6c2becdab0bc9a8c68649bdeadc21).

Note this isn’t a retroactive change. However it’s worth noting that when “Related elements from a specific site?” is disabled, those relations which don’t exist for the current site won’t actually get returned by relation field element queries by default, unless you are overriding the `site`/`siteId` param.

**Comment by MoritzLost** [comment]
@brandonkelly Thanks! Preventing those relations from being propagated will be a great improvement, and will solve the problems the client's been having in this project.

> Note this isn’t a retroactive change. However it’s worth noting that when “Related elements from a specific site?” is disabled, those relations which don’t exist for the current site won’t actually get returned by relation field element queries by default, unless you are overriding the site/siteId param.

Hmm, but in my example above, the Control Panel was still showing false results when filtering by the relation field. Filtering by entries related to a particular target entry in the specific field returned incorrect entries that were no longer related to that entry in the current site, if those had the propagated relation to the entry from the current site. Maybe there's still something not working as intended there?

**Comment by brandonkelly** [comment]
The control panel adds `->site('*')->unique()` params to the relation query, to ensure all relations are shown, regardless of whether they’d get included in front-end queries by default.

**Comment by MoritzLost** [comment]
@brandonkelly Ah got it, was just a bit confusing in this case.
