### ISSUE TITLE
[5.x]: Asset field buttons overflow their container

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#15450]
### Description

The two buttons in Assets fields can't wrap into two lines, so they can overflow if the space for a field is too small. Particularly noticeable in element flyouts, and when the field is set to 1/4 or 1/2 width. We like to use a slightly more verbose label for the first button to distinguish both buttons, which makes this more likely.

![Field layout with voerflowing buttons in an asset field](https://github.com/user-attachments/assets/ab476bb2-4425-45d5-9885-fc2c2085587e)

### Steps to reproduce

1. Create an Assets field and define a slightly longer label in the _“Add” Button Label_ setting.
2. Add the Assets field to an entry field layout at 1/4 or 1/2 width.
3. Create an entry with that field in a flyout.

### Expected behavior

1. The second button should wrap below the first one if the space grows too small.
2. If the first button is too long for the given space by itself, the button label should span two rows or truncate the label (less desirable).

### Actual behavior

The buttons overflow and overlap with fields next to it.

### Craft CMS version

5.2.8

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
That was previously reported via #15419, and fixed in 5.2.9 :)

**Comment by MoritzLost** [comment]
@brandonkelly Ah I didn't see that issue, thanks!
