### ISSUE TITLE
[5.x]: utils/prune-orphaned-entries deletes all entries in some sections

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#15458]
### Description

In trying to debug an issue, I ran `utils/prune-orphaned-entries` in a local development environment with a copy of the production database. To my surprise, it deleted _all entries_ in some sections. Only sections where the propagation is set to the _Save entries to all sites enabled for this section_ were left untouched. All sections that were set to manual propagation (_Let each entry choose…_) or no propagation had all entries in all sites deleted.

Not sure how to reproduce this or if it's an issue with my database, but this should never happen.

The issue I'm trying to debug is related to #14348 and #14347. We're still seeing remnants of previous relations sticking around, querying for relations returns elements that were previously related, but were removed from the field. I can't reproduce this fully yet, but something is still not right there. Not sure if it's a database issue that might also cause this problem.

### Craft CMS version

5.2.8

### PHP version

8.3

### Database type and version

MySQL 8

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Yikes, thanks for reporting that! That command was added in 4.7 as `utils/prune-orphaned-matrix-blocks` (#14154), and I guess I didn’t think to update the element query to exclude top-level entries when adapting it for nested entries in Craft 5.

**Comment by MoritzLost** [comment]
@brandonkelly Thanks for the fix! Good to know this was just an oversight, I was sure my database was somehow messed up 😄

**Comment by brandonkelly** [comment]
Craft 5.2.10 is out with that fix. Thanks again!
