### ISSUE TITLE
Add support for `webp` images as a valid image Asset type

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#1545]
`webp` is a really nice image format that has the weight of Google behind it; and it delivers really nice optimization of images in terms of file size.

While [not all browsers support it yet](http://caniuse.com/#feat=webp), leaving it up to the developer to decide if it should be allowed would be useful. Here are some `webp` images from Google for a comparison:

https://developers.google.com/speed/webp/gallery1

Additionally, what many websites are doing is having the webserver itself handle the delivery of `webp` images based on the `Accept` header:

Nginx: https://github.com/uhop/grunt-tight-sprite/wiki/Recipe:-serve-WebP-with-nginx-conditionally

Apache: https://gist.github.com/seeekr/2415528

YouTube and other major sites do this; if you visit their site using Chrome, you get `webp` images. If you visit their site using a browser that doesn't support them, you get `jpg` or `png`

As long as Craft supports `webp` as an allowable image type, we'd be able to deliver this functionality in, even automatically pre-created the `webp` versions of the images if https://github.com/craftcms/cms/issues/1544 is implemented.

**Comment by khalwat** [comment]
https://github.com/aelvan/Imager-Craft/issues/90

**Comment by khalwat** [comment]
Adding for completeness:

https://www.vaersaagod.no/en/using-webp-images-in-craft-with-imager

**Comment by andris-sevcenko** [comment]
Improved the support for this with #e4ba1e3b
