### ISSUE TITLE
Not possible to save a section without a URL format on the initial section save

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#1546]
### Description

See title.

### Steps to reproduce

1. Create a new Section
2. Delete the automatically created Entry URL Format
3. Save the section.
4. Notice the URL format is set back to what was automatically created
5. You can successfully delete it on future saves.

### Additional info

- Craft version: 3.x
- PHP version: 7.x
- Database driver & version: n/a
- Plugins & versions: n/a

**Comment by snoopdouglas** [comment]
I'm seeing what is potentially the same bug on 3.x, but the problem persists on subsequent saves.

**Comment by takobell** [comment]
Fixed in https://github.com/craftcms/cms/commit/55b0ebda4ad264ef02e5b2f1193e68b478852514
