### ISSUE TITLE
[5.3.0-beta.1]: Lightswitch field UI in Site Settings

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#15460]
### What happened?

Lightswitch fields in the Site Settings section of the Section Settings page are displaying incorrectly when in the “on” state.

![screenshot-2tiGD7cI@2x](https://github.com/user-attachments/assets/e1675c35-f76f-4626-a678-14f9f359f032)

### Craft CMS version

5.3.0-beta.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 5.3.0-beta.2 is out with that fix. Thanks again!
