### ISSUE TITLE
[5.x]: Response on Grapqhl Entry deletion is null

### ISSUE THREAD

**Issue by The-Dan-Main** [craftcms/cms#15465]
### Description

When i delete an entry via graphql, it should return a boolean, whether the deletion was succesfull or not (information from docs), but it returns "nulll" at all times.

### Steps to reproduce

1.delete an entry via id with graphql

### Expected behavior

to return a boolean, which outsputs the successfulness of my mutation.

### Actual behavior

it returns null, in both cases (entry existed and is deleted now // entry did not exist and therefore was not deleted)

### Craft CMS version

5.2.9 Pro

### PHP version

8.3.7

### Operating system and version

Plesk Obsidian with Debian Base

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next Craft 4 and 5 releases.

**Comment by brandonkelly** [comment]
Craft 4.10.8 and 5.2.10 are out with that fix. Thanks again!
