### ISSUE TITLE
[4.x]: Invalid Route

### ISSUE THREAD

**Issue by Jude867** [craftcms/cms#15469]
### Description

More something I am doing wrong than a bug with Craft.
I can't get routing to work with Craft 4. When I navigate to a url I get the error
Page not found - caused by invalid route unable to resolve the request

### Steps to reproduce

1. I have a controller set up BillingRequestController.php
Located in modules/gocardless/src/controllers
(Note modules/gocardless/GoCardless.php is all set up and working)
It has a function named public function actionGetBillingRequestFlowId()

```php
namespace modules\gocardless\controllers;

use Craft;
use craft\web\Controller;
use yii\web\Response;

class BillingRequestController extends Controller
{
    protected $allowAnonymous = true;

    public function actionGetBillingRequestFlowId()
    {
        $this->requireAcceptsJson();

        $billingRequestFlowID = Craft::$app->session->get('billingRequestFlowID');

        if ($billingRequestFlowID) {
            return $this->asJson([
                'success' => true,
                'billingRequestFlowID' => $billingRequestFlowID,
            ]);
        } else {
            return $this->asJson([
                'success' => false,
                'error' => 'No billing request flow ID found in session.',
            ]);
        }
    }
}
```

2. I have the following setup in config/routes.php
return [
    'gocardless/billing-request/get-billing-request-flow-id' => 'gocardless/billing-request/get-billing-request-flow-id',
];
3. When I go to the url /gocardless/billing-request/get-billing-request-flow-id I get the error HTTP 404 Not Found. Page not found caused by invalid route. unable to resolve the request "gocardless/billing-request/get-billing-request-flow-id"

I have tried this with simpler routes too but none seem to work

### Expected behavior

The route to work

### Actual behavior

404 Error

### Craft CMS version

Craft Pro 4.10.7

### PHP version

8.2.21

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
What is your module’s ID?

The module ID is defined by its key in the `modules` array within `config/app.php`. For example, in the following config, the module ID is `foo`:

```php
return [
    // ...
    'modules' => [
        'foo' => FooModule::class,
    ],
];
```

**Comment by Jude867** [comment]
Thank you, it's gocardless, this is what I have in my app.php

```php
return [
    'id' => App::env('CRAFT_APP_ID') ?: 'CraftCMS',
    'modules' => [
        'gocardless' => \modules\gocardless\GoCardless::class,
    ],
    'bootstrap' => ['gocardless'],
];
```

**Comment by brandonkelly** [comment]
Do you have this code in your `GoCardless` module’s `init()` method?

```php
if (Craft::$app->request->isConsoleRequest) {
    $this->controllerNamespace = 'modules\\gocardless\\console\\controllers';
} else {
    $this->controllerNamespace = 'modules\\gocardless\\controllers';
}
```

**Comment by Jude867** [comment]
Thank you so much - I had missed modules\\ off the start of those namespaces.
I am such an idiot - I looked at those lines of code a hundred times and I missed it.
Thank you for your help, it is so much appreciated.

**Comment by brandonkelly** [comment]
Hah, no worries, glad you got it working!
