### ISSUE TITLE
[4.x]: Headers link is showing duplicate language path in URL .../en-us/en-us/...

### ISSUE THREAD

**Issue by mateostabio** [craftcms/cms#15461]
### Description
My client noticed in their SEO Ahrefs Report that the site is having loads of errors on the other language sites as it shows 404 error pages as the response headers link. Here's an example:

On this blog post: 
https://clearestate.ddev.site/en-us/blog/how-to-become-an-executor-of-an-estate-without-a-will

The response header Link shown is this: 
<https://clearestate.ddev.site/en-us/en-us/blog/how-to-become-an-executor-of-an-estate-without-a-will>; rel="canonical"

I see the response header link as duplicate on my local ddev and on the production site. 

### Steps to reproduce

This started happening after performing an update 2 months ago from CraftCMS v4.6.1 to v4.9.4

![Screenshot 2024-08-01 at 1 24 00 PM](https://github.com/user-attachments/assets/dcf20729-c961-46e3-bcd8-05db954f6240)

Canonical is correct in the HTML:
![Screenshot 2024-08-01 at 1 45 47 PM](https://github.com/user-attachments/assets/db9da4d9-accf-4f8e-a29d-f6b5567c2659)

### Craft CMS version

4.9.4

### Installed plugins and versions

    "vlucas/phpdotenv": "^2.4.0",
    "verbb/super-table": "^3.0.7",
    "craftcms/redactor": "3.0.4",
    "craftcms/aws-s3": "^2.0.3",
    "sebastianlenz/linkfield": "2.1.5",
    "ether/seo": "^v4.0.3",
    "vaersaagod/geomate": "^2.1.0",
    "born05/craft-twofactorauthentication": "^3.0.1",
    "vlucas/phpdotenv": "^5.4.0",
    "ether/logs": "4.0.0"

**Comment by mmikkel** [comment]
@mateostabio Craft doesn't add any "Link" response headers. I'm pretty sure this is a problem with the Ether SEO plugin: https://github.com/ethercreative/seo/issues/469

**Comment by mateostabio** [comment]
@mmikkel Thank you!!!
