### ISSUE TITLE
[5.x]: Matrix fields with "card" or "element index" view do not fire "afterInit" Garnish event like regular "block" fields

### ISSUE THREAD

**Issue by timmyomahony** [craftcms/cms#15470]
### Description

On the Craft 5 control panel entry page, when a Matrix field with the "block" view is rendered, its JavaScript (`MatrixInput.js`) [fires a `afterInit` event once the field is ready](https://github.com/craftcms/cms/blob/5.x/src/web/assets/matrix/src/MatrixInput.js#L157). This is useful for hooking into Matrix fields in JavaScript to [augment their functionality](https://github.com/timmyomahony/craft-matrix-field-preview).

But when you change the view to use the new "card" or "element index" view (which uses [`NestedElementManager.js`](https://github.com/craftcms/cms/blob/5.x/src/web/assets/cp/src/js/NestedElementManager.js)), this event doesn't exist.

This means you can't rely on the `afterInit` event for Matrix fields, as it only fires for one "view" (the block view). 

To fix this, a `trigger('afterInit')` needs to be added to the `NestedElementManager.init` function here:

https://github.com/craftcms/cms/blob/5.x/src/web/assets/cp/src/js/NestedElementManager.js#L24

### Steps to reproduce

Create some Javascript on the Control Panel that listens for `afterInit`:

```js
// Works when view = block on matrix field
Garnish.on(
  Craft.MatrixInput,
  "afterInit",
  {},
  function (ev) {
    console.log("Matrix field loaded");
  }.bind(this)
);

// Should work when view = card/element index on matrix field but doesn't
Garnish.on(
  Craft.NestedElementManager,
  "afterInit",
  {},
  function (ev) {
    console.log("Nested matrix field loaded");
  }.bind(this)
)
```

### Expected behavior

When a matrix field input that has its view set as "card" or "element index" loads on the control panel entry page, we should be able to see the console output "Nested matrix field loaded". 

### Actual behavior

The event `afterInit` doesn't exist on this field, so it will never run.

### Craft CMS version

5

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Added for 5.3 (bcd23b448f7bbf54cd2059da229a22eeccc113a0).
