### ISSUE TITLE
[5.x]: Spacing off in element edit page sidebar

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#15473]
### What happened?

This irks me somewhat, so bringing to your attention the fact that the spacing under “Notes about your changes” is inconsistent with the other sidebar panel headings, due to the styling on the `label`.

I’ve tried to show this using colours below, but if you look close enough you’ll see that the extra spacing is quite noticeable.

This issue affects both Craft 5.2.9 and 4.10.7.

![screenshot-mqbywR2s@2x](https://github.com/user-attachments/assets/6a299c45-2640-4268-bd4d-dec161b59bbe)

### Craft CMS version

5.2.9 and 4.10.7

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next Craft 4 and 5 releases.

**Comment by brandonkelly** [comment]
Craft 4.10.8 and 5.2.10 are out with that fix. Thanks again!
