### ISSUE TITLE
[5.x]: CP Account menu shows blank space where email address should be

### ISSUE THREAD

**Issue by antcooper** [craftcms/cms#15475]
### Description

Users other than the initial admin user account have a blank space where the email address should be to link to their profile page.

![CleanShot 2024-08-05 at 11 18 08@2x](https://github.com/user-attachments/assets/154dfaa3-efe3-44a4-a807-5dd512a6bb1f)

### Steps to reproduce

1. We have `useEmailAsUsername(true)` in our general.php config. 
2. Create a new user in the 'Client' group that has control panel access.
3. Login as that user and there's no text inside the anchor link to their Profile page.

### Expected behavior

Users should see their email address in the menu.

### Actual behavior

This [section is blank](https://github.com/craftcms/cms/blob/4cc11114402289f876c668c8b50aeccec464c39d/src/templates/_layouts/cp.twig#L186). It seems that `currentUser.username` has no value. 

Users can login without issue, but looking in the database the `username` column is blank for everyone apart from the first admin user.

We created the site whilst Craft 5 was in beta, but have applied updates and now on 5.2.9

### Craft CMS version

5.2.9

### PHP version

8.3.9

### Operating system and version

Linux 6.1.0-22-amd64

### Database type and version

MySQL 28.1

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.1-32)

### Installed plugins and versions

    "craftcms/ckeditor": "4.1.0",
    "nystudio107/craft-seomatic": "5.1.1",
    "nystudio107/craft-vite": "5.0.0",
    "putyourlightson/craft-sprig": "3.2.0",
    "servd/craft-asset-storage": "4.0.6",

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 4.10.8 and 5.2.10 are out with that fix. Thanks again!
