### ISSUE TITLE
[5.x]: Request to Expose .title Method in New Link Field

### ISSUE THREAD

**Issue by alexanderloewe** [craftcms/cms#15484]
### What happened?

First and foremost, I want to express my gratitude for your continuous dedication to improving Craft CMS. The introduction of the new Link field into the core of the CMS is a significant advancement, and I am thrilled to see this feature implemented.

Specifically, I would like to suggest the addition of a method to access the link's title (or label) directly within templates.

### Current Situation 
At present, the Link field allows us to use the .link method to output the entire link, like this:
```{{ entry.myLinkFieldHandle.link }}```

However, there is no built-in method to access just the **title** of the link. This limitation makes it challenging to separate and manipulate different parts of the link for template customization.

### Proposed Feature
I propose introducing a method such as .title or .label that would allow users to access just the title of the link. This would enable more flexible template rendering and customization, allowing developers to query the title independently from the rest of the link.

Example usage could look like this:

`{{ entry.myLinkFieldHandle.title }}` or `{{ entry.myLinkFieldHandle.label }}`

### Benefits
1. Enhanced Template Flexibility: Users can tailor the display of link components without having to manipulate the entire link object.
2. Consistency: The proposed method aligns with how similar properties are typically accessed in Craft CMS, ensuring intuitive and streamlined code.
3. Increased Customization: Developers gain more control over the presentation of content, which is crucial for designing tailored and dynamic web pages.

Implementing this feature would greatly benefit users who require a more granular level of control over link elements within templates. It would enhance the versatility and usability of the Link field and align with the functionality already provided by other field types in Craft CMS.

Thank you for considering this enhancement.

### Craft CMS version
5.3

**Comment by BigglesZX** [comment]
Just looking at the [new docs](https://craftcms.com/docs/5.x/reference/field-types/link.html#linkdata) for this field type – would `entry.myLinkFieldHandle.element.title` get you what you need?

**Comment by mmikkel** [comment]
Looks like the docs doesn't mention this detail currently, but you can actually access the link's text via the `label` property, i.e.

```twig
{{ entry.myLinkFieldHandle.label }}
```

Similarly, the link's url value (i.e. what would be the `href` for the link) is available via `entry.myLinkFieldHandle.value`.

Some more info in the original PR: https://github.com/craftcms/cms/pull/15251

**Comment by alexanderloewe** [comment]
`block.linkMulti.title`
Returns: `Calling unknown method: craft\fields\data\LinkData::title()`

`block.linkMulti.element.title`
Returns: `Impossible to access an attribute ("title") on a null variable`

**Comment by alexanderloewe** [comment]
I had also tried `{{ entry.myLinkFieldHandle.label }}` without success. Now it works. I must have made a typing error.

Sometimes I are a bit slow in the head. 🤪

Thanks guys


@PnT Maybe add it to the doc? I would offer to support you in expanding the doc.

**Comment by brandonkelly** [comment]
Yeah `.label` is what you’re looking for!

`.element.title` would work, but only if the link is actually set to an element. So you’d need to wrap it in a `{% if entry.myLinkField.element %}` condition.

We’ll get the docs updated.

**Comment by AugustMiller** [comment]
[Done](https://github.com/craftcms/docs/commit/cee2ce49c5ab2d1ea5149fedcaf398cb5862c768)! Should be deployed in just a moment. 💞

(…aaaand, found a typo, which will get corrected in the next deploy! 😅)

**Comment by alexanderloewe** [comment]
Thanks to Everyone!
