### ISSUE TITLE
[5.x]: New headersFilter in app.web.php applying to Control Panel requests and not Site requests

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/cms#15495]
### Description

The new feature in #15397 doesn't appear to be working correctly. I tried applying a `as headersFilter` in the app.web.php but this applied to Control Panel requests not site Requests.

Example config used in app.web.php:

```
// Attach the headers filter to the application
'as headersFilter' => [
    'class' => \craft\filters\Headers::class,
    'site' => 1,
    'headers' => [
        'X-Test-Header' => 'Test Value',
    ]
]
```

For a site request:

![image](https://github.com/user-attachments/assets/7b9d7080-0e4e-4154-b314-de278ff80e54)

For a CP request:

![image](https://github.com/user-attachments/assets/19e4105b-94ec-436a-b20f-7b98357541bc)

### Steps to reproduce

1. Add `as headersFilter` example in #15397
2. Inspect response headers of a site request (value is not present)
3. Inspect response of CP request e.g. /admin (value is present)

### Expected behavior

Headers to be present on site requests only.

### Actual behavior

Site requests do not have any headers added, but are appearing on Control Panel requests which is the reverse of intended functionality.

### Craft CMS version

5.3.0.3

### PHP version

8.3

### Database type and version

MySQL

**Comment by jamesmacwhite** [comment]
@timkelty For reference regarding the new headersFilter in 5.3

**Comment by timkelty** [comment]
Looking now, @jamesmacwhite

**Comment by timkelty** [comment]
@jamesmacwhite Thanks for the report, should be fixed here: https://github.com/craftcms/cms/pull/15499

Amazing what difference a `!` can make. We'll try and get a release out ASAP.

**Comment by jamesmacwhite** [comment]
Happens to us all! Thanks for looking into it and proposing a quick patch. I'm currently use the request component to set headers on site requests only currently, but once a new release is made, I'll transition over.

**Comment by brandonkelly** [comment]
Craft 4.11.1 and 5.3.1 are out with that fix. Thanks again for reporting!

**Comment by jamesmacwhite** [comment]
No worries. Thanks for the quick fix @timkelty and release @brandonkelly.

It's great adding front end HTTP headers is consistent for Craft CMS apps now.
