### ISSUE TITLE
[5.x]: Replace file option on an entry is confusing

### ISSUE THREAD

**Issue by lexisother** [craftcms/cms#15498]
### Description

The naming of the "Replace file" option is a bit confusing. One of our clients just submitted a report that when they tried to use this option to replace the file on an entry, it'd get replaced on another entry as well. Unbeknownst to them, that's exactly the point of the feature, but it's weird for it to be placed right there in the entry editing view. Especially when you consider the "Remove" button right below it doesn't actually remove the entire asset, just its use within that entry.

Maybe something can be done about this? If I had to give my own view on this, I wouldn't even have that button there to begin with, realistically it should only be in the Assets view. I should note that the Craft language is set to Dutch in our client's case, but in English I can see the same confusion happening.

### Steps to reproduce

1. Have an entry with an Image field
2. Upload an image to the field
3. Click the three dots on the image and click "Replace file"
4. Select a new image and submit it

### Expected behavior

Judging by the text on the button I'd expect the image to be replaced *on that entry only*.

### Actual behavior

The entire asset is replaced, on every field that uses it.

### Craft CMS version

5.2.7

**Comment by brandonkelly** [comment]
Agree, that’s a little dangerous. I just removed that action from asset chips and cards, for Craft 5.4 (52480638fe12e95a89971807228c9bfe4b6f91c2).

The action will still be available within asset slideouts, where it’s more obvious what will happen.

**Comment by brandonkelly** [comment]
Craft 5.4.0 is out with that change. Thanks for the feedback!
