### ISSUE TITLE
Using "Edit Entry" from the entry index page will cause IE 11 to slow down/freeze

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#1549]
### Description

Tested with Happy Lager database, but suspect a fresh install would do the same.

### Steps to reproduce

1. Install HappyLager database.
2. Go to entry index page.
3. Check an entry check box and click "Entry Entry" from the action menu.
4. Release your anger at Internet Explorer and the state of the web in general.

### Additional info

- Craft version: 2.x and 3.x
- PHP version: 7.0
- Database driver & version: n/a
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Fixed via 853bbadecb89cfbf4084becc35fc6ffb03a83fbe
