### ISSUE TITLE
[5.x]: Link Field Does Not Retain Section and File Selection Options After Saving

### ISSUE THREAD

**Issue by alexanderloewe** [craftcms/cms#15491]
### What happened?

I'm experiencing an issue with the new Link field in Craft CMS where the options for selecting sections and files are not retained after the field is saved.

### Steps to Reproduce:
- Create a new Link field in Craft CMS.
- Set up the field to allow selecting specific sections and files.
- Save the field settings.
- Reopen the field settings to verify if the selections are retained.

### Expected Behavior:
The section and file selection options should be retained after saving the field.

https://github.com/user-attachments/assets/c18a991e-11bd-4e56-a33a-5cd2849a2c9d

### Craft CMS version

5.3.0.1

### PHP version

8.3

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.3.1 is out with that fix. Thanks again!

**Comment by alexanderloewe** [comment]
Thanks to P&T :)
