### ISSUE TITLE
[5.x]: Plugin table not found during site install

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#15506]
### Description
In my SEO plugin, I'm listening for `Sites::EVENT_AFTER_SAVE_SITE` to add default values in my now table for the new site. ([here](https://github.com/studioespresso/craft-seo-fields/blob/develop-v5/src/SeoFields.php#L312-L319))

When installing the plugin on its own, that works - but when installing from existing project config files, that contain the plugin, this failed because the table can't be found - (yet?)

```bash
Exception: The table does not exist: {{%seofields_data}} (/var/www/html/vendor/yiisoft/yii2/db/ActiveRecord.php:442)
#0 /var/www/html/vendor/yiisoft/yii2/db/ActiveRecord.php(266): yii\db\ActiveRecord::getTableSchema()
#1 /var/www/html/vendor/yiisoft/yii2/db/ActiveRecord.php(238): yii\db\ActiveRecord::filterValidColumnNames(Object(craft\db\Connection), Array)
#2 /var/www/html/vendor/yiisoft/yii2/db/ActiveRecord.php(195): yii\db\ActiveRecord::filterCondition(Array, Array)
#3 /var/www/html/vendor/yiisoft/yii2/db/BaseActiveRecord.php(110): yii\db\ActiveRecord::findByCondition(Array)
#4 /var/www/html/vendor/studioespresso/craft-seo-fields/src/services/DefaultsService.php(115): yii\db\BaseActiveRecord::findOne(Array)
#5 /var/www/html/vendor/studioespresso/craft-seo-fields/src/services/DefaultsService.php(63): studioespresso\seofields\services\DefaultsService->getRecordForSiteId(NULL)
#6 /var/www/html/vendor/studioespresso/craft-seo-fields/src/services/DefaultsService.php(123): studioespresso\seofields\services\DefaultsService->getDataBySiteId(NULL)
#7 /var/www/html/vendor/studioespresso/craft-seo-fields/src/SeoFields.php(319): studioespresso\seofields\services\DefaultsService->copyDefaultsForSite(Object(craft\models\Site), NULL)
```

Checking the database I see that table doesn't exist yet, and in the plugins table I can see that the plugin isn't actually installed yet - I think.

I tried wrapping my event listeners in `Craft::$app->onInit(function () {});` but the error still happens.

What would be the best way to fix this? Thanks!

### Craft CMS version

5.3.0.3

### PHP version

8.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
The problem is that your code is latching onto the `EVENT_AFTER_SAVE_SITE` event, which is triggered during install, before the plugin itself has been installed (and your tables have been created).

If you change [this condition](https://github.com/studioespresso/craft-seo-fields/blob/7df7be619eeb4d1cc585f0c09f18046f32b096d4/src/SeoFields.php#L316) to:

```php
if ($event->isNew && SeoFields::getInstance()?->isInstalled) {
```

It will avoid that error, however you’ll need to test whether that causes other issues downstream.

**Comment by janhenckens** [comment]
Thanks @brandonkelly! Just so I understand how or why this is happening: the event listener gets triggered even though the plug-in is not enabled yet? But the same behaviour doesn't happen for for example element events? Or is this something specific to the install process?

**Comment by brandonkelly** [comment]
@janhenckens Sorry, I realized this is an unintended change in behavior in 4.11 and 5.3, due to [this change](https://github.com/craftcms/cms/commit/369807d9b8da0ff0968e292591eee5f8924b57cc).

Just released 4.11.2 and 5.3.3 with a fix, so plugins don’t get instantiated until Craft is actually ready to install them.

**Comment by janhenckens** [comment]
Thanks @brandonkelly!

**Comment by boboldehampsink** [comment]
@brandonkelly these changes seem to break it for me. The schemaVersion is now always 1.0.0 according to Craft

**Comment by i-just** [comment]
@boboldehampsink, this will happen if the plugin doesn’t specify the `$schemaVersion` property. Here’s a related issue: https://github.com/craftcms/cms/issues/15559. We’ll discuss this internally.

**Comment by brandonkelly** [comment]
Craft 4.11.4 and 5.3.5 are out with a fix for this. Thanks again for reporting!
