### ISSUE TITLE
[5.x]: Cannot reorder Matrix field blocks

### ISSUE THREAD

**Issue by rgauthier4c4** [craftcms/cms#15505]
### Description
I have a matrix field used as a page builder with about 12 differents entrytypes. We have create one block of each to test them. Now we want to move them around and change the order. When moved, the autosaved is trigger with the confirmation of the new position saved. But when we reload the page, the order is back

### Steps to reproduce

1. Create a matrix field with multiple entrytypes
2. Create differents entries in your matrix field
3. Move one entry around and wait for the new position saved message
4. Save the page
5. The order is different from what was saved

### Expected behavior
The order is the same before and after the save.

### Actual behavior
The order is changed and doesn't respect the order that i've set

Image 1 : The current list of blocks
Image 2 : One item has his position moved (block image cards before tabs)
Image 3 : After the save, the item is shifted 2 places up ( block image card is now over block medias)

<img width="1573" alt="1" src="https://github.com/user-attachments/assets/868aaff3-bdcf-4145-8e1e-73c8860d4078">
<img width="1573" alt="2" src="https://github.com/user-attachments/assets/9cdf9c54-7f3e-44fc-943a-7b7c69521346">
<img width="1573" alt="3" src="https://github.com/user-attachments/assets/0c4dcfd6-4725-4113-bb9c-b86671007364">

### Craft CMS version

5.3.1

### PHP version

8.2.15

### Database type and version

mysql 8.0

### Installed plugins and versions

-
craftcms/aws-s3                       2.2.1
craftcms/ckeditor                     4.1.0
nystudio107/craft-code-field          5.0.0
mmikkel/cp-field-inspect              2.0.2
spicyweb/craft-embedded-assets        5.1.1
verbb/hyper                           2.0.3
verbb/image-resizer                   4.0.0
nystudio107/craft-retour              5.0.2    
putyourlightson/craft-sendgrid        3.0.0
nystudio107/craft-seomatic            5.1.1
studioespresso/craft-splashingimages  5.0.3
putyourlightson/craft-sprig           3.3.0
nystudio107/craft-twigpack            5.0.0

**Comment by i-just** [comment]
Hi, thanks for reporting! I was able to replicate this. It's related to the nested entries being disabled. I raised a PR for it.

**Comment by brandonkelly** [comment]
Craft 5.3.2 is out with the fix for this. Thanks again!
