### ISSUE TITLE
[4.x]: 4.11.02 creating errors in Hyper

### ISSUE THREAD

**Issue by iainhenderson** [craftcms/cms#15501]
### Description

We recently updated a site from 4.10.6 to 4.11.02. After the update edit pages with Hyper fields started displaying this error:

![Screenshot 2024-08-08 at 11 15 18 AM](https://github.com/user-attachments/assets/70537f01-686e-4231-b9c8-aee813cf6248)

We then noticed 4.11.1 was available with a fix for a javascript error, so we upgraded to  4.11.1 the first JS disappeared, but the Hyper fields do not render at all and the new JS error is:

![image (1)](https://github.com/user-attachments/assets/94333fc3-5f2e-4939-a40d-0c6e96fbeb42) 

Rolling back to CraftCMS 4.10.6 resolved the JS issues. At no point in this process was Hyper updated. (1.2.0 installed)

We can create **new** pages, with **new** Hyper fields successfully under 4.11.1. But all existing Hyper fields fail for any entry saved under 4.11.0.2 . It may be Hyper has saved corrupted config as it was expecting something from Craft  - which wasn't supplied due to Craft's JS error.

ping @engram-design 

### Steps to reproduce

1. Create an entry with Hyper fields in CraftCMS 4.10.6, Hyper 1.2
2. Upgrade to Craft 4.11.02
3. Resave the entry, refresh page and see JS error in the console
5. Upgrade to 4.11.1
6. Reopen previous entry

### Expected behavior

Hyper fields are visible and JS is not broken

### Actual behavior

Hyper fields are not rendered, a number of CMS functions are broken due to JS error

Ping @engram-design 

### Craft CMS version

4.11.02

### PHP version

8.3

### Installed plugins and versions

Hyper 1.2
Neo 4.2.9

**Comment by engram-design** [comment]
Thanks to @brandonkelly for the assistance with this, fixed in [Hyper 1.2.1](https://github.com/verbb/hyper/releases/tag/1.2.1)

**Comment by iainhenderson** [comment]
Brilliant, thanks @engram-design and @brandonkelly for fixing that so quickly.

**Comment by leevigraham** [comment]
Related ticket: https://github.com/verbb/hyper/issues/182

**Comment by engram-design** [comment]
@leevigraham Just FYI, that issue is more related to a combination with Neo, but does raise a similar error about disclosure.

**Comment by leevigraham** [comment]
Fixed in https://github.com/spicywebau/craft-neo/commit/73d46c1dd1d8f103f29d79c24c20c88c28ef0e9c
