### ISSUE TITLE
[5.x]: Categories not showing in structured table view

### ISSUE THREAD

**Issue by iamtompickering** [craftcms/cms#15503]
### Description
I have just pulled down a database from our staging environment, where I had created some new categories. 

But when I try and view the new categories locally, they do not show up on the structured table view, see Loom video below.  

https://www.loom.com/share/0e6e3e6892b7479983dc197e3cc0b0fe

I managed to resolve it by going into one of the categories via another view and hitting save. After that, all of the categories in that group were visible again via the structured table view. So could be some sort of indexing issue?

### Steps to reproduce

1. Create categories on staging environment
2. Download staging DB and import locally
3. Try viewing the new categories via structured table view

### Craft CMS version

5.3.0.3

### PHP version

8.2.21

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch. Are there any errors in the console (or in the logs) when this happens?

**Comment by iamtompickering** [comment]
Hi @i-just I've just tried to replicate this issue to check the console / logs now and it is not longer happening!

I have recently updated the site to 5.3, so maybe there was a fix for this in that release.
