### ISSUE TITLE
[5.x]: SearchScore return null - Graphql

### ISSUE THREAD

**Issue by The-Dan-Main** [craftcms/cms#15513]
### Description
When you try to get the searchScore through GraphQL, it always returns null. In the OrderBy parameter, it does not acknowledge "searchScore", but "score", which is fine, but the "score" attribute on entries does not exists.

### Steps to reproduce

1.Graphql entries with searchScore on a search Query

### Expected behavior

to return the score for each entry, which came back from the search

### Actual behavior

The attribute does always return null

### Craft CMS version

5.3.1

### PHP version

7.3.10

### Operating system and version

Plesk Obsidian with Debian Base

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 5.3.2 is out with a fix.
