### ISSUE TITLE
Allow overriding route variable set by entries/saveEntry

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#1551]
If you're already on an existing `entry` url and you have a `entries/saveEntry` form, your `entry` variables will conflict.

Example:
```
{% extends '_layouts/page' %}

{% block main %}
  <h1>{{ entry.title }}</h1> {# e.g. "Submit New Entry", from section "pages" #}
  
  <form
    method="post"
    action=""
    accept-charset="UTF-8">

    {{ getCsrfInput() }}
    <input type="hidden" name="action" value="entries/saveEntry">
    <input type="hidden" name="sectionId" value="23">

    {# Here we want the `entry` returned from entries/saveEntry (sectionId:23) #}
    <input type="text" name="title" required value="{{ entry.title|default }}">
{% endblock %}
```

[The Guest Entries plugin](https://github.com/pixelandtonic/GuestEntries#configuration) has the `entryVariable` for this reason.

Ideally I could do something like:
```
<input type="hidden" name="entryVariable" value="newsEntry">
```

Or I'm open to any other solutions.

**Comment by timkelty** [comment]
This continues to be a pain point for me in lots of builds.

Would love to see it's priority bumped up. Sure, it's an enhancement, but in practice it feels like a bug/oversight.

Or if we can agree on an approach, I can PR. It could be handled the same way as Guest Entries, but it seems better and more flexible to be able to set the var name from the POST (above example). Futhermore, we would probably also want to do it across all elements, not just entries (e.g. listen for `elementVariable` in the POST).

Basic use-case:

- "Pages" section with URI `/my-section/new`
- Page entry renders `entry` things about the page, but also has a `entries/saveEntry` form.
- Catching `entry` errors from `entries/saveEntry` and rendering page entry details simultaneously is impossible because the `entry` variables conflict.

/cc @brandonkelly

**Comment by brandonkelly** [comment]
would be happy to review/approve PR to address this in Craft 3.

Agree that a post param would be ideal. I guess called `entryVariable` (adjusted for whatever is being submitted).

One request is, the input should be required to be hashed.

```twig
<input type="hidden" name="entryVariable" value="{{ 'errorEntry'|hash }}">
```

```php
$entryVariable = Craft::$app->getRequest()->getValidatedBodyParam('entryVariable') ?? 'entry';
// ...
```

**Comment by timkelty** [comment]
Sounds good, I'll work on a PR.

**Comment by timkelty** [comment]
Only took me 3 years.

Duplicate of https://github.com/craftcms/cms/issues/6240
