### ISSUE TITLE
[5.x]: Link field with only one link type defined doesn't show up in some scenarios

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#15515]
### Description

A LInk field with only one defined link type doesn’t appear on the edit entry page (depending on the one link type).

### Steps to reproduce

1. On a fresh Craft 5.3.x installation, create a new Link field and select “phone number”.

![CleanShot 2024-08-09 at 15 16 12@2x](https://github.com/user-attachments/assets/8b76ce8e-587a-4805-8ea5-5ce71bc931fd)

2. Add that field to an entry type and that entry type to a section.
3. Create a new entry in that section.
4. Notice the link field doesn’t show a phone number option.

![CleanShot 2024-08-09 at 15 21 07@2x](https://github.com/user-attachments/assets/f37a5063-e559-44de-85b5-e192411b3cb4)

5. If you add a 2nd link type to the settings, they both appear fine.

![CleanShot 2024-08-09 at 15 23 09@2x](https://github.com/user-attachments/assets/9a046275-dc32-4360-8c0d-797572d38748)

6. The URL link type seems to be an exception in that if it’s the only one selected, it shows up fine.

![CleanShot 2024-08-09 at 15 24 22@2x](https://github.com/user-attachments/assets/eac877f1-3b36-4403-b21b-7e4b9cdf71c5)

### Craft CMS version

5.3.1

### PHP version

8.2

### Operating system and version

macOS

### Database type and version

n/a

### Image driver and version

n/a

### Installed plugins and versions

none

**Comment by brandonkelly** [comment]
Hi Angry, thanks so much for posting that! It looks like the same issue has already been reported by #15512, and is fixed for the next release.
