### ISSUE TITLE
[5.x]: Link Field Type Allowed Link Types Phone or Email

### ISSUE THREAD

**Issue by laurabennett** [craftcms/cms#15512]
### Description
When phone or email is the only allowed link type selected the field doesn't display when creating a new entry and therefore cannot be filled in. If you select both or any other allowed link types the field displays as expected.

### Steps to reproduce

1. Create a new field in settings
2. Select Field Type - Link
3. Under Allowed Link Types select ONLY Email or Phone (not both)
4. Add field to an Entry Type
5. Create a new entry
6. The title of this field displays but no input to enter data

### Expected behavior
The input display and validates as expected for phone or email

### Craft CMS version

5.3.1 SOLO

### PHP version

8.2.19

### Operating system and version

Linux 5.15.153.1-microsoft-standard-WSL2

### Database type and version

	MySQL 8.0.33

### Image driver and version

	Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

Calendar	5.0.6
CKEditor	4.1.0
Craftagram	3.0.0
Embedded Assets	5.1.1
Expanded Singles	3.0.0
Feed Me	6.2.1
Field Manager	4.0.2
Hyper	2.0.3
Navigation	3.0.3
SEO	v5.0.0-rc4
User Manual	5.0.2
Vite	5.0.0

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 5.3.2 is out with a fix.
