### ISSUE TITLE
[5.x]: Saving element in afterSave results in integrity constraint violation exception

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#15517]
### Description
If you need to (re)-save an element in its `afterSave`, you will get an integrity constraint violation on the `elements_sites` table, unless you manually include `isNewForSite = false`.

```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '17-1' for key 'elements_sites.idx_yuhsxkwkfvwtibgopgvkaghhoafftioctgde'
The SQL being executed was: INSERT INTO `elements_sites` (`elementId`, `siteId`, `title`, `slug`, `uri`, `enabled`, `content`, `dateCreated`, `dateUpdated`, `uid`) VALUES (17, 1, 'Entry #17', 'foo', 'blog/foo', 1, NULL, '2024-08-10 20:12:30', '2024-08-10 20:12:30', '8db0279e-b40a-4727-b352-cf5db88f64f4')
```

This only happens when trying to save something outside of the normal CP entry form, so it may have something to do with saving directly to a live element vs starting as a draft. Craft 4 has no problem with the same code.

Here's a gist of a contrived example where you want to put the entry ID in the title, so you re-save the entry in the `afterSave` event: https://gist.github.com/timkelty/1cfb09a9611587552ed0f81ab99b1af7

### Craft CMS version

5.3

### Related Issues
https://github.com/craftcms/craftnet/pull/1098

**Comment by steverowling** [comment]
The problem also manifests for me on Craft 4.11.0.2, when using the `afterPropagate` event handler.

Adding the `event->sender->isNewForSite = false;` line from the gist resolves the issue.

This only appeared to start happening after updating to Craft 4.11.0.2 from 4.10.8. Perhaps related to this item in the 4.11.0 changelog:

```
Fixed a bug where $element->isNewForSite was always false from fields’ normalizeValue() methods when propagating an element to a new site.
```

For reference, my site is not multisite, if that makes any difference.

**Comment by i-just** [comment]
@steverowling, thanks for the additional info! We’re looking into it.

**Comment by timkelty** [comment]
ah thanks @steverowling! I must have been testing an earlier version of 4.x

**Comment by mckenzieclark** [comment]
@brandonkelly thanks for addressing! Could this fix also be added to 4.x?

**Comment by brandonkelly** [comment]
Craft 4.11.2 and 5.3.3 are out with a fix for this!
