### ISSUE TITLE
[5.x]: Front end save-user not uploading to asset fields

### ISSUE THREAD

**Issue by iamtompickering** [craftcms/cms#15511]
### Description
This issue only seems to be happening since updating to 5.3. 

The following form is not uploading the image I add to the file input to the asset field in the CMS. It creates the asset, but does not link it up to the field `headerImage`

```
<form method="post" accept-charset="UTF-8" enctype="multipart/form-data">
    {{ csrfInput() }}
    {{ redirectInput(url(craft.app.request.getPathInfo, { notification: 'profileUpdated' })) }}
    <input type="hidden" name="action" value="users/save-user">
    <input type="hidden" name="userId" value="{{ currentUser.id }}">

    <input type="file" name="fields[headerImage][]">
    <input type="submit" value="Submit">
</form>
```

This was working absolutely fine whilst running a 5.2.x version

### Craft CMS version

5.3.1

### Installed plugins and versions

-

**Comment by timdov** [comment]
+1 experiencing the same issue here.

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 5.3.2 is out with a fix.
