### ISSUE TITLE
[5.x]: Missing Database Backup Button

### ISSUE THREAD

**Issue by sandrodunkel** [craftcms/cms#15510]
### Description
After updating to the newest Craft version the _Database Backup_ button in the _Utilities_ section is missing.
Edit: This only seems to happen in my local dev environment using ddev/docker. In prod, everything works as expected.

### Steps to reproduce

1. Update Craft CMS to 5.3.1
2. Go to section _Utilities_

### Expected behavior

The third link from the bottom should be _Database Backup_.

### Actual behavior

_Database Backup_ link is missing.

### Craft CMS version

Pro 5.3.1

### PHP version

8.2.20

### Operating system and version

MacOS Sonoma 14.1.1

### Database type and version

MySQL 8.0.36

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- CKEditor 4.1.0
- Cookies 5.0.0
- Dashboard Begone 3.0.0
- Matrix Extended v3.5.0
- SEOmatic 5.1.1

**Comment by i-just** [comment]
Hi, thanks for reaching out. 

Could you please confirm that you don’t have the `backupCommand` in your `config/general.php` or `CRAFT_BACKUP_COMMAND` in the `.env` file set to `false`? 

Also, it would be good to know which version you've updated from.

**Comment by sandrodunkel** [comment]
I migrated from using MAMP (with backup commands) to using ddev (no backup commands). I correctly removed the backup commands. Turns out emptying the cache is what fixed the issue now. My bad. Thanks anyways!

**Comment by i-just** [comment]
Glad you got to the bottom of it!
