### ISSUE TITLE
[5.x]: fields/merge allow outgoing field instructions/label to persist in field layouts

### ISSUE THREAD

**Issue by myleshyson** [craftcms/cms#15528]
### Description
Our team is currently trying to update to 5.x, and as part of that we're working on cleaning up our matrix fields. The `fields/merge` command works great for a lot of cases, but we're noticing that it's missing the ability to keep the outgoing fields instructions/label in the field layout during merge.

For example, after updating to 5.x we now have several summary fields in the global space, `summary`, `summary2`, `summary3`, etc. Each of those fields have their own instructions because they're in different contexts. 

Currently, if I were to run `fields/merge summary summary2`, the instructions for `summary2` on any of it's field layouts are overridden by `summary`, which isn't what we want for this particular case. 

Wondering if ya'll would be down to add an option (or group of options) to the `fields/merge` command to add the ability to fine-tune the merge process.

Thinking maybe something like this would be nice.
```shell
php craft fields/merge summary summary2 --keep-outgoing-instructions --keep-outgoing-label
```

This way, we can ensure our field handles are merged (so our templates work again) and we have minimal impact for our content team as the instructions in each context would be the same.

### Craft CMS version

5.3.0.3

### PHP version

8.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
The command will ensure that the field labels, handles, and instructions remain consistent with how they were before:

https://github.com/craftcms/cms/blob/812a7db96a9368f36c5653db761c355afc5bde2e/src/console/controllers/FieldsController.php#L360-L362

https://github.com/craftcms/cms/blob/812a7db96a9368f36c5653db761c355afc5bde2e/src/console/controllers/FieldsController.php#L416-L423

Just tested to double check that it’s working as expected.

It sounds like that’s what you’re asking for?

**Comment by myleshyson** [comment]
Hey yea so sorry about that. We were just noticing this. The field layout field override vs the actual field itself was tripping us up. Gonna close this.

**Comment by brandonkelly** [comment]
Hah, no worries :) Glad it’s working as expected.
