### ISSUE TITLE
[5.x]: Website button in CP no longer redirects to website

### ISSUE THREAD

**Issue by droemmelbert** [craftcms/cms#15525]
### Description
When clicking the website button in the top left corner of the CP one used to be redirected to the homepage of the website. Now however when I click it, I get redirected to the same page I am currently on.

### Steps to reproduce

1. Login to CP
2. click the website button in the top left corner
3. redirected to the same page you are already on

![Screenshot 2024-08-13 at 10 42 06](https://github.com/user-attachments/assets/d5cfac19-5935-4c9a-9aa8-497695cb1ddb)

### Expected behavior
Website button in top left corner of CP redirects to homepage of website.

### Actual behavior
Website button in top left corner of CP redirects to the same (CP) page you are currently on.

### Craft CMS version

5.3.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
The only way I can reproduce that is if the primary site doesn’t have a URL. Just fixed for the next Craft 4 and 5 releases.

**Comment by brandonkelly** [comment]
Craft 4.11.3 and 5.3.4 are out now with that fix.
