### ISSUE TITLE
[5.x]: 'Entries' field during save populated with other field content which is initially the same field

### ISSUE THREAD

**Issue by lennonpuype** [craftcms/cms#15526]
### Description
When saving an entry or even when it is auto saving after a save using a toggle the first field for example 'CTA Block' gets populated with the second field 'Outro Block' content which. The second field is an identical version of the first field because it makes use of the new mechanic inside craft when adding fields to an Entry type.

See the video below you see the Outro Block gets empty and the content is added to the CTA Block:
https://github.com/user-attachments/assets/1c2ba43d-f137-4a23-bd03-b817a7f8f1f1

### Steps to reproduce

1. Have 2 'entries' fields on an entry starting from the same on in the setup
2. In my situation only 1 entry is allowed on that field
3. Make sure to add an entry to each of the 2 fields
4. When editing using a toggle during the autosave the first field should get populated with the content of the second field. and that isn't supposed to happen

### Expected behavior

When editing the entry it should just save. 

### Actual behavior

Because of some restrictions I set the entry is not saving because the content from the second field gets populated in the first field.

### Craft CMS version

5.3.2

### PHP version

8.3.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 5.3.4 is out now with a fix.
