### ISSUE TITLE
[5.x]: Craft Native Link Field - the native link field don't have the custom title input field

### ISSUE THREAD

**Issue by yumpdevs** [craftcms/cms#15531]
### Description
The craft native link field don't have the link custom title field as showed in Documentation: https://craftcms.com/docs/5.x/reference/field-types/link.html

The current native link field only has the "Action" part for all types of link. 
![Screenshot 2024-08-14 at 14 18 33](https://github.com/user-attachments/assets/be3ffc48-6f1a-4d51-8bcc-b4de3341b7ac)

Is this what it supposed to be and we need to create a matrix block to enable the Custom Link Title?

Hyper and Typed Link Field have the feature which allowe user to select whether they would like to open the link in a new window by using a "open the link in new window" checkbox. Can we have that in the native link field as well?

### Steps to reproduce

1. create a "link" field and use it in any entry.

### Expected behavior
A Link field with two input box will be created, one is "Title", allow user to enter the custom link text, one is "Action", allow user to select link type and enter the link.

If a checkbox "open in new window" can also be added in the field that would be great.

### Actual behavior
Only the input "Action" is created, allowing user to select link type and enter link.

### Craft CMS version

5.3.4

### PHP version

8.2.20

### Installed plugins and versions

-

**Comment by Megafry** [comment]
Hi yumpdevs
You need to create a new entry type to replicate this.
My suggestion:
Create the following fields: 
- `href` as link-field 
- `target` as dropdown-Field

Create a new entry type with the name Link
Create a new Field `linkElement` as Matrix

![image](https://github.com/user-attachments/assets/af4107f4-a712-4c98-825e-0627caebdf9f)

Now you have full flexibility, you can also add new field for:
- Anchor
- URL suffix
- Classe 
- Link title
- Rel (noreferrer)
- Button style
- ...

**Comment by brandonkelly** [comment]
Right, Link is focused only on storing the actual URL/relation/etc., as noted in the PR (#15251).

> Link fields do **not** have the ability to show settings to control `target`, label, etc. Those can be captured via separate custom fields.
