### ISSUE TITLE
[4.x]: `.env` variable normalization of float instead of string results in truncation

### ISSUE THREAD

**Issue by engram-design** [craftcms/cms#15533]
### Description
We have an [issue](https://github.com/verbb/formie/issues/2021) where we want to store a Client ID for OAuth for Slack as an `.env` variable. This looks like: `2833563543.1341693581393`.

The problem is that when this is parsed as an `.env` variable the value is truncated:

```
// .env
SLACK_CLIENT_ID="2833563543.1341693581393"

// php
App::parseEnv('$SLACK_CLIENT_ID');

// produces
2833563543.1342
```

It seems this is due to the [normalization](https://github.com/craftcms/cms/blob/ea7e5395f731525488b7bdee4e087c9cf89d933f/src/helpers/App.php#L436-L444) of variables, and it thinks that this is a float, where it's a string. 

Could some more smarts be added to check if this should be an int/float by checking if the length of the source string and the target int/float are the same before assuming things?

### Craft CMS version

4.11.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next Craft 4 and 5 releases.

**Comment by brandonkelly** [comment]
Craft 4.11.4 and 5.3.5 are out with that fix.
