### ISSUE TITLE
[5.x]: Graphql - Filter elements depending on nested field in matrix field

### ISSUE THREAD

**Issue by yannkost** [craftcms/cms#15547]
### Description
I try to create a graphql query where I can filter a list of products. These products have `variants` that are stored in a matrix field. I now want to query all entries, where the price of at least 1 variant fullfills the conditions. 

```
query MyQuery {
  entries(section: "bikes", offset: 0, limit: 12, relatedTo: [3112]) {
    id
    ... on bikes_Entry {
      id
      title
      variants {
        ... on bikeVariant_Entry {
          id
          buyPriceInclusiveDiscount
        }
      }
    }
  }
}
```

I know that I can filter the variant by doing
```
variants (buyPriceInclusiveDiscount: ">=1000")  { 
.....
}
``` 
But this will only filter the number of variants returned, and not the number of entries itself, which I need for the pagination.
I have read in this [issue](https://github.com/craftcms/cms/issues/10242) that `Craft 5 added full support for querying for nested Matrix entries via GraphQL, using fieldId and ownerId arguments.` But I do not know, how to use them. Any help is appreciated here as I didn't find a working example of a graphql query that filtered entries depending on a field in a matrix field.

### Craft CMS version

5.3.4

### PHP version

5.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
> I now want to query all entries, where the price of at least 1 variant fullfills the conditions.

The only way to accomplish this right now would be with a custom (and poorly-performing) SQL query.

A better approach would be to start storing additional info in custom fields on the top-level entries, dynamically using [Preparse](https://plugins.craftcms.com/preparse-field?craft5) fields. For example you could create a `maxBuyPriceInclusiveDiscount` field with the template:

```twig
{{ element.variants.collect().max('buyPriceInclusiveDiscount') }}
```

Then set `maxBuyPriceInclusiveDiscount: ">=1000"` on the main entry query.



> I have read in this [issue](https://github.com/craftcms/cms/issues/10242) that `Craft 5 added full support for querying for nested Matrix entries via GraphQL, using fieldId and ownerId arguments.` But I do not know, how to use them.

You can enable querying for variants directly by selecting the `Query for entries in the “Variants” Matrix field` option under “Entries” in your GraphQL schema settings. You will then be able to set `field: "variants"` on your `entries`/`entry` GraphQL queries; or use the `variantsFieldEntries` query instead.

But if you were to go that route, you’d need to split the work into two queries: one to get all the matching variant entries and their `ownerId`s, and a second query to fetch the top-level entries.
