### ISSUE TITLE
[5.x]: Link Field doesn't allow Singles to be selected as allowed link types

### ISSUE THREAD

**Issue by adrianjean** [craftcms/cms#15549]
### Description

When allowing the new Link field to access Entries, the following options only show entry types that are channels or structures — all of my singles are not showing in the list of selectable entities. Unsure if this is by design or TBD, but wanted to flag it.

### Steps to reproduce

1. Create a field of type Link
2. Under "Allowed Link Types" select "Entry"
3. Note that any entries of type "Single" are not showing in the list of allowed types.

### Craft CMS version

Pro 5.3.4

### PHP version

8.3.10

### Operating system and version

Linux 5.15.0-118-generic

### Database type and version

MySQL 8.0.30

### Image driver and version

GD 8.3.10

### Installed plugins and versions

AsyncQueue	4.0.0
Button Box	5.0.0
CKEditor	4.2.0
Colour Swatches	5.0.2
Control Panel CSS	3.0.0
Control Panel Nav	5.0.1
Cookies	5.0.0
Device Detect	3.0.0
DigitalOcean Spaces Filesystem	3.0.0
Expanded Singles	3.0.0
Feed Me	6.3.0
Field Manager	4.0.2
Formie	3.0.3
Icon Picker	3.0.0
Knock Knock	3.0.1
Minify	5.0.0
Neo	5.2.0
Retour	5.0.2
SendGrid	3.0.0
SEOmatic	5.1.2
Sherlock	5.1.0
Sprig	3.3.0
Super Table	4.0.2
Typogrify	5.0.1
View Count	2.0.0

**Comment by brandonkelly** [comment]
I’m not able to reproduce that.

<img src="https://github.com/user-attachments/assets/2d0f11f5-4bf9-4347-9a8b-573fe46c4e98" width="266" height="351" alt="A Link field’s settings, highlighting that “Singles” is listed under “Entry Sources”.">

Note that it will only show up as an option if you actually have any Single sections.

**Comment by adrianjean** [comment]
Ah — seems all sections (singles, channels, etc.) that don't have a URL configured in the Section's settings are ignored from this list - which makes perfect sense... you can't link to something that doesn't have a URL.

However, the Single that I have set as the "Home" for the site, prevents me from setting a URL, and so doesn't show up in this list. Maybe this a non-issue because I can simply link to Home with URL type "/" in this field, or code it into my templates. But it did confuse me a bit.

**Comment by brandonkelly** [comment]
The Homepage single is working on my end. Does the site in question have a Base URL?

**Comment by adrianjean** [comment]
Hmm — I am using a Base URL (Settings -> Site -> Base Url) — it's an environment variable to a full url like  `http://www.website.com`

Strange it doesn't show up in my list of selectable pages.
I created a new single and it's also not showing up.
Might be something wrong with this particular site.

**Comment by brandonkelly** [comment]
Yeah that should be fine. And to be clear, your homepage single section has homepage checkbox selected in the section’s site settings, correct?

**Comment by adrianjean** [comment]
That's right — the home checkbox is enabled for that Single.

**Comment by brandonkelly** [comment]
Any chance you can send your Composer files and a database backup into support@craftcms.com so we can look into why it’s not showing up?
