### ISSUE TITLE
[5.x]: `EVENT_DEFINE_ACTION_MENU_ITEMS` gives TypeError

### ISSUE THREAD

**Issue by shifuma** [craftcms/cms#15550]
### Description

Using the example from the events docs: https://craftcms.com/docs/5.x/extend/events.html#event-code-generator

```
use craft\base\DefineMenuComponentEvent;
use craft\elements\Entry;
use yii\base\Event;

Event::on(
    Entry::class,
    Entry::EVENT_DEFINE_ACTION_MENU_ITEMS,
    function (DefineMenuComponentEvent $event) {
        // ...
    }
);
```

I get: `Argument #1 ($event) must be of type craft\base\DefineMenuComponentEvent, craft\events\DefineMenuItemsEvent given`

Is this a docs error? Am I using it wrong?

---

Is this the right thing to use to add something to this menu?

![screenshot_2024_08_17 _11 49](https://github.com/user-attachments/assets/008e2291-2ab7-44e3-a20c-bd3fff9c049c)

### Craft CMS version

5.3.4

### PHP version

8.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Sorry, yes, it should have been `DefineMenuItemsEvent`. Fixed for the next release.
