### ISSUE TITLE
[4.x]: Upgrade jquery-ui to 1.13.<latest> or better 1.14 (newest)

### ISSUE THREAD

**Issue by hiasl** [craftcms/cms#15558]
### Description

Our security consultants advised us to upgrade our Craft 4 installation to the newest version of jquery-ui, which currently seems to be 1.14. There are also new patch versions of 1.13 (.3 oder maybe already .4), which might be easier to replace.

Since we can not replace this in the Craft bundle, when can we expect updates to the newest versions?

### Craft CMS version

4.10.4 (-4.11.3)

### PHP version

8.2

**Comment by brandonkelly** [comment]
Just updated jQuery UI to 1.13.3 for the next Craft 4 and 5 releases.

**Comment by brandonkelly** [comment]
Craft 4.11.4 and 5.3.5 are out with that update.

**Comment by bencroker** [comment]
If I’m reading things correctly, @hiasl, your security consultants will be relieved to hear that jQuery UI was updated to 1.14.0, see https://github.com/craftcms/cms/pull/15582 😉

**Comment by hiasl** [comment]
we are ALL very relieved to hear that ;-) 
thanks @brandonkelly and @bencroker
