### ISSUE TITLE
Bootstrap constants for CRAFT_ENVIRONMENT

### ISSUE THREAD

**Issue by nateiler** [craftcms/cms#1555]
File: cms/bootstrap/bootstrap.php
Line: 24

Since CRAFT_ENVIRONMENT isn't a path, if CRAFT_ENVIRONMENT constant is defined, it will always return false since it's not a path.

Ref: #1554

**Comment by brandonkelly** [comment]
Fixed via 2f74e4cf43b2719553caa642dbe434dcf6ff7311
