### ISSUE TITLE
Highlight delete entry / delete draft

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#1556]
A client just called me to say they deleted an entry when their intention was to delete the draft.

I wonder if the "Delete" button should be relabelled "Delete Entry". Alternatively customise the confirmation when the user is editing a draft to alert them that they are editing a draft and their action will delete the entry. 

Even better… a custom modal with a button for both options: "Delete draft" "Delete entry".

![screen shot 2017-03-22 at 13 16 05](https://cloud.githubusercontent.com/assets/25124/24179241/1535a8d6-0f02-11e7-8f8c-a753de9b86af.png)

**Comment by leevigraham** [comment]
Nice! Just saw this in the latest update. I'm wondering if there's any value adding the issue id to the changelog notes?

**Comment by takobell** [comment]
@leevigraham eventually they'll link to the referenced issue in case anyone wants the context around it
