### ISSUE TITLE
[5.x]: Can't delete entry in matrix field with view mode cards

### ISSUE THREAD

**Issue by AmarHuda1** [craftcms/cms#15575]
### Description
In Craft CMS 5, when a Matrix field with both the `min and max entries` are set to 2, and the view mode is set to `cards` with the `grid style`, the option to delete the entry content is missing . However, if the view mode is change to `inline-editable block`, the delete option appears.

### Steps to reproduce

1. Create matrix with 3 entry type
2. Set both min entries and max entries to 2
3. Set the view mode to card with the style grid
4. Now try to fill the matrix field

### Expected behavior
The option to delete entry content should appear as it does in the inline-editable block view mode.

### Actual behavior
<img width="822" alt="Card view" src="https://github.com/user-attachments/assets/45bca0c6-dfbf-4ac5-84df-e29eb15a0a9d">
<img width="1287" alt="inline-editable block" src="https://github.com/user-attachments/assets/e877ca09-4402-44c6-b997-88494c1fa395">

### Craft CMS version

5.3.4

### PHP version

8.3.10

### Operating system and version

Linux 6.4.16-linuxkit

### Database type and version

MySQL 8.0.35

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.12-98)

### Installed plugins and versions

- CKEditor 4.2.0
- Formie 3.0.3
- Navigation 3.0.3
- SEOmatic 5.1.2

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.3.6 is out with that fix. Thanks again!

**Comment by AmarHuda1** [comment]
Nice, work as expected. Thank you I-just & Brandon
