### ISSUE TITLE
[5.x]: GraphQL product image format WebP not working

### ISSUE THREAD

**Issue by MatthiasBrodelet** [craftcms/cms#15572]
### Description
I'm not 100% if this issue should be posted here or in the CMS repository. Feel free to move it.

I am trying to fetch the product images with GraphQL using an image transform where I need each image in the original format and the WebP format.
Since I have 2 product types I guess I need to define this twice.

```
{
  products {
    id
    title
    slug
    url
    defaultPriceAsCurrency
    ... on coinsAndGoldBars_Product {
      images {
        url: url @transform (transform: "productThumbnail")
        webpUrl: url @transform (transform: "productThumbnail", format: "webp")
      }
    }
    ... on otherProducts_Product {
      images {
        url: url @transform (transform: "productThumbnail")
        webpUrl: url @transform (transform: "productThumbnail", format: "webp")
      }
    }
    variants {
      id
      title
      sku
      price
      stock
    }
  }
}
```
The query does not fail and the transform works but the WebP format is not working.
It just gives the same URL as the normal non WebP URL.

It also seems to return a slightly different path than when I do this with twig.

GraphQL image URL => https://the-house.lndo.site/uploads/products/_productThumbnail/1_4oz-Krugerrand2-Medium.png
Twig image URL => https://the-house.lndo.site/uploads/products/_400x400_fit_center-center_none/1_4oz-Krugerrand2-Medium.png

The working Twig WebP transform also seems to add a product ID in the URL.

### Steps to reproduce

1. Use the query above

### Expected behavior
It should return the path to the WebP version of this image.

### Actual behavior
It just returns the original image format.

### Craft CMS version

5.3.4

### Craft Commerce version

5.0.16.2

### PHP version

8.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Craft 4.11.5 and 5.4.6 are out now with a fix for this, via #15580.
