### ISSUE TITLE
Keep scroll position of live preview

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#1557]
### Description

Editing a field in live preview refreshes the preview and resets the scroll position to 0,0. It would be great if the scroll position could be saved to avoid jumping / re-scrolling.

**Comment by brandonkelly** [comment]
It already does (and I just verified it still works), although it won’t work if some nested `div` within your page is the one that gets scrolled, rather than the `window`.

**Comment by leevigraham** [comment]
Hmm… this might actually be on an older version of Craft. I'll check the updates and report back.
