### ISSUE TITLE
[5.x]: Illegal offset type getPreviewHtml country field

### ISSUE THREAD

**Issue by jeroenlammerts** [craftcms/cms#15583]
### Description
When having a country field added to the sources of the index page of an entry type you get the error `Illegal offset type`

![Capture 2024-08-23 at 12 12 22](https://github.com/user-attachments/assets/97372c70-eb99-4c8c-9db1-7d7a7b3cc2d9)

### Steps to reproduce

1. Create a country field
2. Add the field to an entry type
3. Add the country field to the index page of the entry

### Expected behavior
Not throwing an error and show a preview of the field.

### Actual behavior
Throwing the error `Illegal offset type`

### A possible fix could be
craftcms/cms/src/fields/Country.php
```
    public function getPreviewHtml(mixed $value, ElementInterface $element): string
    {
        if (!$value || !$value instanceof CountryModel) {
            return '';
        }

        $list = Craft::$app->getAddresses()->getCountryRepository()->getList(Craft::$app->language);
        return $list[$value->getCountryCode()] ?? $value;
    }
```

### Craft CMS version

5.3.4

### PHP version

8.3

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by alexanderbuergin** [comment]
Thanks. Same problem here.

**Comment by brandonkelly** [comment]
Craft 5.3.6 is out with a fix for this. Thanks again!
