### ISSUE TITLE
Allow plugins to define their sub-modules via composer 'extra' properties

### ISSUE THREAD

**Issue by nateiler** [craftcms/cms#1559]
Not sure if this adds significant overhead, but it allows the entire plugin config to be managed in one place.

Ref: #1558

**Comment by brandonkelly** [comment]
Yeah I don’t see why not. Overhead would be on par with defining `components` in composer.json, which we already allow. Mostly just the added work in JSON-decoding the file, which is pretty trivial.

**Comment by brandonkelly** [comment]
Worth noting that #1558 will only add support for `extra.modules` for plugins that were manually installed in the `plugins/`folder. For plugins that were Composer-installed, you will need craftcms/plugin-installer [v1.2.0](https://github.com/craftcms/plugin-installer/releases/tag/1.2.0) or later.
