### ISSUE TITLE
[5.x]: Unable to Select Entries from Other Sites in Link Field within a Multisite Setup

### ISSUE THREAD

**Issue by alexanderbuergin** [craftcms/cms#15594]
### Description:

The new Link field introduced in Craft CMS currently lacks the ability to select an entry from another site in a multisite environment. This limitation makes it impossible to dynamically link to entries across different sites within the same project. As a result, users are forced to manually input static URLs for entries from other sites, which negates the dynamic advantages of the Link field.

### Expected Behavior:

Similar to the behavior of the standard Entry field, there should be an option within the Link field to include entries from other sites. This would allow users to select entries from different sites, ensuring that the links remain dynamic and the multisite functionality is properly supported.

### Suggested Solution:

Add an option within the Link field settings to "Show site menu" in the entry selection modal. This would allow users to switch between sites when selecting an entry, just as they can with the standard Entry field.

<img width="686" alt="Bildschirmfoto 2024-08-25 um 00 30 44" src="https://github.com/user-attachments/assets/154fff67-82f4-456d-971c-75a094d2e26c">

### Craft CMS version

5.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Craft 5.3.6 is out now, which adds a site menu to Link fields’ element select modals.

**Comment by alexanderbuergin** [comment]
Thanks Brandon!
