### ISSUE TITLE
[5.x]: Dynamic column heights of field groups in the Slide-Out module

### ISSUE THREAD

**Issue by alexanderbuergin** [craftcms/cms#15590]
## Description
When editing Entry Types within the Slide-Out module, there is a display issue. The height of the columns for the field groups is dynamically set via JavaScript, which leads to inconsistent layouts.

## Problem
1. For example, when one column is eight fields tall and the adjacent column has only one field, a large gap appears.
2. This results in unpredictable drag-and-drop behavior within the Slide-Out. Fields tend to "jump" during the drag-and-drop process, making it difficult to position them correctly.
3. To work around this issue, we have to edit the Entry Type in the settings instead of using the Slide-Out module.

## Current Behavior
Column heights are uneven, leading to large gaps and making drag-and-drop functionality difficult to use.

## Steps to Reproduce
1. Open the Slide-Out module to edit an Entry Type.
2. Observe the column heights across different fields in the groups.
3. Attempt to move a field via drag-and-drop within the Slide-Out module.

## Screenshots
<img width="940" alt="Bildschirmfoto 2024-08-22 um 19 47 44" src="https://github.com/user-attachments/assets/bf23d3b4-c9b5-4c88-aadf-f6df75bb7171">
<img width="975" alt="Bildschirmfoto 2024-08-22 um 19 48 03" src="https://github.com/user-attachments/assets/3edfda76-4e07-4076-85ac-7a77dceb8bcb">

### Craft CMS version
5.3.5

### PHP version
8.3

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.4.0 is out now with that fix. Thanks again!
