### ISSUE TITLE
[5.x]: Order of plain text field

### ISSUE THREAD

**Issue by le-seisme** [craftcms/cms#15609]
### What happened?

When I try to sort a list of entries alphabetically using a plain text field value (other kinds of fields behave as expected), the sorting process is taking accents into account, but it should be accent-insensitive. Database character set is utf8mb4 and collation is utf8mb4_0900_ai_ci.

<img width="1147" alt="image" src="https://github.com/user-attachments/assets/717e4c66-b632-4d86-8e67-daeae3b27602">

### Craft CMS version

Craft Solo 5.3.6

### PHP version

8.3.6

### Operating system and version

Linux 6.8.0-36-generic

### Database type and version

MySQL 8.0.39

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.12-98)

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.4.0 is out now with that fix. Thanks again!
