### ISSUE TITLE
[5.x]: New Table field row alignment issue

### ISSUE THREAD

**Issue by engram-design** [craftcms/cms#15602]
### Description
First create a Table field, attach it to an entry and populate some rows with content. Save the entry.

Then, click a new row, and notice the action icons are slightly misaligned for the new rows.

<img width="654" alt="image" src="https://github.com/user-attachments/assets/bd9db747-cb94-4ae1-a704-8b4eabea5e0d">

Seems to be a lack of `<div class="flex flex-nowrap">` element for newly created rows in JS, as server-rendered rows have this.

![CleanShot 2024-08-27 at 13 04 04@2x](https://github.com/user-attachments/assets/ce29d798-4295-4406-8083-beb530e97bed)

### Craft CMS version

5.3.6

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.4.0 is out now with that fix. Thanks again!
