### ISSUE TITLE
[5.x]: Can't use Twig's 'is array' on eager loaded return

### ISSUE THREAD

**Issue by modelesque** [craftcms/cms#15618]
### Description

I'm querying for some entries and eagerloading a relation field. The relation field is returned as a `craft\elements\ElementCollection` object that behaves like an array in Twig (and used to be an array in previous versions of Craft). However, using Craft's Twig test `is array` returns `false`.

### Steps to reproduce

1. Query for some entries like `{% set entry = craft.entries.sectionId(1).with(['relatedTopics']).one() %}`.
2. Make sure you're eagerloading elements like my `relatedTopics` field.
3. Run a test like `{% dd entry.relatedTopics is array %}`.
4. The output reads `false` even though `relatedTopics` was returned in the query.

### Expected behavior
I understand that `is array` tests for an actual `array` data type, while using the `with` param returns an `ElementCollection` object, so `false` is technically correct. However, Twig's so simplified that I would expect `is array` to be true in this case. After all, writing this works:
```
{% for topic in entry.relatedTopics %}
   {# loop through the elements as if .all() was called #}
{% endfor %}
```
Otherwise, it gets cumbersome to run a test like:
```
{% if entry.relatedTopics is array or className(entry.relatedTopics) == 'craft\\elements\\ElementCollection' %}
   {# do something truthy #}
{% endif %}
```

So I imagine that an `ElementCollection` evaluates to an array under certain circumstances (like for loops) but fails when tested with `is array`. Excuse me if this is intended and not an issue, but it seemed unintuitive for Twig's `is array` test.

### Craft CMS version

5.3.6

### PHP version

8.2.15

### Operating system and version

Linux 6.10.6-orbstack-00249-g92ad2848917c

### Database type and version

MySQL 8.0.33

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch! 

The `is array` Twig test is an `is_array()` PHP function [underneath](https://github.com/craftcms/cms/blob/5.3.6/src/web/twig/Extension.php#L276-L278), so the test works as expected. 

There‘s a native `iterable` test in Twig which might help you achieve what you’re after. 

Finally, if you need to test specifically for `ElementCollection`, you can use the `is instance of()`.

Given your example, 
- `{% dd entry.relatedTopics is array %}` will return `false`,
- `{% dd entry.relatedTopics is iterable %}` will return `true`,
- `{% dd entry.relatedTopics is instance of('craft\\elements\\ElementCollection') %}` will return `true`.

I hope this helps!
