### ISSUE TITLE
[5.x]: Missing contrast on update spinner in CP

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#15634]
### What happened?

The update spinner appears to have lost most of its contrast in a recent update.

![screenshot-TDkb6Qub@2x](https://github.com/user-attachments/assets/e997b34d-4b5c-4e3c-8906-6fdbb55b1762)

### Steps to reproduce

1. Visit the Entries page in the CP.
2. Add a `sleep()` command to a custom module’s `init()` method to slow down responses.
3. Switch the Entries source to see the update spinner.

### Craft CMS version

5.3.6

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.4.1 is out with a fix for this. Thanks again!
