### ISSUE TITLE
[5.2.0]: LivePreview markup differs from Preview, missing styles

### ISSUE THREAD

**Issue by superextinct** [craftcms/cms#15640]
### Description
Solspace Calendar includes a live preview for their Event elements. When opening the preview, the editor panel is not scrollable and is missing some padding:

![craft-calendar-test ddev site_admin_calendar_events_2_default](https://github.com/user-attachments/assets/c6a809ce-c16f-4265-a402-faa7de4bb218)

Live Preview gets initiated [here](https://github.com/solspace/craft-calendar/blob/a3953a0a2c976a7030b1b88628fc26e71e7f8f8c/packages/plugin/src/Controllers/EventsController.php#L480) through `Craft.LivePreview.init`, that's why I'm opening the issue here.

I believe this to be caused by this commit https://github.com/craftcms/cms/commit/e1d523ab4b022b7e7146c8bf5182a93b4096d760 

While the new `.lp-content` class was introduced to the Preview class, it's not being used for LivePreview:

<img width="375" alt="Bildschirmfoto 2024-09-02 um 13 03 51" src="https://github.com/user-attachments/assets/f765835c-d8ea-4ccd-8cfc-b0d7d7a5c5f6">

### Steps to reproduce

1. Install Solspace Calendar 
2. Configure a preview target for the default calendar (/admin/calendar/calendars/default)
3. Create and save a valid event
4. Open Live Preview

### Expected behavior

All fields should be visible, the editor panel should have horizontal padding and can be scrolled.

### Actual behavior

Due to the missing padding, some fields are not fully visible. The panel cannot be scrolled.

### Craft CMS version

5.2.0

### PHP version

8.2

### Installed plugins and versions

- "solspace/craft-calendar": "^5.0.7"

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 5.4.0 is out now with that fix. Thanks again!
