### ISSUE TITLE
[4.x]: 410 Error Page/Template Not Loading

### ISSUE THREAD

**Issue by terryupton** [craftcms/cms#15644]
### Description

I am using Retour and I am removing a load of old news pages (section) for a client.
I have added regex and I have set the error to a 410 (gone).
I have created a bespoke template (my 404 and 503 error templates load and show).
However, the 410 page is just getting the default chrome message and not the bespoke template.

I assumed Craft would route the error to the default template without any additional server config. 

What steps am I missing?
I am on a nginx server. (Ploi).

### Steps to reproduce

1. Visit an page that has been removed and re-toured to a 410 error.

### Expected behavior
Show the custom bespoke 410 error page.

### Actual behavior
Get a standard browser error page.
![image](https://github.com/user-attachments/assets/f755b061-71b3-4d54-a0f6-76c27d7ba4d3)

### Craft CMS version

Craft Pro 4.11.5

### PHP version

8.3.10

### Operating system and version

Linux 5.15.0-118-generic

### Database type and version

MySQL 8.0.39

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Just tested locally with a custom `410.twig` template, and a `test.twig` template that has:

```twig
{% exit 410 %}
```

And when I request `/test`, my custom 410 template is rendered, with a `410` response code.

So everything is working as expected, as far as Craft’s error handling is concerned. Can’t speak for Retour, though.

**Comment by terryupton** [comment]
Thanks @brandonkelly 
Would you expect this to work out the box on a NGINX server or expect some additional config be required for loading a custom 410 error page? As I said the 404 and 503 custom pages show correctly, so I assumed it would 'just work' :-)

I have also added the {% exit 410 %} and this does in fact load the template correctly. So maybe this is something with Retour? I will reach out on their repo. 

Thanks

**Comment by brandonkelly** [comment]
I’m not an nginx expert, but I am testing on nginx locally. I would imagine you’d have to go out of your way to have nginx handle 410 responses differently from 404s.

Considering `{% exit 410 %}` is working as expected for you, it’s almost certainly going to be a Retour issue, rather than nginx/Craft.

**Comment by khalwat** [comment]
@brandonkelly sort of. If you try the analogous thing in Craft:

```twig
{% redirect "/" 410 %}
```

...you'll get the same generic browser error page. I think this is just how some browsers handle an incoming response with a `Location` and the response code set to `410`.

I'm not sure there is anything I can actually do about this, except _maybe_ special-case for a `410` and route through Craft in that case, but that feels icky.

**Comment by khalwat** [comment]
I'm pretty sure this is just a result of Nginx not being configured to send `410` errors to Craft the way it is typically configured to send `404` errors through to Craft.

Ensure that your webserver is set up to redirect not just `404` errors but also `410` errors through Craft like this:

https://github.com/nystudio107/nginx-craft/blob/master/sites-available/basic_localdev.com.conf#L33

```
    # 410 error handler
    error_page 410 /index.php?$query_string;
```

**Comment by brandonkelly** [comment]
Maybe this is just more of a browser thing? I just tested `{% redirect '/' 410 %}` locally, and got the expected response per the browser’s Network tab, but the page isn’t redirecting to `/` as expected, despite getting the `location` header back.

**Comment by terryupton** [comment]
> # 410 error handler
>     error_page 410 /index.php?$query_string;

Thanks for the feedback. 
I can confirm that this code is in place and still getting the default browser 410 age.


it is a shame we can't use the custom template because when removing a whole section (like news in this instance) it would be nice for the user to see the site with a custom error and so they can move around the site still, rather then as per the default error, it appears as a completed dead website/domain.

**Comment by terryupton** [comment]
I will also just add that in Chrome you do get the default browser error page.
```
This dev.frostslandscapes.co.uk page can’t be foundIt may have been moved or deleted.
HTTP ERROR 410
```

However, in Safari, you get nothing, just a blank white screen.
<img width="1910" alt="Screenshot 2024-09-03 at 17 17 46" src="https://github.com/user-attachments/assets/5ffc96a3-00b0-4f46-b266-b904825592db">
Which I think this thread alludes to:
https://github.com/nystudio107/craft-retour/issues/295

Which is way worse for the end user.

I will test Firefox later when I have it on that machine.

**Comment by khalwat** [comment]
@brandonkelly yeah it could very well be a browser thing; I've only tested it with Chrome

@terryupton, did you restart Nginx after changing that config code? It won't take effect until you do

**Comment by brandonkelly** [comment]
I was testing in Firefox, which like Safari, just gives you a blank page.

**Comment by terryupton** [comment]
> @brandonkelly yeah it could very well be a browser thing; I've only tested it with Chrome
> 
> @terryupton, did you restart Nginx after changing that config code? It won't take effect until you do

Yes I restarted Nginx.

**Comment by brandonkelly** [comment]
410 isn’t an expected response code when a `location` header is sent (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location) so that explains why browsers aren’t handling it consistently.

**Comment by terryupton** [comment]
Do we need to send a `location` header? If it is "gone' does it need a `location` as it isn't really a redirect?
Could Retour handle without a `location` @khalwat ? At the moment it defaults to /

**Comment by brandonkelly** [comment]
Isn’t the entire point of Retour to send `location` headers?

**Comment by khalwat** [comment]
So as it turns out, there was already code in there special-casing for > 400 errors, because we need to render them directly rather than return them... but the issue is it wasn't then just returning the response, it was _redirecting_ the response, which we don't want for a > 400 status code.

This actually _does_ work without having to modify the Nginx config, because Retour is rendering the response itself and returning it, so it isn't then routed through Nginx.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.2.20”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v4 as 4.1.20”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v5 as 5.0.4”,
```
Then do a `composer clear-cache && composer update`

**Comment by terryupton** [comment]
Thanks @khalwat - I can confirm this is working as expected now. 👍🏻
