### ISSUE TITLE
[5.x]: Save entry in slide out panel results in "A server error occurred. "

### ISSUE THREAD

**Issue by dgrigg** [craftcms/cms#15650]
### Description
Attempting to save a Matrix block entry, in a Matrix field that is set as "view mode: cards", via the slide out panel on a structured entry results in a 500 "A server error has occurred". If I change the field settings to "view mode: as inline editable blocks" then I can save the structure with the new blocks and no error occurs. 

### Steps to reproduce

1. Open the Structured entry. 
2. Click on the "new entry" within the Matrix field. 
3. Add the required fields (title) 
4. Click the 'Create entry' button
5. Error "A server error occurred" flashes in the bottom left corner 
6. Checking the network inspector provides shows no response value/content in the network call. 

### Expected behavior
1. Save the entry type without an error.

### Actual behavior
1. The "A Server error occurred" flash each time 

### Craft CMS version

5.4.0.1

### PHP version

8.3.7

### Operating system and version

Linux 5.15.0-102-generic

### Database type and version

MySQL 8.0.39

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>

<meta http-equiv="Content-Style-Type" content="text/css">
<meta name="Generator" content="Cocoa HTML Writer">
<meta name="CocoaVersion" content="2299.77">

</head>
<body>

CKEditor | 4.2.0
Embedded Assets | 5.1.2
Formie | 3.0.5
Hyper | 2.0.4
Navigation | 3.0.3
Postmark | 3.1.0
SEOmatic | 5.1.2
Sprig | 3.5.0
Vite | 5.0.1
Wordsmith | 5.0.0

</body>
</html>

**Comment by brandonkelly** [comment]
Not able to reproduce that. Try clearing out your `storage/logs/` folder, reproducing the error, and then searching through `storage/logs/` for `[web.ERROR]`. You should find a full error report, including the stark trace. Please post that here.

**Comment by dgrigg** [comment]
@brandonkelly no errors show up in the web log, just INFO. A little more info. It only happens on our staging server. In the local dev environment everything saves correctly.  Checked PHP logs, no errors there.

**Comment by brandonkelly** [comment]
Try again with your browser’s Network tab open. Do you get any non-200 Ajax requests logged when the error occurs? If not, what about JavaScript errors?

**Comment by dgrigg** [comment]
@brandonkelly network shows outgoing request but a completely empty response. No javascript errors in the console. Thinking out loud, possibly a CORS issues as its only happening with Ajax saves via the slide out panel instead of full http posts using the inline editor.  Would that make sense? The odd thing I just noticed, if I refresh the page after the failed save, the content is there so the server is getting the data and saving it something in the response is not being handled causing the error.

**Comment by dgrigg** [comment]
Forgot to mention the response shows a 302 status code

**Comment by brandonkelly** [comment]
Any chance you can send your Composer files and a database backup into support@craftcms.com?

**Comment by dgrigg** [comment]
@brandonkelly sending everything over. I also recorded a video to help show exactly what is happening.

**Comment by dgrigg** [comment]
@brandonkelly following up on this. It looks like the culprit was a Nginx configuration adding trailing slashes to the admin urls.

**Comment by brandonkelly** [comment]
Ah ha! Glad you got it sorted!
