### ISSUE TITLE
[5.x]: Incorrect offset of sort icon

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#15655]
### What happened?

The sort icon is incorrectly offset when sorting columns in element index pages.

![screenshot-32ObWpyx@2x](https://github.com/user-attachments/assets/9f498e9d-b4ca-44de-8e0f-522202be615f)

### Steps to reproduce

1. Visit an element index page.
2. Click a sortable column header.

### Craft CMS version

5.4.0.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed in 5.4.1.
