### ISSUE TITLE
[5.x]: Unable to edit URL Link Field on multi-entry edit on element view

### ISSUE THREAD

**Issue by akukral** [craftcms/cms#15653]
### Description

In element view on a structured entries page editing multiple entries at once unable to change or edit Link Field type entries that are as URL in selection dropdown.

![image](https://github.com/user-attachments/assets/0c4e9704-9cfd-4f07-88cc-45482b086b44)

### Steps to reproduce

1. Structure of entries with Link field type as part of entry type
2. Link field type as a default visible field in the customize sources in structured table view.
3. Click "Edit" in the element table view of the entries tab to edit multiple entries.
4. Elements with existing URL type links have a clickable link and an ellipse.
![image](https://github.com/user-attachments/assets/e535efef-95ae-41c0-b207-cd06dcfbb575) 

### Expected behavior

Clicking within the text area of the URL should highlight the whole text within the field allowing for copy/paste or keyboard input.

### Actual behavior

Unable to utilize keyboard or cursor input to select and delete Link Field text from within the multi-entry edit of the element view of a structure on Link field types that already have a type of URL.

### Craft CMS version

5.4.0.1

### PHP version

8.2.20

### Operating system and version

Mac Sonoma 14.6.1 / DDEV version v1.23.2

### Database type and version

MySQL 8.0.36

### Image driver and version

Imagick 3.7.0

### Installed plugins and versions

- Amazon S3: 2.2.1
- Batch Actions: 2.0.1
- Blitz: 5.7.1
- BlurHash: 3.0.0
- CKEditor: 4.2.0
- Control Panel CSS: 3.0.0
- Embedded Assets: 5.1.2
- Environment Label: 5.0.0
- Feed Me: 6.3.0
- Freeform: 5.5.8
- Matrix Extended: v3.5.0
- Minify: 5.0.0
- Reverse Relations: 3.0.0
- SEOmatic: 5.1.2
- Smith: 3.1.0
- Sprig: 3.5.0

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.4.1 is out with that fix. Thanks again!

**Comment by akukral** [comment]
Thank you. The Craft team is amazing!
