### ISSUE TITLE
[5.x]: Error when saving entries field: "Only structured sources may be used when relating ancestors."

### ISSUE THREAD

**Issue by jeromecoupe** [craftcms/cms#15666]
### Description

I have a `blog` channel with a `blogType` entries field that references a channel called `blogpostsTypes`. Whenever I try to save that field, I get the following error messsage

> Blogposts Types is not a structured source. Only structured sources may be used when relating ancestors. 

I don't quite understand the error message itself, this is a simple relation between each blog entry and an entry from another channel. Cannot find anything obvious related to that error in the logs, nothing in the console either as far as I can see.

The problem seems to lie with the field. I have tried to uncheck Blogposts Types and to check any other source in the "Sources" checkboxes and I get the same error.

> Partners is not a structured source. Only structured sources may be used when relating ancestors. 

### Steps to reproduce

Cannot provide exact steps here. It's a craft 4 project that has been upgraded to Craft 5. It is a small client project that I have been using to test the fields CLI merge tool and the likes. A few fields have changed back and forth between dedicated fields and instances but not that field specifically.

### Expected behavior

I should be able to save the entries field and update the number of min and max relations, which is why I edited the field originally.

### Craft CMS version

Craft Pro 5.4.0.1

### PHP version

8.2.22 (DDEV)

### Operating system and version

Linux 6.6.26-linuxkit (DDEV)

### Database type and version

MySQL 8.0.36 (DDEV)

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- CKEditor 4.2.0

**Comment by jeromecoupe** [comment]
I deleted the field, recreated it and re-linked all `blog` entries to entries in the `blogpostsTypes` channel and the error is gone. I am again able to edit the field and modify its settings.

Upon inspecting the changes on project config, I noticed several changes. Most notably:

- `branchLimit: 1`became `branchLimit: null`
- `maintainHierarchy: true`became `maintainHierarchy: false`

At some point duting this project lifetime, I think that the `blogpostsTypes` might have been defined as a structure before becoming a channel. Maybe some settings stuck around for the ride in project config.

**Comment by jeromecoupe** [comment]
I guess now, my question becomes: after these changes are applied in production, should I download the production DB in my local environment, rebuild project config and redeploy everything ?

**Comment by brandonkelly** [comment]
I was able to reproduce that error if I saved a relation field with only one (structured) source selected, plus the “Maintain hierarchy” setting enabled, and then went and selected additional sources as well and resaved. (The “Maintain hierarchy” setting will automatically disappear when it’s no longer applicable, but it still exists in the DOM and still gets submitted as enabled, causing the error.)

Fixed for the next Craft 4 and 5 releases.

Assuming you have existing relations you don’t want to lose, you should revert the project config changes (or restore a production backup) so the original field comes back.

You can get the fix early by changing your `craftcms/cms` requirement in composer.json to `5.x-dev as 5.4.1` and running `composer update`.

**Comment by jeromecoupe** [comment]
Thanks @brandonkelly. Solved on my side (dev and prod) but good to know that was indeed a bug and that it is now fixed for the next releases.

Small project so recreating those relations was quick. When I deleted / recreated the field, I noticed that the project config file for that field changed in a few places. Wondering if I should now download the DB from prod > local + do `craft project-config/rebuild` locally, commit and redeploy to production (the deployment includes a `craft project-config/apply` command in prod) to make sure everything is in sync. I guess my question is: is this good practice and is there any risk involved in the operation ?

**Comment by brandonkelly** [comment]
@jeromecoupe The bulk of the project config changes are probably going to be a result of the fact that the field’s UUID changed (since it’s a new field). The next time you deploy, the old field will get removed and a new field will get created. So then you will need to recreate those relations on production for the new field. Maybe that’s fine in this case, but still, seems like it would be easier to just revert the changes and apply the bug fix, so there’s no significant project config changes to deploy and content loss involved.

**Comment by brandonkelly** [comment]
Craft 4.12.1 and 5.4.2 are out with that fix!
