### ISSUE TITLE
[5.x]: The content of the prefecture in the address field is not displayed in Japanese.

### ISSUE THREAD

**Issue by mersy** [craftcms/cms#15668]
### Description

When the user's language setting is set to Japanese and an address is registered, only the prefecture is displayed in English. The country is displayed in Japanese. Is it by design that the prefecture is not displayed in Japanese?

The following issue seems to be similar to the current situation.
https://github.com/craftcms/cms/issues/15591

### Steps to reproduce

1. set up address field
2. set address in entry
3. show addres by card

### Expected behavior

While the prefecture can be displayed and selected in Japanese when choosing it, the prefecture is not displayed in Japanese on the card.

#### CP
When the user's language setting is set to Japanese and an address is registered, only the prefecture is displayed in English. The country is displayed in Japanese. 

![20240905-105846](https://github.com/user-attachments/assets/c831006c-3d0b-4147-a217-2afdb809de95)

Is it by design that the prefecture is not displayed in Japanese?

When the user's language setting is set to English, both the prefecture and the country are displayed in English.
![20240905-105928](https://github.com/user-attachments/assets/76761719-88c2-4ecc-a901-75f691629e37)

#### Front-end 
When the site's language setting is set to Japanese, the country is displayed in Japanese, but the prefecture is displayed in English. When set to English, both the country and the prefecture are displayed in English.

**language setting : Japanese**
![20240905-110153](https://github.com/user-attachments/assets/0cae32b3-6bcb-4fa3-a4df-0fcbaa647365)

I would like it to display "東京都" instead of "Tokyo."

**language setting : English**
![20240905-110113](https://github.com/user-attachments/assets/697abc8f-73ec-4cb2-9960-026e1ac8508b)

**Template**

```
{% set addresses = entry.testAddress.all() %}
<ul>
  {% for address in addresses %}
    <li>{{ address|address }}</li>
  {% endfor %}
</ul>
```

### Craft CMS version

5.4.1

### PHP version

8.2.23

### Operating system and version

Linux 3.10.0-957.27.2.el7.x86_64

### Database type and version

MySQL 8.0.35

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.7.8-9)

### Installed plugins and versions

- CKEditor 	4.2.0
- Multi Translator 	2.7.0

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by mersy** [comment]
Thanks!! @i-just

**Comment by brandonkelly** [comment]
Craft 4.12.1 and 5.4.2 are out with that fix! Thanks again.
