### ISSUE TITLE
[5.x]: Base URL is mobbing me: always puts http:// in front of the field i.E. http://$CRAFT_WEB_URL/en/

### ISSUE THREAD

**Issue by pixelwerft** [craftcms/cms#15663]
### Description

When saving the site settings, the field's value of the Base URL is always automatically replaced by 
http://$CRAFT_WEB_URL/en/ instead of $CRAFT_WEB_URL/en/
And even if the http:// is suffixed: please let it be https:// 

### Steps to reproduce

1. Choose a variable in the site settings for the field base_URL.
2. Save it and check the result

### Expected behavior

Content of the field should be $CRAFT_WEB_URL/en/

### Actual behavior

But it is: http://$CRAFT_WEB_URL/en/

### Craft CMS version

Craft Pro 5.4.0.1

### PHP version

8.3.10

### Operating system and version

FreeBSD 13.3-RELEASE-p5

### Database type and version

MariaDB 10.6.18

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.1-26)

### Installed plugins and versions

- Asset Usage, 4.0.0
- CKEditor, 4.2.0
- Field Manager, 4.0.2
- Formie, 3.0.5
- SEO, v5.0.0-rc5
- Translation Helper, 1.0.5
- Vite, 5.0.1

**Comment by brandonkelly** [comment]
`$CRAFT_WEB_URL/en/` is not valid input to begin with. If you want to set the value to an environment variable, you can’t append additional content to it. Instead, define a new environment variable that includes the full URL (`https://example.com/en/`) and set the value to that variable.
