### ISSUE TITLE
[5.x]: Closing the Live Preview enables disabled entries

### ISSUE THREAD

**Issue by elfacht** [craftcms/cms#15670]
### Description

Editing an disabled entry with Live Preview will enable the entry despite the way of closing the preview (X or `Save`). That said, if I want to edit any entry before publishing it the entry will published as soon I would close the preview. This occurs on different projects using Craft CMS.

### Steps to reproduce

1. Create a new entry with `disabled` as default state.
2. Open the `Preview` and edit something.
3. Close the preview by clicking the X icon or `Save` button.
4. Reload the entry without saving it (auto save)
5. See the entry in a `enabled` state.

### Expected behavior

While working in the Live Preview the CMS should respect the entry status as long I am not chaning it manually.

### Actual behavior

The entry status changes as soon I am leaving the Live Preview, despite the desired status.

### Craft CMS version

6.4.1 and prior

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 5.4.2 is out with a fix.

**Comment by elfacht** [comment]
Awesome, thanks for the quick fix!
