### ISSUE TITLE
[5.x]: Is it not possible to show the parent entry when listing out matrix blocks using a custom source

### ISSUE THREAD

**Issue by terryupton** [craftcms/cms#15671]
### Description
So I have a list of matrix blocks so that these are quickly accessible, as they are used across multiple pages/products.
It would be really helpful to allow for a column to show the entry (and a link to it) where the block was originally created (what entry is it's parent). 

I have tried to enable the parent and ancestor fields in case those would show the relationship, but they don't. I can see other use cases for this. 

Is this possible? Am I just missing something or could this be a feature request if not. 

<img width="1835" alt="Screenshot 2024-09-05 at 14 16 57" src="https://github.com/user-attachments/assets/fae1992d-1a41-461a-8df6-910514dccf98">
<img width="1381" alt="Screenshot 2024-09-05 at 13 46 27" src="https://github.com/user-attachments/assets/07257adb-4cd8-465a-95d0-3909ba40ebbd">

Thanks.

### Craft CMS version

Craft Pro 5.4.1

### Installed plugins and versions

-

**Comment by abdulrehman-code** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by brandonkelly** [comment]
That was previously requested via #15230. See my response there for an explanation for why it’s not included out of the box, and how you can add it yourself.
