### ISSUE TITLE
[5.x]: Card's image wont grow to cover its side of the card.

### ISSUE THREAD

**Issue by ZapaNOR** [craftcms/cms#15673]
### What happened?

If the entry type's field layout is set up correctly, an entry type's cards will show an image on the left side.
This image has an max height, and wont cover the entire area. Is this by design?

Personally I think it looks much better when it actually grows to cover.

<img width="916" alt="Screenshot 2024-09-05 at 16 55 55" src="https://github.com/user-attachments/assets/e86664d4-989e-41cf-95d1-4551d1eb8fa4">
<img width="908" alt="Screenshot 2024-09-05 at 16 56 08" src="https://github.com/user-attachments/assets/14ec4cbd-9f6e-4372-887a-5e74cc85b079">

The CSS in question:

.card>.thumb img, .card>.thumb svg {
    max-height: 128px;
    -o-object-fit: cover;
    object-fit: cover;
    width: 100%;
}

### Craft CMS version

5.4.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for pointing that out! We decided to take the thumb styling in a different direction for Craft 5.5, which resolves this issue: #15692.

**Comment by brandonkelly** [comment]
Craft 5.5.0 is out now with that change 🎉
