### ISSUE TITLE
[5.x]: Visual bug on empty "Tip" UI Element

### ISSUE THREAD

**Issue by frederikvdbe** [craftcms/cms#15681]
### Description
Visual bug when adding an empty "Tip" UI Element

### Steps to reproduce

1. Add "Tip" UI Element to any field layout.

### Expected behavior

Either change the appearance when emtpy or make the Tip field in the Tip UI Element required.

### Actual behavior

<img width="193" alt="Screenshot 2024-09-06 at 09 04 07" src="https://github.com/user-attachments/assets/8c0ba656-28bb-4a02-8787-55aef34d36f9">

### Craft CMS version

5.4.0.1

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 4.12.1 and 5.4.2 are out with a fix for that. Thanks again.
