### ISSUE TITLE
[5.x]: Address translation

### ISSUE THREAD

**Issue by olsp** [craftcms/cms#15682]
### What happened?

I would like to translate the subfields of an address field. The city for example has different names in different languages but also the street name may be different. I didn't find a way to translate those fields, is this currently possible?

### Craft CMS version

5.4.1

**Comment by i-just** [comment]
Hi, thanks for getting in touch. Can you please clarify what you'd like to do? Do you want to translate the labels of the address subfield; translate the predefined values that show in dropdowns (like in the country field); something else?

**Comment by olsp** [comment]
Sorry for not being more precise in the first place.
What I would like to do is to translate the contents of the subfields.

So for example I have an address, where the city is Vienna (in English). On the German site, it should be called Wien.
Right now, only the label field can be translated, as indicated with the icon next to the label.

<img width="445" alt="address-fields" src="https://github.com/user-attachments/assets/79e91180-cbd6-4972-a03a-047d5aeefe77">
