### ISSUE TITLE
[5.x]: Section element index view - editing entries throws JS error

### ISSUE THREAD

**Issue by croxton** [craftcms/cms#15694]
### Description
JS error when editing multiple entries and trying to save changes.

<img width="1224" alt="Screenshot 2024-09-06 at 17 15 15" src="https://github.com/user-attachments/assets/14b1b906-c0fc-4ec8-a4d7-a2752833aa81">

### Steps to reproduce

1. Click the `Edit` button when viewing an element index for a section, e.g. `/control-panel/entries/people`
2. Edit one or more field values.
3. Click 'Save'

### Expected behavior
Elements should save without error.

### Actual behavior
JS error thrown:
```console
'TableElementIndexView.js:238 Uncaught TypeError: this.elementIndex.$elements.find(...).timepicker is not a function
```
<img width="1075" alt="Screenshot 2024-09-06 at 17 16 54" src="https://github.com/user-attachments/assets/92a0fa99-bf3f-4c3b-9d65-30597b19ba8b">

### Craft CMS version

5.4.0.1

### PHP version

8.2

### Operating system and version

Mac OSX

### Database type and version

MySQL 8

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 5.4.2 is out with a fix.
