### ISSUE TITLE
[5.4.2]: Matrix block header styling seems 'off'

### ISSUE THREAD

**Issue by nilsenpaul** [craftcms/cms#15703]
### Description
In both Firefox and Chrome on Mac, the styling of the Matrix block headers is as shown in the screenshot. Is this the way it's supposed to look (tab is vertically centered, right side icons and checkbox not vertically centered)?

<img width="678" alt="Scherm­afbeelding 2024-09-10 om 10 02 11" src="https://github.com/user-attachments/assets/fcf9f39b-b173-4898-9e57-b41e0adc3265">

### Craft CMS version

5.4.2

### PHP version

8.2

### Operating system and version

MacOS 14.1.1

### Database type and version

-

### Image driver and version

-

### Installed plugins and versions

CKEditor 4.2.0
Embedded Assets 5.1.2
Feed Me 6.3.0
Position Fieldtype 5.0.0
Postmark 3.1.0
SEOMate 3.1.1
Vite 5.0.1

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.4.3 is out with that fix. Thanks again!
