### ISSUE TITLE
[4.x]: Unknown command '\-' on database import

### ISSUE THREAD

**Issue by iainsaxon** [craftcms/cms#15701]
### Description

This is related to #15277.

The issue is MariaDB introducing a backwards compatibility breaking change to address a security concern as documented in their update notice: https://mariadb.org/mariadb-dump-file-compatibility-change/

DDEV are aware of this and have taken steps to try and work around the issue by removing the opening sandbox line from the database dump if using the `ddev import-db` and `ddev export-db`:
https://ddev.com/blog/mariadb-dump-breaking-change/

Unfortunately these don't help if your automated tools are written to use the `craft db/backup` and `craft db/restore` commands to take advantage of the site's Dotenv configuration and other boilerplate code that Craft brings with it.

While the previous solution for #15277 of setting the database version in the `.ddev/config.yaml` to match the live server or CI pipeline was correct and worked at the time I'm not sure this is still the case.

I was sure I read earlier today that Debian Bookworm images in newer versions of DDEV are no longer compatible with older versions of MariaDB 10.3 but I can no longer find this information to confirm. (Update: this is the page I was thinking of https://jira.mariadb.org/browse/MDEV-34183?focusedCommentId=285055&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-285055)

What I can see in an older project that I just ran `ddev start` on was the version of MariaDB in the `.ddev/config.yaml` is being ignored. This is in the config file:

```
database:
    type: mariadb
    version: "10.3"
```

This is what `mysql --version` returned: `mysql  Ver 15.1 Distrib 10.11.8-MariaDB, for debian-linux-gnu (aarch64) using  EditLine wrapper`

Setting the database version in the DDEV config file no longer appears to resolve the issue.

There are conditional statements in the Craft DB commands related to handling the specifics for the database types.

Does this need to be expanded to add a version comparison for MariaDB so that older clients drop the first line that is causing the DB import command to fail or should this be handled as an event listener for the `EVENT_BEFORE_RESTORE_BACKUP` for developers who need it?

Update 2: after some more testing I found DDEV is potentially using the newer version of MariaDB in the web container.
If I look at the `$e->sender->getSchema()->getServerVersion()` in a DB import event I get `10.3.39-MariaDB-1:10.3.39+maria~ubu2004-log` while the version of MariaDB in `ddev ssh` returns `mysql  Ver 15.1 Distrib 10.11.8-MariaDB, for debian-linux-gnu (aarch64) using  EditLine wrapper`. This suggests that DDEV is always using a newer version of MariaDB in the web image to help mitigate the backwards compatibility issue. This causes issues however if Craft is executing import/export commands using the web image version of MariaDB which we then expect to use on another server.

### Craft CMS version

4.10.4

### PHP version

8.2

### Operating system and version

Debian Bookworm via `ddev version v1.23.4`

### Database type and version

MariaDB 10.3

### Image driver and version

NA

### Installed plugins and versions

- NA

**Comment by brandonkelly** [comment]
What version of DDEV are you running? Supposedly this was improved in 1.23.3 (see ddev/ddev#6083).

**Comment by iainsaxon** [comment]
I'm running `ddev version v1.23.4`.

I checked the versions of `mysql` and `mysqldump` again between the `web` and `db` services and got the following:
```
ddev exec --service web mysql --version
mysql  Ver 15.1 Distrib 10.11.8-MariaDB, for debian-linux-gnu (aarch64) using  EditLine wrapper

ddev exec --service db mysql --version
mysql  Ver 15.1 Distrib 10.3.39-MariaDB, for debian-linux-gnu (aarch64) using readline 5.2

ddev exec --service web mysqldump --version
mysqldump  Ver 10.19 Distrib 10.11.8-MariaDB, for debian-linux-gnu (aarch64)

ddev exec --service db mysqldump --version
mysqldump  Ver 10.19 Distrib 10.3.39-MariaDB, for debian-linux-gnu (aarch64)
```

I had a look at the options for `mysqldump` on the newer `web` image but didn't see a way to disable the sandbox mode so I can't just adjust this in the Craft config.

**Comment by angrybrad** [comment]
@iainsaxon Even if we were to add specific MariaDB version conditionals, I’m not sure how that would work or if it’d be worth it.

We’re ultimately passing our backup commands to `mysqldump`, which is assumed to be available to PHP via a $PATH.

So, we’ll use whatever version is available.

The only thing I could think of is that we could try to add some logic around dumping and restoring MySQL/MariaDB dumps that parses the files and tries to remove incompatible lines. But that’s impractical in cases where you’re processing the files from PHP, and dumps are in the multi-GB range. And it’s also very heavy-handed on our part.

> causing the DB import command to fail or should this be handled as an event listener for the EVENT_BEFORE_RESTORE_BACKUP for developers who need it?

That’s definitely a possibility. Especially if the database size is enough to be parsed by PHP or you exec out to the shell and do some `grep` work.

Given the above, and that we’re no longer [recommending MariaDB](https://craftcms.com/docs/5.x/requirements.html#recommended-system-specs) and that there are workarounds on the DDEV side, I’m not sure we’ll be able to do much with this.

It’s also worth considering moving away from MariaDB to MySQL altogether. This is only one of the many issues and bugs they’ve had over the last few years, and they’ve fallen behind on features that MySQL has. The company has been struggling for a while, and it was recently acquired by a private investment firm, which rarely ends well.

https://www.prnewswire.com/news-releases/k1-acquires-mariadb-a-leading-database-software-company-and-appoints-new-ceo-302243508.html

At any rate, the whole thing is a mess.

**Comment by iainsaxon** [comment]
Understandable. I created the ticket to bring light to the topic in case other developers have had or will have similar issues as I did and try looking online for information. It is an issue specific to development setups like `ddev` where the version of MariaDB differs between the web and DB containers so it (hopefully) shouldn't effect a production environment. I'm thinking the `EVENT_BEFORE_RESTORE_BACKUP` listener might be the way to work around the issue for us.

**Comment by iainsaxon** [comment]
For anyone interested I have tried to address this in an event listener.

```
Event::on(Connection::class, Connection::EVENT_BEFORE_RESTORE_BACKUP, function (RestoreEvent $e) {
            $file = $e->file;

            // See: https://mariadb.org/mariadb-dump-file-compatibility-change/
            $mysqlVersion = $e->sender->getSchema()->getServerVersion();
            $mariaDbDumpCompatibilityFixNeeded = version_compare($mysqlVersion, '10.11.8') < 0;

            // delete any lines containing the sandbox mode
            if ($mariaDbDumpCompatibilityFixNeeded) {
                exec('sed -i -e \'/\/\*\!999999/ d\' ' . $file, $output);
            }
        });
```
