### ISSUE TITLE
[5.x]: Cannot add uploaded assets with \craft\fields\Asset anymore due to BaseRelationField::normalizeValue change

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#15707]
**Sorry if this should have been a discussion / suggestion. I'm not sure if it's a breaking change/bug or not since my usage was never intended in the first place but worked** 

### Description

I used to upload additional assets to asset fields by setting it's field value to the original ids after calling `setFieldValuesFromRequest`. This worked great until one of the last updates... My process was the following.

```php
$entry->setFieldValuesFromRequest('fields');
$entry->setFieldValue('images', $oldImageIds);
```
This will let `\craft\fields\Asset` to search for uploads plus the field will contain a query to all the existing Uploads so it will add them.
https://github.com/craftcms/cms/blob/5e56c6d168524ed02f0620c9bc1c9750f5b94e3b/src/fields/Assets.php#L568-L572

In the lines above, `$query->id` will contain the previous ids since I set them.
However, due to your change in BaseRelationField

https://github.com/craftcms/cms/commit/2ce4b5babe94f6f9b1d016440ea2c8d9817ead34#diff-dd150284a0df94daa2918aaacda81e6ad9b20bac8d429414043f37120a5769ddL677-L680

`$query->id` does not include the asset ids anymore and there is no real way to add assets to the existing one instead of overwriting them all.
I know I used an "unsupported" hack to achieve my goal but since adding/uploading additional assets to an entry is a common task for me, I really hope you could add an event or some other way to achieve this. As of now, I "fixed" it with the following code.

```php
$entry->setFieldValuesFromRequest('fields');
$entry->setFieldValue('images', $oldImageIds);
$entry->getFieldValue('images')->id = $oldImageIds;
```
Which is of cause bad and I do not want to do this.

I considered it as a "kind of bug" since you are using `$query->id` at one place and `$query->andWhere` at the other place at least that should be consistent.

### Craft CMS version

5.4.x

### PHP version

8.3

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

You can test ahead of time by changing your `craftcms/cms` requirement in composer.json to:

```json
"craftcms/cms": "5.x-dev as 5.4.2",
```

**Comment by brandonkelly** [comment]
Craft 5.4.3 is out with that fix.
