### ISSUE TITLE
[5.x]: Layout shifts around/glitches when removing a selected asset from a field w/ Large Thumbnails or Cards view mode

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#15712]
### Description

If an asset field is using the "Large Thumbnails" or "Cards" view modes, a significant layout shift/glitch occurs whenever a selected asset is removed from the field:

https://github.com/user-attachments/assets/6e268cf7-5388-42f5-8ea9-d5ae292c466a

I'm able to reproduce this behavior in latest versions of Edge, Chrome, Safari and Firefox browsers on macOS 14.6.1. The glitch does not happen if the field is using the "List" view mode.

### Steps to reproduce

1. Create an assets field, with all default settings except "Large Thumbnails" or "Cards" for the View Mode
2. Add an asset to the field
3. Remove the asset

### Craft CMS version

5.4.2

### Operating system and version

macOS 14.6.1

### Installed plugins and versions

- None

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.4.3 is out with that fix. Thanks again!
