### ISSUE TITLE
[5.x]: Matrix Entries status - Live preview

### ISSUE THREAD

**Issue by rgauthier4c4** [craftcms/cms#15713]
### Description
When editing an entry and opening the live preview modal, it is not possible to change the status of a matrix block and see the changes in the preview.

### Steps to reproduce

1. Edit an entry with a matrix block
2. Open the live preview
3. The blocks are shown in the preview
4. Change the status of a single block to be disable
5. The block is still showing in the preview

### Expected behavior
The block should disappear from the page.

### Actual behavior
The block is still there.

### Craft CMS version

5.4.1

### PHP version

8.2

### Database type and version

mysql 8.0

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch! What view mode is this matrix field using?

**Comment by rgauthier4c4** [comment]
> Hi, thanks for getting in touch! What view mode is this matrix field using?

The field is in "as card" view mode

**Comment by i-just** [comment]
Thanks for confirming! 
I think I see what you mean. When you change the status, you don’t save the nested entry (block), right?

**Comment by rgauthier4c4** [comment]
Exactly, I've played around a little bit an I think I understand the problem now.

Every nested entries needs to be saved/published before his parent can display the change in the live preview.

Live preview is only useful if the entry contains basic fields to display the drafts changes.

**Comment by i-just** [comment]
We’ll discuss this internally.

**Comment by bliswebagency** [comment]
Would just like to add we noticed this while saving draft pages where their nested entries (within a content builder matrix) would be saved with a live status instead of draft. Changing out of card view does save the draft correctly but the card view would be ideal as it can offer a better editing experience in many cases.

Edit: just saw this was already covered under planned improvements on the Craft roadmap page

**Comment by brandonkelly** [comment]
Craft 5.5.0 is out which improves on the nested entry workflow quite a bit, including for Live Preview (#16002).
