### ISSUE TITLE
[5.x]: Link Field - Url goes outside of field boundaries in Slide out

### ISSUE THREAD

**Issue by DowleyDeveloped** [craftcms/cms#15722]
### Description

If you put a long url into the link field it goes outside of the field itself and you can't click to change any of the values.

<img width="352" alt="Screenshot 2024-09-11 at 21 05 00" src="https://github.com/user-attachments/assets/09d32069-9308-4942-9607-7b870d62144a">

### Steps to reproduce

1. Create a Link Field
2. Add a long URL within a Slide out entry Type.

### Expected behavior

The Field should either wrap, or truncate the value.

### Craft CMS version

5.4.2

### PHP version

8.3

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.4.4 is out with that fix. Thanks again!
