### ISSUE TITLE
[5.x]: Ability to Customize Site Order in Control Panel Language Dropdown

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#15725]
### Description

In Craft CMS 5, how can we modify the order of sites in the Control Panel?

I have configured several sites in the **All Sites** section. Initially, the first site was set as the **Primary** site, which was ideal because it appeared first in the language dropdown when editing content. However, after changing the **Primary** site, it now appears further down the list. 

If the sites were sorted alphabetically, this wouldn't be an issue. However, the sites appear to be sorted by their ID, which is not ideal from a display standpoint. 

Is there a way to modify the site order, or can this be considered as a potential feature request for more flexible site ordering?

### Steps to reproduce

1. Configure multiple sites in **All Sites**.
2. Change the **Primary** site to a different site.
3. Observe the site ordering in the language dropdown during content editing.

### Expected behavior

The **Primary** site or the sites should be displayed in a logical order, ideally alphabetical, or have a custom option to reorder them.

### Actual behavior

Sites are displayed in the order of their ID, which doesn't provide a user-friendly experience, especially when the **Primary** site is not listed first.

### Craft CMS version

5.4.3

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out! You can reorder sites within their groups by using the diamond icon. 
<img width="1214" alt="Screenshot 2024-09-13 at 11 28 43" src="https://github.com/user-attachments/assets/c2a9dec3-9d09-4a82-9c5b-2fd28dc05567">

The “All sites” page shows all the sites ordered by the group name (alphabetically) and then by the order of the sites within the group.
<img width="1229" alt="Screenshot 2024-09-13 at 11 29 07" src="https://github.com/user-attachments/assets/cb8f164d-1897-48ba-ab3c-714329636a64">

I hope this clarifies things!
