### ISSUE TITLE
[5.x]: Assets Field Type re-arranging asset lagging 5 to 10 seconds in Safari

### ISSUE THREAD

**Issue by zawilliams** [craftcms/cms#15728]
### Description

I'm seeing an issue with a client where when having a large amount of assets in an Asset field type (50 items definitely is laggy), the moving around of assets when trying to arrange order completely locks up the page - scrolling seems to work still, but interaction on the whole page freezes. Chrome seems to lag a tiny bit, but Safari is almost unusable.

Anyone encountering this? 

Just upgraded to Craft 5 recently and it seems to be since then that this is happening. Went to upgrade the last few minor updates today to see if it fixed things, but no dice.

Included a video to show:

https://github.com/user-attachments/assets/d3b096f2-33c1-4a89-8510-ca1b1a563bcd

### Steps to reproduce

1. Load up 50 assets in an asset field. Drag and drop using the "Reorder" 4 dot diamond.

### Expected behavior

Smooth dragging.

### Actual behavior

Browser locks up for 5 to 10 seconds.

### Craft CMS version

5.4.3

### PHP version

8.3

**Comment by zawilliams** [comment]
Thanks for looking into this @brianjhanson! Following along.

**Comment by brandonkelly** [comment]
We just released Craft 5.4.6 with some improvements to drag-n-drop responsiveness for Safari (#15788). There’s still some work to do, but it’s much more usable now.

**Comment by zawilliams** [comment]
Thanks for the fix @brandonkelly!
