### ISSUE TITLE
[5.x]: `Attempt to read property "type" on null` when editing Matrix entries on front-end

### ISSUE THREAD

**Issue by shifuma** [craftcms/cms#15737]
### Description
I'm trying to create a front-end entry edit form, but getting `Attempt to read property "type" on null`.

### Steps to reproduce

1. Use the [example entry form as a basis](https://www.craftcms.com/knowledge-base/entry-form) to create a form to edit a Matrix entry

```
{% set entry = craft.entries().id(1).one() %}

<form method="post" accept-charset="UTF-8">
  {{ csrfInput() }}
  {{ actionInput('entries/save-entry') }}

  {# {{ hiddenInput('sectionId', entry.sectionId) }} -- this is the problem as Matrix entries don't have a section #}
  {{ hiddenInput('typeId', entry.typeId) }}
  {{ hiddenInput('entryId', entry.id) }}
  {{ hiddenInput('enabled', true) }}

  <label for="title">Title</label>
  {{ input('text', 'title', entry.title, {id: 'title',}) }}
  {{ _self.errorList(entry.getErrors('title')) }}

  <button type="submit">Publish</button>
</form>
```

### Expected behavior
Able to save a Matrix entry like regular entries on the front-end.

### Actual behavior
Because Matrix entries don't have a section you get this error: `yii\base\ErrorException: Attempt to read property "type" on null in /var/www/html/packages/cms/src/controllers/EntriesController.php:252`

https://github.com/craftcms/cms/blob/5f69bc4f699e6f97a90c057584e720a808c80b98/src/controllers/EntriesController.php#L248-L254

---

I've tried adding:

```
{{ hiddenInput('fieldId', 1) }}
{{ hiddenInput('ownerId', entry.ownerId)}}
```

As per https://github.com/craftcms/cms/discussions/15345 but that doesn't help. Is there something else I need to add or is this a bug?

### Craft CMS version

5.4.3

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

To test the fix early, change your `craftcms/cms` requirement in composer.json to

```json
"craftcms/cms": "5.x-dev as 5.4.4",
```

**Comment by brandonkelly** [comment]
Craft 5.4.5 is out with that fix. Thanks again!
