### ISSUE TITLE
[5.x]: Link field values' widths seem unnecessarily constrained since updating to 5.4.4

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#15738]
### Description

Since updating to 5.4.4, link field values' widths seem unnecessarily constrained. I'm guessing this is a side effect of https://github.com/craftcms/cms/pull/15731, but if possible it'd be nice if field values used the available width – as the way the field renders even URLs of moderate lengths looks a bit awkward right now:

Now (5.4.4):

![CleanShot 2024-09-15 at 23 23 35@2x](https://github.com/user-attachments/assets/76fd71c7-6070-49c3-b0bb-8c28dbbaf25a)

Before (5.4.3):

![CleanShot 2024-09-15 at 23 22 37@2x](https://github.com/user-attachments/assets/96b72b9c-03f0-4dd6-89d1-b6ff34211937)

### Steps to reproduce

1.

### Craft CMS version

5.4.4

### Operating system and version

macOS 14.6.1 (MS Edge 128.0.2739.79)

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 5.4.5 is out with that fix. Thanks again!
