### ISSUE TITLE
[5.x]: Remove recommendation to explicitly override `@web` alias

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#15739]
### What happened?

The “Requirements” section under “System Report” still recommends explicitly overriding the `@web` alias, even though this is no longer officially recommended (#14440, #14612).

![screenshot-dmB5fFRP@2x](https://github.com/user-attachments/assets/9fd22148-f4fc-4c29-b369-8126bccc4769)

### Steps to reproduce

1. Don’t explicitly override the `@web` alias.
2. View the “Requirements” section under “System Report” .

### Expected behavior

It should _not_ recommend explicitly overriding the `@web` alias.

### Actual behavior

It recommends explicitly overriding the `@web` alias.

### Craft CMS version

5.4.4

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for the reminder! Just tagged craftcms/server-check 2.1.9 (Craft 4) and 5.0.2 (Craft 5) with that check removed.
