### ISSUE TITLE
[5.x]: Wrong entry types after upgrade from Craft CMS 4 to 5

### ISSUE THREAD

**Issue by urbantrout** [craftcms/cms#15740]
### What happened?

After upgrading to Craft CMS 5 some (not all) entries show the wrong entry type in the CP. 

Here is what the section looks like if I edit it:

<img width="253" alt="Editing section 'Homepage' with one entry type selected called 'Homepage'" src="https://github.com/user-attachments/assets/f950f339-024c-4f50-88bb-45da07f51acb">

And this is what I get when I edit the homepage entry:

<img width="443" alt="Sidebar of entry showing wrong entry type" src="https://github.com/user-attachments/assets/dc512f23-bc1e-4c30-bd88-351b8ef4f26e">

Here `Team - Standard` is selected~ and I cannot change it to `Homepage`.

When I try to save the entry with `Team - Standard` selected I get the following exception:

`Team - Standard entries are no longer allowed in this section. Please choose a different entry type.`

When I try to save the entry with `Homepage` selected I get the following exception:

`Invalid Argument – [yii\base\InvalidArgumentException](https://www.yiiframework.com/doc-2.0/yii-base-invalidargumentexception.html)
Entry Type is no longer allowed in this section.`

### Craft CMS version

5.4.4

### PHP version

8.2.5

### Operating system and version

Linux 6.10.4-linuxkit

### Database type and version

MariaDB 10.11.8

### Installed plugins and versions

- CP Field Inspect 	2.0.2
- Element API 	4.1.0
- Embedded Assets 	5.1.2
- Minify 	5.0.0
- Typogrify 	5.0.1
- Vite 	5.0.1

**Comment by brandonkelly** [comment]
Any chance you can send your Craft 4 database backup and current (Craft 5) Composer files over to support@craftcms.com?

**Comment by urbantrout** [comment]
Sure. I just sent the files.

**Comment by urbantrout** [comment]
I am so sorry! I custom module messed up the entry types after saving entries… So this is totally on me 😢

**Comment by brandonkelly** [comment]
Hah, no worries. Glad you got it sorted!
