### ISSUE TITLE
[5.x]: Unable to entrify global sets

### ISSUE THREAD

**Issue by wblommaert** [craftcms/cms#15746]
### Description

We recently upgraded a Craft 4 site to Craft 5 and are now applying some improvements, one of them being the entrification of all the global sets. Whenever we run the entrification commands however, the process stops when it tries to save the new section. This consistently happens to every global set and we've not been able to narrow down the problem since it seems to be occurring in entries service.

We're running Craft CMS 5.4.4 in DDEV with PHP 8.3 and MySQL 8.

### Steps to reproduce

1. Run `ddev craft entrify/global-set tickets`
2. Follow all the steps with their default values
3. The process errors

<img width="1089" alt="Screenshot 2024-09-17 at 09 52 29" src="https://github.com/user-attachments/assets/fb9f99bf-8a28-484c-9018-a5a56cebcab8">

### Expected behavior

Entry type and section are created, content is migrated.

### Actual behavior

Entry type is created, section creation fails, everything is rolled back.

### Craft CMS version

5.4.4

### PHP version

8.3

### Operating system and version

DDEV 1.23.4 on macOS Sonoma 14.6.1

### Database type and version

MySQL 8.0.36

### Image driver and version

Imagick 3.7.0

### Installed plugins and versions

- CKEditor	4.2.0
- Color Mixer	4.0.0
- Colour Swatches	5.0.2
- Control Panel CSS	3.0.0
- Cookies	5.0.0
- Device Detect	3.0.0
- Expanded Singles	3.0.0
- Field Manager	4.0.2
- FOMU Events	1.1.0
- Footnotes	5.0.0
- Freeform	5.5.10
- Hyper	2.0.5
- Imager X	5.0.2
- Mix	v1.7.1
- Navigation	3.0.4
- Neo	5.2.6
- Redactor	4.2.0
- SEOmatic	5.1.3
- Smith	3.1.0

**Comment by wblommaert** [comment]
Obviously after posting an issue here we discover half an hour later that during the Craft 5 upgrade several entry types were created, one of which has a conflicting handle with the default settings the entrification command suggests. Providing a non-existent handle leads to a succesful run of the entrification command. 

Perhaps it would be better though to provide more feedback when the entrification fails due to overlapping handle values? Right now it gives the impression that it successfully created the entry type and fails at the section creation, as seen in the screenshot I provided.

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.4.5 is out with that fix. Thanks again!
