### ISSUE TITLE
Provide User Groups Query Element

### ISSUE THREAD

**Issue by theskyfloor** [craftcms/cms#1574]
### Description

I have several needs for the ability to query all user groups and return an array in Twig. Why can't I do that? Seems silly to produce a plug-in for such a simple task. For now I am stuck assigning every group I create to one user just so I can return an array of all available groups but that is a backwards way to do something so simple.

### Additional info

- Craft version:  2.6.2968
- PHP version: 7.0.16
- Database driver & version: MySQL
- Plugins & versions:

**Comment by lindseydiloreto** [comment]
This function should be available directly in templates in Craft 3...

https://craftcms.com/classreference/services/UserGroupsService#allGroups-detail

In the meantime, you'd need a simple plugin to wrap that.

**Comment by brandonkelly** [comment]
Actually this is already possible in Craft 2:

```twig
{% set groups = craft.userGroups.getAllGroups() %}
```

That still works in Craft 3, but has been deprecated (and will be removed in v4). The new way is:

```twig
{% set groups = craft.app.userGroups.getAllGroups() %}
```

**Comment by theskyfloor** [comment]
Is it in the docs? If not I guess that would be the request
