### ISSUE TITLE
[5.x]: Alignement of dropdowns in table fields

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#15742]
### Description
Dropdowns in table fields are center aligned which looks a little off and awkward to read.

### Steps to reproduce

1. Include a dropdown in a table field with multiple columns

### Expected behavior

The dropdown should be left aligned:
<img width="693" alt="image" src="https://github.com/user-attachments/assets/6d4b62f9-a6cc-41eb-90d3-3a745f20f1e2">

### Actual behavior

The dropdown is centered:
<img width="687" alt="image" src="https://github.com/user-attachments/assets/583ca136-7f17-4057-91ad-e2e2b8a64632">

### Craft CMS version

5.4.4

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for the feedback! We’ve opted to left-align the dropdown menus starting in Craft 5.5.

**Comment by brandonkelly** [comment]
Craft 5.5.0 is out now with that change 🎉
