### ISSUE TITLE
[5.x]: Cannot delete and re-create homepage

### ISSUE THREAD

**Issue by harry2909** [craftcms/cms#15755]
### Description
After deleting the home single I had set as the homepage and trying to re-create, I get the message "Site already has a homepage."

### Steps to reproduce

1. Create single and assign as homepage
2. Delete single
3. Attempt to re-create single with same handle as homepage

I've even tried reverting and deleting via the command line.

I've also tried directly deleting the single in the DB.

### Expected behavior

I should be able to re-create the single.

### Actual behavior

I cannot re-create the single.

### Craft CMS version

5.4.4

### PHP version

8.3

### Database type and version

MYSQL 8

### Installed plugins and versions

-

**Comment by harry2909** [comment]
I've actually just fixed this by:

1. Creating the single without setting it to the homepage
2. Save single
3. Set single to homepage
4. Save

**Comment by brandonkelly** [comment]
Glad you got it sorted! I just tried this on my end and wasn’t able to reproduce.
