### ISSUE TITLE
[5.x]: Required property not set on custom field object

### ISSUE THREAD

**Issue by peteeveleigh** [craftcms/cms#15752]
### Description
When looping through custom fields I was trying to automatically set the required attribute based on {{ customField.required }}. It looks like this property has been moved into {{ customField.layoutElement.required }} but the original property still exists and is not being set - it's always false.

Custom field properties. The required property is false, despite the field being set to 'required'
![Screenshot 2024-09-18 at 09 45 59](https://github.com/user-attachments/assets/50eaafe0-4b97-4b97-90fe-99d365815c33)

Same field, layoutElement
![Screenshot 2024-09-18 at 10 05 14](https://github.com/user-attachments/assets/10477e4e-df18-49f0-b913-bd0ea5c32201)

While I understand that this property has been moved into layoutElement, if the original property remains then should it also honour the required setting of the field for consistency's sake. At least until fully deprecated (if that's the plan) .

### Steps to reproduce

1. Create a custom field and set it to be required
2. On the front-end loop through the custom fields and use the {{ customField.required }} property to set the required attribute on the field.

### Expected behavior
The field should received a required attribute

### Actual behavior
The {{ customField.required }} property is always false while the {{ customField.layoutElement.required }} property honours the setting in the CP.

### Craft CMS version

5.4.4

### PHP version

8.2.18

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting. I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 4.12.4 and 5.4.5 are out with that fix. Thanks again!
