### ISSUE TITLE
[5.x]: Dynamic slug for matrix owned entries get truncated

### ISSUE THREAD

**Issue by wuhhh** [craftcms/cms#15754]
### Description

I have a matrix entry URI in the format `{owner.uri}/{slug}`. When I quickly create entries via the matrix (in place), the slug is often truncated - this seems to be because the slug has not finished generating based on the title value before I save the entry.

### Steps to reproduce

1. Create a matrix field that has a dynamic slug such as {owner.uri}/{slug}
2. Quickly create entries in place

### Expected behavior

Should not be allowed to save an entry before its slug has generated

https://github.com/user-attachments/assets/f8c8b3d6-81f6-43e4-a218-98694079ffa4

### Craft CMS version

5.4.4

### PHP version

8.2.18

### Operating system and version

Linux 6.10.7-orbstack-00280-gd3b7ec68d3d4

### Database type and version

MySQL 8

**Comment by brandonkelly** [comment]
Thanks for reporting that! I just removed the delay on auto slug generation (as well as for other auto-generated inputs) for the next Craft 4 and 5 releases, so this shouldn’t be a problem any more going forward.

**Comment by brandonkelly** [comment]
Craft 4.12.4 and 5.4.5 are out with that fix. Thanks again!
