### ISSUE TITLE
[5.x]: hasAlt sticks on "true" even when an asset removes its alt text

### ISSUE THREAD

**Issue by andrewfairlie** [craftcms/cms#15762]
### Description
When you upload an image to Assets, it is `hasAlt` as `false` by default. When you add text, it goes to `true`, but removing the text doesn't go back to `false`

### Steps to reproduce

1. Upload an empty image
2. Observe value of `hasAlt`
3. Add some text to alt
4. Observe value of `hasAlt`
5. Remove all of the text
6. Observe value of `hasAlt`

### Expected behavior
1. Upload an empty image
2. Observe that `hasAlt` is false
3. Add some text to alt
4. Observe that `hasAlt `is true
5. Remove all of the text
6. Observe `hasAlt` is **false**

### Actual behavior
1. Upload an empty image
2. Observe that `hasAlt` is false
3. Add some text to alt
4. Observe that `hasAlt `is true
5. Remove all of the text
6. Observe `hasAlt` is still true

### Craft CMS version

 5.4.4

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.4.5 is out with that fix. Thanks again!
