### ISSUE TITLE
[5.x]: Fields with duplicate labels no selectable for entry conditions

### ISSUE THREAD

**Issue by Dollhopf** [craftcms/cms#15764]
### Description
When 2 (or more) fields have the same label (but different handle), only the first one can selected under `Settings`>`Entry Condition`>`Add a rule`. If a condition is selected with different labels and afterwards renamed to a duplicate label, the dropdown shows both correctly (see **Expected behavior**). Switching or deleting the condition results in the initial state with only one field showing (see **Actual behavior**).

### Steps to reproduce

1. Create a field layout with two fields of the same type and lable but different handle.
2. Save entry to make the fields available vor `Entry Conditions`.
3. Add a third field.
4. Go to `Settings`>`Entry Condition`>`Add a rule`.

### Expected behavior
Both fields should show independently, even if they have the same label.

Currently this is only true if the condition was set before renaming the field with the condition on it:
![image](https://github.com/user-attachments/assets/1a1f49f7-422a-437e-82b1-d75f9ac690be)

### Actual behavior
The second field with the same label is missing in the selection dropdown.
![image](https://github.com/user-attachments/assets/727f9873-8180-40d5-80d9-6d64f9a5aec6)

### Craft CMS version

5.4.4

### PHP version

8.3

### Operating system and version

Windows 11, Firefox 130.0

### Installed plugins and versions

None

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.4.5 is out with that fix. Thanks again!
