### ISSUE TITLE
[5.x]: Element Index view on Matrix field shows some relations twice

### ISSUE THREAD

**Issue by tommysvr** [craftcms/cms#15777]
### Description
When using Element Index view on a Matrix field, relations are shown in the original field and the multi-instance field.

### Steps to reproduce

1. Create a Matrix Field
2. Create an Entry Type and add the same entries field twice
3. Set Matrix field View Mode to 'As an element index', 'Include Table View' enabled and add entries fields to Default Table Columns
4. Create an Entry & Nested Entry inside the Matrix field, add one relation to each entries field
5. Element Index view will show the relation from the second entries field on the first entries field

### Expected behavior
Each entries field will show only one relation in this case

### Actual behavior
The first entries field shows its relation and the relation of the second entries field

Screenshots hopefully explain a little bit better

Matrix Field settings:
![screenshot_2024_09_23 _12 00](https://github.com/user-attachments/assets/2fc24a6b-b62a-4d00-be11-4f4814f6348b)

---

Entry Type:
![screenshot_2024_09_23 _12 00](https://github.com/user-attachments/assets/5ddf7a2c-d80b-4296-a6be-bd360eaaa92e)

---

Nested Entry:
![screenshot_2024_09_23 _12 00](https://github.com/user-attachments/assets/b22876f5-9fa9-4c0b-a114-3b532c9cc877)

---

Columns showing duplicate relation:
![screenshot_2024_09_23 _11 59](https://github.com/user-attachments/assets/67fd78a8-2ddb-4011-a649-b85813fd0df9)

### Craft CMS version

5.4.4

### PHP version

8.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Not able to reproduce this on my end. Was this on a fresh install?

**Comment by brandonkelly** [comment]
Fixed in 5.4.5!
