### ISSUE TITLE
[5.x]: Calling unknown method: craft\web\Application::sections()

### ISSUE THREAD

**Issue by paulwaddington** [craftcms/cms#15778]
### What happened?

Just running the example from the docs throws the error 'Calling unknown method: craft\web\Application::sections()'

{# get all the sections for the current site #}
{% set sections = craft.app.sections.getAllSections() %}

https://craftcms.com/docs/5.x/reference/twig/global-variables.html#craft-app

### Craft CMS version

5.4.4

### PHP version

8.3.10

### Operating system and version

Linux 6.10.4-linuxkit

### Database type and version

MySQL 8.0.36

### Image driver and version

GD 8.3.10

### Installed plugins and versions

Amazon S3 - 2.2.1
CKEditor - 4.2.0
Cloudflare - 3.0.1
Expanded Singles - 3.0.0
Freeform - 5.6.2
Mailgun - 3.1.0
Maps - 5.0.3
Minify - 5.0.0
Super Table - 4.0.2
Width Fieldtype - 5.0.0

**Comment by i-just** [comment]
Hi, thanks for pointing that out! We’ll update the docs. 
To get all the sections in Craft 5, please use `{% set sections = craft.app.entries.getAllSections() %}`

**Comment by AugustMiller** [comment]
Fixed—thanks for reporting!
