### ISSUE TITLE
[5.x]: Mutation that only inserts into a site other than the primary site gets forbidden when schema is restricted only to this site

### ISSUE THREAD

**Issue by ahoikapptn-dev** [craftcms/cms#15779]
### Description

A mutation on a site other than the primary site gets 403 forbidden, because it does not have access to the primary site (which it doesn't need)

### Steps to reproduce

1. Create a write (mutation) schema for a site other than the primary site only
2. Query with that schema

### Expected behavior
Mutation gets executed

### Actual behavior
403 because no access to to primary site

### Craft CMS version

latest

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. I created two sites, and a section that is enabled for the second site. Then I created a GraphQL schema that can only query from the second site, and enabled mutation queries for the section.

![Screenshot of a GraphQL request to create an entry is the section](https://github.com/user-attachments/assets/f23673a2-aab2-48e1-a54b-f4f53072442d)

Is there something I’m missing?

**Comment by ahoikapptn-dev** [comment]
Hi @brandonkelly - what did you tick in the Schema? Just "Edit entries in the "Test Locations" section, right?

Ok, here are all other details on the setup, not sure if it makes a difference for reproducing.
The second site is in another group than the primary site. Additionally we have a token auth, not sure if you used that in your replication. We have not ticked any "Query" in the schema for any Site. Lastly, the "Test Locations" are only available on the second site as well and not on the primary site.

Here is our schema:
![image](https://github.com/user-attachments/assets/34969b8e-248f-49be-bf04-83383c9fca65)

**Comment by brandonkelly** [comment]
> We have not ticked any "Query" in the schema for any Site.

Alright, that’s your problem. Those schema components actually affect mutations as well. I guess we should consider renaming them to be more clear.
