### ISSUE TITLE
[5.x]: Links in error summaries no longer work with Matrix fields

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#15797]
### Description

When saving an entry causes validation errors, the error messages in the summary above the form are anchor links that should scroll to the field in question:

![Screenshot 2024-09-26 at 16 35 19](https://github.com/user-attachments/assets/c0374546-43b7-4d4b-94ca-17cc99aa0ce7)

I found that this no longer words if the error is inside a Matrix field. I've only checked Matrix fields that are set to display as inline blocks. Might also be an issue if the field is set to card or element index view.

### Steps to reproduce

1. Create a Matrix field set to inline view and select an entry type with a required field.
2. On a new entry, create an entry in the Matrix field and leave the required field empty.
3. Save the entry.
4. Click on the link in the error summary about the empty required field.

### Expected behavior

The links should always scroll to the field in question, even inside an inline matrix block.

### Actual behavior

Clicking on the links doesn't do anything.

### Craft CMS version

5.4.5.1

### PHP version

8.3

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi @MoritzLost, thanks for reporting! 

I have tested this against a matrix field in an inline-editable blocks view mode, and it works as expected for the first-level matrix fields. However, it gets confused if the nesting gets deeper. I’ll have a look into that!

**Comment by MoritzLost** [comment]
@i-just You're right, the errors occured in nested Matrix fields one level deep. Forgot to mention that, sorry!

**Comment by i-just** [comment]
Thanks for confirming!

**Comment by i-just** [comment]
I have raised a PR for this. Thanks again for reporting!

**Comment by brandonkelly** [comment]
Craft 5.4.8 is out with that fix. Thanks again!
