### ISSUE TITLE
[5.x]: "Invalid draft ID" exception when editing entries in slideouts, if the slideout entry does not exist in the currently requested site

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#15798]
### Description

Certain actions in entry slideouts will fail with a BadRequestHttpException "Invalid draft ID", _if the entry being edited in the slideout does not exist for the currently requested site_. Stack trace here: https://pastebin.com/6jndVcMx

For one, attempting to **discard unsaved changes** from the slideout will fail w/ the above error. I suspect this might be because there is no site ID passed to the `delete-draft` action; likely making Craft fall back to the currently requested site (`'norwegian'`, in this case), in which the slideout entry doesn't exist?

![CleanShot 2024-09-26 at 16 31 25@2x](https://github.com/user-attachments/assets/c7394704-c3bd-416c-857a-2abede33ca16)

Similarly, **attempting to add a nested entry** in a CK Editor field on the slideout entry will also fail with the same exception, causing a blank slideout for the attempted new nested entry. Again, the request (this time to `elements/edit`) is missing a site ID param:

![CleanShot 2024-09-26 at 16 29 28@2x](https://github.com/user-attachments/assets/9b4e858b-a649-459d-9b95-e406eef814a5)

https://github.com/user-attachments/assets/65e9e894-807a-4606-b6ef-b3ef430a9b16

_^ Attempting to add a nested entry in a CK Editor field for an entry that doesn't exist in the currently requested site_

**Saving changes** in the slideout does work (both in terms of auto-saving the provisional draft and actually clicking "Save" in the slideout); presumably because these requests include the slideout entry's site ID as a param:

![CleanShot 2024-09-26 at 16 31 55@2x](https://github.com/user-attachments/assets/b51d1992-1e5e-439a-9867-b96e11fbdca5)

### Steps to reproduce

1. Create two sites, "Site A" and "Site B"
2. Create two sections, "Section A" and "Section B". _Make sure that "Section B" is only enabled for "Site B"._
3. Create an entry in Section B (Site B).
4. Create an Entries field, and select "Section B" as the only source. _Enable the "Show the site menu" setting._
5. Add the Entries field to Section A.
6. Create an entry in Section A, Site A. Add the entry from Section B (Site B) to the field.
7. Double-click the selected Site B entry in the entries field to have it open in a slideout. Make some changes. After the auto-draft completes saving, click the "Discard changes" button in the slideout.

### Expected behavior

Editing entries in relational fields' slideouts should work, even if the entry doesn't exist for the currently requested site.

### Actual behavior

Saving content changes via slideouts for entries that doesn't exist in the currently requested site works, but other actions such as adding nested entries or discarding changes doesn't.

### Craft CMS version

5.4.5.1 (Solo)

### Installed plugins and versions

- None, although I tested editing nested entries using CK Editor

**Comment by brandonkelly** [comment]
Thanks for reporting that! The “Discard changes” bug is fixed now in Craft 4.12.5 and 5.4.6. We’ll look into the CKEditor bug separately.

**Comment by brandonkelly** [comment]
CKEditor 4.3.0 is out now with the other fix for this.
