### ISSUE TITLE
[5.x]: Error when defining validation rules for an entry

### ISSUE THREAD

**Issue by rob-c-baker** [craftcms/cms#15792]
### Description

While trying to migrate (v4 -> v5) some entry validation rules with this custom module code:

```php
Event::on(
    Entry::class,
    Entry::EVENT_DEFINE_RULES,
    function (DefineRulesEvent $event) {
        /** @var Entry $entry */
        $entry = $event->sender;
        if (ElementHelper::isDraftOrRevision($entry)) {
            return;
        }
        if ($entry->getSection() === null) { // What was a matrix block - probably
            if ($entry->getType()->handle === '[specificTypeHandle]') {
                $event->rules[] = [ ... ];
            }
        }
    }
);
```

I get an error in the CMS when adding a new entry to a Matrix inside a Matrix:

![image](https://github.com/user-attachments/assets/a9d7bca4-ca88-4f4a-99b7-04793d336a28)

_(Call to a member function getEntryTypes() on null)_

Looking at the trace in the JSON response, it happened in `vendor/craftcms/cms/src/elements/Entry.php`, line 1378 and was a few steps in as a result of the call in the above code: `$entry->getType()->handle`.

Looking at the `$entry`, all the fields are empty. Makes sense as it's so new it hasn't even been displayed yet.

Looking [here](https://craftcms.com/docs/5.x/extend/events.html#event-code-generator) it looks like the code should be OK.

However, perhaps there is different set of conditions I should be checking before applying validation rules?

Or maybe I am not correctly detecting that the Entry arriving in this event is part of a Matrix field (inside a Matrix field)? However, I have been unable to work out the _correct_ way to do that.

### Steps to reproduce

1. Matrix field on a section
2. Another matrix field inside that
3. Add the above event code to a custom module
4. Try to add an entry in the CMS to the inner most Matrix field (see screen shot)

### Expected behavior

No error when calling `$entry->getType()` in the event.

### Craft CMS version

5.4.4

**Comment by i-just** [comment]
Hi, thanks for getting in touch! Sounds like this issue should explain what’s happening and how you can proceed: https://github.com/craftcms/cms/issues/15509. 

I’ll close this now, but feel free to get in touch again if you have any further questions.

**Comment by rob-c-baker** [comment]
Ah, that referenced issue makes sense. I'll pick though that - I'm sure there is a combination in there that will work.

The other thing, which is slightly off topic (referred to above): Is there a correct way to determine if any particular entry belongs to a Matrix field?

**Comment by i-just** [comment]
Entries that are nested in a field have the `fieldId` parameter populated. If you need to know if it’s specifically a matrix field, you could check that field’s type.
