### ISSUE TITLE
[>5.4]: Uploading assets in front-end form replaces existing assets

### ISSUE THREAD

**Issue by tommysvr** [craftcms/cms#15809]
### Description
Since 5.4.0, a saving an entry in a front-end form replaces existing assets. Verified this was working as expected in 5.3.6

### Steps to reproduce

Upload a new asset to an entry with existing assets from a front-end form:

```
<form method="post" accept-charset="UTF-8" enctype="multipart/form-data">
  {{ csrfInput() }}
  {{ actionInput('entries/save-entry') }}
  {{ hiddenInput('entryId', entry.id) }}

  <label for="title">Title</label>
  {{ input('text', 'title', entry.title, {id: 'title',}) }}

  {% for relatedAssetId in entry.assets.ids() %}
    {{ input('text','fields[assets][]',relatedAssetId) }}
  {% endfor %}

  {{ input('file', 'fields[assets][]', options={multiple: true}) }}

  <button type="submit">Publish</button>
</form>
```

### Expected behavior
New asset will be added to existing assets

### Actual behavior
All existing assets are removed and only the new asset is saved to the entry

### Craft CMS version

>5.4.0

### PHP version

8.2

### Installed plugins and versions

-

**Comment by Anubarak** [comment]
Did you try version 5.4.3?
https://github.com/craftcms/cms/issues/15707

**Comment by tommysvr** [comment]
> Did you try version 5.4.3? #15707

Yep still happening on 5.4.6 (latest) and report in support from 5.4.4.

**Comment by i-just** [comment]
Thanks for the clear replication steps, Tommy! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.4.7 is out with that additional fix.
