### ISSUE TITLE
[4.x]: Wrong timezone displayed for Date field in CP

### ISSUE THREAD

**Issue by stolat** [craftcms/cms#15805]
### Description
Timezone for EST dates is being displayed as EDT

### Steps to reproduce

1.  Create an entry with a Date field with enable Show Time Zone on
2. Set date to 12/1/24, select New York for time zone

### Expected behavior
Timezone should be EST

### Actual behavior
Timezone is EDT - there is no issue in front-end templates, but content managers are confused and complaining

### Craft CMS version

4.12.4.1

### PHP version

8.1.2.7

### Operating system and version

Ubuntu 22.04.4

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
New York is currently on the EDT time zone (D = Daylight).

**Comment by stolat** [comment]
Understood, but select a date that should be EST and it still shows at D

![2024-09-27_11-18-20](https://github.com/user-attachments/assets/04227f57-eba7-4bbf-82e3-bfa9afec37bc)

**Comment by brandonkelly** [comment]
Right, ok. Just fixed this for the next Craft 4 and 5 releases. Note that the time zone labels won’t refresh automatically – so they may be mislabeled right when you select a date that is on a different time zone. But the labels will correct themselves the next time the form is loaded.

**Comment by brandonkelly** [comment]
Craft 4.12.6 and 5.4.7 are out with that fix. Thanks for reporting!
