### ISSUE TITLE
[5.x]: Tag field not working when label is hidden

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#15800]
### Description

When the label is hidden for a tag field, the field doesn't work.

### Steps to reproduce

1. Add a tag field to a field layout.
2. Hide the label.
3. Try to add a tag.

### Expected behavior

Existing matching tags are displayed on input, and a new tag can be added.

### Actual behavior

The "spinner" is displayed momentarily, but no results are displayed for existing tags and no new tags can be added.

### Craft CMS version

5.4.5.1

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.4.6 is out with that fix. Thanks again!
