### ISSUE TITLE
Silent non-running of plugins in console

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1580]
### Description
This is a config issue underneath, but the problem is that it is wholly invisible,
Solution would be for console to report as web app does, when it can't open the database, 
Potentially that would be  important also for other showstoppers, for example, that would cause ApplicationTrait::getIsInstalled() to return false. Or any other reason for silent running....

### Steps to reproduce

1. Don't have a default  db config; just web url ones
2. Try to run a console command in a plugin
3. Things run, but the plugin console controller silently (never) runs.

### Additional info

PHP version	7.1.2-4+deb.sury.org~xenial+1
Database driver & version	MySQL 5.7.17-0ubuntu0.16.04.1
Image driver & version	GD 7.1.2-4+deb.sury.org~xenial+1
Craft edition & version	Craft Personal 3.0.0-beta.9
Yii version	2.0.11.2
Twig version	2.1.0
Guzzle version	6.2.1
Imagine version	0.7-dev
Plugins

Trimmer	1.0.0
Bactrian	1.0.0
Standards Agent	2.0.4

**Comment by brandonkelly** [comment]
This is only an issue if Craft isn’t even installed yet?

**Comment by narration-sd** [comment]
No, it's an issue when Craft *is* installed, but there is no or incorrect database config.

Instead of a warning, you just get a silent no-run.

**Comment by brandonkelly** [comment]
Just tested this locally, and getting this message in response:

> Unknown command: docs-helper/element-queries

This is Yii territory so not much we can do (without overriding a bunch of stuff we’d rather not do).

Web requests still give a more complete explanation of what’s going on:

> <img src='https://shipusercontent.com/5047ca14a4d2420a8b32cbf03effb62a/Screen%20Shot%202017-04-05%20at%2010.37.32%20AM.png' title='Screen Shot 2017-04-05 at 10.37.32 AM.png' width=342>

**Comment by narration-sd** [comment]
Hmm -- yes, I get an Unknown command message also -- not sure how it seemed nothing before.

However, here's what tests out as  an easy way to do this without any Yii-level involvement, as in enclosing fragment below.. I changed the craft/craft.php console  laucher to have a quick check inserted, 

I hope with some of the inimitable Craft 'you forgot' initialization message style :)

```
// Craft
            // for converted rather fresh site
define('CRAFT_BASE_PATH', $root . "/craft");
$app = require $root.'/vendor/craftcms/cms/bootstrap/console.php';

if(!$app->db->isActive) {
    echo  'error:  Can\'t connect to the Craft database with current configuration' . "\n"
      . '          -- please fix this.' . "\n";
    exit(-1);
}

$exitCode = $app->run();
exit($exitCode);
```
Imagining this would fit also with Craft 2.

**Comment by brandonkelly** [comment]
Thanks for the suggestion. Ended up doing something similar in Craft’s `bootstrap/console.php`. This is what you’ll get, going forward:

> <img width="892" alt="screen shot 2017-04-05 at 2 20 03 pm" src="https://cloud.githubusercontent.com/assets/47792/24727503/1811cbb6-1a0b-11e7-82ac-2f3aad219c5c.png">

**Comment by narration-sd** [comment]
Even better  -- cheers! 👍 

...if not so sly, but I think @takobell is the one we look to for that 🥇...
