### ISSUE TITLE
[5.x]: Full name field required fails validation

### ISSUE THREAD

**Issue by alanski66** [craftcms/cms#15808]
### What happened?

Steps
1. create user profile fields. 
2. make full name a required field
3. Leave full name blank and Save 
No validation takes place and filed is saved empty

### Craft CMS version

5

### PHP version

8

### Operating system and version

OSX

### Database type and version

mysl8

### Image driver and version

GD

### Installed plugins and versions

-Feed me

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.4.7 is out with that fix. Thanks again!
