### ISSUE TITLE
[4.x]: PLugin licenses for my own plugins

### ISSUE THREAD

**Issue by pnpaes** [craftcms/cms#15816]
### What happened?

Hi, I have a plugin published on craftcms plugin store.
This is a paid plugin and I also use the plugin on my websites.
Is it possible for me to install my own plugin without purchasing it?
If I added the repo as a vcs type it requires authentication when I use the craft update command even though it is loading from the public git repository.

### Craft CMS version

4.X

### Installed plugins and versions

-

**Comment by white-lukas** [comment]
You can create licenses for your own plugins with the API https://docs.craftcms.com/craftnet/plugin-licenses.html#create-a-plugin-license

**Comment by brandonkelly** [comment]
You can also use the [Plugin Key Generator](https://plugins.craftcms.com/plugin-key-generator?craft4) plugin.

**Comment by pnpaes** [comment]
Thank you @white-lukas, that worked like a charm.
@brandonkelly just a heads up, i have the latest craft5 installed (5.4.8) and got an error when installing the plugin that you suggested:

`*** installing plugin-key-generator`
`*** failed to install plugin-key-generator: Undefined constant craft\services\Utilities::EVENT_REGISTER_UTILITY_TYPES`

**Comment by brandonkelly** [comment]
@pnpaes Weird, just tested on my end and didn’t get that error. And that constant has existed since Craft 3.0.0.
