### ISSUE TITLE
[5.x]: Sorting entries by a number field

### ISSUE THREAD

**Issue by rellafella** [craftcms/cms#15828]
### Description
When sorting entries by a text field the sort ascending/descending works pretty well. However, when set to a number field it falls apart.

### Steps to reproduce

1. Create a custom number field
2. Create a channel and add the new number field to an entry type.
3. Add some numerical values to your entries
4. Sort the entry view by the number field

### Expected behavior
Entries would be sorted in numerical order

### Actual behavior
Entries are sorted based on the value of the first number only
![CleanShot 2024-10-02 at 5  12 32](https://github.com/user-attachments/assets/10162c05-dcff-4705-9a34-458589d2ecd5)

### Craft CMS version

5.4.4

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch! What database type and version are you using?

**Comment by rellafella** [comment]
This is a Postgres project using 16.3

**Comment by i-just** [comment]
Thanks! I raised a PR for it.

**Comment by brandonkelly** [comment]
Craft 5.4.7 is out with that fix. Thanks again!

**Comment by rellafella** [comment]
@brandonkelly It looks like this may have regressed

**Comment by i-just** [comment]
Thanks @rellafella! New PR raised.

**Comment by brandonkelly** [comment]
Craft 5.6.6 is out with that fix. Thanks again!

**Comment by rellafella** [comment]
Thanks team
