### ISSUE TITLE
[5.x]: Craft's .htaccess rewrite rule has conflicts with Apache 2.4

### ISSUE THREAD

**Issue by hiasl** [craftcms/cms#15825]
### Description
I used the Embedded Assets plugin in Craft 5 on Apache 2.4. The Assets > "Embed" button should normally show a preview after pasting e.g. a YouTube URL, but it fails. The reason is that newer versions of Apache give you a 403 (Forbidden) if the query string of a GET request contains a `%3f` (encoded `?`). A YouTube URL like https://www.youtube.com/watch?v=Cq1ZSWAVpnU fails because it get's encoded and passend on to the preview action URL via GET.

The problem is this rewrite rule in Craft's .htaccess:
`RewriteRule (.+) index.php?p=$1 [QSA,L]`

I could get it working by changing the rule to
`RewriteRule (.+) index.php [QSA,L]`
which seems to be fine for Craft, but there must be reasons why Craft is shipped with the initial rule.

I am reporting this here, because it is actually an issue which could happen to any GET request containing a `%3f` in the query string which gets rewritten to Craft's index.php via .htaccess, not only in Embedded Assets.

Here's my ticket to Spicyweb: https://github.com/spicywebau/craft-embedded-assets/issues/274

I am not asking for a solution, I only want to bring it to your attention.

### Craft CMS version

5.4.6

### PHP version

8.2

### Installed plugins and versions

- Embedded Assets 5.1.2

**Comment by brandonkelly** [comment]
Thanks for pointing that out. Tested locally and verified the `?p=$1` isn’t needed anymore, nor is `QSA`.

I’ve just tagged new versions of [craftcms/craft](https://github.com/craftcms/craft) with those removed (https://github.com/craftcms/craft/commit/d9d7f51f5c00fa6e9e9a4f9ffc197a2f8737e7ae). That will only affect new projects though, so anyone else who runs into this will need to remove those from `web/.htaccess` themselves.
