### ISSUE TITLE
[5.x]: Translatable Link Field retains same entry across sites

### ISSUE THREAD

**Issue by liencard** [craftcms/cms#15821]
### Description

When using a translatable Link field in a multisite setup, I expect that when I select an entry of the current site, it should default to the corresponding entry in the other sites (languages).

Currently, when I select an entry for a particular site, the same entry is retained across the other sites. This results in linking to the incorrect entry on those other sites.

### Steps to reproduce

1. Create a multisite setup.
2. Add a translatable Link field to an entry.
3. Select an entry in one site.
4. Observe that the same entry is applied across all sites instead of selecting the corresponding entry for the other site.

### Expected behavior

When selecting an entry in one site, the Link field should automatically map to the corresponding entry in the other site.

I understand that the Link field should be editable per site, but by default, I would prefer it to automatically select the corresponding entry for each site.

### Actual behavior

The selected entry is retained for all sites, leading to incorrect linked entries across the multisite setup.

### Craft CMS version

5.4

### PHP version

8.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for the suggestion. It’s working as expected currently – when creating a new entry, its translatable field values will automatically be copied over to other sites, just to provide a default value to the author, with the expectation that the author will probably end up modifying it on other sites later on.

That said, I can see how swapping out the selected entry with a localized version during that propagation would be more helpful, so it’s pointing to the same site that the author would have ended up getting if they had selected the same entry manually. So I’ve made that change for the 5.5 release (c3efaecd7f926b0860a32b0a93f6d298f2a249f7).

**Comment by brandonkelly** [comment]
Craft 5.5.0 is out now with that change 🎉
