### ISSUE TITLE
[5.x]: Merging fields

### ISSUE THREAD

**Issue by LukeAndrewColeman** [craftcms/cms#15823]
### Description

Trying to manually merge fields, tried to merge two fields together (one was a matrix field), merge found a different field with the same name and merged (not the matrix field), ran the merge script again and the matrix field could not be found.

### Steps to reproduce

1. Merge to fields together

### Expected behavior

Merge the two fields together.

### Actual behavior

Merged the wrong fields.

### Craft CMS version

Craft Pro 5.4.6

### PHP version

8.2.15

### Operating system and version

Mac OS 15.0 (24A335)

### Database type and version

MySQL 8.0.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch! Could you please provide more info on this? You used the `craft fields/merge` command? What types of fields were you merging (you said one was a matrix, but what was the second one)? Did you get any errors while running the merge command?

**Comment by LukeAndrewColeman** [comment]
Hey, 

I don't remember what both fields were unfortunately, but first i ran the entry type merge command on two entry types, i then realised that the entry type fields could be merged together because they were the same, so i ran the field merge command on the fields, let's say they were both plain text fields, this then merged the two fields and the command was successful, no errors. One of the fields used to be a matrix field i believe.

I then checked the cms which didn't reflect this change, our senior developer took a look and he seems to think that a field got merged with the same name but a different id to the one i wanted to megre, so then i re ran the merge but no field could be found to merge.

Hope this helps.

**Comment by i-just** [comment]
Do you still have a database backup from before those merges? If so, would you be able to restore it, go through the same process you described above, and share the details?

**Comment by LukeAndrewColeman** [comment]
Hey, I'm sorry I don't. Basically, i did an entry type merge then after i tried to merge 2 fields from those 2 entries and it said they were merged but in the cms this wasn't reflected. I don't really have much more info than what I have already said but I hope this helps.

**Comment by brandonkelly** [comment]
Matrix fields only support merging into other Matrix fields, and only if the persisting Matrix field has all of the same entry types as the outgoing field.

Unfortunately without specific steps to reproduce, there’s not much for us to go on here.

Most web hosts will create backups, so you can try contacting your host to see if they have one. Alternatively, if the merge was tracked in Git, you can revert your `config/project/` changes from the merge, and then run `php craft project-config/apply`. The original field(s) should return to normal after that.
