### ISSUE TITLE
Dates are saving on entries incorrectly

### ISSUE THREAD

**Issue by jolora** [craftcms/cms#1583]
### Description

Setting a date on an entry is not working as expected. My timezone is set as UTC+1(London). If I attempt to set a date on entry of 06/03/2017 (I will click on the 6th March from the calendar UI to do this) and then save the entry, the date is then transformed to US format of 03/06/2017 (3rd June).

This means that each time I save an entry the data gets flipped between 03/06/2017 and 06/03/2017. This is has the added consequence of potentially disabling certain entries from being live as they are given a future date.

The date is set correctly when creating a new entry.

### Additional info

PHP version	7.1.2-3+deb.sury.org xenial+1
Database driver & version	MySQL 5.7.17-0ubuntu0.16.04.1
Image driver & version	GD 7.1.2-3+deb.sury.org~xenial+1
Craft edition & version	Craft Client 3.0.0-beta.9
Yii version	2.0.11.2
Twig version	2.1.0
Guzzle version	6.2.1
Imagine version	0.7-dev

Server passes all requirement checks
No plugins installed

**Comment by brandonkelly** [comment]
Hey @jolora, just tested and unfortunately am not able to reproduce this.

Can you create a template with this code and tell me what it outputs:

```twig
{{ craft.app.language }}
```

**Comment by jolora** [comment]
The language was set to en-GB.

The error was my fault. I was testing on two separate machines and the one I noticed the error on did not have the Intl extension installed. Installing that resolved the issue.

Sorry for wasting your time.
