### ISSUE TITLE
[5.x]: It's possible all urls which craft generate should be url encoded.

### ISSUE THREAD

**Issue by joepagan** [craftcms/cms#15838]
### Description

I created [an issue originally](https://github.com/nystudio107/craft-seomatic/issues/1519) about this on the SEOmatic plugin repo who suggested this maybe should be resolved upstream.

In short, I believe I've found evidence that Craft should be encoding every url for publicly available elements.
Especially where non-ascii characters are used this can cause problems.

This isn't obviously a problem for browser users as browsers do a good job of showing a decoded version in the address bar but actually making a request to the encoded version of a url.
But for crawlers, bots, services and tools it will be a bigger deal.

Slightly longer version:

The main issue presented in my SEOmatic issue I was highlighting is that the plugin likely calls a craft `url` function, which is used to generate the canonical link element and a canonical header.
However, nginx does not support non-ascii characters in response headers, so we actually get a different URL, which results in a 404 if you were to visit it.

As an example where an element on an entry with SEOmatic enable which has a url: `/genêve`
- the link element - uses `/genêve` - which does not match t
- the link response header - uses `/genÃªve` which 404s
- the page itself - available on `/gen%C3%AAve`

I think this probably been fine for the most part for the longest as most crawlers likely detect non-ascii chars and parse them themselves. Though this was highlighted to me originally where some third-party SEO crawler tool noticed the SEOmatic response header did not match the canonical link element value, as it thought it was going to a different destination... it was! Because the nginx header was invalid.

Though the referenced specs in my other issue which most systems use as a guide, does seem to suggest that all URLs should be encoded so other systems can pick them up.
I think this goes for the link element, response headers, but potentially any `a` element's href value too given that a non-browser system which (e.g. a crawler) could pick that up.

There is lots more data to digest in the linked issue above for your reading leisure!

#### relevant links:

- https://developers.google.com/search/docs/crawling-indexing/url-structure
- https://www.rfc-editor.org/rfc/rfc3986#section-2
- https://stackoverflow.com/questions/4400678/what-character-encoding-should-i-use-for-a-http-header
- https://developers.google.com/maps/url-encoding#:~:text=It%20is%20recommended%20you%20use,properly%20escaped%20for%20your%20platform
- https://www.rfc-editor.org/rfc/rfc7230#section-3.2.4

### Steps to reproduce

1. install/enable seomatic
2. create an entry with a non-ascii character in it's slug
3. checkout the canonical element/response header

### Expected behavior

Use a non-ascii character in an element's slug, where craft will return an encoded url where the url function is used. e.g. in the examples above, SEOmatic canonical link elements, response headers, a element href values etc

### Actual behavior

A mixture of results which can result in invalid response headers, and non-matching references to a single element's public URL.

### Craft CMS version

5.3.6

### PHP version

8.3

### Installed plugins and versions

- seomatic 5.1.2

**Comment by khalwat** [comment]
Related: 

https://github.com/nystudio107/craft-seomatic/issues/1519

https://datatracker.ietf.org/doc/html/rfc3987

**Comment by brandonkelly** [comment]
We can’t start automatically encoding every URL generated via `UrlHelper::url()` as that would be a breaking change. Even `UrlHelper::encodeParams()` explicitly avoids encoding param names and `/`, `{`, and `}` characters in param values, to prevent issues like #13603.

That said, I’ve just made it easier to properly encode URLs when it really matters, like for HTTP headers, by adding a new `UrlHelper::encodeUrl()` method and corresponding `encodeUrl()` Twig function for Craft 4.13 and 5.5 (17a918ce33c4c1f36d40627f4d65b1d74ae9a9e3). I also updated `craft\web\Response::redirect()` to start calling that, so `Location` headers will be encoded.

**Comment by khalwat** [comment]
@brandonkelly it's also not clear to me that you'd necessarily _want_ to encode all URLs anyway, given:

https://datatracker.ietf.org/doc/html/rfc3987

**Comment by joepagan** [comment]
Thanks for the change @brandonkelly that should help with the headers issue!

So does the new `encodeUrl` function take into consideration avoiding `/{}` characters in params?

>We can’t start automatically encoding every URL generated via UrlHelper::url() as that would be a breaking change. 

I get that developers/users will not expect this to behave this way on a minor update. Though one could say (maybe naively) that it's unlikely that it'll be a problem in most contexts (could even alert potential breaking change in the updates area)? So therefore there is still a strong argument for it being default behaviour.

RFC 3987 does seem to suggest that it shouldn't be required to encode links in HTML anymore as browsers and _most_ other systems appear to use IRI now (Only reviewed an AI overview), but [there is direct evidence that Google uses RFC3986 only in a crawling context](https://developers.google.com/search/docs/crawling-indexing/url-structure). 

Given they were both proposed in 2005, surely Google should have updated their docs by now if they are using RFC 3987.  There is a strong argument that all URLs are valid URIs and not IRIs otherwise websites could be punished by Google in SERPs.

Update:
- I submitted feedback on the Google docs page to request a "last updated" date on that page, and asked if RFC 3986 is still correct.
- Additional point: it's hard to know how many crawler systems are using either spec but the most important thing is that when Google crawls a Craft website that the website is using a URIs which Google deems valid.

**Comment by brandonkelly** [comment]
> So does the new `encodeUrl` function take into consideration avoiding `/{}` characters in params?

No, because in theory, it will only be used in contexts where any additional manipulation of the URL has already taken place.

> Though one could say (maybe naively) that it's unlikely that it'll be a problem in most contexts (could even alert potential breaking change in the updates area)? So therefore there is still a strong argument for it being default behaviour.

Any contexts where additional manipulation on query params would be needed would be examples of why we can’t do this automatically via `url()`. Because query string params are part of the generated URL which would need to be encoded.

**Comment by khalwat** [comment]
@joepagan this experiment appears relevant: https://www.monperrus.net/martin/google+url+encoding

> What happens if a URL contains encoded extended ASCII characters (i.e. > 128)?
> Googlebot does not modify the link. Characters are kept encoded, and the URLs presented in search results are the same as the ones you produced. However, it seems that Google complies with RFC 3987 (Internationalized Resource Identifiers (IRIs)) for interpreting and indexing this kind of characters (using UTF-8 encoding). Consequently, you should never url-encode iso-latin1 characters.

Also regarding URLs in sitemaps: https://www.sitemaps.org/protocol.html

> In addition, all URLs (including the URL of your Sitemap) must be URL-escaped and encoded for readability by the web server on which they are located. However, if you are using any sort of script, tool, or log file to generate your URLs (anything except typing them in by hand), this is usually already done for you. Please check to make sure that your URLs follow the [RFC-3986](http://www.ietf.org/rfc/rfc3986.txt) standard for URIs, the [RFC-3987](http://www.ietf.org/rfc/rfc3987.txt) standard for IRIs, and the [XML standard](http://www.w3.org/TR/REC-xml/).

Also see this answer here: https://stackoverflow.com/a/36667242/11820132

> Historically, the answer was "no". According to [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986), from 2005, such addresses are not URIs (and therefore not URLs, since URLs [are a type of URIs](https://www.rfc-editor.org/rfc/rfc3986#section-1.1.3)). Per the terminology of 2005 IETF standards, we should properly call them IRIs (Internationalized Resource Identifiers), as defined in [RFC 3987](https://www.rfc-editor.org/rfc/rfc3987), which are technically not URIs but can be converted to URIs simply by percent-encoding all non-ASCII characters in the IRI.

> Per modern spec, the answer is "yes". The [WHATWG Living Standard](https://url.spec.whatwg.org/) simply classifies everything that would previously be called "URIs" or "IRIs" as "URLs". This aligns the specced terminology with how normal people who haven't read the spec use the word "URL", which was one of the spec's [goals](https://url.spec.whatwg.org/#goals).

So I'm honestly not sure that the behavior you're asking for is actually needed or even desirable in many cases.

**Comment by brandonkelly** [comment]
Craft 4.13.0 and 5.5.0 are out with those new `encodeUrl()` methods.
