### ISSUE TITLE
[5.x]: Pressing return discards inline field changes and saves owner entry

### ISSUE THREAD

**Issue by tommysvr** [craftcms/cms#15841]
### Description
When inline-editing a Matrix field with the Element Index view, changes made to fields as discarded and the owner entry is saved when `return` is pressed.

### Steps to reproduce

1. Create a Matrix field with View more set to 'As an element index'
2. Edit the entries inline and make a change
3. Press return/enter

### Expected behavior
Matrix/inline changes are saved and user stays on the entry screen.

### Actual behavior
Owner entry is saved and redirected back to main element index; inline changes to Matrix field were not saved.

https://github.com/user-attachments/assets/aed087b9-b44e-4949-bd38-55b0c08ab91d

### Craft CMS version

5.4.6

### PHP version

8.2

### Installed plugins and versions

-

**Comment by i-just** [comment]
Thanks Tommy! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.5.0 is out now with that fix.
