### ISSUE TITLE
[4.x]: Registered JS not working when routed through a controller

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#15847]
### Description
While debugging a larger issues with CSRF tokens in a statically cached site in a complex build, I noticed that neither Craft's JS or Blitz's JS wasn't showing up on a page the is gets routed through a controller. 

So I tried reproducing it in a clean install (not cached, no plugins) and there I have the same issue.

Are we missing something essential here? Any pointer are appreciated.

### Steps to reproduce

I have a single called `testSingle`, located at `/test`, using the `_test.twig` template

_test.twig
````twig
{% extends '_layout.twig' %}

{% block content %}
    <h1>{{ entry.title }}</h1>
    {% js %}
        console.log('hier');
    {% endjs %}
{% endblock %}
````
Opening `/test` in the browser shows the console message.

Next in our case, we use the same template through a route and a controller:
```php
$event->rules['test/<step:\d{1}>'] = 'craft-module/web/index';
```

````php
public function actionIndex($step = 1)
{
    $entry = Entry::find()->section('testSingle')->one();

    return Craft::$app->getView()->renderTemplate('_test', [
        'entry' => $entry,
        'step' => $step,
    ]);
}
````

Pointing the browser to `/test/1` goes through the controller but the console message doesn't appear.

If we register an asset bundle (which includes a JS file) on our module, the same thing happens. It works as expected on the route that goes to the entry, it doesn't when the route goes through the controller.

### Expected behavior

Template JS & asset bundles are missing

### Actual behavior

Template JS & asset bundles work :) 

### Craft CMS version

4.12.5

### PHP version

8.2.22

### Operating system and version

/

### Database type and version

/

### Image driver and version

/

### Installed plugins and versions

None, new & empty craft install

**Comment by bencroker** [comment]
Can you try calling `Craft::$app->getView()->renderPageTemplate()` (instead of `renderTemplate()`)? I believe registered JS is only output on “page” templates.

**Comment by janhenckens** [comment]
That seems to have done the trick @bencroker! 🙌
