### ISSUE TITLE
[5.x]: MySQL error 1235 during Craft 4 to 5 upgrade

### ISSUE THREAD

**Issue by TUSAB-web** [craftcms/cms#15853]
### Description

MySQL error 1235 during Craft 4 to 5 upgrade

### Steps to reproduce

1. Craft 5 running in dev, deploying to staging
2. Deployed, ran composer install
3. Edited .env file with recommended MySQL settings for the upgrade
4. Run php craft up

### Expected behavior
A successful upgrade

### Actual behavior
Most migrations went through normally, but an error was received pretty far into the migration process:

'*** applying m231013_185640_changedfields_amend_primary_key
    > drop primary key elementId ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1235 This version of MySQL doesn't yet support 'existing primary key drop without adding a new primary key. In @@sql_generate_invisible_primary_key=ON mode table should have a primary key. Please add a new primary key to be able to drop existing primary key.'
The SQL being executed was: ALTER TABLE `craft_changedfields` DROP PRIMARY KEY (/home/site/vendor/yiisoft/yii2/db/Schema.php:676)’

Full error message here: 

[craft5-migration-error.txt](https://github.com/user-attachments/files/17283593/craft5-migration-error.txt)

### Craft CMS version

5.4.6

### PHP version

8.2.21

### Operating system and version

Azure Linux Web App

### Database type and version

MySQL 8.0.37

### Image driver and version

n/a

**Comment by brandonkelly** [comment]
I tried reversing the order of these lines:

https://github.com/craftcms/cms/blob/d44a2d4628b02db2290ecff4248ba70f664c070d/src/migrations/m231013_185640_changedfields_amend_primary_key.php#L19-L20

However then I get the following error:

```
1068 Multiple primary key defined
```

So I don’t think there’s anything we can do about this. You will need to run the upgrade locally from an environment with a real version of MySQL (like [DDEV](https://ddev.com/)):

1. Create a database backup on Azure
2. Restore the Azure backup locally
3. Run the Craft 5 upgrade
4. Create a database backup locally
5. Restore the local backup to Azure

**Comment by brandonkelly** [comment]
Craft 5.4.7 is out with a fix for this. Thanks for reporting! (And sorry about the earlier miscommunication.)
