### ISSUE TITLE
[5.x]: Craft::$app->elements->createElementQuery generating SQLSTATE[42S22]: Column not found: 1054 for greater than/less than conditions

### ISSUE THREAD

**Issue by matthewstick** [craftcms/cms#15859]
### Description
Unfortunately, I have to do some complex where queries.

I am following your documentation here:
https://craftcms.com/docs/5.x/development/element-queries.html#element-types

Your documentation references Trait yii\db\QueryTrait to construct the queries.

### Craft 4

This worked great.  I had to use content.field_equity_ovuqoppe  instead of just saying equity, but it worked.  And atleast I could figure that out in the built in debugger.  I could get the field names.  Was annoying to have to refer to it in this obscure way, but at least the queries worked.

```
$todayFormatted = \Craft::$app->formatter->asDate($todayString, 'php:Y-m-d');
$conditions = [
    'and',
    [
        'and',
        'content.field_equity_ovuqoppe = 1'
    ],
    [
        'or',
        ['and', 'content.field_closed_mrapuapo = 0', 'content.field_openingDate_aqjbbnel <= :today'],
        'content.field_openingDate_aqjbbnel > :today',
    ]
];


$allToursQuery = \Craft::$app->elements->createElementQuery(Entry::class)
    ->section('tours')
    ->andWhere($conditions)
    ->params([':today' => $todayFormatted])
    ->orderBy(['alphabeticalSort' => SORT_ASC, 'title' => SORT_ASC]);

return $allToursQuery;
```

### Craft 5

First the content.field_equity_ovuqoppe seemed to break.  If I simplify it to something like this, equity and closed fields pass through.  but it reports Column not found: 1054 Unknown column 'openingDate' in 'where clause'.  equity and closed (light box fields) which are equality and not conditional checks, actually do do not generate the error.

```
$todayFormatted = \Craft::$app->formatter->asDate($todayString, 'php:Y-m-d');
$conditions = [
    'and',
    [
        'and',
        'equity' => 1
    ],
    [
        'or',
        [
            'and',
            'closed' => 0,
            ['<=', 'openingDate', $todayFormatted]
        ],
        ['>', 'openingDate', $todayFormatted]
    ]
];

// Create the element query
$allToursQuery = \Craft::$app->elements->createElementQuery(Entry::class)
    ->section('tours')
    ->andWhere($conditions)
    ->orderBy(['alphabeticalSort' => SORT_ASC, 'title' => SORT_ASC]);

return $allToursQuery;
```

### Expected behavior

I'm guess my issue is either there is a new way to reference fields in the where clause for Craft 5, so maybe the documentation needs updated to better allow us to get fields.  Or there is an error itself in these conditions reference and it's not a widely used feature in craft cms so it hasn't come up before.

A: fix errors?
A.1: I expect openingDate to not generate an error.
A.2: Also, equity and closed, even though they don't generate an error, actually don't work.  In the db, some lightbox switch fields are 0 and some are 1, but 1 gives all results and 0 gives results.  Aka, but more simply, let's say my conditions were just this.

```
$conditions = [
            'and',
            [
                'and',
                'equity' => 1
            ]
        ];
```

I know this is not the purest way of writing a condition, but it's just to show a point quickly.  Aka, let's say the a database has 700 entries where equality is 1 and 300 entries where equality is 0.  The condition I just wrote returns 1000 for equality is 1 and 0 entries where is 0.

B: Update documentation?
2: If this is just a documentation issue, updated documentation so this is figure-outable.  Having nested where clauses in a select statement is not that unusual.  I'm not trying to do something that crazy.  Just filter my data based on some field values.

Thanks!

### Craft CMS version

5.4.6

### PHP version

8.2.0

### Operating system and version

Linux 5.15.49-linuxkit

### Database type and version

MariaDB 10.4.27

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

Amazon S3	2.2.1
CKEditor	4.2.0
Cloner	3.0.1
Cloudflare	3.0.1
Control Panel CSS	3.0.0
Control Panel JS	3.0.0
Feed Me	6.4.0
Field Manager	4.0.2
Fix FKs	2.1.0
Formie	3.0.7
Incognito Field	2.0.0
Maps	5.0.3
Neo	5.2.9
SuperSort	5.0.0
Word Translations	4.0.2

**Comment by brandonkelly** [comment]
The entire `content` table went away in Craft 5, in favor of a `content` column that stores JSON data for custom fields within the `elements_sites` table.

Custom fields have a new `getValueSql()` method, which can be used to get the correct SQL expression you should use in place of `content.field_<handle>_<suffix>`.

```php
$entryType = Craft::$app->entries->getEntryTypeByHandle('myEntryType');
$fieldLayout = $entryType->getFieldLayout();
$equityField = $fieldLayout->getFieldByHandle('equity');
$closedField = $fieldLayout->getFieldByHandle('closed');
$openingDateField = $fieldLayout->getFieldByHandle('openingDate');

$conditions = [
    'and',
    [
        'and',
        $equityField->getValueSql() => 1
    ],
    [
        'or',
        [
            'and',
            $closedField->getValueSql() => 0,
            ['<=', $openingDateField->getValueSql(), $todayFormatted]
        ],
        ['>', $openingDateField->getValueSql(), $todayFormatted]
    ]
];
```

(Replace `myEntryType` with the actual entry type handle.)

**Comment by matthewstick** [comment]
Thanks for this.  I still think there might be a bug.

This took me forever to figure out ◡̈ 

It seems $equityField->getValueSql() (which is a light switch) return all entries if I put 0.  And no entries if I put 1.  There are definitely values selected.  I tried "1" as well as true.  But they all show up if 0. 

I have a reduced version here for simplicity

**ALL SHOW UP**
```
$allToursQuery = \Craft::$app->elements->createElementQuery(Entry::class)
            ->section('tours')
            ->where([$equityField->getValueSql() => 0])
            ->orderBy(['alphabeticalSort' => SORT_ASC, 'title' => SORT_ASC]);
```

**NONE SHOW UP**
```
$allToursQuery = \Craft::$app->elements->createElementQuery(Entry::class)
            ->section('tours')
            ->where([$equityField->getValueSql() => 1])
            ->orderBy(['alphabeticalSort' => SORT_ASC, 'title' => SORT_ASC]);
```

also tried "1" and true.

**But FINALLY, if I set to "true"** - it works.  That was a last ditch effort of mine.


Probably because lightswitch fields technically become CHAR(5)?
CAST((`elements_sites`.`content`->>'$.\"462a27bf-25ce-4333-8331-94f801936176\"') AS CHAR(5))

Also, same issue with date fields.  

CAST((`elements_sites`.`content`->>'$.\"ed3a7d60-0ad2-4c83-8304-9a44c673841e\".\"date\"') AS DATETIME)

In craft 4, I could just do date.  But craft 5, seems it is datetime.  
So I need to compare to 2024-11-04 00:00:00 instead of 2024-11-04


FINALLY, this is what I have as the end result
```
public function getAllToursQuery($todayString = "now")
    {
        // Format the date as a full DATETIME string
        $todayFormatted = \Craft::$app->formatter->asDatetime($todayString, 'php:Y-m-d H:i:s');

        // Get the field handles and SQL expressions
        $entryType = \Craft::$app->entries->getEntryTypeByHandle('default');
        $fieldLayout = $entryType->getFieldLayout();

        $equityField = $fieldLayout->getFieldByHandle('equity');
        $closedField = $fieldLayout->getFieldByHandle('closed');
        $openingDateField = $fieldLayout->getFieldByHandle('openingDate');

        // Set up conditions using raw SQL expressions for field values
        $conditions = [
            'or',
            [
                'and',
                new \yii\db\Expression($closedField->getValueSql() . ' = "false"'), // Ensure raw SQL is used here
                ['<=', new \yii\db\Expression($openingDateField->getValueSql()), $todayFormatted]
            ],
            [
                '>',
                new \yii\db\Expression($openingDateField->getValueSql()),
                $todayFormatted
            ]
        ];

        // Construct the query
        $allToursQuery = \Craft::$app->elements->createElementQuery(Entry::class)
            ->section('tours')
            ->andWhere(new \yii\db\Expression($equityField->getValueSql() . ' = "true"')) // Ensure raw SQL is used here as well
            ->andWhere($conditions)
            ->orderBy(['alphabeticalSort' => SORT_ASC, 'title' => SORT_ASC]);
        
        return $allToursQuery;
    }
```

What do you think?  Would love to see this documented somewhere so I don't have to guess.

Thanks!

**Comment by brandonkelly** [comment]
Sorry, yeah, I should have clarified that it needs to be `true`/`false`.
