### ISSUE TITLE
Locale error message issue upon user deletion

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/cms#1585]
### Description

I noticed that if you delete a user with a different locale to that of the default Craft locale their session error displays in the default locale, not that of the user.

For example the default locale is French, but the user’s preferred locale is English. The user was then deleted by another user causing the ‘Your session has ended’ alert, when the user attempts to re-enter their password it doesn’t work (because they’ve been deleted obviously) but the error message displays in French, when the user would only understand English.

### Additional info

- Craft version: 2.6.2968

**Comment by brandonkelly** [comment]
The strings for that session modal are set in JavaScript on page load, and they are set in user’s preferred language. The only way the session modal could have shown any messages in the wrong language is if the user’s preferred language had changed in the background (e.g. from a separate browser tab), so the main browser tab had out-of-date translation strings.
