### ISSUE TITLE
[5.x]: Color Field - Hex Indicator is over input value

### ISSUE THREAD

**Issue by HigumaSan4050** [craftcms/cms#15868]
### Description
In fields of type 'Color' the hex indicator is positioned over the value of the input field value

You can test it, when creating a new field of type 'Color' and set in the input field of 'default color' the value 'ffffff' (6 f)
it looks like #fffff (with 5 f)

### Craft CMS version

5.4.7

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.4.8 is out with that fix. Thanks again!
