### ISSUE TITLE
what about setting up multibyte, timezone, etc. for console applications? And...User...

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1587]
### Description
With regards to other work on multibyte characters as well as the current issue about console User, I look at craftcms/cms/bootstrap/console.php, and note how bare it is compared to bootstrap/web.php.

I don't think multibyte is going to work at all in console apps, nor utf8 locale, nor rather crucially database TZ, upon which all DateTime creation and arithmetic depend.

I use all of these things in the cron-called mainspring timer of my database agent, in the course  of creating and comparing various kinds of records. Should I have to replicate your setup in the init phase of the plugin implementation, and would this anyway come  early enough to take care of everything in early stages of the Application build?

This  kind of raises a point also about #1581 and its cousin #1562. Along with what seems requisite setup just noted for use of  Craft console beyond scaffolding migrations, Uset is going to be in there also as a requirement. Wouldn't it be good if Craft provided one, set  to guest  initially, and able to be set to a Craft Uset identity we identify for it in the plugin init? 

Our responsibility as far as permitting use of this Craft User.  Setting it in permission-protected ed app config is probably enough -- that's equivalent to what craft config can do itself there..

Extra points: I am pretty confident I had every bit of this working properly, without extras as above needing to be added, in a non-released Craft 2 version of the agent system, where i first worked out last year the cron-console app approach to its clock, so much better than the url way. In particular I just set the Entry author id as part of configuring the new object, unchanged from the web app version. Has Yii2 changed that much, or are the things above teething problems on Craft 3 because it did? 

### Steps to reproduce

1. not relevant this time
2.

### Additional info

PHP version	7.1.2-4+deb.sury.orgxenial+1
Database driver & version	MySQL 5.7.17-0ubuntu0.16.04.1
Image driver & version	GD 7.1.2-4+deb.sury.orgxenial+1
Craft edition & version	Craft Personal 3.0.0-beta.9
Yii version	2.0.11.2
Twig version	2.1.0
Guzzle version	6.2.1
Imagine version	0.7-dev
Plugins

Trimmer	1.0.0
Bactrian	1.0.0
Standards Agent	2.0.4

**Comment by takobell** [comment]
Went ahead and did some UTF-8 and default time zone normalization in console's bootstrap in https://github.com/craftcms/cms/commit/6ac12354de6e5872f4d7f5c3e6626a09b7bb4e5c

The default user thing for a console request feels like it should warrant a whole other conversation/feature request, though.  I feel like there would already be ways to pull that off in console's bootstrap and/or in a `craft/config/console.php` config file.

**Comment by narration-sd** [comment]
Just pulled it via Composer dev-develop, and looking very healthy now, as well as test-running in console tasks. My soon-to-be-Craft 3-reinstated hung task handlersetc.  will no doubt be much happier due to DateTimes being consistent, so good thanks here.

Interesting your thoughts about a default user. Brandon has fixed the base problem on #1581, and such could well follow on, given you come up with something you feel nice to do.

From my own view, I always set, the Entry authorId, needfully, and its in fact a basic config item for the plugin. For someone less concerned/attentive, though, having a default user (and internally defaulting it to 1/admin) would probably be pretty helpful, esp. at the initial seeing-it-can-work stage with console. 

Particularly as unless I've missed something obvious, it's not a thing to have PhpStorm nicely run xdebug for you on a remote console, as in Vagrant or staging servers.

Always appreciate the way you consider things through, Brad, felt that again here -- C.
