### ISSUE TITLE
[5.x]:  The "Twig\Extension\EscaperExtension::addSafeClass()" method is deprecated

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#15873]
### Description

addSafeClasses is deprecated and throws deprecation warnings in PHPUnit

https://twig.symfony.com/doc/3.x/deprecated.html#extensions

https://github.com/craftcms/cms/blob/5.x/src/web/View.php#L389-L390

![Image](https://github.com/user-attachments/assets/a8396a8e-b672-4d8f-9a4d-74130c52123b)

### Craft CMS version

5.4.7.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next release.

**Comment by leevigraham** [comment]
@brandonkelly I spotted another twig deprecation but I can't remember what it was… I'll try and recreate it.

**Comment by brandonkelly** [comment]
Craft 5.4.8 is out with that initial one. Thanks again!
