### ISSUE TITLE
[5.x]: Condition on global set with a lightswitch field not working

### ISSUE THREAD

**Issue by ggallo909** [craftcms/cms#15881]
### Description
When creating a global set with a lightswitch field and other fields that have a condition to be visible only if the lightswitch is enabled, clicking on the lightswitch in the globals section will not make the hidden fields to show. The hidden fields are visible only after saving the global set.

### Steps to reproduce

1. create a global set containing at least one lightswitch field and another field of any type
2. set one or more fields' Global set Condition to be visible only if the lightswitch is enabled
3. save and open the new global set
4. enable the lightswitch

### Expected behavior
The hidden fields with the Global set Condition associated to the lightswitch should become visible right after enabling the lightswitch. Disabling the lightswitch should hide the fields with the condition.

### Actual behavior
When toggling the lightswitch nothing happens and the hidden fields does not become visible. Only after saving the global set the hidden fields become visible if the lightswitch has been enabled and if the condition is set to make visible fields after enabling the lightswitch.

![Image](https://github.com/user-attachments/assets/5bad656a-fefe-41f0-a7bc-de8504bdff42)

### Craft CMS version

5.4.7.1 

### PHP version

8.2

### Operating system and version

ubuntu in wsl

### Database type and version

mysql 8.0

### Image driver and version

n/a

### Installed plugins and versions

It's a fresh test installation without any additional plugin

**Comment by brandonkelly** [comment]
This is currently expected behavior, as we haven’t updated global set edit pages to the new ElementEditor features. It would be a big lift, and we’re working toward replacing global sets with Single sections, so probably won’t end up happening.

**Comment by ggallo909** [comment]
Sounds great knowing that the globals will be replaced by single sections, that's something I wished for long time. Thank you for the clarification @brandonkelly I'm closing this issue.

**Comment by brandonkelly** [comment]
You can convert globals to singles already using the `craft entrify/global-set <handle>` command! We just need to improve the UI before we fully deprecate globals.

**Comment by ggallo909** [comment]
That's awesome @brandonkelly! If I understand correctly globals in the future will just be simple single sections, right? Or will they be a special single entry? I'm wondering if it's a good practice to start working with single sections as global settings content containers instead of the old globals, for new projects.

**Comment by brandonkelly** [comment]
@ggallo909 They’ll get converted to normal Single sections, just like the `entrify/global-set` command does currently.

Single sections already work well as global set replacements. With the [preloadSingles](https://craftcms.com/docs/5.x/reference/config/general.html#preloadsingles) config setting enabled (which is by default ever since 4.4 came out), your single entries will even be globally available within your templates (via their section handle), just like global sets. So you can access their custom fields via `sectionHandle.fieldHandle` without actually needing to load the entry beforehand.

**Comment by ggallo909** [comment]
@brandonkelly awesome, thank you!
