### ISSUE TITLE
[5.x]: Redundant margin rule for preview button icon

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#15883]
### Description

Since the CP icon set was changed for Craft 5 there's a left-over `-2px` margin for the "eye" icon next to the preview button. This was to balance the previous icon, but now looks off (not verticaly centered):

![Image](https://github.com/user-attachments/assets/b3652e4a-3391-4674-b286-0af021fb225c)

Without the margin it looks centered, like this:

![Image](https://github.com/user-attachments/assets/e6a6aae0-86d7-42d9-9694-498efbb2307c)

### Expected behavior

The icon looks right.

### Actual behavior

You're in your room, sleeping, when somebody knocks on the door. Trying to shake-off last nights' hangover you drag yourself to the door and look through the peephole: Two men with nondescript haircuts, monochromatic t-shirts, sunglasses. They seem normal, too normal! 

"SH*T, IT'S THE DESIGN POLI ..."

Your gun is under the pillow, no time for that. You start to turn and look for the nearest window, but the door is already busted, and you are pushed to the floor with your hands tied behind your back.

The next few days... the interrogation, the courtroom, all is a blur.

You are now sitting in a dark prison cell with your face in your hands. Your life shouldn't have come to this. If only you hadn't forgotten about that margin. _If only_...

### Craft CMS version

5.x

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next release.
