### ISSUE TITLE
Change focal point without re-saving image

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#1588]
It would be nice to set or change the focal point without re-saving image and consequently losing quality by adding new compression artifacts.

**Comment by swey** [comment]
@andris-sevcenko Still no totally solved. The image files still will be replaced if only a focal point changes.

Why this is a problem to us:
-We have very big files, the saving is delayed even the image itself is not changed
- The file timestamps change
- We use Cloudinary as storage, which means we need unnecessary operations and the "changed" image has to be re-calculcated in many transformations

**Comment by andris-sevcenko** [comment]
Fixed via  aee8f07
