### ISSUE TITLE
[5.x]: Creating new filesystem - .gitignore

### ISSUE THREAD

**Issue by patrikkaprinay** [craftcms/cms#15887]
### Description
When I'm trying to create a new filesystem at path **@web/assets/files** in a newly created app I get the error:

> file_put_contents(https://[web_address]/assets/files/.gitignore): **Failed to open stream: HTTP wrapper does not support writeable connections**

### Steps to reproduce

1. Settings > Filesystems > New filesystem
2. Add name
3. Toggle "Files in this filesystem have public URLs"
4. Enter Base URL: `@web/assets/files`
5. Enter Base Path: `@web/assets/files`
6. Save

### Expected behavior
New filesystem gets created

### Actual behavior
Error page with error:
file_put_contents(https://[web_address]/assets/files/.gitignore): **Failed to open stream: HTTP wrapper does not support writeable connections**

![Image](https://github.com/user-attachments/assets/24f7d941-2a03-4ee4-87aa-86345dfac55f)
![Image](https://github.com/user-attachments/assets/a066b8cf-fec4-4fa2-83d7-eade61755b06)

### Craft CMS version

5.4.7.1

### PHP version

8.2.22

### Operating system and version

MacOS Sequoia 15.0

### Database type and version

MariaDB 10.5.9

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- CKEditor (4.2.0)
- Contact Form (3.1.0)
- SEO (5.0.0)

**Comment by i-just** [comment]
Hi, thanks for getting in touch! 

The Base Path should be set to the filesystem’s root directory on the server (not the URL). One option would be setting it to `@webroot/assets/files`. You can find more info on how to configure it [here](https://craftcms.com/docs/5.x/reference/element-types/assets.html#local-filesystems).

I hope this helps!

**Comment by patrikkaprinay** [comment]
then shouldn't it display a in-house error message, instead of a PHP panic screen?

**Comment by i-just** [comment]
You’ll see the actual error with the stack trace if you have [devMode](https://craftcms.com/docs/5.x/reference/config/general.html#devmode) enabled. It’s usually enabled in the development environment where seeing the details is helpful. If it’s disabled, a dialed-down error will be shown.
