### ISSUE TITLE
[5.x]: Copy or move modal too many sections are in it.

### ISSUE THREAD

**Issue by exin12** [craftcms/cms#15900]
### Description

If you have too many sections, you cannot select them with the “Copy or move to” function because you cannot scroll in the window. 
see picture under Actual behavior

### Steps to reproduce

1 CP -> Entries
2. select an entry to copy or move
3. and have more than 8 sections

### Expected behavior

The ability to scroll.

### Actual behavior

see picture (German)

![Image](https://github.com/user-attachments/assets/79751ee9-8f66-4003-b0ad-c03a4a3b338e)

### Craft CMS version

Craft Pro 5.4.8

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.4.9 is out with that fix. Thanks again!
