### ISSUE TITLE
[5.x]: craft\fieldlayoutelements\Template rendered in TEMPLATE_MODE_SITE

### ISSUE THREAD

**Issue by commercial-hippie** [craftcms/cms#15926]
### Description
When using `craft\fieldlayoutelements\Template` in the admin panel ID like to use `{% import "_includes/forms" as forms %}`, but because it's rendered in SITE mode the CP templates are not loaded.

It works when I change vendor/craftcms/cms/src/fieldlayoutelements/Template.php:103 to `TEMPLATE_MODE_CP`, but I guess that could cause other issues.

Maybe there is a better way to accomplish this?  My end-goal is to use the `elementSelectField` helper.

Alternatively template mode could be added as a config option:
```
new Template([
    'template' => '_myplugin/test.twig',
    'templateMode' => View::TEMPLATE_MODE_CP,
]),
```

### Steps to reproduce
```
Event::on(
    FieldLayout::class,
    FieldLayout::EVENT_CREATE_FORM,
    function (CreateFieldLayoutFormEvent $e) {
        if ($e->element instanceof Course) {
            $e->tabs[] = new FieldLayoutTab([
                'name' => Craft::t('app', 'Test'),
                'layout' => $e->sender,
                'elements' => [
                    new Template([
                        'template' => '_myplugin/test.twig',
                    ]),
                ],
            ]);
        }
    }
);

// test.twig
{% import "_includes/forms" as forms %}
```

### Expected behavior
Should load the helpers.

### Actual behavior
```
Unable to find the template “_includes/forms”
```

### Craft CMS version

5.4.71

### PHP version

8.2

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch!

The `Template` UI Element is meant to reference a template file from within your `templates/` folder. That said, it is possible to change the template mode in your template like so:
```
{% set oldTemplateMode = view.templateMode %}
{% do view.setTemplateMode('cp') %}
{% import "_includes/forms" as forms %}
<p>this is where the `elementSelectField` would go</p>
{% do view.setTemplateMode(oldTemplateMode) %}
```

There’s also this old but related stack exchange question which provides additional information on how you could achieve what you’re after: https://craftcms.stackexchange.com/questions/1384/is-it-possible-to-use-includes-forms-outside-of-the-control-panel

I hope this helps!

**Comment by commercial-hippie** [comment]
Hi

Thanks for getting back to me.  I did see the stackoverflow answers, but in my case I'm actually using the forms includes in the control panel.

The problem is when using `\craft\fieldlayoutelements\Template`.  It's explicitly set to render the template with `View::TEMPLATE_MODE_SITE`.  I don't think `{% do view.setTemplateMode('cp') %}` will do anything in this case.  See the code I copied out below:

```
vendor/craftcms/cms/src/fieldlayoutelements/Template.php:99
try {
    $content = trim(Craft::$app->getView()->renderTemplate($this->template, [
        'element' => $element,
        'static' => $static,
    ], View::TEMPLATE_MODE_SITE)); <------------------------------
} catch (Throwable $e) {
    return $this->_error($e->getMessage(), 'error');
}
```

**Comment by i-just** [comment]
I tested both the snippet I provided and one of the latest suggestions from the Stack Exchange - both with the event and template code you provided, and they both work.

> The problem is when using \craft\fieldlayoutelements\Template. It's explicitly set to render the template with View::TEMPLATE_MODE_SITE.

Yes, that’s correct. This is what makes this part of your event code
```
new Template([
    'template' => '_myplugin/test.twig',
]),
```
load the `test.twig` located in your `templates/_myplugin` folder. 

If you then use the snippet I pasted before, you’ll be able to import the `forms.twig` and use the `elementSelectField` helper (or you can use the custom twig filter). 
I added a screenshot showing how both options render what I believe you’re after in the control panel:

![Image](https://github.com/user-attachments/assets/9e741dac-3165-4f58-a48d-fdb7c4fb6c82)


I hope this clarifies things, but feel free to reply if you’ve run into any further issues or if I missed your point.
