### ISSUE TITLE
[5.x]: Plain text field with handle "sectionId" returns null value after migration from Craft 4 to Craft 5

### ISSUE THREAD

**Issue by sydneyhaggard** [craftcms/cms#15923]
### Description

Plain text field named "Section Id" with handle "sectionId" does not render input data from CMS backend inside rendered template. This previously worked when my project was running Craft 4, but returns a null value after migrating project to Craft 5. Appears to be a potential conflict with a protected handle in the [Craft 5 Class reference on entries](https://docs.craftcms.com/api/v4/craft-elements-entry.html#property-sectionid). Changing handle of field to "sectionID" works and bypasses this issue.

### Steps to reproduce

1. Spin up Craft 4 project.
2. Create matrix field and matrix entry.
3. Create plain text field called "Section Id" with handle "sectionId". Add "Section Id" to matrix entry and template.
![Image](https://github.com/user-attachments/assets/0c712b96-8e27-49c3-80ea-8fc74a52cb52)
![Image](https://github.com/user-attachments/assets/f73b1ee3-a0fb-4706-ad8e-9d1f07f32ad8)
4. Add "Section Id" field to entry and set a value for the field. 
![Image](https://github.com/user-attachments/assets/8049eff4-2e7b-4ae9-b74f-c8e24b559844)
5. Save entry with "Section Id" field value.
6. Verify in template that "sectionId" handle outputs value as expected on frontend template.
![Image](https://github.com/user-attachments/assets/5df7c25d-b6b0-452e-8a29-64ba5e100852)
7. Migrate site from Craft 4 to Craft 5.
8. Verify "Section Id" field still exists with handle "sectionId"
![Image](https://github.com/user-attachments/assets/3f9478c3-446f-4a3b-a884-d89adc7ba1e0)
9. Verify "Section Id" is available on the entry backend and has content saved to the field.
![Image](https://github.com/user-attachments/assets/87fb90aa-c841-4e87-ae7f-89a9d0dd9389)
10. Verify "Section Id" does NOT render on front end template.
![Image](https://github.com/user-attachments/assets/48aa10f7-3863-44d2-9984-f45c8348d58a)
11. Navigate back to field in Settings.
12. Change handle of "sectionId" to "sectionID". Modify entry template to match.
![Image](https://github.com/user-attachments/assets/3455369b-0986-4863-bb83-6a466daf89da)
![Image](https://github.com/user-attachments/assets/69fe456b-3394-45e5-9c14-4f3dcf1de3ad)
13. Verify data renders on front end template. 
![Image](https://github.com/user-attachments/assets/173fe56b-a503-4ee4-a798-347285f2fcf6)

### Expected behavior

For Section Id field with handle "sectionId" to render entered value on backend on front end template.

## Actual behavior

 Section Id field with handle "sectionId" returns with null value and does not render on front end template.

### Craft CMS version

5.4.8

### PHP version

8.2

### Operating system and version

MacOS Sequoia 15.0.1

### Database type and version

 mariadb:10.5 

### Installed plugins and versions

- CKEditor by Pixel & Tonic. v4.2.0
- Embedded Assets by Spicy Web. v5.1.2
- SEO by Ether Creative. v5.0.0

**Comment by i-just** [comment]
Hi, thanks for getting in touch and clear replication steps!

This happens in v5 because matrix blocks are now entries; all entries have a `sectionId` property, which, for the nested entries (like matrix “blocks”), is `null`. Renaming that handle is the way to go. I just raised a PR to make the `sectionId` field handle reserved in the context of an Entry Type.

**Comment by brandonkelly** [comment]
Craft 5.4.9 is out now, where `sectionId` is now a reserved field handle for entry types.
