### ISSUE TITLE
[5.x]: Clicking "Save" in element slideouts doesn't save the element if the initial slideout auto-save hasn't triggered

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#15938]
### Description

If the "Save" button in an element slideout is clicked after making an initial content change, _before the slideout auto-save has had a chance to trigger_, the slideout will close and Craft will create a provisional draft behind the scenes, i.e. leaving the element in an "Edited" state, instead of actually saving it.

This behavior can make quick-editing elements via slideouts a chore, as authors needs to remember to wait for the auto-save to trigger after making their edit. If not, they will have to re-open the "Edited" element after the slideout closes, and then click "Save" again to actually save their changes.

_I'm not able to reproduce this behavior when using the Cmd+S shortcut to save changes in slideouts, it specifically only happens when clicking the Save button._

https://github.com/user-attachments/assets/222e60b2-44fb-4356-aaf3-7148c9237c7b

### Steps to reproduce

1. Edit an element in a slideout. _Make sure the element has no "unsaved changes" from before._
2. Make a change to a field, and then quickly click the slideout "Save" button, before the auto-save has had a chance to trigger.
3. Observe that after the slideout closes, the element chip or card becomes tagged with "Edited", as Craft has created a provisional draft instead of actually saving the element.

### Expected behavior

Clicking the "Save" button in an element slideout should always save the element.

### Actual behavior

Clicking the "Save" button does not save the element if the slideout hasn't had time to create a provisional draft before the button is clicked.

### Craft CMS version

5.4.8

### PHP version

8.2.22

### Operating system and version

macOS 14.6.1 (DDEV v1.23.4)

### Database type and version

MySQL 8.0.36

### Installed plugins and versions

None

**Comment by i-just** [comment]
Hi, thanks for reporting! 

It looks like the changes are saved, but then a provisional draft is still created with content that’s already been saved. I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.4.9 is out with that fix. Thanks again!
