### ISSUE TITLE
The DeleteStaleTemplateCaches task can potentially miss some caches that should be busted

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#1593]
### Description

When the DeleteStaleTemplateCaches task is running, it applies a `status = null` to the element query to decide if the current element's cache needs to be busted or not.

This has the potential to bump the elements that should be in the results out past the element limit, whether that is 100 (the default) or a custom limit that is set on the query (`limit = 20`).

If that happens, it won't clear certain caches that should have been cleared.

### Additional info

- Craft version: 2.x
- PHP version: 7.0
- Database driver & version: n/a
- Plugins & versions: n/a

**Comment by takobell** [comment]
Fixed in C2 for the next release.

**Comment by narration-sd** [comment]
good man also
