### ISSUE TITLE
[5.x]: Loss of content when converting a Global Set to an Entry (Single) using the entrify command

### ISSUE THREAD

**Issue by alexanderbuergin** [craftcms/cms#15935]
### Description

Hi Craft team,

I’m encountering an issue with the entrify command when trying to convert a Global Set into an Entry (Single). During the process, all the content from the original Global Set is lost. It seems like the command successfully performs the conversion, but none of the content is transferred. 

I’ve tried different variations of this command, but I keep getting the same result: the new entry is empty after the conversion. The content from the original Global Set does not appear in the new entry.

I’m wondering if I’m doing something wrong or if the entrify command is not functioning as expected. In Craft CMS 4, this worked without any issues.

Could you please advise if this is a bug or if there’s a specific process I need to follow to retain the content during conversion?

### Steps to reproduce

Here’s the sequence I executed in the terminal:

```
php craft entrify/global-set gloOrganization
Have you already created a section to replace the “Organisation” global set (yes|no) [no]:
Let’s create one now, then.
Section name: [Organisation] 
Section handle: [gloOrganization] 
Enable entry versioning for the section? (yes|no) [yes]:
Have you already created an entry type for this section? (yes|no) [no]:
Let’s create one now, then.
Entry type name: [Organisation] gloOrganization
Entry type handle: [gloorganization] 
 → Saving the entry type … ✓
 → Saving the section … ✓

✅ Section created.

Which section should entries be saved to? (gloOrganization,?): gloOrganization
 → Converting “Organisation” … ✓

✅ Global set converted.

 → Updating user permissions … ✓

💡 Run this command on other environments immediately after deploying these changes:
   
php craft entrify/global-set gloOrganization --section=gloOrganization
```

Thank you for your help and for all the great work with Craft CMS!

### Craft CMS version
5.4

### PHP version
8.3

### Images

![Image](https://github.com/user-attachments/assets/77903164-b233-4f90-b653-4634e3c2d734)
![Image](https://github.com/user-attachments/assets/5a4f980c-d901-4fa8-a643-940824f2ee20)

**Comment by i-just** [comment]
Hi, thanks for reporting! That’s a bug. We’re working on a fix.

**Comment by alexanderbuergin** [comment]
Thanks

**Comment by brandonkelly** [comment]
Just released Craft 5.4.9 with a fix for this. Thanks again!

**Comment by pascal-blaser** [comment]
Hi everyone, sorry but I think the issue isn't fully fixed yet. To me it seems like the content of matrix fields is still getting lost during the conversion. 

I just tried it with two different global sets with one matrix field each. Both fields contained 3 entries, all of them disappeared.

**Comment by brandonkelly** [comment]
@pascal-blaser Can you please send your database backup (from before running the command) and composer files over to support@craftcms.com, and point out which global set you are converting?
