### ISSUE TITLE
[5.x]: Buttons in Assets fields overflow with long selection labels

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#15931]
### Description

If the `“Add” Button Label` for an Assets field is a bit longer than the default, it can overflow in narrow fields:

![Image](https://github.com/user-attachments/assets/81b696de-dad5-4b42-ba3a-b9697aa16955)

We like to use a slightly verbose label (approx. _Select an asset from the media library_) because we feel the default labels don't make it quite clear what the two buttons do, and clients end up uploading duplicates of images that are already in the assets library.

### Expected behavior

The button label should be able to break into multiple lines so it doesn't overflow.

### Actual behavior

The button label overflows its container and bleeds into the next field.

### Craft CMS version

5.4.8

### PHP version

8.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 4.12.8 and 5.4.9 are out with a fix.
