### ISSUE TITLE
two slighter but usability-substantiating Asset issues, at beta 9

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1594]
### Description
I was testing the fix on Asset transforms, which track per-Suite fine now, very nicely, but, with a double proviso: 
1) you have to declare the Volume path as a full server path, or this will not be so for transforms, you'll get a non-executed transform path continually  -- and
2) you need to declare the url path as absolute-relative (/resources/images, vs. resources/images) if you want  to work out of one set of images (not Site-relative).

Then, 
- propose that we should be able to use relative paths for Volume::$path, in volumes.php file. In fact, you really want to do that to cover different server installs, with differing heads of full path,  no?
- propose in fact that these relative paths ought to be allowed to start with a '/' slash, avoiding much confusion 
- I suspect that you don't want to do this normalization as I first considered, for Volume::$url, as the distinction between domain-relative and currrent path-relative is what allows use or not of per-Site assets, at least at present if you  didn't declare the asset especially as not per-Site. 
- ...then you see where the further fun begins...
- thus propose very clear documentation of just how to use per-Site assets, in particular to make only some of them per-Site. As far as code/concept  behind this, it would seem very good if the solution is _not_ to have to declare another field type to get non/or/per-Site assets.

Just as a side note, I had a lot of fun with *some* thumbnails not showing up in the CP - a new one. This waasn't Craft, it was Chrome latest. Yet another funny requiring to clear its entire cache after a while of complex use, similar presentations changing, where forced full refresh doesn't cut it. This has been something wrong for years, in case you hit it.

### Steps to reproduce
1. As above, try different pathing modes in volumes.php
2. See what happens to them, on a muti-Site, differing assets per site (but not different asset Volumes per site) site (!). 
3.  Plus try setting up partially differing volumes when you want to sort out clarity on that.

### Additional info

PHP version	7.1.2-3+deb.sury.org~xenial+1
Database driver & version	MySQL 5.7.17-0ubuntu0.16.04.1: 
Image driver & version	GD 7.1.2-3+deb.sury.org~xenial+1
Craft edition & version	Craft Personal 3.0.0-beta.9
Yii version	2.0.11.2
Twig version	2.1.0
Guzzle version	6.2.1
Imagine version	0.7-dev
Plugins
 -- this test site virgin composer-project installed, none added

**Comment by brandonkelly** [comment]
Craft never actually parses volume URL fields; it will just output whatever you put in there, verbatim.

So if you put in a relative URL (e.g. `resources/images`), it’s only going to work when you’re requesting the root of the correct domain, because browsers will always resolve that as relative to the current domain and “directory” of the URI. E.g. if you were requesting `http://foo.com/about/team`, a relative URL that begins with `resources/images` would resolve to `http://foo.com/about/resources/images`.

If you put in a root-relative URL (e.g. `/resources/images`), it will work regardless of the URI you are accessing, but it will still only work from a single domain. So if you have a multi-site install with two different domain names, you need to be aware that browsers will automatically enter the domain name.

I don’t think Craft should _enforce_ a certain URL format, but I’ve gone ahead and updated the instructions and placeholder text to nudge people in the right direction.

> <img src='https://shipusercontent.com/d561bdad09a8fc73ae146a6a31c46a82/Screen%20Shot%202017-04-05%20at%2012.22.52%20PM.png' title='Screen Shot 2017-04-05 at 12.22.52 PM.png' width=514>

**Comment by narration-sd** [comment]
Fair enough thinking as far as the url part, but don't you want to look again at the apparent need for a full root path on the filesystem value?

This is going to fail often, crossing between deployment filesystems -- dev to staging to public -- as the roots will change. And if you try a partial path for filesystem location, it doesn't work on Sites, due to some relation probably to the initial directory. This is what led me into noting the issue. 

We used to use environmentals to solve this, but i think can't now, or am I missing something?

Back on urls, I know how they work, of course, just trying there to make it easier on everyone, as this is sort of a blind area to hit when Assets 'just don't work', or indexing of them. Whether you can again depends on intents for how Site-differentiated individual assets are supposed to operate.

**Comment by brandonkelly** [comment]
Yeah I suppose we should make a similar recommendation for the path. Done in ab59cc5a65fe8d8d70f295cc3c322e62a9540f98.

**Comment by narration-sd** [comment]
Ok, and I pulled it because now I can, reloaded the Vagrant, and had a look...

- think it's fine for url, thanks
- good for filesystem, but think  'is recommended' should add 'so that Assets will work consistently with multiple Sites' -- or somesuch....

Then, seems what i was missing on handling deployments filesystems was staring me in the face, had i looked -- the ASSET_BASE_PATH/_URL pair. Or even as I was first thinking, nested Volume configs, but I like the true environmentals better.  A nod, as quite pleasantly often...
