### ISSUE TITLE
[5.x]: composer create-project skips database connection

### ISSUE THREAD

**Issue by noregt** [craftcms/cms#15943]
### Description
When installing CraftCMS, the installation procedure will skip the database connection, but starts asking for the username etc and then:
*** failed to install Craft: An error occurred while executing the "craft\migrations\Install migration: Craft CMS can’t connect to the database.

Using version 5.2 works: composer create-project craftcms/craft . "5.2.*", so I used that as the starter

### Steps to reproduce

1. run the installer as composer create-project craftcms/craft . 

### Craft CMS version

5.3

### PHP version

8.3

### Operating system and version

Cloudways server

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just released Craft 4.12.8 and 5.4.9 with a fix.
