### ISSUE TITLE
Creating a new field with OPcache enabled breakes Craft 3

### ISSUE THREAD

**Issue by connor-baer** [craftcms/cms#1595]
### Description

I want to password-protect a few pages and thus created a new plain-text field called "Password" with the handle `password`. After hitting save, Craft logged me out and wouldn't let me log back in. The website returned a 500 status error. Had to restore from a backup to get it to work again.

I guess this happens because `password` is a reserved handle, akin to `section` or `title`. Throwing an error would be nicer than breaking Craft though. 😉 

### Steps to reproduce

1. Create a new field called "Password" with the handle `password`.
2. Hit save.

### Additional info

- Craft version: Craft 3 beta 9
- PHP version: 7.1.3
- Database driver & version: MySQL 5.7.17

**Comment by connor-baer** [comment]
Never mind, creating any kind of field has that effect on my Craft install. Will investigate further...

**Comment by brandonkelly** [comment]
@connor-baer Can you send a DB backup to support@craftcms.com ? We can investigate from there.

**Comment by connor-baer** [comment]
@brandonkelly Thanks for the offer! I found the source of the problem. OPcache is enabled on my server, running `sudo service php7.1-fpm reload` did the trick. However I need to do that every time I create a new field - kinda annoying.

I'll send you a DB backup and my logs in case you want to investigate this further.

**Comment by connor-baer** [comment]
Well that was quick. 😲🎉 Was just writing you that email...

Thank you!!

**Comment by connor-baer** [comment]
Just tried the fix and can confirm that it works. 👍

**Comment by brandonkelly** [comment]
Thanks for letting me know!
