### ISSUE TITLE
[5.x]: Nested entries edited while in a draft are auto-applied to parent entry

### ISSUE THREAD

**Issue by gateszies** [craftcms/cms#15956]
### Description
Our authors are facing a similar problem as discussed over [here](https://github.com/craftcms/cms/discussions/14603). We're using a Matrix-based page builder with nested entries displayed as cards. This has been a huge upgrade for authoring pages, but we've been running into an issue related to drafts. When authors create a draft on the page, they expect that any edits made to the page sections will be included in the memory of that draft. Instead, any edits made to the nested entries are auto-saved to the current version of the page. 
https://github.com/user-attachments/assets/eef32195-f739-4080-b442-6b05b45aa81a

### Steps to reproduce

1. Create a draft on a page
2. Edit a nested entry section
3. Go to the current version of the page and check the edited section
4. The edits made to the edited nested entry section are now applied to the current version of the page

### Expected behavior

When creating a draft on a page, the nested entry content should be tied to that page draft. The revisions should not be auto-applied to the current version of the page until the page draft is applied.

### Actual behavior

Edits made to nested entries while in a page draft are auto-applied to the current version of the page. Especially on a page that exclusively uses a page builder with nested entries, this makes the concept of a page draft non-functional.

### Craft CMS version

5.4.7.1

### Installed plugins and versions

-

**Comment by gateszies** [comment]
It seems the current advice would be to create individual drafts for each nested entry. This has a few problems - the first being that there isn't a way to create a draft in the nested entry drawer view. Our authors are primarily using the slide-out panels to edit elements on a page but the only place to create a draft is if the nested entry is opened in a new tab.
![Image](https://github.com/user-attachments/assets/19d1dbc4-ba70-4768-bd4d-c6a7e4d21bb7)

The bigger issue is the overall draft functionality on nested entries. When an author goes to edit a page with page builder content, they expect that the nested content is in the context of the overall page draft, and therefore shouldn't get applied to the current version unless the page draft is applied. I can see instances where this might not be the case, but in the context of a page builder, it's crucial to have all nested entries tied to overall page draft. 

The below shows what a typical page looks like in this context. Currently the only way to use drafts is to individually open each section in a new tab, create a draft for each, and subsequently manage and apply every draft on every section.
![Image](https://github.com/user-attachments/assets/447827da-b00b-4a85-b865-0fbe24abd2d2)

**Comment by gateszies** [comment]
I would echo an updated Matrix configuration solution proposed over [here](https://github.com/craftcms/cms/discussions/14603#discussioncomment-9544850).

>I don't think there's a single solution that will work for all use-cases. In my opinion, those two modes of operation should be an option on matrix fields, so I as a developer can decide which mode of operation I want for every matrix field. I imagine a configuration on matrix fields with two options:
> - Nested entries share their owner's life-cycle. Changes in a pop-out are saved as provisional drafts, and applied when the parent entry is saved.
> - Nested entries have their own life-cycle. Changes to nested entries are applied immediately upon saving.

**Comment by brandonkelly** [comment]
Thanks for the feedback! Made some improvements to working with nested entries (and addresses) for Craft 5.5: #16002 🎉

**Comment by brandonkelly** [comment]
Craft 5.5.0 is out with those changes 🎉

**Comment by ryanleichty** [comment]
Hey @brandonkelly, I was just testing this out right now and the latest changes in `5.5` don’t seem to work when creating an actual draft.

- If you're editing the current version of the entry, edits to nested entries are saved as drafts and published when the parent is published. Great 🚀
- If you create a new draft of the parent, edits made to nested entries are immediately published. This is the part we're trying to solve in this issue

**Comment by MoritzLost** [comment]
@ryanleichty Just gave this a try – for me it's working correctly in both situations. Do you have specific steps to reproduce this problem? I want to be sure it's working correctly before I commit to using cards mode …

**Comment by brandonkelly** [comment]
I was able to reproduce that, and just fixed it for the next release (bc047295cb58775301fcd710ee567a4a7a788f16).
