### ISSUE TITLE
[4.x]:  Unknown column 'elements.id' in 'where clause'

### ISSUE THREAD

**Issue by DowleyDeveloped** [craftcms/cms#15951]
### What happened?

When filtering by a an entry field being empty or just having a value. The filter errors with "Unknown column 'elements.id' in 'where clause'".

This does not happen if you filter by an actual entry

### Steps to reproduce

1. Run entry filters and choose an entry field as being empty/having a value. See Error

### Expected behavior

The properties should filter

### Craft CMS version

4.12.8

### PHP version

8.2

**Comment by i-just** [comment]
Hi, thanks for getting in touch! I’m not able to replicate this. Could you please enable [`safeMode`](https://craftcms.com/docs/4.x/config/general.html#safemode) and see if the issue persists? Can you share a full stack trace for this error?

**Comment by DowleyDeveloped** [comment]
Hi @i-just 

Was a plugin! Apologies

**Comment by i-just** [comment]
Glad you got to the bottom of it!
