### ISSUE TITLE
[4.x]: Action buttons in Matrix blocks have weird placement

### ISSUE THREAD

**Issue by shoored** [craftcms/cms#15965]
### Description
Action buttons in Matrix blocks have weird placement

### Steps to reproduce

1. Open an entry with a Matrix field and some blocks

### Expected behavior
Buttons are nicely aligned in the blocks' toolbar

### Actual behavior
The inherited min-height on the `.btn` class gives the `.settings` button a height of 34px instead of the defined 20px.
Also it seems the `.disabled` class is no longer present on disabled blocks, which the MatrixMate plugin relies on for spacing.

![Image](https://github.com/user-attachments/assets/64c379bd-aa05-450b-bb4c-bc3ff81eb535)

### Craft CMS version

4.12.8

### PHP version

8.2

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for the height/placement issue. 

As for the `.disabled` class, as of v4.9.4, the `.matrixblock` uses the `.disabled-entry` class to indicate disabled blocks.

**Comment by shoored** [comment]
Thanks @i-just for the quick response!
Yeah the `.disabled` class "bug" is a MatrixMate thing. Strange that I never noticed it before.

**Comment by mmikkel** [comment]
@shoored I just tagged MatrixMate v. 2.2.2 with a fix for the `.disabled` bug 🙂

**Comment by shoored** [comment]
@mmikkel Oh how great, thanks! :)

**Comment by brandonkelly** [comment]
Craft 4.12.9 is out with that fix for the Matrix button styling. Thanks again!
