### ISSUE TITLE
[4.x]: currentSite versus Control Panel

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#15971]
### Description
For a large project with multiple sites, we're running [Social Login from Verbb](https://github.com/verbb/social-login) and on anything other than the primary site that causes some issues with redirects & urls.

Here's the setup we have:
- Primary site: `project.com`
- Landing page for Belgium: `project.be`
- Site for Belgium (Dutch): `project.be/be`
- Site for Belgium (French): `project.be/fr`
- Site for France: `project.fr`
- Site for the Netherlands: `project.nl`

Our client's head office is located in Belgium so they mainly log in through project.be, where have a Microsoft Azure login button, courtesy Social Login. 

Social login will then try to get [build a redirect url](
https://github.com/verbb/social-login/blob/d5ee9648e21717a4bbb1aaa0b43e125d49363444/src/base/OAuthProvider.php#L40-L44) using the current site, but even on project.be/admin/login (which is configured as the landing page for BE), Craft sees the primary site as the `currentSite`. After logging into Azure, the user gets redirect to a different domain then were the started, causing them to not be logged in.

From the code and discord, I gather this is the intended behaviour - is there any way around this?

(we though about just making project.be the primary site, but that would still keep the "issue" for users login in on .fr and .nl domains)

### Steps to reproduce

1.

### Craft CMS version

4.12.6.1

### PHP version

8.2.24

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
> From the code and discord, I gather this is the intended behaviour - is there any way around this?

Correct. And no there’s not, sorry. You need to keep control panel traffic limited to a single domain, to avoid licensing alerts about the license being used on the wrong domain.

There’s no requirement that you stick with the primary site’s domain though. Craft will **always** set the current site to the primary site, for control panel requests, regardless of which domain/base URL you are accessing it from.

I’d recommend setting the [baseCpUrl](https://craftcms.com/docs/5.x/reference/config/general.html#basecpurl) setting to ensure all CP traffic sticks to the correct domain. Can’t speak to how that works with Social Login, though.
