### ISSUE TITLE
[5.x]: Make it possible to specify php options for queue processes

### ISSUE THREAD

**Issue by nitriques** [craftcms/cms#15975]
### Description

We process lots of data in craft's queue. We can't set the memory limit to 2G by default (in php.ini), since this limit would be shared with the web processes.

### Steps to reproduce

1. Create a queue job that requires lots of memory.
2. Run the queue and watch it failed.

### Expected behavior

I could set a env var to be included in the exec command.

`QUEUE_EXEC_ARGS='-d memory_limit=2G'`

Or we could also set a flag in the 'queue/listen' command

`php craft queue/listen --child-php-args='-d memory_limit=2G'`

Or support `--` and copy args when forking

`php craft queue/listen -- -d memory_limit=2G`

### Actual behavior

```
The command "'php' 'craft' 'queue/exec' '3829414' '300' '1' '1451441' '--verbose=1' '--color=0'" failed. Exit Code: 1(General error) Working directory: /home/intelcomweb Output: ================ 2024-10-28 09:57:30 [3829414] Freeform: Processing Notifications (attempt: 1, pid: 1451441) - Started Error Output: ================ Error: Allowed memory size of 402653184 bytes exhausted (tried to allocate 96472704 bytes)
```

LOL.
Thanks

### Craft CMS version

5

### PHP version

8.3

### Operating system and version

linux 

### Database type and version

mysql 8

### Image driver and version

-

**Comment by nitriques** [comment]
BTW, I do get a crash (bug), but this is more of a feature request... I might try to send a PR.

**Comment by brandonkelly** [comment]
> Create a queue job that requires lots of memory.

Is this for a custom queue job?

Craft 4.4.0 added `craft\queue\BaseBatchedJob`, which expensive queue jobs can extend to break the job up into multiple smaller chunks, to help avoid time and memory limits.

**Comment by nitriques** [comment]
Hey @brandonkelly 

> Is this for a custom queue job?

Not custom for _me_, but my previous example is using Freeform plugin.
Either doing extractions of many many rows or sending large files via email.

We can't be sharing the same php configs for both web and background processes.

Thanks!

**Comment by brandonkelly** [comment]
Alright, I’ll reach out to Solspace and suggest that they use `BaseBatchedJob`.

**Comment by gustavs-gutmanis** [comment]
Hi @nitriques, I'll ask the question here, even though the thread is closed.

Could you please provide some info about what your notification templates look like and the complexity of your forms?
There won't be any benefit by introducing batched jobs, because a single notification job takes care of sending a single notification and then it finishes. 
We would need to figure out what is causing so much memory to be used in this particular case.

**Comment by nitriques** [comment]
Hi @gustavs-gutmanis 

We are dealing with a high volume of responses. Daily exports can contain 10K records, with many attachments in them.

No later than this morning, we had an export notification that did not went trough. Nothing in the logs, we just do not see it.
100% looks like a php process crash tho.

We also have _many_ daily exports configured. We run the same setup on 4 different websites: The issue is always where the hi volume is. Maybe that where the batch would be nice ? Process one export per runner ? cc @brandonkelly 

My servers have plenty of RAM, being able to add more to the runner would surely fix the bugs.

**Comment by gustavs-gutmanis** [comment]
Ah I see @nitriques, so it's the export that is the problem. We will think about how to solve this issue, and get back to you.  
I was under the impression that simply sending notifications was the issue.

**Comment by nitriques** [comment]
@gustavs-gutmanis Thanks!

**Comment by nitriques** [comment]
@gustavs-gutmanis Just wanted to let you know that we still have export notifications that fails to generate/send. Still no errors in craft's log.

@brandonkelly Getting to add php directives in child runners would really help.

**Comment by gustavs-gutmanis** [comment]
Hi @nitriques 

We just did a complete revamp of how exports work, now they are way more memory efficient (with the exception of Excel export, their library has a limitation and doesn't let us write to the file line-by-line.) and your hurdles should be over.

This refactor isn't released yet, but is about to be, just wanted to let you know.

The previous functionality gathered **all** export data in memory, parsed it, and returned it as HTML content, or wrote it to file afterwards.
The new one - gathers data in chunks, it creates a temp file, and writes to it only chunk-by-chunk, and once it's done writing, it streams the file in the response, so it should take care of your memory issues.

Which export type are you using? `csv`, `json`, `excel`?

**Comment by nitriques** [comment]
> Which export type are you using? csv, json, excel?

Sadly, Excel.

**Comment by gustavs-gutmanis** [comment]
It might still solve your problem, because the data is fetched in chunks and written in chunks. So fingers crossed...

**Comment by nitriques** [comment]
@gustavs-gutmanis We will be pushing this to prod this week, will get back to you ASAP. Thanks again.
