### ISSUE TITLE
[4.x]: Control Panel -> Field Editor -> Copying a block -> Blocks can't be edited independently

### ISSUE THREAD

**Issue by mfell** [craftcms/cms#15979]
### Description

**Control Panel -> Field Editor**

Some blocks cannot be edited independently:
Adding a field in one block causes this field to appear in all other blocks, behaving as a single, linked field.

Note: I recall that I may have duplicated the block, which could be the key to reproducing or resolving this issue.

Please see the screen capture here for reference:
http://files.fell.hamburg/NeoFieldEditor.mov

If helpful, I can provide a complete backup of the entire project and database.

### Steps to reproduce

1. Duplicate a block
2. Save
3. Add a new field to the duplicated block
4. Save again
5. Observe if the new field appears in all duplicated blocks

If this doesn’t reproduce the issue, I can send my project files.

### Expected behavior

Each block should behave independently.

### Actual behavior

The blocks are linked and act as if they are connected.

### Craft CMS version

4.12.8

### PHP version

8.2

### Operating system and version

DDEV

### Database type and version

MariaDB

### Installed plugins and versions

-

**Comment by mfell** [comment]
Okay, I found the cause of this behavior in the config files: Different fields have identical IDs. This may have happened due to copying a block. But shouldn’t each field have a unique ID?

How can I fix this without losing data? Can I simply edit the config file to set unique IDs for each field?

![Image](https://github.com/user-attachments/assets/ebf6e477-beaf-4151-9e48-9dd4343b24b1)

**Comment by mfell** [comment]
I just reproduced the issue: Copying a block twice results in new blocks with identical IDs.  
The handles are individual because of the added timestamp(?).

I’m not sure if this could be an issue with Neo.

**Comment by i-just** [comment]
Hi, thanks for getting in touch! This sounds like a Neo-specific issue. Can you please raise this in the [plugin’s repo](https://github.com/spicywebau/craft-neo/issues)? 
It sounds like it might be related to [this issue](https://github.com/spicywebau/craft-neo/issues/862#issuecomment-1983612133), but I’m not 100% sure.
