### ISSUE TITLE
[5.x]: Ordering by number still not fixed when using twig queries.

### ISSUE THREAD

**Issue by leonwebcreators** [craftcms/cms#15973]
**What happened?**
When ordering by a number field, the resulted order will be:
6
32
31
30
29
[...]

**This query will result in the above wrong ordered list:**
{% set entries = craft.entries().search('keyword').orderBy('number desc').all() %}

**Ordering with another param works:**
{% set entries = craft.entries().search('keyword').orderBy('weblink desc').all() %}

**Expected behavior**
Able to order by number in Twig

**Actual behavior**
Errors as above

**Craft CMS version**
5.4.9

**PHP version**
8.3

**Operating system and version**
No response

**Database type and version**
PostgreSQL 13/14/15/16

**Image driver and version**
No response

**Installed plugins and versions**
No response

**Related errors (but this one was backend-only)**
#15417

**Comment by i-just** [comment]
Hi, thanks for reporting. I raised a PR for this.

**Comment by leonwebcreators** [comment]
You lord, are a hero. Thanks!

**Comment by brandonkelly** [comment]
Craft 5.4.10 is out with that fix. Thanks again!
