### ISSUE TITLE
[5.x]: Not able to update craft or run composer update

### ISSUE THREAD

**Issue by pnpaes** [craftcms/cms#15978]
### Description
I am not able to run composer update or php craft update all commands

### Steps to reproduce

1. If I type `composer update` in the terminal i get this error:

```
In CurlDownloader.php line 389:
                                                                                                                                        
curl error 28 while downloading https://api.github.com/repos/symfony/mime/zipball/caa1e521edb2650b8470918dfe51708c237f0598: Connection timeout after 10006 ms

```
2. If I type `php craft update all` i get this error:

```
Fetching available updates ...
Exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL error 28: SSL connection timeout (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.craftcms.com/v1/updates'

in /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:275
```

I tried to delete composer.lock and vendor folder and run `composer install` again.
Got the same error that i had with `composer update`

Any ideas?

### Craft CMS version

Craft Pro 5.4.8

### PHP version

8.3.3

### Operating system and version

Linux 6.6.32-linuxkit

### Database type and version

MariaDB 10.7.8

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

CKEditor: 4.2.0
Cookie Manager: 2.0.1
Image Resizer: 4.0.1

**Comment by pnpaes** [comment]
More details.

I am running my project inside a docker container. (I have several setup that way and have been doing that for a long time without problems).
So i ran the composer inside the docker container when I got that error.
Then I cleared the compsoer cache and tried again, then the error was different:

```
In CurlDownloader.php line 389:
                                                                                                       
curl error 28 while downloading https://composer.craftcms.com/packages.json: SSL connection timeout
```

It seems to have permissions issues access the craftcms.

Even after installing composer from outside the container, i am not able to run `php craft update` from inside the container.
I get that `SSL connection timeout`. It is not even able to fetch the available updates.

I tried the command from outside the docker container and it worked fine.
Any ideas on why this is happening?

**Comment by angrybrad** [comment]
> It seems to have permissions issues access the craftcms.

```
curl error 28 while downloading https://api.github.com/
```

Not just Craft, but even Github from your error message. Are you able to `curl` to api.github.com or anywhere else?

**Comment by pnpaes** [comment]
Hi @angrybrad 
i can curl https://api.github.com from inside my docker container without a problem.
But now I just tried to run the `php craft update/info` from inside the container and it worked.

I am currently at home, so I am wondering if there is anything being blocked at the office's connection.
I am sure we don't have any firewall blocking that, but we have a different provider than I have at home.

But on the other hand, even from the office, it worked when I tried to run from outside the container, but not from the inside.
And I could also check for updates from the utilities panel in the admin.

So i couldn't really pin point the cause for it.
Hopefully it was a temporary (weird) issue that got resolved on its own 🤷‍♂ 

But thanks for taking the time anyway.


After I test tomorrow morning, if all is working fine I can just close the issue here.

**Comment by angrybrad** [comment]
@pnpaes fair enough!

**Comment by pnpaes** [comment]
Ok, does anyone can make sense of this?

If I connect to the internet from home or from my mobile hotspot I can run the `craft update/info` from inside the docker container, from outside the docker container and I can get the updates details via browser in the utilities menu.

Now if I connect to my office wifi, i am not able to run the `craft update/info` from inside the docker container. From outside the container and via the browser it works though.
This is the error: 

```
URL error 28: SSL connection timeout for https://api.craftcms.com/v1/updates
```

 Although this is not a craftcms issue, does anyone have any idea what the issue could be here?

**Comment by angrybrad** [comment]
@pnpaes Maybe some antivirus or security/firewall software on the work network? Odd that it would only be interfering from inside a docker container, but it's all I can think of.

**Comment by pnpaes** [comment]
thanks @angrybrad .
i am sure that there is now extra security measures on the network.
and yes, odd that it is from inside the container only, and only via terminal. Maybe something with the network preferences in the container itself.
But anyway, thanks for checking. I am closing this one ;)
