### ISSUE TITLE
[5.x]: The new Linkfield is not supporting some URL's

### ISSUE THREAD

**Issue by LeoWie93** [craftcms/cms#15989]
### Description
https://www.graubündensport.ch

### Steps to reproduce

1. Fill the follwoing url in a linkfield of craft 5: https://www.graubündensport.ch
  - contains a german umlaut
  - is a 302 redirect
3. The entry can't be saved, because the url is said to be invalid

### Expected behavior
The url saves 

### Actual behavior
The entry can't be saved because the url is invalid

### Craft CMS version

5.4.9

### PHP version

8.2

### Operating system and version

Linux

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! We have [a PR](https://github.com/craftcms/cms/pull/15891) for it. I just tested it against your example, and it works as expected.

**Comment by brandonkelly** [comment]
Craft 5.5.0 is out now with that fix. Thanks again!
