### ISSUE TITLE
[5.x]: Javascript error in element index view mode

### ISSUE THREAD

**Issue by rgauthier4c4** [craftcms/cms#15984]
### Description
In one the latest Craft update, some javascript errors have broken the Element index view mode for a Matrix block. The table is not able to load his content. 

My staging environment is working fine on version 5.4.6 but it is broken on 5.4.9

### Steps to reproduce

1.  Create a matrix field with Element Index as the view mode.
2. Associated the section with this field
3. Open the section and see the javascript errors

### Expected behavior

![Image](https://github.com/user-attachments/assets/4afb3682-ff31-42e6-aa57-00a6aa38a072)

### Actual behavior

![Image](https://github.com/user-attachments/assets/7e740659-620f-4eef-b04c-61009737e720)

### Craft CMS version

5.4.9

### PHP version

8.2

### Database type and version

mysql 8

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch! I’m not able to reproduce this. Could you please turn on the [`safeMode`](https://craftcms.com/docs/5.x/reference/config/general.html#safemode) and see if the issue persists?

**Comment by rgauthier4c4** [comment]
> Hi, thanks for getting in touch! I’m not able to reproduce this. Could you please turn on the [`safeMode`](https://craftcms.com/docs/5.x/reference/config/general.html#safemode) and see if the issue persists?

Thanks you, I didn't know that the safeMode exists. It's working without the plugin.

It is the Guide plugin that breaks the field, I will contact them to check this case.

**Comment by i-just** [comment]
Cool, thanks for the update!
