### ISSUE TITLE
[5.x]: UX Issue on entry title with action buttons

### ISSUE THREAD

**Issue by JeanLucEsser** [craftcms/cms#15981]
### Description

When editing an entry, in certain circonstances when the entry title span two lines, action buttons act weirdly and change position. That is true for the French localized version where I guess button labels are not standard width. See attached clip.

### Steps to reproduce

1. Set Craft in French
2. Create an entry with a long title so it spans two lines
3. Make the auto save green check icon appear and disappear

### Expected behavior

The "more ..." action button should be on the same line as the other action buttons.
When the green check icon appears and disappears, the "save" action button should not move.

### Actual behavior

Action buttons change place every time the entry is autosaved.

https://github.com/user-attachments/assets/61173f32-2483-4fa9-9728-fb83e78e812b

### Craft CMS version

5.4.9

### PHP version

8.3

### Operating system and version

MacOS 15

### Database type and version

MySQL 8

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for pointing that out! We’ve improved the header styling for Craft 5.5 (#16001).

**Comment by brandonkelly** [comment]
Craft 5.5.0 is out now with that change 🎉
