### ISSUE TITLE
[5.x]: Matrix initial field not loaded

### ISSUE THREAD

**Issue by stephanedemotte** [craftcms/cms#15980]
### Description
Hello !
When a matrix have a one min and max entries inside another Matrix, the field is not initialized, so when the client try to save, we've got an error.

### Steps to reproduce

https://github.com/user-attachments/assets/28b85b38-7ee5-4208-a6be-473b6a3928df

### Expected behavior

Matrix should be initialized

### Actual behavior

Matrix Empty

### Craft CMS version

5.4.9

### PHP version

8.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 5.4.10 is out with a fix.
