### ISSUE TITLE
[5.x]: Short elevated session time (1 sec) blocks multi-factor auth setup

### ISSUE THREAD

**Issue by roelvanhintum** [craftcms/cms#15992]
### Description
When using a short elevated session time (for example 1 second), it is impossible to setup multi-factor auth.

### Steps to reproduce

1. Set `elevatedSessionDuration` to `1`
2. Start multi-factor auth setup
3. Login with elevated session auth popup
4. Scan QR code and enter the TOTP
5. Error pops up that elevated session is missing

### Expected behavior

After entering the TOTP i would expect another elevated session popup.

### Actual behavior

Error pops up that elevated session is missing.

### Craft CMS version

Craft Pro 5.4.9

### PHP version

8.3.12

### Operating system and version

Linux 4.4.0

### Database type and version

MySQL 8.4.3

### Image driver and version

GD 8.3.12

### Installed plugins and versions

- Amazon S3	2.2.1
- CKEditor	4.3.1
- Enforce password	3.0.0-beta.1
- ImageOptimize	5.0.3
- SendGrid	3.0.0
- Sentry SDK	3.0.0

**Comment by brandonkelly** [comment]
This is working as expected. Don’t set `elevatedSessionDuration` to one second.
