### ISSUE TITLE
[5.x]: Users multi-factor auth not possible to reset as admin or from cli

### ISSUE THREAD

**Issue by roelvanhintum** [craftcms/cms#15991]
### Description
When a user loses the multi-factor auth secret and backup codes (if they where created), it's impossible for an admin to help the user besides creating a new account. The cli has also no option for this.

### Steps to reproduce

1. Setup multi-factor auth
2. Throw away keys

### Expected behavior

I was looking for some way to help out users without messing around in the database.

### Actual behavior

-

### Craft CMS version

5.4.9

### PHP version

8.3.12

### Operating system and version

Linux 4.4.0

### Database type and version

MySQL 8.4.3

### Image driver and version

GD 8.3.12

### Installed plugins and versions

- Amazon S3	2.2.1
- CKEditor	4.3.1
- Enforce password	3.0.0-beta.1
- ImageOptimize	5.0.3
- SendGrid	3.0.0
- Sentry SDK	3.0.0

**Comment by i-just** [comment]
Hi, thanks for getting in touch! We’ll discuss this internally. 

For now, if you have sufficient privileges, you can log in as that user and turn off 2SV by going to their account page > Password & Verification.

**Comment by brandonkelly** [comment]
Craft 5.5.0 is out now with a new `users/remove-2fa` CLI command that can also help with this (#16053).
