### ISSUE TITLE
[5.x]: "The draft could not be saved" error when attempting to delete a nested entry, if the entry type is no longer available in the Matrix field

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#15990]
### Description

After removing an entry type from a Matrix field, attempting to delete any existing nested entries that use the removed entry type becomes impossible due to an error "The draft could not be saved. - Element 194 could not be duplicated because it doesn't validate.":

![Image](https://github.com/user-attachments/assets/5a1eec8d-250b-4d65-b179-2c7d25455ff9)

_This only happens if the Matrix field is using the "Cards" or "Element Index" view modes._

The workaround is to first change the entry type for the affected nested entries to one of the available ones and _then_ delete them, but this feels convoluted.

### Steps to reproduce

1. Create a Matrix field and add a couple of entry types to it. Use the "Cards" view mode.
2. Create a nested entry in the Matrix field.
3. Go into the Matrix field settings and remove the entry type that was used for the newly created nested entry.
4. Go back to the owner entry, and try to delete the nested entry via the Delete action in the nested entry's actions disclosure menu.
5. Observe that the nested entry is not deleted, the owner entry draft is not saved, and that an error "The draft could not be saved." appears via the revision status alert at the top of the edit page.

### Expected behavior

Deleting nested entries whose entry type is no longer available in a Matrix field should be possible, regardless of the field's view mode.

### Actual behavior

Deleting nested entries whose entry type has been removed from their Matrix field is not possible, preventing the owner entry from being saved.

### Craft CMS version

5.4.9

### Installed plugins and versions

None

**Comment by i-just** [comment]
Hi, thanks for reporting and clear replication steps! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.4.10 is out with that fix. Thanks again!
