### ISSUE TITLE
dot-env not present, thus not working, on upgrade-Craft 3 site until modded in

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1599]
### Description
Trying  to use .env on a my long-term-upgraded Craft test and plugin-conversions site, I couldn't -- it wasnt being seen. 

Turns out I had to manually require dot-env in Composer.

I actually just added it to the composer.json and copied in the check-and-run code from a composer-project-installed web/index.php to my public/index.php, right before the autoload.

Now .env works fine, allowing me to set for example ASSETS_BASE_PATH/_URL values.

Extra credit, but necessary information:  You may well question where I got this site from, as I no longer well remember myself, given there were some fairly break-with-past Craft 3 releases following hiatuses while you guys beavered away. So I drug out Git Gui, and thus gitk, and had a squint at old git log info, down into the past, which extends well down into the originating Craft 2 site, since the .git folder was copied over with the rest. 

It does appear that it was originally intentionally converted in May last year, from a copy of a Craft 2 original having a fair number of moving parts; why I chose it. I believe it's been dutifully upgraded per Craft 3 emanations ever since, pretty much as soon as  you released them. I hope you still convert suitable Craft 2-version sites, and I may have a fuzzy memory of possibly re-converting this one at some point where things changed too much, but it is still I actually feel a C2-converted rather than re-entered-in-C3 creation. Certainty less than 100% on that, though.

In any case, it is a conversion at the point of the last few month's re-release and ongoing sprint on Craft 3, and not a fresh Composer project install. 

Just what that means in terms of this issue  and other critical differences I've been finding and reporting, I think you'll have to reckon. I will as much as can help -- just ask. This latest missing dot-env package and index.php call is a good example case.

Cheers, C.

### Steps to reproduce

1. As above
2.

### Additional info

- Craft version: beta 9, latest of the moment dev-develop composer updated
PHP version	7.1.2-4+deb.sury.org~xenial+1
Database driver & version	MySQL 5.7.17-0ubuntu0.16.04.1
Image driver & version	GD 7.1.2-4+deb.sury.org~xenial+1
Craft edition & version	Craft Personal 3.0.0-beta.9
Yii version	2.0.11.2
Twig version	2.1.0
Guzzle version	6.2.1
Imagine version	0.7-dev
Plugins

Trimmer	1.0.0
Bactrian	1.0.0
Standards Agent	2.0.4

**Comment by brandonkelly** [comment]
Yeah Craft’s dotenv support is limited to the `craftcms/craft` Composer project, so if you want to add it to an existing Craft site, it’s up to you to do all the things.

Here’s a guide that will walk you through setting up dotenv for Craft 2, which is 99% relevant to Craft 3 as well (you just need to make sure the paths match your own project, which again, are just a per-project configuration thing).

https://mattstauffer.co/blog/environment-specific-configuration-for-craftcms-using-phpdotenv

**Comment by narration-sd** [comment]
Ok, fair enough, but again, probably lost in the history explanation, I was querying this about nowadays conversion of Craft 2n-> Craft 3 sites.

Do you intend to convert sites this way now? Or are people supposed to start a site completely fresh for Craft 3? Daunting, if it has a lot of database data. Of course plugins etc. need conversion.

If you do indeed intend to up-convert Craft 2 sites, things like this dot-env insertion I think will turn out to be important, no?

**Comment by narration-sd** [comment]
You know, I had another thought about this. The reply hinted the issue was just skimmed, so I think I'm helping overload, which is the reverse of my intention. One truth out of what you say, though, is that this app with history isn't relevant to needs now, due to the revised Craft 3 upgrade pattern, which I just found and reread.

I think my issue here may yet be relevant, but I will simply prove it if so. I'll do a fresh 2->3 conversion, and see what I get -- it will for practical purposes be the same site, so we can see if this or other issues raised remain. Machine is in backup now, and anyway a rest from such, so I'll let you know when I do it.

Cheers, Brandon,
Clive

**Comment by narration-sd** [comment]
Ok, I got second wind in late hours, and pieced this together.

- I have a fresh late craft 2 project sset up and running in a fresh vm
- I followed the simple docs upgrade.md instructions
- but failed out on the first composer require of craftcms/cms -- reason, that  bower-asset/d3 4.6.0.0 is required, but packagist doesn't appear to have it davailable at the moment;

Really though, Brandon, the answer to this issue is simple and clear, no? 

Since the requires and edits are all done manually anyway,
- change the doc, no coding needed
- add a composer require step, for vlucas/phpdotenv after the cms and plugin-installer
- add a step to put the lines that call dotenv into the index.php, after or with your present mods there.

This is all I did anyway to get this working, and it does on my historic site.  It will on the new one also, as soon as I can get composer to install Craft.

Do you want me to enter this as a doc isssue, or will you just pick it up from here?

**Comment by narration-sd** [comment]
Hey, Brandon -- thanks for whatever you did as Composer is succeeding this morning, right now bower chunks and all the other things busily coming down.

I'm going to remove  notes above; just a long day, and I iwll write a doc issue/upgrade for the point here, as a good conclusion to the  questions here. 

As far as Matt Stauffer's site commentaries, I use those often enough, and not too much thinking about adding dot-env to Craft 2 here, but as ever, his is a good link for that, thanks.

Ok, craft even dev-develop nicely installed, also  phpdotenv, matters looking good...

**Comment by narration-sd** [comment]
Ok, have done this and a  little more, from actuality, in docs/issues [#11](https://github.com/craftcms/docs/issues/11),  [#12](https://github.com/craftcms/docs/issues/12),  [#13](https://github.com/craftcms/docs/issues/13)  -- links work.

Cheers, Brandon, sunny afternoon,
Clive
