### ISSUE TITLE
[5.x]: Can't export any entries after entry 100

### ISSUE THREAD

**Issue by LuukRM2000** [craftcms/cms#15996]
### Description
When exporting entries after entry 100 I get empty csv files.

### Steps to reproduce

1. Populate more then 100 orders (In my case I need to export a order in commerce). 
2. Then try to export a entry after entry 100.

### Expected behavior

A populated csv file

### Actual behavior
A empty csv file

### Craft CMS version

5.4.9 // commerce 5.2.1

### PHP version

8.2.8

### Operating system and version

macOS Version 15.1 (24B83) // MacBook air m2

### Database type and version

MySQL 8.0.40

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.1-13)

### Installed plugins and versions

- commerce 5.2.1

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.4.10 is out with that fix. Thanks again!
