### ISSUE TITLE
Craft does not re-render template with different query params when OPcache is enabled

### ISSUE THREAD

**Issue by connor-baer** [craftcms/cms#1600]
### Description

I am trying to implement password-protection for pages according to this [StackOverflow answer](https://craftcms.stackexchange.com/questions/8360/protect-a-page-with-a-single-password#answer-10994): The page gets loaded and since no password has been provided, the user is asked for one. The password is submitted to Craft as a query param. If the submitted password matches the password that's been set for the page, Craft renders the page content.

This works perfectly on my local vagrant/homestead setup, but not in production. Craft always returns the page the way it was first requested. The culprit is OPcache ([again](https://github.com/craftcms/cms/issues/1595)). Turning it off removes the issue.

### Steps to reproduce

1. Enable OPcache on the server.
2. Built a page template that dynamically changes based on the query params.
3. Submit a page without and then with some query params.
4. Craft will render the page the page the way it was first requested. It ignores the new query params.

### Additional info

- Craft version: Craft 3 beta 9
- PHP version: 7.1.3
- Database driver & version: MySQL 5.7.17
- Plugins & versions: at their latest: Minify, Cookies, Recipe, Mailgun, Twitter, ImageOptim, Asset Rev

**Comment by connor-baer** [comment]
Never mind ([again](https://github.com/craftcms/cms/issues/1595#issuecomment-291882000)) 😳🙈

It wasn't OPcache (turning it off did in fact _not_ fix it). It was me. I had the entire page wrapped in `{% cache %}` tags. Stupid, stupid me. 😬

**Comment by brandonkelly** [comment]
Haha, no worries :)
