### ISSUE TITLE
[5.x]: GraphQL token is shown as to never expire when expiry date is set.

### ISSUE THREAD

**Issue by kbergha** [craftcms/cms#16029]
### Description

GraphQL tokens is shown as "Expires - Never" in the overview of all token, even tough a date+time is set on the token.

![Image](https://github.com/user-attachments/assets/e5d9e6dd-2c00-441e-a581-132bf71d3582)
![Image](https://github.com/user-attachments/assets/e828ee55-c597-43ba-87c4-021198be526b)

### Steps to reproduce

1. Add a token with an expiry date/time.
2. Go to the GraphQL Tokens / overview page.

### Expected behavior

List should show the set expiry date/time.

### Actual behavior

List shows "Never" for expiry.

### Craft CMS version

5.4.8

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 4.12.9 and 5.4.10 are out with that fix. Thanks again!
