### ISSUE TITLE
[5.x]: Can't adjust order of variants when more than 50 variants

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#16026]
### Description
We’re experiencing an issue with reordering product variants when a product has more than 50 variants. 

Initially, the order can be adjusted successfully, but after the save the variant is back at the initial place. 

This is before a save: 
After successfully reordering once, attempting to reorder a second time fails. During the second attempt, the variant item cannot be dragged as expected; instead, only the icons are selectable, and dragging is unresponsive.
![Image](https://github.com/user-attachments/assets/040e6c44-37e3-488b-b1f7-a5cadac7ffb1)

### Steps to Reproduce

1. Create a product.
2. Add more than 50 variants to the product (e.g., 55 variants).
3. Reorder the variants.
4. Attempt to reorder the variants a second time, without refreshing the page.
5. Save the page

### Expected Behavior

- The variant should be at the position it’s dragged to after the save.
- Reordering should work consistently, allowing users to adjust the order multiple times without needing to refresh the page.

### Actual Behavior

- After the save the variant reverts to its original position.
- Subsequent reordering fails unless the page is refreshed.

### Craft CMS version

5.3.4

### Craft Commerce version

5.0.16.1

### PHP version

8.3.8

**Comment by WHITE-developer** [comment]
Some extra info, 

The reordering feature occasionally fails for products with fewer than 50 variants.

Example:

For a product with 13 variants, when attempting to reorder, the system displays the message "New positions saved."
However, after saving, the reordered variant reverts to its original position.
For products with more than 50 variants, the "New positions saved" message does not appear at all.
![Image](https://github.com/user-attachments/assets/5fb08e78-a7fc-48b8-b1f9-fd41ca5cffd7)
![Image](https://github.com/user-attachments/assets/e8952b45-7723-42ad-89e1-6e6085ae23bc)

**Comment by nfourtythree** [comment]
Hi @WHITE-developer 

Thank you for the feedback, I have also managed to replicate this issue with a matrix field using element index mode on an entry.

The issue has been transferred to Craft CMS repositroy for further investigation.

Thanks!

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.4.10 is out with that fix. Thanks again!

**Comment by WHITE-developer** [comment]
Thanks @i-just and @brandonkelly for the quick fix, it looks good!
