### ISSUE TITLE
Client cannot access image edit tool

### ISSUE THREAD

**Issue by jolora** [craftcms/cms#1602]
### Description

A client account does not have the same abilities for managing assets as the developer account. Is this expected behaviour or a bug?

**What the dev account sees:**
<img width="201" alt="screen shot 2017-04-06 at 13 20 47" src="https://cloud.githubusercontent.com/assets/4901960/24753882/188387da-1acc-11e7-8228-145d597e1f49.png">

**What the client account sees:**
<img width="208" alt="screen shot 2017-04-06 at 16 07 38" src="https://cloud.githubusercontent.com/assets/4901960/24761420/31759550-1ae3-11e7-8eca-94d701ecab25.png">

### Additional info

PHP version	7.1.2-3+deb.sury.org xenial+1
Database driver & version	MySQL 5.7.17-0ubuntu0.16.04.1
Image driver & version	GD 7.1.2-3+deb.sury.org~xenial+1
Craft edition & version	Craft Client 3.0.0-beta.9
Yii version	2.0.11.2
Twig version	2.1.0
Guzzle version	6.2.1
Imagine version	0.7-dev

Server passes all requirement checks
No plugins installed

**Comment by brandonkelly** [comment]
@laurabennett Yep, it was fixed in 3.0.0-RC1.

For a user to have access to the Image Editor, they will need both the “Upload files” and “Remove files and folders” permissions.
