### ISSUE TITLE
[5.x]: Applying project config with a new site addition (multisite) fails on environments with schema access disabled

### ISSUE THREAD

**Issue by justinholtweb** [craftcms/cms#16044]
### Description
We have a site where we have added a new site (multisite) and have failures applying the project config on remote environments where the schema mutation is disabled. It appears that Craft is trying to mutate the site yaml file for the new site when applying, but it is not clear what it is actually changing. I have recreated this behavior locally, and when then allowing schema mutation and letting it run successfully, no actual changes appear in Project Config files in the repo. 

### Steps to reproduce

1. Add a new site, using ENV variables for the site URL values.
2. Apply the project config on an environment with schema access disabled.
3. See the failure.

### Expected behavior
Project Config will apply and create the new site on the remote environment. 

### Actual behavior
The application of the project config schema fails when trying to apply the new site. The error is the generic "error: Changes to the project config are not possible while in read-only mode." Screenshots are attached of the error and of the file for that site in project config. 

Notes:
As mentioned I was able to recreate this locally when my local schema access is disabled and when matching my local DB to the remote (pre-migration). The site is hosted on Servd and this causes a fatal error that pollutes the sites project config, requiring a backup application to restore the site. ![Image](https://github.com/user-attachments/assets/da9737e8-030c-4a4c-bfcd-0354ba8a35a9)
![Image](https://github.com/user-attachments/assets/3d0a16ce-9399-4745-9642-21f3d7dcec89)

### Craft CMS version

Craft Pro 5.4.10

### PHP version

8.3.8

### Database type and version

SQL 8.0.36

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

**Comment by i-just** [comment]
Hi, thanks for reaching out! I’m not able to replicate this on a fresh installation. Would you be able to send your remote (pre-migration) database export and `composer.json`, `composer.lock` and `config/project` folder from your local to support@craftcms.com so we can try to replicate and dig deeper?

**Comment by justinholtweb** [comment]
Just emailed with the assets requested and referencing this issue ID. Thanks!

**Comment by justinholtweb** [comment]
We ended up solving this by doing some stepped commits with different changes to the repo. We can close for now and if we run into this again we will start a new issue. Thanks for your investigation efforts!
