### ISSUE TITLE
[5.4.10]: Matrix field in Globals section no longer works after updating to 5.4.10 version

### ISSUE THREAD

**Issue by giacomocarra** [craftcms/cms#16041]
### Description
Matrix field in Globals section no longer works after updating to 5.4.10 version

### Steps to reproduce

1. Add a matrix field to the Globals section;
2. Update Craft to version 5.4.10;
3. Try adding a new Matrix block in the Globals section.

### Expected behavior
Create a new empty matrix block

### Actual behavior
Clicking on the drop down menu does not happen anything

### Craft CMS version

5.4.10

### PHP version

8.2.24

### Operating system and version

Linux 5.10.0-31-cloud-amd64

### Database type and version

MariaDB 10.6.19

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

CKEditor	4.3.1
Postmark	3.1.0

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just released Craft 5.4.10.1 with a fix.
