### ISSUE TITLE
[5.4.10]: Upgrading from Craft 4 to Craft 5.4.10 deletes field content

### ISSUE THREAD

**Issue by DowleyDeveloped** [craftcms/cms#16042]
### What happened?

I have a site with several plain text fields. When upgrading from Craft 4 to 5.4.10 all these fields were removed.

This doesn't happen if I upgrade to 5.4.9

### Steps to reproduce

1. Create an entry with plain text fields
2. Upgrade to Craft 5
3. Field are now empty

### Expected behavior
Fields should contain content

### Craft CMS version

5.4.10

### PHP version

8.3

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Any chance you can share your Craft 4 database, and new Craft 5 Composer files with us? Please send them to support@craftcms.com if so.

**Comment by DowleyDeveloped** [comment]
@brandonkelly Sent!

**Comment by olivierbon** [comment]
Running `php craft project-config/rebuild` before running the update fixed the issue.
