### ISSUE TITLE
[4.x]: Safe to remove deleted matrix blocks?

### ISSUE THREAD

**Issue by markhuot** [craftcms/cms#16054]
### Description

I have a site with (currently) 15M elements. Of those 15M, 4.9M of them are deleted matrix blocks. Most of them are probably from long ago when we migrated in to Craft and moved 1M articles over from an old system in to Craft. That migration took a few runs and we probably created a number of matrix block orphans with repeated saves/updates.

So, the question is then… can we blindly delete those rows with something like this?

```sql
DELETE FROM craft_elements WHERE type='craft\\elements\\MatrixBlock' and dateDeleted is not null;
```

We are running `craft gc` to purge any deleted entries so those deleted matrix blocks _shouldn't_ be tied to anything.

Context: we're trying to shrink the database before upgrading to Craft 5 because the content migration is crashing after a few hours of churn.

### Steps to reproduce

1. Import a massive amount of data
2. Repeatedly update the data by overwriting matrix fields
3. End up with a bunch of old/deleted matrix blocks from previous versions of the entries

### Expected behavior

n/a

### Actual behavior

n/a

### Craft CMS version

4.3.10

### PHP version

8.3

### Operating system and version

Amazon Linux 2

### Database type and version

MySQL 8

### Image driver and version

n/a

### Installed plugins and versions

None of note.

**Comment by brandonkelly** [comment]
That would be safe to run, sure. You could also run `craft gc --delete-all-trashed`.
