### ISSUE TITLE
[5.x]: Restoring an Entry also restores nested Elements from prior versions

### ISSUE THREAD

**Issue by ryansupercool** [craftcms/cms#16059]
### Description

When deleting and then restoring an Entry with a Matrix field, blocks from previous versions are also restored.

### Steps to reproduce

1. Add a block (Block A) to a Matrix field and save.
2. Add another block (Block B) and save.
3. Delete Block B and save.
4. Delete the Entry.
5. Restore the Entry.

https://github.com/user-attachments/assets/1e450b01-ac8b-4e1d-a7da-e45c3f737660

### Expected behavior

Only Block A should be present in the restored Entry.

### Actual behavior

Only Block B is also restored when restoring the Entry.

Note this is in Craft the unreleased Craft 5.5, I'm not sure if this is expected or if something has changed from Craft 4 where only content from the latest revision would be restored.

### Craft CMS version

5.5

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! I’ve fixed it for the next release. Unfortunately it won’t be fixed for any parent entries that were already deleted, though.

**Comment by brandonkelly** [comment]
Craft 5.5.0 is out with that fix. Thanks again!
