### ISSUE TITLE
Reset Password - preventUserEnumeration stops blank entry error

### ISSUE THREAD

**Issue by davidteal** [craftcms/cms#1605]
### Description
When resetting a password, preventUserEnumeration config prevents the "Username or email is required." error being shown. I would have thought this error should be shown regardless of the preventUserEnumeration setting and gives a better UX. "The Invalid username or email." and "There was a problem sending the password reset email." errors should obviously still be suppressed.

### Steps to reproduce

1. Add 'preventUserEnumeration' => true to general.php config
2. Reset password with an empty email address field.
3. Password reset email sent notice appears on the redirected to page.

### Additional info

- Craft version: 2.6.2968

**Comment by brandonkelly** [comment]
It’s not even possible to submit the form until you’ve entered a username or email address:

> <img src='https://shipusercontent.com/254e2a02d38f1f27de02099a14589dd5/Screen%20Shot%202017-04-07%20at%203.37.06%20PM.png' title='Screen Shot 2017-04-07 at 3.37.06 PM.png' width=332>

Am I missing something?

**Comment by davidteal** [comment]
Apologies, should have been clearer. This is when resetting the password from the front end using this form: https://craftcms.com/docs/templating/forgot-password-form
