### ISSUE TITLE
Commerce - Breakpoint issue

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#1606]
- Craft 2.6.2968
 - Commerce 1.2.1337
 - Chrome (don't know which version)

---

My client is seeing a weird issue with Variants. He says it can be corrected by adjusting the size of his screen. I'm unable to reproduce it on my machine.

I've attached his screenshots...

![before](https://cloud.githubusercontent.com/assets/5309692/24821576/3f362aee-1ba4-11e7-9078-732696472584.png)

![after](https://cloud.githubusercontent.com/assets/5309692/24821580/43768504-1ba4-11e7-8781-7a61d8127e54.png)

![after firefox](https://cloud.githubusercontent.com/assets/5309692/24821583/47bc9dd8-1ba4-11e7-9b07-42404eb0d5d3.png)

And here are his complete messages on the subject...

>_"When you're viewing workshops on the admin side, you can collapse the variants, which makes viewing the page much easier to scroll through.  When you expand them again, the layout of all the elements is jumbled and certain elements are missing."_

>_"I just realized it's due to my screen size!  I zoomed out & the layout changed, which cleared up the issue!  I also tried it on a different computer & it worked fine.  I use a 13" mbp."_

If you guys can figure out what's going on there, great! If not, just let me know.

Thanks! :)

**Comment by brandonkelly** [comment]
Closing this because it's not a Craft CMS bug. (Commerce bugs should still go to support@craftcommerce.com.) We’ll follow up with you via email.

**Comment by lindseydiloreto** [comment]
Sounds good, thanks Brandon!
