### ISSUE TITLE
[5.x]: https://api.craftcms.com/v1/plugin/index.php/reviews?v=1731319234910 404 (Not Found)ye {message: 'Request failed with status code 404', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}code: "ERR_BAD_REQ

### ISSUE THREAD

**Issue by abhitest** [craftcms/cms#16075]
### Description
unable to get plugins 

### Steps to reproduce

1.       GET https://api.craftcms.com/v1/plugin/index.php/reviews?v=1731319500437 

### Expected behavior
get plugin

### Actual behavior

didnt got plugins
### Craft CMS version

5.4.10.1 (Solo)

### PHP version

8.2.24

### Operating system and version

Linux 5.15.153.1-microsoft-standard-WSL2

### Database type and version

MySQL 8.0.36

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

**Comment by brandonkelly** [comment]
The in-app Plugin Store is working for me. Are you still getting an error?

**Comment by abhitest** [comment]
yes i am still facing the issue .
here is the error i get while opening the plugin 
![Image](https://github.com/user-attachments/assets/fa265f92-ec3d-4a8e-abda-a798da885eb0)

**Comment by brandonkelly** [comment]
Are you behind a firewall that could be blocking the request?

**Comment by brandonkelly** [comment]
You can try tethering from your phone, or from a different location, and see if that helps.

**Comment by AugustMiller** [comment]
I can reproduce this if I manually visit a path like `/admin/plugin-store/index.php`. Not sure why the store itself would generate a URL like this, though! :(

**Comment by mofman** [comment]
This is also happening for us too on wifi and tethering.

**Comment by mofman** [comment]
Seems to be resolved now

**Comment by abhitest** [comment]
Seems to be resolved now

**Comment by abhitest** [comment]
thank you
