### ISSUE TITLE
[4.x]: Scheduled publishing of Drafts does not get published

### ISSUE THREAD

**Issue by patrikalienus** [craftcms/cms#16072]
### Description
A published entry with a Draft scheduled to be published at X time, does not get published.

### Steps to reproduce
1. Create an entry and publish it.
2. Create a draft and set it to get published at X date/time
3. Time has passed, Draft remains unpublished

### Expected behavior
Draft should get published.

### Actual behavior
Draft doesn't get published  
Publishing an entry on a schedule where no revision is published at all (i.e. the entry isn't published at all), works as expected so I know the problem isn't Cron-related. I have also made sure that the server time is correct.

### Craft CMS version

4.12.8

### PHP version

8.2

### Operating system and version

Linux 6.10.0-linuxkit

### Database type and version

PostgreSQL 13.15

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- Azure Blob Storage | 2.1.0
- CKEditor 3.10.0
- Element API 4.1.0
- Inventory 3.2.0
- Navigation 2.1.1
- Neo 4.2.18
- Published X 3.0.1
- Translations 4.0.2

**Comment by i-just** [comment]
Hi @patrikalienus, it sounds like an issue with the Published X plugin. Please raise it with the [plugin’s developers](https://github.com/Goldinteractive/craft-publisher/issues).

**Comment by patrikalienus** [comment]
> Hi [@patrikalienus](https://github.com/patrikalienus), it sounds like an issue with the Published X plugin. Please raise it with the [plugin’s developers](https://github.com/Goldinteractive/craft-publisher/issues).

Oh I see, my bad. I didn't know this was a publisher X feature as I recently took over this project. Thanks.
