### ISSUE TITLE
[5.x]: `fillGapsInElements` not getting all elements

### ISSUE THREAD

**Issue by white-lukas** [craftcms/cms#16085]
### Description
When trying to get all structure elements from an array of elements, The [`fillGapsInElements`](https://github.com/craftcms/cms/blob/5.x/src/services/Structures.php#L152) is not returning all elements from the structure, it's depending on the sort order of the given elements.

Example:
when passing in 2 elements into the function with the following structure:
1. fietsen/heren/starters-racefiets/starters-racefiets
2. fietsen/racefietsen/starters-racefiets

The `lft` value of the first element is `117`, the second `14`

When passing the elements in this order the returned array is missing the `fietsen/racefietsen` entry.

When I would change the order of the passed in elements the `fietsen/racefietsen` entry is returned as well

### Craft CMS version

5.4.10.1

### PHP version

8.3.13

### Operating system and version

Ubuntu 24.04

### Database type and version

mysql 8.0

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out. Let me first double check if I understand this correctly. Your structure looks something like that:
-- racefietsen
------ starters racefiets
-- heren
------ starters racefiets
---------- starters racefiets

And you're saying that if you pass `[<heren/starters-racefiets/starters-racefiets>, <racefietsen/starters-racefiets>]` to the `fillGapsInElements()`, you get back 4 of the above mentioned elements:
- heren
- heren/starters-racefiets
- heren/starters-racefiets/starters-racefiets
- racefietsen/starters-racefiets

And if you flip the order and pass `[<racefietsen/starters-racefiets>, <heren/starters-racefiets/starters-racefiets>]`, you get back all 5 of the above mentioned elements:
- racefietsen
- racefietsen/starters-racefiets
- heren
- heren/starters-racefiets
- heren/starters-racefiets/starters-racefiets

Is that correct?

**Comment by white-lukas** [comment]
complete structure is

![Image](https://github.com/user-attachments/assets/f943f24f-1d18-41d5-83f8-38073dfce567)

When passing in `[<heren/starters-racefiets/starters-racefiets>, <racefietsen/starters-racefiets>]` I miss the `fietsen/racefietsen` category, as then [this](https://github.com/craftcms/cms/blob/5.x/src/services/Structures.php#L172) is getting added and filters out the lower `lft` value of the `racefietsen/starters-racefiets` entry

**Comment by i-just** [comment]
Thanks for confirming. I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 4.13.3 and 5.5.1 are out with that fix. Thanks again!
