### ISSUE TITLE
[5.x]: Upgrading from 4 to 5 loses all content in text fields

### ISSUE THREAD

**Issue by idleog** [craftcms/cms#16089]
### Description
I am upgrading a project from 4 to 5 and the content of all text fields (except titles) and CKEditor fields are lost.
The CKEditor fields have been converted from Redactor in 4.12.9 with no problem. 

### Steps to reproduce

1. upgrade from 4.12.9 to 5.4.10.1

### Expected behavior
go smooth

### Actual behavior
does not go smooth

### Craft CMS version

5.4.10.1 (upgrading from 4.12.9)

### PHP version

8.3.13

### Operating system and version

Linux 3.10.0-1160.92.1.el7.x86_64

### Database type and version

MariaDB 10.6.18

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.10-68)

### Installed plugins and versions

"craftcms/ckeditor": "4.3.1",
    "doublesecretagency/craft-cpbodyclasses": "3.0.0",
    "doublesecretagency/craft-cpcss": "3.0.0",
    "doublesecretagency/craft-siteswitcher": "3.0.0",
    "idleog/craft-goeldi": "^5.0",
    "nystudio107/craft-cookies": "5.0.0",
    "topshelfcraft/wordsmith": "5.0.0",
    "vaersaagod/seomate": "3.1.1",
    "verbb/cloner": "3.0.1"

**Comment by i-just** [comment]
Hi, thanks for reaching out! It sounds a lot like https://github.com/craftcms/cms/issues/16042. Did you run the `php craft project-config/rebuild` before running the update as per step 3 [here](https://craftcms.com/docs/5.x/upgrade.html#performing-the-upgrade)?

**Comment by idleog** [comment]
Hi, I have to admit that I _think_ I did run the rebuild, but I am not sure. I will try again with the rebuild and come back here to let you know.
Cheers
Peter

**Comment by idleog** [comment]
ok, I did the whole procedure again, exactly how it is described here: https://craftcms.com/docs/5.x/upgrade.html

Here what happens: on my local environment all went as expected and correct on local environmet. But when I deploy the  changes (config, composer.json and some template adjustments) to the live environment and after running `composer update` and `craft up` there, all ckeditor fields within entry types used by matrix blocks lose their content. all other fields are ok. 

In don't know if this was correct: I installed ckeditor plugin on live environment and run `craft ckeditor/convert/redactor` on craftcms 4.12.13 _before_ I deployed the changes and run `composer update` and `craft up`

it seems that sth. is buggy

**Comment by i-just** [comment]
Thanks for the additional info!

> In don't know if this was correct: I installed ckeditor plugin on live environment and run craft ckeditor/convert/redactor on craftcms 4.12.13 before I deployed the changes and run composer update and craft up

Can you please clarify this bit? Are you saying you updated the site locally, then ran `craft ckeditor/convert/redactor ` on the live environment, and then deployed the changes from local?

**Comment by idleog** [comment]
First I installed CKEditor and ran craft ckeditor/convert/redactor (on Craft4) and updated the system to craft 5 locally.
Then I installed CKEditor and ran craft ckeditor/convert/redactor on live system (on Craft4)
Then I deployed and updated to Craft5 on live environment.

**Comment by i-just** [comment]
Ah, so that’s the problem then. Your live and local environments have to be in sync before you do the upgrade (that’s what steps 1-3 are about). Making changes separately on production and locally while performing the upgrade is not going to give the expected results. Ideally, you’d want to:
- First, run the `ckeditor/convert/redactor` command, deploy those changes and then upgrade to Craft 5 (as per the guide) and deploy those changes.
- First, upgrade to Craft 5 (as per the guide), deploy those changes, and then run the `ckeditor/convert/redactor` command and deploy those changes.

I'll close this now, but feel free to reply if you run into any further issues.

**Comment by idleog** [comment]
Thanks! 

Just one question: if I run the convert command for redactor fields, upgrade to craft5 and deploy then: do the redactor fields on the live system then automaticaly recognize that they are converted to ckeditor fields and keep their content without running the convert command? 

Just to be sure.

**Comment by idleog** [comment]
OK, I got it, everything worked now. Thanks for ypour help

**Comment by i-just** [comment]
Not a problem! Glad it’s all working as expected now.
