### ISSUE TITLE
[5.x]: Failed update from 4 to 5: failed to apply m230511_000000_field_layout_configs

### ISSUE THREAD

**Issue by mathieuser** [craftcms/cms#16096]
### Description
When following the guide to upgrade craft 4 to 5, the update fails with error 'failed to apply m230511_000000_field_layout_configs'. 
I've run garbage collection and rebuild project-config beforehand.

Stacktrace for reference:
`*** applying m230511_000000_field_layout_configs
Exception: Class "craft\elements\MatrixBlock" not found (/var/www/html/vendor/craftcms/cms/src/models/FieldLayout.php:270)
#0 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\models\FieldLayout->init()
#1 /var/www/html/vendor/craftcms/cms/src/base/Model.php(87): yii\base\BaseObject->__construct()
#2 [internal function]: craft\base\Model->__construct(Array)
#3 /var/www/html/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#4 /var/www/html/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\models\\Fi...', Array, Array)
#5 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\models\\Fi...', Array, Array)
#6 /var/www/html/vendor/craftcms/cms/src/Craft.php(70): yii\BaseYii::createObject(Array, Array)
#7 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(1069): Craft::createObject(Array)
#8 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(904): craft\services\Fields->createLayout(Array)
#9 [internal function]: craft\services\Fields->craft\services\{closure}(Array, 7)
#10 /var/www/html/vendor/craftcms/cms/src/base/MemoizableArray.php(90): call_user_func(Object(Closure), Array, 7)
#11 /var/www/html/vendor/craftcms/cms/src/base/MemoizableArray.php(76): craft\base\MemoizableArray->normalizeByKey(7)
#12 [internal function]: craft\base\MemoizableArray->craft\base\{closure}(7)
#13 /var/www/html/vendor/craftcms/cms/src/base/MemoizableArray.php(76): array_map(Object(Closure), Array)
#14 /var/www/html/vendor/craftcms/cms/src/base/MemoizableArray.php(104): craft\base\MemoizableArray->normalize(Array)
#15 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(996): craft\base\MemoizableArray->all()
#16 /var/www/html/vendor/craftcms/cms/src/migrations/m230511_000000_field_layout_configs.php(25): craft\services\Fields->getAllLayouts()
#17 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(50): craft\migrations\m230511_000000_field_layout_configs->safeUp()
#18 /var/www/html/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#19 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(382): yii\console\controllers\BaseMigrateController->migrateUp('m230511_000000_...')
#20 [internal function]: craft\console\controllers\MigrateController->actionAll()
#21 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#22 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#23 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
#24 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(195): yii\console\Controller->runAction('all', Array)
#25 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction('all', Array)
#26 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#27 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('migrate/all', Array)
#28 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(212): craft\console\Application->runAction('migrate/all', Array)
#29 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(207): yii\base\Controller->run('migrate/all', Array)
#30 /var/www/html/vendor/craftcms/cms/src/console/controllers/UpController.php(60): craft\console\Controller->run('migrate/all', Array)
#31 [internal function]: craft\console\controllers\UpController->actionIndex()
#32 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#33 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#34 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('', Array)
#35 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(88): yii\console\Controller->runAction('', Array)
#36 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction('', Array)
#37 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('', Array)
#38 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('up', Array)
#39 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('up', Array)
#40 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('up', Array)
#41 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#42 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#43 /var/www/html/craft(22): yii\base\Application->run()
#44 {main}
*** failed to apply m230511_000000_field_layout_configs (time: 0.027s)`

Thanks!

### Craft CMS version

5.5.0

### Installed plugins and versions

-

**Comment by mathieuser** [comment]
Ok, never mind, just after posting this I did the following:

– Upgrade to craft 5.0.0 (fixed version)
– Migrate database successfully
– Upgrade to latest craft version
– Migrate database successfully

**Comment by idleog** [comment]
I run into the same problem, so if you ask me, sth. is not good here.

I used the workaround of @mathieuser (first update to craftcms 5.0.0, CKEditor 4.0.6 and migrate, then to craftcms ^5.0.0 and CKEditor 4.4.0 and migrate)
that worked, but it seems that there is a bug somewhere...

**Comment by i-just** [comment]
@idleog, it sounds like it's this bug: https://github.com/craftcms/cms/issues/16098. PR is already raised.

**Comment by brandonkelly** [comment]
Craft 5.5.0.1 is out with that fix. Thanks again!
