### ISSUE TITLE
[5.5.0]: Live preview with Matrix Blocks

### ISSUE THREAD

**Issue by rgauthier4c4** [craftcms/cms#16094]
### Description
I had this issue (https://github.com/craftcms/cms/issues/15713) with the live preview and I've update my project to the version 5.5.0 to test the new features.

Changing the status of a block refresh the live preview (without a draft). I understand that the status is linked to the entry and not the draft. But if I am editing an existing block, the live preview isn't using the drafted version of the content.

And i've see another bug in the same flow. If you create a Matrix entry and leave it as a draft and open the live preview. If you drag the order of another block, the drafted entry is appearing in the live preview, but you can't open the panel to edit it because the draft was saved and publish. If you close the preview, your block is now active.

Video to show the steps: https://gauthier-robin.com/uploads/craftcms/live-preview.mov

#### Editing 

1. Edit an entry with a matrix
2. Open the live preview
3. Edit a field in a matrix block

#### Status
1. Create a matrix entry and leave it as a draft
2. Open the live preview
3. Drag the position of another block
4. Try to open the draft block (Broken)
5. Close the preview and check the status of the draft block.

### Expected behavior
The preview is updated with the drafted content.

### Actual behavior
Nothing is updated.

### Craft CMS version

5.5.0

### PHP version

8.2

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! 

Live Preview won’t update as you type within the nested entry slideout, but it will update once you press Save. 
Thanks to #16002, as of 5.5.0, changes made to the nested entries are not automatically published when saved - they’re part of the owner’s draft, and only once the owner is saved (draft is applied) will those changes get published, too.

We’ll look into the other 2 issues you mentioned!

**Comment by brandonkelly** [comment]
Craft 5.5.1 is out with fixes for these bugs. Thanks again for reporting!
