### ISSUE TITLE
[5.x]: Can't move the last variant in the variant list

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#16103]
### Description

We have an product with more then 50 variants but when we we want to reorder the last variant of the page we get an JavaScript error.
Maybe related to: https://github.com/craftcms/cms/issues/16026

### Steps to reproduce

1. Create a product.
2. Add more than 50 variants to the product (e.g., 55 variants).
3. move the last variant

### Expected behavior
The variant should be at the position it’s dragged to.
Reordering should work consistently, allowing users to adjust the order of the variants.

### Actual behavior
The variant won't reorder and we get an JavaScript error in the console:
`Uncaught (in promise) ye {message: 'Request failed with status code 400', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}`
We can't reorder any other variants. I tried to move the last variant 3 times and get the same error 3 times:
![Image](https://github.com/user-attachments/assets/e147194a-f9aa-4941-ae3c-bf894b4a761e)

### Craft CMS version

5.4.10

### PHP version

8.3.8

### Database type and version

MySQL 8.0.37

### Installed plugins and versions

-Commerce: 5.x-dev

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by WHITE-developer** [comment]
We also have a different problem when I move an disabled variant:
![Image](https://github.com/user-attachments/assets/90cc285a-d517-40e0-933b-915512feabfc)
And save the page with "ctrl" + "s" the whole layout of variants changes:
![Image](https://github.com/user-attachments/assets/1536fd61-aa9a-4396-a545-b1429f2b85fc)
In the first image, we initially had two disabled products stacked above each other, with our moved variant positioned below them. However, after saving the page, the arrangement changed. Now, either:
- Two enabled variants have moved up, or
- Our moved variant has shifted down, now paired with another disabled variant.

**Comment by i-just** [comment]
Thanks! That’s a separate issue, and it only affects Commerce variants, so I [raised it](https://github.com/craftcms/commerce/issues/3769) in the Commerce repo (along with a PR).

**Comment by brandonkelly** [comment]
Craft 5.5.1 is out with that original fix. Thanks again!
