### ISSUE TITLE
[5.x]: "tag" constructor argument of the "craft\web\twig\nodes\GetAttrNode" class is deprecated

### ISSUE THREAD

**Issue by michtio** [craftcms/cms#16107]
### Description

Since the upgrade to Craft 5.5 our tracking systems get flooded with deprecation warnings from Twig, more specifically:

```
Since twig/twig 3.12: The "tag" constructor argument of the "craft\web\twig\nodes\GetAttrNode" class is deprecated and ignored (check which TokenParser class set it to "null"), the tag is now automatically set by the Parser when needed.
```

### Expected behavior

It would be nice if this is adjusted, or the deprecation errors could be silenced.

### Craft CMS version

5.5.0.1

### PHP version

8.3.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed now for the next Craft 4 and 5 releases.

**Comment by brandonkelly** [comment]
Craft 4.13.3 and 5.5.1 are out with that fix. Thanks again!
