### ISSUE TITLE
CORS policy prevents fetching updates

### ISSUE THREAD

**Issue by FrDH** [craftcms/cms#16100]
### Description
Somehow since this morning we are no longer able to check for updates in the control panel (on /cp//utilities/updates).
Getting this error in the devtools network tab on all different installs (both craft 4 and 5, both local and in production):
> updates:1 Access to XMLHttpRequest at 'https://api.craftcms.com/v1/updates?v=xxxxxxxx&processCraftHeaders=1' from origin 'https://xxxxxx.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### Steps to reproduce
1. Go to the updates page in the control panel
2. See an error appear on the page
3. See the network tab in devtools

### Craft CMS version

All I think

**Comment by jamesmacwhite** [comment]
Not official Craft support, but the Plugin Store/API is currently experiencing an outage, which is likely related, as it is not actually responding with proper API responses currently.

https://status.craftcms.com/

Currently returning a 503 error.
