### ISSUE TITLE
[5.x]: Last login date is not saved when creating users programmatically

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#16101]
### Description

I'm working on an import migration that's creating some users programmatically:

```php
$user = new User();
$user->email = $userData['E-Mail'];
$user->username = $userData['E-Mail'];
$user->firstName = $userData['First name'];
$user->lastName = $userData['Last name'];
$user->dateCreated = DateTimeHelper::toDateTime($userData['Created date']);
$user->dateUpdated = DateTimeHelper::toDateTime($userData['Changed date']);
$user->lastLoginDate = DateTimeHelper::toDateTime($userData['Login date']);
$user->active = true;

$success = $this->elements->saveElement($user);
```

I want to retain the timestamp fields (created, updated, last login) from the previous system, but the `lastLoginDate` is not saved.

I have verified that the timestamp is correct (the three timestamp fields all have the same format) and the `$user` object is correctly populated with a `DateTime` object. While `dateCreated` and `dateUpdated` get imported correctly, `lastLoginDate` doesn't. After the migration has run, the `lastLoginDate` is empty in the Control Panel (displayed as `Never`) for all imported users in the backend.

Is this the same issue as `$user->setGroups`, which doesn't have any effect when creating a user?

### Steps to reproduce

1. Create a user programmatically, set the last login date programmatically and save the user through the `Elements` service.
2. Look at the user in the Control Panel.

### Expected behavior

The last login date should be saved when creating a user.

### Actual behavior

The last login date is not saved, but is seemingly discarded.

### Craft CMS version

5.4.4

### PHP version

8.3

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out! That's expected behaviour. `lastLoginDate` and a few other properties are only updated in certain cases. For example the `lastLoginDate` will be updated after user has [logged in successfully](https://github.com/craftcms/cms/blob/5.x/src/services/Users.php#L718). After User element is saved (via `saveElement()` method) only some properties are stored in the User record. You can have a look at the [`afterSave()`](https://github.com/craftcms/cms/blob/5.x/src/elements/User.php#L2384) method on the User element to see the details. The values for `lastLoginDate`, `dateCreated` and `dateUpdated` won't be saved.

That said, if you have a valid case for changing those, you could first create a User element and then update the record directly.
To assign user to groups, you can use `Craft::$app->getUsers()->assignUserToGroups($user->id, $groupIds);`

I hope this helps!

I'll close this now, but feel free to reply if you run into any further issues.

**Comment by MoritzLost** [comment]
@i-just Thanks for the explanation. This may come across as a slight rant, but I find this very frustrating. This is a problem I run into a lot with custom modules. Some properties or methods _seem_ to do what I need, but don't actually work the way that can be reasonably expected because of some implementation detail that I don't really have a chance to find without a super intricate knowledge of the code base.

Those are just two examples. I set a `lastLoginDate`, which is exactly the property I need, but for some reason it's treated differently than all the other properties that I can set. Same with user groups – the first time I ran into this problem, I took a deep dive into the code and the database. So now I understand why `$user->setGroups()` won't actually save the groups I set, and I have to _first_ save the user and _then_ use the service to assign the groups. But how is a new developer that just wants to create a user and assign it some groups supposed to find out about this?

I feel that this is a weak point for Craft. In some cases, implementation details leak into high-level interfaces and models. I think this could be improved in multiple ways:

- Better differentiate between public methods and methods/properties that are intended for internal use (like `User::setGroups()` and `User::$lastLoginDate`).
- Improve the docblocks for those methods / properties to explain why their behaviour may not align with reasonable expectations.
- Improve documentation to include more examples for those use-cases.

---

To get back to this concrete case: Could the `afterSave` method be adjusted to save the `lastLoginDate` as well? If it's set explicitly, it's likely there for a reason, so is there any reason _not_ to save it?

---

> The values for lastLoginDate, dateCreated and dateUpdated won't be saved.

I'm curious about this, because only `lastLoginDate` is not working correctly in my migration. `dateCreated` and `dateUpdated` appear in my imported users correctly, using the values from the data source. Do you know how that is working if the `afterSave` method doesn't save those fields?

**Comment by i-just** [comment]
> dateCreated and dateUpdated appear in my imported users correctly

I checked the wrong table, sorry about the confusion 🤦‍♀ Yes, `dateCreated` and `dateUpdated` are set to the values you provide. The bit of code that sets them is here: https://github.com/craftcms/cms/blob/5.x/src/db/ActiveRecord.php#L99-L132.
