### ISSUE TITLE
[5.x]: Unable to Access Plugin Store in Craft CMS Control Panel to Upgrade from Solo to Pro

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#16106]
### Description
I am unable to access the Plugin Store in the Craft CMS Control Panel. This issue prevents me from upgrading from Craft Solo to Craft Pro (trial version). When I attempt to access the Plugin Store, the following error appears:

**Error message:** "The Plugin Store is not available, please try again later."

### Steps to reproduce
1. Log into the Craft CMS Control Panel.
2. Navigate to the Plugin Store.

### Expected behavior
The Plugin Store should load successfully, allowing me to browse and upgrade from Craft Solo to Pro.

### Actual behavior
The Plugin Store does not load, and I see the error message: "The Plugin Store is not available, please try again later."

### Additional Information
- **Craft CMS Version:** 5.0 (as specified in `composer.json`)
- **PHP Version:** 8.2
- **Plugins in use:** Various plugins, as detailed in `composer.json`.
- **Config file:** `app.php` contains additional configuration.

#### `composer.json` content
```json
{
  "minimum-stability": "dev",
  "prefer-stable": true,
  "require": {
    "craftcms/ckeditor": "^4.4",
    "craftcms/cms": "^5.0.0",
    "mmikkel/cp-field-inspect": "^2.0",
    "mmikkel/retcon": "^3.2",
    "nystudio107/craft-minify": "^5.0",
    "nystudio107/craft-seomatic": "^5.1",
    "nystudio107/craft-typogrify": "^5.0",
    "putyourlightson/craft-dashboard-begone": "^3.0",
    "spacecatninja/imager-x": "^5.0",
    "spicyweb/craft-embedded-assets": "^5.4",
    "studioespresso/craft-dumper": "^5.0",
    "studioespresso/craft-mailersend": "^5.0",
    "topshelfcraft/environment-label": "^5.0",
    "verbb/expanded-singles": "^3.0",
    "verbb/knock-knock": "^3.0",
    "verbb/smith": "^3.1",
    "vlucas/phpdotenv": "^5.4.0"
  },
  "require-dev": {
    "craftcms/generator": "^2.0.0",
    "yiisoft/yii2-shell": "^2.0.3"
  },
  "config": {
    "allow-plugins": {
      "craftcms/plugin-installer": true,
      "yiisoft/yii2-composer": true
    },
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "8.2"
    }
  },
  "scripts": {
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example.dev', '.env');\""
    ]
  },
  "autoload": {
    "psr-4": {
      "modules\\custom\\": "modules/custom/"
    }
  }
}
```

#### `config/app.php` content
```php
<?php
use craft\helpers\App;
use modules\custom\Custom;

return [
  'id' => App::env('CRAFT_APP_ID') ?: 'CraftCMS',
  'modules' => [
    'custom' => Custom::class,
  ],
  'bootstrap' => [
    'custom',
  ],
];
```

Thank you for your assistance with this issue.

### Craft CMS version

Craft Solo 5.5.0

### PHP version

8.2

### Installed plugins and versions

-

**Comment by jamesmacwhite** [comment]
It is a known issue due to a general service outage with the Craft Plugin Store, API, Console etc.

See: status.craftcms.com.

**Comment by brianjhanson** [comment]
Yep, Plugin Store & Console had some issues this morning, but those should be resolved now. Thanks!
