### ISSUE TITLE
[5.x]: Assets fields in card view overflows in slideouts

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#16112]
### Description

An Assets field with a thumbnail and some displayed fields overflows in a slideout at half width:

![Image](https://github.com/user-attachments/assets/8ed7dfa2-0531-4a8f-a30b-21ab9102a276)

### Craft CMS version

5.5.0.1

### PHP version

8.3

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! It only happens if the Assets field is set to View Mode: Cards and has ”Show cards in a grid“ turned on. Looking into it.

**Comment by brandonkelly** [comment]
Craft 5.5.1 is out with that fix. Thanks again!
