### ISSUE TITLE
[5.x]: The database is deleted when a section is deleted

### ISSUE THREAD

**Issue by foxtrt** [craftcms/cms#16115]
Description

I updated my craft version from 5.4.8 to 5.5.0 and noticed that after deleting a section something strange happens to my psql database

### Craft CMS version

5.5.0

### PHP version

8.2

### Operating system and version

Ubuntu 20.04

### Database type and version

PostgreSQL 16

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
There’s nothing in Craft itself that would ever delete an entire database, under any condition. Not really sure what to suggest, but can say with absolute certainty that Craft is not the culprit here.

**Comment by brandonkelly** [comment]
Another issue came in that is probably the same as this, but gave us a better clue as to what was going on (#16230). Craft 5.5.4 is out now with a fix for it.
