### ISSUE TITLE
[5.x]: Nested entries are sometimes lost when reverting entries to a previous revision

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#16116]
### Description

When reverting entries to a previous revision, nested Matrix entries are sometimes lost. 

https://github.com/user-attachments/assets/6cbffd36-32c8-4282-83d3-5f0f461cdcfe

### Steps to reproduce

The following steps should consistently reproduce the issue (it's what I'm doing in the above video):

1. Create a new entry that has a Matrix field using the inline-editable view mode in its field layout, and add a nested entry to the Matrix field. Save the entry.
2. Make some changes to the entry, and save it again (i.e. creating a new revision).
3. Revert the entry back to the first revision.
4. **Make some changes to the nested Matrix entry.** Then save the entry again.
5. Revert the entry back to the first revision, again
6. Notice that the nested entry has disappeared.

### Expected behavior

Nested entries should be retained when reverting content from a previous revision.

### Actual behavior

Nested entries sometimes disappear when reverting content from a previous revision.

### Craft CMS version

5.5.0.1

### PHP version

8.2.24

### Operating system and version

14.6.1 (DDEV v1.23.5)

### Database type and version

MySQL 8.0.36

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Craft 5.5.1 is out with a fix for that. Thanks for reporting!
