### ISSUE TITLE
Craft 3: "searchindex" table MyISAM engine causes PDOexception

### ISSUE THREAD

**Issue by iliaivanov** [craftcms/cms#1612]
### Description
_searchindex_ table MyISAM engine causes PDOException:
```
SQLSTATE[HY000]: General error: 1785 When @@GLOBAL.ENFORCE_GTID_CONSISTENCY = 1, updates to non-transactional tables can only be done in either autocommitted statements or single-statement transactions, and never in the same statement as updates to transactional tables.
The SQL being executed was: INSERT INTO `searchindex` (`elementId`, `attribute`, `fieldId`, `siteId`, `keywords`) VALUES (7, 'field', 1, 1, ' templatewithfooterandheader ') ON DUPLICATE KEY UPDATE `keywords` = ' templatewithfooterandheader '
```

When **GLOBAL.ENFORCE_GTID_CONSISTENCY** set to 1.

### Steps to reproduce
1. Install Craft version 3.0.0-beta.9.
2. Mysql **GLOBAL.ENFORCE_GTID_CONSISTENCY** set to 1.
3. Create some section and try to create new entry.

### Additional info
- Craft version: 3.0.0-beta.9
- PHP version: 7.0.17
- Database driver & version: MySQL 5.7.17
- Plugins & versions: Element API 2.0.1

Can _searchindex_ table engine be changed to InnoDB? If it's not possible to be changed in Craft's core (in initial migrations), then how harmful it might be for our app if we change it in our DB?

**Comment by takobell** [comment]
The InnoDB engine in MySQL didn't add support for Full Text search indexes until MySQL 5.6.4 and Craft 3 has a minimum MySQL requirement of MySQL 5.5.  Your options are to 1) set `ENFORCE_GTID_CONSISTENCY` to `0`, 2) change the storage engine for the `searchindex` table to use InnoDB or 3) use Postgres.

**Comment by iliaivanov** [comment]
Thank you @takobell !

**Comment by missmatsuko** [comment]
Since 3.1.12, searching with an InnoDB craft_searchindex table causes errors:
#3862

**Comment by brandonkelly** [comment]
For posterity, #3862 is now resolved.
