### ISSUE TITLE
[5.x]: Re-ordering nested entries doesn't trigger Live Preview refresh

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#16122]
### Description

This could be related to #16094, so pardon the noise if it is.

When re-ordering existing nested entries in a Matrix field using the Cards or Element Index view modes, Live Preview is only triggered for the first change (i.e. when the provisional draft is created). If there is a provisional draft already, subsequent re-ordering of the nested entries doesn't refresh the Preview.

Works as expected for the inline-editable view mode.

https://github.com/user-attachments/assets/3bfb74ab-1e52-4080-8c72-ccf8e3fd4df1

### Steps to reproduce

1. Create a Matrix field using the "Cards" view mode, and add some nested entries to an entry
2. Open up Live Preview and re-order the nested entries using the drag handles
3. Observe that the Live Preview is not auto-refreshed. Clicking the "Refresh" button manually works.

### Expected behavior

Re-ordering nested entries should auto-refresh Live Preview.

### Actual behavior

Re-ordering nested entries doesn't auto-refresh Live Preview, beyond the first change

### Craft CMS version

5.5.0.1

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 5.5.1 is out with that fix. Thanks again!
