### ISSUE TITLE
404 template doesn't show while in devMode

### ISSUE THREAD

**Issue by robmcfadden** [craftcms/cms#1613]
### Description

The 404.html template does not show like it used to when devMode is set to true. I am not sure that this is a problem, but it's a difference that took me a bit to figure out. Seems like there should be a way to see it while in devMode. Thanks!

### Steps to reproduce

1. Set devMode to true
2. Go to a URL that does not exist

### Additional info

- Craft version: 3.0.0-beta.10
- PHP version: 7.0.8
- Database driver & version: MySQL 5.5.42
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
This changed in [Beta 7](https://github.com/craftcms/cms/blob/develop/CHANGELOG-v3.md#300-beta7---2017-03-10):

> `UserException` reports are now styled like other exceptions when Dev Mode is enabled, with the full stack trace shown.

You can see your 404 template by requesting it directly, e.g. `http://mysite.dev/404`
