### ISSUE TITLE
[5.x]: JSON error after Craft 4 upgrade

### ISSUE THREAD

**Issue by CharlieGentle** [craftcms/cms#16138]
### What happened?

Upgrading a Craft 4 site to Craft 5.5.0.1

Accessing any page in the CP (except login) or the front-end results in an Invalid Argument error in **src/elements/db/ElementQuery.php** at line **2311**. This happens with all plugins disabled.

After a bit of debugging I can see it's trying to run Json::decode with a plain string instead of a JSON encoded string. In this case the string is 'Array'. I'm not sure why this is happening but if I change line 2309 to `if (!empty($this->customFields) && !empty($content) && json_validate($content)) {` then the CP loads ok but with a lot of missing content.

Have I missed a step in the upgrade process?

### Craft CMS version

5.5.0.1

### PHP version

8.2

### Operating system and version

Linux 5.10.104-linuxkit

### Database type and version

MySQL 8.0.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

Amazon S3 | 2.2.1
Compress | 5.0.0
Cookies | 5.0.0
Feed Me | 6.5.0
Hyper | 2.2.0
Imager X | 5.0.3
Navigation | 3.0.5
oEmbed | 3.1.1
Postmark | 3.1.0
Redactor | 4.2.0
SEOmatic | 5.1.5
Servd Assets and Helpers | 4.0.8
Sprig | 3.5.1
Super Table | 4.0.2
Twigpack | 5.0.0
Typed link field | 3.0.0-beta
Vite | 5.0.1
Wheel Form | 4.0.2
Wordsmith | 5.0.0

**Comment by brandonkelly** [comment]
Were you running MySQL 8.0.33 when you initially performed the upgrade? It sounds like the database didn’t support JSON columns at the time when you initially performed the upgrade.

**Comment by CharlieGentle** [comment]
🤦‍♂️ Sorry, I did the database change after the migration which was clearly the wrong way round.
