### ISSUE TITLE
[5.x]: Database error when saving a new Single section

### ISSUE THREAD

**Issue by trijammer** [craftcms/cms#16145]
### Description

After updating from 5.5.0.1 to 5.5.1.1, I can't create a new Single section. Every attempt to save a new one results in a database error.

### Steps to reproduce

1. Update to 5.5.1.1.
2. Create a new Single section, any configuration, any entry types.

### Expected behavior

New section created.

### Actual behavior

```
Database Exception – yii\db\Exception
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'craft_entries.deletedWithEntryType' in 'WHERE'
```
in  `.../vendor/yiisoft/yii2/db/Command.php at line 1320`

Stack trace:
https://pastebin.com/kj0fHTj4

### Craft CMS version

5.5.1.1

### PHP version

8.2.25

### Operating system and version

Linux 5.4.0-196-generic

### Database type and version

MariaDB 10.6.20

### Installed plugins and versions

- CKEditor 4.4.0
- Postmark 3.1.0

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by MoritzLost** [comment]
I'm also seeing this issue when running `craft/up`. Hope the fix can be released soon, already updated and now we're stuck 👀

**Comment by brandonkelly** [comment]
Craft 5.5.2 is out with a fix for this. Thanks again!
