### ISSUE TITLE
[5.x] View field selection list on a new (unsaved) Custom Sources duplicates Fields to select

### ISSUE THREAD

**Issue by humandevs** [craftcms/cms#16177]
If a Field is added to multiple Entry Types, when a Custom Sources is created (but not yet saved), the Fields will be duplicated in the list of Fields to select for the Custom Sources View columns. 

Once the Custom Sources is saved, selecting Fields for the View columns correctly "collapses" those multiple Field instances into one Field/column to select for the View.

Before saving a new Custom Source:
![image](https://github.com/user-attachments/assets/313a6861-058e-46b0-95f7-f7d69abbb011)

Editing an existing Custom Source:
![Image](https://github.com/user-attachments/assets/5994e089-cc62-4af2-b58e-19275906a106)

This is in Craft 5.5.0.1, but exists in older version of 5 as well.

### Discussed in https://github.com/craftcms/cms/discussions/16119

<div type='discussions-op-text'>

<sup>Originally posted by **humandevs** November 14, 2024</sup>
The list of fields to add to a Custom Sources view can be confusing as it lists all fields even if a View filter limits the Entry Types to include in that view, and because the same Field can now be used in multiple Entry Types, all of them are listed in the View columns, and there's no easy way to differentiate which Entry Type corresponds to the Field added to the View. Adding the Entry Type to the label for the Field in the View list would solve this issue. 

Example screenshot of multiple Fields with the same name but for different Entry Types confusingly presented as options for adding to a Custom Sources view:

![image](https://github.com/user-attachments/assets/313a6861-058e-46b0-95f7-f7d69abbb011)

Even better would be to only need to add the Field column once for all Entry Types Fields that are of the same source Field type, so that multiple columns don't have to be taken up to show contents of Fields of the same source/name but from multiple Entry Types, but that's a whole other can of worms!
</div>

**Comment by brandonkelly** [comment]
Craft 5.5.3 is out with the fix for this. Thanks for reporting!
