### ISSUE TITLE
Add child category without parent

### ISSUE THREAD

**Issue by tu5** [craftcms/cms#1618]
### Description
I was trying to have a country selection that would include continents but went into trouble like on this pic:
![paz7c](https://cloud.githubusercontent.com/assets/18059922/24928533/0c001c68-1f03-11e7-86b2-6252c1121a10.png)

### Steps to reproduce

1. Create categories like on above pic and limit field to one or two

### Additional info

- Craft version: Craft CMS 2.6.2971

**Comment by carlcs** [comment]
The Categories field’s Limit setting is replaced with a Branch Limit setting in Craft 3 (see https://github.com/craftcms/cms/issues/1388). With this set to 1, you wouldn’t be able to select Europe and North America in your example.
