### ISSUE TITLE
[5.x]: Address fieldLayout not restored when rebuilding project config

### ISSUE THREAD

**Issue by ryansupercool** [craftcms/cms#16189]
### Description

It would appear that when clearing out the project config files and running `craft project-config/rebuild`, `addresses.fieldLayouts` is not restored.

### Steps to reproduce

1. Save Address field layout
2. Remove the loaded project config
  - clear caches
  - delete `config/project`
  - remove data from `projectconfig` table
  - clear `storage/config-deltas`, `storage/runtime`
3. Run `craft project-config/rebuild`
### Expected behavior

When running `craft project-config/rebuild` the layout data is added back to `config/project/addresses/fieldLayouts`.

### Actual behavior

When running `craft project-config/rebuild` the layout data is missing from `config/project/addresses/fieldLayouts`.

### Craft CMS version

5.5.2

### PHP version

8.2.15

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 4.13.3 and 5.5.3 is out with that fix. Thanks again!
