### ISSUE TITLE
[5.x]: Ckedcitor save error in craft instance with multiple groups

### ISSUE THREAD

**Issue by LeoWie93** [craftcms/cms#16196]
### Description
Having a craft instance with:
- 2 groups of sites
  - Group A
    - Site A1 (primary site), Site A2
  - Group B
    - Site B1, Site B2
- the primary site can only be in one group. Only one primary site can exist.

Trying to save an entry that is part of Site B1 or B2 gives an error.

### Steps to reproduce

1. Have a craft instance with the structure explained above
2. have entries with a ckeditor field
3. try to save said entry

### Expected behavior
the entry saves

### Actual behavior
![Image](https://github.com/user-attachments/assets/db3f032c-bab7-4276-81fe-e9e35aaa251b)

### Craft CMS version

5.52

### PHP version

8.2

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting!

I suspect PR https://github.com/craftcms/cms/pull/16162 will fix this. If you’d like to test early, you can change your `craftcms/cms` requirement in `composer.json` to
```
"craftcms/cms": "5.x-dev#cab2531e1a244ae15d04e122f47d919c83f11772 as 5.5.2",
```
and run `composer update`.

**Comment by brandonkelly** [comment]
Craft 5.5.3 is out with the fix for this. Thanks again!
