### ISSUE TITLE
3.0 Beta: Checkboxes & Select Fields Data Not Rendering in Admin UI

### ISSUE THREAD

**Issue by travismeyer** [craftcms/cms#1619]
### Description
Upon refresh after saving checkbox or select fields to an entry, the saved data is not reflected in the admin ui, although the data is properly saved to the content table row. 

### Steps to reproduce
1. Setup checkbox or multiselect fields & configure etc
2. Select checkbox or multiselect data in admin ui and `cmd + s`

-> Checkboxes 'reset' such that all options are null

### Additional info
- Craft version: 3
- PHP version: 7.0
- Database driver & version: mysql2
- Plugins & versions: element api 2.0.1

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. What specific version of Craft 3 are you running? The latest is `3.0.0-beta.10`. If you’re on something earlier, try running `composer update` and see if you’re still getting it.

If updating doesn’t fix (or you’re already on the latest), please send in a support ticket from your dashboard, including the DB backup, and reference this issue #. We may have better luck reproducing the bug using your DB backup.

**Comment by travismeyer** [comment]
Hey Brandon,

After a day and a half getting craft 3 setup with a docker image based on nginx-php-fmp I'm still having the same issue with checkboxes. It's really weird.

But you're right — I'm on `3.0.0-beta.3`. I ssh'd into my docker image and ran `composer update` but got:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

Sorry if this is a newbie question, I'm a bit new at managing composer dependencies, any idea why the latest isn't being brought in by `composer update`?

**Comment by brandonkelly** [comment]
If you’re stuck on Beta 3 it’s because the environment doesn’t have all of the necessary PHP extensions, which we added as Composer dependencies in Beta 4 (fa7d2ff3da643f17e4d062b96d17671b1add068e).

You can probably find out which specific extension is missing by bumping your `craftcms/cms` version requirement to `"^3.0.0-beta.10"`, forcing Composer to explain why it can’t install that version.

Or you can just have Composer completely ignore the PHP requirements, and let Craft do its own extension checking:

```shell
composer update --ignore-platform-reqs
```

**Comment by travismeyer** [comment]
Thanks again,

I successfully updated to beta.10, and using a new database, was able to again recreate the issue described above. I double checked the system report and all the requirements are met, seems like somethin' else is going on.

I'll go ahead and send a message to craft support with a db dump. Feel free to close this issue if you'd like, I'll go ahead and close the other related issue (multi-select behaving the same).

**Comment by travismeyer** [comment]
Forgot to add — I submitted a message to craft support with a db dump.
