### ISSUE TITLE
[5.x]: Pagination of Entrytypes not working correctly

### ISSUE THREAD

**Issue by samuelreichor** [craftcms/cms#16204]
### Description
The pagination of the Entrytypes is not working correctly when using it together with the search. 

https://github.com/user-attachments/assets/6f0e895b-7b1c-40b1-b29b-cae8e6f566ea

### Steps to reproduce

1. Search for something, that shows more than 100 Entrytypes
2. Try to use the pagination

### Expected behavior
The pagination should show the Entrytypes. 

### Craft CMS version

5.5.2

### PHP version

8.3

### Operating system and version

MacOs 14.2 (23C64)

### Database type and version

mariadb 10.4

### Installed plugins and versions

    "born05/craft-sentry": "3.0.0",
    "craftcms/ckeditor": "4.4.0",
    "craftcms/cms": "5.5.3",
    "craftcms/feed-me": "6.5.0",
    "craftcms/mailgun": "3.1.0",
    "craftcms/redactor": "4.2.0",
    "doublesecretagency/craft-cpcss": "3.0.0",
    "goldinteractive/craft-sitecopy": "2.1.1",
    "mmikkel/cp-field-inspect": "2.0.2",
    "nystudio107/craft-emptycoalesce": "5.0.0",
    "nystudio107/craft-retour": "5.0.3",
    "nystudio107/craft-seomatic": "5.1.6",
    "nystudio107/craft-templatecomments": "5.0.3",
    "nystudio107/craft-twigprofiler": "5.0.0",
    "nystudio107/craft-vite": "5.0.1",
    "putyourlightson/craft-blitz": "5.9.6",
    "putyourlightson/craft-elements-panel": "3.0.0",
    "spacecatninja/imager-x": "5.0.3",
    "studioespresso/craft-dumper": "5.0.1",
    "ttempleton/craft-nocache": "3.0.4",
    "verbb/expanded-singles": "3.0.1",
    "verbb/field-manager": "4.0.3",
    "verbb/formie": "3.0.12",
    "verbb/hyper": "2.2.0",
    "verbb/image-resizer": "4.0.1",
    "verbb/smith": "3.1.0",
    "verbb/tablemaker": "5.0.3",

**Comment by samuelreichor** [comment]
(After submitting, I also tested it with "craftcms/cms": "5.5.3", but it doesn't work in this version either.)

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.5.4 is out with that fix. Thanks again!
