### ISSUE TITLE
[4.x]: Relational field exists condition

### ISSUE THREAD

**Issue by dusan-stojnic** [craftcms/cms#16203]
### Description
When trying to filter element index with relational field has a value condition, an error occurs.

### Steps to reproduce

1. Navigate to any element index where elements field layout has relational field.
2. Try to filter out elements where that relational field has a value

### Expected behavior
Get a list of elements that match condition

### Actual behavior
Server error occurred flash message

### Craft CMS version

4.13.3 & 4.12.9

### PHP version

8.2.20 & 8.2.23

### Operating system and version

Linux 5.15.167.4-microsoft-standard-WSL2 & Linux 6.1.0-23-amd64

### Database type and version

MariaDB 10.4.34 & MySQL 8.0.39

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

**Comment by dusan-stojnic** [comment]
While checking, I found that namespace is missing from some parts of the query in `existsQueryCondition` method in `BaseRelationalField`. Adding the namespace fixes the error, but there were still no results.

**Comment by i-just** [comment]
Hi, thanks for reaching out! I can’t replicate this behaviour. Could you enable [`safeMode`](https://craftcms.com/docs/4.x/config/general.html#safemode) and check if the issue persists? Could you please check the logs (`storage/logs/web*.log`) and share the stack trace for this error?

**Comment by dusan-stojnic** [comment]
After trying `safeMode` and some more debugging, figured out it was one of the plugins that caused the issue, sorry for the hassle.

**Comment by i-just** [comment]
Thanks for the update. Glad you got to the bottom of it!
