### ISSUE TITLE
[5.x]: Link field link types order control visually broken when only only one link type enabled

### ISSUE THREAD

**Issue by michaelij** [craftcms/cms#16213]
### Description

The button that lets you order link field types shows an empty menu when there's only one type enabled

### Steps to reproduce

1. Create a link field type
2. Tick only one of the types
3. Click the "..." button next to that option

### Expected behavior

Either don't show this toggle button when only one option is enabled, or show but disable the options.

### Actual behavior

A weird looking empty menu:

![Image](https://github.com/user-attachments/assets/002c9a2d-b5a3-4f21-b5c4-c44811427553)

### Craft CMS version

5.5.3

### PHP version

8.2.24

### Operating system and version

Linux 6.10.4-linuxkit

### Database type and version

MySQL 8.0.36

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

```
"carlcs/craft-diywidget": "4.1.1",
"craftcms/ckeditor": "4.4.0",
"craftcms/cms": "^5.0.0",
"ether/seo": "5.0.0",
"miranj/craft-obfuscator": "1.2.0",
"mmikkel/cp-clearcache": "2.0.1",
"mmikkel/cp-field-inspect": "2.0.2",
"nystudio107/craft-twigpack": "5.0.0",
"verbb/default-dashboard": "3.0.1",
"verbb/expanded-singles": "3.0.1",
"verbb/field-manager": "4.0.3",
"verbb/super-table": "4.0.2",
"vlucas/phpdotenv": "^5.6.1",
"xpertbot/craft-wheelform": "4.0.2"
```

**Comment by i-just** [comment]
Hi, thanks for pointing that out. I raised a PR for it.

**Comment by brandonkelly** [comment]
Craft 5.5.4 is out with that fix. Thanks again!
