### ISSUE TITLE
[5.x]: Field type compatibility is inaccurate

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#16219]
### What happened?

When switching between field types, **the default field type compatibility is inaccurate**.

I wouldn't say that that the "Address (Google Maps)" field type is compatible with _any_ of these other types...

<img src="https://github.com/user-attachments/assets/4264a1c8-07d8-43c5-8eed-27739d68e87d" alt="Dropdown when switching field types" width="251" style="padding-bottom:20px">

***

I discovered this when trying to mark the "Address (GM)" field as compatible with the Ether "Map" field... they were **already marked as compatible by default.**

Obviously, this negates the purpose of the `EVENT_DEFINE_COMPATIBLE_FIELD_TYPES` event.

<img src="https://github.com/user-attachments/assets/7027c9bd-9a3c-44fa-9746-2f714cf0ebe3" alt="Shouldn't be compatible by default" width="257">

***

### Steps to reproduce

1. Install Google Maps (or any plugin which adds a custom field type).
2. Create a field of the custom type (ie: "Address (Google Maps").
3. Go back and attempt to change field types.
4. Note which field types are marked as compatible.

### Expected behavior

None of those other field types should be marked as compatible by default.

### Actual behavior

See screenshot.

### Craft CMS version

5.5.3

### PHP version

8.2.22

### Operating system and version

Linux 6.11.6-orbstack-00279-g28c6c77332e6

### Database type and version

MySQL 8.0.36

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- Google Maps v5.0.3
- Maps v5.0.4

**Comment by brandonkelly** [comment]
Looks like [AddressField](https://github.com/doublesecretagency/craft-googlemaps/blob/v5-dev/src/fields/AddressField.php) isn’t defining a `dbType()` method, so the default value (`string`) is being returned. So it’s being marked as compatible with any other field types that also return `string`.

It looks like you’re storing address values in a separate table via `afterElementSave()`, so you should be returning `null`, to indicate that the fields shouldn’t get a place within elements’ content JSON data (and so they aren’t marked as compatible with any other field types).

```php
public static function dbType(): array|string|null
{
    return null;
}
```

**Comment by lindseydiloreto** [comment]
Brilliant, that did the trick! Thanks @brandonkelly! 🍺
