### ISSUE TITLE
[5.x]: Live preview - x-craft-live-preview parameter

### ISSUE THREAD

**Issue by iwingate-digistorm** [craftcms/cms#16211]
### Description
When editing a matrix item (cards view) on a page Entry in Live Preview. The `x-craft-live-preview` value doesn't change. If I update any field on the Entry itself (eg, Title). I get a new `x-craft-live-preview` value every time.

### Expected behavior
I'd expect the `x-craft-live-preview` value to update, to help with cache busting. 

### Craft CMS version

5.5.2

### PHP version

8.3

**Comment by brandonkelly** [comment]
When you edit a nested entry within a Matrix field in cards view, the preview only actually updates when you press **Save**. When you do that, the `x-craft-live-preview` param gets updated just like for other updates.
