### ISSUE TITLE
[5.x]: homepage url always contains a trailing slash

### ISSUE THREAD

**Issue by nitriques** [craftcms/cms#16226]
### Description

We have ` 'addTrailingSlashesToUrls' => false,` in the config file.
Url should never have a trailing slash.

### Steps to reproduce

1. Set a section to be the home page. Here's the setup:
![Image](https://github.com/user-attachments/assets/26ff0ea9-123f-4e60-ab5d-408f2624068c)

Here's the site setup (no trailing slash)

![Image](https://github.com/user-attachments/assets/bad9b1c9-5af1-42f0-a070-2a13ed5eedbe)

### Expected behavior

The home page url should be `hxxps://host/en` not `/en/`.
The same goes for the site url, which always seems to contains a trailing /.

We have this problem both in the cp and in graphql responses.

### Actual behavior

The home page url is (and the site url) is `hxxps://host/en/`.

### Craft CMS version

5.5.3

### PHP version

8.3

### Operating system and version

linux

### Database type and version

mysql 8

### Image driver and version

gd

### Installed plugins and versions

- N/A

**Comment by i-just** [comment]
Hi, thanks for getting in touch! This was raised before in https://github.com/craftcms/cms/issues/5675. There are some workarounds you can use on that issue, and it’s on the list for v6 (as changing the behaviour would be a breaking change).

I'll close this now, but the original issue is still open if you want to follow there.

**Comment by nitriques** [comment]
Ah. Sorry about the duplicate. 

Thanks.
