### ISSUE TITLE
[4.x]: Changing matrix field handle creates duplicate DB table when applying project config

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/cms#16227]
### Description

After changing the handle of an existing matrix field, deploying and applying the project config changes resulted in an unexpected database structure. Specifically:
* A new `matrixcontent` table was created for the new handle, but it lacked columns for the matrix block fields
* The `matrixcontent` table for the old handle remained in the database unchanged

### Steps to reproduce

1. Create a matrix field, deploy the project config changes, and apply them. This updates the database as expected.
2. Change the matrix field's handle, deploy the project config changes, and apply them.

### Expected behavior

The database table for the matrix field should be renamed from `matrixcontent_oldhandle` to `matrixcontent_newhandle`, preserving the existing columns for the matrix block fields.

### Actual behavior

A new table, `matrixcontent_newhandle`, is created, but it does not include any columns for the matrix block fields. The `matrixcontent_oldhandle` table remains in the database, unmodified.

### Craft CMS version

4.13.3

### PHP version

8.2.4

### Operating system and version

Linux 4.15.0-65-generic

### Database type and version

PostgreSQL 14.7

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.7-4)

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 4.13.4 and 5.5.4 are out with that fix. Thanks again!
