### ISSUE TITLE
[5.x]: Duplicate entry type icon displaying on cards inside matrix field

### ISSUE THREAD

**Issue by wearereeds** [craftcms/cms#16234]
### Description
When selecting to show 'Entry Type' on a card which has a icon assigned, the displayed card inside a matrix shows the icon twice.

![Image](https://github.com/user-attachments/assets/f1228d58-ea94-44ca-8081-31f1bf8d4727)

### Steps to reproduce

1. Create Entry Type
2. Assign Icon To Entry Type
3. Select 'Entry Type' in Card Attributes
4. Assign Entry Type To A Matrix Field
5. Set Matrix Field To Display Cards
6. Create New Entry In Matrix Field

### Expected behavior
- Show Icon Once

### Actual behavior
- Shows Icon Twice

### Craft CMS version

5.5

### PHP version

8.4

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
Craft 5.5.4 is out with that fix. Thanks again!
