### ISSUE TITLE
Field type’s `beforeSave()` method not called for new Asset elements

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#1623]
### Description

At the point where it’s currently called, the new element has no field layout yet and “Tell the fields about it” does exactly nothing.

https://github.com/craftcms/cms/blob/3.0.0-beta.10/src/elements/Asset.php#L992
https://github.com/craftcms/cms/blob/3.0.0-beta.10/src/base/Element.php#L1690

### Additional info

- Craft version: 3.0.0-beta.10
- PHP version: 7.0.15
- Database driver & version: MySQL / MariaDB 10.1.21
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
@andris-sevcenko Probably just need to set the assets’ `$fieldLayoutId` earlier on in the request. It should probably be set right when you are first instantiating the Asset object.
