### ISSUE TITLE
[5.x]: Can't programmatically create a link to an entry in a Link field

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#16245]
### Description

I'm trying to programmatically create an entry link in a [Link field](https://craftcms.com/docs/5.x/reference/field-types/link.html). The first thing I tried is to set the `type` to `entry` and the `value` to the ID of the target entry:

```php
$target = Entry::find()->id(123)->one();
$entry->setFieldValue('myLinkField', [
    'type' => 'entry',
    'value' => $target->id,
]);
```

But that doesn't work. Had a look at the source code, I also tried to set `['entry' => $target->id]`, that doesn't work either. The only way I found that works is to reverse-engineer the entry reference tag format that's used by the field and use that:

```php
$entry->setFieldValue('myLinkField', [
    'type' => 'entry',
    'value' => sprintf('{entry:%1$s@1:url}', $target->id),
]);
```

But that's very awkward and relies on undocumented internal behaviour that might change at any point.

### Expected behavior

Setting the `value` to an entry ID (first example) should create a link to that entry's ID.

### Actual behavior

I have to match the storage format used by the field internally exactly, or my link isn't saved correctly.

Slightly off-topic, but it would be super helpful if the documentation for Craft fields included examples for how to set values programmatically. At the moment it's a combination of trial and error and code diving.

### Craft CMS version

5.5.3

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment]
We’ve added support for passing an element instance or an ID into the `value` key for Craft 5.6 (#16255).

> But that's very awkward and relies on undocumented internal behaviour that might change at any point.

FWIW, reference tags are in fact [documented](https://craftcms.com/docs/5.x/system/reference-tags.html) and the syntax is not expected to ever change. (It would break a lot of existing content if we did!)

**Comment by MoritzLost** [comment]
@brandonkelly Great, thanks!

> FWIW, reference tags are in fact documented and the syntax is not expected to ever change. (It would break a lot of existing content if we did!)

Sorry, I was too unspecific there. I didn't mean reference tags itself, but rather that the link field _uses_ reference tags internally to store element links. That part is opaque to users, and was a bit surprising at first, at least to me 🙂
So being able to just pass in an entry ID is a great improvement!

**Comment by brandonkelly** [comment]
Craft 5.6.0 is out now 🚀
