### ISSUE TITLE
[4.x]: SVG with focal point breaks transforms, thumbnail generation

### ISSUE THREAD

**Issue by kabel** [craftcms/cms#16258]
### Description

I am using an asset field on an entry to generate some page CSS for background images. I've started to use SVG background images and would like to use the asset focal point feature to control the `background-position` in the entry template.

### Steps to reproduce

1. Upload an SVG as an asset
2. Click the preview button
3. Click the enable focal point button
4. Drag and save the focal point
5. Save the asset

### Expected behavior

The asset is saved and a thumbnail of the asset is generated that either ignores the focal point or does as the source `TODO` [mentions](https://github.com/craftcms/cms/blob/c89aea32f0ec77d4e32d5c1cdf282ef917d60aa9/src/image/Svg.php#L165-L168).

### Actual behavior

An error is thrown and a message is written to the log.

```
[web.ERROR] [craft\errors\ImageTransformException] Failed to generate transform with id of #
```

![Image](https://github.com/user-attachments/assets/ab17399a-4e06-4ad1-85fc-0fd97409040d)

### Craft CMS version

4.13.0

### PHP version

8.3.8

### Operating system and version

Linux 4.14.345-262.561.amzn2.x86_64

### Database type and version

MySQL 8.0.35

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.13-11)

### Installed plugins and versions

- Amazon S3 	2.2.1
- CKEditor 	3.10.0

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next Craft 4 and 5 releases.

**Comment by brandonkelly** [comment]
Craft 4.13.7 and 5.5.7 are out with that fix. Thanks again!
