### ISSUE TITLE
[5.x]: Invalid Configuration: Either `sectionId` or `fieldId` + `ownerId` must be set on the entry

### ISSUE THREAD

**Issue by jamiepittock** [craftcms/cms#16254]
### Description

I ran across this when attaching a behavior to our entries.

```
Event::on(
    Entry::class,
    Entry::EVENT_DEFINE_BEHAVIORS,
    function(DefineBehaviorsEvent $e) {
        if ($e->sender->getType()->handle === 'questionType') {
            $e->behaviors['questionTypeStats'] = QuestionTypeBehavior::class;
        }
    }
);
```

For nested matrix entries this seems to throw the error 

> Invalid Configuration – [yii\base\InvalidConfigException](https://www.yiiframework.com/doc-2.0/yii-base-invalidconfigexception.html)
> Either `sectionId` or `fieldId` + `ownerId` must be set on the entry.

These entries have a `fieldId` + `primaryOwnerId`, but no `ownerId`.

![Image](https://github.com/user-attachments/assets/99399ee1-f24a-4701-b958-f0bf80a03287)

### Craft CMS version

5.5.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
There were a few areas throughout the control panel where we were instantiating elements without actually configuring them at all (e.g. setting the `sectionId`/`fieldId`/`ownerId` on entries), which led to this error when calling `getType()`.

Craft 4.13.4 and 5.5.4 are out with a couple fixes for those (130fd77e0fce7213b9284cd1e9a62cd2505c5291 + eff667160a318a8301304481ff2b36b0edcca505).

You still may want to make your code a bit more defensive though, in case any plugins are doing something similar.

```php
use craft\elements\Entry;
use craft\events\DefineBehaviorsEvent;
use yii\base\Event;
use yii\base\InvalidConfigException;

Event::on(Entry::class, Entry::EVENT_DEFINE_BEHAVIORS, function(DefineBehaviorsEvent $e) {
    /** @var Entry $entry */
    $entry = $e->sender;

    try {
        $type = $entry->getType();
    } catch (InvalidConfigException $e) {
        return;
    }

    if ($type->handle === 'questionType') {
        $e->behaviors['questionTypeStats'] = QuestionTypeBehavior::class;
    }
});
```

**Comment by jamiepittock** [comment]
Thanks!

**Comment by architchandra** [comment]
Still facing this kind of an issue but with the `EVENT_DEFINE_RULES` event.

Craft CMS `5.10.12`.

**Comment by brandonkelly** [comment]
@architchandra See the commits I referenced in my last message for examples of how you can fix in your own code.

**Comment by architchandra** [comment]
@brandonkelly - Yes, that was super helpful. We followed that advice only. Thanks! Wrote to you just to bring this seemingly-related error to your notice as well.

**Comment by brandonkelly** [comment]
@architchandra Thanks, but unfortunately we can’t do anything to fix event-based code. That’s going to be up to whatever plugin/module is implementing the event.
