### ISSUE TITLE
[5.5.4]: Matrix (cards) is broken

### ISSUE THREAD

**Issue by vandres** [craftcms/cms#16262]
### Description

With the latest update, there was a bug introduced, which breaks adding new elements to a Matrix. 

`NestedElementManager.js` line 427 - $editBtn can also be null

https://github.com/user-attachments/assets/a6ce61ca-67f7-4118-a4f7-7b8840769e58

### Steps to reproduce

1. Create a Matrix (cards)
2. Add an element to the Matrix
3. Try to open the context menu

### Expected behavior

Context menu is working

### Actual behavior

Context menu is not working

### Craft CMS version

5.5.4

### PHP version

8.3

### Operating system and version

MacOS

### Database type and version

MariaDB 10.5

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 5.5.5 is out with a fix.
