### ISSUE TITLE
[5.x]: URI no longer being generated for new entries

### ISSUE THREAD

**Issue by mark-reason** [craftcms/cms#16271]
### Description
Any new entries aren't generated a uri

### Steps to reproduce

1. Create new entry
2. Check graphql output

### Expected behavior
Return the uri like older entries

### Actual behavior
URI returns null

https://github.com/user-attachments/assets/216c8c56-340f-4e6d-8f7e-c32a50f140c8

### Craft CMS version

5.5.4

### PHP version

5.1.23

### Operating system and version

macOS 14.6.1

### Database type and version

mysql 8.0

### Installed plugins and versions

- CKeditor
- Webhooks
- Navigation

**Comment by i-just** [comment]
Hi, thanks for reaching out. Can you please turn on the [`safeMode`](https://craftcms.com/docs/5.x/reference/config/general.html#safemode) and see if you get the same result? Can you also share the settings for the section from your screen recording?

**Comment by mark-reason** [comment]
Thank you, I found this issue, I had my "Entry URI Format" set to {uri}, have now changed to {parent.uri}/{slug} and is working again.
