### ISSUE TITLE
[5.x]: Link field changes in one site do not reflect in the entry of other site versions in a multisite setup after changing the translation method.

### ISSUE THREAD

**Issue by suposatech** [craftcms/cms#16274]
### Description
I have over 1,000 entries in a section, with the same entries translated into other languages in a multisite setup. For a button, I use a link field. To support multi-language translation, I changed the Translation Method to 'Translate for each site.'

When I tested it by adding a new entry, it worked as expected. For example:

New Entry URL:
Global site: abc.com
French site: abc.com/fr
However, for older entries, the change doesn't reflect. Instead, I get:

Old Entry URL:
Global site: abc.com
French site: abc.com (instead of abc.com/fr).

### Steps to reproduce

Add a link field without setting any translation method initially. Add an entry, and after saving, change the translation method.

### Expected behavior
Global site: abc.com
French site: abc.com/fr

### Actual behavior
Global site: abc.com
French site: abc.com

### Craft CMS version

5.5.1.1

### PHP version

8.3.14

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
> When I tested it by adding a new entry, it worked as expected. For example:
> 
> New Entry URL: Global site: abc.com French site: abc.com/fr However, for older entries, the change doesn't reflect. Instead, I get:

Link fields explicitly cater to this context – see #15821.

In any other context, it’s expected that the value you set on a translatable Link field will only be applied to the site you set it on, and whatever other sites the value should get propagated to via the field’s translation method (which is none, for “Translate for each site”).

**Comment by ammannbe** [comment]
Not sure if this is really related or if I should open a new issue.

If we create a new website, we normally setup the whole website structure, texts, images, links etc. in one language. In the next step we create a new site (e.g. German) and copy the content to the new site.

Now the entry in a link field does not point to the corresponding site in German, but still in English instead.
Is that also intended?

**Comment by brandonkelly** [comment]
@ammannbe Just tested that locally, and Link field values with an entry selected are getting updated to point to the new site, when adding a new site to a section.

There are a couple prerequisites, though:

- The Link field’s Translation Method setting must be set to something besides “Not translatable”.
- The selected entry must already be enabled for the newly-added site, and its section settings must specify an Entry URI Format for the site (so it has a URL on that site).
