### ISSUE TITLE
[5.x]: columnSuffix deprecated, how to get a fields column name?

### ISSUE THREAD

**Issue by segidev** [craftcms/cms#16285]
### Description
I am having a custom query to optimize and also to cover a pretty complex query. Before the upgrade from Craft 4 (latest) to Craft 5 I was able to do this:

```php
$releaseDateColumnName = ElementHelper::fieldColumnFromField(Craft::$app->getFields()->getFieldByHandle('releaseDate'));
```

This way I get the column name like `field_releaseDate_jwzcxmze`.

Now I can't find any way anymore to get this. The `ElementHelper::fieldColumnFromField` is not available anymore. This method was using the `columnSuffix` and the `handle` (see [here](https://github.com/craftcms/cms/blob/4.13.5/src/helpers/ElementHelper.php#L735-L742)).

I see though now `columnSuffix` is deprecated. It is still working but I don't want to use something that might just disappear with the next update, silently breaking everything.

The docs (see [here](https://craftcms.com/docs/5.x/upgrade.html#advanced-queries)) suggest to use `getValueSql()` but that doesn't work with a custom sql string query. The result of `getValueSql()`is like this:

```
COALESCE(("elements_sites"."content"#>>'{"590ad414-264f-452a-82f1-f2d4d1eb8991","date"}'), ("elements_sites"."content"#>>'{"590ad414-264f-452a-82f1-f2d4d1eb8991"}'))
```

### Steps to reproduce

Craft:

```php
$field = Craft::$app->getFields()->getFieldByHandle('releaseDate');
$field->columnSuffix; // <--- deprecated
```

Commerce:

```php
$productsType = Plugin::getInstance()->getProductTypes()->getProductTypeByHandle('products');
$releaseDateField = $productsType->getVariantFieldLayout()->getFieldByHandle('releaseDate');
$releaseDateField->columnSuffix; // <---- deprecated
```

### Expected behavior

Any clear way to get the column name? I can't find anything to be honest

### Craft CMS version

Craft Pro 5.5.5

### PHP version

8.2.24

### Database type and version

PostgreSQL 14.11

**Comment by i-just** [comment]
Hi, thanks for reaching out!
 
In Craft 5, elements’ content is stored in the `elements_sites` table in a `content` column as a JSON blob, so there are no separate columns per field anymore. You can find more info on it [here](https://craftcms.com/docs/5.x/upgrade.html#elements-content).

> The docs (see [here](https://craftcms.com/docs/5.x/upgrade.html#advanced-queries)) suggest to use getValueSql() but that doesn't work with a custom sql string query.

Could you please clarify what you’re trying to do and how the `getValueSql()` doesn’t work?

**Comment by segidev** [comment]
@i-just Thank you 🙏 for your answer.

When using a completely custom query for example:

```php
$command = Craft::$app->db->createCommand(sprintf(
    <<<'EOD'
WITH products AS (
    SELECT DISTINCT p.id, MAX(c.title) OVER(PARTITION BY p.id) as title, %s
    FROM commerce_products as p
      INNER JOIN commerce_variants v on p.id = v."productId"
      INNER JOIN content c on v.id = c."elementId"
      INNER JOIN elements e on c."elementId" = e."id"
      INNER JOIN relations r on v."id" = r."sourceId"
    WHERE c."%s" = false
      AND e."dateDeleted" IS NULL
      -- This is the programArea ID
      AND r."targetId" = :programArea
      AND c."%s" <= now()
      -- This can be used to filter by specific book types
      %s
    ORDER BY %s, title
)
SELECT *, COUNT(products) Over() total FROM products OFFSET :offset LIMIT :limit;
EOD,
    $selectCommand['select'],
    $isDeactivatedColumnName,
    $releaseDateColumnName,
    $bookTypes ?
        sprintf('AND c."%s" IN (%s)', $bookTypeOnix3DetailCodeColumnName, collect($bookTypes)->map(fn(string $bookType) => sprintf("'%s'", $bookType))->join(', ')) :
        '',
    $selectCommand['orderBy'],
), [
    ':programArea' => $programArea,
    ':offset' => $offset,
    ':limit' => $limit,
]);
```

This the simple query still but it's more efficient for what is needed. It is no longer compatible due to the changes where data is stored etc. Maybe now after what you wrote I could pick the data from the `elements_sites` table instead but I can't confirm it yet.

**Comment by brandonkelly** [comment]
Anything referencing `content`/`c` will need to be updated as that table no longer exists.

- The `title` column was moved to `elements_sites`.
- Custom fields (`$isDeactivatedColumnName`, `$releaseDateColumnName`, `$bookTypeOnix3DetailCodeColumnName`) need to be updated to pull from the fields’ `getValueSql()` methods, fetched via the field layout.

`getValueSql()` assumes that the `elements_sites` table doesn’t have an alias (or is aliased to `elements_sites` if the actual table name has a table prefix), so you’ll also need to drop the `es` alias, as well.

```php
use craft\commerce\Plugin as Commerce;

$fieldLayout = Commerce::getInstance()->getProductTypes()
    ->getProductTypeByHandle('myProductType')
    ->getFieldLayout();

$isDeactivatedField = $fieldLayout->getFieldByHandle('isDeactivated');
$releaseDateField = $fieldLayout->getFieldByHandle('releaseDate');
$bookTypeOnix3DetailCodeField = $fieldLayout->getFieldByHandle('bookTypeOnix3DetailCode');

$command = Craft::$app->db->createCommand(sprintf(<<<EOD
WITH products AS (
    SELECT DISTINCT p.id, MAX(elements_sites.title) OVER(PARTITION BY p.id) as title, %s
    FROM commerce_products as p
      INNER JOIN commerce_variants v on p.id = v."productId"
      INNER JOIN elements e on p."id" = e."id"
      INNER JOIN elements_sites on elements_sites."elementId" = e."id"
      INNER JOIN relations r on v."id" = r."sourceId"
    WHERE %s = false
      AND e."dateDeleted" IS NULL
      -- This is the programArea ID
      AND r."targetId" = :programArea
      AND %s <= now()
      -- This can be used to filter by specific book types
      %s
    ORDER BY %s, title
)
SELECT *, COUNT(products) Over() total FROM products OFFSET :offset LIMIT :limit;
EOD,
    $selectCommand['select'],
    $isDeactivatedField->getValueSql(),
    $releaseDateField->getValueSql(),
    $bookTypes ?
        sprintf('AND %s IN (%s)',
            $bookTypeOnix3DetailCodeField->getValueSql(),
            collect($bookTypes)->map(fn(string $bookType) => sprintf("'%s'", $bookType))->join(', ')) :
        '',
    $selectCommand['orderBy'],
), [
    ':programArea' => $programArea,
    ':offset' => $offset,
    ':limit' => $limit,
]);
```

**Comment by segidev** [comment]
@brandonkelly Thank you 🙏 I will give it a try
