### ISSUE TITLE
[5.x]: Nested entries - Creating a draft is not adding the card

### ISSUE THREAD

**Issue by rgauthier4c4** [craftcms/cms#16282]
### Description
In a matrix field, if I create a nested entry and exit the panel, the new drafted card isn't added to the field. 

And if the nested entry have a required field, an validation error will appear on publishing and the drafted field will now be added to the matrix field.

Here's a video of he problem : https://www.gauthier-robin.com/uploads/craftcms/draft-not-added.mov

### Steps to reproduce

1. Create a matrix field with an entrytype with a required field
2. In the section with the field, create a new block and when the panel open, close it without filling the required field.
3. The list should be empty
4. Try to publish the changes
5. A validation error appears and the entry draft is now shown

### Expected behavior
The block list should refresh when the panel is closing

### Actual behavior
The draft is invisible until the error is displayed

### Craft CMS version

5.5.5

### PHP version

8.2

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR for this.

To clarify, when you create an unsaved draft (a draft that hasn’t been edited in any way, just initialised and then left untouched), that draft shouldn’t show when you reload or attempt to save the owner element. It’ll eventually be cleaned out by the garbage collection. If you initialise a new nested element, make any changes, and close the slideout without saving, that element shows in the field value straight away.

**Comment by brandonkelly** [comment]
Craft 5.5.6 is out with that fix. Thanks again!
