### ISSUE TITLE
[5.x]: Order query not following ASCII Rules

### ISSUE THREAD

**Issue by AmarHuda1** [craftcms/cms#16286]
### Description
I have a website that is being upgraded from Craft CMS v3 to v5, and it seems the new version order query is not following ASCII order for special characters. I noticed this issue when querying a list entry in GraphQL. Some special characters always appear at the top of others, without considering their ASCII values. Here is the result of my GraphQL query when I try to sort an entry by the sortParam field with the order set to ASC:
`{
  "data": {

    "entries": [
      {
        "sortParam": "bags,Backpack"
      },
      {
        "sortParam": "bags,Bags - 30x30 to 60x30"
      },
      {
        "sortParam": "bags,Bags - 30x30 to 60x30"
      },
      {
        "sortParam": "bags,Bags (Inner Pocket) - Up to 30x30"
      },
      {
        "sortParam": "bags,Clutch Bag / Purse"
      },
      {
        "sortParam": "bags,Luggage (Nested) - Size <30\""
      }
    ]
  }
}`

As you can see, the order for alphabetical characters is preserved, but there seems to be an issue with the special characters.

### Steps to reproduce

1. Create some entries with titles starting with special characters, such as -, (, #, etc.
2. In the section, try ordering by title in ascending order.
3. You will notice that special characters like the dash (-) appear at the top of the open bracket (() and hashtag (#) when compared to their [ASCII values ](https://www.cs.cmu.edu/~pattis/15-1XX/common/handouts/ascii.html).
<table>
  <tr>
    <th>Character</th>
    <th>Decimal Value</th>
  </tr>
  <tr>
    <td>Dash (<code>-</code>)</td>
    <td><strong>45</strong></td>
  </tr>
  <tr>
    <td>Open Bracket (<code>(</code>)</td>
    <td><strong>40</strong></td>
  </tr>
  <tr>
    <td>Hashtag (<code>#</code>)</td>
    <td><strong>35</strong></td>
  </tr>
</table>

### Expected behavior
Looking on my gql query i expect the result to be
`{
  "data": {

    "entries": [
      {
        "sortParam": "bags,Backpack"
      },
      {
        "sortParam": "bags,Bags (Inner Pocket) - Up to 30x30"
      },
      {
        "sortParam": "bags,Bags - 30x30 to 60x30"
      },
      {
        "sortParam": "bags,Bags - 30x30 to 60x30"
      },
      {
        "sortParam": "bags,Clutch Bag / Purse"
      },
      {
        "sortParam": "bags,Luggage (Nested) - Size <30\""
      }
    ]
  }
}`

### Craft CMS version

Craft CMS 5.5.0.1

### PHP version

8.2

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch! What’s your database type and version, and what charset and collation are you using?

**Comment by AmarHuda1** [comment]
I am using MySql v.8.0.35
Charset: utf8mb4
Collation: utf8mb4_0900_ai_ci

**Comment by i-just** [comment]
Thanks! 

The sort order is based on the collation used by your database tables. The `-` being returned before `(` is consistent with the `utf8mb4_0900_ai_ci` collation for MySQL 8.x. 

`utf8mb4_0900_ai_ci` collation’s comparison is more advanced than e.g. `utf8mb4_general_ci` (and recommended for MySQL 8.x). There’s an overview table near the bottom of [this article](https://kedar.nitty-witty.com/blog/mysql-8-utf8mb4_0900_ai_ci-collation-confusion) that compares those two example collations.

[This article](https://www.coderedcorp.com/blog/guide-to-mysql-charsets-collations/) explains a bit more about differences in MySQL collations.
You can find more detailed info on differences in collations on the [MySQL website](https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-sets.html).

Finally, [this issue](https://github.com/craftcms/cms/issues/16043) is not about the ordering problem, but it does highlight how your database charset can influence the results of a query, so I thought you might find it helpful.

I hope this helps!

I’ll close this now, but feel free to reach out if you run into any further issues.
