### ISSUE TITLE
[5.x]: Changes in matrix blocks in card view are not reflected in the live preview

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#16295]
### Description

Very similar issue to https://github.com/craftcms/ckeditor/issues/331, but with Matrix fields.

Matrix fields set to cards view will not show any changes in the live preview until you click on save in the popup. Here's a screen recording:

https://github.com/user-attachments/assets/ab46617b-199f-4c16-a77e-2cfbd95dd045

Again, this is understandable from a technical perspective, but is broken from an author's point of view.

It's even worse when you have nested matrix fields set to cards view. In this case, you need to click two levels deep and save two levels of popups every time you want to actually see your changes.

### Steps to reproduce

See above.

### Expected behavior

For the live preview to be useful, it needs to take all changes into account, including draft changes in a popup. For an author, it's not reasonable behaviour that _some_ changes are not immediately reflected in the live preview, regardless of the underlying technical limitations.

### Actual behavior

The live preview doesn't take into accounts drafts in nested entries, despite being intended to _show_ an author their current draft on the live site.

### Craft CMS version

5.5.5

### PHP version

8.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for the feedback. It’s working as expected, but I see your point.

I went ahead and got provisional changes to start showing up when previewing owner elements, for both Addresses and Matrix fields, for Craft 5.6. (a14ffb1747a2c8ec7668dd7a8ed66898247a25e7)

**Comment by MoritzLost** [comment]
@brandonkelly That's great, thanks Brandon!

**Comment by brandonkelly** [comment]
Craft 5.6.0 is out with that change! 🎉

**Comment by BryceBubbles** [comment]
@brandonkelly Would it be possible to apply this fix to other relationships like the Entries field?

We've found that many situations call for reusable content and being able to add, remove and re-add blocks of content, which Matrix doesn't cover. It's unfortunate that this comes with a degraded live preview experience.

**Comment by brandonkelly** [comment]
@BryceBubbles Not sure about that one since the edits on the related entry aren’t necessarily related to the edits on the previewed entry.

It will be solved with content releases, though (#8941).

**Comment by BryceBubbles** [comment]
@brandonkelly Ok thanks, content releases are going to be great!

**Comment by BryceBubbles** [comment]
> Thanks for the feedback. It’s working as expected, but I see your point.
> 
> I went ahead and got provisional changes to start showing up when previewing owner elements, for both Addresses and Matrix fields, for Craft 5.6. ([a14ffb1](https://github.com/craftcms/cms/commit/a14ffb1747a2c8ec7668dd7a8ed66898247a25e7))

Hi @brandonkelly, are you aware of any reason why provisional changes wouldn't be showing when a Matrix is displayed as cards? I have it working in a Craft 5.7.5 Solo instance, but in a different Craft 5.7.5 Pro with multiple sites it's not. If there's no obvious issue I'll dig deeper.

**Comment by brandonkelly** [comment]
@BryceBubbles There should definitely not be any differences between Solo and Pro editions when it comes to displaying Matrix content. Feel free to send your database backup and Composer files over to support@craftcms.com, and point out where the issue is occurring, and we can help look into it from there.
