### ISSUE TITLE
[5.x]: `z-index` bug with autosuggest inputs

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/cms#16298]
### What happened?

When an autosuggest input appears near the bottom of a page that occupies the full height of a window, I'm observing a visual "stacking" glitch with a couple elements in the footer:

![z-index stacking bug](https://github.com/user-attachments/assets/4c945ac0-2044-45cd-9b85-e49194a9c646)

- The edition badge appears to use `relative` positioning without any corresponding `top` / `left` / etc. values;
- The  "Go" arrow is given an explicit z-index by the browser [due to it's use of `opacity`](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index/Stacking_context);

### Craft CMS version

 5.5.4

### PHP version

8.2

**Comment by brandonkelly** [comment]
Fixed in 5.5.6.1!
