### ISSUE TITLE
[3.x]: Re-Configuration of Asset Fields leads to deleted assets in AWS

### ISSUE THREAD

**Issue by mnlmaier** [craftcms/cms#16305]
### Description
I don't know if this is a bug or if this is expected behavior, I still wanted to report to at least understand why this is happening.

Recently, we re-configured the restricted location of some asset fields. Basically, we went from `{site.group}/asset.ext` to `{site.group}/{site.name}/asset.ext`. So far, so good.

After deploying, I was able to observe two things:
- Assets did not move around. No big deal, I think I only need to trigger re-saves?
- Some assets (not all, seems to be random) were deleted from our AWS S3 bucket 3 days after the deployment. I wasn't really able to figure out what went wrong there. **Those assets were not moved at all, just deleted.**

Luckily, our bucket is versioned, so we can programmatically remove all delete markers and restore the assets with rather minimal effort. I wasn't able to spot a pattern in the asset deletions, it also seems to be limited to a certain time, maybe some kind of automation which we are not aware of. No deployment or development task was triggered when the deletion markers were created.

First i thought that someone accidentally re-saved an entry, but even among entries, assets seem to be half gone and half there.

For the time being, we will be keeping a list of all deletion markers (for pattern-spotting later on) and remove them from the bucket afterwards, so that the assets will be restored again. Still, this only solves the immediate problem. As I'd like to get to the bottom of this: Do you guys know of any reason why this might be happening?

I know it's a wild guess without any further information, but currently, I don't really know where to start investigating this. The logs didn't contain anything relevant, either.

As we will migrate the project from Craft 3 to Craft 5 in the coming weeks, I want to make sure that we'll know what's going on there.

### Steps to reproduce

1. Re-Configure asset field (restrict to path, adjust path)
2. Deploy
3. Observe AWS assets being randomly deleted some days later (deployment on Thursday, deletion markers set on Sunday 00:05 am)

### Expected behavior
1. Assets shift around, nothing gets deleted

### Craft CMS version

Craft Pro 3.9.5

**Comment by brandonkelly** [comment]
Changing an Assets field’s location settings won’t have any immediate impact on existing assets. They will only get relocated based on the new setting value when an entry is saved. So I think the fact that you recently saved that setting is just a red herring.

Do you have multiple Craft installs/environments pointing to the same S3 bucket? If so, that could explain the behavior. For example, if you have a dev/staging environment that also uses that S3 bucket, and has the new Assets field settings, when an entry is saved in that environment, it will cause the asset to be relocated. Only that environment will actually know about the move though, so to other environments, it will just look like the file was mysteriously deleted on S3. (The assets will “come back” if you run the Asset Indexes utility, however they will become new asset elements; any relations you had to the old assets will not map over to them.)

If that’s the case, the answer is to stop doing that, and give each environment its own dedicated S3 bucket or other asset storage location.

**Comment by mnlmaier** [comment]
@brandonkelly — Thanks for the very quick reply, very much appreciated!

Also thank you from confirming my thinking that assets will only get moved around when entries are actually saved.

I was also thinking about other environments influencing the asset storage (yes, we do have one bucket, but are currently in the process of changing that). Still, we're talking too many **random** assets here for this to be the root cause (like, deletion of 4 out of 12 images in a gallery in the same entry, only referenced there), also, most deletion markers were set on a Sunday night when none of the other devs was working on any environment. I suspect some kind of automated task here (because, we're not talking dozens, but hundreds of assets all deleted in the timespan of minutes), but still, I'm very confused when it comes to the randomness of the issue.

That's why I wanted to raise an issue, not because I necessarily think that this might be Craft's fault or a bug, but I figured maybe you can think of something which could randomly trigger lots of asset resaves — I had some kind of transform generation in mind, but even then, assets should stay put unless the entry is saved.

Also I'm still confused why assets have been **deleted** (ie marked with a deletion marker) instead of moved around — I'd get it if they would be changing folders, because this is what we were aiming for anyway.

We'll try to investigate more and pull all the deletion markers into a JSON file, to maybe spot a pattern, and will update this issue if we find one.

Again, thanks for the quick reply!

**Comment by mnlmaier** [comment]
Following up on this: We just had a deep dive into this. The large amount of Delete Markers is caused by the fact that, in a versioned S3 Bucket, AWS does not actually **move** the asset, but copy it to another folder, adding a Delete Marker to the orginal asset.

So far, so good. Though it seems like somewhere in between, things go wrong — because the asset did not "arrive at its destination" and is just "gone", both in the Craft Asset Management and in AWS as well 🤔 The asset is available in Craft, but cannot be displayed (no preview image, 404 when opening the assets aws link)

We'll continue to investigate furher in a cloned bucket, I'll update this is as soon as I learn more.

**Comment by brandonkelly** [comment]
> (like, deletion of 4 out of 12 images in a gallery in the same entry, only referenced there)

That rules out it being in response to an entry being saved, I think. If this were caused in reaction to an entry being saved, you would expect that all 12 assets would be handled in the same way.



> Also I'm still confused why assets have been **deleted** (ie marked with a deletion marker) instead of moved around

To be clear, you’re talking about within S3 right? (Seems so, based on your follow up comment.)

That would also rule out it being due to another environment. If another environment needed to move an asset, the S3 object would get moved, not deleted.

Assets fields never delete assets; only create them. The only way to actually delete assets in Craft (out of the box) is via the “delete” action within the Assets index page.

**Comment by mnlmaier** [comment]
@brandonkelly — True, and that's what confuses me. I would have guessed that, probably, after re-configuring our asset fields, some files get moved around (which creates a delete marker on the original file in AWS), but are — for some reason — not updated in Craft. 

For example, all those images in the (redacted) screenshot below were uploaded at the same time, and are referenced in the same entry. They're basically a series of photos used in a gallery.

![Image](https://github.com/user-attachments/assets/e72c546f-9e72-47df-8262-c80f42fd19c3)

Though, the last of them, for some reason, has received a delete marker in AWS. I think we might just end up restoring all delete markers of broken files (which are still referenced in Craft) on the live bucket, which will probably lead to some files being duplicated across different folders (in case they were successfully moved already) — still better than some files being broken for our users.

I was thinking of manually updating all asset indexes in the Craft instance (never done that), but at this point, I'm afraid it'll complicate things even more.

**Comment by mnlmaier** [comment]
@brandonkelly — Another follow up:

I have a list of all deletion markers in AWS (pulled from AWS), which includes this (seemingly deleted) example:

### Deleted instance:
```
{
        "Owner": {
            "ID": "...redacted..."
        },
        "Key": "images/Redacted Folder/RedactedFilename_13.jpg",
        "VersionId": "A28UUiP3rTQZUyyA...",
        "IsLatest": true,
        "LastModified": "2024-12-07T23:03:44+00:00"
    },
```

Also, i pulled a list of all active assets in the S3 bucket:

### Active instance:
```
{
        "ETag": "\"redacted\"",
        "Size": 1502509,
        "StorageClass": "STANDARD",
        "Key": "images/Redacted-Folder/Redacted-Folder-DE/Filename_13.jpg",
        "VersionId": "GlCeUqqTV2ZauWZqko3redacted",
        "IsLatest": true,
        "LastModified": "2024-12-07T23:03:43+00:00",
        "Owner": {
            "ID": "43e1394f94f3669d99d0ababc5aa042redacted"
        }
    },
```

**The new folder structure matches our asset field re-configuration**. We also have older deletion markers from back when we re-sorted sites into different groups, when the asset path still included `{site.group}` as a variable.

So it seems like there WAS some movement going on after all. The weird thing is, again, not all of the entry's images have been moved around.

To get to the bottom of this: I checked the live database, and the asset had the incorrect `folderId` assigned to it. Once i updated the folder ID to match the AWS key, the asset showed up:

![Image](https://github.com/user-attachments/assets/ae8f251d-eaba-42a6-b2fc-22b3f02e9cd4)

I know, lots of redactions going on in the screenshot, but there's personal data on there :D 

So it might have to do something with moving after all.

Just a guess, I currently have no confirmation that this is the case: Could it be that, if an asset is referenced across multiple entries, the references in other entries are not updated? Wouldn't make sense tho, because once the correct `folderId` is set on the asset, things should go fine, right?

**Comment by mnlmaier** [comment]
Next follow up: I wrote a quick little script to compare deletion markers and active assets, indicating a move instead of actual deletion:

```
===== Results =====
Moved Files: 51309
Truly Deleted Files: 2103
Saving results to JSON files...
Results have been saved to 'moved-files.json' and 'deleted-files.json'.
```

Also, by far not all of the 51k files are broken in Craft, it's just some of them for some reason. This is AWS data, so it also shows assets which were moved and stored in craft correctly.

Truly deleted files can very well be files which were deleted intentionally.

Something was moving the assets around, and in return, the asset index was not updated. We're running a manual asset index update on one of our stages (granted, still using the same bucket), we have about 150k assets so this will take a while. I'll report back if that fixes the immediate issue on stage — if it does, we will trigger the asset indexing update on live, too.

Still doesn't answer the question what actually triggered the files to be moved without any re-saves going on (at least none we know of) — also only partially for multiple files in same field.

**Comment by mnlmaier** [comment]
Update: I ran the Asset Re-Index task on the console and several thousand assets in, I'm getting:

```
error: Error executing "HeadObject" on "https://redacted.s3.eu-central-1.amazonaws.com/images/redacted/redacted.jpg"; AWS HTTP error: Client error: `HEAD https://redacted.s3.eu-central-1.amazonaws.com/images/redacted/redacted.jpg` resulted in a `400 Bad Request` response  (client): 400 Bad Request (Request-ID: SD0WDNF0VMWDY9AC) - 
```

Could a broken asset be the reason that the asset index seems so far off?

**Comment by mnlmaier** [comment]
@brandonkelly — I need to circle back to this, with another question.

I tried running the Asset Index Rebuild on a test environment, with hopes of updating the moved files to their correct target destinations, so that they correctly show up in Craft again. Keep in mind that this works when updating the folderId in the Database by hand.

Sadly, craft only adds new files for moved files instead of updating the existing ones. File names stayed the same.

Is there anything I'm overlooking, shouldn't the assets' folder references be updated if the filename stays the same instead of creating new assets?

**Comment by mnlmaier** [comment]
Following up on this again: We will now, for the time being, resort to:

- Restoring the Field Configs
- Removing all Delete Markers of the initially moved files since the initial deployment of the config change (about 1 week ago) -> This will lead to duplicates because assets were partially moved into the desired subfolders, we'll delete those later -> Still, all assets will be available again and all authors will be able to access them (because the field folder restriction will be set to the old path, too)
- Since I am not certain that the Asset Index Rebuild works as expected, we will probably have to do some adjustments for the `folderId`s by hand

@brandonkelly — Do you have any indication on what will happen if craft tries to move the file "back" into the original folder when it's already there, since we will be reverting the field configs? Should work, right?

I still struggle to understand what initially caused the problem at all. It all seems to come down to Craft moving assets in AWS while not updating the Asset Index correctly (folderId), I'm still figuring out what we did wrong.

---

Alternatively, we could also use the backup which we created of the initial bucket before we deployed, create a new bucket from it, and manually migrate the new assets which were uploaded in the meantime. This might be better — once connected, would craft pick up the new assets automatically when uploaded / migrated directly into the new AWS bucket? We would have to do some database changes ourselves tho, since Craft tries to find some assets from the new folders which would then be not available.

**Comment by brandonkelly** [comment]
> some files get moved around (which creates a delete marker on the original file in AWS)

Ah ok, then ignore the second part of my [previous response](https://github.com/craftcms/cms/issues/16305#issuecomment-2537341648).

> Just a guess, I currently have no confirmation that this is the case: Could it be that, if an asset is referenced across multiple entries, the references in other entries are not updated? Wouldn't make sense tho, because once the correct `folderId` is set on the asset, things should go fine, right?

Yeah no… entries only have a reference to the asset ID, not its location. You could move an asset to an entirely different volume from the Assets index page and it wouldn’t break any existing entry relations.

> Sadly, craft only adds new files for moved files instead of updating the existing ones. File names stayed the same.

Yeah I mentioned that would happen in my [first reply](https://github.com/craftcms/cms/issues/16305#issuecomment-2532620361).


> Next follow up: I wrote a quick little script to compare deletion markers and active assets, indicating a move instead of actual deletion:

> Also, by far not all of the 51k files are broken in Craft, it's just some of them for some reason. This is AWS data, so it also shows assets which were moved and stored in craft correctly.

This is all pointing to the assets being moved from outside of this Craft install/environment. Whether that’s directly on S3 or via an S3 client, or another Craft install/environment.

My guess is that there is a dev environment somewhere that has an older version of some of these entries with only a subset of the assets selected, which is connected to the same S3 bucket, and the entries got resaved after the new Assets field config was pulled down. The new restricted asset location was applied to _each_ of the assets that were selected for the entry in that environment, which caused _some_ of the selected assets to go missing for your production environment.

**Comment by mnlmaier** [comment]
@brandonkelly — Thanks for your response! That kind of confirms my toughts, too. 

> Yeah no… entries only have a reference to the asset ID, not its location. You could move an asset to an entirely different volume from the Assets index page and it wouldn’t break any existing entry relations.

Thanks for confirming that, for me that's also expected behavior.

> Yeah I mentioned that would happen in my https://github.com/craftcms/cms/issues/16305#issuecomment-2532620361.

Yep, you're right, sorry — lots of things going on last week, haha. I overlooked that.

So for now, I will do the following:

- Duplicate the bucket first
- Remove all deletion markers, even if that causes duplicates for files which had already been moved
- Revert the commit which re-configured the asset fields (to allow author access to all files again, since only some where moved to the new restricted locations which are subfolders of the old configuration, so at least access for authors should be possible again)
- Deal with duplicates afterwards, need to figure out the best way to do this. I don't know if Craft will just "move them back" or if it would be better to update the `folderId` of the assets to point to the original file (we know the folders which include duplicates, so that should not be too hard)

Good thing we're working with S3 here. Turns out the initial problem was already implemented 2 or 3 months back when we 
adjusted site groups, it only just became obvious when we adjusted restricted locations for the authors in the field config.

---

I'm just thinking: What would be the best way to create new and correct asset indexes for all environments, without breaking related assets in entries?

**Comment by brandonkelly** [comment]
> I'm just thinking: What would be the best way to create new and correct asset indexes for all environments, without breaking related assets in entries?

I would just focus on cleaning up your production environment. Once that’s looking good, you can restore a production database backup on your other environments, along with S3 files, so everything is in sync. And then just make sure that only your production environment has access to the S3 bucket going forward.
