### ISSUE TITLE
[5.x]: z-index problem Safari 18.1.1, macOS 15.1.1 Feed-Me Plugin

### ISSUE THREAD

**Issue by phelex** [craftcms/cms#16319]
### Description
dropdown .selectize-dropdown-content gets rendered underneath following input.
https://share.cleanshot.com/mB5hGlZt

### Steps to reproduce
Use Safari to edit Feed-Me mapping of imported data. … feed-me/feeds/map/

### Expected behavior
works as expected on Edge and Firefox

### Craft CMS version

5.5.6 (Solo)

### PHP version

8.3.14

### Operating system and version

Linux 6.8.0-47-generic

### Database type and version

MariaDB 10.11.10

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- Button Box 5.0.0
- CKEditor 4.4.0
- Contact Form 3.1.0
- Elements Panel 3.0.0
- Empty Coalesce 5.0.0
- Feed Me 6.6.1
- Minify 5.0.0
- Scheduler 4.0.0
- Sprig 3.5.1
- Typogrify 5.0.1
- Vite 5.0.1

**Comment by i-just** [comment]
Hi, thanks for getting in touch! If you update to Craft CMS v5.5.6.1, the problem should be resolved.
