### ISSUE TITLE
[5.x]: Craft 5 upgrade for matrix changes sort order of migrated matrix blocks

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#16314]
### Description

During the Craft 5 upgrade, all matrix block types in all matrix fields are converted to entries. The matrix block types setting is replaced by an entry type selection. We found that during this update, the existing order of the matrix blocks is not maintained. After the update, the entry types selected in the matrix field are in a (seemingly) random order, instead of the order the matrix blocks had. This is bad for the author experience, as you usually put more commonly used matrix blocks at the top, and/or order them in a way that makes sense for the given block types.

### Steps to reproduce

1. In a Craft 4 site, create a Matrix field with several matrix block types. Note the existing order of the block types.
2. Upgrade the site to Craft 5.
3. Check the order of the migrated entry types in the matrix field.

### Expected behavior

The order should be preserved during the upgrade.

### Actual behavior

The order is not preserved, the blocks are shuffled around.

### Craft CMS version

5.5.5

### PHP version

8.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
I’m not able to reproduce that. Can you send your **Craft 4** database backup and **Craft 5** Composer files into support@craftcms.com, and point us to an entry where the block order has changed? support@craftcms.com

**Comment by MoritzLost** [comment]
@brandonkelly Done! Let me know if you need anything else.

**Comment by brandonkelly** [comment]
Sorry, I thought you were talking about nested entries within Matrix fields. For posterity, this is actually about entry _types_ within the Matrix field settings.

Fixed now for the next release!

**Comment by MoritzLost** [comment]
@brandonkelly Thanks! Sorry for the ambiguous description.

**Comment by brandonkelly** [comment]
Craft 5.5.7 is out with that fix! Thanks again.
