### ISSUE TITLE
[5.5.6]: CSS bugs with status toggle and Commerce prices

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#16312]
### Description
Just a heads-up (images taken from Discord comments): 

![Image](https://github.com/user-attachments/assets/0404c595-6598-4dab-9b59-85155eddf701)
![Image](https://github.com/user-attachments/assets/b2d441f2-48ba-4d49-844c-646fcb63704f)

### Craft CMS version

5.5.6

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 5.5.6.1 is out now with a fix.
