### ISSUE TITLE
[5.x]: Slug Duplication Issue in Entry Type with Dynamic Title and Link Field

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#16322]
### Description

I am encountering an issue with slug duplication in Craft CMS 5 (5.5.3). The problem arises in an Entry Type that I use to create Call To Action (CTA) entries. This Entry Type is utilized both within a Structure and a Matrix field.

#### Entry Type Details:
- **Fields**:
  - `linkUrl` (required, Link field)
  - `customTitle` (optional, Plain Text field)
- **Default Title Format**:
  ```
  {{ customTitle ?: (linkUrl.type == "entry" ? linkUrl.element.title : linkUrl) }}
  ```

#### Observations:
1. When only the `linkUrl` field is populated, and it points to another Entry, the slug of the pointed Entry is used as the slug for the current Entry.
2. This can lead to slug conflicts if the pointed Entry's slug matches an existing slug in the system. In such cases:
   - On save, the current Entry's URL can conflict with an existing one.
   - The Entry with the original slug becomes inaccessible as the first-defined URL takes precedence.
3. If the slug of the pointed Entry changes, the original slug remains in use for the current Entry. However:
   - If the original slug is reverted on the pointed Entry, the system allows duplicate slugs, creating two Entries with the same slug.

#### Additional Issue:
When the option **"Show the Slug field"** is disabled for this Entry Type:
- The previous slug is still retained in memory.
- This means disabling the slug field does not resolve the slug conflict issue.

---

### Steps to reproduce

1. Create a new Entry using the affected Entry Type and populate only the `linkUrl` field, pointing it to an existing Entry.
2. Save the Entry.
3. Attempt to save another Entry with the same slug or change the slug of the pointed Entry to create a conflict.
4. Optionally, disable the "Show the Slug field" option for the Entry Type and repeat the process.

### Expected behavior

- The system should ensure unique slugs for all Entries, even when the slug is dynamically generated from a linked Entry.
- Disabling the "Show the Slug field" option should either:
  - Prevent slug conflicts entirely, or
  - Provide a fallback mechanism to ensure slug uniqueness.

### Actual behavior

- Slug conflicts occur when the linked Entry's slug matches an existing one.
- Duplicate slugs can exist in the system, causing URL conflicts.
- Disabling the slug field does not prevent slug conflicts, as the previous slug is still retained.

### Craft CMS version

5.5.3

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out!

Slugs don't have to be unique, the URIs have to (providing element is set to have URLs); if the URI pattern ensures uniqueness, having more than one entry with the same slug is fine.

If, during the validation, it turns out that the URI wouldn’t be unique, the slug will be auto-incremented up to the value specified by the `maxSlugIncrement` setting.

If `maxSlugIncrement` limit is reached, then the entry will be saved as disabled; if you then try to enable it, you’ll get an error message under the slug field saying that the URI is not unique.

If the slug field is set not to show, then you’ll get the error in the error summary but no chance to correct it unless you know which fields to manipulate based on the URI format. We’ll discuss this case internally.

**Comment by romainpoirier** [comment]
Thank you for your response.

I’ve noticed that in all previous Craft projects I’ve worked on, slugs were automatically incremented when a duplicate was detected. This behavior ensured no conflicts occurred and allowed queries like `craft.entries.slug('<slug>').one()` to function properly without issues.

In the current scenario, involving a combination of a Link field and nested Matrix field, this auto-increment behavior seems to no longer apply. As a result, I no longer benefit from slug auto-incrementation.

This is particularly problematic in cases where I use the slug to load specific routes, such as contextualizing URLs for pages within Channels. Is it expected that slug auto-incrementation is not applied in this case? Is there a configuration setting available to enforce slug incrementation?

While I understand that I could refine my queries—for example, `craft.entries.slug('<slug>').type('not linkType').one()`—this solution is not ideal for complex route contextualization.

**Comment by i-just** [comment]
I tested the auto-increment on a root entry yesterday and that works as expected. I just tested it with matrix entries, and it also works as expected - the slug gets auto-incremented when the matrix field is set to have URLs (“Entry URI Format” for the field is specified). Does the matrix field you use in this case, have “Entry URI Format” for the site you’re editing?

**Comment by romainpoirier** [comment]
### Additional Test Case

Here is another test case that might help illustrate the issue:

1. I create an Entry in a Channel, which contains a Matrix field. 
2. Inside this Matrix, I add a sub-block of type Matrix, which contains a Link field allowing me to select an Entry.

#### Setup:
- I set the slug of the main Entry to `champagne-extravagance`.
- In the Link field of the Matrix, I select another Entry with the slug `champagne-extravagance-collection`, but its **Title** is set to `Champagne Extravagance`.

#### Title Format:
The **titleFormat** for the Matrix Entry is defined as follows:
```twig
{{ customTitle ?: (linkUrl.type == "entry" ? linkUrl.element.title : linkUrl) }}
```

#### Behavior:
If I only define the `linkUrl` field and point to the page with the title `Champagne Extravagance`, the **slug** of the Matrix block containing the Link field inherits the slug `champagne-extravagance` (derived from the title of the page it points to).

This results in a **duplicate slug** (`champagne-extravagance`), without any auto-incrementation. This is problematic because the main Entry and the Matrix block now share the same slug.

#### Example Issue in Twig:
When querying in Twig using:
```twig
craft.entries.slug('champagne-extravagance').count()
```
The result returns **two entries**:

```json
[
    {
        "id": 711149,
        "slug": "champagne-extravagance",
        "type": "link",
        "section": null
    },
    {
        "id": 584303,
        "slug": "champagne-extravagance",
        "type": "webpage",
        "section": {
            "id": 3,
            "structureId": null,
            "name": "Stories",
            "handle": "stories",
            "type": "channel",
            "maxAuthors": 1,
            "maxLevels": null,
            "enableVersioning": true,
            "propagationMethod": {
                "name": "All",
                "value": "all"
            },
            "defaultPlacement": "end",
            "previewTargets": [
                {
                    "label": "Primary entry page",
                    "refresh": "1",
                    "urlFormat": "{url}"
                }
            ],
            "uid": "8a9773a5-118d-4007-a7e7-06706b754157"
        }
    }
]
```

### Key Issue:
- The slug `champagne-extravagance` is duplicated without auto-incrementation.
- This creates conflicts when working with slugs programmatically, such as querying `craft.entries.slug('<slug>').one()`.

Is there a specific configuration that enforces slug auto-incrementation in such cases? Or is this behavior expected when slugs are dynamically generated in this way?

### Screenshots:
<img width="1695" alt="Image" src="https://github.com/user-attachments/assets/0085cfa6-982c-4a96-a27b-3f719fd8c69a" />
<img width="1694" alt="Image" src="https://github.com/user-attachments/assets/9a8f7863-e200-4ea4-a377-1f700d80d1b6" />
<img width="1694" alt="Image" src="https://github.com/user-attachments/assets/6e737505-a599-42ae-9135-0caf5faf93fd" />

**Comment by i-just** [comment]
> Is there a specific configuration that enforces slug auto-incrementation in such cases?

Yes, the slug (both auto-generated and not) will get auto-incremented in a matrix field’s entry when that matrix field is set to have URLs.

If you want to keep your matrix field entries without URLs and you want to query entries by slug, you can modify your query and add `.section('*')`. This way, you’ll be searching by slug but only among the entries that belong to any section (matrix field entries don’t belong to a section).

**Comment by romainpoirier** [comment]
Thank you for the tip about using `.section('*')`—it should do the trick!

However, regarding this:  
> Yes, the slug (both auto-generated and not) will get auto-incremented in a matrix field’s entry when that matrix field is set to have URLs.  

Does this mean there shouldn’t be any duplicate slugs, and that slugs are automatically incremented in principle? Based on the example I previously shared with you, I encountered identical slugs. Could this be a bug?

**Comment by brandonkelly** [comment]
@romainpoirier Only if your Matrix field is configured with a nested entry URI format, which contains `{slug}`.
