### ISSUE TITLE
[5.x]: Status labels cut off in some contexts / widths in 'card view'

### ISSUE THREAD

**Issue by iparr** [craftcms/cms#16325]
### Description

See screenshot:

<img width="360" alt="Image" src="https://github.com/user-attachments/assets/6610c6dd-0eaa-4ae0-b65e-b8df1646634b" />

This is the candidate for improvement:

```
.card .card-content .card-body>:not(:has(>.no-truncate)) {
    --max-lines: 2;
    margin: 0;
    max-height: calc(var(--lh)* var(--max-lines));
}
```

### Steps to reproduce

1. Edit a document without saving so that 2x 'labels' appear
2. Switch to 'card view' in entry listing
3. Resize viewport to make the labels 'wrap'

### Expected behavior

Not to hide.

### Craft CMS version

5.5.56.1

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 5.5.7 is out with that fix. Thanks again!
