### ISSUE TITLE
[5.x]: Matrix inline max 1, min 1 not loaded if is not on the current loaded tab

### ISSUE THREAD

**Issue by stephanedemotte** [craftcms/cms#16331]
### Description

Matrix inline max 1, min 1 not loaded if is not on the current loaded tab

### Steps to reproduce

Create a matrix with inline view mode inline, max 1, min 1, put it in a tab (not the first one)

### Expected behavior

Field must load even is not on the current tab

### Actual behavior

The field doesn't load, when we save, we have an error and we have to create it "manually"

https://github.com/user-attachments/assets/0cd8a033-ebda-4055-9bf9-67d5ae9612c7

### Craft CMS version

5.5.6.1

### PHP version

8.2

### Operating system and version

Mac

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Just tested this locally and it’s working as expected:

https://github.com/user-attachments/assets/936f32be-1a3a-42c8-9536-889944a72598

Are you getting any JavaScript errors on the page?

**Comment by stephanedemotte** [comment]
Yes and you're right it's not happening every time, sometimes the matrix load correctly, but sometimes i've got this.

https://github.com/user-attachments/assets/417490f9-246a-45cd-81a7-c25630952dc0

**Comment by brandonkelly** [comment]
Can you click on that first one (`matrix/create-entry`) and post the Response details?

**Comment by stephanedemotte** [comment]
<img width="804" alt="Image" src="https://github.com/user-attachments/assets/5fc1f077-4122-4075-82d1-094517b50e05" />

**Comment by brandonkelly** [comment]
Any chance you can send me a database backup and your Composer files? support@craftcms.com

**Comment by stephanedemotte** [comment]
@brandonkelly done

**Comment by brandonkelly** [comment]
Fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 5.5.8 is out with that fix. Thanks for all the help!
