### ISSUE TITLE
[5.x]: PHP error when eager loading an element owner that is not the same element type as the nested element

### ISSUE THREAD

**Issue by lukeholder** [craftcms/cms#16339]
### Description

The following code will cause the error:

```twig
{% set addresses = craft.addresses.with(['owner']).all() %}
```

This is due to 

https://github.com/craftcms/cms/blob/92440e9996fdd4e1bf24497e13677f19e1ba290d/src/base/NestedElementTrait.php#L42

expecting that the element type for the eager loading of the parent is the same element type as the source element.

Adding a matrix field to a category element and using this query can also cause the error:

```twig
{% set matrix = craft.entries.with(['owner']).all() %}
```

Since the category is not an entry element type.

### Steps to reproduce

Add this code to a front-end template:

{% set addresses = craft.addresses.with(['owner']).all() %}

### Actual behavior

PHP error

Related issue:

https://github.com/craftcms/commerce/issues/3817

Fixed manually in Commerce with:

https://github.com/craftcms/commerce/commit/5eacab1544f09dc7b4f5bb1808a1f7236ccdc838

### Craft CMS version

5.x

**Comment by brandonkelly** [comment]
Thank you sir! Fixed in Craft 5.5.7.
