### ISSUE TITLE
[5.x]: Slug is not generate on propagation of new entry

### ISSUE THREAD

**Issue by rgauthier4c4** [craftcms/cms#16347]
### Description
When i'm saving an entry, the slug isn't generate for the other sites available.

I have a multisite (English and French) with a section having the propagation sets to : Save entries to all sites enabled for this section.

My entrytype doesn't have the default **title** field and the title is generated from another field. (header_title)

### Steps to reproduce

1. Create a simple section in a multisite with the propagation set to all sites.
2. Create an entrytype that doesn't have the default title field and another text field as the title value
3. Create a new entry in one site. The slug should be generated
4. Switch to the other site and the entry is created without a slug. (If you resave the entry, the slug is generated correctly.)
5. If you go back to the entries listing, the slug is saved as temp_xyz

### Expected behavior
The other site slug value is generated from the first site title.

### Actual behavior
The title is created but the slug doesn't exist.

(I can provide screenshot or a video if needed)

### Craft CMS version

5.5.7

### PHP version

8.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 5.5.8 is out with that fix. Thanks again!
