### ISSUE TITLE
[5.x]: X-Robots-Tag defaults to none irrespective of config settings

### ISSUE THREAD

**Issue by nathansnelgrove** [craftcms/cms#16345]
### Description

Launched a Craft project today to find out that X-Robots-Tag is set to `none` by default in a live environment. I have not changed my config settings at all. Enabling SEOMatic changes the value to `X-Robots-Tag:all`, and I don't know why. I would prefer this setting to not be there at all, but that's just my two cents.

### Steps to reproduce

1. Launch a new website with your environment set to `production` and a default Craft config. Inspect the HTTP headers.

### Expected behavior

I kind of wonder why we need an X-Robots-Tag at all? The only reason it came up is because my SEO Guy told me he would prefer not to have them. I didn't understand his reasoning, but truthfully a bunch of this is over my head.

### Actual behavior

X-Robots-Tag defaults to `none`.

### Craft CMS version

5.4.9

### PHP version

8.3

### Database type and version

MySQL 8.0

### Installed plugins and versions

S3, SEOMatic, Formie, Retour, CKEditor, Oembed, ImageOptimize, AsyncQueue, all the latest. (Is there any easy way for me to copy and paste all the values from somewhere next time?)

**Comment by nathansnelgrove** [comment]
Ah, user error. Ignore me.

**Comment by nhyoga** [comment]
I am seeing this issue locally setting environment variable to 'production'

**Comment by brandonkelly** [comment]
@nhyoga Nothing in Craft cares what your environment is named.
