### ISSUE TITLE
2.6.2972 breaks on PHP 5.3

### ISSUE THREAD

**Issue by RitterKnightCreative** [craftcms/cms#1634]
### Description
I know, I know PHP 5.3 is basically dead but Craft's system requirements mentions it runs on 5.3 and we still have an old server on 5.3 waiting to get updated so we found this on one our installs. It was easy to patch at least...

### Steps to reproduce

1. Update Craft to 2.6.2972
2. Watch for white screen of death after it updates.

``PHP Parse error:  syntax error, unexpected '[' in craft/app/fieldtypes/AssetsFieldType.php on line 59``

https://github.com/pixelandtonic/Craft-Release/commit/b33dd9e6d8f59b8825b45e56d7f0c4b404f929cd#diff-dced90b509f052967974a34ed81c40d8R59

### Additional info

- Craft version: 2.6.2972
- PHP version: < 5.4

**Comment by takobell** [comment]
Fixed for the next Craft 2 release and those responsible have been flogged.

**Comment by takobell** [comment]
And the release: https://craftcms.com/changelog#2-6-2973
