### ISSUE TITLE
[5.x]: Conditional rule on field not working as expected

### ISSUE THREAD

**Issue by clintonbeattie** [craftcms/cms#16356]
### Description

I have a Matrix content builder with an entry type of Hero. Within Hero there is a CTA field. I have set the field Settings, for this CTA instance only, to display only when Section is 'Homepage' but is doesn't appear and likewise with other fields were this condition is set.

### Craft CMS version

5.5.5

### PHP version

8.3

### Operating system and version

Mac OS with Sonoma 14.4.1 

### Database type and version

SQL

### Installed plugins and versions

<img width="1123" alt="Image" src="https://github.com/user-attachments/assets/3d2162b9-ff6b-4d76-b530-4117e9909139" />
<img width="553" alt="Image" src="https://github.com/user-attachments/assets/ecd93c68-614d-4445-b2b2-97adbe5b6ef7" />
-

**Comment by Ticolyle** [comment]
@clintonbeattie perhaps related to #15260 and other similar discussions

**Comment by brandonkelly** [comment]
What @Ticolyle said!
