### ISSUE TITLE
[5.x]: Category setting not being saved without an error.

### ISSUE THREAD

**Issue by bob-pixeldeluxe** [craftcms/cms#16351]
### Description
I wanted to create a category which creates an dynamic background pattern which can be reused on pages. Now i want the customer to be able to use the live preview without necessarily an url. So im trying to save the category with just a template path and no url format. However after saving the category is unchanged and there is no error message. (I've solved this another way but thought I should report it)

### Steps to reproduce

1. create a category group.
2. after creation edit it and under site settings add just a template path no URI format and save.
3. check if the input was saved.

### Expected behavior
Either it should work or there should be an error that the url is required.

### Actual behavior
Input is not saved. 

### Craft CMS version

 5.5.7

### PHP version

8.2

### Database type and version

mariadb 10.4

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
This is expected behavior. The placeholder text within the “Category URI Format” column says “Leave blank if categories don’t have URLs”. If the categories don’t have URLs for a site, the Template value will be discarded.
