### ISSUE TITLE
[5.x]: Account activation redirects to /login instead of completing activation using autoLoginAfterAccountActivation

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#16357]
### Description

Under Craft CMS 5.5.3 and associated plugins (see dependencies listed below), the account activation process consistently redirects users to `/login`, regardless of previous configurations or expectations. To further investigate, I tested avoiding the 404 error in `devMode` by creating a `/login` template and adding the line `{{ d(currentUser) }}` at the start. This consistently outputs `null`, which confirms that `autoLoginAfterAccountActivation` is not functioning as expected. 

This issue occurs despite enabling the `autoLoginAfterAccountActivation(true)` configuration. The expected behavior is to redirect users to the `e-shop/account/orders` page (if logged in) or `e-shop/account/sign-in` page (if not logged in), without explicitly defining these paths. These are static paths unrelated to account activation, and this functionality worked without issue until now. Specifying the login URL via the `loginPath` configuration parameter does not resolve the problem either, and the activation process consistently redirects to `/login`.

In `devMode`, the following error appears:

```
yii\web\NotFoundHttpException: Page not found. in /var/www/html/vendor/craftcms/cms/src/web/Request.php:1412
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/web/Application.php(82): craft\web\Request->resolve()
#1 /var/www/html/vendor/craftcms/cms/src/web/Application.php(318): yii\web\Application->handleRequest(Object(craft\web\Request))
#2 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#3 /var/www/html/htdocs/index.php(12): yii\base\Application->run()
#4 {main}
```

To avoid the 404 error in `devMode`, I created a `/login` template and added the following line at the beginning of the template:

```
{{ d(currentUser) }}
```

This outputs `null`, indicating that `autoLoginAfterAccountActivation` is not working as expected.

In production mode (with `devMode` disabled), the activation request does not throw visible errors but fails silently. These are static paths unrelated to account activation, and this functionality worked without issue until now. Specifying the login URL via the `loginPath` configuration parameter does not resolve the problem either. Logs anonymized for privacy (below) show a warning indicating a possible misconfiguration or resolution error.

### Steps to reproduce

1. Enable `autoLoginAfterAccountActivation` in the Craft CMS configuration.
2. Attempt to activate a user account using the activation link sent via email.
3. Observe that users are redirected to `/login` instead of completing the activation process.
4. Check logs for relevant errors or warnings.

### Expected behavior

- Upon clicking the account activation link, the account should be activated successfully.
- If the user is already logged in, they should be redirected to `e-shop/account/orders`.
- If the user is not logged in, they should be redirected to `e-shop/account/sign-in`.
- Explicit configuration of these paths should not be necessary, as they worked without issue previously.

### Actual behavior

- Clicking the activation link redirects to `/login`, regardless of user authentication status.
- Activation does not complete successfully.
- Errors in logs suggest a request resolution issue within the Craft CMS routing system.

### Dependencies

```json
"require": {
    "craftcms/ckeditor": "4.4.0",
    "craftcms/cms": "5.5.3",
    "craftcms/commerce": "5.2.6",
    "craftcms/commerce-stripe": "5.0.4.3",
    "craftcms/element-api": "^4.1",
    "craftcms/feed-me": "6.6.1",
    "mmikkel/cp-field-inspect": "2.0.2",
    "mmikkel/retcon": "3.2.1",
    "nystudio107/craft-instantanalytics-ga4": "5.0.1",
    "nystudio107/craft-minify": "5.0.0",
    "nystudio107/craft-retour": "5.0.4",
    "nystudio107/craft-seomatic": "5.1.8",
    "nystudio107/craft-typogrify": "5.0.1",
    "putyourlightson/craft-sprig": "3.5.1",
    "spacecatninja/imager-x": "5.1.0",
    "spatie/mjml-php": "^1.2",
    "spicyweb/craft-embedded-assets": "5.4.0",
    "studioespresso/craft-dumper": "5.0.1",
    "studioespresso/craft-mailersend": "5.0.0",
    "topshelfcraft/environment-label": "5.0.0",
    "ttempleton/craft-nocache": "3.0.4",
    "verbb/abandoned-cart": "4.0.3",
    "verbb/expanded-singles": "3.0.1",
    "verbb/queue-monitor": "^2.0.0",
    "verbb/smith": "3.1.0",
    "vlucas/phpdotenv": "^5.4.0",
    "voku/html-min": "^4.5",
    "yiisoft/yii2-redis": "^2.0"
}
```

### Anonymized Logs

```
2024-12-24 12:22:35 [web.WARNING] [application] Request context: {"environment":"production","vars":{"_GET":{"code":"<activation_code>","id":"<user_id>"},"_POST":[],"_FILES":[],"_COOKIE":{"CraftSessionId":"<session_id>","_ia":"<ia_value>","CRAFT_CSRF_TOKEN":"<csrf_token>"},"_SESSION":{"error":"Erreur lors de l’activation de votre compte"},"_SERVER":{"REQUEST_URI":"/en/verifyemail?code=<activation_code>&id=<user_id>","REQUEST_METHOD":"GET","SERVER_PROTOCOL":"HTTP/1.1","CRAFT_ENVIRONMENT":"production","HTTP_HOST":"<host>","HTTPS":"on"}}}
```

### Craft CMS version

5.5.3

### PHP version

8.2.24

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
The only way I can reproduce that is if I click an activation link for a user that is already activated, in which case the expected behavior is that they’d be redirected to the login page. `autoLoginAfterAccountActivation` does not come into effect in this case, because they aren’t re-activating their account by clicking the link a second time.

**Comment by romainpoirier** [comment]
In my case, I can confirm that the user is not yet activated.  
The email address does not exist in the `Users`, including in the `Trashed` section.  
This is the first time this email address has been received, and the registration occurred directly as part of a reduced test scenario.  

Additionally, I was never redirected to `/login` until now. Currently, attempting to access `/login` results in a 404 error, as the route is both non-existent and unnecessary in my case.  
Even when explicitly defining the correct login path using `->loginPath('e-shop/account/sign-in')`, I am still redirected to `/login`, which leads to a 404. This happens even after creating a new account prior to making this change.  

If I define a route as follows:  
```php
$routes['login'] = [
    'template' => 'e-shop/account/sign-in',
];
```
the correct template is used, and the 404 error no longer occurs. However, the account is never activated, and I consistently receive the flash message: *"Erreur lors de l’activation de votre compte"* (*"Error activating your account"*), while the account remains in the `Pending` status.

I have updated from version `5.5.3` to `5.5.7`, but the issue persists.  

How can I generate the logs you need for further investigation?  
What additional information do you require to reproduce and analyze the issue?

**Comment by brandonkelly** [comment]
> The email address does not exist in the `Users`, including in the `Trashed` section.

How are you sending an activation email for a user that doesn’t exist yet?

**Comment by romainpoirier** [comment]
When I mentioned this:

> The email address does not exist in the Users, including in the Trashed section.

It was in response to this:

> The only way I can reproduce that is if I click an activation link for a user that is already activated.

What I meant was that, as part of my reduced test case, I ensured prior to registration that no user already existed for the email address in question and that no such user had already been activated.

The activation email is sent natively through a standard registration process using a POST request to `users/save-user`.

That said, after further investigation, I discovered that the issue most likely originates from a web service called during the `EVENT_BEFORE_ACTIVATE_USER`. Therefore, it is very likely that the problem does not stem from Craft CMS itself.

For now, you can close this ticket. I will reopen it if necessary. Thank you!

**Comment by brandonkelly** [comment]
Thanks for the clarification!
