### ISSUE TITLE
[5.x]: Missing address display in Craft control panel after 5.5.7 update

### ISSUE THREAD

**Issue by apitel** [craftcms/cms#16353]
### Description
When upgrading from Craft 5.5.6 → 5.5.7, the User Address field disappears in the Craft Commerce Order screen and in the Craft Users page, within the control panel. The only fields that appear where the address used to be populated is the Name and Organization. Once you click on the address, the pop-over shows the address. This behavior was verified by @AugustMiller on [Discord](https://discord.com/channels/456442477667418113/666747438794670140/1319438882957426819). 

### Steps to reproduce

1. Create a user and add an address
2. Look at the User's address page in the control panel and the address are not displayed

### Expected behavior

Full address should be displayed in User and Order screens within the control panel. 

### Actual behavior

Only name and organization are shown, as of Craft 5.5.7. 

### Craft CMS version

Craft Pro 5.5.7

### PHP version

8.3.13

### Operating system and version

Linux 5.15.0-125-generic

### Database type and version

MySQL 8.0.40

### Image driver and version

GD 8.3.13

### Installed plugins and versions

All plugins disabled

**Comment by AugustMiller** [comment]
I suspect that [this fix](https://github.com/craftcms/cms/issues/16325) has something to do with it!

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 5.5.8 is out with that fix. Thanks again!
