### ISSUE TITLE
[5.x]: German translation corrections

### ISSUE THREAD

**Issue by mprofitlich** [craftcms/cms#16354]
### Description
I found a couple of wrong translation in Craft 5. I will deviate from the standard issue structure and add a table instead. 

| Current translation  | Suggested translation | Correction | Location |
| ------------- | ------------- | ------------- | ------------- |
| Neue Eintrag | Neuer Eintrag | r is missing | Standard red button for creating a new entry |
| entwurf speichern  | Entwurf speichern  | Entwurf needs to be written with an captial E | Dropdown in red button in a not yet saved new entry |
| entwurf löschen  | Entwurf löschen | Entwurf needs to be written with an captial E | Dropdown in red button in a draft |
| Bist du &ensp;sicher, dass du […] | Bist du sicher, dass du […]  | Delete superfluos space | JS alert when deleting a draft from the entry list |
| Primäre Eintrag Seite | Primäreintrag Seite | It should be a portmanteau | Section settings › target preview › table |
| Wird verschoben… | Verschieben nach… | Now it says "being moved"; use same wording as in following dialogue | Assets › select file(s) › cog symbol |

### Craft CMS version

5.5.7

### PHP version

8.2

### Operating system and version

ddev

### Database type and version

Maria DB

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting those! They’ve each been addressed for the next Craft releases. (5755af3cca5f0dfc26ec78662a9174e4d0a252d4 + #16361)

Looks like you’re using the Swiss German (`de-CH`) language. Do you know if the following suggestions would be appropriate for German (`de`) as well?

- `Bist du sicher, dass du […]`
- `Primäreintrag Seite`
- `Verschieben nach…`

**Comment by mprofitlich** [comment]
You’re right, I’m using `de-CH`. In `de` all translations are correct, except "Primäre Eintrag Seite".

Looking at the `de` translation I see that "Move" is translated to "Verschieben…". I suggested "Verschieben nach" but "Verschieben" is better.

Thanks for incorporating my translations!

**Comment by brandonkelly** [comment]
Thanks! I’ve made those additional changes as well (#16378).

**Comment by brandonkelly** [comment]
Craft 4.13.8 and 5.5.8 are out with those fixes. Thanks again!
