### ISSUE TITLE
Sections::EVENT_AFTER_SAVE_SECTION called for each Site

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#1637]
Looks like the `Sections::EVENT_AFTER_SAVE_SECTION` is triggered once for each Site that the Section has URLs for, but the `siteId` isn’t passed into the event, which seems like an oversight?

```
        // Fire an 'afterSaveSection' event
        $this->trigger(self::EVENT_AFTER_SAVE_SECTION, new SectionEvent([
            'section' => $section,
            'isNew' => $isNewSection
        ]));
```

Expected behavior is either:

1. `Sections::EVENT_AFTER_SAVE_SECTION` is fired only once when a Section is saved
2. `'siteId'` is passed in via the `SectionEvent`

**Comment by brandonkelly** [comment]
Sections are only saved once, globally, and the `afterSaveSection` event is only fired [once](https://github.com/craftcms/cms/blob/c937404e533434d875d0dcb2cf1e465c58218379/src/services/Sections.php#L566-L569), at the end of `craft\services\Sections::saveSection()`.

**Comment by khalwat** [comment]
Confirmed; I put in `trace` logging to see what was going on; the saving of a Section was triggering the re-saving of Entries (which I'd forgotten about), and that was firing another event I was listening to.

No more bug filing until daylight hours for me.
