### ISSUE TITLE
“Can't find variable: Craft” JavaScript errors in Yii debug toolbar

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#1639]
### Description

I’m getting a bunch of JavaScript errors in my browser’s dev tools when I open the Yii debug toolbar in the detailed view. This only seems to happen if plugins are installed that register Asset Bundles.

> ReferenceError: Can't find variable: Craft

### Steps to reproduce

1. Install plugin that registers an Asset Bundle.
2. Open the detailed Yii debug info, either in the expanded toolbar or in a separate browser window (example.com/admin/actions/debug/default/index).
3. See JavaScript errors in browser dev tools.

I was able to reproduced  that issue with other plugins listed on craftcms/plugins.

### Additional info

- Craft version: 3.0.0-beta.12
- PHP version: 7.0.15
- Database driver & version: MySQL / MariaDB 10.1.21
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Where are you registering the asset bundle? From your plugin’s `init()` method? That will probably get called on Debug panel requests, which is out of the scope of the Control Panel.

**Comment by carlcs** [comment]
Yes, from the `init()` method. Only for CP requests though.
