### ISSUE TITLE
HUDs open in wrong position in Safari

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#1647]
### Description

All HUDs in the CP are shown in the top-left corner for a moment before moved into place.

### Additional info

- Craft version: 3.0.0-beta.13
- Web browser & version: Safari 10.1

**Comment by benjamindavid** [comment]
Hey @carlcs, I'm not able to replicate this on my side. Could you please point me out to a specific page where you observe this.

Just a thought but do you have any extensions installed for this browser ?
