### ISSUE TITLE
isImageManipulatable looking for sample.pdf

### ISSUE THREAD

**Issue by shoeshine** [craftcms/cms#1648]
### Description
Logs have this repeated item:
<img width="1146" alt="screen_shot_2017-04-20_at_15 24 58" src="https://cloud.githubusercontent.com/assets/2280395/25249798/36e7b064-25e1-11e7-8062-d3c09d9e8d75.png">

Line 59 of craft/app/helpers/ImageHelper.php seems to be the culprit.

```
public static function isImageManipulatable($extension)
    {
        $path = craft()->path->getResourcesPath();
        $file = $path."images/samples/sample.".StringHelper::toLowerCase($extension);

        try
        {
            craft()->images->loadImage($file);
            return true;
        }
        catch(\Exception $e)
        {
            return false;
        }
    }
```

### Additional info

- Craft version: 2.6.2973
- PHP version: 5.4.13 and 7.0.15
- Database driver & version: MySQL

**Comment by takobell** [comment]
Several places in the code that call this and only a few of them check to make sure if it's an image type first. They probably all should.  Not actually a bug, just unnecessary noise in the logs.
