### ISSUE TITLE
Feature request: Expose current version creator

### ISSUE THREAD

**Issue by mattstein** [craftcms/cms#1650]
### Description

**UX/UI issue**: the current Entry Version's creator is accessible via the EntryVersionModel (and `entryversions.creatorId` table), yet the creator's name isn't displayed anywhere in the control panel. This makes it unclear who created the current version, which seems just as important as whoever created previous revisions—each of which exposes the creator's name.

**Request**: display the current version's creator near _Version Notes_, or at least in the version menu next to the entry title.

**Bonus Request**: use friendly names rather than just usernames if they exist.

![](https://wrkbin.com/raw/creator-fr-c9d4a49fea.png)

### Steps to reproduce

1. Switch on `Enable versioning for entries in this section?` for a section.
2. Create new Entry and save it with revision notes.
3. Observe the "Current" label in the Entry's version dropdown, with version notes in the `.lightpane` sidebar/footer.
4. Make edits and save a new version with revision notes.
5. Observe the current version's notes in the sidebar, the _past_ edition's creator and datestamp under "Recent Versions" in the revision menu, and yet no reference to the current version's creator.

### Additional info

- Craft version: 2.6.2968
- PHP version: 7.0.12
- Database driver & version: MySQL 5.6.33
- Plugins & versions: n/a

**Comment by takobell** [comment]
Done for the next release of Craft.

**Comment by brandonkelly** [comment]
(initial commit: 429d15addc30fa97b558354509a99b76e64751ab)
