### ISSUE TITLE
Saving an entry switches you back to the default site

### ISSUE THREAD

**Issue by robmcfadden** [craftcms/cms#1653]
### Description

When saving an entry, it should stay on the current site, rather than switching back to the default site. Craft 2 did this for locales.

### Steps to reproduce

1. Have multiple sites
2. When viewing Entries, switch to a site other than the default
3. Edit an entry and save
4. When taken back to Entries, it switches back to the default site

### Additional info

- Craft version: Craft Pro 3.0.0-beta.13
- PHP version: 7.0.15-0ubuntu0.16.04.4
- Database driver & version: MySQL 5.7.17-0ubuntu0.16.04.2
- Plugins & versions: n/a

**Comment by robmcfadden** [comment]
@brandonkelly - Found it. Updating line 2011 in Craft.js from this.site to this.siteId fixes the issue for me.

**Comment by brandonkelly** [comment]
Fixed, thanks!
