### ISSUE TITLE
Provide a method to retrieve element that was just saved

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#1655]
Currently if you're saving an element and want to retrieve the saved element on success, the best you can do is pass the the `{id}` as a query string to the success redirect.

Ideally this would be only available for that next request, retrieving it from session data. Here's now this can be done with a plugin (Craft 2 example):
```
// custom/CustomPlugin.php
craft()->on('entries.onSaveEntry', function($event) {
    $entry = $event->params['entry'];
    craft()->httpSession->add('lastEntryId', $entry->id);
});

// custom/CustomVariable.php
public function getLastEntry()
{
    if (craft()->httpSession->get('lastEntryId'))
    {
        $entryId = craft()->httpSession->get('lastEntryId');
        $entry   = craft()->entries->getEntryById($entryId);

        craft()->httpSession->destroy('lastEntryId');
    }

    return $entry ?? null;
}

// In your success template
{% if lastEntry %}
    <h2>Review "{{ lastEntry.title }}" submission successful.</h2>
{% endif %}
```

Seems like a common enough thing that would be nice if it were core functionality. Above uses session directly but perhaps flash message data is the way to go?

https://craftcms.stackexchange.com/questions/2210/is-it-possible-to-setroutevariables-when-redirecting-after-a-successful-form-sub

https://craftcms.stackexchange.com/a/17233

/cc @BenParizek ↑

**Comment by brandonkelly** [comment]
This feels awkward to me, so not interested in adding it to core. Easy enough to do as a plugin though, as you’ve shown.

You could also store the entry ID as flash data, saving yourself a little trouble as it would just be destroyed automatically the first time it's accessed:

```php
// from onSaveEntry:
craft()->userSession->setFlash('lastEntryId', $entry->id);

// from getLastEntry():
$lastEntryId = craft()->httpSession->getFlash('lastEntryId');
// ...
```

**Comment by timkelty** [comment]
Sounds good, thanks.

**Comment by timkelty** [comment]
@brandonkelly Keep needing this, so I wanted to bring it back up.

Certainly not arguing my solution is the one to go with, but I find it odd that core functionality doesn't allow you to get ID of the element upon saving. Putting `{id}` in the redirect query string seems to be the only supported way to do this, which seems like poor substitute.

**Comment by brandonkelly** [comment]
> I find it odd that core functionality doesn't allow you to get ID of the element upon saving.

By the time Craft is rendering the follow-up page, it’s a completely new request, and Craft has no idea that you just saved an entry in the previous request. So while it may feel like the follow up page is an extension of the save process, in Craft’s perspective it is just a typical page request.

So the only way to solve this is to hook into the save process and store extra data in the user’s session that can inform the following request – data that Craft has no use for internally – and without something using/clearing it, it will just bounce around in session until the session expires, for no reason. Which is why this seems awkward to me.

**Comment by timkelty** [comment]
Makes sense, thanks for the follow up.
I'll stick with my plugin option, or just go with a regular ole param in the redirect.
