### ISSUE TITLE
ActiveRecord does not work after plugin install in Craft 3.x beta 12

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#1657]
I have a super-simple plugin called `TestCase` that has an install migration that creates a database table `{{%testcase_dogfood}}`, and then listens for the `Plugins::EVENT_AFTER_INSTALL_PLUGIN` event to save an db row in this table via ActiveRecord:

```
    public function init()
    {
        parent::init();
        self::$plugin = $this;

        Event::on(
            Plugins::className(),
            Plugins::EVENT_AFTER_INSTALL_PLUGIN,
            function (PluginEvent $event) {
                if ($event->plugin === $this) {
                    $dogFoodRecord = new DogFoodRecord([
                    ]);
                    $dogFoodRecord->save();
                }
            }
        );
    }
```

However, this results in:
```
Invalid Configuration – yii\base\InvalidConfigException

The table does not exist: {{%testcase_dogfood}}
```

Expected result:

1. I would be able to use the ActiveRecord tables my Install migration has created.

TestCase plugin attached:

[testcase.zip](https://github.com/craftcms/cms/files/949149/testcase.zip)

**Comment by brandonkelly** [comment]
Guessing this is because Yii caches DB schemas as they are requested, and something in your plugin is doing something with the Active Record class before it actually does exist.

Try adding this at the end of your Install migration, or at the beginning of your `afterInstallPlugin` event handler:

```php
Craft::$app->db->schema->getTableSchema(DogFoodRecord::tableName(), true);
```

**Comment by khalwat** [comment]
I tried that too @brandonkelly while debugging, it was returning null, though I wasn't passing in `true` as the second parameter.  When I do this:

```
                Craft::dd(Craft::$app->db->schema->getTableSchema(DogFoodRecord::tableName(), true));
```
It does indeed return the correct schema. Perhaps Craft/Yii/something should be flushing the caches after migrations are run?

**Comment by brandonkelly** [comment]
Yeah, Yii should probably be automatically clearing schema caches when schema-altering functions are called on `yii\db\Command`. Maybe create an issue with them?

**Comment by khalwat** [comment]
So I added this to my `safeUp()` method in my `Install.php` migraiton, and it all works as expected now:
```
                    Craft::$app->db->schema->refresh();
```

Something seems wrong tho, I can't imagine that migrations in general don't clear the schema cache. Could it be something particular in terms of the migrations being attached to components that are dynamically loaded?

**Comment by khalwat** [comment]
@takobell found this: https://github.com/yiisoft/yii2/issues/3305

Seems like it's by design, and not a bug.

**Comment by brandonkelly** [comment]
I just left a comment on that issue, proposing a less heavy-handed solution. Maybe they’ll bite.

**Comment by brandonkelly** [comment]
Just submitted a Yii2 PR that will fix this: https://github.com/yiisoft/yii2/issues/14072

**Comment by brandonkelly** [comment]
Just submitted a Yii2 PR that fixes this: https://github.com/yiisoft/yii2/pull/14073

**Comment by khalwat** [comment]
Awesome. I just pushed a change to `generator-craftplugin` that does `Craft::$app->db->schema->refresh()` in the `Install.php` migration just before calling the `insertDefaultData()` method.

**Comment by brandonkelly** [comment]
Officially fixed for the next Yii release.

**Comment by khalwat** [comment]
Saw that! Well done sir!
