### ISSUE TITLE
Calling Craft::$app->getUrlManager() causes it to no longer trigger events

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#1658]
#I have a plugin where I access the UrlManager via `Craft::$app->getUrlManager()->`  If I do that _before_ I register an event handler such as:

```
        // Handler: UrlManager::EVENT_REGISTER_SITE_URL_RULES
        Event::on(
            UrlManager::className(),
            UrlManager::EVENT_REGISTER_SITE_URL_RULES,
            function (RegisterUrlRulesEvent $event) {
                Craft::trace(
                    'UrlManager::EVENT_REGISTER_SITE_URL_RULES',
                    'seomatic'
                );
            }
        );
```

...then those events are never sent. It sort of makes sense, because accessing the component likely causes it to instantiate itself and then it triggers those events just once, so subsequently adding listeners does nothing.

Took me a while to figure out what was going on, though, so perhaps this isn't desired behavior? Or should we just be registering out event listeners first thing in the plugin?

**Comment by khalwat** [comment]
hmmm, the more I think about this, the more I think it's a problem.

Even if _my_ plugin is nice about it, and ensures that it registers the `UrlManager::EVENT_REGISTER_SITE_URL_RULES` event listener before calling anything that accesses `Craft::$app->getUrlManager()`, if any plugin that loads before me triggers `Craft::$app->getUrlManager()` then my listener will similarly not receive any events.

Additionally, any plugins that load after me will presumably be deaf to the same events. 

This may or may not apply to other services that fire events as well, I don't know.

**Comment by brandonkelly** [comment]
Nothing we can do about this, as `yii\web\UrlManager` calls its `buildRules()` function from `init()`. All plugins will just need to be careful not to instantiate UrlManager in their `init()` methods.

**Comment by narration-sd** [comment]
@khalwat  actually these things you are finding out about init() are pretty useful -- things not to do or depend on there.

Could be this sort of thing should be collected in a section of plugin doc?
