### ISSUE TITLE
ElementHelper::createSlug() doesn't respect conversion of äüöß

### ISSUE THREAD

**Issue by steveooo9** [craftcms/cms#1660]
### Description
`ElementHelper::createSlug($string);` seems to not respect conversion of specific characters like `äüöß`.

### Steps to reproduce

1. Test `return ElementHelper::createSlug('Bier Bräu');`
2. Should output `bier-braue` instead of `bier-bräu`

### Additional info

- Craft version: 2.6.2974
- PHP version: 7.1
- Database driver & version:
- Plugins & versions: none

**Comment by takobell** [comment]
`ElementHelper::setValidSlug($element)` takes the [`limitAutoSlugsToAscii`](https://craftcms.com/docs/config-settings#limitAutoSlugsToAscii) config setting into account,
 and then calls `createSlug()`. Maybe call that instead?

**Comment by steveooo9** [comment]
@takobell Well, I read into this method, but I am using it in some other code just for slugifying strings.

**Comment by steveooo9** [comment]
@takobell Brad, I believe in you! You can do this!

**Comment by takobell** [comment]
Not keen to change this behavior on Craft 2 as it's been completely refactored in Craft 3. Your plugin can always do the call directly, though... i.e.

```
if (craft()->config->get('limitAutoSlugsToAscii'))
{
	$slug = StringHelper::asciiString($slug);
}

$slug = ElementHelper::createSlug($slug);
```

**Comment by steveooo9** [comment]
@takobell Okay. Thanks! I use this instead!
