### ISSUE TITLE
"Test email" data doesn't have a recipient

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#1661]
### Description

I'm building a plugin that does email delivery through [mandrillapp.com](http://mandrillapp.com) or [postmarkapp.com](http://postmarkapp.com), using the `onBeforeSendEmail` event to intercept the EmailModel object and send the message through the API.

This works with most plugins that use the EmailModel for their messages, but not with the "Test" button in the email settings in the dashboard. Clicking the button sends an email and thus fires the `onBeforeSendEmail` event but the `toEmail` field in that object in empty.
### Steps to reproduce

1. Listen for the `onBeforeSendEmail` event
2. Click the "Test button in email settings
3. Check the data you have available in the event

### Additional info

- Craft version:  2.6.2974
- PHP version: 7.1
- Database driver & version: na
- Plugins & versions: na

**Comment by brandonkelly** [comment]
Rather than getting the email address from `$event->params['emailModel']->toEmail`, check `$event->params['user']->email`.
