### ISSUE TITLE
Content cut off 

### ISSUE THREAD

**Issue by yellostudio** [craftcms/cms#1664]
[###](url) The content gets cut off when you access the entry page.  If you save it sometimes it sorts itself.

<img width="1270" alt="screen shot 2017-04-24 at 21 34 28" src="https://cloud.githubusercontent.com/assets/1303564/25360106/abe9f4a6-293f-11e7-9e98-1011f5fc4fe4.png">

### Steps to reproduce

Access an entry page

### Additional info

- Craft version: V3 Beta 13
- PHP version: 7
- Database driver & version: N/A
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
I haven’t seen this.  What browser are you using?
