### ISSUE TITLE
Cache not broken on query of structure descendants when adding a new child entry

### ISSUE THREAD

**Issue by swixpop** [craftcms/cms#1667]
### Description

Cache is not being broken on a page showing descendants in a structure when a new descendant entry is created. Happens when the querying entries using `descendantOf ` or when fetching children using `entry.getChildren()`.

### Steps to reproduce

1. Create a structure with more than 1 level.
2. Create a cached query to list the descendants and output length.
```
{% cache globally using key ('foo' ~ craft.request.path) %}
  {% set parent = craft.categories().id(260).first() %}
  {% set children = craft.entries({
    descendantOf: parent
  }) %}
  {{ children | length }}
{% endcache %}
```
3. Hit the page to create the cache. Create a new child entry under parent.
4. Hit the page again and `{{ children | length }}` does not change.
5. Clear the cache and hit the page again, length is now updated.

### Additional info

Tested on 2.6.2973 and 2.6.2974

**Comment by brandonkelly** [comment]
Please specify which version(s) you are seeing this on – 2.6.2976 and/or 3.0.0-beta.13

**Comment by swixpop** [comment]
Tested on 2.6.2973 and 2.6.2974

**Comment by brandonkelly** [comment]
In the Control Panel sidebar, do you see a “Deleting Stale Template Caches” task that is stalled?

**Comment by swixpop** [comment]
There aren't any stalled tasks.

**Comment by brandonkelly** [comment]
Thanks, was able to reproduce. We just talked it over, and unfortunately the fix for this is pretty complicated, so not something we can address right now. (We do plan on rearchitecting how template caches work down the road, and this is one more reason why we should.)

In the meantime, you can work around the issue by changing this line:

```twig
descendantOf: parent
```

to:

```twig
descendantOf: parent.id
```

**Comment by TomDeSmet** [comment]
This workaround is not working for me unfortunately. :(
