### ISSUE TITLE
FEATURE REQUEST: Config Variable to Disable Plugins

### ISSUE THREAD

**Issue by bgarrant** [craftcms/cms#1669]
We could really use a way to disable individual plugins and all plugins via a configuration variable.  

Something like this for individuals:

`'disablePlugins' => ['commerce', 'contact_form']`

 or this for all:

`'disablePlugins' => 'true'`

You get the idea...

**Comment by lindseydiloreto** [comment]
That sounds pretty handy! I can think of a few scenarios where we'd want a plugin to be enabled in one environment, but disabled in another environment.

**Comment by carlcs** [comment]
Disabling plugins is not possible any more, see https://github.com/craftcms/cms/commit/95310077bb703e8f8d68cf93207340ec6ed61b54.

**Comment by takobell** [comment]
@carlcs Just in the context of Composer installed plugins. Non-composer installed ones (when we add support for them) can still be.

**Comment by carlcs** [comment]
@takobell will plugins installed from the Craft Store count as Composer installed plugins?

**Comment by brandonkelly** [comment]
@carlcs TBD. Though, the fact that there are certain plugins that can't be disabled means that a `disablePlugins` config setting would be pretty confusing, so I'm going to say no to this one.

That said, there's already a very easy way to disable all (non-Composer-installed) plugins: just rename your plugins/ folder :)
