### ISSUE TITLE
Old folder remains when an asset bundles is re-published

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#1670]
### Steps to reproduce

1. Install a plugin that registers an asset bundle
2. See how the bundle gets published to cpresources/
3. Edit an asset that’s included in the bundle
4. See how the bundle gets re-published and the old folder is still there in cpresources/

### Additional info

- Craft version: 3.0.0-beta.13
- PHP version: 7.0.15
- Database driver & version: MySQL / MariaDB 10.1.21
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Fixed for Craft, though ideally it could be fixed directly in Yii (https://github.com/yiisoft/yii2/issues/14099).
