### ISSUE TITLE
Translations missing in assets menu

### ISSUE THREAD

**Issue by nilsenpaul** [craftcms/cms#1672]
### Description
In the menu on the assets page, two translations are missing: "Download Asset file" and "Edit Image".
![schermafbeelding 2017-04-26 om 15 42 14](https://cloud.githubusercontent.com/assets/6794819/25460633/8c6898b6-2a99-11e7-9f91-c3bb858eecec.png)

### Steps to reproduce

1. Go to assets page
2. Open the assets menu by clicking the cog icon :)

### Additional info

- Craft version: 3.0.0-beta.13
- PHP version: 
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
They are set up to be translated; we just haven't updated Craft’s translations for v3 yet. Will do that when closer to general release.

FFR, you can find out if a string is "translated" as far as Craft is concerned by setting the `translationDebugOutput` config setting in `config/general.php:`

```php
'translationDebugOutput' => true,
```

Strings that are translated will get wrapped in `@`, `$`, or `%`, depending on the translation category (`app`, `site`, or a plugin):

> <img width="175" alt="screen shot 2017-05-01 at 4 11 57 pm" src="https://cloud.githubusercontent.com/assets/47792/25598330/37260016-2e89-11e7-9d85-d9550fb56068.png">
