### ISSUE TITLE
FR: Allow batch select/actions on fields in Layout Designer 

### ISSUE THREAD

**Issue by ldstevens** [craftcms/cms#1674]
Quick feature request :) 

When putting together complex field layouts, it's a pain to drag & drop fields one at a time when picking fields out of 60-odd spread across half a dozen groups, especially when the groups wrap below other (long) groups, making the drag target far away.

Instead I wonder if having checkboxes with those fields would allow you to just run through all fields, check the ones you want, and then perform a batch action of "Add all to [tab x]", in a similar way to how you can select multiple entries and then perform a batch action that way. That way you can "shop" for your fields, and it only takes one click per field to add (+ batch action).

You could do the same thing with fields already added to a tab to batch remove them, or batch move them to another tab, etc.

Cheers :)

(Ah I see similar ideas have come up before: https://github.com/craftcms/cms/issues/1076 )

**Comment by AbbeyDesign** [comment]
After about 20-30 fields it gets a bit unwieldy. The Freeform form plugin has a nice approach to the way they manage their fields. Maybe something could be gleaned from their approach.

**Comment by dougstjohn** [comment]
Two ideas to improve this UI:
- Add one or more 'search' fields that filter by field name, field handle, or field type.
- Right click, double click or click a gear on any field and pick which tab you want to add the field to.
