### ISSUE TITLE
Craft 3 Beta - Database backup size

### ISSUE THREAD

**Issue by marjorg** [craftcms/cms#1676]
### Description
I've noticed the SQL file from Craft 3 beta database backups are massive compared to the Craft 2 sites we've made.

Here is a screenshot comparing backups from three sites. The Craft 2.6 sites has way more entries and plugins than the beta site.

![screen shot 2017-04-28 at 11 00 35](https://cloud.githubusercontent.com/assets/5442549/25522161/30d7815a-2c02-11e7-9399-638ed9acbf61.png)

Not sure if it's a bug or just a consequence of new Craft 3 features.

**Comment by takobell** [comment]
Craft does PHP based database backups.  Craft 3 ditches that (for many reasons) and relies on [mysqldump](https://dev.mysql.com/doc/refman/5.7/en/mysqldump.html) if you're using MySQL and [pgdump](https://www.postgresql.org/docs/9.3/static/app-pgdump.html) if you're using PostgreSQL.

Craft 2 would also _not_ backup certain tables by default (i.e. sessions, template caches, index data, etc.), but Craft 3 does and that's likely what you're seeing (the extra data in those tables).  You can change the default command and parameters that Craft uses for creating backups with the [backupCommand](https://github.com/craftcms/cms/blob/develop/src/config/GeneralConfig.php#L99-L118) config setting.
