### ISSUE TITLE
FR: Remove Target="_blank" From Site Link in CP

### ISSUE THREAD

**Issue by AbbeyDesign** [craftcms/cms#1678]
### Description
Going back and forth between the front end and the CP always leaves us with a million new open tabs/windows. It would be nice if the link to the site on the top left of the CP was not set to target="_blank". I should be able to choose on my end via my mouse if I open this link in a new window or not.

Currently I have added a plugin to my browser to override this but then that breaks the "live preview in a new window" feature on an edit page. Having it default to not open in a new window or a config I could adjust would be ideal.

**Comment by lindseydiloreto** [comment]
I strongly disagree with this.

While I recognize the annoyance of having too many tabs open, it's "the lesser of two evils" in my mind. When I'm surfing around the CP, clicking on that link _rarely_ means I want to leave the CP entirely. It's usually a sign that I want to view the back-end & front-end simultaneously.

At most, I could see a checkbox option buried somewhere in the general settings. Or (even better) a `/config/general.php` setting to control this behavior.

**Comment by brandonkelly** [comment]
Yeah I think it’s pretty standard behavior for “offsite” links to open in a new window. The CP may _manage_ the front-end site, but the context is so completely different that I’d classify it as an offsite link.

That said, if you really dislike the `target="_blank"` here, just use the [CP JS](https://github.com/lindseydiloreto/craft-cpjs) plugin to add this JS:

```js
$('a.site-name').removeAttr('target')
```
