### ISSUE TITLE
Field layout editor doesnt work in Firefox

### ISSUE THREAD

**Issue by jassok** [craftcms/cms#1679]
### Description
The drag and drop layout editor doesn't in firefox very often. It will work every once in a while, but more often than not will throw an error: `TypeError: this.refreshCols._ is undefined`

`TypeError: this.refreshCols._ is undefined craft.js:12050`

### Steps to reproduce

Screencast: https://www.screencast.com/t/yaADqIlXAfp
1.  Go to any section 
2. Try to add a new content type
3. ????

### Additional info

- Browser: http://www.whatsmybrowser.org/b/SRR3O5D
- Craft version: Craft-2.6.2976
- PHP version: 7.0
- Database driver & version:  mysql  Ver 14.14 Distrib 5.5.55, for debian-linux-gnu (x86_64) using readline 6.3
- Plugins & versions: None

**Comment by benjamindavid** [comment]
Hey @jassok, there seem to be a bug in older versions of Firefox (48 and below) that prevents private properties from working properly. Please update to latest version, I'd also suggest turning auto updates on (Firefox preferences > Advanced > Update > Automatically install updates)
