### ISSUE TITLE
slight  problem with Channel slugs

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1680]
### Description
This will particularly occur on a converted site, and at first looked like a doc bug. But it isn't.

If you use a slug definition like `news/{postDate.year}/{slug}` for a Channel, the {postDate.year} will turn into a blank when you get it from entry.url, so that a linked formed with it will look like `news//{slug} only, and 404.

I tried postDate.year() as the doc might suggest, but no joy.

Then because I hadn't quite grokked an underlying pattern and was trying things, I rewrote the slug with slight changein the Entry form, and saved it again. 

Now the full date pattern arrived from entry.url in the Twig. So it's something  a little awry in when that gets generated for the database.

I checked, and nothing like this happens in Craft 2

### Steps to reproduce

1. As above

### Additional info

PHP version	7.1.3-3+deb.sury.org~xenial+1
Database driver & version	MySQL 5.7.17-0ubuntu0.16.04.1
Image driver & version	GD 7.1.3-3+deb.sury.org~xenial+1
Craft edition & version	Craft Personal 3.0.0-beta.13
Yii version	2.0.11.2
Twig version	2.1.0
Guzzle version	6.2.1
Imagine version	0.7-dev
Plugins

Bactrian	1.0.0
Trimmer	1.0.0
Standards Agent	2.0.1
Video Embed	3.0.0 (yes, I converted it, but haven't asked to post it)

**Comment by brandonkelly** [comment]
This is due to date format templating changes in Craft 3 – https://github.com/craftcms/docs/blob/master/en/upgrade.md#date-formatting

Though `.year`, etc., will continue to work once Beta 14 is released, and just log a deprecation error.

**Comment by narration-sd** [comment]
Yeah, sorry, I misread that chart at the time, and used what was on the left, thinking it just needed parens!

**Comment by narration-sd** [comment]
Yeah, sorry, I misread that chart at the time, and used what was on the left, thinking it just needed parens!

Nice idea to make it work with deprecation, though -- will save a lot of conversions support...
