### ISSUE TITLE
3.0.0-beta.13 Installation not working bower-asset/timepicker

### ISSUE THREAD

**Issue by William-Owen** [craftcms/cms#1681]
### Description

Composer installation is failing: -

````bash
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - craftcms/cms 3.0.0-beta.13 requires bower-asset/timepicker 1.11.10.0 -> no matching package found.
    - craftcms/cms 3.0.0-beta.12 requires bower-asset/timepicker 1.11.10.0 -> no matching package found.
    - craftcms/cms 3.0.0-beta.11 requires bower-asset/timepicker 1.11.10.0 -> no matching package found.
    - craftcms/cms 3.0.0-beta.10 requires bower-asset/timepicker 1.11.10.0 -> no matching package found.
    - Installation request for craftcms/cms ^3.0.0-beta.10 -> satisfiable by craftcms/cms[3.0.0-beta.10, 3.0.0-beta.11, 3.0.0-beta.12, 3.0.0-beta.13].
````

### Steps to reproduce

1. from the command line `composer create-project craftcms/craft craft -s beta`
2. above error appears in the logs.

### Additional info

- Craft version: 3.0.0-beta.13
- PHP version: 7.1
- Database driver & version: mysql
- Plugins & versions: Element API

**Comment by brandonkelly** [comment]
Fixed for the next beta release. For now, you can install Craft manually to avoid this:

1. Download this repo's zip file, and extract it wherever you want your Craft project
2. Edit composer.json and change the `craftcms/cms` version requirement to `"dev-develop as 3.0.0-beta.99"`
3. Open Terminal, `cd` to the project root, and run `composer install`.

**Comment by MDXDave** [comment]
@brandonkelly You must download the zip of **[this](https://github.com/craftcms/craft)** repo, not _craftcms/cms_ 😄

**Comment by brandonkelly** [comment]
@MDXDave Doh! Thanks :)

**Comment by brandonkelly** [comment]
Beta 14 was just released with a fix.

**Comment by William-Owen** [comment]
Epic; thanks for the heads up.
