### ISSUE TITLE
BUG: `Craft\EntryModel` in the Title field

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#1685]
### Description

When creating a new entry, `Craft\EntryModel` is being pre-populated in the Title field:

<img width="408" alt="Craft\EntryModel" src="https://cloud.githubusercontent.com/assets/5309692/25641289/2de1fc5c-2f48-11e7-98da-0feabd987bac.png">

This is happening across all sections. (there are four sections total)

### Steps to reproduce

1. Go to "Entries"
2. Click "New Entry" button
3. Witness `Craft\EntryModel` pre-populated in the Title field

### Additional info

- Craft version: 2.6.2977
- PHP version: 7.0
- Plugins & versions: All plugins have been disabled

**Comment by evanwarner** [comment]
And when creating a new Category it reads `Craft\CategoryModel`.

**Comment by takobell** [comment]
Fixed in https://craftcms.com/changelog#2-6-2978
