### ISSUE TITLE
Create Field Group Button Not Appearing

### ISSUE THREAD

**Issue by jeremiahricih** [craftcms/cms#1686]
### Description
On a new install, the Create Field Group button is not appearing. This of course means the only message that is shown is "No fields exist yet." Can't create any new fields because there are no field groups...

### Steps to reproduce

1. Create new install of Craft CMS.
2. Install PRO license key.
3. Navigate to Fields in settings to see the issue.

### Additional info

- Craft version: 3.0.0 beta 14
- PHP version: 7.0.15-0ubuntu0.16.04.4
- Database driver & version: MySQL 5.7.18-0ubuntu0.16.04.1
- Plugins & versions:

**Comment by brandonkelly** [comment]
The button is technically there; just not visible due to #1364, so closing this and re-opening that one.
