### ISSUE TITLE
Client account unable to access globals in Craft 3 beta 14

### ISSUE THREAD

**Issue by jolora** [craftcms/cms#1687]
### Description

I have created a simple globals set (it is the only globals set on the site) and I have assigned permission to the client account so that they may access it. However, when the client does attempt to access the global set they are greeted with the following error 

> Unauthorized
> User not permitted to edit content in any sites

### Steps to reproduce

1. Create a global set.
2. Assign the appropriate permissions to the client account
3. Attempt to access the set from within the client account

### Additional info

PHP version	7.0.18
Database driver & version	MySQL 5.5.5-10.0.30-MariaDB
Image driver & version	GD 7.0.18
Craft edition & version	Craft Client 3.0.0-beta.14
Yii version	2.0.11.2
Twig version	2.3.2
Guzzle version	6.2.1
Imagine version	0.7-dev

No plugins installed.

**Comment by brandonkelly** [comment]
@jolora Do you have multiple sites?

**Comment by jolora** [comment]
@brandonkelly No, just the one (with a handle of _default_)
