### ISSUE TITLE
Manual template cache management

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/cms#1689]
The current template caching system has a high dosage of automagic cache busting:

- `{% cache %}` tags record:
  - each of the element IDs whose properties were accessed (stored in `templatecacheelements`)
  - any element queries that were executed (stored in `templatecachecriteria`)
- Whenever an element is saved/deleted, template caches will be deleted if:
  - they are associated with the element’s ID (via `templatecacheelements`)
  - any of the element queries associated with the template cache are now pulling in the element’s ID (via `templatecachecriteria`)

The element query-based cache busting works in general, but there are a few edge cases (e.g. #1667) where it doesn’t, and it is also generally a huge performance suck, and the cause of many stalled tasks. It’s so expensive that some sites resort to disabling it altogether, via the `cacheElementQueries` config setting.

We should probably just completely remove element query-based cache busting, and replace it with manual cache management, plus the ability to define automated cache busting strategies.

**Comment by brandonkelly** [comment]
Element query caching has been completely rewritten for Craft 3.5, in a way that no longer suffers from the performance issues / long-runnning background jobs that have plagued `{% cache %}` tags to date. Details here: https://github.com/craftcms/cms/issues/1507#issuecomment-633147835

**Comment by Mosnar** [comment]
@brandonkelly Great work! Just a heads-up, I was playing with this and if you don't create a query within the cache tag (for example, using the matched element (`entry.title`) instead, the cache is not automatically invalidated when the corresponding entry saves.

Does not clear on entry save:
```twig
{% cache %}
{{ entry.title }}
{% endcache %}
```

Does clear on entry save:
```twig
{% cache %}
    {% set entry = craft.entries.section('homepage').one() %}
    <h1>{{ entry.test }}</h1>
{% endcache %}
```
