### ISSUE TITLE
The "add row" button doesn't work on tables added to plugin settings

### ISSUE THREAD

**Issue by Rias500** [craftcms/cms#1691]
### Description
When I add a table (editableTable) to a plugin's settings with the following code:

```
{{ forms.editableTableField({
        label: "My Table",
        id: "table",
        name: "table",
        cols: [
        {
            heading : 'From',
            type: 'singleline'
        },
        {
            heading : 'To',
            type: 'singleline'
        },
        ],
        rows: settings[table]
    })
}}
```

The "add row" button doesn't work. If there's a value in the table the delete or move buttons don't work either.

### Additional info

- Craft version: 3.0 beta 14
- PHP version: 7.1

**Comment by splendidrob** [comment]
@brandonkelly just come across this issue again using Craft 5.3.1.

Settings.php:
```
<?php

use craft\base\Model;

/**
 * stripe-cart settings
 */
class Settings extends Model
{
    public array $tableField = [];

    public function rules(): array
    {
        return [
            [['tableField'], 'safe'],
        ];
    }
}
```
_settings.twig:
```
{% import '_includes/forms.twig' as forms %}
{% set columns = [
    {
        heading: "Column 1",
        handle: "col1",
        width: "",
        type: "singleline"
    },
    {
        heading: "Column 2",
        handle: "col2",
        width: "",
        type: "singleline"
    }
] %}

{% set rows = settings.tableField ?: {
    'row1': { 'col1': 'Test 1', 'col2': 'Test 2' }
} %}

{{ forms.editableTable({
    label: 'Shipping Rates',
    id: 'myTableId',
    name: 'tableField',
    cols: columns,
    rows: rows,
    addRowLabel: 'Add a row'
}) }}
```

The field shows up in my plugin settings page but has no way of adding more rows. It also doesnt seem to show a label either - although changing the form macro include to 'editableTableField' shows the label but no add button...am I missing something?

**Comment by brandonkelly** [comment]
As of Craft 4.0 you must explicitly pass `allowAdd`, `allowDelete`, and `allowReorder` settings to `forms.editableTable()` if you want to enable those features:

```twig
{{ forms.editableTable({
    label: 'Shipping Rates',
    id: 'myTableId',
    name: 'tableField',
    cols: columns,
    rows: rows,
    allowAdd: true,
    allowDelete: true,
    allowReorder: true,
    addRowLabel: 'Add a row'
}) }}
```

(See #10163)

**Comment by splendidrob** [comment]
@brandonkelly Ahhh that'll be it! Thank you so much, really appreciate you pointing me in the right direction! Where abouts in the docs can I find this info? Been struggling to find any guidance on the form macros available and how to work with them...

**Comment by brandonkelly** [comment]
We don’t have any CP UI docs yet 😞 Working on it for v6 though.
