### ISSUE TITLE
craftcms/cms 3.0.0-beta.14 installation bug: bower-asset/d3 ~4.8.0 -> no matching package found.

### ISSUE THREAD

**Issue by cmac1000** [craftcms/cms#1698]
### Description

I'm running into a composer dependency problem trying to use `"craftcms/cms": "3.0.0-beta.14"`:

Composer complains that `craftcms/cms 3.0.0-beta.14 requires bower-asset/d3 ~4.8.0 -> no matching package found.`

I made a small github repo to demonstrate the problem for reproducibility: https://github.com/cmac1000/craft-3-installation-2017-05-09

The composer error signature is:

```
  Problem 1
    - Installation request for craftcms/cms 3.0.0-beta.14 -> satisfiable by craftcms/cms[3.0.0-beta.14].
    - craftcms/cms 3.0.0-beta.14 requires bower-asset/d3 ~4.8.0 -> no matching package found.
```

### Steps to reproduce

1.  `git clone git@github.com:cmac1000/craft-3-installation-2017-05-09.git` 
2.  `cd craft-3-installation-2017-05-09`
3.  `docker build -t temp .`
4.  `docker run temp composer install --dry-run`

(alternatively, try a composer installation in some other environment using this composer.json: https://github.com/cmac1000/craft-3-installation-2017-05-09/blob/master/composer.json)

### Additional info

- Craft version: `3.0.0-beta.14`
- PHP version: `PHP 7.0.16-1~dotdeb+8.1 (cli) ( NTS )`
- Database driver & version: N/A
- Plugins & versions: N/A

**Comment by cmac1000** [comment]
brief slack discussion: https://craftcms.slack.com/archives/C04UQS105/p1494342132329610

**Comment by brandonkelly** [comment]
To install Craft 3 you must either use the `craftcms/craft` Composer project as a starting point:

    > composer create-project craftcms/craft <PATH> -s beta

or you can manually require `craftcms/cms` in an existing project, but you must add `asset-packagist.org` as a repository to your composer.json file first (see step 1 in the [Updating Craft CMS](https://github.com/craftcms/docs/blob/master/en/upgrade.md#updating-craft-cms) docs).
