### ISSUE TITLE
Assets on a site with multiple locales only get indexed in the primary locale

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#17]
#### Environment:

- Craft version: 3.x
- PHP version: 7.x
- Database driver & version: n/a
- Plugins & versions:

#### Description:

When you upload an asset to Craft and there are multiple locales available, then search/index service only indexes element attributes for the primary locale of the site causing you to not be able to search for that file in other locales.

**Comment by brandonkelly** [comment]
@andris-sevcenko if asset indexing goes through `craft\services\Elements::saveElement()` this shouldn't be the case.

**Comment by andris-sevcenko** [comment]
As of 7ecb943f14656f87cb15736e976f5d93422ddfe2 it definitely goes through `craft\services\Elements::saveElement()`
