### ISSUE TITLE
Structure URLs not updated when changing section URI

### ISSUE THREAD

**Issue by rynpsc** [craftcms/cms#1705]
### Description

Structure URLs not updating until entry is resaved.

### Steps to reproduce

1. Create a new section e.g. Pages, leave "Entry URI Format" as is i.e "pages/{slug}".
2. Add new entry called "Test" in newly created structure.
3. Open entry using the "View webpage" link.
4. URL should be "/pages/test".
5. Go back to structure settings and change  "Entry URI Format" to be "{slug}", save.
6. Go back to entries and open entry using the "View webpage" link - URL hasn't updated - still "/pages/test".
7. Open entry and re-save.
8. Open entry using the "View webpage" link, entry URL has changed to "/test".

### Additional info

- Craft version: 3.0.0-beta.15
- PHP version: 7.1.4
- Database driver & version: MySQL 5.7.18
- Plugins & versions: None

**Comment by emersonthis** [comment]
Bingo. I had a queue of stuck background jobs. Raising the PHP memory_limit to 1024 solved it for me. Thanks!
