### ISSUE TITLE
Live preview not working as expected

### ISSUE THREAD

**Issue by Rias500** [craftcms/cms#1710]
### Description
So I have a Matrix field set up with a redactor field and an image field, they both have position buttons. The code used to render the matrix field is similar to the setup used in HappyLager.

When I just edit the entry and save, the positions change accordingly and nothing is wrong, if I change the positions and order of the fields in live preview, weird things happen.

### Steps to reproduce

1. Create a matrix field
2. Add a "text" and "image" block with position fields
3. Write a template that changes the position of the blocks according to the content
4. Change them in live preview

Video of the bug in action:

https://vimeo.com/217530030

### Additional info

- Craft version: 3 beta 17
- PHP version: 7.1

**Comment by brandonkelly** [comment]
Can you post your template code?

**Comment by Rias500** [comment]
```
{#
 # Article Body include template
 # -----------------------------
 #
 # This template is used to output HTML for the main content Matrix field.
 #
 # An `entry` variable is expected to be defined.
-#}

{% set prevType = null %}
{% set prevPosition = null %}
{% set nextType = null %}
{% set nextPosition = null %}
{% set closedLastRow = true %}
{% set blocks = entry.pageBody %}

{% macro getPosition(block) %}
    {%- spaceless %}
        {% set positionedTypes = ['text', 'image', 'cta'] %}
        {{ block.type.handle in positionedTypes and block.position ? block.position : 'center' }}
    {% endspaceless -%}
{% endmacro %}

{% from _self import getPosition %}

{% for i, block in blocks %}

    {# If there's no next type, we're on the first type #}
    {% set type = (nextType ?: block.type) %}

    {# Get the position for this block (left, center, right, full) #}
    {% set position = (nextPosition ?: getPosition(block)~'') %}

    {# Get the next blockType #}
    {% set nextType = (not loop.last ? blocks[i+1].type.handle) %}

    {# Get the next position #}
    {% set nextPosition = (not loop.last ? getPosition(blocks[i+1])~'') %}

    {# Is this block floated to the left or right? #}
    {% set isFloat = position in ['left', 'right'] %}

    {# Is this a breakout block (a sole floated block before a centered block)? #}
    {% set isBreakout = (
        isFloat and type in ['text', 'image'] and
        (position == 'left' or prevPosition != 'left') and
        nextPosition == 'center'
    ) %}

    {# Are we starting a new row? #}
    {% if position == 'full' %}
        <div class="row">
    {% elseif closedLastRow %}
        <div class="container">
        <div class="row">
        {% if type not in ['gallery'] %}
            {%- if (type == 'image' and position == 'center') %}<div class="col-sm-10 offset-sm-1">{% endif -%}
        {% endif %}
    {% endif %}

    {# If the element is floated, create a column of 6, otherwise 12 #}
    <div class="col-12
        {%- if isFloat %} col-sm-6{% endif -%}
        {%- if isBreakout %} breakout{% endif -%}
        {%- if position == 'right' and prevPosition != 'left' %} offset-sm-6{% endif -%}
        ">

    {# Load our component #}
    {% include '_partials/components/' ~ type %}

    {# Close the column #}
    </div>

    {# Are we closing this row? #}
    {% if not (
        (position == 'left' and nextPosition == 'right') or
        isBreakout
    ) %}
        {% if position != 'full' and type not in ['gallery'] %}
            </div>
        {% endif %}
        </div>
        </div>
        {% set closedLastRow = true %}
    {% else %}
        {% set closedLastRow = false %}
    {% endif %}

    {% set prevType = type %}
    {% set prevPosition = position %}
{% endfor %}
```

**Comment by brandonkelly** [comment]
Can you try simplifying the template a bit? Considering we haven’t had any similar reports, and the complexity of your template, my hunch is that this is just a bug in the template logic somewhere.

**Comment by Rias500** [comment]
Yeah I guess it has to do with the template, with a really simplified one (which doesn't account for previous or next blocks) it works.

Weird that it would work when saving the entry then but not with live preview, I'll try and come up with a simpler template to solve what I'm trying to achieve.

**Comment by Rias500** [comment]
@brandonkelly Okay so I've found some weirdness, look at the following situation:

<img width="654" alt="screen shot 2017-05-15 at 23 13 30" src="https://cloud.githubusercontent.com/assets/3626559/26083238/27e21176-39c4-11e7-9d6c-94bbc9cf9070.png">

I have 3 images, each with a position field. First one is `left`, second one `right` and the last one `full`. The template is just this and spits out some position variables:

```
{% set blocks = entry.pageBody %}
{% for i, block in blocks %}
    {% set nextBlock = blocks[i+1] ?? null %}
    {% set nextPosition = nextBlock ? nextBlock.position : null %}
    {% set nextType = nextBlock ? nextBlock.type : null %}

    <div class="container">
        <p>
            <span>i: {{ i }}</span><br>
            <span>Current position: {{ block.position }}</span><br>
            <span>Next position: {{ nextPosition }}</span>
        </p>
    </div>
{% endfor %}
```

As you can see in the first screenshot, everything is correct, but as soon as I switch the second image from `right` to `center` the following happens:

<img width="627" alt="screen shot 2017-05-15 at 23 15 59" src="https://cloud.githubusercontent.com/assets/3626559/26083323/95a1e556-39c4-11e7-90cc-0f2df2a3ff09.png">

As you can see the "Next position" is not correct anymore, and this only happens in live preview.

**Comment by Rias500** [comment]
There seems to be some weird caching going on in the `entry.pageBody` when accessing it by index.

I've worked around it for now by creating a first loop to save all the positions in an array and then recalling that array when checking the next/previous positions of blocks. Not exactly a solution but at least the live preview now works!

```
{% set positions = [] %}
{% for block in blocks %}
    {% set positions = positions|merge({(loop.index0): (block.position)}) %}
{% endfor %}
```

**Comment by brandonkelly** [comment]
Thanks for the additional info! Was able to reproduce and find/fix the bug.
