### ISSUE TITLE
No global template for craft 3 frontend?

### ISSUE THREAD

**Issue by yellowmamba** [craftcms/cms#1714]
### Description

Setting up Craft 3 from scratch. Created the project from composer, and I know that you can put all twig templates in the `templates` folder. However, by default Craft 3 doesn't seem to provide a default layout or base template.

As a pragmatic developer, I really do need the Yii profiler to show up on the frontend templates so I know what variables are available to me, for example. This is one of the main reasons why I came to Craft 3 (NOT 2). I am able to enable the profiler in the admin, under the admin user profile, there are two checkboxes that says enable profiler on frontend and CP. However, I can only see the profiler in admin, not on frontend.

I feel like I could extend my own templates from a base template or something that have debugging toolbar builtin somewhere, but I can't find any docs detailing how to do that.

### Steps to reproduce

1. Create a fresh new project with composer
2. Go to "My Account" page, check both "Show the debug toolbar on the front end" and "Show the debug toolbar on the Control Panel". And save.
3. Navigate to frontend. Refresh the page, the profiler is not showing up at the bottom of the page.

### Additional info

- Craft version: 3.0.0-beta.17
- PHP version: 7.1.4
- Database driver & version: Mysql 5.6.35

**Comment by narration-sd** [comment]
Michael, it’s a per-user setting. 

So if you are logged in as admin, and view the front end, you should see icon on the lower right corner which opens the Yii bar.

If you want it to show for a front-end-only user, the checkbox needs to be ticked on that user’s profile.

**Comment by narration-sd** [comment]
Updated reply after running up a Craft 3 box at this late hour -- it work as it has for months.

**Comment by yellowmamba** [comment]
Unfortunately I don't see any widget down on the bottom right corner.

After Craft is installed, I went to `/` page on the frontend, and it was returning 404 because I didn't have any template for homepage yet. Then I created a single section for homepage with the template name "home". I have `home.html` under `templates` folder, with only the following in the template:
```
<h1>Welcome</h1>
```
Nothing else is showing except for the bloody obvious h1 title.

PS: I am logged in as admin when viewing frontend.

**Comment by narration-sd** [comment]
Well, for one, Michael, I’d suggest keeping your language decent, and also having a little patience.

Craft is an exceptionally well-designed and generally entirely dependable system. You’ve chosen to work on the Beta, with all the caveats on that. Still, we are dealing with computers…

It’s very late here (west coast NA) and I am going to have to leave you with this. I’m not staff of anybody, just doing you the courtesy as a new  user.

The test I set up did something very similar to your setup, and worked as this always has – I was just checking memory, as simple arrangements easily can miss something. 

The one thing I can think of to suggest is that you may not have set up any fields yet in your test home section. Thus the entirety of Craft’s content handling may not be functioning on it yet, thus not firing the debug bar buttons.

Try adding just a single simple text field – you create that under Fields, and might as well call it Body. Then add it to your Home Section’s default entry type, using the graphical tool there. Save, and got to Entries for the Home page, put something in the Field, and save. Now try the page from the front-end. You an also add <p>{{ body }}</p> (the field handle) in the template to see what you wrote. At this point I’d expect also to see the buttons. 

If this doesn’t work, report back, and advice will be forthcoming am sure. 

Regards,
Clive

**Comment by yellowmamba** [comment]
@narration-sd Sorry, didn't mean to sound offensive or anything, just pulling my hairs over this issue i've been dealing all day. I will try to avoid swear words in this issue.

Just set up a demo site and looking at the Happy Lager setup in the CMS, looks like I did miss quite a bit, including fields as you suggested, so I will give it a go when I am back at work.

Appreciate your patience and courtesy to offer help late into the day.

**Comment by Rias500** [comment]
@yellowmamba The debug bar needs a full html page to hook into, just an `<h1>` won't work.

**Comment by narration-sd** [comment]
@Rias500  Just so, and thanks for pitching in.

In fact what it needs is a `<body>` tag -- actually a `</body> --  to hook to and inject the extras.

Too easy to look for complex reasons in a complex  system...especially at marginal hours of a day.....

Michael @yellowmamba, thanks also, and good fortune as you move ahead now, in the Craft community.

**Comment by narration-sd** [comment]
@yellowmamba  In fact, no Section or fields are required either, meant to say, so you can use this even before beginning  that sort of work, which is what I think you were trying to do.

**Comment by yellowmamba** [comment]
Yeah, that did the trick. Too easy to overlook things like this when you just want to spin up a new thing to play with. How else would Craft inject javascript without identifying the <body> tag in your own template?

Thanks guys!
