### ISSUE TITLE
Error templates not rendering

### ISSUE THREAD

**Issue by nateiler** [craftcms/cms#1715]
Dropped this guy in a template `{% exit 404 %}` and expected my `404.twig` template (in the template root) to be rendered.  I do not have error prefix config setting set.

- Craft version: beta-17

**Comment by brandonkelly** [comment]
Working on my end, however note that you must have Dev Mode _disabled_ if you want to avoid the exception debug view.

**Comment by nateiler** [comment]
Ah hell.  I'm an idiot.

Sorry for the troubles.

**Comment by mattstein** [comment]
Ugh. You're not alone @nateiler, for whatever that's worth.

**Comment by brandonkelly** [comment]
You guys stumped @takobell too, FWIW!

**Comment by mattstein** [comment]
![Giphy](http://media1.giphy.com/media/5VKbvrjxpVJCM/giphy.gif)

**Comment by narration-sd** [comment]
haha -- I have to say this has  bitten me before as well.

I put it down to sensory overload -- in the land of javascript packagers...
