### ISSUE TITLE
user perm for Update check allows screen, but not actual check

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1719]
### Description

You can with perms and not admin set use the Updates screen, but only the indefinitely spinning icon results -- no successful check.

### Steps to reproduce

1. Be logged in as a user with group allowing Updates page
2. Use the page
3. See spinner spinning -- and that's all.

### Additional info

PHP version	7.1.4-1+deb.sury.org~xenial+1
Database driver & version	MySQL 5.7.17-0ubuntu0.16.04.1
Image driver & version	GD 7.1.4-1+deb.sury.org~xenial+1
Craft edition & version	Craft Pro 3.0.0-beta.17
Yii version	2.0.11.2
Twig version	2.3.2
Guzzle version	6.2.1
Imagine version	0.7-dev
Plugins

Doxter	3.1.2
Standards Agent	2.0.1

**Comment by brandonkelly** [comment]
Just to clarify, the user has permission to access the Updates utility, but not the permission to actually _perform updates_, right?
