### ISSUE TITLE
Error on first save to new folder in S3 (assets field)

### ISSUE THREAD

**Issue by eva-rose** [craftcms/cms#1721]
### Description

Images are being saved to an S3 folder named assetlocation/images/{section.handle}. When the first image is added to a (not-yet-created) folder, there is an error on (attempted) entry save. 

Reviewing in S3 shows that the folder was created along with a corrupt/partial version of the file. On returning to the entry, the user can successfully upload and save the file.

### Steps to reproduce

1. Create an asset field set to save to a not-yet-existent S3 folder.
2. Attempt to save image to that folder.

### Additional info

- Craft version: 2.6.2973
- PHP version: 7.0.x
- Database driver & version: MySQL 
- Plugins & versions: n/a

**Comment by andris-sevcenko** [comment]
I'm not able to reproduce this locally. Can you get in touch via support@craftcms.com?
