### ISSUE TITLE
Other pages entries show up for the user which doesnt have permission to that page

### ISSUE THREAD

**Issue by nexflo** [craftcms/cms#1723]
NewElement belongs to another page. I see it, clicking on it gives me a 403 permission error. I shouldnt see that page at all.

![image](https://cloud.githubusercontent.com/assets/970914/26278896/7fbc3d56-3da5-11e7-8ae5-eb7b96d83b74.png)

**Comment by brandonkelly** [comment]
Can you please send in a ticket from the Craft Support widget on your Dashboard, including the DB backup, and reference this issue # ?

**Comment by brandonkelly** [comment]
Closing due to lack of response. Guessing this is related to #1778.
