### ISSUE TITLE
Enhancement: Allow external user registration/login services

### ISSUE THREAD

**Issue by nexflo** [craftcms/cms#1724]
It would be cool if one could use Google SignIn or LDAP as an authentication provider and the backend.

**Comment by benjolabs** [comment]
For Craft 2 there is the Social Login plugin https://dukt.net/social
I am sure they will support Craft 3 eventually

**Comment by takobell** [comment]
Closing as a dupe of https://github.com/craftcms/cms/issues/1471. Feel free to add a thumbs-up/comment to that one.
