### ISSUE TITLE
inline editing an entry only shows title field on new items

### ISSUE THREAD

**Issue by hiasl** [craftcms/cms#1725]
### Description
Inline editing of entries (by double clicking a selected entry in an entries field) only seems to provide the title field in current Craft3 beta, but no custom fields, if the entry itself was created directly from the selection dialog box.

### Steps to reproduce

1. In an entry field, click the button to select the entry -> dialog box opens
2. Create a new entry and the select it -> dialog box closes, entry is shown in field
3. Double click the entry. Only the title can be changed, but no custom fields.

BUT: if you do not create the entry from within an entry field, but directly via the Craft main navigation, save it, then select and double click it, all custom fields will be shown.

### Additional info

- PHP version	7.1.5-1+deb.sury.org~xenial+1
- Database driver & version	MySQL 5.7.18-0ubuntu0.16.04.1
- Image driver & version	GD 7.1.5-1+deb.sury.org~xenial+1
- Craft edition & version	Craft Pro 3.0.0-beta.18
- Plugins & versions: none

**Comment by brandonkelly** [comment]
Thanks!
