### ISSUE TITLE
Add Focal Points to quick Edit and a clear Focal Point Option would be nice

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#1727]
At the moment Focal Point is not really usable cause it's only direct in the assets to set.
Please add it here:
![image](https://cloud.githubusercontent.com/assets/764292/26310546/68f57742-3f01-11e7-8a21-f07ef9216cf6.png)

And a "clear focalpoint" would be also nice.

**Comment by leevigraham** [comment]
To throw a user story behind this…

Most of our clients upload through the edit UI and then use live preview. In the current implementation they would need to jump between Assets (image editing) and refreshing the edit window.
