### ISSUE TITLE
Dynamic Title format not automatically updating entries when saving entry type

### ISSUE THREAD

**Issue by RitterKnightCreative** [craftcms/cms#1728]
### Description
When setting a dynamic title format for an entry type—in its entry type settings—when you go to save the title format, it does not automatically save the existing entries. You need to manually resave them. 

I'm not sure when this started happening but working on a client project now with a lot of technical information and wanted to use a couple of the existing fields to populate the title. 

I recall a few versions back when Craft would automatically kick off a task to update the new entries. If you go into an entry and save it out manually, it does work.

Craft would also kick back an error message if it couldn't find your fields or your twig format was bad. The only way you'll know is if you go into each entry and resave it, then you'll get the error.

I'm assuming this is a bug end not new behavior?

### Steps to reproduce

1. Set a custom Title Format for an entry type
2. Hit Save in that window
3. Existing entries are not updated with new title format.

### Additional info

- Craft version: Craft CMS 2.6.2980
- PHP version: 7
- Database driver & version: mysqlnd 5.0.12-dev - 20150407 (MAMP)

**Comment by brandonkelly** [comment]
Craft 2 doesn’t automatically re-save entries after an Entry Type has been updated. (Craft 3 does, though.) To get all the titles updated, just re-save the main Section settings as well, even if you don’t change anything.

**Comment by RitterKnightCreative** [comment]
> To get all the titles updated, just re-save the main Section settings as well, even if you don’t change anything.
Odd. I can see a pending task that says "resaving entries" but the titles are not updated.

**Comment by brandonkelly** [comment]
is there a stuck task in the queue before it or something? The titles won’t be updated until that "resaving entries" task is finished.

**Comment by RitterKnightCreative** [comment]
The task appears to finish. The only way I can get the titles to update is manually going into both of them and saving. Tried on another install as well, same thing.

**Comment by brandonkelly** [comment]
Doh, thanks, was able to reproduce. Fixed for the next release!
