### ISSUE TITLE
User with user group cannot create categories

### ISSUE THREAD

**Issue by fmolina24** [craftcms/cms#1729]
### Description
Seems that when I create a user group with permissions to edit a category group and assign that user group to a user and try to create a new category with that user i get the following.

Unauthorized
User not permitted to edit content in any sites

### Steps to reproduce

1. Create category group
2. Create user group that has access to the admin and can edit that category group
3. Assign that user group to a user
4. Log in with that user
5. Try to create a new category 
6. Notice error.

### Additional info

- Craft version: Craft CMS 3.0.0-beta.18
- PHP version: 7.1.1 (MAMP PRO)
- Database driver & version: MySQL 5.5.42
- Plugins & versions: none

**Comment by brandonkelly** [comment]
Thanks!
