### ISSUE TITLE
Add label to Post date & Expiry date fields icons so they're clickable

### ISSUE THREAD

**Issue by jamie-jenks** [craftcms/cms#1730]
### Description
Would be nice to be able to click the `Post date` & `Expiry date` icon which would click the input element. Its a very small feature but I have had clients come back to saying that its not working when all they had to do was click slightly to the right...

### Steps to reproduce

1. Open any entry

### Additional info

- Craft version: N/a
- PHP version: N/a
- Database driver & version: N/a
- Plugins & versions: N/a

**Comment by brandonkelly** [comment]
Agree, this would be an improvement. Maybe the icons can become `<label>`s.
