### ISSUE TITLE
Category Group Relationship Field cannot resolve field handle

### ISSUE THREAD

**Issue by grantnhoward** [craftcms/cms#1731]
### Description
Creating a custom relationship field on a category group results in the following error:

Exception – yii\base\Exception

Invalid field handle: availableBrands 
1. in /home/domain/vendor/craftcms/cms/src/base/Element.php at line 1826
2. in /home/domain/vendor/craftcms/cms/src/base/Element.php at line 1491 

### Steps to reproduce

1. Create category group Vehicles (and add a Vehicle)
2. Create category group Brands (and add a Brand)
3. Create new relationship field AvailableBrands that selects from the Brands category
4. Add AvailableBrands field to the Vehicles category group field list
5. Try to view a single Vehicle category in the admin

### Additional info

- Craft version: 3.0.0-beta.18
- PHP version: PHP 7.0.15-0ubuntu0.16.04.4
- Database driver & version: Mysql 5.6.27
- Plugins & versions: Element API, AWS S3

**Comment by brandonkelly** [comment]
Not able to reproduce this unfortunately. Can you please reproduce the issue and then send a DB backup plus the contents of storage/logs/ over to support@craftcms.com ? Thanks!

**Comment by grantnhoward** [comment]
Just sent over the files now, thank you!

**Comment by brandonkelly** [comment]
Thanks! This ended up being related to #1725, which has been fixed for the next release.
