### ISSUE TITLE
Embedded video removed on-save

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/cms#1732]
### Description

Videos embedded inside redactor rich text fields are removed on-save.

### Steps to reproduce

1. Embed video using Redactor
2. Save entry

### Additional info

- Craft version: 2.6.2980
- PHP version: 7

**Comment by brandonkelly** [comment]
They’re probably getting stripped out by HTML Purifier. If you trust your authors to not try to do anything malicious, you can disable the “Purify HTML?” setting on your Rich Text field.

Worth noting that in Craft 3, it’s possible to customize the HTML Purifier config in the same way you can configure the Redactor config, so you could override the defaults to allow the video embeds there.
