### ISSUE TITLE
Remove support for manual plugin installation

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/cms#1734]
We should remove support for manually installing plugins in the plugins/ folder, because:

- Composer-installed plugins run faster, thanks to Composer’s [class map generation](https://getcomposer.org/doc/articles/autoloader-optimization.md#optimization-level-1-class-map-generation)
- it would drastically simplify the Plugins service, which currently has a lot of fallback code for plugins that aren’t Composer-installed
- it would make it less awkward that all plugins (even those that aren’t real Composer packages) must have a `composer.json` file
- Composer will be used behind the scenes to auto-update plugins, and it would be nice to have _all_ plugins be auto-updatable, so we can put an “Update All" button in there.
- Plugins’ documentation won’t have to provide alternate instructions for manual installs.
- those who don’t like Composer will have an even better way to install/update plugins once the plugin store is available
- for internal plugins, Composer can load local packages without going through Packagist using [`path` repositories](https://getcomposer.org/doc/05-repositories.md#path).
- it may help encourage developers to build project-specific functionality as a [Yii module](http://www.yiiframework.com/doc-2.0/guide-structure-modules.html) rather than a plugin

**Comment by narration-sd** [comment]
This sounds like a good path, added a thumbs up. Just wondering if there are any downsides in not having a specifically Craft interface plugins provide to, giving a funnel point sanitizing access (if sanitation ussful?).

**Comment by brandonkelly** [comment]
@narration-sd not sure I’m following you there 🤔

**Comment by narration-sd** [comment]
well, kind of an open comment, intending to spur thought. 

I.e. is there anything Craftish an added module might want to be required to service?

I see not from a Yii-centric point of view, but if there's some integrity you need to protect on Craft side -- or even just to place a marker that this new module is involved with Craft, for inventory or future functionality even if it's just cataloging....

**Comment by narration-sd** [comment]
p.s. here's an integrity check example for you maybe, depending on how you think.

Right  now in Slack, @benparizek had a plugin fail to run across two different C3 environments. It turned out to be letter-casing in the plugin name....not exactly a Craft problem, but something it could failsafe if it had a look at module intending to be run.

**Comment by brandonkelly** [comment]
Resolved by 5635ceeaf74790495a4bc7977c93fd7214bfba14
