### ISSUE TITLE
Searching entries with categories with 3 letters doesn't return any result

### ISSUE THREAD

**Issue by vincentritter** [craftcms/cms#1735]
### Description
When creating categories with 3 letters, or less, and assigning them to an entry - searching for entries containing the word/category returns no results. This is true for both front-end and admin 'entries' filter.

### Steps to reproduce

1. Create a few entries with a category picker
2. Create a category named 'iOS' or anything with 3 letters i.e 'cms'.
3. Create another category with 4 letters or more i.e 'Craft'
4. Assign entries with the created categories. Note that the category name shouldn't appear in the title or the entry.body - just to keep the test fair.
5. For good measure clear your search index.
6. Search for the 3 letter category on the front end (same issue in admin 'entries' section)
7. No results (entries) are returned for the 3 letter category.
8. Search the 4 letter or more category word.
9. Results are returned.

### Additional info
If you rename the 3 letter category and make it a 4 letter one, searching it will show results as normal.

Any questions, let me know.

- Craft version: Craft CMS 3.0.0-beta.18
- PHP version: 7
- Database driver & version: MySQL

**Comment by vincentritter** [comment]
@brandonkelly - I am happy for you to use my installation and/or database if you can't reproduce it. Just let me know.

**Comment by takobell** [comment]
Craft (2 and 3) have a hard-coded minimum word length of 4 that you're running into. https://github.com/craftcms/cms/blob/develop/src/helpers/Search.php#L97-L103

I suppose an argument could be made for opening that up as a config option, so feel free to create a new issue and we'll tag it as a feature request and reference this one.

But keep in mind even if we did that, both [MySQL](https://dev.mysql.com/doc/refman/5.7/en/fulltext-stopwords.html) and [PostgreSQL](https://www.postgresql.org/docs/9.1/static/textsearch-dictionaries.html) have their own stop word lists they'll use for searches to exclude lots of < 4 letter words they consider noise (a, the, an, but, etc.).

**Comment by vincentritter** [comment]
@takobell - That explains it! 

OK - would be great to have as a config option so I'll create a new issue.
For my specific case I would never consider using the stop words as the name.

**Comment by narration-sd** [comment]
Well, I would be thoughtful, actually careful about this. 

It's not just stopwords needing to be considered. 

for example, https://stackoverflow.com/questions/1585611/mysql-full-text-search-for-words-with-three-or-less-letters 

When this issue first showed up, I was remembering what may be a root, that there's a perfomance issue with string search algorithms if you let them try short strings.

**Comment by brandonkelly** [comment]
As of the next Craft 3 release (RC6), Craft will fall back to a non-full-text search query in the event that the search term is less than 4 characters, so this shouldn't be an issue anymore.
