### ISSUE TITLE
Allow change to minWordLength for search via config option

### ISSUE THREAD

**Issue by vincentritter** [craftcms/cms#1736]
Would be great to have an option to allow changing the minimum word length for search.

Particular useful when using categories with 3 letters or less (you never know).

If added, there should be a note about the stop words in the documentation also.

**Comment by takobell** [comment]
For reference: https://github.com/craftcms/cms/issues/1735

**Comment by brandonkelly** [comment]
Also: https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_ft_min_word_len

**Comment by vincentritter** [comment]
I guess it should stay as it is. Considering you probably took this decision based on the default value anyway. I don't think this was ever an issue in the past so I don't want to create any unknowns from getting this added. I value performance and don't want to add to a negative impact or support nightmare.

This was more a specific issue for my own project where categories are sometimes 3 letters like 'iOS' or 'C#' - which caught me out. Perhaps I just need to rethink that. Beyond this issue though.

**Comment by brandonkelly** [comment]
As of the next Craft 3 release (RC6), you will be able to add this to `config/app.php` in the event that you’ve changed MySQL’s [ft_min_word_len](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_ft_min_word_len) setting to something other than `4`:

```php
return [
    'components' => [
        'search' => [
            'minFulltextWordLength' => 1, // or whatever ft_min_word_len is set to
        ],
    ],
];
```
