### ISSUE TITLE
Craft Commerce throws an error when submitting a new shipping and a new billing address in the same form with "sameAddress" set to 0.

### ISSUE THREAD

**Issue by tfortier** [craftcms/cms#1737]
### Description

I was submitting a Craft Commerce form to update the shipping and billing address. WHen suppllying a new shipping and billing address, I was given an error. When using the "sameAddress" field (setting it to 1) no error. 
The error was about a model being expected and null being received. I digged up and found it was comming from around line 259 in controllers/Commerce_CartController. Right above there is an if with a single = and a reference to $billingAddressId which at this point is undefined.

I changed the code to this which seem to work (lines 248 to 261) :  

```
if (!$sameAddress)
            {
                $billingAddressId = craft()->request->getParam('billingAddressId');
                if ($billingAddressId != "new")
                {
                    $billingAddress = craft()->commerce_addresses->getAddressById($billingAddressId);
                }
                else
                {
                    $billingAddress = new Commerce_AddressModel();
                    $billingAddress->setAttributes(craft()->request->getParam('billingAddress'));
                }
                $result = craft()->commerce_orders->setOrderAddresses($cart, $shippingAddress, $billingAddress);
            }
```

### Steps to reproduce

Send a cart update form with a new Shipping and a new Billing address with sameAddress set to 0.

### Additional info

- Craft version: 2.6.2980 (Pro)
- PHP version: 7.0.19
- Database driver & version: MySQL 5.6.35-log
- Plugins & versions: 
    - Ansel 1.0.1
    - Backup Pro 3 3.4
    - Commerce 1.2.1342
    - Elixir 2.0.0 (Custom plugin)

**Comment by takobell** [comment]
Can you shoot an email to support@craftcommerce.com with a link to this issue?  We haven't moved Commerce to a public Github repo (yet), so we're still tracking all Commerce issues/bugs the old fashioned way... through our help desk software.
