### ISSUE TITLE
Error in routes from Control Panel

### ISSUE THREAD

**Issue by fractorr** [craftcms/cms#1741]
### Description
I have been playing with Routes in the admin and having an issue with it.  I am getting odd behavior in the templates but seems to work when using `config/routes.php`

### Steps to reproduce

Here is what I have tried.

Admin Panel

    product/view/(slug)       /product/index             Gets 404 error - Template not found
    product/view/(*)          /product/index             Gets 404 error - Template not found
    product/view/test         /product/index             No error - works as expected

`config/routes.php`

    return [
        'product/view/<slug:[^\/]+>' => ['template' => 'product'],
    ];

### Additional info

- Craft version: 3.0.0-beta.18
- PHP version: 7.1.5-1+deb.sury.org~xenial+1 (cli) (built: May 11 2017 14:07:52) ( NTS )
- Database driver & version: 5.7.18-0ubuntu0.16.04.1 (Ubuntu)
- Plugins & versions:
Category Tree 1
Contact Form 2.0.0
Cookies 1.1.4
Json 1.0.6
Svg 1.0.2

**Comment by takobell** [comment]
Just to clarify, are you saying the routes work as expected when you define them in `config/routes.php`, but they don't work as expected when you define them in the Control Panel under Settings->Routes?

**Comment by carlcs** [comment]
@takobell it’s just the routes stored to the DB, yes. There seems to be an issue with too many characters being escaped.

**Comment by brandonkelly** [comment]
@fractorr Can you post a screenshot of your Settings → Routes index view please?

**Comment by brandonkelly** [comment]
Closing due to lack of response.

**Comment by carlcs** [comment]
<img width="428" alt="bildschirmfoto 2017-07-07 um 14 55 15" src="https://user-images.githubusercontent.com/7516543/27958629-5b34445c-6324-11e7-9cc8-12da4c448ec3.png">

@brandonkelly I just re-created that setup @fractorr is describing and can confirm that with the above route setup in Settings > Routes, requests to http://craft3.dev/product/view/test respond with 404 errors.

**Comment by brandonkelly** [comment]
@carlcs Thanks, can confirm that doesn't work.
