### ISSUE TITLE
Rendering twig template from console app results in error due to session.

### ISSUE THREAD

**Issue by nateiler** [craftcms/cms#1742]
We have an email by key task that is kicked off via console application.  The email is rendered via key and therefor the body is rendered via `View::renderString`.  Since the console application does not have a session, we're running into issues with `View::registerAssetFlashes`. 

vendor/craftcms/cms/src/web/View.php:843

Possible solution:
```
protected function registerAssetFlashes()
    {

        if(Craft::$app instanceof Application) {

            $session = Craft::$app->getSession();

            foreach ($session->getAssetBundleFlashes(true) as $name => $position) {
                if (!is_subclass_of($name, YiiAssetBundle::class)) {
                    throw new Exception("$name is not an asset bundle");
                }

                $this->registerAssetBundle($name, $position);
            }

            foreach ($session->getJsFlashes(true) as list($js, $position, $key)) {
                $this->registerJs($js, $position, $key);
            }

        }

    }
```

### Additional info

- Craft version: Latest
- PHP version: 7.0

**Comment by brandonkelly** [comment]
Main issue here is that the `EventTagFinder` / `EventTagAdder` Twig node visitors should only be called for templates rendered with `View::renderPageTemplate()` – not `renderTemplate()`, `renderTemplateMacro()`, `renderString()`, or `renderObjectTemplate()`.

**Comment by nateiler** [comment]
No clue what any of that means ... but thanks.

**Comment by brandonkelly** [comment]
haha, was a note to myself :)
