### ISSUE TITLE
Section fields desaparecido, when changing Section template

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1743]
### Description

You change a section template setting, say from index to _entry. 
You have no fields.
The database still has values, which reappear when you manually reinstate the fields on the entryType
I tried and exercised this only on a Single, but probably the same for any Section type. And would it disappear all entryTypes->fields? Imagining so...
And multiply by Sites?? Likely also...

### Steps to reproduce

1. Have a Section working nicely, with some fields besides Title
2. change the Section>Site Settings>Template to something else, like index to _entry, for example, or back.
3. Each time you change it, the entryType turns up with no fields besides Title
4. When you reinstate the entryType's fields, they work, including Matrix ones, and still have their content in the database. Thank goodness for that...

### Additional info

PHP version	7.1.3-3+deb.sury.org~xenial+1
Database driver & version	MySQL 5.7.17-0ubuntu0.16.04.1
Image driver & version	Imagick 3.4.3RC2, ImageMagick 6.8.9-9
Craft edition & version	Craft Personal 3.0.0-beta.18
Yii version	2.0.11.2
Twig version	2.3.2
Guzzle version	6.2.1
Imagine version	0.7-dev
Plugins

Bactrian	1.0.0
Trimmer	1.0.0
Standards Agent	2.0.1
Video Embed	3.0.0

**Comment by brandonkelly** [comment]
Looks like this only affects Singles.

**Comment by brandonkelly** [comment]
Also looks like no change is necessary to the section settings; just re-saving the section without changing anything will also wipe out its entry type’s fields
