### ISSUE TITLE
Kill the global `user` variable

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#1744]
Feature request for Craft 3...

**It's time to kill the `user` global variable.**

The `user` global variable has always been an alias for `currentUser`, which makes far more sense in context. I've personally found that the `user` variable causes some confusion, since it's not obvious that it's referring to the currently logged-in user. Similarly, there are many cases where you'd want to actually _define_ a variable named `user`, leading to further confusion and/or conflicts.

`user` is not defined in the docs. `currentUser` is...

https://craftcms.com/docs/templating/global-variables#currentUser

`user` was formally deprecated in Craft 1.2.2333 (in September 2013)...

https://craftcms.com/changelog#1-2-2333

>_“Added a new currentUser global variable set to the currently logged-in user, if any. (‘user’ is still available but **deprecated indefinitely**.)“_

When you consider all of those factors together, I don't see a valid case for keeping `user` alive.

**Comment by brandonkelly** [comment]
You're all savages!

**Comment by lindseydiloreto** [comment]
Lol awesome, thanks Brandon!

<img src="http://31.media.tumblr.com/0b4c0d8ec01974a32d35e69d1685d00c/tumblr_mok4d5ZCsv1spkic4o1_400.gif">
