### ISSUE TITLE
Use of undefined constant IMG_WEBP - assumed 'IMG_WEBP'

### ISSUE THREAD

**Issue by noffsin6** [craftcms/cms#1750]
### Description
I get this issue on Craft CMS 3 Beta 19 (and any previous versions I have tried):

 PHP Notice – yii\base\ErrorException
Use of undefined constant IMG_WEBP - assumed 'IMG_WEBP'

I will attach the full error page as an image (gitub doesn't accept html files).

I am not using any webp images so if I comment out the IMG_WEBP => ['webp'] in C:\inetpub\craft_cvm\vendor\craftcms\cms\src\services\Images.php it works.

![yii_base_errorexception_-_2017-06-01_09 48 35](https://cloud.githubusercontent.com/assets/8354935/26683402/a822affe-46b1-11e7-9400-998b755a19c6.png)

### Steps to reproduce

1.  Install Craft CMS Beta through composer
2.  

### Additional info

- Craft version:  Craft 3 Beta 19
- PHP version: 7.0.9
- Database driver & version:  MySQL 
- Plugins & versions: No plugins installed

**Comment by brandonkelly** [comment]
@andris-sevcenko looks like those other `IMG_*` constants are defined by GD, which is an optional requirement, so we shouldn’t assume that they’re defined either.

**Comment by andris-sevcenko** [comment]
@brandonkelly if the code makes it past the Imagick check, it's safe to assume that GD is in play.

That constant is available only since PHP 7.0.10, though. I'll add some checks.

**Comment by brandonkelly** [comment]
@andris-sevcenko Imagick defines the same `IMG_*` constants, and assigns the same values as GD? If not, maybe we should be defining our own constants?

**Comment by andris-sevcenko** [comment]
If Imagick is used, the code branches off earlier and the constants are never reached (https://github.com/craftcms/cms/blob/develop/src/services/Images.php#L107-L109)
