### ISSUE TITLE
Emoji makes plain text fields implode

### ISSUE THREAD

**Issue by ow** [craftcms/cms#1753]
### Description
If you put an emoji into any plain text field, it implodes with an error that it couldn't insert into the database, presumably due to encoding.`CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x91\x8A' for column 'field_testimonial' at row 1`

### Steps to reproduce

1. Create a plain text field
2. Try save an emoji in it
3. Oh no

### Additional info

- Craft version: 2.6.2980 (Personal)
- PHP version: 7.0.15-0ubuntu0.16.04.4
- Database driver & version: MySQL 5.7.18-0ubuntu0.16.04.1
- Plugins & versions: 
    - Analytics 3.4.4
    - Buffer 1.0.3
    - Contact Form 1.8.1
    - Disqus 1.1.1
    - Excerpt 1.0.0
    - Footnotes 1.1.2
    - Hacksaw 2.0.0
    - jSocial 1.1.0a
    - Navee 1.3.0
    - OAuth 2.0.3
    - Publish to Apple News 1.0.1
    - Redactor Image Position 1.0.3
    - SEO 1.1.46
    - Sitemap v1.0.0-alpha.4

**Comment by ow** [comment]
I just noticed this is resolved in #1627 but that's no good for Craft 2... totally understand if you can't/won't fix though.

**Comment by brandonkelly** [comment]
Emoji is only supported by Rich Text fields when using MySQL (as is always the case in Craft 2).

**Comment by mattandrews** [comment]
I can understand the technical reasons for not supporting emoji in plain text, but could this error be handled more gracefully? When I experienced this, the entire entry became uneditable and I had to hit the database to restore an older revision manually. 

Would it be possible to simply strip it out when saving, rather than breaking the entire entry?

**Comment by brandonkelly** [comment]
Not sure about stripping it out, but we could definitely handle it more gracefully, with a validation error.

**Comment by brandonkelly** [comment]
Even better – if you’re running PHP 5.4+ , Plain Text fields will now convert emojis to `:shortcodes:` when saving to the database (and back to unicode when retrieving the data).

**Comment by mattandrews** [comment]
🙏  incredible work, thank you @brandonkelly!

**Comment by narration-sd** [comment]
...he's like that...thought  saw this come by and thought it was pretty cool too :)

**Comment by nathanielperales** [comment]
Is this fixed for Craft 2 or just Craft 3?

**Comment by brandonkelly** [comment]
Both – but the fix won’t apply to Craft 2 if your server is still running PHP 5.4, as the library we’re using requires PHP 5.4+.

**Comment by nathanielperales** [comment]
Thanks for the reply Brandon. I just tried it with Craft 2.6 and in my server info I see:

PHP Version | 7.0.22-0ubuntu0.16.04.1

But I'm still getting the error when trying to save an emoji in a plain text field.

**Comment by brandonkelly** [comment]
What version of Craft 2.6? Plain Text fields just got support for emojis in this week’s 2.6.3004 update. Also worth noting that not _all_ emojis are supported – just the ones [LitEmoji](https://github.com/elvanto/litemoji) supports.

**Comment by nathanielperales** [comment]
I see. Yeah one of the feeds uses this one: 🤘 which is a newer Emoji. Thanks!
