### ISSUE TITLE
Entry revision data is empty

### ISSUE THREAD

**Issue by iliaivanov** [craftcms/cms#1755]
### Description
Entry revisions data is displayed correctly in the UI, but when trying to access it programmatically all  fields are having `null` values. For instance I have Entry with `lightSwitch` field. I created number of Entry revisions with different lightswitch positions being selected. When I switching revisions in UI, lightswitch value is displayed correctly: off when it was disabled and on when was activated.
Problem starts when I trying to access this revision values in code. I have a method to extract last (aka current) revision values:
```
       public static function getEntryLastRevision(Entry $entry)
	{
		$revisions = Craft::$app->getEntryRevisions()->getVersionsByEntryId(
			$entry->getId(),
			Craft::$app->getSites()->getPrimarySite()->id,
			1,
			true
		);

		if (empty($revisions)) {
			return false;
		}

		return reset($revisions);
	}
```

When I saved different revisions with different light switch positions, I also changed title. By title value I can confirm that method returned correct revision, but light switch field value was null when it was suppose to be 1.

### Steps to reproduce

1. Create section.
2. Add lightswitch field to it.
3. Create different entry revisions with different lightswitch positions.
4. Access revisions from code using `Craft::$app->getEntryRevisions()->getVersionsByEntryId()` service method.

### Additional info

- Craft version: Craft::$app->getEntryRevisions()->getVersionsByEntryId(
- PHP version: 7.0.17
- Database driver & version: mysql 5.7
- Plugins & versions: Amazon S3, Element API - both latest.

**Comment by brandonkelly** [comment]
This was by design, but I just added a `$withContent` argument to `getVersionsByEntryId()` and `getDraftsByEntryId()` which you can set to `true` to get the version/draft content included in the results.

**Comment by iliaivanov** [comment]
Thank you @brandonkelly! Is there any chance this enchantment will be added to the next release?

**Comment by takobell** [comment]
@iliaivanov it'll be in the next Craft 3 release: https://github.com/craftcms/cms/commit/58eddbddcd8dfa7aa6b22a6139d008fb990017dd
