### ISSUE TITLE
Creating a new Element() is no longer aware of its associated fields (as easily)

### ISSUE THREAD

**Issue by nateiler** [craftcms/cms#1756]
I understand this is a result of a conscious design choice (not a bug) that was recently made, but the impact makes it rather cumbersome to create new elements for plugin development.  What was nice with the previous implementation, was the leniency and auto-resolving within the element.

Previously, this was sufficient.

```php
$entry = (new Entry([
'typeId' => 1,
'sectionId' => 1
]);

$entry->setFieldValues($values);

// Bingo bango
```

Perhaps there is a bigger design constraint, but it seems if a fieldLayoutId isn't present on the element, it could revert to the prior logic of using the entry type, category group, global type, etc.

**Comment by narration-sd** [comment]
@nateiler  I was curious about this, as I have some ancient-by-now code that works still, if it uses Yii's similar (Model::)setAttributes() rather than the Element setFieldValues() call.

I wondered how it did that, and discovered the following was my setup code in Craft 2, still appropriate:
```
        private function _setUpEntry(&$entry)
	{
		$entry->sectionId = $this->sectionId;
		$entry->typeId = $this->entryTypeId;
		$entry->authorId = $this->authorId;
                $entry->fieldLayoutId = $entry->getType()->fieldLayoutId;
		$entry->enabled = true;

		return true; // unless we do more error checking
	} 
```

I'm not sure then where automating the fieldLayoutId could be arranged, as you are free to create an Entry without having  set the typeId until after?

**Comment by nateiler** [comment]
@narration-sd So we typically do something similar as well.  The more I think about this the more it's not that big of an inconvenience.  What really brought this up was we were building an element config array.  Imagine an 'Event' service class.  Within that class you can create an In-Person or Webinar type event.

```php
public function create(array $config = [])
{
    $config = ['sectionId' => 1] + $config;
    return new Entry($config);
}

public function createWebinar(array $config = [])
{
    $config = ['typeId' => 1] + $config;
    return $this->create($config);
}

public function createInPerson(array $config = [])
{
    $config = ['typeId' => 2] + $config;
    return $this->create($config);
}
```

Something like that no longer works.  We can easily add another step in there to get and set the fieldLayoutId.  My initial reaction is, we should already know it via the entry type so why not just used it.  Anywho

**Comment by narration-sd** [comment]
Yes, that's kind of what I thought you were doing.

Apology for crudeness of my code above; was in a terrific hurry at the time about other things. 

But -- what about using good old object polymorphism to your advantage?

- have a class for each kind of entry, including one encapsulating Entry itself
- have a parent class, whose constructor calls a create() method, which will be the child's
- have the parent constructor set the fieldLayoutId after create -- one means at present
- if really the layout  id were set sometimes by alternate means, make that a virtual method also
- child constructors just call the parent

I'm still thinking other  languages, but I suspect php's sort of unusual objects will do this?

**Comment by nateiler** [comment]
I believe this is related to #1797

**Comment by brandonkelly** [comment]
Yep, and as of Beta 20 it will no longer be necessary to set `fieldLayoutId` on elements, thanks to 540cf7f6da17dbb9f8d0a11c7d4a73c7d46e4b33
