### ISSUE TITLE
devMode not being observed during update.

### ISSUE THREAD

**Issue by billythekid** [craftcms/cms#1757]
### Description
On some server environments using PHP7.1  the "Non well-formed numeric value" error(notice) can prevent updates from working. (Adding `error_reporting(0);` to app/bootstrap.php after the error reporting level has been set is a workaround for this).

### Steps to reproduce

1. Try to hit the update button on a craft install on a server running php 7.1 where the php.ini is set in a way that returns errors, I suppose.

### Additional info

- Craft version: lower than 2.6.2981
- PHP version: 7.1
- Database driver & version: n/a
- Plugins & versions: n/a

**Comment by takobell** [comment]
Any chance you've got the `craft/storage/runtime/logs` files that still has this error with a stack trace in it? Or a box already setup where it's reproducible and can grab the stack trace?

**Comment by takobell** [comment]
I'm not able to reproduce this so going to close, but feel free to comment with any additional info and we can always re-open.
