### ISSUE TITLE
FR: Allow subpages for a plugin's settings

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#1759]
Some plugins (like Smart Map) have a _ton_ of settings. Managing them all on a single page is pretty unwieldy...

![settings](https://cloud.githubusercontent.com/assets/5309692/26797871/49b566ac-49e3-11e7-803f-3e0677f68f11.png)

It would be great if I could break this into a series of subpages. I know I could already do that via the sidebar nav, but there are two reasons why that feels wrong:

1. You'll never really need to access Smart Map settings on a regular basis, so it's silly for this to occupy space in the side nav.
2. These are all _settings_... they only belong in the plugin's settings area. It feels very weird to disguise them as normal CP pages when they'd all be trying to manage the plugin's settings.

**Would it be possible to allow multiple settings pages for plugins?**

**Comment by brandonkelly** [comment]
Also see [Advanced Settings Pages](https://github.com/craftcms/docs/blob/master/en/plugin-settings.md#advanced-settings-pages) in the docs.

**Comment by lindseydiloreto** [comment]
Good thinking, thanks @brandonkelly!
