### ISSUE TITLE
Installation error - An internal server error occurred.

### ISSUE THREAD

**Issue by traffic-dev** [craftcms/cms#1760]
### Description
Hi, I got an error when I was trying to install Craft 3.
"An internal server error occurred."

Any solution for this?

Thanks a lot!

**Comment by takobell** [comment]
If it's a Craft generated 500 Internal Server error, the underlying error message should be in the `craft/storage/logs` files.  If it's a web server generated 500 ISE, it should be in your web server's error logs.

**Comment by traffic-dev** [comment]
Thank you!

**Comment by takobell** [comment]
Going to go ahead and close, but just respond if you need help figuring out the error message!
