### ISSUE TITLE
assets.onReplaceFile never raised

### ISSUE THREAD

**Issue by stefanmf** [craftcms/cms#1761]
### Description

According to docs, assets.onReplaceFile should be raised, when an asset file is replaced. The event is never raised.

### Steps to reproduce

1. Add the following code to a plug-in init() function: 
```
craft()->on('assets.onReplaceFile', function(Event $event) {            
    Plugin::log('assets.onReplaceFile raised');
});
```	
2. Replace a file via the asset browser
3. Examine log file — the action is never raised

### Additional info

- Craft version: 2.6.2981
- PHP version: 5.5.18
- Database driver & version:
- Plugins & versions:

**Comment by andris-sevcenko** [comment]
The documentation is slightly lacking here - the event will be raised only when the Replace File element action is used. Is this how you're attempting to trigger this?

**Comment by stefanmf** [comment]
No, I tried triggering it by uploading a new file with the same filename as an existing file. Is an event raised in that case? It would be very useful, in order to clear/regenerate image caches and update additional image fields dependent on image size/resolution.

**Comment by andris-sevcenko** [comment]
You make a good point. I'll look into that and I'll see if we can add an event for that as well since that would make sense.

**Comment by andris-sevcenko** [comment]
@stefanmf sorry for the delay - I just fixed this (so that this event gets fired whenever a file is replaced) and the fix should be out with the next Craft release.
