### ISSUE TITLE
Clear cache popup doesn't work the second time without refreshing the whole settings page

### ISSUE THREAD

**Issue by duur222** [craftcms/cms#1762]
### Description

Clear cache popup doesn't work the second time without refreshing the whole settings page

### Steps to reproduce

1. click on the clear cache button
2. click "clear"
3. after the cache is cleared the finished icon appears
4. click outside the popup
5. click again on the clear cache button
6. now the finished icon is still there
7. to use it again the page has to be reloaded

### Additional info

- Craft version: 2.6.2981
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by takobell** [comment]
Known issue that's been resolved in the upcoming Craft 3 and likely won't get a 2.x backport.
