### ISSUE TITLE
XML declaration stripped from uploaded SVG assets.

### ISSUE THREAD

**Issue by mark-cr** [craftcms/cms#1767]
### Description
Craft appears to be stripping XML declarations when uploading SVG assets.

### Steps to reproduce

1. Using Craft 2.6.2982, upload an SVG file (menu-allergen-white-original.svg) containing an XML declaration to an asset source, local or remote.
2. Review the uploaded (menu-allergen-white-uploaded.svg) file--it no longer contains an XML declaration.

### Additional info
[svg-files.zip](https://github.com/craftcms/cms/files/1065161/svg-files.zip)

- Craft version: 2.6.2982
- PHP version: 7.1.5
- Database driver & version: MySQL 5.7.16

**Comment by brandonkelly** [comment]
Fixed in 2.6.2983 - thanks!
