### ISSUE TITLE
TypeError caused by php.ini value bigger than PHP_INT_MAX

### ISSUE THREAD

**Issue by Benjamin-Bur** [craftcms/cms#1771]
### Description
PHP TypeError is thrown when config value with 'M' or 'G' suffix in `php.ini` is bigger than `PHP_INT_MAX`. (E.g. _memory_limit = 2048M_)

> Return value of craft\helpers\App::phpConfigValueInBytes() must be of the type integer, float returned

### Steps to reproduce
Following steps are describing the problem for my environment:
1. Change `memory_limit` to **2048M**
2. Open the login page for craft **/admin**
3. TypeError appears

### Additional info

- Craft version: 3.0.0-beta.19
- PHP version: 7.0.10
- Database driver & version: MySQL 5.6.31
- Plugins & versions:

[Full Stacktrace: TypeError - http___craft3.local_admin_login.pdf](https://github.com/craftcms/cms/files/1067895/TypeError.-.http___craft3.local_admin_login.pdf)

**Comment by brandonkelly** [comment]
Thanks!
