### ISSUE TITLE
HTML Purifier breaks sites on PHP 7.1+

### ISSUE THREAD

**Issue by diggy** [craftcms/cms#1775]
HTML Purifier was singled out as the cause by our hosting provider, unfortunately we do not have extra info. Downgrading to 7.0 fixed the issue.

**Comment by brandonkelly** [comment]
We have tested HTML Purifier without issues on PHP 7.1. Are you on the latest version of Craft? Do you have logs or remember the error you were seeing?

**Comment by diggy** [comment]
The errors occurred on `2.6.2967` and `2.6.2958`

Did you guys test on 7.1.1?

Nothing much in the logs, except maybe the following:

````
[Thu Jun 15 11:36:25.720797 2017] [error] [pid XXX] util_script.c(479): [client xxx.xx.xx.xx:XXXX] End of script output before headers: index.php
[Thu Jun 15 11:36:25.720821 2017] [info] [pid XXX] fcgid_bridge.c(191): [client xxx.xx.xx.xx:XXXX] mod_fcgid: /public/index.php took longer than busy timeout (300 secs)
````

**Comment by takobell** [comment]
Guessing what you're seeing is https://github.com/ezyang/htmlpurifier/issues/134 and https://github.com/ezyang/htmlpurifier/issues/135

**Comment by takobell** [comment]
Updated HTML Purifier to 4.9.3, which should resolve this and will be in the next Craft release.
