### ISSUE TITLE
Display revisions pertaining to site being edited.

### ISSUE THREAD

**Issue by justjoolz** [craftcms/cms#1777]
## Problem.

When a user who only has access to one site clicks the revisions dropdown, they can see all revisions that don’t apply to the content being edited. If they choose them nothing happens, to the edit screen they are on. 

## Solution

Expected behaviour would be to display only the revisions that have modified the particular site version of the entry being edited.

### Additional info

- Craft version: 3.0.0-beta.19

**Comment by takobell** [comment]
Just confirming this is on Craft 3, correct?

**Comment by justjoolz** [comment]
3.0.0-beta.19

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. The entry revision dropdown is only showing versions/drafts that were created for the currently-selected site. (Tested with both an admin account and an account that only has access to one site.)

If you’re still having an issue related to this, please send a DB backup to support@craftcms.com and we can look into it from there.
