### ISSUE TITLE
FR: Ability to add custom url to requireLogin

### ISSUE THREAD

**Issue by theskyfloor** [craftcms/cms#1780]
### Description

I would love it if it were possible to include a query or url string that gets passed to the login page as an optional addition to the requireLogin tag... this could also allow for a custom login page to be used on different pages. Something like:

`{% requireLogin 'podcasts/login' %}`

or

`{% requireLogin 'login?source=podcasts' %}`

Thanks!

**Comment by brandonkelly** [comment]
The `{% requireLogin %}` tag doesn’t take any parameters. In fact you should be getting a Twig parsing error if you tried to do `{% requireLogin 'some/path' %}`.

The path is specified by the [loginPath](https://craftcms.com/docs/config-settings#loginPath) config setting, which should support query strings.

**Comment by theskyfloor** [comment]
This isn't a bug report. Its a feature request. I want to use the logic of requirelogin but be able to route back and forth to different templates. Im asking you to add support for a destination parameter.

**Comment by theskyfloor** [comment]
Let me know if you want me to explain my use case more.

**Comment by brandonkelly** [comment]
Ah gotcha – sorry I got tripped up by the query string bit.

**Comment by theskyfloor** [comment]
Totally - poorly phrased on my part - edited.

**Comment by hiasl** [comment]
maybe this syntax (like include) might  be nice:` {% requireLogin with {...} %}`

**Comment by brandonkelly** [comment]
What is the use case for multiple login pages?

**Comment by theskyfloor** [comment]
The use case would be for login pages that have specialized information on them - let's say someone hits a page about podcasts - we want to redirect them to a login/sign-up page that talks about podcasts or other pages that have specialized messaging on them but I would like to be able to use the logic built into the requireLogin tag to do the automatic routing and redirection to content, etc. Does this describe my use case well enough? Or should I add more detail? Basically I just want to the flexibility to present my content including login pages with different content instead of always having to hit the same login page for everything. That is where the URL string notion came in... at least it could be login?type=podcast and I could do the rest in the template. But even more flexibility is preferred

**Comment by brandonkelly** [comment]
Gotcha. Since there is only one set of user accounts, I think adding this would cause more confusion that it’s worth. However in Craft 3 the `loginPath` config setting can be set to a function, which should work for you:

```php
'loginPath' => function($siteHandle) {
    // Is this the Podcasts page?
    if (Craft::$app->request->getPathInfo() == 'podcasts') {
        return 'podcasts/login';
    }

    return 'login';
},
```

**Comment by theskyfloor** [comment]
I guess I don't understand what one set of user accounts has to do with why this would not work.  I feel like its an edit that makes Craft flexible when it comes to login content pages. 

I get that I won't win this but it seems like such an obvious tweak as its one of the only areas Craft hasn't been flexible for me. 

Could this be added with a plugin?

I don't think its very confusing but maybe you can just add my request to Craft and not document it. Then its not confusing! And I get my functionality : P

One of my hopes with making this a tag parameter was that I could make a matrix block that would allow users to create both a login page and the requireLogin route from the CP. From the sounds of it Craft 3 still won't let me handle this functionality the way I need to (and that my client already works on Wordpress, being able to create login content pages where they want in the content editor)

**Comment by brandonkelly** [comment]
> I guess I don't understand what one set of user accounts has to do with why this would not work.

Not saying it couldn’t be done; just that I think it would add confusion. Multiple login pages implies that there are multiple sets of user accounts (e.g. a Publisher account vs a Listener account), but Craft only has a single set of accounts.

> Could this be added with a plugin?

Yes, plugins can [register custom Twig extensions](https://craftcms.com/docs/plugins/hooks-reference#addTwigExtension) that provide new tags (or override existing ones).

> maybe you can just add my request to Craft and not document it

Then we are essentially building this feature just for you. Better off as a plugin (or just set the `loginPath` config setting dynamically).

**Comment by myriago** [comment]
Hi I was actually looking for something like that and it's the second website I would find this useful. 

Every time when I build a website with a customer area I end up with multiple user groups and multiple levels of access. For example, one group only offers access to posting comments while the other group gives access to the front end form for adding content.

Having the ability theskyfloor suggested would make things easier.
