### ISSUE TITLE
CraftCMS3: accessing fields of matrix blocks loaded with craft.matrixBlocks() does not work and .type() condition not working

### ISSUE THREAD

**Issue by hiasl** [craftcms/cms#1789]
### Description
When you load matrix blocks via craft.matrixBlocks() it's no possible to access its fields' values, they are always NULL. Also the .type() limitation for matrixBlocks() does not seem to work, whatever handle is passed to it will not change the found blocks.

### Steps to reproduce

1. Take an empty craftcms 3 installation
2. Create a field (handle "dates") with a matrix block (type handle "eventDate") containing only one block type which contains some fields (in my case a text field (ticketUrl) and a date (date))
3. Use that field in an entry type of a section (handle "eventEntries").
4. Create ONE entry for that section and enter ONE block of data into the matrix block field
5. Now try to output the matrix blocks' fields with the following loop:

```
{% for entry in [craft.entries.section('eventEntries').one().dates.one(), craft.matrixBlocks.type('eventDate').one()] %}
        <li>ID: {{ dump(entry.uid) }}</li>
        <li>DATE: {{ dump(entry.date) }}</li>
        <li>TEXT: {{ dump(entry.ticketUrl) }}</li>
{% endfor %}
```
As you can see, the first element in the loop is the one loaded via the section, the second one is the same element loaded via matrixBlocks().

Output will be:
```
* ID: string(36) "b57b7916-b2a5-4abb-933a-8637c0655b0e"
* DATE: object(DateTime)#501 (3) { ["date"]=> string(26) "2017-06-15 00:00:00.000000" 
 ["timezone_type"]=> int(3) ["timezone"]=> string(13) "Europe/Vienna" }
* TICKETURL: string(22) "http://www.tickets.com"
==== vs. ==== 
* ID: string(36) "b57b7916-b2a5-4abb-933a-8637c0655b0e"
* DATE: NULL
* TICKETURL: NULL
```
Accessing the two fields in the second iterations outputs NULL, although the UID of the 2 blocks found is the same. In the first iteration it works.

the second problem, that .type() is not working can be verified by changing the passed handle to something not existing. still the same block will be found (but also not working)

### Additional info

PHP version	7.1.6-1 ubuntu16.04.1+deb.sury.org+1
Database driver & version	MySQL 5.6.13
Image driver & version	GD 7.1.6-1 ubuntu16.04.1+deb.sury.org+1
Craft edition & version	Craft Pro 3.0.0-beta.19

**Comment by brandonkelly** [comment]
You must specify the `fieldId` param if you want the content pulled in with the query.

```
craft.matrixBlocks.fieldId(X)
```

**Comment by hiasl** [comment]
and the .type() filter? why does this have no influence?

**Comment by hiasl** [comment]
and sorry, I don't completely understand your answer. Why do I need to specify the field(s) when coming through .matrixBlocks but not through .entries? What is the reason for this behavior?

**Comment by brandonkelly** [comment]
Each Matrix field has its own content table in the database. So Craft needs to know ahead of time which content table it should join in, and the way it figures that out is by knowing which Matrix field ID you’re grabbing blocks for.

**Comment by hiasl** [comment]
I understand what you say, but I do not understand why this is only necessary when accessing through craft.matrixBlocks but not when I come via craft.entries. why do you treat that in a different way?

**Comment by brandonkelly** [comment]
Because when loading entries (or any other element type besides Matrix blocks), the content table is known ahead of time (`craft_content`). So Craft doesn’t need any help figuring that out.

**Comment by hiasl** [comment]
Hi Brandon, thanks for explaining that. This works.
now 2 last questions apart from that:
- is it expected behavior, that .fieldId(int) brings the content, but .fieldId(int[]) (like fieldId([4,20]) does not?
- is it expected behavior, that .type('correctHandle') limits the results to this handle, but .type('unknowHandle') results in all blocks? to me an empty result would be more logical.

Thanks a lot!

**Comment by brandonkelly** [comment]
@hiasl That does seem like unexpected behavior. Since it's unrelated to the main question, can you please post that as a new issue?

**Comment by ohbiko** [comment]
@brandonkelly 
How do I pass the fieldId?  I have something like this and have been trying out different ways but it's not working:
$blocks = MatrixBlock::find()->relatedTo($entry)->fieldId([33])->all();

Also, what's an easy to also find the fieldId?  I'm currently inspecting the element for the ID but there must be a better way?

**Comment by brandonkelly** [comment]
@ohbiko pretty close, do `->fieldId(33)` instead.

You can get the field ID from the URL when editing your Matrix field.

**Comment by ohbiko** [comment]
Thank you! Yes I thought that I needed to pass the field ids of the matrix block items.

**Comment by brandonkelly** [comment]
If you’d like to filter by Matrix block ID you can do that – in addition to specifying the `fieldId` – using the `id` param (just like entry queries, etc.).
