### ISSUE TITLE
Craft 3: Cache "Data too long for column 'query'"

### ISSUE THREAD

**Issue by jasondonnette** [craftcms/cms#1792]
### Description

I had a page that was getting this MySQL error, I fixed it by setting the `craft_templatecachequeries`-> `query` field to type `LONGTEXT` instead of `TEXT` and the error went away.

I was only getting this error in production, not in development - not sure why. 

This is on a project that was upgraded from Craft 2 to Craft 3.

### Steps to reproduce

1. I imagine you can reproduce it but putting over 65,535 characters inside a cache block.

### Additional info

- Craft version:  3.x
- PHP version: 7.1
- Database driver & version:
- Plugins & versions:

**Comment by takobell** [comment]
Any chance you could send a Craft 2 database dump over to support@craftcms.com so we can dig into this a bit?

**Comment by mildlygeeky** [comment]
@takobell  - I am currently seeing the same issue in Craft 3 RC1 — for some reason Craft is trying to set the query field to a 3,160 character field in my case. Removing my `cache globally using key` code in my template makes it stop.

**Comment by mildlygeeky** [comment]
![pasted image at 2017_12_07 01_44 pm](https://user-images.githubusercontent.com/273266/33732933-160eb088-db56-11e7-85ef-73666ca18dbe.png)

**Comment by mildlygeeky** [comment]
Also, I don't believe this project was ever a Craft 2 project.

**Comment by mildlygeeky** [comment]
Interestingly, the only element query calls inside of that cache tag are being created by this plugin: https://packagist.org/packages/pdaleramirez/category-tree — still, wondering how the cache tag could end up with such a bizarre (almost looks like a base64-encoded string), long query string.

**Comment by mildlygeeky** [comment]
@takobell feels like this should be re-opened

**Comment by brandonkelly** [comment]
@mildlygeeky Can you try changing the `templatecachequeries.query` column type to `longtext` ?

**Comment by mildlygeeky** [comment]
@brandonkelly that worked like a charm.

**Comment by shaneturner** [comment]
We were also having this problem on dev and production. Query was simple category relation and only contained one for loop, returning only an image url reference with transform and title, with no more than 30 records. 

I can confirm that changing the column type manually to LONGTEXT resolved the issue.

```ALTER TABLE `templatecachequeries` MODIFY `query` LONGTEXT;```

**Comment by brandonkelly** [comment]
Thanks @mildlygeeky & @shaneturner! Just fixed for RC3.
