### ISSUE TITLE
CRAFT_BASE_PATH on Windows

### ISSUE THREAD

**Issue by davidteal** [craftcms/cms#1793]
### Description
This is more of a suggestion than a bug. I think it would be better to use `dirname(CRAFT_APP_PATH)` instead of `realpath(CRAFT_APP_PATH.'..')` when defining CRAFT_BASE_PATH. The use of realpath on Windows platforms adds back in backslashes which `$appPath = str_replace('\\', '/', $appPath);` tries to remove.

### Steps to reproduce
1. Open bootstrap.php
2. CRAFT_APP_PATH = E:/web/sites/craft-welford/craft/app/
3. CRAFT_BASE_PATH is defined using realpath
4. CRAFT_BASE_PATH = E:\web\sites\craft-welford\craft/

### Additional info
- Craft version: 2.6.2982
- Platform: Windows 10

**Comment by takobell** [comment]
`dirname` has issues with symlinks/windows junctions, if I recall from our testing. `realpath` worked cross-platform.  Plus Windows deals with both `/` and `\` in paths fine.

**Comment by davidteal** [comment]
Fair enough, I just thought it was strange that CRAFT_APP_PATH will always use forward slashes due to `$appPath = str_replace('\\', '/', $appPath);` but the rest of the paths could use a mix. The reason this came about was because `craft()->templates->getRenderingTemplate()` and `craft()->templates->getTemplatesPath()` return inconsistent paths e.g. `E:/web/sites/craft-welford/craft/templates/index.twig` vs `E:\web\sites\craft-welford\craft/templates/`

**Comment by khalwat** [comment]
Alright, I have no way to test this but... I added this code to the build in the `develop` branch:

        // Try to normalize things for Windows
        $currentTemplate = str_replace('\\', '/', $currentTemplate);
        $templatesPath = str_replace('\\', '/', $templatesPath);

Let me know if this works for you?
