### ISSUE TITLE
Template not found when site's base url contains path

### ISSUE THREAD

**Issue by acehead** [craftcms/cms#1794]
### Description
When Site's Base URL contains path, template resolution does not work as expected

### Steps to reproduce

1. Create a site with Base URL http://site.local/en (and ensure that this host is defined in your hosts file)
2. Create a structure section with {slug} s URI format and _entry as template for the site defined in step 1
3. Put _entry.html into templates directory
4. Create an entry into the section, with a slug "somepage"
5. Open http://site.local/en/somepage, Template Not Found exception occurs

### Additional info

- Craft version: Craft Personal 3.0.0-beta.19
- PHP version: PHP/7.1.1 
- Database driver & version: MySQL 5.6.35
- Plugins & versions: None

**Comment by brandonkelly** [comment]
I’m not able to reproduce this, so probably something environmental rather than a Craft bug. If you need help looking into it, please email support@craftcms.com, thanks!

**Comment by clsse** [comment]
@acehead Were you able to resolve this issue?
