### ISSUE TITLE
Fix Redactor CSS overrides for Live Preview

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#1795]
### Description

Redactor CSS overrides in craft.scss `#main .redactor`… don’t affect Live Preview fields. Probably just a merge problem as this is not an issue in Craft 3 branch.

(and while you’re at it, can you please make the field look a little bit less out of place in the Craft CP?)

### Additional info

- Craft version: 2.6

**Comment by brandonkelly** [comment]
@carlcs Are you using the version of Redactor included in Craft 2.6, or the old Redactor I plugin?

**Comment by carlcs** [comment]
Redactor II, no plugin.

**Comment by carlcs** [comment]
It looks like #1467 is where is got fixed for Craft 3
