### ISSUE TITLE
Image transform error

### ISSUE THREAD

**Issue by unasoft** [craftcms/cms#1796]
### Description
When setting the transformation parameters, and trying to call `image.getWidth(thumb)`, I get an error

`Argument 1 passed to craft\elements\Asset::getWidth() must be of the type string or null, array given`

This is because strict typing "string" is set
```
craft\elements\Asset::getWidth(string $transform = null)
```
### Steps to reproduce
```
{% set image = block.image.one() %}
{% set thumb = {"width": 600} %}
{% set width = image.getWidth(thumb) %}
```

### Additional info

- Craft version: 3.0.0-beta.19
- PHP version: 7.1.6
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks!
