### ISSUE TITLE
Saving new entries programmatically

### ISSUE THREAD

**Issue by SteveEdson** [craftcms/cms#1797]
### Description
I've been trying for ages to figure out how to create and save a new Entry, via PHP with Craft 3.

I got as far as the following code:

```php
$entry = new Entry();
$entry->sectionId = 4;
$entry->typeId = 4;
$entry->authorId = 1;
$id = uniqid('product_');
$entry->title = $id;
$entry->slug = $id;
$entry->setFieldValue('excerpt', 'Lorem...');
if(Craft::$app->elements->saveElement($entry)) {
    return $entry;
} else {
    throw new \Exception("Couldn't save new bespoke product: " . print_r($entry->getErrors(), true));
}
```

which saved without any errors, however my custom field values weren't being saved into the entry. 

**After lots of digging, I realised that it was because I was missing: `$entry->fieldLayoutId = 10;`.**

I think that this can be improved in either of 2 ways:

- A warning is thrown when saving entries with custom fields, that are missing a fieldLayoutId (or entries that are missing a layout id in general)
- A helper method to save these entries, using the entry type handle, something like:

```php
$newEntry = Craft::$app->entries->createNewEntry('product', [
    'title' => 'My Title',
    'slug' => 'my-title',
    'excerpt' => 'Lorem...',
    'images' => $imageIds,
]);
```

etc. The `sectionId`, `typeId` and `fieldLayoutId` could be found automatically based on the handle of the entry type.

### Additional info

- Craft version: **3.0.0-beta.19**
- PHP version: 7.1.6
- Database driver & version: MySQL
- Plugins & versions: N/A

**Comment by narration-sd** [comment]
Yes, I've run into this. 

Just fixed and blew through it as I was converting a big plugin, but truly matters would be much improved with a measage, something like 'one or more fields not saved, due to missing fieldLayoutId for them'

- This should go in the log, naturally, but should also appear as a flash message.
- in fact, shouldn't the save be denied if occuring  on the front end, as really you did not get a save
- in which case, really this should be an error message, more important than a warning?

**Comment by SteveEdson** [comment]
Now that I've figured out what I'm doing, I created this:

```php
    public static function saveNewEntry(string $handle, array $fields) {
        $entryType = EntryType::find()->where(['handle' => $handle])->one();

        $entry = new Entry();
        $entry->sectionId = $entryType->getAttribute('sectionId');
        $entry->typeId = $entryType->getAttribute('id');
        $entry->fieldLayoutId = $entryType->getAttribute('fieldLayoutId');
        $entry->authorId = 1;

        if(isset($fields['title'])) {
            $entry->title = $fields['title'];
            unset($fields['title']);
        }

        if(isset($fields['slug'])) {
            $entry->title = $fields['slug'];
            unset($fields['slug']);
        }

        $entry->setFieldValues($fields);

        if(Craft::$app->elements->saveElement($entry)) {
            return $entry;
        } else {
            throw new \Exception("Couldn't save new bespoke product: " . print_r($entry->getErrors(), true));
        }
    }
```

This lets me save anything with:

```php
return self::saveNewEntry('article', [
    'title' => $id,
    'slug' => $id,
    'excerpt' => $excerpt,
    'body' => $body
]);
```

**Comment by narration-sd** [comment]
I think  you're right. This case already shows up as a save error.

**Comment by SteveEdson** [comment]
Which is showing as a save error? My latest code for `saveNewEntry`?

**Comment by narration-sd** [comment]
no, the fault with lacking fieldLayoutId that you were concerned with.

**Comment by SteveEdson** [comment]
Ah ok. When I saved it without a fieldLayoutId, it didn't throw any errors but just silently continued.

**Comment by narration-sd** [comment]
Ok, then my original comment's suggestion stands....

**Comment by SteveEdson** [comment]
Yeah sorry, just clearing things up. I read "This case already shows up as a save error." as it meaning it causes errors when saving.

**Comment by brandonkelly** [comment]
Starting in Beta 20, it will not be necessary to set `$fieldLayoutId` anymore. Thanks for the feedback!

**Comment by brandonkelly** [comment]
(Oh and a quick note - you don't need to set the `$id` property when creating a new entry. That will be assigned automatically on save.)

**Comment by max8hine** [comment]
@SteveEdson 


I got `Call to undefined method craft\models\EntryType::find()` error

Is the EntryType class still work in the below way?
``` php
use craft\models\EntryType;
EntryType::find()->where(['handle' => $handle])->one()
```

**Comment by lemiwinkz** [comment]
@SteveEdson You need to use the [ActiveRecord](https://docs.craftcms.com/api/v3/craft-records-entrytype.html) class. The example like below should work. 
```
use craft\records\EntryType;
EntryType::find()->where(['handle' => $handle])->one()
```
