### ISSUE TITLE
Cannot redeclare getTranslations when using a non-existing translation

### ISSUE THREAD

**Issue by jordikroon** [craftcms/cms#1799]
### Description

I'm getting the following error when using a non-existing translation:

```
Fatal error: Cannot redeclare getTranslations() (previously declared in
/vagrant/racingnews/craft/translations/includes/functions.php:8) in 
/vagrant/racingnews/craft/translations/includes/functions.php on line 23
```

The error doesn't explain much and should be catched by a more friendly message. e.g: Translation not found.

### Steps to reproduce

1. Print a translation using a non-existing translation `Craft::t('route.news', [], null, 'nonexistent')`
2. Error gets printed `Cannot redeclare getTranslations()`, see description for the full error.

### Additional info

- Craft version: 2.6.2985
- PHP version: PHP 5.6
- Database driver & version: 5.5.52-MariaDB
- Plugins & versions: N/A

**Comment by takobell** [comment]
`craft/translations/includes/functions.php` isn't a core Craft file, so this looks like an error in whatever custom logic is being loaded from that file.
