### ISSUE TITLE
Table fieldtypes default to 1 existing row when created leading to blank output

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#18]
#### Environment:

- Craft version: 3.x
- PHP version: 7.x
- Database driver & version: 
- Plugins & versions:

#### Description:

When creating a new table field it defaults to already having one empty row unfilled. If left in the default state and the user leaves this field blank while creating an entry then the template may output blank content without extra logical checks to empty cell-values within the template.

It is possible to delete the default blank row 'placeholder' when creating the field, however this behavior seems different from the default of other fields which fallback to a 'null' state when left blank.

I see the argument here that adding the first row to a table may be non-obvious to the user, but the default state seems just as confusing.

**Comment by tjdraper** [comment]
Adding here that it's not just happening when creating a new table field. At least on Matrix, a single empty row of default values is created anytime the Matrix field is revisited and re-saved, which is extremely frustrating when you have to remember to delete that empty default values row for every table in the Matrix field that isn't supposed to have default values.

**Comment by brandonkelly** [comment]
Table fields will only create a default row if their Default Value field setting has a row. If you don’t like that behavior, you can delete the default row in the setting.

@tjdraper The only time a Matrix field should be creating any blocks automatically is if the Min Blocks setting is set (new in Craft 3), and there’s only one available block type. If it’s happening in other situations for you, please post as a new issue with specific steps to reproduce - including your Craft version number. Thanks!
