### ISSUE TITLE
Problem with thumbnail elements

### ISSUE THREAD

**Issue by AgnieszkaCE** [craftcms/cms#1802]
### Description

As shown on the screenshot, I have a problem with thumbnail elements in models forms. The label overlaps the element below. I have found that the problem is caused by fixed height of .element class.

![craft-bug](https://user-images.githubusercontent.com/6688682/27691300-e4e1cc0c-5ce3-11e7-8748-7d9d588c92e1.png)

- Craft version: 2.6.2960

**Comment by AgnieszkaCE** [comment]
Some solution?

**Comment by AgnieszkaCE** [comment]
any progress?

**Comment by brandonkelly** [comment]
Sorry for the delay, @AgnieszkaCE. Just fixed for the next release.
