### ISSUE TITLE
Improve helvetica font stack in admin panel

### ISSUE THREAD

**Issue by sam327** [craftcms/cms#1805]
I'd like the Helvetica font stack to degrade a little more gracefully.

So, in _/craft/app/resources/css/craft.css_

Mostly, fonts are set up to go like this: 
````font-family: HelveticaNeue, sans-serif;````

Can you make that a longer stack? Something more like this:
```` font-family: "Helvetica Neue", HelveticaNeue, Helvetica, Arial, "Lucida Grande", sans-serif; ````

My Mac doesn't like "HelveticaNeue" - it was showing things in sans-serif. Changed to "Helvetica Neue" and now it works fine.

And some of the office PCs here have helvetica, but not helvetica neue.

IMNSHO, I'd be perfectly happy if you ditched helvetica entirely and went with something like Open Sans or Google's Noto - any font that's free for desktop & web use and is consistent across macs/windows/linux.

**Comment by brandonkelly** [comment]
Added a check for `"Helvetica Neue"` for the next release. Not interested in adding Helvetica or Arial to the mix though, as Helvetica looks gross on Windows and Arial looks gross on macOS. Conveniently `sans-serif` will generally default to Helvetica on macOS and Arial on Windows, where they look their best, so I’m happy with that behavior. (No way do I want to add Lucida Grande though :)

**Comment by brandonkelly** [comment]
> IMNSHO, I'd be perfectly happy if you ditched helvetica entirely and went with something like Open Sans or Google's Noto - any font that's free for desktop & web use and is consistent across macs/windows/linux.

I’d rather just have the type look good for the platform it’s being rendered on, than have it be consistent across all platforms. Especially if consistency means forcing browsers to load a heavy web font.

**Comment by sam327** [comment]
Ah, on my PC, I think the default 'sans-serif' font is slightly different on each browser. I'll check it the next time I fire it up to be sure. On my Chromebook, sans-serif defaults to Noto Sans. (yes, I've got like 8 computers. I'm sorry.)

I mentioned open sans & noto - because they're free to download for desktop and free for use as webfonts. So if someone doesn't have it, they can just download it. And/or you could even distribute it in the craft package. Makes you independent of people's OS choices. "WindowsME? Who cares! Download this, and it'll look great!"  I don't want Craft to load a webfont either, but I also don't want people to have a 'not-optimal experience' because they don't have helvetica neue. 

Whereas Helvetica Neue is expensive to get for non-MacOS devices. It can quickly rack up a couple hundred bucks in licenses _per computer_ in a commercial environment.

**Comment by brandonkelly** [comment]
Helvetica Neue also generally doesn’t look great at small sizes on non-macOS devices, so I’m not worried about that.

If you’d prefer to use Open/Noto sans, you can do it with the [CP CSS](https://github.com/lindseydiloreto/craft-cpcss) plugin ;)

**Comment by PanMan** [comment]
@brandonkelly Does the CP CSS plugin work with Craft 3?

**Comment by takobell** [comment]
@PanMan It doesn't look like it's been ported, yet. https://github.com/craftcms/plugins

**Comment by brandonkelly** [comment]
Easy enough to write your own plugin that does the same thing, though. It’s a really simple plugin.
