### ISSUE TITLE
Install via composer, craft v2: guzzle no matching package found

### ISSUE THREAD

**Issue by masiorama** [craftcms/cms#1809]
As stated in the subject, I can't install craft via composer, due to:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for craftcms/cms 2.6.2986 -> satisfiable by craftcms/cms[2.6.2986].
    - craftcms/cms 2.6.2986 requires guzzle/guzzle v3.9.4 -> no matching package found.

https://packagist.org/packages/guzzle/guzzle

**Comment by carlcs** [comment]
Version `3.0.0-beta.1` is the first one that officially supported Composer installation.

**Comment by brandonkelly** [comment]
Craft 2 can't be installed with Composer, that's a new v3 feature.

**Comment by roelvanhintum** [comment]
I know this was closed a long time ago, but for documentation purposes:
We run a lot of Craft 2 projects and to keep the repository clean, we prefer installing using composer. It is possible, you just need to add some extra stuff to the composer.json. 

```json
{
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/pixelandtonic/Twig"
        },
        {
            "type": "git",
            "url": "https://github.com/pixelandtonic/guzzle3"
        },
        {
            "type": "git",
            "url": "https://github.com/pixelandtonic/simplepie"
        },
        {
            "type": "git",
            "url": "https://github.com/pixelandtonic/pel"
        },
        {
            "type": "git",
            "url": "https://github.com/pixelandtonic/yii"
        },
        {
            "type": "git",
            "url": "https://github.com/pixelandtonic/pclzip"
        }
    ],
    "require": {
        "craftcms/cms": "2.6.3012"
    },
    "autoload": {
        "classmap": [
            "vendor/craftcms/cms/src/"
        ]
    }
}
```

Point the index.php to the new folders:

```php
define('CRAFT_APP_PATH', realpath(dirname(__FILE__) . '/../vendor/craftcms/cms/src/') . '/');
define('CRAFT_VENDOR_PATH', realpath(dirname(__FILE__) . '/../vendor/') . '/');
define('CRAFT_FRAMEWORK_PATH', realpath(dirname(__FILE__) . '/../vendor/yiisoft/yii/framework/') . '/');
```
