### ISSUE TITLE
Renaming field causes saving failures on Postgres

### ISSUE THREAD

**Issue by acehead** [craftcms/cms#1810]
### Description

When field is renamed, saving an entry which used it fails (on Postgres at least)

### Steps to reproduce

1. Create matrix field with handle ogElements, save it
2. Add it to global set or some entry
3. Edit field, rename handle to ogElements2
4. Try to save entry or global set containing this field
5. Following error occurs while saving entry with new field included:
SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "public.matrixcontent_ogelements2_id_seq" does not exist

Dropping the field entirely and recreating it with a new name helps to work issue around.

### Additional info

- Craft version: Craft Personal 3.0.0-beta.19
- PHP version: PHP/7.1.1
- Database driver & version: PostgreSQL 9.6.2
- Plugins & versions: None

**Comment by brandonkelly** [comment]
Issue is that Postgres doesn’t rename a table’s corresponding Sequence when renaming a table (see https://www.postgresql.org/message-id/200308211224.06775.jgardner%40jonathangardner.net).

I've just fixed this for future Matrix field renames, but if you’re getting this error you’ll need to run this SQL query:

```sql
alter sequence "matrixcontent_oldhandle_id_seq" rename to "matrixcontent_newhandle_id_seq"
```

(Replace `oldhandle` and `newhandle` with the old and new Matrix field handles, all-lowercase.)
