### ISSUE TITLE
Craft3: Redactor html button is missing

### ISSUE THREAD

**Issue by nternetinspired** [craftcms/cms#1812]
### Description

A rich-text field using the ‘Standard’ Redactor config should display the html button `<>` in the Redactor toolbar; it doesn't.

### Steps to reproduce

1. Add a rich-text field.
2. Set it's Redactor config field to ‘Standard’.
3. Check out the field in an entry.

#### Expected result:
![screen shot 2017-07-05 at 10 36 53](https://user-images.githubusercontent.com/1090182/27858676-06a92518-616e-11e7-98a7-931a6fde9a08.png)

#### Actual result:
![screen shot 2017-07-05 at 10 38 55](https://user-images.githubusercontent.com/1090182/27858721-30718df4-616e-11e7-83a8-fdd11391a129.png)

### Quick fix…
I was able to get the expected behaviour by changing `config/redactor/Standard.json`, removing `html` from the buttons list and adding `source` to the plugin list, i.e:

```
{
"buttons"["html","formatting","bold","italic","unorderedlist","orderedlist","link","image","video"],"plugins":["fullscreen","video"],
"toolbarFixed": true
}
```
to: 

```
{
"buttons": ["formatting","bold","italic","unorderedlist","orderedlist","link","image","video"],"plugins":["fullscreen","source","video"],
"toolbarFixed": true
}

```

### Additional info

- Craft version: 3.0.0-beta.19
- PHP version: 7.0.19-1+deb.sury.org~trusty+2
- Database driver & version: MySQL 5.5.55-0ubuntu0.14.04.1
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Thanks! FFR please post issues with the base project files in the [craftcms/craft](https://github.com/craftcms/craft) repo.

**Comment by nternetinspired** [comment]
Sorry @brandonkelly, my bad. Totally missed that this was the wrong repo, but that does explain why I couldn't find the correct file to do a PR on!
