### ISSUE TITLE
"Couldn’t save route" when using the same pattern for different sites

### ISSUE THREAD

**Issue by acehead** [craftcms/cms#1813]
### Description
I want to define different routing rules on per site basis. Rules have the same URL pattern but different templates. Craft is not allowing to save different rules having the same pattern. I see no reason why this should be restricted.

### Steps to reproduce

1. Create two sites: site1 and site2
2. Define route with pattern "test/(year)" and template "test1" for site1
3. Define route with pattern "test/(year)" and template "test2" for site2
4. Couldn’t save route error shown and second route was not saved

### Additional info

- Craft version: Craft Personal 3.0.0-beta.19
- PHP version: PHP/7.1.1
- Database driver & version: PostgreSQL 9.6.2
- Plugins & versions: None

**Comment by takobell** [comment]
Fixed in https://github.com/craftcms/cms/commit/71499e927b44ec5c5f03293dd5e7a4ffc046c692 and will be in the next release.
