### ISSUE TITLE
Unable to save reordered entries headings on Postgres

### ISSUE THREAD

**Issue by acehead** [craftcms/cms#1814]
### Description
Reordering entries headings works for the first time, when saving second time "An unknown error occured" message shown (2 times) and order of elements is not saved

### Steps to reproduce

1. Open reordering dialog, change the order of elements in the left panel, Save it
2. It worked. Repeat step 1.
3. "An unknown error occured" message shown (2 times) and order of elements is not saved

Log contents:
PDOException: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "elementindexsettings_type_unq_idx"
DETAIL:  Key (type)=(craft\elements\Entry) already exists.

### Additional info

- Craft version: Craft Personal 3.0.0-beta.19
- PHP version: PHP/7.1.1
- Database driver & version: PostgreSQL 9.6.2
- Plugins & versions: None

**Comment by brandonkelly** [comment]
Looks like we already fixed this for the next release!
