### ISSUE TITLE
Missing Update button

### ISSUE THREAD

**Issue by mccombs** [craftcms/cms#1822]
### Description
<img width="1280" alt="screen shot 2017-07-07 at 4 43 50 pm" src="https://user-images.githubusercontent.com/454117/27978136-84e80964-6333-11e7-8fd7-df1bd10999ea.png">

Perhaps I'm overlooking something but there's no update button.

Is it now a CLI update only? If so, what's the command to update? I didn't see anything in the docs: https://github.com/craftcms/docs

### Steps to reproduce

1. Chrome: Version 59.0.3071.115 (Official Build) (64-bit)
2. Visit /admin/utilities/updates

### Additional info

- Craft version: Craft CMS 3.0.0-beta.19
- PHP version: 7.0.15
- Database driver & version: mysql 5.6.35
- Plugins & versions: NA

**Comment by brandonkelly** [comment]
Updates have been CLI-only up until Beta 20. Once you've run `composer update` this one last time, you should start seeing Update buttons in there.
