### ISSUE TITLE
Cannot use object of type Closure as array - After beta 20 update

### ISSUE THREAD

**Issue by andrelopez** [craftcms/cms#1823]
### Description
I just updated from beta19 (I also installed a fresh version) and I got this error: "Cannot use object of type Closure as array"

The log file is bellow:
[web.txt](https://github.com/craftcms/cms/files/1132518/web.txt)

![beta 20 error](https://user-images.githubusercontent.com/875476/27979277-aca47f1e-6342-11e7-8fca-bfbf02da8422.png)

### Steps to reproduce

1. Install or update beta20

### Additional info

- Craft version: beta20
- PHP version: 7.0.0 (windows using MAMP)
- Database driver & version: 5.6.34-log - MySQL
- Plugins & versions: None

**Comment by brandonkelly** [comment]
Shoot, looks like we accidentally relaxed our Yii Debug extension version requirement in 429ef84d63274e43ed99f22c3ecab6fa9829848b. That was supposed to be hard-set at 2.0.8 until yiisoft/yii2-debug#234 is fixed. Just fixed this w/ Beta 21. Run `composer update` and you should be good to go.
