### ISSUE TITLE
Mac Preview App > Scale Image >Upload doesn't work

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#1824]
### Description
When I resize an Image with the Mac Preview App the Craft Upload failed. 
No error Message but the upload bar is all the time visible and full filled.

here is the Image.
![winnetous-sohn-cover 15 32 36](https://user-images.githubusercontent.com/764292/28020824-ef0d89c8-6585-11e7-976e-737af24eacc0.jpg)

### Steps to reproduce

1. go to files
2. upload the file

### Additional info

- Craft version: 3.0.0-beta.19
- PHP version: 7.1

**Comment by brandonkelly** [comment]
I just tried uploading your image to my own Craft 3 install and it worked fine. But GitHub is likely running it through a cleansing process, so it’s probably not the exact same image you’re using locally.

Can you send it to us through the Craft Support widget on your Dashboard, and include your logs? Thanks!

**Comment by davidhellmann** [comment]
Is a Staging Server with no mailserver :)

here the image as Zip File. Maybe you can try this one :)
[Uploading image.zip…]()
