### ISSUE TITLE
Database error when opening entry edit view (Postgres)

### ISSUE THREAD

**Issue by acehead** [craftcms/cms#1827]
### Description
When opening entry edit view database-related error appears in the logs (see attached file). At first it seems that it does not influence editing or saving anyhow, however I think it's better to fix it.

### Steps to reproduce

1. Open entry edit form
2. Check logs or debug toolbar, attached error occurs.
[craft-db-error.txt](https://github.com/craftcms/cms/files/1138801/craft-db-error.txt)

### Additional info
Initially installed Craft 3 beta 19, upgraded to beta 21. Error happened on beta 19 as well.

### Additional info

- Craft version: Craft Pro 3.0.0-beta.21
- PHP version: PHP/7.1.1
- Database driver & version: PostgreSQL 9.6.2
- Plugins & versions: None

**Comment by brandonkelly** [comment]
The only awkward thing here is that these exceptions are getting logged. That they occur is not a problem (they are used as an internal way to abort a query if we know ahead of time that it won't return any results). Removing the log calls now…
