### ISSUE TITLE
Non Admins Can't download Assets

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#1829]
### Description
I've a User Group "Redakteur" with all rights set except "Tools" and "Users".
Now (with a Redakteur Account) within the Assets I checkmark an Image and go to "Download Asset" it comes this Message in a new Tab

```
Unauthorized
User is not permitted to perform this action
```

![image](https://user-images.githubusercontent.com/764292/28107221-1a425dfa-66e7-11e7-8dfd-69928fc5c04f.png)

### Additional info

- Craft version: Beta 19

**Comment by andris-sevcenko** [comment]
Fixed in the coming release.

**Comment by brandonkelly** [comment]
This was already fixed in Beta 20.
