### ISSUE TITLE
Link from section details to its entry types

### ISSUE THREAD

**Issue by hiasl** [craftcms/cms#1830]
### Description
Suggestion for improvement: Can you create a link in the admin background from the details page of a section to its corresponding entry type(s). Maybe I'm just a dumb user, but too often i open the wrong admin screen (I want to modify entry types but go into the details page of a section)

### Steps to reproduce

1. In the Admin GUI, go to Settings > Sections
2. Select any section 
3. Here a link to its entry types would be great

### Additional info

PHP version	7.1.6-1~ubuntu16.04.1+deb.sury.org+1
Database driver & version	MySQL 5.6.13
Image driver & version	GD 7.1.6-1~ubuntu16.04.1+deb.sury.org+1
Craft edition & version	Craft Pro 3.0.0-beta.21
Yii version	2.0.12
Twig version	2.3.2
Guzzle version	6.2.1
Imagine version	0.7-dev

**Comment by hiasl** [comment]
Solved with https://github.com/craftcms/cms/issues/6826

**Comment by brandonkelly** [comment]
Ah sorry, forgot this had already been requested. Thanks for closing!
