### ISSUE TITLE
Category Field: If limited is reached, "Add a category" button is still shown

### ISSUE THREAD

**Issue by hiasl** [craftcms/cms#1831]
### Description
If an entry type contains a category field and the limit of selectable category branches is reached (e.g. 1), then the "Add a category" buttons stays visible, though nothing can be selected anymore unless the previously selected one is removed first. This is different with assets, where the buttons disappears (which I believe is better from a usability pov).

I think it would be better, if the button was hidden, once the limit is reached.

### Steps to reproduce

1. Edit a an entry which contains a category field, that is limited to e.g. 1 branch.
2. Select a category branch
3. The button "Add a category" does not disappear, though nothing can be selected anymore.

### Additional info

PHP version	7.1.6-1 ubuntu16.04.1+deb.sury.org+1
Database driver & version	MySQL 5.6.13
Image driver & version	GD 7.1.6-1 ubuntu16.04.1+deb.sury.org+1
Craft edition & version	Craft Pro 3.0.0-beta.21
Yii version	2.0.12
Twig version	2.3.2
Guzzle version	6.2.1
Imagine version	0.7-dev

**Comment by brandonkelly** [comment]
This is a known issue, but not something we can easily solve, because the field doesn’t know whether the selected branch(es) have additional leaves that could be selected.
