### ISSUE TITLE
After adding an SVG file as login page logo user is unable to log in

### ISSUE THREAD

**Issue by acehead** [craftcms/cms#1832]
### Description
Craft fails getting sized of an SVG logo uploaded as login page logo, which means that unless file is removed from filesystem login page is broken and users are not able to log in.

### Steps to reproduce

1. Upload SVG file as login page logo
2. After saving error occurs

`Return value of craft\web\twig\variables\Image::getHeight() must be of the type integer, null returned`

- Craft version: Craft Pro 3.0.0-beta.21
- PHP version: PHP/7.1.1
- Database driver & version: PostgreSQL 9.6.2
- Plugins & versions: None

**Comment by brandonkelly** [comment]
Login page logos work in general. Can you either upload your SVG to this thread, or email it to support@craftcms.com and reference this issue?
