### ISSUE TITLE
craft\db\elements\ElementQuery::one() and nth() now consistently return false rather than null when no matching element is found.

### ISSUE THREAD

**Issue by michaelrog** [craftcms/cms#1836]
From 3.0.0-beta.22:

 > craft\db\elements\ElementQuery::one() and nth() now consistently return false rather than null when no matching element is found.

Why? `null` seems like a more correct value to represent something that _doesn't exist_. (Especially since `one()` and `nth()` will get used a lot in templates... because `??`ing fallback values is wonderful, and the magic would be spoiled by a boolean return value in that case.)

...but before I go complaining, I'm curious what yall's reasoning is for that change.

**Comment by brandonkelly** [comment]
Consistency with [yii\db\Query::one()](http://www.yiiframework.com/doc-2.0/yii-db-query.html#one()-detail), which ElementQuery::one() overrides.
