### ISSUE TITLE
Delete user dialog fails when reassigning data to another user

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#1837]
### Description

There's an error in `DeleteUserModal.js:68` where the elementType property for the `BaseElementSelectInput` is set to `User`. This value needs to be `craft\elements\User` (or rather, `craft\\elements\\User` to be exact.)

I was able to verify this fix by changing the value in the minified JS and successfully reassigning content to a different user and deleting the original.

### Steps to reproduce

1. Create user A and user B
2. Create content as user A
3. Go to delete user A from control panel, click on user select button, modal fails to load

### Additional info

- Craft version: v3 Beta 22
- PHP version: 7.x
- Database driver & version: MySQL
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks!
