### ISSUE TITLE
Bugs when using category field

### ISSUE THREAD

**Issue by Luuc15** [craftcms/cms#1839]
### Description
When you have a category field and a limit to select only one category for an entry, then it is still possible to select multiple categories, although only one will actually be used.
Also when you have already selected a category and want to select another, double clicking on the category does not work (it closes the popup but does not replace the selected category), also when selecting an other category in the popup, clicking the button to choose the category, the category gets replaced, but when trying to select another category before saving, the old selected category still stays disabled for selection. (So instead of one category that is not selectable you now have two, the old and the new one)

### Steps to reproduce

Problem one, double click to replace an already choosen category
1. Add a category field to an entry that is limited for 1 category selection
2. Choose one category at your entry, double click it and the popup will close and you will see the category you chose.
3. Now save the entry
4. Open the entry again, now try to choose another category, and to double click it to use it. It won't work. The popup will close, but the category will not be used.
It will only work if you click on the button at the bottom right in the popup

Problem two, greyed out previous category
1. Add a category field to an entry that is limited for 1 category selection
2. Choose one category at your entry and save
3. Now try to choose another category, but do not yet save
4. existing category will be replaced
5. If you try to choose the previous category again it will still be grayed out.
6. Even when you remove all categories the ones selected will still be greyed out and can not be selected again, untill you reload the page or save the entry.

You can also see that it is possible to select multiple categories, (still only one will be used).

### Additional info

- Craft version: Newest
- PHP version: 7
- Database driver & version: mysql
- Plugins & versions: No additional plugins

![schermafbeelding 2017-07-13 om 13 57 32](https://user-images.githubusercontent.com/661751/28268215-adf65a78-6afd-11e7-87ac-6294d86ec8f7.png)
![schermafbeelding 2017-07-13 om 13 57 41](https://user-images.githubusercontent.com/661751/28268216-adf775e8-6afd-11e7-8f58-631cc8c0eb98.png)
![schermafbeelding 2017-07-13 om 13 58 03](https://user-images.githubusercontent.com/661751/28268217-adf854ea-6afd-11e7-9ffe-beeefd3cda65.png)
![schermafbeelding 2017-07-13 om 13 58 20](https://user-images.githubusercontent.com/661751/28268219-adfa676c-6afd-11e7-8ee0-4abf1e5463dc.png)
![schermafbeelding 2017-07-13 om 13 58 34](https://user-images.githubusercontent.com/661751/28268218-adf94b7a-6afd-11e7-9948-745a8b434d30.png)
![schermafbeelding 2017-07-13 om 13 58 41](https://user-images.githubusercontent.com/661751/28268220-adfb7e40-6afd-11e7-8f6b-dfc317b48fc1.png)
![schermafbeelding 2017-07-13 om 13 59 19](https://user-images.githubusercontent.com/661751/28268221-ae0e7b3a-6afd-11e7-8bb7-543dc05b2c5e.png)

**Comment by brandonkelly** [comment]
Please post only one bug per issue. Also please specify the actual, full version of Craft you are using.
