### ISSUE TITLE
Feature: Static translation based on multisite level

### ISSUE THREAD

**Issue by Luuc15** [craftcms/cms#1840]
### Description
Static translations now reside in the /translations folder with the same structure used in the translations folder of the craft app.

Translations are now based on locale, so you will get /translations/en/site.php
However if you would like to manage static translations on a site level, lets say site-one and site-two then you have to use the locale of the defined site and then seperate the site in the php file if even possible.

A much better way would be if the folder would be named like the handle.
So you would get /translations/site-one/site.php and /translations/site-two/site.php
This way you can have different translations per site.

Just an idea ;)

**Comment by brandonkelly** [comment]
Unfortunately this isn’t technically possible, since static translations are a core Yii concept that doesn’t know anything about Craft’s concept of “sites”.
