### ISSUE TITLE
Multiple URIs to one template

### ISSUE THREAD

**Issue by dorothyDorothy** [craftcms/cms#1841]
### Description
I have the following sections in my blog
##### A section called blog_item with the following entry format: `blog/{postDate|date("Y")}/{postDate|date("m")}/{slug}`
which maps to a template 
`blog/_entry`

This works very well.

#### A blog listing page with this template
`blog/index`
which works without any need for a section or dynamic route.

#### Blog listings which are filtered by month
I would like these to be served by the same template as the blog listing page
`blog/index`

This results in a 404.

### Attempts to resolve this

1. I have added a new route `blog/*/*` to point to blog/index
2. I have changed the route to be `blog/*`
3. I have changed the route to be `blog/<year>/<month>/` where the year and months are tokens that you can add from the form.

None of the above configurations works and neither does removing the route altogether.

N.B. `/blog` does not feature in any of my redirects created in Redirect Manager.
This must be a pretty basic set up. What am I doing wrong?

### Additional info

- Craft version: 2.6.2986
- PHP version: 7.0.21-1~ubuntu16.04.1+deb.sury.org+1
- Database driver & version: mysql v 5.0
- Plugins & versions: 
-- Contact Form 1.9.0
-- reCAPTCHA for Craft 1.0
-- Redirect Manager 1.9.1
-- Sitemap 1.2.3

**Comment by brandonkelly** [comment]
Hey @dorothyDorothy, guessing you got this sorted?
