### ISSUE TITLE
Auto expand asset subfolders

### ISSUE THREAD

**Issue by jordikroon** [craftcms/cms#1842]
### Description

My clients would like to see an option to have subfolders expanded by default, or have it opened to the latest state. It is frustrating to, if you have lots of assets and folders, click on the folder every time. 

For flexibility, we have 1 folder names "Uploads", where he can create folders in.

### Steps to reproduce

1. Go to assets
2. Folder is collapsed

### Additional info

- Craft version: 2.6.2987 
- PHP version: 7.0

### Temporary solution
We solved it for now by creating a js file and injecting it through a plugin, but that feels rather hacky and is not sustainable.

`$('.sidebar li:not(.expanded) > .toggle').trigger('click');`

**Comment by brandonkelly** [comment]
Craft 3 will remember which folders were expanded previously.
