### ISSUE TITLE
c3 button updating fails on converted c2 sites

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1843]
### Description
Ok, I emailed to give you an early heads up, but here's a very quick issue

- on a conversion site from Craft 2, updater fails because it can't find the composer.json file. 

It's there -- just not where updater expects, because of the old folder structure.. 

One up from the craft folder, in that case, would be a good guess...

### Steps to reproduce

1. Have a button-updateable, but legacy-converted Craft site
2. Push the button when prompted by blue ball
3. Fail

### Additional info

- Craft version: beta 20 or so; dev-develop
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Were you following the [recommended update procedure](https://github.com/craftcms/docs/blob/master/en/upgrade.md#updating-craft-cms)?

**Comment by narration-sd** [comment]
I kind of think so -- the site itself, and Composer update have been
working fine for many months.

I'll check, and contents of index.php especially, when I get home.

**Comment by narration-sd** [comment]
Ok, I looked into this, and what I found doesn't appear what I would write for style. Checking around, it looks like I ported the standard install index.php for Craft 3 at the time.

Just by inspection, this importantly results in CRAFT_BASE_PATH  being impossible, and am sure matters deteriorate from there.

I'll match what you have in the doc existing now, and try again on next release point -- imagine things will be fine.

Thanks, Brandon.  Will close

**Comment by narration-sd** [comment]
A p.s. though -- I also had in there a try/use for .env file, which was also wrong being borrowed from someplace, and anyway needs a check on existence of vendor/vlucas/phpdotenv -- might be nice if the boilerplate in the doc shows how to do that properly also.

**Comment by narration-sd** [comment]
Ok, and if useful, here's the resultant working index.php file. I had to split the composer operations and  .json between the project root, where Vagrant uses it, and /craft, where you now want /vendor to appear.

I don't remember anything about that at original time of C2->C3 conversion, but that was early days, or possibly I missed it.

Anyway, I expect button-update to work next time it's offered.

`<?php
// Path to your craft/ folder
$craftPath = '../craft';

// Do not edit below this line
// except to convert C2 to C3, we rather did

defined('CRAFT_BASE_PATH') || define('CRAFT_BASE_PATH', realpath($craftPath));

if (!is_dir(CRAFT_BASE_PATH.'/vendor')) {
    exit('Could not find your vendor/ folder. Please ensure that <strong><code>$craftPath</code></strong> is set correctly in '.__FILE__);
}

require_once CRAFT_BASE_PATH.'/vendor/autoload.php';

// dotenv? must check here, after autoload
$dotenvpath = CRAFT_BASE_PATH . '/..';
if (file_exists($dotenvpath . '/.env')
    && file_exists(CRAFT_BASE_PATH . '/vendor/vlucas/phpdotenv')) {
    $dotenv = new Dotenv\Dotenv($dotenvpath);
    $dotenv->load();
}

$app = require CRAFT_BASE_PATH.'/vendor/craftcms/cms/bootstrap/web.php';
$app->run();
`

**Comment by brandonkelly** [comment]
We changed the conversion guide at some point, just to make it a little simpler. But the old way would be fine too. Craft just needs to be able to find your `composer.json` file. By default, it will look inside your `CRAFT_BASE_PATH` directory (either as defined within `index.php`, or assumed to be the parent directory of your `vendor/` directory). If that’s not where your `composer.json` lives, you can tell Craft where it lives by defining a `CRAFT_COMPOSER_PATH` constant in index.php, set to its location.

```php
define('CRAFT_COMPOSER_PATH', 'path/to/composer.json');
```

**Comment by narration-sd** [comment]
Ah, nice to know about that constant. I already refactored this site, but could have saved the work; and if I have to fix one for someone else...
