### ISSUE TITLE
Category field: double click to replace an already chosen category

### ISSUE THREAD

**Issue by Luuc15** [craftcms/cms#1845]
### Description
When you have a category field that is limited to only one selection and you already selected a category and want to select another, double clicking on the category does not work (it closes the popup but does not replace the selected category)

### Steps to reproduce

1. Add a category field to an entry that is limited for 1 category selection
2. Choose one category at your entry, double click it and the popup will close and you will see the category you chose.
3. Now save the entry
4. Open the entry again, now try to choose another category, and to double click it to use it. It won't work. The popup will close, but the category will not be used.
5. It will only work if you click on the button at the bottom right in the popup

### Additional info

- Craft version: 3.0.0-beta.21 - 2017-07-07
- PHP version: 7.0.15
- Database driver & version: Mysql version 5.6.35
- Plugins & versions: No plugins

**Comment by brandonkelly** [comment]
This is actually the same issue as #1847 - comes down to the fact that the modal window is not aware of the field’s limits. If it was, you wouldn’t be able to select another category in the first place.
