### ISSUE TITLE
Category field: Previous category not selectable before saving entry

### ISSUE THREAD

**Issue by Luuc15** [craftcms/cms#1846]
### Description
When you have an entry with a category field that is limited to only one selection, and you have already a selected category, this category will be greyed out in the selection.
This is correct behavior. 

If we would now choose another category, the previously selected category gets replaces (because the fields is set to only one selection). Still everything works good. 

Do not save the entry yet!

When we want to select the previous category again, because well we did not want to replace it in the first place or something, then the previous category is still greyed out and not selectable.
In fact you will see two greyed out selections, when only one is possible.

When you refresh the page or save the entry it will be selectable again in the category field

### Steps to reproduce

1. Add a category field to an entry that is limited for 1 category selection
2. Choose one category at your entry and save
3. Now try to choose another category, but do not yet save
4. existing category will be replaced
5. If you try to choose the previous category again it will still be grayed out.
6. Even when you remove all categories the ones selected will still be greyed out and can not be selected again, untill you reload the page or save the entry.

### Additional info

- Craft version: 3.0.0-beta.21 - 2017-07-07
- PHP version: 7.0.15
- Database driver & version: Mysql version 5.6.35
- Plugins & versions: No plugins

---

Step 2 - chose category "PLAY":
![schermafbeelding 2017-07-13 om 13 57 32](https://user-images.githubusercontent.com/661751/28305856-91901e50-6b9d-11e7-8299-c3585000fffb.png)

---

Step 3 - choose another category:
![schermafbeelding 2017-07-13 om 13 57 41](https://user-images.githubusercontent.com/661751/28305857-91a87d60-6b9d-11e7-8334-db7505e9913d.png)

---

Step 4 - chose category "JUMP":
![schermafbeelding 2017-07-13 om 13 58 03](https://user-images.githubusercontent.com/661751/28305858-91aecec2-6b9d-11e7-8ad7-72f5a59a6754.png)

---

Step 5 - Try to choose category "PLAY" again:
![schermafbeelding 2017-07-13 om 13 58 20](https://user-images.githubusercontent.com/661751/28305859-91b1a6d8-6b9d-11e7-9017-9eaa5f83567e.png)

**Comment by brandonkelly** [comment]
Was able to reproduce this. Looks like it only happens if the 2nd category you choose is positioned _above_ the initially-selected category. (Otherwise the new selection will get stripped out when the Branch Limit setting is applied.)
