### ISSUE TITLE
downloadBackupFile allows access to download zip files all over the filesystem.

### ISSUE THREAD

**Issue by roelvanhintum** [craftcms/cms#1848]
Modifying the downloadBackupFile url allows file access to other zips in the filesystem (also outside of craft). 

Example for: `../../../other/folder/file`
```
/index.php?p=admin/actions/tools/downloadBackupFile&fileName=..%2F..%2F..%2Fother%2Ffolder..%2Ffile
```

- Craft version: 2.6.2987

**Comment by brandonkelly** [comment]
Thanks for pointing that out, but in the future please send security-related bug reports directly to us (support@craftcms.com) rather than posting publicly here, per the [contribution guidelines](https://github.com/craftcms/cms/blob/develop/CONTRIBUTING.md).

**Comment by roelvanhintum** [comment]
Sorry about that, completely missed the security guideline.
