### ISSUE TITLE
Entries field: Chosen entries can not be saved after adding a site

### ISSUE THREAD

**Issue by Luuc15** [craftcms/cms#1854]
### Description
When you have an entry with an entries field, then after adding a new site, existing chosen entries are removed and it is not possible to add chosen entries again.

### Steps to reproduce

1. Make a clean install of the cms
2. Create two sections, in this case a "products" section and a "projects" section, type channel.
3. Create a new fieldgroup with the name "Relations"
4. Create a new field with fieldtype entries, with name "Projects" and with entry source "Projects"
5. Add the "Projects" field to the entry type of the "Products" section
6. Create two new entries. One in the channel "Products" and one in the channel "Projects"
7. Now edit a "Product" entry and add one project with the entries field

8. Add a site through settings->sites
9. Enable the added site for both sections (products and projects sections) by editing the sections site settings, and set default status for each site to be switched off.

10. Now go to your product entry and see that there is one chosen project entry for the entries field. 
11. Now press the "Save" button and view the product entry again.
12. The chosen project entry for the entries field is now gone!
13. If you now try to choose a project entry again with the entries field and try to save, then it will not save the entries field any more and it will stay empty.

### Additional info

- Craft version: 3.0.0-beta.22 - 2017-07-14 
- PHP version: 7.0.15
- Database driver & version: MySql 5.6.35
- Plugins & versions: No plugins

---

Step 2 - Create sections:
![schermafbeelding 2017-07-20 om 13 43 23](https://user-images.githubusercontent.com/661751/28419434-32acd432-6d5f-11e7-9c24-b006abcb7b46.png)
![schermafbeelding 2017-07-20 om 13 43 45](https://user-images.githubusercontent.com/661751/28419435-32ad7aea-6d5f-11e7-991e-e7d56a98bb5a.png)

---

Step 4 - Create field:
![schermafbeelding 2017-07-20 om 13 46 36](https://user-images.githubusercontent.com/661751/28419483-532f56c6-6d5f-11e7-82e7-67992770833c.png)

---

Step 5 - Add field to entry type:
![schermafbeelding 2017-07-20 om 15 16 42](https://user-images.githubusercontent.com/661751/28419532-8818f900-6d5f-11e7-9a48-2c74a0997753.png)

--- 

Step 6 - Create two entries:
![schermafbeelding 2017-07-20 om 15 14 48](https://user-images.githubusercontent.com/661751/28419570-abcf95ac-6d5f-11e7-90c2-319b33886a10.png)
![schermafbeelding 2017-07-20 om 15 15 06](https://user-images.githubusercontent.com/661751/28419571-abd03a16-6d5f-11e7-95ec-a594351e8b51.png)
![schermafbeelding 2017-07-20 om 13 50 53](https://user-images.githubusercontent.com/661751/28419580-b3631b0e-6d5f-11e7-804e-44761d845e7e.png)

---

Step 7 - Edit entry
![schermafbeelding 2017-07-20 om 15 17 03](https://user-images.githubusercontent.com/661751/28419602-cc666e44-6d5f-11e7-956a-af7cd3c08bfc.png)

---

Step 8 - Add site
![schermafbeelding 2017-07-20 om 15 17 44](https://user-images.githubusercontent.com/661751/28419621-dfcf7228-6d5f-11e7-9e94-592254257204.png)

---

Step 9 - Enable site for sections
![schermafbeelding 2017-07-20 om 15 18 26](https://user-images.githubusercontent.com/661751/28419644-f31a78d2-6d5f-11e7-8d83-abba160ba84a.png)
![schermafbeelding 2017-07-20 om 15 18 46](https://user-images.githubusercontent.com/661751/28419645-f3239a5c-6d5f-11e7-8494-84cc80e606ed.png)

---

Step 10 - There is one chosen "project" entry
![schermafbeelding 2017-07-20 om 15 31 41](https://user-images.githubusercontent.com/661751/28419830-92eaeef0-6d60-11e7-95e3-10815ea6d6bd.png)

---

Step 12 and 13 - There is no chosen "project" entry anymore, and not possible to add again.
![schermafbeelding 2017-07-20 om 15 19 19](https://user-images.githubusercontent.com/661751/28419760-5e36b022-6d60-11e7-9cbf-6a3ee80fce6a.png)

**Comment by brandonkelly** [comment]
Thanks for the detailed steps to reproduce and the screenshots. Unfortunately even with them, I’m not able to reproduce this. Can you send a DB backup to support@craftcms.com, please?

**Comment by brandonkelly** [comment]
To reproduce this, the related entry must be disabled in one of the other sites.

**Comment by Luuc15** [comment]
Good to hear you found a way to reproduce this.
If we follow step 9 (see screenshot) with default status "disabled", then the existing entries will always be disabled for the site we just added right?

**Comment by brandonkelly** [comment]
@Luuc15 Yep you’re right – I must have overlooked that originally 😞
