### ISSUE TITLE
Ability for plugin to detect what site's content has actually been edited

### ISSUE THREAD

**Issue by acehead** [craftcms/cms#1855]
### Description
When an entry or global set is being edited it is not possible for plugin (according to my knowledge) to detect which site it belongs to.

### Steps to reproduce

1. Create simple plugin, put the following code in its `init()` method:

    ```php
    Event::on(
        Elements::class,
        Elements::EVENT_AFTER_SAVE_ELEMENT,
        function (ElementEvent $event) {
            Craft::info(
                'Elements::EVENT_AFTER_SAVE_ELEMENT Site ID from event: '.$event->element->siteId,
                __METHOD__
            );
            Craft::info(
                'Elements::EVENT_AFTER_SAVE_ELEMENT Current Site ID: '.Craft::$app->getSites()->currentSite->id ,
                __METHOD__
            );
        }
    );
    ```

2. Create 3 sites, open CP on site # 1 and edit content belonging to site # 2. Save an entry.
3. When devMode enabled notice that event has been triggered for multiple sites, currentSite property also does not refer to the site acutally being edited.

### Additional info

- Craft version: Craft Pro 3.0.0-beta.22
- PHP version: PHP/7.1.1
- Database driver & version: PostgreSQL 9.6.2

**Comment by brandonkelly** [comment]
When you save an entry, it will first get saved for the site you were editing, but then in order to apply fields’ Translation settings, it propagates the save across the other sites.

You can tell if the event is getting called in the course of the propagation step by checking the element’s `propagating` property:

```php
if ($event->element->propagating) {
    // Not the site the element was deliberately saved for
    return;
}
```

**Comment by acehead** [comment]
Hi Brandon,

Thanks for your reply.

I have adopted your code, but it still seems to fire multiple times for a number of sites. I'm using following snippet:
        ```
Event::on(
            Elements::class,
            Elements::EVENT_AFTER_SAVE_ELEMENT,
            function (ElementEvent $event) {
                if (!$event->propagating) {
                    $siteId = Craft::$app->request->post('siteId');
                    Craft::info(
                        'Elements::EVENT_AFTER_SAVE_ELEMENT Detected site id: '.$event->element->siteId.', post site id: '.$siteId,
                        __METHOD__
                    );
                }
            }
        );
```
From the logs you can notice that the logging is still fored multiple times and site id is not always the site id from the post (workaround method I'm using now)

**Comment by andris-sevcenko** [comment]
You should be checking for the `propagating` property on the element of the event, not the event itself.

**Comment by acehead** [comment]
Hi, sorry, I took the code from my second attempt to get it working. Fixed it in my comment, but the question remains valid

**Comment by brandonkelly** [comment]
@acehead Does your entry have a Matrix/Neo field? If so there might just be multiple elements that need to get saved in the course of saving your entry.

**Comment by acehead** [comment]
Hi, yes, we use matrix fields quite heavily. I'm pretty ok with event firing multiple times, however it will be great to find a way to filter out only event originating from the site being edited. `$event->element->propagating` does not do the job, `Craft::$app->request->post('siteId')` does, but imho this is more like a hack/workaround.

**Comment by brandonkelly** [comment]
You can find the site that the element is getting saved for by checking `$event->element->siteId` (as you did in the initial post). You can also determine if `$element` is an entry by checking

```php
if ($event->element instanceof \craft\elements\Entry::class) {
    // ...
}
```
