### ISSUE TITLE
Plugin development exceptions returns to login

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#1858]
### Description

It seems when a plugin has a fatal exception the login screen is presented. This makes it difficult to debug the actual exception.

**Comment by nateiler** [comment]
I have noticed this as well too.  I spent a few minutes trying to get to the root of it, but didn't get very far.

**Comment by brandonkelly** [comment]
I haven’t seen this. If you can come up with steps to reproduce, we can look into it.

**Comment by brandonkelly** [comment]
Just saw this when loading a core class with a syntax error. Will look into it.

**Comment by brandonkelly** [comment]
Fixed this, at least for one case where I was able to reproduce it. If you see it going forward after Beta 23 comes out, let me know.

**Comment by leevigraham** [comment]
@brandonkelly, Awesome fixed the issue for me.
