### ISSUE TITLE
Page not found on public registration

### ISSUE THREAD

**Issue by S1lentium** [craftcms/cms#1859]
### Description

HTTP 404 – Not Found – yii\web\NotFoundHttpException
Unable to resolve the request: users/saveUser

I do the same as described here:
https://craftcms.com/docs/templating/user-registration-form

### Additional info

- Craft version: 3.0.0-beta.22
- PHP version: 7.0
- Database driver & version: MySQL 5.5

**Comment by takobell** [comment]
You're referencing the Craft 2 docs.  For Craft 3 you'd need to change the hidden `action` input to `<input type="hidden" name="action" value="users/save-user">` per https://github.com/craftcms/docs/blob/master/en/upgrade.md#action-params
