### ISSUE TITLE
Craft Path Not Found when using Craft-cli

### ISSUE THREAD

**Issue by myleshyson** [craftcms/cms#1861]
### Description
I get an error "Your Craft path could not be found" when trying to use the craft-cli. 

### Steps to reproduce

1. Install fresh version of craft via compser.
2. Cd into project and run craft show:config. Returns "Your Craft path could not found"

### Additional info

- Craft version: 3.0.0-beta.22
- PHP version: 7.0.2
- Database driver & version: 5.7.18
- Plugins & versions: craft-cli 0.14.2

**Comment by takobell** [comment]
You should file an issue on the craft-cli plugin repo page (or contribute to this one which mentions Craft 3 compatibility; https://github.com/rsanchez/craft-cli/issues/24)
