### ISSUE TITLE
FR: Make browser language accessible in template

### ISSUE THREAD

**Issue by stablestorage** [craftcms/cms#1863]
### Description
Please make the Browser language (getPreferredLanguage()) from HttpRequestService available in template by putting a getter emthod in the HttpRequestVariable.

This would help me to redirect the user based on this variable when  #s/he enters the page.

### Additional info

- Craft version: 2.6
- PHP version: 7.0
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
In Craft 3 you can access that via `craft.app.request.acceptableLanguages`. Not adding new template variable methods in Craft 2 though.
