### ISSUE TITLE
ContentBehavior.php prevents programmatic migration

### ISSUE THREAD

**Issue by my2ter** [craftcms/cms#1865]
### Description

My migration is:

- Creating fields
- Creating category groups with previously created fields
- Creating category elements within previously created groups with content

The problem occurs when saving a category element because the **ContentBehavior.php** class hasn't been regenerated yet. Because the field version is only updated at the end of a request the following code will fail with the exception **Setting unknown property: craft\behaviors\ContentBehavior::myFieldHandle (vendor/yiisoft/yii2/base/Object.php:161)**

```php // vendor/craftcms/cms/src/base/Element.php:1502
$behavior = $this->getBehavior('customFields');
$behavior->$fieldHandle = $value; // This will fail
```

Running the migration after this error will pass because the autoload will recompile the **ContentBehavior.php** (detecting the fieldVersion change) which will now contain my new fields handle.

I do not have a solution at this point and this implementation goes probably against what you want for the migrations but I do think that something like that should work.

### Steps to reproduce
You should in one request (like a migration) try to:

1. Create a new field
2. Assign the field to a category group
3. Create and save a new category element

### Quick code example
I omitted some code to keep it short

```php
// Create field
$field = Craft::$app->fields->createField([
    'name' => 'My Field',
    'handle' => 'myFieldHandle',
    // other parameters
]);

Craft::$app->fields->saveField($field);

// Create group
$group = new \craft\models\CategoryGroup();
$group->handle = 'aGroup';

// Create tabs and layout
$tab = new \craft\models\FieldLayoutTab();
$tab->name = 'Content';
$tab->setFields([$field]);
$tabLayout[] = $tab;

$layout = new \craft\models\FieldLayout();
$layout->setTabs($tabLayout);

// Add layout to group
$layout->type = \craft\elements\Category::class;
$group->setFieldLayout($layout);

Craft::$app->categories->saveGroup($group);

// Create category
$category = new \craft\elements\Category();
$category->groupId = $group->id;
$category->setFieldValue('myFieldHandle', 'Some content');

Craft::$app->getElements()->saveElement($category);
```

### Additional info

- Craft version: 3.0.0-beta.22
- PHP version: 7.1
- Database driver & version: MySQL 5.7

**Comment by brandonkelly** [comment]
Good one! Not actually sure what the right way to fix this is off the top of my head. Maybe keep track of any custom field handles that have been saved during the current request, and add magic getter/setter methods for those in ContentBehavior.

**Comment by my2ter** [comment]
Hey @brandonkelly !

**Comment by my2ter** [comment]
Hey @brandonkelly, thanks for checking this one.

Unless I a missing something I cannot use magic setters/getters (that would have been one possible solution) because the **ContentBehaviour** class extends **\yii\base\Object** and it will throw an exception.

```php
public function __get($name)
{
    $getter = 'get' . $name;
    if (method_exists($this, $getter)) {
        return $this->$getter();
    } elseif (method_exists($this, 'set' . $name)) {
        throw new InvalidCallException('Getting write-only property: ' . get_class($this) . '::' . $name);
    } else {
        throw new UnknownPropertyException('Getting unknown property: ' . get_class($this) . '::' . $name);
    }
}

public function __set($name, $value)
{
    $setter = 'set' . $name;
    if (method_exists($this, $setter)) {
        $this->$setter($value);
    } elseif (method_exists($this, 'get' . $name)) {
        throw new InvalidCallException('Setting read-only property: ' . get_class($this) . '::' . $name);
    } else {
        throw new UnknownPropertyException('Setting unknown property: ' . get_class($this) . '::' . $name);
    }
}
```

Tbh the **\yii\base\Object** class is pretty restrictive anyway..

**Comment by brandonkelly** [comment]
Sorry for the confusion – I was just thinking out loud about how _we_ colud fix this for you :)
