### ISSUE TITLE
Changing columns for assets on subfolders are always applied to first asset volume

### ISSUE THREAD

**Issue by hiasl** [craftcms/cms#1871]
### Description
If you have an 2 assets volumes and you create a subfolder on the second one and then change the preference what columns to show on the subfolder (e.g. add "id"), it will be applied to the first asset volume, not the second one. The selected subfolder of the second volume does not seem to know its parent when the preferences are applied.

Volume 1
Volume 2
- Subfolder

### Steps to reproduce

1. Make sure you have 2 assets volumes
2. Click on "Assets"
3. Make sure the second asset volume has subfolders
4. Select one subfolder in the second asset volume
5. Now click the "Customize Sources" Icon below and change the shown columns
6. The selected asset volume is now the first one and the changes are applied to the first one as well

### Additional info

PHP version	7.1.6-1 ubuntu16.04.1+deb.sury.org+1
Database driver & version	MySQL 5.6.13
Image driver & version	Imagick 3.4.3, ImageMagick 6.8.9-9
Craft edition & version	Craft Pro 3.0.0-beta.22
Yii version	2.0.12
Twig version	2.3.2
Guzzle version	6.2.1
Imagine version	0.7-dev

**Comment by brandonkelly** [comment]
This is expected behavior – visible columns always apply to the volume as a whole, not per-folder. (You’ll notice that the subfolder is not listed on the source list within the Customize Source Modal.)

**Comment by hiasl** [comment]
NO, please reopen!

It's applied to the first (of many volumes), but not the one containing the subfolder.

**Comment by brandonkelly** [comment]
Sorry, misunderstood.
