### ISSUE TITLE
image.width / height is NULL

### ISSUE THREAD

**Issue by hiasl** [craftcms/cms#1872]
### Description
`image` is an asset
`image.width` and `image.height` dump to NULL, but `image.url` works

I tried the same thing on a brand new craft 3 installation on the same server and it does not happen, however it occurs in my project on 2 different machines (vagrant / central dev server). Craft Beta version is the same.

Also resizing with `getUrl({...config here...})` works

I have no clue, which difference in code / configuration is causing this behavior.

if needed I can provide the full project to solve this via e-mail / support mail

### Steps to (not) reproduce

1. upload an image to an asset volume
2. reference the image in a loop or loading it via id
3. output this in a template: `Img Width: {{ image.width }}, Image height: {{ image.height }}, Image Url: {{ image.url }}, Dump: {{ dump(image.width) }}`
4. this is what i get: `Img Width: , Image height: , Image Url: /userfiles/photos/test/blabla.jpg, Dump: NULL`
### Additional info

PHP version	7.1.6-1 ubuntu16.04.1+deb.sury.org+1
Database driver & version	MySQL 5.7.19-0ubuntu0.16.04.1
Image driver & version	Imagick 3.4.3, ImageMagick 6.8.9-9
Craft edition & version	Craft Pro 3.0.0-beta.22
Yii version	2.0.12
Twig version	2.3.2
Guzzle version	6.2.1
Imagine version	0.7-dev

**Comment by brandonkelly** [comment]
Can you please send us a DB backup to support@craftcms.com, and reference this issue number?

**Comment by brandonkelly** [comment]
@andris-sevcenko FYI the only assets where I was able to reproduce this are SVGs. (Just using the standard Happy Lager DB dump.) Looks like @hiasl is seeing it with a JPG though.

**Comment by hiasl** [comment]
The bug is fixed, but is it really true, that I need to upload my images again? Because all images uploaded before still do not know their width/height, only new ones have the information. And this is not so nice, since the images are already used in content. Any trick, that might help me?

**Comment by andris-sevcenko** [comment]
Re-indexing the Asset Volume should populate the width/height values.

**Comment by hiasl** [comment]
yes, that does it. did not know this exists. thanks for all and the fast fix!
