### ISSUE TITLE
In "General Settings" page, SVG uploads generate error

### ISSUE THREAD

**Issue by johnfmorton** [craftcms/cms#1874]
### Description

In the Settings > General Settings page within the control panel, when trying to upload SVG files for the _Login Page Logo_ and _Site Icon_, I receive a an error that says "the uploaded file is not an image". 

The same image when uploaded as an Assets panel, there is no error generate and the upload proceeds as expected.

### Steps to reproduce

1. Try to upload a new SVG in _Login Page Logo_ in General Settings.
2. Try to upload a new SVG in _Site Icon_ in General Settings.

### Additional info

- Craft version: 3.0.0-beta.22
- PHP version: 7.1.5-1+deb.sury.org~xenial+2
- Database driver & version: MySQL 5.7.19-0ubuntu0.16.04.1
- Plugins & versions: Doxter

**Comment by nikolowry** [comment]
Status? My experience is the same running a nearly identical stack with Apache2.

However, if I run `php -s 0.0.0.0:9000 -t public` locally on my development box all works as intended.  

I even tried to add the following to my server's .htaccess but had no luck:

```
#.htaccess
AddType image/svg+xml svg svgz
AddEncoding gzip svgz
```

**Comment by brandonkelly** [comment]
@andris-sevcenko correct me if I’m wrong, but isn’t IM only required if you want to transform SVGs? Uploading them should work fine with GD right?

**Comment by andris-sevcenko** [comment]
This issue happened because of the changes in how Craft detected if it could manipulate an image or not. During this change, Craft conveniently forgot that SVG manipulation does not require any image driver and hence is always supported, falling back to what the used image driver was reporting. (Surprise! GD does not support SVG files)
