### ISSUE TITLE
Setting title variable from routed template not working

### ISSUE THREAD

**Issue by matthisamoto** [craftcms/cms#1876]
### Description

When using a route to grab a template, I can't seem to set the page title properly from that template with `{% set title = 'Title' %}`

When I print out the title variable in the page it is correct but the page title in the browser does not acknowledge this, as if the variable never makes it back up the tree to the layout.

I don't know if it would matter but this template file does not get used for any existing sections, only for this routed path.

### Steps to reproduce

1. Create route to a template (mine in particular was for an event month, so the route looked like `events/{year}/{month}`)
2. Try to set title variable from that template using `{% set title = 'Title' %}`

### Additional info

- Craft version: 2.6.2987 (Pro)
- PHP version: 5.6.30
- Database driver & version: MySQL 5.6.35
- Plugins & versions: 
    - Attach Channel 1.0
    - Beer Finder Import 1.0
    - Commerce 1.2.1346
    - Cookies 1.0.4
    - Events 2.0.26
    - Field Manager 1.5.3
    - InstaBlog 1.2
    - Lost and Found 1.0.1
    - Many to Many 0.1.2
    - Navee 1.3.0
    - Reasons 1.0.10
    - Smart Map 2.4.0
    - SuperSort 1.2.0
    - Typogrify 1.0.1

**Comment by brandonkelly** [comment]
You need to actually output that `title` variable in the `<title>` tag:

```twig
<head>
    <title>{{ title }}</title>
    <!-- ... -->
</head>
```

**Comment by matthisamoto** [comment]
Sorry I figured that was a given, that's what I mean, it is output in my layout, but the variable doesn't seem to resolve, only with this routed template.

**Comment by brandonkelly** [comment]
This is pretty basic Twig functionality, so 99.99% chance it's not a bug in Craft/Twig, so will leave it closed, but can try helping you solve it.

Where is the `title` variable getting defined in relation to it being output in the `<title>` tag?

**Comment by matthisamoto** [comment]
My route loads the template at events/month, which has the title var defined within it. It extends a layout template where the title tag lives and the variable title is printed. I can print the title within the template content itself and it is correct. 

This is how I've got each unique section template set up, and it works beautifully, but just on this template, loaded via a route instead of through the section model.

I do appreciate your time, and you're right it may be just a Twig thing, I have been having trouble separating the two. I am mostly trying to understand why does it only happen with the route?

**Comment by brandonkelly** [comment]
Can you paste in the route template, plus all of its parent template(s)?

**Comment by matthisamoto** [comment]
I had the lines inside the block tags. I guess the title variable needed to be set above this? Explains why it would print inside the template. I'm sorry to waste your time on this.

**Comment by brandonkelly** [comment]
No worries :) Yeah for a variable to be available in a parent template, it needs to be set outside of the `{% block %}` tags.
