### ISSUE TITLE
Uninstall field throws translation error on fields screen

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#1877]
### Steps to reproduce

1. Install field type plugin
2. Create new field using plugin
3. Uninstall plugin
4. Visit /admin/settings/fields

![image](https://user-images.githubusercontent.com/25124/28660671-492bd9f4-72f7-11e7-9fba-a4e8d04ae480.png)

**Comment by brandonkelly** [comment]
Issue is that as long as a plugin is still _Composer_-installed, its classes are still autoloadable, so existing Craft fields can still load its field types, etc. But if its field types are loaded without the primary plugin class preceding it, than anything the primary plugin class was supposed to do (like set up the plugin’s translation category) won’t get done.

The plan is that once the Plugin Store makes it into Craft, uninstalling a plugin will also Composer-remove it, so it is completely uninstalled.

**Comment by brandonkelly** [comment]
Probably the right way to fix this will be that the Component helper should verify that if the requested component belongs to a plugin, the plugin is still installed. If not, throw a MissingComponentException.
