### ISSUE TITLE
Error when using custom HtmlPurifier config

### ISSUE THREAD

**Issue by wei2go** [craftcms/cms#1878]
### Description
I have been using a custom HtmlPurifier config to allow custom style and class attributes in Rich Text: 

`{
	"CSS.Trusted": true,
	"HTML.AllowedAttributes": "*.class"
}`

This has been working fine (running Craft CMS 2.6.2983), until I updated to 2.6.2987. It gives me this user warning every time I try to save an entry with the Rich Text field:

![screenshot - 28_07_2017 11_31_33 am](https://user-images.githubusercontent.com/19367571/28698951-034a6ee4-738a-11e7-86a5-177fafcbb79d.png)

### Additional info

- Craft version: 2.6.2987
- PHP version: 7.0.21
- Database driver & version: MySQL 5.1.0

**Comment by brandonkelly** [comment]
How are you setting your custom HTMLPurifier config? Craft 2 doesn’t have a supported way to do that.

**Comment by wei2go** [comment]
Hi Brandon,

Thanks for reply.

I put the custom .json file under craft/config/htmlpurifier, like what it says on the Rich Text field's setting screen.

![screenshot - 31_07_2017 5_08_39 pm](https://user-images.githubusercontent.com/19367571/28766487-1337a2dc-7613-11e7-963a-bc5261ab51b1.png)

You might be right about it's never supported, because I just realised that my Rich Text field's htmlpurifier setting has actually been set to 'Default' at some point. But that's strange, cuz I do remember that I managed to put 'style' attribute into the HTML editor in redactor in this way.

**Comment by brandonkelly** [comment]
Doh, sorry, I forgot we added that for Craft 2.

I’m not sure why all of a sudden you are receiving that error, but it is to be expected, based on your HTMLPurifier config. You are basically saying that `class` is the only allowed element attribute – so if you were to submit HTML with an `<img>` tag with a `src` attribute, it would cause the error you’re getting.

**Comment by wei2go** [comment]
The weird thing is, the error message actually comes from a simple text input into the redactor like this, which doesn't contain any attributes.:

![screenshot - 2_08_2017 10_12_50 am](https://user-images.githubusercontent.com/19367571/28852261-43dc7706-776b-11e7-92ab-2d6024572c1f.png)

**Comment by brandonkelly** [comment]
Strange - any ideas @takobell ?

**Comment by takobell** [comment]
The HTML Purifier version in Craft 2.6.2983 was 4.8.0 and the HTML Purifier version in Craft 2.6.2987 is 4.9.3.

Nothing in their changelog is jumping out at me that would explain this: http://repo.or.cz/w/htmlpurifier.git/blob/v4.9.3:/NEWS

After doing an xDebug session, HTML Purifier isn't complaining about the content of the Rich Text field, but about an internal list of HTML elements it parses during setup (one of them being an `img` tag where it's looking for a required `src` element - hence the error).  I don't know enough about HTML Purifier to know whether this is an HTML Purifier bug or an expected change in behavior in their code or how supplying that custom config is affecting it.

**Comment by wei2go** [comment]
Weird thing, isn't it? Thanks for the info guys.
