### ISSUE TITLE
Admin entry Url pattern is {{ entry.id }}-{{ entry.slug}}

### ISSUE THREAD

**Issue by nateiler** [craftcms/cms#1881]
Is there a particular reason why the entry/element Id AND slug are used to construct am admin url?  Often we'll internally reference an entry Id, but we can't simply append it to a url segment ... we also need to know the slug.  Seems a little redundant and complex.

**Comment by brandonkelly** [comment]
The slug is just there so it's easy to identify the entry when passing the URL around, but it's optional – Craft will still load the correct entry edit page as long as the ID is there.
