### ISSUE TITLE
"It looks like someone is currently performing a system update" error when updating

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1883]
### Description
Ok, this one has to do with my famous decades-of-updates-from-C2 site.

Getting around issues in 'number  one' report #1884, I have Craft telling me 'It looks like someone is currently performing a system update.'  This happens whether I initiate the update within Craft CP, or if I send up to Vagrant the results of a composer update from the source.

I did a number of backoffs, reverting composer several ways, and nothing helps this, except going into the database and turning off the craft_info maintenance field.

Once I set that off, the update proceeds, and eventually I get beta 23 showing, with the usual issue of the Dashboard still showing update necessary until I go back to Updates and try again to get that turned off.

It very much appears the beta 23 software load is turning on that maintenance flag, prior to reporting it's locked out of database update because the flag is set???  Very consistent, and only on my C2-converted site.

### Steps to reproduce

1. Have a converted site with beta 22 (actually 22 as of 22 July; composer updated dev-develop last for this site then, from git log)
2. Try to update to beta 23

### Additional info

- Craft version: as just above
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
This is a seemingly unavoidable consequence of some updater changes that came in Beta 20, in which Craft now uses Maintenance Mode as a way to avoid two people attempting to update Craft at the same time. The issue is, if something goes wrong with an update, and the update attempt is abandoned, Craft has no way of knowing that it should disable Maintenance Mode, and the admin just has to go into the DB and manually disable it.

Will keep this open, and continue thinking about how we can improve it.

**Comment by narration-sd** [comment]
Hmm. Fair enough, except I believed to have turned maintenance bit off, brought up a fresh beta 23 /vendor, tried to update, and found it locked again. .

Turning the bit off, then things proceed. But have you an idea where there was a first fail to turn it on by your insight just now? Since that first fail appears to sees it already on, though it wasn't?

Might actually be a clue, seems anyway. And again, only on an upgraded site, which I believe to be laid out in the pattern  you expect lately, /vendor under /craft. Hope info helps...

**Comment by brandonkelly** [comment]
It doesn’t get turned on until the updater starts working. Possible you double-clicked on the “Update” button or something?

**Comment by narration-sd** [comment]
No, it happened just as  you say:  manually cleared Offline bit set again once I'd clicked Update, just once, on a new try.

I guess you have another bit set somewhere for having failed; had thought of it and was going to look this up but got beleaguered last night with trying to get a photo to print out in proper color balance for a gift. Another worked, doesn't work crisis :)

Noting Adam's #1885, guess this isn't solely a C2-updated site problem, so relaxed on that. 

The initial update fail that set my chain of events going would no doubt be the first time I tried to update this site and failed due to the old-method site layout, if you remember, and which I was trying to validate had gone away, having restructured the site to the current from-C22 model. 

So I think the circle is closed, and indeed updateing from the CP did work fine for this site, once the bad-bit issue was removed. Going to forgo my own head-scratching about this sequence of events for the fault, and let you guys do it...take care!

**Comment by brandonkelly** [comment]
So it sounds like maybe the issue really started when updating to Beta 22, which left the `maintenance` bit set to `1`, however that never surfaced as a problem until you attempted to update to Beta 23.

**Comment by narration-sd** [comment]
Brandon, I thought so.  Reflection after, there might have been some other upset also to do it at the time of Craft 23, as I believe to have seen it on one other site, and only the first had the 22 fail due to old structure.

Apologies for the vagueness -- water under bridge since as per usual, not to say some weekend.  But I suspect we both feel the basic issue will need its fix, as others are now running into this -- and of course there will be conversions to come from Craft 2 which will  likely have initial fails as people bring them together. 

As they'd say in Britain, cheers, mate....

**Comment by narration-sd** [comment]
@brandonkelly  Hmm, a flash, from some way had  been considering this 'slow race' condition.

In all cases, the regular Maintenance mode was _not_ set prior to beginning the Beta 23 update. Underline.

So whatever sets this off, it's not that flag in craft_info table directly, in my belief.  This is why some of the mention of some extra 'bit' flag seeming to have been added.

Sequence:
- Craft beta at earlier stage works, possibly or not reorganized recently
- attempt Beta 23, whether by CP Update button, or by source Composer update.
- get the site-offline, immediately from button, or once you have Composer'd source uploaded
- clear the craft_info table flag
- site updates normally, or just begins to work, in case of Composer update at dev source
