### ISSUE TITLE
couple of funny things with updates - number one

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1884]
### Description
Belated as apparently I didn't save it the first time. Hope to have remembered well??

Entering CP on a Craft 3 site, see there's an update in the Dashboard. Clicking the link gives however a 404.

If you then go to Utilties>Updates manually, that works. And afterwards, so does the link in the Dashboard.

Other issues have to do with my plugin - should go away with plugin store, but may be important to doc well for non-store plugins; possibly back later on this aspect. Where fixed, update goes through.

### Steps to reproduce

1. As above.
2.

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by narration-sd** [comment]
Looks like you caught and fixed it -- closing...

**Comment by brandonkelly** [comment]
First one was posted, I just renamed it: #1882
