### ISSUE TITLE
Beta Update .22 -> .23 broke element queries with conditions on custom fields 

### ISSUE THREAD

**Issue by hiasl** [craftcms/cms#1887]
### Description
This `craft.entries.section('news').showOnStartpage(true)` worked on Beta 22 but does not work on Beta 23 anymore, where showOnStartpage is the handle of a custom lightswitch field. I also tried with value '1' instead of true.

I get this exception: `Calling unknown method: craft\elements\db\EntryQuery::showOnStartpage()
`

Also interesting: I have a second lightswitch field called "sticky" as handle in the news section, and although I do not get the exception when querying with a condition on this field ( `.sticky(true)` ) the results are not correct and any further daisy chained query command (in my case the limit command) causes an error:

`Impossible to invoke a method ("limit") on a null variable.`

The only difference is that the the 2 handles look different, one is camel case (unknow method exception), the other lowercase (impossible to invoke method exception and wrong result).

Addition 31/7/2017: It also does not work on a date field anymore, where I query with `.date(...)`

### Steps to reproduce

1. Have a section with a custom lightswitch field and give it a camelCase handle
2. Query for elements and limit on this field: 
`craft.entries.section(<yourSection>).<yourFieldHandle>(true)`
3. Exception is thrown

### Additional info

Maybe important: Project is multilingual

PHP version	7.1.6-1 ubuntu16.04.1+deb.sury.org+1
Database driver & version	MySQL 5.6.13
Image driver & version	Imagick 3.4.3, ImageMagick 6.8.9-9
Craft edition & version	Craft Pro 3.0.0-beta.23

**Comment by brandonkelly** [comment]
@hiasl Your first issue is most likely just due to out-of-date ContentBehavior.php / ElementQueryBehavior.php files in craft/storage/runtime/compiled_classes/. There is a migration that should have forced them to get re-generated as part of the Beta 23 update, but maybe that didn’t work as intended for you. Try deleting those files and see if the 1st error persists. 

Second issue is definitely a bug, and just fixed that @ 7729a04.

**Comment by grantnhoward** [comment]
Still experiencing this with Beta 24, have followed the above steps to clear the compiled classes as well.
`{% set profile = craft.users.customProfileField(craft.app.request.segments|last).one() %}`

throws
Unknown Method – yii\base\UnknownMethodException
Calling unknown method: craft\behaviors\ElementQueryBehavior::one()

Craft Pro 3.0.0-beta.24
PHP version | 7.0.22-0ubuntu0.16.04.1
MySQL 5.6.27-log

**Comment by hiasl** [comment]
@brandonkelly 
First issue was my fault (camelCase typo), not an out-of-date compiled file.

BUT with second issue @grantnhoward  is right, the problem is not solved (or it's a new different one), I got this:
`Calling unknown method: craft\behaviors\ElementQueryBehavior::all()` when trying to iterate over result (without calling all() - deprecated now, I know)

**Comment by brandonkelly** [comment]
Ah I see what’s going on here. Just fixed for the next release. You can get the patch in the meantime by running:

```
composer require craftcms/cms:"dev-develop as 3.0.0-beta.99"
```
