### ISSUE TITLE
Craft 3 Multi-site multiple sites on same domain not "working"

### ISSUE THREAD

**Issue by jeffreygnatek** [craftcms/cms#1888]
### Description

Attempting to use the multi-site feature to have multiple micro-sites within the same domain, such as

http://foobar.com - main site
http://foobar.com/baz - a micro site that has a shared structure (but not identical) to the other microsites
http://foobar.com/bap - a micro site etc.

i believe this is done in the straight up craft hangout that talked about multisite, as they did it for different language versions on the same domain. i tried changing languages on my sites to see if that changed anything, but it did not.

the only way i'm currently able to get this to work is to use subdomains (or i suppose entirely different domains).

using valet also

### Steps to reproduce

With a fresh install of Craft 3, add a second site, using the base url as a sub directory of the main domain, such as

http://foobar.com - Default site
http://foobar.com/baz - Baz site

After adding a directory, index.php file for baz in the web directory, such as web/baz/index.php, you will be able to add an entry section single for homepage, and see it work. 

This is the only entry section that will work however, any subsequent section, such as having both sites share an about-us single, such as,

http://foobar.com/about-us - Default site About Us
http://foobar.com/baz/about-us - Baz site About Us

will result in the template not being found, despite it existing as the default "about-us/_entry" or anything else. the site will attempt to find instead, "baz/about-us" as a template.

### Additional info

- Craft version: 3 - 23
- PHP version: 7.1
- Database driver & version: 5.7.18
- Plugins & versions: Element API, S3 adapter

**Comment by hiasl** [comment]
I have exactly your setup working here with 3.23. Did you also copy the .htaccess to the subdir baz?

**Comment by jeffreygnatek** [comment]
that is great to hear, i did copy that as well. i'm wondering if it is something with valet, i will close for now.
