### ISSUE TITLE
false deprecation of EVENT_DEFINE_COMPONENTS as yet

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1889]
### Description
Looks like you got a bit ahead of  #1856, as this is on a feature branch

Consequence is you get the deprecation, also noted in PhpStorm.

- if you actually try to use EVENT_INIT, plugin variables will fail, as wrong event is passed
- doco around beta 20 changes is inscrutable enough that you're not sure also just where the event registration should go, or if naming of variable changes for Twig scripts. Answers are, 1) after the parent init() etc. is fine; 2) variable naming stays the same, e.g. craft.pluginhandle-kebabifneeded.varname. Probably without the function-calling parens; either way works for now.

Improvement in the plugin upgrade doc pretty needed, save hours x plugin developers time in the world debug tracing down...which probably is getting pretty big in the world, 5000 Craft devs registered?

### Steps to reproduce

1. be getting your plugin vars up to speed
2.

### Additional info

PHP version	7.1.2-4+deb.sury.org~xenial+1
Database driver & version	MySQL 5.7.17-0ubuntu0.16.04.1
Image driver & version	GD 7.1.2-4+deb.sury.org~xenial+1
Craft edition & version	Craft Personal 3.0.0-beta.23
Yii version	2.0.12
Twig version	2.3.2
Guzzle version	6.2.1
Imagine version	0.7-dev
Plugins

Trimmer	1.0.0
Bactrian	1.0.0
Standards Agent	2.0.1

**Comment by brandonkelly** [comment]
> if you actually try to use EVENT_INIT, plugin variables will fail, as wrong event is passed

What do you mean by that? As of Beta 23 the new EVENT_INIT event is up and running.

**Comment by brandonkelly** [comment]
[Beta 20 update guide](https://github.com/craftcms/cms/wiki/Beta-20--Update-Guide) is now updated with EVENT_INIT code example.

Also added a [Template Variables](https://github.com/craftcms/docs/blob/master/en/updating-plugins.md#template-variables) section to the Updating Plugins for Craft 3 guide.

**Comment by narration-sd** [comment]
It  is. But then when it fires, it sends the wrong type, Event, to the handler. 

Which wants a DefineComponentsEvent, properly because you need the components[] array included....

**Comment by brandonkelly** [comment]
The `EVENT_INIT` handler should expect a `yii\base\Event` object, not `craft\events\ DefineComponentsEvent`.

**Comment by narration-sd** [comment]
...okay, I see what you just did in the new example -- that  should  cover the problem, and looks a cleaner way to assure what gets set.

Cheers on the better doco 🥇

**Comment by narration-sd** [comment]
re: EVENT_INIT  expect type -- it does -- that was the problem.  Again, the new fixes it, am sure -- will try it, no report means  fine....

**Comment by narration-sd** [comment]
...tried, and it's fine...

beat me to the close....
