### ISSUE TITLE
settings button not showing on Settings>Plugins page

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1892]
### Description
Just noticed that though my plugin has settings, no button icon on the Plugins page appears

I've been using the icon button on the sidebar, which shows and works fine, so not sure how long this has been true.

### Steps to reproduce

1. plugin with settings and icon
2. try to see that in Plugins page

### Additional info

PHP version	7.1.2-4+deb.sury.org~xenial+1
Database driver & version	MySQL 5.7.17-0ubuntu0.16.04.1
Image driver & version	GD 7.1.2-4+deb.sury.org~xenial+1
Craft edition & version	Craft Personal 3.0.0-beta.23 -- up to minute dev-develop
Yii version	2.0.12
Twig version	2.3.2
Guzzle version	6.2.1
Imagine version	0.7-dev
Plugins

Trimmer	1.0.0
Bactrian	1.0.0
Standards Agent	2.0.1

**Comment by brandonkelly** [comment]
Does your plugin define the `hasCpSettings` property in its primary plugin class?

```php
public $hasCpSettings = true;
```

or could also be defined in composer.json – `extra.hasCpSettings`

```json
"extra": {
  "hasCpSettings": true
}
```

(note this is not the same as `hasCpSection`.)

**Comment by narration-sd** [comment]
p.s. I do have ` "hasSettings": true,` in the plugin's composer.json extras; tried changing that to kebab-case 'just in case', and two things:  1) didn't fix problem 2) settings still showed on sidebar.

**Comment by brandonkelly** [comment]
We renamed it from `hasSettings` to `hasCpSettings` in [Beta 8](https://github.com/craftcms/cms/blob/develop/CHANGELOG-v3.md#300-beta8---2017-03-24).

If the plugin is installed with a `path` repository, you will need to remove and re-install your plugin for composer.json changes to take effect.

**Comment by narration-sd** [comment]
I'm just trying that...Vagrant reloading....will report

**Comment by narration-sd** [comment]
Right -- that did it -- the name change.

Also right, did  have to remove/require the plugin to get its composer.json read, the old advice, and explains the anomaly.  Also, fix my path specs due to the new updated-site refactoring.

Closing, thanks, Brandon
