### ISSUE TITLE
Save plugin Settings returns to Dashboard

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1893]
### Description
In C2, save returns you to the Settings page, which is sensible -- see what you got.
In C3 Beta 23, save goes to Dashboard, though database shows setting was saved.

I couldn't find anything in the doc, and I am near certain this jump away didn't happen on earlier C3

### Steps to reproduce

1.  have a plugin with settings
2.  go to Settings page and change something (optional)
3.  Save by any method; button, ctrl-S, enter in form field
4.  End up on the Dashboard???
5.  craft_plugins.settings however shows the new value/s, and plugin properly responds to it.

### Additional info

PHP version	7.1.2-4+deb.sury.org\~xenial+1
Database driver & version	MySQL 5.7.17-0ubuntu0.16.04.1
Image driver & version	GD 7.1.2-4+deb.sury.org\~xenial+1
Craft edition & version	Craft Personal 3.0.0-beta.23 -- to the moment dev-develop
Yii version	2.0.12
Twig version	2.3.2
Guzzle version	6.2.1
Imagine version	0.7-dev
Plugins

Trimmer	1.0.0
Bactrian	1.0.0
Standards Agent	2.0.1

**Comment by brandonkelly** [comment]
Not able to reproduce this (tested with Guest Entries). Is your plugin setting template creating its own `<input name="redirect">` input, either directly or via `{{ redirectInput() }}`?

**Comment by narration-sd** [comment]
Hmm, no 'redirect' in the template anywhere.

I just tried putting in ```<input type="hidden" name="redirect" value="/settings/plugins/standardsagent">``` , and it wasn't obeyed -- still going to the Dashboard.

Have  to go and will look further. I'm including _includes/forms, for example, and making some mods so that I can have tabs on the settings page, which may be implicated, something changed in C3 there, perhaps....

**Comment by narration-sd** [comment]
And here's a funny thing: the view-source shows an (also bogus??) redirect already in there:

``` <input type="hidden" name="redirect" value="c56089949ad37bfaba4cca0cad018a36e924b16d3c394efd4def2d987e9b247fsettings/plugins"> ```

This didn't change with a cache clear from Utilities, or when I took my added <input> out.
 
Maybe something about  cpresources, or other?  Where should that redirect normally lead?


<input type="hidden" name="redirect" value="c56089949ad37bfaba4cca0cad018a36e924b16d3c394efd4def2d987e9b247fsettings/plugins">

**Comment by brandonkelly** [comment]
That is the expected redirect. From the base plugin settings template (settings/plugins/_settings.html):

```twig
{{ redirectInput('settings/plugins') }}
```

Note that in Craft 3, if you do want to type the `redirect` param manually, you will need to hash the value for Craft to respect it, and don’t have it start with a `/` as Craft will confuse that for a full URL:

```twig
<input type="hidden" name="redirect" value="{{ 'settings/plugins/standardsagent'|hash }}">

Try removing your custom `redirect` param though, and go to your plugin’s settings page. Then open your browser’s JavaScript console and type this:

```js
$('#container').serialize()
```

Can you paste in the output?

**Comment by narration-sd** [comment]
Sure:

>$('#container').serialize()
"CRAFT_CSRF_TOKEN=8Gi9HJK-ECM8JtSxoo1p_BfD-rVykTak_UCjKeoX6hHSOGOeoHplfUWbv8QBoxmgUjl-LCTIoJcqoy1fJvxtZLuI6wlIxr0igtaUR0p3eecLBMsTwpFswGhUC3NqVfFH4vo9YNtG9LvAZ4ak2b9fQYrs-t1TDwMgeWaURj0CdvrjaZauUfUx964cL06BylL-gAyIP3DxqZSDqtXC54BYsDSZxP2i_yid5ZlZXrpe78HBBN-wtJ4x5YS8zppZ9M-ckMEnXv_GPKDJb25R03anabou6yjF_XMWZm2NwuXsCMkksYvnQeVVz8Vt0V-9J4EonU0C2e00JjM5ro-mZ5UrxWYJGEoTq8XyHJAUaxSfDl3YuoprfqKJFeHlrHF5TkyEajb4cvCoXaEJbD9FW2TDdoScC1K5csbfpC3A8u3oHCK_trGEIEhiQUxV5jdvMQKZiFG73CeiAZyXU1ovxoccvc5wuUNUw9CwspnxoKnvAfRV2I2L5o5HrJPNE2iVO5qQjkaP44DPecr876v0F4Go_dyHRCymglj2_CI6MKcgxRA%3D&action=plugins%2Fsave-plugin-settings&pluginHandle=standardsagent&redirect=settings%2Fplugins%2Fstandardsagent&settings%5BrefreshInterval%5D=3"

Looking at this decode, could question whether there should be a '/' before 'settings', but I can't get a manual hashed `<input>` to place where it would over-ride to try it.

The decoded path looks right, except it's missing the site's admin introducer. However, if I try that from the browser address bar, I get a 404 as expected, not the tearaway to Dashboard....

If it worked as the path seems to wish, it would be fine -- and that's what it still does on C2.

[** other speculation thought through and deleted **]

**Comment by brandonkelly** [comment]
There should not be a `/` (as noted above), but the value wasn't hashed, and if it was left to Craft’s base settings template, it would just be pointing to `settings/plugins`, not `settings/plugins/standardsagent`. So you must have a `redirect` param in there somewhere.

**Comment by narration-sd** [comment]
Ok, I got the noted above, just felt to ask.

Honestly, I don't have any refresh elements.  And when I put one in, the Craft-invented one dominated, as mentioned.

However, there is something tricky I originally did with a refresh event listener, due to the (re?-) naming conventions on the settings page in C2. Maybe that is going awry, and doesn't fit Craft 3 -- except it seems fine in a straight Craft 3 install. This one is the famous ancient-C2-converted.

I'll trace through things happening and in these versions, not immediately this evening, and get back to you. 

Thanks, Brandon.

**Comment by narration-sd** [comment]
Ok, Brandon, I've got this, and will close.

You've been correct, of course. It's not to do with converted site topologies, or anything else except that I did actually have something that modified the _redirect_ hidden input element. 

I think I missed this by searching 'refresh' as lined out above, in a big hurry at the moment, but also as it had some semantic meaning in my namings, their activities.

You can't over-ride this `<input>` by putting another in, as you suggested, but you can use JQuery to modify the one that's there, and I had done so, long ago to get the UX working in the first delivery. This caused the odd value you noted with that good serialize trick I will keep.

I had to use another trick learned at that time, to make this work now -- setting a JS var in the template, then running the JQuery snippet using it for value separately in an included js file. Because ordering, to have JQuery available at moment  of need, and because no parsing on the js files, so the Twig couldn't go there .

Fatto, as a very pretty and decent Italian woman used to come in and announce on a consult there, when she'd got a big thing done. Norah Jones also a big help in these wee hours; isn't it funny how sometimes they are so effective? 

I've done some of my best completion coding in such seasons of a night -- truth if smile. Quietness of the mind or something...maybe accounts for some of your hours...

There are some very nice things in here, if you like:  https://www.youtube.com/watch?v=nchSZswc21w

**Comment by brandonkelly** [comment]
Glad you got it sorted!

**Comment by narration-sd** [comment]
Me too :)

**Comment by totov** [comment]
Adding a redirect input field to a plugin settings form now adds in the `settings` namespace to the `name` attribute, so it doesn't work.

For example, in `pluginname/src/templates/settings.twig`:

`{{ redirectInput('test') }}`

Produces:

`<input type="hidden" name="settings[redirect]" value="9e1f7203d076614e5ba75c3bcf4ad3e2da35f46217a3140a21e4122c00fbb5a9test">`

Any way around this so I can have a custom redirect when the user updates the settings?

**Comment by brandonkelly** [comment]
You could manually redirect the request from your plugin’s `afterSaveSettings()` method:

```php
use craft\helpers\UrlHelper;

public function afterSaveSettings()
{
    parent::afterSaveSettings();
    Craft::$app->response
        ->redirect(UrlHelper::url('test'))
        ->send();
}
```
