### ISSUE TITLE
Live Preview: Use Debounce instead of Throttle for page refresh

### ISSUE THREAD

**Issue by steveooo9** [craftcms/cms#1897]
### Description
When using Live Preview and typing, the preview refreshes too often. Makes browser and everything slow. I think it uses throttle. It would be better if using debounce.

**Comment by brandonkelly** [comment]
It doesn't use either, and neither would really work for Live Preview, since if there's any significant JS stuff going on, it's happening within the iframe – not something Live Preview has control over.

**Comment by steveooo9** [comment]
@brandonkelly Okay. Good to know! I opened this because I feel that using Live Preview has some very big performance issues. When using and building a page with Live Preview, my very fast notebook is very active (on latest Chrome, latest macOS). Is there some room for performance optimization?

**Comment by brandonkelly** [comment]
Is there much JS stuff going on on your webpage? Maybe you can just disable that when it’s being rendered for LP:

```twig
{% if not craft.request.isLivePreview %}
    <script ...></script>
{% endif %}
```

**Comment by steveooo9** [comment]
@brandonkelly Hmm. Thanks for that. I am using this, but maybe it a lot of JavaScript... Is it a smooth way of content creation for you? Maybe my website with lots of JS is the problem..

**Comment by brandonkelly** [comment]
> Maybe my website with lots of JS is the problem..

That’s what I’m saying – you may have better luck if you disable your JS scripts for Live Preview requests.
