### ISSUE TITLE
Return URL incorrectly relative to `cpTrigger` on site -> CP login

### ISSUE THREAD

**Issue by msbit** [craftcms/cms#1901]
### Description

When visiting a controller endpoint on site that is marked as requiring authentication:

`http://site.name/privileged`

without being logged in, then manually visiting the CP login page:

`http://site.name/{cpTrigger}/login`

and logging in successfully, the redirect to the original URL becomes relative to `cpTrigger`, e.g.:

`http://site.name/{cpTrigger}/privileged`

My expectation would be that after login the redirect would be to the original URL:

`http://site.name/privileged`

### Steps to reproduce

1. Visit `http://site.name/privileged`
2. Observe redirect to `http://site.name/{loginPath}`
3. Visit `http://site.name/{cpTrigger}/login`
4. Log in successfully as admin
5. Observe redirect to `http://site.name/{cpTrigger}/privileged`

### Additional info

- Craft version: 2.6.2988
- PHP version: 7.0.18-0ubuntu0.16.04.1

**Comment by brandonkelly** [comment]
Worth noting this only occurs if you access the CP login page directly. Visiting the CP trigger without appending `/login` will override the return URL, taking you to the CP dashboard after logging in.

**Comment by msbit** [comment]
Thanks @brandonkelly! I had noticed that it only occurred going directly to `/cpTrigger/login`, but as I was swapping between admin and non-admin users in testing, the the CP login had become an autocomplete URL for the browser, so I'd end up hitting it directly quite frequently :)
