### ISSUE TITLE
Delete user modal keeps loading endlessly

### ISSUE THREAD

**Issue by hiasl** [craftcms/cms#1903]
### Description

When you delete a user and want to reassign the content to another user, the modal loads endlessly.

### Steps to reproduce
see above

### Additional info
PHP version	7.1.7-1+ubuntu16.04.1+deb.sury.org+1
Database driver & version	MySQL 5.7.19-0ubuntu0.16.04.1
Image driver & version	Imagick 3.4.3, ImageMagick 6.8.9-9
Craft edition & version	Craft Pro 3.0.0-beta.22

**Comment by brandonkelly** [comment]
FFR please post one bug per GitHub issue.

> When a user is created and no user group is assigned (because none exists), you get an exception

That one was already fixed in Beta 23, so I’m going to remove it and focus this GH issue on the second one…

**Comment by brandonkelly** [comment]
Just tested and wasn’t able to reproduce the modal issue. Can you try updating to the latest version and see if you’re still having the issue?

**Comment by hiasl** [comment]
ok. I'll try, but I need Beta 24  :-)
