### ISSUE TITLE
Empty string pageTrigger value breaks CP settings section

### ISSUE THREAD

**Issue by evanwarner** [craftcms/cms#1914]
### Description
If I set the `pageTrigger` config to an empty string (in order to have simple pagination URLs like `section/2`), all the **content** settings sections in the CP are broken:

1. I cannot view individual field groups. Selecting one still shows the full field list and doesn't filter.
1. Trying to edit any field gives a "Page not found" error.
1. I cannot edit any section. I can view the sections list but clicking a title does nothing.
1. I cannot edit any entry types. I can see the lists of entry types but clicking one does nothing.
1. Trying to view/edit an asset sources gives a "Page not found" error.
1. I cannot edit any global sets. I can see the list of sets, but clicking one does nothing.
1. I cannot edit any category groups. I can see the list of groups, but clicking one does nothing.
1. I cannot edit any tag groups. I can see the list of groups, but clicking one does nothing.
1. (I don't have any locales to test)

All other settings seem to be unaffected.

### Steps to reproduce

1. Set the `pageTrigger` config to `''` (empty string)
2. Interact with the various content settings in Craft

### Additional info

- Craft version: 2.6.2988
- PHP version: 5.5.38
- Database driver & version: MySQL 5.7.11
- Plugins & versions: Cookies 1.0.4, CP Sortable Custom Columns 1.1.2, Freeform 1.5.1, Incognito Field 1.0.1, Neo 1.4.1, Page Redirects 1.0.19, Reasons 1.0.10, Redactor Extras 1.3.2, Sitemap v1.0.0-alpha.4, Weather 1.0

**Comment by brandonkelly** [comment]
Yeah setting to an empty string is not supported.

If you really want to pull it off, you could leave `pageTrigger` set to `'p'`, and then define some redirects in your web server config that bridge the gap. For example if you’re using Apache, you could add this to your `.htaccess` file, before the general-purpose `index.php` redirect that Craft provides:

```
RewriteRule ^(section)/(\d+)/?$ index.php?p=$1/p/$2 [QSA,L]
```
