### ISSUE TITLE
Support for 2FA-Auth

### ISSUE THREAD

**Issue by MDXDave** [craftcms/cms#1916]
How about 2FA support on login page? (Yubico, Google authenticator etc.)

**Comment by takobell** [comment]
Closing this as a dupe of https://github.com/craftcms/cms/issues/1471. Feel free to add additional thoughts/comments over there.

**Comment by brandonkelly** [comment]
Could be argued that 2FA should be an option in core, without requiring a plugin that provides a custom login form.

**Comment by MDXDave** [comment]
Yes, the intention was, to support 2FA on login without any external plugin.

**Comment by roelvanhintum** [comment]
Right now i'm refactoring our 2FA plugin for Craft 3 (it was written for Craft 2). I'll give an update when it's done. https://github.com/born05/craft-twofactorauthentication

**Comment by roelvanhintum** [comment]
@MDXDave the Craft 3 version of our 2FA plugin is in beta.
https://github.com/born05/craft-twofactorauthentication

**Comment by XhmikosR** [comment]
I'd also like to see this in core. 2FA is a mandatory precaution these days :)

**Comment by stevenjwright** [comment]
@brandonkelly Is there any movement on this? Just wondering the likelihood of it ending up being pushed back again? Cheers!

**Comment by brandonkelly** [comment]
@stevenjwright I can’t promise exactly when we’ll get to it, but we have our own internal needs for it so it’ll happen sooner than later.

**Comment by zavelin** [comment]
Hello there - any update on when this will be added? will it be in 4.0?

**Comment by brandonkelly** [comment]
That’s the current plan.

**Comment by roelvanhintum** [comment]
@brandonkelly i'm both happy and sad to read this. ;)

**Comment by Mosnar** [comment]
Since this is on the menu right now, I wanted to request that the two-factor methods supported include TOTP (e.g. Authy and Google Authenticator) and FIDO U2F (e.g. [Yubikey](https://www.yubico.com/), [Titan](https://store.google.com/us/product/titan_security_key?hl=en-US))

Related: [Browser support for FIDO U2F API](https://caniuse.com/u2f)

**Comment by andris-sevcenko** [comment]
@Mosnar Not to re-iterate, but that is the current plan :)
