### ISSUE TITLE
current dev-develop w/yii2-queue fails to update; crashes CP

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1918]
### Description
Log attached; can't see that the craft_queue-creating migration ran, though it is present in the folder. 
Stack trace locks out of CP; due to craft_queue table not present
Also, site continues to run; no indication of db change needed.

### Steps to reproduce

1. Have days-recent dev-develop
2. composer update, which does load  yii2 parts
3. attempt to enter CP; stack trace.

### Additional info

- Craft version: current dev-develop
- PHP version: 7.1.3
- Database driver & version:
- Plugins & versions:

**Comment by narration-sd** [comment]
[web.log.zip](https://github.com/craftcms/cms/files/1223985/web.log.zip)

Here's that log zipped

**Comment by narration-sd** [comment]
hmm - faster than a speeding bullet, or that my composer update can find it yet...

I'll give it some minutes, dinner to cook :)

Thanks, Brandon

**Comment by brandonkelly** [comment]
Forgot to update the schema version :)

**Comment by narration-sd** [comment]
composer updated; Craft update now works; site does.

My tasks don't -- must have  misunderstood about the old way remaining in parallel with new queue. Will look into this in detail later. Thanks still :)

**Comment by brandonkelly** [comment]
If you have custom tasks, those will need to be updated to be queue jobs.

- They should extend `craft\queue\BaseJob`
- Replace the `getTotalSteps()` and `runStep()` methods with an `execute()` method, which takes a `$queue` argument.

For long-running jobs, you can update the queue with the job's progress as it's working by calling `$this->setProgress()`.

```php
// 0.5 == 50% progress
$this->setProgress($queue, 0.5);
```

(I’ll write more thorough documentation for the plugin update guide when we release Beta 24.)

**Comment by brandonkelly** [comment]
Also, how you add a job to the queue has changed. The Tasks service has gone away, so now you would do:

```php
Craft::$app->queue->push(new MyJobClass());
```

or if your job has some public settings properties you want to set,

```php
Craft::$app->queue->push(new MyJobClass([
    'foo' => 'bar',
]));
```

**Comment by narration-sd** [comment]
Brandon, thanks - def will make upgrade more painless.

I'd figured out what you'd done, falling asleep last night after scanning some code. I'm thinking you'll help reliability, though open question until I dig in about whether I need my restart/ornotkill code still. 

For issues like Fred @sjelfull is dealing with, at the least you've got the platform in there for us, and we can invent other queues that operate without the UI->php overhead, etc., to need -- cheers.
