### ISSUE TITLE
Model field returning wrong localized data after populateModel

### ISSUE THREAD

**Issue by thomasJoei** [craftcms/cms#1922]
### Description
Model created from `populateModel`  return default locale data when requesting a localized field even if `populateModel` is given right localized data.

### Steps to reproduce
```
$criteria = craft()->elements->getCriteria(ElementType::Entry);
$criteria->section = $this->initiativesHandle;
$criteria->id = $initiativeId;
$dbCommand = craft()->elements->buildElementsQuery($criteria); // select the current locale
$dbCommand = $this->joinSupporterCount($dbCommand);
$initiative = BuildQueryModel::populateModel($dbCommand->queryRow()); // query the right localized data, populateModel is the one inherited from BaseElementModel.

echo($initiative->field_shortDescription); / data in the right locale
echo($initiative->shortDescription);die; // data in the default locale
```
I also tested it with `EntryModel::populateModel` which my `BuildQueryModel` inherit, to be sure it wasn't my class fault.
My workaround was to override the `BaseElementMode::populateModel` method in my `BuildQueryModel` class. Apparently setting the locale afterward do the trick: 
```
public static function populateModel($value = null)
  {
    $model = parent::populateModel($value);
    $model->locale = craft()->language;

    return $model;
  }
```
But I suppose the `locale` attribute should be transferred to the model when populating it no ?
Thanks

### Additional info

- Craft version: 2.6.2988
- PHP version: 7.0.18-0ubuntu0.16.04.1
- Database driver & version: mysql, mysqlnd 5.0.12-dev
- Plugins & versions:

**Comment by brandonkelly** [comment]
The locale is never actually selected by the query, since we already know the locale each element will be. (It’s not possible to query for elements in more than one locale at a time.) So it’s expected that you would have to manually set the locale on your BaseQueryModel class manually.
