### ISSUE TITLE
Fields of sections that have default site status switched off do not get validated

### ISSUE THREAD

**Issue by Luuc15** [craftcms/cms#1924]
### Description
When you have a section with type channel or structure, and the default status of a site for that section is switched of, then fields that require validation for the entries created in that section, won't get validated. (Tested with number field)

### Steps to reproduce

1. Create a new section with type "channel", and a new field with type "Number".
2. Switch off the "default status" of the sites under the site settings of this section (i had two sites defined) and save the entry
3. At the entry layout add the "numbers" field
4. Now create a new entry in this section
5. Fill in some text (not a number) in the number field and click on save
6. You will not get any validation error and the entry will just be saved, converting the text to a zero.
7. When you edit the entry again and set the switch for the current side (top right column) to be switched on (publish the entry), then validation will run correctly and you will get an error. 

### Additional info

- Craft version:
- PHP version:  7.0.15
- Database driver & version: MySQL 5.5.41-MariaDB
- Plugins & versions: none

**Comment by Luuc15** [comment]
The bug also happens if you just switch of the publish state of an existing entry.

**Comment by brandonkelly** [comment]
This is expected behavior. Custom field validation only occurs for enabled elements.
