### ISSUE TITLE
includecss  and caching

### ISSUE THREAD

**Issue by andresnijder** [craftcms/cms#1928]
### Description

We tried to use the tag as described here: https://craftcms.com/docs/templating/includecss During the first run, the css is included in the head, after the second run, it is not included. 

### Steps to reproduce

1. add includeCss tag as described 
2. render the page, check the existence of the style in the header
3. refresh the page and notice that the style block is not included anymore

### Additional info

- Craft version: 2.6.2987 (Pro)
- PHP version: 7.1.7
- Database driver & version: MySQL 5.5.5-10.1.25-MariaDB
- Plugins & versions: 
    - Element API 1.2.1
    - Formerly 1.5.1
    - Navee 1.1.1
    - Neo 1.4.0
    - Patrol 1.4.2
    - Video Embed 1.0.1

**Comment by brandonkelly** [comment]
That is expected behavior, since the `<style>` tag is added to the `<head>`, not directly where the `{% includecss %}` tag is placed – so it doesn’t get cached by `{% cache %}` tags.

You should probably just move your `{% includecss %}` tag outside of your `{% cache %}` tags.
