### ISSUE TITLE
craft.request.isAjax return false when using XHR

### ISSUE THREAD

**Issue by steveooo9** [craftcms/cms#1929]
### Description
I am using Infinite Scroll (infinite-scroll.com) for replacing the normal pagination and loading works, but the plugins loads the full page (via XHR) instead of a slimmed down one.
I am using this code:
```{% extends '_layout' ~ (craft.request.isAjax ? '-ajax') %}```

### Steps to reproduce

1. Load something with AJAX/XHR
2. Check in template for it via `craft.request.isAjax`

### Additional info

- Craft version: 2.6.2988
- PHP version: 7.1
- Database driver & version:
- Plugins & versions:

**Comment by takobell** [comment]
You'll need to set the `X-Requested-With` header to `XMLHttpRequest` whenever you're making the AJAX call since that's what [`isAjaxRequest`](https://github.com/yiisoft/yii/blob/1.1.19/framework/web/CHttpRequest.php#L679) is looking for.

**Comment by steveooo9** [comment]
@takobell Okay. Thanks! Good to know! Maybe considering mentioning this in the docs? Because X-Requested-With isn't a standardized header format. Every framework uses another thing, so maybe it's good to mention it somewhere..

**Comment by brandonkelly** [comment]
@steveooo9 Setting an `X-Requested-With` header on Ajax requests is pretty standard practice – that’s what jQuery does anyway.

For Craft 3 we’ve switched it up a bit though. Generally Craft stops caring about whether it’s an Ajax request or not, and instead checks to see if the `Accept` header includes `application/json`, before returning a JSON response.
