### ISSUE TITLE
UserController is missing craft\events\UserEvent usage

### ISSUE THREAD

**Issue by Luuc15** [craftcms/cms#1930]
### Description
When creating a new user with an automatic "set password" mail,
if clicked on the link in the mail there will now be an error.

`Class 'craft\controllers\UserEvent' not found`

### Solution
Add `use craft\events\UserEvent;` at the top of the userController file (src/controllers/UsersController.php)

### Steps to reproduce

1. Create a user with an automatic set password mail
2. Click the link in the email and see the error

### Additional info

- Craft version: Craft Pro 3.0.0-beta.24
- PHP version: 7.0.19
- Database driver & version: MySQL 5.5.41-MariaDB
- Plugins & versions: None

**Comment by takobell** [comment]
Thanks, @Luuc15.  Already resolved in https://github.com/craftcms/cms/commit/6de6895e6b6b88b15e7ff1a6ef62b98c1173efbd for the next release.
