### ISSUE TITLE
Deprecation Error in Tags Fieldtype Template

### ISSUE THREAD

**Issue by putyourlightson** [craftcms/cms#1932]
### Description

I'm seeing a deprecation error as follows:

`Looping through element queries directly has been deprecated. Use the all() function to fetch the query results before looping over them. /vendor/craftcms/cms/src/templates/_components/fieldtypes/Tags/input.html:13`

### Additional info

- Craft version: 3.0.0 beta 24
- PHP version: 7.1.1

**Comment by crazyx13th** [comment]
I have the same issue and only using element-api with no loop from my site, why you close it?
thanks!

**Comment by takobell** [comment]
@crazyx13th because it was resolved in this commit: https://github.com/craftcms/cms/commit/060ddfabca6ba26754115b73e688a90791a799d4

**Comment by crazyx13th** [comment]
but I have the newest one :-/
![grafik](https://user-images.githubusercontent.com/8912561/30433039-b4a2cb38-9963-11e7-8a78-85c03aa88fbc.png)

**Comment by crazyx13th** [comment]
> Steps leading up to the deprecation error:
15	Deprecation error: Looping through element queries directly has been deprecated. Use the all() function to fetch the query results before looping over them.
Called from /.../vendor/craftcms/cms/src/elements/db/ElementQuery.php:398
14	craft\elements\db\MatrixBlockQuery::getIterator()
Called from /.../vendor/craftcms/cms/src/fields/Matrix.php:464
13	craft\fields\Matrix::getSearchKeywords(craft\elements\db\MatrixBlockQuery, craft\elements\Entry)
Called from /.../vendor/craftcms/cms/src/services/Content.php:242
12	craft\services\Content::_updateSearchIndexes(craft\elements\Entry, craft\models\FieldLayout)
Called from /.../vendor/craftcms/cms/src/services/Content.php:205
11	craft\services\Content::saveContent(craft\elements\Entry)
Called from /.../vendor/craftcms/cms/src/services/Elements.php:473
10	craft\services\Elements::saveElement(craft\elements\Entry)
Called from /.../vendor/craftcms/cms/src/controllers/EntriesController.php:490
9	craft\controllers\EntriesController::actionSaveEntry()
8	call_user_func_array([craft\controllers\EntriesController, "actionSaveEntry"], [])
Called from /.../vendor/yiisoft/yii2/base/InlineAction.php:57
7	yii\base\InlineAction::runWithParams(["p" => "admin/entries/apiContact/954-api-contact/cblub"])
Called from /.../vendor/yiisoft/yii2/base/Controller.php:156
6	craft\controllers\EntriesController::runAction("save-entry", ["p" => "admin/entries/apiContact/954-api-contact/cblub"])
Called from /.../vendor/yiisoft/yii2/base/Module.php:523
5	craft\web\Application::runAction("entries/save-entry", ["p" => "admin/entries/apiContact/954-api-contact/cblub"])
Called from /.../vendor/craftcms/cms/src/web/Application.php:241
4	craft\web\Application::runAction("entries/save-entry", ["p" => "admin/entries/apiContact/954-api-contact/cblub"])
Called from /.../vendor/craftcms/cms/src/web/Application.php:385
3	craft\web\Application::_processActionRequest(craft\web\Request)
Called from /.../vendor/craftcms/cms/src/web/Application.php:201
2	craft\web\Application::handleRequest(craft\web\Request)
Called from /.../vendor/yiisoft/yii2/base/Application.php:380
1	craft\web\Application::run()
Called from /.../web/index.php:21

**Comment by takobell** [comment]
@crazyx13th That looks like a different issue.  Can you create a new issue on Github along with that stack trace so we can track it?

**Comment by crazyx13th** [comment]
sure, thx !
https://github.com/craftcms/cms/issues/1983
