### ISSUE TITLE
craft\volumes\MissingVolume contains 14 abstract methods

### ISSUE THREAD

**Issue by nateiler** [craftcms/cms#1934]
Internal Server Error

Class craft\volumes\MissingVolume contains 14 abstract methods and must therefore be declared abstract or implement the remaining methods (craft\base\VolumeInterface::getFileList, craft\base\VolumeInterface::getFileMetadata, craft\base\VolumeInterface::createFileByStream, ...)

### Steps to reproduce
1. Rename a volume type to something invalid.

### Additional info
- Craft version: 3.0.0-beta.25
- PHP version: 7

**Comment by brandonkelly** [comment]
Thanks!
