### ISSUE TITLE
PDF is corrupted after upload

### ISSUE THREAD

**Issue by buesing** [craftcms/cms#1938]
### Description

After uploading a 70-page 24MB PDF, the file that's actually saved on the server is only 1MB and has only one page, which is a pixellated color negative copy of the last page. I'm not sure if this is a Craft bug, but maybe you have an idea as to what causes this? I would have expected the CMS to not touch uploaded files at all, except for image transforms.

### Steps to reproduce

1. Upload large PDF
2. Check the uploaded file in the assets folder

### Additional info

PHP version: 7.0.22-0ubuntu0.16.04.1
Database driver & version: MySQL 5.7.19-0ubuntu0.16.04.1
Image driver & version: Imagick 3.4.0RC6, ImageMagick 6.8.9-9
Craft edition & version: Craft Client 3.0.0-beta.22
Yii version: 2.0.12
Twig version: 2.3.2
Guzzle version: 6.2.1
Imagine version: 0.7-dev

**Comment by brandonkelly** [comment]
@andris-sevcenko Sounds like PDF is being treated as an image format.

**Comment by amandasaffer** [comment]
I have a similar error, but my "corrupted" PDF is simply a 1-page gray rectangle. I'm uploading 5-15 page PDFs with a lot of text. My limits are as follows, so I should be fine:

- upload_max_filesize: 256M
- post_max_size 256M
- memory_limit 512M

Immediately after upload, I can click View Asset in the admin panel and see the PDF just fine:
<img width="1439" alt="screen shot 2017-10-08 at 3 00 19 pm" src="https://user-images.githubusercontent.com/7903971/31320898-749bcac4-ac39-11e7-8303-5bcd4cd06b3b.png">

However, after a number of seconds (or minutes, in some cases, but this example just took seconds), when I click View Asset, I am greeted with a gray PDF. Downloading the file via the Admin panel or via SCP confirms the PDF is saved as a gray page.
<img width="1440" alt="screen shot 2017-10-08 at 3 00 26 pm" src="https://user-images.githubusercontent.com/7903971/31320900-826c8a76-ac39-11e7-9529-672f7fe2703c.png">


This does not happen on smaller PDFs (under 300MiB), so what gives? Are the limits/configs above not enough?

**Comment by andris-sevcenko** [comment]
Should not be happening for PDFs anymore. Existing PDFs will have to be re-uploaded, though.
