### ISSUE TITLE
ElementRelationParamParser adding non-integer numeric fields to SQL query on integer id fields causing db error

### ISSUE THREAD

**Issue by freelancediary** [craftcms/cms#1939]
### Description
I came across this when adding "longitude" and "latitude" fields to a client's contact form to use for a google map. 

On the contact form I have a "Team" section which shows entries related to the (single) contact form from this channel. Part of the twig template uses the `length` filter to determine the number of team members. Before adding long/lat fields this was all working fine.

After adding the long/lat values as 2 additional simple text fields to the contact page field layout and entering long/lat values as decimal numbers this page broke with the following error:

````
Database Exception – yii\db\Exception

SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "51.507"
The SQL being executed was: SELECT COUNT(*)
FROM (SELECT "elements"."id" AS "elementsId", "elements_sites"."id" AS "elementsSitesId", "content"."id" AS "contentId"
FROM "elements" "elements"
INNER JOIN "entries" "entries" ON "entries"."id" = "elements"."id"
INNER JOIN "elements_sites" "elements_sites" ON "elements_sites"."elementId" = "elements"."id"
INNER JOIN "content" "content" ON "content"."elementId" = "elements"."id"
LEFT JOIN "structureelements" "structureelements" ON "structureelements"."elementId" = "elements"."id"
WHERE (("entries"."sectionId" = '13')) AND ("elements_sites"."siteId"=3) AND ("content"."siteId"=3) AND ("elements"."archived"='0') AND (((("elements"."enabled"='1') AND ("elements_sites"."enabled"='1')) AND ("entries"."postDate" <= '2017-08-22 19:55:26') AND (("entries"."expiryDate" IS NULL) OR ("entries"."expiryDate" > '2017-08-22 19:55:26')))) AND ("elements_sites"."enabled"='1') AND (("elements"."id" IN (SELECT "sources1"."targetId"
FROM "relations" "sources1"
WHERE ("sources1"."sourceId" IN (9, 9, 1, 11, 9, 38, 3, '51.507', '0.127', 32, 31)) AND ("sources1"."fieldId"=70))) OR ("elements"."id" IN (SELECT "targets1"."sourceId"
FROM "relations" "targets1"
WHERE ("targets1"."targetId" IN (9, 9, 1, 11, 9, 38, 3, '51.507', '0.127', 32, 31)) AND ("targets1"."fieldId"=70))))) "subquery"
INNER JOIN "entries" "entries" ON "entries"."id" = "subquery"."elementsId"
INNER JOIN "elements" "elements" ON "elements"."id" = "subquery"."elementsId"
INNER JOIN "elements_sites" "elements_sites" ON "elements_sites"."id" = "subquery"."elementsSitesId"
INNER JOIN "content" "content" ON "content"."id" = "subquery"."contentId"
LEFT JOIN "structureelements" "structureelements" ON "structureelements"."elementId" = "subquery"."elementsId"
Error Info: Array
(
    [0] => 22P02
    [1] => 7
    [2] => ERROR:  invalid input syntax for integer: "51.507"
)
````

Upon digging into the source I found that the problem seems to come from:

1. The `length` filter triggers a SQL COUNT query
2. The `relatedTo` part of my `craft.entries` template is parsed by the class `ElementRelationParamParser`
3. In `ElementRelationParamParser`, the private `_subparse` method on line 140 loops over elements (properties) of the object and builds the `$relElementIds` array of potential id matches for the related objects.
4. In `ElementRelationParamParser` on line 189 the check is `if (is_numeric($element)) {...` This is the line that is causing the problem. As `is_numeric` returns true for a decimal number in string format (in my case, "51.507" and "0.127"), these are being added to the `$relElementIds` array and hence to the `WHERE ("sources1"."sourceId" IN (..)` part of the query - causing the db error.

To fix this we could change `is_numeric` to `is_int`, but I'm not so familiar with Craft to know if that will break anything else. Especially as `is_int` will return false for an integer cast as a string (eg, `is_int("42") ~ false`). 

Or check like `is_numeric($element) && intval($element) == $element` (note double equals not triple).

Or change line 190 to `$relElementIds[] = intval($element)`.

All these suggested fixes seem to work fine for me when I hack the file directly, but I've not done any proper testing. I'm happy to PR this but would like to hear any thoughts on the best way to do it first from someone with a bit more experience working with Craft!

### Steps to reproduce

1. Create an entries field
2. Create a basic text field
3. Add these 2 fields to the field layout for an entry
4. Edit this entry
5. Pick a couple of entries for the entries field 
6. Enter a decimal number into the text field
7. Save the entry
8. In the template for the entry put `{{ entry.myEntries | length }}`
9. Load the frontend view
10. Observe the database error

### Additional info

- Craft version: 3.0.0-beta.23
- PHP version: 7.1.8
- Database driver & version: PostgreSQL 9.5
- Plugins & versions: ~

**Comment by brandonkelly** [comment]
Can you post your actual `craft.entries` template code?

**Comment by freelancediary** [comment]
Of course:

````
{% set
    coreTeamMembers = craft.entries({
        section: 'teamMembers',
        relatedTo: {element: entry, field: 'coreTeamMembers'},
        limit: null,
        with: [
            ['memberImage', {withTransforms: ['memberImage']}],
        ]
    }) 
%}
````
