### ISSUE TITLE
Element padding in relationship fields

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#1941]
### Description

The element items in relationship fields have unnecessary padding when referencing from structural element groups, even if only one element is allowed. It would be nice if the first level would be aligned with a “normal” relationship field’s elements. Or if it wouldn’t happen when the field is restricted to a single element.

In this screenshot the first field is an Entries field where you can pick elements from a Structure, the second one a Categories field. Both fields are restricted to one element.

<img width="692" alt="bildschirmfoto 2017-08-23 um 12 33 01" src="https://user-images.githubusercontent.com/7516543/29612116-6d80a49c-8800-11e7-8410-34d141891474.png">

### Additional info

- Craft version: 2.6.2988

**Comment by carlcs** [comment]
Don’t know when, but this is fixed now.

**Comment by brandonkelly** [comment]
Thanks! Sorry, not sure why this fell through the cracks.
