### ISSUE TITLE
Allow overriding of Redactor UI texts

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#1942]
### Description

It would be nice if Craft would allow to override Redactor UI texts using static translations.

### Additional info

- Craft version: 2.6.2988

**Comment by brandonkelly** [comment]
If we did this, it would need to be in Craft 3, and we’d give the messages a `redactor` translation category.

**Comment by carlcs** [comment]
Alright, let’s continue this issue in https://github.com/craftcms/redactor/issues/3
