### ISSUE TITLE
Unable to save channel entries after upgrade to build 26

### ISSUE THREAD

**Issue by acehead** [craftcms/cms#1943]
### Description
The same as in #1935 

### Steps to reproduce

1. Do the same as in #1935 
2. following error occurs:
![craft-beta26](https://user-images.githubusercontent.com/2222878/29616084-eacfefbc-8818-11e7-800f-3057b16e6eae.png)

### Additional info

Craft version: Craft Pro 3.0.0-beta.23
PHP version: PHP/7.1.1
Database driver & version: PostgreSQL 9.6.2

**Comment by brandonkelly** [comment]
This is not related to #1935, though it may seem similar at first glance.

The Task APIs were removed in [Beta 24](https://github.com/craftcms/cms/blob/develop/CHANGELOG-v3.md#300-beta24---2017-08-15). Your `nginxclustercachemanager` plugin will need to be updated to use the Queue APIs instead.
