### ISSUE TITLE
Make EventTagFinder/EventTagAdder configurable 

### ISSUE THREAD

**Issue by swey** [craftcms/cms#1944]
Craft's Twig `Extension` adds the two `NodeVisitors` `EventTagFinder` and `EventTagAdder`, which inject code in the markup of the templates. By using the functions `head()/beginBody()/endBody()` you can control, where the scripts and styles are rendered, but you have no possibility to disable that rendering and the injections.

No plugin should ever be allowed to add scripts or styles to my page if I don't want it. I want to keep full control of the rendered pages.

**Comment by swey** [comment]
As workaround for now I had to create a plugin with that (dirty) code:
```
// Workaround for disabling unwanted template injections
        if (!Craft::$app->getRequest()->isCpRequest) {
            Event::on(View::class, View::EVENT_BEFORE_RENDER_TEMPLATE, function(TemplateEvent $event) {
                Craft::$app->getView()->assetBundles = [];
                Craft::$app->getView()->getAssetManager()->bundles = [];
            });
        }
```

**Comment by brandonkelly** [comment]
Meh… if your template or a plugin calls `registerCss()`, etc., I think it would be even less expected that the function would have no effect.

Those node visitors will only add the functions if they can’t already be found in the template. So if you really want to avoid it you could throw this in your layout template:

```twig
{% set junk %}
    {{ head() }}
    {{ beginBody() }}
    {{ endBody() }}
{% endset %}
```

(and just never output the `junk` variable.)

**Comment by swey** [comment]
Ok, at least that's an easy workaround for everyone
