### ISSUE TITLE
Finish job on Queue when progress is 100%

### ISSUE THREAD

**Issue by andrelopez** [craftcms/cms#1945]
### Description
After a long job on queue (30 min), runned via Cli command (_php craft queue/run_) it finish correctly but the progress stuck on 100%

![queue stuck](https://user-images.githubusercontent.com/875476/29633524-889a5566-8814-11e7-85b2-a23cd1f67307.png)
![queue](https://user-images.githubusercontent.com/875476/29633672-0d8d1ed4-8815-11e7-9bc5-e95833658ec4.png)

### Steps to reproduce

1. Craft::$app->queue->push(new LongJob());
2. execute php craft queue/run

### Additional info

- Craft version: Craft CMS 3.0.0-beta.26
- PHP version: 7.0
- Database driver & version:  MYSQL - Linux - ver 14.14
- Plugins & versions: none

**Comment by brandonkelly** [comment]
The job progress is purely for giving users feedback; even if a job says its progress is 100%, the queue won’t take that as a confirmation that the job is done. So most likely after the job called `setProgress(1)`, some fatal error occurred. You can try checking `storage/logs/phperrors.log` for hints.

**Comment by andrelopez** [comment]
I got it. How could the user cancel or delete the job in the CP when this scenario happens?

**Comment by brandonkelly** [comment]
The CP should eventually recognize the task as failed. If that’s not happening, can you please send a DB backup to support@craftcms.com so we can take a look?

**Comment by andrelopez** [comment]
You're right Brandon, after a while the task disappear. 👍

**Comment by ctmaloney** [comment]
For future me and anyone else I'm fairly sure this is caused by the mysql wait timeout setting being less than the length of the task
