### ISSUE TITLE
Element saving logic in controller (e.g. EntryController/CategoriesController) 

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#1946]
It seems like element controllers contain logic that would make more sense (in my thinking anyway) as part of a service (`craft\services\Elements::saveElement`).

https://github.com/craftcms/cms/blob/develop/src/controllers/EntriesController.php#L445-L489
https://github.com/craftcms/cms/blob/develop/src/controllers/CategoriesController.php#L428

For example, the permission enforcement is all done in the controller, not in `craft\services\Elements\saveElement`. This makes it difficult if you want to leverage that logic when calling `saveElement` (which seems like you would, or at least I do in this case).

My use case is a plugin with it's own `saveThing` controller, which in turn saves an entry. 

Because I need the logic present in the `saveEntry` controller, I'm forced to call `craft()->runController('entries/saveEntry')`, when I really want to just call `craft()->entries->saveEntry($entry)`***

*** Craft 2 example, sorry :)

**Comment by timkelty** [comment]
I'm guessing the reasoning for having that stuff in the controller is it deals with `$currentUser`, which you'd want separate from `saveElement`.

So perhaps what I'm wanting is some publicly accessible method to do all the permission/checking enforcement.

Not sure why the revisions stuff wouldn't be in the service though…https://github.com/craftcms/cms/blob/develop/src/controllers/EntriesController.php#L480-L487

**Comment by brandonkelly** [comment]
Permission enforcement always goes in the controllers, not the services. Although I suppose there’s no reason why the bulk of the logic couldn’t be moved to helper methods. We just don’t have an internal need for it, so not something we’ve thought much about. Feel free to submit a PR if you want.

**Comment by timkelty** [comment]
👍
