### ISSUE TITLE
Pushing job to queue fails because job column is restricted to 'BLOB' size

### ISSUE THREAD

**Issue by phoob** [craftcms/cms#1948]
### Description

When trying to push a job where I use an element (Entry) to the new queue, I get the following error:
```
PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'job' at row 1 in /dev/craft/vendor/yiisoft/yii2/db/Command.php:842
```

It seems the likely cause is that the `job`column in the `queue`table is set to `BLOB`. Changing it to `LONGTEXT` (as Laravel does it, according to @sjelfull on [slack](https://craftcms.slack.com/archives/C04UQS105/p1503573012000031)) seems to fix the issue.

- Craft version: Craft Pro 3.0.0-beta.26
- PHP version: 7.0.20
- Database driver & version: MySQL 5.5.5-10.2.6-MariaDB

**Comment by andris-sevcenko** [comment]
Disregard previous comment, mixed up the github issue numbers when making that.
