### ISSUE TITLE
JavaScript Error (runPendingTasks in Craft.js)

### ISSUE THREAD

**Issue by putyourlightson** [craftcms/cms#1951]
### Description

Seems that there are still multiple calls to the removed `runPendingTasks` function in the Craft.js file as I am seeing this error in the console:

```
Craft.js:2519 
Uncaught TypeError: Craft.cp.runPendingTasks is not a function
```

### Additional info

- Craft version: 3.0.0-beta.26

**Comment by phoob** [comment]
+1
