### ISSUE TITLE
Restoring Previous revisions not working for Singles

### ISSUE THREAD

**Issue by nmann4789** [craftcms/cms#1954]
### Description

All revisions to a Single appear in the dropdown, but when you select one and preview the revision the current revision is displayed. When you then select "Revert entry to this revision" the entry is still not reverted

### Steps to reproduce

1.  Choose Revision
2. Click "Revert entry to this revision"

### Additional info

- Craft version: Craft CMS 3.0.0-beta.26
- PHP version: 7.1.1
- Database driver & version: 5.6.35
- Plugins & versions:
  - Element API 2.4.2
  - Greenhouse 1.0.0 (My custom plugin)

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you please send a DB backup to support@craftcms.com and point us to the Single entry that you’re seeing this with?
