### ISSUE TITLE
Unable to upgrade from beta 24 to beta 26

### ISSUE THREAD

**Issue by andrelopez** [craftcms/cms#1955]
### Description
After I hit `composer update` and go to `craft3.dev/admin` and run the update an error message comes up:

> 
One of Craft CMS’s migrations failed.
TypeError: Argument 1 passed to craft\helpers\StringHelper::split() must be of the type string, array given, called in C:\MAMP\htdocs\craft3\vendor\craftcms\cms\src\helpers\MigrationHelper.php on line 93
> 
> Migration: craft\migrations\m150403_183908_migrations_table_changes
> 
> Output:
> 
> Exception: Argument 1 passed to craft\helpers\StringHelper::split() must be of the type string, array given, called in C:\MAMP\htdocs\craft3\vendor\craftcms\cms\src\helpers\MigrationHelper.php on line 93 (C:\MAMP\htdocs\craft3\vendor\craftcms\cms\src\helpers\StringHelper.php:522) #0 C:\MAMP\htdocs\craft3\vendor\craftcms\cms\src\helpers\MigrationHelper.php(93): craft\helpers\StringHelper::split(Array) #1 C:\MAMP\htdocs\craft3\vendor\craftcms\cms\src\helpers\MigrationHelper.php(118): craft\helpers\MigrationHelper::doesIndexExist('{{%migrations}}', Array, true) #2 C:\MAMP\htdocs\craft3\vendor\craftcms\cms\src\migrations\m150403_183908_migrations_table_changes.php(35): craft\helpers\MigrationHelper::dropIndexIfExists('{{%migrations}}', Array, true, Object(craft\migrations\m150403_183908_migrations_table_changes)) #3 C:\MAMP\htdocs\craft3\vendor\craftcms\cms\src\db\Migration.php(44): craft\migrations\m150403_183908_migrations_table_changes->safeUp() #4 C:\MAMP\htdocs\craft3\vendor\craftcms\cms\src\db\MigrationManager.php(250): craft\db\Migration->up(true) #5 C:\MAMP\htdocs\craft3\vendor\craftcms\cms\src\db\MigrationManager.php(166): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m150403_183908_migrations_table_changes)) #6 C:\MAMP\htdocs\craft3\vendor\craftcms\cms\src\services\Updates.php(488): craft\db\MigrationManager->up() #7 C:\MAMP\htdocs\craft3\vendor\craftcms\cms\src\controllers\UpdaterController.php(348): craft\services\Updates->runMigrations(Array) #8 [internal function]: craft\controllers\UpdaterController->actionMigrate() #9 C:\MAMP\htdocs\craft3\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array) #10 C:\MAMP\htdocs\craft3\vendor\yiisoft\yii2\base\Controller.php(156): yii\base\InlineAction->runWithParams(Array) #11 C:\MAMP\htdocs\craft3\vendor\yiisoft\yii2\base\Module.php(523): yii\base\Controller->runAction('migrate', Array) #12 C:\MAMP\htdocs\craft3\vendor\craftcms\cms\src\web\Application.php(241): yii\base\Module->runAction('updater/migrate', Array) #13 C:\MAMP\htdocs\craft3\vendor\craftcms\cms\src\web\Application.php(496): craft\web\Application->runAction('updater/migrate') #14 C:\MAMP\htdocs\craft3\vendor\craftcms\cms\src\web\Application.php(155): craft\web\Application->_processUpdateLogic(Object(craft\web\Request)) #15 C:\MAMP\htdocs\craft3\vendor\yiisoft\yii2\base\Application.php(380): craft\web\Application->handleRequest(Object(craft\web\Request)) #16 C:\MAMP\htdocs\craft3\web\index.php(21): yii\base\Application->run() #17 {main}

### Steps to reproduce

1. Upgrade from beta24 to current version
2.

### Additional info

- Craft version: Craft3 beta24
- PHP version: 7.0.0
- Database driver & version: mysql
- Plugins & versions: nope

**Comment by brandonkelly** [comment]
Fixed via 76702cb69efb71b8a92c7863fc29d9c620ac7333
