### ISSUE TITLE
Immediately rename new tabs when editing field layouts.

### ISSUE THREAD

**Issue by mijewe** [craftcms/cms#1956]
### Description

When creating a new tab for fields, I reckon it should ask you to name it immediately in a dialog. I never want a tab called 'tab 2' so it's just more clicks to rename afterwards.

### Steps to reproduce

1.
2.

### Additional info

- Craft version: 2.6.2988 (Pro)
- PHP version: 5.5.9-1ubuntu4.17
- Database driver & version: MySQL 5.5.49-0ubuntu0.14.04.1
- Plugins & versions: 
    - Contact Form 1.9.0
    - Imager 1.6.2
    - Json Transforms 1.0
    - Refresh String 1.0

**Comment by brandonkelly** [comment]
Finally got around to this, for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.12 is out now with that change ✨
