### ISSUE TITLE
Images are not loaded specifically into each site's web folder

### ISSUE THREAD

**Issue by hlldo** [craftcms/cms#1975]
### Description

Currently, I have 3 multisite setup in Craft 3 beta. When I uploaded an image to a site, it shows up as uploaded into all my sites in the dashboard. However, when I check my local folder inside the web folder for each site, the file is only uploaded to the original web folder and not into any of my other site's web folders.

### Steps to reproduce

1. Create new Volume in Assets
2. Base Url "/assets/general"
3. File System Path: "assets/general"
4. Upload image in site 2
5. No image appears in site 2's web folder 
6. Image only appear in site 1 web's folder

### Additional info

- Craft version: Craft 3 beta
- PHP version: 7.1.8
- Database driver & version: MySQL 5.7
- Plugins & versions:

**Comment by brandonkelly** [comment]
Asset volumes are global, not site-specific. So this is expected behavior.

Considering that, note that you should set your volumes’ Base URL and File System Path settings to absolute URLs/paths, as they will be referenced from different sites.
