### ISSUE TITLE
Error when adding an image field inside a matrix with Manage relations on a per-site basis checked

### ISSUE THREAD

**Issue by hlldo** [craftcms/cms#1987]
I get an error when I tried to add an image field within a matrix when the `Manage relations on a per-site basis` is checked. This only occurred when I first created the field and had the `Manage relations on a per-site basis` checked.

### Steps to reproduce

1. Create matrix field
2. Add a field and set it as an asset
3. Click on `Advanced` and click on the Manage relations on a per-site basis box. 
4. Save

### Additional info

- Craft version: Craft 3 beta
- PHP version: PHP 7.1.8
![screencapture-craft3-dev-admin-settings-fields-edit-37-1505503070514](https://user-images.githubusercontent.com/15054682/30499589-f58ecb0e-9a0f-11e7-9fc8-f424d7d505f5.png)

**Comment by brandonkelly** [comment]
Fixed for the next release (3fa7674eaefdfdaebdbfd2d15e4af02d42fc8472), thanks! In the meantime you can save the field without the “Manage relations on a per-site basis” setting enabled at first, and then re-save the field with the setting enabled.
