### ISSUE TITLE
New assets saved to entries via setContentFromPost() not sanitizing correctly

### ISSUE THREAD

**Issue by chasegiunta** [craftcms/cms#1988]
### Description

Need some validation on this, and _**it's a definite edge case**_, but here it is:

I have a PDF upload form hitting my controller, and saving the PDF to the applicable entry's asset field. It's doing so in the form of `$entry->setContentFromPost('fields');` (possibly not the best way to go about this? Taken from https://craftcms.stackexchange.com/questions/4175/create-entry-with-newly-uploaded-asset-programatically/4177#4177).

These forms are stored in S3. It appears that saving & setting asset fields this way will name the asset & the filename after the entry's title (not sure why it does this, instead of retaining the filename that's uploaded). Usually, this works. `filename.pdf` saved onto "My First Entry" would be renamed & set as `My-First-Entry.pdf`. 

The exception to this is if the entry has an apostrophe in the title. "Sarah's First Entry" is saved into S3 as `Sarahs-First-Entry.pdf`, yet saved into Craft either as `Sarah%27s-First-Entry.pdf` or `Sarah's-First-Entry.pdf` - I've seen both.

I'm guessing there's probably a better method to saving these assets onto my entries, but a minor bug still exists here.

### Steps to reproduce

1. Edit entry title to include an apostrophe.
2. Save entry from frontend with new asset via `setContentFromPost('fields')` from plugin.

### Additional info

- Craft version: 2.6.2989
- PHP version: 7.1

**Comment by chasegiunta** [comment]
Just ran across this again with ampersands. Asset saved/indexed into Craft (using same method) as `FloridaA&MUniversity.pdf`, but saved into S3 as `FloridaAMUniversity.pdf`

**Comment by andris-sevcenko** [comment]
@chasegiunta I'm not able to reproduce either of those issues (named after entry; mismatch between indexed/real filenames) using super-simple code. Can you perhaps share your code? Probably worth taking this to email, too, if that's proprietary code.

**Comment by chasegiunta** [comment]
Yet again, my attempts at bug-hunting have been foiled. Randomly found some old code in a plugin today that was renaming these files upon upload, just apparently not sanitizing them correctly (probably need to find the method being used in Craft). Sorry for wasting your time @andris-sevcenko
