### ISSUE TITLE
Make plugin settings consistent with component settings

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/cms#1989]
It is weird how everything in Craft 3 that has settings implements the settings as public properties on the model, except for plugins, which must define settings on a separate model.

The reason is because plugins are modules, not models, and currently models are the only thing that support validation.

We could possibly hack something together using Yii’s DynamicModel class, but that would add additional complexity, because setting values, validation rules, and errors would need to be transferred between the plugin and the model when running validation. Ideally Yii 2.1 will implement yiisoft/yii2#11884, and we’ll be able to implement validation support consistently across plugins and other components.

**Comment by brandonkelly** [comment]
As of Craft 3.4 it will be possible to configure plugins from `config/app.php` like other application components, via a new `craft\services\Plugins::$pluginConfigs` property.

```php
return [
    'components' => [
        'plugins' => [
            'pluginConfigs' => [
                'plugin-handle' => [
                    '...' => '...',
                ],
            ],
        ],
    ],
];
```

Not exactly what I was thinking when I created this issue, but it makes more sense to think of plugins as part of the application than user-definable components like custom fields / widgets / etc.

**Comment by piotrpog** [comment]
@brandonkelly 
Will we be able to still use separate config files to configure plugins as well?

**Comment by brandonkelly** [comment]
@piotrpog Yeah this just adds another option, for when it makes sense to modify the plugin’s module config directly.

**Comment by acalvino4** [comment]
> Will we be able to still use separate config files to configure plugins as well?

I haven't been able to find any documentation or blogs on how to set this up. I've gotten something working by looking into how other plugins do it, but I'm curious if there is a standard recommended way.

**Comment by brandonkelly** [comment]
It’s documented here: https://craftcms.com/docs/4.x/extend/plugin-settings.html (see [ Overriding Setting Values](https://craftcms.com/docs/4.x/extend/plugin-settings.html#overriding-setting-values) specifically for info on how the config files work).

**Comment by acalvino4** [comment]
Does this approach work for modules as well?

**Comment by brandonkelly** [comment]
Modules don’t have a dedicated settings concept. You can make a module configurable by adding public properties to the `Module` class, and then overriding their values from `config/app.php`:

```php
return [
    'modules' => [
        'my-module' => [
            'class' => MyModule::class,
            'propertyName' => 'override value',
            // ...
        ],
    ],
    // ...
];
```
