### ISSUE TITLE
AdminCP _include/forms and checkboxGroupField

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#1991]
I have a UX for a plugin I'm working on where I need a Checkbox Group field, where some of the options may be disabled.

The macro for `checkboxGroupField` seems conspicuously missing from `_include/forms`, I'd expect there to be something like:

```
{% macro checkboxGroupField(config) %}
    {% import "_includes/forms" as forms %}
    {{ forms.field(config, forms.checkboxGroup(config)) }}
{% endmacro %}
```

I can certainly just roll all of this behavior myself, but if it's simply an oversight/omission from the `_layouts/forms` templates, I figure it'd make sense to have it addressed in core.

**Comment by brandonkelly** [comment]
Yep that’s an oversight. Fixed now (f9f951dc25e720d35a9043c9288edede6aaa99b3).
