### ISSUE TITLE
Problem to save Entries after adding a EventListener in a plugin

### ISSUE THREAD

**Issue by boscho87** [craftcms/cms#1993]
### Description
```php
 Event::on(
            Entry::class,
            Entry::EVENT_AFTER_SAVE,
            function (AfterSaveEvent $event){
                var_dump($event->name);
                die();
            }
        );
```
this ends with the error:

> {closure}() must be an instance of yii\db\AfterSaveEvent, instance of craft\events\ModelEvent given

### Steps to reproduce

1. Add an Event in  a plugin 
2. Try to Save an Entry

### Additional info

- Craft version: 3.0.28-beata
- PHP version: 7.1
- Database driver & version: 
- Plugins & versions: // does not matter

**Comment by phoob** [comment]
Just change `AfterSaveEvent` to `craft\events\ModelEvent` in your code, maybe?

**Comment by phoob** [comment]
Or better: change to `craft\events\ElementEvent`

**Comment by brandonkelly** [comment]
At the top of your file you probably have this:

```php
use yii\db\AfterSaveEvent;
```

That should be:

```php
use craft\events\ModelEvent;
```

Then  change this line:

```php
function (AfterSaveEvent $event){
```

to:

```php
function (ModelEvent $event){
```
