### ISSUE TITLE
Redirecting after email verification

### ISSUE THREAD

**Issue by MarcoWilliamsPF** [craftcms/cms#1998]
### Description
As a developer,  I would like to be able to control where the page navigates to after a user verify's their email address.   

Optionally wanted:  Event to override from a plugin that would allow me to set the redirect.

### Steps to reproduce

1.  Enable Verification emails from the CP, or make sure they are enabled.
2.  Register as a new user
3.  Receive verification email and click on the link.
4.  it is forced to redirect to  admin/login   (CP/Root)

###  Code POI
UserController -> actionVerifyEmail

![image](https://user-images.githubusercontent.com/13422559/30646027-71c04346-9dcc-11e7-9895-bc6be09f8ebd.png)

Only Redirects if the request accepts JSON
![image](https://user-images.githubusercontent.com/13422559/30646479-fb70d6b8-9dcd-11e7-8377-3f5bb8b4a71a.png)
Content Types of the request when activation link is clicked.
![image](https://user-images.githubusercontent.com/13422559/30646722-cf27bf3a-9dce-11e7-816d-79b28f9c6e82.png)
Therefore the following is never called, resulting in  null returning from the method.
`return $this->_redirectUserAfterAccountActivation($user);`

### Solutions
I'm not 100% what the proper fix is for this issue.  There is not a situation where you can set the content type for "application/json"  in which it expects.  

I have replaced the return of UserController -> actionVerifyEmail  to the following
`return $this->redirectToPostedUrl();`

And I am overriding the  'redirect' in body params in the EVENT_AFTER_ACTIVATE_USER  event from my plugin.

However, there is probably a more elegant solution.

### Additional info

- Craft version: 3.0.0-beta.26
- PHP version: 7.1.x

**Comment by brandonkelly** [comment]
This is what the [activateAccountSuccessPath](https://craftcms.com/docs/config-settings#activateAccountSuccessPath) config setting is for.

**Comment by romainpoirier** [comment]
@brandonkelly, sorry to re-open the discussion, but still today (`Craft CMS 3.1.19`), the `activateAccountSuccessPath` config setting seems to only works after an account creation but not on email change (which still redirect to siteUrl instead). It would be also very useful to be able to customized this setting in this case.

**Comment by brandonkelly** [comment]
@romainpoirier Good point!

So currently `activateAccountSuccessPath` comes into play when:

- A user has registered an account on the front-end, on a site where “Verify email addresses?” is disabled and “Allow public registration?” is enabled (so their account gets activated immediately).
- A user has verified their email address for a previously-inactive account, thus activating their account, on a site where “Verify email addresses?” is enabled.

Verifying a new email address for an already-active account isn’t quite the same thing as verifying an email for a previously-inactive account, and I imagine some people will want that to redirect to a different page than the one that newly-activated users are sent to, so I think it warrants a new config setting.

**Comment by brandonkelly** [comment]
A new `verifyEmailSuccessPath` config setting has been added for the next release!

**Comment by yellostudio** [comment]
@brandonkelly is there any way of generating the` activateAccountSuccessPath` dynamically for each user?  Or is it just a static path?

**Comment by brandonkelly** [comment]
It’s static, but you could potentially set it to the URL of a template that redirects them _again_ based on the user account, via the `{% redirect %}` tag.
