### ISSUE TITLE
RTL field inputs are shown as LTR if the user's preferred language is LTR

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#20]
#### Environment:

- Craft version: 3.x
- PHP version: 7.x
- Database driver & version: n/a 
- Plugins & versions:

#### Description:

If a user's preferred language is LTR-oriented, and they are editing a RTL-oriented locale (e.g. Arabic), the fields are still LTR-styled, when they should be RTL.

**Comment by brandonkelly** [comment]
This has been fixed for v2 and v3 for a while.

**Comment by proimage** [comment]
@brandonkelly @angrybrad This appears to be an issue again in 3.6.x and 3.7.4. I've got a plain text field, in a Hebrew-language site (`he-IL`), but when my user is set to show things in English, the text field's (Hebrew) contents are shown LTR.

**Comment by brandonkelly** [comment]
@proimage Can you please create a new issue, with steps to reproduce, expected behavior, and screenshots?
