### ISSUE TITLE
Redactor plugins

### ISSUE THREAD

**Issue by MDXDave** [craftcms/cms#2000]
It would be nice if it would be possible to enable a redactor plugin without the need of a craft plugin. Just include the 20 plugins from redactor (https://imperavi.com/redactor/plugins/) and maybe the possiblity of adding a plugin by name and js file.

**Comment by AbbeyDesign** [comment]
I need just one of the simplest things, text alignment. At some point Redactor made this a separate plugin but Craft is not including this plugin.

**Comment by brandonkelly** [comment]
We’re moving Redactor out into its own plugin (https://github.com/craftcms/redactor), which will officially launch in the Plugin Store with Craft 3 RC1.

Good news! Redactor 1.0 will have this feature – all you will need to do is upload your Redactor plugins to `config/redactor/plugins` (plus add the plugin to your config’s `"plugins"` array), and the field will pick it up.

**Comment by BryceBubbles** [comment]
@brandonkelly Hi, is this still a thing in Craft 3 with the Redactor plugin?
> all you will need to do is upload your Redactor plugins to config/redactor/plugins (plus add the plugin to your config’s "plugins" array), and the field will pick it up.

Would be amazing if it was!

**Comment by brandonkelly** [comment]
@BryceBubbles It is, but even better, the Redactor plugin for Craft 3 comes with all of Imperavi’s 1st party plugins bulit-in. So assuming you don’t need to make any changes to the JS, you can just go straight to including a plugin in your Redactor config `.json` file.
