### ISSUE TITLE
Matrix + Multi-Site broken

### ISSUE THREAD

**Issue by swey** [craftcms/cms#2001]
## Description
In the latest versions the usage of Matrix fields breaks the usage of multiple sites.

The error "Resaving matrix block elements" occurs:
![bildschirmfoto 2017-09-21 um 08 25 16](https://user-images.githubusercontent.com/568574/30681712-f7c31786-9ea6-11e7-8abc-687e37dd31df.png)

### Steps to reproduce

1. Create a new Matrix field with a simple block and a section using that matrix
2. Create a entry in that section and add a matrix block with some dummy content
3. Try to create a new site

### Additional info

- Craft version: Latest `dev-develop` (`3.0.0-beta.28`+)
- PHP version: 7.1.1
- Database driver & version: Tested with MySQL and MariaDB
- Plugins & versions: Tested in a fresh install without plugins

**Comment by ChanceArthur** [comment]
Getting the same thing here on PostgreSQL.

**Comment by brandonkelly** [comment]
Thanks – fixed for the next release.
