### ISSUE TITLE
No such file or directory error on changing users photo

### ISSUE THREAD

**Issue by S1lentium** [craftcms/cms#2005]
### Description

unlink(/home/cms/storage/runtime/temp/assets59cb4ae26f1842.80020798.jpg): No such file or directory

### Steps to reproduce
When changing users photo, after save i got error.

The problem is on FileHelper::removeFile($fileLocation), because $users->saveUserPhoto already clean temp file.

Trace:
```php
// Did they upload a new one?
if ($photo = UploadedFile::getInstanceByName('photo')) {
    $fileLocation = Assets::tempFilePath($photo->getExtension());
    move_uploaded_file($photo->tempName, $fileLocation);
    $users->saveUserPhoto($fileLocation, $user, $photo->name);
    FileHelper::removeFile($fileLocation);
}
```

Sorry for my English)
### Additional info

- Craft version: 3.0.0-beta.28
- PHP version: 7.0
- Database driver & version: mysql 5.5

**Comment by brandonkelly** [comment]
Are you seeing this in the Control Panel or a front-end user profile form?

**Comment by S1lentium** [comment]
front-end

**Comment by brandonkelly** [comment]
Thanks! Fixed for the next release.
