### ISSUE TITLE
Drop down field value gets saved for all entries when set to default, even if they don't use field

### ISSUE THREAD

**Issue by ldstevens** [craftcms/cms#2007]
### Description

Ran into this little issue the other day when a field was evaluating as not empty for an entry that didn't use it and I didn't know why.

My expectation was that a drop down field with a default option checked would still save as null for entries that didn't use it. 

### Steps to reproduce

1. Create a drop down field, check one option as default. 
2. Submit an entry that doesn't use that field.
3. The new entry will have the default drop down value saved in its craft_content data.
4. Unchecking default stops this happening.

### Additional info

- Craft version: 2.6.2989 

Hope that makes sense. Thanks! :)

**Comment by StevenVerbiest** [comment]
I have the same issue, but this only occurs when u check the default option when creating the field.

If you create a dropdown field and select no default value and add the default value later, everything works as expected.

It took me some time to figure this out...

**Comment by brandonkelly** [comment]
This sounds like expected behavior to me! The “Default” setting determines which option will be selected be default when you first load the page.

**Comment by ldstevens** [comment]
Just to clarify...

Say we have two sections, one called News and one called LongAssArticles, with entry types of the same name.

News has a few basic fields.

LongAssArticles has a bunch of extra fields, including a drop down with a default value set to "CoolDefaultValue".

Expected behavior for all entries saved in LongAssArticles is to have the default value set on page load, for sure.

However, currently News entries (which don't have the drop down field in their entry type) get saved with "CoolDefaultValue" despite not using that value. I would have expected it to be null.

This becomes an issue when testing variables in shared templates. Let's say News and LongAssArticles have a shared header template. I would normally do something like...

```
if dropDownField is not null
[html and values]
endif
```

...however that's not going to work, because a default value means dropDownField is always the default value and never null across all entries regardless of entry type.

Does that make sense? If so and that's still expected behavior, so be it, just wanted to make sure my explanation was clear :)

Thanks!

**Comment by brandonkelly** [comment]
Gotcha, thanks for clarifying. Will look into it.

**Comment by brandonkelly** [comment]
OK so, this is (awkwardly) expected behavior for Craft 2, just because of the way things are architected. However it is no longer the case in Craft 3, thanks to all the content refactoring.

In the meantime, you’ll just have to add some template code that checks the entry’s section, rather than checking the dropdown field value.

```twig
{% if entry.section.handle in ['sectionA', 'sectionB'] %}
```

**Comment by TomDeSmet** [comment]
Hi, I seem to have this problem on Craft 3.1.31? I thought this was 'fixed' in Craft 3?

1. I created a drop down field with a default selection.
2. Added it to an entry type.
3. Removed it from that entry type.
4. But the value was still saved in the content table.

Deleting it from the content table solved my issue (it doesn't get resaved when resaving the entry).

But this seems like a bug.
