### ISSUE TITLE
suggestion: make Field which defined as Title automatically mandatory

### ISSUE THREAD

**Issue by crazyx13th** [craftcms/cms#2008]
### Description
If I save a Entry and keep my Headline - which is defined as **title** - blank, I got "could not save" and nobody knows why

![grafik](https://user-images.githubusercontent.com/8912561/30956571-110054c0-a438-11e7-97c1-823348f94ec1.png)

Would it makes sense to make this **automatically** mandatory (with a *) ?

![grafik](https://user-images.githubusercontent.com/8912561/30956560-096b49e0-a438-11e7-97b1-ec37bb7f0c81.png)

Thx!

Greetings
crazyx13th

**Comment by brandonkelly** [comment]
Did you rename the Title field to Headline, or is Headline a custom text field?

If the latter, you must mark it as required from your field layout.
