### ISSUE TITLE
Safari 11 Color Picker

### ISSUE THREAD

**Issue by RitterKnightCreative** [craftcms/cms#2010]
### Description
Noticed Safari 11 (finally) now natively supports ``<input type="color">``. 

Probably a poly fill issue... but as rendered in SafarI:

![screen shot 2017-09-28 at 4 36 03 pm](https://user-images.githubusercontent.com/3707869/30991614-5ad038e4-a46b-11e7-9313-a73739856afa.png)

As rendered (properly) in Chrome:
![screen shot 2017-09-28 at 4 37 21 pm](https://user-images.githubusercontent.com/3707869/30991770-12aca9ac-a46c-11e7-9a45-5603816b1574.png)

### Additional info

- Craft version: Craft CMS 2.6.2990

**Comment by brandonkelly** [comment]
Fixed the width of the input for the next release – thanks!
