### ISSUE TITLE
Craft 2.x error handling

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#2011]
In `ErrorHandler.php` you do:

```
	/**
	 * Renders the exception information. This method will display information from current {@link error} value.
	 */
	protected function renderError()
	{
		// This could be an exception because handleException can call renderError.
		$exception = $this->getException();

		// If the exception exists, and it's an instance of HttpException or devMode isn't enabled
		// set the errorAction to our TemplatesController->renderError().
		if (!YII_DEBUG || $exception instanceof HttpException)
		{
			$this->errorAction = 'templates/renderError';
		}

		parent::renderError();
	}
```
So it's only if `devMode` is off _and_ the exception is a `HttpException` that we get the nice Craft error templates (with the potential ability to override their display on the frontend with `404.html`, etc templates).

The problem is that when a db exception, it falls back on the standard Yii error display. This is a problem if for security reasons, the client does not want information like the db error, the fact that it's running MySQL, and the names of tables, etc. displayed on the frontend.

In an ideal world, there would be some way to control what information is display publicly in the event of any type of exception, not just `HttpException`s

**Comment by brandonkelly** [comment]
If Dev Mode isn't enabled (as it should never be on production), it will always go to the lower-info error display, which seems like expected behavior?

**Comment by khalwat** [comment]
So here's the scenario. A production company finished a website for a client. A third party penetration testing service then ran some penetration tests.

One of the tests (likely automated) that they did was to put various random string URLs in.  If you put a URL with 4-byte UTF-8 encoded string in it, and you're running MySQL (which only handles 3-byte encoding), it causes my Retour plugin to throw an error that looks like this:

<img width="1133" alt="screenshot 2017-09-28 22 34 21" src="https://user-images.githubusercontent.com/7570798/31048073-df1facd2-a5e3-11e7-9311-972984827b8f.png">

I've since rectified the problem, by using `StringHelper::encodeMb4()` on any URL parameters before putting them into the database.

However, the penetration company considered the above error message to be a security risk, because it displays information about the database that's running (MySQL), as well as the underlying schema.

Which brings up the general point that I've heard from other clients before, which is that they'd like to be able to control what information is displayed when an error is thrown. I've seen database errors thrown for a variety of reasons, and many clients would prefer a much more generic error "A problem has occurred" (or whatever) with `devMode` off.

There doesn't appear to be a way to override the above Yii error display without a custom plugin. Thus it would be nice if there was a way to control what error message information gets displayed on the frontend at the Craft level.

**Comment by brandonkelly** [comment]
You can create an `error.html` or `error.twig` (or `500` instead of `error`) to override the error template that gets rendered there.

**Comment by khalwat** [comment]
Including overriding the Yii-ish error messages? It didn't seem so from the code, because `$this->errorAction = 'templates/renderError';` won't be set for non-`HttpException`s

**Comment by khalwat** [comment]
Ugh nevermind... `||`

**Comment by brandonkelly** [comment]
Hah, yeah a little confusing. We’ve actually made it simpler in Craft 3 – all errors/exceptions will go throug

**Comment by khalwat** [comment]
So @brandonkelly I've been looking into this a bit more of late, and there's something I'm not understanding.

I do see that there is a generic `error.html` template that Craft itself falls back on if you don't provide one on the frontend:

```
{% extends "_layouts/message" %}
{% set title = "Oops!"|t %}

{% block message %}
	<h2>{{ title }}</h2>
	{% filter md %}{{ message }}{% endfilter %}
{% endblock %}
```
However, this is most certainly not what was used to render the above referenced screenshot:

<img width="1133" alt="screenshot 2017-09-28 22 34 21" src="https://user-images.githubusercontent.com/7570798/31048073-df1facd2-a5e3-11e7-9311-972984827b8f.png">

It doesn't have any of the formatting that should be inherited from `_layouts/message` (and then `_layouts/base`).

Is this because it's a lower-level error that is handled by Yii, without it bubbling up to Craft? Or is it actually that error, but for whatever reason, it's unable to load the associated styling somehow? Or is it because we end up here:

```
	protected function handleDbConnectionError(DbConnectException $exception)
	{
		$this->_error = $data = array(
			'code'      => 'error',
			'type'      => get_class($exception),
			'errorCode' => null,
			'message'   => $exception->getMessage(),
			'file'      => null,
			'line'      => null,
			'trace'     => '',
			'traces'    => null,
		);

		if (!headers_sent())
		{
			HeaderHelper::setHeader('HTTP/1.0 500 '.$this->getHttpHeader(500, get_class($exception)));
		}

		$this->render('error', $data);
	}
```

?

**Comment by khalwat** [comment]
Alright, I did some further tests, and it looks like it's actually using the appropriate code path, but for whatever reason, certain errors can prevent the stylesheet from loading.

**Comment by brandonkelly** [comment]
You will get a plain text version if the actual error template ends up throwing its own exception of some sort. (Like, if it's a Twig syntax error in your layout template, and your error template also uses the same layout template.)

**Comment by narration-sd** [comment]
I'd just throw in here if it helps considerations that I was getting some fully unformatted full stack traces a few days ago, while bringing up some fairly nefarious plugin code, until it worked. These failures may well have occurred during initialization (I now think), within the plugin init at boot time.

I thought this was a regression on lost formatting that you fixed in C3 a longish time ago, Brandon, if I couldn't locate that as an issue. I couldn't replicate the problem yesterday when intending to write this up, but I probably didn't hit init this time, which your discussion now has me thinking about.

I'm not sure Craft needs to be formatting errors that occur in plugin init, as that _should_ be dev time, but it was a surprise and a  little mis-lead into suspicion since  it didn't, in the midst of thinking out the rest of what might be going on.  Thus maybe making this formatting consistent could be worth it, if not too much trouble in re-ordering the code.
