### ISSUE TITLE
Frontend User Logout

### ISSUE THREAD

**Issue by janelmer** [craftcms/cms#2014]
### Description
I have this standard Code to log out a user from the frontend:

    {% if craft.session.isLoggedIn %}
           <a href="{{ logoutUrl }}">Logout</a>
    {% endif %}

After clicking the logout link in the frontend the user stays logged in. User gets directed to the logout page, but is still logged in. 

### Additional info
- Craft version: 2.6.2986
- PHP version: 7.0
- Database driver & version: MySql 5.6.35

**Comment by takobell** [comment]
Not able to reproduce this locally on a fresh install.  How are you testing if they are logged in still?  Guessing you've got some caching showing false-positives... either opcache/APC, `{% cache %}` tags, Varnish, browser, etc.

**Comment by janelmer** [comment]
I can see that the cookies are still there after login out. If i go back to the page with
{% requireLogin %} tag, i'm still logged in. And the site keeps displaying the Logout link by that code:
{% if craft.session.isLoggedIn %}
       <a href="{{ logoutUrl }}">Logout</a>
{% endif %}
I have no {% cache %} tags in my templates and do not use varnish. Browser cache is disabled.
When i log out from the CP it works, cookie gets deleted and i'm logged out.

**Comment by janelmer** [comment]
it is http://localhost/logout set in the config.php file as 
'logoutPath' => 'http://localhost/logout',

**Comment by brandonkelly** [comment]
Ah… the `logoutPath` config setting must just be a URI path, not a full URL. It should just be `'logout'`.

**Comment by janelmer** [comment]
Thanks a lot, that works. But it doesn't redirect to that page. But it works for me now.
