### ISSUE TITLE
Database backup fails using Postgres in Craft 3.x

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#2017]
In Craft 3.x, if you're using Postgres and you try to back up the database via the admin/utilities and your database has a password, you'll get an error like this:

```
Could not create backup: The shell command "pg_du
mp --dbname=craft3beta --host=postgres --port=5432 --username=craft3beta --no-pa
ssword --if-exists --clean --file=/usr/share/nginx/storage/backups/thirdway_1710
04_161700_rqmvmzc3xb_v3.0.0-beta.29.sql --schema=public --exclude-table-data 'pu
blic.assetindexdata' --exclude-table-data 'public.assettransformindex' --exclude
-table-data 'public.cache' --exclude-table-data 'public.sessions' --exclude-tabl
e-data 'public.templatecaches' --exclude-table-data 'public.templatecachecriteri
a' --exclude-table-data 'public.templatecacheelements'" failed with exit code 1:
 pg_dump: [archiver (db)] connection to database "craft3beta" failed: fe_sendaut
h: no password supplied in /usr/share/nginx/vendor/craftcms/cms/src/controllers/
UtilitiesController.php:377
```

You should be creating a credentials temp file as per: https://github.com/nystudio107/craft-scripts/blob/master/scripts/backup_db.sh#L58

...and then set the `PGPASSFILE` environmental variable to the path to it before calling `pg_dump`

Something like this:

```
    echo ${LOCAL_DB_HOST}:${LOCAL_DB_PORT}:${LOCAL_DB_NAME}:${LOCAL_DB_USER}:${LOCAL_DB_PASSWORD} > "${TMP_DB_DUMP_CREDS_PATH}"
    chmod 600 "${TMP_DB_DUMP_CREDS_PATH}"
    PGPASSFILE="${TMP_DB_DUMP_CREDS_PATH}" $LOCAL_PG_DUMP_CMD $LOCAL_DB_CREDS $LOCAL_IGNORED_DB_TABLES_STRING $PG_DUMP_ARGS --schema="${LOCAL_DB_SCHEMA}" --file="${BACKUP_DB_PATH}"
    rm "${TMP_DB_DUMP_CREDS_PATH}"
```

**Comment by takobell** [comment]
This works from a shell script because you're able to create a environment variable on the fly and execute the backup from that same script.  I've yet to find a way to be able to create a global environment variable from PHP that a console request started with proc_open or exec (which is how Craft triggers pg_dump) would have access to, that also works on *nix and Windows.

**Comment by takobell** [comment]
Leaving this open, because I feel like it should be possible and maybe someone smarter than myself can chime in.

**Comment by khalwat** [comment]
https://stackoverflow.com/questions/3571582/how-to-set-command-line-environment-variable-in-php-shell-exec

**Comment by khalwat** [comment]
Here's a PR that works on Mac & Linux:

https://github.com/craftcms/cms/pull/2023

![google chromescreensnapz752](https://user-images.githubusercontent.com/7570798/31285902-902b4eb4-aa8a-11e7-8839-83eb0ee9069d.png)

**Comment by takobell** [comment]
Fixed in https://github.com/craftcms/cms/commit/242d6cd4564550ff3e36388f6972795937167580.
