### ISSUE TITLE
Error when trying to update "The HOME or COMPOSER_HOME environment variable must be set for Composer to run correctly."

### ISSUE THREAD

**Issue by davist11** [craftcms/cms#2019]
### Description
When trying to update both Craft CMS and Contact Form in the control panel, I get the error

```
The HOME or COMPOSER_HOME environment variable must be set for Composer to run correctly.
```

I installed composer globally following the normal instructions, and I checked the `composer config --list` to see that the home variable is set

```
[home] /Users/tdavis/.composer
```

And I can confirm that that folder exists. I tried setting the `CRAFT_COMPOSER_PATH` manually and got the same error.

### Steps to reproduce

1. Visit /admin/utilities/updates and try to run a pending update

### Additional info

- Craft version: Craft Pro 3.0.0-beta.26
- PHP version: 7.1.8
- Database driver & version: MySQL 5.6.35
- Plugins & versions:
    - Contact Form 2.0.2
    - Contact Form Honeypot 1.0.1
    - Inlin 2.0.0
    - Asset Rev 1.1.0

**Comment by brandonkelly** [comment]
Run this in your terminal: (from the same environment you’re running Craft in – so if it’s a Vagrant box you need to SSH into that first)

    echo $HOME; echo $COMPOSER_HOME

What does it output?

**Comment by davist11** [comment]
`/Users/tdavis`

**Comment by brandonkelly** [comment]
Hm, it must not be available to the PHP instance that’s actually running on the web server. Try creating a PHP file with this, and see what it outputs in the browser:

```php
<?php
print_r(getenv('HOME'));
echo '<br>';
print_r(getenv('COMPOSER_HOME'));
```

**Comment by davist11** [comment]
Nada.

That does make sense though since I'm using MAMP for managing local servers. I went through [this guide](https://gist.github.com/kkirsche/5710272) to install Composer for MAMP, but I'm still getting the same result.

**Comment by brandonkelly** [comment]
Cool, can try looking into it with MAMP. What PHP version is it set to? Have you made any changes to the php.ini template?

**Comment by lynseyenvoc** [comment]
Was this resolved? Having same issue.

**Comment by brandonkelly** [comment]
Yes, for the next release.
