### ISSUE TITLE
Expand getWidth() and and getHeight() to video files

### ISSUE THREAD

**Issue by jan-thoma** [craftcms/cms#2024]
Sometimes we need to get video sizes in before eg. for lazy loading or stuff like packery.

**Comment by khalwat** [comment]
They'd probably want something like:

https://github.com/JamesHeinrich/getID3

If they wanted to extract the meta information. It's non-trivial to try to do.

**Comment by andris-sevcenko** [comment]
It's definitely not trivial and is pretty niche. I could see it happening as a plugin, though.

**Comment by khalwat** [comment]
This plugin already does it: 

https://github.com/carlcs/craft-assetmetadata

**Comment by jan-thoma** [comment]
maybe exiftools is worth a try, if its installed on the host system.

**Comment by brandonkelly** [comment]
This definitely feels like a job for a plugin.

**Comment by carlcs** [comment]
@jan-thoma there’s no additional package installation required to get Asset Metadata plugin running (it uses getID3). You can store the video width, height or other metadata like framerate.

```twig
{{ metadata.video.resolution_x ?? null }}
```

**Comment by KatieMFritz** [comment]
That plugin doesn't seem to have made it to the plugin store yet. What are folks doing in Craft 3 for this?

**Comment by brettburwell** [comment]
For anyone that ends up here, @khalwat's Transcoder plugin can help with this.
https://plugins.craftcms.com/transcoder

Here's the relevant bit from the docs:
https://nystudio107.com/docs/transcoder/Using.html#generating-a-transcoded-video

**Comment by ryanleichty** [comment]
@khalwat If all we want is the ability to get a video’s width and height from Craft (to avoid layout shift, etc), would using the Transcoder plugin be overkill for that purpose?

**Comment by khalwat** [comment]
@ryanleichty probably. It requires that you have `ffmpeg` installed too

**Comment by stephanedemotte** [comment]
I try to to use getID3 to get the width/height of a video but cannot find the right event to do it.

I've created a new modules, and try to catch the after saved event asset but i got an error when i try

```
use yii\base\Event;
use craft\elements\Asset;

      Event::on(
          Asset::class,
          Asset::EVENT_AFTER_REPLACE_ASSET,
          function(ReplaceAssetEvent $event) {
              // will try to overwrite the width and height
          }
      );
```

`Undefined constant craft\elements\Asset::EVENT_AFTER_REPLACE_ASSET`

Please someone can help ?

**Comment by mmikkel** [comment]
@stephanedemotte You have the wrong namespace for the Asset class; replace `use yii\craft\elements\Asset;` with `use craft\elements\Asset;`.

**Comment by stephanedemotte** [comment]
@mmikkel thank i have updated my code but still have the same error message `Undefined constant craft\elements\Asset::EVENT_AFTER_REPLACE_ASSET`

**Comment by i-just** [comment]
@stephanedemotte the `EVENT_AFTER_REPLACE_ASSET` is part of the `craft\services\Assets` (not `craft\elements\Asset`). If you go to the [event code generator](https://craftcms.com/docs/4.x/extend/events.html#event-code-generator) in the docs, you can check/fine-tune how to use the available events. I hope this helps!

**Comment by stephanedemotte** [comment]
I share my fix, i'm a noob on Craft, if someone can make this code better, i take ! :)

```
use yii\base\Event;
use craft\assetpreviews\Video;
use JamesHeinrich\GetID3;

//......

        Event::on(
          Video::class,
          Video::EVENT_INIT,
          function (Event $event) {
            $asset = $event->sender->asset;
            if($asset->width == null && $asset->height == null):
              $getID3 = new GetID3\GetID3;
              $infos = $getID3->analyze($asset->getImageTransformSourcePath());
              $asset->width = $infos['video']['resolution_x'];
              $asset->height = $infos['video']['resolution_y'];
              Craft::$app->elements->saveElement($asset);
            endif;
          }
        );
```
