### ISSUE TITLE
separate plugin settings for each site

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#2028]
Just a question and if it is not possible a feature request since I expect more users than us to have this issue.

Is it somehow possible to support multi site pluginsettings for Craft 3? 
For example I made a Google Analytics Plugin to show GA Charts on the dashboard. The Credentials are stored in the plugin settings. A multi site project needs obviously multiple credentials for each site.

Is there standard method from craft to handle such situations? In our company we have multiple plugins that require such a feature and our current plan (workaround) is creating a custom database table to store plugin settings with the siteId instead of using the craft "plugins" table.

So as for the future: can we continue with out custom table or are there plans to include settings for each site?

**Comment by brandonkelly** [comment]
I think you’re already doing it the right way. I don’t want to overcomplicate the built-in plugin settings support; it works well for most cases.
