### ISSUE TITLE
"add" button disappears from category fields if a category is added which adds a disabled step in the category tree

### ISSUE THREAD

**Issue by olets** [craftcms/cms#2035]
### Description

Entry category fields lose their "add" button if a descendant of a disabled category which itself is a descendant of an enabled category is added without adding one of its ancestors at the same time.

That is, for `+` is enabled and `-` with the category tree

```
(…)
  A +
    (…)
      B -
        (…)
          C +
```

adding C to a category field will make the "add" button disappear from the field.

### Steps to reproduce

1. Create a category (A)
1. Create another category (B) as a descandant of A
    - Toggle B's `enable` to off
1. Create a subcategory of B (C)
1. Create a category field and apply it to an entry
1. In an entry that has the category field, add C
1. Save the entry
    - The "add" button will have disappeared from the field interface
1. Remove C
1. Save.
    - The "add" button is back

This happens regardless of how far removed the added category is from the disabled category, as long as the added category is a descendant of the disabled categoy
 
That's the basic situation. It's actually more involved:

#### Works

  - If you skip A, and just make a top-level disabled category B, and create C a descendant of B, and add C to a category field on an entry, and save, the add button is still there.
  - If you do 1-4, add A or B, and then continue with 5 and 6, the add button will be there
  - If you do 1-5 but before saving you add A or B to the field and then save, the add button will be there

#### Doesn't work

  - If you do 1-4, add A or B, save, and then add C and save, the button will not be there

&nbsp;

### Additional info

I've tried two sites so far and both have this bug

- Craft version: 2.6.2988, 2.6.2989
- PHP version: 5.5.38
- Database driver & version: where is this?
- Plugins & versions: 

   The plugins shared by the two sites I've tested are

    - Import 0.8.28, 0.8.32
    - Inlin 1.1
    - Pimp My Matrix 2.1.2
    - Reroute 1.0.4
    - Super Table 0.4.8, 1.0.5
    - Video Embed 1.0

**Comment by brandonkelly** [comment]
Does your Categories field have a limit?

**Comment by olets** [comment]
I've only tested so far on no-limit category fields

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by olets** [comment]
Thanks @brandonkelly @MakeilaLundy!
