### ISSUE TITLE
Unable to type spaces in tag fields

### ISSUE THREAD

**Issue by whoisgina** [craftcms/cms#2036]
### Description
When typing in a tag field, all spaces are trimmed as you type them. However, it _is_ possible to add spaces after the fact as long as they're in the middle of the string. This started happening after we updated to 2.6.2991. Our clients are adding full names as tags so this is slowing them down quite a bit.

@khalwat in Slack says that this bit of `TagsController.php`:
`$tag->getContent()->title = trim(craft()->request->getRequiredPost('title'));`

Could be the culprit? He suggests using `ltrim()` and `rtrim()` instead.

Here's a video of the issue from @luizboaretto: https://www.dropbox.com/s/0xisoce9bb8840o/tags_bug.mov?dl=0

### Steps to reproduce

1. Type a string with a space in it in the tag field
2. Notice how the spaces are automatically deleted! 
3. Note that you can move your cursor to a point in the middle of a string and add a space without it being deleted

### Additional info

- Craft version: 2.6.2991
- PHP version: 5.5.9-1ubuntu4.21
- Database driver & version: mysql 5.5.55 (maybe, not sure if this is what you need?)

### Plugins & versions:
- Ad Wizard 1.3.1
- Entry Count 1.0.0
- Escapee 1.0
- Inlin 1.1
- Legacy Redirects 1.0.22
- Neo 1.4.1
- Redactor Inline Styles 2.1.3
- Relabel 0.1.3
- Similar 1.0.0
- Smartdown 2.1.0
- Tag Manager 0.2.0
- User Manual 1.1.1

**Comment by brandonkelly** [comment]
Thanks! Fixed for the next release (coming soon…)

**Comment by takobell** [comment]
And here it is! https://craftcms.com/changelog#2-6-2992

**Comment by luizboaretto** [comment]
Thanks Brad!



Luiz

**Comment by whoisgina** [comment]
So fast! Thanks so much!
