### ISSUE TITLE
getQueryStringWithoutPath() does not return full query string if multiple params with same key exist

### ISSUE THREAD

**Issue by chasegiunta** [craftcms/cms#2041]
### Description

given a URL of `site.com?foo=bar&foo=baz&foo=biz`

`craft.request.getQueryStringWithoutPath()` would return `foo=biz` on this, while `craft.request.getQueryString` returns `foo=bar&foo=baz&foo=biz`

If this is the intended behavior, might be worth stating in docs, as the only thing stated is
>Returns the query string, except for the `p=` param

### Steps to reproduce

1. Request query that has multiple params with same key via `getQueryStringWithoutPath()`

**Comment by khalwat** [comment]
Looks like they do two different things:
```
	/**
	 * Returns part of the request URL that is after the question mark.
	 * @return string part of the request URL that is after the question mark
	 */
	public function getQueryString()
	{
		return isset($_SERVER['QUERY_STRING'])?$_SERVER['QUERY_STRING']:'';
	}
```
and then:
```
	/**
	 * Returns the request’s query string, without the p= parameter.
	 *
	 * @return string The query string.
	 */
	public function getQueryStringWithoutPath()
	{
		$queryData = $this->getQuery();

		unset($queryData[craft()->urlManager->pathParam]);

		return http_build_query($queryData);
	}
```

http://php.net/manual/en/function.http-build-query.php

**Comment by chasegiunta** [comment]
Yep. If it's a caveat that we have to live with, then maybe it should just be mentioned. Since I knew I was only doing this on one page, and I knew the particular route/segment, I ended up using the normal `craft.request.queryString` and using the trim filter to `trim('p=segment&', 'left')`. Not ideal, but a workaround for now since I have the relevant info needed get past this.

**Comment by brandonkelly** [comment]
I’m able to reproduce this and it's definitely not expected behavior. Will fix…
