### ISSUE TITLE
Memcache config missing username and password 

### ISSUE THREAD

**Issue by askogrand** [craftcms/cms#2045]
### Description
[Yii Memcache Config](http://www.yiiframework.com/doc-2.0/yii-caching-memcache.html) seems to support username and password, but those options are not currently supported in Craft 3

### Additional info

- Craft version: 3
- PHP version: 7.1
- Database driver & version: 5.5.49

**Comment by brandonkelly** [comment]
We’ve dropped support for the `cacheMethod` config setting, as well as `config/memcache.php`, for the next Beta release (per #2053). Instead you can configure memcached from `config/app.php`:

```php
'components' => [
        'cache' => [
            'class' => yii\caching\MemCache::class,
            'useMemcached' => true,
            'username' => getenv('MEMCACHED_USERNAME'),
            'password' => getenv('MEMCACHED_PASSWORD'),
            'defaultDuration' => 86400,
            'servers' => [
                [
                    'host' => 'localhost',
                    'persistent' => true,
                    'port' => 11211,
                    'retryInterval' => 15,
                    'status' => true,
                    'timeout' => 15,
                    'weight' => 1,
                ],
            ],
        ],
    ],
];
```

(No need to wait for the next Beta release to drop – you can make this change right now.)
