### ISSUE TITLE
The table column URI for structures are not updating on nested sorting, leaving the user with a 404 page when visiting.

### ISSUE THREAD

**Issue by H-i-red** [craftcms/cms#2046]
### Description

The table column URI for structures are not updating on nested sorting, leaving the user with a 404 page when visiting.

### Additional info

- Craft version: 2.6.2993 (Client)
- PHP version: 7.1.6
- Database driver & version: MySQL 5.6.35

**Comment by brandonkelly** [comment]
Yeah unfortunately this isn’t something we can easily solve, since the values get updated from a background task after the fact, and there’s no easy way to notify the Control Panel once it’s done.
