### ISSUE TITLE
Matrix Block Type with over 32 fields

### ISSUE THREAD

**Issue by paulmck21** [craftcms/cms#2047]
I need to create a block in a matrix with 60 fields, this is necessary as I cannot put a matrix inside a matrix.

When I make any more than 32 fields the extra fields are deleted on save without throwing an error.

Is there a setting I can change to allow this or should I find another workaround?

- Craft version: 2.6.2954
- PHP version: 5.6.10

Thanks in advance

**Comment by takobell** [comment]
You're likely running into https://craftcms.stackexchange.com/questions/21290/cant-add-anymore-fields-blocks-to-matrix-field/21296#21296
