### ISSUE TITLE
Pagination doesn't seem to (fully) work

### ISSUE THREAD

**Issue by PanMan** [craftcms/cms#2051]
### Description
I get some elements which display fine with:

```twig
{% for event in craft.entries
    .section('events')
    .eventTimeStart('>= ' ~ now|date('Y-m-d'))
    .order('eventTimeStart asc')
    .limit(10)
    .all() %}
```

I now want to change that to use pagination:

```twig
{% paginate craft.entries
    .section('events')
    .eventTimeStart('>= ' ~ now|date('Y-m-d'))
    .orderBy('eventTimeStart asc')
    .limit(10) as pageInfo, pageEntries %}
```

I have 2 issues with this:

1. it retrieves entries, but seems to ignore the eventTimeStart (showing my first events)
2. `pageInfo.getPrevUrl()` and `pageInfo.getNextUrl()` stay empty.
`pageInfo.total` does show 3 pages.

### Steps to reproduce

1. Code above :)

### Additional info

- Craft version:
3.29 beta
- PHP version:
7.1
- Database driver & version:
MySQL

Thanks for any pointers!

**Comment by PanMan** [comment]
Thanks for fixing! 👍

**Comment by brandonkelly** [comment]
Thanks for the help!
