### ISSUE TITLE
Cannot specify x-goog-project-id when using Google Cloud Storage for Assets

### ISSUE THREAD

**Issue by ingernet** [craftcms/cms#2055]
### Description
Craft 2.6 UI does not allow a user to specify the Google Project ID (either by number or by slug) that is associated with a Google user's keys, when the user chooses Google Cloud Storage as the asset source type. This is a problem because key/secret pairs are associated with _users_ on the Google system, who may be associated with more than one project, rather than by _project_.

If an `x-goog-project-id` variable isn't passed in while accessing the Google Cloud Storage API, the system looks at the key/secret and uses the default project associated with the user attached to the key/secret. This yields (at best) an incorrect list of buckets available as part of that default project, or (worse) a generic error message or (very worst) an accidental upload of confidential images to the wrong bucket. 

Simply changing the default project in Google won't work, as that can potentially affect all of the user's interoperability transactions that are in play outside of Craft, which might be relying on the default project ID.

I propose that you add a conditional field that shows up when a Craft admin selects Google Cloud Storage as a source type. This field can be as simple as an ~integer~ string field with the label of "x-goog-project-id." It can be passed in as a header during GC operations, in compliance with [these docs](https://cloud.google.com/storage/docs/projects).

### Steps to reproduce

1. Set up two projects on Google Cloud Platform - `Project ABC` and `Project DEF`. For simplicity's sake, set these up using the same Google account
2. On the `Project ABC` project, create 2 public buckets in Cloud Storage: `ProjectABCBucket_01` and `ProjectABCBucket_02`
3. Switch projects in the top Project menu to `Project DEF`, then create 2 public buckets in Cloud Storage: `ProjectDEFBucket_01` and `ProjectDEFBucket_02`
4. Switch projects back to `Project ABC`, then in Google Console > Storage, make sure that `Project ABC` is selected in the Projects list at the top, and click the Interoperability tab.
5. Confirm that `Project ABC` is listed as your default project for interoperability. (It'll be in a green div.) If it's not, click the "Make Project ABC my default project" button.
6. Make a note of your access key and secret listed in the Interoperability tab - this is associated with your user, not with the project! So weird! Why, Google? WHYYYY
6. In Craft admin area, go to Settings > Assets and add a new Asset source
7. Choose Google Cloud Storage as your asset type
8. Add your asset key and secret, and click Refresh

Expected result: You should only see `ProjectABCBucket_01` and `ProjectABCBucket_02` buckets. `ProjectDEFBucket_01` and `ProjectDEFBucket_02` should not show up because they don't belong to the default project.

### Additional info

- Craft version: 2.6.2993
- PHP version: 7.1.1
- Database driver & version: MySQL 5.7
- Plugins & versions: this is core code - /craft/app/lib/GC.php

**Comment by andris-sevcenko** [comment]
Closing this one as it's a little bit outdated.
