### ISSUE TITLE
Multi-Site Permissions - Part 1 - List Filter

### ISSUE THREAD

**Issue by zmetcalf** [craftcms/cms#2057]
We are looking to add additional permission filtering based off of multi-sites in the control panel. What we had in mind was only showing entries that are enabled and able to edited by a user for a particular site. 

I believe we can filter the cp query by adding a hook here: https://github.com/craftcms/cms/blob/develop/src/base/Element.php#L437

I can submit a pull request if this is ok?

**Comment by brandonkelly** [comment]
> What we had in mind was only showing entries that are enabled and able to edited by a user for a particular site.

This should already be the case; if it’s not it’s probably a bug. Can you point me to where you’re seeing it?

**Comment by zmetcalf** [comment]
There are some permissions that block access to other sites a user is not assigned to. However, users can see all of the entries in the system. What we had in mind was blocking/delisting entries entirely if they were not enabled for the site. For example, in this image, this user can edit the Tennessee site, but we would actually want to block/delist it because it is not enabled. 

![29ab6bdc15e459020de02cd424ca0654](https://user-images.githubusercontent.com/1666893/32072940-ae35c89a-ba51-11e7-9031-c9467e70723d.png)

**Comment by brandonkelly** [comment]
Gotcha – so you want a new permission to access _enabled entries_ for the selected site. Users that don’t have it won’t see these entries, and if an entry needs to show up for the site, a user with the permission will need to access it and be the one to enable it.

If that permission did exist, it would affect both the index page and edit pages (#2058).

I’m not sure I want to include this directly in Craft though; seems like a pretty specific edge case that would make more sense as a plugin.

The plugin could prevent disabled entries from showing up on index pages by adding this JS to the page (if the user doesn't have the permission):

```javascript
Craft.defaultIndexCriteria.localeEnabled = true;
```

And the plugin could prevent access to site-disabled pages by using the `cp.entries.edit` template hook, checking their permission and the entry’s site status, and throwing a 403 error if they shouldn’t have access.

**Comment by zmetcalf** [comment]
Thank you very much for taking the time to help with this. Both the fixes worked great; have a great weekend!
