### ISSUE TITLE
Rethinking Color Fields (feature request)

### ISSUE THREAD

**Issue by proimage** [craftcms/cms#2059]
So I know most of you P&T devs probably use Macs and are unaware of this, but the native OS color picker on Windows is... horrific.

![image](https://user-images.githubusercontent.com/1027523/32074364-d403d314-baa1-11e7-81ca-dd7b84c66ca2.png)

I know, I know—"Who uses Windows??" Well, although the first-world web dev community may have largely converted over to Apple, many developers in less-developed regions—and many, many more clients—still use Windows. This means they have a horrible experience when given the chance to pick a color in Craft.

Not only that, but there's no way for a developer or designer to place any sort of restrictions on the color the client might pick, and if you think about it... that's a problem.

Both these issues can be resolved with one stone: a JS-based color picker—but with that well thought-out, P&T touch.

Beyond the typical/standard color wheel and RGB/HSL/transparency sliders that 99% of JS-based color pickers have, I envision a P&T color picker might have the enhancement of developer-applied restrictions to any or all of those color controls. Imagine being able to restrict a client's color choices to only those with a lightness over 128, a saturation of exactly 141, or even a predefined palette of colors straight from the company's style guide?

I know this probably won't be done for Craft 2.x, seeing as 3.0 is only a few months away, but I feel like relying on the native OS color picker is one of Craft's ugliest features (on Windows), and there's so much room for enhancement that it's a shame not to do this.

EDIT: And yes, I know Craft uses the browser color picker if it supports `<input type="color">`, and falls back to a JS picker otherwise, but that's exactly the problem. Browser-based color pickers in Windows rely on Windows' color picker... which was probably a good color picker—back in 1994.

**Comment by brandonkelly** [comment]
Is there a JS-based color picker that’s actually significantly better than that Windows one? If there is I haven’t seen it (and I’ve looked).

You might be better off just using a 3rd party color field type, such as [Color Swatches](https://www.viget.com/articles/craft-color-swatches-plugin) by Viget.

**Comment by proimage** [comment]
For one, the Windows color picker doesn't accept hexadecimal color values. Neither does it have any allowance for transparency. Finally, that whole "Color|Solid" bit harkens back to the days of 256-color limits and dithering. o.o It's ancient and decrepit, and is really jarring to see pop up amidst the carefully crafted beauty that is Craft.

But those are just the _problems_ with relying on the default browser/OS color picker. That's only half the reason behind the feature request. The other half—which is honestly the more exciting part—is the color restriction feature I outlined.

Let's put it this way. With matrix being so awesome in allowing clients to design their own unique pages, I think there really should be a way that goes hand-in-hand with that to allow them to pick from a restricted set or range of style-guide-approved colors. If they want to have a call-to-action section on one page that has a purple background, that's great, but they should be restricted to picking a purple hue from the company's style guide, which has been tested to work with the color palette in use on the entire site, shouldn't they?

I know I could make a custom drop-down of specific color values, but there's no visual aspect to that—no representation of the actual color itself.

**Comment by michaelrog** [comment]
@proimage Curious if you've tried my [Hue](https://github.com/TopShelfCraft/Hue) plugin, and if that color picker works any better for you? (FWIW, I'm planning to add support for limited color palettes as well, in the Craft 3 version, and I would happily accept your ideas/FRs about what customizations you'd like to have available when setting up color pickers for your sites.)

**Comment by brandonkelly** [comment]
The macOS color picker doesn’t accept hex values by default either; you have to install a 3rd party color palette like [Skala Color](https://bjango.com/mac/skalacolor/). I suppose I could see us beefing it up just a bit to support that. But I’m not interested in making any drastic changes to the field type, like giving you predefined options. Seems like that should be left for a plugin.

**Comment by proimage** [comment]
@michaelrog I haven't, but I will if I end up needing to. In general, I try to do as much as I can without using any plugins for the functioning of the sites I build (content import or field managing plugins, being strictly backend-only, are fine). Since the color picker that Craft hooks into is so anemic on Windows (it's virtually worthy of being categorized as a bug), I figured I'd combine a complaint with a suggested fix. :)

@brandonkelly I missed the link to [Color Swatches](https://www.viget.com/articles/craft-color-swatches-plugin); that does indeed cover the basics of what I had been thinking of with predetermined colors.

I still think Craft should intentionally bypass at least the Windows color picker... I mean, for Pete's sake, the current Windows 10 color picker basically _predates the Internet_, as it has remained largely unchanged since Windows 3.1 in 1992:

![image](https://user-images.githubusercontent.com/1027523/32099875-c662fde2-bb1a-11e7-9185-49877edd4fe4.png)

Anyway... is what's pictured on the Color Field docs page the JS picker, or the native MacOS one?

![image](https://user-images.githubusercontent.com/1027523/32099760-4db9cbdc-bb1a-11e7-9941-07168ee5f077.png)

**Comment by brandonkelly** [comment]
> Anyway... is what's pictured on the Color Field docs page the JS picker, or the native MacOS one?

That’s the native macOS one. The JS one is hideous.

**Comment by brandonkelly** [comment]
I ended up implementing a mix of this and #2061. As of Craft 3 RC1, Color fields will sport a new look, which will be consistent regardless of whether the browser supports `<input type="color">`:

<img width="152" alt="screen shot 2017-11-05 at 6 06 38 am" src="https://user-images.githubusercontent.com/47792/32415501-8706c88c-c1ef-11e7-8f9d-8424c124551c.png">

If the browser happens to support `<input type="color">`, then clicking on the color preview will open the browser’s native color picker. But that is now just a progressive enhancement thing; if you don’t want to use the browser’s color picker, you can still type in a hex value manually.

As an added bonus, the new input will support leaving the value blank, whereas previously it always saved a color value, defaulting to `#000000`.

**Comment by michaelrog** [comment]
If we leave the color field empty, can we get a `null` value?

**Comment by brandonkelly** [comment]
Yeah, that’s what I meant by that last sentence.

**Comment by michaelrog** [comment]
Cool! I may not need to port Hue after all! 🎉

**Comment by brandonkelly** [comment]
@michaelrog Looks like at this point Hue basically offers the following over Craft 3’s built-in Color field:

- default color setting (including `null`)
- `ColorModel` with some fancy template helper methods

Giving Color fields a default value has been requested before (#949), and would be pretty easy to add. The `ColorModel` looks a bit more involved. You cool if I steal your code?

**Comment by michaelrog** [comment]
You're more than welcome.

**Comment by proimage** [comment]
@brandonkelly Thanks for providing a hex field at least. :)

@michaelrog Note that Craft 3 will still be using the native browser/OS color picker, which—in Chrome on Windows—is hideous. So for those people with clients on Windows, it might be worth using Hue just for the user experience. ;)
