### ISSUE TITLE
Drop JS fallback for Color inputs

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/cms#2061]
Now that [basically everything](http://caniuse.com/#search=color) besides IE supports `<input type="color">`, we should remove the JS fallback, and just let a normal text input be shown for browsers that don’t support it.

**Comment by proimage** [comment]
Would this mean that IE users, who are often less tech-savvy than others, would just see and edit plain hexadecimal color values?

**Comment by brandonkelly** [comment]
Right, or upgrade to Edge.

**Comment by brandonkelly** [comment]
(We should either do this or implement a consistent JS color picker, a la #2059. But only interested in that if we can find/make a halfway decent JS color picker, which I’m doubtful of.)

**Comment by proimage** [comment]
[Spectrum](https://bgrins.github.io/spectrum/) looks good. I mean, by default it _looks_ very plain, but that's good because it makes it easier to apply styles to match the Craft backend.

Dare I say it even has a `showPaletteOnly` mode for those "restricted sets of colors" situations...? ;)

**Comment by takobell** [comment]
Spectrum looks fairly abandoned.  127 open issues, 43 open pull requests, just 1 commit this year which was a license change.  https://github.com/bgrins/spectrum

**Comment by proimage** [comment]
Ahh, true... didn't think to check repo activity.

**Comment by brandonkelly** [comment]
Resolved for Craft 3 RC1 per https://github.com/craftcms/cms/issues/2059#issuecomment-341975881
