### ISSUE TITLE
`docsUrl` isn't a thing anymore in Craft 3 AdminCP templates

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#2067]
Craft 3 beta 29

It used to be that your plugin could do something like:
```
{% set docsUrl = "https://github.com/nystudio107/craft3-instantanalytics/blob/master/README.md" %}
```

And that'd be linked to via a `(?)` icon at the bottom of the page.  It doesn't appear that Craft 3 utilizes this convention anymore; not sure if this is intentional or not.

I did a search of the codebase, and Craft 3 itself is still setting `docsUrl` in a number of places:

![phpstormscreensnapz019](https://user-images.githubusercontent.com/7570798/32109131-c516b92e-bb01-11e7-83b0-5fb866a85f05.png)

**Comment by brandonkelly** [comment]
You are actually looking at RC1 code, which currently doesn’t do anything with it. We’re on the fence so haven’t removed the variables in the templates yet.
