### ISSUE TITLE
Missing users.onBeforeSaveUser and users.onSaveUser Events

### ISSUE THREAD

**Issue by davist11** [craftcms/cms#2068]
### Description
I'm working on converting [Pending User](https://github.com/vigetlabs/craft-pendinguser) to Craft 3, and I can't seem to find the `users.onBeforeSaveUser` or `users.onSaveUser` events. Are there different events I should be using instead?

### Additional info

- Craft version: 3.0.0-beta.29

**Comment by brandonkelly** [comment]
Yep; both the Elements service and individual element types (e.g. User) have before/after save events:

- `craft\services\Elements::EVENT_BEFORE_SAVE_ELEMENT`
- `craft\services\Elements::EVENT_AFTER_SAVE_ELEMENT`
- `craft\base\Element::EVENT_BEFORE_SAVE` (cancellable)
- `craft\base\Element::EVENT_AFTER_SAVE`

for example,

```php
use craft\base\Element;
use craft\elements\User;
use craft\events\ModelEvent;
use yii\base\Event;

Event::on(User::class, Element::EVENT_BEFORE_SAVE, function(ModelEvent $event) {
    /** @var User $user */
    $user = $event->sender;

    // prevent the user from getting saved by setting...
    $event->isValid = false;
});
```

**Comment by davist11** [comment]
Ah perfect. Thanks Brandon.
