### ISSUE TITLE
Plugins: Sidebar name doesn't respect `getName()`

### ISSUE THREAD

**Issue by engram-design** [craftcms/cms#2069]
### Description
Forgive me if I might be a little out of date with this discussion (if its already been had). Still learning!

If plugins wanted to change the name of the plugin in the main sidebar menu through config settings, it doesn't seem to be possible. This is particularly useful for Feed Me, as people often like to change it to something a little more professional.

Right now, you can change the `getName()` function to something else, and it won't update the menu

```
public function getName()
{
    return 'Crazy Plugin Name';
    
    // Ideally, we want this:
    return Craft::t('feed-me', $this->getSettings()->pluginName);
}
```

There is one way around this for the moment, by directly modifying the `getCpNavItem()` function.

```
public function getCpNavItem()
{
    $navItem = parent::getCpNavItem();
    $navItem['label'] = $this->getName();
    return $navItem;
}
```

Maybe the plugin is loaded before it has a chance to first fetch any config settings? What is the correct approach here?

**Comment by brandonkelly** [comment]
Plugins don’t have a `getName()` method in Craft 3; just a `$name` property ;)

**Comment by engram-design** [comment]
@brandonkelly Aw man, sorry about that. Carry on!
