### ISSUE TITLE
UI: Multisite doesn't handle large numbers of sites very well

### ISSUE THREAD

**Issue by mattcdavis1** [craftcms/cms#2070]
In a case where an organization has hundreds of chapters and each chapter has their own home page, event page, about page etc. it is useful to create a site for each chapter.  However, the current UI doesn't handle large numbers of sites very well as the dropdown is not paginated or filterable. 

For most users, they would only need to see their site and the main site, however admins would need to see everything and the current UI just doesn't work well for this.

https://goo.gl/r1iLN3

Also, it would be nice to have an "All Sites" view of a channel for admins.

**Comment by brandonkelly** [comment]
We’ve made a few improvements to sites in Craft 3 RC1, such as:

- “Site Groups” – similar to Field Groups, and will give you a way of organizing your sites into logical groups.
- The Entries index will only show the sections that are enabled for the selected site.
- The sites on Edit Entry/Category pages are now listed in the context menu next to the entry title

After RC1 is out, if you still have any suggestions we would love to hear them! But please submit each feature request as its own GitHub issue, as we like to reference issue #’s when implementing the changes. Thanks!

**Comment by mattcdavis1** [comment]
great! thanks for the response.  look forward to checking out RC1 when it's released.
