### ISSUE TITLE
Can't change Tags field layout tab names, or add new tab?

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#2071]
### Description

This may belong on the bucket list, as checking, find you can't do these things on Craft 2 either. So maybe nobody uses fields on Tags. I'm trying just in testing for an unusual plugin which might  manipulate on such values, so.

### Steps to reproduce

1. try to edit field layout on a new Tags group. Can't do it, nor can you add a new tab -- no button.
2. 

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Tag groups’ field layout tabs are not editable (same with Users and Global Sets – at least until Craft 3 RC1). You should be able to add new fields to the existing tab though.

**Comment by narration-sd** [comment]
Sounds good, hadn't expected an upgrade coming.

Yes, adding fields from current groups worked -- cheers.
