### ISSUE TITLE
Feature Request: Possibility to overwrite Thumb Url

### ISSUE THREAD

**Issue by swey** [craftcms/cms#2073]
I like the solution to overwrite asset urls via `GetAssetUrlEvent`, but miss the possibility to do that for thumbnails. Would be really awesome to have it here as well.

See the asset url solution: https://github.com/craftcms/cms/blob/develop/src/services/Assets.php#L547-L557

Thank you!

**Comment by brandonkelly** [comment]
@andris-sevcenko Could probably reuse the GetAssetUrlEvent class for this.
