### ISSUE TITLE
[Bug] Image Thumb Breaks if Selected Too Soon

### ISSUE THREAD

**Issue by mattcdavis1** [craftcms/cms#2075]
### Description
When uploading an asset if you select it before the thumbnail has loaded in the upload modal, the image will show up broken in the field.  In my case i'm using an S3 Volume with Cloudfront as a based URL (not sure if that affects things).  I'm also using a matrix in the context of this particular issue (probably happens in non-matrix as well).

### Steps to reproduce

1. Create a single with a matrix field type that has an asset field type
2. Upload a file and select it as soon as it is available for selection (before the thumbnail has had a chance to render)

Screenshot: https://goo.gl/xotHcc

### Additional info

- Craft version: 3.0.0-beta.29
- PHP version: 7.0
- Database driver & version: Mysql
- Plugins & versions: "craftcms/aws-s3": "^1.0"

**Comment by mattcdavis1** [comment]
Yes - i'm still able to reproduce this.  It's easier to reproduce with a larger file.

https://goo.gl/UcZteV

**Comment by andris-sevcenko** [comment]
Definitely no longer an issue with Craft 4 :)
