### ISSUE TITLE
[Bug] _createBlocksFromSerializedData assumes web context, fails in console

### ISSUE THREAD

**Issue by mattcdavis1** [craftcms/cms#2079]
### Description
I have a migration that imports content from a previous site via a craft migration using a console command.  Using the below code to import Matrix content throws an error "`Calling unknown method...Request::getIsLivePreview`".  The `getIsLivePreview` method is not a member of the `craft\console\Request` class so this fails.  Probably just need a dummy method that returns false.  I'm assuming the below code is the proper way to handle importing matrix content.

```php
$craftEntry = $someEntryIJustSaved;
$products = OldDatabaseModel::find()->where(['foreign_key' => $someValue])->all();
$matrixFieldValues = [];
$i = 1;

foreach ($products as $product) {
    $matrixFieldValues["new{$i}"] = [
        'type' => 'product',
        'enabled' => 1,
        'fields' => [
            'productTitle' => $product->name,
            'description' => $product->body,
            'amount' => $product->amount,
            'pdfs' => '',
        ],
    ];

    $i++;
}

$craftEntry->setFieldValue('products', $matrixFieldValues);

Craft::$app->getElements()->saveElement($craftEntry)
```

### Steps to reproduce

1. Create an entry with matrix content from the console context.

### Additional info

- Craft version: 3.0.0-beta.29
- PHP version: 7.0
- Database driver & version: Mysql
- Plugins & versions: "craftcms/aws-s3": "^1.0"

For a temporary workaround i am using the following:

```php
Craft::$app->getRequest()
    ->attachBehavior('live.preview', new class() extends \yii\base\Behavior {
        public function getIsLivePreview() { return false; }
    });
```

**Comment by takobell** [comment]
This should be fixed in [beta 30](https://github.com/craftcms/cms/blob/develop/CHANGELOG-v3.md#300-beta30---2017-10-31) already via https://github.com/craftcms/cms/pull/2020

**Comment by mattcdavis1** [comment]
yep - thanks!
