### ISSUE TITLE
Distribute craft console bin as a composer vendor binary

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#2080]
Seems like the `craft` console binary should be defined as a [vendor binary](https://getcomposer.org/doc/articles/vendor-binaries.md), and thus would be available at `[composer_dir]/bin` on install.

Example in Yii: https://github.com/yiisoft/yii2/blob/master/composer.json#L106-L108

**Comment by brandonkelly** [comment]
The `craft` executable is provided by the [craftcms/craft](https://github.com/craftcms/craft) _project_ (not by a dependency), so Composer wouldn’t save a symlink of it to `bin/` even if we did mark it as a vendor binary in composer.json.

> ## What happens when Composer is run on a composer.json that defines vendor binaries?
> 
> For the binaries that a package defines directly, nothing happens.

**Comment by timkelty** [comment]
Thanks for the explanation!
