### ISSUE TITLE
Return value of craft\services\Elements::_getRefTokenReplacement() must be of the type string, null returned

### ISSUE THREAD

**Issue by acehead** [craftcms/cms#2082]
### Description

When opening an entry for editing technical error occured

### Steps to reproduce

1. Open entry for editing (click on it)
2. Internal Server Error
Return value of craft\services\Elements::_getRefTokenReplacement() must be of the type string, null returned

### Additional info

- Craft version: Craft Pro 3.0.0-beta.30
- PHP version: 7.1.9
- Database driver & version: PostgreSQL 9.6.2
- Plugins & versions:

**Comment by brandonkelly** [comment]
I can’t reproduce this, but looking at the code I think I know how the error could have occurred, and fixed that. Try running the following terminal command:

    composer require craftcms/cms:"dev-develop as 3.0.0-beta.99"

and then let me know if the error goes away. Thanks!

**Comment by acehead** [comment]
Hi, just tried it out, the problem went away. Thanks!
Looking forward getting new official release with this fix included.

**Comment by brandonkelly** [comment]
Great, thanks for letting me know!
