### ISSUE TITLE
Yii Toolbar Fails to load

### ISSUE THREAD

**Issue by sergeifilippov** [craftcms/cms#2083]
### Description

After enabling devmode, I expected to see the Yii debug toolbar in the admin. Instead I got this in the console:

http://craft3.local/actions/debug/default/toolbar?tag=59fbed7372614

```
HTTP 400 – Bad Request – yii\web\BadRequestHttpException
Missing required parameters: tag
```
![400 bad request 2017-11-03 17-27-07](https://user-images.githubusercontent.com/123676/32360603-5cb0f2a8-c0bc-11e7-84a6-b79665eb09d0.png)

### Steps to reproduce

1. Enable Devmode
2. Login to admin.

### Additional info

- Craft version: Craft CMS 3.0.0-beta.30
- PHP version: 7.1.11
- Database driver & version: MySql 5.6
- Plugins & versions: None

This is my php configuration in nginx.conf:

```nginx
  1     location ~ \.php$ {
  2
  3         fastcgi_split_path_info ^(.+\.php)(/.+)$;
  4         gzip off;
  5         expires off;
  6         try_files $uri =404;
  7         
  8         fastcgi_pass php71;
  9
 10         include /usr/local/etc/nginx/fastcgi_params;
 11
 12         # set dev env value
 13         fastcgi_param APPLICATION_ENV "development";
 14
 15         fastcgi_index  index.php;
 16         fastcgi_ignore_client_abort off;
 17         fastcgi_buffers 16 16k;
 18         fastcgi_buffer_size 32k;
 19         fastcgi_read_timeout 300;
 20         fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
 21     }
```

**Comment by brandonkelly** [comment]
The Debug Toolbar doesn’t require Dev Mode to be enabled, so the only thing that probably changed when you enabled it is you got a more verbose error message & stack trace.

What is the request URI and query string / form data params for the request where you’re getting that error?

**Comment by sergeifilippov** [comment]
Thanks @brandonkelly!

The request uri is `/actions/debug/default/toolbar?tag=59fc5abf8d12a`.

```
Bad Request: Missing required parameters: tag
```

![yii-debug](https://user-images.githubusercontent.com/123676/32373092-686ae848-c0fc-11e7-964c-1982349ab39e.gif)

**Comment by brandonkelly** [comment]
Try creating a new template (e.g. `test.twig`) with this:

```twig
<pre>tag: {{ craft.app.request.getQueryParam('tag') }}</pre>
```

Then load it in your browser, with the query string `?tag=foo`. What gets output in your browser?

**Comment by sergeifilippov** [comment]
`http://craft3.local/admin/dashboard?tag=foo` returns nothing ☹️ 

<img width="227" alt="dashboard - haiku lab 2017-11-05 09-48-58" src="https://user-images.githubusercontent.com/123676/32409327-90e334ac-c20e-11e7-9d37-01035cad67b5.png">

**Comment by brandonkelly** [comment]
In that case it’s some sort of environmental issue – maybe your `.htaccess` file is dropping query strings when redirecting to `index.php` (assuming you’re on Apache.)

**Comment by sergeifilippov** [comment]
I'm on nginx.

I'll have a look and report back if this is the case.

Do you have a "blessed" nginx configuration file to test with? @brandonkelly

**Comment by narration-sd** [comment]
@sergeifilippov  I think this from Andrew  -- @khalwat here,-- is quite well thought of:

https://github.com/nystudio107/nginx-craft

It may be over-elaborate for what you want, but you can just use the parts you need. Also, Andrew is very helpful on such things on CraftCMS Slack -- best to ask on the #devops channel, and meniton him as @nystudio107 there.

**Comment by sergeifilippov** [comment]
The issue was definitely due to nginx misconfiguration.

Tracked it down to missing definition of:

```nginx
    # Craft-specific location handlers to ensure AdminCP requests route through index.php
    # If you change your `cpTrigger`, change it here as well
    location ^~ /admin {
        try_files $uri $uri/ /index.php?$query_string;
    }
    location ^~ /cpresources {
        try_files $uri $uri/ /index.php?$query_string;
    }
```

**Comment by brandonkelly** [comment]
Glad you got it sorted @sergeifilippov!
