### ISSUE TITLE
`DateTime::uiTimestamp` returns invalid description in early morning

### ISSUE THREAD

**Issue by msbit** [craftcms/cms#2086]
### Description

If I call `DateTime::uiTimestamp` early in the morning (AEDT) the results are incorrect for recent `DateTime`s.

For a date the day before last, it returns `Yesterday`, whereas for yesterday it returns the name of the day. I've observed this behaviour at ~7:45 AM and ~12:15 AM.

Debugging through this, it appears to be due to a call to:

```
strtotime('yesterday')
```

at `DateTimeHelper.php:287` which returns the UTC timestamp of midnight, the day before last (ie calling now 2017-11-04 00:25+11:00 results in 1509580800, or 2017-11-02 00:00+00:00).

You might be able to replace with:

```
(new DateTime('yesterday', new \DateTimeZone(craft()->getInfo('timezone'))))->getTimestamp()
```

which (called around the same time) returns 1509627600, or 2017-11-02 13:00+00:00 / 2017-11-03 00:00+11:00.

### Steps to reproduce

1. Be in Australia
2. Call `DateTime::uiTimestamp` early in the morning (probably before 11:00 AM this time of year)

### Additional info

- Craft version: 2.6.2994
- PHP version: 7.0.24

**Comment by brandonkelly** [comment]
Thanks! Fixed and I didn’t even have to fly to Australia :)
