### ISSUE TITLE
Overwriting volumes through PHP does not make changes to database table.

### ISSUE THREAD

**Issue by c4milo** [craftcms/cms#2094]
### Description
I'm currently creating a simple S3 volume without any AWS configuration. Then, during deployment, I'm attempting to overwrite and add missing values. The values show up correctly in the CP. However, when I look at the volumes table in Postgres, I don't see any of the changes. 

### Steps to reproduce

1. Create a S3 volume only setting its name. 
2. Overwrite it using volumes.php, adding missing information such as AWS credentials, S3 bucket, etc. 

### Additional info

- Craft version: 3.0.0-beta.29
- PHP version: 7.1.10
- Database driver & version:  PostgreSQL 9.6.5
- Plugins & versions: 
aws-s3: 1.0.6
element-api: 2.4.3

**Comment by brandonkelly** [comment]
That is expected behavior. The DB will only be updated if you click the Save button from the volume’s settings page.
