### ISSUE TITLE
Slug conversion to ASCII does not work when using custom title

### ISSUE THREAD

**Issue by steveooo9** [craftcms/cms#2096]
### Description
Auto-generate slugs (conversion from ä-ö-ü-ß => ae-oe-ue-ss) from a title does work, but defining a title like `{entryField.first().title}` doesn't convert the äüöß, but removes them.

### Steps to reproduce

1. Define auto title like `{entryField.first().title}`
2. Remove previously generated slug
3. Save a title with "öäüßÖÄÜ" and see that everything non-ASCII get's removed instead of converted

If you can't reproduce, I am glad to help in any further bugfixing!

**Comment by brandonkelly** [comment]
What version of Craft are you seeing this in?

**Comment by steveooo9** [comment]
@brandonkelly I am using Craft CMS 2.6.2989

**Comment by brandonkelly** [comment]
Just tested and I’m not able to reproduce on 2.6.2997. Can you try updating and see if that helps?

The only thing I can think of is, maybe you enabled the `limitAutoSlugsToAscii` config setting in craft/config/general.php? Although if you had, it should have affected the auto-generated slug as well.

**Comment by steveooo9** [comment]
@brandonkelly I am unable to test in the most recent version at the moment..

I have following in my general.php: ```    'omitScriptNameInUrls' => true,
    'limitAutoSlugsToAscii' => true,
    'convertFilenamesToAscii' => true,```

**Comment by brandonkelly** [comment]
`'limitAutoSlugsToAscii' => true` is your problem. You are telling Craft to downgrade/discard anything but plain ASCII characters in slugs.

**Comment by steveooo9** [comment]
@brandonkelly But when I set this to true, I can't convert my characters, right?

But this conversion from ä => ae and such did work before and must work. Where do I control these character conversions?

**Comment by steveooo9** [comment]
@brandonkelly It seems that the logic from the `limitAutoSlugsToAscii` setting (discard anything but ASCII chars) is being applied before some other character conversions (e.g. ä => ae)?

**Comment by brandonkelly** [comment]
@steveooo9 Tested both and both were converting correctly for me. Possible you added that config setting _after_ the initial entry had been saved?

**Comment by brandonkelly** [comment]
There are two places that config setting is taken into account – in the CP JavaScript, when auto-populating the Slug value as you type in the Title field, and in the PHP when the entry is being saved.

**Comment by takobell** [comment]
I'm not able to reproduce this on a stock Craft install, either.  The `limitAutoSlugsToAscii` config settings calls [`StringHelper::asciiString($str)`](https://github.com/pixelandtonic/Craft-Release/blob/master/app/helpers/StringHelper.php#L278), which uses the Craft [default ASCII character mappings](https://github.com/pixelandtonic/Craft-Release/blob/master/app/helpers/StringHelper.php#L217-L233), but also factors in any custom ASCII character mappings via the [`customAsciiCharMappings`](https://craftcms.com/docs/config-settings#customAsciiCharMappings) config setting.  Are you setting any custom mappings via that last config setting?

**Comment by steveooo9** [comment]
@takobell Can it be that when using auto title via `entry.first().title`somehow a step is missing? Is seems that without it everything get's lowercased and ASCII get mapped. Maybe with the first one, only it get's ASCII mapped but not lowercased. In Craft's `asciiString` method, there's no conversion for uppercase ÖÄÜ, so maybe there's an issue?

**Comment by brandonkelly** [comment]
@steveooo9 Try this for me… open up craft/app/helpers/ElementHelper.php and replace your `setValidSlug()` method with this:

```php
public static function setValidSlug(BaseElementModel $element)
{
	$slug = $element->slug;

	if (!$slug)
	{
		// Create a slug for them, based on the element's title.
		// Replace periods, underscores, and hyphens with spaces so they get separated with the slugWordSeparator
		// to mimic the default JavaScript-based slug generation.
		$slug = str_replace(array('.', '_', '-'), ' ', $element->title);

		// Enforce the limitAutoSlugsToAscii config setting
		if (craft()->config->get('limitAutoSlugsToAscii'))
		{
			if (!craft()->config->get('allowUppercaseInSlug'))
			{
				// Do this now because our ASCII character mappings are lowercase only.
				$slug = mb_strtolower($slug);
			}

			$slug = StringHelper::asciiString($slug);
		}
	}

	$element->slug = static::createSlug($slug);
}
```

**Comment by steveooo9** [comment]
@brandonkelly Yep, this works great! Great fix!

**Comment by brandonkelly** [comment]
Awesome, thanks for letting me know. We’ll get that fix into the next release.

**Comment by steveooo9** [comment]
@brandonkelly Great!
