### ISSUE TITLE
Feature request: easy access to the toggle for expand/collaspe block

### ISSUE THREAD

**Issue by orangethread** [craftcms/cms#2097]
I am getting fairly heavy into the page design and accessing what I call Page Blocks. It is crazy how often I expand/collapse a field within the block. I would love it if the expand/collapse toggle wasn’t hidden in the menu but pulled out for an easier click.

I have attached a screen grab to help explain.
![craft ux suggestion](https://user-images.githubusercontent.com/33496311/32568642-de9c4046-c48c-11e7-85a8-a9b53326d47e.png)

**Comment by brandonkelly** [comment]
There already is a shortcut for expanding/collapsing a block – just double-click on its title bar ;)

**Comment by orangethread** [comment]
I had no idea!

thanks!
