### ISSUE TITLE
Calling QueueController/actionRun when runQueueAutomatically is disabled

### ISSUE THREAD

**Issue by putyourlightson** [craftcms/cms#2104]
### Description

If `runQueueAutomatically` is set to false then how can the `actionRun` method be called in `QueueController` through a cron job? It seems that the following code returns a response and prevents the queue from running.

```
// Make sure Craft is configured to run queues over the web
if (!Craft::$app->getConfig()->getGeneral()->runQueueAutomatically) {
   return $response;
}
```

[https://github.com/craftcms/cms/blob/b3ec1ad47c14608d916fe72da36f36676894d29b/src/controllers/QueueController.php#L78](https://github.com/craftcms/cms/blob/b3ec1ad47c14608d916fe72da36f36676894d29b/src/controllers/QueueController.php#L78)

### Additional info

- Craft version: 3.0.0-beta.34

**Comment by brandonkelly** [comment]
The different options for running the queue are documented here: https://github.com/yiisoft/yii2-queue/blob/master/docs/guide/worker.md

**Comment by putyourlightson** [comment]
So am I correct in assuming that this should be as follows for a cron job?

`* * * * * /usr/bin/php /my_project_path/craft queue/run`

That gives me the following error:

`parse error in /my_project_path/vendor/craftcms/cms/bootstrap/bootstrap.php on line 104`

**Comment by takobell** [comment]
Sounds like `/usr/bin/php` isn't PHP 7?

**Comment by putyourlightson** [comment]
Ah you're right, I grabbed the line of code from the docs and forgot to change the path to PHP. Working now, thanks!!
