### ISSUE TITLE
Unknown Error when Migrating DB

### ISSUE THREAD

**Issue by zmetcalf** [craftcms/cms#2106]
### Description
On our production server, we are running into an issue when migrating the DB from version 30->31 (any migration really). The issue seems to happen before anything gets called in the UpdaterController (except init) For example, the force update action is never called when it should. This issue only occurs on our production server; the updates work fine locally. We also have backupOnUpdate set to false, too. 

![image](https://user-images.githubusercontent.com/1666893/32740629-bba5ae38-c860-11e7-99cf-915ba862e7dc.png)

The only thing of interest in the logs is this:
![image](https://user-images.githubusercontent.com/1666893/32741260-d6aab1e0-c862-11e7-896b-8b50dcfa6f07.png)

Do you all have any ideas how to debug this better? 

### Additional info

- Craft version: 30
- PHP version: 7.1.8
- Database driver & version: MySQL 5.5.5-10.2.10-MariaDB-10.2.10+maria~jessie
- Plugins & versions: Element API 2.4.3

**Comment by brandonkelly** [comment]
Do you have anything in `storage/logs/phperrors.log` ?

**Comment by zmetcalf** [comment]
No errors were reported in that log.

**Comment by brandonkelly** [comment]
Open your browser’s Network console before running the update. What URL / params are requested when that fatal error response comes back?

**Comment by zmetcalf** [comment]
Oh, I get it now, the AJAX is posting to http instead of https so it is creating these errors: 
![image](https://user-images.githubusercontent.com/1666893/32743274-288907a4-c869-11e7-8a9f-1dec5c5936fc.png)

Is this your code or my configuration?

**Comment by takobell** [comment]
Are you forcing http or https rewrites in your .htaccess file on production?  If so, double check where you're defining Craft's siteUrl and make sure that it's consistent with what you're rewriting to.

**Comment by zmetcalf** [comment]
Thank you all of taking the time to help me trace the issue. I have it from here.

**Comment by zmetcalf** [comment]
Just as a follow up, Yii 2.0.13 made some changes in their recent upgrade that created this issue: 

The `yii\web\Request` class allowed to determine the value of `getIsSecureConnection()` form the
    `X-Forwarded-Proto` header if the connection was made via a normal HTTP request. This behavior
    was insecure as the header could have been set by a malicious client on a non-HTTPS connection.
    With 2.0.13 Yii adds support for configuring trusted proxies. If your application runs behind a reverse proxy and relies on
    `getIsSecureConnection()` to return the value form the `X-Forwarded-Proto` header you need to explicitly allow
    this in the Request configuration. See the [guide](http://www.yiiframework.com/doc-2.0/guide-runtime-requests.html#trusted-proxies) for more information.
  
    This setting also affects you when Yii is running on IIS webserver, which sets the `X-Rewrite-Url` header.
    This header is now filtered by default and must be listed in trusted hosts to be detected by Yii:
  
    ```php
    [   // accept X-Rewrite-Url from all hosts, as it will be set by IIS
        '/.*/' => ['X-Rewrite-Url'],
    ]
    ```

**Comment by zmetcalf** [comment]
How do you set this in craft? Do you create a config/app.php file? @brandonkelly

**Comment by brandonkelly** [comment]
Ah we considered that might be the culprit, but ruled it out because we assumed you would still get some sort of response. Apparently not!

Beta 34 [added](https://github.com/craftcms/cms/blob/develop/CHANGELOG-v3.md#300-beta34---2017-11-09) a few new config settings for those new Request properties. And Beta 35 is going to set the default `trustedHosts` setting value to `['any']`, so by default you will have the same behavior as pre-Yii 2.0.13.

For the time being, open up config/general.php and add this:

```php
'trustedHosts' => ['any'],
```

**Comment by zmetcalf** [comment]
Awesome, thank you!
