### ISSUE TITLE
Craft admin screen freezing when Lists button is selected

### ISSUE THREAD

**Issue by craftster** [craftcms/cms#2109]
### Description

Craft admin screen freezing when the button for ordered and unordered list is selected during content creation, causing the screen to go blank and data loss. 

### Steps to reproduce

1. Create a new entry with a Rich Text field with the Lists buttons active.
2. Add three or four lines of text.
3. Select all the lines.
4. Click on the Unordered or Ordered List button in the Redactor toolbar.

**Comment by brandonkelly** [comment]
Was able to reproduce this on https://imperavi.com/redactor/. We’ll submit a bug report to Imperavi.
