### ISSUE TITLE
Slow performing queries for globally cached tags on the craft_templatecaches table

### ISSUE THREAD

**Issue by rungta** [craftcms/cms#2110]
### Description

Querying for template caches that are created using the `globally` keyword (hence, without a `path` component) is not optimised. Example query:

```sql
SELECT * FROM `craft_templatecaches` WHERE `cacheKey` = 'my-global-cache-key' AND `locale` = 'en_in' AND `expiryDate` >= '2017-11-16'
```

Running an `EXPLAIN` on the above query reveals the `craft_templatecaches_locale_fk` index being used. This covers just the `locale` clause, leading to a full scan on the remaining rows. We were noticing 300% average CPU usage by the MySQL process on a site with about 6500 entries / 126,000 elements / 5000 templatecaches on an 8GB / 4 core VPS. The high CPU usage was consistent for the time we were monitoring the server.

After repeatedly noticing the `craft_templatecaches` queries in the `SHOW PROCESSLIST` we added a new index to the table with _just_ the `cacheKey`, `locale` and `expiryDate` columns. CPU usage immediately dropped from an average of 300% to a meagre 10%. It has been 24 hours since this index was added and CPU usage has remained low, at the levels we expected for the traffic the site is receiving.

We had encountered this issue on an earlier project as well and reported it on the old feedback site.

### Steps to reproduce

1. Create a lot of template caches in the `craft_templatecaches` table.
2. Run the example query shared above and profile the time and MySQL resource (mainly CPU) usage.
3. Add a new index to `craft_templatecaches` with just `cacheKey`, `locale` and `expiryDate`
4. Run the same query and profile the time and MySQL resource usage.

### Additional info

- Craft version: 2.6.2997
- PHP version: 7.1
- Database driver & version: mysql Ver 14.14 Distrib 5.7.20, for Linux (x86_64)

**Comment by takobell** [comment]
I couldn't reproduce the performance issue with a 100k element table and 25k templatecaches table, but the EXPLAIN does reveal it's much more efficient with the new index, so went ahead and added it for the next release.  Thanks!

**Comment by rungta** [comment]
Hey @takobell, just got around to installing v2998 on the production server. I deleted the index we’d manually added (now that Craft added it’s own), but noticed the MySQL CPU usage shoot up from ~50% to ~350% right after removing the old index.

After some frantic debugging, TIL that the [order of columns in a MySQL (or any BTREE) index matters](https://www.percona.com/blog/2009/06/05/a-rule-of-thumb-for-choosing-column-order-in-indexes/). The Craft index column of `expiryDate, cacheKey, locale` isn’t getting us significant performance boosts. Instead, re-ordering the columns to `cacheKey, locale, expiryDate` brings the CPU usage back from ~350% to 50%. This is probably because filtering by the `cacheKey` column drastically reduces the result set down to essentially one row. So I’ve altered the column order in the index. You might want to do the same.

This makes me think that the previously existing `craft_templatecaches_expiryDate_cacheKey_locale_path_idx` index might also benefit from a column re-order.

**Comment by takobell** [comment]
TIL I learned something too, then.  Changed the order of that index as well as the `craft_templatecaches_expiryDate_cacheKey_locale_path_idx` index for the next release.
