### ISSUE TITLE
setPasswordPath being ignored in email

### ISSUE THREAD

**Issue by jerome2710** [craftcms/cms#2111]
It seems that `setPasswordPath` is being ignored in Craft 2.6.2997. I am trying to use a custom URL for the front-end only requests with a user who has no access to the CP. Craft still adds the original URL to the email.

`setPasswordPath` does not pop up in the stack-trace of the `users/sendPasswordResetEmail` action:
- `UsersController->actionSendPasswordResetEmail()`
- `UsersService->sendPasswordResetEmail()`
- `UsersService->getPasswordResetUrl()`
- `UsersService->_getUserUrl`

Ref: https://craftcms.com/docs/config-settings#setPasswordPath

**Comment by takobell** [comment]
The link in the email will always point to an action on the UsersController.  It's when you click on the link the action in the email will take the `setPasswordPath` config setting into account.  https://github.com/craftcms/cms/blob/develop/src/controllers/UsersController.php#L1637

That behavior is the same for Craft 2 and 3.
