### ISSUE TITLE
Craft template cache doesn't save added resources by plugins

### ISSUE THREAD

**Issue by Rias500** [craftcms/cms#2115]
### Description
When using the `{% cache %}` tag around your whole template (which I'm using to do static caching), Craft doesn't seem to include css/js resources added by plugins.

### Steps to reproduce

1. Add a `{% cache %}` tag around all the template logic
2. Check the cache entry in the database
3. Notice that plugin resources are not added

### Additional info

- Craft version: 2.6.2997
- PHP version: 7.1
- Database driver & version: Mysql

**Comment by andris-sevcenko** [comment]
As [noted in the documentation](https://craftcms.com/docs/templating/cache#when-to-use-cache-tags), `{% cache %}` will only cache HTML.
