### ISSUE TITLE
Call to a member function getStatus() on boolean

### ISSUE THREAD

**Issue by iliaivanov** [craftcms/cms#2117]
### Description
`Call to a member function getStatus() on boolean` exception was thrown from `cms/vendor/craftcms/cms/src/elements/User::findIdentity` method. Unfortunately can't provide any steps how to reproduce it, because I got when was trying to migrate data from mysql to postgre. It looks like first `if` statement's condition will be passed when `$user` is false. Also according to the `UserQuery::one` method docs, it returns `false` on empty result. So this condition can pass `$user` variable with `false` value through. This is not a real bug I think, but could lead to some problems I guess.

### Additional info
- Craft version: 3.0.0-beta.28
- PHP version: 7.1

**Comment by brandonkelly** [comment]
We actually just caught & fixed this for the next release, in the process of implementing #2105 :)

**Comment by iliaivanov** [comment]
Hah cool! :)
