### ISSUE TITLE
Live Preview with Angular 1.6

### ISSUE THREAD

**Issue by jamesmusgrave** [craftcms/cms#2120]
### Description

I’m trying to develop a site using Craft 3 and Angular 1.6.

The Angular app works correctly within the live preview window. However when I edit the content and the POST request is made to update the preview I get the error

WARNING: Tried to load angular more than once.

This causes the angular app to become detached from the DOM. 

Have you encounter this issue before?

Could I ask what is exactly happening within the Live Preview window? I can see a POST request is happening. Is DOM being injected using JS? Is there anything I could do to force a full page refresh within the iFrame with the new content?

Is it possible to get live preview content via the Element API?

### Steps to reproduce

1. Bootstrap basic angular app (no router)
2. Edit page using Live Preview

### Additional info

- Craft version: Craft Pro 3.0.0-beta.34
- PHP version: 7.1.11
- Database driver & version: MySQL 5.7.20
- Plugins & versions: 
Amazon S3 1.0.7
Element API 2.5.1
Mix 1.3.0
NSM Fields 0.0.4
Amazon SES 1.0.0

**Comment by brandonkelly** [comment]
This has been resolved for the next 3.2 Alpha release!
