### ISSUE TITLE
New strings for translation: duplicates with existing strings in previous file (updated)

### ISSUE THREAD

**Issue by ebeauchamps** [craftcms/cms#2121]
'Find and replace' was added
but 'Find and Replace' already was in the file
Which one can be deleted ?

*******updated
_'Updating children' already was in the file_ : no, deleted in a previous commit, my bad
_'Resaving all elements' already was in the file_ : no, deleted in a previous commit, my bad
_'Resaving all localizable elements' already was in the file_ : no, deleted in a previous commit, my bad
_'Working in Matrix field “{field}”' already was in the file_ : no, deleted in a previous commit, my bad
*******/updated

'Clear caches' was added
but 'Clear Caches' already was in the file
Which one can be deleted ?

'Edit image' was added
but 'Edit Image' already was in the file
Which one can be deleted ?

'Clear all' was added
but 'Clear All' already was in the file
Which one can be deleted ?

**Comment by ebeauchamps** [comment]
Update:

'City' was added in a previous commit but apparently 'City/town' wasn't deleted

**Comment by takobell** [comment]
Thanks, @ebeauchamps.  Just had some big updates to all of the languages over on the RC1 branch: https://github.com/craftcms/cms/tree/release/3.0.0-RC1

I believe most/all of theses have been addressed there.  But I'd probably do any checking/comparisons on that branch until we officially release RC1 next week, at which point the develop branch will be caught up again.  Feel free to open a new issue for anything you find.

**Comment by ebeauchamps** [comment]
NEW:
I can find both 'Install Craft CMS' and 'Install Craft'

**Comment by ebeauchamps** [comment]
@takobell  Hello Brad, did you have a chance to read the above? thanks.

**Comment by takobell** [comment]
@ebeauchamps 

> 'Last login' and 'Last Login'...

Going to leave those alone... two different contexts.

> I don't understand why some ’ are now replaced by \' :

The difference is if it's a normal quote (i.e. `'`), then it has to be escaped with a backslash so it'll still be valid PHP in the translation files.  If it's a "fancy quote" (i.e. `’`), then it doesn't.

Just made a commit to clean up some of the normal quotes to the fancy ones.

https://github.com/craftcms/cms/commit/2e40f29ebced1859924693e49d3f7ade9d863b0c
