### ISSUE TITLE
Styles for field validation errors in CP `details` block

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#2127]
Field validation errors don’t look optimized for the new designed `details` block in RC1 preview.

<img width="345" alt="bildschirmfoto 2017-11-23 um 15 21 45" src="https://user-images.githubusercontent.com/7516543/33177317-771856a8-d062-11e7-9a34-b48ac4adf26b.png">

**Comment by brandonkelly** [comment]
Thanks!
