### ISSUE TITLE
Ref token replacement does not respect the site you are editing

### ISSUE THREAD

**Issue by acehead** [craftcms/cms#2129]
### Description
We have run across a pretty serious issue when urls of entries are being changed after saved first. It seems that while replacing content for textarea `parseRefs(string $str): string` does not take current site id into account. It searches for elements, but the site id remains default.

### Steps to reproduce

1. You need to have multisite installation and you should be editing an entry not from primary site
2. Create an entry with richtext element
3. Create a hyperlink (using Redactor) linking to another entry.
4. Save.
5. Note that the link leads to the correct site
6. Open it for editing once again
7. Choose to edit hyperlink.
8. Note that it contains base url of the primary site, instead of the site you are editing.
9. In case of saving, wrong url will be saved

### Additional info

Craft version: Craft Pro 3.0.0-beta.34
PHP version: 7.1.11
Database driver & version: PostgreSQL 9.6.2

**Comment by brandonkelly** [comment]
Fixed this in our new [Redactor](https://github.com/craftcms/redactor) plugin, which will launch alongside Craft 3 RC1 next week.
