### ISSUE TITLE
Image editor not loading image

### ISSUE THREAD

**Issue by retop** [craftcms/cms#2130]
### Description
When trying to edit an image the editor fails to load the image - resulting in a empty cropping canvas. 

**Web developer toolbar console shows the following error:**
Error loading http://domainname.de/craft/web/index.php?p=admin/actions/assets/edit-image&assetId=413&size=3840&cacheBust=1511524556508

**Visiting the aforementioned url shows the following error:** 
Internal Server Error
transliterator_transliterate(): Could not create transliterator with ID "Any-Latin; Latin-ASCII; [\u0080-\uffff] remove" (transliterator_create: unable to open ICU transliterator with id "Any-Latin; Latin-ASCII; [\u0080-\uffff] remove": U_INVALID_ID)

### Steps to reproduce

1.
2.

### Additional info

- Craft version: Craft Pro 3.0.0-beta.34
- PHP version: 7.1.9
- Database driver & version: MySQL 5.7.17-11
- Plugins & versions: no plugins
- Image Driver & Version:  GD 7.1.9

**Comment by takobell** [comment]
Any chance you could reproduce that error with devMode enabled, the share the full stack trace leading up to the error?

**Comment by retop** [comment]
There you go:

yii\base\ErrorException: transliterator_transliterate(): Could not create transliterator with ID &quot;Any-Latin; Latin-ASCII; [\u0080-\uffff] remove&quot; (transliterator_create: unable to open ICU transliterator with id &quot;Any-Latin; Latin-ASCII; [\u0080-\uffff] remove&quot;: U_INVALID_ID) in /html/craft/vendor/yiisoft/yii2/helpers/BaseInflector.php:507
Stack trace:
#0 /html/craft/vendor/craftcms/cms/src/web/ErrorHandler.php(85): yii\base\ErrorHandler->handleError(2, 'transliterator_...', '/html/craft/ven...', 507)
#1 [internal function]: craft\web\ErrorHandler->handleError(2, 'transliterator_...', '/html/craft/ven...', 507, Array)
#2 /html/craft/vendor/yiisoft/yii2/helpers/BaseInflector.php(507): transliterator_transliterate('Any-Latin; Lati...', '413.jpg')
#3 /html/craft/vendor/yiisoft/yii2/web/Response.php(770): yii\helpers\BaseInflector::transliterate('413.jpg', 'Any-Latin; Lati...')
#4 /html/craft/vendor/yiisoft/yii2/web/Response.php(612): yii\web\Response->getDispositionHeaderValue('inline', '413.jpg')
#5 /html/craft/vendor/yiisoft/yii2/web/Response.php(586): yii\web\Response->setDownloadHeaders('413.jpg', 'image/jpeg', true, 34672)
#6 /html/craft/vendor/yiisoft/yii2/web/Response.php(487): yii\web\Response->sendStreamAsFile(Resource id #208, '413.jpg', Array)
#7 /html/craft/vendor/craftcms/cms/src/web/Response.php(111): yii\web\Response->sendFile('/html/craft/sto...', '413.jpg', Array)
#8 /html/craft/vendor/craftcms/cms/src/controllers/AssetsController.php(607): craft\web\Response->sendFile('/html/craft/sto...', NULL, Array)
#9 [internal function]: craft\controllers\AssetsController->actionEditImage()
#10 /html/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /html/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 /html/craft/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('edit-image', Array)
#13 /html/craft/vendor/craftcms/cms/src/web/Application.php(242): yii\base\Module->runAction('assets/edit-ima...', Array)
#14 /html/craft/vendor/craftcms/cms/src/web/Application.php(419): craft\web\Application->runAction('assets/edit-ima...', Array)
#15 /html/craft/vendor/craftcms/cms/src/web/Application.php(202): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#16 /html/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /html/craft/web/index.php(21): yii\base\Application->run()
#18 {main}

**Comment by brandonkelly** [comment]
What is the image’s filename?

**Comment by andris-sevcenko** [comment]
Seems to be an environment thing and has nothing to do with Assets or filenames. Yii will attempt to transliterate any file name when sending a download, triggering an error if the ICU lib is out of date. 

Sort of related: https://bugs.php.net/bug.php?id=69120

**Comment by ricricucit** [comment]
@retop did you find out what was your issue about?
