### ISSUE TITLE
Unable to display a plugin's sub-navigation in global sidebar

### ISSUE THREAD

**Issue by nateiler** [craftcms/cms#2132]
It seems that the `.has-subnav` class should display a plugin's sub-nav item's, but it doesn't.

Reviewing the CSS I found adding the class `.expanded` will make them appear, but it's never set via the twig templating.

- Craft version: RC1

**Comment by brandonkelly** [comment]
Fixed in 1c770b6f28aa151f12f55be4fcc0ef41c0770631 - thanks!
