### ISSUE TITLE
A long name breaks the admin CSS

### ISSUE THREAD

**Issue by Rias500** [craftcms/cms#2133]
### Description
Screenshot:

![screen shot 2017-11-27 at 17 30 27](https://user-images.githubusercontent.com/3626559/33277432-cfa9b5da-d398-11e7-9011-d7bcee6fb2d3.png)

### Steps to reproduce

1. Have a long name 😄

### Additional info

- Craft version: 3.0-RC1 branch

**Comment by brandonkelly** [comment]
Your name shouldn’t be showing up there at all! Can you try clearing out your web/cpresources/ folder?

**Comment by Rias500** [comment]
Yep! That fixed it
