### ISSUE TITLE
Adding in filtering by date on a for statement breaks Live Preview

### ISSUE THREAD

**Issue by kmmartinez** [craftcms/cms#2134]
### Description

Adding a Start Date and End Date (date/time craft fields) to show content between those dates in a for statement breaks the live preview.

### Steps to reproduce

1. Add Two Fields, a start and end Date
2. Have a matrix field where you can add multiple items
3. In Twig, create a for statement that goes through and prints out those items based on the dates entered as a start and end date for showing.
4. Look at live preview

### Additional info

- Craft version: 2.6.2993
- PHP version: 7.1
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
What exactly do you mean by "breaks Live Preview" ?

If you do any sort of filtering on your Matrix field within your template, it will discard the posted content and query the database. So expected behavior would be that it shows you the stored content for those Matrix blocks, rather than what you entered in L.P.

**Comment by kmmartinez** [comment]
By break, I mean if I show live preview and change the text/image it won't update the live preview version with the change.

**Comment by brandonkelly** [comment]
OK, yeah that’s what I thought. So my response above explains why that’s happening.

**Comment by kmmartinez** [comment]
Is there a suggested work around to be able to get it to show on Live Preview while still trying to filter?

**Comment by brandonkelly** [comment]
You could move your current block code (whatever is between the `{% for %}` and `{% endfor %}` tags) into a [macro](https://twig.symfony.com/doc/2.x/tags/macro.html), and then do something like this in place of your current `{% for %}` tag:

```twig
{% macro matrixBlock(block) %}
    <!-- your current block code goes here -->
{% endblock %}

{% import _self as macros %}

{% if craft.request.isLivePreview() %}
    {% for block in entry.myMatrixField %}
        {% if block.startDate <= now and block.endDate > now %}
            {{ macros.matrixBlock(block) }}
        {% endif %}
    {% endfor %}
{% else %}
    {% for block in entry.myMatrixField.startDate('<= '~now).endDate('> '~now).find() %}
        {{ macros.matrixBlock(block) }}
    {% endfor %}
{% endif %}
```
