### ISSUE TITLE
Windows Firefox 57.0 (64-bit) create account installation problem

### ISSUE THREAD

**Issue by brammittendorff** [craftcms/cms#2137]
### Description

When using the web installation on Windows in firefox:

```Firefox 57.0 (64-bit)```

You click begin and the next screen will be the create account screen. After filling in the username email and password you can not click the `Next ->` button. It will not go to the next screen. 

**When I try the exact same steps it works in Chrome (latest) or IE (latest).**

### Steps to reproduce

1. Download latest craft
2. Navigate on windows with Firefox 57.0 (64-bit) to `admin/`
3. Click the begin button
4. Fill in your details
5. The `Next ->` button keeps on loading and will not go to the next screen

### Additional info

- Client-OS: Windows (64 bit)
- Craft version: Craft-2.6.2997
- PHP version: 7.0.26

The post on `admin/actions/install/validateAccount` goes wrong. With body:
```
				<h2>Bad Request</h2>
			<p>The CSRF token could not be verified.</p>
```

When I check the source there is a token:
```
<input name="CRAFT_CSRF_TOKEN" value="HgqucTAefBkCfiXunWj82kOd6t22Qa1nruG6snhH" type="hidden">
```

**Comment by brandonkelly** [comment]
I just tested this and wasn’t able to reproduce. Can you try it again following your exact steps to reproduce? There might be more to the story, like perhaps something happened that caused the CSRF token to be regenerated.

**Comment by brammittendorff** [comment]
Ill check this when I get home. In a few hours.

**Comment by brammittendorff** [comment]
I think its a case works on my machine, I tried this on multiple machines and it is working so ill close this issue.
