### ISSUE TITLE
How to add an HTML5 module to HTML Purifier?

### ISSUE THREAD

**Issue by proimage** [craftcms/cms#2138]
I'm having trouble wrapping my head around how to configure (extend?) HTML Purifier in Craft with an HTML5 module. I get that the [configuration options](http://htmlpurifier.org/live/configdoc/plain.html) just get tossed inside a `.json` file, but it looks like adding modules is done via PHP code ([from here](https://github.com/xemlock/htmlpurifier-html5)):

```
$config = HTMLPurifier_HTML5Config::create();
$purifier = new HTMLPurifier($config);
$purifier->purify(...);
````

Is there a way to accomplish this in Craft's packaged HTML Purifier?

---

All I actually want to accomplish is to allow `<mark>` tags in Redactor, without disabling HTML Purifier entirely. I already have Redactor configured to permit them, but HTML Purifier is being a mean ol'... _meanie_! 😜 

### Additional info

- Craft version:  2.6.2997
- PHP version: 5.4.45

**Comment by brandonkelly** [comment]
Unfortunately the way Yii 1 instantiates HTML Purifier, there’s no way for us to hook into it (or let plugins hook into it) to register new HTML elements. Yii 2 is more flexible though, so in Craft 3 we [configure](https://github.com/craftcms/cms/blob/develop/src/helpers/HtmlPurifier.php#L44-L77) HTML Purifier with all the HTML5 elements by default – no plugin required.

So either you’ll need to upgrade to Craft 3 (it’s pretty stable now – RC1 will be released next week), or disable HTML Purifier for the time being.
