### ISSUE TITLE
Being able to filter a matrix and have it show in LP

### ISSUE THREAD

**Issue by kmmartinez** [craftcms/cms#2140]
### Description
From a previous issue - If you do any sort of filtering on your Matrix field within your template, it will discard the posted content and query the database. So expected behavior would be that it shows you the stored content for those Matrix blocks, rather than what you entered in L.P.

Is there a suggested work around to be able to get the changes to a matrix to show on Live Preview while still trying to filter by date? 

### Steps to reproduce

1. Filter by date on a matrix
2. Change while in LP - no changes will show

### Additional info

- Craft version: 2.6.9993
- PHP version: 7.1
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
_(Reposting from https://github.com/craftcms/cms/issues/2134#issuecomment-347561820 for posterity…)

You could move your current block code (whatever is between the `{% for %}` and `{% endfor %}` tags) into a [macro](https://twig.symfony.com/doc/2.x/tags/macro.html), and then do something like this in place of your current `{% for %}` tag:

```twig
{% macro matrixBlock(block) %}
    <!-- your current block code goes here -->
{% endblock %}

{% import _self as macros %}

{% if craft.request.isLivePreview() %}
    {% for block in entry.myMatrixField %}
        {% if block.startDate <= now and block.endDate > now %}
            {{ macros.matrixBlock(block) }}
        {% endif %}
    {% endfor %}
{% else %}
    {% for block in entry.myMatrixField.startDate('<= '~now).endDate('> '~now).find() %}
        {{ macros.matrixBlock(block) }}
    {% endfor %}
{% endif %}
```
