### ISSUE TITLE
Migration error: Key column 'locale' doesn't exist in table

### ISSUE THREAD

**Issue by lauris** [craftcms/cms#2142]
Tried to setup CraftCMS 3 beta by following the docs.  When executing "./craft setup" the setup process fails because of SQL error:

```
create index templatecaches_expiryDate_cacheKey_locale_idx on {{%templatecaches}} (expiryDate,cacheKey,locale) ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'locale' doesn't exist in table
The SQL being executed was: ALTER TABLE `templatecaches` ADD INDEX `templatecaches_expiryDate_cacheKey_locale_idx` (`expiryDate`, `cacheKey`, `locale`)
```  

Migrations try to setup an index on an column that doesn't exist – table "templatecaches" no longer has "locale" column. The index is created here:
https://github.com/craftcms/cms/blob/a50502ad0edc0c240d6cd86790f9f9ddcd2ca346/src/migrations/Install.php#L844

After removing the index creation from Install.php everything works as expected.

**Comment by brandonkelly** [comment]
Doh! Thanks!
