### ISSUE TITLE
Dropdown field value of "0" returns a false value for the selected property

### ISSUE THREAD

**Issue by nateclonch** [craftcms/cms#2144]
### Description

Using the dropdown field with an option having "0" as its value prevents the selected property from returning `true`

### Steps to reproduce

1. Create and implement a dropdown field with "0" as one of the option values
2. Select that option from the dropdown and save the element
3. `dump()` the field's option property (e.g. `<pre>{{ dump(entry.dropdown.options) }}</pre>`)
4. Confirm that the selected option is in fact not returning `true`

### Additional info

- Craft version: 2.6.2997
- PHP version: 5.5.9
- Database driver & version: MYSQL 5.5.55
- Plugins & versions: NA

**Comment by brandonkelly** [comment]
Fixed for the next release. Thanks!
