### ISSUE TITLE
Craft ID Connect in RC1 returns 404

### ISSUE THREAD

**Issue by sjelfull** [craftcms/cms#2145]
### Description

When clicking _Connect_ under My Account, it leads to https://api.craftcms.com/login, which returns 404.

![image](https://user-images.githubusercontent.com/10508/33426011-bcc7502e-d5c0-11e7-84db-6bc44eabf421.png)

![image](https://user-images.githubusercontent.com/10508/33426036-cdbce830-d5c0-11e7-8c09-e6a095ab38c8.png)

### Steps to reproduce

1. Go to My Account in RC1
2. Click Connect in the sidebar

### Additional info

- Craft version: Craft Pro 3.0.0-RC1
- PHP version: 7.1.11

**Comment by brandonkelly** [comment]
Whoops, yep that’s not ready for prime time yet :) Just hid it.
