### ISSUE TITLE
Allow alteration of message via LoginFailureEvent

### ISSUE THREAD

**Issue by nateiler** [craftcms/cms#2147]
It would be nice to allow alteration of the login messaging via the 'LoginFailureEvent'.  Use case is delegating login logic to external resource and providing a clear explanation.

Ref: vendor/craftcms/cms/src/controllers/UsersController.php:1495

**Comment by brandonkelly** [comment]
It’s already possible; just override the translation. Create the file `translations/en-US/app.php` with this:

```php
return [
    'Invalid username or password.' => 'Something else',
    // ...
];
```

**Comment by nateiler** [comment]
Hmmm.  Not an ideal way of handling this in our case.

We have the ability to set a custom '$user->authError' attribute value but the message definition is hard coded.  It seems instead of altering an existing message (which still may be applicable) it would be helpful to provide additional message handling too.

**Comment by brandonkelly** [comment]
Ah missed that you are setting a custom error code. Sure, we can get this in.

**Comment by nateiler** [comment]
Awesome!  Thanks!
