### ISSUE TITLE
Saving a matrix field causes a 500 error

### ISSUE THREAD

**Issue by gablaxian** [craftcms/cms#2148]
### Description

When creating a new or saving a pre-existing matrix field, I sometimes get a nginx 500 error (We have nginx proxying to apache for PHP).

### Steps to reproduce

I _think_ it's when I create multiple fields in a block at once. It saves correctly when I create a block then a field and save first before going back and adding the others one at a time.

I can reproduce with these settings:

1. Have 3 previous block types with one field in each (all translate for each site)
2. create a `button` block type.
3. create two fields, `button link` (plain text, translate for each site, column type: varchar) and `button text` (rich text, translate for each site)
4. save

### Additional info

- Craft version: 3.0.0-beta.36
- PHP version: 7.1
- Database driver & version: MySQL 5.7.20
- Plugins & versions: Amazon S3 1.0.7, FastCGI Cache Bust 1.0.3, Typogrify 1.1.2

**Comment by gablaxian** [comment]
Actually it's triggering just when I try and save the rich text field in the above example. Even without translate for each site.

**Comment by gablaxian** [comment]
Okay, now it's causing a 500 error no matter what the field is after the `button link`

**Comment by gablaxian** [comment]
I rearranged the matrix field so that instead of multiple blocks with one field, it's one block with multiple fields. Worked okay until I needed to add another row to one of the fields which is a table. Back to 500 error.

**Comment by brandonkelly** [comment]
Any chance you have a Craft 2 site running in the same environment? Curious if you get the same nginx error with that.

**Comment by takobell** [comment]
What's the actual 500 error message?  If it's Craft generated, it'll be in your `craft/storage/logs` files and if it's nginx generated, it'll be in your nginx error logs.

**Comment by gablaxian** [comment]
In true bug fashion, after restarting my VM I no longer get the 500 errors. I'll close this issue and assume it's down to my VM/dev environment but if it crops up again I'll try and get more info.

Thanks!

**Comment by brandonkelly** [comment]
Hah, ok. If it crops up again try to remember to write down the actual error message, and make  a copy of any log files in storage/logs/, so we can try to see what was going on (if it was actually Craft-related).
