### ISSUE TITLE
RC1: new issues when translating Craft

### ISSUE THREAD

**Issue by ebeauchamps** [craftcms/cms#2150]
I can find both 'Install Craft CMS' and 'Install Craft'
=> Any chance it's a duplicate?

'Last login' and 'Last Login'
=> One of them has to be disconnected...

I don't understand why some ’ are now replaced by \\' 
Examples of keys I just found:
'This field’s default upload location Volume is missing'
'This field’s single upload location Volume is missing'
BUT : 'This field\\'s Volume configuration is invalid.' ???

Other examples:
'The Asset you\\'re trying to download does not exist.'
'The Asset you\\'re trying to edit does not exist.'
In the previous version of the language file, we had:
'The Asset you’re trying to download does not exist.'
'The Asset you’re trying to edit does not exist.'

Take care, no hurry.
Emmanuel

**Comment by brandonkelly** [comment]
We’ve made a few message changes since the translations were ordered. The duplicates will get cleared out after the next batch of translations are ordered.
