### ISSUE TITLE
nested hamburger menu may be better for narrow CP Utilities menu

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#2151]
### Description
What happens now on Utilities as screen width narrrows is that the inner side menu transforms into a dropdown. Problem is, that little down arrow, out of sight path on the right, and with the big title of the Utilities section, is not apparent, especially on a non-IPS laptop screen.

Thus seems would be better if this indicator/actor were another hamburger menu. What the action is could remain the drop-down to get the release out, if it takes too long, but better would be a slide-across, so that there can be contrasting look and evidence during appearance.

### Steps to reproduce

1. Be in CP Utilities, some aspect of it
2. narrow the screen, see the Utilities menu disappear, try to find it....

### Additional info

- Craft version: beta 36 or RC1
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Not sure how I feel about this – having two humburger menus on the same page would be pretty awkward.

**Comment by narration-sd** [comment]
yeah, would kind of agee there's an aesthetics question, but what I though was on hamburger would be white on black, the other black on white, likely,greys  instead of white or black, and in fit to tints of the menus themselves.

If you don't do something here, it's pretty 'blind' to seeing how to choose which Utility. You may well have another idea, but this seemed simple, and I like to keep the sliding menus motif rather than sudden not-so-clear dropdown. Esp. since it pushes down content so not very visible when you do find it.

Fun...

**Comment by narration-sd** [comment]
p.s. besides apology my typos corrected.  It's that of any eyes/age where you use multifocals, the instant scan field is narrowed -- you just map out things that aren't in good focus unless you remember to carefully scan, which exacerbates the situation with the little down arrow. 

n.b. Mine personally is worse due to damage being fixed, but normally is still an effect -- because the multifocals have a 'channel' in their transitional distances which gets pretty narrow at screen-reading range.

And anyway, know to prefer the sliding menus, as above.

**Comment by narration-sd** [comment]
closing, with respect, taken care of in #2323
