### ISSUE TITLE
Add config setting to disable installation of plugins from the store 

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#2154]
### Description

Looking for the equivalent to the `'allowAutoUpdates' => false` setting, but for new plugin installations.

### Additional info

- Craft version: 3.0 RC1

**Comment by brandonkelly** [comment]
@benjamindavid We can make this happen as part of the plugin action button changes coming in Craft 3 GA once the plugin store goes commercial.

**Comment by brandonkelly** [comment]
We’ve added a new `allowUpdates` config setting that replaces `allowAutoUpdates` for Craft 3 RC5, which also can be used to disable installing plugins via the Plugin Store.
