### ISSUE TITLE
Expose Matrix drag events

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#2156]
### Description

I can't seem to find a way to listen to Matrix drag events. Are these events exposed to other plugins via javascript? If so how can I add an event listener?

#probablyNotABug

**Comment by brandonkelly** [comment]
As of Craft 3 release you’ll be able to do this:

```js
var matrix = $('#matrix-container-id').data('matrix');
matrix.dragSort.on('sortChange', callback);
```
