### ISSUE TITLE
Redactor II is not production-ready

### ISSUE THREAD

**Issue by nicbou** [craftcms/cms#2158]
### Description

The default WYSIWYG editor is buggy and unreliable. It is so unpredictable that I struggle to use it myself. As a result, I cannot use Craft for client sites.

Since Redactor II is not on GitHub and does not have any accessible support channel, and since Craft is rendered unusable by Redactor II, I am creating a ticket here.

### Steps to reproduce

*  Selecting text and creating hyperlinks does not always work. Sometimes, the link will be inserted next to the selected text. Sometimes it will replace the whole paragraph.
* Line break bugs. I could not exit a bold paragraph no matter what I did. Create four lines of bold text (with shift+enter to create <br>s instead of <p>s), and try to add a regular paragraph after that.
* Inserted images create a figure tag and a bunch of empty paragraphs. Trying to remove the empty paragraphs removes the image.
* Superscript text with links is impossible to work with. I use superscript links for references, and they are a pain to update. The only solution is to delete the superscript text, recreate the link, and format it as supertext again.
* A few other random issues when trying to enter/exit contexts (bold, italic, link etc)

### Additional info

- Craft version: Craft CMS 2.6.2989
- Plugins & versions: no plugins

**Comment by brandonkelly** [comment]
We have dropped Redactor from the core for Craft 3, and made it a plugin, in addition to a new CKEditor plugin.

**Comment by nicbou** [comment]
That's fantastic news, thanks Brandon!

**Comment by nicbou** [comment]
I just want to update this ticket, in case someone is reading this in 2021. Redactor is still not production-ready. There are many serious bugs that still haven't been fixed.

- Sometimes, inserting a link will delete every other link in the paragraph.
- <br> tags are randomly inserted at the end of paragraphs
- <p> tags are randomly removed, leaving unwrapped text in random parts of the content
- The first line in a rich text field isn't wrapped in a <p> tag, until you manually wrap it yourself in HTML mode

I lost sight of how bad it was until I hired my first employee, and realised that I couldn't trust them to modify any of the content.

**Comment by nicbou** [comment]
4 years later, every single one of these issues are still present in redactor 2. That makes Craft unsuitable for a production environment. 

https://github.com/craftcms/redactor/issues/331

**Comment by mmikkel** [comment]
@nicbou ...the good news is that the first party CKEditor plugin is out of beta: https://plugins.craftcms.com/ckeditor

**Comment by nicbou** [comment]
I just got it running, and right off the bat, it breaks superscript, upon which I rely for thousands of citations on my website. It might have broken other things that I am not aware of.

**Comment by nicbou** [comment]
I've played with CKEditor some more, and it's even more broken than Redactor. The image upload button shows a file dialog, then nothing. There's no integration with assets and transforms.

I love working with Craft, but I've been waiting 4 years for a working editor, and there was zero progress. Instead, I had to get used to the bugs and work my way around them. I wasted a ton of time because of these Redactor bugs, and I'm afraid to sink more time in CKEditor to learn that it's also not working.

**Comment by brandonkelly** [comment]
We still have some work to do to get CKEditor on feature-parity with Redactor, yes. You might also want to check out [Vizy](https://plugins.craftcms.com/vizy), a new block-based editor by Verbb.

**Comment by nicbou** [comment]
This is still a serious issue in 2022. Here's another issue I commonly face.

https://user-images.githubusercontent.com/88917/153021640-53b6f5fe-c2ce-4161-b291-15eef3fb1feb.mov

**Comment by nicbou** [comment]
#331 is still a major, unfixed issue that I deal with on a daily basis.

**Comment by nicbou** [comment]
https://github.com/craftcms/redactor/issues/331

https://github.com/craftcms/redactor/issues/362
