### ISSUE TITLE
Can't get Docs URL from composer.json

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#2161]
### Description

In the `composer.json` file for plugins, the `"support" > "docs"` value is not being recognized.

<img width="1191" alt="screen shot 2017-12-04 at 4 08 10 pm" src="https://user-images.githubusercontent.com/5309692/33583280-70c36194-d90e-11e7-8779-e86f3de610f8.png">

You can see that the "Documentation" link is missing.

### Steps to reproduce

1.  Something like this in your `composer.json`...

```
"support": {
    "docs": "https://github.com/doublesecretagency/craft-cpcss/blob/v2/README.md",
    "issues": "https://github.com/doublesecretagency/craft-cpcss/issues"
}
```

### Additional info

- Craft version: `dev-release/3.0.0-RC1 as 3.0.0-RC1`

**Comment by brandonkelly** [comment]
Can you post an example composer.json?

**Comment by lindseydiloreto** [comment]
Upon further testing... looks like this ticket isn't 100% accurate.

The documentation link is working perfectly when the package is installed **locally**. But when the package is installed **remotely**, the link doesn't show.

Here's Andrew's current theory...
<img width="1018" alt="screen shot 2017-12-04 at 4 31 51 pm" src="https://user-images.githubusercontent.com/5309692/33583778-e1155c2a-d910-11e7-8dc6-73e476ff566d.png">

**Comment by lindseydiloreto** [comment]
@brandonkelly Here's the full original JSON...

```
{
    "name": "doublesecretagency/craft-cpcss",
    "description": "Add custom CSS to your Control Panel.",
    "type": "craft-plugin",
    "version": "2.0.0",
    "keywords": [
        "craft",
        "cms",
        "craftcms",
        "craft-plugin",
        "cp-css",
        "css"
    ],
    "support": {
        "docs": "https://github.com/doublesecretagency/craft-cpcss/blob/v2/README.md",
        "issues": "https://github.com/doublesecretagency/craft-cpcss/issues"
    },
    "license": "MIT",
    "authors": [
        {
            "name": "Double Secret Agency",
            "homepage": "https://www.doublesecretagency.com/plugins"
        }
    ],
    "require": {
        "craftcms/cms": "^3.0.0-beta.36"
    },
    "autoload": {
        "psr-4": {
          "doublesecretagency\\cpcss\\": "src/"
        }
    },
    "extra": {
        "name": "Control Panel CSS",
        "handle": "cp-css",
        "schemaVersion": "2.0.0",
        "hasCpSettings": true,
        "hasCpSection": false,
        "changelogUrl": "https://raw.githubusercontent.com/doublesecretagency/craft-cpcss/v2/CHANGELOG.md",
        "class": "doublesecretagency\\cpcss\\CpCss"
    }
}
```

**Comment by lindseydiloreto** [comment]
Just in case it wasn't clear... This is how I install packages locally:

```
  "repositories": [
    {
      "type": "path",
      "url": "local-plugins/cp-css"
    }
```

**Comment by brandonkelly** [comment]
Thanks guys. Assuming  this is only occurring when installing a plugin via the Plugin Store, in which case, should be fixed now :)

**Comment by brandonkelly** [comment]
(You won't see any change until the next plugin update though, or if you remove + reinstall)

**Comment by lindseydiloreto** [comment]
Works perfectly... thanks Brandon! 👍
