### ISSUE TITLE
RC1: (just a few) missing translations

### ISSUE THREAD

**Issue by ebeauchamps** [craftcms/cms#2164]
The top-right button label to add a category inside a newly created Category Group: "+ New category"

The top-right button label to add an entry inside a section: "+ New entry"
This is only shown once when you first click on the submenu in the sidebar. Indeed, when you click thereafter on the various sections/structure/single, the top-right button gets back its proper translated label

The top-right button label to upload an asset in the Assets submenu: "Upload files"

**Comment by brandonkelly** [comment]
Thanks, fixed for the next release!
