### ISSUE TITLE
Currency filter not working in rc1

### ISSUE THREAD

**Issue by bliswebagency** [craftcms/cms#2167]
### Description

The currency filter is not working craft 3 rc1, this is working in craft 2 (latest version)

### Steps to reproduce

1. create template
2. add `{{"50"|currency('USD', true)}}`
3. view page

### Additional info

- Craft version: 3.0.0 RC1
- PHP version: 7.0.26
- Database driver & version: MySQL 5.6.16-1~exp1
- Plugins & versions: Redactor 1.0.0

[stacktrace.txt](https://github.com/craftcms/cms/files/1534038/stacktrace.txt)

**Comment by brandonkelly** [comment]
Thanks for pointing that out. You just need to update your tag to:

```twig
{{ 50|currency('USD', stripZeros = true }}
```

Just added a [Currency Formatting](https://github.com/craftcms/docs/blob/master/en/changes-in-craft-3.md#currency-formatting) section to the Changes in Craft 3 page.
