### ISSUE TITLE
Unable to access Plugin Store due to missing axios.js file

### ISSUE THREAD

**Issue by Harry-Harrison** [craftcms/cms#2168]
### Description

I'm unable to view the Plugin Store due to a 404 error on a file called axios.js. The path is `/cpresources/5e5a76c0/42d1a2cb/axios/axios.js` however there is no `/cpresources/5e5a76c0/42d1a2cb/axios`.

I've tried deleting the entire `cpresources` directory and letting it regenerate as pages are accessed but it's still not coming in. The `axios.js` file does exist at `/vendor/craftcms/cms/lib/axios/axios.js`.

Composer is fully updated, as is my Homestead environment.

### Steps to reproduce

1. Visit /admin/plugin-store

### Additional info

- Craft version: Craft Personal 3.0.0-RC1
- PHP version: 7.1.12-1+ubuntu16.04.1+deb.sury.org+1
- Database driver & version: MySQL 5.5.5-10.2.11-MariaDB-10.2.11+maria~xenial-log
- Plugins & versions: N/A

**Comment by dreadfullyposh** [comment]
Having the same issue here.

**Comment by nateiler** [comment]
Me too.

I noticed the lib exists in`/vendor/craftcms/cms/lib`

Tried:
- deleting the cpresource directory.
- deleting vendor + composer.lock

**Comment by Harry-Harrison** [comment]
RC2 Seems to have fixed this for me.

**Comment by benjamindavid** [comment]
@Harry-Harrison Awesome, thanks!

@dreadfullyposh @nateiler did RC2 improved the situation for you as well?

**Comment by nateiler** [comment]
Yep.  Looks good on my end too.

Deleted: cpresources + vendor + composer.lock

**Comment by benjamindavid** [comment]
Thanks!

Closing this for now, feel free to reopen if needed.
