### ISSUE TITLE
Long fields overflow in entry editor on screens > 998px

### ISSUE THREAD

**Issue by Radiergummi** [craftcms/cms#2169]
### Description
If you have long (as in, many pixels wide) fields defined for an entry and navigate to `/admin/entries/{section}/{entry}` on a screen wider than 998px, the fields overflow the visible screen. Due to `overflow-x: hidden` being set on the body, though, you can't properly edit the item.

### Steps to reproduce
1. Create a field that can grow pretty wide, such as a rich text field from the Redactor plugin
2. Add the field to an entry type and create a new entry
3. Populate the field with a long snippet of text and save the entry

### Steps to solve
*Please note: This is an intermediate solution to a problem that might have another origin, but it works for me.*
Modify the following CSS for the breakpoint for `min-width: 999px`: 

```css
#main-container #main #main-content #content-container {
+  max-width: calc(100% - 350px);
}
```

**Reasoning:**
The content container lacks the details bar width (which is statically set to `flex: 0 0 350px`), so that needs to be added to the width calculation, and it has to be restrained to the `#main-content` width.

### Additional info

- OS/Browser: MacOS 10.13/Chrome 62.0.3202.94
- Craft version: `3.0.0-RC1`
- PHP version: `7.0.8`
- Database driver & version: MySQL
- Plugins & versions:
   - pixelandtonic/contactform
   - craftcms/redactor

Screenshots:
<img width="1280" alt="bildschirmfoto 2017-12-06 um 10 31 10" src="https://user-images.githubusercontent.com/6115429/33655586-be1acdea-da73-11e7-9dd1-d861fb78c062.png">
<img width="1279" alt="bildschirmfoto 2017-12-06 um 10 30 53" src="https://user-images.githubusercontent.com/6115429/33655587-be3ae792-da73-11e7-8421-27431bd319c4.png">

*Note: These screenshots don't include the browser chrome due to being on MacOS, but show the full window width.*

**Comment by brandonkelly** [comment]
Thanks for the heads up! Fixed for the next release.
