### ISSUE TITLE
Specifying `registerJs` position has side-effect of displacing the `jquery.js` reference

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#2173]
### Plugin Development (Craft 3)

(1) Works as expected:

```php
$view = Craft::$app->getView();
$view->registerAssetBundle(MyAssets::class);
```

... which will inject my JS file like so:

```html
<script src="/cpresources/1665d842/3089c54f/jquery.js?v=1511390655"></script>
<script src="/cpresources/9783ad35/b16dc2c5/js/from-asset-bundle.js?v=1512631372"></script>
```

This is the **expected behavior**. Actually... I'd expect `from-asset-bundle.js` to appear after _all other_ scripts were loaded, but it appears that only `jquery.js` is jumping ahead. This behavior changed slightly between Craft 2 -> 3.

(2) If you _also_ add some inline JS, but specify **where you want it to be included**, it will knock `jquery.js` out of the first position.

```php
$view->registerJs('myFunction();', View::POS_HEAD);
```

... that will correctly output the `myFunction();` call in the header, but have the strange side effect of knocking `jquery.js` out of it's top slot in the queue.

```html
<script src="/cpresources/9783ad35/b16dc2c5/js/from-asset-bundle.js?v=1512631372"></script>
<script src="/cpresources/1665d842/3089c54f/jquery.js?v=1511390655"></script>
```

This is unexpected behavior. I would expect that the `jquery.js` file remains at the top of the queue, regardless of where the unrelated `registerJs` snippet was placed.

This was very hard to explain, please let me know if you have any follow-up questions.

### Additional info

- Craft version: Craft Pro 3.0.0-RC1

**Comment by lindseydiloreto** [comment]
Ahh... I was just set straight on Slack. Apparently, this is just a matter of making my AssetBundle dependent on the `CpAsset` bundle.

```php
$this->depends = [CpAsset::class];
```

Sorry & thanks anyway!

**Comment by smockensturm** [comment]
This is cool for CP development, but if you want to register a bundle (from a PlugIn) for your front end templates to use - and do **not** include the CpAsset dependancies, the goods do get added **before** all your other front-end scripts (typically. ymmv.)

Which is a bit of a drag. I know we can re-jigger our front-end loading sequence, but when I want to add say a jQuery plugin from a Craft plug-in, I want it to load last. After everything.

**Comment by brandonkelly** [comment]
@smockensturm I wouldn’t recommend using any asset bundles on your front end which were intended for the Control Panel. If you want to use asset bundles, write a module that provides its own completely independent set of bundles, and then you will have complete control over what gets loaded, in which order.
