### ISSUE TITLE
Missing RichText fieldtypes after upgrade

### ISSUE THREAD

**Issue by ow** [craftcms/cms#2175]
### Description
I'm busy exploring upgrading a heavily trafficked Craft CMS installation, with custom plugins, to the latest version so I can go back and re-write my internal stuff. After the upgrade, which went smoothly, and no composter installs failed, I get this:

![image](https://user-images.githubusercontent.com/3075582/33716726-865803e8-db57-11e7-81c0-86108dbf8712.png)

### Steps to reproduce

1. Upgrade from Craft 2
2. Log in to dashboard, head to fields
3. All RichText missing, unable to choose from dropdown

### Additional info

- Craft version: Craft Pro 3.0.0-RC1
- PHP version: 7.0.22
- Database driver & version: MySQL 5.7.19-0ubuntu0.16.04.1
- Plugins & versions: None enabled (yet)

**Comment by brandonkelly** [comment]
Craft 3 doesn't ship with a built-in WYSIWYG editor. The built-in "Rich Text" field type from Craft 2 has been moved into a "Redactor" plugin for Craft 3, available in the Plugin Store. (There's a beta for a new CKEditor plugin in there, too;)

**Comment by ow** [comment]
Ohhhhh ok, is there someplace that's in the documentation? Might be worth considering, perhaps, making it _far_ higher than it is now? I spent at least a few hours puzzled if it was corrupted or not (uninstalled and reinstalled a number of times), and have a number of Craft installs where I use the Rich Text field so must have missed the memo completely somehow.

Given how much has changed I'm sure it's hard to prioritize what to tell people but this is a fairly large breaking change and I was perplexed for a good amount of time... 'scuse the ignorance, just taking in everything still and hoping to provide useful feedback.  :) 

Thanks for the speedy response!

**Comment by ow** [comment]
P.S - Holy crap the store is great

**Comment by brandonkelly** [comment]
Yeah agree it should be more prominent. Just added it to the top of the [Changes in Craft 3](https://github.com/craftcms/docs/blob/master/en/changes-in-craft-3.md) page.
