### ISSUE TITLE
Can you change the name of webroot dir /web to something else?

### ISSUE THREAD

**Issue by E2design** [craftcms/cms#2176]
Can you change the name of the webroot dir /web, to something that reflects the server guidelines? 

f.i. Arcustech requires a /public or /public_html dir as webroot. 

And would it be possible to adjust after Craft3 already went through the installation procedure?

**Comment by brandonkelly** [comment]
You can name that folder whatever you want (just like you could rename `public` to whatever you wanted in Craft 2). `web` is just the new default. You can change it at any time. Just make sure that your `CRAFT_BASE_PATH` constant in `<web>/index.php` is still set correctly.
