### ISSUE TITLE
Routes with unnamed parameters are not matched in Craft 3

### ISSUE THREAD

**Issue by bwlng** [craftcms/cms#2184]
### Description

In Craft 3 RC1, when creating a route using an asterisk in the CP or a pattern with no parameter name like `'blog/type/([^\/]+)'` in `routes.php`, a 404 is returned instead of the specified template.

In Craft 3 adding the pattern below to routes.php results in a 404 when requesting a URL that should match

    return [
        'blog/type/([^\/]+)' => ['template' => 'test']
    ];

In Craft 2 adding the pattern below to routes.php loads the `test` template as expected with a `matches` array available in the template:

    return [
        'blog/type/([^\/]+)' => 'test',
    ];

Adding a named parameter (`slug` in the code below) works as expected with the parameter available in the template
 
    return [
        'blog/type/<slug:([^\/]+)>' => ['template' => 'test']
    ];

### Steps to reproduce

![screen shot 2017-12-09 at 1 55 44 am](https://user-images.githubusercontent.com/199782/33793842-1faaed7a-dc85-11e7-9fa9-e66677534671.png)

1. Create a route with an asterisk in the CP or a pattern without a name in routes.php
2. Make a request to the route
3. Response status is 404

![screen shot 2017-12-09 at 2 04 23 am](https://user-images.githubusercontent.com/199782/33793853-508d14b8-dc85-11e7-8d26-da88a6e8069d.png)

4. Edit route in CP to use `slug` placeholder or the same pattern as step 1 but with the name `slug` in routes.php
5. Make a request to the route
6. Response status is 200

### Additional info

- Craft version: Craft Pro 3.0.0-RC1
- PHP version: 7.1.8
- Database driver & version: MySQL 5.6.35

**Comment by brandonkelly** [comment]
Thanks, fixed now, for CP routes, although you will need to update your config/routes.php routes to use the new `<name:pattern>` syntax:

```php
return [
    'blog/type/<foo:[^\/]+>' => ['template' => 'test']
];
```
