### ISSUE TITLE
Vertical height of span.info

### ISSUE THREAD

**Issue by putyourlightson** [craftcms/cms#2185]
### Description

Sometimes it is desirable to put line breaks into a `<span class="info"></span>` element, however this increases the vertical height of the span which displays the info icon:
![screen shot 2017-12-09 at 10 39 42](https://user-images.githubusercontent.com/2318222/33794483-502ee896-dccd-11e7-9928-60a2180e9552.png)

A simple solution could be to add the following CSS rule:

```
.info p {
    display: none;
}
```

And then we can wrap the content of the `span` in a `p` tag as follows:

```
<span class="info">
    <p>
        Line 1<br/>
        Line 2<br/>
        Line 3
    </p>
</span>
```

### Additional info

- Craft version: 3.0.0 RC1

**Comment by brandonkelly** [comment]
Took the fix in a different direction, but end result is the same. You’ll also be able to include multiple paragraphs in `.info` elements if you want, too.

```html
<div class="info">
    <p>Paragraph 1</p>
    <p>Paragraph 2</p>
</div>
```

**Comment by putyourlightson** [comment]
Lovely, thanks!
