### ISSUE TITLE
Feature request: add a warning before leaving a page with unsaved content

### ISSUE THREAD

**Issue by dbismut** [craftcms/cms#2188]
At the moment, entry aren't automatically saved. and leaving an entry with unsaved content doesn't trigger any warning which I feel can generate user errors.

Here's my temporary hack using [Control Panel JS plugin](https://github.com/doublesecretagency/craft-cpjs).

```javascript
$('form#main-form').on(
  'change',
  'input:not(#slug), select, textarea',
  function() {
    window.isDirty = true;
  }
);
$('form#main-form').submit(function() {
  window.isDirty = false;
});
window.onbeforeunload = function() {
  if (window.isDirty) {
    return 'Are you sure you want to leave the page?';
  }
};
```

**Comment by brandonkelly** [comment]
The CP actually already has that feature, it just wasn’t getting initialized in Craft 3, I guess due to a breaking change in jQuery. Just fixed for the next release.
