### ISSUE TITLE
Delta Versions

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/cms#2190]
Entry versions should only store the actual changes that occurred; not a full copy of the content.

Related: #2189, #1133

**Comment by michaelrog** [comment]
Seems like this also assumes an immutable chain of history between the original version and the current one, i.e. It would preclude ever deleting versions?

**Comment by narration-sd** [comment]
@michaelrog  think you may have hit on a very important point, maybe why it's designed the way it is. 

Massive amount going on in Craft; any of us can easily forget...

**Comment by andris-sevcenko** [comment]
@michaelrog are you... suggesting blockchain for Craft?

**Comment by michaelrog** [comment]
@andris-sevcenko If you implement CraftCoin, I will buy it.

**Comment by brandonkelly** [comment]
Decided against this.
