### ISSUE TITLE
Element Query filters quietly failing on reserved keywords

### ISSUE THREAD

**Issue by grantnhoward** [craftcms/cms#2191]
### Description
Element filters such as .slug() will not work properly if given words like 'and', 'or', etc. I ran into this while testing a category slug lookup for the state of Oregon (or), and verified the same issue happens with the slug 'and' for a Category Element. 

This is an **extreme low priority** issue, but something to be aware of in case there is a deeper risk for how these queries are being parsed and run.

### Steps to reproduce

1. Create a category element named Oregon, give it the slug 'or'
2. Try to lookup the category from `craft.categories.group('states').slug('or').one()`
3. No result returned

### Additional info

- Craft version: Craft Pro 3.0.0-RC1
- PHP version: 7.0.22-0ubuntu0.16.04.1
- Database driver & version: MySQL 5.6.27-log
- Plugins & versions:

**Comment by brandonkelly** [comment]
Ah this is happening because `or` and `and` are special values that the param parser will check for when determining how to handle multiple values.

You can work around this by changing the param to `slug('and', 'or')`.
