### ISSUE TITLE
Can't rename pdf to original file name after replacing it

### ISSUE THREAD

**Issue by mathiasgomig** [craftcms/cms#2195]
### Description

If one uploads a PDF file (let's call it _fileA.pdf_), replaces it with another PDF file (_fileB.pdf_), it can't be renamed to the original file name (_fileA.pdf_), because the original file (_fileA.pdf_) doesn't get deleted. 

The reason I'm creating an issue for this is, because this workflow is working perfectly for images. Is this a bug or is there a reason why PDF files are not deleted but images are?

### Steps to reproduce

**PDFs (Doesn't work)**

1. Upload fileA.pdf
2. Replace it with fileB.pdf
3. Rename fileB.pdf to fileA.pdf inside the assets and see the error message (File “fileA.pdf” already exists at target location.)

<img width="683" alt="error" src="https://user-images.githubusercontent.com/4096309/33832529-c573c148-de7c-11e7-9c9a-2c1fdb2dfd21.png">

**Images (Works)**

1. Upload fileA.jpg
2. Replace it with fileB.jpg
3. Rename fileB.jpg to fileA.jpg inside the assets

### Example files

[fileA.pdf](https://github.com/craftcms/cms/files/1547804/fileA.pdf)
[fileB.pdf](https://github.com/craftcms/cms/files/1547805/fileB.pdf)

![filea](https://user-images.githubusercontent.com/4096309/33832372-3d7f6bd4-de7c-11e7-8701-adc2d38de746.jpg)

![fileb](https://user-images.githubusercontent.com/4096309/33832373-3d9ae404-de7c-11e7-9aa5-9ae75abfdb53.jpg)

### Additional info

- Craft version: 2.6.3000
- PHP version: 7.0.22
- Database driver & version: mysql 5.0.12
- Plugins & versions: no plugins installed
- Also tested in Craft Demo

**Comment by andris-sevcenko** [comment]
This has been fixed in d62a4b3

**Comment by joepagan** [comment]
This appears to still be occurring on Craft 2.7.0 on Amazon S3 with PDF files, however, a PNG file behaves as expected.

**Comment by andris-sevcenko** [comment]
@angrybrad ^^ any thoughts about the update silently failing?

**Comment by angrybrad** [comment]
@joepagan @andris-sevcenko maybe some sort of overly agressive settings for OpCache or other PHP byte level caching extension?
