### ISSUE TITLE
Jquery-ui added on a plugin conflicts with autocomplete code in Craft.js 

### ISSUE THREAD

**Issue by dbismut** [craftcms/cms#2196]
### Description
I've added jquery-ui to a plugin that features autocomplete field. I've added `jquery-ui.min.js` in my plugin asset php file.

```javascript
$this->js = [
  'vendors/jquery/jquery-ui.min.js',
  'js/script',
];
```

However, when I go to the Settings/Fields section and create a Matrix field, when adding a block I get the following error in the console:

**Uncaught Error: cannot call methods on autocomplete prior to initialization; attempted to call method 'off'**

This issue seems to be triggered by this [line](https://github.com/craftcms/cms/blob/a3208046220706004ec73841e8c502720f574612/src/web/assets/cp/src/js/UI.js#L15), and is also similar to this issue:

https://github.com/clientIO/JointJS_plus/issues/45

### Steps to reproduce

1. Load jquery-ui.min.js into a plugin
2. Go to the fields section
3. Add a Matrix field
4. Create a block

### Additional info

- Craft version: Craft Pro 3.0.0-RC1
- PHP version: 7.1.12
- Database driver & version: MySQL 5.7.20

**Comment by brandonkelly** [comment]
Thanks! Fixed for the next release.
