### ISSUE TITLE
Unable to save entry when "show title field" is unchecked

### ISSUE THREAD

**Issue by whoisgina** [craftcms/cms#2199]
### Description

I'm unable to save an entry when `Show the Title field` is unchecked in the respective Entry Type settings. I get the error: `Couldn’t save entry.`, but no fields are flagged. In fact this happens with a new entry with no fields at all.

### Steps to reproduce

1. Make a structure, and add an entry to it.
2. Edit the Entry Type so that `Show the Title field` is unchecked.
3. Open/edit and attempt to save the entry. 
4. Voilà, `Couldn’t save entry.`

### Additional info

- Craft version: Craft Personal 3.0.0-RC1
- PHP version: 7.0.24
- Database driver & version: MySQL 5.7.18
- Plugins & versions: CKEditor 1.0.0-beta.1

**Comment by brandonkelly** [comment]
What is your Entry Title Format set to?

**Comment by whoisgina** [comment]
Oh duh, it's not set! Which reveals that the Entry Type editor will successfully save even if a required field isn't set.

**Comment by brandonkelly** [comment]
Doh, thanks for pointing that out! Fixed for the next release.
