### ISSUE TITLE
Can't save multiple "slugless" entries

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#22]
#### Environment:

- Craft version: 3.x
- PHP version: 7.x
- Database driver & version: n/a
- Plugins & versions:

#### Description:

It's possible to save an entry with a Title that will generate no slug:

Title: "-"

Because dashes are removed, the slug becomes an empty string. This behavior is a little weird, but I'm not sure what it should be doing instead.

The real problem appears when you try to create a *second* entry with the same title. Normally, the slug would automatically append a "-1", but it seems to fail that in this case. Instead, I get an error message on the slug field:

URI "machinery/" has already been taken.

**Comment by aNickzz** [comment]
Was this resolved? It looks like there was only three commits on this, where the second one just reverts the first one, and the third one only changed the changelog.

**Comment by brandonkelly** [comment]
@aNickzz Probably best to just ignore this issue (especially given all the false references to it over the years from people posting their stack traces), and just post a new issue if something isn’t working as expected.
