### ISSUE TITLE
Sidebar active item getting cut off

### ISSUE THREAD

**Issue by putyourlightson** [craftcms/cms#2200]
### Description

The background colour of the active item in the sidebar gets cut off when scrolling down.

![screen shot 2017-12-12 at 02 03 31](https://user-images.githubusercontent.com/2318222/33862015-f6a5df4e-dee0-11e7-8d7b-446b272668fe.png)

### Steps to reproduce

1. Go to System Report in Utilities
2. Scroll down

### Additional info

- Craft version: 3.0.0 RC1

**Comment by brandonkelly** [comment]
Already fixed for the next release :)

**Comment by putyourlightson** [comment]
Thanks!!
