### ISSUE TITLE
left sidebar destroys layout on scroll right main content

### ISSUE THREAD

**Issue by crazyx13th** [craftcms/cms#2201]
### Description

If I have scrolled the right entry-list, the sidebar changing the width
![grafik](https://user-images.githubusercontent.com/8912561/33876266-4ffb0832-df25-11e7-9c55-89843b0c2a62.png)

### Additional info

- Craft version: Craft Pro 3.0.0-RC1
- PHP version: 7.0.26
- Plugins & versions:
![grafik](https://user-images.githubusercontent.com/8912561/33876693-7b55fe6e-df26-11e7-96bc-79a82032ccb2.png)

**Comment by crazyx13th** [comment]
small hint: header and sidebar is jumping 1px up on scroll too :-)

**Comment by brandonkelly** [comment]
Already fixed for the next release :)
