### ISSUE TITLE
Caps lock hint isn't working

### ISSUE THREAD

**Issue by mattstein** [craftcms/cms#2203]
### Description

The caps lock image [referenced in Craft's CSS](https://github.com/craftcms/cms/blob/1ec5ce2f776cad117d0a3a521475c3a82beb8fc4/src/web/assets/cp/dist/css/_main.scss#L3534) doesn't exist anymore, nor does the caps lock hint seem to work.

Expected behavior (as seen previously): from the CP login view, turning on caps lock and selecting the password field should display the icon indicating that caps lock is enabled.

Actual result: not that. No `capslock` class added to field, no warning at all. Acts just like any other normal password field.

### Steps to reproduce

1. Visit CP login, turn on caps lock, select password field.
2. Note lack of caps lock warning icon.
3. Revisit CP login, turn off caps lock, select password field.
4. Observe identical result as seen in step 2.

### Additional info

- Craft version: 2.6.2997, 3 RC1

**Comment by brandonkelly** [comment]
Man that’s weird. I remember adding this feature way back in the day, but I can’t actually find a release that contains capslock.png.

You’re sure you’ve seen it though?

**Comment by brandonkelly** [comment]
Actually looks like I did intentionally remove it (7e4b165584e79b32ff20985e257c23cc8a222d9e). I'll remove the reference to capslock.png in the CSS.

**Comment by mattstein** [comment]
For the record, I'm sure I've seen the feature but can't begin to guess when I last noticed it. Even weirder is that FullStory's _bot_ somehow noticed the missing image and led me to this.
