### ISSUE TITLE
unable to save with "show title field" unchecked

### ISSUE THREAD

**Issue by kevindoveton** [craftcms/cms#2204]
### Description
Kind of related to #2199  
not able to save the second entry with "show title field" unchecked, first entry is fine

### Steps to reproduce

1. Create a section of type channel
2. Make sure show title unchecked
3. set title format to `{someVariableInEntry}`
4. Save first entry
5. Save second entry (`Could not generate a unique URI based on the URI format.`)

### Additional info

- Craft version: 3.0 RC 1
- PHP version: 7,2
- Database driver & version: Mysql
- Plugins & versions: redactor

**Comment by kevindoveton** [comment]
Actually just noticed i had about 15 `Resaving SECTION entries` in my task list, deleting the channel and recreating fixed the issue.

**Comment by brandonkelly** [comment]
This would happen if the Entry Title Format field is not generating a unique URI for each entry, and doesn’t contain a `{slug}` tag.
