### ISSUE TITLE
Open "System Report" links in new window

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#2205]
**Craft Pro 3.0.0-RC2**

1. Go to `/admin/utilities/system-report` page.
2. Click on any info bubble with a link.
3. Links to external libraries should open in a new tab.

><img width="281" alt="system-report" src="https://user-images.githubusercontent.com/5309692/33927894-afe7386a-df98-11e7-92f5-c60a6ce19017.png">

**Comment by brandonkelly** [comment]
Fixed! Run `composer update` to get the server-check code.

**Comment by lindseydiloreto** [comment]
Works great, thanks @brandonkelly!
