### ISSUE TITLE
Deep-linking to layout editor is broken

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#2206]
**Craft Pro 3.0.0-RC2**

Theoretically, it's possible to deep-link to the field layout editor for both **Assets** and **Global Sets**. However, the anchors on these links appear to be broken...

 - `/admin/settings/assets/volumes/{id}#assetvolume-fieldlayout`
 - `/admin/settings/globals/{id}#set-fieldlayout`

In each case, the link will take you to the correct _page_, but won't load the correct _tab_.

**Comment by brandonkelly** [comment]
IIRC, this has never actually been possible. Theoretically we could _make_ it possible, but just to clarify, you aren’t saying this used to work right?

**Comment by brandonkelly** [comment]
Nevermind, just tested and it does work in Craft 2. Will fix for Craft 3.
