### ISSUE TITLE
Plugin Store: Whats New? Whats Hot? Sorting?

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#2208]
It would be nice to have an overview about the latest Plugins and maybe an overview about the hottest Plugins (most downloaded) etc. Or in general a bit more Filter / Sorting possibilities. 

And when I'm in a specific category a Backbutton would be also nice :)

**Comment by juresrpcic** [comment]
Good idea, especially now that new plugins are added daily and there's no way to know which were recently added.

I would suggest a dropdown that would sort by:
- date plugin was added to the store
- date plugin was last updated
- (what David suggested above)

Also it would be useful to get versions + last updated displayed on each plugin even when sorted by something else.

**Comment by brandonkelly** [comment]
> It would be nice to have an overview about the latest Plugins and maybe an overview about the hottest Plugins (most downloaded) etc. Or in general a bit more Filter / Sorting possibilities.

RC2 added the ability to sort by Popularity and “Last Update” within category views, and I just added a new “Recently Added” set to the Plugin Store homepage.

> And when I'm in a specific category a Backbutton would be also nice :)

The browser’s back button works within the Plugin Store.

FFR please keep each GitHub issue limited to 1 request, thanks!
