### ISSUE TITLE
[Bug] Plugin store unusable when omitScriptNameInUrls setting is set to false.

### ISSUE THREAD

**Issue by monachilada** [craftcms/cms#2209]
### Description

When clicking on the plugin store, it appears to ignore the omitScriptNameInUrls setting and try to redirect to /admin/plugin-store.

### Steps to reproduce

1. Set omitScriptNameInUrls to false in config
2. Click the plugin store link

### Additional info

- Craft version: 3.0.0-RC1 (Pro)
- PHP version: 7.1.12-2+ubuntu16.04.1+deb.sury.org+2
- Database driver & version: MySQL 5.7.20-0ubuntu0.16.04.1
- Plugins & versions: 
    - Redactor 1.0.0.1
    - CP Field Inspect 1.0.2

**Comment by brandonkelly** [comment]
@benjamindavid Looks like it initially goes to /index.php?p=admin/plugin-store (as expected) but the page changes the URL to /admin/plugin-store/index.php?p=admin%2Fplugin-store.

**Comment by brandonkelly** [comment]
Plus, the plugin store doesn't actually load when this happens.
