### ISSUE TITLE
Queues are not run at the end of ajax requests in RC2

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#2211]
@brandonkelly had made a hot fix at some point to have any pending jobs in the queue run at the end of AdminCP modals that are handled via ajax, to allow tasks the opportunity to kick off

These work great for things like replacing an Asset, but pending jobs in the queue are not run at the end of the Image Editor's lifecycle.

Expected behavior:

Pending jobs in the queue would be given a chance to run at the end of ajax requests after the Image Editor is used.

Actual behavior:

Pending jobs in the queue are not run until the next normal AdminCP request

**Comment by khalwat** [comment]
After further testing, they _are_ run for things like replacing an Asset... but pending jobs are _not_ run after the Image Editor is dismissed.

So if people change the Focal Point of an image, for instance, the pending tasks won't be run until they reload the page with a regular request.

**Comment by brandonkelly** [comment]
@andris-sevcenko The Image Editor should be calling `Craft.cp.runQueue()` after saving an image.
