### ISSUE TITLE
Add EVENT_DELETE_CREATED_TRANSFORMS in AssetTransforms.php 

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#2212]
It'd be wonderful if the `deleteCreatedTransformsForAsset()` fired an `EVENT_DELETE_CREATED_TRANSFORMS` so that plugins that may have created image variants via `EVENT_GENERATE_TRANSFORM` have a chance to clean up after themselves.

Specifically in my case, I create an `.webp` variant, and I'd like to clean it up if transforms are deleted as per:

https://github.com/nystudio107/craft3-imageoptimize/issues/22

**Comment by khalwat** [comment]
Thanks @andris-sevcenko but (there's always a "but")...

In order to be able to find the proper transform sub-folder, we'd need to have `$transformIndex` passed down too:

```
        // Fire a 'deleteCreatedTransforms' event
        if ($this->hasEventHandlers(self::EVENT_DELETE_ASSET_TRANSFORMS)) {
            $this->trigger(self::EVENT_DELETE_ASSET_TRANSFORMS, new DeleteAssetTransformsEvent([
                'asset' => $asset,
                'transformIndex' => $transformIndex,
            ]));
```

...otherwise we won't be able to do:

```             $volume->deleteFile($asset->getFolder()->path.$this->getTransformSubpath($asset, $transformIndex));
```

...in the event handler (we'll have no idea what `transformIndex` is associated with the passed down `asset`).

**Comment by brandonkelly** [comment]
@khalwat Just made some changes to the event(s). Let me know if it will work for you now.

**Comment by andris-sevcenko** [comment]
@khalwat yeah for some reason I had assumed that `nystudio107/craft3-imageoptimize` maintained it's own transform index and would know what files to get rid of. I'm not sure why, now.
