### ISSUE TITLE
Edit entry screen messy on mobile

### ISSUE THREAD

**Issue by phoob** [craftcms/cms#2214]
![68fbe299-7ffc-4e90-8367-3f97b113a008](https://user-images.githubusercontent.com/1475800/33983198-8ed3d18a-e0b3-11e7-80ba-45e58709531a.png)

### Description

See attachment.

### Steps to reproduce

Edit entry on iOS device. iPhone 8 Plus, tried both safari and chrome. 

### Additional info

- Craft version: Craft 3 RC2

**Comment by H-i-red** [comment]
#2224
