### ISSUE TITLE
Disabled Matrix row not deleting after saving

### ISSUE THREAD

**Issue by bliswebagency** [craftcms/cms#2219]
### Description

If a Matrix row is Disabled and you delete it... it doesn't actually get deleted. Instead, once you refresh the entry, the row is still there.

The only way to delete the row is to first "enable" the row again. Then save. Then delete the row. Then save again.

### Steps to reproduce

1. Disable a Matrix row
2. Save
3. Try to delete the row (it will look like it's worked).
4. Save
5. Refresh the entry (CMD/CTRL+R)
6. Observe the row is still there

### Additional info

- Craft version: 3.0.0-RC2
- PHP version: 7.0.26
- Database driver & version: MySQL 5.6.16-1~exp1
- Plugins & versions:
Redactor	1.0.0.1
Control Panel CSS	v2.0.0
Control Panel JS	v2.0.0
Snitch	2.0.0
Position Fieldtype	1.0.1

**Comment by brandonkelly** [comment]
Thanks for reporting!
