### ISSUE TITLE
Can not clear all caches using the all option

### ISSUE THREAD

**Issue by bliswebagency** [craftcms/cms#2220]
### Description

using the clear "all" caches option does not work, manually selecting each option does.

### Steps to reproduce

1. Head to "Clear Caches"
2. Select "All" if not already selected
3. Hit the "Clear Caches" button

### Additional info

- Craft version: 3.0 RC2
- PHP version: 7.0
- Database driver & version: Mysql 5.6
- Plugins & versions: redactor

```
yii\web\BadRequestHttpException: Request missing required body param in /srv/users/serverpilot/apps/glenside-website-craft/vendor/craftcms/cms/src/web/Request.php:497
Stack trace:
#0 /srv/users/serverpilot/apps/glenside-website-craft/vendor/craftcms/cms/src/controllers/UtilitiesController.php(332): craft\web\Request->getRequiredBodyParam('params')
#1 [internal function]: craft\controllers\UtilitiesController->actionClearCachesPerformAction()
#2 /srv/users/serverpilot/apps/glenside-website-craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /srv/users/serverpilot/apps/glenside-website-craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /srv/users/serverpilot/apps/glenside-website-craft/vendor/craftcms/cms/src/web/Controller.php(80): yii\base\Controller->runAction('clear-caches-pe...', Array)
#5 /srv/users/serverpilot/apps/glenside-website-craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('clear-caches-pe...', Array)
#6 /srv/users/serverpilot/apps/glenside-website-craft/vendor/craftcms/cms/src/web/Application.php(242): yii\base\Module->runAction('utilities/clear...', Array)
#7 /srv/users/serverpilot/apps/glenside-website-craft/vendor/craftcms/cms/src/web/Application.php(420): craft\web\Application->runAction('utilities/clear...', Array)
#8 /srv/users/serverpilot/apps/glenside-website-craft/vendor/craftcms/cms/src/web/Application.php(202): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#9 /srv/users/serverpilot/apps/glenside-website-craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /srv/users/serverpilot/apps/glenside-website-craft/public/index.php(21): yii\base\Application->run()
#11 {main}
```

**Comment by brandonkelly** [comment]
Not able to reproduce this on my end.

The stack trace you posted says that the required `params` param was not submitted with the request. That definitely should be in there though, regardless of whether “All” or specific caches are selected.

Are you sure it’s working for you if only specific caches are selected, rather than “All” ?

**Comment by bliswebagency** [comment]
You're right, i've just tried this again today to get a screen recording and it worked fine - odd

**Comment by bliswebagency** [comment]
I take that back - it seems if you need to go in to another section in the utilities before trying to clear the cache. 

Video 1 should show this  
https://kdoveton.com/craft/vid1.mov

Video 2 shows the behaviour when trying to deselect all, i reckon this might have something to do with it but notice it still cleared something 😕 
https://kdoveton.com/craft/vid1.mov

**Comment by bliswebagency** [comment]
closing as it seems fixed in rc5

**Comment by brandonkelly** [comment]
Glad to hear that :)
