### ISSUE TITLE
Multi-site not working in Craft 3 RC2

### ISSUE THREAD

**Issue by jolora** [craftcms/cms#2221]
My default site works fine but when I switch to the translated site ("/ru") I get the following error on anything other than the homepage:

```
yii\web\NotFoundHttpException: Template not found: ru/tester in /home/vagrant/Code/density.co.uk/vendor/craftcms/cms/src/controllers/TemplatesController.php:71
Stack trace:
#0 [internal function]: craft\controllers\TemplatesController->actionRender('ru/tester', Array)
#1 /home/vagrant/Code/density.co.uk/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /home/vagrant/Code/density.co.uk/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#3 /home/vagrant/Code/density.co.uk/vendor/craftcms/cms/src/web/Controller.php(80): yii\base\Controller->runAction('render', Array)
#4 /home/vagrant/Code/density.co.uk/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#5 /home/vagrant/Code/density.co.uk/vendor/craftcms/cms/src/web/Application.php(242): yii\base\Module->runAction('templates/rende...', Array)
#6 /home/vagrant/Code/density.co.uk/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#7 /home/vagrant/Code/density.co.uk/vendor/craftcms/cms/src/web/Application.php(207): yii\web\Application->handleRequest(Object(craft\web\Request))
#8 /home/vagrant/Code/density.co.uk/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /home/vagrant/Code/density.co.uk/web/index.php(21): yii\base\Application->run()
#10 {main}
```

It seems that it's passing the page URI to TemplatesController->actionRender rather than the template set in the section settings. In this example the template set for both sites is 'tester/_entry'. This is a single section... I have the same problem with a structure section.

My site config is basic:

en | en-GB | http://dev.density.co.uk/ (this is the "primary" site which works fine)
russian | ru | http://dev.density.co.uk/ru/

### Additional info

PHP version | 7.1.2-3
MySQL 5.7.17-0ubuntu0.16.04.1
GD 7.1.2-3+deb.sury.org~xenial+1
Craft Client 3.0.0-RC2
Yii version | 2.0.13.1
Twig | 2.4.4
Guzzle | 6.2.1
Imagine | 0.7-dev

**Comment by brandonkelly** [comment]
You need to actually create a `ru/` folder inside your web root, with its own `index.php` file (and `.htaccess` if running Apache), copied from your web root. Within `ru/index.php` make sure that the `CRAFT_BASE_PATH` constant is getting set correctly (it will need to go 1 level deeper than the web root’s version did), and also add a `CRAFT_SITE` constant, set to the handle of your `ru` site:

```php
define('CRAFT_BASE_PATH', dirname(__DIR__, 2));
define('CRAFT_SITE', 'ru');
```

**Comment by jolora** [comment]
Hi @brandonkelly - I had done exactly that.

In `/web/ru/index.php` I have:

```
<?php

define('CRAFT_SITE', 'ru');

// Set path constants
define('CRAFT_BASE_PATH', dirname(__DIR__, 2));
define('CRAFT_VENDOR_PATH', CRAFT_BASE_PATH.'/vendor');

// Load Composer's autoloader
require_once CRAFT_VENDOR_PATH.'/autoload.php';

// Load dotenv?
if (file_exists(CRAFT_BASE_PATH.'/.env')) {
    (new Dotenv\Dotenv(CRAFT_BASE_PATH))->load();
}

// Load and run Craft
define('CRAFT_ENVIRONMENT', getenv('ENVIRONMENT') ?: 'production');
$app = require CRAFT_VENDOR_PATH.'/craftcms/cms/bootstrap/web.php';
$app->run();
```

The homepage works fine - if I don't set the CRAFT_SITE properly or adjust CRAFT_BASE_PATH accordingly then the homepage won't even work. Could the issue be with the htaccess I have in /web/ru/. I just copied it directly from /web/ : 

```
<IfModule mod_rewrite.c>
	RewriteEngine On

	# Send would-be 404 requests to Craft
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteCond %{REQUEST_URI} !^/(favicon\.ico|apple-touch-icon.*\.png)$ [NC]
	RewriteRule (.+) index.php?p=$1 [QSA,L]
</IfModule>
```

**Comment by jolora** [comment]
@brandonkelly - it doesn't look like this is a new problem. It remains unsolved here from last year: https://craftcms.stackexchange.com/questions/11545/multi-locale-pages-404-on-subdirectories?rq=1

**Comment by jolora** [comment]
Thanks @hiasl 

My multisite config is pretty much identical (albeit for Russian) and my CRAFT_SITE value matches the handle.

Adding stuff to the .htaccess made no difference. And in a moment of clarity I've just realised why... I'm running nginx (Laravel Homestead) not Apache!! That must be the root of the issue.

**Comment by hiasl** [comment]
Then you definitely need some other configs instead of the mod_rewrite things :-)

**Comment by brandonkelly** [comment]
@jolora Doh, I guess I should have asked that. Here’s an example of how to set up your nginx config: https://craftcms.stackexchange.com/a/2007

**Comment by jolora** [comment]
@brandonkelly well it's one of those things that seems too obvious to even check I suppose! 

That being said it would probably still be worth mentioning nginx config in the new multi-site docs.

Thanks for your help.
