### ISSUE TITLE
Ressource field in a matrix cannot access variable and breaks when trying

### ISSUE THREAD

**Issue by ineghi** [craftcms/cms#2223]
### Description

Getting 'Could not resolve the subpath “work/{slug}”' when saving a entry containing an image in a matrix.

The images are then referenced in the temporary image within the ressource tab but not present in the server.

### Steps to reproduce

1. Create a matrix field
2. Add somehow an ressource(image) field inside
3. Restrict the folder location, specify something/{variable} (in my case, {slug})
4. Try to save a concerned entry
5. ...
6. Profit

### Additional info

- Craft version: Craft 3 RC2
- PHP version: 7.0.22-0
- Database driver & version: MySQL 5.7.20-0
- Plugins & versions:
   - Element api: 2.5.2
   - Expanded Singles: 3.0.1
   - Redactor: 1.0.0.1
   - SimpleMap: 3.1.1

**Comment by andris-sevcenko** [comment]
Shouldn't you use {owner.slug}, if the Asset field is inside a Matrix field?

**Comment by ineghi** [comment]
@andris-sevcenko Apparently ! :D Shouldn't it be documented somewhere ? (or it is and I'm definitly blind :P)
All these errors should be catched anyway. 

 Thanks Andris !

**Comment by andris-sevcenko** [comment]
Pretty sure it's [mentioned in the docs](https://craftcms.com/docs/assets-fields#dynamic-subfolder-paths) :)
