### ISSUE TITLE
Css Control panel issue

### ISSUE THREAD

**Issue by H-i-red** [craftcms/cms#2224]
### Description
![craftadmin](https://user-images.githubusercontent.com/19476159/34085476-bedf0ce2-e391-11e7-9b4a-cb40c20da6e6.png)

### Steps to reproduce

Happens on media query, it is a css issue.
Latest browser of Chrome/Firefox - Mac
```
#main-container #main #main-content {
    -webkit-box-flex: 1;
    -ms-flex: 1;
    flex: 1;
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    min-height: 0;
    -webkit-box-orient: horizontal;
    -webkit-box-direction: normal;
    -ms-flex-direction: row;
    flex-direction: row;
    -webkit-box-align: stretch;
    -ms-flex-align: stretch;
    align-items: stretch;
    width: calc(100vw - 225px);
}
```
Remove min-height: 0; on : _cp.scss line 597 fixes the issue..but do test first..

### Additional info

- Craft version: Craft Personal 3.0.0-RC2
- PHP version: 7.1.6
- Database driver & version: MySQL 5.6.35
- Plugins & versions: Redactor 1.0.0.1

**Comment by brandonkelly** [comment]
Fixed for RC3, thanks for reporting!
