### ISSUE TITLE
Unsaved data warning when nothing has changed

### ISSUE THREAD

**Issue by H-i-red** [craftcms/cms#2225]
### Description

![skarmavbild 2017-12-18 kl 01 30 04](https://user-images.githubusercontent.com/19476159/34085576-3c63960a-e393-11e7-8379-3442f2325498.png)

### Steps to reproduce

1. When using keyboard shortcut to save entries, the entry does not get that it is already saved!
 It works if you press the save button..

### Additional info
- Browser: Firefox 57.0.1 / MAC
- Craft version: Craft Personal 3.0.0-RC2
- PHP version: 7.1.6
- Database driver & version: MySQL 5.6.35
- Plugins & versions: Redactor 1.0.0.1

**Comment by H-i-red** [comment]
Hmm it happens all the time now, I don´t even have to change anything in the entry. If I try to go to other page, it complains and the modal/alert are showing..

**Comment by davidhellmann** [comment]
Yes, same here. 
Mac High Sierra
Chrome newest
RC2

**Comment by brandonkelly** [comment]
Turns out this was due to some HTML formatting done by Redactor fields on page load. Fixed for RC3. Thanks for reporting!
