### ISSUE TITLE
Globals not injected into error handling template

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#2230]
Craft CMS 3 RC 3

I have a `503.twig` error handling template for when the site is offline. I updated from Craft 3 RC2 to RC3, and went to the site, and as expected the `503.twig` template was shown on the frontend.

However, the site name, description, and a few other things come from a GlobalSet, which apparently wasn't injected into the template, because they were empty.

If I go to the error template directly via https://devmode.fm/503 it does properly display the data coming from the GlobalSet, so it must have something to do with the error handling code path.

**Comment by brandonkelly** [comment]
I just tested this locally and couldn’t reproduce. Global content is getting displayed correctly.
