### ISSUE TITLE
Plugin Store installation is broken on a fresh Digital Ocean/ServerPilot installation.

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#2234]
### Description

Plugin Store installation is broken on a fresh Digital Ocean/Server Pilot installation.

### Steps to reproduce

1. Create an Ubuntu DO droplet.
2. Let ServerPilot manage it.
3. Install Craft 3 RC3.
4. Try to install anything in the plugin store.

![capture](https://user-images.githubusercontent.com/61869/34184826-c8a2a568-e4d6-11e7-9b9f-497ff2a0ee2a.PNG)

### Additional info

- Craft version: Craft 3 RC3
- PHP version: 7.1
- Database driver & version: MySQL
- Plugins & versions: None

**Comment by kevindoveton** [comment]
Experienced this while trying to upgrade from RC1 to RC2 on another shared hosting platform - running composer update manually allowed me to update

**Comment by takobell** [comment]
I installed xDebug and got remote debugging connections working to see what the issue is... and now it works fine on the same box.  :-/

**Comment by takobell** [comment]
Likely the culprit: https://github.com/symfony/symfony/pull/25559

**Comment by takobell** [comment]
> HOWEVER, If you have xdebug installed, it won't affect you.

Because of course.

**Comment by narration-sd** [comment]
chortle chortle... :)

I wonder if just possibly there's a way to use the 'listen for debug' ability of PhpStorm could be useful in some contorted way, if startup not actually debugging might let the fault show.

Not fully thought through, and only because I recently discovered how useful this could be with Ajax-ed in calls, which might be a  hint also, but otherwise I guess it's back to good old Craft::dd()

**Comment by narration-sd** [comment]
...cheers, Brad :) ....

**Comment by matt-adigital** [comment]
Just encountered this issue myself on a digital ocean / serverpilot box after updating a site from RC1 to RC3 and then attempting to update the redactor plugin.

I got around it by downgrading my php version to 7.0 which then allowed me to update redactor successfully without any errors, I then set my php version back to what it was and all is working. I hope that helps anyone else who might be affected by this.

**Comment by angrybrad** [comment]
The fix is included in Symfony [3.3.15](https://github.com/symfony/symfony/releases/tag/v3.3.15), [3.4.3](https://github.com/symfony/symfony/releases/tag/v3.4.3) and [4.0.3](https://github.com/symfony/symfony/releases/tag/v4.0.3), so anyone running into this issue in Craft should just `composer update`, which will bring in the fix.
