### ISSUE TITLE
Creating multiple new matrix blocks in an entry draft does not work

### ISSUE THREAD

**Issue by phoob** [craftcms/cms#2235]
### Description

When I try to add multiple matrix blocks to a matrix field in an entry draft, only one of them gets saved.. 

### Steps to reproduce

1. Open an existing entry
2. Save as draft
3. Add two new matrix blocks
4. Save. Only one gets saved (or none, if I use the shortcut `cmd`+`s`)

See attached gif:

![des -20-2017 15-55-25](https://user-images.githubusercontent.com/1475800/34212996-4696699c-e59e-11e7-9a9e-ee84d2a31ba5.gif)

### Additional info

- Craft version: Craft 3 RC3
- PHP version: 7.0
- Database driver & version: Mariadb, mysql, latest stable.
- Plugins & versions: element-api, redactor.

**Comment by phoob** [comment]
Thanks!

**Comment by brandonkelly** [comment]
Thanks for reporting!
