### ISSUE TITLE
Asset fields does not store the default value.

### ISSUE THREAD

**Issue by H-i-red** [craftcms/cms#2238]
### Description

Asset fields does not store the default value, it stores the first available value.

### Steps to reproduce

1. Add a dropdown field to a Asset Volume.
2. Set the default value (not the first value)

### Additional info

- Craft version: Craft Personal 3.0.0-RC3
- PHP version: 7.1.6
- Database driver & version: MySQL 5.6.35
- Plugins & versions: —

**Comment by brandonkelly** [comment]
The default value will only apply to newly uploaded assets, not existing ones.

**Comment by H-i-red** [comment]
Well for me it does not work.

**Comment by H-i-red** [comment]
I noticed some issues regarding matrix field and default values as well. Add multiple drop downs, try to set the default value, it does not save the default value upon saving the field. It reverts back to no default. (the checkbox mark dissapears)
