### ISSUE TITLE
Populate Models Functionality

### ISSUE THREAD

**Issue by putyourlightson** [craftcms/cms#2239]
### Description

Craft 2 used its own BaseModel which had the very handy [populateModels()](https://craftcms.com/classreference/models/BaseModel#populateModels-detail) method which allowed populating models from an array of records in a single line:

`$myPluginModels = MyPluginModel::populateModels($myPluginRecords);`

Is there any way to achieve this in Craft 3  without having to loop through each record?

```
$myPluginModels = [];
foreach ($myPluginRecords as $myPluginRecord) {
   $myPluginModel = new MyPluginModel();
   $myPluginModel->setAttributes($myPluginRecord->getAttributes());
   $myPluginModels[] = $myPluginModel;
}
```
### Additional info

- Craft version: 3.0.0-RC3

**Comment by takobell** [comment]
> Is there any way to achieve this in Craft 3 without having to loop through each record?

Not really.  Here's the general pattern we've settled on, which you may or may not find cleaner:

    $myResults = MyRecord::find()->all();

    foreach ($myResults as $key => $value) {
        $myResults[$key] = new MyModel($value->toArray([
            'property1',
            'property2',
            'property3',
        ]));
    }

    return $myResults;

**Comment by putyourlightson** [comment]
Hmm ok, I wonder if this is worth adding as a feature request to Yii2.

**Comment by putyourlightson** [comment]
Any chance you might consider adding it to `craft\base\Model`?

**Comment by brandonkelly** [comment]
I’d rather not. In general we are trying to avoid adding things that feel like Yii’s turf in Craft 3, unless it’s sorely needed and Yii isn’t going to add it. Definitely worth bringing up an issue at https://github.com/yiisoft/yii2/issues though.

**Comment by putyourlightson** [comment]
I did and it doesn't seem to be a strong enough case: 
https://github.com/yiisoft/yii2/issues/15403

For now I've just created my own Base Model with this functionality.
