### ISSUE TITLE
Target _blank

### ISSUE THREAD

**Issue by H-i-red** [craftcms/cms#2240]
### Description

Please don´t use target `_blank` to preview entries in the cms, the user will end up with 1 miljon tabs..use a “targeted” preview `<a target="preview"...`

**Comment by carlcs** [comment]
I think it’s reasonable to use it for links to the website front-end.

**Comment by H-i-red** [comment]
uhm yeah but it you use a predefined target as i mentioned it will of course open up in a new tab, not replace the admin window.. it will replace the target window !

**Comment by carlcs** [comment]
Sorry, I missed that you set the `target` attribute to a named target `preview`. Thought it’s about the link to an entry’s preview.

Can you list examples for links where you find `_blank` misplaced?

**Comment by H-i-red** [comment]
Probably like everywhere, take the entries view in the admin for example, you click the uri or link button(a tag) in the table view.. it opens up a **new** window all the time, leaving you with a lot of windows(tabs)..if you don´t close it afterwards manually.. If you name your new window with a specific name, for instance `target="santa"` it will open up a new window, and you can leave it there..go back to admin hit another entry preview button - THEN it take you to the "SANTA" window and replace that page with the new entry.. 

Hope I make myself clear.. and it´s no issue really it´s more of a suggestion for good UI..

**Comment by Rias500** [comment]
There's 3 different ways this could be solved:

- Keep everything that goes to the front-end `_blank` (current behaviour)

- Open entry links in a `target="preview"` tab, which causes the tab to refresh when you click a preview link

- Open entry links in a `target="preview-{id}"` tab which opens a new tab for each entry you click open, but refreshes the tab if you already have one open for that entry.

**Comment by lindseydiloreto** [comment]
With all due respect, this feels like it will cause more problems than it solves. I've downvoted mainly for that reason. Overall, it feels like _unusual behavior which may be confusing_.

I vote to keep the existing behavior.

**Comment by brandonkelly** [comment]
Not going to do this. Someone could end up browsing to another website in the `preview` tab (all the more likely if there’s only one), and then clicking another `target="preview"` link would bring the tab back to their Craft site, unexpectedly losing the page they were on.
