### ISSUE TITLE
Helvetica Neue

### ISSUE THREAD

**Issue by H-i-red** [craftcms/cms#2241]
### Description

**Helvetica Neue**,  are not the best use for a interface font : New font suggestion: `Source sans pro`. https://fonts.google.com/specimen/Source+Sans+Pro or se @Rias500 below, which is a great suggestion.

**Comment by Rias500** [comment]
I suggest using the system default fonts (like Github does) which will always make it look good regardless of the OS:

`font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"`

**Comment by nternetinspired** [comment]
@H-i-red Might I suggest you show a little more respect in your communications? Craft CMS is not FOSS project where people just rock up, toss their ideas into a big hat and demand the project leads ask the community to vote on them, thankfully. 

Beyond that, there's always real people with feelings on the receiving end of such comments.

> …hire a designer?

Please. That is very disrespectful.

You don't like Helvetica Neue? Fine, that's your _opinion_. I'm sure no one minds you voicing an opinion, but it is just that, _your opinion_.

**Comment by H-i-red** [comment]
@nternetinspired thanks for letting me now, I am from Sweden, will work on my communication skills..edited it !

**Comment by narration-sd** [comment]
Good conversation, and nice holidays to both.

I don't have anything strongly against Helvetica Neue yet, if for long texts I possibly would, but it's also not a normally present Win font.

So on both counts, Rias's idea is quite possibly a good one.

**Comment by brandonkelly** [comment]
Thanks for the feedback @H-i-red. Ended up going with @Rias500’s suggestion of using default system UI fonts like GitHub does. (Also doing the same for `fixed width` fonts.) Definitely makes the UI a bit more readable, so I’m happy with it.
