### ISSUE TITLE
Saving an Entry with a dynamic title that gets too long will throw only a general warning

### ISSUE THREAD

**Issue by medoingthings** [craftcms/cms#2242]
### Description
I have an entry type where the title field is set to the value of the copy field (`{copy}`). When I try to save an entry that has quite a bit of copy text, Craft will just get back to me with a general error "Couldn’t save entry", but without any hint why.

It’s an easy fix by having `{copy|slice(0,20)}` as the title value, but I’d expect Craft to give me a more informative message like "title is too long" or something alike.

Craft 3 RC3

### Steps to reproduce

1. Create an entry type with the title value set to a customField with plaintext
2. Create a new entry and put a lot of text into that customField
3. Try to save the entry

### Additional info

- Craft version: Craft 3 RC3
- PHP version: 7.18
- Database driver & version: MySQL
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Thanks for pointing that out!
