### ISSUE TITLE
Twig macro errors show unformatted stack traces

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#2243]
### Description
With devMode on, Craft is showing normally formatted stack traces in most cases. However, make an error in a Twig macro, and an unformattet stack trace appears -- quite hard to read

### Steps to reproduce

1. have a twig macro, simple is fine
2. introduce an error in it, for example, misspell a macro parameter where used
3. stack trace shows, but unformatted

### Additional info

PHP version	7.1.11-1+ubuntu16.04.1+deb.sury.org+1
Database driver & version	MySQL 5.7.20-0ubuntu0.16.04.1
Image driver & version	GD 7.1.11-1+ubuntu16.04.1+deb.sury.org+1
Craft edition & version	Craft Pro 3.0.0-RC3
Yii version	2.0.13.1
Twig version	2.4.4
Guzzle version	6.2.1
Imagine version	0.7-dev
Plugins yes

**Comment by brandonkelly** [comment]
Not able to reproduce this. Can you post the stack trace?

**Comment by narration-sd** [comment]
Ok, this one is more tricky, not related to #2244, even if similar circumstance.

Trace by copy-paste from View Source is at bottom. On browser, of course no line breaks show from the newlines, so it's just a mass of unformatted text. I can when this happens and when it doesn't, with a simple change.

Here is the issue, based on the macro just below:
- for this demo, the issue of #2244 not just fixed, but code commented out, so that there's  no modification of hook context at all
- if the {% hook %} call is at the beginning of the macro, as shown, there's no formatting of the error and stack trace from the error introduced by misnaming the param 'portionx'/
- if the hook call is  moved to the end of the macro code, below the div, then the error comes out formatted nicely, just as you expect. 
- And, with the hook call at the end, there is no stack trace at all - just the nicely presented Twig error,
plus cookie and session data blocks
- by the way, am I off base to think we don't always see nice Twig errors, but sometimes/often a stack trace without Twig error explanation?? If this is true, perhaps related to what's going on here...

The simple macro, slightly sanitized to protect the guilty:
```
{% macro insert(portionx) %}
  {% hook "yyy-xxx" %}
  <div class="xxx-insert">
    {% include "xxx/" ~ portion %}
  </div>
{% endmacro %}
```

The error text, from view-source of page for clarity (direct browser view has no line breaks or other formatting): 

```
  | Exception 'Twig_Error_Runtime' with message 'Variable "portion" does not exist.'
-- | --
  |  
  | in /home/vagrant/seventh-page_html/templates/vue/insert_macros.html:7
  |  
  | Stack trace:
  | #0 /home/vagrant/seventh-page_html/storage/runtime/compiled_templates/e0/e061cc380b2b8fe8323f264efb022fd62991ca8d4bcd6d63e2b7ad3148f608ad.php(40): __TwigTemplate_f1cf96b0f6d83a05a9fb4a8f74c0be4d2b91f43fb8f3ee34922c39d97f011139->{closure}()
  | #1 /home/vagrant/seventh-page_html/storage/runtime/compiled_templates/6e/6e32b499b5cdf9312aa6803b273c5257db08a34668fd52524d9c6cadfdad3a80.php(57): __TwigTemplate_f1cf96b0f6d83a05a9fb4a8f74c0be4d2b91f43fb8f3ee34922c39d97f011139->macro_insert('app_insert')
  | #2 /home/vagrant/seventh-page_html/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_84474c17041944f36c7722965bba3dcc64ce0312648aec0143e9d81c184d2ab1->doDisplay(Array, Array)
  | #3 /home/vagrant/seventh-page_html/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
  | #4 /home/vagrant/seventh-page_html/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
  | #5 /home/vagrant/seventh-page_html/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
  | #6 /home/vagrant/seventh-page_html/vendor/twig/twig/lib/Twig/Template.php(374): craft\web\twig\Template->display(Array)
  | #7 /home/vagrant/seventh-page_html/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
  | #8 /home/vagrant/seventh-page_html/vendor/craftcms/cms/src/web/View.php(292): Twig_Environment->render('weasel/index', Array)
  | #9 /home/vagrant/seventh-page_html/vendor/craftcms/cms/src/web/View.php(340): craft\web\View->renderTemplate('weasel/index', Array)
  | #10 /home/vagrant/seventh-page_html/vendor/craftcms/cms/src/web/Controller.php(121): craft\web\View->renderPageTemplate('weasel/index', Array)
  | #11 /home/vagrant/seventh-page_html/vendor/craftcms/cms/src/controllers/TemplatesController.php(79): craft\web\Controller->renderTemplate('weasel/index', Array)
  | #12 [internal function]: craft\controllers\TemplatesController->actionRender('weasel/index', Array)
  | #13 /home/vagrant/seventh-page_html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
  | #14 /home/vagrant/seventh-page_html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
  | #15 /home/vagrant/seventh-page_html/vendor/craftcms/cms/src/web/Controller.php(80): yii\base\Controller->runAction('render', Array)
  | #16 /home/vagrant/seventh-page_html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
  | #17 /home/vagrant/seventh-page_html/vendor/craftcms/cms/src/web/Application.php(242): yii\base\Module->runAction('templates/rende...', Array)
  | #18 /home/vagrant/seventh-page_html/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
  | #19 /home/vagrant/seventh-page_html/vendor/craftcms/cms/src/web/Application.php(207): yii\web\Application->handleRequest(Object(craft\web\Request))
  | #20 /home/vagrant/seventh-page_html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
  | #21 /home/vagrant/seventh-page_html/web/index.php(21): yii\base\Application->run()
  | #22 {main}
```

**Comment by brandonkelly** [comment]
I just created the following template:

```twig
{% macro insert(portionx) %}
    {% hook "yyy-xxx" %}
    <div class="xxx-insert">
        {% include "xxx/" ~ portion %}
    </div>
{% endmacro %}

{% from _self import insert %}
{{ insert('x') }}
```

And loaded it from a browser, and got the normal-looking Yii-styled error details view.

<img width="823" alt="screen shot 2017-12-27 at 2 14 23 pm" src="https://user-images.githubusercontent.com/47792/34394763-47122ae2-eb10-11e7-8274-fbc28a4f90bb.png">

Can you post the PHP code you’re latching onto the hook with?

**Comment by narration-sd** [comment]
Hmm. Ok, here is simplified version. Summary: I only read context, not modify it, in the still-problem-showing test.

Hook access in Plugin.php init():
```
        Craft::$app->getView()->hook('yyyy-xxx',
            function (&$context) {

                $post = Craft::$app->request->post();

                $dataata = empty($post)
                    ? $this->sources->onePlace($context)
                    : $this->sources->fromPreview(anotherPlace$post, $context);

                return '<div id="zzzz">'
                    . $data
                    . '</div>';
            }
        );
```
and the context-accessing block in called func, which develops the $data for the inserted div:

```
        if(\count($context) && \array_key_exists('entry', $context)) {
            $entry = $context['entry'];
        }
```

**Comment by narration-sd** [comment]
Well. Interrupted by something else, realized that it would be easier for me to track at least some more of this down at this end, given you show a working case especially.

Turned out to be especially so, as this one is a pretty deviant case...

- that little code which was the only access on $context isn't relevant -- and turns out to be surplus left over in the module from development, as the result isn't used any more.
- I tested by replacing the real call to `anotherPlace()` with its text results -- macro error handling then looked as yours, fine.
- a small amount of dumping and headscratching later, I realized the problem isn;'t in the data. It's rather in the fact that what is really in `anotherPlace()` is an extra controller, one of Craft's, being run by itself. You may recall where we've discussed I did this, for advancing purposes...
- Apparently running that extra controller out of the usual chain of command disturbed the report handling when the macro error triggered it.  
- That it was run from the plugin `init()` method might well have to do with that disturbance.

Conclusion: 
- unless something obvious occurs to you, I don't think it's fair to ask this odd case be handled.
- the deliverable package will include the error-free macro
- I'll at least put in a nota bene about what might be seen if user makes another errored macro
- Can't see where I can pick this one off myself, but what I could do is put in a config that would bypass this call for a troubleshooting session should someone run into this.

Any thoughts, you know where to send, and I will close this; can always re-open...thanks, Brandon.

**Comment by narration-sd** [comment]
Correction: the hook setup is run from the plugin init, but the callback comes from the Twig interpretation.

Thus it's just something about the controller run in the unexpected spot during template response, not order otherwise, which causes the problem.

I'll send you the actual routine via support, as not wanting to publicize just now.

**Comment by narration-sd** [comment]
I'll also leave that hook call last in the project's macro, with a note, which should help at least with avoiding the problem, depending on order of anything the developing user might add...

**Comment by narration-sd** [comment]
Just a note to properly close this. The problem came because a controller called out of normal sequence set the Response to raw. There was normally an event used to reset this, but in the Twig interpretation error case, the event wasn't triggered, leaving formatting set to raw -- hence the result.

Brandon suggested a different pattern, which works well. This is to install a dummy Result in Craft::$app for the duration of the extra controller run, then put the original back. Errors and their stack traces now keep proper formatting.
