### ISSUE TITLE
Twig macro variables disappear with error after Twig/Craft hook statement

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#2244]
### Description
A Twig macro that works fine fails if a {% hook "hookname" %} is introduced before any part of the macro body. 

Temporary workaround can be to place the hook after the macro body, still withn the macro, if this will give usable order (e.g. for displsy:none element)

### Steps to reproduce

1. Have a working Twig macro with some body action using passed param and/or variable
2. introduce a valid Twig/Craft hook statement above use of param or variable
3. Macro fails with stack trace indicating the param or variable isn't known
4. move the hook statement to follow the rest of the macro body
5. Now both macro and hook function correctly

### Additional info

PHP version	7.1.11-1+ubuntu16.04.1+deb.sury.org+1
Database driver & version	MySQL 5.7.20-0ubuntu0.16.04.1
Image driver & version	GD 7.1.11-1+ubuntu16.04.1+deb.sury.org+1
Craft edition & version	Craft Pro 3.0.0-RC3
Yii version	2.0.13.1
Twig version	2.4.4
Guzzle version	6.2.1
Imagine version	0.7-dev
Plugins yes

**Comment by brandonkelly** [comment]
Not able to reproduce this. Can you post your Twig macro, as well as the PHP code you are using to connect to the hook?

**Comment by narration-sd** [comment]
Ok, that was the clue -- 'doh', to quote a certain personage...

I was adding an element to the hook context, but did it a wrong way, wiping the rest of context.

Hook works fine now, regardless of order in macro, closing.
