### ISSUE TITLE
Matrix Fields > Asset Block Type > path/to/subfolder variables don't seem to work

### ISSUE THREAD

**Issue by m8i** [craftcms/cms#2246]
### Description
On matrix fields, asset block types, the instructions say: "Note that the subfolder path can contain variables like {slug} or {author.username}."

However, when I use {author.username}, I get a 500 error on saving an entry because it is unable to resolve the path {author.username}. 

I've also tried {section.handle} and {entry.section.handle} - I was shooting in the dark for those, but I tried.

I do not have a folder created for each user, but the folder is writable by Craft and it is able to write image variations in that same assets folder.

### Steps to reproduce

1. Set a variable in an asset block on a matrix field
2. Edit (or create) an entry with
3. Save the entry
4. Receive error

### Additional info

- Craft version: 3.0.0-RC3 (Pro)
- PHP version: 7.0.22-0ubuntu0.16.04.1
- Database driver & version: MySQL 5.7.20-0ubuntu0.16.04.1
- Plugins & versions: 
    - Redactor 1.0.0.1
    - Control Panel Nav 2.0.2
    - Redirect plugin for Craft 3 1.0.11
    - Json Client 1.0.1

**Comment by brandonkelly** [comment]
If the field is used within a Matrix field, then you should use `{owner.author.username}` instead. `owner` will give you the “owner” element of the Matrix block (the entry).

**Comment by m8i** [comment]
I see that in the documentation now. Sorry! 
And thank you!

**Comment by wooge** [comment]
If you are like me and have a matrix inside of a super table, inside of a matrix, then you have to parent everything:    {owner.owner.slug}  in my case.
