### ISSUE TITLE
Error on the command line tool on RC3

### ISSUE THREAD

**Issue by webrgp** [craftcms/cms#2248]
I've caught a bug while developing a plugin. It's related to the command line tool.

`PHP Fatal Error 'yii\base\ErrorException' with message 'Class craft\queue\Command contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (yii\queue\cli\Command::isWorkerAction)'`

Craft Command class is extending Yii2 queue/Command.php but didn't implement the [isWorkerAction](https://github.com/yiisoft/yii2-queue/blob/f5ff5426f500f8065fcec1bfab0071f2b40f2ba7/src/cli/Command.php#L75) abstract method.

**Comment by webrgp** [comment]
For now, I've hardcoded a empty function, and it seems to fix the error, but I am not well versed enough in Yii to know if that would create unintended consequences.

**Comment by takobell** [comment]
Looks like it comes from a change in the new 2.0.2 queue release: https://github.com/yiisoft/yii2-queue/commit/10f74bb7b50a3814c4a917e4285b50e78b553265#diff-9a74ce881acb5860a1a9d2e2b3b85d25

**Comment by takobell** [comment]
Thanks for reporting it!

**Comment by webrgp** [comment]
What would be the best way for me to update my local version with this new update?

**Comment by takobell** [comment]
You can either wait for RC4 to be released (planned for Jan 2), or change your `craftcms/cms` requirement in `composer.json` to `"dev-develop as 3.0.0-RC99"`, and then run `composer update`.  That will always update from the latest commit in the repo.
