### ISSUE TITLE
Error template routing doesn't work

### ISSUE THREAD

**Issue by marknotton** [craftcms/cms#2251]
### Description

I can't find any mention of a breaking change [here](https://github.com/craftcms/docs/blob/master/en/changes-in-craft-3.md#remote-volumes). So I'm going to assume [the following](https://craftcms.com/docs/config-settings#errorTemplatePrefix) still stands to be the correct approach to routing error templates:

Adding this to the config/general.php file no longer routes to any error templates: `'errorTemplatePrefix' => "_errors/",`

In fact, even without the `errorTemplatePrefix` setting. Having the 400.twig, 403.twig, 404.twig, 500.twig, or 503.twig files in the root of the /templates/ doesn't work either. 

No adjustments have been made to the .htaccess file (not that it should matter anyway)

### Steps to reproduce

1. Go to a uri that doesn't exist. 

### Additional info

- Craft version: Craft 3.0.76 RC3
- PHP version: 7.1.8
- Database driver & version: MySQL 5.6.35
- Plugins & versions: n/a

### Stacktrace

```
yii\web\NotFoundHttpException: Template not found: fake in /Volumes/Mark Notton/Clients/Craft Master/Website/vendor/craftcms/cms/src/controllers/TemplatesController.php:71
Stack trace:
#0 [internal function]: craft\controllers\TemplatesController->actionRender('fake', Array)
#1 /Volumes/Mark Notton/Clients/Craft Master/Website/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /Volumes/Mark Notton/Clients/Craft Master/Website/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#3 /Volumes/Mark Notton/Clients/Craft Master/Website/vendor/craftcms/cms/src/web/Controller.php(80): yii\base\Controller->runAction('render', Array)
#4 /Volumes/Mark Notton/Clients/Craft Master/Website/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#5 /Volumes/Mark Notton/Clients/Craft Master/Website/vendor/craftcms/cms/src/web/Application.php(242): yii\base\Module->runAction('templates/rende...', Array)
#6 /Volumes/Mark Notton/Clients/Craft Master/Website/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#7 /Volumes/Mark Notton/Clients/Craft Master/Website/vendor/craftcms/cms/src/web/Application.php(207): yii\web\Application->handleRequest(Object(craft\web\Request))
#8 /Volumes/Mark Notton/Clients/Craft Master/Website/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /Volumes/Mark Notton/Clients/Craft Master/Website/public/index.php(23): yii\base\Application->run()
#10 {main}
```

**Comment by brandonkelly** [comment]
Do you have Dev Mode enabled? Craft 3 will always show Yii’s error details view (with the stack trace) when Dev Mode is enabled.

**Comment by marknotton** [comment]
*sign*, I hold my head in shame. That's exactly right Brandon. I'm not sure how I've never encountered this before. Sorry to have wasted your time on on my oversight. Thank you.

**Comment by brandonkelly** [comment]
Haha no worries :)
