### ISSUE TITLE
Allow customization of hasCpSettings

### ISSUE THREAD

**Issue by BenParizek** [craftcms/cms#2252]
### Description

The `PluginTrait::hasCpSettings` setting assumes your settings are in the Craft settings area. For more advanced plugins, it would be nice to have the option to override the settings URL and point the user to the CP area of the plugin where the settings are.

For example, in Sprout Forms, the settings area is located at: `sprout-forms/settings` and has several sub-tabs of settings.

### Steps to reproduce

template:  *src/templates/settings/plugins/index.html*

```
{% if config.hasCpSettings %}
  <a href="{{ url('settings/plugins/'~config.moduleId) }}"><span data-icon="settings"></span> {{ "Settings"|t('app') }}</a>
{% else %}
  <span class="light">—</span>
{% endif %}
```

### Additional info

- Craft version: RC3

**Comment by brandonkelly** [comment]
To accomplish this in Craft 3, override your plugin’s `getSettingsResponse()` method with this:

```php
public function getSettingsResponse()
{
    $url = UrlHelper::cpUrl('sprout-forms/settings');
    return Craft::$app->getResponse()->redirect($url);
}
```
