### ISSUE TITLE
Unable to drag fields to selected area in Field Layout with lots of fields 

### ISSUE THREAD

**Issue by BenParizek** [craftcms/cms#2253]
### Description

I have a Craft 3 site with a lot of fields. Once the field groups wrap down multiple rows on the page, I am unable to drag a selected field from the bottom of the page up to the area where it becomes selected.

### Steps to reproduce

1. Create 'one billion' fields (or just enough in different field groups to wrap things down the page)
2. Edit an Entry Type
3. Select a field that you have to scroll down to select. The area where you want to drop the field should not be visible when you select it and start dragging.
4. Drag it up until you are thwarted and the page doesn't scroll.
5. Resort to suboptimal workarounds.

### Additional info

- Craft version: RC3
- PHP version: 7.1
- Database driver & version: MySQL 
- Plugins & versions: Various under development

**Comment by shuckster** [comment]
Finding this out for myself too.

A work-around is to group the fields up, then take advantage of the alphabetical sorting and put the fields you want to use in the "A", "B" (etc) groups. :D
