### ISSUE TITLE
The Globals index page doesn't remember the user's last selected locale on a multi-locale install

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#2254]
### Description

If you change the locale filter dropdown on the entry index page, Craft updates `BaseElementIndex.locale` in locale application storage and sets that as the the default when the user loads that page at a later time.

Doing the same thing on the Globals index page never updates `BaseElementIndex.locale`, so it always resets to the primary locale.

### Steps to reproduce

1.  Have two locales in Settings->Locales.
2.  Create a Global Set and then a Global.
3.  Edit the Global and swap to language number 2.
4.  Leave the Global page and come back.
5.  Language number 1 is selected again. 

### Additional info

- Craft version: 2.x (and probably 3.x)
- PHP version: 7.0

**Comment by brandonkelly** [comment]
The locale/site selector on the Globals page actually redirects the browser to a different, locale/site-specific URL. The locale-specific content isn’t loaded over Ajax on the same page, like on element index pages. So unless we started remembering the selected locale in the PHP session, and factored that in whenever generating the CP nav, this isn’t something we can fix.
