### ISSUE TITLE
PlainText field Character Limit front/backend validation is off

### ISSUE THREAD

**Issue by divyan** [craftcms/cms#2257]
### Description
The front-end validation of character limit is different from the back-end validation. Because of this, the entry doesn't save.

### Steps to reproduce

1. Create a PlainText field and set Character Limit to let's say 160 and the rows to 4 with the Linebreaks on.
2. Create an entry with the field above and fill up the field with text with 160 characters with a few whitespaces and hard linebreaks within the content. Fill the content untill the counter in the bottom-right-corner of the textarea is 0.
3. Save the entry and an error will appear: [Fieldname] should contain at most 160 characters.

### Additional info

- Craft version: Craft CMS 3.0.0-beta.28
- PHP version: 7.0.3
- Database driver & version: MySQL 5.6.11
- Plugins & versions: None

**Comment by brandonkelly** [comment]
Guessing this also affects Craft 2.
