### ISSUE TITLE
Copy password reset shows ⌘C on Windows

### ISSUE THREAD

**Issue by Rias500** [craftcms/cms#2258]
### Description
When copying a password reset link, it shows '⌘' instead of 'Ctrl+' on Windows with the Chrome browser.

![afbeelding](https://user-images.githubusercontent.com/3626559/34489652-77706100-efdd-11e7-84a0-8446b1a59ed9.png)

This is probably because the check `(navigator.appVersion.indexOf('Mac') ? '⌘' : 'Ctrl-')` returns '⌘'

![afbeelding](https://user-images.githubusercontent.com/3626559/34489736-b77b8d42-efdd-11e7-9e3d-e89b7fe75286.png)

### Steps to reproduce

1. Open the prompt to copy a password reset link
2. See "⌘C" on Windows

### Additional info

- Craft version: 2.6 & 3

**Comment by brandonkelly** [comment]
This was fixed via 67abe08f14433766465cb351ea212f445be9a78f.
