### ISSUE TITLE
Documentation and changelog buttons in plugin store should probably open in a new tab

### ISSUE THREAD

**Issue by dreadfullyposh** [craftcms/cms#2260]
### Description
While the documentation and changelog buttons for each plugin in the plugin store are handy, it's not so handy when those buttons take you out of the CMS to get to them. Ideally these buttons would open a new tab.

### Steps to reproduce

1. Go to the plugin store
2. Click any plugin
3. Click documentation button or changelog button

### Additional info

- Craft version: 3.0.0-RC4
- PHP version: 7.0.
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Agree @benjamindavid
