### ISSUE TITLE
Default field values inside matrix blocks does not get saved

### ISSUE THREAD

**Issue by H-i-red** [craftcms/cms#2261]
### Description
Default field values inside matrix blocks does not get saved

### Steps to reproduce

1. Add multiple fields with default values, only one field will store the default value..

### Additional info

- Craft version: Craft Personal 3.0.0-RC4
- PHP version: 7.1.6
- Database driver & version: MySQL 5.6.35
- Plugins & versions:

**Comment by brandonkelly** [comment]
> Add multiple fields with default values, only one field will store the default value..

Can you please elaborate on that?

**Comment by H-i-red** [comment]
Yes I can.

1. Create multiple block types with "drop down" fields.
2. Set the default value for each one.
3. Save the matrix field, or just toggle between the fields, the checkbox mark is gone, and it does not store the default value. The last "checked" field are the only one, the rest "checked"(default) values are gone.

**Comment by brandonkelly** [comment]
Thanks, figured it out. Fixed for the next release!
