### ISSUE TITLE
{basePath} being written on Assets Volume folder's name

### ISSUE THREAD

**Issue by atimoda** [craftcms/cms#2263]
### Description
Craft is uploading assets to the wrong folder when using dynamic basePath, hard-writing the dynamic {basePath} on the folder's name.

### Steps to reproduce

1. Set an local Volume group with File System Path to: "{basePath}some/folder"
2. Upload a picture.
3. Craft now created a folder in the "public_html" with this exacly name: "/public_html/{basePath}some/folder", instead of the expected "/public_html/some/folder".

### Additional info

- Craft version: Craft Pro 3.0.0-RC4
- PHP version: 7.1.8
- Database driver & version: MySQL 5.6.35
- Plugins & versions:

**Comment by takobell** [comment]
You're probably defining `{basePath}` as a Craft 2 style [environment variable.](https://craftcms.com/docs/multi-environment-configs#environment-specific-variables)

They went away in Craft 3, but the recently released Craft 3 RC4, which it appears you're running, introduced an [`aliases`](https://github.com/craftcms/cms/blob/develop/src/config/GeneralConfig.php#L59) config setting where you can define custom [Yii aliases](http://www.yiiframework.com/doc-2.0/guide-concept-aliases.html).

Once you define your aliases in the config setting, you can reference them from a Volume's File System Path setting via: `@alias/some/folder`

Related issue here: https://github.com/craftcms/cms/issues/2250

**Comment by sethburtonhall** [comment]
I am experiencing this same issue and I am running Craft CMS 2.7.4. Any ideas?

**Comment by brandonkelly** [comment]
@sethburtonhall did you read https://github.com/craftcms/cms/issues/2263#issuecomment-355087771 ?
