### ISSUE TITLE
Folders in asset volumes cannot be toggled to open or close in RC4

### ISSUE THREAD

**Issue by bendesilva** [craftcms/cms#2264]
### Description

Toggle element with dropdown arrow in the assets sidebar is misaligned and as a result folders cannot be opened or closed on the assets page or window. The 10px value appears to have been removed from .toggle in _cp.scss

<img width="242" alt="screenshot 2018-01-03 14 12 32" src="https://user-images.githubusercontent.com/5658721/34524064-0798463a-f092-11e7-952e-123cc8fe5dc3.png">

### Steps to reproduce

1. Visit the assets page or bring up the window from a field, arrows are misaligned
2. Try and click a folder or volume to open or close

### Additional info

- Craft version: Craft Pro 3.0.0-RC4
- PHP version: 7.1.6
- Database driver & version:
- Plugins & versions: Amazon S3

**Comment by brandonkelly** [comment]
Thanks for reporting!
