### ISSUE TITLE
Improve Composer performance with Prestissimo

### ISSUE THREAD

**Issue by sjelfull** [craftcms/cms#2267]
### Description

[Prestissimo](https://github.com/hirak/prestissimo) is a Composer plugin that installs dependencies in parallel, and i've seen huge improvements in speed.

Could this be used in Craft too?

**Comment by angrybrad** [comment]
Semi-related: https://github.com/craftcms/cms/issues/2159

Had played with Prestissimo awhile back and wasn't getting much of a speed increase.  Willing to look at it again, though.

**Comment by brandonkelly** [comment]
@sjelfull If you add it to your project, it should get loaded when updating/installing things from the Control Panel. Have you done any speed comparisons?

**Comment by angrybrad** [comment]
Someone correct me if I'm wrong, but my experience with Pretissimo was that is parallelized the downloading of the required `.json` files (using `curl_multi`), but it still had to process the dependencies in a serial manner, which is where 90% of the memory and execution time of Composer is consumed.   Leaving open, but guessing that with [this commit](https://github.com/craftcms/cms/commit/3b88277fa9477e1594e6343b00d42ec1cb931112) (and further web service / Craft changes we could make), Prestissimo is more of a micro-optimization for our use-case.

**Comment by sjelfull** [comment]
@angrybrad you might be right, but if it doesn't hurt, consider it.

This is my hunch, but this should help with slow connections / bad latency. Could revisit after you you got all the custom composer stuff up and running.

**Comment by angrybrad** [comment]
Going to go ahead and close this since Composer 2 has added parallelization support natively.
