### ISSUE TITLE
Deprecation of first() and last()

### ISSUE THREAD

**Issue by shuckster** [craftcms/cms#2269]
It seems especially a shame to lose `last()`, since there's no way to use `nth(query.count() - 1)` in an Entry Title. For example, I have the following:

    { sessions.first().sessionDate|date("jS M") } to { sessions.last().sessionDate|date("jS M, Y") }

Yes, the issue I'm talking about is exclusive to Titles in the CP and doesn't affect general templating in terms of functionality, since there are alternatives. But I think conciseness is a great thing to have in a templating system.

**Comment by brandonkelly** [comment]
It is possible using full Twig syntax (which is allowed) and explicitly referencing the entry (`object`):

```twig
{{ object.sessions.nth(object.sessions.count() - 1).sessionDate|date("jS M, Y") }}
```

It’s not pretty, I’ll give you that.

The issue with `last()` is that it has always required two queries to get its result. The suggested replacement in the deprecation error is at least more clear that’s the case. However thanks to all the element query improvements in Craft 3, an even better option is available – you can use `orderBy()` + `one()` to get the result in a single query:

```twig
{sessions.orderBy('[[relations.sortOrder]] desc').one().sessionDate|date("jS M, Y")}

**Comment by shuckster** [comment]
Thanks for the explanation and alternative, I'm using that now. :)

**Comment by brandonkelly** [comment]
For posterity, here’s a link to section in the docs that explains this in more detail: https://github.com/craftcms/docs/blob/master/en/changes-in-craft-3.md#last
