### ISSUE TITLE
Field searching for empty/non-empty values is broken

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#2270]
### Description
Consider a plain text field `body`…

These work as expected:

```php
$entries = Entry::find()->body(':notempty:');
$entries = Entry::find()->body(':empty:');
```

This however, does not (following [2.x docs](https://craftcms.com/docs/searching):

```php
$entries = Entry::find()->search('-body:*'); // 0 results
$entries = Entry::find()->search('body:*'); // inconsistent results with Entry::find()->body(':notempty:') 
```

For the hell of it I also tried this with no luck,
```php
$entries = Entry::find()->search('body:":notempty:"'); // 0 results
$entries = Entry::find()->search('body:":empty:"'); // 0 results
```

The above results are the same when typing the string values into a CP search.

Also, `:notempty:` and `:empty:` were never documented when added to 2.x, so it would be good to know if they are sticking around, and if they ever relevant to _searching_ or if they should just be used in ElementQuery attributes.

### Additional info

- Craft version: 3 RC.4
- PHP version: 7.1
- Database driver & version: MySQL 5.7

**Comment by brandonkelly** [comment]
Thanks for the heads up - fixed for RC5!
