### ISSUE TITLE
Select field options in the control panel have no background color.

### ISSUE THREAD

**Issue by sbossarte** [craftcms/cms#2272]
As of Craft 3.0.0-RC4, `option` elements under `select` inputs in the control panel will use system theme colors as their background in Firefox/IE on Windows (and possibly other browser/OS combinations). Attached is an example of what this winds up looking like:

![dropdown](https://user-images.githubusercontent.com/10968087/34587836-97b33328-f16f-11e7-8ade-3b40c003fc63.png)

**Comment by angrybrad** [comment]
Tested the latest Craft RC4 on Windows 10 with Firefox Quantum 57.0.5, Internet Explorer 11.125 and Microsoft Edge 41.16299 and am not able to reproduce after playing around with several theme settings.  Can you track down which theme setting is causing the issue?

**Comment by sbossarte** [comment]
Sorry, I should have been a bit more specific in that I'm seeing this on Windows 7. It is the "Window" primary color in the "Window Color and Appearance" menu.

Here's an example, with Firefox 57.0.3 https://user-images.githubusercontent.com/10968087/34644448-7b436f94-f2fc-11e7-9692-44da1d9d2d0c.png
