### ISSUE TITLE
proposal: use 'craft setup --interactive' to read config parameters from env vars 

### ISSUE THREAD

**Issue by noandrea** [craftcms/cms#2273]
### Description

The command `craft setup` is interactive and cannot be used in an automated way. There is an optional parameter `--interactive` (that seems to be ignored) that could be used to instruct the command line tool to read the parameters from environment variables. 

This will be extremely helpful in context where the setup is automated. In particular using Docker with Craft. 

### Additional info

- Craft version: 3.0.0-RC4
- PHP version: 7.1.7
- Database driver & version: MySQL 5.7.20
- Plugins & versions: None

**Comment by brandonkelly** [comment]
I’d rather not add support for a bunch of new arguments to the `setup/index` command, but as of the next release it will be possible to run `setup/db-creds` non-interactively. (`install/index` already supported non-interactive execution.)

So here’s what your setup script should run, for fully non-interactive setup & installation:

```
craft setup/security-key
craft setup/db-creds --interactive=0 --database=<database> --user=<db-user> --password=<db-password>
craft install --interactive=0 --email=<email> --username=<username> --password=<password> --siteName=<site-name> --siteUrl=<site-url>
```

Tag | Replace with
-- | --
`<database>` | Your  database name
`<db-user>` | Your database username
`<db-password>` | Your database password
`<email>` | The admin account’s email
`<username>` | The admin account’s username
`<password>` | The admin account’s password
`<siteName>` | The site name (wrap with `"`s if multiple words)
`<site-url>` | The site’s base URL

**Comment by noandrea** [comment]
sounds good to me, thanks!
