### ISSUE TITLE
`Craft.postActionRequest` using CP trigger (in addition to Actions trigger)

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#2279]
**Craft Pro 3.0.0-RC4**

---

I'm not 100% sure, but it seems like `Craft.postActionRequest` is generating an action path which **includes the full admin URL**.

For example, if I do this...

```js
Craft.postActionRequest('my-plugin/my-controller'...
```

It tries to ping the wrong URL...

    SHOULD PING
    actions/my-plugin/my-controller
    
    ACTUALLY PINGS
    admin/actions/my-plugin/my-controller

Which spits out this error:

> POST http://mysite.com/index.php?p=admin/actions/my-plugin/my-controller 500 (Internal Server Error)

It seems like **`admin/actions`** is an obvious error... why would it include the CP trigger _and_ the actions trigger? Or am I mistaken about how this is supposed to work in Craft 3?

**Comment by lindseydiloreto** [comment]
Hmm... as I dive deeper, it seems like `actions/` and `admin/actions/` should **both** work. It looks like I may have been bumping into errors elsewhere.

Can you confirm that both action paths are valid?

**Comment by brandonkelly** [comment]
Both are supposed to be there, yes.

**Comment by lindseydiloreto** [comment]
Good to know, thanks @brandonkelly!

Sorry for the false alarm.

<img src="http://memeshappen.com/media/created/-my-bad-meme-44244.jpg">
