### ISSUE TITLE
Craft.EditableTable.getRowHtml has been removed?

### ISSUE THREAD

**Issue by Nav33d** [craftcms/cms#2280]
### Description

`Craft.EditableTable.getRowHtml()` has been removed from EditableTable.js. Is this intentional? It throws an error when setting up Table field and our Table Maker plugin depends on this too.

Many thanks for your help :)

### Additional info

- Craft version: 3
- PHP version: 7.0
- Database driver & version: MySQL
- Plugins & versions:

**Comment by brandonkelly** [comment]
It has been replaced with `createRow()`, which returns a jQuery object for the `<tr>`, instead of the raw HTML. If you just want the HTML, you can call `createRow(...).html()`.
