### ISSUE TITLE
Entry list table displays field value instead of label

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/cms#2282]
### Description

When displaying a field value in an entry list table, the field value is displayed rather than the human-friendly label.

### Screenshot

<img width="117" alt="screen shot 2018-01-08 at 14 49 59" src="https://user-images.githubusercontent.com/24975058/34676020-3e5bc6c0-f483-11e7-9006-116e6b08a63e.png">

### Steps to reproduce

1. Create dropdown field
2. Set field value to display in an entry list table
3. Values displayed are that of the field value, rather than the human-friendly field label

### Additional info

- Craft version: Craft Pro 3.0.0-RC4
- PHP version: 7.2

**Comment by brandonkelly** [comment]
Thanks for pointing that out!
