### ISSUE TITLE
Dollar sign in database password can cause wrong value saved in .env

### ISSUE THREAD

**Issue by chrissam42** [craftcms/cms#2283]
### Description

When running the `craft setup` command line install, a database password with a dollar sign followed by a number gets saved wrong in the `.env` configuration file.

### Steps to reproduce

1. Run `craft setup`
2. Configure a database connection with password `craft$4u`
3. Complete the installation
4. `.env` contains `DB_PASSWORD="craftu"`

### Additional info

- OS: Linux, CentOS 7.4
- Craft version: 3.0.0-RC1 (Yii version 2.0.13.1)
- PHP version: 7.1.13
- Database driver & version: mysqlnd 5.0.12-dev
- Plugins & versions: Fresh install

**Comment by brandonkelly** [comment]
Thanks! Fixed for the next release.
