### ISSUE TITLE
&amp; in image transformation URLs generated by getUrl()

### ISSUE THREAD

**Issue by hiasl** [craftcms/cms#2286]
### Description
When I output an image transformation URL like this:
`{{ entry.headerBackgroundImage.one().getUrl({width: 1440}) }}`

I will get this as a URL
`<host>/index.php?p=actions/assets/generate-transform&amp;transformId=364`

This is supposed to work in image tags `<img src="...">` but does not seem to work as inline css background image url (at least in Chrome). When I replace the `&amp;` with & it works (or if i pipe it through the raw filter)

Is this expected behaviour? I guess this has changed, because I just updated from beta34 to RC4 and this problem did not happen before.

### Steps to reproduce

1. Create an inline css with a background image url
2. Use TWIG to dynamically output a transformation URL

The background image won't load unless you pipe it through the raw filter:
`{{ entry.headerBackgroundImage.one().getUrl({width: 1440}) | raw }}`

### Additional info
PHP version	7.1.6
Database driver & version	MySQL 5.7.20-0ubuntu0.16.04.1
Image driver & version	Imagick 3.4.3, ImageMagick 6.9.6-2
Craft edition & version	Craft Pro 3.0.0-RC4

**Comment by brandonkelly** [comment]
`getUrl()` is actually returning just plain `&`, but Twig will automatically convert that to the `&amp;` entity when it’s output, via the `{{ ... }}` tag.

That’s generally correct behavior – i.e. you want it to be `&amp;` when the URL is being output to an `<img src="">` attribute. For times where you want it to stay just `&`, use the `|raw` filter, as you’ve discovered will work.
