### ISSUE TITLE
My.cnf not generated by database backup utility

### ISSUE THREAD

**Issue by alexstojda** [craftcms/cms#2291]
### Description
Generating Database backup fails 

Does not seem to generate the 'my.cnf' referenced by the shell command. I tried manually pasting the command from the logs into the shell and got: 
`Could not open required defaults file: CRAFTPATH\storage\runtime\temp\my.cnf
Fatal error in defaults handling. Program aborted`

### Steps to reproduce

1. Navigate to utilities -> database backup
2. Click Backup 
3. Error message appears saying unsuccessfull

### Additional info

PHP version | 7.0.26
MySQL 5.5.5-10.1.29-MariaDB
GD 7.0.26
Craft Pro 3.0.0-RC5
No plugins

**Comment by angrybrad** [comment]
Is `CRAFTPATH` literally in the path it's trying to reference or did you just redact the actual path?

**Comment by alexstojda** [comment]
I redacted the path

Upgrading from RC3 to RC5 fixed this issue
