### ISSUE TITLE
Control panel UI for static translations

### ISSUE THREAD

**Issue by thaoms** [craftcms/cms#2294]
Hello

We let our clients fill in their own translations. (Belgium has three official languages)
That often includes static translations.

We can't just send them php files so I was wondering if this ever gets included in the control panel?
A simple UI is much more clear for less technical clients.

There used to be an old plugin for Craft 2, but this has been abandoned a while ago.
(https://github.com/boboldehampsink/translate)

I am using globals to simulate this now, but I guess that's not why globals were made.

Thank you!

**Comment by brandonkelly** [comment]
I could see this being a Utility. Though UI copy is a perfectly valid use case for globals :)

The main reason static translations exist is for Control Panel copy (for Craft and plugins), which doesn’t require an optimized author-facing UI for being customized.

**Comment by outline4** [comment]
In Switzerland we have 4 official Languages. There's a real need for static translation that can be edited in the CP. Globals work, but there's too much work involved to set it up...

So a utility would be really great! 

Thanks

**Comment by smcyr** [comment]
It would be nice, because if you have hundred of strings to translate across the website, if you do a field per strings in the globals, the database will have too many columns in the "content" table.
Thanks

**Comment by thaoms** [comment]
I stumbled upon this one, didn't use it yet but it looks good.
https://enupal.com/en/craft-plugins/translate

**Comment by bertheyman** [comment]
This would really be a nice feature!
Someone created a [plugin](https://github.com/MutationDigitale/craft3-translate), but would prefer this as a native Craft feature. (ongoing support + make sure it keeps up with other new Craft features)
