### ISSUE TITLE
Custom field labels are not translated in element indexes

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#23]
#### Environment:

- Craft version: 3.x
- PHP version: 7.x
- Database driver & version: n/a 
- Plugins & versions:

#### Description:

In the new Customizable Element Indexes (CEI), it appears that field labels aren't translated – see http://cly.mmikkel.no/3P3v1F0a0R1y for an example (the value "field.label.featuredImage" is found in /translations/{locale}.php and is translated everywhere else throughout the CP but here).

**Comment by brandonkelly** [comment]
Not able to reproduce this in v2 or v3. Custom field labels are getting translated properly in both the Customize modal and the table headers.
