### ISSUE TITLE
Make BaseOptionsField::multi public

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#2302]
### Description

`BaseOptionsField::multi` is currently `protected`, which can be annoying when dealing with a group of fields programatically.

Since `BaseOptionsField::multi` isn't public, you're forced to test against something like `instance of craft\fields\Checkboxes || instanceof craft\fields\MultiSelect` which is not ideal.

### Additional info

- Craft version: 3 RC5
- PHP version: 7.1

**Comment by brandonkelly** [comment]
`$multi` shouldn’t be settable by anything other than the implementing class, so it should stay protected. I just added a public `getIsMultiOptionsField()` method to `craft\fields\BaseOptionsField` though, which returns the `$multi` value, so you can just start calling that to get the value.

**Comment by timkelty** [comment]
Ah yes, that's much better. Thanks!
