### ISSUE TITLE
After Template form-submission, Asset folders are created even when there's nothing to put in them

### ISSUE THREAD

**Issue by shuckster** [craftcms/cms#2303]
### Description

When `Default Upload Location` is set to a dynamic value, such as the current-date, folders will be created when submitting a form with an upload-button, but has no actual file selected.

### Steps to reproduce

1. Enter a `Default Upload Location` of `{now|date('Y-m-d-H-i-s')}`
2. Open a form with an `<input type="file">`, but don't set it.
3. Submit the form.

### Additional info

- Craft version: Craft Pro 3.0.0-RC5
- PHP version: 7.2.0
- Database driver & version: MySQL 5.5.28
- Plugins & versions: -

**Comment by andris-sevcenko** [comment]
`EDIT - Just to note that the reason for trying this in the first place is that uploading files with the same name (ie; from an iPhone) doesn't seem to work when it comes to overwriting existing Assets.`

Can you clarify that part and make it another issue?

**Comment by shuckster** [comment]
No problem. :)

**Comment by brandonkelly** [comment]
This also occurs in Craft 2. Ideally if we can come up with a fix, it should be applied in both versions.
