### ISSUE TITLE
Wrong db credentials tries to initiate reinstall

### ISSUE THREAD

**Issue by bliswebagency** [craftcms/cms#2308]
### Description
Using the wrong db credentials and accessing /admin will bring you to the /admin/install page.

### Steps to reproduce

1. Create a valid craft installation
2. Add an extra character to the end of your DB_USER or DB_PASSWORD in .env
3. Access /admin

### Additional info

- Craft version: Craft Client 3.0.0-RC5
- PHP version:  7.0.27
- Database driver & version:  MySQL 5.6.16-1~exp1
- Plugins & versions:

**Comment by brandonkelly** [comment]
This is expected behavior. If Craft can’t connect to the database, it’s reasonable for it to assume that it’s not installed yet.
