### ISSUE TITLE
ElementQuery::addOrderBy results in Exception

### ISSUE THREAD

**Issue by nateiler** [craftcms/cms#2310]
The ElementQuery has an `orderBy` property with the initial value as an empty string (this overrides the default Query which has a null value.

As a result, when calling `ElementQuery::addOrderBy` an exception is thrown because it's looking explicitly for null and assuming an array if not null.

I noticed this when working with an ElementQuery and an ActiveDataProvider.

- Craft version: RC5
- PHP version: 7.1

**Comment by brandonkelly** [comment]
Thanks!
