### ISSUE TITLE
Aliases in site settings

### ISSUE THREAD

**Issue by ray-001** [craftcms/cms#2312]
### Description
Saving site settings with aliases parses the alias as an url.
In my aliases I have an alias called siteBaseUrl:
```
'aliases' => array(
            'siteBaseUrl' => $siteBaseUrl
        ),
```
In my sitesettings I filled in:
Base URL
The base URL for the site. It can begin with an alias, such as ```@web```.
- ```@siteBaseUrl/nl/```
After reopening the site the url is formatted to:
```http://@siteBaseUrl/nl/```

If I try entry->getUrl the output is ```http://@siteBaseUrl/nl/some-slug```

### Steps to reproduce

1. Create alias in general settings
2. Go to sitesettings and fill in the baseUrl field the aliased route

### Additional info

- Craft version: Craft Pro 3.0.0-RC5
- PHP version: 7.1.13
- Database driver & version: MySQL 5.6.38

**Comment by babau67** [comment]
I have the same issue just filling in
`@web`

After reopen site settings, the site Url is re-write as `http://@web`

**Comment by brandonkelly** [comment]
Thanks for reporting that!
