### ISSUE TITLE
Empty bulleted list item left over after running a task

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/cms#2314]
### Description

An empty list item seems to be left over after running a task, just underneath the plugin store link.

![image](https://user-images.githubusercontent.com/24975058/35011600-ac493e52-fafe-11e7-81e1-a1e648adab04.png)

The `<li>` looks to be inside of `<nav id="nav">` but outside of the `<ul>`

```html
<nav id="nav">
  <ul></ul>
  <li></li>
</nav>
```

### Steps to reproduce

1. Have way too much time on your hands
2. Perform an action that leads to a task being run
3. Keep your eye on the area directly beneath the plugin store link.

### Additional info

- Craft version: 3.0.0-RC5
- PHP version: 7.2.1

**Comment by brandonkelly** [comment]
Thanks!
