### ISSUE TITLE
Exception throw when a null value is returned on craft\services\UserGroups::getGroupByHandle

### ISSUE THREAD

**Issue by dsmrt** [craftcms/cms#2317]
### Description
If a group doesn't exist, craft\services\UserGroups::getGroupByHandle will return a null value which will throw the following TypeError:

Return value of craft\services\UserGroups::getGroupByHandle() must be an instance of craft\models\UserGroup, null returned

### Steps to reproduce

1. Call craft\services\UserGroups::getGroupByHandle with a group handle that doesn't exist.

### Additional info

- Craft version: 3.0.0-RC6
- PHP version: 7.2
- Database driver & version: mysql (5.6)

**Comment by brandonkelly** [comment]
Fixed for the next release, thanks!
