### ISSUE TITLE
Display Craft version number alongside edition label (or via tooltip)

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#2318]
<img width="707" alt="fr-craft-version" src="https://user-images.githubusercontent.com/5309692/35074559-4fde4fd6-fba3-11e7-823c-04497e0e0cf7.png">

**Comment by brandonkelly** [comment]
And the reward for laziest feature request goes to…

**Comment by lindseydiloreto** [comment]
![](https://78.media.tumblr.com/207d3e2fcb58b3195894c26f84e43161/tumblr_n7yoo4lZ311tfa8pto1_500.gif)

**Comment by narration-sd** [comment]
well played :)

**Comment by brandonkelly** [comment]
I forgot that the edition badge already has a tooltip if you’re running a trial (“Manage your Craft CMS edition”). But I agree, it’s nice to know the current version at a glance, so just added it underneath the edition badge.

<img width="225" alt="screen shot 2018-01-18 at 10 06 34 am" src="https://user-images.githubusercontent.com/47792/35113720-4d8da7b0-fc37-11e7-8b74-72170d4e92ec.png">

**Comment by lindseydiloreto** [comment]
Beautiful!! Thanks @brandonkelly!

![](https://media.giphy.com/media/qnOBmH70CGSVa/200.gif)

**Comment by narration-sd** [comment]
That's really handsome looking, Brandon.

I'd really preferred that way, but hadn't felt to say; nice to see it ;)
