### ISSUE TITLE
Asset's Title auto generated by upload contains separators instead of spaces

### ISSUE THREAD

**Issue by babau67** [craftcms/cms#2324]
### Description

If I upload a file via an Asset field or via the sidebar Assets, its **Title** is auto generated with separators between each words, eg: 

- file name: my awesome document.pdf _became_

- title: My-Awesome-Document.pdf

I expected, like in Craft 2, to have the auto generate Title with words separate by space.

### Steps to reproduce

1. Go to Assets.
2. Uploads a file with a file name made up more words
3. Look at the Title

### Additional info

- Craft version: Craft 3 RC-6
- PHP version: 7.0.22
- Database driver & version: Mysql 5.7.20
- Plugins & versions: Redactor 1.0.1

**Comment by brandonkelly** [comment]
@andris-sevcenko Was this change intentional? Do you remember why? On the surface Craft 2’s behavior seems better.

**Comment by brandonkelly** [comment]
Fixed now, thanks @babau67!

**Comment by babau67** [comment]
Thanks, perfect! in the new RC7, Asset field will be awesome!

**Comment by phoob** [comment]
Would it be possible to make titleCase optional? In Scandinavian languages, titles only capitalize the first word...

**Comment by brandonkelly** [comment]
@phoob Can you post a new issue for that?
