### ISSUE TITLE
Action buttons jump around on entry view

### ISSUE THREAD

**Issue by jwb009** [craftcms/cms#2325]
### Description
Based on the length of an entries title, the version, live preview, share, and save buttons move around. These buttons should probably be stationary, regardless of title length or browser size.   

### Steps to reproduce

1. Add an entry with a short title or long title
2. Notice the position of the action buttons.

### Additional info

- Craft version: 3.0.0 RC6
- PHP version: 7.1
- Database driver & version:
- Plugins & versions:
- Windows 10/Chrome Latest

Here's an example of a short title:
![short-title](https://user-images.githubusercontent.com/7241260/35165012-48f67228-fd12-11e7-91df-f51827a972bd.PNG)

A really long title (which my clients often have):
![long title](https://user-images.githubusercontent.com/7241260/35165024-55026824-fd12-11e7-937e-23020ec41828.PNG)

A suggestion to fix. The version button seems more appropriate in the sidebar. The other 3 buttons would be confined to a static 350px space alongside the title:
![fix](https://user-images.githubusercontent.com/7241260/35165038-60a06438-fd12-11e7-9657-a2ab50bd6408.PNG)

**Comment by richhayler** [comment]
Like this idea. Would be worth also considering the styling of the version dropdown and entry type dropdown and whether they should match...

**Comment by brandonkelly** [comment]
This has been resolved for the next 3.2 Alpha release!
