### ISSUE TITLE
Allow resolving of aliases in Twig templates

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#2327]
Now that we can define `aliases` in our `general.php` for things like Asset Volume URLs and such, it'd be useful to be able to resolve these aliases in Twig templates.

The use-case is that in my `general.php` I might add an alias like `@baseUrl` so that I can use that in my Volume settings, for instance. But I might also want to use it in templates for things that are _not_ saved in an Assets Volume, but _are_ being served from the same CDN or such that my Assets are

Things like JavaScript, CSS, etc. that are part of the build process, but _are_ served from my CDN, I’d like to be able to do something like:

```
<link rel="stylesheet" href="{{ getAlias('@baseUrl') }}css/site.combined.min.{{staticAssetsVersion}}.css">
```

You could just add the `getAlias()`/`setAlias()` pair, and they'd be simple functions that call down to `Craft::getAlias()` and `Craft::setAlias()` respectively.

I’m sure there are other cases where it’d be useful, too, and being able to use the `@web` and `@webroot` in templates could definitely come in handy as well.

**Comment by bencresty** [comment]
For who, like me, found this page by searching on how including an alias was working again;

The function is called `alias()` nowadays (2021, v3.x):

``` text
<img src="{{ alias('@assetBaseUrl/images/logo.png') }}">
```

https://craftcms.com/docs/3.x/dev/functions.html#alias

**Comment by khalwat** [comment]
@bencresty would recommend using `parseEnv()` which does both: https://nystudio107.com/blog/multi-environment-configuration-for-craft-cms-3#parse-env-does-both
