### ISSUE TITLE
 Craft::$app->getSites()->currentSite returns incorrect site

### ISSUE THREAD

**Issue by mattcdavis1** [craftcms/cms#2333]
### Description
When i query `Craft::$app->getSites()->currentSite` in the context of `saveElement` (i've overriden the Craft Elements Service) it always returns '1' even if i'm on a different site.  `Craft::$app->request->post('siteId')` returns the correct site ID.

### Steps to reproduce

1. query `Craft::$app->getSites()->currentSite` in the context of `saveElement`

### Additional info

- Craft version: Craft Pro 3.0.0-RC6
- PHP version: 7.0.27
- Database driver & version: MySQL 5.5.58
- Plugins & versions:

**Comment by brandonkelly** [comment]
The current site is determined by the `CRAFT_SITE` constant, which should be defined in index.php, not any query/post param.

**Comment by mattcdavis1** [comment]
@brandonkelly - has this been added in the past few days (`CRAFT_SITE` in index.php).  I just created this site recently and it is not in my index.php.  This is what i see when i try and access that constant in the context of `saveElement`: https://goo.gl/KQmKQB

I'm not seeing this constant in the [repo either](https://github.com/craftcms/craft/blob/master/web/index.php)

**Comment by brandonkelly** [comment]
Sorry the general setup process isn’t documented yet (will be soon). It’s the Craft 3 equivalent of Craft 2’s `CRAFT_LOCALE` constant. (See Craft 2’s [Setting up a Localized Site](https://craftcms.com/docs/localization-guide) guide.

It’s something you would need to add yourself, from any index.php files that should not serve the primary site, and tells Craft which site the current request is for. It gets checked from the bootstrap script: https://github.com/craftcms/cms/blob/2b511b3e3540315b3a1a1eab91509dce61e4777a/bootstrap/bootstrap.php#L238-L240

**Comment by mattcdavis1** [comment]
hmm - the localized site guide assumes a different public directory for each site which would be cumbersone for my use-case.  With the addition of the [single-site-entries](https://github.com/craftcms/cms/commit/a3cc52f0f13b3bd7288e599571adf5da0d70cc69) commit i don't really need access to this information currently anyway.  

However, i imagine getting the current site in the admin context could be a fairly common requirement for plugins.  I'm guessing this is maintained via session/cookie currently.  Would be nice to document the proper way to get the current site in the admin context.

**Comment by brandonkelly** [comment]
Well technically you don’t have to create multiple index.php's – it doesn’t matter how you set the `CRAFT_SITE` constant. You could just have a single index.php and set it to different values depending on other factors.

**Comment by mattcdavis1** [comment]
ok got it - thanks!
