### ISSUE TITLE
Eager loading and Live Preview

### ISSUE THREAD

**Issue by H-i-red** [craftcms/cms#2335]
### Description
Live preview does not seem to work when I "Eager load" a matrix field.

```
{% set blocks = entry.grid.with([
    ['image:image', {
        withTransforms: ['background']
    }]
]).all() %}
```

### Additional info

- Craft version: Craft Personal 3.0.0-RC6
- PHP version: 7.1.6
- Database driver & version: MySQL 5.6.35
- Plugins & versions:

**Comment by H-i-red** [comment]
Workaround !

```
{% set preview = craft.app.request.isLivePreview %}

{% if preview %}
    {% set blocks = entry.grid.all() %}
{% else %}
    {% set blocks = entry.grid.with([
        ['image:image', {
            withTransforms: ['background']
        }]
    ]).all() %}
{% endif %}
```

**Comment by benface** [comment]
@brandonkelly This wasn't fixed, was it?

**Comment by brandonkelly** [comment]
It is expected behavior, per the [Eager-Loading docs](https://github.com/craftcms/docs/blob/v3/en/templating/eager-loading-elements.md#accessing-eager-loaded-elements):

> However when the assets _are_ eager-loaded, `entry.assetsField` gets overwritten with an array of the eager-loaded assets. So `one()`, `all()`, and other element query methods are not available. Instead you must stick to the standard array syntaxes.

(Example uses assets, but the behavior applies to all element types.)

**Comment by marionnewlevant** [comment]
I know about the `[0]` vs `.one()` difference, but why does eager loading break live preview?

**Comment by brandonkelly** [comment]
Sorry, was on a different train of thought I guess 🙃

Live Preview will preload each of your field values based on the POST data, but eager-loading will override those values with the eager-loaded values. So as @H-i-red’s workaround demonstrates, if it’s a Live Preview request you should just avoid eager-loading anything.

**Comment by narration-sd** [comment]
Wow. Is there any way to generally disable eager-loading, or should there be??

**Comment by brandonkelly** [comment]
Problem is, if the template is telling Craft to eager-load elements, then the template should also have adjusted following code to treat those field values like arrays (as they will be if they've been eager-loaded. So we can't just disable eager-loading for LP requests, as that will likely cause other errors further down the template.

**Comment by narration-sd** [comment]
Ok, and I had thought of @H-i-red 's solution before seeing it, which will do what you know I'm interested in, and will have to be standard practice anyway.

Thanks, @brandonkelly

**Comment by carlcs** [comment]
There should be a warning in the Eager Loading docs with instruction how to best write the conditional to avoid code duplication.
