### ISSUE TITLE
Entries errors

### ISSUE THREAD

**Issue by vladyslavhontar** [craftcms/cms#2337]
### Description
Hi, i have created single entity and channel entity using the same field. Then i went to the Sections sub menu and got this:
https://ibb.co/dVLQib

First of all I didn't see the single section at all. After creating new item for channel section i couldn't see it too. **For Russian Language**
### Steps to reproduce
1. Create single entity
2. Create channel entity
3. Go to the Entries sub menu

### Additional info

- Craft version: 3.0.0-RC6
- PHP version: 7.0
- Database driver & version: mysql 5.6

**Comment by brandonkelly** [comment]
I’m not able to reproduce this on my end. Can you please send a database backup to support@craftcms.com ?
