### ISSUE TITLE
Make title case optional for auto generated asset titles

### ISSUE THREAD

**Issue by phoob** [craftcms/cms#2339]
### Description
Right now auto-generated asset titles use Title Case. However, in most languages, titles only capitalize the first word. In fact, according to [Wikipedia](https://en.m.wikipedia.org/wiki/Capitalization), Title Casing seems to be somewhat particular to the US. Therefore, could we make it optional to use title case for asset titles? Maybe a setting in generalConfig..?

Ref: #2324

**Comment by babau67** [comment]
This feature could be very useful!
Having to upload a bunch of files and removing manually the capitalisation of each word.
Is there a workaround for that?

**Comment by brandonkelly** [comment]
Decided to just make this the new behavior rather than add a config setting. Added for the next 3.1 beta release.
