### ISSUE TITLE
Manually scrolling while dragging a field in Field Layout Editor

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#2340]
This is possible in Craft 2, but not in 3 unfortunately:

- click on a field element in the Field Layout Editor and hold the mouse button
- scroll up to the tab boxes area (still holding mouse button)
- drag the field to a box and drop it

I’m doing this a lot in Craft 2 when working on a small screen, on a MacBook using multi-touch gestures.

Tested in latest Firefox and Safari

**Comment by brandonkelly** [comment]
It should still work, you just have to (semi-awkwardly) drag to the top of the entire window. Can you verify @carlcs?

**Comment by carlcs** [comment]
Sorry for being unclear, but this is not about the automatic scrolling that get’s triggered when dragging the field to the top, which does in fact still work.

Manually scrolling does not, using mouse wheel or touch gesture.

**Comment by brandonkelly** [comment]
Mouse scrolling is still working on my end. Just make sure the cursor is positioned over the main content area in the CP; to work around some browser wonkiness we had to make that its own scroll container, rather than the whole window.

**Comment by carlcs** [comment]
While still holding the mouse button to drag the field? Didn't work for me but I will try again tomorrow.

**Comment by brandonkelly** [comment]
Yep that’s what I tested.

**Comment by davidhellmann** [comment]
Drag & Scroll also not working here.

**Comment by mattcdavis1** [comment]
this is not working for me either (Craft Pro 3.0.13.2).  This is a new issue for me though - was working as of a couple of weeks ago.

https://goo.gl/hWgKio

**Comment by carlcs** [comment]
@brandonkelly the issue with manually scrolling seems to be something else, it’s still not working here and I have https://github.com/craftcms/cms/commit/e67236f25ce2e3efa2ccdf11591cc25de87d6098 installed.

**Comment by brandonkelly** [comment]
Sorry didn’t mean to close this. I realize it’s a different issue.

**Comment by carlcs** [comment]
Yeah no worries, and you fixed @mattcdavis1 sub-issue! 😉
But it‘s weird that it works on your machine…

**Comment by brandonkelly** [comment]
I just tested this again and finally able to reproduce it. No idea why I couldn’t before 🤷‍♂️

Fixed for the next release!
