### ISSUE TITLE
Color field - Browser crash

### ISSUE THREAD

**Issue by H-i-red** [craftcms/cms#2341]
### Description
The browser crashes when trying to close the color picker "window/modal".

### Steps to reproduce

1. Pick a color.
2. Close the color picker window/modal.
3. Repeat a couple of times, (2 times), the browser crashes..

### Additional info

- Computer / system : Mac, macOS High Sierra v. 10.13.3
- Browsers: Firefox 57.0.4 (64-bit), Chrome (latest)
- Craft version: Craft Personal 3.0.0-RC7
- PHP version: 7.1.6
- Database driver & version: MySQL 5.6.35
- Plugins & versions:

**Comment by H-i-red** [comment]
Well it seems that it is a macOS browser related problem..anyone else with this problem ?

**Comment by Wiejeben** [comment]
Does your browser also crash when using the example colorpicker on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color?

**Comment by H-i-red** [comment]
Yes, it crashes. It´s MacOS / Browser related. According to craft slack I´m not alone.

**Comment by brandonkelly** [comment]
If you’re also seeing it on MDN’s `<input type="color">` example, then I think it’s safe to say this is a browser bug, not something we can fix.
