### ISSUE TITLE
Asset upload to unchecked source but default upload location

### ISSUE THREAD

**Issue by mrnebbi** [craftcms/cms#2343]
### Description

We have spotted an issue where uploading a new image to an asset field with drag and drop, causes the image to be placed in the Default Upload Location folder even if that folder has been unchecked from the Sources options.

Would expect that if a user can't select from a specific folder, or see it in the asset modal, then they shouldn't be able to upload to it with drag and drop.

### Steps to reproduce

1. Select an asset field with a source unchecked, but default upload location set to an unchecked source
2. Drag and drop a file to that asset field to cause it to upload

### Additional info

- Craft version: 2.6.3005
- PHP version: 7.0.27
- Database driver & version: 
- Plugins & versions:

**Comment by brandonkelly** [comment]
I don’t think I agree. The main point of the Default Upload Location setting is for drag-and-drop uploads. If you’ve told the field to upload to X, then it would seem like a bug if it didn’t.

**Comment by mrnebbi** [comment]
Fair enough, clearly a developer fail. Just a frustrating one to catch, user was pretty confused.

👍

**Comment by jacksco** [comment]
I agree with Brandon here Mr Nibs. If you don't set the folder source for the input fields then it SHOULD default to the main source set in your general file. It's just idiotic if you presume otherwise... duh.

**Comment by narration-sd** [comment]
I think you've read wrong, @jacksco .

Snark level down, for this community definitely.
