### ISSUE TITLE
Unable to create Single on more than one site

### ISSUE THREAD

**Issue by mattcdavis1** [craftcms/cms#2345]
### Description
See comment [here](https://github.com/craftcms/cms/commit/a3cc52f0f13b3bd7288e599571adf5da0d70cc69#r27055680).  Currently, a given single (i.e. "Home", "About" can only be created on one site and it seems to be random which site that single shows up on.

### Steps to reproduce

1. Attempt to create the same single (i.e. "Home") in a multisite install on more than one site

### Additional info

- Craft version: 3.0.0-RC7
- PHP version: PHP7

**Comment by brandonkelly** [comment]
Yikes, thanks for pointing that out. This ended up being a relatively major bug, and we’ll get an update out with the fix shortly.
