### ISSUE TITLE
Debug toolbar icon shows Yii logo

### ISSUE THREAD

**Issue by putyourlightson** [craftcms/cms#2348]
### Description

I'm assuming that the Craft logo was not intentionally replaced by the Yii logo in the debug toolbar. At least that's what I'm seeing in Craft 3.0.0-RC7.1.
![screen shot 2018-01-25 at 09 16 23](https://user-images.githubusercontent.com/2318222/35377686-7456d712-01b0-11e8-8bc4-7f5b851e144a.png)

**Comment by brandonkelly** [comment]
Thanks!
