### ISSUE TITLE
Saving Sections Single renames single entry title

### ISSUE THREAD

**Issue by babau67** [craftcms/cms#2349]
### Description
When I save a Single Section (from settings) automatically the title of the single entry is renamed with the Section Name.

### Steps to reproduce

1.Create a new Section with Type Single, naming "Test" and Save.
2.Open the relative Entry Type and flag "show the title field" and add some fields.
3: Go to Entries  / Singles and open the Entry "Test"
4. Change the Title and Save (eg from Test to New Test)
5. Go to Settings / Sections open the Single Section "Test" and Save.
6. Go to Entries  / Singles I expected to find my Entry "New Test", instead I see the entry with the Section name.

### Additional info

- Craft version: 3.0.0-RC7.1
- PHP version: 7.0.22
- Database driver & version: 5.7.21
- Plugins & versions: Redactor 1.0.1 / Inventory 2.0.0 / CP field Inspect 1.0.2 / Control Panel CSS 2.1.0

**Comment by brandonkelly** [comment]
Thanks!
