### ISSUE TITLE
Grouping error on column "structureelements.lft" when using Postgres

### ISSUE THREAD

**Issue by Tam** [craftcms/cms#2352]
### Description
I'm not sure whether this is a SimpleMap issue or a Craft one. [A bug](https://github.com/ethercreative/simplemap/issues/70) was found when paginating entries while querying SimpleMap. With the help of @brandonkelly we managed to find [a fix](https://github.com/ethercreative/simplemap/issues/70#issuecomment-356575448), but it only works for MySQL. This error is thrown when using Postgres: 

```
SQLSTATE[42803]: Grouping error: 7 ERROR: column "structureelements.lft" must appear in the GROUP BY clause or be used in an aggregate function
LINE 17: ORDER BY "structureelements"."lft", "elements"."dateCreated"...
^
The SQL being executed was: SELECT COUNT(*)
FROM (SELECT "elements"."id" AS "elementsId", "elements_sites"."id" AS "elementsSitesId", "content"."id" AS "contentId"
FROM "elements" "elements"
INNER JOIN "entries" "entries" ON "entries"."id" = "elements"."id"
INNER JOIN "elements_sites" "elements_sites" ON "elements_sites"."elementId" = "elements"."id"
INNER JOIN "content" "content" ON "content"."elementId" = "elements"."id"
JOIN "simplemaps" "simplemap" ON ("elements"."id" = "simplemap"."ownerId") AND ("elements_sites"."siteId" = "simplemap"."ownerSiteId")
LEFT JOIN "structureelements" "structureelements" ON "structureelements"."elementId" = "elements"."id"
WHERE (("entries"."sectionId" = '2')) AND ("elements_sites"."siteId"=1) AND ("content"."siteId"=1) AND (("content"."field_number" > '1')) AND ((("simplemap"."lat" >= 51.270363 - (50 / 111.045)) AND ("simplemap"."lat" <= 51.270363 + (50 / 111.045))) AND (("simplemap"."lng" >= 0.522699 - (50 / (111.045 * COS(RADIANS(51.270363))))) AND ("simplemap"."lng" <= 0.522699 + (50 / (111.045 * COS(RADIANS(51.270363))))))) AND ((111.045* DEGREES(ACOS(COS(RADIANS(51.270363))* COS(RADIANS("simplemap"."lat"))* COS(RADIANS(0.522699) - RADIANS("simplemap"."lng"))+ SIN(RADIANS(51.270363))* SIN(RADIANS("simplemap"."lat"))))) <= 50) AND ("elements"."archived"=FALSE) AND (((("elements"."enabled"=TRUE) AND ("elements_sites"."enabled"=TRUE)) AND ("entries"."postDate" <= '2018-01-25 11:30:23') AND (("entries"."expiryDate" IS NULL) OR ("entries"."expiryDate" > '2018-01-25 11:30:23')))) AND ("elements_sites"."enabled"=TRUE)
ORDER BY "structureelements"."lft", "elements"."dateCreated" DESC) "subquery"
INNER JOIN "entries" "entries" ON "entries"."id" = "subquery"."elementsId"
INNER JOIN "elements" "elements" ON "elements"."id" = "subquery"."elementsId"
INNER JOIN "elements_sites" "elements_sites" ON "elements_sites"."id" = "subquery"."elementsSitesId"
INNER JOIN "content" "content" ON "content"."id" = "subquery"."contentId"
JOIN "simplemaps" "simplemap" ON ("elements"."id" = "simplemap"."ownerId") AND ("elements_sites"."siteId" = "simplemap"."ownerSiteId")
LEFT JOIN "structureelements" "structureelements" ON "structureelements"."elementId" = "subquery"."elementsId"
ORDER BY "structureelements"."lft", "elements"."dateCreated" DESC
```

The reason I think this *might* be a Craft issue is because by the time the map fields `modifyElementsQuery` is run the `$query->orderBy` is empty, when it should have the user specified orderBy. This means SimpleMap can't do what it needs to with the `distance` orderBy.

### Steps to reproduce

1. Setup Craft w/ latest [dev version](https://github.com/ethercreative/simplemap/tree/v3-dev) of SimpleMap using Postgres
2. Add a map field to a channel
3. Paginate with a SimpleMap query and order by distance:
```twig
{% paginate craft.entries.section('mapTest').testMap({
	location: 'Maidstone, UK' 
}).orderBy('distance').limit(1) as pageInfo, entries %}
```

### Additional info

- Craft version: 3.0.0-RC7
- PHP version: 7.1.8
- Database driver & version: PostgreSQL 10.1
- Plugins & versions: ether/simplemap dev-v3-dev

**Comment by brandonkelly** [comment]
> The reason I think this _might_ be a Craft issue is because by the time the map fields `modifyElementsQuery` is run the `$query->orderBy` is empty, when it should have the user specified orderBy.

What do you mean by “user specified orderBy”? If the user explicitly set the `orderBy` param, then `$query->orderBy` will definitely be set by the time `modifyElementsQuery()` is called.

**Comment by brandonkelly** [comment]
…or do you mean `$query->query->orderBy` (the actual built query as opposed to the element query)?

**Comment by Tam** [comment]
Ah, solved it.

This:
https://github.com/ethercreative/simplemap/blob/v3-dev/src/services/MapService.php?ts=4#L279-L282
and
https://github.com/ethercreative/simplemap/blob/v3-dev/src/services/MapService.php?ts=4#L290-L291
were the issue. `$query->orderBy` is null the first time `modifyElementsQuery` is run, and populated the second. I was setting it to an empty array if it was null and not setting it back to null when I was done. Apparently MySQL didn't mind this, but Postgres did!

I still have no idea exactly why it threw the grouping error, but hey, it works now!
