### ISSUE TITLE
Add permission for adding Dashboard widgets

### ISSUE THREAD

**Issue by steveooo9** [craftcms/cms#2357]
### Description
Currently you aren't able to restrict adding and selecting Dashboard widgets for a user role. It would be great if you can disable the use of Dashboard widgets because sometimes the default widgets or widgets by 3rd-party plugins disclose some data nobody in this role should see.

**Comment by noregt** [comment]
A bit similar would be to be able to set the default widgets for a user group. Right now everybody gets the craft news widget and recent posts. For the really basic users I prefer no widgets at all.

**Comment by brandonkelly** [comment]
@noregt Can you please post that as a new FR?
