### ISSUE TITLE
Field Layout Editor to show field handles and normal case the tab names

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#2360]
<img width="251" alt="bildschirmfoto 2018-01-26 um 09 51 23" src="https://user-images.githubusercontent.com/7516543/35444317-770ed6fe-02ae-11e8-809c-98384f945a4e.png">

It would be very helpful if the Field Layout Editor would show field handles instead of field names. I know it won’t look as pretty with that change, but I think it’d be much more useful (see problem in the screenshot above).

Another but rather minor annoyance is that you can’t tell if the casing of the Tabs is entered correctly. I would much prefer they would not be uppercased, so I don’t have to check the edit entries pages if I got it right.

**Comment by brandonkelly** [comment]
I’ve actually been thinking I should probably remove the `text-transform: uppercase`, so thanks for the nudge. Not going to show the handles in place of the field names, but I’ve given the field names some tooltips that reveal the handles. (Fixed for Craft 2 - will merge to Craft 3 for RC8.)
