### ISSUE TITLE
Json Decode Exception when Changeing a TextField to a TableField

### ISSUE THREAD

**Issue by boscho87** [craftcms/cms#2365]
### Description
I Changed a Field Type from test to Json (in the Admin Panel), then there was a json decode problem, because the  fields data were not deleted by chaning the field type, and i was not able to edit the entry, until i deleted the field value from the database.

### Steps to reproduce

1. Create a text field, and add it to a section
2. Write some text in the filed (no json)
3. change the field to table type
4. try to edit the page again --> exception

### Additional info

- Craft version: 3.0.0-RC1
- PHP version: 7.1
- Database driver & version: mysql 5.7
- Plugins & versions: --

**Comment by brandonkelly** [comment]
Fixed, thanks!
