### ISSUE TITLE
Bad contrast for version/edition

### ISSUE THREAD

**Issue by MDXDave** [craftcms/cms#2368]
### Description
The contrast for the edition/version is very bad. It shoud be a light grey or something like this.
![image](https://user-images.githubusercontent.com/6099976/35477799-35fac578-03cc-11e8-9c25-5396cf0b8248.png)

### Additional info

- Craft version: 3.0.0-RC7.1
- PHP version: 7.1

**Comment by brandonkelly** [comment]
The low contrast is intended.
