### ISSUE TITLE
Tags displaying entity name rather than the character itself

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/cms#2369]
### Description

When creating tags with characters such as the ampersand, the entity name is displayed rather than the character itself. This is the same when outputting the tag in the templates.

<img width="188" alt="image" src="https://user-images.githubusercontent.com/24975058/35503720-d80df79c-04d8-11e8-82d9-96378fd75009.png">

I'm not 100% sure if this is expected behaviour?

### Steps to reproduce

1. Create tag field
2. Add tag that includes an ampersand
3. Entity name is displayed rather than the character

### Additional info

- Craft version: 3.0.0-RC7.1
- PHP version: 7.2.1
- Database driver & version: MySQL

**Comment by brandonkelly** [comment]
Thanks!
