### ISSUE TITLE
[Feature Request] Add per assignment field settings

### ISSUE THREAD

**Issue by mattcdavis1** [craftcms/cms#2370]
### Description
It would be nice to update the instructions / label at an assignment level rather than the field level (field level would still be used as the default).  [Here's an example](https://goo.gl/8WvsGs) of what this functionality looks like in PyroCMS.

A sample use case would be an image with a field name of "Image" that is a "Profile Image" in one context and a "Product Image" in another context.  Also, even with fields having the same label, instructions might differ per assignment (i.e. please upload image with the following dimensions...).

**Comment by brandonkelly** [comment]
This FR is already covered by #806, #841, and #1524.

**Comment by mattcdavis1** [comment]
ahh - ok i searched for "assignment" thanks!
