### ISSUE TITLE
[Bug] Global Text Field overwriting value for all sites

### ISSUE THREAD

**Issue by mattcdavis1** [craftcms/cms#2371]
### Description
When i save a Globals text field value for one site, it updates that same field for all sites. 

### Steps to reproduce

1. Create a global with a text field
2. Save a value to that field
3. Change the value of that field on another site

Expected: Field value on original site remains the same
Actual: Changing the field value on site B updates the field value for site A

[Screenshot](https://goo.gl/tTdbL7)

### Additional info

- Craft version: Craft Pro 3.0.0-RC7.1
- PHP version: 7.0.27
- Database driver & version: MySQL 5.5.58

**Comment by mattcdavis1** [comment]
Hmm - ok.  One of my co-workers pointed out that the "Translatable" setting controls this so changing this request to "Please update terminology for "Translation Method".  When i choose a certain value on site "A" and another value on site "B" i am not translating that value.  It is english in both cases.  

I think the default setting for multisite should be that field values are not shared (what is the point of multisite otherwise) and that the terminology should be changed to use "Site" in place of "Language" (i.e. "Site Settings" instead of "Translation Method" or something like that)

**Comment by brandonkelly** [comment]
“Translation” doesn’t have to mean “language translations”. Even if it goes from English → English, Craft considers the process of storing different values for different sites “translations”.

**Comment by mattcdavis1** [comment]
Ok - but from a user experience perspective the naming is not ideal, regardless of how the mechanics of this may work behind the scenes.

**Comment by brandonkelly** [comment]
The wording generally works, which is good enough - there are plenty of other cases where the Craft name for something might not be a perfect match to what it is used for (“Section”, “Entry”, and many more terms, are never always going to be exactly semantic in every use case. Naming is hard.)
