### ISSUE TITLE
[Feature Request] Set min and max rows for a table field

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#2372]
### Description

Synonymous to the new matrix field min and max options in CraftCMS 3 RC7.1, and for much the same reasons, it would be great to have similar options for setting the min and max number of rows for a table field.

If the min and max number are the same then do not display the “add a row” button.

Additionally if one could be able to change the default “add a row” button label to be a custom one that may be more contextual to the content this would also be a big  plus.

**Comment by davidhellmann** [comment]
Good point. And also when min == max it's directly visible.

**Comment by brandonkelly** [comment]
We just added these settings to Table fields in 3.0.0-RC17.

**Comment by richhayler** [comment]
Awesome!! Thanks guys :)
