### ISSUE TITLE
Nav badges hidden when selected

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/cms#2374]
### Description

<img width="224" alt="image" src="https://user-images.githubusercontent.com/24975058/35569742-e1a3ce02-05c4-11e8-82b5-8c75679b031b.png">

<img width="225" alt="image" src="https://user-images.githubusercontent.com/24975058/35569753-ea78d770-05c4-11e8-8443-802a2726e8aa.png">

### Additional info

- Craft version: 3.0.0-RC7.1
- PHP version: 7.2.1

**Comment by brandonkelly** [comment]
That is intentional; no need to show the badge if you’re already looking at the page with all the errors on it.

**Comment by lukeyouell** [comment]
@brandonkelly Ah, I see.

I was working through deprecation errors while upgrading from Craft 2, I had to go to a different page to see the number of deprecation errors left as there is no error count on the page. I think it would be handy to be able to see the error count somewhere!
