### ISSUE TITLE
'Nothing to update' when there is

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/cms#2378]
### Description

Despite there being plugin updates available, when I clicked 'Update' I was immediately told there was nothing to update.

The value in my composer.json file was `"ether/simplemap": "^3.1"`

![ezgif-5-5e7d8afa8d](https://user-images.githubusercontent.com/24975058/35615656-b9fd3af4-066a-11e8-8215-5471b1dc6df0.gif)

### Additional info

- Craft version: 3.0.0-RC8
- PHP version: 7.2.1
- Database driver & version: MySQL

**Comment by davidhellmann** [comment]
`allowUpdates: false;` maybe? But when it is the button should be not visible.

**Comment by lukeyouell** [comment]
@davidhellmann there's nothing in the config interfering with updates

**Comment by brandonkelly** [comment]
Definitely a bug on our end. On it…

**Comment by lukeyouell** [comment]
Cheers! @brandonkelly
