### ISSUE TITLE
Entry page height issue

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/cms#2379]
### Description

Since updating to `.3006` it looks like the entries page sets the height of the container to the height of the table, which leads to a small container.

![ezgif-5-40919da97e](https://user-images.githubusercontent.com/24975058/35616520-63e56332-066d-11e8-8121-96089392e83f.gif)

Tested in Chrome & Firefox.

### Additional info

- Craft version: 2.6.3006

**Comment by mattcheww** [comment]
I'm experiencing the same issue since upgrading to `.3006`. I see the issue in nearly every area where the sidebar exists.

**Comment by oblongd** [comment]
Same here. Prior to .3006, there were styles dynamically applied to the **#content** and **#sidebar** elements which set height and positioning, so this seems to be a scripting issue.

**Comment by elfacht** [comment]
Same here since `.3006` in Global Content, but only in particular sections.

**Comment by bertoost** [comment]
Same here since .3006
Only in sections which are empty. Also in users section if they are empty etc.
Can it be something regarding the jQuery update?

**Comment by stefanfriedrich** [comment]
Same here since .3006 in different sections.

**Comment by bertoost** [comment]
Downgrading to .3005 is easy. Just [download it here](https://download.craftcms.com/craft/2.6/2.6.3005/Craft-2.6.3005.zip) and replace the `craft/app/` folder (remove or rename + add old-version folder)

**Comment by lukeyouell** [comment]
This update has been applied to one of our larger sites, so I'm reluctant to roll back to a previous verson.

`Craft does not support rolling back to previous versions`

**Comment by carlcs** [comment]
@lukeyouell this is only the case when an update included migrations. And there's none in this update. So it's save to replace the app/ folder.

**Comment by brandonkelly** [comment]
Thanks everyone. Fixed now, and we’ll get a release out ASAP.

**Comment by brandonkelly** [comment]
2.6.3007 is out now with the fix.
