### ISSUE TITLE
Sorting Entries via entry date field not working

### ISSUE THREAD

**Issue by nmann4789** [craftcms/cms#2383]
### Description

I have a date field called Start Date (`startDate`) in my events channel and am trying to access entries for this channel based on that date. For example: 

```twig
{% set events = craft.entries({
        section: 'events',
        startDate: '>= '~ now|date
    })
    .order('startDate desc') %}
```

All of the entries seem to be appearing and sorting based on Entry Expiry Date.

Please advise

### Additional info

- Craft version:Craft Pro 3.0.0-RC5
- PHP version: 7.1.8
- Database driver & version: MySQL 5.6.35
- Plugins & versions:

**Comment by brandonkelly** [comment]
As you are on Craft 3, can you try using the `orderBy` param rather than `order`? You also may wish to update the `section` and `startDate` params so they are all set consistently. And don’t forget to use `.all()`!

```
{% set events = craft.entries()
    .section('events')
    .startDate('>= '~ now|date)
    .orderBy('startDate desc')
    .all() %}
```

**Comment by nmann4789** [comment]
Thanks for the update.

I have applied what you suggested and am still seeing entries returned
before 'now'.

The query looks like this:

{% set events = craft.entries.section('events').startDate('>='~
now|date).orderBy('startDate asc').all() %}

You can see the Start Date in the entry is set as follows:

[image: Inline image 1]

On the front end it is returned as the first entry:

[image: Inline image 2]

I'm not sure what I'm missing here :/

**Comment by brandonkelly** [comment]
@nmann4789 your images didn't post successfully. Can you repost from github.com?

**Comment by nmann4789** [comment]
![image](https://user-images.githubusercontent.com/4096608/35820595-0d496b44-0a74-11e8-84bd-15266a88abfd.png)

![image](https://user-images.githubusercontent.com/4096608/35820610-176245a6-0a74-11e8-8997-53506e8f88fa.png)

**Comment by nmann4789** [comment]
@brandonkelly Not sure if you saw, but I have re-uploaded the images for you. Thanks for your help on this one

**Comment by brandonkelly** [comment]
The issue is that the default output for the `|date` filter is a human-readable string, e.g. `Feb 4, 2018`, which MySQL doesn’t know what to do with.

You could either pass a format into the filter (e.g. `date|('Y-m-d')`, or go with the `|atom` filter, which is a shortcut for `date|('Y-m-d\\TH:i:sP')`.
