### ISSUE TITLE
Broken styles in admin after .3006 upgrade.

### ISSUE THREAD

**Issue by gjhead** [craftcms/cms#2384]
Not sure if this is related to #2379 at all but since upgrading to .3006 I'm seeing some broken styles in my admin.  Specifically in my Entries lists.  This does NOT happen in all of them but just the first two in my list (See Image: Site Navigation and Restaurant Locations)

![cap](https://user-images.githubusercontent.com/192508/35657023-504b4700-06c8-11e8-8bff-b8b8b3a6f5fe.png)

**Comment by brandonkelly** [comment]
Does updating to 2.6.2007 fix it for you?

**Comment by gjhead** [comment]
@brandonkelly it did!  Thanks for the quick fix on this!

**Comment by brandonkelly** [comment]
Great thanks!
