### ISSUE TITLE
Error when saving enabled sections in multi site

### ISSUE THREAD

**Issue by Rias500** [craftcms/cms#2385]
### Description
When trying to save enabled sites for a section, I get the following error:

![afbeelding](https://user-images.githubusercontent.com/3626559/35674720-e79849aa-0745-11e8-9c69-3714b226f81f.png)

I've tracked this down and this is because the `$presistentSiteIds` array looks like this for me:

```
[
    8 => 1
]
```

So there is no key `[0]`, this can be fixed by using `'siteId' => reset($persistentSiteIds),`

### Steps to reproduce

1. Have an enabled site id for a section that is not the first.
2. Try to enable other sites

### Additional info

- Craft version: 3-RC8
- PHP version: 7.1

**Comment by brandonkelly** [comment]
Fixed for RC9, thanks! You can get the fix before RC9 by changing your `craftcms/cms` version constraint in composer.json to `"dev-develop as 3.0.0-RC99"` and then run `composer update`.
