### ISSUE TITLE
Provide method for plugins to override field rendering

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#2387]
Of course we can always create a new field type that actually `extends` the `craft\fields` field in question (e.g. https://github.com/timkelty/craft-simplecategories), however, this isn't always ideal.

If a hook/event existed for the field rendering (FieldHtml), I instead create a plugin that specified certain fields to use this custom type of rendering.

**Comment by timkelty** [comment]
FWIW I did try a hacky monkey patch solution (@khalwat made me 🐲 ), which didn't work:

```
        Event::on(ElementQuery::class, ElementQuery::EVENT_AFTER_POPULATE_ELEMENT, function(PopulateElementEvent $event) {
          $event->element->fieldLayout->fields = array_map(function($field) {
            $field->attachBehavior('myFieldBehavior', FieldBehavior::class);

            return $field;
          }, $element->fieldLayout->fields);
        });
```

I _believe_ that would be because the template rendering those fields doesn't actually use the instances from `event->element->fieldLayout->fields` and instead uses `entryType.getFieldLayout().getTabs()[].getFields()`.

**Comment by timkelty** [comment]
@brandonkelly I'd love to start a PR for this but would like some quick input as to you approaches you might prefer to merge.

The end goal is to be able to override the `getInputHtml` of a given field.

In this example, this would allow me to have a plugin whose settings selected relation fields that you wanted to display differently (as checkboxes), rather than having to introduce a new fieldtype.

My specific examples all deal with relation fields, so another option would be just to make `BaseRelationField::inputTemplate` public, so that I could just override the template for a field instance.

**Comment by brandonkelly** [comment]
I’m already planning on giving relation fields multiple UI modes in Craft 4 (see #2632, #4137), and I think including “Checkbox list” as one of the options would make sense. If that’s all you need, then I can probably safely close this?

**Comment by timkelty** [comment]
@brandonkelly Sounds good to me, go ahead and close.

However you implement, it would be nice to allows devs to hook into it the rendering of any field in the same way.
