### ISSUE TITLE
Error when trying to save a new entry with a Matrix field

### ISSUE THREAD

**Issue by howells** [craftcms/cms#2389]
### Description

An error is returned when trying to create a new entry that features a Matrix field.

````Argument 1 passed to craft\services\Matrix::_applyFieldTranslationSetting() must be of the type integer, string given, called in ......./vendor/craftcms/cms/src/services/Matrix.php on line 665````

````in ......../vendor/craftcms/cms/src/services/Matrix.php at line 665 – craft\services\Matrix::_applyFieldTranslationSetting('id-nu8MpKlWPM', 1, craft\fields\Matrix)````

This error only started to appear after I created a new entry type for the given section. I then removed the new type, but the error stays.

If I remove `int` from line 845, it seems to work:
`
````private function _applyFieldTranslationSetting($ownerId, int $ownerSiteId, MatrixField $field)````

### Steps to reproduce

1. Create a new entry with a Matrix field type.

### Additional info

- Craft version:  Craft CMS 3.0.0-RC8
- PHP version:  7
- Database driver & version:  
- Plugins & versions:

**Comment by brandonkelly** [comment]
Not able to reproduce this. Can you please send a database backup to support@craftcms.com?

**Comment by howells** [comment]
@brandonkelly just emailed you a dump of the db. Many thanks.

**Comment by brandonkelly** [comment]
Able to reproduce with your DB, thanks!
