### ISSUE TITLE
Deleted users entry revisions not being deleted

### ISSUE THREAD

**Issue by alexmarchant** [craftcms/cms#2390]
### Description

`Argument 1 passed to craft\services\Users::getUserById() must be of the type integer, null given, called in /Users/alex/Developer/craft/mastinlabs.com-craft/site/vendor/craftcms/cms/src/models/BaseEntryRevisionModel.php on line 78`

### Steps to reproduce

1. Create an test user
2. Login as that user
3. Edit an entry and save a revision
4. Log out and into an admin user
5. Delete test user and chose to erase/delete their content
6. Load entry that was edited by test user
7. See error:

`Argument 1 passed to craft\services\Users::getUserById() must be of the type integer, null given, called in /Users/alex/Developer/craft/mastinlabs.com-craft/site/vendor/craftcms/cms/src/models/BaseEntryRevisionModel.php on line 78`

If you look at the `entryversions` table you'll notice the last revision has `NULL` as the `creatorId` which is causing the exception.

### Additional info

- Craft version: 3 RC8
- PHP version: 7.2.1
- Database driver & version: PostgreSQL 10.1
- Plugins & versions:

- ElementAPI 2.5.2
- Redactor 1.0.1
- AmazonS3 1.0.8

**Comment by brandonkelly** [comment]
Thanks!
