### ISSUE TITLE
Enabling "manage blocks on a per-site basis" for Matrix fields results in SQL Error - Integrity constraint violation

### ISSUE THREAD

**Issue by vikdialpad** [craftcms/cms#2391]
### Description
Seeing an error with Matrix fields in a Multisite environment. We have been using matrix fields throughout the site and we now need to enable the option 'Manage blocks on a per-site basis', as we would like to configure things differently for different sites. 

If we select this option when creating a brand newly created matrix field group there are no issues, however for an existing matrix field group, that has been used to create content, selecting this option results in the following errors (after enabling the option, and then updating content within the corresponding matrix field group and saving): 

```
Integrity constraint violation – yii\db\IntegrityException
SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "dp_relations_fieldId_sourceId_sourceSiteId_targetId_unq_idx"
DETAIL: Key ("fieldId", "sourceId", "sourceSiteId", "targetId")=(167, 2255, 3, 233) already exists.
The SQL being executed was: INSERT INTO "dp_relations" ("fieldId", "sourceId", "sourceSiteId", "targetId", "sortOrder", "dateCreated", "dateUpdated", "uid") VALUES (167, 2255, 3, 233, 1, '2018-02-01 21:01:51', '2018-02-01 21:01:51', 'ff25bd29-73d5-4d15-8ab1-e545c7f7c9c6'), (167, 2256, 3, 233, 1, '2018-02-01 21:01:51', '2018-02-01 21:01:51', '19be435f-e25a-420c-b461-e7a7c9a39d74'), ............

Error Info: Array
(
[0] => 23505
[1] => 7
[2] => ERROR: duplicate key value violates unique constraint "dp_relations_fieldId_sourceId_sourceSiteId_targetId_unq_idx"
DETAIL: Key ("fieldId", "sourceId", "sourceSiteId", "targetId")=(167, 2255, 3, 233) already exists.
)
↵
Caused by: PDOException
SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "dp_relations_fieldId_sourceId_sourceSiteId_targetId_unq_idx"
DETAIL: Key ("fieldId", "sourceId", "sourceSiteId", "targetId")=(167, 2255, 3, 233) already exists.
in /usr/share/nginx/vendor/yiisoft/yii2/db/Command.php at line 994
```

### Steps to reproduce

1. Create a Matrix field group with multiple blocks (doesn't matter the type of fields within the blocks, can just be text fields)
2. Use the Matrix field group to create and populate content
3. Go back and enable the option 'Manage blocks on a per-site basis'
4. Now return to your content that uses the Matrix field group, try and update and save. Stated error occurs.

### Additional info

- Craft version: Craft Pro 3.0.0-RC8
- PHP version: 7.0.25
- Database driver & version: PostgreSQL 10.1
- Plugins & versions:
Amazon SES	1.0.0
Redactor	1.0.1
Google Cloud Storage	1.0.5
Redirect plugin for Craft 3	1.0.14
Inlin	2.0.0
Cookies	1.1.8

**Comment by brandonkelly** [comment]
I’m not able to reproduce this, so there must be more to it. Can you send a DB backup to support@craftcms.com?

**Comment by brandonkelly** [comment]
Able to reproduce, and looks like it only occurs if the Matrix field has sub-relational fields that manage relations on a per-site basis.
