### ISSUE TITLE
Expanding the relatedTo parameter

### ISSUE THREAD

**Issue by nateclonch** [craftcms/cms#2392]
### Description

As a feature request, it would be nice to be able to access the elements' properties from the `relatedTo` parameter, rather than only their fields.

### Steps to reproduce

1. NA

### Additional info

- Craft version: 2.6.3004
- PHP version: 7.0.26
- Database driver & version: MySQL 5.0.12
- Plugins & versions: NA

**Comment by brandonkelly** [comment]
Can you elaborate? Elements queried via `relatedTo` have all the standard properties.

**Comment by nateclonch** [comment]
Yes, sorry. I did not find documentation on using `relatedTo` in conjunction with `author`. I may have used the incorrect slug, but I was not able to produce a successful result. This was a few days ago, but I believe I tried using both `author` and `authorId` with the user element and user ID respectively.

**Comment by brandonkelly** [comment]
Should definitely work. If you are still having trouble, feel free to update the issue with the exact code you’re using, and we’ll review.

**Comment by nateclonch** [comment]
If it should work, would you mind telling me exactly what the `field` value should be, if I'm trying to get the author of an entry element, and if I'm providing the user element as the `targetElement`?

Sorry. There's just no documentation, and searching the craft/app folder wouldn't help me much either.

**Comment by brandonkelly** [comment]
Entry-author relationships are not actually stored the same way that custom field-based relationships are, so the `relatedTo` param doesn’t apply to them in the first place. To get the author of an entry, just access `entry.author`. For example,

```twig
<p>Author: {{ entry.author.name }}</p>
```

Relevant docs:
- `EntryModel::author`: https://craftcms.com/docs/templating/entrymodel#author
- `UserMoel` (what `.author` gives you): https://craftcms.com/docs/templating/usermodel

Additionally if you do end up needing the `relatedTo` param for normal relationship fields, you can find it documented here: https://craftcms.com/docs/relations

**Comment by nateclonch** [comment]
I appreciate your time and help, but nothing of your previous response is news to me. I'm not trying to get the author of an entry. I'm trying to pull entries that have only been created by a specific user. My workaround was just to create a User field that also saves the author - so I'm basically having the author saved twice.

With that said, I understand that entry-author relationships aren't stored the same way. I found that out when I couldn't use `relatedTo` with `author`. This is why I mentioned this as a feature-request in my initial post. I'm assuming there would need to be significant adjustments to the `relatedTo` parameter.

Although I would find it extremely valuable, I have no clue how valuable this would be to the Craft community. So thanks again for entertaining this.

**Comment by brandonkelly** [comment]
Sorry, misunderstood.

To get all the entries by a particular user, use the [authorId](https://craftcms.com/docs/templating/craft.entries#authorId) entry criteria param.

For example, this will give you all of the entries that belong to the currently logged-in user (if there is one):

```twig
{% if currentUser %}
    {% set entries = craft.entries.authorId(currentUser.id) %}
{% endif %}
