### ISSUE TITLE
Field instructions are placeholders now

### ISSUE THREAD

**Issue by bertoost** [craftcms/cms#2396]
### Description

I saw that field instructions are set as placeholder instead of appearing below the field (or title). This is kind of confusing when the field is filled and you want to explain what the value is used for.
I did not notice when this is changed, but it was appearing above (or below) fields before.

I think that approach was better than setting placeholders.

![image](https://user-images.githubusercontent.com/398492/35766482-ea696084-08d9-11e8-9b32-998fcc0fac98.png)

### Additional info

- Craft version: 2.6.3007
- PHP version: 7.1

**Comment by brandonkelly** [comment]
That definitely shouldn’t be happening, and I can’t reproduce on my end. Are you sure you didn’t type your instruction text into the “Placeholder” setting by accident?

**Comment by bertoost** [comment]
OMG! this is so painful.. I checked it three times and three times I thought it was okay.. I even started investigation in core files.. Never mind

**Comment by brandonkelly** [comment]
haha, no worries :)
