### ISSUE TITLE
Craft should try to determine the Current Site automatically

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/cms#2397]
On requests where the `CRAFT_SITE` constant isn't defined, Craft should check the hostname and URI, and compare them to the Base URLs for its sites, and set the `currentSite` to the best match (if it can find one); only falling back to the Primary Site if it’s not sure what to do.

**Comment by bertoost** [comment]
Cool! This would be good to have since I think that's the most common usage.

For time being I am using a ContextRouter which also works great with environment configs
https://gist.github.com/bertoost/8093f89c080021fed95f54001512ce80
