### ISSUE TITLE
Matrix Field: Moving Delete Block also to top

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#2400]
### Description
Delete a Matrix block can be a bit pain when you have many Blocks. Simple solution was to duplicate the `delete` button and show him also on top after the `disable` button. 
![image](https://user-images.githubusercontent.com/764292/35799573-768023ae-0a66-11e8-8134-06904a1966fe.png)

### Additional info

- Craft version: RC8

**Comment by brandonkelly** [comment]
Agree if you have a lot of block types, the Delete option's position could be annoying. Would be weird to have two Delete options, but I just moved it up above the “Add [Block Type] above” options for the next release.

Also worth noting – you can delete multiple blocks at once by selecting them all first, and then clicking the Delete option on any one of them. (And you can even select a range of blocks at once by selecting one, and then shift-clicking on another one.)

**Comment by davidhellmann** [comment]
Thanks! Much better  :)
