### ISSUE TITLE
Image Editor: Broken :/

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#2401]
### Description
When I click `edit` Image this it was I saw now:
![image](https://user-images.githubusercontent.com/764292/35799694-cfc4a7a0-0a66-11e8-91ad-acc5b2223542.png)

There is no image to see. Loading is finished. 
Now, when I'm clicking first time on `cancel` it comes this:

When I'm clicking a second time on `cancel` the editor does not close.

When I'm clicking a third time on `cancel` this is coming:
![image](https://user-images.githubusercontent.com/764292/35799809-41351492-0a67-11e8-833b-b0d2edc511ae.png)

Sometime it needs more clicks to come to this point.

Again: To set the focal point there are to many clicks needed at the moment. 
Related to this: #2331 

### Additional info

- Craft version: RC8

**Comment by khalwat** [comment]
At @davidhellmann 's request, I logged into his site to test this... the image editor worked fine for me without incident on Chrome 64.0.3282.119 / Mac

**Comment by davidhellmann** [comment]
Really Strange. Test it on Chrome and Firefox (newest both) and there is the same problem. 
Test it on three different macs. hmmm

**Comment by davidhellmann** [comment]
![image](https://user-images.githubusercontent.com/764292/35807161-3a14fcfc-0a82-11e8-8c84-0cef9fc95c66.png)

No errors or something

**Comment by davidhellmann** [comment]
Safari also not working. Console said this: 
![image](https://user-images.githubusercontent.com/764292/35807453-230e03d6-0a83-11e8-9162-0d3782ac38ec.png)

**Comment by brandonkelly** [comment]
@davidhellmann Hard to tell if it's related, but it wouldn't hurt to fix that CORS issue you're getting, and see if it helps.

**Comment by khalwat** [comment]
I think @davidhellmann mentioned that he was invoking the image editor via the Edit Image button that my ImageOptimize plugin provided. So the problem could be my fault potentially, but it's irrelevant, since I've removed this button now that Craft has an Edit button on the image preview:

https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.4.13
