### ISSUE TITLE
CSS Files returning 404 template not found

### ISSUE THREAD

**Issue by mlaing88** [craftcms/cms#2402]
### Description
style.css file not loading, when viewed directly through url in browser it returns a 404 template not found error (see screenshots).

Other css files in the same directory are loading fine - however don't seem to be changing when updated via ftp.

### Additional info

- Craft version: 3.0.0-RC4
- PHP version: 7.0.22-0ubuntu0.16.04.1
- Database driver & version: MySQL 5.7.20-19
![2018-02-05](https://user-images.githubusercontent.com/28098426/35831423-8e38f9de-0ac1-11e8-9855-a003ac683995.png)

**Comment by brandonkelly** [comment]
@mlaing88 Looks like you're a few Craft 3 versions behind. Can you try updating to RC8 and see if you’re still having the same issue?

**Comment by mlaing88** [comment]
@brandonkelly thanks - updated to RC8 and all seems to be working now 👍🏻

**Comment by brandonkelly** [comment]
Good to hear, thanks!
