### ISSUE TITLE
FR: Provide bulk actions (Install/Disable) for plugins

### ISSUE THREAD

**Issue by engram-design** [craftcms/cms#2405]
Often we have 10-15 plugins that are installed on each site. Currently (with Craft 2) we have to quickly click the "Install" button on each plugin before the page reloads. However, with Craft 3 changing this Install button into a dropdown, this isn't the best feasible. Its also generally not the best approach in the first place!

I realise the code to actually install all plugins is trivial, but it'd be great to have a way to handle these bulk options. This may be useful for debugging (disable all plugins). Potentially, in a similar way to the Entries index, where you can check multiple plugins and have an element actions-like dropdown to perform bulk actions on plugins (Install, Uninstall, Enable, Disable).

**Comment by benface** [comment]
A way to quickly disable/enable all plugins would be great for debugging purposes!
