### ISSUE TITLE
Craft 3 pre-RC7 can fail to update in weirdly specific circumstances

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#2407]
### Steps to reproduce

1. Have a Craft install pre-RC7.
2. Install a plugin that accesses field data in it's `init()` method installed like https://github.com/mmikkel/CpFieldInspect-Craft
3. Update to the latest Craft release via the CLI.  `composer update`
4. Load the Control Panel to finish the update.
5. Get error:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sections.propagateEntries' in 'field list'
The SQL being executed was: SELECT `sections`.`id`, `sections`.`structureId`, `sections`.`name`, `sections`.`handle`, `sections`.`type`, `sections`.`enableVersioning`, `sections`.`propagateEntries`, `structures`.`maxLevels`
FROM `sections` `sections`
LEFT JOIN `structures` `structures` ON `structures`.`id` = `sections`.`structureId`
ORDER BY `name`
```

### Additional info

- Craft version: RC6, then latest.
- PHP version: n/a
- Database driver & version: n/a
- Plugins & versions: CpFieldInspect

**Comment by davist11** [comment]
Is there any solution to this problem?

**Comment by shift2design** [comment]
Having the same issue here when trying to update several C2 sites.

**Comment by shift2design** [comment]
I am having the same issue as Davist11. I have several C2 sites to update to Craft 3 and I get gateway timeout errors on update and then it results in the same error davist11 posted. Sent logs to support@craftcms.com.

**Comment by angrybrad** [comment]
@davist11 @shift2design your error is different than the original issue, but we've seen yours happen when an error occurs while updating (like a gateway timeout error) and Craft is not able to successfully restore the site/database to it's original pre-update attempt state.

You can use this as a starting point to help debug 504 gateway timeout errors. https://craftcms.com/support/504-gateway-timed-out-error

Ironically enough, I can't reproduce the original issue anymore so closing this one out.
