### ISSUE TITLE
Unused Matrix blocks cause huge amount of db queries 

### ISSUE THREAD

**Issue by swey** [craftcms/cms#2410]
### Description

Hi there,

we noticed that Craft will make two additional database requests for every new block type you add to a Matrix setting(!) even if that block type is never used.

Is it really necessary to make all those extra requests?

Thanks a lot for helping (and hopefully optimizing :))

### Steps to reproduce:
* Create a Matrix field "Body" with any block type
* Create a Section/Entry type "Test" with having the field "Body"
* Create new Entry in "Test" (without adding any content)
* Add a simple code output to the template `{{ entry.body|length }}`
* Monitor the amount of database queries
* Add a new block type to "Body" (just to the settings, still no usage)
* Compare the amount of database queries (=> 2 more)
* Add a new block type to "Body" (just to the settings, still no usage)
* Compare the amount of database queries (=> 2 more)
* ...

### Additional info

- Craft version: 3.0 RC9 (also tested with RC7 and older beta versions from November)
- PHP version: 7.1
- Database driver & version: MySQL
- Plugins & versions: Fresh installation

**Comment by brandonkelly** [comment]
Yes; but they are super small queries that should not have any noticeable impact on page load speeds.

**Comment by swey** [comment]
Thanks for your feedback @brandonkelly!

But even the page load speed is not noticeable affected, Craft still fires unused and unnecessary database requests.

In our recent project we have multiple and quite complex Matrix fields that cause around 300(!) db queries per page. In one case we use a Matrix inside a Matrix and that page hast 980(!) db queries. Getting noticeable in terms of page load speed... and of course also in terms of database load as soon multiple users requesting those pages the same time.

(Yes, we use a CDN in front of most pages, but some need to be excluded from this.)

**Comment by brandonkelly** [comment]
They are not unnecessary; Matrix needs to learn what the available field handles are for each of the available block types, in order to A) add the fields’ columns to the `SELECT` clause, and B) to give the field a chance to modify the element query.

That said, 980 😱 I guess we can find a way to reduce that

**Comment by swey** [comment]
Thanks for reopening!

Let's say they are unnecessary as long the blocks are not used. Maybe there is a simple solution to load only the field layouts of used blocks :)

**Comment by brandonkelly** [comment]
In hindsight they are not necessary, but Matrix doesn’t know that there aren’t any blocks until it has built and executed the query. And the fields are needed to help build the query in the first place.

**Comment by brandonkelly** [comment]
Alright, this should be fixed for the next release.

You can grab the fix early by changing your `craftcms/cms` version requirement in composer.json to `"dev-develop as 3.0.0-RC99"`, and then run `composer update`.

**Comment by swey** [comment]
Thanks @brandonkelly! In some cases we still have too many queries, but in most cases it helped a lot!

**Comment by brandonkelly** [comment]
@swey Feel free to open additional issues if you find other things that seem like they could be improved.

Guessing [eager loading](https://github.com/craftcms/docs/blob/v3/en/templating/eager-loading-elements.md) could help in some cases, too.
