### ISSUE TITLE
"first" used in css & js templating tags throws error

### ISSUE THREAD

**Issue by chasegiunta** [craftcms/cms#2413]
### Description
In the docs (https://github.com/craftcms/docs/blob/v3/en/templating/tags/css.md) it mentions a "first" keyword that can be added to end of the `css` & `js` tags. Using the tags without "first" work as expected, but upon adding "first", throws a `Unexpected token "name" of value "first" ("end of statement block" expected).` twig error.

### Steps to reproduce
 
```
{% set myCss %}
  body { background-color: #000; }
{% endset %}

{% css myCss first %}
```
or
```
{% set myJs %}
  console.log('test');
{% endset %}

{% js myJs first %}
```

### Additional info

- Craft version: 3.0.0-RC9
- PHP version: 7.1

**Comment by brandonkelly** [comment]
Sorry – documentation bug. Fixed now.
