### ISSUE TITLE
Field data not clearing after field removed from S3 asset volume field layout

### ISSUE THREAD

**Issue by bro-strummer** [craftcms/cms#2416]
### Description
I attached an entry field to an asset volume, filled the field for a couple of assets, and then realized I didn't really need the field. So I deleted it. Weirdly, the data is still there. I can tell because I'm still able to sort the CP by the field.

The data is still there even after clearing caches and updating asset indices. 

BTW, it's a remote asset volume on AWS S3.

### Steps to reproduce

1. Add entry field to S3 asset volume's field layout.
1. Fill out the field for a few assets.
1. Configure the asset volume index CP view to show the field.
1. Remove entry field from S3 asset volume's field layout.
1. Clear all caches.
1. Update all asset indices.

### Additional info

- Craft version: Craft Pro 3.0.0-RC9
- PHP version:  7.0.22
- Database driver & version: MySQL 5.7.18 
- Plugins & versions:
    - Amazon S3 1.0.8
    - ImageOptimize 1.4.13 (though there's no OptimizedImage field in the volume's field layout)

**Comment by brandonkelly** [comment]
This is expected behavior (for now), but there is an open feature request to change it: #1772
