### ISSUE TITLE
Craft 3 Email Column is showing Full Name

### ISSUE THREAD

**Issue by tjdraper** [craftcms/cms#2417]
### Description

When viewing users in the CP, the email column is showing the name instead

### Steps to reproduce

1. Log into a Craft control panel
2. View Users

### Additional info

- Craft version: 3.0.0-RC9
- PHP version: 7.1.3
- Database driver & version: mysqlnd 5.0.12-dev

![user-email-column-issue](https://user-images.githubusercontent.com/3803475/36012151-ca79da0a-0d21-11e8-82f5-b9296b8c08ef.png)

**Comment by brandonkelly** [comment]
Thanks for pointing that out. If your users didn’t have their real names filled out, then the column label would make sense, as the default thing that is shown is either their username or email (depending on the `useEmailAsUsername` config setting). Considering that it could be their real name, I’ve just relabelled the column to “User”, and added the option for dedicated Email and Username columns.
