### ISSUE TITLE
Table field type default values always has a blank row every time you edit the field type

### ISSUE THREAD

**Issue by tjdraper** [craftcms/cms#2418]
### Description

When creating a table field and deleting the default values row because it is not desired to have an empty row to start with, upon returning to edit the field, the empty default values row shows up again. Since the field has been saved without a default values row this should not happen.

### Steps to reproduce

1. Create a table field type and remove the default values row
    - This works as when you create an element with this field no default row shows up
2. Revisit the field type to edit some aspect of it and note that a blank default values row shows up
    - Don't do anything with this row
3. Save the field type and note that it now has an empty default values row
4. Visit an element and note that a blank row now shows up in the table field by default.

### Video

I demonstrated this bug/UX issue in a video so that it's easier to understand: https://vimeo.com/255045813/dcea2f2a19

### Additional info

- Craft version: 3.0.0-RC9
- PHP version: 7.1.3
- Database driver & version: mysqlnd 5.0.12-dev

**Comment by brandonkelly** [comment]
Thanks!
