### ISSUE TITLE
Plugin `schemaVersion` is cached in `plugins.php` and can't be updated

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#2419]
If you created a plugin that has a `schemaVersion` in the `extra` array, this data is cached in the `plugins.php` file by Craft.

If you then have db migrations that you want to run, you can't update the `schemaVersion` in your `composer.json` because Craft doesn't look there for it when loading the plugin. Instead, it looks at the cached into if has in `plugins.php`

If you then try to update the public property `$schemaVersion` in your plugin's primary class, this unfortunately is stomped on by the `schemaVersion` that is cached in the `plugins.php` file.

The only solution is to uninstall and re-install the plugin (which could potentially involve data loss, depending on the plugin), or manually edit the `plugins.php` file to remove the `schemaVersion` key/value pair.

I'll modify `generate-craftplugin` to remove the `schemaVersion` field from the `composer.json` and move it to the public property `$schemaVersion` but this does create a bit of an issue for any existing plugins that might run into this situation.

**Comment by khalwat** [comment]
Lindsey noted that if will check the `schemaVersion` if you bump the plugin's version number as well, so this actually may be a non-issue, if that's the intention functionality.

**Comment by brandonkelly** [comment]
> The only solution is to uninstall and re-install the plugin (which could potentially involve data loss, depending on the plugin), or manually edit the `plugins.php` file to remove the `schemaVersion` key/value pair.

This is only the case for `path` repos, where Composer doesn't ever re-check the repo when running `composer update`. If the plugin is installed via a Composer repo (either Packagist or the Plugin Store), then `vendor/craftcms/plugins.php` will be updated when the plugin is updated.

> Lindsey noted that if will check the `schemaVersion` if you bump the plugin's version number as well, so this actually may be a non-issue, if that's the intended functionality.

That’s not actually true; the two are always checked independently of each other.
