### ISSUE TITLE
Allow Post Action Overrides for Craft.BaseElementEditor

### ISSUE THREAD

**Issue by nateiler** [craftcms/cms#2425]
A similar implementation can be found here:
https://github.com/craftcms/cms/blob/d108cbd148600201041c84447f2babd67a9d8c57/src/web/assets/cp/src/js/BaseElementIndex.js#L1644

This settings makes it easier to point to a custom controller to serve the HUD Html

**Comment by nateiler** [comment]
Oh, this one would be really nice to override too: https://github.com/craftcms/cms/blob/d108cbd148600201041c84447f2babd67a9d8c57/src/web/assets/cp/src/js/BaseElementEditor.js#L225

**Comment by brandonkelly** [comment]
Use case?

**Comment by nateiler** [comment]
![screen shot 2018-02-13 at 8 10 55 am](https://user-images.githubusercontent.com/1892443/36156841-8350449e-1095-11e8-89ae-68375ea07500.png)

I've got a custom element index (User) which lists all associated users to an organization (custom element).  A user can also be associated to multiple 'departments' which is what I'm currently using the HUD for.

I may end up creating a HUD that's similar and not element specific and not on the actual element to manage these, so feel free to ignore if you wish.

**Comment by brandonkelly** [comment]
Yeah I think a custom HUD makes more sense.
