### ISSUE TITLE
Unsaved changes alert fires regardless if a change has been made

### ISSUE THREAD

**Issue by jwb009** [craftcms/cms#2428]
### Description
If you view an entry _without_ making any changes and navigate to a different page, the warning modal will still pop up saying 'Changes you made may not be saved.'  This doesn't occur if I use the back button on my mouse. It only happens when clicking.

### Steps to reproduce

1. View an entry
2. Click to a different page.
3. Notice the warning alert pop up.

### Additional info

- Craft version: 2.6.3008
- PHP version: 7.1.6-1
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Already fixed for today’s release :) But there was no actual GitHub issue for the bug yet, so just updated the changelog to point to this, if anyone needs more context.

**Comment by jwb009** [comment]
Awesome, thanks!

**Comment by jsunsawyer** [comment]
Getting this same issue when switching locales on entries in 2.6.3013

**Comment by brandonkelly** [comment]
@jsunsawyer Maybe plugin related?

**Comment by jsunsawyer** [comment]
@brandonkelly We have to update to Craft 3 to resolve an issue with matrix fields and new locales. Will check back in if this issue persists.
