### ISSUE TITLE
Saving entry as draft still populates in entry query

### ISSUE THREAD

**Issue by fvaldes33** [craftcms/cms#2429]
### Description
Saving a channel entry as a draft doesn't prevent it from populating in an entry query.

### Steps to reproduce

1. Save a channel entry as a draft
2. Prepare a query for that channel like so:

```
{% set postsQuery = craft.entries({
    section: 'blog',
    order: 'postDate desc'
}).all %}
```

3. The draft entry will show in the results

### Additional info

- Craft version: 3.0.0-RC9
- PHP version: 7.0.15
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
For step 1, assume this is for a brand new (never saved) entry?

**Comment by fvaldes33** [comment]
Yes, brand new entry.

**Comment by brandonkelly** [comment]
Thanks! Fixed just in time for today’s release :)

**Comment by fvaldes33** [comment]
Awesome! Thanks.
