### ISSUE TITLE
File upload fails using the Rich Text field if the filename contains an apostrophe.

### ISSUE THREAD

**Issue by jeslen** [craftcms/cms#2430]
### Description

I have a Rich Text field in one of my singles entries. The option for Available Assets Sources is set to All to allow for file uploads. If I upload a file that has an apostrophe in the filename the upload freezes. The loading bar is shown as full but never resolves.

### Steps to reproduce

1. Open entry that has a Rich Text field with available sources set to All
2. Select the File icon in the editor to open the Assets window to upload a file
3. Click the button at the bottom left labelled Upload files
4. Choose a file with an apostrophe in the filename

### Additional info

- Craft version: 2.6.2999
- PHP version: 5.6.31 
- Database driver & version:
    Database client version: libmysql - 5.5.45-37.4
    PHP extension: mysqli

**Comment by andris-sevcenko** [comment]
I'm not able to reproduce this. On that Craft version apostrophes are removed in filename on file upload.

Please enable devmode, reproduce this errors and submit a support ticket from your dashboard referencig this issue.

Thanks!
