### ISSUE TITLE
Error when switching entry type

### ISSUE THREAD

**Issue by DiederikVanHoorebeke** [craftcms/cms#2432]
### Description

When switching entry type, I get an error. `index.php?p=cms/actions/entries/switch-entry-type` replies with `An exception has been thrown during the rendering of a template ("Invalid field handle: fieldHandleName").`

The fieldHandleName is not the problem. I've already tried with a different one.

### Steps to reproduce

1. Create a new channel section and entry type.
2. Add an entry to the channel.
3. Create a new field (radio buttons in my case) and add it to a new entry type for that channel.
4. Go to the existing entry and switch to the new entry type.

### Additional info

- Craft version: **3.0.0-RC10**
- PHP version: **7.1.11**
- Database driver & version: **MySQL 5.7.20**
- Plugins & versions: 
  * Minify 1.2.7
  * Redactor 1.0.1
  * Mailchimp Subscribe 2.0.0
  * CP Field Inspect 1.0.2
  * Element Map 1.0.2
  * Expanded Singles 1.0.2
  * Videos 2.0.0-beta.6
  * Advanced Image Field 1.0.0
  * Wordsmith 3.0.2
  * Inventory 2.0.0
  * Redirect plugin for Craft 3 1.0.14
  * schema 1.0.0
  * Logs 3.0.0
  * Image Resizer 2.0.1
  * Super Table 2.0.3

**Comment by brandonkelly** [comment]
Thanks! Fixed now. We'll get a hotfix update out soon.

**Comment by DiederikVanHoorebeke** [comment]
I can confirm it's fixed. Thank you!
