### ISSUE TITLE
Cannot publish a draft with an auto-generated title

### ISSUE THREAD

**Issue by iparr** [craftcms/cms#2440]
### Description

I have a reasonably complicated auto-generated title:
```
{%if object.eventName%}{eventName}{%elseif object.eventPerformerMatrix.one()%}{eventPerformerMatrix.one().guest|default('')}{eventPerformerMatrix.one().maker|first|default('')}{%elseif object.eventPromoter%}{eventPromoter.one().title}{%endif%}
```

This works pretty well (!), unless you use the draft functionality. In those cases the *title* field appears upon hitting the "Publish draft" button with the message "Title cannot be blank."

This field was not there before I hit the button.

I tried entering a dummy title, just to trick the system into publishing the entry, however I can't click to focus the (red outlined) title field. I can't click on another field and tab into it either. It knows it shouldn't be there. It's a ghost field!

### Steps to reproduce

1. Make changes to an existing entry. Save as draft.
2. Select draft for publishing, use "Publish draft" drop down button.

### Additional info

- Craft version: RC10.1
- PHP version: 7.0.8
- Database driver & version: MySQL 5.7.21
- Plugins & versions: Redirect plugin for Craft 3 | 1.0.14, Contact Form | 2.1.1, Redactor | 1.0.1

**Comment by brandonkelly** [comment]
Can you please send a database backup to support@craftcms.com?
