### ISSUE TITLE
3.0.0 RC11?

### ISSUE THREAD

**Issue by goinnovative** [craftcms/cms#2455]
I try to install craftcms/redactor but it always ask for Craft CMS 3.0.0 RC11?

How to install this version? Can't find this on https://packagist.org/packages/craftcms/cms#3.0.0-RC10.1

**Comment by brandonkelly** [comment]
How are you trying to install Redactor?

**Comment by goinnovative** [comment]
With composer requier craftcms/redactor like mentioned on the readme..

**Comment by brandonkelly** [comment]
Open your composer.json and see if you have this line:

```json
"minimum-stability": "dev"
```

Assuming you do, you can either remove it, or force Composer to install the latest stable version (1.0.1)  with this command:

```
composer require craftcms/redactor:1.0.1
```

Or you can just install the Redactor plugin from the Plugin Store within your Control Panel.
