### ISSUE TITLE
Message: Looping through element queries directly has been deprecated.

### ISSUE THREAD

**Issue by MrGlasspoole** [craftcms/cms#2459]
### Description

Message in Deprecation Errors:
Looping through element queries directly has been deprecated. Use the all() function to fetch the query results before looping over them.

### Origin

/var/www/proteus-iv/templates/assets/index.twig:23

### Stacktrace

`24	Deprecation error: Looping through element queries directly has been deprecated. Use the all() function to fetch the query results before looping over them. 
Called from /var/www/proteus-iv/vendor/craftcms/cms/src/elements/db/ElementQuery.php:393
23	craft\elements\db\EntryQuery::getIterator() 
Called from /var/www/proteus-iv/storage/runtime/compiled_templates/05/050a0b4391db935c9fd78c20446cb736e2cbdabea5fbc6f59b56bd7853b3475e.php:67
22	__TwigTemplate_1df74e373556a65a862aec9fe5abf90fc052bc1968b774ce90893ff3ee3996bf::block_main(["view" => craft\web\View, "SORT_ASC" => 4, "SORT_DESC" => 3, "POS_HEAD" => 1, ...], ["main" => [__TwigTemplate_1df74e373556a65a862aec9fe5abf90fc052bc1968b774ce90893ff3ee3996bf, "block_main"]]) 
Called from /var/www/proteus-iv/vendor/twig/twig/lib/Twig/Template.php:188
21	__TwigTemplate_1df74e373556a65a862aec9fe5abf90fc052bc1968b774ce90893ff3ee3996bf::displayBlock("main", ["view" => craft\web\View, "SORT_ASC" => 4, "SORT_DESC" => 3, "POS_HEAD" => 1, ...], ["main" => [__TwigTemplate_1df74e373556a65a862aec9fe5abf90fc052bc1968b774ce90893ff3ee3996bf, "block_main"]]) 
Called from /var/www/proteus-iv/storage/runtime/compiled_templates/05/050a0b4391db935c9fd78c20446cb736e2cbdabea5fbc6f59b56bd7853b3475e.php:37
20	__TwigTemplate_1df74e373556a65a862aec9fe5abf90fc052bc1968b774ce90893ff3ee3996bf::doDisplay(["view" => craft\web\View, "SORT_ASC" => 4, "SORT_DESC" => 3, "POS_HEAD" => 1, ...], ["main" => [__TwigTemplate_1df74e373556a65a862aec9fe5abf90fc052bc1968b774ce90893ff3ee3996bf, "block_main"]]) 
Called from /var/www/proteus-iv/vendor/twig/twig/lib/Twig/Template.php:389
19	__TwigTemplate_1df74e373556a65a862aec9fe5abf90fc052bc1968b774ce90893ff3ee3996bf::displayWithErrorHandling(["view" => craft\web\View, "SORT_ASC" => 4, "SORT_DESC" => 3, "POS_HEAD" => 1, ...], ["main" => [__TwigTemplate_1df74e373556a65a862aec9fe5abf90fc052bc1968b774ce90893ff3ee3996bf, "block_main"]]) 
Called from /var/www/proteus-iv/vendor/craftcms/cms/src/web/twig/Template.php:51
18	__TwigTemplate_1df74e373556a65a862aec9fe5abf90fc052bc1968b774ce90893ff3ee3996bf::displayWithErrorHandling(["view" => craft\web\View, "SORT_ASC" => 4, "SORT_DESC" => 3, "POS_HEAD" => 1, ...], ["main" => [__TwigTemplate_1df74e373556a65a862aec9fe5abf90fc052bc1968b774ce90893ff3ee3996bf, "block_main"]]) 
Called from /var/www/proteus-iv/vendor/twig/twig/lib/Twig/Template.php:366
17	__TwigTemplate_1df74e373556a65a862aec9fe5abf90fc052bc1968b774ce90893ff3ee3996bf::display([], []) 
Called from /var/www/proteus-iv/vendor/craftcms/cms/src/web/twig/Template.php:32
16	__TwigTemplate_1df74e373556a65a862aec9fe5abf90fc052bc1968b774ce90893ff3ee3996bf::display([]) 
Called from /var/www/proteus-iv/vendor/twig/twig/lib/Twig/Template.php:374
15	__TwigTemplate_1df74e373556a65a862aec9fe5abf90fc052bc1968b774ce90893ff3ee3996bf::render([]) 
Called from /var/www/proteus-iv/vendor/twig/twig/lib/Twig/Environment.php:289
14	craft\web\twig\Environment::render("assets", []) 
Called from /var/www/proteus-iv/vendor/craftcms/cms/src/web/View.php:308
13	craft\web\View::renderTemplate("assets", []) 
Called from /var/www/proteus-iv/vendor/craftcms/cms/src/web/View.php:356
12	craft\web\View::renderPageTemplate("assets", []) 
Called from /var/www/proteus-iv/vendor/craftcms/cms/src/web/Controller.php:120
11	craft\controllers\TemplatesController::renderTemplate("assets", []) 
Called from /var/www/proteus-iv/vendor/craftcms/cms/src/controllers/TemplatesController.php:79
10	craft\controllers\TemplatesController::actionRender("assets", [])
9	call_user_func_array([craft\controllers\TemplatesController, "actionRender"], ["assets", []]) 
Called from /var/www/proteus-iv/vendor/yiisoft/yii2/base/InlineAction.php:57
8	yii\base\InlineAction::runWithParams(["template" => "assets"]) 
Called from /var/www/proteus-iv/vendor/yiisoft/yii2/base/Controller.php:157
7	craft\controllers\TemplatesController::runAction("render", ["template" => "assets"]) 
Called from /var/www/proteus-iv/vendor/craftcms/cms/src/web/Controller.php:80
6	craft\controllers\TemplatesController::runAction("render", ["template" => "assets"]) 
Called from /var/www/proteus-iv/vendor/yiisoft/yii2/base/Module.php:528
5	craft\web\Application::runAction("templates/render", ["template" => "assets"]) 
Called from /var/www/proteus-iv/vendor/craftcms/cms/src/web/Application.php:240
4	craft\web\Application::runAction("templates/render", ["template" => "assets"]) 
Called from /var/www/proteus-iv/vendor/yiisoft/yii2/web/Application.php:103
3	craft\web\Application::handleRequest(craft\web\Request) 
Called from /var/www/proteus-iv/vendor/craftcms/cms/src/web/Application.php:216
2	craft\web\Application::handleRequest(craft\web\Request) 
Called from /var/www/proteus-iv/vendor/yiisoft/yii2/base/Application.php:386
1	craft\web\Application::run() 
Called from /var/www/proteus-iv/web/index.php:21`

### Additional info

- Craft version: Personal 3.0.0-RC10.1
- PHP version: 7.2.2
- Database driver & version: MySQL 5.5.5
- Plugins & versions: none

**Comment by carlcs** [comment]
https://github.com/craftcms/docs/blob/v3/en/changes-in-craft-3.md#treating-queries-as-arrays

**Comment by angrybrad** [comment]
Not a bug, you just need to update your template to call `.all()` first like in @carlcs's [link](https://github.com/craftcms/cms/issues/2459#issuecomment-366866336)
