### ISSUE TITLE
"Require password reset" doesn't work with new user

### ISSUE THREAD

**Issue by jstewartdesign** [craftcms/cms#2460]
### Description

When selecting "Require a password reset on next login" the next time the user logs in it fails to login (no error message)

### Steps to reproduce

1. Create a new user
2. Activate the account
3. Setup a password for the account using the "Copy password reset URL"
4. In a private/incognito window paste the URL and enter a new password
5. In admin check the box "Require a password reset on next login" on the new user account and save
6. Try and login with new password - nothing will happen (spinner appears then disappears)
7. Uncheck "Require a password reset on next login"
8. Attempt login again - working

### Additional info

- Craft version: RC 10.1
- PHP version: 7.2.1
- Database driver & version: MySQL 5.5.58
- Plugins & versions:

Custom Entry Order	1.0.0
Expanded Singles	1.0.2
Redactor	1.0.1

**Comment by brandonkelly** [comment]
I am able to reproduce this when Craft is not properly configured to send emails.
