### ISSUE TITLE
Changing filled channel into structure losses the ability to rearrange entries

### ISSUE THREAD

**Issue by E2design** [craftcms/cms#2461]
### Description
I had a channel filled with a number of entries. Decided to reorganise and changed the existing channel into a structure. Everything worked out well except that I'm not able to reorder the entries because the reorder icon isn't visible in the (changed) structure overview

### Steps to reproduce

1. Create a channel
2. Fill the channel with entries
3. Change the channel into a structure
4. Try to rearrange the entries 

### Additional info

- Craft version: 3.0.0-RC10.1
- PHP version: 7.0.25
- Database driver & version: 5.7.21

![schermafdruk 2018-02-20 14 50 15](https://user-images.githubusercontent.com/5907530/36427401-68935fb6-164d-11e8-9371-6c3e93db2657.png)

**Comment by angrybrad** [comment]
Likely you're running into this: https://craftcms.stackexchange.com/questions/2160/changed-section-from-channel-to-structure-but-cant-re-order-entries
