### ISSUE TITLE
Error while handling error crash when set baseurl to @web/someSite

### ISSUE THREAD

**Issue by marionnewlevant** [craftcms/cms#2464]
### Description
Attempting to take advantage of the new features:
> Craft no longer relies on the CRAFT_SITE constant to determine which site it should serve. If it’s not set, it will compare the requested URL with the sites’ base URLs and use the closest match. (#2397)
> It is no longer necessary to route sites with base URI paths to separate index.php files. Craft will automatically detect URI segments that were meant to be part of the site base URI, and ignore them when routing the request.

So I have just the one unmodified index.php, and I set the base URL for site `someSite` to `@web/someSite` and every cp request after that is just the attached stack trace, complaining of Invalid path alias.

Setting the baseUrl back to NULL in the database gets me going again.

### Additional info

- Craft version: Craft Pro 3.0.0-RC11
- PHP version: 7.0.13
- Database driver & version: MySQL 5.7.16
- Plugins & versions: Redactor 1.0.1 ; Agnostic Fetch 2.0.3

[stackTrace.txt](https://github.com/craftcms/cms/files/1742985/stackTrace.txt)

**Comment by brandonkelly** [comment]
Good ol’ order of operation bugs. Fixed now, thanks!
