### ISSUE TITLE
Globals gone when added new primary site (Craft 3 RC11)

### ISSUE THREAD

**Issue by larsboldt** [craftcms/cms#2465]
### Description
Globals gone when added new primary site (Craft 3 RC11)

### Steps to reproduce

1. Add a global group with some content
2. Add a new primary site
3. Global group gone

### Additional info

- Craft version: 3 RC11
- PHP version: 7.1
- Database driver & version: Mysql 5.6
- Plugins & versions: None

**Comment by brandonkelly** [comment]
Thanks for pointing that out! The bug has been fixed for the next release, but we couldn’t fix it retroactively, so updating won’t be enough in your case. To get your globals back, do either one of these things:

- Edit the previous primary site, and re-enable it as the primary site. Then wait for queue to complete before changing it back.
- For each of your global sets, go to `http://example.com/admin/globals/<site-handle>/<global-set-handle>`, and click Save. (Replace `<site-handle>` with the previous primary site’s handle, and `<global-set-handle>` with the global set handle. You can find that by looking at the `globalsets` database table, if you forget.)
