### ISSUE TITLE
When 'adding another' entry in a multi-site, the next new entry should be in the same site as the previous entry

### ISSUE THREAD

**Issue by peteheaney** [craftcms/cms#2466]
### Description

With multi-site, when creating a new entry in a non-primary site, clicking 'Save and add another' redirects back to the entry page, but with the primary site selected rather than the non-primary site to which the previous entry was added.

I think it would make sense if 'adding another' to be redirected back to the same site the last entry was added to.

### Steps to reproduce

1. Setup a multi-site with two (or more) sites
2. Create a section (_channel_ or _structure_) that is available in both sites
3. Create a new entry in a non-primary site and click 'Save and add another'
4. You will be redirected back to the new entry page, but with the primary site selected

### Additional info

- Craft version: 3.0.0-RC11
- PHP version: 7.1.1
- Database driver & version: MySQL 5.6.35

**Comment by peteheaney** [comment]
This is fixed in b55c7a6

**Comment by brandonkelly** [comment]
Ah whoops, forgot about this. Guess technically #2844 was a duplicate. Thanks for pointing that out!
