### ISSUE TITLE
Asset thumbnails and transforms not working on S3 volumes

### ISSUE THREAD

**Issue by petehjfd** [craftcms/cms#2468]
### Description
This may be related to #2463 but it seems like a different issue.

Since updating to 3.0.0-RC11, image thumbnails and transforms don't seem to be working for Amazon S3 volumes.

When uploading a new image, either in the main Assets area or via an image field, a thumbnail is not generated. When attempting to output a transformed version of the image in the template, the image does not load (the image URL looks like `/index.php?p=actions/assets/generate-transform&transformId=12`).

I can see that the original image has been uploaded to S3 but the transformed version has not (because it's not being loaded in the template and therefore never being created).

This only affects images uploaded after the update to RC11. For images uploaded prior to that, all thumbnails and transforms are working correctly.

### Steps to reproduce

1. Be on version RC11
2. Create an S3 volume
3. Create a transform
4. Upload an image to the S3 volume (either in the main Assets area or via an image field)

### Additional info

- Craft version: 3.0.0-RC11
- PHP version: 7.1.1
- Database driver & version: MySQL 5.6.35
- Plugins & versions: Amazon S3 1.0.8

**Comment by brandonkelly** [comment]
Can you please try changing your `craftcms/cms` version requirement in composer.json to `"dev-develop as 3.0.0-RC99"`, and then run `composer update` and see if this is fixed for you?

**Comment by brandonkelly** [comment]
99% sure this stems from the same issue as #2463, so closing it now. @petehjfd if that ends up not being the case, please let me know.

**Comment by petehjfd** [comment]
Yep, that fixed it, thanks @brandonkelly
