### ISSUE TITLE
Changing an Entry Type after an initial save stops saving values of new fields

### ISSUE THREAD

**Issue by Harry-Harrison** [craftcms/cms#2474]
### Description
Took quite a while to pinpoint what's happening here but I think I've got it. If you change the entryType of an entry after it's been saved as a different entryType once before, and newly revealed fields do not have their values saved.

If a new field is required it still submits, but when the entry edit page reloads the field is empty.

### Steps to reproduce

1. Create a structure
2. Create two entry type's on it called _type1_ and _type2_
3. Create two fields called _field1_ and _field2_
4. Assign _field1_ to _type1_ and _field1_ and _field2_ to _type2_
5. Create a new entry using _type1_ and populate the _field1_ on it and save
6. Edit that new entry and change it's type to _type2_
7. Update the value of _field1_ and _field2_ and save
8. Notice how _field1_ will be updated but _field2_ will be blank

### Additional info

- Craft version: Craft Pro 3.0.0-RC11
- PHP version: 7.2.2
- Database driver & version: MySQL 5.7.20
- Plugins & versions: N/A

**Comment by admench** [comment]
I have precisely the same issue.

- php v7.2.2
- craft 3 RC11
- mysql 5.7.20

**Comment by brandonkelly** [comment]
Fixed – thanks! Getting a release out soon.

**Comment by admench** [comment]
Good job @brandonkelly thanks for the quick response - this was frustrating, so pleased to see you pick this up so quickly!

**Comment by brandonkelly** [comment]
I bet! Sorry for the frustration 😞
