### ISSUE TITLE
Create a new child entry dropdown URL is incorrect

### ISSUE THREAD

**Issue by Harry-Harrison** [craftcms/cms#2475]
### Description
The url the **Create a new child entry** item in the action dropdown is incorrect. It tries to go to `/admin/admin/entries/market/new?parentId=65` – So their's one extra admin segment in there.

### Steps to reproduce

<img width="365" alt="screen shot 2018-02-22 at 09 43 59" src="https://user-images.githubusercontent.com/140605/36531193-04128076-17b5-11e8-9018-caf89c4279ca.png">

### Additional info

- Craft version: Craft Pro 3.0.0-RC11
- PHP version: 7.2.2
- Database driver & version: MySQL 5.7.20
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
Strange. I’m not able to reproduce this. The URL is generated with the `Craft.getUrl()` JavaScript function, which is used in various other places throughout the Control Panel as well.

Can you please tell me the following?

- Open up your JavaScript console and type `Craft.baseUrl`. What does that output?
- Are you setting the `baseCpUrl` setting in `config/general.php` ? If so, to what?
- What is the full URL in your browser when this occurs?

(For each of these, it’s ok to replace the hostname with `example.com` if you need to redact that info.)

**Comment by Harry-Harrison** [comment]
- `"/admin"`
- `'baseCpUrl' => '/'`
- `http://example.com/admin/admin/entries/market/new?parentId=59`

I did a little extra digging and found a solution to be to not set `'cpTrigger' => 'admin'` and also to unset `baseCpUrl `. Still odd that every other link works apart from that one.
