### ISSUE TITLE
User unable to delete its own entries

### ISSUE THREAD

**Issue by babau67** [craftcms/cms#2478]
### Description

Setting a User Groups Permissions to:

Edit entries
- Create entries
- Publish live changes
- Delete entries

without checking the other options (_Edit other authors’ entries and Edit other authors’ drafts_)

Users are able to create and publish their own entries but they can't delete them.

Only checking:

```
- Edit other authors’ entries
  - Delete other authors’ entries
```

They are able to delete them

### Steps to reproduce

1. setting the User Groups Permissions to:
    ```
    - Edit entries
      - Create entries
      - Publish live changes
      - Delete entries
    ```
2. login as user in that groups
3. create an entry and publish it
4. try to delete it

### Additional info

- Craft version: Craft CMS 3.0.0-RC10.1
- PHP version: 7.0.25
- Database driver & version:MySql 5.7.21
- Plugins & versions:
Redactor 1.0.1
CP Field Inspect 1.0.2
Inventory 2.0.0
Control Panel CSS 2.1.0
Super Table	2.0.4

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you please send a database backup to support@craftcms.com and reference this issue?
