### ISSUE TITLE
[Enhancement] Asset folder drag and dropable

### ISSUE THREAD

**Issue by MiMaMuh** [craftcms/cms#2479]
Hi,

it would be awesome when the asset folder itself is responsive to dragged and dropped files. Right now pushing always the "Upload file" button is a little bit annoying. It would be awesome to be able to just drag files in the preview or have at least a drop-zone?

**Comment by brandonkelly** [comment]
To be clear, in addition to being able to upload files within the file view with drag-n-drop (which is already possible), you want the individual volume folders in the sidebar to be drop zones as well?

**Comment by brandonkelly** [comment]
The whole file area already is a drop zone ;)

**Comment by MiMaMuh** [comment]
[A small video about what I mean :)](https://drive.google.com/file/d/11T7PsJ_YlJ-jN0s3uEZhHq7WFPHVR5T0/view?usp=sharing) as it seems I have a different experience.

**Comment by brandonkelly** [comment]
Ahhh, looks like the drop zone is only as tall as the list of files. If you don’t have any files yet, that’s not a very big drop zone :)

Going to mark this as a bug; that doesn’t seem right.
