### ISSUE TITLE
Feature Request: Default / First User should have same language setting as site

### ISSUE THREAD

**Issue by robzor** [craftcms/cms#2480]
### Description
Currently, if I set up a new Craft install and select en-GB as my language for the site, the admin user (and I am going to assume all subsequent users) have English (United States) set as their default user.

Hopefully a small one, but can the default user/s' language setting be the same as the site one?

(Also, something about the default timezone being LA but that's another ticket for another day ;))

### Additional info

- Craft version: Craft 3 RC11
- PHP: 7.2 using Laravel Valet, intl module not installed.

**Comment by brandonkelly** [comment]
Easy enough. Done!

**Comment by robzor** [comment]
Ha! Thanks! :D
