### ISSUE TITLE
Empty redactor field no longer false in twig

### ISSUE THREAD

**Issue by marionnewlevant** [craftcms/cms#2481]
### Description
I have a richtext field `headline`. In Craft 2 I could test it: `{% if entry.headline %}` and get false for an empty field. Craft 3, that is a 
```
object(craft\redactor\FieldData)[3362]
  private '_pages' => null
  private '_rawContent' => string '' (length=0)
  private 'content' (Twig_Markup) => string '' (length=0)
  private 'charset' (Twig_Markup) => string 'UTF-8' (length=5)
```
which is not false.

I think in the past, these things were `null`.

### Steps to reproduce

1. create a rich text field
2. save some entry/global with this field in it (but empty)
3. Test the value

### Additional info

- Craft version: Craft Personal 3.0.0-RC12
- PHP version: 7.0.13
- Database driver & version:
- Plugins & versions: Redactor 1.0.1

**Comment by angrybrad** [comment]
`{% if entry.headline|length %}` or `{% if entry.headline.getRawContent() %} definitely works, although at first glance I'm having a hard time seeing how Craft 2 behavior would be any different.

**Comment by marionnewlevant** [comment]
I'll double check in Craft 2. Maybe it's a feature request...

**Comment by brandonkelly** [comment]
Just verified in Craft 2, an empty Rich Text field will normalize to `null`.
