### ISSUE TITLE
Clarify @web alias usage, especially with siteUrl

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#2486]
Docs state `@web` alias is:
> The URL to the folder that contains the index.php file that was loaded for the request

To me, I assumed that meant it would attempt to dynamically build a full URL, using [`yii\web\Request::getHostInfo`](https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L706).

What you _actually_ get is just the dirname string (not URL) where the served `index.php` relative to the web root, so often an empty string.

So while the field instructions state you can use `@web`, if you do you _also_ have to set the `siteUrl` config in `general.php`.

![screen shot 2018-02-23 at 10 43 04 am](https://user-images.githubusercontent.com/18329/36605118-bf753718-188d-11e8-8b59-bb1bab3fa415.png)

It also doesn't let you put merely `@web`, but will allow `@web/`.

At the least I think this needs to be clarified in docs and siteUrl field instructions.

Now knowing how Yii handles `@web`, personally I will probably begin setting my own `@baseUrl` alias that uses `yii\web\Request::getHostInfo`, and set my siteUrl config setting to that.

Especially if not dealing with a multisite, it seems silly to require a static siteUrl be set (either in config or cp, when most of the time dynamically getting it from the current request is sensible).

**Comment by timkelty** [comment]
I think part of the problem is this: https://github.com/craftcms/cms/blob/develop/src/helpers/UrlHelper.php#L326-L336

If a site has not `baseUrl`, Craft is trying to get it dynamically, however because the trailing slash is added `$currentSite->baseUrl` is `/`, even when the `siteUrl` is `null`.

**Comment by timkelty** [comment]
Here's what my config might look like for this to work:
```
use yii\web\Request;

$request = new Request;

return [
    '*' => [
        'aliases' => [
          '@baseUrl' => $request->getHostInfo(),
        ],
        'siteUrl' => '@baseUrl',
    ],
];
```

I tried redefining `@web`, but that doesn't work, so I'm using my own `@baseUrl` alias.

In it's current state, unless i'm missing something, I'm not sure how `@web` is very helpful, as it isn't a full url.

**Comment by brandonkelly** [comment]
Agree it's weird that the host info isn’t included in `@web`, so now Craft is setting the value itself and including that.

**Comment by timkelty** [comment]
Perfect, thanks!
