### ISSUE TITLE
Purpose of calling hasEventHandlers() before trigger()

### ISSUE THREAD

**Issue by putyourlightson** [craftcms/cms#2489]
### Question

Is there a purpose for checking whether `hasEventHandlers()` returns `true` before triggering an event, or is that redundant? I'm just trying to understand best practices for adding events to plugins.

```php
// Fire a 'beforeSaveSection' event
if ($this->hasEventHandlers(self::EVENT_BEFORE_SAVE_SECTION)) {
    $this->trigger(self::EVENT_BEFORE_SAVE_SECTION, new SectionEvent([
        'section' => $section,
        'isNew' => $isNewSection
    ]));
}
```

### Additional info

- Craft version: 3.0.0 RC12

**Comment by brandonkelly** [comment]
We’re following Yii’s convention, for the most part, but there’s a slight performance/memory improvement by not instantiating event classes that aren’t going to be needed.

The only time we blindly create an event class and trigger it is if something further down in the code needs to reference a property on the event, for example `if ($event->isValid)`. (Also following Yii’s conventions.)

**Comment by putyourlightson** [comment]
Got it, thanks for the explanation Brandon!!
