### ISSUE TITLE
Unless a site has an absolute base URL set, all activation/reset URLs and emails are relative

### ISSUE THREAD

**Issue by bendesilva** [craftcms/cms#2490]
### Description

If a base URL of a site is set to the @web alias, all activation and password reset emails (and associated URLs available through the CP) are relative rather than absolute. For instance a URL will be set as 

/admin/actions/users/set-password?code=1DhWFwgjd2ZN2z7bJ8iKN4VSlurVSGt9&id=4364798d-d46c-434c-a0b7-40b00ac79431

Rather than 

http://testdomain.com/admin/actions/users/set-password?code=1DhWFwgjd2ZN2z7bJ8iKN4VSlurVSGt9&id=4364798d-d46c-434c-a0b7-40b00ac79431

### Steps to reproduce

1. Set the Base URL of your site to @web
2. Create a new user
3. Send an activation email, request a password reset or copy an activation URL

### Additional info

- Craft version: Craft 3 RC 12
- PHP version: 7.2

**Comment by brandonkelly** [comment]
As of the next release, `@web` will be an absolute URL (see #2486 / 5f3d4908dfe263fe131512313d61367346b56b1a), so this is fixed now :)
