### ISSUE TITLE
Unable to revert to a revision for a channel or structure, error "Undefined property: craft\models\EntryVersion::$link"

### ISSUE THREAD

**Issue by bendesilva** [craftcms/cms#2491]
### Description

When attempting to revert to a previous revision for a channel or structure entry the error "Undefined property: craft\models\EntryVersion::$link" occurs upon save. This does not occur for singles.

It appears as though the error is linked to having variables in the entry URI format, if the format is static (like a single) then the error does not occur.

I have also experienced the issue on an existing craft site prior to saving and simply when selecting the previous revision from the dropdown menu.

### Steps to reproduce

1. Create a new Craft CMS project
2. Create a new channel or structure section, leave all the defaults as they are including the entry URI format as including {slug}
3. Create an entry within the section.
4. Save the entry a few times to generate revisions
5. Select a revision
6. Save the entry

### Additional info

- Craft version: Craft 3 RC 12
- PHP version: 7.2
- Database driver & version: MySQL 5.6

**Comment by brandonkelly** [comment]
Fixed, thanks!
