### ISSUE TITLE
Undeprecate `getAssetThumbUrl` event

### ISSUE THREAD

**Issue by aelvan** [craftcms/cms#2493]
When you deprecated the `getAssetThumbUrl` event (see https://github.com/craftcms/cms/issues/2398#issuecomment-363208887), there is no way to replace the thumb generation in Craft with an external service, like Imgix. The `getThumbPath` event takes a path, so the thumb has to be generated locally (and end up in /cpresources). 

As far as I can tell, the reason you deprecated it was a different use-case, and this one probably was not considered. Any chance of undeprecating it?

**Comment by brandonkelly** [comment]
Done 👍

**Comment by aelvan** [comment]
Awesome, thanks!
