### ISSUE TITLE
Base URL field does not appear when selecting Amazon S3 volume type

### ISSUE THREAD

**Issue by peteheaney** [craftcms/cms#2494]
### Description
Prior to RC12, you would:
- select the Amazon S3 volume type
- enter your Access Key ID and Secret Access Key
- click refresh to load the buckets list

at which point, the Base URL would be revealed, auto-populated with the S3 bucket URL.

Since RC12, the Base URL field does not appear. You have to save the volume then go back in to the volume settings to update the Base URL field.

### Steps to reproduce

1. Create a new volume
2. Select the S3 volume type
3. Enter access key and secret
4. Click refresh

### Additional info

- Craft version: 3.0.0-RC12
- PHP version: 7.1.1
- Database driver & version: MySQL 5.6.35

**Comment by brandonkelly** [comment]
We were able to reproduce this _if_ the first interaction with the “ Assets in this volume have public URLs” setting was interpreted as a drag (meaning the cursor moved slightly mid-click), but it wasn’t dragged far enough to actually trigger a lightswitch value change.

Fixed now, for today’s release.
