### ISSUE TITLE
EmailVerifyUrl and PasswordResetUrl generated from current site?

### ISSUE THREAD

**Issue by milanjandric** [craftcms/cms#2496]
### Description
Should URLs generated for EmailVerify email and PasswordReset email be to the current site, or to a primary site? 

I have been expecting to be returned to the same site I have used to fill in a "Forgotten password" form when clicked on a link in an email, and not to the "Primary" one.

### Additional info
- Craft version:Craft Pro 3.0.0-beta.29
- PHP version: 7.0.27

**Comment by brandonkelly** [comment]
Currently it is expected that the URLs would be for the primary site. If you have a use case where that isn’t desirable, can you post it as a new feature request, and explain the reason?
