### ISSUE TITLE
Matrix block ids not saved when saving first entryversion of an entry

### ISSUE THREAD

**Issue by steverowling** [craftcms/cms#2498]
### Description

When versioning is turned on for a section, serialised versions of an entry saved in the `craft_entryversions` have the block `id` of individual matrix blocks stripped from the entry content.

The `id`s for all other native element types are preserved when an entry version is saved, so it seems odd and inconsistent that the matrix block `id` is not saved as part of the entry version as well.

I am using the matrix block `id` to relate entries to specific matrix blocks in another entry. This works well until you attempt to retrieve an earlier saved version of an entry, using `craft()->entryRevisions->getVersionById()`, when the relation breaks as the matrix block `id` has not been saved in the entry version.

### Steps to reproduce

1. Set up a section with `Enable versioning for entries in this section?` switched on.
2. Add a matrix field to the entry with a number of blocks of content.
3. Save the entry, then edit and save again. Repeat as necessary.
4. Check the earlier versions of the entry in the `craft_entryversions` table. All the content has been preserved, with the exception of the matrix block `id`s which don't exist.

### Additional info

- Craft version: 2.6.3000
- PHP version: 7.1.8
- Database driver & version: MySQL 5.6.35
- Plugins & versions: Not relevant.

**Comment by steverowling** [comment]
I've been digging around with this for a bit more and I can see that the matrix block `id` _is_ being saved as part of the entry version in the `craft_entryversions` table.

However, when using `craft()->entryRevisions->getVersionById()` to get the entry version from the DB when there is only one version of the entry existant, the matrix block `id`s are not being set on the returned `EntryVersionModel`. Instead, the `id`s are being set as `new1`, `new2`, etc. as if they were new matrix blocks, whereas the content of each block is being returned correctly.

And now I see why. When the first version of an entry is saved in the `craft_entryversions` table, the matrix block `id`s are indeed saved as `new1`, `new2`, etc., rather than the actual `id`s of the matrix blocks.

Since the entry has already been saved (including the matrix blocks) before an entry version is saved, it should be possible to save the first version with the actual matrix block `id`s rather than the placeholder `new1, `new2`, `id`s.

Please would you consider adding this so that matrix block `id`s are properly retrievable for all entry versions.

Thanks!

**Comment by brandonkelly** [comment]
If you save an existing entry without creating any new blocks, are the block IDs getting saved correctly?

**Comment by steverowling** [comment]
Yes. As soon as you save a second version of an entry, without creating any new blocks, the matrix block ids are saved correctly.

**Comment by brandonkelly** [comment]
Thanks! All fixed for tomorrow’s update :)
