### ISSUE TITLE
Failed to set referrer policy

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#2499]
### Description

I’m getting this error in Safari console, probably related to this PR #2436 

> Failed to set referrer policy: The value 'origin-when-cross-origin' is not one of 'no-referrer', 'origin', 'no-referrer-when-downgrade', or 'unsafe-url'. Defaulting to 'no-referrer'.

### Additional info

- Craft version: 3.0 RC 12
- Browser: Safari 11.0.3

**Comment by brandonkelly** [comment]
Yeah Safari has added support in the upcoming 11.1 release. (https://caniuse.com/#search=referrer) In the meantime, falling back to `no-referrer` is fine.
