### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry

### ISSUE THREAD

**Issue by mishellnovosel** [craftcms/cms#2503]
Hi,

I've started receiving weird Server error yesterday when I try to update Fields or Sections. 

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '876-211' for key 'craft_fieldlayoutfields_layoutId_fieldId_unq_idx' The SQL being executed was: INSERT INTO craft_fieldlayoutfields (layoutId, tabId, fieldId, required, sortOrder, dateCreated, uid, dateUpdated) VALUES (876, 1174, 211, 0, 1, '2018-02-27 09:33:43', '65064258-b790-4ea0-a923-a4cd46f47e48', '2018-02-27 09:33:43')

### Steps to reproduce

1. Open existing section or field
2. Edit any value and save changes

### Additional info

- Craft version: Craft Pro 3.0.0-RC12 , Multisite installation
- PHP version: 7.0.27
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
 -- Redactor - 1.0.1
 -- Amazon S3 - 1.0.8
 -- Wordsmith - 3.0.2
 -- Redactor Font Awesome - 2.0.4
 -- Super Table - 2.0.4
 -- Json Client - 1.0.1

I have same setup on my DEV server, and update is working correctly there, but on live environment I receive described errors. They started to happen after update from 3.0.0-RC10 to RC12.

Any idea why and how to fix it?
Thank you.

**Comment by brandonkelly** [comment]
Sounds like something in your database didn’t get deleted in full at some point. Can you send a database backup to support@craftcms.com so we can look into it?

**Comment by farrellScript** [comment]
@brandonkelly do you remember what caused this? I'm experiencing the same error after updating a site from Craft 2 to 3.
