### ISSUE TITLE
Custom date/time field as entry title

### ISSUE THREAD

**Issue by himynameisphil** [craftcms/cms#2504]
### Description
Using a custom date/time field to generate an entry title doesn't seem to work as intended. I think it's using the 'Updated at' date instead.

### Steps to reproduce

1. Create a custom dateTime field and assign it to an entry type.
2. Update the entry type's Title Format to include the custom dateTime value.

### Additional info

- Craft version: Craft CMS 3.0.0-RC12
- PHP version: 7.1.8

**Comment by brandonkelly** [comment]
What is your entry type’s title format?

**Comment by himynameisphil** [comment]
{{ entry.dateTime|date("l jS F") }}

**Comment by brandonkelly** [comment]
Delete `entry.` and it will work:

```twig
{{ dateTime|date('l jS F') }}
```
or single-braces will work as well here:
```
{dateTime|date('l jS F')}
```
