### ISSUE TITLE
Entries cannot be serialized anymore

### ISSUE THREAD

**Issue by Rias500** [craftcms/cms#2506]
### Description
When passing an entry to the queue, Yii tries to serialize it, but in a recent change

https://github.com/craftcms/cms/commit/de493974ccc908e741cf24de16f9469cb473415a#diff-da1851d592b1e6e8f1e8303c34f51582R541

there was a validator added with a closure and closures cannot be serialized.

A similar issue with the solution can be seen here: https://github.com/yiisoft/yii2/issues/7773#issuecomment-82889529

The validator should be changed to a method on the model.

### Steps to reproduce

1. Try to create a queue job with an entry model
2. Fails

### Additional info

- Craft version: 3-RC13
- PHP version: 7.1

**Comment by brandonkelly** [comment]
Thanks!
