### ISSUE TITLE
Naming a block type "Section" in a matrix prevents saving (with unique handle)

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#2508]
### Description
Naming a block type "Section" in a matrix field results in the same save error as a reserved name error even when using a different, unique handle.

### Steps to reproduce

1. Create a matrix field
2. Add Block Type with Name "Section" and a Handle "somethingSection"
3. Save

### Additional info

- Craft version: Craft CMS 3.0.0-RC13
- PHP version: 7.1.13
- Database driver & version: MySQL 5.5.5

**Comment by Radabaugh** [comment]
Hey @jsunsawyer, we're having trouble reproducing this error. If you're still experiencing the error you can open a support ticket by emailing support@craftcms.com. If you provide a database backup, and reference this issue in the email, we would be happy to dig deeper.

**Comment by jsunsawyer** [comment]
@Radabaugh I'm able to name a block "Section" now without an error.
