### ISSUE TITLE
Selectize styling is broken

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#2510]
### Description

Selectize styling is broken

### Steps to reproduce

1. Open license purchase screen
2. Open country drop down

### Additional info

<img width="201" alt="screen shot 2018-03-01 at 18 34 38" src="https://user-images.githubusercontent.com/25124/36832378-662247f4-1d7f-11e8-94a4-cef61e5c34e3.png">

Also applied in custom plugin:

<img width="305" alt="screen shot 2018-03-01 at 18 37 07" src="https://user-images.githubusercontent.com/25124/36832436-97ef5484-1d7f-11e8-9a2b-8a61af68ed7d.png">

- Craft version: RC-13
- PHP version: 7.1

**Comment by brandonkelly** [comment]
Strange, looking fine on my end.

> <img width="177" alt="screen shot 2018-03-01 at 3 02 10 pm" src="https://user-images.githubusercontent.com/47792/36874658-9736f894-1d61-11e8-8a4b-4b02c1f77e58.png">

What browser/version are you using? Any browser extensions that might be messing with it?
