### ISSUE TITLE
Default value for checkbox not respected

### ISSUE THREAD

**Issue by justjoolz** [craftcms/cms#2511]
### Description

Just noticed that when creating a custom checkbox field on an asset the default setting of the checkbox is not respected and no value is selected by default.

### Additional info

- Craft version:  CMS 3.0.0-RC13
- PHP version: 7.1.6

**Comment by brandonkelly** [comment]
Currently, this is expected behavior. Default values only apply to brand new elements. Behavior will change when #2446 is implemented, though.
