### ISSUE TITLE
Warn before switching sites in element editor HUDs

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#2512]
Feedback from two Clients yesterday during a Backend Workshop:

When you have fields on Assets und you edit them and you switch the site (dropdown) there is not warning that changes are lost like "You have changed stuff, please save before you switch" or stuff like this. Can you add a small text under the Dropdown when something changes?

For me as Dev it's fine but for clients it's not the best behaviour —  UX : )

![image](https://user-images.githubusercontent.com/764292/36839735-23047a1e-1d43-11e8-8326-08e626e83eac.png)

**Comment by ryanpcmcquen** [comment]
For anyone else bitten by this issue, until an official fix is in place, this has been working well for my team:

```css
.hud-shade,
.modal-shade {
    position: static;
}
```

We added it using: https://plugins.craftcms.com/cp-css

**Comment by brandonkelly** [comment]
This has been resolved for Craft 3.5, which will start warning authors before switching sites within an element editor HUD, if there are any unsaved content changes.
