### ISSUE TITLE
Emoji in entry titles throw a DB errors

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#2513]
### Steps to reproduce

1. Create an entry
2. Add an emoji to the title  🕷🐨

### Additional info

- Craft version: rc-13
- PHP version: 7.1
- Database driver & version: MariaDB 10.2.13

**Comment by brandonkelly** [comment]
We only support emoji in titles in PostgreSQL, but i suppose we could at least check for it and set a validation error.
