### ISSUE TITLE
[Enhancement] Total number of entries

### ISSUE THREAD

**Issue by nexflo** [craftcms/cms#2516]
There is no native way to see the total amount of entries in channel.

In a Content Management System one should natively see how many entries are in a section I believe - this shouldn't be left to a plugin, but feels like the most "core" of features?

**Comment by ryanmasuga** [comment]
I agree that this feels like a core feature. It would help offset frustration with infinite scroll and lack of pagination in the CP.

**Comment by brandonkelly** [comment]
This is a duplicate of #1023
