### ISSUE TITLE
Replacing Field Layout of a Section does not Update `fieldLayoutId` of Elements

### ISSUE THREAD

**Issue by sbossarte** [craftcms/cms#2517]
### Description

Manually setting a new field layout on a section via PHP will not update the `fieldLayoutId` property of `elements` associated with the section. This causes these entries to become immutable, as any save made in the backend will, while appearing to succeed, not actually update any of the entry's content.

### Steps to reproduce

1. Create a single section with the handle `testSection`.
2. Run:
```
$section = \Craft::$app->getSections()->getSectionByHandle('testSection');
$entrytype = \Craft::$app->getSections()->getEntryTypesBySectionId($section->id)[0];
$tab = new \craft\models\FieldLayoutTab();
$tab->name = 'PHP-Generated-Tab';
$tab->sortOrder = 1;
$tab->setFields([]);
$fieldlayout = new \craft\models\FieldLayout();
$fieldlayout->setTabs([$tab]);
$fieldlayout->setFields([]);
$fieldlayout->type = \craft\elements\Entry::class;
$entrytype->setFieldLayout($fieldlayout);
Craft::$app->getSections()->saveEntryType($entrytype);
```
3. Make any additional manual edits to the section's field layout (add or remove fields/tabs/etc.).
4. Edit and save the single entry.

### Additional info

- Craft version: 3.0.0-RC10.1
- PHP version: 7.1.14
- Database driver & version: MySQL 5.5.56

**Comment by brandonkelly** [comment]
I would say this is expected, since an entry type’s field layout ID isn’t supposed to ever change. You should modify its existing field layout rather than replace it with a new one.

If you want to keep replacing it, then it’s on you to update existing elements’ `fieldLayoutId` records as well.
