### ISSUE TITLE
Required Asset fields incorrectly validate when populated from front-end

### ISSUE THREAD

**Issue by elvdm** [craftcms/cms#2519]
### Description

I am trying to save custom fields to the User field layout from the front-end with Axios, to allow a user to create content for their user profile. Some of these are Asset fields.

I receive `{fieldHandle} cannot be blank` errors for required Asset fields.
I have verified that the data is being sent correctly to the controller (`users/save-user` action), and the files show up as expected when I dump the $_FILES array in the controller method. Not sure if this is expected behaviour, but images do not appear in the customFields array when I dump the User element after running `$user->setFieldValuesFromRequest('fields');` (the other custom fields do).

When I make the field not required so that it passes validation, the image uploads fine and appears on the User field layout as expected.

### Steps to reproduce

1. Add a new Asset field that accepts images to the User field layout. Make it required.
2. Try populate the User's field layout from the front-end asynchronously with JS (using Axios in my case).

### Additional info

Craft version: RC-13
PHP version: 7.1.8
Database driver & version: MariaDB 10.2.13

**Comment by andris-sevcenko** [comment]
@elvdm Is this still an issue after the fixes we implemented for #2550?

**Comment by elvdm** [comment]
@andris-sevcenko No, don't seem to be having any more issues. Thanks!
