### ISSUE TITLE
PostgreSQL Paginated Search Error

### ISSUE THREAD

**Issue by leigeber** [craftcms/cms#2520]
### Description

When trying to paginate entries with a search term a PostgreSQL exception is thrown.

```
SQLSTATE[42803]: Grouping error: 7 ERROR: column "elements.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 15: ORDER BY CASE WHEN "elements"."id"=145 THEN 0 WHEN "elements...
```

I'm not sure why order by criteria is even being applied in this context (twice in fact) since its a count query? Thanks!

```php
{% set searchTerm = craft.app.request.getParam('search') %}

{% paginate craft.entries({
	limit: 10,
	search: searchTerm,
	section: 'support'
}) as entries %}
```

### Additional info

- Craft version: Craft Pro 3.0.0-RC13
- PHP version: 7.2.2
- Database driver & version: PostgreSQL 9.6.3
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you send a DB backup to support@craftcms.com ?

**Comment by leigeber** [comment]
There's a lot going on in our setup so I threw up a fresh, vanilla install of the latest RC on PostgreSQL, created a Single section called "Homepage" with just a title field and then put the following in the template for the index. The search does actually have to match results to throw the error it seems so I used 'homepage' as the term in this case.

If these instructions don't trigger it and a backup of the new setup would help I'll send it over. Thanks.

```twig
{% paginate craft.entries({
	limit: 10,
	search: 'homepage',
	section: 'homepage'
}) as entries %}
```

The error output in full is...

```
SQLSTATE[42803]: Grouping error: 7 ERROR:  column "elements.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 15: ORDER BY CASE WHEN "elements"."id"=2 THEN 0 ELSE 1 END

The SQL being executed was: SELECT COUNT(*)
FROM (SELECT "elements"."id" AS "elementsId", "elements_sites"."id" AS "elementsSitesId", "content"."id" AS "contentId"
FROM "craft_elements" "elements"
INNER JOIN "craft_entries" "entries" ON "entries"."id" = "elements"."id"
INNER JOIN "craft_elements_sites" "elements_sites" ON "elements_sites"."elementId" = "elements"."id"
INNER JOIN "craft_content" "content" ON "content"."elementId" = "elements"."id"
LEFT JOIN "craft_structureelements" "structureelements" ON "structureelements"."elementId" = "elements"."id"
WHERE ("entries"."sectionId" = '1') AND ("elements_sites"."siteId"=1) AND ("content"."siteId"=1) AND ("elements"."archived"=FALSE) AND ((("elements"."enabled"=TRUE) AND ("elements_sites"."enabled"=TRUE)) AND ("entries"."postDate" <= '2018-03-04 04:20:43') AND (("entries"."expiryDate" IS NULL) OR ("entries"."expiryDate" > '2018-03-04 04:20:43'))) AND ("elements_sites"."enabled"=TRUE) AND ("elements"."id"=2)
ORDER BY CASE WHEN "elements"."id"=2 THEN 0 ELSE 1 END) "subquery"
INNER JOIN "craft_entries" "entries" ON "entries"."id" = "subquery"."elementsId"
INNER JOIN "craft_elements" "elements" ON "elements"."id" = "subquery"."elementsId"
INNER JOIN "craft_elements_sites" "elements_sites" ON "elements_sites"."id" = "subquery"."elementsSitesId"
INNER JOIN "craft_content" "content" ON "content"."id" = "subquery"."contentId"
LEFT JOIN "craft_structureelements" "structureelements" ON "structureelements"."elementId" = "subquery"."elementsId"
ORDER BY CASE WHEN "elements"."id"=2 THEN 0 ELSE 1 END
```

**Comment by brandonkelly** [comment]
Just realized I wasn’t able to reproduce because we had already fixed the underlying bug. So this will be fixed for you in RC14. Or you can get the fix ahead of time by changing your `craftcms/cms` version requirement in composer.json to `"dev-develop as 3.0.0-RC99"`, and running `composer update`.

**Comment by leigeber** [comment]
Thanks, Brandon, that does resolve the issue. However, in case it's related or a side effect of the fix... if I do happen to put order: 'score' on the criteria it does blow up now.

```
SQLSTATE[42703]: Undefined column: 7 ERROR:  column "score" does not exist
LINE 9: ORDER BY "score"
```

**Comment by brandonkelly** [comment]
You probably just need to change it to `orderBy: ['score' => SORT_DESC]`. (Or use the method – `orderBy('score')`.)

**Comment by leigeber** [comment]
Gotcha, it works chained with order/orderBy or using object format on the criteria, not array as above. Maybe https://github.com/craftcms/docs/blob/c62ea7b6cf1ed7bb405b836daaa18f528f386116/en/searching.md#ordering-results-by-score should reflect something else? Over and out.

**Comment by brandonkelly** [comment]
Ah good point. Just tweaked Craft so it doesn't care as much how `orderBy` is set (5b5f919a).
