### ISSUE TITLE
Request's getUrl method should return an absolute URL

### ISSUE THREAD

**Issue by rynpsc** [craftcms/cms#2521]
### Description

`craft.app.request.getUrl()` should output an absolute URL rather than a relative one, or accept a parameter to do so.

### Steps to reproduce

1. Set site URL using either the `@web` alias or explicitly set the URL 
2. Output `{{ craft.app.request.getUrl() }}` in a template - shows relative url, unlike Craft 2 which is absolute

### Additional info

- Craft version: Craft Personal 3.0.0-RC13
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Plugins & versions:

**Comment by brandonkelly** [comment]
Yeah in Craft 2, `craft.request.getUrl()` was actually a shortcut for `url(craft.request.path)`. A closer Craft 3 equivalent is `craft.app.request.getAbsoluteUr()`.

**Comment by chasegiunta** [comment]
@brandonkelly should it behave the same for applicable elements then, for consistency? `entry.getUrl()` should return `/entry-slug` instead of the whole _absolute_ url?

**Comment by brandonkelly** [comment]
@chasegiunta An element’s `getUrl()` method could already go either way; it will return the site’s URL combined with the element’s URI. So it will be absolute or root-relative depending on the site’s URL. And if the site’s URL is root-relative, there’s no way we could definitively come up with an absolute URL for an element.
