### ISSUE TITLE
Author - missing as a reserved word? Craft CMS 3 - RC13

### ISSUE THREAD

**Issue by larsboldt** [craftcms/cms#2522]
### Description
I added a textfield called author, now I can't log in. Maybe I should have been warned this was a reserved word and Craft should have not saved the textfield?

1. in /home/vagrant/code/vendor/craftcms/cms/src/templates/_components/widgets/RecentEntries/body.html at line 10
{%- if CraftEdition >= CraftClient and entry.author %}, {{ entry.author.username }}{% endif -%}

### Steps to reproduce

1. Add a textfield to an entry in a section called author
2. Log out, log in.

### Additional info

- Craft version: 3RC13
- PHP version: 7.2
- Database driver & version: 5.6
- Plugins & versions:

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you send a DB backup to support@craftcms.com ?
