### ISSUE TITLE
Let CSRF Token Be Available 

### ISSUE THREAD

**Issue by zmetcalf** [craftcms/cms#2523]
I am not sure if this is an issue or just a lack of understanding on my part, but the CRAFT_CSRF_TOKEN cookie is set as httpOnly on this line: https://github.com/craftcms/cms/blob/d8e023276cc065a63000f8c51965b69ca3ed457e/src/Craft.php#L103

after being called from here: 
https://github.com/craftcms/cms/blob/ad740287644ea113206212e55046bbeb16b64a47/src/config/app.web.php#L42

Should this cookie be hidden from JavaScript? If it isn't available to JavaScript, why is it there?

**Comment by zmetcalf** [comment]
Also, as a follow up question, is there a better way to force the session other than putting the `{{ csrfInput()}}` in the template? (re: #1765)

**Comment by angrybrad** [comment]
> Should this cookie be hidden from JavaScript?

Yes, by default.  It's reduces attack surface and most installs don't need access to it from JS.

If you have an explicit need where you need to, you can override component behavior in `craft/config/app.php`.

> is there a better way to force the session other than putting the {{ csrfInput()}} in the template?

You can use `{{ craft.app.session.open() }}

**Comment by zmetcalf** [comment]
Thank you @angrybrad
