### ISSUE TITLE
Selecting an image transform inside of Redactor and saving is broken

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#2524]
### Description

If you setup a Rich Text field with access to an Volume and a Transform, when you select an Image in Redactor and apply a Transform, then save the element, the generated tokens get mangled when trying to view the element again.

Creating issue here instead of Redactor repo because it looks to be a bug in the Craft parseRefs logic.

### Steps to reproduce

1. Install Redactor, create an Asset volume and a transform.
2. Create a Redactor field and give it access to the volume and transform.
3. Add Redactor field to a a section and create an entry.
4. Insert and image into Redactor and select a transform.
5. Notice the image source similar to:

> http://path/to/craft/web/img/uploads/_transformName/file.jpg#asset:19:transform:transformName

6. Save and view the entry.
7. Notice the image source is now similar to:

> {asset:19:transform:transformName}#asset:19:transform:transformName

Additionally, this gets logged:

```
craft\services\Elements::_getRefTokenReplacement

An exception was thrown when parsing the ref tag "{asset:19:transform:transformName}":

Setting read-only property: craft\elements\Asset::cpEditUrl
```

### Additional info

- Craft version: 3.0 RC13
- PHP version: 7.0
- Database driver & version: MySQL 5.7
- Plugins & versions: Redactor 1.0.1

**Comment by vimcat** [comment]
I'm on RC 14 and the html coming back looks like this: 

<img src="{asset:47:transform:w273}" alt="">
