### ISSUE TITLE
Content Migrations: sections and single page error on migrate/up with blank uriFormat

### ISSUE THREAD

**Issue by skramstad** [craftcms/cms#2525]
### Description
When running ./craft migrate/up with this code and uriFormat is blank for homepage. It fails to run the migration. Setting null does not work either. However if I set something random in the uriFormat field it works.

Is this a bug or am I missing something?

Thanks!

Error message below:

       *** failed to apply m180304_095011_entry_homepage (time: 0.021s)
       0 from 1 migrations were applied.
      Migration failed. The rest of the migrations are canceled.

Migration:

        // Get the primary site ID
        $siteId = Craft::$app->sites->getPrimarySite()->id;

        //
        // Create Home
        //
        $homepage = new Section([
            'name' => 'Home',
            'handle' => 'homepage',
            'enableVersioning' => 1,
            'type' => 'single',
            'siteSettings' => [
                new Section_SiteSettings([
                    'siteId' => $siteId,
                    'uriFormat' => '',
                    'template' => 'index',
                    'hasUrls' => 1,
                ])
            ]
        ]);

        return Craft::$app->sections->saveSection($homepage);

### Steps to reproduce

1. Create a [new migration](https://craftcms.com/news/craft-3-content-migrations) with migrate/create 
2. Insert this code
3. `./craft migrate/up`

### Additional info

- Craft version: Craft Pro 3.0.0-RC13
- PHP version: 7.0.25
- Database driver & version: MySQL 5.7.21

**Comment by brandonkelly** [comment]
If you want the single to be the homepage, you must set its `uriFormat` to `__home__`.
