### ISSUE TITLE
New "Delete" Permission for Users and User Groups.

### ISSUE THREAD

**Issue by MattWilcox** [craftcms/cms#2529]
### Description

The ability to delete Entries / Users / etc should be a Permission that can be assigned to Users and User Groups. If they don't have the permission to do so, instead offer to archive the item the user wants to delete. Ideally this feature would be combined with clearer warnings about what happens to content when its owner User is deleted (But that's another issue: https://github.com/craftcms/cms/issues/875 )

Creating this new FR at Brandon's request ( https://github.com/craftcms/cms/issues/875#issuecomment-370392104 )

**Comment by brandonkelly** [comment]
> The ability to delete Entries / Users / etc should be a Permission that can be assigned to Users and User Groups.

There alreadiy are “Delete” permissions:

- Delete users
- Delete entries
- Delete other authors’ entries
- Delete other authors’ drafts
- Remove files and folders

> If they don't have the permission to do so, instead offer to archive the item the user wants to delete.

Craft 3.1 will introduce soft-deletes (#867), but that will replace hard-deletes, not act as an alternative for users that don’t have delete permissions.

> Ideally this feature would be combined with clearer warnings about what happens to content when its owner User is deleted

Already done.
