### ISSUE TITLE
orderBy defaulting to postDate asc instead of desc?

### ISSUE THREAD

**Issue by robzor** [craftcms/cms#2531]
### Description
Hi there,

On my homepage template I am fetching the latest 4 news entries, using this query:

```twig
{% set newsList = craft.entries.section('news').limit(4).all() %}
```

I have created 4 news entries, and then **updated their post dates** either directly when working on the entry or after an initial save.

I am expecting the default order to be `postDate desc`. Instead I appear to be getting either `postDate asc` or `dateCreated desc`.

This means I am having to manually add `.orderBy('postDate desc')` to the query.

Screenshot of the entries in the CP with their creation date vs their post date:

<img width="483" alt="screenshot 2018-03-05 17 21 46" src="https://user-images.githubusercontent.com/704032/36989468-bd6f2564-2099-11e8-8524-828ba291a41e.png">

Screenshot of front-end output:

![screenshot-2018-03-05-17 26 56](https://user-images.githubusercontent.com/704032/36989815-c2320cb4-209a-11e8-865e-dabe1529e490.png)

### Additional info

Using latest version of Laravel Valet

- Craft version: 3.0.0 RC13
- PHP version: 7.2.2
- Database driver & version: MySQL 5.7.21

**Comment by robzor** [comment]
Additionally, if I try using
 `{% set newsList = craft.entries.section('news').limit(4).orderBy('dateCreated desc').all() %}`

I get this error:
```
Integrity constraint violation – yii\db\IntegrityException
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'dateCreated' in order clause is ambiguous
```

**Comment by brandonkelly** [comment]
Fixed, thanks!

Regarding that SQL error, that’s because a single element query joins in multiple tables with `dateCreated` columns. So you will need to set it to `'elements.dateCreated desc'`.

**Comment by robzor** [comment]
Aha! awesome.
