### ISSUE TITLE
Invalidating a Structure Move Event Does not Work as Expected

### ISSUE THREAD

**Issue by jayhaase** [craftcms/cms#2537]
### Description

Comments in the file `craftcms/cms/src/base/Element.php`describe being able to cancel a structure element move by setting `ElementStructureEvent::isValid` to `false`. See code snippet below:

```php
/**
 * @event ElementStructureEvent The event that is triggered before the element is moved in a structure.
 * You may set [[ElementStructureEvent::isValid]] to `false` to prevent the element from getting moved.
 */
const EVENT_BEFORE_MOVE_IN_STRUCTURE = 'beforeMoveInStructure';
```

When I set  `ElementStructureEvent::isValid` to `false` during a move event, the move will not be saved, but the Ajax display notice to the user will say "New position saved."

### Steps to reproduce

1. Register for the event

```php
Event::on(
    Element::class,
    Element::EVENT_BEFORE_MOVE_IN_STRUCTURE,
    [$this, 'handleBeforeMoveInStructure']
);
```

2. In the event handler set `isValid` to `false`

```php
public function handleBeforeMoveInStructure(ElementStructureEvent $event)
{
    $event->isValid = false;
}
```

3. Go to an the Entries page and view a structure.
4. Drag a structure entry to a new position.
5. Notice the message: New position saved.
6. Refresh the page in the browser and notice the structure position was not saved.

### Additional info

- Craft version:  3.0.0-RC13
- PHP version: 7.2.2
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
Fixed, thanks!
