### ISSUE TITLE
[FR] Currency Symbol for Sites

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#2540]
We built a Shop with different languages. 
Next to the country code should be the Currency Symbol for the language.

Any way to bring this in with core features?

AT (€)
US ($)

And Stuff like this.

**Comment by davidhellmann** [comment]
Something like this
![image](https://user-images.githubusercontent.com/764292/37048142-48aabbc4-216d-11e8-9b67-38cadcc83ca8.png)

**Comment by brandonkelly** [comment]
Each locales doesn’t necessarily have a single currency, so we can’t do anything to make this easy for you.

That said you could write a macro that outputs it.

```twig
{% macro currencySymbol() %}
{%- spaceless %}
    {% switch craft.app.language %}
        {% case 'en-us' %}
            $
        {% default %}
            €
    {% endswitch %}
{% endspaceless -%}
{% endmacro %}

{% from _self import currencySymbol %}

{{ currencySymbol() }}

**Comment by davidhellmann** [comment]
Oh yes, macro! Good solution I think that can work. Thanks!
