### ISSUE TITLE
New Entry button is positioned offscreen in IE11

### ISSUE THREAD

**Issue by mattandrews** [craftcms/cms#2545]
### Description
On Internet Explorer 11, a flexbox issue causes the "New entry" button to render almost entirely offscreen:

![screenshot 2018-03-07 10 16 13](https://user-images.githubusercontent.com/394376/37086969-dead6ff8-21f0-11e8-855f-d763e26928c9.png)

### Steps to reproduce

1. Load up your favourite IE11 VM
2. Visit `/admin/entries`

### Steps to fix

This is just me digging into the CSS, but it looks like applying `flex: 1` to the `#extra-headers` element fixes it (without breaking anything in other browsers):

![screenshot 2018-03-07 10 16 23](https://user-images.githubusercontent.com/394376/37087078-2b93ad78-21f1-11e8-8e55-d04a9b26361b.png)

### Additional info

- Craft version: Craft CMS 3.0.0-RC13
- PHP version:  7.1.11

**Comment by brandonkelly** [comment]
Fixed, thanks!

**Comment by mattandrews** [comment]
❤️
