### ISSUE TITLE
[Feature Request] Eager-loaded collections should use the same API as non-eager-loaded ones

### ISSUE THREAD

**Issue by benface** [craftcms/cms#2549]
It would be nice if we didn't have to write different code for listing/accessing elements that were eager-loaded vs those that were loaded normally. Kinda similar to what [this plugin](https://github.com/marionnewlevant/craft-agnostic_fetch) is doing, but I really believe this should be part of the core. It would be very useful for re-using code (such as Twig macros, or plugin services/variables) that should work with an element query or a collection of elements regardless of whether eager-loading was used or not.

**Comment by nateiler** [comment]
Seems the eager loaded elements could be set on the appropriate `ElementQuery::setCachedResult()`.

**Comment by brandonkelly** [comment]
Yeah that’s probably the direction we’d take for relation fields. But this would be a breaking change so not something we can do until 4.0.
