### ISSUE TITLE
No validation on asset fields when populated from front-end

### ISSUE THREAD

**Issue by pju-** [craftcms/cms#2550]
### Description
When uploading to an asset field from a frontend-form via entries/save-entry, it seems there is not validation:
- There are no checks for filesize (unlike if you upload to the asset field from the cp)
- There are no checks for file type (unlike if you upload to the asset field from the cp)
- There are no checks for the amount of files (unlike if you upload to the asset field from the cp)
In all those cases, the files will be uploaded and the asset field populated with the uploaded file.

This issue is similar to [this one](https://github.com/craftcms/cms/issues/2519) but I figured it should have it's own discussion, please move it if that's not the case.

### Steps to reproduce

1. Set up a section with an asset field.
2. Set up a regular, non-ajax frontend-form as described [here](https://craftcms.com/docs/templating/entry-form), with the necessary adjustments for Craft3 (save-entry instead of saveEntry, csrfInput() instead of getCsrfInput().
3. Try different validation rules for the asset field as described above.

### Additional info

- Craft version: Craft Personal 3.0.0-RC14
- PHP version: 7.1.11
- Database driver & version: MySQL 5.5.5
- Plugins & versions: None

**Comment by pju-** [comment]
Thanks for the quick work, but it seems this is only partially fixed. These two problems remain:

- There are no checks for filesize (unlike if you upload to the asset field from the cp - the maxUploadFileSize config is ignored).
- There are no checks for the amount of files - if the field is e.g. set to accept two files only, you can still upload more than two files. The field will only contain two files though. This seems similar to the cp though (where you can upload as many files as you like, but select only two).

### Additional info

- Craft version: Craft Personal 3.0.0-RC15

**Comment by andris-sevcenko** [comment]
As for the second point, you can easily implement some client-side validation so that the user can only upload two files. As you said - it's similar to cp and the limitation is selecting two files, not uploading two files.

I'll look into the filesize thing.
