### ISSUE TITLE
Duplicate file uploads when uploading from frontend

### ISSUE THREAD

**Issue by pju-** [craftcms/cms#2551]
### Description
When uploading to an asset field from a frontend-form via entries/save-entry, there are duplicate files uploaded when there is more than one site setup and **propagate entries across all enabled sites** is activated for the section.

When I try uploading pdf files, the duplicate file has a filename with timestamp attached to the original filename, but is not a valid pdf file (filesize is 0 bytes).

When I try uploading an image, an craft\errors\ImageException is thrown (see below), even though I tried uploading a valid file.

From the stack trace it appears that the propagation triggers another asset safe:
> craft\elements\Asset::afterSave(false) 
(…)
> craft\elements\Asset::afterSave(true) 

### Steps to reproduce

1. Set up a section with an asset field.
2. Set up a regular, non-ajax frontend-form as described [here](https://craftcms.com/docs/templating/entry-form), with the necessary adjustments for Craft3 (save-entry instead of saveEntry, csrfInput() instead of getCsrfInput().
3. Set up a second site.
4. Try posting a new entry with file upload from the frontend.

### Additional info

- Craft version: Craft Personal 3.0.0-RC14
- PHP version: 7.1.11
- Database driver & version: MySQL 5.5.5
- Plugins & versions: None

### Error message (for the image case)
`
craft\errors\ImageException: 
The file “assets5aa00d63d297e9.08968811.JPG” does not appear to be an image. 

in /Applications/XAMPP/xamppfiles/htdocs/craft3-test/vendor/craftcms/cms/src/image/Raster.php:169

    1. in /Applications/XAMPP/xamppfiles/htdocs/craft3-test/vendor/craftcms/cms/src/image/Raster.php at line 169
    2. in /Applications/XAMPP/xamppfiles/htdocs/craft3-test/vendor/craftcms/cms/src/services/Images.php at line 213 – craft\image\Raster::loadImage('/Applications/XAMPP/xamppfiles/h...')
    3. in /Applications/XAMPP/xamppfiles/htdocs/craft3-test/vendor/craftcms/cms/src/helpers/Image.php at line 188 – craft\services\Images::loadImage('/Applications/XAMPP/xamppfiles/h...')
    4. in /Applications/XAMPP/xamppfiles/htdocs/craft3-test/vendor/craftcms/cms/src/elements/Asset.php at line 1413 – craft\helpers\Image::imageSize('/Applications/XAMPP/xamppfiles/h...')
    5. in /Applications/XAMPP/xamppfiles/htdocs/craft3-test/vendor/craftcms/cms/src/elements/Asset.php at line 1216 – craft\elements\Asset::_relocateFile()
    6. in /Applications/XAMPP/xamppfiles/htdocs/craft3-test/vendor/craftcms/cms/src/services/Elements.php at line 459 – craft\elements\Asset::afterSave(true)
    7. in /Applications/XAMPP/xamppfiles/htdocs/craft3-test/vendor/craftcms/cms/src/fields/Assets.php at line 303 – craft\services\Elements::saveElement(craft\elements\Asset)
    8. in /Applications/XAMPP/xamppfiles/htdocs/craft3-test/vendor/craftcms/cms/src/base/Element.php at line 1723 – craft\fields\Assets::afterElementSave(craft\elements\Entry, false)
    9. in /Applications/XAMPP/xamppfiles/htdocs/craft3-test/vendor/craftcms/cms/src/elements/Entry.php at line 976 – craft\base\Element::afterSave(false)
    10. in /Applications/XAMPP/xamppfiles/htdocs/craft3-test/vendor/craftcms/cms/src/services/Elements.php at line 459 – craft\elements\Entry::afterSave(false)
    11. in /Applications/XAMPP/xamppfiles/htdocs/craft3-test/vendor/craftcms/cms/src/services/Elements.php at line 1337 – craft\services\Elements::saveElement(craft\elements\Entry, true, false)
    12. in /Applications/XAMPP/xamppfiles/htdocs/craft3-test/vendor/craftcms/cms/src/services/Elements.php at line 469 – craft\services\Elements::_propagateElement(craft\elements\Entry, true, ['enabledByDefault' => '1', 'siteId' => '2'])
    13. in /Applications/XAMPP/xamppfiles/htdocs/craft3-test/vendor/craftcms/cms/src/controllers/EntriesController.php at line 539 – craft\services\Elements::saveElement(craft\elements\Entry)
    14. craft\controllers\EntriesController::actionSaveEntry()
    15. in /Applications/XAMPP/xamppfiles/htdocs/craft3-test/vendor/yiisoft/yii2/base/InlineAction.php at line 57 – call_user_func_array([craft\controllers\EntriesController, 'actionSaveEntry'], [])
    16. in /Applications/XAMPP/xamppfiles/htdocs/craft3-test/vendor/yiisoft/yii2/base/Controller.php at line 157 – yii\base\InlineAction::runWithParams([])
    17. in /Applications/XAMPP/xamppfiles/htdocs/craft3-test/vendor/craftcms/cms/src/web/Controller.php at line 74 – yii\base\Controller::runAction('save-entry', [])
    18. in /Applications/XAMPP/xamppfiles/htdocs/craft3-test/vendor/yiisoft/yii2/base/Module.php at line 528 – craft\web\Controller::runAction('save-entry', [])
    19. in /Applications/XAMPP/xamppfiles/htdocs/craft3-test/vendor/craftcms/cms/src/web/Application.php at line 237 – yii\base\Module::runAction('entries/save-entry', [])
    20. in /Applications/XAMPP/xamppfiles/htdocs/craft3-test/vendor/craftcms/cms/src/web/Application.php at line 445 – craft\web\Application::runAction('entries/save-entry', [])
    21. in /Applications/XAMPP/xamppfiles/htdocs/craft3-test/vendor/craftcms/cms/src/web/Application.php at line 221 – craft\web\Application::_processActionRequest(craft\web\Request)
    22. in /Applications/XAMPP/xamppfiles/htdocs/craft3-test/vendor/yiisoft/yii2/base/Application.php at line 386 – craft\web\Application::handleRequest(craft\web\Request)
    23. in /Applications/XAMPP/xamppfiles/htdocs/craft3-test/web/index.php at line 21 – yii\base\Application::run()
`

**Comment by davist11** [comment]
I'm actually having this same problem. We are on **Craft CMS 3.0.0-RC16.1** with 5 sites setup. When we upload a file on the front-end (a Commerce Order field), 5 copies of the same file are uploaded.

<img width="903" alt="screen shot 2018-03-28 at 5 53 12 pm" src="https://user-images.githubusercontent.com/199985/38062986-e4b05f98-32c4-11e8-995b-612edb3fdaee.png">

Happy to open a new issue or send DB, templates, or whatever information is helpful. Thanks!

**Comment by andris-sevcenko** [comment]
@davist11 can you provide more context? I'm using an Assets field on an entry locally with two sites and it's not duplicating for me.

**Comment by davist11** [comment]
Sure, here is a screen recording showing the entire process: https://drive.google.com/file/d/1BOtPPvyRgA-c2lyzXb5-HYSPZkrGRhLt/view?usp=sharing

The asset volume is an S3 volume. Let me know if you want me to send templates and DB over or whatever other details are helpful.

Craft CMS 3.0.0-RC17

**Comment by andris-sevcenko** [comment]
Yeah, I'll assume CP/sFTP access is not available since it looks to be a test machine, so templates and DB would help.

Just send them over to support@craftcms.com

**Comment by davist11** [comment]
DB and templates sent

**Comment by andris-sevcenko** [comment]
Resolved over email.
