### ISSUE TITLE
Configure a mailer/transport settings via config file

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#2554]
### Description
I'm trying to configure my mailer (in this case mailgun) via config file.

My best guess was to do it in `config/app.php`, but didn't seem to work:

```php
use Craft;

return [
    'components' => [
        'mailer' => function () {
            $settings = Craft::$app->getSystemSettings()->getEmailSettings();
            $settings->transportType = 'craft\mailgun\MailgunAdapter';
            $settings->transportSettings = [
                'domain' => 'mydomain.com',
                'apiKey' => 'my-api-key',
            ];

            return craft\helpers\MailerHelper::createMailer($settings);
        },
    ],
];
```

**Comment by brandonkelly** [comment]
That looks right, per [the docs](https://github.com/craftcms/docs/blob/v3/en/configuration.md#mailer-component). You’ve installed the Mailgun plugin right?

**Comment by timkelty** [comment]
Can't believe I missed that in the docs, but looks like i got it right…

Yep, have `craftcms/mailgun` installed, but doesn't appear to be working with the above `config/app.php`.

With that config, would you expect the settings to display in the CP Email Settings → Transport Type/Settings (they aren't).

I also verified sent some test emails and verified they _aren't_ coming through Mailgun, but the default Sendmail.

I've also tried just a `Craft::dd()` within the `mailer` function, and it doesn't seem to be getting called.

**Comment by janhenckens** [comment]
I'm trying to do the same thing, but using the Mandrill mail adapter, and am having similar issues. Dumping in `config/app.php`and the code doesn't get called.

**Comment by brandonkelly** [comment]
> With that config, would you expect the settings to display in the CP Email Settings → Transport Type/Settings (they aren't).

So I just tested locally and it works, but the Email settings page is unaffected. 

If you have Xdebug, try setting a breakpoint on line 93 of MailerHelper.php:

https://github.com/craftcms/cms/blob/28c26598af2022656a7d6558dc5d3dc5ceb82d1e/src/helpers/MailerHelper.php?utf8=%E2%9C%93#L93

Otherwise just add `throw $e` into that `catch` block, so the exception can surface.

**Comment by timkelty** [comment]
I'm debugging breakpoints in `craft\helpers\MailerHelper::createMailer` and still not seeing it working…

No exception is thrown.

For me, `craft\helpers\MailerHelper::createMailer` is only ever called by the adapter in the CP settings. The one `config/app.php` → `components` → `mailer` is never called. (I'm putting a breakpoint [right at the top of `createMailer`](https://github.com/craftcms/cms/blob/28c26598af2022656a7d6558dc5d3dc5ceb82d1e/src/helpers/MailerHelper.php?utf8=%E2%9C%93#L89) , and it only breaks once with the CP transport settings).

**Comment by brandonkelly** [comment]
The only time it should be called is when an email is getting prepped to be sent. Are you doing something that would trigger sending an email, like sending a user an activation email?

**Comment by timkelty** [comment]
Right, I'm testing it with the "Test" button on the `settings/email` screen.

**Comment by brandonkelly** [comment]
Yeah try it somewhere else though. That Test button will override the saved settings with whatever was submitted in the form, so it’s not a reliable place to test your custom config.

**Comment by timkelty** [comment]
oh, derp

**Comment by brandonkelly** [comment]
Working in other contexts?

**Comment by janhenckens** [comment]
Tried this with an activation email instead of a test (was doing the same) and that works!

Slightly confusing though that the different configuration isn't reflected in the CP.

**Comment by brandonkelly** [comment]
Agree, that part confused me as well at first 🙈

**Comment by brandonkelly** [comment]
OK, going forward, the Email Settings page will show this warning if app.php is defining a `mailer` component:

<img width="840" alt="screen shot 2018-03-23 at 5 44 15 am" src="https://user-images.githubusercontent.com/47792/37829703-4fb4cfd4-2e5d-11e8-8485-ebbf6a762fbd.png">

**Comment by Saboteur777** [comment]
In case anyone is looking for an example configuration for this: 

**config/app.php:** 
``` 
<?php
/**
 * Yii Application Config
 *
 * Edit this file at your own risk!
 *
 * The array returned by this file will get merged with
 * vendor/craftcms/cms/src/config/app/main.php and [web|console].php, when
 * Craft's bootstrap script is defining the configuration for the entire
 * application.
 *
 * You can define custom modules and system components, and even override the
 * built-in system components.
 */

return [
    'modules' => [
        'my-module' => \modules\Module::class,
    ],
    //'bootstrap' => ['my-module'],

    '*' => [
    ],

    'dev' => [
        'components' => [
            'mailer' => function() {
                // Get the stored email settings
                $settings = Craft::$app->systemSettings->getEmailSettings();

                // Override the transport adapter class
                $settings->transportType = craft\mailgun\MailgunAdapter::class;

                // Override the transport adapter settings
                $settings->transportSettings = [
                    'domain' => 'sandboxXXXXXXXXXXX.mailgun.org',
                    'apiKey' => 'key-XXXXXXXXXXX',
                ];

                return craft\helpers\MailerHelper::createMailer($settings);
            }
        ]
    ],

    'staging' => [
        'components' => [
            'mailer' => function() {
                // Get the stored email settings
                $settings = Craft::$app->systemSettings->getEmailSettings();

                // Override the transport adapter class
                $settings->transportType = craft\mailgun\MailgunAdapter::class;

                // Override the transport adapter settings
                $settings->transportSettings = [
                    'domain' => 'YYYYYYYYYYYY',
                    'apiKey' => 'key-YYYYYYYYYYYY',
                ];

                return craft\helpers\MailerHelper::createMailer($settings);
            }
        ]
    ],

    'production' => [
        'components' => [
            'mailer' => function() {
                // Get the stored email settings
                $settings = Craft::$app->systemSettings->getEmailSettings();

                // Override the transport adapter class
                $settings->transportType = craft\mailgun\MailgunAdapter::class;

                // Override the transport adapter settings
                $settings->transportSettings = [
                    'domain' => 'ZZZZZZZZZZZZ',
                    'apiKey' => 'key-ZZZZZZZZZZZZ',
                ];

                return craft\helpers\MailerHelper::createMailer($settings);
            }
        ]
    ],
];
```

**Comment by drifteaur** [comment]
Updated for Craft 3.1, thanks @Saboteur777 

config/app.php:

```php
<?php

use craft\helpers\App;

return [

    '*' => [
    ],

    'dev' => [
        'components' => [
            'mailer' => function() {
                // Get the stored email settings
                $settings = App::mailSettings();

                // Override the transport adapter class
                $settings->transportType = \craft\mail\transportadapters\Smtp::class;

                // Override the transport adapter settings
                $settings->transportSettings = [
                    'host' => 'localhost',
                    'port' => '1025',
                    'useAuthentication' => false,
                ];

                $config = App::mailerConfig($settings);
                return Craft::createObject($config);
            }
        ]
    ],
];

```
