### ISSUE TITLE
[Bug?] CP no longer works behind remote reverse proxy

### ISSUE THREAD

**Issue by mattcdavis1** [craftcms/cms#2558]
### Description
Some of our sites run through a CDN such as Akamai, Cloudflare, etc (the entire site, not just assets).  We typically create rules for certain url prefixes (admin/*) that instruct the CDN to not cache these requests but to just pass them through to the source server. 

In Craft 2 this worked fine as the siteUrl was respected even if the domain differed from the current site domain (different domain is needed as a source for the CDN server).  However, in Craft 3 the UrlHelper is forcing same domain as request in some cases and this is causing issues.  For example, site is `www.mysite.com` and CDN source is `prod.mysite.com`.  I want all URLs requested via `prod.mysite.com` to be prefixed with `www.mysite.com`

One workaround would be to just use the non-cdn-routed source domain (`prod.mysite.com`) for the CP area but i would prefer to keep the same domain across the board and also i'm concerned that this issue will pop up in other places where i may not have the flexibility to use the source domain.

### Steps to reproduce

1. Run the entire Craft site through a remote reverse proxy such as Cloudflare or Akamai.
2. Attempt to navigate the CP area while still staying on the same domain.

### Additional info

- Craft version: 3.0.0-RC14
- PHP version: 7.0.28
- Database driver & version: MySQL 5.6.38
- Plugins & versions:

**Comment by brandonkelly** [comment]
URL routing mostly works the same in Craft 3. What is your site URL?

**Comment by mattcdavis1** [comment]
I've set the siteUrl to https://www.mydomain.com which is set in an env file and stays the same regardless of the domain that the site is being viewed on.  The problem is that when the site is requested by the CDN via https://prod.mydomain.com the siteUrl is not respected and a number of assets are generated with an https://prod.mydomain.com instead of ignoring the host and using my siteUrl setting.

At least one problem is in the UrlHelper on line 406:
```php
// If we must show the script name, then just start with the script URL,
// regardless of whether this is a CP or site request, as we can't assume
// that index.php lives within the base URL anymore.
if ($showScriptName) {
    if ($request->getIsConsoleRequest()) {
        // No way to know for sure, so just guess
        $baseUrl = '/'.$request->getScriptFilename();
    } else {
        $baseUrl = $request->getHostInfo().$request->getScriptUrl();
    }
} else if ($cpUrl) {
```

You can see above where $baseUrl is being set based on the hostname or script file name rather than using the $baseUrl from config/general.

**Comment by brandonkelly** [comment]
Sorry, asset URLs don't factor in the site URL, just their volume's base URL. So that’s where to look. What is the volume's base URL set to?

**Comment by mattcdavis1** [comment]
@brandonkelly - the volume's base URL isn't relevant here.  The issue is with admin pages not user uploaded content. I'm not talking about CDN usage for assets i'm talking about CDN usage for website + admin area.  The entire domain (front and backend) is reverse proxied through a CDN.  For the admin area requests are just passed through rather than cached but the base domain still differs even in pass through scenarios.

So one problem, for example, is that on the admin/login page some assets load from a different domain (prod.mydomain.com rather than www.mydomain.com) due to code shown above which causes cross site script security issues and the page doesn't function

**Comment by brandonkelly** [comment]
Ahhhh, understand now. I missed the “in some cases” bit. Looks like the issue is limited to action URLs, which must include the script name. What changed in Craft 3 (semi-recently) is that Craft can no longer assume the location of `index.php` based on the site’s base URL, so that UrlHelper logic changed to just going with what yii\web\Request said the host info/script URL were.

Just fixed – now Craft will construct these URLs by combining the host info from the current site’s base URL, and the script URI from yii\web\Request.

**Comment by mattcdavis1** [comment]
great - thanks!
