### ISSUE TITLE
InvalidArgumentException using checkPath()

### ISSUE THREAD

**Issue by steveooo9** [craftcms/cms#2563]
### Description

I get an fatal error and the log says: ```error
Category  exception.Twig_Error_Runtime
Message Imagine\Exception\InvalidArgumentException: File https://test.com/assets/foobar.jpg does not exist. in /var/www/test/htdocs/craft/app/vendor/pixelandtonic/imagine/lib/Imagine/Image/AbstractImagine.php:72```

### Steps to reproduce

1. Create a function like `return craft()->images->getExifData($image->getUrl());`
2. Use that functing via TwigExtension or Variable in template
3. Get the error
4. We found out that the issue is with `fopen()` at using urls. There might be some issues with servers who have `allow_url_fopen` disabled.
5. We have no clue what the right thing should be. After short researching here, there might be some behavior Craft should check on the server? https://stackoverflow.com/a/127562/5058154

### Additional info

- Craft version: Craft CMS 2.6.3012
- PHP version: 7.1
- Database driver & version:
- Plugins & versions:

**Comment by andris-sevcenko** [comment]
That method is not intended to work with URLs but rather with files on the server (https://craftcms.com/classreference/services/ImagesService#getExifData-detail)

**Comment by steveooo9** [comment]
@andris-sevcenko Well, the issue was that we had `.htpasswd` in our environment and somewhere a `checkPath()` was using `@fopen($path, 'r')` to get this file, so we fixed it by writing a method that translates things like this:

From: `http://www.test.com/assets/monkey.jpg` to `http://htUser:htPass@www.test.com/assets/monkey.jpg` and it work's now.

Not pretty, but maybe useful some you or someone else.

`fopen` creates a own stream which needs authentification when a `htpasswd` is in place.

**Comment by andris-sevcenko** [comment]
Well, to each his own. I'm just saying that the method is not intended to work for URLs, so whatever issues you encounter in this scenario might be harder to resolve :)
