### ISSUE TITLE
FR: Asset uploads in Table field

### ISSUE THREAD

**Issue by theskyfloor** [craftcms/cms#2564]
### Description

Sometimes I want to store some extra meta data on an image or image gallery as a set of subfields on a Matrix per entry and not per asset... adding the ability to upload images to a table row would solve this for me without needing to resort to a 3rd party plug-in.

### Steps to reproduce

1. Create a table field
2. You can't make a column asset upload

### Additional info

- Craft version: Craft 3 RC14
- PHP version: 7.2

**Comment by brandonkelly** [comment]
This FR is covered by #811. Something like it is planned for 3.x ;)

**Comment by theskyfloor** [comment]
Sorry I didn't check for dupes, my bad!
