### ISSUE TITLE
@webroot doesn't return '/web' on console

### ISSUE THREAD

**Issue by ostark** [craftcms/cms#2566]
Simply setting the @webroot alias to `dirname($this->getScriptFile()))` doesn't make much sense as the cli is not executed in `/web`. But the value of the alias should be consistent, otherwise we can not rely on that.

As guessing or detecting the actual webroot from the console is not easy, a configuration option might be useful. This way we can overwrite it, if we don't use the default `web` folder.

### Additional info

- Craft version: 3.0.0-RC15

**Comment by TUSAB-web** [comment]
Another common name for a webroot would be wwwroot/ if you wanted to add it as something craft checks for.
