### ISSUE TITLE
Craft is not permitted to test edition upgrades from this server

### ISSUE THREAD

**Issue by tjdraper** [craftcms/cms#2569]
### Description

I'm having an issue trying to switch to Craft Pro on my plugin dev test domain anselcraft.test. According The network tab reveals the error: "Craft is not permitted to test edition upgrades from this server"

### Steps to reproduce

1. Install craft on the domain "anselcraft.test"
2. Attempt to try out the pro edition

### Additional info

- Craft version: 3.0.0-RC15
- PHP version: 7.1.3
- Database driver & version: MySQL 5.5.5

![y-tho](https://user-images.githubusercontent.com/3803475/37377262-d5b7532c-26f6-11e8-86af-1277d0a61f97.png)

**Comment by kbergha** [comment]
Do you also get a "Unknown error" in the GUI like this (it disappears after a little while):

![untitled](https://user-images.githubusercontent.com/4321846/37398992-987e959e-2780-11e8-87e8-7d38892608d5.png)

If so, I may have had the same issue as you when I was on RC8. 

The actual JSON-response was ` {error: "Craft is not permitted to test edition upgrades from this server"}` - just like your error.

For me, the upgrade option started working again after clearing all cache under Utilities -> Clear cache.

**Comment by brandonkelly** [comment]
Just tested this and it’s working fine on my end. Strange that it would show the Test buttons if it thought you weren't on a dev domain.

When exactly do you see that error show up? When you click the Test button?

By the way, you can force-switch it to Craft Pro from your `craft_info` table. Just change the `edition` column to `2`.

**Comment by angrybrad** [comment]
@kbergha what was the domain you were testing on when you got that error? @tjdraper does clearing Craft's caches help?

**Comment by kbergha** [comment]
The domain was http://magasin.test

**Comment by tjdraper** [comment]
@angrybrad Clearing caches did not help. However the first time I clicked on the edition in the sidebar footer, there was no "try for free" button. Refreshing brought the button(s) back but same issue when clicking the button.

**Comment by angrybrad** [comment]
@tjdraper looking through our logs, I can see calls coming in from anselcraft.test and it shows we're treating it as both a "non-public" domain and as a "testable" domain in the response.  You're still getting the exact same "Craft is not permitted..." response back as in the original?

**Comment by tjdraper** [comment]
@angrybrad Yep. Same thing.

![craft-try-pro-error-1](https://user-images.githubusercontent.com/3803475/37528055-9a602b52-2901-11e8-8ee9-34b5fb197562.png)

![craft-try-pro-error-2](https://user-images.githubusercontent.com/3803475/37528069-a0ef49bc-2901-11e8-9039-56febea04359.png)

**Comment by brandonkelly** [comment]
Hey TJ,

Can you try this again on the latest release please?

**Comment by tjdraper** [comment]
For a while I thought I wasn't going to be able to even get the Try for Free button because it wasn't showing up. But then, randomly one time when I clicked the edition in the bottom left of the CP the Try for Free button did show up. But clicking the button produces the same results as before. :-(

3.0.0-RC17.1.

![craft-try-error](https://user-images.githubusercontent.com/3803475/38165787-aa6d64cc-34de-11e8-88b7-e23463a8ed68.png)

**Comment by angrybrad** [comment]
Curious if this is still an issue for you on the latest Craft 3.0.7 @tjdraper?

**Comment by tjdraper** [comment]
@angrybrad Seems to be working correctly now.

**Comment by angrybrad** [comment]
Thanks, @tjdraper. Going to go ahead and close this, but let us know if it pops up again.
