### ISSUE TITLE
FR: Default language preference for new users

### ISSUE THREAD

**Issue by Kashkin** [craftcms/cms#2570]
### Description

New user accounts are created with empty preferences. User preferences now control date formatting rather than a global site preferences. For users who prefer dd.mm.yyyy format, they have to individually update their preferences.

We have a site with 50+ users, and would greatly benefit from the ability to set a default Language Preference for new users. This could live with the other global settings at `/admin/settings/users/settings`.

**Comment by brandonkelly** [comment]
There already is a config setting for this – [defaultCpLanguage](https://docs.craftcms.com/api/v3/craft-config-generalconfig.html#$defaultCpLanguage-detail) ;)
