### ISSUE TITLE
Element validation UI not showing in RC15

### ISSUE THREAD

**Issue by rynpsc** [craftcms/cms#2572]
### Description

The UI for element validation (error messages and styling) is not showing in RC15, elements are still validated.

### Steps to reproduce

1. Create a new text field
2. Assign to section and make required
3. Save section with text field blank

### Additional info

- Craft version: Craft Pro 3.0.0-RC15
- PHP version: 7.1.14
- Database driver & version: MySQL 5.7.21
- Plugins & versions: NA

**Comment by brandonkelly** [comment]
Thanks!
