### ISSUE TITLE
Check for valid locale when using command line installer

### ISSUE THREAD

**Issue by nilsenpaul** [craftcms/cms#2573]
### Description
When using the command line installer, I was able to enter `NL` as the locale, while it should have been `nl`. I think this should be validated against a list of known locales.

### Steps to reproduce

1. Install Craft using the command line installer
2. Use `NL` or `FR` as the locale

### Additional info

- Craft version: 3.0.0-RC15
- PHP version: 7.1.14
- Database driver & version: MySQL 5.7.18
- Plugins & versions: none

**Comment by brandonkelly** [comment]
Fixed, thanks!
