### ISSUE TITLE
Empty user language when updating from Craft 2

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/cms#2574]
### Description

After updating from Craft 2, the 'Language' field located on the 'My Account' section is set to 'Deutsch' by default.

It looks like this is because the language values in Craft 3 differ to those in 2, in my case what was `en_gb` in Craft 2 is now `en-GB` in 3.

<img width="285" alt="image" src="https://user-images.githubusercontent.com/24975058/37398396-49e6e17a-2776-11e8-9c1e-c18fe1c745f5.png">

### Steps to reproduce

1. Upgrade from Craft 2 to 3
2. Visit the 'My Account' section in the CP

### Additional info

- Craft version: 3.0.0-RC15
- PHP version: 7.2.3
- Database driver & version: MySQL

**Comment by brandonkelly** [comment]
Thanks!
