### ISSUE TITLE
Fields' isEmpty() method has been deprecated

### ISSUE THREAD

**Issue by Rias500** [craftcms/cms#2575]
### Description

![afbeelding](https://user-images.githubusercontent.com/3626559/37402767-0b2c25f0-278d-11e8-948a-07fde6e0e5f8.png)

Stacktrace:

![afbeelding](https://user-images.githubusercontent.com/3626559/37402834-3980c956-278d-11e8-9ef9-642dd026093b.png)

### Steps to reproduce

1. Save an entry

### Additional info

- Craft version: 3 RC-15
- PHP version: 7.1

**Comment by brandonkelly** [comment]
This is actually due to the Redactor plugin. Fixed for its next release, but you can get the fix ahead of time by changing your `craftcms/redactor` version requirement to `"dev-v1 as 1.0.1"` in composer.json, and running `composer update`.
