### ISSUE TITLE
Unable to upload file XML into Assets

### ISSUE THREAD

**Issue by babau67** [craftcms/cms#2578]
### Description
I'm not able to upload file with extension .xml either directly into Asset folders or via an Asset fields.

### Steps to reproduce

1. Go into the sidebar menu
2. Click to Assets
3. Upload the file mydoc.xml

OR

1. Open an entry with an Asset field
2. Upload the file mydoc.xml

the message from the system is: 

`Upload failed. The error message was: “Failed to save the Asset:“xml” is not an allowed file extension.”
`
### Additional info

- Craft version: Craft CMS 3.0.0-RC15
- PHP version: 7.0.25
- Database driver & version: MySQL 5.7.21
- Plugins & versions: Redactor 1.0.1 - CP Field Inspect 1.0.2

**Comment by angrybrad** [comment]
You'll need to add `'xml'` to [this config setting](https://craftcms.com/docs/config-settings#extraAllowedFileExtensions) as it's not in the [default list](https://craftcms.com/docs/config-settings#allowedFileExtensions). :)

**Comment by darylknight** [comment]
Updated link for anyone who lands here from Google: https://craftcms.com/docs/3.x/config/config-settings.html#extraallowedfileextensions
