### ISSUE TITLE
Publishing a draft does not create an entry version

### ISSUE THREAD

**Issue by samstevens** [craftcms/cms#2579]
### Description

We've noticed that if you have entry versioning enabled and create then publish a draft, this only updates the content of the "Current" version and does not create a version of the previous content.

Eg: if we have - 
Current
Version 2
Version 1

Creating a draft of "Current" would appear in the version list as a new draft. If you publish this draft, you would expect to end up with:

Current (newly published draft)
Version 3 (old version of current)
Version 2
Version 1

However, this result is:

Current (with the published draft content)
Version 2
Version 1

### Steps to reproduce

1. Enable versioning
2. Create an entry
3. Save the entry to create a version
4. Create a draft.
5. Publish the draft.
6. Look at the versions list to see there is now only 2 items - current and the first version (there should be 3 items).

### Additional info

- Craft version:Craft Pro 3.0.0-RC15
- PHP version: 7.1.15
- Database driver & version: MySQL 5.7.21
- Plugins & versions: Lots

Thanks :) 👍

**Comment by brandonkelly** [comment]
Thanks for reporting!
