### ISSUE TITLE
Base URL issue when running as a headless CMS with RC-15, preventing log in.

### ISSUE THREAD

**Issue by davidrapson** [craftcms/cms#2581]
### Description

We use Craft as a headless CMS which means that we use a different domain for Craft than we do for the public facing website. Prior to RC-15 we were able to handle this by setting the site URL to be the url of the public facing website (allowing preview links to work) but serving Craft over a different URL for editing.

For example:

- Craft admin: cms.internal.com
- Public website: example.com

With the RC-15 update Craft is using the site URL for internal links meaning that internal admin links and the login form use the site URL rather than the current host. In our case this prevents us from logging in or accessing any admin sections.

Educated guess is that is is something to do with this change: https://github.com/craftcms/cms/commit/e4d3059e130bcf67e6b386ce554a6b96102f2969

I've tried setting a custom `baseCpUrl` which looks like it resolves some of the issue, but even with that set the post action of the login form goes to the site URL which fails as it's cross domain.

### Additional info

- Craft version: RC-15
- PHP version:  7.1.11

**Comment by davidrapson** [comment]
Addendum to this: Looks like I'm describing the opposite problem to this https://github.com/craftcms/cms/issues/2558

**Comment by davidrapson** [comment]
Reverse engineered this a little bit and found the problem. Setting a 

Viewing the source of `/admin/login` shows the problem. With the site domain set to `www.example.com` and the control panel domain set to `cms.example.com` you get the following:

``` js
window.Craft = {
  baseUrl: "https\x3A\x2F\x2Fcms.example.com\x2Fadmin",
  baseCpUrl: "https\x3A\x2F\x2Fcms.example.com\x2Fadmin",
  baseSiteUrl: "https\x3A\x2F\x2Fwww.example.com\x2F",
  actionUrl: "https\x3A\x2F\x2Fwww.example.com\x2Findex.php\x3Fp\x3Dadmin\x2Factions",
…
```

Note that `actionUrl` is using `www.` rather than `cms.`, which prevents login / form action from working.

**Comment by brandonkelly** [comment]
Thanks for reporting that, and investigating the culprit! Just fixed for the next release. You can get the update ahead of time by changing your `craftcms/cms` version requirement in composer.json to `"dev-develop as 3.0.0-RC99"`, and then run `composer update`.

**Comment by brandonkelly** [comment]
@davidrapson Cool, let me know how it works for you!

**Comment by davidrapson** [comment]
Can confirm that this worked for me.
