### ISSUE TITLE
Standard Craft Search doesn't work for anything other than headlines/titles

### ISSUE THREAD

**Issue by martinhellwagner** [craftcms/cms#2582]
### Description

I've been implementing a basic search on our Craft CMS project (basically straight from the documentation):
```
{% set query = craft.app.request.getParam('q') %}
{% set data = craft.entries.search(query).orderBy('score') %}
```

However, the search doesn't return any results for queries that are **not** in a headline/title. Anything in a `<p>` tag is ignored by the search, for example. I've also tried using the search without `orderBy('score')`, but to no avail. This snippet doesn't work either:
```
{% set query = craft.request.getParam('q') %}
{% set data = craft.entries({
  search: query
}) %}
```

Is it possible that there is a bug in the Craft search?

### Steps to reproduce

1. Try searching for anything that is not in a headline/title

### Additional info

- Craft version: Craft Pro 3.0.0-RC15
- PHP version: 7.1.15
- Database driver & version: MySQL 5.7.21
- Plugins & versions: _None relevant for search_

**Comment by angrybrad** [comment]
Can you provide some steps to reproduce what you're seeing?

Craft indexes textual custom field keywords (including Rich Text, which I'm assuming is what you're using) in the `craft_searchindex` table by elementId, fieldId attribute and locale.  The keywords go through a normalization process stripping out HTML tags, punctuation, etc.

Are you able to find whatever you're querying for in that table?

Maybe you just need to rebuild your search indexes?

**Comment by martinhellwagner** [comment]
Sorry for the late reply! I've just updated the search indexes in the admin panel, and that seems to be solving the problem. Thanks for the help! 👍
