### ISSUE TITLE
Missing translations in CP sidebar user popup

### ISSUE THREAD

**Issue by ockam** [craftcms/cms#2583]
### Description

in the user popup menu (at the top of the CP sidebar) the _View site_ and _My account_ link label are hardcoded, i.e. not going through translate filter.

See /src/templates/_layouts/cp.html at lines 104 and 108

### Steps to reproduce

1. set your user locale to any locale other than en-US
2. click on menu

### Additional info

- Craft version: 3.0.0 RC15

**Comment by brandonkelly** [comment]
Thanks for reporting!
