### ISSUE TITLE
Colour field preview not showing on Entry Index

### ISSUE THREAD

**Issue by alexjcollins** [craftcms/cms#2587]
### Description

When showing the colour field on an entry index, the colour preview isn't showing properly.

![colour-preview](https://user-images.githubusercontent.com/12031196/37508318-76aa5834-28ea-11e8-9405-40084f1b8b4b.png)

### Steps to reproduce

1. Create a colour field
2. Attach it to an entry type
3. Create an entry with a colour
4. Show that field on the entry index

### Additional info

- Craft version: 3.0.0-RC15

**Comment by brandonkelly** [comment]
Thanks for reporting!
