### ISSUE TITLE
Colour Field type default value validation

### ISSUE THREAD

**Issue by alexjcollins** [craftcms/cms#2588]
### Description

It appears as though you cannot set a default colour that contains letters. I am able to save #000000 for example, but not #FFFFFF. I can however save whatever valid hex I like in the entry where the field is being used.

### Steps to reproduce

1. Create a colour field
2. Set a default hex that contains letters
3. Try to save the field

### Additional info

- Craft version: 3.0.0-RC15

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. What happens when you try to save the field? Do you get an error of some sort?

**Comment by alexjcollins** [comment]
@brandonkelly Yeah, I get `Default Color isn't a valid vex color value`.

Here's a quick screen grab : https://youtu.be/8cOS6cvjMpw

**Comment by brandonkelly** [comment]
@alexjcollins Thanks, turns out the issue only affected uppercase letters.

In addition to that, the Default Color setting was not normalizing 3-character colors (e.g. `#abc` → `#aabbcc`), like Color field inputs do.
