### ISSUE TITLE
Add timezone as user preference per site instead being a General setting

### ISSUE THREAD

**Issue by bzin** [craftcms/cms#2589]
### Description

Having multiple sites for different countries and languages gives the need of having different timezone for the site itself.

This should/could be added as a user preference instead of having only one timezone per installation. When this would not be defined, timezone could drop to the default timezone set. 

However, this does only solve the problem when the country has only a time zone. Australia, United States and India do have multiple time zones. 

Maybe could also be an idea to include a site preference where you associate your site with a specific country. Therefore it would "automatically" associate multiple time zones to the site id.

**Comment by benjaminkohl** [comment]
This is a feature that has come up for us numerous times over the years for content administrators (CP access users) that live in different timezones than the default timezone and they want to see the date/time field values in the CP adjusted to match where they live.
