### ISSUE TITLE
'Checkboxes' translates to 'Tickboxes' for en-GB

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/cms#2590]
### Description

The word 'checkboxes' and it's variations are translated to 'tickboxes' for en-GB when they're generally referred to as 'checkboxes' in the UK, which can be a bit annoying when creating field types considering 'checkbox' is the official input type.

https://github.com/craftcms/cms/blob/08fb899568b7c44ab9c95b900c5025093abbf5dc/src/translations/en-GB/app.php#L180#L181#L182

### Additional info

- Craft version: 3.0.0-RC15

**Comment by brandonkelly** [comment]
Thanks for letting us know!

**Comment by carlcs** [comment]
Hm… it looks like https://github.com/craftcms/cms/commit/92b0ac6385f9689054fc6d7ee859a3f9eb6993c9 reverted this again.

**Comment by angrybrad** [comment]
Brought back in https://github.com/craftcms/cms/commit/aead133cb59dddef8e670d0651996a5d528615b8
