### ISSUE TITLE
Option to hook into parseRefs()

### ISSUE THREAD

**Issue by steveooo9** [craftcms/cms#2592]
### Description

We are using `craft()->elements->parseRefs()` pretty much everywhere and it's great. But we have an issue: When parserefs converts a reference tag that is of type `Date` (which is allowed in parseRefs()), how can I format that date? Would be great to either change it's default method (change somewhat the toString() of Date model?) or let it give some kind of `{entry:42:startDate|date('d.m.Y')}` Any ideas?

Another option would be for you to add a hook so we could add own logic to parseRefs().

Craft 2

**Comment by steveooo9** [comment]
@brandonkelly Would be great if there is a way to hook into this before converting the reference tag but after we have a element. So I could check if the reference tag is of type `Date`, so I could define my own date return. Currently it defaults to YYYY-MM-DD which isn't really useful for people living outside the US and having other date standards.

Do you plan on implementing this in the near future?

**Comment by brandonkelly** [comment]
@steveooo9 `YYYY-MM-DD` is the ISO 8601 standard; not US specific. So you could actually apply the `|date` filter to it to change its formatting:

```twig
{{ "{entry:42:startDate}"|parseRefs|date('medium') }}
```

(though that will only help you if you have a string that is nothing but the reference tag, at which point the reference tag isn’t actually helping you at all.)

If you’re using Craft 3, another route you could take is to add a new function to your entries that could be accessed from `parseRefs`. Here’s how to do that:

1. Create a [Behavior](https://www.yiiframework.com/doc/guide/2.0/en/concept-behaviors) class, with this function in it:

  ```php
  public function getNiceStartDate(): string
  {
      return $this->owner->startDate->format('d.m.Y');
  }
  ```

2. From your [Module class](https://github.com/craftcms/craft/blob/master/modules/Module.php)’s `init()` method, use the [EVENT_DEFINE_BEHAVIORS](https://docs.craftcms.com/api/v3/craft-base-component.html#EVENT_DEFINE_BEHAVIORS-detail) event to register your behavior with all entries (or you could limit to just a single section):

  ```php
  use yii\base\Event;
  use craft\elements\Entry;
  use craft\events\DefineBehaviorsEvent;

  Event::on(Entry::class, Entry::EVENT_DEFINE_BEHAVIORS, function(DefineBehaviorsEvent $e) {
      $e->behaviors[] = MyBehavior::class;
  });
  ```

3. Update your reference tags to point to your new function:

  ```twig
  {entry:42:niceStartDate}
  ```

**Comment by brandonkelly** [comment]
We’re doing a form of this in Craftnet, albeit for Users instead of entries.

Here’s our UserBehavior class: https://github.com/pixelandtonic/craftnet/blob/develop/src/developers/UserBehavior.php

And here’s where we register it: https://github.com/pixelandtonic/craftnet/blob/develop/src/Module.php#L71-L73

With that in place, all users in that system have custom `getDeveloperName()` methods, etc.., which technically we could use in reference tags if we wanted, via `{user:X:developerName}`.

**Comment by steveooo9** [comment]
@brandonkelly Thanks for this very good answer (mostly for Craft 3)! We are still using Craft 2 a lot and will for some time, so we need a solution for Craft 2. Is there a simple hook for changing the value of a parseRef possible?

**Comment by brandonkelly** [comment]
sorry no. And realistically even if we do ever implement this feature, it would be Craft 3 only.

**Comment by steveooo9** [comment]
@brandonkelly I found out that when using a Date with a Time, only Y-m-d is returned instead of some Y-m-d H:i

Is this something that could get added?

**Comment by brandonkelly** [comment]
Changing the default string output for DateTime objects would be a breaking change, so no we can’t do that, sorry.

**Comment by steveooo9** [comment]
Hmm...

**Comment by steveooo9** [comment]
@brandonkelly Could you give a simple hook for DateTimes to overwrite its __toString() method? This wouldn't break things and gives the options to declare other outputs for DateTimes. Because it doesn't make sense to have a DateTime with Time but only output the Date. There's 50% missing here and this is important. So a hook would be the easiest way to to...

**Comment by brandonkelly** [comment]
Considering that the entire `Craft\DateTime` class has been removed in Craft 3, adding more functionality to it in Craft 2 feels awkward.

If you _must_ solve this for Craft 2, I’d say the easiest thing to do would be to create a plugin that A) defines its own `DateTime` class that extends `Craft\DateTime` with a custom `__toString()` method; and B) provides a custom Date/Time field type, that extends Craft’s `DateFieldType` class, and overrides the `prepValue()` method to return an instance of the custom `DateTime` class instead.

```php
class MyPlugin_DateTime extends DateTime
{
    public function __toString()
    {
        return $this->format(static::ATOM);
    }
}
```

```php
class MyPlugin_DateFieldType extends DateFieldType
{
    public function prepValue($value)
    {
        if (!$value)
        {
            return null;
        }

        if (!class_exists(MyPlugin_DateTime::class))
        {
            require (dirname(__DIR__).'/MyPlugin_DateTime.php';
        }

        return new MyPlugin_DateTime('@'.$value->getTimestamp(), new \DateTimeZone(craft()->timezone));
    }
}
```

**Comment by brandonkelly** [comment]
> Will there be some database problems (corruption etc.) if I switch the field type on existing fields or should it be cool because they are pretty similar?

As long as the field stores data in the same way, you should be able to just change the Field Type setting w/out any bad consequences.

> And thanks for the code! I didn't test it, but it seems like a solution that's not good, but okay for the use case!

“not good, but okay” is what I strive for!

**Comment by steveooo9** [comment]
@brandonkelly Okay, thanks! 👍 👍
