### ISSUE TITLE
Debug toolbar does not display results based on cache tag usage with cache enabled.

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#2593]
### Description
Craft 2 had **Profiling Summary Report** setting when devMode was enabled that allowed me to test optimal cache tag placement.

**Example:**
```
Time:   0.33632s
Memory: 21,914Kb
Total Queries: 44
```

Craft 3 has replaced this with the debug toolbar, but it doesn't seem to behave the same way when viewing cached pages, making it difficult to test cache benefits. What I expect to see is a reduced number of queries and render time when I place a cache tag around a complex block of code.

### Steps to reproduce

1. Add generic cache tag around entire site.
2. View a page with debug toolbar visible. Note Time/DB queries.
3. Compare the same page with cache disabled.

### Additional info

- Craft version: 3.0.0-RC15
- PHP version: 7.1.13
- Database driver & version: MySQL 5.5.5

**Comment by khalwat** [comment]
I'm seeing this on RC15 as well. I wrapped my entire `layout.twig` in a `{% cache %}` / `{% endcache %}` tag pair just to test it... then I toggled `enableTemplateCaching` in my `config/general.php`:

![phpstormscreensnapz061](https://user-images.githubusercontent.com/7570798/37544194-8c54a734-293a-11e8-9a08-a621ad8ccec6.png)
^ `'enableTemplateCaching' => false,`

![google chromescreensnapz1085](https://user-images.githubusercontent.com/7570798/37544212-97029fec-293a-11e8-8533-736af1438add.png)
^ `'enableTemplateCaching' => true,`

So in my case, I’m actually getting _more_ queries with `templateCaching` on… presumably from the db calls to track the element queries, etc. in the cache.

But yeah unless something has changed that I don’t understand, I think this is not working as I’d expect. It's almost like the `{% cache %}` tag is doing nothing.

**Comment by khalwat** [comment]
I checked the compiled template:

```
        if (!$ignoreCache1) {
            $cacheKey1 = "uMaa0zytOfoHr3GEo7mi8soylTvVWmqLoh6e";
            $cacheBody1 = $cacheService->getTemplateCache($cacheKey1, false);
        } else {
```
...and the cache key does correspond to the correct key in the db... and I verified that it's returning the right cached HTML in `$cacheBody1`

So now I'm going to guess that it's some kind of strange interaction with the Yii2 Debug Toolbar. Because from what I can tell, the compiled template is doing what it should be doing: grabbing the cached HTML from the db, and displaying it.

**Comment by brandonkelly** [comment]
Working on my end.

I created a `test.html` template on a stock [Happy Lager](https://github.com/pixelandtonic/HappyLager) site with this in it:

```twig
{% cache %}

    {% set entries = craft.entries.section('work').all() %}
    
    {% for entry in entries %}
        {% do entry.featuredThumb.first() %}
    {% endfor %}
    
{% endcache %}
```

First request (cold cache): 41 queries

Second request (warm cache): 20 queries

Most likely this is just an issue with your template – the element queries are getting triggered outside of the `{% cache %}` tags or something. If you can’t figure it out, feel free to send a DB backup and your template(s) to support@craftcms.com and we can try to help.
