### ISSUE TITLE
Queue console commands have gone missing in RC15

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#2594]
`./craft queue` used to be a console command available via the CLI; but it appears to be gone in RC15.

```
vagrant@homestead ~/sites/nystudio107 (develop) $ ./craft queue
Unknown command: queue
```

This is a bit unfortunate, as @ostark 's [Async Queue](https://github.com/ostark/craft-async-queue) plugin depends on it being there.

The disappearance is also somewhat mystifying; I couldn't find anything related to it in the Craft CMS 3, Yii2, or Yii2 Queue logs.

**Comment by brandonkelly** [comment]
doh.
