### ISSUE TITLE
Add option to exclude fields from front-end search results.

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#2600]
We're using the [Guest Entries](https://github.com/craftcms/guest-entries) plugin on a site and noticed that the email addresses that we're collecting are searchable on the front-end when using the standard search query.

We don't want people being able to glean info that should be private through searching.

Having a way to mark a field as unsearchable or an option to exclude that field in the search would be ideal here.

**Comment by Harry-Harrison** [comment]
Could do with this for pretty much the exact same reason. We've got an "Editors notes" field that could contain potentially _sensitive_ information that shouldn't be search-able.

**Comment by brandonkelly** [comment]
We’ve added this for Craft 3.1 :)

**Comment by jsunsawyer** [comment]
@brandonkelly I'm having trouble finding a reference to this in the docs or 3.1 changelog. How does one go about implementing this?

**Comment by hiasl** [comment]
@brandonkelly can this feature be used with normal entries as well? 

background: we have an entries field to select related content but I do not want the main entry to be found when the keyword appears in the selected related entries... thanks

**Comment by brandonkelly** [comment]
@hiasl No but you could exclude the entry you don’t want using the [id](https://docs.craftcms.com/v3/dev/element-queries/entry-queries.html#id) entry query param.

```twig
{% set entries = craft.entries()
    .search('your search query')
    .id(['not', mainEntry.id])
    .all() %}
