### ISSUE TITLE
order: sortOrder throw sql error on Craft CMS 3 RC15

### ISSUE THREAD

**Issue by MDXDave** [craftcms/cms#2601]
### Description
The [following code](https://craftcms.com/docs/assets-fields) has worked on Craft Cms 2.x:

```twig
{% set assets = craft.assets({
    relatedTo: { sourceElement: entry, field: "assetsFieldHandle" },
    order:     "sortOrder",
    limit:     null
}) %}
```

In Craft Cms 3 RC15 it throws an sql error:

> INTERNER SERVERFEHLER
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sortOrder' in 'order clause' The SQL being executed was: SELECT elements.id, elements.fieldLayoutId, elements.uid, elements.enabled, elements.archived, elements.dateCreated, elements.dateUpdated, elements_sites.slug, elements_sites.uri, elements_sites.enabled AS enabledForSite, assets.volumeId, assets.folderId, assets.filename, assets.kind, assets.width, assets.height, assets.size, assets.focalPoint, assets.dateModified, volumeFolders.path AS folderPath, content.id AS contentId, content.title, content.field_addressFooter, content.field_addressHeader, content.field_description, content.field_cdnUrl, content.field_hintHeader, content.field_infoHeader, content.field_body, content.field_contactHeader, content.field_lizenzLink, content.field_lizenz, content.field_menu, content.field_rechteinhaber, content.field_order, content.field_phoneHeader, content.field_weatherHeader FROM (SELECT elements.id AS elementsId, elements_sites.id AS elementsSitesId, content.id AS contentId FROM elements elements INNER JOIN assets assets ON assets.id = elements.id INNER JOIN elements_sites elements_sites ON elements_sites.elementId = elements.id INNER JOIN content content ON content.elementId = elements.id WHERE (elements_sites.siteId='1') AND (content.siteId='1') AND (elements.archived=FALSE) AND (elements_sites.enabled=TRUE) AND (elements.id IN (SELECT sources1.targetId FROM relations sources1 WHERE (sources1.sourceId='29') AND (sources1.fieldId='3'))) ORDER BY sortOrder) subquery INNER JOIN assets assets ON assets.id = subquery.elementsId INNER JOIN volumefolders volumeFolders ON assets.folderId = volumeFolders.id INNER JOIN elements elements ON elements.id = subquery.elementsId INNER JOIN elements_sites elements_sites ON elements_sites.id = subquery.elementsSitesId INNER JOIN content content ON content.id = subquery.contentId ORDER BY sortOrder

Has something changed between Craft cms 2 and 3? Or is it an unexpected bahvior?

**Comment by shuckster** [comment]
"sortOrder" should point to the field you wish to sort by, and optionally, the direction:
```
    order:     "filename asc",
```
Also, I believe `order` is now deprecated in favour of `orderBy` in v3.

**Comment by MDXDave** [comment]
But i want to have the same order as i defined in the backend:

![image](https://user-images.githubusercontent.com/6099976/37661066-31ecf89c-2c54-11e8-8c8f-350631297a37.png)

How to achieve this?

**Comment by shuckster** [comment]
Apparently, the default order option is [postDate desc](https://craftcms.com/docs/templating/craft.entries#order), so perhaps simply exclude the order option.

**Comment by MDXDave** [comment]
Without using the order/orderBy param, the order is complelty wrong
![image](https://user-images.githubusercontent.com/6099976/37662938-753e86b6-2c58-11e8-8af4-02f5241c78c0.png)

**Comment by shuckster** [comment]
Looks like [fixedOrder](https://straightupcraft.com/articles/cheat-sheet-craft.entries) is the parameter to try.

**Comment by shuckster** [comment]
After more digging, perhaps this: [order('lft')](https://craftcms.stackexchange.com/questions/3011/output-children-of-a-structure-section-in-reverse-order/3013#3013)

**Comment by MDXDave** [comment]
_Unknown column 'lft'_

As you can see, the param _sortOrder_ should be right, but i can not access them, because it will not read out from the database. There should be something like ``sources1.*`` or ``sources1.sortOrder``

``SELECT sources1.targetId FROM relations source1``

![image](https://user-images.githubusercontent.com/6099976/37664529-cd092d58-2c5b-11e8-96c1-c0232eb8cb62.png)

**Comment by shuckster** [comment]
Perhaps try back-ticking it? Or using single/double quotes:
```
order( 'sortOrder' )
order( '`sortOrder`' )
order( "'sortOrder'" )
order( '"sortOrder"' )
```

**Comment by MDXDave** [comment]
Nope, it does not make any difference.

**Comment by shuckster** [comment]
How about:
```
order( 'elements.sortOrder' )
order( '[[elements.sortOrder]]' )
```

**Comment by MDXDave** [comment]
> Column not found: 1054 Unknown column &#039;elements.sortOrder&#039; in &#039;order clause&#039;

**Comment by shuckster** [comment]
Try the edit.

**Comment by MDXDave** [comment]
Same error, but with _relations.sortOrder_ , the column will not be select from the database

**Comment by shuckster** [comment]
Perhaps the `relatedTo` option is messing things up? I guess you've tried it with `order` as the only option?

**Comment by MDXDave** [comment]
Nope, it also does not work without the _relatedTo_ param, same error.

**Comment by shuckster** [comment]
How about this: `order( 'structureelements.lft' )`

**Comment by MDXDave** [comment]
> Column not found: 1054 Unknown column &#039;structureelements.lft&#039; in &#039;order clause&#039;

**Comment by shuckster** [comment]
Damn. I actually tested that one and it works for Entries. Didn't test with Assets.

But on my adventures I found a bug with [fixedOrder](#2607), so perhaps the rabbit hole goes deeper. 🐰

**Comment by brandonkelly** [comment]
The issue here is that the `relations` table no longer gets joined into the element query in Craft 3, when using the `relatedTo` param. It just gets queried via a subquery.

Here’s the SQL query from your exception message, indented for clarity. The super-indented lines are what I’m talking about:

```sql
SELECT elements.id, ...
FROM (
	  SELECT elements.id AS elementsId, elements_sites.id AS elementsSitesId, content.id AS contentId
	  FROM elements elements INNER JOIN assets assets ON assets.id = elements.id
	  INNER JOIN elements_sites elements_sites ON elements_sites.elementId = elements.id
	  INNER JOIN content content ON content.elementId = elements.id
	  WHERE (elements_sites.siteId='1')
	    AND (content.siteId='1')
	    AND (elements.archived=FALSE)
	    AND (elements_sites.enabled=TRUE)
	    AND (elements.id IN (
	    	                 SELECT sources1.targetId
	    	                 FROM relations sources1
	    	                 WHERE (sources1.sourceId='29')
	    	                   AND (sources1.fieldId='3')
	    	                )
	        )
	  ORDER BY sortOrder
	 ) subquery
INNER JOIN assets assets ON assets.id = subquery.elementsId
INNER JOIN volumefolders volumeFolders ON assets.folderId = volumeFolders.id
INNER JOIN elements elements ON elements.id = subquery.elementsId
INNER JOIN elements_sites elements_sites ON elements_sites.id = subquery.elementsSitesId
INNER JOIN content content ON content.id = subquery.contentId
ORDER BY sortOrder
```

The easiest way to get the related elements ordered by `sortOrder` is just to go through the field itself, which will give you a different query where the `relations` table is actually joined into the parent query, so that elements can be ordered by `sortOrder`:

```twig
{% set assets = entry.assetsFieldHandle %}
```

From your example Twig code I don’t see any reason why just going that route wouldn’t work, unless there’s more to it you didn’t share. (If that’s the case, you’ll just need to manually join in the `relations` table, the way that [BaseRelationField::normalizeValue()](https://docs.craftcms.com/api/v3/craft-fields-baserelationfield.html#normalizeValue()-detail) does.)
