### ISSUE TITLE
Searching file extensions to be extended

### ISSUE THREAD

**Issue by seandelaney** [craftcms/cms#2606]
### Description

I have added extra file extensions to the `extraAllowedFileExtensions` list in the config file, but this does not find these extra file extensions when searching.

### Steps to reproduce

1. Update general config, adding `'extraAllowedFileExtensions' => 'xlsm',`
2. Upload an XSLM file (https://fileinfo.com/extension/xlsm).
3. Perform a search.
4. No results found.

### Additional info

- Craft version: Craft Pro 3.0.0-RC15
- PHP version: 7.2.1
- Database driver & version: MySQL 5.6.38
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Where are you performing the search, and what are you searching for?

**Comment by seandelaney** [comment]
So, for example, I uploaded a document called `Diving_PTW_Form_NSS_051A_Rev_A.xlsm`.

When I search I type in words in the Title or Filename of the document. e.g. Diving PTW or NSS_051A.

**Comment by seandelaney** [comment]
@andris-sevcenko Yes, still an issue.

**Comment by seandelaney** [comment]
Anyone???

**Comment by brandonkelly** [comment]
Assets register their full filename, their extension, and their file kind (e.g. `image`) as search keywords when saved. At no point is the type of file extension factored in.

I’m guessing it has more to do with your Craft/MySQL config. Try running this database query on the same DB server you’re getting this issue on: (You can use our [Query](https://github.com/craftcms/query) plugin if you don’t have access to the DB server.)

```sql
SHOW VARIABLES LIKE 'ft_min_word_len'
```

By default it should be 4, but I’m wondering if in your case it might be higher.

**Comment by seandelaney** [comment]
![screen shot 2018-04-09 at 14 26 48](https://user-images.githubusercontent.com/580403/38500362-1868a5de-3c02-11e8-8fa5-999fe2cde626.png)

**Comment by seandelaney** [comment]
I've just re-run the Assets indexes and now the files in question all appear in search results.

**Comment by seandelaney** [comment]
So either the assets indexes didn't run correctly or the update I did earlier, fixed something in the core codebase.

**Comment by seandelaney** [comment]
Thanks for your help @brandonkelly and @andris-sevcenko !

**Comment by brandonkelly** [comment]
Can you try running the Search Indexes utility? Curious if that will fix it.

**Comment by brandonkelly** [comment]
Great. Guessing this was just a fluke, then. Let us know if it crops up again.
