### ISSUE TITLE
No validation on edit of Number field

### ISSUE THREAD

**Issue by vimcat** [craftcms/cms#2612]
### Description
Number field validation does not work when _editing_ a Number field.

### Steps to reproduce

1. Create a Number field and save it.
2. Edit the newly created Number field and enter a string in 'Min' - it causes a Yii error: `Argument 1 passed to craft\helpers\Db::getNumericalColumnType() must be of the type integer or null, string given, called in .../vendor/craftcms/cms/src/fields/Number.php on line 124`

*note* validation while creating a new Number field works as expected. It's only when you edit the field and try to save an invalid value where it fails to validate.

### Additional info

- Craft version: 3.0.0-RC15
- PHP version: PHP 7.1.14
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting!
