### ISSUE TITLE
"out of range" SQL error for the "sortOrder" column in "relations" table

### ISSUE THREAD

**Issue by moldedjelly** [craftcms/cms#2613]
### Description
was getting an "out of range" SQL error for the "sortOrder" column in "relations" table when trying to save an entry... I had to change the column to INT and set length to 6 (was TINYINT length 3) and it stopped the error happening

### Steps to reproduce

1. Have a pretty heavy site with loads of assets in a field
2. Went to save the entry and got the SQL error "out of range" for relations table

### Additional info

- Craft version: 3.0.0-RC15
- PHP version: 7.0.8
- Database driver & version: MySQL 5.7.13
- Plugins & versions: NA

**Comment by brandonkelly** [comment]
Fixed, thanks!
