### ISSUE TITLE
User roles: User cant create Entries within channels when he have not right for __home__

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#2615]
We created a user role and give them all rights to add blogposts but it comes this error:

![image](https://user-images.githubusercontent.com/764292/37711028-c160c196-2d0f-11e8-8f26-4bb3c73cba51.png)

When we give him the rights for the __home__ single it works. But looks like a bug for me.

**Comment by brandonkelly** [comment]
Can you please send in a database backup to support@craftcms.com, and point us to the user account you created, and where that error is occurring? Thanks!

**Comment by davidhellmann** [comment]
@brandonkelly mail is out. Thanks!

**Comment by brandonkelly** [comment]
This turned out to be a bug with Expanded Singles, and looks like it has already been fixed via verbb/expanded-singles@6d5e9e980118f63b33b1a82d88e1f9771f95e3ad, though that fix hasn’t been released yet. (cc @engram-design)

**Comment by davidhellmann** [comment]
Ah, good point :) Forget that I've the plugin installed. Thanks for the hint @brandonkelly

**Comment by engram-design** [comment]
@brandonkelly Sorry to cause issues here, will be released shortly...
