### ISSUE TITLE
EVENT_REGISTER_SITE_TEMPLATE_ROOTS doesn't work on site requests

### ISSUE THREAD

**Issue by BenParizek** [craftcms/cms#2617]
### Description

It seems `EVENT_REGISTER_SITE_TEMPLATE_ROOTS` currently makes certain assumptions that apply to the CP that are different on the front-end.

Example implementation code:

```php
Event::on(View::class, View::EVENT_REGISTER_SITE_TEMPLATE_ROOTS, function(RegisterTemplateRootsEvent $event) {
    $myTemplateRoot = Craft::getAlias('@barrelstrength/sproutforms/templates/_special/templates');

    $event->roots = [
        'sprout-forms' => $formTemplateRoot
    ];
});
```

### Steps to reproduce

1. Add a `EVENT_REGISTER_SITE_TEMPLATE_ROOTS` to a plugin 
2. Try to load a page with a template that only exists in your plugin

### Additional info

- Craft version: RC15
- PHP version: 7.1
- Database driver & version: MySQL
- Plugins & versions: Lots under development

**Comment by BenParizek** [comment]
I've proposed a pull request above, that can at least illustrate what I think the issue may be.

It may be worth considering if the same syntax is desirable for front-end and backend requests.

It appears back-end requests require an array with the `plugin-handle` to help determine the sub-templates.

```
$event->roots = [
    'sprout-forms' => $basepath
];
```

However, on the front-end this may be meaningless info, as we can't assume that any particular folder structure is being respected, and a simple array may be a more expected pattern:

```
$event->roots[] = $basepath;
```

The pull request addresses the existing problem that the current syntax doesn't seem to work. However, it may make sense to update to this new syntax at some point.

**Comment by brandonkelly** [comment]
> 2. Try to load a page with a template that only exists in your plugin

How are you trying to load that page? Going with your example, Craft will only check your template root if the page URI begins with `sprout-form/...`.

**Comment by BenParizek** [comment]
Hmm, maybe I just need documentation here. I've actually decided on another route for this at the moment. After I got deeper into the potential direction, other potential issues revealed themselves. So maybe it's best to back away from this request until I understand what was supposed to be happening and see proper docs.

To give you an idea of what I was thinking, I was trying to make another template folder accessible on all requests as a fallback, and worry about avoiding conflicts in the plugin itself. So, from what you are saying, I think I wanted something like:

```
$event->roots = [
    '' => $basepath
];
```

The idea was to have something like this in the template:

```
{% include ['sprout-forms/subfolder/form'] with {
	handle: 'basicFieldsForm'
} %}
```

Where if the `form` template wasn't found on the front-end, it looked for the template in the new registered root. Obviously, there is a greater potential for conflict with a short template name like `form` so I was trying to solve that by pointing to a root that had a folder within it that acted as the namespace. 

So, Template Root would be something like `sprout-forms/templates/rootfolder` and the root folder would have a subfolder structure like `sprout-forms/subfolder/form`. So, the full path to my template I was trying to display was something like: `sprout-forms/templates/rootfolder/sprout-forms/subfolder/form`

From your comments, it seems that this feature requires us to match a URI with the key that we register? I'd need to test again, but am I wrong to think that this could be used for includes on any request, or did I just get the syntax wrong to do something like that?

**Comment by brandonkelly** [comment]
> The idea was to have something like this in the template:
> 
> ```twig
> {% include ['sprout-forms/subfolder/form'] with {
>     handle: 'basicFieldsForm'
> } %}
> ```

That would be totally possible if you set a `sprout-forms` template root, pointed at a directory that contains a `subfolder/form` template.

Maybe the easiest way to wrap your head around template roots is to consider that you are **already using them** every time you load one of your plugin’s templates in the Control Panel.

For example, if you go to `/admin/sprout-forms/foo/bar`, here’s how Craft interprets that URI:

```
┌─────────┐   ┌────────────────────────────┐
│         │   │ ┌──────────────┐           │
│  admin  │ / │ │ sprout-forms │ /foo/bar  │
│         │   │ └───────┬──────┘           │
│         │   │         ╵                  │
│         │   │   template root            │
└────┬────┘   └───────────────┬────────────┘
     ╵                        ╵
CP trigger              template path
```

It recognizes `sprout-forms` as a template root because your plugin registered it as one, from the `craft\base\Plugin` constructor:

https://github.com/craftcms/cms/blob/e916d854d869d55de286c0e2ffe5f4e1161d8219/src/base/Plugin.php#L77-L82

(`$this->id` is your plugin’s handle, `sprout-forms`.)

Same applies when a CP template includes/extends another `sprout-forms/...` template.

So the `EVENT_REGISTER_SITE_TEMPLATE_ROOTS` is just a front-end facing version of `EVENT_REGISTER_CP_TEMPLATE_ROOTS`, and the same rules apply to it.

**Comment by BenParizek** [comment]
Thanks, Brandon. I haven't had a chance to test this yet, but I'm going to go ahead and close this. From the comments above, it sounds like I was just misunderstanding how the root needed to be structured.
