### ISSUE TITLE
`modifyAssetFilename` is being run twice

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#2624]
### Description

The `modifyAssetFilename` hook seems to get run twice when a file is uploaded.

### Steps to reproduce

1. Write a simple hook, like this one...

        public function modifyAssetFilename($filename)
        {
            $filename = $filename.'-'.time();
            return $filename;
        }

2. Save a new asset.
3. Notice that the `time` was appended to the filename twice.

### Additional info

- Craft version: 2.6.3012
- PHP version: 7.0
- Database driver & version: MySQL 5.7
- Plugins & versions: Tons

**Comment by lindseydiloreto** [comment]
This site has tons of plugins, so it's certainly _possible_ that this is a local issue. However, I did some rudimentary searches for `modifyAssetFilename`, and only came up with this one instance.

**Comment by andris-sevcenko** [comment]
I can certainly reproduce this.

**Comment by lindseydiloreto** [comment]
Sweet, thanks @andris-sevcenko!
