### ISSUE TITLE
Viewport to big to load more Assets

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#2626]
I've to resize my browser to trigger the ajax request for more images :) Maybe a combo button that we can trigger by hand would be nice.

![image](https://user-images.githubusercontent.com/764292/37746215-6d7f191e-2d79-11e8-92a7-7a0a4fdb23a3.png)

**Comment by brandonkelly** [comment]
This seems to be working on my end – as long as the bottom image is within the viewport, the index will keep loading more batches.

Any chance you can send us an admin account to your site? support@craftcms.com

**Comment by davidhellmann** [comment]
Send it.
