### ISSUE TITLE
Error when creating new category from an entry's popup

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#2627]
### Description

With a user that got permissions to edit sites versions others that the primary, and when editing one entry from one of this non-primary site entry, I can't add new category from an entry's popup when the user has not the permission to edit the primary site.

I get this error after clicking on _+ New Category entry:_ An unknown error occurred. Please note that this category is enabled for all sites versions, so it should not return this error.

It really seems related to a permission bug, because if I add the primary site permission to this user, the error disappears.

### Steps to reproduce

1. Edit an entry
2. Click on the button to add a new category
3. Try to create a new category from the entry's popup

### Additional info

- Craft version: 7.1.8
- PHP version: 3.0.0-RC15
- Database driver & version: MySQL
- Plugins & versions:

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Here’s exactly what I did:

1. Create a section that is enabled in a non-primary site
2. Create a category group
3. Create a Categories field tied to the category group
4. Add the Categories field to the section
5. Create a user that only has access to the non-primary site
6. Log in as that user, and edit an entry in the section
7. Click “Add a category”
8. Click the “Net [group name] category” button in the modal
9. Define a new category and save it, and select it from the modal
10. Save the entry

All of that worked as expected for me. Am I missing something? If you’re not sure what other steps I should be trying, can you just send us a database backup, and point us to the user we should be testing with, and what section? You can send it to support@craftcms.com. Thanks!

**Comment by romainpoirier** [comment]
Thank you for trying this. I also tried the steps you described, and as you I was able to create this new category. That's probably because the setup is not exactly the same.

So, to be more precise in my case:

- This section is enabled in all site versions
- This user has permissions granted for all site versions except the primary site

I tried with a brand new section, brand new category and brand user but as you I was not able to reproduce this, so I should be related to something else...

After trying again with the initial setup that got this error, the following is what I can see in the logs:

`2018-03-23 11:21:20 [::1][242][-][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: Entry is missing its section ID in /vendor/craftcms/cms/src/elements/Entry.php:651`

I'm sending you a support ticket so you can check with the same database backup.

**Comment by brandonkelly** [comment]
The missing piece is that this bug affects creating _entries_, not _categories_. Fixed now for the next release.
