### ISSUE TITLE
Why can't you Propagate entries across all enabled sites for structures

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#2630]
Hi,

Why can't you Propagate entries across all enabled sites for structures, this would be really helpfull.
For instance, if you have pages with relation to each other, it doesn't necessarily mean you want those on all sites. For channels, you can just tick the box and it fixes this, but for structures this option is not available. Why is this?

**Comment by carlcs** [comment]
@lenvanessen have a look at https://github.com/craftcms/cms/issues/2386

**Comment by lenvanessen** [comment]
Close 'cause duplicate
