### ISSUE TITLE
Requesting URL segments on the homepage not returning an empty array 

### ISSUE THREAD

**Issue by marknotton** [craftcms/cms#2633]
### Description

On a homepage where there are no paths in the URL. Requesting the URL segments no longer returns an empty array. 

### Steps to reproduce

`{{ dump(craft.app.request.segments) }}`

Returns:

`array(1) { [0]=> string(0) "" }`

The same happens with the Craft 2 equivalent method:

`{{ dump(craft.request.getSegments() }}`

In Craft 2, this was what use to be returned: 

`array(0) { }`

This essentially makes doing something like this defunct:

`{% if craft.app.request.segments is empty %} ... {% endif %}`

My current work around:

`{% if craft.app.request.segments|first is empty %} ... {% endif %}`

Maybe this isn't a bug and is meant to be intentional. But thought it was worth sharing.

### Additional info

- Craft version: 3.0.0-RC15
- PHP version: 7.0

**Comment by brandonkelly** [comment]
Definitely not intended. Fixed now. Thanks!
