### ISSUE TITLE
Password reset GDPR

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/cms#2640]
I was reading an [article](https://www.webdesignerdepot.com/2018/03/how-to-survive-gdpr-the-essential-guide-to-the-webs-new-privacy-regulations/) this morning about how to prepare for GDPR and it mentions how to handle password reset requests. The suggestion is that we shouldn't be confirming whether or not an account exists based on the details provided. 

> Could a malicious user compromise data by triggering an error? For example, if a user enters email addresses in a “Forgot Email” form, will the form confirm that the password reminder has been sent (and by inference confirm that the user has an account)?

If an account doesn't exist Craft informs the user: 

<img width="364" alt="image" src="https://user-images.githubusercontent.com/24975058/37959338-d1144a3c-31aa-11e8-8c39-76a334316336.png">

Should this be changed so that the submission always succeeds, with the request only being processed if an account exists and failing silently if one doesn't?

**Comment by brandonkelly** [comment]
There’s a config setting for that :) https://craftcms.com/docs/config-settings#preventUserEnumeration

**Comment by lukeyouell** [comment]
@brandonkelly Impressive! Thanks!
