### ISSUE TITLE
RC 16.1 seems to break showing available updates for plugins

### ISSUE THREAD

**Issue by kjmartens** [craftcms/cms#2642]
### Description

We have an update for Solspace Calendar (beta 7) that I am certain was showing while on RC15 (with Calendar beta 6), and then after updating to RC16.1, the update option inside Updates page of CP went away for Calendar. I waited it out for a day now and still there (and seemingly no one else has mentioned this yet). The Plugin store shows beta 7 is available, and a fresh install of Calendar from plugin store gives me beta 7. Also, updating through Terminal works fine for getting me from beta 6 to beta 7. I tested this with another plugin as well and same issue. @carlcs also confirmed this with me in Craft Slack.

### Steps to reproduce

1. Have an plugin you know has an update available (or install earlier version)
2. Go to Updates area in Craft CP and you'll see no available updates for it if using Craft 3 RC 16.1

### Additional info

- Craft version: Craft 3 RC 16.1
- PHP version: PHP 7.1.12
- Database driver & version: MySQL 5.6.38

**Comment by brandonkelly** [comment]
Thanks for pointing that out! We’ll get an update out soon with a fix.
