### ISSUE TITLE
CP Menu plugin icon svg path gets hardcoded

### ISSUE THREAD

**Issue by juresrpcic** [craftcms/cms#2643]
### Description

When I install [SEOmatic](https://github.com/nystudio107/craft-seomatic) (latest beta, but has been an issue since the beginning and had the same issue with other plugins that have custom icons) on the server, it works fine, but locally, the icon is a big mess. When examining the svg path in devtools, I see the path is still hardcoded (same as on Ubuntu 16.04 server where the plugin was installed initially).

![craft-broken-icon](https://user-images.githubusercontent.com/2803433/37970823-bbb63568-31d4-11e8-8bea-72c88774c15e.png)

The devtools path for the broken svg in above screenshot is: `/home/forge/productionwebsite.com/vendor/nystudio107/craft-seomatic/src/icon-mask.svg`

It should be: `c:\web\devwebsite.local\vendor\nystudio107\craft-seomatic\src\icon-mask.svg` as this is on windows. Forward slashes would work too from my experience. 

The same thing happens if I install the plugin locally first and then move to Linux - the hardcoded path is now from Windows and the nasty icon is shown on Linux.

### Steps to reproduce

1. Install a plugin with a custom icon on production (Linux)
2. Export DB, import locally (Windows)
3. Custom plugin SVG path is broken - the path is hardcoded and still from Linux

### Additional info

- Craft version: 3.0.0-RC16.1
- PHP version: PHP 7.1.10 (cli) (built: Oct 4 2017 08:54:01)
- Database driver & version: MySQL 5.7.19
- Plugins & versions: SEOmatic 3.0.0-beta.18

**Comment by angrybrad** [comment]
Is it more than just the database you move over when doing this?  i.e. anything in the `craft/vendor` folder?

**Comment by juresrpcic** [comment]
No, just the database, I install all composer dependencies separately on dev/production.

Just to be sure, I tried `rm -rf vendor/` + `rm composer.lock` + `composer install` again locally (where the icon is broken currently) - doesn't help.

**Comment by angrybrad** [comment]
Can you share a screenshot of the HTML you're seeing when you inspect the code.  Craft just loads the SVG data to display a plugin's icon so not seeing how any absolute paths are coming into play: https://github.com/craftcms/cms/blob/develop/src/services/Plugins.php#L925

Also, I'm not able to reproduce this with the testing I've done.

![capture](https://user-images.githubusercontent.com/61869/39788154-ed24ec5a-52dd-11e8-8b90-b2a692edff2e.PNG)

**Comment by juresrpcic** [comment]
I think I found the culprit - the `verbb/cpnav` plugin. This is a screenshot of my code when using `cpnav`: 

![svg-issue-cpnav](https://user-images.githubusercontent.com/2803433/39801602-0703892c-536c-11e8-8960-2eb4290f6172.png)

And here it is when I uninstall `cpnav`:

![svg-issue-without-cpnav](https://user-images.githubusercontent.com/2803433/39801608-0be3a97c-536c-11e8-9a34-70fed818a429.png)

... I'll reference this issue in cpnav's tracker.

**Comment by juresrpcic** [comment]
Issue is resolved in cp-nav 2.0.6, thanks Josh!
