### ISSUE TITLE
UI/UX — field widths and matrix tabs.

### ISSUE THREAD

**Issue by H-i-red** [craftcms/cms#2644]
### Description

**Ui/Ux**. Field widths and matrix tabs.
Use flexbox/grid for field widths on dekstop/tablets view. On mobile view, just add a media query, full width and call it the day.

**New** :

![new](https://user-images.githubusercontent.com/19476159/37975194-0d00429c-31df-11e8-87d8-d542179714b5.png)

**Old** :

![old](https://user-images.githubusercontent.com/19476159/37975195-0d29894a-31df-11e8-95ef-f6d180fccc82.png)

**Set width for field** :

![width](https://user-images.githubusercontent.com/19476159/37975196-0d43995c-31df-11e8-84d8-54550c8166db.png)

**Comment by Rias500** [comment]
Groups, tabs and horizontal fields with defined column sizes would indeed be a great addition!

**Comment by carlcs** [comment]
@H-i-red feature requests for all of this already exist. See https://github.com/craftcms/cms/issues/2409 and https://github.com/craftcms/cms/issues/1138

**Comment by H-i-red** [comment]
oh crap sorry..

**Comment by Rias500** [comment]
The horizontal fields with widths is a new feature request though I think

**Comment by davidhellmann** [comment]
@H-i-red is that photoshop or do u have tabs within matrix fields? 🤔

**Comment by H-i-red** [comment]
@davidhellmann I do have tabs ; ) !

**Comment by H-i-red** [comment]
I did a hacky solution by creating a module to add css and js to admin. Then I took the plugin "entry instructions" targeted the fields with js and css... But hey it works.. lol... 
Here are the js if interested :  You have to add a observer to check for dom changes (New matrix blocks..) I don´t have the plugin skills atm. but someone else maybe does.. 🤔

```
jQuery(document).ready(function ($) {

    'use strict';

    var config = { childList: true };

    $(".matrix .blocks").each(function () {
        var target = this;
        var observer = new MutationObserver(function(mutations) {
            mutations.every(function(mutation) {
                if (mutation.addedNodes.length > 0) {
                    tabber($(mutation.addedNodes));
                }
            });
        });
        observer.observe(target, config);
    });

    function tabber(obj) {
        if (obj) {
            var tabs = obj.find('div.field[data-type$="EntryInstructionsField"]');
            tabs.first().addClass("active");
            tabs.on('click', function() {
                tabs.removeClass("active");
                $(this).addClass("active");
                console.log("cool")
            });
        } else {
            $('.matrixblock').each(function() {
                var tabs = $(this).find('div.field[data-type$="EntryInstructionsField"]');
                tabs.first().addClass("active");
                tabs.on('click', function() {
                    tabs.removeClass("active");
                    $(this).addClass("active");
                    console.log("cool")
                });
            });
        }
    }

    tabber();
});
```
Some of the css to hide the "inactive fields"..

```
.matrixblock div.field[data-type$="EntryInstructionsField"] ~ div {
    display: none;
}

.matrixblock div.field[data-type$="EntryInstructionsField"].active ~ div {
    display: block;
}

.matrixblock div.field[data-type$="EntryInstructionsField"].active ~ div.field[data-type$="EntryInstructionsField"] ~ div {
    display: none;
}
```

**Comment by davidhellmann** [comment]
OK, that sounds hacky :D but cool! :D haha

**Comment by brandonkelly** [comment]
As of the next Craft 3.5 release, it will be possible to customize fields’ widths, setting them to either 25%, 50%, 75%, or 100% width.

<img width="248" alt="Two fields with 50% width" src="https://user-images.githubusercontent.com/47792/87213177-ebea9d00-c2d7-11ea-8cf9-ca7dba620a23.png">

Note that this doesn’t affect Matrix sub-fields yet, and will keep #2409 open to address the Matrix block tabs request.

**Comment by brandonkelly** [comment]
Matrix sub-fields have now been updated to support custom field widths as well (see https://github.com/craftcms/cms/issues/6346#issuecomment-658919451).
