### ISSUE TITLE
Tranfer license key to new domain - error

### ISSUE THREAD

**Issue by kinoli** [craftcms/cms#2647]
### Description
I transferred my 'Personal' 2.x version of craft to a new domain. When I click 'Transfer it to this domain', referring to the license key. It always says, it is unable to do so at this time. How do I fix that?

### Steps to reproduce

1. click button
2. see error

### Additional info
I just downloaded it a few weeks ago.

- Craft version: 2.6.3012 (Personal)
- PHP version: 7.1.15
- Database driver & version: MySQL 5.5.58-cll
- Plugins & versions: 
    - Prune 0.1.0

**Comment by brandonkelly** [comment]
Domain transferring must now be done from your [Craft ID](https://id.craftcms.com/) account.

Unfortunately there was no way for us to make that change without making it awkward for existing Craft installs that still think it’s possible to transfer licenses within the app, but if you update to Craft 2.6.3013 this has been “fixed” by replacing the Transfer button with a link to id.craftcms.com.
