### ISSUE TITLE
Cyrillic "х" character causes "Malformed UTF-8 characters, possibly incorrectly encoded." error

### ISSUE THREAD

**Issue by extens** [craftcms/cms#2650]
### Description

Cyrillic "х" character (U+0445) in title or any plain text field causes "Malformed UTF-8 characters, possibly incorrectly encoded." error on submit. 

Issue appeared after RC16 or 16.1.

For entries, created before that in edit entry page or website itself character is replaced with unknown character symbol. In DB data is intact and can be shown property in entries list view.
![screen shot 2018-03-27 at 10 55 37](https://user-images.githubusercontent.com/7449123/37954575-eb7d7656-31ae-11e8-93f2-55f21c80b6ae.png)
![screen shot 2018-03-27 at 10 55 43](https://user-images.githubusercontent.com/7449123/37954576-eba19c7a-31ae-11e8-85ac-b9170bc45e1d.png)

### Steps to reproduce

1. Update to RC16 or RC16.1
2. Create new entry with "х" character in title or any plain text field.

### Additional info

- Craft version: 3.0.0-RC16.1
- PHP version: 7.0, 7.1.15, 7.2
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

**Comment by SpySerp** [comment]
I can confirm this issues

**Comment by brandonkelly** [comment]
Hi @extens & @SpySerp, can you please update to RC17 and re-test this?

**Comment by SpySerp** [comment]
@brandonkelly The problem is still present in RC17, both in admin panel and front-end, database contains correct values

**Comment by SpySerp** [comment]
And I confirm that it fixed by @angrybrad, thanks

**Comment by extens** [comment]
Hi @brandonkelly, updated to RC17, issue is still there for plain text fields. Also when trying to output such field in template from an entry, created earlier, get a blank page (no errors in craft logs).

**Comment by brandonkelly** [comment]
@extens Yeah at first glance I had thought it was something else. It’s fixed now for the next release (we’ll probably release a 17.1 later today).

**Comment by brandonkelly** [comment]
We just released Craft 3 RC17.1 with a fix for this.

**Comment by extens** [comment]
Yep, fixed indeed, thanks!
