### ISSUE TITLE
Changing the handle of a matrix field doesn't rename the table resulting in data lost

### ISSUE THREAD

**Issue by MoritzKn** [craftcms/cms#2651]
### Description

When changing the handle of a matrix all usages of it are empty.
I could fix this by renaming the database table. E.g. after renaming the matrix filed foo to bar executing:
```sql
RENAME TABLE matrixcontent_foo TO matrixcontent_bar;
```
### Steps to reproduce

1. Create matrix filed
2. Use it
3. Rename filed
-> Data is gone

### Additional info

- Craft version: Craft 3 RC 14
- PHP version: 7.2.0
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Element API (2.5.2), Redactor (1.0.1), Amazon S3 (1.0.8)

**Comment by brandonkelly** [comment]
Not able to reproduce this on my end. Do you have a database backup from before you made the change? If so can you send to support@craftcms.com ?
