### ISSUE TITLE
"Unable to delete the file: No such file or directory" errors

### ISSUE THREAD

**Issue by tyler-deboer** [craftcms/cms#2652]
### Description
This seems to be related to #2463 but it's still happening to me on the latest RC. If my cache gets cleared or I'm uploading a lot of assets at once, and then I navigate to the Assets page, the site stalls  (both back-end and front-end) for several seconds, and sometimes even up to 20-30 seconds. Going through the logs I see a bunch of warnings in `craft\services\AssetTransforms::getLocalImageSource` that look like:

```Unable to delete the file "/var/www/site-name/storage/runtime/assets/sources/1335.jpg": unlink(/var/www/site-name/storage/runtime/assets/sources/2227.mp4): No such file or directory```

It seems that my permissions are all set up correctly - the `storage/runtime` folder has `755` permissions and has the same user:group as what's running PHP.

On a (possibly?) related note, it seems to be trying to generate thumbnails for .mp4 videos I'm uploading too, which also stalls the site. For those I'm getting 500 errors in `craft\errors\ImageException` 

```craft\errors\ImageException: The file “compressed-industry-pages-exterior5abbdc8183dec7.65958004.mp4” does not appear to be an image. in /var/www/site-name/vendor/craftcms/cms/src/image/Raster.php:169```

### Additional info
- Craft version: Craft Pro 3.0.0-RC16.1
- PHP version: 7.2.2
- Database driver & version: MySQL 5.7.21
- Image driver & version: Imagick 3.4.3 (ImageMagick 6.8.9-9)
- Plugins & versions: Various, but ImageOptimize 1.4.24 and (maybe?) Async Queue 1.3.0 would be relevant to this issue.

**Comment by andris-sevcenko** [comment]
If you clear the caches or upload a lot of assets, you would probably end up generating quite a few thumbnails. What sort of files are you uploading? If the majority are images, are there also GIFs in that mix?

As far as Craft thinking it could generate thumbnails for videos, I'll think about how to handle it with more grace.

**Comment by tyler-deboer** [comment]
I have about ~350 total images in my Assets library. I usually only upload one at a time as needed, but occasionally will batch upload 5-6 at once. I have maybe 3-4 gifs in there, the rest are either .png, .jpg or .svg. 

I'm not sure if it's an Imagick thing, a permissions thing, or something else. I'm running the site on a DigitalOcean 4 CPU 8GB droplet, so I don't think it should be the server. Are there any other environment factors that could be playing a role in it? I'm not really a devops guy so I'm not totally sure what relevant things I should be looking for.

**Comment by andris-sevcenko** [comment]
I've made some changes in 242fbed. If your composer is pointed towards dev-develop, you can do composer-update. If not, you'll have to wait for the next release and see if it helps your woes.

**Comment by tyler-deboer** [comment]
Sounds great, thanks! I'll update to the latest `dev-develop`. If I keep running into that issue I'll keep you posted.

**Comment by andris-sevcenko** [comment]
@tyler-deboer okay, closing for now!

**Comment by kgrote** [comment]
I'm still having this problem in 3.1.1. It happens when I move the site files to a new environment. Since `craft/storage/runtime` is .gitignore'd none of the local transforms come along for the ride. Then my transform URLs break in the templates and all of the asset thumbnails in the control panel break. In `web.log` I get the same "Unable to delete the file" error.

Seems to resolve itself after a few hours so it's clearly a caching issue, but clearing the asset caches and the asset transform index doesn't have any effect.

**Comment by cdm2m** [comment]
罗祖脉

总经理

成都多一晨网络科技有限公司

0773-2537748

18577384028

广西桂林市七星区桂磨大道国家大学科技园509




 
 
 
------------------ Original ------------------
