### ISSUE TITLE
[FR] Config Settings for Asset View

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#2653]
Is it possible to add a config option to set the default view for images? 

![image](https://user-images.githubusercontent.com/764292/38050094-3878568a-32ca-11e8-9efb-f89d0b6cddfb.png)

I think most of the time the grid view is much better for editors to find the right picture.

**Comment by brandonkelly** [comment]
No, but the page will remember what you had selected between page loads (remembered per source.).
