### ISSUE TITLE
Reordering structured content generates 403 Forbidden

### ISSUE THREAD

**Issue by nazwa** [craftcms/cms#2655]
### Description

When trying to order structured entries as an admin, craft shows `Unknown error` .

Response from the actual request:
```
Unauthorized
User is not authorized to perform this action
```

### Steps to reproduce

1. Create a few entries in a structured section
2. Drag one of them to a new position
3. `Unknown error`

### Additional info

- Craft version: 3.0.0-RC17
- PHP version: 7.1.15
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
AsyncQueue 1.3.0
Control Panel CSS 2.1.0
Element API 2.5.2
Image Resizer 2.0.2
Redactor 1.0.1

**Comment by brandonkelly** [comment]
Are you getting this when logged in as an admin or a regular account? If the latter, what permissions does the user have? And is this a multi-site install?

**Comment by nazwa** [comment]
Hey @brandonkelly 

yes - the issue was on an admin account - but I managed to find an answer (i think).

After ours of searching I realized it was caused by multiple docker instances of the cms running and the load balancer was persistently hitting the one without a valid session. Not sure why this was never an issue for any other actions, but removing the second instance fixed the problem!

**Comment by brandonkelly** [comment]
Ah gotcha, thanks for the follow up!
