### ISSUE TITLE
Section permissions are ignored when linking to an entry

### ISSUE THREAD

**Issue by its-me-mario** [craftcms/cms#2656]
### Description
Users with permissions to limited sections can still “link to an entry” in any section from within the WYSIWYG (Redactor) editor. 

### Steps to reproduce

1. Create a user with no permissions for certain a sections
2. Login as that user
3. Edit an entry with a Rich Text (Redactor) field
4. Create a "Link to an entry"
5. The user can now see ALL sections, not the ones that theiry limited to.

### Additional info

- Craft version: 2.6.3013
- PHP version: 7.1.7
- Database driver & version: Apache/2.4.7 (Ubuntu)

![wysiwyg-section-permissions](https://user-images.githubusercontent.com/788170/38057845-9732c15e-3295-11e8-820d-b47287707182.jpg)

**Comment by brandonkelly** [comment]
This is expected behavior, as all they are doing is selecting entries here (and only entries that actually have URLs); not actually viewing them.
