### ISSUE TITLE
Tabs CSS / JS now has super high specificity

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#2660]
The [Recipe](https://github.com/nystudio107/craft-recipe) plugin for Craft CMS uses tabs in its Field to divide up the settings:

![recipe01](https://user-images.githubusercontent.com/7570798/38098080-13ebea0e-3345-11e8-8e87-b190b05aa006.png)

This worked by leveraging the `tabs` CSS class, which styled things appropriately, and apparently the JS also keyed off of, because it "just worked" in previous versions of Craft 3. Somewhere along the way, this has broken (it's broken as of Craft CMS 3.0.0-RC.17, not sure when things changed):

<img width="710" alt="google chromescreensnapz101" src="https://user-images.githubusercontent.com/7570798/38098099-1f102c9c-3345-11e8-885c-c5d3819286f3.png">

This appears to be because the specificity is now super high for tabs, tied to a single element with an `id` of `tabs`:

```
        #tabs {
          position: relative;
          z-index: 1;
          box-shadow: inset 0 -1px 0 $hairlineColor;
          min-height: 40px;
          overflow: hidden;

          ul {
            display: flex;
            flex-direction: row;
            width: calc(100% + 1px);

            li {
              box-sizing: border-box;
              @include border-right(1px solid $hairlineColorAlpha);

              a {
                position: relative;
                display: block;
                padding: 10px 24px;
                white-space: nowrap;
                overflow: hidden;
```

Is there a way to get this reverted back? And if not, what is the suggested method going forward for a plugin wanting to implement Craft-styled tabs in a Field or Field Settings?

**Comment by khalwat** [comment]
...and duplicate the CSS? Because it’s tied to a single element with `id` of `tabs`

**Comment by brandonkelly** [comment]
Yeah. As of RC1, Craft no longer supports any tabs besides the main tabs at the top of the content area.

**Comment by khalwat** [comment]
Implemented my own
