### ISSUE TITLE
Database exception when saving an element with a PlainText field containing an uppercase "Å" character

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#2663]
### Description

Since updating from Craft 3.0.0-RC15 to Craft 3.0.0-RC16.1 (skipped RC16), I've been unable to save elements where a PlainText field contains an uppercase `Å` character, because the following database exception is thrown:

`SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xC3\x0A' for column 'field_heading' at row 1`

**I'm currently on 3.0.0-RC17, and the issue persists.**

After the database exception, the element is not (re)saved. If I turn off `devMode` the exception is not thrown and the element _is_ saved, but the `Å` character will render as a `�`.

I first noticed the issue after updating from RC15 to 16.1, when all uppercase Å's in PlainText fields were changed to the `�` character (indicating an invalid UTF-8 character). Attempting to replace the `�` with the `Å` character threw the above exception for the first time. 

Lowercase `å` does _not_ cause the exception, and neither does any other lower- and uppercase special characters I've tried – such as `Ø` and `Æ` (these are all common letters in Norwegian). In other words, only the uppercase `Å` seems to cause this error.

The error happens both in Entries and in Global Sets (haven't tried other element types).

The error happens for all PlainText fields (also inside Matrix and SuperTable blocks).

The error does _not_ happen for the _Title_ field.

The error happens regardless of whether or not a certain PlainText field _previously_ (i.e., before updating to RC16.1) in an existing element held an `Å` character or not.

The error happens both in re-saving entries that existing pre-RC16.1, and in new Entries created after updating.

The error happens both locally (running Valet on OSX) and on Forge.

The error also happens if I disable all installed plugins.

### Steps to reproduce

1. Enable `devMode`
2. Add an uppercase `Å` to a PlainText field (anywhere in the field; doesn't have to be the first or only character)
3. Save the element

### Additional info

- Craft version: 3.0.0-RC16.1 and 3.0.0-RC17
- PHP version: 7.0.14 and 7.0.28
- Database driver & version: MySQL 5.6.34 and MySQL 5.5.5-10.1.31-MariaDB
- Plugins & versions: Amazon S3 1.0.8, Child Me! 1.0.0, Cookies 1.1.9, CP Clear Cache 1.0.1, CP Field Inspect 1.0.4, Entry Instructions 1.0.0, Field Manager 2.0.2, Imager dev-craft3, Image Resizer 2.0.2, Inlin 2.0.0, Minify 1.2.8, Preparse Field 1.0.0, Redactor 1.0.1, Retcon 1.0.0, Stamp 2.0.0, Super Table 2.0.4

Database collation is `utf8-general-ci`

Site locale is `nb`

**Comment by brandonkelly** [comment]
We just released Craft 3 RC17.1 with a fix for this.
