### ISSUE TITLE
Craft.js:12647 Uncaught TypeError: Cannot read property 'css' of null

### ISSUE THREAD

**Issue by fb-derrick-grigg** [craftcms/cms#2664]
### Description
When attempting to edit field settings the following JS error is thrown:

Craft.js:12647 Uncaught TypeError: Cannot read property 'css' of null
    at s.constructor.updateAddRowButton (Craft.js:12647)
    at s.constructor.init (Craft.js:12608)
    at s.constructor.constructor (garnish.js:711)
    at s.constructor (garnish.js:40)
    at new s.constructor (garnish.js:40)
    at 9:2487

### Steps to reproduce

1. Attempt to create a new field or edit an existing field 

<img width="489" alt="screen shot 2018-03-31 at 9 49 02 pm" src="https://user-images.githubusercontent.com/32313284/38169119-2ef96a4c-352f-11e8-99e0-8a06b8255085.png">
<img width="573" alt="screen shot 2018-03-31 at 9 48 51 pm" src="https://user-images.githubusercontent.com/32313284/38169121-31c2534c-352f-11e8-88b4-63c79ec0e041.png">

### Additional info

- Craft version: Craft CMS 3.0.0-RC17.1
- PHP version: 7.0.19
- Database driver & version: MySQL 5.6.33
- Plugins & versions:

CKEditor	1.0.0-beta.2
Linkit	v1.0.5
Redirect plugin for Craft 3	1.0.15
SEOmatic	3.0.0-beta.19
Super Table	2.0.4
Video Embedder	1.0.8

**Comment by juresrpcic** [comment]
@fb-derrick-grigg Try clearing caches and deleting your `web/cpresources/` folder. https://github.com/craftcms/cms/issues/2659#issuecomment-377506223

**Comment by fb-derrick-grigg** [comment]
@juresrpcic that worked thanks!
