### ISSUE TITLE
Propagate versions for channel/structure entries

### ISSUE THREAD

**Issue by colinmeinke** [craftcms/cms#2669]
### Description

When I create a new channel with entry versioning and select “propagate across all enabled sites”, on editing an entry content **is** propagated, but versions are only added for the current site.

I would expect versions to be added for all sites. If not, how do you got about creating "global" content with versions? 

### Steps to reproduce

1. Setup a Craft install with multiple sites.
2. Create a channel, with versioning and “propagate across all enabled sites” enabled.
3. Create an entry.
4. Edit that entry.
5. View the entry versions table, version have only been added for the current site.

### Additional info

- Craft version: 3.0.0-RC17.1

**Comment by carlcs** [comment]
An enabled “propagate across all enabled sites” setting _only_ makes sure that all of the section’s entries always exist for all sites. Content can still be unique per site (depends on the fields’ translation settings), so entry versions have to be stored per site as well.

What I’d suggest for global content is to create the section for one site only and then use the `site` parameter in your element queries.

**Comment by colinmeinke** [comment]
Thanks, this is what I ended up doing. It just doesn't feel right from a UX perspective, but I can see the technical reasons for it.

**Comment by carlcs** [comment]
@colinmeinke you might want to leave this open and see what P&T has to say

**Comment by brandonkelly** [comment]
Yeah considering content is per-site, so should entry drafts/versions.

**Comment by colinmeinke** [comment]
@brandonkelly I think this may need revisiting. This doesn't seem right conceptually:

1. Create a new structure, enable versioning, enabled on 4 sites.
2. Create an entry for the new structure, content is updated for all sites, but a version is only added for the site I am editing.
3. Edit the entry 2 more times, content is updated for all sites, but again a version is only added for the site I am editing.

In reality, all sites have had 3 versions, but only the site that I was editing has been added to the `entryversions` table. I understand this is really tricky technically as some fields can be translatable, but I feel that if the state of an entry changes at all for a specific site, then a new version should be added.

**Comment by brandonkelly** [comment]
@colinmeinke Yeah I guess I could see that. I’lr reopen, and will consider this when we rewrite the revision system (planned for a future 3.x release).

**Comment by brandonkelly** [comment]
This has been added for the next 3.2 Alpha release!
