### ISSUE TITLE
suppressTemplateErrors results in Call to a member function display() on string error when using include to handle per-entry type templates

### ISSUE THREAD

**Issue by harrison-drift** [craftcms/cms#2676]
### Description
Sorry for the title-gore!

When trying to follow the instructions [here](https://craftcms.com/support/entry-type-templates) for setting up per-entry type templates with `'suppressTemplateErrors' => true` in the config a `Call to a member function display() on string` error occurs.

The strange thing is this works absolutely fine if `suppressTemplateErrors` is disabled. This also works if not visiting a page using the fallback but instead a unique template. This also happens regardless of the content in the default templates.

The compiled troublesome template PHP is as follows apparently.
```
$this->loadTemplate(array(0 => ("markets/_types/" . craft\helpers\Template::attribute($this->env, $this->getSourceContext(), (isset($context["entry"]) || array_key_exists("entry", $context) ? $context["entry"] : (function () { throw new Twig_Error_Runtime('Variable "entry" does not exist.', 1, $this->source); })()), "type", array())), 1 => "markets/_entry"), "markets/_template-router", 1)->display($context);
```

The twig that's generating that is as follows.
```
{% include ["markets/_types/" ~ entry.type, "markets/_entry"] %}
```

### Steps to reproduce

1. Setup a template structure to use per entry type templates with a fallback like [here](https://craftcms.com/support/entry-type-templates)
2. Have `'suppressTemplateErrors' => true` in your config
3. Visit a url that would be using the default template for that entry type

### Additional info

- Craft version: Craft Pro 3.0.0-RC17.1
- PHP version: 7.2.4
- Database driver & version: MySQL 5.7.21
- Plugins & versions: 
  - Expanded Singles 1.0.3
  -  Redirect plugin for Craft 3 1.0.15

**Comment by brandonkelly** [comment]
Can you find the error in `storage/logs/web.log` (or possibly in a subsequent log file) and post the stack trace that follows it?

**Comment by Harry-Harrison** [comment]
@brandonkelly Sorry, I've only just spotted your reply here and I have no clue what project this was. This can probably be closed though if you're unable to recreate it?

**Comment by brandonkelly** [comment]
Hah no worries! I don’t think we’ve seen a similar report since.
