### ISSUE TITLE
Issues w/ your CDN

### ISSUE THREAD

**Issue by fuzzysignal** [craftcms/cms#2678]
### Description

There seem to be issues at some of the CDN's for us ... seems to be related to certificate issues. 
craftcmsassets.craftcdn.com
download.craftcdn.com

### Steps to reproduce

1.  Attempt to upgrade our v 2.x CMS installs 
2. Load your website (CSS / Images etc) are broken

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by narration-sd** [comment]
@fuzzysignal  you're a little brief here for understanding, but have you tried clearing Craft caches and re-indexing Assets, both from the control panel, after the update?  Sometimes this is needed....

**Comment by fuzzysignal** [comment]
@narration-sd 

Thanks.  It looks like a firewall rule on our end starting blocking craft's cdn servers.
