### ISSUE TITLE
Real-time collaborative editing

### ISSUE THREAD

**Issue by nexflo** [craftcms/cms#2679]
Multi-user auditing of the CMS should be possible. Ideally realtime google docs like editing, as a first step locking documents so one knows someone else is editing that entry.

**Comment by lukeholder** [comment]
Good idea. Check out https://github.com/marionnewlevant/craft-snitch in the meantime.

**Comment by brandonkelly** [comment]
Warning users when someone else is editing the entry is covered by #824.
