### ISSUE TITLE
in a plugin, UserPhoto url not available from its Asset

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#2684]
### Description
In line 954 of User.php, you put a deprecation up that instructs to get user photos urls by calling getUrl() on their Asset, which seems entirely sensible.

However, this fails, because UserPhoto assets have no url set, and flag this by coding false in hasUrl. This results in a null url. For the same reason, an alternative call AssetsService::getAssetUrl() returns only the folder/filename tail end of what would be a proper url.

I have an Asset id, and I need to get the image url for it. getUrl on the Asset found by getAssetById() feels good composable semantics as a solution, if getAssetUrl seems equivalent.  Both work already for normal assets -- just not for User::photoId.

Is there something I missed, or is this a feature that was intended but not yet implemented?  A plugin release date wishes it could know ;)

### Steps to reproduce

1. As above
2.

### Additional info

Craft 3.0.0.2

**Comment by narration-sd** [comment]
A little more information. The underlying problem here is that am picking up this image as it's used in photoId  of user -- which was the original intent  of the message I quoted above in the code.

If I've used the same image as a normal Asset photo, I get a different id for it -- and this one does produce a proper url.

So the need here is to provide a way to get a workable url for the Asset id passed in a User object. It would be quite desirable if this was the original image rather than the downsized (I think) one in cp_resources, so that the widest range of end sizing and/or transforms could be applied to it.

**Comment by brandonkelly** [comment]
Does your User Photos asset volume have a base URL set?

**Comment by andris-sevcenko** [comment]
Also, is that a public volume with URLs enabled?

**Comment by narration-sd** [comment]
Well, doh, to quote someone ...to completely forget my responsibilities to set this up...

It takes both of the things you fellows  say - and then even the form I actually need,  `getAssets()->getAssetUrl($asset, $transform, true)` works fine. 

Nice for some maybe if that form shows up also in the deprecate notice? 

And we will not speak of the long and merry chase I led myself into, ending far down into the depths of flysystem, because for a while I was looking at the wrong server, this Saturday afternoon.

Here in any case is a reward -- a visible-size version of that late afternoon, wind-riffled yang and yin moment, on the Rhine, in Basel: https://lv.narrationsd.com/resources/images/userphotos/4sp-admin/avatar200.jpg
