### ISSUE TITLE
Variable "CraftClient" does not exist

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/cms#2686]
### Description

After updating to the latest version of Craft (3.0.1) the dashboard is throwing an error:

`Variable "CraftClient" does not exist`

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/24975058/38354481-ab56b196-38b1-11e8-8236-4b32c78f2c31.png">

### Additional info

- Craft version: 3.0.1
- PHP version: 7.2.4

**Comment by mudechs** [comment]
Same issue here.

Craft version: 3.0.1
PHP version: 7.1.12

**Comment by angrybrad** [comment]
For anyone running into this, can you try clearing your `craft/storage/runtime/compiled_templates` folder and see if that helps?  If not, can you check and see if you have [opcache](https://secure.php.net/manual/en/book.opcache.php) or any other PHP byte level caching extensions installed on your box like APC?

**Comment by brandonkelly** [comment]
Starting in the next release, Craft will make sure all compiled templates are cleared out whenever Craft or a plugin is updated, to guard against this sort of thing. (7c1b32a85652c360ef99e94bc94d6303c0aa0f91)
