### ISSUE TITLE
Error saving entries of type single from frontend ajax request

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#2687]
### Description
Single `Entries` created in the CP don't have an `authorId` for whatever reasons. When you are trying to save such a single entry with an `$authorId` is removed in the `beforeSave` function

    // Section type-specific stuff
    if ($section->type == Section::TYPE_SINGLE) {
        $this->authorId = null;
        $this->expiryDate = null;
    }

So far no problem, but when you send an ajax request the controller does the following

    if ($request->getAcceptsJson()) { 
        ......
        $return['authorUsername'] = $entry->getAuthor()->username; /<--- you'll receive an exception here
    }

### Steps to reproduce

1. Create a new section of type single in the CP, do something with the entry
2. Try to save the entry via frontend ajax request

### Steps to solve
 change [line 572 in EntriesController](https://github.com/craftcms/cms/blob/develop/src/controllers/EntriesController.php#L572) to

    $return['authorUsername'] = $entry->getAuthor()? $entry->getAuthor()->username : '';

### Additional info

- Craft version: Craft CMS 3.0.0-RC17

**Comment by brandonkelly** [comment]
Fixed for the next Craft 2 and Craft 3 releases. Thanks!
