### ISSUE TITLE
Change email permissions issue for custom user groups

### ISSUE THREAD

**Issue by shornuk** [craftcms/cms#2693]
### Description
Custom User group with the permission to "Change users' emails" doesn't appear to be working.

### Steps to reproduce

1. Create custom user group and assign permission to "Change users' emails" 
2. When editing a user, you enter the new email, it asks for password to confirm. Enter that, it refreshes as if it's worked but the email address is not updated. 

3. When doing the same as an Admin (full permission) it. works. 

### Additional info

- Craft version: 3.0.1
- PHP version: 7.0.29
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

Amazon S3	1.0.8
Asset Up	1.0.0-beta.2
Dumper	1.1.3
Expanded Singles	1.0.3
Field Manager	2.0.2
Position Fieldtype	1.0.10
Postmark	1.0.0-rc.1.2
Preparse Field	1.0.0
Redactor	1.1.0
SimpleMap	3.3.3
Super Table	2.0.5
Wordsmith	3.0.2

**Comment by brandonkelly** [comment]
Just tested and it does work, however something to be aware of is, if the “Verify email addresses?” setting is enabled in Settings → Users → Settings, then the new email will still need to be verified before it is fully saved on the user account. (The only time that setting isn’t enforced is if an admin is making the email change.)

**Comment by JustJarethB** [comment]
@brandonkelly is there any plausibility of adding a config variable to allow other users with the correct permissions to set passwords without needing verification? Say for example, a "Web Admin" that doesn't need updates/settings access but should be able to have full editorial permission on users and entries.

**Comment by brandonkelly** [comment]
@JustJarethB No, making it easy for users to set other users’ passwords would be enabling a very bad security practice.
