### ISSUE TITLE
Disabling a single section for a site returns an error

### ISSUE THREAD

**Issue by bartrylant** [craftcms/cms#2695]
### Description
If you have a single, and you already filled in some info in that single, and after that you tun that single off in the site settings, you get a 404 error.

### Steps to reproduce
1. Make a single section and tun it on for all sites (i.e. contactSection)
2. Enter some content in the single entry
3. Go to settings > sections > the single section (contactSection) and disable that section for the site you just entered content in
4. click save

### Additional info
- Craft version: Craft Pro 3.0.1
- PHP version: 7.1.16
- Database driver & version: MySQL 5.7.21

**Comment by brandonkelly** [comment]
Fixed for the next release. Thanks!
