### ISSUE TITLE
Craft ID not sending reset-password email

### ISSUE THREAD

**Issue by shuckster** [craftcms/cms#2696]
As title. Trying to upgrade from Solo to Pro.

**Comment by lukeholder** [comment]
I can't reproduce the issue, I receive the password reset email just fine.

Are you submitting an email address on file? Try signing up with that email address to see if it is available.

You can't make purchases from Craft ID just yet, only within the Craft control panel for now. We plan on adding the ability in the near future.

**Comment by shuckster** [comment]
When trying to sign-in I get an `Account is not activated` message, so I'm assuming the email exists in your database.

The error happens when I try signing-in with either my user-name or email address.

But I'll try signing-up again.

**Comment by shuckster** [comment]
Tried signing-up with previous details, and both email and user-name `have already been taken`.

**Comment by lukeholder** [comment]
send your email address to support@craftcms.com and we will send you a new password reset link.

**Comment by shuckster** [comment]
Thank you, done. :)

**Comment by brandonkelly** [comment]
FFR, Craft ID-related issues should be posted to https://github.com/pixelandtonic/craftnet/issues ;)
