### ISSUE TITLE
Add Hook on Completion of Matrix Save Field

### ISSUE THREAD

**Issue by zmetcalf** [craftcms/cms#2698]
### Description

I am looking to remove matrix blocks after an entry is saved in the CP, but the matrix block save actions are listening to the same event as me (EVENT_AFTER_SAVE_ELEMENT). What happens is that when I remove them, the matrix blocks from the original save attempt try to save at the same time throwing an error since they have been removed from the system. 

May I submit a pull request to add an event for when this method completes: https://github.com/craftcms/cms/blob/dca7cca889ee079528b3fbcdcacf97d7ef5f86a4/src/services/Matrix.php#L629 or is there a better way?

### Steps to reproduce

NA

### Additional info

- Craft version: 3.0.1
- PHP version: 7.1.8
- Database driver & version: MySQL 5.5.5
- Plugins & versions: 
NA

**Comment by brandonkelly** [comment]
I take it you figured out another way?

**Comment by zmetcalf** [comment]
@brandonkelly I may have gotten myself into a weird state with how I was building this out because the issue seems to cleared out. If it is a race condition that pops up again, I will submit a new request. Thank you for checking in and have a great week!
