### ISSUE TITLE
Searching multiple fields not working with space character

### ISSUE THREAD

**Issue by Coysh** [craftcms/cms#2702]
### Description
I'm searching using element-api endpoint, and it seems that searching the second field doesn't work if I include a space in the parameter.
This search works:
![image](https://user-images.githubusercontent.com/5764356/38428616-216f8eea-39b4-11e8-87fa-c1ba54d3b0b0.png)
This search **does not** work:
![image](https://user-images.githubusercontent.com/5764356/38428647-3230f4a8-39b4-11e8-9ea2-be06ce4ad896.png)

If I take out searching the title: in the search query, and try searching 'chris d', I get the correct response.
I have defaultSearchTermOptions (subLeft/subRight) set to true

```
use craft\elements\Entry;
use craft\helpers\UrlHelper;
return [
	'endpoints' => [
		'api/search' => [
			'elementType' => Entry::class,
			'paginate' => false,
			'criteria' => [
				'section' => ['pages','newsAndViews'],
				'limit' => 9,
				'search' =>
					(Craft::$app->getRequest()->getParam('q')) ?
					'title:'.Craft::$app->getRequest()->getParam('q')
					.' OR '.
					'shortDescription:'.Craft::$app->getRequest()->getParam('q')
					: ''
			],
			'transformer' => function(Entry $entry) {
				return [
					'title' => $entry->title,
					'description' => $entry->shortDescription,
					'url' => $entry->url,
					'searchUrl' => '/search?q=' . Craft::$app->getRequest()->getParam('q'),
				];
			},
		]
	]
];
```

### Steps to reproduce

1. Create endpoint that searched two fields
2. Try searching something on the second field with a space

### Additional info

- Craft version: 3.0.1
- PHP version: 7.2.0
- Database driver & version: MySQL 5.7.21

**Comment by brandonkelly** [comment]
If there’s a chance there will be spaces in the search term, you just need to wrap the term in quotes.

```php
'search' => ($q = Craft::$app->request->getParam('q'))
    ? "title:\"{$q}\" OR shortDescription:\"{$q}\""
    : '';
```

**Comment by Coysh** [comment]
@brandonkelly Thanks Brandon. Easy work 👍
