### ISSUE TITLE
Bug when pushing a job onto the queue

### ISSUE THREAD

**Issue by putyourlightson** [craftcms/cms#2704]
### Description

Getting the following error when pushing a job onto the queue.

```
An Error occurred while handling another error:
TypeError: Return value of craft\web\Response::getContentType() must be of the type string, null returned in /Users/ben/Sites/craft3/vendor/craftcms/cms/src/web/Response.php:54
```

And I see the incorrect type returned in the code [here](https://github.com/craftcms/cms/blob/3.0.1/src/web/Response.php#L54).

### Additional info

- Craft version: 3.0.1

**Comment by brandonkelly** [comment]
Fixed for the next release, thanks!

**Comment by putyourlightson** [comment]
Thank you!
