### ISSUE TITLE
Allow symfony/*:^4.0 packages

### ISSUE THREAD

**Issue by ostark** [craftcms/cms#2707]
### Description

Craft does not support Plugins with `symfony/*:^4.0` dependencies, as it depends on `composer/composer:~1.5.2` and this package depends on:

```
        "symfony/console": "^2.7 || ^3.0",
        "symfony/finder": "^2.7 || ^3.0",
        "symfony/process": "^2.7 || ^3.0",
        "symfony/filesystem": "^2.7 || ^3.0",
```

In `composer/composer:1.6.` they opened the version constraint to ^4.0:
https://github.com/composer/composer/commit/3a491a9b340b8f5658e5f83a217a93ad156a0a1a#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

AFAIK it's safe to upgrade as there are no API changes from 3.4 to 4.0. I tried it locally without any issues.

**Comment by brandonkelly** [comment]
If anyone’s going to follow SemVer it’ll be Composer :)

**Comment by ostark** [comment]
Thanks
