### ISSUE TITLE
rotateImagesOnUploadByExifData is not respected when uploading images

### ISSUE THREAD

**Issue by aelvan** [craftcms/cms#2709]
### Description
When uploading images that have rotation exif data, the image is not rotated, even if `rotateImagesOnUploadByExifData` is set to `true` in the config.

In fact, as far as I can tell, [`cleanImage` in `services/Images.php`](https://github.com/craftcms/cms/blob/develop/src/services/Images.php#L278) is only run when [`replaceAssetFile` in `services/Assets.php`](https://github.com/craftcms/cms/blob/develop/src/services/Assets.php#L144) is triggered. If I upload and image, and then replace the file with the same one, it works as expected; the image is rotated on upload.
 
`cleanImage` also contains code to sanitize SVGs, so should probably be run on all uploads.

### Steps to reproduce

1. Set `'rotateImagesOnUploadByExifData' => true` in general.php.
2. Upload an image with exif rotation data (attached is an example).
3. Observe that the thumbnail shown in Assets, is not rotated. 

### Additional info

- Craft version: 3.0.1
- PHP version: 7.0.27
- Database driver & version: MySQL 5.6.38
- Plugins & versions: -

![dd9763cc35b2](https://user-images.githubusercontent.com/2675644/38468879-6c493896-3b4c-11e8-9827-dd9763cc35b2.jpg)

**Comment by mrtpain** [comment]
+1 - same issue on version 2.6.3015 except my setting is set to false and rotation still occurs.
