### ISSUE TITLE
Move ArrayHelper::toArray deprecation error inside a conditional

### ISSUE THREAD

**Issue by nateiler** [craftcms/cms#2711]
https://github.com/craftcms/cms/blob/b82e93be8dccdd26d3f1e105c7f75ee3c38d9d1e/src/helpers/ArrayHelper.php#L33

Technically Yii's `ArrayHelper::toArray` accepts a string so it only seems fitting that this deprecation should only be thrown if your custom string criteria is met.

**Comment by brandonkelly** [comment]
Good point. Changed for the next release.
