### ISSUE TITLE
ID criteria on eager-loaded queries is ignored

### ISSUE THREAD

**Issue by rungta** [craftcms/cms#2717]
### Description

Eager-loaded elements [support custom parameters][1] such as `authorId` and `kind`. However, this does not appear to work for the `id` criteria.

[1]: https://docs.craftcms.com/v2/templating/eager-loading-elements.html#defining-custom-parameters-on-eager-loaded-elements

### Steps to reproduce

1. Create an Entries field called `related`.
2. Add some elements to an entry with this field.
3. Query for this entry and try to eager-load the `related` field, like so:
```
craft.entries({
  section: 'news',
  with: [
    ['related', { id: 9999999 }]
  ]
})
```
4. The `related` field on the entries returned should be empty arrays or contain only one element with the matching `9999999` id, if it had been added to the field. However, the `related` field arrays are returned unchanged.

### Additional info

- Craft version: 2.6.3015
- PHP version: 5.5.38
- Database driver & version: MySQL 5.7.17
- Plugins & versions: None

**Comment by brandonkelly** [comment]
Fixed for the next Craft 2 and Craft 3 releases. Thanks!
