### ISSUE TITLE
Clear Caches utility does not clear template caches

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#2720]
### Description
Since updating to 3.0.2, deleting template caches via the Clear Caches utility tool in the CP does not actually delete the template caches.

There are no errors, and the `clear-caches-perform-action` action returns `{"success":true}`, as expected. However, no rows are deleted in the `templatecaches` database tables.

When saving an element, appropriate template caches are cleared as expected.

I've tested the Clear Caches tool on the same Craft install using both 3.0.1 and 3.0.2, and it works on the former, but not the latter.

### Steps to reproduce

1. Clear template caches using the tool in the Utilities section
2. Confirm that no rows have been deleted from the templatecaches database table

### Additional info

- Craft version: 3.0.2
- PHP version: 7.0.14
- Database driver & version: MySQL 5.6.34
- Plugins & versions:

**Comment by brandonkelly** [comment]
Fixed for the next release, thanks!
