### ISSUE TITLE
Routes containing a dot created in the CP won’t work

### ISSUE THREAD

**Issue by tpmatthes** [craftcms/cms#2721]
### Description

First of all, congrats on the launch of Craft 3! 🎉 I’m excited to use it in production.

I’m currently migrating a big website to Craft 3. In Craft 2.5 I’ve created a custom route in the CP for dynamic rss feeds. Each category in a blog has its own feed. It looks like this:

![craft 3 cp route bug](https://user-images.githubusercontent.com/30212990/38607180-4210b350-3d78-11e8-9c32-c49fbe9f7aad.png)

However, if I load a url like `example.com/blog/feeds/test.rss`, Craft shows this error message:

```
HTTP 404 – Not Found – yii\web\NotFoundHttpException
Template not found: blog/feeds/test.rss
```

It seems like Craft 3 doesn’t trigger the dynamic route at all. Do I need to escape the dot? If I remove the dot from the route, it works. Both routes work just fine with Craft 2.5.

### Steps to reproduce

1. Navigate to “Settings > Routes” in the CP
2. Create a new route: `(slug).rss` -> `test.twig`
3. Create an empty template and name it `test.twig`
4. Navigate to `/test.rss` in your browser

### Additional info

- Craft version: 3.0.2 (Pro)
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Plugins & versions: Redactor 1.1.0

**Comment by brandonkelly** [comment]
Fixed for the next release, thanks!
