### ISSUE TITLE
Unable to resolve the request: elements/get-editor

### ISSUE THREAD

**Issue by alexanderhofstaetter** [craftcms/cms#2726]
### Description

After update from craft v2 to v3 I have some errors when using the backend with some ajax requests. i cannot use some backend feautures which require ajax. It says in red "An unknown error occurred".

In my browser I see that /index.php?p=admin/actions/elements/get-editor Failed to load resource: the server responded with a status of 500 ().

In my log file I see the following:

```
2018-04-11 17:29:45 [81.217.205.174][1][-][error][yii\base\InvalidRouteException] yii\base\InvalidRouteException: Unable to resolve the request: elements/get-editor in /var/www/vhosts/domain.com/vendor/yiisoft/yii2/base/Controller.php:128
Stack trace:
#0 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/web/Controller.php(74): yii\base\Controller->runAction('get-editor', Array)
#1 /var/www/vhosts/domain.com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('get-editor', Array)
#2 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/web/Application.php(244): yii\base\Module->runAction('elements/get-ed...', Array)
#3 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/web/Application.php(452): craft\web\Application->runAction('elements/get-ed...', Array)
#4 /var/www/vhosts/domain.com/vendor/craftcms/cms/src/web/Application.php(228): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#5 /var/www/vhosts/domain.com/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#6 /var/www/vhosts/domain.com/web/index.php(21): yii\base\Application->run()
#7 {main}
2018-04-11 17:29:45 [81.217.205.174][1][-][info][application] $_GET = [
    'p' => 'admin/actions/elements/get-editor'
]
```

### Additional info

- Craft version: Craft Solo 3.0.2
- PHP version: PHP 7.2.4
- Database: MySQL 5.5.56

**Comment by brandonkelly** [comment]
Strange – the closest action I can find is `elements/get-editor-html`, but nothing in the JavaScript is trying to call just `elements/get-editor`. Do you have any plugins installed?

**Comment by alexanderhofstaetter** [comment]
Its holding part off the backend from loading, i cannot edit my content :(. No, i haven´t installed a single plugin!

**Comment by brandonkelly** [comment]
Did you install Craft 3 via Composer or the zip file?

- If Composer, can you try deleting your `vendor/` folder and run `composer install`?

- If zip, try re-downloading, delete your `vendor/` folder, and replace with the new zip’s `vendor/` folder.

Either way, then delete the `web/cpresources/` folder. See if that helps.

**Comment by alexanderhofstaetter** [comment]
I already did all this things, i deleted all caches also and my browser cache too. `rm -rf` of `vendor` and `composer install` didn´t work. The problem persists.

I get this error when i want to edit an image in my an entry. I try to double click on it but the image edit options does not popup, instead I get the error "An unknown error occurred".

Please see this chrome JS stacktrace:

![photo](https://user-images.githubusercontent.com/6820505/38643598-ee8db2e4-3ddd-11e8-99a9-d49d5ab372ba.png)

**Comment by brandonkelly** [comment]
Can you click on the red `index.php` and see where it's coming from?

**Comment by alexanderhofstaetter** [comment]
Unfortunately clicking on the `index.php` does not show any more informations. On hover it says only `domain.com/index.php?p=admin/actions/elements/get-editor`

**Comment by brandonkelly** [comment]
What page are you on when this happens? Does it happen immediately or only after you try to perform an action on the page? (What action?)

Also, what browser & OS are you using?

**Comment by alexanderhofstaetter** [comment]
i wrote you an email to your mail address shown on your github profile.

**Comment by brandonkelly** [comment]
Followed up there.
