### ISSUE TITLE
[Bug?] Categories field not refreshing after category source change.

### ISSUE THREAD

**Issue by AmericanTrails** [craftcms/cms#2727]
### Description

Categories field not refreshing after category source change.

### Steps to reproduce

1. created a category field, set to a particular category source
2. later changed the category source to a different group. 

In data entry, the categories from the first group are still displayed. Unable to get it to refresh.. tried the usual (log out, clear cache, curse, etc.). 

### Additional info

- Craft version: 3.0.1 (Pro)
- PHP version: 7.0.28
- Database driver & version: MySQL 5.7.21
- Image driver & version: Imagick 3.4.0RC6 (ImageMagick 6.8.9-9)
- Plugins & versions: 
    - Redactor 1.1.0

**Comment by AmericanTrails** [comment]
Oh, well, never mind. I had a field by the same name in a matrix and was editing the wrong one. Sorry to waste your time.

**Comment by brandonkelly** [comment]
No worries! Glad you got it sorted.
