### ISSUE TITLE
Weight rates saving to the wrong shipping category

### ISSUE THREAD

**Issue by hellokv** [craftcms/cms#2729]
### Description

When configuring shipping rules, the weight rate that is entered for one category appears for a different category after the shipping rule is saved.

### Steps to reproduce

1. Create 2 shipping categories (A and B)
2. Create a shipping method
2. Create a shipping rule
3. Go to the Costs tab for the shipping rule
4. Enter a Weight Rate for Category B and Save

### Additional info

- Craft version: Craft 3
- PHP version: 7.0.28
- Database driver & version: MySQL 5.7.21
- Plugins & versions:
Algolia	1.0.0
Amazon S3	1.0.8
Asset Rev	6.0.0
Calendar	2.0.0-beta.9
Certificates	1.0.0
Craft Commerce	dev-develop
Environment Label	3.1.3
Field Manager	2.0.2
Flat Categories	2.0.0
Forms	dev-master
Freeform Pro	dev-master
Geo Cookie	1.1.1
Inlin	2.0.0
Inventory	1.0.0
Redactor	1.1.0
Sidebar Toggle	2.0.0
SimpleSentry	1.0.0
Super Table	2.0.5
Taxes	1.0.0
Twig Perversion	2.0.3

**Comment by angrybrad** [comment]
Seems like a Commerce issue instead of a Craft one.  Can you post on the Commerce repo? https://github.com/craftcms/commerce/issues
