### ISSUE TITLE
One more click to download a backup database than in Craft 2

### ISSUE THREAD

**Issue by JayBox325** [craftcms/cms#2732]
### Description
The process for downloading a Craft DB in the admin used to be `Setting » Download Backup`, but now it's `Utilities » Database Backup » Backup`.

It's only one more click and I realise it's to do with being able to backup a database into another virtual location and locally, but it's still an extra click.

Feel free to discard this ticket if it's too precious. 😂

**Comment by brandonkelly** [comment]
Actually it’s the same number of clicks:

| | Craft 2 | Craft 3 |
| - | - | - |
| 1 | Settings | Utilities |
| 2 | Clear Caches _(opens HUD)_ | Clear Caches _(opens new page)_ |
| 3 | “Go” button | “Clear Caches” button |
