### ISSUE TITLE
Last Update in Plugin store shows NaN/NaN/NaN

### ISSUE THREAD

**Issue by joshua-martin** [craftcms/cms#2733]
### Description

Couldn't find this as an active issue already—When you're in the plugin store and you click on one of the plugins, the Last update value shows **NaN/NaN/NaN**.

![screen shot 2018-04-12 at 13 50 53](https://user-images.githubusercontent.com/1694957/38678311-88b130e2-3e58-11e8-9379-cdd928dd939b.png)

### Additional info

- Craft version: 3.0.2

**Comment by brandonkelly** [comment]
Not able to reproduce this. What browser/OS are you on?

**Comment by joshua-martin** [comment]
Sorry, should've added those—Safari Version 11.0.2 in macOS High Sierra 10.13.2. It does work in Firefox and Chrome on the same machine.

**Comment by brandonkelly** [comment]
Thanks! Able to reproduce in Safari.
