### ISSUE TITLE
Only a enabled plugin can be installed

### ISSUE THREAD

**Issue by MDXDave** [craftcms/cms#2734]
### Description
If a plugin is disabled, you are not able to uninstall it. You have to enable it before you can uninstall it.

![image](https://user-images.githubusercontent.com/6099976/38679081-1968f5de-3e63-11e8-92c7-dad11064acf0.png)
![image](https://user-images.githubusercontent.com/6099976/38679092-1f61ac10-3e63-11e8-8f8b-bbbbc7ecee05.png)

### Steps to reproduce

1. Disable a plugin
2. try to uninstall it
3. enable it
4. uninstall it

### Additional info

- Craft version: 3.0.2 Solo
- PHP version: 7.2.4

**Comment by brandonkelly** [comment]
Yeah this had to be the case because a plugin is actually responsible for uninstalling itself.
