### ISSUE TITLE
Users can self-activate by resetting their password

### ISSUE THREAD

**Issue by Harry-Harrison** [craftcms/cms#2735]
### Description
I'm building a site that has public registration enabled, the registration works and marks the user as "Unverified". If that same user then uses the "forgotten password" form (clone from the docs) then that users account is marked as activated.

I think might be a naming issue. Is "Activation" actually just email verification?

### Steps to reproduce

1. Use the public registration form to create a new user
2. Then use that same email address or username on the forgotten password form

### Additional info

- Craft version: 3.0.2
- PHP version: 7.2.4
- Database driver & version: MySQL 5.7.21
- Plugins & versions:
  - Amazon S3 | 1.0.8
  - Element Map | 1.0.2
  - FeedMe 3.0.0-beta.4

**Comment by brandonkelly** [comment]
> I think might be a naming issue. Is "Activation" actually just email verification?

Correct. And going through the Forgot Password process is a form of email verification.
