### ISSUE TITLE
Deleting template caches doesn't delete templates caches

### ISSUE THREAD

**Issue by nilsenpaul** [craftcms/cms#2736]
### Description
When trying to clear the template caches from the utilities section, they do not get removed from the templatecaches table. By the looks of it, that is because:

services/TemplateCaches.php, line 637 sets `$this->_deletedAllCaches` to true, after which

services/TemplateCaches.php, line 394 checks if `$this->_deletedAllCaches` is true, returns false and does not remove caches.

What am I missing?

### Steps to reproduce

1. Create a row in templatecaches table
2. Try to empty that table through the admin

### Additional info

- Craft version: 3.0.2

**Comment by domstubbs** [comment]
I’m seeing the same thing, clearing caches doesn’t seem to have any impact on the templatecaches table (3.0.2 for me as well).

**Comment by brandonkelly** [comment]
Duplicate of #2720, fixed for the next release.
