### ISSUE TITLE
[FR] Allow the `defaultSearchTermOptions` config setting to merge with the default array

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#2737]
The default `defaultSearchTermOptions` value is this...

    'defaultSearchTermOptions' => [
        'attribute' => null,
        'exact' => false,
        'exclude' => false,
        'subLeft' => false,
        'subRight' => true
    ],

The only one I want to change is `subLeft`. But if I add this to my config file...

    'defaultSearchTermOptions' => ['subLeft' => true]

... it breaks the rest of the values in that array.

Can we have it so the config-specified settings get _merged_ with the default settings? I'd rather not re-declare all five array keys when I only need to change a single one.

**Comment by lindseydiloreto** [comment]
Discussed further on Slack...

<img width="1054" alt="possible solution?" src="https://user-images.githubusercontent.com/5309692/38694493-a72b1278-3e3e-11e8-84c3-9830b9aa72bf.png">

**Comment by brandonkelly** [comment]
We can’t merge this one setting without merging all arrays, and that's not always going to be desired.

**Comment by lindseydiloreto** [comment]
So we have to recreate the entire 5 key array in our config settings, even if we're just changing a single value? That's unfortunate.

Other than "mass merging", is there any other way to address this shortcoming? In that Slack conversation, we discussed the possibility of `defaultSearchTermOptions` drawing from its default values if any of the array values are `null`.

That would be something that happens when _the search is executed_, not when the config array is initially compiled.

**Comment by angrybrad** [comment]
Not saying it's the best solution, but we addressed this with the [allowedFileExtensions](https://docs.craftcms.com/api/v3/craft-config-generalconfig.html#$allowedFileExtensions-detail) config setting by adding the [extraAllowedFileExtensions](https://docs.craftcms.com/api/v3/craft-config-generalconfig.html#$extraAllowedFileExtensions-detail) config setting that gets merged in.

It's much more pronounced there because there are so many items in the allowedFileExtensions setting that you'd need to duplicate.

**Comment by lindseydiloreto** [comment]
Hmm, that solution may be extreme for `defaultSearchTermOptions`. It makes sense for file extensions because there are so damn many of them (and who know what people will try to add).

It looks like `defaultSearchTermOptions` only comes into play once (okay twice) in a very narrow neighborhood...

https://github.com/craftcms/cms/blob/develop/src/services/Search.php#L155-L163

If possible, what I'm proposing is this...

1. Load the config settings for `defaultSearchTermOptions` around line 155.
2. Compare that to the Craft default version of the same array.
3. Fill in any `null` values with the Craft values.

It seems like a minor kludge, but it would be pretty well contained in the `filterElementIdsByQuery` method.

Thoughts?

**Comment by lindseydiloreto** [comment]
Actually, let me adjust my previous statement... a perfect place for that null-value comparison would be in the `SearchQuery` constructor!

https://github.com/craftcms/cms/blob/develop/src/search/SearchQuery.php#L49-L52

**Comment by brandonkelly** [comment]
I just made sure the default corresponding property values on `SearchQueryTerm` matched the config defaults (there was only one inconsistency), and now the default value is just an empty array. So you can just set the things you want to change.

**Comment by lindseydiloreto** [comment]
Brilliant, that should work perfectly! Thanks @brandonkelly 👍
