### ISSUE TITLE
Cyrillic in url when creating a new page

### ISSUE THREAD

**Issue by paveell** [craftcms/cms#2738]
Tell me why url translit does not work from Cyrillic when creating a new page?

When you enter the page name, url is generated, but in Cyrillic alphabet a must be in Latin.

Example url: уборка-квартир = uborka-kvartir (see screen)

![2018-04-12 21 25 47](https://user-images.githubusercontent.com/20890143/38696875-143a7494-3e99-11e8-99df-b5bfcccd73a0.png)

Thank you.

**Comment by angrybrad** [comment]
You need to set this to `true` in your `craft/config/genera.php` file: https://docs.craftcms.com/v2/config-settings.html#limitAutoSlugsToAscii
