### ISSUE TITLE
Missing Craft.eot file

### ISSUE THREAD

**Issue by jeffreyschmitz87** [craftcms/cms#2740]
When a person (not an admin account) logs into a Craft 3 multisite an `An unknown error occurred.
` fires on each page the person loads.

I've installed Sentry to figure out why the error shows on every page. Sentry gives the following error:
`yii\web\NotFoundHttpException`
`Template not found: cpresources/2dbc1074/fonts/Craft.eot`

### Steps to reproduce

1. Log in to a Craft multistite with any account that is not an admin account

### Additional info
- Craft version: Craft Pro 3.0.2
- PHP version: 7.1.14
- Database driver & version: MySQL 5.5.56

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next release.
