### ISSUE TITLE
“Translatable” icon on name input fields

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#2742]
What’s the idea with the “translatable” icon added to all the name input fields in the CP (Section settings, User Group settings, etc.). Is it meant to indicate that these are translatable using static translations?

If yes, then it is missing on the “System Name” field. But I think I’d rather see it not being used to mark static translation prospects, as it makes the icon’s intention less clear. There are also many places in the CP where it’s currently not even possible to use the icon for this, e.g., for tab names in the FLD or input fields that open with a browser dialog.

**Comment by brandonkelly** [comment]
They indicate that the custom field’s Translation Method is set to something besides “None”.

**Comment by carlcs** [comment]
@brandonkelly I am not talking about custom fields

<img width="547" alt="Name field translatable" src="https://user-images.githubusercontent.com/7516543/38825878-58bf7ffc-41ae-11e8-90e2-75294a15ed62.png">

**Comment by brandonkelly** [comment]
Ah gotcha. I don’t remember the thinking behind those; maybe to indicate static translations. But we haven’t been consistent about it, and some fields that don’t and shouldn’t support static translations had the icon too. Just removed the icons everywhere, except for things that can be translated directly in the CP.

**Comment by narration-sd** [comment]
I know I shouldn't hijack, but this conversation makes me think of something related that has long felt important. I know I've made an issue for it before.

The request is that you clear up the Advanced items that show up on a field like Assets, when you have translatable invoked.  They say:

**Comment by narration-sd** [comment]
Ah -- that previous  request/issue/enhancement-you-labelled-it is #1968 .

It's discussed about Assets there, but I rather suspect this obscure Advanced settings language shows up on at least several other Fields....
