### ISSUE TITLE
Opening Modal: Uncaught Garnish is already defined!

### ISSUE THREAD

**Issue by chanwhab** [craftcms/cms#2745]
### Description
Modal: e.g. add a category in category field

Opening first modal will result in erorr.
“Uncaught Garnish is already defined!”

Opening second modal will result in error:
Uncaught TypeError: Cannot read property 'menu' of undefined
Uncaught TypeError: Cannot read property 'getSelectedElements' of null
[Bug Video](https://streamable.com/sdxsq)

### Steps to reproduce

1. Open a first modal
2. Open a second modal

### Additional info

- Craft version: 3.0.2
- PHP version: 7.2.1
- Database driver & version:  MySQL 5.6.34
- Plugins & versions:
Amazon S3	1.0.8
CP Field Inspect	1.0.4
Craft Commerce	2.0.0-beta.2
Element API	2.5.2
Imgix	2.0.3
Importable	1.0.1
Instant Analytics	1.0.6
Logs	3.0.0
Minify	1.2.8
Redactor	1.1.0
SEOmatic	3.0.0-beta.22
Social	2.0.0-beta.5
Stripe for Craft Commerce	1.0.1

**Comment by brandonkelly** [comment]
Is this only happening for Commerce variants? Or are you seeing similar behavior in other areas of the Control Panel?

**Comment by angrybrad** [comment]
This was resolved in support by setting https://docs.craftcms.com/api/v3/craft-config-generalconfig.html#$securityKey-detail to a consistent value for all server in a load-balanced environment.
