### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry

### ISSUE THREAD

**Issue by ewe1991** [craftcms/cms#2747]
### Description
Updated Craft 3.0.1 to 3.0.2 

Now getting the error below for anything I try to add/edit/save.
`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry  '54' for key 'PRIMARY'`

### Steps to reproduce

1. Updated Craft 3.0.1 to 3.0.2 via CMS
2. Deleted a volume 
3. Tried to edit/save etc get the above error.  

### Errors 
No deprecation errors to report!

### Additional info

Laravel Valet 

- Craft version: 3.0.2
- PHP version: 7.2.3
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Redactor v 1.1.0  & SimpleMaps v3.3.3

**Comment by brandonkelly** [comment]
Can you send a database backup to support@craftcms.com with specific steps to reproduce the error? Thanks!
