### ISSUE TITLE
Debug toolbar obscures last plugin action dropdown

### ISSUE THREAD

**Issue by johnwbaxter** [craftcms/cms#2750]
### Description

I have some plugins installed on a site and i have one that i disabled whilst debugging something. I'd like to enable it, but the admin debug toolbar obscures it (see attached)

<img width="1695" alt="screen shot 2018-04-16 at 14 00 32" src="https://user-images.githubusercontent.com/338729/38810653-581e12ae-417f-11e8-844d-696f0d6b21a9.png">

Obviously disabling the toolbar solves this!

### Steps to reproduce

1. Enable admin debug toolbar
2. Have a bunch of plugins installed and disable one of them
3. Try and click menu option to re-enable plugin

### Additional info

- Craft version: 3.0.2
- PHP version: 7.0.0
- Database driver & version: MySQL 5.5
- Plugins & versions: SEOMatic - 3.0.0-beta.21 (but i'm sure it happens with any)

**Comment by brandonkelly** [comment]
No longer an issue due to 2d4196a972af21e70952875a4da5971c8d56fcb9 (#2744).
