### ISSUE TITLE
Changing password sets language to German?

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/cms#2751]
### Description

I was going through a number of installations and updating my password from the 'My Account' section, after saving my password on a couple of installations it also switched my preferred language to German. 

Weird one, I can't reproduce it but it happened twice and somebody else confirmed on Slack that it had happened to them too.

### Steps to reproduce

1. Save new password from the 'My Account' section

### Additional info

- Craft version: 3.0.2
- PHP version: 7.2.4
- Database driver & version: MySQL

**Comment by janhenckens** [comment]
I had this happen 2 weeks ago on a new project too, with the site going from English to German as well.

Will try to reproduce tonight with a fresh install.

**Comment by brandonkelly** [comment]
This should have been fixed in 3.0.0 (GA) via 2928951ef6e7a2e5bfc623b60a4d56314beb1a5d. Let me know if you see it on a newer release.
