### ISSUE TITLE
Renaming site handle fails

### ISSUE THREAD

**Issue by acehead** [craftcms/cms#2756]
### Description
Error occured when changing site handle 

### Steps to reproduce

1. Change site handle and press save
2. An internal server error occurred message is shown

### Additional info

- Craft version: Craft Pro 3.0.1
- PHP version: 7.1.12
- Database driver & version: PostgreSQL 9.6.6
- Plugins & versions:

**Comment by acehead** [comment]
Problem disappeared after redeployment

**Comment by brandonkelly** [comment]
Strange, but glad it’s working now!

**Comment by acehead** [comment]
It could be related to the fact that site handle in an index.php was not updated appropriately

**Comment by brandonkelly** [comment]
Ah yes, that could be it, if you have a `CRAFT_SITE` constant. That’s actually no longer needed 99% of the time, as Craft is capable of determining the requested site just be looking at the requested URL now.
