### ISSUE TITLE
Show the package URL in the plugin store

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#2757]
### Description
WIth composer being such a core part of Craft 3, I'd like to see the package / command to install the plugin shown in the plugin store. When running Craft locally, I frequently get gateway timeout errors and the general experience of installing and updating plugins through the control panel feels unreliable. If the command / URL to plugin packages was shown in the Plugin Store, I could install them via the command line and eliminate the problems.

### Additional info

- Craft version: 3.0.2
- PHP version: 7.1.15

**Comment by brandonkelly** [comment]
Installing plugins via the terminal would require the plugin to be registered with Packagist – something that isn’t actually required. Technically we could try to figure that out, but our goal is to fix those timeout errors in the first place, so I’d rather just focus on that. In the meantime if you must use the terminal, you should be able to find the Composer command in the plugin’s documentation, which the store does link to.

**Comment by carlcs** [comment]
Now that package names are shown on https://plugins.craftcms.com, can we please have them in the CP’s plugin store as well?
