### ISSUE TITLE
[Craft 2] Redactor formatting breaks Edit Entry HUD on Edge

### ISSUE THREAD

**Issue by joe-thom** [craftcms/cms#2758]
### Description
Adding any formatting tags (h1, h2, h3) to a redactor 2 rich text field breaks the edit entry HUD and clears any content in following rich text fields on entry save in Edge.

### Steps to reproduce
1. Open craft 2 in Edge
2. Add formatting to a redactor rich text field
3. HUD should break in any following content blocks
4. Save entry

### Additional info
- Craft version: 2.6.3015
- PHP version: 7.1.6
- Plugins & versions: Redactor II Version 2.11

**Comment by brandonkelly** [comment]
Please post Redactor issues to https://github.com/craftcms/redactor/issues - thanks!
