### ISSUE TITLE
Wrong time in entry for multisite

### ISSUE THREAD

**Issue by jeffreyschmitz87** [craftcms/cms#2761]
### Description

When you create an entry in a multisite, save it and the timezone in the general settings is not UTC, the time is wrong when you edit the entry.

### Steps to reproduce

1. Have a multisite
2. Set timezone to `UTC+2 (CEST) – Europe/Amsterdam`
3. Create an entry and hit save
4. Open the saved entry and the time is the current time -2 hours
5. Save the entry again with the wrong time and open it again. The time is -2 hours again

### Additional info

- Craft version: 3.0.2
- PHP version: 7.0.23
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
I’m not able to reproduce this on my end. Any chance we can get admin/FTP access to your site? If so please reach us at support@craftcms.com and we can help you from there.
