### ISSUE TITLE
User rights management in general

### ISSUE THREAD

**Issue by virtucol** [craftcms/cms#2766]
Hi there!

Basically: Thumbs up for this excellent CMS, including out of the box features competitors still dream of! And probably this isn't really a new "issue", rather than an(other) request (by my side) for a pretty exigent _–but in Craft unfortunately so far still missing–_ "feature", which is:

- **A clearly more differantiated user rights managent.**

I think there is even no need in mentioning examples on this one...

Most urgently I would need to – which should suffice in most project cases:

1. limit user access to user-specific asset source subfolders only
2. limit user rights to edit specific entry types (views) only

Alternatively: Why not split right-settings up into the very smallest common denominator – down onto a per-field level..!? ..but this could be too overdosed even..

Best regards, and thank you again for this (othervise) peace of art of a CMS!

-Hendrik-

EDIT: Sorry, I just re-wrote about your plans of implementing this in a future version.. So feel free to delete this one..

**Comment by brandonkelly** [comment]
Yeah these are covered by other issues, but we likely won’t get to them until we’ve had a chance to overhaul how permissions work (moving to an RBAC system). In the meantime, plugins can register their own permissions where needed.

Glad you’re liking Craft!
