### ISSUE TITLE
Unable to remove widgets.

### ISSUE THREAD

**Issue by noregt** [craftcms/cms#2769]
### Description

In the Dashboard, if you remove all widgets, it will reset them all and also add extra rows in the craft_widgets table. 

### Steps to reproduce

1. Remove all widgets
2. Go to another page, for instance content
3. Back to the dashboard, all widgets are back and extra rows are added in the db table

This happens for all users.

### Additional info

- Craft version: 3.0.3.1 (Pro)
- PHP version: 7.0.29
- Database driver & version: MySQL 5.5.59
- Image driver & version: Imagick 3.4.3 (ImageMagick 6.8.9-9)
- Plugins & versions: 
    - Contact Form 2.1.1
    - Contact Form Honeypot 1.0.2
    - Expanded Singles 1.0.3
    - Image Resizer 2.0.2
    - Redactor 1.1.0

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release.
