### ISSUE TITLE
When I try to add an Author column to my All Events listing (Solspace Calendar), I get an "unknown error".

### ISSUE THREAD

**Issue by vaughn-taylor** [craftcms/cms#2770]
### Description

When I try to add an Author column to my events listing (Solspace Calendar), I get an "unknown error". I cannot view events until I remove this column from the listing.

### Steps to reproduce

1. Calendar > Events > Click the cog that allows column management
2. Add "Author" column and click Ok.
3. Unknown error returned
4. Must remove the "Author" column before I can view the listing again

### Additional info

- Craft version: 3.0.3.1 (Pro)
- PHP version: 7.1.15
- Database driver & version: MySQL 5.5.5
- Image driver & version: GD 7.1.15
- Plugins & versions: 
    - Calendar 2.0.0-beta.9
    - Cookies 1.1.9
    - Easy Address Field 1.1.2
    - Element API 2.5.2
    - Redactor 1.1.0
    - Wordsmith 3.0.2

**Comment by brandonkelly** [comment]
This sounds like a Calendar bug? cc @kjmartens

**Comment by vaughn-taylor** [comment]
@kjmartens, I'm also getting "an unknown error occurred" when I perform a search in the list view of events in the CP.

**Comment by angrybrad** [comment]
This should probably be moved over to the Calendar repo, no? https://github.com/solspace/craft3-calendar/issues

**Comment by kjmartens** [comment]
I can duplicate this as well, and we'll fix for the next release. Thanks :)
