### ISSUE TITLE
Deleting compiled templates when migrating up can result in incorrect directory ownership

### ISSUE THREAD

**Issue by OscarBarrett** [craftcms/cms#2771]
### Description
[This change](https://github.com/craftcms/cms/commit/7c1b32a85652c360ef99e94bc94d6303c0aa0f91#diff-1075b2fa7eebd1c8e9fb3bbfff94ce61) deletes compiled templates when migrating up. Because `getCompiledTemplatesPath` creates the directory if it doesn't exist, performing the migration as a user other than the one running the php/web process can prevent Craft from being able to write to the directory later on.

One situation where this could easily happen is running craft within a docker container with a non-persistent storage directory and migrations are run before starting the php process.

The workaround is to correct the permissions after running migrate/up.

### Steps to reproduce

1. `rm -rf storage/runtime`
2. Run `./craft migrate/up --interactive=0` as root
3. Start the php process

### Additional info

- Craft version: 3.0.3.1
- PHP version: 7.2
- Database driver & version: MySQL 5.7
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
Thanks for reporting that! Going forward, Craft is no longer going to create directories in the process of clearing them, if that’s the only thing it needed to do with the directory.
