### ISSUE TITLE
Error in setting up Craft (only the first run)

### ISSUE THREAD

**Issue by nilsenpaul** [craftcms/cms#2774]
### Description
On installing a new Craft project, and running `./craft setup`, I encounter the following error:

`An error occurred while executing the "craft\migrations\Install migration: Unsupported DB driver value: '`

**If I run the setup again, with exactly the same values, it works and install migrations get executed.**

### Steps to reproduce

1. `composer create-project craftcms/craft .`
2. `./craft setup`, using a mysql database and root credentials and `nl` as the locale
3. Error occurs after entering locale

### Additional info

- Craft version: 3.0.3.1
- PHP version: 7.0.27-0+deb9u1 (cli)

**Comment by narration-sd** [comment]
Are you sure you had a dot-env file in place the first time? If it is missing, thus MySql isn't specified, I've seen recently that Craft will default to trying to run the Postgres driver, and give a message as you got. 

You're in a different place, because of the migration, but sounds similar...

**Comment by nilsenpaul** [comment]
> Are you sure you had a dot-env file in place the first time? If it is missing, thus MySql isn't specified, I've seen recently that Craft will default to trying to run a Postgres driver, and give a message as you got.

I did not, but `./craft setup` creates the .env for you, lets you specify a db driver as a first step, and checks if a connection can be made.

**Comment by brandonkelly** [comment]
Fixed for the next release, thanks!
