### ISSUE TITLE
cpresources generated in wrong directory

### ISSUE THREAD

**Issue by retop** [craftcms/cms#2775]
### Description
Craft generates my cpresource folder in wrong directory resulting in missing js and css files in the control panel.
Folder gets generated in craft/cpresources instead of craft/web/cpresources.
This happened after an update from one of the RCs to 3.0.3.1
There is no modification of the $resourceBasePath in general.php

### Additional info

- Craft version: 3.0.3.1
- PHP version: 7.1.9
- Database driver & version: MySQL 5.7.19
- Plugins & versions:  
Contact Form  2.1.1
Guest Entries  2.1.3
Inventory 2.0.0
Redactor 1.0.1
Redirect plugin for Craft 3  1.0.13

**Comment by brandonkelly** [comment]
Glad you got it sorted! FYI, you generally shouldn’t even have to set `@web` yourself – Craft automatically sets it to the URL that points to the current `index.php` parent directory. So if the current request is pointing to `http://example.com/index.php`, by default `@web` will be set to `http://example.com/`.
