### ISSUE TITLE
No results on selecting entries from a user's field in a multisite installation

### ISSUE THREAD

**Issue by nilsenpaul** [craftcms/cms#2776]
### Description
If I add an entries field to the user settings, on a multisite installation, I get no results in the field's modal.

### Steps to reproduce

1. Create 2 sites
2. Create a section (channel) `locations`, don't propagate entries
3. Create one or more entries in the section
4. Create an entries field for users, select the `locations` section and don't make the field translatable (because why should you, users are the same for all sites)
4. Try to select any entries from this field for any user. Modal is empty.

### Additional info

- Craft version: 3.0.3.1

**Comment by brandonkelly** [comment]
This is probably expected behavior. Entries fields will only show entries for the site of the element you’re currently editing by default. And if it’s a non-localizable element type like Users, then that will be the primary site.

To fix this, in your Entires field settings, set the target site to the site that the section is enabled for.

**Comment by nilsenpaul** [comment]
Problem is, that the entries exist for all sites, not for a specific one. Each site has its own locations, and a user can be related to one or more entries within one site. That's not always the same site, though, so setting the target site will not fix my problem.

Could I programmatically create a relation between a user and any entry on any site?

**Comment by brandonkelly** [comment]
Currently there’s no way to set the site on a per-relation basis. And even if you could, there isn’t a way you could fetch all the related entries together in a single query.

If you allow multiple relations, and each relation is pointed at a different site, how would that look from the element query perspective, as each query can only select elements from one site at a time?

We could do it with multiple element queries, perhaps, and stitch the results together, but it wouldn’t be very performant.

How many sites do you have? Would it be impractical to just create multiple Entries fields, each pointed at a different site?

**Comment by nilsenpaul** [comment]
Brandon, I turned the whole thing around by giving the entries a user field, so I can select one or more users that have 'access' to a certain location entry. Works just fine, so please ignore this issue.
