### ISSUE TITLE
Preselect an asset after uploading it

### ISSUE THREAD

**Issue by matt-adigital** [craftcms/cms#2782]
Feature Request:

We've had a few clients mention this now but when an asset is uploaded within an entry, can the asset field popup window please jump down to it and have the row highlighted/selected so that they don't have to scroll down to find it or type in the search bar.

Clients are lazy and want everything done for them...

Thank you.

**Comment by brandonkelly** [comment]
This is already (partially) implemented – uploaded assets do get selected, but only if they are in view. So going to close this in favor of #2812, which is more of a bug report.
