### ISSUE TITLE
Can't save asset when focuspoint selected

### ISSUE THREAD

**Issue by Coysh** [craftcms/cms#2783]
### Description
This seemed to break recently, as we have set focus points on assets before.
When we try and save any asset, after selecting a focuspoint, I get the following error in an alert and the asset doesn't save. Saving the asset without selecting a focuspoint works.

```Argument 1 passed to craft\helpers\Assets::getFileKindByExtension() must be of the type string, null given, called in /home/forge/craft/vendor/craftcms/cms/src/elements/Asset.php on line 1215```

### Steps to reproduce

1. Edit an asset
2. Set a focus point
3. Save asset

### Additional info

- Craft version: 3.0.3
- PHP version: 7.2
- Database driver & version: mySQL
- Plugins & versions: ImageOptimize // Image Resizer (both latest)

**Comment by brandonkelly** [comment]
This was fixed in 3.0.3.1.
