### ISSUE TITLE
Thumbnail on Users field rendered twice

### ISSUE THREAD

**Issue by chasegiunta** [craftcms/cms#2785]
### Description
![image](https://user-images.githubusercontent.com/1377169/39087201-5418e6c4-4563-11e8-91b6-fda10f15e8a7.png)

![image](https://user-images.githubusercontent.com/1377169/39087305-a0c30f12-4564-11e8-92b7-528e9b209dda.png)

Looking at inspector, looks like the actual `img` tag is being output twice within `.elementthumb`

### Steps to reproduce

1. Add user to users field

### Additional info

- Browser: Chrome 66 (MacOS 10.13)
- Craft version: 3.0.3.1
- PHP version: 7.1.16
- Database driver & version: mysql

**Comment by brandonkelly** [comment]
Fixed for the next release, thanks!
