### ISSUE TITLE
Order of sites listed in front-end template

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#2789]
### Description
When outputting the list of sites for a multisite setup in a front-end template the order is displayed alphabetically based on the site name. Should the default order match the custom order set within the CP?

### Steps to reproduce

1. For a multisite setup go to the CP --> Settings --> Sites and reorder the list of sites
2. In your front-end template use the following code display below
3. Sites will be displayed alphabetically instead of in the order they were set in the CP

`{% set sites = craft.app.sites.getAllSites() %}
{% for site in sites %}
{{ site.name }}
{% endfor %}
`

### Additional info

- Craft version: 3.0.3.1
- PHP version: 7.2.4

**Comment by brandonkelly** [comment]
Yep what @carlcs said.

**Comment by richhayler** [comment]
Thanks for your advice @carlcs :) Sorry for raising this as an issue incorrectly.

**Comment by jeroenlammerts** [comment]
If you never sorted the sites in the group, the ordering is still random ;)
