### ISSUE TITLE
FR: Custom Fields for Sites

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#2790]
### Description
It would be great it you could add custom fields for sites in a multisite setup.

If you have the option to use the layout designer within the CP --> Settings --> Sites to configure  custom fields that could be set per site and then render the data in a front-end template, e.g. site.description, site.primaryColour, site.twitter or currentSite.description, currentSite.primaryColour, currentSite.twitter etc.

Appreciate that "Globals" provides for this functionality but it makes more sense to me that site-specific fields might be better served being accessed from within the "sites" section? Also i'm not sure if you can access values of global fields (setup for each site) in a frontend template by looping through sites? `craft.app.sites.getAllSites()`?

**Comment by brandonkelly** [comment]
Everything in Settings is restricted to admins only, for good reason, as anything you change in there could have significant consequences to the Craft install. It would be a little unnerving to manage content values right alongside those system settings.

A Global Set with translatable fields seems like the right way to go for this.

**Comment by richhayler** [comment]
Makes sense. Thanks for considering this and explaining your rationale. I’ll post in Slack regarding how to access global sets for each site in a loop. Trying to create a site switcher with additional details about each site, e.g site logo, description, brand name etc.

**Comment by brandonkelly** [comment]
Actually, just realized it wasn’t really possible to query global sets in other sites. So I just added a `craft.globalSets()` method, similar to `craft.entries()`, for today’s 3.0.4 release. When that’s out you’ll be able to do this:

```twig
{% for site in currentSite.group.sites %}
    {% set global = craft.globalSets.handle('<globalSetHandle>').siteId(site.id).one() %}
    <p>{{ global.<customFieldHandle> }}</p>
{% endfor %}
```

**Comment by richhayler** [comment]
Awesome! Thanks @brandonkelly!

**Comment by richhayler** [comment]
I've updated to 3.0.4 and implemented the above code (with a couple of minor changes) however i'm only getting back the first value for the selected global set for all of the sites.

So if I have 3 sites and each have a global with the handle "brand" set to "A, B, C" respectively, when I implement the following code I get the following output:

1 - A
2 - A
3 - A

instead of,

1 - A
2 - B
3 - C

```
{% set sites = craft.app.sites.getSitesByGroupId(1) %}
{% for site in sites %}

   {% set brand = craft.globalSets.handle('brand').siteId(site.id) %}
   {{ site.id }} - {{ global.brand }}

{% endfor %}
```

**Comment by timkelty** [comment]
> A Global Set with translatable fields seems like the right way to go for this.

The drawback to this approach is that while any fields in a global set can be translatable, the fields and sets themselves are always going to show up, which can result in global fields/sets that don't necessarily apply to a particular site.
