### ISSUE TITLE
Craft 3.0.4 account registration mail sends broken link

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#2802]
### Description
It seems the registration mail for Craft 3 is not working properly, it only sends the path, not the domain, resulting in users that are not able to register

Expected:
domain.com/actions/users/set-password?code=xxx

Reality
/actions/users/set-password?code=xxx

### Additional info

- Craft version: 3.0.4

**Comment by brandonkelly** [comment]
> Info: The URL for set password, after manually activating the account, works properly, it just is the activation url

Strange, because both of those go through the same URL generation function. Did anything change between the time those two emails were sent? Such as, did the user gain permission to access the Control Panel, or did your site’s Base URL change?

**Comment by brandonkelly** [comment]
Is your site’s Base URL root-relative?
