### ISSUE TITLE
When you create a new entry, and switch entry-type, the tabs initially don't show up

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#2806]
### Description
If you create a new entry, and select a non-default entry type. The tabs don't show up. You have to save and reload, then they are visible. The ajax is not injecting them when switching the types.

### Additional info
- Craft version: 3.0.4

**Comment by brandonkelly** [comment]
Tabs are getting updated on my end. Are you getting any JavaScript errors when switching entry types?

**Comment by lenvanessen** [comment]
closed
