### ISSUE TITLE
Add translation method description on translatable fields

### ISSUE THREAD

**Issue by codyjames** [craftcms/cms#2808]
### Description
It would be nice to indicate the translation method used for each field in the CP. When mixing-and-matching methods the author may get surprised when something fields do not behave consistently.

<img width="361" alt="screen shot 2018-04-25 at 1 48 17 pm" src="https://user-images.githubusercontent.com/378665/39272160-fd44844a-488f-11e8-944b-93007270d505.png">

### Additional info

- Craft version:  3.0.4
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Starting with the next release, those icons’ tooltips will reveal the translation method, if it was set to Site, Site Group, or Language.
