### ISSUE TITLE
Allow Assets Field and Entries Field to be managed at the site, site group, and language level

### ISSUE THREAD

**Issue by codyjames** [craftcms/cms#2809]
It would cool if Assets Fields (and Entries Fields) could be managed at the site, site group, and language level _in the same way as other fields_. For instance, we have an "English" site group and would want to use the same assets for all of those sites, but a French site may use a different asset.

<img width="333" alt="screen shot 2018-04-25 at 2 13 55 pm" src="https://user-images.githubusercontent.com/378665/39273482-c2876d5a-4893-11e8-86d4-aacf67d6eb59.png">

**Comment by codyjames** [comment]
Gosh, we could really use this. It greatly adds to complexity of what we are trying to do (translate a site into 12+ languages).

**Comment by brandonkelly** [comment]
I’m not even sure how we’d go about this, as there is curretnly a direct correlation between assets and the physical files on the server.

One option is you could create a volume spceifically for holding “translated” assets, and put a “Translated File” custom Assets field on your main asset wolume, connected to the translated asset volume & set to manage relations on a per-site basis. Then use your main volume to hold the “primary” language’s assets, and whenever you need to supply a translated version of an asset, just double-click on it, and  upload a file to the Translated File field.

Then from your template, do this whenever dealing with an asset:

```twig
{% set asset = asset.translatedFile.one() ?? asset %}
```

Or if looping through multiple assets, you could eager load them.

```twig
{% set assets = entry.myAssetsField.with(['translatedFile']).all() %}
{% for asset in assets %}
    {% set asset = asset.myAssetsField[0] ?? asset %}
    ...
{% endfor %}
```

**Comment by brandonkelly** [comment]
Ah, right, sorry I must have been thinking of a different issue.

Making relations translatable with the same modes as normal fields would be quite a big change, so not something we would do unless this FR got significant traction.

**Comment by jsunsawyer** [comment]
Without this feature, translations are really confusing to explain to the client. It immediately introduces an exception to how groups work.

User wants to edit an image and text field for all sites in an English site group.
- User updates text field content: Text is updated for each site in group.
- User updates an image: Image is updated for the current site, other sites in the group use the old image.

Outside of creating extra work, this inconsistency introduces a scenario where content can easily and unintentionally get out of sync.

This seems like a really important change to make translations clear and consistent.

**Comment by mstvincent** [comment]
This is a feature I stand behind for sure !

**Comment by michaelhue** [comment]
@brandonkelly Would you accept a pull request for this? I'm not very familiar with the internals of the relation fields but I'd be willing to give it a shot. A little guidance would go a long way though.

Update `3.2` added propagation methods for sections and matrix fields, which is fantastic for "true" multi-site + multi-language setups. The two relation fields being an exception hurts the experience.

I completely agree with @jsunsawyer; clients are repeatedly confused by this.

**Comment by brandonkelly** [comment]
@michaelhue I think it’s best if this one is resolved in-house. We are going to be making other content modeling-related changes in Craft 4, so I think that would be the best time to try to tackle this. I’ll add it to that milestone and see what I can come up with.

**Comment by timkelty** [comment]
To clarify: you already can manage these per-site, right? ("Manage relations on a per-site basis" checkbox in field settings)

So the issue remains for how to manage them on the group level, right?

I use https://github.com/timkelty/craftcms-site-sync to get around some of these issues. Not sure if it will fit your use-case, though.

**Comment by wsydney76** [comment]
>  so not something we would do unless this FR got significant traction.

Happy to add some traction. A lot. The lack of this is leading to a lot of confusion/inconsistency/epic instructions.

**Comment by maxstrebel** [comment]
I just have the same situation. I build a page builder for a client, which uses Sites for branded pages. Most of them have 2 locales. They want to manage the images separately and have a hard time to understand why they should either manage the asset twice for each language or have all assets of the different marketing departments. And I don't like it at all, neither.

Please, please consider to split Locale and Sites in Craft 4. 

In the meantime I'd be really happy to be able to manage Assets in a siteGroup basis. Is there any way this could be done until Craft4?

**Comment by soschubert** [comment]
Looks like this is still unsolved?

We want to offer some files for download and they are in different languages. Almost everything else is 'translatable' but not the asset content/field.

We used a workaround for now, but we'd be happy if there is a clean solution for it in the future.

**Comment by andris-sevcenko** [comment]
@soschubert there will be, but for it to be clean, there needs to be a refactor of how content modeling works in Craft. Currently looks to be slated for 5.0.

**Comment by johnwbaxter** [comment]
I found this one a bit confusing when creating a multi site site. Coming from EE land, I was expecting everything to be interchangeable so this threw me a bit :)

To get around this, I wrap fields like this in a supertable field so that it's translatable, but I do think that they should be translatable like everything else.

**Comment by maxstrebel** [comment]
Thats a clever hack @johnwbaxter. 

I sincerely hope you consider a Refactor in 4.0, @andris-sevcenko. After my last Multisite Project, I'm mildly frustrated (because it is a bump in an otherwise very positive client experience). Translations and also Asset Permissions on a Site basis are all big hacks right now.
