### ISSUE TITLE
Saving Matrix Field through jobs throws an error

### ISSUE THREAD

**Issue by pdaleramirez** [craftcms/cms#2813]
https://github.com/craftcms/cms/blob/d8420fe5c5a61887063fb49a3663c8649161b1b7/src/elements/MatrixBlock.php#L406-L407

Saving matrix data field through jobs queue on an element will result into `Cannot send session cookie - headers already sent error` and failed jobs. Tested commenting those 2 lines fixed the issue,
@BenParizek

**Comment by brandonkelly** [comment]
Fixed for the next release, thanks!
