### ISSUE TITLE
unverifiedEmail on the user element always returns null

### ISSUE THREAD

**Issue by tomwelch** [craftcms/cms#2815]
### Description

When trying to access the unverifiedEmail property on a user element who has changed their email address and not yet followed the link in the email NULL is returned rather than their unverified email address.

### Steps to reproduce

1. As a user, change the email address either via the Control Panel or a front end form
2. Check the user record in the database and verify the unverifiedEmail field contains the new email address
3. In a twig template retrieve the user element via either `currentUser` or `craft.users.id(ID).one()` and dump `unverifiedEmail`

### Additional info

- Craft version: 3.0.4
- PHP version: 7.1.12
- Database driver & version: MySQL 5.7.17
- Plugins & versions: None

**Comment by brandonkelly** [comment]
This is expected, because we don’t have any good reason to select users’ unverifiedEmail column values on most user queries, so it’s not there by default.

You can include the value by adding an `addSelect()` call to your user query:

```php
$user = \craft\elements\User::find()
    ->id(100)
    ->addSelect(['users.unverifiedEmail'])
    ->one();
```
