### ISSUE TITLE
Feature Request: CP Sort by Custom Field - 3.X

### ISSUE THREAD

**Issue by thisanimus** [craftcms/cms#2818]
It would be nice to be able to sort entities by their custom fields.  This issue has been raised in Craft 2.5, but I did not see that anyone had mentioned it for 3.X. 

Related Issues in 2.5:
https://github.com/craftcms/cms/issues/859
https://github.com/craftcms/cms/issues/987

**Comment by jsunsawyer** [comment]
I previously used https://github.com/mmikkel/CpSortableCustomColumns-Craft to achieve this in Craft 2. Really feel that this should be built into Craft though.

**Comment by thisanimus** [comment]
From a content authoring standpoint, Craft is basically a magical unicorn.  Everything else is so easy and customizable that it makes this one issue stick out like a sore thumb.

**Comment by KatieMFritz** [comment]
Plus one! A plugin would work too, but I can't see NOT wanting this feature in any instance.

**Comment by RitterKnightCreative** [comment]
+1 for this.

**Comment by paul-frost** [comment]
+1
I need this feature on every site I build. The plugin for 2.5 was part of my standard instal so I forgot it was a plugin. I've just started working on my first Craft 3 site and am stuck.
Any site that has events is going to have a custom date field, and being able to list them in date order in the CP is very helpfull for editors.
I don't want to commision a custom plugin as that could be a problem going forward with maintaining it and I don't have the time of skill to build it myself.

**Comment by pixeldeluxe** [comment]
+1 
There are a lot of times when I want certain cols to be sorted. Thanks in advance and keep up the good work, you guys!

**Comment by brandonkelly** [comment]
@thisanimus I can’t give you an ETA or anything at this time. You can pull it off with a module/plugin like this:

```php
use craft\elements\Entry;
use craft\events\RegisterElementSortOptionsEvent;
use yii\base\Event;

Event::on(Entry::class, Entry::EVENT_REGISTER_SORT_OPTIONS, function(RegisterElementSortOptionsEvent $event) {
   $event->sortOptions[] = [
       'label' => '<FieldName>',
       'orderBy' => 'field_<FieldHandle>',
       'attribute' => 'field:<FieldID>'
   ];
});
```

**Comment by thisanimus** [comment]
beautiful, thanks!

**Comment by benface** [comment]
Very odd that this isn't built in yet!

**Comment by brandonkelly** [comment]
We only have time for 10 things at a time!

**Comment by KatieMFritz** [comment]
Hi @brandonkelly - thanks for the code snippet! I was able to add sort functionality for some custom fields in Entries.

I want to do the same for Assets. Can I do that in the same module, or do I need a separate module?

**Comment by brandonkelly** [comment]
@KatieMFritz You could use the same module, either with a second event listener (for `craft\elements\Asset` instead than `craft\elements\Entry`) or if you want the _exact same_ sort options added for assets, a single event listener on `craft\base\Element` would be easier:

```php
use craft\base\Element;
use craft\elements\Asset;
use craft\elements\Entry;
use craft\events\RegisterElementSortOptionsEvent;
use yii\base\Event;

Event::on(Element::class, Element::EVENT_REGISTER_SORT_OPTIONS, function(RegisterElementSortOptionsEvent $event) {
    if ($event->sender instanceof Asset || $event->sender instanceof Entry) {
        $event->sortOptions[] = [
            'label' => '<FieldName>',
            'orderBy' => 'field_<FieldHandle>',
            'attribute' => 'field:<FieldID>'
        ];
    }
});
```

**Comment by KatieMFritz** [comment]
@brandonkelly Thank you! @angrybrad _just_ helped me and I was writing my own answer to the question. 😆

**Comment by jonlongnecker** [comment]
+1 from me as well. Had to create an events section, and because of the weird way that Craft's default entry date field worked, it made more sense to create a separate start date field. But now I can't sort any of the events entries by that custom start date in the control panel! For everyone's sanity I'd love to be able to click and sort by that field.

**Comment by littlered** [comment]
+1. This would make an awesome CP even awesomer!!

**Comment by brandonkelly** [comment]
The next Craft 3.2 Alpha release will give custom fields the ability to opt into being sort options, by implementing a new `SortableFieldInterface`.

**Comment by xaddict** [comment]
If I want to add this functionality right now and I want to sort by related fields, what would I fill in under `orderBy` and `attribute`?

**Comment by brandonkelly** [comment]
@xaddict The change is just for the CP, and relational fields don’t even support it. Not really an easy way to sort elements by their related elements. Definitely more complicated than just a custom `orderBy` value.

**Comment by xaddict** [comment]
Okay.
I could see a way where orderBy is a function or something to take care of that.
Will the 3.2 Stable release support sorting for one dimensional fields out of the box?

**Comment by xaddict** [comment]
Okay.
I could see a way where orderBy is a function or something to take care of that.
Will the 3.2 Stable release support sorting for one dimensional fields out of the box?

**Comment by brandonkelly** [comment]
@xaddict You can already sort by most fields using `.orderBy('fieldHandle ASC')`(or DESC).

**Comment by xaddict** [comment]
@brandonkelly I meant in the backend for default views like the entries list. Being able to sort/filter by anything is a real nice addition to any CMS. Craft is already way ahead of some other systems, but this would be a top feature for a lot of my clients.

**Comment by brandonkelly** [comment]
@xaddict that’s what this feature request is all about. Yes, implemented in 3.2.

**Comment by KatieMFritz** [comment]
![beautiful](https://user-images.githubusercontent.com/7085184/60979938-8b5e0400-a301-11e9-9910-b867c1ad991e.jpg)

**Comment by mdunbavan** [comment]
Hey has this been implemented for Craft Commerce 2 @brandonkelly ?

**Comment by brandonkelly** [comment]
@mdunbavan It’s been added for all element types that have index pages, including Commerce products & orders.

**Comment by mdunbavan** [comment]
@brandonkelly this doesn't show up when I am on the index page for commerce. If I hit the cog icon at the bottom of the product types on the left and look for a custom field it isn't there

**Comment by brandonkelly** [comment]
Only custom fields that implement [PreviewableFieldinterface](https://docs.craftcms.com/api/v3/craft-base-previewablefieldinterface.html) can be added to the table; and only fields that implement [SortableFieldInterface](https://docs.craftcms.com/api/v3/craft-base-sortablefieldinterface.html) will be listed as sort options.

**Comment by mdunbavan** [comment]
Ah right so things like categories wouldn't be possible then?

**Comment by brandonkelly** [comment]
Relational fields (including Categories) can be added as table columns, but they can’t be sorted.

**Comment by simonkuran** [comment]
Any updates on sorting by a relation? It would be really nice to be able to sort by the title of the first entry in an Entries field.

Is there a straightforward way to build this in a plugin?

**Comment by brandonkelly** [comment]
To be clear, it wouldn’t be possible to sort by relation fields, as that would result in a bunch of duplicate results in the element index.

What you could do is use a [Preparse field](https://plugins.craftcms.com/preparse-field) to store the title of the related element(s), and then show & sort that column instead of the actual relation field.

The field’s output setting would be:

```twig
{{ element.myRelationField.all()|column('title')|join(', ') }}
```

**Comment by simonkuran** [comment]
That seems like a solid workaround, thanks.
