### ISSUE TITLE
getAssignableGroups returns the user's assigned group even if it isn't enabled in permissions

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/cms#2820]
### Description

The `getAssignableGroups` method in the [UserGroup service](https://github.com/craftcms/cms/blob/develop/src/services/UserGroups.php#L83) returns the group that the user is assigned to regardless of whether or not it's enabled in the user's permissions. 

I'm struggling to understand why this would be the case, shouldn't we be able to explicitly define which groups the user is allowed to assign other users to?

### Additional info

- Craft version: 3.0.4

**Comment by brandonkelly** [comment]
@lukeyouell That method is called in the context of assigning another user's groups, so it will return a combination of user groups that the logged-in user belongs to and groups that the user being edited already belongs to. In other words, when you are editing another user, you are able to A) assign them to any groups that you belong to; and B) maintain their existing user group assignments.
