### ISSUE TITLE
Clearing Control Panel resources deletes gitignore

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/cms#2823]
### Description
When clearing control panel resource cache, it deletes the (by default provided by `craftcms/craft`) `/web/cpresources/.gitignore` file. As a result someone could accidentally commit the contents of their `cpresources` directory.

### Steps to reproduce
1. Having a `.gitignore` file inside the `cpresources` directory
2. CP -> Utilities -> Clear Cache -> Make sure Control Panel resources is selected -> Press Clear Caches

### Additional info
- Craft version: 3.0.4
- PHP version: 7.0.30
- Database driver & version: MySQL 5.7.21
- Plugins & versions: -

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next release.

**Comment by benface** [comment]
I'm still experiencing this @brandonkelly, on Craft CMS 3.1.14. Same repro steps as the first post ^

**Comment by brandonkelly** [comment]
@benface Strange, still working correctly on my end. Is your gitignore file named exactly `.gitignore` ?

**Comment by benface** [comment]
@brandonkelly This is weird. It's happening on the production server but not locally. And yes, the file is named exactly `.gitignore` and it has the following contents:

```
*
!.gitignore
```

The server is a cPanel VPS. All the requirements are met for running Craft (except the Max Execution Time which is set to 60 seconds instead of 120). Anything else would be useful?

**Comment by brandonkelly** [comment]
Have you set a custom `resourceBasePath` config setting value?

**Comment by benface** [comment]
@brandonkelly No, I haven’t.

**Comment by brandonkelly** [comment]
Huh… I’m a bit stumped then. You’re positive that the `.gitignore` file is deleted exactly when you are running the Clear Caches utility? Maybe worth sending in some admin & SSH credentials to support@craftcms.com so we can try looking into it from there.

**Comment by epcliff** [comment]
I'm having the same issue.

**Comment by Wiejeben** [comment]
@epcliff which version of Craft are you running?

**Comment by brandonkelly** [comment]
Sorry, I guess this fell through the cracks. I was able to reproduce the issue after looking into it again per #7361, and it’s now fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.18 is out now with that fix ✨
