### ISSUE TITLE
Unable to update entry type handle of Single

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/cms#2824]
### Description
After creating a new entry with type Single, I am unable to change the entry type handle. I am however able to change the section type handle.

For now I had to manually change the entry type handle in the database myself.

### Steps to reproduce

1. Create a entry of type 'Single'
2. Go to 'Edit entry type' and you will see there is no entry type handle field.
3. So lets go change the section type handle... However when using {{ entry.type }} you will get back the initial handle of when we created the single.

### Additional info

- Craft version: 3.0.4
- PHP version: 7.0.30
- Database driver & version: MySQL 5.7.21
- Plugins & versions: -

**Comment by Wiejeben** [comment]
I made a typo the first time and in my templates I was using `{{ entry.type }}`, had to use `{{ entry.section.handle }}` to get the desired result.

**Comment by brandonkelly** [comment]
Gotcha. We were already keeping single sections’ entry types’ names in sync with the section name, so I just updated that to also include their handles.

**Comment by brandonkelly** [comment]
@herrajon The change was only made for Craft 3. I just backported it to Craft 2 for the next release, though.
