### ISSUE TITLE
Category order not preserved in Matrix

### ISSUE THREAD

**Issue by alexjcollins** [craftcms/cms#2827]
### Description
I have a category field in a Matrix block where I can add more than one relation. When selecting the relations, regardless of what order I select and add them in, they always save in alphabetical order.

The order of selection is preserved when adding relations to a category field *not* in a matrix.

### Steps to reproduce

1. Create a category and a bunch of category entries
2. Create a Matrix field
3. Add a category relation field and allow a branch limit of > 1
4. Add the matrix field to a section
5. Edit an entry in that section, creating a matrix block
6. Add a category to the field. Add the last category (alphabetically) first.
7. Add a second category
8. Notice how the second category assigned to the field will be first in the order.

Repeat the same steps for a vanilla category field on an entry and notice how the order in which they are assigned is preserved.

### Additional info

- Craft version: 3.0.4
- PHP version: 7.1.16
- Database driver & version: PostgreSQL 9.5.12
- Plugins & versions:

**Comment by brandonkelly** [comment]
Categories fields always save relations in the order defined by the Category Group.

**Comment by alexjcollins** [comment]
@brandonkelly That... make sense! Thanks
