### ISSUE TITLE
Asset permissions bug: Users can view volumes they don't have permission to view from entry image/asset upload fields

### ISSUE THREAD

**Issue by gracecanfield** [craftcms/cms#2828]
### Description

When I set a user or user group's permissions to only be able to view certain asset volumes (S3 buckets, in our case), I'm still able to view and select from asset volumes I don't have permissions to when selecting from assets within an entry image or asset upload field.

### Steps to reproduce

1. Assign permissions to a user so they have view/edit access to one asset volume but not another.
2. Log in as that user.
3. Navigate to a section that contains an asset or image upload field.
4. Expected: Despite whichever asset volumes are associated with that field, the user should still only see asset volumes they have permissions to see.
5. Actual: User sees all asset volumes that are associated with the field, even those they don't have permission to view (though they can't upload new files to volumes they don't have permissions to).

Screencast:
![](http://g.recordit.co/bwxwJPjdHc.gif)

### Additional info

- Craft version: Craft Pro 3.0.3.1
- PHP version: 7.0.28
- Database driver & version: MySQL 5.7.22
- Plugins & versions:

**Comment by brandonkelly** [comment]
Currently Assets fields don’t take user permissions into account – so this is intended behavior, but I can see how it might not be desired. Here’s an open feature request that addresses it: #887
