### ISSUE TITLE
CLI getenv vars: 'Craft CMS can’t connect to the database with the credentials in config/db.php.

### ISSUE THREAD

**Issue by ryanmasuga** [craftcms/cms#2829]
### Description
I have a 3rd-party plugin installed that has console commands I'd like to run. We use a multi-environment Craft setup where the contents of our config/db.php file look like:

```
return [
    'server'      => getenv('CRAFTENV_DB_HOST'),
    'database'    => getenv('CRAFTENV_DB_NAME'),
    'user'        => getenv('CRAFTENV_DB_USER'),
    'password'    => getenv('CRAFTENV_DB_PASS'),
];
```
With those in place, I try `./craft queue/run` and that results in this error:

Exception 'craft\errors\DbConnectException' with message 'Craft CMS can’t connect to the database with the credentials in config/db.php.'

in /home/.../build/vendor/craftcms/cms/src/db/Connection.php:207

If I replace the env variables with hardcoded equivalents, the queue command runs, and then I can see the 3rd-party commands available for use

```
return [
    'server'   => 'localhost',
    'database'   => 'database_prod',
    'user'   => 'thedbusr',
    'password'   => 'p@55w3rD',
];
```

### Steps to reproduce

1. Use getenv vars in config/db.php
2. try to run `./craft queue/run` on the command line

### Additional info

- Craft version: 3.0.4
- PHP version: 7.2.3
- Database driver & version: MySQL 5.6.39
- Plugins & versions: Image Optimize 1.4.31

**Comment by brandonkelly** [comment]
Sounds like your `.env` file isn’t getting loaded for console requests. Check your `craft` executable and make sure the paths are correct.

**Comment by ryanmasuga** [comment]
Ah ha. We're using a multi-environment setup similar to nystudio's [craft3-multi-environment](https://github.com/nystudio107/craft3-multi-environment) - meaning we're using .env.php files instead of .env. We had updated our public/index to reflect that, but not the Craft executable.

Fixed this by changing:
```
if (file_exists(CRAFT_BASE_PATH.'/.env')) {
    (new Dotenv\Dotenv(CRAFT_BASE_PATH))->load();
}
```
to
```
if (file_exists(CRAFT_BASE_PATH . DIRECTORY_SEPARATOR . '.env.php')) {
    require_once CRAFT_BASE_PATH . DIRECTORY_SEPARATOR . '.env.php';
}
```
