### ISSUE TITLE
No unsaved data warning when editing user data.

### ISSUE THREAD

**Issue by myriago** [craftcms/cms#2832]
### Description
No unsaved data warning when editing user data.

### Steps to reproduce

1. Go to users and select any user
2. Change any field value
3. Navigate away from the page

### Additional info

- Craft version: 2.6.3015
- PHP version: 5.6.35
- Database driver & version: MySQL 5.6.35
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next Craft 2 and Craft 3 releases.
