### ISSUE TITLE
Modules unable to register Twig extensions if there are pending migrations

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#2833]
### Description

Possibly related to #2831:

Updating from 3.0.3.1 to 3.0.5, Craft is unable to run database migrations due to the following exception:

```
LogicException
Unable to register extension "namespace\module\twigextensions\SomeTwigExtension" as extensions have already been initialized.
```

The exception is only thrown if there are pending database migrations. If the calls to `Craft::$app->getView()->registerTwigExtension()` are removed from the modules, the migrations/update completes successfully. After updating, the calls to `registerTwigExtension()` can be added back in without the exception being thrown on subsequent requests.

### Steps to reproduce

1. Add a custom Twig extension to a module's constructor or `init()` method using `Craft::$app->getView()->registerTwigExtension()`
2. Make sure there are pending database migrations
3. Visit /admin to run the migrations
4. Confirm that a `LogicException` is thrown

### Additional info

- Craft version: 3.0.5
- PHP version: 
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Yep that definitely sounds related to #2831, which has been fixed now.
