### ISSUE TITLE
New Entry button label, include entry type

### ISSUE THREAD

**Issue by RichardJong** [craftcms/cms#2835]
### Description
When on an Entry index page, I want the add button to display 'New {section} entry' instead of 'New Entry'.
I see this is already programmed in EntryIndex.js:98, but it always shows 'New entry'

`label = (this.settings.context === 'index' ? Craft.t('app', 'New entry') : Craft.t('app', 'New {section} entry', {section: selectedSection.name}));`

**Comment by richhayler** [comment]
It might be better instead of "New {section} entry" to instead use "New {section.entry.type}", the "entry type" being the one at the top of the list if additional entry types are defined.
