### ISSUE TITLE
Craft 3 deprecated "localeEnabled" not equivalent to "enabledForSite"

### ISSUE THREAD

**Issue by boldenamsterdam** [craftcms/cms#2839]
### Description

New Craft 3 "enabledForSite" filter is not equivalent to deprecated "localeEnabled".

### Steps to reproduce

1) Create two sites:

siteId: 1
siteHandle: english
siteName: English

siteId: 2
siteHandle: dutch
siteName: Dutch

2) Create a section with handle "mySection"

3) Create an entry

siteId: 1
Title: Title
status: false
enabledForSite: false

siteId: 2
Title: Titel
status: false
enabledForSite: false

4) In order to fetch entry where locale is disabled and status is either disabled or enabled I use the following query:

```php
$entry = Entry::find()->where('title = :title', ['title' => 'Title'])->siteId(1)->section('mySection')->status(null)->localeEnabled(null)->one();
```

I tried with the following but I get no result

```php
$entry = Entry::find()->where('title = :title', ['title' => 'Title'])->siteId(1)->section('my Section')->status(null)->one();
```

Also "enabledForSite" does not allow "null". So if "localeEnabled" gets removed there it is not possible to fetch my entry.

### Additional info

- Craft version: 3.0.5
- PHP version: 7.0.8
- Database driver & version: 5.7.9
- Plugins & versions: none

**Comment by brandonkelly** [comment]
`localeEnabled` was renamed to `enabledForSite`; you can use them the same.

> In order to fetch entry where locale is disabled and status is either disabled or enabled I use the following query:
> 
> ```php
> $entry = Entry::find()->where('title = :title', ['title' => 'Title'])->siteId(1)->section('mySection')->status(null)->localeEnabled(null)->one();
> ```

It’s not actually possible to get entries where their locale/site status is disabled _only_, with either `localeEnabled` (Craft 2) or `enabledForSite (Craft 3)`. Setting that to `null` or `false` just tells Craft that it doesn’t have to worry about the locale/site status in the first place:

https://github.com/craftcms/cms/blob/ed1499da486e51324ec0d702a8d83312bfb36636/src/elements/db/ElementQuery.php#L960-L962

If you really want to only get entries that are disbaled for the current site, in Craft 3 you could do that by adding a custom condition to your entry query:

```php
$entry = Entry::find()
    ->where('title = :title', ['title' => 'Title'])
    ->siteId(1)
    ->section('mySection')
    ->status(null)
    ->enabledForSite(false)
    ->andWhere(['elements_sites.enabled' => false])
    ->one();
```

(Note that you still do need the `enabledForSite` param, to prevent Craft from adding the opposite `elements_sites.enabled` condition as well.)
