### ISSUE TITLE
Craft Elements - don't throw an Exception when setting invalid properties

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#2841]
### Description
There might be cases when someone want's to include a custom behavior/custom select values for Craft Elements that should not be lazy loaded, so these values should be selected in the query. Currently I have to do the following

```PHP
$entry= Entry::find()->one();
$entry->attachBehavior(....);
// query the values I want to have in my behaviors init function
$entry->getMyCustomBahaviorProperty();
```
So I can't eager load my custom values. I would rather like to do the following

```PHP
$entries = Entry::find()
    ->join(...)
    ->addSelect(['myTable_column1', 'myTable_column2'])
    ->all();
```

But this will always throw an exception since there is no way to remove custom columns like it's done for the `ContentBehavior` [here](https://github.com/craftcms/cms/blob/develop/src/elements/db/ElementQuery.php#L2055)

Of course I could create a custom field for this - but there are certain cases where you don't want to include several custom hidden fields in the `content` table for whatever reasons (performance for example)

I think the easiest way would be to change the `__set` method in order to not throw an exception or provide an opportunity to change the `$row` array in the [_createElement](https://github.com/craftcms/cms/blob/develop/src/elements/db/ElementQuery.php#L2014) function, and attach these values to custom behaviors like `$element->setFieldValues($fieldValues);`

My current work around is to extend the `ElementQuery` in Craft in order to overwrite this function. It would be awesome to have this ability per default.

I don't want to lose the ability to simply do `$entry = Entry::find()->select('...')->one()` instead of `$row = Entry->find()->select('...')->asArray()->one();` and populate the entry on my own (it's a mess in Twig)

The issue can be related to this question [Add custom attribute to standard element from plugin](https://craftcms.stackexchange.com/questions/25878/add-custom-attribute-to-standard-element-from-plugin/25882#25882) 
### Additional info

- Craft version: 3.x.x

**Comment by brandonkelly** [comment]
If you attach your behavior using the [EVENT_DEFINE_BEHAVIORS](https://docs.craftcms.com/api/v3/craft-base-component.html#EVENT_DEFINE_BEHAVIORS-detail) event, then the behavior will be in place in time for Yii to set the property on it.

```php
use craft\elements\Entry;
use craft\events\DefineBehaviorsEvent;
use yii\base\Event;

Event::on(Entry::class, Entry::EVENT_DEFINE_BEHAVIORS, function(DefineBehaviorsEvent $event) {
    // you can access  the entry via $event->sender, if you need to do any conditional logic here
    $event->behaviors[] = MyBehavior::class;
});

$entry = Entry::find()->one();
$prop = $entry->myCustomBehaviorProperty;
```
