### ISSUE TITLE
`cleanImage` method bloats up animated GIF

### ISSUE THREAD

**Issue by souvikdg** [craftcms/cms#2845]
### Description
We have got a highly optimised animated GIF, but the size is bloating up whenever uploaded through Craft admin panel. 

### Steps to reproduce

Upload [this image file (670kb)](https://user-images.githubusercontent.com/663682/39625266-4eddd4b0-4fba-11e8-8836-7e5e66ab953c.gif) through the Craft Asset Panel and the uploaded file will grow to nearly 1mb.

### Additional info

- Craft version: 2.6.3012
- PHP version: 7.1.17
- imagick: 3.4.3

**Comment by souvikdg** [comment]
Would be good to have a configuration like `sanitizeSvgUploads` that would skip animated GIFs from being cleansed. We had earlier faced an issue with animated GIFs (due to host constraint / old version of imagick) where the images were losing animation. Such a configuration can be handy in trusted environments.

**Comment by brandonkelly** [comment]
@andris-sevcenko thoughts?

**Comment by andris-sevcenko** [comment]
@brandonkelly If the setting by default sanitizes GIFs and users have to explicitly turn it off (consciously disabling a security feature), I feel like it's a good idea.

**Comment by brandonkelly** [comment]
Should  it just be GIFs, or maybe a way to disable all image sanitization (at least when uploaded via the Control Panel)?

**Comment by andris-sevcenko** [comment]
Even though GIF gets hit the hardest, probably should stick to one setting for all sanitization - too granular config settings often get confusing.

**Comment by souvikdg** [comment]
The two possible aspects are the _image formats_ and _upload sources_ (Control Panel or site front-end). You could provide two different settings for the two aspects, but I think it would be wise to lift the security feature for Control Panel uploads only. As far as _image formats_ go, instead of a blanket disable, one approach could be to accept a list of formats/extensions that will be skipped.

**Comment by brandonkelly** [comment]
Agree with all of that  @souvikdg. Maybe we could even roll SVGs into this, and deprecate the `sanitizeSvgs` config setting.

**Comment by andris-sevcenko** [comment]
Love this.

**Comment by carlcs** [comment]
It seems like there’s quite many people wanting to have this config setting for other image formats as well. See #3287 #3060 

As a workaround I override the Images service, but would love to see a config option.

```php
<?php

namespace modules\craft;

class Images extends \craft\services\Images {

    /**
     * @inheritdoc
     */
    public function cleanImage(string $filePath)
    {
        // no cleansing
    }
}
```

**Comment by brandonkelly** [comment]
@carlcs Let’s move the discussion over to #3287
