### ISSUE TITLE
Wrong formatting of month "May" using {{entry.postDate|date('F')}}

### ISSUE THREAD

**Issue by babau67** [craftcms/cms#2848]
### Description
I have a multisite in one language (italian) when I use a date format **F** for full textual representation, it returns correctly all months (eg January -> Gennaio, and so on) but not May that should be Maggio.
For May it returns me "**mag**" like if I had used the short format **M** (three letters).

### Steps to reproduce

1. multisite with italian locale
2. try to output some data in may with filter | date('F) - eg {{entry.postDate|date('F')}}
3. the output is **mag** instead **maggio**

### Additional info

- Craft version: 3.0.5
- PHP version: 7.0.28
- Database driver & version:  MySQL 5.7.22
- Plugins & versions: Redactor 2.0.0.1

**Comment by brandonkelly** [comment]
Thanks for pointing that otu! Fixed for the next release.
