### ISSUE TITLE
[SQL BUG?] orderBy('ifnull(...)')

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#2850]
### Description

There seems to be a bug when trying to `orderBy` an `ifnull` statement.

### Steps to reproduce

Sneak this anywhere into your code...

```php
$results = (new craft\db\Query())
    ->select('[[content.title]]')
    ->from('{{%content}} content')
    ->orderBy('ifnull([[content.title]], "zzz")')
    ->column();
```

**Expected behavior:**
`$results` would be a list of element titles, with untitled elements (ie: users) appearing as "zzz".

**Actual behavior:** 
It immediately kicks up an SQL error:

    You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 3
    The SQL being executed was: SELECT `content`.`title`
    FROM `craft_content` `content`
    ORDER BY ifnull(`content`.`title`, `"zzz")`

The error seems to be at the very end of that generated SQL statement...

    `"zzz")`

When `"zzz")` is being quoted, it's _including the closing parenthesis_. Very, very weird. I can't tell if this is a Craft bug, or perhaps even a Yii bug. ¯\\\_(ツ)_/¯

Let me know if it makes any sense to you. Feel free to ping me with questions.

### Additional info

- Craft version: 3.0.5
- PHP version: 7.0.29
- Database driver & version: MySQL 5.5.5 (MariaDB)

**Comment by brandonkelly** [comment]
When you pass a string into `orderBy()` the first thing it will do is split it on the commas, asusming each comma-separated segment represents a column:

https://github.com/yiisoft/yii2/blob/2.0.15.1/framework/db/QueryTrait.php#L372

If you want to avoid this, I think your best bet is to define your  expression within a `yii\db\Expression` object:

```php
use yii\db\Expression;

$results
    // ...
    ->orderBy([
        new Expression('ifnull([[content.title]], "zzz")')
    ])
    ->column();
```
