### ISSUE TITLE
Feature Request: Keyboard shortcut for 'Save and add another'

### ISSUE THREAD

**Issue by bensomething** [craftcms/cms#2851]
Having `Command + S` as a shortcut is so great, but sometimes I find myself having to enter a bunch of entries manually and would love to have `Shift + Command + S` (or similar) mapped to **Save and add another**.

**Comment by CreateSean** [comment]
Plus one to infinity

**Comment by lindseydiloreto** [comment]
This would be such a lifesaver. I'm about to enter 150 categories in manually.

Also... wouldn't this be pretty easy to implement? Maybe someone should do a PR.

**Comment by Mosnar** [comment]
@lindseydiloreto I would suggest using Feed Me on a Google Sheet or CSV instead of entering all of those manually.

**Comment by lindseydiloreto** [comment]
I'm reading them off of a piece of paper. 😢

**Comment by lindseydiloreto** [comment]
Alright, I've got a pretty solid JS workaround. Using the [CP JS plugin*](https://plugins.craftcms.com/cp-js), I injected this...

```js
$(function () {
    var redirect = '485b4c6a1848521a679e1e58ce5c90756067d76a8cc20b1ab9566a9f503e1363categories/industryTypes/new?parentId={parent.id}#';
    $('input[name="redirect"]').val(redirect);
});
```

When the page loads, it'll automatically update the form's hidden `input` field. It swaps out the default value for the already-hashed string you specify.

Now when adding new categories, you can just hit enter and immediately start typing the next one! 🎉 

If you copy this code, the `redirect` value on your site would be different from mine. I copied this value from the "Save and Add Another" button (it's attached as the `data-redirect` attribute).

I plan on using this workaround briefly, then removing it as soon as I'm done. If I intended to keep it in place longer, I would do a better job of targeting the hidden redirect field. Most likely, I'd use the [CP Body Classes plugin*](https://plugins.craftcms.com/cp-body-classes) to more accurately hone in on that specific page.

Hope others may find this helpful until a shortcut is added to core!

---
\* _Disclaimer: I'm the author of both of those plugins._

**Comment by brandonkelly** [comment]
Just added this for Craft 3.5.

Went with <kbd>Shift</kbd> + <kbd>Ctrl</kbd>/<kbd>Command</kbd> + <kbd>S</kbd>.
