### ISSUE TITLE
All site URLs display primary site unless `CRAFT_SITE` is hard coded

### ISSUE THREAD

**Issue by KatieMFritz** [craftcms/cms#2853]
### Description
I have two sites: 
- `safs` (primary, http://safs.local)
- `effs` (secondary, http://effs2.local)

**If I add `define('CRAFT_SITE', 'effs');` to `index.php`, then http://effs2.local shows the `effs` site. Otherwise, it shows the `safs` for both URLs.** I need to use `web/` as my webroot for my server, so I don't want to use a separate directory for the `effs` site.

### Steps to reproduce
![screenshot-safs local-2018 05 07-12-12-18](https://user-images.githubusercontent.com/7085184/39712123-e5d2a29c-51ef-11e8-8a1c-05343c16b36d.png)

I've tried various configurations, but currently I have a single `web/` folder. 

Here's my `index.php`, based on Andrew Welch's multi env config:
```php
// Set path constants
define('CRAFT_BASE_PATH', dirname(__DIR__));
define('CRAFT_VENDOR_PATH', CRAFT_BASE_PATH.'/vendor');


// Load Composer's autoloader
require_once CRAFT_VENDOR_PATH.'/autoload.php';

// Load dotenv?
if (file_exists(CRAFT_BASE_PATH.'/.env')) {
    (new Dotenv\Dotenv(CRAFT_BASE_PATH))->load();
}

// Load the local craft3-multi-environment
if (file_exists(CRAFT_BASE_PATH . DIRECTORY_SEPARATOR . '.env.php')) {
    require_once CRAFT_BASE_PATH . DIRECTORY_SEPARATOR . '.env.php';
}

// Default environment
if (!defined('CRAFT_ENVIRONMENT')) {
    define('CRAFT_ENVIRONMENT', getenv('CRAFTENV_CRAFT_ENVIRONMENT'));
}

// Load and run Craft
$app = require CRAFT_VENDOR_PATH.'/craftcms/cms/bootstrap/web.php';
$app->run();
```

I can provide the local `.env.php` on request.

Here's the `.htaccess` in my `web/` folder:
```
<IfModule mod_rewrite.c>
	RewriteEngine On

	# Send would-be 404 requests to Craft
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteCond %{REQUEST_URI} !^/(favicon\.ico|apple-touch-icon.*\.png)$ [NC]
	RewriteRule (.+) index.php?p=$1 [QSA,L]

        # Use canonical URL (safs.msu.edu)
	# RewriteCond %{HTTP_HOST} ^www.safs.msu.edu [OR]
	# RewriteCond %{HTTP_HOST} ^www.safss.msu.edu [OR]
	# RewriteCond %{HTTP_HOST} ^safss.msu.edu
	# RewriteRule ^(.*)$ https://safs.msu.edu/$1 [L,R=302]
</IfModule>

## Text compression for better performance
<IfModule mod_deflate.c>
	AddOutputFilterByType DEFLATE text/html text/plain text/css application/json
	AddOutputFilterByType DEFLATE application/javascript
	AddOutputFilterByType DEFLATE text/xml application/xml text/x-component
	AddOutputFilterByType DEFLATE application/xhtml+xml application/rss+xml application/atom+xml
	AddOutputFilterByType DEFLATE image/x-icon image/svg+xml application/vnd.ms-fontobject application/x-font-ttf font/opentype
</IfModule>
```

It's possible that I added this to some Apache config on my local server, though I don't remember how to check:
```php
SetEnv CRAFTENV_BASE_URL "http://safs.local"
SetEnv CRAFTENV_BASE_PATH "C:\wamp64\www\safs-effs\web"
```

### Additional info

- Craft version: Craft Pro 3.0.5 (upgraded from Craft 2)
- PHP version: 7.1.9
- Database driver & version: MySQL 5.7.19
- Plugins & versions:
![screenshot-safs local-2018 05 07-12-16-09](https://user-images.githubusercontent.com/7085184/39712267-6f499a08-51f0-11e8-8be1-f8e44d69871e.png)

**Comment by brandonkelly** [comment]
Go to `http://effs2.local/admin/utilities/php-info` (replace `admin` with your CP trigger, if you’ve changed it to something else). Then search for `$_SERVER['HTTP_HOST']` and `$_SERVER['SERVER_NAME']`. Are they both set to `effs2.local` ?

**Comment by KatieMFritz** [comment]
Yes, they are.

**Comment by brandonkelly** [comment]
Try duplicating your `index.php` file as `scratch.php`, and comment out the `$app->run();` line, and add this afterwards:

```php
Craft::dd($app->sites->currentSite->handle);
```

Then go to http://effs2.local/scratch.php . What gets output?

**Comment by KatieMFritz** [comment]
'safs'

**Comment by brandonkelly** [comment]
OK, replace that `Craft::dd()` line with this - what does it give you?

```php
Craft::dd($app->request->hostName);
```

**Comment by KatieMFritz** [comment]
`'effs2.local'`

**Comment by brandonkelly** [comment]
Huh, so the system definitely knows that effs2.local was requested; and yet it’s still deciding to set the current site to SAFS. The only thing I can think of is, it must be also considering SAFS to be a valid option.

In Settings → Sites, click on the SAFS site. What is the Base URL setting set to? (It might be different there than what is displayed on the Settings → Sites index page.)

Also check if you’re setting the `siteUrl` in `config/general.php`. If so, to what?

**Comment by brandonkelly** [comment]
Ah, yeah OK that `siteUrl` config setting is your issue. It is telling the primary site to always have a Base URL set to the currently-requested host name. So when you go to http://effs2.local, BOTH of your sites’ Base URLs are going to be `http://effs2.local/`. And whenever there’s a draw, Craft will go with the primary site (which always gets scored with one extra point just because it’s the primary site).

So to fix this, you should explicitly set the `siteUrl` config setting to the correct URLs.

```php
return [
    '*' => [
        // any config settings you want set regardless of environment go here...
    ],
    'dev' => [
        'siteUrl' => [
            'safs' => 'http://safs.local/',
            'effs' => 'http://effs2.local/',
        ],
    ],
    'prod' => [
        'siteUrl' => [
            'safs' => 'http://safs.msu.edu/',
            'effs' => 'http://effs2.msu.edu/ , // or whatever this is supposed to be on production
        ],
    ],
];
```

Rather than using a multi-environment config, you could also just create multiple environment variables – `SAFS_SITE_URL` and `EFFS_SITE_URL` – and explicitly set those to the correct URLs rather than making them dynamic based on the requested host name.

**Comment by KatieMFritz** [comment]
Hallelujah! Thanks, Brandon.

**Comment by jkorff** [comment]
I found this thread after debugging a similar issue for hours with my staging environment. Despite showing the correct env string it always assumed siteID 1 and the "default" site handle, and loaded my production templates (Craft 3.6.4.1).

I could eventually fix it by adding this to my .env.stage (and corresponding values to prod and local):

```
# Set site handle
SITE_HANDLE=mysiteStage
```
and this to index.php:
```
define('CRAFT_SITE', getenv('SITE_HANDLE'));
```

**Comment by brandonkelly** [comment]
@jkorff If you write into support@craftcms.com we can help you look into it from there.
