### ISSUE TITLE
FR: Option for Title fields to be non-translatable

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#2856]
Currently `Title` is always translatable between sites, which may not be ideal for a non-lang based multi-site.

## Use case:
I have a multi-site with a shared `products` section. By "shared" i mean:
- Section is enabled for each site
- **Propagate entries across all enabled sites?** is checked
- All my fields are non-translatable, so they can edit an entry on any site and it is reflected everywhere.

That is…except for the `Title` field. Since that is always translatable, it is updated independently, which is not what I want here.

## Workaround
- create a required `nonTranslatableTitle` field
- set the **Title format** for the Entry Type to `{nonTranslatableTitle}`.

Ideally, in the Entry Type config, along with the other Title field options, a **Translation Method** option was present, just like when you create a Plain Text field.

**Comment by timkelty** [comment]
Note: The workaround mentioned works well for Entries, but other element types aren't so lucky, as you can't specify a title format (Categories).

**Comment by amityweb** [comment]
The workaround method results in the Title still showing in the entries list. You cannot disable the Title column in the list, so you would have a Title column, then the nonTranslatableTitle column.

**Comment by amityweb** [comment]
Addition to the workaround... in my case I am importing hundreds of entries using FeedMe which updates the titles of the site I am importing into, but does not update the titles of the other entries within the same group. So all my for example Spanish sites entries had English titles except for the one I imported into, and I could not see how to sync the titles (which would be expected to happen). Resaving the original did nothing. 

So this workaround worked, except I had to re-save the entry, and on hundreds of entries its not practical. So running this command will save the all the other sites entry titles as the new imported title:
`php craft resave/entries --section=pages --site=de`
Obviously changing section and site to your own.

**Comment by kgrote** [comment]
+1 for both category titles AND entry slugs

**Comment by brandonkelly** [comment]
Just added a new Translation Method setting to entry types for Craft 3.5.

Not going to touch categories since that concept is being phased out.

**Comment by JeanLucEsser** [comment]
Actually as @kmgdevelopment hinted at, it would be nice to have the same setting for the slug.
Depending on how we use multisite, specifically when there's no front, there is no use to have the slug translatable.

BTW, will this be in beta 4?

**Comment by ItagMichael** [comment]
Throwing a vote in to also have an option to **not** translate the slug.

I implemented a feature on a site where a certain channel is shared across multiple sites with identical content. The non-translatable title option in 3.5 is great for ensuring this content is always consistent, but an editor changing a slug without realising it changes for one site may cause issues due to our implementation. Being able to ensure a fixed slug always would be perfect!

**Comment by brandonkelly** [comment]
Please submit that request as a new issue.
