### ISSUE TITLE
Craft keeps trying to generate thumbnails for .mp4 files

### ISSUE THREAD

**Issue by tyler-deboer** [craftcms/cms#2858]
### Description
I have an S3 assets volume where I've been trying to upload `mp4` files. The upload usually progresses normally and speedy, but then the backend stalls for 20-30 seconds after that because Craft tries to generate a thumbnail for the video, and I end up with a `craft\errors\ImageException` error.

```craft\errors\ImageException: The file “video-name-15af1fc60a76874.17442007.mp4” does not appear to be an image. in /var/www/site-name/vendor/craftcms/cms/src/image/Raster.php:169```

I'm not sure where that hashed string is coming from at the end of the file name either -- the original file I'm adding has a name of `video-name.mp4`.

This is happening even when I navigate away from that Assets page and back into it - Craft again tries to generate thumbnails for each of the `mp4` files I have in there every time I load the Assets page. I looked a little closer at the logs and while each video file is still returning an error each time the page is loaded, the hashed string at the end of the video file name is different (i.e. I'll get a `The file “video-name-15af1fd578b4f61.60122716.mp4” does not appear to be an image.` error instead of a `The file “video-name-15af1fc60a76874.17442007.mp4” does not appear to be an image.` error).

### Steps to reproduce
1. Hook up an asset volume to a S3 bucket
2. Upload an .mp4 file on the Assets page

### Additional info
- Craft version: 3.0.6
- PHP version: 7.2.2
- Database driver & version: MySQL 5.7.22
- Image driver & version: Imagick 3.4.3 (ImageMagick 6.8.9-9)
- Plugins & versions: Amazon S3 1.0.8, ImageOptimize 1.4.31

**Comment by brandonkelly** [comment]
Craft will only generate thumbnails for images, so either Craft somehow is confusing this file for an image (seems unlikely), or maybe you have a plugin installed that is trying to create the thumbnail?

**Comment by andris-sevcenko** [comment]
Related to #2408

**Comment by tyler-deboer** [comment]
Yeah I'm puzzled to what's going on. I have a duplicate staging site so I went in and uninstalled all my plugins there and cleared the cache and it's still giving me the `500` errors.

Interestingly enough, my local MAMP version is handling things just fine and not trying to generate any thumbnails. There are only a few differences between my local and prod/staging environments:

PHP: `Local` 7.2.1 / `Prod` 7.2.2
Database Driver: `Local` MySQL 5.6.38 / `Prod` 5.7.22
Image Driver: `Local` GD 7.2.1 / `Prod` Imagick 3.4.3 (ImageMagick 6.8.9-9)

I'm running Apache on my local setup but using nginx for my prod setup. I can't imagine it's the PHP or MySQL versions that are causing the issue, so my guess is either the Image Driver and/or the server type?

It's very possible I just have some settings that aren't configured correctly on the server end too - I'm not a devops expert by any means.

**Comment by brandonkelly** [comment]
@tyler-deboer Do you have GD installed on production (in addition to ImageMagick)? If you’re not sure, you can find out by searching for “gd” at `/admin/utilities/php-info`.

If you do, you can force Craft to use GD instead of ImageMagick by going into `config/general.php` and adding this:

```php
'imageDriver' => 'gd',
```

That will probably fix this for you, assuming this is in fact the same bug as #2408.

**Comment by tyler-deboer** [comment]
Yup, that was the culprit! Interesting that ImageMagick's configs are set up like that. Glad to finally get to the bottom of the problem though, I thought I was going crazy. I'll change my setup to `gd` for now. Thanks!

**Comment by brandonkelly** [comment]
Cool, glad that switching to GD worked for you. I’ll close this as it's basically a different symptom of the same problem as #2408.
