### ISSUE TITLE
v3.0.6 - Twig |date('U') returns nothing

### ISSUE THREAD

**Issue by thisanimus** [craftcms/cms#2867]
### Description
Attempt to display a datetime value in UNIX timecode format using the twig |date() filter

### Steps to reproduce
1. Put `{{ entry.postDate|date('U') }}` in a template file.
2. Notice that this returns nothing.

### Additional info

- Craft version: 3.0.6
- PHP version: 7.0.30
- Database driver & version: MySQL 5.6.38

**Comment by brandonkelly** [comment]
Just fixed this for the next release, but in the meantime you can just change `|date('U')` to `.timestamp`.

```twig
{{ entry.postDate.timestamp }}
```
