### ISSUE TITLE
Invalid Configuration Error - Redactor plugin not found: source

### ISSUE THREAD

**Issue by tehatjamberry** [craftcms/cms#2869]
### Description

The Redactor config Standard.json calls for the **Source** plugin although it is not included in the redactor/lib/redactor-plugins directory.

### Steps to reproduce

1. Create a redactor field
2. Set the redactor field to use Standard (config)
3. Apply field to section
4. Edit entry in section

### Additional info

- Craft version: 3.0.6
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Plugins & versions: Redactor 2.0.1

**Comment by brandonkelly** [comment]
The Source plugin was dropped in Redactor 3.

We’ve [updated](https://github.com/craftcms/craft/commit/bba8b1317579a90555a2fc93cbee4f211134dafd) the default Standard.json config to no longer include the `source` plugin, and new Redactor installations/upgrades will _try_ to update existing Redactor configs  for you – but that is only possible if PHP has write permissions for those files. Most likely in your case it did not. So you will just need to manually edit Standard.json and remove that `source` plugin from the list.
