### ISSUE TITLE
Deprecator Class

### ISSUE THREAD

**Issue by gregorskii** [craftcms/cms#2870]
### Description

The deprecator service class can flood an instance of Craft 3 with too many open writes, as each deprecation error is written to the database on every request.

Per the file:

https://github.com/craftcms/cms/blob/develop/src/services/Deprecator.php

There is no way to turn off Deprecation writes to the DB, and some of the Deprecation errors I am getting are out of my control.

Temporarily we returned false from the Deprecator.

This feature should be removed on production, or write to a file instead, or be controlled by the user.

### Additional info

- Craft version: Craft Pro 3.0.3.1
- PHP version: 7.1.15
- Database driver & version:  Aurora MySQL 5.6.10a
- Plugins & versions: Element API 2.5.2, Migration Manager 3.0.0, Redactor 1.1.0

----

Looks like some of the deprecations are coming from an outdated version of Migration Manager, I can work on updating that, but nevertheless I humbly suggest these should not be written to the DB on each request... :)

![screenshot 2018-05-09 16 25 35](https://user-images.githubusercontent.com/1130448/39844628-e49d0fa4-53a5-11e8-8a23-6758fe295e2b.png)

I have fixed the config mismatches in the log here as well.

**Comment by brandonkelly** [comment]
The assumption is that you will fix the deprecation errors when you see them. If we removed them from production (or wrote to a file), the logs would likely be missed by most people.

**Comment by gregorskii** [comment]
Fair, but leaving then in production on a high traffic site has the potential to take it down.

I would imagine its fair to assume people should fix these issues in staging, or make their own choice to disable them in production.

**Comment by brandonkelly** [comment]
I just added a new `$logTarget` property to the Deprecator service, which can be changed to `'logs'` if you want deprecation errors to be saved to your error logs, or `false` if you want them to be suppressed entirely.

You can set that property from `config/app.php`:

```php
return [
    'components' => [
        'deprecator' => [
            'logTarget' => 'logs',
        ],
    ],
];
```

**Comment by gregorskii** [comment]
Awesome thank you 🙏

**Comment by gregorskii** [comment]
Thanks this is deployed to our server. I believe it is working. I am now not getting any deprecation errors in the CMS admin panel.

Looks like this is good.

TY
