### ISSUE TITLE
Request: Ctrl + S on Field pages

### ISSUE THREAD

**Issue by mark-chief** [craftcms/cms#2872]
Since Ctrl + S 'ing is so damn handy it would be good to have this functionality when adding or editing a field.

I am quite often making small tweaks then clicking save to then be sent back to the fields overview page. Especially irritating when editing a matrix field block as you have to click on the field, and then drill down through the blocks to find the field you were editing.

Whilst I am here, "Save and add another field" would also be super handy.

We cool though, there's worst things in the world that not having this.

**Comment by j-greig** [comment]
Control + S would be nice to have on _any_ page with a Save button IMO :)

**Comment by brandonkelly** [comment]
@j-greig that should already be the case ;) This request is more about post-shortcut behavior (you should probably be kept on the same page rather than redirected to the parent page).

**Comment by brandonkelly** [comment]
This has been added for the next release 🎉

![The Save button on an Edit Field page, with its new expanded menu, revealing a “Save and continue editing” option](https://user-images.githubusercontent.com/47792/92963423-4498fc00-f427-11ea-8d3c-86baab4dd1f5.png)

**Comment by brandonkelly** [comment]
Craft 3.5.10 is out now with this.

**Comment by carlcs** [comment]
This would be nice to have on the Entry Type settings page as well!

**Comment by brandonkelly** [comment]
Added for the next release, as well as for Edit Section pages.

**Comment by brandonkelly** [comment]
Craft 3.5.17 is out now with the change to Section / Entry Type pages.
