### ISSUE TITLE
[BUG] Moving asset sub folder into another deletes all child assets.

### ISSUE THREAD

**Issue by DanielSteadfast** [craftcms/cms#2873]
### Description
Moving a folder in the asset browser deleted all of the child assets.

### Steps to reproduce

1. Create a folder and add assets to it
2. Drag the folder within another folder
3. All image in the moved folder will be deleted

### Additional info

- Craft version: 3.0.6
- PHP version: 7.2.5
- Database driver & version: MySQL 5.7.22
- Plugins & versions:
Amazon S3	1.0.8
Control Panel CSS	2.1.0
Control Panel JS	2.1.0
Expanded Singles	1.0.3
Field Manager	2.0.2
Redactor	2.0.1
SuperSort	3.0.1
Typed link field	1.0.8
Videos	2.0.0-beta.7

**Comment by andris-sevcenko** [comment]
Is this something you can reproduce or is this something that "just happened"?

**Comment by DanielSteadfast** [comment]
I have managed to replicate it a couple of times, but not every time.

I will do some more fiddling tomorrow to see if i can replicate it and record it as it happens.

Thanks.

**Comment by DanielSteadfast** [comment]
@andris-sevcenko I have recorded a video showing the issue from creation to it actually happening on a fresh install of craft:

https://youtu.be/n0IyZSOrllU

**Comment by andris-sevcenko** [comment]
Tried to fiddle around, but could not reproduce it.

Did the files delete from the server as well, or only from Assets?

**Comment by DanielSteadfast** [comment]
From previous testing yes they did, I cannot currently check for the instance in the video as I am away from my work computer.

I did take me several attempts to replicate it, but that video was on a fresh install with no plugins.

**Comment by DanielSteadfast** [comment]
@andris-sevcenko if you would like to skype or phone call to go over it please let me know.

Would really like to get this resolved ASAP.

Thanks

**Comment by andris-sevcenko** [comment]
Can you get in touch via support@craftcms.com so we can arrange further communication?
