### ISSUE TITLE
Element query status does not seem to work

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#2880]
### Description
When using this query:
```twig
{% set criteria = craft.entries.section('cases').orderBy('title asc').limit(null).status('live') %}
```

Craft returns also draft entries, when it should only return live entries. And if i'm correct:

```twig
{% set criteria = craft.entries.section('cases').orderBy('title asc').limit(null) %}
```

This query should also only return live queries, but also returns drafts.

Craft 3.0.7

**Comment by lenvanessen** [comment]
Full query
```
 {% set criteria = craft.entries.section('cases').orderBy('title asc').limit(null) %}
     {% set prev = entry.getPrevSibling(criteria) ?: criteria.inReverse().one() %}
                    {% set next = entry.getNextSibling(criteria) ?: criteria.one() %}
```

**Comment by brandonkelly** [comment]
In the Control Panel, go to one of the draft entries that are showing up when you set `status` to `live`, and then in the top revision menu, select “Current”. Is the entry enabled from that revision? If so you will need to disable it.

(There is no such thing as a “draft entry”; just entries, and entries  can have drafts, whether their current revision is enabled or disabled.)

**Comment by lenvanessen** [comment]
Hi, The current version is disabled but still showing up

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you send a database backup over to support@craftcms.com ?
