### ISSUE TITLE
Hidden title field is showing up after save when it's empty

### ISSUE THREAD

**Issue by marcwieland95** [craftcms/cms#2881]
### Description

The hidden title field shows up when it's content or the content of it's replaced field is empty.
In addition, the custom title replacement field also does not need to be required.

### Steps to reproduce

1. Set an alternative field in the section panel for the default title
2. Go to the section and leave the custom title field empty
3. Press Save
4. The hidden Title-Field is showing up

### Additional info

- Craft version: 3.0.7
- PHP version: 7.0
- Database driver & version: MySQL

![bildschirmfoto 2018-05-14 um 15 38 39](https://user-images.githubusercontent.com/6168975/40001112-c1821bd6-578d-11e8-8764-826fa8446497.png)

**Comment by brandonkelly** [comment]
Yeah it’s a little awkward but this is intended; we needed _some place_ to show Title validation errors, when the title is generated dynamically.

**Comment by marcwieland95** [comment]
@brandonkelly ok, thanks for the clarification. Just wanted to report it.
Nice work on Craft. I enjoy working with it.

**Comment by brandonkelly** [comment]
Glad to hear that!

**Comment by RitterKnightCreative** [comment]
@brandonkelly Just bumped into this today and threw me for a loop for a second...

It would be nicer if Craft could check to see if an existing custom field is set in the dynamic title and if that field is set to required, don't show the title validation (because it'll be a redundant notification).

**Comment by brandonkelly** [comment]
Easier said than done, unfortunately, since there is a wide variety of ways you might be setting the Title Format, including templates that don’t involve any fields (e.g. `{id}`), or multiple fields.
