### ISSUE TITLE
Asset::getUrl always produces error due to isGif call

### ISSUE THREAD

**Issue by sebastian-lenz** [craftcms/cms#2887]
### Description

Calling `craft\elements\Asset::getUrl` currently always produces a php error as it is calling `craft\helpers\FileHelper::isGif` passing only the filename and not the complete path.

Under the hood, `FileHelper::isGif` will call `FileHelper::getMimeType` which will try to call `finfo_file` on the passed filename. There are no checks for whether the file actually exists and therefore each call to `Asset::getUrl` produces a php error as all the passed filenames are incomplete.

### Steps to reproduce

1. Call `Asset::getUrl()`. Debugger will always hit `craft\web\ErrorHandler::handleError`.

### Additional info

- Craft version: 3.0.7
- PHP version: 7.1.16
- Database driver & version: MySQL 5.7.19
- Plugins & versions: None

### Suggestions

Craft should check whether the file resides on the local file system and should pass the complete path to `FileHelper::isGif` if so. Additionally `FileHelper::getMimeType` should check whether the given file actually exists and is readable, if not it should directly fall back onto the extension check.

**Comment by andris-sevcenko** [comment]
Fixed in 9d767f73

**Comment by sebastian-lenz** [comment]
Well, partially. This commit only fixes the error produced by `finfo_file` but it will never pass the actual complete file path to `FileHelper::getMimeType` leading to wasted `file_exists` calls. If the gif detecting feature is no that important, the gif check could directly rely on `getMimeTypeByExtension` and thus avoiding unnecessary file system checks.

**Comment by andris-sevcenko** [comment]
It's because sometimes a whole path is checked and sometimes it's just a filename. When uploading a file, you actually have the full path to file to run the mimetype check on, but when dealing with a gif on a remote volume, you'll only have the filename.

**Comment by sebastian-lenz** [comment]
As far as I understand it, we always only pass just the filename to `FileHelper::isGif` right here and never the whole path: https://github.com/craftcms/cms/blob/develop/src/elements/Asset.php#L708

To get the whole path we would need some logic like in `Asset::getImageTransformSourcePath`:
https://github.com/craftcms/cms/blob/develop/src/elements/Asset.php#L880

Actually @brandonkelly put a comment concerning this issue right here: https://github.com/craftcms/cms/blame/361341a303cadf1c2c5e26c9462f34734f4ed6a9/src/elements/Asset.php#L776 and the builtin `Asset::getMimeType` therefore uses `FileHelper::getMimeTypeByExtension`. But `Asset::getUrl` now uses `FileHelper::getMimeType` through the backdoor of `FileHelper::isGif` and produces unnecessary file system lookups.

**Comment by andris-sevcenko** [comment]
You do have a point when it concerns the elegance of the approach used.
