### ISSUE TITLE
Migration issue with matrixcontent_contentblocks

### ISSUE THREAD

**Issue by auredeco** [craftcms/cms#2888]
### Description
After upgrading from Craft 2 to Craft 3 I encountered an issue regarding matrixcontent.
Migrating resulted in matrix content not being loaded properly or even data loss in multiple rows.

Checking the database in table "craft_entrydrafts" all content is present but not loaded properly.
Some data in matrixcontent_contentblocks is missing.

### Steps to reproduce

1. Clean install Craft 3
2. Install plugins
3. Update the necessary content fields to redactor fields.
4. Check content for the matrixcontent blocks.

### Additional info

- Craft version: 3.0.7
- PHP version: 7.1.9
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
Redactor | 2.0.1
Super Table | 2.0.7
Schematic | 4.0.6

**Comment by brandonkelly** [comment]
Can you please send two database backups to support@craftcms.com ? One from before the Craft 3 upgrade, and one from after.
