### ISSUE TITLE
ElementSelect on Plugin Settings not saving

### ISSUE THREAD

**Issue by samuelbirch** [craftcms/cms#2894]
### Description
I've created a plugin which has some settings. One of theses settings i would like to be an element selector. I have the elementSelectField on the settings template working fine, the modal works create etc. The issue comes to saving the settings, i get the following error in the /vendor/craftcms/cms/src/web/View.php file:

```
line: 1477
       } else if (isset($context['viewMode']) && $context['viewMode'] === 'thumbs') {
            $elementSize = 'large';
        } else {
            $elementSize = 'small';
        }

        // Create the thumb/icon image, if there is one
        // ---------------------------------------------------------------------

        $thumbUrl = $element->getThumbUrl(self::$_elementThumbSizes[0]);
 
        if ($thumbUrl !== null) {
            $srcsets = [];
 
            foreach (self::$_elementThumbSizes as $i => $size) {
                if ($i == 0) {
                    $srcset = $thumbUrl;
                } else {
                    $srcset = $element->getThumbUrl($size);
```

the $element here is just the id of the element not the actual element model.

### Steps to reproduce

1. add an element selector to a plugin settings
2. try and save

### Additional info

- Craft version: Pro 3.0.8
- PHP version: 7.1.17
- Database driver & version: MariaDB
- Plugins & versions:

**Comment by brandonkelly** [comment]
`elementSelect` inputs will just give you an array of seleceted element IDs. Which is exactly what you should be saving in the settings. It’s on you to then convert that list of IDs over to actual element models when rendering your template, as native relation fields do from `getInputHtml()`.

For example, if you are saving entry IDs, you could convert those to [craft\elements\Entry](https://docs.craftcms.com/api/v3/craft-elements-entry.html) objects like this:

```php
use craft\elements\Entry;

$entries = Entry::find()
    ->id($settings->entryIds)
    ->status(null)
    ->enabledForSite(false)
    ->all();
```
