### ISSUE TITLE
Can't run Craft 3 with read-only DB

### ISSUE THREAD

**Issue by jacksutherland** [craftcms/cms#2895]
### Description

We have a couple sites that are replicated on 2 servers, with a master/slave setup that requires the slave to be read only. Craft 2 runs smoothly with this configuration, but Craft 3 throws a DB exception "General error: 1290 The MariaDB server is running with the --read-only option so it cannot execute this statement"

### Steps to reproduce

1. Create Craft 3 site
2. Turn on the read-only option to MySQL

### Additional info

- Craft version: Pro 3.0.7
- PHP version: 7.0.29
- Database driver & version: mysql
- Plugins & versions:

**Comment by jacksutherland** [comment]
I was able to get it to work by commenting out the code that logs deprecation errors (line 99 in  vendor/craftcms/cms/src/services/Deprecator.php) and the code that updates plugin version numbers (line 217 in vendor/craftcms/cms/src/services/Plugins.php). However I obviously can't run updates now without overwriting my changes. Can we introduce some config option to prevent DB writes, when loading the non-admin front-end site?

**Comment by angrybrad** [comment]
Have you configured Yii 2 read/write splitting like so? https://www.yiiframework.com/doc/guide/2.0/en/db-dao#read-write-splitting

Have never tested this particular setup, but from what I can tell it seems like with that setup, Yii should automatically handle `SELECTS` going to the read-only slaves and anything `INSERT/UPDATE` related automatically going to the master(s).

**Comment by jacksutherland** [comment]
I tried just now. Not having much luck getting Craft to connect that way.

**Comment by angrybrad** [comment]
Can you share how you're doing it?  You'd need to do that through `craft/config/app.php` completely overriding our `craft/config/db.php` abstraction on top of it.  https://docs.craftcms.com/v3/configuration.html#application-config

**Comment by jacksutherland** [comment]
Oh I see. I'm trying to recreate the db object in the components array, but feel like I'm shooting in the dark trying to get it right. Would you mind providing an example or at least a rough example?

**Comment by angrybrad** [comment]
Untested, but something like this should do it.

That should completely overwrite whatever Craft initializes the database component with in `craft/config/db.php`

```
return [
    'components' => [
        'db' => [
            'class' => 'yii\db\Connection',

            // configuration for the master
            'dsn' => 'dsn for master server',
            'username' => 'master',
            'password' => '',

            // common configuration for slaves
            'slaveConfig' => [
                'username' => 'slave',
                'password' => '',
                'attributes' => [
                    // use a smaller connection timeout
                    PDO::ATTR_TIMEOUT => 10,
                ],
            ],

            // list of slave configurations
            'slaves' => [
                ['dsn' => 'dsn for slave server 1'],
                ['dsn' => 'dsn for slave server 2'],
                ['dsn' => 'dsn for slave server 3'],
                ['dsn' => 'dsn for slave server 4'],
            ],
        ]
    ]
]
```

**Comment by jacksutherland** [comment]
OK I got that to work, but the class has to be 'craft\db\Connection'.
But now I'm having trouble getting the slave to connect using the slave config instead of the master config.

**Comment by jacksutherland** [comment]
Unfortunately I couldn't get slave config setup, and am over on time and have to move on to other things. I had it working with the 2 problematic lines of code commented out, but the last update introduced another DB write. So this will be an uphill battle.

Just out of curiosity, why is the front-end writing to the DB for things like updating version numbers? That seems like an authenticated admin operation.

**Comment by jacksutherland** [comment]
I finally got a chance to get back to this. Here is my current configuration...

return [
        'modules' => [
            'my-module' => \modules\Module::class,
        ],
        'components' => [
            'db' => [
                'class' => 'craft\db\Connection',

                // configuration for the master
                'dsn' => 'mysql:host=master-ip;dbname=my-db-name',
                'username' => 'my-master-user',
                'password' => 'my-master-password',

                // common configuration for slaves
                'enableSlaves' => true,
                'slaveConfig' => [
                	'dsn' => 'mysql:host=localhost;dbname=my-db-name',
                    'username' => 'my-slave-user',
                    'password' => 'my-slave-password',
                    'attributes' => [
                        // use a smaller connection timeout
                        PDO::ATTR_TIMEOUT => 10,
                    ],
                ],

                // list of slave configurations
                'slaves' => [
                    ['dsn' => 'mysql:host=localhost;dbname=my-db-name'],
                ],
            ]
        ]
    ];

But it's not working. If I set the .env on the slave to the master db it works, just really slow because it's on a different region server. But the app.php configuration above just won't write to the master. Is there any other option with this, or am I just out of luck?

**Comment by jacksutherland** [comment]
I finally got a chance to get back to this. Here is my current configuration...

return [
'modules' => [
'my-module' => \modules\Module::class,
],
'components' => [
'db' => [
'class' => 'craft\db\Connection',

            // configuration for the master
            'dsn' => 'mysql:host=master-ip;dbname=my-db-name',
            'username' => 'my-master-user',
            'password' => 'my-master-password',

            // common configuration for slaves
            'enableSlaves' => true,
            'slaveConfig' => [
            	'dsn' => 'mysql:host=localhost;dbname=my-db-name',
                'username' => 'my-slave-user',
                'password' => 'my-slave-password',
                'attributes' => [
                    // use a smaller connection timeout
                    PDO::ATTR_TIMEOUT => 10,
                ],
            ],

            // list of slave configurations
            'slaves' => [
                ['dsn' => 'mysql:host=localhost;dbname=my-db-name'],
            ],
        ]
    ]
];
But it's not working. If I set the .env on the slave to the master db host/user it works, just really slow because it's on a different region server. But the app.php configuration above just won't write to the master. Is there any other option with this, or am I just out of luck?

**Comment by jacksutherland** [comment]
So we're in a bind now... We're supposed to go live with this site in a week, but still can't get Craft 3 to work with a read-only DB as we did with Craft 2. And the Yii suggestion didn't work either. Is there any thing you can do, or is this just not something that we'll be able to do with Craft 3? I need know to give our client a definitive answer. Thanks.

**Comment by angrybrad** [comment]
If you want to send all of the relevant credentials necessary to test this over to support@craftcms.com, we can take a stab at it.

**Comment by jacksutherland** [comment]
OK i just sent credentials.

**Comment by angrybrad** [comment]
For posterity, this format ended up working from `craft/config/app.php`:
    
    return [
        'components' => [
            'db' => [

                'schemaMap' => [
		    'mysql' => \craft\db\mysql\Schema::class,
		],
		'commandMap' => [
		    'mysql' => \craft\db\Command::class,
		],
			
                'class' => 'craft\db\Connection',
		'charset' => 'utf8',

                // configuration for the master
                'dsn' => 'mysql:host=localhost;dbname=mymaster',
                'username' => 'username',
                'password' => 'password',
            
                // common configuration for slaves
                'enableSlaves' => true,
                'slaveConfig' => [
            	    'dsn' => 'mysql:host=localhost;dbname=myslave',
                    'username' => 'username',
                    'password' => 'password',
                ],

                // list of slave configurations
                'slaves' => [
                    [
                        'dsn' => 'mysql:host=localhost;dbname=myslave'
                    ],
                ],
            ]
        ]
    ];

**Comment by narration-sd** [comment]
...fascinating -- also didn't know you could do config/app

my private comment fo you still holds, with all vicissitudes encountered...

**Comment by tmulry** [comment]
I played with @angrybrad  's sample config and had to add a few parameters to get it working. It's important to set the charset and table prefix on the master and slave config.  I also had to disable server status caching to get it working. The yii logic for caching status seems to be broken with my particular implementation.  

`            // configuration for the master
            'dsn' => "mysql:host=" . getenv('DB_SERVER_WRITE') . ";dbname=" . getenv('DB_DATABASE'),
            'username' => getenv('DB_USER'),
            'password' => getenv('DB_PASSWORD'),
            'tablePrefix' => getenv('DB_TABLE_PREFIX'),

            // don't cache server status for now...
            'serverStatusCache' => false,
            
            // common configuration for slaves
            'enableSlaves' => true,
            'slaveConfig' => [
                'dsn' => "mysql:host=". getenv('DB_SERVER_READ') .";" . "dbname=" . getenv('DB_DATABASE') ,
                'username' => getenv('DB_USER'),
                'charset' => 'utf8',
                'password' => getenv('DB_PASSWORD'),
                'tablePrefix' => getenv('DB_TABLE_PREFIX'),
            ],

            // list of slave configurations
            'slaves' => [
                [
                    'dsn' => "mysql:host=". getenv('DB_SERVER_READ') .";" . "dbname=" . getenv('DB_DATABASE') ,

                ],
            ],`

**Comment by jacksutherland** [comment]
Anybody know if it's possible to implement something like this in Craft 2? And if so where it would be implemented?

**Comment by angrybrad** [comment]
> We have a couple sites that are replicated on 2 servers, with a master/slave setup that requires the slave to be read only. Craft 2 runs smoothly with this configuration,

Thought you already had it working on Craft 2?

**Comment by angrybrad** [comment]
@jacksutherland Honestly I'm not even sure how you got it working on Craft 2 without hacking some core files. There's no real clean way to override core components like there is in Craft 3.

**Comment by jacksutherland** [comment]
OK. I assumed that would be the case. Thanks.

**Comment by lesaff** [comment]
Tested read replica on `3.3.6` against AWS RDS Aurora and it works. I've modified core codes to allow slaves and settings through `.env`. Can I make a PR for this?

**Comment by brandonkelly** [comment]
@lesaff Go for it :)

**Comment by brandonkelly** [comment]
We just updated the docs with an example of how to configure Craft for read/write splitting: https://docs.craftcms.com/v3/config/app.html#database-component

Note this example is cleaner than the other code examples in this thread, as it calls [craft\helpers\App::dbConfig()](https://docs.craftcms.com/api/v3/craft-helpers-app.html#method-dbconfig) as a starting point for the `$config` array.

**Comment by parthi-me** [comment]
@brandonkelly We followed the documentation and it doesn't work as expected. We think the problem is in somewhere the PDO connection setup. 

Following DNS setting not working, an failed with memory exception error(incorrect error also).
['dsn' => "xxxxxx-slave1.xxxxxx.rds.amazonaws.com"],

But when we use the following DNS setting it works,
['dsn' => "mysql:host=xxxxxxx-slave1.xxxxxxx.rds.amazonaws.com;dbname=xyxyxy;port=3306"],

Could someone check and fix it, please.
