### ISSUE TITLE
Random Twig Template Loading Error

### ISSUE THREAD

**Issue by davist11** [craftcms/cms#2900]
### Description
We've started to get some sporadic twig template loading errors, always referencing the same template. This is the first template that is being included in our layout. But if you refresh the page, the error goes away.

```
craft\web\twig\TemplateLoaderException: Unable to find the template “_partials/global-header” in "_layouts/app" at line 22. in /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/TemplateLoader.php:122
Stack trace:
#0 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/TemplateLoader.php(75): craft\web\twig\TemplateLoader->_resolveTemplate('_partials/globa...')
#1 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Environment.php(270): craft\web\twig\TemplateLoader->getCacheKey('_partials/globa...')
#2 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Environment.php(350): Twig_Environment->getTemplateClass('_partials/globa...')
#3 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Environment.php(40): Twig_Environment->loadTemplate('_partials/globa...', NULL)
#4 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(330): craft\web\twig\Environment->loadTemplate('_partials/globa...', NULL)
#5 /Users/tdavis/sites/hamilton/storage/runtime/compiled_templates/c3/c3b76555c77bb82f4f4795b442df2d3ea019c55612a657dca75bccb51c6458d5.php(64): Twig_Template->loadTemplate('_partials/globa...', '_layouts/app', 22)
#6 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_d98899b25fe8f0db05db0a86f37f129a4d5f3e5a1305bb1466466e12d2f3451b->doDisplay(Array, Array)
#7 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#8 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#9 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#10 /Users/tdavis/sites/hamilton/storage/runtime/compiled_templates/83/83bdc225b2e83c45d350aeec2a7bab924107a04e92ed3e6af6f59345fb907997.php(39): craft\web\twig\Template->display(Array, Array)
#11 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_50a5c29cf92e11ff1ff0aaa40ffcc312081827a107ba83b3c672ce1bc41ab219->doDisplay(Array, Array)
#12 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#13 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#14 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#15 /Users/tdavis/sites/hamilton/storage/runtime/compiled_templates/f1/f1d743e33b3e57ff8115d9c361a74eb65127bd16ee33c620b0677543cf645087.php(42): craft\web\twig\Template->display(Array, Array)
#16 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_3e4d03b7764528ede21ea70b79a5f26de55032abf9b2f87cb9f8bf0c08ba38d2->doDisplay(Array, Array)
#17 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#18 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#19 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#20 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#21 /Users/tdavis/sites/hamilton/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#22 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/View.php(305): Twig_Environment->render('_indices/docume...', Array)
#23 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/View.php(352): craft\web\View->renderTemplate('_indices/docume...', Array)
#24 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Controller.php(128): craft\web\View->renderPageTemplate('_indices/docume...', Array)
#25 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/controllers/TemplatesController.php(78): craft\web\Controller->renderTemplate('_indices/docume...', Array)
#26 [internal function]: craft\controllers\TemplatesController->actionRender('_indices/docume...', Array)
#27 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#28 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#29 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Controller.php(76): yii\base\Controller->runAction('render', Array)
#30 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#31 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(273): yii\base\Module->runAction('templates/rende...', Array)
#32 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#33 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(262): yii\web\Application->handleRequest(Object(craft\web\Request))
#34 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#35 /Users/tdavis/sites/hamilton/public/index.php(39): yii\base\Application->run()
#36 {main}
```

### Steps to reproduce

I'm not totally sure since it randomly occurs, but potentially:

`index.html`
```
{% extends '_layouts/app' %}

{% set title = 'Test Page' %}

{% block content %}
    Content here
{% endblock %}
```

`_layouts/app`
```
{% include '_partials/global-header' %}
```

### Additional info

- Craft version: Craft Pro 3.0.8
- PHP version: 7.0.30
- Database driver & version: MySQL 5.7.22
- Plugins & versions:

<table>
<tbody>
                            <tr>
                    <th class="light">Algolia</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Amazon S3</th>
                    <td>1.0.8</td>
                </tr>
                            <tr>
                    <th class="light">Asset Rev</th>
                    <td>6.0.0</td>
                </tr>
                            <tr>
                    <th class="light">AsyncQueue</th>
                    <td>1.3.2</td>
                </tr>
                            <tr>
                    <th class="light">Automatic Site Switch</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Calendar</th>
                    <td>2.0.1</td>
                </tr>
                            <tr>
                    <th class="light">Certificates</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Craft Commerce</th>
                    <td>dev-master</td>
                </tr>
                            <tr>
                    <th class="light">Environment Label</th>
                    <td>3.1.3</td>
                </tr>
                            <tr>
                    <th class="light">Field Manager</th>
                    <td>2.0.2</td>
                </tr>
                            <tr>
                    <th class="light">Flat Categories</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Forms</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Freeform Pro</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Geo Cookie</th>
                    <td>1.1.2</td>
                </tr>
                            <tr>
                    <th class="light">Hamilton Utility</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Importer</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Inlin</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Inventory</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Redactor</th>
                    <td>2.1.0</td>
                </tr>
                            <tr>
                    <th class="light">Sidebar Toggle</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th class="light">SimpleSentry</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Super Table</th>
                    <td>2.0.7</td>
                </tr>
                            <tr>
                    <th class="light">Taxes</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Twig Perversion</th>
                    <td>2.0.3</td>
                </tr>
                    </tbody>
                    </table>

**Comment by brandonkelly** [comment]
Is this happening on a load-balanced environment? Maybe it only occurs when the environment scales up or something?

**Comment by davist11** [comment]
It is not a load balanced environment. I think we tracked it down to a custom plugin that was running on a cron job. That controller was calling a service that set the template mode:

```
$view = Craft::$app->getView();
$this->oldTemplateMode = $view->getTemplateMode();
$view->setTemplateMode($view::TEMPLATE_MODE_CP);
$this->view = $view;
```

And then reverted the template mode: 

```
public function __destruct() {
    $this->view->setTemplateMode($this->oldTemplateMode);
}
```

Are we doing something wrong? We were planning on moving these templates into the main template directory to avoid this error, but would be useful to know moving forward if we should have handled this differently.

**Comment by brandonkelly** [comment]
Is that code (or anything like it) happening on the same requests where you’re getting that error? If it’s only happening on a cron job, then it should be unrelated.

**Comment by davist11** [comment]
It shouldn't have been occurring on the same request;, this is what the main plugin class looks like

```
public function init() {
    parent::init();

    // Add Algolia variable to Twig to access settings
    Craft::$app->getView()->getTwig()->addGlobal('algolia', Algolia::getInstance()->settings);

    $this->setComponents([
        'reindex' => Reindex::class,
    ]);

    Event::on(Elements::class, Elements::EVENT_AFTER_SAVE_ELEMENT, function(Event $event) {
        $element = $event->element;

        $this->reindex->queueElementId($element->id);
        $this->reindex->queueRelatedElementIds($element->id);
    });

    Event::on(Elements::class, Elements::EVENT_BEFORE_DELETE_ELEMENT, function(Event $event) {
        $element = $event->element;

        $this->reindex->purgeElement($element);
    });


    Event::on(
        Utilities::class,
        Utilities::EVENT_REGISTER_UTILITY_TYPES,
        function(RegisterComponentTypesEvent $event) {
            $event->types[] = AlgoliaUtility::class;
        }
    );
}
```


Our other developer ended up moving some code around in the main service, and it seems to have resolved the problem 🤷‍♂️ 

![screen shot 2018-06-05 at 4 04 06 pm](https://user-images.githubusercontent.com/199985/40999829-18d55918-68da-11e8-9b34-a2cd04687402.png)

**Comment by brandonkelly** [comment]
Huh, strange, but glad you got it solved!
