### ISSUE TITLE
Redactor: link to entry adding too many slashes

### ISSUE THREAD

**Issue by thaoms** [craftcms/cms#2902]
After using the 'link to entry' button this href gets added, after I submit it gets removed because of the 4 slashes.

`<a href="http:////xxx.xxx.xx/contact#entry:3">`

For now I'm just removing 2 slashes manually and everything works fine.

PHP 7.1.15
Craft Pro 3.0.8
Redactor 2.1.0

**Comment by thaoms** [comment]
It might be related to the url protocol (relative):

```
'siteUrl' => [
    'xxx' => '//xxxxx.xx/',
    'xxx' => '//xxxxx.xx/',
],

```

**Comment by andris-sevcenko** [comment]
Gotcha. Able to reproduce on [redactor site](https://imperavi.com/redactor/), submitted a support ticket.
