### ISSUE TITLE
Field `isEmpty()` deprecation error seems wrong

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#2905]
Craft CMS 3.0.8: In `src/based/Field.php` we have this:

```
    /**
     * @inheritdoc
     */
    public function isValueEmpty($value, ElementInterface $element): bool
    {
        $reflection = new \ReflectionMethod($this, 'isEmpty');
        if ($reflection->getDeclaringClass()->getName() !== self::class) {
            Craft::$app->getDeprecator()->log('Field::isEmpty()', 'Fields’ isEmpty() method has been deprecated. Use isValueEmpty() instead.');
        }

        return $this->isEmpty($value);
    }

    /**
     * @param mixed $value
     * @return bool
     * @deprecated in 3.0.0-RC15. Use isEmpty() instead.
     */
    public function isEmpty($value): bool
    {
        // Default to yii\validators\Validator::isEmpty()'s behavior
        return $value === null || $value === [] || $value === '';
    }
```

I'm pretty sure the intent was to deprecate `isValueEmpty()` in favor of just `isEmpty()` -- but if it's the other way around, something still isn't quite right here...

**Comment by lindseydiloreto** [comment]
Agreed. Either the deprecation message is wrong, or it's in the wrong place.

**Comment by michtio** [comment]
I changed everything from `isEmpty()` to `isValueEmpty()` because of this .. so what should it be ? :)

**Comment by pauljohnston** [comment]
I presume this is what is causing this error?

`Argument 2 passed to craft\base\Field::isValueEmpty() must implement interface craft\base\ElementInterface, null given, called in /vendor/craftcms/cms/src/fields/Number.php on line 152 and defined in /vendor/craftcms/cms/src/base/Field.php:311`

**Comment by brandonkelly** [comment]
The deprecation error is correct. You should be using `isValueEmpty()` now.

We can’t put the deprecation error in `isEmpty()` because then it would  never get hit*, as outdated plugins are by definition overriding that method.

*unless they call `parent::isEmpty()`, but we can’t count on that.

**Comment by lindseydiloreto** [comment]
@brandonkelly I don't see how that can possibly be right. The warning makes no sense here...

https://docs.craftcms.com/api/v3/craft-base-field.html#method-isempty

<img width="499" alt="isEmpty" src="https://user-images.githubusercontent.com/5309692/40375221-de8389e6-5d9f-11e8-9c61-22ba8f611227.png">

**Comment by brandonkelly** [comment]
Ah... I was looking at the deprecation log, not the `@deprecated` flag. That is in fact wrong; it should say to use `isFieldEmpty()` instead. Will update…
