### ISSUE TITLE
Unable to select file from asset browser modal

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/cms#2906]
### Description

I'm seeing the following JS error when trying to link to an asset using the "File" button in Redactor:

`TypeError: t.search is not a function [redactor.js:16712:16]`

The error is thrown when I hit the "Select" button in the asset browser modal.

- Craft version: 3.0.8

**Comment by andris-sevcenko** [comment]
This definitely belongs in `craftcms/redactor`. Can you reopen this issue there? Also, please add what version of the Redactor plugin you're using.

**Comment by andris-sevcenko** [comment]
Also, when you do, can you, please, add a full stack trace for that JS error? Thanks!
