### ISSUE TITLE
Make Craft CMS database migration more clear in front-end

### ISSUE THREAD

**Issue by jordikroon** [craftcms/cms#2914]
### Description

We regularly update our Craft CMS version (as it should). When that happens in an environment where multiple developers work on the same project, we get confused developers.

A developer opens the homepage, and gets an 503 ServiceUnavailableHttpException. This is because _processUpdateLogic throws it. Then a developer should visit the /admin route, and the database schema will update.
 
We'd like to have ServiceUnavailableHttpException throw a message: e.g visit the CP to perform a database update. Right now it's not clear if it's either a programming error made by the developer or a Craft update that should be performed.

### Additional info

- Craft version: 3.0.9
- PHP version: 7.1.16
- Database driver & version: MariaDB 10
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
I’m not sure that it’s a good idea to display info about the system status on the front end. Better to just remember that when the front end is giving 503’s, you can learn why by accessing the Control Panel.
