### ISSUE TITLE
Simplify Field Layout by hiding tab/label when there's only one tab

### ISSUE THREAD

**Issue by michaelrog** [craftcms/cms#2915]
As mentioned in #2911, it sometimes feels silly to show the tab UI, with a generic/meaningless tab title, when there's only one tab.

Where the Field Layout only has one tab, showing the single tab or its title is probably not valuable, because there aren't any other field groupings to navigate to or differentiate between. In those cases, I propose hiding the tab UI altogether, i.e. only showing the tab UI in Field Layouts where there will be more than one tab.

**Comment by brandonkelly** [comment]
Made this change for Craft 3.4!
