### ISSUE TITLE
Inefficient Caching with templatecachequeries

### ISSUE THREAD

**Issue by funnylookinhat** [craftcms/cms#2916]
### Description
A PR was recently merged that fixed a memory issue for pages with lots of queries that involved several eager-loaded elements: https://github.com/craftcms/cms/pull/2904

It seems like the entire point of this code is to store the query object in the database:
https://github.com/blasvicco/cms/blob/develop/src/services/TemplateCaches.php#L227-L243

The only place I'm aware of that base64 encoded payload being decoded is here: https://github.com/craftcms/cms/blob/e916d854d869d55de286c0e2ffe5f4e1161d8219/src/queue/jobs/DeleteStaleTemplateCaches.php#L82-L85

It seems like the only purpose of that then is to store the element IDs that are affected by the query - and if that's the case, would it make sense to update the `templatecachequeries` to either have a list of element IDs that are affected, or add an additional table that joins the affected IDs to each templatecachequery ?

As an example, we have a page that eager-loads almost a dozen other elements for a given entry - and there are hundreds of entries on that single page.  Updating how these query caches are managed would drastically improve performance of pages like that and simplify the template caching process.

We're more than happy to do the work for this, but before we go down that road I wanted to gut-check our suspicions with you all and see if we were looking at this in the wrong way.

### Steps to reproduce

See #2903 for additional details and steps to reproduce. 

### Additional info

- Craft version: 3.0.9
- PHP version: 7.0.12

**Comment by brandonkelly** [comment]
Element IDs affected by the query are stored in a separate table (`templatecacheelements`). The point of storing the queries is to see if there are any elements that shoud _start_ showing up in a cached template, which weren’t included when the cache was created.

The most obvious example of this would be a News index page, which included entries 1-10 when the template was first cached. Then when entry 11 is created, the DeleteStareTemplateCaches job is run, to see if entry 11 should show up in any cached templates, by re-running element queries, and seeing if entry 11 comes up in the results.

**Comment by funnylookinhat** [comment]
Awesome, great - thank you for the thorough explanation!

**Comment by blasvicco** [comment]
I'm still thinking that the serialization should be avoided. We found for example that the `$elementQuery` in [here](https://github.com/blasvicco/cms/blob/develop/src/services/TemplateCaches.php#L227)  could contain an instance of objects like `Aws\S3\S3Client` that **are not serializable**, resulting in a RuntimeException:

<img width="1280" alt="screen shot 2018-05-25 at 20 07 37" src="https://user-images.githubusercontent.com/1821068/40559549-68330612-6057-11e8-84e3-25ccb71a6777.png">

why we can not store just the raw queries?
