### ISSUE TITLE
Tags with required fields can be saved even if no value is set 

### ISSUE THREAD

**Issue by ul8** [craftcms/cms#2918]
### Description

I would expect that a user cannot create a new tag without setting a value of a required field of the tag's field layout. Not so.  Only when I double click the tag and try to save in that little popup I get an error message. Is that by design, or an omission?

### Steps to reproduce

1. Create a tag group, add a "required" field to its field layout (I used a category type field)
2. Create a section and add the above tag as a field to its entry type field layout
3. Add a new entry to that section. 
4. In the entry, add a new tag, then save the entry.

--> The tag will be saved even though the required field has not been set.

### Additional info

- Craft version: 3.0.9
- PHP version: 7.0.30
- Database driver & version: MySQL 5.7.22
- Plugins & versions:
Architect	2.2.8
AsyncQueue	dev-master
Control Panel Nav	2.0.6
Cookies	1.1.9
Dumper	1.2.1
Eager Beaver	1.0.3
Environment Label	3.1.3
Guide	1.2.1
ImageOptimize	1.4.32
Minify	1.2.8
Redactor	2.0.1
SEOmatic	3.0.18
Typed link field	1.0.8
Typogrify	1.1.10

**Comment by brandonkelly** [comment]
It’s by design, as the UI for creating tags doesn’t even give authors an option to edit custom field values until after it’s saved. That said, #820 will provide a way to create tags while enforcing custom field validation rules.

**Comment by ul8** [comment]
Thanks. I would argue that maybe authors _should_ be given that option, maybe as simple as immediately showing the tag edit popup once the "+ tag" button is clicked (maybe only if there are any fields defined for the tag group). Anyway I don't know the big picture planning I'm sure you'll find a good solution.

**Comment by brandonkelly** [comment]
Yeah I guess rather than saying it’s “by design” I should say that it’s a known issue without a decent solution right now, but it will be solved by #820.
