### ISSUE TITLE
Broken activation link

### ISSUE THREAD

**Issue by thaoms** [craftcms/cms#2919]
When sending an activation mail to a user the url starts with // when using protocol relative site urls.

Hey xxxx

Thanks for creating an account with xxxx! To activate your account, click the following link:

`
//xxxx.com/actions/users/set-password?code=xxxxxxxxxxxx&id=xxxxxxxxxxxx
`
If you were not expecting this email, just ignore it.

```

'production' => [
	'siteUrl' => [
	    'xxxx' => '//www.xxxxxxx.xx/',
	    'xxxx' => '//www.xxxxxxx.xx/',
	],
],
```

### Additional info

- Craft version: 3.0.9
- PHP version: 7.1.15
- Database driver & version: MySQL 5.7.20

**Comment by brandonkelly** [comment]
Fixed for the next release, thanks!
