### ISSUE TITLE
Calling getElementById with a matrixBlock causes an error

### ISSUE THREAD

**Issue by efatsi** [craftcms/cms#2924]
### Description

`Craft::$app->getElements()->getElementById($elementId);` where the element is a MatrixBlock is blowing up.

Error message is:
```
Argument 1 passed to craft\services\Matrix::getContentTableName() must be an instance of craft\fields\Matrix, instance of craft\fields\Entries given
```
at line [src/elements/db/MatrixBlockQuery.php:257](https://github.com/craftcms/cms/blob/5f038f44564921b5f3d07d5e1a900fc6e4f6df2b/src/elements/db/MatrixBlockQuery.php?utf8=%E2%9C%93#L257)

### Additional info

Craft version: Craft Pro 3.0.9
PHP version: 7.0.30
Database driver & version: MySQL 5.7.22
Plugins & versions:
```
Algolia               1.0.0
Amazon S3             1.0.8
Asset Rev             6.0.0
AsyncQueue            1.3.2
Automatic Site Switch 1.0.0
Calendar              2.0.1
Certificates          1.0.0
Craft Commerce        dev-master
Environment Label     3.1.3
Field Manager         2.0.2
Flat Categories       2.0.0
Forms                 2.0.0
Freeform Pro          2.0.0
Geo Cookie            1.1.2
Hamilton Utility      1.0.0
Importer              1.0.0
Inlin                 2.0.0
Inventory             1.0.0
Redactor              2.1.0
Sidebar Toggle        2.0.0
SimpleSentry          1.0.0
Super Table           2.0.7
Taxes                 1.0.0
Twig Perversion       2.0.3
```

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you search for the error in `storage/logs/web.log` and post the stack trace that follows it?

**Comment by efatsi** [comment]
Sorry for the delay, I'm unable to reproduce this anymore as well.

**Comment by brandonkelly** [comment]
Thanks for the update!
