### ISSUE TITLE
provide alternate h6 styles within rich text input field.

### ISSUE THREAD

**Issue by tmulry** [craftcms/cms#2927]
### Description

The style of heading 6 in the wysiwyg editor is drastically different than h1-h5.  The the main issue is that the text displays as gray and uppercase, which makes it difficult to review capitalization.   

### Steps to reproduce

1 . choose an entry with a rich text(redactor) field.  
2. enter a text paragraph, and change the style, using the dropdown to "Heading 6"

the h6-styles have a special mixin defined here: https://github.com/craftcms/cms/blob/29691a336fa983db12e2603ae9f7d47f158f5745/lib/craftcms-sass/_mixins.scss#L303

### Additional info

- Craft version: Craft Pro 3.0.9
- PHP version: 7.2.1

- Database driver & version: MySQL 5.5.5
- Plugins & versions: Redactor | 1.1.0

<img width="827" alt="screen shot 2018-05-28 at 9 31 22 pm" src="https://user-images.githubusercontent.com/4219434/40635595-63b58e78-62c0-11e8-9b48-4ed850f9e3b2.png">

**Comment by narration-sd** [comment]
Sounds like @lindseydiloreto 's plugin may be useful for you? 

    https://github.com/doublesecretagency/craft-cpcss

Some notes here also: 

    https://craftcms.stackexchange.com/questions/19373/change-font-of-redactor-ii

**Comment by brandonkelly** [comment]
The styling was intentional (even Redactor’s core CSS will force H6’s to be all-uppercase), but you make a good point about that making it hard to review casing. So as of the next release, text-transform will be back to normal.
