### ISSUE TITLE
Matrix blocks disappearing after accessing

### ISSUE THREAD

**Issue by newtonne** [craftcms/cms#2929]
### Description

Something strange is happening with matrix fields. It looks like as soon as I query by type, I then lose the ability to access any blocks that are not of that type. See the following example from my entry template:

    <p>Number of blocks in article matrix: {{ entry.article | length }}.<br>
    Types of block:</p>
    <ul>
    {% for block in entry.article.all() %}
        <li>{{ block.type }}</li>
    {% endfor %}
    </ul>

    <p>Print something from the first textBlock block:<br>
    {{ entry.article.type('textBlock').one().text }}</p>

    <p>Number of blocks in article matrix: {{ entry.article | length }}.<br>
    Types of block:</p>
    <ul>
    {% for block in entry.article.all() %}
        <li>{{ block.type }}</li>
    {% endfor %}
    </ul>

Which is producing the following output:

Number of blocks in article matrix: 5.
Types of block:

imageBlock
textBlock
imageBlock
textBlock
imageBlock

Print something from the first textBlock block:
This is text in the first text field

Number of blocks in article matrix: 2.
Types of block:

textBlock
textBlock

### Steps to reproduce

1. Create a matrix field called with 2 block types, textBlock and imageBlock
2. Add a plain text field called text to the textBlock block type
3. Set up a channel and add this field to an entry type
4. Create a new entry for the channel. Add a number of imageBlock and textBlock blocks
5. Paste the code above into the entry template for the channel

### Additional info

- Craft version: 3.0.9
- PHP version: 7.1.17
- Database driver & version: MySQL 5.5.5

**Comment by andygrn** [comment]
I'm seeing the same thing in 3.0.9 for Entries fields too. A type query will wipe out results not of that type for future queries on the field.

**Comment by newtonne** [comment]
Just looked through the docs again and figured it out:

https://docs.craftcms.com/v3/changes-in-craft-3.html#cloning-element-queries

In the above example, I think I would need to do something like:

    {% set article = entry.article %}

at the top. And then query:

    {{ clone(article).type('textBlock') }}
