### ISSUE TITLE
"Delete" Element action missing when viewing "all entries"

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#2933]
Not sure if this is a bug or by-design. Seems odd to me, though.

![screen shot 2018-05-30 at 10 25 36 am](https://user-images.githubusercontent.com/18329/40726607-13ceb7c4-63f4-11e8-9287-9488c50f1c10.png)

**Comment by brandonkelly** [comment]
It’s by design because the available element actions are determined per-source, and it’s hard to know if the user will have permission to delete all the entries, especially if any singles are  going to be listed (which are never deletable from here).
