### ISSUE TITLE
Show a count/progress when updating Asset indexes

### ISSUE THREAD

**Issue by ryanmasuga** [craftcms/cms#2934]
### Description
Would it be possible to show actual numbers like “Indexing: 341/18405” near the progress bar when updating Asset indexes? That progress bar is nice looking, but when you run indexes that take upwards of 40 minutes on directories that have tens of thousands of assets in them, seeing real numbers would make me _feel_ better.

Suggestion (before / after):

![screen shot 2018-05-30 at 1 56 31 pm](https://user-images.githubusercontent.com/988995/40738339-4c8a5e02-6411-11e8-823d-49d98b7a72eb.png)

Not sure how that would work when selecting multiple asset sources to index at the same time, but food for thought.

**Comment by narration-sd** [comment]
I think this is a sound idea, Ryan, and in fact I've had a minimally invasive PR which can make it straightforward to provide, in the hopper for a while -- think it got lost in the Craft 3 clusure needs.

I'll have a look shortly to see if it needs anything to be up to date with the current develop branch -- having done the necessary merges several times before -- https://github.com/craftcms/cms/pull/1931

I've been using the functionality in the way you're envisioning, to show progress on complex tasks I run on a  remote database to Craft Entries agent which is 'out there' from a custom job, if not quite suitable for a standard store plugin. The screen display is pretty much just as you propose -- I highjacked the CP HUD to show this.

**Comment by narration-sd** [comment]
CC: @andris-sevcenko ^^

**Comment by narration-sd** [comment]
Ok, PR re-merged with latest Craft dev-develop, and checked kout via running up my Craft 3 conversion of the agent plugin. Much fun getting that vm sane again, naturally, but interesting to watch Craft 3 late adjustments sort of float by. I think I liked the shadowed CP tabs before they went away, but seem to recall there was a reason.

Mini-screenshots below show result of the PR working -- in the removing entries pic, the number decrements as blocks of Entries are removed: we are on 100 left out of 200 at beginning, added by four  exercises of the Manual Posting button at 50 Entries created from remote ms-sql database content. In real life, the plugin back-ends an official furniture standards website in the UK.

The PR has an owner tag added to Jobs, besides the state which is giving the changing messages. This allows selective 'adjustments' (i.e. kills) on Jobs, which is also rather handy, keeping for example this agent's job/task safeties from interfering with Craft or anyone else's queued Jobs.

![posting-entries](https://user-images.githubusercontent.com/247945/40749662-937acd9e-6419-11e8-9307-442262c94d3a.png)

![removing-entries](https://user-images.githubusercontent.com/247945/40749661-935949da-6419-11e8-85cc-af2df8a29e11.png)
