### ISSUE TITLE
Can't save "0" in Plain Text field

### ISSUE THREAD

**Issue by natebeaty** [craftcms/cms#2935]
### Description

Trying to enter 0 in a Plain Text field, it just gets emptied out on save. This was an issue for us, as we have a required field, and need to save 0 (zero) as the content for a statistic, and it won't let us save the entry, giving a validation error that the field is blank.

### Steps to reproduce

1. Add Plain Text field.
2. Try to enter 0 as the content and save.
3. It shows as an empty field, or if required, it won't even let you save the entry.

### Additional info

- Craft version: 3.0.9
- PHP version: 7.2.4
- Database driver & version: MySQL 5.7.21
- Plugins & versions:
Asset Rev	6.0.0
CKEditor	1.0.0-beta.2
Command Palette	3.1.4
CP Field Inspect	1.0.4
Expanded Singles	1.0.3
Incognito Field	1.0.0
Similar	1.0.0
Sprout Active	2.0.6
Super Table	2.0.7
Wordsmith	3.0.2

**Comment by angrybrad** [comment]
Already resolved in https://github.com/craftcms/cms/commit/5bc978a0cc24e83870d34584139bc19cedd11c40 for the next release!
