### ISSUE TITLE
Copy Asset URLs (feature request)

### ISSUE THREAD

**Issue by proimage** [craftcms/cms#2944]
Can there be either a menu item for copying the URL(s) of the selected asset(s) (see below), or if "Preview file" isn't able to handle a filetype, include a direct link to the file in the preview window (or both)? Something like, "Preview not available. You can try to [open this file in a new tab](#)."

![image](https://user-images.githubusercontent.com/1027523/40860793-59a9d254-65ef-11e8-91cd-c374afc9c2c6.png)

**Comment by brandonkelly** [comment]
@proimage Thanks for posting these. Please keep each issue limited to a single feature request though, so we can track progress on them individually. (You can edit this one to just include one of the FR’s, and then post two new issues for the others.)

**Comment by proimage** [comment]
Whoops, of course! Done.

**Comment by jsunsawyer** [comment]
Yes! It seems that **Preview File** replaced **View Asset** when asset previews got added. Definitely confusing for users coming from Craft 2.

@proimage For now, you can enable the **Link** option to quickly view an asset's source.

**Comment by proimage** [comment]
> For now, you can enable the Link option

What is this "Link option" of which you speak?

**Comment by brandonkelly** [comment]
Doh, forgot about that – so this is already implemented (or something close enough, anyway). Just click the gear icon below the volume list on the Assets page, and check the box next to “Link”, for whichever volumes you want to be able to access files in directly.

**Comment by bstein-clever** [comment]
I ran into this today, as well. It's extremely intuitive coming from Craft 2, especially since I need to add the link column to *all* of my asset folders, which is a little frustrating.

Add one more vote to having the ability to open a link to the asset if "preview" doesn't work for the file type.

**Comment by brandonkelly** [comment]
Fair enough, I’ll reopen.

**Comment by johandouma** [comment]
As mentioned above, I am aware that we can add the Link as a column, but there are already quite a few options in the cog drop down that relate to copying, eg previewing, download, I think it would make sense to add a Copy URL in that drop down as well.

**Comment by ryanmasuga** [comment]
It never occurred to me to add the Link column in the list view, but this feels a bit like a cheat considering how many other options are already in the gear dropdown. Also, I pretty much have to go through 30-40 asset volumes and remember to add that to the view. I'd assume that so long as "Assets in this volume have public URLs" is checked, there could be a way to get that from the gear in almost exactly the same way as "Copy reference tag" works.

**Comment by khalwat** [comment]
[Video of how to add a Link column](https://twitter.com/nystudio107/status/1154068882614870017?s=20) for anyone who might be searching on how to do this.

**Comment by khalwat** [comment]
In case the PR was missed: https://github.com/craftcms/cms/pull/4499

**Comment by bstein-clever** [comment]
And by "the PR" you really mean "one that was closed with no explanation"? :(

**Comment by CreateSean** [comment]
The link column should be on by default

**Comment by rungta** [comment]
A good workaround for this (until we get a permanent fix) is enabling the _Link_ column (as suggested by multiple folks) by default using the [Element Index Defaults](https://github.com/verbb/element-index-defaults) plugin, with the following config:

```php
// config/element-index-defaults.php

return [
    'Asset' => [
        'title',
        'filename',
        'size',
        'dateModified',
        'link',
    ]
];

```

**Comment by ldennison-bsd** [comment]
I also support adding a dropdown option for "Copy URL" or something like that. It took me having to lookup this thread to realize I could add the "Link" column to an asset volume. Can't hurt to have the option in both places.

**Comment by jordikroon** [comment]
This has just been released as a [Plugin](https://github.com/reworkdigital/craftcms-adminasseturl). Though it would still be convenient to have this added to the core @brandonkelly 🤞

**Comment by brandonkelly** [comment]
This has been added for Craft 3.5. Thanks @putyourlightson for the initial PR!
