### ISSUE TITLE
Invalid currentSite config setting value: default

### ISSUE THREAD

**Issue by Saboteur777** [craftcms/cms#2947]
### Description

After simply upgrading from a bilingual Craft 2 installation I got a `Invalid currentSite config setting value: default` error on /admin. 

```
select * from craft_sites;
+----+---------+---------+----------------------+--------+----------+---------+-----------------------------+-----------+---------------------+---------------------+--------------------------------------+
| id | groupId | primary | name                 | handle | language | hasUrls | baseUrl                     | sortOrder | dateCreated         | dateUpdated         | uid                                  |
+----+---------+---------+----------------------+--------+----------+---------+-----------------------------+-----------+---------------------+---------------------+--------------------------------------+
|  1 |       1 |       1 | Webmenedzser.hu (hu) | hu     | hu       |       1 | https://www.webmenedzser.hu |         1 | 2018-06-01 17:36:46 | 2018-06-01 17:37:10 | e5b4ae61-27ee-400e-8501-a9801806de9f |
|  2 |       1 |       0 | Webmenedzser.hu (en) | en     | en       |       1 | https://www.webmenedzser.hu |         2 | 2018-06-01 17:36:46 | 2018-06-01 17:36:46 | 4c7e6599-6ebd-4f0e-8ca3-dfa0d9cc6e0a |
+----+---------+---------+----------------------+--------+----------+---------+-----------------------------+-----------+---------------------+---------------------+--------------------------------------+
2 rows in set (0.00 sec)
```

Running `update craft_sites set handle="default" where craft_sites.primary=1;` fixed the issue. 

```
select * from craft_sites;
+----+---------+---------+----------------------+---------+----------+---------+-----------------------------+-----------+---------------------+---------------------+--------------------------------------+
| id | groupId | primary | name                 | handle  | language | hasUrls | baseUrl                     | sortOrder | dateCreated         | dateUpdated         | uid                                  |
+----+---------+---------+----------------------+---------+----------+---------+-----------------------------+-----------+---------------------+---------------------+--------------------------------------+
|  1 |       1 |       1 | Webmenedzser.hu (hu) | default | hu       |       1 | https://www.webmenedzser.hu |         1 | 2018-06-01 17:36:46 | 2018-06-01 17:37:10 | e5b4ae61-27ee-400e-8501-a9801806de9f |
|  2 |       1 |       0 | Webmenedzser.hu (en) | en      | en       |       1 | https://www.webmenedzser.hu |         2 | 2018-06-01 17:36:46 | 2018-06-01 17:36:46 | 4c7e6599-6ebd-4f0e-8ca3-dfa0d9cc6e0a |
+----+---------+---------+----------------------+---------+----------+---------+-----------------------------+-----------+---------------------+---------------------+--------------------------------------+
2 rows in set (0.00 sec)

```

### Additional info

- Craft version: 3.0.9
- PHP version: 7.2.5
- Database driver & version: MySQL 5.5.5
- Plugins & versions: not relevant

**Comment by brandonkelly** [comment]
Do you have something like this in `index.php`?

```php
define('CRAFT_LOCALE', 'default');
```

**Comment by Saboteur777** [comment]
Content of `web/index.php`: 

```
<?php
/**
 * Craft web bootstrap file
 */

define('CRAFT_SITE', 'default');

// Set path constants
define('CRAFT_BASE_PATH', dirname(__DIR__));
define('CRAFT_VENDOR_PATH', CRAFT_BASE_PATH.'/vendor');

// Load Composer's autoloader
require_once CRAFT_VENDOR_PATH.'/autoload.php';

// Load dotenv?
if (file_exists(CRAFT_BASE_PATH.'/.env')) {
    (new Dotenv\Dotenv(CRAFT_BASE_PATH))->load();
}

// Load and run Craft
define('CRAFT_ENVIRONMENT', getenv('ENVIRONMENT') ?: 'production');
$app = require CRAFT_VENDOR_PATH.'/craftcms/cms/bootstrap/web.php';
$app->run();

```

**Comment by Saboteur777** [comment]
I should change `define('CRAFT_SITE', 'default');` to whatever handle is in the database?

**Comment by brandonkelly** [comment]
Where did that code come from in the first place?

Craft 2 supported a `CRAFT_LOCALE` constant, which could be set to the locale ID that should be served (e.g. `en_us`), but never something like `default`.

In Craft 3, the old locale IDs have become the new site handles, and the new `CRAFT_SITE` constant is (for now) interchangable with the old `CRAFT_LOCALE` constant – both just specify the site handle now rather than the locale ID.

So there shouldn't be a breaking change here that’s worth mentioning (besides that you should eventually change `CRAFT_LOCALE` to `CRAFT_SITE`, which is mentioned [here](https://docs.craftcms.com/v3/changes-in-craft-3.html#php-constants).

**Comment by Saboteur777** [comment]
It was the default index.php at around RC9. The file is inherited from a project boilerplate which I forgot to update.

**Comment by brandonkelly** [comment]
I just looked through the [history of that file](https://github.com/craftcms/craft/commits/master/web/index.php) and couldn’t find a time when `CRAFT_SITE` was ever defined. So it must have been added to your project at some point; not something we’ll need to worry about as far as upgrade instructions go.

**Comment by Saboteur777** [comment]
I tried to trace down the process how it got added to the project, but now I literally have no clue: 
- it was added with the `init` commit of that repo, 
- it has only 1 commit in its history, so never touched that file, 
- I didn't write this piece of code before

Sorry for the false alarm.
