### ISSUE TITLE
Saving entry without title results in "-1" slug

### ISSUE THREAD

**Issue by RyanRoberts** [craftcms/cms#2954]
### Description
Save an entry without entering title text results in the slug becoming _-1_ which is then saved if the user enters some title text and saves the entry.

FWIW I am using the Sites feature to run two alternate versions of the site as well as the default site.

### Steps to reproduce

1. Create new channel entry or structure
2. Fill out any fields but not the Title field or Slug
3. Save
4. Get prompted to enter the Title text (as it's required, obviously)
5. Enter Title text and save

### Additional info

- Craft version: 3.0.9
- PHP version: 7.2.5
- Database driver & version: MySQL 5.5.5
- Plugins & versions: 

- Amazon S3 | 1.0.8
- Button Box | 2.0.0
- CP Field Inspect | 1.0.4
- Default Tab | 1.2.4
- Field Manager | 2.0.2
- Google Cloud Storage | 1.0.5 (not used)
- Migration Manager | 3.0.10 (not used)
- NSM Fields | 0.0.10
- Redirect plugin for Craft 3 | 1.0.16
- Super Table | 2.0.7

**Comment by brandonkelly** [comment]
I'm not able to reproduce this – when saving an entry without a title & slug, the both fields come back empty with validaiton errors. And if I enter a title at that point, the slug auto-populates as expected.

Check your browser’s JavaScript console – are you getting any JS errors on the page?

If you are still experiencing this, please send a database backup and your composer.json and composer.lock files over to support@craftcms.com, so we can try reproducing with your setup.
