### ISSUE TITLE
Make reference tags localizable

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/cms#2956]
It should be possible to specify a site handle in a reference tag, so the element gets queried for the specified site.

Especially useful when storing a link to an entry for a specific site (e.g. #2945).

Possible syntax: `{entry:123@siteHandle:url}`.

**Comment by timkelty** [comment]
Lots of other issues would be fixed with this:

While Craft core is concerned, it may be fair to consider this an "enhancement", but the resulting behavior from other plugins (e.g. Redactor) seems pretty buggy/broken:

- https://github.com/craftcms/redactor/issues/53
- https://github.com/craftcms/redactor/issues/92
- https://github.com/markhuot/craftql/issues/157

**Comment by mattandrews** [comment]
I would like this feature – we sometimes need to insert links to pages from another locale (eg. "Click here to read this article in another language") and when saving these links, they get rewritten back to the original site.

I'm also not sure if this is related, but it seems that when I use the "Link to an entry" dialog from Redactor, switching sites/locales seems to have no effect on the content:

![locales](https://user-images.githubusercontent.com/394376/53632379-af4f6180-3c0c-11e9-9a36-9e2aa67efc88.gif)

If I view that same section via the Entries panel, I see:

![locales2](https://user-images.githubusercontent.com/394376/53632448-e0c82d00-3c0c-11e9-8a96-979884ea2482.gif)

(eg. those entries are definitely different between locales)

**Comment by timkelty** [comment]
@mattandrews Correct, the site dropdown is broken in the `craftcms/redactor`.

See:
- https://github.com/craftcms/redactor/issues/53
- https://github.com/craftcms/redactor/issues/92

**Comment by timkelty** [comment]
@brandonkelly @andris-sevcenko is there a plan to address this (3.x vs 4.x)?

It is marked as a feature here, but it could resolve actual bugs in craftcms/redactor.

**Comment by brandonkelly** [comment]
We are planning on looking into this (and related #2854 and #3584 issues) for Craft 3.2.

**Comment by davidhellmann** [comment]
@mattandrews is that the same bug I've?
https://github.com/craftcms/cms/issues/4121

**Comment by brandonkelly** [comment]
Added for the next 3.2 Alpha release, using the `@<Site>` syntax shown in the original post. The site can be represented by its ID, UUID, or handle.

**Comment by mattandrews** [comment]
Incredible! Thanks so much 😀
