### ISSUE TITLE
UI bug: scrolling versions drop-down when there are lots of versions

### ISSUE THREAD

**Issue by davidrapson** [craftcms/cms#2957]
Spotted a small bug with the versions drop-down. When you have a lot of versions you can scroll the UI out of view. Any chance of an overflow scroll on this drop-down?

![scroll](https://user-images.githubusercontent.com/123386/40970964-09ce745c-68b4-11e8-8226-3222c35e4b58.gif)

### Additional info

- Craft version: 3.0.9
- PHP version: 7.1.13

**Comment by davidrapson** [comment]
Reading through existing issues it looks like this is a duplicate https://github.com/craftcms/cms/issues/2942 and https://github.com/craftcms/cms/issues/2912

Candidate for a general fix?

**Comment by brandonkelly** [comment]
Yep, the fix in pixelandtonic/garnishjs@ccb7c56 should resolve all of these.
