### ISSUE TITLE
Unknown error when reordering structure

### ISSUE THREAD

**Issue by Emkaytoo** [craftcms/cms#2958]
### Description
User with Admin-level permissions is unable to reorder structures by dragging and dropping. When attempting to reorder entries, the entry appears to move, but an alert appears saying **An unknown error occurred.** Upon refreshing the entries page, the entry has reverted back to it's original position.

### Steps to reproduce

1. Create a multi-level structure, and create two levels of content
2. Reorder the content via drag-and-drop in the Structure's entry section
3. The error will appear

### Additional info
This issue happens consistently and predictably with multi-level structures. On single-level structures, it happens intermittently. Sometimes user can reorder (new position saved), sometimes the error appears.

- Craft version: Pro 3.0.9
- PHP version: 7.1.17
- Database driver & version: MySQL 5.7.12
- Plugins & versions: 

|Plugin|Version|
|:-----|:------|
|Amazon S3|1.0.8|
|Architect|2.2.8|
|Blockonomicon|1.1.1|
|Blockonomicon Super Table Adapter|1.0.0|
|Cookies|1.1.9|
|CP Field Inspect|1.0.4|
|Eager Beaver|1.0.3|
|Element API|2.5.2|
|Element Map|1.0.2|
|Entry Instructions|1.0.0|
|Expanded Singles|1.0.3|
|Freeform Lite|2.0.3|
|Guide|1.2.1|
|ImageOptimize|1.4.33|
|Instant Analytics|1.0.6|
|Json Client|1.0.1|
|Minify|1.2.8|
|Preparse Field|1.0.0|
|Redactor|2.1.0|
|SEOmatic|3.0.18|
|Smart Map|3.1.0|
|Snitch|2.0.1|
|SuperSort|3.0.1|
|Super Table|2.0.7|
|Template Select|2.0.0|
|Twig Profiler|1.0.0|
|Typed link field|1.0.8|
|Typogrify|1.1.10|

**Comment by Emkaytoo** [comment]
**Update**: After reading #2772, I realized this was happening on our `stage` environment. I tried testing on `dev` and was able to reorder an entry successfully. However, I was unable to move the repositioned entry back to it's original spot.

**Conclusion**: this is happening consistently on `stage` and intermittently on `dev`.

**Comment by Emkaytoo** [comment]
This was a result of a load balancer issue. The Craft team recommended using the [Yii 2 Redis extension](https://github.com/yiisoft/yii2-redis) for keeping session data synced.

**Comment by brandonkelly** [comment]
Glad moving to Redis got this sorted!
