### ISSUE TITLE
Elements are not eager-loaded when using `.one()` to execute a query

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/cms#2960]
### Description

I've set up and executed a query specifying some eager-loaded elements, like this:

```twig
{% set menu = craft.entries({
    section: 'menus',
    slug: slug,
    with: [
        ['children']
    ]
}).one %}
```

However, when trying to loop over `menu.children`, I get a deprecation error, suggesting that I must first call `.all()` on the element query. This would indicate that the elements were not eager-loaded.

However, if I use `.all | first`, the element and it's children _are_ eager-loaded:

```twig
{% set menu = craft.entries({
    section: 'menus',
    slug: slug,
    with: [
        ['children']
    ]
}).all | first %}
```

This holds true for eager-loading Matrix blocks, as well.

### Steps to reproduce

1. Define a structure section, or an Entry with a Matrix field;
2. Construct a query (making use of the `with` key to eager-load either the child entries or Matrix blocks), and execute it with `.one()`;
3. Observe a deprecation notice when accessing the child entries or blocks.

### Additional info

- Craft version: Craft Pro 3.0.9
- PHP version:  7.1.16
- Database driver & version: PostgreSQL 10.3
- Plugins & versions:
  - Commerce, 2.0.0-beta.5
  - Redactor, 2.1.0
  - Stripe Gateway, 1.0.2
  - Typogrify: 1.1.10

**Comment by brandonkelly** [comment]
This should have been fixed by 4d6892b048c598db8e430f30e8c369728b1ea2b7, which was in today’s 3.0.10 release. Try updating Craft and let me know if it works for you.

**Comment by AugustMiller** [comment]
Resolved, as far as I'm concerned! 👍

**Comment by brandonkelly** [comment]
Great!
