### ISSUE TITLE
Entry field search input loses focus mid typing on subsequent entry searches

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#2964]
### Description
When adding an entry to an entries field, a search modal pops up allowing you to search and select an entry. When typing, the search occasionally automatically updates the search result (maybe after a ver short pause?). When this happens, the focus stays in the search box and you can continue typing.

After adding an entry, then attempting to add another, the search trigger causes the search field to lose focus, requiring the user to focus the search field again to continue typing.

### Additional info

- Craft version: 3.0.9

**Comment by brandonkelly** [comment]
Fixed, and this made it into the 3.0.10.2 release :)
