### ISSUE TITLE
Issue with registerJsFile() “depends” option 

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#2965]
### Description

When using the `depends` option, the file doesn’t get output in the HTML. No issue when I remove the option.

```php
$basePath = Craft::getAlias('@config/diy-widget/');
$baseUrl = Craft::$app->getAssetManager()->getPublishedUrl($basePath, true);
Craft::$app->getView()->registerJsFile("{$baseUrl}/countdown.js", [
    'depends' => CpAsset::class
]);
```

This used to work before 3.0.10

### Additional info

- Craft version: 3.0.10
- PHP version: 7.1

**Comment by brandonkelly** [comment]
Just released 3.0.10.2 with a fix for this.
