### ISSUE TITLE
You can name a field 'author'

### ISSUE THREAD

**Issue by texasbaptists** [craftcms/cms#2971]
### Description
You can name a field slug `author`, but if you try to call it, for example, `{{entry.author}}` it will get the user that created the entry. not whatever is in the `author` field. I suggest making this a reserved term for fields.

### Steps to reproduce

1. Make a field `author` and make it part of an entry type layout.
2. Create an entry with and fill in `author` with something other than your username.
3. Call out this field in a template. 

### Additional info

- Craft version: 3.0.10.1
- PHP version: 7.5.2
- Database driver & version: MySQL 5.7.22
- Plugins & versions:

**Comment by angrybrad** [comment]
See here for an explanation of why: https://github.com/craftcms/cms/issues/918

And here for when it would get implemented: https://github.com/craftcms/cms/issues/1524
