### ISSUE TITLE
[Feature Request] Add config option to limit the number of "Recent Versions" for entries

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#2976]
Our client has 715 entry versions on their homepage. This is causing the entry in the CP to load very slowly. (Over 3 seconds)

I tested purging all entries with https://github.com/carlcs/craft-deleteentryversions, but this is not an ideal solution as we still want the most recent versions.

A general config option or additional setting under `Enable versioning for entries in this section?` in **Sections** that allowed a limit to be set would keep these pages from growing slower and slower over time.

**Comment by brandonkelly** [comment]
This is actually a bug. Craft 2 only shows the 10 most recent versions, but that limit was accidentally omitted when updating logic for Craft 3. Fixed for the next release.
