### ISSUE TITLE
Feature Request: Add Asset Indexing as a cli action

### ISSUE THREAD

**Issue by sergeifilippov** [craftcms/cms#2980]
It would be great to be able to run Asset Indexing via the `craft cli`.

**Comment by timkelty** [comment]
Converting the indexing process to a Yii queue is pretty critical for any site with a sizeable amount of assets.

We've run into all sort of problems with indexing (latest being https://github.com/craftcms/cms/issues/2876#issuecomment-434434075), which makes indexing basically a "cross your fingers" operation, that's nearly impossible to debug.

**Comment by ryanpcmcquen** [comment]
Is there a way to index assets from a migration script?

**Comment by brandonkelly** [comment]
Not currently.

**Comment by ryanpcmcquen** [comment]
This works for me inside of a migration script for indexing assets on a specific volume:

```php
        try {
            if ($volume = Craft::$app->getVolumes()->getVolumeByHandle('VOLUME_HANDLE')) {
                foreach (Craft::$app->getAssetIndexer()->getIndexListOnVolume($volume) as $item) {
                    Craft::$app->getAssetIndexer()->indexFile(
                        $volume,
                        $item['path'],
                        '',
                        false
                    );
                }

            } else {
                return false;
            }
            return true;

        } catch (\Throwable $e) {
            echo $e->getMessage();
            return false;
        }
```
