### ISSUE TITLE
Globals can't be set per site, in multi-site setup

### ISSUE THREAD

**Issue by milantopalov** [craftcms/cms#2982]
### Description

When I set a Global to a value in 'Site One' this value also appears when I switch to 'Site Two'. i.e. I can't set Global values for each site independently, as per documentation.

### Steps to reproduce

1. add additional site
2. create a global 
3. set a global to a value
4. switch to another site
5. note that the value set is showing for the other site as well - which is a bug

### Additional info

- Craft version: 3.0.10.3 (Pro)
- PHP version: 7.0.30
- Database driver & version: MySQL 5.5.55
- Image driver & version: Imagick 3.4.3 (ImageMagick 6.7.2-7)
- Plugins & versions: 
    - Schematic 4.0.10

**Comment by brandonkelly** [comment]
To set unique values for each site, you need to edit your field’s settings and set its Translation Method to “Translate for each site”.

**Comment by andreasbecker** [comment]
How does this work for an image asset field which isn't translatable? We'd like to set a logo per site in a Global

**Comment by brandonkelly** [comment]
@andreasbecker Relational fields like Assets have a “Manage relations on a per-site basis” setting you can enable.
