### ISSUE TITLE
Element Chiclet Customization

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/cms#2984]
### Description

Currently, all Element chiclets (the nodes that show which Entries, Assets, custom Elements, etc) are attached via a relations field are rendered by the same function, `_getCpElementHtml`, via the `cp.elements.element` hook.

It would be _wonderful_ if we could override this behavior more easily, i.e. customizing just the text, the size, etc. via properties on a custom Element.

This would allow plugin developers to use their own custom Element/Model properties or methods to generate more useful element preview names.

For instance, Commerce Variants only display their `title`, at the moment, which as identified in craftcms/commerce#333, isn't particularly useful on its own.

**Comment by brandonkelly** [comment]
The label is just based on whatever the element’s `__toString()` method returns, which seems right.

Element types can create a [getHtmlAttributes()](https://docs.craftcms.com/api/v3/craft-base-elementinterface.html#method-gethtmlattributes) method, for defining additional HTML `data` attributes that should be added to their element `<div>`. Is that what you mean by custom properties?

**Comment by AugustMiller** [comment]
Ah, this is brilliant! I must not have gotten this deep into the hook, but I think this is plenty good enough for the foreseeable future.

Thank you! 💞
