### ISSUE TITLE
PHP Info Utility Local vs Master Values

### ISSUE THREAD

**Issue by sbossarte** [craftcms/cms#2987]
### Description

I have encountered a case where a web host provides configurations for PHP in a way that override local configuration values for PHP, but leave the master values at a system default that cannot be changed. While the correct values are displayed in a regular `phpinfo()` call, Craft's PHP Info utility prefers displaying the master value if the two differ.

Understandably, due to changes that Yii or other modules may make via `ini_set`, displaying the local value may not be wholly accurate for all requests. It threw me off seeing an unexpected value reported by the utility.

### Additional info

- Craft version: 3.0.10.3
- PHP version: 7.1.18
- Database driver & version: MySQL 5.5.56
- Plugins & versions: None

**Comment by brandonkelly** [comment]
The PHP Info utility actually gets its info from a normal `phpinfo()` call:

https://github.com/craftcms/cms/blob/e43b4dcd9c6924d4da6b120a9416e82b181a2c77/src/utilities/PhpInfo.php#L66

So not sure why your results would differ from the utilities. Any ideas @angrybrad?

**Comment by sbossarte** [comment]
What I mean to say is that the local value (first column) would be a different value from the master value (second column), and that the master value is what's displayed, instead of the local:

https://github.com/craftcms/cms/blob/e43b4dcd9c6924d4da6b120a9416e82b181a2c77/src/utilities/PhpInfo.php#L110

**Comment by brandonkelly** [comment]
Ahh, yeah OK. Feel free to PR it :)

**Comment by sbossarte** [comment]
Alrighty, figured it was best to open the issue first to ask about the behavior.

https://github.com/craftcms/cms/pull/2990

**Comment by angrybrad** [comment]
Merged... thx!
