### ISSUE TITLE
Debug Toolbar animates open on every page load - Chrome

### ISSUE THREAD

**Issue by jeremyabrahams** [craftcms/cms#2994]
### Description

With the Front-End Debug Toolbar checked in the Prefs and open - on each page load the toolbar animates from the right side of the screen. Not only is this distracting but I worry that users with vestibular disorders will experience even greater negative effects. #a11y

### Steps to reproduce

1. Login
2. Admin > My Account > User Preferences
3. Select `Show the debug toolbar on the front end`

### Additional info

- Craft version: `3.0.11`
- PHP version: `7.1.12`
- Database driver & version: `MySQL 5.6.38`

### Observed in
- Chrome 67 > Yes
- Firefox 60 > No
- Safari 11.0.3 > No

### Screencast
https://cl.ly/2f243X0J2P1e

**Comment by brandonkelly** [comment]
I’m not able to reproduce this – the only time the toolbar should animate is when going from collapsed to expanded, or vise-versa. On new page loads it should begin at the same width it was before.

Are you seeing the same behavior in the Control Panel? If not, it is likely some sort of conflict between the toolbar and your website’s JS/CSS.

**Comment by jeremyabrahams** [comment]
Getting it in the CP too.
The screencast I linked was from a stripped down html file containing no CSS/JS.

```<!DOCTYPE html>
<html lang="en">
<head>
  <title>HI</title>
</head>
<body>
  <h1>hello</h1>
</body>
</html>```

**Comment by jalendport** [comment]
@jeremyabrahams I can replicate this on my end as well 👍

**Comment by brandonkelly** [comment]
I was on Chrome 66. Updated to 67 and able to reproduce now.

**Comment by brandonkelly** [comment]
Posted the issue in the yii2-debug repo: yiisoft/yii2-debug#327
