### ISSUE TITLE
New renderObjectTemplate() behavior breaks SEOmatic

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#3002]
In Craft CMS 3.0.10 the following change was made:

* Variables passed into `craft\web\View::renderObjectTemplate()` can now be referenced using the shorthand syntax (e.g. `{foo}`).

The relevant code appears to be:

```
        // Swap out the remaining {xyz} tags with {{object.xyz}}
        $template = preg_replace('/(?<!\{)\{\s*(\w+)([^\{]*?)\}/', '{{ ($1 ?? object.$1)$2|raw }}', $template);
```
...which results in this as a string template when I pass in `{seomatic.meta.mainEntityOfPage}`:

```
{{ (seomatic ?? object.seomatic).meta.mainEntityOfPage|raw }}
```

The problem here is that there _is_ a global Twig variable `seomatic` that I add, but I'm also passing in my own `object.seomatic` variable to `renderObjectTemplate()` and they are _not_ the same. So the effective behavior of this method has changed. I changed the code back to be just:

```
        // Swap out the remaining {xyz} tags with {{object.xyz}}
        $template = preg_replace('/(?<!\{)\{\s*(\w+)([^\{]*?)\}/', '{{ (object.$1)$2|raw }}', $template);
```
...and SEOmatic works again, because it's using the `object` variables I pass in. I guess I'm looking for guidance on this, in terms of whether this functionality is intentional, and now something I need try to work around?

**Comment by khalwat** [comment]
I'm just going to figure out a work-around for this

**Comment by brandonkelly** [comment]
Don’t worry about it :) Fixed for the next release, which is going to go out today.

**Comment by khalwat** [comment]
erf... already did a work-around. Oh well :)

**Comment by narration-sd** [comment]
@khalwat,  many have tried...you can't beat @brandonkelly at his game 😄

**Comment by boboldehampsink** [comment]
This new change breaks my site, see https://github.com/craftcms/cms/commit/0f7880b5272544a61d0646d1d3b127a322394dd9#r29428895
