### ISSUE TITLE
Potentially misleading pricing info

### ISSUE THREAD

**Issue by marflow** [craftcms/cms#3009]
On the website (https://craftcms.com/pricing) and on the in-app upgrade page, the price for a Craft Pro license is given as "$299 plus $59/year for updates". This may be misleading, since people could think the initial cost is $358,-.

Could be worth communicating that $299,- includes 12 months of updates already and $59,- is the price for the optional but recommended update renewal.

**Comment by ostark** [comment]
Fixed now

**Comment by angrybrad** [comment]
Thanks for the reminder!
