### ISSUE TITLE
Display errors on asset index generation

### ISSUE THREAD

**Issue by ul8** [craftcms/cms#3012]
### Description

When the manual asset index generation is running into issues, the backend process will helpfully provide useful error messages while the CP ignores them and pretends everything is fine (no error messages, just a way too quick finishing of the progress bar.

Suggestion: Print the errors in a scrollable element.

### Steps to reproduce

1. Add files that throw an error to an asset volume. In my example, I had file names with character encodings not matching my server setup (legacy files imported from a 10+ years old project originally coming from Windows). Example file name: '$'\326''zsecilmis_3529.jpg. Corrected file name is: Özsecilmis_3529.jpg
2. Trigger a manual asset indexing.

### Additional info

This was the response I got in this example:

```json
{"name":"Exception","message":"Malformed UTF-8 characters, possibly incorrectly encoded.","code":5,"type":"yii\\base\\InvalidArgumentException","file":"/path/to/vendor/yiisoft/yii2/helpers/BaseJson.php","line":133,"stack-trace":["#0 /path/to/vendor/yiisoft/yii2/helpers/BaseJson.php(67): yii\\helpers\\BaseJson::handleJsonError(5)","#1 /path/to/vendor/yiisoft/yii2/web/JsonResponseFormatter.php(119): yii\\helpers\\BaseJson::encode(Array, 320)","#2 /path/to/vendor/yiisoft/yii2/web/JsonResponseFormatter.php(104): yii\\web\\JsonResponseFormatter->formatJson(Object(craft\\web\\Response))","#3 /path/to/vendor/yiisoft/yii2/web/Response.php(1044): yii\\web\\JsonResponseFormatter->format(Object(craft\\web\\Response))","#4 /path/to/vendor/craftcms/cms/src/web/Response.php(185): yii\\web\\Response->prepare()","#5 /path/to/vendor/yiisoft/yii2/web/Response.php(337): craft\\web\\Response->prepare()","#6 /path/to/vendor/yiisoft/yii2/base/Application.php(392): yii\\web\\Response->send()","#7 /path/to/web/index.php(42): yii\\base\\Application->run()","#8 {main}"]}
```

PHP 7.0.30
MySQL 5.7.22
Craft Pro 3.0.12

**Comment by andris-sevcenko** [comment]
This has been improved in later Craft versions.
