### ISSUE TITLE
Staging environment loads production asset URLs

### ISSUE THREAD

**Issue by mediabeastnz** [craftcms/cms#3017]
### Description
We have noticed on a few sites that have the environment mode as "staging" occasionally try and load images from the production URL instead of the staging.

e.g. we're expecting site.dev/assets/img.jpg but get site.com/assets/img.jpg

We are using a plugin (Imager) to resize these but I'm not 100% sure if it's Craft doing something or Imager is not recognising the environment correctly.

### Steps to reproduce
There seems to be no way to reproduce - it happens randomly :/

### Additional info
- Craft version: 3.0.12
- PHP version: 7.2
- Database driver & version: MySQL
- Plugins & versions: Imager 2.0.1.2

**Comment by aelvan** [comment]
The url is _custom_ in Imager, in the sense that it's based off of whatever you set the `imagerUrl` config setting to. But, the config supports multi-environment in exactly the same way as Craft itself. 

Sure this is not due to some kind of caching? Could it be that this happen when you dump the prod DB down to your local environment? If not, how do you determine which environment you're in, and how's your `imagerUrl` configured?

**Comment by mediabeastnz** [comment]
Hmmm it could be the base URL. In our config we set this for each environment:
e.g. staging = `'siteUrl' => "http://site.craft.preview.com"` and live would be the live URL.

And the volume base URL is always set to this `@web/assets`

Is this not the right approach?

**Comment by brandonkelly** [comment]
`@web/assets` will tell Craft to use whatever the requested host is, which shouldn’t be an issue here.

**Comment by mediabeastnz** [comment]
@aelvan I haven't set a specific imagerUrl - should I?

**Comment by aelvan** [comment]
@mediabeastnz No, it's not necessary, the url by default is relative, `/imager/`, so that shouldn't be the reason then. Could it be template caching that causes this? What do you do to "fix" it?

**Comment by mediabeastnz** [comment]
I clear the cache and it seems to fix its self but that's no really a long term solution. Not sure what's causing the issue in the first place :/

**Comment by brandonkelly** [comment]
@mediabeastnz Do you have both staging and production environments sharing the same database?

**Comment by mediabeastnz** [comment]
@brandonkelly yup - mostly because staging turns into production (via domain alias/dns records).
This is for new sites FYI.

**Comment by brandonkelly** [comment]
@mediabeastnz so that must be the issue; if you have any `{% cache %}` tags, it’s storing template caches into the DB on one environment, and then the other environment loads that as well.
