### ISSUE TITLE
There's no "Delete" button when editing an entry

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#3018]
### Description
In Craft 2, you used to be able to delete an Entry while editing it, using a button on the right. In Craft 3, that button has disappeared and the only way to delete entries is from the listing page on `admin/entries`

### Additional info

- Craft version: 3.0.12
- PHP version: 7.1

**Comment by brandonkelly** [comment]
It’s right here:

<img width="270" alt="screen shot 2018-06-21 at 10 53 22 am" src="https://user-images.githubusercontent.com/47792/41736439-589204de-7541-11e8-9f4c-ed2e98d7cd82.png">
