### ISSUE TITLE
Trailing spaces on entry titles

### ISSUE THREAD

**Issue by circa1977** [craftcms/cms#3020]
### Description

If an entry title includes a trailing space, it's captured and saved that way.

If this entry's title—as a related entry—is pulled in to a title field, it can have unwanted effects, like putting a space before a comma.

Trailing spaces should be trimmed from titles.

### Steps to reproduce

1. Create a new entry with a space at the end of the title.
2. Save it.

### Additional info

- Craft version: Observed in current version of Craft 2; could be a Craft 3 issue, too.
- PHP version: NA
- Database driver & version: NA
- Plugins & versions: NA

**Comment by brandonkelly** [comment]
Fixed for the next release, thanks!
