### ISSUE TITLE
svg() function sometimes produces invalid HTML

### ISSUE THREAD

**Issue by robmcfadden** [craftcms/cms#3025]
### Description

The `svg()` function prepends a string to id attributes that sometimes starts with a number, which doesn't validate.

### Steps to reproduce

The `svg()` function is used in a template and pulling an SVG from an assets field.

### Additional info

- Craft version: 3.0.9
- PHP version: 7.1.16
- Database driver & version: MySQL 5.7.22

**Comment by brandonkelly** [comment]
Fixed for today’s release – thanks!
