### ISSUE TITLE
Assets thumbnail errors when using S3 in load-balanced environment

### ISSUE THREAD

**Issue by mtwalsh** [craftcms/cms#3026]
### Description

We're load balancing Craft 3 (with assets stored at S3) and getting 500 errors frequently when asset thumbnails are requested in the control panel:

* `fopen(.../cpresources/b2004c53/thumb-100x100.jpg): failed to open stream: No such file or directory`
* `The file or directory to be published does not exist`

### Steps to reproduce

Load the assets page in Craft when assets are stored in S3 and the site is running in a load-balanced environment.

### Additional info

- Craft version:  3.0.12
- PHP version: 7.0.30

### Related

- https://github.com/craftcms/cms/issues/2500

**Comment by brandonkelly** [comment]
Check your database’s `resourcepaths` table for a row where `hash = b2004c53` (or any other hash value you get in the invalid file path when this error crops up). Is it there? What is the row’s `path` set to?

**Comment by mtwalsh** [comment]
Thanks for the response Brandon, I've investigated a few of the paths that return a 500 in the `resourcepaths` table and sometimes the folder exists on two instances of the three running but not the file within it. Other times (but less commonly) the folder does not exist at all on one instance but does on the others.  For example `storage/runtime/assets/thumbs/121` exists but not the `thumb-30x30.png` file with it. We're getting the errors from all of the three instances running so it doesn't seem to be an issue isolated to one instance.

**Comment by brandonkelly** [comment]
Ah, ok, so the issue is that the _source_ thumbnails may not have been generated across all web servers yet. So if the resource request goes to a web server that hadn’t had a reason to generate `thumb-30x30.png` yet, it won’t have anything to publish in the `cpresources/` folder.

Just fixed this for today’s release – going forward we’ll just start serving asset thumbnails dynamically rather than trying to publish them into the `cpresources/` folder.

**Comment by mtwalsh** [comment]
Wow! Thanks for the quick response on this, much appreciated. I'll let you know how we get on.

**Comment by mtwalsh** [comment]
Yes, that's sorted the issue, thank again.

**Comment by brandonkelly** [comment]
Thanks for checking!

**Comment by chanwhab** [comment]
amazing, finally got this fixed.
