### ISSUE TITLE
User Photos {username} subfolders removed during Craft 2 to Craft 3 upgrade

### ISSUE THREAD

**Issue by ademers** [craftcms/cms#3027]
### Description

As far as I can tell, Craft 2 stores User Photos in `craft/storage/userphotos/{username}` by default. I would like to keep this structure in my Craft 2 to Craft 3 upgrade. However, after running the DB upgrade, the `{username}` subfolders are gone, and the the Craft 3 User Photo Location field is blank (i.e. doesn't contain `{username}`).

### Steps to reproduce

1. Copy your old user photos from `craft/storage/userphotos/` over to your new project’s `storage/userphotos/` directory as per step 4 in Performing the Upgrade at https://docs.craftcms.com/v3/upgrade.html#performing-the-upgrade
2. Run Craft 2 to Craft 3 database upgrade.
3. Check `storage/userphotos/` in Craft 3 and the `{username}` subfolders are gone. (I think that the user photos are still there, at least for some accounts, but I can't tell for sure because not all users uploaded a user photo).
4. Check the User Settings in CP, and the User Photo Location field is blank (i.e. doesn't contain `{username}`).

### Additional info

- Craft version: Craft Pro 3.0.12
- PHP version: 7.0.29
- Database driver & version: MySQL 5.5.5
- Plugins & versions: None

**Comment by brandonkelly** [comment]
That’s an intentional change, as user photos are assets now in Craft 3 (https://docs.craftcms.com/v3/changes-in-craft-3.html#user-photos). While placing them in a `{username}` folder is still technically possible, it’s not a good idea for sites with hundreds/thousands of users, as the Assets UI doesn’t scale well for that many subfolders.

**Comment by ademers** [comment]
Thanks for the clarification. May I suggest adding a note to the docs explaining that User Photos in Craft 3 are no longer stored in `{username}` subfolders by default? If so, I could give it shot and create a pull request.

**Comment by brandonkelly** [comment]
Just made a note about that in the docs :)

**Comment by brandonkelly** [comment]
Just made a note about it in the docs :) https://github.com/craftcms/docs/commit/75d69bbb6f25cfac1cbe72974f3d79f65d7a6c32
