### ISSUE TITLE
Only one relation value displayed in control panel lists

### ISSUE THREAD

**Issue by ul8** [craftcms/cms#3030]
### Description

When viewing entries or users lists (I assume it applies to categories too, didn't test), columns for relation fields where the entry has multiple values set only displays one value, instead of a list of all values.

I realize this list may become too long and not fit in the table column, but the current behavior is confusing and misleading (it looks like there is only value while there may be many). 

Suggestion: display a reasonable amount of values, then "(x more..)". People can always hide the column if it gets too long.

### Steps to reproduce

1. Set up an entry with a relation field
2. Select multiple values in the relation
3. configure the list view to display that relation field as a column.

### Additional info

- Craft version: 3.0.12
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by Guy-Wilkinson-Plastyk** [comment]
Hi, 

Has there been any movement on this request? This would be perfect for an Intranet project we are working on, where users in a "managers" user group have a number of staff assigned to them – being able to see these at a glance in the users list would be super handy!

Cheers.

**Comment by brandonkelly** [comment]
Just got this in for Craft 3.4!

Relation fields will still only show the first selection initially, butt now with a “+X” button revealing how many additional elements are related, and if you click on it, all of the relations will be shown.

<img width="1032" alt="An element index table with a relation field column, each showing that there are two additional relations beyond what is shown" src="https://user-images.githubusercontent.com/47792/69583105-f2b5e100-0f8e-11ea-93ae-a108a83790b6.png">

<img width="1034" alt="An element index table with a relation field column, with one of the rows showing all three related elements" src="https://user-images.githubusercontent.com/47792/69583142-06614780-0f8f-11ea-96af-4aa5280d927f.png">
