### ISSUE TITLE
'error' should be a reserved field handle

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/cms#3032]
### Description

I can create a field with the handle of `error` without any issues, but when I try to save an entry containing the new `error` field the following error is thrown:

```
ArgumentCountError
Too few arguments to function craft\base\Model::getError(), 0 passed in /Users/lukeyouell/Sites/xxx/vendor/yiisoft/yii2/base/Component.php on line 139 and exactly 1 expected
```

It looks like `error` should be included in the list of reserved field handles.

### Additional info

- Craft version: 3.0.12

**Comment by brandonkelly** [comment]
Sure.

**Comment by riusi88** [comment]
Hey @brandonkelly "errorSummary" might need to be added to the list of reserved field handles as well. I got the same stack trace as @lukeyouell when using it. 

`ArgumentCountError: Too few arguments to function yii\base\Model::getErrorSummary(), 0 passed in /Users/ryaniusi/git/basf_nps/craft3/vendor/yiisoft/yii2/base/Component.php on line 139 and exactly 1 expected in /Users/ryaniusi/git/basf_nps/craft3/vendor/yiisoft/yii2/base/Model.php:637
Stack trace:
#0 /Users/ryaniusi/git/basf_nps/craft3/vendor/yiisoft/yii2/base/Component.php(139): yii\base\Model->getErrorSummary()
#1 /Users/ryaniusi/git/basf_nps/craft3/vendor/craftcms/cms/src/base/Element.php(980): yii\base\Component->__get('errorSummary')
#2 /Users/ryaniusi/git/basf_nps/craft3/vendor/yiisoft/yii2/validators/Validator.php(254): craft\base\Element->__get('errorSummary')
#3 /Users/ryaniusi/git/basf_nps/craft3/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(craft\elements\MatrixBlock), Array)
#4 /Users/ryaniusi/git/basf_nps/craft3/vendor/craftcms/cms/src/fields/Matrix.php(686): yii\base\Model->validate()
#5 /Users/ryaniusi/git/basf_nps/craft3/vendor/craftcms/cms/src/base/Element.php(1255): craft\fields\Matrix->validateBlocks(Object(craft\elements\Entry), NULL)
#6 [internal function]: craft\base\Element->validateCustomFieldAttribute('field:quizBuild...', Array, Object(yii\validators\InlineValidator))
#7 /Users/ryaniusi/git/basf_nps/craft3/vendor/yiisoft/yii2/validators/InlineValidator.php(72): call_user_func(Array, 'field:quizBuild...', Array, Object(yii\validators\InlineValidator))
#8 /Users/ryaniusi/git/basf_nps/craft3/vendor/yiisoft/yii2/validators/Validator.php(257): yii\validators\InlineValidator->validateAttribute(Object(craft\elements\Entry), 'field:quizBuild...')
#9 /Users/ryaniusi/git/basf_nps/craft3/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(craft\elements\Entry), Array)
#10 /Users/ryaniusi/git/basf_nps/craft3/vendor/craftcms/cms/src/services/Elements.php(1914): yii\base\Model->validate()
#11 /Users/ryaniusi/git/basf_nps/craft3/vendor/craftcms/cms/src/services/Elements.php(525): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false)
#12 /Users/ryaniusi/git/basf_nps/craft3/vendor/craftcms/cms/src/controllers/EntriesController.php(378): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#13 [internal function]: craft\controllers\EntriesController->actionSaveEntry(false)
#14 /Users/ryaniusi/git/basf_nps/craft3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /Users/ryaniusi/git/basf_nps/craft3/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#16 /Users/ryaniusi/git/basf_nps/craft3/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('save-entry', Array)
#17 /Users/ryaniusi/git/basf_nps/craft3/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#18 /Users/ryaniusi/git/basf_nps/craft3/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('entries/save-en...', Array)
#19 /Users/ryaniusi/git/basf_nps/craft3/vendor/craftcms/cms/src/web/Application.php(565): craft\web\Application->runAction('entries/save-en...', Array)
#20 /Users/ryaniusi/git/basf_nps/craft3/vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#21 /Users/ryaniusi/git/basf_nps/craft3/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#22 /Users/ryaniusi/git/basf_nps/craft3/web/index.php(42): yii\base\Application->run()
#23 {main}`

**Comment by brandonkelly** [comment]
@riusi88 Added that to the list for the next release.
