### ISSUE TITLE
asset-list not refreshing after image is edited via popup-link

### ISSUE THREAD

**Issue by igorA53** [craftcms/cms#3035]
### Description
Thumbview not updating after a new image is made (with the image editor) if you enter the image-editor via the edit-button in the popup

### Steps to reproduce

1. doubleclick on image to open the popup
2. hover over the image and click "edit"
3. edit the image, fi. crop it
4. save as new image
5. the interface now returns to the popup which gives the impression you should give the new image a new name, but in fact this is still the popup of the old image + after you close the popup, the newly created image isn't shown in the thumb-view.

### Additional info

- Craft version: 3.0.12
- PHP version: 7.0.30
- Database driver & version: MySQL 5.7.22
- Plugins & versions:

**Comment by brandonkelly** [comment]
We refactored how asset thumbnail generation works in v3.0.13. Can you try updating?

**Comment by igorA53** [comment]
the problem remains Brandon.

technically there is no error: the new image is saved + the correct thumb is generated, but you don't see it because the view (list or thumbgrid) isn't refreshed. I'd also close the image-popup if you return from the image editor because it now give the (wrong) impression you are editing the newly created image.

**Comment by igorA53** [comment]
I forgot to mention that the regular way to edit an image by selecting it > and open the editor via the settings-button > "edit the image" works perfectly fine. Then the view-list is updated. There's no refresh if the image editor is opened through the popup > edit-button.
