### ISSUE TITLE
Incorrect IP address detected on nginx reverse proxy (Bluehost VPS hosting)

### ISSUE THREAD

**Issue by rachelrine** [craftcms/cms#3036]
### Description
Found reference to this issue [here](https://wordpress.org/support/topic/plugin-detecting-default-ip-nginx-reverse-proxy-bluehost-vps-hosting/).

### Solution
Was able to fix the issue by manually removing [line 55](https://github.com/craftcms/cms/blob/master/src/web/Request.php#L53-L60).

### Needed
Looking for a way to specify this in the admin, so the manual fix doesn't get overwritten on update.

**Comment by davist11** [comment]
This change now prevents the correct IP from being returned and `127.0.0.1` is returned

**Comment by brandonkelly** [comment]
Yeah looking at the [Wikipedia article](https://en.wikipedia.org/wiki/X-Forwarded-For) for `X-Forwarded-For`, looks like it is in fact meant to represent the client’s IP.

@rachelrine It sounds like your server is the one that is misusing the header. If that’s out of your control, you can configure Craft to ignore it with the [ipHeaders](https://docs.craftcms.com/v3/config/config-settings.html#ipheaders) config setting:

```php
/* config/general.php */

'ipHeaders' => [
    'Client-IP',
    'X-Forwarded',
    'X-Cluster-Client-IP',
    'Forwarded-For',
    'Forwarded',
],
```
