### ISSUE TITLE
Unable to add options to dropdown field

### ISSUE THREAD

**Issue by nihlton** [craftcms/cms#3037]
### Description
when creating the field, I was able to add options.  Now, later, I'd like to add additional options.  the button remains unresponsive.  no JS errors that I can see.  it appears to me that there is no event handler bound in this scenario

there is one JS error on page load which which is not likely related:  
fieldtype-settings.js?v=1530119445:170 Uncaught ReferenceError: g is not defined
    at fieldtype-settings.js?v=1530119445:170

### Steps to reproduce

1. settings > fields > select an existing dropdown field
2. try to add options

### Additional info

- Craft version: Craft Pro 3.0.12
- PHP version:  7.1.18
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Most likely the JS error you’re getting is effecting the page, even if it’s completely unrelated code, thanks to https://github.com/yiisoft/yii2/issues/15651.

Can you send your `composer.lock` and `composer.json` files, and a database dump, over to support@craftcms.com ? We might have better luck reproducing the issue using those.

**Comment by nihlton** [comment]
@brandonkelly 

i set a break point before the error, and set global vars to allow the problem code to continue without errors.   the issue still persisted.
