### ISSUE TITLE
Issue redirecting a specific url with .htaccess

### ISSUE THREAD

**Issue by rachelrine** [craftcms/cms#3040]
### Description

I moved my site from an nginx server to an apache one. I'm using the default `.htaccess` file provided by Craft, and it's working as expected except for urls that use "communities" as the first segment.

http://staging.kingstonhealthcare.com/communities
http://staging.kingstonhealthcare.com/communities/kingston-residence-of-santa-fe

The first link is a page entry whose slug is communities. The second link is an entry in my "Communities" section. If I change that section url to something else, it works as expected, but the page does not. If I change the page slug, it works, but not the section entries.

The "Resources" section follows the same structure (page entry, with a section of resource entries), but works as expected.

Is there something special about the word communities? I've been disabling plugins, deleting routes, and nothing seems to help. Let me know if server/cp creds would be helpful.

### Additional info

- Craft version: Craft Pro 3.0.12
- PHP version: 7.0.30
- Database driver & version: MySQL 5.6.38
- Plugins & versions: 
     - Amazon S3 | 1.0.8
     - Button Box | 2.0.1
     - Control Panel CSS | 2.1.0
     - Element API | 2.5.3
     - Entry Instructions | 1.0.0
     - Feed Me | 3.0.0-beta.15
     - Guest Entries | 2.1.3
     - Imager | v2.0.1.2
     - Neo | dev-dev-3-port
     - Notifications | 1.1.0
     - Preparse Field | 1.0.0
     - Redactor | 2.1.0
     - Redirect plugin for Craft 3 | 1.0.16
     - Smart Map | 3.1.0
     - Store Hours | 2.0.6
     - Super Table | 2.0.7
     - Wordsmith | 3.0.2

**Comment by brandonkelly** [comment]
Craft doesn’t have the word “communities” anywhere in its codebase. Most likely it’s a server config issue.
