### ISSUE TITLE
Strange MatrixBlock Element Query behavior

### ISSUE THREAD

**Issue by acehead** [craftcms/cms#3043]
### Description
After applying element query on matrix fields (similar to this https://craftcms.stackexchange.com/a/914) the result stays the same. 

### Steps to reproduce

1. Create matrix field having different block types, populate it
2. Run following element queries:

```
All blocks: {{entry.articleBody.all | length}} //returns 5
Image blocks: {{entry.articleBody.type('image').all | length }} // returns 2
All blocks: {{entry.articleBody.all | length}} //returns 2
```

### Additional info

- Craft version: Craft Pro 3.0.13.2
- PHP version: 7.2.6
- Database driver & version: Postgres 9.6.3

**Comment by angrybrad** [comment]
You'll need to `clone` that 2nd element query... see here: https://docs.craftcms.com/v3/changes-in-craft-3.html#cloning-element-queries
