### ISSUE TITLE
MatrixBlock 'with' doesn't work

### ISSUE THREAD

**Issue by jeffreyschmitz87** [craftcms/cms#3044]
### Description
I've made a matrix block and have an asset field inside the matrix block.
![screen shot 2018-06-28 at 14 37 12](https://user-images.githubusercontent.com/34717885/42035664-c6f4a7e0-7ae3-11e8-85c3-843508716af8.png)

In Twig I set the matrix block to a variable: `{% set introduction = entry.introduction.with(['introductionImage']).one %}`.

When I use this line of code `{% set imageUrl = introduction.introductionImage.count ? introduction.introductionImage.one.url(thumb) : '' %}` I get the following error message: `Key "count" does not exist as the array is empty.` When I remove the `with` parameter the code works. The above code used to work but since the 3.0.13.1 version update it gives me the error.

### Additional info
- Craft version: 3.0.13.1
- PHP version: 7.1.18
- Database driver & version: MySQL 5.5.56

**Comment by brandonkelly** [comment]
That's expected behavior, and I highly doubt that earlier versions behaved any differently. See https://docs.craftcms.com/v3/eager-loading-elements.html#accessing-eager-loaded-elements .
