### ISSUE TITLE
Plugin actions all errantly require admin

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#3045]
I had a user report an issue that despite being given complete permissions to access a plugin, they were unable to save the plugin settings as a non-Admin user:

https://github.com/nystudio107/craft-seomatic/issues/155

The culprit appears to be in `PluginsController.php`:

```php
    /**
     * @inheritdoc
     */
    public function init()
    {
        // All plugin actions require an admin
        $this->requireAdmin();
    }
```

I'm not sure if this is intentional or not, but I'd think the permissions should be more fine-grained, if they have permission to access the plugin:

https://www.dropbox.com/s/khb7ivoqaank19o/Screenshot%202018-06-28%2008.31.44.png?dl=0

I would think they'd be able to do plugin-related actions (or at least ping the `plugins/save-plugin-settings` controller? Or a separate permission for "Change XXXX plugin settings"?

**Comment by brandonkelly** [comment]
Plugin settings are (by default) all contained within the Settings section, and everything in there requires an admin. If your plugin provides its own settings elsewhere in the CP, you should save the settings with a custom controller rather than PluginsController.
