### ISSUE TITLE
[Feature request] Do not propagate Tags

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#3051]
### Description
Since there is no real Tag manager and since it doesn't make much sense to translate Tags I would suggest to turn of Tag propagation by default or at least provide an option to turn it off. We have a project with ~200 sites and each Tag consumes 199 useless rows in the `content` table that are actually never used since it contains a massive amount of null values + the same title.
We turned it off via service locators (overwriting the `Elements` component) for now and include a `siteId` to the `TagQuery` manually so we don't have all in all ~199000 useless rows.

The CP stores and searches for existing Tags only in the `currentSite` and not in the defined site for the element, so there won't be any difference

**Comment by brandonkelly** [comment]
We can’t just remove that as some people are taking advantage of the feature. So I'm going to close this issue.

When we implement #2856 for entries (option to make titles non-translatable), we will do the same for tags and categories. There will still be "useless" rows, but at least you won't have to worry about keeping the translations up-to-date.
