### ISSUE TITLE
Unable to get the siteUrl from a Console Request

### ISSUE THREAD

**Issue by andrelopez** [craftcms/cms#3055]
### Description

I'm unable to the get the baseSite url within a console request. This stops working in v3.0.13

```
use craft\helpers\UrlHelper;
use Craft;
....
// Returns '/my-url'
$url = UrlHelper::siteUrl('my-url);

// Returns '/'
$baseUrl = Craft::getAlias("@web");

// Returns '/'
$baseUrl = UrlHelper::baseSiteUrl();
```

### Steps to reproduce

1. Call `$baseUrl = UrlHelper::baseSiteUrl();` in a console request

### Additional info

- Craft version: 3.0.13.2
- PHP version: 7.1.7
- Database driver & version: Mysql
- Plugins & versions: -

**Comment by andrelopez** [comment]
Hi @brandonkelly 

I have added this to my init function of the plugin:

```
public function init()
    {
        $url = UrlHelper::siteUrl('my-url');
        Craft::dd($url);
        ....
    }
```

When I go to my dashboard in the browser I got: 
'http://craft3.test/my-url'

The dashboard value is right but when I go to my console and try to run the craft command I got this:
![no-site-url](https://user-images.githubusercontent.com/875476/42223429-b9200068-7ea5-11e8-9ef0-4de9453ea1d2.png)

My primary site has "@web/" in the baseUrl
![sites](https://user-images.githubusercontent.com/875476/42223558-0572c20c-7ea6-11e8-9b96-63c97a4671f9.png)

Best,

**Comment by andrelopez** [comment]
If I set the my baseUrl to http://craft3.test it works.

So the `@web` alias does not work in console commands?

**Comment by brandonkelly** [comment]
Correct, `@web` is just whatever the URL is that was requested by the browser. If  it’s a console request, there is no requested URL.
