### ISSUE TITLE
Number field type, with decimals, fails if string is entered

### ISSUE THREAD

**Issue by nicolasbinet** [craftcms/cms#3059]
### Description

When entering texts in a Number field type with decimals, validation fails, returning  an error 

PHP Warning – yii\base\ErrorException
number_format() expects parameter 1 to be float, string given

Here is a full error log https://gist.github.com/nicolasbinet/bc241f35003cb01335f0a38a2de69946

### Steps to reproduce

1. Create a new Number field
2. Set decimals
3. Add field to Section type
4. Create a new entry
5. Type some random text
6. Validate 

### Additional info

- Craft version: 3.0.13.2
- PHP version: 7.0

**Comment by brandonkelly** [comment]
Fixed just in time for the 3.0.14 release :)

**Comment by nicolasbinet** [comment]
Why it the format Number not enforced trough input[type=text] in the form ?
Not for security reasons, but it would help guiding user through editing.

**Comment by brandonkelly** [comment]
Because `<input type="number">` requires en-US-style number formats (`,` as thousands separator, `.` as decimal), but other locales don’t always use those same characters. E.g. `,` is often used as the decimal character.

**Comment by nicolasbinet** [comment]
@brandonkelly thanks.
