### ISSUE TITLE
Dragging fields to a section's layout designer doesn't work when scrollable

### ISSUE THREAD

**Issue by mdominguez** [craftcms/cms#3066]
### Description

When dragging a field in the layout designer from the bottom of the scrolled page to top, the scrollable block doesn't scroll to the desired tab where I want to place my field.

[View recording](https://cl.ly/shXH)

### Additional info

- Craft version: 3.0.13.2
- Browser version: latest Chrome 67.0.3396.99

**Comment by brandonkelly** [comment]
That was fixed in 3.0.14, released yesterday.
