### ISSUE TITLE
ElementTables loading all elements in a loop till the end is reached

### ISSUE THREAD

**Issue by Naffto** [craftcms/cms#3068]
### Description
View any ElementIndexTable with more than 50 elements. As soon as the 'get-elements' call is complete, an additional 'get-more-elements' call will be fired. As soon as this call is complete, the next 'get-more-elements' call will be fired.
This stops when all elements are displayed.

Normal behavior is to load more elements while scrolling down.

### Steps to reproduce

1. Add more than 50 elements to any Section/Structure/Category
2. View the list

### Origin of the error

In this [commit](https://github.com/craftcms/cms/commit/d3cbc38df578112e26b2169800134350134a617a#diff-95a1902fb868380acb3302dd19c95045L615) you changed the scroll container from `#content-container` to `#container`.

Now in the [BaseElementIndexView.js](https://github.com/craftcms/cms/blob/develop/src/web/assets/cp/src/js/BaseElementIndexView.js#L114) you are using `Craft.cp.$contentContainer` for the scroll-container. And this value is always `$('#content-container')`

### Additional info

- Craft version: 3.0.14 Pro
- PHP version: 7.0.28
- Database driver & version: MySQL 5.7.14
- Plugins & versions: none

**Comment by brandonkelly** [comment]
Thanks for reporting!
