### ISSUE TITLE
[BUG] #content-container width not properly restricted in Firefox

### ISSUE THREAD

**Issue by mgrandl** [craftcms/cms#3071]
I have some matrix blocks with a lot of content. When collapsing them the collapsed block runs way too long so it hides it's context menu beyond the viewport in Firefox.

I fixed this locally by adding overflow: hidden to #content-container but I did not properly test this. I hope this helps.

**Comment by brandonkelly** [comment]
What version of Craft are you running?

**Comment by mgrandl** [comment]
Craft 3 latest.

**Comment by mgrandl** [comment]
![image](https://user-images.githubusercontent.com/10323670/42335364-6a0e6bc2-8080-11e8-8a51-3e33490adcbf.png)

![image](https://user-images.githubusercontent.com/10323670/42335389-7a0ae320-8080-11e8-81dc-959955a4c99b.png)

In the second image I added the `overflow: hidden` and now it displays fine.

**Comment by tpmatthes** [comment]
This also happens, if you have a lot of tabs:

![firefox hidden sidebar](https://user-images.githubusercontent.com/30212990/42369830-63419126-810b-11e8-8c42-f7043249395a.png)

The mobile view (< 1000 px) works just fine.

Firefox 61.0.1 and Craft Pro 3.0.14

**Comment by johnwbaxter** [comment]
I have the same issue, but only 2 tabs and only 4 matrix blocks so not sure it's the quantity of these at fault!

However, i do have a fair few matrix types and when this issue happens, they haven't been condensed into a single dropdown, so, i'd guess a JS issue here.

See attached for console output.
<img width="1916" alt="screen shot 2018-07-07 at 13 01 33" src="https://user-images.githubusercontent.com/338729/42410696-eedda938-81e5-11e8-9000-67115f2af42f.png">

**Comment by brandonkelly** [comment]
This should be fixed now for the next release. I wasn’t able to reproduce the tab issue, but suspect it’s related. If you have a chance, you can test by opening `composer.json` and changing the `craftcms/cms` constraint to `"dev-develop as 3.0.14"`, and then run `composer update`.

**Comment by tpmatthes** [comment]
Regarding the tab issue: I’ve just tested it with `dev-develop` and everything works fine again. Thanks for your help! 👍

**Comment by mgrandl** [comment]
`dev-develop` works for me as well. Thanks for your work!
