### ISSUE TITLE
Extra white space rendered when selected dropdown label is blank

### ISSUE THREAD

**Issue by rynpsc** [craftcms/cms#3075]
### Description

When you have a Dropdown / Select field where one of the options has a blank label, selecting the blank option results in extra whitespace being rendered below it causing all content below to jump.

Looks to be caused by the [`white-space` property](https://github.com/craftcms/sass/blob/master/src/_mixins.scss#L362-L366). Removing it fixes it, with no obvious side effects.

Reproducible in Chrome 67 and Safari.

### Steps to reproduce

1. Create a new dropdown field where at least on option has a blank label and at least one that has a non blank label
2. Create any other field
3. Add both fields to a section with the dropdown positioned before the second field
4. Go to the entry edit page and select the non blank and blank option in turn.

### Additional info

- Craft version: Craft Solo 3.0.14
- PHP version: 7.2.4 
- Database driver & version: MySQL 5.7.21

**Comment by brandonkelly** [comment]
Well that’s a weird one! Thanks for reporting and looking into it. Fixed for the next release.
