### ISSUE TITLE
Searching difficulties with hyphens (-) and periods (.) in assets

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#3080]
![screen shot 2018-07-09 at 12 49 27 pm](https://user-images.githubusercontent.com/18329/42464690-d80791a4-8377-11e8-8365-8d3f511cecf4.png)

I've had clients have difficulties finding assets like the one shown above.

The following yield no results, which seems a bit broken: `138-501`, `"138-501"`, `138-501.jpg`, `"138-501.jpg"`.
…and I certainly can't ask them to search for `*138*501*jpg` :)

I noticed that _entries_ with hyphens still seem to be searchable (e.g. I can search for `e-mail` and get a result for an entry with `e-mail` in the title), but the behavior is different with assets.

**Comment by angrybrad** [comment]
Currently _all_ search keywords that get inserted into the `searchindex` table in the database go through a [normalization](https://github.com/craftcms/cms/blob/develop/src/helpers/Search.php#L41-L81) process, which includes things like removing punctuation from a given string because those are typically considered noise in a search.

So "138-801.jpg" will end being saved as " 138 501 jpg " in the database, which is why your first four examples won't match.

I think ultimately this will be solved in the Control Panel by https://github.com/craftcms/cms/issues/833 and/or https://github.com/craftcms/cms/issues/2060

**Comment by timkelty** [comment]
Thanks @angrybrad, sounds good.

Any idea why I'm seeing a different behavior for Entries (seem to be able to search for entries with hyphenated titles)?

**Comment by narration-sd** [comment]
Interessant.

 I was about to ask if such terms should be entered without the hyphens, etc., like certain maddening telephone etc. number forms. Glad to see your intent is rather 'the Craft Way' ;)

Does at first seem subLeft ought to be default true, as subRight is, though. Something important I'm missing? (no doubt...)

**Comment by timkelty** [comment]
@angrybrad indeed, I changed `defaultSearchTermOptions` and I now get results:

```
        'defaultSearchTermOptions' => [
            'subLeft' => true,
            'subRight' => true,
        ],
```

However, I'm not sure I understand why…(why would `subLeft: true` affect it when I'm searching from the beginning of a string)?

E.g. I can now search for `138-801.jpg ` and get an exact result, which is good. But I can also search for 38-801.jpg and still get the same result, which is certainly better than nothing, but not really what I'd want ideally.

**Comment by angrybrad** [comment]
@timkelty because all of the keywords in the `searchindex` table in the database are padded on both sides with whitespace.  i.e. ` 138 501 jpg `

Since 138 is the beginning of the string, you'd need the subleft to include the initial space.

**Comment by timkelty** [comment]
I see…a bit weird, but good enough until hopefully #833 and/or #2060 happens.

Thanks, @angrybrad!

**Comment by angrybrad** [comment]
I agree it's a bit awkward.  Turns out search is pretty difficult.

**Comment by narration-sd** [comment]
@angrybrad  again, is there a reason not to default subLeft?

Much agreed, search itself is ever a potential bandit -- this just seams it would ease a bit for use?

**Comment by yellowstar0826** [comment]
I have some prolbesm with my code.

**Comment by yellowstar0826** [comment]
Hey, I deal with it.
