### ISSUE TITLE
Cannot set Category Field on random entries

### ISSUE THREAD

**Issue by nmann4789** [craftcms/cms#3086]
### Description

We have a content channel in our database called Resources, which has a Category field, and on random entries we are not able to select a category on the field and save the entry.

I can provide the db we use upon request.

### Steps to reproduce

1. Go to Resources Section
2. Open ​"Backup vs Business Continuity"
3. Attempt to set category "Ransomware Page" on "Show in Field"
4. Save Entry.

### Additional info

- Craft version: Craft Pro 3.0.15
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Plugins & versions:

**Comment by nmann4789** [comment]
This was actually a result of another required field not being set properly in a different tab within the entry.

Can we add some better descriptions in the errors we receive when an entry has missing required fields?

**Comment by brandonkelly** [comment]
Glad you got it sorted! 

> Can we add some better descriptions in the errors we receive when an entry has missing required fields?

Sounds like  #1379 - feel free to add a 👍 to that!
