### ISSUE TITLE
Multi-site getCpEditUrl not scoping for site

### ISSUE THREAD

**Issue by davist11** [craftcms/cms#3089]
### Description
On a multi-site install, if you are using `getCpEditUrl` on the front-end to link to the edit entry screen, the site handle is not added to the url. Presumably, it's because of this line

`$this->siteId != Craft::$app->getSites()->getCurrentSite()->id`

### Steps to reproduce

1. Create multiple sites
2. Create a single and enable it for multiple sites
3. Output `getCpEditUrl` on the front-end for that entry template

### Additional info

- Craft version: Craft Pro 3.0.13.1
- PHP version: 7.0.30
- Database driver & version: MySQL 5.7.22
- Plugins & versions:

<table class="data fullwidth fixed-layout">
        <tbody>
                            <tr>
                    <th class="light">Algolia</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Amazon S3</th>
                    <td>1.0.8</td>
                </tr>
                            <tr>
                    <th class="light">Asset Rev</th>
                    <td>6.0.0</td>
                </tr>
                            <tr>
                    <th class="light">AsyncQueue</th>
                    <td>1.3.3</td>
                </tr>
                            <tr>
                    <th class="light">Audit</th>
                    <td>2.0.1</td>
                </tr>
                            <tr>
                    <th class="light">Automatic Site Switch</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Calendar</th>
                    <td>2.0.3</td>
                </tr>
                            <tr>
                    <th class="light">Category Utilities</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Certificates</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Converge</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Craft Commerce</th>
                    <td>dev-develop</td>
                </tr>
                            <tr>
                    <th class="light">Enupal Snapshot</th>
                    <td>1.0.4</td>
                </tr>
                            <tr>
                    <th class="light">Environment Label</th>
                    <td>3.1.4</td>
                </tr>
                            <tr>
                    <th class="light">Feed Me</th>
                    <td>3.0.0-beta.15</td>
                </tr>
                            <tr>
                    <th class="light">Field Manager</th>
                    <td>2.0.2</td>
                </tr>
                            <tr>
                    <th class="light">Flat Categories</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Forms</th>
                    <td>2.1.1</td>
                </tr>
                            <tr>
                    <th class="light">Freeform Pro</th>
                    <td>2.1.1</td>
                </tr>
                            <tr>
                    <th class="light">Geo Cookie</th>
                    <td>1.2.1</td>
                </tr>
                            <tr>
                    <th class="light">Hamilton Utility</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Importer</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Inlin</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Inventory</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">OrderExporter</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Redactor</th>
                    <td>2.1.0</td>
                </tr>
                            <tr>
                    <th class="light">Sidebar Toggle</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th class="light">SimpleSentry</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Super Table</th>
                    <td>2.0.7</td>
                </tr>
                            <tr>
                    <th class="light">Taxes</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Twig Perversion</th>
                    <td>2.0.3</td>
                </tr>
                    </tbody>
    </table>

**Comment by brandonkelly** [comment]
What do you mean by “site handle” ? Can  you post the URL you’re getting and the URL you expected to get?

**Comment by davist11** [comment]
Ah sure, an actual URL example would have been helpful, sorry about that...

We have an Applications Index single that is available across multiple sites. If I visit that entry on the front-end of two different sites:

```
/laboratory-products/applications
/process-analytics/applications
```

the `getCpEditUrl` is the same for both:

```
/admin/entries/applicationsIndex/56677-applications-index
```

Where I would expect them to be:

```
/admin/entries/applicationsIndex/56677-applications-index/laboratory
/admin/entries/applicationsIndex/56677-applications-index/processAnalytics
```

**Comment by brandonkelly** [comment]
There was some logic to omit the site handle when creating the entry edit URL, if the entry’s site was the same as the current site, which is fine in the CP, but didn’t take into account that it might be a front-end request, where the entry will almost always be queried for the current site, which may not be the same site that the CP gets.

Fixed for the next release.
