### ISSUE TITLE
camelCaseStrings to kebab-case-strings

### ISSUE THREAD

**Issue by mdominguez** [craftcms/cms#3090]
Hi there,

Is there a way to convert camelCasedStrings to kebab-cased-strings (hyphenate them)? If not, is that something you'd provide in the near future?

Currently the |kebab filter converts "camelCasedStrings" to "camelcasedstrings" instead of putting hyphens between the words, which is non-desirable in any case I can think of right now :)

Many thanks!

**Comment by brandonkelly** [comment]
Just changed that for the next release :)

**Comment by mdominguez** [comment]
Awesome, on what frequence do releases mostly come out?

**Comment by angrybrad** [comment]
Roughly once a week: https://github.com/craftcms/cms/blob/develop/CHANGELOG-v3.md
