### ISSUE TITLE
Licence for charity org

### ISSUE THREAD

**Issue by ArnyS** [craftcms/cms#3095]
I've developed a website for a charitable foundation that helps children for free.
Can it use a free license or do the foundation need to purchase a commercial version?

Thx

**Comment by brandonkelly** [comment]
Hi Arny,

If the Solo edition works for you, then feel free to use it. If you do have a need for the Pro edition features, please email support@craftcms.com as we may be able to offer you a discount. We generally match whatever discount you are offering for your services.
