### ISSUE TITLE
Live Preview on latest Firefox is semi-borked.

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#3098]
### Steps to reproduce

1. Use latest Firefox (61.0.1) on Windows or Mac.
2. Create a new section and point it to a template (no custom fields necessary).
3. Create a new entry in that section.
4. Click "Live Preview" - notice the templates loads.
5. Click "Close Live Preview" - Live Preview closes,  but there is an error in the console.

![capture](https://user-images.githubusercontent.com/61869/42728866-62b1ce5e-877a-11e8-8cf3-a2b36e7b29d7.PNG)

6. The entry content area is now blank and you can't click "Live Preview" again.

### Additional info

- Craft version: 3.0.15
- PHP version: 7.1
- Database driver & version: n/a
- Plugins & versions: n/a

**Comment by narration-sd** [comment]
had to have a look; you'll understand why, and just would like to confirm, all you say. Plus the extra effect just noted making the list below.

For me, the following items suggest work-arounds to need, until you guys can run this down:

- a refresh when on the blank editing page will recover, bringing back normal display, and allowing another single Live Preview session via its button. 
- Saving by Save button while in a Live Preview looks to continue with normal operation, likely by provoking a similar normal refresh.
- Doing a Save while still in Live Preview is also essential so as not to lose your edits, as simply closing it by the Close Live Preview button also loses your  edit data.

Cheers, Clive

**Comment by narration-sd** [comment]
...added an extra tip to the list
