### ISSUE TITLE
No margin between widgets which are 3-columns wide.

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#3100]
### Steps to reproduce

1. Add the following widgets to your dashboard.
     - Craft Support
     - Updates
     - New Users
2. Make them all three-columns wide.
3. Refresh your browser.
4. Notice that there is no margin between the widgets.

<img width="1216" alt="3-column widgets" src="https://user-images.githubusercontent.com/5309692/42739616-15742ecc-884f-11e8-882a-4ad3ada7e490.png">

### Additional info

- Craft version: 3.0.15

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release.
