### ISSUE TITLE
[FR] Site group-based templates

### ISSUE THREAD

**Issue by chanwhab** [craftcms/cms#3101]
### Description

If there is only translation between localized site, we probably dont need to add new templates
````
templates/
├── account.twig      --> default site A account template, and works for both EN, DE, FR localization
````
But with multiple sites + localization, 
Site A, Site B, Site C can have a large difference in page layout.
it becomes:

````
templates/
├── account.twig      --> default site A account template,  works for all EN, DE, FR localization
└── siteBen /
    └── account.twig  --> siteB EN account template
└── siteBde /
    └── account.twig  --> siteB DE account template
└── siteBfr /
    └── account.twig  --> siteB FR account template
└── siteCen /
    └── account.twig  --> siteC EN account template
└── siteCde /
    └── account.twig  --> siteC DE account template
└── siteCfr /
    └── account.twig  --> siteC FR account template
````

Can we make use of siteGroup concept, and workout something like this:
````
templates/
├── account.twig      --> all sites default account template,  works for all EN, DE, FR localization
└── siteGroupB /
    └── account.twig  --> siteGroupB account default template,  works for all EN, DE, FR localization
└── siteGroupC /
    └── account.twig  --> siteGroupC account default template,  works for all EN, DE, FR localization
````

**Comment by BenParizek** [comment]
Just to note it here. This sounds similar to the need we had for Site Groups with a plugin supporting multi-lingual sitemaps. Nice to see another use case appear for those Site Groups.

**Comment by el-schneider** [comment]
+1 

I would love to see this functionality implemented.

**Comment by WHITE-developer** [comment]
+1 
Exactly in that situation right now, multiple sites with multiple languages which need slightly changes across the sites aka site groups.

**Comment by jan-dh** [comment]
Looking forward to this, wondering if there's a clean work-around in the current setup.

**Comment by jan-dh** [comment]
There's a [PR](https://github.com/ThomasDeMarez/cms/commit/aa5cee4a386576d4b8a1d0b82a327040bca17481) for this
