### ISSUE TITLE
CraftCMS 3 - Update \craft\services\Fields::$_fetchedAllGroups when a new group is created

### ISSUE THREAD

**Issue by joruro** [craftcms/cms#3102]
Please, update the `\craft\services\Fields::$_fetchedAllGroups` to false when a new group is created. Or add a method to reset it. Otherwise, when I try to get all the groups, I just that the groups that were fetched before creating the new one

**Comment by brandonkelly** [comment]
Thanks for pointing that out - fixed for the next release.

Instead of setting `$_fetchedAllGroups` to `false`, `saveGroup()` now adds/updates the group's record in `$_groupsById`.

**Comment by joruro** [comment]
Thanks. Note that I see this logic repeated on other services. For instance `\craft\services\Volumes` or `\craft\services\Sections`
