### ISSUE TITLE
Bug: event Plugins::EVENT_BEFORE_SAVE_PLUGIN_SETTINGS is mixed up and not per plugin

### ISSUE THREAD

**Issue by bertoost** [craftcms/cms#3105]
### Description

For example, I have installed 2 plugins. One is heavely in development and I registered a listener on `Plugins::EVENT_BEFORE_SAVE_PLUGIN_SETTINGS`. That plugin should do something when a certain setting is enabled.

Now saving settings from the second plugin and I did get an error like this;

```
Unknown Property – yii\base\UnknownPropertyException
Getting unknown property: first\plugin\models\Settings::enabledSetting
```

This setting belongs to the second plugin and it tries to resolve it on the first plugin.

### Steps to reproduce

1. Create a second plugin (fake one) and define a setting which does not exists in an other plugin.
2. Also create a listener on the event (named before), checking that setting.
2. Then edit settings from the first plugin and save them. Then I get above error

### Additional info

- Craft version: 3.0.15
- PHP version: 7.1.18
- Database driver & version: MySQL 5.7.17

**Comment by brandonkelly** [comment]
Can you post your full event handler code?

**Comment by bertoost** [comment]
This is what I do in the plugin, which is listening to plugin event

```php
use craft\services\Plugins;
//...
Event::on(
    Plugins::class,
    Plugins::EVENT_BEFORE_SAVE_PLUGIN_SETTINGS,
    [SettingsService::class, 'onSaveSettingsListener']
);
```

```php
// settings service class
public function onSaveSettingsListener()
{
    $settings = $event->plugin->getSettings();
    if ($settings->enabledOption) {

        // actual code here, just writes files based on the settings
    }
}
```

So when save-settings from another plugin is saved, it is triggering this code, which only should happen when this plugin settings are saved.

**Comment by brandonkelly** [comment]
That event is supposed to fire regardless of which plugin is getting saved. So your event handler is responsible for checking if it was _your_ plugin that was saved.

```php
public function onSaveSettingsListener()
{
    if ($event->plugin !== MyPlugin::getInstance()) {
        return;
    }

    // ...
}
```

**Comment by brandonkelly** [comment]
I just added a couple new events that get fired directly from `craft\base\Plugin` – `EVENT_BEFORE_SAVE_SETTINGS` and `EVENT_AFTER_SAVE_SETTINGS`.

So as of the next release, you will be able to register a class-level event listener for the specific plugin class you care about.

```php
use craft\base\Plugin;
use yii\base\Event;

Event::on(
    MyPlugin::class,
    MyPlugin::EVENT_BEFORE_SAVE_SETTINGS,
    [SettingsService::class, 'onSaveSettingsListener']
);
```

Note that the actual event class will be a [craft\events\ModelEvent](https://docs.craftcms.com/api/v3/craft-events-modelevent.html) object, so you will need to access the plugin instance from `$event->sender` rather than `$event->plugin`.

```php
use craft\events\ModelEvent;

public function onSaveSettingsListener(ModelEvent $event)
{
    /** @var MyPlugin $plugin */
    $plugin = $event->sender;

    $settigs = $plugin->getSettings();
    // ...
}
```

**Comment by bertoost** [comment]
Wauw! That is awesome.
Btw. as far my English goes, the docs are saying that this event is used for saving a plugin’s settings. That assumes it already is what you’ve recently added. Maybe have to put a note on that part of the docs?

**Comment by brandonkelly** [comment]
Which docs are you referring to?
