### ISSUE TITLE
svg() has no output

### ISSUE THREAD

**Issue by jhealey5** [craftcms/cms#3106]
### Description
From the docs (https://docs.craftcms.com/v3/dev/functions.html#svg-svg-sanitize) it sounds like `svg()` is supposed to output an svg inline from a path. When I use it though it does nothing.

Seeing as there's no other issues regarding this, is there anything that could prevent it from working and/or am I not understanding the docs?

### Steps to reproduce

`<img src="/assets/images/icon--search.svg" alt="">` works
`{{ svg('/assets/images/icon--search.svg') }}` doesn’t

### Additional info

- Craft version: 3
- PHP version: 7.2.1

**Comment by brandonkelly** [comment]
The path must be a _file system path_, not a URL.

Assuming your  `assets/` folder lives alongside your `index.php` file, you can do this:

```twig
{{ svg('@web/assets/images/icon--search.svg') }}
```

(`@web`  is an [alias](https://docs.craftcms.com/v3/config/#aliases) to the directory that contains your  `index.php` file.)

**Comment by jhealey5** [comment]
@brandonkelly using 
`{{ svg('@web/assets/images/icon--search.svg') }}` 
gives me a URL ( `//localhost:3000/assets/images/icon--search.svg`)

Based on that though, trying 
`{{ svg('@webroot/assets/images/icon--search.svg') }}` 
does give me a filepath (`/Users/john/Sites/client/web/assets/images/icon--search.svg`).

Though, sorting that lead me to another problem - Craft throws an exception when it encounters a forward slash in an SVG element id. e.g; `<g id="Elements/Logo">`.

Easily fixed but thought you might want to know.

Cheers!

**Comment by brandonkelly** [comment]
Sorry, yeah meant `@webroot`.

Can you post the error you’re getting, along with the full contents of the SVG image, in a new issue please?
