### ISSUE TITLE
Warn against conflicting module names (e.g. app)

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#3107]
I was registering my "app-specific module" as `app`:

```
    'modules'   => [
        'app' => [
            'class' => \modules\app\Module::class,
        ],
    ],
    'bootstrap' => ['app'],
```

I thought everything was fine, but then noticed a bunch of 404s in my CP, e.g. to `/index.php?p=cp/actions/app/check-for-updates`.

Naming my module to something else mitigated the issue. I'm not sure if the `craftcms/cms/src/controllers/AppController.php` is the only thing that would be affected by this, but it would be nice to document if there are module names that are reserved.

**Comment by brandonkelly** [comment]
Modules are implemented by Yii so not something we can do much about, but I just added a warning about this to the [How to Build a Module](https://docs.craftcms.com/v3/extend/module-guide.html) page in the docs.

**Comment by timkelty** [comment]
Thanks!
