### ISSUE TITLE
Sorting eager loaded elements only works with "order" not "orderBy"

### ISSUE THREAD

**Issue by kristiansp** [craftcms/cms#3109]
### Description
It seems that ordering eager loaded elements only works with the deprecated `order`, not the new `orderBy`. Thus the following code returns the wanted result, sorting the `shows` in ascending order by `showTime`:

```
{% set currentMovies = craft.entries({
                         section: 'movies',
                         type:    'movie',
                         orderBy:   'startingDate asc',
                         limit:   null,
                         with: [
                           ['shows', { order: 'showTime asc' }],
                           'poster',
                           'stills'
                         ]
                       }).all()
%}
```
It will then throw a deprecation warning with the following origin:
`/Applications/MAMP/htdocs/craft3/vendor/craftcms/cms/src/elements/db/EntryQuery.php:216`

Whereas the following code does not sort the shows:

```
{% set currentMovies = craft.entries({
                         section: 'movies',
                         type:    'movie',
                         orderBy:   'startingDate asc',
                         limit:   null,
                         with: [
                           ['shows', { orderBy: 'showTime asc' }],
                           'poster',
                           'stills'
                         ]
                       }).all()
%}
```

### Steps to reproduce

1. Make element query with eager loaded elements
2. Sort the eager loaded elements by a custom field

### Additional info

- Craft version: Craft Pro 3.0.15
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
Thanks! Fixed that for the next release.
