### ISSUE TITLE
Saving a new entry with an accented character in the title causes a PHP error

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#3113]
### Description

Appears to be a regression from this commit: https://github.com/craftcms/cms/commit/360843c7413e726ba66347df3c257e7a36ff3f45

Error message: 
> Argument 1 passed to craft\helpers\StringHelper::splitOnWords() must be of the type string, null given, called in /app/vendor/craftcms/cms/src/helpers/StringHelper.php on line 1055

### Steps to reproduce

1. Save a new entry with `ä` in the title.
2. Get the error.

### Additional info

- Craft version: 3.0.16
- PHP version: 7.x
- Database driver & version: n/a
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Fixed via 9190983d
