### ISSUE TITLE
Allow element types to set additional query params used in getElementById()

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#3117]
In my element type I have a query parameter which conceptually works very similar to `status`, where if it isn’t explicitly set it defaults to a specific value.

I’m now running into issues with the `Elements::getElementById()` function, which doesn’t always return my elements because I’d need to set/override my param to `null` for it to work. I am not calling `getElementById()` myself, it’s called by `Elements::propagateElement()` when I save my element.

It would be nice if it was possible to set additional query params used in `getElementById()`, maybe via a static function that I could add to my element class or via an event listener.

This is the code I have in the constructor of my `ElementQuery`:
```php
// Default status
if (!isset($config['status'])) {
    $config['status'] = [Task::STATUS_INPROGRESS];
}

// Default environment
if (!isset($config['environment'])) {
    $config['environment'] = Plugin::getInstance()->getEnvironments()->getCurrentEnvironment();
}
```

**Comment by carlcs** [comment]
I don’t need to override that code that calls it. What I want to do is to override the default `environment` param in `getElementById()`. Similar to what you do with `status`, you set a default in `ElementQuery` and overrride it in `getElementById()`.

**Comment by carlcs** [comment]
A default `status` of “live” makes sense for entry queries, but you can’t have that set for `getElementById()`.

In my use case a default `environment` of the current environment ID makes sense, but this causes issues with `getElementById()`.

**Comment by brandonkelly** [comment]
OK, just so I’m clear, you are asking for a way to register custom query params that are only applied when `getElementById()` is called?

What if instead you just don’t set the `environment` param at all from your constructor, and determine the default value for it from your `beforePrepare()` method instead?

```php
protected function beforePrepare(): bool
{
    // ...

    // Determine the environment
    $env = $this->environment ?? (empty($this->id)
        ? Plugin::getInstance()->getEnvironments()->getCurrentEnvironment()
        : null;

    // Now use $env instead of $this->environment ...
}
```

**Comment by carlcs** [comment]
> OK, just so I’m clear, you are asking for a way to register custom query params that are only applied when getElementById() is called?

Yes, exactly.

> What if instead you just don’t set the environment param at all from your constructor, and determine the default value for it from your beforePrepare() method instead?

Well, it still must be possible to set the param to `null` for the places where I have to query for all elements. I could use `false` as a value for this, and I actually had that as a workaround, but I actually would prefer to be consistant with the status parameter values.

This is what I currently do to work around errors being thrown by `Elements::propagateElement()`.  In `beforePrepare()`:
```php
if (
    !Craft::$app->getRequest()->getIsConsoleRequest() &&
    Craft::$app->getRequest()->getActionSegments() === ['maintenance', 'tasks', 'save-task']
) {
    $this->environmentId = null;
}
```

**Comment by brandonkelly** [comment]
Maybe a better option would be for us to add a new method to ElementQuery, perhaps called `nofilter()`, which sets `$this->status = null` and `$this->enabledForSite = false` internally, and start calling that everywhere that we’re currently manually setting both of those params (such as `getElementById()`) instead.

Then you could just override that method, and null out your `environment` param.

```php
public function nofilter()
{
    $this->environment = null;
    return parent::nofilter();
}
```

**Comment by carlcs** [comment]
This would be perfect.

**Comment by carlcs** [comment]
Or a 3rd argument for the constructor?

```php
public function __construct($elementType, array $config = [], bool $nofilter = false);
```

**Comment by brandonkelly** [comment]
Thought about that, but a lot of the places we currently null-out the `status` and `enabledForSite` params are places where that code wasn’t where the query got created in the first place.

**Comment by brandonkelly** [comment]
All set now. We decided to call it `anyStatus()`, since that’s closer to what the method does in the base class, and `nofilter` would imply that other things like `id`, `section`, etc., should also be nulled out.

**Comment by carlcs** [comment]
Thank you Brandon! When I said perfect I lied a little bit, I didn't like the name. With naming it `anystatus` it's perfect for real.

**Comment by brandonkelly** [comment]
Hah, good to head! We had to debate it for a bit; the only issue we had with `anyStatus` is it didn’t seem like it was a good fit for your `environment` use case :)

**Comment by carlcs** [comment]
Well I consider it a status-like property of my element. It is just another way to disable it under certain conditions, I think you can say it is defining its status.
