### ISSUE TITLE
Field Type Categories: Autodetect "Relate categories from a specific site?"

### ISSUE THREAD

**Issue by kdouglass** [craftcms/cms#3118]
Instead of selecting a site under "Which site should categories be related from?", it would be nice to have a feature where it autodetected the active site in the sites menu. This way you can create one reusable field and have the options related to the active site.

**Comment by brandonkelly** [comment]
If you leave the “Relate categories from a specific site?” checkbox unticked, then you will be able to create relations using whatever the currently selected site is, which sounds like what you’re describing.
