### ISSUE TITLE
Asset field restricted upload location does not respect variable filter

### ISSUE THREAD

**Issue by admench** [craftcms/cms#3119]
### Description

An asset field has a 'restrict upload location' setting `{username|hash}`.

However, when adding an asset to this field, a directory is created with the pattern `4a614de4d2187a0647baae29997ecc3a6658704ded6ed5c6d8a8431b530e246aemail@email.com`

As you can see it has appended the username value to the end of the hashed value

### Steps to reproduce

1. Create new asset field and set upload location to as above
2. Upload file to this asset field.
3. Check volume subdirectory name

### Additional info

- Craft version: 3.0.14
- PHP version: 7.2.5
- Database driver & version: MySql 5.7.22-0ubuntu18.04.1
- Plugins & versions: no plugins used in this issue

**Comment by carlcs** [comment]
This is how the `hash` filter is meant to work.

> Prefixes the given string with a keyed-hash message authentication code (HMAC), for securely passing data in forms that should not be tampered with.
https://docs.craftcms.com/v3/dev/filters.html#hash

You could consider registering a Twig extension that adds a filter for [calculating MD5-hashes](http://php.net/manual/de/function.md5.php) (you can use the example module that comes with the default Craft install).

**Comment by admench** [comment]
For anyone finding this issue, I used the `{uid}` variable for the dynamic subfolder path on my asset field associated with the User.

**Comment by admench** [comment]
...this gave me enough security to separate user uploads to public paths anonymously.
