### ISSUE TITLE
Trailing slash in files with `addTrailingSlashesToUrls`

### ISSUE THREAD

**Issue by XhmikosR** [craftcms/cms#3123]
### Description

I originally reported this on https://github.com/nystudio107/craft-seomatic/issues/173 because that's where I noticed it. But judging from @khalwat's comment there, it seems this is done in core.

### Steps to reproduce

1. Set `addTrailingSlashesToUrls` to `true`
2. Install craft-seomatic plugin
3. Visit `domain.tld/sitemap.xml` and see that the internal link to the sub-sitemap includes a trailing slash like: `https://foo.bar/sitemaps/1/section/pages/1/sitemap.xml/`

### Additional info

- Craft version: 3.0.16.1
- PHP version: 7.2
- Database driver & version: N/A
- Plugins & versions: SEOmatic 3.1.2

**Comment by khalwat** [comment]
It's done in core, I'm just not sure if its intended behavior or not.

I’d think it would not add the trailing slash if the URL ends in a file extension?

**Comment by brandonkelly** [comment]
> I’d think it would not add the trailing slash if the URL ends in a file extension?

I suppose we could make that happen.

**Comment by khalwat** [comment]
@brandonkelly I can just trim it myself too; I guess I'm just confused about what the expected behavior would be here?

**Comment by brandonkelly** [comment]
As of the next release the expected behavior is to not add a slash for `sitemap.xml` URLs :)

**Comment by XhmikosR** [comment]
@brandonkelly: no pressure, just wondering if there's an ETA for this? It's hurting SEO because the image URLs also have the trailing slash resulting in a 404.

**Comment by khalwat** [comment]
@XhmikosR I can make a fix for you that will take care of this in the interim if needs be.

**Comment by XhmikosR** [comment]
@khalwat: if it's going to take a long time, we could use a workaround for sure. If it's going to take like a couple of days, not worth going through the trouble of releasing a new version and stuff :)

Thanks!

**Comment by brandonkelly** [comment]
We usually cut releases on Tuesdays, and today is Tuesday.

**Comment by XhmikosR** [comment]
Thanks, guys, all good now!
