### ISSUE TITLE
Unable to see children of disabled item in structure view

### ISSUE THREAD

**Issue by mattcdavis1** [craftcms/cms#3126]
### Description
Unable to see children of disabled item in structure view

### Steps to reproduce

1. Create a structure with 1 parent and 2 children
2. Disable Parent
3. Try to view children in structure view

### Additional info

- Craft version: Craft Pro 3.0.16.1
- PHP version: 7.2.7
- Database driver & version: MySQL 5.7.22

Screenshot: https://goo.gl/86EWgF

**Comment by brandonkelly** [comment]
Fixed for tomorrow’s release - thanks for reporting!
