### ISSUE TITLE
Hooking in on Element Route triggers unsupported operand error

### ISSUE THREAD

**Issue by bertoost** [craftcms/cms#3128]
### Description

I followed this https://docs.craftcms.com/v3/extend/updating-plugins.html#getelementroute from the documentation to "infiltrate" on existing entry routes to custom control the page via a controller.
Did it before in Craft 2, that's why I came on this doc page.
Therefor I now handle this in a module instead of a plugin, but that shouldn't matter right?

Unfortunate this gives me the next error;

![image](https://user-images.githubusercontent.com/398492/43046292-f889c6a0-8dc6-11e8-948a-e85c86c8bdc1.png)

### Additional info

- Craft version: 3.0.16.1
- PHP version: 7.1.17
- Database driver & version: MySQL 5.7.20

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next release, but in the meantime you can change how your route is defined:

```php
// from:
$event->route = 'products/view-entry';

// to:
$event->route = ['products/view-entry', []];
```

**Comment by bertoost** [comment]
Cool! Thanks.
