### ISSUE TITLE
[Suggestion] Add type declaration for (extra)AllowedFileExtensions etc

### ISSUE THREAD

**Issue by billythekid** [craftcms/cms#3131]
When you add a file extension to the allowed uploads/assets but output `{{ file.type }}` it can return 'undefined'. I propose that the config setting for allowedFileExtensions and extraAllowedFileExtensions be in the format `['extension'=>'type', … ]` where type is optional or make it an array of tuples `[['ext','type'],['ext,'type']]`, whatever implementation you like for backwards compatibility.

for example…

``` 
// key=>val style
'extraAllowedFileExtensions' => [
    'pub' => 'publisher', 
    'bz'  => 'compressed'
]

// tuple-style
'extraAllowedFileExtensions' => [
    ['pub', 'publisher'], 
    ['bz', 'compressed'],
]

```

perhaps this can be extended to include mimetypes too to add to Yii's getMimeTypeByExtension helper that it looks like Craft uses. (Which just maps pre-set values anyway)

**Comment by missmatsuko** [comment]
I think you can do this now with `extraFileKinds`.
https://docs.craftcms.com/v3/config/config-settings.html#extrafilekinds

**Comment by brandonkelly** [comment]
Yep! Added in 3.0.37.
