### ISSUE TITLE
Route input - UX improvments

### ISSUE THREAD

**Issue by astronauta88** [craftcms/cms#3136]
When clicking more than about 30px after end of text residing inside route input, cursor lands on start of input. It would be logical to place cursor on end of text residing inside input instead.

Ctrl+s keyboard shortcut doesnt trigger saving of route form - to be consistent with rest of CP, it should.

Selecting variable "pill" inside input, `delete` key should also delete it - right now only `backspace` does it. There should be also mouse-only solution.

**Comment by brandonkelly** [comment]
@astronauta88 Please edit this to focus on a single feature/enhancement request, and post additional issues for the others.
