### ISSUE TITLE
Bug: without filter doesn't really filter out anything

### ISSUE THREAD

**Issue by jan-dh** [craftcms/cms#3137]
### Description
When trying to get all the sites except for the current one, you should be able to filter it out like so:

`{% set otherLocales = craft.app.sites.getAllSites()|without(currentSite.id) %}`. 

However, the `|without` filter doesn't filter out anything. This will still give you a list with all the current sites.

### Steps to reproduce

1. Create a Craft site with multiple sites
2. Try filtering in the templates with `{% set otherLocales = craft.app.sites.getAllSites()|without(currentSite.id) %} `

Have tried it as such : `{% set otherLocales = craft.app.sites.getAllSites()|without(currentSite) %} `, but with the same result.

### Additional info

- Craft version:  3.0.16.1

**Comment by brandonkelly** [comment]
`craft.app.sites.getAllSites()` will give you an array of [craft\models\Site](https://docs.craftcms.com/api/v3/craft-models-site.html) objects. `currentSite.id` is an integer. So it is expected that your `|without` doesn’t have any effect on the array; none of the values in it are the same as the integer you’re passing in.

If you drop the `.id` it should work, though.

```twig
{% set otherLocales = craft.app.sites.getAllSites()|without(currentSite) %}
```

**Comment by jan-dh** [comment]
Yes, I also tried it without the `.id` but that also doesn't seem to work. Still gives me all my three sites.

**Comment by brandonkelly** [comment]
Sorry, you’re right, `|without` was broken if you passed an object into it. Fixed for today’s release.

**Comment by jan-dh** [comment]
Thanks!
