### ISSUE TITLE
Empty `defaultCpLanguage` sets initial account language to German on visiting and saving Account page

### ISSUE THREAD

**Issue by rungta** [craftcms/cms#3142]
### Description

A fresh Craft install with no custom value for the `defaultCpLanguage` config, and a single site with the language set to a region specific English (like `en-in`) does not appear to explicitly assign a language for the initial user account. This leads to the user account being assigned the first option from the list of supported languages in the _Language_ dropdown on the _My Account_ page, and saving that page results in the user's language inadvertently switching to German. The issue does not effect any subsequent accounts created from inside the control panel, just the initial account created during the setup process.

### Steps to reproduce

1. Create a fresh Craft CMS install
2. During the setup, pick a region specific English, like `en-IN` as the default site's _Language_.
3. Complete the setup process
4. Visit the default user's _My Account_ page
5. Save

### Additional info

- Craft version: 3.0.16.1
- PHP version: 7.1
- Database driver & version: MySQL

**Comment by brandonkelly** [comment]
With Dev Mode enabled, please create a test template with this in it:

```twig
{{ dump(craft.app.request.getAcceptableLanguages()) }}
```

Can you tell me what that outputs when you access it from a browser?

**Comment by rungta** [comment]
```
array(4) {
  [0]=>
  string(5) "en-GB"
  [1]=>
  string(2) "en"
  [2]=>
  string(5) "en-US"
  [3]=>
  string(2) "hi"
}
```

**Comment by brandonkelly** [comment]
Thanks! Fixed for today’s release.
