### ISSUE TITLE
New feature: alternate name for same field in different field layouts

### ISSUE THREAD

**Issue by bertoost** [craftcms/cms#3144]
For example: when you have a "pageBody" field, with name "Body". Sometimes you want to use another label for the field using it on a different field layout. Like "Bio" on a employee-entry. Would be nice you can change this. The same way they did in [Freeform](https://solspace.com/craft/freeform/#overview).

**Comment by carlcs** [comment]
It’s a duplicate of https://github.com/craftcms/cms/issues/806

**Comment by bertoost** [comment]
Good catch. This can be closed then.

**Comment by brandonkelly** [comment]
Gah, I knew I had seen this before, but couldn’t find it. Thanks @carlcs !
