### ISSUE TITLE
"Integrity constraint violation" when re-saving elements in multi-site installations

### ISSUE THREAD

**Issue by aelvan** [craftcms/cms#3146]
### Description

I have encountered this issue in two different scenarios; first when making a custom import routine for a new multi-site installation (with two sites), and when using the Preparse field plugin on multi-site installations with _more than two sites_ (oddly enough). Not 100% sure if this is a bug, or if I'm doing something wrong, but it's at least not obvious to me why this happends. The error I get is ([stacktrace](https://github.com/craftcms/cms/files/2224361/stacktrace.txt) attached):

```
Integrity constraint violation – yii\db\IntegrityException

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '9-4' for key 'craft_content_elementId_siteId_unq_idx'
The SQL being executed was: INSERT INTO `craft_content` (`elementId`, `siteId`, `title`, `field_preparseTestField`, `dateCreated`, `dateUpdated`, `uid`) VALUES (9, 4, 'qwdqwdq', NULL, '2018-07-24 15:29:11', '2018-07-24 15:29:11', '1801a51c-c01b-4315-ad67-a553478ddede')
```

The overall process that produces the error in a plugin/module is:

Create a new Entry.
Set some attributes.
Call `Craft::$app->getElements()->saveElement($element);`.
Do something... (or not)
Call `Craft::$app->getElements()->saveElement($element);` a second time on the same element.

If I instead do this, the error does not happen:

Create a new Entry.
Set some attributes.
Call `Craft::$app->getElements()->saveElement($element);`.
Get the ID of the new entry, and query for the entry using that ID.
Do something... (or not)
Call `Craft::$app->getElements()->saveElement($element);`.

The easiest way to reproduce the error is installing the Preparse Field plugin, so the steps to reproduce is based on that.

### Steps to reproduce

1. Install Craft and Preparse Field plugin.
2. Create three sites.
3. Create a preparse field (doesn't matter if it's set to propagate or not).
4. Create a section that's enabled for all sites.
5. Add the preparse field to the entry type.
6. Create a new entry and save. 

...and the error should occur.

### Additional info

- Craft version: 3.0.16.1
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Plugins & versions: Preparse Field 1.0.0

**Comment by brandonkelly** [comment]
I wasn’t able to reproduce this. Tried on a freshly-updated [Happy Lager](https://github.com/pixelandtonic/HappyLager) install, with the following code:

```php
$entry = new Entry();
$entry->sectionId = 2;
$entry->typeId = 6;
$entry->title = 'Testing';
Craft::$app->elements->saveElement($entry);
Craft::$app->elements->saveElement($entry);
```

Can you produce some specific code that demonstrates the issue (preferably without any plugins)?

**Comment by aelvan** [comment]
After retesting I see that my original post was a little bit wrong, sorry about that. But, I still think there's an issue or two here.. ;)

First, to recreate the issue I'm seeing in Preparse, add this to the init function of a module or plugin:

```
Event::on(Elements::class, Elements::EVENT_AFTER_SAVE_ELEMENT,
    function(ElementEvent $event) {
        $element = $event->element;

        if (!\in_array($element->id, $this->parsed, true)) {
            $this->parsed[] = $element->id;
            $success = Craft::$app->getElements()->saveElement($element);
        }
    }
);
```

The `parsed` variable has to be added to the class. And, this is the error that only happens when there's _more_ than two sites.

The error in my import routine was a tiny bit different than what I described, and may be a different issue all together. But, it happens when I try to set `siteId` on a saved element and resaving, like this:

```
$entry = new Entry();
$entry->sectionId = 1;
$entry->typeId = 1;
$entry->title = 'First site';
\Craft::$app->getElements()->saveElement($entry);

$entry->siteId = 2;
$entry->title = 'Second site';
\Craft::$app->getElements()->saveElement($entry);
```

The use-case being that I want to create a new entry with the imported data from the default site, plus any data that needs to propagate, and then update the localized data for the other sites.

I solved this by doing:

```
$entry = new Entry();
$entry->sectionId = 1;
$entry->typeId = 1;
$entry->title = 'First site';
\Craft::$app->getElements()->saveElement($entry);

$newId = $entry->id;
$entry = \craft\elements\Entry::findOne(['id' => $newId, 'siteId' => 2, 'status' => null, 'enabledForSite' => null]);

$entry->title = 'Second site';
\Craft::$app->getElements()->saveElement($entry);
```

Which is fine. I just thought that these two issues maybe was related. I notice now that if I try to set `siteId` to another site than the one I queried for, I get this error no matter what. Maybe that means that it's suppose to be read only?

**Comment by aelvan** [comment]
@carlcs That removes the exception, but the result is not really desirable, as it will only save the preparsed data for one of the sites. This result is the same as specifying in `saveElement` to not propagate, a route I already went down. :) But, the result of something like this:

```
Event::on(Elements::class, Elements::EVENT_AFTER_SAVE_ELEMENT,
    function (ElementEvent $event) {
        $element = $event->element;

        if (!\in_array($element->id, $this->parsed, true)) {
            $this->parsed[] = $element->id;

            $element->setFieldValue('testField', mt_rand(10000, 99999));
            $success = Craft::$app->getElements()->saveElement($element, true, false);
        }
    }
);
```

Is that `testField` is only updated for one of the sites. And, weirdly enough, not the default/active one, in my case the value is saved to the second site.

I guess one solution would be to parse the data, then loop over all sites, query for the element in question, store the data, and save. But it seems... convoluted. :)

**Comment by brandonkelly** [comment]
@aelvan I think you should do this:

```php
Event::on(Elements::class, Elements::EVENT_AFTER_SAVE_ELEMENT,
    function (ElementEvent $event) {
        $element = $event->element;

        // keep track of whether we've parsed this element *for this site*
        $key = $element->id. . '--' . $element->siteId;

        if (!\in_array($key, $this->parsed, true)) {
            $this->parsed[] = $key;

            $element->setFieldValue('testField', mt_rand(10000, 99999));
            $success = Craft::$app->getElements()->saveElement($element, true, false);
        }
    }
);
```

**Comment by aelvan** [comment]
@brandonkelly That works! 

And the other issue where setting the siteId results in the same error. Is the conclusion that I'm not suppose to do it? ;)

**Comment by brandonkelly** [comment]
If you change `siteId`, I think you’ll also need to change `contentId`, as each element will have a unique ID in the `content` table per ID/site ID. But yeah, probably just avoid changing either of those :)

**Comment by aelvan** [comment]
Ok, thanks. 

I now have found another issue related to Assets, but I'll post that as a separate issue. :)
