### ISSUE TITLE
Allow yii\queue::$ttr to be configurable

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#3147]
On sites with a lot of elements, I'm seeing errors like this from the queue on extra long-running tasks (Resaving all entries, etc):

```
The process "/usr/local/bin/php /app/bin/craft queue/exec "2137" "300" "1" "" --color=" exceeded the timeout of 300 seconds.
```

Does it makes sense to expose this to `GeneralConfig`?

**Comment by brandonkelly** [comment]
You can configure it from `config/app.php` like so:

```php
return [
    'components' => [
        'queue' => [
            'ttr' => 600,
        ],
    ],
];
```

**Comment by timkelty** [comment]
Figured :) thanks.

**Comment by naboo** [comment]
This would be a good thing to mention somewhere in the docs, like a special topic.
