### ISSUE TITLE
Provide method to add log target, instead of overriding component

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#3152]
I know I can fully override the `log` component in `config/app.php`, but I'm wondering if it might be nice to have a method to simply _add_ a log target.

Alternatively, there could be a method to get the default FileTarget configuration: https://github.com/craftcms/cms/blob/develop/src/config/app.php#L230-L262

Thoughts?

**Comment by timkelty** [comment]
Love it!

**Comment by brandonkelly** [comment]
I’ve been meaning to make those dynamic component configs easier to modify, so using this as my excuse to do it.

As of the next release, you will be able to do this from `config/app.php`:

```php
return [
    'components' => [
        'log' => function() {
            // Use the system's `log` config as a starting point
            $config = craft\helpers\App::logConfig();
            if ($config === null) {
                return null;
            }

            // Make changes
            $config['targets'][] = [
                // new log target config
            ];

            // Instantiate and return the component
            return Craft::createObject($config);
        },

        // ...
    ]
];
```
