### ISSUE TITLE
Eager loading sporadically not working

### ISSUE THREAD

**Issue by davist11** [craftcms/cms#3158]
### Description
This one may be somewhat hard to describe and diagnose, but here goes...

We have a multi-level navigation structure with two entry types

<img width="973" alt="screen shot 2018-07-26 at 10 13 00 am" src="https://user-images.githubusercontent.com/199985/43267650-86b6df56-90bc-11e8-9953-dbdb84099969.png">

The Secondary entry type has a matrix field named menu.

When outputting the navigation, I added some eager loading, and the children sporadically don't work on all pages

```
{% set navigation = craft.entries({
	section: 'navigation',
	site: 'hamilton',
	level: 1,
	with: [
		'children',
		'children.menu',
	],
}).all() %}

{% for item in navigation %}
	<li>
		<a>{{ item.title }}</a>

		{% if item.children | length %}
			<ul>
				...
			</ul>
		{% endif %}
	</li>
{% endfor %}
```

If I remove the eager loading, the children display correctly. Pretty weird edge case, so if nothing stands out, I can send URLs.

### Additional info

- Craft version: Craft Pro 3.0.16.1
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Plugins & versions:

<table class="data fullwidth fixed-layout">
        <tbody>
                            <tr>
                    <th class="light">Algolia</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Amazon S3</th>
                    <td>1.0.8</td>
                </tr>
                            <tr>
                    <th class="light">Asset Rev</th>
                    <td>6.0.1</td>
                </tr>
                            <tr>
                    <th class="light">AsyncQueue</th>
                    <td>1.3.3</td>
                </tr>
                            <tr>
                    <th class="light">Audit</th>
                    <td>2.0.1</td>
                </tr>
                            <tr>
                    <th class="light">Automatic Site Switch</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Calendar</th>
                    <td>2.0.4</td>
                </tr>
                            <tr>
                    <th class="light">Category Utilities</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Certificates</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Converge</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Craft Commerce</th>
                    <td>dev-develop</td>
                </tr>
                            <tr>
                    <th class="light">Enupal Snapshot</th>
                    <td>1.0.4</td>
                </tr>
                            <tr>
                    <th class="light">Environment Label</th>
                    <td>3.1.4</td>
                </tr>
                            <tr>
                    <th class="light">Feed Me</th>
                    <td>3.0.0-beta.17</td>
                </tr>
                            <tr>
                    <th class="light">Field Manager</th>
                    <td>2.0.2</td>
                </tr>
                            <tr>
                    <th class="light">Flat Categories</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Forms</th>
                    <td>2.2.1</td>
                </tr>
                            <tr>
                    <th class="light">Freeform Pro</th>
                    <td>2.2.1</td>
                </tr>
                            <tr>
                    <th class="light">Geo Cookie</th>
                    <td>1.2.1</td>
                </tr>
                            <tr>
                    <th class="light">Hamilton Utility</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Importer</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Inlin</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Inventory</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">OrderExporter</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Redactor</th>
                    <td>2.1.2</td>
                </tr>
                            <tr>
                    <th class="light">Sidebar Toggle</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th class="light">SimpleSentry</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Super Table</th>
                    <td>2.0.7</td>
                </tr>
                            <tr>
                    <th class="light">Taxes</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Twig Perversion</th>
                    <td>2.0.4</td>
                </tr>
                    </tbody>
    </table>

**Comment by brandonkelly** [comment]
What do you mean by “sporadically”? Are certain children consistently not loading? Which children? And is it the entire entry or just the Matrix blocks?

**Comment by davist11** [comment]
It varies from page to page, and I can't seem to track down any sort of pattern. Either all children display or none.

**Comment by brandonkelly** [comment]
Ok, and on a page where entries aren’t loading, if you keep refreshing the page, are they consistently not loading for that page?

**Comment by davist11** [comment]
Correct

**Comment by brandonkelly** [comment]
Can you try disabling your plugins to rule those out?

**Comment by davist11** [comment]
I disabled all the plugins I could without the template throwing a twig error. The following plugins are still enabled:

<table>
        <tbody>

<tr>
                    <th>Craft Commerce</th>
                    <td>dev-develop</td>
                </tr>
                <tr>
                    <th>Asset Rev</th>
                    <td>6.0.1</td>
                </tr>
                <tr>
                    <th>Geo Cookie</th>
                    <td>1.2.1</td>
                </tr>
                <tr>
                    <th>Inlin</th>
                    <td>2.0.0</td>
                </tr>
                <tr>
                    <th>Twig Perversion</th>
                    <td>2.0.4</td>
                </tr>
                    </tbody>
    </table>

And I'm still experiencing the issue.

**Comment by brandonkelly** [comment]
Alright, still a lot of unknowns in there. Can you try creating a fresh install and reproducing the issue?

**Comment by davist11** [comment]
I'm having a hard time re-creating on a fresh install. But, I removed virtually everything from the templates except for this navigation, and there are a bunch of extra queries being executed on pages where the navigation is showing. Here are the extra queries from the homepage, where the navigation displays correctly

<table>
<tbody>
<tr data-key="36"><td>15:02:53.189</td><td>19.5 ms</td><td>yii\db\Command::query</td><td><span class="indent">→</span><span class="indent">→</span><span class="indent">→</span>SELECT `ownerId` AS `source`, `id` AS `target`
FROM `craft_matrixblocks`
WHERE (`fieldId`='109') AND (`ownerId` IN ('471', '478', '484', '61706', '61715', '61721', '61727', '61733'))
ORDER BY `sortOrder`</td></tr>
<tr data-key="37"><td>15:02:53.214</td><td>14.5 ms</td><td>yii\db\Command::query</td><td><span class="indent">→</span><span class="indent">→</span><span class="indent">→</span>SELECT `fields`.`id`
FROM `craft_fields` `fields`
INNER JOIN `craft_matrixblocktypes` `blocktypes` ON `blocktypes`.`fieldId` = `fields`.`id`
INNER JOIN `craft_fieldlayoutfields` `fieldlayoutfields` ON `fieldlayoutfields`.`layoutId` = `blocktypes`.`fieldLayoutId`
WHERE `fieldlayoutfields`.`fieldId`='109'
LIMIT 1</td></tr>
<tr data-key="38"><td>15:02:53.230</td><td>0.6 ms</td><td>yii\db\Command::query</td><td><span class="indent">→</span><span class="indent">→</span><span class="indent">→</span>SELECT `id`, `fieldId`, `fieldLayoutId`, `name`, `handle`, `sortOrder`
FROM `craft_matrixblocktypes`
WHERE `fieldId`=109
ORDER BY `sortOrder`</td></tr>
<tr data-key="39"><td>15:02:53.232</td><td>1.7 ms</td><td>yii\db\Command::query</td><td><span class="indent">→</span><span class="indent">→</span><span class="indent">→</span>SELECT `fields`.`id`, `fields`.`dateCreated`, `fields`.`dateUpdated`, `fields`.`groupId`, `fields`.`name`, `fields`.`handle`, `fields`.`context`, `fields`.`instructions`, `fields`.`translationMethod`, `fields`.`translationKeyFormat`, `fields`.`type`, `fields`.`settings`
FROM `craft_fields` `fields`
WHERE `fields`.`context` IN ('matrixBlockType:20', 'matrixBlockType:21', 'matrixBlockType:37', 'matrixBlockType:38', 'matrixBlockType:39', 'matrixBlockType:40', 'matrixBlockType:82', 'matrixBlockType:22')
ORDER BY `fields`.`name`, `fields`.`handle`</td></tr>
<tr data-key="40"><td>15:02:53.242</td><td>1.3 ms</td><td>yii\db\Command::query</td><td><span class="indent">→</span><span class="indent">→</span><span class="indent">→</span>SELECT `flf`.`layoutId`, `fields`.`id`
FROM `craft_fields` `fields`
INNER JOIN `craft_fieldlayoutfields` `flf` ON `flf`.`fieldId` = `fields`.`id`
WHERE `flf`.`layoutId` IN ('526', '527', '709', '710', '711', '712', '778', '528')</td></tr>
<tr data-key="41"><td>15:02:53.248</td><td>13.4 ms</td><td>yii\db\Command::query</td><td><span class="indent">→</span><span class="indent">→</span><span class="indent">→</span>SELECT `elements`.`id`, `elements`.`fieldLayoutId`, `elements`.`uid`, `elements`.`enabled`, `elements`.`archived`, `elements`.`dateCreated`, `elements`.`dateUpdated`, `elements_sites`.`slug`, `elements_sites`.`uri`, `elements_sites`.`enabled` AS `enabledForSite`, `matrixblocks`.`fieldId`, `matrixblocks`.`ownerId`, `matrixblocks`.`ownerSiteId`, `matrixblocks`.`typeId`, `matrixblocks`.`sortOrder`, `content`.`id` AS `contentId`, `content`.`field_category_label`, `content`.`field_laboratory_label`, `content`.`field_robotics_label`, `content`.`field_storage_label`, `content`.`field_oem_label`, `content`.`field_processAnalytics_label`, `content`.`field_hamilton_label`, `content`.`field_url_customUrl`, `content`.`field_url_label`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`
FROM `craft_elements` `elements`
INNER JOIN `craft_matrixblocks` `matrixblocks` ON `matrixblocks`.`id` = `elements`.`id`
INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `craft_matrixcontent_menu` `content` ON `content`.`elementId` = `elements`.`id`
WHERE (`matrixblocks`.`fieldId`='109') AND (`elements_sites`.`siteId`='1') AND (`elements`.`id` IN ('96197', '61780', '61729', '61723', '61717', '61708', '473', '486', '487', '61724', '61718', '61730', '61709', '474', '61781', '8557', '8555', '475', '61719', '61725', '61731', '61710', '61782', '60856', '61732', '61726', '61827', '476', '61720', '483', '61711', '61703', '57364', '61783', '57492', '61713', '136363', '61704', '124599', '61828', '57365')) AND (`content`.`siteId`='1') AND (`elements`.`archived`=FALSE) AND (`elements`.`enabled`=TRUE) AND (`elements_sites`.`enabled`=TRUE)) `subquery`
INNER JOIN `craft_matrixblocks` `matrixblocks` ON `matrixblocks`.`id` = `subquery`.`elementsId`
INNER JOIN `craft_elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `craft_matrixcontent_menu` `content` ON `content`.`id` = `subquery`.`contentId`</td></tr>
<tr data-key="42"><td>15:02:53.283</td><td>6.4 ms</td><td>yii\db\Command::query</td><td><span class="indent">→</span><span class="indent">→</span><span class="indent">→</span>SELECT `id`, `type`
FROM `craft_fieldlayouts`
WHERE `id`=528
LIMIT 1</td></tr>
<tr data-key="43"><td>15:02:53.292</td><td>9.3 ms</td><td>yii\db\Command::query</td><td><span class="indent">→</span><span class="indent">→</span><span class="indent">→</span>SELECT `fields`.`id`, `fields`.`dateCreated`, `fields`.`dateUpdated`, `fields`.`groupId`, `fields`.`name`, `fields`.`handle`, `fields`.`context`, `fields`.`instructions`, `fields`.`translationMethod`, `fields`.`translationKeyFormat`, `fields`.`type`, `fields`.`settings`, `flf`.`layoutId`, `flf`.`tabId`, `flf`.`required`, `flf`.`sortOrder`
FROM `craft_fields` `fields`
INNER JOIN `craft_fieldlayoutfields` `flf` ON `flf`.`fieldId` = `fields`.`id`
INNER JOIN `craft_fieldlayouttabs` `flt` ON `flt`.`id` = `flf`.`tabId`
WHERE `flf`.`layoutId`=528
ORDER BY `flt`.`sortOrder`, `flf`.`sortOrder`</td></tr>
<tr data-key="44"><td>15:02:53.336</td><td>0.4 ms</td><td>yii\db\Command::query</td><td><span class="indent">→</span><span class="indent">→</span><span class="indent">→</span>SELECT `id`, `type`
FROM `craft_fieldlayouts`
WHERE `id`=526
LIMIT 1</td></tr>
<tr data-key="45"><td>15:02:53.338</td><td>2.4 ms</td><td>yii\db\Command::query</td><td><span class="indent">→</span><span class="indent">→</span><span class="indent">→</span>SELECT `fields`.`id`, `fields`.`dateCreated`, `fields`.`dateUpdated`, `fields`.`groupId`, `fields`.`name`, `fields`.`handle`, `fields`.`context`, `fields`.`instructions`, `fields`.`translationMethod`, `fields`.`translationKeyFormat`, `fields`.`type`, `fields`.`settings`, `flf`.`layoutId`, `flf`.`tabId`, `flf`.`required`, `flf`.`sortOrder`
FROM `craft_fields` `fields`
INNER JOIN `craft_fieldlayoutfields` `flf` ON `flf`.`fieldId` = `fields`.`id`
INNER JOIN `craft_fieldlayouttabs` `flt` ON `flt`.`id` = `flf`.`tabId`
WHERE `flf`.`layoutId`=526
ORDER BY `flt`.`sortOrder`, `flf`.`sortOrder`</td></tr>
<tr data-key="46"><td>15:02:53.348</td><td>0.4 ms</td><td>yii\db\Command::query</td><td><span class="indent">→</span><span class="indent">→</span><span class="indent">→</span>SELECT `id`, `type`
FROM `craft_fieldlayouts`
WHERE `id`=712
LIMIT 1</td></tr>
<tr data-key="47"><td>15:02:53.351</td><td>2.9 ms</td><td>yii\db\Command::query</td><td><span class="indent">→</span><span class="indent">→</span><span class="indent">→</span>SELECT `fields`.`id`, `fields`.`dateCreated`, `fields`.`dateUpdated`, `fields`.`groupId`, `fields`.`name`, `fields`.`handle`, `fields`.`context`, `fields`.`instructions`, `fields`.`translationMethod`, `fields`.`translationKeyFormat`, `fields`.`type`, `fields`.`settings`, `flf`.`layoutId`, `flf`.`tabId`, `flf`.`required`, `flf`.`sortOrder`
FROM `craft_fields` `fields`
INNER JOIN `craft_fieldlayoutfields` `flf` ON `flf`.`fieldId` = `fields`.`id`
INNER JOIN `craft_fieldlayouttabs` `flt` ON `flt`.`id` = `flf`.`tabId`
WHERE `flf`.`layoutId`=712
ORDER BY `flt`.`sortOrder`, `flf`.`sortOrder`</td></tr>
</tbody>
</table>

I'm not sure what I can do to help diagnose this, especially since it doesn't happen on every page. What would be helpful? Specific URLs? Access to the repo?

**Comment by brandonkelly** [comment]
If you can’t give us specific steps to reproduce, there’s not much more we can help with. It is most likely going to be a problem created by either a plugin or custom site-specific code.
