### ISSUE TITLE
Craft license across multi-site domains

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#3161]
Multi-sites with different TLDs will complain about a mismatched license in CP when trying to access via a different domain than what is registered in Craft ID.

Example:
- Craft ID domain: sitea.com
- User accesses CP at `siteb.com/admin`, and gets a license error

I'm currently solving this by forcing CP access from the registered domain, but seems like something that should be allowed. 

Related-ish: https://github.com/craftcms/cms/issues/1160

**Comment by brandonkelly** [comment]
This is a critical part of how our license enforcement works: https://craftcms.com/support/license-enforcement#single-website-enforcement

**Comment by timkelty** [comment]
👍 thanks, makes sense.
Seems like locking the CP down to a single domain is the way to go.
