### ISSUE TITLE
Rich Text fields using Redactor in Craft CMS 2 don't correctly work with IMEs

### ISSUE THREAD

**Issue by roberttolton** [craftcms/cms#3166]
### Description

Rich Text fields using Redactor in Craft CMS 2 don't correctly work with IMEs (Input Method Editors) for inputting text such as Japanese. Standard text input fields work fine, as does using the 'Edit Source' mode of the Redactor field. This happens in both Simple and Standard configurations.

Anyone had anything similar?

Maybe Craft's implementation is doing something with these events?: https://stackoverflow.com/a/37099672

Thinking this might be limited to Redactor 2 (but can't find a non Craft-enhanced demo of Redactor 2), while the demo on the Redactor site is version 3.

An implementation of CK Editor by Verbb seems fine, but this obviously looses the Craft-enhancements: http://cloud.roberttolton.com/2o1v392d1k3a

### Steps to reproduce

Using Redactor demo page to input correctly:
http://cloud.roberttolton.com/401R2q083800

Using Edit Source mode inputs correctly:
http://cloud.roberttolton.com/3b3K3W2h2k1m

Same doesn't work when using Craft's implementation of Redactor in the normal mode:http://cloud.roberttolton.com/363k1w0c1d46

### Additional info

- Craft version: 2.6.3019 (Pro)
- PHP version: 7.1.12-3+ubuntu14.04.1+deb.sury.org+1
- Database driver & version: MySQL 5.5.5-10.1.30-MariaDB-1\~trusty
- Plugins & versions: 
    - Asset Rev 5.0.0
    - Asset Usage 1.0.2
    - Button Box 1.5.0
    - Cache Clear 1.0.1
    - Cache Flag 1.1.11
    - camelCase to kebab-case filter 1.1
    - Default Locale 1.0.1
    - Element API 1.6.0
    - Email From Template 0.0.1
    - Imager 1.6.4
    - Language Link 1.1.0
    - Link It 2.3.4
    - Locale Redirector 1.0.4
    - Locale Sync 1.5.1
    - Minify 1.2.0
    - Navee 1.3.0
    - Neo 1.5.0
    - Papertrail 1.0.0
    - Papertrail Route 0.1.0
    - Patrol 1.4.2
    - Preparse Field 0.3.6
    - Retour 1.0.22
    - SEO 1.1.56
    - Simple Map 1.8.2
    - Simple Text 1.1
    - Smart Doll 1.0.0
    - Super Table 1.0.6

**Comment by brandonkelly** [comment]
Craft isn’t doing anything to suppress this; most likely it just wasn’t available for Redactor 2, but is for Redactor 3. Unfortunately v3 is a breaking change so we can’t update Craft 2 to it, but our [Redactor plugin](https://github.com/craftcms/redactor) for Craft 3 does use Redactor 3.
