### ISSUE TITLE
Re-saving Asset elements on upload in EVENT_AFTER_SAVE_ELEMENT event result in validation error

### ISSUE THREAD

**Issue by aelvan** [craftcms/cms#3167]
### Description

When uploading a new asset and trying to add content and re-save in an EVENT_AFTER_SAVE_ELEMENT event, the following validation error is thrown:

```
2018-07-30 17:07:40 [::1][1][-][info][craft\services\Elements::saveElement] Element not saved due to validation error: Array
(
    [newLocation] => Array
        (
            [0] => New Location cannot be blank.
        )

    [tempFilePath] => Array
        (
            [0] => Temp File Path cannot be blank.
        )

)

2018-07-30 17:07:40 [::1][1][-][info][application] $_GET = [
    'p' => 'admin/actions/assets/save-asset'
]
```

### Steps to reproduce

1. Create a new local asset source.
2. Create a field with handle `testField` and add to the asset source field layout.
3. Add the following event handler to a module's init method. The class needs a property named `parsed`:

```
Event::on(Elements::class, Elements::EVENT_AFTER_SAVE_ELEMENT,
    function (ElementEvent $event) {
        $element = $event->element;
        $key = $element->id . '__' . $element->siteId;
        
        if (!\in_array($key, $this->parsed, true)) {
            $this->parsed[] = $key;

            $element->setFieldValue('testField', mt_rand(10000, 99999));
            Craft::$app->getElements()->saveElement($element, true, false);
        }
    }
);
```  

4. Upload a new file to the asset source and observe that the field `testField` is empty. The validation error is in the `web.log`. Re-saving an existing asset updates the field as expected.

### Additional info

- Craft version: 3.0.17.1
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38

**Comment by andris-sevcenko** [comment]
If you're reusing that same element, it'll have the scenario set to `create` and it will expect certain properties to be set on save. Properties, that get nulled after being consumed. Your best bet is probably setting the scenario to the default one in your event handling code. (`$element->setScenario(Element::SCENARIO_DEFAULT);` should work)

**Comment by aelvan** [comment]
Thanks @andris-sevcenko, that works. Follow-uo question though.. Is this something I can safely set for all element types, or could that result in unwanted behavior? This is for Preparse Field, so the handler could potentially be run for all different kinds of elements. Should I do a check and only set scenario if the element is an Asset?

**Comment by andris-sevcenko** [comment]
Just based on the fact that there are a lot of custom elements out there, I'd say you should stick to checking if it's an Asset. You can never know what crazy stuff people are doing/will do with scenarios in their 3rd party plugins, for example.
