### ISSUE TITLE
Twig Globals are not registered in console requests for site templates

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#3169]
### Description
We want to render and send frontend E-Mail templates via console request that may contain globals from our Twig Extension but we always receive an error due to the different environments if we don't register them again after we changed the template mode

### Steps to reproduce

1. Create a Twig Extension and include a `getGlobals` function 
2. Register it in your plugins `init` function
3. Create a console controller and try to render a template that uses a `global` from your Twig Extension 
4. See an exception is thrown

### Steps to solve the issue (developer point of view)

```PHP
Craft::$app->view->setTemplateMode(View::TEMPLATE_MODE_SITE);
// after changing the template mode, just register it again
Craft::$app->getView()->getTwig()->addGlobal('profile', someValue);
```

### Additional info

- Craft version: Craft Pro 3.0.15
- PHP version: 7.0.7

**Comment by brandonkelly** [comment]
The trick is, in step 2, you should be registering the extension with [View::registerTwigExtension()](https://docs.craftcms.com/api/v3/craft-web-view.html#public-methods), rather than adding it to the Twig environment manually. Then Craft will keep track of it, and re-register it if the templame mode ever changes.

**Comment by Anubarak** [comment]
I do the following currently which produces an error in console requests

```PHP
Craft::$app->view->registerTwigExtension(new ThaffTwigExtension());
```

**Comment by brandonkelly** [comment]
What error are you getting? And can you post the stack trace (should be shown in `storage/logs/console.log`)

**Comment by Anubarak** [comment]
@brandonkelly 

> Exception 'Twig_Error_Runtime' with message 'Variable "profile" does not exist.'

This is because 

```PHP
public function registerTwigExtension(Twig_ExtensionInterface $extension)
{
    $this->_twigExtensions[] = $extension;

    // Add it to any existing Twig environments
    if ($this->_cpTwig !== null) {
        $this->_cpTwig->addExtension($extension);
    }
    if ($this->_siteTwig !== null) {
        echo "<pre>";
        var_dump("I'm defined");
        echo "</pre>";
        die();
        $this->_siteTwig->addExtension($extension);
    }
}
```
For normal site requests I see `I'm defined` console request outputs nothing -> the extension is not registered in `_siteTwig`

**Comment by brandonkelly** [comment]
It’s OK if `_siteTwig` isn’t defined yet; it will get added to the `_twigExtensions` array regardless, and then `createTwig()` is _supposed_ to loop through that and register everything in there.

https://github.com/craftcms/cms/blob/f5f4a10d180676705f9e0818935a79a5b3568af1/src/web/View.php#L265-L268

> And for whatever reasons it is not registered correctly in `createTwig` afterwards

So the question is, why not?

My guess is that it is one of these things:

- You are creating your own Twig environment rather than going through `View::getTwig()`
- You are rendering your template before the Twig extension was actually registered.

**Comment by brandonkelly** [comment]
`secondred\thaff\twigextensions\ThaffTwigExtension` and `Twig_Extensions_Extension_Text` aren’t added by Twig or Craft, and those are showing up in your console requests. So how are those being added?

**Comment by Anubarak** [comment]
In my plugins init function
```PHP
$twigExtension = new ThaffTwigExtension();
Craft::$app->getView()->registerTwigExtension($twigExtension);
```

and my getGlobals function
```PHP
    public function getGlobals(): array
    {
        return [
            'profile' => Thaff::getInstance()->getProfileService(),
            'hashKeySeparator'        => ';',
            'hashValueSeparator'      => '-',
            'hashArraySeparator'      => ':',
            'locationSeparator'       => '*',
            'locationSlugSeparator'   => '/',
            'defaultHash'             => [
                'ansicht'    => 'list',
                'seite'      => '1',
                'sortierung' => 'publishDate'
            ],
            'defaultHashContactGuide' => [
                'ansicht'    => 'grid',
                'seite'      => '1',
                'sortierung' => 'startDate'
            ],
            'defaultHashCalendar' => [
                'ansicht'    => 'list',
                'monat'      => (new \DateTime())->format('m'),
                'jahr'      => (new \DateTime())->format('Y'),
            ],
            'defaultHashMedia' => [
                'kategorie'    => 'alle',
                'dateien'    => '', // injected via JS
            ],
        ];
    }
```

All those values are available in site request but not in console request..
All I do in my console controller is

```PHP
$this->$oldMode = Craft::$app->view->getTemplateMode();
 Craft::$app->view->setTemplateMode(View::TEMPLATE_MODE_SITE);
$html = Craft::$app->getView()->renderTemplate('somePath', $variables);
```

When I include 
`Craft::$app->getView()->getTwig()->addGlobal('profile',  Thaff::getInstance()->getProfileService())` or when I remove the `{%do plugin.doSomething %}` call in my template everything works fine. And yes I made sure `getProfileService` returns a valid object and not null / undefined.

**Comment by brandonkelly** [comment]
To clarify, why are `secondred\thaff\twigextensions\ThaffTwigExtension` and `Twig_Extensions_Extension_Text` registered for console requests, but not `secondred\base\twigextensions\TwigExtension`?

**Comment by Anubarak** [comment]
They are - but not in `View::TEMPLATE_MODE_SITE`

```PHP
// contains all extensions with all globals
// all in all it prints 10 items
echo "<pre>";
var_dump(array_keys(Craft::$app->getView()->getTwig()->getExtensions()));
echo "</pre>";

Craft::$app->getView()->setTemplateMode(View::TEMPLATE_MODE_SITE);

// doesn't contain them
// prints only 8 items
echo "<pre>";
var_dump(array_keys(Craft::$app->getView()->getTwig()->getExtensions()));
echo "</pre>";
die();
```

`secondred\base\twigextensions\TwigExtension` is registered the same way 
```PHP
Craft::$app->getView()->twig->addExtension(new TwigExtension());
```

There are no checks about the request type.

**Comment by brandonkelly** [comment]
Instead of
```php
Craft::$app->getView()->twig->addExtension(new TwigExtension());
```
It should be
```php
Craft::$app->getView()->registerTwigExtension(new TwigExtension());
```

**Comment by Anubarak** [comment]
Okay okay, but since that extension doesn't do something anyway (it's not mine and I don't use it).

Did you ever face a similar issue or would you recommend to add the global after changing the template mode?

**Comment by brandonkelly** [comment]
I can’t reproduce, no. I think if you fix the `addExtension()` call (and any other `getTwig()` calls in plugins/modules) so only `registerTwigExtension()` is used, it will fix your `profile` error.

**Comment by Anubarak** [comment]
Okay.... I found the issue - maybe you could eventually explain this but it was due to a missing `implements Twig_Extension_GlobalsInterface`

All my extensions had a function `getGlobals` and for frontend requests everything worked fine, but as soon as I changed the template mode - for whatever reason - those globals are not accessible in the other mode if it's a console request.

That's why someone else pinged me a certain thing from [Commerce Extension](https://github.com/craftcms/commerce/blob/develop/src/web/twig/Extension.php) wasn't available for him as well but [Crafts](https://github.com/craftcms/cms/blob/develop/src/web/twig/Extension.php#L56) as soon as I remove `implements \Twig_Extension_GlobalsInterface` from your class the following 

```PHP
echo "<pre>";
var_dump(array_keys(Craft::$app->getView()->getTwig()->getGlobals()));
var_dump(array_keys(Craft::$app->getView()->getTwig()->getExtensions()));
echo "</pre>";
```

prints
```
<pre>array(12) {
  [0]=>
  string(12) "secondredSEO"
  [1]=>
  string(8) "homepage"
  [2]=>
  string(7) "profile"
  [3]=>
  string(16) "hashKeySeparator"
  [4]=>
  string(18) "hashValueSeparator"
  [5]=>
  string(18) "hashArraySeparator"
  [6]=>
  string(17) "locationSeparator"
  [7]=>
  string(21) "locationSlugSeparator"
  [8]=>
  string(11) "defaultHash"
  [9]=>
  string(23) "defaultHashContactGuide"
  [10]=>
  string(19) "defaultHashCalendar"
  [11]=>
  string(16) "defaultHashMedia"
}
array(10) {
  [0]=>
  string(19) "Twig_Extension_Core"
  [1]=>
  string(22) "Twig_Extension_Escaper"
  [2]=>
  string(24) "Twig_Extension_Optimizer"
  [3]=>
  string(27) "Twig_Extension_StringLoader"
  [4]=>
  string(24) "craft\web\twig\Extension"
  [5]=>
  string(20) "Twig_Extension_Debug"
  [6]=>
  string(43) "secondred\base\twigextensions\TwigExtension"
  [7]=>
  string(49) "secondred\thaff\twigextensions\ThaffTwigExtension"
  [8]=>
  string(30) "Twig_Extensions_Extension_Text"
  [9]=>
  string(48) "secondred\formbuilder\web\twig\GetClassExtension"
}
```

And I receive an error 

> craft is not defined

 In Twig. Any Ideas?
