### ISSUE TITLE
Add support for setting propagate to false for localized Element in getEditorHtml request

### ISSUE THREAD

**Issue by BenParizek** [craftcms/cms#3173]
### Description

I think this may be a bug, or unconsidered scenario, but I'm not really sure. It could also just be a question or misunderstanding on my part.

I have an Element which is localized, but there is no way to translate an Element between sites. Each site just has their respective entries.

Everything is working fine except when trying to save the Element via the Element Edit modal defined by the `Element::getEditorHtml()` method.

### Steps to reproduce

Craft handles how this form is submitted and submits directly to the saveElement method, setting the $propograte attribute to true. I don't appear to have any way to control that value.

The first saveElement works fine, however, when it begins to propagate the second attempt to save results in an error when attempting to run the element validation. The error is "Unknown scenario: essentials".

When we call saveElement from our plugin we set $propagrate to false. And if I hard code the Craft saveElement method to set $propagrate to false, the save works.

Is there a way I can set $propagate to false from the getEditorHtml request? Or are there any alternatives I'm not considering?

If helpful, the getEditorHtml method our Element is using is here: 
https://github.com/barrelstrength/craft-sprout-seo/blob/develop/src/elements/Redirect.php#L295

### Additional info

- Craft version: 3.0.17
- PHP version: 7.1
- Database driver & version: MySQL
- Plugins & versions: various under development

**Comment by brandonkelly** [comment]
You shouldn’t be looking to `$propagate = false` as a way to prevent an element from being saved at all for other sites.

If you want an element to only exist in a single site, then override the [getSupportedSites()](https://docs.craftcms.com/api/v3/craft-base-elementinterface.html#method-getsupportedsites) method and only return an array with that one site’s ID.

```php
public function getSupportedSites(): array
{
    // limit to just the one site this element is set to
    return [$this->siteId];
}
```

**Comment by BenParizek** [comment]
This works perfectly. Just what I was looking for. Thanks. I'll dig into `getSupportedSites` more.
