### ISSUE TITLE
Feature request: add 'class' parameter to svg()

### ISSUE THREAD

**Issue by frankharrison-wj** [craftcms/cms#3174]
Would be great for the svg() function to allow a second 'class' parameter which would inject that class name into the SVG before inlining it. I built my own plugin to do this but would be nice to have out-of-the-box!

**Comment by brandonkelly** [comment]
Not sure I’m following. You mean so it ends up like this?

```xml
<svg class="<TheClassName>" ... />
```

**Comment by frankharrison-wj** [comment]
Yep – can also be done with a find and replace on the text, but would be nice to have it as part of the svg() function if possible.

**Comment by brandonkelly** [comment]
I’m not really interested in making the `svg()` function more complicated than it needs to be. You could just wrap the SVG in a `<div>` with the class name instead.

**Comment by frankharrison-wj** [comment]
Fair enough – I'll stick to my plugin!

**Comment by benface** [comment]
@frankharrison-wj Have you released this plugin somewhere by any chance? :)

**Comment by brandonkelly** [comment]
I’ve actually seen the light on why a `class` attribute would be super helpful, so reopening this and will see if we can get it into 3.1 before it goes out of beta.

**Comment by benface** [comment]
@brandonkelly Great! Have you been using functional CSS by any chance? ;)

**Comment by brandonkelly** [comment]
Haha yes :)

**Comment by brandonkelly** [comment]
OK added for the next 3.1 beta release :)

**Comment by benface** [comment]
That was fast!

**Comment by frankharrison-wj** [comment]
Ah that's great! Was about to say that I'd not released my plugin anywhere, as it's probably not super-stable and relies on being used exactly as I use it! But glad to see I'm not going to need it soon.
