### ISSUE TITLE
Globals are not saved on a per site basis

### ISSUE THREAD

**Issue by divyan** [craftcms/cms#3176]
### Description
Globals are not saved on a per site basis.

### Steps to reproduce

1. Create some sites.
2. Create a field: text or e-mail.
3. Create a Global set with that field.
4. Add value in that text/e-mail field and save it for the default/main site.
5. Change the site on the Globals page and edit the text-field and save the field.
6. Switch back to the main/default site and you'll see that the value saved globally and not on a per site basis.

### Additional info

- Craft version: Craft Pro 3.0.17.1
- PHP version: 7.1.20
- Database driver & version: MySQL 5.7.22
- Plugins & versions:
HTTP2 Server Push 	1.0.0
Inlin 	2.0.0
Linkit 	v1.0.8
Schematic 	4.0.14
SEO 	3.3.0
Sites Field 	1.0.0
SuperSort 	3.0.1
Super Table 	2.0.7

**Comment by angrybrad** [comment]
Guessing the fields you've got assigned to the Global you're testing this on have their "Translation Method" setting set to "Not translatable".  Change those to "Translate for each site" and those fields in the Global still start saving on a per-site basis.
