### ISSUE TITLE
Issues in IE11 backend layout

### ISSUE THREAD

**Issue by pette87** [craftcms/cms#3177]
### Description

Checkboxes in entries not on the right place.  

https://imgur.com/fk1L3pi

### Steps to reproduce

1. go to entries or see screenshot

### Additional info

- Craft version: 3.0.9 and higher

### Solution

IE11 CSS hack:

```
_:-ms-lang(x),
.elements .tableview td.checkbox-cell input.checkbox + label, .elements .tableview td.checkbox-cell div.checkbox {
    top: 16px;
}

_:-ms-lang(x),
body.ltr input.checkbox + label:empty, body.ltr div:empty.checkbox {
    display: block;
}
```

**Comment by brandonkelly** [comment]
Fixed, thanks for providing the CSS!
