### ISSUE TITLE
Internal Server Error when restoring a draft containing a matrix field

### ISSUE THREAD

**Issue by tpmatthes** [craftcms/cms#3183]
### Description

If you restore a revision of an entry with a matrix field, that no longer contains a dropdown, you get an internal server error:

```
Setting unknown property: craft\behaviors\ContentBehavior::dropdown
```

Expected behavior: Craft should just ignore the dropdown field since it no longer exists. :)

### Steps to reproduce

The error occured on a big website, but you can reproduce it on a new installation:

1. Create a fresh Craft 3 installation.
2. Create a single section.
3. Create a matrix field with one block. The block should contain a dropdown with multiple options and a plain text field.
4. Add the matrix field to the section.
5. Edit the entry, add some matrix blocks with content and save a new version.
6. Remove the dropdown from the matrix block (via field settings).
7. Go back to the entry and restore a revision -> error!

### Additional info

- Craft version: 3.0.18
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Plugins & versions: nothing

I’m happy to provide you with more information, if needed.

**Comment by brandonkelly** [comment]
Just got that fixed for tomorrow’s update. Thanks for reporting!
