### ISSUE TITLE
Error on assets propagation and moving to other folder

### ISSUE THREAD

**Issue by DiederikVanHoorebeke** [craftcms/cms#3184]
### Description
After adding a second site, the `Propagating asset elements` task failed. 
The response json contains:
```
description: "Propagating asset elements"
error: "Undefined offset: 1"
id: "106"
progress: 0
status: 4
```

Dragging a file to another location also causes an error:
```
error: "Undefined offset: 1"
```

### Steps to reproduce the first error

1. Create Assets volume (Type: Amazon S3)
2. Add create an assets field and add it to a section and use the field in the content SEO in SEOmatic as the source for the SEO image
3. Create a secondary site and use `@web/` as Base URL (This is where the error occurred)
4. Update the general config file and add the correct Base URL for the site handle (Didn't fix it)

### Additional info

- Craft version: Craft Pro 3.0.19
- PHP version: 7.2.8
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Amazon S3: 1.0.8, Calendar: 2.0.5, Craft Cheat Sheet: 2.0.2, Craft Commerce: 2.0.0-beta.7, Entry Instructions: 1.0.0, Freeform lite: 2.2.2, Mailchimp Subscribe: v2.0.2, Minify: 1.2.9, Mollie for Craft Commerce: 1.0.0, Password Policy: 1.0.3, Position Fieldtype: 1.0.13, Redactor: 2.1.5, Redirect plugin for Craft 3: 1.0.17, Responsive Images: 0.2.1, SEOmatic: 3.1.13.1, Similar: 1.0.3, Super Table: 2.0.7, Upper: 1.3.7

**Comment by DiederikVanHoorebeke** [comment]
I get the same error, when trying to drag a file to another folder in Assets: `error: "Undefined offset: 1"`.
This issue was also present before the second site was added.

**Comment by brandonkelly** [comment]
Can you please send a database backup, and your `composer.json` and `composer.lock` files, at support@craftcms.com ? We can try to look into this from there.

**Comment by brandonkelly** [comment]
This ended up being due to a bug in the Responsive Images plugin.

Bug report: gentsagency/craft-responsive-images#2
