### ISSUE TITLE
in an entry editor, a time field can be opened while logged out

### ISSUE THREAD

**Issue by olets** [craftcms/cms#3186]
### Description

Can get into a field that should be blocked until login

### Steps to reproduce

1. log in
1. edit and entry
1. time out so you're logged out
1. while interacting with the login modal, it's possible to open a date field.

I haven't figured exactly when/how this happens. I'm on macOS using a password stored in 1password, so opening the password picker with option-command-\ and then arrowing the right password and hitting enter.

![login](https://user-images.githubusercontent.com/3282350/43863824-e28e39cc-9b2b-11e8-961b-c58f371212e1.png)

### Additional info

- Craft version: 3.0.18

**Comment by brandonkelly** [comment]
Thanks for reporting that!
