### ISSUE TITLE
jQuery .load and {% js %}

### ISSUE THREAD

**Issue by johnj24** [craftcms/cms#3188]
### Description
I'm trying to get my head around how we can include {% js %} within a partial template that then gets loaded into a parent template via jQuery .load. What I think is happening is the `{% js %}` is rendering before getting to the parent template, and since no `<body>` element is found in the partial template, Craft doesn't place the js anywhere.

For example, this does not log anything into console:

jstest.twig
```
<html>
<head></head>
<body>
  <button>Load content</button>
  <div></div>

  <script src="[jquery]"></script>
</body>
</html>

{% js %}
  $(function() {
    $('button').click(function() {
      event.preventDefault();

      $('div').load("jstest-partial");
    });
  });
{% endjs %}
```

jstest-partial.twig
```
foo

{% js %}
  $(function() {
    console.log( "ready!" );
  });
{% endjs %}
```

### Additional info

- Craft version: 3.0.17.1

**Comment by brandonkelly** [comment]
By default Craft will output dynamically-registered scripts right before the `</body>` tag. If your partial doesn’t have one of those, then you can add a `{{ endBody() }}` tag to your template wherever you want the scripts to output.

It can even go before your `{% js %}` tag if you want.

```twig
foo
{{ endBody() }}

{% js %}
  $(function() {
    console.log( "ready!" );
  });
{% endjs %}
```
