### ISSUE TITLE
Allow disabling of Live Preview

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#3192]
Live preview doesn't currently work for SPAs or API-driven sites where you're not using Twig, but still have Craft-managed URLs.

It would be nice to be able to disable the Live Preview button all together.

**Comment by khalwat** [comment]
...or even better, have a way to map it to the "real" URL for the site, so content authors can preview it.

**Comment by timkelty** [comment]
> ...or even better, have a way to map it to the "real" URL for the site, so content authors can preview it.

In my case, the Craft URL _is_ the "real" url…(but the site's URL isn't pointing to the Craft Server, it points to a Node/Express server). But that page just makes calls to the craft server/api, it doesn't know how to response to live preview POST data like Craft Twig templates do.

**Comment by brandonkelly** [comment]
We’ll most likely make this possible when we get around to #1489. In the meantime, you could just set your section’s Template setting to an invalid template path. The Live Preview button will only show up if the section has URLs _and_ the template exists. (A blank Template path is still valid if you have an `index.twig` file.)

**Comment by timkelty** [comment]
Good tip, @brandonkelly!

**Comment by narration-sd** [comment]
That is a smart one :)

**Comment by timkelty** [comment]
> The Live Preview button will only show up if the section has URLs and the template exists.

@brandonkelly the bummer about that is it _also_ removed the "share" button, so there's no way to open the entry URL from entry edit.

For a quick fix, made this: https://github.com/craftcms/cms/pull/4275

**Comment by brandonkelly** [comment]
You were one day too early @timkelty :) #1489 is resolved now as of Friday, so now there’s a way to share/preview entries (and other elements) whether or not Craft is the one rendering them.
