### ISSUE TITLE
AssetQuery height/width as string

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#3195]
### Description

The docs and the source code states you are able to pass things like `width('>= 500')`  as a parameter to the function https://github.com/craftcms/cms/blob/develop/src/elements/db/AssetQuery.php#L117.

But the function is
```php
    public function width(int $value = null) // <-- the int will disallow strings thus `>=` is invalid
    {
        $this->width = $value;
        return $this;
    }
```

### Steps to reproduce

1. create an AssetQuery
2. search for height/width values in range/larger/smaller than
3. notice an exception `>= 500 cant't  be converted to integer`

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for tomorrow’s release.
