### ISSUE TITLE
Multi-Site Config: '@' Alias Value Does Not Apply to 'BaseURL' Field

### ISSUE THREAD

**Issue by bryantwells** [craftcms/cms#3198]
### Steps to reproduce

1. Define an alias within `/config/general.php`, e.g.:
```
'aliases' => [
    '@blog' => getenv('BLOG_URL'),
],
```
2. Apply the alias in `settings > site` to a site that is **not marked as primary**.
3. The alias will not be translated to an actual value after being saved. Default aliases (like `@web`) will not work either.

### Additional info

- Craft version: 3.0.19
- PHP version: 7.0
- Database driver & version: MySQL [5.6.32-78.1]
- Plugins & versions: SEOmatic [3.1.13.1], FeedMe [3.0.0-beta.17], Redactor [2.1.5], Mailchimp Subscribe [2.0.2], Typogrify [1.1.11]

**Comment by brandonkelly** [comment]
You should still see `@blog` (or `@web` if you go with that) in the Control Panel; Craft will only parse the Base URL for aliases when generating actual URLs based off of it.

**Comment by bryantwells** [comment]
@brandonkelly  Hmm... When used in a template, `{{ craft.app.sites.getSiteByHandle('someSiteHandle').baseUrl }}` spits out the alias string (`@blog`) — not the intended URL.
