### ISSUE TITLE
Add `rel="noopener"` for all external links

### ISSUE THREAD

**Issue by XhmikosR** [craftcms/cms#3201]
References

* https://developers.google.com/web/tools/lighthouse/audits/noopener
* https://mathiasbynens.github.io/rel-noopener/
* https://jakearchibald.com/2016/performance-benefits-of-rel-noopener/

There are some links dynamically created in JS; those should have it too.

I have a local branch which takes care of this, but since I'm not familiar with the code base I decided not to submit it. If it'll help, I can make a PR, though.

**Comment by brandonkelly** [comment]
Craft already sets a referrer policy for all Control Panel pages, so this is not necessary.

https://github.com/craftcms/cms/blob/2058b4cd50969a98daa7dd77196afa1c9cd5cbbf/src/templates/_layouts/base.html#L19

**Comment by XhmikosR** [comment]
@brandonkelly: this is not related to the referrer. Please read the links above.

**Comment by XhmikosR** [comment]
Done in #3202.
