### ISSUE TITLE
Redirect url in form not being used for Ajax / JSON requests

### ISSUE THREAD

**Issue by nathanedwards** [craftcms/cms#3204]
### Description

When you post a login form via AJAX (to the UsersController, i.e `users/login` ) it doesn't get the 'redirect' param from the post request, so in the JSON response `returnUrl` only ever gets the value from the `postLoginRedirect` setting in `general.php`

### Steps to reproduce

1. Use `{{ redirectInput('some-url') }}` in a form, amongst the usual fields
2. Post that form with AJAX *(in this case I'm using Axios.)*

```JavaScript
const form = document.getElementById('my-login-form')
const data = new FormData(form);
const config = {
	responseType: 'json',
	headers: {
		'X-Requested-With': 'XMLHttpRequest',
		'Content-Type': 'application/x-www-form-urlencoded'
	}
};

axios.post( window.location.href, data, config )
	.then(function (response) {
		console.log( response.data );
		/* outputs 
		{
			success: true,
			returnUrl: 'http://mysite.com/url-from-postLoginRedirect'
		}
		*/
		// We would redirect the user based on where the server told us:
  		window.location.href = response.data.returnUrl; 
	})
	.catch(function (error) {
		// oh noes
	});
```

As far as I can see, `craft\controllers\UsersController::_handleSuccessfulLogin` just gets the url from
` $returnUrl = $userService->getReturnUrl();` and it's `redirectToPostedUrl` that then handles the `redirect` param from the post request. 

Now, I fully appreciate that this might be 'Working as intended' because the *obvious* answer is that since I've got the 'redirect' param in my form, in JavaScript I could just look for that. But I just feel like it seems 'right' to respect what the server told us, because then this somewhat decouples the AJAX handler from the forms themselves, and the ajax is a bit more reusable. 

For some context: we're using AJAX so that we don't have to do full page refreshes if things went wrong (i.e. wrong password) but we are refreshing the page so as to update the page now the user is logged in. And whether the redirect is to the account area or the same page or somewhere else, is quite contextual from where the user tried to log in from (hence different `{{ redirectInput() }}` uses

Thanks!

### Additional info

- Craft version: Craft Pro 3.0.20

**Comment by brandonkelly** [comment]
As you theorized, this is already working as intended.

`returnUrl` is just there to tell you which page the user was trying to access before they got redirected to your login page (e.g. via a [requireLogin](https://docs.craftcms.com/v3/dev/tags/requirelogin.html) tag). It is not necessarily meant to be the place that you should redirect them to. If you already have another place in mind, then you should just disregard `returnUrl` and redirect them where you want them to go.
