### ISSUE TITLE
Asset Entry Modal : PDF Image Size

### ISSUE THREAD

**Issue by magnessjo** [craftcms/cms#3209]
### Description

An asset entry modal appear incorrectly for PDF.    

For images, the modal appears correctly with an image follow by the fields.  

For PDF, the modal appears with a generic PDF image but it sized to be 1000px and scales out of it parent container.  The parent container (image-preview-container) has a set height of 190px so an easy fix is to just set the child to a height of 190px as well.  A white background on the parent with the child element using background-image set to contain would be better to remove an possible responsive issues.  

See attachments.  

![screen shot 2018-08-16 at 3 01 08 pm](https://user-images.githubusercontent.com/856595/44229372-dc06c480-a165-11e8-8a06-a5da2f1005e7.png)
![screen shot 2018-08-16 at 2 44 20 pm](https://user-images.githubusercontent.com/856595/44229381-df01b500-a165-11e8-8953-fe4ef322f43f.png)

### Steps to reproduce

1. Save a PDF file and double click to edit 

### Additional info

- Craft version:  Craft Pro 3.0.20
- PHP version: 7.1.8
- Database driver & version: MySQL 5.5.56
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting!
