### ISSUE TITLE
Improving entry version/reversion UX clarity

### ISSUE THREAD

**Issue by michaeldhopkins** [craftcms/cms#3210]
### Description

Hi, currently, reverting an entry to a previous version can look broken to users when previous versions are very similar. This is because the version still says "Current" and the dropdown gives no indication that "Current" is now #10 instead of the latest, #15. I filed a support request, thinking versioning was somehow broken, before I did some testing and realized what was happening.

Would it be possible to change the dropdown to something like `Current (Version 10)` and to highlight 10 in the dropdown to make it more clear that the currently used version is an older one?  Thanks for considering the issue.

### Steps to reproduce

1. Save an entry a few times.
2. Click the `Current` dropdown and select an older version.
3. In the preview, click `Revert entry to this version`
4. A success message will appear. The dropdown will still say Current. Depending on the entry and its history, the user might not notice any difference between the version they've selected and the previous.

### Additional info

- Craft version: 3.0.19
- PHP version: 7.2
- Database driver & version: MariaDB 10.2
- Plugins & versions: no special authoring plugins

**Comment by brandonkelly** [comment]
When you click “Revert entry to this version”, it will re-save the entry based on the contents of whatever version you had selected. So if you select version `10` and click that, you are creating a new version of the entry, based on version `10`, but as a _new_ version of the entry (number `16` or whatever). So changing the revision dropdown to say `Current (Version 10)` would be misleading.

**Comment by michaeldhopkins** [comment]
Thanks, Brandon. What you are saying makes sense and I agree that the number next to Current would be misleading. I still think it could be made less confusing.

Here is an example I recorded where I save a new entry three times, then revert to #2. http://recordit.co/QfVnP3MOPm

It sounds like you are saying that the reversion should be creating a "Version 4" identical to Version 2. What I see in the UI is that I go from 1/2/Current to 1/2/Current, except Current is now identical to 2 instead of to 3. 3 doesn't actually appear to be available to revert to, even though it still exists in the database. 

What I see in the database is that I still have the same old three versions, though I could see the intention being that the user will make changes and then save version 4 as a modification of 2:
<img width="952" alt="entryversions" src="https://user-images.githubusercontent.com/133994/44235906-d19df800-a170-11e8-877b-cbdfcc2f3db6.png">

What do you think about at least displaying 1/2/3/Current in the dropdown in this scenario after the reversion to make it more obvious there are now four versions, even if a new entry version isn't saved in the DB?

Also, instead of putting a number next to Current, what about some text near the Revert button to make it more explicit that the entry version is going to become a new, current version? I think that would help manage my author's expectations up front without changing anything else.

Again, thanks for considering this.

**Comment by brandonkelly** [comment]
> It sounds like you are saying that the reversion should be creating a "Version 4" identical to Version 2. What I see in the UI is that I go from 1/2/Current to 1/2/Current, except Current is now identical to 2 instead of to 3. 3 doesn't actually appear to be available to revert to, even though it still exists in the database.

Ah that was a bug. Just fixed for the next release. Also, you will find this in the details pane when viewing a revision that was created by reverting a previous version:

<img width="349" alt="screen shot 2018-08-16 at 3 08 09 pm" src="https://user-images.githubusercontent.com/47792/44237683-4b7cb400-a166-11e8-811a-6018b0ab4949.png">

**Comment by michaeldhopkins** [comment]
Sounds good! I think those two things will work well for us.
