### ISSUE TITLE
Craft 2.7.0: Live Preview console - Uncaught (in promise) TypeError

### ISSUE THREAD

**Issue by croxton** [craftcms/cms#3211]
### Description

Uncaught (in promise) TypeError: Cannot read property 'createElement' of null
    at t.createElement (VM408 widgets.js:9)
    at i (VM408 widgets.js:8)
    at VM408 widgets.js:9

### Steps to reproduce

1. Open a Live Preview pane when editing an entry
2. Edit some text - the preview updates as expected but the error appears in the console.

### Additional info

Happens on two sites I upgraded to 2.7.0, tried on a few different servers - same problem.

- Craft version: 2.7.0
- PHP version: 7.1
- Database driver & version: MySQL 5.7.20
- Plugins & versions:

**Comment by brandonkelly** [comment]
I’m not able to reproduce this, and Craft doesn’t even have a `widgets.js` file. Maybe it’s coming from a plugin?

**Comment by croxton** [comment]
Tracked this down for anyone that finds this - it was Twitter's widget script that was throwing the error in Live Preview, in Craft 2.7.0:
`<script type="text/javascript" async src="https://platform.twitter.com/widgets.js"></script>`

If you need it, you can add a conditional to remove it from your template when live preview is active.

```
{% if not craft.request.isLivePreview %}
<script type="text/javascript" async src="https://platform.twitter.com/widgets.js"></script>
{% endif %}
```
