### ISSUE TITLE
Installation Issues - Craft CMS 3

### ISSUE THREAD

**Issue by reachnative** [craftcms/cms#3212]
### Description

I've used Craft CMS 2 for two years and have built my website locally using Craft CMS 3. I was able to successfully setup my local copy of my website via MAMP with no issues. However, when it came to setting up my website on Production through the SSH (Terminal on macOS) and using composer, the setup finally installed, but nothing seems to work properly. I can make adjustment to my templates and the changes aren't being reflected when I deploy it through GIT.

As another test I tried manually changing the template on the server and my changes still aren't being reflected. I've tried clearing the browser cache and Craft's cache and still not seeing anything. In addition, the Production version can't find my templates that I've created for the other pages and will only show the template for my homepage. Any help would be appreciated as I have almost given up on this.

- Craft version: 3.0.20
- PHP version: 7.0.31
- Database driver & version: MySQL 5.5.60
- Plugins & versions: No plugins installed yet.

**Comment by brandonkelly** [comment]
Hey @reachnative, sorry you’re having trouble. I think it’ll be a lot easier for us to debug this if we can get on a screen share with you and run through some tests. If that’s doable, email us at support@craftcms.com and we can set up a time.
