### ISSUE TITLE
Disabled light switch fields can still be toggled

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/cms#3213]
### Description

Small one... disabled light switches can still be toggled.

![ezgif-1-d0f4ab9076](https://user-images.githubusercontent.com/24975058/44255543-584ce680-a1fe-11e8-91b0-740088e2d276.gif)

### Additional info

- Craft version: 3.0.20

**Comment by Anubarak** [comment]
Do you use the macro for it? because this line is LightSwitch.js

```js
// If the input is disabled, go no further
if (this.$input.prop('disabled')) {
    return;
}
```
Should prevent using disabled lightswitch fields
For me it works as expected
```TWIG
{{ forms.lightswitchField({
	label: "Enabled"|t('app'),
	id: 'enabled',
	name: 'enabled',
	on: campaign.enabled
}) }}

{{ forms.lightswitchField({
	label: "Mail send"|t('app'),
	disabled: true,
	name: 'mailSend',
	on: campaign.mailSend
}) }}
```

tested with Craft Pro 3.0.20

**Comment by lukeyouell** [comment]
This is the field displayed in the above gif:

```
{{ forms.lightswitchField({
    first: true,
    label: 'Format Check',
    instructions: 'Perform a standard email format check, verifying it\'s basic compliance.',
    on: true,
    disabled: true
}) }}
```

**Comment by Anubarak** [comment]
Bad father.... you should always name your childs :-P
They won't obey when you don't give them names
```twig
{{ forms.lightswitchField({
    first: true,
    label: 'Format Check',
    instructions: 'Perform a standard email format check, verifying it\'s basic compliance.',
    on: true,
    disabled: true,
    name: 'fromNowOnIWillAlwaysNameThem'
}) }}
```

**Comment by brandonkelly** [comment]
Yeah.

**Comment by lukeyouell** [comment]
Fair enough!

I didn't give it a name as it doesn't serve any purpose other than as a visual placeholder.
