### ISSUE TITLE
@web versus siteUrl

### ISSUE THREAD

**Issue by joshuabaker** [craftcms/cms#3215]
The `@web` alias in `resourceBaseUrl` is not resolving to the `siteUrl`, which is what I would have expected. Is this by design?

**Comment by brandonkelly** [comment]
Per the [docs](https://docs.craftcms.com/v3/config/#aliases), `@web` is

> The URL to the folder that contains the `index.php` file that was loaded for the request

Usually that ends up being the same as the site’s Base URL (in fact often times `@web` is used as the site’s Base URL), but it’s not necessarily going to be the same.
