### ISSUE TITLE
Redirect to Settings after saving a plugin’s settings

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#3216]
It would be nicer if you get redirected to Settings instead of Settings > Plugins. The plugins section on the main Settings page makes it much simpler to find the link.

### Steps to reproduce

1. On a plugin’s settings page click save
2. See how you’ve been redirected to Settings > Plugins
3. If you now want to make more changes to the plugin’s settings, it is hard to find the link again, in the list of all plugins.

**Comment by brandonkelly** [comment]
Good idea – done.

**Comment by narration-sd** [comment]
@carlcs  You likely know it, but for others this little thing can be very handy when you want to keep your Settings in view after saving  -- as with a table of items, etc..

   ` {{ redirectInput('settings/plugins/your-plugin-handle') }}`

**Comment by carlcs** [comment]
Hm this brings me to another idea, what if plugin settings had support for the cmd + s shortcut.
There's probably some other open issue with a request for cmd + s support on all pages where I can save some thing, somewhere.

**Comment by brandonkelly** [comment]
Pretty sure they already do, as long as they’re not overriding the settings form.

**Comment by narration-sd** [comment]
yes, works for me

**Comment by carlcs** [comment]
Sorry, I wasn’t in front of a Craft CP when I replied. What I actually had in mind was that cmd + s would always keep you on the current page, the “Save and continue editing” behavior of edit element pages.

Click Save button →  redirect
Keyboard shortcut → stay on current page …for any page in the CP with a Save button

I found a related issue now https://github.com/craftcms/cms/issues/2872
