### ISSUE TITLE
Overriding volume settings is very cumbersome

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#3219]
If you're configuring AWS or something with API secrets and you want it kept out of the DB (as it is stored unencypted), [overriding volume settings](https://docs.craftcms.com/v3/config/#overriding-volume-settings) is your only option.

However, it is very cumbersome to do so.

## Example:

 - Start by creating a `test` Amazon S3 volume, putting your creds in the CP because that's the only way you can save the volume.
- you can now overriding your `test` creds in `config/volume.php`, getting them from env, or wherever.
- you'll need to repeat this, matching the handle for each volume.
- At this point the creds are overridden, but still in the DB – so to get them out you'd have to hop into the DB and delete the JSON values in `volumes.settings`. However, if that volume ever gets saved again, they're back in the DB :(

## Solutions?

This is something that  in Craft 2, this might have been been solved with "environment variables". You could do everything in the CP, but reference the variables instead. Aliases work for this for path-based things, but their application seemed to be limited to paths/urls…

If creating Volumes in the CP is a  requirement, it seems like there should be a manageable way to reference dynamic values for this purpose.

These examples are specifically for volumes, but the same is true for other components with credentials (e.g. email).

**Comment by brandonkelly** [comment]
Yep. I think we should add a way to access environment variables in these settings (in addition to aliases where those still make sense).

For example, Symfony sets `env(VAR_NAME)` variables when parsing its configuration files (https://symfony.com/doc/current/configuration/external_parameters.html#environment-variables).

```yaml
doctrine:
    dbal:
        url: '%env(DATABASE_URL)%'
    # ...
```

**Comment by brandonkelly** [comment]
Think it should be `env:X` rather than `env(X)` though.

**Comment by timkelty** [comment]
That'd be great!

**Comment by dougstjohn** [comment]
I like the idea of using an env value. Another UI solution would be a 'Save as a new volume' like there is for entries, etc.

**Comment by brandonkelly** [comment]
This is implemented for Craft 3.1! (237d6969e02295ef2b14fe53bf5f20afae6cd5fb)

Ended up just going with `$VARIABLE_NAME`, rather than `env:VARIABLE_NAME`, etc., as it’s more concise and consistent with `@aliasName` (and `$VARIABLE_NAME` is how you reference environment variables in the terminal).

Currently supported by:

- Sites:
  - Base URL
- Volumes
  - Base URL
  - File System Path
- Email settings
  - System Email Address
  - Sender Name
  - HTML Email Template
  - Username (Gmail, SMTP)
  - Password (Gmail, SMTP)
  - Host Name (SMTP)

**Comment by timkelty** [comment]
@brandonkelly – So, for this to be useful for non-core Volume types (e.g. AWS S3) – would this have to be supported specifically supported by each Volume type, or could/should this be dynamically applied to all volume settings?

**Comment by brandonkelly** [comment]
We’ll need to update the S3 plugin to add support for it.

**Comment by timkelty** [comment]
> We’ll need to update the S3 plugin to add support for it.

👍 Made an issue: https://github.com/craftcms/aws-s3/issues/35
