### ISSUE TITLE
Root relative site URLs no longer work

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#3221]
I think this was introduced here: https://github.com/craftcms/cms/commit/c17487b4ce921e1697edfb2e121ae2187d390405#diff-8761a7cd35e729b6fadc9ebfa1200391

`craft\helpers\UrlHelper::url` will now always return a full url, even if your `siteUrl` is explicitly root relative (e.g. `/`)

**Comment by brandonkelly** [comment]
I don’t think it was that commit, or the exact issue off the top of my head, but the change was intentional.

**Comment by timkelty** [comment]
Looking at the changelog, I'm guessing it was this:

> Generated site URLs now always include full host info, even if the base site URL is root/protocol-relative.

So root/protocol relative values are ok in the `siteUrl` setting, but any generated URLs will have full path info. That seems a bit confusing to me.

My use-case for wanting a root-relative siteUrl is using Craft as a detached API, where having full URLs sometimes doesn't make sense. Obviously there are times where you do need  a full URL though (URLs in email).

It almost seems like maybe there could be a third template rendering mode (CP, site, email/external) to manage things like this.

**Comment by brandonkelly** [comment]
Right, that's the one. Committed in 4848022f425819d1f2e10c476d2142ea111542ab, which fixed #2919.

It’s pretty easy to turn an absolute URL into a root-relative URL using [parse_url()](http://php.net/manual/en/function.parse-url.php), so maybe you could just use that when you need it?

```php
$url = parse_url($url, PHP_URL_PATH);
```

**Comment by timkelty** [comment]
> so maybe you could just use that when you need it?

In my case that's not really a possibility (I don't think), as this is an API (CraftQL), not Twig – so I'd have to know any field/fieldtype that might use `craft\helpers\UrlHelper::url` and tap into it somehow.

If `craft\helpers\UrlHelper::url` had an event hook, that would be one way.

At this point, I'm all set: I'm just making the dev consuming my API parse the URI out. :)
