### ISSUE TITLE
HUD modal only showing single source and not pre-selecting on first trigger

### ISSUE THREAD

**Issue by davist11** [craftcms/cms#3227]
### Description
We have an Entries field that is related to multiple sections (across multiple sites), and also managed on a per site basis. When I click to add an entry the first time, I see the following:

<img width="873" alt="screen shot 2018-08-22 at 9 49 45 am" src="https://user-images.githubusercontent.com/199985/44467374-bc055400-a5f0-11e8-8320-1c50af6d6592.png">

The left sidebar seems unnecessary, and the section isn't pre-selected. If I click the section in the left sidebar, leave that entry, and then come back to it later in the session, clicking add entry now pre-selects the section:

<img width="872" alt="screen shot 2018-08-22 at 9 47 58 am" src="https://user-images.githubusercontent.com/199985/44467281-78aae580-a5f0-11e8-94ef-dab2a85a1966.png">

### Steps to reproduce

1. Create 2 different sites
1. Create 1 section in each of those sites
1. Create an entries field and select the 2 sections created
1. Make the field managed on a per site basis
1. Visit an entry with the field on it and click add an entry

### Additional info

- Craft version: Craft Pro 3.0.19
- PHP version: 7.0.30
- Database driver & version: MySQL 5.7.23
- Plugins & versions:

<table class="data fullwidth fixed-layout">
        <tbody>
                            <tr>
                    <th class="light">Algolia</th>
                    <td>1.0.1</td>
                </tr>
                            <tr>
                    <th class="light">Amazon S3</th>
                    <td>1.0.8</td>
                </tr>
                            <tr>
                    <th class="light">Asset Rev</th>
                    <td>6.0.1</td>
                </tr>
                            <tr>
                    <th class="light">AsyncQueue</th>
                    <td>1.3.3</td>
                </tr>
                            <tr>
                    <th class="light">Audit</th>
                    <td>2.0.1</td>
                </tr>
                            <tr>
                    <th class="light">Automatic Site Switch</th>
                    <td>1.0.1</td>
                </tr>
                            <tr>
                    <th class="light">Calendar</th>
                    <td>2.0.5</td>
                </tr>
                            <tr>
                    <th class="light">Category Utilities</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Certificates</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Converge</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Craft Commerce</th>
                    <td>dev-develop</td>
                </tr>
                            <tr>
                    <th class="light">Enupal Snapshot</th>
                    <td>1.0.4</td>
                </tr>
                            <tr>
                    <th class="light">Environment Label</th>
                    <td>3.1.4</td>
                </tr>
                            <tr>
                    <th class="light">Feed Me</th>
                    <td>3.0.0-beta.17</td>
                </tr>
                            <tr>
                    <th class="light">Field Manager</th>
                    <td>2.0.2</td>
                </tr>
                            <tr>
                    <th class="light">Flat Categories</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Forms</th>
                    <td>2.2.2</td>
                </tr>
                            <tr>
                    <th class="light">Freeform Pro</th>
                    <td>2.2.2</td>
                </tr>
                            <tr>
                    <th class="light">Geo Cookie</th>
                    <td>1.2.1</td>
                </tr>
                            <tr>
                    <th class="light">Hamilton Utility</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Importer</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Inlin</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Inventory</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">OrderExporter</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Redactor</th>
                    <td>2.1.5</td>
                </tr>
                            <tr>
                    <th class="light">Sidebar Toggle</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th class="light">SimpleSentry</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Super Table</th>
                    <td>2.0.7</td>
                </tr>
                            <tr>
                    <th class="light">Taxes</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Twig Perversion</th>
                    <td>2.0.4</td>
                </tr>
                    </tbody>
    </table>

**Comment by brandonkelly** [comment]
Are the sections that aren’t visible enabled for the current site?

**Comment by davist11** [comment]
No, they are only enabled in their individual sites. For example, we have 5 sites:

1. Automated Liquid Handling
1. Automated Sample Management
1. Laboratory
1. Process Analytics
1. OEM

And 5 sections:

1. Automated Liquid Handling Case Studies
1. Automated Sample Management Case Studies
1. Laboratory Case Studies
1. Process Analytics Case Studies
1. OEM Case Studies

Those sections are only enabled in their respective sites.

And then, we have a Case Studies (entries) field with the following settings:

* Managed on a per site basis
* Sources:
  1. Automated Liquid Handling Case Studies
  1. Automated Sample Management Case Studies
  1. Laboratory Case Studies
  1. Process Analytics Case Studies
  1. OEM Case Studies

**Comment by brandonkelly** [comment]
Hm, ok. In that case it seems like it is mostly behaving as expected.

- The sidebar is visible because the field is configured with multiple sources.
- The sidebar only shows one section because the other 4 get filtered out due to not being relevant for the current site.

I don’t think that just because only a single source ends up being visible, that the field should actually remove the sidebar (like it would on a field that is only configured for a single source) – because Craft doesn’t know that the author is expecting a single source. For all it knows, the field’s name & instruction text are written assuming that multiple sources would be visible, and it won’t be clear which source is selected if the sidebar isn’t shown.

So the only awkward thing here is that the one source doesn’t get selected automatically.

**Comment by davist11** [comment]
👍  that makes sense. If the single source could be pre-selected, I think it would help reduce the confusion that we've seen some clients have.
