### ISSUE TITLE
Disable editing user field layout on Solo license

### ISSUE THREAD

**Issue by mollyce** [craftcms/cms#3228]
With solo license admin can add additional fields to user object, but cannot edit them. This is inconsistent.

I propose either removing ability to add fields to user on solo license, or give ability to edit them on this license.

**Comment by brandonkelly** [comment]
What do you mean they cannot edit the fields? All fields are editable in Settings > Fields.

**Comment by mollyce** [comment]
@brandonkelly Its not that i cannot edit fields, i cannot edit fields values with solo license. With solo license, tab with additional user fields doesnt appear in user profile. But i can still set these fields up using settings. So, setting them up does nothing in this scenario.

**Comment by brandonkelly** [comment]
Ahh, gotcha. Yep that’s a bit awkward. I just removed the Craft Pro checks for that page, so custom fields will be visible in the next release.
