### ISSUE TITLE
Feature: Entries search: Keep controls sticky at top

### ISSUE THREAD

**Issue by jkorff** [craftcms/cms#3233]
### Description
When I'm searching entries and scrolling through the list the upper controls and search box should remain sticky at the top so they’re always available no matter where I am in the list.

### Steps to reproduce

1. Craft > Entries
2. Scroll down the listing => the controls disappear.

### Additional info

- Craft version: 3.0.12
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
That was supposed to already be the case, but looks like there was a bug. Just fixed for the next release.

**Comment by jkorff** [comment]
Great, thank you.
