### ISSUE TITLE
Asset Field does not show correct images when a dynamic path is being used in the settings, until an entry is saved

### ISSUE THREAD

**Issue by BenParizek** [craftcms/cms#3237]
### Description

It appears that a custom asset folder path does not get rendered until an Entry is saved for the first time. This makes some workflows fairly inconvenient as a user would not see that any files exist in a folder until they first save the Entry they are working from for the first time.

### Steps to reproduce

1. Create an Assets Field
2. Define your folder path using another relation field in your field layout: `somewhere/{{ owner.relationField.one().slug }}`
3. Add a few images in the target folder
4. Create a new Entry that includes the Asset Field and the target Relation field (In our case, the Asset Field as also within a Matrix Block)
5. Select the value for your Relations field 
6. Attempt to select an asset from your Asset Fields custom folder path
7 If the Entry has not yet been saved, the Asset modal will only display assets in the Temporary Uploads directory. After you save the Entry, re-triggering the Asset modal will then display the assets in your target field

### Additional info

- Craft version: 3.0.21
- PHP version: 7.1
- Database driver & version: MySQL
- Plugins & versions: Several

**Comment by brandonkelly** [comment]
If Craft is able to parse the subfolder path template without any errors, it will store the assets there right away.

But in your case, Craft isn’t able to resolve `{{ owner.relationField.one().slug }}` until the entry exists. (It’s not possible for Craft to query the relations defined by `owner.relationField` until the entry has an ID.) So it has to place them in a temporary location until the entry has been saved. It may be inconvenient, but there is no other way.

**Comment by BenParizek** [comment]
While I don't think it is a high priority, it may be nice to consider displaying a message that indicates the behavior in the UI requires the entry to be saved before things will display as expected. I'm not sure how to word that, but I feel it would be nice, as a user, to know that Craft is aware that it can't resolve the path and that there may be other images that will display after the item is saved. 

When the Asset Modal is displayed, and limited to a single upload folder, there is no context for the user to recognize except that files appear or don't appear in the initial modal. Having a small message somewhere saying something like: "you may need to save your element before you can select from all existing images in this folder" could be a small indicator that the UI is aware that the user may not be interacting with what they expect.

Both myself and another regular Craft developer struggled with explaining what behavior we were seeing for a half hour or so. We had to run several upload tests while double checking the Asset field settings to explore our theories before we made sense of what was happening.
