### ISSUE TITLE
Logging in user by id (loginByUserId) throws exception, establishes user session

### ISSUE THREAD

**Issue by cscomfort** [craftcms/cms#3239]
### Description
In the process of updating plugins for our upgrade to Craft 3, I'm unable to establish user sessions for a password-protected section of the site: `loginByUserId` throws *HTTP 400 – Bad Request – yii\web\BadRequestHttpException: Unable to verify your data submission*.

After the login process fails, however, a user session is indeed established–this confirmed by successfully navigating to the password-protected without receiving another login request.

### Notes
- The password-protected URL is /dashboard; we are using a custom `cpTrigger`.

- We can log in to the control panel without issue.

- I have tried disabling `enableCsrfProtection` in config/general.php, clearing Craft cache from the control panel, and then re-enabling `enableCsrfProtection` to no avail.

- Early on during our upgrade to Craft 3, we ran into some environment-specific issues that requires us to set custom headers in .htaccess (though, again, we can log in to the control panel without issue; alternatively, removing the config from .htaccess produced the same result):
```
SetEnvIf X-Requested-With "XMLHttpRequest" JSONREQ
RequestHeader set Accept "application/xhtml+xml,application/xml,application/json,text/javascript; charset=UTF-8" env=JSONREQ
```

#### Login form
```php
<form method="post" accept-charset="UTF-8">
      {{ csrfInput() }}
      <input type="hidden" name="action" value="plugin_name/user/login">

      <fieldset>
        <input id="loginUsername" class="c-login__input" id="username" type="text" name="username" value="{{ craft.app.user.rememberedUsername }}" placeholder="Enter Your UT EID" data-type="input">

        <label for="loginPassword" class="u-hide-visually">Password:</label>
        <input id="loginPassword" class="c-login__input" id="password" type="password" name="password" placeholder="Password" data-type="input">
      </fieldset>

      <button id="loginSubmit" class="c-login__submit" type="submit">Log In</button>
</form>
```

#### UserController.php
*Note that we are handling actual authentication externally. Controller is simplified here for troubleshooting purposes, tested as-is below with the same failing result.* 
```php
use Craft;
use craft\web\Controller;
use craft\web\User;

class UserController extends Controller
{

    // Protected Properties
    // =========================================================================

    /**
     * @var    bool|array Allows anonymous access to this controller's actions.
     *         The actions must be in 'kebab-case'
     * @access protected
     */
    protected $allowAnonymous = ['login'];

    // Public Methods
    // =========================================================================

    public function actionLogin()
    {
        // Only allow POST requests.
        $this->requirePostRequest();

        // Retrieve username and password from POST.
        $username = Craft::$app->request->post('username');

        // Retrieve user.
        $user = (new Query())
            ->select('id')
            ->from('craft_users')
            ->where(['username' => $username])
            ->one();
        
        // Log in user by id.
        Craft::$app->user->loginByUserId($user['id']);
    }
}
```

### Additional info

- Craft version: 3.0.19
- PHP version: 7.0.27

**Comment by brandonkelly** [comment]
If the user is getting logged in, then it sounds like `loginByUserId()` is working as expected. I’m guessing the 400 error is getting thrown somewhere else.

Check your logs for the 400 error (`storage/logs/web.log`) to get the stack trace that shows where it’s getting thrown. Or enable Dev Mode in `config/general.php`, so you can see the full stack trace in your browser right when it occurs.

```php
return [
    'devMode' => true,
    // ...
];
```
