### ISSUE TITLE
Plugin Store Craft ID callback fails

### ISSUE THREAD

**Issue by jerome2710** [craftcms/cms#3241]
### Description

After logging with your Craft ID and returning to the website Craft CP, the callback fails:

```
Status: Internal Server Error

Response: {"error":"Argument 1 passed to craft\\helpers\\DateTimeHelper::secondsToInterval() must be of the type integer, null given, called in /_{truncated}_/vendor/craftcms/cms/src/services/PluginStore.php on line 109"}
```

### Steps to reproduce

1. Go to the Craft CP Plugin Store
2. Login with your Craft ID and confirm to return to your website

### Additional info

- Craft version: 3.0.21
- PHP version: 7.1.18
- Database driver & version: MySQL 5.5.56
- Plugins & versions: _various_

**Comment by benjamindavid** [comment]
@jerome2710 Hey, sorry about that, could you please send the URL the process fails on, as well as your browser/os details? Thanks!

**Comment by jerome2710** [comment]
@benjamindavid, thanks for the quick reply! The URL within the control panel is `/admin/plugin-store/callback/`, which executes an XHR to `/index.php?p=admin/actions/plugin-store/save-token`. This throws an exception as mentions above, with the following stack trace:

```
#0 /home/.../domains/.../releases/2/vendor/craftcms/cms/src/services/PluginStore.php(109): craft\helpers\DateTimeHelper::secondsToInterval(NULL)
#1 /home/.../domains/.../releases/2/vendor/craftcms/cms/src/controllers/PluginStoreController.php(199): craft\services\PluginStore->saveToken(Array)
#2 [internal function]: craft\controllers\PluginStoreController->actionSaveToken()
```

Please let me know if you need anything else.

**Comment by benjamindavid** [comment]
@jerome2710 Thanks for the extra details! Do you confirm that you don't have any hash at the end of the callback URL like this: `/admin/plugin-store/callback#access_token=eyJ0eXAiOi…`?

Also, which browser/os are you using?

**Comment by jerome2710** [comment]
@benjamindavid Correct, no contents after `/callback` in the url.

The problem occurs with all our developers, using macOS High Sierra (10.13.6) and Safari 11.1.2. I now see it does work, with a hash in the URL, when using Google Chrome (68.0.3440.106).

**Comment by jerome2710** [comment]
Many thanks to @benjamindavid, who helped looking into this matter with communications through Slack. He tracked down the problem as being a Safari 'bug', whereas Safari strips the hash when there is a training slash before the hash. Some background can be found here: https://community.auth0.com/t/hash-gets-lost-on-safari-webkit-browsers/7263/6.

We were rewriting all URLs to make them prettier with a trailing slash, but it would be better to leave the control panel routes alone anyway. We now exclude these rules in the htaccess and this resolves the issue for Safari!
