### ISSUE TITLE
Vulnerability in zendframework/zend-feed 2.8.0

### ISSUE THREAD

**Issue by losbeekos** [craftcms/cms#3242]
### Description

We have a security checker in our Craft sites and we discovered the following vulnerability in zendframework/zend-feed 2.8.0. It should be resolved with version 2.10.3, see: https://framework.zend.com/security/advisory/ZF2018-01.

Symfony Security Check Report
--
  | =============================
  |  
  | // Checked file: /app/user/composer.lock
  |  
  |  
  | [ERROR] 1 packages have known vulnerabilities.
  |  
  |  
  | zendframework/zend-feed (2.8.0)
  | -------------------------------
  |  
  | * (no CVE ID): URL Rewrite vulnerability
  | https://framework.zend.com/security/advisory/ZF2018-01
  |  
  | ! [NOTE] This checker can only detect vulnerabilities that are referenced in
  | !        the SensioLabs security advisories database. Execute this command
  | !        regularly to check the newly discovered vulnerabilities.

### Steps to reproduce

1. Use the latest stable Craft version
2. Run Sensiolabs Security checker
3. Watch it fail

### Additional info

- Craft version: 3.0.12
- PHP version: 7.2
- Database driver & version: MySQL
- Plugins & versions: -

**Comment by brandonkelly** [comment]
Craft 3.0.13 loosened up Craft’s composer restrainsts so that things like zend-feed could update freely up until the next major version (commit: f607d7314a8f7b6050859c3e7c362a86bcbe7709).

So if you update Craft, zend-feed will get updated to v2.10.3 as well.
