### ISSUE TITLE
allowAutoUpdates deprecation error from services/Config.php

### ISSUE THREAD

**Issue by olets** [craftcms/cms#3244]
### Description

I'm getting the following deprecation error, which appears to be coming from Craft itself. This has persisted after a fresh `rm -rf vendor && composer install`

```
The allowAutoUpdates config setting has been renamed to allowUpdates.

<my path>/craft/vendor/craftcms/cms/src/services/Config.php:109
```

### Steps to reproduce

1. Load site
2. Go to /admin/utilities/deprecation-errors

### Additional info

- Craft version: 3.0.22
- PHP version: 7.1.12

**Comment by brandonkelly** [comment]
That’s just a bug in the deprecation log. The real origin is going to be your `config/general.php` file.

**Comment by angrybrad** [comment]
@olets it was fixed in https://github.com/craftcms/cms/commit/1785197827f8ef39d6b8b1e33dd974a5ae317e2f
