### ISSUE TITLE
FR Better delineation between "sites" and "languages" 

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#3250]
We discussed (and got) the addition of Site Groups: https://github.com/craftcms/cms/issues/1668 but I think we still need a better delineation between sites and localizations of said sites.

While Craft's current implementation is flexible, it's also a bit confusing, and the lack of structure makes it difficult for plugins like SEOmatic to understand the relationship between sites (which is what the original issue was about).

From an SEO POV, we need to tell search engines what is really just another localization/translation of the same thing. This applies to tags added to the page, as well as to the sitemap. While you _can_ set it up this way:

```
├── Primary Site Group
│   ├── English Site
│   ├── Chinese Site
|   └── German Site
├── Sister Site Group
│   ├── English Site
|   └── German Site
```

...the [Sites documentation](https://docs.craftcms.com/v3/sites.html) says that you can group sites together by anything that makes sense to you. Thus there is no enforced structure defining that this is a Site, and these are localizations of said site.

So people can (and do) set up sites where Site Groups are used to organize things by language, which brings us back to the same problem that was listed in https://github.com/craftcms/cms/issues/1668 which is:

> A real conundrum I’m having is how to handle sitemaps for “multi-site”. Sitemaps have built-in support for different URLs for the same content, but in different languages. Since there’s no hierarchy for “sites”, I have no way of knowing what the association between the sites is.
> 
> So let’s say we have a corporate website that’s localized in 3 languages. That’s 3 “sites”. Then they also have 2 more “sister sites” for product brands, that are also localized in 3 languages.
> 
> We now have 9 distinct sites, but nothing expressing the relationship between any of them, so there’s no way to know which of these “sites” are localizations of the same “site”, and which are logically separate “sister sites”
> 
> So then I’d need to add some kind of “site grouping” UI that allows users can express the relationship between the sites, but that really feels like something that Craft should be doing
> 
> I think content authors in the AdminCP will have similar confusion, because of the lack of logical grouping of "things that are related" (in this case, Sites)

Instead of a sibling relationship between all Sites, and the Site Groups just being an arbitrary way to lump them together however you want, I think there should be a parent/child relationship defined between sites, and localization/translation of said sites.

I've added [Documentation to SEOmatic](https://github.com/nystudio107/craft-seomatic#multi-site-languagelocale-support) describing how it expects it to work, but I think this needs to be formalized in some way.

**Comment by khalwat** [comment]
Background: I had someone come to me who organized their Site Groups _by language_, lumping all of the English sites together, German sites together, etc.:

```
├── English Site Group
│   ├── US English Site
│   ├── NZ English Site
|   └── GB English Site
├── German Site Group
│   ├── DE German Site
|   └── AT German Site
```

In this instance, there's no way for SEOmatic to know that these are all really the same site, they've just decided to use Site Groups to group things by language.

**Comment by khalwat** [comment]
For now, I've Implemented via https://github.com/nystudio107/craft-seomatic/commit/89a5d50bdad0102b5a8ea769d19ba93a719ebedf

![google chromescreensnapz1336](https://user-images.githubusercontent.com/7570798/44809605-2db74200-ab9d-11e8-8654-f2499d763af1.png)

> Turn this setting OFF if you're not using Site Groups to organize things by separate logical sites

...but it feels a little... icky.

**Comment by Rias500** [comment]
To offer a counter opinion, I don't think making Craft more structured in this would benifit developers or clients. It takes away quite a bit of flexibility on how you can organise the CMS's structure around the structure of the business.

A better idea might be relying on a plugin or custom functionality in SEOmatic's plugin to relate sites to eachother and base the SEO tags on that relation.

**Comment by khalwat** [comment]
@Rias500 I understand the flexibility part, and by no means am I expecting P&T to write my plugin for me. However, what this means is that every plugin author who wants to do something like this will need to write their own UI for defining what is a site, and what is related to what.

The original issue https://github.com/craftcms/cms/issues/1668 that spurred the creation of Site Groups to begin with was meant to address this.

I think Sites in general are a bit confusing to most people when approaching them.

**Comment by narration-sd** [comment]
@khalwat  This caught my eye, from experiences, and those leads to  support @Rias500 's view. 

Cultures have quite different needs from technical singularity of organisation, often enough,, and your example of the multiple English and German variants is actually a very good illustration of this -- it's a pattern that needs to be allowed to happen..

Appreciating as well your SEO concern, it occurs that while the Site Groups you contributed to give a good handle on organising the cultural presentation, it would be just as good an idea for a service like SEOMatic to be providing its own organizing tree. Then the SEO view needs can be clearly raised and separately answered.

Are Sites confusing? Sure. Any human categorizing system tends to be (cf. Lakoff - Women, Fire, and Dangerous  Things). That's a great title for sure, and  the explanation at the beginning of the first chapter, via Kindle free preview, places the reality that we humans surely can categorize things in many differing ways. 

Anyway, I liked it ;) , and the memories of working various things out overseas do support multiple views deserving their own answers...

**Comment by narration-sd** [comment]
...an intriguing and  welcome solution to another 'category' problem, just turned up on news:

https://www.scmp.com/news/china/diplomacy-defence/article/2161888/taiwan-grateful-united-airlines-imaginative-website

**Comment by brandonkelly** [comment]
@khalwat It’s easy enough to change up how sites are organized, so I think you should just make it clear in SeoMatic’s documentation how they _should_ be using Site Groups in order for SeoMatic to do its job properly.

**Comment by khalwat** [comment]
Yep, that's what I did @brandonkelly https://github.com/nystudio107/craft-seomatic#multi-site-languagelocale-support

The issue in this case is that he was using the sites organized by language, and then taking advantage of the Site translation method. So actually re-organizing things would have been a good bit of work.

**Comment by brandonkelly** [comment]
@khalwat the Site translation method doesn’t take site groups into account.
