### ISSUE TITLE
Bug with Date/Time fields when changing timezones? 

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [craftcms/cms#3251]
So I recently updated the timezone in the `General Settings` and it looks like it updated all the time fields (field type is a `Date/Time`) for each event entry. Is this expected behavior? Not sure if it was intended to change all inputed times hence why I'm logging it here 

### Additional info

- Craft version: latest
- PHP version: 7.2
- Database driver & version: mysql 5.7

Feel free to close this if it's intended behavior but I'm not so sure it should be.

Thanks everyone!

**Comment by brandonkelly** [comment]
Yes, because Date/Time fields (and any other dates/times in Craft) respect the system time zone. So if you set your time to 9:00 AM in UTC, and then you change your time zone to UTC-8, the "new" time will be 1:00 AM in UTC-8 – which is the exact same point of time as 9:00 AM in UTC.

**Comment by DynamiteGoesBoom** [comment]
Gotcha thanks for the clarification.
