### ISSUE TITLE
Suggestion for updating plugin which is not installed in our project

### ISSUE THREAD

**Issue by nweevers** [craftcms/cms#3253]
### Description
We have our own plugin, which is called 'Tools'. Craft suggest to update it, but it is already at the latest version. I think that this is, because of an other plugin which has the same name in the Plugin Store.

<img width="532" alt="screen shot 2018-08-30 at 11 23 02" src="https://user-images.githubusercontent.com/1636038/44842961-74fa0d00-ac47-11e8-9879-02c4e34a07f3.png">

Maybe a check for complete name will help. So `amimpact/tools` instead of `tools`

**Comment by brandonkelly** [comment]
This is pretty much the same root issue as #3054 - see the discussion there for the reasoning behind this behavior.
