### ISSUE TITLE
[Feature Request] Add link to Entry Types page on Section edit page in CP?

### ISSUE THREAD

**Issue by swthate** [craftcms/cms#3255]
Has this been brought up before? Am I completely missing something that already exists? I don't know...

In any case! I always grumble at myself when I go to Settings -> Sections in the CP and find that I clicked on the section title and was brought to the edit screen for that section, when in fact I was wanting to visit the entry types edit screen for that section. Can the entry types screen exist as a tab within the main edit screen for the section? **Just like Settings -> Globals has a Settings and Field Layout tab.**

🙏🙏🙏

**Comment by brandonkelly** [comment]
I suppose it could as long as it’s only shown once the section has been saved.

**Comment by KatieMFritz** [comment]
I do this at least 60% of the time too, @swthate.

**Comment by brandonkelly** [comment]
This was resolved in 3.6.10 – see #6826. (Sorry, I forgot this had already been requested at the time. I should have marked that one as a duplicate of this one.)
