### ISSUE TITLE
Devmode banner element doesn't show up on some browsers (DPI scaling)

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/cms#3259]
### Description

The devmode SVG patterned banner does not show up on some browsers. Weirdly, its appearing in Google Chrome on Mac, but with Google Chrome on Windows it doesn't show and in other browsers as well.

Not quite sure why, initially I thought about adding the `position` property, but this will cause uneven spacing, instead adding `min-height` seems to work.

### Additional info

- Craft version: 2.7.2

**Comment by brandonkelly** [comment]
Working on my end:

<img width="333" alt="screen shot 2018-09-03 at 8 01 26 am" src="https://user-images.githubusercontent.com/47792/44993487-a0367200-af4f-11e8-905b-82622fdd22ef.png">

Do you have any plugins installed that could be messing with the CSS?

**Comment by jamesmacwhite** [comment]
@brandonkelly We do and I initially thought this was the case, however inspecting the element in Chrome I cannot see any overrides/other rules from anything else and the fact because it works on equivalent browsers on Mac, I figured it can't be, otherwise it would be consistent. I'll double check, but its bizarre.

**Comment by brandonkelly** [comment]
@jamesmacwhite Glad you figured out the culprit! Happy to include the change if it’s not hurting anything.

**Comment by jamesmacwhite** [comment]
@brandonkelly Thanks! Will this be back ported to Craft 2 at some point? If not don't worry, I will implement this fix in my plugin that loads additional CSS in the CP.

**Comment by brandonkelly** [comment]
Gah, sorry, I forgot this is for Craft 2. Will add there as well.
