### ISSUE TITLE
CategoryField - set siteId in normalizeValue

### ISSUE THREAD

**Issue by Naffto** [craftcms/cms#3261]
### Description
Hey,
this is a "bug" which only occurs if you modify categories, so that they aren't propagated through all sites.
There is a problem in the fields/Categories.php -> normalizeValue method. 
```php
/** @var Category[] $categories */
$categories = Category::find()
    ->id($value)
    ->anyStatus()
    ->all();
```

You don't set a siteId for the CategoryQuery, so it always defaults to the currentSite, which is a problem if the category isn't propagated for the current site. 
Other relation fields like Entries are working fine with this setup.

Simple fix would be either the logic from fields/Matrix.php
```php
->siteId($element->siteId ?? null)
```
or from the BaseRelationField
```php
->siteId($this->targetSiteId($element))
```

### Steps to reproduce

1. Setup categories, so they don't propagate through all sites (custom behavior)
2. Log in the CP with a domain from Site A
3. create a category for Site B
4. Edit an Entry in Site B and try to set a category relation
5. Save it (the relation won't save, since the category doesn't exist in Site A)

### Additional info

- Craft version: 3.0.22
- PHP version: 7.0.7
- Database driver & version: MySQL 10.1.14 (MariaDB)

**Comment by brandonkelly** [comment]
> which only occurs if you modify categories, so that they aren't propagated through all sites.

How exactly are you doing that?

**Comment by Naffto** [comment]
Well, as an example:
I'm overwriting your elements service in our App.php with my own.
My own one extends your's and in the saveElement method i will stop the propagation of categories.

This is just a basic example and not the whole solution, since this example will have some side effects.

It would be nice if you can implement the above fix, since it wouldn't mess with anything existing and it would be consistent with the BaseRelation field.

Sorry for errors, i'm on my mobile phone.

**Comment by brandonkelly** [comment]
Explicitly querying relatied elements from the same site as the source element would be a change in behavior, so not something I feel comfortable doing in a build release, but we can do it for 3.1.

**Comment by brandonkelly** [comment]
Done.
