### ISSUE TITLE
Image transform via image editor not showing up in live preview

### ISSUE THREAD

**Issue by janhendrickx** [craftcms/cms#3265]
### Description
If you edit an image with the image editor in Craft, it isn't rendered in the live preview; It needs to be saved first (and of course the page needs to be refreshed) before you get to see it.
It would be handy if the edited version is shown in the live preview - if possible.

### Steps to reproduce

1. Choose an image in an entry
2. Open live preview
3. Edit the image
4. Live preview shows the unedited version 

### Additional info

- Craft version: 3.0.22
- PHP version: -
- Database driver & version: -
- Plugins & versions: -

**Comment by brandonkelly** [comment]
Hey Jan, we just released Craft 3.0.23 which includes a fix for this.
