### ISSUE TITLE
Deprecation error when trying to iterate eager loaded array without .all()

### ISSUE THREAD

**Issue by howells** [craftcms/cms#3266]
### Description

When looping through an eager loaded collection of objects, a deprecation error is shown for not using `.all()`. However, when `.all()` is added to the array, the error `Impossible to invoke a method ("all") on an array.` is shown.

### Steps to reproduce

1. Eager load categories for posts, e.g.

```
{% set posts = craft.entries({
    section: 'posts',
    with: ['thumbnailImage', 'readTime', 'postCategories', 'postTypes']
}) %}
```

2. Try to loop through the postCategories, e.g. `{%- for category in entry.postCategories.all() %}` - the loop works without `.all()`, but a deprecation error is shown: `Looping through element queries directly has been deprecated. Use the all() function to fetch the query results before looping over them.`

### Additional info

- Craft version: 3.0.22

**Comment by brandonkelly** [comment]
I’m not able to reproduce this, and pretty sure what you’re describing is impossible, as that deprecation error comes from `craft\elements\db\ElementQuery`, but when you eager-load elements, the result is an array.

I’m guessing the actual deprecation error is getting triggered from somewhere else. Check Utilities → Deprecation Errors to see where it’s saying the origin of that error is.

**Comment by howells** [comment]
Hi sorry for the delay on this. The deprecation error is reporting the exact line in the twig template that I mentioned in my original post, i.e. 

`/*****/templates/components/_entryGrid.twig:31`

Line 31 is:

`{%- for category in entry.postCategories %}`

Not really sure where to go from here or what I'm doing wrong.

**Comment by howells** [comment]
(I should also say, the same deprecation error appears in many places in my twig templates. In each case, adding all just errors.)

**Comment by howells** [comment]
@brandonkelly done - many thanks!

**Comment by zizther** [comment]
@howells Did you get this sorted, as I have been having the issues on multiple sites, even with Craft 3.4.5

**Comment by howells** [comment]
@zizther no, it was never resolved

**Comment by brandonkelly** [comment]
We added [craft\services\Deprecator::$throwExceptions](https://docs.craftcms.com/api/v3/craft-services-deprecator.html#throwexceptions) in 3.1.18, which may be helpful here. Instead of logging the deprecation error, an exception will be thrown, which will help you determine where and how they are occurring. (Only recommended for local environments.)

To enable, open `config/app.php` and add this:

```php
return [
    '*' => [
        // global config...
    ],
    'dev' => [
        'components' => [
            'deprecator' => [
                'throwExceptions' => true,
            ],
        ],
    ],
];
```

**Comment by narration-sd** [comment]
nice aid...

**Comment by jsunsawyer** [comment]
Checking in with the same issue.

I'm simply eager loading a set of categories, so I can't use `.all()`.

```
{% set films = craft.entries({
  section: 'films',
  with: ['relatedTopics']
}) %}
```

Inside my paginated films list I'm outputting categories with each film.

```
{% set relatedTopics = film.relatedTopics %}
{% if relatedTopics %}
  <ul>
    {% for topic in relatedTopics %}
      <li><a href="{{ topic.url }}">{{ topic.title }}</a></li>
    {% endfor %}
  </ul>
{% endif %}
```

Debug toolbar tells me that I need to use `.all()` in my categories loop.

Craft 3.4.8

**Comment by zizther** [comment]
This is a similar scenario to examples of this issue I have had

**Comment by brandonkelly** [comment]
@jsunsawyer @zizther Please set `'throwExceptions' => true` per my last comment, and then check the stack trace when the exception gets thrown. If it looks like Craft is the culprit, find the error in `storage/logs/web.log` and post the stack trace that follows.

**Comment by jsunsawyer** [comment]
@brandonkelly After a bit more digging, we figured out what was causing the issue.

We were doing a separate query for featured films that later get excluded from our normal films query. So our normal query had eager loading setup, while the other didn't, but both were using the same film widget component.
