### ISSUE TITLE
[Twig Runtime Error] Error when creating a new field

### ISSUE THREAD

**Issue by nikolowry** [craftcms/cms#3267]
### Description

Just updated to v3.0.23, and now when I attempt to create a new field I get the following message:
```
Twig Runtime Error – Twig_Error_Runtime
Variable "blockTypes" does not exist.

1. in /var/www/site/vendor/craftcms/cms/src/templates/_components/fieldtypes/Matrix/settings.html at line 12
```

Screenshot:
![img-2018-09-04-155211](https://user-images.githubusercontent.com/597310/45054304-93527500-b05a-11e8-8724-e5905bb8c081.png)

Seems directly related to the changes located at https://github.com/craftcms/cms/blob/master/src/templates/_components/fieldtypes/Matrix/settings.html#L12

Do note, in different environments when `devMode` is `false` and `suppressTemplateErrors` is `true`, the normal 'Create a new field' flow is restored.

### Steps to reproduce

1. Update to latest release
2. Ensure the following are set in `config/general.php`:
```
return [
    `devMode` => true,
    `suppressTemplateErrors` => false
]
```
3. Go to Settings > Fields
4. Click 'New Field +' CTA

### Additional info

- Craft version: v3.0.23
- PHP version: 7.2
- Database driver & version: MariaDB 10.1

**Comment by nikolowry** [comment]
Closing as this seems to be a duplicate of https://github.com/craftcms/cms/issues/3268

**Comment by brandonkelly** [comment]
(Actual culprit is verbb/super-table#194.)
