### ISSUE TITLE
Matrix settings template throwing errors when trying to create or edit fields

### ISSUE THREAD

**Issue by tjdraper** [craftcms/cms#3268]
### Description

Site in dev was a few versions behind so I ran composer update. Now getting errors from the Matrix settings template any time I try to create or edit a field.

![screenshot_1](https://user-images.githubusercontent.com/3803475/45054191-deb45580-b051-11e8-97ce-ac58c036df48.png)

### Steps to reproduce

1. Try to create or edit a field

### Additional info

- Craft version: 3.0.23
- PHP version: 7.2.5
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
    - Ansel for Craft 2.0.0
    - Craft Static 1.0.4
    - Redactor 2.1.6
    - Super Table 2.0.8

**Comment by tjdraper** [comment]
Doh. Should have spent a *little* more time digging. I think this is a Super Table issue...

**Comment by tjdraper** [comment]
Yep, sorry. I saw errors from a CMS core template and thought it was a bug in the CMS. Sorry to bother you.

**Comment by brandonkelly** [comment]
(Actual culprit is verbb/super-table#194.)
