### ISSUE TITLE
Twig Runtime Error – Twig_Error_Runtime Variable "blockTypes" does not exist.

### ISSUE THREAD

**Issue by sethdouwsma** [craftcms/cms#3272]
### Description
Getting a twig error when trying to add a new field with 3.0.23.*
https://cl.ly/37988903aa37

### Steps to reproduce

1. Upgrade to 3.0.23.*
2. Settings->Fields->Add a new field

### Additional info

- Craft version: 3.0.23.1
- PHP version: 7.2.1
- Database driver & version: MySQL 5.6.38
- Plugins & versions: https://cl.ly/6090050edb24

**Comment by pette87** [comment]
Same to: Variable "blockTypes" does not exist.

Please fix ver quick!

**Comment by brandonkelly** [comment]
This is due to verbb/super-table#194.

Here's how you can patch it while we wait for a Super Table update: https://github.com/verbb/super-table/issues/194#issuecomment-418519440

**Comment by sethdouwsma** [comment]
@brandonkelly Thank you!

**Comment by pette87** [comment]
@brandonkelly Thanks a lot! 👍
