### ISSUE TITLE
Error when creating or editing field.

### ISSUE THREAD

**Issue by tplassman** [craftcms/cms#3273]
### Description
After updating to 3.0.23.1, when editing an existing field or creating a new field in setting I get the following error:

Variable "blockTypes" does not exist.
/vendor/craftcms/cms/src/templates/_components/fieldtypes/Matrix/settings.html at line 12 

### Steps to reproduce

1. Have Craft CMS v3.0.23.1
2. Navigate to Settings > Fields
3. Click create new field

### Additional info

- Craft version: 3.0.23.1 (Pro)
- PHP version: 7.1.20
- Database driver & version: MySQL 5.5.5
- Image driver & version: GD 7.1.20
- Plugins & versions: 
    - Email 1.0.0
    - Redactor 2.1.6
    - Sprout Forms 3.0.0-beta.24
    - Super Table 2.0.8

[new-field.pdf](https://github.com/craftcms/cms/files/2354029/new-field.pdf)

**Comment by brandonkelly** [comment]
This is due to verbb/super-table#194. While we wait for a new Super Table release, can patch your install by following these instructions: https://github.com/verbb/super-table/issues/194#issuecomment-418519440

**Comment by tplassman** [comment]
Thanks, @brandonkelly.  Appreciate the quick response and information.
