### ISSUE TITLE
Database exception error when adding Replace() to Cast() in orderBy

### ISSUE THREAD

**Issue by jkorff** [craftcms/cms#3274]
### Description
I have entries with auto-generated titles of the format `Timeline-YYYY-MM-DD` or `Timeline+YYYY-MM-DD` which I want to sort without the string `Timeline`.

The code I need is

```twig
{% set entries = craft.entries(queryParameters)
    .offset(offsetParam)
    .orderBy('cast(replace(title, "Timeline", "") as decimal)')
    .limit(null) %}
```

Working SQL fiddle: http://sqlfiddle.com/#!9/fe0833/11;
Similar tested SO code: https://stackoverflow.com/a/10264751/7942404

In Craft, this code technically works:

```twig
{% set entries = craft.entries(queryParameters)
    .offset(offsetParam)
    .orderBy('cast (title as decimal)')
    .limit(null) %}
```

...but obviously all entries are cast to zero. The `cast()` function is working however. Adding the `replace()` function though throws the database exception error, and it complains about wrong syntax in a subquery (the line with the cast and replace functions).

Is this a bug or a limitation of Craft?

### Steps to reproduce

as outlined above

### Additional info

- Craft version: 3.0.21
- PHP version: 7
- Database driver & version: MySQL 5.5
- Plugins & versions:

**Comment by brandonkelly** [comment]
What SQL error are you getting?

Is the date being defined by the entry’s post date, or a custom Date/Time field?

**Comment by jkorff** [comment]
Thank you for looking into this. Here is the error message that I get (field list cut for brevity):

```
Database Exception – yii\db\Exception
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`subquery`
INNER JOIN `entries` `entries` ON `entries`.`id` = `subquery`.`elemen' at line 9
The SQL being executed was: SELECT `elements`.`id`, [...] `structureelements`.`structureId`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`
FROM `elements` `elements`
INNER JOIN `entries` `entries` ON `entries`.`id` = `elements`.`id`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `content` `content` ON `content`.`elementId` = `elements`.`id`
LEFT JOIN `structureelements` `structureelements` ON `structureelements`.`elementId` = `elements`.`id`
WHERE (`entries`.`typeId`='22') AND (`entries`.`sectionId`='2') AND (`elements_sites`.`siteId`='1') AND (`content`.`siteId`='1') AND (`elements`.`archived`=FALSE) AND (((`elements`.`enabled`=TRUE) AND (`elements_sites`.`enabled`=TRUE)) AND (`entries`.`postDate` <= '2018-09-06 07:12:36') AND ((`entries`.`expiryDate` IS NULL) OR (`entries`.`expiryDate` > '2018-09-06 07:12:36'))) AND (`elements_sites`.`enabled`=TRUE)
ORDER BY cast(replace(title, `"Timeline"`, `"") as decimal)`) `subquery`
INNER JOIN `entries` `entries` ON `entries`.`id` = `subquery`.`elementsId`
INNER JOIN `elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `content` `content` ON `content`.`id` = `subquery`.`contentId`
LEFT JOIN `structureelements` `structureelements` ON `structureelements`.`elementId` = `subquery`.`elementsId`
ORDER BY cast(replace(title, `"Timeline"`, `"") as decimal)`
Error Info: Array
(
    [0] => 42000
    [1] => 1064
    [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`subquery`
INNER JOIN `entries` `entries` ON `entries`.`id` = `subquery`.`elemen' at line 9
)
↵
Caused by: PDOException
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`subquery`
INNER JOIN `entries` `entries` ON `entries`.`id` = `subquery`.`elemen' at line 9
in /Users/xxx/code/craft/vendor/yiisoft/yii2/db/Command.php at line 1258
```

**Comment by brandonkelly** [comment]
Thanks. Just looked into this. The only way you can get the `order by` clause you want is if you can set the value to an [Expression](https://www.yiiframework.com/doc/api/2.0/yii-db-expression) object, which wouldn’t be possible from your template.

```php
$query->orderBy(new \yii\db\Expression('cast(replace(title, "Timeline", "") as decimal)'));
```

Otherwise, Yii is going to see those commas and assume that you’re trying to order by a list of column names – which is why it is adding those backticks (<code>`</code>) to your query:

```sql
ORDER BY cast(replace(title, `"Timeline"`, `"") as decimal)`
                             ^          ^  ^               ^
```

(It’s not adding backticks around  the first segment, `ORDER BY cast(replace(title`, because it contains a left parentheses (`(`), which is also why this sortof works as expected when you leave out the `replace()` function.

So either you create a PHP function that your template can access, which sets the `orderBy` param to an Expression object (see [Extending Twig](https://docs.craftcms.com/v3/extend/extending-twig.html#extend-the-global-craft-variable)), or you need to find a different way to get the results you want.

So again… is the date being defined by the entry’s post date, or a custom Date/Time field?

**Comment by brandonkelly** [comment]
You're going to get much better performance if you set the timestamp/decimal value in a custom field anyway (so MySQL doesn't have to do any type-recasting at query execution time). You could still have the value be automated.

1. Create a new custom field to hold the values, using whatever field type is most appropriate.
2. Write a [module](https://docs.craftcms.com/v3/extend/module-guide.html) that listens to the [EVENT_BEFORE_SAVE](https://docs.craftcms.com/api/v3/craft-base-element.html#event-before-save) event for entries, and sets the custom field value.

```php
use yii\base\Event;
use craft\elements\Entry;
use craft\base\Element;
use craft\events\ModelEvent;

Event::on(Entry::class, Element::EVENT_BEFORE_SAVE, function(ModelEvent $e) {
    /** @var Entry $entry */
    $entry = $e->sender;

    if ($entry->section->handle == '<SectionHandle>') {
        $entry->setFieldValue('<FieldHandle>', '<FieldValue>');
    }
});
```

Then in the template you can just do this:

```twig
{% set entries = craft.entries(queryParameters)
    .offset(offsetParam)
    .orderBy('<FieldHandle>')
    .limit(null) %}
```

**Comment by jkorff** [comment]
Thank you, Brandon! I appreciate that you took the time to set me off for the module.
