### ISSUE TITLE
Error: Tried to read the folder contents of [...]/public/cache/, but could not.

### ISSUE THREAD

**Issue by steveooo9** [craftcms/cms#3279]
### Description
I get a lot of errors with this "[error] [application]: Tried to read the folder contents of [...]/public/cache/, but could not."

Also:
```
2018/09/06 13:33:06 [error] [application] Tried to read the folder contents of /var/www/project/htdocs/craft/storage/runtime/cache/, but could not.
2018/09/06 13:33:06 [error] [application] Tried to read the folder contents of /var/www/project/htdocs/craft/storage/runtime/assets/sources/, but could not.
2018/09/06 13:33:07 [error] [application] Tried to read the folder contents of /var/www/project/htdocs/craft/storage/runtime/temp/, but could not.
```
All these folders have `775`.

I don't know if this helps, but when clearing the cache via the backend, after cleared, the whole backend is slow as hell. Sometimes so slow that it won't really load.

Hope for help, because this is somewhat urgent.

### Additional info

- Craft version: 2.6.3019
- PHP version: 7.1

**Comment by steveooo9** [comment]
@brandonkelly Also getting `Unable to determine if PATH_INFO is enabled on the server: Client error response` even if https://website.com/index.php/testPathInfo says `success`.

**Comment by brandonkelly** [comment]
@steveooo9 Well you can fix that latter error by explicitly setting the `usePathInfo` setting to `true` or `false`.

**Comment by steveooo9** [comment]
@brandonkelly What about the first one?

We've got a pretty slow system, esp. in the backend.

**Comment by brandonkelly** [comment]
@angrybrad any ideas?

**Comment by angrybrad** [comment]
@steveooo9 you were probably hitting this, which has been fixed for the next release: https://github.com/craftcms/cms/commit/43678553bc1c97090c500ae9f953518c9e12372e

False positive and safe to ignore in the meantime.

**Comment by steveooo9** [comment]
@angrybrad Okay, could be it.

I was looking through the logs in the hope to find the error message that would explain why the backend is pretty slow. Can I share my logs with you via mail, so you could look through them if any message would justify the slow backend?

**Comment by angrybrad** [comment]
@steveooo9 sure... nuke your logs, replicate a slow request with devMode enabled, zip up the logs and send them to support@craftcms.com and we can take a look.
