### ISSUE TITLE
Redactor: Matrix block image setting not saving

### ISSUE THREAD

**Issue by marcustrapp** [craftcms/cms#3282]
### Description
It appears that when a Redactor field is in a Matrix block, it doesn't retain an embedded image's "Open in New Window" checkbox setting.

### Steps to reproduce
1. Create a Matrix field with a block that contains a Reactor field.
2. Configure the Redactor field to allow image embeds.
3. Open an entry with the Matrix field, insert an image.
4. Click on the image, select "Edit", enter a URL for the link, check the "Open in New Window" checkbox, and save the entry.
5. Leave the page or otherwise reload the entry.
6. Reopen the image's Edit window -- all other information will be present, but the "Open in New Window" checkbox will now be unchecked.

### Additional info
- Craft version: Pro 3.0.23.1
- PHP version: 7.0
- Database driver & version: Mariadb 10.3
- Plugins & versions: Redactor 2.1.6

**Comment by brandonkelly** [comment]
Can you please post this in the Redactor repo? https://github.com/craftcms/redactor/issues
