### ISSUE TITLE
assets on multi site setup with different domains

### ISSUE THREAD

**Issue by Djive** [craftcms/cms#3283]
I have a multi site setup with sites on different domains.
Structure of the sites is that web is main site and other sites are parallel with it.
/web
/second-site.com
/third-site.om

I did a relative path setup for Asset Volume, like so:
Base URL: images/news
File System Path: images/news

Created the assets folders in each site:
/web/images/news
/second-site.com/images/news
/third-site.com/images/news

"Propagate entries across all enabled sites?" is enabled for the section.
"Manage relations on a per-site basis" is enabled in the asset field.

**The goal** is not to have duplicate images for each site AND to have each site appear to have its own images.
To have shared assets that appear as separate assets :)
In example:
I publish an entry and upload the image on main site, and save entry.
Entry gets propagated to all sites.
Now I would like for each site to appear to have its own image, like this (even though image exists physically only on main site):
first-site.com/images/news/image.jpg
second-site.com/images/news/image.jpg
third-site.com/images/news/image.jpg

Is it even possible to have image on only 1 site but to show it as it was on different sites (even though its not phisically there)?

Thanks in advance!

- Craft version: Craft CMS 3.0.23.1
- PHP version: 7.2

**Comment by narration-sd** [comment]
@Djive I had an install to move to multisite this evening, and turned up what may help you. The new Craft 3 Sites ability is wide and much more straightforward than before, but there are of course complicated corners yet in it.

The one that may simplify things for you is  actually a set of settings you won't see, unless you go to the bottom of the Image field configuration, and check the Advanced box.  Then you'll  have two settings, which will grow further if you check the top one of them. I think you probably don't need that for your case, but might as well have a look.

And then you'll  need the documentation, to understand what the rather opaque labels for these checkboxes mean. That's here, and can probably be understood for each of them, with patience.

    [](https://docs.craftcms.com/v3/assets-fields.html#multi-site-settings

 I suspect the checkbox setting you're looking for is 'Manage relations on a  per-site basis'. The rest of the issue will have to do with the Asset Sources you've set up, on the Settings>Assets page, and then choosing appropriately which one/s can be used, back on the Asset Field page -- documented above the multi-site settings.

**Comment by Djive** [comment]
Thank you for your comment, but as stated in the middle of my post, I already have enabled 'Manage relations on a per-site basis' in my asset field.

I also did test 'Relate assets from a specific site?' setting and that didn't seem to have much difference in my case. When I enabled it and changed the image in the entry on any of the sites, the image would change on all sites, but on the front-end it was still only visible on main site.

My issue here is that each of my sites is on a different domain.
I did a relative path setup for Asset Volume and I can see all the assets from all sites in the admin under Assets, but when I try to display assets on the front-end, my images don't display on any site but main site since they physically exist only on main site (domain).

**Comment by narration-sd** [comment]
Hmm -- sorry I missed that.

It's late again, and i in a phone away from a computer, but the thought
occurs that possibly you didn't have it all set up at first, and captured
the stage in cache.

If you clear cache and then index assets from Utilities, this path out
something related could be quickly checked.

With a single site, that you can see the thumbnails in the CP might say
indexes were ok, but there might be something about going to multisite that
needs this extra step, much as entries can need a re-save.

**Comment by brandonkelly** [comment]
@Djive There are two ways you can achieve this.

The easiest way would be to stop using 3 different web roots. Are there any notable differences between the files in `web/`, `second-site.com/`, or `third-site.com/` ? If not, just have all 3 domains point to the same `web/` folder. Craft will still be able to determine which site’s content & templates to use based on the requested domain name, as long as:

1. your sites’ base URLs in Settings → Sites include the actual host names, rather than `@web`
2. your `web/index.php` file isn’t restricting Craft to only serve a single site using the `CRAFT_SITE` PHP constant.

If you really do need 3 different web roots, then your other option is to symlink the asset directories.

For example:

```
my-project/
├── web/
│   └── images/
│       └── news/
│           └── ...
├── second-site.com/
│   └── images/
│       └── news --> symlink to ../../web/images/news
└── third-site.com/
    └── images/
        └── news --> symlink to ../../web/images/news
```

**Comment by narration-sd** [comment]
@brandonkelly , beyond needs for @Djive, thanks for such a clear layout of the situations possible here - would feel this could well make it into doc.

- the point about @web actually bit me in another way over the weekend, and seems it should be warned against specifically up front for setting up multisite

- the diagram and an expanded point that it could still be a possible pattern if you need to break out  _some_ assets is also sounds good for that doc area, The diagram could have site-specific content as well as the shared, to make the point.

- Indeed, though, ito not use multiple directories, but rather set asset volumes to split the site-specific content feels much the cleaner and clearer way, if you agree, and then should head the above as a recommendation. Am I missing somthing about this, other reasons one could prefer multiple folders?

I apologize anyway for missing the center of @Djive 's issue -- was of course trying to get him some help over the weekend and possibly off your  guys' shoulders, but should have known better probably than to do it post-midnight ;)

Cheers both,
Clive

**Comment by brandonkelly** [comment]
@narration-sd We wouldn’t recommend one way over the other. It depends on whether you have other things going on in the web root that are site-specific (separate JS/CSS/image resources, etc.).

In this case, with all the images needing to be the same across all 3 sites, it seems somewhat likely that a single web root for all 3 sites would be OK, but I don’t know the whole story.

**Comment by narration-sd** [comment]
@brandonkelly  fair enough, of course.

In fact I got to thinking of some of the other things separate folders might be used for, such as the constants that allow retargeting of various Craft items. And that upgrade of Craft 2 sites might want to stick with the folders approach, just to smooth transitions..

It does seem that single folder could be recommendable, if specific needs aren't there for the other.

My own head too far in other things to have anything like the overview you have of Craft, though, always quite respected...so do as you think, of course...
