### ISSUE TITLE
limitAutoSlugsToAscii do not work for a Cyrillic  "ъ"

### ISSUE THREAD

**Issue by ipetrov87** [craftcms/cms#3286]
### Description
When creating a new entry, the generated slug do not convert a Cyrillic letter **Ъ** to ANSII.

![capture](https://user-images.githubusercontent.com/14108063/45302373-d493ca80-b51b-11e8-96e6-de12195a1b39.PNG)

### Steps to reproduce

1. Set `limitAutoSlugsToAscii `  to `true ` in your `craft/config/genera.php`
2. Go to `Entries -> New entry` and start typing title in Cyrillic, that contains **Ъ**
3. Check the generated slug

### Additional info

- Craft version: 3.0.23.1
- PHP version: 7.2.9
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
I believe this is a bug with [Stringy](https://github.com/danielstjules/Stringy) (the library Craft uses to convert characters to ASCII). I’ve just submitted a bug report about it here: danielstjules/Stringy#190

As of tomorrow’s Craft 3.0.24 release, you will be able to work around this bug with the new `extraAppLocales` config setting in config/general.php:

```
return [
    // ...
    'extraAppLocales' => ['bg'],
];
```

With that in place, user accounts’ Language preferences will have a new “български” option. If you select that, the Control Panel will still be shown in English (as Craft doesn’t currently offer a Bulgarian translation), however it will force Stringy to start using its Bulgarian-specific ASCII character mappings, so `ъ` will get converted to `a`.
