### ISSUE TITLE
Activation Link broken in half

### ISSUE THREAD

**Issue by bymayo** [craftcms/cms#3288]
### Description

When a user activation email is sent, the URL in the email is broken on to two lines in some email clients (Mainly @live.com accounts).

I fixed this by putting the link behind something like `please click <a href="">this link</a> to activate your account` 

This meant the auto linking of the raw URL in the email wasn't broken in half.

I'm unsure if this is happening on all emails sent from Craft.

### Steps to reproduce

1.
2.

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
To be clear this is just a visual annoyance, right? The link still works despite wrapping to multiple lines?

**Comment by bymayo** [comment]
The link appears on 2 lines, but the first line is linked, but the second line is just plain text.

So when they click the link, it only has half of the activation code. 

I don't know if this is just because in the email it isn't added as an actual HTML / Markdown object, and that the mail client is adding the link itself - But only to half of it.

**Comment by brandonkelly** [comment]
Thanks. Shouldn’t be a problem as of the next release.

**Comment by bymayo** [comment]
@brandonkelly Thanks for the fix!
