### ISSUE TITLE
Installer not respecting project.yaml

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/cms#3291]
### Description

After installation, if the `useProjectConfigFile` config setting is enabled, Craft should check if there’s a `config/project.yaml` file and if so, not overwrite it, and allow the next request to apply the changes in it.

### Steps to reproduce

1. Ensure a `project.yaml` file is in place and the `useProjectConfigFile` config setting is enabled
2. Install Craft

### Additional info

- Craft version: 3.1.0-alpha.1

**Comment by brandonkelly** [comment]
This should solve #881.

**Comment by andris-sevcenko** [comment]
Closed via 3878d16
