### ISSUE TITLE
Exception in the CP before you’re able to run 3.1 migrations

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#3295]
### Description

I updated to 3.1 alpha and didn’t get a chance to trigger migrations from the CP.

> Column not found: 1054 Unknown column 'elements.dateDeleted' in 'where clause' in /Users/Christian/Websites/craft3/vendor/yiisoft/yii2/db/Command.php:1258

https://gist.github.com/carlcs/8e3ed1bb2c6d12ac94247c87f8ff002d

### Steps to reproduce

1. Update to 3.1.x-dev e96e107
2. Go to /admin/dashboard, /admin/entries or /admin/settings

**Comment by brandonkelly** [comment]
@carlcs can you email your `composer.json`, `composer.lock`, and a zip of `/Users/Christian/Websites/dev/Plugins/craft-maintenance` over to support@craftcms.com?

**Comment by carlcs** [comment]
Sorry, I totally didn’t realize that it was coming from my own plugin. 

I’m querying for elements in my `Plugin::init()`, and already have a guard clause in place to exit early when the plugin isn’t installed or if it needs migrations.

So it looks like I now have to add another condition for when Craft needs migrations. 

```php
if (
    !$this->isInstalled ||
    Craft::$app->getPlugins()->doesPluginRequireDatabaseUpdate($this) ||
    Craft::$app->getUpdates()->getIsCraftDbMigrationNeeded()
) {
    return;
}
```

It works now, but I realize I’d rather run my code in an event handler. Would you be open to add one or two new events to `craft\web\Application`, [line 250](https://github.com/craftcms/cms/blob/76bad35619649d8428e911bcf9ca157132f338ad/src/web/Application.php#L250) or [line 276](https://github.com/craftcms/cms/blob/76bad35619649d8428e911bcf9ca157132f338ad/src/web/Application.php#L276) would probably work well.

**Comment by brandonkelly** [comment]
I don’t think you should have to worry about it in your code. If you can just send me the stuff I mentioned (without your fix), I can fix it on Craft’s end

**Comment by michaelroper** [comment]
Hey @brandonkelly - i just hit this same error after upgrading to 3.1, is this something that is still open and needs plugin authors to make changes? I tried to run the migrations with `./craft migrate/all`, but that failed too...

**Comment by brandonkelly** [comment]
@michaelroper Never heard back from @carlcs so this hasn’t gone anywhere yet. Can you send me the files mentioned in https://github.com/craftcms/cms/issues/3295#issuecomment-420739724 ?

**Comment by khalwat** [comment]
If it helps @brandonkelly looking at the stack trace from the issue I posted, it appears to be coming from Rich Variables after it tries to register an Asset Bundle in the plugin's `init()`: https://github.com/nystudio107/craft-richvariables

**Comment by michaelroper** [comment]
@brandonkelly - pretty sure I'm hitting this because the migrations haven't run properly, as a few people have mentioned in the slack thread today. I've just updated and got the `3.1.0-beta.2` version, and running `./craft migrate/all` still errors with this (similar to #3296?):
```
Exception: Undefined index: 369d012d-89ae-4d6c-9ce3-0b18e627d984 (/Users/michael.roper/Sites/vocus-website-v3/vendor/craftcms/cms/src/migrations/m180516_153000_uids_in_field_settings.php:148)
```

**Comment by carlcs** [comment]
@brandonkelly I completely forgot about this issue. Sorry about that, I’ll send you the files this weekend.

**Comment by brandonkelly** [comment]
Was able to reproduce the error by running an element query from a module’s `init()` method. Seems like that’s the common culprit here. Fixed for the next release.
