### ISSUE TITLE
Error when deleting a site

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#3297]
### Description

> TypeError: Argument 1 passed to craft\services\Sites::deleteSiteById() must be of the type integer, string given, called in /Users/Christian/Websites/craft3/vendor/craftcms/cms/src/controllers/SitesController.php on line 318 and defined in /Users/Christian/Websites/craft3/vendor/craftcms/cms/src/services/Sites.php:862

### Additional info

- Craft version: 3.1.x-dev e96e107

**Comment by carlcs** [comment]
Similar error occurs when deleting an entry type

>yii\base\ErrorException: A non well formed numeric value encountered in /Users/Christian/Websites/craft3/vendor/craftcms/cms/src/services/Sections.php:1273

**Comment by brandonkelly** [comment]
@carlcs What version of PHP are you on, and are you using MySQL or PostgreSQL?

**Comment by carlcs** [comment]
- PHP version: 7.1.21
- Database driver & version: MariaDB 10.3.9
