### ISSUE TITLE
Cron Job Import in FeedMe not triggering EVENT_AFTER_SAVE? Possibly after 3.0.22 update.

### ISSUE THREAD

**Issue by whoisjuan** [craftcms/cms#3299]
### Description
I have a couple of things in my Craft, that depend on listening for this event. One is a preparse field and the other one is a notification system. Both of them are triggered correctly when you create an entry manually.
This also used to work well with my FeedMe imports, but something happened in the last weeks and they stopped working.
FeedMe does the import correctly, but it seems that the EVENT_AFTER_SAVE is not getting triggered when FeedMe creates the entry.

Seems like this happened after updating to Craft 3.0.22, but I'm not entirely sure this has to do with that. I tried finding something meaningful in the logs after running the workflows in DevMode, but didn't see anything relevant.

Any clue on what might be going on?

### Steps to reproduce

1. Import an Entry with FeedMe (Only tested with Cron triggered imports)
2. Listen for EVENT_AFTER_SAVE --> Doesn't fire or something prevents it from being listened.

### Additional info

- Craft version: 3.0.22 / 3.023 & UP
- PHP version: 7.1
- Database driver & version: MySQL
- Plugins & versions: Feed-Me 3.0.0-beta.21

Have a similar issue opened in Feed-Me's Repo: https://github.com/verbb/feed-me/issues/389

**Comment by brandonkelly** [comment]
Hm, not sure what FeedMe is doing but guessing this will end up being bug on that end. Going to close this and subscribe to your other GH issue for now.
