### ISSUE TITLE
Craft 3.1 Users settings bug

### ISSUE THREAD

**Issue by smcyr** [craftcms/cms#3303]
### Description
When I go to:
/admin/settings/users/settings

I get this error:
Key "photoVolumeUid" for array with keys "allowPublicRegistration, defaultGroup, permissions, photoSubpath, photoVolumeId, requireEmailVerification" does not exist.

### Additional info

- Craft version: Craft 3.1 commit bce3b80322f1c92bdbe53b8a932f72bbcaaafbb7
- PHP version: 7.1

`
Twig_Error_Runtime: Key "photoVolumeUid" for array with keys "allowPublicRegistration, defaultGroup, permissions, photoSubpath, photoVolumeId, requireEmailVerification" does not exist. in D:\projects\craft3\vendor\craftcms\cms\src\templates\settings\users\settings.html:54
Stack trace:
#0 D:\projects\craft3\vendor\craftcms\cms\src\helpers\Template.php(73): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Array, 'photoVolumeUid', Array, 'any', false, false)
#1 D:\projects\craft3\storage\runtime\compiled_templates\2f\2f113c6d3bb3eecf781b73ff434bd020080d9bc9cbb7c941bc3d69b017d20564.php(76): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Array, 'photoVolumeUid', Array)
#2 D:\projects\craft3\vendor\twig\twig\lib\Twig\Template.php(189): __TwigTemplate_bb1e796f7ac1a99bb9587fd05dacabdb4ba1089655555e1a8e257ff635b2e7f3->block_content(Array, Array)
#3 D:\projects\craft3\storage\runtime\compiled_templates\72\721977e040a675b8551472554d21e5becaf298d83a8ac08b511ea305c93c0196.php(639): Twig_Template->displayBlock('content', Array, Array)
#4 D:\projects\craft3\vendor\twig\twig\lib\Twig\Template.php(189): __TwigTemplate_ea3b386e61cad9dc7e0b9dda7065aa45e394e9d5b344f254fed459b1eadea0c4->block_main(Array, Array)
#5 D:\projects\craft3\storage\runtime\compiled_templates\72\721977e040a675b8551472554d21e5becaf298d83a8ac08b511ea305c93c0196.php(536): Twig_Template->displayBlock('main', Array, Array)
#6 D:\projects\craft3\vendor\twig\twig\lib\Twig\Template.php(189): __TwigTemplate_ea3b386e61cad9dc7e0b9dda7065aa45e394e9d5b344f254fed459b1eadea0c4->block_body(Array, Array)
#7 D:\projects\craft3\storage\runtime\compiled_templates\7a\7a0bb42b86f501c0488a0142f42c13ea2df5a55e629437bb184221ce466dda5c.php(60): Twig_Template->displayBlock('body', Array, Array)
#8 D:\projects\craft3\vendor\twig\twig\lib\Twig\Template.php(390): __TwigTemplate_a502428e4cb20937fcbbf0275b06c9542aad6bf9e68f0213d212fe4b0b2172a5->doDisplay(Array, Array)
#9 D:\projects\craft3\vendor\craftcms\cms\src\web\twig\Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#10 D:\projects\craft3\vendor\twig\twig\lib\Twig\Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#11 D:\projects\craft3\vendor\craftcms\cms\src\web\twig\Template.php(31): Twig_Template->display(Array, Array)
#12 D:\projects\craft3\storage\runtime\compiled_templates\e6\e6823382c708f16a182bafb6919ceb6278864408a1727bd8a3927eeaf107b24c.php(40): craft\web\twig\Template->display(Array, Array)
#13 D:\projects\craft3\vendor\twig\twig\lib\Twig\Template.php(390): __TwigTemplate_3219283cc496eeb500265e63f6e9b7e305b954b22a2badbf709ecb499cddc373->doDisplay(Array, Array)
#14 D:\projects\craft3\vendor\craftcms\cms\src\web\twig\Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#15 D:\projects\craft3\vendor\twig\twig\lib\Twig\Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#16 D:\projects\craft3\vendor\craftcms\cms\src\web\twig\Template.php(31): Twig_Template->display(Array, Array)
#17 D:\projects\craft3\storage\runtime\compiled_templates\72\721977e040a675b8551472554d21e5becaf298d83a8ac08b511ea305c93c0196.php(94): craft\web\twig\Template->display(Array, Array)
#18 D:\projects\craft3\vendor\twig\twig\lib\Twig\Template.php(390): __TwigTemplate_ea3b386e61cad9dc7e0b9dda7065aa45e394e9d5b344f254fed459b1eadea0c4->doDisplay(Array, Array)
#19 D:\projects\craft3\vendor\craftcms\cms\src\web\twig\Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#20 D:\projects\craft3\vendor\twig\twig\lib\Twig\Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#21 D:\projects\craft3\vendor\craftcms\cms\src\web\twig\Template.php(31): Twig_Template->display(Array, Array)
#22 D:\projects\craft3\storage\runtime\compiled_templates\d2\d2f9caf79462d31af3ee3607deea6c601107ef972f73b1ac68339efe534c52bd.php(40): craft\web\twig\Template->display(Array, Array)
#23 D:\projects\craft3\vendor\twig\twig\lib\Twig\Template.php(390): __TwigTemplate_4714455ad4f9ceda6672c2e12134396382a0bfa925ea4dc3d70e786e46a775c6->doDisplay(Array, Array)
#24 D:\projects\craft3\vendor\craftcms\cms\src\web\twig\Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#25 D:\projects\craft3\vendor\twig\twig\lib\Twig\Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#26 D:\projects\craft3\vendor\craftcms\cms\src\web\twig\Template.php(31): Twig_Template->display(Array, Array)
#27 D:\projects\craft3\storage\runtime\compiled_templates\2f\2f113c6d3bb3eecf781b73ff434bd020080d9bc9cbb7c941bc3d69b017d20564.php(56): craft\web\twig\Template->display(Array, Array)
#28 D:\projects\craft3\vendor\twig\twig\lib\Twig\Template.php(390): __TwigTemplate_bb1e796f7ac1a99bb9587fd05dacabdb4ba1089655555e1a8e257ff635b2e7f3->doDisplay(Array, Array)
#29 D:\projects\craft3\vendor\craftcms\cms\src\web\twig\Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#30 D:\projects\craft3\vendor\twig\twig\lib\Twig\Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#31 D:\projects\craft3\vendor\craftcms\cms\src\web\twig\Template.php(31): Twig_Template->display(Array, Array)
#32 D:\projects\craft3\vendor\twig\twig\lib\Twig\Template.php(375): craft\web\twig\Template->display(Array)
#33 D:\projects\craft3\vendor\twig\twig\lib\Twig\Environment.php(289): Twig_Template->render(Array)
#34 D:\projects\craft3\vendor\craftcms\cms\src\web\View.php(331): Twig_Environment->render('settings/users/...', Array)
#35 D:\projects\craft3\vendor\craftcms\cms\src\web\View.php(378): craft\web\View->renderTemplate('settings/users/...', Array)
#36 D:\projects\craft3\vendor\craftcms\cms\src\web\Controller.php(155): craft\web\View->renderPageTemplate('settings/users/...', Array)
#37 D:\projects\craft3\vendor\craftcms\cms\src\controllers\TemplatesController.php(78): craft\web\Controller->renderTemplate('settings/users/...', Array)
#38 [internal function]: craft\controllers\TemplatesController->actionRender('settings/users/...', Array)
#39 D:\projects\craft3\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#40 D:\projects\craft3\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#41 D:\projects\craft3\vendor\craftcms\cms\src\web\Controller.php(103): yii\base\Controller->runAction('render', Array)
#42 D:\projects\craft3\vendor\yiisoft\yii2\base\Module.php(528): craft\web\Controller->runAction('render', Array)
#43 D:\projects\craft3\vendor\craftcms\cms\src\web\Application.php(294): yii\base\Module->runAction('templates/rende...', Array)
#44 D:\projects\craft3\vendor\yiisoft\yii2\web\Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#45 D:\projects\craft3\vendor\craftcms\cms\src\web\Application.php(283): yii\web\Application->handleRequest(Object(craft\web\Request))
#46 D:\projects\craft3\vendor\yiisoft\yii2\base\Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#47 D:\projects\craft3\web\index.php(21): yii\base\Application->run()
#48 {main}
`

**Comment by andris-sevcenko** [comment]
Is this on a fresh install or did you update from Craft 3.0.x? Can you send over the contents of the `craft_migrations` table to support@craftcms.com and reference this issue?

**Comment by smcyr** [comment]
I sent an email with the database. I upgraded from Craft 3.0.x. Thanks!

**Comment by Moskydesign** [comment]
Any solution to this? I've got the same problem.

**Comment by brandonkelly** [comment]
Just released 3.1.11 with a fix for this.
