### ISSUE TITLE
Visiting /0 on a Craft 3 install renders index.html outright

### ISSUE THREAD

**Issue by sbossarte** [craftcms/cms#3304]
### Description

Visiting `https://example.com/0` causes Craft to render the template at `index.html` without any provided entry. This happens even if the homepage would normally use a different template.

### Steps to reproduce

1. Start with a fresh Craft install
2. Set up a single to act as the homepage, using template `_x.html`
3. Set up another template at `index.html` as an example
4. Visiting the homepage `https://example.com/` renders the single via `_x.html`
5. Visiting `https://example.com/0` renders `index.html`

or

1. Start with a fresh Craft install
2. Set up a single to act as the homepage, using template `index.html`
3. Visiting the homepage `https://example.com/` renders the single via `index.html`
4. Visiting `https://example.com/0` renders `index.html`, but with `entry` undefined within the template

### Additional info

- Craft version: 3.0.24
- PHP version: 7.1.20
- Database driver & version: MySQL 5.5.56
- Plugins & versions: None

**Comment by brandonkelly** [comment]
Fixed for the next release, thanks for reporting!
