### ISSUE TITLE
Day in date field becomes incorrect prior to 2/12/1847

### ISSUE THREAD

**Issue by Tam** [craftcms/cms#3305]
### Description
The day in a date field becomes incorrect prior to 2/12/1847 (UK format). The futher back in time you go, the more the day drifts. For example, saving 10/9/1847 will result in 9/9/1847 while 10/9/1000 will result in 3/9/1000. Interestingly, the date stored in the database is correct.

### Steps to reproduce

1. Create a date field
2. Save a date prior to 2/12/1847

### Additional info

- Craft version: 3.0.24
- PHP version: 7.2.7
- Database driver & version: Postgres 10.5
- Plugins & versions: 
  - Super Table 2.0.9

**Comment by brandonkelly** [comment]
I’m able to reproduce this, and narrowed it down to a bug in the PHP Intl extension.

Here’s a simple script that reproduces the issue:

```php
$formatter = new \IntlDateFormatter('en-US', \IntlDateFormatter::NONE, \IntlDateFormatter::NONE, 'America/Los_Angeles', null, 'd/M/yyyy');

$date = new \DateTime('1000-09-10');

echo $formatter->format($date);

// expected: 10-9-1000
// actual: 3/9/1000
```

Try disabling the Intl extension on your server. I guess in this case going with PHP’s date formatter is going to be more reliable.
