### ISSUE TITLE
Test E-mail throws template not found error

### ISSUE THREAD

**Issue by bertoost** [craftcms/cms#3309]
### Description

When having a custom template set for emails in Craft, testing the settings is not working correctly. It can not find the core template of the settings page. Caused by not setting the the template-mode back correctly?

![image](https://user-images.githubusercontent.com/398492/45679205-72008700-bb38-11e8-9879-f2358045ef96.png)

As I checked; it is being set back in the Mailer, but that's not working from the controller.
I had to put this at the end of the controller function to get it working again.

```php
/**
 * Tests the email settings.
 */
public function actionTestEmailSettings()
{
    // ....
    Craft::$app->getView()->setTemplateMode(\craft\web\View::TEMPLATE_MODE_CP);
}
```

### Steps to reproduce

1. Login the CP
2. Setup a custom template (don't know for sure if this is the trigger)
3. Try a test e-mail (even if it doesn't work, it should give a nice notification instead of this error)

### Additional info

- Craft version: 3.0.24
- PHP version: 7.1.20

**Comment by brandonkelly** [comment]
Thanks, fixed for today's update.

**Comment by bertoost** [comment]
Nice @brandonkelly ! Lovely to work on a system where bug-reports picked up this soon 👍
