### ISSUE TITLE
Ability to disable 'lastloginAttemptIp'

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/cms#3311]
### Description

Due to GDPR we don't really want to be storing the IP addresses of users, so if possible we'd like the ability to disable this value being stored in the database.

Thanks!

### Additional info

- Craft version: 3.0.24

**Comment by brandonkelly** [comment]
Plan is to add a `storeUserIps` config setting for v3.1, which Craft and plugins can refer to whenever considering storing an IP address somewhere (including `craft\log\FileTarget::$includeUserIp`). By default it will be `false`.

**Comment by brandonkelly** [comment]
Added the `storeUserIps` config setting for the next 3.1 release.
