### ISSUE TITLE
cpresources css/js not displaying on first install

### ISSUE THREAD

**Issue by isomglobal** [craftcms/cms#3312]
### Description
I am trying complete an initial install of Craft (v. 3.0.24). I am having problems with css and js files in cpresources not displaying. I get the following:

![image](https://user-images.githubusercontent.com/43385814/45706330-93b23c00-bb41-11e8-9e8f-6c2d7edc8f6e.png)

I have verified all the server configuration, permissions, and files. I did not use Composer for the installation. Anyone had this experience?

**Comment by isomglobal** [comment]
Hopefully this will help someone else...
When I changed the permissions of cpresources from 744 to 755, the css displayed.

**Comment by jamiehylands** [comment]
> Hopefully this will help someone else...
> When I changed the permissions of cpresources from 744 to 755, the css displayed.

Genius. This has killed me in the past.

**Comment by uxsw** [comment]
Haha! I was stuck on this for ages.
Thanks for posting, HUGE help 👍
