### ISSUE TITLE
Assets don't show up in the on new sites

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#3315]
### Description
We have some strange (i think at least) behaviour. Since the last site we added, assets stopped sharing.

What i interpreted from ticket #1975 is that Assets should be shared between all sites. And this has been the case for us ever since we started with the beta version.

But for some reason, the last site we added doesn't have any assets in the back-end. If you go to the Assets all folders are empty, switch back to another site and they show up again.

So 7 sites sharing assets, and 1 site all by itself with no assets to keep 'm warm in the winter.

What could be the issue here?

### Additional info

- Craft version: 3.0.25
- PHP version: 7.2
- Database driver & version: MySQL 5.7
- Plugins & versions: S3 1.0.8

**Comment by lenvanessen** [comment]
Update: Seems like after adding a new site, in the past the `elements_sites` table got updated, but somewhere in the last releases that stopped working, any ideas?

**Comment by lenvanessen** [comment]
Calling the asset index refresh fixes the problem;)

**Comment by brandonkelly** [comment]
When you add a new site, Craft will add some new Propagate Elements jobs to the queue, for propagating your existing assets, categories, global sets, and tags over to the new site. If anything isn’t showing up in the new site, start by making sure that your queue is completing jobs successfully, by checking its status in your sidebar.

Glad that you got it sorted by reindexing your assets, but I worry that there's still an underlying issue with your queue that needs to be addressed.
