### ISSUE TITLE
Redactor HTML Purifier - Configure to allow iFrame

### ISSUE THREAD

**Issue by jkufrin** [craftcms/cms#3316]
Craft Pro 3.0.25
Redactor 2.1.6
PHP 7.0
MySQL 5.6.34

I'm trying to get the CMS to allow me to input iFrames into the WYSIWIGs. Ideally, I'd like to whitelist additional URLs to allow, but I can't even get Youtube working yet. 

In the WYSIWIG, I can use the Video embed button to add the Youtube embed code. It populates the WYSIWIG, but upon Saving the page, it strips out the iFrame tag. I can also use the HTML button to include the iFrame temporarily, but Saving blows it away.

I edited the /config/redactor/Standard.json file and got it to display the HTML & Video buttons. The allowedTags param doesn't seem to help.

I added a /config/htmlpurifier/config.json file that doesn't seem to work. I also tried the same JSON content with the file as /config/htmlpurifier.json. I'm not sure if Craft is properly importing the config file.

Here's a bitly link to a HTML Purifier Live Demo where I'm trying to get it to allow iFrames. The demo tool doesn't even seem to be allowing iFrames through.
https://bit.ly/2PNwjQS

I'm not sure if HTML Purifier configuration is my issue or if Craft isn't importing the config properly or if it's a bug within Craft/Redactor.

Please advise how to properly setup Craft 3 to allow iFrames. Thanks!

Here are my config files:

config/redactor/Standard.json
```
{
	"buttons": ["html", "formatting", "bold", "italic", "unorderedlist", "orderedlist", "link", "image", "video"],
	"plugins": ["fullscreen", "video"],
	"toolbarFixed": true,
	"allowedTags": ["iframe"]
}
```

config/htmlpurifier/config.json
```
{
	"HTML.Allowed": ["iframe"],
	"HTML.SafeIframe": true,
	"URI.SafeIframeRegexp": "%^(https?:)?//(www\\.youtube(?:-nocookie)?\\.com/embed/|player\\.vimeo\\.com/video/)%"
}
```

**Comment by jkufrin** [comment]
@eablokker are you using Craft 3+? I thought rich text fields went away for Redactor. I don't see an Advanced section in the Settings tab.

**Comment by eablokker** [comment]
Sorry I meant Redactor field, not rich text field. When you are editing the field settings, at the very bottom there is a tiny drop down link that says Advanced. Kind of hard to notice.

**Comment by jkufrin** [comment]
Thanks @eablokker Removing that line and updating the Advanced Settings worked. I was finally able to whitelist a new domain and add an iframe.

**Comment by bkmorse** [comment]
This helped, I have a question about when updating a site from v2 of craft to 3, the video embed worked just fine in craft cms 3 within redactor, but when I went to edit an entry where it showed the video successfully in craft cms 2, but now in craft cms 3 it no longer shows within the redactor field. It must of been stripped during the upgrade process. 

Does anyone know if there is a way to retain the video embeds so I do not have to go and re embed them in each entry? I created a video.json file within config/htmlpurifier and set the field to use that in the advanced settings, but there is no default file within that directory to set it to

`    "HTML.SafeIframe": true,
    "URI.SafeIframeRegexp": "%^(https?:)?//(www\\.youtube(?:-nocookie)?\\.com/embed/)%",
    "Attr.AllowedFrameTargets": ["_blank"],
    "HTML.AllowedComments": ["pagebreak"]
`
So it will not strip out the iframes that worked on craft v2.

Any advice?

**Comment by brandonkelly** [comment]
@bkmorse I just tried creating an HTML Purifier config with the exact code you posted above, and I was able to successfully save a YouTube embed.

The Craft 3 upgrade itself wouldn’t touch any of your field values, and Redactor only runs HTML Purifier when _saving_ entries, not when displaying their existing values. So if you have content that is no longer showing embeds, then those entries must have been resaved before your field was updated to use your custom HTML Purifier config.

**Comment by bkmorse** [comment]
I noticed after doing the upgrade where it altered the v2 of the db to v3, then I'd log into the CP and noticed it was running thousands of queues, most of them were re-saving entries or re-saving drafts, so maybe it stripped them during then?

I also changed the config/htmlpurifier/video.json to config/htmlpurifier/Standard.json and went to the field's advanced settings and it had Standard set instead of "Default" from the list, so I am hoping it will default to config/htmlpurifier/Standard.json and when I run thru the upgrade process again it won't strip the existing iframes.

**Comment by brandonkelly** [comment]
The upgrade will migrate old revision & draft data, but it won’t resave the main entries in the process.

**Comment by bkmorse** [comment]
Thanks @brandonkelly! I went thru the upgrade today and can verify that it did retain the video embeds.

**Comment by brandonkelly** [comment]
Redactor allows iframes for YouTube and Vimeo by default now, so closing this.
