### ISSUE TITLE
SQL error when creating a second homepage

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#3318]
### Description

I was trying to create a seperate homepage single for a site in a multisite setup and got this sql error:

`PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1070-3' for key 'content_elementId_siteId_unq_idx' in /Users/user/Sites/stuwec/vendor/yiisoft/yii2/db/Command.php:1258`

The error only happens when I first disable the original homepage single for site B but leave it enabled for site A. Then I try creating the new only only for site B, not site A.

When disabling site B on the first single, a validation error is show saying "Site B already has a homepage."

### Steps to reproduce

Make sure your install has multiple sites and:
1. Disable the homepage single for site B
2. Create a new homepage single and enable it only for site B

### Additional info

- Craft version: 3.0.25
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Plugins & versions: No plugins installed

**Comment by janhenckens** [comment]
Note: I made the issue because of the exception, not because I think this should be possible :)

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. I'm able to have two separate homepage entries side-by-side as long as they are enabled for different sites. Can you send a DB backup to support@craftcms.com, along with your `composer.json` and `composer.lock` files? Maybe I’ll be able to reproduce it with those.
