### ISSUE TITLE
preg_match(): Compilation failed: nothing to repeat at offset 11

### ISSUE THREAD

**Issue by pauljohnston** [craftcms/cms#3323]
Since the last update the following error has started to appear
> preg_match(): Compilation failed: nothing to repeat at offset 11

It looks to be only happening on multi site setup where url is a 404.

> yii\base\ErrorException preg_match(): Compilation failed: nothing to repeat at offset 11
> /vendor/yiisoft/yii2/web/UrlRule.php:412 yii\base\ErrorHandler::handleError
> /vendor/craftcms/cms/src/web/ErrorHandler.php:76 craft\web\ErrorHandler::handleError
> [internal] preg_match
> /vendor/yiisoft/yii2/web/UrlRule.php:412 yii\web\UrlRule::parseRequest
> /vendor/craftcms/cms/src/web/UrlRule.php:84 craft\web\UrlRule::parseRequest
> /vendor/craftcms/cms/src/web/UrlManager.php:408 craft\web\UrlManager::_getMatchedUrlRoute
> /vendor/craftcms/cms/src/web/UrlManager.php:343 craft\web\UrlManager::_getRequestRoute
> /vendor/craftcms/cms/src/web/UrlManager.php:117 craft\web\UrlManager::parseRequest
> /vendor/craftcms/cms/src/web/Request.php:926 craft\web\Request::resolve
> /vendor/yiisoft/yii2/web/Application.php:82 yii\web\Application::handleRequest
> /vendor/craftcms/cms/src/web/Application.php:271 craft\web\Application::handleRequest
> /vendor/yiisoft/yii2/base/Application.php:386 yii\base\Application::run
> /public/index.php:42 [main]

- Craft version: Craft Pro 3.0.25
- PHP version: 7.2.7
- Database driver & version: MySQL 5.7.23
- Plugins: 

404 monitor | 1.0.4
-- | --

Craft Commerce | 2.0.0-beta.10
-- | --

**Comment by brandonkelly** [comment]
Sounds like you have an invalid URL rule defined somewhere. Most likely in `config/routes.php`, or via a plugin/module that is registering rules using `EVENT_REGISTER_CP_URL_RULES` or `EVENT_REGISTER_SITE_URL_RULES`.
