### ISSUE TITLE
Craft saves dates in the locale format

### ISSUE THREAD

**Issue by TomDeSmet** [craftcms/cms#3325]
### Description
**I saw this behavior in Craft 2.7 but I expect it not being changed in Craft 3.**

I have a website with multiple locales (English, Dutch, French, German and Spanish). I'm saving dates on a front-end form through Ajax, but it seems that Craft saves the dates in the locales' format, eg. in English, the 1st February 2018 would be 02/01/2018 and in Dutch it would be 01/02/2018.

I'd think Craft would save all dates in the same format, disregarding any locale. I read somewhere that craft saves all dates in UTC format.

When I'm in the locale EN and I pass the date 01/02/2018, expecting 2nd January 2018 to be saved, it saves OK. However, if I'm in NL, DE or FR and I pass the same date, it is saved as 1st February 2018 as these languages switch the day and month around.

I always pass MM/DD/YYYY to the date field whatever locale. I'm using the dateFns library for formatting and the date it formats is correct. I use VueJS v-calendar as a datepicker which also shows everything correct.

But when it's saved to Craft it suddenly switched day and month in the back-end!

https://craftcms.stackexchange.com/questions/27817/does-craft-save-dates-in-the-locale-format/27818#27818

### Expected behavior
Isn't this a strange design choice purely targeted towards Twig output?
Because a date input field expects a certain format (MM/DD/YYYY), it doesn't care about locales. 
On top of that, the browser formats the date in the date field according to the users browser language, which can be different from the locale of the website. It probably is most of the time. 
So if Craft switches DD and MM, the browser and the datefield interprets the date wrong! 

So I would expect Craft to save it in a fixed locale (maybe if the field would be translatable it could do what it does now, then it would make sense). This behavior is good for Twig outputs but that's not always the use case!

### Additional info

- Craft version: 2.7
- PHP version: 7.0
- Database driver & version: MySQL
- Plugins & versions: Many

**Comment by brandonkelly** [comment]
In the database, all dates are stored in the MySQL/PostgreSQL DATETIME format (YYYY-MM-DD HH:MM:SS), and always in UTC. The only thing that can vary depending on locale is how Craft will format dates by default, and how Craft expects dates to be submitted within forms.

Craft is used by a global audience, and 01/02/2018 means different things depending on where you live. In the US that means “January 2, 2018”. In the UK that means “1st January 2018”. Forcing everyone to stick with a specific format would drive half of Craft’s users mad.

If you really want to have your website’s date inputs stick to a consistent format, you can do that if you normalize the value into `YYYY-MM-DD HH:MM:SS` (or just `YYYY-MM-DD` if time isn’t important), or a Unix timestamp. You could probably pull that off with a little JavaScript.

```html
<input type="hidden" name="fields[myDateTimeField]" value="2018-02-01">
```
