### ISSUE TITLE
Craft is unable to execute some background tasks if ignore_user_abort is disabled

### ISSUE THREAD

**Issue by justdoweb-be** [craftcms/cms#3328]
### Description

My CraftCMS instance report me an unknown error (red box on top of admin panel) while trying to delete stale template caches. Many backgrounds tasks stay with a pending status while working on content.

<img width="386" alt="screenshot 2018-09-27 at 11 06 19" src="https://user-images.githubusercontent.com/878879/46135423-6d795400-c245-11e8-97c3-a7d79e69b5f5.png">

Maybe we can add a check on system report's page to see if the function **ignore_user_abort** is available or not.

### Steps to reproduce

1. Disable ignore_user_abort in php configuration.
2. Edit an entry and save it.

### Additional info

- Craft version:Craft Pro 3.0.25
- PHP version:7.2.8
- Database driver & version:MySQL 5.5.5
- Plugins & versions: Seems not relevant in this case

**Comment by brandonkelly** [comment]
By “disable” do you mean “enable”? `ignore_user_abort` is already disabled by default in php.ini.

**Comment by justdoweb-be** [comment]
Sorry for the confusion. Yes, `ignore_user_abord` must be enabled. So it shouldn't be listed in `disable_functions`'s php setting...

**Comment by brandonkelly** [comment]
Sorry I was confused; I thought you were talking about the [ignore_user_abort](http://php.net/manual/en/misc.configuration.php#ini.ignore-user-abort) _setting_, which determines PHP’s default behavior when the user closes the connection. By default that is set to `false`, which means that the PHP script will automatically terminate when the connection is closed, but could also be set to `true`, so PHP is never terminated when the connection closed.

But to clarify, you are not talking about that setting, you are talking about the [ignore_user_abort()](http://php.net/manual/en/function.ignore-user-abort.php) _function_ being disabled by the `disable_functions` setting.

Craft relies on the ability to call `ignore_user_abort(true)` when running background tasks using the built-in queue worker. So there is nothing we can do about this. You will need to do one of these things:

- Get your host to remove `ignore_user_abort` from `disabled_functions`.
- Disable Craft’s [runQueueAutomatically](https://docs.craftcms.com/v3/config/config-settings.html#runqueueautomatically) config setting, then either [use a different queue driver](https://docs.craftcms.com/v3/config/#application-config) or exclusively run the queue [from the console](https://github.com/yiisoft/yii2-queue/blob/master/docs/guide/driver-db.md#console).
- Find a different host.
