### ISSUE TITLE
Feature Request: Update yiisoft/yii2-queue to 2.1.0

### ISSUE THREAD

**Issue by putyourlightson** [craftcms/cms#3331]
The Yii2 Queue Extension has some enhancements since [version 2.1.0](https://github.com/yiisoft/yii2-queue/blob/2.1.0/CHANGELOG.md), specifically "AWS SQS implementation" and "worker loop event", which be great to have access to in plugins. 

So please consider this a feature request for updating the minimum requirement of the package to 2.1.0.

Danke!!

**Comment by andris-sevcenko** [comment]
This was fixed in https://github.com/craftcms/cms/commit/fe91109ce8e3bccbed31ad78c697813020e9d6ba
