### ISSUE TITLE
Disabled Matrix blocks visible in Share URLs

### ISSUE THREAD

**Issue by stevehurst** [craftcms/cms#3338]
I'm seeing this behavior on Craft 3.0.26.1

1) Disabled Matrix Blocks are hidden in Current entry versions, and Live Previews of Current and Draft Versions
2) Disabled Matrix Blocks are visibile in shared Draft versions, outside of the CP

I'm not eager loading or anything out of the ordinary on the templates.

### Additional info

- Craft version: 3.0.26.1
- PHP version: 7.0.32
- Database driver & version: MySQL 5.7.23

**Comment by brandonkelly** [comment]
Thanks, fixed for the next release!
