### ISSUE TITLE
\craft\web\Application::_processActionRequest() isn't taking URL rules into consideration

### ISSUE THREAD

**Issue by sjadema** [craftcms/cms#3340]
### Description

I'm building a plugin which serves as a base to create front end forms. I would like to use the `action` parameter in the `POST` request upon form submission to resolve the correct controller.

### Steps to reproduce

1. Create a URL rule with a param in it (e.g. `plugin-handle/<param:[^\/]+> => plugin-handle/controller`)
2. Try to make an `action` request to this route with the `param` filled (e.g. `action/plugin-handle/test`)
3. You will now get an `yii\base\InvalidRouteException` exception because the route is invalid

### Additional info

- Craft version: 3.0.26.1
- PHP version: 7.2.10
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
URL rules are only for routing URLs. If you are explicitly passing an `action` param, that takes precedence over the URL (it is explicitly telling Craft which controller _action_ to route the request to). So it’s expected behavior that your URL rules would not apply.

**Comment by sjadema** [comment]
Okay, i'm fine with telling the action the explicit controller but it removes the ability to pass parameters via a URL to the controller. As this is intended behaviour, would it be possible to make this a feature request? What was the decision behind not letting `action` URLs pass through the `UrlManager`?

**Comment by brandonkelly** [comment]
You can pass parameters in the query string or request body (if it's a POST request).

**Comment by brandonkelly** [comment]
See https://docs.craftcms.com/v3/routing.html for a list of steps Craft takes to route requests. Action requests (step 1) are a special case that will get routed before Craft starts parsing the URL as a possible element URI (step 2) or URL rule pattern (step 3).

**Comment by sjadema** [comment]
I know i can pass parameters in the body (which is my use case). This just introduces an additional step for me as i have to check for the presence of that parameter. If the action URL would be passed through the `UrlManager`, it removes this check because it will just throw a `404` because the route requirements are not met (when someone fiddles with the form).

I'll change my code so the parameter is passed in the request body. I still think it would be a nice feature though :)

**Comment by brandonkelly** [comment]
Well, I should say that there’s nothing forcing you to send an “action request”. You could just register a new URL rule and have the request point to that, so your parameters are enforced.

**Comment by sjadema** [comment]
Yeah, but then the URL actually changes which is bad when submitting the form (for validation purposes). Or is there a way to circumvent this? Rerouting the request internally or something?

**Comment by brandonkelly** [comment]
Sorry yes you are right.

**Comment by sjadema** [comment]
Hence the bug report that might become a feature request ;)

**Comment by brandonkelly** [comment]
Well you should still be able to specify action params as query string parameters.

```twig
{% set url =  actionUrl('plugin-handle/action/path', {
    'param1': 'foo',
    'param2': 'bar',
}) %}

<form method="post" action="{{ url }}">
```

Or if you want to specify the controller action using an `action` body param:

```twig
{% set url =  url(craft.app.request.pathInfo, {
    'param1': 'foo',
    'param2': 'bar',
}) %}

<form method="post" action="{{ url }}">
    <input type="hidden" name="action" value="plugin-handle/action/path">
```

**Comment by sjadema** [comment]
Yeah, in my case i'd like to use the 2nd method. It doesn't change much implementation wise. I either need to check the `GET` parameter for the value or the `POST` parameter. I'll just pass an additional hidden input with the request body. Thanks for your time and explanation!

**Comment by brandonkelly** [comment]
It does, because any query string parameters will be passed directly to the controller action’s arguments if their names match the argument names.

For example with the above example, if you had this in your controller:

```php
public function actionFooBar(string $param1, string $param2)
{
    // ...
}
```

Then `$param` and `$param2` would be set to whatever those query string parameters were in the form action.
