### ISSUE TITLE
Widget Manager/HUD won't close

### ISSUE THREAD

**Issue by adampatpattison** [craftcms/cms#3343]
### Description

Widget Manager/HUD doesn't close and the hud-shade renders the rest of the page useless without a refresh.

### Steps to reproduce

1. Login to admin dashboard
2. Click the Widget edit cog 
![image](https://user-images.githubusercontent.com/4398922/46283515-7a12ea80-c56c-11e8-8db4-f1da3f7c6011.png)
3. Try to return to the dashboard (regardless of changing anything or not)

MP4 Video: https://pat-cts.tinytake.com/sf/Mjk2MDU1OF84ODg0NjU2

### Additional info

- Craft version: 3.0.25  
- PHP version: 7.1.20
- Database driver & version: MySQL 5.6.36
- Other Info
	- Image driver & version	Imagick 3.4.3 (ImageMagick 6.9.10-7)
	- Craft edition & version	Craft Pro 3.0.25
	- Yii version 2.0.15.1
	- Twig version	2.5.0
	- Guzzle version	6.3.3
	- Imagine version	0.7-dev
- Plugins
	- Advanced Url Field	1.0.0
	- Agnostic Fetch	2.0.3
	- Anchors	2.1.0
	- Contact Form	2.2.2
	- Contact Form Honeypot	1.0.2
	- CP Field Inspect	1.0.5
	- Entry Instructions	1.0.2
	- Environment Label	3.1.4
	- FastCGI Cache Bust	1.0.8
	- Google Cloud Storage	1.1
	- Incognito Field	1.0.0
	- Logs	3.0.0
	- Mailgun	1.2.0
	- Mailgun Events	1.0.4
	- Migration Manager	3.0.11
	- Minify	1.2.9
	- NSM Fields	0.0.11
	- Query	2.0.3
	- Redactor	2.1.6
	- Redirect plugin for Craft 3	1.0.18
	- SEO Settings	3.1.22
	- Snitch	2.0.2
	- Super Table	2.0.10
	- Typogrify	1.1.11

**Comment by brandonkelly** [comment]
I’ve seen this before but haven’t been able to reproduce. Any chance you can send a database backup, plus your `composer.lock` and `composer.json` files over to support@craftcms.com ? Also let me know what browser/version you’re using.

**Comment by adampatpattison** [comment]
I've sent those over just now.

Browser I am getting the issue in is Google Chrome for Windows Version 69.0.3497.100 (Official Build) (64-bit)

Thanks

**Comment by brandonkelly** [comment]
Fixed for the next release. Thanks for helping!
