### ISSUE TITLE
Page titles disappear when element don't pass validation on the Name attribute

### ISSUE THREAD

**Issue by owldesign** [craftcms/cms#3344]
### Description

The page header titles in the `h1` tag are not returned if validation fails for elements. Seems to happen to most things, like Globals, assets, etc.

### Steps to reproduce

1. Go to Settings -> Sections. Create new test section. Save it.
2. Go back to edit that section, delete value from the Name field, validation error returned for the Name field and `h1` tag is empty for the header title.

Im assuming it should return previously saved name attribute?

### Additional info

- Craft version: 3.0.26.1
- PHP version: 7.1.19

![1](https://user-images.githubusercontent.com/438764/46445755-429f6c00-c72d-11e8-8a06-d418b0befd75.png)
![2](https://user-images.githubusercontent.com/438764/46445760-459a5c80-c72d-11e8-965d-3e011f776e87.png)

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next release.
