### ISSUE TITLE
Cant disable/enable more then a couple 100 entries

### ISSUE THREAD

**Issue by FrencisAlreadyInUse** [craftcms/cms#3346]
### Description
Craft throws an error when trying to enable/disable lots of entries at once

### Steps to reproduce

1. Select couple 100 entries 
2. Set Status to disabled

### Additional info

- Craft version: Craft Solo 3.0.26.1
- PHP version: 7.0.29
- Database driver & version:  MySQL 5.7.21
- Plugins & versions: http://files.wild.as/lYWBcq

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you please send the following to support@craftcms.com?

- your `composer.json` and `composer.lock` files
- a database backup
- any custom plugins/modules that are being pulled in by `path` repos in composer.json
