### ISSUE TITLE
Plugin Store: Can't add plugins to the cart

### ISSUE THREAD

**Issue by ghost** [craftcms/cms#3355]
### Description

Plugin Store: Can't add plugins to the cart. I get a javascript error:

`Cannot read property 'lineItems' of undefined`

### Steps to reproduce

1. Add a plugin to the cart

### Additional info

- Craft version: 3.0.26.1
- PHP version: 7.1.14
- Database driver & version:MySQL 5.7.23
- Plugins & versions: n/a

**Comment by tokersey** [comment]
I have seen this same issue on multiple Craft 3 installs and when creating a new project from composer. When looking at the request being made to `/index.php?p=admin/actions/plugin-store/update-cart`, it returns `{"message":"Server Error"}`.
