### ISSUE TITLE
Editing title field is not updating "live preview"

### ISSUE THREAD

**Issue by kevinmu17** [craftcms/cms#3365]
### Description
When editing the Title field it is not getting updated in "live preview"

### Steps to reproduce

1. Create entry with a simple template that displays {{ entry.title }}
2. Open this entry as admin from the dashboard -> content
3. Open "live preview" and edit the title field (nothing happens)

### Additional info

- Craft version: 3.0.23.1
- PHP version: 7.1.21
- Database driver & version: MySQL 10.1.35
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Not able to reproduce this. Are you fetching that `entry` variable manually, at least when outputting the title?
