### ISSUE TITLE
Issues with the URL field type validation

### ISSUE THREAD

**Issue by eric-chantigny** [craftcms/cms#3367]
### Description
I have some urls that I need to put in and it keeps giving me the Is not a valid URL error.

https://www.academy.com/shop/pdp/adidas-mens-tiro-17-training-pant#repChildCatid=3772582

I'm assuming that the = after the # is the culprit, but that's how my client's system displays the variant products.  I could change the field to a text field, but that defeats the purpose.

### Steps to reproduce

1.  Create a URL field type
2. Try inputting the above url in it.

### Additional info

- Craft version: Craft Solo 3.0.25
- PHP version: 7.2.7
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

**Comment by eric-chantigny** [comment]
Seems that this is a non issue.  I'm closing.

**Comment by brandonkelly** [comment]
So just to confirm, you're no longer getting a validation error for that URL?

**Comment by eric-chantigny** [comment]
Correct @brandonkelly .  All the urls in the document I was using for content migration had some kind of invisible character at the end of each urls.  It wasn't visible so it failed to grab my attention.  I looked at all the usual culprit, missing this one.  Finally realized it was a non issue when one of the urls didn't have that character and passed validation.

**Comment by brandonkelly** [comment]
Cool, glad it’s working then :)
