### ISSUE TITLE
Date fields in Craft not respecting site language

### ISSUE THREAD

**Issue by jamiewade** [craftcms/cms#3369]
### Description
My Craft sites are set-up using the `en-GB` language. As such, dates should be formatted as `DD-MM-YYYY`. However Craft is not respecting this, and displaying dates as `MM-DD-YYYY`.

This is true for the entry Post Date and any custom date field types. Dates are also showing in the wrong format when viewing the entry section overview page.

### Additional info

- Craft version: 3.0.26.1
- PHP version: 7.2.10
- Database driver & version: MySQL 5.7.23

**Comment by brandonkelly** [comment]
The Control Panel uses the date format associated with your user account’s Preferred Language. Go to My Account > Preferences and make sure that Preferred Language is set to `en-GB`.

**Comment by jamiewade** [comment]
@brandonkelly Thanks Brandon, I did check that setting prior to posting the issue. My language was set to `English` so I didn't think anything of it.

Turns out there is an `English (United Kingdom)` option, so after setting that the dates are displaying fine!

**Comment by brandonkelly** [comment]
Yeah, according to the ICU database, `en` uses US date formats. Glad you got it working as expected :)
