### ISSUE TITLE
Error converting Channel to Structure

### ISSUE THREAD

**Issue by mtnorthrop** [craftcms/cms#3373]
### Description
When I try to convert a Channel to a Structure, I get a `Invalid argument supplied for foreach` error, referencing line `1342` of `src/services/Sections.php`:

```
        foreach ($siteIds as $siteId) {
            ...
        }
```

It appears that this is a bug that was introduced in version `3.0.27`, and is due to the fact that `$siteIds` variable is set to an integer on line `1334`:

```
        if ($oldSection->propagateEntries) {
            $siteIds = reset($oldSiteIds);
        } else {
            $siteIds = $oldSiteIds;
        }
```
The issue is that the `reset()` function returns the first value of the array, so when we try to use it in the `foreach` loop on line `1342`, we get an error.

I'm afraid I can't offer a way to fix this issue because I'm not very familiar with the code and it's not obvious to me at a glance why the `$oldSiteIds` array is being reset if `$oldSection->propagateEntries` is "truthful".

### Additional info

- Craft version: 3.0.27
- PHP version: 7.2

**Comment by brandonkelly** [comment]
Thanks for reporting that @mtnorthrop ! We just released 3.0.27.1 with a fix.
