### ISSUE TITLE
Typo in cms\services\Sections.php::getEntryTypesByHandle doc block

### ISSUE THREAD

**Issue by nickfreedom** [craftcms/cms#3376]
https://github.com/craftcms/cms/blob/4402eb4bfd4515246a07706d23f4f5c1f5efcbc8/src/services/Sections.php#L918

The function call example in the doc block appears to be missing an "s" for getEntryTypesByHandle.

Should be:
```php
* $entryType = Craft::$app->sections->getEntryTypesByHandle('article');
```

**Comment by brandonkelly** [comment]
Thanks for pointing that out!
