### ISSUE TITLE
errorTemplatePrefix setting : not possible for multi-site sub array?

### ISSUE THREAD

**Issue by mdominguez** [craftcms/cms#3378]
See attached [screenshot](https://cl.ly/0531bede7f80), doesn't seem to work for this setting?

**Comment by brandonkelly** [comment]
No, that setting does not support per-site values.

Craft will automatically look in `templates/` subfolders named after the current site’s handle, so what you’re trying to do should _just work_ without doing anything. (See https://docs.craftcms.com/v3/dev/#template-localization)
