### ISSUE TITLE
Number fields should return to their default value if the field content was deleted then saved

### ISSUE THREAD

**Issue by jamiewade** [craftcms/cms#3380]
### Description

A number field that has a 'default value' set should return to the default value if the field content was deleted then saved.

At the moment, the field just goes blank.

### Steps to reproduce

1. Create a number field with a default value
2. Add the field to an entry type and create a new entry (adding the field to an existing entry won't work as per https://github.com/craftcms/cms/issues/3379)
3. The entry will display the default value. Delete the content of the field and hit save
4. The field will now be blank

### Additional info

- Craft version: 3.0.27.1
- PHP version: 7.2.10
- Database driver & version: MySQL 5.7.19
- Plugins & versions: No plugins installed

**Comment by brandonkelly** [comment]
I think if you delete the value and click Save, expected behavior is that it will save the blank value.
