### ISSUE TITLE
Number field is ignoring min value when saved as empty

### ISSUE THREAD

**Issue by jamiewade** [craftcms/cms#3381]
### Description

A number field that has a 'Min Value' is ignoring that rule if the field is saved empty.

### Possible workaround

I could set the field as required in the entry type, but if the field itself has a validation rule, it should follow that rule when the entry gets saved.

### Steps to reproduce

1. Create a number field with a min value
2. Add the field to an entry type visit an entry using that type
3. Hit save. The entry will now save with the field blank, even though a min value has been defined in the field settings

### Expected behaviour

Saving the field as blank should populate the field with whatever is defined as the 'Min Value'.

### Additional info

- Craft version: 3.0.27.1
- PHP version: 7.2.10
- Database driver & version: MySQL 5.7.19
- Plugins & versions: No plugins installed

**Comment by brandonkelly** [comment]
I think Min Value should only apply if there is a value.

If you want to force the field to have a value, you can make it required. Then the Min Value setting will always be enforced.
