### ISSUE TITLE
Fields should default to not-translatable when when don't have a content column

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#3385]
It seems like potentially a better default for `craft\base\Field::supportedTranslationMethods` would be to default to `[self::TRANSLATION_METHOD_NONE]` if field don't have a content column (`hasContentColumn` returning false).

The default now assumes if a plugin dev is storing things outside of `content`, they are also making values things multi-site, which probably isn't the case. Since someone would have to intentionally make that field translatable, it makes sense they would have to deal with their own `supportedTranslationMethods` method.

Example: https://github.com/doublesecretagency/craft-smartmap/issues/21

**Comment by brandonkelly** [comment]
Agree, that would be a better default.

**Comment by timkelty** [comment]
👍 I'll PR next time I'm in there

**Comment by brandonkelly** [comment]
No need :)

**Comment by timkelty** [comment]
![download](https://user-images.githubusercontent.com/18329/47156571-6a5a0c80-d2b5-11e8-84f0-d81b4525b7d3.jpg)
