### ISSUE TITLE
search goes blank, but doesn't let go

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#3391]
### Description

I found this trying out 3.1, but from the look of it, may well be in 3.0.x also. 

The problem is that if you use the Search ui field to try to find an Entry, for example, the Search field goes blank but Search remains in force, should you go on to look at other categories of the Entry, etc..

### Steps to reproduce

1. Open Entries in the CP
2. enter a Search term and use it. I was looking for possibles via in: trashed, but it does the same for any search text.
3. See what you see: zero or more Entries
4. As one would naturally think, choose a category of Entry -- nothing. Which actually makes sense, in some ways, but...
5. ...the Search field has gone blank, so you have no idea why you see nothing,
6. With or  without realizing, click Entries again, and all you expect returns to normal view.

Now, another good question on this is whether Craft should indeed refresh to not have the Search restrictor in use, just as it is actually presently showing, when you click on an Element category after a search -- fully revert. I think there can be a good argument this is what a non-programmer is expecting...

### Additional info

- Craft version: 3.1x in test, others suspected

**Comment by brandonkelly** [comment]
> 4. As one would naturally think, choose a category of Entry -- nothing. Which actually makes sense, in some ways, but...
> 5. ...the Search field has gone blank, so you have no idea why you see nothing,

I’m not sure I’m following you here. Are you doing anything in either of these steps?

**Comment by narration-sd** [comment]
Well, let's try another way of stating the steps. It's really simple.

bring up Entries, with several Sections in their Groups available (e.g. Singles, Channels, Structures)
view the sections
type something unfindable in the Search field
note all of the sections disappear
now do a natural thing: click on one of the Groups: e.g. Channels
you don't see any sections come into view
but the Search has gone blank again, so you have no clue why not
I'm suggesting not to correct that the Search went blank, but to let it blank and auto-refresh for the selected Group.

Because clicking that way is a natural move;, especially if you had looked away from the screen. So it should get some action, but showing the content, not clearing the Search field. As that the Search field would be still in force would be unexpected, and probably not seen.

Sleep after all, now. Software, as you know.

**Comment by brandonkelly** [comment]
Thanks, able to reproduce that, but only in Craft 3.1, not 3.0. Will fix.

**Comment by narration-sd** [comment]
Great to hear -- thanks, Brandon

**Comment by narration-sd** [comment]
...and apologies that the steps were a bit misleading in some nouns -- it was indeed quite late.... ;)

**Comment by brandonkelly** [comment]
Fixed via 1ce08ef0601343c5d56adf3f5e92e0459c61d734

**Comment by narration-sd** [comment]
👍
