### ISSUE TITLE
Saving new fields from a new Block Type is not updating the matrixcontent table on a migration

### ISSUE THREAD

**Issue by Tyrannogina** [craftcms/cms#3393]
### Description

On a migration safeUp method I wrote the following migration:

```php
// Get the matrix field
$collectionMatrix = Craft::$app->fields->getFieldByHandle('collection');

// Initialize the block type
$columnsComponent = new \craft\models\MatrixBlockType([
    'fieldId' => $collectionMatrix->id,
    'name' => 'Columns',
    'handle' => 'columns',
    'fields' => [
        // Content
        new \craft\fields\PlainText([
            'name' => 'Section title',
            'handle' => 'sectionTitle',
            'placeholder' => null,
            'code' => '',
            'multiline' => '',
            'initialRows' => '4',
            'translationMethod' => 'site',
        ]),
        new \craft\redactor\Field([
            'name' => 'Section sub title',
            'handle' => 'sectionSubTitle',
            'translationMethod' => 'site',
            'redactorConfig' => 'SimpleTextOnly.json',
            'purifierConfig' => '',
            'cleanupHtml' => '1',
            'purifyHtml' => '1',
        ]),
        new \craft\fields\Lightswitch([
            'name' => 'Align column content left?',
            'handle' => 'alignLeft',
            'translationMethod' => 'none',
            'default' => "",
        ]),
        new \craft\redactor\Field([
            'name' => 'Column one',
            'handle' => 'columnOne',
            'translationMethod' => 'site',
            'redactorConfig' => 'Standard.json',
            'purifierConfig' => '',
            'cleanupHtml' => '1',
            'purifyHtml' => '1',
        ]),
        //Took out some other fields for brevity, but they are also redactor fields
    ],
]);

return Craft::$app->matrix->saveBlockType($columnsComponent);
```

On the `saveBlockType` method, when the `saveField` method is called, the content table that it's retrieved here `$contentTable = Craft::$app->getContent()->contentTable;` points to the `content` table instead of to the `matrixcontent_collection` table that is where it's expecting the new field columns to be. 

The only workaround I found to this was calling `Craft::$app->matrix->saveSettings($collectionMatrix);` after `saveBlockType` which does indeed update the `matrixcontent_collection` columns and prevents errors, but when running more than one migration at a time, it seems to be blocking the table and the second migration does not update the matrixcontent table.

I might be missing something, but I don't seem to find any other method that updates the matrixcontent table for the new blocktype as I'd expect. And neither using the saveSettings or doing it manually myself seem like good approaches. 

### Steps to reproduce

1. Run the migration above on an existing matrix named Collection.
2. Check the table `matrixcontent_collection` to not find there the fields columns (field_columns_sectionTitle, field_colums_sectionSubTitle, etc.).

Alternatively, if two migrations are run with the saveSettings after the saveBlockType, the second one fails. I could probably refactor both migrations as one and run saveSettings only once, as they are blockTypes for the same component, but we wanted to have the option to rollback the migrations separately.

### Additional info

- Craft version: 3.0.0
- PHP version: 7.1
- Database driver & version: mysql 5.7.22,
- Plugins & versions:

I tried to explain as clear as I could think of, but please let me know if more information is required. Thank you.

**Comment by brandonkelly** [comment]
Usually block types are saved while saving the full Matrix field settings (from `craft\services\Matrix::saveSettings()`), and at that point it’s not clear to the block type what the _new_ content table name is going to be (as it may have just changed if the Matrix field handle has changed), so it’s up to the surrounding code to set the correct content table name on the Content service.

```php
$contentTable = Craft::$app->content->contentTable;
Craft::$app->content->contentTable = $collectionMatrix->contentTable;

Craft::$app->matrix->saveBlockType($columnsComponent)

Craft::$app->content->contentTable = $contentTable;
```
