### ISSUE TITLE
Recursive structure in manual download archive

### ISSUE THREAD

**Issue by evanwarner** [craftcms/cms#3394]
### Description
The manual install archive at https://craftcms.com/latest-v3.zip has an issue where each of the top level folders (config, modules, storage, templates, web) has a copy of itself inside.

### Steps to reproduce
1. Download and unzip https://craftcms.com/latest-v3.zip
2. Look inside any top level folder (except vendor) and you'll find a copy of itself.

**Comment by angrybrad** [comment]
@evanwarner that was weird, but should be fixed now on our end!
