### ISSUE TITLE
|nl2br in shorthand "if" statement renders <br /> tags

### ISSUE THREAD

**Issue by mdominguez** [craftcms/cms#3396]
When outputting the contents of a Plain Text field (with line-breaks setting checked) through a Twig shorthand "if" statement, the <br /> tags are rendered "raw".
This screenshot will point out the issue => [view screenshot](https://cl.ly/5231e41d834e)

**Comment by brandonkelly** [comment]
This is happening because in your second example, `|nl2br` isn’t the last thing in the tag, so by the time Twig gets to the end of the tag, it doesn’t remember that the value returned by `|nl2br` should be considered “safe”.

You can fix by adding a `|raw` filter after `|nl2br`.

```twig
{{ (entry.alternativeTitle|length) ? entry.alternativeTitle|nl2br|raw : entry.title }}
```

**Comment by mdominguez** [comment]
Hmm tried that already but unfortunately with the same result => [screenshot](https://cl.ly/85410af179f5)

**Comment by brandonkelly** [comment]
Huh, ok. Try this. then:

```twig
{{ (entry.alternativeTitle|length ? entry.alternativeTitle|nl2br : entry.title|e)|raw }}
```

(The `|e` filter after `entry.title` is crucial here, otherwise the `|raw` tag will introduce an XSS vulnerability.)

**Comment by mdominguez** [comment]
Works great! Thanks Brandon!

**Comment by mdominguez** [comment]
Unfortunately when having an "&" in the title, it outputs the HTML entity "&amp;"

**Comment by brandonkelly** [comment]
Just tested and I’m not able to reproduce. Are you sure you copied my code exactly?

**Comment by mdominguez** [comment]
Oh ok well there's a small difference now, instead of printing it directly through {{ }}, I needed to add it as a parameter to an _include of a component twig file. Like so => [https://cl.ly/9bc5528ef9b4](url)

**Comment by brandonkelly** [comment]
In that case you will need to move the `|raw` tag over to the output tag in the include template. But then you will need to make sure that you are manually escaping the `title` variable everywhere that the include template is used (using `|e`), which seems sketchy.

Maybe it would be better to just always run the `title` variable through `|nl2br`, right from in your `_components/card` template.

```twig
{{ title|nl2br }}
```

Then you can stop worrying about adding `|e` and `|raw` filters altogether.

```twig
{% include "components/_card" with {
    title: entry.alternativeTitle ?: entry.title,
    ...
```
