### ISSUE TITLE
Race condition when saving Matrix fields

### ISSUE THREAD

**Issue by aghull** [craftcms/cms#3400]
### Description

When saving matrix fieldsets under heavy load, the compiled classes fail to accurately compile the full field set, causing missing property errors.

In `Craft\services\Fields#saveField` the `updateFieldVersion` method is called. This method is run for each field in the matrix. The fieldversion is bumped on the first field saved and prevented from being bumped again in the same request:

https://github.com/craftcms/cms/blob/d03dc3bb5d58b3937a359a0278559b11295cdfbb/src/services/Fields.php#L1361

If a request arrives in craft after the first field is saved but before a brand new field is saved, it caches the compiled `ContentBehaviour` class with the new fieldversion, but *without* the new field, preventing the new field from ever appearing in the compiled class.

Removing the line above that prevents multiple fieldversion changes resolves this bug.

### Steps to reproduce

1. Place the site under heavy load
2. Save a large matrix field with a new field added
3. Load any front-end Craft page

### Additional info

- Craft version: 3.0.22
- PHP version: 7.1.17
- Database driver & version: mysql 5.7.22

**Comment by aghull** [comment]
^^ @brandonkelly

**Comment by brandonkelly** [comment]
@aghull Thanks for looking into that and providing the fix. Your PR is merged in for the next release!
