### ISSUE TITLE
Add ability to extend asset previews

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#3402]
### Description

Currently, the "Preview Asset" button is quite limited. At the time of writing this, it appears to only support some hard coded asset kinds:
```php
[self::KIND_IMAGE, self::KIND_HTML, self::KIND_JAVASCRIPT, self::KIND_JSON]
```

Adding some events to register custom asset preview handlers would go a long way to opening up doors for developers. I started investigating this after a client requested the ability to preview PDFs in the CMS. I can easily visualize other use-cases with things like 3D objects, video files, CAD drawings, Unity files, etc.

**Comment by Mosnar** [comment]
As a follow-up here, I was able to come up with a plugin-based workaround for what I needed to do. I wanted to show thumbnails of PDFs, so I hooked into the `Assets::EVENT_GET_THUMB_PATH` event and injected my own thumbnail generation logic. It's certainly not ideal, since the "preview" button in the Element list doesn't work, but you can see thumbnails of the PDFs on the element and when you double-click them to edit them.

I didn't release it because it feels dirty, but if anyone wants to implement it themselves, here's a starting point:

```php

use craft\helpers\Assets as AssetsHelper;
use craft\elements\Asset;
use craft\events\AssetThumbEvent;
use craft\services\Assets;

/// In your init()

Event::on(
            Assets::class,
            Assets::EVENT_GET_THUMB_PATH,
            function (AssetThumbEvent $event) {
                /** @var Asset $asset */
                $asset = $event->asset;
                if (AssetsHelper::getFileKindByExtension($asset->filename) === Asset::KIND_PDF) {
                    // $event->path = (some logic to generate a thumbnail using Imagick)
                }
            }
        );
```
Ideally, it would be nice to pass a blob to Craft and let it figure out what to do with it for the thumbnail rather than making the plugin figure out how to store it with all the options, but it's not difficult to come up with your own convention.

**Comment by urbantrout** [comment]
I guess this is now solved: https://github.com/craftcms/cms/pull/5136
