### ISSUE TITLE
Files missing on manual download for latest update!

### ISSUE THREAD

**Issue by jorgeduardos** [craftcms/cms#3404]
### Description

Folder downloaded from official link ( https://craftcms.com/latest-v3.zip) is missing critical folders and files.
Folders missing: config, storage, templates, web. Only folder inside is the vendor folder.
Also missing env an composer files.

When I cliked on update today from my CP my installation failed and made my site crashed because the files where missing. Had to rollback.!

### Steps to reproduce

1. Download Craft CMS 3.0.28 from https://craftcms.com/latest-v3.zip
2. Open folder a look for missing files.

### Additional info

- Craft version: 3.0.28

**Comment by angrybrad** [comment]
@jorgeduardos Sorry about that!  Should be fixed now on our end.
