### ISSUE TITLE
Web font load stalling

### ISSUE THREAD

**Issue by jamiewade** [craftcms/cms#3405]
### Description
When moving around Craft, the web font used for the sidebar icons stalls whilst loading.

At first I thought it could be related some Chrome plugins, so I loaded Craft in an incognito window but got the same behaviour. 

### Steps to reproduce
![bug](https://user-images.githubusercontent.com/6672331/47555828-bdab0b00-d904-11e8-96ab-0e95dc7dc620.gif)

Here is the font loading in the Network tab:

![bug](https://user-images.githubusercontent.com/6672331/47555864-d74c5280-d904-11e8-9f34-078e4520236d.jpg)

We're running on very fast internet here, so I don't think our network is the cause.

### Additional info

- Craft version: 3.0.28
- PHP version: 7.2.10
- Database driver & version: MySQL 5.7.24

**Comment by brandonkelly** [comment]
Your browser should just be loading that file from cache. Try clicking on it and check the _response_ headers. Is it coming back with `Cache-Control: no-cache` or something?

**Comment by jamiewade** [comment]
Sorry @brandonkelly, this was a configuration issue on our shared development server. All sorted now.
