### ISSUE TITLE
Looping through options for dropdown/checkbox/radio inputs in new entry forms.

### ISSUE THREAD

**Issue by michaeldavidtodd** [craftcms/cms#3408]
### Description
In reference to https://docs.craftcms.com/v3/dropdown-fields.html#templating:
```
{% for option in entry.dropdownFieldHandle.options %}
  <li>{{ option }}</li>
{% endfor %}
```
When using this method on an entry form for creating a _new entry_, this error occurs:
> Impossible to access an attribute (“options”) on a null variable.

### Steps to reproduce

1. Use the above method on an entry form used to create _new_ entries.

### Additional info

The page that my entry form exists on does have an entry, but it's separate from the entry the form is meant to create. The dropdown, checkbox, and radio fields that are coming up null are not used in the page's entry, but in the section for the entry I'm trying to post to. Craft 2 appears to ignore this issue, possibly using the page's entry as a way to get to the field options, even though those fields are not associated with the section the page's entry is assigned to.

- Craft version: 3.0.28 (Pro)
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Image driver & version: GD 7.1.12
- Plugins & versions: 
    - Guest Entries 2.1.3
    - Navigation 1.0.12
    - Redactor 2.1.6

**Comment by michaeldavidtodd** [comment]
I was able to get help in the Slack: https://craftcms.slack.com/archives/C04UQS105/p1540691975178200

Using `craft.fields.getFieldbyHandle` allowed me to look up the field's options without having to go through an entry to get to them. However, I couldn't find this anywhere in Craft's docs. So it seems to be an unofficial workaround. The suggestion was to use `field.settings.options` for the loop, but the `.settings` bit didn't appear to be necessary, so I left that out.

```
{% set field = craft.fields.getFieldbyHandle('dropdownFieldHandle') %}
{% for option in field.options %}
   <option value="{{ option.value }}">{{ option.label }}</option>
{% endfor %}
```

This certainly makes sense, though I'd love to see the docs updated to reflect the need for this if this is the intended solution.

**Comment by brandonkelly** [comment]
The Dropdown field documentation now contains a complete [entry form](https://docs.craftcms.com/v3/dropdown-fields.html#entry-form) templating example, pulling available options from the field model. (Checkboxes, Multi-select, and Radio Buttons field docs have been updated too.)

**Comment by michaeldavidtodd** [comment]
@brandonkelly WONDERFUL! THANK YOU SO MUCH!
