### ISSUE TITLE
Number fields give error when decimal setting is changed and text is entered into the field.

### ISSUE THREAD

**Issue by IndigoViking** [craftcms/cms#3416]
### Description
If the decimal points setting on the number field is set to 0, adding text in the number field will display errors.

If the decimal points setting is set to anything else, Twig will throw an expected float got string error.

See Stack Issue for full discussion:
https://craftcms.stackexchange.com/questions/28270/number-format-expects-parameter-1-to-be-float-string-given/28272#28272

### Steps to reproduce

1. Create number field with decimal points setting other than 0.
2. Add field to section entry type
3. Create entry and enter non-numeric text into field and try to save entry.

### Additional info

- Craft version: 3
- PHP version: 7.1
- Database driver & version: mysql 5.6.25
- Plugins & versions: none

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Whether Decimal Points is set to 0 or something else, if I try saving an entry with a non-numeric value in the Number field, I get the same “<Field Name> must be a number” validation error.

Make sure you’re on the latest version of Craft. Then if you’re still experiencing this issue, please send a database backup, and your composer.json and composer.lock files over to support@craftcms.com.

**Comment by IndigoViking** [comment]
Thanks for looking into it. I just tried to replicate the problem again and no issues were found. Craft and plugins are all up to date. If issue arises again, will look at other possible causes.
