### ISSUE TITLE
Make logger FileTarget class configurable

### ISSUE THREAD

**Issue by timeverts** [craftcms/cms#3418]
### Description
This is a feature request which I really hope you'll implement :)

Craft currently sets the configuration for log files in `craft\helpers\App\logConfig()`. As part of that configuration, a target class is defined for the logger, the target class being `craft\log\FileTarget::class`.

It would be extremely useful if there was a general configuration property that allowed overriding the target class that gets used. This could make the logging set up completely customizable by the developer. This could be achieved by adding a configuration property to `craft\config\GeneralConfig` and having `craft\helpers\App\logConfig()` obtain the target class from that. 

For example:

`craft\config\GeneralConfig`
```
    // Properties
    // =========================================================================
    
    // ...  

    /**
     * @var \yii\log\FileTarget The target class used for logging.
     */
    public $loggerTargetClass = \craft\log\FileTarget::class;
```

`craft\helpers\App\logConfig()`
```
    /**
     * Returns the `log` component config.
     *
     * @return array|null
     */
    public static function logConfig()
    {
        // ...  

        $generalConfig = Craft::$app->getConfig()->getGeneral();

        $target = [
            'class' => $generalConfig->loggerTargetClass,
            'fileMode' => $generalConfig->defaultFileMode,
            'dirMode' => $generalConfig->defaultDirMode,
        ];
        // ...  
    }
```

Using this setup, the developer can implement their own `FileTarget` class that can customise the logger settings, making it possible to customise things like the log file paths, override the log message prefix etc.

A use case where this might be applicable is when running Craft on a load balanced environments where log files can be written from different machines. Thus it might be useful to extend Craft's `FileTarget` class with a custom class that dynamically inserts the host name as part into the log file name. This way each load balanced machine writes to it's own instance of the `web.log` file, particularly if all log files are maintained in a central file store that is used by all machines. 

Another use case might be to have the current date be dynamically included in the log file name so Craft generates a separate `web.log` file for each date. This is great for keeping historical log files rather than having them overwritten through log rotation.

Furthermore, being able to customise the `FileTarget` class would allow for manipulation of the max file size at which log files are rotated. For high traffic Craft sites, the 11mb limit is really too small, such that log files are rotated far too quickly and thus historical logging data gets overwritten far to quickly. Being able to customise the `FileTarget` class means a custom value can then be set for the `maxFileSize` property, meaning logs files are larger and rotated less often.

I'm happy to submit a pull request for this change if preferred.

**Comment by brandonkelly** [comment]
You can already customize that by customizing the [application config](https://docs.craftcms.com/v3/config/#application-config).

Create an `app.php` file in your `config/` folder, with this:

```php
return [
    'components' => [
        'log' => function() {
            $config = craft\helpers\App::logConfig();

            // use a custom target class
            $config['targets'][0]['class'] = my\custom\FileTarget::class;

            return $config ? Craft::createObject($config) : null;
        },
    ],
];
```
