### ISSUE TITLE
Without trailing slash docs goes to AWS

### ISSUE THREAD

**Issue by mrudling** [craftcms/cms#3422]
If you check the v3 docs without a trailing slash you get the AWS URL in the address bar - https://docs.craftcms.com/v3

Goes here:

http://awseb-e-d-awsebloa-z7javxtlhtny-1801095340.us-west-2.elb.amazonaws.com/v3/

With the trailing slash it works fine https://docs.craftcms.com/v3/

**Comment by angrybrad** [comment]
Resolved now.
