### ISSUE TITLE
docs server tweaks

### ISSUE THREAD

**Issue by XhmikosR** [craftcms/cms#3424]
Hi, there!

So, it seems that currently you don't have the following on the docs server:

1. gzip enabled
2. long Cache-Control headers; this needs to be tested before but it seems there's proper cache busting via vuepress

BTW, have you thought about using GitHub pages or even another solution like Netlify? With Netlify you should be able to have build links for each PR for example.

PS. I'm not affiliated with GitHub nor Netlify :)
PPS. I'll make a couple of PRs for a few more trivial issues we can improve.

**Comment by angrybrad** [comment]
There is now a Cloudfront distribution in front of the docs with automatic compression enabled.

**Comment by XhmikosR** [comment]
Weird, I don't see gzip enabled.

**Comment by XhmikosR** [comment]
Now gzip is enabled, but see my point about utf-8 above. This still happens.

**Comment by angrybrad** [comment]
@XhmikosR do you have an updated link with a file with garbled characters? https://docs.craftcms.com/v3/assets/js/206.b2ea0170.js is no longer good and having a hard time finding where `What itâ€™s For` would be in the source docs.

**Comment by XhmikosR** [comment]
@angrybrad https://docs.craftcms.com/v3/assets/js/39.8b7485f5.js

Basically at least CSS, JS and HTML should have `charset=utf-8` to be safe. For a full list see https://github.com/h5bp/server-configs-apache/blob/master/src/media_types/character_encodings.conf

**Comment by angrybrad** [comment]
Cool... done. https://docs.craftcms.com/v3/assets/js/39.8b7485f5.js

**Comment by XhmikosR** [comment]
Cool, not bad, even if it took a while :P

![Screenshot_2019-10-22 Compare Reports docs craftcms com, docs craftcms com, docs craftcms com GTmetrix](https://user-images.githubusercontent.com/349621/67261368-001c0f00-f4a9-11e9-9d19-bdc9934c3494.png)

You could also tweak cache control since the files are cache busted, but it's your call
