### ISSUE TITLE
Ability to disable CP login on multi-site setup specific sites

### ISSUE THREAD

**Issue by naboo** [craftcms/cms#3437]
### Description
I have a feature request which is that in a multi-site setup to be able to disable all sites CP login form that isn't the primary site. Or have some sort of re-direct or button letting you browse to the primary site's login page.

### Why?
Since the licensing is tied into one primary domain and all site related administration should be handled from the "main domain" everytime you login to another site that isn't primary you get the "The license located at config/license.key belongs to XXXX". This is of course confusing for people when they login using the "wrong URL".

### Steps to reproduce

1. Create 2 different sites (Site A, Site B)
2. Set Site A as primary
3. Login to Site B CP
4. Error message will be shown

**Comment by brandonkelly** [comment]
Agree that auto-enforcement is something we should consider. In the meantime you can pull this off using the [baseCpUrl](https://docs.craftcms.com/v3/config/config-settings.html#basecpurl) config setting.

**Comment by naboo** [comment]
Will there be any issues when the user goes to site B login, and tries to login at site A (since the baseCpUrl will be set to another site?) or if the user gets logged in and then click a link which directs them to another site(?). On mobile so not available to test. 
Thanks

**Comment by naboo** [comment]
... thinking about this a bit more. Maybe just mute the licensing error and instead display something like "Running in multi-site setup" would be better?

### Why?

Let's say you are running 5 sites and someone is suppose to edit Site E but shouldn't be aware of Site A. Then you don't want that person to have to login at Site A.

**Comment by brandonkelly** [comment]
> Will there be any issues when the user goes to site B login, and tries to login at site A (since the baseCpUrl will be set to another site?) or if the user gets logged in and then click a link which directs them to another site(?).

Not totally sure I’m following the question, but if the setting is set to `http://site-a.com` and someone goes to `http://site-b.com/admin`, they will be redirected to `http://site-a.com/admin/login`.

> Maybe just mute the licensing error and instead display something like "Running in multi-site setup" would be better?
>
> Why? Let's say you are running 5 sites and someone is suppose to edit Site E but shouldn't be aware of Site A. Then you don't want that person to have to login at Site A.

Single domain enforcement is the only real tool we’ve got to ensuring people use a single Craft license per project (and even then we could be missing some violators if people have multiple Craft projects running on the same domain with the same license), so that’s not something we can change.
