### ISSUE TITLE
FR: Add site ID or site handle as CSS ID or Class on CP HTML or Body tag

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#3439]
### Description
For Multisite setups it would provide some extra extensibility within the control panel to apply additional CSS or JavaScript to style or manipulate the behaviour of site specific pages.

For example css overrides could be set on an entry page based on the selected site in a Multisite setup.

**Comment by brandonkelly** [comment]
Added for the next release!

**Comment by richhayler** [comment]
Awesome - thanks Brandon.
