### ISSUE TITLE
Saving a System Messages Email results in a "non-saving" behavior.

### ISSUE THREAD

**Issue by internetztube** [craftcms/cms#3440]
### Description

Saving a `System Messages Email` results in a "non-saving" behavior. 

### Steps to reproduce

1. Goto /admin/settings/email/messages
2. Edit `Activate your account` Mail
<img width="684" alt="bildschirmfoto 2018-11-05 um 15 56 03" src="https://user-images.githubusercontent.com/6382364/48005282-5581d380-e113-11e8-8447-bc822c567a59.png">

3. Edit body of the first language in the drop-down.

4. Click save.
<img width="361" alt="bildschirmfoto 2018-11-05 um 15 50 01" src="https://user-images.githubusercontent.com/6382364/48005219-24090800-e113-11e8-880d-44a5d7159836.png">
<img width="161" alt="bildschirmfoto 2018-11-05 um 15 50 09" src="https://user-images.githubusercontent.com/6382364/48005220-279c8f00-e113-11e8-847a-d389da7a2e01.png">

5. Reload page.

6. Edit `Activate your account` Mail

7. The content of the primary sites language is in the body input of `de-DE`.

### Additional info

Default Site's language is `en`.

- Craft version:  Craft Pro 3.0.27
- PHP version: 7.1.23
- Database driver & version: MySQL 5.7.24

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. In step 7 are you re-selecting “German (Germany)” when you open the modal?

**Comment by internetztube** [comment]
"German (Germany)" is the default property in the dropdown.

**Comment by brandonkelly** [comment]
Can you please send your `composer.json` and `composer.lock` files, and a database backup, over to support@craftcms.com ? Maybe I will have better luck reproducing the issue with those.

**Comment by internetztube** [comment]
Sent.

**Comment by internetztube** [comment]
Thanks.
