### ISSUE TITLE
Failed to write cache file error

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#3442]
### Description
On one of my windows machines, where i run craft on localhost xampp, i periodically get such errors:

`RuntimeException: Failed to write cache file "C:\xampp\htdocs\website\storage\runtime\compiled_templates/c9/c90c1457752bf3aec3b5a117b34a77a93c144645754ccaa6ca4b10baaf55fe28.php".`

When such error appears, refreshing doesnt help - i need to wait 30 seconds or so and then refresh.

I dont really get this on other machines, so maybe its matter of weak performance of specific machine?

I tried to remove storage folder in craft or php temporary files, but it didnt helped.

### Additional info
- Craft version: Craft CMS 3.0.28

**Comment by angrybrad** [comment]
What are the permission on `C:\xampp\htdocs\website\storage`?  If you recursively give the "Everyone" user permissions on that folder, does it help?

**Comment by piotrpog** [comment]
@angrybrad Permissions are `rwxrwxrwx`. So it seems that its full access. 

Little update, i got this error on my other machine. but this machine is more powerfull, so it resolved itself almost immediately, didnt had to wait 30 seconds, just something like 3 seconds. I have a feeling this errors have something to do with poor performance of my PC after all.

**Comment by angrybrad** [comment]
Hrm... if you have any antvi-virus software or other real-time file scanning software installed that can drastically affect performance.

**Comment by MatoTominac** [comment]
Actually this happens to me too occasionally, also on on Win+XAMPP

**Comment by EngrEli** [comment]
I just refreshed it , and it goes away.
