### ISSUE TITLE
Element x doesn’t exist in the site y when saving new Matrix block

### ISSUE THREAD

**Issue by sjelfull** [craftcms/cms#3445]
### Description

After upgrading to 3.0.30, i'm getting this error when saving a new entry (with a new Matrix block):

Element 9350 doesn’t exist in the site 2.

This is triggered in services/Matrix.php:674.

### Steps to reproduce

1. Create a Matrix field with “Manage blocks on a per-site basis” enabled.
2. Add the field to a section enabled for multiple sites, with “Propagate entries across all enabled sites?” enabled.
3. Try to save a new entry in that section, with at least one block.

### Additional info

- Craft version: 3.0.30

**Comment by mildlygeeky** [comment]
I am having the same issue, though I am running 3.0.29

**Comment by brandonkelly** [comment]
Just released 3.0.30.1 with a fix for this.

@mildlygeeky yeah it was introduced in 3.0.29.

**Comment by mildlygeeky** [comment]
Thanks @brandonkelly!
