### ISSUE TITLE
Error during installing or updating - "Template not found: 500.shtml"

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#3447]
When i try to remove some plugin or update system, sometimes i get this error:
```
Status: Not Found
Response: {"error":"Template not found: 500.shtml"}
```
When this happens, installation/update doesnt fail completly. In case if installing for example, plugin will be added to `vendor`, just listed as "not installed" on plugin list.

My system info, of craft install that gets these errors:

```
PHP version	7.2.11
Database driver & version	MySQL 5.6.12
Image driver & version	GD 7.2.11
Craft edition & version	Craft Solo 3.0.30
Yii version	2.0.15.1
Twig version	2.5.0
Guzzle version	6.3.3
Imagine version	0.7-dev
```

My composer.json file:

```
{
  "require": {
    "craftcms/cms": "3.0.30",
    "vlucas/phpdotenv": "^2.4.0",
    "nystudio107/craft-seomatic": "3.1.26",
    "mmikkel/cp-field-inspect": "1.0.5",
    "superbig/craft3-mobiledetect": "1.0.1",
    "craftcms/redactor": "2.1.6",
    "benjamminf/craft-embedded-assets": "1.0.2",
    "clubstudioltd/craft-asset-rev": "v6.0.1",
    "verbb/super-table": "2.0.11",
    "doublesecretagency/craft-smartmap": "3.1.3",
    "nystudio107/craft-retour": "3.0.17",
    "charliedev/element-map": "1.2.1",
    "topshelfcraft/wordsmith": "3.0.4",
    "verbb/image-resizer": "2.0.4",
    "enupal/translate": "1.1.3",
    "sebastianlenz/linkfield": "1.0.15",
    "craftcms/contact-form": "2.2.2",
    "lukeyouell/craft-contactformtemplates": "1.0.1",
    "craftcms/contact-form-honeypot": "1.0.2",
    "rias/craft-position-fieldtype": "1.0.14",
    "lukeyouell/craft-queue-manager": "1.0.0"
  },
  "autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  },
  "config": {
    "optimize-autoloader": true,
    "platform": {
      "php": "7.0"
    }
  },
  "scripts": {
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ]
  }
}

```

**Comment by angrybrad** [comment]
This is because your environment/host is setup to redirect to a hard-coded "500.shtml" file (which isn't a Craft file) when a 500 Internal Server Error occurs, in your case likely the result of a fatal PHP error because of a php.ini `memory_limit` and/or `max_execution_time` setting that is too low. Try setting those to `256M` and `120` respectively.

**Comment by Johnsalzarulo** [comment]
@angrybrad - trying these tips to solve my issues over on #3451 - Where do I set this memory limit? I just searched my whole repo for `memory_limit` and a `php.ini` file and I can't find any of this. I think my issue is I'm not experienced at all in `Apache` or `MAMP` - I've only worked with Rails / Node in the past. I'm really struggling to find any good docs or info on localhost config.

**Comment by angrybrad** [comment]
@Johnsalzarulo looks like you got sorted over in the other GH issue.
