### ISSUE TITLE
Feature Request: Add button to open currently edited element in inline element editor in a new tab

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#3448]
### Description
The inline element editor when you double-click a relation field is no-doubt a huge benefit; however, it can actually be a bit of a sore spot if a client is trying edit a particularly complicated field layout in the inline editor and feeling constrained. Adding a button to the top of the editor to open the element edit page in a new tab seems like an easy and reasonable solution. Of course, the inline editor would need to close when you click this link to prevent overwriting content when they're done. Ideally, this window would automatically close when the element is saved. I'm imaging just utilizing the UI for the title bar shown when in multi-site/language mode and adding an edit icon.

### Additional info

- Craft version: 3.x

**Comment by davidhellmann** [comment]
The inline editing is great. But it would be nice if the modal not that small. Why not like a paper stack and width: calc(100% - ($layerLevel * 2rem))

that is much better as the current small modal and also better (IMO) as edit in a separate tab.

**Comment by mmikkel** [comment]
I've been thinking/hoping for a long time that those tiny modals would some day be replaced by something more like panes, inline tabs (or a paper stack-like thing).

**Comment by brandonkelly** [comment]
@mmikkel that’s the plan for 3.6 ;)

**Comment by brandonkelly** [comment]
This is resolved for 3.7! See #8017.
