### ISSUE TITLE
Inconsistent Results from Asset Indexing (w/ nginx+fpm)

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#3450]
You will end up with certain items not indexed, and the message at the end prompting you for missing files that are actually there.

`maxConcurrentActions: 3` in the js is the culprit: https://github.com/craftcms/cms/blob/develop/src/web/assets/assetindexes/dist/AssetIndexesUtility.js#L191

Because of the way the indexer steps through the `assetindexdata`, it doesn't really jive with any sort of concurrency.

This may only be apparent when you are running nginx+php-fpm, as request are handled in a pool, so there is no guarantee of synchronous execution.

A good reason to bump https://github.com/craftcms/cms/issues/2980 to the top of the 3.x list if you ask me :)

**Comment by timkelty** [comment]
@andris-sevcenko this is definitely still an issue, please reopen.

The `index-assets/one` cli command works consistently and as expected.
The web utility indexes inconsistently.

Screencast of web utility/CLI: https://drive.google.com/file/d/1p-neAYKnaPrS7X6Ugz24k2-Grm3d0Drz/view

Related: https://github.com/craftcms/cms/issues/2876

**Comment by andris-sevcenko** [comment]
@timkelty any chance of getting the CP access to the site? support@craftcms.com, as usual!

**Comment by timkelty** [comment]
Thanks @andris-sevcenko 

For anyone else finding this thread, having a centralized `session`component (`\yii\redis\Session`) was what triggered this behavior.
