### ISSUE TITLE
Global Asset Fields not displaying thumbnails and unresponsive after 3.0.30.1 patch

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#3452]
### Description
Since applying the 3.0.30.1 patch **global** asset fields (in a multisite setup) are not displaying thumbnails and are unresponsive (can't click to delete the asset or upload a new one).

*Note that **entry** asset fields appear to be unaffected.

### Steps to reproduce

1. Create an image asset field - set to "Manage relations on a per-site basis"
2. Add the field to a global layout (on a multisite setup)
3. View the globals section and click on the asset upload field - field is unresponsive.

*Note that the volume for the asset field is using "@web/" and "@webroot/" for the Base Url and File System Path" respectively.

I have verified the above on latest versions of Chrome and Safari. In my specific setup I have tabs for my global layout and the asset fields in question are within the third tab.

<img width="497" alt="3452" src="https://user-images.githubusercontent.com/2505643/48168888-3e2a2c80-e345-11e8-87f7-7a53118c2a49.png">

### Additional info

- Craft version: 3.0.30.1
- PHP version: 7.2

**Comment by andris-sevcenko** [comment]
@richhayler I'm not able to reproduce this. Are you getting any javascript errors in your browser's console?

**Comment by richhayler** [comment]
So sorry for the very tardy response! You were right I took a closer look at its a javascript error caused by the ColorIt plugin that this blocking the rendering of this field. I will log the bug with FruitStudios. Apologies for not looking into this deeper myself. Thanks

**Comment by richhayler** [comment]
[https://github.com/fruitstudios/craft-colorit/issues/8](url)

**Comment by brandonkelly** [comment]
Thanks for looking into it further!
