### ISSUE TITLE
array_column broken in PHP 7.0.32, breaks services/Plugins.php

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#3453]
### Description

As part of `services/Plugins.php`, it does the following:

```php
        // Sort plugins by their names
        $names = array_column($this->_plugins, 'name');
        array_multisort($names, SORT_NATURAL | SORT_FLAG_CASE, $this->_plugins);
```
https://github.com/craftcms/cms/blob/develop/src/services/Plugins.php#L236

`array_column()` is apparently broken on PHP 7.0.32, and possibly earlier, since the change list for PHP 7.0.32 is pretty sparse: http://php.net/ChangeLog-7.php

It just returns an empty array here, which then causes `array_multisort()` to throw an exception, since the arrays of of a different length.

@engram-design wrote this alternate code, which causes it to work fine:

```php
// Sort plugins by their names
$names = [];
foreach ($this->_plugins as $plugin) {
   $names[] = $plugin->name;
}
```

### Steps to reproduce

@engram-design narrowed it down to a simple test case:

```
$class = new \stdClass();
$class->name = 'Test';
var_dump($class);

$names = array_column([$class], 'name');
var_dump($names);

// Produces:
object(stdClass)#769 (1) { ["name"]=> string(4) "Test" }
array(0) { }
```

### Additional info

- Craft version: 3.0.30.1
- PHP version: 7.0.32

Submitted PHP bug: https://bugs.php.net/bug.php?id=77119

**Comment by engram-design** [comment]
See also https://bugs.php.net/bug.php?id=77119

**Comment by marionnewlevant** [comment]
Exactly the same thing *was* happening to me, but it has also mysteriously stopped. I think something was done to the php install, but I'm not sure what. It is still reporting 7.0.32

**Comment by brandonkelly** [comment]
We just released 3.0.30.2 with a fix for this.

**Comment by djAjax** [comment]
The same issue in 7.0.33

**Comment by brandonkelly** [comment]
@djAjax where? the particular array_column() call this issue is about has been updated. Can you post a new issue, and include a stack trace pulled from your log files in `storage/logs/`?
