### ISSUE TITLE
Running into an issue trying to delete a category from the list view

### ISSUE THREAD

**Issue by eric-chantigny** [craftcms/cms#3456]
### Description

Anytime I try to delete a first level category from the listing view that has childrens, I get this SQL error.  If I delete another level (childrens or not), it deletes fine.  Deleting all childrens, I can then delete the first level.

```
{"error":"SQLSTATE[22003]: Numeric value out of range: 1690 BIGINT UNSIGNED value is out of range in '(`aos_chatbot`.`structureelements`.`level` - 3)'
The SQL being executed was: UPDATE `structureelements` SET `level`=`level`-3, `dateUpdated`='2018-11-08 21:04:00' WHERE ((`lft` >= 19) AND (`rgt` <= 20)) AND (`root`=1)"}
```

### Steps to reproduce

1. Create a multi-level category structure
2. Try to delete the first level when it has childrens in the list view

### Additional info

PHP version | 7.2.1
MySQL 5.6.38
Imagick 3.4.3 (ImageMagick 6.9.6-2)
Craft Solo 3.0.30.2

Feed Me | 3.0.0-beta.26

**Comment by naboo** [comment]
I can confirm this issue still exists, running Craft 3.1.18.

Its related to how the tree deletes. When the SQL runs and parent entries within the tree has been removed Craft fires this error message (when reaching a child in which the parent has been previously removed):

```PDOException: SQLSTATE[22003]: Numeric value out of range: 1690 BIGINT UNSIGNED value is out of range in '(`dev_db`.`structureelements`.`level` - 2)' in /srv/users/dev/apps/dev/vendor/yiisoft/yii2/db/Command.php:1290 Stack trace:```

Example SQL:
```UPDATE `structureelements` SET `level`=`level`-2, `dateUpdated`='2019-04-02 07:16:12' WHERE ((`lft` >= 17) AND (`rgt` <= 18)) AND (`root`=23)```

**Comment by naboo** [comment]
Also, it seems that you need more then 2-3 levels for it to give the error. Using just 1-2 levels seem to work (from what I can tell).

**Comment by brandonkelly** [comment]
@naboo Can you send me your composer.json and composer.lock files, plus a database backup, and point me to a category that will cause this error if I delete it?

**Comment by eric-chantigny** [comment]
I'll send you my DB soon @brandonkelly .  I just tried it again and it looks like it does it when you have a few levels and try to delete a tree from the listing.

- one
-- two
--- three
---- four

Try to delete all those from the listing.

**Comment by eric-chantigny** [comment]
Actually @brandonkelly, in 3.1.20.1, it's not happening anymore for me.

**Comment by naboo** [comment]
@brandonkelly sorry for the late reply. I just tried updating to Craft CMS 3.1.22 (as @eric-chantigny did) and that also solved the issue for me.

**Comment by brandonkelly** [comment]
Cool, thanks for checking! Closing this now.

**Comment by clieee** [comment]
I'm getting this error when trying to delete entries in a structure. Select all for example will give me this error.

**Comment by brandonkelly** [comment]
@clieee If you are running something less than 3.1.22, try updating. Otherwise please send a database backup and `composer.json` and `composer.lock` files over to support@craftcms.com.

**Comment by brandonkelly** [comment]
I was able to reproduce this locally and got it fixed for the next release.
