### ISSUE TITLE
Trim whitespace on user submission for email host name

### ISSUE THREAD

**Issue by KatieMFritz** [craftcms/cms#3459]
### Description

I just spent a while troubleshooting SMTP email setup, when part of my problem was that I had pasted a trailing space at the end of my host name. It would be cool if that field automatically trimmed whitespace at the start or end of the string. I can't think of a case where whitespace would be needed - can you?

### Steps to reproduce

1. Paste host name with trailing space that you don't notice.
2. Troubleshoot fruitlessly for a while.
3. Think "what if there's a trailing space?"
4. Discover trailing space and delete it.
5. Successfully send test email.
6. Ask Craft to save future devs from this cycle.
😘 

![screen shot 2018-11-09 at 12 23 00 pm](https://user-images.githubusercontent.com/7085184/48278008-515afc00-e41a-11e8-81b9-674940f56554.png)

### Additional info

- Craft version: 3.0.30.2

**Comment by brandonkelly** [comment]
Thanks for the suggestion. Done for tomorrow’s release!
