### ISSUE TITLE
Category creation issue when using level parameter in URI

### ISSUE THREAD

**Issue by sweetsixteen** [craftcms/cms#3465]
### Description

Not sure if it's a bug, or normal behavior:

I  have a 2-level category group,for which I'd like the URL to look like this:
- If first level: **topics/level1_slug**
- If second level: **topics/level1_slug/level2_slug**

I declared the Category URI format as:
`{%if level == 1 %}topics{% else %}{parent.uri}{% endif %}/{slug}`

That works perfectly for existing categories. But if I try to create a new category, I get the following error:

> Twig Runtime Error – Twig_Error_Runtime
> Variable "level" does not exist in ...

Which seems understandable, but quite annoying: I need to test this case within the URI format:
`{% if level is not defined %}topics{% elseif level == 1 %}topics{% else %}{parent.uri}{% endif %}/{slug}`

Is it the normal behavior? Is there a better way to handle this case?

### Additional info

- Craft version: 3.0.30.2
- PHP version: 7.0.32
- Database driver & version: MySQL 5.7.24

**Comment by brandonkelly** [comment]
Reason is that `level` isn’t defined until after the category has been saved, when it is added to the hierarchy, though we may be able to add some code to fake it.

You can also just do this instead:

```
{parent.uri ?? ‘topics’}/{slug}
```

**Comment by brandonkelly** [comment]
Turns out there was already some code in place to preemptively set the `level` attribute for new entries and categories, but it wasn’t working correctly. Fixed for today’s release!
