### ISSUE TITLE
Asset File System Path outside of project director

### ISSUE THREAD

**Issue by mrjacobfisher** [craftcms/cms#3468]
This is as much a question as it is an issue. I'm in development of a site where I'd like store the files for an asset source outside of the root folder of the project – in a different root directory on the server. Digital Ocean mounts Block / Scalable volume storage at the root of the droplet, and I'd like to use this volume storage for storing assets.

My current asset source configuration looks like this:
Name: `Main`
Handle: `main`
Base Url: `@web/uploads`
File System Path: `/mnt/volume-sfo2-02/[redacted]`

Am I correct in assuming this should be possible? I am able to upload assets using this configuration (they are added to the server and I can see the files), but I get 404 errors when I try to access them in the browser.

**Comment by brandonkelly** [comment]
As long as the path is accessible (which it sounds like it is), then yes it’s possible. 404 errors in the browser indicate that your Base URL is incorrect. `@web` is an alias to the URL of the folder containing `index.php` (usually your web root). If you want the asset URLs to begin with that + `uploads/`, then you will need to create a symlink from `web/uploads` to the actual folder path. Or use the base URL provided by DO for the mount.

**Comment by mrjacobfisher** [comment]
This is great. Thank you. I suspect the symlink will take care of the issue.

Thanks for building Craft, too. I love working with it!
