### ISSUE TITLE
Fieldset changes on volumes aren't passed on to existing assets.

### ISSUE THREAD

**Issue by roelvanhintum** [craftcms/cms#3469]
### Description
When changing the fieldset on a volume the existing assets aren't resaved and are missing fields as a result. Saving an asset by hand does solve the issue for that asset.

### Steps to reproduce

1. Create a volume
2. Upload asset to volume
3. Add a field to the volume's fieldset
4. Go the edit mode of the asset, where the new field should be visible

### Additional info

- Craft version: 3.0.31
- PHP version: 7.1.20
- Database driver & version: MySQL 5.7.22
- Plugins & versions:
-- Asset Usage	2.0.0-beta.2
-- Color Extractor	2.0.0-beta.5
-- Element API	2.5.4
-- Linkit	1.1.4
-- Migration Manager	dev-master
-- Rackspace Cloud Files	1.0.5
-- Redactor	2.1.6
-- Sentry	1.4.1
-- SEO	3.4.4
-- Snitch	2.0.2
-- Super Table	2.0.14
-- Tags	1.0.1
-- Two-Factor Authentication	2.0.0-beta.13
-- Webtexttool	1.0.2

**Comment by andris-sevcenko** [comment]
I'm not able to reproduce this locally. Also, field layouts are stored on a per-volume basis, not on a per-asset basis, so re-saving an asset should not change anything.

Is this on a site where we can get access? If so, can you send it over to support@craftcms.com?

**Comment by roelvanhintum** [comment]
This was solved by updating the asset indexes. The Rackspace volume did contain 4216 assets, does this influence behavor? I did a local storage test with one asset and it didn't had any issues.
