### ISSUE TITLE
Missing site indicator on entry edit form

### ISSUE THREAD

**Issue by michaelhue** [craftcms/cms#3471]
### Description

Inside a multi-site setup with non-propagating sections, there is no indication which site is currently active while editing an entry.

When creating a new entry a dropdown shows the currently selected site and even allows changing it. (Figure 1)

![Figure 1](https://user-images.githubusercontent.com/31861/48624674-546f6280-e9ad-11e8-9b97-781e260588cb.png)
_**Figure 1.** New entry header_
 
When editing an entry there is no site indicator. (Figure 2)

![Figure 2](https://user-images.githubusercontent.com/31861/48624683-5a654380-e9ad-11e8-82d1-bb5efbad6bcc.png)
_**Figure 2.** Editing entry header._

It would be great to at least be able to see which site the entry belongs to. Currently it's very easy to get confused about which site I'm editing.

### Steps to reproduce

1. Have at least two different `Sites`.
2. Have a `Section` (channel or structure) with entry propagation _turned off_.
3. Create and save a new `Entry` in the `Section`.
4. Notice the name of the currently selected `Site` is displayed at the top. (Figure 1)
5. Open the newly created `Entry` again.
6. Notice that there is no way to tell on which `Site` the `Entry` is published. (Figure 2)

### Additional info

- Craft version: Craft Pro 3.0.31

**Comment by brandonkelly** [comment]
Good point. Fixed for tomorrow’s release!
