### ISSUE TITLE
Running command "craft migrate/fresh" throws Exception 'yii\base\NotSupportedException'

### ISSUE THREAD

**Issue by pablofernandezgh** [craftcms/cms#3472]
### Description
Running command "craft migrate/fresh" throws Exception 'yii\base\NotSupportedException' with message 'This command is not implemented in craft\console\controllers\MigrateController' 

### Steps to reproduce

1. run ./craft migrate/fresh

**Comment by brandonkelly** [comment]
Fixed for tomorrow’s release. Thanks for reporting!
