### ISSUE TITLE
Control panel structure. Can't create new entry within an structure. Change nesting not working

### ISSUE THREAD

**Issue by jlachancekffein** [craftcms/cms#3476]
### Description
A specific structure seem to been broken. On new entry creation, the error : **Can not create a node when the target node is new record.** is shown.

The only solution is to set a parent entry to the current entry. After, we can remove the parent and it work.

Another problem, is when we try to change the order or the nesting of the entries on the listing page, the change seem to be ok, but on reload page, the nesting is broken. By example, childrens become at level -1 (lower that the most basic level).

We cannot move an entry to be the first item of the section by drag/drop in the listing view. Error is shown at the top of the CP panel.

I try to create a new structure section, and update the entries related to the broken structure, but the problem persist in the new section.

What we think is the the cause of the problem, is the fact that our client put to trash a parent entry before moving the child entry.

Is it a way to clean a structure section (reset all parents childrens, etc) to prevent this problem ?

It's difficult to explain the problem without access to the CP. If you need, we could create an user with right for this section to debug the problem.

### Steps to reproduce

1. Create a new entry on the broken section without parent entry
2. Error is thrown : Can not create a node when the target node is new record.
3. Create a new entry with an parent
4. New entry is created correctly
5. Try to move the new entry to the first item of the section in the listing with drag/drop, error alert is shown
6. Try change nesting or order of entries. Save without error, but reload the page show that it not working correctly

### Additional info

- Craft version: Craft CMS 3.0.31
- PHP version: 7.2.3
- Database driver & version: mysql

![image](https://user-images.githubusercontent.com/24896469/48714983-ecee2880-ebe1-11e8-8806-42fc5400ce85.png)

![image](https://user-images.githubusercontent.com/24896469/48715098-376fa500-ebe2-11e8-815c-fcaaba472748.png)

**Comment by brandonkelly** [comment]
Can you please email your `composer.json` and `composer.lock` files, as well as a database dump, over to support@craftcms.com? Otherwise not going to be possible for us to reproduce and look into this.
