### ISSUE TITLE
Restricting Matrix loop to blocks of certain type is also being applied to cosequent calls

### ISSUE THREAD

**Issue by intoeetive** [craftcms/cms#3477]
### Description

If you loop through Matrix field and only need to display blocks of certain type, and you chain block type parameter to {% for %} loop, it displays only blocks of that type, which is correct.

But if afterwards in same template you want to display all blocks from same field (irrespective of type), you will still get only blocks of the type to which you restricted in first place.

### Steps to reproduce

1. Create Matrix field 'someMatrixField' with several block types, e.g. 'one', 'two' and 'three'
2.  Loop through Matrix field blocks, restricting call to only blocks of certain type
    ```twig
    {% for block in entry.someMatrixField.type('one').all %}
      -{{ block.id }}
    {% endfor %}
    ```
3. Later in template, loop through the same field without restriction
    ```twig
    {% for block in entry.someMatrixField.all %}
      -{{ block.id }}
    {% endfor %}
    ```
4. The output is same

### Additional info

- Craft version: 3.0.31
- PHP version: 7.1.12
- Database driver & version: MySQL 5.5.58
- Plugins & versions: SuperTable

**Comment by brandonkelly** [comment]
This is intended behavior in Craft 3. The change compared to Craft 2 is explained here: https://docs.craftcms.com/v3/changes-in-craft-3.html#element-queries

To workaround it, use the [clone()](
https://docs.craftcms.com/v3/dev/functions.html#clone-objec) function in step 2:

```twig
{% for block in clone(entry.someMatrixField).type('one').all() %}
  -{{ block.id }}
{% endfor %}
```
