### ISSUE TITLE
clearing cached hasCpSection value for custom plugin

### ISSUE THREAD

**Issue by davefischoff** [craftcms/cms#3479]
### Description
I ran into an issue with a custom plugin I'm developing where the `hasCpSection` value was originally set to `false`, but re-setting it to `true` did not result in a cp section showing for the plugin, even after uninstalling and reinstalling the plugin, building a new `composer.lock` file and clearing all caches via the Utilities tab. Eventually, I tracked down a cached value of `false` for my plugin's `hasCpSection` in 
Craft's `plugins.php` file. I deleted the cached value from this file and added `public $hasCpSection = true;` to my plugin's main PHP file (instead of adding it to the plugin's `composer.json`), and the cp section worked.

My issue has been resolved, but I wanted to leave this here to point out that there doesn't seem to be an easy way to remove a cached `hasCpSection` value for a plugin from Craft's `plugins.php` file. This Stack Exchange post is another example of someone running into the issue (and the answer helped me resolve my issue): https://craftcms.stackexchange.com/questions/26384/remove-a-control-panel-section

### Steps to reproduce

1. In a custom plugin's `composer.json` file, set `"hasCpSection": false` in `"extra"`.
2. After installing plugin, try to change the setting to `"hasCpSection": true`
3. the custom plugin retains a `"hasCpSection": false` value, despite uninstalling and reinstalling the plugin, clearing all caches and building a new `composer.lock` file.

### Additional info

- Craft version: Craft Pro 3.0.26.1
- PHP version: 7.2.6
- Database driver & version: MySQL 5.6.40
- Plugins & versions: custom plugin, version 1.0.0

**Comment by brandonkelly** [comment]
Yeah this is a known issue with `path` Composer repositories – see the warning at the bottom of this section in the docs: https://docs.craftcms.com/v3/extend/plugin-guide.html#path-repository
