### ISSUE TITLE
Craft::$app->request->getQueryParam('query') returns NULL

### ISSUE THREAD

**Issue by clarknelson** [craftcms/cms#3480]
### Description

The code `Craft::$app->request->getQueryParam('query')` returns null in PHP, while returning the expected value in Twig.

### Steps to reproduce

1. Test the previous statement inside of an element api config or similar PHP script.

### Additional info

- Craft version: 3.0.31
- PHP version: 7.2.10
- Database driver & version: Mysql 5.7.20
- Plugins & versions: Element API 2.5.4

**Comment by brandonkelly** [comment]
`craft.app.request.getQueryParam()` in Twig is the exact same function as `Craft::$app->request->getQueryParam()`, so there’s no chance that they would act inconsistently, unless the query string itself is inconsistent.

**Comment by clarknelson** [comment]
Yeah that's what I thought too, but here is my code:

![screen shot 2018-11-21 at 9 14 42 am](https://user-images.githubusercontent.com/4106671/48850563-982be880-ed6e-11e8-9ae5-12e00639c685.png)

![screen shot 2018-11-21 at 9 19 07 am](https://user-images.githubusercontent.com/4106671/48850583-a24de700-ed6e-11e8-866b-9ee5115297e7.png)

![screen shot 2018-11-21 at 9 17 03 am](https://user-images.githubusercontent.com/4106671/48850592-a67a0480-ed6e-11e8-954e-2b1cdf119e5c.png)

![screen shot 2018-11-21 at 9 16 27 am](https://user-images.githubusercontent.com/4106671/48850598-a843c800-ed6e-11e8-9e94-2c2b988da351.png)

The only thing I can think of is my AJAX call is incorrect. But the code to get to search query in the element API seems to never work because it always returns the same 9 values (every portfolio entry)

**Comment by brandonkelly** [comment]
Your Element API endpoint is a separate request from the template request, with its own query string. Looking at your JS code, you’re just sending the ajax request to `/portfolio.json` without any query string.

Try changing that `$.get()` line to:

```javascript
$.get("/portfolio.json?query="+val, function( data ) {
```

**Comment by clarknelson** [comment]
oh dang... thank you so much for your time and assistance
