### ISSUE TITLE
FR: Expose yii\log\Target::logVars to Craft config

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#3486]
Craft tries to redacts sensitive info, but it isn't bulletproof.

Would be nice if this could be set via GeneralConfig, so one could set it via multi-env config.

**Comment by timkelty** [comment]
FWIW: What got me down this road was when I realized there is no "force" param for logging like there was in Craft 2. I wanted to log some info in production (devMode=false), but using `Craft::warning` just to force it to log feels weird.

_Then_ I realized logging dumps the $_ENV no matter what log level…

Later I had a client's IT dept freak out when they saw the ENV dump in logs on a production box.

**Comment by brandonkelly** [comment]
You can customize the list of keywords that Craft looks for when redacting sensitive info by overriding [craft\services\Security::$sensitiveKeywords](https://docs.craftcms.com/api/v3/craft-services-security.html#property-sensitivekeywords) from `config/app.php`:

```php
return [
    'components' => [
        'security' => [
            'sensitiveKeywords' => [ /* ... */ ],
        ],
    ],
];

**Comment by brandonkelly** [comment]
…and as of the next release, when you override `sensitiveKeywords` there, the keywords you add will be _appended_ to the default value.

**Comment by timkelty** [comment]
Lovely, thanks @brandonkelly!
