### ISSUE TITLE
Add a detail button to see failed queue job error

### ISSUE THREAD

**Issue by riasvdv** [craftcms/cms#3489]
### Description

It would be great to have a "detail" button between the "retry" and "cancel" buttons on a queue job to see what went wrong.

**Comment by brandonkelly** [comment]
We’ve added a new Queue Manager utility for Craft 3.4, and jobs have a details view that reveals the error that caused a job to fail:

![A failed job’s details view within the Queue Manager utility in Craft 3.4)](https://user-images.githubusercontent.com/47792/71935184-08f0b880-315b-11ea-9084-cc360e0fa0b0.png)
