### ISSUE TITLE
Incompatible declaration error when trying to connect to CraftID via plugin store

### ISSUE THREAD

**Issue by Tam** [craftcms/cms#3491]
### Description
```
Declaration of 
craftcms\oauth2\client\provider\CraftId::getResourceOwnerDetailsUrl(League\OAuth2\Client\Token\AccessToken $token) 
must be compatible with 
League\OAuth2\Client\Provider\AbstractProvider::getResourceOwnerDetailsUrl(League\OAuth2\Client\Token\AccessTokenInterface $token)
```

### Steps to reproduce

1. Go to plugin store in Craft CP.
2. Click "Sign into Craft ID" in the top right.
3. Error above is thrown.

### Additional info

- Craft version: Craft Pro 3.0.32
- PHP version: 7.2.8
- Database driver & version: PostgreSQL 9.5.14
- Plugins & versions:

Name | Version
-- | --
Blitz | 1.7.1
Bookings | 1.0.0-alpha.17
Contact Form | 2.2.3
Contact Form Extensions | 1.0.11
Craft Commerce | 2.0.0-beta.13.1
Entry Instructions | 1.0.4
Gift Voucher | 2.0.3
Imager | v2.1.1
Minify | 1.2.9
Position Fieldtype | 1.0.14
Redactor | 2.1.6
SagePay for Craft Commerce | 1.1.0
SEO | 3.4.4
SimpleMap | 3.3.4
Super Table | 2.0.14
Typed link field | 1.0.15

**Comment by brandonkelly** [comment]
Looks like this was an unintentional BC break in the OAuth 2 client (league/oauth2-client#752), which was [fixed](https://github.com/thephpleague/oauth2-client/commit/bb12ba558b0e41b25aeb92e3ca989a8aa404c424) in v2.4.1.

If you run `composer update` the error should go away. And I’ll have the next Craft release explicitly avoid that 2.4.0 version.
