### ISSUE TITLE
How to handle deep nested data inside the CMS

### ISSUE THREAD

**Issue by Hyra** [craftcms/cms#3493]
We have a project which consists of a lot of 'TV' related data.

The structure is:

Programs
    Seasons
        Episodes
             Fragments

In Craft this works fine, of course. Programs is a structure, and Seasons, Episodes and Fragments are Channels.

However, since Seasons (and episodes) often have the same titles, it's really hard for the client to find the right item to edit.

I also tried moving everything into a Structure, where everything gets nested nicely, but if you then search for a specific program then it only shows the top level (Programs) and hides all subentries.

Is it possible to have Craft show all the descendants as well when searching inside a structure?

**Comment by brandonkelly** [comment]
It’s probably better to have everything split up into multiple sections like you had it.

I’m assuming the following:

- Seasons entries have a “Program” (`program`) Entries field to choose which program the season is for
- Episodes have a “Season” (`season`) Entires field to choose which season the episode is for
- Fragments have an “Episode” (`episode`) Entries field to choose which episode the fragment is for

If any of those are wrong then the technical details of my answer may need to change, but the gist will be the same.

---

That said, to give authors more context on which entry they should be editing, you can take one of these approaches:

- Add the “parent” field (Program, Season, or Episode depending on the section) as a new column on the section’s table on the Entries index page. (Click the cog icon below all the sections in the sidebar to change the visible table columns.)

- Create a custom “Name” (`name`) Plain Text field, and add it to the Seasons, Episodes, and Fragments sections’ entry types, and use it to store the actual season/episode/fragment titles. Once the Name fields are all filled in, re-edit the entry types and give them these entry title formats:

  ```twig
  {# Seasons #}
  {program.one().title} - {name}

  {# Episodes #}
  {season.one().title} - {name}

  {# Fragments #}
  {episode.one().title} - {name}
  ```

  That way what shows up as entry titles will be a combination of the “parent” entry’s title plus the entry’s name. (e.g. `<Program Title> - <Season Name>`.)
