### ISSUE TITLE
Password reset sends mail without link

### ISSUE THREAD

**Issue by Rias500** [craftcms/cms#3495]
### Description

When requesting a password reset on a Dutch site (nl-BE), Craft sends an English email to reset a password.

This would be fine, but the email contains no actual link to reset the password.

![image](https://user-images.githubusercontent.com/3626559/48937904-d8769c80-ef0f-11e8-953c-0ac5e20328db.png)

### Steps to reproduce

1. Request a password reset
2. See mail without link

**Comment by brandonkelly** [comment]
What version of Craft are you on?

What are the details of the sites you’ve created (Selected languages and base URLs)?

Which site is the primary?

**Comment by angrybrad** [comment]
Debugged offline and can no longer reproduce the issue.
