### ISSUE TITLE
Create a new child entry with multiple sites bug

### ISSUE THREAD

**Issue by simonleadbetter** [craftcms/cms#3496]
### Description

When using the **Create a new child entry** from the Entries page with multiple sites, then Entry page defaults to the first site. 

### Steps to reproduce

1. Go to Structure on Entries page
2. Select an existing page
3. Choose Create a new child entry
4. The entry page won’t be on the selected site (if not the first one), but defaults to the first site in list

### Additional info

- Craft version: 3.0.32

**Comment by brandonkelly** [comment]
Thanks for pointing that out. Fixed for tomorrow's release!
