### ISSUE TITLE
Newly added Matrix blocks don't stay collapsed when the entry is saved

### ISSUE THREAD

**Issue by jasonmorehead** [craftcms/cms#3499]
### Description

When a new matrix block is added and then immediately collapsed, it doesn't stay collapsed when the entry is saved.

### Steps to reproduce

1. Add a new matrix block.
2. Fill out the block's fields.
3. Collapse the block using the "Collapse" option under the gear icon.
4. Save the entry to keep working on it. (I use Command + S.)

After the page has reloaded, the new block is still open. You have to collapse it and save the entry a second time for it to stay collapsed.

Note: This only seems to happen in Chrome and Safari. I haven't been able to replicate it in Firefox. I haven't tested in IE or Edge.

### Additional info

- Craft version: 3.0.32

**Comment by brandonkelly** [comment]
Thanks for reporting. Fixed for the next release.
