### ISSUE TITLE
Issue creating single on v3.1.0-v2 using project config

### ISSUE THREAD

**Issue by mediabeastnz** [craftcms/cms#3506]
### Description
I got an error on a fresh install of version 3.1.0-v2 when creating a single. I was creating a home page so it had no slug. The error that gets returned on save is:

```php
// array_keys() expects parameter 1 to be array, null given
// in /home/vagrant/Code/craft/vendor/craftcms/cms/src/services/Sections.php at line 1505
$allSiteUids = array_keys(Craft::$app->getProjectConfig()->get(self::CONFIG_SECTIONS_KEY . '.' . $section->uid . '.siteSettings'));
```

### Steps to reproduce

1. install version 3.1.0-v2
2. ensure project config is enabled
3. create new single section (home)
4. save section

### Additional info

- Craft version: 3.1.0-v2
- PHP version: 7.2.1
- Database driver & version: mysql 5.7

**Comment by brandonkelly** [comment]
Thanks for reporting that. Fixed for the next release!
