### ISSUE TITLE
Array to string conversion error on System Report page

### ISSUE THREAD

**Issue by mcjackson18** [craftcms/cms#3507]
### Description
The /admin/utilities/system-report page gives an "Array to string conversion" error. It looks like it's linked to this update -https://github.com/craftcms/cms/commit/d515bf007c9849c47111ea4a5d332f3c21cbf4d6

- Craft version:  3.0.33

**Comment by mcjackson18** [comment]
Update: adding the module to the bootstrap array in config/app.php resolves the issue but using an empty bootstrap array `'bootstrap' => []` when you have a module installed gives the Array to string conversion error.

**Comment by brandonkelly** [comment]
I was able to reproduce this if I configured a module using an array rather than a string of the class name:

```php
'modules' => [
    'my-module' => [
        'class' => MyModule::class,
    ],
],
```

Fixed for the next release.

If you don’t have a need to use an array here, switching to a string will workaround the issue in the meantime.

```php
'modules' => [
    'my-module' => MyModule::class,
],
```
