### ISSUE TITLE
Error on Arabic language when entry has post date 

### ISSUE THREAD

**Issue by onemoreahmad** [craftcms/cms#3509]
### Description
If the user changed his preference language to **Arabic**, he gets an error when he try to open any entry has a post date.

### Steps to reproduce

1. Publish any entry
2. Change language to Arabic 

### Additional info

- Craft version: Craft Pro 3.0.33
- PHP version: 7.2.9

I think the error has to do with Arabic language file for the craft itself or maybe datepicker javascript library (?)
`vendor/craftcms/cms/lib/datepicker-i18n/datepicker-ar.js`
Have no idea.

<img width="625" alt="screen shot 2018-11-30 at 5 17 13 pm" src="https://user-images.githubusercontent.com/1885785/49294798-08501200-f4c5-11e8-8f1d-6dec1da4b15c.png">
Entries have postDate NULL work fine, other don't

<img width="330" alt="screen shot 2018-11-30 at 5 17 23 pm" src="https://user-images.githubusercontent.com/1885785/49294800-08501200-f4c5-11e8-9fe9-5efff318e068.png">
<img width="1616" alt="screen shot 2018-11-30 at 5 17 56 pm" src="https://user-images.githubusercontent.com/1885785/49294801-08501200-f4c5-11e8-843a-9bcd60e1f0fd.png">

**Comment by brandonkelly** [comment]
This should be fixed for the next release. I wasn’t able to reproduce your exact error (the page loaded fine, but I got a JavaScript error on it). So if you can test it yourself, I’d appreciate it.

You can get the fix by opening your composer.json file and changing your `craftcms/cms` requirement to `dev-develop`:

```json
"require": {
  "craftcms/cms": "dev-develop as 3.0.33",
  "...": "..."
}
```

Then run `composer update`.

**Comment by onemoreahmad** [comment]
Thank you @brandonkelly for the quick response , changing craft version and updating composer fixed the problem.
