### ISSUE TITLE
Craft 3.1.0-beta3 - Project sync console command

### ISSUE THREAD

**Issue by smcyr** [craftcms/cms#3510]
### Description

Having a continuous integration system in place (Jenkins), there are some scripts that apply migrations automatically after deployments (`php craft migrate/all`). The `migrate/all` doesn't seem to sync the new project config file for Craft 3.1, so it would be nice to have a new command for sync to not be forced to do it manually via the control panel.

### Steps to reproduce

1. Do some changes to project.yaml
2. Run command `php craft migrate/all`
3. Go to control panel (/admin)
4. It asks you to sync changes

### Additional info

- Craft version: 3.1.0-beta3
- PHP version: 7.2

**Comment by brandonkelly** [comment]
I’d been meaning to add this. Thanks for the reminder!
