### ISSUE TITLE
Character Limit With Issue with Urdu Slugs

### ISSUE THREAD

**Issue by andrewfairlie** [craftcms/cms#3514]
### Description
In English, we're limited to 255 characters in a slug.

With Urdu, it seems to be significantly less and the error message isn't useful

> Could not generate a unique URI based on the URI format.

I suspect that this is because Urdu uses more bytes per character than ASCII characters.

### Steps to reproduce

1. Make a new entry with a very long Urdu title, for example "یہ ایک بہت طویل عنوان ہے یہ ایک بہت طویل عنوان ہے. یہ ایک بہت لمبی عنوان ہے. یہ ایک بہت لمبی عنوان ہے. یہ واقعی ایک طویل عنوان ہے. ایک بہت طویل عنوان یہ ایک بہت طویل عنوان ہے. یہ واقعی ایک طویل عنوان ہے"
2. Try to save, you'll see the error

More detail...

A long title

> یہ ایک بہت طویل عنوان ہے یہ ایک بہت طویل عنوان ہے. یہ ایک بہت لمبی عنوان ہے. یہ ایک بہت لمبی عنوان ہے. یہ واقعی ایک طویل عنوان ہے. ایک بہت طویل عنوان یہ ایک بہت طویل عنوان ہے. یہ واقعی ایک طویل عنوان ہے

Is 202 characters so should be sluggable, but because it's 354 bytes (https://mothereff.in/byte-counter) it seems to be disallowed.

Shorten that to 230 bytes (to allow a few bytes for dashes)...

> یہ ایک بہت طویل عنوان ہے یہ ایک بہت طویل عنوان ہے. یہ ایک بہت لمبی عنوان ہے. یہ ایک بہت لمبی عنوان ہے. یہ واقعی ایک طویل عنوان ہے. ا

And it'll work

### Additional info

- Craft version: Craft Pro 3.0.31
- PHP version: 7.2.12
- Database driver & version: MySQL 5.7.24

**Comment by brandonkelly** [comment]
There is a validation rule ensuring that slugs and URIs are <= 255 characters so they can fit into their `varchar` database columns, however the rule _should_ be looking at the _byte_ length rather than character count, so it gets triggered in cases like this where some characters are made up of more than one byte (your sample string is 354 bytes). I’ve fixed that for the next release. The validation error message is still a little misleading, but at least it will point you in the right direction.

<img width="361" alt="validation error on a Slug field stating that the slug must be at most 255 characters" src="https://user-images.githubusercontent.com/47792/49404599-c7ded700-f704-11e8-9256-e846249e1923.png">

**Comment by brandonkelly** [comment]
Take that back. Looking into this further, I was wrong and a `varchar(255)` column does actually just care that it’s 255 _characters_ and not 255 _bytes_.

So not totally sure if there’s a good course of action here for us to take. Reopening…

**Comment by brandonkelly** [comment]
One thing you can do is limit the length of the slug in your section’s URI Format. For example:

```
news/{slug[0:250])
```

**Comment by brandonkelly** [comment]
There was already code in place to auto-shrink slugs in order to get the URI down to <= 255 characters, but there were some logic bugs in the code. Fixed now for the next release.

**Comment by narration-sd** [comment]
Wow, that is a hot one, Brandon. I don't find any doc for this; should there be??

Was watching this one due to experience with languages needing longer sizes...not jumping in though...

**Comment by narration-sd** [comment]
Yeah, I understand -- but also understand from close up for years how much such things bite a multilingual environment. German itself is like 150% of English, still using Latin-1 characters.

The actual saving grace is probably the size of the field vs. generally reasonable slugs -- divided by 2 or 4...

Anyway, thanks for thinking, as ever, Brandon. And I'm having to think very carefully what complexity to present, in doc after reducing it as much as possible in the application, you know where. It's going to be the focus-group beta that determines in what form or whether this thing sensibly flies.  

You and Brad weren't wrong to think of the alternative of consulting it in, though I can't see how that path with open source would get me out of the hot seat of intense support, exactly -- though, just this moment am thinking again...maybe I missed a point, while falling into the gravitation of long perfecting ;)
