### ISSUE TITLE
[FR] Implement the QueueInterface as a Behavior

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#3518]
Just like Craft's `SessionBehavior` can be attached to the session handler, implement the `QueueInterface` as a `QueueBehavior` so that we can implement whatever queue method we like, such as `\yii\queue\redis\Queue::class` but still have the extra functionality added by P&T for the Craft Queue Jobs.

Would really love to see this, so that then I can replace the queue via `app.php`:

```
            'queue' => [
                'class' => \yii\queue\redis\Queue::class,
                'redis' => [
                    'hostname' => 'localhost',
                    'port' => 6379,
                    'database' => 3,
                ],
                'channel' => 'queue', // Queue channel key
            ],
```

...whilst still retaining the queue status display in the AdminCP, etc.

**Comment by brandonkelly** [comment]
There isn’t really any code in Craft’s `craft\queue\Queue` implementation of `QueueInterface` that could be abstracted away in a behavior. The interface itself is pretty simple. Just up to the queue driver to figure out how to store jobs in a way where the data needed by the interface can be known (which isn’t very easy to do for anything besides DB queues).
