### ISSUE TITLE
Lightswitch enabledForSite shows up only on creation when not propagating

### ISSUE THREAD

**Issue by HeleenE** [craftcms/cms#3519]
### Description

In a multi-site set up when a section is not propagating there are some issues with the two *Enabled* lightswitches. When you create a new entry, both lightswitches show up: *Enabled Globally* and *Enabled for [Site]*, but when you try to edit these later only the *Enabled Globally* lightswitch shows up. 

This causes some issues: 
• If you save with *Enabled for [Site]* disabled, once you go back to edit you'll only have access to *Enabled Globally*, so you can't enable *Enabled for [Site]*
• If you save with *Enabled for [Site]* enabled, once you go back to edit you'll only have access to *Enabled Globally*, so you can't disable *Enabled for [Site]*

This setting can be changed with the *Set Status* dropdown from the entries overview, although this isn't super clear, since there is only one *Enabled* option and there are two *Disabled* (globally and for site) options. 

### Steps to reproduce

1. Set up at least two sites in Craft
2. Create a section and enable it for both sites, but don't check the propagation checkbox
3. Make sure your newly created section has an entry type
4. Create a new entry in the section, notice how you have **two** *Enabled* lightswitches?
5. Edit the newly create entry, notice how you have only **one** *Enabled* lightswitch?

### Additional info

- Craft version: Craft Pro 3.0.33
- PHP version: 7.1.23
- Database driver & version: MySQL 5.7.22
- Plugins & versions: I don't think these are relevant, but here you go:
Advanced Url Field 1.0.0
Amazon S3 1.0.8
Contact Form 2.1.1
Control Panel CSS 2.1.0
Control Panel Nav 2.0.8
Element API 2.5.3
Expanded Singles 1.0.4
Feed Me 3.0.0-beta.16
Feed Me Pro 3.0.4
Field Manager 2.0.2
Geo Cookie 1.2.1
Redactor 2.1.0
Smart Map 3.1.0
Store Hours 2.0.6
Super Table 2.0.7

*Thanks to Slack user **bensomething** for helping me figure out what is going on*

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just fixed for the next release.

**Comment by HeleenE** [comment]
@brandonkelly Thanks for the quick fix! The overview still shows a 'Disabled for site' and 'Disabled Globally' option though. Not a big issue, but it might be nice to clean this up too.

**Comment by brandonkelly** [comment]
@HeleenE Good point. That has been fixed for tomorrow's release.
