### ISSUE TITLE
Error on assettransformindex table

### ISSUE THREAD

**Issue by Tyrannogina** [craftcms/cms#3521]
### Description

One of the records on `assettransformindex` table was saved in an invalid state, and that prevented any type of access to an Entry (an unpublished blogpost). It did not trigger errors, I wasn't able to find anything in the logs, just made the page stay 'loading' until at some point we were getting a 504 Gateway Time-out (so the Yii Debugger wasn't loading either).
By changing the database from this (no image name, fileExists = 0, inProgress = 1)
``` `347	6874	NULL	jpg	_1200x630__center-center_82_none	1	0	1	2018-12-04 11:36:10	2018-12-04 11:36:10	2018-12-04 17:33:59	ad74189f-8541-46ba-a66b-e318222e4d84```
to this (fake image name, fileExists = 1, inProgress = 0)
 ```347	6874	img.jpg	jpg	_1200x630__center-center_82_none	1	1	0	2018-12-04 11:36:10	2018-12-04 11:36:10	2018-12-04 17:33:59	ad74189f-8541-46ba-a66b-e318222e4d84```
the entry was loading normally again.

I believe this is related to an asset on the SEO tab of the entry, but I am not sure, as how it all relates on the DB is still a bit obscure to me.

### Steps to reproduce

I am not sure what information would you need me to provide to make this information more useful. Please ask for the information needed. 

My only issue with this is that it was really hard to find out what originated the error, as there's so many things that relate to an Entry, a timeout could be originated by almost anything. Just a clearer error message would have made this a lot less painful to fix.

### Additional info

- Craft version: 3.0.29
- PHP version: 7.1
- Database driver & version: mysql 5.7.22,
- Plugins & versions: "nystudio107/craft-seomatic": "^3.1" and some others that I doubt would be related.

**Comment by brandonkelly** [comment]
Generally a not-yet-generated transform won’t actually hold the page load up, as they get generated in separate requests. That may not be the case if you have the `generateTransformsBeforePageLoad` config setting enabled in `config/general.php`, in which case initial requests of entries can take longer while Craft is generating all of the transforms for it.

In any case, if there was a problem generating a transform, there should be an error either in `storage/logs/phperrors.log` or `storage/logs/web.log`. Though if the request is timing out, it could just be that for whatever reason GD or ImageMagick is taking an extremely long time to process the image. We’ve seen that happen with large PNG files, but from the looks of your table data this was a JPG.

The changes you made to the `assettransformindex` table probably aren’t a great idea… you’re telling Craft to remember that this particular transform is done being generated and its file exists, which probably isn’t accurate, so you’ll see 404 errors for the image on the front end. If you undo that change (or deleted the row) and are still experiencing issues, please contact support@craftcms.com and we can try to help you from there.

**Comment by Tyrannogina** [comment]
Yes, `generateTransformsBeforePageLoad` is set as true. I will check why. 

I will look into the size of the image were they using originally. 

I know modifying the record is not a good a good approach, just a way to verify the error was there. And because I don't know very well how transforms work, I didn't want to risk deleting the record before knowing if that could mess any possible dependency.

Thank you very much!
