### ISSUE TITLE
FR: Disable propagation of entries on Singles

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#3522]
### Description

The propagate entries toggle seems to only be available when using channels and now structures (https://github.com/craftcms/cms/issues/2386), is it possible to have this for Singles?

This would allow the use of the same Single on multiple sites, with different content per-site, and avoid work-arounds suggested here: https://craftcms.stackexchange.com/questions/24185/multi-sites-how-to-give-each-site-a-home-single-entry/24190#24190

**Comment by Takaya213** [comment]
I 2nd this, would like to be able to create eg a standard Terms and Conditions page layout that can be used across multiple sites as one single, but not have the content the same across all the sites.

**Comment by brandonkelly** [comment]
Single sections are by definition single-entry sections. You can choose which sections the entry should be available on from the section settings. Which means you have two options, depending on the needs:

- If each site needs has its own unique homepage content requirements, you can create multiple Single sections, each enabled for a different site (as Robin suggested in his [Stack Exchange answer](https://craftcms.stackexchange.com/a/24190/9).
- If each site has the same general homepage content requirements, you can create one Homepage single section, and then set its fields to translatable where needed.
