### ISSUE TITLE
[Feature Request] Add systemName config option

### ISSUE THREAD

**Issue by benface** [craftcms/cms#3529]
There's already `isSystemOn` and `timezone` so I think it would make sense to add `systemName`.

**Comment by brandonkelly** [comment]
Do you have a use case for it, especially where it would make sense to customize it on a per-environment basis? If you just want to be able to edit it in code, that is already possible in 3.1 by editing the `system.name` value in `config/project.yaml`.

**Comment by benface** [comment]
It's mostly, like you said, to be able to edit it in code, and not so much because it would change per environment (although I can see a use case where someone would want to append `(Staging)` to the system name for clarity). So for me, the `project.yaml` solution is great. Thank you :)

**Comment by brandonkelly** [comment]
Cool :)

**Comment by leevigraham** [comment]
@brandonkelly I also wanted this so I can flag if the system is Local / Dev / Prod in the siteName. Also we have a boilerplate and we control a lot of settings / labels from the .env file.

**Comment by khalwat** [comment]
@leevigraham sounds like a good use case for https://github.com/TopShelfCraft/Environment-Label

**Comment by brandonkelly** [comment]
@leevigraham Next release will allow you to set your System Name setting to an environment variable.

**Comment by leevigraham** [comment]
👍🏻 Looks like the way Craft is moving is that env variables are going to be used in fields in the admin rather than config overrides?
