### ISSUE TITLE
[Feature inquiry] Add option 'spaceless' to {% cache %}?

### ISSUE THREAD

**Issue by jkorff** [craftcms/cms#3530]
### Description
I've noticed that any code segments I'm caching with {% cache %} store all whitespace that's rendered in the database.

Wouldn't it save storage space (and maybe some query time) if whitespace wasn't cached?
Instead of 
{% cache %}{% spaceless %} ... stuff to cache ... {% endspaceless %}{% endcache %}
we could extend the cache tag to
{% cache spaceless %} ... {% endcache %}

### Steps to reproduce
1. Cache any segment
2. Check the 'body' field of the 'templatecaches' table.

### Additional info

- Craft version: 3.0.34
- PHP version: 7.2
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
It wouldn’t significantly reduce storage or improve performance, and I don’t think that Craft should be making assumptions about whitespace. You’re welcome to add that `{% spaceless %}` tag inside your `{% cache %}` tag though!
