### ISSUE TITLE
Tab names in field layout editor can't contain emoji 😢

### ISSUE THREAD

**Issue by swixpop** [craftcms/cms#3532]
### Description
Tab names in field editor can't contain emoji 😢

### Steps to reproduce

1. Create tab
2. Rename it with an emoji
3. Crash and burn

![ezgif-4-301ffed2ca50](https://user-images.githubusercontent.com/7113101/49642168-96228480-fa12-11e8-9c4c-d33983554667.gif)

**Comment by brandonkelly** [comment]
Fixed for tomorrow’s release!

**Comment by bramus** [comment]
Adding a mention of https://github.com/craftcms/cms/issues/2527 here, as that's the root cause of this issue ;)
