### ISSUE TITLE
[3.1.0-beta.4] Reordering entry types is not persisted

### ISSUE THREAD

**Issue by JeanLucEsser** [craftcms/cms#3536]
### Description

When trying to reorder entry types in sections settings, the order is not saved despite a successful message saying it is.

### Steps to reproduce

1. Go to settings > sections
2. Add multiple entry types for a section
3. Change order, witness successful message, go somewhere else, come back, order is lost

### Additional info

- Craft version: 3.1 beta 4

**Comment by andris-sevcenko** [comment]
This was fixed in 75dfbb4f60e0be2d9213f3a9d37301ec7b434087
