### ISSUE TITLE
[Feature Request] Allow reverse :empty: / :notempty: relation queries

### ISSUE THREAD

**Issue by benface** [craftcms/cms#3538]
Not sure if the title makes sense, because this is somewhat complicated, but I'll explain it with an example. Let's say I have two sections: `articles` and `authors`, and an `article` entry has a `author` field (relation field). I can easily list all the articles that have at least one author:

```twig
{% set articlesWithAnAuthor = craft.entries.section('articles').author(':notempty:').all() %}
```

Or all the articles that have no author:

```twig
{% set articlesWithoutAnAuthor = craft.entries.section('articles').author(':empty:').all() %}
```

But if I want to list all the authors that have at least one article, it's more complicated. I can do it with two queries:

```twig
{% set articleIds = craft.entries.section('articles').ids() %}
{% set authorsWithArticles = craft.entries.section('authors').relatedTo(articleIds).all() %}
```

But it would be nice to do it with just one:

```twig
{% set authorsWithArticles = craft.entries.section('authors').relatedTo({ section: 'articles', field: 'author', element: ':any:' }) %
```
(not sure at all if that API makes sense, just a suggestion)

If I want to list all the authors with no article, it's even more complicated:

```twig
{% set articleIds = craft.entries.section('articles').ids() %}
{% set idsOfAuthorsWithArticles = craft.entries.section('authors').relatedTo(articleIds).ids() %}
{% set authors = craft.entries.section('authors').all() %}
{% set authorsWithoutArticles = [] %}
{% for author in authors %}
    {% if author.id not in idsOfAuthorsWithArticles %}
        {% set authorsWithoutArticles = authorsWithoutArticles|merge([author]) %}
    {% endif %}
{% endfor %}
```

But it could be supported in a similar manner:

```twig
{% set authorsWithoutArticles = craft.entries.section('authors').notRelatedTo({ section: 'articles', field: 'author', element: ':any:' }) %
```

Thoughts?

**Comment by brandonkelly** [comment]
Related: #1640
