### ISSUE TITLE
`mergeElementsByIds()` is using the wrong table name in Craft 2

### ISSUE THREAD

**Issue by jalendport** [craftcms/cms#3539]
### Description
I created a console command that accepted two parameters (category element ids) and then used [`mergeElementsByIds()`](https://docs.craftcms.com/api/v2/craft-elementsservice.html#method-mergeelementsbyids) to merge the two categories. Worked fine on my local machine but when running the command on the production server I would get:

    CDbException: CDbCommand failed to execute the SQL statement: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'production_db.craft_structureElements' doesn't exist. The SQL statement executed was: SELECT count(`id`) FROM `craft_structureElements` WHERE (`structureId`=:pQ1RntGflh) AND (`elementId`=:pK4htsr7b7)

The table `craft_structureElements` doesn't seem to exist in that camelCase version; it's actually `craft_structureelements` in both my local and remote DBs. Seemed kind of odd so I decided to check into the Craft source code. I found [this line](https://github.com/craftcms/cms/blob/master-v2/src/services/ElementsService.php#L1875) that, when I updated it to the non-camelCased DB name, worked fine for me on my production server. Seems everywhere else in the codebase you're using `craft_structureelements` so I'm guessing this one usage is just a typo.

### Additional info

- Craft version: 2.6.3019
- PHP version: 7.1.21
- Database driver & version: 10.3.9-MariaDB Homebrew
- Plugins & versions: (a bunch and from what I can tell unimportant so will leave them out for now; can provide if necessary)

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Looks like it would only be a problem for case-sensitive collations, but still, not sure how it’s gone this long undetected :) Fixed for the next Craft 2 and 3 releases.

**Comment by brandonkelly** [comment]
Hah, it’s called any time you need to merge two assets together, so I’m sure it’s called semi-frequently :)

**Comment by jalendport** [comment]
Oh interesting, didn't realize that method was getting used anywhere in the CP. Very odd indeed...

Thanks again!
