### ISSUE TITLE
[3.1.0-beta.4] `info` table columns out of order

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#3540]
### Description

When the `config` and `configMap` columns are added to the `info` table, they are simply being appended as the last columns.

<img width="300" alt="`info` table columns" src="https://user-images.githubusercontent.com/5309692/49694430-c8c99b80-fb3e-11e8-8b94-e819172eeacd.png">

It looks like the migration to add them is not specifying which columns they should come **after**:

https://github.com/craftcms/cms/blob/3.1/src/migrations/m180521_173000_initial_yml_and_snapshot.php#L23-L24

### Steps to reproduce

1. Update a site from 3.0 to 3.1
2. See the `info` table

### Additional info

- Craft version: 3.1.0-beta.4

**Comment by andris-sevcenko** [comment]
That’s because Postgres does not support adding columns at certain positions, so the consistent thing to do was to stop doing that altogether.

**Comment by andris-sevcenko** [comment]
Oh wait, I was wrong. We should be doing that, just Postgres will ignore that. Silly of me.

**Comment by lindseydiloreto** [comment]
Haha, I was gonna say... Thanks @andris-sevcenko! 🍺

**Comment by brandonkelly** [comment]
Fixed for the next release, for new 3.1 upgrades.

Column positioning is 100% cosmetic and won’t have any impact on query performance, so not going to add a migration to reposition the columns for existing Craft 3.1 upgrades. You can always tweak the position in a DB client app if you care, though.

**Comment by lindseydiloreto** [comment]
Beautiful, thanks @brandonkelly! 👍
