### ISSUE TITLE
Path not being preserved when retrieving assets

### ISSUE THREAD

**Issue by bragle** [craftcms/cms#3543]
### Description

If Craft is placed on a specific path, assets wont be loaded due to the path being stripped from the URL set in config.

### Steps to reproduce

1. Place Craft on a specific path (ex `example.com/craft/`)
2. Add image assets to a page
3. Craft will try to load the asset (after transformed) from `example.com/index.php?p=actions/assets...` instead of `example.com/craft/index.php?p=actions/assets...`

### Additional info

- Craft version: 3.0.34
- PHP version: 7.0.32

**Comment by bragle** [comment]
I verified, and the base URL does include `craft/`. test.php only outputs an empty string, so I guess that might be the source of my problem.

**Comment by brandonkelly** [comment]
Hm yeah, that should gave output `'craft'`. Sounds like a server config issue.

Craft/Yii will check the following places when determining the base request URL:

- `$_SERVER['SCRIPT_NAME']`
- `$_SERVER['PHP_SELF']`
- `$_SERVER['ORIG_SCRIPT_NAME']`
- `$_SERVER['DOCUMENT_ROOT']`

Make sure at least one of those is set – and includes the same script name (`index.php`) as `$_SERVER['SCRIPT_FILENAME']`.

**Comment by bragle** [comment]
Looks like the first two are set to `/index.php`, but that might be because of our server configuration. We have one server that will forward the request to another server where Craft is hosted if the request URL is `example.com/craft/`. I could change `$_SERVER['SCRIPT_NAME']` in `index.php` but that seems like a hacky solution.

**Comment by brandonkelly** [comment]
On the server where Craft actually lives, is your `index.php` file located within a `craft/` folder in your web root? Or is “`craft/`” just an imaginary folder that only lives on the first web server?

**Comment by bragle** [comment]
`craft/` doesn't actually exist. It's just used in a .htaccess-file or something like that somewhere on another server (that I don't have access to). I really appreciate all the help!

**Comment by MR4online** [comment]
> On the front end, URLs generally take your site’s Base URL into account. If Craft is located in a `craft/` subfolder, then your Base URL should include `craft/`. Go to Settings → Sites, click on your site, and verify that.
> 
> If you’re also seeing this behavior in the Control Panel, try this:
> 
>     1. In your `craft/` folder, copy your `index.php` file to `test.php`.
> 
>     2. In `craft/test.php`, delete this line at the bottom:
>        ```
>        $app->run();
>        ```
> 
>     3. Add this to the bottom of the file:
>        ```
>        Craft::dd($app->request->getBaseUrl());
>        ```
> 
> 
> Then access `http://example.test/craft/test.php` in your browser and let me know what it outputs.

I may have an similar problem.
I installed the happylager.test. (But without the virual-host pointer). 

So my Base-URL is:
**http://192.1.1.1/craft-cms/happylager.test/web/**

And printing the base-url in the /web/index.php as you said, prints:
 **'/craft-cms/happylager.test/web'** 
which is somehow correct. But in the Frontend, Images are still searched in: 
**http://192.1.1.1/assets/site/_thumb/fist.jpg**

Everthing else (CSS, JS) is loaded correct.

**Comment by brandonkelly** [comment]
@MR4online Asset URLs are based on the volume’s Base URL setting, which in Happy Lager’s case uses custom `@assetBaseUrl` [alias](https://docs.craftcms.com/v3/config/environments.html#aliases), defined on [line 28](https://github.com/craftcms/demo/blob/master/config/general.php#L28) of `config/general.php`.

Just change that value to `/craft-cms/happylager.test/web/assets/` and you should be good to go.

**Comment by brandonkelly** [comment]
@bragle Can you try moving the Craft install into an actual `craft/` subfolder in your web root, to mirror its location on the front web server, and then ask whoever’s in change of the front server to change their `/craft/*` requests to point to `/craft/*` on the Craft server?

**Comment by bragle** [comment]
Yeah, that solved it. Thanks!

If anyone else has the same problem, remember to change `CRAFT_BASE_PATH` too.

**Comment by brandonkelly** [comment]
Cool, glad to hear it!
