### ISSUE TITLE
Volume fieldlayout tab name saved with translated name

### ISSUE THREAD

**Issue by christianruhstaller** [craftcms/cms#3544]
### Description
When you have a multilingual site and you create a volume in the CP and add a field to the layout
the tab name of the field layout ("Content") gets saved in the localized version of the CP language ("Inhalt" for german).

Normally this does not produce any problems except that the value isn't translated. But if you export the volume via The Architect and want to import it again it throws an error because the volumes needs a tab named "Content" and we only got the localized version of it. 

### Steps to reproduce
1. Change CP language to german 
2. Create a volume
3. Add field to the volume
4. Look at the db table "fieldlayouttabs" and you see that the name is the translated version of "Inhalt" instead of "Content"

### Additional info

- Craft version: Craft Pro 3.0.34
- PHP version: 7.2.13

**Comment by brandonkelly** [comment]
Craft isn’t strict about field layout tab names intentionally, and may down the road start allowing admins to create custom tabs in their volume field layouts. So I consider this an Architect bug.

I’ve reported it here: https://github.com/Pennebaker/craft-architect/issues/35
