### ISSUE TITLE
After clearing a search in the admin, it does not return to previous sort mode in listing

### ISSUE THREAD

**Issue by guyinpv** [craftcms/cms#3548]
### Description
After doing a search for entries in the admin area and then clicking the 'x' to clear the search, the listing maintains a similar sort as the search sort, rather than returning to what the sort was on the listing before.

### Steps to reproduce

1. Sort entries by date descending.
2. Do a search which is perhaps by score desc.
3. Now click 'x' to clear the search.
4. The listing will now be sorting by title desc instead of original date desc.

### Additional info

- Craft version: 3.0.34
- Plugins & versions: I have image resizer, redactor, redirect plugin, and retcon.

What should happen, is that after clearing a search, I should be returned to whatever the previous "view" was, the previous sort and maybe even same location in the listing I was at. As a bonus, since the listing is infinite-scroll, it would also be nice to return to the location I was at, if I happened to be on page 3 or something when I did the search, it should go back to page 3 when I clear the search, to leave me exactly where I was before searching.

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next Craft 2 and 3 releases.
