### ISSUE TITLE
Errors passed to _handleSendPasswordResetError are not displayed

### ISSUE THREAD

**Issue by gilleard** [craftcms/cms#3549]
### Description

System emails were not being sent due to an unrelated network issue, but the issue went unnoticed as the error messages weren't being displayed.

### Steps to reproduce

1. Mock an exception in the try block within `UsersController::actionSendPasswordResetEmail` (or just manually call `_handleSendPasswordResetError` immediately)
2. In the CP click the "Send password reset email" action from the edit user screen
3. The page doesn't redirect due to the error (the exception is logged) but the `errors` route parameter is not used/displayed

### Additional info

- Craft version: 3.0.19

**Comment by brandonkelly** [comment]
Thanks! That’s been fixed for the next Craft 2 and Craft 3 releases.
