### ISSUE TITLE
Change in Handling Relations Fields from the Front End

### ISSUE THREAD

**Issue by levinelson** [craftcms/cms#3552]
### Description

In Craft 2, it was possible to save multiple elements in a relation field on an entry from the front end by passing an array of ids like so:

```  
<input type="hidden" name="action" value="entries/save-entry">
...
<input type="hidden" name="fields[myRelationField]" value="[1,2,3]">
```

This no longer works, and `inputs` like this must be refactored to one `input` per ID to be saved:

```  
<input type="hidden" name="action" value="entries/save-entry">
...
<input type="hidden" name="fields[myRelationField][]" value="1">
<input type="hidden" name="fields[myRelationField][]" value="2">
<input type="hidden" name="fields[myRelationField][]" value="3">
```

Not a big deal, but it took me a while to hunt down why my previous method wasn't working. Just thought it'd be worthwhile to note this in the "[Changes in Craft 3](https://github.com/craftcms/cms/blob/b1276c9a048a80b00866fb1c800e6b201a1b4968/docs/changes-in-craft-3.md)" docs.

### Additional info

- Craft version: 3.0.35
- PHP version: 7.2.1

**Comment by brandonkelly** [comment]
We never intentionally supported that syntax in the first place. Any idea where you learned you could use it? Can add it to the Changes in Craft 3 page if the JSON syntax is actually documented/suggested publicly anywhere.

**Comment by levinelson** [comment]
👍 I can't remember where I learned the technique and can't find anything useful by Googling. Thanks for checking into it.
