### ISSUE TITLE
Feature Request: Add upload user to an asset

### ISSUE THREAD

**Issue by andrewfairlie** [craftcms/cms#3553]
This may be a duplication, but I couldn't find it on GitHub.

A client has requested that they can see which user uploaded what file. As far as I can tell, Craft 3 currently doesn't link assets to users like Entries do.

It would be useful to have this option so that clients know who uploaded what.

**Comment by brandonkelly** [comment]
Yeah currently not something Craft stores anywhere.

**Comment by Macrike** [comment]
I'd also love to see this as it would come in _very_ handy.

It would be extremely useful to have some of the parameters currently available on entry queries over on asset queries too.

'after, 'authorGroup', 'authorGroupId', 'authorId', 'before', et cetera

**Comment by brandonkelly** [comment]
Just added this for the next 3.4 Beta release!
