### ISSUE TITLE
Propagate entries, but only across site group

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#3554]
Lets say we have this setup:

```
site group cats
    cats - english
    cats - russian
site group dogs
    dogs - english
    dogs - russian
```

When I create entries, for example blog posts, i want them to propagate across multiple language versions, but only within their site group.

Right now entries would propagate across both `cats` and `dogs` groups, or no at all.

**Comment by naboo** [comment]
+1

Would be very appreciated!

**Comment by croxton** [comment]
Yes please. This would be an extremely useful.

**Comment by joelzerner** [comment]
+1
Yes please!

**Comment by brandonkelly** [comment]
Just added a new “Propagation Method” setting for the next Craft 3.2 alpha release, with the following options:

- Only save entries in the site they were created in
- Save entries to other sites in the same site group
- Save entries to other sites with the same language
- Save entries to all sites enabled for this section

The first and last of those have the same behavior as the previous “Propagate entries across all enabled sites?” setting when disabled and enabled, respectively.

To get this update right now, edit your composer.json file and change the `craftcms/cms` requirement to:

```json
"require": {
  "craftcms/cms": "3.2.x-dev as 3.2.0-alpha.1",
  "...": "..."
}
```

Then run `composer update`.

**Comment by pgrzyb** [comment]
Switching a section to use "Only save entries in the site they were created in" results in:
`[error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Getting unknown property: craft\records\Section::propagateEntries in /home/vagrant/sites/***/craft3/vendor/yiisoft/yii2/base/Component.php:154`

Am I doing something wrong or is this a bug?

**Comment by brandonkelly** [comment]
@pgrzyb That was due to a merge from the `develop` branch into the `3.2` branch, which I should have spent a little more time reviewing before pushing. Fixed it yesterday though. Run `composer clear-cache` followed by `composer update` and you should be good.

**Comment by amityweb** [comment]
Any idea when a stable 3.2 is released? I think we need this feature now as per a few recent issues I posted on Stack Exchange. Looks like this will fix it. Our site will go love next month, curious to know if 3.2 is stable to use now. Cant see how else we can get the site finished if we cant sync content within groups.

**Comment by brandonkelly** [comment]
@amityweb 3.2 will be stable soon, but I don’t think this feature will help you with [your importing question](https://craftcms.stackexchange.com/questions/30739/feedme-all-sites-get-overwritten-by-other-foreign-sites-import-even-though-fi) (assuming that’s the one you are referring to). When the new Propagation Method setting is set to ”Save entries to other sites in the same site group”, entries won’t exist at all in any sites that aren’t part of the same group they were created in.

**Comment by amityweb** [comment]
About "entries won’t exist at all in any sites that aren’t part of the same group they were created in." I already have all sites created in English though. I followed this article to import all content, which initially imports all sites in English, then FeedMe for each site would update the entries https://caffeinecreations.ca/blog/importing-entries-into-a-multi-lingual-craft-cms-website/. Its just FeedMe is replacing Matrix outside of the groups, all sites, so wondered if this setting at all would help. 

If its not related to FeedMe updates and only when creating new Sites, it would be great if someone could address the issue of the import overwriting all sites and not those within the group? e.g. perhaps the Matrix field needs the translation setting to only translate per group, like other fields? 

Thanks

**Comment by brandonkelly** [comment]
@amityweb I think something is getting lost in translation here. I do understand what you’re trying to accomplish but it’s currently not possible, as I’ve tried to explain at https://github.com/craftcms/feed-me/issues/463#issuecomment-504988387 and above. Maybe best to email support@craftcms.com and book some consulting time with us, so we can work with you on a solution.

**Comment by amityweb** [comment]
Yeah I am going to need that. I am quote surprised by all this, 75% into a project to find its not possible. Its not very clear. Fields are translatable per group, so you just expect all fields including Matrix. We have some serious issues now choosing Craft without being able to have matrix fields duplicate across a group.
