### ISSUE TITLE
User statuses are confusing (Craft 2 and Craft 3)

### ISSUE THREAD

**Issue by missmatsuko** [craftcms/cms#3556]
### Description
![Screenshot of 'Pending' status filter applied on Users](https://i.imgur.com/n02Ed02.png)
1. When we filter users by status and select 'Pending' (orange), users with the suspended status (red) will appear. I'm guessing this is because these suspended users never verified their account, but it is confusing that the filter doesn't show only users whose status is set to 'Pending'. 

![Screenshot of an 'Unverified' user status](https://i.imgur.com/SesYzpb.png)
2. When I inspected some of these users, I found that even the users marked with orange that I thought were 'Pending' were actually 'Unverified'. I don't know where this term is coming from, since the docs below only list `'active'`, `'locked'`, `'suspended'`, `'pending'`, `'archived'`, and `null` as possible values for User Status. I did notice that there's a 'pending' class on this element, though.
- [Craft 2 User Status Docs](https://docs.craftcms.com/v2/templating/craft.users.html#parameters)
- [Craft 3 User Status Docs](https://docs.craftcms.com/api/v3/craft-elements-db-userquery.html#method-status)

### Steps to reproduce
1. Set up a Craft site and add some users
2. Suspend some users
3. Go to `/admin/users` and select the 'Pending' status

### Additional info

- Craft version: All? Observed on Craft 2 and Craft 3 sites
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
It’s a little awkward because a user technically could be both pending and suspended (though suspending a user that hasn’t even activated their account yet, let alone done something suspense-worthy, is a little [Dickish](https://en.wikipedia.org/wiki/Pre-crime)).

Considering that I would say this is expected behavior. If their account is pending, they should show up in this list, regardless of whether they’ve been suspended. If they’ve been suspended, I do think that’s an important thing to show in the Status column, even when searching for Pending users.

> 2. When I inspected some of these users, I found that even the users marked with orange that I thought were 'Pending' were actually 'Unverified'.

Where are you seeing the reference to “unverified” ? Pending and unverified mean the same thing, but we should be consistent.

**Comment by missmatsuko** [comment]
> It’s a little awkward because a user technically could be both pending and suspended (though suspending a user that hasn’t even activated their account yet, let alone done something suspense-worthy, is a little Dickish).

Yeah, I'm not sure what the reason for suspending users was. It looks like maybe the accounts were created with spammy-looking emails, so maybe that's why they got suspended.

> Considering that I would say this is expected behavior. If their account is pending, they should show up in this list, regardless of whether they’ve been suspended. If they’ve been suspended, I do think that’s an important thing to show in the Status column, even when searching for Pending users.

In this particular case, the client wants to see only Pending users who are not Suspended.

If this is the expected behaviour, then the user detail view should display both 'Pending' and 'Suspended'. Currently it looks like the user's status is only 'Suspended'.

The dot in the list-view items should also match the filter, maybe by showing both colors. Currently it seems like the filter is broken because the filter's dot color doesn't match the result dot colors.

The documentation for user status should also be updated to make it clear that a user can have multiple statuses. Is this really the case though? It seems like user status is a string, so a user shouldn't be able to have multiple statuses: [Craft 3 User Model - Status](https://docs.craftcms.com/api/v3/craft-elements-user.html#public-properties)

> Where are you seeing the reference to “unverified” ? Pending and unverified mean the same thing, but we should be consistent.

I saw this in the user's detail page (e.g. `/admin/users/26`), in the right sidebar.

**Comment by brandonkelly** [comment]
Yep done.

**Comment by missmatsuko** [comment]
Champ!
