### ISSUE TITLE
3.1.Beta5.1 - TypeError: Argument 1 passed to craft\services\Fields::getGroupById() must be of the type integer

### ISSUE THREAD

**Issue by neokoenig** [craftcms/cms#3561]
### Description

/admin/settings/fields in CP throws `TypeError: Argument 1 passed to craft\services\Fields::getGroupById() must be of the type integer`

### Steps to reproduce

1. Go to Control Panel > Settings > Fields

### Additional info

- Craft version: Craft Pro 3.1.0-beta.5.1
- PHP version: 7.2.1
- Database driver & version: MySQL 5.6.26
- Plugins & versions:
 

Architect | 2.2.11
Asset Usage |  2.0.0-beta.2
Dumper | 1.3.1
Feed Me | 3.0.2.1
ImageOptimize | 1.4.44
oEmbed | dev-feature/craft-v3.1
Redactor | 2.1.6
SEOMatic  |3.1.36
Tags | 1.0.1
Twitter | 2.1.3

TypeError: Argument 1 passed to craft\services\Fields::getGroupById() must be of the type integer, null given, called in D:\inet_craft\public\vendor\craftcms\cms\src\base\Field.php on line 445 and defined in D:\inet_craft\public\vendor\craftcms\cms\src\services\Fields.php:268
Stack trace:
 - #0 D:\inet_craft\public\vendor\craftcms\cms\src\base\Field.php(445): craft\services\Fields->getGroupById(NULL)
 - #1 D:\inet_craft\public\vendor\yiisoft\yii2\base\Component.php(139): craft\base\Field->getGroup()
 - #2 D:\inet_craft\public\vendor\craftcms\cms\src\helpers\Template.php(57): yii\base\Component->__get('group')
 - #3 D:\inet_craft\public\storage\runtime\compiled_templates\b7\b7e6ecae075cd56bc18f339d31d0fa53b98bd7574bffb48857195ee0c7cf5d73.php(276): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\fields\Dropdown), 'group', Array)
 - #4 D:\inet_craft\public\vendor\twig\twig\lib\Twig\Template.php(189): __TwigTemplate_ec38eebdede5c54918da2b43cf1d4ae867da2c034506bcc6c68e121900aa4a62->block_content(Array, Array)
 - #5 D:\inet_craft\public\storage\runtime\compiled_templates\58\5818ca4bc8c8a51238ebc8e009518f7ea3df76a9d77a144d17ee204866a8e5d9.php(648): Twig_Template->displayBlock('content', Array, Array)
 - #6 D:\inet_craft\public\vendor\twig\twig\lib\Twig\Template.php(189): __TwigTemplate_659e12b0b03c4923cbc2c1d9b49f51e47f2f87c7cc96b0c5162213a5af127764->block_main(Array, Array)
 - #7 D:\inet_craft\public\storage\runtime\compiled_templates\58\5818ca4bc8c8a51238ebc8e009518f7ea3df76a9d77a144d17ee204866a8e5d9.php(533): Twig_Template->displayBlock('main', Array, Array)
 - #8 D:\inet_craft\public\vendor\twig\twig\lib\Twig\Template.php(189): __TwigTemplate_659e12b0b03c4923cbc2c1d9b49f51e47f2f87c7cc96b0c5162213a5af127764->block_body(Array, Array)
 - #9 D:\inet_craft\public\storage\runtime\compiled_templates\50\50b9571352228c106b69653b8078a0543bffb0a4390a5c2e9a94db40c8a2a059.php(60): Twig_Template->displayBlock('body', Array, Array)
 - #10 D:\inet_craft\public\vendor\twig\twig\lib\Twig\Template.php(390): __TwigTemplate_91d2b2cb36b602e01f40e69eaa04e590398d251824293c9ce6def3560b189b4f->doDisplay(Array, Array)
 - #11 D:\inet_craft\public\vendor\craftcms\cms\src\web\twig\Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
 - #12 D:\inet_craft\public\vendor\twig\twig\lib\Twig\Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
 - #13 D:\inet_craft\public\vendor\craftcms\cms\src\web\twig\Template.php(31): Twig_Template->display(Array, Array)
 - #14 D:\inet_craft\public\storage\runtime\compiled_templates\6b\6b9db6fea1ebe277289415b38f52fc0bcc3aba5f4e73d2fca127e8f7ea36f75f.php(40): craft\web\twig\Template->display(Array, Array)
 - #15 D:\inet_craft\public\vendor\twig\twig\lib\Twig\Template.php(390): __TwigTemplate_f091f36ee5a0cdea84a2c3434d5d94082574c823e830a759704c45b212c73ae5->doDisplay(Array, Array)
 - #16 D:\inet_craft\public\vendor\craftcms\cms\src\web\twig\Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
 - #17 D:\inet_craft\public\vendor\twig\twig\lib\Twig\Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
 - #18 D:\inet_craft\public\vendor\craftcms\cms\src\web\twig\Template.php(31): Twig_Template->display(Array, Array)
 - #19 D:\inet_craft\public\storage\runtime\compiled_templates\58\5818ca4bc8c8a51238ebc8e009518f7ea3df76a9d77a144d17ee204866a8e5d9.php(95): craft\web\twig\Template->display(Array, Array)
 - #20 D:\inet_craft\public\vendor\twig\twig\lib\Twig\Template.php(390): __TwigTemplate_659e12b0b03c4923cbc2c1d9b49f51e47f2f87c7cc96b0c5162213a5af127764->doDisplay(Array, Array)
 - #21 D:\inet_craft\public\vendor\craftcms\cms\src\web\twig\Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
 - #22 D:\inet_craft\public\vendor\twig\twig\lib\Twig\Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
 - #23 D:\inet_craft\public\vendor\craftcms\cms\src\web\twig\Template.php(31): Twig_Template->display(Array, Array)
 - #24 D:\inet_craft\public\storage\runtime\compiled_templates\b7\b7e6ecae075cd56bc18f339d31d0fa53b98bd7574bffb48857195ee0c7cf5d73.php(66): craft\web\twig\Template->display(Array, Array)
 - #25 D:\inet_craft\public\vendor\twig\twig\lib\Twig\Template.php(390): __TwigTemplate_ec38eebdede5c54918da2b43cf1d4ae867da2c034506bcc6c68e121900aa4a62->doDisplay(Array, Array)
 - #26 D:\inet_craft\public\vendor\craftcms\cms\src\web\twig\Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
 - #27 D:\inet_craft\public\vendor\twig\twig\lib\Twig\Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
 - #28 D:\inet_craft\public\vendor\craftcms\cms\src\web\twig\Template.php(31): Twig_Template->display(Array, Array)
 - #29 D:\inet_craft\public\vendor\twig\twig\lib\Twig\Template.php(375): craft\web\twig\Template->display(Array)
 - #30 D:\inet_craft\public\vendor\twig\twig\lib\Twig\Environment.php(289): Twig_Template->render(Array)
 - #31 D:\inet_craft\public\vendor\craftcms\cms\src\web\View.php(331): Twig_Environment->render('settings/fields', Array)
 - #32 D:\inet_craft\public\vendor\craftcms\cms\src\web\View.php(378): craft\web\View->renderTemplate('settings/fields', Array)
 - #33 D:\inet_craft\public\vendor\craftcms\cms\src\web\Controller.php(161): craft\web\View->renderPageTemplate('settings/fields', Array)
 - #34 D:\inet_craft\public\vendor\craftcms\cms\src\controllers\TemplatesController.php(78): craft\web\Controller->renderTemplate('settings/fields', Array)
 - #35 [internal function]: craft\controllers\TemplatesController->actionRender('settings/fields', Array)
 - #36 D:\inet_craft\public\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
 - #37 D:\inet_craft\public\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
 - #38 D:\inet_craft\public\vendor\craftcms\cms\src\web\Controller.php(109): yii\base\Controller->runAction('render', Array)
 - #39 D:\inet_craft\public\vendor\yiisoft\yii2\base\Module.php(528): craft\web\Controller->runAction('render', Array)
 - #40 D:\inet_craft\public\vendor\craftcms\cms\src\web\Application.php(294): yii\base\Module->runAction('templates/rende...', Array)
 - #41 D:\inet_craft\public\vendor\yiisoft\yii2\web\Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
 - #42 D:\inet_craft\public\vendor\craftcms\cms\src\web\Application.php(283): yii\web\Application->handleRequest(Object(craft\web\Request))
 - #43 D:\inet_craft\public\vendor\yiisoft\yii2\base\Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
 - #44 D:\inet_craft\public\web\index.php(21): yii\base\Application->run()
 - #45 {main}

**Comment by brandonkelly** [comment]
Looks like one of your fields is missing its group ID. Can you please send us a ticket from your Craft Support dashboard widget, including the DB backup, and reference this issue?

**Comment by neokoenig** [comment]
Done!

**Comment by MaffooBristol** [comment]
I had this issue after a botched install. For some reason Mariadb on my Amazon AMI had created a database with a dot in it and craft completely exploded from it:

```
    > saving the first user ... done
Exception: SQLSTATE[42000]: Syntax error or access violation: 1102 Incorrect database name '#mysql50#.rocksdb'
```

This then caused issues with saving fields, and in turn viewing the list.
