### ISSUE TITLE
Image Transforms for getImg() function

### ISSUE THREAD

**Issue by Visiluna** [craftcms/cms#3563]
The ability to pass an image transform to an asset's `getUrl()`, `getWidth()`, and `getHeight()` methods is pretty awesome and I use it a lot.

It'd be even more awesomer if you could add the ability to pass an image transform to an asset's `getImg()` method.

That way, I could write
`{{ asset.getImg('transform') }}`
instead of
`<img src="{{ asset.getUrl('transform') }}" width="{{ asset.getWidth('transform') }}" height="{{ asset.getHeight('transform') }}" alt="{{ asset.title }}">`.

Thanks.

**Comment by andris-sevcenko** [comment]
This has been added for Craft 3.4!
