### ISSUE TITLE
FR: Add class "site--<SiteHandle>" to <body> of "Entries Listing"

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#3565]
### Description
As an amendment to #3439 and for consistency, please can you add the `site--<SiteHandle>` class on the `<body>` to the "Entries Listing" page in the CP.

**Comment by brandonkelly** [comment]
Switching the site there doesn’t reload the page like Edit Entry pages; just reloads the entries via Ajax. So I think it would be weird to have a `site--x` class on the body in this case.

If you have a need to do something in JavaScript based on the selected site, you can get a reference to the selected site via `Craft.elementIndex.siteId`. And you can be notified whenever the site changes from the `selectSite` event:

```javascript
Craft.elementIndex.on('selectSite', function(ev) {
    // new selected site ID is `ev.siteId`
});
```

**Comment by richhayler** [comment]
Fair enough. I’m currently using the site class to apply a background colour (based on the selected site’s primary colour) to the header as a visual indicator of which site’s entries I’m editing so the above solution will work for that use case. Thanks.

**Comment by lindseydiloreto** [comment]
@richhayler Take a look at [CP Body Classes](https://github.com/doublesecretagency/craft-cpbodyclasses), it may be helpful.

Although as Brandon noted, the entries index page doesn't reload when you switch sites. The list gets refreshed via AJAX.
