### ISSUE TITLE
BaseUrl Default Setting

### ISSUE THREAD

**Issue by magnessjo** [craftcms/cms#3572]
@nystudio107 tweeted the warning for using @web as the baseURL from https://docs.craftcms.com/v3/sites.html#creating-a-site 

If I’m not mistaken, all new craft projects are created with the base url set to @web/.  I believe it’s set in the Site Model.  

Should this setting be removed to avoid any possible vulnerabilities?  

### Additional info

- Craft version: Craft Pro 3.0.35

**Comment by brandonkelly** [comment]
Duplicate of #3559
