### ISSUE TITLE
Asset field in element index don't work as expected

### ISSUE THREAD

**Issue by swixpop** [craftcms/cms#3575]
When you add an asset field to an element index, if you double click the thumbnail which opens the asset modal, clicking the edit button does nothing.

Ideal behaviour would be that the button works as expected. If this is not possible, the Edit button should not appear.

**Comment by brandonkelly** [comment]
Which element type is the index for?

**Comment by swixpop** [comment]
Adding an image field to an entries index

**Comment by brandonkelly** [comment]
And which edit button are you referring to?

**Comment by swixpop** [comment]
![ezgif-4-94437863c3cd](https://user-images.githubusercontent.com/7113101/50228869-472d0580-03a9-11e9-8088-01f36799d81d.gif)

**Comment by swixpop** [comment]
Tried disabling all plugins, tried on different computers and on different sites. Always the same result.

**Comment by brandonkelly** [comment]
Thanks, will look into it.
