### ISSUE TITLE
Keyboard Accessibility When adding a dropdown field

### ISSUE THREAD

**Issue by kmmartinez** [craftcms/cms#3576]
### Description
When adding rows to a dropdown field (Settings->Fields) the "Add an Option" button has to be clicked on by a mouse versus pressing enter on a keyboard. 

### Steps to reproduce

1. Settings
2. Fields
3. New Fields
4. Matrix, etc then choose dropdown, try adding options just through the Keyboard

### Additional info

- Craft version: 3.0.34 (Pro)
- PHP version:7.2.9
- Database driver & version: MySQL 5.6.10
- Plugins & versions:

**Comment by brandonkelly** [comment]
Added for the next release, for all editable tables including custom Table fields, not just Dropdown fields’ Options settings.

Couple notes:

- If there is a subsequent row in the table, then that row’s matching cell will be focused, without creating a new row.
- If it’s a multi-line cell, you will need to hold down <kbd>Ctrl</kbd> (Windows) or <kbd>Command</kbd> (Mac) while pressing <kbd>Return</kbd>.

**Comment by brandonkelly** [comment]
Also worth mentioning, it’s technically also possible to <kbd>tab</kbd> your way over to the “Add a row” button, and then press <kbd>spacebar</kbd>, to create a new row without your mouse.
