### ISSUE TITLE
Dragging a file from computer to assets field doesn't respect "view mode"

### ISSUE THREAD

**Issue by benface** [craftcms/cms#3578]
### Steps to reproduce

1. Create an Assets field with the "View Mode" set to "Large Thumbnails", and add it to some field layout.
2. Drag an image from your computer to the Assets field.
3. Notice the selected asset appears as a list item instead of a large thumbnail.

### Additional info

- Craft version: 3.0.36
- PHP version: 7.2.10
- Database driver & version: MySQL 5.7.23

**Comment by andris-sevcenko** [comment]
@benface I'm unable to reproduce this. Is this still happening? If it is, can you share a screencast?

**Comment by benface** [comment]
@andris-sevcenko Sure, here is one: https://www.youtube.com/watch?v=vhwgWa9nhlU

**Comment by benface** [comment]
Still happening on Craft 3.1.1.
