### ISSUE TITLE
"buildwithcraft.com" in CHANGELOG-v2.md

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#3580]
There are still a lot of references to "buildwithcraft.com" in the `CHANGELOG-v2.md` file...

https://raw.githubusercontent.com/craftcms/cms/develop/CHANGELOG-v2.md

**Comment by brandonkelly** [comment]
Meh…

**Comment by lindseydiloreto** [comment]
Ha, fair enough. I'll tackle this one if my OCD flares up.  😉
