### ISSUE TITLE
Feature Request: UID Routing Token

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/cms#3582]
All records have a `uid` column—sometimes, it's helpful to generate obfuscated URLs, or at least hide the sequential nature of a record. It appears as though they follow a pretty standard `8-4-4-4-12` pattern.

It'd be awesome to have a new routing “token” compatible with the UIDs provided by Yii, say, `{uid}`:

<img width="642" alt="screen shot 2018-12-20 at 1 14 38 am" src="https://user-images.githubusercontent.com/1895522/50275637-ae23dc00-03f4-11e9-9acc-e67fd619f9d8.png">

In `routes.php`, it'd look like:

```php
return [
    'account/subscriptions/<subscriptionUid:{uid}>' => ['template' => '_account/subscriptions/subscription'
];
```

The Regex is a little cumbersome to include in a routes file (and isn't obvious what it's for, at first blush), so this feels like a worthwhile shortcut…

```
[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}
```

Happy to issue a PR if y'all are amenable to it! I'll be sure to update the [relevant docs](https://docs.craftcms.com/v3/routing.html#advanced-routing-with-url-rules), as well.

💞

**Comment by brandonkelly** [comment]
Sure, we’ll take a PR for that.

**Comment by AugustMiller** [comment]
This was added a long while back, so I'm closing!
