### ISSUE TITLE
FR: Entries field option for selecting entries across multiple sites

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#3584]
Since the introduction of "propagate entries across all enabled sites" for channel and structure sections it's now possible to uncheck this option and create completely independent content (but using a common set of entry fields/layout) across multiple sites in a multisite setup.

So one could setup an "articles" section, design an entry layout and then create completely separate articles for site A and site B in a multisite setup.

What would be awesome is that the "entries" field now include an additional option to allow entries to be selected across multiple sites.

So using the above example an article with a "related articles" entries field could reference articles from site A and / or site B and display the entry content within the current site context.

One way this could be implemented from a UI perspective is to allow one or more sites to be selected in the sites dropdown list that is presented when checking the "entries" filed option "Relate entries from a specific site?"

There are a number of other use cases I can think of where this would be a great addition to provide flexibility and selected reuse of content managed within the CMS on a multisite setup.

**Comment by brandonkelly** [comment]
Not against this, but it’s a little complex. In order for this to be possible:

- Element queries would need to be able to select elements from different sites at once (without returning duplicate results for elements that belong to multiple sites)
- Relations would need to start storing a `targetSiteId` value that can either be an integer or null.
- Relational fields would need to submit which sites had been selected for each element.

**Comment by naboo** [comment]
@brandonkelly why not introduce a new core field type that stores that info on field level? Like an "Entries (Sites)" field type for cross site relations. So you can make the feature without doing such a large thing with core....(?).

**Comment by brandonkelly** [comment]
@naboo It would be awkward for us to do that, but it would certainly be possible for someone else to write that plugin.

**Comment by kgrote** [comment]
So presumably related entries are saved based on their individual entry ids which are unique regardless of slug or parent site. So I'm not getting why cross-site queries would be a problem?

I terms of UI I see the Entries field exactly as it is now except a dropdown at the top of the modal window to select a site, which toggles the available entries accordingly. Pretty much exactly like how entry listings work on the main control panel.

**Comment by brandonkelly** [comment]
@kgrote The original use case was for sections where “Propagate entries across all enabled sites” is disabled (or in Craft 3.2 terms, where the Propagation Method is set to “Only save entries in the site they were created in”). In that case, it isn’t really possible to relate entries that are created for other sites than the current one, as Entires fields can only fetch entries in the same site as the source entry, or a single specific site per the “Relate {type} from a specific site?” setting.

Though in Craft 3.2 this is less of an issue, now that it’s possible to make multi-site element queries. So this is possible:

```twig
{% set relatedEntries = entry.myEntriesField
    .siteId('*')
    .unique()
    .all() %}
```

Considering that, I may wait and see how much this FR is still needed until after 3.2 is out.

**Comment by richhayler** [comment]
I am so keeping my fingers crossed that this makes it into 3.2

Even an option to select entries for one specific section and only one selected site.

I've got another idea for creating a "page builder" style entries section where "blocks" of html / content can be selected from a shared entries repository (a dedicated site in a multi-site setup).

**Comment by kgrote** [comment]
@brandonkelly I don't know if this is helpful at all, but I have a situation where the section I want to relate is set to "Only save entries in the site they were created in" and I was able to make a multi-site entry picker by using a matrix field with an Entries block for each site. So the "Financial Services" block is an Entries field set to "Relate entries from a specific site?" -> financial-services.mysite.tld

When I go to output the field in the template, I don't even need to specify sites in the query, it just outputs the related entries automatically regardless of parent site.

This solution works pretty well (if a bit bloated) except I can't use it inside another Matrix field, which is a bummer. 

@richhayler Maybe you can use this technique as a temporary solution?

**Comment by richhayler** [comment]
@kgrote interesting, I took a look and I see what you mean. This might just work for the above use case. Thanks for the idea.

**Comment by richhayler** [comment]
@kgrote I tried out your suggestion and it’s actually a pretty practical solution for the “page builder” scenario. I’ve tested this out from the authoring perspective and also the twig templating for the front end and it works great.

Having said that it would still be awesome to have one native entries field that could allow entries to be selected across multiple sites so the content of those entries could either be linked to or reused, repurposed or replicated by the site establishing the entries relationship.

**Comment by brandonkelly** [comment]
Yeah at the least we should make it possible to choose a site when selecting entries. But that may be enough for 3.2 – originally I was thinking we would also need to store the site in the relation data, which is likely no longer necessary.

**Comment by brandonkelly** [comment]
Alright, as of the next 3.2 Alpha release,

- Relation fields that aren’t locked down to a single site will show a site menu in element selection modals
- Relation fields that aren’t locked down to a single site will set the following params to their values’ element queries:

  - `siteId: '*'`
  - `unique: true`
  - `preferSites: [<element’s site>]`

`preferSites` is a new param (23dbe6ba9ba4a0e2e7f7f6026f8843ee3f70d343) that can be paired with `unique` to instruct Craft on which site(s) should be preferred when fetching multi-site elements. In this case it’s telling the element query to return related elements from the same site as the source element if possible, otherwise no preference. You can override that default value in your templates if you want to make that more specific:

```twig
{% set related = entry.myEntriesField
    .preferSites([entry.siteId, 'siteA', 'siteB', 'siteC'])
    .all() %}
```

**Comment by davidhellmann** [comment]
@brandonkelly intalled the alpha 4. looks great. But the channels must be enabled for all sites otherwise it's not possible to select an entry from this site, right?

![image](https://user-images.githubusercontent.com/764292/56670309-e4c77700-66b2-11e9-8cd6-1dc87e53d8f7.png)

**Comment by brandonkelly** [comment]
@davidhellmann If you are referring to the section that contains the Entries field, then no, there’s no need to enable additional sites for it.

**Comment by javangriff** [comment]
@brandonkelly this is such a nice addition to Craft. Are there any plans on improving the display of selected entries within the selected entries list. Currently, when selecting an entry from another site there is no way to quickly distinguish from which site it has been selected, other than by double-clicking on the entry within the selected entries list.

**Comment by brandonkelly** [comment]
@javangriff That was suggested by #4690. See my response for my current thinking about it.
