### ISSUE TITLE
SQL error when uploading an asset with emoji in the filename

### ISSUE THREAD

**Issue by skoften** [craftcms/cms#3601]
When uploading an asset file that contains emoji characters, a SQL error will be returned.

Example file: [🦄.txt](https://github.com/craftcms/cms/files/2737907/default.txt)

> ```
> Upload failed. The error message was: “SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\xA6\x84' for column 'title' at row 1
> The SQL being executed was: INSERT INTO `craft_content` (`elementId`, `siteId`, `title`, `field_shortDescription`, `dateCreated`, `dateUpdated`, `uid`) VALUES (257, 1, '🦄', NULL, '2019-01-03 21:28:38', '2019-01-03 21:28:38', 'e66348b8-8352-4f21-8836-afed2fb4bd15')”
> ```

<img width="468" alt="screen shot 2019-01-08 at 9 53 05 am" src="https://user-images.githubusercontent.com/47792/50849230-3843ce00-132b-11e9-9239-adbf2493d35d.png">

- Craft version:  3.0.36
- PHP version: 7.0.32
- Database driver & version: Mysql  Ver 14.14 Distrib 5.7.24

**Comment by bramus** [comment]
Adding a mention of https://github.com/craftcms/cms/issues/2527 here, as that's the root cause of this issue ;)
