### ISSUE TITLE
Documentation on getting all category groups appears to be wrong

### ISSUE THREAD

**Issue by JayBox325** [craftcms/cms#3603]
### Description
I was trying to loop over all category groups  in a project and I found myself here:

https://docs.craftcms.com/v3/changes-in-craft-3.html#template-functions

Once I learned that the Craft 2 method was `craft.categoryGroups.getAllGroups()` I tried to use the corresponding Craft 3 syntax, however, I was getting an error when using `craft.app.categoryGroups.allGroups`.

The error was as follows:

```
Twig Runtime Error – Twig_Error_Runtime
Calling unknown method: craft\web\Application::categoryGroups()
```

So I removed the `.app` from the method and it worked perfectly as `craft.categoryGroups.allGroups`. My query is whether the `.app` version should have worked or is the documentation wrong?

### Additional info

- Craft version: 3.0.27.1

**Comment by brandonkelly** [comment]
Thanks for pointing that out. The docs are wrong, it should be `craft.app.categories.allGroups`.
