### ISSUE TITLE
Plugin store loading blocks navigation to other pages

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#3604]
### Description
Super minor annoyance, but I sometimes accidentally click the Plugin Store tab when I mean to go to Settings > Plugins and have to wait for it to load, and sometimes it takes a really long time.

Would be great if we could navigate away from this without being blocked by load times.

### Additional info

- Craft version: 3.0.36

**Comment by brandonkelly** [comment]
Not sure this is possible – @benjamindavid ?

**Comment by jsunsawyer** [comment]
Looks like this was resolved in 3.3.16!

See: https://github.com/craftcms/cms/issues/5194

**Comment by brandonkelly** [comment]
Sorry I had completely forgotten about this issue, but yes, fixing this behavior was one of the main focuses of 3.3.16 :)
