### ISSUE TITLE
Internal Server Error on Converting PlainText to DateTime

### ISSUE THREAD

**Issue by RitterKnightCreative** [craftcms/cms#3605]
### Description
Not a big issue but found this today while doing some data modeling on a client's site.

When changing a field's type from plain text to date, Craft spits out an internal server error.

Ideally Craft should fail silently or could attempt to do a ``strtotime`` to  try to convert the Plain Text field to Datetime.

``2019-01-08 11:57:27 [-][1][ns6lrem823f9icuaodqog1vcq5][error][yii\db\Exception] PDOException: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '10/6/2011' for column 'field_dateCompleted' at row 108 in /web/vendor/yiisoft/yii2/db/Command.php:1258``

This only happens when a field is already populated, if the field is empty, there's nothing to error out.

### Steps to reproduce

1. Set a new field as plain text.
2. Enter content 
3. Change field type from plain text to date 

### Additional info

- Craft version: 3.0.36
- PHP version: 7

**Comment by brandonkelly** [comment]
Looks like this is happening when converting the column from VARCHAR to DATETIME. The existing values are never run through PHP during that process. Will have to think about what to do here.

**Comment by brandonkelly** [comment]
Related: #5266

**Comment by brandonkelly** [comment]
Just realized there’s a pretty easy fix for this that hadn’t occurred to me before. Going forward, if a SQL error occurs when changing a field’s column type, Craft will rename the old column to `<previous_name>_old`, and then create a _new_ column with the new column type. All existing field values will become null, but the old data will still be in the DB so it will be possible to write a script that migrates it if needed.

**Comment by brandonkelly** [comment]
Craft 3.5.12 is out now with that change ✨
