### ISSUE TITLE
Widget size not saving

### ISSUE THREAD

**Issue by alexjcollins** [craftcms/cms#3609]
### Description
The Widget size is not saved to the database.

Looking into this a bit further, it appears as though the installation script is setting the `colspan` column on the `widgets` table to `boolean()` when it should be `smallInteger()` inline with the installation script for Craft 2.

https://github.com/craftcms/cms/blob/81e0dddf45639f408f0248c18b7e7ba7de33cebe/src/migrations/Install.php#L729

### Steps to reproduce

1. Resize widget
2. Refresh page

### Additional info

- Craft version: Craft Pro 3.0.37
- PHP version: 7.0.32
- Database driver & version: PostgreSQL 9.5.14

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.
