### ISSUE TITLE
Declare database support on Plugin Store

### ISSUE THREAD

**Issue by alexjcollins** [craftcms/cms#3610]
I think plugin developers should be able to declare which database they support with their plugins. We've run into a number of issues where devs have only implemented support for MySQL when writing their database queries (we use Postgres for all our C3 sites). I think that's completely fair enough - but users should know ahead of installing it that it has been developed and tested to support both.

My suggestion is to implement a Database row in the meta that shows the types the developer supports and has tested in, much like how wordpress.org shows version support for plugins.

I've quickly mocked up how this could look if your database is supported
![supported](https://user-images.githubusercontent.com/12031196/50917324-1fbfda80-1435-11e9-9bc5-8d9fcf3d2200.png)

And what it could look like if it's not:
![not-supported](https://user-images.githubusercontent.com/12031196/50917306-159ddc00-1435-11e9-9364-5e930d41d7b1.png)

Appreciate there's little finesse here and there are a bunch of things that should be considered (that I probably haven't), but I'm really keen to get your thoughts on this Craft team.

**Comment by brandonkelly** [comment]
I don’t think developers should have to opt into Postgres support, as plugins that are using Craft/Yii’s database query builders don’t have to do anything special to support it. But I’d be open to giving developers a chance to communicate whether they’re testing their plugins on MySQL and/or Postgres. Showing the range of Craft versions they’re testing with would be good info, too.

**Comment by alexjcollins** [comment]
That's a fair point. Showing if they're testing with MySQL and/or Postgres would probably achieve the same thing for us when viewing the plugin on the store, so that sounds good. Including Craft versions would also be nice, maybe even noting features such as the upcoming Project Config.

**Comment by brandonkelly** [comment]
Adding to the list, showing plugins that support Project Config and Soft-Deletes would also be nice.

**Comment by brandonkelly** [comment]
Closing this in favor of #3867
