### ISSUE TITLE
3.1 - Windows - http:// prefixed to $DEFAULT_SITE_URL

### ISSUE THREAD

**Issue by smcyr** [craftcms/cms#3612]
### Description

If I save a site in the CP with this value for the base url:
`$DEFAULT_SITE_URL/en/`
If I come back, the value is now:
`http://$DEFAULT_SITE_URL/en/`
But if I change it into the project.yaml directly, it works fine.

### Additional info

- Craft version: 3.1.0-beta6
- PHP version: 7.2 on Windows

**Comment by brandonkelly** [comment]
`$DEFAULT_SITE_URL/en/` isn’t a supported format. If you want to use an environment variable for the setting value, you can’t append anything else after it.
