### ISSUE TITLE
Fatal error when upgrading from 3.0 to 3.1 with multiple Sites

### ISSUE THREAD

**Issue by joshangell** [craftcms/cms#3614]
### Description

I upgraded my local install from `3.0.36` to `3.1.0-beta.7` and it went fine in the console, tried to load `/admin/entries` and got this:

```
yii\base\ErrorException: Nesting level too deep - recursive dependency? in /.../vendor/craftcms/cms/src/services/Sites.php:574
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
```

If I delete the second Site I have, transfer the content to the primary and then re-add the Site its fine.

### Additional info

- Craft version: 3.1.0-beta.7
- PHP version: 7.1
- Database driver & version: MariaDB 10.2.14
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Hey Josh,

Do you have a database backup from before you updated to 3.1? If so can you send it to support@craftcms.com, along with your `composer.json` and `composer.lock` files?

**Comment by joshangell** [comment]
Sent - unfortunately I didn’t take a backup myself but there was an older one in the `storage/backups` directory.

I only have the composer files from after the upgrade ... do you still want those?

**Comment by brandonkelly** [comment]
Yes, post-3.1 update Composer files will work.
