### ISSUE TITLE
Paginated pages beyond last page don't 404

### ISSUE THREAD

**Issue by robmcfadden** [craftcms/cms#3616]
### Description

Paginated pages don't 404 when you go beyond the last page. If I have 10 entries and I'm paginating them with 5 on a page, /p3, /p4, /p5, and so on all serve the contents of /p2 (the last page), but it feels like they should 404 instead.

### Additional info

- Craft version: 3.0.37
- PHP version: 7.2.1
- Database driver & version: MySQL 5.6.38

**Comment by brandonkelly** [comment]
Craft doesn’t know in advance which elements it will be paginating, so we can’t really fix this at the source, and technically every Craft URL could end in `/p2`, etc., and that URI segment would just have no effect if there are no `{% paginate %}` tags. That said you could guard against it by adding this to your template:

```twig
{% if pageEntries|length == 0 %}
    {% exit 404 %}
{% endif %}
```

**Comment by robmcfadden** [comment]
Got it. Thanks for taking a look. That work around, however, won't work. If p2 is your last page and you go to p3, the pagination variables return the same as p2 would, so pageEntries will not be 0. Here's the best way to achieve what I need, I'm thinking.

```twig
{% if craft.app.request.getPageNum() > pageInfo.totalPages %}
    {% exit 404 %}
{% endif %}
```

**Comment by brandonkelly** [comment]
Ah right, forgot that we do that.
