### ISSUE TITLE
[3.1] Project Config: Sources settings in asset field gets lost

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#3618]
### Description

When restricting sources in an asset fields to a single volume, that information gets lost when applying project.yaml

### Steps to reproduce

1. Set up an asset field like this:
![image](https://user-images.githubusercontent.com/25308802/51029046-7cd2a200-1595-11e9-817a-fdef0f984fc2.png)

2. Deploy project.yaml, you get this:
![image](https://user-images.githubusercontent.com/25308802/51029104-ae4b6d80-1595-11e9-83e8-bb8868cf4138.png)

"Restrict uploads to a single folder" seems to work fine.

Thanks.

### Additional info

- Craft version: 3.1.0 beta 7
- PHP version: 7.0
- Database driver & version:
- Plugins & versions:

**Comment by andris-sevcenko** [comment]
Doh. Thanks for spotting this!

**Comment by andris-sevcenko** [comment]
Fixed via 7597739
