### ISSUE TITLE
Show a warning when ./craft can't connect to the database

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#3620]
### Description
When you run `./craft` and Craft can't connect to the database, it fails silently and any commands from plugins can not be listed.
That can (and does) trip up the user,  thinking our plugin commands are missing/wrong/registered incorrectly/etc.

### Additional info

- Craft version: 3.1-beta6
- PHP version: 7.2
- Database driver & version: 5.7.33
- Plugins & versions: None

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next release.
