### ISSUE TITLE
3.1 Database migration fails

### ISSUE THREAD

**Issue by sjadema** [craftcms/cms#3622]
### Description

When updating from 3.1-beta-5.1 => 3.1-beta-7 the migration `\craft\migrations\m190108_113000_asset_field_setting_change` fails. I think this happens because on `src/migrations/m190108_113000_asset_field_setting_change.php:48` `null` is returned (instead of an empty array). This is an invalid argument for the `foreach()` following that statement.

### Steps to reproduce

1. Install Craft 3.1 beta 5.1
2. Do not add any content to the database
3. Upgrade to Craft 3.1 beta 7

### Additional info

- Craft version: Craft 3.1 beta 7
- PHP version: 7.3
- Database driver & version: MySQL 5.7
- Plugins & versions: None

**Comment by sjadema** [comment]
Yeah, i defaulted the matrix blocks to an empty array since i don't have them defined.

**Comment by brandonkelly** [comment]
Yep this should have been fixed by 4daa4e4cdb47d197d8a45e05cd47c5259934bbf3 .
