### ISSUE TITLE
Functionality to clear all previous versions of entry/all entries in section

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#3623]
Recently i noticed that my database grew to over 100 mb. And most of this are previous version of entries.

Of course i can clear them manually from database, but some kind of functionality avaible from control panel would be nice. For specific entry or for all entries in section.

**Comment by richhayler** [comment]
In the meantime this is another way to achieve this via the CP
[
https://github.com/carlcs/craft-deleteentryversions](url)

**Comment by gtettelaar** [comment]
@piotrpog Craft 3.2 will get a fully re-worked entry revisions & draft system. One feature is a [maxRevisions](https://github.com/craftcms/cms/commit/78e1fc7b56e14d67299afedfd1b0ddf933809111) config setting. Using this you can tell Craft to only store I.E the last 50 revisions of a particular entry (or any Element for that fact). That setting should prevent overloading of your DB without needing any more custom CP functionality - or do you have another use case?

**Comment by piotrpog** [comment]
@gtettelaar This config setting will be pretty useful. But setting it to some number won't remove previous versions that already exceed this number, am i right?

**Comment by gtettelaar** [comment]
@piotrpog Actually Craft will delete all revisions whose number exceed the config setting. So if you have 100 revisions and then set the setting to 50. The next time you save an entry, 50 revisions of that entry will be deleted.

You can see the code in action [here](https://github.com/craftcms/cms/blob/3.2/src/services/Revisions.php#L186).

**Comment by piotrpog** [comment]
@gtettelaar ok, so I just need to resave all entries to clear my database.

**Comment by brandonkelly** [comment]
Good point @gtettelaar. Going to close this now.
