### ISSUE TITLE
Bug with site propagation when publishing multiple languages in succession

### ISSUE THREAD

**Issue by davidrapson** [craftcms/cms#3626]
### Description

Apologies if this is a little vague, but I am seeing an occasional bug when publishing a new page across multiple sites (in our case an English and Welsh translated version of the page).

When publishing both sites/languages I often see one of the sites be overridden with the content of the other one. This is pretty frustrating as it can result in lost work and delay publishing.

### Steps to reproduce

This might be tricky to replicate but:

1. Create a new page with drafts in multiple languages
2. Publish both pages one after the other
3. See if content is overridden in one or other of the translated versions

### Additional info

We are a few patch versions of craft out of date so it's possible we're missing a fix to this in a later version. In the meantime would disabling site propagation help?

- Craft version: 3.0.25 
- PHP version: 7.1.17
- Database driver & version: MySQL 5.7.22
- Plugins & versions:

Amazon S3	1.0.8
Element API	2.5.4
Preview Button	1.0.2
Redactor	2.1.6
Super Table	2.0.10
Tags	1.0.1

**Comment by brandonkelly** [comment]
Have you ensured that all of the fields that should be translatable have the proper Translation Method set on them?

**Comment by davidrapson** [comment]
Oh that's interesting. The specific fields that changed in the instance that prompted me to raise the issue were a matrix block with a  redactor field in.

The translation option is set to "translate for each site"

![image](https://user-images.githubusercontent.com/123386/51171290-718ab980-18a8-11e9-8108-1d4d0d720110.png)

How do I determine what the proper translation method is? Should I be using "translate for each language"? We have two sites (in the same group), one english, one welsh language.

**Comment by brandonkelly** [comment]
If all sites have a unique language, then "Translate for each site" and "Translate for each language" will have the same effect.

Under "Advanced" in your Matrix field settings, do you have the "Manage blocks on a per-site basis" setting checked or unchecked?

**Comment by davidrapson** [comment]
I didn't find it under advanced but do you mean this setting?

![image](https://user-images.githubusercontent.com/123386/51179820-840fed80-18be-11e9-897e-740036ec1475.png)

If so it's unchecked in this case.

**Comment by brandonkelly** [comment]
Sorry, yes, that one.

So with things set how you have them, each site should be getting the same list of blocks, and for whichever fields have “Translate for each site” selected, each site should be getting its own values.

The only exception should be when you create new blocks, where no field values exist at all on the other site yet. In those cases it should copy the values over to the other site.

Are you able to consistently reproduce different behavior? If so, please send your `composer.json` and `composer.lock` files, along with a database backup, over to support@craftcms.com and provide us specific steps to reproduce it, and we can look into it from there.

**Comment by davidrapson** [comment]
Thanks Brandon that helps clear things up

> The only exception should be when you create new blocks, where no field values exist at all on the other site yet. In those cases it should copy the values over to the other site.

I think this might describe the exact situation I'm in. I think this is only happening when publishing drafts from a fresh/empty entry so there's a point where one ore the other of the sites might have no no values for the matrix field. For context we're using craft as a headless CMS so the way we use drafts to publish and preview new pages might be a little atypical.

I think this gives me enough to go on to try and create a reduced test case. Thanks again for your help.
