### ISSUE TITLE
ImageMagick TIF to JPG transforms not functioning after upgrade to Craft 3

### ISSUE THREAD

**Issue by peytonchance** [craftcms/cms#3628]
### Description
Previously, a client site relied on ImageMagick-powered transforms to convert TIFs to JPG. After upgrading to Craft 3, this is not functioning properly and many images are not receiving transforms, and therefore not rendering on the front-end (except in Safari, IE11 and Edge, which support TIF). 

### Additional info

- Craft version: 3.0.35
- Image Driver: Imagick 3.4.0RC6 (ImageMagick 6.8.9-9)
- PHP Version: 7.0.32

**Comment by brandonkelly** [comment]
Did you make any server changes (like update ImageMagick, your PHP version, etc.) alongside the Craft 3 upgrade?

**Comment by davist11** [comment]
After adding that to our `config/app.php`, we still weren't seeing a change. In our example, we are explicitly passing in the format to be `jpg`

```
{% set thumb = {
	mode: 'fit',
	width: 300,
	height: 300,
	format: 'jpg'
} %}

<img src="{{ item.thumbnail[0].url(thumb) }}" alt="" >
```

**Comment by andris-sevcenko** [comment]
@davist11 by any chance are you trying to convert a file with `tif` extension? I've updated the config above to include both `tif` and `tiff` extensions.

**Comment by davist11** [comment]
🤦‍♂️  yup that was it, didn't even think about the actual extension. Thanks!
