### ISSUE TITLE
[3.1] Project Config: New plugins don't get installed

### ISSUE THREAD

**Issue by michaelroper** [craftcms/cms#3629]
### Description

If i `composer require` a new plugin locally, and then _install_ it in the control panel locally, the plugin is now _enabled_, and my `project.yaml` will show the plugin key as `enabled: true`. If I deploy that config change, I am expecting that plugin to be _installed and enabled_ in my remote site. It currently seems like it’s not running the _install_ part, and therefore not enabling it either… am I missing a step in my deploy process?

### Steps to reproduce

In local dev environment:

1. Run `composer require solspace/freeform` (presuming the same for any plugin)
2. From _settings/plugins_ page, _install_ the plugin, so it is now enabled.
3. Check in `project.yaml` that the new plugin key now has `enabled: true` set.
4. Commit that change to repo.

In remote environment:
1. run deploy script to do `composer install`, `migrate/all`, and then `project-config/sync`.
2. check _utilities/system report_ page, and notice that plugin _is_ listed there.
3. check _setting/plugins_ page, and see that plugin is listed as _Not installed_.

### Additional info

- Craft version: 3.1.0-beta.5.1
- PHP version: 7.2

**Comment by brandonkelly** [comment]
The web-based config sync process was already installing/uninstalling plugins, but we forgot to add that for the CLI tool. Just fixed for today’s release.
