### ISSUE TITLE
Fixed field - field visible on all entry tabs

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#3630]
Right now only `title` field can be considered "fixed" - it is displayed on top of entry edit form, no matter which tab is opened.

What I propose, is adding ability to make other fields "fixed".

**Comment by brandonkelly** [comment]
The current plan is to give you control over which tab the Title shows up on, so it’s no longer fixed for all tabs. I think that would be better than adding to the confusion by letting custom fields be fixed as well.
