### ISSUE TITLE
Section won't appear on entries list

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#3636]
Just installed clean Craft 3.1 to test latest version. I added channel type section. Then i entered entries page. Section name appeared for second on list, below "all entries" and disappeared. I also cannot add new entry, clicking "new entry" does nothing.

My system info:

PHP version	7.2.2
Database driver & version	MySQL 5.5.5
Image driver & version	GD 7.2.2
Craft edition & version	Craft Solo 3.1.0
Yii version	2.0.15.1
Twig version	2.6.2
Guzzle version	6.3.3
Imagine version	0.7-dev

I got this error using Chrome and Edge.

**Comment by moorebrett0** [comment]
This is happening for me as well.

**Comment by piotrpog** [comment]
It seems it disappears once JS loads and runs. I managed to stop page loading with [x] browser button, and section name was still there, but no JS was active. 
If i reload, then it appears, and disappears again.

I sent all revelant files on support@craftcms.com

**Comment by piotrpog** [comment]
Thats strange. Craft version in composer file is still 3.0.0, but control panel shows 3.1.

**Comment by brandonkelly** [comment]
@piotrpog Is it `3.0.0` or `^3.0.0` (which would include 3.1)?

Try changing it explicitly to `3.1.0`, and then run `composer update` and see if `craftcms/cms` gets updated.

**Comment by piotrpog** [comment]
@brandonkelly Yes, it is `^3.0.0` indeed, i didnt noticed. When i switched to `3.1.0` and run composer update, it showed
`Nothing to install or update`.

**Comment by brandonkelly** [comment]
This ended up being expected behavior; the section that was getting hidden wasn’t enabled for the site being viewed.
