### ISSUE TITLE
Unable to update to Craft 3.1 due to dependancy conflict

### ISSUE THREAD

**Issue by lukebailey** [craftcms/cms#3640]
### Description
Attempting to update to Craft 3.1 (from 3.0.37) and seeing the following dependency conflict with craftcms/vue-asset

![image](https://user-images.githubusercontent.com/3185073/51239467-6354a000-1971-11e9-8e55-939c9ecfc33d.png)

### Additional info

- Craft version: 3.0.37
- PHP version: 7.2.1
- Database driver & version: MySQL
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
We’ve seen this happen when `composer.lock` contains a rogue reference to `craftcms/vue-asset`. Try manually running `composer update` to fix, and then reattempt the Craft update. If you’re not comfortable with that, send your `composer.json` and `composer.lock` files over to support@craftcms.com and we’ll get you sorted.

**Comment by brandonkelly** [comment]
Figured out why this is happening, and fixed it for 3.1 updates going forward via https://github.com/pixelandtonic/craftnet/commit/a4d1c103ed80035da1bc6174998550279b238866 .
