### ISSUE TITLE
'Try' button disabled in plugin store for 3.1

### ISSUE THREAD

**Issue by bymayo** [craftcms/cms#3642]
### Description

I updated to Craft 3.1 today and when going to the plugin store, I can't install anything (Or 'Try' it) unless I buy the plugin by adding to my cart.

At first I thought this was only happening on the 'Free - $0.00' plugins, but it does it across the whole store. 

It seems the Try button has `disabled="disabled"` on it, so it can't be clicked.

Is there a config setting I'm missing thats new to 3.1 or something similar?

### Additional info

- Craft version: 3.1
- PHP version: 7.1.22
- Database driver & version: 5.7.23
- Plugins & versions:

**Comment by clarknelson** [comment]
I believe the environment value in the .env file will effect how the plugin store behaves

**Comment by brandonkelly** [comment]
This was fixed via eb08ea548e37f00b2ff32b2679eedf0040110c89. We’re going to get a 3.1.1 release out soon with the fix.

**Comment by wsydney76** [comment]
After updating to 3.1.1 the "Try" button for paid plugins is still disabled for me.

![image](https://user-images.githubusercontent.com/25308802/51307533-3e7b2e00-1a40-11e9-9a94-fbdd2c8620cb.png)

Using a .local domain and devMode=true

Could manually remove the disabled="disabled" with developer tools and it works...

**Comment by clarknelson** [comment]
I am also experiencing this issue now :)

**Comment by brandonkelly** [comment]
Yeah looks like it’s still broken for plugins with one edition. We’re working on a fix…

**Comment by brandonkelly** [comment]
OK this is definitely fixed for the next release now :)

You can get the fix early by editing your `composer.json` file with 

```json
"require": {
    "craftcms/cms": "dev-develop#2f5f0b90b221540c9de585f21f62d286f00deead as 3.1.1",
    "...": "..."
}
```

Then run `composer update`.
