### ISSUE TITLE
Eager loading broken on assets and entry fields within matrix blocks

### ISSUE THREAD

**Issue by d13creative** [craftcms/cms#3644]
Entry and asset fields within a matrix block return an empty array when eager loading after updating to 3.1

The following code generates the error "Key "0" does not exist as the array is empty". Prior to updating to 3.1 this was working ok:

(site is a Global Set, logos is a matrix field which has one 'logo' block type)

```twig
{% set logos = site.logos
    .with([
        ['logo:image', { withTransforms: [ 'logo', 'logo2x' ]} ]
    ])
    .all() %}

{% for logo in logos %}
{% set image = logo.image[0] %}
    {% if logo.website | length %}
        <li><a href="{{ logo.website }}"><img class="lozad" data-src="{{ image.getUrl('logo') }}" data-srcset="{{ image.getUrl('logo') }} 1x, {{ image.getUrl('logo2x') }} 2x" alt="{{ logo.logoTitle }}"></a></li>
        {% else %}
        <li><img class="lozad" data-src="{{ image.getUrl('logo') }}" data-srcset="{{ image.getUrl('logo') }} 1x, {{ image.getUrl('logo2x') }} 2x" alt="{{ logo.logoTitle }}"></li>
    {% endif %}
{% endfor %}
```

If I change the code to this the code works:

```twig
{% set logos = site.logos.all() %}
{% for logo in logos %}
{% set image = logo.image.one() %}
    {% if logo.website | length %}
        <li><a href="{{ logo.website }}"><img class="lozad" data-src="{{ image.getUrl('logo') }}" data-srcset="{{ image.getUrl('logo') }} 1x, {{ image.getUrl('logo2x') }} 2x" alt="{{ logo.logoTitle }}"></a></li>
        {% else %}
        <li><img class="lozad" data-src="{{ image.getUrl('logo') }}" data-srcset="{{ image.getUrl('logo') }} 1x, {{ image.getUrl('logo2x') }} 2x" alt="{{ logo.logoTitle }}"></li>
    {% endif %}
{% endfor %}
```

- Craft version: 3.1
- PHP version: 7.3.1

**Comment by richardfrankza** [comment]
We are experiencing exactly the same issue with eager loading an image asset in a matrix block. Instead of returning `AssetQuery` it just returns an empty array.

**Comment by brandonkelly** [comment]
Fixed for the next release. You can patch your installs in the meantime by editing composer.json:

```json
"require": {
    "craftcms/cms": "dev-develop#f738158f3f264e5cbd48656338f7661c151408d1 as 3.1.0",
    "...": "..."
}
```

And then run `composer update`.

**Comment by JshGrn** [comment]
I still get this exact issue, has it been reintroduced?

**Comment by brandonkelly** [comment]
@JshGrn Not to our knowledge… can you provide your Craft version, and exactly what you’re seeing?

**Comment by JshGrn** [comment]
If I do a .with on a matrix field eager loading the asset field it returns an empty array. I was able to work around it by doing a asset query withTransforms and then relatedTo the matrix field.

**Comment by brandonkelly** [comment]
@JshGrn There is a special syntax for eager-loading fields nested within Matrix fields – see [ Eager-Loading Elements Related to Matrix Blocks](https://craftcms.com/docs/3.x/dev/eager-loading-elements.html#eager-loading-elements-related-to-matrix-blocks).
