### ISSUE TITLE
Settings Column Missing from Plugin Table

### ISSUE THREAD

**Issue by magnessjo** [craftcms/cms#3645]
### Description

An error is thrown when migrating from Craft 3.0.* to Craft 3.1.0.  

The error occurs on line 1322 of the Plugins service file.  $row['settings'] = Json::decodeIfJson((string)$row['settings']);

I added a 'settings' column to the plugin table and the migration completed (I have other issues showing but I don't know enough yet to add them to this issue or possibly add another).  

Note: this issue has been added to the [redactor](https://github.com/craftcms/redactor/issues/110) repo but it appears to be a craft issue.  It occurred for me as a redactor issue because redactor was the first plugin installed.  While testing, I removed redactor and the error occurred for Super Table (second plugin installed).  

### Steps to reproduce

1.  Update to craft 3.1.0 via composer.  
2.  ./craft migrate/all

### Additional info

- Plugins & versions:

  redactor: 2.1.7
  super-table: 2.0.14
  craft-somatic: 3.1.38

**Comment by nchorniiNetls** [comment]
+
same issue

**Comment by magnessjo** [comment]
So I modified the _getPluginCoinfigData function to:

```
        // todo: remove this after the next breakpoint
        if (version_compare(Craft::$app->getInfo()->version, '3.1', '<')) {
            $plugin = $this->getPlugin($handle);
            $row = (new Query())->from([Table::PLUGINS])->where(['handle' => $handle])->one();
            if($plugin) {
              $row['settings'] = Json::decodeIfJson($plugin->getSettings());
            }
            return $row;
        }
```

My understanding (or lack of understanding) from creating plugins is that the settings are stored in a modal for Craft 3 (I think they were stored as a string on the content table in Craft 2).  I modified the function to pull the settings via the helper function.  Note: that is probably wrong, but I was curious on my lunch break so I played around for a bit.  

The migration works correctly now (or at least I think it does), but I am presented with another error after reload due to lack of data from the project config file (line 1333 of the Plugin Service).  I'm not sure if this is another bug so I am going to hold off on adding another issue until I get feedback on this issue.

**Comment by andris-sevcenko** [comment]
@magnessjo can you perhaps send a pre-update database backup and your composer.lock and composer.json files over to support@craftcms.com referencing this issue?

**Comment by magnessjo** [comment]
@andris-sevcenko,

  I’ve spent an email with the db, composer.json and composer.lock.  

  I have two projects showing the error but I sent you the one that I was doing the most testing on (it is the older of two… like 7 months without an update old).  

  You will notice that there  are four plugins that need updating.  You will get an error related to SEOmatic's dependency to vue-asset if you do a composer update to only Craft.    It is composer dependency hell.  You need to first need to update Craft to 3.0.37, then update SEOMatic to 3.1.38, then update Craft to 3.1.0.  

  Let me know if you have any problems and I can list more specifics or send another project that is only a week or two behind.

**Comment by khalwat** [comment]
hmmmm. SEOmatic doesn't `require` `vue-asset` tho:

```
    "require": {
        "craftcms/cms": "^3.0.20",
        "php-science/textrank": "^1.0.3",
        "davechild/textstatistics": "1.0.2",
        "sunra/php-simple-html-dom-parser": "^1.5.2"
    },
```
https://github.com/nystudio107/craft-seomatic/blob/v3/composer.json#L31

It was in there in a while ago, but I removed it. So perhaps you have a pretty old version of SEOmatic?

**Comment by turnstylerj** [comment]
FWIW I'm having the same issue with `vue-asset`, but it's not coming from SEOmatic. Looking at the full error that's spit out, it's coming from the plugin `superbig/craft3-mobiledetect` in my case. I will be filing an issue with them.

**Comment by brandonkelly** [comment]
That plugin doesn’t require `craftcms/vue-asset` either.

https://github.com/sjelfull/craft3-mobiledetect/blob/f6eba7f9ecb34363ab5c0fbede538e3268896c8c/composer.json#L24-L27

Yesterday we noticed a bug where if a plugin had previously required `craftcms/vue-asset`, it would be listed in `composer.lock` even if nothing required it anymore. We fixed that on our end by forcing Composer to update/remove that package each time a new update is run (https://github.com/pixelandtonic/craftnet/commit/a4d1c103ed80035da1bc6174998550279b238866) so it should only be a problem if any plugins are still requiring it. You can find out by searching your `composer.lock` file for `craftcms/vue-asset` and see if it's listed in the `require` object of any packages.

**Comment by turnstylerj** [comment]
Yeah @brandonkelly, looks like the `vue-asset` message was just showing above the actual error from that plugin. Saw your fix in the mobiledetect repo - thanks!

**Comment by khalwat** [comment]
So the issue with MobileDetect as well as Template Select is that the Craft CMS semver that they `require` is `~3.0.0` which doesn't allow for updating to Craft CMS 3.1.x

@brandonkelly fixed it in both cases:

https://github.com/sjelfull/craft3-mobiledetect/commit/4170a6176a33883213e86d5c5acba49b8c3c716a#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

https://github.com/sjelfull/craft3-templateselect/commit/8c77bcf45f65ce95aded85adc6a48cd9c2cfecb4#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

...but @sjelfull needs to tag a new release version for Composer to see it. In the interim, for both of these plugins, you can set the semver in your project's `composer.json` to `dev-master` and it'll pull down the fixed version.

**Comment by magnessjo** [comment]
@khalwat,

  Yes it is a much older version (3.1.5).  It wasn't the issue though.  There was an issue occurring with the migration.  

@brandonkelly, @turnstylerj, @andris-sevcenko 

  Andris and I communicated via email to resolve the issue.  It has been tested and confirmed with 3.1.1.  This issue could be marked as closed for me.

**Comment by brandonkelly** [comment]
Good to hear!

**Comment by brandonkelly** [comment]
@sjelfull Can you tag a new release for https://github.com/sjelfull/craft3-logoutredirect as well?

**Comment by sjelfull** [comment]
@brandonkelly Done.
