### ISSUE TITLE
Can't Delete Entries in 3.1

### ISSUE THREAD

**Issue by bymayo** [craftcms/cms#3650]
### Description

This may not be a bug, but intentional due to soft delete - So I apologise if its not!

But when on Entries > All Entries, theres no way to delete an entry. The option to delete in the dropdown is just not there, unless you click on a specific page type or section etc to filter the entries.

I think this could confuse some users.

### Additional info

Craft version: 2.6.3002
PHP version: 7.1.13
Database driver & version:
Plugins & versions:

**Comment by carlcs** [comment]
I don’t think the Delete action ever worked in the “All entries” source, even in Craft 2.

**Comment by bymayo** [comment]
@carlcs Oh your right! My mistake then! ☹️It tripped me up and presumed it was a 3.1 issue.

**Comment by brandonkelly** [comment]
Yeah the available actions are set on a per-source basis. “All entries” could contain singles, which aren’t deletable from there, so it doesn’t show up there.
