### ISSUE TITLE
Automatically installing plugins listed in the project.yaml file

### ISSUE THREAD

**Issue by nmsdvid** [craftcms/cms#3651]
### Description
Automatically installing plugins listed in the project.yaml file. Currently you need to install the plugins manually, would be cool if Craft would installed it automatically when it detects there was a change in the project.yaml file.

**Comment by brandonkelly** [comment]
It already does :) Have you found a case where it does not?

**Comment by brandonkelly** [comment]
Ah right, you want them to be Composer-installed. Yep that would be cool. Maybe we can get to this when we rewrite Craft’s self-updater soon.

**Comment by ca-miked** [comment]
+1

**Comment by pathei** [comment]
Hey @nmsdvid. Seeing you out on the wild ;):
