### ISSUE TITLE
Can't apply existing project config: session_set_save_handler(): Cannot change save handler when headers already sent

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#3654]
### Description
```
can't apply existing project config: session_set_save_handler(): Cannot change save handler when headers already sent
```

### Steps to reproduce

1. Generate a project.yaml file with a project
2. Start new project with this project.yaml file and install via `./craft install`

### Additional info

- Craft version: 3.1.1
- PHP version: 7.3.1
- Database driver & version: PostgreSQL 10.6
- Plugins & versions: Commerce 2.0.1

**Comment by brandonkelly** [comment]
Not able to reproduce on my end. Is there a stack trace for that error in the logs?

**Comment by boboldehampsink** [comment]
Yup, found this to be in a third party plugin. Thanks.
