### ISSUE TITLE
Static Message Translations Override Issue

### ISSUE THREAD

**Issue by magnessjo** [craftcms/cms#3656]
### Description

My understanding for Craft 3.0.* is that you add a translations directory to the root directory with a subdirectory that is named the language’s ID.  See docs [https://docs.craftcms.com/v3/static-translations.html#prep-your-messages] for more information.  

Currently, I have a directory structure like:

```
— translations
  — en
    — site.php
```

In that file, I am returning an array of messages to be changed.  Example: 

```
<?php

return [
  'Singles' => 'Pages',
];
```

Currently, that does message overwrite does not work for me.  It does work for me if I change the file name from site.php to app.php (to match the naming convention in the craftcms repo).  

I was going to put in a pull request for the documentation to be modified, but I did some more digging and I think this is actually a bug (or some strange error on my part).  If I am understanding the i18n directive of the app.php file, then app should be overwrite by site (allow overrides is set true).

Also, I read this from the changes in craft 3 file:

```
The acceptable translation categories are:

| Category        | Description
| --------------- | -----------------------------------------
| `app`           | Craft’s translation messages
| `yii`           | Yii’s translation messages
| `site`          | custom site-specific translation messages
| `plugin-handle` | Plugins’ translation messages

```

### Additional info

- Craft version: Craft Pro 3.0.31

**Comment by carlcs** [comment]
No, translation categories exist to provide messages for different contexts (namespacing them). You’ll need a separate file for each translation category.

**Comment by magnessjo** [comment]
@carlcs,

  Hi, thanks for the comment.  I am using the translation categories as an example of the types of categories associated with translations but my question/issue isn't concerning plugin development.  

  I don't believe the translation categories apply to [static translations ](https://docs.craftcms.com/v3/static-translations.html#prep-your-messages), so I probably shouldn't have used them as a reference.  I was just trying to reference that fact that there are differences between the associate to 'app' and 'site'.  I could be wrong though (please let me know if I am).  

Thanks!

**Comment by carlcs** [comment]
Static translations is just the term that Craft uses for the Yii translation feature. For your own front end messages you’ll want to use the “site” category, and to translate messages used by Craft in the CP that would be the “app” category.

> To do that, Craft employs Yii’s Message Translations feature, and pre-defines a special translation category, site, for front-end messages.

**Comment by magnessjo** [comment]
@carlcs,

  Thank you very much for the explanation!  I believe I understand what the issue is with my logic and the documentation now.  The file shouldn't be called site to change a control panel message like 'Singles', it should be called app.  If I had specific message for my project then I would use the site file.

**Comment by carlcs** [comment]
Thanks @magnessjo, do you have suggestions to improve the documentation?

**Comment by magnessjo** [comment]
@carlcs,

Yes, in the provide the translations section I would add two files under location ID of de: site.php and app.php.  

Then I would explain what the purpose is for both (site.php and app.php).  

I would bet most people are looking for how to adjust the language in the control panel over their own messaging.  I’m stupid so I have been making control panel language modifications in plugins or modules for the last two years (….like really stupid).  

I have a deliverable tonight, but I can put in a PR tomorrow during for the static-translations page?
