### ISSUE TITLE
Table Columns settings don't transfer when updating to 3.1

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#3659]
When updating to Craft 3.1, all Table Columns settings revert to default settings.

This update also mixed up my entries/headings order.

**Comment by brandonkelly** [comment]
Are you referring to element index tables, like on the Entries page?

**Comment by jamiewade** [comment]
+1.

I had all my entries arranged in different headings and groups, but after updating to `3.1`, all entries are now showing like this:

![screenshot](https://user-images.githubusercontent.com/6672331/51380417-a5184e80-1b09-11e9-8cff-b3b4ba173b9f.png)

PHP version: 7.2.10
MySQL 5.7.24
Craft Pro 3.1.1

**Comment by jsunsawyer** [comment]
@brandonkelly Yeah, whatever it's called. Here's a screenshot of where you adjust the settings.

![screen shot 2019-01-18 at 8 58 46 am](https://user-images.githubusercontent.com/1007191/51401373-6bdae100-1aff-11e9-8a9a-1d78178f192d.png)

**Comment by brandonkelly** [comment]
3.1.2 is out with a fix for this.
