### ISSUE TITLE
Plugin edition/trial label links to 404

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#3664]
### Description

Clicking a plugin's edition or trial label in the overview of plugins (`/admin/settings/plugins`) goes to `/admin/plugin-store/plugins/commerce` (in this case), which 404's.
The correct link in the store for this plugin is `/admin/plugin-store/commerce`
![screenshot 2019-01-18 at 14 03 20](https://user-images.githubusercontent.com/755428/51388488-dc96f300-1b29-11e9-8ff7-a425370d6fdf.png)

### Steps to reproduce

1. Install Commerce as a trial
2. Go to the list of installed plugins
3. Click the trial label
4. 404

### Additional info

- Craft version: 3.1.1
- PHP version: 7.2.1
- Database driver & version: 5.7
- Plugins & versions: None

**Comment by janhenckens** [comment]
Nevermind, allready fixed in f0525d65f371c3bcb54504ace79edcbc6eca56ea :)

**Comment by brandonkelly** [comment]
Yep :) I’ll go ahead and point the release note to this issue though.

**Comment by brandonkelly** [comment]
3.1.2 is out with the fix for this.
