### ISSUE TITLE
Plugin settings referencing Element::sources[].key will break after 3.1 upgrade

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#3666]
As 3.1 changes the `key` of Element's sources to be the UID, any saved settings from plugins referencing the id-based key will be broken, e.g. https://github.com/sebastian-lenz/craft-linkfield/issues/49

At the very least, this should be outlined for plugin developers so they can write migration scripts.

**Comment by brandonkelly** [comment]
Just published an [Updating Plugins for Craft 3.1](https://craftcms.com/guides/updating-plugins-for-craft-3-1) guide.
