### ISSUE TITLE
Upgrade to 3.1 - No Create Button on Entries List

### ISSUE THREAD

**Issue by mwcbrent** [craftcms/cms#3667]
### Description
Note: on SOLO plan / instance.

After upgrading to 3.1 from 3.0.36 my entries pages do not have a button to create a new entry.  I can manually append a `/new` to the URL and view the form.  I can create sections and fields but not new entries.  I checked all the docs that I could find in order to understand if there is a new configuration setting but didn't find it.

### Steps to reproduce

1. Have a 3.0.3.6 Craft CMS installation
2. Upgrade to 3.1 via composer
3.  Run the upgrade migration
4.  View the entries index
5.  Observe there is no "New" button on the top left of the entries page.

### Additional info

- Craft version: 3.1
- PHP version: 7.3.1
- Database driver & version: MySQL 
- Plugins & versions: None

**Comment by brandonkelly** [comment]
What version of "3.1" are you on? Can you try updating to the latest?

**Comment by mwcbrent** [comment]
Was `3.1.2` will try it on the latest and report back.

**Comment by peimansh** [comment]
Experienced the same issue after upgrading from 3.0.35 to 3.1.34.3.
Even after updating to the latest 3.3.15 the issue is still there.
But we are experiencing this just on our local development environment but not on test or production.

**Comment by brandonkelly** [comment]
@peimansh do you have any plugins installed that could be messing with the UI?

**Comment by peimansh** [comment]
This is my composer.json file:
 ```
"require": {
    "craftcms/cms": "3.3.15",
    "vlucas/phpdotenv": "^2.4.0",
    "topshelfcraft/environment-label": "3.1.5",
    "verbb/super-table": "2.3.0",
    "nystudio107/craft-minify": "1.2.9",
    "craftcms/redactor": "2.4",
    "fruitstudios/linkit": "1.1.11",
    "craftcms/aws-s3": "1.2.5",
    "verbb/image-resizer": "2.0.6",
    "nystudio107/craft-seomatic": "3.2.33",
    "rias/craft-position-fieldtype": "1.0.14",
    "superbig/craft-entry-instructions": "1.0.6",
    "dolphiq/redirect": "v1.0.22",
    "samdark/yii2-psr-log-target": "^1.0",
    "verbb/expanded-singles": "1.0.7",
    "lewisjenkins/craft-dynamic-fields": "3.0.10",
    "servd/craft-remote-assets": "^0.1.7",
    "viget/craft-video-embed": "^1.2"
  }```
Don't think any of them mess with the UI. But strange is that I am having this issue only in Local Development and not in the Test and Production environments in AWS.

**Comment by brandonkelly** [comment]
Yeah, strange. Try disabling your plugins one-by-one from Settings → Plugins, and see if the issue resolves itself.

**Comment by peimansh** [comment]
Seems the problem is Craft Remote Assets plugin. After disabling it, the "New entry" button started showing up.
I don't know exactly why it is causing this.

**Comment by brandonkelly** [comment]
Are any JS errors getting logged in the console when the plugin is enabled?

**Comment by peimansh** [comment]
No nothing

**Comment by brandonkelly** [comment]
Strange. Maybe open up an issue on he plugin’s repo – https://github.com/servdhost/craft-remote-assets/issues (assuming that’s the plugin you are referring to).

**Comment by peimansh** [comment]
Yeah, I raised an issue but it seems it has not been updated for a long time. Not sure if someone is taking care of it.
