### ISSUE TITLE
Minor issue with SVG thumbnails in Assets

### ISSUE THREAD

**Issue by adrienne** [craftcms/cms#3672]
### Description

Certain SVGs don't display thumbnails properly when uploaded. A sample is attached. Mostly it seems to be animated SVGs, but some others don't display thumbnails either. Might need to have some kind of fallback generation method for SVG thumbnails?

[svg_he.zip](https://github.com/craftcms/cms/files/2776287/svg_he.zip)

### Steps to reproduce

1. Upload the attached SVG as an asset
2. Look at the Asset and notice that it doesn't have a thumbnail

### Additional info

- Craft version: 3.0.37

**Comment by andris-sevcenko** [comment]
The SVG file attached itself does not render in Chrome 71.0.3578.98 for me, so it might not be resizing that's not working reliably here but that the SVG itself is tricky.

As far as resizing SVG files goes, Craft just tries to figure out any constraints set on the root SVG tag and then adjust the markup for the required size. It's a bit finicky, but it's reliable enough. As far as animated SVGs go - well, that would mean transforming the CSS that animates the SVG and I'm not sure that would ever fall into Craft's scope to take care of that.

If you want/need a fallback solution, you can tap into the `craft\services\Assets::EVENT_GET_ASSET_THUMB_URL` and `craft\services\AssetTransforms::EVENT_GENERATE_TRANSFORM` to provid your own images, in case you have a software library that's great at this.
