### ISSUE TITLE
System message not working or changes not applied

### ISSUE THREAD

**Issue by krizajb** [craftcms/cms#3673]
### Description
The user password reset mail is acting weird. When resetting the user password the mail I receive has `forgot_password_subject` subject and `forgot_password_body` content. I tried checking the source code but after few hours gave up.
The `systemmessages` database table is empty. The System messages are correctly displayed in the admin control panel. The reset user password functionality works normal while being accessed via the admin page.
I've also discovered that changing the System message via admin control panel doesn't work. 

Site language is `sl-SI (Slovenian)`. Using sendgrid mailer.
![image](https://user-images.githubusercontent.com/496094/51463787-66ca9b80-1d64-11e9-91dd-7306be8b3c4b.png)

Update:
I think I found the problem, still no clue how to solve it. If I set the site language to anything but `en-US` the system messages don't work. If i change it to `en-US`, the changes made to the system messages aren't applied.

### Steps to reproduce

1. Configure mailer
2. Reset user password via front end
3. Receive reset mail with `forgot_password_subject` subject and `forgot_password_body` mail content

### Steps to reproduce (Update)

1. Configure mailer
2. Change 'When someone forgets their password:' 
3. `systemmessages` database table is successfully altered
5. Change is visible in the control panel 
6. Reset user password via front end
7. Receive the default reset password mail

**Comment by brandonkelly** [comment]
What version of Craft are you using?

Does the user account you’re testing have access to the Control Panel?

If so, what is their Preferred Language set to?

What is the language of the site?

In the `systemmessages` database table, which language(s) are stored in there?

**Comment by krizajb** [comment]
Craft edition & version: Craft Pro 3.0.34

The user account is also an admin account. The language set on the admin account is English. So for the first case the site language was set to `sl-SI (Slovenian)` which produces the `forgot_password_subject` subject and `forgot_password_body` mail content. For the second case the site language is set to `en-US (American English)`.

The `systemmessages` database table contains only `en-US` entries.

When trying to reset non admin user password the correct system message is applied!

**Comment by brandonkelly** [comment]
When Craft is sending a system message to a user, if the user has a preferred language selected, then it will send the message in that language, regardless of what the site language is set to.

Since you only have one site and it’s set to `sl-SI`, it’s not possible for you to edit the English translation of system messages. Which is why Craft is using the system’s default translation.

If you want to test your translated system messages, change the user account’s preferred language to Slovenian first.

**Comment by krizajb** [comment]
How do you then justify the `forgot_password_subject` subject and `forgot_password_body` mail?

**Comment by brandonkelly** [comment]
Sorry, it wasn’t clear to me that the messages were coming with _literal_ “forgot_password_subject” and “forgot_password_body” strings, as opposed to their English translations.

I’ve been able to reproduce that, and about to commit a fix…

**Comment by brandonkelly** [comment]
No worries, it was a complicated issue :)
