### ISSUE TITLE
Existing tags are not suggested anymore

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#3676]
### Description

When adding a tag it should suggest existing tags in the autocompleter. It doesn't do that anymore, and always offers to add a new tag.

### Steps to reproduce

1. Add a tag group and add a tag field to an element
2. Add a tag, then add that same tag again
3. Expected: re-use the tag
4. Result: new tag

### Additional info

- Craft version: 3.0.37
- PHP version: 7.3.1
- Database driver & version: PostgreSQL 10.6
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
> Add a tag, then add that same tag again

As in you’re trying to add the same tag to the same field?

That’s explicitly disallowed, and has been since the Tags field was first written.

https://github.com/craftcms/cms/commit/0a9ff80d4e09854c4add55d6fa0054d3981735ff#diff-1b2161c927879802b1e09ac06216e819R116

**Comment by boboldehampsink** [comment]
Yeah it should be disallowed. In stead, I can add it again (it creates a new one). What I expect is that it autosuggests the already existing tag to me.

**Comment by boboldehampsink** [comment]
Here is a screenshot
<img width="362" alt="screen shot 2019-01-21 at 14 54 40" src="https://user-images.githubusercontent.com/378974/51478708-837ac980-1d8c-11e9-8e2d-4ba9440f8a86.png">
