### ISSUE TITLE
Request getIsLivePreview() not working

### ISSUE THREAD

**Issue by putyourlightson** [craftcms/cms#3680]
The following appears to be returning `false` even in live preview requests (when it should obviously be returning `true`), which is tripping up the validation method in the Snaptcha plugin.
```
Craft::$app->getRequest()->getIsLivePreview()
```

This is happening as of Craft 3.1, currently seeing it on 3.1.2.2.

**Comment by putyourlightson** [comment]
After some more investigating, it seems that it is working, but that the check is performed later than it was previously., so that it is not yet registered when the `Controller::EVENT_BEFORE_ACTION` event is triggered. If this is intentional then I'll update the code on my end.

**Comment by putyourlightson** [comment]
If the line `Craft::$app->getRequest()->setIsLivePreview(true);` was moved from: 
https://github.com/craftcms/cms/blob/3.1.2.2/src/controllers/LivePreviewController.php#L104 
to:
https://github.com/craftcms/cms/blob/3.1.2.2/src/controllers/LivePreviewController.php#L36 
then that would perhaps make it more reliable?

**Comment by brandonkelly** [comment]
Yep, easy enough.

**Comment by putyourlightson** [comment]
Thanks!
