### ISSUE TITLE
Unable to drag order categories in categories field type

### ISSUE THREAD

**Issue by mark-chief** [craftcms/cms#3681]
### Description

I am unable to drag and re-order the selected categories in a Categories field type. Expected behaviour is to be able to drag and re-order your selection like and Entries field(?)

### Steps to reproduce

1. Create Categories field, add to section
2. Add multiple categories
3. Try and drag and drop the order of them.

### Additional info

- Craft version: 3.1.2.2
- PHP version: 7.1

<img width="938" alt="screen shot 2019-01-21 at 16 44 35" src="https://user-images.githubusercontent.com/18699249/51487926-2555e280-1d9c-11e9-9bf7-50ce0493f2ce.png">

**Comment by brandonkelly** [comment]
This is the expected behavior - to maintain the order defined by the category group.
