### ISSUE TITLE
Can't create new headings to organize channel types.

### ISSUE THREAD

**Issue by zenbug** [craftcms/cms#3684]
### Description

After a recent Craft update, I can no longer create new headings to separate my channel types (Structures, Channels, Singles, etc.)

### Steps to reproduce

1. In the Entries screen, click the cog wheel in the left column.
2. Click the "New Heading" button.
3. Type a heading and hit save. Heading does not appear.

### Additional info

- Craft version: 3.1.2.2
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by CreateSean** [comment]
I see, when you create the heading before saving it, you need to move it into place above already existing sections.

**Comment by zenbug** [comment]
Ah yes. Sean's right - I have to move it up first, because it gets added at the bottom of the list.
