### ISSUE TITLE
Updating breaks system when failed because not enough memory

### ISSUE THREAD

**Issue by MetaDevelopment** [craftcms/cms#3686]
### Description
I've set up a new Craft install and a day later a Craft update was available (nothing else changed yet). I tried to execute it, but I got an error that there was not enough memory. So, I changed the server settings to allow for more memory to be used, however, visiting any link (the front-end or the control panel) gives the following errors:

```
Warning: require(.../vendor/craftcms/cms/bootstrap/web.php): failed to open stream: No such file or directory in .../public/index.php on line 20

Fatal error: require(): Failed opening required '.../vendor/craftcms/cms/bootstrap/web.php' (include_path='.:') in .../public/index.php on line 20
```

Upon checking the /vendor/craftcms/cms folder, it seems this is now empty. Can it be prevented that trying to execute an update breaks the entire system?

### Steps to reproduce

1. Set up a Craft install
2. Make sure not a lot of memory is available to Craft so it will not be able to fully execute its update
3. Wait until a Craft update is available
4. Try to install the update via the control panel

**Comment by brandonkelly** [comment]
To fix your current installation, you will need to run `composer update` manually from your terminal.

You can prevent this from happening again in the future by editing your php.ini file and increasing the `memory_limit` setting. Craft [requires](https://docs.craftcms.com/v3/requirements.html) at least 256M assigned to it for things to work properly.

While you’re at it, you should check the `max_execution_time` setting and make sure that’s set to at least 120.

If you’re not sure where your php.ini file is located, create a PHP file called `ini.php` alongside your `index.php` file with this:

```
php
echo 'Loaded php.ini: ' . php_ini_loaded_file();
```

Then access that file in your web browser by going to `http://your-project.test/ini.php`.

Once you’ve made those changes, restart your web server for the changes to take effect.
