### ISSUE TITLE
Unable to make changes to Sites after 3.1 update

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#3687]
### Description
I've just tested this on two separate projects that started on Craft 3, and have been updated to 3.1. Since updating, I can't update details of my Site anymore. If I go to Settings > Sites and try to update anything in there like the Name, handle or Base URL, I get this error:

    Getting unknown property: craft\records\SiteGroup::craft\errors\SiteNotFoundException

![image](https://user-images.githubusercontent.com/1250017/51521856-7d3e2900-1e30-11e9-92fd-67a373019499.png)

### Steps to reproduce

1. Update to 3.1.x
2. Try changing a Site

### Additional info

- Craft version: Craft Pro 3.1.3
- PHP version: 7.3.0
- Database driver & version: MySQL 5.5.5
- Plugins & versions: All disabled

**Comment by brandonkelly** [comment]
I’m not able to reproduce this on my end. Can you please send your `composer.lock` and `composer.json` files over to support@craftcms.com, along with a database backup?

**Comment by darylknight** [comment]
Yep - sent yesterday. Further info, I think this might be related to PHP 7.3, as it works on my server (7.1.26), but not locally (7.3)

**Comment by owldesign** [comment]
I can confirm that I get this error on php 7.3 as well

**Comment by brandonkelly** [comment]
@owldesign We weren’t able to reproduce with @darylknight (and nor is he anymore). Maybe we’ll have better luck with you… can you send your `composer.json` and `composer.lock` files to support@craftcms.com with a DB backup?

**Comment by owldesign** [comment]
I want to mention that I am unable to reproduce is again. Looks like its back to working on PHP 7.3 locally.
