### ISSUE TITLE
SVG with class doesn't parse

### ISSUE THREAD

**Issue by 1stevengrant** [craftcms/cms#3688]
### Description

When I copy the example in the docs, https://docs.craftcms.com/v3/dev/functions.html#svg-svg-sanitize-namespace-class and attempt to pass a class attribute to the svg, I get a Twig syntax error.

### Steps to reproduce

1. in a Twig template, add `{{ svg('@webroot/icons/lemon.svg') }}` and replace the path with an svg in your public dir
2. refresh the browser and see the Twig syntax error `Unknown argument "class" for function "svg(svg, sanitize, namespace)".`

### Additional info

- Craft version:
- PHP version: 7.29
- Database driver & version: MySQL mysqlnd 5.0.12

**Comment by 1stevengrant** [comment]
update to `3.1.3` has resolved.

**Comment by brandonkelly** [comment]
Yeah that argument was added in 3.1.0.
