### ISSUE TITLE
Replace spaces in Asset subfolder names

### ISSUE THREAD

**Issue by NixonGit** [craftcms/cms#3689]
### Description

Currently it's possible for users to create a subfolder that contain spaces in the name. Craft then preserves these spaces in the file path. This is problematic when using the `img` `srcset` attribute and `getUrl()` as unlike the `src` attribute spaces are used as the delimiter for the descriptor. Spaces within the file url cause the browser to stop parsing and ignore `srcset`.

Craft should convert spaces in folder names to underscores (or similar) on folder creation, or disallow spaces entirely.

### Additional info

- Craft version: 3.1
- PHP version: 7.1

**Comment by brandonkelly** [comment]
I agree spaces shouldn’t ever be allowed, in filenames or subfolder names (unless a plugin were to modify the name after we’ve already removed the spaces ourselves).

**Comment by simpleim** [comment]
We just encountered this issue in 3.1.

I was pretty sure that this is a recent bug, and when testing on Craft 3.0.37, we found that subfolders with spaces are replaced with hyphens; e.g. "Banner Images" becomes "Banner-Images".

Since 3.1, this behaviour no longer occurs.
