### ISSUE TITLE
No Access to CP, reset Password and access granted

### ISSUE THREAD

**Issue by CreateSean** [craftcms/cms#3691]
### Description
Have site with a content freeze while updates and custom plugin are being worked on staging. On the live site users with CP access had that revoked by unchecking **access the CP** in their usergroup settings. User did password reset and now has access to the CP, had to manually revoke their permisions.

### Steps to reproduce

1. revoke CP access to usergroup
2. user does password reset
3. CP access is granted by doing the password reset.

### Additional info

- Craft version: 3.0.34
- PHP version:7.2.14
- Database driver & version: 
- Plugins & versions:

**Comment by brandonkelly** [comment]
Password reset doesn’t make any changes to permissions. Are you sure this user doesn’t just have the permission assigned directly to their account?

**Comment by CreateSean** [comment]
Brandon,

My client's (They're an agency) response:

> Honestly, I think we can just leave it as is. I went through and unchecked everything from the Site Admin permissions (not just the CP checked box). Hoping that fixes it. 

you can close this since it seems like everything is fine. Sorry for the trouble.

**Comment by brandonkelly** [comment]
No worries!
