### ISSUE TITLE
no web folder anymore. which folder is new root?

### ISSUE THREAD

**Issue by olsp** [craftcms/cms#3693]
Until recently, there used to be a "web" folder when installing craft via composer. Now there isn't one anylonger. How is the new workflow? Which folder has to be used as root for the domain? I don't have an index.php file in the root directory either.

**Comment by brandonkelly** [comment]
There still is – here it is in the `craftcms/craft` project that we recommend using to start up new Craft projects:

https://github.com/craftcms/craft/tree/master/web

**Comment by olsp** [comment]
But that's not what I get when I run `composer create-project craftcms/craft <Path>` as stated here: https://docs.craftcms.com/v3/installation.html#step-1-download-craft
