### ISSUE TITLE
Field instructions for fields does ignore single line breaks

### ISSUE THREAD

**Issue by christianruhstaller** [craftcms/cms#3694]
### Description
If you add an instruction to a field and the instruction contains a single new line this new line does not get outputted. If there are two line breaks Craft will add it as a paragraph. This works as expected but if it only contains one line break it does not output the expected result.

### Steps to reproduce

1. Add field instruction:
```
Test
Instruction
```
2. Edit an entry where the field is part of the layout and see only one line text

### Additional info

- Craft version: 3.0.37

**Comment by brandonkelly** [comment]
That’s expected and how other Markdown parses work as well. You should be able to add a `\` to the end of the first line to force a line break.
