### ISSUE TITLE
Firewall blocks /admin/login: Serialized PHP object in HTTP header

### ISSUE THREAD

**Issue by limesquare-nl** [craftcms/cms#3696]
### Description
One of our customers can't see the /admin/login page because their firewall blocks it.
Serialized PHP object in HTTP header
https://securitykb.stormshield.eu/us/6dbc52de301619a2.html

### Steps to reproduce

1. does not apply

### Additional info

- Craft version: Craft Pro 3.1.3
- PHP version: 7.1.14
- Database driver & version: MySQL 5.7.24
- Plugins & versions:

Amazon S3	1.0.8
Asset Rev	6.0.2
Bugsnag	2.0.1
Campaign Monitor Lists	1.1.3
Campaign Monitor Service	1.0.6
CodeMirror	1.0.1
Embedded Assets	1.0.2
Freeform Lite	2.5.8
Image Resizer	2.0.4
Mailgun	1.3.0
MobileDetect	1.0.2
Navigation	1.0.18
Position Fieldtype	1.0.14
Redactor	2.2.1
Redactor Custom Styles	3.0.2
Redirect plugin for Craft 3	1.0.18
SEOmatic	3.1.38
SimpleMap	3.3.4

**Comment by angrybrad** [comment]
Can you shoot an email to support@craftcms.com so we can further discuss this?

Going to go ahead and close this issue as potential security concerns should be emailed directly us (https://github.com/craftcms/cms/wiki/Security-Policy).
