### ISSUE TITLE
Database password that starts with "@" triggers "InvalidArgumentException"

### ISSUE THREAD

**Issue by transopticmedia** [craftcms/cms#3700]
### Description

I updated Craft today to the latest version (3.1.3), and started to get an "internal error" when going to _settings->assets_ or _settings->email._ The error message in the logs was: 

_`_yii\base\InvalidArgumentException: Invalid path alias: @L)o95Pqw5&=_`_ 

( eventually, I realized "@L)o95Pqw5&=" was the DB password set in .env)

The error line was: `/vendor/yiisoft/yii2/BaseYii.php:154`

It was easy to fix it by changing the password, but it took a while to figure out what was happening. I had the password set to that for several weeks with no issues until the update. 

### Steps to reproduce

1. Set your database pw to begin with "@"

### Additional info

- Craft version: 3.1.3
- PHP version: 7.2
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release.
