### ISSUE TITLE
Craft installs tables in PostgresSQL DB in public schema even after specifying DB_SCHEMA env variable

### ISSUE THREAD

**Issue by pacifier17** [craftcms/cms#3701]
### Description
We have specified an environment variable DB_SCHEMA as per [this doc](https://docs.craftcms.com/v3/config/db-settings.html). But still craft installs all the tables in public schema.
This is failing our craft installation as we are using a hosted PostgresSQL DB and we do not have permissions to create tables in the public schema.

### Steps to reproduce

1. Specify DB_SCHEMA variable in .env file with value anything other than 'public'
2. Run the craft installer.
3. It fails with message telling us that table creation failed as no schema was selected.

### Additional info

- Craft version: 3.0.33
- PHP version: 7.2.12
- Database driver & version: PostgreSQL 10.6

**Comment by brandonkelly** [comment]
This is actually a Yii bug: https://github.com/yiisoft/yii2/issues/12763

**Comment by pacifier17** [comment]
@brandonkelly looks like this Yii bug has been open for more than 2 years now and no one seems to be fixing it. Do you have any suggestion on how to work around this bug in Craft? Any custom setting in any file?

**Comment by brandonkelly** [comment]
Just looked into it a bit. If you want Craft to use a different schema, then you will need to change your [search_path](https://www.postgresql.org/docs/11/ddl-schemas.html#DDL-SCHEMAS-PATH) Postgres config setting to list that schema before `public`. Yii’s `yii\db\Schema::$defaultSchema` property (which Craft’s `schema` DB config setting maps to) is really just a way of telling Yii that it can safely omit that schema when building database queries. I’ve [updated the setting’s docblock](https://github.com/craftcms/cms/commit/4ffdab5b0da30a3caa7d093c0744e2f42af8c818) for the next release to clarify that.

**Comment by skoch** [comment]
I have updated the `search_path` as per the above and yet, I cannot get either a fresh install of Craft or use a DB dump with a different schema to work. Any tips here @brandonkelly?

```
// after restoring a DB with a different schema:
# \dt
                       List of relations
  Schema   |               Name                | Type  | Owner
-----------+-----------------------------------+-------+--------
 marketing | assetindexdata                    | table | craft3
 marketing | assets                            | table | craft3
...etc...
```

```
# show search_path;
    search_path
-------------------
 marketing, public
```

**Comment by brandonkelly** [comment]
@skoch Have you tried setting `defaultSchema` to `marketing` as well?

**Comment by skoch** [comment]
@brandonkelly I recall logging into the Docker image and echoing the variable correctly however will triple check to verify.
