### ISSUE TITLE
Strange asset display button group duplication

### ISSUE THREAD

**Issue by iamtompickering** [craftcms/cms#3702]
### Description
Came across some strange behaviour when creating sub folders in Assets. Every time I created a new subfolder, it added a new set of 'display' buttons into the toolbar (see screenshot attached). 

### Steps to reproduce

1. Create a new subfolder
2. Add an asset into it
3. Click out of the subfolder / into another and the duplicated buttons appear. 

### Additional info

- Craft version: 3.0.37
<img width="1801" alt="screenshot 2019-01-24 at 08 47 49" src="https://user-images.githubusercontent.com/6592882/51671679-5d8a3a80-1fc1-11e9-8b62-880d1b03e8a0.png">

**Comment by brandonkelly** [comment]
Fixed for the next release!
