### ISSUE TITLE
Duplicate an entry from entry list menu

### ISSUE THREAD

**Issue by robin-gauthier** [craftcms/cms#3705]
### Description
After a Craft update the duplicate link disappear from the menu when the user is not an administrator. The user group have all the permissions to all entry types on the website.

Admin:
![image](https://user-images.githubusercontent.com/39380569/51689194-2bc6a300-1fc4-11e9-9476-18b5682c1040.png)

User:
![image](https://user-images.githubusercontent.com/39380569/51689938-a217d500-1fc5-11e9-978d-d9dd66c4d6d2.png)

### Steps to reproduce

1. Login as a user who doesn't have admin access
2. Go to an entries list an select an entry with the checkbox
3. Open the actions menu and there's no duplicate button.
4. You can do the same step as an admin and the button is there.

### Additional info

- Craft version: 3.1.3
- PHP version: 7.0.32
- Database driver & version: MySql 5.6.34
- Plugins & versions:

Amazon S3  |  1.0.8
Amazon SES  |  1.1.0
CP Field Inspect  |  1.0.5
Craft Commerce  |  2.0.1
Embedded Assets  |  1.0.2
Image Resizer  |  2.0.4
PayPal for Craft Commerce  |  1.0.0.1
Redactor  |  2.2.1
Redirections  |  3.1.3
SEO  |  3.1.38
Super Table  |  dev-craft-3

**Comment by brandonkelly** [comment]
Fixed for the next release. Thanks for reporting!
