### ISSUE TITLE
Screenshots in the plugin store not showing correctly

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#3709]
### Description
In clicking through to the details of a plugin the the CP (eg enupal-translate) all screenshots are displayed on the first slide, while the correct number of slide indicator bullets are visible.

![screenshot 2019-01-25 at 08 46 35](https://user-images.githubusercontent.com/755428/51732433-89b7c100-207e-11e9-9147-2d9bb0dca805.png)

I assume this should work like it does on plugins.craftcms.com (http://plugins.craftcms.com/enupal-translate), where each screenshot has its own slide.

### Steps to reproduce

1. Visit a plugin with screenshots in the plugin store in the CP.
2. Click on the screenshots
3. Click the slider to go to the second slide

### Additional info

- Craft version: 3.1.4
- PHP version: 7.2.10
- Database driver & version: 5.7
- Plugins & versions: None

**Comment by benjamindavid** [comment]
Should be fixed in the next release. Thanks for reporting @janhenckens!
