### ISSUE TITLE
Error on adding/editing users

### ISSUE THREAD

**Issue by d13creative** [craftcms/cms#3712]
Adding a new user or editing an existing user in Craft version: 3.1.4 results in the following error whenever the first name or second name fields contain any text:

vendor/yiisoft/yii2/validators/UrlValidator.php
preg_match(): Delimiter must not be alphanumeric or backslash

This is not an issue in 3.1.3

**Comment by andris-sevcenko** [comment]
This has been fixed for the next release. You can edit your composer.json file to pull in these changes immediately by requiring Craft like this:

`"craftcms/cms": "dev-develop#05461658def6b40d5f6e46ddd3366bfa435b0715 as 3.1.4"`

and running `composer update`
