### ISSUE TITLE
Asset view icons showing in inconsistent places

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#3715]
### Description
When moving around files and renaming them in the CP, the top bar (where the search box, the sort order & the grid/list buttons are) reloads with some inconsistent placements.

For example: double grid/list icons

![screenshot 2019-01-25 at 14 39 01](https://user-images.githubusercontent.com/755428/51749497-d23ba280-20af-11e9-9f5b-9b8932f4b744.png)
 
On refresh they're back in the right place.

Sometimes they also show up twice on the right, like this:

![screen shot 2019-01-25 at 14 35 27](https://user-images.githubusercontent.com/755428/51749557-f7301580-20af-11e9-8f87-3bf13ea4620c.png)

### Steps to reproduce

1.  Select one or more assets and make changes to them through the links under the actions button
2. After 2/3 changes, the grid/list buttons will show up in different places.

### Additional info

- Craft version: 3.1.4
- PHP version: 7.2.10
- Database driver & version: 5.7
- Plugins & versions:

**Comment by andris-sevcenko** [comment]
Duplicate of #3702
