### ISSUE TITLE
CP lets you have no primary site selected in a multisite setup

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/cms#3720]
### Description

If you have more than 1 site setup, and you toggle between which one is the primary site, you can get into a position where you have no primary site selected, which in turn makes your entire site/cp inaccessible .

### Steps to reproduce

1. Setup a new multisite
2. Go into that new site, and toggle `is this the primary site` to `yes` (By doing this, it should make your default site not the primary site anymore)
3. Go back into the new multisite and toggle `is this the primary site` to `no`.

You should now have no primary site selected. 404 errors in the cp and the front-end.

### Additional info

- Craft version: 3.1.3
- PHP version: 7.1.26
- Database driver & version: MySQL 5.5.5
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Well that i dumb :) Fixed for the next release.

Are you able to re-set one of the sites as primary?

**Comment by jonleverrier** [comment]
I managed to reset it back to the default. project.yaml to the rescue !
