### ISSUE TITLE
Dropdown field doesn't respect the default value and returns NULL

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/cms#3724]
### Description

When you create a dropdown field and assign it a default value, in the CP the first value in your options is always shown and not the default value. The dropdown field also returns `null` even though a default is set.

### Steps to reproduce

1. Create a dropdown field
2. Create 3 options: alpha, beta, gamma
3. Set gamma as the default option
4. Go to an entry where the field is assigned
5. alpha is showing as the default option

### Additional info

- Craft version: 3.1.5
- PHP version: 7.1.26
- Database driver & version: MySQL 5.5.5
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
The default value only comes into play for new elements, not existing ones.

**Comment by jonleverrier** [comment]
Apologies for the false flag. This makes sense now!

**Comment by jonleverrier** [comment]
Related: https://github.com/craftcms/cms/issues/3379, https://github.com/craftcms/cms/issues/2446
