### ISSUE TITLE
Uninstalled plugins create an additional "missing" entry

### ISSUE THREAD

**Issue by AndrewMac** [craftcms/cms#3726]
### Description

For any and all plugins that are uninstalled, but not yet removed, there exists a corresponding "missing" plugin entry

### Steps to reproduce

1. Uninstall a plugin
2. Scroll to the bottom of the plugins screen, and wait a few seconds
3. A new row, "missing", will be created
4. Reinstall or remove the uninstalled plugin, and the unwanted "missing" row will disappear
5. Same behaviour exists for both commercial and free plugins
6. This has happened on all three local installs of current projects I have running

### Additional info

I first noticed this after updated to CraftCMS 3.1.4, and it's still present in 3.1.5. I can confirm that the issue goes away when reverting back to 3.1.3, and reappears on updating again to 3.1.5.

- Craft version: 3.1.5
- PHP version: 7.2.10
- Database driver & version: MySQL

**Comment by brandonkelly** [comment]
Fixed for the next release. Thanks for reporting!

**Comment by shoored** [comment]
I seem to be having the same issue on 3.5.19.1. Uninstalled plugins, removed composer packages, cleared all Craft caches. 

It's not showing "Missing" for all removed plugins, only 2 at the moment. 
One I have uninstalled through CP. The other one was done through CLI.

**Comment by brandonkelly** [comment]
@shoored Craft shows “Missing” plugins when it knows that you own a license for the plugin, which is associated with the current Craft CMS license. The plugin is fully uninstalled; it’s just there as a convenience because you might want to _install_ it.

You can detatch the plugin license from the Craft CMS license from https://id.craftcms.com.
