### ISSUE TITLE
Still able to access admin settings pages with `allowAdminChanges` => false

### ISSUE THREAD

**Issue by rjgux** [craftcms/cms#3728]
### Description

I'm not sure whether this should be labelled request or a bug. With `'allowAdminChanges'` set to **false** I can still access admin settings pages in the CMS e.g. _/admin/settings/sections_ or _/admin/settings/sections/new_ which is confusing.

Links to these pages are hidden in the sidebar, but can still access them via a URL. I'm not able to save these admin pages (throws the NotSupportedException - Changes to the project config are not possible while in read-only mode), but I wouldn't expect to see any page in the CMS where you can effect the config, before actually saving.

### Steps to reproduce

1. Open CMS admin
2. Navigate to an admin settings page via a URL

### Additional info

- Craft version: 3.1.5

**Comment by brandonkelly** [comment]
Fixed that for the next release. Thanks for the nudge!
