### ISSUE TITLE
project-config/sync should generate a yaml file if none exists

### ISSUE THREAD

**Issue by sjelfull** [craftcms/cms#3736]
### Description

I enabled the `useProjectConfigFile` setting and ran `project-config/sync` without knowing that it would wreck my installation.

Everything deletable like sites, sections, entry types etc. got a `dateDeleted` value, and i'm currently receiving the error ```An Error occurred while handling another error: craft\errors\SiteNotFoundException: No primary site exists``` when accessing the control panel.

I tried setting all the dateDeleted columns to `null`, including the sites - to no avail.

Shouldn't it generate a file if none exists?

### Steps to reproduce

1. Setup a new install.
2. Enable `useProjectConfigFile`.
3. Run `./craft project-config/sync` without visiting the CP.

**Comment by brandonkelly** [comment]
Yes it should.
