### ISSUE TITLE
Allow SMTP Port in Email Settings to be set to an environment variable

### ISSUE THREAD

**Issue by rungta** [craftcms/cms#3740]
### Description

With 3.1 we can now use environment variables for SMTP email settings. But this feature was not extended to the SMTP Port field. Different SMTP configurations on dev and production cannot truly live in the `.env` file if both SMTP servers do not share the same port (e.g. Mailgun on production uses 587, but Mailtrap on dev uses 465).

### Steps to reproduce

1. Go to _Settings > Email_
2. Set _Transport_ Type to `SMTP`
2. Set the value of the _Port_ field to a variable from your `.env` file, like `$SMTP_PORT` 

### Additional info

- Craft version: 3.1.5

**Comment by brandonkelly** [comment]
Correct. Is that something you need to set for each environment? Seems like 99% of the time the standard ports are used.

**Comment by rungta** [comment]
We use [Mailtrap](https://mailtrap.io/) (`25, 465, 2525`) for our dev environment installs and [Mailgun](https://www.mailgun.com/) (`25, 587, 465`) or Amazon SES (`25, 587, 2587`) for staging and production installs, and since these services [don’t always share the same port](https://www.mailgun.com/blog/which-smtp-port-understanding-ports-25-465-587), we need to set separate port values on dev and production.

(`25` is common but often blocked.)

**Comment by echantigny** [comment]
I'm also looking into this.  Locally, I use my gmail to test, but on the production server, it has it's own SMTP server that I can't use locally (blocked to localhost).  I would like to be able to set the transport type somehow, and the port would be required too at this point.

**Comment by brandonkelly** [comment]
Alright, as of the next release it will be possible to set Port to an environment variable.

**Comment by echantigny** [comment]
Any chance that will include a way to set the transport type too?  I would love to use the project config file, but impossible for me without a way to save that in a config.

**Comment by brandonkelly** [comment]
No that wouldn’t be possible; that’s why we allow you to [override the mailer transport](https://docs.craftcms.com/v3/config/app.html#mailer-component) at runtime.
