### ISSUE TITLE
[Feature Request] Add values and labels to Lightswitch fields

### ISSUE THREAD

**Issue by proimage** [craftcms/cms#3741]
I'd like the ability to customize the values of a Lightswitch field, as well as to display text labels alongside it:

![image](https://user-images.githubusercontent.com/1027523/51911200-e2b68a80-23d9-11e9-8708-284c1a726fc4.png)

Instead of the Lightswitch essentially being nothing more than a restyled checkbox, we could choose to add custom values and labels, at which point it would behave more like a 2-option dropdown menu (or a 2-input radio group with one preselected).

**Comment by proimage** [comment]
Just curious, any thoughts about when this might make it in to Craft?

**Comment by proimage** [comment]
@brandonkelly Here's an (apparently) yearly bump! ;) Just looking for an update, not (necessarily) implementation. :)

**Comment by brandonkelly** [comment]
I just happened to have a need for adding a label beside a Lightswitch input in 3.5, so went ahead and added a field setting to custom Lightswitch fields to take advantage of that.

![A Lightswitch field with a custom label beside it](https://user-images.githubusercontent.com/47792/90080058-756a0200-dcbe-11ea-99a9-0889e315c5a0.png)


Lightswitch fields are only meant to be used for enabling/disabling things, so not going to add support for a left-side label. Your Fit/Crop use case in the screenshot would make more sense implemented as a Dropdown/Radio Buttons field.

**Comment by proimage** [comment]
Hmm... I guess my original request is trying to tackle two separate issues:

### State ambiguity
The lightswitch on/off state is not the most obvious to discern. Two things change: color, and left-right position. 

1. The color change is between two colors that have very similar brightness levels, and relies solely on saturation to differentiate them; I imagine this is not very accessible (not to mention that color "meanings" aren't globally consistent, eg. China & red).
2. The left/right position, meanwhile, doesn't on its own say "on" or "off" (and don't even get me started on if the backend is set to an RTL language).

With those concerns, there should be a less ambiguous way to tell what state a lightswitch is in, ideally through some On/Off or Yes/No text to either side of the control. Having customizable text on one side certainly helps, but if that customization doesn't alter the boolean aspect of the underlying field, then why not add customizable text on the left as well?

One more aspect to mention related to this is that often when I try to click a lightswitch control, the mouse moves a pixel or two during the click. The lightswitch then translates the interaction as a drag operation that didn't go far enough to change the control, and does nothing. I'm not sure how you could solve that issue directly, but allowing text on both sides could give the user an element they could click to change the state to that side—one that isn't draggable in the first place and thus wouldn't have the problem the lightswitch itself does.

### Enhancement of field values
Having thought of that possible solution to the ambiguity of the lightswitch control, I took that a step further and figured why not allow the customizable text to represent customizable values, too? Obviously, at that point the functionality is more that of a 2-option dropdown menu than a boolean control.

---

At this point, I think that solving the first issue is far more important than the second (which isn't a problem to be solved as much as a possible enhancement).

**Comment by brandonkelly** [comment]
Actually yeah I take that back. Realized even normal lightswitches often have OFF labels.

![A lightswitch switched to the OFF position, revealing a “OFF” label](https://user-images.githubusercontent.com/47792/90136804-96b40800-dd29-11ea-9050-312f0be055c3.jpg)

So just went ahead and added an OFF label as well.

<img width="347" alt="A Lightswitch field revealing both ON and OFF labels" src="https://user-images.githubusercontent.com/47792/90136874-aaf80500-dd29-11ea-958b-9d29d6d6d983.png">

And now when you click on the labels, they will toggle the lightswitch based on the one you clicked on, instead of just focusing the input.

**Comment by brandonkelly** [comment]
Craft 3.5.4 is out now with these new Lightswitch field settings.

**Comment by proimage** [comment]
You rock, thanks so much!!
