### ISSUE TITLE
Where is 3.0.38?

### ISSUE THREAD

**Issue by hdpe** [craftcms/cms#3743]
### Description

The 3.0.38 release isn't mentioned in the docs (https://docs.craftcms.com/v3/installation.html#step-1-download-craft still points to 3.0.37 and latest as 3.1.5), and 3.0.38 can't be found when changing the URL to the same pattern as these other releases.

### Steps to reproduce

1. Go to https://docs.craftcms.com/v3/installation.html#step-1-download-craft
2. Expected latest 3.0.x release to be 3.0.38, actual is still 3.0.37

### Additional info

- Craft version: n/a
- PHP version: n/a
- Database driver & version: n/a
- Plugins & versions: n/a

Thanks

**Comment by sjwarner-bp** [comment]
Any progress on this? We'd love to be able to pull it down :slightly_smiling_face:

**Comment by angrybrad** [comment]
https://download.craftcdn.com/craft/3.0/Craft-3.0.40.zip (and 39 and 38) exists now and will get the docs updated shortly to point to the latest 3.0.40.

**Comment by brandonkelly** [comment]
Install instructions are updated now: https://docs.craftcms.com/v3/installation.html#step-1-download-craft

**Comment by hdpe** [comment]
Great, thanks!

**Comment by ricricucit** [comment]
@brandonkelly I still miss something I guess.

Reading from here: https://docs.craftcms.com/v3/installation.html#step-1-download-craft I get that I have to download from the CDN, and _get the files that I expect to have_.

BUT when reading here: https://craftcms.com/guides/downloading-previous-craft-versions I understand that the craft new versions are to be downloaded from the release packages on GitHub. 

Fair enough, **but** from GitHub I do not get the files that expect to have (same folder structure and files I get from the CDN)...so what am I missing?

**Comment by brandonkelly** [comment]
@ricricucit You’d need to start with installing Craft like normal, following the [installation instructions](https://docs.craftcms.com/v3/installation.html), and _then_ modify the `craftcms/cms` requirement based on the version you want.

**Comment by ricricucit** [comment]
Thank you.
Yes, that's what I've been doing until now, but that gives me the ability to only install the latest craft version (^3.0.0), while I would need to access all the version (or, anyway, specific versions).

Or, even better, where do I find all the downloadable versions, similar to the ones listed [here](https://docs.craftcms.com/v3/installation.html#step-1-download-craft)

I'm referring to:
- zip: 3.0.41, latest
- tar.gz: 3.0.41, latest

Thanks! :)

**Comment by brandonkelly** [comment]
We don’t have a public list of prior versions but if you want to get the distributed zip file for a specific version, use this URL template:

```
https://download.craftcdn.com/craft/<major>.<minor>/Craft-<major>.<minor>.<patch>.zip
```

So for example Craft 3.0.41 is

```
https://download.craftcdn.com/craft/3.0/Craft-3.0.41.zip
```

**Comment by ricricucit** [comment]
I did try this as well, but found some inconsistencies:

```
https://download.craftcdn.com/craft/3.1/Craft-3.1.18.tar.gz --> 👌 
https://download.craftcdn.com/craft/3.1/Craft-3.1.19.tar.gz --> 🚫 
https://download.craftcdn.com/craft/3.1/Craft-3.1.20.tar.gz --> 🚫
```

**Comment by ricricucit** [comment]
@brandonkelly do you have any hint that could help me here?

**Comment by brandonkelly** [comment]
What exactly do you need?

**Comment by ricricucit** [comment]
I'd basically like to understand why I cannot find newer versions (3.1.19+) and if I can rely on this URL template...

**Comment by brandonkelly** [comment]
Sorry, I’m following you now. Looks like our zip generation is broken for some reason. Pinging @angrybrad – https://craftcms.com/latest-v3.zip is giving me Craft 3.1.18, rather than 3.1.22 (the actual latest).

**Comment by angrybrad** [comment]
@ricricucit should be fixed now
