### ISSUE TITLE
[Feature Request] Default focal point setting per Asset volume or field

### ISSUE THREAD

**Issue by stevehurst** [craftcms/cms#3744]
We have a large Assets volume of profile pictures and headshots oriented to 5x7, but frequently have a need for square crops of the image. By default on a portrait, this results in a center crop on the chest and chin. There are likely other use cases where a focal point not set to center by default would be useful in transforms. You could set this default per Asset volume or field.

**Comment by brandonkelly** [comment]
Duplicate of #1906
