### ISSUE TITLE
Craft 3.1 breaks semantic versioning and composer version constraints

### ISSUE THREAD

**Issue by tjdraper** [craftcms/cms#3745]
### Description

The update from Craft 3.0 to Craft 3.1 introduces breaking changes in the way element source keys are referenced. https://craftcms.com/guides/updating-plugins-for-craft-3-1#update-element-source-key-references

Composer version constraints work on [semantic versioning](https://semver.org/). This breaking change requires updating Craft's version to 4.x. Because this was not done, breaking changes are introduced into a project by running `composer update` without changing version constraints in composer.json. This MUST not be allowed to happen in the future. I can't stress enough how much this breaks version constraints with composer and semantic versioning. Obviously this affected some of my projects where composer updates went live and introduced breaking changes into live projects.

### Steps to reproduce

1. Update from Craft 3.0 to Craft 3.1 with any plugin that references IDs instead of UIDs
2. Note subtle breakage of the application

### Recommended solution

Please do not introduce breaking changes that are not in accordance with semantic versioning. This breaks the way composer works and introduces breakages and bugs into live projects.

### Other

Yes I know I should have caught this in beta for my plugins. I've been very busy and didn't expect breaking changes based on the version number.

Also, I'm sorry. I know developing software is not easy and can be a thankless job. Particularly when you're getting bug reports from frustrated devs in situation like this such as myself. We'll all be alright, I'm working on my plugin to get it up to date with uid references instead of ID references. I'm only hoping we can prevent breaking semver in the future.

Thanks!

**Comment by brandonkelly** [comment]
Closing because there’s nothing we can do about this at this point, and we’ve beat the issue to death in Craft Slack.
