### ISSUE TITLE
EVENT_AFTER_SAVE_SECTION not really after save section

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#3747]
### Description
I have a tiny [plugin](https://github.com/studioespresso/craft3-defaulttab) that adds a tab to each newly created section.

Works fine on 3.0.39, but it's not working on 3.1.x

On 3.1, the section isn't saved to the database when the event fires. 
Guessing this has something to do with project config and it being saved to config but not to the database yet, though the problem also exists with project config disabled.

Anything I can do to fix this in the plugin?

### Additional info

- Craft version: 3.1.5
- PHP version: 7.2.10
- Database driver & version: 5.7
- Plugins & versions: Default Tab 1.3.0

**Comment by andris-sevcenko** [comment]
It should have worked, as that event is fired after saving a record to the database, but the fix implemented in studioespresso/craft3-defaulttab@3af079c5993eee8a77bca9e243abe6faf1f8965b works, too!
