### ISSUE TITLE
Can't save Table field with Date field in 3.1.6

### ISSUE THREAD

**Issue by engram-design** [craftcms/cms#3748]
### Description

Getting the error `Argument 1 passed to craft\helpers\DateTimeHelper::_parseDateTime() must be of the type string, null given, called in /Users/joshcrawford/public_html/craft31/vendor/craftcms/cms/src/helpers/DateTimeHelper.php on line 149`

Tracing the full error leads back to the ID for the newly created field.

This is pretty serious as it crashes the entire control panel - no page is accessible. Editing the settings for the Table field fixes this.

Field settings are (before editing):

`{"addRowLabel":"Add a row","maxRows":"","minRows":"","columns":{"col1":{"heading":"Date","handle":"date","width":"","type":"date"}},"defaults":{"row1":{"col1":null}},"columnType":"text"}`

### Steps to reproduce

1. Create a new table field, give it a name
2. Add a date field, give it a name
3. Ensure there's a single default row, but value is empty

### Additional info

- Craft version: 3.1.6
- PHP version: 7.0.31
- Database driver & version: MySQL 5.7.23

**Comment by brandonkelly** [comment]
Whoops, thanks! Just released 3.1.6.1 with a fix for this.
