### ISSUE TITLE
Admin unable to log in as other users when 'allowAdminChanges' => false

### ISSUE THREAD

**Issue by johnfmorton** [craftcms/cms#3749]
### Description

The title says it all. 

Admin-level users are unable to log in as other users when `'allowAdminChanges' => false`.

In 3.1.5 I was logging in as my other users and tweaking their account widgets but now that I'm in 3.1.6.1 I can no longer set up these accounts. 

I receive this error dialog box:

http://share.jmx2.com/1JcXT4

### Steps to reproduce

1. `'allowAdminChanges' => false` in config/general.php
2. Log in as admin
3. Attempt to log in as a lower level user (aka an "Editor" type of user)

### Additional info

- Craft version: 3.1.6.1
- PHP version: 7.3
- Database driver & version: MySQL 5.5
- Plugins & versions: Guest Entries

**Comment by brandonkelly** [comment]
Thanks for reporting that, it’s fixed for the next release!

To patch your install and get the fix early, change your `craftcms/cms` requirement in `composer.json` to:

```json
"require": {
  "craftcms/cms": "dev-develop#0cf5513a84020b927b1e5534e9c98cab950ccbf8 as 3.1.6.1",
  "...": "..."
}
```
