### ISSUE TITLE
ini_set and FPM mode

### ISSUE THREAD

**Issue by rinusvandam** [craftcms/cms#3756]
### Description
I'm running a Craft Pro site on a VPS with PHP in FPM mode. 

When i check the Craft installation at Utilities > System Report > Requirements ini_set calls keeps giving a warning: It appears calls to ini_set are not working for Craft. You may need to increase some settings in your php.ini file such as memory_limit and max_execution_time for long running operations like updating and asset transformations.

Craft is right, ini_set doesn't work in FPM mode. But memory_limit is set to 256 and max_execution_time to 120. Everything works fine like running updates and updating asset indexes. So shouldn't it check the memory_limit and max_execution_time values instead of ini_set? It feels strange that ini_set keeps warning me while everything work fine and is set the way it should be.

### Additional info

- Craft version: Craft Pro 3.1.6.1
- PHP version: 7.0.33
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
You have a good point, but we just talked through this internally and decided it’s worth keeping it around, as there are places in Yii and other dependencies that attempt to call `ini_set()` as well, for their own reasons.

**Comment by buckhornmktg** [comment]
Just FYI for others running FPM and getting the ini_set error. You can change your settings from php_admin_value (which can't be overridden by Craft) to php_value to clear the error. E.g. php_value[memory_limit]=256M not php_admin_value[memory_limit]=256M.
