### ISSUE TITLE
Slugs are generated for Singles on creation, but not updated on edit.

### ISSUE THREAD

**Issue by chasegiunta** [craftcms/cms#3758]
### Description
Even though slugs aren’t technically used by singles, that attribute is still created and populated on creation. A bit nice because if you’re finding an entry, you can use the same API (slug => 'xyz'), no matter which section type.

But, that Single's slug isn't updated whenever you edit it's title or URI.

This may not be a bug at all, but more of a question on whether it _should_ be updated or not, or at least something to note if #3368 ever happens. It just seems odd that the attribute lives there but is never touched after creation.

### Steps to reproduce

1. Create single.
2. View the slug attribute for that single.
3. Edit single.
4. Observe unchanged slug.

### Additional info

- Craft version: 3.1.6
- PHP version: 7.1.24

**Comment by brandonkelly** [comment]
We’re planning on making Single entry slugs editable in Craft 3.2 (#3368) so this won’t be awkward anymore at that point.
