### ISSUE TITLE
Feature Request: Update Plugin Store Image URLs for CSP Whitelisting

### ISSUE THREAD

**Issue by kgrote** [craftcms/cms#3759]
We're trying to implement [CSP headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) on our site which requires that we whitelist source domains for scripts and images. The Plugin Store serves images from `s3-us-west-2.amazonaws.com/plugin-icons.craftcms`, however we don't want to whitelist the entirety of `s3-us-west-2.amazonaws.com`. 

My suggestion is to create a CloudFront distribution that points to your `plugin-icons.craftcms` bucket, that way we can whitelist the unique CloudFront domain in our headers.

**Comment by angrybrad** [comment]
The plugin store is now pulling from a CDN using these URL if you want to whitelist them for CSP:

pluginicons.craft-cdn.com
avatars.craft-cdn.com
pluginscreenshots.craft-cdn.com
