### ISSUE TITLE
[Bug] Screen jumps when Matrix block header is clicked

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#3762]
### Description

I like to double-click the Matrix block headers to collapse/expand them. However, this often causes the entire page to move unexpectedly.

See this GIF... (1) successful double-click collapse, (2) the block jumps when I click the header:

![slippery matrix](https://user-images.githubusercontent.com/5309692/52105371-50fa7900-25a3-11e9-9938-07c7143a34ca.gif)

Oddly, this seems to be a side-effect of another quirk... Clicking the header bar will check/uncheck the block's checkbox. This in itself seems like undesirable behavior. There are several reasons to click the header (expand/collapse, move the block) which don't require the checkbox to be checked. Double-clicking multiple blocks will leave you with several random blocks checked for no reason.

>**Suggestion:** Decouple the behavior where clicking the header automatically checks the box. This would half-solve the issue.

Here is a related thread, posted when I thought CP Field Inspect might be contributing to the issue...

https://github.com/mmikkel/CpFieldInspect-Craft/issues/9

Several people on that thread (and on Slack) have been able to replicate this behavior.

### Steps to reproduce

1. Check the checkbox of a Matrix block.
2. Repeat until the page randomly jumps upward.

### Additional info

- Craft version: 3.0.40
- Browser version: Chrome on Mac
- Plugins: None (though CP Field Inspect seems to make it worse)

**Comment by jsunsawyer** [comment]
It seems to have something to do with the matrix block's height compared to the viewable area (where fields live).

When clicking on the top bar of a matrix block...

If a block is fully visible on the screen, no scroll happens.

If a block is taller than the viewable area, the block scrolls to the top.

If a block is shorter than the viewable area, the block scrolls so the bottom of the block is at the bottom.

**Comment by wooge** [comment]
It's acting as if there is JS that applies a scrolltop: 0  when collapsed.

**Comment by brandonkelly** [comment]
I’m able to reproduce and think I see what’s going on.

**Comment by brandonkelly** [comment]
Fixed for the next release!

**Comment by lindseydiloreto** [comment]
Sweet, thanks @brandonkelly! 🍺

**Comment by wooge** [comment]
Thank you!!!
