### ISSUE TITLE
Pressing Return inside the URI field on the Edit Section page creates a new Site row

### ISSUE THREAD

**Issue by rungta** [craftcms/cms#3765]
### Description

Pressing <kbd>Return</kbd> on the URI field while creating or editing a section's settings results in a new row being created. Most likely a regression introduced while addressing #3576.

### Steps to reproduce

1. Settings > Section > New Section
2. Click on the _Entry URI Format_ field
3. Press <kbd>Return</kbd>

### Additional info

- Craft version: 3.1.7

**Comment by brandonkelly** [comment]
Good catch! Just fixed that for the next release.
