### ISSUE TITLE
Error Levels for Custom Log Targets are not working

### ISSUE THREAD

**Issue by TheFox** [craftcms/cms#3766]
### Description

Consider this settings:

```php
// app.php
return [
    'components' => [
        'log' => function () {
            $logConfig = craft\helpers\App::logConfig();

            // Email Target
            $logConfig['targets'][] = [
                'class' => EmailTarget::class,
                'levels' => ['warning', 'error'],
                'message' => [
                    'from' => ['error@example.com'],
                    'to' => ['error@example.com'],
                    'subject' => 'My Project ERROR',
                ],
                'logVars' => [],
            ];

            // Instantiate and return the component.
            return Craft::createObject($logConfig);
        },
    ],
];
```

Then, very often, I get emails with the following text:

```
2019-02-01 10:37:14.312 +0100 [info][craft\queue\QueueLogBehavior::beforeExec]  [96] Deleting stale template caches (attempt: 1) - Started
...
```

This should not happen since I have only subscribed warning and error.

### Steps to reproduce

1. Create custom log target.
2. Wait for it.

### Additional info

- Craft version: Craft Pro 3.1.6.1
- PHP version: 7.2.13
- Database driver & version: MySQL 5.5.5

**Comment by TheFox** [comment]
Ok, I'll. Thanks.

**Comment by erktime** [comment]
@brandonkelly I recently had the same issue. I don't believe this is a YII bug but instead a Craft bug. Craft's custom `QueueLogBehavior` modifies all log targets setup for the site. Look at your code:
https://github.com/craftcms/cms/blob/develop/src/queue/QueueLogBehavior.php#L89

You override the `except` and `levels` for *every* log target, not just the default file target that craft uses by default.

**Comment by brandonkelly** [comment]
Doh, you are correct @erktime. 😞

**Comment by brandonkelly** [comment]
Fixed for the next release.

To get the fix early. change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#34e1fef8ee10754014ab1bc986b682ef5f0fa4a9",
  "...": "..."
}
```

Then run `composer update`.

**Comment by erktime** [comment]
Team work 👍
