### ISSUE TITLE
Overwriting a file: Duplicate error 

### ISSUE THREAD

**Issue by christianLuis** [craftcms/cms#3773]
### Description
When you upload a file (in my case it was an image) while editing entries, then delete it by the backends file manager and then upload it again, an SQL Error is thrown. You get informed that the file is already there (even though you just deleted it) and got to choose whether to keep the old file or overwrite it. In my case i went for overwriting. Afterwards the error is thrown. The new file entry is corrupted. 

### Steps to reproduce

1. Upload an file (e.g. image) while editing entries 
2. Delete the file by the backends file manager
3. Upload the same image again

### Additional info

- Craft version: Craft Solo 3.1.7
- PHP version: 7.1.26
- Database driver & version: MySQL 5.7.23
- Plugins & versions:
-- Yii version	2.0.15.1
-- Twig version	2.6.2
-- Guzzle version	6.3.3
-- Imagine version	0.7-dev
-- CKEditor	1.0.0-beta.2
-- Typed link field	1.0.16

**Comment by andris-sevcenko** [comment]
This should be fixed via 03bbc56
