### ISSUE TITLE
System Message settings error with allowAdminChanges => false

### ISSUE THREAD

**Issue by AndrewMac** [craftcms/cms#3775]
### Description

With allowAdminChanges set to false it is still possible to see the Edit widget in Utilities > System Messages, but clicking the message does nothing but flash "An unknown error occurred" at the top of the screen.

I'm not sure what the intended behaviour is, though: with allowAdminChanges set to "false" should it be possible to edit these messages, or should attempting to do so instead throw the "Unauthorised: Administrative changes are disallowed in this environment" response (rather than "unknown error")?

### Steps to reproduce

1. Go to Utilities > System Messages
2. Hover and click a message
3. "An unknown error occurred" will flash at the top of the screen

### Additional info

- Craft version: 3.1.7
- PHP version: 7.2.14
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thank for reporting that! Fixed for the next release.
