### ISSUE TITLE
Asset modal interface is unusable on mobile

### ISSUE THREAD

**Issue by robarov** [craftcms/cms#3781]
### Description
The interface of the Asset modal on mobile makes it almost impossible to select or upload files.

### Screenshot
![schermafbeelding 2019-02-04 om 17 40 29](https://user-images.githubusercontent.com/869705/52222778-a2a54b00-28a4-11e9-9e98-37ff7ee11680.png)

### Steps to reproduce

1. Open the CP on a mobile device
2. Upload a file

### Additional info
Craft version: All

**Comment by gcamacho079** [comment]
This will be fixed in an upcoming release. 👍🏼
