### ISSUE TITLE
UserSettings: Key "photoVolumeUid" for array with keys "fieldLayouts, groups" does not exist.

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#3783]
### Description

I'm seeing the following error on `admin/settings/users/settings`:

```
Key "photoVolumeUid" for array with keys "fieldLayouts, groups" does not exist.
```

Screenshot:
<img width="1490" alt="screen shot 2019-02-05 at 08 17 18" src="https://user-images.githubusercontent.com/378974/52258209-7b8b5f80-291e-11e9-9832-d1301448178d.png">

### Steps to reproduce

1. Install Craft
2. Go to admin/settings/users/settings

### Additional info

- Craft version: 3.1.8
- PHP version: 7.3.1
- Database driver & version: PostgreSQL 10.6
- Plugins & versions: N/A

**Comment by boboldehampsink** [comment]
I added a fix for this but I found that there is already a migration that is supposed to fix this. I came to this point by setting up a new installation with an existing (older) project.yaml. In that case the migration is not executed.

**Comment by brandonkelly** [comment]
The bug here is that Craft’s installer shouldn’t be applying the current `project.yaml` file if the Craft schema version in there doesn’t match up with what’s actually installed. (That was already the case for plugin schema versions.) Fixed for the next release.
