### ISSUE TITLE
Cannot change any setting, like fields or sections

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#3785]
I have section with "Propagate entries across all enabled sites" setting enabled. When i uncheck it click save, it shows success message. But when i open section settings again, it is still checked. Section entries are also still propagated, so nothing changed at all.

**edit:** 
Actually it seems that EVERY thing among fields or sections settings cannot be changed. And not only in this single craft install, i have another one on server (its staging server) with craft 3.1.8, and it also has this problem.

This problem occurs on remote linux server. On localhost windows machine i don't experience it.

**My system info:**
PHP version	7.2.11
Database driver & version	MySQL 5.6.39
Image driver & version	GD 7.2.11
Craft edition & version	Craft Pro 3.1.7
Yii version	2.0.15.1
Twig version	2.6.2
Guzzle version	6.3.3
Imagine version	0.7-dev
Plugins
CP Field Inspect	1.0.5
Entry Instructions	1.0.4
Field Manager	2.0.4
Imager	v2.1.4
MobileDetect	1.0.2
Navigation	1.0.18
Redactor	2.3.1
Retour	3.1.5
SEOmatic	3.1.40
Translations	1.2.0

**Comment by brandonkelly** [comment]
Can you please send a database backup and your `composer.json` and `composer.lock` files over to support@craftcms.com so we can try reproducing it on our end?
