### ISSUE TITLE
Unable to clear Control Panel resources using ./craft clear-caches/all

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#3787]
### Description
I'm trying to use the .`/craft clear-caches/all` CLI command.

Everything is working fine, except that I always get this error:

`Error clearing cache Control Panel resources: Unable to clear Control Panel resources because the location isn't known for console commands.`

My configuration returns these values:
- `Craft::$app->getConfig()->getGeneral()->resourceBasePath` -> `@webroot/cpresources`
- `Craft::getAlias('@webroot')` -> return correct value (using `/htdocs` as root folder)

I tried on another Craft 3.1 website, and got the same error. So perhaps it is a bug.

### Steps to reproduce

1. Use the `./craft clear-caches/all` command

### Additional info

- Craft version: 3.1.8
- PHP version: 7.1.8
- Database driver & version: PostgreSQL 9.6.9

**Comment by brandonkelly** [comment]
That’s because `@webroot` is only reliable on web requests. To fix, update your [resourceBasePath](https://docs.craftcms.com/v3/config/config-settings.html#resourcebasepath) config setting to a real path:

```php
'resourceBasePath' => dirname(__DIR__) . '/web/cpresources';
```

**Comment by brandonkelly** [comment]
As of the next release, the `clear-caches` console command will clear CP resources if the `@webroot` was custom-defined by the [aliases](https://docs.craftcms.com/v3/config/config-settings.html#aliases) config setting as well.

```php
'aliases' => [
    '@webroot' => dirname(__DIR__) . '/web',
],
```
