### ISSUE TITLE
Customize sources with allowAdminChanges disabled

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#3788]
### Description

An error is thrown when clicking Customize Sources button with `allowAdminChanges` disabled.

```
yii\web\ForbiddenHttpException: Administrative changes are disallowed in this environment. in /usr/www/users/me/site/vendor/craftcms/cms/src/web/Controller.php:201
```

### Steps to reproduce

1. Disable `allowAdminChanges` general.php 
2. Click Customize Sources button in a element index

### Additional info

- Craft version: 3.1.8

**Comment by carlcs** [comment]
Related to issue #3658

**Comment by brandonkelly** [comment]
Fixed for the next release!
