### ISSUE TITLE
Request missing required param when trying to set new password

### ISSUE THREAD

**Issue by magnusskogen** [craftcms/cms#3790]
When trying to set password for a user, the access URL generates a 400 Bad Request, with the error `Request missing required param`. The URL that is accessed is
`/admin/actions/users/set-password?code=Qjn8auhAJZty3loxuHK8ay1j24TC6VZp&id=721d236b-e9d2-40a2-8edf-85478a4bcbe0`. Same error for for all users in all user groups.

### Steps to reproduce

1. Go to a user, click gear icon and click "Copy password reset URL".
2. Access URL.

### Additional info

- Craft version: 3.1.5
- PHP version: 7.2.14-1
- Database driver & version: MySQL 5.7
- Plugins & versions: None

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you try updating to 3.1.8 and see if that fixes it? If not, please use the Craft Support widget on your Dashboard to send in a support request, and reference this issue URL.

**Comment by angrybrad** [comment]
@magnusskogen can you share your Craft public .htaccess file?  My guess is you've got a rewrite rule that's dropping querystring params.

**Comment by magnusskogen** [comment]
That was it, @angrybrad. Many thanks!
