### ISSUE TITLE
Default entry status ignored, always enabled

### ISSUE THREAD

**Issue by skoften** [craftcms/cms#3791]
Ok so I added a second site yesterday and now the default entry status in the section configuration seems to be ignored; the entry is always enabled by default.

I tested it on another install with only 1 site configured and this seem to work fine. So probably only an issue in case of a multi site configuration?

Running Craft CMS 3.1.8

**Comment by brandonkelly** [comment]
Is it being ignored by existing entries or brand new entries, or both?

**Comment by skoften** [comment]
It's ignored when creating a new entry; I have to switch it manually to disabled, but the default status in the section is set to disabled. Used to work fine, but after adding a second site this changed.

**Comment by brandonkelly** [comment]
I’m not able to reproduce that. New entries are enabled/disabled for each site in accordance with the section’s settings.

Can you please contact us from your Craft Support widget on your Dashboard, and reference this GitHub issue URL?

**Comment by mark-chief** [comment]
Same for me. 

I changed the setting on an existing Section, and new entries are not reflecting the change and are enabled by default.

Craft Pro v3.1.8
PHP v7.2

<img width="1042" alt="screen shot 2019-02-08 at 10 19 22" src="https://user-images.githubusercontent.com/18699249/52472878-59971480-2b8c-11e9-9ee6-c02b1f3f780d.png">
<img width="1050" alt="screen shot 2019-02-08 at 10 18 33" src="https://user-images.githubusercontent.com/18699249/52472879-5a2fab00-2b8c-11e9-9dc4-07b0fb677210.png">

**Comment by brandonkelly** [comment]
Ahhh, OK I’m able to reproduce when “Propagate entries across all enabled sites?” is disabled.

**Comment by brandonkelly** [comment]
Fixed for the next release.

**Comment by skoften** [comment]
Hm, I updated the EntriesController.php with your changes, but it doesn't seem to have any effect; the default status is still enabled.

<img width="708" alt="screenshot 2019-02-08 at 12 27 04" src="https://user-images.githubusercontent.com/1286410/52475851-26a94c80-2b9d-11e9-8ff4-178d9288f71f.png">

<img width="744" alt="screenshot 2019-02-08 at 12 27 36" src="https://user-images.githubusercontent.com/1286410/52475854-28731000-2b9d-11e9-98f8-647ab9d7fe71.png">

**Comment by brandonkelly** [comment]
@skoften Yeah you’re right. The fix only worked for sections with more than one enabled site. Just implemented a better fix that seems to be working correctly across all the different scenarios.

Rather than editing the code manually, you can test the fix early by editing your `craftcms/cms` requirement in composer.json:

```json
"require": {
  "craftcms/cms": "dev-develop#6680a10a1fe4de0516d027272a88f67dfca25a6f as 3.1.8",
  "...": "..."
}
```

Then go to your project in your terminal and run `composer update`.

**Comment by skoften** [comment]
Thanks! But I can't test it though, because I get an 503 after updating with that development version;

<img width="1122" alt="screenshot 2019-02-08 at 15 13 36" src="https://user-images.githubusercontent.com/1286410/52483542-8101d780-2bb4-11e9-9346-163326f7ae08.png">

**Comment by brandonkelly** [comment]
That should only happen on the front-end. If you visit your Control Panel you should be given the opportunity to run the new migrations.
