### ISSUE TITLE
Project Config's dateModified is updated even when there are no changes

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#3792]
### Description

I wonder if it is necessary to update the project.yaml `dateModified` when there's no changes? Makes me have to commit or discard it every time.

### Steps to reproduce

1. Install a new Craft project from an existing project.yaml
2. After running install, run `craft project-config/sync`
3. project.yaml's `dateModified` is updated, but nothing else

### Additional info

- Craft version: 3.1.8
- PHP version: 7.3.1
- Database driver & version: PostgreSQL 10.6
- Plugins & versions: N/A

**Comment by andris-sevcenko** [comment]
This has been resolved with c20adf2bca58d16a3adbe78b2ceef37b90947797

**Comment by boboldehampsink** [comment]
Just updated to 3.1.12 but this still happens

**Comment by jorenvanhee** [comment]
Can confirm. Only happens when applying a project-config file to a fresh Craft installation.

**Comment by brandonkelly** [comment]
@boboldehampsink Is that where you were seeing this too—when installing Craft?

**Comment by boboldehampsink** [comment]
Yes, see description

**Comment by brandonkelly** [comment]
Sorry, missed that. Why is step 2 necessary in the first place? There shouldn’t be any chances left to sync after installing Craft with an existing `config/project.yaml` file.

**Comment by boboldehampsink** [comment]
In case Craft is already installed
