### ISSUE TITLE
Image rotation throws JS error

### ISSUE THREAD

**Issue by RobinWithouck** [craftcms/cms#3793]
### Description
When I try to rotate an image in the image editor and save the image, I get an javascript error. 
The error shows when I try to save the image. The modal does not disappear.

### Steps to reproduce

1. Go to assets -> double click an image and click Edit.
2. Rotate the image.
3. Save the image

### Additional info

- Craft version: Craft Pro 3.1.8
- PHP version: 7.0.29

![screenshot 2019-02-06 at 16 07 55](https://user-images.githubusercontent.com/6160509/52351252-ab278e00-2a2a-11e9-8b9d-9ce11ca827c0.png)

**Comment by andris-sevcenko** [comment]
So you get an error when you actually try to save the image? Can you reproduce this and send your log folder to support@craftcms.com referencing this issue?
