### ISSUE TITLE
Missing share button in entry editing form

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#3794]
I notided that recently share button disappeared from entry editing form. Probably it has something to do with update.

I know that button won't be displayed if craft cannot render entry because it cannot find template, but its not the case, entries can be accessed from frontend.

**Application Info**
PHP version	7.2.12
Database driver & version	MySQL 5.5.5
Image driver & version	GD 7.2.12
Craft edition & version	Craft Solo 3.1.8
Yii version	2.0.15.1
Twig version	2.6.2
Guzzle version	6.3.3
Imagine version	0.7-dev

**Plugins**
CP Field Inspect	1.0.5
Element Map	1.2.1
Enupal Translate	1.2.0
Imager	v2.1.4
Image Resizer	2.0.4
Imager Pretransform	2.0.2
MobileDetect	1.0.2
Position Fieldtype	1.0.14
Redactor	2.3.1
Retour	3.1.6
SEOmatic	3.1.40
Smart Map	3.2.1
Super Table	2.1.6
Template Comments	1.0.5
Typed link field	1.0.17
Wordsmith	3.0.4

**Comment by piotrpog** [comment]
Little update about this problem..
It turns out that  my adblocker browser addon blocked this button. I have "NoAds - Adblocker" installed on chrome.

**Comment by brandonkelly** [comment]
Sounds like a bug with your ad blocker.

**Comment by hiasl** [comment]
Hey Brandon,
sorry I missed that. I even tried the "View" button but only looked for the "x-something" hash in the URL, which does not appear unless it's a draft.
Thanks.
