### ISSUE TITLE
Recent Entries Widget Shows Entries Based on Update Date

### ISSUE THREAD

**Issue by kgrote** [craftcms/cms#3806]
### Description
The "Recent Entries" widget on the dashboard homepage shows entries based on most recent update date, not most recent publish date. I would recommend either a) changing the widget title to read "Recent Updates" or b) changing the widget to display entries based on publish date.

### Additional info

- Craft version: 3.1.7

**Comment by carlcs** [comment]
It’s actually showing Recently Created Entries for me, which I think is pretty useful. If you’d rather have a widget that sorts by the post date, you could take a look at the [DIY widget](https://plugins.craftcms.com/diy-widget) plugin I wrote.

**Comment by brandonkelly** [comment]
Right it’s meant to be ordered by date created.
