### ISSUE TITLE
Unrelated columns in matrixcontent tables

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#3810]
### Description

I don’t have steps to reproduce, but there are columns in my matrixcontent tables that I never created for the respective block types. The columns don’t follow the naming schema for custom fields in a block type, the part for the block type handle is missing.

Examples:
`field_endDate`
`field_ticketOrderUrl`

I have fields with this handles in my global context, but I am very sure I never created them within any Matrix field. This installation was created with 3.1 from the start.

The issue might be related to #3809 

### Additional info

- Craft version: 3.1.8
- Database driver & version: MySQL

**Comment by brandonkelly** [comment]
Hm, strange. Can you check if you have any database backups from before these columns were added? What is the version in the `info` table at the time? What is the first Craft version where you see the fields show up? (Note that the Craft version listed in Craft’s auto-generated backup files will generally be the version that you were updating _to_ at the time, as backups aren't made until after Composer is done fetching the new version. So it’s best to just look at the actual `info` table value.)

**Comment by carlcs** [comment]
Sorry, but I didn’t find any backups that don’t have these columns. In the meantime I have added many more global fields and fields in Matrix block types, and the issue didn’t happen again.

It’s probably best to close here, until someone runs into the same issue and can provide more info.
