### ISSUE TITLE
Unserialize - Migration issue

### ISSUE THREAD

**Issue by kinoli** [craftcms/cms#3812]
### Description
I'm trying to migrate to a server from my local environment. I keep getting Internal Server Error. I have the latest version of 3+ of CraftCMS. Everything works fine locally but on the server not so much. Here is what I'm seeing in my Craft log file.
```
    2019-02-08 05:02:35 [-][-][-][error][yii\base\ErrorException:8] yii\base\ErrorException: unserialize(): Error at offset 352 of 93525 bytes in /home/kinoliclients/public_html/jbbls/cms/vendor/craftcms/cms/src/services/ProjectConfig.php:997
Stack trace:
#0 /home/kinoliclients/public_html/jbbls/cms/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError(8, 'unserialize(): ...', '/home/kinolicli...', 997)
#1 [internal function]: craft\web\ErrorHandler->handleError(8, 'unserialize(): ...', '/home/kinolicli...', 997, Array)
#2 /home/kinoliclients/public_html/jbbls/cms/vendor/craftcms/cms/src/services/ProjectConfig.php(997): unserialize('a:17:{s:12:"dat...', Array)
#3 /home/kinoliclients/public_html/jbbls/cms/vendor/craftcms/cms/src/services/ProjectConfig.php(982): craft\services\ProjectConfig->_getStoredConfig()
#4 /home/kinoliclients/public_html/jbbls/cms/vendor/craftcms/cms/src/services/ProjectConfig.php(912): craft\services\ProjectConfig->_getLoadedConfig()
#5 /home/kinoliclients/public_html/jbbls/cms/vendor/craftcms/cms/src/services/ProjectConfig.php(227): craft\services\ProjectConfig->_getConfigurationFromYaml()
#6 /home/kinoliclients/public_html/jbbls/cms/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\services\ProjectConfig->init()
#7 [internal function]: yii\base\BaseObject->__construct(Array)
```
The PHP log file gives a bit more information.
```
[08-Feb-2019 13:36:48 UTC] PHP Notice:  unserialize(): Error at offset 352 of 93525 bytes in /home/kinoliclients/public_html/jbbls/cms/vendor/craftcms/cms/src/services/ProjectConfig.php on line 997
[08-Feb-2019 13:36:48 UTC] An Error occurred while handling another error:
TypeError: Return value of craft\services\ProjectConfig::_getStoredConfig() must be of the type array, boolean returned in /home/kinoliclients/public_html/jbbls/cms/vendor/craftcms/cms/src/services/ProjectConfig.php:997
Stack trace:
#0 /home/kinoliclients/public_html/jbbls/cms/vendor/craftcms/cms/src/services/ProjectConfig.php(982): craft\services\ProjectConfig->_getStoredConfig()
```
Also, just for context. I had the site running on the remote server but then did an update (the one that said, this is a difficult update). The update put it in a vegetative state (internal server error). The same update worked locally, so I then copied the files and database to the remote server hoping that would fix the issue remotely. However, it didn't. Was their a new PHP extension requirement or something, that might have done this?

### Additional info

- Craft version: The very latest
- PHP version: 7.2

Here's what I'm seeing in the browser (http://jobbliss.kinoliclients.com/).

<img width="1650" alt="screen shot 2019-02-08 at 8 20 05 pm" src="https://user-images.githubusercontent.com/61486/52515895-0b5f3100-2bdf-11e9-9e6f-0af39f31406f.png">

**Comment by kinoli** [comment]
I figured it out. When I migrated to the new server, I updated the exported sql with the new domain. This messed up the serialized data in the `craft_info` table. When you do that, you need to update the character count, which is right before the domain string. If you don't, then you will get that unserialize error because the unserialization won't work otherwise.

**Comment by wineworkskeith** [comment]
@kinoli would you mind elaborating a bit on this? I'm getting the same error after trying to update my craft site. No new domains or migration occurred on my install so I'm not 100% sure it's related, but I'm getting the same error and line as you

**Comment by kinoli** [comment]
If you did a find replace in the database dump with your new domain, the serialized data within the craft_info table will be off. Basically, it serializes it with a total character count. Update the character count to fix the issue (this is in the sql file that you modified).
