### ISSUE TITLE
Asset volume order is not saved

### ISSUE THREAD

**Issue by timprint** [craftcms/cms#3813]
### Description

When re-arranging the order of asset volumes by dragging in /admin/settings/assets the order is not saved. The blue confirmation notice is shown "New Order Saved" but when you leave the page and then return to it the new order has not been saved. It is back to the original order. There is no way to re-arrange the order.

### Steps to reproduce

1.  Re-order volumes by dragging /admin/settings/assets
2. Leave page and return

### Additional info

- Craft version: 3.1.8
- PHP version: 7.3.1
- Database driver & version: MySQL 5.7.25
- Plugins & versions:
Freeform Lite 2.5.11
Imager v2.1.4 
Redactor 2.3.1
Retour 3.1.6
SEOMatic 3.1.42
oEmBed 1.0.5

**Comment by carlcs** [comment]
@timprint there an issue for that already #3764

**Comment by timprint** [comment]
@carlcs Ah, thanks. I'll close this.
