### ISSUE TITLE
User cannot edit section if section type was changed

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#3815]
Steps to reproduce:

- create user
- give him rights to editing specific section that is single type, user can edit section
- change section type to channel
- user cannot edit entries of this section

I can send you DB backup of craft install i encountered this if its needed. 

Also, little update:
Performing permission check in Twig template for user in question returns true. But user still cannot edit these entries in control panel:
```
{% set permission = 'editEntries:' ~ entry.getSection().uid %}
{{currentUser.can(permission)}}
```

system info:
Application Info
PHP version	7.2.2
Database driver & version	MySQL 5.5.5
Image driver & version	GD 7.2.2
Craft edition & version	Craft Pro 3.1.8
Yii version	2.0.15.1
Twig version	2.6.2
Guzzle version	6.3.3
Imagine version	0.7-dev
Plugins
No plugins are enabled.

**Comment by brandonkelly** [comment]
This is intended behavior, if perhaps unexpected:

1. When you create the Single section, the entry that is created along with it does not have an author.
2. When you convert the section to a Channel, that entry still doesn’t have an author.
3. When you are viewing a Channel/Structure section on the Entries index page, if you don’t have the “Edit other authors’ entries” permission for the section, then Craft will only show you entries where you are set as the author. Therefor the entry doesn’t show up.

To get it to show up, either grant your user the “Edit other authors’ entries” permission, or edit the entry and assign them as the author.

**Comment by narration-sd** [comment]
maybe it should assign the author at conversion to the logged in admin/user?
