### ISSUE TITLE
[Feature Request] Ability to use aliases in `renderTemplate`

### ISSUE THREAD

**Issue by benface** [craftcms/cms#3819]
I like to put templates related to my custom field types (settings.twig, input.twig) in the field's folder rather than in the module's `templates` folder, but then I have to render them like this:

```
Craft::$app->getView()->renderTemplate('module/../fields/my-custom-field/templates/settings');
```
(where `module` is a CP-registered template root)

But since my module has a `@module` alias that points to its folder, it would be nice to be able to do it like this:

```
Craft::$app->getView()->renderTemplate('@module/fields/my-custom-field/templates/settings');
```

Not much shorter, but feels cleaner without the `../`. Unfortunately it doesn't work... Would it be possible or does it go against the "template roots" concept?

**Comment by brandonkelly** [comment]
This could potentially lead to some security issues, as it would enable Twig to load a lot of textual files that were never intended to be parsed by Twig.

**Comment by benface** [comment]
Gotcha!
