### ISSUE TITLE
Special chars in slugs please not based on CP language

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#3820]
### Description
The slug special chars work different in relation to the cp language. It's a problem for me. We use mostly EN as CP language but now, the slugs are incorrect (möchte => mochte) this are totally different meanings for this word. When I change the language to german it's fine. But why is the special char handling not the same for alle cp languages? Can't find a setting to handle that for slugs particular.

### Steps to reproduce

1. Use german as CP lang => all fine (möchte => moechte)
2. Use english as CP lang => broken (möchte => mochte)

### Additional info

- Craft version: 3.1.8
- PHP version: 7.2

**Comment by carlcs** [comment]
Yeah I think it should use the language of the site you’re currently editing the entry for. Doesn’t make sense to use the current user’s language (what @davidhellmann means with CP language).

**Comment by davidhellmann** [comment]
Yes, site language is more clear as cp lang.

**Comment by brandonkelly** [comment]
Fixed this for the next release.

**Comment by davidhellmann** [comment]
Thanks brandon!

**Comment by davidhellmann** [comment]
@brandonkelly another issue related to this is the search within the CP. When I search for something like `österreich` with a german umlaut in it I get null results. Maybe it can be also  related to the matching site?

**Comment by brandonkelly** [comment]
@davidhellmann Can you post a new issue please?

**Comment by davidhellmann** [comment]
Sure!
