### ISSUE TITLE
ElementHelper::supportedSitesForElement's static $siteUidMap is problematic

### ISSUE THREAD

**Issue by nicholasc** [craftcms/cms#3824]
### Description
We have cli script that installs and configures Craft 3 and since we updated craft to 3.1.8 it has stopped working properly. After investigating we figured the our problem was the new `static $siteUidMap` that is used to store each site uid. When Craft installs, the static variable is filled with the uid of the default site. So when we decide to programmatically add a new site and create a section for it, it does not exist in the `static $siteUidMap` array causing an undefined index '2' at [line 233](https://github.com/craftcms/cms/blob/13270004dbb83a4865c584b9ec05d91e7b870bd8/src/helpers/ElementHelper.php#L233).

### Steps to reproduce

1. Install craft programatically using the `$app->runAction`. This at some point uses the `ElementHelper::supportedSitesForElement` function therefore populating the `static $siteUidMap` [here](https://github.com/craftcms/cms/blob/13270004dbb83a4865c584b9ec05d91e7b870bd8/src/helpers/ElementHelper.php#L213-L222).
```php
Craft::$app->runAction('install/craft', [
    'username' => $username,
    'password' => $password,
    'email'    => $email,
    'language' => $lang,
    'siteUrl'  => '@web',
    'siteName' => $this->siteName,
]);
```

2. Create a new site with the same group id used in the default one. When we do this, there should be a way to inform the `static $siteUidMap` about this new site.
```php
Craft::$app->getSites()->saveSite(new Site([
    'groupId' => $defaultSite->groupId,
    'name' => 'Alternate',
    'handle' => 'alt',
    'hasUrls' => true,
    'baseUrl' => '@web/alt/',
    'language' => 'en'
]));
```

3. Create a home section for all the new sites effectively crashing the script because it cannot find the uid for the alternate site that we created.

```php
$homeSection = new Section([
    'name' => 'Home',
    'handle' => 'home',
    'type' => Section::TYPE_SINGLE,
    'enableVersioning' => false,
    'propagateEntries' => true,
]);

$allSiteSettings = [];
foreach (Craft::$app->getSites()->getAllSites() as $site) {
    $siteSettings = new Section_SiteSettings([
        'siteId' => $site->id,
        'hasUrls' => true,
        'uriFormat' => '__home__',
        'template' => 'index',
    ]);

    $allSiteSettings[$site->id] = $siteSettings;
}

$homeSection->setSiteSettings($allSiteSettings);
        
// this crashes because `static $siteUidMap[2]` is not defined.
Craft::$app->getSections()->saveSection($homeSection);
```

### Additional info

- Craft version: 3.1.8
- PHP version: 7.1.19
- Database driver & version: mariadb 10.3.12
- Plugins & versions: None

**Comment by brandonkelly** [comment]
Fixed for the next release. Thanks for tracking that down and reporting it!
