### ISSUE TITLE
Why can't a section both have hasUrls set to false and a template configured?

### ISSUE THREAD

**Issue by pieterbeulque** [craftcms/cms#3830]
https://github.com/craftcms/cms/blob/e97588fb197fc88a9ea497e0d0c0a29874ef2250/src/services/Sections.php#L649-L655

I'm having trouble using `Craft::$app->sections->saveSection($section)` to create a section with settings configured like this:

```php
new Section_SiteSettings([
  'siteId' => $site->id,
  'hasUrls' => false,
  'uriFormat' => 'IGNORE', // This is neccessary to skip validation errors, somehow
  'template' => 'myTemplate',
]);
```

Am I trying to do something that I shouldn't try to do or is this a bug?

**Comment by pieterbeulque** [comment]
It worked with these `Section_SiteSettings`.

```php
new Section_SiteSettings([
  'siteId' => $site->id,
  'hasUrls' => true,
  'uriFormat' => '__home__', // This is a magic keyword, apparently
  'template' => 'myTemplate',
]);
```

**Comment by brandonkelly** [comment]
If you don’t want the section to have URLs, then you should just leave the `uriFormat` set to `null` (or don't include the line at all).

**Comment by pieterbeulque** [comment]
@brandonkelly, that's what I thought, but that threw a validator error saying `uriFormat` cannot be blank.

**Comment by brandonkelly** [comment]
@pieterbeulque The only time `uriFormat` is required is if the section type is a Single, or if `hasUrls` is `true`.

**Comment by pieterbeulque** [comment]
OK, then it threw the validation error because it was a single.

Thanks for clarifying this, @brandonkelly!
