### ISSUE TITLE
Changes to Matrix fields aren't saving after update to 3.1.9

### ISSUE THREAD

**Issue by thejoshsmith** [craftcms/cms#3832]
### Description
I updated a site running Craft 3.1.8 to 3.1.9, and noticed that changes made to fields within a matrix don't save. In my case, I ticked on the "field is required" checkbox, but other field content doesn't save either.

### Steps to reproduce

1. Upgrade an existing Craft site with matrix fields to 3.1.9 (maybe not necessary)?
2. Make a change to a matrix block field and save.
3. Go back to the matrix field. The changes won't have persisted.

- Craft version: 3.1.9
- PHP version: 7.2.14
- Database driver & version: MySQL 5.7.25

### Plugins & versions: 
- Architect 2.2.12
- Asset Rev 6.0.2
- Forms 2.5.11 
- Mailgun 1.4.0
- Redactor 2.3.1
- SEO 3.5.4
- SimpleMap 3.3.4
- Sprout Active 2.0.9
- Super Table 2.1.7
- Typed link field 1.0.17

### Screen capture of issue
[craftcmsmatrixfieldissue.mp4.zip](https://github.com/craftcms/cms/files/2858594/craftcmsmatrixfieldissue.mp4.zip)

**Comment by darylknight** [comment]
I can reproduce this on a fresh Craft install with no plugins.

**Comment by m8brgarc** [comment]
I'm having this issue as  well.

**Comment by FabianJacobs** [comment]
I have the same problem, I updated to the latest version of Craft CMS 3.1.9.1 and now I can't modify the field anymore after creating a new one. Can't delete, change or add any new field to the matrix

**Comment by jonXmack** [comment]
Having the same issue, 3.1.9.1, can't update/modify my matrix fields.

**Comment by jordikroon** [comment]
Also having the same issue. I rolled back to 3.1.8 with schema version 3.1.23.

**Comment by rogerdawkins** [comment]
Having the same problem. I tried rolling back to 3.1.8 by changing composer.json but get a message that downgrading to 3.1.8  is not supported when I do a composer update.

**Comment by jordikroon** [comment]
@rogerdawkins try setting 3.1.8 and 3.1.23 in the craft_info database table.

**Comment by rogerdawkins** [comment]
@jordikroon Thanks, that's perfect, back to 3.1.8 and able to edit matrix fields again.

**Comment by m8brgarc** [comment]
I looked for an update but I don’t see it.

Since the issue is closed does that mean it will be in the next update?

**Comment by darylknight** [comment]
Yes - Brandon closed it by referencing a commit which hasn't been released yet

**Comment by mmikkel** [comment]
FWIW – if the field's title, handle and/or instructions fields are changed, the block settings will actually save. So a workaround until the next release (if you don't want to roll back or apply the patch commit) is to add gibberish to the instructions field when saving changes to the block types.

**Comment by simeon-uxiliary** [comment]
When will this be released? We have a large client that is in the middle of training on this and we'd like to update this ASAP.

**Comment by mmikkel** [comment]
3.1.10 was just released, resolving the issue ^ @simeon-uxiliary.

**Comment by simeon-uxiliary** [comment]
Excellent, thank you!

**Comment by brandonkelly** [comment]
Sorry, meant to update the thread after releasing 3.1.10 but got pulled into a meeting. Should be all good now!

**Comment by nicbou** [comment]
I have exactly the same issue in the latest version, 3.5.9

**Comment by brandonkelly** [comment]
@nicbou Please send a database backup and your Composer files over to support@craftcms.com and we can help look into it from there.
