### ISSUE TITLE
Deleting Entry Elements does not delete table records on the database

### ISSUE THREAD

**Issue by pdaleramirez** [craftcms/cms#3833]
### Description
When deleting entries in the control panel index page it does not delete table records in the database. This also happens on other element entries.

### Steps to reproduce

1. Create an entry
2. Go to entry index page, tick that entry then use the action drop down to delete that entry
3. Check the `entries` table in the database and you will it is not deleted or cascading delete.

### Additional info

- Craft version: 3.1.6.1
- PHP version: 7.2

**Comment by andris-sevcenko** [comment]
@pdaleramirez this is because entries are soft-deleted as of Craft 3.1. You can reduce the default soft-delete duration of 30 days by adjusting the [config setting](https://docs.craftcms.com/v3/config/config-settings.html#softdeleteduration).

**Comment by brandonkelly** [comment]
You can also immediately hard-delete all soft-deleted elements by running this command from your terminal:

```bash
./craft gc --delete-all-trashed
```

**Comment by pdaleramirez** [comment]
Sounds good. Thank you
