### ISSUE TITLE
Gmail SMTP settings propably using port 465 when 587 is selected

### ISSUE THREAD

**Issue by elfacht** [craftcms/cms#3834]
### Description

Setting up a Gmail SMTP in email settings throws an error on a server where port 465 is closed, but 587 is open. The error occurs when port 587 is selected. The CMS seems to use 465 in that case, but I couldn't check it.

Testing the ports on my server:

```
# telnet smtp.gmail.com 465
Trying 74.125.140.109...
Trying 74.125.140.108...
Trying 2a00:1450:400c:c0a::6d...
telnet: Unable to connect to remote host: Connection refused

# telnet smtp.gmail.com 587
Trying 74.125.140.109...
Connected to gmail-smtp-msa.l.google.com.
Escape character is '^]'.
220 smtp.gmail.com ESMTP y20sm32707580wra.51 - gsmtp
```
From web.log:

```
[warning][application] Error sending email: Connection could not be established
with host smtp.gmail.com [Connection refused #111
'host' =>  'smtp.gmail.com'
'craft\\mail\\transportadapters\\Gmail
```

A similiar setup with the exact same settings and same Gmail account on another server where port 465 is open works fine when port 587 is selected.

### Steps to reproduce

1.  Be sure that port 465 is closed on the server.
2. Set up either a Gmail account or a Gmail SMTP server in email settings, using smtp.gmail.com and port 587 with TLS.
3. Be sure that your Gmail account allows unsafe apps.
3. Send test mail.

### Additional info

- Craft version: 3.1.8
- PHP version: 7.2

**Comment by brandonkelly** [comment]
I verified that the `Swift_SmtpTransport` object does get properly configured with `params['port']` set to `587`, when the Port setting is set to that, so it’s not a configuration bug at least.

I searched through SwiftMailer’s codebase and couldn’t find any occurrences of `465`. The default SMTP port is 25, but Craft overrides that with whatever you’ve entered.

I’m guessing that this is a server configuration issue. Perhaps your server is forwarding port 587 traffic to something else?

**Comment by elfacht** [comment]
This might be a Gmail issue, I guess? On my other server by a different hoster it works fine, BUT if I replace the SMTP settings with a another mail server (not Gmail) and using 587 it works fine, too. This is very strange.

Maybe Gmail is blocking 587 requests from this particiular hoster or vice versa? The tech support is out of ideas, too.

**Comment by elfacht** [comment]
Well, I've found the root of all evil:

https://www.ipserverone.info/google-apps/how-to-solve-gmail-error-password-not-accepted-from-server/

https://support.google.com/mail/answer/7126229?visit_id=636857391298706033-411564613&rd=2#cantsignin
