### ISSUE TITLE
Field value still appears in search index even if excluded from search keywords

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#3837]
### Description

Field value still appears in search index, even if excluded from search keywords.

In my current project, this happens within a User field within a Matrix field, but after testing on another project this also happens with a simple Plain Text field.

Search keywords are still there on update Entry / new Entry, and also after updating the search indexes.

### Steps to reproduce

1. Create a Matrix field, and uncheck `Use this field’s values as search keywords?`
2. Update the search indexes
3. Check `craft_searchindex` table > filter by `fieldId` > look for field value in the `keywords` column
4. Alternatively on front end, start a new search using field value

### Additional info

- Craft version: Craft Pro 3.1.9.1
- PHP version: 7.1.8
- Database driver & version: PostgreSQL 9.6.9

**Comment by brandonkelly** [comment]
We just released 3.1.10 with a fix for this!
