### ISSUE TITLE
Dropdown field says - can't be blank when value field has content "0"

### ISSUE THREAD

**Issue by michtio** [craftcms/cms#3842]
### Description

When you have a dropdown field, and you add a value of "0" and a label of "0" when you select this option from the dropdown, Craft CMS gives an error:

- Dropdownfield cannot be blank.

This is unexpected behaviour, because a value of 0 is definitely not a blank value, this field is used / should be used together with css utility classes, in my case tailwind, where classes are build based upon the values from the dropdown.

Seems a bit tedious to change that value to "zero" and then go to twig to do the following:

``` 
{% if entry.dropdown.value == "zero" %}
  {% set spacing = 0 %}
{% else %}
  {% set spacing = entry.dropdown.value %}
{% endif %}

<div class="m-{{ spacing }}"></div>
``` 

instead of being able to do:

```
<div class="m-{{ entry.dropdown.value }}"></div>
```

### Steps to reproduce

1. Create a dropdown field
2. Add Label: 0
3. Add Value: 0
4. Use the field in a section
5. Select 0 from the dropdown field
6. Error appears when you save the entry

### Additional info

- Craft version: 3.1.10

**Comment by brandonkelly** [comment]
Just released 3.1.11 with a fix for this.
