### ISSUE TITLE
Custom headings in sidebar does not get reflected in project.yaml 

### ISSUE THREAD

**Issue by nettum** [craftcms/cms#3843]
### Description
Custom headings in sidebar does not sync to project.yaml.  
I'm using custom headings in the sidebar with craft 3.1 and using project.yaml to reflect all settings made on dev ('allowAdminChanges' => true) into stage and production ('allowAdminChanges' => false).

As far as I can see, the custom headings does not sync to project yaml and they will be missing on the stage/production environment.

### Steps to reproduce

1. Set 'allowAdminChanges' => true on dev env and 'allowAdminChanges' => false for stage/production.
1. Add custom headings on sidebar in dev env (project.yaml isn't updated)
2. Deploy code to stage/prod and verify that headings are gone.
3. Try click the "Customize sources" button on stage/production. You will get an error "An unknown error occurred.". The underlying ajax response is (rightfully) 403 forbidden - "error: Administrative changes are disallowed in this environment."

See screenshots:  
dev:  
![image](https://user-images.githubusercontent.com/798156/52784166-7f249200-3054-11e9-8ba8-b97e5e15ce5d.png)

stage/production:
![image](https://user-images.githubusercontent.com/798156/52784224-ae3b0380-3054-11e9-8b30-050ad0288d7e.png)

### Additional info

- Craft version: 3.1.8
- PHP version: 7.2

**Comment by nettum** [comment]
I see that this _may_ be the intended behavior as "Table Columns"-settings also does not sync.  
Still, keeping the issue open to hear your thought.

**Comment by carlcs** [comment]
Hey @nettum, this is more or less a duplicate of #3658

**Comment by nettum** [comment]
Ah, yes. And it seems to be "fixed" in 3.1.9 -> https://github.com/craftcms/cms/commit/4401672c2511fd8099ddaf4c470f0a584c935920  
Will do an craft update to see if I can change the settings in stage/production env after update.

**Comment by nettum** [comment]
> We haven’t added this yet because we decided that element index settings actually shouldn’t be, because eventually each user is going to be able to customize element indexes to their own liking.

Makes sense then.  
Can also confirm that I can edit headings on stage/production after updating craft to 3.1.10.
Thanks @carlcs :+1: 
Closing issue.
