### ISSUE TITLE
Debug toolbar doesn't work across multiple domains in multi-site setup

### ISSUE THREAD

**Issue by naboo** [craftcms/cms#3848]
### Description
If you run a multi-site Craft setup across different domains and you set `baseCpUrl` in your production environment (so your content creators doesn't see the licensing issue displayed if logged into another domain then the domain holding the license) the debug toolbar doesn't work for frontend requests.

### Steps to reproduce

1. Setup Craft with 2 sites (Site A, Site B), different domains
2. Set `baseCpUrl` in production to Site A
3. Login to Craft
4. Enable debug toolbar for frontend requests
5. Browse entry in Site B

**Comment by brandonkelly** [comment]
Yeah there’s no easy way for Craft to solve this automatically. You’ll need to give your site its own [login form](https://docs.craftcms.com/v3/dev/examples/login-form.html), so you can establish a user session on that domain. Once logged in, Craft will start showing the debug toolbar, per the user preference.

**Comment by naboo** [comment]
Ah totally makes sense. Thanks.

Den fre 15 feb. 2019 18:58Brandon Kelly <notifications@github.com> skrev:
