### ISSUE TITLE
500 error when current user’s photo doesn’t exist

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#3849]
### Description

When I deleted my own user photo directly via the element action in Assets → Volume, I got this wonderful error

```
yii\base\InvalidConfigException: Invalid photo ID: 700 in /app/vendor/craftcms/cms/src/elements/User.php:1207
```

Stack trace: https://gist.github.com/carlcs/3d2bed36ac3dda9f37d6baa9f9780fd0

### Additional info

- Craft version: 3.1.11

**Comment by brandonkelly** [comment]
We released 3.1.12 today with a fix for this.
