### ISSUE TITLE
Uploading files with emoji's in filename cause SQL error

### ISSUE THREAD

**Issue by skoften** [craftcms/cms#3852]
<img width="464" alt="screenshot 2019-02-17 at 13 24 59" src="https://user-images.githubusercontent.com/1286410/52912875-e1310180-32b7-11e9-83d6-ca89c5e16043.png">

Craft CMS 3.1.12
PHP 7.2.14
 Mysql 5.7.24

**Comment by brandonkelly** [comment]
Fixed that for the next release. Thanks for reporting!

**Comment by bramus** [comment]
Adding a mention of https://github.com/craftcms/cms/issues/2527 here, as that's the root cause of this issue ;)
