### ISSUE TITLE
Quick edit shows deleted fields and deprecated order, new fields are missing

### ISSUE THREAD

**Issue by elfacht** [craftcms/cms#3856]
### Description

The quick edit flyout shows already deleted fields by deleted plugins, and a deprecated field order. Doesn't occur on every entry, but on older ones. Editing the entry on the detail view works fine.

Deleting the cache didn't help.

#### Field layout on quick edit
 
(Google Places is already removed and uninstalled, Latitude and Longitude fields are missing)

![screenshot 2019-02-18 um 11 08 11](https://user-images.githubusercontent.com/529443/52943716-084a0a80-336e-11e9-9dd5-1173464168d7.jpg)

… but on the edit page itself it's correct:

![screenshot 2019-02-18 um 11 16 07](https://user-images.githubusercontent.com/529443/52957681-87513a00-3392-11e9-8ff4-998ee6eb29e9.jpg)

#### Actual field layout

![screenshot 2019-02-18 um 12 58 15](https://user-images.githubusercontent.com/529443/52949568-f328a800-337c-11e9-983c-075b7d5d4735.jpg)

![screenshot 2019-02-18 um 11 13 40](https://user-images.githubusercontent.com/529443/52943823-47785b80-336e-11e9-92f3-56ef39cb82c6.jpg)

### Additional info

- Craft version: 3.1.12

**Comment by elfacht** [comment]
Removing the `LocateField` manually from the `project.yml` (it was still there despite deleting it via the settings) removed the field from the edit modal. The new fields (lat and lng) are still missing on older entries. The order is also still the old one.

**Comment by brandonkelly** [comment]
Regarding the missing Latitude and Longitude fields, are you sure you don’t have multiple Entry Types set up for the section?

**Comment by elfacht** [comment]
@brandonkelly Yep, there's just a single entry type for this section, no entry type to choose. And it just affect entries older than — I don't know — prior Craft 3.1 (in this case: August 2018)? Newer entries work fine, as you can see in the screenshot.

**Comment by brandonkelly** [comment]
Can you please send in a support ticket from your Craft Support widget on your Dashboard?
