### ISSUE TITLE
Using extraFileKinds does not work in element select modal

### ISSUE THREAD

**Issue by aelvan** [craftcms/cms#3869]
### Description

I've added an extra file kind through the `extraFileKinds` general config setting, and added a field that is restricted to use only this kind. When opening the Element Selctor Modal from the field, files of this kind, does not appear in the modal. 

### Steps to reproduce

1. Add a new kind to general.php:

    ```php
    'extraFileKinds' => [
        'svg' => [
            'label' => 'SVG',
            'extensions' => ['svg'],
        ],
    ],
    ```

2. Create a new field, ad choose to restrict the field with this kind.
3. Add THE field to an entry type.
4. Publish a new entry of type, and try to add a new asset to the field. 
5. The Element Selector Modal does not show any files, even if they're of the right type.

### Additional info

- Craft version: 3.1.12
- PHP version: 7.2.14
- Database driver & version: MySQL 5.7.18

**Comment by brandonkelly** [comment]
Fixed for the next release, thanks!
