### ISSUE TITLE
Clicking on settings / fields throws an error and ruins the whole DB

### ISSUE THREAD

**Issue by cstudios-slovakia** [craftcms/cms#3870]
### Description

after the update from 3.0.x to 3.1.11 the website worked well, until we wanted to add a field. clicking the field option in the settings the following error was thrown:

`Argument 1 passed to craft\services\Fields::getGroupById() must be of the type integer, null given, called in /nfsmnt/hosting1_2/9/6/96bd64db-42a5-42e4-8cc9-243ca88497b1/jokai.sk/web/craft/vendor/craftcms/cms/src/base/Field.php on line 445`

this caused the relation with the entries, so all of the content is gone. This happens with a fresh Craft install with the exported database. Basically the group entry group called "globals" disappears from the database when a new field is created, so the relation is not existent.

if you need more info, please get in touch. we will provide as much as possible.

### Additional info

- Craft version: 3.1.12
- PHP version: 7.2
- Database driver & version: MariaDB 10.1
- Plugins & versions:

**Comment by brandonkelly** [comment]
Hi @cstudios-slovakia,

Do you have a database backup from before the field was added, which you are able to reproduce this with?

If so, please send it to support@craftcms.com, along with your `composer.json` and `composer.lock` files, and reference this GitHub issue URL, and provide steps to reproduce the issue.

**Comment by Anubarak** [comment]
I had the same issue in my current project. The reason for this is: the initial migration didn't run well and the field groups are not included in your project Config. As soon as you try to store a field Craft proceeds to sync the project config field groups with your database. Since those field groups don't exist it will remove them causing all existing fields and the group to be deleted and all your content in your content table is removed. The newly created field will be stored with no group and as soon as you enter your field settings it tries to grab this null group causing the error. You can solve it by creating a new group, move all fields to this new group and delete the old one. Repeat this until all fields are saved

**Comment by brandonkelly** [comment]
@Anubarak Did you happen to catch the error in the initial migration?

**Comment by Anubarak** [comment]
Unfortunately not. The issue was another migration back in 2018 but I don't remember the exact one. It should have added a `fieldId` or `siteId` to a certain column but that wasn't the case for 2 projects. I'll search on Monday if that migration didn't run or if those changes were not reflecteded in the install.php (if the projects were created after it)

However: that issue (the missing column) caused an exception during the migration process for Craft 3.1. I'll search for all recent file changes on the PC in my office on Monday because I edited certain things. Maybe I can track which column it was because of that.

All other projects migrated without any problems

**Comment by brandonkelly** [comment]
Thanks, that would be helpful.

**Comment by Anubarak** [comment]
Okay: at least for us the following happened. I'm not sure if that caueses the mentioned thing for the creator of this topic as well or what the exact cause of it is or even why it happened, but here we go:

In my `migrations` table there are the followin records
```
id  | pluginId | type | name                                  | applyTime  
1   | NULL     | app  | Install                               | 2018-10-18 08:10:09
....
103 | NULL     | app  | m181112_203955_sequences_table        | 2018-12-17 14:55:18
104 | NULL     | app  | m180425_203349_searchable_fields      | 2019-01-16 13:29:30 <-- Exception column "fields.searchable" already exists 
105 | NULL     | app  | m180516_153000_uids_in_field_settings | 2019-01-16 13:29:30
```
The `searchable` column in fields was already there in those two projects and the first backup created by Craft in the backups folder already contains it.( `2019-01-16` was the day I updated to Craft 3.1) I solved the issue by removing the line in the migration and clicked on "reapply". The other migrations ran "successfully" (at least there were no errors directly) but those projects ended both with an empty project config, while every other Updates were successfully

I don't know if that exception is even related in any way with the empty project config. Maybe it has something to do with the time I started the migrations (both at `2019-01-16`) maybe with something else, I wasn't able to figure out the reason but I can send you the first DB backups of the day if you like.

PS: No I didn't touch the core files nor the migrations before the update - only after the update to remove all exceptions and make the system run again.

**Comment by brandonkelly** [comment]
> The `searchable` column in the `fields` table was already existent in those two projects and the first backup created by Craft in the backups folder already contains it.

Any idea when that column would have been added? Craft itself didn’t introduce that column until Craft 3.1.0.

**Comment by cstudios-slovakia** [comment]
Sorry for the slow reaction, here is the requested data.
composer.json:
`{
  "require": {
    "benjamminf/craft-embedded-assets": "1.0.2",
    "craftcms/cms": "^3.0.0",
    "craftcms/contact-form": "2.2.3",
    "craftcms/redactor": "2.3.1",
    "ether/seo": "3.5.4",
    "mikestecker/craft-videoembedder": "1.1.1",
    "mmikkel/child-me": "1.0.4",
    "mmikkel/cp-field-inspect": "1.0.5",
    "monachilada/craft-matrixtoolbar": "1.0.6",
    "topshelfcraft/wordsmith": "3.0.4",
    "verbb/expanded-singles": "1.0.7",
    "vlucas/phpdotenv": "^2.4.0"
  },
  "autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  },
  "config": {
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "7.0"
    }
  },
  "scripts": {
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ]
  }
}`

composer lock is a bit longer, i pasted it here: [https://pastebin.com/9JJVZc4x](https://pastebin.com/9JJVZc4x)

and the DB backup can be downloaded here: [https://drive.google.com/file/d/1k3j9OY4qhS90LI3nbT2T8va68Lz74du4/view?usp=sharing](https://drive.google.com/file/d/1k3j9OY4qhS90LI3nbT2T8va68Lz74du4/view?usp=sharing)


also sending it to the email given

**Comment by brandonkelly** [comment]
@cstudios-slovakia you probably don’t want to share DB backups here!!

**Comment by JorgeAnzola** [comment]
I have the same issue. I have a script that runs:

docker-compose exec app ./craft install
docker-compose exec app ./craft install/plugin assetrev
docker-compose exec app ./craft install/plugin seo
docker-compose exec app ./craft install/plugin redactor

After that if I try to create a field, I get a 404, then a 500. After this, if I try to go to the fields settings I get `Argument 1 passed to craft\services\Fields::getGroupById() must be of the type integer, null given, called in /var/www/vendor/craftcms/cms/src/base/Field.php on line 477` 
 
If I do the installation from the explorer, it works normally.

I attach a DB before creating the field, the DB after doing so and three screenshots of the errors.
[Docker - Localhost-craft-201972371140.gz](https://github.com/craftcms/cms/files/3420323/Docker.-.Localhost-craft-201972371140.gz)
[Docker - Localhost-craft-201972371047.gz](https://github.com/craftcms/cms/files/3420324/Docker.-.Localhost-craft-201972371047.gz)
<img width="1432" alt="1" src="https://user-images.githubusercontent.com/15676614/61684454-cefd3880-ad19-11e9-8d8f-ba8bb8dd2f1b.png">
<img width="1440" alt="2" src="https://user-images.githubusercontent.com/15676614/61684455-cf95cf00-ad19-11e9-8d62-edabefae77b9.png">
<img width="1421" alt="3" src="https://user-images.githubusercontent.com/15676614/61684456-cf95cf00-ad19-11e9-99f4-0964da314e84.png">

**Comment by brandonkelly** [comment]
@JorgeAnzola Thanks! We're able to reproduce this and will get it fixed.

**Comment by brandonkelly** [comment]
This is fixed for the next release!

**Comment by JorgeAnzola** [comment]
I just updated but I still get the same issue :(

```
Argument 1 passed to craft\services\Fields::getGroupById() must be of the type integer, null given, called in /var/www/vendor/craftcms/cms/src/base/Field.php on line 477
```

**Comment by brandonkelly** [comment]
Sorry to be clear, we were only able to fix it for new installs. Once you got yourself into the situation, the update won’t fix this for you. You can try running `./craft project-config/rebuild` though.

**Comment by DynamiteGoesBoom** [comment]
Has any additional info been found for this error? I was simply reorganizing some Tag fields when this error popped up. It doesn't sound like there is much info on it as it pertains to a fix.

What can we do here about this error?

**Comment by brandonkelly** [comment]
@DynamiteGoesBoom have you tried running `./craft project-config/rebuild`?

**Comment by DynamiteGoesBoom** [comment]
I did, but it didn't help. We reverted back and all is fine now. But I'm a
little nervous that things could go haywire again :/

**Comment by brandonkelly** [comment]
If you can reproduce with the DB backup, can you send it in, as well as your `composer.json` & `composer.lock` files, to support@craftcms.com and list the steps to reproduce?

**Comment by DynamiteGoesBoom** [comment]
If it happens again I'll do that. Thanks!

**Comment by DynamiteGoesBoom** [comment]
It looks like it only happens when moving a field to another field group
under Fields.

**Comment by DynamiteGoesBoom** [comment]
Email sent with what you requested Brandon. Thanks again!

**Comment by olivierbon** [comment]
Running `./craft project-config/rebuild` fixed the issue.

**Comment by brandonkelly** [comment]
Glad we were able to help!

**Comment by DynamiteGoesBoom** [comment]
This issue creeped up again and `./craft project-config/rebuild` did not correct it.

**Comment by DynamiteGoesBoom** [comment]
I just sent in an update to P&T Support, thanks y'all!

**Comment by DynamiteGoesBoom** [comment]
@brandonkelly / @olivierbon Is there a way to revert using Project Config temporarily? I really need to be able to add additional fields and this issue is blocking me from doing anything.

**Comment by timkelty** [comment]
Seeing the same thing on a craft 2->3 migration…`project-config/rebuild` didn't help.
