### ISSUE TITLE
Craft archive versions and content are out of sync

### ISSUE THREAD

**Issue by markhobson** [craftcms/cms#3871]
### Description

After 3.0.37 the Craft archives that can be [manually downloaded](https://docs.craftcms.com/v3/installation.html#step-1-download-craft) are out of sync with their content. For example, the [3.0.38](https://download.craftcdn.com/craft/3.0/Craft-3.0.38.zip) archive appears to be for 3.1.8.

### Steps to reproduce

1. Run the following script to obtain the internal Craft CMS version for a given archive, e.g.:

        VERSION=3.0 BUILD=38 sh -c 'echo $VERSION.$BUILD && curl https://download.craftcdn.com/craft/$VERSION/Craft-$VERSION.$BUILD.zip -s -o /tmp/craft.zip && rm -rf /tmp/craft && unzip -q /tmp/craft.zip -d /tmp/craft && grep version /tmp/craft/vendor/craftcms/cms/composer.json'

2. See the discrepancies:

Archive Version | Craft CMS Version
----------------|------------------
3.0.37 | 3.0.37
3.0.38 | 3.1.8
3.0.39 | 3.1.8
3.0.40 | 3.1.8
3.1.0 | 3.1.1
3.1.1 | 3.1.2
3.1.2 | 3.1.2.1
3.1.2.1 | 3.1.2.2
3.1.2.2 | 3.1.3
3.1.3 | 3.1.4
3.1.4 | 3.1.5
3.1.5 | 3.1.5
3.1.6 | 3.1.6.1
3.1.6.1 | 3.1.7
3.1.7 | 3.1.8
3.1.8 | 3.1.9
3.1.9 | 3.1.9.1
3.1.9.1 | 3.1.9.1
3.1.10 | 3.1.11
3.1.11 | 3.1.12
3.1.12 | 3.1.12

### Additional info

- Craft version: N/A
- PHP version: N/A
- Database driver & version: N/A
- Plugins & versions: N/A

**Comment by angrybrad** [comment]
Thanks for reporting this... should be resolved now!

**Comment by markhobson** [comment]
Looks great, thanks!
