### ISSUE TITLE
License key field missing on 3.0.40

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#3876]
### Description
In the plugins overview on 3.1.12, there is a license key input field under each plugin that needs one.
On 3.0.40 however, that field is not shown.

On 3.0.40
![3040](https://user-images.githubusercontent.com/755428/53158985-307f7680-35c5-11e9-83ab-a736f5245f97.png)

On 3.1.12
![3112](https://user-images.githubusercontent.com/755428/53158934-0c239a00-35c5-11e9-879e-9f626d2c110d.png)

### Additional info

- Craft version: 3.0.40
- PHP version: 7.2.1
- Database driver & version: 5.7
- Plugins & versions:

**Comment by brandonkelly** [comment]
Doh! Just released 3.0.40.1 with a fix for this.

**Comment by janhenckens** [comment]
Thanks!
