### ISSUE TITLE
Localize Relations job fails on PostgreSQL

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#3877]
### Description

The Localize Relations job fails on PostgreSQL. This is because PostgreSQL is case sensitive. See this line https://github.com/craftcms/cms/blob/develop/src/queue/jobs/LocalizeRelations.php#L70

### Additional info

- Craft version: 3.1.12
- PHP version: 7.3.2
- Database driver & version: PostgreSQL 10.6
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
Thanks for reporting that!
