### ISSUE TITLE
Yii2 Mutex resource unavailable when upgrading to Craft 3.1.13 

### ISSUE THREAD

**Issue by lukebailey** [craftcms/cms#3881]
### Description
After upgrading to Craft 3.1.13 (from 3.1.12) the following PHP warning is shown running locally on a MAMP environment:

![image](https://user-images.githubusercontent.com/3185073/53183223-d2698800-35f2-11e9-9ffd-ae1fd174c6c4.png)

### Steps to reproduce

1. Upgrade to Craft 3.1.13 from 3.1.12

### Additional info

- Craft version: 3.1.13
- PHP version: 7.1
- Database driver & version: MySQL
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Duplicate of #3879
