### ISSUE TITLE
Allow singles to have no URL

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#3883]
When Craft is used as a headless CMS, you might still have one off entry types for certain content. Can we please have a “Entry doesn’t have a URL” option for single sections, which disables the route and Live Preview.

I guess you could benefit from it yourself! 😉
https://github.com/pixelandtonic/craftnet/blob/master/src/controllers/api/v1/PluginStoreController.php#L106

**Comment by brandonkelly** [comment]
I’ve been wondering about this ever since #3830. Will put this on the 3.2 list.

**Comment by jalendport** [comment]
Just chiming in to say I'm looking forward to this as well 👍

**Comment by brandonkelly** [comment]
This is added for Craft 3.3!

<img width="975" alt="Screenshot of Site Settings for a Single section" src="https://user-images.githubusercontent.com/47792/63527040-3a6f2d00-c4b5-11e9-8798-a06732bf4edc.png">
