### ISSUE TITLE
Error while updating Craft CMS

### ISSUE THREAD

**Issue by Djive** [craftcms/cms#3887]
When trying to update to Craft CMS 3.1.14. from control panel we got the following error:

```
A fatal error has occurred:

Status: Internal Server Error

Response: {"nextAction":"server-check","status":"Checking server requirements…","data":"0bc6658e87341a2ac6489a5fced5f9c190254a30711e4206e94bfda5ece64c09{\"install\":{\"craft\":\"3.1.13\"},\"current\":{\"craftcms/cms\":\"3.1.12\"},\"requirements\":{\"craftcms/cms\":\"3.1.13\"},\"reverted\":false,\"returnUrl\":\"utilities/updates\",\"postPrecheckState\":{\"nextAction\":\"composer-install\",\"status\":\"Updating Composer dependencies (this may take a minute)…\"}}"}

Yii
Events 1782
User 1
Status 200 Route updater/index
Log 90
Deprecated 0
Time 3,355 ms Memory 114.731 MB
DB 71 2,807 ms
Asset Bundles 26
```

Noticed a lot of errors like this one also in our errors_log

```
[21-Feb-2019 19:54:25 Europe/Berlin] PHP Warning:  require(/home/site/vendor/craftcms/cms/bootstrap/web.php): failed to open stream: No such file or directory in /home/site/public_html/index.php on line 20
[21-Feb-2019 19:54:25 Europe/Berlin] PHP Fatal error:  require(): Failed opening required '/home/site/vendor/craftcms/cms/bootstrap/web.php' (include_path='.:/opt/alt/php72/usr/share/pear') in /home/site/public_html/index.php on line 20
```

PHP version 7.2.14
Craft Pro 3.1.13

Our settings are quite high, for example:
max_execution_time = 4200
memory_limit = 3560M

Is there any way to fix this without Composer?

Thanks!

**Comment by brandonkelly** [comment]
Sounds like there was a previous error when Composer-installing the update that went undetected.

You should be able to fix by manually running `composer update`. If that doesn’t help, then Composer may be under the impression that nothing went wrong, in which case you can nuke your entire `vendor/` folder and run `composer install`.

**Comment by Djive** [comment]
Sorry to bother again.
Is there any way to fix this without Composer?

**Comment by brandonkelly** [comment]
You could download a fresh copy of Craft from https://craftcms.com/latest-v3.zip and upload the `vendor/` folder and `composer.json` and `composer.lock` files (ignoring everything else in the zip), and then re-install any plugins you had installed.

**Comment by brandonkelly** [comment]
Actually, if you have SSH access, then just upload the new `vendor/` folder from that zip (**not** `composer.json` or `composer.lock`, and then SSH onto your server, `cd` to your project root, and then run:

```bash
./craft update/composer-install
```

**Comment by Djive** [comment]
We uploaded the new `/vendor` folder.
Then we SSH onto our server and tried running `./craft update/composer-install`
Got this response:
```
sitename@ssd2 [~]# ./craft update/composer-install
-bash: ./craft: Permission denied
```
Can you give us any further pointers on this.
If you would like, we can give you SSH access.
Thank you!

**Comment by brandonkelly** [comment]
Check the permissions on your `craft` executable file. The user you are SSH’d in as will need execute permissions for it.

**Comment by Djive** [comment]
It worked. 
Thank you!
