### ISSUE TITLE
Make Systemessages translation keys/rules less strict

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#3888]
### Description
Currently when sending a Systemmessage to a `craft\elements\User` passed via `message::setTo` there must be an exact match of the prefered language and the site language. So when a User submits `en-US` in his/her preferences but the site is `en` or `en-GB` the user won't receive the translated message but the default system message. It would be good to match `en` with `en-XX` if no exact match was found.

### Steps to reproduce

1. Create a user with `en-US` language
2. Change the content of a Systemmessage in a site with `en-GB`
3. Send a mail to this user and see it uses the default message

**Comment by brandonkelly** [comment]
All set for the next release!
