### ISSUE TITLE
Odd behaviour in routes in CP

### ISSUE THREAD

**Issue by loqus** [craftcms/cms#3892]
### Description
When changing routes it says 'New route order saved' and routes are followed how they are supposed to. But after loggin in a next time (after session expires) has the routes changed back to their entered order. So the last entered route is on the bottom. 

### Steps to reproduce

1. Enter routes
2. Shuffle them in the right order
3. Let session expire
4. Go back to routes and order is changed to order of entry

### Additional info

- Craft version: Craft Pro 3.1.14
- PHP version: 7.2.15
- Database driver & version: MySQL 5.5.60
- Plugins & versions:
Imager | v2.1.5
Image Resizer | 2.0.4
Redactor | 2.3.2
Splashing Images | 1.2.0

**Comment by brandonkelly** [comment]
If you reload the page after changing the route order, does it still show the new order?

**Comment by loqus** [comment]
I should have checked this. Indeed it jumps back on reload.

**Comment by brandonkelly** [comment]
Thanks! That’s been fixed for the next release.

**Comment by loqus** [comment]
It seems to have been fixed by the last update together with https://github.com/craftcms/cms/issues/3922

**Comment by brandonkelly** [comment]
Whoops, yes this one was fixed in 3.1.15. Looks like I messed up the commit note so GitHub didn’t automatically close the issue.

#3922 fix is still pending; we plan to officially release the fix tomorrow as part of 3.1.16.
