### ISSUE TITLE
Creating structure section, then resaving as channel breaks entry creation/access

### ISSUE THREAD

**Issue by chasegiunta** [craftcms/cms#3895]
### Description
This one's pretty easy to reproduce.

### Steps to reproduce

1. Create a structure section. Save.
2. Go back into section settings, change to channel. Save.
3. Try to create new entry in channel section.
4. Observe missing entry.
5. Click "All Entries", see new entry in index, click to get 404..

### Additional info

If viewed within 48 hours, can see on Happy Lager demo site https://demo.craftcms.com/j67o1DVf82/s/

**Comment by brandonkelly** [comment]
Fixed for the next release.

If you need the fix right away, change the `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#60a9e5a5649802aac7e3c673a5c946deeba7d80c as 3.0.14",
  "...": "..."
}
```

Then run `composer update`.
