### ISSUE TITLE
Users with a preferred language set receive system messages in incorrect language.

### ISSUE THREAD

**Issue by bzin** [craftcms/cms#3900]
### Description

In a multisite installation users have a preferred language that is non existent in the App Locales. This makes these users receiving System messages emails in the primary language instead.

The issue can be fixed by updating the `getPreferredLanguage` method:
https://github.com/craftcms/cms/blob/develop/src/elements/User.php#L1152
```
    public function getPreferredLanguage()
    {
        $language = $this->getPreference('language');

        // Make sure it's valid
        if ($language !== null &&
            in_array($language, Craft::$app->getI18n()->getAppLocaleIds(), true) ||
            in_array($language, Craft::$app->getI18n()->getSiteLocaleIds(), true)) {
            return $language;
        }

        return null;
    }
```

### Additional info

- Craft version: Craft Pro 3.0.40.1
- PHP version: 7.2.14

**Comment by brandonkelly** [comment]
How did they get their preferred language set to something not returned by `getAppLocaleIds()` in the first place? The code for the Edit User page only allows you to select a supported app locale.

If you are manually setting users’s preferred languages to unsupported locales, you can configure Craft to begin supporting that language using the [extraAppLocales](https://docs.craftcms.com/v3/config/config-settings.html#extraapplocales) config setting.

**Comment by bzin** [comment]
@brandonkelly sorry the lack of context here.

Basically the users do not have access to the CP so they are not able to set their preferred language.
Their language preference is saved when they are associated with an entry from a specific Site. On this projects users cannot have entries on different Sites. Their account will always be restricted to one.

The check for Sites Locales was suggested because on this multisite installation languages like `de-AT` and `sv-SE` are not represented in the App locales.

On top of that I was not aware of the `extraAppLocales` settings nor was able to find it (should have search better 🙄). 

In the end yoursuggestionn fixes my issue. Thanks!

**Comment by brandonkelly** [comment]
Ah yes I remember that now.

**Comment by bzin** [comment]
Does it make more sense now the second check? :)

**Comment by brandonkelly** [comment]
@bzin No I think I should have just recommended also adding new values to the `extraAppLocales` config setting.
