### ISSUE TITLE
Multi-Site Globals Entry Fields Clearing

### ISSUE THREAD

**Issue by lg-m** [craftcms/cms#3902]
### Description
I have a multi-site setup with multiple global sets (a global set is used by each site). Periodically all the entry fields lose their values (including entry fields within matrix fields), sometimes this is across all sets and sometimes this is only some / one of them, however it's always all the entry fields in a set, never just some of them. It's happened on multiple occassions but haven't been able to purposefully replicate it, have been able to edit the sets, fields and the contents of the fields without this occurring. 
The only thing flagged in the System Report tab is that memory_limit is currently 128M, unsure if this could be related?

### Additional info
- Craft version: Craft Pro 3.0.35
- PHP version: 7.0.33
- Database driver & version: MySQL 5.7.25
- Plugins & versions:
  - Contact Form 2.2.3
  - Freeform Lite 2.5.5
  - Freeform Pro 2.5.5
  - Redactor 2.1.7
  - Redirect plugin for Craft 3 1.0.18
  - SimpleMap 3.3.4
  - Tags 1.0.1

**Comment by brandonkelly** [comment]
That’s odd, we’ve never heard of that before. Unfortunately it’s not much for us to go on though. If you can come up with steps to reproduce, please reopen this issue and post them.
