### ISSUE TITLE
Plugin Store doesn't render blockquotes in Markdown

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#3903]
It seems the Plugin Store is not properly rendering blockquotes...

>This is a blockquote.

When prefixing a line with `>`, it doesn't seem to do anything...

https://plugins.craftcms.com/inventory

**Comment by brandonkelly** [comment]
When the blockquote is formatted correctly in Markdown (begin with `>` and a space), the HTML comes back correct but there’s no blockquote CSS styling on it.

<img width="230" alt="screen shot 2019-02-25 at 4 26 21 pm" src="https://user-images.githubusercontent.com/47792/53378387-3903e400-391a-11e9-918e-5a1ec2e753e7.png">

**Comment by brandonkelly** [comment]
Looks right in the in-app plugin store, though.

**Comment by benjamindavid** [comment]
The `.readable` class was missing from the styles, should be fixed now. Thanks @lindseydiloreto!

**Comment by lindseydiloreto** [comment]
Looks perfect, thanks @benjamindavid! 🍺
