### ISSUE TITLE
Craft does not use app.php configured redis session handler

### ISSUE THREAD

**Issue by rob-baker-ar** [craftcms/cms#3904]
### Description

Having set-up Craft to use the Yii2 Session driver, like this in config/app.php:

```php
return [
    'modules' => [],
    'components' => [
        'redis' => [
            'class' => yii\redis\Connection::class,
            'hostname' => 'localhost',
            'port' => 6379,
        ],
        'session' => [
            'class' => yii\redis\Session::class,
            'as session' => craft\behaviors\SessionBehavior::class,
        ],
        'cache' => [
            'class' => \yii\redis\Cache::class,
            'defaultDuration' => 86400,
        ],
    ]
];
```

I have tried a large number of variations of the above. Redis is configured to only respond internally (localhost) and works fine from the command line.

It seems Craft is instead silently using the database for sessions, each request has queries along these lines:

```sql
SELECT id FROM sessions WHERE (`token`=?) AND (userId=?) LIMIT 1
```
```sql
UPDATE sessions SET dateUpdated=? WHERE id=?
```

I can't find any logged errors related to this.

### Additional info

- Craft version: 3.1.14
- OS: Ubuntu Server 18.04
- PHP version: 7.2.15-0ubuntu0.18.04.1
- Database driver & version: MySQL / 5.7.25
- Plugins & versions: Commerce 2.0.4

**Comment by rob-baker-ar** [comment]
Perhaps I should add that the above configured "cache" lines work - I can see Redis being populated with cache entries, just not session data.

**Comment by brandonkelly** [comment]
> It seems Craft is instead silently using the database for sessions, each request has queries along these lines:

That table is unrelated to the `session` component. It’s there to serve user session validation, but does not actually hold any session data stored via `Craft::$app->session->set()`, etc..

Most likely Redis is working properly for actual session storage. You can test by first clearing out all PHP session data (go to `/admin/utilities/php-info` and search for `session.save_path` to see where that is stored), then with Craft configured to use Redis, try logging in, and then comment out your custom `session` component config, and reload the Control Panel. If you are no longer logged in, then you had it configured correctly.

**Comment by rob-baker-ar** [comment]
Thank you.

This pointed me in the right direction - I eventually worked out that the `session.save_path` in php.ini was not taking effect and was being overridden by an additional Nginx configuration line looking like:

`php_admin_value[session.save_path] = "/path/on/filesystem"`

...Found in: /etc/php/7.2/fpm/pool.d/[loads of numbers].conf

Once I added in the settings for Redis session handling to that file (and restarted nginx and php7.2-fpm), everything started working.

_(It was definitely right to look in the Craft control panel here: `/admin/utilities/php-info` to see what was going on / actually taking effect)._

It's unfortunate there is either an `INSERT` or an `UPDATE` against the `sessions` database table every request in any circumstance but I can live with that for the moment.

**Comment by narration-sd** [comment]
It may be helpful to remember small and repeated transactions, especially, are in memory with a db engine, whose mastery is caching....

**Comment by rob-baker-ar** [comment]
I agree but it was specifically on my radar because (probably because they are writes) they are the slowest queries on the page.

**Comment by brandonkelly** [comment]
> It's unfortunate there is either an `INSERT` or an `UPDATE` against the `sessions` database table every request in any circumstance but I can live with that for the moment.

Only if a user is logged in; guest requests won’t touch that table.
