### ISSUE TITLE
Use Environment Variables in Project Config

### ISSUE THREAD

**Issue by TheFox** [craftcms/cms#3906]
There is this new feature in Project Config (`project.yml`), that makes it possible to use environment variables for yaml variables. Like

```yaml
xyz: '$ABC'
```

 I'm not sure, but should

```yaml
xyz: 'Hello, $ABC'
```

also work as well?

When it's not working, is this a bug, or by intention?

**Comment by brandonkelly** [comment]
Not a bug. Settings that support environment variables must be set to the environment variable name plus the `$`, and nothing else.
