### ISSUE TITLE
Craft 2 - A locked user crashes entries they've authored

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#3908]
### Description

If a user has too many failed logins and gets locked out, it causes crashes and timeouts in various parts of the system.

- Unable to search & view that user in the CP
- Unable to search & view any entries they've authored
- Equally destructive for their user/entry pages on the front-end

### Steps to reproduce

1. Create a user, login as that user.
2. Mess up your password repeatedly and get locked out.
3. As the admin, try to find & access that user in the CP.

**ALSO:**

1. Create a user, login as that user.
2. Create an entry (so the new user is the Author).
3. Mess up your password repeatedly and get locked out.
4. As the admin, try to find & access that entry in the CP.

**ALSO:**

Any entries on the front-end that belong to the user won't load. They cause a timeout instead.

### Additional info

- Craft version: 2.7.5
- PHP version: 7.0 (production) & 7.1 (local)
- Database driver & version: MySQL 5.7 (production) & MariaDB (local)
- Plugins & versions: So, so many

**Comment by brandonkelly** [comment]
> Unable to search & view that user in the CP

You should be able to find them if you set the Status to “Locked”.

But yeah, we recently became aware of how destructive a locked user can be to the system, and we fixed it in 3.1.7 by changing how Craft treats locked accounts. It was a bit involved though, and relied on some other changes made in 3.0 and 3.1, so not something we can easily backport to Craft 2.

**Comment by lindseydiloreto** [comment]
Ok cool, good to know it's already been addressed! No worries about backporting it... this may be the inspiration I need to finally pull the trigger on a C3 upgrade. 🙂 

Thanks!

**Comment by lindseydiloreto** [comment]
This just bit me again, on a different Craft 2 site.

For anyone else looking for a fix to this (including future me), you can just add this to your config...

```
'maxInvalidLogins' => false,
```

https://docs.craftcms.com/v2/config-settings.html#maxinvalidlogins
