### ISSUE TITLE
Craft 2 syntax in Craft 3 Docs

### ISSUE THREAD

**Issue by missmatsuko** [craftcms/cms#3913]
### Description
I think there's still a lot of Craft 2 syntax in the Craft 3 docs.

e.g. in [Searching](https://docs.craftcms.com/v3/searching.html#searching-for-specific-element-attributes) `craft.request.getParam('q')` is used, although [Changes in Craft 3](https://docs.craftcms.com/v3/changes-in-craft-3.html#template-functions) indicates it's changed from `craft.request.getParam(name)` to `craft.app.request.getParam(name)`.

I noticed others, too. Should they be updated?

### Steps to reproduce

1. Search in the docs for Craft 2 syntax.

### Additional info

- Craft version: 3.x.x
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed all `craft.request` references for the next release. Let me know if you run into anything else.

**Comment by missmatsuko** [comment]
I think I found some more, but made a PR for them instead of listing them out.
