### ISSUE TITLE
[Feature Request]: Change {% exit 404 %} Behavior

### ISSUE THREAD

**Issue by mattcdavis1** [craftcms/cms#3915]
Currently, when i use {% exit 404 %} in a template, a `yii\web\HttpException` is thrown which then causes a `Twig_Error_Runtime` exception to be thrown.  This differs from how a normal 404 is handle where a `yii\web\NotFoundHttpException` is thrown.

Although the end result is the same (404 response code + rendering of 404 template), the generic `Twig_Error_Runtime` exception that is thrown makes exception notification reporting difficult (i.e. Bugsnag).  Ideally, i don't want to ignore `Twig_Error_Runtime` exceptions but right now i have to or i'll get overwhelmed with notifications from 404s.

If there's some better way of handling this with the existing functionality please let me know. I'm using the [Superbig Bugsnag Plugin](https://superbig.co/plugins/bugsnag) currently.

**Comment by brandonkelly** [comment]
Done for the next release!

**Comment by mattcdavis1** [comment]
great - thanks!
