### ISSUE TITLE
Can't get field value from a different locale of a global set

### ISSUE THREAD

**Issue by Sam-Black-0013** [craftcms/cms#3919]
### Description
I am trying to get the a global set field value from a different locale than the current locale, but the value returned is null
{{  globalHandle.locale("es").fieldHandle }}

**Comment by brandonkelly** [comment]
Is this for Craft 2 or 3?

**Comment by Sam-Black-0013** [comment]
Craft 3
I tried [this answer](https://craftcms.stackexchange.com/questions/8253/how-can-i-retrieve-a-global-value-in-a-different-locale) but it did not work. but someone suggested to do it like this: 
`{% if locale == "es" %}
{% set localeSetHandle = craft.app.globals.getSetByHandle('globalSetHandle', 1) %}
{% else %}
{% set localeSetHandle = craft.app.globals.getSetByHandle('globalSetHandle', 2) %}
{% endif %}
{{ localeSetHandle .fieldValue}}`

and it worked

**Comment by brandonkelly** [comment]
Yeah that SE answer is for Craft 2, which had “locales”, but those are now “sites” in Craft 3.

The [Global Set Queries](https://docs.craftcms.com/v3/dev/element-queries/global-set-queries.html) page in the Craft 3 docs explains how to load a global set from a different site. Easiest way is using the [site](https://docs.craftcms.com/v3/dev/element-queries/global-set-queries.html#site) parameter.

```twig
{% set globalSet = craft.globalSets()
    .site('siteB')
    .one() %}
```

**Comment by Sam-Black-0013** [comment]
Craft 3
I tried [this answer](https://craftcms.stackexchange.com/questions/8253/how-can-i-retrieve-a-global-value-in-a-different-locale) but it did not work. but someone suggested to do it like this: 
`{% if locale == "es" %}
{% set localeSetHandle = craft.app.globals.getSetByHandle('globalSetHandle', 1) %}
{% else %}
{% set localeSetHandle = craft.app.globals.getSetByHandle('globalSetHandle', 2) %}
{% endif %}
{{ localeSetHandle .fieldValue}}`

and it worked
