### ISSUE TITLE
Issue with duplicate routes

### ISSUE THREAD

**Issue by olivierbon** [craftcms/cms#3922]
### Description

Getting `array_multisort(): Array sizes are inconsistent` on front end when a duplicate route exists.

### Steps to reproduce

1. Create twice the same route in the cp/settings/routes
2. access front of site

### Additional info

- Craft version: 3.1.15
- PHP version: 7.2.1

**Comment by loqus** [comment]
This is exactly what I needed after the last update. Thx!

**Comment by brandonkelly** [comment]
@loqus You can update to that change immediately by changing your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#cba5d6032afc6c2682e3bb83686a085954ccd771 as 3.1.5",
  "...": "..."
}
```

Then run `composer update`.
