### ISSUE TITLE
Craft doesn't return to active tab after saving content if the tab contains accented character(s)

### ISSUE THREAD

**Issue by benface** [craftcms/cms#3923]
### Steps to reproduce

1. In the field layout editor of any entry type, add 3 tabs with the following titles: "Contenu", "Description", and "Médias". Put at least a field in each tab.
2. Go to an entry that uses this field layout. Enter some content in the second tab, then do "Save and continue editing". Notice the second tab (Description) is still active when the page is refreshed.
3. Now move to the third tab (Médias), enter some content, and "Save and continue editing" again.

**Expected result**: The page is refreshed and the third tab is still active.
**Actual result**: The page is refreshed and the first tab is now active. It seems to do that for any tab that contains non-ASCII characters in its title.

### Additional info

- Craft version: 3.1.14
- PHP version: 7.2.13
- Database driver & version: MySQL 5.7.23

**Comment by brandonkelly** [comment]
Fixed for the next release. Thanks for reporting!
