### ISSUE TITLE
statusCode not available in error template, (exception-) code always '0'

### ISSUE THREAD

**Issue by punishirt** [craftcms/cms#3924]
### Description
In the error templates, the HTTP status code is not available. I want to make one dynamic error template with logic thats based off of the value of this status code. I used `code` for this purpose, only to realise that this is the code of the exception. (And somehow is always `0`?) 

As far as i can tell, currently, status code is only used to determine which template to load.

Current template variables:
```
$variables = array_merge([
    'message' => $message,
    'code' => $exception->getCode(),
    'file' => $exception->getFile(),
    'line' => $exception->getLine(),
], get_object_vars($exception));
```

Ideal template variables:
```
$variables = array_merge([
    'message' => $message,
    'code' => $exception->getCode(),
    'statusCode' => $statusCode,
    'file' => $exception->getFile(),
    'line' => $exception->getLine(),
], get_object_vars($exception));
```

### Steps to reproduce

1. In `general.php` enable custom error templates by setting a path with `errorTemplatePrefix`
2. Create `error.twig` in the directory specified in the previous step and use it to print out `{{ code }}`
3. Trigger an error somewhere by adding a `{% exit 500 %}` or something similar.

### Additional info

- Craft version:
3.1.14

- PHP version:
7.0
- Database driver & version:
MySQL 5.7.25-28

- Plugins & versions:

**Comment by brandonkelly** [comment]
If the exception was a `yii\web\HttpException`, then its `statusCode` property will be available to the error template as a `statusCode` variable. It will get merged into that array via that `get_object_vars($exception)` call.
