### ISSUE TITLE
Add 'disabled' property to autosuggest field

### ISSUE THREAD

**Issue by timeverts** [craftcms/cms#3925]
This is a feature request.

Please add support for the 'disabled' property on the autosuggest field template.

**Comment by brandonkelly** [comment]
Autosuggest fields are powered by [vue-autosuggest](https://github.com/darrenjennings/vue-autosuggest), which doesn’t support a `disabled` property as far as I can tell.

If you want to disable it, you could use a normal `text` input instead.

**Comment by timeverts** [comment]
I initially raised the ticket after first testing it by changing Craft's autosuggest template and it seemed to work there. I've also done a JS Fiddle showing the disabled property in use: https://jsfiddle.net/o65w4p8z/

**Comment by brandonkelly** [comment]
Still, though, what’s the use case for this? Why is it worth instantiating a Vue app if the input is just going to be disabled?

**Comment by timeverts** [comment]
@brandonkelly, that's certainly a good point. I guess it was more for convenience then.

My use case was the following: a Commerce gateway settings template that takes into account environment variable suggestions (hence the autosuggest field) but also factors in the settings being overridden via the `commerce-gateways.php` config file. In the case where the setting is overridden, the field input needs to be disabled, since changing it's value would have no affect on save.

```
{% from "_includes/forms" import autosuggestField, lightswitchField %}

{% set gatewayOverrides = craft.commerce.gateways.getGatewayOverrides(gateway.handle) %}
{% set configFileName = 'craft/config/commerce-gateways.php' %}
{% set overriddenWarning = "This is being overridden in {file}."|t('commerce-fatzebra', {file: configFileName}) %}

{{ autosuggestField({
    first: true,
    label: 'Username'|t('commerce-fatzebra'),
    id: 'username',
    name: 'username',
    suggestEnvVars: true,
    suggestAliases: true,
    value: gateway.username,
    required: true,
    disabled: gatewayOverrides.username is defined,
    warning: gatewayOverrides.username is defined ? overriddenWarning,
    errors: gateway.getErrors('username')
}) }}
```
In the above case it is convenient for the `autosuggestField` macro to support the `disabled` property so I didn't have to wrap it in an if clause to swap it out to use a `textField` macro when the override exists (unless there's a way to put the macro name in a Twig variable perhaps?).

Let me know your thoughts/advice.

**Comment by brandonkelly** [comment]
Yeah fair enough.

**Comment by brandonkelly** [comment]
Added for the next release!
