### ISSUE TITLE
[feature request] Add method for querying site by group handle

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#3926]
Right now we can just query sites by their group ID, using `getSitesByGroupId`. 
It would be usefull to have ability to query sites by their group name/handle.

**Comment by brandonkelly** [comment]
Site groups don’t have handles.

**Comment by piotrpog** [comment]
@brandonkelly 
They have names. So, query by name maybe? If we have multiple site groups we have to memorize their IDs.
