### ISSUE TITLE
Documentation link missing from Plugin when installed manually

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/cms#3929]
### Description

This might be expected behaviour, however...

When a plugin is installed manually through the command line via composer, for example:
```
composer require craftcms/postmark
``` 
The documentation link is missing:
![screen shot 2019-02-28 at 15 45 18](https://user-images.githubusercontent.com/2373940/53574455-f63b4980-3b6f-11e9-9169-19b91d49e84d.png)

When a plugin is installed through the Craft CMS plugin store, the documentation link is present:
![screen shot 2019-02-28 at 15 49 15](https://user-images.githubusercontent.com/2373940/53574729-6cd84700-3b70-11e9-8c60-8389a35c837f.png)

_I appreciate the screenshots above show 1 plugin installed and the other not, but it's the same behaviour_

### Steps to reproduce

1. Install a plugin manually through the command line (now check settings > plugins and notice the documentation link is missing, even though it's specified in the composer.json file
2. Instal the same plugin, but through the Craft Plugin Store (check settings > plugins and notice the documentation link is present)

### Additional info

- Craft version: 3.1.15
- PHP version: 7.2.14
- Database driver & version: MySQL 5.5.5
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Huh… looks like Packagist doesn’t include the `support` key from packages’ `composer.json` files in its package data. We’ll have to start including documentation links in the `extra` key as well.
