### ISSUE TITLE
Display Volume & more metadata on the Asset HUD

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#3930]
With an asset field, your only option to see the selected asset is via the HUD (double click).

However, within the HUD there are key things you can't see:

- Which Volume the asset is in?
- Other meta data you might have in your asset index columns, especially relevant for assets:
  - image dimensions
  - file size
  - url/download: https://github.com/craftcms/cms/issues/3729
  - replace file: https://github.com/craftcms/cms/issues/2842
- "copy reference tag"

Volume is the biggest problem - more often than not I have to remove the selection and select it again, just to figure out what volume it is in.

Pie-in-the-sky/long term thoughts – it may make sense for displayed meta data for both the entry sidebar and HUD to be customized per element source (similar to how asset indexes are now). This might allow you to, say, display the element ID in publish side, or add the kind asset things for the HUD I'm talking about here.

**Comment by brandonkelly** [comment]
Mostly resolved for 3.7 via asset editor [slideouts](https://github.com/craftcms/cms/pull/8017), which include location, file size, the uploader (if known), and image dimensions.

Not including the ability to download/replace the file, but you can click the link to open the asset’s dedicated edit page if you need to do those things.
