### ISSUE TITLE
SQL Constraint Violation When Saving "as new entry" with Field as Slug

### ISSUE THREAD

**Issue by coryzibell** [craftcms/cms#3933]
### Description
I have a section where the "Entry URI Format" is a field from the entry, e.g. `{websitePageUrl}`.
If I attempt to open one of these entries, modify that field, and save as a new entry, I receive the following SQL error:

```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'benefits-of-us-surrogacy-agencies-for-parents-in-norway-norwegia' for key 'elements_sites_uri_siteId_unq_idx'
The SQL being executed was: INSERT INTO `craft_elements_sites` (`elementId`, `siteId`, `slug`, `uri`, `enabled`, `dateCreated`, `uid`, `dateUpdated`) VALUES (5503, 1, 'fordeler-med-et-amerikansk-surrogatiagentur-kontra-andre-land-for-foreldre-i-norge', 'benefits-of-us-surrogacy-agencies-for-parents-in-norway-norwegian', 1, '2019-02-28 21:14:34', '87b4cdf7-3b13-4793-b52d-d42c586207f8', '2019-02-28 21:14:34')
```

It appears that the values being inserted are not reflecting the changes I make to the field or slug. (E.g. when I just use `new-test-entry` in the `{websitePageUrl}` field, and `new-test-entry-slug` for the slug, the SQL error is the same.

### Steps to reproduce

1. Create a section with a single field.
2. Set the "Entry URI Format" of the section to that field in the format `{fieldName}`
3. Create an entry in the section.
4. Re-open the entry. Change the field used above, as well as the title. Attempt to "Save As New Entry"

### Additional info

- Craft version: 3.1.15
- PHP version: 7.1
- Database driver & version: MySQL 5.6
- Plugins & versions:

Asset Rev	6.0.2
Calendar Links	1.0.1
Child Me!	1.0.4
Cloudflare	0.2.7
Contact Form	2.2.3
Cookies	1.1.11
CP Field Inspect	1.0.5
Environment Label	3.1.5
Feed Me	3.1.10
Fetch	1.2.0
Guide	1.3.2
Image Resizer	2.0.4
Inlin	2.1.1
Inventory	2.0.2
Json Client	1.0.3
Nanoslugs	1.0.3
Position Fieldtype	1.0.14
Redactor	2.3.2
SEO	3.5.4
Spoon	3.3.3
SuperSort	3.0.1
Super Table	2.1.13.3
Twig Perversion	2.0.7

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you please send in a ticket from your Dashboard, and reference this issue URL in the message body?
