### ISSUE TITLE
resave/entries has "resave" as its default id

### ISSUE THREAD

**Issue by nilsenpaul** [craftcms/cms#3940]
### Description
If I use the console command `resave/entries` without any params, it doesn't find any elements. A bit of debugging showed that `$this->id` in `ResaveController.php` returns `"resave"` if no specific id is set. I think this is default Yii2 behaviour.

### Steps to reproduce

1. Run `./craft resave/entries` without any params, or at least without --id

### Additional info

- Craft version: 3.1.15
- PHP version: 7.0

**Comment by jonleverrier** [comment]
@nilsenpaul Looks like this was fixed with this commit https://github.com/craftcms/cms/commit/a308a9e30b42893a015861a8a436ae71f5c6a333

**Comment by nilsenpaul** [comment]
@jonleverrier Cool, thanks!
