### ISSUE TITLE
Resave controller uses the id for its uid filter

### ISSUE THREAD

**Issue by nilsenpaul** [craftcms/cms#3941]
### Description
When settings --uid for a resave command, the --id parameter gets used:

    // vendor/craftcms/cms/src/console/controllers/ResaveController.php, line 206:
    if ($this->uid) {
        $query->uid(explode(',', $this->id));
    }

### Additional info

- Craft version: 3.1.15

**Comment by jonleverrier** [comment]
@nilsenpaul Looks like this was fixed with this commit https://github.com/craftcms/cms/commit/a308a9e30b42893a015861a8a436ae71f5c6a333
