### ISSUE TITLE
[Feature Request] Add a Read-only feature to fields

### ISSUE THREAD

**Issue by Sam-Black-0013** [craftcms/cms#3942]
### Description
I think Craft would be more awesome and more handsome if it allowed me to mark some fields as read-only. just a small checkbox in the field's settings 😽

**Comment by carlcs** [comment]
There’s a plugin for it https://plugins.craftcms.com/incognito-field

**Comment by brandonkelly** [comment]
@Sam-Black-0013 Is that plugin relatively similar to what you’re looking for?

**Comment by Sam-Black-0013** [comment]
Yub it is, thanks. But can't it be added as a core feature in fields ?

**Comment by Sam-Black-0013** [comment]
AWW @brandonkelly u guys are the best >.<

**Comment by missmatsuko** [comment]
I would find it handy if there could be readonly setting on fields by user roles. Like if admins/devs could edit the field from the CMS without changing the field type from readonly to editable, but it would always be readonly for everyone else.

**Comment by brandonkelly** [comment]
Craft 3.5 has a new field layout designer, which includes the ability to add additional UI elements, including one that pulls in a site template of your choosing. So you can use that to put whatever arbitrary HTML you want in your field layout, which I’d say resolves this.

**Comment by carlcs** [comment]
Brandon, I think you misunderstood the feature request. The idea is to be able to configure regular fields’ visibility on edit pages. Ideally this would work with every field type, and configuration would be per field layout.

The Incognito field plugin solves this for plain text fields only. Visibility can be configured dynamically using Twig.

```twig
{{ currentUser.isInGroup('editors') ? 'readonly' : 'hidden' }}
```

**Comment by brandonkelly** [comment]
There hasn’t been any mention of toggling field _visibility_ here, just _writability_. Toggling field visibility based on user groups is covered by #947.

I interpreted the issue as requesting a _field-level_ “Read-only” checkbox – not something that could sometimes be writable, sometimes not, depending on a condition. At which point, it would be better to just not have a field in the first place, and use a Template UI element in the field layout. But can reopen if I was mistaken.

**Comment by carlcs** [comment]
Ah ok, that’s how you read it! I don’t see the purpose of a field that’s not writeable at all, so I assumed the issue is about its rendering in the control panel. Content would be written to it in other ways, from front end forms, or programatically.

#947 is pretty much covering my intepretetion of this request.

**Comment by brandonkelly** [comment]
> I don’t see the purpose of a field that’s not writeable at all

Yeah good point. I’ll go ahead and reopen on the assumption that the request is for _sometimes_-read-only fields.
