### ISSUE TITLE
Redactor & other previously installed plugins missing from plugin store after 2.7.5 to 3.0.41 upgrade

### ISSUE THREAD

**Issue by ademers** [craftcms/cms#3948]
### Description

Redactor is missing from the plugin store after upgrading Craft 2.7.5 to to 3.0.41.

**UPDATE**: According to https://github.com/craftcms/redactor, Redactor requires 3.1.x or later. I plan to eventually upgrade to 3.1.x, but there seem to be all kinds of issues, hence the upgrade to 3.0.41 as an intermediary step.

UPDATE 2: In the meantime, I've discovered that other plugins that had been installed in the Craft 2.x version of the site do not appear when searching plugin store. For example: Sprout Forms & Fields, Dukt Videos, and Dolphiq XML Sitemap. The ones with status _available_: https://cl.ly/dfd29e130649

### Steps to reproduce

1. Upgrade Craft 2.7.5 to 3.0.41.
2. Search for Redactor in the plugin store or click install button next to Redactor in rich text field. Screenshot of store search results: https://cl.ly/5e0ce8bfd862

### Additional info

- Craft version: 3.0.41
- PHP version: 7.0.33
- Database driver & version: MySQL 5.5.5
- Plugins & versions: None

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Redactor and other missing plugins are now back in the Craft 3.0 Plugin Store, at their latest 3.0-compatible versions (2.1.7 in Redactor’s case).
