### ISSUE TITLE
Make the "Title" field behave like all other fields in the Admin UI

### ISSUE THREAD

**Issue by andreimoment** [craftcms/cms#3953]
### Description
Currently, the "Title" field is repeated in each of the tabs of an entry's admin panel. It also cannot be assigned to a tab in the field layout in the settings section.

**Making the Title field behave like the rest of the fields would be an improvement to the consistency of the UI and UX of the CMS.** Right now Title behaves differently... It could still be mandatory, but position-able within the content tabs.

It has confused users because they didn't understand that this was always the same field.

![image](https://user-images.githubusercontent.com/6190/53924049-52e6aa80-402f-11e9-9d7b-4041b8556fe6.png)

### Steps to reproduce

1. Set  an entry type to have more than one field set / tab
2. Notice that it is not possible to assign the Title field to any of the tabs during the setup process.
2. When editing an instance of the entry, switch between the tab fields and you'll notice that the Title field appears in all of them.

### Proposed improvement

Make it possible to assign the Title field to a field set just like any of the other fields. If necessary, make it non-remove-able. 

<img width="1042" alt="screen shot 2019-03-06 at 5 06 37 pm" src="https://user-images.githubusercontent.com/6190/53924828-6ba48f80-4032-11e9-934a-d28f80a3422a.png">

### Additional info

- Craft version: 3.1
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by dennisfrank** [comment]
I also never understood why the field has to be displayed in every tab. It has confused clients of mine too because they didn't understand that this was the always the same field. They tried to change the title for different tabs.

**Comment by dennisfrank** [comment]
I already postet this as a CSS-only workaround(!) in [Discord](https://discordapp.com/channels/456442477667418113/456442477667418115/553014199958372362):

```css
[id^="tab-"]:not(:first-child) {
  position: relative;    
  margin-top: -81px;
  background: #fff;
}
```

**Comment by davidhellmann** [comment]
For me it's fine to have this field in every tab. But maybe it's fine to put it outside the tabs to make it more clear. Understand the problem (UX).

+1 for a better solution but not the solution like in post one

**Comment by dennisfrank** [comment]
I played a bit with CSS. What do you think of something similar to this?

![craft-title](https://user-images.githubusercontent.com/65968/53957048-a6afcd00-40dd-11e9-998d-146e2f2cebbf.gif)

**Comment by davidhellmann** [comment]
Right direction!

**Comment by andreimoment** [comment]
@dennisfrank this UI is much clearer about Title being the same field in different tab states. 

I however wonder about the balance of pros and cons of repeating the field. 

Having it in one place only and not repeated makes it easy to associate with that one place and eliminates confusion. 

Having it be accessible from everywhere is not a common ui pattern and still a bit confusing imo. 

Lastly, I am curious about the history behind the decision to make it available everywhere in the first place. Did admin users need access to title change more often than anything else?

**Comment by missmatsuko** [comment]
There's an existing issue for moving the title field outside/above tab content:
#902

**Comment by thejoshsmith** [comment]
I've written a simple plugin that shifts the title field to the sidebar: https://plugins.craftcms.com/craft-title-to-sidebar.

**Comment by brandonkelly** [comment]
As of the next Craft 3.5 release, it will be possible to explicitly set the position of Title fields, so it will no longer appear on every tab.

<img width="289" alt="A field layout designer with a Title field" src="https://user-images.githubusercontent.com/47792/87213216-4c79da00-c2d8-11ea-8e60-1dcd597f2867.png">
