### ISSUE TITLE
Editing an entry via index view HUD doesn't create a new version of the entry

### ISSUE THREAD

**Issue by mikegraham00** [craftcms/cms#3959]
### Description

When editing an entry via the index view HUD, a new version of the entry is not created - even if versions are enabled for this section.

### Steps to reproduce

1. view a section that has versioning activated entries index view page
2. select an entry by checkbox
3. click the actions icon dropdown
4. select "Edit Entry"
5. make a change to the entry in the HUD and save
6. visit the edit entry detail view
7. click the versions dropdown & see that a new version has not been created.

### Additional info

- Craft version: 3.1.16
- PHP version: 7.1
- Database driver & version:
- Plugins & versions: several...

**Comment by brandonkelly** [comment]
Fixed for the next release. Thanks for reporting!
