### ISSUE TITLE
Feature Request: Site-specific databases

### ISSUE THREAD

**Issue by cscomfort** [craftcms/cms#3962]
### Description

It would be great, if ever possible, for the Sites feature to support unique site-specific databases similar to Drupal's multisite capabilities. The more mature the Sites feature matures, the easier it will be to deploy solutions that have traditionally depended on Drupal -- e.g. multiple sites across a university department.

**Comment by brandonkelly** [comment]
At that point you’re talking about completely separate Craft installs. Maybe you just want a way to centrally manage multiple installs?

**Comment by cscomfort** [comment]
Thanks for the quick response, and yes centrally managed installs could certainly be a workable solution for some instances.

**Comment by brandonkelly** [comment]
Cool, can you post as a separate feature request, with some examples of how you envision it would improve your workflows?

**Comment by cscomfort** [comment]
Will do. Cheers.
