### ISSUE TITLE
Tokens documentation is inaccurate

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/cms#3967]
It looks as though the `craft\services\Tokens::createToken` method documentation describes a `routes.php`-style object…

```php
['action' => "controller/action", 'params' => ['foo' => 'bar']]
```

…when in reality, the shape is more like this:

```php
['controller/action', ['foo' => 'bar']
```

At least… this is what I ended up needing to do?

That brought up a question: can you route a token to a template, or does it have to map to a controller action? (This is also a bit unclear, as the comment suggests “…*if you want* [it] to be routed to a controller action…”)

**Comment by AugustMiller** [comment]
The latter format is used elsewhere, i.e: https://github.com/craftcms/cms/blob/develop/src/controllers/LivePreviewController.php#L60-L65

**Comment by brandonkelly** [comment]
Thanks for pointing that out. Fixed now. https://docs.craftcms.com/api/v3/craft-services-tokens.html#method-createtoken
