### ISSUE TITLE
Incrementing token results in SQL error

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/cms#3969]
### Description

When setting a `usageLimit` on a new Token and subsequently accessing/consuming the token, I'm getting an error about an unknown column:

```
Error Info: Array
(
    [0] => 42703
    [1] => 7
    [2] => ERROR:  column "usagecount" does not exist
LINE 1: UPDATE "tokens" SET "usageCount"=usageCount + 1, "dateUpdate...
                                         ^
HINT:  Perhaps you meant to reference the column "tokens.usageCount".
)
```

It sounds like something's wrong with [`new Expression('usageCount + 1')`](https://github.com/craftcms/cms/blob/develop/src/services/Tokens.php#L134), but I'm useless when it comes to SQL expressions! 😢 

### Steps to reproduce

1. Create a Token with a `usageLimit`: `$tokens->createToken(['controller/action', ['param' => 'val']], 100);`;
2. Trigger the token by making a request: `https://mydomain.com/path?token=EQhn5d29k1kT-1yjldVbi8gFRZf0v2h6`;
3. Maybe observe error?

### Additional info

- Craft version: Craft Pro 3.1.15
- PHP version: 7.2.14
- Database driver & version: PostgreSQL 10.6
- Plugins & versions: Commerce, and a couple of business-logic plugins (one of which generates this token)

**Comment by brandonkelly** [comment]
Thanks, that’s fixed for the next release.

To get the fix early. change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#8a4f94fd46ff187c0a293c24713f58960d9f4ef2 as 3.1.17.1",
  "...": "..."
}
```

Then run `composer update`.
