### ISSUE TITLE
Minor issue with thumbnail for pictures in portrait format 

### ISSUE THREAD

**Issue by thomasbendl** [craftcms/cms#3970]
### Description
When uploading a picture in portrait format to assets in CP it is streched to an 100px width and 100px height picture in thumbnail preview. Also in listview it is streched to an 30px 30px pic.

Update CSS in .tableview .element .elementthumb should fix the problem. Width is also set to 100px fo portrait pictures

### Steps to reproduce

1. Got to CP Assets
2. Upload picture in portrait format
3. Look  thumbnail or listview

### Additional info

- Craft version: 3.1.16
- PHP version: 7.1.6
- Database driver & version: MySQL 5.6.35
- Plugins & versions: Embedded Assets 2.0.0, Redactor 2.3.2, Redirect plugin for Craft 3 1.0.20, SEOmatic  3.1.45

![screenshot-tulpen](https://user-images.githubusercontent.com/8804216/54076429-cc8acc80-42ab-11e9-94ba-60874d82bd3e.jpg)

**Comment by thomasbendl** [comment]
.elementthumb > img{
	width: auto;
}

should fix the Problem!

**Comment by andris-sevcenko** [comment]
I'm not able to reproduce this. What browser are you using?

**Comment by dennisfrank** [comment]
I've only just seen this issue. I posted a PR for this earlier: https://github.com/craftcms/cms/pull/4179

I am sure there are different solutions. I used `object-fit: contain;` on the image.

**Comment by brandonkelly** [comment]
@dennisfrank We’re still not able to reproduce the issue in the first place. Is it happening for all portrait images, or just some? What browser are you using? (I’ve tested various portrait images in Safari, Chrome, and Firefox, all without issue.)

**Comment by wsydney76** [comment]
Here this is happening when the 'Embedded Assets' plugin is enabled,  there is a  `.elementthumb > img {
	width: 100%;
}` style in their main.scss file.

spicywebau/craft-embedded-assets#99 seems to be the corresponding issue

**Comment by brandonkelly** [comment]
Thanks @wsydney76. I’ll leave it to Spicy to fix this.
