### ISSUE TITLE
UnknownPropertyException 500 error logging in the admin section after update 3.1.17.1

### ISSUE THREAD

**Issue by loqus** [craftcms/cms#3973]
### Description
I got locked out of the admin environment by a 500 error

The web error log states: 
`yii\base\UnknownPropertyException: Setting unknown property: craft\models\Updates::message in /home/mysite/httpdocs/vendor/yiisoft/yii2/base/Component.php:209`

When commenting out this line (209) 
`throw new UnknownPropertyException('Setting unknown property: ' . get_class($this) . '::' . $name);`

The admin works as expected
### Steps to reproduce

Update Craft to 3.1.17.1

I tried fixing this by removing the vendor folder and composer.lock and do a composer update. But that didn't do the trick

### Additional info

- Craft version: Craft Pro 3.1.17.1
- PHP version: 7.2.15
- Database driver & version: MySQL 5.5.60
- Plugins & versions:

**Comment by olivierbon** [comment]
Could you try running `./craft clear-caches/all`

**Comment by loqus** [comment]
Tried it, but uncommenting the line resulted in the same error.

**Comment by olivierbon** [comment]
Could you send me your composer.json and composer.lock files at support@craftcms.com?

**Comment by loqus** [comment]
Sent!
I see I also have some trouble with the Plugin Store and and unknown error in the installed plugin list. Just thought I'd mention it if It may be related

**Comment by theskyfloor** [comment]
Having this same error.

**Comment by theskyfloor** [comment]
Actually never mind. I can only load the CP once after clearing caches, then I have to clear again to load the next page.

**Comment by angrybrad** [comment]
@theskyfloor any chance this is on a public box and you could send some Craft CP and SSH access to support@craftcms.com?

**Comment by theskyfloor** [comment]
It is. The tough thing is it's on the client's server and they are the devops server admin : (  Let me see what I can do!

**Comment by phoob** [comment]
Hello! Getting the same error, but only on one Craft install, not the other.. Here is  a stack trace: https://sentry.dfo.no/share/issue/328978bc5d1b4ec9b4b598e1fbd11099/

**Comment by phoob** [comment]
@angrybrad I can't give you SSH access because of firewall restrictions, but I could give you a login to the CP.. (but now I've downgraded it to 3.1.16...)

**Comment by phoob** [comment]
@theskyfloor : what plugins do you have activated..? Ours are AsyncQueue, CodeMirror, Queue Manager, Redactor, Spoon, and Workflow..

**Comment by theskyfloor** [comment]
@phoob I have a lot of plug-ins on this install but we definitely have some overlap which is interesting: AsyncQueue, CodeMirror, Queue Manager, Redactor, Spoon, and Workflow are all installed on this site as well for me.

**Comment by echantigny** [comment]
@angrybrad I'm having the same issue here if I install 3.1.17.1.  Other than Redactor, none of the plugins overlap with the other guys.

**Comment by rtgoodwin** [comment]
Following, had the same issue. Redactor is the only overlap with @phoob. (I'm Serenity_Nowver on Discord)

**Comment by klick** [comment]
Another one:

`#0 /var/customers/webs/user/storage/runtime/compiled_templates/df/df0c16a54d981ac5acf688cef8747e1f1d7c948e99f12b72cdeeef5005bd2e35.php(60): Twig_Template->displayBlock('body', Array, Array)
#1 /var/customers/webs/user/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_c6de53c1e4cac33583d6207ea858f8dd5cdc248068cbbc70e3aea8aa84f842d2->doDisplay(Array, Array)
#2 /var/customers/webs/user/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#3 /var/customers/webs/user/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#4 /var/customers/webs/user/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#5 /var/customers/webs/user/storage/runtime/compiled_templates/35/35f91127ce84dee1b476336501550007b1dfbb7a2b5c624262e9cbe712a66942.php(40): craft\web\twig\Template->display(Array, Array)
#6 /var/customers/webs/user/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_6d109b48f8d7dfb06e3ec1982e9d7a2a45fa08b9b313a2f860350989c1457dba->doDisplay(Array, Array)
#7 /var/customers/webs/user/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#8 /var/customers/webs/user/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#9 /var/customers/webs/user/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#10 /var/customers/webs/user/storage/runtime/compiled_templates/a2/a248df1bea817936a1ba55105afd43bc0ca8d578e085c30480e85e6dbe551ee0.php(95): craft\web\twig\Template->display(Array, Array)
#11 /var/customers/webs/user/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_29c5a7bfe63811cc678605c74b9be4afd0958415b7165396c0f995ab55f3e35a->doDisplay(Array, Array)
#12 /var/customers/webs/user/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#13 /var/customers/webs/user/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#14 /var/customers/webs/user/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#15 /var/customers/webs/user/storage/runtime/compiled_templates/20/20e8ccad45a868ad50f4715db8fdbfb38fee1c9d3323066e69ecf86396677fc8.php(54): craft\web\twig\Template->display(Array, Array)
#16 /var/customers/webs/user/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_815df9b9e5f4e88f11b25b77caf0c07ac90a7f57aa7c400ce639e7c276cf03ad->doDisplay(Array, Array)
#17 /var/customers/webs/user/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#18 /var/customers/webs/user/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#19 /var/customers/webs/user/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#20 /var/customers/webs/user/storage/runtime/compiled_templates/1c/1cc00e0a68838e58f8cf166e29c1a0c37bb175996b28dc25a8c74d841c6b0454.php(40): craft\web\twig\Template->display(Array, Array)
#21 /var/customers/webs/user/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_af6a88fa156c1be1038585408e1ce1ee67c5c514baac36b46587227a9174448e->doDisplay(Array, Array)
#22 /var/customers/webs/user/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#23 /var/customers/webs/user/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#24 /var/customers/webs/user/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#25 /var/customers/webs/user/vendor/twig/twig/lib/Twig/Template.php(371): craft\web\twig\Template->display(Array)
#26 /var/customers/webs/user/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#27 /var/customers/webs/user/vendor/craftcms/cms/src/web/View.php(337): Twig_Environment->render('users', Array)
#28 /var/customers/webs/user/vendor/craftcms/cms/src/web/View.php(384): craft\web\View->renderTemplate('users', Array)
#29 /var/customers/webs/user/vendor/craftcms/cms/src/web/Controller.php(161): craft\web\View->renderPageTemplate('users', Array)
#30 /var/customers/webs/user/vendor/craftcms/cms/src/controllers/TemplatesController.php(78): craft\web\Controller->renderTemplate('users', Array)
#31 [internal function]: craft\controllers\TemplatesController->actionRender('users', Array)
#32 /var/customers/webs/user/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#33 /var/customers/webs/user/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#34 /var/customers/webs/user/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('render', Array)
#35 /var/customers/webs/user/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#36 /var/customers/webs/user/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('templates/rende...', Array)
#37 /var/customers/webs/user/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#38 /var/customers/webs/user/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#39 /var/customers/webs/user/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#40 /var/customers/webs/user/html/index.php(21): yii\base\Application->run()
#41 {main}`

**Comment by klick** [comment]
Same Error here.

`
#0 /var/customers/webs/usermitte/staging.user-service.de/vendor/yiisoft/yii2/BaseYii.php(546): yii\base\Component->__set('message', 'Server Error')
#1 /var/customers/webs/usermitte/staging.user-service.de/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(craft\models\Updates), Array)
#2 /var/customers/webs/usermitte/staging.user-service.de/vendor/craftcms/cms/src/services/Updates.php(106): yii\base\BaseObject->__construct(Array)
#3 /var/customers/webs/usermitte/staging.user-service.de/vendor/craftcms/cms/src/services/Updates.php(77): craft\services\Updates->getUpdates()
#4 /var/customers/webs/usermitte/staging.user-service.de/vendor/craftcms/cms/src/widgets/Updates.php(74): craft\services\Updates->getTotalAvailableUpdates()
#5 /var/customers/webs/usermitte/staging.user-service.de/vendor/craftcms/cms/src/controllers/DashboardController.php(514): craft\widgets\Updates->getBodyHtml()
#6 /var/customers/webs/usermitte/staging.user-service.de/vendor/craftcms/cms/src/controllers/DashboardController.php(99): craft\controllers\DashboardController->_getWidgetInfo(Object(craft\widgets\Updates))
#7 [internal function]: craft\controllers\DashboardController->actionIndex()
#8 /var/customers/webs/usermitte/staging.user-service.de/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/customers/webs/usermitte/staging.user-service.de/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /var/customers/webs/usermitte/staging.user-service.de/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('index', Array)
#11 /var/customers/webs/usermitte/staging.user-service.de/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('index', Array)
#12 /var/customers/webs/usermitte/staging.user-service.de/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('dashboard/index', Array)
#13 /var/customers/webs/usermitte/staging.user-service.de/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('dashboard/index', Array)
#14 /var/customers/webs/usermitte/staging.user-service.de/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#15 /var/customers/webs/usermitte/staging.user-service.de/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#16 /var/customers/webs/usermitte/staging.user-service.de/html/index.php(21): yii\base\Application->run()
#17 {main}
`

**Comment by phoob** [comment]
By the way: i have two craft sites on the same server, with very (very) similar configuration.. one of them works with 3.1.17.1, the other one fails..

**Comment by whoisjuan** [comment]
I'm also having this issue in (3.1.17.1). In my local if I downgrade Feed Me to 3.1.13, it breaks the console. If I upgrade it to 3.1.15 the error goes away. I cannot reproduce any of this in my remove server though. Maybe Feed Me is unrelated but seems that many people with this issue have Feed Me installed.

If you clear the caches and reload the CP you can gain momentary access to the CP until you move to another view. When I do that I'm seeing that this request `index.php?p=admin/actions/app/check-for-updates` is getting a 500.

**Comment by brandonkelly** [comment]
Is anyone still getting this error?

**Comment by theskyfloor** [comment]
I certainly was. I downgraded so I can't test further.

**Comment by phoob** [comment]
> Is anyone still getting this error? (Especially after running `./craft clear-caches/all`)

@brandonkelly yes: running `./craft clear-caches/all` fixes the problem only until Craft starts looking for updates again.. which appears to happen immediately. Then I get two error notices in CP, and when trying to reload the page, it fails. (https://sentry.dfo.no/share/issue/328978bc5d1b4ec9b4b598e1fbd11099/)

**Comment by whoisjuan** [comment]
I'm still getting it. `./craft clear-caches/all` only recovers the first load.

**Comment by JMKelley** [comment]
Getting the same error. Some overlap Feedme & Redactor. But doubt this is the issue.

**Comment by angrybrad** [comment]
Believe we found the root of this and it's on our end... will get a fix deployed shortly.

**Comment by brandonkelly** [comment]
We’ve confirmed this is fixed now! Run `./craft clear-caches/all` or delete the  contents of your `storage/runtime/cache/` folder and you should be back in bsusiness.

**Comment by echantigny** [comment]
@brandonkelly Any idea when this will be part of an official release?

**Comment by whoisjuan** [comment]
@brandonkelly can you clarify if this was a remote bug? because `./craft clear-caches/all` didn't work before, so I'm assuming something changed.

**Comment by eric-chantigny** [comment]
@whoisjuan After a bit of digging in the commit that closed this issue, I noticed that it is a file that is part of CraftNet, the system that powers the plugin store, updates and all that.  Most likely why it now works fine without any updates to Craft.

**Comment by whoisjuan** [comment]
@echantigny Thanks!

**Comment by brandonkelly** [comment]
Yeah sorry for not clarifying. The bug was on Craftnet’s end.
