### ISSUE TITLE
Import from project config fails(?) silently when running from CLI

### ISSUE THREAD

**Issue by nettum** [craftcms/cms#3977]
### Description
See https://github.com/fruitstudios/craft-linkit/issues/57
If I try to import this `project.yaml` file after the 3.1.17 update - sections, fields, usergroups etc. will not get synced. Only the plugins will get synced and installed.

Import will say:
```
    > applying existing project config ... done
    > saving the first user ... done
*** installed Craft successfully (time: 6.570s)

```
but something has failed on the way.
If I go into the linkit folder in vendor and set `$projectConfig->muteEvents = false;`, drop/create db and run `./craft setup` again everything will work.
This may be an issue with linkit, but I feel like I should get an error or something from craft, because the import did not go well. 

To reproduce:
1) Take the content from project.yaml pasted in https://github.com/fruitstudios/craft-linkit/issues/57
2) start with empty db
3) run `./craft setup`
4) Verify that sections, fields etc. *is not synced*

Same happens if I do the following:
1) start with empty db
2) set `'useProjectConfigFile' => false`
3) run `./craft setup`
4) set `'useProjectConfigFile' => true`
5) run `./craft project-config/sync` 
6) Verify that sections, fields etc. *is not synced*

This will for some reason work:
1) start with empty db
2) set `'useProjectConfigFile' => false`
3) run `./craft setup`
4) set `'useProjectConfigFile' => true`
5) Manually edit dateModified in project.yaml to force sync.
6) Reload page in CP.
7) Verify that sections, fields etc. *is synced*

- Craft version: 3.1.17.1
- PHP version: 7.2.16
- Database driver & version: Mysql 5.7.25
- Plugins & versions: Linkit 1.1.9

**Comment by andris-sevcenko** [comment]
This was a bug with linkit's install migration.
