### ISSUE TITLE
Add ability to download project.yaml file

### ISSUE THREAD

**Issue by intoeetive** [craftcms/cms#3979]
In our workflow, the changes to site structure are often made on remote server (production or staging), which are then synchronized back to local and other environments. 

It would be nice to have an utility which would allow to download project.yaml locally, instead of going to FTP for that. 

Is this something that you would consider to implement?

**Comment by brandonkelly** [comment]
Realistically we’d probably go with #3960 instead, but will leave this open just in case.

**Comment by brandonkelly** [comment]
We added a new “Project Config” utility in Craft 3.5, and the next release (3.5.6) will add a “Download” button to it:

<img width="908" alt="The project config data output within the Project Config utility, with a Download button below it" src="https://user-images.githubusercontent.com/47792/91130335-56755380-e660-11ea-96d3-db9a0a7bbc7a.png">

**Comment by brandonkelly** [comment]
Craft 3.5.6 is out now with that change.
