### ISSUE TITLE
Plugin store / Plugin Store (title case inconsistency)

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#3980]
### Description

Only a tiny thing, but is there somewhere that controls the case of the Plugin store link in the sidebar? All my sites have a mix of `Plugin store` and `Plugin Store`, and I can't find any reason why this might be.

![image](https://user-images.githubusercontent.com/1250017/54192138-f583ab00-44bf-11e9-8862-cc7f0cc91a87.png)

![image](https://user-images.githubusercontent.com/1250017/54192147-fcaab900-44bf-11e9-9749-d0b7ba056b7f.png)

### Additional info

- Craft version: 3.1.11, 3.1.4, 3.1.15
- PHP version: 7.1, 7.2
- Database driver & version: MySQL

**Comment by brandonkelly** [comment]
@darylknight Guessing on the one with a lowercase `s` you have your user account’s preferred language set to `en-GB` or something besides `en-US`, where `Plugin Store` gets “translated” to `Plugin store`. (Title Case is mostly unique to the USA.)

**Comment by darylknight** [comment]
Yep, that was it - thanks. English (United Kingdom) is lowercase P. Odd, I always assumed "Plugin Store" was a proper noun, just like Craft CMS

**Comment by brandonkelly** [comment]
Hm yeah it is; so maybe this is a translation bug.
