### ISSUE TITLE
Clearing text field not saved when draft

### ISSUE THREAD

**Issue by mark-adigital** [craftcms/cms#3981]
Hi,

I've noticed an issue where saving an entry as a draft having cleared content from a plain text field results in the previous content repopulating the field. When saving as an entry the field updates correctly and I haven't noticed the problem with other field types either.

I've seen this in Craft 3.1.15 and 3.1.17.1, but other versions may also be affected.

Thanks,

Mark

**Comment by brandonkelly** [comment]
Are you able to reproduce this consistently? If so can you please send a database backup, and your `composer.json` and `composer.lock` files over to support@craftcms.com?

**Comment by mark-adigital** [comment]
Yes, I am seeing the issue consistently. However, I've done some more testing and found that if I populate and clear the field after saving as a draft it works as expected, so the issue only seems to occur where the entry field had data.

Thanks - will send those files over now.
