### ISSUE TITLE
Random order of sites in site switcher widget

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#3982]
I have website with multiple sites, in various languages.

Each time i refresh control panel, order of these sites in site switching widget changes at random.
Is it normal or maybe my site is broken in some way?

**My site info:**
Application Info
PHP version	7.3.2
OS version	Linux 4.4.0-87-generic
Database driver & version	MySQL 5.7.25
Image driver & version	Imagick 3.4.3 (ImageMagick 6.8.9-9)
Craft edition & version	Craft Pro 3.1.12
Yii version	2.0.15.1
Twig version	2.6.2
Guzzle version	6.3.3
Imagine version	0.7-dev
Plugins
Entry Instructions	1.0.4
Imager	v2.1.4
MobileDetect	1.0.2
Navigation	1.1.3
Redactor	2.3.1
Retour	3.1.6
SEOmatic	3.1.44
Translations	1.2.0

**Comment by janhenckens** [comment]
@piotrpog When you say "Site switching widget" are you talking about the dropdown with sites above an entry detail or entry listing, or about an actual widget/plugin?

**Comment by piotrpog** [comment]
@janhenckens 
I mean dropdown with sites. Both in entry list and entry details page.

**Comment by naboo** [comment]
+1 for always keeping Sites in all situations ordered by name by default.

For example right now I have this sort order in my site switcher on the entries page:

Group A
- Site A (sv)
- Site B (en)
Group B
**- Site A (en)
- Site B (sv)**
Group C
- Site A (sv)
- Site B (en)

**Comment by brandonkelly** [comment]
Site groups should be ordered alphabetically, and the sites within them should be ordered based on their specified order from Settings → Sites → <Site Group Name>.

If that’s not happening for you, please send in a support ticket from your Dashboard. Reference this GitHub issue, and point us to an example Control Panel page where you are seeing this behavior.

**Comment by naboo** [comment]
@brandonkelly I couldn't find _based on their specified order_ until I clicked a site group itself. I had no idea you ordered them within the actual group. This solved the issue for me. Thank you.
