### ISSUE TITLE
Twig 2.7.0 breaks TokenParserInterface()

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#3983]
### Description
The latest version of Twig (2.7.0) deprecated the `Twig_TokenParser` that Craft uses in [CacheTokenParser](https://github.com/craftcms/cms/blob/f607d7314a8f7b6050859c3e7c362a86bcbe7709/src/web/twig/tokenparsers/CacheTokenParser.php#L18), which is causing the site & CP to crash with this error:

`Declaration of craft\web\twig\tokenparsers\CacheTokenParser::parse(Twig_Token $token) must be compatible with Twig\TokenParser\TokenParserInterface::parse(Twig\Token $token) `

### Steps to reproduce

1. Install twig/twig 2.7.0
2. Navigate to the CP

### Additional info

- Craft version: 3.1.17.1
- PHP version: 7.2.10
- Database driver & version: 5.7

**Comment by okolvik-avento** [comment]
`Declaration of craft\web\twig\tokenparsers\CacheTokenParser::parse(Twig_Token $token) must be compatible with Twig\TokenParser\TokenParserInterface::parse(Twig\Token $token)
`
Is the error here.

**Comment by aelvan** [comment]
Can confirm that Twig 2.7 that dropped today kills Craft. A temporary workaround is adding a requirement for 2.6.2 to your projects composer.json and running `composer update` again.

```
"twig/twig": "2.6.2"
```

**Comment by janhenckens** [comment]
See this issue on the twigphp/twig repo as well https://github.com/twigphp/Twig/issues/2886

**Comment by eheiser** [comment]
Can confirm this also happens on new Craft installs. Ran into this just now when doing a composer install on a local machine.

**Comment by boboldehampsink** [comment]
We need 2.7.0 as 2.6.2 is not secure anymore! See https://symfony.com/blog/twig-sandbox-information-disclosure

**Comment by iparr** [comment]
I've tried to force 2.6.2 but…

```
Problem 1
    - twig/twig v2.6.2 conflicts with roave/security-advisories[dev-master].
    - roave/security-advisories dev-master conflicts with twig/twig[v2.6.2].
    - twig/twig v2.6.2 conflicts with roave/security-advisories[dev-master].
    - Installation request for twig/twig 2.6.2 -> satisfiable by twig/twig[v2.6.2].
    - Installation request for roave/security-advisories dev-master -> satisfiable by roave/security-advisories[dev-master].
```

Any suggestions? This has not been a happy update!

**Comment by khalwat** [comment]
Craft version 3.1.17.2 released -> https://github.com/craftcms/cms/blob/develop/CHANGELOG-v3.md#31172---2019-03-12

* Craft now requires Twig `~2.6.2`

**Comment by boboldehampsink** [comment]
That is not a fix! Every sane person that uses a security vulnerability step in CI will still fail on this as 2.6.2 has a vulnerability. cc @iparr 

See https://symfony.com/blog/twig-sandbox-information-disclosure

**Comment by angrybrad** [comment]
@boboldehampsink 3.1.17.2 and 3.0.40.1 are just stop-gaps so people's sites will stop breaking. Working on updating our custom Twig stuff for the breaking changes and will cut more releases with Twig 2.7 "real soon now".  Going to go ahead and close this in the meantime.

**Comment by domstubbs** [comment]
FWIW I’ve just tried the just-release [Twig 2.7.1](
https://github.com/twigphp/Twig/issues/2886#issuecomment-47205785) with Craft 3.1.17.1 and I only had to change one line in Environment.php (`\Twig_Source` to `\Twig\Source`) to get Craft working again. It looks as though the larger number of breaking changes in the initial release were unintentional.

**Comment by brandonkelly** [comment]
Twig ^2.7.2 is in place for the next release (2b06c7d6e108d68cbc62e326895f38703da0b188).
