### ISSUE TITLE
Use "_404.twig" file as default 404 error page

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#3984]
Right now, `404.twig` (or `404.html`) file is used as template for 404 error page by default.

Because of that, user can display `404.twig` file directly, not only trough requesting some non existing url but just by using template file routing.  And 404 file doesn't return 404 http status error when displayed trough template routing.

This can be fixed by setting `errorTemplatePrefix` to `_`, so now template used for 404 error is `_404.twig` and underscore blocks 404 file from being directly accessed. But i think Craft should use filename with underscore by default for 404 page.

**Comment by brandonkelly** [comment]
I disagree; it’s nice to be able to preview different error code templates by accessing them directly, e.g. `/404`, `500`, etc.. And as you said, if you don’t like that behavior it’s as simple as setting that `errorTemplatePrefix`.

**Comment by piotrpog** [comment]
@brandonkelly 
In that case, there could be exception in template routing.
If template filename starts with underscore, but rest of filename matches pattern of status code (404, 403 etc.) - template **would be avaible** trough template routing - only if devmode is active.
