### ISSUE TITLE
Craft 3: Environment variable not displayed in admin/CP

### ISSUE THREAD

**Issue by skramstad** [craftcms/cms#3993]
### Description
Environment variable in my .env is not displayed in admin/CP. I can see all my variables in the PHP Info page in CP tho (/utilities/system-report). I can add the variable manually in a field and it will detect it on save, but autocomplete is not working.
Example in .env file:
`SYSTEM_EMAIL="hey@you.me"`

_This is the autocomplete I'm talking about._
https://docs.craftcms.com/v3/assets/img/volume-base-url-setting.98aed098.jpg

### Steps to reproduce

1. Create a .env file
2. Add some variables
3. See if they display in CP autocomplete window

### Additional info

- Craft version: Craft Pro 3.1.17.2
- PHP version: 7.0.33

**Comment by brandonkelly** [comment]
Are _any_ of your environment variables defined by `.env` showing up?

**Comment by skramstad** [comment]
No, they do not.

**Comment by brandonkelly** [comment]
And if you add a new variable to `.env`, it will show up on the PHP Info utility?

**Comment by skramstad** [comment]
Yes.

Under page utilities/php-info and Environment. 
However, the new variable in the .env did show up in the autocomplete window, but none of the other. And yes, the other variables is still present on the utilities/php-info page.

Thats odd.

**Comment by brandonkelly** [comment]
Hm, very odd.

Craft assembles the list of environment variable suggestions by looping through [$_ENV](https://secure.php.net/manual/en/reserved.variables.environment.php).

Try creating  `test.php` file with this:

```php
<?php
print_r($_ENV);
```

Then access it from your browser. Does it output the missing environment variables?

**Comment by skramstad** [comment]
Hmm, no its blank.

`Array
(
)
`

However, the testing variable you asked me to try is still present in CP. Is craft using the php fpm pool config or .env if both is set/available?

**Comment by brandonkelly** [comment]
Doh, forgot you need to load in the `.env` file first :) Just updated that code example. I’m assuming that the file will live one level down from the `vendor/` folder and `.env` file; otherwise you may need to adjust that `$basePath` variable.

**Comment by skramstad** [comment]
Ah. Norries.
Now it found the testing variable. But I cant figure out why my other variables is not loading. They are generated with ansible, but that shouldn't matter. Same .env file and only a line below.

Am I missing something?

`Array
(
    [TESTING_ENV] => something@working.not
)
`

**Comment by brandonkelly** [comment]
Yeah something must be messed up with them. Maybe using nonstandard line endings or something? Try manually re-writing a couple of them and see if they start showing up.

**Comment by skramstad** [comment]
Did some more digging and if I comment out the variables from the pool.d conf file, they are visible in CP. So I have to see if there is any PHP settings that needs to be turned on or something else.

I read about `;clear_env = no` and uncomment this, so gonna try that.

From php doc.
`; Clear environment in FPM workers 
; Prevents arbitrary environment variables from reaching FPM worker processes
; by clearing the environment in workers before env vars specified in this
; pool configuration are added.
; Setting to "no" will make all environment variables available to PHP code
; via getenv(), $_ENV and $_SERVER.
; Default Value: yes
;clear_env = no`

**Comment by skramstad** [comment]
Ok, I found a solution, or a fix I dunno. However, if you change load to `overload` in web/index.php

`(new Dotenv\Dotenv(CRAFT_BASE_PATH))->load();`
to
`(new Dotenv\Dotenv(CRAFT_BASE_PATH))->overload();`

All my variables load in CP.

I read in here https://github.com/vlucas/phpdotenv#immutability but I'm not sure if craft's default index.php should be overload or not.

Do you have any thoughts on this? @brandonkelly

**Comment by brandonkelly** [comment]
Huh, interesting. Well, that `index.php` file is actually part of your project, not a core Craft file, so you are welcome to change it to use `overload()` :)
