### ISSUE TITLE
`myLightswitchField: ':empty:'` matches entries without the field, `myTextField: ':empty:'` does not

### ISSUE THREAD

**Issue by olets** [craftcms/cms#3994]
### Description

I have a situation where I need to retrieve all entries except for those were a certain text field has content. Not all entries have the field.

If it was a lightswitch field I was interested in, I could do

```
craft.entries.myLightswitchField(':empty:')
```

to return all entries that either don't have the field or where the field is present but off.

I expect the same behavior from

```
craft.entries.myTextField(':empty:')
```

but that returns only entries that have the field and it's empty — it doesn't return entries that don't have the field.

Before discovering that it works as expected for lightswitches I thought this was just a limitation of how queries run. But the difference between the lightswitch result and the text field result makes me think it it's either an error or an addable feature.

### Steps to reproduce

1. Create a text field
2. Add it to some entries
3. Try `craft.entries.<your field name>(':empty:')`

### Additional info

- Craft version: 3.0.41
- PHP version: 7.2.10
- Database driver & version: MySQL 5.7.23
- Plugins & versions: (many, can write them up if necessary)

**Comment by brandonkelly** [comment]
Both of those should result in the exact same generated SQL.

You can test by comparing the following outputs:

```twig
<pre>
{{ craft.entries()
    .myLlightswitchField(':empty:')
    .getRawSql() }}

{{ craft.entries()
    .myTextField(':empty:')
    .getRawSql() }}
</pre>
```

The only difference should be the column names used in the conditions. So not sure why they would have different behavior here.

**Comment by ccsantos23** [comment]
@brandonkelly I think #5896 broke my query for ':empty:' on a lightswitch field that is not on every entry.  My query was supposed to return entries that either have the lightswitch=false, or not have the lightswitch field at all.  Is there any other way to write this query?

**Comment by ccsantos23** [comment]
Oh wait I think I figured it out.  Checking for (my lightswitch field is "disableActionLinkToThisEntry"):
```
disableActionLinkToThisEntry: ':empty:' or false
```
generates the desired SQL:
```
WHERE (`elements_sites`.`siteId`='1') AND ((`content`.`field_disableActionLinkToThisEntry`=TRUE) OR (`content`.`field_disableActionLinkToThisEntry` IS NULL)) ...
```

**Comment by brandonkelly** [comment]
@ccsantos23 Hm… you _should_ just be able to go with either `:empty:` or `false`, and not need both. Seems unrelated to this issue though, which I’m going to close due to inactivity. Can you please post a new GH issue explaining your expected behavior and what you’re seeing instead?

**Comment by ccsantos23** [comment]
Ok I added a new issue.  Also realized that the result of `':empty:' or false` was returning a check for NULL or TRUE, instead of NULL or FALSE.  :(
