### ISSUE TITLE
Code snippets don't wrap/scroll in Craft store

### ISSUE THREAD

**Issue by missmatsuko** [craftcms/cms#3998]
### Description
This page is wiiiiideee:
https://plugins.craftcms.com/document-search

### Steps to reproduce

1. Go to https://plugins.craftcms.com/document-search
2. Look at it

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by benjamindavid** [comment]
It should be fixed now. Thank you for the feedback  @missmatsuko!
