### ISSUE TITLE
Swapping a Matrix field to another will leave orphaned schema + data in the database

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#4]
#### Environment:

- Craft version: 3.x
- PHP version: 7.x
- Database driver & version: MySQL - need to verify PostgreSQL behavior
- Plugins & versions:

#### Description:

Create a Matrix field + blocks. Save the field. Change the field type to a Table.  The Matrix table schema still exists in the database.

**Comment by brandonkelly** [comment]
Fixed in 8870c8fb4a9a99214256d3d0f97ccbb0446a04da
