### ISSUE TITLE
CP badge counters use decimals without the `intl` extension installed

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#4002]
### Description

On a site without the `intl` extension installed, badge counters (e.g. Utilities -> available updates) display with decimals (i.e. `1.00` instead of `1`).

The badge counters are localized (i.e. changing the CP's language to `nb` display badge counters as `1,00`).

Installing the `intl` extension fixes the issue.

![image](https://user-images.githubusercontent.com/298510/54422867-ae8bf480-470f-11e9-9389-ce4261dfbe70.png)

### Steps to reproduce

1. Install Craft 3.1.18 on a server without the `intl` extension installed
2.

### Additional info

- Craft version: 3.1.18
- PHP version: 7.2.14
- Database driver & version: MySQL 5.7.24
- Plugins & versions: 

![image](https://user-images.githubusercontent.com/298510/54422941-da0edf00-470f-11e9-99c4-1e5b1e169386.png)

**Comment by brandonkelly** [comment]
Fixed for the next release, thanks for reporting!
