### ISSUE TITLE
Favicon for Craft Dashboard pages

### ISSUE THREAD

**Issue by meyerweb** [craftcms/cms#4003]
It would be nice to be able to define a favicon for Dashboard pages that’s separate from the overall site favicon.  As an example, the regular site icon, but with a red lock embedded.

It could be a General setting, though it could as easily be a predefined location (not at public root level) to drop a customized `favicon.ico`.

**Comment by brandonkelly** [comment]
This will be possible in Craft 3.5 via a new `cpHeadTags` config setting, which lets you define whatever additional `<head>` tags you want for the control panel.

That was about the only way I could think of to add this, considering all the other icon types there are nowadays, between [PNG favicons](https://caniuse.com/#feat=link-icon-png), [SVG favicons](https://caniuse.com/#feat=link-icon-svg), [touch icons](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html), and [Safari pinned tab icons](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html), and others.
