### ISSUE TITLE
Can't edit or override settings fields values that can be configured in an environment variable

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#4004]
### Description

For reasons that I ignore, the Settings fields that can be configured in an environment variable are not displaying.

It is therefore not possible for me to configure the value of these fields, which is quite blocking especially for the configuration of Email Settings blocking the sending of emails.

This problem is faced on my online project, regardless of the environment applied.

The problem persists when, for example, the values of the fields of Email Settings are added to the `config/app.php` file: these values are not read.

I use `project.yaml` config, yet up to date, but who could be causing the problem? As for the allowAdminChanges option, I have disabled it for the moment, just in case.

![](https://i.imgur.com/UqT6MbR.png)

### Steps to reproduce

1. Go to settings, try to edit System Name in General Settings, or System Email Address in Email Settings

### Additional info

- Craft version: Craft Pro 3.1.18
- PHP version: 7.1.26
- Database driver & version: PostgreSQL 9.5.15

**Comment by romainpoirier** [comment]
I finally found that that line in my `.htaccess` file was blocking the script which inject these fields:

> Header set Content-Security-Policy "script-src 'self' maps.googleapis.com apis.google.com *.google-analytics.com 'unsafe-inline'; object-src 'self'"

This is what I found later in the JS console:
```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' maps.googleapis.com apis.google.com *.google-analytics.com *.usersnap.com 'unsafe-inline'".

    at new Function (<anonymous>)
    at Object.createAccessors (fabric.js:1022)
    at fabric.js:13696
    at fabric.js:11770

```
Adding this to the `.htaccess` line solve the problem:
`'unsafe-eval'`

**Comment by brandonkelly** [comment]
Glad you got it sorted!
