### ISSUE TITLE
Date/time in Table Field in Matrix without default throws system-wide exception

### ISSUE THREAD

**Issue by jacotijssen** [craftcms/cms#4005]
### Description
Creating a date/time column within a Table Field within a Matrix Block without a default table row throws an exception. After this, any page in the backend becomes unreachable.

### Steps to reproduce

1. Create a Matrix field
2. Create a Table field within the matrix field
3. Set one of the columns to a Date/Time type
4. Delete the default row
5. Save the field

### Additional info

- Craft version: 3.1.18
- PHP version: 7.2.15
- Database driver & version:  MySQL 5.7.24
- Plugins & versions: _none_

**Comment by brandonkelly** [comment]
Thanks for reporting that. It’s been fixed for tomorrow’s release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#a02c552f61f5ab5dcc193f5603a98caa0b997a85 as 3.1.18",
  "...": "..."
}
```

Then run `composer update`.
