### ISSUE TITLE
Inconsistent auto capitalisation of custom field handle first letter on mobile devices

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#4009]
### Description
**Minor UI enhancement**.
On a mobile device (i.e. iPad), when creating a new field, deleting the auto generated field handle and then keying in a new handle, the first letter is auto capitalised instead of being lowercase (by default) to ensure consistency.

This automatic functionality is a slight annoyance. As a workaround, I typically key in first letter of the new field handle twice and then backspace and delete the first auto capitalised letter which is pretty clunky.

### Steps to reproduce

1. Access the CP on a mobile device (i.e. iPad)
2. Create a new field
3. Delete the auto generated field handle
4. Key in the new field handle - the first letter of the handle is auto capitalised and should be overridden to be lowercase as the default

**Comment by richhayler** [comment]
Same issue for “entry slugs” and “section handles”

**Comment by brandonkelly** [comment]
Should be fixed in the next release!
