### ISSUE TITLE
Hyphens no longer removed from default asset titles

### ISSUE THREAD

**Issue by elivz** [craftcms/cms#4011]
It used to be (unless I'm going crazy) that the default title for an uploaded asset would have any hyphens changed to spaces. So the file "this-is-a-photo.jpeg" would be given the default title "This is a photo". Recently, that seems to have been changed, so now you would end up with "This-is-a-photo".....significantly less nice, imho.

I believe that change was introduced in [this commit](https://github.com/craftcms/cms/commit/3cc998fc12e7249c3e245997eef41a822543421e#diff-2fb164d33ece14215111da636d12af74). Seems like it might be as simple as just changing [line 181 in the filename2String() function](https://github.com/craftcms/cms/blob/ab459d8bf4d944ab45e09be8bd9fc1de224c2aef/src/helpers/Assets.php#L181) to:

````php
return StringHelper::upperCaseFirst(implode(' ', StringHelper::toWords($filename, false, true)));
````

Or maybe this was an intentional change, but it leads to a lot of junk-looking image titles in e.g. Google Image Search results.

**Comment by brandonkelly** [comment]
Yeah this seems like an oversight. Made the change you recommended.
