### ISSUE TITLE
Syncing project.yaml fails when you change a field from matrix to something else

### ISSUE THREAD

**Issue by N0ps32** [craftcms/cms#4015]
### Description
We had a field that was originally a Matrix field and changed it to type craft\fields\RadioButtons. Changing it locally worked but when you then sync the project.yaml against an environment that still has the matrix field in it it breaks.

This line: https://github.com/craftcms/cms/blob/develop/src/services/Matrix.php#L341
causes the problem because it assumes the field it fetches is a Matrix field (in our case a RadioButton was returned).

"Applying changes from project.yaml ... error: Getting unknown property: craft\fields\RadioButtons::contentTable"

Another problem is that there is **no Stacktrace** when something goes wrong because this piece of code just throw the exception information away: https://github.com/craftcms/cms/blob/develop/src/console/controllers/ProjectConfigController.php#L65

Why? Could you at least log the exception stacktrace please? I had to go in the code and manually get the trace.

### Additional info

- Craft version: Craft Pro 3.1.17.1
- PHP version: 7.2.13
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
Advanced Url Field | 1.0.0
Migration Manager | 3.0.19
Neo | 2.2.5
Redactor | 2.3.2

**Comment by andris-sevcenko** [comment]
Sorry for the oversight on the exception stack trace. Logging it as expected when encountering errors now.

As far as the original issue - we're discussing internally on the resolution for this, as it can go two ways:
a) changing a Matrix field to something else deletes all the block types, subfields, and content
or
b) handling block type changes should account for the possibility that the parent matrix field does not exist anymore.

Once we decide (probably today), I'll fix the rest of this issue.

**Comment by N0ps32** [comment]
I think it would be a good idea to have it behave the same way it does when you change the fields in the CMS by hand.

**Comment by andris-sevcenko** [comment]
> I think it would be a good idea to have it behave the same way it does when you change the fields in the CMS by hand.

Right, the thing is that currently hanging a Matrix field to something else leaves the block types still existing in the database and the project config. So if you make changes to a block type, then change the matrix field to something else and push that project.yaml file, Project Config would react to block type changes and fail to find the matrix field.

We're trying to figure out if this is the "correct" behavior and we should make that part of the code more defensive to be OK with the parent field missing or if this in itself is a bug that the block types and everything else is not deleted when the field type changes.

**Comment by benface** [comment]
@andris-sevcenko Think I just ran into this... I converted a Matrix field into a Table field and I'm seeing this error:

```
Getting unknown property: craft\fields\Table::contentTable
```
