### ISSUE TITLE
Error when updating Craft CMS to version 3.1.18

### ISSUE THREAD

**Issue by Djive** [craftcms/cms#4016]
Tried updating plugins in admin/utilities/updates but dukt/social had some errors regarding league/oauth2-google dependencies.
So we decided to update everything via SSH.
We uploaded new Craft 3.1.18 vendor folder, SSH onto our server and tried running `./craft update/composer-install` then got this error:

`Performing Composer install ... error: The "https://codeload.github.com/protocolbuffers/protobuf-php/legacy.zip/66dc42d891a4fc8e9190c524fd67961688a37bbe" file could not be downloaded (HTTP/1.1 404 Not Found)`

Attached is the screenshot of the process and error.
Tried searching the web regarding the error but didn't find anything.
How can we fix this?

Thanks

![craft-update-3-1-18](https://user-images.githubusercontent.com/1241189/54678540-a4019e80-4b05-11e9-9dfc-7f947a598202.jpg)

**Comment by brandonkelly** [comment]
Hm, my guess is that your `composer.lock` file is referencing a commit hash that no longer exists. What happens if you run `composer update`?

**Comment by Djive** [comment]
`composer update` was successful.

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 21 updates, 36 removals
...
 - Updating google/protobuf (v3.6.1.3 => v3.7.0): Downloading (100%)
...
Package dukt/oauth2-google is abandoned, you should avoid using it. Use league/o                                                                                                                                                             auth2-google instead.
Writing lock file
Generating optimized autoload files
```

But now we have `Internal Server Error` in the Admin.
This is error from the phperrors.log

`[20-Mar-2019 13:10:15 Europe/Zagreb] PHP Warning:  Declaration of craft\web\twig\Environment::compileSource(Twig_Source $source) should be compatible with Twig\Environment::compileSource(Twig\Source $source) in /home/site/vendor/craftcms/cms/src/web/twig/Environment.php on line 87`

**Comment by brandonkelly** [comment]
@Djive Sounds like you’re still running Craft 3.1.17.1 or earlier. Open your `composer.json` and change your `craftcms/cms` requirement to `3.1.19`, and then run `composer update` again.

**Comment by Djive** [comment]
This worked!
Many thanks!
