### ISSUE TITLE
URL field type has character count cap of 255

### ISSUE THREAD

**Issue by Harry-Harrison** [craftcms/cms#4019]
### Description
The native URL field type has a character limit which isn't shown on the field or documented anywhere, but is also arbitrary. I'd like to see these removed or at least be configurable. If made configurable, it should be added to the field like the plain text implementation.

### Steps to reproduce

1. Create a URL field
2. Add it to a section
3. Create an entry in that section
4. Try and paste pretty much any URL from Facebook these days in there or this crazy but valid URL that is 256 characters `https://facebook.com?000000100000000010000000001000000000100000000010000000001000000000100000000010000000001000000000100000000010000000001000000000100000000010000000001000000000100000000010000000001000000000100000000010000000001000000000100000000010000=256`

### Additional info

- Craft version: 3.1.18
- PHP version: 7.2.14
- Database driver & version: PostgreSQL 11.2
- Plugins & versions: None

**Comment by brandonkelly** [comment]
Next release of Craft gives URL fields a new “Max Length” setting, so you can change it to whatever you want.
