### ISSUE TITLE
FR: terminal command to send test emails

### ISSUE THREAD

**Issue by billythekid** [craftcms/cms#4020]
It would be nice to have a terminal command to send test emails for the instances where we're overriding email settings in app.php with different configurations for environments etc.

At the moment to send a test email from the dashboard you need to fill in settings and it uses those, even if they're being overridden. 

A command in terminal could solve this, something like;

`./craft email/test [user@example.com] [environment]`

**Comment by gtettelaar** [comment]
@billythekid Just finished an idea for this over at #4407 but not entirely sure about one thing. 

What specifically did you mean by testing for specific environments? Do you mean in the console command you want to select `staging`, `dev`, `production` e.t.c and an email will be sent using the config settings as defined by that environment in `app.php` or just enter custom transport adapter options to use for testing your email settings and their integration with Craft? Thanks!

**Comment by billythekid** [comment]
@gtettelaar Yeah, I set dev and staging environments to use specific mailer components (usually mailtrap) and just set them in app.php…

```
/* app.php */
return [
    '*'          => [
        'modules' => [
            'my-module' => \modules\Module::class,
        ],
      //'bootstrap' => ['my-module'],
    ],

  // Dev environment settings
    'dev'        => [
        'components' => [
            'mailer' => function () {
              $settings                    = \craft\helpers\App::mailSettings();
              $settings->transportType     = \craft\mail\transportadapters\Smtp::class;
              $settings->transportSettings = [
                  'useAuthentication' => true,
                  'host'              => getenv('SMTP_HOST'),
                  'port'              => getenv('SMTP_PORT'),
                  'username'          => getenv('SMTP_USERNAME'),
                  'password'          => getenv('SMTP_PASSWORD'),
              ];
              $config                      = \craft\helpers\App::mailerConfig($settings);

              return Craft::createObject($config);
            },
        ],
    ],

  // Staging environment settings
    'staging'    => [
        'components' => [
            'mailer' => function () {
              $settings                    = \craft\helpers\App::mailSettings();
              $settings->transportType     = \craft\mail\transportadapters\Smtp::class;
              $settings->transportSettings = [
                  'useAuthentication' => true,
                  'host'              => getenv('SMTP_HOST'),
                  'port'              => getenv('SMTP_PORT'),
                  'username'          => getenv('SMTP_USERNAME'),
                  'password'          => getenv('SMTP_PASSWORD'),
              ];
              $config                      = \craft\helpers\App::mailerConfig($settings);

              return Craft::createObject($config);
            },
        ],
    ],

  // Production environment settings
    'production' => [
    ],
];
```

You'll see I don't bother with production mailer component because, depending on the site/client it could be any of local/smtp/mailgun/postmark/mandrill/whatever so for production I actually set it up in the normal dashboard way.

I'd either like the console command to just know, or have passed to it as a parameter, what environment it's in and use those settings, regardless of what's filled in in email settings on the site.

Does this help clarify it?

**Comment by gtettelaar** [comment]
@billythekid That makes sense. It will be a selection you can make (I.E. Which env you want to use). I'll implement that over the weekend in the PR I mentioned above. Thanks for your help!

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/cms/pull/4407
