### ISSUE TITLE
Multi site routes not working when the same pattern is used

### ISSUE THREAD

**Issue by mark-chief** [craftcms/cms#4021]
### Description
Same route patterns on different sites not working. 

Only the primary site loads the template, the other site will display Page not found / Template not found

1. Create 2 sites Site1 (primary) and Site2.
2. Create identical routes for both sites but change the template path
3. Go to url pattern in browser on Site 2 and get "Page Not Found Template not found: _events

<img width="423" alt="Screen Shot 2019-03-20 at 16 28 01" src="https://user-images.githubusercontent.com/18699249/54701461-f904db00-4b2c-11e9-842f-035b655d2196.png">

Although I am loading Site2 in the browser, the screenshot suggests that craft is looking for the Site1 route template.

<img width="715" alt="Screen Shot 2019-03-20 at 16 29 35" src="https://user-images.githubusercontent.com/18699249/54701590-379a9580-4b2d-11e9-95b1-5c451d3516b1.png">

### Additional info

- Craft version: 3.1.18
- PHP version: 7.1

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#d770f57016b0923acc4aa66d6f80f11edb636bf9 as 3.1.19",
  "...": "..."
}
```

Then run `composer update`.

**Comment by mark-chief** [comment]
Thanks for the update. 

Also experiencing a similar issue when using a search form.

 Not sure if linked or not but in the second site I get a template not found error, it is looking for the `search/results` template even though the form is set to `site2/search/results`.

**Comment by brandonkelly** [comment]
@mark-chief Sounds unrelated. Can you post more details on a new issue?
