### ISSUE TITLE
Phantom email send errors after enabling Project Config

### ISSUE THREAD

**Issue by swthate** [craftcms/cms#4023]
### Description
A user in production mentioned they were able to save a new user but the activation email could not be sent. I thought this was odd, as nothing about the email settings have changed for a long time, and I just recently made a new user with no issues. Then I realized I recently enabled Project Config. I think `project.yaml`'s handling of the password was causing the issue.

Also, I say "phantom" because when searching my logs for `[exception.Craft\EmailTestException]` returned nothing. Or is that page outdated and should I be searching for something else in Craft 3?

### Steps to reproduce

1. Fill out email settings using SMTP with SSL and literal password string.
2. Given a successful test, enable Project Config
3. Come back to email settings, password value will be a base64 encoded string.
4. Test email settings again, should get "An error occured..."
5. But in `storage/runtime/debug/mail/` there will be an `eml` file showing the test message with a success message. I'm not sure if this means it was successful, but found this intriguing.
6. Change password back to literal password string and test: success flash message.
7. Let `project.yaml` update, revisit email settings, test will fail.

### Additional info

After going through those steps I tried changing my email settings to ENV variables and now have consistent success both in development and production environments. This leads me to believe `project.yaml` was mishandling something along the way, but I'm not sure.

- Craft version: 3.1.18
- PHP version: 7.2.8
- Database driver & version: MySQL 5.7.23
- Plugins & versions:
  - Asset Rev 6.0.2
  - CKEditor 1.0.0-beta.2
  - CraftQL 2.x-dev
  - Inlin 2.1.1
  - Redactor 2.3.2
  - Smart Map 3.2.2
  - Sprout Fields 3.2.8

**Comment by brandonkelly** [comment]
> Also, I say "phantom" because when searching my logs for `[exception.Craft\EmailTestException]` returned nothing. Or is that page outdated and should I be searching for something else in Craft 3?

In Craft 3 email exceptions get logged as `warning`s, and the log message will begin with `Error sending email: `.

> After going through those steps I tried changing my email settings to ENV variables and now have consistent success both in development and production environments. This leads me to believe `project.yaml` was mishandling something along the way, but I'm not sure.

Nothing should have changed here, unless you had made any changes to your email settings before deploying the updated `project.yaml` file to production. For example if you swapped the Password field to use an environment variable locally, you would have needed to set that same environment variable on production as well, otherwise Craft will just be stuck with setting the password to `$YOUR_PASSWORD_ENV_VAR_NAME`.
