### ISSUE TITLE
Project config not syncing all the data

### ISSUE THREAD

**Issue by jan-dh** [craftcms/cms#4028]
### Description
The project-config is not picking up all the changes such as sections, fields, fields linked to section.

My setup: I have a local database where I set up all my fields, channels, structures, ..
After deploy to the server with a database on the server, only some fields, sections, ... are synced. At the moment I'm "forcing" sycs by adding extra text to fields and changing the field order in my sections, so changes get picked up.

### Additional info

- Craft version: 3.1.18
- PHP version: 7.2.16
- Database driver & version:  MySQL 5.6.34

**Comment by andris-sevcenko** [comment]
Can you reproduce this issue (without forcing anything afterward) and send over your project.yaml and zipped up contents of your storage/config-backups folder to support@craftcms.com?

**Comment by jan-dh** [comment]
Mailed you all the files.

**Comment by andris-sevcenko** [comment]
Fixed by deleting the project.yaml file on the target server and making a request to the page, forcing the server to regenerate the project.yaml file.

Doing this eliminated the inconsistency between the internal serialized system configuration and the project.yaml file.

If this happens again, let us know.

**Comment by jan-dh** [comment]
Issue still persists, even after deleting the project.yaml file

**Comment by davist11** [comment]
I'm having the same problem as well where not all changes are syncing

**Comment by andris-sevcenko** [comment]
@davist11 Can you get in touch over support@craftcms.com? Ideally, this is on a public site and can be reproduced consistently.

**Comment by jurriaanr** [comment]
I have the problem also consistently, unfortunately I am still in development. But I believe one of the problems is that if an error occurs during the syncing process the craft_info table will still be updated as if everything went well. And the changes will never again trigger. I have fields that are clearly in the project.yml that are not in the database. And I am really looking for a way to force the project.yml file into the database, for example by using "insert ignore" style queries, or for a true check on the project.yml file to check if there are missing fields/sections etc.

**Comment by andris-sevcenko** [comment]
@jurriaanr based on my research for this bug, I'm going to tentatively partially agree.  The current workaround solution would be to run `touch config/project.yaml` file to update it's date modified value on the filesystem.

**Comment by andris-sevcenko** [comment]
I've just pushed a fix that partially addresses this by always assuming that the `project.yaml` file has been changed when running the `./craft project-config/sync` command.

I will keep this open until I've investigated/fixed other side-effects and or contributing bugs.

@jurriaanr if you could let me know if this fix helps you, it would be very helpful. To pull in the latest changes just set your `craftcms/cms` requirement to `dev-develop#1b861d72500b8795eb5323c0bbb693ad6afbd57d as 3.1.21.1` in your `composer.json`  file and run `composer update`.

**Comment by jurriaanr** [comment]
Unfortunately no. I have tried it on a server that was running behind quite a bit with the actual project file, but multiple things were not synced. I am now thinking this goes wrong in a different way. The fieldlayout attached to my entrytype cannot be found in the database, and thus the fields attached to it cannot be added. I attached some screenshots of this.

![project yml](https://user-images.githubusercontent.com/7426848/55867016-e7d64980-5b81-11e9-9d5f-cd6fb7f8e3bd.png)
![fieldlayoutnotfound](https://user-images.githubusercontent.com/7426848/55867022-ea38a380-5b81-11e9-906f-aa4534cdefd5.png)

I will send a dump of the database and the project.yml file to support@craftcms.com as well

**Comment by andris-sevcenko** [comment]
This was fixed over by introducing the `--force` option to the `project-config/sync` console command. a long time ago.

**Comment by texasbaptists** [comment]
Is `--force` in the documentation anywhere? What's it doing that the normal process is not?

**Comment by brandonkelly** [comment]
Normally only values in `project.yaml` that appear to have changed will be processed.  With `--force`, all values are treated as added/updated.

**Comment by mizziness** [comment]
> Is `--force` in the documentation anywhere? What's it doing that the normal process is not?

I was also not able to find this in the docs and keep running into issues with changes not being synced properly.  I had no idea that there was a --force option :( 

Is there help needed with updating docs?

**Comment by mattstein** [comment]
Finally noted `--force` behavior here: https://docs.craftcms.com/v3/project-config.html#config-data-could-get-out-of-sync

Thanks for the nudge, @mizziness!
