### ISSUE TITLE
Can `beforeSaveDraft` be cancelable?

### ISSUE THREAD

**Issue by engram-design** [craftcms/cms#4032]
Refer to https://github.com/verbb/workflow/issues/59 which hooks into `EntryRevisions::EVENT_BEFORE_SAVE_DRAFT`. It seems that the `DraftEvent` event isn't cancellable like the equivalent of before save of an entry (`ElementEvent`). In that instance, you set `isValid` to be false, after which is stops and doesn't proceed to saving.

This is clearly because https://github.com/craftcms/cms/blob/develop/src/services/EntryRevisions.php#L206-L211 doesn't really care about the result. It does check the entry's validation, but that's not going to work for our case with Workflow.

I know there's validation (or lack thereof) tied to drafts for a particular reason, but wondering if this might be something to update?

**Comment by brandonkelly** [comment]
In general `before` events on services aren’t cancellable anymore, especially if there is a validation step that follows them, as is the case here, as well as `beforeSaveElement`, etc.:

https://github.com/craftcms/cms/blob/fa7c15fb50ad7b3badf49c89cb373e47b44690ad/src/services/Elements.php#L395-L401

Would tying into validation work for you?

```php
use craft\models\EntryDraft;
use yii\base\Event;
use yii\base\ModelEvent;

Event::on(EntryDraft::class, EntryDraft::EVENT_AFTER_VALIDATE, function(ModelEvent $e) {
    /** @var EntryDraft $draft */
    $draft = $e->sender;

    $validates = // ...

    if (!$validates) {
        $draft->addError('attribute', 'Error message');
    }
});
```

Or if you don’t want to add an error on the draft, use `EVENT_BEFORE_VALIDATE` and set `$e->isValid = false` instead, which will prevent normal validation from occurring, so basically the same as cancelling the `beforeSaveDraft` event.

```php
use craft\models\EntryDraft;
use yii\base\Event;
use yii\base\ModelEvent;

Event::on(EntryDraft::class, EntryDraft::EVENT_BEFORE_VALIDATE, function(ModelEvent $e) {
    /** @var EntryDraft $draft */
    $draft = $e->sender;

    $validates = // ...

    if (!$validates) {
        $e->isValid = false;
    }
});
```

**Comment by engram-design** [comment]
Thanks for the feedback @brandonkelly one of these will certainly do.
