### ISSUE TITLE
Fields are duplicating on render if you use ->getIdentity() inside a module

### ISSUE THREAD

**Issue by leecrosdale** [craftcms/cms#4035]
### Description

There is a strange issue where using `Craft::$app->getUser()->getIdentity();` inside a module (or possibly other places) it causes fields in craft to duplicate on render. It doesn't change anything in the database.

Bit of a strange one, it's easily fixed by adding a `false` parameter, But it took me a bit of time to realise!

### Steps to reproduce

1. Add a module with this code 
~~~
<?php
namespace modules;

use Craft;
use yii\base\Module;

class DoubleFields extends Module
{

    public function init()
    {
        parent::init();
        Craft::$app->getUser()->getIdentity(false);
    }

}
~~~
2. Add it to your app.php in your config.
3. Goto Settings -> Fields (And you will see everything is fine)
4. Change `getIdentity(false)` to `getIdentity()`
5. Refresh your fields, see that there are now duplicated fields.

### Additional info

- Craft version: 3.0.38
- PHP version: 7.1.26
- Database driver & version: MySQL
- Plugins & versions:

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you try updating to the latest release and let me know if that fixes it for you? If not, please send your `composer.json`, `composer.lock`, and module files, plus a database backup over to support@craftcms.com

**Comment by leecrosdale** [comment]
On a fresh install, I couldn't replicate either. It turned out to be an issue with the 'Spoon' plugin. Will follow up with them!
