### ISSUE TITLE
Feature Request: Queue permissions

### ISSUE THREAD

**Issue by tim-pixeldeluxe** [craftcms/cms#4040]
I would like to have a few extra permissions for queue related actions. Having permissions to control who can view, retry and release queue jobs would be great. I use jobs for importing/exporting data and our customers should not be able to manage those jobs.

Thanks in advance!

**Comment by brandonkelly** [comment]
Alternatively, it might make sense to limit queue actions to admin users only.

**Comment by brandonkelly** [comment]
Job details and management have been moved to a new Queue Manager utility for Craft 3.4, so you can now decide which users should be able to access that via the utility’s permission.

![The Queue Manager utility in Craft 3.4](https://user-images.githubusercontent.com/47792/71934751-f629b400-3159-11ea-80e3-9876d7e13465.png)
