### ISSUE TITLE
Impossible to invoke a method ("format") on a string variable ("23-03-2019").

### ISSUE THREAD

**Issue by MarcelWeidum** [craftcms/cms#4041]
### Description
Make a form with an 'editableTableField' and a type date and try to load a date.

### Steps to reproduce

1. Make a form with an 'editableTableField' 
2. And a type 'date' and try to load a date

### Additional info

- Craft version: 3.1.19
- PHP version: 7.2.15
- Database driver & version: MySQL 5.5.5
- Plugins & versions: -

**Comment by brandonkelly** [comment]
Editable table inputs and Date inputs were expecting a DateTime object, but they will start defending against a raw timestamp string being passed in as of the next release.
