### ISSUE TITLE
For \craft\mail\Message setTo($to) doesn't work if $to is User[]

### ISSUE THREAD

**Issue by bighoho123** [craftcms/cms#4048]
### Description
When calling `setTo($to)`, if $to is of User[], it will throw "Array to string conversion" error

### Steps to reproduce

```php
$message = new \craft\mail\Message();
$to = User::findAll();
$message->setTo($to);
$message->setSubject("Test");
$message->setHtmlBody("Hello World");
```

### Additional info

- Craft version: Craft Pro 3.0.26.1
- PHP version: 7.2.5
- Database driver & version:
- Plugins & versions:

I think the reason being the Swiftmailer will expect $to to be `['email1@email.com'=>'Person 1', 'email2@email.com'=>'Person 2']` instead of `[['email1@email.com'=>'Person 1'],[ 'email2@email.com'=>'Person 2']]`

**Comment by brandonkelly** [comment]
Thanks for pointing that out, it’s been fixed for the next release.
