### ISSUE TITLE
Fields: Feature Request - Option to Prefix or Postfix Text to a Number Field

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#4055]
### Description
While entry instructions or placeholder text are great at directing entry authors for field input, it would be nice to have an option to add text before or immediately after a number field.

For example adding "$" before the number field or "%" or "cm" after a number field so this is displayed on the entry edit page to the author to guide their input.

_Placeholder text is only shown to the entry author before they enter a value. In the scenario when a different author needs to update an entry, this placeholder text may not be displayed. So displaying prefix or postfix text can make it much clearer in this scenario._

A super nice addition would then be to display the pre or postfix text along with the number value in the entries listing (for that section) if the field is selected when defining the table columns.

This feature also negates the need for custom fields for these specific data type instances.

**Comment by brandonkelly** [comment]
Easy enough! Added for the next release.
