### ISSUE TITLE
Widgets: Enhancement - CraftCMS “Get Help” Widget

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#4058]
### Description
On the CraftCMS get help widget within the control panel it would be great if this displayed links to other resources that could offer help - e.g. Craft Community (Discord, Stack Exchange, Twitter), GitHub, CraftCMS website, Craft Docs, Craft Guides, etc.

Sure much of this info can be discovered through the CraftCMS website but in this case it surfaces this info in the context when it may be needed most.

**Comment by brandonkelly** [comment]
Good idea! Here’s what I came up with, for the next release:

<img width="342" alt="Screen Shot 2019-03-27 at 7 30 51 AM" src="https://user-images.githubusercontent.com/47792/55084600-99de2380-5062-11e9-9318-847af8d01b31.png">

Link to Craft Partners takes care of https://github.com/craftcms/cms/issues/4057#issuecomment-477110988.

**Comment by richhayler** [comment]
Yup, that looks awesome.
