### ISSUE TITLE
Fields: UI Enhancement - Number Field Thousandth’s Separator

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#4059]
### Description
It is common to use a comma every three decimal places in numbers of four or more digits counting right to left.

Could this convention be applied to the number field so it automatically inserts the comma and also renders the number in this format in the entries listing section if the field has been selected as a table column to be displayed.

The benefit of this (apart from it following the common convention) would be to make larger numbers more readable within the control panel interface.

I can’t think of any instances where inserting the comma in the number field would be an issue for display within the control panel. However if inserted in a template via twig code I would expect the number to be rendered without the comma applied?

**Comment by brandonkelly** [comment]
Number fields will start formatting their values for element index tables in the next release.

It’s up to you whether they should be formatted or not on the front-end. The raw field value is just going to be the number, without any formatting, but you can run it through the [number](https://docs.craftcms.com/v3/dev/filters.html#number) filter to format it with the correct thousands separator and decimal point characters, per the current locale. (I’ve just updated the [Number field docs](https://docs.craftcms.com/v3/number-fields.html#working-with-number-field-data) to show an example of that.)

**Comment by richhayler** [comment]
I totally understand about number fields being formatted appropriately on the front-end by the developer (e.g. using the currency filter). This request asked consideration to apply the thousandths separator as a pure UI embellishment within the control panel for readability purposes. As there is an option to specify decimal points for number fields (and a decimal point then being displayed) would it make sense to offer a thousandths separator?

**Comment by richhayler** [comment]
I totally understand about number fields being formatted appropriately on the front-end by the developer (e.g. using the currency filter). This request asked consideration to apply the thousandths separator as a pure UI embellishment within the control panel for readability purposes. As there is an option to specify decimal points for number fields (and a decimal point then being displayed) would it make sense to offer a thousandths separator option?

**Comment by brandonkelly** [comment]
Where exactly in the CP are you referring to? As said in my previous comment, Number field values are now getting formatted properly within element index tables.

**Comment by richhayler** [comment]
Insert foot in mouth... I don’t know how I missed this - I’m so sorry. Thank you for making that change. This makes a great difference to looking at some financial data I’m managing in craft. Thank you
