### ISSUE TITLE
Feature Request: Ability to show live entries as default

### ISSUE THREAD

**Issue by philipboomy** [craftcms/cms#4060]
Ability to set something in config file to show live entries as default all the time. Even if navigating away from the index page or coming back after logout.

Robin was kind enough to provide me with this

```php
Craft::$app->getView()->registerJs('
    Craft.OriginalEntryIndex = Craft.EntryIndex;
    Craft.EntryIndex = Craft.OriginalEntryIndex.extend({
        afterInit: function(){
            this.$statusMenuBtn.data("menubtn").menu.$options[1].click();
            this.base.apply(this, arguments);
        }
    });

    delete(Craft._elementIndexClasses["craft\\\elements\\\Entry"]);
    Craft.registerElementIndexClass("craft\\\elements\\\Entry", Craft.EntryIndex);
', 3);
```

but it register the script frontend as well causing issues as "Craft" does not exist frontend.

Thanks

**Comment by brandonkelly** [comment]
I have a feeling that would cause more confusion than it would help, as people will stop seeing in-progress entries and not think to change the status.

Robin’s suggestion is a good one. If you wrap it with the following condition, you will fix the front-end JS error:

```php
if (Craft::$app->request->isCpRequest) {
    // ...
}
```
