### ISSUE TITLE
Craft CMS 3 and Clockwork

### ISSUE THREAD

**Issue by thegregthomp** [craftcms/cms#4065]
### Description
I've attempted twice to integrate clockwork (https://underground.works/clockwork/installation/vanilla?#content) vanilla version into craft for use in plugin development. I've used clockwork before with Laravel and it's an excellent tool that makes debugging/testing/dev a lot less painful. I've installed with composer, added it to autoloader etc. I think my issue is around the routing and I just can't get it to work. I'm not exactly sure why it doesn't work but I'm wondering if anyone here uses it/has gotten it to work before.

### Additional info

- Craft version: 3.0.41
- PHP version: ~7

**Comment by narration-sd** [comment]
@thegregthomp  Greg, that's an intriguing dev part I wan't aware of.  

I wonder, though,  if you've yet discovered the Yii Debug Toolbar which is already built into Craft, is easy to turn on from the CP, and seems to offer at least a great deal of what Clockwork does -- definitely plus. The information is  right there with your screen or app, and it's drill-down, so spans of details are easy to access when you want them, even when a site may be already fielded.

Most importantly, possibly, it's attuned to the many things Craft actually uses and does, while including all those database, timing, etc. matters -- with Craft's own levels of logging beside them. 

There's a free video on this by a great communicator in the community, Ryan Irelan, who offers a wide-ranging set of training videos which also might interest on his CraftQuest site - https://craftquest.io/pathways is the latest entry point, where you can see plugin development is highlighted, and there are some really expert persons presenting courses.  I think he's helped many.

Here's that video where you can get a walkthrough and see a lot about the debug toolbar as embedded in Craft 3:

     https://www.youtube.com/watch?v=PvWV6yqh2EI

For the rest, especially for plugin development, I suspect you'd probably find most developers using PhpStorm, which has many suited features. Its debug abilities are top-notch, and with them you can go as far towards PHP bare metal as needed. Php, Craft, Yii are in almost every way single-threaded, and so this is very effective -- and this IDE is as useful in most of what you'd do with JavaScript as well.

**Comment by thegregthomp** [comment]
Thanks for the response @narration-sd, honestly I’m mostly looking for the logging aspect, the ability to log out multiple vars without a var_dump, die. I’m not to familiar with the yii tools or how to use them

**Comment by narration-sd** [comment]
Makes sense, if this sort of thing is PhpStorm debug's specialty, via an xdebug implementation that works, where you can not only monitor, observe branching, pause to observe, etc., but also set var values yourself at a trouble point and resume.

Here's another way you can get at your variables nicely in the sense you are thinking. 

Use Craft::info(), Craft::warning(), or Craft::error() to put a message with your information in the Craft log. When you use a plugin name in the optional second $category argument, your own log items will be labeled. Then that same Yii toolbar will parse the log for you, limited to your own labelled messages.

All you need to do is create a string for your message from vars in involved, letting you label and send several at once. You already know the PHP way to do this -- just use var_export() with a formatting expression and a return argument of true.

**Comment by narration-sd** [comment]
Just to head off trouble, you'll need to have Craft debugMode set true, for the tools to work for you.

I'd expect to learn areas of the things you mention, for success as you get into plugin development. That's where Ryan's courses will likely give a quickstart, and then Google is your friend.

**Comment by brandonkelly** [comment]
This isn’t really the right place get this kind of help, as it’s not an issue or feature request for Craft. I’d suggest you post the same question over at https://craftcms.stackexchange.com.
