### ISSUE TITLE
Entries field quadruples selected entries

### ISSUE THREAD

**Issue by Tam** [craftcms/cms#4066]
### Description
Selected elements in the entries field are quadrupled.

### Steps to reproduce

1. Create an entries field
2. Add an entry to the field
3. Try to save

<img width="323" alt="Screenshot 2019-03-28 at 12 03 01" src="https://user-images.githubusercontent.com/977594/55156302-75ad4000-5151-11e9-9de7-088099cf938e.png">

### Additional info

- Craft version: Craft Solo 3.1.20.1
- PHP version: 7.3.2
- Database driver & version: PostgreSQL 11.2

Plugin | Version
--- | ---
Blitz | 2.0.7
DigitalOcean Spaces Volume | 1.1.1
Imager | v2.1.7
Imager Storage Driver for DigitalOcean Spaces | 1.0.0
Minify | 1.2.9
Redactor | 2.3.2
SEO | 3.5.4
Super Table | 2.1.16
Typed link field | 1.0.17

**Comment by brandonkelly** [comment]
Can you try disabling each of those plugins and see if this continues to happen?

**Comment by Tam** [comment]
I've tried disabling each plugin individually and all of them at once but the issue persists. The post data is correct, the returned data is wrong. Everything was fine in 3.1.19, the issue only started happening when we upgraded to 3.1.20.1.

**Comment by Tam** [comment]
Also worth noting that the limit passed to the element query is doubled, so passing a limit of 3 will return 6 elements.

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you please send your `composer.json` and `composer.lock` files and a database backup over to support@craftcms.com and reference this issue URL?

**Comment by Tam** [comment]
That's sent

**Comment by brandonkelly** [comment]
This ended up being due to the entries having soft-deleted structure data associated with them. Fixed for the next release.
