### ISSUE TITLE
Project config not applying correctly

### ISSUE THREAD

**Issue by GuiguiCucu** [craftcms/cms#4067]
### Description

I want to import all my sections and fields from my local database to my preproduction database.
However, the project config is not applying correctly on my preproduction environment.

When I try to apply it from the back office, it fails with this message: 
`Couldn't save single entry due to validation errors on the slug and/or URI`.

When executed in terminal, it fails silently as some of my single sections are missing.

Thanks in advance.

### Steps to reproduce

1. Activate project config in `config/general.php`
2. Deploy project on another environment with another database
3. Go to the admin page and execute project config synchronisation

### Additional info

- Craft version: 3.1.19
- PHP version: 7.1.24
- Database driver & version: MySQL 5.5.62
- Plugins & versions:
  - Neo 2.2.7
  - CP Field inspect 1.0.5
  - Redactor 2.1.0
  - Super table 2.1.16
  - Typed link field 1.0.17

**Comment by brandonkelly** [comment]
Please ensure you’ve followed the steps listed here: https://docs.craftcms.com/v3/project-config.html#enabling-the-project-config-file

**Comment by GuiguiCucu** [comment]
Ok, we have omitted the primary database backup in steps 6 and 7, so there was conflict between our two databases.
It works just fine now.

Thanks a lot !
