### ISSUE TITLE
Double click to expand sub folders?

### ISSUE THREAD

**Issue by RitterKnightCreative** [craftcms/cms#4070]
### Description
Minor usability thing, on macOS (and Windows), when you double click on a folder, it opens the reveal more items in inside. 

It would be nice if Craft also followed that simple paradigm for asset volumes.

Had a client forget that the triangle next the asset volume expanded to reveal more assets.

The tap target for the triangle is also quite small. 

Very similar to the usability requested in https://github.com/craftcms/cms/issues/979.

### Additional info

- Craft version: 3.1

**Comment by brandonkelly** [comment]
Easy enough! Added for the next release.

**Comment by RitterKnightCreative** [comment]
Right on - thanks!
