### ISSUE TITLE
Enabling a site for a section fails to propagate content based on translation methods

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#4071]
### Description
I have some site groups that are being used to define shared languages between sites. Certain fields are set so their translation methods are based on groups.

I have a group named **German** with the sites **German (German)** and **Switzerland (German)**.

If **Switzerland (German)** is disabled for a section, then gets enabled, the site's content is populated from the primary site, **US (English)**.

My expectation is that the re-saving entries task should take translation methods into account when populating content for a newly enabled site.

### Steps to reproduce

_Assuming the the following setup:_
- Multi-site
- Sites grouped by language
- Have at least one site in a site group that is not in the same group as the primary site
- Have a section with fields that use group based translation methods

1. Add a site to an existing site group
2. Enable that site in a section
3. Wait for re-saving entries task to complete
4. View an entry in that section for your new site
5. Notice that the content is incorrect in terms of translation method logic

_If this is working as intended, the resulting content for your new site can cause issues as re-saving an entry from this site will propagate incorrect information to other sites in the group._

I also tried disabling a site for a section, which results in all of its content being deleted. Re-enabling the site re-populates content from the primary site, just like setting it up for the first time. Should this data be completely removed, or should it still exist so it can possibly be re-enabled again, at a later date.

### Additional info

- Craft version: 3.1.20.1
- PHP version: 7.1.25
- Database driver & version: MySQL 5.5.5

**Comment by jsunsawyer** [comment]
I just stumbled upon #3554, which seems to add a completely different way of handling site propagation altogether.

I believe that this would be too restrictive for our use case, as propagation should happen for sites newly created groups as well.

**Comment by brandonkelly** [comment]
There are a lot of details that matter here, so it’s probably easiest if you can send your `composer.json` and `composer.lock` files, plus a database backup, over to support@craftcms.com, along with steps to reproduce _for your install_. Otherwise, please at least post your `composer.json`, `composer.lock`, and `config/project.yaml` file (you may need to temporarily enable [useProjectConfigFile](https://docs.craftcms.com/v3/config/config-settings.html#useprojectconfigfile) to get that).

**Comment by jsunsawyer** [comment]
@brandonkelly I sent the above details to support a while back, but never got a response. We've since handed off this project to another agency, so I have no intention of digging into this further.

I wouldn't even be able to tell you if this is still an issue due to the complex nature of the site. Closing for now. I'll reopen if I ever run into this again in a similar setup.

**Comment by brandonkelly** [comment]
Huh, strange, can’t find any record of it and we would never close a ticket without responding. Sorry about that :(
