### ISSUE TITLE
Add command to retry all failed jobs in the queue

### ISSUE THREAD

**Issue by rungta** [craftcms/cms#4072]
### Description

The job queue can often rack up a whole lot of similar _Failed_ tasks due to various reasons (server misconfiguration being a common one). In such cases, the workflow then is to figure out why the job(s) were failing, fix that, and then manually click on each job and select _Retry_. This is alright when the number of failed jobs are 10 or less, but quite inefficient if that number if 50 or more. It would be great if one could bulk trigger retrying all failed jobs from the command line. Something like:

```shell
# retry a single job
craft queue/retry <id>

# retry all failed jobs
craft queue/retry all
```

### Additional info

- Craft version: 3.1.19
- PHP version: 7.3

**Comment by brandonkelly** [comment]
Good idea. Added for the next release!
