### ISSUE TITLE
Project Config rebuild matrix blocks without fields

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#4074]
### Description
Sometimes you have matrix blocktypes without fields such as some dividers or other fixed content that does not need to be edited. Currently when you rebuild the project with such empty blocks an exception is thrown in [ProjectConfig line 1713](https://github.com/craftcms/cms/blob/develop/src/services/ProjectConfig.php#L1713)

```PHP
$blockType['fields'] = $matrixSubFields[$blockTypeUid]
```

`matrixSubFields` is an array of all fields, and you build the matrix block types by those fields but since this block type has none you'll receive an undefined index exception.
The simple solution would be to include this
```PHP
$blockType['fields'] = $matrixSubFields[$blockTypeUid]?? [];
```

### Steps to reproduce

1. Create a matrix block type without fields
2. Run  `project-config/rebuild`

### Additional info

- Craft version: 3.1.20.1
- PHP version: 7.2

**Comment by andris-sevcenko** [comment]
Thanks!
