### ISSUE TITLE
[Feature Request] Perform DB backup from CLI

### ISSUE THREAD

**Issue by spAnser** [craftcms/cms#4075]
It would be helpful to be able to perform database backups through the command line.

Yes there is probably fairly easy ways to do this already, but having Craft already handling the MySQL user, password, database name, file naming and compression. It would be much easier to just call a quick `backup/db` action through the CLI.

**Comment by brandonkelly** [comment]
Added for the next release!

The following are supported:

```bash
# create backup in the given folder
./craft backup ./backups

# create backup in working directory with custom filename
./craft backup backup.sql

# create backup in specific location
./craft backup ./backups/backup.sql

# create backup in the storage/backups/ folder
./craft backup
```
