### ISSUE TITLE
interrupted VM consistently corrupts Craft searchindex table

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#4081]
### Description
I hope this isn't just a fluke of my otherwise very reliable Vagrant dev setup.

What happens is that every time I forget the VM is running, and do a completely proper Win10 'Shut down' as they call it, next time I bring the VM up and the Craft install on it executes a particular database call, it fails on a side effect of noting searchindex is corrupted.

It's an instant fix with Navicat, but very consistently happens. I suspect:
- the query that fails is in a plugin, and the one that fails out is either a record creation or the transaction entry that begins it.
- why should anything about shutdown, even a rude power-off which this definitely isn't, hurt the database? 
- Especially when there's always been at least minutes of interval between last Craft instance running and the soft shutdown? Thus even task queues should never be involved. And this fail always occurs, when I do the forget-VM-running-later-shut-down sequence.
- I can only think it's because database activity on that one searchindex table is still in memory, and even MariaDB/MySql doesn't auto-flush it on receiving the external powerdown signal.
- So, this could be at any point in the chain of Win10-VirtualBox-Homestead/Vagrant-Craft-Database, yes.
- I'm thinking, though, that there may be either something unusual about that searchindex table's setup, and/or, there's something Craft should be doing to assure it's transactions are flushed to disk in a timely fashion.
- like maybe there's something unfinished in the updates to searchindex  that must occur when entries are edited?  In a task running after to do it, maybe?

Haven't investigated further as a) you guys know all about this best b) have been rather busy with the alligators getting Live Vue Gatsby into the Plugin Store, latest being giving the Beta group the wholesale Yaml drive they wanted.  Which became actually a very nice thing, when I insta-layered my Guidance Experience on it. Will have to talk to you about that...

### Additional info
It's been many, always to-the-minute. Current is:

PHP version	7.1.26
OS version	Linux 4.15.0-45-generic
Database driver & version	MySQL 5.7.25
Image driver & version	GD 7.1.26
Craft edition & version	Craft Pro 3.1.20.1
Yii version	2.0.16.1
Twig version	2.7.4
Guzzle version	6.3.3
Imagine version	0.7-dev
Plugins
CraftQL	2.0.0-beta1
Element API	2.5.4
Live Vue Gatsby	dev-gatsby
Redactor	2.3.2

**Comment by brandonkelly** [comment]
I get this too, FWIW, so it’s not Windows-specific or the fault of a plugin.

**Comment by narration-sd** [comment]
That's very interesting, Brandon. What I meant about a plugin being involved, is that it happens where _my_ plugin is involved -- and only when through a hook, it does more than init, and goes into action.

The thing it does, only when in action, and that I strongly suspect just gets the database to realize its been in trouble, is set (and complete) a transaction. And within that transaction, it's creating - and placing content in -- a new Entry.

That, we could predict, is going to set off some searchindex table action, for the new content. And so the fractured table is recognized, requiring the repair. QED, I think.

So it comes back to two things, at least from my perspective (!):

- what I suggested, about searchindex needing something more, to assure it's always very soon getting flushed to disk
- in with the alligators as I am, if you have a tip on actually not firing searchindexing on this new Entry, which will never need it, I'd appreciate not having to figure this out, and we'd both gain the efficiency benefits, thanks.

**Comment by jamesmacwhite** [comment]
Can confirm I also get this with Nanobox. The only common factor is likely VirtualBox. I put it down to generally being an environment related thing, not necessarily down to a specific plugin though.

**Comment by narration-sd** [comment]
Incidentally, perhaps, I'm not seeming to see these anymore, so possibly something's changed for the better, beyond perhaps improved habits here.

**Comment by brandonkelly** [comment]
Sweet! We moved search index updating off to a queue job that runs after elements are saved, which should generally improve that table’s reliability. I’ll close this now.
