### ISSUE TITLE
[3.2] Element index pagination history is incorrect

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#4084]
### Description
The URL is being updated to the incorrect value when clicking the back link.

### Steps to reproduce
Video: https://venveo.d.pr/ZPqGpQ
1. Create any channel and insert some data
2. Visiting entry list appends "htt" to the URL immediately
3. Click Next
4. Click Back - additional "htt" strings are appended

### Additional info

- Craft version: 3.2.x-dev
- PHP version: 7.2
- Section Name: Test Channel
- Section Handle: testChannel
- Section URL format: test-channel/{slug}
- Section Template: None
- Single site

### Related
#818

**Comment by brandonkelly** [comment]
Fixed this in the `3.2` channel. Run `composer clear-cache` and then `composer update` and you should be good to go.
