### ISSUE TITLE
How to configure Craft to run admin on a local network.

### ISSUE THREAD

**Issue by BBaysinger** [craftcms/cms#4085]
### Description

I have a Craft instance running via Valet, per the instructions [here][1].

Running the project via `valet link` works great, and `valet share` works, except when I try to access the admin side. I'm using `valet share` to try to access the site over a local network for a demo.

In Chrome from `http://ad3f5068.ngrok.io/admin/login` when I try to log in, I get:

    OPTIONS http://craftycoffee.test:60/index.php?p=admin/actions/users/login 404 (Not Found)
    Access to XMLHttpRequest at 'http://craftycoffee.test:60/index.php?p=admin/actions/users/login' from origin 'http://ad3f5068.ngrok.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

If I use HTTPS, I get net::ERR_SSL_PROTOCOL_ERROR across a bunch of requests.

Jalen Davenport suggested unsecuring Craft, via enableCsrfProtection, but I'm still getting the same errors. I'm not sure if there is something I need to do in Craft or Valet to get this working.

In any case, I'm not finding instructions on how to run Craft on a local network.

### Steps to reproduce

1. Set up a Craft instance via https://medium.com/@jalendport/running-craft-cms-3-on-laravel-valet-6df61e5193fd
2. run `valet share`
3. Try logging in to admin.
4. Check the console for errors.

### Additional info

- Craft version: Craft Solo 3.1.20.1
- PHP version: 7.3.2
- Database driver & version: MySQL 8.0.15
- Plugins & versions: None

**Comment by brandonkelly** [comment]
That’s a CORS error, which is happening because you are accessing Craft from `http://ad3f5068.ngrok.io` but Craft apparently thinks it is being accessed from `http://craftycoffee.test`.

Any idea where Craft is getting `craftycoffee.test`? Perhaps you’ve set the [baseCpUrl](https://docs.craftcms.com/v3/config/config-settings.html#basecpurl) config setting in `config/general.php` ?

**Comment by ademers** [comment]
@BBaysinger Did you ever manage to resolve this? I'm having the same issue on Homestead. When I set `'baseCpUrl' => 'http://xyz.ngrok.io',`, I get a 404 error `Template not found: admin`. Thanks!

**Comment by BBaysinger** [comment]
This was long ago. I can’t remember what I did, but there may be some info here: https://craftcms.stackexchange.com/questions/30001/valet-share-ngrok-giving-404-cors-errors
