### ISSUE TITLE
[Feature Request] “Or” condition when querying elements with radio buttons fields

### ISSUE THREAD

**Issue by benface** [craftcms/cms#4086]
Looking at [this page](https://docs.craftcms.com/v3/radio-buttons-fields.html#templating), it looks like it’s not currently possible to query elements that have either one of many radio options selected. It would be useful.

**Comment by brandonkelly** [comment]
Just updated the templating examples to show how you can do an OR condition.

**Comment by benface** [comment]
@brandonkelly Oooh nice! What about checkboxes fields?

**Comment by brandonkelly** [comment]
@benface Checkboxes and Multi-select fields are a little messier, since they just store the selected options as JSON, but you could do it with this syntax:

```
['*"foo"*', '*"bar"*']
```
