### ISSUE TITLE
Eager loaded matrix fields of type redactor and url are returning empty arrays

### ISSUE THREAD

**Issue by sem4phor** [craftcms/cms#4087]
### Description
When using element queries with eagerloading to load a matrix field of the type URL / Redactor you get an empty array.

```
use craft\elements\MatrixBlock;

$elements = MatrixBlock::find()
      ->fieldId(fieldId)
      ->with(['blockType:fieldNameOfUrlField'])
      ->all();

echo $elements[0]->fieldNameOfUrlField; // [ ]
```

Possible Workaround: query with 'asArray'

```
$elements = MatrixBlock::find()
      ->fieldId(fieldId)
      ->with(['blockType:fieldNameOfUrlField'])
      ->asArray()
      ->all();

echo $elements[0]['fieldNameOfUrlField']; // https://craftcms.com/
```

### Steps to reproduce

1. Create a matrix with a field of type URL
2. Look up the field id in your database
3. Execute above query with your field id

### Additional info

- Craft version: 3.1.8
- PHP version: 7.1-apache
- Database driver & version: mariadb 10
- Plugins & versions:  element-api 2.5.4, redactor 2.3.1

**Comment by brandonkelly** [comment]
Eager-loading only works correctly for relational fields. For URL and Redactor fields there’s nothing to eager-load.
