### ISSUE TITLE
Asset field with variables on multisite creates a bunch of unwanted folders

### ISSUE THREAD

**Issue by lexislav** [craftcms/cms#4090]
When using asset field with variables in my entries, example:

`/photos/news/{postDate|date('Y')}/{slug}`

On multisite with translations, every update of each translation move photos to another folder - with the localized slug. Leaving empty folders behind. Example: 

from

`/photos/news/2018/english-slug`

to

`/photos/news/2018/deutshce-slug`

while keeping original folder.

It is quite logical. And quite impractical. It doubles, triples number of folders in assets (depending on a number of translations). It makes it hard to navigate in assets then and to localize files when needed. It is not probably a bug (?) but neither comfortable solution. Could be solved by creating a symlink for localized assets' locations or even better by fixing the variables when originally saved.

- Craft version: 3.1.20.1 (Pro)
- PHP version: 7.2.11
- OS version: Linux 3.16.0-77-generic
- Database driver & version: MySQL 5.5.62
- Image driver & version: Imagick 3.4.3 (ImageMagick 6.7.7-10)

**Comment by brandonkelly** [comment]
Maybe just standardize on using a single site’s slugs?

```twig
/photos/news/{postDate|date('Y')}/{{ site.handle == 'primarySiteHandle' ? slug : (craft.entries.id(id).site('primarySiteHandle').one().slug ?? slug) }}
```

**Comment by lexislav** [comment]
I haven't been thinking about such extensive use of code in assets field - thanks, Brandon, for pointing out how powerful it might be!
Impressive. Seems like Craft can really anything. Tested and it's working.

**Comment by brandonkelly** [comment]
Glad that’s working for you!
