### ISSUE TITLE
Refer to environment variable within another in .env

### ISSUE THREAD

**Issue by BridgingUnit** [craftcms/cms#4093]
Had thought about doing something like this:

in .env:

```
DEFAULT_SITE_URL="//mysite.com"
ASSETS_BASE_URL = DEFAULT_SITE_URL."/assets"
```

in config/general.php:

```
'aliases' => [
            '@assetBaseUrl' => getenv('ASSETS_BASE_URL'),
        ],

```
But if I do, then when that alias is used within Base URL in an asset volume, and then output, I get something like this:

`<img src="DEFAULT_SITE_URL.&quot;/assets&quot;/uploads/images/myasset.jpg">`

The environment variable referring to another doesn't parse properly within the alias.

Not sure if I'm trying to do something I shouldn't, or if this is a bug.

**Comment by jamesmacwhite** [comment]
Environment variables generally aren't designed to work this way. You are also mixing between ENV and PHP syntax in your examples.

In your config/general.php, you could just as easily concatenate the two env vars:

```
'aliases' => [
    '@assetBaseUrl' => getenv('DEFAULT_SITE_URL') . '/' . getenv('ASSETS_BASE_URL'),
],
```

Or perhaps define DEFAULT_SITE_URL as a PHP constant:

```
define('SITE_URL', getenv('DEFAULT_SITE_URL') . '/');

'aliases' => [
    '@assetBaseUrl' => SITE_URL . getenv('ASSETS_BASE_URL'),
],
```

These are just a couple of examples and could probably be a bit cleaner, but .env should be used in a one-to-one nature, more complex stuff should be done with PHP.

**Comment by BridgingUnit** [comment]
Cheers James.

Already got that figured and worked around it, but thought I'd flag up the impact, in case it was something that needed to be looked into. If not, fine. Seemed odd that output from one alias would come back output the way it did, when works fine the usual way, but like you say, it's probably trying to use PHP within .env when that's not how it should be used.

Thank you though.

**Comment by jamesmacwhite** [comment]
No problem. I should clarify, the general use case is mainly one-to-one, but for information, Craft CMS uses PHP dotenv:

https://github.com/vlucas/phpdotenv

It does support using ENV vars within another using interpolation with `${}`:

ENV_VAR="example"
ANOTHER_ENV_VAR="${ENV_VAR}/somethingelse"

However, it's often cleaner to not do this, but you can if you want.

**Comment by BridgingUnit** [comment]
That's great James. Demonstrates what I should have done and points to where it can be referenced perfectly.

I should probably close this now. Thanks again.
