### ISSUE TITLE
__home__ slug gets rewritten to home on save

### ISSUE THREAD

**Issue by nilsenpaul** [craftcms/cms#4096]
### Description
If we want to define an entry as the site's homepage, we always set the slug to `__home__`. As of the last update, this gets automatically rewritten to `home`, which stops the homepage from being found.

### Steps to reproduce

1. Create an entry with slug `__home__`
2. Save it, re-open it and see the slug changed to `home`

### Additional info
The problem is solved in a very quick and dirty way, if I change line 42 in `craftcms/cms/src/helpers/ElementHelper.php` to:

```
if ($str !== '__home__') {
    $str = StringHelper::toKebabCase($str, $glue, $lower, false);
} 
```  

- Craft version: 3.1.21

**Comment by brandonkelly** [comment]
Sorry about that. Just released 3.1.21.1 which fixes this.
