### ISSUE TITLE
Method to check if element matches array of criteria without db lookup

### ISSUE THREAD

**Issue by sjelfull** [craftcms/cms#4097]
It would be great if there was a way to check if a array of criteria matches a element without doing extra db lookups.

This would a static method or a method on the base element class.

**Comment by putyourlightson** [comment]
Something like this should get you started:
```
$elementQuery = $elemenType::find();

$elementQuery->where($criteria);

$found = in_array($element->id, $elementQuery->ids());
```

**Comment by putyourlightson** [comment]
Although, now that I think about it you probably meant to write "with_out_ db lookup" in the issue title instead of "with db lookup", so my code above probably doesn't help.

**Comment by brandonkelly** [comment]
As said in Discord, it wouldn’t be possible to achieve this without quite a bit of help from each element type, as not all element query params have a direct correlation to instantiated element attributes.

That said, there are ways to reduce the number of queries needed to one per element type/criteria you care about.
