### ISSUE TITLE
craft.app.sites.getAllSites() not returning base URL stored in environment variable

### ISSUE THREAD

**Issue by peteheaney** [craftcms/cms#4098]
### Description
If I store the site URLs in the .env file, e.g.

```
SITE_URL_US="https://www.example.com"
SITE_URL_GB="https://www.example.co.uk"
```

and then select those environment variables as the `Base URL`s in the CP, the following code outputs a list of environment variables rather than a list of URLs:

```html
{% set sites = craft.app.sites.getAllSites() %}
{% for site in sites %}
    {{ site.baseUrl }}<br>
{% endfor %}
```

This should output:
```
https://www.example.com
https://www.example.co.uk
```

But it actually outputs:
```
$SITE_URL_US
$SITE_URL_GB
```

### Steps to reproduce

1. Create a SITE_URL variable in the .env file
2. Select that environment variable as a site Base URL in the CP
3. In a template, loop through all sites and attempt to output the Base URL for each one

### Additional info

- Craft version: 3.1.21
- PHP version: 7.2.15
- Database driver & version: MySQL 5.7.25
- Plugins & versions: Amazon S3 1.2.2, Freeform Lite 2.5.16, Json Client 1.0.3, Mailchimp Subscribe 2.0.4, Maps 3.4.10, Redactor 2.3.2, Super Table 2.1.16, Wordsmith 3.0.4.

**Comment by brandonkelly** [comment]
To get the parsed URL, you have to call `site.getBaseUrl()` rather than `site.baseUrl`. (See #3964 for a related discussion.)

**Comment by jan-dh** [comment]
@brandonkelly this seems to be broken, even with the `site.getBaseUrl` still only get the unparsed URL. 

my `.env` file:
```
BASE_URL_1 = "http://multilanguage.com"
```
my template:
```
{# Loop through all of the site locales, except the current one #}
{% set langSwitcher = craft.app.sites.getAllSites()|without(currentSite) %}

{% for site in langSwitcher %}
    {% set url = site.getBaseUrl() %}
    <a href="{{url}}">{{site.language}}</a>
{% endfor %}
```

My output:
```
  <a href="$BASE_URL_1" >EN-US</a>
  <a href="http://multilanguage.com>EN-US</a>
```

First site is being set in `.env` (with the name `BASE_URL_1`). For the second one, I made an alias in the general config using the same variable:

```
'aliases' => [
	'baseURL1' => trim(getenv('BASE_URL_1'), '/'),
],
```

**Comment by brandonkelly** [comment]
@jan-dh Can you please send your `composer.json`, `composer.lock`, and template files, plus a database backup, over to support@craftcms.com?

**Comment by jan-dh** [comment]
Done
