### ISSUE TITLE
Project config rebuild will restore deleted content

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#4100]
### Description
When you run `project-config/rebuild` it will restore deleted content without it's `dateDeleted` value. While this won't do any harm in most cases it could do unexpected things in certain scenarios.

### Steps to reproduce

1. Create a field
2. Delete a field
3. Run `project-config/rebuild`
4. Sync your config with live
5. See your Field will be live and not on your local env

### Additional info

- Craft version: 3.1.21

**Comment by andris-sevcenko** [comment]
Oooh, good catch!
