### ISSUE TITLE
Missing translation categories should not be logged as Error

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#4109]
If you are in the CP using a non-english lang, your logs will be littered with tons of errors:

```
2019-04-08 14:21:33 [-][1][-][error][yii\i18n\PhpMessageSource::loadFallbackMessages] The message file for category 'relabel' does not exist: /app/vendor/composer/anubarak/craft-relabel/src/translations/fr-CA/relabel.php Fallback file does not exist as well: /app/vendor/composer/anubarak/craft-relabel/src/translations/fr/relabel.php
```

…which can be annoying when you're looking for actual errors. Seems like falling back is the expected behavior, and shouldn't be logged as an error.

**Comment by gtettelaar** [comment]
@timkelty It should be possible to do that using Yii's [except](https://www.yiiframework.com/doc/guide/2.0/en/runtime-logging#message-filtering) property which you can set that in `app.php`?

**Comment by timkelty** [comment]
Good idea @gtettelaar, this seems to work:

```
                        'except' => [
                            'yii\web\HttpException:40*',
                            'yii\i18n\PhpMessageSource:*'
                        ],
```

**Comment by gtettelaar** [comment]
@brandonkelly If this is something you would be open to having in the core via `Craft::$app->getConfig()->getGeneral()` i have some time to set up a PR for this?

**Comment by brandonkelly** [comment]
Probably safe to just ignore PhpMessageSource errors as part of the base configuration, rather than making it a config setting. If either of you have a chance to test it out and PR it, I’d be happy to accept it, even for Craft 3.1.
