### ISSUE TITLE
img "alt" attribute disappearing in html field

### ISSUE THREAD

**Issue by dviedma** [craftcms/cms#4110]
### Description
"alt" attribute disappears from <img> tag on HTML field after reloading the page

### Steps to reproduce

1. Add an image to the HTML field
2. Edit its alt property via image popup
3. Switch to source code view, notice alt attribute is there
4. Reload the page. Open again image pop or switch to source code view. Notice alt attribute is gone

### Additional info

- Craft version: 3.6.4

**Comment by dviedma** [comment]
Major facepalm: it turns out the "alt" attribute wasn't listed in the "allowed_attributes" in the htmlcleaner config. This is a non issue.

**Comment by brandonkelly** [comment]
Glad you got it working!
