### ISSUE TITLE
Draft matrix blocks not displaying in editor

### ISSUE THREAD

**Issue by mark-adigital** [craftcms/cms#4114]
Hi - I've hit an issue that seems to have been introduced with a recent update. When adding a matrix block and saving the entry as a draft, the block will display in preview, but not in the the entry editor, and the project where this was reported also includes a front end editor through which the same issue occurs.

I tried this with other Craft installs we have running and consistently found that the problem occurs after updating to the most recent version. I don't know specifically when the issue is introduced, but it definitely is not present in 3.1.18.

Thanks,

Mark

**Comment by brandonkelly** [comment]
Duplicate of #4105
