### ISSUE TITLE
Re-indexing Asset volume won't include empty folders

### ISSUE THREAD

**Issue by naboo** [craftcms/cms#4119]
### Description
If I re-index an Asset volume which contains empty folders these folders won't get added to the volume (but remain on disk/space). When I later want to create those folders from within Craft to add new files I can't because Craft throws an error saying that the folder already exists.

### Additional info

- Craft version: Craft CMS 3.1.18
- PHP version: 7.2

**Comment by andris-sevcenko** [comment]
Is this using a local volume?

**Comment by naboo** [comment]
No, this was actually a S3 volume.

Den ons 10 apr. 2019 11:12Andris Sevcenko <notifications@github.com> skrev:

**Comment by andris-sevcenko** [comment]
@naboo not able to reproduce this. Are you still experiencing this?

**Comment by naboo** [comment]
I haven't tried in a while @andris-sevcenko. But you can keep it closed and if I do I'll re-open it. Thanks.
