### ISSUE TITLE
FR: Pass query results to paginate tag

### ISSUE THREAD

**Issue by jan-dh** [craftcms/cms#4120]
### Description
I sometimes have pages where I need a list of items, both paginated and not paginated. For example: a page with a list of shops. I would like to have
1. paginated shops 
2. a google maps with all the shops on it 

At the moment I have to do this in 2 seperate queries:
1. paginated tag with the query
2. another query for all the musea that I then output to a json

**Comment by brandonkelly** [comment]
This mostly defeats the point of pagination, but we just released Craft 3.1.22 which adds a `setPageResults()` method to Craft’s Paginator class, so now you should be able to do this:

```twig
{% set query = craft.entries()
    .section('shops')
    .orderBy('shopName ASC') %}

{% set allShops = query.all() %}
{% set shopsPerPage = 10 %}
{% set offset = (craft.app.request.pageNum - 1) * shopsPerPage %}
{% set pageShops = allShops|slice(offset, shopsPerPage) %}

{% set paginator = create('craft\\db\\Paginator', [query, {
    pageSize: shopsPerPage,
    currentPage: craft.app.request.pageNum,
    pageResults: pageShops
}]) %}

<!-- create the map -->
{% for shop in allShops %}
    ...
{% endfor %}

<!-- page results -->
{% for shop in pageShops %}
    ...
{% endfor %}

<!-- pagination navigation -->
{% set pageInfo = create('craft\\web\\twig\\variables').create(paginator) %}

Page: {{ pageInfo.currentPage }}
First Page: {{ pageInfo.firstUrl }}
Last Page: {{ pageInfo.lastUrl }}
Prev Page: {{ pageInfo.prevUrl }}
Next Page: {{ pageInfo.nextUrl }}
```

If it were me, I’d just opt for a second query on the page, maybe within some `{% cache %}` tags along with all the map HTML, so it doesn’t even need to be run most of the time. But I’ll let you be the judge :)

**Comment by jan-dh** [comment]
Nice! I'll make sure to test out your solution. Thanks for the quick reply. Awesome work as always 🤗

**Comment by simeon-smith** [comment]
I'm trying to do something similar but am getting and error when I try to set up the pageInfo.

```
{% set pageInfo = create('craft\\web\\twig\\variables').create(paginator) %}
```

**Comment by brandonkelly** [comment]
@simeon-smith `craft\web\twig\variables` is not a class name.

**Comment by simeon-smith** [comment]
@brandonkelly, I was following the code in your example. Is this no longer available?

**Comment by brandonkelly** [comment]
Whoops, that should have been `craft\\web\\twig\\variables\\Paginate`. Just updated the example.
