### ISSUE TITLE
Entries Multisite CP Navigation Bug

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#4121]
### Description
We have some Multisites on our installation. There is a Single Entry `Startseite` (Home) for Each Site. When I switch between the Site via the Dropdown and afterwards I click on the `Startseite` Entry I come to a other Multisite. 

Maybe Images can describe it better:

![image](https://user-images.githubusercontent.com/764292/55892950-98127500-5bb7-11e9-8b9e-06341ece227a.png)

I'm on this site: When I hover over the `Home` (It must called be Startseite but it doesn't switch when I switch a site) I get this link:

`https://www.bistum-passau.de/admin/entries/home/2-homepage/default`

When I hover on `Home Sub Site` in the table on the right I get this Link (this one is the right link):

`https://www.bistum-passau.de/admin/entries/homeSubSite/10678-home-sub-site/pfarrverbandBurghausenDe`

But it becomes more strange after Reload:
![image](https://user-images.githubusercontent.com/764292/55893107-ecb5f000-5bb7-11e9-8e94-faa4c8915910.png)

Now on the left there is the `Startseite` but when I hover now I get this link:

`https://www.bistum-passau.de/admin/entries/homeSubSite/10678-home-sub-site/bistumsblattDe`

To make it a bit more clear here is a short video. Look at the status bar when I hover on the links.

https://drive.google.com/file/d/1vusjpkGIBhfHoNUn5WNgvpMNBsaSGGYj/view

### Additional info

- Craft version: 3.1.15
- PHP version: 7.2
- Database driver & version: MySQL 8

**Comment by brandonkelly** [comment]
Do you have multiple “Home” sections defined in Settings → Sections? Which sites are each of them enabled for?

**Comment by davidhellmann** [comment]
I have two Home Sections. One for the Main Page and one for the subpages. The setup looks like this:

Main Site:
![image](https://user-images.githubusercontent.com/764292/56061774-b7053880-5d6a-11e9-96b3-efd44210fb14.png)


Sub Sites:
![image](https://user-images.githubusercontent.com/764292/56061796-c5ebeb00-5d6a-11e9-824c-ac727bd9e53e.png)


I can imagine whats happen here. Craft can handle just one HOME Template? Is there a way to fix that cause I need different Fields on the Pages. 

Thanks for looking into it @brandonkelly

**Comment by brandonkelly** [comment]
@davidhellmann Yeah so if there are two different “Home” sections, Craft isn’t going to maintain selection between them when switching between your main site and a subsite. Wouldn’t really be possible either so this will just have to be a slightly awkward behavior on your site.

**Comment by davidhellmann** [comment]
@brandonkelly but how can I have two different Home templates. Site A has this fields and Site B hast other fields. 🤔

**Comment by brandonkelly** [comment]
You can’t, so having two Home sections is the right way to go.

**Comment by christophpaster** [comment]
@brandonkelly — I'm working with @davidhellmann on this: It's unfortunately beyond "slightly awkward": When multisite-users (only having access to 1 multisite) want to edit their Homepage, they get an `Unauthorized`-Error. That's because the Home-Entry of another Multisite is requested. 

It seems like the shortname of a Site is added to the URI. Once you delete the shortname manually, you get to the right entry in the CP.

**Comment by brandonkelly** [comment]
@christophpaster @davidhellmann can you send your `composer.json` and `composer.lock` files, and a database backup, to support@craftcms.com, and reference this issue + point us to the user account that this is happening for?

**Comment by martinhellwagner** [comment]
@brandonkelly I have sent the requested files already for issue https://github.com/craftcms/cms/issues/4172. However, I just sent you the updated `composer.json` and `composer.lock` plus the Google Drive link to the updated DB dump in an e-mail.

**Comment by martinhellwagner** [comment]
@brandonkelly Any news on this?

**Comment by brandonkelly** [comment]
@christophpaster we just looked into it with the Composer files and database you sent. It looks like the behavior you’re seeing is due to the Expanded Singles plugin. If you disable that, it should work as expected.

**Comment by davidhellmann** [comment]
@engram-design Brandon said it‘s a bug related to expanded singles. I disabled the plugin and it looks like it works. Maybe you can look into it?
