### ISSUE TITLE
Draft matrix blocks not displaying in preview

### ISSUE THREAD

**Issue by mark-adigital** [craftcms/cms#4125]
Possibly related to #4105 - I think there's still an issue here, our use case involves a front end entry editor and after applying the 3.1.22 release the Craft editor is fine but in the front end editor I had to update the field data retrieval from `entry.fieldHandle.status(null).all()` to `entry.getFieldValue('fieldHandle').all()`.

Also (and possibly related), I find that when previewing the draft via the 'Live Preview' and 'Share' buttons that the current entry data for matrix fields appears to be loaded rather than the draft data. I've tried updating the method call described above in the entry template but this didn't resolve the issue.

**Comment by brandonkelly** [comment]
You shouldn’t ever have to add `.status(null)`, even before eb5dc9f503863eb41f2d5fd1a46a49c91faa6c68, but yeah post-3.1.21 I would expect that it would start preventing Matrix fields from showing Live Preview/draft content if you are doing that.

Look through your templates and make sure you’re never setting any parameters on your Matrix block loops (such as `.status(null)`).

**Comment by mark-adigital** [comment]
Sorry - I wasn't very clear. The front end editor template was where I had `status(null)`, the idea being that this would then pull through both enabled and disabled blocks. However, updating that template to use `getFieldValue` instead worked.

The entry template itself (as in, the one rendered in live preview etc.) simply calls `entry.fieldHandle.all()`, but this isn't including the draft blocks.

**Comment by brandonkelly** [comment]
@mark-adigital Probably easiest if you could contact us from your support widget on the dashboard, which will send us all the files needed to reproduce the issue. Please point out specific steps to reproduce in the request body, and refer to this issue URL.

**Comment by mark-adigital** [comment]
Thanks for following this up @brandonkelly , I've taken another look and realised I couldn't replicate this specific issue in another install so investigated further and the actual root cause was a call to `entry.fieldHandle.inReverse().one()` which was breaking everything and needed to be changed to the `entry.fieldHandle.nth(entry.fieldHandle.count() - 1)` syntax in our use case (this had recently been updated from `.last()` due to a deprecation error!)

Unfortunately I just happened to notice both this issue and the one addressed in #4105 at the same time so thought they were related, but it turns out not.

**Comment by brandonkelly** [comment]
@mark-adigital Are you saying that `inReverse()` wasn't working _at all_, or just breaking results further down the page? The latter would be expected, as from then on, the element query returned by `entry.fieldHandle` will have the `inReverse` param enabled on it.

To set query parameters that don’t affect subsequent query calls, you can clone the element query using the [clone()](https://docs.craftcms.com/v3/dev/functions.html#clone-object) function:

```twig
{% set last = clone(entry.fieldHandle)
    .inReverse()
    .one() %}
```

**Comment by mark-adigital** [comment]
@brandonkelly Basically, the matrix field in question populates a slider and we needed to get the last slide before iterating over the others. The result of using `inReverse()` appeared to be twofold in that, as you say, the next element query was also reversed - but retrieval of the draft blocks is also prevented.

Thanks for the tip on using the `clone()` function, however that approach seems to break the retrieval of the last slide - `null` is returned. Everything is working as expected using the `nth` syntax, though.

**Comment by brandonkelly** [comment]
Can you post your whole template code?
