### ISSUE TITLE
Suggested edit for sendPasswordResetEmail() docblock

### ISSUE THREAD

**Issue by snowden0** [craftcms/cms#4128]
Current:

"A new verification code will generated for the user overwriting any existing one."

Suggested edit: 

"A new verification code will be generated for the user, overwriting any existing one."

https://github.com/craftcms/cms/blob/005bd938c7f5895b0b5c515880c45302462a1260/src/services/Users.php#L364

**Comment by brandonkelly** [comment]
Fixed, thanks!
