### ISSUE TITLE
[Feature request] Ability to resize HUD modal for new entries

### ISSUE THREAD

**Issue by KatieMFritz** [craftcms/cms#4129]
### Description

When adding a new entry in a second-level HUD modal (I don't know what to call it - see the picture), the form is capped at `max-width: 600px`. When a user has the screen real estate available, it's more comfortable to have a wider area for editing, especially when plugins have wonky styling.

![Image 2019-04-11 at 4 42 03 PM](https://user-images.githubusercontent.com/7085184/55991728-ed628b00-5c78-11e9-9aaf-42d4e52fd9a0.png)

Workaround I may try in the meantime, using the Control Panel CSS plugin:
```css
.hud .elementeditor {
  max-width: 100%;
}
```

I'm playing around with `resize: horizontal`, but haven't found the right application yet. 

### Steps to reproduce

1. Open a related entry field
2. Add a new element from there

**Comment by brandonkelly** [comment]
This is basically resolved for 3.7! Element editor HUDs have been replaced with (bigger) slideouts. See #8017.
