### ISSUE TITLE
session_start(): Unable to clear session lock record

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#4133]
### Description

This is almost certainly to do with the shared hosting this client website is on, but posting here incase anything can be done in Craft to fix it. I don't have access to Composer or SSH on this server, so all files are uploaded manually (don't know if that makes a difference).

Frequently in the control panel, usually when I try to do several things at once, I get this error message:

![image](https://user-images.githubusercontent.com/1250017/56032636-59053080-5d2b-11e9-8a39-a95a7d15df2f.png)

### Additional info

- Craft version: 3.1.22
- PHP version: 7.0 (also happens on 7.2)
- Database driver & version: MySQL
- Plugins & versions: Contact Form, Dashboard Begone, Mailchimp Subscribe, Redactor, SEO

**Comment by angrybrad** [comment]
Where is PHP configured to store its sessions on this box? You can check by going to http://yoursite.com/admin/utilities/php-info and searching for `session.save_path`.

**Comment by darylknight** [comment]
Looks like a series of IP addresses with port numbers

10.170.0.172:11211; 10.170.0.173:11211; 10.170.0.174:11211

![image](https://user-images.githubusercontent.com/1250017/56569218-398ac500-65c1-11e9-96a2-59b2b7e3222d.png)

**Comment by angrybrad** [comment]
Yup, those are likely memcached IP address for PHP session storage.

Best I can tell this is either a bug with PHP 7 and memcached or a bug in PHP itself.

See these for some potential workarounds:

https://github.com/php-memcached-dev/php-memcached/issues/399

https://github.com/php-memcached-dev/php-memcached/issues/269

https://bugs.php.net/bug.php?id=76465

**Comment by darylknight** [comment]
No worries, thanks Brad!
