### ISSUE TITLE
FR: Entry Edit - Hide Field Headings

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#4138]
It would be great if individual field headings could be toggled "hidden" when using the field layout designer. 

For a number of fields that provide the option for placeholder text, custom select button labels (e.g. an entries, category or assets field)  or in other cases when it's implied (e.g. for a blog entry there is a single rich text field), it would be great to have the option to hide the field heading. In many cases the heading can feel redundant, repetative and unnecessarily adds to the vertical height of an entry edit page.

**Comment by brandonkelly** [comment]
This was added in Craft 3.5.4 (see #6608).
