### ISSUE TITLE
[Feature Request] Add propagateElements method and events in 3.2

### ISSUE THREAD

**Issue by putyourlightson** [craftcms/cms#4139]
Feature request to add a `propagateElements` method and events to the `Elements` service in Craft 3.2.

Something similar was done with `resaveElements` in https://github.com/craftcms/cms/commit/5b0cd57a2f7cddd2bd8cb66cd42cc9c62d5deeba and the same logic could hopefully be applied to propagating elements. I'd be happy to submit a PR but I assume you probably want to follow your own pattern in the implementation of this.

**Comment by putyourlightson** [comment]
FYI since 3.2.0-alpha.4 changed the behaviour back to propagating elements immediately on save, this is less of a priority than previously, and possible not even necessary.

> `craft\services\Elements::saveElement()` now immediately propagates elements if $propagate is true, as it used to.

**Comment by brandonkelly** [comment]
I’ll probably land somewhere in between, where most of the time we propagate over a background task. But there were cases where the blanket approach was an issue.

**Comment by putyourlightson** [comment]
Ok, I'll wait and see where this ends up, thanks!

**Comment by brandonkelly** [comment]
Added `propagateElements()` for the next 3.2 Alpha release.

**Comment by putyourlightson** [comment]
Thanks Brandon!
