### ISSUE TITLE
Pages not working for one specific locale

### ISSUE THREAD

**Issue by robm2002** [craftcms/cms#4146]
### Description
I've changed the default locale from `en_us` to `en_au` in the system, and weirdly, all `en_us` sub-pages (e.g. uat.netohq.com.au/us/pricing) aren't working (404). The home page (uat.netohq.com.au/us) is working fine. Also, sub-pages for all other locales are working fine too.

Here's what I've updated:

**Locales settings page**
I've dragged Australian English to the top, to make it the primary locale. U.S. English is second in the list (followed by a few others).

**Custom properties file—default.properties**
This file allows us to deploy our local changes across our UAT, staging, and production environments.
 
```
config.base_url = ~
config.base_url.with_proto = https://${config.base_url}
config.base_path = /var/www/vhosts/netohq

config.site_url.au = ${config.base_url.with_proto}/
config.site_url.us = ${config.base_url.with_proto}/us/
config.site_url.hk = ${config.base_url.with_proto}/hk/
config.site_url.sg = ${config.base_url.with_proto}/sg/
config.site_url.my = ${config.base_url.with_proto}/my/
config.site_url.nz = ${config.base_url.with_proto}/nz/
```

**craft/config/general.php**
```
'siteUrl' => [
    'en'    => '${config.site_url.au}',
    'en_au' => '${config.site_url.au}',
    'en_hk' => '${config.site_url.hk}',
    'en_sg' => '${config.site_url.sg}',
    'ms_my' => '${config.site_url.my}',
    'en_us' => '${config.site_url.us}',
    'en_nz' => '${config.site_url.nz}'
],

'rootUrl' => '${config.base_url.with_proto}/',
'defaultLocale' => '${config.site_url.au}',
```
 
**public folder**
Originally had "au" folder with the necessary `htaccess` and `index.php` files. Renamed this to `us`, and changed the `define('CRAFT_LOCALE', 'en_au')` line to `define('CRAFT_LOCALE', 'en_us')`.

I even tried setting up a brand new section, and encountered the same problem—uat.netohq.com.au/us/testpage doesn't work, but all other locales work fine (e.g. uat.netohq.com.au/nz/testpage).

**Additional info**
- All of the US pages are active
- Tried clearing caches

Can you guys help? Been trying to figure this out for almost 2 days, and it's driving me insane.

### Additional info

- Craft version: 2.7.4
- PHP version: 7.1.26

**Comment by brandonkelly** [comment]
Please contact us at support@craftcms.com with SSH / FTP credentials, and we can help look into it from there.
