### ISSUE TITLE
Bug: Site Order Randomly Changes Between Site Selection in Globals

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#4147]
### Description
In the "Globals" section of the control panel the order of sites listed in the site dropdown field changes between selecting a particular site.

### Steps to reproduce
For a multi-site setup with a number of sites configured (e.g. ~5 sites)
1. Go to the "Globals" section in the control panel
2. Click on the "Sites" dropdown - note the site order
3. Select a site
4. Click on the "Sites" dropdown once the page refreshes - note the order (which should have changed compared to step 2)

- Craft version: 3.1.22

**Comment by richhayler** [comment]
On its way to you now...

**Comment by richhayler** [comment]
Looks like this may only be an issue when no custom order has been applied to the default "Site Group". I only have one site group but after I specified a custom sort order it appears that new order was respected each time I selected a different site in the dropdown list within the "Globals" section.

**Comment by richhayler** [comment]
It would be interesting to understand what order craft applies to listed sites if no custom order has been set for the default site group. Looking at my above screenshots and as far as I can tell it doesn't appear this is alpha numerically or by site ID?

**Comment by richhayler** [comment]
A "default" order for "all sites" or a site group where no custom order is set would probably make sense to be alpha numeric with the exception of placing the specified "primary site" at the top of the list.

**Comment by andris-sevcenko** [comment]
There's still an order. Looking at the files you sent over it seems like that was overwritten at some point. Trying to see if I can reproduce borking the sort order locally now.
