### ISSUE TITLE
Can't create field groups (even with all plugins disabled)

### ISSUE THREAD

**Issue by proimage** [craftcms/cms#4148]
### Description
I started having a problem the other day with Neo (I know, this is Craft's repo, bear with me) where the block groups were disappearing after saving the Neo field. [It was (supposedly) patched](https://github.com/spicywebau/craft-neo/issues/207), and I've applied the patch.

However, not only does it seem like Neo was having trouble, but the entirety of Craft as well. When I try to create a regular Field Group (for regular Craft fields—nothing related to Neo), I get an "404 Not Found" error page. I've disabled every single plugin I had installed, and it still happens. Here's the first bit of the error page:

```
HTTP 404 – Not Found – yii\web\NotFoundHttpException
Template not found: settings/fields/null
1. in C:\Users\____\Projects\____\vendor\craftcms\cms\src\controllers\TemplatesController.php at line 70
61626364656667686970717273747576777879     * @param string $template
     * @param array $variables
     * @return Response
     * @throws NotFoundHttpException if the requested template cannot be found
     */
    public function actionRender(string $template, array $variables = []): Response
    {
        // Does that template exist?
        if (!$this->getView()->doesTemplateExist($template)) {
            throw new NotFoundHttpException('Template not found: ' . $template);
        }
 
        // Merge any additional route params
        $routeParams = Craft::$app->getUrlManager()->getRouteParams();
        unset($routeParams['template'], $routeParams['template']);
        $variables = array_merge($variables, $routeParams);
 
        return $this->renderTemplate($template, $variables);
    }
```

### Steps to reproduce

1. Not sure it will happen on a fresh install, but go to Settings -> Fields
2. Click the "+ New Group" button
3. Type in a name and click "Ok".
4. Bask in the error page.

### Additional info

- Craft version: 3.1.22
- PHP version: 7.0.28
- Database driver & version: Ver 15.1 Distrib 10.1.31-MariaDB, for Win32 (AMD64)
- Plugins & versions: all disabled.

**Comment by brandonkelly** [comment]
Can you try running `./craft project-config/rebuild` and see if that helps?

**Comment by proimage** [comment]
Ok, so this was (perhaps obviously from the OS paths) on my local environment. When the problem occurred, I temporarily shifted database-related work (creating fields, etc) over to the remote dev server. Before trying your suggested fix, I wanted to make sure local was in sync with dev, so I committed on dev (only `config/project.yaml` had changed) and pulled locally. Then I went to see if I could still recreate the issue locally.

However, it seems like pulling that updated `project.yaml` already fixed the issue, and I'm guessing that's effectively the same as rebuilding, as long as I'm pulling from an intact and working environment. :)

Thanks anyway—you rock!

**Comment by brandonkelly** [comment]
Yeah there’s always going to be potential for bad things to happen if your database is out of sync with `project.yaml`. Probably still worth running that `project-config/rebuild` command just in case.

**Comment by proimage** [comment]
Done. Looks like most of the changes are like `[setting_name]: true` -> `[setting_name]: '1'` and the like.

**Comment by brandonkelly** [comment]
Yeah you can safely ignore those changes, they equate to the same thing.
