### ISSUE TITLE
craft command line tool should return non-0 on failure

### ISSUE THREAD

**Issue by marionnewlevant** [craftcms/cms#4153]
### Description
The craft command line tool returns 0 even when it fails because e.g. the php version is less than 7.0

This is makes my automated deploy think it has succeeded when it hasn't.

**Comment by brandonkelly** [comment]
Craft was already returning `0` or `1` for all console actions, but if PHP was under 7.0 that was the one exception. Fixed for the next release!

**Comment by marionnewlevant** [comment]
`console/controllers/ProjectConfigController.php` returns `ExitCode::OK` even when:
> Your `project.yaml` file was created for different versions of Craft and/or plugins than what’s currently installed. Try running `composer install` from your terminal to resolve.

or

> Craft is not configured to use project.yaml. Please enable the 'useProjectConfigFile' config setting in config/general.php.

Which I don't think it should. (I want my automated deploy to fail for these sorts of things).
