### ISSUE TITLE
Prevent the use of '/actions' as a URI segment as it is reserved by the system

### ISSUE THREAD

**Issue by brady-lapine** [craftcms/cms#4154]
### Description
For our Craft site, a section was created named Actions, and the system automatically populated the "Entry URI Format" with `actions/{slug}` which lead to a great deal of confusion on my end when I tried to view the template I just created and was greeted with a 404 error.

After some research, I think that I have discovered that [`actions` is a reserved URI segment by the system](https://docs.craftcms.com/v3/config/config-settings.html#actiontrigger). If this is the case I would think that the system should prevent people from attempting to use it as part of their own URI formats.

### Steps to reproduce

1. Create a site section named "Actions"
2. Make sure the Entry URI Format is `actions/{slug}`
3. Try to access a template at that URI

### Additional info

- Craft version: Craft Pro 3.0.40
- PHP version: 7.3.1
- Database driver & version: MySQL 5.7.24
- Plugins & versions:

**Comment by jan-dh** [comment]
Just ran into this. If it's reserved or you shouldn't be using this, please give a warning of some sort or just prevent me from saving this as a route.

**Comment by brandonkelly** [comment]
Just added this for today’s 3.2.10 release!

**Comment by jan-dh** [comment]
Thank you!

**Comment by brandonkelly** [comment]
Whoops, just saw @gtettelaar’s PR and realized I forgot to fix this for section URI formats. (I only fixed it for routes defined in Settings → Routes.) Will review his PR now and get that half of the fix in as well.

**Comment by brandonkelly** [comment]
Now definitely fixed :)
