### ISSUE TITLE
Craft 3 breaks with .rocksdb

### ISSUE THREAD

**Issue by mdunnerstick** [craftcms/cms#4159]
AWS creates a database by default called .rocksdb.

On the server, if ".rocksdb" is present, Craft CMS will not work.  It will manifest in different ways, such as uploading assets.  Or the site itself won't load.

The fix is to delete .rocksdb:
cd /var/lib/mysql/
sudo rm -rf .rocksdb

But AWS keeps adding it by default.  

I believe the issue is this db begins with a "." and it freaks out Craft.

The real fix needs to be that Craft CMS doesn't freak out.

**Comment by brandonkelly** [comment]
Do you have an asset volume pointing to the same directory that contains that file, or something like that?

**Comment by mdunnerstick** [comment]
While unrelated to Craft, this URL documents the issue that Craft is also having:
https://bugzilla.redhat.com/show_bug.cgi?id=1530511

The work around is to delete .rocksdb.  But that isn't exactly a fix, since .rocksdb gets automatically added whenever you update AWS.

In the default AWS setup for EC2, MySQL will be here:
/var/lib/mysql/

Here's same contents in the directory:

drwx------  2 mysql mysql     8192 Apr  1 19:09 .rocksdb
-rw-rw----  1 mysql mysql    16384 Apr 18 21:53 aria_log.00000001
-rw-rw----  1 mysql mysql       52 Apr 18 21:53 aria_log_control
-rw-rw----  1 mysql mysql    10538 Apr 18 21:53 ib_buffer_pool
-rw-rw----  1 mysql mysql 79691776 Apr 22 18:32 ibdata1
-rw-rw----  1 mysql mysql 50331648 Apr 22 18:32 ib_logfile0
-rw-rw----  1 mysql mysql 50331648 Apr 22 18:32 ib_logfile1
-rw-rw----  1 mysql mysql 12582912 Apr 18 21:55 ibtmp1
-rw-------  1 mysql mysql  1298388 Apr 22 18:46 log000000000009.tokulog29
-rw-rw----  1 mysql mysql        0 Mar 26 13:05 multi-master.info
drwx------  2 mysql mysql     4096 Mar 26 13:05 mysql
srwxrwxrwx  1 mysql mysql        0 Apr 18 21:55 mysql.sock
-rw-rw----  1 mysql mysql       16 Mar 26 13:05 mysql_upgrade_info
drwx------  2 mysql mysql       20 Mar 26 13:05 performance_schema
-rw-rw----  1 mysql mysql    24576 Apr 18 21:55 tc.log
-rw-rw----  1 mysql mysql    16384 Mar 26 13:05 tokudb.directory
-rw-rw----  1 mysql mysql    16384 Mar 26 13:05 tokudb.environment
-rw-------  1 mysql mysql        0 Mar 26 13:05 __tokudb_lock_dont_delete_me_data
-rw-------  1 mysql mysql        0 Mar 26 13:05 __tokudb_lock_dont_delete_me_environment
-rw-------  1 mysql mysql        0 Mar 26 13:05 __tokudb_lock_dont_delete_me_logs
-rw-------  1 mysql mysql        0 Mar 26 13:05 __tokudb_lock_dont_delete_me_recovery
-rw-------  1 mysql mysql        0 Mar 26 13:05 __tokudb_lock_dont_delete_me_temp
-rw-rw----  1 mysql mysql    16384 Mar 26 13:05 tokudb.rollback
drwx------  2 mysql mysql     8192 Apr  1 19:09 mycraftdb


The craft database (mycraftdb) is in the same folder as the .rocksdb database.  Because .rocksdb begins with a dot, Craft thinks it is a column name.  And you get theses weird "#mysql50#.rocksdb" messages.  And the Craft framework implodes.


In terms of waht was built, you basically just follow Amazon's EC2 default setup procedures step by step, including Step 3 for the MySQL database:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-lamp-amazon-linux-2.html

**Comment by brandonkelly** [comment]
There are only a few places where Craft will iterate through files on the filesystem:

- When determining the last modified time of a directory that is getting published to `web/cpresources/`.
- When finding template files to list as auto-suggestions for Template inputs in the Control Panel
- When indexing a Local asset volume

So there shouldn’t ever be a reason why Craft would even know that you're `.rocksdb` file exists, unless you have pointed the [CRAFT_TEMPLATES_PATH](https://docs.craftcms.com/v3/config/php-constants.html#craft-templates-path) constant at your project root, or created a Local volume pointed at that, or something like that.

**Comment by mdunnerstick** [comment]
I did the default composer install installation.  No special nothing for paths.

It's definitely happening though... completely reproducible using the steps above.  I have two systems now built the same way.  Both have the issue.

I don't think it is Craft's fault even.  It think it is a core MySQL fault.  But it is affecting Craft.  If you see that redhat bugzilla documentation above, people have been updating their systems to work around MySQL's issue with this....

**Comment by brandonkelly** [comment]
That bug refers to two cases where `.rocksdb` is problematic:

- When a `SHOW DATABASES` query is executed, which Craft never does
- When the `mysqldump` command is run ([comment 12](https://bugzilla.redhat.com/show_bug.cgi?id=1530511#c12)), which Craft will run when making a database backup.

Craft will only ([optionally](https://docs.craftcms.com/v3/config/config-settings.html#backuponupdate)) make a database backup when performing an update, or when you’ve manually initiated one from the Database Backup utility, so it’s still not clear that Craft is at fault here. Maybe `mysqldump` is being run automatically via a Cron job or something?

**Comment by mdunnerstick** [comment]
Thanks.  Hmm... this is an out of the box Craft 3 installation.  And an out of the box EC2 installation.
Nothing further has been added or adjusted.  Just run the default Craft composer setup in the EC2 environment.

One area where Craft clearly breaks is upon uploading images in the CMS.

**Comment by brandonkelly** [comment]
What is your volume’s File System Path setting set to?

**Comment by MaffooBristol** [comment]
I had this problem with an install, and then deleted the rocksdb reference, which made it all work properly. However, for some reason it has reappeared suddenly, and I've found myself having issues with `{{ getCsrfInput() }}` where I get 500 internal errors when trying to render the template

**Comment by MaffooBristol** [comment]
As an additional tidbit, I've found that it seems to have been included in AWS Amazon Linux's version of MariaDB, but trying to remove just the RocksDB part of it causes yum to freak out:

```
Removing:
 mariadb-rocksdb-engine                             x86_64                    3:10.2.10-2.amzn2.0.3                    @amzn2extra-lamp-mariadb10.2-php7.2                     13 M
Removing for dependencies:
 mariadb-backup                                     x86_64                    3:10.2.10-2.amzn2.0.3                    @amzn2extra-lamp-mariadb10.2-php7.2                     22 M
 mariadb-cracklib-password-check                    x86_64                    3:10.2.10-2.amzn2.0.3                    @amzn2extra-lamp-mariadb10.2-php7.2                    7.3 k
 mariadb-gssapi-server                              x86_64                    3:10.2.10-2.amzn2.0.3                    @amzn2extra-lamp-mariadb10.2-php7.2                     15 k
 mariadb-server                                     x86_64                    3:10.2.10-2.amzn2.0.3                    @amzn2extra-lamp-mariadb10.2-php7.2                     82 M
 mariadb-server-utils                               x86_64                    3:10.2.10-2.amzn2.0.3                    @amzn2extra-lamp-mariadb10.2-php7.2                     11 M
 mariadb-tokudb-engine                              x86_64                    3:10.2.10-2.amzn2.0.3                    @amzn2extra-lamp-mariadb10.2-php7.2                    2.3 M
```

I'm struggling to know whose real position it is to fix this combination of wonkiness but I don't think that Craft on Amazon Linux is such an edge case that it shouldn't be addressed on a Craft level.

The installation being odd is not too bad because I can just remove and then try again, but seeing as the CSRF token is being used to do basic `contact-form` stuff, which would actually break my site completely for anon users if Amazon decides to re-add it.

Obviously in hindsight I should've just stuck with spinning up an Ubuntu box rather than Amazon Linux but I thought I'd give it a punt...!

Anything that could be considered as to why Craft specifically is not liking this would be really helpful. Thanks

**Comment by angrybrad** [comment]
Can someone who is able to reproduce this, do so with devMode enabled, then send the zipped results of the `storage/logs` folder over to support@craftcms.com?  Alternatively, you can share SSH/Craft CP credentials via the same means as well and we can look into it that way.

**Comment by MaffooBristol** [comment]
Thanks @angrybrad - I'll create a reproducible instance tomorrow (quite late now in my timezone) and send it over, cheers for the reply

**Comment by MaffooBristol** [comment]
@angrybrad @brandonkelly I've sent an email to support@ with ssh login details and a link to a running instance that shows the broken CSRF functionality as well as a hopefully reproducible broken installation if you install craft via composer and run `./craft setup` anywhere in the file system. If you delete (or probably better to move) the `/var/lib/mysql/.rocksdb` folder, you should be able to see the `/csrf` page spring into life again and installations work properly. Please let me know if there's anything further I can do to help, thanks.

**Comment by angrybrad** [comment]
@MaffooBristol Thanks for that, Matt. This does look like a legit MariaDB bug (possibly in conjunction when using RedHat distro).

https://bugzilla.redhat.com/show_bug.cgi?id=1530511

https://jira.mariadb.org/browse/MDEV-12451

I think it's reasonable to expect that if Craft queries MySQL's information schema that it should be able to do so without getting any errors.

I tried a few workarounds on our end, but ultimately they were hacky and brittle.

One thing to do on the server-side to fix the problem while the bug exists, though, is to edit `my.cnf` and add this under `[mysqld]`:

```
ignore-db-dir='.rocksdb'
```

That will instruct MySQL to ignore that `.rocksdb` folder on the file system when taking into account queries.

You'll likely need to restart the mysql service after making that change for it to pick up.
