### ISSUE TITLE
Element query gives error on ORDER BY after update from 3.1.13 to 3.1.23

### ISSUE THREAD

**Issue by divyan** [craftcms/cms#4160]
### Description
A regular element query is giving an error on the ORDER BY clause after updating from 3.1.13 to 3.1.23.

It seems it's not listening to my orderBy() and it's doing a duplicate field string with the element.dateCreated: "ORDER BY `elements`.`dateCreated elements`.`dateCreated` DESC"

Element query:
craft.entries.section('pages').orderBy('dateCreated asc').limit(5).all()

Error:
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'elements.dateCreated elements.dateCreated' in 'order clause'
The SQL being executed was: SELECT `elements`.`id`, `elements`.`fieldLayoutId`, `elements`.`uid`, `elements`.`enabled`, `elements`.`archived`, `elements`.`dateCreated`, `elements`.`dateUpdated`, `elements_sites`.`slug`, `elements_sites`.`uri`, `elements_sites`.`enabled` AS `enabledForSite`, `entries`.`sectionId`, `entries`.`typeId`, `entries`.`authorId`, `entries`.`postDate`, `entries`.`expiryDate`, `content`.`id` AS `contentId`, `content`.`title`, `content`.`field_adviceLineNumber`, `content`.`field_adviceLineText`, `content`.`field_cookieNotice`, `content`.`field_cookieAgree`, `content`.`field_copyright`, `content`.`field_email`, `content`.`field_footerTextContent`, `content`.`field_footerTextHeading`, `content`.`field_housenumber`, `content`.`field_housenumber_extra`, `content`.`field_compactDescription`, `content`.`field_postalcode`, `content`.`field_seo`, `content`.`field_street`, `content`.`field_phone`, `content`.`field_city`, `structureelements`.`root`, `structureelements`.`lft`, `structureelements`.`rgt`, `structureelements`.`level`, `structureelements`.`structureId`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`, `structureelements`.`structureId`
FROM `elements` `elements`
INNER JOIN `entries` `entries` ON `entries`.`id` = `elements`.`id`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `content` `content` ON `content`.`elementId` = `elements`.`id`
LEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `elements`.`id`) AND (EXISTS (SELECT *
FROM `structures`
WHERE (`id` = `structureelements`.`structureId`) AND (`dateDeleted` IS NULL)))
WHERE (`elements_sites`.`siteId`='1') AND (`content`.`siteId`='1') AND (`elements`.`archived`=FALSE) AND (((`elements`.`enabled`=TRUE) AND (`elements_sites`.`enabled`=TRUE)) AND (`entries`.`postDate` <= '2019-04-19 07:55:54') AND ((`entries`.`expiryDate` IS NULL) OR (`entries`.`expiryDate` > '2019-04-19 07:55:54'))) AND (`elements`.`dateDeleted` IS NULL) AND (`elements_sites`.`enabled`=TRUE) AND ((`elements`.`id` IN (SELECT `sources1`.`targetId`
FROM `relations` `sources1`
WHERE `sources1`.`sourceId`='86')) OR (`elements`.`id` IN (SELECT `targets1`.`sourceId`
FROM `relations` `targets1`
WHERE `targets1`.`targetId`='86')))
**ORDER BY `elements`.`dateCreated elements`.`dateCreated` DESC**
LIMIT 50) `subquery`
INNER JOIN `entries` `entries` ON `entries`.`id` = `subquery`.`elementsId`
INNER JOIN `elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `content` `content` ON `content`.`id` = `subquery`.`contentId`
LEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `subquery`.`elementsId`) AND (`structureelements`.`structureId` = `subquery`.`structureId`)
ORDER BY `elements`.`dateCreated elements`.`dateCreated` DESC

Error Info: Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'elements.dateCreated elements.dateCreated' in 'order clause'
)
`

### Steps to reproduce

1. Put this in a twig template {%  set items = craft.entries.section('pages').orderBy('dateCreated asc').limit(5).all() %} (also gives an error without orderBy )

### Additional info

PHP version | 7.1.25
MySQL 5.7.24
Craft Pro 3.1.23

**Comment by brandonkelly** [comment]
@divyan Take it you got this sorted?
