### ISSUE TITLE
Matrix field :notempty: field problems

### ISSUE THREAD

**Issue by mofman** [craftcms/cms#4161]
### Description
Essentially the `:notempty:` keyword only works when the field is virgin.
Once you have added a block to the field and then saved and then return later to remove all blocks, the  `:notempty:` keyword no longer works and entries will still appear even if they have no blocks. 

```twig
{% set events = craft.entries.section('whatsOn').eventSuites(':notempty:').all() %}

<h1>Show events which have suites</h1>
{% for event in events %}
    {{ event.title }}<br />
    {{ event.eventSuites|length }}<br />
{% endfor %}

<h1>Show events which do not have suites</h1>
{% set events = craft.entries.section('whatsOn').eventSuites(':empty:').all() %}

{% for event in events %}
    {{ event.title }}<br />
    {{ event.eventSuites|length }}<br />
{% endfor %}
```

### Additional info

- Craft version: 3.1.23
- PHP version: 7.2
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Fixed for the next release. Thanks for reporting!
