### ISSUE TITLE
Account activation issues

### ISSUE THREAD

**Issue by skoften** [craftcms/cms#4165]
We've experienced some issues with account activation. Unfortunately I can't reproduce it exactly, but I wanted to inform about it. 

This is what happened;

- a user emailed us saying he could not activate his account
- he also told us that he did receive and clicked the activation email
- we've resent the activation email to him to be sure
- he confirmed he received it again and clicked the activation link
- the account was still pending though
- we've manually activated it so solve the issue at that moment

Then we did some testing and ran into the same issue;

- we deleted our test-acount via the backend
- created a new one on the frontend
- we received the activation email
- clicked the link
- got redirected to the success template
- account was still pending

So we tried a fresh email address that didn't exist in the database yet. This worked without any issues and the account got activated.

I then did a query on the user table to check any data existed with our test email address, which gave me this;

<img width="660" alt="Screenshot 2019-04-22 at 20 06 49" src="https://user-images.githubusercontent.com/1286410/56518274-4bc41f00-653f-11e9-93a7-18243fdcab62.png">

After deleting these rows the registration & activation process worked fine.  So, my question here is; how can this happen and how can we prevent it?

Thanks!

- Craft version: 3.1.23
- PHP version: 7.2
- Database driver & version: MySQL 5.7.25

**Comment by brandonkelly** [comment]
Why did you feel you needed to delete those rows? What is the full SQL query you executed?

You should make sure to also delete those same IDs in the `elements` table, and in the future don’t delete rows in the `users` table directly.

**Comment by skoften** [comment]
Quick update; I did some more digging and realised we've been using a avatar plugin since a few days: https://github.com/hashtagerrors/userinitialsphoto 

This plugin is causing the issue, I will submit a new issue there. 

PS. I did a "delete from user where email = 'xxx' query. I also have deleted the element id's from the elements table. Should be fine now?

**Comment by skoften** [comment]
PS. the accounts that are "affected" by this plugin, won't get activated anymore. Even resending the activation email results in a pending account; the first time the link is clicked the user is redirected to the success template, but not logged in (which we have enabled in the general config). But also, the account is still pending in the CP.

So my concern now is that we have hundreds of pending accounts in the database, which cannot be activated, even when the plugin is disabled. The table data of this user look like this;

<img width="736" alt="Screenshot 2019-04-23 at 12 06 21" src="https://user-images.githubusercontent.com/1286410/56573118-b4071500-65c0-11e9-8f5b-02d91334d02f.png">

I am looking for a way to let people activate them again...

**Comment by brandonkelly** [comment]
That example row is missing its `verificationCode` and `verificationCodeIssuedDate` values, which is why Craft is redirecting them when they click an activation link (per the [invalidUserTokenPath](https://docs.craftcms.com/v3/config/config-settings.html#invalidusertokenpath) config setting).

If those are still null after you’ve resent an activation email, then something else must be affecting this. Do you have any other plugins installed, or a custom module?

**Comment by skoften** [comment]
When I resend the verification email both **verificationCode** and **verificationCodeIssuedDate** are filled again. The email is received, but after clicking the link the account doesn't get activated, user is not logged in automatically, but is redirected to the success template. And: verificationCode and verificationCodeIssuedDate are both empty again.

We have some plugins, but as far as I can see none can affect this proces. 

And the weird part is, that accounts that are created with the User Initials Photo plugin removed, get activated just fine.

Anything else I can check?

PS. this is my list of plugins;

<img width="820" alt="Screenshot 2019-04-23 at 13 24 07" src="https://user-images.githubusercontent.com/1286410/56577456-5b894500-65cb-11e9-9341-67051e3ba4ef.png">

**Comment by brandonkelly** [comment]
I’ll spin up a test with that plugin installed and see if I can reproduce.

**Comment by skoften** [comment]
Awesome!

In the meantime I did some extra research and I dug into the User controller and the activation process.  Apparently **unverifiedEmail** needs to be filled in before and account can change/update  from **pending** to not begin pending.

The thing is: all accounts that are having this issue (which are created when the User Initials Photo plugin was activated), have a NULL value on the unverifiedEmail column.

So, when I manually updated the unverifiedEmail to the same value as the email column with MySQL, the account is activated successfully after resending the activation email.

**Comment by brandonkelly** [comment]
I’m not able to reproduce any abnormalities when activating user accounts with that plugin installed. Not sure what else to suggest though. Can you email your `composer.json` and `composer.lock` files, and a database backup, over to support@craftcms.com and reference this GH issue? We can look into it from there.

**Comment by brandonkelly** [comment]
Right I had mentioned those columns in https://github.com/craftcms/cms/issues/4165#issuecomment-485751919. But you said they get re-filled when sending a new activation email, and yet the activation links still wouldn't work?

**Comment by skoften** [comment]
**verificationCode** and **verificationCodeIssuedDate** are indeed filled after resending the activation email, but the **unverifiedEmail** is NULL and doesn't get a value after resending the mail.

I will grab some files and send it to you asap. Thanks!

**Comment by Mosnar** [comment]
Not sure if it's related or helpful at all, but I actually have an long outstanding issue on a completely up-to-date Craft 2 site that sounds suspiciously like this. The user receives the activation email, they click the link (and in this case, they are logged in successfully, according to the client) but the account is never actually activated (I verified this myself). Similarly, I was never able to reproduce the issue with my own testing and it only seems to happen occasionally. Activating the user manually from the CP works as expected. Happy to provide more data if it helps. Seems like a very specific combination of events trigger this and it may have gotten carried over from Craft 2.

**Comment by skoften** [comment]
@brandonkelly I've sent you an email with all required data so you can do some checks.

For now the cause seems to be a missing value for **unverifiedEmail**, after creating the account with the User Initials Plugin activated. When creating an account with the plugin disabled unverifiedEmail has a valid value.

The solution would be to do a check on unverifiedEmail and updating it in case it's NULL, before creating & sending the activationUrl.

**Comment by angrybrad** [comment]
Created a pull request that fixes this in the plugin here: https://github.com/hashtagerrors/userinitialsphoto/pull/4
