### ISSUE TITLE
Add additional caveat about enabling Project Config in Craft 2 to 3 migrations

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/cms#4168]
### Description

This is a bit subjective and opinionated but I don't know if it's worth updating the docs either on the Craft 2 to 3 section or Project Config caveats of having project config enabled for a project that is being migrated from Craft 2 to 3?

For a reasonably large Craft 2 project, you are likely to be testing the migration path regularly and therefore will keep overwriting your development database with the production DB from the existing Craft 2 site, having project config enabled will just be a headache as new changes will be generated, which are just because the DB was refreshed i.e. uid value changes. In addition, you will probably come across some other issues which I've personally experienced which cause out of sync or wrong version errors when deploying to a staging environment etc etc, even when using `./craft project-config/sync`.

The summary of the above, to save others discovering the hard way, it might be worth adding a note about recommending project config being disabled for migrating an existing Craft 2 site and enabled after the migration is complete and deployed to the production environment to synchronise all environments accordingly.

I believe the `useProjectConfigFile` config is now default false (I think it may have been true originally), but might be worth mentioning still?

Thoughts welcome! It is just my opinion based on recent experiences!

**Comment by brandonkelly** [comment]
Yeah so originally when Craft 3.1 latched, we updated the default Craft project to enable `useProjectConfigFile`, but later realized it was better to leave it disabled, and let people opt into it when they’re ready. Step 2 under [Enabling the Project Config File](https://docs.craftcms.com/v3/project-config.html#enabling-the-project-config-file) says to ensure you’re all up-to-date, which I’d say covers this suggestion.

I’ll update the [useProjectConfigFile](https://docs.craftcms.com/v3/config/config-settings.html#useprojectconfigfile) config setting docs to point to those steps though, as well as add a comment to the default `config/general.php` linking to it.
