### ISSUE TITLE
Save user controller returning current password error with incorrect key?

### ISSUE THREAD

**Issue by samhibberd** [craftcms/cms#4169]
### Description

The save user controller requires the current password to update email, username or password. It correctly returns the error if currentPassword is not set or incorrect, although it requires an input called `password` is sent to the controller, but returns and error with the key `currentPassword`. Not sure if / why this is, as for us it's causing some complication when adding errors to forms using javascript. 

Should it not be named the same `password`?

### Steps to reproduce

1. Create a front end template profile form template, posting using ajax when requesting a password change but send invalid current password.
2. Check response.

### Additional info

- Craft version: 3.1.23
- PHP version: 7.1.25
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
Agree that’s a bit awkward. As of the next release Craft will check for an input named `currentPassword` in addition to `password`.

**Comment by samhibberd** [comment]
Perfect! Thanks @brandonkelly
