### ISSUE TITLE
State Abbreviation for Oregon being treated as a conditional

### ISSUE THREAD

**Issue by kmmartinez** [craftcms/cms#4170]
### Description
I've got an entries query where I'm trying to filter by a custom field: craft.entries.section('dealers').stateProvince('OR')…. All other two-letter state abbreviations work fine, but it appears that OR is being interpreted as a conditional operator instead of a string.
All other states are pulling the right counties, Oregon is pulling every single county for every state.
It also does this on search in the CP. OR should show a test county, but it doesn't. The first image is just showing an OR county exists.

<img width="1094" alt="Screen Shot 2019-04-22 at 3 39 02 PM" src="https://user-images.githubusercontent.com/33701090/56589814-93809000-65ab-11e9-8ad6-49d067acb16a.png">
<img width="1069" alt="Screen Shot 2019-04-22 at 3 38 36 PM" src="https://user-images.githubusercontent.com/33701090/56589815-93809000-65ab-11e9-8e89-27c3cca2d2f2.png">

```

  {% set stateSlug = craft.app.request.getParam('state') %}

  {% if stateSlug %}

      {% set results = [] %}

      {% for county in craft.entries.section('counties').stateProvince(stateSlug).orderBy('title').all() %}

      {% endfor %}
  {% endif %}
```

### Steps to reproduce

1. Trying to pull in a list of counties (channel) using the stateProvince field based on the state chosen
2. Or create a channel with a state field, set it as OR, then search for it in the CP search bar.

### Additional info

- Craft version: Craft Pro 3.1.23
- PHP version: 7.2.9
- Database driver & version: MySQL 5.6.10

**Comment by brandonkelly** [comment]
What kind of field is `state`?

**Comment by kmmartinez** [comment]
Plain Text

**Comment by brandonkelly** [comment]
Alright, this is a little awkward but the only way to work around this is to change your `stateProvince` param to `stateProvince(['or', stateSlug])`. That way Craft will pull out the first value as the `or` condition glue, and not do anything special with `stateSlug`.

**Comment by kmmartinez** [comment]
That works great. Thank you!
