### ISSUE TITLE
Draft name repeats site name on multiple edits

### ISSUE THREAD

**Issue by jurriaanr** [craftcms/cms#4171]
### Description
When saving an entry as a draft, if you edit the draft to add a note or change the name, the site name is added. This will be done again for every edit.

![draft-edit-bug](https://user-images.githubusercontent.com/7426848/56610059-e7709080-660e-11e9-9eab-05297fc76689.gif)

### Steps to reproduce

1. Make multiple sites (might also happen if there is only 1 site)
2. Add a new entry
3. Save entry as a draft
4. Switch to the current item through version dropdown
5. Switch back to draft and click edit button to add note.
6. Switch to the current item through version dropdown
7. Switch back to draft and click edit button to add note

The site name will now be added twice

### Additional info

- Craft version: Craft Solo 3.1.22
- PHP version: 7.2.10
- Database driver & version: MySQL 5.7.23
- Plugins & versions: No plugins are enabled.

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.
