### ISSUE TITLE
Wrong event date in Live Preview of sub site with German admin panel

### ISSUE THREAD

**Issue by martinhellwagner** [craftcms/cms#4172]
### Description

In our Craft CMS multisite installation, the sub sites frequently display a wrong date in the Live Preview of an event when the admin panel is in German (see first screenshot). In the frontend, however, the date is displayed correctly (see second screenshot). More often than not, the date is just "inverted" in German (instead of _dd/mm_, the format _mm/dd_ – common in English – is displayed), but sometimes a completely wrong date is shown (as in the screenshot below). Note that the problem **only** occurs when the admin panel is in German.

Is there something wrong with the Live Preview of Craft CMS, or does our template have problems with displaying the correct date in the Live Preview? We're using a macro `dateMarkup` to display the dates, which in turn prints the date like so: `{{ startDate | date("d.m.") }}`

### Steps to reproduce

1. Log into your Craft CMS admin panel on a multisite installation
2. Make sure the language of the admin panel is in German
3. Create an event on a sub site
4. Open the Live Preview for this event

### Additional info

- Craft version: Craft Pro 3.1.15
- PHP version: 7.1.25
- Database driver & version: MySQL 5.6.40
- Twig version: 2.6.2

![events-preview](https://user-images.githubusercontent.com/19146752/56655137-36abd500-6692-11e9-8749-6240f743936d.png)
![events-frontend](https://user-images.githubusercontent.com/19146752/56655143-39a6c580-6692-11e9-9533-e86a953e024d.png)

**Comment by brandonkelly** [comment]
What languages are your sites set to? All German?

**Comment by martinhellwagner** [comment]
Yes, the primary site as well as all multisites are set in German. The admin panel is set to English on the primary site, and to German on the multisites.

**Comment by brandonkelly** [comment]
> The admin panel is set to English on the primary site, and to German on the multisites.

By that are you referring to the [defaultCpLanguage](https://docs.craftcms.com/v3/config/config-settings.html#defaultcplanguage) setting? That’s the closest thing Craft has to letting you set a language specifically for the Control Panel in general. But that’s just what should be used as default, for users that haven’t saved their own user account settings yet, which locks them into whatever language is selected in their Preferred Language preference.

**Comment by martinhellwagner** [comment]
We have `'defaultCpLanguage' => 'en'` set in our _general.php_ config file, yes. The editors of the multisites have mostly set German as the language of their admin panel – and that's when the date macro shows wrong dates in the live preview.

**Comment by brandonkelly** [comment]
Do you have any plugins or custom modules installed? I’m guessing that something is initializing the formatter before this line is executed:

https://github.com/craftcms/cms/blob/81e712ccf8f1a9b0a65426c70769229f20dc6b26/src/controllers/EntriesController.php#L447-L448

Probably going to be easiest if you can send us a ticket from your dashboard, and reference this GH issue, and include any custom modules/Composer packages you may have installed.

**Comment by martinhellwagner** [comment]
Done! Sent you a bug report from the dashboard just now. I've attached the `composer.json` file as well. If there's anything else you need, just let me know! 🙂

**Comment by martinhellwagner** [comment]
I've tried sending a bug report from the dashboard just now, but the request errors out:

![Screenshot 2019-04-30 at 15 28 29](https://user-images.githubusercontent.com/19146752/56965514-c7385880-6b5d-11e9-8eb3-8a4e1585dfba.png)

**Comment by brandonkelly** [comment]
Hm, ok, can you just email support@craftcms.com directly? Include `composer.json`, `composer.lock`, a zip of your `templates/` folder, and a database backup, and reference this issue URL in the body.

**Comment by martinhellwagner** [comment]
Done! However, our DB dump is rather huge because of all the multisites (5 GB). Shall I sent it to you anyways?

**Comment by brandonkelly** [comment]
I’d suggest sending it via [WeTransfer](https://wetransfer.com) in that case.

**Comment by martinhellwagner** [comment]
Unfortunately, it is also too big for the free version of WeTransfer (maximum of 2 GB). I've uploaded the DB dump and the `templates` ZIP to Google Drive now and shared the files with support@craftcms.com.

**Comment by brandonkelly** [comment]
We weren’t able to reproduce the bug using the files you’ve sent, but suspect that the issue lies with your macro. Assuming things work correctly on normal front-end requests, we suspect this will resolve itself when you upgrade to Craft 3.2, where Live Preview has been completely rewritten to be simpler and behave identically to normal front-end requests.

**Comment by brandonkelly** [comment]
Worth mentioning, when you do upgrade to Craft 3.2, you’ll have better luck if you update from the console, as one of the migrations takes a few minutes to run due to the size of your database.
