### ISSUE TITLE
Subsequent querying of an asset field returns only the results from the first query

### ISSUE THREAD

**Issue by benjaminkohl** [craftcms/cms#4173]
### Description

When querying an Asset field twice in one template with different sets of criteria, the second query returns the same results as the first.

### Steps to reproduce

Here is one example where this came up:

We have an entry with an asset field (assetField) that contains one image file and one PSB file. We first fetch the image to use as a preview image on the page. This functions as expected.

```
{% set previewImage = item.assetField.kind('image').one() %}
```

Further down the template, we fetch all the files from the same field so that we can create download links.

```
{% set allFiles = item.assetField.all() %}
```

The contents of allFiles is only the one image asset returned in the first preview image query. If we remove the preview image query from the template, the second query returns both the image file and the PSB file as expected.

### Additional info

- Craft version: 3.0.37
- PHP version: 7.3.4
- Database driver & version: MySQL 5.7.25
- Plugins & versions:

Amazon S3	1.0.8
Cookies	1.1.11
CP Field Inspect	1.0.5
Entry Instructions	1.0.4
Hvrcraft	3.0.0-beta.4
Imager	v2.1.4
Inventory	2.0.2
KeyChain	1.0.0
Linkit	1.1.4
Link Vault	3.0.5.3
Minify	1.2.9
Password Policy	1.0.4
Preparse Field	v1.0.6
Redactor	2.1.7
S3 Sync	1.0.6
SAML SSO Service Provider	1.0.6
Sprout Reports	1.0.0-beta.16
Super Table	2.0.14
Typogrify	1.1.16

**Comment by andris-sevcenko** [comment]
This is the expected behavior in Craft 3. See [here](https://docs.craftcms.com/v3/changes-in-craft-3.html#cloning-element-queries).

**Comment by benjaminkohl** [comment]
Ok, thanks. That feels like a "gotcha" that I'm willing to bet many developers are not expecting. Here is what I did to fix our example...

```
{% set assetFieldQuery = item.assetField %}
{% set previewImage = clone(assetFieldQuery).type('image').one() %}
{% set allFiles = clone(assetFieldQuery).all() %}
```

...Versus what I was doing before...

```
{% set previewImage = item.assetField.kind('image').one() %}
{% set allFiles = item.assetField.all() %}
```
