### ISSUE TITLE
Craft Commerce "Add to Cart" error if field with handle 'behaviors' exists

### ISSUE THREAD

**Issue by jasonleelab** [craftcms/cms#4184]
### Description
Cannot add to cart in Craft Commerce if there is a field with handle: `behaviors`.

### Steps to reproduce

1. Create a field called "Behaviors" with handle: `behaviors`
2. Using Craft Commerce, try and add to cart. You'll receive "PHP Fatal Error". Screenshot: https://cl.ly/c855a1cf399e 

### Additional info

- Craft version: 3.1.24
- PHP version: 7.2.1
- Database driver & version: PostgreSQL 11.2
- Plugins & versions: Commerce LITE 2.1.3.1

**Comment by brandonkelly** [comment]
Yeah that make sense, it’s triggering an infinite recursive loop since elements already have a concept of `behaviors`. I’ll mark that as a a reserved field handle.
