### ISSUE TITLE
Specific Lightswitch field doesn't get project-config-sync'ed

### ISSUE THREAD

**Issue by mdominguez** [craftcms/cms#4189]
### Description
The sync command gets executed successfully but this Lightswitch field doesn't get attached to the entry after the sync on the production server. While other lightswitches or fields get sync'ed perfectly... Any idea what's wrong with it?
[view screenshot](https://cl.ly/eac9a7ddf61d)
Lightswitch field => [view screenshot](https://cl.ly/5d7cfe204488)

**Comment by mdominguez** [comment]
Removing and re-adding the field seems to have fixed the issue..

**Comment by brandonkelly** [comment]
Something must have been off about that field. If something like this happens in the future, running the rebuild command is a good first troubleshooting step:

```bash
./craft project-config rebuild
```

**Comment by mdominguez** [comment]
I did but unfortunately didn't resolve the issue
