### ISSUE TITLE
Display notes in plugin change logs less obtrusive

### ISSUE THREAD

**Issue by sebastian-lenz** [craftcms/cms#4190]
### Description

I've just published an update to a plugin and added a note in the change log as described [here](https://docs.craftcms.com/v3/extend/changelogs-and-updates.html#release-notes). The resulting entry within the plugin store however looks like a big warning:

![Bildschirmfoto 2019-04-29 um 15 22 40](https://user-images.githubusercontent.com/2273359/56899019-af47d280-6a92-11e9-8216-54f1e450a276.png)

Changing the css class to `warning` actually produces a less obtrusive styling of the text. I assume that the two are mixed up? Nevertheless, I would not expect a "note" to be indicated by a warning sign.

### Steps to reproduce

1. Publish a plugin with a change log entry containing 
```
> {note} A note.
```
2. Visit plugin in the plugin store

### Additional info

- Craft version: 3.1.24
- PHP version: 7.2

**Comment by brandonkelly** [comment]
What plugin is this?

**Comment by sebastian-lenz** [comment]
It's this plugin right here:
GitHub: https://github.com/sebastian-lenz/craft-linkfield
Plugin store: https://plugins.craftcms.com/typedlinkfield (*)

The corresponding line within the change log is here:
https://github.com/sebastian-lenz/craft-linkfield/blame/master/CHANGELOG.MD#L8

(*) Just noted that the note is not properly displayed in the external plugin store

**Comment by brandonkelly** [comment]
I’ve updated the docs to clarify that `{note}` is more serious than `{warning}`, which is the intended behavior.

If you want to swap to `tip` (what I’d recommend given the content), do this:

1. Create a new local branch off of your 136c7fcc221d8f53ef903be215f2929a19218a69 commit (the current one tagged with `1.0.19`) called `changelog-edit` or something
2. Change `{note}` to `{tip}` in your changelog, and commit the change
3. Go to your plugin’s repo in your terminal and run this command:
    ```bash
    git tag -d 1.0.19
    ```
4. Tag your new commit with `1.0.19`
5. Merge your `changelog-edit` branch into `master`
6. Force-push to GitHub, which will overwrite the 1.0.19 tag here, and cause the Plugin Store to update its indexes and re-download the changelog contents.

**Comment by benjamindavid** [comment]
The issue where the online Plugin Store was not properly showing icons for tips, warning, and notes, should now be fixed.
