### ISSUE TITLE
Cannot make new entry with DateTime value

### ISSUE THREAD

**Issue by Kota-M** [craftcms/cms#4192]
### Description
When I make a new entry with a DateTime field, this error occurs.

PHP Recoverable Error – yii\base\ErrorException
Object of class DateTime could not be converted to string

Due to this error, I cannot make any new entry with DateTime at all.
Could you tell me how to make it?

### Steps to reproduce

1. Make a channel with at least one DateTime field and make it required
2. Try to make a new entry in this channel

### Additional info

- Craft version: 3.0.41
- PHP version: 7.1.2
- Database driver & version: MySQL 5.6.22
- Plugins & versions: Nothing

**Comment by brandonkelly** [comment]
Please search for that error message in your logs (`storage/logs/*`) and paste the stack trace that follows it here.

**Comment by Kota-M** [comment]
The error log is attached on this comment.

[errorlog.txt](https://github.com/craftcms/cms/files/3131450/errorlog.txt)

**Comment by brandonkelly** [comment]
Thanks, now please do this:

1. open `storage\runtime\compiled_templates\3c\3ceb8ef9bd48f6798242cfa99f62316537023cbbe1ef5c5561ec7a3bc8d2af72.php`
2. the top of the file should have a comment that names a template path; make note of that.
3. go to 27. Shortly above that, there should be a comment that looks like this: `// Line XYZ`. Make note of the line number

What is the template name (step 2) and line number (step 3)?

**Comment by Kota-M** [comment]
The top is;
/* __string_template__c68a76ba39ce58390336cc9f8eb59d72d4907b54ab8debe638f7b33da5f7cb5d */

And it is line 1.

**Comment by brandonkelly** [comment]
Ah, right, I just looked a bit further down the stack trace and it’s coming from this line:

https://github.com/craftcms/cms/blob/cbea3303ac55fd22d358760179bd26b9605f4250/src/elements/Entry.php#L972

So, it’s occurring when Craft is generating an entry title, based on a custom Title Format setting.

You must have `{dateFieldHandle}` in one of your entry types’ Title Format settings, which is causing this error. (DateTime objects can’t be output as a string like that – you will need to pass the value through the [atom](https://docs.craftcms.com/v3/dev/filters.html#atom), [rss](https://docs.craftcms.com/v3/dev/filters.html#rss), [date](https://docs.craftcms.com/v3/dev/filters.html#date), [datetime](https://docs.craftcms.com/v3/dev/filters.html#datetime), [time](https://docs.craftcms.com/v3/dev/filters.html#time), or [timestamp](https://docs.craftcms.com/v3/dev/filters.html#timestamp) filter, for example:

```
{dateTimeHandle|date('Y-m-d')}
```

**Comment by Kota-M** [comment]
Yes, it works now. Thank you for helping me.
