### ISSUE TITLE
[Feature Request] Twig filter to convert string to ASCII

### ISSUE THREAD

**Issue by benface** [craftcms/cms#4193]
This would be very useful in addition to the `|kebab` filter to convert a user-entered title or something into a URL-friendly string, just like Craft itself does with slugs when `limitAutoSlugsToAscii` is `true`.

Looks like I'm not alone in wanting this:
- https://craftcms.stackexchange.com/questions/22306/convert-characters-to-ascii
- https://craftcms.stackexchange.com/questions/15297/twig-filter-to-convert-special-characters-to-url-friendly-characters

Thank you for considering it :)

**Comment by brandonkelly** [comment]
Added for the next release!
