### ISSUE TITLE
Fields’ isEmpty() method has been deprecated. Use isValueEmpty() instead.

### ISSUE THREAD

**Issue by jacobgraf** [craftcms/cms#4195]
### Description
Deprecation error in CP. Does not appear to be plugin-related, but core.

### Steps to reproduce

1. Look in deprecation logs to find error...

`Fields’ isEmpty() method has been deprecated. Use isValueEmpty() instead.`

### Additional info

- Craft version: Craft Solo 3.1.24
- PHP version: 7.1.26
- Database driver & version: MySQL 5.7.25
- Plugins & versions:

CKEditor 1.0.0-beta.2
Craft Commerce 2.1.3.1
Events 1.0.1
Field Manager 2.0.5
Linkit 1.1.11
SEOmatic 3.1.49
Smith 1.0.0
Sprout Active 2.0.9
Stripe for Craft Commerce 1.2.1

### Stack Trace

https://pastebin.com/PrKDaADG

**Comment by brandonkelly** [comment]
The deprecation warning is logged from a core field but only if the field type has implemented it as well. 

https://github.com/craftcms/cms/blob/aa862bd7f2ee3a81c692f0b6c4d0aa9f20e85373/src/base/Field.php#L336-L341

What field type is `paragraphBody` ?

**Comment by jacobgraf** [comment]
It's a CKEditor field.

https://plugins.craftcms.com/ckeditor
