### ISSUE TITLE
Table Field Bug?

### ISSUE THREAD

**Issue by fodney** [craftcms/cms#4200]
### Description

I've run into what I think is a bug.  I have a table field that is part of a global.  The table has three columns.  After I enter data into the third column column and hit save the data from the third column populates column 1 as well. If I enter data in col 1 it is overwritten by whatever is in col 3.running 3.1.20.1

### Steps to reproduce

1. Create a table field with three columns
2. try adding data to third column and save

### Additional info

- Craft version: 3.1.20.1 (Solo)
- PHP version: 7.1.28
- OS version: Linux 2.6.32-042stab136.1
- Database driver & version: MySQL 5.6.43
- Image driver & version: GD 7.1.28
- Plugins & versions: 
    - Contact Form 2.2.4
    - Contact Form Honeypot 1.0.2
    - Redactor 2.3.2

**Comment by brandonkelly** [comment]
Hm, that’s odd. Can you please send in your `composer.json` and `composer.lock` files, plus a database backup, over to support@craftcms.com and reference this issue URL? Also point out which global + Table field you are seeing this issue in.

**Comment by fodney** [comment]
Just sent.  Thanks!
