### ISSUE TITLE
Error on user settings page

### ISSUE THREAD

**Issue by NixonGit** [craftcms/cms#4206]
### Description

When accessing the user settings page (/settings/users/settings) the following error is thrown.

`Impossible to access an attribute ("requireEmailVerification") on a null variable.`

```
vendor/craftcms/cms/src/templates/settings/users/settings.html:67

{{ forms.checkboxField({
  label: "Verify email addresses?"|t('app'),
  instructions: "Should new email addresses be verified before getting saved to user accounts? (This also affects new user registration.)"|t('app'),
  name: 'requireEmailVerification',
  checked: settings.requireEmailVerification,
}) }}
```

### Steps to reproduce

1. Access user settings page on a Craft Pro site.

### Additional info

- Craft version: Craft Pro 3.1.24
- PHP version: 7.2.1
- Database driver & version: MySQL 5.6.38
- Plugins & versions: Asset Rev 6.0.2, Cookies 1.1.11, Feed Me 4.1.0, Redactor 2.3.3.2

**Comment by brandonkelly** [comment]
Only way that could happen is if your project config is somehow missing its `users` key. I’ve updated the template to make it more defensive about that, for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#30b4b1c351cbc24b26cf54b91bb06a9af71f004c as 3.1.25",
  "...": "..."
}
```

Then run `composer update`.
