### ISSUE TITLE
Image thumbnail is not refreshed after image editor changes

### ISSUE THREAD

**Issue by benface** [craftcms/cms#4212]
### Steps to reproduce

1. In an Assets field, double-click on an image (assuming at least one image was selected) to open its modal, then click on "Edit" to open the image editor.
2. Make any obvious modification to the image, for instance a 90-degree rotation, then click on "Save".
3. When the image editor closes, notice the modal's large thumbnail refreshes to display the modified image, but the list item's thumbnail doesn't refresh. Even when you close the modal, it doesn't refresh, while it does in the Assets page of the CP.

This is a serious issue for one of my clients, because they upload and manage tons of images and frequently have to rotate some of them, and right now they can't see which ones have been done when there's a very long list.

### Additional info

- Craft version: 3.1.25
- PHP version: 7.3.3
- Database driver & version: MySQL 5.7.25

**Comment by richardfrankza** [comment]
We are seeing this behaviour in Craft CMS 3.5.15.1 where the asset doesn't update (standard asset field or one within a matrix). Has there been a regression?

**Comment by brandonkelly** [comment]
I just tested and it’s working fine on my end. The small thumbnail doesn’t refresh until the editor HUD is closed (whether you click Save on Cancel).

**Comment by richardfrankza** [comment]
Ahh Brandon, I'm clicking Save As New Asset. Is this intended behaviour?

https://www.loom.com/share/9bd83c4fdb924fe692d8805b909e6ef2

**Comment by brandonkelly** [comment]
In that case yes, because you aren’t updating the current asset when you do that.

**Comment by richardfrankza** [comment]
Ok thanks. Take it or leave it but that wasn't entirely intuitive for me.
