### ISSUE TITLE
Cache tag database exception

### ISSUE THREAD

**Issue by tim-pixeldeluxe** [craftcms/cms#4218]
### Description
Whenever I place cache tags around a specific category query I get a database exception.

Code that causes the error:
```twig
{% set themes = craft.categories.group('themes').level(1).image(':notempty:').all() %}
```

Error:
https://pastebin.com/yPVR6Xm8

### Steps to reproduce

1. Place cache tags around categorie query
2. Load the page

### Additional info

- Craft version: 3.1.25
- PHP version: 7.1.6
- Database driver & version: MySQL 5.5.59
   * max_allowed_packet = 1500M
- Plugins & versions: N/A

**Comment by angrybrad** [comment]
What if you doubled the max_allowed_packet setting?

**Comment by tim-pixeldeluxe** [comment]
That didn't work unfortunately. I even tried changing it to 6000M which also didn't solve the problem.

**Comment by angrybrad** [comment]
Can you simplify the template down to a reproducible test case, then send it, your composer.json file and a database dump over to support@craftcms.com?
