### ISSUE TITLE
'limitAutoSlugsToAscii' => true, breaks chinese tags

### ISSUE THREAD

**Issue by jan-thoma** [craftcms/cms#4225]
### Description

With 'limitAutoSlugsToAscii' => true, we are not able to save tags which contains traditional chinese characters.

### Steps to reproduce

1. set 'limitAutoSlugsToAscii' => true
2. try to save 工作频率 as tag

### Additional info

- Craft version 3.1.25:
- PHP version 7.2:
- Database driver & version psql:

**Comment by angrybrad** [comment]
What would the latin ASCII equivalent of 工作频率 be?  Craft uses [Stringy](https://github.com/danielstjules/Stringy) for this type of thing and it looks like they don't have mappings for _any_ glyph based characters.  https://github.com/danielstjules/Stringy/blob/master/src/Stringy.php#L1686-L1848

If you have to keep that setting enabled, you're still free to manually edit the slug to include the characters, too.

**Comment by jan-thoma** [comment]
Is there an option to edit the tag slug in the admin panel? It looks like i only can change the title

![Bildschirmfoto 2019-05-08 um 08 36 14](https://user-images.githubusercontent.com/24450307/57354697-77b0e880-716c-11e9-9bbb-0fb3e073ed26.png)

**Comment by brandonkelly** [comment]
Only by going to the Entries section and finding the entry from there.

**Comment by jan-thoma** [comment]
We're are talking about tags, they are not showing up in the entries section.

**Comment by angrybrad** [comment]
Totally missed this was about tags, too. :(
