### ISSUE TITLE
Sending email change request activates user without password

### ISSUE THREAD

**Issue by Tam** [craftcms/cms#4226]
### Description
If an email is changed on a pending user and the user clicks the confirmation link, their accound is activated without them having set a password.

Idealy the confirmation link would either keep the users status and simply change their email, or act as an activation email and redirect the user to the set password page.

### Steps to reproduce

1. Ensure "Verify email addresses?" is checked in user settings
2. Create a pending user, don't activate it
3. Change the users email (as a non-admin user)
4. Click the confirmation link in the on the new email

### Additional info

- Craft version: Craft Pro 3.1.25
- PHP version: 7.3.4
- Database driver & version: PostgreSQL 11.2

**Comment by brandonkelly** [comment]
By clicking the link, they have shown that they own the email address, thus their email has been verified. Little awkward because they didn’t have a chance to set a password, but they can always go through the Forgot Password workflow.
