### ISSUE TITLE
Add fields to multi-site creation

### ISSUE THREAD

**Issue by millman2394** [craftcms/cms#4227]
I know that when you create a new site, you can add global fields for each site, but I would like to add additional fields to the actual site creation page.

For example, we have many locations that will have their own site in craft and I'd like to have a select field for whether a location is franchise or corporate.

Is this something that can be done via a module?

**Comment by brandonkelly** [comment]
Only “elements” can have custom fields in Craft, and sites aren’t elements – and they can’t be, as Craft needs to know all of the available sites before it can execute any element queries.
