### ISSUE TITLE
User permission to show/edit/remove entries by usergroup

### ISSUE THREAD

**Issue by pette87** [craftcms/cms#4228]
Hi,

if is possible to add a function to select a usergroup for author?

Regards,

Patric

**Comment by brandonkelly** [comment]
Can you elaborate please?

**Comment by pette87** [comment]
At the moment only one user can be selected as author for an entry. We would also like to be able to select an entire user group at this point.

**Comment by brandonkelly** [comment]
It’s not possible to assign an entire user group as an author of an entry, however you can allow a user group to edit any entry within a section regardless of who authored it, by enabling the “Edit other authors’ entries” user group permission
