### ISSUE TITLE
Add Config Setting to Validate Required User Custom Fields on Public Registration Forms

### ISSUE THREAD

**Issue by medoingthings** [craftcms/cms#4229]
### Description

In Craft 2 required user custom fields got validated on public registration forms. This has [changed in Craft 3](https://github.com/craftcms/cms/blob/master/src/controllers/UsersController.php#L1080) to the [surprise of at least some users](https://craftcms.stackexchange.com/q/25885/1056), including me. Getting the old behavior back is pretty cumbersome and involves duplicating the Users Controller from Craft, just to remove a conditional. 

I’m sure there is a good reason for this, but it would be great if this could be a config setting for `general.php`.

### Steps to reproduce

1. Add custom fields to the users field set, make it required.
2. Create a custom front end registration form.
3. Fill out the registration form.

The form submits successfully, even if the required fields weren’t filled.

### Additional info

- Craft version: Craft Pro 3.1.25
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38

**Comment by russback** [comment]
I agree this came as a surprise and the need for a custom controller isn't great. Would also welcome core support for ajax registration where responses from register user are returned as json.

**Comment by icreatestuff** [comment]
A config setting would be perfect to resolve this issue.

**Comment by OliverMaerz** [comment]
Same here. Updated a site from 2 to 3 and functionality in the public registration user form is gone.

**Comment by brandonkelly** [comment]
@OliverMaerz We didn’t drop any user profile functionality in Craft 2.

**Comment by schwarzdesign** [comment]
+1 on this issue. We want to allow public registration with some required custom fields and prevent the registration if validation fails on the custom fields. A config setting to require validation on custom fields to pass for public registration would solve this without creating any overhead for the default behaviour. @brandonkelly Are you considering this feature for a future release? Or are there issues preventing this from being implemented?

**Comment by brandonkelly** [comment]
I’ll see if we can get this resolved for 3.7.

**Comment by brandonkelly** [comment]
Just added a new “Validate custom fields on public registration” setting to the **Settings** → **Users** → **Settings** page for 3.7. When it’s enabled, public registration will get full custom field validation.
