### ISSUE TITLE
Project Config not applying field layout changes

### ISSUE THREAD

**Issue by matt-adigital** [craftcms/cms#4231]
### Description
Currently 3 of us have exactly the same database and project.yaml file pulled down locally. We are running Craft locally through mamp with composer installed directly onto our machines. All of us have our .env file set to the dev environment which is using project config and allowing admin changes. New fields are being added and removed successfully when we git commit the project.yaml file and pull it down onto another machine, but the field layouts are not working correctly.

My colleague has a section named Job Vacancies which has 2 tabs (Jobs, Additional Details) and a total of 6 fields assigned to these tabs. When I pull down the project.yaml file I can see this in the file correctly, I've synced it with the database and I now have the Job Vacancies section with 2 tabs, but no fields assigned. I've looked into the database and it seems that the fieldlayoutfields table isn't getting updated correctly. I've included database dumps of both my database and my colleagues and the full project.yaml file, the relevant information is between lines 1137 and 1164.

We feel that this is a bug as before we made the changes our databases were exactly the same. Can you please investigate and if you need anything else then please let me know. Thank you.

[without_fields_08-05-2019_11-38.sql.gz](https://github.com/craftcms/cms/files/3156892/without_fields_08-05-2019_11-38.sql.gz)

[with_fields_08-05-2019_11-38.sql.gz](https://github.com/craftcms/cms/files/3156893/with_fields_08-05-2019_11-38.sql.gz)

[project.yaml.zip](https://github.com/craftcms/cms/files/3156894/project.yaml.zip)

<img width="531" alt="layout-with-fields" src="https://user-images.githubusercontent.com/15085874/57369806-6f65a700-7186-11e9-97c5-b66585ef4fbb.png">

<img width="555" alt="layout-without-fields" src="https://user-images.githubusercontent.com/15085874/57369816-768cb500-7186-11e9-9189-2e12dfdc5113.png">

### Steps to reproduce

1. Update field layout on a section
2. Commit project.yaml file
3. Pull down on another machine and sync the project config
4. Field Layout tabs have been updated but fields havn't

### Additional info

- Craft version: 3.1.25
- PHP version: 7.1.1
- Database driver & version: MySQL 5.6.35
- Plugins & versions: Amazon S3 1.2.2, Front 1.0.5, Imager v2.1.10, Minify 1.2.9, Redactor 2.3.3.2, Retcon 2.0.12, SEOmatic 3.1.50, Videos 2.0.6

**Comment by andris-sevcenko** [comment]
@matt-adigital can you also please share your composer.lock and composer.json files over support@craftcms.com referencing this issue?

**Comment by matt-adigital** [comment]
I've just sent these in now @andris-sevcenko so they should be with you shortly. Thanks for taking a look.

**Comment by andris-sevcenko** [comment]
This was resolved running `./craft project-config/sync --force=1`

**Comment by matt-adigital** [comment]
Can confirm that this fixed the problems we were seeing, thank you very much!
