### ISSUE TITLE
FR: Optgroups in native dropdown field

### ISSUE THREAD

**Issue by ryanmasuga** [craftcms/cms#4236]
We have a need to ideally organize a long list of dropdown items into optgroups. We like to stay "Craft-native" where we can, so we'd like to use the native Dropdown fieldtype to do this. Maybe some sort of flag in the value field?

![optgroup](https://user-images.githubusercontent.com/988995/57460655-874f3080-7243-11e9-9adf-53f2c13f66be.png)

**Comment by CreateSean** [comment]
I too would love to see this as a native option - see what I did there ;).

**Comment by brandonkelly** [comment]
@CreateSean I’d count myself in the same group.

**Comment by ryanmasuga** [comment]
That was the optimal response.

**Comment by brandonkelly** [comment]
Added for the next 3.2 Alpha release!

<img width="786" alt="Screen Shot 2019-05-10 at 10 21 22 AM" src="https://user-images.githubusercontent.com/47792/57534167-6b17c600-730d-11e9-942c-6c2908a6f844.png">
