### ISSUE TITLE
Entry level permissions

### ISSUE THREAD

**Issue by korvin87** [craftcms/cms#4238]
### Description
We would love to have the following function: only members of a certain usergroup are allowed to view, edit and delete a subset of entries within one certain section in the backend. Members that do not have this usergroup should not be able to view, edit and delete the entries from this subset . Also we do need several usergroups, each needs to have access (view, edit and delete) to its own subset of entries within a section
For the time being we do not see such a strict separation between different users. Is there any chance to overcome this?

### Additional info

- Craft version: 3.1.26
- PHP version: 7.2
- Database driver & version: MySQL
- Plugins & versions: none

**Comment by mtnorthrop** [comment]
Until entry-level permissions are added to CraftCMS, the [Isolate plugin](https://plugins.craftcms.com/isolate) might help people who are looking for this feature. It allows entry-level permissions to be set on a **per user** basis.
