### ISSUE TITLE
Developer icon & website broken in plugin store

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#4241]
### Description
On the in-site plugin store, when you visit a developer's profile, the logo/icon and the website arenn't loaded.

Works fine on plugins.craftcms.com (eg https://plugins.craftcms.com/developer/70), but in from the CP of a site.

### Steps to reproduce

1. Login in to a craft site
2. Navigate to `/admin/plugin-store/developer/70`

### Additional info

- Craft version: 3.1.26
- PHP version: 7.2.10
- Database driver & version: MySQL 5.7
- Plugins & versions:

**Comment by benjamindavid** [comment]
Thanks, @janhenckens!
