### ISSUE TITLE
Enhancement: Relate Assets From a Specific Site

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#4244]
The site selection dropdown should not be displayed at the top of asset models where the asset field option, “relate assets from a specific site?" has been checked and site selected.

The modal site selection dropdown option in this case is redundant and should not be displayed at all or alternatively the configured site name could be displayed as a heading. 

Currently with the above config set I can select an asset and then double-click the asset to bring up the modal, select a different site from the dropdown and save (and close the modal). When I reopen the modal the site specified in the field config is selected.

While the asset modal is open I can select a different site and then change the asset title name for that site which I should only be permitted to do so for the site configured for the field. 

**Steps**
On a multi-site with at least one volume setup...
1. Create a new asset field and check the option "Relate assets from a specific site?" (select the site)
2. Create a new section and add the asset field to the default entry type
3. Create an entry in the section, upload/select and save an asset
4. Double-click the selected asset to bring up the modal (Notice the site dropdown)
5. Choose a different site from the dropdown
6. Change the asset title while a different site is selected then save the asset. 
7. Double-click the asset to bring up the modal again (notice the configured site is now selected)

![846A6A2F-EFDF-4971-96F8-0EC65228FDA0](https://user-images.githubusercontent.com/2505643/57566540-f2019700-7410-11e9-8706-e909ddd07660.jpeg)

**Comment by brandonkelly** [comment]
The modal is just a shortcut for editing the asset. Changing the selected site within it has no effect on the relation. And users can only edit the asset info for sites that they have permission to edit content on.
