### ISSUE TITLE
Enhancement: Field Order and Default (selected) Field in Asset Model

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#4245]
I think it would be more logical/useful to make the "Asset Title" the default and first field listed before/above the asset filename instead of the other way round.

The Asset Title is automatically generated from the filename and I would think most likely the field that would need to be edited (considering files can be renamed before upload or in some cases as part of upload process). Where files are not going to be shown for download from the front-end of a website it’s probably the case that in most instances it doesn’t matter what the filename is called. But the if the file is to be displayed then again I would suspect that in most cases the file title would be what’s displayed to the user. 

Retaining the current behaviour (auto-selecting the text of the filename) but for the asset title text instead when the model appears would also be useful - it would be nice for an Author to immediately start typing and ideally hit return/enter to save the change and close the modal. 

The current auto text-selection behaviour actually selects the filename and the extension which I would think is not that useful. At a guess I would suspect most people would change the text selection to just be the filename before renaming it. 

![846A6A2F-EFDF-4971-96F8-0EC65228FDA0](https://user-images.githubusercontent.com/2505643/57566540-f2019700-7410-11e9-8706-e909ddd07660.jpeg)

**Comment by brandonkelly** [comment]
Related to #3953

**Comment by brandonkelly** [comment]
This is resolved for 3.7, with element editor slideouts (#8017). Asset slideouts now render the full asset field layout, and place the Title field wherever the field layout says it should go. The filename is relegated to the slideout’s meta sidebar.
