### ISSUE TITLE
Status criteria ignored in EVENT_REGISTER_SOURCES event

### ISSUE THREAD

**Issue by skoften** [craftcms/cms#4249]
So I was trying to create some custom filters in the side menu to filter entries by today/live,  today/pending, etc., but the status criteria seems to be ignored completely.

So I tried  the example from the docs, but this also doesn't seem to work.

Code;

```
Event::on(Entry::class, Element::EVENT_REGISTER_SOURCES, function(RegisterElementSourcesEvent $event) {
    if ($event->context === 'index') {
        $event->sources[] = [
            'heading' => \Craft::t('plugin-handle', 'Statuses'),
        ];

        foreach (Entry::statuses() as $status => $label) {
            $event->sources[] = [
                'key' => 'status:'.$status,
                'label' => $label,
                'criteria' => ['status' => $status]
            ];
        }
    }
});
```
Result: all entries are shown, no matter what status.

Someone on Discord said it may have to do with the fact that the pull down select box is present by default and possibly overriding it. Could be, don't know.

Craft CMS 3.1.26
PHP 7.2
MySQL 5.7

**Comment by brandonkelly** [comment]
Yep, the source’s status was being overridden by the status menu in the UI. Next release will start hiding that status menu (and ignoring its value) if the selected source is already defining a status.

**Comment by leevigraham** [comment]
Tricky one… but should this also be the case for `'status'=>null`? In my case I want to always show all statuses.

**Comment by brandonkelly** [comment]
@leevigraham I would say no unless we have a way of hiding the status menu for that source as well, otherwise it would be a confusing UI.

**Comment by leevigraham** [comment]
> @leevigraham I would say no unless we have a way of hiding the status menu for that source as well, otherwise it would be a confusing UI.

Fair… I ended up just listing all the statuses
