### ISSUE TITLE
FR: Ability to disable matrix block per Section

### ISSUE THREAD

**Issue by mediabeastnz** [craftcms/cms#4252]
_I'm aware this has kind of been touched on in other [feature requests](https://github.com/craftcms/cms/issues/1524) but I'd thought I'd leave my thoughts here anyway..._

Almost every site we create we run into the need of being able to disable a matrix block type per section type. For example the home page section may have a very specific block which needs to be in the matrix field so we can re-order the page but it's so specific to the home page no other section should use it.

There's obviously two ways to solve this, one being a simpler interim approach and two being one that will likely need to be in Crafts next major version.

Option 2 would allow you to build multiple matrix fields and instead of creating new fields for the blocks within them each time you would select from a global area. 

Option 1 which is what i'm suggesting is added into version 3.* is to have the ability to disable matrix blocks per section. If you don't, all blocks would be enabled by default as they currently are but if you do, they'd simply either be greyed out or maybe even completely removed from the list.

_I did look at making a plugin that did this and without it being quite "hacky" I think it's better to get this into core as a lot of that type of CMS functionality is JavaScript driven making it hard to extend._

**Comment by brandonkelly** [comment]
Custom fields (including Matrix) can be used across all element types, so it wouldn’t make sense to start adding entry-specific settings to them, like which section(s) should they be available on. Maybe we could add a condition builder to block types, around the time we implement that for fields (#805).

In the meantime, I’ve given Matrix fields a new `EVENT_SET_FIELD_BLOCK_TYPES` event that you could hook into from a [module](https://docs.craftcms.com/v3/extend/module-guide.html) or [plugin](https://docs.craftcms.com/v3/extend/plugin-guide.html), which you can use to remove specific block types when needed:

```php
use craft\elements\Entry;
use craft\events\BlockTypesEvent;
use craft\fields\Matrix;
use yii\base\Event;

Event::on(Matrix::class, Matrix::EVENT_SET_FIELD_BLOCK_TYPES, function(BlockTypesEvent $e) {
    $element = $e->element;
    if ($element instanceof Entry && $element->section->handle === 'news') {
        foreach ($e->blockTypes as $i => $blockType) {
            if ($blockType->handle === 'heading' || $blockType->handle === 'text') {
                unset($e->blockTypes[$i]);
            }
        }
    }
});
```

**Comment by mediabeastnz** [comment]
Good call and that event is perfect, thank you.

**Comment by daltonrooney** [comment]
@mediabeastnz Take a look at [MatrixMate](https://github.com/vaersaagod/matrixmate). It allows you to define matrix block groups, tabs within your blocks, and then define which matrix blocks are available on a per-section basis. Great plugin.
