### ISSUE TITLE
Duplicating an entry in a section where the URI format is {slug} results in duplicate URIs

### ISSUE THREAD

**Issue by benface** [craftcms/cms#4253]
### Steps to reproduce

1. Create a channel or structure and use `{slug}` as the URI format.
2. Create an entry in that section, let the slug auto-generate based on its title.
3. From the entry index page, select the entry and hit "Duplicate".
4. Notice the duplicated entry has the same slug and URI as the first one.

### Additional info

- Craft version: 3.1.26
- PHP version: 7.3.3
- Database driver & version: MySQL 5.7.25

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release.
