### ISSUE TITLE
Seeing Additional Tabs in Users

### ISSUE THREAD

**Issue by tinchalamo** [craftcms/cms#4256]
### Description
I adjusted permissions for a Publisher User Group and am now seeing non-User tabs and fields in the User edit screen.

![image](https://user-images.githubusercontent.com/11000310/57652392-11c1c800-7595-11e9-9189-b271c4f94ee8.png)

### Steps to reproduce

1. Create 2 different user groups
2. Create 2 different sets of permissions for the user groups
3. Assign some users to one user group and the rest on the other user group
4. Go into a User to edit which User Group they're part of and you see non-User tabs showing up in the UI

### Additional info

- Craft version: Craft CMS 3.2.0-alpha.5
- PHP version: 7.2.17
- Database driver & version: MySQL 5.6.43

### Plugins & versions:

- craftcms/redactor: 2.3.3.2
- mmikkel/incognito-field: 1.1.1.1
- rias/craft-position-fieldtype: 1.0.14
- markhuot/craftql: 1.3.2
- verbb/super-table: 2.1.19
- marionnewlevant/match-input: v2.0.1
- fruitstudios/linkit: 1.1.11
- nfourtythree/entriessubset: 1.2.1
- craftcms/aws-s3: 1.2.2
- nystudio107/craft-units: 1.0.3
- doublesecretagency/craft-cpcss: 2.1.0
- doublesecretagency/craft-smartmap: 3.2.2.1
- craftcms/store-hours: 2.1.1.1
- elivz/craft-single-cat: 1.2.1
- fortrabbit/craft-copy: 1.0.0-RC5
- aelvan/preparse-field: v1.0.6
- spicyweb/craft-fieldlabels: 1.1.0
- rias/craft-password-policy: 1.0.4
- craftcms/element-api: 2.5.4
- craftcms/feed-me: 4.1.0
- verbb/workflow: 1.1.9
- robuust/craft-reverserelations: 1.1.4
- mmikkel/cp-field-inspect: 1.0.5
- doublesecretagency/craft-inventory: 2.0.2
- fortrabbit/yii-memcached: ^1.0
- putyourlightson/craft-sendgrid: 1.1.0
- doublesecretagency/craft-cpjs: 2.1.0
- doublesecretagency/craft-cpbodyclasses: 2.1.0

**Comment by brandonkelly** [comment]
Did you use any plugins that may have made changes to your project config (such as duplicating/migrating fields or other settings, etc.)? The only way I can see this happening is if somehow you are sharing the same field layout between users and something else on your site.

**Comment by tinchalamo** [comment]
It does look it's related to permission changes made in settings for the [Workflow plugin](https://github.com/verbb/workflow). It's using the same fieldLayouts as our Movie entry type. Is there an easy fix for this? I'm reaching out to Verbb as well.

**Comment by tinchalamo** [comment]
The weird part is that my local and our production is using the same project config, but this issue is only cropping up on production.

**Comment by andris-sevcenko** [comment]
That's because of a bug with `project-config/rebuild` that's been fixed in db2639777b067163901bc74809968b46e41a159c. The reason you see this only in one environment is that you've run `project-config/rebuild` on that environment.

To fix that, you'll have to edit your project.yaml file, remove the extra field layout that was added there under `users.fieldLayouts` key and run `./craft project-config/sync --force`

**Comment by tinchalamo** [comment]
Is this fixed in 3.2.0-alpha.5?

**Comment by andris-sevcenko** [comment]
That fix hasn't been a part of any release yet.

**Comment by brandonkelly** [comment]
@tinchalamo I just merged `develop` into the `3.2` branch, so you can get the fix by changing your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "3.2.x-dev#ac5e0272ce33db948de57c4cbd2fe72f9fc3eb60 as 3.2.0-alpha.5",
  "...": "..."
}
```

Then run `composer update`, then follow Andris’ instructions in https://github.com/craftcms/cms/issues/4256#issuecomment-492103269.

**Comment by tinchalamo** [comment]
@brandonkelly I updated my local install, made the project.yaml change per @andris-sevcenko and ran `./craft project-config/sync --force`, but then got this error in terminal `error: Maximum number of deferred events reached.` Is that something to be concerned about?

**Comment by brandonkelly** [comment]
Hm, yeah that error is a problem. Can you please send your `composer.json`, `composer.lock`, and `config/project.yaml` files, plus a database backup over to support@craftcms.com and reference this issue URL?

**Comment by tinchalamo** [comment]
Just sent! Thanks for taking a look.
