### ISSUE TITLE
Verification code set to null after a fresh log in

### ISSUE THREAD

**Issue by musicaljoeker** [craftcms/cms#4257]
### Description

I believe I have run into unexpected behavior that invalidates a user's email update request after logging out and logging back in again. I believe the issue is originating here 

https://github.com/craftcms/cms/blob/4a6418ed8fa69290a01a53f13a2e76f1c655ea5c/src/services/Users.php#L488

and here

https://github.com/craftcms/cms/blob/4a6418ed8fa69290a01a53f13a2e76f1c655ea5c/src/services/Users.php#L489

where `$userRecord->verificationCode` and `$userRecord->verificationCodeIssuedDate` are both being set to null upon a successful log in. This prevents a user from submitting an "Update Email" request, logging out, and logging back in, and still being able to verify their new email address.

I am happy to submit a PR for this, but I'm not sure why this is being set to null in the first place.

### Steps to reproduce

1. Initiate a change email request.
2. Log out
3. Log back in using the old (still current) email address prior to verifying the new email
4. Notice in the DB that both the verificationCode and verificationCodeIssuedDate in the user table are both null.
5. Try to verify the new email with the link generated, but now this won't work.

### Additional info

- Craft version: 3.1.26
- PHP version: 7.2.17
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just fixed for the next release.

**Comment by musicaljoeker** [comment]
Thank you @brandonkelly for your prompt response! Greatly appreciated! Do you know what the next release will be and approximately when you plan to release that?

**Comment by brandonkelly** [comment]
@musicaljoeker We just released 3.1.27 with the fix.
