### ISSUE TITLE
FR: Table Field - Add Rows from the Top

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#4259]
Would be great to have an option and UI to support the feature, to add table rows from the top of a table field.

There are some instances where a table field may be used as the predominant field for an entry. This means that updating an entry to add new rows means scrolling to the bottom to access the last row. 

There are other instances where maybe each new row within a table is an update to a changelog which would typically be displayed in reverse order on the front end (latest row first/at the top). Having the authoring experience mimic the reverse ordering would be nice as well as super easy especially if the table had many rows.

This feature would simplify and make the authoring experience more efficient in these and other similar use cases.

**Comment by brandonkelly** [comment]
I don’t think it’s worth adding a UI element for this, but as of the next release it will be possible to press <kbd>Shift</kbd> + <kbd>Return</kbd> (or <kbd>Shift</kbd> + <kbd>Ctrl</kbd>/<kbd>Command</kbd> + <kbd>Return</kbd>) to move the focus to the previous table row – and create a previous table row if the first row is already focused.

**Comment by aaronmclayton** [comment]
> I don’t think it’s worth adding a UI element for this, but as of the next release it will be possible to press Shift + Return (or Shift + Ctrl/Command + Return) to move the focus to the previous table row – and create a previous table row if the first row is already focused.

Two questions for you @brandonkelly:

Which release version are you referring to?
How would that keystroke work when adding a new row in the control panel?

Thank you.

**Comment by brandonkelly** [comment]
@aaronmclayton That was added in Craft 3.1.27. It *only* affected the control panel (any “editable tables” in the CP - where the cells can contain customizable text).
