### ISSUE TITLE
CMS Login page breaks when a port number is present in the URL

### ISSUE THREAD

**Issue by marknotton** [craftcms/cms#4261]
### Description
In any circumstance where a port number is present in the URL the CMS Login page breaks. The login form doesn't show up due to a Javascript error: 

`Uncaught SyntaxError: Unexpected token : Login : 87`

This is happening because of an odd syntax issue occurring with the use of escape expressions on the quotations when setting the brand logo image. I'm afraid I don't know the technical reasons for the error, but I do know how to fix it. 

On line 37 of the `craftcms/cms/src/templates/login.html` template a simple space will resolve the problem:

**Before**
`style="background-image: url(\'{{ logo.url }}\');`

**After**
`style="background-image: url(\' {{ logo.url }}\');`

or you can remove the escaped quotations all-together

`style="background-image: url({{ logo.url }});`

I hope this helps. Thanks. 

### Steps to reproduce

1. Go to your CMS login page with a port number: http://www.website.com:3000/admin/login

### Additional info

- Craft version: 3.1.26
- PHP version: 7.2.14

**Comment by brandonkelly** [comment]
Thanks for reporting that!

**Comment by brandonkelly** [comment]
Removing the `'`s broke the page for someone else (#4262), so have reverted that commit. Don’t want to add a space to the beginning of the URL as that feels too hacky.

Guessing the bug has more to do with your logo filename than the port number; looks like we’re not sanitizing the filename anywhere so there’s a chance the filename could break things. Will fix that.
