### ISSUE TITLE
Custom Login Page Logo is Broken

### ISSUE THREAD

**Issue by tinchalamo** [craftcms/cms#4262]
Looks like the [update here](https://github.com/craftcms/cms/blob/ac5e0272ce33db948de57c4cbd2fe72f9fc3eb60/src/templates/login.html#L37) is missing the correct syntax for setting a background-image. Should be: `url(\'{{ logo.url }}\')`.

**Comment by brandonkelly** [comment]
Huh, that change was just made per #4261. Guess I’ll revert...

**Comment by tinchalamo** [comment]
@brandonkelly maybe try it with the space to see if it fixes the port issue as noted in that issue? `url(\' {{ logo.url }}\')`

**Comment by brandonkelly** [comment]
Eh, that’s too hacky. URLs don’t start with spaces.

**Comment by tinchalamo** [comment]
@brandonkelly is this rolled into `3.2.x-dev#ac5e0272ce33db948de57c4cbd2fe72f9fc3eb60 as 3.2.0-alpha.5`? It's what I'm using in order to get the #4256 fix in.

**Comment by brandonkelly** [comment]
Not yet, will let you know once I have.

**Comment by brandonkelly** [comment]
@tinchalamo Alight `3.2` is updated with the latest changes now. Change your `craftcms/cms` requirement to:

```json
"require": {
  "craftcms/cms": "3.2.x-dev#611ada6ae77d4c2709e37389e841188eb201b788 as 3.2.0-alpha.5",
  "...": "..."
}
```

Then run `composer update`.
