### ISSUE TITLE
Slug generation adds hyphen when it encounters an uppercase character

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/cms#4266]
### Description
Not sure if this is intended behaviour; I have a section that I use to generate PDF documents. The entries in this PDF section are generated via a plugin. 

On an entry, the slug is populated by a mixture of uppercase characters and hyphens. The thought here is that upon save, Craft would lowercase the entire slug field for me. 

Craft does lowercase the string, but adds extra characters in place where it encounters an uppercase character.

### Steps to reproduce

1. Create a new entry
2. Enter `Test` in the title field
3. Enter `A-B-C` in the slug field and save the entry
4. After save, Craft generates the slug as `a--b--c`

### Expected behaviour

To generate a slug like `a-b-c` from `A-B-C`

### Additional info

- Craft version: 3.1.27
- PHP version: 7.2.14
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
```
"craftcms/aws-s3": "1.2.2",
"craftcms/feed-me": "4.1.0",
"craftcms/redactor": "2.3.3.2",
"doublesecretagency/craft-cpbodyclasses": "2.1.0",
"doublesecretagency/craft-cpcss": "2.1.0",
"enovatedesign/craft-style-inliner": "1.1.2",
"pdfcrowd/pdfcrowd": "^4.4",
"solspace/craft3-freeform": "2.5.23",
"vlucas/phpdotenv": "^2.4.0",
"youandmedigital/breadcrumb": "^1.0",
"youandmedigital/craft-foxycarthmac": "1.0.0",
```

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.
