### ISSUE TITLE
Initial install fails when using project config and allowAdminChanges = false

### ISSUE THREAD

**Issue by mattgrayisok** [craftcms/cms#4267]
### Description

If a site is using project config, is installed for the first time in a new environment and has allowAdminChanges set to false for the new environment the installation will fail with `Changes to the project config are not possible while in read-only mode`

This seems to be being caused due to the installer attempting to re-save the `site` properties that are set during the installation process.

```
2019-05-15 10:14:47 [-][-][-][error][craft\errors\MigrationException] yii\base\NotSupportedException: Changes to the project config are not possible while in read-only mode. in /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php:386
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/services/Sites.php(680): craft\services\ProjectConfig->set('sites.7bf426ba-...', Array)
#1 /var/www/html/vendor/craftcms/cms/src/migrations/Install.php(1062): craft\services\Sites->saveSite(Object(craft\models\Site))
#2 /var/www/html/vendor/craftcms/cms/src/migrations/Install.php(73): craft\migrations\Install->insertDefaultData()
```
This is particularly annoying when building docker containers as the config files are baked into the built image so they're not particularly easy to change. I have resorted to pulling the `allowAdminChanges` setting out into an ENV var so that I can easily flip it on and off around the install process (which is arguably a better solution anyway).

Possible that the `allowAdminChanges` setting should specifically be ignored during installation as a special case?

### Steps to reproduce

1. Start a new project in local dev with project config enabled
1. Make some admin changes
2. Set `production` to `'allowAdminChanges' => false` in `general.php`
3. Deploy this project to a `production` environment
4. Install using UI or CLI

### Additional info

- Craft version: 3.1.26
- PHP version: 7.3
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
Yeah I can’t think of a good reason Craft should care about `allowAdminChanges` if it’s not even installed yet. Fixed this for the next release.
