### ISSUE TITLE
twig loop.parent.loop not there for nested loops

### ISSUE THREAD

**Issue by marionnewlevant** [craftcms/cms#4271]
### Description
This used to work, and does work in [twigfiddle](https://twigfiddle.com/):
```
{% for x in 1..2 %}
  {% for y in 1..2 %}
    [{{loop.parent.loop.index}} {{loop.index}}]
  {% endfor %}
{% endfor %}
```
### Steps to reproduce

1. Brand new Craft install (3.1.27)
2. Create a twig template with that content
3. Error is:
> Key "loop" for array with keys "view, devMode, SORT_ASC, SORT_DESC, SORT_REGULAR, SORT_NUMERIC, SORT_STRING, SORT_LOCALE_STRING, SORT_NATURAL, SORT_FLAG_CASE, POS_HEAD, POS_BEGIN, POS_END, POS_READY, POS_LOAD, isInstalled, loginUrl, logoutUrl, now, craft, currentUser, systemName, currentSite, siteName, siteUrl, _parent, _seq, x, _key" does not exist.

### Additional info

- Craft version: 3.1.27
- PHP version: 7.0.13
- Twig version: 2.8.1
- Plugins & versions: none

Looking at the compiled template, and comparing it to the compiled template from [twigfiddle](https://twigfiddle.com/) it is pretty clear what is going wrong.
[compiledTemplateComparison.zip](https://github.com/craftcms/cms/files/3184816/compiledTemplateComparison.zip)

**Comment by brandonkelly** [comment]
Sorry for the delay Marion! Just fixed this for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#509ad31a53ac888e3ee60613c3bf82dbdb98658a as 3.1.28",
  "...": "..."
}
```

Then run `composer update`.
