### ISSUE TITLE
Entry which is enabled for the current site is displayed as inactive when choosing it from the entry type field.

### ISSUE THREAD

**Issue by myriago** [craftcms/cms#4274]
### Description

I have entries called organisations. I also have multiple sites. Organisations are propagated across all sites. Organisations are also the source for an entry field called Organisation. When I create a new Organisation entry and enable it both globally and for the current site (but its disabled on other sites), the organisation field will show this entry as disabled for this site. It shows properly after I set it to active on the other site. It also shows some entries that are inactive on this site as active.

To be fair I don't know if its a bug or it's meant to be like that, but it surely made me confused. I expected consistency between status of an entry in entries section and in entry selector modal.

EDIT: So this looks to be a bug, I have the same field on an entry and a user. On an entry all entries in the modal are displayed as expected meaning the active ones for the current site are active and inactive ones are not, but on the user the modal display the status incorrectly. 

### Steps to reproduce

1. Create a new entry on multi site setup, entry needs to be set to propagate
2. Enable entry globally and for the current site, but disable for other sites.
3. Have an entry field that has the above entry as its source
4. Add this field to the user
4. Add entry via entry picker modal window and you will see the entry is set as inactive although all works fine its just displayed like that.

It's difficult for me to explain, see screenshot below.

![modal](https://user-images.githubusercontent.com/20819907/58093322-2c63f480-7bc6-11e9-9f54-53be8209016c.png)

### Additional info

- Craft version: 3.1.26 (Pro)
- PHP version: 7.1.26
- OS version: Linux 3.16.0-7-amd64
- Database driver & version: MySQL 5.5.62
- Image driver & version: Imagick 3.4.3 (ImageMagick 6.8.9-9)
- Plugins & versions: 
    - Advanced Url Field 1.0.0
    - Calendarize 1.2.8
    - Control Panel Body Classes 2.1.0
    - Control Panel CSS 2.1.0
    - Control Panel JS 2.1.0
    - Feed Me 4.1.0
    - Logs 3.0.0
    - Redactor 2.3.3.2
    - Smart Map 3.2.2
    - Star Ratings 2.1.1
    - Super Table 2.1.19
    - Time Ago 1.0.3
    - Video Embedder 1.1.1

**Comment by brandonkelly** [comment]
Does this happen for all users, or just when you are creating a new user?

**Comment by myriago** [comment]
It happens on new users and while editing existing ones.

**Comment by myriago** [comment]
I've added image to better illustrate what I meant, as after reading my own description I was struggling to understand what was the issue heh.

**Comment by brandonkelly** [comment]
Which site is your primary site?

**Comment by myriago** [comment]
You are right, modal on the user shows primary site status rather then the current site status. I still think it should show current site status though, admins who are limited to one site can get confused about the  difference in status, I was confused even though I have access to all sites.

**Comment by brandonkelly** [comment]
Yeah it’s a little awkward because users aren’t localizable, so they only belong to the primary site, and relational fields will always show statuses as they are set based on the source element’s site, so in users’ case, the primary site.

> I still think it should show current site status though

The Control Panel should generally only be accessed from the primary site, in which case this is already the case.
