### ISSUE TITLE
Option to use snake_case instead of camelCase in autogenerated handles

### ISSUE THREAD

**Issue by jmldavis** [craftcms/cms#4276]
I've always preferred `snake_case` to `camelCase`. It's easier to read, it looks nicer, it's clearer where one word ends and another begins... but Craft CMS auto generates handles in camelCase, which is very painful for those of us who like snake case so much that we go through and manually convert all handles to snake case.

Would be great if there was an option (e.g. in general config) to choose one or the other.

**Comment by TomHell** [comment]
This setting would be very helpfully and happy to get it one day.

**Comment by brandonkelly** [comment]
Just added a new `handleCasing` config setting for Craft 3.6, which can be set to one of the following values:

- `camel` – for camelCase _(default)_
- `pascal` – for PascalCase (aka UpperCamelCase)
- `snake` – for snake_case

(Wish I could have added `kebab` as well, but we will need to make it possible to allow hyphens in slugs first – see #2276.)

**Comment by jmldavis** [comment]
Excellent @brandonkelly - this gives me a disproportionate amount of pleasure

**Comment by brandonkelly** [comment]
Craft 3.6 has now been officially released ✨
