### ISSUE TITLE
Structure 'max levels' ignored-ish when re-ordering entries

### ISSUE THREAD

**Issue by SayChi** [craftcms/cms#4279]
### Description
When max levels is set on a structure, it is not properly taken into consideration when editing an entry to change its parent.

### Steps to reproduce

1. Create a strucure with max levels = 2
2. Create entry a
3. Create entry b with parent a
4. Create entry c without parent
5. Edit entry a to change its parent to c

This results in the strucure showing:
c -> a -> b

### Additional info

- Craft version: 3.1.27
- PHP version: 7.1.29
- Database driver & version: MySQL 5.5.60

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.
