### ISSUE TITLE
Setting alternative  base URL of pagination

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#4286]
I propose some method of setting alternative base URL of pagination links. Right now URL of pagination links is taken from page that pagination is used in.

I would like to display paginated links on homepage of my site, but links should direct to specific section that is NOT homepage.

**Comment by brandonkelly** [comment]
Just made this possible for the next release.

For example, to set the base pagination URL to the homepage, you could do this:

```twig
{% paginate query as pageInfo, pageEntries %}
{% do pageInfo.setBasePath('') %}
```

**Comment by piotrpog** [comment]
@brandonkelly 
Thanks, it will be really useful for me.
