### ISSUE TITLE
Share button in CP generates error when usePathInfo = true

### ISSUE THREAD

**Issue by skoften** [craftcms/cms#4287]
When usePathInfo in the general config is set to true, clicking on the Share button on the entry form generates an Entry Not found error:

![Screenshot 2019-05-20 at 14 13 01](https://user-images.githubusercontent.com/1286410/58021194-93bc6e80-7b0a-11e9-8084-e6e6db83aeb2.png)

Craft CMS 3.1.27

**Comment by brandonkelly** [comment]
What URL does it take you to?

**Comment by skoften** [comment]
usePathInfo false: /index.php?p=cp/actions/entries/share-entry&entryId=160883&siteId=1
usePathInfo true: /index.php/cp/actions/entries/share-entry?entryId=160883&siteId=1

**Comment by brandonkelly** [comment]
Are you running Apache, and is the [AcceptPathInfo](https://httpd.apache.org/docs/2.4/mod/core.html#acceptpathinfo) directive enabled?

**Comment by skoften** [comment]
Running Nginx (load balancer) which some Lighttpd backends behind it.

**Comment by brandonkelly** [comment]
OK, makes sense then. `usePathInfo` should only be set to `true` when running Apache, as it’s an Apache-only concept.
