### ISSUE TITLE
Craft 2 PHP 7.3 compatibility

### ISSUE THREAD

**Issue by OscarBarrett** [craftcms/cms#4294]
Is Craft 2 compatible with PHP 7.3, and if not is compatibility planned?

[Yii 1.1.21 with PHP 7.3 compatibility was released in April](https://www.yiiframework.com/news/206/yii-1-1-21-is-released) which Craft has been updated to use, but it hasn't been mentioned whether Craft is fully PHP 7.3 compatible.

**Comment by OscarBarrett** [comment]
Running [PHPCompatibility](https://github.com/PHPCompatibility/PHPCompatibility) on 2.7.8 using PHP 7.3 shows only warnings, no errors.

**Comment by angrybrad** [comment]
We're not aware of any PHP 7.3 compatibility issues with the latest Craft 2.x release, but please file an issue if you run into something!

**Comment by jonathannz** [comment]
Sorry to drag up this old ticket, but this seems like the most efficient way to follow-up on this.

As of now (July 2020), is it still the case that there's no known compatibility issues with Craft 2 (v2.9.1) and PHP 7.3?

[I've inherited a Craft 2 site, and need to run it on a server with only PHP 7.3 — if at all possible]

**Comment by angrybrad** [comment]
@jonathannz nothing we're aware of.

**Comment by Mosnar** [comment]
@jonathannz Be cautious of PHP 7.3. While Craft 2 works fine on it, not all of the old plugins will. A big one that comes to mind is SEOmatic: https://github.com/nystudio107/seomatic/issues/380
