### ISSUE TITLE
Upload Location that contains slashes lead to nested directories

### ISSUE THREAD

**Issue by s3p2** [craftcms/cms#4296]
### Description
Slashes that are inserted into the path of the Upload Location through an variable like {title} lead to nested directories. I would expect that a slash inside the {title} string would be escaped.

{title} = "Company of foo/bar"
Upload Location = pictures/{title}

leads to following directory structure

![Craft_issue](https://user-images.githubusercontent.com/20905546/58184312-2860d100-7cb1-11e9-8491-917889f151be.png)

![Craft_slash_issue](https://user-images.githubusercontent.com/20905546/58184316-28f96780-7cb1-11e9-8c6a-a3589e5bd07e.png)

but it should be 
-pictures
--|Company of foo/bar

### Steps to reproduce

1. Create a channel with a  field of the type "Asset"
2. Set Upload location to "Companies/{title}"
3. Create a new entry with the title "Company  of foo/bar" and upload a picture
4. check Folder structure in the "Asset" menu

### Additional info

- Craft version: Craft Solo 3.1.28
- PHP version: 7.2.18
- Database driver & version: MySQL 5.5.5
- Plugins & versions: CKEditor | 1.0.0-beta.2

**Comment by brandonkelly** [comment]
Upload Location is just a Twig template, and if the rendered template says to add a `/`, Craft is going to make a subfolder.

You could guard against this by manually having Twig strip out slashes though, by changing `{title}` to `{title|replace('/', '-')}`.
