### ISSUE TITLE
Matrix block issue on routed template

### ISSUE THREAD

**Issue by leigeber** [craftcms/cms#4297]
### Description

It seems there may be an issue in the alpha with matrix blocks pulling from the injected "entry".

For instance, on a routed blog page with the following only the first block is output and the length is 1.

```twig
{{ entry.article.all()|length }}
```

But this outputs the correct number of blocks.

```twig
{% set entry = craft.entries({
	limit: 1,
	section: 'blog',
	slug: entry.slug
}).one() %}

{{ entry.article.all()|length }}
```

### Additional info

- Craft version: 3.2.0-alpha6.2
- PHP version: 7.3.0
- Database driver & version: PostgreSQL 11.2
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
Please send your `composer.json` and `composer.lock` files, plus a database backup, over to support@craftcms.com and reference this GH issue URL, plus include steps to reproduce both of your issues, and I’ll look into it from there.
