### ISSUE TITLE
Issue changing default language in command line with ./craft setup

### ISSUE THREAD

**Issue by brycekirk** [craftcms/cms#4298]
### Description
Attempting to set the language to en-CA using the ./craft setup command returns "en-CA is not a valid language."

### Steps to reproduce

1. Install Craft via composer
2. Run ./craft setup and go through the prompts until you reach language selection

### Additional info

- Craft version: 3.1.25
- PHP version: 7.0.33
- Database driver & version: MySQL 5.7.25

**Comment by brandonkelly** [comment]
That means Craft is unaware that the `en-CA` locale exists, which most likely means you are running it on a server that doesn’t have the [Intl extension](https://www.php.net/manual/en/book.intl.php) installed, so Craft only knows about the locales it has data for in [src/config/locales/](https://github.com/craftcms/cms/tree/develop/src/config/locales).

You can manually tell Craft about the `en-CA` locale by creating a `locales/` folder within your `config/` folder, and then saving https://github.com/craftcms/locales/blob/master/locales/en-CA.php to it. (So `config/locales/en-CA.php`.)
