### ISSUE TITLE
New fieldtype for selecting Craft data structures

### ISSUE THREAD

**Issue by dougstjohn** [craftcms/cms#4301]
Create a new fieldtype that allows users to select Craft data structures like Sections, EntryTypes, User Groups, Category Groups, Field Groups, Asset Groups, etc.

The use case is a client requested to be able to select an EntryType and show the latest 10 entries sorted and filtered by a date range. There is no fieldtype to allow users to select these type of Craft data structures. I ended up creating a Dropdown field and manually defining the EntryType options. If I were to create new EntryTypes, the options list wouldn't be updated and it's likely a dev won't remember to update that options list.

**Comment by brandonkelly** [comment]
This can currently be accomplished using the [Dynamic Fields](https://plugins.craftcms.com/craft-dynamic-fields) plugin by @lewisjenkins.
