### ISSUE TITLE
System settings set with a .env variable will only return variable name front end

### ISSUE THREAD

**Issue by bob-pixeldeluxe** [craftcms/cms#4302]
### Description
So im not sure if this is a bug but when i have the system e-mail set with a .env variable and i try to fetch in using twig it just returns $SYSTEM_EMAIL (My .env variable name)

### Steps to reproduce

1. Set the system email to a .env variable
2. craft.systemSettings.email.fromEmail (I know of the parseEnv() twig function however i still thought i should report it)

#2122

## Additional info

- Craft version: 3.1.28
- PHP version: 7.2.10

**Comment by brandonkelly** [comment]
That’s expected; the raw setting value is whatever you set it to. Craft only parses it as an environment variable when applying it to the Mailer component config.

Related discussion: #3964
