### ISSUE TITLE
Question about search syntax and subRight

### ISSUE THREAD

**Issue by nettum** [craftcms/cms#4305]
### Description
I'm having trouble understanding the results I'm getting below compared to the documentation over at  https://docs.craftcms.com/v3/searching.html#supported-syntaxes

Example:
```
body field is: salty dog

searchquery 1: craft.entries().section('testsection').search('body:"salt"')
searchquery 2: craft.entries().section('testsection').search('body:"alty"')
searchquery 3: craft.entries().section('testsection').search('body:"salty"')
searchquery 4: craft.entries().section('testsection').search('body:"do"')
searchquery 5: craft.entries().section('testsection').search('body:"og"')
searchquery 6: craft.entries().section('testsection').search('body:"dog"')

searchquery 1 result: 1
searchquery 2 result: 0
searchquery 3 result: 1
searchquery 4 result: 1
searchquery 5 result: 0
searchquery 6 result: 1
```
Is it correct that searchquery 1 and 4 above should give results?   

The logic behind this seems to come from https://github.com/craftcms/cms/blob/develop/src/search/SearchQuery.php#L146-L154

[SearchQueryTerm](https://github.com/craftcms/cms/blob/develop/src/search/SearchQueryTerm.php) `subRight` seems to be true as default.

The search will behave the way I want if I change the code from 
```
            if ($token) {
                if (substr($token, -1) === '*') {
                    $term->subRight = true;
                    $token = mb_substr($token, 0, -1);
                }
            } else {
                // subRight messes `attr:*` queries up
                $term->subRight = false;
            }
```
to
```
            if ($token) {
                if (substr($token, -1) === '*') {
                    $term->subRight = true;
                    $token = mb_substr($token, 0, -1);
                } else {
                    $term->subRight = false;
                }
            } else {
                // subRight messes `attr:*` queries up
                $term->subRight = false;
            }
```

What should be the correct behavior?

### Steps to reproduce
Se example query above

### Additional info

- Craft version: 3.1.28
- PHP version: 7.2

**Comment by brandonkelly** [comment]
That is expected. You can prevent options 1 and 4 from returning results by changing the [defaultSearchTermOptions](https://docs.craftcms.com/v3/config/config-settings.html#defaultsearchtermoptions) config setting in `config/general.php` to:

```php
'defaultSearchTermOptions' => [
    'subRight' => false,
],
```

**Comment by nettum** [comment]
Thanks, didn't see that :+1:
