### ISSUE TITLE
Hitting the escape key during install closes the installer modal

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#4307]
### Description
If you hit the <kbd>Esc</kbd> key during the installation (it was an accident!), the setup modal will close. Clicking the "Install" button will show the modal but it progresses to the next step. In my case, I had not finished configuring the install and the next step was to run the migrations.

### Steps to reproduce

1. Start a fresh install from web GUI
2. When you get to the input portion, hit the <kbd>Esc</kbd> key

The modal should probably be locked to prevent closing or the installation process should be reset when closed.

### Additional info

- Craft version: 3.1.x
- PHP version: N/A
- Database driver & version: N/A
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.
