### ISSUE TITLE
table hits row size limit

### ISSUE THREAD

**Issue by rolfkokkeler** [craftcms/cms#4308]
### Description
table with to columns; label and url.
Adding up to 20 rows gives database exception:

> SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large (> 8126). Changing some columns to TEXT or BLOB or using ROW_FORMAT=DYNAMIC or ROW_FORMAT=COMPRESSED may help. In current row format, BLOB prefix of 768 bytes is stored inline. 

### Steps to reproduce

just try an recreate a table with this content:
ield_productDocumentsPimField`='[{\"col1\":\"1\",\"col2\":\"https://aoc-pim.s3.amazonaws.com/Manuals%202/G2770/English.pdf\"},{\"col1\":\"2\",\"col2\":\"https://aoc-pim.s3.amazonaws.com/Manuals%202/G2770/English.pdf\"},{\"col1\":\"3\",\"col2\":\"https://aoc-pim.s3.amazonaws.com/Manuals%202/G2770/English.pdf\"},{\"col1\":\"4\",\"col2\":\"https://aoc-pim.s3.amazonaws.com/Manuals%202/G2770/English.pdf\"},{\"col1\":\"5\",\"col2\":\"https://aoc-pim.s3.amazonaws.com/Manuals%202/G2770/English.pdf\"},{\"col1\":\"6\",\"col2\":\"https://aoc-pim.s3.amazonaws.com/Manuals%202/G2770/English.pdf\"},{\"col1\":\"7\",\"col2\":\"https://aoc-pim.s3.amazonaws.com/Manuals%202/G2770/English.pdf\"},{\"col1\":\"8\",\"col2\":\"https://aoc-pim.s3.amazonaws.com/Manuals%202/G2770/English.pdf\"},{\"col1\":\"9\",\"col2\":\"https://aoc-pim.s3.amazonaws.com/Manuals%202/G2770/English.pdf\"},{\"col1\":\"10\",\"col2\":\"https://aoc-pim.s3.amazonaws.com/Manuals%202/G2770/English.pdf\"},{\"col1\":\"11\",\"col2\":\"https://aoc-pim.s3.amazonaws.com/Manuals%202/G2770/English.pdf\"},{\"col1\":\"12\",\"col2\":\"https://aoc-pim.s3.amazonaws.com/Manuals%202/G2770/English.pdf\"},{\"col1\":\"13\",\"col2\":\"https://aoc-pim.s3.amazonaws.com/Manuals%202/G2770/English.pdf\"},{\"col1\":\"14\",\"col2\":\"https://aoc-pim.s3.amazonaws.com/Manuals%202/G2770/English.pdf\"},{\"col1\":\"15\",\"col2\":\"https://aoc-pim.s3.amazonaws.com/Manuals%202/G2770/English.pdf\"},{\"col1\":\"16\",\"col2\":\"https://aoc-pim.s3.amazonaws.com/Manuals%202/G2770/English.pdf\"},{\"col1\":\"17\",\"col2\":\"https://aoc-pim.s3.amazonaws.com/Manuals%202/G2770/English.pdf\"},{\"col1\":\"18\",\"col2\":\"https://aoc-pim.s3.amazonaws.com/Manuals%202/G2770/English.pdf\"},{\"col1\":\"19\",\"col2\":\"https://aoc-pim.s3.amazonaws.com/Manuals%202/G2770/English.pdf\"},{\"col1\":\"20\",\"col2\":\"https://aoc-pim.s3.amazonaws.com/Manuals%202/G2770/English.pdf\"}]'

### Additional info

- Craft version: 3.1.28
- PHP version: 7.2.18
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

**Comment by brandonkelly** [comment]
Table fields get TEXT columns by default, and they have a Column Type setting that lets you even increase it to MEDIUMTEXT (if using MySQL).

What column type is your `field_productDocumentsPimField` column currently? Any idea how it went from TEXT to that?

Resaving the field should bring it back to TEXT, but I’m curious why it strayed from that to begin with.

**Comment by brandonkelly** [comment]
Row size limits are no longer an issue in Craft 5.
