### ISSUE TITLE
After saving an entry, keep scroll position in entries page.

### ISSUE THREAD

**Issue by alexgilbertDG** [craftcms/cms#4310]
When saving an entry we are redirect to the entries page. My client got 1000+ entries in a specific entry type and they would like to keep the scroll position when they are finish with one entry. Entries are already html ID by their ID so it would probably be just to add a #<ID> when we are redirected to the entries page.

Thanks.

### Steps to reproduce
1. Save Entry
2. You are redirect to the entries page, but at the top.

**Comment by brandonkelly** [comment]
This is resolved in Craft 3.2 (currently in Alpha), where element indexes are now paginated (#818).
