### ISSUE TITLE
Get "Trying to get property of non-object" error when creating new entry

### ISSUE THREAD

**Issue by tinchalamo** [craftcms/cms#4312]
### Description
I get a "Trying to get property of non-object" error when trying to create a Show entry after upgrading to 3.2.0-alpha.6.3. [Here's the stack trace.](https://gist.github.com/tinchalamo/b9df32c5f5411105f740804c30320544)

### Steps to reproduce

1. Update to 3.2.0-alpha.6.3
2. Try to create a Show entry.

### Additional info

- Craft version: 3.2.0-alpha.6.3
- PHP version: 7.2.18
- Database driver & version: MySQL 5.6.43
- Plugins & versions: Reverse Relations 1.1.5

**Comment by brandonkelly** [comment]
Can you send your `composer.lock` and `composer.json` files, and a database backup, over to support@craftcms.com?

**Comment by tinchalamo** [comment]
Done! Thanks for checking it out.

**Comment by brandonkelly** [comment]
Fixed in Craft 3.2 Alpha 7
