### ISSUE TITLE
Matrix block fields suddenly appear as a layout tab of user accounts

### ISSUE THREAD

**Issue by mdominguez** [craftcms/cms#4313]
### Description
I've experienced this issue with a couple of sites now that are built up from a base project.yaml file in my base starter project.
The problem is that some underlying fields of a specific Matrix field on a sudden point in time get added as a layout tab 'Content' under the user accounts (including the admin account). (very weird)
In this screenshot you'll immediately see what I mean => [view screenshot](https://cl.ly/4f5e09143b89)

Deleting these unwanted fields from the User account layout works, but by doing this I somehow break that Matrix field (which had nothing to do with the User account in the first place). So I get the following error when accessing the front-end which loads that matrix field:
```
Invalid Configuration – yii\base\InvalidConfigException
Invalid field layout ID: 10
```

Must be that here's something wrong with that Matrix field in the project.yaml file I'm starting of. You can find it here => [project.yaml](https://www.dropbox.com/s/0stqpst848ujl9h/project.yaml?dl=0)

If you need more info or resources to investigate this issue, feel free to get in touch!
Thanks in advance!

### Additional info

- Craft version: 3.1.28
- PHP version: 7.3
- Database driver & version: MariaDB, n/a
- Plugins & versions: n/a

**Comment by p1729** [comment]
Faced similar kind of issue on project config rebuild ....one of field layout gets into the field layout of users

**Comment by andris-sevcenko** [comment]
Yeah, there was a bug pre-3.1.27 where running a project config rebuild could add a random field layout (and matrix block types also have field layouts) to the user settings. In the project.yaml file linked in the original issue you can see the fields listed under "users.fieldLayouts" key, almost at the end of the file.

The best way to fix this is to edit the project.yaml file, delete the contents of "users.fieldLayouts" and run project config sync.

**Comment by jenibelle08** [comment]
The solution above didn't work for me. I still get "Invalid field layout ID: 1" whether I delete this extraneous tab and set of fields in the CP or in the Project Config directly. Are there any other possible solutions?

**Comment by brandonkelly** [comment]
@jenibelle08 Can you send your `composer.json` and `composer.lock` files, and a database backup, over to support@craftcms.com?

**Comment by olivierbon** [comment]
Fixed in Support.
