### ISSUE TITLE
Element Index Column configuration gets unwieldy with fields outside the global namespace

### ISSUE THREAD

**Issue by BenParizek** [craftcms/cms#4314]
The following issue describes a UI issue we run into with Sprout Forms. The issue may exist in other similar scenarios.

![Form Element Index Customization](https://d2ddoduugvun08.cloudfront.net/items/423S0B3V3b3T1j0p341l/Image%202019-05-16%20at%2012.43.06%20PM.png?X-CloudApp-Visitor-Id=1632995)

Sprout Forms has a Custom Element where users can add custom fields. Those fields are stored outside the `global` context like matrix blocks:

| Element | Field Context | Edit Visibility |
|:-------- |:--------------|:-------- |
| Entry      | global  | Via the Craft Fields tab |
| Matrix Block | matrixBlockType:1 | Via a specific Matrix Field settings |
| Form | sproutForms:1 | Via a specific Form Field Layout |

When viewing the Element Index view for the Form Entries, a user can customize what columns appear, however, as seen in the screenshot above, that view shows ALL fields regardless of what Form Source is being shown. 

In many cases Forms are used by marketing departments for short-term campaigns, leading to a lot of similar fields being created. One solution could be to create all these fields in the Global context but that also can lead to an intimidating number of not-so-relevant fields to choose from when working within Craft on any other field layout.

It seems this use case falls between the Entry and Matrix Block use cases in that the fields are outside of the global scope and they are also visible to the Element Index page.

**Comment by BenParizek** [comment]
This may relate, or be more relevant to Craft Elements if Field Instances are added:
https://github.com/craftcms/cms/issues/2403

**Comment by brandonkelly** [comment]
Excited to say that I found a non-breaking way to fix this for Craft 3.5 🎉

To take advantage of the fix, element types will need to start implementing a `defineFieldLayouts()` method, which returns any field layouts that are associated with a given element source key.

Examples:

https://github.com/craftcms/cms/blob/8678b515a539cef7d20e7464fdb0b62fe8179d52/src/elements/Asset.php#L297-L308

https://github.com/craftcms/cms/blob/8678b515a539cef7d20e7464fdb0b62fe8179d52/src/elements/Entry.php#L261-L283

`craft\base\Element::defineFieldLayouts()` returns all field layouts associated with the element type by default, so if you don’t override it, there won’t be any discernible difference compared to how things currently work (all previewable custom fields used by the element type will be available for all sources).

Using the same method to help filter the available sort options based on the selected source as well (#4802).
