### ISSUE TITLE
[3.2] Validation no longer working

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#4316]
### Description
I was testing the new "validate related entries" in relation fields and it looks like something has broken with entry validation on the latest 3.2 alpha (6.4). I am able to save entries with empty fields that should be required. 

Here's a video I recorded: https://venveo.d.pr/GUVLFU

### Steps to reproduce

1. Create a section with some required fields
2. Try to save and it will succeed

### Additional info

- Craft version: 3.2.0-alpha.6.4
- PHP version: 7.2
- Database driver & version: N/A

**Comment by brandonkelly** [comment]
Thanks for reporting that, fixed for the next release.
