### ISSUE TITLE
The plugin store fails "not gracefully" when project.yaml is not writeable

### ISSUE THREAD

**Issue by echantigny** [craftcms/cms#4319]
### Description

I bought Craft Pro, Commerce and Wishlist.   The craft pro license goes through without a itch, but the Commerce and Wishlist licenses did not register automatically.  The Stripe payment form kept the "in progress rotator" and never gave me an error.  When that happened, I noticed Craft was Ok but the 2 plugins were not so I bought again, with same result.

At that point, I logged in to my Craft ID to notice the 2 invoices.  Tried to use the license key manually, getting an Unknown Error.  After playing around a bit, though about the project.yaml file and made it writeable.  Added the license manually again and it works.

I understand that the file should be writeable, but there must be a more graceful way you can make this fail and letting the users know.

PS:  I have sent an email to support about the double charge.

### Steps to reproduce

1. Project.yaml file NOT writeable
2. Buy Craft Pro and some plugins
3. Craft is active, but not the plugins
4. Add license manually, not working
5. Make project.yaml writeable
6. Activate licenses manually, works

### Additional info

- Craft version: Craft Pro 3.1.27
- PHP version: 7.2.8
- Database driver & version: MySQL 5.7.26
- Plugins & versions:

Craft Commerce | 2.1.6.1
Wishlist | 1.0.6

**Comment by skramstad** [comment]
Same "issue" here. Craft is not able to check licenses when
`'allowAdminChanges' => false,` in prod. As soon as I set `'allowAdminChanges' => true,` and refresh the admin page and click on solve button, the license warning goes away. I then set `'allowAdminChanges' => false`, and all good.

**Comment by brandonkelly** [comment]
@skramstad what version of Craft are you running?

**Comment by skramstad** [comment]
@brandonkelly 3.3.19 Pro.

**Comment by brandonkelly** [comment]
@skramstad I think your issue is different than @echantigny’s. His is about not being able to store new plugin licenses when `project.yaml` isn’t writable; not about the `allowAdminChanges` config setting. Please post a new issue with a little more detail including the nag alert you were getting (as best as you can remember it).

**Comment by brandonkelly** [comment]
There are several things that will break if `project.yaml` isn’t writable, so I just went with the nuclear option: now all pages on the control panel will show a nag alert if:

- the current user is an admin,
- `useProjectConfigFile` is enabled, and
- `project.yaml` is not writable

![An alert in the control panel saying that project.yaml isn’t writable](https://user-images.githubusercontent.com/47792/72352694-94a4a080-3697-11ea-82f9-0163e46697d0.png)

**Comment by echantigny** [comment]
@brandonkelly Thanks, that should do the trick to get our attention.  It doesn't solve the plugin licenses not activating when the file is not writeable though (or was that taken care of elsewhere?).  Should still activate the license, or at least, not let you buy at all if there's an issue with the project file.

**Comment by brandonkelly** [comment]
Plugin licenses are stored in the project config, so if there’s a problem writing to that, you will be SOL. (Along with dozens of similar issues.) Hence the nag alert.

**Comment by skramstad** [comment]
Thanke for clearing that up @brandonkelly.

One more question:

> Plugin licenses are stored in the project config, so if there’s a problem writing to that, you will be SOL. (Along with dozens of similar issues.) Hence the nag alert.

Are we able to check and validate licenses i dev wheres the project config is writable and it will be OK in prod? Or does it need to check for valid licenses once its in prod too?

**Comment by brandonkelly** [comment]
License validation happens on all environments. You just won’t be able to do anything about validation errors on environments with `allowAdminChanges` disabled.
