### ISSUE TITLE
Allow some field settings to be overridden from the field layout designer

### ISSUE THREAD

**Issue by jlawrence-yellostudio** [craftcms/cms#4321]
If I create a field for example "Related Entry" with a limit of 1, I can only use this in other field layouts where only one related entry is also desired. Resulting in me having to create multiple fields for essentially the same purpose, with slight variations in the settings.

If the Limit could be set on the field layout, that would be great; I don't expect this to be easy as "limit" isn't a global setting same as the "required" flag is. 

Maybe you could add an extra column in the fieldlayoutfields table which could accommodate some non global settings and grab the limit from there? 

What do you think @brandonkelly ?

**Comment by brandonkelly** [comment]
I’m not sure I’m following. The “Branch Limit” setting is currently only available on Categories fields, not Users fields. Is “Related User” a Categories field? Or did you mean the “Limit” setting?

**Comment by jlawrence-yellostudio** [comment]
@brandonkelly Apologies I meant limit, not branch limit.

My real life example was actually to do with entries, I have to create an additional field pointing at exactly the same entry source for the same purpose just because the limit is global to that field.

**Comment by brandonkelly** [comment]
Gotcha. It’s similar to #806 (ability to rename fields from the field layout designer) and #841 (ability to override the field instructions from the field layout designer).

We have plans to explore all of this (including overriding field type-specific settings) from the field layout designer as part of a larger content refactoring project we’re planning for Craft 4 (#1524).

Good to have specific issues we can reference as we’re working on the changes, though, so I will keep this open and add it to the 4.0 milestone.

**Comment by jlawrence-yellostudio** [comment]
thanks @brandonkelly
