### ISSUE TITLE
Multi-site entry propagation can result in a partially broken section

### ISSUE THREAD

**Issue by thisisjamessmith** [craftcms/cms#4322]
### Description

If you change your mind about whether to propagate entries across sites and flick the switch back again _before_ the entries have finished automatically resaving, you'll end up with a pretty horrible situation where everything looks fine but saving an entry in one site will delete its corresponding one in the other site that it was propagated from, even though there should be no propagation.

I appreciate there's a little warning underneath the switch that says it may result in data loss, but I don't think that statement anticipated this exact situation (the data loss should be consistent and repeatable, but this is not).

### Steps to reproduce

1. Have a multi-site setup with a section that has several relatively long entries so that the automatic saving task will take enough time for us to cause mischief...
2. Tick the propagate entries checkbox in the section and save, triggering the auto saving task.
3. Before the task has completed, click into the section again and untick the propagate entries checkbox.

You'll now have a situation where some entries have propagated, but the section settings think there should be no propagated entries. Saving one of the propagated ones will delete the corresponding entry in the other site.

### Additional info

- Craft version: 3.1.26
- PHP version: 7.1

**Comment by brandonkelly** [comment]
> Saving one of the propagated ones will delete the corresponding entry in the other site.

That seems like expected behavior to me.

Any time you save an entry, Craft will ensure that A) it has been propagated to all of the sites that the entry _should_ exist in; and B) doesn’t exist for any sites that the entry _shouldn’t_ exist in.

If site propagation has been disabled for a section, and you save an entry that currently exists in 2+ sites, then the correct behavior would be that Craft removes that entry from all but the site you are currently saving it in.

**Comment by thisisjamessmith** [comment]
My problem is not really with how Craft resolves the situation, which as you say makes sense. The problem is that you shouldn't be able get into this situation in the first place, and once you have, it's not immediately obvious that anything has gone wrong. You can be looking at a list of entries, not realising that some of them are propagated ones, while others have subsequently been manually added. Then the first person to save a propagated one in whichever site they happen to be in will arbitrarily trigger a deletion in the others - for us this resulted in the unexpected deletion of a live entry, and scrambling to figure out how this possibly could have happened.
