### ISSUE TITLE
Attempting to duplicate an unsaved element

### ISSUE THREAD

**Issue by tinchalamo** [craftcms/cms#4331]
### Description
When creating a new entry and clicking "Update entry" instead of "Save as a new entry" I get this error: "Attempting to duplicate an unsaved element". [Link to stacktrace](https://gist.github.com/tinchalamo/748e305c7e3d583cc33916c9bade0f6b).

### Steps to reproduce

1. Create a new entry
2. Click on "Update entry" before clicking on "Save as a new entry".

### Additional info

- Craft version: Craft Pro 3.2.0-alpha.7
- PHP version: 7.3.2
- Database driver & version: MySQL 5.6.34
- Plugins & versions: Super Table 2.1.20

**Comment by tinchalamo** [comment]
This also happens when updating an already saved entry.

**Comment by brandonkelly** [comment]
This should be fixed now for the next release.
