### ISSUE TITLE
pathParam breaks admin login

### ISSUE THREAD

**Issue by jmverges** [craftcms/cms#4334]
### Description

/admin/login path is not found after changing .htaccess RewriteRule (.+) index.php?testpath=$1 [QSA,L] and general.php ['*']['pathParam'] = 'testpath',

### Steps to reproduce

1. Change .htaccess Rewrite rule to a different parameter than **p**
2. Adds to general.php config file, under asterisk key pathParam to something different than p
3. Go to Frontend of the site: It works.
4. Go to /admin and try to login: It fails. Console log under chrome says: 
jquery.js:9827 POST http://mydomain.test/index.php/users/login?testpath=admin/actions 403 (Forbidden)
jquery.js:9827 XHR failed loading: POST "http://mydomain.test/index.php/users/login?testpath=admin/actions".

### Additional info

- Craft version: Craft Pro 3.1.28
- Server version: Apache/2.4.34 (Unix)
- PHP version: 7.2.9
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
    "craftcms/ckeditor": "1.0.0-beta.2",
    "craftcms/cms": "^3.0.0",
    "craftcms/postmark": "^2.0.1",
    "fruitstudios/linkit": "^1.1.11",
    "misterbk/mix": "^1.5.2",
    "mmikkel/cp-field-inspect": "^1.0.5",
    "nystudio107/craft-imageoptimize": "^1.5.4",
    "nystudio107/craft-typogrify": "^1.1.17",
    "spicyweb/craft-neo": "^2.3.0",
    "topshelfcraft/environment-label": "^3.1.5",
    "trendyminds/molecule": "^1.2.0",
    "vlucas/phpdotenv": "^2.4.0",
    "verbb/field-manager": "^2.1.0",
    "craftcms/redactor": "^2.3",
    "verbb/navigation": "^1.1.12"

**Comment by jmverges** [comment]
Apparently what is breaking is the AJAX calls. If I remove the changes, and I login to access the /admin, once inside, I make this changes again and I can navigate through the different admin sections but data is not loaded as XHR calls are failing

**Comment by jmverges** [comment]
looks like there is some hardcoded string here: https://github.com/craftcms/cms/blob/develop/src/web/assets/cp/src/js/Craft.js#L202

that makes  https://docs.craftcms.com/v3/config/config-settings.html#pathparam non usable

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.
