### ISSUE TITLE
Entries Sort has repeated fields

### ISSUE THREAD

**Issue by tinchalamo** [craftcms/cms#4336]
### Description
In viewing any of the entries lists in the admin, the sort by dropdown has a lot of repeated fields.

![image](https://user-images.githubusercontent.com/11000310/58642823-aaf61b80-82c3-11e9-878e-6825572a66d2.png)

### Steps to reproduce

1. View an entries list
2. Activate sort by dropdown

### Additional info

- Craft version: 3.2.0-alpha.7
- PHP version: 7.3.2
- Database driver & version: MySQL 5.6.34
- Plugins & versions:
    "craftcms/cms": "3.2.x-dev#53f00211fe868b3935f14cce7ef713f00b59002e",
    "vlucas/phpdotenv": "^2.4.0",
    "craftcms/redactor": "2.3.3.2",
    "mmikkel/incognito-field": "1.1.1.1",
    "rias/craft-position-fieldtype": "1.0.14",
    "markhuot/craftql": "1.3.2",
    "verbb/super-table": "2.1.20",
    "marionnewlevant/match-input": "v2.0.1",
    "fruitstudios/linkit": "1.1.11",
    "nfourtythree/entriessubset": "1.2.1",
    "craftcms/aws-s3": "1.2.2",
    "nystudio107/craft-units": "1.0.3",
    "doublesecretagency/craft-cpcss": "2.1.0",
    "doublesecretagency/craft-smartmap": "3.2.2.1",
    "craftcms/store-hours": "2.1.1.1",
    "elivz/craft-single-cat": "1.2.1",
    "fortrabbit/craft-copy": "1.0.0-RC5",
    "aelvan/preparse-field": "v1.0.6",
    "spicyweb/craft-fieldlabels": "1.1.1",
    "rias/craft-password-policy": "1.0.4",
    "craftcms/element-api": "2.5.4",
    "craftcms/feed-me": "4.1.0",
    "verbb/workflow": "1.1.9",
    "robuust/craft-reverserelations": "1.1.5",
    "mmikkel/cp-field-inspect": "1.0.5",
    "doublesecretagency/craft-inventory": "2.0.2",
    "fortrabbit/yii-memcached": "^1.0",
    "putyourlightson/craft-sendgrid": "1.1.0",
    "doublesecretagency/craft-cpjs": "2.1.0",
    "doublesecretagency/craft-cpbodyclasses": "2.1.0",
    "solspace/api-caller": "*"

**Comment by brandonkelly** [comment]
The culprit for this one was a service method (`craft\services\Fields::getFieldsByElementType()`) tat also affects Craft 3.1, so just fixed it there, and merged the fix into the `3.2` branch for the next alpha release.
