### ISSUE TITLE
Inconsistent Tranform URLs

### ISSUE THREAD

**Issue by JustJarethB** [craftcms/cms#4341]
### Description
URLs returned by image transforms seem to be inconsistent. 
Example:
```
{{ asset.getUrl }} => '/relative/path/file
{{ asset.getUrl('handle') }} => 'https://site.com/index.php?p=actions/assets/generate-transform&transformId=339
{{ asset.getUrl('handle') }} => '/relative/path/_handle/file
```

Usually, this is not a huge deal, but consider we are attempting to generate HTML for an email - now the unreliable relative/static linking is problematic.

### Steps to reproduce

1. Apply new transform to image and inspect first time URL
2. Reload and inspect same URL once image is generated
3. Inspect URL of image without transform

### Additional info

- Craft version: Craft Pro 3.1.14
- PHP version: 7.2.18
- Database driver & version: MySQL 5.7.26
- Plugins & versions:

**Comment by brandonkelly** [comment]
You can get Craft to generate transforms immediately with the [generateTransformsBeforePageLoad](https://docs.craftcms.com/v3/config/config-settings.html#generatetransformsbeforepageload) config setting. With that enabled, transform URLs will always be the generated image URLs.
