### ISSUE TITLE
Transform (sometimes) incorrectly cropping left and right edges

### ISSUE THREAD

**Issue by mediagirl** [craftcms/cms#4346]
### Description
A simple transform of width: 155 is cropping approximately 1px from the left and right edges of certain images... not all of them. 

### Steps to reproduce

1. Upload this logo: [
![logo-danone](https://user-images.githubusercontent.com/249311/58725735-2081ea80-839d-11e9-94e2-5cc6d55f3a22.png)
](url)   
2. Set transform to: {% set image = partnerLogo.one().setTransform({ width: 155 }) %}   
3. You'll see approximately 1px from the left and right is incorrectly cropped: https://www.screencast.com/t/DP87Sjx0s5
4. On my project, this isn't happening with every image but it is happening with several of them including the one I'm attaching.
### Additional info

- Craft version: Craft CMS 3.1.28
- PHP version: 7.3.2

**Comment by andris-sevcenko** [comment]
The default transform mode is "crop" which basically is "scale down as precisely as we can and crop". That image has the dimensions of 300x93, so scaling that down to 155 leaves us with 48.05px vertically. In this case, the casualty was 1px on the side edges, but in other cases, it might end up being the top and bottom edges.

To avoid this you should either use the "fit" transform mode or upload images with proportions that scale precisely (in which case it would produce the same result as using the "fit" mode, anyway).

**Comment by mediagirl** [comment]
Thank you Andris for this explanation. I’ll start using the FIT mode going forward. That’s the behavior I thought would be used if only the width was set.

Anna
------------------------

Anna Brown
MediaGirl, Inc.
anna@mediagirl.com
Office: (505) 350-6520
www.mediagirl.com
