### ISSUE TITLE
"Activate your account" email uses siteUrl instead of baseCpUrl

### ISSUE THREAD

**Issue by codyjames** [craftcms/cms#4349]
### Description
"Activate your account" email uses siteUrl instead of baseCpUrl.

### Steps to reproduce

1. Set baseCpUrl to something different than siteUrl
2. Create a new user
3. "Activate your account" action url will use siteUrl rather than baseCpUrl.

### Additional info

- Craft version: 3.1.25

**Comment by brandonkelly** [comment]
Are you sure the user had the “Access the CP” permission at the time their activation email was sent? If not, it is expected that Craft would send them a front-end activation URL.
