### ISSUE TITLE
Javascript error when saving an entry with a dynamic title

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#4353]
### Description
We've run into a javascript error when trying to save and entry with a dynamic title.
I can reproduce it across 2 installs and made a screen recording:

https://drive.google.com/file/d/1g1BWPCrbsiMAVa01rR5pb_1jQ7IDuVZl/view?usp=sharing

### Steps to reproduce

1. Create a section with 2 entry types, the first one with a regular title field and the second one with a dynamic title field
2. Create a new entry, switch to the type with the dynamic title
3. Press cmd+S

The problem doesn't present itself when the title is set to dynamic for both types.

### Additional info

- Craft version: 3.1.28
- PHP version: 7.2.10
- Database driver & version: 5.7.22
- Plugins & versions:
Dumper 	1.3.1
Freeform 	2.5.24
ImageOptimize 	1.5.6
Mandrill 	1.3.1
Navigate 	2.2.1
Redactor 	2.3.3.2
SEO 	3.5.4
Translate 	1.1.5

**Comment by brandonkelly** [comment]
Fixed for today’s release. Thanks for reporting!

**Comment by janhenckens** [comment]
Thanks for the quick fix!
