### ISSUE TITLE
Image editor crop constraints only let you crop landscapes

### ISSUE THREAD

**Issue by johandouma** [craftcms/cms#4359]
### Description

When using constrained cropping in the image editor, it only gives me landscape options, ie 16/9, 4/3, 3/2 etc... but as far as I can see, there are no options to swap the orientation to portrait, ie 9/16, 3/4, 2/3 etc... So I need to rotate the picture 90 degrees first, then crop it, then rotate it back 90 degrees, which is very tedious. If it's possible at all without rotating the pictures first, I can't find how to do it. 

### Steps to reproduce

1. Edit an asset
2. Go to the crop tool
3. Select constraint
4. Try to crop something to a portrait size

### Additional info

- Craft version: 3.1.28
- PHP version: 7.3.4
- Database driver & version: MySQL
- Plugins & versions: 
Amazon S3 1.2.2
Asset Rev 6.0.2
AsyncQueue 2.0.0
CP Field Inspect 1.0.5
Calendar Links 1.0.1
Dumper 1.3.1
Expanded Singles 1.0.7
Hutsixassets 0.3.3
Imager v2.1.10
Migration Manager 3.0.22
NSM Fields 0.0.14
Position Fieldtype 1.0.14
Redactor 2.3.3.2
Redirect plugin for Craft 3 1.0.23
Simple Sharing 1.0.4
Super Table 2.1.20
Table Maker 2.0.1
Typed link field 1.0.19
Wordsmith 3.0.5
XML Sitemap 1.0.9

**Comment by brandonkelly** [comment]
Here’s what I think we should do, @andris-sevcenko:

- Move the aspect ratio menu to its own line, separate from Focal Point
- When something besides Unconstrained, Original, or Square is selected, add an orientation selector beside it, similar to Photos.app:
  <img width="173" alt="Aspect ratio options in Photos" src="https://user-images.githubusercontent.com/47792/58957849-600e5500-8756-11e9-9e11-2924b7a1283a.png">
- While you’re at it, maybe worth adding a “Custom…” option to the menu as well. When selected, two small text inputs should be added next to the menu (size=3) with a `:` between them, default values set to `1` and `1` (square). Each time either of the values change to a valid aspect ratio, update the crop tool as if a normal option had been selected. (The orientation selector would **not** be visible when “Custom…” is selected, by the way.)

**Comment by dsp303** [comment]
+1 for custom cropping ratios, would be great!

**Comment by jsunsawyer** [comment]
It'd be nice if we could set up the default crop ratios from a config file so we can populate the list with crops that are used in a given site. Being able to give each of these crops a name could also be useful.

**Comment by andris-sevcenko** [comment]
This will be a part of the next 3.4 release!
