### ISSUE TITLE
User element behaviors event not being triggered

### ISSUE THREAD

**Issue by tim-pixeldeluxe** [craftcms/cms#4362]
### Description
The EVENT_DEFINE_BEHAVIORS event isn't being triggered for the User element. I'm trying to add some extra functions to the currentUser variable (aka the User element) but the event is never triggered.

This works fine:
```php
Event::on(
    \craft\elements\Entry::class,
    \craft\elements\Entry::EVENT_DEFINE_BEHAVIORS,
    function (Event $event) {
        exit('test');
    }
);
```

This even isn't being triggered:
```php
Event::on(
    \craft\elements\User::class,
    \craft\elements\User::EVENT_DEFINE_BEHAVIORS,
    function (Event $event) {
        exit('test');
    }
);
```

### Steps to reproduce

1. Create an event listener to define User element behaviors
2. Try using the new functions on the currentUser variable (frontend)
3. "Calling unknown method: craft\elements\User::myFunction()"

### Additional info

- Craft version: 3.1.28
- PHP version: 7.1.6
- Database driver & version: MySQL 5.5.59
- Plugins & versions:
```php
"php": ">=7.0.0",
"craftcms/cms": "^3.1.24",
"vlucas/phpdotenv": "^2.4.0",
"craftcms/aws-s3": "1.2.2",
"ether/logs": "v3.0.0",
"verbb/cp-nav": "2.0.9",
"verbb/expanded-singles": "1.0.7",
"twbs/bootstrap": "4.0.0-beta.2",
"verbb/super-table": "2.1.20",
"topshelfcraft/wordsmith": "3.0.5",
"verbb/field-manager": "2.1.0",
"mmikkel/cp-field-inspect": "1.0.5",
"sebastianlenz/linkfield": "1.0.19",
"mikestecker/craft-videoembedder": "1.1.3",
"ether/seo": "3.5.4",
"lukeyouell/craft-hideadmin": "1.0.1",
"supercool/tablemaker": "2.0.1",
"doublesecretagency/craft-siteswitcher": "2.1.0",
"anubarak/craft-relabel": "1.3.1",
"mmikkel/child-me": "1.0.4",
"craftcms/element-api": "^2.5",
"carlcs/craft-redactorcustomstyles": "^3.0",
"craftcms/contact-form": "2.2.5",
"nystudio107/craft-cookies": "^1.1",
"craftcms/redactor": "2.3.3.2",
"craftcms/feed-me": "4.1.0",
"ttempleton/craft-nocache": "^2.0",
"matt-west/craft-recaptcha": "^1.3"
```

**Comment by brandonkelly** [comment]
`craft\elements\User` isn’t overriding `behaviors()` so there’s nothing that could stop the event from firing.

Do you have any plugins or modules that could be listening for the same event, and perhaps marking the event as `handled`? (If an event handler marks an event as `handled`, Yii won’t call any additional handlers.)

**Comment by tim-pixeldeluxe** [comment]
Just used ctrl + f to search in my entire project (including the vendor). The only places I found EVENT_DEFINE_BEHAVIORS were inside the Craft source code (vendor), my own plugin (the event listener that isn't working), inside a web.log (I caused an error when setting up a behavior for Request earlier) and a Craft changelog.
https://pastebin.com/RrPeWjVN

I have already tried deleting my vendor and re-installing it (which often fixes strange bugs) but that didn't work this time. I've also looked at the Craft source code before making this report to see if behaviors() was being overwritten. This wasn't the case and you've confirmed this (thanks).

Are you able to reproduce this?

**Comment by brandonkelly** [comment]
Just verified that it’s working for me.

Most likely the user is just getting loaded before your event handler is registered. Where are you putting your `Event::on()` code? It should be within a plugin or module, from the `init()` method. And if it’s in a module, make sure you are listing the module ID within the `'bootstrap'` key in the array returned by `config/app.php`.

```php
return [
    'modules' => [
        'my-module-id' => my\Module::class,
    ],
    'bootstrap' => ['my-module-id'],
];
```

**Comment by tim-pixeldeluxe** [comment]
I'm using a plugin and my event handler is registered from within the init() function. 

Not sure where the currentUser global is set? Are plugins loaded before that? I noticed that my plugin doesn't load when accessing the CP login screen. When I try to login the ajax call does trigger my event as the response is "test". So I think the currentUser variable might be set before loading the plugins.

**Comment by brandonkelly** [comment]
`currentUser` is just a reference to whatever [yii\web\User::getIdentity()](https://www.yiiframework.com/doc/api/2.0/yii-web-user#getIdentity()-detail) returns for the request (the logged-in user):

https://github.com/craftcms/cms/blob/cb6e3054dd4351653329da508616c15dd0e69874/src/web/twig/Extension.php#L1029

The logged-in user is queried, instantiated (along with its `EVENT_DEFINE_BEHAVIORS` getting triggered) the first time that `getIdentity()` method is called in the request, which is almost certainly going to be before the point when the `currentUser` global variable is getting set.

If you have Xdebug, set a breakpoint on [line 189](https://github.com/yiisoft/yii2/blob/694a1410e8fdd5a2aafce02276e06db33572cc13/framework/web/User.php#L189) of `vendor/yiisoft/yii2/web/User.php`, and another one in your `init()` method where you’re registering the event listener. That should show you why `getIdentity()` is getting called first (assuming its breakpoint is hit first).

If not, send over your `composer.json` and `composer.lock` files, plus any other custom plugins/modules you may be referencing in `composer.json` and a database backup, over to support@craftcms.com and we can try to look into it for you.

**Comment by tim-pixeldeluxe** [comment]
Don't have Xdebug unfortunately. Will send some more info via mail.

I also used the Yii debug bar to see whether the event is being fired. Not sure if it helps, but it might.
Frontend page:
https://i.postimg.cc/FKvbMmkS/Schermafbeelding-2019-06-05-om-10-07-04.png

CP dashboard:
https://i.postimg.cc/Njm7CLFY/Schermafbeelding-2019-06-11-om-09-02-25.png

The event also wasn't fired when I'm on the myAccount page in the CP.

**Comment by tim-pixeldeluxe** [comment]
Update: I have been installing all of my plugins one by one on a clean install. Whenever I install one of these two plugins the event is no longer fired: "CP Field Inspect", "Child Me!".

**Comment by tim-pixeldeluxe** [comment]
Update 2: Whenever I place the following code inside my plugin's init function the event is no longer fired:
```php
$user = Craft::$app->getUser();
$isAdmin = $user->getIsAdmin();
```

**Comment by tim-pixeldeluxe** [comment]
Screenshots of Yii debug

Without $user->getIdentity() in my plugins init function:
![Schermafbeelding 2019-06-11 om 10 59 52](https://user-images.githubusercontent.com/46448696/59258388-2b0f7000-8c38-11e9-98c0-020f24d6bd7d.png)

With $user->getIdentity() in my plugins init function:
![Schermafbeelding 2019-06-11 om 11 00 20](https://user-images.githubusercontent.com/46448696/59258433-42e6f400-8c38-11e9-823a-080aa67d519a.png)

**Comment by brandonkelly** [comment]
> Update 2: Whenever I place the following code inside my plugin's init function the event is no longer fired:
> 
> ```
> $isAdmin = $user->getIsAdmin();
> ```

Are you calling that before or after registering your event handler?

If you register the event handler _after_ calling `getIsAdmin()` (or anything else that will ultimately call `getIdentity()`, then it’s too late, the user has already been registered and their behaviors have already been set.

**Comment by tim-pixeldeluxe** [comment]
> > Update 2: Whenever I place the following code inside my plugin's init function the event is no longer fired:
> > ```
> > $isAdmin = $user->getIsAdmin();
> > ```
> 
> Are you calling that before or after registering your event handler?
> 
> If you register the event handler _after_ calling `getIsAdmin()` (or anything else that will ultimately call `getIdentity()`, then it’s too late, the user has already been registered and their behaviors have already been set.

Its registered after that function is called so that explains a lot. Is there any way I can register my event before the other plugins are loaded? Thanks in advance!

**Comment by brandonkelly** [comment]
> Is there any way I can register my event before the other plugins are loaded?

Not without getting those plugins to stop grabbing the user identity from their `init()` methods, maybe holding off until [EVENT_AFTER_LOAD_PLUGINS](https://docs.craftcms.com/api/v3/craft-services-plugins.html#event-after-load-plugins) event.

That’s probably not very practical though. So instead maybe just check if there’s a logged-in user, and if so attach it right from your `init()` method, otherwise register the event:

```php
$user = Craft::$app->user->getIdentity();
if ($user) {
    $user->attachBehavior('my-behavior', new MyBehavior());
} else {
    Event::on(User::class, User::EVENT_DEFINE_BEHAVIORS, function(DefineBehaviorsEvent $e) {
        $e->behaviors['my-behavior'] = new MyBehavior();
    });
}
```
