### ISSUE TITLE
Setting an entry URI to {uid} requires the entry to be saved twice to take effect

### ISSUE THREAD

**Issue by Harry-Harrison** [craftcms/cms#4364]
### Description
This works as expected `{id}`, but not `{uid}`

### Steps to reproduce

1. Make a channel and create an entry type
2. In the Element Index for the new channel, reveal the URI column
3. Set the entry type's URI pattern to be `{uid}`
4. Create an entry in the previously made channel
5. The the URI column will be empty
6. Re-save the entry with no other changes
7. The URI column will have the entries UID as it's URI now

### Additional info

- Craft version: Craft Pro 3.1.28
- PHP version: 7.2.19
- Database driver & version: MySQL 5.7.26
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
Just fixed that for the next release!

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#a78c7045e2db2079311076472217f8f415745e5a",
  "...": "..."
}
```

Then run `composer update`.

**Comment by Harry-Harrison** [comment]
Awesome, thanks @brandonkelly!

**Comment by Harry-Harrison** [comment]
@brandonkelly So this doesnt seem to be totally fixed. Thought im not sure if this should be a separate issue. It works through the admin panel, but when using the Guest Entries plugin to update an entry the URI is removed when it's just the entry's uid.

**Comment by brandonkelly** [comment]
@Harry-Harrison The Guest Entries plugin is just for creating new entries. You’re using it to update existing ones?

**Comment by Harry-Harrison** [comment]
@brandonkelly Yeah sorry, I should've been clearer. I saw [this post](https://craftcms.stackexchange.com/a/28321) from yourself. That all actually works fine and I'm not setting the URI or the slug at any point in my form. If I set the Entry URI Format on the section to just `{id}` it works as expected. If I set it to `{uid}` after an update from the guest entries plugin it does not.

**Comment by brandonkelly** [comment]
@Harry-Harrison Ah gotcha. Just updated that answer with a better way of doing it, which would also maintain the entry UID.

**Comment by Harry-Harrison** [comment]
@brandonkelly Thanking you muchly, that seems to be working a treat.

**Comment by jamiepittock** [comment]
Hey @brandonkelly I think this may have been reintroduced. I'm having the same problem and can reproduce using the same steps as Harry listed above.

I've tested it using a fresh install of **Craft 3.5.13.2** with no plugins installed.

The first entry I create gets no {uid} in it's URI. If I create a second entry, it gets a {uid} in it's URI but the entry is disabled.

<img width="692" alt="Screenshot 2020-10-16 at 15 18 33" src="https://user-images.githubusercontent.com/35454/96270097-1c229580-0fc3-11eb-98d3-b3ea80d92197.png">

<img width="1055" alt="Screenshot 2020-10-16 at 15 19 05" src="https://user-images.githubusercontent.com/35454/96270111-204eb300-0fc3-11eb-9f28-025fbbfca7e7.png">

**Comment by brandonkelly** [comment]
@jamiepittock Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.14 is out now with that fix.
