### ISSUE TITLE
[3.2] Image Resizer causes error

### ISSUE THREAD

**Issue by tinchalamo** [craftcms/cms#4366]
### Description
Latest Craft 3.2 Beta was working fine until I installed Image Resizer. I got an "Unknown error occured" message everytime I uploaded an asset. Upon trying to update the entry I got an error screen. [Here's the stracktrace](https://gist.github.com/tinchalamo/59c8a776c65448164820a749f4ea5e15).

### Steps to reproduce

1. Install Image Resizer and point to asset source.
2. Upload image to an asset field.
3. Click on "Update Entry"

### Additional info

- Craft version: Craft Pro 3.2.0-beta.1
- PHP version: 7.3.2
- Database driver & version: MySQL 5.6.34
- Plugins & versions: "verbb/image-resizer": "2.0.5"

**Comment by brandonkelly** [comment]
Do you see any other errors in your logs? (Search for `[error]`.) The one in your stack trace seems completely unrelated to Image Resizer.

**Comment by tinchalamo** [comment]
@brandonkelly it is the correct stack trace and happened just after I started using Image Resizer. Let me try Image Resizer again to see if it crops up.
