### ISSUE TITLE
Filenames are not normalized on asset index

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#4372]
When you upload an asset, filenames with spaces get kebab-cased. The same does not happen when you index assets, which can be confusing.

Not sure what the expected behavior is but figured I'd mention it.

Craft 3.2-beta.1

**Comment by brandonkelly** [comment]
I don’t think it would be expected behavior for updating asset _indexes_ to make actual filename changes.

**Comment by timkelty** [comment]
👍 just wanted to make sure that was expected.
