### ISSUE TITLE
[3.2] Migration `m190529_204501_fix_duplicate_uids` takes 2 hours to complete

### ISSUE THREAD

**Issue by martinleveille** [craftcms/cms#4374]
### Description

I was trying to upgrade to 3.2.0-beta.1 for testing purpose.

The `m190529_204501_fix_duplicate_uids` migration takes 2 hours to complete when we try to migrate from 3.1.29 to 3.2.0-beta.1 on one of our large Craft site.

Our `elements` table have 50986 rows in it.

### Screenshot

<img width="1089" alt="craft_3_2_beta_1_migrate" src="https://user-images.githubusercontent.com/534656/59043330-08e9ac80-884a-11e9-98dc-3e48dbc67917.png">

### Additional info

- Craft version: 3.2.0-beta.1
- PHP version: 7.2.17
- Database driver & version: MySQL

**Comment by brandonkelly** [comment]
@martinleveille Do you have a database backup from before you ran that migration? Any chance you can throw it up on Dropbox or something and share it with us at support@craftcms.com?

**Comment by martinleveille** [comment]
@brandonkelly I'll try to send you the database to your support email. Need to obfuscate users and commerce data before.

**Comment by martinleveille** [comment]
Thanks Brandon !
