### ISSUE TITLE
Save button disappearing after increasing dropdown options

### ISSUE THREAD

**Issue by tinybeans** [craftcms/cms#4376]
### Description

In the case of adding a dropdown field in a table field, I couldn’t press a save button in the dropdown setting dialogue on a because I cannot scroll inside the dialogue. In other words, the save button would disappear when I increase dropdown options a lot.

![dropdown-options-table-field-min](https://user-images.githubusercontent.com/181721/59055950-2ae73b80-88eb-11e9-848c-0818802f0e84.png)

### Steps to reproduce

1. Create a table field
2. Select a dropdown field as a column type
3. Increase dropdown options a lot

### Additional info

- Craft version: 3.2.0-beta.1
- PHP version: 7.2.17
- Database driver & version: MySQL

**Comment by brandonkelly** [comment]
This is fixed for the next release, thanks for reporting!
