### ISSUE TITLE
Asset (CDN) invalidation should also get triggered on asset alteration (rotate, resize, etc).

### ISSUE THREAD

**Issue by nateiler** [craftcms/cms#4379]
I noticed that asset invalidation is only triggered when an asset is deleted.  However, if you edit an asset (ex: rotate it via the editor), this should also trigger invalidation.

Furthermore, in order to invalidate transforms it's probably wise to support wildcard invalidation; though this may be specific to the provider.

As an example, via AWS S3 / Cloudfront we'll need to invalidate:
`path/to/asset/file.jpg` and `path/to/asset/*/file.jpg`  The `/*/` catches all the image transforms

**Comment by dsmrt** [comment]
To add to this,  here's what we are doing to hook-in via element `afterSave` (which targets aws/cloudfront assets specifically).

```php
       /** @var Asset $asset */
        $asset = $event->sender;
        if (! $asset instanceof Asset) {
            return;
        }

        /** @var Volume $volume */
        $volume = $asset->getVolume();
        if (! $volume instanceof Volume) {
            return;
        }

        $subfolder = $volume->subfolder ? '/' . $volume->subfolder : '';
        $path = $subfolder .
            '/' . $asset->getPath($asset->getFilename());
        $transformerPath = $subfolder . '/' .
            //remove the filename from the path
            str_replace($asset->getFilename(), '', $asset->getPath()) .
            '*/' . $asset->getFilename();

        // using instance profile
        $client = new CloudFrontClient([
            'region' => static::AWS_DEFAULT_REGION,
            'version' => 'latest',
        ]);

        $result = $client->createInvalidation([
            'DistributionId' => $volume->cfDistributionId,
            'InvalidationBatch' => [
                'CallerReference' => 'Craft-' . StringHelper::randomString(24),
                'Paths' => [
                    'Items' => [
                        $path,
                        $transformerPath,
                    ],
                    'Quantity' => 2,
                ],
            ],
        ]);
```

I've tried to following the logic here `\craft\awss3\Volume::invalidateCdnPath` and I think the path might be missing subfolder (see my above code). Just a heads up (I'm not 100% sure though).

**Comment by andris-sevcenko** [comment]
> I noticed that asset invalidation is only triggered when an asset is deleted. However, if you edit an asset (ex: rotate it via the editor), this should also trigger invalidation.

When you edit an image in the editor in a way that actually modifies the existing image, the previous file is deleted, triggering invalidation. 

> Furthermore, in order to invalidate transforms it's probably wise to support wildcard invalidation; though this may be specific to the provider.

Likewise, when deleting an asset, all the transforms Craft is aware of, are deleted, again, triggering invalidation.

> To add to this, here's what we are doing to hook-in via element afterSave (which targets aws/cloudfront assets specifically).

Same thing. If you do anything that causes an Asset to be replaced, the previous file is deleted, triggering invalidations for everything that Craft is aware of.

I just tested that on the latest commit of Craft 3.2 branch and that is working as expected. Have you ever noticed a scenario where this actually doesn't work and can you reproduce that consistently?

**Comment by dsmrt** [comment]
Sorry to take so long to get back to you on this. I believe this is working as expected. You can close this ticket. Thanks for the response on this!
