### ISSUE TITLE
Uninstall option is missing for disabled plugins

### ISSUE THREAD

**Issue by terryupton** [craftcms/cms#4383]
### Description
It seems the option to uninstall disabled plugins is missing.
The option is present for any active plugins. 
The following screenshots show this.
<img width="1642" alt="Screenshot 2019-06-07 at 16 26 30" src="https://user-images.githubusercontent.com/5698596/59115454-3cf3c900-8941-11e9-93af-0115a359276f.png">
<img width="1641" alt="Screenshot 2019-06-07 at 16 26 40" src="https://user-images.githubusercontent.com/5698596/59115455-3ebd8c80-8941-11e9-8663-1f72eb90c5aa.png">

Typically I would disable a plugin before deciding to remove it. 

### Steps to reproduce

1. Disabled a plugin
2. Click the cog and there is no uninstall option.
3. Click the cog for an active plugin and there is an uninstall option.

### Additional info

- Craft version: Craft Pro 3.1.29
- PHP version: 7.2.18
- Database driver & version: 	MySQL 5.5.5

**Comment by narration-sd** [comment]
believe I ran into this also, a week or two ago -- does seem Uninstall should be there for Disabled plugin, no?

**Comment by brandonkelly** [comment]
This is expected, because we don’t want to ever executing a plugin’s code if it is disabled. And plugins are responsible for uninstalling themselves to a degree, and we couldn’t do that without executing its code.
