### ISSUE TITLE
No pagination in element selector modal (3.2 beta 1)

### ISSUE THREAD

**Issue by daltonrooney** [craftcms/cms#4385]
### Description
I upgraded an existing site with about 150 images in the asset library to 3.2 beta 1. When I click on the Assets link in the dashboard, I am able to paginate through the list of all 150 images. When I try to attach an asset to an entry, I am only able to see the first 50 images and there is no pagination control. 

No console error, and searching for a particular image by filename does work.

### Steps to reproduce

1. Click on an asset field in an entry to open the element selector modal
2. Scroll to bottom of list. No way to select next page of elements.

### Additional info

- Craft version: Craft Pro 3.2.0-beta.1
- PHP version: 7.2.0
- Database driver & version: MySQL 5.6.34

**Comment by brandonkelly** [comment]
Thanks for reporting that, it’s been fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "3.2.x-dev#90d8f008a5913965c43325bb01e841ac14605876",
  "...": "..."
}
```

Then run `composer update`.
