### ISSUE TITLE
Editor forgets what tab I was in when I save an entry and continue editing (3.2 Beta 1)

### ISSUE THREAD

**Issue by daltonrooney** [craftcms/cms#4386]
### Description
In Craft 3.1, when I save and continue editing, the page refreshes and remembers what tab I was last editing. In Craft 3.2 when I update an entry, the page refreshes and I am always returned to the first tab. 

### Additional info

Craft version: Craft Pro 3.2.0-beta.1
PHP version: 7.2.0
Database driver & version: MySQL 5.6.34

**Comment by brandonkelly** [comment]
Thank for reporting that! Fixed for the next release.
