### ISSUE TITLE
Craft::$app->security->validateData() returns empty string in Twig when invalid value used

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#4387]
I'm not really sure if it counts as bug. 

When i use `Craft::$app->security->validateData()` equivalent in twig - `craft.app.security.validateData('hashes_string')`, and i place something else then proper hashed data in parameter, it returns empty string instead of false. [Docs](https://docs.craftcms.com/v3/dev/filters.html#hash) mention it should be checked for `false` value:

```
$foo = Craft::$app->request->getPost('foo');
$foo = Craft::$app->security->validateData($foo);

if ($foo !== false) {
    // data is valid
}
```

**Comment by brandonkelly** [comment]
It’s the exact same function, so `false` will definitely be returned.

What is your template code?

**Comment by piotrpog** [comment]
When i use this: 
```
<pre>{{ dump(craft.app.security.validateData('incorrect_value')) }}</pre>
```
I get this:
```
C:\craft\vendor\twig\twig\src\Extension\DebugExtension.php:61:string '' (length=0)
```
It returns empty string.

**Comment by brandonkelly** [comment]
Looks like this was broken for both PHP and Twig. Just fixed for tomorrow’s release. Thanks for reporting!
