### ISSUE TITLE
currentSite returns .env variable name, instead of URL

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#4389]
### Description
When you use `currentSite.baseUrl` in your twig templates you'd expect it to return the url, instead it returns the variable name from the .env file that is specifying the domain.

### Steps to reproduce

1. Set a variable in the sites config to reflect the url of the domain, e.g. `DOMAIN_MAIN_SITE=http://test.com`
2. use `currentSite.baseUrl` in your templates, it will return `DOMAIN_MAIN_SITE` instead of `http://test.com`

### Additional info

- Craft version: 3.1.5
- PHP version: 7.3

**Comment by brandonkelly** [comment]
That is expected behavior; you can get the parsed site URL using `currentSite.getBaseUrl()` though. See #3964 for related discussion.
