### ISSUE TITLE
Matrix Block afterDelete jsFlash/assetBundleFlash on frontend.

### ISSUE THREAD

**Issue by JamesNuttall** [craftcms/cms#4390]
### Description
When deleting an entry (that includes a matrix block field) from the entries index via the [dropdown](http://prntscr.com/o0ff44), if you don't reload the CP and instead go straight to the frontend, cpresources are injected.

I had a similar [issue](https://craftcms.stackexchange.com/questions/25637/craft-3-resaving-matrix-from-frontend-causing-issues-craft-is-not-defined) a while back and believe it could be related some how? It seems to have something to do with the same block in the [MatrixBlock afterDelete method](https://github.com/craftcms/cms/blob/develop/src/elements/MatrixBlock.php#L426).

### Steps to reproduce

1.  Create a section that includes a Matrix Block Field
2. Create an Entry within that section with at least one matrix block populated
3. Navigate to the entries index and delete the entry via the [dropdown](http://prntscr.com/o0ff44) at the top of the page
4. Without reloading the CP, load any page on the frontend
5. Opening the network tab in your browser you will see cpresources have been injected.

### Additional info

- Craft version: 3.1.19 Pro
- PHP version: 7.2.14
- Database driver & version: MYSQL 5.7.25

**Comment by brandonkelly** [comment]
Thanks, just fixed this for today’s release.
