### ISSUE TITLE
Craft search queries containing the word "with" don't return results.

### ISSUE THREAD

**Issue by NickThompson1993** [craftcms/cms#4392]
### Description
Element queries where the "search" or "title" parameters (and possibly others, haven't tested thoroughly) contain the word "with" (e.g title: "Come dine with me" ) don't return the expected results.

Example snippet:
```

    {% set entryById = craft.entries.id(175).one() %}

    {{dump(entryById.title) }} => "Come dine with me"

    {% set entry = craft.entries.search(entryById.title).one() %}

```
**Expected:** returns the entry titled "Come dine with me"
**Actual:** returns null

My temporary work-around:
```
    {% set entryById = craft.entries.id(175).one() %}
    {{dump(entryById.title) }} => "Come dine with me"

    {% set escapedQuery = query|replace('with': '*') %}

    {% set entry = craft.entries.search(escapedQuery).one() %}

```
**Result:** returns the entry model as expected, however this is less than ideal (will return any entry that fits the new pattern) and fairly hacky.

### Steps to reproduce

1. Create an entry whose title contains the word with
2. Search for it, either through an element query or in the CP's search bar

### Additional info

- Craft version: 3.1.29
- PHP version: 7.1.22
- Database driver & version: Mysql 5.7.23
- Plugins & versions: None relevant to the issue

**Comment by angrybrad** [comment]
"with" is a MySQL stopword for both MyISAM and InnoDB storage engines: https://dev.mysql.com/doc/refman/8.0/en/fulltext-stopwords.html

You'd need to modify your MySQL server config to remove it if you want to return results with it.
