### ISSUE TITLE
FR: Ability to store plugin license keys in .env file

### ISSUE THREAD

**Issue by monachilada** [craftcms/cms#4393]
### Description

For security reasons, it would be nice to be able to keep my plugin licenses stored in my .env files and out of the `project.yaml` file in my repo. Currently it's only possible to have the license defined explicitly in the project config file.

**Comment by brandonkelly** [comment]
This is possible with the [CRAFT_LICENSE_KEY](https://docs.craftcms.com/v3/config/php-constants.html#craft-license-key) PHP constant.

**.env**:
```bash
LICENSE_KEY="#########..."
```

**web/index.php** (after loading `.env`):
```php
define('CRAFT_LICENSE_KEY', getenv('LICENSE_KEY'));
```

**Comment by monachilada** [comment]
> This is possible with the [CRAFT_LICENSE_KEY](https://docs.craftcms.com/v3/config/php-constants.html#craft-license-key) PHP constant.

For the Craft license sure, but I was talking about specific 3rd party plugin licenses.

**Comment by brandonkelly** [comment]
Sorry, somehow I missed that!

**Comment by brandonkelly** [comment]
Just added the ability to set plugin license keys to environment variables using the `$VARIABLE_NAME` syntax, for the next release. If you do, they will be saved to your `project.yaml` file the same way, so the license key won’t make it into your repo.

**Comment by monachilada** [comment]
Fantastic, thank you!

**Comment by jurriaanr** [comment]
Small problem with this is that the name of the variable has a max length because the field is cut to the length of a license key

**Comment by brandonkelly** [comment]
@jurriaanr Thanks for pointing that out. Just removed the `maxlength` input attribute for today’s 3.2.6 release.

**Comment by janklan** [comment]
For those interested in storing the license key in an environment variable: don't forget to add `define('CRAFT_LICENSE_KEY', getenv('LICENSE_KEY'));` also to the `/craft` executable.

**Comment by khalwat** [comment]
FWIW, it does work already... I'm doing it here for Craft: <https://github.com/nystudio107/devmode/blob/develop/cms/bootstrap.php#L23> and here for plugins: <https://github.com/nystudio107/devmode/blob/develop/cms/config/project/project.yaml#L144>
