### ISSUE TITLE
[3.2] Element Selector Modals are limited to 50 with no pagination

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#4394]
Each source is limited to 50, but there is no pagination or infinite scroll, so you can't see all the elements.

**Comment by brandonkelly** [comment]
This seems like a duplicate of #4385, which was fixed in 3.0.0-beta.2. Are you running that?

**Comment by timkelty** [comment]
Nope, on 3.2 latest beta

**Comment by timkelty** [comment]
Doh. Was on beta.1

**Comment by brandonkelly** [comment]
Sorry yeah.
