### ISSUE TITLE
./craft setup wizard can get you into trouble with SITE_BASE_URL 

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#4398]
### Description
In putting up a completely vanilla staging site, I tried out the craft setup wizard, and believe it proposed or otherwise put in the SITE_BASE_URL by itself, as I don't remember typing the long url in. However, the result had no protocol, and this caused various breaking errors in editing entries, troublesome to find.

This is probably an FR as well as an error issue, as I believe the wizard and as well Craft itself should catch and warn you of this specific error, as there are lots of ways to have made the mistake, even if the wizard didn't do it for you. 

Reason: the cause is otherwise not easy to find.

### Steps to reproduce
Here's a simplest way:
1. install craft via standard composer instructions
2. run the path/craft setup wizard, putting in expected values to accepted conclusion
3. set up some fields and a section with them as normal;  also simple templates
4. create a new entry; try to use the Share button
5. get a very long non-existing path, with the site url in the middle of it, like https://some.site.com/some.site.com/sec-tion/page-template, which fails.
6. fish around until you discover that the .env file contains an innocent-looking value for SITE_BASE_URL. But, this value contains no protocol.
7. alter this .env value so there is at least a minimal protocol, e.g. //some.site.com, so that it will work without worrying about secure or not.
8. Now editing an entry and using Share works fine
9. Similar but more obscure problems occur for Live Preview, before the fix, with the only visible evidence as a 500 in the browser console, which in logs is a can't-find-template problem.
10. plugins were present and some affected, but otherwise not involved

### Additional info

PHP version	7.1.30
OS version	Linux 4.15.0-51-generic
Database driver & version	MySQL 5.5.5
Image driver & version	GD 7.1.30
Craft edition & version	Craft Solo 3.1.30
Yii version	2.0.19
Twig version	2.11.2
Guzzle version	6.3.3
Imagine version	0.7-dev
Plugins
CraftQL	1.3.2
Element API	2.5.4
Live Vue Gatsby	v0.9.80-rc.1
Redactor	2.3.3.2

**Comment by brandonkelly** [comment]
The installer will take whatever URL you entered into it and save it in your `.env` file as `DEFAULT_SITE_URL`, but not `SITE_BASE_URL`.

If you’re seeing `SITE_BASE_URL` then that probably originated from a `config/project.yaml` file that was already in place at the time you installed Craft. There is no reference to `SITE_BASE_URL` anywhere in the codebase.

**Comment by narration-sd** [comment]
Ok, then, sorry for that, as I must somehow have done it or had it something else that got read. At least this is a tip for someone  who gets the symptom, and thanks for the exposé. Do you think it's worth trapping the case of no protocol and warning?  This back to my often way of thinking, of course.

**Comment by brandonkelly** [comment]
Hm not sure; it’s a little awkward especially when using a preexisting environment variable, because Craft doesn’t control its value, it just uses it.

**Comment by narration-sd** [comment]
True. The question becomes where to put the warning. I may have an idea coming for that ;)

**Comment by narration-sd** [comment]
Easier solution yet on this one -- prevention rather than announcing. Just add a `//` false protocol to value received if it doesn't have a protocol.  That's the kind I use anyway to avoid issues with ssl or not, and it worked fine here. Not worth a PR, is it?

**Comment by brandonkelly** [comment]
The URL is already going through some normalization, but Craft supports a variety of base URL formats:

- absolute (`scheme://hostname/…`)
- “protocol”-relative (`//hostname/…`)
- root-relative: (`/…`)

So if you just enter `hostname`, Craft is going to assume that was meant to be a root-relative path, and add in the scheme + hostname for you.

It’s tricky because `https://some.site.com/some.site.com/sec-tion/page-template` is a perfectly valid URL.

**Comment by narration-sd** [comment]
That last is, agree, and I guess you know if persons are using such things...
