### ISSUE TITLE
configMap in table 'info' stores absolute paths

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#4405]
### Description

Saw a closed issue https://github.com/craftcms/cms/issues/3546 for that, but i still see absolute paths in the configMap field like that:

`{"email":"E:\\craft\\temp2\\config\\project.yaml","fieldGroups":"E:\\craft\\temp2\\config\\project.yaml",` ...

Maybe because of the windows file paths?

### Steps to reproduce

1. Fresh install
2. Enable project config, change a config value in cp

### Additional info

- Craft version: Craft Solo 3.1.30
- PHP version: 7.2.14
- Database driver & version: MySQL 5.7.14
- Plugins & versions: -
- OS: Windows 10

**Comment by brandonkelly** [comment]
Most likely a bug in `Craft::alias()`. We’ll look into it.

**Comment by brandonkelly** [comment]
This is fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#3eb805bc82f229d1e2d8b1f075a0089dc7227fd0 as 3.1.30",
  "...": "..."
}
```

Then run `composer update`.

**Comment by wsydney76** [comment]
@brandonkelly Thanks for the quick response.  

After clearing the configMap field and saving a field, the content shows `{"categoryGroups":"@config\\project.yaml","dateModified":"@config\\project.yaml","email":"@config\\project.yaml"` ... , so without the path, but still a backslash.

Saving the field again show an error `Invalid path alias: @config\project.yaml`

Manually changing the content to `@config/project.yaml` fixes that.

**Comment by brandonkelly** [comment]
Hey @wsydney76 thanks for testing! Do you mind testing once more?

This time set your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#be1a1aa66d32b0704e41e5d3eebec0f61797514f as 3.1.30",
  "...": "..."
}
```

Then run `composer update`.

**Comment by wsydney76** [comment]
@brandonkelly 

Fresh install (3.1.30), enabling projectConfigFile and saving a field:

`{"email":"E:\\craft\\temp2\\config\\project.yaml","fieldGroups":"E:\\craft\\temp2\\config\\project.yaml"` ...

Applying the patch, clearing the  configMap and resaving the field:

`{"dateModified":"@config/project.yaml","email":"@config/project.yaml",` ...

When moving the project files to a new location and adding a few more config changes, everything seems to work fine, project.yaml is correctly saved in the new location.

Thanks!

**Comment by brandonkelly** [comment]
Great, thanks again @wsydney76!
