### ISSUE TITLE
Function Imagick::setimageopacity() is deprecated

### ISSUE THREAD

**Issue by johnwbaxter** [craftcms/cms#4411]
### Description

I'm getting an error when loading some pages where I get internal server error and the logs say: [error][yii\base\ErrorException:8192] yii\base\ErrorException: Function Imagick::setimageopacity() is deprecated in /srv/users/xxxx/apps/xxxx/vendor/pixelandtonic/imagine/lib/Imagine/Imagick/Imagine.php:88

### Steps to reproduce

1. Load a page using images transformed by craft. This specifically happens for PNG images
2. See error

### Additional info

- Craft version: 3.1.28
- PHP version: 7.2.19
- Database driver & version: MySQL 5.7.26
- Plugins & versions:

**Comment by rogerdawkins** [comment]
Several pages on one of my client sites are all failing with Internal Server Error as well. The common theme seems to be that they contain GIF images.

I'm getting the same log error: [error][yii\base\ErrorException:8192] yii\base\ErrorException: Function Imagick::setimageopacity() is deprecated in /srv/users/xxxx/apps/xxxx/vendor/pixelandtonic/imagine/lib/Imagine/Imagick/Imagine.php:88

**Comment by rogerdawkins** [comment]
I have gotten around this error by switching off Imagick on the server. Craft then reverts to using GD instead and all the pages on two of my client sites, that had Internal Server errors, now all display OK.

However, digging deeper I think the cause in my case is that I am using PHP 7.2 and 7.3 and in both cases the Imagick is v3.4.4 (ImageMagick 6.9.4-10). I will contact the hosting company to see if it is possible to use ImageMagick 7 instead as that will then use setImageAlpha rather than setImageOpacity.

But I still don't understand why a function that is deprecated should cause an error.

**Comment by andris-sevcenko** [comment]
Sounds like your hosting company has `E_DEPRECATED` enabled in error logging.

As you can see in the [extension's code](https://github.com/Imagick/imagick/blob/bb93a3da072c2243934fe4629c0f47a12407da9a/imagick.c#L2326), the PECL extension sets the internal deprecated flag on the function.

Then, when calling a function with the internal deprecated flag set, PHP itself will trigger an error, if [`E_DEPRECATED` is enabled in error reporting](https://php.net/manual/en/errorfunc.constants.php#errorfunc.constants.errorlevels.e-deprecated-error).

That error is caught by Yii and then handled using its error handler. Which, in this case, throws an ErrorException`.

So, yeah. You can reduce the error reporting level (maybe not always a good idea) or update Imagick to a version that is, uhh, not as stale.

**Comment by rogerdawkins** [comment]
I can set the Error Reporting level for the server and I have changed it to E_ALL ~ E_DEPRECATED ~ E_NOTICE. If I check the phpinfo it shows a value of 24567 which is correct for the above setting. However, I still get the same error in Craft even after clearing all caches.

Looking in the Craft bootstrap.php file it sets error_reporting(E_ALL); which I presume overrides my server setting.

I would like to update ImageMagick but I use cpanel and that only supports version 6.9 at this time.

**Comment by rogerdawkins** [comment]
OK, I have a solution for my setup. Bootstrap does override the server setup it seems, so I added another override in index.php after the call to bootstrap line. I have re-enabled Imagick and it is all ok now.

**Comment by simonleadbetter** [comment]
Yup. I’ve had a few clients report this same issue in the last few days. I have tried to disable error reporting completely, but I see an 'Internal server error' message. Enabling dev mode renders the same error original reported:

Function Imagick::setimageopacity() is deprecated

Line 88 in /home/seriousorg/vendor/pixelandtonic/imagine/lib/Imagine/Imagick/Imagine.php

I can only assume there has been some update to cPanel in the background that has suddenly caused this issue to come to light.

As yet, I haven’t found a solution, but I thought I would share so you are aware it is a common(ish) problem.

**Comment by simonleadbetter** [comment]
Good news. I have isolated the cause and I am surprised this issue hasn’t revealed itself before now, so I am suspicious something has changed on the server, i.e. an automatic update via WHM/cPanel.

Essentially, my clients have been uploading images with the .jpeg extension, which Imagick does not like (at all). Simply changing this to .jpg resolved the issue.

To avoid this happening again, we have modified our general config file, deleting jpeg as a value from the allowedFileExtensions setting. I hope this helps.

**Comment by rogerdawkins** [comment]
@ryanmasuga  In my post above I didn't change it in the bootstrap.php file, I changed it in the index.php file in the public folder. The change needs to be added after the **call** to bootstrap so your change overrides the one actioned in the bootstrap file.

Making the change in the index.php file is safer as it does not get overriden with future Craft updates.
