### ISSUE TITLE
Additional information on license expiry email

### ISSUE THREAD

**Issue by mediabeastnz** [craftcms/cms#4412]
Currently when a license expires or is due to expire we're sent an email which contains the list of licenses but not what domain they are assigned/tied to.

It would be great to see this in the email as it prevents having to copy the license code and then search for the site on the ID dashboard. Especially useful when you're managing 30+ craft pro websites + plugins.

Something like this would be great:

```handlebars
Hey ,

The following licenses have expired for the domain {{ www.example.com }}:

    Craft Pro XXXXXXXXXX
    Freeform XXXXXXXXXX

To ensure you don’t miss any updates, click on the license key links above, and click the “Renew your license” button in the “Updates” section.

Have a great day!
```

**Comment by brandonkelly** [comment]
Thanks for the suggestion! Going forward, notification emails will show the domain right after each license key.
