### ISSUE TITLE
Automatic Duplicate Slug Generation > 100

### ISSUE THREAD

**Issue by JustJarethB** [craftcms/cms#4413]
### Description
Given a title `Title`, craft will create a slug `title`.
Duplicate entries of `Title` gives a slug format `title-[n-1]`.
Duplicate 100 produces slug `title-99`
Duplicate 101 throws error `Could not generate a unique URI based on the URI format.` in backend and has frontend behaviour I don't fully understand, but could be normal.

### Steps to reproduce

1. Create 101 entries with the same Title and don't edit the slug

### Additional info

- Craft version: Craft Pro 3.1.25
- PHP version: 7.1.30
- Database driver & version: MySQL 5.5.62

**Comment by angrybrad** [comment]
You can adjust this behavior by changing the [maxSlugIncrement](https://docs.craftcms.com/v3/config/config-settings.html#maxslugincrement) config setting.
