### ISSUE TITLE
Upgrade breaks matrix fields

### ISSUE THREAD

**Issue by dustfeather** [craftcms/cms#4414]
### Description
When you upgrade from 3.2.0-alpha.3 to any version higher than that, all of the matrix blocks in entries loose their content.

### Steps to reproduce

1. Install craft 3.2.0-alpha.3
2. Add content to a matrix block of any entry
3. Update to 3.2.0-beta.2 using the command line `craft update all`
4. Check the content you just added to that matrix block (it's gone)

### Additional info

- Craft version: 3.2.0.beta.2
- PHP version: 7.2
- Database driver & version: mysql 5.7

**Comment by brandonkelly** [comment]
I’m not able to reproduce this.

Do you have a database backup from before you updated passed Alpha 3? If so can you send that, plus your `composer.json` and `composer.lock` files, over to support@craftcms.com?
