### ISSUE TITLE
[3.2] Image transform on first save points to _tempuploads/user directory

### ISSUE THREAD

**Issue by tinchalamo** [craftcms/cms#4415]
### Description
I have a few preparse fields that run a transform on images when an entry is saved. On the first save of an entry, the transformed URL is returned as `https://website.com/images/_tempuploads/user_1/_landscape/snow-buddies-hero-image-1.jpg`. Notice the `/_tempuploads/user_1/` part of the path. On resave of that entry the transformed URL is returned correctly without that path.

### Steps to reproduce

1. Create new entry and add assets.
2. Save entry and get server error.
3. Review entry and see that everything was saved correctly. Make a change then update the entry.
4. Receive no server error and see that the transformed image URL is correctly updated.

### Additional info

- Craft version: Craft Pro 3.2.0-beta.3
- PHP version: 7.3.5
- Database driver & version: MySQL 5.6.34
- Plugins & versions:
    "craftcms/cms": "3.2.0-beta.3",
    "vlucas/phpdotenv": "^2.4.0",
    "craftcms/redactor": "2.3.3.2",
    "mmikkel/incognito-field": "1.1.1.1",
    "rias/craft-position-fieldtype": "1.0.14",
    "markhuot/craftql": "1.3.2",
    "verbb/super-table": "2.1.20",
    "marionnewlevant/match-input": "v2.0.1",
    "fruitstudios/linkit": "1.1.11",
    "nfourtythree/entriessubset": "1.2.1",
    "craftcms/aws-s3": "1.2.3",
    "doublesecretagency/craft-cpcss": "2.1.0",
    "doublesecretagency/craft-smartmap": "3.2.2.1",
    "craftcms/store-hours": "2.1.1.1",
    "elivz/craft-single-cat": "1.2.1",
    "fortrabbit/craft-copy": "1.0.0-RC5",
    "aelvan/preparse-field": "v1.0.6",
    "spicyweb/craft-fieldlabels": "1.1.2",
    "rias/craft-password-policy": "1.0.4",
    "craftcms/element-api": "2.5.4",
    "craftcms/feed-me": "4.1.0",
    "verbb/workflow": "1.1.10",
    "robuust/craft-reverserelations": "1.1.5",
    "mmikkel/cp-field-inspect": "1.0.5",
    "doublesecretagency/craft-inventory": "2.0.3",
    "fortrabbit/yii-memcached": "^1.0",
    "putyourlightson/craft-sendgrid": "1.1.0",
    "doublesecretagency/craft-cpjs": "2.1.0",
    "doublesecretagency/craft-cpbodyclasses": "2.1.0",
    "solspace/api-caller": "*",
    "aelvan/imager": "v2.1.10",
    "nystudio107/craft-webperf": "1.0.11",
    "ostark/craft-async-queue": "2.0.0"

**Comment by tinchalamo** [comment]
@brandonkelly some more info. We are hosting the site on the fortrabbit Pro Stack across 4 PHP nodes. I tailed the log while saving a new entry and got the "Internal Server Error" and at the same time this popped up in the log:

` 2019-06-19T13:04:08Z 2019-06-19 08:04:07 [-][1][ba156e1e5200737bb5c1f081417212a6][warning][craft\services\AssetTransforms::deleteAllTransformData] Unable to delete the file "/srv/app/crafthouse-prod/htdocs/storage/runtime/assets/sources/14332.jpg": unlink(/srv/app/crafthouse-prod/htdocs/storage/runtime/assets/sources/14332.jpg): No such file or directory `

**Comment by brandonkelly** [comment]
Solved via aelvan/Preparse-Field-Craft#56.
