### ISSUE TITLE
Deprecation warning after updating to 3.1.31

### ISSUE THREAD

**Issue by elfacht** [craftcms/cms#4416]
### Description

After updating to `3.1.31` this deprecaation warning pops up:

`ThedefineComponentsevent on CraftVariable has been deprecated. Use theinitevent to register custom components instead.`
Called from /xxx/vendor/craftcms/cms/src/web/twig/variables/CraftVariable.php:139

This warning comes up on all my Craft projects., even with all plugins disabled.

### Steps to reproduce

1. Update from 3.1.30 to 3.1.31

### Additional info

- Craft version: 3.1.31
- PHP version: 7.2

**Comment by brandonkelly** [comment]
Yii 2.0.20 included a [fix](https://github.com/yiisoft/yii2/commit/317a73a59f7f1a0beb4a0f181e96bb775810420b) for wildcard event handlers, which could have something to do with this.

I know you said you disabled all your plugins, but do you have a module that may be registering a wildcard event perhaps?

**Comment by brandonkelly** [comment]
Turns out this happens when the Debug Toolbar is enabled, which registers a wildcard event.

I’ve removed the check for that event for the next Craft 3.2 Beta release, so those deprecation errors will go away after that.

**Comment by lukeyouell** [comment]
@brandonkelly will this be fixed also be applied to 3.1? We're not in a position to update to 3.2 yet but the deprecation error is slightly annoying!

**Comment by elfacht** [comment]
@lukeyouell This is already fixed in 3.2.

**Comment by lukeyouell** [comment]
@elfacht I can appreciate that, but bug fixes such as this shouldn't just be applied to 3.2 as they affect projects using 3.1 too.

**Comment by brandonkelly** [comment]
@lukeyouell 3.1 is not an LTS release or anything.

**Comment by lukeyouell** [comment]
@brandonkelly Thanks. Is there a reason why it isn't?

The reason we aren't in a position to update is due to the bugs associated with the new features that ship with 3.2, it just doesn't look to be stable enough _yet_, which is understandable considering it was only released a week ago. 

I do think there's a case for 3.x releases to receive short-term support in the form of minor bug/security fixes, at least until the latest release is tried-and-tested.

**Comment by brandonkelly** [comment]
There’s definitely a case for us establishing a LTS program, but 3.1 isn’t one.

Plus in this case, this deprecation error can safely be ignored. The fix was a slight breaking change, which is why I made it for 3.2.0 rather than a 3.1.x release.

**Comment by lukeyouell** [comment]
@brandonkelly Yeah the deprecation issue is minor. I think my initial point developed into a wider question! Thanks for explaining!
