### ISSUE TITLE
Error message: Unknown "reduce" filter.

### ISSUE THREAD

**Issue by AlexJenter** [craftcms/cms#4417]
### Description
Issue with the twig [reduce](https://docs.craftcms.com/v3/dev/filters.html#reduce) filter 
example i tried taken from [symphony docs](https://twig.symfony.com/doc/2.x/filters/reduce.html)

### Steps to reproduce

1. Create an array in Twig or PHP
2. Calling reduce results in a variety of errors depending on arguments
  - called with arrow function:
```twig
{% set numbers = [1, 2, 3] %}

{{ numbers|reduce((carry, v) => carry + v) }}
```
> An opened parenthesis is not properly closed. Unexpected token "punctuation" of value "," ("punctuation" expected with value ")").
  - called with no arguments:
```twig
{% set numbers = [1, 2, 3] %}

{{ numbers|reduce() }}
```
> Unknown "reduce" filter.

### Additional info

- Craft version: 3.1.27
- PHP version: 7.2.16
- Plugins & versions:
  - Asset Rev 6.0.2
  - Commerce 2.1.6.1
  - Kint 1.0.0
  - Redactor 2.3.3.2

**Comment by brandonkelly** [comment]
Twig’s `reduce` filter wasn’t added until v2.10.0, so you need to be on at least Craft 3.1.29 to use it.

**Comment by AlexJenter** [comment]
Ah, thank you @brandonkelly, will check as soon as im able to run the updates
