### ISSUE TITLE
Craft::$app->matrix->saveBlockType($newBlock) fails.

### ISSUE THREAD

**Issue by isjackwild** [craftcms/cms#4418]
### Description
When adding a new MatrixBlockType to an existing Matrix field, by calling `Craft::$app->matrix->saveBlockType()` on a newly created block , an exception is thrown by the `Db::idByUid()` helper method.

> Exception: Argument 2 passed to craft\helpers\Db::idByUid() must be of the type string, null given, called in /Users/jackwild/Repos/CraftTest-01/vendor/craftcms/cms/src/services/Matrix.php on line 287

After some debugging, it seems that on line 287 of the Matrix helper, the id of the newly created block cannot be found, as there is no uid on the newly created MatrixBlockType passed as an argument.

### Steps to reproduce

1. Create an existing matrix block
2. In PHP (I'm using the migrations tool), try to add a new block type:

```
$myExistingMatrix = Craft::$app->fields->getFieldByHandle("myExistingMatrix");

        $blockType = new \craft\models\MatrixBlockType([
            "fieldId" => $myExistingMatrix->id,
            "name" => "Text Content",
            "handle" => "legacy_TextContent",
            "fields" => [
                // Content
                new \craft\fields\PlainText([
                    "name" => "Text Content",
                    "handle" => "text",
                    "instructions" => "The content of this block",,
                ]),
            ],
        ]);
        return (Craft::$app->matrix->saveBlockType($blockType));
```

### Additional info

- Craft version: 3.1.30
- PHP version: 7.1.20
- Database driver & version: MySQL 5.7.23
- Plugins & versions: None

**Comment by brandonkelly** [comment]
`saveBlockType()` isn’t meant to be called directly; it’s better to save the entire Matrix field, with the added block type set on it.

```php
/** @var \craft\fields\Matrix $myExistingMatrix */
$myExistingMatrix = Craft::$app->fields->getFieldByHandle('articleBody');

$blockTypes = $myExistingMatrix->getBlockTypes();
$blockTypes[] = [
    'name' => 'Text Content',
    'handle' => 'legacy_TextContent',
    'fields' => [
        // Content
        'new1' => [
            'type' => \craft\fields\PlainText::class,
            'name' => 'Text Content',
            'handle' => 'text',
            'instructions' => 'The content of this block',
        ]
    ]
];
$myExistingMatrix->setBlockTypes($blockTypes);
Craft::$app->fields->saveField($myExistingMatrix);
```

**Comment by isjackwild** [comment]
Awesome — the example article / code I was following clearly had the wrong end of the stick. This makes sense.

Many thanks
