### ISSUE TITLE
[FR] Add event for "beforeUpsertContent" that passes $values

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#4422]
It would seem I'm in the need for an event, just before content is inserted/updated to the db: https://github.com/craftcms/cms/blob/develop/src/services/Content.php#L186

There already is `craft\services\Content::EVENT_BEFORE_SAVE_CONTENT`, but I specifically wan't to manipulate the `$values`.

…so it might look something like:

```
        // Trigger a 'beforeUpsertContent' event
        $event = new ElementContentEvent([
            'element' => $element,
            'values' => $values
        ]);

        $this->trigger(self::EVENT_BEFORE_UPSERT_CONTENT, $event);
        $values = $event->values;
```

### Use-case:

I need to perform a string manipulation on the values about to be saved the the db. I want to do it specifically on the serialized values, as I don't want to have to worry about what kind of fields values might be.

In this case I'm replacing a hyphenated company's name, e.g. A-B-C / Acme-Bread-Company, with non-breaking hyphen characters.

However, a more general use for this event might be a profanity filter on content, just before it hits the DB. In that case, it may make sense to also pass an `isValid` param so that the use could bail out if desired.

@brandonkelly think this makes sense? Or is there a better way to achieve what I'm after? Happy to prep a PR.

**Comment by timkelty** [comment]
The other option would be to simply move `Content::EVENT_BEFORE_SAVE_CONTENT` after the serialization and pass the values. It seems like if someone wanted to manipulate the element before saving (and serialization), they could just use `Element::EVENT_BEFORE_SAVE`.

**Comment by brandonkelly** [comment]
It seems like an event there would be pretty hacky and get abused.

You could pull of what you’re trying to do with [craft\services\Element::EVENT_BEFORE_SAVE_ELEMENT](https://docs.craftcms.com/api/v3/craft-services-elements.html#event-before-save-element) though, and even in a way that wouldn’t have to account for field types like you want:

```php
use craft\events\ElementEvent;
use craft\helpers\ElementHelper;
use craft\services\Elements;

Event::on(Elements::class, Elements::EVENT_BEFORE_SAVE_CONTENT, function(ElementEvent $e) {
    // If this is Craft 3.2+, probably best if this only kicks in when not saving a draft or revision
    // Otherwise just remove these lines
    if (ElementHelper::isDraftOrRevision($e->element) {
        return;
    }

    // Get the field layout; ignore if there is none
    $fieldLayout = $e->element->getFieldLayout();
    if (!$fieldLayout) {
        return;
    }

    // Find the fields with content columns
    $fieldHandles = [];
    foreach ($fieldLayout->getFields() as $field) {
        if ($field::hasContentColumn()) {
            $fieldHandles[] = $field->handle;
        }
    }

    // Get their serialized values
    $fieldValues = $e->element->getSerializedFieldValues($fieldHandles);

    // Update the field values
    foreach ($fieldValues as $fieldHandle => $fieldValue) {
        // $value is either going to be an array, number, string, boolean
        // You can either work with that directly, accounting for the different types,
        // or pass through prepareValueForDb() to make it identical to what will get sent to the DB
        $fieldValue = Db::prepareValueForDb($fieldValue); // optional

        // Now make your changes...

        // Update the element if it changed
        if ($newValue !== $fieldValue) {
            $e->element->setFieldValue($fieldHandle, $newValue);
        }
    }
});
```

**Comment by timkelty** [comment]
makes sense, thanks @brandonkelly!
