### ISSUE TITLE
[3.2] Title shows ID and URI temp name

### ISSUE THREAD

**Issue by rinusvandam** [craftcms/cms#4423]
### Description

When creating an entry inside a section that has two languages, the entry in the other language shows the ID as title and a temp name as URI. For example:

I create an entry called Test and save the entry. The CP shows:

- Title: Test
- URI: test

When I switch from Spanish to English the CP shows:

- Title: 10 (the ID of the entry)
- URI: __temp_wcW3r4Y73egS4Uh6yHInNttpxpQdtG1dxRYl

![example](https://user-images.githubusercontent.com/6650702/59847113-f307db80-9361-11e9-91eb-6b21e20bc5a9.png)

### Steps to reproduce

1. Create two site groups and add two languages to each site
2. Create a section and set propagation to ‘Save entries to other sites in the same site group’ and enable ‘Enable versioning for entries in this section?’
3. Create and save an entry
4. Switch to another language in the same site group

### Additional info

- Craft version: Craft Pro 3.2.0-beta.3
- PHP version: 7.3.1
- Database driver & version: MySQL 5.7.25
- Plugins & versions: Site Switcher 2.1.0

**Comment by brandonkelly** [comment]
I’m not able to reproduce this.

Can you send in your `composer.json` and `composer.lock` files, plus a database backup, over to support@craftcms.com?

**Comment by Anubarak** [comment]
We are facing the same issue, the reason for this is the way you propagate elements right at the start.
When you enter the form to create a new entry Craft creates and propagates this entry for all sites so it runs the `craft\services\Elements::_propagateElement`.

That means when you store the element the very first time manually via "save" there is already a propagated master element

```PHP
if ($siteElement === null && !$isNewElement) {
    $siteElement = $this->getElementById($element->id, get_class($element), $siteInfo['siteId']);
}

// isNewSiteForElement is not true because there is an element and it's not considered as "new" -> it does not clone the element and just creates an empty placeholder with no title and no slug

// If it doesn't exist yet, just clone the master site
if ($isNewSiteForElement = ($siteElement === null)) {
    $siteElement = clone $element;   //
    $siteElement->siteId = $siteInfo['siteId'];
    $siteElement->contentId = null;
    $siteElement->enabledForSite = $siteInfo['enabledByDefault'];
} else if ($element->propagateAll) {
    $oldSiteElement = $siteElement;
    $siteElement = clone $element;
    $siteElement->siteId = $oldSiteElement->siteId;
    $siteElement->contentId = $oldSiteElement->contentId;
    $siteElement->enabledForSite = $oldSiteElement->enabledForSite;
} else {
    $siteElement->enabled = $element->enabled;
    $siteElement->resaving = $element->resaving;
}
```

Later on, when this line is called
```PHP
$siteElement->setScenario(Element::SCENARIO_ESSENTIALS);
$siteElement->propagating = true;

if ($this->saveElement($siteElement, true, false) === false) {
```
You have an nearly empty element with no title and Craft creates one by itself
```PHP
// Set a dummy title if there isn't one already and the element type has titles
if (!$runValidation && $element::hasContent() && $element::hasTitles() && !$element->validate(['title'])) {
    if ($isNewElement) { 
        $element->title = Craft::t('app', 'New {type}', ['type' => $element::displayName()]);
    } else {
        $element->title = $element::displayName() . ' ' . $element->id; // this is the title of propagated elements
    }
}
```

Maybe it's a little bit more clear what happens

**Comment by brandonkelly** [comment]
> Edit: It only happens when you click hit the "save" button too fast after inserting the title with a slow internet connection so when the version can't be saved automatically

Aha, I’m able to reproduce that. I think I have an idea of how to solve it…

**Comment by brandonkelly** [comment]
Just fixed this for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#499f222cc26d01ac15c96709ed37befd583ef1ee as 3.2.9",
  "...": "..."
}
```

Then run `composer update`.
