### ISSUE TITLE
Project config likes to switch between data types.

### ISSUE THREAD

**Issue by ryanpcmcquen** [craftcms/cms#4424]
### Description

Perhaps this happens when `craft project-config/rebuild` gets run, but we end up with huge diffs occasionally that are merely just type switching, for example:

```
required: '0'
sortOrder: '1'
```

Becomes:

```
required: false
sortOrder: 1
```

### Steps to reproduce

1. Make changes to an existing field in Craft.
2. If that doesn't work, run: `craft project-config/sync` and then `craft project-config/rebuild`.

### Additional info

- Craft version: 3.1.31
- PHP version: 7.x

**Comment by brandonkelly** [comment]
We’ve been improving typecasting in Craft so this sort of thing is more rare, but I will keep this open so we can note any future progress we make. The example you showed is a step in the right direction though; it’s whatever stored `'0'` and `'1'` to begin with that is the issue.

**Comment by jan-dh** [comment]
This issue is still happening, even with things like plain text fields on a fresh Craft install. It seems to occur on certain type of properties. Once I found to be problematic regularly

- searchable: goes from `true` to `1`
- uriFormat: goes from `null` to `''`
- required in fieldLayouts > tabs changes from `0` to `false`
- sortOrder in fieldLayouts > tabs changes from `'3'` to `3`
- 

some examples:
```
- searchable: true
+ searchable: '1'
```

```
  fieldLayouts:
      f8eca5a5-12be-4be4-911f-cd70352174a1:
        tabs:
          -
            fields:
              0ac19cf2-7cff-402d-88f5-ee1c455fe85d:
-                required: '0'
-                sortOrder: '3'
+                required: false
+                sortOrder: 3
```

**Additional info**
Craft version: 3.4.23
PHP version: 7.4.2

**Comment by brandonkelly** [comment]
Right, it’s still not fully solved, and won’t be until we can start taking advantage of typed properties in PHP 7.4. The issue is that all data comes back as strings from MySQL.

**Comment by brandonkelly** [comment]
I just refactored how project config rebuilding works internally for Craft 3.5, and now all built-in system components use the same config generation methods that are used when saving the components normally. So you shouldn’t see any more type juggling going forward.

**Comment by jan-dh** [comment]
This is still an issue as of Craft 3.5. This is the result of a `/craft project-config/rebuild` command

![image](https://user-images.githubusercontent.com/5801781/89642118-73193980-d8b3-11ea-9016-b5aa3433dbb9.png)

**Additional info**
Craft version: 3.5.1
PHP version: 7.4

**Comment by brandonkelly** [comment]
@jan-dh What file is that?

**Comment by jan-dh** [comment]
Some examples, this is a basic starting setup though.

```
- config/project/fields/intro--957980f8-81e5-40dc-a6b6-53a8007d820b.yaml
- config/project/sites/sitename--daab03ee-7bda-4b63-be9e-722444ab39f5.yaml
- config/project/superTableBlockTypes/ac263991-1837-4325-a1fa-379e35856a25.yaml
- config/project/fields/entryTypes/sitemap--5702ad47-2a0a-4519-8990-b848b7ec6c9c.yaml
```

As far as I can tell, atm in `fields, sites, superTableBlockTypes, entryTypes`.

**Comment by brandonkelly** [comment]
Just searched the codebase and every place we are setting `sortOrder` or `searchable` on a config, we are properly typecasting them to integers/booleans. So suspect this is coming from a plugin. If you send your Composer files and a database backup into support@craftcms.com we can look into it further.
