### ISSUE TITLE
Filters do not work in twig templates in craft cms. (Particularly reduce function)

### ISSUE THREAD

**Issue by g1un** [craftcms/cms#4426]
### Description
I tried to use reduce function in template, but got error. It seems twig/craftcms can not work with such functions. Reduce function docs:<br/>https://docs.craftcms.com/v3/dev/filters.html#reduce<br/>
My example:<br/>
```
{% set data = craft.entries.section("faqChannel").orderBy('faqOrder').all() %}
{% set types = data|reduce((acc, v) => v.faqType is not in acc ? acc|merge([v.faqType]) : acc, []) %}
```
Error:<br/>
```
Twig Syntax Error – Twig_Error_Syntax
An opened parenthesis is not properly closed. Unexpected token "punctuation" of value "," ("punctuation" expected with value ")").
```

### Steps to reproduce

1. Use reduce function (https://docs.craftcms.com/v3/dev/filters.html#reduce) in twig template in craft cms (or any other such function).

### Additional info

- Craft version: Craft Solo 3.1.1
- PHP version: 7.2.19
- Database driver & version: MySQL 5.5.46
- Plugins & versions: 

### Stackoverflow
https://craftcms.stackexchange.com/questions/30702/arrow-functions-in-twig-or-craft-cms

**Comment by brandonkelly** [comment]
Arrow functions weren’t added until Twig 2.10.0. You’ll need to be on a more recent version of Craft to have access to that (at least 3.1.29).
