### ISSUE TITLE
Users cp permissions

### ISSUE THREAD

**Issue by samuelbirch** [craftcms/cms#4431]
if a user can only see/manage certain user groups, if they create a user and forget to assign a user group in the permissions tab, then they can not see the user they just created. The user appears in the "all users" list which they can not see.

What would be great is if the user can always see the all users list but filtered by their user group permissions, so if in the case above the forget to assign to a group they can still see and edit the user.

Also, is it possible to have a permission so only admins can see other admins even in the all users list?

**Comment by brandonkelly** [comment]
> so if in the case above the forget to assign to a group they can still see and edit the user.

How would they edit the user if they don’t have permission to?

**Comment by samuelbirch** [comment]
I guess if they dont have permission to, then they cant. 

Would a better solution be to have a setting that can be turned to make a user group a required field?

**Comment by brandonkelly** [comment]
Just looked into this, and I’m actually not even sure what you mean by “if a user can only see/manage certain user groups”. Craft doesn’t have permissions that prevent users from editing other users.

<img width="258" alt="User permission list" src="https://user-images.githubusercontent.com/47792/59978976-c4bf1180-9596-11e9-9923-07f343c14680.png">

**Comment by samuelbirch** [comment]
just realised that we had a "hide admin" plugin installed which also hides the all users list. doh! 

would be good to have a permission though to show admins or not!
