### ISSUE TITLE
[3.2] Revisioning disabled: entry revision not found

### ISSUE THREAD

**Issue by rinusvandam** [craftcms/cms#4438]
### Description

I have a section called ‘Pages’ with versioning for entries enabled for a multi-site. After adding some entries I decided to disable versioning. 

When opening an entry the list with revisions is still visible. When I click on a revision I get ‘Entry not found’. 

#### In the web-404s.log it says:

`[-][1][o6sgeliqmvmcjdhcnknj2m2usb][error][yii\web\HttpException:404] yii\web\NotFoundHttpException: Entry not found in /sites/sitename/craft/vendor/craftcms/cms/src/controllers/EntriesController.php:777`

#### Stack trace:

```
#0 /sites/sitename/craft/vendor/craftcms/cms/src/controllers/EntriesController.php(101): craft\controllers\EntriesController->_prepEditEntryVariables(Array)
#1 [internal function]: craft\controllers\EntriesController->actionEditEntry('pages', 4, NULL, 53, 'businessEnglish', NULL)
#2 /sites/sitename/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /sites/sitename/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /sites/sitename/craft/vendor/craftcms/cms/src/web/Controller.php(186): yii\base\Controller->runAction('edit-entry', Array)
#5 /sites/sitename/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-entry', Array)
#6 /sites/sitename/craft/vendor/craftcms/cms/src/web/Application.php(298): yii\base\Module->runAction('entries/edit-en...', Array)
#7 /sites/sitename/craft/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('entries/edit-en...', Array)
#8 /sites/sitename/craft/vendor/craftcms/cms/src/web/Application.php(283): yii\web\Application->handleRequest(Object(craft\web\Request))
#9 /sites/sitename/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /sites/sitename/web/index.php(21): yii\base\Application->run()
```

### Additional info

- Craft version: 3.2.x-dev#6e8c5b41fd744f92070cad474c6a2f2aac074673 as 3.2.0-beta.3
- PHP version: 7.3.1
- Database driver & version: MySQL 5.7.25
- Plugins & versions: -

**Comment by brandonkelly** [comment]
I’m not able to reproduce that. Can you send in your `composer.json` and `composer.lock` files, plus a database backup, over to support@craftcms.com ?

**Comment by brandonkelly** [comment]
Issue ended up being that Structure entry revisions weren’t getting fully saved correctly, which is why they were 404ing. (Disabling entry versioning for the section had nothing to do with it.)

Fixed for the next release, but unfortunately there’s nothing we can do about the current revisions. They’re just going to keep 404ing.

You could clear them out by re-enabling versioning for the section, set your `maxRevisions` config setting to `1` in `config/general.php`, and then re-save the entry(s) you’re seeing this in.
