### ISSUE TITLE
Twig variable representing current object - entry, category or commerce product

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#4440]
Currently when i want to make some universal component that works both in entry page, category page or (in case of craft commerce) product page, i need to do it like this 

```
{{entry.title ?? category.title ?? product.title}}
```
It would be usefull if there was some kind of shortcut variable, representing current object avaible to template - like `currentObject`. 

So, with `curerentObject` I could output title like this:

```
{{currentObject.title}}
```
And it would work with entry, category and product.

**Comment by brandonkelly** [comment]
When you request an element URL, it’s up to the element type to actually route the request to a template and pass in an `entry` / `category` / `product` variable. So there’s not a central place we could implement a `currentObject` variable.

However if the request did go through an element URL, you will always be able to get the matched element like this:

```twig
{% set element = craft.app.urlManager.matchedElement %}
```

Though I’d recommend just having your component templates expect that whatever is including them pass an `element` variable. For example:

**_includes/title.twig**
```twig
<h1>{{ element.title }}</h1>
```

**news/_entry.twig**
```twig
{% include '_includes/title' with {
  element: entry
} %}
```

**Comment by piotrpog** [comment]
@brandonkelly Thanks for letting me know about `craft.app.urlManager.matchedElement`!
