### ISSUE TITLE
Entry status is orange, yet user is enabled

### ISSUE THREAD

**Issue by Manzanit0** [craftcms/cms#4441]
### Description

Basically we have an entry which is orange, but the user is enabled (green), so I don't really understand what that means, or if its something we should worry about. We can't seem to enable it, but we can the children entries. I didn't find anything in the documentation regarding this.

See image:

![image](https://user-images.githubusercontent.com/10437518/60013820-5a31d280-9677-11e9-83a5-c71450cd2c85.png)

### Additional info

- Craft version: 3.1.30
- PHP version: 7.1.27
- Database driver & version: MySQL 5.6.39
- Plugins & versions:

Amazon S3, 1.2.3
Contact Form, 2.2.5
Neo, 2.3.5
Redactor 2.3.3.2
Retour, 3.1.16
Seomatic, 3.2.19

**Comment by brandonkelly** [comment]
If an entry is orange, then either its Post Date is in the future (so it is pending), or its Expiry Date is in the past (so it has expired).

Author statuses are unrelated to the entry statuses. Green dots beside them just mean that the author accounts are active (as opposed to unverified or suspended).

**Comment by Manzanit0** [comment]
Ah, it was the Post Date – we didn't know that was the behaviour if it was in the future. Thanks for the quick reply!
