### ISSUE TITLE
Expose setStreamOptions on the Swiftmailer smtp adapter

### ISSUE THREAD

**Issue by renzo-s** [craftcms/cms#4444]
### Description
The current exposed config parameters on the SMTP adapter prevent supplying custom stream options.

### Steps to reproduce
Our use case is targeted specifically to passing these options:

```
['ssl' => [ 'verify_peer_name' => false ]]
```

The problem arises if the SMTP server lives in a docker container which is closed to the outside. Swiftmailer will get a different host from the server cert, since it talks to it's local network, and will not send (although the cert is valid).

### Additional info

- Craft version: 3.x
- PHP version: 7.x

**Comment by brandonkelly** [comment]
You can configure Craft with a completely custom-configured `mailer` component from `config/app.php`. Here’s an example: https://docs.craftcms.com/v3/config/app.html#mailer-component

**Comment by nordentwickler** [comment]
Hey @brandonkelly i tried to use it that way in Craft 4:

```
'components' => [
		'mailer' => function() {
			// Get the default component config:
			$config = App::mailerConfig();

			// Use custom tedom Mailer in dev mode:
			if (Craft::$app->getConfig()->getGeneral()->devMode) {
				$adapter = craft\helpers\MailerHelper::createTransportAdapter(
					craft\mail\transportadapters\Smtp::class,
					[
						'host' => App::env('MAIL_HOST'),
						'port' => App::env('MAIL_PORT'),
						'username' => App::env('MAIL_USERNAME'),
						'password' => App::env('MAIL_PASSWORD'),
						'encryptionMethod' => 'tls',
						'streamOptions' => [
							'ssl' => [
								'allow_self_signed' => true,
								'verify_peer' => false,
								'verify_peer_name' => false,
							],
						],
					]
				);

				// Override the transport:
				$config['transport'] = $adapter->defineTransport();
			}

			// Return the initialized component:
			return Craft::createObject($config);
		},
	],
```
But of course this is not going to work, cause we do not have a "streamOptions" in Smtp.php. So, how can we archive this?

**Comment by brandonkelly** [comment]
@nordentwickler Symfony Mailer doesn’t support setting `allow_self_signed` via [`EsmtpTransportFactory::create()`](https://github.com/symfony/mailer/blob/6.2/Transport/Smtp/EsmtpTransportFactory.php#L24), so you’ll need to modify the transport after it was created:

```php
use craft\helpers\App;
use Symfony\Component\Mailer\Transport\Smtp\EsmtpTransport;
use Symfony\Component\Mailer\Transport\Smtp\Stream\SocketStream;
use yii\symfonymailer\Mailer;

return [
    'components' => [
        'mailer' => function() {
            $config = craft\helpers\App::mailerConfig();

            // Use custom tedom Mailer in dev mode:
            if (App::devMode()) {
                $config['transport'] = [
                    'scheme' => 'smtps',
                    'host' => App::env('MAIL_HOST'),
                    'port' => App::env('MAIL_PORT'),
                    'username' => App::env('MAIL_USERNAME'),
                    'password' => App::env('MAIL_PASSWORD'),
                ];

                /** @var Mailer $mailer */
                $mailer = Craft::createObject($config);
                /** @var EsmtpTransport $transport */
                $transport = $mailer->getTransport();
                /** @var SocketStream $stream */
                $stream = $transport->getStream();

                $streamOptions = $stream->getStreamOptions();
                $streamOptions['ssl']['allow_self_signed'] = true;
                $streamOptions['ssl']['verify_peer'] = false;
                $streamOptions['ssl']['verify_peer_name'] = false;
                $stream->setStreamOptions($streamOptions);
            } else {
                $mailer = Craft::createObject($config);
            }

            return $mailer;
        },
    ]
];
```

(Note there’s no need to go through a second transport adapter; from here it’s easier to just set the new `transport` config directly on `$config`.)

**Comment by brandonkelly** [comment]
(Just updated the previous example to be more future-proof, as I just realized that `Mailer::getTransport()` was [made private](https://github.com/yiisoft/yii2-symfonymailer/pull/27/commits/64bd4b0bd4361b5e41a2cf9271bfdb6345073484) in yii2-symfonymailer 3.0.0.)
