### ISSUE TITLE
[3.1.32.1] Error 'Integrity constraint violation' when applying project.yaml

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#4446]
### Description

Updated a project to 3.1.32.1 and rebuild the project config. When applying this project.yaml file to a fresh install, there is an error:

`Integrity constraint violation: 1062 Duplicate entry 'Linked Text-12' for key 'matrixblocktypes_name_fieldId_unq_idx'`

PS.
This is only some educational stuff, so no high priority.

### Steps to reproduce

1. Fresh install of 3.1.32.1
2. Apply the project.yaml file from https://github.com/wsydney76/craft_starter/blob/master/config/project.yaml

This file was freshly rebuild from the database in https://github.com/wsydney76/craft_starter/tree/master/_data

### Additional info

- Craft version: Craft Pro 3.1.32.1
- PHP version: 7.2.14
- Database driver & version:  MySQL 5.7.14
- Plugins & versions: Control Panel CSS | 2.2.0

**Comment by brandonkelly** [comment]
That `project.yaml` file defines four separate block types with the name “Linked Text”, all for the same Matrix field (UID `58b2e318-26cc-47b8-bee2-81369731d72f`).

Do you know how that ended up happening? (Take a look through your `storage/config-backups/` folder for clues.)

**Comment by wsydney76** [comment]
@brandonkelly Thanks, i deleted the orphaned blocktypes from project.yaml and reapplied, works fine.

Looking through the config-backups i find a first version with one instance of the type, and than newer versions with two, three, four.

The config field in the info tabled also showed four block types, whereas the matrixblocktypes table has only one.

Looking back, i remember there were some cases where input seemed not to be saved, but i didn't really  pay attention, attributing it to same wrong key strokes or mouse clicks (i don't function well in the heat) or network problems, so i can't tell what happened exactly.

So all fine for now, no further issues occurred, thanks again, i will have a look if something like that happens again.

**Comment by brandonkelly** [comment]
Huh, strange. Keep an eye out for that issue. If you end up reproducing it, please send your `composer.json` and `composer.lock` files and a database backup over to support@craftcms.com with steps to reproduce.
