### ISSUE TITLE
Decimal input locale problem (German and German (Switzerland))

### ISSUE THREAD

**Issue by christianruhstaller** [craftcms/cms#4447]
### Description
As a user you want to input your decimal values like you're used to in your localization. Currently for swiss people this is not possible, because the control panel currently only has the "german" translation but the default german locale uses a different decimal point character. 

Swiss people want to enter "2.0" but the Craft CP with the german translation needs "2,0" (Which from a technical standpoint is correct).

de: http://www.localeplanet.com/icu/de/index.html
de-CH: http://www.localeplanet.com/icu/de-CH/index.html

There should be the option to use the locale "de-CH" for the control panel.

**Comment by brandonkelly** [comment]
You can add support for de-CH by setting the [extraAppLocales](https://docs.craftcms.com/v3/config/config-settings.html#extraapplocales) config setting in `config/general.php`.

```php
'extraAppLocales' => ['de-CH'],
```

If you don’t have the [Intl extension](https://www.php.net/manual/en/book.intl.php) installed, then you will need to manually configure Craft to support that locale, by creating a new `config/locales/` folder, and then downloading [this file](https://github.com/craftcms/locales/blob/master/locales/de-CH.php) to it.
