### ISSUE TITLE
[3.2] In multi-language setup, '-1' is appended to slugs

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#4448]
### Description

When editing an entry in a multi-language setup, '-1' is appended to the slug of other sites.

### Steps to reproduce

1. Fresh install of 3.1.32.1
2. Site up sites like this:

![image](https://user-images.githubusercontent.com/25308802/60167694-e2dd7980-9803-11e9-9e12-b19f0c797dbf.png)

3. Create a section with propagation methods 'to all sites'
4. Update to 3.2-RC1

5. Create an entry (in site en) and click 'Save enty', elements_sites tables shows correctly:

![image](https://user-images.githubusercontent.com/25308802/60167950-6e570a80-9804-11e9-90a8-89a41193ae89.png)

6. Make a change and click 'Update entry':

![image](https://user-images.githubusercontent.com/25308802/60168256-c857d000-9804-11e9-9887-dd0b3a7e5ef3.png)

So repeatedly making changes in both site will end up with something like

![image](https://user-images.githubusercontent.com/25308802/60168474-313f4800-9805-11e9-829e-a935f51c06c6.png)

### Additional info

Craft version: Craft Solo 3.2.0-RC1
PHP version: 7.2.14
Database driver & version: MySQL 5.7.14

**Comment by tillramstein** [comment]
fighting the same issue in version 3.2.0-beta.3

**Comment by brandonkelly** [comment]
I’m not able to reproduce this, however I think I see how this could possibly happen, and have addressed that.

If either of you have time to test, please change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "3.2.x-dev#22b510914faac64f3ca21b0a230041069ecef0af as 3.2.0-RC1",
  "...": "..."
}
```

Then run `composer update`.

**Comment by wsydney76** [comment]
@brandonkelly Thanks, but...

So, in a fresh install, when i create a new entry and click save, iget:

![image](https://user-images.githubusercontent.com/25308802/60246109-4fb54a00-98be-11e9-9189-15a2eb8ce54d.png)


Changing to the german site and replacing every occurence of 'en' with 'de' and clicking Update entry, the new  Title  is copied to the enlish site:

![image](https://user-images.githubusercontent.com/25308802/60246249-973bd600-98be-11e9-9ee2-5270b4376874.png)


When you change the title back in the english site and update, the slug and the translatable field are copied over :

![image](https://user-images.githubusercontent.com/25308802/60246535-2812b180-98bf-11e9-9db8-cfbcafa7b950.png)

So, things are a bit weird and random, and are effecting the actual content this time.

PS.
I've copied things to https://github.com/wsydney76/craft_slug_issue_4448 in case you want to look into it. admin/password

**Comment by herlea** [comment]
I just tested this in our site, using the version @brandonkelly suggested. I get the same issues @wsydney76 observed. It does no longer append 1 to the slugs. But it copies slugs from one language to the other. ( This does not happen on every save tho, and I don't understand when or why it does or does not. I agree that this seems weird and random right now. )

**Comment by brandonkelly** [comment]
I think 80594518a2e1476ba9a32681eb35050084135d99 may have fixed this. Can someone here please test that?

To test, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "3.2.x-dev#3449e30688d06d64e85017d9db7861c3635a029f as 3.2.0-RC2",
  "...": "..."
}
```

Then run `composer update`.

**Comment by wsydney76** [comment]
For me with just a few tests, that seems to work. Couldn't test all possible variations though.

(Still saw the same issues with the previously in 3.2  entered items, but probably they weren't saved correctly)

One thing, possibly unrelated: If you change a title and leave the slug blank, the new slug is not derived from the title, but the previous slug is restored.

Thanks.

**Comment by herlea** [comment]
Did a quick test, works for me.
Slugs seem to persist, nothing gets appended.
Very nice, thank you @brandonkelly!

**Comment by brandonkelly** [comment]
Thanks for checking!
