### ISSUE TITLE
@siteUrl alias when upgrading from Craft 2

### ISSUE THREAD

**Issue by bymayo** [craftcms/cms#4451]
### Description

I've just ran an update on a Craft 2 > Craft 3 site. All went smoothly, apart from when I tried to use the base URL of the site.

It seems when the migration took place it used `@siteUrl` alias as the Base URL inside a site, where it should be `@web` instead.

(Also the same issue with Asset Sources, having `@baseUrl` instead of `@web`)

### Steps to reproduce

1. Upgrade a project from Craft 2 > Craft 3
2. Go to Settings > Sites and check the Base URL field.

### Additional info

- Craft version: Craft CMS 3.1.27
- PHP version: 7.1.22 
- Database driver & version: MySQL 5.7.23
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
The migration won’t inject the `@web` alias into your URLs; it will only check to see if you were using [environment-specific variables](https://docs.craftcms.com/v2/multi-environment-configs.html#environment-specific-variables), and if so convert those to aliases. So in your case you must have had your site URL set to `{siteUrl}`, and an asset source URL set to `{baseUrl}...`, referencing `siteUrl` and `baseUrl` keys in your [environmentVariables](https://docs.craftcms.com/v2/config-settings.html#environmentvariables) config setting.

That config setting was removed in Craft 3, but if it’s set, Craft will treat its values as [custom aliases](https://docs.craftcms.com/v3/config/config-settings.html#aliases).

**Comment by bymayo** [comment]
In the old Craft 2 config it was like this:

```

    $baseUrl  = $protocol . $_SERVER['HTTP_HOST'] . '/';
    $basePath = realpath(dirname(__FILE__) . '/../../') . '/';

    return array(
        '*' => array(
            ...
            'siteUrl' => $baseUrl,
            'environmentVariables' => array(
                'baseUrl'  => $baseUrl,
                'basePath' => $basePath
            ),
...
```

So are you saying because we set these in the `general.php` config file, that it's pulled these through? But used the array keys as the aliases? 

Looking back at this config, it's horrible (We customised it!) compared to the Craft 3!

**Comment by brandonkelly** [comment]
No, I’m saying that the actual Site URL was likely set to `{siteUrl}`, and the asset source setting likely began with `{baseUrl}`. And those tags were converted to aliases during the migration.
