### ISSUE TITLE
PHP error on Settings > Fields

### ISSUE THREAD

**Issue by brycekirk** [craftcms/cms#4458]
### Description
Getting an error when I got to Settings > Fields: 
Argument 1 passed to craft\services\Fields::getGroupById() must be of the type integer, null given, called in /Applications/MAMP/htdocs/ackah_law/vendor/craftcms/cms/src/base/Field.php on line 447

Running ./craft project-config/rebuild does not fix the issue

### Steps to reproduce

1. Go to the admin panel > Settings > Fields

### Additional info

- Craft version: Craft Solo 3.1.32.1
- PHP version: 7.3.1
- Database driver & version: MySQL 5.7.25

**Comment by brycekirk** [comment]
Reverted to an earlier database backup and deleted the contents of storage > runtime and I can at least view and add fields again. Seems like there's a bug here though.

**Comment by brandonkelly** [comment]
If you are able to reproduce it later, please send your `composer.json` and `composer.lock` files and a database backup to support@craftcms.com.
