### ISSUE TITLE
[3.2] FR: Let plugins register preview targets

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#4477]
### Description

It'd be great if there was an event that let plugins manipulate a section's preview targets, similar to how something like `UrlManager::EVENT_REGISTER_CP_URL_RULES` or `Element::EVENT_REGISTER_SOURCES` works.

**Comment by brandonkelly** [comment]
It’s possible! Use the new [EVENT_REGISTER_PREVIEW_TARGETS](https://github.com/craftcms/cms/blob/d46c389981002c9bec933f1789cccdb3692e5d77/src/base/Element.php#L157-L160) event.

https://github.com/craftcms/cms/blob/d46c389981002c9bec933f1789cccdb3692e5d77/src/base/Element.php#L157-L160

**Comment by mmikkel** [comment]
@brandonkelly Doh, I should've looked harder! Thanks.
