### ISSUE TITLE
Translation for update entry button

### ISSUE THREAD

**Issue by robbue** [craftcms/cms#4480]
### Description
How to add translation for "Update entry" button?
![Skjermbilde 2019-07-03 14 00 03](https://user-images.githubusercontent.com/1470041/60590101-69adcb80-9d9b-11e9-9aef-09c66c429e62.png)
`nb` translation gives the translation "Update artikkel" (only the second word is correct). But I cant find a way to change it (and could then submit a PR).

### Additional info

- Craft version: 3.2.0-RC3

**Comment by brandonkelly** [comment]
The source string there is `Update {type}`:

https://github.com/craftcms/cms/blob/d92d506a0fd4768756223467f058d8cd4b34359d/src/templates/_layouts/element.html#L94

**Comment by robbue** [comment]
Thank you! Is there a reason that the string is not present in the [translation](https://github.com/craftcms/cms/tree/develop/src/translations) files?

**Comment by wsydney76** [comment]
@brandonkelly Correct translations are probably on your agenda, so just a reminder:

`{{ 'Save {type}'|t('app', { type: element.displayName()|lower })`  will show as "[Save..] eintrag" in language 'de', yet nouns always begin with a capital letter in german.

Has to be in reverse order anyway, something like `{type} speichern` => "Eintrag speichern"

**Comment by brandonkelly** [comment]
@robbue We haven’t updated translations for 3.2 yet, so none of the new strings are in the translation files yet.

@wsydney76 Just because the source string is `Save {type}` doesn’t mean you can’t change the position of `{type}` in the translated message.

**Comment by wsydney76** [comment]
@brandonkelly Sorry, i just wanted to say that we need the type value to start with a capital letter in German.

So maybe you can pass in both like

`'Save {type}'|t('app', {typeCapitalized:element.displayName(), type: element.displayName()|lower })`

so that it can be translated to `'{typeCapitalized} speichern'` ?

**Comment by brandonkelly** [comment]
Gotcha. We’re going to be moving to Title Casing button labels in general anyway, so I just removed the `|lower` filters there.
