### ISSUE TITLE
[3.2] Validate related entries setting infinite loop.

### ISSUE THREAD

**Issue by JamesNuttall** [craftcms/cms#4482]
### Description
I think I have found an issue with the "Validate related" field setting that causes an infinite loop.

The issue occurs, in this case, when having a category that is related to an entry via an "Entries" field type, where that entry is also related to the original category via a "Categories" field type. I believe this is resulting in the following if both the "Categories" and "Entries" field types have the "Validate related {type}" option selected:

When opening the entry in the CP the [validateRelatedElements function](https://github.com/craftcms/cms/blob/3.2/src/fields/BaseRelationField.php#L259) attempts to validate each field, upon reaching the "Categories" field type field it then tries to validate the category, which then will try to validate the "Entries" field type field on the category, which then will try to validate the "Categories" field type field on the entry and here we have our loop!

### Steps to reproduce

1.  Setup a category that has one field of field type "Entries" with "Validate related entries" selected.
2. Setup an entry that has one field of field type "Categories" with "Validate related categories" selected.
3. Create a category inside the category type just created.
4. Create an entry in the new entries section and select the just created category in the categories field and save the entry.
5. Now go back to the category and attach the just created entry in the entries field and save.
6. From the index, try to go back into the just saved category and the loop/timeout should occur.

### Additional info

- Craft version: 3.2.0-RC3
- PHP version: 7.1.11

**Comment by JamesNuttall** [comment]
For some more background information/context. Our use case is that we have news articles that belong to categories but then those categories also have a "featured" article field, which is how we get the relation loop.

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "3.2.x-dev#dbbacb5cbb981abeaece99c380f8438ecd2d22c7 as 3.2.0-RC3",
  "...": "..."
}
```

Then run `composer update`.

**Comment by JamesNuttall** [comment]
Cheers for yet another rapid response/fix!

**Comment by WHITE-developer** [comment]
Looks like I get the same problem if I select the entry I'm currently editing in an entries selector. After saving and going back to that entry I get the xdebug `Maximum function nesting level of '256' reached, aborting!` error.
Disabling the related entries check makes the entry accessible again.

Craft 3.2.6

**Comment by brandonkelly** [comment]
@WHITE-developer Can you please send your `composer.json` and `composer.lock` files, plus a database backup, over to support@craftcms.com? Reference this GH issue and steps to reproduce in the body, and then we can look into it.

**Comment by WHITE-developer** [comment]
Hmm, not sure anymore how to reproduce it :see_no_evil:, as the site is in development and I changed the settings to move forward.
I'll let you know if I get the issue again.

**Comment by WHITE-developer** [comment]
~Hmm, not sure anymore how to reproduce it :see_no_evil:, as the site is in development and I changed the settings to move forward.~
~I'll let you know if I get the issue again.~
Found it, you've got mail.

**Comment by brandonkelly** [comment]
Alright so a version of this bug still existed if the source element had multiple relational fields, each with relation validation enabled, *and* circular relations as well. Fixed now for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#6924f79fd3cfcee4d23cdba6d34b46c5768c8c78 as 3.2.9",
  "...": "..."
}
```

Then run `composer update`.
