### ISSUE TITLE
Craft 3.1.30 breaks duplicating of entries

### ISSUE THREAD

**Issue by lukasNo1** [craftcms/cms#4485]
I testet it with 2 different sites.

Duplicating entries on our websites only works until Version 3.1.29.
The changes in Version 3.1.30 broke something.

Is this something you can reproduce?

Error Message:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4824-2' for key 'content_elementId_siteId_unq_idx'
The SQL being executed was: INSERT INTO `content` (`elementId`, `siteId`, `title`, `field_lead`, `dateCreated`, `dateUpdated`, `uid`) VALUES (4824, 2, 'test', 'test', '2019-07-04 11:57:50', '2019-07-04 11:57:50', '070c9f66-2f4c-4caa-9706-5b217d0ac8be')

### Additional info

- Craft version: 3.1.30
- PHP version: 7.3.3
- Database driver & version: 10.1.26-MariaDB

**Comment by joao-proenca-ef** [comment]
I have the same issue.

A easy way to reproduce is:

1. Create a new Craft install,
2. Add a new Site with another language, so we have 2, 
3. Create a section, I've done a Structure, 
4. Create a entry in that structure, 
5. and finally try to duplicate it using Save as a New Entry

### Additional info

- Craft version: Craft Solo 3.1.33
- PHP version: 7.2.5
- MySQL: 5.5.5

**Comment by brandonkelly** [comment]
We are releasing Craft 3.2.0 on Tuesday, which brings some improvements to element duplication. Can you please test on that?

To update to 3.2.0 ahead of time, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "^3.2.0-RC3",
  "...": "..."
}
```

Then run `composer update`.

**Comment by joao-proenca-ef** [comment]
The Craft 3.2.0 RC3 seems to work correctly!

**Comment by lukasNo1** [comment]
Yes, 3.2.0 RC3 fixes the duplicating for me too.

Im gonna go ahead and close the issue.

**Comment by brandonkelly** [comment]
@joao-proenca-ef @lukasNo1 Thanks for confirming!
