### ISSUE TITLE
restore/db command do not fully reset the database to its previous backup state

### ISSUE THREAD

**Issue by juban** [craftcms/cms#4486]
### Description

When using the craft command `./craft restore/db`, the backup file is restored but leaves potential additional tables behind which could lead to migrations errors :
For instance, when upgrading Craft from version 3.1 to 3.2, the first migration adds new tables like `draft` and `revision` tables.
Afterward, if one want to downgrade Craft to 3.1 again and restore a 3.1 backup file then upgrade to 3.2 again, this will lead to migration errors because `draft` and `revision` tables were not removed by the previous restore process and already exists.
In my opinion, the `restore/db` command should "fully" restore the previous database state.

### Steps to reproduce

1. Create a database backup using Craft 3.1.29 or upper
2. Upgrade Craft CMS to version 3.2
3. Apply the migrations with `.craft migrate/all`
4. Downgrade Craft CMS to 3.1.29 again
5. Restore the previous database backup from step 1
6. Apply the migrations with `.craft migrate/all` (optional)
7. Upgrade Craft CMS to version 3.2 again
8. Apply the migrations with `.craft migrate/all`

### Additional info

- Craft version: >3.1.29 and 3.2
- PHP version: 7.2.19
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
Unfortunately it’s not possible for us to do this. You’d just have to delete the whole database and then recreate it, before restoring.
