### ISSUE TITLE
Saving Entry as draft increments slug if same as slug in other channel/structure level

### ISSUE THREAD

**Issue by degraaf** [craftcms/cms#4487]
### Description

There seems to be a problem in the validation/generation of slugs, but only when saving an existing entry as a draft.

### Steps to reproduce

1. Create entry under a structure section (e.g. we have a structure for page content), with the name "Slug Test Page" and slug "slug-test-page"
2. Create a second entry with the same name "Slug Test Page" and slug "slug-test-page", and select the first page as the parent. Pages are created with slugs as expected:
/slug-test-page
/slug-test-page/slug-test-page
4. Go back to the second test page and select "Save as draft"
5. Slug will be automatically updated and incremented, even though it shouldn't be. We now have:
/slug-test-page
/slug-test-page/slug-test-page-1
6. When the draft is published, URLs have changed and external links break.

**Other notes**

This seems to occur for entries in other sections or any level of the same section/structure. It is not checking against the URI but is just reading the slug portion and incrementing when it shouldn't.

We've alerted our content authors to watch out when creating drafts to ensure the slug/URL doesn't change.

### Additional info

- Craft version: 3.1.30
- PHP version: 7.1.17
- Database driver & version: Ver 14.14 Distrib 5.7.26, for Linux (x86_64) using  EditLine wrapper
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
I was able to reproduce this, however the bug doesn’t occur in Craft 3.2.0, which will be released on Tuesday.

To update to Craft 3.2 a little early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "^3.2.0-RC3",
  "...": "..."
}
```

Then run `composer update`.
