### ISSUE TITLE
Update from 3.1.20.1 to 3.1.33 completely broke my install

### ISSUE THREAD

**Issue by N0ps32** [craftcms/cms#4489]
### Description
Updating my craft installation from 3.1.20.1 to 3.1.33 completely broke my install. Any idea how to fix it?

```
Your project.yaml file was created for different versions of Craft and/or plugins than what’s currently installed.

Try running composer install from your terminal to resolve." 
```

I ran both composer update and install without any luck.

You can see the update I did here:
https://github.com/N0ps32/blog/commit/84b656428f56fe8f3ea7f41c926fb7bb049566a7
  
I updated and verified that everything works locally and then pushed to production where it broke.

**Comment by brandonkelly** [comment]
Sounds like you had some pending `project.yaml` changes that weren’t synced up yet at the time that you updated Craft.

If you’ve already run `composer update` so there are new changes to `composer.lock`, try pulling in the most recent `composer.json` and `composer.lock` files from your `storage/composer-backups/`, and then run `composer install`, and see if that brings your site back up.

If you need additional help, please write into support@craftcms.com with SSH access credentials.
