### ISSUE TITLE
entry.enabledForSite returns string "0" or "1" instead of boolean

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#4491]
I'm not sure if its bug or desired behavior, but when I checked entry properties, I noticed that `enabledForSite` attribute returns strings `0` or `1` instead of boolean within Twig template.

**Comment by brandonkelly** [comment]
Yeah this is expected behavior if you are using MySQL, since MySQL doesn’t support boolean column types, and its PDO driver always returns strings.

**Comment by piotrpog** [comment]
@brandonkelly will this property behave the same if I used postgres?

**Comment by brandonkelly** [comment]
If you were using Postgres it would get set to `true` or `false`.

It doesn’t really matter either way though, as long as you don’t use strict type checks.

```php
// works reliably
if ($entry->enabledForSite)
if ($entry->enabledForSite == true)

// doesn't work reliably
if ($entry->enabledForSite === true)
```

**Comment by piotrpog** [comment]
@brandonkelly  thanks for explaining.
