### ISSUE TITLE
Access to dateDeleted?

### ISSUE THREAD

**Issue by boxadesign** [craftcms/cms#4493]
I have an endpoint that sets a response header when an entry is saved (code below).

Is there a similar method I can use when an entry is deleted?

```php
'api/entries.json' => function() {
    return [
        'elementType' => Entry::class,
        'criteria' => ['order' => 'dateUpdated asc', 'limit' => 1],
        'transformer' => function(Entry $entry) {
            \Craft::$app->response->headers->set('Last-Modified', date('D, j F Y H:i:s \G\M\T', $entry->dateUpdated->getTimestamp()));
            return [
                'updated' => $entry->dateUpdated,
            ];
        }
    ];
},
```

**Comment by brandonkelly** [comment]
Sorry, I didn’t realize that we were actually unsetting the `dateDeleted` value when retrieving trashed elements. I’ve just changed that for Craft 3.2.0, which should be released on Tuesday.

To update to 3.2 a little early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "3.2.x-dev#636ad42cf2656ec7a5e635ee2a7f81888bd9c59c as 3.2.0-RC3",
  "...": "..."
}
```

Then run `composer update`.

**Comment by boxadesign** [comment]
OK cool thanks.

**Comment by boxadesign** [comment]
@brandonkelly Works great. Thanks for your help on this.
