### ISSUE TITLE
Set the number of digits when using the filesize filter

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#4498]
### Description

It would be nice to be able to set the number of digits after the decimal point to display when using the `filesize` filter. Example: 500,771 Ko → 501 Ko, or 500,8 Ko.

It should be possible as this filter is using the `asShortSize` method: https://www.yiiframework.com/doc/api/2.0/yii-i18n-formatter#asShortSize()-detail.

**Comment by brandonkelly** [comment]
Since the filter is directly mapping to `Formatter::asShortSize()`, all of its arguments are also available to the filter. So both of these syntaxes are already possible:

```twig
{{ number|filesize(0) }}

{{ number|filesize(decimals=0) }}
```
