### ISSUE TITLE
[3.2] Structure entries with no children showing expand arrow

### ISSUE THREAD

**Issue by gregorterrill** [craftcms/cms#4504]
### Description
After updating to 3.2, some entries in a structure with no children are showing the expand arrow next to them in the CP. If I inspect, I can see that the `data-descendants` attribute on those entries' table rows show a non-zero number, even though there aren't actually any descendants. Clicking the expand arrow causes a new row to flash in and then disappear.

I believe the affected entries _previously_ had children which were later moved to be top-level entries themselves (long before updating to 3.2).

Re-saving the entry, creating and deleting a new child entry, and clearing all caches all don't clear the issue.

### Additional info
- Craft version: 3.2
- PHP version: 7.1.18
- Database driver & version: MySQL 5.7.21

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.
