### ISSUE TITLE
If Entry Type doesn't have lightswitch field at all, is not included when using "not 1"

### ISSUE THREAD

**Issue by Dean-Wilson** [craftcms/cms#4506]
### Description

We have a lightswitch field that we use to filter entries. Turning this lightswitch on excludes the entry. We do this with code like this:

`craft.entries({lightSwitchFieldHandle: 'not 1'})`

However, there are some entry types that don't have the light switch field in their field layout at all. They don't need it and shouldn't have it. We would expect those entries to be included in the results as they don't have the light switch field on. However, they are excluded. This doesn't seem like it should be expected behaviour? 

### Steps to reproduce

1. Create a Light switch field 
2. Exclude with 'not 1' based on that light switch field
3. Create an entry type that doesn't have the lightswitch field in the field layout

### Additional info

- Craft version: Craft Pro 3.1.25
- PHP version: 7.1.4
- Database driver & version: 5.5.6

- Plugins & versions:
Contact Form	2.2.4
Control Panel CSS	2.1.0
Craft Dynamic Fields	3.0.8
Entry Instructions	1.0.4
Field Manager	2.0.5
Google reCAPTCHA for Sprout Forms	1.0.5
Imager	v2.1.10
Inlin	2.1.1
Neo	2.3.2
Redactor	2.3.3.2
Relabel	1.3.0
Retour	3.1.14
SEOmatic	3.1.50
Sprout Fields	3.3.0
Sprout Forms	3.2.2
Sprout Reports	1.1.6
Super Table	2.1.18
Table Maker	2.0.1
Typed link field	1.0.19
Video Embedder	1.1.1
Visor	2.1.0

**Comment by brandonkelly** [comment]
When you set that value to `not 1` you are just saying to not include any elements where the Lightswitch field value is set to `1`, which is going to be the case for all entires that don’t have the field at all. So this is expected behavior.

I’d recommend you also add a `type` param to the query as well, to only look for entries with a certain entry type:

```twig
{% set entries = craft.entries()
    .lightswitchFieldHandle('not 1')
    .type('entryTypeHandle')
    .all() %}
```
