### ISSUE TITLE
After upgrading to Craft 3.2 I have problems saving entries with a date field.

### ISSUE THREAD

**Issue by handplant** [craftcms/cms#4508]
### Description
After saving a change in an entry with date field, the following message appears:

Internal Server Error
Server Error

The web logfile contains the following:
PDOException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x98\x8E? ...' for column `mysite`.`revisions`.`snapshot` at row 1 in /vendor/yiisoft/yii2/db/Command.php:1290

### Steps to reproduce

1. Edit an entry with date field
2. Change something and click "Update Entry"

### Additional info

- Craft version: Craft Pro 3.2.0
- PHP version: 7.2.14
- Database driver & version: MySQL 5.5.5

**Comment by handplant** [comment]
Okay. I'm sorry. That was my problem. I have emotjis in the text which cause the error! :( Please close the issue!

**Comment by brandonkelly** [comment]
You had emojis in the date field? Or a different field type?

**Comment by handplant** [comment]
No, a Plain Text Field.

**Comment by brandonkelly** [comment]
Emojis should be getting converted to shortcakes in the backend. Do you remember which emoji character(s) were triggering this so we can look into it?

**Comment by brandonkelly** [comment]
I was able to reproduce this by temporarily disabling the emoji-shortcode conversion, and updated the UI to do a better job identifying the issue:

<img width="321" alt="A heads-up display explaining why a draft couldn’t be saved" src="https://user-images.githubusercontent.com/47792/61011633-430a0a80-a330-11e9-9f64-a3393f32458b.png">

Hopefully that’ll save people some troubleshooting time in the future.

**Comment by narration-sd** [comment]
‘that, and convincing  your phone you’re not talking about cake recipes 🍰’

**Comment by handplant** [comment]
I have the problem in several installations after updating to 3.2. In version 3.1.x I have no problems. What can I do? How can I activate emoji-shortcode?

**Comment by brandonkelly** [comment]
@handplant it just happens automatically. What exactly are you doing?

**Comment by handplant** [comment]
@brandonkelly Nothing special. Update to 3.2 without problem. After that I try to save this emoji 😃 in a plain text field. The draft is saved in the background without problems. After click "Update entry" the following error occurs: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x98\x80 \xF0...' for column `mysite`.`revisions`.`snapshot`.

**Comment by brandonkelly** [comment]
Doh, I guess I should have tested actually saving entries with emojis, rather than just ensuring draft saving was working :)

Just fixed this for the next release. To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#43d22b4403fb555e1d8db3efc4b9978071b1deb5 as 3.2.0",
  "...": "..."
}
```

Then run `composer update`.

**Comment by khalwat** [comment]
I'm experiencing this too: https://github.com/nystudio107/craft-seomatic/issues/606#issuecomment-615289143
