### ISSUE TITLE
Setting unknown property: craft\records\Element::draftId After upgrading to Craft 3.2

### ISSUE THREAD

**Issue by Sam-Black-0013** [craftcms/cms#4509]
### Description
After i upgraded to Craft 3.2 I get this error when visiting the control panel: Setting unknown property: craft\records\Element::draftId
The entire control panel urls show this error

**Comment by brandonkelly** [comment]
Did you get any errors when updating? Can you check if your `elements` database table in fact has a `draftId` column now?

**Comment by Sam-Black-0013** [comment]
I did not get any errors while updating. I did not get an "Update database" screen after i finished the update, so the database is still for Craft 3.1.34

**Comment by ep-iain** [comment]
I am also having this issue. 

In my case the migrations for Craft 3.2 all ran successfully and my `elements` table has a `draftId` column.

**Comment by ep-iain** [comment]
Update: Clearing caches from the CP seems to have fixed it

**Comment by brandonkelly** [comment]
@Sam-Black-0013 How did you update? From the Control Panel or by running `composer update` / `./craft update craft` ?

**Comment by Sam-Black-0013** [comment]
Composer update

**Comment by brandonkelly** [comment]
@Sam-Black-0013 Can you search for the error in `storage/logs/web.log` and post the full error log, with the stack trace?

**Comment by Sam-Black-0013** [comment]
Mr. @brandonkelly
I did not find any errors in the log, but i waited after you guys released the 3.1.34.2 update, and now it updated successfully.

**Comment by Sam-Black-0013** [comment]
Mr. @brandonkelly 
I had some codes in my plugin's init() function which caused it to crash.
I removed it, and Craft updated successfully.
It is some conditions i need to check with every page, so i don't have any event i can attach it to (Mostly for commerce)
Is there any way I can execute this code without causing the update to crash every time ? 
It would be awesome if there was an event we could use for each page load O_O

**Comment by brandonkelly** [comment]
@Sam-Black-0013 Can you post the code that triggered the error?

**Comment by DavidOliver** [comment]
I cleared the following caches to get around this. I don't know precisely which caches needed to be cleared, but at least it avoids assets caches having to be regenerated.

- Compiled templates
- Data caches
- Temp files
- Template caches

**Comment by Sam-Black-0013** [comment]
```
        $request = Craft::$app->getRequest();
        if($request->getSegment(1) != "api"){
            $cart = Commerce::getInstance()->getCarts()->getCart(true);
            if(isset($cart)){
                $MaxAmount = Craft::$app->globals->getSetByHandle('globols')->getFieldValue('MaxAmount');
                $MinAmount = Craft::$app->globals->getSetByHandle('globols')->getFieldValue('MinAmount');
                $finalTotalPrice = $cart->getItemSubtotal();
                $localDiscountTotal = $cart->getAdjustmentsTotalByType("localDiscount");
                if($localDiscountTotal < 0){
                    $finalTotalPrice += $localDiscountTotal ;
                }
                if($cart->gatewayId == 1 && ($finalTotalPrice > $MaxAmount || $finalTotalPrice < $MinAmount)){
                    $cart->setGatewayId(2);
                }
            }
        }
```
We have like 3 payment gateways, but one had a condition if the cart's total is between two values
we force change the cart gateway.
@brandonkelly

**Comment by brandonkelly** [comment]
Ah, makes sense. Craft is defensive about only selecting draft data if the DB has been updated with 3.2 changes, but the same checks are not in place when inserting/updating data.

So this line:

```php
$cart = Commerce::getInstance()->getCarts()->getCart(true);
```

Will always trigger cart creation or update.

You could make this a bit more bulletproof for future Craft/Commerce updates by adding this check to the beginning of your code:

```php
if (Craft::$app->updates->getIsCraftDbMigrationNeeded() || Craft::$app->updates->getIsPluginDbUpdateNeeded()) {
    // waiting on DB migrations to run
    return;
}
```

Update issues aside, a couple other suggestions:

First, this line:

```php
if($seg!= "api" &&$seg == "checkout" ){
```
Could be simplified to:

```php
if ($seg === 'checkout') {
```

Since `$seg` is never going to be `api` if it is set to `checkout`.

And this line:

```php
$cart = Commerce::getInstance()->getCarts()->getCart(true);
if(isset($cart)){
    // ...
}
```

is *always* going to pass, because `getCart()` will create a cart if there isn’t one already.

Here’s how you can check if the current session contains a cart number, which you can do before fetching the `$cart`:

```php
$session = Craft::$app->session;
$cartsService = Commerce::getInstance()->getCarts();
$hasCartNumber = ($session->getHasSessionId() || $session->getIsActive()) && $session->has($cartsService->cartName);
if ($hasCartNumber) {
    $cart = $cartsService->getCart(true);
    // ...
}
```

I’ve just [added](https://github.com/craftcms/commerce/commit/ef683c60637591422ef59fbadeefcd74b59009b0) a new `getHasSessionCartNumber()` method to the Carts service for the next Commerce release (will be 2.1.11). Once that is out and you’ve updated to it, you could simplify that code to:

```php
$cartsService = Commerce::getInstance()->getCarts();
if ($cartsService->getHasSessionCartNumber()) {
    $cart = $cartsService->getCart(true);
    // ...
}
```

**Comment by Sam-Black-0013** [comment]
Thank u very much Mr. @brandonkelly 
Actually in this file: Services -> Carts -> getCart() -> Line 79 throw an exception if the user opened the site (with no cart and not logged in), but after a refresh everything works fine.
So when i tried to check the cart, that line returned a null and the exception was thrown.
I added the check and the problem stopped.
