### ISSUE TITLE
Project config does not install plugins

### ISSUE THREAD

**Issue by jasonmccallister** [craftcms/cms#4510]
### Description
I'm running my project in Docker and deploying to Amazon ECS. I have an issue where the project config changes are occurring successfully (e.g. new fields and categories are synced). 

However, none of the plugins are being installed. I have ensured that they are:

1. listed in composer.json and composer.lock
2. verified they are present in /vendor/craftcms/plugins.php (thanks Brandon)
3. visible in the project.yaml

To make it more confusing, I enabled admin changes in the staging environment and when I go to the plugins page, the license keys show for the plugins but each plugin (that has a key in the `project.yaml`) is listed as `missing` but contain the license keys from the `project.yaml`. Also, the plugins that don't have keys don't show up.

### Steps to reproduce

1. Use project config
2. Deploy Docker based setup to staging environment and check for plugins

### Additional info

- Craft version: 3.2 and 3.1.34
- PHP version: 7.2.20
- Database driver & version: PostgreSQL 11.2
- Plugins & versions: none ;)

Also, `composer` is not available in the final docker image, as we are using docker's multi-stage build process. Is having composer available a dependency of project config?

**Comment by jasonmccallister** [comment]
This may be related to #3651

**Comment by brandonkelly** [comment]
When a plugin is shown as `missing`, that means Craft knows you have a license for it, but the plugin is not Composer-installed yet.

**Comment by jasonmccallister** [comment]
It’s showing up in composer, do I need to install it a special way?

**Comment by jasonmccallister** [comment]
Ok so this one was on me 100%... 

Here is the deal.... I was using a Docker multi-stage build. Here is Dockerfile:

```Dockerfile
FROM composer as vendor
COPY composer.json composer.json
COPY composer.lock composer.lock
RUN composer install --ignore-platform-reqs --no-interaction --no-plugins --no-scripts --prefer-dist

FROM php:7.3-apache-stretch
# rest of the code to install extensions and dependencies
```

If you have a keen eye, you might spot the issue right away... I didn't. I took this from a Laravel project where we did not need to run composer plugins, so I left `--no-plugins` in the vendor step. Removing this resolved the issue... Hopefully someone else finds this useful!

**Comment by brandonkelly** [comment]
Aha! So `vendor/craftcms/plugins.php` wasn’t getting updated.
