### ISSUE TITLE
[Minor request] Change log file renaming pattern

### ISSUE THREAD

**Issue by proimage** [craftcms/cms#4511]
### Description
When a log file in `storage/logs/` reaches a certain size limit (looks to be around 10Mb), it's renamed to (for example) `web.log.1` and a new `web.log` is started. This naming changes the extension and thus makes the file look like a different filetype entirely (a `something.1` file).

![image](https://user-images.githubusercontent.com/1027523/60972706-7730fb80-a32f-11e9-81ff-d7e1f2120a40.png)

Can the renaming pattern switch from creating `web.log.1`-style files to `web.1.log`-style ones, thus preserving the file extension?

### Steps to reproduce

1. Use a Craft site enough to generate more than 10Mb of log data.
2. Look in `storage/logs` to see the filenames.

### Additional info

- Craft version: 3.1.34

**Comment by brandonkelly** [comment]
This is something that Yii would need to change.
