### ISSUE TITLE
No pagination with structure entry list

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#4516]
I updated Craft to 3.2 and control panel list of entries that is structure (with multiple levels)  still uses lazy loading. Is this expected behaviour?

"All entries" listing uses pagination.

**Comment by brandonkelly** [comment]
Yes, when you are viewing a Structure section or category group, and sorting by Structure (so you see the hierarchy), lazy-loading is expected. It’s not really possible to paginate a hierarchy.
