### ISSUE TITLE
Saving re-named entry with deleted slug doesn't re-generate a new correct slug

### ISSUE THREAD

**Issue by jamiewade** [craftcms/cms#4518]
### Description
When you take an existing entry, re-name it, delete the contents of the `slug` field and hit save, the slug goes back to how it used to be.

It should re-generate a slug based off the new title of the entry.

### Steps to reproduce

1. Re-name an existing entry (don't hit save)
2. Delete the contents of the `slug` field
3. Save the entry

![bug](https://user-images.githubusercontent.com/6672331/60985466-73a07300-a335-11e9-8e47-62085319ee47.gif)

### Additional info

- Craft version: 3.2.0
- PHP version: 7.2.17
- Database driver & version: MySQL 5.7.26

**Comment by jerome2710** [comment]
Subscribing, I found this to be an issue as well.

**Comment by brandonkelly** [comment]
Just fixed this for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#14301610b2746a19b3fa7b3976f9446661329b81 as 3.2.1",
  "...": "..."
}
```

Then run `composer update`.
