### ISSUE TITLE
Asset Input Field: Variable "prevalidate" does not exist in jssettings.

### ISSUE THREAD

**Issue by bryanjhickey** [craftcms/cms#4523]
### Description
Opening an entry in Sprout Forms via control panel results on the Twig Runtime Error (see attached stack trace).

Error seems to be from Craft default Asset input field template. Is this a Craft or Sprout Forms plugin issue?

[stacktrace.log](https://www.dropbox.com/s/5tb2qivacztt1e3/stacktrace.log?dl=0)

### Steps to reproduce

1. Submit new form entry
2. View entry
3. Get Runtime error

### Additional info
Commenting out line #37 allows entries to be viewed.

- Craft version: 3.2.0
- PHP version: 7.3.4
- Database driver & version: MySQL 8.0.15
- Plugins & versions: Sprout Forms 3.3.2

**Comment by brandonkelly** [comment]
Technically that’s a backwards compatibility issue, so just fixed for the next release.
