### ISSUE TITLE
[3.2] project.yaml error on production environment

### ISSUE THREAD

**Issue by handplant** [craftcms/cms#4524]
### Description
After successfully updating to 3.2 in my local environment, it does not work on the production environment.

The following error message appears:

Applying changes from project.yaml ... error: Argument 1 passed to craft\services\Fields::restoreLayoutById() must be of the type integer, null given, called in /home/forge/mysite.de/vendor/craftcms/cms/src/elements/GlobalSet.php on line 192

### Steps to reproduce

1. Deploy with forge

```
git pull origin master
composer install --no-interaction --prefer-dist --optimize-autoloader
./craft migrate/all
./craft project-config/sync
./scripts/clear_caches.sh
```

### Additional info

- Craft version: Craft Solo 3.2.0
- PHP version: 7.2.19
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
Can you please send your `composer.json` and `composer.lock` files, plus a database backup, and your incoming `config/project.yaml` file, over to support@craftcms.com so we can look into this?

And in the meantime you may want to revert the update and restore a database backup.
