### ISSUE TITLE
[3.2] How can I downgrade.

### ISSUE THREAD

**Issue by boxadesign** [craftcms/cms#4527]
### Description

I'm experiencing problems with drafts not being saved and the workflow plugging borking.

I am attempting to downgrade but am getting this error:

`Craft CMS does not support backtracking to this version. Please update to Craft CMS 3.2.0 or later.`

### Steps to reproduce

1. Change the version to `3.1.34` in composer.json
2. Run `composer update`

### Additional info

- Craft version: 3.2
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
You would also need to restore a database backup from before the update (Craft would have attempted to save one in `storage/backups/`).

**Comment by dennismeissner** [comment]
Just to make this complete, when downgrading, you also have to check project config for the schema version.
