### ISSUE TITLE
[3.2] Editor role cannot save entries due to autosave

### ISSUE THREAD

**Issue by boxadesign** [craftcms/cms#4528]
### Description

- Editors do not have publish permissions.
- They create a new entry the entry appears to autosave.
- Navigating back to the entry list the entry is not created and saved in draft format.

### Steps to reproduce

See above

### Additional info

- Craft version: 3.2
- PHP version: 7.1.28
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#3ff133360c26dd1bcfe6986c9acf52bd4848b41e as 3.2.0",
  "...": "..."
}
```

Then run `composer update`.
