### ISSUE TITLE
[3.2] Database error - Invalid parameter number

### ISSUE THREAD

**Issue by tim-pixeldeluxe** [craftcms/cms#4529]
### Description
After updating Craft to version 3.2 I started seeing an error on one of our frontend pages. If you need any more info please let me know.

Stacktrace:
https://pastebin.com/TGqH7Fwz

It seems to be caused by this query, if I remove it my page works:
`entry.showcasedArticles.image(':notempty:').all()`
showcasedArticles is an entry select field.

### Steps to reproduce
1. Update to Craft 3.2
2. Visit a page that worked before the update

### Additional info

- Craft version: 3.2.0
- PHP version: 7.1.6
- Database driver & version: MySQL 5.5.59
- Plugins & versions:
```
"php": ">=7.0.0",
"craftcms/cms": "3.2.0",
"vlucas/phpdotenv": "^2.4.0",
"craftcms/redactor": "2.3.3.2",
"verbb/cp-nav": "2.0.9",
"verbb/expanded-singles": "1.0.7",
"craftcms/contact-form": "2.2.5",
"twbs/bootstrap": "4.0.0-beta.2",
"verbb/super-table": "2.1.20",
"topshelfcraft/wordsmith": "^3.0.4",
"verbb/field-manager": "2.1.0",
"mmikkel/cp-field-inspect": "1.0.5",
"sebastianlenz/linkfield": "1.0.19",
"mikestecker/craft-videoembedder": "1.1.3",
"ether/seo": "3.5.4",
"lukeyouell/craft-hideadmin": "1.0.1",
"supercool/tablemaker": "2.0.1",
"doublesecretagency/craft-siteswitcher": "2.1.0",
"anubarak/craft-relabel": "1.3.2.1",
"craftcms/commerce": "2.1.9",
"craftcms/commerce-mollie": "2.0.1",
"lukeyouell/craft-queue-manager": "1.1.0",
"pixeldeluxe/siteutils": "dev-master",
"pixeldeluxe/privatenamecore": "^1.0.0",
"ttempleton/craft-nocache": "2.0.4",
"solspace/craft-freeform": "3.2.1",
"adigital/help-links": "1.0.7",
"verbb/default-dashboard": "^1.0"
```

**Comment by angrybrad** [comment]
Can you send a database dump, your composer.json and composer.lock files and a template where we can try to reproduce the issue locally over to support@craftcms.com?

**Comment by angrybrad** [comment]
Fixed in https://github.com/craftcms/cms/commit/535d083fcff4375a7b0b1ed2122a33de24cf8c32
