### ISSUE TITLE
[3.2] Unable to acquire a lock for the structure 1

### ISSUE THREAD

**Issue by RobErskine** [craftcms/cms#4536]
### Description
Hey there. When we were on version 3.0.0 we were getting a 503 error when trying to duplicate entries in a structure. 

```php
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry
```

I found a few other tickets of people running into that issue without a solution, other than them sending a DB backup and the ticket gets closed:
1: https://github.com/craftcms/cms/issues/2747
2: https://github.com/craftcms/cms/issues/2503

I tried to fix this on my own with the [Fix FKs plugin](https://github.com/craftcms/fix-fks) but the issue persisted. 

In an attempt to fix this, we updated to the latest version of Craft 3.2.1. We're getting the same error, but a different error message now. 

```php
Unable to acquire a lock for the structure 1
```

![picture of error message](https://cl.ly/aed4cfa4f8fe/Screen%20Shot%202019-07-11%20at%206.46.11%20PM.jpg)

I imagine the issue is the same as the other two tickets. Something is out of sync or wasn't completely deleted and now it's unable to create duplicates of an entry because it already exists. 

Is there anything I can do to remedy this?

### Steps to reproduce

1. Attempt to duplicate entry in a structure
2. See error message

### Additional info

- Craft version: 3.2.1
- PHP version: 7.0
- Database driver & version: MySQL 5.5.5
- Plugins & versions: 
  - redactor - 2.1.6
  - usermanual - 2.0.2
  - field-manager - 2.04
  - neo - 2.3.1
  - enupal snapshot - 1.2.3
  - cp-css - 2.1.0
  - fieldlabels - 1.0.7
  - cp-js - 2.1.0
  - email-on-acid (custom) - 1.0.0
  - fetch - 1.2.0
  - inline - 1.0.1
  - workflow (custom) - 1.0.0
  - super-table - 2.1.18
  - comments - 1.1.7.1
  - minify - 1.2.9
  - user-initials-photo (uninstalled) - 1.1.1
  - snitch - 2.1.0
  - craft-page-exporter - 1.1.2
  - craft dynamic fields - 3.0.8

**Comment by angrybrad** [comment]
Can you send a database dump as well as your composer.json and lock files over to support@craftcms.com and point us to which structure/entry to try and reproduce with?

**Comment by RobErskine** [comment]
I just sent an email to support with all of that info. Thanks again and hope y'all are having a rad weekend.

**Comment by RobErskine** [comment]
This is probably related, and I would love some confirmation if so, but we had over 20,000 pending tasks in our `queue` table after upgrading to 3.2. The one that took the longest was "Updating Entry Drafts and Revisions".  After that we had 10 instances of "Updating Search Indexes" and then every 11th instance was an "Updating Element Slugs and URIs" task. 

These tasks kept timing out on my local machine, but after putting them on a dedicated server they fully ran after 12 hours or so and our `queue` db is now empty. We're now able to duplicate entries without any problems. 

I'm still digging but I think what happened is that something was updated on the server's database 
(from a composer install) that got out of sync with one of our local data/code bases, and then caused a spiral of issues as stuff attempted to propagate.

**Comment by olivierbon** [comment]
Resolved in support.
