### ISSUE TITLE
[3.2] Required fields on assets still ignored on save

### ISSUE THREAD

**Issue by onebrightlight** [craftcms/cms#4537]
### Description
I've set an alt field on my news images to required, but if I upload a new image or choose an existing image asset for my news entries, the entry takes a good 30-45 seconds to save and ignores the required status of my asset fields, though double clicking in to make changes and attempting to save it will produce the error I'm looking for.

### Steps to reproduce

1. Set an asset field to be required
2. Assign that field to an entry
3. Upload an asset in that field in said entry
4. Wait
5. The asset is saved and no error message given.

### Additional info

- Craft version: 3.2.1
- PHP version: 7.3.6
- Database driver & version: 10.4.6-MariaDB Homebrew
- Plugins & versions: 
  - assetusage	2.0.1
  - audit	1.0.4
  - aws-s3	1.2.3
  - beam	2.1.4
  - calendar	2.0.20
  - cp-body-classes	2.1.0
  - cp-css	2.2.0
  - cp-field-inspect	1.0.5
  - element-api	2.5.4
  - empty-coalesce	1.0.6
  - entry-relations-manager	1.0.5
  - environment-label	3.1.5
  - feed-me	4.1.1
  - image-optimize	1.5.7
  - incognito-field	1.1.1.1
  - inlin	2.1.1
  - inventory	2.0.3
  - linkit	1.1.11
  - manytomany	1.0.2.2
  - phone-number	1.2.3
  - preparse-field	v1.0.6
  - redactor	2.3.3.2
  - redactor-tweaks	2.0.2
  - redirect	1.0.23
  - related	1.0.0
  - retour	3.1.17
  - seomatic	3.2.13
  - smart-map	3.2.2.1
  - store-hours	2.1.1.1
  - tablemaker	2.0.1
  - templatecomments	1.0.2
  - twig-perversion	2.1.0
  - twigpack	1.1.7
  - typogrify	1.1.18
  - venveo-bulk-edit	1.0.5
  - video-embedder	1.1.3
  - wordsmith	3.0.5
  - workflow	1.0.2

**Comment by brandonkelly** [comment]
You need to enable the “Validate related assets” setting on your Assets field.
