### ISSUE TITLE
FR: Add ability to pass in attributes to getLink

### ISSUE THREAD

**Issue by rungta** [craftcms/cms#4543]
### Description

It would be quite handy to pass in attributes (especially classes) to the `getLink()` function on `craft\base\Element`, similar to the newly introduced `attr()` Twig function.

```twig
{# This #}
<a class="bg-red" href="{{ entry.url }}">{{ entry.title }}</a>

{# Becomes #}
{{ entry.getLink({ class: 'bg-red' }) }}
```

**Comment by brandonkelly** [comment]
`getLink()` is defined by `ElementInterface` so adding an `$attr` argument would be a breaking change for element types, so we’ll have to wait until Craft 4 to implement this, unfortunately.

**Comment by rungta** [comment]
Ah okay. Now we wait.

**Comment by fvaldes33** [comment]
@rungta - you could always create a behavior to handle that functionality.

```php
use yii\base\Behavior;
use craft\helpers\Template as TemplateHelper;
use craft\helpers\Html;

class BaseEntryBehavior extends Behavior
{
    public function getLinkEl($attrs = [])
    {
        $entry = $this->owner;

        $attrs['href'] = $entry->getUrl();
        
        return TemplateHelper::raw(Html::tag('a', $entry->title, $attrs));
    }
}
```

In twig:
```twig
{{ entry.getLinkEl({ class: 'button' }) }}
```

**Comment by rungta** [comment]
Great suggestion @fvaldes33. Thanks!

**Comment by piotrpog** [comment]
@brandonkelly 
Maybe just create a new method and call it `linkTag` or something like that?

**Comment by brandonkelly** [comment]
Actually this isn’t really needed anymore as of Craft 3.3, thanks to the [|attr](https://docs.craftcms.com/v3/dev/filters.html#attr) Twig filter.
