### ISSUE TITLE
Entries export limit 0

### ISSUE THREAD

**Issue by SayChi** [craftcms/cms#4547]
### Description
When trying to export entries with the limit set to 0 an error is thrown. I suggest simply setting the minimum for the limit to 1 instead of 0 as exporting 0 entries doesn't make sense anyway (or I just can't think of a reason why it would be useful).

### Steps to reproduce

1. Have some section (I used a channel)
2. Click export...
3. Set limit to 0
4. Click export
5. Stare at the beautiful error

### Additional info

- Craft version: 3.2.1
- PHP version: 7.1.30
- Database driver & version: MySQL 5.5.60
- Plugins & versions: 
-- Empty Coalesce | 1.0.6
-- Expanded Singles | 1.0.7
-- Imager | v2.1.10

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.
