### ISSUE TITLE
Long titles mess up the header layout on the edit Entry page

### ISSUE THREAD

**Issue by rungta** [craftcms/cms#4548]
![Messed up header on the edit Entry page](https://user-images.githubusercontent.com/663677/61132967-1bef3c80-a4da-11e9-88f6-cb1608b5512b.png)

### Steps to reproduce

1. Create an entry with 60 or more characters in its title field.

### Additional info

- Craft version: 3.2.1

**Comment by brandonkelly** [comment]
Fixed this for the next release. Here’s a few ways the header will look depending on viewport width:

<img width="1085" alt="Edit Entry page header in a wide viewport" src="https://user-images.githubusercontent.com/47792/62239050-02c70680-b389-11e9-8519-04b9eb522ce0.png">

<img width="789" alt="Edit Entry page header in a medium-wide viewport" src="https://user-images.githubusercontent.com/47792/62239121-22f6c580-b389-11e9-84b7-df978889abee.png">

<img width="355" alt="Edit Entry page header on a mobile viewport" src="https://user-images.githubusercontent.com/47792/62239143-2c802d80-b389-11e9-834b-4b4a5183491a.png">

Thanks to @sebastian-lenz for the help with title truncation!

**Comment by rungta** [comment]
Suggestion: what if we wrap the title instead of truncating it?

![Title wrap](https://user-images.githubusercontent.com/663677/62274790-34f66800-b45e-11e9-8877-ebc57391fb0f.png)

**Comment by sebastian-lenz** [comment]
I prefer the truncated variant. The title should quickly indicate which page the user is on and the full title is always visible in the title field located on all tabs. Also, css cannot truncated multiline text (as far as I am aware) so with multiline display the header could grow in height to unexpected dimensions.

**Comment by brandonkelly** [comment]
Also I like having the revision menu connected to the heading.

**Comment by ChristopherDosin** [comment]
@brandonkelly Is it possible to refer to the commit with the fix, so i can take a look how you changed it?
