### ISSUE TITLE
3.2 autosaves pollute the concept of drafts

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#4549]
The autosave feature in 3.2 has its merits, but it really messes things up for people that were already used to using drafts, e.g. in the context of a publishing workflow.

The lack of delineation between an explicitly saved draft and an autosaved draft makes it pretty much impossible to ever find an intentionally saved previous draft. †

My vote for fixing this would be differentiate between _autosaves_ and _drafts_, so in the entry dropdown you'd have:

> - Current 7/10/2001, Steve Jobs
> - **Autosaves** 
>   - 7/10/2019, Tim Kelty
> - **Drafts**
>   - Draft 1 by Elon Musk
>  - A Named Draft by Tim Kelty

Treating them differently makes a lot of sense in other ways too:

**Storage limits:**
I wouldn't ever want to limit the amount of stored drafts, but I _would_ want to limit stored autosaves (ideally, probably 1 per element, per-user).

**Visibility:**
I would think most people would expect an autosave to only ever be visible to them (the author). Drafts would depend on your workflow and should work how they do now, by user permissions.

†: one exception might be if you named your draft something useful, but in my experience I've never seen a client actually name a draft.

**Comment by timkelty** [comment]
**Other thoughts:**

---

**Data on Initial load of Entry**
We've had some discussions about what should be initially loaded when an entry has an existing autosave:

1.) The current entry (current behavior)
2.) The autosaved entry, with a notice that your autosaved data has been loaded
3.) The current entry, with a notice the "recover your data"

3 seems to be our office preference, but 2 also seems valid.

**Autosave ownership and tying an autosave to a revision**

> I would think most people would expect an autosave to only ever be visible to them (the author)

Previously I implied that autosaves should specifically belong to a user and only be visible to that author.

That comes with some confusion if two people are working on an entry:

- Casey makes edits that get autosaved
- Steph makes edits and publishes
- Casey goes back, sees her autosave and publishes it, wiping out Steph's changes

Ideally it seems like autosaves need to be tied to a specific revision, so that the user can be prompted there is an autosave, _for the current revision_.

**Comment by brandonkelly** [comment]
For now we’ve just removed the whole draft auto-creation feature. (See https://github.com/craftcms/cms/issues/4535#issuecomment-511613774 for more info.)
