### ISSUE TITLE
Query param pageTrigger breaks link for first page

### ISSUE THREAD

**Issue by lukasgeiter** [craftcms/cms#4550]
### Description

Using a `pageTrigger` with a query param format (e.g. `?page`) breaks the link for the first page when the user is on any other page. Instead of having no `page` parameter, the link points to the current page.

### Steps to reproduce

1. Set the `pageTrigger` config to `?page`
1. Implement pagination. Example:
    ```twig
    {% paginate craft.entries.limit(1) as pageInfo, entries %}
    {# display entries... #}
    {% for page, url in pageInfo.getRangeUrls(1, pageInfo.totalPages) %}
        <a href="{{ url }}">{{ page }}</a>
    {% endfor %}
    ```
1. Use the pagination to jump to page 2 (or any other page except 1)
1. Now the URL for the first page in the pagination will be `?page=2` instead of having no query parameter for the page.

### Further analysis

I think I've found the reason for this bug in [`getPageUrl` method in `Paginate`](https://github.com/craftcms/cms/blob/29e189c8da0a77a46dde8d0c5ad77685ea49932b/src/web/twig/variables/Paginate.php#L114-L146).
If it's the first page the code doesn't add the query param to the url while preserving any existing params. Both behaviors on their own are fine, however if the `page` query param exists, it is kept and results in the wrong URL.

### Additional info

- Craft version: 3.2.1
- PHP version: 7.2.19

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#e516dcb2eac535c88fea172dc148ba1084f9b0eb as 3.2.1",
  "...": "..."
}
```

Then run `composer update`.
