### ISSUE TITLE
Unknown TypeError when MailerHelper::createTransportAdapter is initializing

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#4552]
### Description

`Argument 1 passed to craft\helpers\MailerHelper::createTransportAdapter() must be of the type string, null given, called in /vendor/craftcms/cms/src/controllers/SystemSettingsController.php on line 141`

### Steps to reproduce

1. Visit `/admin/settings/email`, error is shown
2. Alternatively, `cache/flush-all` command return the same kind of error: `Exception 'TypeError' with message 'Argument 1 passed to craft\helpers\MailerHelper::createTransportAdapter() must be of the type string, null given, called in /vendor/craftcms/cms/src/helpers/App.php on line 447' in /vendor/craftcms/cms/src/helpers/MailerHelper.php:85`
3. This also happens after `craftcms/mandrill` package is removed using `composer remove craftcms/mandrill`.

### Additional info

- Craft version: Craft Pro 3.2.1
- PHP version: 7.2.20
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Control Panel CSS 2.2.0, Control Panel JS 2.2.0, Dumper 2.0.0, Element API 2.5.4, Embedded Assets 2.0.10, Expanded Singles 1.0.7, Forms 3.2.1, Imager v2.1.10, Mandrill 1.3.1, Minify 1.2.9, Neo 2.3.5, Redactor 2.3.3.2, Retcon 2.0.12, Retour 3.1.17, SEO 3.2.13, Typogrify 1.1.18

**Comment by brandonkelly** [comment]
Do you have a custom `mailer` component defined in `config/app.php`?

**Comment by romainpoirier** [comment]
No, I haven't.

**Comment by brandonkelly** [comment]
I can’t reproduce this; if I use a custom mailer plugin such as Mandrill, and then composer-remove the package, all I get on the Settings → Email page is a validation error below the Transport Type setting (“The transport type “<class name>” could not be found.”), but otherwise the page loads normally.

Can you please send your `composer.json` and `composer.lock` files, and a database backup, over to support@craftcms.com?

**Comment by romainpoirier** [comment]
I finally found that these lines were missing in my `project.yaml` file:

> email:
>   fromEmail: $SYSTEM_EMAIL_ADDRESS
>   fromName: $SENDER_NAME
>   template: $HTML_EMAIL_TEMPLATE
>   transportType: craft\mandrill\MandrillAdapter
>   transportSettings:
>     apiKey: $MANDRILL_API_KEY
>     subaccount: ''

The `Settings → Email` page had no configuration saved so it was displaying this error.

This was probably linked to my project.yaml version error ([#4546](https://github.com/craftcms/cms/issues/4546)).

**Comment by brandonkelly** [comment]
Aha! Was able to reproduce after deleting that. Just fixed this for the next release.
