### ISSUE TITLE
[3.2] FR: Add "entries per page" setting to Entry indexes

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#4555]
### Description

It would be nice if it was possible to override the default limit of 50 entries per page to a different number, on a per-source basis in the Entry index (i.e. a dropdown or number input beside the pagination UI).

### Steps to reproduce

1.
2.

### Additional info

- Craft version: 3.2
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by ul8** [comment]
I'd be happy with just a global setting, if that helps to get this done earlier. The per-source basis feature can still be added later...but the fixed limit of 50 is way too small for my usual needs.

**Comment by ryanpcmcquen** [comment]
@brandonkelly, is it configurable at all? 100 seems like a better default than 50 ...

**Comment by brandonkelly** [comment]
Agree with that. Just increased the page/batch size to 100 for the next 3.4 release.

**Comment by owldesign** [comment]
You can also try `Craft.elementIndex.settings.batchSize = 1000` to update batchSize limit. Run that javascript on the page where your element index is.
