### ISSUE TITLE
Getting assets from single entry doesn't work after updating Craft to 3.2.1

### ISSUE THREAD

**Issue by SebastiaanSchillebeeckx** [craftcms/cms#4560]
I'm building a content website in Craft CMS. I use single entries to output images, but after I updated Craft to 3.2.1, this doesn't work. Everything else is working fine.

I get this error: Twig Runtime Error – Twig\Error\RuntimeError Key "1" in object with ArrayAccess of class "craft\elements\db\AssetQuery" does not exist.

```
<div class="detail_content_photos3 row">
    <div class="detail_content_photos3_photo col-xs-12 col-md-4">
        <img src="{{ entry.videoPhoto3x3[0].url }}"/>
    </div>
    <div class="detail_content_photos3_photo col-xs-12 col-md-4">
        <img src="{{ entry.videoPhoto3x3[1].url }}"/>
    </div>
    <div class="detail_content_photos3_photo col-xs-12 col-md-4">
        <img src="{{ entry.videoPhoto3x3[2].url }}"/>
    </div>
    <div class="detail_content_photos3_photo col-xs-12 col-md-4">
        <img src="{{ entry.videoPhoto3x3[3].url }}"/>
    </div>
    <div class="detail_content_photos3_photo col-xs-12 col-md-4">
        <img src="{{ entry.videoPhoto3x3[4].url }}"/>
    </div>
    <div class="detail_content_photos3_photo col-xs-12 col-md-4">
    <img src="{{ entry.videoPhoto3x3[5].url }}"/>
    </div>
</div>
```

### Additional info

- Craft version: Craft Solo 3.2.1
- PHP version: 7.3.1
- Database driver & version: MySQL 5.7.25
- CKEditor | 1.0.0-beta.2
- Embedded Assets | 2.0.10

**Comment by brandonkelly** [comment]
We just released Craft 3.2.2 with a fix for this. Thanks for reporting!
