### ISSUE TITLE
[3.2] Export exports fields that do not belong to the entry

### ISSUE THREAD

**Issue by handplant** [craftcms/cms#4561]
### Description
Export exports fields that do not belong to the entry. 

I have a channel section where the entries have only one or two fields. Nevertheless, many more fields are exported that do not match the entry.

### Steps to reproduce
1. Click export in a section 

### Additional info

- Craft version: Craft Pro 3.2.2
- PHP version: 7.2.14
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

**Comment by brandonkelly** [comment]
Yeah this is known behavior, but we should be able to fix this in Craft 4.

**Comment by handplant** [comment]
ok. thanks for the info. unfortunately this is not usable for the customer. Would be much better to disable the function completely or make it optional.

**Comment by carlcs** [comment]
@handplant upvote this FR https://github.com/craftcms/cms/issues/4484

**Comment by brandonkelly** [comment]
Just added a new “Expanded” export type for Craft 3.4, which include only the relevant custom field values.
