### ISSUE TITLE
[3.2] Setting min blocks and max blocks leads to being unable to save entry

### ISSUE THREAD

**Issue by jowhannez** [craftcms/cms#4562]
### Description

If you edit a field to have min blocks 1 and max blocks 1 when the field has more than 1 block in it, you are not able to delete any blocks and the entry will not save.

### Steps to reproduce

1. Make a field with field type "matrix".
2. Give it a block type with at least one field.
3. Add the field to the field layout of a section.
4. Edit/create an entry with the corresponding entry type and add two blocks to your new field (with data).
5. Save the entry.
6. Go back and edit your field to have min blocks = 1 and max blocks = 1.
7. Go back to the entry.
8. Try to delete the blocks.

### Additional info

- Craft version: 3.2.0
- PHP version: 7.1.26
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
Thanks for reporting! Just fixed this for the next release.
