### ISSUE TITLE
[3.2] Matrix fields duplicated on the db

### ISSUE THREAD

**Issue by millerone** [craftcms/cms#4564]
### Description

Hello Everybody!
In my case the 3.2 version generates a lot of duplicates on the _matrixcontent_name_ tables.

Just to give you an example, I get (for the same table):

- 8 rows (with the version 3.1.34)
- 512 rows of duplicates (with the version 3.2)

And the same for all the other matrix tables.
I had to use a backup to restore the 3.1.34 version.

### Steps to reproduce

1. Pick a site with the 3.1.34 version (or lower) and create some matrix fields
2. Populate them
3. Upgrade to Craft Solo Cms 3.2
4. Check the tables

### Additional info

- Craft version: Craft Solo 3.2 and 3.2.2
- PHP version: 7.3.1 and 7.3.6
- Database driver & version: MySQL  5.7.25 and 5.7.26
- Plugins & versions:
It doesn't seems to be related to specific plugins

Thank you for your help!

**Comment by brandonkelly** [comment]
Back on 3.1.34, try running the `./craft project-config/rebuild` command, and then try re-updating to 3.2.

**Comment by millerone** [comment]
Ciao Brandon,

unfortunately it doesn't work.
The situation is this one:
-  I run `./craft project-config/rebuild`
- I update to 3.2
- after a few minutes I get hundreds of messages "Updating entry drafts and revisions" on the dashboard and the database get populated with tons of duplicates

I've the same problem with other sites too.
Is there anything else I can try to do? Thank you.

**Comment by brandonkelly** [comment]
Can you please send your `composer.json` and `composer.lock` files, and a database backup over to support@craftcms.com and reference this GitHub issue? We can help look into it from there.

**Comment by ccsantos23** [comment]
@millerone I think we were having the same issue (I noticed it from the db backup file size #4571).  But I can't rollback, there had already been content changes since my 3.1* backup.

**Comment by millerone** [comment]
@ccsantos23 Yes, I think we have the same problem. For the moment I'm still using the 3.1.34.
The 3.2.3 doesn't fix the issue.

@brandonkelly I just sent you the files. Thank you so much for the help

**Comment by brandonkelly** [comment]
There is no actual issue here. In Craft 3.2, entry drafts and revisions are stored as actual elements, whereas before they were stored as JSON blobs. Those elements will have actual duplicated Matrix block elements associated with them as well. So it’s expected that the size of `elements`, `matrixblocks` and other tables will grow in 3.2.
