### ISSUE TITLE
Aliases like baseUrl not fully resolving in Twig Templates

### ISSUE THREAD

**Issue by bmjdw** [craftcms/cms#4566]
### Description

When using an Alias in **Settings --> Sites --> Name of site --> Base URL**, the alias is not parsed when calling `{{ currentSite.baseUrl }}` from a Twig Template file.

Instead of converting the Alias, the name of the Alias itself is shown: `@siteUrl_mainSite`

### Steps to reproduce

- [ ] Go to **Settings --> Sites**
- [ ] Edit site
- [ ] Insert an alias in the **Base URL** field
- [ ] Use `{{ currentSite.baseUrl }}` in one of your .twig template files

### Additional info

- Craft version: 3.1.34
- PHP version: 7.2.19
- Database driver & version: MySQL 8.0.16
- Plugins & versions: none

**Comment by bmjdw** [comment]
After looking into alias paragraph of the [CraftCMS functions documentation](https://docs.craftcms.com/v3/dev/functions.html#alias), this code is working as expected: `{{ alias(currentSite.baseUrl) }}`

**Comment by brandonkelly** [comment]
You could also do `currentSite.getBaseUrl()`.
