### ISSUE TITLE
[3.2] FR: Re-implement way to save an entry and exit back to the sections view

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#4575]
### Description
Prior to 3.2, a user could use `cmd + s` to "save and continue editing", keeping the user in the entry view. Clicking on the actual save button would save the entry, then push the user to the sections view.

This is something that might seem small, but with the massive amount of content changes that we often have to make, being able to quickly navigate the CP UI in a consistent, flexible method is really important.

The prior functionality may have not been ideal, as it may not have been clear to the user why saving an entry in a different away took them away from a page, but for us power users, it was really beneficial.

- Craft version: 3.2.2

**Comment by brandonkelly** [comment]
Can’t please everyone, I guess. Pre-3.2, we got a lot of feedback that people wished the Save button would keep them on the Edit page.

**Comment by jsunsawyer** [comment]
@brandonkelly I hear ya. Just really stuck out as I've gotten really used to how things used to work.

Maybe an additional save hotkey combo with a modifier for us power users would be nice.

`cmd + s`: save and continue editing
`cmd + shift + s`: save and exit entry

**Comment by dwhoban** [comment]
Agree with @jsunsawyer here.  As soon as I have pushed 3.2 to a couple of customers I have gotten complaints about the change.

I feel like auto-save solves the use case @brandonkelly for the "Save" button, but the "Update Entry" button should be a different ux.

Maybe there is a way to have this as a setting?

**Comment by JeanLucEsser** [comment]
I concur and I'll add another thing related to this which is a long standing issue/enhancement (at least for me):

When searching for entries in a section and selecting an entry to edit, it would be nice to be able to go back to that search results on saving or cancel. 

When you start working with tons of content in a section, you start using search pretty much every chance you get, and sometimes you need to (mass) edit all of those search results one after the other. Loosing sight of that search every time you're done with one entry is a real pain.

Do you need me to open a separate issue for this? 
From a UX POV, finding a solution to those should be part of a single solution.

**Comment by brandonkelly** [comment]
@JeanLucEsser 99% sure there’s another issue that already covers that, but I can’t find it right now.

**Comment by brandonkelly** [comment]
Alright as of Craft 3.2.3 we are reverting to the pre-3.2 Save behavior, where clicking on the Save button (or submitting the form using the Return key on a non-textarea input) will return the user to the Entries index page. The “Save and continue editing” and “Save and add another” options are also back, and all save options besides “Save as a draft” are once again tucked under the “Save Entry” button.

<img width="390" alt="Save Entry context menu" src="https://user-images.githubusercontent.com/47792/61299176-71ef0900-a794-11e9-8ee7-89be2ce83ecf.png">

**Comment by dwhoban** [comment]
You are the best @brandonkelly  :)
