### ISSUE TITLE
Can't disable an entry for a specific site in 3.2.2 version

### ISSUE THREAD

**Issue by giacomocarra** [craftcms/cms#4577]
### Description
Hi,
in 3.2.2 version, with a multisite environment, if I disable an entry for a specific site from the tree view it works 

![screenshot_01](https://user-images.githubusercontent.com/9609677/61277057-9efde480-a7b1-11e9-9898-796046f48aaa.jpg)

 but if I enter the entry, disable for the site and click "update"  button, it doesn't save the edit.

![screenshot_02](https://user-images.githubusercontent.com/9609677/61277065-a58c5c00-a7b1-11e9-8152-ba8bedfafe6a.jpg)

is it a 3.2.2 version bug or am I do something wrong?

Thank you

### Steps to reproduce

1. pick a site with Craft Pro 3.2.2
2. create a multisite environment (for example another language)
3. create a section and enable it for both sites
4. create an entry in this section
5. disable the entry for the second site created and click "update"

### Additional info

- Craft version: Craft Pro 3.2.2
- PHP version: 7.2.16
- Database driver & version: MySQL 5.5.5
- Plugins & versions: 
Contact Form 2.2.5
Notifications 1.1.1
reCAPTCHA 1.3.0
Redactor 2.3.3.2

**Comment by hiasl** [comment]
Same the other way around: Enabling a disabled multi-site entry does not work from the details page.

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release.
