### ISSUE TITLE
Saving an entry fails if draft auto save is processing

### ISSUE THREAD

**Issue by JeanLucEsser** [craftcms/cms#4578]
### Description

Saving an entry fails sometimes (browser (chrome) pop up asking if I really want to leave the page with unsaved modification).

I think I have been able to narrow the issue to happening only when draft auto saving is still processing.

### Steps to reproduce

1. Create an Entry
2. Save it before autosaving is done doing its thing (loading animation still working)

### Additional info

- Craft version: 3.2.2 (latest)

**Comment by brandonkelly** [comment]
This won’t be an issue anymore in Craft 3.2.3, per a658ad42b76c2a367e962b8d2fdac5f886d591f4. (See https://github.com/craftcms/cms/issues/4535#issuecomment-511613774 for more info.)

**Comment by JeanLucEsser** [comment]
@brandonkelly If I read #4535 correctly, the auto saving feature will remain as it is today after saving this first draft. So there is a good chance this issue remains as it exists every time I edit an entry: clicking on update entry while auto saving is processing breaks the saving process.

It is possible I misunderstood the changes coming with 3.2.3 though.
Will report back once 3.2.3 ships.

**Comment by brandonkelly** [comment]
When you attempt to leave a draft while is being autosaved (whether via navigation, clicking Update Entry, or Command + S), it is expected behavior to receive the window unload confirmation, to avoid losing draft changes that weren’t finished being saved yet.

**Comment by JeanLucEsser** [comment]
Ok, so installed 3.2.3.

Issue remains. I get that the window unload confirmation is expected behavior (even if I wouldn't expect it as autosaving shouldn't get in the way of manually saving). But dismissing the window breaks saving. Autosaving won't work anymore and clicking update entry or cmd-s won't do anything. We're left with reloading the page.

Reproduce as follows (on Chrome, latest version) :
- go into draft mode
- make changes in a field
- click update entry or cmd-s before autosaving is finished processing
- dismiss unload confirmation window
- autosaving won't trigger anymore and update entry or cmd-s won't register

**Comment by brandonkelly** [comment]
Huh, yeah I’m able to reproduce that in Chrome as well, but not Safari. Will look into it.

**Comment by brandonkelly** [comment]
Managed to fix that for the next release, and also got Craft to stop getting in the way of a form submit even if it’s in the middle of an autosave. After a little testing it doesn’t appear to be necessary anymore, particularly after a658ad42b76c2a367e962b8d2fdac5f886d591f4.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#a8741b25226ddbcb3e8e526fd621419229b97884 as 3.2.3",
  "...": "..."
}
```

Then run `composer update`.
