### ISSUE TITLE
Simple custom slug in structure - Unable to save entries

### ISSUE THREAD

**Issue by MrGlasspoole** [craftcms/cms#4580]
### Description
I want a custom URL for a structure.
But this does not work:
![structure slug](https://user-images.githubusercontent.com/2067170/61297939-9a4f2580-a7dd-11e9-90e0-38031a2f544a.jpg)

I get a Unable to save entry (EntryRevisionsController.php at line 127).

### Additional info

- Craft version: 3.2.2
- PHP version: 7.2.19
- Database driver & version: MySQL 5.7.26
- Plugins & versions: Simple Text 2.0.2, Super Table 2.2.1

**Comment by brandonkelly** [comment]
You can’t have more than one entry with the same URI. So with a static URI format like this, you should only be able to create one entry. You will need to either clear out the Entry URI Format setting, or make it dynamic, such as including `{id}` or `{slug}`.
