### ISSUE TITLE
CCY Architects SEOmatics tab on various pages (for example - Publications) is not saving or keeping data input once it is typed in. 

### ISSUE THREAD

**Issue by CCYWeb** [craftcms/cms#4582]
### Steps to reproduce

1.
2.

### Additional info

- Craft version: 2.7.8 (Pro)
- PHP version: 7.3.5
- Database driver & version: MySQL 5.7.19-log
- Plugins & versions: 
    - Contact Form 1.9.1
    - Control Panel Nav 1.7.7
    - Menus 1.0.0
    - Retour 1.0.22
    - SEOmatic 1.1.56
    - Spam Guard 0.6.0

**Comment by brandonkelly** [comment]
Unfortunately that’s not something we can help you with, as SEOmatic is a third party plugin. It [appears](https://github.com/nystudio107/seomatic) that the 1.x version of SEOmatic is no longer supported, but you may be able to find someone to help out with it.
