### ISSUE TITLE
[3.1 versions w/token] question: should Share button appear on Current?

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#4583]
### Description
In the midst of finalizing a plugin involved with shares, I noticed that no token is being sent on the link which the Share button opens on a fresh tab-or-window.

The consequence is that sharing from Current will not show any edits you're making on Currrent, which would seem to be the only reason to share that. So would anyone use Share on Current?

In view also of what you're doing on 3.2.3, which hopefully removes the Share as well as Preview buttons on Current (for a much improved, clearer workflow), should the Share button also not appear on Current editing, for 3.1.x forward?

n.b. previews do work on Current, and with or without that plugin, so all good for previews.
n.b. also: I tested the Share button for this issue as far back as 3.1.23, so it's nothing new

### Steps to reproduce

1. Edit Current of an Entry
2. make a change, typed text etc.
3. click Share
4. get the original Current, same as website, changes not shown

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
When viewing the Current entry, and if the entry is live, the Share button is just meant as a way to share the live version of the entry. Which is why there is no `token` or `x-craft-preview` params.

**Comment by narration-sd** [comment]
Well, this is probably why I was previously confused about what Share meant.

If nobody complains that edits of Current don't show on its share, then this must be ok, your call, and everybody knows it by now.

I just was testing 3.2.3, and the same result of Share on Current will occur, no edits, and this remains true with Live Vue, so again, following your call.  My nerves will recover 😄
