### ISSUE TITLE
Expected Behavior when Duplicating Entries in a Multisite with Relationship Field set to "Manage relations on a per-site basis"

### ISSUE THREAD

**Issue by kylecotter** [craftcms/cms#4587]
### Description

Hi! We had a question regarding expected functionality in the following scenario:

1. Create an entry in a Section that is set to propagate entries across all sites.
2. In the entry, fill in an asset field that is set to “Manage relations on a per-site basis”
3. Save entry
4. Entry propagates across all sites
5. Edit the entry for each additional site and add a specific asset per site and save
6. Back on the entry listing page for the primary site, duplicate an entry
7. Entry is duplicated and propagated across all languages
8. The primary site duplicated entry contains the linked asset from the original entry
9. The duplicated entry for the other sites have a blank asset field…as opposed to their original entry counterparts

We've had two separate clients expect the latter when duplicating an entry.

We're wondering if the duplicate entry having a blank relation on the other sites is expected behavior or maybe something that has been changed in Craft 3.2.

Both of these projects are on Craft 3.1.

Thanks!

**Comment by brandonkelly** [comment]
It would be expected that each of the site-specific relations get duplicated along with the rest of the site content. Some of that code has changed in Craft 3.2 so it’s possible that it works as expected now. Give it a shot and let me know if this is something we should be looking into.
