### ISSUE TITLE
Server becomes unresponsive due to GIF transforms performed in control panel

### ISSUE THREAD

**Issue by aaronbushnell** [craftcms/cms#4588]
### Description
The `transformGifs` config has helped us a lot to avoid a large GIF getting transformed on the front-end on the site and exhausting server resources. But it still seems like GIFs are still getting transformed even after the changes added in #3110.

On one particularly GIF-heavy site—if I visit the "Assets" area a list view of 5-10 GIFs ends up locking down the site until all resources are exhausted and it crashes.

If I add a
```php
return "";
```
at the beginning of [the `getThumbPath()` function](https://github.com/craftcms/cms/blob/develop/src/services/Assets.php#L671) it doesn't seem to be an issue. So I wonder if GIFs are still getting transformed in some way that's eating up server resources?

### Additional info

- PHP Version: 7.0.33
- Database: MySQL 5.7.26
- Craft Version: Craft Pro 3.2.3
- Image Driver: Imagick 3.4.0RC6 (ImageMagick 6.8.9-9)

**Comment by andris-sevcenko** [comment]
Well, this is a fun trip down the rabbit hole. By any chance, do you also have set the `optimizeImageFilesize` setting to `false` in your Craft config?

**Comment by andris-sevcenko** [comment]
Never mind, that was an unrelated issue. I found your bug, sir.

**Comment by aaronbushnell** [comment]
Ah man, thanks so much @andris-sevcenko! I applied this change to the site and it seems like it's no longer an issue!

**Comment by andris-sevcenko** [comment]
You're welcome! Now to fix the other bug I found... :)

**Comment by aaronbushnell** [comment]
Hey @andris-sevcenko — you might have seen this already but it looks like Brandon's change here undid the fix that corrected the slow GIF transformation. After updating to the latest version it looks like the slowness is re-occurring on our site. Not sure if there's another fix that could be implemented here?

**Comment by andris-sevcenko** [comment]
@aaronbushnell yeah we have to release a new version of Imagine on our fork so it doesn't break in some other circumstances. Should be out this week definitely, I'll keep you posted!

**Comment by aaronbushnell** [comment]
Totally okay! Appreciate the help and let me know if I can test anything for ya!

**Comment by brandonkelly** [comment]
We just released Craft 3.2.6 with the fix for this.

**Comment by aaronbushnell** [comment]
You all are awesome—thanks a ton!
