### ISSUE TITLE
Singles shouldn't be deletable

### ISSUE THREAD

**Issue by rynpsc** [craftcms/cms#4590]
### Description

Singles are now deletable from the edit entry page. If the single in question was the homepage and you then delete the section, it is not possible to create a new homepage single and are meet with the "Site already has a homepage" message.

Note: option to delete isn't on the entry element index page.

### Steps to reproduce

1. Create a new single section
2. Edit singles entry and click on the "Save Entry" dropdown
3. Proceed to click "Delete entry"

### Additional info

- Craft version: Craft Solo 3.2.3
- PHP version: 7.3.4
- Database driver & version: MySQL 5.7.25

**Comment by brandonkelly** [comment]
You’re absolutely right! Just fixed this for the next release.
