### ISSUE TITLE
FR: Site specific email settings

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#4594]
### Description

Title says it all. With support for multiple domains, it doesn't make a lot of sense to have emails come from the same sender for certain types of emails. For example, if I do a password reset from siteb.com, I would get an email from the sitea.com system email address, which is quite confusing/alarming to siteb.com users.

### Additional info

- Craft version: 3.1.34
- PHP version: N/A
- Database driver & version: N/A
- Plugins & versions: N/A

**Comment by Mosnar** [comment]
For others trying to do this, it's actually really easy to accomplish; however, I still think it's worth leaving this issue open, as it's not very intuitive for those without a lot of experience with Craft.

In our `config/app.php` we just need to override the mailer component of Craft. So in the 'components' key of the app.php file (create one if it doesn't exist), you just need something like this (for Mailgun):

```php
'mailer' => function() {
            // Get the stored email settings
            $settings = craft\helpers\App::mailSettings();

            // Override the transport adapter class
            $settings->transportType = craft\mailgun\MailgunAdapter::class;

            // Override the transport adapter settings
            if (Craft::$app->sites->getCurrentSite()->handle === 'site1') {
                $settings->transportSettings = [
                    'domain' => getenv('MG_DOMAIN_SITE1'),
                    'apiKey' => getenv('MG_API_KEY_SITE1'),
                ];
                $settings->fromEmail = getenv('SITE1_FROM_EMAIL');
                $settings->fromName = getenv('SITE1_FROM_NAME');
            } else {
                $settings->transportSettings = [
                    'domain' => getenv('MG_DOMAIN_SITE2'),
                    'apiKey' => getenv('MG_API_KEY_SITE2'),
                ];
                $settings->fromEmail = getenv('SITE2_FROM_EMAIL');
                $settings->fromName = getenv('SITE2_FROM_NAME');
            }

            // Create a Mailer component config with these settings
            $config = craft\helpers\App::mailerConfig($settings);

            // Instantiate and return it
            return Craft::createObject($config);
        },
```

**Comment by putyourlightson** [comment]
The UI for allowing a full range of site specific email sending settings in the control panel might be tricky. What might be more feasible is to add site specific email addresses, while maintaining a single set of sending settings. I've done something similar in the Campaign plugin and have mocked up what it might look like in Craft.

<img width="840" alt="Screenshot 2019-07-17 at 20 06 00" src="https://user-images.githubusercontent.com/2318222/61399539-a2d35900-a8ce-11e9-9b39-95af04bdaf64.png">

If this is a feature that the P&T team would like to add then I'd be happy to submit a pull request.

**Comment by brandonkelly** [comment]
Yeah maybe. I worry that it’s going to be annoying for sites where no site-specific values are needed though.

**Comment by historicagency** [comment]
Could just be left blank for default?

**Comment by theskyfloor** [comment]
Just fall back to the default if the settings are blank?

**Comment by putyourlightson** [comment]
@theskyfloor Where is the default set?

**Comment by theskyfloor** [comment]
"Site A" in which the handle is usually automatically set to default. Much like this:

"Leave blank if settings should match default site"

<img width="750" alt="Screen Shot 2019-07-18 at 12 11 43 PM" src="https://user-images.githubusercontent.com/8887839/61477605-48311000-a955-11e9-9bf0-53fc648d4553.png">

**Comment by putyourlightson** [comment]
So the email settings would be required for the primary site (the first row in the table)?

**Comment by theskyfloor** [comment]
Default site settings (first row) would follow the same exact convention as now. Email would be filled in with the administrator email, from name with the site name, template blank:

<img width="519" alt="Screen Shot 2019-07-18 at 12 44 02 PM" src="https://user-images.githubusercontent.com/8887839/61479608-cc859200-a959-11e9-83af-f7a40a6822f2.png">

**Comment by theskyfloor** [comment]
@putyourlightson totally! I was just posting that as example of what Craft already does by default! I think your proposal is brilliant and spot on... the first row would just act as the current 3 fields do just in a different format... new sites default to the Primary Site unless otherwise defined :)

**Comment by putyourlightson** [comment]
Got it, so we _are_ on the same page!!

**Comment by brandonkelly** [comment]
That wouldn’t work for Reply To, which is optional. Does a blank value mean to not use a Reply To field, or to use the primary site’s Reply To value?

**Comment by brandonkelly** [comment]
That wouldn’t work for optional settings, like Email Template, where it wouldn’t be clear whether a blank value meant “no email template for this site” or “use the primary site’s template”.

**Comment by putyourlightson** [comment]
That's true. So then let's scrap the idea of falling back to the primary site's values for empty fields and make the required fields required for each site. Perhaps when a new site is created it could automatically inherit the primary site's values to avoid having to manually re-enter them.

An alternative UI could be to move the 3 email setting fields into the site edit page. The question then becomes whether it is intuitive to find email related settings in the site settings.

<img width="553" alt="Screenshot 2019-07-19 at 17 38 41" src="https://user-images.githubusercontent.com/2318222/61547651-177fd200-aa4c-11e9-9aae-1d02becd7555.png">

**Comment by theskyfloor** [comment]
Same thoughts from the peanut gallery! No matter what supporting multiple domains for email seems like an essential part of offering multisite. Site settings is a pretty logical place for site specific config stuff IMO.

**Comment by hhhc** [comment]
I really would like to see this implemented as this would just complete the multi-site offering of CraftCMS.

**Comment by AndrewMac** [comment]
I would just like to add the biggest vote of support I possibly can for getting this sorted out, please. It's a source of confusion and sometimes mistrust for site users, who are these days getting more and more careful about emails they don't recognise.

I can see that it seems to be getting pushed back from milestone to milestone, and I can see that in those milestones it competes with a lot of other great features that we're all hoping for, but this is a service to end users, and they're what sites are all about :-)

Cheers, Andrew
