### ISSUE TITLE
Newly added table cells with email/url fields don't include necessary classes

### ISSUE THREAD

**Issue by chasegiunta** [craftcms/cms#4595]
### Description
After a little dissecting of the screenshot issue below (URL field), looks like newly added table cells that contain email/url fields don't include the necessary `textual` class, causing this extra padding. Initial table cells rendered via twig show correctly.

![image](https://user-images.githubusercontent.com/1377169/61397245-15bcdf80-a88f-11e9-8713-cb4f91270cc5.png)

### Steps to reproduce

1. Create table field with URL/Email field type column
2. Ensure there are no minimum rows.
3. Add new row.

### Additional info

- Craft version: 3.2.3

**Comment by brandonkelly** [comment]
Thanks for reporting! Just released Craft 3.2.4.1 with a fix for this.
