### ISSUE TITLE
[3.2.4] Can't share disabled or pending entries

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#4596]
### Description

When trying to share (not preview) a source entry that is not live, there is an 'unknown error'.

Call to `/index.php?p=admin/actions//preview/create-token` returns with `403 forbidden`

### Steps to reproduce

1. Open the source version of an entry
2. make it 'not live' (not enabled, future Post Date...)
3. Click `Share`

Thanks.

### Additional info

- Craft version: 3.2.4
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting! Just released Craft 3.2.4.1 with a fix for this.
