### ISSUE TITLE
Unknown error when a plugin license environment variable is an empty string

### ISSUE THREAD

**Issue by rungta** [craftcms/cms#4604]
### Description

When I make use of environment variables to keep plugin license keys out of the project config, I’m getting an “Unknown Error” if the environment variable is set to an empty string (as intended in the dev & staging environments, where Craft is running in trial mode). E.g.

![Screen Shot 2019-07-18 at 4 11 22 PM](https://user-images.githubusercontent.com/663677/61451531-3fe9cc80-a977-11e9-811d-c8484b289b01.png)

Related issue: https://github.com/pixelandtonic/craftnet/issues/162

### Steps to reproduce

1. Install a paid plugin (e.g. Craft Dynamic Fields)
2. Add an environment variable to its license field (e.g. `$LICENSE_DYNAMIC_FIELDS`)
3. Set the value of the environment variable to an empty string in your `.env` (e.g.  `LICENSE_DYNAMIC_FIELDS=""`)

### Additional info

- Craft version: 3.2.2
- PHP version: 7.1

**Comment by brandonkelly** [comment]
I’m not able to reproduce this; I just get a “Your license key is invalid.” error below the license input, which is expected. That happens whether I’ve set the environment variable to an empty string or if I just haven’t even set it yet.

Try clearing out your `storage/logs/` folder, then reproduce the error, then search `storage/logs/web.log` for `[error]`. Please post the full error details + stack trace. That should help explain what’s going on.

> (as intended in the dev & staging environments, where Craft is running in trial mode)

You shouldn’t have any issues using the same plugin license keys across all of your environments, as long as the `config/license.key` file has the same Craft license key that the plugin licenses are associated with.

**Comment by rungta** [comment]
Here’s the stack trace:
```
2019-07-19 23:22:48 [-][1][-][error][craft\errors\InvalidLicenseKeyException] craft\errors\InvalidLicenseKeyException: The license key “” is invalid. in .../vendor/craftcms/cms/src/services/Plugins.php:1172
Stack trace:
#0 .../vendor/craftcms/cms/src/services/Plugins.php(1113): craft\services\Plugins->normalizePluginLicenseKey('')
#1 .../vendor/craftcms/cms/src/services/Api.php(489): craft\services\Plugins->getPluginLicenseKey('craft-dynamic-f...')
#2 .../vendor/craftcms/cms/src/services/Api.php(339): craft\services\Api->headers()
#3 .../vendor/craftcms/cms/src/services/Api.php(70): craft\services\Api->request('GET', 'cms-licenses', Array)
#4 .../vendor/craftcms/cms/src/controllers/AppController.php(431): craft\services\Api->getLicenseInfo(Array)
#5 .../vendor/craftcms/cms/src/controllers/AppController.php(349): craft\controllers\AppController->_pluginLicenseInfo()
#6 [internal function]: craft\controllers\AppController->actionGetPluginLicenseInfo()
#7 .../vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 .../vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#9 .../vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('get-plugin-lice...', Array)
#10 .../vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('get-plugin-lice...', Array)
#11 .../vendor/craftcms/cms/src/web/Application.php(298): yii\base\Module->runAction('app/get-plugin-...', Array)
#12 .../vendor/craftcms/cms/src/web/Application.php(565): craft\web\Application->runAction('app/get-plugin-...', Array)
#13 .../vendor/craftcms/cms/src/web/Application.php(277): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#14 .../vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#15 .../web/index.php(21): yii\base\Application->run()
#16 {main}
```

**Comment by brandonkelly** [comment]
Thanks, able to reproduce this now. I think maybe yesterday I accidentally added `$TEST_LICENSE_KEY=""` to `.env`, instead of `TEST_LICENSE_KEY=""`.

Just fixed for the next release. But again, you shouldn't need to set license key environment variables to empty strings in the first place :)
