### ISSUE TITLE
[3.2] Upload error after updating to 3.2.4.1

### ISSUE THREAD

**Issue by zizther** [craftcms/cms#4605]
### Description

After updating Craft from 3.2.3 to 3.2.4.1 I started getting an error message when trying to upload assets.
I have tried downgrading, this made no difference, even though it was working fine on 3.2.3 before.

Error message `Upload failed. The error message was: “Asset is missing its folder ID”`

I have tried the same downgraded site on another environment, but still have the same issue as above.

### Steps to reproduce

1. Update Craft from 3.2.3 to 3.2.4.1
2. Upload an asset

### Additional info

- Craft version: 3.2.4.1
- PHP version: 7.2.10
- Database driver & version: 5.7.23
- Plugins & versions:

**Comment by martinleveille** [comment]
Maybe this can be related to https://github.com/nystudio107/craft-retour/issues/68

**Comment by zizther** [comment]
This was an issue with Retour 3.1.20, not Craf
