### ISSUE TITLE
Asset is missing its folder ID

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#4606]
### Description

Since very recent updates, now under `Craft Pro 3.2.4.1`, I can't upload new assets in pre-existing volumes folders, and also in brand new created folders.

Each times I tried to upload an asset, from back-end or front-end, I got this error: `Asset is missing its folder ID`.

I have made no changes to my assets settings which were working perfectly fine before. I checked the `craft_volumes` and `craft_volumesfolders` and everything seems fine. I can also see references to my volumes in the `project.yaml` file.

Despite this, I cam move files from volumes folders to another without getting this error. So it makes no sense: these `folder ID` seems correctly stored somewhere.

I tried to install a brand new `Craft Pro 3.2.4.1` and I can't reproduce the error. So I have sent my `composer.json`, `composer.lock`, `project.yaml` files, and a database backup to support@craftcms.com for further investigation.

### Steps to reproduce

1. Try to load an a file from the CP or from the front-end
2. Get the error `Asset is missing its folder ID`

### Additional info

- Craft version: Craft Pro 3.2.4.1
- PHP version: 7.1.8
- Database driver & version: MySQL 5.6.35
- Plugins & versions: Control Panel CSS 2.2.0, Control Panel JS 2.2.0, Dumper 2.0.0, Element API 2.5.4, Embedded Assets 2.0.10, Expanded Singles 1.0.7, Forms 3.2.1, Imager v2.1.10, Mandrill 1.3.1, Minify 1.2.9, Neo 2.3.5, Redactor 2.3.3.2, Retcon 2.0.12, Retour 3.1.17, SEO 3.2.13, Typogrify 1.1.18

**Comment by martinleveille** [comment]
Maybe this is related to https://github.com/nystudio107/craft-retour/issues/68

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-retour/commit/8600c31157cc20b38cfe04f400f4ac770e06a978

**Comment by olivierbon** [comment]
Fixed by updating the Retour plugin.

**Comment by khalwat** [comment]
I should note that although I fixed this in Retour, I'm not entirely sure it's a bug in Retour. Or at least the way it worked in the past wasn't an issue on Craft 3.0 or 3.1, so I note this in case P&T runs into it again.

Inside of the callback for `Elements::EVENT_BEFORE_SAVE_ELEMENT` I was calling `$element->getUrl()` which apparently triggers Craft to throw the error mentioned here:

https://github.com/nystudio107/craft-retour/blob/3.1.20/src/Retour.php#L306

I changed it to just $element->uri` and all is well. I didn't trace through the code extensively to see where or why calling `$element->getUrl()` here was problematic when it comes to uploading an asset.

**Comment by khalwat** [comment]
Stack trace for completeness:

```
Stack trace:
#0 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/helpers/Assets.php(93): craft\elements\Asset->getFolder()
#1 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/services/Assets.php(579): craft\helpers\Assets::generateUrl(Object(craft\volumes\Local), Object(craft\elements\Asset))
#2 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/elements/Asset.php(773): craft\services\Assets->getAssetUrl(Object(craft\elements\Asset), NULL)
#3 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/Component.php(139): craft\elements\Asset->getUrl()
#4 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/base/Element.php(879): yii\base\Component->__get('url')
#5 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/elements/Asset.php(582): craft\base\Element->__get('url')
#6 /home/vagrant/webdev/craft/craft-retour/src/Retour.php(306): craft\elements\Asset->__get('url')
#7 [internal function]: nystudio107\retour\Retour->nystudio107\retour\{closure}(Object(craft\events\ElementEvent))
#8 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\ElementEvent))
#9 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\services\\...', 'beforeSaveEleme...', Object(craft\events\ElementEvent))
#10 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/services/Elements.php(502): yii\base\Component->trigger('beforeSaveEleme...', Object(craft\events\ElementEvent))
#11 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/controllers/AssetsController.php(118): craft\services\Elements->saveElement(Object(craft\elements\Asset))
#12 [internal function]: craft\controllers\AssetsController->actionSaveAsset()
#13 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#15 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('save-asset', Array)
#16 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-asset', Array)
#17 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/Application.php(298): yii\base\Module->runAction('assets/save-ass...', Array)
#18 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/Application.php(565): craft\web\Application->runAction('assets/save-ass...', Array)
#19 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/Application.php(277): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#20 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /home/vagrant/sites/craft3/web/index.php(24): yii\base\Application->run()
#22 {main}

```

**Comment by khalwat** [comment]
Nope, never mind -- this is my fault. I shuffled the code around, so I was checking `$element->getUrl()` before I was checking `$event->isNew`
