### ISSUE TITLE
Browser "Leave site?" message appears when moving away from recently saved entry

### ISSUE THREAD

**Issue by jamiewade** [craftcms/cms#4608]
### Description

After you save an entry and wait for the `Updating search indexes` task to complete, then click a Craft link to move away from the entry you have just saved, you receive this browser notification (Chrome) :

![screenshot](https://user-images.githubusercontent.com/6672331/61471436-aa503c00-a97a-11e9-8213-832c71631a1f.jpg)

You get this message even though all tasks have completed, and there is no un-saved changes to the entry.

### Additional info

- Craft version: 3.2.4.1
- PHP version: 7.2.17
- Database driver & version: MySQL 5.7.26
- Browser version: Chrome 75.0.3770.142 (Official Build) (64-bit)

**Comment by jamiewade** [comment]
As an addition, this also happens if you load an entry in Craft, then hit refresh once everything has loaded.

**Comment by brandonkelly** [comment]
Do you have any plugins installed?

**Comment by jamiewade** [comment]
Yes we do have a few plugins installed. Sorry, I didn't think that could be the issue. I'll try this out on a clean install and will get back to you.

**Comment by jamiewade** [comment]
Sorry Brandon, turns out it was Neo causing this. I'll take this issue elsewhere. Have a good day!
