### ISSUE TITLE
3.2+ Asset thumbs not loading in the admin panel

### ISSUE THREAD

**Issue by kellyannmcnamara01** [craftcms/cms#4609]
### Description
Asset thumbs are not loading within the admin panel. When edited the image displays properly, but still not the thumb.

_(I know this was an issue with 3.0.3 when it first was released too)._

### Steps to reproduce

There are two ways to view this error:
1. Go to an entry with an asset picker and the user will see the default-thumb.svg instead of a thumb of the actual image.
2. Go to the assets section of the admin and you will see the default-thumb.svg instead of the thumbs.

### Additional info

- Craft version: 3.2.4.1
- PHP version: 7.2.10

_Screenshots Attached_

![Screen Shot 2019-07-18 at 10 40 26 AM](https://user-images.githubusercontent.com/24300129/61480200-6b62bc00-a963-11e9-8662-670f47c8bafb.png)

![Screen Shot 2019-07-18 at 10 40 30 AM](https://user-images.githubusercontent.com/24300129/61480215-74ec2400-a963-11e9-8232-8b1c6f75f1be.png)

<img width="732" alt="Screen Shot 2019-07-18 at 10 40 36 AM" src="https://user-images.githubusercontent.com/24300129/61480224-7b7a9b80-a963-11e9-9a25-dbf527d983ff.png">

![Screen Shot 2019-07-18 at 10 40 16 AM](https://user-images.githubusercontent.com/24300129/61480235-846b6d00-a963-11e9-8f42-12f491c87cf9.png)

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Are you using any plugins?

**Comment by brandonkelly** [comment]
Turns out this was due to 319e4b121b0a8fedaa503c94c397c8c25b0c8281, which was actually committed _after_ 3.2.4.1, which is why I couldn’t reproduce. Just released 3.2.5.1 with a fix.

**Comment by kellyannmcnamara01** [comment]
Thank you, much appreciated.
