### ISSUE TITLE
Entry: "Save and add another" results in 404 Entry not found

### ISSUE THREAD

**Issue by swthate** [craftcms/cms#4614]
### Description
I was excited to see in one of the recent changelogs that our dear "Save and add another" has made a comeback. However, after clicking it you receive a prompt asking if you want to "leave the page." This prompt also warns you that any changes you made may not be saved. Rather than the entry being saved and you being redirected to a new entry form page you instead are greeted with:
```
HTTP 404 – Not Found – yii\web\NotFoundHttpException

Entry not found
```
If you save the entry normally and then select "save and add another" it behaves as expected. Also, didn't a recent changelog note that you should be redirected back to the entries index after saving an entry now? (update: When you save the entry for the first time it stays on that entry edit page, but when you hit save a second time it then brings you to the index -- is that expected behavior?)

### Steps to reproduce

1. Update to 3.2.4.1
2. Begin to add a new entry
3. Click "Save and add another"
4. Click "Leave" at the prompt

### Additional info

- Craft version: 3.2.4.1
- PHP version: 7.2
- Database driver & version: MySQL 5.7.23
- Plugins & versions: none

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by marionnewlevant** [comment]
I get 'unknown error', and then it saves, and then the new entry page. But I don't think I should get the 'Leave site? Changes you made may not be saved' alert at all. Craft 3.2.7
@brandonkelly

**Comment by brandonkelly** [comment]
@marionnewlevant Thanks for pointing that out. I’m seeing that if you try to save the draft right in the middle of the form getting autosaved. Just fixed that for the next release.
