### ISSUE TITLE
Bug: "Updating" an entry on a multi-site setup results in "Page Not Found"

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#4615]
### Description
It looks like the site handle is not being automatically appended to the CP url after a **draft** entry is updated, i.e. ?site=siteHandle

### Steps to reproduce

1. Edit an existing entry
2. Save as a draft
3. Click "Update Entry"
4. URL redirects to ../entries/section-name/entry-id instead of ../entries/section-name/entry-id?site=siteHandle resulting in the error "Page Not Found / Entry not Found"

This also happens when selecting live preview followed by "updating" the entry as this results in a draft being created.

Where should the user be redirected to? Back to the entries section or the current version of the entry (as a result of updating the draft to replace the current version).

### Additional info

- Craft version: 3.2.4.1

**Comment by richhayler** [comment]
Looks related to #4574

**Comment by jordikroon** [comment]
We're having the same issues. For us it doesn't happen all the time. More about half the times we save an entry.

I've captured the 2 different responses. Hope it helps reproducing/solving the issue.
https://gist.github.com/jordikroon/bb4ae1db5ad7270540f5ebffbbf67953

**Comment by brandonkelly** [comment]
Thanks for reporting that, just fixed for the next release.
