### ISSUE TITLE
Feature request: allow users to edit images but not delete

### ISSUE THREAD

**Issue by bartrylant** [craftcms/cms#4618]
With the new "Edit images" permission, you can choose to allow users to edit images or not. However, if you want non-admin users to be able to edit images, you still have to allow them to delete files and folders. It would be nice if there was an option to allow users to edit images (e.g. to set the focal point) but not allow them to delete images.

**Comment by andris-sevcenko** [comment]
Seems like an oversight. The Edit images permission was intended to be blanket permission for that.

To clarify - you're referring to the element action missing if the required save and delete permissions are not present, right?

**Comment by bartrylant** [comment]
Indeed, when you don't tick "save and delete" but only "edit images", there is no "edit" button in the top right corner when you double click a thumbnail.

**Comment by andris-sevcenko** [comment]
Yeah, that's an oversight.
