### ISSUE TITLE
[3.2] Save Entry button placement

### ISSUE THREAD

**Issue by rynpsc** [craftcms/cms#4622]
### Description

Should the "Save Entry" button be moved to be the rightmost button and proceed the "Save as Draft" button for consistency across the Control Panel? I think most users (new and current) would expect it to be in the top right. Especially when that's where it appears when creating a new entry, it then gets shifted once created.

### Additional info

- Craft version: 3.2.4

**Comment by brandonkelly** [comment]
Going point, done for the next release.
