### ISSUE TITLE
postDate is not taking into account TimeZone for entries added through migration

### ISSUE THREAD

**Issue by timbertens** [craftcms/cms#4627]
### Description
When creating a content migration on the source system (using migration assistent plugin) the postDate for the entry in migration contains the correct postDate and timeZone.  

When executing the migration on the target system the content's postDate is imported as is, not taking into account the timeZone set in the JSON. 

```php
private $json = <<<'JSON'
{"content":{"entries":[{"slug":"kab-22-test","section":"nieuwsItems","sites":{"default":{"slug":"kab-22-test","section":"nieuwsItems","enabled":"1","site":"default","enabledForSite":"1","postDate":{"date":"2019-07-21 17:14:00.000000","timezone_type":3,"timezone":"Europe/Brussels"},"expiryDate":null,"title":"KAB-22 Test","entryType":"nieuws","uid":"c0874846-27ef-442e-8e89-651d730b9aec","fields":{"nieuwsIcoon":[],"introTekst":"TEst","contentBuilder":[]}},"kbcAgentFrans":{"slug":"kab-22-test","section":"nieuwsItems","enabled":"1","site":"kbcAgentFrans","enabledForSite":"1","postDate":{"date":"2019-07-21 17:14:00.000000","timezone_type":3,"timezone":"Europe/Brussels"},"expiryDate":null,"title":"KAB-22 Test","entryType":"nieuws","uid":"c0874846-27ef-442e-8e89-651d730b9aec","fields":{"nieuwsIcoon":[],"introTekst":"TEst","contentBuilder":[]}},"kbcAgentEngels":{"slug":"kab-22-test","section":"nieuwsItems","enabled":"1","site":"kbcAgentEngels","enabledForSite":"1","postDate":{"date":"2019-07-21 17:14:00.000000","timezone_type":3,"timezone":"Europe/Brussels"},"expiryDate":null,"title":"KAB-22 Test","entryType":"nieuws","uid":"c0874846-27ef-442e-8e89-651d730b9aec","fields":{"nieuwsIcoon":[],"introTekst":"TEst","contentBuilder":[]}}}}]}}
JSON;
``` 

Both source and destination system have timeZone 'Europe/Brussels' 

It is expected that the migration would result (in this example) in a postDate of 2019-07-21 15:14:00.000000 (as it has to take into account the +2 hours from the timeZone 'Europe/Brussels') 

However the database on the destination system contains 2019-07-21 17:14:00.000000 as value

When creating a manual entry in the CMS on the destination system at the same moment (so 17:14 local time), the expected 2019-07-21 15:14:00.000000 is found as postDate in the database. 

The problem with having a postDate in the future (as this imported entry results in a localised time being 19:14) of course is that the entry does not show up immediately after the import.  

#### Application Info
PHP version	7.3.1
OS version	Linux 4.15.0-45-generic
Database driver & version	MySQL 5.7.25
Image driver & version	GD 7.3.1
Craft edition & version	Craft Pro 3.2.5.1
Yii version	2.0.21
Twig version	2.11.3
Guzzle version	6.3.3
Imagine version	0.7-dev

#### Plugins
Activity Log	1.0.1
CodeMirror	1.0.1
CP Field Inspect	1.0.6
Field Manager	2.1.0
GeoField	1.0.0
Matrix Toolbar	1.0.6
Migration Assistant	3.1.2
Redactor	2.3.3.2
SEOMate	1.0.7
Stamp	2.1.0
Table Maker	2.0.1
Two-Factor Authentication	2.1.2
Typed link field	1.0.19
Wheel Form	2.2.1

**Comment by brandonkelly** [comment]
This is a bug with Migration Assistant, which is disregarding the timezone when populating the post/expiry dates on entry import. I’ve just submitted an issue on the Migration Assistant repo about it: (dgrigg/craft-migration-assistant#10.

**Comment by dgrigg** [comment]
@timbertens this has been fix in the latest version of Migration Assistant, 3.1.3
