### ISSUE TITLE
Disabled entries appearing when they should not

### ISSUE THREAD

**Issue by tomkiss** [craftcms/cms#4629]
Hello,

I'm noticing a new issue are an upgrade (apologies I'm not sure from which version but it was a good two months of updates, past the recent breakpoint and now am on 3.2.5.1).

I have two sites in a multi-site setup. One EN-GB one EN-US.
I have two channels, A and B. Channel B is embedded into channel A via an entries field type.
Some of channel B's entries are enabled on EN-GB, some are disabled and likewise for EN-US.

When outputting channel A, I loop through the entries field type and display all the associated entries from channel B.
Previously this worked a charm, any entries in channel B that are disabled in EN-US do not appear when viewing the EN-US site, and visa-versa for EN-GB.

However, after updating, I'm now seeing all embedded entries from the field type, irrespective of which site they're enabled for.
Note that the CP always displays the correct status icon next to each entry when viewing items and switching sites.

I've tested this on a fresh install of Craft 3, creating a barebones two channels, addings a single entries fieldtype to one and then including a template for the entry as:
```
{%- for e in entry.channelb.all %}
{{ e.title }}
{%- endfor %}
```
Where the entries fieldtype is called `channelb` and contains two entries, one disabled one not. The given result in the template displays entries disabled.
But again the CP displays the correct result, showing which entries are disabled in either site.

![image](https://user-images.githubusercontent.com/183310/61638341-1ab7cf80-ac91-11e9-85a2-6a138a872109.png)

I can't see this having been talked about elsewhere so hopefully this is a new issue. Has there been a change with recent craft updates, do I need to update my template code or is this a bug?

**Comment by brandonkelly** [comment]
This is expected behavior in 3.2, per #3584. Basically now relational fields will generate multi-site element queries by default, and pull in related elements from whichever site it can find them in where enabled (preferring the entry’s site if possible, of course).

If you want to lock it down to only load entries from the same site as the entry, you can do this:

```twig
{% for e in entry.channelb.siteId(entry.siteId).all() %}
```

**Comment by tomkiss** [comment]
Oh brilliant, thanks for the explanation Brandon.

I had spent 30 minutes trying to find information on what this could be but clearly ran the wrong searches, apologies for the dupe.
