### ISSUE TITLE
The right place to aks questions/community?

### ISSUE THREAD

**Issue by MrGlasspoole** [craftcms/cms#4630]
Is there another place to ask for help/tips than StackExchange?

I don't like StackExchange. Writing a question is a pain (markup) and if you have a simple question you can't ask it because it does not meet the requirements.

People judge if your question is stupid (if YOU ARE stupid).

If you don't get an answer right away you never get one...

I like normal forums (phpBB/vBulletin) and that was what was so great about EE back then.

I asked a question 7 days ago on StackExchange. No answer and i can't proceed because i can't figure it out on my own.

**Comment by Mosnar** [comment]
There's a very friendly/active community on discord: https://craftcms.com/blog/discord

**Comment by brandonkelly** [comment]
Yep, +1 for Discord. And if you’re really stuck, you can email the Stack Exchange URL to support@craftcms.com and we’ll see if we can help.

**Comment by MrGlasspoole** [comment]
Hm, Discord looks complicated and more like a chat where you can't open threads.
