### ISSUE TITLE
[3.2] "pageTrigger" config setting causes unwanted CP redirects if its name matches the primary entry type of a section

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#4631]
### Description
We were having a problem where, after updating to 3.2, we could no longer create new entries for a specific section.

This section was generically titled `Pages` with two entry types, the primary being `page`.

Our `pageTrigger` value was set to `page`. Changing to anything other than `page` made entries work like normal again. Testing against another section's primary entry type, I was able to change the `pageTrigger` name to break those sections in a similar way.

### Steps to reproduce

1. Create a section with an entry type
2. Set your `pageTrigger` config setting to match the name of that section's entry type
3. Try to create a new entry for your section

### Additional info

- Craft version: 3.5.1

**Comment by brandonkelly** [comment]
I could see how this could be an issue if the *section* handle matches the `pageTrigger` config setting, as section handles are included as URL segments when editing entries. Not *entry type* handles though; did you just mistype that, but really mean sections?

I’m also not sure what the 3.2 update would have done to provoke this. You’re sure that the handle was `page` before updating to 3.2 and things worked fine before then?

**Comment by brandonkelly** [comment]
Fixed this for the next release. I was only able to reproduce if the `pageTrigger` ended in a trailing slash (e.g. `page/`), though.
