### ISSUE TITLE
Upgrade from 3.1.34 to 3.2X causes queue to halt indefinitely if any entry contains a slug with a non-standard character 

### ISSUE THREAD

**Issue by jenibelle08** [craftcms/cms#4637]
### Description
After the upgrade on one of my Craft sites, I noticed that the "Updating entry drafts and revisions" queue was stuck.

In trying to locate the culprit, I noticed an entry that would no longer save. That entry had an "ñ" character in its slug. In Craft 3.1.34 there were no issues with the character. However, post update, I saw there was an error in the queue.log file which pertained to this entry. So, after upgrading to 3.2, I deleted the entry, re-added it without the "ñ" character, then manually truncated the queue table. 

The queue seemed to work going forward. I wonder if there has possibly been an error introduced in 3.2 with regards to the new drafts/revisions implementation and non-standard character encodings?

This may be related to this issue: https://github.com/craftcms/cms/issues/4628

### Steps to reproduce

1. Save an entry with a non standard character in the slug, e.g. ñ
2. Upgrade from Craft 3.1.34 to 3.2.5.1

### Additional info
- Craft version: 3.2.5.1
- PHP version: 7.3.6
- From the queue.log file:

INSERT INTO `entryversionerrors` (`versionId`, `error`) VALUES (1542, 'SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: \'\\xC3-ones...\' for column `my_db`.`elements_sites`.`slug` at row 1\nThe SQL being executed was: INSERT INTO `elements_sites` (`elementId`, `siteId`, `slug`, `uri`, `enabled`, `dateCreated`, `dateUpdated`, `uid`) VALUES (1943, 1, \'my-slug-with-�-character\', \'path/to/my-slug-with-ñ-character\', 1, \'2019-07-22 23:19:42\', \'2019-07-22 23:19:42\', \'a49ca345-f109-40ff-9ed6-c90c1f9890c8\')')

**Comment by brandonkelly** [comment]
Yeah this is almost certainly related to #4628. We’re going to release 3.2.6 tomorrow with a fix.
