### ISSUE TITLE
Column sections:previewTargets is installed as varchar(255), causes project-config to fail.

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#4638]
### Description

When upgrading a 3.1 install to 3.2, a previewTargets column was added as text:

`$this->addColumn(Table::SECTIONS, 'previewTargets', $this->text()->after('propagationMethod'));`

In a fresh install however the column is defined as varchar(255) 
`'previewTargets' => $this->string(),`

what causes applying the project config to fail:

`'An error occurred while executing the "craft\migrations\Install migration: SQLSTATE[22001]: String data, right truncated: 1406
Data too long for column 'previewTargets' at row 1
`

Should be created as text as before.

Thanks.

### Additional info

- Craft version: 3.2.5.1
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed this for today’s 3.2.6 release.
