### ISSUE TITLE
Dynamic titles not being created on entry creation, only after resave

### ISSUE THREAD

**Issue by shornuk** [craftcms/cms#4639]
### Description
I've got a section where an entry type has a dynamic title set 
`{dateCreated|date('dmy')}-{{"%07d"|format(id)}}`

When the entry is created (or duplicated) the title does not get generated properly. The example above should generate a title like... `230719-0001965` but once it's created the title is '230719-0000000' - only on a second save does the title updated. The slug however, is generated off the first save and as such, stays as 230719-0000000.

### Steps to reproduce

1. Create an entry type where the entry type has a dynamic title including the ID. 
2. Create new entry or duplicate an existing entry

### Additional info

- Craft version: 3.2.5.1
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
I can reproduce this but I’m not sure what we can do to fix it. The title and slug both need to be set before the entry is saved, and the entry won’t get an ID until after it is saved.

You could work around this bug by adding a module with this code, though:

```php
use Craft;
use craft\elements\Entry;
use craft\events\ElementEvent;
use craft\helpers\ElementHelper;
use craft\services\Elements;
use yii\base\Event;

Event::on(Elements::class, Elements::EVENT_AFTER_SAVE_ELEMENT, function(ElementEvent $e) {
    if ($e->element instanceof Entry && $e->isNew) {
        /** @var Entry $entry */
        $entry = $e->element;

        if (!$entry->propagating &&
            !ElementHelper::isDraftOrRevision($entry) &&
            $entry->section->handle === 'yourSectionHandle'
        ) {
            // Resave the entry so it gets a new title and slug
            $entry->slug = null;
            Craft::$app->elements->saveElement($entry);
        }
    }
});
```

**Comment by samhibberd** [comment]
@brandonkelly We are getting some really strange behaviour here. It appears to be creating multiple entries in the database (multiple rows) although we can't access these in the cp, we can directly by `getEntryById`. They appear identical although the auto slug generation is not working even after forcing the resave (like you example) although we are using an event on Entry (EVENT_AFTER_SAVE). We also seem to be running into an issue with isNew returning true when it should be false.

Not sure if this is oddities with 3.2 or us not understanding the way it is working :(

**Comment by brandonkelly** [comment]
> It appears to be creating multiple entries in the database (multiple rows) although we can't access these in the cp, we can directly by `getEntryById`

You are probably looking at entry drafts or revisions, which are both stored as elements in 3.2. (See the `elements` table – if the row has a `draftId` or `revisionId` value, then it’s a draft/revision.)

> although the auto slug generation is not working even after forcing the resave (like you example) although we are using an event on Entry (EVENT_AFTER_SAVE).

I tested and it’s working on my end. You need to use the `Elements::EVENT_AFTER_SAVE_ELEMENT` event as per my example though, not `Entry::EVENT_AFTER_SAVE`, so your code triggers when `Elements::saveElement()` is completely done with the element save routines.

> We also seem to be running into an issue with isNew returning true when it should be false.

Make sure you’re running the latest Craft 3.2 release.

**Comment by shornuk** [comment]
> I tested and it’s working on my end. You need to use the Elements::EVENT_AFTER_SAVE_ELEMENT event as per my example though, not Entry::EVENT_AFTER_SAVE, so your code triggers when Elements::saveElement() is completely done with the element save routines.

Good to know. We were using the `EVENT_AFTER_SAVE` so that takes care of that. 

> Make sure you’re running the latest Craft 3.2 release.

We're on the latest version, we ran into the `isNew` issue when using the `EVENT_AFTER_SAVE` so not sure if that is causing an issue too? Using the `Elements::EVENT_AFTER_SAVE_ELEMENT` seems to be working.

> You are probably looking at entry drafts or revisions, which are both stored as elements in 3.2. (See the elements table – if the row has a draftId or revisionId value, then it’s a draft/revision.)

That was our understanding, but it's creating entries in the `entries` table. Rows are created in the elements table, but nothing in `drafts` table and only the current entry in the `revisions` table.
This means that each entry that is being created is getting an ID that is 2 on from last one. Is that right?

**Comment by brandonkelly** [comment]
> That was our understanding, but it's creating entries in the `entries` table.

All entries should have a row in `entries`, `elements`, `elements_sites`, and `content` – whether they are a draft, revision, or normal entry.

> This means that each entry that is being created is getting an ID that is 2 on from last one. Is that right?

Yes. When you first click “New Entry”, an entry will be created in an “unsaved draft” state, which means that the entry is a draft, but if you find its row in the `drafts` table (per its `draftId` value), you will find that the `sourceId` column is `null`, because the draft doesn’t have a source entry yet. In this state the entry won’t actually show up anywhere, and the draft is ephemeral, so unless you click “Save Entry”, it will be deleted via garbage collection after 30 days ([configurable](https://docs.craftcms.com/v3/config/config-settings.html#purgeunsaveddraftsduration)).

Once you click “Save Entry”, the following happens:

1. The draft will be updated one last time with the latest form data.
2. A new, _real_ entry will be created based on the draft.
3. As part of the entry creation process, a revision will be created for the entry, capturing its initial state.
4. The draft will be deleted.

So those two IDs that were “skipped” when you create a new entry belong to the unsaved draft (now deleted) and the initial entry revision.

**Comment by shornuk** [comment]
Thanks @brandonkelly for the explanation. I think it was just throwing us with all the entries being created in the `entries` table - which don't ever seem to get cleaned up/removed via garbage collection. 
We also found it was a little confusing seeing the `Revision from 24 Jul 2019, 08:25:58` in the notes field when the entry is first created. It didn't/doesn't give the impression that this is the first version of the entry, especially when there are no revisions to roll back to.
