### ISSUE TITLE
[3.2] Umlauts do not work in slugs

### ISSUE THREAD

**Issue by handplant** [craftcms/cms#4640]
### Description

Umlauts do not work in slugs, no matter if limitAutoSlugsToAscii is set to true or false.

![Bildschirmfoto 2019-07-23 um 13 23 35](https://user-images.githubusercontent.com/2598962/61708638-8fe8da80-ad4d-11e9-8967-68f2c4ded55e.png)

### Steps to reproduce

1. Edit an entry and add "ääää" to slug
2. Save Entry

### Additional info

- Craft version: Craft Solo 3.2.5.1
- PHP version: 7.2.14
- Database driver & version: MySQL 5.5.5

**Comment by MaximilianSchwarz** [comment]
Sometimes i have the same error.

**Comment by sebastian-lenz** [comment]
Hey, you can find a prerelease solving this issue here: #4628

**Comment by MaximilianSchwarz** [comment]
Ah perfect. Thanks.

**Comment by brandonkelly** [comment]
We just released Craft 3.2.6 with the fix for this.
