### ISSUE TITLE
Dashboard js error when Quick Post widget not enabled.

### ISSUE THREAD

**Issue by KatieMFritz** [craftcms/cms#4641]
### Description
```
Uncaught TypeError: Cannot read property 'prototype' of undefined
    at s.constructor.setup (Widgets.js?v=1563800684:22)
    at dashboard:1115
```

### Steps to reproduce

1. Load dashboard with Quick Post widget not enabled.
2. Get console error.
3. Enable Quick Post widget.
4. No error.

### Additional info

- Craft version: Craft Pro 3.2.5.1
- PHP version: 7.2.19
- Database driver & version: PostgreSQL 10.9
- Plugins & versions: many.

**Comment by brandonkelly** [comment]
Craft doesn’t have a `Widgets.js` file. Maybe that’s a plugin-supplied script?

**Comment by KatieMFritz** [comment]
Well then! 😁 I'll do some more digging. Sorry bout that.
