### ISSUE TITLE
FR: Reference tags for globalset identified by handle instead of id

### ISSUE THREAD

**Issue by timbertens** [craftcms/cms#4645]
We're currently dealing with use case of 1 codebase for about 40 individual sites, so all the configuration and standardisation we can use is very welcome. 

I have however an issue with reference tags and globalset, it seems that globalset can only be identified using id and not their handle.  

The problem is that we're also heavily relying on migrations and project.yaml (which are blessings in the case) and the ids for globalset are not the same over the different environments, but the handles of course are.  

So now I'm using 
`{globalset:26:companyName} `
for instance, but that fails to work of course when the id of the globalset is not 26 for some reason

We would like to use 
`{globalset:agent:companyName} `
instead

This request is related to https://github.com/craftcms/cms/issues/1227

**Comment by brandonkelly** [comment]
This is done for 3.3.

**Comment by nicbou** [comment]
I found this by accident. Is it possible that this feature is not documented?

**Comment by brandonkelly** [comment]
@nicbou See the last example here: https://craftcms.com/docs/3.x/reference-tags.html#examples

**Comment by nicbou** [comment]
Fantastic! I'm surprised that I've missed it. Thanks Brandon

Brandon Kelly ***@***.***> schrieb am Fr., 21. Jan. 2022,
22:43:
