### ISSUE TITLE
Enhancement: Layout Designer - Entry Style Layout

### ISSUE THREAD

**Issue by jwb009** [craftcms/cms#4647]
### Description
I've always felt the UI of the Layout Designer to be a bit of an odd duck relative to the polish of the rest of the Control Panel. To increase usability, I would propose a layout that more closely mimics an actual entry page. 

The ideas are fairly self-explanatory by viewing my crude mockup below. 

- Title, Name, and Handle go-to the detail section of the sidebar
- Below that you have Field Groups, designed as accordion-style dropdowns. 
- You drag Fields to the content area, which gives a good approximation of what it would look like on an Entry Page (this would also open up the possibility of the much-requested ability to put fields into columns)

![craft_mockup](https://user-images.githubusercontent.com/7241260/61747373-591dbf00-ad63-11e9-8822-ec5f24b777f0.png)

**Comment by brandonkelly** [comment]
We’re planning a big field layout designer redesign for Craft 4 ;)

**Comment by brandonkelly** [comment]
The next Craft 3.5 release will feature a redesigned field layout editor, with several improvements (see #806, #913, #1138, #2644, and #3953). Decided against trying to style it like a normal edit page, but at least it looks a lot more at home in the Craft control panel now:

<img width="1035" alt="The new field layout designer in Craft 3.5" src="https://user-images.githubusercontent.com/47792/87213338-15f08f00-c2d9-11ea-8afb-78f4d7bfc6aa.png">
