### ISSUE TITLE
[3.2.6] Adding Categories not firing Preview update

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#4648]
### Description
I just noticed this testing Live Vue Gatsby samples for release, so it feels recent. Other types like images, texts Redactor or simple, etc. are fine, but when I add a category to an Entry's list, by selecting from the usual hud, there's no preview update -- until I mouse in one of the text fields. That's all it takes. 

There might be a delay, even then, compared to other edits -- not certain but should be checked.

Removing a category, on the other hand, immediately updates fine.

### Steps to reproduce

1. EntryType with a category Field
2. Edit an Entry with it, fresh new or otherwise - I checked both
3. Use the Add a Category button, and select one available
4. Nothing happens
5. Now mouse within a text or Redactor field of the CP Editor
6. Previewed category list updates, maybe with a delay
7. Stabilize, then remove a category on the edit side
8. Proper immediate update happens, and preview shows the removed gone

### Additional info

PHP version | 7.1.28
OS version | Linux 4.15.0-47-generic
Database driver & version | MySQL 5.7.25
Image driver & version | GD 7.1.28
Craft edition & version | Craft Pro 3.2.6
Yii version | 2.0.21
Twig version | 2.11.3
Guzzle version | 6.3.3
Imagine version | 1.2.3-dev

CraftQL | 1.3.2
Element API | 2.5.4
Live Vue Gatsby | dev-draft-previews-new-architecture
Redactor | 2.3.3.2

**Comment by brandonkelly** [comment]
Thanks! All fixed for the next release.

**Comment by narration-sd** [comment]
Hmm. This seems not to do the trick yet....
- tested on your hash plus current dev-master
- tested on current Chrome, Firefox, and the Chrome Canary I usually use
- all testing on Win10 latest and greatest (?...)

On each of these, same behavior as before in issue, no updates until mousing in a text field afterwards

@brandonkelly

**Comment by brandonkelly** [comment]
> tested on your hash plus current dev-master

Your `craftcms/cms` requirement should be set to `dev-develop#b6836a8412bcf775196e14d1c3bf815ef4a2c9b4`, not `dev-master#...`.

**Comment by narration-sd** [comment]
I did that first -- and still. The dev-master plain thing was just to see if there was a difference.

Also lots of clear browser cache total/restart, vagrant reload, etc. to try to eliminate caches.

It looks pretty solid...?

**Comment by narration-sd** [comment]
```
        "craftcms/cms": "dev-develop#b6836a8412bcf775196e14d1c3bf815ef4a2c9b4 as 3.2.5",
```

**Comment by brandonkelly** [comment]
Doh sorry, I forgot that Categories fields don't call `selectElements()` like other relational fields. Really fixed now. Use `dev-develop#6f47e6aa8a988639152619a462f2082bea675d1d`.

**Comment by narration-sd** [comment]
will try :)

**Comment by narration-sd** [comment]
Bingo -- works fine, multiple cat adds included.

Cheers,  @brandonkelly
