### ISSUE TITLE
[3.2] Add an option to end-user to disable autosave completely

### ISSUE THREAD

**Issue by minyangu-bgl** [craftcms/cms#4649]
### Description
The new autosave creates a lot of unnecessary web-hook events. For our use case, we would rather turning it off completely. However, there is no option available to let end user decide if we should enable/**disable** the autosave. 

Currently, the autosave is enabled when user crates a new entry (since a draft is automatically created), or it is enabled when user manually creates a draft. 

### Steps to reproduce

1. Create a New Entry for multi-lingual sites. Say 10 languages.
2. Filling up the entry and click save.
3. There are 1 deleted event as the auto created draft is deleted, and it also generated more than 60 events for saved entry. For integration, this will definitely create a lot of server burden to handle those events at real time, as those 60 events are published at the exact SAME time. 

So the question here is why it generates so many events at saving time. If it only generates 3 events, then I can understand, e.g.
- 1 event for the deleted draft
- 1 event for creating the revision, 
- 1 event for creating/updating the current entry.

However, generating 60+ or even potentially hundreds of events at once seems a bit wrong somewhere to me.

For our use case, we want to disregard any events if they are related to draft/revisions. Hence, one quick option here is to let the end user to disable the auto-saving feature completely, until one day the number of events can be dramatically reduced at Saving time.

### Additional info

- Craft version: 3.2.6
- PHP version: 4.2
- Database driver & version: MariaDB 10.4
- Plugins & versions: Webhook 2.0.1

**Comment by effer89** [comment]
I am also having this issue, I need a way to disable this autosaves, and I think theres something wrong, when I created a new entry, afterSave is trigger 12 times with 1 site/language.

**Additional info**
Craft version: 3.2.6
Plugins & versions: Webhook 2.0.1

**Comment by brandonkelly** [comment]
> For our use case, we want to disregard any events if they are related to draft/revisions.

You can disregard them from the event handler. Sounds like you also would like to disregard events that are triggered when the entry is getting propagated, which would have triggered before 3.2 as well. And as of Craft 3.2, you can even tell when the entry is being saved as part of a bulk-resave operation (either in a background Resave Elements job, or via the `resave/entries` console command).

If you are using [craft\base\Element::EVENT_AFTER_SAVE](https://docs.craftcms.com/api/v3/craft-base-element.html#event-after-save), do this:

```php
use yii\base\Event;
use craft\elements\Entry;
use craft\base\Element;
use craft\events\ModelEvent;
use craft\helpers\ElementHelper;

Event::on(Entry::class, Element::EVENT_AFTER_SAVE, function(ModelEvent $e) {
    /** @var Entry $entry */
    $entry = $e->sender;

    // Ignore events we don't care about
    if (
        $entry->propagating ||
        $entry->resaving ||
        ElementHelper::isDraftOrRevision($entry)
    } {
        return;
    }
}
```

If you are using [craft\services\Elements::EVENT_AFTER_SAVE_ELEMENT](https://docs.craftcms.com/api/v3/craft-services-elements.html#event-after-save-element), do this:

```php
use yii\base\Event;
use craft\services\Elements;
use craft\events\ElementEvent;
use craft\elements\Entry;
use craft\helpers\ElementHelper;

Event::on(Elements::class, Elements::EVENT_AFTER_SAVE, function(ElementEvent $e) {
    // Ignore if this isn't for an entry
    if (!$e->element instanceof Entry) {
        return;
    }

    /** @var Entry $entry */
    $entry = $e->element;

    // Ignore events we don't care about
    if (
        $entry->propagating ||
        $entry->resaving ||
        ElementHelper::isDraftOrRevision($entry)
    } {
        return;
    }
}
```
