### ISSUE TITLE
FR: Add hook to header of entry edit pages

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#4650]
### Description

When adding some useful information/warnings to the edit screen like 

`Conflict: Entry has been updated by xy after this draft has been created!`,

 this can be placed at the bottom of the details block via `cp.entries.edit.details`. Where it can be overlooked, especially if other plugins add their things.

This can be very custom specific, so it goes beyond the scope of generic impovements to the drafts workflow.

So it would be great to add a hook in the header, next to the versions drop down.

### Additional info

- Craft version: 3.2.6

**Comment by brandonkelly** [comment]
I think your best bet to do this is going to be to add the message dynamically with JavaScript.

**Comment by wsydney76** [comment]
Ok, thanks, will try that.

Is there a JavaScript event we could listen to  when a new draft is created?

**Comment by brandonkelly** [comment]
Yeah, you could do this:

```javascript
if (window.draftEditor) {
    window.draftEditor.on('createDraft', function() {
        // ...
    });
}
```
