### ISSUE TITLE
Add any attributes with svg()

### ISSUE THREAD

**Issue by missmatsuko** [craftcms/cms#4660]
### Description
We can already add classes to SVGs with this function, but it would be great if we could add any attribute.

It would make it a lot easier to follow [accessible SVG patterns](https://developer.paciellogroup.com/blog/2013/12/using-aria-enhance-svg-accessibility/), especially with #3937 and if there were some way to reference the title and/or desc elements added that way.

**Comment by brandonkelly** [comment]
Just added a new `|attr` filter for Craft 3.3, which will work on any HTML element, not just SVGs.

```twig
{{ svg('@webroot/icons/hello')|attr({
    class: 'icon',
    role: 'img',
    'aria-labelledby': 'title desc'
}) }}
```

It supports the same attribute definition as the [attr()](https://docs.craftcms.com/v3/dev/functions.html#attr) function added in 3.2 – they both use [Html::renderTagAttributes()](https://www.yiiframework.com/doc/api/2.0/yii-helpers-basehtml#renderTagAttributes()-detail) behind the scenes.

Docs here: https://github.com/craftcms/cms/blob/3.3/docs/dev/filters.md#attr
