### ISSUE TITLE
Error when deleting user with transfer content

### ISSUE THREAD

**Issue by carolineboeykens** [craftcms/cms#4670]
### Description
Error when deleting user with transfer content

error:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'dateUpdated' in 'field list'
The SQL being executed was: UPDATE `drafts` SET `creatorId`=549, `dateUpdated`='2019-07-29 09:17:52' WHERE `creatorId`='559'
```

### Steps to reproduce

1. Delete a user
2. Transfer content to other user

### Additional info

- Craft version: 3.2.7
- PHP version: 7.2.1

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release (will be Craft 3.2.8).

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#05a0456db4e246304bb798b5e0ffa76908776e06",
  "...": "..."
}
```

Then run `composer update`.
