### ISSUE TITLE
"Save as a new entry" doesn't update the postDate

### ISSUE THREAD

**Issue by jamiewade** [craftcms/cms#4673]
### Description
When using the "Save as a new entry" feature, the newly created entry keeps the `postDate` from the entry it was duplicated from.

I would instead expect that the `postDate` be updated to reflect the moment this new entry was created.

### Additional info

- Craft version: 3.2.6
- PHP version: 7.2.17
- Database driver & version: MySQL 5.7.27

**Comment by brandonkelly** [comment]
“Save as a new entry” will create a new entry with all the same values you currently see on the page. So if you want the new entry to gain a new Post Date, you will need to clear out the current Post Date value before submitting.
