### ISSUE TITLE
Upgrading from 3.0.18E to 3.0.20E causing failure to update taxonomy

### ISSUE THREAD

**Issue by manateeyl** [craftcms/cms#4675]
## Describe the bug
Since we upgraded to CrafterCMS AMI 3.0.20E, we are not able to add/update new content. We got error "video-streams.xml in system processing". And tomcat catalina.out complained java.security.AccessControlException: access denied when it is trying to do a github repo update.

## To Reproduce
1. Go to Studio and click Taxonomies, and Video Streams. 
2. Add a new Video stream and click submit
3. See error: Failed to write emma-portal:/site/taxonomies/video-stream.xml:video-streams.xml:/component/taxonomy

## Expected behavior
No error should be seen and new content should be showing. 

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
{{Software version if applicable (copy paste from Help > About).}}
Crafter CMS Enterprise Edition v3.0.20E. 
### OS
{{What OS did you use to produce the bug.}}
ubuntu

### Browser
{{What browser did you use to produce the bug.}}
Firefox

## Additional context
{{Add any other context about the problem here.}}

**Comment by brandonkelly** [comment]
Hi, this repo is for [Craft CMS](https://craftcms.com), unrelated to Craft**er** CMS.
