### ISSUE TITLE
Broken Link - v3 Documentation - Testing - Getting Started

### ISSUE THREAD

**Issue by dcplebranch** [craftcms/cms#4678]
### Description

Link for get started guide is broken
### Steps to reproduce

1. Go to https://docs.craftcms.com/v3/testing/#introduction
2. Clicking "get started guide" 

If I click the same link within github, it seems to work though

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks! This was fixed by PR #4666, which is going to be published a little later today :)
