### ISSUE TITLE
Plugin-Development: Auto save API

### ISSUE THREAD

**Issue by sebastian-lenz** [craftcms/cms#4679]
Okay, now that the dust of the 3.2 release has settled, I would like to address some questions regarding the new auto save features in Craft CMS from the perspective of a plugin/field developer. Over the past weeks I've tweaked my fields to play well with the new auto save feature and right now I am facing two obstacles where I ran out of ideas.

## Trigger an auto save

The auto save currently listens to certain html events to trigger a save. The following events might [trigger an auto save](https://github.com/craftcms/cms/blob/develop/src/web/assets/cp/src/js/DraftEditor.js#L99): `keypress`, `keyup`, `change`, `focus`, `blur`, `click`, `mousedown` and `mouseup`.

However, one of my fields uses html drag events and those do not emit mouse events. Similar problems show up if fields use asynchronous operations, e.g. the SimpleMap field does not trigger auto saves correctly as the location data is fetched from api and updates happen outside of the given events.

_Question:_ So what should we do in those cases, is there a callback or event we can use to tell Craft that an auto save is required right now?

_Easiest solution:_ Implement an event fields can emit when an auto save is required.

## Omit fields from auto save

Craft currently determines whether the draft has changed by collecting all form data using the jQuery function `serializeForm` [here](https://github.com/craftcms/cms/blob/develop/src/web/assets/cp/src/js/DraftEditor.js#L296) and comparing that data with the last saved one. The jQuery documentation states that [only "successful controls" are serialized](https://api.jquery.com/serialize/), meaning we can prevent inputs from being collected here by either disabling them or not giving them a name.

Problems arise as soon as we don't have control over those properties. While the disabled attribute is usually not usable, we found situations where we created Redactor fields dynamically and Redactor enforces a name to be set on the underlying `textarea` element, causing auto save to be triggered.

_Question:_ How can we tell Craft that certain form values should not be considered when triggering auto saves?

_Easiest solution:_ Serialize form data using [serializeArray](https://api.jquery.com/serializeArray/), trigger an event that allows fields to manipulate that data and then compare it.

**Comment by brandonkelly** [comment]
> So what should we do in those cases, is there a callback or event we can use to tell Craft that an auto save is required right now?

Do this in your JavaScript, when you’re ready for the autosave to kick off:

```javascript
if (window.draftEditor) {
    window.draftEditor.checkForm();
}
```

There are a couple places where Craft does that itself:

https://github.com/craftcms/cms/blob/1239460455a61552510153fd249e48e3c325c27f/src/web/assets/cp/src/js/BaseElementSelectInput.js#L423-L430

https://github.com/craftcms/cms/blob/1239460455a61552510153fd249e48e3c325c27f/src/web/assets/cp/src/js/AssetSelectInput.js#L202-L209

> How can we tell Craft that certain form values should not be considered when triggering auto saves?

That’s not currently possible, and I think it’s reasonable for Craft to assume that if the the form data has changed, there’s something in there worth autosaving.

> we found situations where we created Redactor fields dynamically and Redactor enforces a name to be set on the underlying `textarea` element, causing auto save to be triggered.

Not sure I’m following this example… are you creating the Redactor input as part of a custom control that doesn’t directly impact the main entry content? If that’s the case, maybe just place it outside of the page’s primary form?
