### ISSUE TITLE
AllowAnonymous not working as expected

### ISSUE THREAD

**Issue by Zae** [craftcms/cms#4684]
### Description
I also posted this to the plugin where I noticed this, but because the documentation seems to agree with how they are doing this I wanted to post this here as well.

https://github.com/verbb/comments/issues/133

It seems that the `$allowAnonymous` check does not work as expected. In my testing craft checks the `$allowAnonymous` array for the key `save`, but the action is called `actionSave`, just like the documentation says it should be.

Could this be something that changed in 3.2 and the docs are not updated yet? I know there were changes to this system recently.

### Steps to reproduce

1. Try to call an action 'anonymously'
2. 503 error is thrown because the action is not allowed.

### Additional info

- Craft version: 3.2.5.1
- PHP version: 7.2
- Plugins & versions: verbb/comments: 1.1.7.1

**Comment by brandonkelly** [comment]
Josh is on the case. It’s not a Craft bug.
