### ISSUE TITLE
Expand button missing in structure view 

### ISSUE THREAD

**Issue by sebastian-lenz** [craftcms/cms#4685]
### Description

The structure view does not show the expand/collapse handle in front of entries if all children are disabled. In this example the little arrow in front of "Services" is missing:

![Bildschirmfoto 2019-07-31 um 14 42 40](https://user-images.githubusercontent.com/2273359/62212860-f8653680-b3a1-11e9-909f-153577408455.png)

This can lead to strange situations, if you move a disabled entry onto another entry, it sometimes seems to disappear cause the parent is collapsed.

### Steps to reproduce

1. Create a structure section.
2. Create an entry, will be the parent.
3. Create a child entry on the parent entry, set it to be disabled.
4. Look at the structure view.

### Additional info

- Craft version: Craft Solo 3.2.7 & Craft Pro 3.2.8
- PHP version: 7.2.19
- Database driver & version: MySQL 5.7.19
- Plugins & versions:
  - Content Field: dev-release
  - Redactor: 2.3.3.2

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.
