### ISSUE TITLE
"Save and add another" triggers leaving page warning

### ISSUE THREAD

**Issue by MaffooBristol** [craftcms/cms#4686]
### Description

Save and add another comes up with a "Leave site?" modal warning. This makes it feel like doing so will not save the content, but it does. It also sometimes flashes a red error at the top of the page before being covered by an entry saved confirmation message. I couldn't quite catch what it said.

Not the highest priority but I could imagine that if it were a, let's say "less technologically advanced" client who came across this, it might confuse them.

Thanks!

### Steps to reproduce

1. Create a new entry
2. Enter a title
3. Choose "Save and add another"

### Additional info

- Craft version: Craft Solo 3.2.5.1
- PHP version: 7.2.17
- Database driver & version: MySQL 5.7.25
- Plugins & versions: Redactor 1.0

![image](https://user-images.githubusercontent.com/3296828/62230439-b34cfe80-b3b9-11e9-89a7-2c233492fa85.png)

**Comment by MaffooBristol** [comment]
Just got the same thing actually when choosing the default "Save Entry", so perhaps this isn't specific to the save and add another button

**Comment by brandonkelly** [comment]
This was fixed in 3.2.8 via df021c15d8cf2363cedb3f628931102bad9f72c4.
