### ISSUE TITLE
The "Updating entry drafts and revisions" task during the 3.2.x upgrade never completes for large `entryversions` tables

### ISSUE THREAD

**Issue by aaronbushnell** [craftcms/cms#4688]
### Description

Related to #4687 which was a symptom of the actual problem noted below

We have a massive `entryversions` table (~900 MB/~2 million records). The query that is ran to convert this data into the new `entryversions` format during a 3.2.x upgrade never completes due to how large this table is for us.

The `$query` being built [in the convertVersions() method](https://github.com/craftcms/cms/blob/develop/src/queue/jobs/ConvertEntryRevisions.php#L191-L195) never completes and this process never finishes for us.

Here's the raw SQL that I got by running `$query->getRawSql()` instead of `->count()`:

```sql
SELECT `id`, `entryId`, `creatorId`, `siteId`, `num`, `notes`, `data`, `dateCreated`, `uid` 
FROM `craft_entryversions` `v`
WHERE (NOT EXISTS (SELECT * FROM `craft_entryversionerrors` WHERE `versionId` = `v`.`id`)) AND (`num` > (SELECT max(cast(`num` as signed)) - 10 FROM `craft_entryversions` WHERE `entryId` = `v`.`entryId`))
ORDER BY `id` DESC
```

With a table the size of ours this never finishes pulling the data. I'm happy to supply a SQL file if that's helpful!

### Steps to reproduce

1. Upgrade to 3.2.x with an `entryversions` table that has many records

### Additional info

- Craft version: 3.2.8
- PHP version: 7.2.12
- Database driver & version: MySQL 5.7.24

**Comment by brandonkelly** [comment]
Hey Aaron, in theory you probably don’t really need any revisions that are more than a month or two old, so one possibility you could just delete any revisions that are older than that:

```sql
DELETE FROM craft_entryversions
WHERE dateCreated < '2019-05-31'
```

(Keep the original table backed up somewhere first, in case you do end up needing any of that revision data.)

Then try re-running the “Updating entry drafts and revisions” job, with the smaller dataset.

**Comment by aaronbushnell** [comment]
Thanks, @brandonkelly! Will this cause any issues if there's an entry that has only one version and it was created after this date?

**Comment by brandonkelly** [comment]
You’d just end up losing all revision history for that entry. It won’t impact the current revision of any entries though.

**Comment by aaronbushnell** [comment]
Looks like that worked, @brandonkelly! It's now processing the entry drafts and revisions.
![Screen Shot 2019-07-31 at 3 33 36 PM](https://user-images.githubusercontent.com/315202/62242185-99ef8680-b3a8-11e9-8223-473b9a122037.png)

Since this is working should I just plan on trashing a number of these `entryversions` records before performing the 3.2.x update? Any concerns I should have about any data loss if I do this?

**Comment by brandonkelly** [comment]
This is the first case I’ve heard of where deleting existing revisions was necessary in order to get the job to work properly. As long as that first query is able to execute, it shouldn’t really matter how big that `entryrevisions` table is, since the query only selects the last 50 (or whatever `maxRevisions` is set to) revisions for each entry, ignoring the rest. So I’d say in general you should not worry about it, unless you run into the same issue again.

**Comment by aaronbushnell** [comment]
Thanks, @brandonkelly! Sounds like when I do the official upgrade for the live site I'll need to run that SQL deletion if I want these to process through.

And, sorry, just to be 100% clear—I can run that `DELETE` statement without worrying about data loss, correct? This won't delete any entries it'll just remove the revisions of all entries to a certain date?

**Comment by brandonkelly** [comment]
Yep exactly.

**Comment by aaronbushnell** [comment]
Thanks again, @brandonkelly!

**Comment by bgrrtt** [comment]
I just ran into this issue upgrading from Craft 2 to Craft 3.2. Our craft_entryversions table had ~500,000 rows and even though we are only loading the first 50 versions of each entry, could looping through this many entries "tweak out" php/mysql? 

MySql's `SHOW FULL PROCESSLIST;` showed several stalled tasks looping through `craft_entryversions` and inserting into `entryversionerrors`.

Luckily, all of these entry versions were able to be removed, which also resulted in a reduced DB size from ~900MB to ~350MB, and after restarting php/mysql haven't had an issue.

**Comment by Harry-Harrison** [comment]
I had this same issue with a recent update but im struggling to see how to re-run the “Updating entry drafts and revisions” job now I have a smaller dataset. Any way I can do it from the command line?
