### ISSUE TITLE
Request missing required body param error when attempting to publish new entry via front-end form

### ISSUE THREAD

**Issue by ademers** [craftcms/cms#4693]
### Description

After updating Craft to 3.2.x, I get `Request missing required body param` error when attempting to publish a new entry via a front-end form.

Error screenshot: https://cl.ly/a1a13a755c69

Adding `<input type="hidden" name="entryId" value="">` as per SE post https://craftcms.stackexchange.com/questions/30797/request-missing-required-body-param-error-when-creating-entry-on-front-end to the form seems to resolve the issue.

The example form in the docs at https://docs.craftcms.com/v3/dev/examples/entry-form.html does not contain `<input type="hidden" name="entryId" value="">`.

Is this a bug or a breaking change?

### Steps to reproduce

1. Update Craft to 3.2.x
2. Attempt to submit a front-end form to create a new entry
3. `Request missing required body param` error displays

### Additional info

- Craft version: 3.2.8
- PHP version: 7.0.33
- Database driver & version: MySQL 5.7.27
- Plugins & versions:
```
    "craftcms/cms": "3.2.8",
    "vlucas/phpdotenv": "^2.4.0",
    "mmikkel/retcon": "^2.0.11",
    "craftcms/redactor": "2.3.3.2",
    "aelvan/mailchimp-subscribe": "3.0.0",
    "barrelstrength/sprout-encode-email": "^v2.0.4",
    "topshelfcraft/wordsmith": "^3.0.4",
    "craftcms/contact-form": "2.2.5",
    "mmikkel/cp-field-inspect": "^1.0.5",
    "craftcms/mailgun": "1.4.2",
    "rias/craft-notifications": "^1.1.1",
    "lukeyouell/craft-mailchimplists": "^1.0.5",
    "carlcs/craft-redactorcustomstyles": "^v3.0.2",
    "nystudio107/craft-scripts": "^1.2",
    "craftcms/feed-me": "4.1.1",
    "verbb/field-manager": "2.1.0",
    "verbb/super-table": "^2.0.14",
    "lukeyouell/craft-mailgunevents": "^1.0.4",
    "ether/simplemap": "3.6.4.1",
    "solspace/craft3-calendar": "2.0.21",
    "rias/craft-contact-form-extensions": "1.1.6",
    "verbb/expanded-singles": "^1.0.5",
    "nystudio107/craft-connect": "^1.0.0",
    "nystudio107/craft-typogrify": "^1.1.15",
    "nystudio107/craft-seomatic": "3.2.18",
    "aelvan/imager": "v2.1.10",
    "nystudio107/craft-minify": "^1.2",
    "verbb/cp-nav": "2.0.9",
    "nystudio107/craft-retour": "3.1.22",
    "carlcs/craft-assetmetadata": "^3.0.0-beta.2",
    "misterbk/mix": "v1.5.2",
    "craftcms/contact-form-honeypot": "1.0.2",
    "aelvan/preparse-field": "v1.0.6",
    "superbig/craft3-beam": "2.1.4",
    "marionnewlevant/twig-perversion": "2.1.0",
    "lukeyouell/craft-queue-manager": "1.1.0",
    "verbb/cloner": "1.0.3",
    "jdsdev/craft-embedder": "^2.0",
    "craftcms/webhooks": "1.1.2",
    "verbb/comments": "1.1.7.1",
    "olivierbon/craft-squeeze": "1.1.2",
    "topshelfcraft/supersort": "3.0.1",
    "wbrowar/guide": "2.0.0"
```

**Comment by brandonkelly** [comment]
Whoops, that wasn’t an intentional breaking change. Just reverted to `getBodyParam()` for the next release.
