### ISSUE TITLE
Live Preview and entry descendants

### ISSUE THREAD

**Issue by kylecotter** [craftcms/cms#4694]
### Description

The following template works with a published entry on the front end. In live preview and when sharing the draft, `descendants` returns nothing. Are there additional checks/settings I should be doing for Live Preview?

```twig
{{ entry.title }}

{% set descendants = entry.descendants %}

{% for descendant in descendants.all() %}
    {{ descendant.title }}
{% endfor %}
```

### Additional info

- Craft version: Craft CMS Pro 3.2.8

**Comment by brandonkelly** [comment]
All fixed for the next release, thanks for reporting!
