### ISSUE TITLE
Date field not saving properly via an ajax call to the saveEntry action

### ISSUE THREAD

**Issue by pgrzyb** [craftcms/cms#4697]
### Description

I have a front end setup for creating new entries through an AJAX call. The entry type is built with a few text fields, a dropdown, and a date field. A new entry is created and all fields are saved correctly, which I verified in the database (the date field has the correct SQL DateTime format). 

When trying to show that specific entry filtering by the custom date field i get no results - query: 
`craft.entries.type('visits').visitDate(day).visitHour(hour.value)`
Removing the `visitDate(day)` part of the query returns entries, so my assumption is that the date field is to blame.

If I go into the CP and resave the entry without changing any of the content, the same query returns that entry.

### Steps to reproduce

1. Create an entry type with a custom date field.
2. Add a new entry using a front-end form calling the saveEntry action with the date field included in the call.
3. Try to view entries filtered by the custom date field ( craft.entries.*.customField(date) ). The query renders no results.
4. Save the entry manually from the CP without modifying the date field.
5. Run the same query again - this time it returns the entry.

### Additional info

- Craft version: 3.2.8
- PHP version: 7.1.27
- Database driver & version: MySQL 5.5.5
- Plugins & versions: 
```Amazon S3: 1.2.0
ButtonBox: 2.0.4
Kint: 1.0.0
Queue Manager: 1.1.0
Redactor: 2.3.2
Relabel: 1.2.3
Super Table: 2.1.21
Time Ago: 1.0.3

**Comment by pgrzyb** [comment]
I ended up comparing those dates as strings inside the loop the lists them, like:
`{% if day|date('Y-m-d') == visitDate|date('Y-m-d') %}`
and that works, but only as a temporary solution, since in a months time, I might end up having to loop through 30 visits 10 times per page load, in a year that gets multiplied by 12, which is... Well - a lot of DB queries :)

**Comment by brandonkelly** [comment]
Sounds like this could be a caching issue, if the query doesn’t work initially but does start working once you resave the entry in the CP without changing anything.

**Comment by pgrzyb** [comment]
Clearing cache in the CP (without resaving the entry) does not resolve this. I also disabled element query and template cache in the general config, none of those changed the way this behaves.

Another thing I tried before comparing the two strings was comparing the date objects - that failed aswell. Only after comparing 'Y-m-d' formatted strings I managed to get the condition to pass.

**Comment by brandonkelly** [comment]
After saving an entry from your Ajax form, copy its value in the `content` table to a text editor. Then resave the entry from the CP and copy its new value in the `content` table. Did the values change at all?

**Comment by pgrzyb** [comment]
The values don't change at all at first glance, but I did what you suggested, and here is what happened:

1. Copied the visitDate value from the craft_content table into Atom,
2. Saved the entry from CP,
3. Ran the query and it returned the expected results just fine,
4. Copied the value from Atom and pasted it back into the craft_content table,
5. Refreshed the page to run the query again, and that entry was missing from the results.

On a hunch, I checked the encoding of the visitDate field contents after copying and again after resaving it, it was the same UTF-8 in both cases.

**Comment by brandonkelly** [comment]
Per your steps, clearly the value did change. What are the before & after values, exactly?

**Comment by pgrzyb** [comment]
Ok, somehow I managed to fool myself here... The value does change, but here is where it gets a bit weird.
**Before save:** 2019-08-02 00:00:00
**After save:** 2019-08-01 22:00:00
Craft CP still shows the first date as the fields value (https://imgur.com/a/MoHEHJQ) and the query shows it as if it was added with the first date as well. 
I still do not understand why nothing is getting returned from that query before resaving the entry on either of those dates.
As a side note - I verified all time zone settings in Ubuntu, PHP, and MySQL - everything is set to the same one (Europe/Warsaw) returning the same time.

**Comment by brandonkelly** [comment]
Aha, makes sense. The CP submits the date along with your selected timezone. So if you save with a value of `2019-08-02`, you’re really setting the value to `2019-08-02` *in Europe/Warsaw*, which then gets converted to UTC when saving to the database.

When you query for Date/Time fields, it is also assumed that you are querying with the system timezone, unless otherwise specified.

So to get this working as you’d expect, you will need to start submitting the timezone as part of your Ajax request, [as explained here](https://docs.craftcms.com/v3/date-time-fields.html#customizing-the-timezone).

For example, instead of submitting this:

```
fields[yourDateFieldHandle]: 2019-08-02
```

You should submit this:

```
fields[yourDateFieldHandle][date]: 2019-08-02
fields[yourDateFieldHandle][timezone]: Europe/Warsaw
```

**Comment by pgrzyb** [comment]
Amazing! Works like a charm, thank you!
