### ISSUE TITLE
Allow Preview Targets to process environment variables.

### ISSUE THREAD

**Issue by ryanpcmcquen** [craftcms/cms#4701]
It'd be great if the preview target configs allowed environment variables as other fields do.
![Screen Shot 2019-08-02 at 12 54 28 PM](https://user-images.githubusercontent.com/772937/62395310-af89bb00-b524-11e9-9b9c-5c6c60835cd4.png)

**Comment by brandonkelly** [comment]
No CP settings that allow environment variables will let you combine it with a suffix. So even if we allowed `$FOO`, you wouldn’t be able to type `$FOO/preview/{slug}`. So I’m not sure how helpful this would be in this case.

This is already possible, however:

```twig
{{ getenv('FOO') }}/preview/{slug}
```
