### ISSUE TITLE
[Feature request] Ability to get current site's dateCreated

### ISSUE THREAD

**Issue by bertoost** [craftcms/cms#4703]
### Description

When having a multiple-site installation and both sites are created on a different time (especially a different year) then it would be cool to be able to get it's `dateCreated`. This can be used to build a dynamic "copyright {year}" footer for example.
Currently I am using the `craft.app.info.dateCreated` instead, but that's not the same for all sites if you add them later.

### Additional info

- Craft version: 3.2.8
- PHP version: 7.3.8

**Comment by brandonkelly** [comment]
Just added this for the next release (3.2.9) - so this will be possible:

```twig
{{ currentSite.dateCreated|date('Y') }}
```

**Comment by bertoost** [comment]
Cool @brandonkelly ! Thanks
