### ISSUE TITLE
Unable to switch from draft to current version in CP/edit entry

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#4705]
### Description

Since 3.2.8 (I was unable to reproduce this on 3.2.7), I'm experiencing an issue where it isn't possible to toggle back to the current entry version, when viewing a draft.

### Steps to reproduce

1. Create an Entry in a section, and save it
2. Click "Save as a Draft"
3. _Switch back to the current version, and reload the browser_ (alternatively; go back to the Entries index and then re-open the Entry from there)
4. Switch version to the Draft 
5. Attempt to switch back to the current version; Craft will reload but stay on the Draft (the `draftId` GET variable will still be in the URL)

There are no errors in the JS console in devtools.

Here's a quick screencap demonstrating the issue: http://recordit.co/yvYFVdya5u

### Additional info

- Craft version: 3.2.8
- PHP version: 7.2.20
- Database driver & version: MySQL 5.6.43
- Plugins & versions: None

**Comment by brandonkelly** [comment]
Thanks for reporting! Just fixed this for tomorrow’s 3.2.9 release.
