### ISSUE TITLE
EVENT_AFTER_SEARCH not triggered if returning scores

### ISSUE THREAD

**Issue by alexmglover** [craftcms/cms#4710]
### Description

If running a search query that includes scores, EVENT_AFTER_SEARCH hook is not triggered.

### Steps to reproduce

1. Run a search query via Twig template tag, EVENT_AFTER_SEARCH is not triggered.

### Additional info

- Craft version: 3.2.7
- PHP version: 7.2.20
- Database driver & version: 5.6
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for today’s release (3.2.9).
