### ISSUE TITLE
'Updating entry drafts and revisions' Stalled Task

### ISSUE THREAD

**Issue by bymayo** [craftcms/cms#4713]
### Description

The `Updating entry drafts and revisions` task/job is stalled at 0 of 1120 and won't move. I've checked the logs and it seems i'm getting an error about the slug being incorrect format:

```
2019-08-06 10:00:42 [-][1][-][error][craft\queue\QueueLogBehavior::afterError]  [509] Updating entry drafts and revisions (attempt: 1) - Error (time: 0.129s): SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xCE--\xCE--...' for column 'error' at row 1
The SQL being executed was: INSERT INTO `entryversionerrors` (`versionId`, `error`) VALUES (5328, 'SQLSTATE[HY000]: General error: 1366 Incorrect string value: \'\\xCE--\\xCE--...\' for column \'slug\' at row 1\nThe SQL being executed was: INSERT INTO `elements_sites` (`elementId`, `siteId`, `slug`, `uri`, `enabled`, `dateCreated`, `dateUpdated`, `uid`) VALUES (131897, 1, \'using-rsin-Î--Î--a-level-maths-factsheet\', \'resources/using-rsin-Î¸-Î±-a-level-maths-factsheet\', 1, \'2019-08-06 09:00:42\', \'2019-08-06 09:00:42\', \'74695ff6-dbda-4445-bd6a-59c18bf94fa3\')')
```

I tried the steps in https://github.com/craftcms/cms/issues/4688 but this didn't resolve my issue (Other than reduce 4,000+ entries to 1,120) like I hoped it would. But it seems it's because the slug has a unusual character in it:

`Using Rsin (θ + α) - A Level Maths Factsheet`

### Additional info

- Craft version: Craft CMS 3.2.5.1
- PHP version: 7.3
- Database driver & version: MySQL 5.7
- Plugins & versions:

**Comment by brandonkelly** [comment]
Craft 3.2.6 and 3.2.7 both contained fixes for handling entries with unicode characters, so you should have better luck if you update to the latest Craft release first.

**Comment by bymayo** [comment]
@brandonkelly Upgrading to 3.2.9 has fixed my issue 💯

**Comment by brandonkelly** [comment]
Good to hear!
