### ISSUE TITLE
Upgrading to 2.7.10 getting 500

### ISSUE THREAD

**Issue by TerenzeY** [craftcms/cms#4714]
Upgraded to 2.7.10 is giving forever 500 HTTP error?

Memory limit, execution time has already been checked. Any help?

**Comment by Mosnar** [comment]
You'll probably want to provide some additional context here to ensure you get help as quickly as possible.

- What version are you upgrading from?
- What version of PHP are you running?
- Are you on shared or dedicated hosting?
- What plugins are you running?
- Is there anything else particularly interesting about your environment? (i.e., mod_security, Windows, non-standard SQL flavor, etc.)

Additionally, you'll want to provide logs from your logs folder. You can either email these directly to Pixel & Tonic or paste them here, making sure to obfuscate any sensitive info.

**Comment by TerenzeY** [comment]
Looks like its PHP verison needs upgrading.
