### ISSUE TITLE
isSystemLive not accepting env variable

### ISSUE THREAD

**Issue by dwhoban** [craftcms/cms#4715]
### Description
`isSystemLive` does not seem to accept env variables via `getenv()` and marks the system live. 
This works for a range of other settings such as devMode, allAdminChanges and allowUpdates.

### Steps to reproduce

1. Add a env var `IS_SYSTEM_LIVE`
2. set var to `"false"` or `0`
3. add `'isSystemLive' => getenv('IS_SYSTEM_LIVE'),` to `general.php`
4. Log out and visit home page.
5. Site is "up"
6. Create a multi-env config
7. set `'isSystemLive' =>false,`  to the correct environment
8. site "down".

### Additional info

- Craft version: 3.2.8
- PHP version: 7.3.6
- Database driver & version: 10.4.7-MariaDB/MySQL 5.5.5
- Plugins & versions:

**Comment by brandonkelly** [comment]
`isSystemLive` needs to be set to `true` or `false`, but environment variables can only be set to strings. So you will need to do your own typecasting from `general.php` if you want to use an environment variable:

```php
'isSystemLive' => (bool)getenv('IS_SYSTEM_LIVE'),
```

That will result in `false` if `IS_SYSTEM_LIVE` is set to `"0"` or `""`, but `"false"` won’t work, as PHP wouldn’t consider that to be an [“empty”](https://www.php.net/manual/en/function.empty.php#refsect1-function.empty-returnvalues) value.
