### ISSUE TITLE
Cannot set `Content-Type` response header from plugin

### ISSUE THREAD

**Issue by joepagan** [craftcms/cms#4716]
### Description

Cannot set `Content-Type` response header to be anything but `text/html; charset=UTF-8` when hitting a plugin controller action.
Looks similar to: https://github.com/craftcms/cms/issues/1424 but this time in a plugin rather than through a twig template.

### Steps to reproduce

1. Try set `content-type` header in plugin to anything but `text/html`
2. get `text/html`

Example code:

```php
Craft::$app->response->headers
      ->set('Content-Type', 'text/calendar; charset=UTF-8')
      ->set('Content-Disposition', 'attachment; filename="cal.ics"');
```

Curl response `curl -I url`:
```bash
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 06 Aug 2019 15:43:53 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding
Content-Disposition: attachment; filename="cal.ics"
```

Response when dumping `Craft::$app->response->headers` on the controller action:
```bash
object(yii\web\HeaderCollection)#345 (1) {
  ["_headers":"yii\web\HeaderCollection":private]=>
  array(2) {
    ["content-disposition"]=>
    array(1) {
      [0]=>
      string(30) "attachment; filename="cal.ics""
    }
    ["content-type"]=>
    array(1) {
      [0]=>
      string(28) "text/calendar; charset=UTF-8"
    }
  }
}
```

Sets `content-disposition`, but, not `content-type`?

### Additional info

- Craft version: 3.1.28
- PHP version: 7.2

**Comment by brandonkelly** [comment]
Your `Content-Type` header is being overridden by the HTML response formatter.

To get Yii to stop assuming the response is going to be HTML, add this:

```php
Craft::$app->response->format = \yii\web\Response::FORMAT_RAW;
```

Alternatively, it looks like you are trying to respond with a `.ics` file. You can skip overriding the response format and manually setting the `Content-Type` and `Content-Disposition` headers entirely using one of these methods:

Method | Description
-|-
[sendFile()](https://www.yiiframework.com/doc/api/2.0/yii-web-response#sendFile()-detail) | Sends a physical file on the file system
[sendContentAsFile()](https://www.yiiframework.com/doc/api/2.0/yii-web-response#sendContentAsFile()-detail) | Sends a string of file contents as a file

For example:

```php
return Craft::$app->response->sendFile($filePath, 'cal.ics');
```

**Comment by joepagan** [comment]
Thanks for the explanation, I was not aware of this, works great.
