### ISSUE TITLE
[Improvement] Name first Section Entry Type "default" instead of section name

### ISSUE THREAD

**Issue by bertoost** [craftcms/cms#4718]
### Description

When creating a new section, the first auto created Entry Type get's the same name as the section. Which is a little weird. For example; when creating a "News" section, the entries in it will get "News" Entry Type.
My suggestion is to name the first auto created Entry Type to "Default". Because it's the first and initially the only one, "default" is a more applicable name.

### Additional info

- Craft version: 3.2.9
- PHP version: 7.3.2

**Comment by mmikkel** [comment]
My problem with this suggestion is that out of the box, you'd end up with multiple Entry Types having the same name and handle, across different Sections.

We all build sites differently and having multiple Entry Types with the same handle is technically allowed, but I think retaining the current behaviour where Entry Type handles are all initially unique (i.e., the same as their Section's handle) is a more sensible default.

**Comment by bertoost** [comment]
I know what you mean @mmikkel , but as you said; an entry type is in a section. Which has it's own name. So, a "News" section (channel), starting with a "Default" sounds more logical to me than having a "News" Entry Type inside a "News" section.
But I agree that we all build sites differently. Gladly we can rename those things as well.

**Comment by mmikkel** [comment]
I agree that on a conceptual level, having a "Default" Entry Type makes more sense.

But I can also imagine several situations or use cases where having 20 different Entry Types all named `default`, would be a problem (or at least, a source of confusion or frustration) :)

**Comment by bertoost** [comment]
Yeah I can imagine too. Therefore you probably wil not have multiple Entry Types with the name "Default" in one Section ;-) and it's just to start with, you can change. Only in those situations where you just have one, a "Default" sounds better to me.

**Comment by brandonkelly** [comment]
I’m considering separating sections from entry types in Craft 4 (#4724 – please comment there if you have any thoughts!). If that happens then this obviously wouldn’t make any sense.

**Comment by SHoogland** [comment]
This ("default" named entry types) seems to be implemented in craft 4, although I strongly agree with the concern of multiple default named entry types in my projects right now... can somebody point me to where this decision has been made? So I can maybe understand it? (or oppose it)

**Comment by brandonkelly** [comment]
Doh, this was implemented in 3.7 per #7078. I didn’t realize it was a duplicate at the time.

My previous comment still stands though: entry types are going to be decoupled from sections in Craft 4, so creating a new section will no longer automatically create a new entry type. No more `default` handles.
