### ISSUE TITLE
cannot run migrations, because of missing table

### ISSUE THREAD

**Issue by krizzzly** [craftcms/cms#4720]
### Description

Database is broken after update, cannot run page or control panel

```
kv-imac-web-04:test Christian$ php -d memory_limit=-1 craft update all
Fetching available updates ... done
Performing one update:

    - craft 3.1.34.2 => 3.2.9

Backup the database? (yes|no) [yes]:no
Skipping database backup.
Performing update with Composer ... done
Applying new migrations ... error: The command "'/www/test/craft' 'migrate/all' '--no-content'" failed.

Exit Code: 1(General error)

Working directory: /www/test

Output:
================


Error Output:
================
Exception 'yii\db\Exception' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test.drafts' doesn't exist
The SQL being executed was: SELECT `e`.`draftId`, `e`.`type`
FROM `elements` `e`
INNER JOIN `drafts` `d` ON `d`.`id` = `e`.`draftId`
WHERE (`d`.`sourceId` IS NULL) AND (`e`.`dateCreated` < '2019-07-08 09:38:32')'

in /www/test/vendor/yiisoft/yii2/db/Schema.php:664

Error Info:
Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'test.drafts' doesn't exist
)

Stack trace:
#0 /www/test/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'SELECT `e`.`dra...')
#1 /www/test/vendor/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('SELECT `e`.`dra...')
#2 /www/test/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /www/test/vendor/yiisoft/yii2/db/Query.php(237): yii\db\Command->queryAll()
#4 /www/test/vendor/craftcms/cms/src/db/Query.php(162): yii\db\Query->all(NULL)
#5 /www/test/vendor/craftcms/cms/src/services/Drafts.php(303): craft\db\Query->all()
#6 /www/test/vendor/craftcms/cms/src/services/Gc.php(59): craft\services\Drafts->purgeUnsavedDrafts()
#7 /www/test/vendor/craftcms/cms/src/base/ApplicationTrait.php(1333): craft\services\Gc->run()
#8 /www/test/vendor/craftcms/cms/src/console/Application.php(65): craft\console\Application->_postInit()
#9 /www/test/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
#10 /www/test/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#11 /www/test/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#12 /www/test/vendor/craftcms/cms/src/console/Application.php(54): yii\console\Application->__construct(Array)
#13 [internal function]: craft\console\Application->__construct(Array)
#14 /www/test/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#15 /www/test/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\console\\A...', Array, Array)
#16 /www/test/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\console\\A...', Array, Array)
#17 /www/test/vendor/craftcms/cms/bootstrap/bootstrap.php(248): yii\BaseYii::createObject(Array)
#18 /www/test/vendor/craftcms/cms/bootstrap/console.php(34): require('/www/test...')
#19 /www/test/craft(21): require('/www/test...')
#20 {main}
```

### Steps to reproduce

1. $ php -d memory_limit=-1 craft update all.

### Additional info

- Craft version: 3.1.34.2
- PHP version: 7.2.20
- Database driver & version: mysql 5.7
- Plugins & versions: 

    "craftcms/cms": "3.1.34.2",
    "vlucas/phpdotenv": "^2.4.0",
    "barrelstrength/sprout-notes": "2.2.3",
    "ether/logs": "3.0.1",
    "lucasbares/craft-emailobfuscator": "^2.1.0",
    "aelvan/preparse-field": "v1.0.7",
    "supercool/buttonbox": "^2.0",
    "marionnewlevant/picture": "^2.2",
    "verbb/default-dashboard": "^1.0",
    "wrav/oembed": "^1.1.6",
    "smalot/pdfparser": "^0.14.0",
    "putyourlightson/craft-campaign-pro": "^1.0.0",
    "putyourlightson/craft-campaign": "1.10.1",
    "superbig/craft3-templateselect": "^2.0",
    "vaersaagod/matrixmate": "^1.1.4",
    "topshelfcraft/spreadsheet-tools": "3.0.0-beta.1",
    "vaersaagod/seomate": "1.0.7",
    "solspace/craft-freeform": "3.2.4"

**Comment by krizzzly** [comment]
happens when updating to 3.2.0, in 3.2.0 vendor/craftcms/cms/src/migrations/m190312_152740_element_revisions.php 
is added inbetween older migrations. This migration is adding the 'drafts' table. The last migration of 3.1.34.2 is m190502_122019_store_default_user_group_uid.php

**Comment by krizzzly** [comment]
problem is, before i can run the migrations, the garbage collector now from 3.2.0 on wants to ```        Craft::$app->getDrafts()->purgeUnsavedDrafts();``` but there is no drafts table yet.

**Comment by krizzzly** [comment]
**SOLVED**

in app.php i have configured: 

```
    'components' => [
        'gc' => [
            'probability' => 1000000, // 1 in 1
        ]
    ]
```
to avoid elements going to garbage collection.
This will make the migration to 3.2.0 fail.

**Comment by brandonkelly** [comment]
@krizzzly To avoid garbage collection from happening automatically, you need to set `probability` to `0`, not `1000000`.

**Comment by krizzzly** [comment]
sorry my explanation was misleading. The configuration will set the possibility for garbage collection to be run to at a chance of 100000 / 100000 * 100 % - so actually after each request. Elements get deleted right away. Is there another way to achieve that?

**Comment by brandonkelly** [comment]
Gotcha – I wouldn’t recommend doing that as it would add a performance drain to each request.

If you want to ensure it is getting run regularly, set it to `0` and then set up a cron job to run every minute that runs the `./craft gc` command.

**Comment by krizzzly** [comment]
```./craft gc``` wants me to confirm with yes|no, is there a way to get around that ?

**Comment by krizzzly** [comment]
```./craft gc/run --deleteAllTrashed``` ?

**Comment by brandonkelly** [comment]
Only do that if you want to delete trashed elements _immediately_ rather than letting them sit in the trash for 30 days. I would **not** recommend you create a Cron job that includes that option, unless you are setting `--delete-all-trashed=0` to explicitly avoid it.

If you really want trashed items to be removed quicker, maybe modify your [softDeleteDuration](https://docs.craftcms.com/v3/config/config-settings.html#softdeleteduration) config setting to a shorter value, like `'P1D'` (one day).

**Comment by krizzzly** [comment]
still i think its a bug, because i still run (with a certain posibility) into garbage collector, which will cause the migration to fail, because craft doesnt have to 'drafts' table yet at that moment.

vendor/craftcms/cms/src/services/Gc.php:55

        if (!$force && mt_rand(0, 1000000) >= $this->probability) {
            return;
        }

**Comment by brandonkelly** [comment]
Are you still running Craft 3.1.34.2 ? The `drafts` table wasn’t added until 3.2.0.

**Comment by krizzzly** [comment]
yes the error happens when updating from the last version of 3.1 to 3.2

**Comment by brandonkelly** [comment]
Ah, I understand now. Just fixed this for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#ddd75cdd0ab15b425fddaeabceb62f35af999f58 as 3.2.10",
  "...": "..."
}
```

Then run `composer update`.
