### ISSUE TITLE
Use of undefined constant IDNA_NONTRANSITIONAL_TO_ASCII - assumed 'IDNA_NONTRANSITIONAL_TO_ASCII'

### ISSUE THREAD

**Issue by evjohns** [craftcms/cms#4722]
### Description
Error in:
/vendor/craftcms/cms/src/web/Request.php

line 1157:
if (
                !empty($parsed['host']) &&
                $hostName &&
                $parsed['host'] !== $hostName &&
                (
                    !function_exists('idn_to_ascii') ||
                    idn_to_ascii($parsed['host'], IDNA_NONTRANSITIONAL_TO_ASCII, INTL_IDNA_VARIANT_UTS46) !== $hostName
                )
            ) {
                continue;
            }

Error:

Use of undefined constant IDNA_NONTRANSITIONAL_TO_ASCII - assumed 'IDNA_NONTRANSITIONAL_TO_ASCII'

### Steps to reproduce

1. Set the sites base domain and then visit a different domain.
e.g. set base domain to example.com then visit www.example.com

### Additional info

- Craft version: Craft Pro 3.2.9
- PHP version: 7.1.31
- Database driver & version: MySQL 5.5.62
- Plugins & versions:

Amazon S3: 1.2.5
Redactor: 2.3.3.2
Supertable: 2.2.1
Amazon S3: 1.0.9

**Comment by brandonkelly** [comment]
Just fixed this for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#259297cd890398c3ac16946b7c898b2ad040dbbe as 3.2.9",
  "...": "..."
}
```

Then run `composer update`.
