### ISSUE TITLE
FR: native healthcheck controller

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#4723]
Having a healthcheck url that returns proper http status code is an pretty standard requirement for any scalable/distributed app deployment.

Would be great if Craft had this natively (there are some older plugins around).

Will work on a simple PR if you'll consider it.

**Comment by brandonkelly** [comment]
Sure!

**Comment by timkelty** [comment]
On second thought…it's probably just as easy to have a `status` template or whatever that has your success response, and rely on Craft to serve error codes/templates when the system is down.
