### ISSUE TITLE
Deleting a matrix block does not trigger draft save

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#4727]
### Description

When deleting a matrix block, the modified draft appears not to be saved, content is still visible in preview for example, a 'leave page warning' is shown when navigating away from the page.

However, the draft is saved when you click somewhere else on the page (shifting focus i assume).

Thanks.

### Steps to reproduce

1. see above, using both Chrome 75 and Firefox

### Additional info

- Craft version: 3.2.9 
- PHP version:
- Database driver & version:
- Plugins & versions: Element Api 2.6.0

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just fixed for the next release.
