### ISSUE TITLE
"Element X could not be duplicated for site Y" when saving an entry from a draft

### ISSUE THREAD

**Issue by benface** [craftcms/cms#4733]
### Description

I have this site with a custom module that I am updating from Craft 3.1 to 3.2, and I'm running into this old issue, which seems to be back with the new draft/revision system: https://github.com/craftcms/cms/issues/2237

My module has this event handler to prevent the CP user from adding entries with the same title in a given section:

```php
// Prevent duplicate items
Event::on(
    Entry::class,
    Entry::EVENT_BEFORE_SAVE,
    function(craft\events\ModelEvent $event) {

        $entry = $event->sender;
        $section = $entry->section->handle;

        // Only continue if we have the right section and if the entry is not a draft or a revision
        if ($section !== 'items' || ElementHelper::isDraftOrRevision($entry)) {
            return;
        }

        // If another item with the same title exists, fail validation
        if (Entry::find()->section($section)->status(null)->title($entry->title)->id(['not', $entry->id])->one()) {
            $event->isValid = false;
            $event->sender->addError('title', Craft::t('module', 'There is already an item with that name.'));
        }

    }
);
```

(Notice that I added a `ElementHelper::isDraftOrRevision($entry)` check for Craft 3.2.)

It works well when updating an existing entry (i.e. not from a draft): it correctly refreshes the page with a "Couldn't save entry" notification at the top, and the title field is highlighted with an error message ("There is already an item with that name") .

The problem occurs when first creating an entry (saving from the "first draft"), or when updating an existing entry from a draft. I am not talking about saving drafts; those events bypass the validation (due to the `return` in the `ElementHelper::isDraftOrRevision($entry)` condition) and that's fine. But when trying to save an actual entry from a draft, instead of the page refreshing with a user-friendly error, I get a Craft exception:

```
craft\errors\InvalidElementException: Element 17827 could not be duplicated for site 1 in vendor/craftcms/cms/src/services/Elements.php:948
Stack trace:
#0 vendor/craftcms/cms/src/services/Drafts.php(245): craft\services\Elements->duplicateElement(Object(craft\elements\Entry), Array)
#1 vendor/craftcms/cms/src/controllers/EntryRevisionsController.php(385): craft\services\Drafts->applyDraft(Object(craft\elements\Entry))
#2 [internal function]: craft\controllers\EntryRevisionsController->actionPublishDraft()
#3 vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#5 vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('publish-draft', Array)
#6 vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('publish-draft', Array)
#7 vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('entry-revisions...', Array)
#8 vendor/craftcms/cms/src/web/Application.php(566): craft\web\Application->runAction('entry-revisions...', Array)
#9 vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#10 vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#11 public/index.php(21): yii\base\Application->run()
#12 {main}
```

### Steps to reproduce

1. Have a section with the handle `items`, and have the code above in a module.
2. Create a new entry in that section with the title "Test".
3. Create another entry in the same section with the same title.
4. Boom!

### Additional info

- Craft version: 3.2.9
- PHP version: 7.3.7
- Database driver & version: MySQL 5.7.26
- Plugins & versions: All disabled

**Comment by brandonkelly** [comment]
This is happening because by the time you are adding a validation error, Craft has already been given the green light to create/update the entry based on the draft.

Just updated Craft to be prepared for the possibility that the entry will get validation errors even though the draft did not, so this error is avoided, and validation errors on the entry are even copied back over to the draft before the edit form is re-rendered.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#7e67261322e3fd25d27a9c7a8db51b614f537905 as 3.2.9",
  "...": "..."
}
```

Then run `composer update`.

**Comment by benface** [comment]
Thank you! ❤️
