### ISSUE TITLE
$isNewElement is true for excisting elements

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#4734]
### Description
In `Elements::EVENT_AFTER_SAVE_ELEMENT`, the `$isNew` value is set to true for elements that aren't new anymore.

### Steps to reproduce

1. Add an eventlistener for `Elements::EVENT_AFTER_SAVE_ELEMENT` and dump `$event`
2. Create a new entry
3. Save an excisting entry
4. `$event->isNew` will be true for both

### Additional info

- Craft version: 3.2.9
- PHP version: 7.2.1
- Database driver & version: 5.7

**Comment by brandonkelly** [comment]
You are probably looking at the entry revision that is being created.

If you want the event handler to ignore drafts and revisions, add this to your event handler:

```php
if (\craft\helpers\ElementHelper::isDraftOrRevision($event->element)) {
    return;
}
```
