### ISSUE TITLE
Garbage collection times out if there are a lot of issues

### ISSUE THREAD

**Issue by alexmglover** [craftcms/cms#4735]
### Description

I have a site with a lot of trashed elements (~1 million) which I think are related to feedme, but I can't run the gc/run without it timing out. I think it probably makes sense to queue up the deletions and batch run them.

### Steps to reproduce

1. Have lots of elements in the database that.
2. Attempt to run gc/run cli.

### Additional info

- Craft version: 3.2.8
- PHP version: 7.2
- Database driver & version: Maria DB

**Comment by brandonkelly** [comment]
I just improved the way search indexes are cleaned up, which was most likely the main culprit here.

To get the change  early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#5a8988c03376b5ec3e098d96a8b0804efda00924 as 3.2.9",
  "...": "..."
}
```

Then run `composer update`, and try running `./craft gc` again.
