### ISSUE TITLE
Export button not working

### ISSUE THREAD

**Issue by edwardpmartinez** [craftcms/cms#4737]
### Description
The export button is not working. Tried to export entries and users but no file is downloaded. Here's a screenshot of the export button:

<img width="232" alt="Screen Shot 2019-08-10 at 3 47 45 PM" src="https://user-images.githubusercontent.com/7778861/62819332-45a58d00-bb86-11e9-998c-fd6ccc4e58ee.png">

### Steps to reproduce

1. Click on the checkbox of any element
2. Click on the export button. Leave the limit blank
3. After clicking the export button, the user is redirected to the dashboard

### Additional info

- Craft version: 3.2.8
- PHP version: 7.2.17
- Database driver & version: MYSQL
- Plugins & versions: Latest version of Craft Commerce

**Comment by brandonkelly** [comment]
It’s working on my end. Are you getting any JavaScript errors on the page?

**Comment by edwardpmartinez** [comment]
I was able to identify the cause of the issue. If there is a value for "tokenParam", the export button doesn't work. In this particular site, I set a value for "tokenParam" because it uses PayPal for checkout. 

Is there a way to make the export button work even with a value for "tokenParam"?

From: https://github.com/craftcms/commerce-paypal
> If you're going to use the PayPal Express payment gateway you are required to change the default value of tokenParam in your Craft config
> Choose any different token name other than token, for example you could put craftToken. Otherwise redirects from PayPal will fail.

**Comment by brandonkelly** [comment]
Doh! Thanks, fixed that for today’s 3.2.10 release.

**Comment by edwardpmartinez** [comment]
Thank you, @brandonkelly  :)
