### ISSUE TITLE
Feature Request: Tab instructions

### ISSUE THREAD

**Issue by carl-evans** [craftcms/cms#4738]
I'd love to add tab instructions for certain tabs to make it easier for people to understand how entries' tabs - not just fields - relate to the website's rendered content. Something like this:

<img width="668" alt="Screenshot 2019-08-10 at 11 36 03" src="https://user-images.githubusercontent.com/32574150/62820960-3f061e00-bb64-11e9-82da-a041062e267d.png">

Obviously with more whitespace around the instruction.

**Comment by mildlygeeky** [comment]
Wondering if something like an info window popup / modal on the tab title itself might be a cleaner way of implementing. Regardless, I could see content authors appreciating something like this.

**Comment by davidhellmann** [comment]
@mildlygeeky sounds not mobile friendly. But maybe the info can be a toggle to show / hide.

**Comment by brandonkelly** [comment]
The next Craft 3.5 release features a new field layout designer with the ability to add headings, tips, and warnings, among other things. So if you want to give a tab custom instructions, just add a tip to the top of it. (See #1138 and #4647.)

**Comment by beckysolomon** [comment]
@brandonkelly  Is there a way to use HTML tags inside a tip?  I want to add a link to a certain page of the CMS from the tip but HTML tags don't seem to render. I thought maybe that's what was meant by "Can contain Markdown formatting."

**Comment by brandonkelly** [comment]
@beckysolomon You can add Markdown-formatted text, which will be rendered as HTML within the edit page.

What sort of HTML are you hoping to add?

**Comment by beckysolomon** [comment]
@brandonkelly I thought "Markdown" meant HTML but realized my mistake. I figured it out using https://daringfireball.net/projects/markdown/ Thanks.
