### ISSUE TITLE
.env ENVIRONMENT value is too important to be cached

### ISSUE THREAD

**Issue by TC72** [craftcms/cms#4741]
I've just run into a problem because of the ENVIRONMENT value in craft/.env being cached. Long story short the SEOMatic plugin uses this value to automatically add a tag telling search engines to ignore the site if it's in a development state. I've posted what happened here:
[https://github.com/nystudio107/craft-seomatic/issues/454](url)

The problem was made more difficult to catch because Craft is caching the ENVIRONMENT variable. Even after I'd fixed the value for SEOMatic the plugin wasn't able to see the change until I cleared the Craft cache.

A value like this seems too important to be cached.

**Comment by brandonkelly** [comment]
Craft doesn’t cache that anywhere.
