### ISSUE TITLE
app translation file for Danish language - rogue characters

### ISSUE THREAD

**Issue by i-just** [craftcms/cms#4744]
### Description
There are some rogue characters in the app.php translation file for Danish language (`vendor/craftcms/cms/src/translations/da/app.php`). Lines 800 & 802 (screenshot attached). They're making a site in Danish error with a message of "An internal server error occurred." and the attached screenshot when in dev mode.
![Screen Shot 2019-08-12 at 13 24 59](https://user-images.githubusercontent.com/4500340/62864811-9e029900-bd04-11e9-937f-859dc61e1766.png)
<img width="1249" alt="Screen Shot 2019-08-12 at 12 57 20" src="https://user-images.githubusercontent.com/4500340/62864818-a2c74d00-bd04-11e9-9913-31c6647fff8e.png">

Temporarily fixed by removing those characters.

### Steps to reproduce

1. set you site language to Danish (da)
2. visit the homepage in your browser

### Additional info

- Craft version: 3.2.9
- PHP version: 7.1.23
- Database driver & version: MySQL 5.5.5
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
Thanks for pointing this out. Looks like it was already fixed by 9337a81d78df8d194b038264d116eb1e106dc222 which will be in 3.2.10.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#d1af4ff955d806f32ed338e58f6701133d6cdd08 as 3.2.9",
  "...": "..."
}
```

Then run `composer update`.
