### ISSUE TITLE
Elements with a `0` as title show with their database ID as title in overview

### ISSUE THREAD

**Issue by m-rsmn** [craftcms/cms#4745]
### Description
When you create an entry with as title `0`, it will show in the overview list in the control panel with it's database ID as title. 

This happens also with custom elements & assets. When you try to create a new user with a `0` as username , it will display as  `craft\elements\User` in the overview,  which also does not seem right. 

### Steps to reproduce

1. Clean craft install (3.2.9)
2. Create section, no fields needed as this regards the title
3. Go to entries, create a new one with `0` as title
4. Go to section overview and the new entry will have it's database ID as title

### Additional info

- Craft version: 3.2.9
- PHP version: 7.x
- Plugins & versions: /

**Comment by brandonkelly** [comment]
Thanks for reporting that! It’s been fixed for the next release.
