### ISSUE TITLE
Category selection fields on multi-site don't show Categories from expected site

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#4749]
### Description
I'm not positive, but I don't think this is intended behavior. We have a multi-site install with a "Products" entries set. These products are propagated across both sites. We also have a category group for "Product Categories" with a field on products set to "Manage relations on a per-site basis"

Some categories have different names on the different sites. If I go to our main site's CP, say, www.siteA.com/admin and go to edit a product entry in Site B and I click to add a category, I am presented with the category names from Site A. If I select one and save the entry, it normalizes and appears with the correct site B category assigned.

If I access the CP from siteB.com/admin, I see the category titles from Site B as expected.

### Steps to reproduce

1. Create entries propagated to two sites
2. Create a category group and a category field localized by site and assign it to the entries above
3. Create some categories, change the names in the different sites
4. Try to edit an entry on the non-primary site and add a category. See category names are not from the correct site.

### Additional info

- Craft version: 3.2.9
- PHP version: 7.2.x
- Database driver & version: MySQL
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
Yeah this is expected. Since your Categories field isn’t set to only relate categories from a specific site (from what I can tell), it doesn’t really matter which site you see in the Control Panel – all that really matters is which element you select.

There is a site menu in the category selection modal; you can use that to change which site the categories are being queried from within there if it will help you find the right category to select. Craft is just defaulting to the current site.

**Comment by Mosnar** [comment]
Hmm, not seeing the site switcher. Here's my field configuration:

![image](https://user-images.githubusercontent.com/3810939/62948918-43744600-bdb3-11e9-89ad-b18824c6950f.png)

I created a new category called "Test (Site A)" and renamed it to "Test (Site B)" on site B. 

And here's what I see when I go to add a category:
![image](https://user-images.githubusercontent.com/3810939/62949349-09577400-bdb4-11e9-9679-1b57c9e43d8c.png)

**Comment by brandonkelly** [comment]
Doh, you’re right. Pushing a fix…

**Comment by brandonkelly** [comment]
And fixed for today’s 3.2.10 release.
