### ISSUE TITLE
Multi-site entry fields no longer default to current site

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/cms#4751]
### Description

Since updating to 3.2 we've noticed that entry field queries no longer default to returning entries for the current site if one is not provided. We are now seeing entries returned for the sites they are enabled for, even though this goes against the documented behaviour.

We've managed to narrow this down to the changes that were made to `fields/BaseRelationField.php` on the 23rd of April.

https://github.com/craftcms/cms/commit/d8e579b8533259cb42ff3aad3785572be81a7080#diff-5a27a6a2e45a0d9be235d44e3d97baec

<img width="224" alt="Screen Shot 2019-08-13 at 15 38 44" src="https://user-images.githubusercontent.com/24975058/62951400-d4621600-bde1-11e9-8561-c9829fa54e49.png">

In our case, only 'Somnus' was (correctly) returned when we were using 3.1 - since updating to 3.2 we are seeing all four entries being returned in the templates, each for the site they are enabled on.

- Craft version: 3.2.9

**Comment by brandonkelly** [comment]
This is expected behavior as of Craft 3.2. You can force your field to only return entries that are enabled for the current site by doing this:

```twig
{% for related in entry.myEntriesField.site(currentSite).all() %}
```

**Comment by lukeyouell** [comment]
Is there a reason this wasn't documented anywhere? 

The current docs state that the current site is still used by default, even though this is no longer the case. 

https://docs.craftcms.com/v3/dev/element-queries/entry-queries.html#site

**Comment by brandonkelly** [comment]
Normal entry queries are still going to only give you entries in the current site by default, but if you are going through an Entries field, that has never been a stock entry query:

https://docs.craftcms.com/v3/entries-fields.html#working-with-entries-field-data

**Comment by gilleard** [comment]
Some quick thoughts on this @brandonkelly - think this needs some more thought:

- I'm really surprised disabled entries are expected to be returned by a default field query now, this doesn't seem consistent with the rest of Craft and definitely feels like something that should have been made clearer in the release notes
- The Entries field docs you referenced still states under [Multi-Site Settings](https://docs.craftcms.com/v3/entries-fields.html#multi-site-settings) that "_If disabled, related entries will always be pulled from the current site._" which is no longer the case
- `entry.<FieldHandle>.all` and `entry.<FieldHandle>.site(null).all` should return the same entries surely?
- This would be solved by the new unique param logic respecting entry status for the current site

Ultimately this change is going to require us to update all our existing entry field calls - I'd have thoght we won't be the only ones.

For reference, here's our setup that's lead to this issue:

- Multi-site install
- Entries field with "relate entries from a specific site?" disabled
- Relating to entries that propagate
- Retrieving entries in template without setting the `siteId` param

**Comment by brandonkelly** [comment]
Good points, I’ll look into altering the behavior.

**Comment by brandonkelly** [comment]
Alright, reverted that change for the next release (3.2.11). Going forward, if you want to include relations across all sites, you will need to set the `siteId`, `preferSites`, and `unique` params yourself:

```twig
{% set related = entry.myEntriesField
    .siteId('*')
    .preferSites([entry.siteId])
    .unique()
    .all() %}
```
