### ISSUE TITLE
Plugin subnav menus to allow optional badge counts

### ISSUE THREAD

**Issue by matt-adigital** [craftcms/cms#4756]
### Feature Request!
Can we please have badge counts on subnav items? Noticed that we can have them on the main plugin item, and in sidebars, but not on subnavs. This could be an optional array key which is ignored if left blank.

https://github.com/craftcms/cms/blob/66e16f7f7a2bfaa0af97196c77c41a8346328db1/src/templates/_layouts/cp.html#L150

Updating the above code wrap the text in a span with class of label and then checking for item.badgeCount in a condition to add a span with class of badge would enable this. Then in our plugin where we set our subnav label and url we can easily just define a badgeCount also.

This would be a handy option to have where we are using subsections within plugins along with sidebars like so:

<img width="449" alt="Screenshot 2019-08-14 at 16 18 20" src="https://user-images.githubusercontent.com/15085874/63033223-2f157380-beaf-11e9-8132-bb840f810958.png">

The sidebar counters are already possible but the subnav ones aren't. Not sure if theres an explicit reason for this but could it please be added? Thank you.

**Comment by brandonkelly** [comment]
This has been implemented for Craft 3.3!
