### ISSUE TITLE
Fulltext search fails to find entries

### ISSUE THREAD

**Issue by croxton** [craftcms/cms#4763]
### Description
After upgrading a site from a Craft 2 a Craft 3 I noticed that searches for some entry titles in the CP (and front end search) return no results. 

For example an entry with the title `Five Little Pigs` cannot be found. Searching for `Five` or `Little` also returns no results. Searching for "Pigs" however _does_ return the entry.

Looking deeper it seems that a Craft 3 search for our phrase yields this fulltext search query:

```sql
SELECT * FROM `craft_searchindex` 
WHERE MATCH(`keywords`) AGAINST('+five* +little* +pigs*' IN BOOLEAN MODE) 
AND `siteId` = '1' 
AND `elementId` IN (...)
```

Whereas in Craft 2 this query successfully returns the entry:
```sql
SELECT * FROM `craft_searchindex` 
WHERE (`keywords` LIKE '% five %') 
AND (`keywords` LIKE '% little %') 
AND MATCH(`keywords`) AGAINST('+pigs' IN BOOLEAN MODE)
AND `locale` = 'en' 
AND `elementId` IN (...)
```

I adapted the Craft 2 query and ran it on the Craft 3 database, in order to eliminate problems with the search index itself. This query successfully returned the entry:

```sql
SELECT * FROM `craft_searchindex` 
WHERE (`keywords` LIKE '% five %') 
AND (`keywords` LIKE '% little %') 
AND MATCH(`keywords`) AGAINST('+pigs' IN BOOLEAN MODE)
AND `siteId` = '1' 
AND `elementId` IN (...)
```

### Steps to reproduce

1. Create an entry with the title `Five Little Pigs`
2. Search for the phrase `Five Little Pigs` in the CP entries listing screen - no results found.

### Additional info

- Craft version: 3.2.9
- PHP version: 7.1
- Database driver & version: PHP 5.7.20
- `searchindex` table set to MySIAM and `ft_min_word_len` = 4

**Comment by croxton** [comment]
It's the default MyISAM fulltext stopwords that is the problem: 
https://dev.mysql.com/doc/refman/8.0/en/fulltext-stopwords.html

It can be changed or disabled by setting `ft_stopword_file` in `my.cnf`, restarting MySQL and then repairing each table that uses fulltext indexes. Which is rather a PITA to be honest, and may not be possible for many production environments.

In Craft 2 it looks like you had a specific workaround for this issue in the search service, whereby each word was compared to a hardcoded list of stopwords. If a word was found to be a stopword you added it as a `WHERE ... LIKE` instead of including it in the fulltext search (as per queries in first post).

That's not exactly elegant but it certainly worked! Please can we have it back? And make the list of stopwords configurable, so if we do have the ability to change the stopwords file for the MySQL server we can change it?

**Comment by angrybrad** [comment]
@croxton The reason it was changed in the first place was that some people were relying on the MySQL server's stopword list and didn't want Craft interfering with it at the application level.

Ultimately, I think the proper solution for stuff like this will be https://github.com/craftcms/cms/issues/833
