### ISSUE TITLE
Can't export users

### ISSUE THREAD

**Issue by edwardpmartinez** [craftcms/cms#4771]
### Description
When trying to use the export feature on users, this error appears:

Database Exception – yii\db\Exception
SQLSTATE[HY000]: General error: 1 Can't create/write to file '/tmp/*****' (Errcode: 13 - Permission denied)

Initially, I tried to treat this as a MYSQL issue. I set the right permissions for the /tmp folder and disabled AppArmor, but the error still persists.

### Steps to reproduce

1. Go to users
2. Check one user
3. Click on export button
4. Error appears

### Additional info

- Craft version: 3.2.10
- PHP version: 7.2.11
- Database driver & version: MySQL 5.7.24
- Plugins & versions:

Activity Log	1.0.1
Cookie Consent Banner	1.1.6
Cookies	1.1.11
Craft Commerce	2.1.11
Delete Account	1.0.2
Element API	2.6.0
Inlin	2.1.1
Instagram Feed	1.0.2
Logs	3.0.1
Minify	1.2.9
PayPal for Craft Commerce	2.1.0.1
Position Fieldtype	1.0.14
Postmark	2.0.2
QARR	1.1.8
Redactor	2.3.3.2
SEO	3.6.2
Sprout Reports	1.2.6
Typogrify	1.1.18

**Comment by angrybrad** [comment]
What are the permissions on the `/tmp` folder, what user:group owns it and what user:group is your web server running under?

**Comment by edwardpmartinez** [comment]
Hi @angrybrad, I'm using a Vagrant box for local development (Laravel Homestead). But the error also appears on the production side. When I export other elements (entries, assets, etc.), it works fine. But when I export anything that includes users — users and Sprout reports — that error appears. 

To answer your questions:
The /tmp folder
(1755/drwxr-xr-t)  Uid: ( 1000/ vagrant)   Gid: ( 1000/ vagrant)

The user group that Nginx is running as is vagrant:vagrant

**Comment by angrybrad** [comment]
@edwardpmartinez can you share the full stack trace leading up to that error?  I'm not able to reproduce, but my guess is it's a side-effect of one of the plugins you've got installed.

**Comment by edwardpmartinez** [comment]
I apologize for this error. I was able to fix this issue by creating a new temp folder, setting its permissions to 1777, changing the MySQL tmp folder location, and restarting MySQL. My apologies for attributing this bug to Craft.

**Comment by angrybrad** [comment]
No worries, @edwardpmartinez!
