### ISSUE TITLE
SiteUrl removes array params

### ISSUE THREAD

**Issue by gijsstegehuis** [craftcms/cms#4778]
### Description
When using `UrlHelper::siteUrl()`, passing params as a string containing an array param will maintain only one of the array's values.

### Steps to reproduce

E.g. `UrlHelper::siteUrl('some/path', 'param1=x&param2[]=y&param2[]=z')` would result in `http://localhost/some/path?param1=x&param2[]=z`.

Expected result: `http://localhost/some/path?param1=x&param2[]=y&param2[]=z`.

### Additional info

- Craft version: 3.2.10
- PHP version: 7.3.7

**Comment by brandonkelly** [comment]
Thanks for reporting this! Just fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#92fa26c2b379564beaa27070895078e53a015b04 as 3.2.10",
  "...": "..."
}
```

Then run `composer update`.
