### ISSUE TITLE
Reorganizing site groups will delete Matrix blocks on edited sites after changing propagation method

### ISSUE THREAD

**Issue by elfacht** [craftcms/cms#4779]
### Description

When site groups are renamed and sites are moved to another site group, Matrix blocks will be removed immediatly from the entries of the edited site(s) when the propagation method will be changed from **Save blocks to all sites the owner element is saved in** to **Save blocks to other sites in the same site group**.  And it can't be undone by changing the method back. This will not happening after saving the entry, but as soon it's open.

I experienced this issue after setting up an international website where we've created the content with similiar blocks for every page. This was very convenient while working with multiple languages and countries. When it was done we changed the popagation method to add indiviual blocks to certain language pages. Reorganising the site groups was mandatory due structure changes.

### Steps to reproduce

1. Create two sites, i.e. `global` and `italy`
2. Create a Matrix field with a simple text block. Set propagation method to **Save blocks to all sites the owner element is saved in**.
3. Create a section with that field, edit the entry and add a block. Save it across both pages.
4. Create a site group, i.e. `Europe` and move `italy` to that group.
5. Change propagation method of the Matrix field to **Save blocks to other sites in the same site group**. Wait until the "Resaving Matrix field" task is done.
6. Open the entry, switch to `italy` to see the missing block(s).

I've tested it with a clean install without any plugins. The expected behaviour would be that the blocks will be untouched unless they would be edited or changed by the author. I guess the `resave/matrix-block` will cause this issue. On an existing site with plenty of pages and blocks this is not a minor issue. 

### Additional info

- Craft version: 3.2.10

**Comment by brandonkelly** [comment]
This is the same issue as you reported in #4731 right?

From reading your steps to reproduce, it seems like everything is working as expected to me.

When you change the Propagation Method from “Save blocks to all sites the owner element is saved in” to “Save blocks to other sites in the same site group”, you are telling Craft to save blocks in _less_ sites. If Italy is in a different group than the rest, the blocks are going to be dropped from it.

I don’t see why you would expect nothing to change until the author does something, when you have explicitly told Matrix to stop saving blocks across all sites, as it had been doing before.

**Comment by brandonkelly** [comment]
I’ve added warnings to sections’ and Matrix fields’ Propagation Method settings, when there’s a good chance that changing the setting will result in data loss.

<img width="405" alt="Propagation Method setting with a data loss warning" src="https://user-images.githubusercontent.com/47792/63595706-70bcb300-c56e-11e9-84a2-ff4b7212f381.png">

Hopefully that will help avoid this in the future.

**Comment by elfacht** [comment]
@brandonkelly 

> I don’t see why you would expect nothing to change until the author does something, when you have explicitly told Matrix to stop saving blocks across all sites, as it had been doing before.

We built a multi-language page with multiple country pages where pages could have the same content across all sites while other pages are available in certain country version. We built the global sites pretty fast with the option **Save blocks to all sites the owner element is saved in**. Changing it afterwards to site groups works for shure. But if we have to stick with the site groups we've created in the beginning then we just expected a huge warning that says: *If you move this site into another group or rename the group, you will lose your Matrix data!*. Especially when it's happening right on with no undo. This is what we've just experienced.

**Comment by elfacht** [comment]
> I’ve [added](https://github.com/craftcms/cms/commit/eff99ca1ac443f6cbf4c06442b3575c14e77256e) warnings to sections’ and Matrix fields’ Propagation Method settings, when there’s a good chance that changing the setting will result in data loss.
> 
> <img alt="Propagation Method setting with a data loss warning" width="405" src="https://user-images.githubusercontent.com/47792/63595706-70bcb300-c56e-11e9-84a2-ff4b7212f381.png">
> 
> Hopefully that will help avoid this in the future.

Putting this warning to the sites section when you try to rename a group or move a site to another would be helpful to. This is where the magic happened …

**Comment by brandonkelly** [comment]
Ah good call, just added that as well.
