### ISSUE TITLE
Cache tag causes Twig runtime error when "path" column contains emoticon chars

### ISSUE THREAD

**Issue by skoften** [craftcms/cms#4780]
For some reason someone is requesting an entry on the frontend, but adding some chars/emoticons to the URL, which causes a parsing error between the cache tags for the column "path".

![Screenshot 2019-08-20 at 16 04 38](https://user-images.githubusercontent.com/1286410/63354511-dc333480-c364-11e9-92a3-7540317207cd.jpg)

Craft CMS 3.1.34.2

**Comment by brandonkelly** [comment]
Thanks for reporting! Just fixed this for the next release.

To get the fix early, please first update to Craft 3.2.10, and then change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#78fdd4508df2879b45ed71655c04d8de85c7f8b9 as 3.2.10",
  "...": "..."
}
```

Then run `composer update`.
