### ISSUE TITLE
Cannot rename assets when changing case only

### ISSUE THREAD

**Issue by jeffers102** [craftcms/cms#4785]
### Description
When I try to rename an asset by changing case only, it fails with an error saying that that filename is already in use.  Due to a client's wishes, I recently had to change the case for several dozen assets all at once, which was time consuming, as I had to do it in 2 rename operations.  Not a big deal, but resolution might help others with more images in their CMS.

### Steps to reproduce

1. Upload an image: MyFuNnYiMage.jpg
2. Try to rename the image be all lower case: myfunnyimage.jpg

Error occurs.

### Additional info

- Craft version: Craft Pro 3.2.10
- PHP version: 7.3.8
- Database driver & version: PostgreSQL 11.5

**Comment by andris-sevcenko** [comment]
This boils down to case sensitivity for different OS, as that's the part that eventually returns the message.

Craft has no way of knowing whether that file really exists (for example on linux systems you can have "file.txt" and "File.txt" in the same folder) or not (on MacOS it's not possible) and guessing wrong can mean destroying a file that was not indexed, so Craft errs on the side of safety.
