### ISSUE TITLE
Allow static message translations to be defined by site handles

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#4786]
I could be wrong, but it seems that it's currently only possible to set up [Static Message Translations](https://docs.craftcms.com/v3/static-translations.html) by language.

I just set up a sister site for a client that uses the primary site as a template. We were hoping to use static message translation files to customize some of the language throughout the template.

Our hope was that there'd be a way to tie a translation to a site by its handle rather than a language (which is the same for both sites), so we'd end up with a template structure like so...

```
- translations
  - sitehandle
    - site.php
```

Is something like this possible, or would it make sense for it to be implemented?

**Comment by brandonkelly** [comment]
You could do this by overriding the `site` translation message source config.

Add this to `config/app.php`:

```php
return [
    'components' => [
        'i18n' => [
            'translations' => [
                'site' => function() {
                    $site = Craft::$app->sites->currentSite;
                    return Craft::createObject([
                        'class' => craft\i18n\PhpMessageSource::class,
                        'sourceLanguage' => 'en-US',
                        'basePath' => "@translations/{$site->handle}",
                        'forceTranslation' => true,
                    ]);
                },
            ],
        ],

        // ...
    ],
];
```

**Comment by jsunsawyer** [comment]
@brandonkelly Thanks, but this doesn't seem to work for me.

![Screen Shot 2019-08-20 at 4 09 44 PM](https://user-images.githubusercontent.com/1007191/63390772-13094a80-c365-11e9-95ca-88a00b4dfb46.png)
![Screen Shot 2019-08-20 at 4 10 27 PM](https://user-images.githubusercontent.com/1007191/63390775-156ba480-c365-11e9-8a71-e954fde69544.png)

**Comment by brandonkelly** [comment]
Sorry, I should have clarified, you would still need the language-specific folders within your site folders. So `translations/nwsp/en/site.php`, for example.
