### ISSUE TITLE
Reindex assets missing assets model closes undexpectedly

### ISSUE THREAD

**Issue by nickcobley** [craftcms/cms#4795]
### Description

Bit of a long-standing issue that I run into every now and again, but it's quite frustrating when I do.

If you reindex the assets, at the end of the process if there are any missing this modal is displayed:

![Screenshot 2019-08-22 13 31 39](https://user-images.githubusercontent.com/70206/63490743-fc3f3100-c4e7-11e9-8a34-ba21a3308ddd.png)

The problem is if you click outside the window, it closes the modal without any confirmation rather than requiring you to select either "Cancel" or "OK".

Where this causes usability issues, in particular, is long-running operations. Few times I've been reindexing a large remote source like S3 which may take 15 minutes or more to run. When it finishes, instinct is to click on the inactive browser window, when you do, that first click to activate the window/tab if outside that modal window closes the window with the list of missing assets. 

When this happens you then have to run the reindex again to get the list of missing assets. 

### Steps to reproduce

1. Reindex an asset source that has missing images
2. When the missing image modal shows, click outside the window

### Additional info

- Craft version: 3.2.10
- Browser: Chrome 76.0.3809.100

**Comment by brandonkelly** [comment]
Good point! Just fixed this for the next release.
