### ISSUE TITLE
Frequent "An unknown error occurred" alerts

### ISSUE THREAD

**Issue by mtnorthrop** [craftcms/cms#4796]
### Description
While navigating the Craft control panel, I'm regularly shown "An unknown error occurred" alerts.

I've checked `web.log` and `queue.log` but they don't report any issues.

The best way to trigger these errors seems to be to navigate quickly between sections of the control panel. For example, click on "Entries" immediately after logging in, before the Dashboard has finished loading, or just click from one section to the next in the CP sidebar menu.

I suspect that these errors are connected to an AJAX request being interrupted, or something related to queue jobs running in the background, but so far I haven't been able to find any record of these errors in the logs.

However, in the Firefox console, I see that there are some requests that don't have a response body.

For example, this AJAX request: `POST http://mysite.test/index.php?p=admin/actions/element-indexes/get-elements` has an empty response, and the request was made around the time I got an "unknown error".

I see these "unknown errors" on pretty much every Craft site I've worked on, both on my local development machine as well as on the production servers.

I've been seeing them since Craft 3.0, and still see them on Craft 3.2. These unknown errors don't seem to actually "break" anything, but it's sometimes awkward to explain to clients that these errors are expected and that they should just ignore them.

Is there any way to fix these errors, or at least troubleshoot them if nothing is appearing in the logs?

**Comment by brandonkelly** [comment]
What version of Craft are you using? We fixed a similar issue in 3.2.8.

**Comment by mtnorthrop** [comment]
I'm using 3.2.10, but have seen the issue in all versions as far as I can remember.

I've done a bit more testing and although it's easy to replicate the issue while using Firefox, I don't seem to be able to replicate it in Chrome. It might be a Firefox-specific issue.

**Comment by wsydney76** [comment]
Maybe unrelated, but i also see this every now and then.  Attributed it to working locally on a non thread safe Windows/Apache/DotEnv environment (see #3631), so an ajax call may be unable to get db credentials etc. Also gets obvious when something like `$SYSTEM_NAME` appears in the CP sidebar, or `{{ entry.url }}` shows a variable name.

@brandonkelly On a sidenote: craftcms/craft seems to require dotenv ^3.4 now (potentially solving this issue), so would it be safe to upgrade existing installations accordingly?

**Comment by brandonkelly** [comment]
@mtnorthrop Thanks! I was able to reliably reproduce in Firefox as well. Just fixed for the next release.

@wsydney76 It’s unrelated to Dotenv, but you are welcome to update it. There were some syntax changes between 2 and 2 so be sure to check the [upgrade guide](https://github.com/vlucas/phpdotenv/blob/master/UPGRADING.md).
