### ISSUE TITLE
Query for drafts also returns drafts of soft deleted entries

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#4797]
### Description

When an entry with existing drafts is soft deleted, those drafts are still returned by queries.

Should be soft deleted as a whole with all its drafts. (Didn't check that for revisions...)

PS.
It's also possible to open an edit screen for this draft, entering the url manually.

Thanks.

### Steps to reproduce

1. Create a draft for an existing entry
2. Soft delete the entry
3. Run craft.entries.drafts(true).all
4. The draft for this entry will be returned.

### Additional info

- Craft version: 3.2.10
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just fixed this for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#283bdaca9925be2f22e413ef1f586a90038a9618 as 3.2.10",
  "...": "..."
}
```

Then run `composer update`.
