### ISSUE TITLE
Unable to open entry with drafts from a deleted user

### ISSUE THREAD

**Issue by thechrisroberts** [craftcms/cms#4800]
### Description

Getting the error `Return value of craft\behaviors\DraftBehavior::getCreator() must be an instance of craft\elements\User, null returned` when trying to open an entry if that entry has drafts created by a deleted user.

### Steps to reproduce

1. Create a draft
2. Delete the user that created the draft
3. Open the entry in the dashboard as a different user

### Additional info

- Craft version: 3.2.10
- PHP version: 7.2.21
- Database driver & version: MySQL 5.2.27

**Comment by brandonkelly** [comment]
Thanks for reporting that! It’s been fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#c6f75e8c3d8379347ca5073de01c3a48d290e993 as 3.2.10",
  "...": "..."
}
```

Then run `composer update`.

**Comment by knynkwl** [comment]
Is there another way around this without updating? 

Like adding the same user or something in the DB that I can change?

**Comment by knynkwl** [comment]
I get this error when trying to update: 

`
Declaration of craft\helpers\Stringy::charsArray() must be compatible with Stringy\Stringy::charsArray(): array
`

**Comment by knynkwl** [comment]
I get this error when trying to update.

`Declaration of craft\helpers\Stringy::charsArray() must be compatible with Stringy\Stringy::charsArray(): array
`

**Comment by brandonkelly** [comment]
@knynkwl Ignore my previous comment; at this point you should just be updating to the latest release.
