### ISSUE TITLE
Getting « Integrity constraint violation: 1048 Column 'uid' cannot be null » error after trying to update form builder entry

### ISSUE THREAD

**Issue by elodiegrondin** [craftcms/cms#4803]
### Description

Hello, I'm not sure if my problem is related to craft cms or the plugin I'm using, so I'm asking on both side, sorry if it's not a craft cms issue... [[form-builder-3](https://github.com/roundhouse/Form-Builder-3/issues/4#issue-482706980)]

I get this error « Integrity constraint violation: 1048 Column 'uid' cannot be null » after trying to save a form. It seems to be related to the craft_element table. [[see logs](https://github.com/craftcms/cms/files/3533514/form-builder.log)]

I've already launch a composer update, uninstall and reinstall plugin but still have the same issue… What's odd is that I do not have this error in dev environment, only in production.

I think the uid gets lost somewhere in the saving entry process but I can't find out where and why...

### Steps to reproduce

1. install roundhouse/Form-Builder-3
2. create form
3. in prod env, try to edit the form and save it

### Additional info

- Craft version: 3.2.10
- PHP version: 7.1.25
- Database driver & version: MySQL 5.7.23
- Plugins & versions: Form Builder 3.0.17

**Comment by brandonkelly** [comment]
Definitely looks like a bug in Form Builder to me. I’ve commented on https://github.com/roundhouse/Form-Builder-3/issues/4.
