### ISSUE TITLE
Default Values

### ISSUE THREAD

**Issue by Willbv** [craftcms/cms#4806]
When a matrix block has a minimum number of blocks set, they don't populate the default date for a colour field (possibly anything with default data set but I haven't tested) for those blocks on a new entry.

1. Create a matrix field with a colour field and default value
2. Add a value to the minimum blocks
3. Assign field to a section
4. Create new entry, the default blocks have not set the default field values

- Craft version: 3.2.10
- PHP version: 7.1.31
- Database driver & version: MySQL 5.7.27
- Plugins & versions: Tried on a fresh build

**Comment by brandonkelly** [comment]
Thanks for reporting that!  Just fixed it for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#5e4bb8abef0f2eea9d16e99b165d048d523fc3eb as 3.2.10",
  "...": "..."
}
```

Then run `composer update`.

**Comment by Willbv** [comment]
Thanks @brandonkelly for the quick fix, it works great now.
On a similar note, is it possible when adding a new field to an existing matrix block to populate it with the default value on all entries currently with that matrix block?
