### ISSUE TITLE
DATETIME comparisons with empty string no longer work with MySQL 8.0.16

### ISSUE THREAD

**Issue by klemenb** [craftcms/cms#4808]
### Description

MySQL 8.0.16 started throwing errors when comparing DATETIME columns with empty strings as per - https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-16.html:

> When comparing a DATE or DATETIME value with a string MySQL first tries to convert the string to the same type (DATE or DATETIME) and then to compare the two as values of that type. If this conversion fails, MySQL raises an Incorrect date value warning and then falls back to comparing the values as strings, which is the expected behavior. In some cases, even though the converted string did not reflect a valid DATE or DATETIME value, no warning was issued so and it was compared with the DATE or DATETIME value as a value of that type. Now in such cases, the converted string is always checked for validity as a DATE or DATETIME before being compared, unless the ALLOW_INVALID_DATES server SQL mode has been set explicitly. (Bug #28940878)

The "Recent Orders" widget now breaks the dashboard due to this comparison:

`$query->dateOrdered(':notempty:');`

I am not sure if there are any other places where this can be a problem.

### Steps to reproduce

1. Update to MySQL 8.0.16
2. Try to load a dashboard with "recent orders" widget

### Additional info

- Craft version: 3.1.25, Commerce version: 2.1.5.2
- PHP version: 7.3.5
- Database driver & version: MySQL 8.0.16

**Comment by brandonkelly** [comment]
This has been fixed for Craft 3.3.0, which will be out soon.
