### ISSUE TITLE
Revision query not returned in order

### ISSUE THREAD

**Issue by colinmeinke** [craftcms/cms#4825]
Maybe this is my misconception, but shouldn't a revision query return ordered by revision number? This is not the case when I do something like:

```
{% set entries = craft.entries
  .section(sectionHandle)
  .site(siteHandle)
  .revisions()
  .all()
%}
```

I have to add `.orderBy('revisions.num asc')` to get the behaviour I would expect.

Craft 3.2.10.

**Comment by colinmeinke** [comment]
@brandonkelly thanks for the explanation, I can see why it works like that. What is the default order in that case, `postDate`? Wouldn't `postDate` be identical for all revisions, as that is a column in the entries table, and the revisions all share the source entry?

I'd definitely like to add my vote for default ordering by `revisions.num`, either asc or desc, when using `.revisions()`.

**Comment by brandonkelly** [comment]
Alright cool, I’ve just made that change for the next release. Going with descending order to be consistent with the Control Panel menu.

**Comment by colinmeinke** [comment]
@brandonkelly fantastic, thank you!
