### ISSUE TITLE
Undefined variable: accessToken

### ISSUE THREAD

**Issue by sebastian-lenz** [craftcms/cms#4827]
### Description

When opening the default GraphQL schema in the control panel, a php notice is raised: `compact(): Undefined variable: accessToken` in line [218 of `GraphqlController`](https://github.com/craftcms/cms/blob/develop/src/controllers/GraphqlController.php#L218)

The variable `$accessToken` is only defined in the `else` part in the condition above this line, so whenever the condition matches, `$accessToken` is not defined.

### Steps to reproduce

1. Visit `admin/graphql/schemas` after upgrading Craft 3.2 to 3.3
2. Click on the default schema listed there

### Additional info

- Craft version: Craft Pro 3.3.0
- PHP version: 7.3.8
- Database driver & version: MySQL 5.7.27

**Comment by bzin** [comment]
Was just too excited to try out the recently announcement of GraphQL api and the `headlessMode` and also got this this error.

```
PHP version | 7.3.6
Database driver & version | MySQL 5.5.5
Craft edition & version | Craft Pro 3.3.0
```
