### ISSUE TITLE
FR: GraphQL support on Mutation

### ISSUE THREAD

**Issue by minyangu-bgl** [craftcms/cms#4835]
### Description
Before Craft 3.3, we use CraftQL for both **Query** and **Mutation** on 
- Entries 
- Globals
- Categories
- Tags

Now with 3.3 release, the native GraphQL seems only support viewing on those data types which will break our integration if we upgrade, and there is no way for us to install the CraftQL plugin anymore in the latest 3.3 version due to conflicts with natively supported GraphQL server.

Please support **GraphQL Mutation** soon on those above data types, so we can migrate over to latest version and remove all existing CraftQL usage.

### Additional info
- Craft version: 3.3

**Comment by andris-sevcenko** [comment]
@minyangu-bgl it's definitely in the plans to add it as soon as possible.

**Comment by brandonkelly** [comment]
CraftQL 1.3.3 is out now which fixes the dependency conflict with Craft 3.3, so you should be able to update that now.

**Comment by narration-sd** [comment]
Good one, @brandonkelly

**Comment by narration-sd** [comment]
And it works -- now I just have to get Hal to be kind about whether you've got either of them available and ready to play...!

**Comment by minyangu-bgl** [comment]
1.3.3 indeed fixed the dependency issue during installation which is great. However, I am now experiencing below issue:
  "error": "Class 'GraphQL\\Type\\Definition\\DirectiveLocation' not found"
}

It appear on both Craft CMS 3.2/3.3, rolling back from 1.3.3 back to 1.3.2 will make things back to normal. So unfortunately, I can not upgrade Craft CMS to 3.3 unless CraftQL fixes this issue.

Here is the raised bug ticket on CraftQL: https://github.com/markhuot/craftql/issues/312

**Comment by sunscreem** [comment]
Hey @minyangu-bgl Can I ask dumb question? How do I upgrade craftQL? Its not listed as a plug in and I can't see any reference to it my vendor folder. Was it replaced by something else?

I'm getting `Schema is not configured for mutations` when I'm trying to create contact form entries

**Comment by blnkt** [comment]
@andris-sevcenko Any sense of when (or if) support for mutations will make it into an upcoming release? I'm pleased to see CraftQL is now compatible with Craft 3.3, and that'll be a more than adequate stop-gap, but I am looking forward to utilizing your new native graphQL features.

**Comment by andris-sevcenko** [comment]
I just added the 4.0 milestone. It's definitely not a thing that can be rushed, so it won't make the cut for 3.4.

**Comment by brandonkelly** [comment]
Excited to say that mutations will be making it into Craft 3.5! 🎉 

![An example GraphQL mutation query along with its response](https://user-images.githubusercontent.com/47792/79590672-3c14e300-808c-11ea-8cb0-eef299da246f.png)

If you want to help test, you can start right now by changing your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "3.5.x-dev",
  "...": "..."
}
```

Then run `composer update`.

Currently mutations are purely allowed or disallowed per the schema settings. We will be adding an additional runtime authorization layer in Craft 4, pending a move to [RBAC](https://www.yiiframework.com/doc/guide/2.0/en/security-authorization)-based authorization (#1646).

**Comment by brandonkelly** [comment]
Mutation docs are now up in the 3.5 branch: https://github.com/craftcms/docs/blob/3.5/graphql.md#mutations
