### ISSUE TITLE
Admin Menu (Cache) Issue?

### ISSUE THREAD

**Issue by DomLip94** [craftcms/cms#4837]
### Description

When changing a custom menu CP URL or label, it does not refresh.
I've tried clearing the caches, restarting PHP-FPM, NGINX and even rebooting the production server last night.

The only work around that actually fixed it was...
1. remove the menu code entirely
2. Commit and Push to production
3. Reload the page
4. Re-add code, but move it about in the file (e.g. was below... . 
`Event::on(
            UrlManager::class,
            UrlManager::EVENT_REGISTER_CP_URL_RULES,
            function (RegisterUrlRulesEvent $event) {}
);` 
...section but it's now above
5. Re-commit, re-push
6. Reload the page

This doesn't appear to be tied to any particular Craft version and has been going on some time.

### Steps to reproduce

1. Add a CP menu item using the Event trigger (see code below)
2. Change either the label or URL

### Additional info

- Craft version:
- PHP version: PHP 7.3.8-1+ubuntu18.04.1+deb.sury.org+1
- Database driver & version: MariaDB
- Plugins & versions:

` Event::on(Cp::class, Cp::EVENT_REGISTER_CP_NAV_ITEMS,
            function (RegisterCpNavItemsEvent $event) {
                         $event->navItems[] = [
                                'url' => 'epos/orders/new',
                                'label' => 'In-store Order'
                            ];
            }
);`

**Comment by angrybrad** [comment]
I'm not able to reproduce this at all.  Guessing there's some other external caching going on like Varnish or Cloudflare, etc. that you're running into.
