### ISSUE TITLE
FR: Add an option to give the menu a hover dropdown.

### ISSUE THREAD

**Issue by mikesnoeren** [craftcms/cms#4838]
When for example clearing cache you have to perform too many actions: 
Click utilities > click clear cache in the submenu > click clear caches.

Perhaps this could be simplified by using an optional dropdown menu on hover(or click) so it doesn't require extra page loads. Especially when using an external database while developing. this will speed up the process of navigation a lot!

**Comment by davidhellmann** [comment]
@Mikesnoeren you need this: https://plugins.craftcms.com/cp-clearcache
