### ISSUE TITLE
FR: Translation menu item

### ISSUE THREAD

**Issue by Mikesnoeren** [craftcms/cms#4839]
Perhaps it would be a nice idea to add a way to edit translations from the CMS and not by editing php files.

my idea would be to create a menu item named 'Static translations' and let craft read out the `/translations/*` folders and Which would then place all the translatable messages in a `<table>`.

This will give the end user an easy way to edit those translations themselves.

**Comment by brandonkelly** [comment]
This is a duplicate of #2294
