### ISSUE TITLE
GraphQL: Allow Config To Whitelist only Certain Domains for CORS

### ISSUE THREAD

**Issue by edmotech** [craftcms/cms#4842]
### Description

It would be great if you could specify a whitelist for the GraphQL CORS to lock down the api to certain domains.

### Additional info

- Craft version: 3.3.0.1
- PHP version: 7.2
- Database driver & version: mysql 5.6
- Plugins & versions:

**Comment by simeon-smith** [comment]
@AugustMiller that would definitely be an interesting idea and a cool feature. My primary concern (as posted under the edmotech user) is simply to allow locking down the API via a CORS whitelist.
