### ISSUE TITLE
Number fields don't throw errors when the value is not a number

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#4849]
### Description
The Number field as of now is a little bit confusing and I tend to use my custom Number field that actually validates numbers.
With the Feed Me fix here https://github.com/craftcms/feed-me/issues/527 you included 

```php
return $value === '' || !is_numeric($value) ? null : $value;
```

which causes to convert inputs like "aa" to null, so the number Validator won't fire and the model is saved without errors. When the client doesn't pay attantion and wants to submit something he/she won't see an error and it's just saved as empty. I don't think thats any good 

### Steps to reproduce

1. Create a Number field
2. Insert a string
3. See it's saved without errors but as null

### Additional info

- Craft version: 3.2.10

**Comment by brandonkelly** [comment]
Agree that’s not great. We’ll have to fix the Feed Me bug at the source.
