### ISSUE TITLE
[FR] Flush revisions CLI command/Utility

### ISSUE THREAD

**Issue by olivierbon** [craftcms/cms#4851]
It would useful to have a CLI command/Utility to flush revisions when `maxRevisions` is adjusted mid-project.

As an example, if you decide to set `'maxRevisions' => 10` on a project which didn't have a limit before, all revisions beyond the limit will only get flushed when the entry itself is resaved in the Control Panel.

**Comment by gtettelaar** [comment]
Wouldnt `resave/*` clear the revisions? Admittedly it's not purpose-built and so a little slower but it should work fine?

**Comment by olivierbon** [comment]
Hey @gtettelaar, no it doesn't. Revisions get flushed [when a revision is created](https://github.com/craftcms/cms/blob/develop/src/services/Revisions.php#L188).

**Comment by gtettelaar** [comment]
@olivierbon Doh! Didn't look at the code but just assumed this would happen during saving in `->getElements()->saveElement()`.

**Comment by michtio** [comment]
+1 on this tho, deleting entry revisions should be possible or have a dedicated command line exec.

**Comment by brandonkelly** [comment]
Just added a `utils/prune-revisions` command for Craft 3.4.
