### ISSUE TITLE
[FR] Add Live Preview to Headless Mode

### ISSUE THREAD

**Issue by brycebenson** [craftcms/cms#4853]
With the recent release of Headless Mode, the Live Preview button was removed from entries. Can you please add back the Live Preview buttons for headless builds that still require using Live Preview via tokens?

**Comment by brandonkelly** [comment]
It will show up if you add a preview target.

**Comment by brycebenson** [comment]
Didn't realize this was a pro only feature.

**Comment by brandonkelly** [comment]
Right, Preview Targets and the GraphQL API are both Pro-only features.
