### ISSUE TITLE
`users/logout` controller doesn't destroy session

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#4855]
### Description

```php
    /**
     * @return Response
     */
    public function actionLogout(): Response
    {
        // Passing false here for reasons.
        Craft::$app->getUser()->logout(false);
```

The comment says "Passing false here for reasons." -- any clarification on what these reasons might be? I think potentially not destroying the session could be related to https://github.com/nystudio107/craft-webperf/issues/21

### Additional info

- Craft version: 3.3.0
- PHP version: 7.1.x
- Database driver & version: n/a
- Plugins & versions: n/a

**Comment by angrybrad** [comment]
Huh... here's the commit from 4 years ago: https://github.com/craftcms/cms/commit/64d154be404d4eeba66fb64a8f0d816e209cf5f9

Can't recall what the original reason was, but maybe @brandonkelly does.

**Comment by khalwat** [comment]
Some guy named "Brad" is named on the commit :)

**Comment by brandonkelly** [comment]
Theoretically the PHP session could contain things that weren’t tied to the user session.

We go through and explicitly remove any PHP session values that were in fact associated with the user session, and you could do the same:

https://github.com/craftcms/cms/blob/069f389944401cc8eb9fecddd69e408c5b03a912/src/web/User.php#L497-L514

There is an `EVENT_AFTER_LOGOUT` event you could hook into.
