### ISSUE TITLE
Things get cached with should not become cached

### ISSUE THREAD

**Issue by wedot** [craftcms/cms#4858]
### Description
On the site, only on the homepage things gets cached witch should not become cached. Even the Craft toolbar becomes cached and its visible on the frondend when there is no admin logged in. By clearing the cache it has about 1 to 5 minutes and there is a new cached version of the site.

### Steps to reproduce
1. Removed the Caching
2. Tested the Problem on other sites
3. Tested on different browsers and devices

### Additional info
- Craft version: Craft CMS 3.3.0.1 (I had the bug in 3.2 too)
- PHP version: PHP 7.1.30
- Database driver & version: MySQL
- Plugins & versions: 
Imager v2.1.10
Locate 2.1.1
Mailchimp Subscribe 3.0.0
Minify 1.2.9
No-Cache 2.0.4
Redactor 2.3.3.2
Redactor Tweaks 2.0.2
SEO 3.6.2
Sprout Active 2.1.0
Sprout Encode Email 2.0.7
Sprout Fields 3.4.4
Sprout Notes 2.2.3
Super Table 2.2.1
Wheel Form 2.2.4

**Comment by brandonkelly** [comment]
Craft doesn’t cache anything that you don’t explicitly tell it to using the `{% cache %}` tag.

**Comment by wedot** [comment]
I this case it do something like this.

I have removed all cache tags in the template. but it looks like the page gets cached. But this happens only on one page - on the homepage.

**Comment by brandonkelly** [comment]
Then it’s probably not Craft itself that is doing the caching. Perhaps Varnish, a load balancer, or some other server that sits between the end client and Craft.

**Comment by wedot** [comment]
I thought so too. I could not find anything. The strenge thing is this only happen on the homepage. all other pages have the some configs.

**Comment by narration-sd** [comment]
What happens if you refresh your browser on the home page, when you find it's cached?

I've been noticing some apparent browser behaviors lately where if you set to auto-reload 'last open' pages, they don't actually get reloaded -- just replayed from browser cache. It takes then the refresh to see reality...

**Comment by wedot** [comment]
I get the same page again. In the toolbar I always get the identical output. 
All 3 to 30 minutes i get a new page. I don'r think it's the local browsercache.

Tested on: 
Mac: Chrome, Opera, Safari, Brave (cleared browsercache get the some page)
iPhone: Safari, Brave

**Comment by narration-sd** [comment]
Fair enough - and covers the other thing I might have mentioned, that browsers sometimes (particularly Chrome) get 'tired' after a lot of development refreshes, and need to have their own caches fully cleared before they become sensible again. 

Your ISP could be caching, and I think you wouldn't be able to detect that. You could try adding a nonsense query item like `?nutstocaches=1` to your home page url, and see if that breaks a cache somewhere. Presumably you're not running through Cloudflare or the like as well...

**Comment by wedot** [comment]
I don't think that my browsers are the problem. Now i tested it on 2 other PCs. Some problem.

With `?nutstocaches=1` I get a other result but at reloading with the some query I get the some page again. When I count up it always give me a new result for the first time. I think i have to call my hosting partner and ask him if he has some type of caching.

**Comment by narration-sd** [comment]
Sounds right, from what you're seeing. Good fortune

**Comment by wedot** [comment]
Thank you for your support. :)
