### ISSUE TITLE
Matrix Rows Duplicating/Removing During Multi-Site Setup

### ISSUE THREAD

**Issue by matthewmrotter** [craftcms/cms#4859]
### Description
Switching between propagation methods creates unexpected behavior in Matrixes. 

### Steps to reproduce

1. Set method to "Only saves blocks to the site they were created in" 
2. Create content in 2 sites
3. Change Method to "Save blocks in in all sites" 
4. Create new blocks then hit save.
5. Keep changing the preferences and become increasingly more confused as content get added and removed 

https://imgur.com/qGbNtz8

https://imgur.com/4izzgX9
 

### Additional info

- Craft version: 3.3.0.1
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Plugins & versions: None

**Comment by brandonkelly** [comment]
The setting is literally determining which sites a single block should be saved across to, so this all sounds like expected behavior to me.
