### ISSUE TITLE
404 Entry not found error when creating new entries

### ISSUE THREAD

**Issue by dozzed** [craftcms/cms#4862]
### Description

Whenever I try to add a new entry I just get the following error `HTTP 404 – Not Found – yii\web\NotFoundHttpException
Entry not found` and Im not able to access the create entry page. I just get redirected to something like `admin/entries/events/420?draftId=108&fresh=1 ` and just get the error. This is happening on all sections. 

![image](https://user-images.githubusercontent.com/6993471/64009556-578ca700-cb18-11e9-95f4-247c4ac2cae0.png)

Although I can't access the create entry page the system automatically creates drafts. Whenever I try to view those drafts I get the same 404 error.

I can access and edit all previously created entries without issues.

I tried recreating all vendor files but still the same problem.
I tried disabling versions from sections but nothing. (I always get an url with `draftId` parameters even with versions off, is that correct?)
No new plugins were added. No settings were changed.

### Steps to reproduce

1. /admin/entries/events
2. Press "+ New Entry"

### Additional info

- Craft version: Craft Pro 3.3.0.1
- PHP version: 7.2.7
- Database driver & version: 8.0.11
- Plugins & versions:

Contact Form | 2.2.5
Contact Form Honeypot | 1.0.2
CP Clear Cache | 1.0.4
Craft Commerce | 2.1.12.1
Fix FKs | 1.0.2.1
Imager  | v2.1.10
Mailgun  | 1.4.2
reCAPTCHA  | 1.3.0
Redactor | 2.3.3.2
Stripe for Craft Commerce | 2.1.1

**Comment by brandonkelly** [comment]
Try going to `/admin/utilities/php-info?foo=bar` and then search the page for `$_SERVER['QUERY_STRING']`. Does the value column say `foo=bar` or `no value`?

**Comment by dozzed** [comment]
Thanks for the fast response! 

I get:
`$_SERVER['QUERY_STRING'] | no value`

**Comment by brandonkelly** [comment]
That’s what I expected. So that means that your request’s query string is getting lost at some point on its way to PHP.

If you are running Craft on Apache with a `mod_rewrite` rule in `.htaccess` or `httpd.conf`, make sure that the `RewriteRule` includes the `[QSA]` flag. Not sure off the top of my head what else it could be.

**Comment by dozzed** [comment]
Im using Nginx and I'm also having trouble with `craft.app.request.getQueryParam() `. Hmm... this is probably related with my Nginx setup on my local environment then. Thanks for pointing me in the right direction!

**Comment by dozzed** [comment]
I just tested a couple of Craft installations.

Craft CMS 3.1.28 is working correctly
Craft CMS 3.2.4.1 is not working
Craft CMS 3.3.0.1 is not working


All with the same nginx and php configuration. Was there a specific change to the way request parameters worked?

**Comment by brandonkelly** [comment]
I’m guessing you only tested entry creation, which as of Craft 3.2.0 is now reliant on query string parameters. If you test `getQueryParam()` directly in Craft 3.1 I’m guessing it also won’t work there.

**Comment by dozzed** [comment]
I'm getting the correct query parameters on Craft CMS 3.1.28.

![image](https://user-images.githubusercontent.com/6993471/64022368-59fdf980-cb36-11e9-863b-9bc123d90972.png)

**Comment by brandonkelly** [comment]
It still says `no value` in your screenshot.

**Comment by dozzed** [comment]
Oops you're correct. I have a few production websites running Craft CMS 3.2.4.1 and above without problems. So this is definitely a nginx setup issue on my local environment. My local setup has been working for more than a year smoothly until now. I'm guessing the 3.2+ brought some changes that are not compatible with my current local setup. Again appreciate your help!

**Comment by brandonkelly** [comment]
Yeah you’re correct. There are other areas of Craft that probably haven’t been functioning properly that just went under the radar, like how Craft is supposed to default to the same selected entry type and parent entry ID for new entries when clicking “Save and add another” from an Edit Entry page. Nothing as prominent as Craft 3.2+’s reliance on query strings for creating entries, though.

**Comment by dozzed** [comment]
I just fixed my issue. I made this change on the nginx.conf file.

Old setup:
```
	location / {
	try_files $uri $uri/ /index.php;
	}
```
New setup:
```
	location / {
        try_files $uri $uri/ /index.php?q=$uri&$args;
	}
```

I've been battling this problem for days (Im not that smart) and decided to open an issue here when in reality it was a problem on my end. Pointing to query parameters help me put 2 and 2 together. You have saved me a lot of extra frustration. Hope you and the team have an awesome weekend!

**Comment by brandonkelly** [comment]
Glad you got it sorted! You have a good weekend as well :)

**Comment by lukeyouell** [comment]
@brandonkelly I'm seeing this error, but only when signed into the CMS as a user group with restricted permissions. They have full permissions for a particular section, but see "No entry found" when attempting to create a new entry in said section. This isn't the case when signed in as an admin.

Any ideas?

**Comment by charkdesign** [comment]
@brandonkelly apologies for commenting on a closed issue, but can you think of any other reasons why this might happen? I am experiencing this exact issue when creating new entries (existing entries are fine) on one of my Craft sites (v3.7.65.2). When checking `$_SERVER['QUERY_STRING']`, it displays the expected value of `foo=bar`. I've been searching for ages for a solution to this, but I can't find anything that helps, so I'm hoping that you might have some further ideas on this please.

**Comment by brandonkelly** [comment]
@charkdesign If you can send SSH credentials over to support@craftcms.com, we can look into it from there.
