### ISSUE TITLE
Craft 3 batchInsert includeAuditColumns causes Yii2 QueryBuilder to mistypecast

### ISSUE THREAD

**Issue by HunWalk** [craftcms/cms#4864]
### Description

Using craft 3 db to batchInsert into a custom table created with craft migrate creates an error.

### Insight:
https://github.com/yiisoft/yii2/blob/dfbf17683186e553b689eac33e3919c87ef4c5cc/framework/db/QueryBuilder.php#L460-L481

### Steps to reproduce

1. Create a table with ```php craft migrate/create```
2. Make sure the table includes the auditColumns
```php
$this->createTable('{{%tableTest}}',[
    'id' => $this->primaryKey(),
    //yourColumns
    'dateCreated' => $this->dateTime(),
    'dateUpdated' => $this->dateTime(),
    'uid' => $this->string(),
]);
```
3. ``` php craft migrate ```
4. Use [batchInsert](https://github.com/craftcms/cms/blob/8eb03b10ce9bd9d1c26f730aeda34ab4998cf61a/src/db/Command.php#L61-L85)

In this case the variable ```$rows``` is an array which has key value pairs, whereas the key is the corresponding column name , while the value is the value we want to insert.
```php
$rows[] = [
'columnName' => 'value'
];
```
This is a valid representation how inserting should also work using Yii2.

Moving on:

```php
\Craft::$app->db->createCommand()->batchInsert(
    MyActiveRecord::tableName(),
    $attributes,
    $rows
)->execute();
```

### Runtime insight with screenshots
Here i indicated the contents of the variables $columns and $rows
![Screenshot 2019-08-30 at 12 18 45](https://user-images.githubusercontent.com/32835435/64014779-42694580-cb23-11e9-8e92-b6938e618fed.png)

This was var_dumped inside the yii2 QueryBuilder file.

Because of those key => value pairs the auditColumnIndexes are starting from 0 inside the $rows the columns will be off by that. 

And  this will cause the following:
![Screenshot 2019-08-30 at 13 31 28](https://user-images.githubusercontent.com/32835435/64017695-8dd32200-cb2a-11e9-8b48-0d6cdea7d395.png)

### Solution:
Change this:
https://github.com/craftcms/cms/blob/8eb03b10ce9bd9d1c26f730aeda34ab4998cf61a/src/db/Command.php#L74-L78
To this:
```php
foreach ($rows as &$row) {
    $row['dateCreated'] = $date;
    $row['dateUpdated'] = $date;
    $row['uid'] = StringHelper::UUID();
}
```

### Additional info

- Craft version: 3.2.9
- PHP version: 7.3.6
- Database driver & version: MySQL 5.7.25

**Comment by brandonkelly** [comment]
`$rows` should just be a non-indexed array of values in the same order as the column names you’ve passed into the `$columns` argument.

```php
$rows[] = ['value'];
// ...

$this->batchInsert($table, ['columnName'], $rows);
```

And `$columns` should not include those 3 audit columns; `batchInsert()` will add those automatically.
