### ISSUE TITLE
Can't access drafts after converting Channel to Structure

### ISSUE THREAD

**Issue by jeffers102** [craftcms/cms#4866]
### Description
Ran into a weird problem this morning.  I converted a Channel to a Structure yesterday, then today, I tried to promote some drafts within the Structure.  I received no errors when switching between the "Current" revision and draft revision.  However, after reloading, each time the selected revision was the "Current" revision.  I remembered that yesterday I had switched the type.  So I went back and reverted the section to a Channel and things immediately worked again.  My, maybe naive, understanding was that Channels are subsets of Structures.  So I didn't expect draft entries to no longer be selectable.

### Steps to reproduce

1. Create a Channel section.
2. Add a new entry in the Channel.
3. Promote a live version and then make a draft.
4. Change the Channel to a Structure.
5. Attempt to access the draft.

**Comment by brandonkelly** [comment]
Ah this is probably happening because the drafts & revisions aren’t getting added to the structure along with the source entries. So they aren’t getting matched by the draft & revision queries. Will look into what we can do to fix this.

**Comment by brandonkelly** [comment]
Sorry, somehow this bug slipped through the cracks. Fixed now for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.7 is out now with the fix.
