### ISSUE TITLE
Preview target being loaded over https

### ISSUE THREAD

**Issue by kjbrum** [craftcms/cms#4867]
### Description

When adding localhost as a preview target, the URL gets changed to use https.

If I setup a preview target as `http://localhost:3000/blog`, when I try to load a preview, the URL that gets loaded will be `https://localhost:3000/blog`.

### Steps to reproduce

1. Set a preview target URL to `http://localhost:3000`.
2. Preview an entry using the previously created target.
3. Inspect the preview and see that the `iframe` is loading the https version.

### Additional info

- Craft version: 3.3.0.1
- PHP version: 7.3
- Database driver & version: 5.7
- Plugins & versions: CraftQL - v1.3.4

**Comment by brandonkelly** [comment]
As in the `src` attribute on the iframe itself starts with `https://`?

**Comment by kjbrum** [comment]
Correct

**Comment by brandonkelly** [comment]
Just fixed this for the next release.

**Comment by kjbrum** [comment]
Perfect, thanks!
