### ISSUE TITLE
"All entries" heading missing from entries modal

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#4871]
### Description
In the modal shown to add entries to an entries field, the "all entries" option isn't displayed anymore. Logged in with an admin user so I don't think it's a permissions issue.

![Screenshot 2019-09-02 at 09 50 06](https://user-images.githubusercontent.com/755428/64098524-5f8e5600-cd67-11e9-8ddd-d54dbae60d72.png)

We are running [verbb/expanded-singles](https://github.com/verbb/expanded-singles) on the site, but disabling that doesn't fix it.

### Additional info

- Craft version: 3.3.0.1
- PHP version: 7.3
- Database driver & version: 5.7
- Plugins & versions: 
Expanded Singles 1.0.7
Feed Me 4.1.2
Freeform 3.3.1

**Comment by olivierbon** [comment]
@janhenckens you will only see the *All entries* option if you selected **All** under **Sources** in your Settings → Fields → [your field] settings.

**Comment by janhenckens** [comment]
That sounds logical but not very practical from an author's perspective. 

If I have a site with 30 section and a field that has _only_ 20 of those enabled, an "All entries" option with make it much easier to see recent content and to select mulitple entries across sections.

**Comment by brandonkelly** [comment]
@janhenckens Each source is basically just a named entry query, each with different criteria. There’s no way to create a special “All entries” view that is still filtered down based on the different sources that had been selected by the field.
