### ISSUE TITLE
Updating Assets Index: An unknown error occurred

### ISSUE THREAD

**Issue by MrGlasspoole** [craftcms/cms#4881]
Every time i update the Assets Index i get 2 times: "An unknown error occurred".

How to find out what the error/problem is?

**Comment by brandonkelly** [comment]
Try clearing out your `storage/logs/` folder, then update your asset indexes again, and then open `storage/logs/web.log` and search for `[error]`.

Here’s a good article explaining how to read Craft logs: https://nystudio107.com/blog/zen-and-the-art-of-craft-cms-log-file-reading

**Comment by MrGlasspoole** [comment]
Has something to do with memory:
```
[-][1][9e923ecf3d3209db21c3cfbfb1ed5170][error][yii\base\ErrorException:1] yii\base\ErrorException: Allowed memory size of 268435456 bytes exhausted (tried to allocate 48242688 bytes) in /www/htdocs/w018c568/skulltronics.net/vendor/pixelandtonic/imagine/src/Image/Metadata/ExifMetadataReader.php:105
[-][1][9e923ecf3d3209db21c3cfbfb1ed5170][error][yii\base\ErrorException:1] yii\base\ErrorException: Allowed memory size of 268435456 bytes exhausted (tried to allocate 23076864 bytes) in /www/htdocs/w018c568/skulltronics.net/vendor/pixelandtonic/imagine/src/Image/Metadata/ExifMetadataReader.php:105
```

**Comment by brandonkelly** [comment]
Can you try increasing PHP’s `memory_limit` in `php.ini`?

**Comment by MrGlasspoole** [comment]
I did set it to 512M and no errors.
I wonder how high i can go on a shared server.
Any negative side effects with that many php memory?

Is ExifMetadataReader just for reading Exif from the images?
If yes that's something i don't need. Is it possible to disable it?

**Comment by brandonkelly** [comment]
Glad that worked.

Nothing inherently wrong with increasing the memory limit, no. It won’t affect any operations that don’t need additional memory.

There’s always some amount of Exif data that needs to be read, like determining which orientation a camera was in at the time a photo was taken, so we know whether to rotate the image or not, etc.
