### ISSUE TITLE
[bug] GraphQL menu link shows when administrative changes are not allowed

### ISSUE THREAD

**Issue by billythekid** [craftcms/cms#4884]
### Description

If the environment is set to not allow admin changes the graphQL link shouldn't show, as you'll only get an error anyway. I think this is slightly different to #4836 although it's discussed in there as the link in the sidebar still errors.

Once #4371 is available (read only admin pages for admins where admin changes not allowed) it could go back in the menu sidebar.

**Comment by brandonkelly** [comment]
Saw this and fixed it last week, but now that there is a GitHub issue about it, I have linked the release note to this.
