### ISSUE TITLE
[bug] Fields column heading "Type" says "Try for free"

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#4885]
### Description

The column heading that normally says "Type" under admin/settings/fields now says "Try for free"

![image](https://user-images.githubusercontent.com/1250017/64249961-97d79500-cf1d-11e9-8be2-1914eb8ebe79.png)

I've just replicated this on a basic up to date Craft install with no plugins.

### Additional info

- Craft version: 3.3.0.1

**Comment by brandonkelly** [comment]
This has been fixed for the next release.
