### ISSUE TITLE
Upgrading from 3.2.10 to 3.3.01 created a `Undefined index: siteId` issue

### ISSUE THREAD

**Issue by zizther** [craftcms/cms#4886]
### Description
After upgrading from 3.2.10 to 3.3.01 the site is now not working on the frontend, with the error showing `Undefined index: siteId` in in /Users/nathanreed/Documents/Sites/motm/vendor/craftcms/cms/src/elements/db/ElementQuery.php line 1699

This site was developed in C2 before upgrading to C3.0.* +

### Steps to reproduce

1. Have a Craft 3.2.10 
2. Upgrade to 3.3.01 via composer

### Additional info

- Craft version: 3.3.01
- PHP version: 7.2.20
- Database driver & version: MYSQL 5.7.26
- Plugins & versions:

**Comment by zizther** [comment]
This ended up being an issue with Solspace Calendar and the search param.

**Comment by jacotijssen** [comment]
> This ended up being an issue with Solspace Calendar and the search param.

Running into the same issue (also using Solspace Calendar). How did you fix it?

**Comment by zizther** [comment]
The issue for me was to do with the search param in the events query.
I have submitted a bug report to Solspace, they were able to replicate and are working on releasing a fix.

**Comment by brandonkelly** [comment]
We ran into this in some of our own code as well, when the `select` clause was being overridden. I’ll go ahead and reopen this and fix it.

**Comment by brandonkelly** [comment]
And fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#cd3c3e5c48aecdb22c1f373184e88785cc1a5dc6 as 3.3.0.1",
  "...": "..."
}
```

Then run `composer update`.

**Comment by zizther** [comment]
I can confirm this has fixed the issue I was experiencing.
Thanks for sorting so quickly!
