### ISSUE TITLE
Post Date Calendar Enhancement

### ISSUE THREAD

**Issue by CreateSean** [craftcms/cms#4887]
### Description
When editing older entries that you want to adjust the post date it is cumbersom to click through years worth of months. 

Ideally you could click on the month/year to navigate by year and then fine tune it.

![image](https://user-images.githubusercontent.com/6899490/64265458-efb3d300-cf00-11e9-99f4-869477a6ffcc.png)

So in the above screenshot I want to update this entry to September 2019 it's a lot of clicks. Much easier to click the year and change that.

### Steps to reproduce

1.
2.

### Additional info

- Craft version: 3.2.9
- PHP version: 7.2
- Database driver & version:
- Plugins & versions:

**Comment by janhenckens** [comment]
The post date itself is an input field so you can change the value there as well. Does that work for you @CreateSean?

**Comment by CreateSean** [comment]
Didn't know that and yes it works for me.
