### ISSUE TITLE
Utilities PHP Info Error

### ISSUE THREAD

**Issue by tokersey** [craftcms/cms#4889]
### Description
When visiting /admin/utilities/php-info, the error `Array to string conversion` appears for line 66 of /vendor/craftcms/cms/src/utilities/PhpInfo.php.

### Steps to reproduce

1. Log in to Craft
2. Go to /admin/utilities/php-info

### Additional info

- Craft version: 3.3.0.1
- PHP version: 7.2.8

**Comment by janhenckens** [comment]
@tokersey Have a look at #4878, seems to be the same issue.

**Comment by tokersey** [comment]
@janhenckens Thanks, that is the same issue, which was closed without a solution. I don't think the issue is specifically with the phpinfo line, but I think Brandon's suggestion is inaccurate. I doubt it is my environments when the page has worked up until upgrading to 3.3. The only difference being Craft and its dependencies were updated. I can revert back to 3.2.10 and it works as expected. I am seeing the issue on multiple environments which have all worked appropriately in the past.

**Comment by brandonkelly** [comment]
@tokersey Can you please post that info on #4878 ?
