### ISSUE TITLE
Migration timeout when updating Craft 3.1.34 to 3.2

### ISSUE THREAD

**Issue by jkorff** [craftcms/cms#4890]
### Description
I get a timeout error when I attempt to update Craft from 3.1.34 to 3.2:

./craft update craft:3.2
Fetching available updates ... done
Performing one update:
    - craft 3.1.34.3 => 3.2
Backup the database? (yes|no) [yes]:
Backing up the database ... done
Performing update with Composer ... done
Applying new migrations ... Exception 'Symfony\Component\Process\Exception\ProcessTimedOutException' with message 'The process "'/Users/xxx/code/craft/craft' 'migrate/all' '--no-content'" exceeded the timeout of 60 seconds.'
in /Users/xxx/code/craft/vendor/symfony/process/Process.php:1332

Attempting to update composer's timeout with
export COMPOSER_PROCESS_TIMEOUT=600
yields no difference.

### Steps to reproduce

1. Go to the Craft folder
2. In the console, enter './craft update craft:3.2'

### Additional info

- Craft version: 3.1.34
- PHP version: 7.1.23
- Database driver & version: MySQL 5.5.53
- Plugins & versions: 
Cloudflare	0.2.9
Footnotes	2.0.0-beta.1
Matrix Colors	2.0.1
Redactor	2.3.3.2
SuperSort	3.0.1

**Comment by brandonkelly** [comment]
Generally PHP is configured without a time limit for the CLI; can you remove the 60 second timeout?

**Comment by jkorff** [comment]
I found that the time limit came from the php.ini. Since I don't have access to my host's file, I added this line to .htacess which extends it to the recommended value:

`php_value max_execution_time 120`

**Comment by brandonkelly** [comment]
That is going to affect web requests as well; usually there will be a specific `php.ini` configuration for CLI requests, that remove restrictions like `max_execution_time` and `memory_limit`, without affecting web requests. You may want to ask your host to add one.
