### ISSUE TITLE
Make "share" button into link again

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#4891]
Can "share" button visible in entry editing page be made into link again?

Out of habit i keep clicking on it with middle mouse button.

**Comment by brandonkelly** [comment]
It acts as a link unless there is more than one share target, in which case it becomes a menu button.

**Comment by piotrpog** [comment]
@brandonkelly 
I never added any preview targets (fresh install) and the button still does not act as link.

**Comment by brandonkelly** [comment]
What does it do, then?

**Comment by Mosnar** [comment]
@brandonkelly I think he means it's not an anchor tag, but a `div` with a click handler on it, so he can't middle-click or right click and open in a new tab. I was able to confirm that the share button is always a `div`, regardless of whether there are preview targets or not. 

Prior to 3.3, the share button was an anchor tag.

**Comment by piotrpog** [comment]
@Mosnar @brandonkelly 
Yes, thats what I meant.

**Comment by JayBox325** [comment]
This button is now a `<button>` tag, but I definitely think this should be an a tag with a href. For 'opening in new tab' functionality but also accessibility to make it clear it's purpose.

**Comment by brandonkelly** [comment]
The actual target URL that is opened is dynamically generated based on a few different things, so not possible for us to make it a normal `<a>` tag. And it already opens the page in a new window so there shouldn’t be any reason to Command-click it to force it to open in a new window.

**Comment by brandonkelly** [comment]
Found a way to get the View button / menu options to be `<a>` tags, for Craft 3.7.25 ✨  See #10220 for details.
