### ISSUE TITLE
[FR] Give ability to include description of User Groups

### ISSUE THREAD

**Issue by gdubois414** [craftcms/cms#4893]
### Description
I think it would be extremely helpful to have editable descriptions of what a user group has permission to do. This would be for cases where new admins or users that can assign user groups can quickly understand what a given group has access to.

This would not be auto-generated, but rather an additional optional field in the user group settings page.

I think having a line similar to a field's instructions text, or as a tooltip next to the name would both be fine and not clutter the interface too much.

**Comment by darylknight** [comment]
+1. Would be great to be able to tell the users, and remind myself, what specific user groups are set up for.

**Comment by brandonkelly** [comment]
Just added this for 3.5!

<img width="354" alt="A list of user groups with description" src="https://user-images.githubusercontent.com/47792/85190007-f4b3fa00-b268-11ea-8d45-80e3cc605ba5.png">
