### ISSUE TITLE
Unable to create new entries when using CP in `fr` or `fr-CA` locale

### ISSUE THREAD

**Issue by martinleveille** [craftcms/cms#4894]
### Description

We're unable to create new entries when using the CP in `fr` or `fr-CA` locale.

This issue only target channel and structures sections that have entry URI enabled.

There is no issue in 3.2.10.

### Steps to reproduce

1. Do a fresh Craft 3.3.1 install.
2. Log in and change your user language to the "français" or "français (Canada)" locales.
3. Create a new channel section that use entry URI.
4. Create a new entry in that channel and save it.
5. The screen just reload and the entry is not saved.

### Additional info

- Craft version: Solo and Pro 3.3.1
- PHP version: 7.2.21
- Database driver & version: MySQL 5.7.27
- Plugins & versions: No plugins

**Comment by PopaWeb** [comment]
Same thing here!

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you please send a database backup and your `composer.json` and `composer.lock` files over to support@craftcms.com?

**Comment by martinleveille** [comment]
Sent you the files the support email. I made a 2 minutes video that reproduce this issue.

https://www.youtube.com/watch?v=nd-IyE5EnDY

**Comment by angrybrad** [comment]
Thanks for the video, Martin... unfortunately I'm not able to reproduce this on a fresh install of the latest Craft following the exact steps in the video, so we must be missing something. Are you getting any JS errors on your browser's console towards the end when the entry doesn't save?

**Comment by martinleveille** [comment]
That's really a weird one. No javascript errors, no missing files in the network tab. Same issue in Firefox, Chrome and Edge.

I've try different scenarios and the issue only happen in my local env using Laravel Valet. So I've updated my PHP to the latest brew version 7.2.22 and also update the Valet composer package to 2.4.2.

The weird part is that Craft 3.2.10 do not have this issue. When I update Craft to 3.3.0, the issue appear ...

**Comment by martinleveille** [comment]
I've updated my local env to PHP 7.3.9 and the issue is now resolved on 3.3.2. I will not seek more to solve this problem.

Thank you @brandonkelly and @angrybrad for your time, it's very much appreciated.
