### ISSUE TITLE
[FR] Look for default .graphql cached schema file

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#4896]
Many editors with GraphQL plugins ([PhpStorm](https://plugins.jetbrains.com/plugin/8097-js-graphql), [VS Code](https://marketplace.visualstudio.com/items?itemName=apollographql.vscode-apollo) ) and GraphQL "playgrounds" allow you to give them a default `.graphql` schema file for auto-completion purposes. It's just a shortcut to having to rebuild the entire schema.

Since right now the Craft CMS GraphQL implementation [doesn't build the full schema](https://github.com/craftcms/cms/blob/develop/src/controllers/GraphqlController.php#L141) unless `devMode` is on, having such a default file would be useful:

```php
        try {
            $devMode = Craft::$app->getConfig()->getGeneral()->devMode;
            $schemaDef = $gqlService->getSchemaDef($schema, $devMode);
            $result = GraphQL::executeQuery($schemaDef, $query, null, null, $variables, $operationName)
                ->toArray(true);
        } catch (\Throwable $e) {
            throw new GqlException('Something went wrong when processing the GraphQL query.', 0, $e);
        }

        return $this->asJson($result);
    }
```

The idea is that people could use the [graphql console command](https://github.com/craftcms/cms/pull/4834) to dump the schema, and then GraphiQL, various editors, etc. could then utilize it for auto-completion purposes without having to get the full schema back from Craft for the API. 

In addition, support for [graphql-config](https://github.com/prisma/graphql-config) would be wonderful.

As @pauloelias [said](https://github.com/craftcms/cms/pull/4834#issuecomment-529037949):

> In addition to the 👍 I would also like to say this will be a huge help to our workflow since our headless CMS does not have devMode enabled. We still need to be able to test queries with the most up-to-date schema and I'd prefer not to have to fork this (now) huge database to a staging environment every time we update content models.
> 
> When we run headless we only spin up temporary review apps for each release but we don't need a long-running staging server in between releases because we don't need to worry about any frontend twig templates breaking.
> 

Related: https://github.com/craftcms/cms/pull/4834

**Comment by andris-sevcenko** [comment]
Back when I toyed with this, building the schema from a `.graphql` file was *incredibly* slow.

But things should be good enough without this, as Craft now serves the full schema for introspection queries, right?

cc @khalwat @pauloelias

**Comment by khalwat** [comment]
yep especially now that we can just do this:

https://nystudio107.com/blog/graphql-schema-auto-completion-with-phpstorm

**Comment by andris-sevcenko** [comment]
Closing this, then.
