### ISSUE TITLE
[3.3.1.1] Error 'Variable "CraftEdition" does not exist' when saving entries with validation failures

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#4898]
### Description

This is a weird one, as it happens in some sections, but not everywhere. 

If an entry with validation errors (e.g. empty mandatory field) is saved, there is an error `Variable "CraftEdition" does not exist. in ...\src\templates\_layouts\cp.html line 61`

This variable seems to be set in `web\twig\Extension.php line 1113` , yet the templateMode is set to 'site' in this cases.

Reverting the changes in `craft\web\View::renderString() and renderObjectTemplate()` fixes the error provisionally for us.

/sh on behalf of @wsydney76.

### Additional info

- Craft version: 3.3.1.1

**Comment by wsydney76** [comment]
Seems to happen if there is a twig template snippet evaluated when saving, either as title format or upload location of an asset field.

/sh

**Comment by Sam-Black-0013** [comment]
I had the error after i upgraded to 3.3.1.1

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just released 3.3.1.2 with a fix.
