### ISSUE TITLE
chaning File System Path causes missing assets

### ISSUE THREAD

**Issue by aliv** [craftcms/cms#4899]
**Description**
hi
After changing File System Path, and after clear cache, all assets with old file system path aren't accessible anymore. so
- we can see a "Changing this may result in data loss" warning below section type before edit. maybe this is good idea to have a warning for File System Path field too.
- or maybe keep path of asset, relative to project, so change file system path doesn't affect asset.?

**Additional info**
- Craft version: 3.3.1.1
- PHP version: 7.2

**Comment by brandonkelly** [comment]
Craft won’t delete asset records when you change a volume’s File System Path, even if it can’t find the assets anymore. The only way that assets could be deleted because the files can’t be found is if you:

1. Run the “Asset Indexes” utility
2. Once indexing is finished, a dialog will be shown that lists all the missing assets, and you explicitly must tell Craft to delete their records.

**Comment by aliv** [comment]
@brandonkelly sorry, i explained my situation bad, i am just saying maybe it is good idea to have asset files like images in admin/assets page accessible after changing file system path in admin/settings/assets/volumes/x page. currently if i change file system path setting in volume edit page, i  see broken images in admin/assets.

**Comment by aliv** [comment]
@brandonkelly  I'm just saying:
file system path and base url are saved per asset volume not per file. 
this setting can be edited after asset upload too. now
- if user go control panel and edit a old entry , he sees a broken link image because craftcms has only current asset volume setting. -if there is no browser or app cache for those assets-
so IMHO:
- maybe we should warn users to don't change these File System Path ad base url setting because they are going to loose old assets.
- keep file system path per file not per asset volume.

i also can post a Steps to reproduce too.

**Comment by brandonkelly** [comment]
Generally if people change the File System Path, they are also moving all of their existing assets to that new location too, so storing paths per file would not only be messy, but break those workflows.
