### ISSUE TITLE
How about loose yii2 version constraint to latest version?

### ISSUE THREAD

**Issue by lubobill1990** [craftcms/cms#4900]
### Description
Currently, yiisoft/yii2 will update every week, but craftcms restricts yii2 version to 2.1.21.0.

When I have to install craftcms with my current yii2 installation, I have to change yiisoft/yii2 version manually as "2.0.25 as 2.0.21".

How about loose the restriction and change yiisoft/yii2 version as ~2.0.21 ?

### Steps to reproduce

1.N/A

### Additional info

- Craft version:3.2
- PHP version:7.3
- Database driver & version:mysql
- Plugins & versions:N/A

**Comment by brandonkelly** [comment]
Yii 2 doesn’t follow semver; they allow breaking changes in 2.X.Y releases. So we have to lock it at 2.X.Y and only allow hotfix updates, and thoroughly test when new Y releases are released, when there is a good reason to update.

**Comment by lubobill1990** [comment]
I get it, thank you.
