### ISSUE TITLE
Element::getSource Method is still in docs

### ISSUE THREAD

**Issue by spharion88** [craftcms/cms#4901]
### Description
As mentioned in Ticket #4754 you removed the Element::getSource Method with Craft 3.3, but it is still in the docs: https://docs.craftcms.com/api/v3/craft-base-element.html#public-methods

### Steps to reproduce
1. Go to https://docs.craftcms.com/api/v3/craft-base-element.html#public-methods

**Comment by brandonkelly** [comment]
Thanks for reporting that! We’ve been having issues with the API doc generation for the past few weeks, and I finally had a chance to track the culprit down and get the API docs updated. So `getSource()` is no longer listed now.
