### ISSUE TITLE
Default value for lightswitch fields not respected on asset upload (Craft 2)

### ISSUE THREAD

**Issue by olivierbon** [craftcms/cms#4902]
*This is for Craft 2*

### Steps to reproduce

1. Create a lightswitch field with a default value set to *on* (green).
2. Create a new asset source and attached the above field to it.
3. Upload an asset and check the result. The default lightswitch value will not be respected.

### Additional info

- Craft version: 2.7.10
- PHP version: 7.2
- Database driver & version: 5.7.25
- Plugins & versions: n/a

**Comment by angrybrad** [comment]
Closing this because Craft 2 is in security fix only mode https://craftcms.com/guides/supported-versions and it's been resolved in Craft 3 already.
