### ISSUE TITLE
Project config not syncing

### ISSUE THREAD

**Issue by pablofernandezgh** [craftcms/cms#4903]
### Description
The project config file doesn't sync the database anymore

The config column in the table "info" is in line with my project.yaml file, but the database doesn't have the new fields and sections that I created

I've tried running  `craft project-config/sync` and `craft project-config/rebuild`. 
It says everything went ok. But my changes still don't get applied

### Additional info

- Craft version: 3.2.10
- PHP version: 7.3.4
- Database driver & version: PostgreSQL 10.6

**Comment by brandonkelly** [comment]
Please write into support@craftcms.com with a database backup and your `composer.json` and `composer.lock` files, plus a `project.yaml` file that isn’t getting applied, and we can look into it from there.

**Comment by nstCactus** [comment]
Any update on this? We're getting such syncing errors from time to time too. I just had one yesterday but I worked it around without taking a database backup. Next time it happens, I'll take one and email it, if that's  fine with you

**Comment by andris-sevcenko** [comment]
@nstCactus did you also try running `./craft project-config/sync --force`? In theory, that should save solved it, if it was a simple syncing issue (as opposed to a borked project config).

**Comment by nstCactus** [comment]
Thanks for the tip. I did but then ran into 4151. I managed to fix both of the issues but I had to dive into project.yaml
