### ISSUE TITLE
Entry won't create in French language

### ISSUE THREAD

**Issue by ClaireSer** [craftcms/cms#4905]
### Description

Hi,I would like to report a bug on craft.I was creating a new entry (channel type) and I could not save it. It is like I was refreshing the page. However, I was able to work around the problem by changing my langage account from french to English... 
Thank you. Regards.

### Steps to reproduce

1. create a new section of channel type (for me it was "Actualités" with the handle word "news")
2. have the account langage in french
3. create a new entry of news
4. (no need to add fields, just the title one automatically here)
5. write something in the field and save. -> should refresh the page and clear infos.
The other buttons won't work either.

### Additional info

- Craft version: 3.3.1.2 (Solo)
- PHP version: 7.1.12
- OS version: Darwin 17.7.0
- Database driver & version: MySQL 5.6.38
- Image driver & version: GD 7.1.12
- Plugins & versions: 
    - Contact Form 2.2.5
    - Contact Form Extensions 1.1.7
    - Expanded Search 1.2.1
    - Field Manager 2.1.0
    - Redactor 2.3.3.2
    - Site Switcher 2.1.0
    - Typed link field 1.0.19

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Please send a database backup and your `composer.json` and `composer.lock` files to support@craftcms.com and we’ll look into it from there.
