### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by BramBeekman** [craftcms/cms#4908]
array_merge(): Expected parameter 1 to be an array, string given

**Comment by angrybrad** [comment]
Can you enable devMode and share the full stack trace for the error?

**Comment by BramBeekman** [comment]
1014101510161017101810191020102110221023102410251026102710281029103010311032     */
    private function _getConfigurationFromYaml(): array
    {
        if ($this->_useConfigFile()) {
            $fileList = $this->_getConfigFileList();
            $fileConfigs = [];
            foreach ($fileList as $file) {
                $fileConfigs[] = $this->_parseYamlFile($file);
            }
            $generatedConfig = array_merge(...$fileConfigs);
        } else {
            if (empty($this->_parsedConfigs[self::CONFIG_KEY])) {
                $this->_parsedConfigs[self::CONFIG_KEY] = $this->_getLoadedConfig();
            }
            $generatedConfig = $this->_parsedConfigs[self::CONFIG_KEY];
        }
 
        return $generatedConfig;
    }

**Comment by BramBeekman** [comment]
Do you mean this?

**Comment by BramBeekman** [comment]
`yii\base\ErrorException: array_merge(): Expected parameter 1 to be an array, string given in C:\Users\bramb\Documents\Werk\Website\bearclaw\bearclaw\vendor\craftcms\cms\src\services\ProjectConfig.php:1023
Stack trace:
#0 C:\Users\bramb\Documents\Werk\Website\bearclaw\bearclaw\vendor\craftcms\cms\src\web\ErrorHandler.php(80): yii\base\ErrorHandler->handleError(2, 'array_merge(): ...', 'C:\\Users\\bramb\\...', 1023)
#1 [internal function]: craft\web\ErrorHandler->handleError(2, 'array_merge(): ...', 'C:\\Users\\bramb\\...', 1023, Array)
#2 C:\Users\bramb\Documents\Werk\Website\bearclaw\bearclaw\vendor\craftcms\cms\src\services\ProjectConfig.php(1023): array_merge('')
#3 C:\Users\bramb\Documents\Werk\Website\bearclaw\bearclaw\vendor\craftcms\cms\src\services\ProjectConfig.php(1139): craft\services\ProjectConfig->_getConfigurationFromYaml()
#4 C:\Users\bramb\Documents\Werk\Website\bearclaw\bearclaw\vendor\craftcms\cms\src\services\ProjectConfig.php(504): craft\services\ProjectConfig->_getPendingChanges()
#5 C:\Users\bramb\Documents\Werk\Website\bearclaw\bearclaw\vendor\craftcms\cms\src\web\Application.php(224): craft\services\ProjectConfig->areChangesPending()
#6 C:\Users\bramb\Documents\Werk\Website\bearclaw\bearclaw\vendor\yiisoft\yii2\base\Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#7 C:\Users\bramb\Documents\Werk\Website\bearclaw\bearclaw\web\index.php(21): yii\base\Application->run()
#8 {main}`

**Comment by andris-sevcenko** [comment]
Can you share the contents of your `config/project.yaml` file, if you have one?

**Comment by BramBeekman** [comment]
I cant open it

**Comment by andris-sevcenko** [comment]
> I cant open it

What's the reason? Permissions? Missing file? No content? I'm gonna need something :)

**Comment by BramBeekman** [comment]
![image](https://user-images.githubusercontent.com/37911406/64610860-73bdfd00-d3d0-11e9-8160-a6f1bf093b8f.png)

**Comment by BramBeekman** [comment]
![image](https://user-images.githubusercontent.com/37911406/64611020-c3042d80-d3d0-11e9-8683-93f25044fc0d.png)

**Comment by andris-sevcenko** [comment]
Can you still open the file and see what's inside? Can you describe in more detail how you came to this situation? Was it after installation, was it after an update?

**Comment by BramBeekman** [comment]
If i open the file i see this (See Pic) It was out of nowhere, Yesterday it works fine and now this broken.

**Comment by BramBeekman** [comment]
![image](https://user-images.githubusercontent.com/37911406/64611930-dfa16500-d3d2-11e9-86ff-3cb7f051ce36.png)

**Comment by andris-sevcenko** [comment]
Huh. That is peculiar. Can you delete it? Craft should generate a new one for you based on the internal project config state.

**Comment by BramBeekman** [comment]
Dude your awesome! That was the trick haha!
