### ISSUE TITLE
Programmatic field population

### ISSUE THREAD

**Issue by ryanpcmcquen** [craftcms/cms#4910]
### Description

I'd like to fill in a field, based on a request using a url from another field. Is there any way to do this besides using `EVENT_BEFORE_SAVE`? The scenario in this case is getting a SoundCloud TrackId based on the consumer facing SoundCloud url.

For instance, user enters this url:
https://soundcloud.com/the-bad-plus/and-here-we-test-our-powers

Then a request is made to the SoundCloud api to get the TrackId, with something like this:

```php
$client = new Client();
$soundcloudRequest = 'https://api.soundcloud.com/resolve?url=' . $foo->soundcloudUrl . '&client_id=' . getenv('SOUNDCLOUD_CLIENT_ID');

$soundcloudData = $client->createRequest()
    ->setHeaders(['content-type' => 'application/json'])
    ->setMethod('GET')
    ->setFormat(Client::FORMAT_JSON)
    ->setUrl($soundcloudRequest)
    ->send();

$soundcloudJson = json_decode($soundcloudData->getContent(), true);

if ($soundcloudData->isOk) {
    $foo->soundcloudTrackid = $soundcloudJson['id'];
}
```

I'd like to ideally generate this with some kind of button or interaction besides forcing the user to save.

### Additional info

- Craft version: 3.1.x

**Comment by brandonkelly** [comment]
Yes, you could build a custom [field type](https://docs.craftcms.com/v3/extend/field-types.html) that watches its text input value and loads the additional data automatically, and submits that data as part of its value.
