### ISSUE TITLE
Template mode reset issue

### ISSUE THREAD

**Issue by joshuabaker** [craftcms/cms#4912]
### Description

9864d0bb8c15a3bfcf00257704a6f0b5022e0c37 introduces an issue in instances where an exception is thrown before the [template mode is reset](https://github.com/craftcms/cms/blob/a49ccf67359d69e01005cf122b77e54b85e3e2f0/src/web/View.php#L555).

For example, if an element throws an exception at [L511](https://github.com/craftcms/cms/blob/a49ccf67359d69e01005cf122b77e54b85e3e2f0/src/web/View.php#L511) of View.php the template mode is not reset.

Additionally, if the exception is suppressed anywhere ([like here](https://github.com/craftcms/cms/blob/a49ccf67359d69e01005cf122b77e54b85e3e2f0/src/fields/Assets.php#L705-L709)) you end up with misleading template loader exceptions.

Related issue: verbb/super-table#297

### Additional info

- Craft version: 3.3.1.2

**Comment by brandonkelly** [comment]
Thanks for reporting that, it should be fixed for the next release!
