### ISSUE TITLE
Handling "Your project.yaml file was created for different versions of Craft" errors

### ISSUE THREAD

**Issue by aaronbushnell** [craftcms/cms#4914]
### Description
I'm on the latest version of Craft 3.2.x and I have set `useProjectConfigFile` to `true` in my config file. The `project.yaml` file is created without issue, but I noticed `schemaVersion` is set to `3.1.27` (even though I'm on version 3.2.x).

If I make a small change in my `project.yaml` file and refresh the control panel I see the following error message.

>Your `project.yaml` file was created for different versions of Craft and/or plugins than what’s currently installed.
>
>**Craft CMS** currently installed has the schema version of 3.2.16 (expected 3.1.27)
>
>Try running `composer install` from your terminal to resolve.

I have tried the following but none of these resolve this error message:

1. Run `./craft project-config/rebuild`
2. Delete `composer.lock` and `vendor/` and run `composer install`

I did notice that the `config` column in the `craft_info` table has an object that looks like this:

```json
{
  "edition": "pro",
  "live": true,
  "name": "My Site",
  "timeZone": "America/Indiana/Indianapolis",
  "schemaVersion":"3.1.27"
}
```

Should the `schemaVersion` be updated? 

### Additional info

- **PHP version**: 7.1.26
- **OS version**: Darwin 18.7.0
- **Database driver & version**: MySQL 5.7.27
- **Image driver & version**: GD 7.1.26
- **Craft edition & version**: Craft Pro 3.2.10

**Comment by aaronbushnell** [comment]
It seems like this is no longer a problem locally if I call [the updateCraftVersionInfo() function](https://github.com/craftcms/cms/blob/develop/src/services/Updates.php#L313-L334) in a random module I have setup on this site.

I'm guessing that ensures the `schemaVersion` in the `craft_info` table under the `config` column is up-to-date?

Is this the best way to resolve this or are there some gotchas I should be on the look-out for here?

**Comment by kennethormandy** [comment]
I think I’m having the same issue: my `schemaVersion` seemed like it was stuck on `3.1.28`, and I keep running into this error in my production environment. I’m running `3.3.3` locally and there.

I’ve rebuild the file and have the same database in both environments. `composer install` runs each time I push to production, so I don’t think that’s part of the problem. The `project.yaml` also does seem to be updated properly as things change or Craft is upgraded, it’s just the `schemaVersion` that didn’t change.

As a test, I tried manually changing the version number to `3.3.3` (I didn’t know about `updateCraftVersionInfo()`), and seems to have worked to get me past the problem for now—although maybe that is just deferring things until the next time the version number needs to be updated?

I can try and provide any other details, if it helps. Thanks for all the hard work on this project!

**Comment by jamiewade** [comment]
Related https://github.com/craftcms/cms/issues/4998

**Comment by j-greig** [comment]
Have a similar problem with schemaVersion on `3.1.28` but the CP reporting `3.1.34` and the database and Composer also set to `3.1.34`, unsure how to resolve.

**Comment by brandonkelly** [comment]
To be clear the schema version is not the same as the Craft version; you can see what your installed schema version is from `vendor/craftcms/cms/src/config/app.php` (`schemaVersion` key).

**Comment by aaronbushnell** [comment]
Hey @brandonkelly is there a way to ensure the Craft database is using the correct schema version? It seems like the issue I'm encountering is that Craft isn't accurately reflecting the schema my site should be on. 

I called [the updateCraftVersionInfo() function](https://github.com/craftcms/cms/blob/develop/src/services/Updates.php#L313-L334) in a random module I have setup on this site but I'm not sure if this has other side-effects that could cause issues?

**Comment by andris-sevcenko** [comment]
@aaronbushnell I'll take a look at this tomorrow my time. Sorry for the long wait :(

**Comment by aaronbushnell** [comment]
Totally good, @andris-sevcenko! Let me know if you need me to test anything for ya!

**Comment by andris-sevcenko** [comment]
@aaronbushnell so the core issue seems here that for some reason migrations were run, but the schema version remained the same in the internal project config. Looking at the code, I have a hard time imagining how that could have happened, unfortunately.

> but I'm not sure if this has other side-effects that could cause issues?

Yeah, that is hard to predict and depends on where the original borkiness happened. Definitely make DB backups. 

After that, the safest way would be to:

1. Disable the `useProjectConfigFile` setting and deleting the file
2. Go to your `info` table and set the `schemaVersion` field to `3.1.27`, ensuring that any unapplied migrations since that schema get applied ...
3. ... as you run `./craft migrate/up --type=app`
4. Enable the `useProjectConfigFile` setting?

Did I mention making sure you have DB backups before that?

**Comment by aaronbushnell** [comment]
Thanks for the info, @andris-sevcenko! Have an update for ya here.

## Getting a copy of the production database

Before I ran any of the steps you mentioned I grabbed the most recent database backup from the production site and noticed that if I run...
```sql
SELECT version, schemaVersion FROM craft_info;
```
I get...

| version      | schemaVersion  |
|-----------|-----------------|
| 3.2.10       | 3.2.16                  |

...which _seems_ to be correct. However, I still see that the `system` object in the large JSON payload in `config` still has this output:
```json
{
  "system": {
    "edition": "pro",
    "live": true,
    "name": "My Site",
    "timeZone": "America/Indiana/Indianapolis",
    "schemaVersion": "3.1.27"
  }
}
```

Any reason why my `schemaVersion` column wouldn't match the `schemaVersion` value in the JSON object? Is that by design?

## Changing the value in the `schemaVersion` column

I already have the Project Config disabled so I skipped step 1 and ran the following to update my `schemaVersion` column:
```sql
UPDATE craft_info SET schemaVersion="3.1.27" WHERE id=1;
```
Then for confirmation I ran...
```sql
SELECT version, schemaVersion FROM craft_info;
```
...and I get...

| version      | schemaVersion  |
|-----------|-----------------|
| 3.2.10       | 3.1.27                  |

## Running the migration command

Then ran `./craft migrate/up --type=app` and received this message:

```sh
Yii Migration Tool (based on Yii v2.0.21)

No new migrations found. Your system is up-to-date.
```

## After generating a new Project Config

At this point I generated a new `project.yaml` file by enabling the config option in `general.php` and then using `./craft project-config/rebuild` and here's the output in the `system` section:

```yaml
system:
  edition: pro
  live: true
  name: 'My Site'
  timeZone: America/Indiana/Indianapolis
  schemaVersion: 3.2.16
```

And this appears to correctly match what's in the database if I run...

```sql
SELECT version, schemaVersion FROM craft_info;
```
...and I get...

| version      | schemaVersion  |
|-----------|-----------------|
| 3.2.10       | 3.2.16                  |

## Confirming if a database change was needed

Just to double check if the database changes were necessary I started this process over, but did the following:

1. Copied a fresh production database to my local machine
2. Ran `./craft migrate/up` and received the `No new migrations found` message
3. Enabled `useProjectConfigFile` in `general.php` and ran `./craft project-config/rebuild`

And after that the `system` section of `project.yaml` still read:

```yaml
system:
  edition: pro
  live: true
  name: 'My Site'
  timeZone: America/Indiana/Indianapolis
  schemaVersion: 3.1.27
```

**BUT**, if I run that same process with a small tweak to the `./craft migrate/up` command:

1. Copied a fresh production database to my local machine
2. Ran `./craft migrate/up --type=app` and received the `No new migrations found` message
3. Enabled `useProjectConfigFile` in `general.php` and ran `./craft project-config/rebuild`

Now the `system` section of `project.yaml` reads:

```yaml
system:
  edition: pro
  live: true
  name: 'My Site'
  timeZone: America/Indiana/Indianapolis
  schemaVersion: 3.2.16
```

## Conclusion

It _looks_ like running `./craft migrate/up --type=app` and regenerating the Project Config gets me consistent `schemaVersion` data!

However, I don't know why that wasn't happening when I just ran `./craft migrate/up`? Is there a reason why one would've successfully updated the schema, but not the other?

**Comment by andris-sevcenko** [comment]
> Any reason why my schemaVersion column wouldn't match the schemaVersion value in the JSON object? Is that by design?

The internal project config state is updated when the request ends. So, if the update script dies between updating the DB with the schema version and firing the request end event, it might happen. The good thing, though, is that Craft won't re-run migrations that are already finished, so setting schema version in the `info` table is a rather safe bet.

> However, I don't know why that wasn't happening when I just ran ./craft migrate/up? Is there a reason why one would've successfully updated the schema, but not the other?

By default `./craft migrate/up` only runs content migrations. You can run `./craft migrate/all` to run all of the migrations, which is what you'll usually want to do.

**Comment by aaronbushnell** [comment]
Thanks, @andris-sevcenko! Hope this helps anyone who has had similar issues with the Project Config schema mismatch.

**Comment by aaronbushnell** [comment]
Sorry—one thing I wanted to add to this (not sure if this is a bug).

When I run `./craft migrate/all` before generating a new Project Config I still have the wrong schema version. I needed to specifically run `./craft migrate/up --type=app` to have the correct schema generated in that file.

Again, not sure if that's a bug—but just noting it in case someone encounters this.

**Comment by brandonkelly** [comment]
@aaronbushnell It should be perfectly safe to run `migrate/all` when there are pending schema changes. What error did you get, exactly?

**Comment by aaronbushnell** [comment]
@brandonkelly — When I generate a `project.yaml` file it seems to have the wrong schema version and running both: `./craft migrate/all` and `./craft migrate/up` don't seem to fix that. You'll see in this GIF that my `schemaVersion` is `3.1.27` instead of the correct `3.2.16` version.

It's only when I run `./craft migrate/up --type=app` that my `project.yaml` file schema changes to the correct version.

Here's a GIF that might best explain this.

![schema-issues](https://user-images.githubusercontent.com/315202/66779471-44e9e980-ee9c-11e9-8d85-b7473c411293.gif)

**Comment by brandonkelly** [comment]
I’m not able to reproduce that with Craft 3.3.9. Can you try updating Craft and then re-test this the next time an update comes with a new schema version?

**Comment by aaronbushnell** [comment]
Hey @brandonkelly — upgrading to the latest version (3.3.9) and then generating a new `project.yaml` file is providing the correct schema version (3.3.3)!

**Comment by brandonkelly** [comment]
Cool, so we must have changed something since then that fixes this :)

**Comment by N0ps32** [comment]
@brandonkelly this is still broken for me with the latest version of craft. I'm completely unable to update my production environment

**Comment by timmyomahony** [comment]
I'm suddently getting this for a project. It's only happening on my staging server, not local or development.

> SEO is installed with schema version of 3.1.1 while 3.1.0 was expected.

**Comment by dialedin-team** [comment]
Hi @brandonkelly ,

When I rebuild the project config, the schema version changes(fixed the issue), but also it has an impact on multiple files. For example, in the 'servd\AssetStorage\AssetsPlatform\Fs' type, the subfolder path value changes from 'staging/images' to 'local/images' in the 'project.yml' file. Is this potentially dangerous for the live site because the path now indicates the local file path, and the 'changedFieldIndicator' value of supertable plugin is set to null?
See the attached Screenshot: [https://i.stack.imgur.com/QDsbW.png](url)
[https://i.stack.imgur.com/XN7NS.png](url)
Thanks in advance.
