### ISSUE TITLE
Function for transfering variables from Twig to JS

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#4915]
I often pass Twig variables into JS. I do this like this:

```
{% js %}
var js_variable = '{{twig_variable}}'
{% endjs %}
```

This is little cumbersome. I propose simplifying this process with function like this:

```
{{twigToJs(variable, 'js_variable_name')}}
```

This would output:
```
var js_variable_name = 'twig_variable_contents'
```
If second argument would not be provided, js variable name would be same as twig variable name.

If object or array was used instead of simple twig variable, it would be passed through json encode function.

If twig variable was boolean instead of string, function could skip wrapping js variable in `'`.

**Comment by brandonkelly** [comment]
You can already do this using the [json_encode](https://docs.craftcms.com/v3/dev/filters.html#json-encode) filter.

```twig
var js_variable_name = {{ twig_variable|json_encode|raw }}
```
