### ISSUE TITLE
Add option for {% js %} tag to output javascript into file

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#4916]
As in issue title - add option for {% js %} tag to output javascript into file.

This would make easier consuming generated JS code by build systems like gulp.

**Comment by brandonkelly** [comment]
Can you give me an example of how this would work?

**Comment by piotrpog** [comment]
@brandonkelly 
Right now all JS is concated and appended right before closing `<body>` tag.

What i propose is outputting JS into file. If no file exist, it would be created.

**Comment by brandonkelly** [comment]
Gotcha. You could accomplish this by creating a template ending in `.js`, and output all your dynamic JS code in there, then pull it in using `view.registerJsFile(url('path/to/template.js'))`.

**Comment by piotrpog** [comment]
@brandonkelly 
Thanks!

**Comment by piotrpog** [comment]
@brandonkelly 
I just looked into it a bit. Doesn't it require that i put all JS into this file myself?
I wanted to keep using `{% js %}` tag as i used to in multiple twig components.

**Comment by brandonkelly** [comment]
If the actual JS is going to vary based on the request, then it’s better for it to be included in the response HTML. Moving it to a separate file that changes with each request would add a bunch of unnecessary overhead.

**Comment by piotrpog** [comment]
I think you are right, I forgot that different pages/sites will have different JS.
It would be better to somehow hook gulp or any other tool into build process but this is probably job for the plugin.
