### ISSUE TITLE
Seeding a site with an excisting project config

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#4918]
### Description
Not an issue but a more a question. We're setting up a repo to use as a starter package for our Craft projects (through composer's `create-project` command).

In order to avoid having to keep a database in the repo, we enabled `projectConfig` and have our sections and fields in the `project.yaml` in the starter repo. But when settings up a site using `craft/setup` overwrites that entirely.

Is there a way to get an existing `project.yaml` setup in the database?

### Additional info

- Craft version: 3.3.1.1
- PHP version: 7.3.7
- Database driver & version: 5.7

**Comment by brandonkelly** [comment]
Craft will try to use the `project.yaml` file if it’s there, and `config/general.php` has `'useProjectConfigFile' => true`.

If it’s not working, it will explain why in your logs – search them for `can't apply existing project config:`.

**Comment by janhenckens** [comment]
Gotcha, I'll check the logs!
