### ISSUE TITLE
Can't access label when dropdown is in a table (and maybe also in a global)

### ISSUE THREAD

**Issue by LauraMontgomery** [craftcms/cms#4920]
### Description
I have a globals field which contains a table. The table contents a dropdown. On the front-end, I am unable to access the label (but can access the value) of the dropdown items. Outputting a dump of the table row seems to conform my experience, that the label is not available for some reason.

`array(4) { ["col1"]=> string(78) "https://open.spotify.com/show/0a9EtFwLvkYsIzo9tTvJ0i?si=peBnRJJVTMKhLs_Mxkc22A" ["col2"]=> string(7) "spotify" ["podcastPlatformLink"]=> string(78) "https://open.spotify.com/show/0a9EtFwLvkYsIzo9tTvJ0i?si=peBnRJJVTMKhLs_Mxkc22A" ["podcastPlatformIcon"]=> string(7) "spotify" } `

### Steps to reproduce

1. Global field, contains a table, table contains a dropdown field
2. Try of output {{ block.podcastPlatformIcon.label }}
3. Get a twig error

`Impossible to access an attribute ("label") on a string variable ("spotify").`

### Additional info

- Craft version: 3.3.1.2

**Comment by brandonkelly** [comment]
This was just reported this morning :) See #4911 

Unfortunately it’s not really possible for us to make dropdown labels within Table fields accessible the same way that it works for “real” Dropdown fields, though @jalendport did show off a way it can be done from the templates by going through the field settings – https://github.com/craftcms/cms/issues/4911#issuecomment-530386553

**Comment by brianlarson** [comment]
FTR the macro from @jalendport in https://github.com/craftcms/cms/issues/4911#issuecomment-530386553 solved this issue for me.
