### ISSUE TITLE
Why Does Manual Cache Clear Work But CP Task Fails?

### ISSUE THREAD

**Issue by kgrote** [craftcms/cms#4921]
### Description

I've been having a problem with my site not properly clearing out its template caches. The task list gets stuck on "Pending" when trying to execute the "Deleting stale template caches" task.

I understand this kind of stalled task is a [common problem](https://craftcms.com/guides/resolving-stalled-background-tasks), but if I manually clear the caches by going to Utilities -> Clear Caches, that works fine and it unblocks the pending task list.

I thought maybe the problem was that my PHP `memory_limit` was too low, but if that were the case wouldn't the manual cache clear command also cause a timeout error?

### Additional info

- Craft version: 3.3.1.2
- PHP version: 7.3.1
- Database driver & version: MySQL 5.7.25

**Comment by brandonkelly** [comment]
In `config/general.php` do you have `'runQueueAutomatically' => false` set by chance?

**Comment by kgrote** [comment]
Nope!

**Comment by brandonkelly** [comment]
Probably easiest if you can give us access to this site over at support@craftcms.com so we can look into it directly.
