### ISSUE TITLE
Craft requires ext-zip * -> the requested PHP extension zip is missing from your system

### ISSUE THREAD

**Issue by Pixelalb** [craftcms/cms#4927]
### Steps to reproduce

1.
2.

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by PrestonSonomaWeb** [comment]
how is that done?

**Comment by PrestonSonomaWeb** [comment]
this should likley not be closed as it is still very much an issue with craft installs.

here is the error message i get:


Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - craftcms/cms 3.3.9 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.8 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.7 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.6 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.5 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.4.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.4 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.3 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.20.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.20 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.2 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.19 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.18.4 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.18.3 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.18.2 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.18.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.18 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.17 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.16.3 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.16.2 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.16.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.16 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.15 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.14 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.13 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.12 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.11 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.10 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.1.2 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.1.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.0.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.3.0 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.2.9 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.2.8 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.2.7 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.2.6 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.2.5.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.2.5 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.2.4.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.2.4 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.2.3 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.2.2 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.2.10 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.2.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.2.0 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.9.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.9 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.8 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.7 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.6.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.6 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.5 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.4 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.34.3 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.34.2 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.34.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.34 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.33 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.32.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.32 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.31 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.30 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.3 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.29 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.28 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.27 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.26 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.25 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.24 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.23 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.22 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.21.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.21 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.20.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.20 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.2.2 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.2.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.2 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.19 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.18 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.17.2 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.17.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.17 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.16 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.15 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.14 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.13 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.12 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.11 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.10 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.1.0 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.9 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.8 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.7 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.6 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.5 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.41.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.41 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.40.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.40 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.4 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.39 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.38 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.37 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.36 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.35 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.34 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.33 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.32 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.31 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.30.2 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.30.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.30 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.3.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.3 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.29 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.28 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.27.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.27 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.26.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.26 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.25 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.24 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.23.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.23 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.22 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.21 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.20 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.2 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.19 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.18 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.17.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.17 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.16.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.16 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.15 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.14 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.13.2 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.13.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.13 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.12 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.11 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.10.3 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.10.2 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.10.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.10 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.0.2 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.0.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - craftcms/cms 3.0.0 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - Installation request for craftcms/cms ^3.0.0 -> satisfiable by craftcms/cms[3.0.0, 3.0.0.1, 3.0.0.2, 3.0.1, 3.0.10, 3.0.10.1, 3.0.10.2, 3.0.10.3, 3.0.11, 3.0.12, 3.0.13, 3.0.13.1, 3.0.13.2, 3.0.14, 3.0.15, 3.0.16, 3.0.16.1, 3.0.17, 3.0.17.1, 3.0.18, 3.0.19, 3.0.2, 3.0.20, 3.0.21, 3.0.22, 3.0.23, 3.0.23.1, 3.0.24, 3.0.25, 3.0.26, 3.0.26.1, 3.0.27, 3.0.27.1, 3.0.28, 3.0.29, 3.0.3, 3.0.3.1, 3.0.30, 3.0.30.1, 3.0.30.2, 3.0.31, 3.0.32, 3.0.33, 3.0.34, 3.0.35, 3.0.36, 3.0.37, 3.0.38, 3.0.39, 3.0.4, 3.0.40, 3.0.40.1, 3.0.41, 3.0.41.1, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.9, 3.1.0, 3.1.1, 3.1.10, 3.1.11, 3.1.12, 3.1.13, 3.1.14, 3.1.15, 3.1.16, 3.1.17, 3.1.17.1, 3.1.17.2, 3.1.18, 3.1.19, 3.1.2, 3.1.2.1, 3.1.2.2, 3.1.20, 3.1.20.1, 3.1.21, 3.1.21.1, 3.1.22, 3.1.23, 3.1.24, 3.1.25, 3.1.26, 3.1.27, 3.1.28, 3.1.29, 3.1.3, 3.1.30, 3.1.31, 3.1.32, 3.1.32.1, 3.1.33, 3.1.34, 3.1.34.1, 3.1.34.2, 3.1.34.3, 3.1.4, 3.1.5, 3.1.6, 3.1.6.1, 3.1.7, 3.1.8, 3.1.9, 3.1.9.1, 3.2.0, 3.2.1, 3.2.10, 3.2.2, 3.2.3, 3.2.4, 3.2.4.1, 3.2.5, 3.2.5.1, 3.2.6, 3.2.7, 3.2.8, 3.2.9, 3.3.0, 3.3.0.1, 3.3.1, 3.3.1.1, 3.3.1.2, 3.3.10, 3.3.11, 3.3.12, 3.3.13, 3.3.14, 3.3.15, 3.3.16, 3.3.16.1, 3.3.16.2, 3.3.16.3, 3.3.17, 3.3.18, 3.3.18.1, 3.3.18.2, 3.3.18.3, 3.3.18.4, 3.3.19, 3.3.2, 3.3.20, 3.3.20.1, 3.3.3, 3.3.4, 3.3.4.1, 3.3.5, 3.3.6, 3.3.7, 3.3.8, 3.3.9].

would love to not be getting this, most answers on the web involve laravel which i did not realize was a craft dependency.  this is a bit of a mess. please advise.

**Comment by brandonkelly** [comment]
> this should likley not be closed as it is still very much an issue with craft installs.

@PrestonSonomaWeb Well, Craft does in fact rely on the Zip library, therefore the error you are getting is expected behavior if your environment doesn’t have the Zip lib installed.

> would love to not be getting this, most answers on the web involve laravel which i did not realize was a craft dependency. this is a bit of a mess. please advise.

I’m guessing that you are seeing references to [Laravel Homestead](https://laravel.com/docs/4.2/homestead), which despite the confusing name, is not the same thing as Laravel. _Homestead_ is a [Vagrant](https://www.vagrantup.com/) environment that is preconfigured with a few different PHP versions, MySQL and Postgres, and other things that are generally needed for running PHP applications (like Laravel apps or Craft CMS). (It is maintained by the Laravel project, hence the name.)

**Comment by lukeholder** [comment]
If you are using vagrant, and trying to run `composer install` or `composer update` from outside of the vagrant VM (you really want to run composer install *from your local machine*) you have 2 options:


1) Install the zip extension into your local PHP installation.

2) Append `--ignore-platform-reqs` to your command like this:

  `composer install --ignore-platform-reqs`

The PHP extension zip requirement error will go away and allow you to proceed.

Be aware that the zip extension is still required to run Craft though, so you wouldn't want to ignore the reqs running composer in your production environment.

**Comment by PrestonSonomaWeb** [comment]
'composer install --ignore-platform-reqs' 
this is *exactly* what i have been searching for composer can run now. yes, I am just trying to get a local version running. the prod environment can run craft so it will not be an issue. thanks so much for your help with this.

**Comment by chadcrowell** [comment]
For the record I've been getting this exact error message over the past week or 2 from 3 or 4 Craft installations when running updates locally, whether from composer, or the CP Update button. I've run updates for months and months for these sites and others in this same MAMP install with no trouble in the past. I thought I was nuts but its good to see someone with this issue as well. 

I do have ext-zip installed (and if it was required by Craft before 3.3.20.1, Craft never complained about it until that version). In fact, I've fought with this on 2 sites *today* locally. In both PHP 7.2.21 and 7.3.8 on MAMP Pro I am getting this message.  

I tracked this Stack Exchange discussion down last week and was able to get ext-zip installed but now sometimes I get an error that says zip is already installed, so I comment it out of my php.ini and then the Control Panel will load. However, composer update fails as described by the OP. https://stackoverflow.com/a/59293432/604844

Even when I am getting this error, I can see this in phpinfo:
https://d.pr/i/9mq2cG

**Comment by chadcrowell** [comment]
Of course, as soon as I sent this, I found this https://stackoverflow.com/a/58300437/604844 which explains the same thing as a Catalina issue rather than MAMP/Craft issue. Funny as I've had Catalina since it came out and I am just now getting this error. However, this worked for me to solve it. It seems the Craft system report is looking at MAMP's php info, whereas composer is looking at the system php info, which didn't have zip installed.

**Comment by watershed** [comment]
Your final sentence makes sense to me @chadcrowell. But I’m no closer. I’ve been through that stack thread and got nowhere with it. 

I appreciate the underlying complexity of myriad operating system and user setup variables, but this is a horrible user experience :/

**Comment by brianjhanson** [comment]
@watershed I've run into this a handful of times before because of what @chadcrowell is describing. When you run `composer` from the command line, it runs with a different version of PHP (which one would be returned by running `which php` in your terminal) but when Craft is running it uses the version within MAMP.

In order to solve this you need to run composer on the command line specifically against the MAMP version of PHP, usually something like:
```
/Applications/MAMP/bin/php/${PHP_VERSION}/bin/php /absolute/path/to/composer install
```

This _should_ ensure that MAMP's version of PHP runs composer.  You also may have to make sure that the "Make this version available on the command line" box is checked.

If you want all php on the command line to be run with MAMP's version, you can [do something like this](https://stackoverflow.com/a/4262717)

**Comment by watershed** [comment]
Thanks @brianjhanson. That makes sense. Will look at doing that.

**Comment by watershed** [comment]
@brianjhanson, total life saver. That worked! Thanks :)

**Comment by smockensturm** [comment]
Wither the zip extension in CRAFT NITRO 2 ?

```
Which PHP extension would you like to enable? 
  1. bcmath
  2. bz2
  3. calendar
  4. dba
  5. enchant
  6. exif
  7. gettext
  8. gmp
  9. imap
  10. interbase
  11. ldap
  12. mysqli
  13. oci8
  14. odbc
  15. pcntl
  16. pdo_dblib
  17. pdo_firebird
  18. pdo_oci
  19. pdo_odbc
  20. pdo_sqlite
  21. recode
  22. shmop
  23. snmp
  24. sockets
  25. sysvmsg
  26. sysvsem
  27. sysvshm
  28. tidy
  29. wddx
  30. xmlrpc
  31. xsl
  32. zend_test
```

**Comment by reachpriti12** [comment]
> @watershed I've run into this a handful of times before because of what @chadcrowell is describing. When you run `composer` from the command line, it runs with a different version of PHP (which one would be returned by running `which php` in your terminal) but when Craft is running it uses the version within MAMP.
> 
> In order to solve this you need to run composer on the command line specifically against the MAMP version of PHP, usually something like:
> 
> ```
> /Applications/MAMP/bin/php/${PHP_VERSION}/bin/php /absolute/path/to/composer install
> ```
> 
> This _should_ ensure that MAMP's version of PHP runs composer. You also may have to make sure that the "Make this version available on the command line" box is checked.
> 
> If you want all php on the command line to be run with MAMP's version, you can [do something like this](https://stackoverflow.com/a/4262717)

How can I find my absolute path of composer?

**Comment by brandonkelly** [comment]
@reachpriti12 Run `which composer`

**Comment by reachpriti12** [comment]
Hi,

It just gives me attached screenshot error.

Regards,
Priti


From: Brandon Kelly ***@***.***>
Date: Thursday, 24 June 2021 at 11:45 AM
To: craftcms/cms ***@***.***>
Cc: Priti Burfield-Mills ***@***.***>, Mention ***@***.***>
Subject: Re: [craftcms/cms] Craft requires ext-zip * -> the requested PHP extension zip is missing from your system (#4927)

@reachpriti12<https://github.com/reachpriti12> Run which composer
