### ISSUE TITLE
--delete-missing-assets option for index-assets/* commands

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/cms#4928]
Would it be possible to add a `--delete-missing-assets` option (default to false) for index-assets console commands? We get a lot of file uploads from a few contact forms and it would be great to create a cron job that deletes files older than X days, then runs the `index-assets` console command and removes asset indexes of files that were deleted. Would be a lot simpler for us than removing them all manually. Thanks for your consideration!

**Comment by andris-sevcenko** [comment]
This has been added for Craft 3.4!

**Comment by anchovy** [comment]
Be great if this flag could be added to the description, something like:

```
- index-assets                                              Allows you to re-index assets in volumes. Add flag --delete-missing-assets to purge missing asset references
    index-assets/all                                        Re-indexes assets across all volumes.
    index-assets/one (default)                              Re-indexes assets from the given volume handle ($startAt = 0).

```

**Comment by brandonkelly** [comment]
@anchovy All options are documented when you pass the `--help` flag to a specific action, or use the `help` command:

```bash
> craft index-assets/all --help
> craft help index-assets/all
```
