### ISSUE TITLE
strange behaviour of asset field on save

### ISSUE THREAD

**Issue by aliv** [craftcms/cms#4933]
### Description
when 'Relate assets from a specific site?'  and 'Manage relations on a per-site basis' are both enabled, on saving new entry, assets only save for current site.

### Steps to reproduce
1. enable site1 and site2
2. enable 'Relate assets from a specific site?'  and 'Manage relations on a per-site basis' and set 'Which site should assets be related from?' to site1. 
3. go to new entry and upload asset2.jpg for site2 and then switch to site1 and you can see that asset2.jpg in site1 too.  
4. on site1, remove asset2.jpg and upload asset1.jpg.
5. switch back to site2, you can see asset2.jpg as expected  and save entry
6. open entry and you can see asset only for site2 and there is no asset1.jpg for site1.jpg.

on all scenarios i tested, it depends which site is current when i saved entry.  so if we saved entry on site1, asset was saved only for site1. 

### Additional info
- Craft version: 3.3
- PHP version: 7.2

**Comment by aliv** [comment]
@brandonkelly 
about 6, i mean open in control panel again.  
this is a fresh install of craft and there is no additional plugin or plugin. actually i am just trying to figure out how craft cms and its database structure works.

one simpler scenario:
1- upload asset1.png to site1 
2- switch to site2. you can see asset1.png
3- save entry on site2. 
4- go to edit entry in control panel
5- site1 has no asset and site2 has asset1.png because we saved entry on site2
-and relation table has one record for site2 too-
-if i save entry on site1, i only have asset1.png on site1 -

**Comment by brandonkelly** [comment]
Sorry we still can’t reproduce this. Maybe we’ll have better luck trying it on your site – can you please send a database backup, and your `composer.json` and `composer.lock` files over to support@craftcms.com?

**Comment by aliv** [comment]
@brandonkelly i sent an email to support@craftcms.com
