### ISSUE TITLE
Links to entries in headless mode (Redactor)

### ISSUE THREAD

**Issue by diluno** [craftcms/cms#4934]
### Description

My client heavily relies on the ability to insert links to other entries in text fields with Redactor. I used to do this on our headless site by setting the base site URL to the frontend-URL instead of the CMS.
Now that I turned on headless mode (which is great for everything else, I'm very happy about this change!), this is not possible anymore.

Maybe preview targets could be used as the entry URLs here?

### Additional info

- Craft version: 3.3.3
- Plugins & versions: Redactor 2.3.3.2

**Comment by howells** [comment]
@brandonkelly sorry to bring this up in a closed issue but I'm not sure I'm following how Link to Entry can used to link to the "front-end" URL of the selected entry. In headless mode, with a Primary preview target set to the client version of the entry, the redactor field (queried using Gql) just returns the regular, api version of the URL

**Comment by brandonkelly** [comment]
@howells It’s going to depend on what your site’s Base URL is set to, as well as the section’s Entry URI Format.

**Comment by howells** [comment]
Sorry - misconfiguration my side, all works as expected!
