### ISSUE TITLE
Navigating to the Globals tab in a multi-site setup doesn't respect the current site

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#4935]
### Description
In a multi-site setup with `Site A` and `Site B`, if you're on **Entries** with `Site B` selected, then navigate to **Globals**, `Site A` will be selected.

This is problematic because it's inconsistent with navigating between other sections within a selected site, so a user may unintentionally change content in **Globals** in the wrong site. Also, since there's no revision history for **Globals**, they could lose the overridden content.

### Additional info

- Craft version: 3.3.3

**Comment by brandonkelly** [comment]
The control panel doesn’t currently have a concept of a currently selected site; only certain pages within it do.

> it's inconsistent with navigating between other sections within a selected site

When you navigate between sections, that all happens on the same page, which explains that.

That said I do think it would make sense for Craft to remember the last site you had selected as you navigate throughout the control panel, so I’ll mark this as an enhancement and we’ll see if we can address it for Craft 3.4.

**Comment by jsunsawyer** [comment]
@brandonkelly Saw a new issue that better describes what we want in terms of consistency. See https://github.com/craftcms/cms/issues/5756

**Comment by brandonkelly** [comment]
👍 I’ll close this then, and move that one to the 4.0 milestone.

**Comment by brandonkelly** [comment]
This was actually originally covered by #2779, and it has been resolved for Craft 3.5.
