### ISSUE TITLE
[Feature Request] GraphQL Debug Log

### ISSUE THREAD

**Issue by andrewfairlie** [craftcms/cms#4936]
I haven't seen other GraphQL implementations do this, but a thought is that it would be great if we could request a field called something like `debug` which returns a log of the database requests so we can spot what in the query might be taking time so we can optimise it.

**Comment by narration-sd** [comment]
If the data you want were in a database table, you could just query that from any GraphQL...

First late night thought is that it could be done with a plugin

**Comment by brandonkelly** [comment]
You can use the Debug Toolbar for this! Make sure it’s enabled, and then look for the `X-Debug-Link` header on the API response. That will give you a URL you can go to, to view a full-page debug toolbar output of the API request.

<img width="682" alt="The X-Debug-Link header on a GraphQL API response" src="https://user-images.githubusercontent.com/47792/64860811-25cd1300-d5e3-11e9-9b62-859355dafb81.png">

**Comment by andrewfairlie** [comment]
Well that's just outstanding. Thanks @brandonkelly

**Comment by narration-sd** [comment]
ha, yes, forgot that...

They always accuse me of over-complicating, @andrewfairlie  ;)
Also, other matters not forgotten, just busy accomodating Craft motions
