### ISSUE TITLE
Entrys in Structure without slug or Group Function?

### ISSUE THREAD

**Issue by X-Tender** [craftcms/cms#4937]
I have the following structure in my page
<img width="307" alt="Bildschirmfoto 2019-09-13 um 10 57 54" src="https://user-images.githubusercontent.com/1413979/64850525-d522dd80-d615-11e9-9795-c2b2fa2a64d6.png">
Now I would like to achieve that when I got to "Items" that the slug of "Glosar" is not visible in the url. My Slug configuration is the following:
`{parent.uri}/{slug}`
So for "Items" I get `/fall-winter-2019/glosar/items` but I would like to get `/fall-winter-2019/items` the other pages "Damen" and all below should use the normal slug. so for example `/fall-winter-2019/damen/hats`.

So that "Glosar" behaves like a folder.

Did someone have an Idea? I've searched for a plugin but couldn't find anything.

**Comment by brandonkelly** [comment]
To clarify, this is what I think you are asking for:

Entry | URI
-- | --
Fall/Winter 2019 → Herren → Hats | `fall-winter-2019/herren/hats`
Fall/Winter 2019 → Damen → Hats | `fall-winter-2019/damen/hats`
Fall/Winter 2019 → Glosar → Items | `fall-winter-2019/items` _(no `glosar` segment)_

So Glosar is a special case, which doesn’t get a segment in subpages’ URIs.

You could pull that off by changing the section’s URI format to:

```
{{ parent.uri|replace('/glosar/', '/') }}/{slug}
```

**Comment by X-Tender** [comment]
That could work, I'l give it a try. Thank you.
