### ISSUE TITLE
"Update all" button doesn't show up anymore

### ISSUE THREAD

**Issue by benface** [craftcms/cms#4938]
### Description

Not sure when it started happening, but it's definitely happening in Craft CMS 3.3.3.

### Steps to reproduce

1. Go to Utilities > Update on an install where there are a couple plugins to update.
2. Notice there is no "Update all" button at the top right.

### Additional info

- Craft version: 3.3.3
- PHP version: 7.3.8
- Database driver & version: MySQL 5.7.26

**Comment by brandonkelly** [comment]
Can you send your `composer.json` and `composer.lock` files over to support@craftcms.com, with multiple updates showing up as available?

**Comment by benface** [comment]
@brandonkelly Done!

**Comment by brandonkelly** [comment]
Thanks @benface, we were able to reproduce with that, and have fixed it for the next release.
