### ISSUE TITLE
Can't query elements via lightswitch that haven't been resaved since adding the lightswitch field

### ISSUE THREAD

**Issue by benface** [craftcms/cms#4939]
### Steps to reproduce

1. Add a lightswitch field to an existing entry type's field layout.
2. Edit one of the entries and turn the lightswitch on (there need to be other entries of the same entry type, but don't edit them).
3. Try to query the other entries of that entry type in a template:
```
{% set entries = craft.entries.type(entryTypeHandle).lightswitchFieldHandle(false).all() %}
```
4. Notice no entries are returned, even though there are entries of that type where the lightswitch is off (the ones that haven't been edited).
5. Edit another one of these entries, don't change anything (keep the lightswitch off), and just resave it.
6. Try the same query again.
7. The last entry you edited is now returned.

### Additional info

- Craft version: 3.3.3
- PHP version: 7.3.8
- Database driver & version: MySQL 5.7.26

**Comment by brandonkelly** [comment]
Thanks for reporting! Just fixed that for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#e6cd1b1dc6fa80598738de87d207c39389908670 as 3.3.3",
  "...": "..."
}
```

Then run `composer update`.
