### ISSUE TITLE
[Feature Request] User element HUD should include email field

### ISSUE THREAD

**Issue by benface** [craftcms/cms#4942]
### Steps to reproduce

1. Create a Users field and add it to some field layout.
2. Select a user from that field.
3. Double-click on the selected user to open the user element HUD.
4. Notice there is a "Username" field (if `useEmailAsUsername` is `false`), as well as "First Name" and "Last Name", but no "Email" field (or "Photo" for that matter, but that's not as important). I understand not being able to change a user's email address from there, but the email address should at least be visible IMO.

### Additional info

- Craft version: 3.3.3
- PHP version: 7.3.8
- Database driver & version: MySQL 5.7.26

**Comment by benface** [comment]
@brandonkelly Any chance this could fit in 3.4 (or 3.5)? :)

**Comment by brandonkelly** [comment]
Changing their email is a little complicated due to email verification possibly being a requirement, so we could only show it at best for now, but element editor HUDs don't currently show any meta info like that. So I think this will be more of a 4.0 thing.

**Comment by brandonkelly** [comment]
Just added user metadata to user editor [slideouts](https://github.com/craftcms/cms/pull/8017) for 3.7:

<img width="1278" alt="Screenshot of a user editor slideout, with its metadata sidebar shown" src="https://user-images.githubusercontent.com/47792/120906880-ec87d280-c611-11eb-98f4-fb08a2883985.png">
