### ISSUE TITLE
Change button text on Asset update index dialog

### ISSUE THREAD

**Issue by proimage** [craftcms/cms#4943]
### Description
When updating the Asset index where there are missing folders or files, the resulting dialog box could stand to have better (clearer) button text:

![image](https://user-images.githubusercontent.com/1027523/64921464-2e347200-d7cc-11e9-8d71-7a9cc3520131.png)

IMO, the buttons would be better if they were "Yes, delete from index" (or just "Delete" for short) and "No, keep missing items in index" (or just "Keep") instead of "OK" and "Cancel".

### Steps to reproduce

1. Index some items in an Asset volume
2. Delete one or more of the items via OS file management (not via Craft)
3. Go to Utilities -> Asset Indexes
4. Click on "Update Asset Indexes"

### Additional info

- Craft version: 3.1.34.2

**Comment by brandonkelly** [comment]
Done!
