### ISSUE TITLE
Table field with no rows normalizes as `null` instead of an empty array

### ISSUE THREAD

**Issue by benface** [craftcms/cms#4945]
### Steps to reproduce

1. Create a field of type "Table" and add it to some field layout.
2. Get any element containing that field in PHP, e.g. `$entry = Entry::find()->section('sectionHandle')->one()`
3. Try to loop through the field's rows, e.g. `foreach ($entry->tableFieldHandle as $tableRow)`
4. `Invalid argument supplied for foreach()` because `$entry->tableFieldHandle` is `null` instead of an empty array.

### Additional info

- Craft version: 3.3.3
- PHP version: 7.3.8
- Database driver & version: MySQL 5.7.26

**Comment by brandonkelly** [comment]
This is clearly the intended behavior:

https://github.com/craftcms/cms/blob/f80576531d23f44f51dd04c5101de1593256cd6a/src/fields/Table.php#L370-L372

So you will just need to adjust your template to check for a value before looping through the table rows.
