### ISSUE TITLE
unable to load dynamic library 'mcrypt.so'

### ISSUE THREAD

**Issue by sufiyanpk7** [craftcms/cms#4946]
### Description

PHP Warning:  PHP Startup: Unable to load dynamic library 'mcrypt.so' (tried: /usr/lib/php/20170718/mcrypt.so (/usr/lib/php/20170718/mcrypt.so: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/mcrypt.so.so (/usr/lib/php/20170718/mcrypt.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

### Steps to reproduce

1.
2.

### Additional info

- Craft version:
- PHP version:7.2
- Database driver & version:apache
![Screenshot from 2019-09-17 01-04-02](https://user-images.githubusercontent.com/45423403/64987568-16054580-d8e7-11e9-891f-a456717b7601.png)

- Plugins & versions:

**Comment by angrybrad** [comment]
Sounds like your PHP config is trying to load the mcrypt.so module, but it doen't exist on your file system.

**Comment by BhoopendraChaurasia** [comment]
![image](https://user-images.githubusercontent.com/76529188/223379442-e401a563-93f3-4c11-99ab-f67ad1e67a59.png)

**Comment by BhoopendraChaurasia** [comment]
I have been done each possible changes but not getting proper result.

problem coming "Mcrypt is required"

**Comment by BhoopendraChaurasia** [comment]
Please help me

**Comment by brandonkelly** [comment]
@BhoopendraChaurasia For environmental questions like this, your best bet will be to reach out to support@craftcms.com. We should be able to help you get up and running from there.
