### ISSUE TITLE
Changing the field type in a matrix from Entries to a text-based one does not show the Translation Method

### ISSUE THREAD

**Issue by stevepiron** [craftcms/cms#4949]
### Description

In an existing matrix, when changing the type of a field from Entries to URL or Plain text, the dropdown menu titled Translation Method doesn't show until the matrix is saved and editing that field again.

### Steps to reproduce

1. In Settings > Sites make sure to have at least two sites.
2. Create a matrix with at least one block type and one field. Set the type of that field to "Entries"
3. Save the matrix
4. Edit the matrix: change the type of the field from "Entries" to "URL" or "Plain text". The Translation Method dropdown doesn't show.
5. Save the matrix
6. Edit the matrix again. This time it is possible to change the Translation Method. 

### Additional info

This bug might occur from changing from and to other field types than the ones stated above.

- Craft version: 3.3.0.1
- PHP version: 7.3.9
- Database driver & version: MySQL 5.7.27
- Plugins & versions:

|Name|Version|
|-|-|
|Amazon S3|1.2.5|
|Component-based Templating|dev-master|
|Language Redirector|1.2.0|
|Minify|1.2.9|
|Postmark|2.0.2|
|Redactor|2.3.3.2|
|SEO|3.2.21|

**Comment by brandonkelly** [comment]
Thanks for reporting! Just released Craft 3.3.4 with a fix.
