### ISSUE TITLE
Should `getIsPreview()` be true for shared drafts (not live preview)?

### ISSUE THREAD

**Issue by dennisfrank** [craftcms/cms#4950]
### Description

I am trying to add a HTML element to shared draft entries to clarify that this is a draft and _not_ the live entry. This element should only be displayed when the shared URL is used, not in the live preview in the panel. 

This is how I thought it should work: 

```twig
  {% if entry is defined and entry.isDraft and not craft.app.request.getIsPreview() %}
    <div>DRAFT</div>
  {% endif %}
```

But `craft.app.request.getIsPreview()` seems also to be true for shared Drafts that are not viewed in live preview.

### Steps to reproduce

1. Add `{{ craft.app.request.getIsPreview() }}` to a template.
2. Share a draft and open the generated URL (with `?x-craft-preview=` in the URL)
3. The output is `1` in the live preview **and** the shared draft

Or are there other/better ways to display a note just for shared drafts?

### Additional info

- Craft version: 3.3.3
- PHP version: 7.3.9
- Database driver & version: MySQL 5.7.21

**Comment by brandonkelly** [comment]
Yeah either way it’s a “preview” request.

You could just add the notice either way, but have some CSS that hides it, unless the body has a specific class on it, e.g. 

```css
.draft-notice {
    display: none;
}

body.not-iframe .draft-notice {
    display: block;
}
```

Then add some JS on the page that adds that `draft-notice` class if it’s not loaded in an iframe:

```twig
{% if entry.isDraft ?? false %}
  <div class="draft-notice">DRAFT</div>
  {% js %}
    if (window.self == window.top) {
      $(document.body).addClass('not-iframe');
    }
  {% endjs %}
{% endif %{}
```

**Comment by dennisfrank** [comment]
Thanks for the JS example @brandonkelly! And I also habe a small feature request:

Could you add an additional parameter to the URL of the iframe preview so that you can use it to control logic in the template? `&live-preview=1` for example.

`?x-craft-preview=xtIPdUO7Oj&token=Pq35jU_FAysneBo4E0UhOUSai3Yp6jFT&live-preview=1`

In the template you could then check for live preview like this:

```twig
  {% if craft.app.request.getQueryParam('live-preview') == true %}
    …
  {% endif %}
```

Without the need for Javascript or any additional markup or CSS in the template.

**Comment by brandonkelly** [comment]
Good idea. Going forward, that `x-craft-preview` query param will be `x-craft-live-preview` for Live Preview requests.

**Comment by dennisfrank** [comment]
Thanks @brandonkelly, that would be awesome! And all the best for Dot All 2019.
