### ISSUE TITLE
Default value for number fields does not appear

### ISSUE THREAD

**Issue by mlathrom** [craftcms/cms#4953]
### Description
The default number set on number fields does not display on the fields in sections or globals.

![default-value](https://user-images.githubusercontent.com/373889/65089001-4f35c800-d970-11e9-9d54-a0d1cf3a7b8d.png)

![default-value-empty](https://user-images.githubusercontent.com/373889/65089000-4f35c800-d970-11e9-8605-0b98c5691f37.png)

### Steps to reproduce

1. Create a new number field
2. Set a default value
3. Add number field to section or global set
4. Visit globals, look at number field or add entry in the section

### Additional info

- Craft version: 3.3.4.1
- PHP version: 7.3
- Database driver & version: MySQL 5.7
- Plugins & versions: Minify 1.2.9, Position Fieldtype 1.0.14, Redactor 2.4.0, Twigpack 1.1.8

**Comment by brandonkelly** [comment]
Default values only apply to *new* elements. Your globals, and any preexisting entries, will not get those default values. Just new entries.
