### ISSUE TITLE
Getting "Integrity constraint violation" when syncing project config sometimes

### ISSUE THREAD

**Issue by jishi** [craftcms/cms#4955]
### Description

When invoking `craft project-config/sync` I sometimes end up in a state where the info table has more than one row.

### Steps to reproduce

1. change project.yaml
2. run `craft project-config/sync`

### Additional info

- Craft version: 3.3.3 (happened in 3.2 and 3.3.0 as well)
- PHP version: 7.2.22
- Database driver & version: MySQL 5.6.10
- Plugins & versions: Redactor 2.3.3.2, Redactor Custom Styles 3.0.2, Amazon S3 1.2.5

I end up having an extra row with ID=2 in the info table at some point, and then when applying the project.yml changes, it does an update (with ID) without a where statement, thus throwing a:

```
Exception 'yii\db\IntegrityException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'
craft_1    | The SQL being executed was: UPDATE `info` SET `id`=1, `version`='3.3.3', ....
```

I have to manually remove the row from the database to get past this. It has never happened when applying changes from the web prompt. 

I am running with docker-compose which starts a MariaDB container and a nginx/php container with craft. On startup, it calls 

`craft migrate/all`
`craft project-config/sync`

And sometimes the migrate/all is called before the database has finished starting, giving me: 

```
craft_1    |
craft_1    |     Craft isn’t installed yet!
craft_1    |
craft_1    | Yii Migration Tool (based on Yii v2.0.21)
craft_1    |
craft_1    | Migrated up successfully.
```

This could be related, but it is very unclear why that would inject a single almost empty row into the info table? 

Either way, it would be nice to never have multiple rows in the info table, but it seems fair that it should at least have a WHERE statement when updating the project config, otherwise this seems like a recipe for disaster. 

From the table (I skipped id=1 since it is huge):

```
MariaDB [craft]> select * from info where id = 2;
+----+---------+---------------+-------------+--------+-----------+--------------+---------------------+---------------------+--------------------------------------+
| id | version | schemaVersion | maintenance | config | configMap | fieldVersion | dateCreated         | dateUpdated         | uid                                  |
+----+---------+---------------+-------------+--------+-----------+--------------+---------------------+---------------------+--------------------------------------+
|  2 | 3.3.3   | 3.3.3         |           0 |        |           | 000000000000 | 2019-09-18 11:38:43 | 2019-09-18 11:38:43 | 26568976-16dc-4dc1-a23d-ed943e008345 |
+----+---------+---------------+-------------+--------+-----------+--------------+---------------------+---------------------+--------------------------------------+
1 row in set (0.00 sec)
```

**Comment by angrybrad** [comment]
Can you send your composer.json, database dump and project.yaml file over to support@craftcms.com hopefully along with some reproducible steps as well?

**Comment by jishi** [comment]
I haven't been able to reliably reproduce it, but I'll see what I can do. I added a delay before the attempt to run the DB-migrations, which seems to have mitigated the extra rows in the info-table, so I'm starting to think that it is the `craft migrate/all` that actually misbehaves when it has trouble to connect to the database, making it sort of a race condition.

**Comment by angrybrad** [comment]
Going to go ahead and close this, but feel free to comment with any new information.
