### ISSUE TITLE
[FR] Move site settings into project config root

### ISSUE THREAD

**Issue by gglnx** [craftcms/cms#4957]
Our setup allows to add new websites in the production environment, but other settings should be in SCM and only changed by deployment. We've split our `project.yaml` into multiple files via `imports`. So `sites.yaml` is not part of our Git repo.

But the settings for which section on which site is active is part of the `sections` group. So `sections` and with it field layouts can't be part of the synced project configuration, too.

It would be great if `siteSettings` would move into `sites` or to the root level.

**Comment by brandonkelly** [comment]
There’s a ton of things that need to reference site UIDs throughout the project config, so this isn’t possible. If you need to manage sites on production, then you should just stop using `project.yaml` entirely.
