### ISSUE TITLE
Required field, filled in, displays "cannot be blank" error message

### ISSUE THREAD

**Issue by riekusdn** [craftcms/cms#4964]
### Description

When creating a new entry with a required field within a Matrix, an error will be displayed upon saving the entry, even when the required field is filled out. This only occurs when creating a new entry and adding and filling in the required field. When first creating the entry with a title only, then saving, editing again and adding the field, the error does not occur. 

### Steps to reproduce

1. Create a new entry which contains a Matrix field.
2. Add a block / field within the Matrix field with required values
3. Fill out the required field
4. Hit save

The edit screen will be presented with an empty value in the required field and the error message "cannot be blank"

before saving:
![Screenshot 2019-09-19 at 16 34 55](https://user-images.githubusercontent.com/52716006/65253770-81bffc00-dafb-11e9-9e9c-a18155ae2b17.png)

after saving:
![Screenshot 2019-09-19 at 16 35 09](https://user-images.githubusercontent.com/52716006/65253769-81276580-dafb-11e9-8006-1711776af07a.png)

### Additional info

PHP version	7.2.13
OS version	Linux 4.9.125-linuxkit
Database driver & version	MySQL 5.7.27
Image driver & version	GD 7.2.13
Craft edition & version	Craft Pro 3.3.4.1
Yii version	2.0.21
Twig version	2.11.3
Guzzle version	6.3.3
Imagine version	1.2.3-dev

Plugins
Admin Bar	3.1.8.1
Asset Rev	6.0.2
Bugsnag	2.0.4
CKEditor	1.0.0-beta.2
Cookies	1.1.11
Dumper	2.0.0
Freeform	3.4.1
HTTP2 Server Push	1.0.1
schema	1.0.3
SEO	3.6.2
Super Table	2.3.0
Video Embedder	1.1.4
XML Sitemap	1.0.9

Field configuration: 
![Screenshot 2019-09-19 at 16 31 46](https://user-images.githubusercontent.com/52716006/65253617-39084300-dafb-11e9-907e-6f986962c028.png)

**Comment by riekusdn** [comment]
Upon further inspection, this seems to be specific to the “CKEditor” field type. Should I report the bug in that repo?

**Comment by riekusdn** [comment]
I've created a PR for ckeditor which fixes this: https://github.com/craftcms/ckeditor/pull/21

**Comment by jamiematrix** [comment]
I've upped the version to "^12.3.1" and run 'composer update' but ckeditor doesn't seem to update.
