### ISSUE TITLE
problem with count of element type translation 

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#4970]
### Description
yesterday i sent a [Pull request for Persian language](https://github.com/craftcms/cms/pull/4969) 

at first i have to say in Persian langauge we have plural form of words and we use it sometimes - for example in sidebar of CP ,or settings page- translations for users, entries, categories, sites and...  are and should be in plural form like English is.

but when we talk or write about how many or count of items we always use singular form of names even if there are many items (imagine something like 1 entry, 2 entry, 1000 entry) so translation of  [this line](https://github.com/craftcms/cms/blob/8accf5860f06c24185258a74dcc7d18313275703/src/web/assets/cp/src/js/BaseElementIndex.js#L1547) generate wrong count text when response.count is [bigger than one](https://github.com/craftcms/cms/blob/8accf5860f06c24185258a74dcc7d18313275703/src/web/assets/cp/src/js/BaseElementIndex.js#L1544)

when Persian language is ready to be in user language list, i check it again if there are similar issues.

**Comment by brandonkelly** [comment]
Thanks for pointing that out! I’ve just fixed this for the next release.

Here’s how it will look when there are less than 50 entries:

<img width="68" alt="‘6 entries’ translated into Persian" src="https://user-images.githubusercontent.com/47792/65559118-38522100-deee-11e9-92ac-4cfc19e01ba2.png">

And here’s how it will look if there are more than 50:

<img width="201" alt="‘1-50 of 56 entries’ translated into Persian" src="https://user-images.githubusercontent.com/47792/65559135-4acc5a80-deee-11e9-85f9-18341ef12b96.png">

Both of those appear to be pulling from the singular `Entry` translation correctly now. All other languages will continue to use the plural version when appropriate, however other languages do have the option to customize these strings as well now, by translating the following strings:

https://github.com/craftcms/cms/blob/fa2b44d677c1200ed6d15d13b8d6c66eff7d6a2c/src/translations/en/app.php#L1215

https://github.com/craftcms/cms/blob/fa2b44d677c1200ed6d15d13b8d6c66eff7d6a2c/src/translations/en/app.php#L1448

**Comment by vnali** [comment]
thank you @brandonkelly!
