### ISSUE TITLE
Tiny documentation error for craft.app.request.isPreview

### ISSUE THREAD

**Issue by evanwarner** [craftcms/cms#4971]
Discovered in a [Discord conversation](https://discordapp.com/channels/456442477667418113/456442867163070466/624954384765157376):
With the change in v3.2.1 from `isLivePreview` to `isPreview`, the change description on the [Changes in Craft 3](https://docs.craftcms.com/v3/changes-in-craft-3.html#template-functions) page is now out of date. I know `isLivePreview` was only deprecated in v3.2.1 but it doesn't seem to work anymore.

**Comment by dougstjohn** [comment]
@evanwarner If you go to the bottom of that page, you can edit it and submit a PR.

**Comment by evanwarner** [comment]
Done! Looks like Brad also moved all documentation to a [new repository](https://github.com/craftcms/docs) a few hours ago, so this issue no longer pertains to this repo.
