### ISSUE TITLE
FR: Re-order Globals like Entries

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#4972]
Could we add an option for organising Globals in the same way that Entries can be? For example, it doesn't make much sense that Footer comes above Header here:

![image](https://user-images.githubusercontent.com/1250017/65385808-82df6c00-dd3b-11e9-8dcc-31832c438542.png)

Having the modal that lets you organise Sections within the Entries part of the control panel would be great:

![image](https://user-images.githubusercontent.com/1250017/65385814-9c80b380-dd3b-11e9-9c35-479f2797ab9d.png)

**Comment by mmikkel** [comment]
Really hoping this gets added in a 3.x release (possibly 3.6?).

**Comment by brandonkelly** [comment]
Added to the milestone :)

**Comment by Visiluna** [comment]
Any update on when we might see this feature implemented?

**Comment by darylknight** [comment]
@Visiluna This is on the 4.0 milestone, which isn't out yet. No release date as far as I know either.

**Comment by Visiluna** [comment]
@darylknight It was in the 3.6 milestone once upon a time. I was hoping to see this before 4.0, but I guess we'll have to wait.

**Comment by brandonkelly** [comment]
Added this for 3.7 (#8052).
