### ISSUE TITLE
Twig `attr` filter encoding `href` and `src` attributes

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#4984]
### Description

The new `attr` filter has the (in my opinion) unfortunate side effect of HTML encoding all attribute values for the tag that the filter operates on (as in, all of them – not only the attributes you're adding or modifying using the filter).

I know this is due to Yii's `BaseHtml::renderTagAttributes()` method running all the values through `htmlspecialchars()`, so I don't know if a fix on Craft's end is feasible. But, this unexpected behaviour can definitely lead to some gotcha moments, especially for attributes like `src` and `href`, where e.g. ampersands in query strings being encoded to `&amp;` can be an issue (I just realized some of my Imgix URLs were failing due to this).

### Steps to reproduce

```twig
{% filter attr({ class: 'foo' }) %}
    <img src="image.jpg?width=100&height=100" />
{% endfilter %}
```

Renders `<img class="foo" src="image.jpg?width=100&amp;height=100" />`

### Additional info

- Craft version: 3.3.4.1
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
In your example, the correct behavior should be to encode the `&` to `&amp;`, as the HTML you posted is actually invalid.

However if it already is encoded as `&amp;`, the filter should *not* be double-encoding it to `&amp;amp;`, which it was doing. So I’ve just fixed that for the next release.

**Comment by mmikkel** [comment]
Ah! You're absolutely correct. And the double `&amp;amp;` was my actual issue, of course. Thanks for the quick fix!

**Comment by samhibberd** [comment]
@brandonkelly i'm not sure if this is related, a separate issue or me not understanding something but seeing some inconsistencies between rendering HTML chars when run using the `attr()` function:

```html
<input {{ attr({
    type: "submit",
    value: "Go &rarr;",
    class: "btn btn-green cursor-pointer"
}) }}>

<input type="submit" value="Go &rarr;" class="btn btn-green cursor-pointer">
```

I would expect these two submit buttons should render exactly the same, but they don't?

<img width="596" alt="Screenshot 2022-03-09 at 13 47 38" src="https://user-images.githubusercontent.com/1846063/157454778-15b86ae6-9c42-4ca1-b0dc-079321dd57c6.png">

<img width="236" alt="Screenshot 2022-03-09 at 13 50 44" src="https://user-images.githubusercontent.com/1846063/157454856-a2e4cf32-6d96-4444-90fa-6edee00536e6.png">

**Comment by brandonkelly** [comment]
@samhibberd the `&` is probably getting encoded by the output tag (`{{ }}`), not the `attr()` function. Add `|raw` after the `}}` to avoid that.

```twig
<input {{ attr({
    type: "submit",
    value: "Go &rarr;",
    class: "btn btn-green cursor-pointer"
})|raw }}>
```

or just use the [tag()](https://craftcms.com/docs/3.x/dev/functions.html#tag) function:

```twig
{{ tag('input', {
    type: "submit",
    value: "Go &rarr;",
    class: "btn btn-green cursor-pointer"
}) }}
```
```

**Comment by samhibberd** [comment]
Hey @brandonkelly, tried that and the input tag, same deal for me, I must be missing something really obvious :(

Tested the following in a fresh template, with no other content, and only the first raw html version outputs correctly:

<img width="292" alt="Screenshot 2022-03-14 at 11 41 57" src="https://user-images.githubusercontent.com/1846063/158165325-160b5cce-2e5a-42b8-b444-8d80f6db61fb.png">

```html
<input type="submit" value="Go &rarr;">

<input {{ attr({
    type: "submit",
    value: "Go &rarr;",
}) }}>

<input {{ attr({
    type: "submit",
    value: "Go &rarr;",
})|raw }}>

{{ tag('input', {
    type: "submit",
    value: "Go &rarr;",
}) }}
```

**Comment by samhibberd** [comment]
Cool. Thanks @brandonkelly
