### ISSUE TITLE
setFieldValues no longer respects translatable fields in a MatrixBlock

### ISSUE THREAD

**Issue by colinmeinke** [craftcms/cms#4986]
I'm not sure at what version this changed, but previously I could save a Matrix field that had translatable fields programatically, like so:

```
$element = Entry::find()->section('test')->siteId(2)->one();

$element->setFieldValues([
  'matrixFieldHandle' => [[ 'type' => 'test', 'fields' => ['test' => 'test']]]
]);

Craft::$app->elements->saveElement($element);
```

And this would only update the MatrixBlock translatable field for site 2.

However, in the most recent versions of Craft, this will save the field across all sites. Is this now expected? And if so, how would you now target a specific site?

**Comment by brandonkelly** [comment]
The behavior depends on two things: the Matrix field’s Propagation Method setting, and the sub-field’s Translation Method setting. What are those set to?

**Comment by colinmeinke** [comment]
@brandonkelly this is happening where the the matrix field's propagation setting is "Save blocks to all sites the owner element is saved in", but the child plain text field has a translation setting of "Translate for each site".

**Comment by brandonkelly** [comment]
OK so in that case when you edit an existing block, it should only save the field value for the site you are saving it in.

I think the issue is that in your example code, you aren’t editing an existing block; you are creating a new one. You need to set the keys of the array you are setting on the Matrix field to the existing block IDs:

```php
$element->setFieldValues([
    'matrixFieldHandle' => [
        '100' => ['type' => 'test', 'fields' => ['test' => 'test']],
    ],
]);
```

**Comment by colinmeinke** [comment]
Okay, thanks for the explanation :)
