### ISSUE TITLE
Collapsing a Matrix block with long content makes it render wider than viewport

### ISSUE THREAD

**Issue by fantasticmachine** [craftcms/cms#4987]
When collapsing matrix blocks the header of the matrix block shows a preview of the content. If the content is a long block of text then this causes the matrix block to render wider than the viewport and pushes the UI controls for the block off screen with no way to scroll to view them.

Content is shown in preview form in the header of the collapsed block, it isn't being truncated at all.

### Steps to reproduce

1. Create a matrix block with a Rich text field in it.
2. Add long content to the Rich text field
3. Collapse the matrix block

- Craft version: 3.3.3

**Comment by brandonkelly** [comment]
I’m not able to reproduce - the text is getting truncated as expected:

<img width="1091" alt="A collapsed Matrix block with truncated preview text" src="https://user-images.githubusercontent.com/47792/65604959-278cc400-df5d-11e9-835e-f9473c19ee67.png">

Do you have any custom CSS styles applied to the Matrix field?

**Comment by fantasticmachine** [comment]
No custom styles that I'm aware of but we do have a few plugins installed - none should be adding styles though
I'll happily investigate it further if you want to close this and I'll reopen it if I can find out any more.

**Comment by brandonkelly** [comment]
Sounds good 👍
