### ISSUE TITLE
No warning of failed config sync

### ISSUE THREAD

**Issue by bramus** [craftcms/cms#4988]
### Description

If you deploy an altered `config/project.yaml` file, and then visit `/admin` you must first sync the changes. That page then internally calls `/admin/actions/config-sync/apply-yaml-changes` over XHR.

When said call fails (here due to a memory allocation error) the user is not notified of this failure. The page keeps on showing the spinner and the "Applying changes from the config file" text.

It's only when opening the dev tools that one can see the call has actually failed:

![Screenshot 2019-09-25 at 12 18 08](https://user-images.githubusercontent.com/213073/65601496-76108180-dfa2-11e9-842f-a3e2d3d0adc0.png)

It'd be better that the page notifies the user of the failure of the call.

For reference, here's the full error from `web.log`:

```
2019-09-25 12:16:21 [-][-][-][error][yii\base\ErrorException:1] yii\base\ErrorException: Allowed memory size of 33554432 bytes exhausted (tried to allocate 4194312 bytes) in /home/dencstudio/vendor/craftcms/cms/src/helpers/StringHelper.php:285
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
2019-09-25 12:16:20 [-][-][-][info][application] $_GET = [
    'p' => 'admin/actions/config-sync/apply-yaml-changes'
]
```

### Additional info

- Craft version: 3.3.4.1
- PHP version: 7.3.9
- Database driver & version: MySQL 5.7.27
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
Thanks for pointing that out! I was able to reproduce in the event that the request timed out, and fixed for the next release.
