### ISSUE TITLE
[Feature Request] Helper method to check if we're on the home page

### ISSUE THREAD

**Issue by benface** [craftcms/cms#4993]
Right now we can check if `entry.uri` is empty, but it would be helpful to have a `craft.request.isHome` helper.

**Comment by brandonkelly** [comment]
I wouldn’t say that being on the homepage is a property of the _request_. There is no homepage, even if you access `/`, if you’re running Headless Mode for example. I did just add a `getisHomepage()` method to elements though, so you could start doing

```twig
{% if entry.isHomepage ?? false %}
```
