### ISSUE TITLE
Inconsistent sibling queries for entries in structures

### ISSUE THREAD

**Issue by michaelhue** [craftcms/cms#4997]
### Description

I noticed a problem with `prevSiblingOf` and `nextSiblingOf` queries. For some entries, these where always `null`, even if they are surrounded by siblings inside the structure.

I wasn't able to pinpoint the reason for this, but I found that the problem could be reproduced consistently in live preview.

Given the following entry structure:

```
+ Section (propagates to site groups)
    + (#2) Parent Entry
        + (#3) Entry One
        + (#4) Entry Two
        + (#5) Entry Three
```

and given the following template code:

```twig
Entry ID:    {{ entry.id }}
Parent ID:   {{ entry.getParent().id ?? 'none' }}
Prev ID:     {{ craft.entries.prevSiblingOf(entry).one().id ?? 'none' }}
Next ID:     {{ craft.entries.nextSiblingOf(entry).one().id ?? 'none' }}
Sibling IDs: {{ craft.entries.siblingOf(entry).ids()|join(', ') }}
```

**(A)** Output for site request for entry ID 4:

```
Entry ID:    4
Parent ID:   2
Prev ID:     3
Next ID:     5
Sibling IDs: 3, 5
```

**(B)** Output for live preview (and sometimes site request) for entry 4:
```
Entry ID:    1877
Parent ID:   2
Prev ID:     none
Next ID:     none
Sibling IDs: 3, 4, 5
```

Output B has a different entry ID, has no prev/next IDs and includes the original entry id in the siblings.

**Note:** This is not just true for live preview requests, for some entries every site request also produces this result.

### Steps to reproduce

Not sure, to be honest. Some entries are ok, some never show the correct siblings. I think it may be related to revisions.

### Additional info

- Craft version: Craft Pro 3.3.5
- PHP version: 7.3.4
- Database driver & version: MySQL 5.6.39

**Comment by michaelhue** [comment]
I added the following workaround in my template in order to get consistent results:

```twig
{% set children = craft.entries.descendantOf(entry.getParent()).ids() %}
{% set position = children|indexOf(entry.id) %}

{% set prevId = position > 0 ? children[position - 1] : null %}
{% set nextId = position < (children|length - 1) ? children[position + 1] : null %}

{% set prevEntry = prevId ? craft.entries.id(prevId).one() : null %}
{% set nextEntry = nextId ? craft.entries.id(nextId).one() : null %}
```

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just fixed some reliability issues with those params for the next release.
