### ISSUE TITLE
Display problem for fields name in entries after upgrading to 3.3.5

### ISSUE THREAD

**Issue by xavierdemoor** [craftcms/cms#5002]
### Description
_Note: I have this problem only with 3.3.5 version. I tried a downgrade and the problem was gone with previous version._

The fields name is not correctly displayed in entries editing. It gives me this:
`Titre de l&#039;article` in place of `Titre de l'article`

### Additional info

- Craft version: 3.3.5
- PHP version: 7.3.9
- Database driver & version: mysql 5.7.24
- Plugins & versions:

**Comment by john-henry** [comment]
This is also a breaking change for me if I'm trying to do things like `entry.title|camel`. It is not dealing with html entities and leaving them in.

**Comment by darylknight** [comment]
I noticed this in 3.3.5 too - it's now showing ascii versions of characters like < and >.

Also happening with the Redactor plugin:

![image](https://user-images.githubusercontent.com/1250017/65762696-412f3680-e12a-11e9-9ad4-4b5366bada7d.png)

**Comment by cuebit** [comment]
Also getting this issue in the CP after upgrading to 3.3.5 specifically with SproutSEO where `forms.textField` is being using with labels containing html i.e. icons.

<img width="1202" alt="Screenshot 2019-09-27 at 16 33 23" src="https://user-images.githubusercontent.com/1493221/65782067-d0494800-e144-11e9-8cd3-2bbc5c3ce22f.png">

**Comment by brandonkelly** [comment]
Thanks for reporting, all! We just released Craft 3.3.6 with a fix for this.

**Comment by john-henry** [comment]
@brandonkelly Using `{{ entry.title|camel }}` is still retaining an ampersand if used in the title where it stripped it prior to Craft 3.3.5

**Comment by brandonkelly** [comment]
@john-henry Do you know what version you were coming from? We didn’t change anything related to that filter in 3.3.5, And I just tested `{{ 'Pixel & Tonic'|camel }}` in 3.3.0 and even there it still output `pixel&Tonic`.

**Comment by john-henry** [comment]
@brandonkelly Hmmm OK good point. May not have been related to original issue so. It was stripping it in Craft 3.1.19 defo
