### ISSUE TITLE
[FR] Further improve pageInfo with pagination TWIG tag

### ISSUE THREAD

**Issue by hiasl** [craftcms/cms#5005]
### Description
Currently the TWIG tag for "paginate" provides a lot of useful links and infos.

However for me there is one thing missing, which is always time consuming when creating paginations, namely the direct links to certain pages (Google Style, see link below at the end of the results)
[https://www.google.at/search?q=craft+cms&safe=off&start=90]

I am talking about those direct links to result pages. Initially pages 1-10, and further on +/- 5 pages around the current one until you get the last 10 pages.

```
{% for link in pageInfo.getDynamicRangeUrls(5) %}
... Link here ...
{% endfor %}
```

Maybe with an option, to also get the first and the last page link:

```
{% for link in pageInfo.getDynamicRangeUrls(5, true) %}
... Link here ...
{% endfor %}
```

My FR is actually a further improvement to the "Nearby Page Links" Sample in the documentation

Would be really cool to have something like that. 

### Additional info

- Craft version: 3.3.5
- PHP version: 7.2

**Comment by hiasl** [comment]
I just added it myself and created a pull request: https://github.com/craftcms/cms/pull/5006

**Comment by brandonkelly** [comment]
Added for Craft 3.4. Thanks again for the PR!
