### ISSUE TITLE
Live preview not working for third level deep element in structure

### ISSUE THREAD

**Issue by texasbaptists** [craftcms/cms#5009]
### Description
I have a pages that are level three in the page structure or more.
example.com/grandparent/parent/page

Pages at this level work when published. When unpublished the share link with a token will work. But live preview will not work. If I move the page to level two: example.com/parent/page live preview works. 

### Steps to reproduce

1. Make an entry that is the child of a page that is a child. 
2. Click live preview button. 

### Additional info

- Craft version: 3.3.4.1, 3.3.5
- PHP version: 7.2.20
- Database driver & version: MySQL 5.7.27
- Plugins & versions:

**Comment by brandonkelly** [comment]
Live Preview loads the exact same URL as the Share button – just in an iframe rather than a new browser tab.

Try opening your browser’s console, _then_ open Live Preview, and see if any issues are reported in your console.

**Comment by texasbaptists** [comment]
False alarm. It seems to have been an issue with my adblocker. Not sure why pages three levels deep were getting blocked but not other live preview pages...

**Comment by brandonkelly** [comment]
Huh, weird. Glad it’s working though :)
