### ISSUE TITLE
"Update Entry" button for drafts is counter-intuitive to end-users

### ISSUE THREAD

**Issue by huelabs** [craftcms/cms#5011]
### Description
The intent of the "Update Entry" is unclear. Will the button save the draft or publish the draft? Obviously the button publishes the draft, which is supercritical to know for busy content publishers. Can you make this button more descriptive such as "Publish Draft"?

The habit of hitting the red "Save" button is engrained in my users, so the natural behavior after making changes to a draft is to hit the red button. Not good ATM. Thanks for considering!

![draft](https://user-images.githubusercontent.com/132374/65803369-3fb63c00-e133-11e9-8863-49d2bd723931.jpg)
![draft--revised](https://user-images.githubusercontent.com/132374/65803376-447af000-e133-11e9-9dfb-edbe1470c521.jpg)

- Craft version: 3.3.4.1

**Comment by brandonkelly** [comment]
The button says “Publish changes” now in 3.4, per f9b3af9b5c5ecd0cf9155db4fbc668dafb1a3453.
