### ISSUE TITLE
error `Failed to instantiate component or class`  after update craft to 3.3.6 

### ISSUE THREAD

**Issue by kos76** [craftcms/cms#5012]
### Description
Hi!
I use function {% do view.registerAssetBundle("assetBundle\\LandingPageAssetBundle")
in my main layout 
after update craft to 3.3.6 I get error 
Invalid Configuration – yii\base\InvalidConfigException
Failed to instantiate component or class "assetBundle\LandingPageAssetBundle".
Class assetBundle\LandingPageAssetBundle does not exist

namespace and alias set up as described here 
https://docs.craftcms.com/v3/extend/asset-bundles.html
all worked fine with craft 3.1.33
### Steps to reproduce

1. update craft to 3.3.6
2. open page where use {% do view.registerAssetBundle('')

### Additional info
PHP version  7.1.32
Linux 4.15.0-55-generic
MySQL 5.7.27
Imagick 3.4.4 (ImageMagick 6.9.7-4)
Craft Solo 3.3.6
Yii version 2.0.21
Twig version   2.11.3
Guzzle version  6.3.3

**Comment by brandonkelly** [comment]
Do you have your `assetBundle` namespace properly configured as an [autoload root](https://getcomposer.org/doc/04-schema.md#autoload) in `composer.json`?

Try running `composer update` manually and see if that helps.

**Comment by kos76** [comment]
@brandonkelly  thank you very much, this solved the problem.

**Comment by kos76** [comment]
@brandonkelly, thank you very much, this solved the problem
