### ISSUE TITLE
List icon is missing in user/index page in rtl CP

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#5018]
list icon is missing in user/index page in rtl CP
i am not sure, maybe because [this line](https://github.com/craftcms/cms/blob/d01d0afdb3c2132e6cbd0a0cde0a20988efd08c0/src/web/assets/cp/dist/css/_main.scss#L110) overwrites [this line](https://github.com/craftcms/cms/blob/d01d0afdb3c2132e6cbd0a0cde0a20988efd08c0/src/web/assets/cp/dist/css/_main.scss#L101)
![65758822-936e5880-e126-11e9-85fe-c99aeb59311b](https://user-images.githubusercontent.com/55586085/65837160-19de9200-e301-11e9-8444-38c34f25bc0c.png)

**Comment by brandonkelly** [comment]
Fixed that for the next release, thanks for reporting!
