### ISSUE TITLE
Structure live preview descendantOf not working

### ISSUE THREAD

**Issue by vincentvis** [craftcms/cms#5021]
### Description

In my template i show a list of descendants of the current parent entry (grouped by level 2 as 'sub-'parent and level 3 as children of those 'sub' parents)

The main issue is that descendantOf() returns no results in live-preview even though it works fine in de site itself. The query looks like this:

``` TWIG
{% set groupedOnLevel = craft.entries().descendantOf(entry).all() | group('level') %}
```

After that I want to display them like this:

``` TWIG
{% set levelTwo = groupedOnLevel[2] %}
{% set levelThree = groupedOnLevel[3] | group('parent.slug') %}
<div class="o-layout o-margin--large">
  {# loop over things in level 2 #}
  {% for parentItem in levelTwo %}
    <div class="o-cell">
      <h3>{{ parentItem.title }}</h3>
      
      {% if levelThree[parentItem.slug] is defined %}
        <ul class="c-list__arrow t-text">
          {% for child in levelThree[parentItem.slug] %}
            <li>
              <a href="{{ child.url }}">
                {{ child.title }}
              </a>
            </li>    
          {% endfor %}
        </ul>
      {% endif %}
    </div>
  {% endfor %}
</div>
```

On the site it works, in live-preview the `craft.entries().descendantOf(entry).all()` query returns nothing
Trying `{{ entry.hasDescendants() }}` gives 'true' in both live-preview and site. So it does recognize that there should be something. 

### Steps to reproduce

1. Create structure
2. let some entry have some descendants
3. show descendants in template with `craft.entries().descendantOf(entry).all()` 

### Additional info

- Craft version: Craft Pro 3.3.6
- PHP version: 7.3.9
- Database driver & version: MySQL 5.5.5

**Comment by michaelhue** [comment]
Possibly related to #4997.

**Comment by brandonkelly** [comment]
Also fixed for the next release!
