### ISSUE TITLE
Loading assets after changing volume type

### ISSUE THREAD

**Issue by Willbv** [craftcms/cms#5022]
I have just been testing out the Amazon S3 plugin and got everything up an running but the images are still using the old base URLs until I go to the entry section or specific entry (have some inconsistent results on which pages seem to update this). After I have loaded the entry or section and then view the image again it correctly uses the S3 base URL that is set.

The images are queried from the CMS using the CraftQL plugin (Not Craft's Graph QL integration) I'm not sure if this could have any contribution to the issue.

1. Create local asset volumes
2. Upload images and set them on some entries
3. Update the asset volumes to the S3 from the Amazon S3 plugin
4. Update asset indexes
5. View front end render of image
6. Load the section and or entry with an image
7. View front end render of image again

- Craft version: Craft Pro 3.3.6
- PHP version: 7.3.9
- Database driver & version: MySQL 5.7.27
- Plugins & versions:
    1. Amazon S3: 1.2.5
    2. CraftQL: 1.3.4

**Comment by brandonkelly** [comment]
Sounds like a caching issue. Does CraftQL have a cache that you can clear?

**Comment by Willbv** [comment]
@brandonkelly There is nowhere that I can see to clear a cache, I'm digging into it to see if it could be something in our setup but haven't had any caching issues with it before

**Comment by brandonkelly** [comment]
Yeah if not CraftQL then maybe part of the infrastructure, or perhaps another caching plugin, like Blitz or Preparse. Craft doesn’t cache asset URLs anywhere itself though, so it’s not going to be a Craft issue.
