### ISSUE TITLE
Where is 3.1.34.3

### ISSUE THREAD

**Issue by sjwarner-bp** [craftcms/cms#5023]
# Description
The 3.1.34.3 can't be found when changing the URL to the download.craftcdn.com pattern (i.e. I get a 404 when looking at [https://download.craftcdn.com/craft/3.1/Craft-3.1.34.3.zip] (https://download.craftcdn.com/craft/3.1/Craft-3.1.34.3.zip)

This structure works for other patterns, such as 3.1.34.2. I'd specifically like 3.1.42.3, as it seems to be a breakpoint.

# Steps to reproduce
Go to [https://download.craftcdn.com/craft/3.1/Craft-3.1.34.3.zip](https://download.craftcdn.com/craft/3.1/Craft-3.1.34.3.zip)
Expect linked file
Get a 404

# Additional info
Craft version: n/a
PHP version: n/a
Database driver & version: n/a
Plugins & versions: n/a

Thanks

**Comment by angrybrad** [comment]
Sorry about that... should be there now.

**Comment by sjwarner-bp** [comment]
Thanks @angrybrad 🙌

**Comment by sjwarner-bp** [comment]
Hi @angrybrad - thanks for getting back to me.

I've just tried to pull it down this morning. It seems as though it's version `3.3.6` of Craft though?

Run the following script to obtain the internal Craft CMS version for a given archive, e.g.:

```
VERSION=3.1 BUILD=34.3 sh -c 'echo $VERSION.$BUILD && curl https://download.craftcdn.com/craft/$VERSION/Craft-$VERSION.$BUILD.zip -s -o /tmp/craft.zip && rm -rf /tmp/craft && unzip -q /tmp/craft.zip -d /tmp/craft && grep version /tmp/craft/vendor/craftcms/cms/composer.json'
```

Am I missing something?

**Comment by sjwarner-bp** [comment]
Hi @angrybrad - any progress on this? :slightly_smiling_face:

**Comment by nettum** [comment]
`composer.lock` file seems incorrect for that release :/
```
            "name": "craftcms/cms",
            "version": "3.3.6"
```

**Comment by angrybrad** [comment]
Should be able to look at it today.

**Comment by angrybrad** [comment]
and by today... I mean tomorrow morning.

**Comment by angrybrad** [comment]
Should be resolved now!
