### ISSUE TITLE
Error when using entries as part of a section URI with drafts in Craft > 3.2

### ISSUE THREAD

**Issue by kringkaste** [craftcms/cms#5024]
### Description
When you start editing an entry, Craft will automatically create a new draft of the entry. If you have a section with an URI containing an entry content like this e.g.

```
magazine/{articleCategory.0.slug}/{slug}
```

you cannot create a new entry anymore. You get a PHP error like this:

```
Error: Method name must be a string in /local/vendor/twig/twig/src/Extension/CoreExtension.php:1485
Stack trace:
#0 /local/vendor/craftcms/cms/src/helpers/Template.php(105): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\db\CategoryQuery), 0, Array, 'any', false, false)
#1 /local/storage/runtime/compiled_templates/79/794b3ea68b8b93f8489dc7a14d19ee98b58bee110a49789a620daa7d96850df6.php(39): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\db\CategoryQuery), 0, Array)
[...]
```

This is because the URI is processed by Twig on creating the draft but there is no entry set at this point. So rendering der URI fails and you can't create a new entry.

Did we miss the announcement that this form of URI will not longer work or do we have to change the URI format of the section somehow? We used this kind of URI since Version 1 and this was no problem until now.

### Steps to reproduce

1. Create a section with URI containing an entry field content
2. Try to create a new entry.

### Additional info

- Craft version: 3.3.6
- PHP version: 7.2
- Twig: 2.11.3

**Comment by kringkaste** [comment]
We could fix this with a condition within the URI. I'm almost sure that you couldn't use conditions in URI formats at an earlier time. But I'm not sure and, as I said, until the introduction of drafts, that wasn't a problem either.

Maybe you could catch this kind of error before Twig creates this PHP error, this would save a lot of time :)

**Comment by brandonkelly** [comment]
That `.0` syntax was [deprecated](https://docs.craftcms.com/v3/changes-in-craft-3.html#treating-queries-as-arrays) in Craft 3, and could have caused the same error in 3.0 or 3.1 if you had attempted to save an entry without a category selected.

If you change the URI format to this, it will work again for you (and stop logging new deprecation errors):

```
magazine/{articleCategory.one().slug}/{slug}
```
