### ISSUE TITLE
Eager loading single entry page matrix field live preview not working

### ISSUE THREAD

**Issue by icreatestuff** [craftcms/cms#5027]
### Description
Similar to this closed thread https://github.com/craftcms/cms/issues/4873 but I'm using what seems to be a legitimate core craft mechanism to eager load content on the injected _entry_ variable of a single entry page.

The gist is I have a matrix field (`contentBlocks`) which I eager load and then loop over with the following code:

```twig
{% do craft.app.elements.eagerLoadElements(
    className(entry),
    [entry],
   ['contentBlocks', image']
) %}

{% for block in entry.contentBlocks %}
    {{ block.type.handle }}
{% endfor %}
```

Loading the single entry webpage URL loads the matrix block content perfectly. Viewing this entry through live preview however reveals that `entry.contentBlocks` is an empty array even though there are matrix blocks added to the form within live preview.

It's worth noting that in the above example the eager loaded image asset is rendered and updates as I swap out the image within live preview, so the issue seems specifically related to matrix fields.

Is this the right way to eager load content on a single entry or am I missing something else?

Many thanks

### Steps to reproduce

1. Create an entry that has a single entry page URL and a matrix field
2. In the entry template add the code above
3. Load up an entry in live preview and notice how none of the block content is displayed

### Additional info

- Craft version: 3.3.3
- PHP version: 7.2.20
- Database driver & version: MySQL 5.7

**Comment by brandonkelly** [comment]
Not sure why that’s not working at first glance, but there’s no point in eager-loading the Matrix blocks themselves if you’re only loading them for a single parent entry; that’s actually going to slow things down a bit.

**Comment by brandonkelly** [comment]
While it’s still true that you shouldn’t eager-load Matrix blocks themselves when you already have the entry, it does turn out that there was a bug that prevented it from working. That has been fixed for the next release.

**Comment by icreatestuff** [comment]
Thanks for the heads up Brandon and for the upcoming fix.
