### ISSUE TITLE
Entries with {slug} in the URI format need to be saved twice

### ISSUE THREAD

**Issue by daveyjones** [craftcms/cms#5028]
### Description

Entries with {slug} in the URI format need to be saved twice

### Steps to reproduce

1. Create a section with `{slug}` as the URI format.
2. Create a new entry in the section, specify a title, and save.
3. An orange dot appears next to the title of the newly created entry.
4. Navigating to the entry results in a 404 error `Template not found: {slug}`.
5. Open the entry and save again.
6. A green dot appears next to the title of the newly created entry.
7. Navigating to the entry is successful.

### Additional info

- Craft version: Craft Pro 3.3.6
- PHP version: 7.2.19
- Database driver & version: MySQL 5.7.27
- Plugins & versions: Cookies 1.1.11, Do It Yourself widget 2.0.1, Imager v2.3.0

**Comment by brandonkelly** [comment]
Sounds like you added the `{slug}` to the Template setting rather than the Entry URI Format setting.
