### ISSUE TITLE
defaultCookieDomain doesn't seem to be used for Craft PHP session

### ISSUE THREAD

**Issue by oddnavy** [craftcms/cms#5029]
### Description
defaultCookieDomain doesn't seem to be used for the Craft PHP session cookie but is used for other Craft cookies even when `session.cookie_domain=''` in php.ini.

`CRAFT_CSRF_TOKEN`, username, and identity all use the correct domain for cookies but `PHPSESSID` does not.

If we manually set the `session.cookie_domain` in `web/index.php` and retry it works as intended.

```php
ini_set('session.cookie_domain', '.example.tld');
```

### Steps to reproduce
1. Serve Craft from a subdomain `subdomain.example.tld`
1. Set `defaultCookieDomain => '.example.tld'` in general.php
2. Check devtools Resources tab for `PHPSESSID` cookie domain. It will not be set to the value set in defaultCookieDomain

### Additional info

- Craft version: Craft Pro 3.3.4.1
- PHP version: 7.2.23
- Database driver & version: MySQL 5.7.12

**Comment by brandonkelly** [comment]
This is pretty weird… I’m able to reproduce, but not sure why. Craft/Yii is correctly setting the session cookie domain based on `defaultCookieDomain`, as evidenced by the `session_get_cookie_params()` output right before headers are sent:

<img width="1107" alt="session_get_cookie_params() output" src="https://user-images.githubusercontent.com/47792/66150244-96a39180-e5c9-11e9-84b1-68de331c298d.png">

Any ideas @angrybrad ?

**Comment by narration-sd** [comment]
Not possibly related to this little gem?  Which I was going to hold onto before saying anything, received last night from latest release Chrome (not  Canary, not tested that  yet).

> 87-demo-hans-j%C3%B8rgen:1 A cookie associated with a cross-site resource at https://site.lv-fgridsome.test/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

pic of headers
![fun-headers](https://user-images.githubusercontent.com/247945/66158909-bc399680-e5db-11e9-8b40-bf9833075d51.png)

**Comment by brandonkelly** [comment]
That looks like a warning about a cookie that will be ignored in a future Chrome release; seems unrelated.

**Comment by oddnavy** [comment]
@brandonkelly I've also spotted that the value for `sameSiteCookieValue` isn't used either

**Comment by angrybrad** [comment]
I'm going to chalk this us to some nutty browser caching.  For example, if I test out `defaultCookieDomain` in an incognito Chrome window, I get relatively consistent behavior where all cookies (including the PHP session cookie) get their domain set correctly.  And the same goes for `sameSiteCookieValue` as well - note that this setting requires PHP 7.3 to work correctly if you're testing with it.
