### ISSUE TITLE
When adding a secondary site, a user group's existing permissions to edit the primary site disappear. 

### ISSUE THREAD

**Issue by bseigel** [craftcms/cms#5032]
### Description
I had to explicitly update their permissions. Permissions for primary site should remain as is when secondary site(s) are added.

### Steps to reproduce
1. Create primary site and some sections. 
2. Create a user group assign permissions.
3. Create a secondary site. Permissions for primary site do not remain. One must explicitly re-assign permissions for a user group under admin/settings/users/groups/{number} > Sites.

### Additional info
- Craft version: 3.3.4.1 (Pro)
- PHP version: 7.0.33
- OS version: Linux 2.6.32-754.10.1.el6.x86_64
- Database driver & version: MySQL 5.5.5
- Image driver & version: Imagick 3.4.0RC6 (ImageMagick 6.7.2-7)
- Plugins & versions: 
    - Advanced Url Field 1.0.0
    - BU Notify 0.0.3
    - CKEditor 1.0.0-beta.2
    - Control Panel CSS 2.2.0
    - Control Panel JS 2.2.0
    - Control Panel Nav 2.0.9
    - CP Field Inspect 1.0.6
    - Craft Cheat Sheet 2.0.3
    - Do It Yourself widget 2.0.1
    - Element Map 1.2.1
    - Entry Instructions 1.0.5
    - Expanded Singles 1.0.7
    - Feed Me 4.1.2
    - Field Manager 2.1.0
    - Guest Entries 2.2.4
    - Importable 1.0.1
    - Incognito Field 1.1.1.1
    - Matrix Colors 2.0.1
    - Preparse Field v1.1.0
    - Redactor 2.4.0
    - Sidebar Themes 1.0.5
    - Sprout Fields 3.4.4
    - Sprout Reports 1.2.7
    - Star Ratings 2.1.1
    - Typed link field 1.0.19

**Comment by brandonkelly** [comment]
This is actually working as expected. Site-specific permissions don’t actually exist until a second site is created, so users haven’t _lost_ those permissions; they never had them to begin with. See [step 5 of our localization guide](https://docs.craftcms.com/v3/localization.html#step-5-give-your-authors-access-to-the-sites).
