### ISSUE TITLE
Element getNext/getPrev fails when calling entry doesn't match conditions

### ISSUE THREAD

**Issue by evanwarner** [craftcms/cms#5036]
### Description
When calling `getNext()` or `getPrev()` on an entry, the entry needs to itself match any criteria passed to the call or else the call will return `null`. This issue is tied to [these lines of code](https://github.com/craftcms/cms/blob/master/src/base/Element.php#L2543-L2547), which search for the calling entry in the array of criteria results and return `null` if it's not found.

I'm coding a situation where the entry upon which I'm looking for a next/prev entry may not match the conditions I'm querying on. There are more longhand ways to do my search, but I wonder if these calls could be refactored to not have this requirement.

### Steps to reproduce

1. Set up criteria for an element query. For example, entries that have a matrix field populated:
```
{
  section: 'mySection',
  search: 'myMatrixField:*'
}
```
2. Pass these criteria to `getNext()`, but called on an entry that does _not_ have that matrix field populated. The results will be `null`.
3. Populate any block on the calling entry's `myMatrixField`, save it, and test the code again. The results will successfully find the next matching element.

### Additional info

- Craft version: 3.3.6

**Comment by brandonkelly** [comment]
This is working as intended. If the entry doesn’t show up within the criteria you pass, Craft has no way of knowing which entry in the results should be considered the “next” or “previous” entry, relative to the current entry.

If you want to make up your own fallback next/previous entry, you can do this in your template:

```twig
{% set next = entry.getNext(query) ?? query.one() %}
```
