### ISSUE TITLE
quick one probably on depreciation warning

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#5037]
### Description
I'm getting one from my plugin settings.html, on a fresh latest craft install.

The message via DP Utilities is:
```
craft.config.[setting] has been deprecated. Use craft.app.config.general.setting instead. 
| /var/www/staging/vendor/narrationsd/live-vue/src/templates/settings.html:266
```

but what's in line 266 is:
```
        {% if craft.config.devMode and not settings.usingDraftPreviews %}
```

I thought of various  things, like my Asset Bundles which it wasn't, but probably you either see a bug here or have a headslap-for-me answer ;) 

While I sort out the old PHP version on this droplet...

### Additional info

PHP version	7.1.31
OS version	Linux 4.15.0-65-generic
Database driver & version	MySQL 5.5.5
Image driver & version	GD 7.1.31
Craft edition & version	Craft Pro 3.3.6
Yii version	2.0.21
Twig version	2.11.3
Guzzle version	6.3.3
Imagine version	1.2.3-dev

Plugins
CraftQL	1.3.4
Element API	2.6.0
Live Vue	dev-craft-gql-merge
Redactor	2.4.0

**Comment by brandonkelly** [comment]
The deprecation notice is telling you to replace `craft.config.devMode` with `craft.config.general.devMode`.

**Comment by brandonkelly** [comment]
For a little syntactic sugar, as of Craft 3.1.20 you can just use the new `devMode` global variable (b4eb782386e22c405a81799a45716ec71db174ae).
