### ISSUE TITLE
[FR] project.yaml "different versions of Craft/plugins" error should state the expected/actual version numbers

### ISSUE THREAD

**Issue by j-greig** [craftcms/cms#5039]
I'm struggling to fix a `Your "project.yaml" file was created for different versions of Craft and/or plugins than what’s currently installed.` error - it would be a lot easier if Craft told me what the mismatch was, or at least whether it was plugin or Craft related.

(Not sure if this is possible though?)

**Comment by brandonkelly** [comment]
If you run `./craft project-config/sync` you will get more details there.

**Comment by j-greig** [comment]
Ah didn't know that, thanks Brandon!

FWIW, I got some _amazingly_ thorough support from Oli on your team which got the site in question working again, hugely thankful :)
