### ISSUE TITLE
Matrix field blocks only load some of the time after upgrade

### ISSUE THREAD

**Issue by mattandrews** [craftcms/cms#5040]
### Description
I recently upgraded a project from Craft 3.1.12 to 3.3.6. We have a few fairly complex Matrix field types, including one with nested SuperTable / Matrix relations. Now when I edit one of these fields, I see a missing area where the blocks should be:

![image](https://user-images.githubusercontent.com/394376/66121625-872a4580-e5d5-11e9-98c0-80a1e834a14c.png)

Bizarrely, if I reload enough times, the fields eventually appear:

![image](https://user-images.githubusercontent.com/394376/66121738-cc4e7780-e5d5-11e9-97d2-6fe659008292.png)

In Safari I see "Failed to load resource: The network connection was lost" in the console when the fields don't appear, but Firefox/Chrome don't show anything. Edge shows "net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)" in the console.

I've tried running `./craft resave/matrix-blocks` which almost works – it makes the blocks consistently appear when I edit the field **until Craft starts processing hundreds of "updating search indexes" requests**.

### Steps to reproduce

1. Upgrade Craft (using built-in control panel updater) from 3.1.12 to 3.3.6
2. Attempt to edit a complex nested Matrix field

### Additional info

- Craft version: 3.3.6
- PHP version: 7.1.30
- Database driver & version: MySQL 8.0.17
- Plugins & versions:

```Amazon S3            1.2.5
Control Panel CSS    2.2.0
Control Panel JS     2.2.0
Element API          2.6.0
Element Map          1.2.1
Inventory            2.0.3
Preview Button       1.0.3
Recentchanges        1.1.3
Redactor             2.4.0
Super Table          2.3.0
Tags                 1.0.5
```

**Comment by mattandrews** [comment]
Figured this out after looking in my nginx logs and seeing this:

```2019/10/03 15:29:44 [warn] 304#0: *3457 an upstream response is buffered to a temporary file /usr/local/var/run/nginx/fastcgi_temp/7/15/0000000157 while reading upstream, client: 127.0.0.1, server: craft.dev, request: "GET /admin/settings/fields/edit/120 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "craft.dev referrer: "http://craft.dev/admin/settings/fields/8"
```

Basically, that directory (`/usr/local/var/run/nginx/fastcgi_temp`) didn't have the right permissions locally so I couldn't write to it. Running `chmod` against it fixed this error. Weird one but glad I worked it out!

**Comment by brandonkelly** [comment]
Glad you got it sorted!
