### ISSUE TITLE
Checking in an Event if the save is from autoResaveEntries or not

### ISSUE THREAD

**Issue by dnspnjrs** [craftcms/cms#5042]
### Description
Hi there,

Is it possible to check in `EVENT_BEFORE_SAVE_ELEMENT` if the save comes from an auto-save or a user generated save?

When im re-saving an entry type all the entries are being "batch re-saved". This causes some issues with my module.

For now i've set `autoResaveEntries` to `false` in config/app.php. But it seems a hacky solution. Is there some way in `craft\events\ElementEvent` to check how the entry is being saved if its from a batch-save or a user-save?

Im using this event:
```
Event::on(
\craft\services\Elements::class, 
\craft\services\Elements::EVENT_BEFORE_SAVE_ELEMENT, 
function(craft\events\ElementEvent $event) {
// if($event == autosave) return;
// my code
}
```

### Additional info
- Craft version: Craft CMS 3.3.3
- PHP Version: 7.1.26
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
You can see if the entry is a draft or revision using [ElementHelper::isDraftOrRevision()](https://docs.craftcms.com/api/v3/craft-helpers-elementhelper.html#method-isdraftorrevision):

```php
if (\craft\helpers\ElementHelper::isDraftOrRevision($event->element)) {
    return;
}
```

**Comment by dnspnjrs** [comment]
> You can see if the entry is a draft or revision using [ElementHelper::isDraftOrRevision()](https://docs.craftcms.com/api/v3/craft-helpers-elementhelper.html#method-isdraftorrevision):
> 
> ```
> if (\craft\helpers\ElementHelper::isDraftOrRevision($event->element)) {
>     return;
> }
> ```

Unfortunately this does not work for me. Both saving an entry and saving the entry type pass as true. This just helps for not saving twice ( draft / revision ). 

For example: re-saving an entry type resets all the entry categories.

**Comment by brandonkelly** [comment]
Can you try reexplaining which events you want to ignore?

**Comment by dnspnjrs** [comment]
Hi @brandonkelly , thanks for your reply.

Ill try to explain myself more clearly.

- I've made a section ( channel ), lets call it: `news`
- I've made an entry type in this cannel, lets call it: `article`
- and I'm using a custom module to automatically add information to this article when saving.

When changing a setting in the entry type `article` it auto re-saves all the articles. This re-saving causes issues with my module where I cannot see it the save comes from a change in the entry type or the actual article.

It would be great to see if the `ElementEvent` is because of a change in the setting of entry type. Therefore ignoring certain fields.

I hope my question makes sense. :)

**Comment by brandonkelly** [comment]
Ah ok, so you want to filter out _batch resaves_, not _autosaves_.

You can do that by checking the entry’s [resaving](https://docs.craftcms.com/api/v3/craft-base-elementtrait.html#resaving) property.

```php
if (event->element->resaving) {
    return;
}
```
