### ISSUE TITLE
Verify email link not working for newly registered user

### ISSUE THREAD

**Issue by samhibberd** [craftcms/cms#5043]
### Description

Newly registered user not verified when visiting the link provided in the activation email. Digging into the code base see https://github.com/craftcms/cms/blob/ff8a72beca2b4baa536f71d9569db7bf6f275cf5/src/services/Users.php#L252 is returning false as the hashes do not match when checked using the `password_verify` in `\yii\base\Security`.

### Steps to reproduce

1. Register user via front end form (setting email and password)
2. Visit the verify email link received by email.
3. User not activated and redirects to the homepage (path supplied in config setting `activateAccountSuccessPath`) 

### Additional info

- Craft version: 3.3.6
- PHP version: 7.2
- Database driver & version: MYSQL
- Plugins & versions:

**Comment by brandonkelly** [comment]
Did you recently change the [blowfishHashCost](https://docs.craftcms.com/v3/config/config-settings.html#blowfishhashcost) config setting or something?

**Comment by samhibberd** [comment]
Not the `blowfishHashCost`, we did change the `token` a few weeks back to support the PayPal gateway. Not sure that would impact. Not sure if the hash values would be of any use, they look to partially match, well the first 30 characters do.

**Comment by angrybrad** [comment]
Did you recently upgrade the server's PHP version or install any new PHP extensions?  The `tokenParam` shouldn't affect this.

**Comment by samhibberd** [comment]
Locally yes 7.1 - 7.2, not sure about extensions, whatever the default install of Valet Plus (recently upgraded to latest). Although it's also not working in the staging environment, which is hosted with cloudways and has always been running 7.2.

**Comment by angrybrad** [comment]
Weird... if you want to send some staging credentials (CP/SSH/database) over to support@craftcms.com, we can poke around a bit, but I'm a bit stumped from the description.

**Comment by angrybrad** [comment]
Is this still an issue for you?  Just created a new user on the staging site you provided (brad@pixelandtonic.com) and was able to verify the account via email successfully.

**Comment by samhibberd** [comment]
All fine now, very strange, customer reported and I was able to recreate. Thanks for investigating.
