### ISSUE TITLE
Updating to a Draft Deletes Content in Multisite Setup

### ISSUE THREAD

**Issue by matthewmrotter** [craftcms/cms#5048]
### Description
Making a change on a separate site in a multi-site localized setup deletes content from the default site. When we went into a sibling site we made a text change and then saved as draft and updated to that draft. When we returned to the default site, a completely different piece of content was deleted. 

[Video Here](https://imgur.com/SQ9ZUxe)

### Steps to reproduce

1. Create Multi-Site Setup
2. Add multiple fields
3. Continue making drafts and content changes until the error appears (it's sporadic)

### Additional info

- Craft version: 3.3.6
- PHP version: 7.1.3
- Database driver & version: MySql 5.5
- Plugins & versions:
**CP Field Inspect** 1.0.6
**CodeMirror** 1.0.1
**Cookies** 1.1.11
**Country Redirect** 2.0.13
**Freeform Lite** 2.5.24
**Read Time** 1.5.0
**Redactor** 2.3.3.2
**Retcon** 2.0.12
**Retour** 3.1.23
**SEOmatic** 3.2.20
**Snitch** 3.0.0
**Super Table** 2.3.0
**Translations** 1.2.5
**Workflow** 1.2.3

**Comment by mdominguez** [comment]
@matthewmrotter Yes indeed, we also experience this as a very severe issue... Doesn't seem like it's going to get fixed before the 3.4 release :) #4642 and #4811

**Comment by matthewmrotter** [comment]
@mdominguez This is a different issue - nothing is getting overwritten or getting reverted to a previous state, it's just randomly deleting content. Support it working on it now but it's inconsistent
