### ISSUE TITLE
add icon for add an asset and delete icon in table have bad position in CP

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#5051]
### Description

add icon for add an asset and delete icon in table field have bad position when CP direction differs with currently editing site direction.
- add icon has bad position because Craft CMS adds direction of site to parent of input if input is translatable -which is unnecessary for asset input field-.
- delete icon in table field has bad position because his padding is always related to body direction not input direction in table - parent of delete icon uses body.rtl table.editable tbody tr td.action + td.action-

wrong position:
![wrong](https://user-images.githubusercontent.com/55586085/66228820-4b829f00-e6ed-11e9-8c5c-2f7a8a416963.png)

right position:
![right](https://user-images.githubusercontent.com/55586085/66228835-53dada00-e6ed-11e9-82bf-78038f65f92a.png)

### Steps to reproduce
in pictures:
1.  admin CP is RTL
2.  admin is editing a site with LTR direction

or it can be:
1.  admin CP is LTR
2.  admin is editing a site with RTL direction

**Comment by brandonkelly** [comment]
Thanks for reporting those! Fixed for the next release.
