### ISSUE TITLE
[FR] GraphQL: Throw an event for permissions

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#5055]
Right now the permissions for GraphQL schemas are hardcoded in the `Gql::getAllPermissions()` method, which makes it impossible for third party plugins or modules to extend the schema token permissions.

Adding a `Gql::EVENT_REGISTER_PERMISSIONS` event that passes in a `RegisterGqlPermissionsEvent` that is triggered from the `Gql::getAllPermissions()` method would be ideal.

**Comment by andris-sevcenko** [comment]
This will be a part of 3.4

**Comment by andris-sevcenko** [comment]
This is now available in Craft 3.4 beta.
