### ISSUE TITLE
Gql: hazard on ping alive query

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#5057]
### Description
Simple - let's say you are having trouble connecting  to a server, so you cut  your usual labelled query down to a 'ping', which is Gql's hello-world, as:
```
query SomeName {
  ping
}
``` 

Now, when you are successful in connecting, you'll still get an error:
```
{
  "errors": [
    {
      "message": "Unknown operation named \"SomeNam\".",
      "category": "graphql"
    }
  ]
}
```

Because, at moment, Gql doesn't allow ping to have a name on its query.

**Comment by andris-sevcenko** [comment]
Are you using Insomnia.app for this? Because I have encountered a similar bug with Insomnia.app. Try clicking anywhere else in the Insomnia.app query editor _except_ the `query SomeName {` line and running it again.

**Comment by andris-sevcenko** [comment]
Actually, clicking anywhere solved that for me - https://imgur.com/a/JKTWqzp

**Comment by narration-sd** [comment]
Actually, you're exactly right. 

I've found how  to cause it to recur, and will ring the bell on that project. Not your problem, and closing here.
