### ISSUE TITLE
Plugin settings vs multisite

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#5060]
### Description
I was wondering if it's possible for plugins to have different settings per site, like Craft's general config has (with `ConfigHelper::localizedValue()`).
Plugin settings are aware of environments out of the box but when I add `environment > siteHandle > settings` that does not work.

The plugin I'm having the issue with in this case is [mailchimp-subscribe](https://github.com/aelvan/mailchimp-subscribe-craft) and I wanted to make a PR to add this but I'm not sure how to.

### Additional info

- Craft version: 3.3.7
- PHP version: 7.3
- Database driver & version: 5.7
- Plugins & versions: mailchimp-subscribe 3.0.0

**Comment by brandonkelly** [comment]
Plugins can run their settings values through `localizedValue()` just like Craft settings.

```php
class Settings extends Model
{
    public $apiKey;

    public function getApiKey(string $siteHandle = null)
    {
        return \craft\helpers\ConfigHelper::localizedValue($this->apiKey, $siteHandle);
    }
}
```

**Comment by janhenckens** [comment]
I can't seem to get this working in any of my plugins. The config settings come through when I just have the environments in the config file, but with the `siteHandle` beneath that all properties are empty.

My settings model:

````
public $googleApiKey;

public function getGoogleApiKey(string $siteHandle = null)
{
    return \craft\helpers\ConfigHelper::localizedValue($this->googleApiKey, $siteHandle);
}
````

My config file:

````
return [
    '*' => [
        'leuvenLeest' => [
            'googleApiKey' => 'foo',
        ]
    ]
];
````

**Comment by brandonkelly** [comment]
From there you would need to specifically start calling `getGoogleApiKey()` rather than the `googleApiKey` property.

**Comment by janhenckens** [comment]
That's what I tried earlier, with no success

```
$settings = EasyAddressField::getInstance()->getSettings();
$settings->getGoogleApiKey(); // null
```

When I check the ConfigHelper class, I see I'm not getting past [here](https://github.com/craftcms/cms/blob/f607d7314a8f7b6050859c3e7c362a86bcbe7709/src/helpers/ConfigHelper.php#L108) since the `$value` that gets passed is null, even though it is my config file.

````
return [
    '*' => [
        'default' => [
            'googleApiKey' => 'foo'
        ]
    ]
];
````

**Comment by brandonkelly** [comment]
What do you get if you dump out the `googleApiKey` setting directly?

```php
Craft::dd(EasyAddressField::getInstance()->getSettings()->googleApiKey);
```

**Comment by janhenckens** [comment]
With the above config that return `null`, without the siteHandle there it works.

**Comment by brandonkelly** [comment]
Hm… is there any sort of normalization logic going on that could be setting the value to `null`?

**Comment by janhenckens** [comment]
Not really no, I'm not doing anything with it in settings.

I saw the same thing when trying this in the mailchimp-subscribe plugin (that's where my current project will probably need this) so I tried it in one of my own plugins, to no avail.

**Comment by brandonkelly** [comment]
I just took a closer look at your example config, and that’s where the problem lies. It should be:

```php
return [
    '*' => [
        'googleApiKey' => [
            'default' => 'foo'
        ]
    ]
];
```

The setting itself should still be at the top level of the config (or environmental config), and its value should be a key/value pair, with the keys set to site handles.

**Comment by janhenckens** [comment]
Oh my, yes, off course 🤦‍♂️.  Works right away.
Thanks for sticking with me :)
