### ISSUE TITLE
Duplicate (corrupt) asset created when saving user.

### ISSUE THREAD

**Issue by JamesNuttall** [craftcms/cms#5061]
### Description
Our user model contains an asset field. When updating a user who doesn't already have a photo from a frontend form, with a photo and a file in the asset field, it seems to cause a corrupt duplicate of the uploaded asset field file.

I believe it has something to do with the usersController saving the user element twice when the user doesn't have a photo attached to their profile before the request. There is no duplicate file on the first [save](https://github.com/craftcms/cms/blob/0e058e1b1132b8df22cbc0941dad81eb488b1fd1/src/controllers/UsersController.php#L1066) but when [saveUserPhoto](https://github.com/craftcms/cms/blob/0e058e1b1132b8df22cbc0941dad81eb488b1fd1/src/controllers/UsersController.php#L1751) is called as a result of [_processUserPhoto](https://github.com/craftcms/cms/blob/0e058e1b1132b8df22cbc0941dad81eb488b1fd1/src/controllers/UsersController.php#L1135) the second [save](https://github.com/craftcms/cms/blob/0e058e1b1132b8df22cbc0941dad81eb488b1fd1/src/services/Users.php#L460) seems to cause the duplicate corrupt file.

My assumption would be that something is still aware of the temp file on the second user element save and it is trying to save a new asset when it doesn't exist anymore. But that is just a guess.

### Steps to reproduce

1. Create an assets field type and add it to the users fields (any volume type seems to work in reproducing the issue).
2. Setup a frontend form to update the users photo & the asset field via the `users/save-user` action, something like this:

```
<form method="post" enctype="multipart/form-data" accept-charset="UTF-8">
        {{ csrfInput() }}

        <input type="hidden" name="action" value="users/save-user">
        <input type="hidden" name="userId" value="{{ currentUser.id }}">

        <label>Photo</label>
        <input id="userPicture" type="file" name="photo"><br>

        <label>Asset Field 1</label>
        <input name="fields[asset1][0]" type="file"><br>

        <button type="submit">Save Profile</button>
</form>
```
3. Make sure the user **_doesn't_** already have a photo on their profile (**_IMPORTANT_**).
4. On the frontend form add a photo & add a file to the asset field then submit.
5. View the asset element index view in the CP and you will see the photo and **_2_** other files, one corrupt:

![image](https://user-images.githubusercontent.com/22011451/66309460-98d75a00-e901-11e9-9bea-d4d660449e79.png)

### Additional info

- Craft version: 3.3.7
- PHP version: 7.2.14
- Database driver & version: MySQL 5.7.25

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.
