### ISSUE TITLE
Slug with wildcard not working when fetching Entries

### ISSUE THREAD

**Issue by michtio** [craftcms/cms#5062]
### Description

When running entry queries following the docs it doesn't always fetch as expected.
In a multisite entry which has both "about" and "about-us" slugs in a structure, when running the following tests: 

#### Returns data
```
{% set about = craft.entries()
  .section('page')
  .slug('about')
  .one() %}
```

#### Doesn't return data
```
{% set about = craft.entries()
  .section('page')
  .slug('about*')
  .one() %}
```

```
{% set about = craft.entries()
  .section('page')
  .slug('*bou*')
  .one() %}
```

```
{% set about = craft.entries()
  .section('page')
  .slug('*about*')
  .one() %}
```

```
{% set about = craft.entries()
  .section('page')
  .slug(['about', 'about-us'])
  .one() %}
```

#### What does work:

```
{% set about = craft.entries()
  .section('page')
  .slug(['*about*'])
  .one() %}
```

I think somewhere along the line there are some issues here?

### Steps to reproduce

1. See above what returns and what not
2. Create a structure in a multisite setup, a page in site 1 will have "about" as slug, site 2 might have "about-us". 

### Additional info

- Craft version: 3.3.7
- PHP version: 7.2

**Comment by michtio** [comment]
This has resolved itself all of the sudden.

**Comment by brandonkelly** [comment]
Weird… glad it’s working for you now though!

**Comment by michtio** [comment]
@brandonkelly yeah it was something really weird. I tried all those different things, refreshed, cleared caches, browser caches... nothing. And after a few hours of trying all of the sudden it worked as it supposed to be. And nothing big on system level locally has had happened. But my guess is that somewhere a service must've been running weird. So definitely not Craft related! :)
