### ISSUE TITLE
Issue with composer.craftcms.com

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#5063]
Some people are running into issues using Craft's updater (both in the CP and via the CLI) updating to the latest ImageOptimize, which includes this as a dependency:

https://github.com/nystudio107/craft-imageoptimize/blob/v1/composer.json#L32

>         "nystudio107/craft-imageoptimize-imgix": "^1.1.0",

...which was recently bumped to a new version:

https://github.com/nystudio107/craft-imageoptimize-imgix/blob/v1/composer.json#L5

If you update via `composer update` via the CLI, everything works fine. But if you use Craft's CP updater or Craft's CLI update console command, it fails with:

> Error: The "https://composer.craftcms.com/p/nystudio107/craft-imageoptimize-imgix/c642ab1cfc1bf5e4c9c3c265837b1e5201a6ed55436f1bbb47558a9c63a49384.json" file could not be downloaded (HTTP/1.1 404 Not Found)

I remember someone had to manually do something to fix this before... not sure what the best long-term solution is here?

Related issue: https://github.com/nystudio107/craft-imageoptimize/issues/169

**Comment by brandonkelly** [comment]
Fixed now, by fasttracking 02e55523055b55c64cce84f3f4c0e31cc78ec55c (& 1dcf0dc7a118491f2b7e759f7823dd038b2312ab) up to Craftnet.

**Comment by khalwat** [comment]
We sure this is fixed? People are still saying they are having issues. Could it be a cache?

https://github.com/nystudio107/craft-imageoptimize/issues/171

**Comment by Coysh** [comment]
Updated to Craft 3.3.8 - and still having the same issue.

**Comment by khalwat** [comment]
FWIW @brandonkelly I've had a few people contact me to mention that they are still running into this. Perhaps the issue is fixed, but there's some caching involved?

The repo is showing that the webhook is delivering the payload just fine now, which is why I'm suspecting some kind of caching issue somewhere.

**Comment by angrybrad** [comment]
@khalwat Should really be fixed now... sorry about that.

**Comment by preston-method** [comment]
Hi
I am seeing this error when trying to install the SAML plugin in the CP

Composer output: Package "craftcms/vue-asset" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- simplesamlphp/saml2 v4.1.7 requires php >=7.2 -> your PHP version (7.4.11) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
- simplesamlphp/saml2 v4.1.6 requires php >=7.2 -> your PHP version (7.4.11) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
- simplesamlphp/saml2 v4.1.5 requires php >=7.2 -> your PHP version (7.4.11) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
- simplesamlphp/saml2 v4.1.4 requires php >=7.2 -> your PHP version (7.4.11) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
- simplesamlphp/saml2 v4.1.3 requires php >=7.2 -> your PHP version (7.4.11) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
- simplesamlphp/saml2 v4.1.2 requires php >=7.2 -> your PHP version (7.4.11) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
- simplesamlphp/saml2 v4.1.1 requires php >=7.2 -> your PHP version (7.4.11) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
- simplesamlphp/saml2 v4.1.0 requires php >=7.2 -> your PHP version (7.4.11) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
- simplesamlphp/saml2 v4.1.8 requires php >=7.1 -> your PHP version (7.4.11) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
- simplesamlphp/saml2 v4.1.9 requires php >=7.1 -> your PHP version (7.4.11) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
- simplesamlphp/saml2 v4.1.10 requires php >=7.1 -> your PHP version (7.4.11) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
- flipboxfactory/saml-idp 1.2.0 requires flipboxfactory/saml-core ^3.0 -> satisfiable by flipboxfactory/saml-core[3.1.0, 3.0.1, 3.0.0].
- flipboxfactory/saml-core 3.1.0 requires simplesamlphp/saml2 ^4.1 -> satisfiable by simplesamlphp/saml2[v4.1.10, v4.1.9, v4.1.8, v4.1.0, v4.1.1, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7].
- flipboxfactory/saml-core 3.0.1 requires simplesamlphp/saml2 ^4.1 -> satisfiable by simplesamlphp/saml2[v4.1.10, v4.1.9, v4.1.8, v4.1.0, v4.1.1, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7].
- flipboxfactory/saml-core 3.0.0 requires simplesamlphp/saml2 ^4.1 -> satisfiable by simplesamlphp/saml2[v4.1.10, v4.1.9, v4.1.8, v4.1.0, v4.1.1, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7].
- Installation request for flipboxfactory/saml-idp 1.2.0 -> satisfiable by flipboxfactory/saml-idp[1.2.0].

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

**Comment by angrybrad** [comment]
@preston-method sounds like you could change https://github.com/craftcms/craft/blob/master/composer.json#L37 in your composer.json file at least 7.2, if not 7.4.
