### ISSUE TITLE
FR: GraphQL expose Preview Targets

### ISSUE THREAD

**Issue by MatthiasGrandl** [craftcms/cms#5070]
It would be cool, if the GraphQL API would be able to query Preview Targets.
Something like:
```
entries {
  previewTargets
}
```
=>
```
entries: [
  previewTargets: [{ url: "/blog/my-post-slug", name: "post" }]
]
```

Example usecase:
I want to build autocomplete search for my site with headless Craft, but there is no way to the get the URL for each entry, without hardcoding the links for every section, which would be a nightmare. 

Since I am doing the preview target stuff anyway, it would be cool if I could just reuse that.

**Comment by brandonkelly** [comment]
> I want to build autocomplete search for my site with headless Craft, but there is no way to the get the URL for each entry, without hardcoding the links for every section

That won’t be an issue in Craft 3.4 – see https://github.com/craftcms/cms/issues/4520#issuecomment-531040417.

**Comment by Jones-S** [comment]
could it be that they are not yet exposed via GraphQL?
When querying `uri` for an entry I would still get `null` (Craft v3.4.x-dev)
