### ISSUE TITLE
Craft 3.3 GraphQL relatedto argument

### ISSUE THREAD

**Issue by smcyr** [craftcms/cms#5071]
### Description
There isn't an argument `relatedTo` in GraphQL to fetch, for example, entries associated to a category. Is there an alternative or is `relatedTo` gonna be added to GraphQL?

**Comment by andris-sevcenko** [comment]
`relatedTo` will be added to GraphQL, but it will support element IDs only, as there's no feasible way of providing a list of, say, categories to a GraphQL query.

**Comment by andris-sevcenko** [comment]
Added this for the next 3.3. release!

**Comment by dangayle** [comment]
There will be no way to pass in a category slug? This would be essential for things like having a url `/blog/cats` that makes a request for a list blogposts related to the cats category. I won't know the id, so I would have to make two requests to get the list of categories first just to get the id.

**Comment by andris-sevcenko** [comment]
@dangayle that's a good point. Could you open a new issue for this? The immediate problem has been addressed and I feel like your issue should be a separate one with its own status and discussion.
