### ISSUE TITLE
[FR] Preserving Matrix Fields Container Display Value on toggle

### ISSUE THREAD

**Issue by svale** [craftcms/cms#5075]
### Description

When expanding a collapsed Matrix block, the blocks fields container is given a style attribute with the value of `opacity:1; display:block` through the `fadeIn`-method of velocity.js.

As opposed to jQuerys `.show()`, velocity.js .`fadeIn()`does not restore the display property to whatever it was initially. Instead it is set to the element's native type. This breaks any custom CSS (like `.fields { display:grid } `) added on top of the default CP-styles.

The display property can however be overridden by passing a custom display value into the `fadeIn()` options object.  

This means a small addition to [MatrixInput.js ](https://github.com/craftcms/cms/blob/2cf33e655bb22866c861a15f1c8f5c79145c6732/src/web/assets/matrix/dist/MatrixInput.js#L545
) allows for more custom styling (directly or through plugins) of Matrix fields. E.g. and specially using CSS grid layouts.

```
var displayValue = this.$fieldsContainer.css('display') || 'block';
this.$fieldsContainer.hide().velocity('fadeIn', {duration: 'fast', display: displayValue});
```

Would this be a possibility and/or a PR be considered?

Thanks!

### Additional info

- Craft version: 3.3.1.2
- Plugins & versions: relevant in the case: doublesecretagency/craft-cpcs

**Comment by brandonkelly** [comment]
We’d take a PR for this, sure.
