### ISSUE TITLE
Gql: internal error on mis-spelled transform (presently handle) query

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#5077]
### Description
Sorry, this is a small one you can work out as convenient; not critical.

Basically, Gql throws a non-transparent internal error, when given a handle that doesn't match a transform.

### Steps to reproduce

1. Have an Asset transform in Craft named something like  `largerCard`
2. But you really meant `largerCards`, and get that right in the GraphQL query, using the url (handle: "largerCards") form for the Asset.
3. Bang, when you run the query
4. Unfortunately there are no clues in the result as why...that's the highest problem, besides that it's internal error; probably both sort out together
5. Spell things right, and back to smooth

### Additional info

- Craft version: dev-feature/graphql-events as 3.4

**Comment by narration-sd** [comment]
Here's the intended pic, that it happened, and what you see

...it's late, still clock unsynced from all-nighter earlier in week...human here too...

![pic-that-it-happened](https://user-images.githubusercontent.com/247945/66569610-c3ebc480-eb20-11e9-9059-8b5c16796c49.png)

**Comment by andris-sevcenko** [comment]
As of some changes I've made over this week, this is now much better both on `3.4` and `develop` branch.
