### ISSUE TITLE
GraphQL: Using '*' as param for multisite results doesn't work.

### ISSUE THREAD

**Issue by michtio** [craftcms/cms#5079]
### Description

Fetching entries over multiple sites with the "*" parameter is not working.

### Steps to reproduce

1. Create a query in the GraphQL Playground.

```
query searchQuery($sections: [String], $needle: String!, $limit: Int)
{
  entries(site: "*", section: $sections, search: $needle, limit: $limit) {
        title
        uri
    }
}
```

```
{
  "sections": "news",
  "limit": 24,
  "needle": "title:T"
}
```

2. This returns an error:

```
{
  "errors": [
    {
      "debugMessage": "Invalid site param: [*]",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "entries"
      ]
    }
  ],
  "data": {
    "entries": null
  }
}
```

3. What does seem to work is to add `entries(site:["not", ""])` but that is unexpected behaviour

### Additional info

- Craft version: 3.3.8
- PHP version: 7.2

**Comment by andris-sevcenko** [comment]
Fixed for the next release!

**Comment by ken-gladeye** [comment]
this issue has returned since 3.6.1, should I create a new issue instead?

**Comment by brandonkelly** [comment]
@ken-gladeye Yes please

**Comment by brandonkelly** [comment]
@ken-gladeye All good, looks like @andris-sevcenko fixed it :)

**Comment by ken-gladeye** [comment]
🎉 you guys are legends!

**Comment by brandonkelly** [comment]
Craft 3.6.2 is out now with that fix.

**Comment by thinkflo** [comment]
I'm Popcorn on Discord. Thanks for this <3
