### ISSUE TITLE
Craft no longer routes requests based on action params in the request body, if the request’s content type is application/json

### ISSUE THREAD

**Issue by mofman** [craftcms/cms#5080]
### Description

**Craft no longer routes requests based on action params in the request body, if the request’s content type is application/json**

- This is breaking all our ajax requests
- Can someone provide some documentation on this?

### Additional info

- Craft version: 3.3.8

**Comment by brandonkelly** [comment]
Routing requests based on an `action` param in a request JSON body was an unintentional side effect of 14a42fa76c7b261191c40d7f9f6ed485b2387796, which was a 3.3.0 change. Problem is that there were some JSON bodies being posted to Craft (e.g. GitHub webhook requests) which defined an `action` param that had nothing to do with routing, but Craft was interpreting it as a route anyway. So as of Craft 3.3.8 we are explicitly only checking for `action` in the request body if the request’s MIME type is **not** `application/json` (02e55523055b55c64cce84f3f4c0e31cc78ec55c).

Sorry that you got bit by this change. You can work around it by passing the action another way, such as via an `action` query param, or by sending the request to the URL `example.com/actions/<your-route>`. (Replace `actions` with whatever your [actionTrigger](https://docs.craftcms.com/v3/config/config-settings.html#actiontrigger) config setting is set to, if you’ve changed it.)
