### ISSUE TITLE
Assets search in the CP not returning expected results

### ISSUE THREAD

**Issue by aarmitage** [craftcms/cms#5081]
### Description

We're searching for assets (images) which we can see exist in the assets directories (using S3). Some results are returned, but others are not.

<img width="973" alt="Screenshot 2019-10-10 at 16 53 29" src="https://user-images.githubusercontent.com/1152884/66585375-9c2b4980-eb7e-11e9-99e5-dadaec13835e.png">

<img width="972" alt="Screenshot 2019-10-10 at 16 53 12" src="https://user-images.githubusercontent.com/1152884/66585402-a9e0cf00-eb7e-11e9-9c49-923a46748be0.png">

We've checked the search index table, and there was no entry ID for some of the images we could see have been uploaded. We rebuilt the search index which appeared to complete successfully and cleared caches.

Checked server and Craft error logs, as well as MySQL logs and no indication of an error.

Attempted to rename a file we could see uploaded but missing from the index table which should in theory have resaved the asset and the index. The file name was updated successfully, but not added to the index table.

### Steps to reproduce

1. Images have been uploaded.
2. Searching for those images using a string (contained in the title) or the exact filename returns no results (screenshot above).

### Additional info

- Craft version: 3.3.41
- PHP version: 7.3 on Ubuntu 16.04
- Database driver & version: MySQL 5.7.27 with MyISAM storage
- Plugins & versions:

**Comment by angrybrad** [comment]
Could you send a database dump along with your composer.json and composer.lock files over to support@craftcms.com and reference this issue?

**Comment by angrybrad** [comment]
I had similar behavior as you, but I went to Utillities->Asset Indexes and updated them (it look 4-5 hours to finish because S3 and all) and tried the same thing again and got expected, so that should resolve it for you, too.

![Screen Shot 2019-10-17 at 2 14 46 PM](https://user-images.githubusercontent.com/61869/67048424-07c66700-f0e9-11e9-8f2f-cca8971f7376.png)

**Comment by aarmitage** [comment]
Thanks Brad, appreciate that. Did you happen to see how many assets were re-indexed? We did this and I think there were about 3,500 assets, and it appeared to complete in about 15 minutes. That against your 4-5 hours would explain why we weren't seeing the results we expected.
