### ISSUE TITLE
[FR] GraphQL : Fetch More Data Related to an Entry

### ISSUE THREAD

**Issue by michtio** [craftcms/cms#5082]
### Description

It would be nice if we could Fetch more Data into our GraphQL queries:

With CraftQL it was possible not only to get the sectionHandle, but to get all information that a section holds.

Also, when returning site information currently we can only fetch siteId, it would be nice if we could get more information out of this as well, as the site handle and the site name for example. That only makes sense if we already fetch the siteId.

**Comment by andris-sevcenko** [comment]
So, an update is due. This feature is still on the table and we realize that it would help a lot when working with the GraphQL API.

It wouldn't make sense to expose just one facet of the site's structure to Craft, so it would be a pretty involved work to expose sites, category and tag groups, sections, entry types, fields, layouts, and more, so it becomes a little bit of an undertaking.

We want to do this right and there currently are things that are a bit more important to get in line for 3.5, so it won't be making the cut for 3.5.

Having said that, it's possible to pull off with a plugin, though, as Craft exposes quite a few GraphQL related events.

**Comment by michtio** [comment]
@andris-sevcenko are there updates on this?
