### ISSUE TITLE
Edit entry screen shows a beforeunload dialog when exiting even without changes

### ISSUE THREAD

**Issue by mattandrews** [craftcms/cms#5085]
### Description

Some of our users are reporting confusion because they're seeing a confirmation dialog when they leave the Edit screen, even if they haven't changed the entry. Here's a demo:

![confirm](https://user-images.githubusercontent.com/394376/66660660-86308e00-ec3d-11e9-8082-e9d9c134d3f2.gif)

I know the `beforeunload` event is useful to warn users about changes they'll otherwise lose, but would it be possible to prevent it in the case of a pristine session? I actually implemented this on our company's website for a complex application form – we did it by calling jQuery's $(form).serialize() method on pageload, storing the result, then calling it again whenever the form changed and comparing whether there had been any modifications (and then setting/unsetting the `beforeunload` event – [source here](https://github.com/biglotteryfund/blf-alpha/blob/master/assets/js/common/forms.js#L50)).

### Steps to reproduce

1. Edit an entry
2. Click a link to leave the page
3. You'll see a `confirm()` dialog regardless of whether you've done anything

### Additional info

- Craft version:  Craft Pro 3.3.6
- PHP version: 7.1.25
- Database driver & version: MySQL 5.7.23
- Plugins & versions:
```
Control Panel CSS    2.2.0
Control Panel JS     2.2.0
Element API          2.6.0
Element Map          1.2.1
Inventory            2.0.3
Preview Button       1.0.3
Recentchanges        1.1.3
Redactor             2.4.0
Super Table          2.3.0
Tags                 1.0.5
```

**Comment by brandonkelly** [comment]
This is most likely being caused by a plugin. Please send your `composer.json` and `composer.lock` files and a database dump over to support@craftcms.com and we can help determine the culprit.

**Comment by brandonkelly** [comment]
@mattandrews Yeah looks like we’re back on the case, thanks!
