### ISSUE TITLE
Don't error on disallowed extension when reindexing through CLI

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#5086]
### Description
We keep a `.gitignore` in our public asset folder to make sure the folder itself always gets deployed, but that results in the following error when running `./craft index-assets/all`:

````bash
> #0: .gitignore ... error: File “.gitignore” was not indexed because extension “gitignore” is not allowed.
````

When updating assets index through the CP there is a warning about these files but the indexing still happens, through CLI the command stops.

Ignoring the error might not be advisable but maybe a `--silent` opiton could be added?
Happy to have a stab at a PR if that's the route you'd like to take!

### Additional info

- Craft version: 3.3.9
- PHP version: 7.3.7
- Database driver & version: 5.7

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just fixed this for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#94190aa3e7700c0ddfee0ed7e5e02e3b087b44db as 3.3.9",
  "...": "..."
}
```

Then run `composer update`.

**Comment by janhenckens** [comment]
Perfect, thanks!
