### ISSUE TITLE
Preview outputs incorrect entry.id · Craft 3.3.8

### ISSUE THREAD

**Issue by bseigel** [craftcms/cms#5087]
### Description

In Preview, using the default view (I have not set up any targets), when I output entry.id, it shows a value different than the one for the entry being previewed.  When the same entry is viewed on the front end (with the same template), the entry.id is correct and pages display as intended.

### Additional info

- Craft version: 3.3.8 (Pro)
- PHP version: 7.1.32
- OS version: Linux 2.6.32-754.10.1.el6.x86_64
- Database driver & version: MySQL 5.5.5
- Image driver & version: Imagick 3.4.3RC1 (ImageMagick 6.7.2-7)
- Plugins & versions: 
    - Advanced Url Field 1.0.0
    - BU Notify 0.0.3
    - CKEditor 1.0.0-beta.2
    - Cloner 1.0.3
    - Control Panel CSS 2.2.0
    - Control Panel JS 2.2.0
    - Control Panel Nav 2.0.9
    - CP Field Inspect 1.0.6
    - Craft Cheat Sheet 2.0.3
    - Do It Yourself widget 2.0.1
    - Element Map 1.2.1
    - Entry Instructions 1.0.5
    - Expanded Singles 1.0.7
    - Feed Me 4.1.2
    - Field Manager 2.1.0
    - Field Reveal 1.0.1
    - Guest Entries 2.2.4
    - Importable 1.0.1
    - Incognito Field 1.1.1.1
    - Matrix Colors 2.0.1
    - Preparse Field v1.1.0
    - Redactor 2.4.0
    - Sidebar Themes 1.0.5
    - Snitch 3.0.0
    - Sprout Fields 3.4.4
    - Sprout Reports 1.2.8
    - Star Ratings 2.1.1
    - Typed link field 1.0.19

**Comment by brandonkelly** [comment]
This is expected, because you are actually previewing a draft, not the source entry, and the draft has its own ID. 

To output the source entry’s ID, use `{{ entry.sourceId }}`.

**Comment by bseigel** [comment]
Brad - before closing the ticket, could you confirm use cases for **entry.sourceId** vs. **entry.id**? If a template is used for front end display and preview, is it appropriate to use **entry.sourceId** universally? Also, docs could use updating - this info is nowhere in [https://docs.craftcms.com/v3](https://docs.craftcms.com/v3)

Thanks.

**Comment by brandonkelly** [comment]
@bseigel `sourceId` could be used universally, yes. It checks if the current element is a draft/revision and if so returns the source entry’s ID, otherwise it returns `$this->id`.

Documented here: https://docs.craftcms.com/api/v3/craft-base-element.html#method-getsourceid
