### ISSUE TITLE
[BUG] Admin can't easily change email address

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#5088]
### Description

When an Admin changes the email address of another user, Craft now sends a confirmation email to the new email address. Previously, this behavior was overridden when an Admin makes the change.

✅**Original behavior in Craft 3.1.34.3**

1. Admin changes email address of another user.
2. Email address is updated.

🚫**New behavior in Craft 3.3.6**

1. Admin changes email address of another user.
2. "Verify your email address" email gets sent to user.
3. User must click the link in the verification email.
4. Email address is updated.

### Additional info

- Craft version: 3.3.6
- I disabled all plugins and modules to test this.

**Comment by brandonkelly** [comment]
Fixed for the next release!

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#bc1dbb64b2b0f9ca86574fab8d788622d07be6d2 as 3.3.9",
  "...": "..."
}
```

Then run `composer update`.

**Comment by lindseydiloreto** [comment]
Fantastic, thanks @brandonkelly! 🍺

**Comment by lindseydiloreto** [comment]
Bad news... this doesn't seem to be fixed. 😕

My client claims she was able to get it to work once, the very first time. But then it stopped working.

I personally haven't been able to get it to work at all. The behavior remains as originally described.

**Comment by brandonkelly** [comment]
Are you/your client testing with an admin account, or an account that has the **Administrate users** permission?

**Comment by lindseydiloreto** [comment]
Yup, we're both full Admins.

**Comment by brandonkelly** [comment]
Really fixed now. And now I’m not sure how it worked for me in the first place ¯\_(ツ)_/¯

**Comment by lindseydiloreto** [comment]
Ha, perfect! It's now working perfectly for me, every time. 👍

Thanks again!
