### ISSUE TITLE
Plugin won't install

### ISSUE THREAD

**Issue by rtgoodwin** [craftcms/cms#5092]
### Description

I've been attempting to install the Retcon plugin, and haven't been able to make it happen. I seem to be alone in this, so suspecting I've found some obscure bug. 

More details in https://github.com/mmikkel/Retcon-Craft/issues/18

Posting over here as author https://github.com/mmikkel is out of ideas. 

I don't necessarily want to try the "composer nuke" route on a production server, but I'm not beyond it if recommended by P&T.

Thanks!

### Steps to reproduce

1. Require the plugin in composer, and/or attempt to install via Plugin Store
2. Craft binary and CP both fail with "no plugin with handle retcon"
3. Composer install/update both report nothing new to install, and vendor/mmikkel/retcon folder is there, as well as in plugins.php. 

### Additional info

- Craft version: 3.3.9
- PHP version: 7.2.19
- Database driver & version: MySQL 5.7.27
- Plugins & versions:

<img width="536" alt="image-11-05-22" src="https://user-images.githubusercontent.com/1183842/66704311-35be3c80-ece0-11e9-8358-b0db9738b73a.png">

**Comment by brandonkelly** [comment]
Did you install directly on production? Maybe it’s a load-balanced environment and the plugin was only actually installed on one of multiple servers.

**Comment by rtgoodwin** [comment]
Unfortunately this a simple little site, hosted on DO. No load balancer to be seen, all commands run locally.

**Comment by janhenckens** [comment]
I've run into this issue as well, both installing a plugin and people reporting the issue for one of my plugin, eg https://github.com/studioespresso/craft-google-shopping-feed/issues/2

**Comment by rtgoodwin** [comment]
Following the instructions to delete the plugin row from the plugin table as suggested in https://github.com/studioespresso/craft-google-shopping-feed/issues/2 worked! Not sure why, but maybe something for P&T to check out.

**Comment by brandonkelly** [comment]
Hmm, the row in the `plugins` table is where Craft keeps track of which plugins are actually installed, in addition to the `plugins` key in the project config. Will close this for now. Next time it crops up, please send your `composer.json` and `composer.lock` files, plus a database backup over to support@craftcms.com and we can try to look into it from there.
