### ISSUE TITLE
craft setup (command line) states I already have installed

### ISSUE THREAD

**Issue by millman2394** [craftcms/cms#5093]
I'm following the instructions on the docs.

I've run `composer create-project craftcms/craft .` inside my directory. It finishes and generates a security key and creates an `.env` file.

When I run `craft setup`, it walks me through setting up DB connection. It's able to connect to the DB and save credentials to the `.env` file.

Then it states  `It looks like Craft is already installed, so we're done here.`

I've tried this on two different environments - one on my docker setup and then on xampp.

The database is empty. I can install by visiting the URL, but I'd like to use the command line.

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just fixed for the next release.

You can still access the installer from `./craft install` even if the `setup` command thinks Craft is already installed.
