### ISSUE TITLE
`content` table column size gets reset to 255 when updating custom field settings

### ISSUE THREAD

**Issue by benjaminkohl** [craftcms/cms#5099]
### Description

We keep running into the max row length issue with the content table with a particular site so I've been spending time reviewing the custom fields that are using VARCHAR columns and setting appropriate sizes for them via our DB client app. For plain text fields, I was also going into Craft to make sure the _Character Limit_ setting reflects the column size I specified in the DB client.

When I re-save the field settings in Craft, it increases the table column size back to 255. That is very undesirable behavior because we will never need 255 characters in a column that will only ever hold 10 characters at most.

Perhaps Craft should leave existing columns alone when re-saving custom field settings OR it should use the _Character Limit_ setting as the column size in the DB. Either option seems more reasonable than overruling our appropriately sized columns, thus making it more difficult for us to avoid the max row length issue.

### Steps to reproduce

1. Resize column length in DB.
2. Re-save the corresponding field's settings in Craft.

### Additional info

- Craft version: 3.3.6
- PHP version: 7.1.32
- Database driver & version: MySQL 5.6.42

**Comment by brandonkelly** [comment]
Column sizes 

> When I re-save the field settings in Craft, it increases the table column size back to 255. That is very undesirable behavior because we will never need 255 characters in a column that will only ever hold 10 characters at most.
>
> Perhaps Craft should leave existing columns alone when re-saving custom field settings

Field types get to decide what their column type is, and Craft will make sure the column is using the correct column type each time you save a field, as the field settings could have caused the desired column type to change.

> OR it should use the _Character Limit_ setting as the column size in the DB.

Column sizes are specified in bytes, not characters. Several characters take up multiple bytes (🤷‍♂️is 13 bytes!), so we can’t just pass the Char Limit setting off to the column definition.

That said, maybe we could give Plain Text fields a custom column type option.

**Comment by benjaminkohl** [comment]
Yes, very true about character byte sizes but all my cases dealt with the more common ASCII characters in plain text fields and/or drop-down fields where each possible value was known and also didn’t use special characters in the values.

**Comment by brandonkelly** [comment]
Just pushed some Plain Text field changes to the 3.4 branch.

- You can now specify the max field size in _bytes_ instead of characters, if desired.
- The Column Type setting now has an “Automatic” option (selected by default for new fields), which will result in `varchar(x)` if a character/byte limit has been set. (Character limits will be multiplied by 4.)

> <img width="481" alt="The new Field Limit setting on a Plain Text field" src="https://user-images.githubusercontent.com/47792/66830021-692fdf80-ef09-11e9-9f83-f3d494fc3429.png">

To get the change early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "3.4.x-dev",
  "...": "..."
}
```

Then run `composer update`.

**Comment by benjaminkohl** [comment]
That will be a very welcome improvement! Thank you!
