### ISSUE TITLE
Queue Job will not work with yii\queue\redis\Queue

### ISSUE THREAD

**Issue by joepagan** [craftcms/cms#5104]
### Description

I cannot seem to get a job working with redis queue. Presuming it's a bug as when I comment out the `queue` section in my `app.php` to fallback to mysql works fine! Can't see any existing related issues.

When running the job it generates these redis tables:

![image](https://user-images.githubusercontent.com/2337910/66839077-c2c1f980-ef5d-11e9-8818-d41d6f1ebc27.png)

Seeing as `queue.waiting` has `(4)` next to it I presume this means 4 items are in limbo?
![image](https://user-images.githubusercontent.com/2337910/66839155-e127f500-ef5d-11e9-95f3-e4dc8e170424.png)

Not too familiar with redis, but, I cannot see the same data that I can normally see in the mysql table which would highlight any potential errors.

`queue.message_id` table:
![image](https://user-images.githubusercontent.com/2337910/66839659-ad999a80-ef5e-11e9-8f7b-db6d07e499b2.png)

`queue.messages` table:
![image](https://user-images.githubusercontent.com/2337910/66839598-965aad00-ef5e-11e9-976b-4f947124012d.png)

Let me know if you need anything else.

### Steps to reproduce

1. Use `yii\queue\redis\Queue::class` for queue
2. Create a queue job
3. Cannot execute code in `execute` method (even a simple call to log)

### Additional info

- Craft version: 3.3.0.1
- PHP version: 7.2
- Database driver & version: redis 4.0.10-alpine
- Plugins & versions:

`app.php`:

```php
<?php
return [
    'components' => [
        'redis' => [
            'class' => yii\redis\Connection::class,
            'hostname' => getenv('REDIS_SERVER'),
            'port' => getenv('REDIS_PORT'),
        ],
        'cache' => [
            'class' => yii\redis\Cache::class,
            'defaultDuration' => getenv('REDIS_CACHE_DURATION'),
        ],
        'session' => [
            'class' => yii\redis\Session::class,
            'as session' => craft\behaviors\SessionBehavior::class,
        ],
        'queue' => [
            'class' => yii\queue\redis\Queue::class,
            'channel' => 'queue',
        ],
        'mutex' => [
            'class' => yii\redis\Mutex::class,
        ],
    ],
];
```

**Comment by brandonkelly** [comment]
Have you set the [runQueueAutomatically](https://docs.craftcms.com/v3/config/config-settings.html#runqueueautomatically) config setting to `false`? If so you will need to manually run the queue [some other way](https://github.com/yiisoft/yii2-queue/blob/master/docs/guide/worker.md).

**Comment by joepagan** [comment]
Didn’t even have that set and by default it’s true

**Comment by brandonkelly** [comment]
Do you have a `storage/logs/queue.log` file? If so search for `[error]` in it.

**Comment by joepagan** [comment]
One doesn’t even get made! does without redis queue

**Comment by brandonkelly** [comment]
Sorry, so if you use anything besides the default queue, then it’s entirely up to you to set up a worker and monitor it. See https://github.com/yiisoft/yii2-queue/blob/master/docs/guide/worker.md for the yii2-queue docs on how to do that.
