### ISSUE TITLE
Dropdown labels must be unique even with option groups

### ISSUE THREAD

**Issue by pixelmachine** [craftcms/cms#5105]
### Description
Previously it was possible to have a Dropdown structured like:

1. Optgroup A
    1. Option A : Value 1
    2. Option B : Value 2
2. Optgroup B
    1. Option A : Value 3
    2. Option B : Value 4

Now, labels are required to be unique regardless of their optgroup and regardless of the uniqueness of the option's value. The dropdown above will give the error:

> All option labels must be unique.

This is incorrect as there are valid use cases for this structure. E.g.:

1. Long sleeve T-shirt 
    1. Red : long-t-red
    2. Blue : long-t-blue
2. Short sleeve T-shirt
    1. Red : short-t-red
    2. Blue : short-t-blue

### Steps to reproduce

1. Create a dropdown with multiple groups containing options with the same label
2. Unable to save

**Comment by brandonkelly** [comment]
Yeah makes sense that labels should be allowed to be unique if they are nested in an optgroup. Will fix…

**Comment by brandonkelly** [comment]
Done for the next release!

To get the change early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#1ef95eada5fd90ac85333ac4942be306c5a037cd as 3.3.10",
  "...": "..."
}
```

Then run `composer update`.

**Comment by KatieMFritz** [comment]
I'm running into this again on Craft 4. I can't even save optgroups with a null or `''` value without getting the error.

**Comment by brandonkelly** [comment]
@KatieMFritz Can you post a screenshot of your Dropdown Options setting?

**Comment by KatieMFritz** [comment]
I was using custom code. 😅 Brad helped me over email.
