### ISSUE TITLE
Validation of Character limit fails (Field should contain at most 0 characters.)

### ISSUE THREAD

**Issue by Jones-S** [craftcms/cms#5109]
### Description
Since today I experience this strange issue that a field `should contain at most 0 characters.`
The field I am talking about has no restrictions and is just a plain text field:

<img width="508" alt="image" src="https://user-images.githubusercontent.com/7059580/66906192-877c0500-f007-11e9-837a-412a1eb92906.png">

---

When entering a value I get the above mentioned error:
<img width="452" alt="image" src="https://user-images.githubusercontent.com/7059580/66906226-9c589880-f007-11e9-8478-856f9afe90dd.png">

### Steps to reproduce
Not sure if it is downright reproduceable by this:

1. Use Craft (Multisite setup, maybe this matters?) 3.4.x-dev
2. Set up a plain text field
3. Add it to a section and try to fill in content... 🤷‍♂ 

I also tried to downgrade to Craft `3.3.10` to see if it resolves the issue.
Now I can't even open the entry:
If I go to `/admin/entries/pages/` (Pages are `sections`) I would get
> Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: craft\fields\PlainText::byteLimit

### Additional info

- Craft version: 3.4.x-dev
- PHP version: 7.2
- Database driver & version: Mysql
- Plugins & versions: 
```
    "craftcms/element-api": "2.5.4",
    "craftcms/redactor": "2.3.3.2",
    "mmikkel/cp-field-inspect": "1.0.6",
    "nystudio107/craft-seomatic": "3.2.28",
    "putyourlightson/craft-cp-style-guide": "1.0.2",
    "sebastianlenz/linkfield": "1.0.19",
    "spicyweb/craft-neo": "^2.5.5",
    "verbb/field-manager": "2.1.0",
    "vlucas/phpdotenv": "^2.4.0",
```

**Comment by brandonkelly** [comment]
Fixed, sorry about that. Run `composer update craftcms/cms` to get the fix.

**Comment by Jones-S** [comment]
Hm. Thank you for your quick answer. I think it fixed the original issue, but it led to a new one:
https://github.com/craftcms/cms/issues/5112

Then I tried to downgrade to `3.3.11` But then I would not be able to open the page at all with the same error as mentioned above:

`Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: craft\fields\PlainText::byteLimit`

**Comment by brandonkelly** [comment]
@Jones-S Yeah it’s not (easily) possible to roll back to 3.3.x once you’ve updated a site to 3.4, unless you have a DB backup.
