### ISSUE TITLE
Invalid Configuration – yii\base\InvalidConfigException error after Saving Matrix Field

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#5111]
### Description
After I save my Matrix Field I run into this error:
![image](https://user-images.githubusercontent.com/764292/66920404-7d67ff80-f023-11e9-8372-128d85f626b5.png)

Afterwards the whole site is dead. Can't serve any url. Get always the same error. 
It's a bit urgent for me and the client :/

### Steps to reproduce

1. Add a Block to the Matrix Field
2. Hit save

### Additional info

- Craft version: 3.2.10
- PHP version: 7.2
- Database driver & version: 8

I have tried to delete the Storage Folder and ReInstall all Composer Packages.
Nothing helps.

**Comment by brandonkelly** [comment]
You need to fix the permissions of your `storage/runtime/` folder so Craft is able to generate the `compiled_classes/` directory + files again.

**Comment by davidhellmann** [comment]
@brandonkelly hm looks like this is not the problem. 
The folder rights are the same since two years and the same as in other projects. 
Worked last week on the same project and no problems. 

Do you have another Idea whats going wrong here?

**Comment by brandonkelly** [comment]
Have the `storage/runtime/compiled_classes/` directory & files been regenerated since you deleted them?

**Comment by davidhellmann** [comment]
@brandonkelly nope. He creates the folders
![image](https://user-images.githubusercontent.com/764292/67078411-8840a280-f191-11e9-87de-b7aa82f710ca.png)

This are my Folder rights

![image](https://user-images.githubusercontent.com/764292/67078487-ad351580-f191-11e9-8123-2e16254b4120.png)

![image](https://user-images.githubusercontent.com/764292/67078470-a4dcda80-f191-11e9-87ed-3fcc354fd3a5.png)

![image](https://user-images.githubusercontent.com/764292/67078438-968ebe80-f191-11e9-801c-3e040c307e50.png)

**Comment by davidhellmann** [comment]
Nope, he creates the folders but not the files. On our Stage env is the same problem. Looks not like a permission problem. Really strange. I'm a bit clueless.

**Comment by brandonkelly** [comment]
Can you write into support@craftcms.com and reference this issue? We can help you from there.

**Comment by localhorst** [comment]
What was the solution here?

**Comment by brandonkelly** [comment]
@localhorst Not sure about @davidhellmann’s issue, but if you’re experiencing something similar, please write into support@craftcms.com and we should be able to get you sorted.
