### ISSUE TITLE
Request: Dont delete leading slash for Entry URI Format in headless Mode 

### ISSUE THREAD

**Issue by Jones-S** [craftcms/cms#5113]
### Description
This is not a bug but a feature request.
In https://github.com/craftcms/cms/issues/4520 we got to know that URIs were reintroduced for headless mode. Which is great.

It would be really nice though, if the user could decide if he wants to have a leading slash for the URIs or not.
In my case I get all the entries and the uris via graphql and it would be nice for my vue app route generation that they already had a leading slash:

e.g. `/de/{parent.slug}/{slug}`
instead of being stripped to 
`de/{parent.slug}/{slug}`.

### Additional info

- Craft version: 3.4.x-dev
- PHP version: 7.2
<img width="903" alt="Craft-Sections-Multilang-Settings" src="https://user-images.githubusercontent.com/7059580/66942563-a7ccb380-f049-11e9-8248-3cf9d86432f0.png">

**Comment by brandonkelly** [comment]
At that point it’s a (root-relative) URL, not just a URI. So just set your site’s base URL to `/` and then fetch the entry’s URL (`url`) instead of its URI.

**Comment by Jones-S** [comment]
Hm. I tried doing that.
But my graphql service would not provide an option to fetch the entry's `url`:
<img width="431" alt="image" src="https://user-images.githubusercontent.com/7059580/66963280-94ced900-f073-11e9-84b4-69ec8b7d5390.png">

Just the `uri`.
Could you give me a pointer what I am missing here?

**Comment by brandonkelly** [comment]
Maybe we need to add support for `url` :)

**Comment by Jones-S** [comment]
That would be lovely! 👍

**Comment by andris-sevcenko** [comment]
@Jones-S as of next release, you'll be able to use `url` on entry elements via GraphQL!

**Comment by davidhellmann** [comment]
Looks like this is the "Problem": https://github.com/craftcms/cms/blob/2eac9249964ccc553bf841c79b9ee44d58f16b61/src/helpers/UrlHelper.php#L191 :(

**Comment by brandonkelly** [comment]
@davidhellmann Craft intentionally always generates absolute URLs to prevent issues like #2919.

Why not just set the base URL to an absolute URL?

**Comment by davidhellmann** [comment]
Good point. I think I solved it on my site and yes, set the site url now to localhost:3000

Looks like it works now as expected.

**Comment by dwhoban** [comment]
@brandonkelly sorry to jump on a closed issue as we are dealing with this at the moment.  

We are using [Gitlab review apps](https://docs.gitlab.com/ee/ci/review_apps/) but this requires a known Craft CMS API URL to be set once (e.g. dev.craftcms.test/api). Obviously on the other side a Base URL can only be set once for this instance.

Currently we have worked around things where we are using plugins like Navigation or Hyper 
but obviously fields like Redactor are a little trickier to solve.

We keep coming back to needing the baseURL to be '/' to ensure the site is fully testable for review environments
