### ISSUE TITLE
Request: official method for extending user preferences

### ISSUE THREAD

**Issue by evanwarner** [craftcms/cms#5114]
I'm working on a plugin that will have a multi-page section in the CP, and there are a few things I'd like to have each user be able to adjust to their liking. I've already found that I can set (`craft.app.users.saveUserPreferences()`) and read (`currentUser.preferences`) preferences, so I can do what I need. But I will have to build my own UI for it that is separate from the already existing place users set their preferences.

~~And one thing I cannot do is delete a preference (when uninstalling the plugin), as the save function uses `array_merge` and has no way to unset~~ (actually I can just manually execute a db update for each user so that's not a roadblock).

It would be wonderful to have an officially supported way to hook into the existing user preferences screen (the same way we can add to user permissions).

**Comment by brandonkelly** [comment]
I just added a `cp.users.edit.prefs` [template hook](https://docs.craftcms.com/v3/extend/template-hooks.html) to the Edit User page, at the bottom of `div#prefs`. You’ll still have to check for the post data on user save and store it yourself, but this will at least make it easy to get your user preference UI in place where you want it.
