### ISSUE TITLE
What is the best environment practice for "useProjectConfigFile" = true and "allowAdminChanges" = false?

### ISSUE THREAD

**Issue by dillonbailey** [craftcms/cms#5115]
### Description
Our general approach when using the project config file (project.yml) is to allow admin changes on local, but disallow admin changes on all other environments (e.g. staging, UAT, production). However we are finding that in a number of cases, we need to loosen this rule in order to perform required tasks, like activating a craft pro license on the staging environment.

So for the purposes of the issue, we will look at activating a craft pro license on a staging environment. But this request is more seeking to understand the best practice for project configuration across the board.

### Steps to reproduce

1. Setup a local and staging craft environment using a project config file
2. Set allowAdminChanges to false on the staging environment
3. Run both environments without a license (e.g. Solo)
4. Purchase a craft pro license and add the license.key file to your project
5. Deploy the key to your staging environment
6. The staging environment continues to run in Solo mode and you are unable to activate the license without allowing admin changes

### Additional info

- Craft version: 3.2.5.1
- PHP version: 7.3.10
- Database driver & version: MySQL 10.3.18
- Plugins & versions:
Advanced Url Field |	1.0.0
Amazon S3 |	1.2.4
Contact Form |	2.2.5
Craft Cheat Sheet |	2.0.3
Redactor	 | 2.3.3.2
Super Table |	2.2.1

**Comment by brandonkelly** [comment]
You can purchase Craft Pro locally or at plugins.craftcms.com. Make sure you're using the same license key (`config/license.key`) across all environments – either by adding that file to Git (if it’s not already there) or if you want to avoid that, save it to an environment variable with the same value in all environments, and assign it to Craft with the [CRAFT_LICENSE_KEY](https://docs.craftcms.com/v3/config/php-constants.html#craft-license-key) constant in `web/index.php`.

```php
define('CRAFT_LICENSE_KEY', getenv('CRAFT_LICENSE_KEY'));
```

**Comment by dillonbailey** [comment]
Thanks for the guidance @brandonkelly. However the issue still exists in my opinion or should receive some documentation. If we purchase the license locally, updating the license key as described, our staging and production environments will not update to use the pro license without allowing admin changes and clicking “reactivate” in the admin panel. 

Given this behaviour I feel the process should be more well documented for those who want to disallow admin changes in staging and production environments.

**Comment by brandonkelly** [comment]
The selected edition is recorded in `project.yaml`, so all environments should be in sync on that.

**Comment by dillonbailey** [comment]
@brandonkelly understood, that’s not the behaviour we are getting on our deployment. Even after running project configuration syncs, the staging environment remains on a solo trial unless we reactivate via the admin panel on that environment.

**Comment by brandonkelly** [comment]
Hm, yeah that’s not right. It could be that something got out of alignment due to a merge conflict or something. As a starting point why don’t you try running through the [Enabling the Project Config](https://docs.craftcms.com/v3/project-config.html#enabling-the-project-config-file) steps again, and see if that helps. If not then send an email over to support@craftcms.com and we can look into it from there.

**Comment by dillonbailey** [comment]
Too easy. Thanks @brandonkelly

**Comment by dillonbailey** [comment]
Hey @brandonkelly I went through these steps again and managed to get it all syncing by watching the changes to project.yml between deployments. Don't know what was happening before!

Thanks again for bearing with me!

**Comment by brandonkelly** [comment]
Glad to hear it’s working for you again!
