### ISSUE TITLE
Entries field throws "This field is required" error with only related entries from another Site selected

### ISSUE THREAD

**Issue by naboo** [craftcms/cms#5116]
### Description
If you have an Entries field and you only select entries from another Site, and the entries themselves aren't available in the current Site (either the section isn't enabled, or the entries aren't set to propagate over) the "This field is required" validation error message is being thrown. 

**This is only** if the field itself is set to be "Required". If you remove that requirement the field saves the relations from the other Site without throwing the error.

### Additional info

- Craft version: Craft CMS 3.3.8
- PHP version: 7.2

**Comment by brandonkelly** [comment]
Thanks for reporting that! It’s been fixed for the next release.
