### ISSUE TITLE
craft setup unable to test the db credentials with DDEV as local environment

### ISSUE THREAD

**Issue by rpkoller** [craftcms/cms#5117]
### Description

If i try to setup a new site in the DDEV local environment with `craft setup` the testing of db credentials fails. if i try with the same credentials with the web version `http://crafttest.ddev.site/index.php?p=admin/install` everything works flawlessly. 

### Steps to reproduce

1. mkdir ~/sites/crafttest
2. cd ~/sites/crafttest
3. composer create-project craftcms/craft ~/sites/crafttest
4. ddev config   (with default settings crafttest, web, php)
5. ddev start
6. ./craft setup
7. applied settings:

```
Which database driver are you using? [mysql,pgsql,?]: mysql
Database server name or IP address: [localhost] db
Database port: [3306]
Database username: [root] db
Database password: db
Database name: db
Database table prefix: cr_
```

8. the resulting error: 
```
Testing database credentials ... failed: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known
```

### Additional info

- Craft version: craftcms/cms (3.3.11)
- DDEV version: v1.11.2
- PHP version: 7.2.22
- Database driver & version: MySQL 5.5.5

**Comment by angrybrad** [comment]
You're not running `craft setup` from within the container, which is where the DB settings would be applied.

Try `ddev ssh` first, then run setup: https://ddev.readthedocs.io/en/latest/users/cli-usage/#ssh-into-containers

There's a good guide on MAMP to DDEV here too if that fits: https://workingconcept.com/blog/mamp-pro-to-ddev

**Comment by rpkoller** [comment]
uhhhh sorry for the false alarm and thank you for the fast reply! i still tend to forget in rare occassions when using ddev that, in particular cases like the 'craft setup' one, it is necessary to run the command inside the container.
in case anyone else stumbling across the same issue. 'ddev ssh' isn't necessary just 'ddev exec craft setup' or  'ddev . craft setup' should be enough. it simply executes the setup command inside the container no login via ssh necessary. and thanks for the link to the article. a good one! :) best regards r.
