### ISSUE TITLE
GraphQL: globalSet asset field returning empty array when it shouldn't be empty

### ISSUE THREAD

**Issue by Marcuzz** [craftcms/cms#5119]
### Description
We're facing an issue where an assets fields can not be retrieved, regardless of what field we're trying to retrieve. For example:

![image](https://user-images.githubusercontent.com/3168421/67097989-93a8c380-f1bb-11e9-86f7-295b2f9d1d91.png)

You can see that footerLogo only returns an empty array.

The footerLogo field does not have any special options:

![image](https://user-images.githubusercontent.com/3168421/67098139-e5514e00-f1bb-11e9-9527-1a0132a0b880.png)

The footerLogo is selected as following (it's an SVG, but it does not work with a png either):

![image](https://user-images.githubusercontent.com/3168421/67098309-3d885000-f1bc-11e9-85d5-8dc260918229.png)

Yet the response from GraphQL is an empty array as opposed to an array containing one object.

We're using a local volume. We've also tried with a remote S3 volume but they both have the same problem.

Can anyone else reproduce this and more importantly; does anyone know if we're doing something wrong or if this is actually a bug?

I tried searching existing issues but I can't find anything regarding this issue.

### Steps to reproduce

1. Create a global section
2. Create an asset field
3. Select an asset for this field
4. Query the globalSet in GraphQL
5. The response will be an empty array

### Additional info

- Craft version: 3.3.9
- PHP version: 7.3
- Database driver & version: MariaDB 10.4.7 
- Plugins & versions: Stock Craft CMS Pro

**Comment by andris-sevcenko** [comment]
Does the public schema have the permission to see the contents of the Volume where the assets are?

**Comment by Marcuzz** [comment]
Yep, that was it! Thanks for spotting that for me :)

I didn't realize there was volume permissions related to a schema as well, whoops!
