### ISSUE TITLE
[Request] index.php with .env variables in headless mode (to display login link)

### ISSUE THREAD

**Issue by Jones-S** [craftcms/cms#5121]
### Description
This is not a bug, but a feature request (or a question).
Before the headless mode I had an index.php where I would load a template to show a little screen with a link to the login (backend) a link to the frontend URL (another domain) and a little welcome message.

Just for the case a client goes to the backend domain straight without remembering that he has to go to /admin/

I realize that I could add a `/web/index.html` – but instead of copy pasting my Site url and my frontend URL I would like to pull that info from the .env file.

I did that before with the `index.php` for example with code like:
```
<a class="button" href="{{ craft.app.config.general.backendUrl }}admin/login">Login</a>
```
How could I get back to susch a solution with headless mode?

Thanks for some input.

### Additional info

- Craft version: 3.4.x-dev
- PHP version: 7.2
- Database driver & version: mysql

**Comment by brandonkelly** [comment]
If you’re exposing the CP URL like that, then I think a better idea would be to just kill the CP trigger to begin with. I just posted #5122 with a proposal to make that possible.
