### ISSUE TITLE
Queries not working correctly in product Live Preview

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/cms#5123]
### Description
Relations are not working correctly for me when viewing a product page in Live Preview. If I click the share button everything works as expected, but when using Live Preview relations will return unexpected results: sometimes null, sometimes elements that are from a different section/group/etc. than the original query. Images below show breadcrumb section on Share vs. Live Preview.  Occurs in both production and dev environments on product pages both enabled and disabled.

<img width="1403" alt="share" src="https://user-images.githubusercontent.com/21298596/67042676-fb90d880-f0ed-11e9-9fea-cf3ddafbb45b.png">
<img width="1403" alt="livePreview" src="https://user-images.githubusercontent.com/21298596/67042675-fb90d880-f0ed-11e9-8f5f-802b96f16907.png">

### Steps to reproduce

1. Go to product page with that contains relations.
2. Click Share button, then click Live Preview.
3. Compare pages.

### Additional info

- Craft version: 3.3.11
- PHP version: 7.2.19
- Database driver & version: MySQL 5.7.27
- Plugins & versions: Commerce 2.1.13

**Comment by brandonkelly** [comment]
Can you post your template code?

**Comment by jmauzyk** [comment]
@brandonkelly Sorry for the slow response, had to focus my efforts elsewhere for a while. I've narrowed the issue down to this line of template code:
```twig
{% set productCategories = product.productCategories.id('not ' ~ newProductCategory.id).all() %}
```

On regular page load, the code performs as expected, returning any category from the `productCategories` relationship field that does not match the `newProductCategory` id.

When loaded in live preview, it instead loads *any category* that does not match the `newProductCategory` id.

I tried explicitly calling out `.id('not 149')` as well as `.id(['not', 149])` but both produced the same behavior in live preview.

**Comment by brandonkelly** [comment]
Try this:

```twig
{% if craft.app.request.isLivePreview %}
    {% set productCategories = product.productCategories.all()|filter(category => category.id != newProductCategory.id) %}
{% else %}
    {% set productCategories = product.productCategories.id('not ' ~ newProductCategory.id).all() %}
{% endif %}
```

**Comment by lukeholder** [comment]
This should be solved with Brandon‘s example.

**Comment by jmauzyk** [comment]
@lukeholder I finally had time to circle back to this. I was able to get live preview working for me for the time being using Brandon's example as a guide. However, I'm curious if the behavior I'm experiencing is expected. In live preview for a product page, calling `{% set productCategories = product.productCategories.all() %}` successfully queries as expected. However, when excluding IDs e.g. `{% set productCategories = product.productCategories.id('not ' ~ newProductCategory.id).all() %}` I experience the behavior described in my original post above. Also noticing other weird behavior in live preview, for example calling `product.productCategories.id(newProductCategory.id).exists()` always returns true in live preview, even when that is not the case. Is this a known issue?

**Comment by brandonkelly** [comment]
@jmauzyk That’s a known issue with the legacy Live Preview implementation (see #1787 & #2801), which is still used by everything besides entries at the moment. You have to get a little creative with how you filter the elements, without modifying the element query. Example: https://craftcms.stackexchange.com/a/8880/9

**Comment by jmauzyk** [comment]
@brandonkelly Gotcha, thanks for clarifying!
