### ISSUE TITLE
How could preview target know multisite siteHandle?

### ISSUE THREAD

**Issue by Jones-S** [craftcms/cms#5126]
### Description
I just realized that with a multisite setup I need to tell the frontend app for which site the graphql queries should be made. Would it be possible to send the siteHandle which is already present in the URL itself to pass on to the iframe url?

By that I could read out that parameter and send it with my axios request to my graphql service.

`<iframe class="lp-preview" src="http://localhost:3000/page-one?x-craft-live-preview=ZsjpWlE5QX&amp;token=47mZ3sacE0IkXqPB7ItPPIGqQJqKQ-tp" frameborder="0"></iframe>`

--> 
`<iframe class="lp-preview" src="http://localhost:3000/page-one?x-craft-live-preview=ZsjpWlE5QX&amp;token=47mZ3sacE0IkXqPB7ItPPIGqQJqKQ-tp&?site=mySiteHandle" frameborder="0"></iframe>`

### Additional info

- Craft version: `3.4.x-dev`
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
You can pass it from your Preview Target URL, e.g. `http://localhost:3000/{slug}?site={site.handle}`.

**Comment by Jones-S** [comment]
Sure, sorry. Could have realized that by myself. 👍
