### ISSUE TITLE
Conditional URI for preview target (/slug and /parentslug/slug instead of //slug and /parentslug/slug)

### ISSUE THREAD

**Issue by Jones-S** [craftcms/cms#5128]
### Description
Another question about urls. This time in relation to our preview targets.

So far I had
<img width="964" alt="image" src="https://user-images.githubusercontent.com/7059580/67156014-9faa9780-f319-11e9-871f-de82d94b6c0c.png">
`@previewUrl/{slug}?site={site.handle}`

But to correctly load my vue templates I need to know the current nesting level of a preview.

I tried to use
`@previewUrl/{parent.slug}/{slug}?site={site.handle}`

This works for the nested pages if a parent slug exists, but for first level entries I get
`...//slug`.

Is there a way to write a conditional url format, like
`@previewUrl{parent.slug ? '/parent.slug' : ''}/{slug}?site={site.handle}`

I realize that I could solve it with parameters again:
`@previewUrl/{slug}?site={site.handle}&parent={parent.slug}`

But it seems a bit clunky.
Maybe you have a suitable idea.

Thank you.

Cheers

### Additional info

- Craft version: 3.4.x-dev
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
> Is there a way to write a conditional url format, like
> `@previewUrl{parent.slug ? '/parent.slug' : ''}/{slug}?site={site.handle}`

Yep, the actual syntax would be:

```twig
@previewUrl/{parent ? parent.slug ~ '/' : ''}{slug}?site={site.handle}
```

**Comment by Jones-S** [comment]
Ah very sweet. Could I have found that in the docs somewhere?

**Comment by brandonkelly** [comment]
The docs say you can use Twig (https://docs.craftcms.com/v3/sections-and-entries.html#preview-targets), but this particular example is not given. It’s just Twig syntax though – except that we’ve added support for the single `{` syntax. You could swap that with `{{` and `}}` though and it would still work the same.

**Comment by Jones-S** [comment]
Ok cool. thanks for the hint. Next time I will try to search a bit more.
