### ISSUE TITLE
Live Preview missing in Headless Mode

### ISSUE THREAD

**Issue by cmmize** [craftcms/cms#5135]
### Description
Running Craft 3.3.11 in a headless mode.  There is no Live Preview button.  How do you configure Craft 3.3.11 to have Live Preview enabled?

### Steps to reproduce

1. Install Craft 3.3.11
2. Enable Headless mode

### Additional info

- Craft version: 3.3.11
- PHP version: 7.2.8
- Database driver & version: MySql v. 5.7.23
- Plugins & versions: Element API 
![Home](https://user-images.githubusercontent.com/3842689/67216989-131fd800-f3f2-11e9-9148-9355f7d8954f.png)
2.6.0

**Comment by brandonkelly** [comment]
You would need to set up at least one [Preview Target](https://docs.craftcms.com/v3/sections-and-entries.html#preview-targets) in your section settings.

**Comment by cmmize** [comment]
So you have to have pro version for headless preview?  From docs:  "With Craft Pro, your sections will have a “Preview Targets” setting, where you can list additional places your entries will show up on your site, so that authors can quickly preview entries everywhere they appear."

I don't see “Preview Targets” setting in the craft solo.... also don't see where to update to pro?

**Comment by brandonkelly** [comment]
Sorry, yeah, it’s a Pro-only feature. You can upgrade from within the Plugin Store, or just click the “SOLO” badge in the sidebar to go straight to that page.
