### ISSUE TITLE
'Restrict uploads to a single folder' setting not applied for all sites in multilang setup

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#5139]
### Description

Assets seem not to be properly moved to their desired location when setting up an assets field with 
* Restrict uploads to a single folder
* Upload location: {section.handle}/{sourceId} (actually a custom field in real life here)
* Manage relations on a per-site basis

One image (on the site active when saving) is moved, the other stays in the temporary upload folder.

### Steps to reproduce

1. Set up two sites  (de/en)
2. Create a field as described above.
3. Create a new entry and add different images for both sites.
4. Save => One image stays in the temporary upload folder.

### Additional info

- Craft version: 3.3.11
- PHP version: 7.2.14
- Database driver & version: MySQL 5.7.14
- Plugins & versions: None

**Comment by andris-sevcenko** [comment]
I am not able to reproduce this on 3.3.12.

You are saving entry once per site, right?

**Comment by wsydney76** [comment]
@andris-sevcenko Sorry, should have described the steps in more details.

Updated to 3.3.12, and this is how the image field is setup:
https://gist.github.com/wsydney76/b96994a94bda4ba1e975053b4bf43f63#file-project-yaml-L27

The steps to reproduce:

1. Select site 'en' in entries listing
2. Click new entry => En - first draft is opened
3. Add title and upload an image to the image field, e.g. 1.jpg
4. Switch to site 'de' => the image field also shows the initially propagated 1.jpg
5. Deselect 1.jpg
6. Upload a second file, e.g. 2.jpg
7. Click Save to create the 'real' entry.

Check assets:
* 2.jpg (belonging to the site that was active when saving) is correctly moved to folder type/id
* 1.jpg (belonging to the inactive site) is still in the 'temporary uploads' folder, resulting in a broken image on frontend in case this folder is not accessible.

Thanks for looking into it.

PS. 
Client is currently only considering using not translatable fields/id for the upload location, so no possible conflicts here. But i think things can get a bit unpredictable when using translatable fields/slug for the upload location, especially if the same image is used for all sites.

**Comment by andris-sevcenko** [comment]
Fixed for the next release!
