### ISSUE TITLE
Character Limit incorrect for international characters 

### ISSUE THREAD

**Issue by antcooper** [craftcms/cms#5141]
Repost of [StackExchange post](https://craftcms.stackexchange.com/questions/32614/character-limit-incorrect-for-international-characters)

### Description
I've been running into errors importing specific entries in my custom module. Boils down to an issue with the Character Limit on the Plain Text fieldtype when importing international characters.

It seems like the Character Limit on the field is actually the number of bytes and not characters. The text I'm trying to import has some multi-byte Japanese characters, so it is reporting the length incorrectly.

I've had a poke around the Craft and yii source and found some string validation, but then it gets a bit beyond me.

For now I've just extended the length limit, but would good to work out if I have something setup incorrectly.

### Steps to reproduce

1. Using $entry->setFieldValues() within a custom module

### Additional info

- Craft version: 3.3.11
- PHP version: 7.2
- Database driver & version: MySQL 5.7

**Comment by brandonkelly** [comment]
Yii’s StringValidator uses [mb_strlen()](https://www.php.net/manual/en/function.mb-strlen.php) to get the string length. It assumes that the string is UTF-8-encoded, perhaps that’s not the case? Perhaps try running your values through [craft\helpers\StringHelper::convertToUtf8()](https://docs.craftcms.com/api/v3/craft-helpers-stringhelper.html#method-converttoutf8) before setting it on the entry.

```php
$entry->setFieldValues([
    'fieldHandle' => StringHelper::convertToUtf8($oldValue),
]);
```
