### ISSUE TITLE
GraphQL cache invalidation on schema change

### ISSUE THREAD

**Issue by dangayle** [craftcms/cms#5148]
Can we add some sort of cache invalidation on our GraphQL schema whenever it or some fields/entries/globals change? I just spent the better part of an hour trying to figure out why my new entry type was not populating in GraphQL, despite the fact that I had checked it. Felt so dumb when someone suggesting clearing my cache.

**Comment by narration-sd** [comment]
Actually, I think Gql cache isn't getting invalidated for (much of?) anything, on 3.3.12 or dev-develop.

Not on saving Entries, anyway. Looks like the doc'd intent got a miss on this delivery.

Actually,  though, it would be entirely fine for builds of Spas if there were some way to turn off caching as a GraphQL argument, most preferably on the Query.  One might even say rather necessary, if you think it through...

**Comment by narration-sd** [comment]
In the mean time, ` 'enableGraphQlCaching' => false,`  in a suitable spot of `config/general.php`, may be helpful...

**Comment by khalwat** [comment]
@narration-sd yep yep -> https://github.com/craftcms/cms/issues/5152

**Comment by andris-sevcenko** [comment]
Jesus. Sorry about this.
