### ISSUE TITLE
Add site query to GraphQL

### ISSUE THREAD

**Issue by jan-thoma** [craftcms/cms#5151]
**This is a feature request.** 

If i'm not missing anything it's not possible right now to query sites. In multisite environments it would be quite handy to have the option to query a sites basic information. For example when we want to build the routes definitions for frameworks like Vue.js on the fly, something like this would be very helpful:

```
{
  sites(groupId: 1) {
     group
     name
     handle
     language
     primary
     baseUrl
  }
}
```

This would allow us to build nested routes in the mentioned frontend frameworks, which makes 
handling multilang content much easier.

**Comment by narration-sd** [comment]
+1 -- I'd been ready to ask for this already today, if the other thing hadn't interrupted, as it could be very useful in specific as well as general ways.  Meta even more than I have, so often a good thing.

A nice set of fields to begin with, @jan-thoma :

**Comment by andris-sevcenko** [comment]
It's certainly a possibility for 3.4.

**Comment by andris-sevcenko** [comment]
This is pretty much the same as #5472, so closing this one in favor of that one.

**Comment by andris-sevcenko** [comment]
Edit: fixed the issue number in the previous comment.
