### ISSUE TITLE
Gql: caching needs a full flush ability per individual query access

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#5153]
### Description
If you've been building static Spa loads for real sites, you'll  understand or soon about  this one.

- As of Craft 3.3. 12 or current dev-master, internal GraphQL (Gql) has a query result cache, a desirable feature for sure.
- It also has an Craft config item `enableGraphQlCaching'` which can be set to disable this
- But, this is not sufficient. Here's some reasoning:
  - for a real site, you most conveniently want to compile ('build') the static html site on a development or other administrative machine. 
  - especially, during Spa development itself, but also on less than formidably scripted/remote controlled/'devops' sites. 
  - at the same time,  you must run those GraphQL page queries against the live site, in order to provide a Spa build which will access resources (e.g. image Assets) as they are target-content configured for that live site's Entries. 
  - Targeting on the same live content machine, is going to be a prevalent case in the field (see, less than 'devops')
  - you don't want to take the live Craft content machine down to uncached etc. while you are doing this, and that would be one more every-time remote operation during dev anyway if you did.
  - Spa systems often have quite enough to keep track of by themselves for successful builds which are to go live -- their own primitive caches that must be dumped manually, for example.
  - Especially true during development...but also when websites want a content re-frocking, which can be quite often even for small ones.

Ok, if you see these points, then it's also pretty evident that control of the Gql cache  needs to be exercisable from the GraphQL query itself. 
- this way the flag can be built into the page queries so that they will always receive fresh data for their static builds, normal fashion
- No touching of the live machine will be necessary, while up-to-date data as _always_ desired for the static build will so arrive.
- The most evident place to put  a flag seems to be as an argument in the outer definition of the query, where you would otherwise define query variables to be pulled into inner items.
- In positioning, it should be fundamentally possible to set a static state for the flag, i.e. `craftGqlCache: false`. 
- This pattern allows the base case of not having to have any formal query variables defined in the Spa machine, which you may not be able to do. But it also allows _use_ of query variables for control of caching during external operations as may be desirable, say for api tools.

A set of thoughts to begin with, anyway....

**Comment by narration-sd** [comment]
Seems should relate to these two as well... #5148, #5152

**Comment by andris-sevcenko** [comment]
As I brought up in both of the related issues - I'm pretty sure that the, fix now in the repository and awaiting a hotfix release, addresses this, since you'll never have stale content in the cache now?

**Comment by narration-sd** [comment]
I'll try it, and think about it, mañana, could be.  Up only to sort out a .git repo that suddenly turned up unusable after a long day's work, but thinking you did good here, Andris, no fault on a small miss even if big shadow, and quick recovery. Take care.

**Comment by narration-sd** [comment]
@andris-sevcenko , big win here, to offset any moments before.

- This works, and I seem to foresee your overall approach to making the cache transparent to updates going to be fine. 
- I've got it running on a puny-enough remote droplet prior to patch, and:
  - saved changes in current live entry are immediately available to the dev server of the Spa
  - and thus also transparently to the build for the Spa -- which is noticeably faster due to cache
  - build comes out just right, popped up to the droplet site
  - 'Share' from the draft is also updated properly from previewed draft changes
  - Share refreshes also appears quite speedy, noticeably more so
  - actually everything is very responsive, so there may be more upgrade than your query cache alone in this - schema cache??
  - the built live site is of course very speedy indeed, compiled Spa, but thanks to your kit  making that now smooth as well as possible.

I'm going to have to give you a chance to see this thing, soon. Letter is actually written, waiting for me to get demo fully together.  Thanks for a great upgrade with this feature, Andris...

**Comment by andris-sevcenko** [comment]
> actually everything is very responsive, so there may be more upgrade than your query cache alone in this - schema cache??

Yeah, if Craft has a cached result for the used access token combined with the query and other variables, there's really no need to invoke anything GraphQL related at all, so no schema is built. It's pretty frickin' fast now :)

**Comment by andris-sevcenko** [comment]
> alone in this - schema cache??

To clarify: the schema built by the IDE is based on the introspection query. Which is also a query and is cached.

**Comment by narration-sd** [comment]
> It's pretty frickin' fast now :)

Indeed it is, and quite appreciated for this - it's going to be a real marker for persons  who understand this, and for Craft -- not to say gives a boost on my own work forwards to see, you can probably understand...got something pretty interesting done yesterday, of the remaining.

My sense of how you've thought about and done this project overall is that it's high accomplishment. A little underline to how @angrybrad and @brandonkelly appreciate your work, as you see I do also..

I also have some idea, in the way my mind seems to prefer to work, that you got your freedom to do this your own way, more than ever. 

Can account for a number of matters, which would be understood, but most of all, a step forward which definitely makes me smile. 

You have it good, Andris -- Clive
