### ISSUE TITLE
Craft not updating composer.json when uninstalling plugins

### ISSUE THREAD

**Issue by iamkeir** [craftcms/cms#5154]
### Description
Craft does not seem to update `composer.json` when uninstalling/removing plugins.

### Steps to reproduce

1. Install a plugin
2. Notice `composer.json` is updated with reference to that plugin
3. Uninstall the same plugin
4. Notice how the reference to the plugin remains in `composer.json`

### Additional info

- Craft version: 3.3.7
- PHP version: 7.2.14
- Database driver & version: MySQL 5.7.25
- Plugins & versions: any

**Comment by brandonkelly** [comment]
The plugin isn’t actually Composer-uninstalled until you select the “Remove” option, which only shows up after you’ve selected “Uninstall”.

<img width="108" alt="An action menu for an uninstalled plugin, with “Install” and “Remove” options" src="https://user-images.githubusercontent.com/47792/67406223-a5e38280-f56a-11e9-92cd-2d37dad68597.png">
