### ISSUE TITLE
[FR] Add arrow function support to the group Twig filter

### ISSUE THREAD

**Issue by rungta** [craftcms/cms#5156]
### Description

Twig arrow functions offer a simpler syntax, access to context variables, and much more flexibility for customizing logic.

Sample use case – group a list of entries by their section handles, except for singles which should all be grouped together. 

```twig
{% set entriesBySection = entries|group(e => e.section.type == 'single' ? 'single' : e.section.handle) %}
```

(I’m aware this particular use case can also be handled by `renderObjectTemplate` and the existing `group` filter.)

**Comment by brandonkelly** [comment]
Great idea! Added for the next release.
