### ISSUE TITLE
CSS issue when creating new section (single only)

### ISSUE THREAD

**Issue by SayChi** [craftcms/cms#5159]
### Description
It seems like some js is adding a weird min-height to the site-settings textareas when you create a new section. This makes the table huge for no reason.

### Steps to reproduce

1. Create new section (keep section type at channel for now)
2. Type something in the title field
3. Notice nothing weird is happening so far
4. Change section type to single
5. Add or remove a character from the title
6. BAM! Table gets huge (min-height: 154px + 20 * title.length per text area)

### Additional info

- Craft version: 3.3.12 (also confirmed in 3.3.6 and 3.3.0.1)
- PHP version: 7.1.32
- Database driver & version: MySQL 5.5.64
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.
