### ISSUE TITLE
Daylight saving still (Brazil)

### ISSUE THREAD

**Issue by effer89** [craftcms/cms#5163]
### Description
In Brazil we had daylight saving until last year (usually from november to february), this year we do not have it anymore, government decision.

But craft still using it on PostDate, CreateDate and UpdateDate.

I already set the correct timezone in my system (Debian 9) and php.ini.

In my config of craft it's right the timezone 'America/Sao_Paulo'

When I run `date` on terminal it gives me the right time.

If I run on .php file `date('Y-m-d H:i:s');` it gives the correct time as well.

### Steps to reproduce

1. Create/update an entry.

### Additional info

- Craft version: Craft Pro 3.3.5
- PHP version: 7.1.18
- Database driver & version: -
- Plugins & versions: -

**Comment by angrybrad** [comment]
Any chance we could get some Craft CP and SSH/(s)FTP access to the box to investigate?  If so, could you send it over to support@craftcms.com and reference this Github issue?
