### ISSUE TITLE
Orphaned Entry Types?

### ISSUE THREAD

**Issue by proimage** [craftcms/cms#5165]
### Description
I've got a site where at one point there were a few "An unknown error occurred" flash messages in the CP, and now there are these orphaned Entry Types I can't seem to get rid of.

Basically, whenever I import `project.yaml` into an environment,  it adds these entry types. When I try to delete them via the backend, I get another flash error message and they don't appear to get deleted, but when I refresh the page, they're gone.

However, they're still in the `project.yaml`, even if I run `./craft project-config/rebuild`. I see them in there... taunting me... 😨 

I could manually edit the project file to delete them, but in a DB search for the name of the Entry Types (they are 3 duplicates, all with the same name), I found a reference in the `info` table. I also figured I might need to send you the `project.yaml` and a DB dump, so I figured I'd hold off on deleting the pests until I heard from y'all at P&T.

### Steps to reproduce

1. Have something go wrong in the backend during development
2. Be unable to fix it by normal means.

(sorry, I really have no idea how to reproduce this)

### Additional info

- Craft version: Craft CMS 3.1.26
- PHP version: 7.2.19-0ubuntu0.18.04.2 (cli) (built: Aug 12 2019 19:34:28) ( NTS )
- Database driver & version: MySQL Ver 14.14 Distrib 5.7.27, for Linux (x86_64) using  EditLine wrapper
- Plugins & versions:
	- Advanced Image Field	1.0.0
	- Button Box	2.0.3
	- Contact Form	2.2.4
	- Contact Form Honeypot	1.0.2
	- Control Panel CSS	2.1.0
	- Digital Download	2.1.5
	- DigitalOcean Spaces Volume	1.1.1
	- Entry Instructions	1.0.5
	- Field Manager	2.1.0
	- Freeform	3.1.0
	- Imager	v2.1.10
	- Imager Storage Driver for DigitalOcean Spaces	1.0.0
	- Mix	1.5.2
	- Neo	2.3.3
	- oEmbed	1.1.6
	- Postmark	2.0.2
	- Redactor	2.3.3.2
	- Redactor Custom Styles	3.0.2
	- SEO	3.5.4
	- Super Table	2.1.21
	- Typed link field	1.0.19

**Comment by brandonkelly** [comment]
It’s probably going to be easiest for us to tackle this if you send in your `composer.json` and `composer.lock` files plus a database backup and steps to reproduce to support@craftcms.com

**Comment by proimage** [comment]
Done! GLHF :p

**Comment by olivierbon** [comment]
Updating to `3.1.34.3` and running `./craft project-config/rebuild` seems to fix the issue.
