### ISSUE TITLE
Search index not rebuilt when disabling search on Entries field type

### ISSUE THREAD

**Issue by MattRogowski** [craftcms/cms#5168]
### Description
When disabling an "Entries" field from being searchable, the search index doesn't get updated with the new data, and still gets searched.

I have re-saved all the relevant entries and cleared every cache, however I can still see the old data in the `searchindex` table, and it is still being searched even though `searchable` is set to `0` in the `fields` table.

### Steps to reproduce

1. Set up an "Entries" field to be used on an entry type - keep "Use this field’s values as search keywords?" checked
2. Create two entries, Entry A and Entry B
3. Set Entry B to have a specific keyword somewhere in the title (I used "badger")
4. Edit Entry A, and pick Entry B as a related entry
5. If you now search for "badger", you will be returned Entry A and Entry B - this is expected
6. Edit the field, and un-check "Use this field’s values as search keywords?"
7. When you now search for "badger", Entry A and Entry B still gets returned - this is wrong, as it shouldn't be searching this field at all
8. Edit Entry B and Remove the reference to "badger" from the title
9. When you now search for "badger", Entry A still gets returned - this is wrong as the related entry doesn't even contain "badger" any more - re-saving Entry A has no effect
10. Edit the field again, and re-check "Use this field’s values as search keywords?"
11. Save Entry A (without changing anything)
12. The row in the `searchindex` table is now gone, and if you search for "badger", you now get no results, as expected
13. You could now un-check "Use this field’s values as search keywords?" again, however you'd have to repeat step 11 with every entry that related to Entry B

So, the problem seems two-fold:

1. The `searchindex` data does not get updated for a field if "Use this field’s values as search keywords?" is unchecked
2. The `searchindex` data is still used even if the associated field has `searchable` set to `0`

Problem 1 is not an issue in itself without Problem 2 - if it didn't try and use the `searchindex` data for un-searchable fields, it wouldn't matter if the indexed data was out of date.

### Additional info

- Craft version: 3.3.13
- PHP version: 7.2.20
- Database driver & version: MySQL 5.7.26
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
I should clarify, the second issue you mentioned is not really the problem. The time that fields’ searchable settings should be factored in is when updating search indexes, not from search queries themselves. So you will need to resave your entries before the change will take effect, either one-by-one from the Control Panel, or using the `resave/entries` console command. (And for posterity, if running Craft 3.4+, you will need to run `resave/entries --update-search-index`, as search indexes will no longer be updated by default.)

**Comment by MattRogowski** [comment]
That makes sense - thank you for fixing this so quickly!
