### ISSUE TITLE
Craft 3.3.x passes an Entry with no id to the EVENT_BEFORE_SAVE event.

### ISSUE THREAD

**Issue by ryanpcmcquen** [craftcms/cms#5173]
### Description

This issue is not present on 3.1.x, but running 3.3.13, `var_dump`-ing `$e->sender->id` shows that it is `null`.

### Steps to reproduce

1. Add an `EVENT_BEFORE_SAVE` containing the following code:
```php
        Event::on(
            Entry::class,
            Entry::EVENT_BEFORE_SAVE,
            function ($e) {
                var_dump($e->sender->id);
            }
        );
```
2. Save an entry.
3. Observe the stack trace that happens when id is `null`.

### Additional info

- Craft version: 3.3.13
- PHP version: 7.2.x

**Comment by brandonkelly** [comment]
This is expected; an entry can’t have an ID before it is saved for the first time. And it was definitely also the case in 3.1. The difference is that in Craft 3.2+, there will also be save events for entry revisions that are created when saving an entry, and also when creating new drafts of entries.

Per the [EVENT_BEFORE_SAVE](https://docs.craftcms.com/api/v3/craft-base-element.html#event-before-save) docs, you can filter out events for drafts/revisions by checking [ElementHelper::isDraftOrRevision()](https://docs.craftcms.com/api/v3/craft-helpers-elementhelper.html#method-isdraftorrevision).
