### ISSUE TITLE
Add minification parameter to {% js %} and {% css %} Twig tags

### ISSUE THREAD

**Issue by timeverts** [craftcms/cms#5183]
### Description
This is an enhancement request.

It would be really beneficial if it were possible to specify a parameter in the Twig `{% js %}`  and `{% css %}` tags to make the contents of the be minified when output. It would save having to install a minification plugin to do this.

For example, something like this:
```
{% js at head minified %}
// This comment would be removed in output
if (console) {
    console.log('Minfiied JS')
}
{% endjs %}
```

And this:
```
{% css minified %}
.foo {
    color: red;
}
{% endcss %}
```

**Comment by brandonkelly** [comment]
Good idea. CSS and JS are now minified by default for Craft 3.4.

You can disable JS minification using the [useCompressedJs](https://docs.craftcms.com/v3/config/config-settings.html#usecompressedjs) config setting. There are also new `minifyCss` and `minifyJs` properties on `craft\web\View` that can be set to `false` from `config/app.php` if desired:

```php
return [
    'components' => [
        'view' => function() {
            $config = craft\helpers\App::viewConfig();
            $config['minifyCss'] = false;
            $config['minifyJs'] = false;
            return Craft::createObject($config);
        },
    ],
];
```

**Comment by timeverts** [comment]
Awesome work @brandonkelly! Thanks.

**Comment by brandonkelly** [comment]
This ended up having major performance drawbacks, so I‘ve disabled JS/CSS minification by default as of the next release (3.4.22).

You can force Craft to continue minifying JS & CSS by adding the above example code to `config/app.php` – just change `false` to `true`.
