### ISSUE TITLE
Suggestion: Actual License Enforcement

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#5185]
The fact is, if a client isn't physically restricted from using Craft when it's unlicensed, they frequently won't bother buying a license. I don't think this is fair on P&T, and I can't do anything about it. Why is this not actually enforced? I hate to use WordPress as a reference, but their plugins frequently do this, and are entirely within their rights to. If you haven't paid for something, you shouldn't be able to use it.

As far as I can tell, most developers want Craft to succeed, but it's client laziness that results in unpaid licenses. If there were something more than a red bar just saying "You’re running Craft Pro with a Craft Solo license" such as not updating entries, or locking them out of the CMS entirely, P&T might find some more money coming in.

**Comment by gtettelaar** [comment]
+1. Wonder what the best way to enforce this would be though?
