### ISSUE TITLE
Internationalization: field name and field instructions should be translatable per site or language

### ISSUE THREAD

**Issue by outline4** [craftcms/cms#5188]
In the "field" and "field edit" page there should be the same site's dropdown as everywhere else (e.g. globals), making it possible to translate the field names and instructions. 

When it comes to localization, just imagine a Chinese person was setting up the control panel and you need to fill it out (I'm talking to you, fellow Americans).  
Let's say fill out this field: 许可证号  
Would you know what to fill in? 

I guess we all need to work our mandarin ;) 

Cheers  
Stefan

**Comment by brandonkelly** [comment]
You can provide translations for site, section, field, and other names using [static message translations](https://docs.craftcms.com/v3/static-translations.html).
