### ISSUE TITLE
Clients are unable to Resolve licensing issues through the CMS

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#5190]
### Description
Related to my question about [correct procedure to get a client to buy a license on StackExchange](https://craftcms.stackexchange.com/questions/32886/what-is-the-correct-method-for-getting-a-client-to-purchase-a-craft-license), I think this is either a bug or poor UI. If you're not a full site administrator, you still see the warning about licensing issues and are given the option to Resolve them, but even if your user group has all of the permissions available, you get an error when you click Resolve.

Warning shown to clients:
![image](https://user-images.githubusercontent.com/1250017/67949544-90b4c680-fbf0-11e9-8ce8-6f175ea5fec6.png)

Error:
![image](https://user-images.githubusercontent.com/1250017/67949697-da9dac80-fbf0-11e9-974d-9a9b7005d2ea.png)

If there is no permission in Craft that would allow a user to resolve a licensing issue without seeing an error page, the button shouldn't be visible to them.

### Steps to reproduce

1. Give a user group all the permissions available
2. Log in as someone from that user group on an unlicensed site and click "Resolve" in the red bar at the top.

**Comment by brandonkelly** [comment]
Whoops, thanks for pointing that out! Fixed for the next release.

<img width="624" alt="A nag alert that says “You’re running Craft Pro with a Craft Pro license. Please notify one of your site’s admins.”" src="https://user-images.githubusercontent.com/47792/67975516-7f0ff680-fbd1-11e9-87a9-be747b36df02.png">
