### ISSUE TITLE
"Updating search indexes" jobs consistently fail (Integrity constraint violation) when using queue/listen

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#5191]
### Description

We've got a multi-site Craft install running on Laravel Forge, with a Deamon set up to run `queue/listen` (`runQueueAutomatically` is set to `false`).

Since updating to Craft 3.3.14, we're seeing the "Updating search indexes" job consistently fail, with errors like the following logged in the `craft_queue` database table:

```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '6528-field-14-3' for key 'PRIMARY'
The SQL being executed was: INSERT INTO `craft_searchindex` (`elementId`, `attribute`, `fieldId`, `siteId`, `keywords`) VALUES (6528, 'field', 14, 3, ' gettyimages 514938230 ')
```

Only jobs triggered by `queue/listen` seem to fail with this error. Re-running failed jobs from the Control Panel (i.e. by selecting "Try again" on the failed job in the sidebar) works, and jobs executed by manually running `queue/run` also succeed. Additionally, all jobs ran over HTTP (we tried setting `runQueueAutomatically` to `true` after stopping the `queue/listen` process) also succeed.

I'm not able to reproduce this issue locally (Valet) – not sure how to debug this further or fix; any pointers would be very welcome.

### Steps to reproduce

1. 
2.

### Additional info

- Craft version: 3.3.14
- PHP version: 7.2.24-0ubuntu0.18.04.1
- Database driver & version: MySQL 5.5.5-10.3.18-MariaDB
- Plugins & versions:

**Comment by mmikkel** [comment]
Update: I downgraded Craft to 3.3.13, and the "Updating search indexes" jobs no longer fail (before downgrading, I also cleared out the queue and rebooted the droplet, which didn't help).

**Comment by brandonkelly** [comment]
Can you try updating to c67e5c6635184e1feea5e5c5b7dc72a846499964 and see if that helps?

```json
"require": {
  "craftcms/cms": "dev-develop#c67e5c6635184e1feea5e5c5b7dc72a846499964",
  "...": "..."
}
```

**Comment by mmikkel** [comment]
@brandonkelly [`c67e5c6`](https://github.com/craftcms/cms/commit/c67e5c6635184e1feea5e5c5b7dc72a846499964) seems to fix the issue! I generated a bunch of "Updating search indexes" jobs w/ `queue/listen` running, and none of them failed. Thanks for the quick fix :)

**Comment by brandonkelly** [comment]
Awesome! Thanks for checking.
