### ISSUE TITLE
Datetime helper error after updating from PHP 7.1 to 7.2+

### ISSUE THREAD

**Issue by MerzonXS** [craftcms/cms#5193]
### Description
Updated PHP version from 7.1 to 7.3 because service host is requesting the update.  Main page won't load after the update with an Internal server error.  Seems to be an issue with isvalidIntervalString in the datetime helper, and I suspect it might have to do with changes made to datetime intervals between 7.1 and 7.2+, but I'm really not sure.
[web.log](https://github.com/craftcms/cms/files/3795687/web.log)

### Steps to reproduce

1. Currently running 7.1 and site is working
2. Update PHP version to 7.2, and site now displays with Internal Server Error

### Additional info

- Craft version: 3.3.14
- PHP version: 7.2.23 (previous working version was 7.1)
- Database driver & version: MySQL 5.7.19
- Plugins & versions:  Amazon S3-1.2.5, Empty Coalesce-1.0.6, Redactor-2.4.0, Redirect plugin for Craft 3-1.0.23, Super Table-2.3.0

**Comment by brandonkelly** [comment]
Thanks for reporting! Just fixed this for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#1bdc131febf2f1fa6f8c6a84e9c4170201763e39",
  "...": "..."
}
```

Then run `composer update`.

**Comment by MerzonXS** [comment]
I tried modifying craftcms/cms in composer.json as you directed, but I just generate dependency errors for verbb/super-table.  I added a replace statement in composer.json to ignore the requirement for craftcms/cms 3.3.1.1 and now it's telling me that the craftcms version is being parsed to 1.0.0...am I doing something wrong, or is there something wrong with using the version "dev-develop#1bdc131febf2f1fa6f8c6a84e9c4170201763e39"?

**Comment by brandonkelly** [comment]
Sorry, try adding `as 3.3.14` to the end of the requirement string. (Example above has been updated with that.)

**Comment by jonathankvitky** [comment]
That worked perfectly.  Thanks!
