### ISSUE TITLE
Multi-site, localized entry version Live Preview loading insecure resource

### ISSUE THREAD

**Issue by kblizeck** [craftcms/cms#5197]
### Description
Two Sites setup - one English and one Japanese
The English version of Live Preview works find, the Japanese version shows a blank scree with the following insecure resource error:

```
Mixed Content: The page at 'https://dev.mysite.com/admin/entries/home/3-home?site=japanese&draftId=90' was loaded over HTTPS, but requested an insecure resource 'http://dev.mysite.com/jp?x-craft-live-preview=HiujTBdpRG&token=_Yk5iPmlyBS07Wh5-N82pc3LpXoYP0rw'. This request has been blocked; the content must be served over HTTPS.
```

![Screen Shot 2019-11-01 at 9 18 22 AM](https://user-images.githubusercontent.com/9886123/68035106-94942780-fc88-11e9-82f2-f58d724cf18a.png)

Environment Variables: 
`$DEFAULT_SITE_URL` : `https://dev.mysite.com`
`$DEFAULT_JP_SITE_URL` : `https://dev.mysite.com/jp`

`general.php` settings:
```
return [
    // Global settings
    '*' => [
        'siteName' => 'My Site',
        'allowAdminChanges' => false,
        'devMode' => false,
        'cacheDuration' => 7200,                // Set the default cache expiration for 2 hours. Can be removed once cacheElementQueries is resolved
        'cacheElementQueries' => false,         // Craft 3.x serializes caches and can insert *massive* chunks of data. Disable this for now until Craft supports a new mechanism
        'cpTrigger' => 'admin',
        'enableCsrfProtection' => true,
        'imagesUrl' => '/images/',
        'maxInvalidLogins' => 3,
        'omitScriptNameInUrls' => true,
        'preventUserEnumeration' => true,
        'requireMatchingUserAgentForSession' => false, // Don't require matching user-agents to stay logged in
        'securityKey' => getenv('SECURITY_KEY'),
        'timezone' => 'America/Indiana/Indianapolis',
        'useProjectConfigFile' => true,
        'userSessionDuration' => 'P1W',

    ],
    // Dev environment settings
    'local' => [
        'allowAdminChanges' => true,
        'devMode' => true,
        'enableCaching' => false
    ],
    // Staging environment settings
    'staging' => [
      'siteUrl' => 'https://dev.mysite.com'
    ],
    // Production environment settings
    'production' => [
        'generateTransformsBeforePageLoad' => true,
        'siteUrl' => 'https://mysite.com'
    ],
];
```

### Steps to reproduce

1. Go to any entry within the site
2. Choose Japanese site from dropdown
3. Choose Live Preview
4. Blank screen shown, with console error

### Additional info

- Craft version: 3.3.12
- PHP version: 7.2.19
- Database driver & version: MySQL 5.7.27
- Plugins & versions: 
![Screen Shot 2019-11-01 at 9 21 18 AM](https://user-images.githubusercontent.com/9886123/68035316-feaccc80-fc88-11e9-9789-7d1b2bd4e500.png)

**Comment by brandonkelly** [comment]
Try inspecting the `<iframe>` when this error occurs. What is its `src` attribute set to?

**Comment by kblizeck** [comment]
@brandonkelly It is set to `https://dev.mysite.com/jp/?x-craft-live-preview=CFqkITbWwX&token=uj0jol9AGuPWqwbOsmhRzBCeCEUl6est`

**Comment by brandonkelly** [comment]
OK, so everything is in fact set correctly as far as your config settings go. There must be some `https` => `http` redirect going on when the page is actually requested.

If you go to https://dev.mysite.com/jp/?x-craft-live-preview=CFqkITbWwX&token=uj0jol9AGuPWqwbOsmhRzBCeCEUl6est directly, does it redirect to `http`?

**Comment by kblizeck** [comment]
@brandonkelly Nope! It correctly loads the page.

**Comment by brandonkelly** [comment]
Huh, weird. Is this happening on a public server that we can check it out on? If so can you send admin & ssh credentials over to support@craftcms.com?

**Comment by kblizeck** [comment]
@brandonkelly Email sent! I appreciate the assist here - I have a feeling it's something on my end... but I can't find it!!

**Comment by kblizeck** [comment]
@brandonkelly is the bomb, and found the issue within my `.htaccess` file - 

Removing these lines did the trick!

```
# Remove trailing slashes
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} (.+)/$
RewriteRule ^ %1 [R=301,L]
```

**Comment by danielsetreus** [comment]
I have the exact same issue - but not using apache, so there is no `.htaccess` file. Running on nginx.

Could you please explain what it is about the trailing slash that breaks the preview?

**Comment by brandonkelly** [comment]
@danielsetreus if you write into support@craftcms.com we can help you out from there.
