### ISSUE TITLE
GraphQL: Can't view groupId on Category query

### ISSUE THREAD

**Issue by daltonrooney** [craftcms/cms#5199]
### Description
When I try to query categories and include the groupId, I get an error response.

Example query:

```
{
  categories {
    groupId
  }
}
```

Response: 

```
 {
      "debugMessage": "Getting unknown property: craft\\elements\\Category::groupIdp",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "categories",
        0,
        "groupId"
      ]
    },
```
This seems like it might be a typo in https://github.com/craftcms/cms/blob/6f29339a039c574a5a8aeccf010312eb7806f79e/src/gql/types/elements/Category.php#L47

and also 

https://github.com/craftcms/cms/blob/6f29339a039c574a5a8aeccf010312eb7806f79e/src/gql/types/elements/Tag.php#L47

**Comment by andris-sevcenko** [comment]
That's just embarrassing.

**Comment by andris-sevcenko** [comment]
Thank you! This has been fixed for the next release!

**Comment by gtettelaar** [comment]
Happens to the best of us! @andris-sevcenko
