### ISSUE TITLE
GraphQL: queries now not respecting [Int] for id(s)

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#5205]
### Description
Did we get a regression here? Suddenly both 3.3.14 and dev-develop give query error when array Int arguments are defined for Entry(Element) id, whether used or not.

### Steps to reproduce

1. Have an Entries query which has previously worked with a query arg of [Int] for id, form:
```
query someQuery ($id: [Int]) {
    entries (id: $id, ...) { ...
```

2. run the query, whether or not defining "id" in the query args (either should work, and has)
3. query will fail, with:
```
"errors": [
    {
      "message": "Variable \"$id\" of type \"[Int]\" used in position expecting type \"[QueryParameter]\".",
      "category": "graphql",
      "locations": [
        {
          "line": 1,
          "column": 21
        },
        {
          "line": 3,
          "column": 63
        }
      ]
    }
  ]
}
```

### Additional info

- Craft version: 3.3.14  or dev-develop #b045a1d

**Comment by andris-sevcenko** [comment]
Ah, that's an unfortunate side-effect of switching the queries up to expect `[QueryArgument]` instead of `[Int]`.

I failed to pick this up because just using values of integers and/or strings works nicely - it just slipped my mind to test whether variables would be backward compatible with this change, too. Also, an indicator where functional tests are lacking.

Anyhow, the solution here is just to switch up the `[Int]` to `[QueryArgument]` for the affected arguments. (https://github.com/craftcms/cms/blob/develop/CHANGELOG-v3.md#3314---2019-10-30, Changed section, wherever "not" is mentioned)

Sorry for the trouble!

**Comment by narration-sd** [comment]
Uh, I think you mean `[QueryParameter]`?

According to the Schema I get, anyway...

**Comment by andris-sevcenko** [comment]
> Uh, I think you mean [QueryParameter]?

`[QueryParameter]` yeah.

> And this system is documented where?

Not explicitly documented yet, rather than inferred from how [element queries work](https://docs.craftcms.com/v3/dev/element-queries/entry-queries.html#parameters). As I said, it didn't cross my mind to check passed variables, as just switching from `[1, 2, 3]` to `['not', 4, 5]` worked just fine in the queries themselves

You were part of the discussion on the original issue (#5161), though, so you're probably familiar with the syntax already.

**Comment by narration-sd** [comment]
Well, Hal will be...

**Comment by andris-sevcenko** [comment]
@narration-sd a heads up - in 3.4 I'll be changing this to QueryArgument.

Unfortunately, I messed up by naming the class one thing and the actual type a [different thing](https://github.com/craftcms/cms/blob/develop/src/gql/types/QueryArgument.php#L27), and, as I've verified, no amount of banging the head against the wall will fix that.

So, I've done my [research about the semantics and nomenclature](https://stackoverflow.com/a/156787) of Argument and Parameter and I've come to the conclusion that the type should be referenced to as `QueryArgument`.

Sorry for the inconvenience :(

**Comment by narration-sd** [comment]
@andris-sevcenko  Good man -- appreciation for the heads up. After the Brandon summer, I'm well practiced in version-compare code diverts.

Good point about the semantics, in truth. As a mostly-words person, meanings in softwareland are often a minefield. Not either a lover of strictness, but when concepts are clear, it's a boon. So good job, once again, and in influencing the trains to run on time ( extra :) if you get that! )  -- C.

**Comment by narration-sd** [comment]
@andris-sevcenko  Andris, in reflection, I think what I'm going to do is release Live Vue with Craft 3.4's apparent schedule, If it's delayed, LV will be mainly for new projects anyway, and persons can just use the Composer sleight-of-versions to get a reasonable facsimile.

This will give more time for your settling-in, and less tracking for me, as well as open proper space for other projects which have been waiting. It seems to fit otherwise, as Brandon's been putting many, many of his eggs into 3.4, past the mutational Brandon-summer. 

Releases me from ways I was considering for your jump, since it even involves documentation how-tos, or massaging tags to what they should be automatically behind scene vs. reporting everything.

**Comment by narration-sd** [comment]
Yust outer curiosity, wonder when you plan this?

No rush truly, but like to have my validations/HalSmarts accurate on tracked 3.4, thanks.

**Comment by andris-sevcenko** [comment]
@narration-sd as far as I can tell, 3.4 is on track for release before Christmas.

**Comment by narration-sd** [comment]
Andris, wasn't trying to rush 3.4 release -- just wanted to get an idea when you were going to put this particular mod into the 3.4.x-dev (QueryParameter => QueryArgument), so could plan a time to integrate it.

It did occur to me earlier this morning that maybe you were holding off due to brainstorm about reverting the whole thing to normative GraphQL (specifying actual tyope, like [Int], with such a type accepting either single Ints or and array of Int. Not sure why different at present, though no doubt you have a raison. Or two...

Best,
Clive

**Comment by andris-sevcenko** [comment]
@narration-sd Ah, I misunderstood, oops.

That change is already pushed to the `feature/graphql-project-config` branch which will probably be finalized (one last migration change to tackle) and merged this week into the `3.4` branch.

> reverting the whole thing to normative GraphQL (specifying actual type, like [Int], with such a type accepting either single Ints or an array of Int

If I do that, then using the `['not', 3, 4]` syntax won't be possible for arguments. I feel like not using built-int GraphQL types is the better call here, as it further pushes Craft's GraphQL flexibility toward what's possible with element queries.

**Comment by narration-sd** [comment]
Ah, that's where it is -- the one place I didn't look, tracking other mass-repo changes/merges. Sharper eyes for such next time.

I see what you mean on the functionality, I think. How this was worked in CraftQL (others??) was to provide an idNot = [ 3, 4 ] syntax. Given Craft has a few things going on besides ids, could be you've got a better approach, yes. 

I would certainly not be one to award prizes to the GraphQL team for their intensely narrow gates on many things...you may imagine :)

**Comment by narration-sd** [comment]
@andris-sevcenko I can't find via Finds somehow where you did this, but you have altered requirement of QueryParameter to be gql_QueryParameter. Probably a good candidate commit area would be [here](https://github.com/craftcms/cms/commit/05c9a5b2d594926aed97fcd44484d08bc6fd317d#diff-883ab9fdce37702ea74a2696a4670ce8).

Could you please just go to QueryArgument, as it will need to be?

I had to track down that this little number conflicted with auto-removal of Gridsome/Gatsby federation-capability prefixing, after remedying all the other things you changed about connecting token names, ids, and schemas.

The second part, ok, I recomposed, hopefully for the last time, and I do understand why you did this to other purposes. 

Just would point out that you _still_ don't have api for getting a schema from the most obvious  thing for code _outside_ your internals, which is from token **name**. Thus the helpers recompose, but.

On the primary thing, the little gql_ or anything else_, this is really a pain. It's not precisely solvable, regexes or patchups, unless I go and change all my Live Vue, Gatsby, and Gridsome projects' configs.
 
And then, of course, I would have to do it all again.

Could we _please_ just have QueryArgument, and be done with this?

I thank you; my schedule thanks you; my bp thanks you; others may...
Cheers, C.

**Comment by narration-sd** [comment]
...and, actually, of course a fixup could be made - regex can do anything, given two minutes thought and regex101.com.

But then, I am got hit that the schema doesn't apparently like gql_QueryParameter (where indeed does the error suggesting that's what you should use come from?

Point A:  This is now the important question/problem to be fixed. Because...

- I looked and found that of the TypeLoader::types available to be accepted...QueryArgument was there.
- I put _that_, au finalement, into my yaml config, and...Voilà, Live Vue is back to working once again. 

I will not complain if you remedy by completing Point A.

Corallaries:
- If I want to come up with a way to do something, it always works immediately after having said it can’t be done
- If I want clarity to come in Craftiness, I have only to write a good socking Issue, and then shortly will similarly arise a new way which after all can resolve the problem.

Isn't software in the 2010s fun??

**Comment by andris-sevcenko** [comment]
>  can't find via Finds somehow where you did this, but you have altered requirement of QueryParameter to be gql_QueryParameter. Probably a good candidate commit area would be here.
Could we please just go to QueryArgument, as it will need to be?

I'm not sure what are you talking about? On the 3.4 branch it's QueryArgument and [has been for 16 days.](https://github.com/craftcms/cms/blame/3.4/src/gql/types/QueryArgument.php#L27)

> Just would point out that you still don't have api for getting a schema from the most obvious thing for code outside your internals, which is from token name. Thus the helpers recompose, but.

Huh. Why would you use the token name, not the actual access token?

> Isn't software in the 2010s fun??

Feels like playing catch-up and losing all the time. But super-fun :)

**Comment by narration-sd** [comment]
Well, apology to have bothered you, definite false report here. I woke up with the off-line portion of noodle having processed this thing, which persona found it just a little too convenient that the error message your Gql _seemed_ to provide contained 'gql_' -- and that I couldn't find this in code, a highlight.  Of course this looked as if it might have been legitimate, which is how I got led down a trail.

A few minutes with the code again this morning, before arriving at your comment here, showed:
- indeed you simply transitioned to QueryArgument. Which is what I wanted. I'd been away from this code a time, thus hadn't picked up on this upgrade.
- this false 'gql_QueryParameter' in the error message has to be a bad edit on the config file that holds the (copied from Gridsome etc.) query, so that I actually had gql_QueryParameter in the text there. This can happen when typing with wrong pane focus in JetBrains, I would be confident you have likely noticed.
- reverting adjustments, and assuring `[QueryParameter]` was the sub for `[Int]` acted just as it should today, your message simply naming the item, and setting it to `[QueryArgument]` proceeds to acting properly.

Conclusion: all is fine with your fresh code, Hal will soon learn to make just the revised proper suggestions for it. This was a real tempest in a teapot. What I get from looking away. But that is how I've found this aspect of life fit properly with others (and 2010s code...) to work far the best. So.

> Why would you use the token name, not the actual access token?

Because it's a lot cleaner and less error prone for persons to put the name in a yaml config for Live Vue, rather than a quite lengthly hex string. If I remember the other brand is quite longer than yours, so that started it.  Anyway, I've coded to what you revised to. Others though might think as I did, so you can decide if a nice interface for it is reckonable -- if appears, I will use it.

Cheers, Andris, and would let you know I had a swift vision of you shaking your head, so smiling here for your answer in good character  :)

**Comment by andris-sevcenko** [comment]
I mean, I can add the fetching the token by a name, too. It's literally just a few lines and no harm in having them. Let me add that to the 3.4 list I have here.

**Comment by narration-sd** [comment]
Good man. I didn't like digging in your arrays that might change, so this will be happy for sure. Will watch the comics for its item...

**Comment by narration-sd** [comment]
Ah, this saga continues a bit further -- and I think now I wasn't mistaken, except as to the source.

What's going is in Gridsome, on the surface and that's why I couldn't find it,  but let's see.

It's not understanding `QueryArgument` as a `Type`.  It  suggests I might mean `gql_QueryArgument`, and indeed that brings back everything to working. I might have given in to this in a moment of weakness a while ago, editing to` [gql_]QueryParameter`, explaining how that prefix got into the queries originally.

Thinking about this, it may be proper, just an unexpected consequence of the federation-preparing prefixing going on now in Gridsome as well as Gatsby. `gql_` is indeed the `typeName` prefix I've been configuring for the Gridsome GraphQL interface, and `QueryArgument` is by your reckoned intent a Type.

So. Not your fault or mine, but one more thing for Hal to get clever about. 

I don’t think this project would ever have been possible without Hal — and that’s a design trope that does intrigue me, extent of history that I have with it especially. Interesting. Maybe even someday Brandon will think so :)

**Comment by narration-sd** [comment]
@andris-sevcenko , in add to the final resolve above, a quick suggestion for your message. Given your excellence in English, what you have just looks like an oversight during rewording -- I make these often enough myself.

There are several ways to remedy, given the possible situations, but I think the most direct is just to replace the word 'both' with 'either' -- important for no trip-up in understanding, but not enough to need an issue, so mentioned here. Could have a comma, your choice...

![broken-queryarg](https://user-images.githubusercontent.com/247945/70367643-a7d17e80-1856-11ea-99d6-568bf32b7851.png)

**Comment by narration-sd** [comment]
Another note, @andris-sevcenko Andris. I've just started to look into this area for documentation, and I think what Gridsome and Gatsby are doing with their typeName and fieldName extensions is not actually federation as Apollo names it, though to some extent it accomplishes in that direction.

What these extensions do, as I once noted to you, is extend the step-by-step type naming you've settled on, so I think you'll need such documentation for Craft Gql also. Once I have something, which is a bit on a back burner, will see if we might be able to share.  Busy now on other...

**Comment by narration-sd** [comment]
Andris @andris-sevcenko , nota nota further -- foolishly read an hour too late at night into now-deprecated schema stitching, and new cool schema fraternising, or was that federation, yes...and then trying a few things this morning.

Interim conclusion: what Gatsby did is not either, though it was/is built on stitching. Gridsome borrowed the form. I'm not sure either of them intend to implement anything like ability to use keys from one schema to query another, but so far have determined you can at least have two schemas providing output values in one Gridsome query, via differing typeName/fieldName pairs.

Not sure it's worth digging farther at present, so figuring how to word about this at present point of knowledge. You have been informed.

**Comment by narration-sd** [comment]
addenda:  usual 'can't do' thought led to another experiment, and there I find I don't think they have any semantics for capturing a value  from one part of dual query to be a variable to constrain another. 

Thus conclusion is that this typeName/fieldName thing is just a very poor man's federation, and thus not at present anyway an attempt to prepare for the real thing. In Gatsby/Gridsome land applications at present, probably not a big need. I'm guessing they'd have to create something like the pseudo-directive form of real federations to actually accomplish such, and don't anticipate it at least for a time. So now documentable words are ideating of a better order.

**Comment by narration-sd** [comment]
Ok, @andris-sevcenko ,  knowing how busy you are attending to other matters, I'll email you the zip of the resulting Markdown/VuePress doco (also here), with a place to view it on the web.  I think it should take one load off, from the writeups you're also providing.

I feel it's at least close, having had a writing and then an edit, and being intent on using it myself. Thus truly endeth this task.

[graphql-with-gatsby-gridsome.zip](https://github.com/craftcms/cms/files/3958644/graphql-with-gatsby-gridsome.zip)

**Comment by narration-sd** [comment]
[small page typo correction in refreshed zip]

**Comment by narration-sd** [comment]
A second-look re-edit of the article in Markdown, clearer, also enabling code highlighting when that's part of your VuePress config, so styles/index.styl is included in the fresh zip this time, to be put in .vuepress if you don't have this already in your theme, or to over-ride if you like the scheme.

[graphql-with-gatsby-gridsome.zip](https://github.com/craftcms/cms/files/3964637/graphql-with-gatsby-gridsome.zip)
