### ISSUE TITLE
Code Vulnerable to Cross Site Scripting

### ISSUE THREAD

**Issue by fsyclospe** [craftcms/cms#5206]
### Description
There is a function in the application code "Response.php" which is vulnerable to Cross Site scripting.
Path: /craftcms/src/web/Response.php

### Vulnerable Code

197: list($handle, $begin, $end) = $this->stream;  // list()
199: $pos = ftell($handle)) <= 
201: $chunkSize = $end - $pos + 1;  // if($pos + $chunkSize > $end),
194: $chunkSize = 8 * 1024 * 1024; 
203: echo echo fread($handle, $chunkSize); 
requires:
196: if(is_array($this->stream))
185: ⇓ function sendcontent()

### Additional info

Userinput reaches sensitive sink when function sendcontent() is called. 

- Craft version: 3.3.14

![image](https://user-images.githubusercontent.com/57394236/68200752-80348f80-ffe6-11e9-9230-77d0c3bb7f9c.png)

**Comment by brandonkelly** [comment]
Please send security disclosures from https://craftcms.com/contact, per our [contribution guidelines](https://github.com/craftcms/cms/blob/develop/CONTRIBUTING.md#security-disclosures).
