### ISSUE TITLE
Possible vulnerability: Debug toolbar visible for visitors with devMode disabled

### ISSUE THREAD

**Issue by rbrv** [craftcms/cms#5207]
### Description
In Craft 2, disabling devMode on production ensured the debug toolbar was hidden.  
In Craft 3, this is no longer true. By design, showing/hiding the debug toolbar is moved to user preferences, ignoring the devMode setting.    
**This creates a possible vulnerability when (fastcgi) caching is enabled.**

### Steps to reproduce 

1. Log in to CP on production (devMode=false) with a user that has the toolbar enabled
1. Visit a page on the frontend, showing the toolbar
1. This page output is cached
1. Visit the same page in an incognito window
1. Debug toolbar is shown for every visitor

### Additional info
- Craft version: 3.x

**Comment by brandonkelly** [comment]
Please send security disclosures from https://craftcms.com/contact, per our [contribution guidelines](https://github.com/craftcms/cms/blob/develop/CONTRIBUTING.md#security-disclosures).
