### ISSUE TITLE
Expired password token should not redirect in headless mode

### ISSUE THREAD

**Issue by nicgordon** [craftcms/cms#5210]
### Description
I believe that [this function](https://github.com/craftcms/cms/blob/3.3.15/src/controllers/UsersController.php#L1928-L1945) should be checking for `Craft::$app->getRequest()->getAcceptsJson()` and returning a json error rather than a redirect if the request does indeed accept json.

I just thought I'd make an issue just in case I'm incorrect and always returning a redirect is in fact intended behaviour.

### Steps to reproduce

1. Run craft in headless mode
2. Make a POST request to `users/set-password` with an invalid token
3. Expect a json error, but instead receive a 302.

### Additional info

- Craft version: 3.3.14
- PHP version: 7.3.10
- Database driver & version: mysql 5.0.12

**Comment by howells** [comment]
Just wanted to bump this - I'm having a nightmare trying to handle a 302 redirect when try to set a password in headless mode.

**Comment by brandonkelly** [comment]
Sorry, this issue slipped through the cracks. I’ve just fixed this, but since it is a bit of a change in behavior, I made the change for Craft 3.5.
