### ISSUE TITLE
[RFC] Include user role in the export

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#5211]
### Description
You can export the users since 3.2 I believe, which is great for Audit purposes. Would it be possible to add a column to the export with the roles?

**Comment by brandonkelly** [comment]
We will be making a few improvements to element exporting in Craft 3.4, so I’ll add this to the list.

**Comment by brandonkelly** [comment]
As of Craft 3.4 it will be possible to register custom element export types, so you can include whatever data you want in those. (See https://github.com/craftcms/cms/issues/5090#issuecomment-563729576.)
