### ISSUE TITLE
Matrix field gets emptied on saving in preview mode

### ISSUE THREAD

**Issue by diluno** [craftcms/cms#5217]
### Description
When I press Cmd+S in live preview mode, an entire matrix field just loses all its content.
Screen capture: https://drive.google.com/open?id=1iUdYkfkAElp44HlLE0uMRptcyOIDBuba

### Steps to reproduce

1. Create matrix field in a section (in a second tab)
2. Open Live Preview
3. Press Cmd+S
4. Content disappears

### Additional info

- Craft version: 3.4.x-dev (d10c55d)
- PHP version: 7.1.32
- Database driver & version: MySQL 5.7.27
- Plugins & versions:
DigitalOcean Spaces Volume 1.1.2
Element API 2.6.0
Redactor 2.4.0
Super Table 2.3.0

**Comment by brandonkelly** [comment]
Yikes, I can reproduce. Will get that fixed!

**Comment by brandonkelly** [comment]
Alright just fixed this on the 3.4 branch. In `composer.json`, if you have a specific commit hash in your `craftcms/cms` requirement, go ahead and remove that, so it looks like this:

```json
"require": {
  "craftcms/cms": "3.4.x-dev",
  "...": "..."
}
```

Then run `composer update`.

**Comment by diluno** [comment]
My matrix fields are now being saved, but the asset fields within them aren't. Can you reproduce this?

**Comment by diluno** [comment]
When I save an entry in live preview, it removes all chosen assets. If i then choose new assets and save again, it removes all matrix blocks.
I know it's my fault for upgrading to 3.4.x-dev, but I hope you can fix this soon 🙈
Thank you!

**Comment by Mosnar** [comment]
@diluno Have you tried clearing your CP cache? In my test environment, I've been seeing stuff like this until I do that and then it seems to work.

**Comment by diluno** [comment]
@Mosnar This didn't help, unfortunately.

**Comment by brandonkelly** [comment]
Fixed a couple more bugs with relation field saving (7a69656834f0efd9e45892306774c8b58d1f48b6). Should be all good now.
