### ISSUE TITLE
GraphQl explorer height issue

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#5219]
### Description
On browser windows narrower than 975px, the GraphQL explorer page at `/admin/graphql` gets really low and unusable. Testing in Chrome, Firefox & Safari.

<img width="1027" alt="Screenshot 2019-11-07 at 20 28 32" src="https://user-images.githubusercontent.com/755428/68420704-2de99f00-019d-11ea-8ad0-fa000e9ae18f.png">

### Additional info

- Craft version: 3.3.15

**Comment by brandonkelly** [comment]
Yikes, thanks for pointing that out! Just fixed for the next release.
