### ISSUE TITLE
Unknown error in CP when user has no permission to create asset folder

### ISSUE THREAD

**Issue by craftedsystems** [craftcms/cms#5223]
### Description

When a user tries to create an asset folder and does not have permission to do so, Craft fails and displays the message "An unknown error occurred.". As visible in the browser network log,

Craft knows the cause and should tell the user what failed.

### Steps to reproduce

1. Create a user group that is not allowed to create asset folders ("Create subfolders")
2. Try to create an asset folder with a user of this user group

### Additional info

- Craft version: 3.3.15
- PHP version: 7.3.11
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

![Screenshot-2019-11-08-at-17 06 24](https://user-images.githubusercontent.com/26137287/68491400-149f2c00-024b-11ea-91dc-86c38dd14645.png)

**Comment by andris-sevcenko** [comment]
Thanks for spotting that! just fixed it for the next relase!
