### ISSUE TITLE
Allow entry versions to be limited

### ISSUE THREAD

**Issue by ryanpcmcquen** [craftcms/cms#5224]
### Description

Allow entry versions to be limited to a specific number. We have some entries with 100s of versions and this has a _significant_ impact on site performance, especially searching, which takes 30 seconds or more on some types.

Deleting old entry versions has an insane impact on entry searches (making it 30 or more times faster).

It'd be great if Craft allowed a limitation (maybe the last 10 versions, or some arbitrary number), rather than either having versioning, or not having versioning.

### Steps to reproduce

1. Have over 100 versions of an entry.
2. Search for that entry under its type.

### Additional info

- Craft version: 3.1.x
- PHP version: 7.2.x

**Comment by brandonkelly** [comment]
We added the [maxRevisions](https://docs.craftcms.com/v3/config/config-settings.html#maxrevisions) config setting in Craft 3.2, which gets enforced each time a new revision is created. (We’ll also be adding a CLI command in Craft 3.4 to prune out extra revisions across the board if `maxRevisions` is ever decreased – #4851.)
