### ISSUE TITLE
URL Helper appears to be corrupting query string parameters

### ISSUE THREAD

**Issue by benjaminkohl** [craftcms/cms#5233]
### Description

I'm having problems with the URL helper (the Twig version) when I am passing it a query string parameter that uses numeric indexes followed by other data. I believe it was working fine until sometime recently (though I can't pinpoint when) so I figured something must have changed with how the URLs are being generated.

The query string parameters in question correspond to field names like the following:

```
filters[0][fieldHandle]
filters[0][filterType]
filters[0][filterValue]
filters[1][fieldHandle]
filters[1][filterType]
filters[1][filterValue]
```

The initial URL is formed as a result of a form submission. If I output the resulting "filters" param in the template using dd(), it looks exactly as I would expect and the page works as expected.

```
{% dd(filtersParam) %}

[
    0 => [
        'fieldHandle' => 'articleLead'
        'filterType' => 'is empty'
        'value' => ''
    ]
    ...
]
```

The trouble begins when we plug in that same filters parameter value back into the Twig url helper to generate "next/previous page" URLs like so:

```
<a href="{{ url('filters/entries', {
	'entryTypeId' : entryTypeId,
	'filters' : filtersParam,
	'limit' : limit,
	'offset' : offset-limit }) }}" class="btn" >&larr; Previous Page</a>
```

Now we get Twig errors because the resulting array is not arranged how it was before. The generated query string on the otherwise correct URL and resulting filtersParam array now look like:

```
?entryTypeId=55&filters[][fieldHandle]=articleLead&filters[][filterType]=is+empty&filters[][value]=&limit=50&offset=50

[
    0 => [
        'fieldHandle' => 'articleLead'
    ]
    1 => [
        'filterType' => 'is empty'
    ]
    2 => [
        'value' => ''
    ]
]
```

So it appears the "0" is going missing. I'm wondering if maybe it has something to do with [this commit](https://github.com/craftcms/cms/commit/a4daaeb56dd61044f9f4f1a638ad98613f6d3f4c#diff-8761a7cd35e729b6fadc9ebfa1200391) but I didn't dig very deep so that is just speculation.

### Additional info

- Craft version: 3.3.15
- PHP version: 7.1.32
- Database driver & version: MySQL 5.6.42
- Plugins & versions:

Amazon S3	1.2.5
Blitz	2.3.4
Button Box	2.0.4
Cache Flag	1.0.3
CP Field Inspect	1.0.7
Feed Me	4.1.2
Freeform	3.5.3
Hvrcraft	3.0.0-beta.4
Imager	v2.3.0
Inventory	2.0.3
Linkit	1.1.11
Link Vault	3.0.5.4
Many to Many Field Type	1.0.2.2
Maps	3.7.1
Position Fieldtype	1.0.14
Redactor	2.4.0
Relabel	1.3.4
Relations	1.2.1
Retcon	2.0.12
Retour	3.1.27
SEOmatic	3.2.32
Sidebar Entry Types	1.0.3
Spoon	3.3.7
Super Table	2.3.0
Typogrify	1.1.18

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#1aa8f2a732aa52159c44519527eda4d43fdcdb5d as 3.3.15",
  "...": "..."
}
```

Then run `composer update`.
