### ISSUE TITLE
Entries fieldtype modal doesn't work well on mobile

### ISSUE THREAD

**Issue by ciceronepress** [craftcms/cms#5234]
### Description

When editing an entry on a mobile device, selecting a related entry doesn't work well on a small screen. The left column is too wide and pushes the list of entries off the screen. Screen shot from a Note 10+ and iPhone SE.

![PNG image 2019-11-14 11_47_32](https://user-images.githubusercontent.com/49522128/68855105-73462900-06d5-11ea-90db-09336c64dcf3.jpg)

![Screenshot_20191114-113631_Chrome](https://user-images.githubusercontent.com/49522128/68855116-79d4a080-06d5-11ea-8cfb-ee37338b8be1.jpg)

**Propose 2 options:**
1. If there is only a single Source to choose from for a field, then don't show the left column on any screen width - it's not really necessary.

2. For mobile, if there is more than 1 source, use the same drop-down option as on the Entries list, where it collapses to the top of the listing.

I'm working on a project that will require people to update entries remotely so this will become an issue for them.

### Steps to reproduce

1. Edit any Entry with an Entries fieldtype

### Additional info

- Craft version: 3.3.12

**Comment by brandonkelly** [comment]
The root issue here is already covered by #3781, so will close this as a duplicate.
