### ISSUE TITLE
Exclude assets from Git

### ISSUE THREAD

**Issue by frank-laemmer** [craftcms/cms#5237]
### Description

Local asset volumes are by default not ignored from Git. I hope a better default, matching more common use cases, to make sure that file uploads from local dev don't show up in Git would make sense. Proposing this as a small **feature**.

### Why bother?

**It complicates deployment.** From my understanding it will not play nice with most Git deployment workflows. Shameless plug: I am co-founder of fortrabbit. This behavior certainly doesn't work well with our platform ;)

I think, a common pattern here is that you have a local development environment and some server out there. Code is deployed with Git. Now when local volumes are included with Git as they are at the moment, images you might have "uploaded" locally during development are going to deployed as well. That first might will feel good. But what if another image gets uploaded on the remote server directly? That file will not be part of Git any more and you start getting out of sync. 

We recommend to separate: Code (and config) gets deployed with Git; Dependencies are managed by Composer along the way; Content files are getting rsynced; MySQL get's dumped. We have developed the [Craft Copy](https://github.com/fortrabbit/craft-copy) plugin to make this easy for our clients. 

So far we provided a custom, opinionated `.gitignore` file. It assumes that assets are stored in a folder named `assets`, which is a common practice, but can not be guaranteed.

**Git is not designed for images.** Last not least, as far as I understand, Git is best to track text files. Images, especially pixel images, are binary data which not be diffed and that will increase Git size.

### Steps to reproduce

1. Create a new local storage volume locally
2. Add images to the volume by uploading locally
3. Check `git status` > images are showing up as changes

### Ideas

I propose to have the files in question ignored from Git by `.gitignore`. I can imagine that this might be done on two levels (choose one):

#### Rules in the root `.gitignore`

Craft CMS could exclude all files from the `web` folder, expect the ones that should belong there. That can be done in the core `.gitignore` file on root level. Andrew Welch does something similar in his Craft scaffolding project, see [here](https://github.com/nystudio107/craft/blob/craft-webpack/.gitignore#L27). There is an opinionated `assets` folder within `web`, so the rule only applies to that folder.

#### Each local volume get's a `.gitignore`

Craft CMS could add a `.gitignore` file to each new local asset volume that get's created to ignore all files in there. Andrew Welch also does something similar, see [here](https://github.com/nystudio107/craft/blob/craft-webpack/web/assets/.gitignore). Again, in this case, an `assets` folder is present.

### Additional info

Craft version, PHP version, database driver & version and plugins & versions are not required to discuss this.

### Thanks for considering!

Maybe I missed something important? Looking forward for your feedback.

**Comment by brandonkelly** [comment]
Your second suggestion (add a `gitignore` file to the folder itself) is a lot cleaner to implement, so I just added that for Craft 3.4.

**Comment by frank-laemmer** [comment]
Small follow up: In your Create a blog tutorial you mention to create the folders manually (https://craftcms.com/docs/getting-started-tutorial/configure/section.html#create-an-asset-volume), not by GUI. 

In that case it seems a .gitignore will not be created.

Related: https://github.com/craftcms/cms/blob/cd07fdb05d12b4594fc8c2ce836b9fa083836ae6/src/volumes/Local.php#L79

Maybe change the tutorial?

**Comment by mattstein** [comment]
Updated @frank-laemmer, thank you! https://github.com/craftcms/docs/commit/7d40c2ecf02b0d74efcbb528751983e628f5145e
