### ISSUE TITLE
Deleting an asset doesn't empty the GraphQL cache

### ISSUE THREAD

**Issue by smcyr** [craftcms/cms#5238]
### Description

Deleting an asset doesn't empty the GraphQL cache. Disabling the cache fix the problem.

### Steps to reproduce

1. Enable Graphql caching
2. Make a Graphql query to fetch assets
3. Delete an asset
4. Re-make the query to fetch the assets
5. The asset is still in the list even if the file doesn't exist anymore

### Additional info

- Craft version: 3.3.15
- PHP version: 7.3
- Database driver & version: MariaDB

**Comment by andris-sevcenko** [comment]
Yikes, sorry about that! Fixed for the next release!

**Comment by sandip192** [comment]
Can I reinstall graphql in craftcms once again.and how to uninstall graphql.

**Comment by andris-sevcenko** [comment]
@sandip192 GraphQL is part of Craft CMS core and cannot be uninstalled. You can enable/disable it, however, using the [enableGql config setting](https://craftcms.com/docs/3.x/config/config-settings.html#enablegql).
