### ISSUE TITLE
Craft appears to be joining structure data on channels during element query

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#5239]
### Description
It appears that even though I'm querying a channel rather than a structure, the structure data is still included in the element query as an additional join. Overhead aside, this is causing some trouble for me as I'm developing a module to allow me to sort by the number of relations from a particular field on the element. The trouble is that because this data is joined, as of MySQL 5.7 (I think), I would need to include this is in my `GROUP BY` statement; however, all of the values are null.

Here's an example of me running the following query on a simple channel called "Blog":

`entry in craft.entries.section('blog').orderBy('title').all()`

![image](https://user-images.githubusercontent.com/3810939/68964546-9e994880-07a7-11ea-9b2d-729d7e98292a.png)

Here's the actual query:
```sql
SELECT `elements`.`id`,
       `elements`.`fieldLayoutId`,
       `elements`.`uid`,
       `elements`.`enabled`,
       `elements`.`archived`,
       `elements`.`dateCreated`,
       `elements`.`dateUpdated`,
       `elements_sites`.`slug`,
       `elements_sites`.`siteId`,
       `elements_sites`.`uri`,
       `elements_sites`.`enabled` AS `enabledForSite`,
       `entries`.`sectionId`,
       `entries`.`typeId`,
       `entries`.`authorId`,
       `entries`.`postDate`,
       `entries`.`expiryDate`,
       `content`.`id`             AS `contentId`,
       `content`.`title`,
       `content`.`field_plainText`,
       `content`.`field_videoField`,
       `structureelements`.`root`,
       `structureelements`.`lft`,
       `structureelements`.`rgt`,
       `structureelements`.`level`,
       `structureelements`.`structureId`
FROM (SELECT `elements`.`id`       AS `elementsId`,
             `elements_sites`.`id` AS `elementsSitesId`,
             `content`.`id`        AS `contentId`,
             `structureelements`.`structureId`
      FROM `craft_elements` `elements`
               INNER JOIN `craft_entries` `entries` ON `entries`.`id` = `elements`.`id`
               INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
               INNER JOIN `craft_content` `content` ON (`content`.`elementId` = `elements`.`id`) AND
                                                       (`content`.`siteId` = `elements_sites`.`siteId`)
               LEFT JOIN `craft_structureelements` `structureelements`
                         ON (`structureelements`.`elementId` = `elements`.`id`) AND (EXISTS(SELECT *
                                                                                            FROM `craft_structures`
                                                                                            WHERE (`id` = `structureelements`.`structureId`)
                                                                                              AND (`dateDeleted` IS NULL)))
      WHERE (`entries`.`sectionId` = '1')
        AND (`elements_sites`.`siteId` = '3')
        AND (`elements`.`archived` = FALSE)
        AND (((`elements`.`enabled` = TRUE) AND (`elements_sites`.`enabled` = TRUE)) AND
             (`entries`.`postDate` <= '2019-11-15 17:51:40') AND
             ((`entries`.`expiryDate` IS NULL) OR (`entries`.`expiryDate` > '2019-11-15 17:51:40')))
        AND (`elements`.`dateDeleted` IS NULL)
        AND (`elements_sites`.`enabled` = TRUE)
        AND (`elements`.`draftId` IS NULL)
        AND (`elements`.`revisionId` IS NULL)
      ORDER BY `title`) `subquery`
         INNER JOIN `craft_entries` `entries` ON `entries`.`id` = `subquery`.`elementsId`
         INNER JOIN `craft_elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
         INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
         INNER JOIN `craft_content` `content` ON `content`.`id` = `subquery`.`contentId`
         LEFT JOIN `craft_structureelements` `structureelements`
                   ON (`structureelements`.`elementId` = `subquery`.`elementsId`) AND
                      (`structureelements`.`structureId` = `subquery`.`structureId`)
ORDER BY `title`
```

As a note, my craft_structures table only has one row and it is associated with a category group. 

### Update
After some additional digging, it looks like if `withStructure` is not explicitly defined in your query, it defaults to true. So... maybe not a bug? Not sure if there's a good reason not to just return whether the section is a channel or a structure.

### Update 2
After sleeping on this, I can see why it assumes withStructure is true, since a query can include multiple sections, some channels, some structures. This makes perfect sense to me. I think there's maybe an optimization that could be done here, checking to see if one is querying multiple sections and determining the ideal result, but I'll defer to the Craft CMS team to determine if that's worth the additional complexity. Feel free to close this issue and consider me appeased if you'd rather just defer this indefinitely. 

### Additional info

- Craft version: 3.4-dev
- PHP version: 7.3.x
- Database driver & version: MySQL 5.7
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
The current behavior serves as a fix for #1375, but as you’ve found, you can explicitly prevent structure data from being joined with with `withStructure(false)`.
