### ISSUE TITLE
Issues with Date/Time fields in graphql

### ISSUE THREAD

**Issue by leobauza** [craftcms/cms#5240]
### Description

I have a "Date/Time" field that I am trying to query through graphql and noticed these fields don't behave the same way as fields like `dateCreated`. When I query for my "Date/Time" field I get:

```
"Expected a value of type \"String\" but received: instance of DateTime"
```

<img width="1173" alt="Screenshot 2019-11-15 15 42 02" src="https://user-images.githubusercontent.com/1823027/68974326-79fc9b00-07be-11ea-8220-4bd63bed63f5.png">

I can easily then use the `@formatDateTime` directive to get a formatted string. However, that doesn't work when I am using `gatsby-source-graphql` to source data from Craft for a Gatsby site.

<img width="1176" alt="Screenshot 2019-11-15 15 43 14" src="https://user-images.githubusercontent.com/1823027/68974385-a4e6ef00-07be-11ea-8d1c-0e3749e23f4c.png">

What would be great is if I could query for my "Date/Time" field without any directives just like I can query `dateCreated`. Then I can take that date string and process it on the gatsby side.

Alternatively, I don't know if anyone knows of a way to get [`gatsby-source-graphql`](https://www.gatsbyjs.org/packages/gatsby-source-graphql/) to source data from Craft and apply a directive to a particular field.

### Steps to reproduce

1. Create a Date/Time field
2. Query this field without any directives with graphql

### Additional info

- Craft version: 3.3.7
- PHP version: n/a
- Database driver & version: n/a
- Plugins & versions: n/a

**Comment by andris-sevcenko** [comment]
Yikes, sorry about that! Fixed for the next release!
