### ISSUE TITLE
XSS vulnerability introduced via enshrined/svg-sanitize (snyk)

### ISSUE THREAD

**Issue by sunscreem** [craftcms/cms#5243]
### Description

snyk reported yesterday that the [SVG sanitiser](https://github.com/darylldoyle/svg-sanitizer) used in craft has a high risk XSS issue.

This issue has been fixed in the package - [see here](https://github.com/darylldoyle/svg-sanitizer/releases/tag/0.13.0).

I've tried running `composer update enshrined/svg-sanitize` but it says nothing needs updated, so I'm guessing its been locked to an older version?

**Comment by angrybrad** [comment]
Deleting this per our [Security Policy](https://github.com/craftcms/cms/wiki/Security-Policy). Please contact support@craftcms.com directly with security-related issues.
