### ISSUE TITLE
Previewing entry revisions fails

### ISSUE THREAD

**Issue by ryanfoote** [craftcms/cms#5244]
### Description

Attempting to preview a revision of an entry (specifically, not a draft) tosses a couple errors into the browser console:

`Failed to load resource: the server responded with a status of 500 ()`

`Uncaught (in promise)`

The XHR request is failing because Craft is tossing this error:

`HTTP 400 – Bad Request – yii\web\BadRequestHttpException
Post request required`

### Steps to reproduce

1. Open an entry
2. Choose a revision
3. Click the preview button at top-right

### Additional info

- Craft version: Craft Pro 3.3.15
- PHP version: 7.2.24
- Database driver & version: MySQL 5.7.27
- Plugins & versions:

Anchors 2.2.0
Cookies 1.1.11
Craft Redactor Script Buttons 1.1.1
Digital Download 2.1.5
DigitalOcean Spaces Volume 1.1.2
Element Map 1.2.1
Freeform 3.5.3
Linkit 1.1.11
Logs 3.0.2
Mailchimp Subscribe 3.0.0
Mailgun 1.4.2
Matrix Toolbar 1.0.6
MD5 Twig Filter 1.0.0
Mix 1.5.2
MobileDetect 1.0.2
Password Policy 1.0.5
Position Fieldtype 1.0.14
Preparse Field v1.1.0
Read Time 1.5.0
Redactor 2.4.0
Redactor Custom Styles 3.0.2
Super Table 2.3.0
Table Maker 2.0.1
Typogrify 1.1.18
View Count 1.0.1

**Comment by brandonkelly** [comment]
Thanks for reporting that! It’s been fixed for the next release.
