### ISSUE TITLE
3.4 alpha: settings cogs have very small hover areas

### ISSUE THREAD

**Issue by JayBox325** [craftcms/cms#5246]
### Description
When adjusting the layouts of my entries listings the cogs to start this process are very small and don't have a great click-area.

### Steps to reproduce
1. Visit an entries listing
2. Hover the cog at the bottom left of the list on the left column

GIF:
![Nov-19-2019 09-47-33](https://user-images.githubusercontent.com/13233809/69135840-b1669280-0ab1-11ea-80cf-1fa2d33ebea0.gif)

### Additional info
- Craft version: 3.4.0 alpha-1

**Comment by brandonkelly** [comment]
Better now :)
