### ISSUE TITLE
3.4 alpha: all tables have horizontal scroll bars appearing

### ISSUE THREAD

**Issue by JayBox325** [craftcms/cms#5247]
### Description
Even if there is no scrolling required, the horizontal scroll bars are appearing for me on Firefox.

<img width="948" alt="Screenshot 2019-11-19 at 09 36 26" src="https://user-images.githubusercontent.com/13233809/69140589-afed9800-0aba-11ea-8482-2d9757e3b3ba.png">
![Uploading Screenshot 2019-11-19 at 09.36.37.png…]()

### Additional info
Craft version: 3.4.0 alpha-1

**Comment by brandonkelly** [comment]
What browser/version are you running?

**Comment by wsydney76** [comment]
Can confirm that for Chrome 78.0.3904.108/Firefox 70.0.1 on Windows 10.

If there is a vertical scrollbar, another horizontal scrollbar appears at the bottom of the page:

![image](https://user-images.githubusercontent.com/25308802/69327350-afd1d180-0c4d-11ea-9e77-0581da4a2db8.png)

Seems to happen on all CP pages with a vertical scrollbar.

**Comment by JayBox325** [comment]
@brandonkelly sorry, yeah, that would have been helpful. I'm running firefox 70.0.1 on Mojave.

**Comment by Mosnar** [comment]
Can confirm in latest Chrome. Looks like it has to do with this rule:
![image](https://user-images.githubusercontent.com/3810939/69344758-f15a8080-0c3d-11ea-9515-1c7d3b529d0f.png)

Here's a gif:
https://venveo.d.pr/INOVUH

**Comment by brandonkelly** [comment]
This is fixed now!
