### ISSUE TITLE
3.4 alpha: Settings cog overlapping edge of globals container

### ISSUE THREAD

**Issue by JayBox325** [craftcms/cms#5248]
### Description
The cog to adjust some settings for a globals section is positioned on top of the edge of the container holding the fields.

![Screenshot 2019-11-19 at 11 14 06](https://user-images.githubusercontent.com/13233809/69141989-c517f600-0abd-11ea-82ca-339e1827245d.png)

### Additional info
- Craft version: 3.4.0 alpha-0

**Comment by brandonkelly** [comment]
Do you have any plugins installed that may be hiding the sidebar on that page?

**Comment by JayBox325** [comment]
Turns out it's the 'CP Field Inspect' plugin's cog, not yours. Apologies!
