### ISSUE TITLE
Quick posts always go to primary site

### ISSUE THREAD

**Issue by gglnx** [craftcms/cms#5253]
### Description

The quick post widget always uses the primary site as target. If the users isn't allowed there, the quick post fails.

Maybe use a similar approach like in the recent entries widget (`RecentEntries::_getTargetSiteId`).

### Steps to reproduce

1. Create a user without access to the primary site
2. Add quick post widget to dashboard
3. Try to create an entry via the quick post widget

### Additional info

- Craft version: 3.3.15
- PHP version: 7.3.11

**Comment by brandonkelly** [comment]
Just added a new Site setting to Quick Post widgets, for the next 3.5 release.
