### ISSUE TITLE
GraphQL schema error if a Category includes a Matrix field that has a Categories field

### ISSUE THREAD

**Issue by OscarBarrett** [craftcms/cms#5255]
### Description
If a Category Group:
- Has a Matrix field in its field layout, and
- The Matrix field has a block type that includes a field of type Categories

Then GraphQL introspection gives the following error
```
Failed to validate the GQL Schema - Schema must contain unique named types but contains multiple types named \"matrixwithcategory_foo_BlockType\" (see http://webonyx.github.io/graphql-php/type-system/#type-registry).
```

Queries still work, but introspection and playground autocompletion break.
Referencing `__schema` in a query also breaks it.

### Steps to reproduce

1. Create a Matrix field, and add a block type that has a field of type Categories
2. Create a Category Group, and add the Matrix field to the Field Layout

### Additional info

- Craft version: 3.3.15
- PHP version: 7.3.11
- Database driver & version: MySQL 5.7.21
- Plugins & versions: N/A

**Comment by andris-sevcenko** [comment]
That was not easy to track down. Thank you! Fixed for the 3.3.16 release which should be out in a few hours!
