### ISSUE TITLE
Add element check for (global set) project config sync

### ISSUE THREAD

**Issue by joshuabaker** [craftcms/cms#5257]
### What happened

Project config sync failed to create a global set fully, setting the ID to a random element.

### Why it happened

A field plugin threw an exception (during validation) inside the associated fieldset, which meant that the element save failed. This meant there was no ID for the globalset sync (below). The default `globalset` table auto increment was used, which caused an invalid reference to an element with the same ID.

https://github.com/craftcms/cms/blob/a0ed3fba32112907d84ab6c0b549d0e9f94026b0/src/services/Globals.php#L441-L445

### How to fix it

I think we should introduce a check here to ensure that the element is saved.

```php
$success = $elementsService->saveElement($element, false);

if (!$success) {
   throw new Exception('Could not save element when syncing global set.');
}

$globalSetRecord->id = $element->id;
```

Without looking, I suspect that this applies more broadly to project config syncing. This could’ve been rather messy had we not tested this a few times locally.

**Comment by andris-sevcenko** [comment]
Thanks for the tip! Fixed for the next release that should be out today!
