### ISSUE TITLE
Unable to delete a Table field in a Matrix that includes a Dropdown type

### ISSUE THREAD

**Issue by vonscriptor** [craftcms/cms#5258]
### Steps to reproduce

1. Create a Matrix field
2. Create a Block with a Table field
3. Add a Table Column Dropdown Type
4. Save
5. Try to delete the Table

Error:
```
yii\base\InvalidConfigException: The config passed into Component::createComponent() did not specify a class: {"type":null,"id":29,"name":null,"handle":null,"instructions":null,"required":false,"searchable":true,"translationMethod":"none","translationKeyFormat":null,"settings":{"columns":{"col1":{"options":"[]"}}},"uid":"7ec390a6-97a8-462f-817f-47398c8370d7"} in /Users/username/Sites/project/vendor/craftcms/cms/src/helpers/Component.php:98
```

#### To delete the Table:

1. Change the Dropdown to a Single-line text type
2. Save
3. Delete the Table field
4. Save

### Additional info

- Craft version: 3.3.11
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release.
