### ISSUE TITLE
Asset transforms remove color profiles, ignoring 'preserveImageColorProfiles' setting

### ISSUE THREAD

**Issue by sonoflee** [craftcms/cms#5261]
### Description
When using native transforms or ImageOptimize, embedded color profiles are stripped out of the resulting files. Transforms created with Imager plugin using default settings preserve color profiles when using the same asset source. 

I have the following parameters set in my general.php:
`'preserveImageColorProfiles' => true,
'imageDriver' => 'imagick',
'preserveExifData' => true`

### Steps to reproduce

1. Update general.php to make sure `'preserveImageColorProfiles' => true` 
2. Upload image with embedded color profile (mine used Adobe RGB)
3. Create any transform
4. Compare uploaded image and generated transform

### Additional info

- Craft version: 3.3.4.1
- PHP version: 7.1.4
- Database driver & version: MySQL 5.6.34
- Image driver & version: Imagick 3.4.3 (ImageMagick 6.8.9-9)
- Plugins & versions: Amazon S3 1.2.5, Calendarize 1.2.16, Colorit 1.0.8, Colour Swatches 1.2.3, Craft Ajaxinate 2.0.1, Dumper 2.0.0, Eager Beaver 1.0.4, Element API 2.6.0, Embedded Assets 2.0.12, Empty Coalesce 1.0.6, Feed Me 4.1.2, Field Labels 1.1.6, Field Manager 2.1.0, Field Reveal 1.0.1, ImageOptimize 1.6.6, Imager v2.2.0, Instagram Feed 1.0.4, Isolate 1.1.2, Link 1.1.4, Linkit 1.1.11, Minify 1.2.9, Neo 2.4.8, Position Fieldtype 1.0.14, Preparse Field v1.1.0, Redactor 2.4.0, Retcon 2.0.12, Spoon 3.3.7, Store Hours 2.1.1.1, SuperSort 3.0.1, Super Table 2.3.0, Table Maker 2.0.1, Twig Perversion 2.1.0, Typed link field 1.0.19, Typogrify 1.1.18

### Example images

**Original (Embedded color profile: “AdobeRGB”)**

![Original - BMS-test3](https://user-images.githubusercontent.com/24461590/69487222-c762b300-0e23-11ea-99d1-025dbd34c5d7.jpg)

**Imager Transform (Embedded color profile: “AdobeRGB”)**

![BMS-test3_1ce71477c4c222c36aa8751eb6404385](https://user-images.githubusercontent.com/24461590/69487264-a9498280-0e24-11ea-8c19-fcb4f09d4be7.jpg)

**Craft Transform, setting: _Quality: Very High_ (No color-space metadata and no embedded color profile)**

![BMS-test3-craftxform](https://user-images.githubusercontent.com/24461590/69487319-c03ca480-0e25-11ea-8042-1009d0913301.jpg)

**Comment by andris-sevcenko** [comment]
I can confirm that I'm able to reproduce this on Craft 3.3.16.1. I'll dig a bit deeper, see what's what.

**Comment by andris-sevcenko** [comment]
Actually, I had left the `preserveImageColorProfiles` setting to `false` on Craft 3.3, so I can't really reproduce that.

Can you try updating to the latest Craft version and see if the image persists? Also, make sure that you're not getting cached versions of the transforms.

**Comment by brandonkelly** [comment]
Also please disable Image Optimize from Settings → Plugins before generating new transforms. Have a feeling that’s the culprit.

**Comment by sonoflee** [comment]
Brandon, you're correct - disabling ImageOptimize solved the issue. I wasn't aware that ImageOptimize transform settings are used by the native transforms when enabled, I will check in to see if that can be made more clear.  Thanks!

**Comment by andris-sevcenko** [comment]
@sonoflee ImageOptimize hooks into the Asset transform process and replace it with its own, rather than transforms using the ImageOptimize settings :)
(cc @khalwat)

**Comment by khalwat** [comment]
@sonoflee @andris-sevcenko So ImageOptimize uses Craft to do the transforms, but what does happen is the image optimizers are run post facto.

Feel fee to contact me to discuss further, but it's likely that you're using one of these optimizers:

https://github.com/nystudio107/craft-imageoptimize/blob/v1/src/config.php#L159

...and one of its optimizations is to strip the color palette. You can fix that by adding an appropriate flag for the optimizer that you're using.

**Comment by sonoflee** [comment]
@khalwat Thanks, that is exactly what was going on! I have updated the webp/png/jpeg optimizers I'm using with flags to preserve profiles, and things are working great now.  

It wasn't clear to me that these optimizations would also be applied to native craft transforms (i.e., those not created in the ImageOptimize fields) as well - but I admit I might not be the most thorough documentation reader around, so not sure if it would be worth spelling this out further in the docs in case anyone runs into the same issue.  

Thanks to everyone for pointing me in the right direction!
