### ISSUE TITLE
Installation with PostgreSQL 12 fails

### ISSUE THREAD

**Issue by timoschwarzer** [craftcms/cms#5263]
### Description
I cannot install Craft using PostgreSQL 12. It works fine with the latest PostgreSQL 11 though.

<details>
<summary>Stack trace</summary>
<pre>
craft_1  | Exception: SQLSTATE[42703]: Undefined column: 7 ERROR:  column c.consrc does not exist
craft_1  | LINE 10:     "c"."consrc" AS "check_expr"
craft_1  |              ^
craft_1  | HINT:  Perhaps you meant to reference the column "c.conkey" or the column "c.conbin".
craft_1  | The SQL being executed was: SELECT
craft_1  |     "c"."conname" AS "name",
craft_1  |     "a"."attname" AS "column_name",
craft_1  |     "c"."contype" AS "type",
craft_1  |     "ftcns"."nspname" AS "foreign_table_schema",
craft_1  |     "ftc"."relname" AS "foreign_table_name",
craft_1  |     "fa"."attname" AS "foreign_column_name",
craft_1  |     "c"."confupdtype" AS "on_update",
craft_1  |     "c"."confdeltype" AS "on_delete",
craft_1  |     "c"."consrc" AS "check_expr"
craft_1  | FROM "pg_class" AS "tc"
craft_1  | INNER JOIN "pg_namespace" AS "tcns"
craft_1  |     ON "tcns"."oid" = "tc"."relnamespace"
craft_1  | INNER JOIN "pg_constraint" AS "c"
craft_1  |     ON "c"."conrelid" = "tc"."oid"
craft_1  | INNER JOIN "pg_attribute" AS "a"
craft_1  |     ON "a"."attrelid" = "c"."conrelid" AND "a"."attnum" = ANY ("c"."conkey")
craft_1  | LEFT JOIN "pg_class" AS "ftc"
craft_1  |     ON "ftc"."oid" = "c"."confrelid"
craft_1  | LEFT JOIN "pg_namespace" AS "ftcns"
craft_1  |     ON "ftcns"."oid" = "ftc"."relnamespace"
craft_1  | LEFT JOIN "pg_attribute" "fa"
craft_1  |     ON "fa"."attrelid" = "c"."confrelid" AND "fa"."attnum" = ANY ("c"."confkey")
craft_1  | WHERE "tcns"."nspname" = 'public' AND "tc"."relname" = 'userpreferences'
craft_1  | ORDER BY "a"."attnum" ASC, "fa"."attnum" ASC (/app/vendor/yiisoft/yii2/db/Schema.php:664)
craft_1  | #0 /app/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'SELECT\n    "c"....')
craft_1  | #1 /app/vendor/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('SELECT\n    "c"....')
craft_1  | #2 /app/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
craft_1  | #3 /app/vendor/yiisoft/yii2/db/pgsql/Schema.php(673): yii\db\Command->queryAll()
craft_1  | #4 /app/vendor/yiisoft/yii2/db/pgsql/Schema.php(205): yii\db\pgsql\Schema->loadTableConstraints('userpreferences', 'primaryKey')
craft_1  | #5 /app/vendor/yiisoft/yii2/db/Schema.php(744): yii\db\pgsql\Schema->loadTablePrimaryKey('userpreferences')
craft_1  | #6 /app/vendor/yiisoft/yii2/db/ConstraintFinderTrait.php(101): yii\db\Schema->getTableMetadata('{{%userpreferen...', 'primaryKey', false)
craft_1  | #7 /app/vendor/yiisoft/yii2/db/QueryBuilder.php(574): yii\db\pgsql\Schema->getTablePrimaryKey('{{%userpreferen...')
craft_1  | #8 /app/vendor/yiisoft/yii2/db/QueryBuilder.php(546): yii\db\QueryBuilder->getTableUniqueColumnNames('{{%userpreferen...', Array, Array)
craft_1  | #9 /app/vendor/yiisoft/yii2/db/pgsql/QueryBuilder.php(337): yii\db\QueryBuilder->prepareUpsertColumns('{{%userpreferen...', Array, Array)
craft_1  | #10 /app/vendor/yiisoft/yii2/db/pgsql/QueryBuilder.php(323): yii\db\pgsql\QueryBuilder->newUpsert('{{%userpreferen...', Array, Array, Array)
craft_1  | #11 /app/vendor/yiisoft/yii2/db/Command.php(546): yii\db\pgsql\QueryBuilder->upsert('{{%userpreferen...', Array, Array, Array)
craft_1  | #12 /app/vendor/craftcms/cms/src/db/Command.php(124): yii\db\Command->upsert('{{%userpreferen...', Array, Array, Array)
craft_1  | #13 /app/vendor/craftcms/cms/src/services/Users.php(303): craft\db\Command->upsert('{{%userpreferen...', Array, Array, Array, false)
craft_1  | #14 /app/vendor/craftcms/cms/src/migrations/Install.php(1076): craft\services\Users->saveUserPreferences(Object(craft\elements\User), Array)
craft_1  | #15 /app/vendor/craftcms/cms/src/migrations/Install.php(73): craft\migrations\Install->insertDefaultData()
craft_1  | #16 /app/vendor/craftcms/cms/src/db/Migration.php(58): craft\migrations\Install->safeUp()
craft_1  | #17 /app/vendor/craftcms/cms/src/db/MigrationManager.php(239): craft\db\Migration->up(true)
craft_1  | #18 /app/vendor/craftcms/cms/src/console/controllers/InstallController.php(161): craft\db\MigrationManager->migrateUp(Object(craft\migrations\Install))
craft_1  | #19 [internal function]: craft\console\controllers\InstallController->actionCraft()
craft_1  | #20 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
craft_1  | #21 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
craft_1  | #22 /app/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
craft_1  | #23 /app/vendor/craftcms/cms/src/console/Controller.php(199): yii\console\Controller->runAction('', Array)
craft_1  | #24 /app/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('', Array)
craft_1  | #25 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('install', Array)
craft_1  | #26 /app/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('install', Array)
craft_1  | #27 /app/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('install', Array)
craft_1  | #28 /app/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
craft_1  | #29 /app/craft(22): yii\base\Application->run()
craft_1  | #30 {main}
craft_1  | Exception 'craft\errors\MigrationException' with message 'An error occurred while executing the "craft\migrations\Install migration: SQLSTATE[42703]: Undefined column: 7 ERROR:  column c.consrc does not exist
craft_1  | LINE 10:     "c"."consrc" AS "check_expr"
craft_1  |              ^
craft_1  | HINT:  Perhaps you meant to reference the column "c.conkey" or the column "c.conbin".
craft_1  | The SQL being executed was: SELECT
craft_1  |     "c"."conname" AS "name",
craft_1  |     "a"."attname" AS "column_name",
craft_1  |     "c"."contype" AS "type",
craft_1  |     "ftcns"."nspname" AS "foreign_table_schema",
craft_1  |     "ftc"."relname" AS "foreign_table_name",
craft_1  |     "fa"."attname" AS "foreign_column_name",
craft_1  |     "c"."confupdtype" AS "on_update",
craft_1  |     "c"."confdeltype" AS "on_delete",
craft_1  |     "c"."consrc" AS "check_expr"
craft_1  | FROM "pg_class" AS "tc"
craft_1  | INNER JOIN "pg_namespace" AS "tcns"
craft_1  |     ON "tcns"."oid" = "tc"."relnamespace"
craft_1  | INNER JOIN "pg_constraint" AS "c"
craft_1  |     ON "c"."conrelid" = "tc"."oid"
craft_1  | INNER JOIN "pg_attribute" AS "a"
craft_1  |     ON "a"."attrelid" = "c"."conrelid" AND "a"."attnum" = ANY ("c"."conkey")
craft_1  | LEFT JOIN "pg_class" AS "ftc"
craft_1  |     ON "ftc"."oid" = "c"."confrelid"
craft_1  | LEFT JOIN "pg_namespace" AS "ftcns"
craft_1  |     ON "ftcns"."oid" = "ftc"."relnamespace"
craft_1  | LEFT JOIN "pg_attribute" "fa"
craft_1  |     ON "fa"."attrelid" = "c"."confrelid" AND "fa"."attnum" = ANY ("c"."confkey")
craft_1  | WHERE "tcns"."nspname" = 'public' AND "tc"."relname" = 'userpreferences'
craft_1  | ORDER BY "a"."attnum" ASC, "fa"."attnum" ASC'
craft_1  | 
craft_1  | in /app/vendor/craftcms/cms/src/db/MigrationManager.php:256
craft_1  | 
craft_1  | Stack trace:
craft_1  | #0 /app/vendor/craftcms/cms/src/console/controllers/InstallController.php(161): craft\db\MigrationManager->migrateUp(Object(craft\migrations\Install))
craft_1  | #1 [internal function]: craft\console\controllers\InstallController->actionCraft()
craft_1  | #2 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
craft_1  | #3 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
craft_1  | #4 /app/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
craft_1  | #5 /app/vendor/craftcms/cms/src/console/Controller.php(199): yii\console\Controller->runAction('', Array)
craft_1  | #6 /app/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('', Array)
craft_1  | #7 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('install', Array)
craft_1  | #8 /app/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('install', Array)
craft_1  | #9 /app/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('install', Array)
craft_1  | #10 /app/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
craft_1  | #11 /app/craft(22): yii\base\Application->run()
craft_1  | #12 {main}
</pre>
</details>

### Steps to reproduce

1. Create a new Craft CMS installation via Composer
2. Try to run `./craft install` in combination with a PostgreSQL 12.1 database

### Additional info

- Craft version: 3.3.16.1
- PHP version: 7.3.12
- Database driver & version: PostgreSQL 12.1
- Plugins & versions: -

**Comment by angrybrad** [comment]
This was fixed in Yii 2.0.29 (https://github.com/yiisoft/yii2/issues/17597), which a fresh Craft install uses 2.0.30 as a minimum: https://github.com/craftcms/cms/blob/develop/composer.json#L50

So not sure how you're getting an older version unless you're locking Yii2 to an older version explicitly in your composer.json file?

**Comment by brandonkelly** [comment]
Search for `"name": "yiisoft/yii2"` in your `composer.lock` file. What version is it installed at?

**Comment by timoschwarzer** [comment]
Thank you very much for the hint! @angrybrad @brandonkelly 
It turned out that my composer cache in `~/.composer` was broken (probably because I'm using Prestissimo). Deleting that and the creating a new Craft installation worked fine. Thank you! :)
