### ISSUE TITLE
PostgreSQL - Unable to convert plaintext field to number

### ISSUE THREAD

**Issue by dbrookes** [craftcms/cms#5266]
### Description

With PostgreSQL, after creating a plain text field (no data in it) I'm unable to convert it into a number field.

### Steps to reproduce

1. Create plain text field
2. Immediately try to convert it into a number field

```
SQLSTATE[42804]: Datatype mismatch: 7 ERROR: column "field_ranking" cannot be cast automatically to type integer
HINT: You might need to specify "USING "field_ranking"::integer".
The SQL being executed was: ALTER TABLE "content" ALTER COLUMN "field_ranking" TYPE integer, ALTER COLUMN "field_ranking" DROP DEFAULT, ALTER COLUMN "field_ranking" DROP NOT NULL
```

### Additional info

- Craft version: Craft Pro 3.3.13
- PHP version: 7.2
- Database driver & version: PostgreSQL 10.11
- Plugins & versions:

**Comment by brandonkelly** [comment]
This is now fixed for the next release. See https://github.com/craftcms/cms/issues/3605#issuecomment-701466443.

**Comment by brandonkelly** [comment]
Craft 3.5.12 is out now with that change ✨
