### ISSUE TITLE
GraphQL - Unable to pass null status on entries/categories fields

### ISSUE THREAD

**Issue by dbrookes** [craftcms/cms#5267]
### Description

Status accepts a null value to return entries of any status, but category and entries fields within the query do not allow this:

```
  entries(limit: 100, section: "pages", status: null) { // works
    title
    ... on pages_page_Entry {
      categoryField(status: null) { // error, only accepts string
        title
      }
      entriesField(status: null) { // error, only accepts string
        title
      }
    }
  }
```

```
"debugMessage": "Undefined property: GraphQL\\Language\\AST\\NullValueNode::$value",
"message": "Internal server error",
```

### Additional info

    Craft version: Craft Pro 3.3.13
    PHP version: 7.2
    Database driver & version: PostgreSQL 10.11
    Plugins & versions:

**Comment by andris-sevcenko** [comment]
Thanks! This is fixed for the next release!
