### ISSUE TITLE
Number fields should return float/int/null, not string

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#5268]
Number fields always return string values, which seems like a bug.

`craft\fields\Number::valueType` is `int|float|null`, so it seems like it should return that?

**Comment by andris-sevcenko** [comment]
Is this related to GraphQL or just a general annoyance?

**Comment by brandonkelly** [comment]
Doh, no idea why I thought this was a GraphQL bug. Just fixed this for the next release.

**Comment by timkelty** [comment]
Thanks!
