### ISSUE TITLE
Unable to override Yii custom session storage

### ISSUE THREAD

**Issue by jlamb1** [craftcms/cms#5269]
### Description
Hi all, working to create a kubernetes boilerplate with 3 services:

- craft - at the moment using the [wyveo/craftcms-docker](https://github.com/wyveo/craftcms-docker) image, which builds on `nginx-php-fpm:php73`
- postgres - pulling from `postgres:11.5`
- redis - pulling from `redis:5.0.6-alpine`

working locally so running in minikube.

The php settings are set in the [Dockerfile](https://github.com/wyveo/craftcms-docker/blob/craft3/Dockerfile), and exec'ing into the container the php.ini and app.php settings all appear to be correct.

I got stuck after install with this error:

```
session_start(): php_network_getaddresses: getaddrinfo failed: Name or service not known
```

I tried setting the `session.save_handler` and `session.save_path` a few ways, but even `ini_set()` in the index.php seemed not to register.

Stumbled upon [this issue](https://github.com/wyveo/craftcms-docker/issues/12#issuecomment-409750801), and changing `vendor/yiisoft/yii2/web/Session.php` line 121 from false to true fixed the issue, and redis logs showed incoming data to the pod.

### Steps to reproduce

Happy to grant access to a private git repo I have, there's not much there yet but it's a simple
- minikube start
- `kubectl apply -k /.`

### Additional info

- Craft version: 3.3.16.3 (Solo)
- PHP version: 7.3
- Database driver & version: postgres 11.5
- Plugins & versions: none

Let me know if I can give any more info, if it were possible to override this within app.php or similar that would be great!

**Comment by brandonkelly** [comment]
Best way to use Redis for session storage is with the [yii2-redis](https://github.com/yiisoft/yii2-redis) extension. We have an example of how to configure it in our docs: https://docs.craftcms.com/v3/config/app.html#session-component

Note that the `as session` config key is Craft-specific, and mandatory.

**Comment by jlamb1** [comment]
ah, i've done that before too and totally blanked- thanks!
