### ISSUE TITLE
Deleting entry type when it exists in a revision

### ISSUE THREAD

**Issue by bymayo** [craftcms/cms#5270]
### Description

We just deleted an entry type we thought we were no longer using from a section. 

Then when we went to edit an entry, if the entry had revisions that had the deleted entry type in there, it would error and not load the entry in the CMS.

Basically throwing an error saying that that particular entry type ID couldn't be found.

### Additional info

- Craft version: 3.3.14
- PHP version: 7.1
- Database driver & version: 5.7

**Comment by brandonkelly** [comment]
Just fixed this for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#https://github.com/craftcms/cms/commit/cd4aa4d4dba87d047816a05bf614439802e4b929 as 3.3.16.3",
  "...": "..."
}
```

Then run `composer update`.
