### ISSUE TITLE
[Bug] Pagination labels for Entries in German are wrong

### ISSUE THREAD

**Issue by vandres** [craftcms/cms#5271]
### Description
If you navigate through the entries, the translation is not correct:

![Bildschirmfoto 2019-11-27 um 12 56 45](https://user-images.githubusercontent.com/1436383/69721617-86191e80-1115-11ea-9eab-617c99acfc7b.png)

"1 eintrag" should be "1 Eintrag"

### Steps to reproduce

1. Base install
2. switch to German

### Additional info

Responsible for that are the `toLowerCase()` in ElementIndexesController:

```
if (!$this->paginated || !$this->elementQuery->limit || $count < $this->elementQuery->limit) {
            $responseData['countLabel'] = Craft::t('app', '{total, number} {total, plural, =1{{item}} other{{items}}}', [
                'total' => $count,
                'item' => StringHelper::toLowerCase($elementType::displayName()),
                'items' => StringHelper::toLowerCase($elementType::pluralDisplayName()),
            ]);
        }
```

- Craft version: 3.3.16.3
- PHP version: 7.2

**Comment by brandonkelly** [comment]
It should be upppercase even though it’s not a heading or anything?

**Comment by vandres** [comment]
Yes, in German nouns are written uppercase

**Comment by brandonkelly** [comment]
Thanks for clarifying! Fixed for the next release.

**Comment by vandres** [comment]
Wow, that was no trivial fix. Thank you!

**Comment by narration-sd** [comment]
Wow -- wondered what you'd think to do when really realized, but this is tops -- kudos for sure, @brandonkelly!  (someone is a code-making, not to say designing, machine...)

**Comment by vandres** [comment]
@brandonkelly I found more spots related to this issue:

`src/templates/_components/fieldtypes/elementfieldsettings.html` e.g. line 56 `instructions: "Enter the text you want to appear on the {type} selection input."|t('app', { type: field.displayName()|lower }),`

There a more spots with `|lower` in that file. Do you want me to make a new issue for that or is here okay?

**Comment by brandonkelly** [comment]
@vandres Doh, forgot to check templates. Just found a few other things that needed to be updated.
