### ISSUE TITLE
[Feature] Pass error code on error template render

### ISSUE THREAD

**Issue by MarqtransIT** [craftcms/cms#5273]
### Pass html error code on error template render
That way it is possible to make error pages in a channel type format

Example error.twig
```javascript
<script>
window.location = "/errors/{{ statuscode }}";
</script>
```

### Pull request [5274](https://github.com/craftcms/cms/pull/5274)

In the file
> vendor\craftcms\cms\src\controllers\TemplatesController.php

at line 242 insert
```php
'statuscode' => $statusCode,
```
so the variables array likes like so

```php
  $variables = array_merge([
            'message' => $message,
            'code' => $exception->getCode(),
            'file' => $exception->getFile(),
            'line' => $exception->getLine(),
            'statuscode' => $statusCode,
        ], get_object_vars($exception));
```
allowing the error.twig template to access `{{ statuscode }}`

**Comment by brandonkelly** [comment]
Technically there already was a `statusCode` variable, if `$exception` was an instance of `yii\web\HttpException`, thanks to that `get_object_vars($exception)` line, but I’ll allow this because now we can be sure that there will always be a `statusCode` variable, set to 500 by default.
