### ISSUE TITLE
Overriding Volume Types

### ISSUE THREAD

**Issue by markhuot** [craftcms/cms#5277]
### Description

Currently to use `config/volumes.php` the volume must first be created in the database/UI. That's fine except for one issue: if you create the initial volume as a "Local" volume and then try to override the `type` in `volumes.php` to S3 you run in to issues because the Local settings include a `path` key which is an invalid config for S3.

It all happens here: https://github.com/craftcms/cms/blob/ee782fbb5cf3237b48fb8720d69fc19d87051886/src/services/Volumes.php#L491-L497

This breaks because my database stores this:

```yaml
settings:
    path: @webroot/path/to/dir
```

And my config stores this,

```php
return [
    "volumeHandle" => [
        "type" => "craft\awss3\Volume",
        "keyId" => "foo",
        "secret" => "bar",
    ],
];
```

So, given those two arrays are merged up there in line 496 I end up with a busted S3 config that looks something like this,

```php
return [
    "volumeHandle" => [
        "path" => "@webroot/path/to/dir",
        "type" => "craft\awss3\Volume",
        "keyId" => "foo",
        "secret" => "bar",
    ],
];
```

I would think one of the following would solve this,

1. add a "dummy" volume driver that doesn't have any settings and simply exists as a way to save a volume to the database without any settings. This could create a lot of user confusion but is probably the least complex.
2. update the existing drivers to ignore unused configuration so S3 wouldn't care if you try to pass it a `path` key, it'd just silently ignore it.

All of this is necessary if you want to use a local filesystem for images in development and s3 in production.

### Steps to reproduce

1. Create a new local volume
2. Save the local volume
3. Try to override that volume in `config/volumes.php`

### Additional info

- Craft version: 3.3.1.2
- PHP version: 7.2.21
- Database driver & version: MySQL 5.7
- Plugins & versions: craftcms/aws-s3

### Prior art

- https://github.com/craftcms/cms/issues/3219

**Comment by brandonkelly** [comment]
We’ve stopped recommending using `volumes.php` and removed almost all mentions of it in the docs, as Craft 3.1 added support for [setting environment variables directly in CP settings](https://docs.craftcms.com/v3/config/environments.html#control-panel-settings). That route should work a little better for you.

**Comment by markhuot** [comment]
Can I use ENV variables to switch from a local volume in development to an S3 volume in production? I’m not sure I can set the type via ENV variables?

**Comment by brandonkelly** [comment]
Yep, choose “Manual” under the Bucket setting:

<img width="251" alt="The Bucket setting" src="https://user-images.githubusercontent.com/47792/69908869-8d0a9000-13a6-11ea-8d07-e41a9e78e922.png">

Then you will be able to set the Bucket and Region manually, to environment variables just like other settings.

<img width="715" alt="The manual Bucket and Region settings" src="https://user-images.githubusercontent.com/47792/69908879-c2af7900-13a6-11ea-953d-bd27f7a99659.png">

**Comment by brandonkelly** [comment]
Sorry, I misread. It would not be possible to switch the underlying volume type, no. You’d have to settle for swapping between two different S3 accounts/buckets.

**Comment by markhuot** [comment]
Is there a recommended way to do this development/production swap?

I'm being a pain because (partially) I'm lazy and don't feel like setting up S3 access for all our developers and also (practically) I don't know that I _can_ set up S3 access for everyone. We have AWS access locked down pretty tightly and are using IAM roles in production, I'm not sure the client wants access keys floating around for local development.

I could create two volumes, e.g., "Blog Images (Production, S3)" and "Blog Images (Local)" but then we get in to training headaches and grossness with Assets fields pointing to the right volume in different environments.

**Comment by brandonkelly** [comment]
Good point, and I don’t have a good answer for you at the moment. So just resolved your initial request. Now if an `UnknownPropertyException` is thrown while trying to initialize a volume, there is a special case to remove the `path` key from the volume config.

**Comment by markhuot** [comment]
Thanks, this is helpful! I'll continue using `config/volumes.php` to set the `type` but maybe look to move everything else over to ENV vars so it's a bit more "standard."

**Comment by brandonkelly** [comment]
@jasonmccallister just tipped me off to https://min.io/, which can give you a local object storage server with an S3-compatible API. Even on Homebrew: https://github.com/minio/minio#homebrew

**Comment by markhuot** [comment]
Nice, that seems easier to setup than https://github.com/localstack/localstack, which I was also exploring. Ideally I'd love to be able to vary volume types per environment because I think that will reduce some overhead on our developers. If you'd like me to write this up as a separate FR, let me know.

In the meantime, this should keep me moving. Thank you!

**Comment by brandonkelly** [comment]
> Ideally I'd love to be able to vary volume types per environment because I think that will reduce some overhead on our developers. If you'd like me to write this up as a separate FR, let me know.

If you have an idea of how it could be made easier, sure, that would be great.
