### ISSUE TITLE
Asset editor focal point and cropping not working on touch devices

### ISSUE THREAD

**Issue by rostockahoi** [craftcms/cms#5279]
### Description
Unable to use asset editor on touch device. Specific: Can't move focal point and cropping rectangle with touch device. Related to: https://github.com/craftcms/cms/issues/3669

### Steps to reproduce
1. Open asset editor of an image
2. Try to edit focal point or crop

### Additional info
- Devices:
  - iPad, iPad OS 12.1, Chrome 5.31
  - Linux Mint 18.3, Chromium 77.0.3865.90 (DevTools Touch emulator)
  - Windows 10, Chrome 78.0.3904.70 (DevTools Touch emulator)
  - some Android phone with Samsung Browser (which I actually wanted to show my client that asset editing is working - it's not :)
- Craft version: 3.3.16.3
- PHP version: 7.2.4
- Database driver & version: MySQL 5.7.21
- Plugins & versions: None (all deactivated)

**Comment by brandonkelly** [comment]
Thanks for pointing that out. Now fixed for the next release!
