### ISSUE TITLE
Switching a site from non-primary to primary kills user search in CP

### ISSUE THREAD

**Issue by thisisjamessmith** [craftcms/cms#5281]
### Description

In a 2-site multi-site setup I tried switching the primary site from one to the other, and afterwards, I am unable to use the keyword search on the Users index. Switching the primary site back again restores the user search functionality

### Steps to reproduce

1. Have a multi-site installation with 2 sites
2. Create a few users
3. Change which site is set as primary
4. Attempt to use the search input on the Users index list

### Additional info

- Craft version: 3.3.16.1
- PHP version: 7.1
- Database driver & version: MySQL 5.6.38

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just fixed for the next release.

In the meantime you can fix by running the `./craft resave/users` command.
