### ISSUE TITLE
Can be define an alias for matrix elements in query?

### ISSUE THREAD

**Issue by nurullahozdemir** [craftcms/cms#5283]
### Description
Can be define an alias for matrix elements in query? I want to named block types in matrix field so excepted result returns me as blocks name.

![Screenshot_1](https://user-images.githubusercontent.com/56108206/69820238-bd6cf580-1211-11ea-8e0d-28db4223db83.png)

Exptected Result: 
`"sections": {
     aliasInHereOrWhere: {
         id: 1
     }
}`

### Additional info

- Craft version: Craft Pro 3.3.16.3
- PHP version: 7.3.11
- Database driver & version: MySQL 5.5.5
- Plugins & versions: GraphQL

@angrybrad @andris-sevcenko @benjamindavid @brandonkelly @lukeholder @olivierbon

**Comment by andris-sevcenko** [comment]
That's not possible with GraphQL and is not a Craft limitation.

You can do

```gql
{
  entries {
    title
    ... on news_news_Entry {
      matrixField {
        ... on matrixField_matrixBlock_BlockType {
          __typename
          typeHandle
        }
      }
    }
  }
}
```
`__typeName` will have the value of "matrixField_matrixBlock_BlockType" while `typeHandle` will have the value of the Matrix block type's handle, so "matrixBlock" in this example.

**Comment by andris-sevcenko** [comment]
@nurullahozdemir Actually, now that I think about it, you might be able to use an approach outlined here: https://github.com/craftcms/cms/issues/5008
