### ISSUE TITLE
Module saving categoryField error

### ISSUE THREAD

**Issue by pieter-janDB** [craftcms/cms#5285]
### Description

I want to add a category to a category field named "catsLinked". But when I use that field in my module logic before saving it, an error occurs. 

When I just var_dump($catToUpdate->catsLinked) or $catToUpdate->catsLinked->ids() an error occurs on afterSave. The idea is I want to use the current ids to merge with the new category and save the field.

### Steps to reproduce

Make a module and use this function to get one category (id 1962 in my case) and link another cat (differend categoryGroup with id 8580 in my case) but use the categoryField in some other logic before saving.
```
use craft\elements\Category; -> this is Category

public function addExtraCategories(){
    $catToUpdate = Category::find()
        ->id(1962)
        ->one();
    $idsToLink = ['8579'];
    $allreadyLinked = ['8580']; // we want to use $catToUpdate->catsLinked->ids() here instead
    var_dump($catToUpdate->catsLinked); // <- this line causes the error, commenting it makes us save the product
    $idsToLink = array_merge($allreadyLinked, $idsToLink);

    //repeating the query to get the product again "fixes" it
    //$catToUpdate = Category::find()
    //    ->id(1962)
    //    ->one();

    $catToUpdate->catsLinked = $idsToLink;
    $saved = Craft::$app->elements->saveElement($catToUpdate);
    var_dump($saved); //true
}
```

Putting this rule in comments removes the error :/ .
```
var_dump($catToUpdate->catsLinked);
```

Error Stack trace:

```
PHP Notice 'yii\base\ErrorException' with message 'Trying to get property 'id' of non-object'

in /Users/pieterjandb/Sites/projectx/vendor/craftcms/cms/src/fields/BaseRelationField.php:650

Stack trace:
#0 /Users/pieterjandb/Sites/projectx/vendor/craftcms/cms/src/elements/Category.php(554): craft\elements\Category->afterSave()
#1 /Users/pieterjandb/Sites/projectx/vendor/craftcms/cms/src/services/Elements.php(2023): craft\elements\Category->afterSave()
#2 /Users/pieterjandb/Sites/projectx/vendor/craftcms/cms/src/services/Elements.php(525): craft\services\Elements->_saveElementInternal()
#3 /Users/pieterjandb/Sites/projectx/modules/MyPluginmodule/src/services/MyPlugin_Categories.php(289): craft\services\Elements->saveElement()
#4 /Users/pieterjandb/Sites/projectx/modules/MyPluginmodule/src/console/controllers/MyPluginController.php(73): modules\MyPluginmodule\services\MyPlugin_Categories->addCategory()
#5 /Users/pieterjandb/Sites/projectx/vendor/yiisoft/yii2/base/InlineAction.php(57): modules\MyPluginmodule\console\controllers\MyPluginController->actionAddCategory()
#6 /Users/pieterjandb/Sites/projectx/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/Users/pieterjandb/Sites/projectx/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#7 /Users/pieterjandb/Sites/projectx/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#8 /Users/pieterjandb/Sites/projectx/vendor/yiisoft/yii2/console/Controller.php(148): modules\MyPluginmodule\console\controllers\MyPluginController->runAction()
#9 /Users/pieterjandb/Sites/projectx/vendor/yiisoft/yii2/base/Module.php(528): modules\MyPluginmodule\console\controllers\MyPluginController->runAction()
#10 /Users/pieterjandb/Sites/projectx/vendor/yiisoft/yii2/console/Application.php(180): craft\console\Application->runAction()
#11 /Users/pieterjandb/Sites/projectx/vendor/craftcms/cms/src/console/Application.php(93): craft\console\Application->runAction()
#12 /Users/pieterjandb/Sites/projectx/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#13 /Users/pieterjandb/Sites/projectx/vendor/yiisoft/yii2/base/Application.php(386): craft\console\Application->handleRequest()
#14 /Users/pieterjandb/Sites/projectx/craft(22): craft\console\Application->run()
#15 {main}

```
### Additional info

- Craft version: 3.3.16.1
- PHP version: PHP 7.2.20
- Database driver & version: mysql@5.7
- Plugins & versions:

Composer.json:
```
{
  "require": {
    "baldwin/medipim-api-v3-client": "^0.4.0",
    "barrelstrength/sprout-forms": "3.5.1",
    "craftcms/cms": "3.3.15",
    "craftcms/commerce": "2.2.7",
    "craftcms/commerce-mollie": "2.1.0.1",
    "craftcms/element-api": "2.6.0",
    "craftcms/redactor": "^2.4",
    "nystudio107/craft-cookies": "^1.1",
    "nystudio107/craft-seomatic": "3.2.33",
    "nystudio107/craft-twigpack": "1.1.12",
    "pennebaker/craft-architect": "^2.3",
    "putyourlightson/craft-log-to-file": "^1.1",
    "putyourlightson/craft-sendgrid": "1.2.0",
    "rias/craft-position-fieldtype": "^1.0",
    "spicyweb/craft-fieldlabels": "1.1.7",
    "topshelfcraft/wordsmith": "3.1.1",
    "trendyminds/isolate": "1.1.2",
    "vaersaagod/matrixmate": "1.2.2",
    "verbb/cloner": "1.0.3",
    "verbb/smith": "1.0.0",
    "verbb/super-table": "2.3.0",
    "vlucas/phpdotenv": "^3.4.0"
  },
  "autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  },
  "config": {
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "7.0"
    }
  },
  "scripts": {
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ]
  }
}

```

**Comment by brandonkelly** [comment]
What do you mean “before saving it”?

**Comment by pieter-janDB** [comment]
I get the category with:
```
$catToUpdate = Category::find()
        ->id(1962)
        ->one();
```
With before saving I mean all logic between getting the category and saving it like this rule which causes the error:
```
var_dump($catToUpdate->catsLinked);
```
With saving I mean:
```
$saved = Craft::$app->elements->saveElement($catToUpdate);
```

**Comment by brandonkelly** [comment]
Thanks, I see what’s going on. You just need to replace this line:

```php
$catToUpdate->catsLinked = $idsToLink;
```

with:

```php
$catToUpdate->setFieldValue('catsLinked', $idsToLink);
```

That will ensure that the new value gets normalized correctly, which needs to happen before the category is saved.

**Comment by pieter-janDB** [comment]
Thanks for the quick response Brandon,
This indeed fixed the problem.

Any explanation why repeating the category query...
```
$catToUpdate = Category::find()
        ->id(1962)
        ->one();
```
... just before I used the wrong syntax & save ...
```
$catToUpdate->catsLinked = $idsToLink;
$saved = Craft::$app->elements->saveElement($catToUpdate);
```
... seems to do the same thing? Categories look like they are linked perfectly and I can use them like expected.

Also Is this the way every field should be set in a craft 3 module?
Is this still valid? :
```
$catToSave = new Category();
$catToSave->groupId = $catGroupId;
$catToSave->title = $title;
$catToSave->enabled = true;
$saved = Craft::$app->elements->saveElement($catToSave);
```
Or should we use setFieldValues for every kind of fieldtype?

Thanks!

**Comment by brandonkelly** [comment]
Field values go through a normalization process before being handled. For example you will notice that if you call `var_dump($catToUpdate->catsLinked)` immediately after fetching the category, you will get a `CategoryQuery` object. And if you update the field value (with `setFieldValue()`) and then `var_dump()` it, you will still get a `CategoryQuery` object, even though you set it to an array.

Elements (such as this category) keep track of whether each field has been normalized yet or not. When you first load the category, none of its field values have been normalized yet. But once you’ve accessed a field value, it will get normalized before being returned.

So when you do this:

```php
$catToUpdate = Category::findOne(1962);
var_dump($catToUpdate->catsLinked);
```

Now the category remembers that `catsLinked` has been normalized. If you then edit the field value directly, setting it to an array, the category won’t realize that the value had been updated, leading to the error you were getting, where something further down the line was expecting a `CategoryQuery`.

It works correctly if you don’t even access `$catToUpdate->catsLinked` before saving the category, because in that case, the category knows the value has not been normalized yet, so it will go ahead and normalize it before saving.

So that’s why you should always set field values using `setFieldValue()` / `setFieldValues()`. Internally, that method will also let the element know that the value needs to be normalized (again).
