### ISSUE TITLE
rememberedUsername twig variable is throwing error

### ISSUE THREAD

**Issue by rostockahoi** [craftcms/cms#5291]
### Description
This is urgent for my client's application. I fixed it by overriding the `UserSession.php` file in the vendor folder which is no fun.

`craft.session.rememberedUsername` Twig variable is throwing an error if there is no username to be remembered. It works if
a) a user is logged in
b) a user has been logged in on the same browser within the `rememberUsernameDuration`

## Error message
`Return value of craft\web\twig\variables\UserSession::getRememberedUsername() must be of the type string, null returned`

### Steps to reproduce
1. Create bare template with
```
{{ craft.session.rememberedUsername }}
```
2. Open up template in browser
3. If you are or have been logged in there is your username.
4. Open up dev tools and clear the browser storage in Application tab.
5. Reload the page

### Solution
In `web/twig/variables/UserSession.php` change
```
    /**
     * Returns the remembered username from cookie.
     *
     * @return string
     */
    public function getRememberedUsername(): string
    {
        Craft::$app->getDeprecator()->log('craft.session.getRememberedUsername()', 'craft.session.getRememberedUsername() has been deprecated. Use craft.app.user.rememberedUsername instead.');

        return Craft::$app->getUser()->getRememberedUsername();
    }
```
to something like this depending of what the template should receive, string only or string|null
```
    /**
     * Returns the remembered username from cookie.
     *
     * @return string
     */
    public function getRememberedUsername(): string
    {
        Craft::$app->getDeprecator()->log('craft.session.getRememberedUsername()', 'craft.session.getRememberedUsername() has been deprecated. Use craft.app.user.rememberedUsername instead.');

        $rememberedUsername = Craft::$app->getUser()->getRememberedUsername();

        return $rememberedUsername !== null ? $rememberedUsername : "";
    }
```

### Additional info
- Craft version: tested on 3.3.11 and 3.3.16.3
- PHP version: 7.2.22
- Database driver & version: MySQL 5.7.21

**Comment by rostockahoi** [comment]
Also tested on another Craft instance with 3.3.16.3/PHP 7.2.15

**Comment by brandonkelly** [comment]
Fixed this for the next release.

Note that that method has been deprecated. If you update your template to call `craft.app.user.rememberedUsername` instead, you won’t get the error.

**Comment by rostockahoi** [comment]
Thanks for the quick help :+1: I'll update it to the current implementation.
