### ISSUE TITLE
actionGenerateTransform Error Handling

### ISSUE THREAD

**Issue by lukebailey** [craftcms/cms#5292]
### Description
Our security scanning solution (Detectify) has identified that certain calls to  actionGenerateTransform is throwing the following server errors. Would it be possible to handle these more gracefully, especially in a production environment, by perhaps throwing a 404 instead of a 5XX? This would prevent warns from our hosting envionrment that there are a high number of server errors when actually there is no issue that can be resolved. 

### Steps to reproduce (URL's that throw 5XX errors)

1. index.php?p=actions/assets/generate-transform&transformId=14758f9d{!1}{!2!}{x}0e13 throws a 500 error with 'A non well formed numeric value encountered'
2. index.php?p[1]=actions/assets/generate-transform&transformId=1475 causes an internal server error not handled by Craft's error page.
3. index.php?p=actions/assets/generate-transform&transformId='");|]]]]]]]]]#^($!@$)(()))******{\n<\0><!— cause a Type error and a 500 response.

### Additional info

- Craft version: 3.3.15
- PHP version: 7.2
- Database driver & version: MySQL

**Comment by brandonkelly** [comment]
Thanks for pointing those up. Just fixed `2` for the next release. The errors in `1` and `3` are coming from Yii internals though, so I’ve submitted yiisoft/yii2#17702 with a fix for those.

**Comment by brandonkelly** [comment]
That PR has been accepted, so this will be fully resolved whenever Yii 2.0.31 is released.

**Comment by lukebailey** [comment]
Looks like Yii 2.0.31 has been released now: https://github.com/yiisoft/yii2/releases/tag/2.0.31. Can we expect this in the next release of Craft?

**Comment by brandonkelly** [comment]
Done: 03577c4edcf15c55815a27a94715ee7a822eaba7

**Comment by brandonkelly** [comment]
Craft 3.3.19 is out now with that Yii update.
