### ISSUE TITLE
Display image dimensions in assets browser

### ISSUE THREAD

**Issue by chris-ca** [craftcms/cms#5294]
### Description
There is no way to display the physical dimensions (width, height) of an image in the asset browser.

This would be useful to determine if images meet certain minimum quality requirements. Generally it would be great if other EXIF data (location etc.) could be shown as well.

### Additional info

- Craft version: 3.3.15

**Comment by brandonkelly** [comment]
You can see the dimensions by clicking on the cog icon below the list of volumes on the Assets index page, and ticking the “Image Size” checkbox.
