### ISSUE TITLE
Ensuring data integrity when propagating matrix field content across sites

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/cms#5295]
I have a multi-site setup with matrix fields that have their propagation set to `Save blocks to all sites the owner element is saved in` which need changing to `Only save blocks to the site they were created in`

The issue is that after doing so all of the sites except for the one in which the matrix fields were initially created, no longer have content for this field. This is a major issue for us as it affects a considerable amount of content across thousands of entries.

I would have expected the matrix field's content to be re-saved for each site, ensuring data integrity across all sites.

Is this expected behaviour? If so, what is the suggested solution for ensuring data integrity when making this change? I'm struggling to see where a loss of data would be acceptable in this situation.

Thanks.

- Craft version: 3.3.16.3

**Comment by brandonkelly** [comment]
It’s a little complicated – multi-site elements (such as Matrix blocks) have a single element record with multiple content records, and when you change that setting, you are telling the blocks to only store a single content record, for the one site that the blocks were created in. So it is expected that those other content records would be discarded as a result of this change.

That said, I realize it’s not what most people would anticipate happening, so I do plan to “fix” this by duplicating existing Matrix blocks for the sites that are getting discarded, as part of the process of changing that setting. You can follow along at #5182.

**Comment by lukeyouell** [comment]
@brandonkelly great to hear that this is going to be addressed in 3.4

What would you suggest I do for now?

We have a situation where we have the same matrix blocks across all sites, but each matrix block contains translatable fields, so even though each site shares the same matrix blocks, they display translated content. We need to have this content propagate across each site, so that each matrix field can be managed on a per-site basis (no longer sharing matrix blocks) - we just can't afford to be losing this translated data when the field propagation method is changed.

How could I 'force' the content to propagate as mentioned, instead of losing data?

**Comment by brandonkelly** [comment]
Just went ahead and implemented #5182 for the next 3.3 release. It’s a bigger change than I’d prefer to make this far into a minor release, but since it is preventing unexpected data loss, seems worth it.

To get the change early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#daa4f2119cee2676cbc60d584da4203a2c1c0587 as 3.3.17",
  "...": "..."
}
```

Then run `composer update`.

Make sure you wait for the “Applying new propagation method to Matrix blocks” job to complete before updating existing entries; otherwise the blocks won’t get duplicated correctly.

**Comment by lukeyouell** [comment]
@brandonkelly this is great and works well, the only issue is that the "Applying new propagation method to Matrix blocks" isn't triggered during deployment. So once `project-config/sync` is run, entries are re-saved before propagation causing the loss of data as described above. 

I would expect these field changes to trigger propagation **before** resaving the entries, at the moment the propagation jobs aren't triggered at all.

**Comment by brandonkelly** [comment]
@lukeyouell Doh, you’re right. Just fixed that for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#4d3884ee88f5e6c64b433ce1b9889ea954fd735f as 3.3.19",
  "...": "..."
}
```

Then run `composer update`.

**Comment by lukeyouell** [comment]
Ace. Thanks Brandon!
