### ISSUE TITLE
This plugin isn't compatible with your version of Craft

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#5299]
### Description

Since updating to Craft 3.3.16.3, all plugins i the Plugin Store are unavailable with this message:

![image](https://user-images.githubusercontent.com/1250017/70038919-b94e2880-15c1-11ea-9bb9-4127439f168e.png)

**Comment by mtnorthrop** [comment]
Same for me. I see this on my in-development sites that are running under a Craft Pro trial license, but I checked one of my live sites that has a paid license and I'm not seeing this issue.

**Comment by kristiansp** [comment]
I have a valid license, and still see the issue

**Comment by rickmerkelbach** [comment]
Same issue here on all our 3.3.16.3 Craft sites (tried 5 so far). Installing through composer (and activating the plugin through the Control Panel) still works.

**Comment by brandonkelly** [comment]
This is fixed now. It was a bug on the Plugin Store API’s end, so nothing you need to update. Sorry about that!
