### ISSUE TITLE
Testing/Querying for "empty" not documented

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#5300]
Testing for empty field values (`Element::isFieldEmpty`), as well as filtering `ElementQuery` via `:empty:`/`:notempty` does not seem to be in the docs.

Which Should this be expected to work on any field type?

**Filtering ElementQuery**

Should these be expected to work, regardless of the field type?
I suspect the `search` method might only work if that field is defined as searchable?

```
$entries = Entry::find()->myField(':notempty:');
$entries = Entry::find()->myField(':empty:');
$entries = Entry::find()->search('-myField:*');
$entries = Entry::find()->search('myField:*');
```

**Field Values**

Is there a canonical way to test for empty on a field (regardless of field type?)

`Element::isFieldEmpty` seems like the right thing here?

```
$entry->isFieldEmpty('myField');
```

…is also appears there may be support for something like (via Element::__call):

```
$entry->isFieldEmpty:myField();
```

Old reference: https://github.com/craftcms/cms/issues/2270

**Comment by brandonkelly** [comment]
`isFieldEmpty()` is used for Required field validation, but technically unrelated to `:empty:` / `:notempty:`.

We’ve documented `:empty:` / `:notempty:` usage where appropriate in the field type docs, e.g. https://docs.craftcms.com/v3/assets-fields.html#querying-elements-with-assets-fields . If you think we are missing something feel free to post an issue/PR over at https://github.com/craftcms/docs.

**Comment by timkelty** [comment]
Thanks @brandonkelly, I knew it was in there somewhere (didn't play nice with the Algolia results)
<img width="609" alt="Screen Shot 2019-12-04 at 7 36 50 AM" src="https://user-images.githubusercontent.com/18329/70143156-e1449700-1668-11ea-8130-0cae7f86f35d.png">

I guess I'm after a documented/condoned way to check for empty on a field value, which internally at least, looks like `isFieldEmpty()`. I'll open an issue in the right place this time :)
