### ISSUE TITLE
Close Live Preview button translation broken

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#5301]
### Description

When opening Live Preview, its close button says "Close Preview". But no translation file contains "Close Preview" - instead they all have "Close Live Preview". This results in this button not being translated.

### Steps to reproduce

1. Use a non-english language
2. Open Live Preview

### Additional info

- Craft version: 3.3.16.3
- PHP version: 7.3.11
- Database driver & version: PostgreSQL 11.5
- Plugins & versions: -

**Comment by brandonkelly** [comment]
We’ll get this fixed when we order new translations for Craft 3.4.

**Comment by angrybrad** [comment]
Fixed in code [here](https://github.com/craftcms/cms/commit/4f8adfc15633c5c65ded822067b688282f338022) and translation will be updated for 3.4.
