### ISSUE TITLE
Matrix field: "This field is translated for each site" is shown instead of "This field is translated for each site group"

### ISSUE THREAD

**Issue by benface** [craftcms/cms#5304]
### Steps to reproduce

1. Create multiple sites across multiple site groups.
2. Create a Matrix field with the propagation method "Save blocks to other sites in the same site group".
3. Add the Matrix field to a Global set.
4. Go to the Global set, and hover the "translatable" icon next to the field's label.

Expected result: A tooltip appears with the text "This field is translated for each site group".
Actual result: A tooltip appears with the text "This field is translated for each site".

### Additional info

- Craft version: 3.3.16.3
- PHP version: 7.3.8
- Database driver & version: MySQL 5.7.26

**Comment by brandonkelly** [comment]
Good catch. The fix was a little involved so I made the changes on the 3.4 branch.
