### ISSUE TITLE
Translate system messages when using custom html template

### ISSUE THREAD

**Issue by stenvdb** [craftcms/cms#5308]
### Description
When setting the 'HTML Email Template' setting, it seems the language always defaults to the site default (unless you're logged in, and the user has a `{{ user.prefferedLanguage }}`. I tested this in my email template using the `{{ craft.app.language }}`, because I noticed that is being set in the Mailer class https://github.com/craftcms/cms/blob/develop/src/mail/Mailer.php#L108

### Steps to reproduce

I tested with a front-end change email form (with a logged in user of course). Submitted the form in 2 sites (the 2 sites each have a different language). In the email template `{{.craft.app.language }}` always defaults to the default site's language.

### Additional info

- Craft version: 3.3.6
- PHP version: 7.2
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
What is the user’s preferred language? Is it set to the same language as the primary site?

**Comment by stenvdb** [comment]
When I'm logged in as an admin user, the preferred language of my account (the one that overrides https://docs.craftcms.com/v3/config/config-settings.html#defaultcplanguage). 

Maybe an extra variable could be passed besides `emailKey, fromEmail & fromName` that holds the language? Kind of like we have `{{ order.orderLanguage }}` in commerce?

**Comment by brandonkelly** [comment]
> When I'm logged in as an admin user, the preferred language of my account (the one that overrides https://docs.craftcms.com/v3/config/config-settings.html#defaultcplanguage).

So… what exactly is the user account’s preferred language?

**Comment by stenvdb** [comment]
What do you mean? In my case 'en-US'

<img width="245" alt="Screenshot 2019-12-06 at 09 30 36" src="https://user-images.githubusercontent.com/362222/70308236-14bf2700-180b-11ea-97e5-83a08b54fe33.png">

**Comment by brandonkelly** [comment]
In that case, emails sent to you should have the language `en-US`, and that's what `craft.app.language` should be set to within the HTML emails template as well. Is that what you are seeing?

**Comment by stenvdb** [comment]
Umm but the main problem is that when I'm logged in as a frontend user (not an admin, hence no preferred language is set), it always defaults to the default site language here.

**Comment by brandonkelly** [comment]
Gotcha, that’s what I was trying to understand – the preferred language of the logged-in user when the email is sent.

If the user doesn’t have a preferred language, then a default is chosen depending on whether it’s the email is being sent from the Control Panel or the front-end.

- If it’s a Control Panel request, then the primary site’s language will be used.
- If it’s a front-end request, then the requested site’s language will be used:

https://github.com/craftcms/cms/blob/a6d67d9a4317a0ac338cfddb2abd7a4fa78678a9/src/mail/Mailer.php#L90-L95

Does that clear things up?

**Comment by stenvdb** [comment]
Ah, this is making things clearer yes. Turns out, when submitting through ajax the requested site's language doesn't come through. When I submit the form wirthout ajax, then it is working.

So to summarize:

I'm submitting a front-end `users/save-user` form, logged in user that has no cp permissions. Submitting with ajax -> `Craft::$app->getRequest()->getIsSiteRequest()` is `true`, but `Craft::$app->language` always defaults to the default site's language. When I disable ajax on the from, then it's working as expected.

Can you look into this @brandonkelly?

**Comment by brandonkelly** [comment]
It shouldn’t matter whether the request is over Ajax or not; you probably just need to make sure the Ajax request is pointed to the base URL of the appropriate site.

**Comment by stenvdb** [comment]
Gotcha, did not know that. From now on I'm gonna start including this in my forms per default:
`action="{{ alias(currentSite.baseUrl) }}"`

Thanks for clearing this out @brandonkelly!

**Comment by brandonkelly** [comment]
Sure thing! Glad it’s working for you.

**Comment by brandonkelly** [comment]
By the way, you could simplify that to just `{{ siteUrl() }}`.
