### ISSUE TITLE
How do you query for all Single type entries?

### ISSUE THREAD

**Issue by ryanpcmcquen** [craftcms/cms#5311]
### Description

I would expect something like this to do it:

```php
Entry::find()
    ->type('single');
```

But it does not.

**Comment by brandonkelly** [comment]
The `type` param is the _entry type_ handle, which is only really relevant for sections with multiple entry types (not singles).

You could either hard-code all of the Single section handles to the `section` param:

```php
Entry::find()
    ->section(['sectionA', 'sectionB']);
```

Or if it needs to be dynamic, best to set the `sectionId` param instead:

```php
use craft\helpers\ArrayHelper;
use craft\models\Section;

// ...

$singleSections = ArrayHelper::where(\Craft::$app->sections->getAllSections(), 'type', Section::TYPE_SINGLE);

Entry::find()
    ->sectionId(ArrayHelper::getColumn($singleSections, 'id');
```
