### ISSUE TITLE
[FR] Maximum image width/height - Twig function for image transforms

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#5314]
When i want to crop image to specific width/height, or keep its size if image is not big enough, i use transform settings like this:

```
{
            width: image.width > 1100 ? 1100 : image.width,
            height: image.height > 1100 ? 1100 : image.height,
}
```
I think it could be simplified a bit with custom twig function that would work like this:

```
{
            width: maxWidth(image, 1100),
            height: maxHeight(image, 1100),
}
```

**Comment by brandonkelly** [comment]
There is already a [max()](https://twig.symfony.com/doc/2.x/functions/max.html) Twig function you can use:

```twig
{
            width: max(image.width, 1100),
            height: max(image.height, 1100),
}
```

We will soon be adding an `upscaleImages` config setting, which can be set to `false` (and will be set to `false` by default for new installs), to prevent Craft from ever upscaling images when generating transforms – see #844.
