### ISSUE TITLE
InvalidConfigException when importing db

### ISSUE THREAD

**Issue by somethingconcon** [craftcms/cms#5316]
### Description
I've imported a database from our production system down into the staging environment we have setup for our developers.  When attempting to add a widget the user sees an "internal server error".

The log of this is:
`2019-12-06 09:50:32 [-][11022][lre4mmfn49vt1fsj9p75sgsmbi][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: Invalid author ID: 17129`

### Steps to reproduce

1. export db from production using craft UI
2. import into staging environment using mysqld cli
3. I went to the dashboard that was blank. I clicked New Widget > Recent Entries and hit save.
4. internal server error

### Additional info

- Craft version: 3.1.29
- PHP version: 7.2

**Comment by brandonkelly** [comment]
Can you try updating to the latest Craft version? We’ve fixed a couple similar bugs.

**Comment by somethingconcon** [comment]
thanks!
