### ISSUE TITLE
Plugin store: cart not found

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#5318]
### Description
Launching a site today and when I wanted to purchase the licenses from the plugin store in the CP I noticed that the loader for the cart kept on spinning.

When looking at the requests the page is making, this one is probably cause that:

GET https://api.craftcms.com/v1/carts/5a8a37d65bce91df6882cc8a2b46b10b, which 404's with `{"message":"Cart Not Found"}`.

The staging install of the site has the same problem, so I tried deleting the license.key to see if that would fix it but the request returns a 404 again.

Clearing Control Panel resources & data caches doesn't fix it, so it looks like something on that API's end.

### Additional info

- Craft version: 3.3.17
- PHP version: 7.3.12
- Database driver & version: 5.7.28

**Comment by benjamindavid** [comment]
Hey @janhenckens, could you please try to clear your browser’s local storage for that website?

**Comment by janhenckens** [comment]
@benjamindavid That fixed it!

**Comment by benjamindavid** [comment]
Great! Just fixed that issue for the next Craft release, thanks for the feedback.
