### ISSUE TITLE
FR: Trigger JS event on Matrix block deletion

### ISSUE THREAD

**Issue by rungta** [craftcms/cms#5329]
### Description

We have a matrix field to build a list with a block type called “Step #". We’re using JS to replace the `#` in the block title with the list item’s sequence number and make it read “Step 1", "Step 2" etc. We’re able to keep these sequence numbers in sync by listening to the `blockAdded` and `sortChange` events, but they fall out of sync if a block (that is not the last) is deleted. Is it possible to also trigger an event when a block is deleted?

![matrix blocks list](https://user-images.githubusercontent.com/663677/70703070-52cdb680-1cf5-11ea-8f12-5dfc688dfded.png)

### Additional info

- Craft version: 3.3.17
- PHP version: 7.2

**Comment by brandonkelly** [comment]
Just added a `blockDeleted` event for the next Craft 3.4 Beta release.

```javascript
$('#my-matrix-field').data('matrix').on('blockDeleted', function(event) {
    console.log(event.$block);
});
```
