### ISSUE TITLE
FR: Allow plugins and modules to exclude/include tables from backups

### ISSUE THREAD

**Issue by ostark** [craftcms/cms#5330]
Plugins may store massive temp data in the database, similar to the `Table::TEMPLATECACHES`.
Excluding those tables from backups helps to keep backups small.

The plugin author knows best if the data in the table is needed or not. Additionally, in some scenarios, a full backup is desired.  

By storing the ignoredTables in a public property, plugins or modules would be able to control this list of tables via `Connection::EVENT_BEFORE_BACKUP`. 

Like this: 
https://github.com/ostark/cms/commit/d293a4db26efbd6c4deaaefe14b8244e0b54b65c

**Comment by bencroker** [comment]
This would be very useful (and was in Craft 2), however I'n not sure it is possible with the current implementation of database backups.

> Craft 3 did away with PHP based backups and now uses mysqldump and pg_dump respectively.

https://github.com/craftcms/cms/issues/1844

**Comment by bencroker** [comment]
Just looked at your fork and the current implementation and see that it is absolutely possible! This would be extremely useful to have for plugins such as Blitz which has large tables that, like`Table::TEMPLATECACHES`, make no sense to include in a database backup.

**Comment by brandonkelly** [comment]
Just added a new `$ignoreTables` property to `craft\events\BackupEvent`, which plugins can add more tables to.

```php
use craft\db\Connection;
use craft\events\BackupEvent;

Craft::$app->db->on(Connection::EVENT_BEFORE_CREATE_BACKUP, function(BackupEvent $e) {
    $e->ignoreTables[] = '{{%mytablename}}';
});
```

**Comment by ostark** [comment]
@brandonkelly Played with this approach as well, but found it too complicated. IMO the whole backup context should be separated, but that's a different story.

**Comment by bencroker** [comment]
Lovely, thanks!
