### ISSUE TITLE
Category Live Preview Doesn't Show Up When Template Doesn't Exist

### ISSUE THREAD

**Issue by tjdraper** [craftcms/cms#5331]
### Description

I'm setting Category Routes via this basic method outlined by @brandonkelly here: https://github.com/craftcms/cms/issues/2450#issuecomment-366561434

This works fine on entries as I have no problem with live preview with entries routed via this method. However, with categories, the live preview buttons do not appear if the template path is not "valid" (i.e. there appears to be a `file_exists` check happening for categories that doesn't happen for entries). This is causing some problems with the afore mentioned routing method.

It's unclear to me if this is somewhat related to the fact that categories don't have preview targets. I don't have to set preview targets in entries when routing via this method in order for live preview to work. However, maybe it's because categories aren't using the whole preview target code path? I'm speculating at this point.

### Steps to reproduce

1. Enter a route in the template field of a category that you intend to route to a controller (in my case, an example is `_classRoute/app-module/service-category/render`).
2. Load a category edit (or create new) page in the CMS and observe that the live preview buttons do not appear on the category.

### Additional info

- Craft version: 3.3.18.1
- PHP version: 7.2.20
- Database driver & version: MySQL 5.7.27

**Comment by brandonkelly** [comment]
Yeah that would have been a limitation for entries as well, before Craft 3.2 when preview targets were added. Just point the value to any actual template path (even a blank value should work if you have a root `index.twig` / `index.html` template).

**Comment by tjdraper** [comment]
> Just point the value to any actual template path

This doesn't work based on the information I provided because I'm checking on `_classRoute` as the beginning of the route to know whether to set the route based on our discussion here: https://github.com/craftcms/cms/issues/2450#issuecomment-366561434

Maybe I'm missing something about what you're saying I need to do.

**Comment by brandonkelly** [comment]
Ah ok, I thought you were just hardcoding the route in the event handler. Would you be able to do that?
