### ISSUE TITLE
Project config fails to add fields to entry field layout

### ISSUE THREAD

**Issue by dlindberg** [craftcms/cms#5332]
### Description

Using the 3.4.0 beta, project config sync works to successfully create / change fields. However, it fails to add fields to the entry type field layout.

### Steps to reproduce

1. With project config sync enabled
2. Create a backup of the site.
2. Add a field (I've tried this with both third party (Super Table) and first party (light switch))
3. Tested with both using the auto generated `config.yaml` and using `./craft project-config/rebuild`.
4. Delete and restore database to pre field addition state from backup.
5. Run `./craft project-config/sync`
6. New fields that have been created / altered appear correctly.
7. Fields added to a field layout will not appear.

### Additional info

- Craft version: 3.4.0-beta 3
- PHP version: 7.1.30
- Database driver & version: MySQL 5.7.26
- Plugins & versions: Super Table 2.3.1 is plugin mentioned above. (Several additional plugins are installed, I can re-test with all disabled if necessary.)

From the `.config.yaml` changes it looks like they are getting written properly:

<img width="799" alt="image" src="https://user-images.githubusercontent.com/684461/70732863-391d7680-1cd7-11ea-9279-0258f814f3c1.png">

**Comment by andris-sevcenko** [comment]
Can reproduce and traced it down. Now just trying to figure out how to fix it :)

**Comment by andris-sevcenko** [comment]
This was fixed in 1997e82d0779b66a5edc1195c833b8e3ed30fac6 and will be a part of the next release.
