### ISSUE TITLE
[Request] Ability to clear PHP opcache from CLI

### ISSUE THREAD

**Issue by zizther** [craftcms/cms#5334]
For instances where CI is being used for deployments and Craft won't reset opcache because it is within a pipeline and not the server, it would be good to to be able to do this through the CLI so that a separate file does not need to be requested to do it, or reloading php-fpm for instance.

This would be a manual call to the same service as when Craft currently resets opcache after composer install/uninstall

**Comment by brandonkelly** [comment]
The opcache used for web requests isn’t available to Craft on CLI requests, so this isn’t really possible. Your best bet is probably to just call `service php-fpm reload`.

**Comment by zizther** [comment]
My suggestion was, it would be good if it could be, it is great we are able to do so much via the CLI at the moment, and it would be great to add to it and keep commands being managed through a central place, rather than having to do something like reload php-fpm, curl a URL, or even browser a page to do the same thing.

Not all servers run the same, and it feels neater to be able to just reset and manage opcache rather than having to use reloads which is doing more than just touching opcache.

If this is already built into Craft it feels like it would be suitable to make it available via the CLI.

**Comment by brandonkelly** [comment]
I get that but it’s not possible, at least without cURL’ing a web request from the CLI, which is hacks and not something I’m interested in.

**Comment by zizther** [comment]
Fair enough.
I wouldn't want to find a hack solution for this.
Thanks

**Comment by narration-sd** [comment]
@zizther  in noticing this, can't help but think back to Shell scripts, as these were invented in the day for just these sort of adminstrative smoothings.

Craft's provided CLI should be ideal for use in these, so you can arrange single, safely permitted commands to handle all your needs for cache breaking in the CI reload, or any other such multiple-call purposes.
