### ISSUE TITLE
Focus to field when selecting an environment variable/alias

### ISSUE THREAD

**Issue by bertoost** [craftcms/cms#5338]
### Description

For example at creating an Assets Volume, you can enter an public URL and system path. These fields showing an auto-complete with env variables and/or aliases.
After clicking one, the focus is not set in the field. Would be nice so you can continue typing immediately after the selected variable/alias.

### Additional info

- Craft version: 3.4-beta.3
- PHP version: 7.3.10
- Database driver & version: mysql 8.0
- Plugins & versions: none (fresh install)

**Comment by brandonkelly** [comment]
You can’t append additional stuff to an environment variable name, but you can with aliases, so I’ve just updated the autosuggest field to reset the focus on the input _if they selected an alias_. That made it into 3.3.18.2, and it will be included in the next 3.4 Beta release as well.
