### ISSUE TITLE
Cannot select 'section', redirects to entry types

### ISSUE THREAD

**Issue by JayBox325** [craftcms/cms#5339]
### Description
I can no longer access a section details/config view because the link for my 'pages' or 'blog' sections automatically link to the entry types meaning I can no longer edit template paths or page urls.

### Steps to reproduce

1. Click on a section
2. See entry types, not config.

### Additional info

- Craft version: 3.4.0-beta.3

**Comment by brandonkelly** [comment]
We just got that fixed for the next 3.4 Beta release. Thanks for reporting!
