### ISSUE TITLE
using data fixtures to populate database in all environments (not only test)

### ISSUE THREAD

**Issue by maxperei** [craftcms/cms#5341]
### Description

hi there,

maybe there's a misunderstanding of what a fixture is, but in my mind it could be used (as well as migrations) to store default data when initializing an app

it looks good within codeception (ie. usersFunctionalCest.php), so fixtures are properly loaded and can also be tested but when i try to run `./craft fixture/load UsersFixture` it throws a
___
**yii\base\InvalidConfigException** with message 'Invalid fixture namespace: "fixtures". Please, check your FixtureController::namespace parameter'
___
i intentionally changed the namespace parameter to match data under *tests/fixtures/* but i feel that something is wrong

should i use migrations instead ? it will load fixtures anyway ??

thanks everyone

### Steps to reproduce

1. set up a test environment
2. create at least one fixture in the right folder
3. add psr-4 element targeting your fixtures namespace in **composer.json**
4. run `composer dump-autoload`
5. run `./craft fixture/load *`

### Additional info

- Craft version: 3.3.15
- PHP version: 7.2.14
- MySQL version: 5.7.24

**Comment by brandonkelly** [comment]
Fixtures are a testing-specific concept. They get their name because they help create a _fixed_ environment for running tests.

We do have plans to give Craft a built-in content importer (see #994), at which point it would probably make sense to create a fixture class that can work with the same data files.
