### ISSUE TITLE
Craft 2.8.0: Unknown "uploadLocationInput" function

### ISSUE THREAD

**Issue by joespiteri** [craftcms/cms#5343]
### Description
After updating to Craft 2.8.0, attempting to create or edit a field of any type produces the error: Unknown "uploadLocationInput" function 

<img width="1907" alt="Screenshot 2019-12-16 at 12 56 38" src="https://user-images.githubusercontent.com/13642527/70882873-b876b700-2003-11ea-8038-86190c283bb5.png">

### Steps to reproduce

1. Install Craft 2.8.0
2. Navigate to Settings > Fields > Click any field title to edit
3. Error 

### Additional info

- Craft version: Craft CMS 2.8.0
- PHP version: 5.6.40 and 7.1.31
- Database driver & version: MySQL 5.7.26

**Comment by brandonkelly** [comment]
Thanks for reporting that. We just released Craft 2.8.0.1 with the fix.
