### ISSUE TITLE
Craft::$app->elements->getElementById() crashes when passing the ID of a "ghost element"

### ISSUE THREAD

**Issue by benface** [craftcms/cms#5345]
### Description

This may not be considered a bug because perhaps it's code that should never run, but nonetheless it happened to me:

1. I installed the [Contact Form](https://plugins.craftcms.com/contact-form) and [Contact Form Extensions](https://plugins.craftcms.com/contact-form-extensions) plugins.
2. Users used the site's contact form to send messages, which were saved as elements by Contact Form Extensions.
3. I uninstalled and removed both plugins (replacing them with Freeform). Contact Form Extensions doesn't seem to clean up after itself, leaving all the elements it created in the database (probably on purpose, so we can reinstall it in the future and still have access to all messages that I received through it).
4. [A bug in the Relations plugin](https://github.com/Nav33d/craft-relations/pull/18) fetched all elements from the `elements` table and ran them through `Craft::$app->elements->getElementById()`.
5. I got this error when it reached one of the "ghost elements":
> Class 'rias\contactformextensions\elements\ContactFormSubmission' not found 
    /home/forge/colloquesims.com/vendor/craftcms/cms/src/services/Elements.php:305 craft\services\Elements::getElementById

Maybe it should return `null` or throw a specific exception instead of crashing?

### Additional info

- Craft version: 3.3.18.2
- PHP version: 7.3.8
- Database driver & version: MySQL 5.7.26

**Comment by brandonkelly** [comment]
Fixed now for the next release!

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#cbec576f5e7e3ae2fc76f7931a875601789d8f5b as 3.3.18.2",
  "...": "..."
}
```

Then run `composer update`.
