### ISSUE TITLE
Craft 2: PHP Warning: Declaration of Craft\BaseModel::setAttributes($values) should be compatible with CModel::setAttributes($values, $safeOnly = true)

### ISSUE THREAD

**Issue by timeverts** [craftcms/cms#5346]
### Description
We have a number of Craft 2 websites that are frequently logging the following PHP warning to the phperrors.log:

```
PHP Warning: Declaration of Craft\BaseModel::setAttributes($values) should be compatible with CModel::setAttributes($values, $safeOnly = true) in /.../craft/app/models/BaseModel.php on line 14
```
Unfortunately a backtrace is not being logged with the warning so I'm not certain of the originating code. However, I do see that in various Craft 2 app files there are calls to the `setAttributes()` method of a model derived from `BaseModel`. Plus we also have several internally developed Craft 2 plugins running on the sites that are executing `$myModel->setAttributes($attributes)`.

I see there is some discussion about a related issue in #2217, but just want to know whether those recommendations are applicable here too and/or whether Craft 2 will be updated to resolve this.

### Additional info

- Craft version: 2.7.5
- PHP version: 7.1.x
- Database driver & version: mySQL 5.7.14
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
Yeah unfortunately there’s nothing we can do to fix this in Craft 2 without breaking plugins. But it’s fixed in v3.
