### ISSUE TITLE
[3.4-beta.3] Scrolling issues on element indexes pages

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#5347]
### Description

On element index pages with a long list of sources that requires scrolling, and a shorter list of elements that does not, the element table scrolls out of the view port, and stays there when selecting an other source.

### Steps to reproduce

Example before scrolling: (On a side note: You can't see which source is selected)

![image](https://user-images.githubusercontent.com/25308802/70979849-9425e380-20b2-11ea-97f3-bbd8a658e0fa.png)

Scrolling down:

![image](https://user-images.githubusercontent.com/25308802/70979970-cb949000-20b2-11ea-84be-28874b9ef6e0.png)

This picture does not change when selecting an other source (e.g. Genre).

PS.
There's an unneeded horizontal scrollbar at the bottom.

### Additional info

- Craft version: 3.4.0-beta.3
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
The scrolling behavior is expected, since the sidebar and main content area are both just being scrolled as part of the window. The exception for that is, if the content area is taller than the sidebar, then the sidebar will get fixed-positioned before it is scrolled out of view (same for the right-hand details column, when present).

Fixed the horizontal scrollbar, though.

**Comment by wsydney76** [comment]
@brandonkelly Thanks for fixing the scrollbar, but hm...

That means in situations like in the second screen shot, when a user clicks a source at the bottom like Genre, what happens on the screen is: exactly nothing. You have to scroll up manually to see the entries.

Also comes into play if you have  asset volumes with a lot of nested subfolders, each containing only a few pics.  So scroll down to your folder, click, see nothing, scroll up, ups not the expected images, cant' see which folder i clicked , scroll down and try to find which folder is highlighted, find the correct folder, click again, see nothing, scroll up again....

I get this looks now better in most situations, but in others it seems to me like a significant step backwards regarding usability.

**Comment by brandonkelly** [comment]
I guess we could give the same optional-fixed treatment to the main content area if that’s the shorter thing.

**Comment by brandonkelly** [comment]
Just fixed this for the next Craft 3.4 release.
