### ISSUE TITLE
[3.4-beta.3] Server Error when saving or editing user group settings

### ISSUE THREAD

**Issue by handplant** [craftcms/cms#5348]
### Description
If I want to create or edit a user group ('action' => 'user-settings/save-group'), the following error occurs:

Internal Server Error
Server Error

The web.log then says:
Getting unknown property: craft\models\UserGroup::handle" in /vendor/yiisoft/yii2/base/Component.php:154

### Steps to reproduce

1. Go to /admin/settings/users
2. Create or edit a user group
3. Click Save

### Additional info

- Craft version: Craft Pro 3.4.0-beta.3
- PHP version: 7.2.14
- Database driver & version: MySQL 5.5.5

**Comment by andris-sevcenko** [comment]
Oops. Sorry about that. Just fixed that on the `3.4` branch so this will be fixed in the next `3.4` beta release.
