### ISSUE TITLE
[3.4-beta.3-next] No Schemas exist yet to assign this token

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#5349]
I'm using the `3.4.x-dev` branch so this is the latest. I updated a site from 3.3 to 3.4.x that had an existing Public Schema but no token beyond the `__PUBLIC__`:

![Screen Shot 2019-12-17 at 11 54 53 AM](https://user-images.githubusercontent.com/7570798/71017307-66499a80-20c4-11ea-80dd-149e260184ca.png)

So no problem I went to go create a token for it, but it claims no schemas exist:

![Screen Shot 2019-12-17 at 11 55 03 AM](https://user-images.githubusercontent.com/7570798/71017347-7497b680-20c4-11ea-8eee-d178ef0511c1.png)

If the public schema is intended to be treated specially, and this is working as intended... just noting that I found it confusing.

**Comment by khalwat** [comment]
Basically, I have a custom controller that is looking to return a specific GraphQL token to the frontend. If that token exists, it returns it. If it does not, it returns what was a constant in the `GqlSchemas` model, but now has moved to the `GqlTokens` model:

```php
    /**
     * The public access token value.
     */
    const PUBLIC_TOKEN = '__PUBLIC__';
```

Doing something like:

```php
    /**
     * @return Response
     */
    public function actionGetGqlToken(): Response
    {
        $result = '';
        $tokens = Craft::$app->getGql()->getTokens();
        foreach ($tokens as $token) {
            if (empty($result) && $token->getIsPublic()) {
                $result = $token->accessToken;
            }
            if ($token->name === self::GQL_TOKEN_NAME) {
                $result = $token->accessToken;
            }
        }

        return $this->asJson([
            'token' => $result,
        ]);
    }
```

This worked in 3.3 (minus the `GqlToken` class that didn't exist, but doesn't apparently in 3.4?

**Comment by andris-sevcenko** [comment]
For posterity - the public token is no longer a magic token to be used. The public schema will be used if no token is provided at all. Also, it is to be treated specially as in the public schema cannot be assigned to a token.
