### ISSUE TITLE
Relation "info" does not exist 3.4.0-beta.1

### ISSUE THREAD

**Issue by jlamb1** [craftcms/cms#5350]
### Description
Appears very similar to https://github.com/craftcms/cms/issues/4563

This can be tested out on a (*really* rough) boilerplate i'm working on here, going through the README steps: https://github.com/jlamb1/k8-craft

After setting up the environment, entering the php container with `kubectl exec -it php /bin/bash`, running `./craft {setup|install|setup/security-key}` etc. errors out with the following:

```
root@php:/var/www/html# ./craft setup
Exception 'yii\db\Exception' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "info" does not exist
LINE 2: FROM "info"
             ^
The SQL being executed was: SELECT "config"
FROM "info"
LIMIT 1'

in /var/www/html/vendor/yiisoft/yii2/db/Schema.php:674

Error Info:
Array
(
    [0] => 42P01
    [1] => 7
    [2] => ERROR:  relation "info" does not exist
LINE 2: FROM "info"
             ^
)

Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'SELECT "config"...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('SELECT "config"...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Command.php(425): yii\db\Command->queryInternal('fetchColumn', 0)
#3 /var/www/html/vendor/yiisoft/yii2/db/Query.php(291): yii\db\Command->queryScalar()
#4 /var/www/html/vendor/craftcms/cms/src/db/Query.php(197): yii\db\Query->scalar(NULL)
#5 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1436): craft\db\Query->scalar()
#6 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(360): craft\services\ProjectConfig->_getInternalConfigValue('system.timeZone')
#7 /var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php(1375): craft\services\ProjectConfig->get('system.timeZone')
#8 /var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php(1333): craft\console\Application->_setTimeZone()
#9 /var/www/html/vendor/craftcms/cms/src/console/Application.php(63): craft\console\Application->_preInit()
#10 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
#11 /var/www/html/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#12 /var/www/html/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#13 /var/www/html/vendor/craftcms/cms/src/console/Application.php(54): yii\console\Application->__construct(Array)
#14 [internal function]: craft\console\Application->__construct(Array)
#15 /var/www/html/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#16 /var/www/html/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('craft\\console\\A...', Array, Array)
#17 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(351): yii\di\Container->get('craft\\console\\A...', Array, Array)
#18 /var/www/html/vendor/craftcms/cms/bootstrap/bootstrap.php(244): yii\BaseYii::createObject(Array)
#19 /var/www/html/vendor/craftcms/cms/bootstrap/console.php(34): require('/var/www/html/v...')
#20 /var/www/html/craft(21): require('/var/www/html/v...')
#21 {main}
```

### Steps to reproduce

This is meant to be a quick setup to begin demoing, so it's a brand new install of craft. It can be fixed by downgrading:

- `minikube delete`
- dump composer.lock and vendor/
- set `craftcms/cms` version to `"^3.0.0"`
- composer install
- repeat steps in README
- entering the php container again and running `./craft install` will complete successfully

### Additional info

- Craft version: 3.4.0-beta-1
- PHP version: 7.4-fpm
- Database driver & version: postgres:11.5
- Plugins & versions:none

Dummy .env data (add to app/.env file before building containers):

```
DB_DRIVER="pgsql"
DB_SERVER="postgres"
DB_USER="craft3"
DB_PASSWORD="password"
DB_DATABASE="craft3"
DB_SCHEMA="public"
DB_PORT="5432"
DB_TABLE_PREFIX=""
```

It's a very early project so it's definitely possible there's something misconfigured in the environment, but it looks like there is something between 3.3 and 3.4 that causes a Yii exception on new setups (empty tables) in postgres:11.5

**Comment by jlamb1** [comment]
Just went through the [docker hub](https://hub.docker.com/_/postgres) tags and tried `12.1`, `11.6`, `10.11`, and `9.6.16` and got the same results.

Added composer to the php Dockerfile as well, so quicker iteration can simply be to enter the php container, try `./craft setup`, dump composer.lock and vendor, change craftcms/cms to `^3.0.0` composer install, and try `./craft setup` again.

Also came across this - potentially a Docker problem? https://craftcms.stackexchange.com/questions/33068/error-relation-info-does-not-exist

**Comment by jlamb1** [comment]
Got a bit farther on this, went through and compared 3.3.18.2 and 3.4.0-beta-1 composer.lock files

composer.lock has a new package [container-interop/container-interop](https://github.com/container-interop/container-interop) which;

"container-interop tries to identify and standardize features in container objects (service locators, dependency injection containers, etc.) to achieve interoperability."

It was deprecated Feb 13, 2017, in favor of `psr/container-implementation`

the craftcms/cms composer.json added mrclay/minify, which in turn calls mrclay/props-dic, which calls container-interop, possibly breaking containerized environments

**Comment by jlamb1** [comment]
This is confirmed fixed with mrclay/minify 3.0.7 release: https://github.com/mrclay/minify/issues/660#issuecomment-567079537

**Comment by brandonkelly** [comment]
What exactly does the minify fix have to do with the SQL error? Sounds more like there was no `info` table at the time the SQL statement was executed, which is just a normal ol’ Craft bug.

**Comment by jlamb1** [comment]
I think this came down to kubernetes service discovery. My best guess is the container-interop package was somehow interfering with my setup, Craft couldn't find the Postgres pod at `postgres:5432`, and the error of "does not exist" came back as it couldn't find or create the table.

I'm not 100% sure on it, but both `3.4.0-beta-1` as well as `3.4.x-dev` are working out of the box now. If I delete minify and explicitly install 3.0.6 the error returns on `./craft setup`

**Comment by brandonkelly** [comment]
Gotcha, alright cool. Well 3.4 Beta 5 is going to start requiring `mrclay/minify ^3.0.7`, so should be all good after that.
