### ISSUE TITLE
Ability to disable `loginPath` and `logoutPath`

### ISSUE THREAD

**Issue by benface** [craftcms/cms#5352]
On sites that don't have a front-end login form, it would be nice if we could disable `loginPath` and `logoutPath` altogether. It seems that setting them to `''` causes them to be triggered on the home page (which makes sense) and `null` is not allowed. It's a very minor annoyance, but when you're logged in on the CP and visit `/login` you are redirected to the home page instead of getting a 404 error like you should, and when you visit `/logout` you are logged out.

**Comment by brandonkelly** [comment]
I’ve just disabled those settings, as well as `setPasswordPath` and `verifyEmailPath`, if headless mode is enabled, for the next 3.4 Beta release.

**Comment by benface** [comment]
Ok, but I meant for a non-headless install. I was basically suggesting that setting those settings to `null` should disable them instead of throwing an error. :P

**Comment by brandonkelly** [comment]
Sorry, I completely missed the word “form” in “On sites that don't have a front-end login form” 🤦‍♂️

**Comment by benface** [comment]
Haha no problem, like I said it’s a very minor annoyance and I understand if you feel it is not worth the complexity to add it.

**Comment by brandonkelly** [comment]
Alright this is really resolved now, for the next 3.4 Beta release. You can now set `loginPath` / `logoutPath` to `false`, either globally or on a per-site basis, to disable those special paths.
