### ISSUE TITLE
Make it easier for headless apps to retrieve user/session/CSRF cookies

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#5355]
Suppose I have a headless Craft site, and I'm trying to render a simple widget to display the current user's username if logged-in, or a login link if logged out.

Ideally we wouldn't have to make an ajax request on every page to do this, as there is a username/identity cookie that is set on login.

However, these are encoded (with a key you wouldn't want exposed to client-side code), and http-only, so they can't be read with JS.

So, you're left with making an additional ajax request every render…only there is no "get current user" controller with anonymous access to get the information. Without writing you'r own, `UsersController::actionGetRemainingSessionTime` is as close as you can get, which can tell you if the user is logged in, but won't give you their username.

So…you can write your own anonymous controller that returns the username, fine.

You're still left with the trouble of CSRF tokens. Again, you don't want to have to keep retrieving these with AJAX requests, but you can't access the `CRAFT_CSRF_TOKEN` vis JS.

Any ideas how to make this less of a headache?

It seems like maybe a config option like `$encodeUserCookies = false` might makes sense?

This is could also be `true` by default when `$headlessMode = true`.

**Comment by jasonmccallister** [comment]
@timkelty if I am understanding you correctly, you could get around this by [disabling CSRF tokens](https://docs.craftcms.com/v3/config/config-settings.html#enablecsrfprotection). That does not solve the issue of getting or verifying a currently logged in user. That would probably require an API or customer controller like you mentioned.

**Comment by brandonkelly** [comment]
CSRF validation only applies to POST requests, not GET, so if you load your controller with a GET request, you won’t have to worry about it.

And individual controllers can also opt-out of requiring CSRF validation, like so:

https://github.com/craftcms/cms/blob/3.3.18.3/src/controllers/PreviewController.php#L42-L50

**Comment by brandonkelly** [comment]
Just added a new `users/session-info` controller action, that returns the same thing `users/get-remaining-session-time` did, as well as `isGuest` (`true`/`false`), and if the user is logged in, `id`, `uid`, `username`, and `email` keys will be returned as well.

**Comment by timkelty** [comment]
@brandonkelly that's great! Thanks.

**Comment by timkelty** [comment]
@brandonkelly I think you'll need to add `session-info` to `$allowAnonymous` :)

**Comment by brandonkelly** [comment]
Yep sorry, that's fixed now.
