### ISSUE TITLE
Templating on a per site base

### ISSUE THREAD

**Issue by jan-dh** [craftcms/cms#5356]
I'm reading up a bit on the multi-site setup and I found this in the docs:

> We recommend you have template directories named after the sites handles (e.g. templates/default and templates/beta). You store the site-specific templates in each site template directory.

[url](https://docs.craftcms.com/v3/sites.html#guide-setting-up-a-new-site)

This seems a bit of an odd approach, since multi-language sites often use the same specific templates but don't have the same handle. 

There is no currently no option available to define a template folder on a per site base. Consider this scenario, I have 5 sites, grouped liked this:
`Group 1: A, B, C`
`Group 2: D, E`

I would like to be able to assign a template root to Group 1, or to site A, B, C (on a site level). 

In my view the multi-site setup is very handy for a couple of scenario's:
1. you share a lot of data but you have a different root url's, templates styling, ..
2. you share a lot of styling but you have different content on a per site base
3. the combination of the first two.

The third option is quiet hard to pull of atm. The fact that locales have been made the same as a site, makes the handle-based approach a bit counter-productive.

**Comment by Mosnar** [comment]
Related #3101

**Comment by jan-dh** [comment]
Ah this might be a duplication yes. Sorry, looked for similar issues but didn't find them. I'll close this up and follow the other one.
