### ISSUE TITLE
GraphQL: How get a single element?

### ISSUE THREAD

**Issue by Jan10** [craftcms/cms#5363]
### Description
I want a single element/entry from the GraphQL-API instead of a list. How do I get it?
This would be possible in craft templates via one (): https://docs.craftcms.com/v3/dev/element-queries/#one

Example Query:
```javascript
query getProduct($slug: [String]!) {
    product: entries(section: "products", slug: $slug) {
      id    
    }
  }
```

Response:
```javascript{
  "data": {
    "product": [
      {
        "id": "8"
      }
    ]
  }
}
```

- Craft Version: Craft CMS 3.4.0-beta.4

Thanks

**Comment by andris-sevcenko** [comment]
Yeah, okay. We'll add that for 3.4, but that'll be an `entry` query, as opposed to `entries`.

**Comment by andris-sevcenko** [comment]
Just pushed this for the next Craft 3.4 release. You can now use the singular forms of the queries (`entries` -> `entry`) to return a single result.
