### ISSUE TITLE
[Feature Request] Add `slugify` Twig filter

### ISSUE THREAD

**Issue by benface** [craftcms/cms#5369]
I see that `craft\helpers\StringHelper::slugify()` has been added in Craft 3.3.0. It would be nice if it was available as a Twig filter.

**Comment by michaelrog** [comment]
FWIW — you can probably use the [`dasherize` filter from Wordsmith](https://wordsmith.docs.topshelfcraft.com/guide/casing.html#dasherize) until this gets added first-party.

**Comment by benface** [comment]
@michaelrog Thanks. Actually I use `|kebab|ascii` in the meantime.

**Comment by benface** [comment]
@brandonkelly Actually, it looks like `|kebab|ascii` does a better job at "slugifying" strings such as "Red/Green" (`red-green`) than `craft\helpers\StringHelper::slugify()` (`redgreen`).

**Comment by brandonkelly** [comment]
Yeah I don’t think we would call `StringHelper::slugify()` directly, as that is just a wrapper for the Stringy method, and not consistent behavior with actual slugs in Craft.

**Comment by brandonkelly** [comment]
Decided not to add this, in part because of the ambiguity with `StringHelper::slugify()`, but also because element slugs are more than just formatting; they are a means of identification, which I think would be diluted a little bit if we added a `slug` / `slugify` Twig filter.
