### ISSUE TITLE
GraphQL: FR: group/groupId Arguments for User Query

### ISSUE THREAD

**Issue by andrewmenich** [craftcms/cms#5374]
### Description
I was hoping to query for users within a specific user group. Unlike the normal twig user query, the GraphQL user query does not contain arguments for `group` or `groupId`.

Sorry if I'm missing something obvious here!

### Additional info

- Craft version:  3.3.18.1

**Comment by andris-sevcenko** [comment]
Thanks for noticing that! Added for the next Craft 3.4 beta release.
