### ISSUE TITLE
Add `.localhost` to list of dev domains

### ISSUE THREAD

**Issue by craftedsystems** [craftcms/cms#5382]
I like to develop with `<project>.localhost` domains in my dev environment. The resulting Craft control panel alert is not very pretty.  
Please add `.localhost` to the list of dev domains. Thx

**Comment by bertoost** [comment]
Maybe try using something other, like `.local` since that's already on the list?

https://craftcms.com/guides/how-craft-license-enforcement-works

**Comment by brandonkelly** [comment]
That should already work just fine, since `localhost` isn’t a registrable TLD. Try clearing your caches and then check for updates, and see whether the nag alert goes away.

**Comment by craftedsystems** [comment]
Thx, nag alert is gone.
