### ISSUE TITLE
Possibility to remove the "Logged in" flash notice message

### ISSUE THREAD

**Issue by bertoost** [craftcms/cms#5383]
### Description

When building a frontend login, you always get a "Logged in" message from the `UserController` (L 1639). Only when you submit by Ajax this is omitted. But I want to be able to disable this message also on normal form-login.
Since the user who logs-in sees when he is logged-in (since I mostly redirect to the referer or account page).
Would be nice to have an ability to disable this message somehow.

Currently I'm using this hacky solution

```php
$notice = Craft::$app->getSession()->getFlash('notice');
if (null !== $notice && $notice === Craft::t('app', 'Logged in.')) {
    Craft::$app->getSession()->getFlash('notice', null, true);
}
```

### Additional info

- Craft version: 3.3.18.4
- PHP version: 7.3.10 (fpm)
- Database driver & version: MySQL 8.0
- Plugins & versions: -

**Comment by brandonkelly** [comment]
Just completely removed that flash notice for Craft 3.4, as the control panel wasn’t even showing it to begin with, and there’s no similar notice on logout.

**Comment by bertoost** [comment]
Cool! even better.. if you want it back, you can hook in on the event 👍
