### ISSUE TITLE
[FR] new propagation method which doesn't propagate but you can select another enabled site on edit

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#5386]
i am thinking about a new propagation method that you can assign entry to one site and on edit of that entry you can assign to another site.

currently when craft cms creates an entry, you can edit that entry only for supported sites -which it varies depending on type of propagation method- and currently only workaround  is to set propagation method to 'save entry to all sites enabled for that section' and after create entry, disable entry for sites you currently don't need. - i can't set site default status in section setting because it differs for each entry of that section -

**-for use case** imagine an article section and entry type with 10 sites with different languages and i upload articles with different languages and their translations if there is any translation available 
for example
for first article i create the article in English site and assign that article to french site when translation is ready. 
for a persian article i upload article to persian site and publish it to other sites if translations for that article is available.

i think i can do this with a custom element type but i think this is nice to have this by craft cms and a new propagation method that it doesn't propagate but you can select from other enabled sites on edit.

**Comment by pdaleramirez** [comment]
Can we add an event hook on the `\craft\services\Elements::_saveElementInternal` right before propagation happens so that we can stop propagation on other elements as well. Such commerce products, variants and assets
