### ISSUE TITLE
revision menu button show unsupported site in drop down

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#5387]
**Description**
revision menu button show unsupported sites for some propagation methods

**Steps to reproduce**
1. enable 3 sites:
- en with en_US language
- en2 with en_us langauge
- fa with fa_IR language
2. set propagation method to "Save entries to other sites with the same language"
3.  add new entry in en language
4. go back to entry index page. select en language and go to edit page.
5. en and en2 are in revision menu list which is correct but fa is also in list which is not correct. if you select fa language you get entry not found error.
i kind of tracked the issue and it seems craft doesn't check unsupported Sites when create revision menu button [in this line](https://github.com/craftcms/cms/blob/d71c1f857a6357939d9f23e997ccc55a0a8a4be9/src/templates/_includes/revisionmenu.html#L64) and loop in all sites .

**Additional info**
- Craft version: 3.3.19
- PHP version: 7.2
- Plugins & versions: fresh install

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by benface** [comment]
@brandonkelly Looks like there's a small typo in the fix: `canEditMultilpeSites` instead of `canEditMultipleSites`

**Comment by brandonkelly** [comment]
Whoops, thanks for pointing that out. At least I was consistently wrong, so it didn’t break anything :)
