### ISSUE TITLE
[Feature Request] Enhance cacheability of element DB queries

### ISSUE THREAD

**Issue by rob-baker-ar** [craftcms/cms#5389]
### Description

Currently, default read based queries end up with something along the lines of:

```
`entries`.`expiryDate` > '2020-01-02 09:13:55'
```

This can make the query a bit less "cacheable" by the database engine as the query is different every second.

In the admin interface date based fields are set to a minute based precision. If there was a similar round to the minute in the code generating the database queries, there should be better database performance as a load of queries would then only change every minute, rather than every second.

This could / should be a configuration option rather than default behaviour.

If this is considered a reasonable idea, I could look into making a pull request.

### Additional info

- Craft version: 3.3.18.1
- PHP version: 7.2.24
- Database driver & version: MySQL 5.7.28
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
Agree the second precision in those queries was not necessary. I’ve just removed it for Craft 3.4.

**Comment by brandonkelly** [comment]
Doh, sorry about that. I’ve just brought back seconds-locking for the next release, but at `59` instead of `00` this time, so it doesn’t re-break #7853.

**Comment by rob-baker-ar** [comment]
That's great, many thanks.

As a side note that might be of interest to others, I have found that it's possible to make the query builder generate SQL that is even more cacheable: it's possible to stop dates appearing in a lot of entry queries like this:

```php
Entry::find()->status('enabled')->all()
```

Or

```twig
craft.entries.status('enabled').all()
```

`status('enabled')` overrides what would by default be `status('live')` and causes the code path to drop through the `switch` / `match` statement in `EntryQuery::statusCondition()` into the parent method which does not set any date based conditions on the query.

**It should be noted that, at the very least, functionality related to date based entry expiry or future `postDate` will in effect stop working with queries using this approach. As far as I can see, soft deletion would still be fine as the query is just checking for `null` in the `dateDeleted` column.**

**Comment by brandonkelly** [comment]
Craft 3.7.44 and 4.0.4 are out now with that change.
