### ISSUE TITLE
[3.4] Include a more prominent changelog notice for Record::__set normalization

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#5390]
> Active record classes now normalize attribute values right when they are set.

This line from the 3.4 changelog sounds fairly innocent, but can cause issues devs are encoding/decoding JSON and trying to manipulate the Record instance, as was happening here: https://github.com/craftcms/feed-me/pull/644

**Comment by brandonkelly** [comment]
Hm, _maybe_, but I kindof doubt any other plugins are trying to save denormalized values back onto records as a transport mechanism like this. Will wait and see…

**Comment by timkelty** [comment]
👍 someone searching that might find this issue is prob enough :)
