### ISSUE TITLE
users/get-remaining-session-time action Deprecation errors in 3.4.0-beta.5

### ISSUE THREAD

**Issue by jdsimcoe** [craftcms/cms#5392]
### Description

After upgrading to `3.4.0-beta.5` I get this error in the Deprecation Warnings:

```
The users/get-remaining-session-time action is deprecated. Use users/session-info instead.
```
Full stack trace:

```
11	Deprecation error: The users/get-remaining-session-time action is deprecated. Use users/session-info instead.
Called from /home/site_folder/vendor/craftcms/cms/src/controllers/UsersController.php:225
10	craft\controllers\UsersController::actionGetRemainingSessionTime()
9	call_user_func_array([craft\controllers\UsersController, "actionGetRemainingSessionTime"], [])
Called from /home/site_folder/vendor/yiisoft/yii2/base/InlineAction.php:57
8	yii\base\InlineAction::runWithParams(["p" => "admin/actions/users/get-remaining-session-time", "dontExtendSession" => "1"])
Called from /home/site_folder/vendor/yiisoft/yii2/base/Controller.php:157
7	craft\controllers\UsersController::runAction("get-remaining-session-time", ["p" => "admin/actions/users/get-remaining-session-time", "dontExtendSession" => "1"])
Called from /home/site_folder/vendor/craftcms/cms/src/web/Controller.php:187
6	craft\controllers\UsersController::runAction("get-remaining-session-time", ["p" => "admin/actions/users/get-remaining-session-time", "dontExtendSession" => "1"])
Called from /home/site_folder/vendor/yiisoft/yii2/base/Module.php:528
5	craft\web\Application::runAction("users/get-remaining-session-time", ["p" => "admin/actions/users/get-remaining-session-time", "dontExtendSession" => "1"])
Called from /home/site_folder/vendor/craftcms/cms/src/web/Application.php:299
4	craft\web\Application::runAction("users/get-remaining-session-time", ["p" => "admin/actions/users/get-remaining-session-time", "dontExtendSession" => "1"])
Called from /home/site_folder/vendor/craftcms/cms/src/web/Application.php:565
3	craft\web\Application::_processActionRequest(craft\web\Request)
Called from /home/site_folder/vendor/craftcms/cms/src/web/Application.php:278
2	craft\web\Application::handleRequest(craft\web\Request)
Called from /home/site_folder/vendor/yiisoft/yii2/base/Application.php:386
1	craft\web\Application::run()
Called from /home/site_folder/public/index.php:21
```

### Steps to reproduce

1. Upgrade to `3.4.0-beta.5`.
2. Go to Deprecation Warnings tag.

### Additional info

- Craft version: 3.4.0-beta.5
- PHP version: 7.3.13
- Database driver & version: MySQL 5.7.28

**Comment by brandonkelly** [comment]
Nothing in Craft calls that anymore. So either the updated JS files didn’t get loaded properly, or you have a plugin installed that is calling the `users/get-remaining-session-time` action.

Try deleting your `vendor/` folder and running `composer install`. Then clear your deprecation warning logs, and see if it comes back again. If so, most likely it is happening due to a plugin.

**Comment by jdsimcoe** [comment]
Thanks @brandonkelly. I removed `vendor/` and re-installed everything. Cleared the deprecation warnings but this keeps on happening—but only on production. I have an identical staging server on Laravel Forge and my local Valet setup, and the error never shows up.

**Comment by brandonkelly** [comment]
Try clearing your `web/cpresources/` folder on production.

**Comment by jdsimcoe** [comment]
@brandonkelly Thanks. I just cleared that folder and the issue still crops out. I can't tell from my stack trace where it's being called but it looks like somewhere in the Yii2 folder `vendor/yiisoft/yii2` is calling it.

**Comment by brandonkelly** [comment]
Try searching your whole `web/cpresources/` folder for `users/get-remaining-session-time`. Does it show up in there somewhere? What file?

**Comment by jdsimcoe** [comment]
@brandonkelly I downloaded the full folder and it doesn't show up anywhere when I search through the folders.

**Comment by brandonkelly** [comment]
Maybe try clearing your browser cache?

**Comment by circa1977** [comment]
I may have solved this. After the following steps I did a find on my `vendor` dir and found matches in Craft's JS, for plugins that haven't updated their Craft version in `Composer.json`. I'll report back if that does the trick.

I removed the `/vendor` dir and re-ran `composer install`. It was gone for a number of clicks around the CP until I clicked into Commerce/Orders. I searched my `web` folder and found the attached.

![Screen Shot 2020-01-14 at 5 16 10 PM](https://user-images.githubusercontent.com/49657/72387470-9c912e80-36f1-11ea-9f59-80fdf99be7c3.png)

I clicked around a bit after clearing, the warning, watching `cpresources` fill back up, and didn't see the warning. Then after updating this issue I went back, clicked into Commerce/Orders, and it popped up again. Seems to be time-based.

But now when I do a find in that dir, I don't get a match.

**Comment by circa1977** [comment]
I'm no longer seeing this after updating all the plugins.

**Comment by jdsimcoe** [comment]
I'm no longer seeing this either. I think other users to the Control Panel had old cache files that were causing this.

**Comment by ryanpcmcquen** [comment]
Did this actually get solved? I am still seeing this issue.

**Comment by juddlyon** [comment]
I had the same issue and nothing seemed to work until I cleared composer's cache.

`
rm -rf vendor/
composer clear-cache
composer install
`

It didn't appear to be a plugin, it popped up after changing licenses and enabling rebranding.
