### ISSUE TITLE
MySQL-PDO: Unknown column 'siteName' in 'field list' when using ./craft backup/db

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#5393]
### Description

I get this error in the `storage/phperrors.log` file when I deploy on my staging environment:

> `PHP Warning:  MySQL-PDO: Unknown column 'siteName' in 'field list', Query: SELECT `siteName` FROM `craft_info` in /deploy/vendor/yiisoft/yii2/db/Command.php on line 1290`

After checking in the `craft_info` table, I can confirm there is no `siteName` column.

I have these scripts added in the `composer.json` file, for deployement automations:

```
"pre-update-cmd": [
  "./craft backup/db"
],
"post-update-cmd": [
  "./craft migrate/all",
  "./craft project-config/sync",
  "./craft queue/run",
  "./craft clear-caches/all",
  "./craft cache/flush-all",
  "./craft backup/db"
]
```

After trying all of these commands, I finally found that the `./craft backup/db` was adding this error to log.

Why do I get this, and how can I fix this?

### Steps to reproduce

1. Try `./craft backup/db` on a staging environment

### Additional info

- Craft version: Craft Pro 3.3.19
- PHP version: 7.3.11
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Agent 1.1.6, Control Panel Body Classes 2.1.1, Control Panel CSS 2.2.0, Dashboard Begone 1.0.1, Dumper 2.0.0, Embedded Assets 2.1.1.1, Expanded Singles 1.0.7, Field Manager 2.1.1, Imager v2.3.1, Mandrill 1.3.1, Minify 1.2.9, Neo 2.5.9, Redactor 2.4.0, Retcon 2.0.12, Typogrify 1.1.18, Wishlist 1.0.6

**Comment by brandonkelly** [comment]
Look for that error in your logs (`storage/logs/`). What is the full stack trace?

**Comment by romainpoirier** [comment]
Unfortunately, there is nothing more than this in _storage/logs/phperrors.log_:

```
[03-Jan-2020 14:01:34 Europe/Luxembourg] PHP Warning:  MySQL-PDO: Unknown column 'siteName' in 'field list', Query: SELECT `siteName`
FROM `craft_info` in /deploy-dev/vendor/yiisoft/yii2/db/Command.php on line 1290
```
No other log line in the other files.

**Comment by brandonkelly** [comment]
Alright, this is fixed now for the next release. Thanks for reporting!
