### ISSUE TITLE
Inconsistent rebuilding rebuilding of project.yaml (order, types)

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#5394]
Running `craft project-config/rebuild` will result in a different yaml file than when Craft makes the changes as a result of a CP change.

Things that can change (that I know of):
- order
- data types (true/false vs '' or '0', integers vs strings)

While these changes might not have any meaningful results in the yaml, the inconsistency can be frustrating when your `project.yaml` is sourced in version control and you constantly have to determine if changes are "real" or not.

**Comment by brandonkelly** [comment]
Ordering should be solved in Craft 3.4. Data types is a known issue though, which unfortunately can’t be easily solved until Craft starts requiring PHP 7.4 when we can start taking advantage of [typed properties](https://wiki.php.net/rfc/typed_properties_v2). Until then, it’s way more trouble than it’s worth to ensure everything always has the correct types.
