### ISSUE TITLE
Craft update fails with missing remote JSON file error

### ISSUE THREAD

**Issue by wuhhh** [craftcms/cms#5396]
### Description

Trying to update Craft or addons from the terminal `./craft update` or through admin produces the following error:

> The "https://composer.craftcms.com/p/provider/5bdfdba84240b2cea21e1e2d80b08b362ede66785af05c436397089bb929459b.json" file could not be downloaded (HTTP/1.1 404 Not Found)

### Steps to reproduce

1. Run `./craft update all` or attempt to update craft or any addon through the control panel

### Additional info

- Craft version: 3.3.18.3
- PHP version: 7.3.10
- Database driver & version: MySQL 5.7.27

**Comment by natkuu** [comment]
I'm getting the same error updating from craft admin panel. 

### Additional info
Craft version: 3.3.16.3
PHP version: 7.2.7
Database driver & version: PostgreSQL 10.4

**Comment by janhenckens** [comment]
Seeing the same issue here, on Craft 3.3.18.3

**Comment by bymayo** [comment]
I was having this issue this morning, but it seems to be resolved now and I can updated Craft.

**Comment by brandonkelly** [comment]
Yeah we were able to reproduce it as well, but the error went away before we could look into it, so… 🤷‍♂
