### ISSUE TITLE
Option to disable automatic search index updating

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#5397]
### Description
We're running into issues on a site with a large nightly import that runs via Feed Me.
Every night we import/update/disable between 7000 and 10000 entries, across multiple paginated feeds and the automated "Updating search indexes" queue job is causing some problems. Right now I have 29000 jobs in my queue, of which 28000 are search index updates.

I've gone through the fields and disabled search usage for most fields but I can't disable it for all since we're also using Craft's search on the site. The entries we're importing are also related to each other a lot of the time so that could also be causing extra indexing updates.

Craft does this in [Elements.php:2075](https://github.com/craftcms/cms/blob/develop/src/services/Elements.php#L2075).

Making it possible to disable this and then manually running the index update after the entire import is ready would probably solve the issue for us. (Well aware that other content changes won't make it to the index then either, we're only using Craft's search for the imported content here so that should be ok).

Would it be possible to have a look/discuss/consider this? Happy help code it if we can agree on how it should be done.

Thanks!

### Additional info

- Craft version: 3.3.18
- PHP version: 7.3
- Database driver & version: 5.7
- Plugins & versions: Feed-Me 4.1.2

**Comment by brandonkelly** [comment]
This is resolved in Craft 3.4 – see https://github.com/craftcms/cms/issues/4840#issuecomment-540097211

**Comment by janhenckens** [comment]
In this case Feed Mee is calling the `saveElement()`, is there a way to tell it to set `$updateSearchIndex` to `false`? 

We've updated the site to the latest 3.4 beta and it's still generating several hundred "Updating search indexes" jobs for every import.

**Comment by brandonkelly** [comment]
Right, we will need to update Feed Me with an option to disable search index updating. Just meant the groundwork has been laid in Craft itself. I just posted https://github.com/craftcms/feed-me/issues/649 covering the Feed Me side of things.
