### ISSUE TITLE
Error removing table column when type is dropdown

### ISSUE THREAD

**Issue by olivierbon** [craftcms/cms#5398]
### Description

It's not possible to remove a table column when column type is set to Dropdown.

```
yii\base\ErrorException
Undefined index: type
```

### Steps to reproduce

1. Create a table field
2. Add a column and set column type to *Dropdown*
3. Save field
4. Go back to the field, remove the Dropdown column and hit save

### Additional info

- Craft version: 3.3.19

**Comment by brandonkelly** [comment]
Doh, this was the same underlying issue as #5258… should have caught it then.
