### ISSUE TITLE
Can't delete assets: Invalid argument supplied for foreach() in /vendor/craftcms/cms/src/services/AssetTransforms.php:1201

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#5399]
### Description

On a bit restrictive server:

1. I can upload a file to the _Assets_;
2. I see it correctly uploaded: I can display it, and I can download it;
3. When I delete the file within the CP, I get the following error: `An unknown error occurred.` + the stack trace bellow (in `/storage/logs/web.log`);
4. This file remains saved in DB, but no longer live on the server;
5. The file stays here even after maintenance operations (`index-assets/all`, `resave/assets`, etc.);

After asking the server admin, this is what he says:
- For my test, it is the `NOTICE` alert for `$files` which is false and which deletes in DB;
- After reading the PHP code, and the code around line 1200 in `/vendor/craftcms/cms/src/services/AssetTransforms.php`, I think this is a Craft CMS' bug;
- `foreach ($a as $e)` expects to have an array for `$a`, or `$a` may be `false` according to the code, which implies a PHP alert (`false` is a documented return for the `glob()` function);
- Adding `(!is_array($files)) $files = array();` at line 1201 prevents this alert;
Moreover, the mode of Craft CMS that causes a global exception for a type of alert notice seems a bit much (see [PHP doc about error handler](https://www.php.net/manual/en/function.set-error-handler.php));
- You can reproduce the bug in a local environment using `ini_set('error_reporting', E_ALL | E_STRICT)`;

Stack trace:
```
#0 /vendor/craftcms/cms/src/web/ErrorHandler.php(80): yii\base\ErrorHandler->handleError(2, 'Invalid argumen...', '/export/hosting...', 1201)
#1 /vendor/craftcms/cms/src/services/AssetTransforms.php(1201): craft\web\ErrorHandler->handleError(2, 'Invalid argumen...', '/export/hosting...', 1201, Array)
#2 /vendor/craftcms/cms/src/services/AssetTransforms.php(1174): craft\services\AssetTransforms->deleteResizedAssetVersion(Object(craft\elements\Asset))
#3 /vendor/craftcms/cms/src/elements/Asset.php(1404): craft\services\AssetTransforms->deleteAllTransformData(Object(craft\elements\Asset))
#4 /vendor/craftcms/cms/src/services/Elements.php(1243): craft\elements\Asset->afterDelete()
#5 /vendor/craftcms/cms/src/elements/actions/DeleteAssets.php(66): craft\services\Elements->deleteElement(Object(craft\elements\Asset))
#6 /vendor/craftcms/cms/src/controllers/ElementIndexesController.php(211): craft\elements\actions\DeleteAssets->performAction(Object(craft\elements\db\AssetQuery))
#7 [internal function]: craft\controllers\ElementIndexesController->actionPerformAction()
#8 /vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('perform-action', Array)
#11 /vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('perform-action', Array)
#12 /vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('element-indexes...', Array)
#13 /vendor/craftcms/cms/src/web/Application.php(565): craft\web\Application->runAction('element-indexes...', Array)
#14 /vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#15 /vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#16 /htdocs/index.php(21): yii\base\Application->run()
#17 {main}
2020-01-03 16:57:49 [-][1][-][info][application] $_GET = [
    'p' => 'admin/actions/element-indexes/perform-action'
]

$_POST = [
    'context' => 'index'
    'elementType' => 'craft\\elements\\Asset'
    'source' => 'folder:99f7ae35-4ba3-4ba0-a9fa-8157f032d16b'
    'criteria' => [
        'siteId' => '1'
        'search' => ''
        'offset' => '0'
        'limit' => '50'
        'trashed' => '0'
        'drafts' => '0'
        'status' => ''
        'enabledForSite' => ''
    ]
    'viewState' => [
        'mode' => 'table'
        'order' => 'dateCreated'
        'sort' => 'desc'
    ]
    'paginated' => '1'
    'elementAction' => 'craft\\elements\\actions\\DeleteAssets'
    'elementIds' => [
        0 => '8248'
    ]
]
```

### Steps to reproduce

1. See **Description**;

### Additional info

- Craft version: Craft Pro 3.3.19
- PHP version: 7.3.11
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Agent 1.1.6, Control Panel Body Classes 2.1.1, Control Panel CSS 2.2.0, Dashboard Begone 1.0.1, Dumper 2.0.0, Embedded Assets 2.1.1.1, Expanded Singles 1.0.7, Field Manager 2.1.1, Imager v2.3.1, Mandrill 1.3.1, Minify 1.2.9, Neo 2.5.9, Redactor 2.4.0, Retcon 2.0.12, Typogrify 1.1.18, Wishlist 1.0.6

**Comment by andris-sevcenko** [comment]
Can you tell a bit more about how is the server restrictive?

`glob()` would return `false` there only if there's an error listing the files. If the code is modified to just silently assume there are no files when there's actually an error, it can easily lead to a situation where not only code is not deleting files that should be deleted, but also there's no information about it in the logs.

**Comment by romainpoirier** [comment]
I forwarded this to the server admin, and below is its answer...

# Point 1:
 The PHP documentation explicitly says that under some conditions it's not possible to distinguish between empty match and error. Seems `openbase_dir` might be such a case (maybe only in case of multi-level globs).

# Point 2:
A dump of what it's `glob()`ing for reveals the following:
- `glob(/storage/runtime/assets/thumbs/[0-9]*/8255.[a-z]*)` → `false`
- `glob(/storage/runtime/assets/imageeditor/8255/[0-9]*/8255.[a-z]*)` → `false`

Passing those paths to `ls` returns `No such file or directory`.

A manual scan of boths globs tells:
- `/storage/runtime/assets/thumbs/` exists and has a few matching ([0-9]*) child directories but those directories have no matching (8254.[a-z]*) children
- `/storage/runtime/assets/imageeditor/` exists but is empty

`Strace` of PHP does not reveal vers useful data:
- first glob: scans through `/thumbs/ `children and finds nothing useful tries to stat `/storage/runtime/assets/thumbs/[0-9]*` and fails with `ENOENT` no further `syscalls` relating to `glob()` follow (that stat attempt could be during `open_basedir` checking)
- second glob: tries to `opendir()` `/storage/runtime/assets/imageeditor/8255` and fails with `ENOENT`
 stats to the same path and fails with `ENOENT` no further `syscalls` relating to `glob()` follow (that stat attempt could be during `open_basedir` checking)

A review on PHP's `glob()` interaction with `open_basedir` might enlighten on why the end-result is false instead of empty `array()`.

On the other hand I can't tell if there is anything else being complained about by PHP as the error handler is not leaving any output for PHP's error_log

Anyhow, interrupting in the middle of deletion operation due to `glob()` failing (thus leaving DB references intact, but already having dropped the target file) feels like bad transaction management.
Not tripping over `$files` being `false` but warning that `glob()` failed while still performing the remaining checks/cleanups gracefully seams more correct.

A `glob()` where at least one file exists does return an array listing existing files.
It seems `glob()` tries to open/test file with name equal to the glob string (up to first segment with wildcard) if it didn't find any other match and that testing might cause trouble with `open_basedir`.

**Comment by andris-sevcenko** [comment]
> Not tripping over $files being false but warning that glob() failed while still performing the remaining checks/cleanups gracefully seams more correct

That seems to be a viable compromise, yeah. I'll add that before the next release.

**Comment by andris-sevcenko** [comment]
Just pushed this fix for the next release!
