### ISSUE TITLE
Package zendframework/zend-feed is abandoned

### ISSUE THREAD

**Issue by lukebailey** [craftcms/cms#5400]
### Description
When running 'composer update' the following warning is shown related to three zendframework packages, seemingly abandoned in favour of laminas. Not an issue for now but suspect our security moniotring will shown highlight this to be actioned. 

<img width="921" alt="image" src="https://user-images.githubusercontent.com/3185073/71827018-383df180-3097-11ea-95e0-953ead102564.png">

### Steps to reproduce

1. Run composer update

### Additional info

- Craft version: 3.3.17
- PHP version: 7.3

**Comment by brandonkelly** [comment]
Swapped to laminas-feed for Craft 3.4.
