### ISSUE TITLE
Get standard uid for preview target

### ISSUE THREAD

**Issue by ryanpcmcquen** [craftcms/cms#5405]
I have a preview target like this:
```
@previewUrl/live-preview/fooBar/{uid}
```

Instead of giving me the uid of the entry, I am getting some weird uid (maybe the uid of the draft). Is there a way to get the standard uid?

**Comment by brandonkelly** [comment]
Yeah, it’s the draft’s. Change to `{sourceUid}` and it will return the real entry UID.

**Comment by ryanpcmcquen** [comment]
@brandonkelly, thanks! Is that documented anywhere?

**Comment by brandonkelly** [comment]
It is now :)

https://docs.craftcms.com/v3/sections-and-entries.html#preview-targets

> If you want to include the entry’s ID or UID in a preview target URL, use `{sourceId}` or `{sourceUid}` rather than `{id}` or `{uid}`, so the source entry’s ID or UID is used rather than the draft’s.
