### ISSUE TITLE
Replace `@web` alias with `DEFAULT_SITE_URL` environment variable in sites base URLs

### ISSUE THREAD

**Issue by nstCactus** [craftcms/cms#5409]
I can't seem to find how to properly set up localized sites using the `DEFAULT_SITE_URL` environment variable rather than the `@web` alias.

I have 3 localized sites:

| handle | default site | base url |
| - | - | - |
| fr | ✔️  | `@web/fr` |
| en | |`@web/en` |
| de | |`@web/de` |

If I try to replace `@web`with `$DEFAULT_SITE_URL` from the CP, it gets rewritten to `http://$DEFAULT_SITE_URL/fr`.
If I try to edit the sites `baseUrl`s in project.yaml, it shows correctly in the CP, but my entries URLs start with `$DEFAULT_SITE_URL/fr` (eg: https://example.com/$BASE_URL/en/demo).

I have several requirements:
  - having localized URLs for my sites, based on the same domain (example.com/fr, example.com/en)
  - having a different domain for each environment (example.ddev.site for dev, preprod.example.com for staging and example.com for live)
  - I have a review environment where I'd like to define the value of the `DEFAULT_SITE_URL` to `@web`. There are no security concerns on this one & the base URL can change

### Additional info

- Craft version: 3.3.19
- PHP version: 7.2.25
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
Do you actually have an environment variable defined (either in `.env` or elsewhere on your system) called `DEFAULT_SITE_URL`?

**Comment by brandonkelly** [comment]
> If I try to replace `@web`with `$DEFAULT_SITE_URL` from the CP, it gets rewritten to `http://$DEFAULT_SITE_URL/fr`.

If you want to use an environment variable there, you can’t append anything to it (e.g. `…/fr`). Only aliases like `@web` can have additional URI segments appended to it.

You can set `@web` or any other alias to an environment variable, however. Doing that for `@web` will also have the benefit of removing any security concerns.

Add this to your `config/general.php`:

```php
'aliases' => [
    '@web' => getenv('BASE_URL'),
],
```

Then you can safely use `@web` as the URL starting point wherever needed.
