### ISSUE TITLE
Allow passing token as a header instead of a query param

### ISSUE THREAD

**Issue by helderdb** [craftcms/cms#5410]
### Description

Currently with the live preview of GraphQL it is only supported to pass the token with a queryparam. I'm using apollo in React as a frontend but querystring parameters are not supported. Instead it would be nice to pass the token as a header.

### Steps to reproduce

1. Use Craft live preview with apollo and React

### Additional info

- Craft version: 3.3.19
- PHP version: 7.2

**Comment by brandonkelly** [comment]
You already can – call the header `X-Craft-Token`.
