### ISSUE TITLE
Element HUDs get pushed outside the screen

### ISSUE THREAD

**Issue by gglnx** [craftcms/cms#5413]
### Description

We're using asset fields inside Matrix and Neo fields. The volume itself has some fields attached, so the element HUD is larger. On double-click the HUD for the asset gets pushed out of the screen. The effect gets bigger each time when are more items inside a Matrix/Neo field.

Example with Matrix:

![support](https://user-images.githubusercontent.com/23519/72078031-987f9e00-32f8-11ea-8704-03b01495cadd.gif)

Example with Neo:

<img width="1440" alt="Bildschirmfoto 2020-01-08 um 14 32 38" src="https://user-images.githubusercontent.com/23519/72077459-9537e280-32f7-11ea-83a9-a9ff1677cb9f.png">

### Steps to reproduce

1. Create some fields, attached to a volume
2. Create a matrix field with a asset field
3. Add some entries to this matrix field
4. Then view is scrollable, double-click on an asset

### Additional info

- Craft version: 3.3.19
- PHP version: 7.4.1 
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Neo 2.5.9

**Comment by brandonkelly** [comment]
Guessing this is already resolved for Craft 3.4, as the control panel has been restyled in a way that should be more resilient for things like this.

**Comment by gglnx** [comment]
I checked it with 3.4 beta 5 and you're right. The problem is fixed. Thank you!

**Comment by brandonkelly** [comment]
Great – thanks for confirming!
