### ISSUE TITLE
Add config option for displaying login flash message even if ajax was used

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#5415]
On one of my recent websites, I created AJAX login form. Form sends AJAX request and when information about successful login is received from backend,  whole page is reloaded.

Only problem with that that no flash message related to being logged-in is displayed after page reload. I understand it is related to fact that request was sent over AJAX - but could we have an option to "force" flash message in such case?

**Comment by brandonkelly** [comment]
Craft actually _never_ sets a “Logged in” flash message. Maybe you can just add a `?login=1` param to the page URL you redirect to after login, and then that page can conditionally show a “Logged in” message if it sees that in the URL.
