### ISSUE TITLE
FR: Confirmation when deleting plugin

### ISSUE THREAD

**Issue by michtio** [craftcms/cms#5421]
### Description

When we're developing, and want to check the plugins if they're installed or not in the CP Plugins panel, you can install/uninstall. But there is also the "remove" option.

I just noticed when clicking the remove button it immediately went to "updating composer dependencies" and started to remove the plugin.

It wouldn't be a bad thing that there is a message "Are you sure you want to delete/remove this plugin?" 

### Steps to reproduce

1. Go the CP -> Settings -> Plugins
2. Select a plugin and click remove.

**Comment by brandonkelly** [comment]
It’s only possible to completely remove a plugin from the UI once it has been uninstalled, and it’s an easy action to “undo” (just reinstall it either from the plugin store or with Composer). So I’m not sure what the point of the warning would be.

**Comment by michtio** [comment]
I agree with that part @brandonkelly that you can't just remove an installed plugin, but when you accidentally click the remove button web-based the process takes a while, and for a few minutes the CP is unavailable, then having to reinstall indeed goes quickly through composer, but also takes a little bit of time to fix again.

So if that happens a few times a day, you easily lose 30 minutes. An option also might be ( if CLI is used for dev ) there is somewhere an options ( disable installing plugins through CP - web based )
