### ISSUE TITLE
Documentation for craft\web\Controller $allowAnonymous

### ISSUE THREAD

**Issue by abryrath** [craftcms/cms#5422]
### Description
craft\web\Controller no longer accepts `true` as a valid value for protected attribute $allowAnonymous. Inline documentation still shows `true` and `bool` as possible values.

I am submitting a PR to update the documentation.

### Steps to reproduce

1. N/A

### Additional info

- Craft version: 3.3.19
- PHP version: N/A
- Database driver & version: N/A
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
`true`/`false` are still supported:

https://github.com/craftcms/cms/blob/49e143d4f866ce477b4a8b4c97f61a8d23fb3dc7/src/web/Controller.php#L75-L77

If it’s not working for you, check if your controller is overriding the `init()` method. If so, make sure that you are calling `parent::init()` within it.
