### ISSUE TITLE
[Feature Request] Add babel option for js twig tag

### ISSUE THREAD

**Issue by keyurshah** [craftcms/cms#5424]
### Description
Wanted to see if it would be possible to add an option to allow code inside js tags to be compiled with babel. 

The js tag works great, but we can't use modern ES6 language features without moving the code away to a separate javascript file.  

Thanks!

**Comment by brandonkelly** [comment]
This would be awesome, but not practical unfortunately. ES6 transpilation would require either using a library [php-babel-transpiler](like https://packagist.org/packages/talyssonoc/php-babel-transpiler) (which requires installing the [v8js](https://pecl.php.net/package/v8js) PHP extension), or running a command directly on the system (which is how [Yii 2’s TypeScript support](https://www.yiiframework.com/doc/guide/2.0/en/structure-assets#asset-conversion) works – it requires that you have the `tsc` command installed).

Environmental requirements aside, transpilation is expensive so you wouldn’t want to run that on every request. For that reason alone, you’re going to be better off keeping your ES6 code confined to JS source files.

**Comment by seanmorris** [comment]
This is totally possible https://www.npmjs.com/package/php-wasm
