### ISSUE TITLE
[FR] Let graphql transform directive apply to all asset properties

### ISSUE THREAD

**Issue by membla** [craftcms/cms#5425]
### Description

As far as I can tell, the transform directive can only be applied to the `url` field of the asset in graphql. At a minimum, it should also be able to give the correct `path` of the transform, but more intuitively it should work on the asset field and return all properties of the given transform, e.g.

```
image @transform(handle:"largeFrontImage") {
url
path
width
height
}
```

Should return the properties of the transformed asset.

### Additional info

- Craft version: 3.4.beta-5

**Comment by andris-sevcenko** [comment]
Great idea! Just pushed this to the `3.4` branch.

**Comment by membla** [comment]
Hmm, just ran into this issue again – not sure if this is a regression but path is not returning the correct (transformed asset path) at e.g.

```
image @transform(handle:"largeFrontImage") {
url // correct url
path //path to original image
}
```

**Comment by brandonkelly** [comment]
@membla `path` refers to the asset’s location within its volume. Not something that would be affected by transforms.

**Comment by membla** [comment]
@brandonkelly Looking now at the PHP API, it makes sense why you don't but I do think it becomes very counterintuitive from a GraphQL perspective having the `@transform` on the asset node when the directive isn't applied to all the fields. This was the assumption I had for my original FR anyway.

**Comment by brandonkelly** [comment]
I’ll pass that on to @mattstein and let him decide whether there’s an opportunity to improve the docs here.
