### ISSUE TITLE
3.4-beta: stack trace on recent code update

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#5429]
### Description
This is very fresh - git blame says due to commit https://github.com/craftcms/cms/commit/a3cd724b62f61d89148963aa0bf20f5c1c513329, occurring on trying edit an entry.

Stack trace error: Undefined index: refresh

The problem seems evident -- have a look at line 1703 of base/Element.php. Something looks a little missing, no?

Picture attached
![refresh-missing](https://user-images.githubusercontent.com/247945/72308473-75732800-3631-11ea-82d9-19002a40c2ac.png)

**Comment by brandonkelly** [comment]
Whoops, thanks for reporting that! Fixed now.

**Comment by narration-sd** [comment]
verified, does de trick...
