### ISSUE TITLE
Updater in production mode gets stuck

### ISSUE THREAD

**Issue by helderdb** [craftcms/cms#5431]
### Description

Sorry if this is already addressed, did not find it yet.

I just ran into a very annoying issue while upgrading one of our craft sites. We have multiple environments where we test from local to a semi-staging environment (this is where the root of the problem lays, devMode is enbaled here). All is dockerized.
When upgrading on our staging, an update prompt shows when navigating to /admin, you click finish up and the database upgrades with the craft installation. It does however say that it cannot backup the database, but since I manually did this I click 'continue anyway'. However, on our production stage, the prompt is not shown to skip the database backup and it hangs at "Checking environment..." and nothing happens. Until you enable devMode, you cannot update the craft installation.

### Steps to reproduce

1. Update craft installation in docker image
2. Deploy docker to production (devMode = false)
3. Navigate to example.com/admin
4. Click 'finish up' button
5. Update hangs!

### Additional info

- Craft version: 3.3.19
- PHP version: 7.3
- Database driver & version: MySQL 5.7.24

**Comment by brandonkelly** [comment]
It’s certainly possible to run update migrations when Dev Mode is disabled. So something else is going on here. Please zip up your `storage/logs/` folder and send it into support@craftcms.com, and reference this issue. Maybe we’ll be able to find additional clues in there.

**Comment by helderdb** [comment]
@brandonkelly I accidentally deleted the logs while creating the docker volume. I'll send them next time I encounter this. However, I was not able to reproduce the problem on our staging env where I disabled devMode and did the same upgrade, so it's weird.

**Comment by brandonkelly** [comment]
Alright, will close this for now. If it happens again, please immediately check your logs or send them into support@craftcms.com.
