### ISSUE TITLE
Rename Draft Doesn't Immediately Update

### ISSUE THREAD

**Issue by RitterKnightCreative** [craftcms/cms#5432]
### Description
Using the pencil icon to rename the Draft, it appears to the user that the draft gets renamed but the draft doesn't actually update unless the user makes some other change to the document.

Going back in to rename the Draft a second time, the name in the widget is updated but the drop down showing all the drafts does not.

If the user clicks out or reloads the window before making a change to the draft, the draft name is never updated. 

Definitely confusing especially if all you want to edit is clean up some drafts.

### Steps to reproduce

1. Use pencil icon to bring up the rename draft widget
2. Rename the draft 
3. Press Save

Notice Craft doesn't actually update the name until the draft is otherwise changed in some way.

### Additional info

- Craft version: 3.3.19
- PHP version: 7.3
- Database driver & version: MySQL 5.7

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just released Craft 3.3.20 with a fix for that.
