### ISSUE TITLE
Browser validation interferes with HUD entry form (no novalidate)

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#5433]
The CP element edit form has `novalidate` on it, but the HUD form does not.

This can lead to some odd behavior with custom field types: e.g.: https://github.com/sebastian-lenz/craft-linkfield/issues/86

Seems like we'd want the forms to behave the same?

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just released Craft 3.3.20, which now adds a `novalidate` attribute to element editor HUD forms.
