### ISSUE TITLE
[Improvement] Better check on ImageMagick installation.

### ISSUE THREAD

**Issue by bertoost** [craftcms/cms#5435]
### Description

Creating an Docker image with PHP 7.4.1 based on Alpine Linux I found some issues installing ImageMagick correctly. Getting this error message in Craft CP

![image](https://user-images.githubusercontent.com/398492/72376736-c4db5600-370e-11ea-9aaa-e0bc68fd7c82.png)

After some intensive debugging I found the actual error occurs by ImageMagic used in `vendor/pixelandtonic/imagine/src/Imagick/Imagine.php :: open($path)`. The error was triggered by ImageMagick because the `\Imagick::queryFormats()` did not return any formats (just an empty array).

Therefore the System Report page in the CP shows that ImageMagick is installed successfully.
Maybe it's good to improve this with checking above method to return at least something? And maybe even check if JPG/JPEG/GIF/PNG etc. are in it?

### Additional info

After I fixed the ImageMagick installation by the next lines (for anyone searching for it), the method from above returned a list of 233 items and after that uploading images works like a charm again.

```
RUN apk add ... imagemagick imagemagick-dev \
    && pecl install imagick-3.4.4 \
    && docker-php-ext-enable imagick
ENV MAGICK_HOME=/usr
```

- Craft version: 3.3.19
- PHP version: 7.4.1

**Comment by bertoost** [comment]
As far I have tried; the requirements check should be extended from
```
'condition' => extension_loaded('gd') || extension_loaded('imagick'),
```
to
```
'condition' => extension_loaded('gd') || (extension_loaded('imagick') && !empty(\Imagick::queryFormats())),
```

But even better also check if JPG/GIF/PNG is in the list.

**Comment by angrybrad** [comment]
Weird...

Curious why `\Imagick::queryFormats()` would return null before running your fix and results after. Clearly the extension is available and enabled both before and after.

```
RUN apk add ... imagemagick imagemagick-dev \
    && pecl install imagick-3.4.4 \
    && docker-php-ext-enable imagick
ENV MAGICK_HOME=/usr
```

Any ideas @bertoost @jasonmccallister?

**Comment by bertoost** [comment]
Yeah I don't know exactly, but the I found the `queryFormats()` in some blog post online. That one returned an empty array before. After this it returned a long list and then the upload started working again and the error disappeared.

**Comment by mattstein** [comment]
FWIW I'm keeping an eye on this issue wondering if it's related to an unsolved SVG mystery, where _either_ image driver _sometimes_ fails to load a source SVG to transform. Deep down, each one claims the source SVG isn't in a known format. (Either `Failed to load the SVG string.` or `Data is not in a recognized format`.) I can `convert test.svg test.png` successfully from the command line, however. Randomly happens in different environments as well.

May be unrelated, but _something_ isn't always convinced it can handle images even when the server software's ready to go.

**Comment by jasonmccallister** [comment]
@bertoost can you share the complete Dockerfile? I'd like to build locally and take a look.

**Comment by bertoost** [comment]
Sure, it's public on github;
https://github.com/bertoost/Docker-Images/blob/master/php/7.4/Dockerfile.fpm

**Comment by jasonmccallister** [comment]
Thanks @bertoost. Did a little research and there are a few things that come to mind. I have had issues setting up imagick and alpine in the past that I had to pass some specific flags when installing the ext. I also found this post on our SE that talks about the same error: https://craftcms.stackexchange.com/questions/16681/the-file-does-not-appear-to-be-an-image-bug

Can you check imagick on the CLI to make sure its configured and working properly?

**Comment by bertoost** [comment]
Hi @jasonmccallister I have installed it now correctly, with above solution. But just suggest a little improvement on the requirements since I ran into this after I thought it was installed, but not installed correctly.

**Comment by angrybrad** [comment]
Resolved this here:

https://github.com/craftcms/cms/commit/3d18a6339702c4ab61e6742430cb0c1fd93ccf08

https://github.com/craftcms/server-check/releases/tag/1.1.8

**Comment by bertoost** [comment]
Cool! Thanks @angrybrad

**Comment by brandonkelly** [comment]
Craft 3.4.0-RC3 is out now with this fix.
