### ISSUE TITLE
PHP Parse error:  syntax error, unexpected ')' in .../vendor/craftcms/cms/bootstrap/console.php on line 26

### ISSUE THREAD

**Issue by proimage** [craftcms/cms#5436]
### Description
Getting this error after updating to Craft 3.3.20 and running `./craft project-config/sync`:

```console
user:/var/www/[redacted]/htdocs$ ./craft project-config/sync
PHP Parse error:  syntax error, unexpected ')' in /var/www/[redacted]/htdocs/vendor/craftcms/cms/bootstrap/console.php on line 26
```

Updating via the backend (both the "Updates to DB" and the "Project Config Sync" stages) works fine.

**Comment by angrybrad** [comment]
Sorry about that... we'll get a hotfix release out shortly.

**Comment by vnali** [comment]
@proimage 
same for me. it's because of this:  https://github.com/craftcms/cms/commit/6d5c70050ed4f593dcaca528157e3aa22dc2c104

**Comment by brandonkelly** [comment]
3.3.20.1 is out now with a fix.
