### ISSUE TITLE
Deprecation Warning in 3.4.0 / 3.0.0 RC-1

### ISSUE THREAD

**Issue by circa1977** [craftcms/cms#5437]
### Steps to reproduce

After successfully upgrading to 3.4.0 RC-1 and installing Commerce 3.0.0 RC-1, I see the following deprecation error that doesn't seem to be coming from my code:

The users/get-remaining-session-time action is deprecated. Use users/session-info instead.

I first attempted to "send to Developer Support," but it just kept spinning.

### Additional info

- Craft version: 3.4.0-RC1.1 (Pro)
- PHP version: 7.3.8
- OS version: Darwin 18.7.0
- Database driver & version: MySQL 5.7.26
- Image driver & version: Imagick 3.4.3 (ImageMagick 6.9.6-2)
- Plugins & versions: 
    - Amazon S3 1.2.7
    - BookingsCRM by Clearbold 0.0.4
    - Campaign Monitor Campaigns 0.1.0-alpha.1
    - Campaign Monitor Lists 1.1.8
    - Campaign Monitor Service 1.0.10
    - Campaign Monitor Synch 0.3.2-alpha.1
    - Campaign Monitor Transactional 1.0.2
    - CKEditor 1.0.0-beta.2
    - Craft Commerce 3.0.0-RC1
    - Dark Sky Weather 1.0.6
    - Fix Me a Link 1.0.1

**Comment by brandonkelly** [comment]
This is a duplicated of #5392 – though we never really got to the bottom of it. Can you read through that thread and follow up if you have any additional info to add?
