### ISSUE TITLE
3.4-RC1.1 Migrating from Craft 2 does not create default preview targets

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#5440]
### Description
I did a dry-run of Craft 2.7.4 to Craft 3.4-RC1.1 and everything went great except that default Preview Targets were not created as they should have been.

### Additional info

- Craft version: 2.7.4 -> 3.4-RC1.1
- PHP version: 7.3
- Database driver & version: MySQL 5.7
- Plugins & versions: N/A - None installed during migration

**Comment by brandonkelly** [comment]
Can you send your Craft 2 database backup over to support@craftcms.com and reference this issue?

**Comment by Mosnar** [comment]
@brandonkelly Done.

**Comment by brandonkelly** [comment]
We just released Craft 3.4 RC2 with a fix for this.
