### ISSUE TITLE
Uninstalled plugin causes failure of project-config/sync on staging env

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#5442]
### Description

If I try a plugin locally, then uninstall it before to push it to another server, the plugin reference is kept and recorded in the `config/project.yaml` file.

On the next deploy, the `project-config/sync` command failed because the plugin is not found:

```
Installing plugin "pdfthumb" ... error: No plugin exists with the handle "pdfthumb".
Aborting config sync
```

This is because the plugin is still recorded in the `config/project.yaml` file, even after uninstall through Composer (and even after delete of this file or the use of `./craft project-config/rebuild`):
```
pdfthumb:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
```

I can confirm that the plugin stills exists in the repository. This can be done with any other plugin that this one.

To unlock the website, I have no other way that:
1. Re-install the plugin
2. Push the updated `config/project.yaml` file to the staging env
3. Uninstall the plugin locally
4. Push the `config/project.yaml` file again to the staging env

### Steps to reproduce

1. Install a plugin locally (example: `composer require jmoont/pdfthumb`)
2. Uninstall the plugin locally (example: `composer remove jmoont/pdfthumb`)
3. Push automatically updated `config/project.yaml` file to another env
4. Try the `./craft project-config/sync` command, and get the error

### Additional info

- Craft version: 3.3.20.1
- PHP version: 7.2.26
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
This is expected behavior. You should be uninstalling plugins from Settings → Plugins before Composer-removing them.

<img width="128" alt="A plugin’s action menu, with “Uninstall” highlighted" src="https://user-images.githubusercontent.com/47792/72479821-5a77f380-37aa-11ea-957e-5f36f49447af.png">
