### ISSUE TITLE
3.4-RC1.1 Info icon vertical alignment

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#5444]
### Description

This is a small but important detail. The `.info` icon height has been changed from `1.375em` to `16px`. This has thrown off the alignment with text. I realise the info icon has become almost non-existant in the CP, but my plugins rely on it heavily and it really helps keep the UI tidy.

A simple fix would be to change `vertical-align: bottom;` to `vertical-align: text-top;`.

Before:
![Screenshot 2020-01-15 at 20 54 04](https://user-images.githubusercontent.com/57572400/72466491-40093e80-37d9-11ea-90ee-cc2819d8eed4.png)

After:
![Screenshot 2020-01-15 at 20 54 20](https://user-images.githubusercontent.com/57572400/72466500-44355c00-37d9-11ea-90f0-3dd9a3be755c.png)

### Additional info

- Craft version: 3.4-RC1.1

**Comment by brandonkelly** [comment]
> I realise the info icon has become almost non-existant in the CP

Quite the opposite! I made the change to compensate for a line height issue after adding them to checkbox labels in the Clear Caches utility (#5418). The change looked OK in Craft’s own info icon uses, including a `<th>` in a `<thead>`, but apparently a `<th>` inside the `<tbody>` is styled slightly differently and caused this.

Anyway, fixed now.

**Comment by bencroker** [comment]
Looking good, thanks!

![Screenshot 2020-01-16 at 09 27 18](https://user-images.githubusercontent.com/57572400/72506594-7cbd5000-3842-11ea-917e-ca955f03da37.png)
