### ISSUE TITLE
Craft CMS / 1PasswordX z-index issues

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#5448]
I'm posting this on both 1Password and Craft issues as I'm not sure what's changed where; but I think there's a lot of developers who use both these tools so hopefully affects more than just me.

A few days ago, on the Craft CMS login screen (on my development sites), the "Forgot your password?" text started appearing over the top of the 1P auto-fill window. I ignored it, but I've just found a more serious one inside the control panel. When you're prompted for a password within the control panel, like when you update user permissions, or get signed out of the CMS, the 1PasswordX autofill window appears behind the overlay underneath everything else so it's not possible to use it.

1Password Issue: https://discussions.agilebits.com/discussion/110566/craft-cms-1passwordx-z-index-issues

1. The suggestions box is behind the popup, and behind the dark overlay
![image](https://user-images.githubusercontent.com/1250017/72510418-1809f180-3852-11ea-8af9-8836b154723c.png)

2. "Forgot your password?" is in front of the auto-fill box
![image](https://user-images.githubusercontent.com/1250017/72510432-1dffd280-3852-11ea-830a-174bebc33f08.png)

3. The auto-fill box is behind the modal, and behind the overlay
![image](https://user-images.githubusercontent.com/1250017/72510447-22c48680-3852-11ea-9e06-d8e1ff548a52.png)

### Additional info

- Craft version: 3.3.20.1
- PHP version: 7.3

**Comment by brandonkelly** [comment]
It must be due to a 1Password X update. I responded to your 1Password Forum post, and will monitor that.

**Comment by darylknight** [comment]
Thank you Brandon; appreciate it.
