### ISSUE TITLE
Bug in mergeElements function (Elements service)

### ISSUE THREAD

**Issue by TimvanDijkhuizen** [craftcms/cms#5450]
### Description

I'm trying to merge two elements but this query causes an error. The relations table doesn't even have an elementId column.
https://github.com/craftcms/cms/blob/939abd1b6034957ef8122205dc242a9c0551688f/src/services/Elements.php#L1085

Context:
https://i.postimg.cc/BQBnTG1j/discord-screenshot.png

### Steps to reproduce

1. Try merging two elements using the mergeElements() function
2. DatabaseException

### Additional info

I currently don't have access to the stacktrace but it should be obvious what is causing the error.

- Craft version: 3.3.16.3
- PHP version: 7.1.6
- Database driver & version: MySQL 5.5.59
- Plugins & versions: No plugins involved

**Comment by brandonkelly** [comment]
Thanks for posting the GitHub issue! Just fixed this for the next Craft 3.4 release.
