### ISSUE TITLE
Unable to save entry as a draft error when creating/resaving entries

### ISSUE THREAD

**Issue by howells** [craftcms/cms#5452]
### Description

I have a section whose Entry URI format is - for example (it happens to similarly configured sections) - `tv/{entry.id}/{entry.slug}`. Since updating to Craft 3.4.0-RC1.1, when I choose to create a new entry I just get an Internal Server Error and in the logs I get the error, `Unable to save entry as a draft: Could not generate a unique URI based on the URI format.`

I get the same error when trying to re-save existing entries, with the error appearing below the slug field.

### Steps to reproduce

1. Create or save an entry with {entry.id}/{entry.slug} in the URI format

### Additional info

- Craft version: 3.4.0-RC1.1

**Comment by brandonkelly** [comment]
That URI format should be `tv/{id}/{slug}` – not `tv/{entry.id}/{entry.slug}`. If you fix that, you shouldn’t have any trouble creating/editing entries.

(Nothing has changed in 3.4 that should have affected this, FTR. That `entry.` syntax has never been supported.)

**Comment by howells** [comment]
So sorry, no idea how I was even able to create these entries in the first place!
