### ISSUE TITLE
[Feature Request] Show what fields are Translatable in settings

### ISSUE THREAD

**Issue by mediabeastnz** [craftcms/cms#5453]
### Description
When working on multi-sites that have a lot of fields (probably most of them) there's no easy way to confirm what fields are translatable without going in and checking each one. 

It would be great if the icon used when the field is rendered is actually displayed in the fields area under settings.

This would allow you to just glace at which fields aren't or are.

**Comment by mmikkel** [comment]
It'd also be nice if the "Use this field’s values as search keywords" setting was exposed in that list.

**Comment by brandonkelly** [comment]
Just made this change for the next release.

<img width="871" alt="A field row on the Settings → Fields page, which identifies that the field is both searchable and translatable" src="https://user-images.githubusercontent.com/47792/92293348-bb8a3e00-eed7-11ea-8458-443a1cc5cf16.png">

**Comment by brandonkelly** [comment]
Craft 3.5.9 is out now with this change.

**Comment by darylknight** [comment]
Looks like this might be bugged - all the fields on my install are showing that icon, but 90% of them aren't searchable

**Comment by brandonkelly** [comment]
@darylknight That was reported in #6808.
