### ISSUE TITLE
 Searchindexes table is forced to MyISAM engine

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/cms#5456]
### Description
We are trying to setup Craft with our Percona Xtradb Cluster database. This does not support MyISAM, because of this we have to hardcoded change the installation to create the `searchindexes` table with the InnoDB engine. Is it possible to have it fallback to InnoDB or somehow make it a possibility to be configured?

### Steps to reproduce

1. Setup Percona Xtradb Cluster
2. Create clean setup of Craft
3. Install Craft with the wizard

### Additional info

- Craft version:
- PHP version: PHP 7.2.26
- Database driver & version: Percona Xtradb Cluster 5.7.26
- Plugins & versions: Clean install

**Comment by verbeeksteven** [comment]
MyISAM is used because InnoDB full text is only supported in 5.6 and CraftCMS supports 5.5 (at least according to https://docs.craftcms.com/v3/requirements.html).

I do feel that increasing the requirement to 5.6 and changing the single MyISAM table to InooDB is reasonable.

**Comment by angrybrad** [comment]
There's a nasty InnoDB MySQL full-text search bug that still exists, which is another reasons we're hesitant to swap it over to InnoDB:

https://bugs.mysql.com/bug.php?id=78485

Issue: https://github.com/craftcms/cms/issues/3862

**Comment by brandonkelly** [comment]
We just resolved #3862 for Craft 3.4, so defaulting to InnoDB for MySQL 5.6+ is a possibility now. That feature request is already covered by #3731 though, so going to close this one.
