### ISSUE TITLE
Yii debug-toolbar in the way of the last plugin

### ISSUE THREAD

**Issue by epic-elise** [craftcms/cms#5457]
The Yii debug toolbar covers the last plugin on the plugin page making the drop down inaccessible.  I've just been hiding it in dev tools when I need to install or make changes to that last plugin.  It's a small annoyance.  Just needs a little more padding on the plugin page or something.  I have a screen shot if you need it.

### Steps to reproduce

1. Have enough plugins to fill the browser depending on screen size (6-7 in my case)
2. have the yii debug tool bar displayed in the bottom right
3. try to click the gear icon for the last plugin - it's displaying under the debug tool bar

### Additional info

- Craft version: 3.3.20.1

**Comment by brandonkelly** [comment]
This is covered by #4591 - and we’ve fixed it for the upcoming 3.4 release :)
