### ISSUE TITLE
Super Table field data not showing in Preview (graphql)

### ISSUE THREAD

**Issue by hannahwoodward** [craftcms/cms#5458]
### Description
I wasn't sure whether it was a Super Table or Craft issue - thought I'd post here first.

A client reported that preview wasn't updating for an entry (it was the first time they'd tried out preview, as we've only recently implemented it). On investigating, I found that everything except the super table field was updating correctly, and the super table field was returning an empty array. Querying for the entry normally (i.e. without preview query string) returns the super table field data as expected.

The site is headless, and the frontend is built using Nuxt & Graphql. The same problem is is happening both locally & on production.

### Steps to reproduce

1. Set up a headless site, using graphql to query data
2. Create Super Table field & add to a entry
2. When editing the entry, open in preview (or share the link)

### Additional info

- Craft version: 3.3.20.1
- PHP version: 7.3.4
- Database driver & version: 5.7.25
- Plugins & versions: Amazon S3 (1.2.7), Contact Form (2.2.6), Contact Form Honeypot (1.0.2), Expanded Singles (1.0.7), Redactor (2.4.0), SEOmatic (3.2.38), Super Table (2.3.2)

**Comment by brandonkelly** [comment]
Can you post your GraphQL query?

**Comment by hannahwoodward** [comment]
Also, trying the same query in Postman yields the same result. The endpoint I'm posting to has the format `https://cms.site.com/api?x-craft-preview=e3lEeidpQx&token=yu2vsvlMCIxyduUI88_cShJzImOmz5Hi`

Unsure if useful, but the response:
```
{
    "data": {
        "entries": [
            {
                "slug": "some-page-slug",
                "title": "Some Page Title",
                "uri": "lp/some-page-slug",
                "heroTitle": "Edited page title updated in preview...",
                "pageBuilderAlt": []
            }
        ]
    }
}
```

**Comment by brandonkelly** [comment]
Thanks, the query looks fine. I suspect this is a Super Table bug. Can you post over at https://github.com/verbb/super-table/issues and then link to it from here, so we can try to help them out with it?
