### ISSUE TITLE
Craft.VueAdminTable does not display search box when `search` set to `true`

### ISSUE THREAD

**Issue by BenParizek** [craftcms/cms#5460]
### Description

It appears the search box only displays if `search` is set to `true` and `tableData` has no length, such as `[]`.

I don't feel I know the full scope of this Vue code yet but this appears like it may be part of the problem:
https://github.com/craftcms/cms/pull/5459

### Steps to reproduce

The following configuration will display a search box:

``` javascript
new Craft.VueAdminTable({
...
tableData: [],
search: true,
...
});
```

However, if an array is passed to `tableData` the search box will disappear.

### Additional info

- Craft version: 3.4.0-RC2

**Comment by nfourtythree** [comment]
Hi @BenParizek 

In its current incarnation, the Vue admin table search is only supported for tables that are provided data via an endpoint. Therefore using the `tableDataEndpoint` param.

I can see that this is probably not entirely obvious from the code.

Further documentation is on the way in regards to how to use the Vue admin table with an endpoint.

An example of what the endpoint would look like, for data return and search, can be seen for Customers in the upcoming Commerce 3 release: https://github.com/craftcms/commerce/blob/3.0/src/controllers/CustomersController.php#L100-L223

Hope this helps!
