### ISSUE TITLE
Cannot create "single" section type in 3.4.0-RC2

### ISSUE THREAD

**Issue by mattwaler** [craftcms/cms#5462]
### Description

I am able to create channels and structures, but attempting to create singles leads to this error. Note, the number grows by 1 every time I attempt to create a new single section:

![Screen Shot 2020-01-19 at 2 46 03 PM](https://user-images.githubusercontent.com/32300026/72687297-70e3bf00-3aca-11ea-84f7-bdcb12c3bb37.jpg)

### Steps to reproduce

1. Attempt to create single type
2. Get error

### Additional info

- Craft version: 3.4.0-RC2
- PHP version: 7.1.31
- Database driver & version: MySQL 5.7.26
- Plugins & versions: N/A

**Comment by andris-sevcenko** [comment]
It's definitely an issue introduced by https://github.com/craftcms/cms/commit/c1958d243b7a079416e0e042056c07769ccc4132

Trying to think the cleanest way around this, so it doesn't end up being just a hack with ramifications down the road.

**Comment by brandonkelly** [comment]
This has been fixed for the next 3.4 release. Thanks for reporting.

**Comment by brandonkelly** [comment]
Craft 3.4.0-RC3 is out now with the fix.
