### ISSUE TITLE
Package zendframework/zend-stdlib is abandoned

### ISSUE THREAD

**Issue by Sceko** [craftcms/cms#5464]
after composer update

Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.
Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead.
Package zendframework/zend-feed is abandoned, you should avoid using it. Use laminas/laminas-feed instead.

**Comment by brandonkelly** [comment]
This is already covered by #5400, and fixed in Craft 3.4.
