### ISSUE TITLE
Entry search with punctuation causes SQL error

### ISSUE THREAD

**Issue by MattRogowski** [craftcms/cms#5466]
### Description
I have followed the steps [here](https://docs.craftcms.com/v3/dev/element-queries/entry-queries.html#search) to search entries, however if your search term includes punctuation such as a period or apostrophe, you receive an SQL error when searching.

```
{% set search = craft.app.request.getQueryParam('search') ?? '' %}

{% set entries = craft
.entries()
.search(search)
.all() %}
```

If you then search for `te.st` or `te'st`, it errors as follows:

![Screenshot 2020-01-20 at 21 53 45](https://user-images.githubusercontent.com/545339/72760046-868edc80-3bcf-11ea-909c-8f27625259c7.png)

If I change `.search(search)` to `.search(search | escape)` the issue is resolved, however the documentation does not say to do this, and I find it strange that it doesn't do this internally by default if simple punctuation causes an error without it.

### Additional info

- Craft version: Craft Pro 3.3.20.1
- PHP version: 7.2.20
- Database driver & version: MySQL 5.6.45
- Plugins & versions:

**Comment by angrybrad** [comment]
@MattRogowski are you using the InnoDB storage engine on the `searchindex` table in the database by chance?  If so, it sounds like you're running into this https://github.com/craftcms/cms/issues/3862, which is a bug in MySQL.  We _just_ put a workaround for it into Craft 4 days ago (https://github.com/craftcms/cms/issues/3862#issuecomment-575770787), but it's on the 3.4 branch, so you'd need to update to that to take advantage of it.
