### ISSUE TITLE
The sessions table fills up really fast

### ISSUE THREAD

**Issue by TonyDeStefano** [craftcms/cms#5467]
### Description

Ever since upgrading to 3.3 we are getting a lot of authentication/token errors and noticed that the sessions table fills up really fast. Just logging in and attempting a live preview created 37 records in the session table for my user (many at exactly the same time). And when attempting live preview, we get a 403 error on this request nearly every time:

/index.php?p=admin/actions/preview/create-token

{"error":"User is not authorized to perform this action"}

![Screen Shot 2020-01-20 at 3 14 16 PM](https://user-images.githubusercontent.com/5439786/72763218-8d99f880-3b97-11ea-9f22-126a75bfb8b6.png)

### Steps to reproduce

1. Log into craft
2. Use live preview
3. View the contents of the sessions table

### Additional info

- Craft version: 3.3.20.1
- PHP version: 7.3
- Database driver & version: MySql 5.7
- Plugins & versions: Element API

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you verify that the DB connection user has read access to the `sessions` table?

**Comment by TonyDeStefano** [comment]
Yes, I just verified that the connection has read access to that table. We tried playing with the userSessionDuration, rememberedUserSessionDuration, enableCsrfCookie andenableCsrfProtection flags in general.php but ended up getting into a state where we could log in, but the minute we tried to do anything, we were immediately logged out. What are your recommended settings for those flags? Also, our Craft install is not public, so we aren't worried about CSRF issues.

**Comment by brandonkelly** [comment]
In your browser developer tools’ Application tab, are you seeing a `CraftSessionId` session cookie?

**Comment by TonyDeStefano** [comment]
We see it when we have enableCsrfProtection set to true, but not when we set it to false.

**Comment by brandonkelly** [comment]
Weird… CSRF shouldn’t have any impact on whether you get a PHP session cookie. I’d start by trying to figure out why that cookie isn’t making its way to the browser.

**Comment by TonyDeStefano** [comment]
I think we found the issue. Our Craft install is load-balanced in a docker swarm between several nodes. Once we reduced the number of nodes to 1, everything works again. But when we increase it to more than one, we lose the ability to log in and stay logged in. We have been using this docker setup for a long time. So maybe something about how sessions are stored changed in 3.3?

**Comment by brandonkelly** [comment]
3.3.18.4 contained a bugfix where users’ identity cookies (which are supposed to expire at the same time as the PHP-based session, and only meant to be a fallback in the event that the PHP session goes away) were getting renewed when they shouldn’t (#3951). It’s possible that your environment was relying on that buggy behavior to a degree, and made worse by the bug fix.

Beyond that, nothing has really changed since 3.1.0, which is when user sessions started relying on the `sessions` table.

**Comment by brandonkelly** [comment]
@TonyDeStefano I take it you go to the bottom of this?

**Comment by TonyDeStefano** [comment]
Yeah, we implemented redis and all of our session problems went away. Thanks! :)

**Comment by brandonkelly** [comment]
Glad to hear!
