### ISSUE TITLE
Stupid height on SOLO :)

### ISSUE THREAD

**Issue by Sceko** [craftcms/cms#5468]
If open admin/plugin-store
solo change height 
![Screenshot 2020-01-21 at 00 27 38](https://user-images.githubusercontent.com/2323952/72763613-d75d0000-3be4-11ea-99f8-0611ee570f83.png)
to
![Screenshot 2020-01-21 at 00 27 12](https://user-images.githubusercontent.com/2323952/72763601-c613f380-3be4-11ea-9c8d-2fd75c882c4c.png)

**Comment by brandonkelly** [comment]
Thanks for reporting that. It’s now fixed for Craft 3.4.
