### ISSUE TITLE
The proposal 

### ISSUE THREAD

**Issue by Sceko** [craftcms/cms#5469]
Its been great to add in fields like in entries or category 
![Screenshot 2020-01-21 at 00 28 35](https://user-images.githubusercontent.com/2323952/72763674-23a84000-3be5-11ea-80cc-7d0df21051f4.png)
Settings to change position, i know that i can change in Design but been great to add on fields

And tell me for what is tags? why not add in tags like in categories URI
![Screenshot 2020-01-21 at 00 32 20](https://user-images.githubusercontent.com/2323952/72763750-7eda3280-3be5-11ea-9fa9-e1fce77e1341.png)
And same possibility like Categories and manage tags page

**Comment by brandonkelly** [comment]
Are you asking for the ability to show custom field values in the index table columns? That is already possible – click on one of the source names in that Customize modal, and then check the boxes next to your custom field names.

**Comment by brandonkelly** [comment]
So are you asking for the ability to reorder field groups? And if so, why?

**Comment by Sceko** [comment]
yes and for globals to, why have category to? for that

**Comment by brandonkelly** [comment]
Field groups aren’t visible to authors, so there’s no reason to reorder them.

The request to make globals sortable is already covered by #2682.
