### ISSUE TITLE
1 more question for tags

### ISSUE THREAD

**Issue by Sceko** [craftcms/cms#5472]
Sorry 1 more question did you add page for tags like category? and with url  
![72763750-7eda3280-3be5-11ea-9fa9-e1fce77e1341](https://user-images.githubusercontent.com/2323952/72847850-a7286680-3ca3-11ea-94a3-375541dbfba4.png)
without this it is totally useless and page for delete tags edit... all like in category

**Comment by brandonkelly** [comment]
No, we are not adding any new features to tags (or categories) at this point, because they are both going away in Craft 4.  Existing tags & categories will be transformed into entries at that point.

**Comment by Sceko** [comment]
i agree great fine news, and price to craft like nove and for multiple using and best cms ever :)
