### ISSUE TITLE
Gracefully handle permission issues with project.yaml in docker mounts

### ISSUE THREAD

**Issue by ul8** [craftcms/cms#5474]
### Description

Saving new fields when project.yaml is not writable results in broken CP.  This should be handled better, i. e. cancelling the whole save without any changes to the DB.

### Steps to reproduce

1. make project.yaml not writable for web server (we know there are a lot of situations this may and will happen accidentally)
2. Save a new field
3. We get an error message saying project.yaml can't be written.
4. any subsequent access to control panel shows a Unknown Property – yii\base\UnknownPropertyException in yii2/base/BaseObject.php:163

### Additional info

- Craft version: 3.3.20.1
- PHP version: 7.3
- Database driver & version: Postgres 11
- Plugins & versions: none
- Using Docker for Mac 2.2.0.0

**Comment by brandonkelly** [comment]
We just addressed this in Craft 3.3.20 (983d1664536ad9237e9cd69a25db4240640b6f86) – now the control panel should be displaying a nag alert across the top if it detects that your `project.yaml` file isn’t writable:

![An alert in the control panel saying that project.yaml isn’t writable](https://user-images.githubusercontent.com/47792/72352694-94a4a080-3697-11ea-82f9-0163e46697d0.png)

You said you are on 3.3.20.1; are you not seeing this banner?

**Comment by ul8** [comment]
I tested this a bit, seems like the nag alert only checks for permissions, but not for file ownership. So for example, if the file is owned by root with 744 permissions (and the web server runs as www-data), there won't be any nag screen displayed.

**Comment by brandonkelly** [comment]
Strange; our method to detect writability literally attempts to get a write handle on the file, and returns whether that was successful:

https://github.com/craftcms/cms/blob/4d11acc31e4820a56fcc4f9f6b15e6936fe0f174/src/helpers/FileHelper.php#L247-L258

I just tried that exact setup – created a file, set owner to root & permissions to 744, and `FileHelper::isWritable()` came back `false`.

**Comment by ul8** [comment]
Yes it's really odd, I agree. It definitely has that effect here though - the banner gets shown or not shown as I chown the file. The file is inside a docker container and mounted, maybe that has some sort of influence on it all. If it is an edge case like that probably not worth bothering with this much more. Thanks!

**Comment by narration-sd** [comment]
Makes one think of the difference between uid/gid 'ownership' handles inside and outside Docker containerse, doesn't it?

It looks like there's been a feature added to handle this more nicely than in earlier days -- perhaps this article will help:  https://seravo.fi/2019/align-user-ids-inside-and-outside-docker-with-subuser-mapping

**Comment by brandonkelly** [comment]
Relinquishing this one to @angrybrad :)

**Comment by angrybrad** [comment]
This is why I'm angry.

**Comment by narration-sd** [comment]
indeed... 🌲🌲

**Comment by angrybrad** [comment]
Going to chalk this up as an edge case... I've got tried with project.yaml inside of a docker mount and have tried changing ownership (root:root) and permissions (0444) and various combinations and always get the "Your project.yaml file isn’t writable." nag alert in the CP as expected.

**Comment by angrybrad** [comment]
Also tried this with a read-only mount:

    - ./config:/var/www/html/config:ro

And couldn't reproduce it, either.
