### ISSUE TITLE
Layout issues when page has scrollbar

### ISSUE THREAD

**Issue by rynpsc** [craftcms/cms#5476]
### Description

When any page in the CP has a vertical scroll bar the user-info component gets cut off (right alignment with other elements is also off when not present).

The right gutter is also mostly cut off when the scroll bar is present making the spacing between the UI and scrollbar a bit too tight.

Going to take a guess and say it's because the UI is using 100vw in various places which is always going to create issues as soon as scrollbars are introduced.
 
<img width="205" alt="Screenshot 2020-01-22 at 19 30 16" src="https://user-images.githubusercontent.com/5955881/72928173-6b4adb00-3d4f-11ea-8bdd-e02d2f3e72b7.png">
<img width="348" alt="Screenshot 2020-01-22 at 19 32 46" src="https://user-images.githubusercontent.com/5955881/72928174-6b4adb00-3d4f-11ea-93c0-7e81ce2e9b3d.png">

**Comment by brandonkelly** [comment]
> (right alignment with other elements is also off when not present)

The image itself is in alignment. But yeah that doesn’t look great when the scrollbar is present, so I’ll go ahead and make the caret icon the thing that gets aligned instead.

**Comment by brandonkelly** [comment]
This has been resolved for the next Craft 3.4 release.

<img width="162" alt="A screenshot of the user menu" src="https://user-images.githubusercontent.com/47792/72939970-cdd9b200-3d22-11ea-9e2f-851d44a246fe.png">
