### ISSUE TITLE
Contents of console.log not equal web.log file for non-devMode environments

### ISSUE THREAD

**Issue by bertoost** [craftcms/cms#5479]
### Description

I noticed a difference between the `console.log` and the `web.log` files. The contents of the web.log file are based on the `$devMode` config setting. Whether or not logging info/debug/profile messages.
That's different for the `console.log` file. When bootstrapping the console, devMode is hard-coded set to `true` and this causes the console.log always contains a lot more messages, even on production-environments (where I configure `$devMode` to `false`)

The lines of code I am talking about can be found here;
https://github.com/craftcms/cms/blob/develop/bootstrap/bootstrap.php#L170-L184

For production-like environments, where `$devMode` is configured `false`, the `console.log` should also respect the same logging levels as for the `web.log` file.

### Workaround

For now I have configured my app config to overrule the log component and overwrite the target levels, for production-like environments.
For those interested in this;

`config/app.php`

```php
<?php

return [
    '*' => [
        // ...
        'components' => [
            'log' => static function () {
                $config = \craft\helpers\App::logConfig();
                $config['targets']['levels'] = \yii\log\Logger::LEVEL_ERROR | \yii\log\Logger::LEVEL_WARNING;

                return $config;
            },
        ],
    ],

    // Dev environment settings
    'dev' => [
        'components' => [
            'log' => static function () {
                // same as Craft's default
                $config = \craft\helpers\App::logConfig();
                return $config ? Craft::createObject($config) : null;
            },
        ],
    ],
];
```

### Additional info

- Craft version: 3.3.20.1
- PHP version: 7.4.1
- Database driver & version: MySQL 8.0
- Plugins & versions: -

**Comment by justinmacleod** [comment]
I just noticed this today myself when switching to using queue/listen. I see in #5256 this was marked as being resolved by @brandonkelly but it doesn't appear to have solved the issue. Thanks for the work around above, I'm going to implement that.

**Comment by brandonkelly** [comment]
Since this is the exact same issue as #5256, I’ve reopened that and will close this as a duplicate.
