### ISSUE TITLE
Special characters not stripped from generated slug (3.4)

### ISSUE THREAD

**Issue by pierrepavlov** [craftcms/cms#5480]
### Description

When creating a new entry which contains special characters (in my case åäö) they are not stripped/replaced from the automatically generated slug. Usually they are replaced like å/ä -> a and ö -> o.

### Steps to reproduce

1. Install Craft 3.4 beta.
2. Create entry with åäö in title.

### Additional info

- Craft version: 3.4.0-RC3
- PHP version: 7.3.12
- Database driver & version: MariaDB 10.3.11
- Plugins & versions: None (tried with blank installation)

**Comment by brandonkelly** [comment]
That will only happen if the [limitAutoSlugsToAscii](https://docs.craftcms.com/v3/config/config-settings.html#limitautoslugstoascii) config setting is enabled (it’s disabled by default).

**Comment by pierrepavlov** [comment]
@brandonkelly Okay, thanks! Wasn't sure if that was expected since I don't have enough knowledge about browsers handling special characters in URLs I guess.
