### ISSUE TITLE
Craft 3.4 RC3: Saving plugin settings crashes on project config

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#5483]
This issue was reported re: Image Optimize plugin and Craft CMS 3.4 RC3:

https://github.com/nystudio107/craft-imageoptimize/issues/188

On a site running Craft 3.4 RC3, when I try to change and save (or just save) the plugin's settings, the site crashes with the following error:

```
yii\base\ErrorException: array_key_exists() expects parameter 2 to be array, null given in /Users/jhenckens/Sites/okaweb/vendor/craftcms/cms/src/services/ProjectConfig.php:1727
Stack trace:
#0 /Users/jhenckens/Sites/okaweb/vendor/craftcms/cms/src/web/ErrorHandler.php(74): craft\web\ErrorHandler->handleError()
#1 /Users/jhenckens/Sites/okaweb/vendor/craftcms/cms/src/services/ProjectConfig.php(1727): craft\web\ErrorHandler->handleError()
#2 /Users/jhenckens/Sites/okaweb/vendor/craftcms/cms/src/services/ProjectConfig.php(1727): ::array_key_exists()
#3 /Users/jhenckens/Sites/okaweb/vendor/craftcms/cms/src/services/ProjectConfig.php(1597): craft\services\ProjectConfig->_loadInternalConfigData()
#4 /Users/jhenckens/Sites/okaweb/vendor/craftcms/cms/src/services/ProjectConfig.php(1586): craft\services\ProjectConfig->_getStoredConfig()
#5 /Users/jhenckens/Sites/okaweb/vendor/craftcms/cms/src/services/ProjectConfig.php(397): craft\services\ProjectConfig->_getLoadedConfig()
#6 /Users/jhenckens/Sites/okaweb/vendor/craftcms/cms/src/base/ApplicationTrait.php(1375): craft\services\ProjectConfig->get()
#7 /Users/jhenckens/Sites/okaweb/vendor/craftcms/cms/src/base/ApplicationTrait.php(1333): craft\web\Application->_setTimeZone()
#8 /Users/jhenckens/Sites/okaweb/vendor/craftcms/cms/src/web/Application.php(100): craft\web\Application->_preInit()
#9 /Users/jhenckens/Sites/okaweb/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#10 /Users/jhenckens/Sites/okaweb/vendor/yiisoft/yii2/base/Application.php(206): craft\web\Application->__construct()
#11 /Users/jhenckens/Sites/okaweb/vendor/craftcms/cms/src/web/Application.php(91): craft\web\Application->__construct()
#12 /Users/jhenckens/Sites/okaweb/vendor/yiisoft/yii2/di/Container.php(400): craft\web\Application->__construct()
#13 /Users/jhenckens/Sites/okaweb/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs()
#14 /Users/jhenckens/Sites/okaweb/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build()
#15 /Users/jhenckens/Sites/okaweb/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#16 /Users/jhenckens/Sites/okaweb/vendor/craftcms/cms/bootstrap/bootstrap.php(245): yii\BaseYii::createObject()
#17 /Users/jhenckens/Sites/okaweb/vendor/craftcms/cms/bootstrap/web.php(51): ::unknown()
#18 /Users/jhenckens/Sites/okaweb/public/index.php(20): ::unknown()
#19 {main}
```

When saving settings for other plugins (SEOmatic, feed-me, freeform), the error doesn't present itself, so it appears to be something specific to this plugin.

Let me know if you need more information or need me to test something.

**Comment by khalwat** [comment]
The only thing I do "special" here is the use of Fields ->

https://github.com/nystudio107/craft-imageoptimize/blob/v1/src/models/Settings.php#L361

So that a subset of the actual model is what ends up being used/validated. Maybe Project Config doesn't like this standard Yii-ism, or I'm doing it wrong somehow?

**Comment by khalwat** [comment]
I can't replicate this @janhenckens 

I'm running Craft CMS 3.4.0-RC3 and I:

* Go to the Settings page
* Click on Image Optimize
* Click on Save

...and everything works as expected.

Are there are any additional things I need to be doing here to replicate this issue?

**Comment by janhenckens** [comment]
That's what does it for me. Here's a screen recording: https://drive.google.com/file/d/1YErE_CIhNrw59OtHEkyUBOClBWVs2YY9/view?usp=sharing

**Comment by andris-sevcenko** [comment]
@janhenckens can you shoot over the DB backup, `composer.json` and `composer.lock` files to support@craftcms.com and reference this issue, please?

**Comment by janhenckens** [comment]
@andris-sevcenko Done!

**Comment by andris-sevcenko** [comment]
This has been fixed for the next release.

The issue was that, with the new Project Config table, if a value was set to `null` (for example, I dunno, plugin settings on install?) and later changed to an array (when saving the said settings, for example), the original value also remained in the table, causing Craft to explode when attempting to translate the project config table into a nested array.

I fixed it so that the original entry is removed (because you can't hold an array AND be a value yourself) on nested entry update, but that would still error out for existing glitched configs, so I made the translation process more robust as well where so that it doesn't choke on malformed values like this, anymore.
