### ISSUE TITLE
Share button appears even when there are no Entry URI Formats, Templates or Preview Targets

### ISSUE THREAD

**Issue by terryupton** [craftcms/cms#5484]
### Description
The share button appears on entries that don't have any Entry URI Formats, Templates or Preview Targets - this results in a blank screen.

**Comment by brandonkelly** [comment]
What version of Craft are you using?

If you resave your entry, does the button go away?

**Comment by Mosnar** [comment]
Seeing this on 3.4-RC3

- Resaving the entry does not fix it. 
- Resaving the section does not fix it.

**Comment by brandonkelly** [comment]
Not seeing it locally. Can one/both of you send in a database backup plus your `composer.json` and `composer.lock` files to support@craftcms.com, and reference this issue URL + where you’re seeing the unwanted Share button?

**Comment by Mosnar** [comment]
@terryupton Are you using SEOmatic? I discovered that in my case, this exact issue was caused by SEOmatic registering preview targets, even though there aren't URLs for the section. The result is a preview and share button that just show a blank white page.

Looping in @khalwat

**Comment by khalwat** [comment]
🤔 I wonder if each plugin/module should check whether there are URLs for a section, or if Craft should just not throw that even if there are no URLs for a section.

I could see arguments both ways, so will side with whatever @brandonkelly wants to do.

**Comment by terryupton** [comment]
@Mosnar - Yes also using SEOmatic.
@khalwat I raised a similar thread yesterday on SEOmatic repo - https://github.com/nystudio107/craft-seomatic/issues/541

**Comment by terryupton** [comment]
@brandonkelly files have been sent over...

**Comment by brandonkelly** [comment]
@khalwat One of the major benefits of Preview Targets is that you can preview entries that don’t have URLs, so we should definitely keep throwing the event. I’d say just check if the entry has a `uri` before adding the SEO preview.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/6f2c078f8ace5f4600eff8f81715678b48bb7fbb
