### ISSUE TITLE
[3.4.0-RC3] Asset detail pages do not load Javascript

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#5485]
### Description

Buttons do not work, obviously because no javascript is loaded.

### Steps to reproduce

1. Open asset detail page e.g /admin/assets/images/27-cinema?site=en
2. Click Preview/Edit/Download etc (except save)

### Additional info

- Craft version: 3.4.0-RC3
- PHP version: 7.2.14
- Database driver & version: MySQL 5.7.14
- Plugins & versions: None

/By Melissa

**Comment by brandonkelly** [comment]
It’s working fine on my end. Are you getting any JavaScript errors on the page?

**Comment by wsydney76** [comment]
@brandonkelly 

![image](https://user-images.githubusercontent.com/60010597/73034871-89473700-3e46-11ea-8958-f4ec67862754.png)

But turns out it has to do with an assetbundle we load that is registered via `View::EVENT_BEFORE_RENDER_TEMPLATE`

```
public function init()
    {
        $this->sourcePath = __DIR__ . '/dist';

        $this->depends = [
            CpAsset::class
        ];

        $this->css = [
            version_compare(Craft::$app->version, '3.4', '>=') ?
                'cp_styles34.css' :
                'cp_styles.css'
        ];

        parent::init();
    }

```

Whereas all other pages i checked work fine, no JavaScript is loaded on the asset edit pages:

![image](https://user-images.githubusercontent.com/60010597/73035607-096e9c00-3e49-11ea-95ad-6db2b49d8a79.png)

while css is loaded:

![image](https://user-images.githubusercontent.com/60010597/73035678-55b9dc00-3e49-11ea-9332-a8f7ca2efb02.png)

Uncommenting the `depends` part fixes the javascript problem, but puts our custom css first, so it is overwritten by the  Craft standards.

/Melissa

PS.  As you can still edit assets the old fashioned way, that's a minor issue for us.

**Comment by AndrewMac** [comment]
Just wanted to add that I found quite a few plug-ins in that create this problem as well. These are the ones I was able to identify, but obviously there could be heaps more:

Calendar
Control Panel CSS
CP Field Inspect
Embedded Assets
Icon Picker
Redactor Anchors
SearchIt
Smith

This is, perhaps, going to be quite a widespread issue, as it seems something has changed in Craft 3.4 core that exposes these problems. Is this something that Pixel and Tonic can address with a general notice to developers, or is it something we should take up with them individually?

Thanks heaps!

**Comment by brandonkelly** [comment]
Very strange… will look into it.

**Comment by brandonkelly** [comment]
Alright, this is all fixed for the next 3.4 release!

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "3.4.x-dev as 3.4.0-RC3",
  "...": "..."
}
```

Then run `composer update`.

**Comment by Mosnar** [comment]
@brandonkelly 😅

**Comment by AndrewMac** [comment]
Hi Brandon
Thanks so much for that. It's fixed the issues with all those plugins :-)

**Comment by brandonkelly** [comment]
Glad to hear that!
