### ISSUE TITLE
[Question] How to use siteName/siteUrl on console

### ISSUE THREAD

**Issue by bertoost** [craftcms/cms#5486]
### Description

For some processes I am using the command line interface, set as cronjob. Some jobs are sending some emails, but the email-template is using the `{{ siteUrl }}` variable for loading the image. 
Therefore this variable is rendered as `@web` alias, but not rendered.
I guess, because the console isn't aware of the web context, and not able to load such aliases/variables because he simply don't know about it.

Is there a way to tell the system which site to load? So this variables/aliases are working as well?

### Additional info

- Craft version: 3.3.20.1
- PHP version: 7.4.1

**Comment by brandonkelly** [comment]
It’s only a good idea to use `@web` for your site URL if you are explicitly defining what it should point to, from your [aliases](https://docs.craftcms.com/v3/config/config-settings.html#aliases) config setting.

If you have multiple sites, you should define separate specific aliases/environment variables to store each of their base URLs, and just not use `@web` anywhere.

**Comment by bertoost** [comment]
Okay.. I always was used to use `@web` alias.
Once I defined environment variables these are not parsed by Craft either.
It looks like only environment variabels set into `.env` are parsed. But as I develop and deploy with Docker containers, I define these variables elsewhere and not using the `.env`. Is there a way to get this working then?

**Comment by brandonkelly** [comment]
It doesn’t matter how the environment variables are defined, so long as they exist at runtime.

You can set your site’s URL to the environment variable value by typing its name prefixed with `$` into the setting field. See the example [here](https://docs.craftcms.com/v3/config/environments.html).

Note that environment variables cannot have additional things appended to them though (e.g. `$VAR_NAME/images`). If you want to use an environment variable as the base value for multiple settings, then you will need to create an alias based off its value in `config/general.php`:

```php
'aliases' => [
    '@web' => getenv('BASE_URL'),
],
```

From there you will be able to safely use `@web/images` or whatever.

**Comment by bertoost** [comment]
Thanks @brandonkelly ! I have managed to fix this 👍
