### ISSUE TITLE
Craft 3.4-RC 3: Potential Craft 2 migration content loss

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#5487]
### Description
During a run-through of a Craft 2 -> Craft 3.4 migration, I ran into an odd issue where a column in a matrix content table for a custom plugin was dropped. By re-running the migration to Craft 3.3 and then to 3.4, the column was preserved as expected, so I think there may be something funny going on with the project config. 

The column that was dropped was a Linkit field data column in a matrix content table.

The Craft 2 database I supplied via email last week is the same one I ran this on.

This is not a pressing issue for me at this point and I've been able to move-on, but I thought I should post it since it deals with unexpected content loss.

### Additional info

Craft version: 2.7.4 -> 3.4-RC3
PHP version: 7.3
Database driver & version: MySQL 8
Plugins & versions: N/A?

**Comment by brandonkelly** [comment]
Followed up privately via email.
