### ISSUE TITLE
403 (Forbidden) Error when attempting to access Live Preview or Share functions on production server

### ISSUE THREAD

**Issue by compass360** [craftcms/cms#5488]
### Description
When a user (even an Admin) attempts to access the Live Preview or Share functionality on the publish/edit form in CP, an alert flashes "An unknown error occurred", and a 403 error appears in the browser console:

`[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (index.php, line 0)     https://[domain]/index.php?p=admin/actions/preview/create-token`

This happens **infrequently**, and sometimes a user is able to access the expected functionality. See below for a more detailed log and stack trace.

### Steps to reproduce

1. Visit the publish/edit form for any entry
2. Use the "Preview" or "Share" buttons
3. See an error
4. Watch Craft increment the draft version # because that's fun too

### Additional info

- Craft version: 3.3.18.1
- PHP version: 7.3.10
- Database driver & version: MySQL 5.6.34
- Plugins & versions: Not sure if any plugins are relevant (this effects forms with no plugins present)

### Log Information:

`apache_access  99.231.65.105 - - [23/Jan/2020:15:11:54 +0000] "POST /index.php?p=admin/actions/preview/create-token HTTP/1.1" 403 1471 "https://[domain]/admin/entries/jobPostings/5330-maintenance-automation-technician?site=en&draftId=93" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Safari/605.1.15"`

`web_php_error  2020-01-23T15:11:54Z Stack trace:
web_php_error  2020-01-23T15:11:54Z 2020-01-23 10:11:54 [-][1][-][error][yii\web\HttpException:403] yii\web\ForbiddenHttpException: User is not authorized to perform this action in /srv/app/mitchell/htdocs/vendor/craftcms/cms/src/web/Controller.php:309
web_php_error  2020-01-23T15:11:54Z #2 /srv/app/mitchell/htdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
web_php_error  2020-01-23T15:11:54Z #0 /srv/app/mitchell/htdocs/vendor/craftcms/cms/src/controllers/PreviewController.php(70): craft\web\Controller->requireAuthorization('previewDraft:93')
web_php_error  2020-01-23T15:11:54Z #1 [internal function]: craft\controllers\PreviewController->actionCreateToken()
web_php_error  2020-01-23T15:11:54Z #3 /srv/app/mitchell/htdocs/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
web_php_error  2020-01-23T15:11:54Z #4 /srv/app/mitchell/htdocs/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('create-token', Array)
web_php_error  2020-01-23T15:11:54Z 'p' => 'admin/actions/preview/create-token'
web_php_error  2020-01-23T15:11:54Z #5 /srv/app/mitchell/htdocs/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('create-token', Array)
web_php_error  2020-01-23T15:11:54Z #6 /srv/app/mitchell/htdocs/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('preview/create-...', Array)
web_php_error  2020-01-23T15:11:54Z #7 /srv/app/mitchell/htdocs/vendor/craftcms/cms/src/web/Application.php(565): craft\web\Application->runAction('preview/create-...', Array)
web_php_error  2020-01-23T15:11:54Z #8 /srv/app/mitchell/htdocs/vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
web_php_error  2020-01-23T15:11:54Z #9 /srv/app/mitchell/htdocs/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
web_php_error  2020-01-23T15:11:54Z #10 /srv/app/mitchell/htdocs/web/index.php(21): yii\base\Application->run()
web_php_error  2020-01-23T15:11:54Z #11 {main}`

**Comment by brandonkelly** [comment]
We’ve seen this happen when the [defaultCookieDomain](https://docs.craftcms.com/v3/config/config-settings.html#defaultcookiedomain) config setting is changed, due to a browser caching bug.

Can you try clearing your browser caches (including cookie caches) and see if that helps?

**Comment by compass360** [comment]
I assumed it was something related to cookies or sessions... alas I’ve tried clearing all of that and running in private modes and it doesn’t improve the situation. I don’t believe I’ve changed that config setting, though I am deploying with Fortrabbit Copy, so could there be some residual cacheing or session info that also needs to be flushed before/after deployment?

**Comment by brandonkelly** [comment]
Only other thing I can think of is, if it’s a load-balanced environment, you’ll need to make sure that all servers are sharing the same data cache, ideally by sharing a single Redis server or something like that. We give a few examples on the [Application Configuration](https://docs.craftcms.com/v3/config/app.html#cache-component) page in the docs.

**Comment by compass360** [comment]
We could try Memcached, which FortRabbit makes easy to implement, and see if it solves it. Thanks for your thoughts!

**Comment by brandonkelly** [comment]
Sorry, in addition to sharing a data cache, they should also share the same session storage as well. Examples here: https://docs.craftcms.com/v3/config/app.html#session-component

**Comment by compass360** [comment]
I've confirmed with support on FortRabbit's end that there's no load-balancing going on in our single-node environment that would benefit from caching/storage like this. Any other suggestions?

**Comment by ostark** [comment]
Hey P&T,
 I'll review the issue today. Since this is not the first App we host :), it must be related to the config somehow.

**Comment by compass360** [comment]
Thanks to the awesome FortRabbit team, we were able to diagnose this as a session/cache issue and have integrated [Memcached](https://github.com/fortrabbit/yii-memcached). All appears to be working as intended. Thanks everyone for taking a look.

**Comment by brandonkelly** [comment]
Awesome – thanks @ostark !
