### ISSUE TITLE
resave entry job fails when disabling default site for a section

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#5489]
**Steps to reproduce**

1. enable a channel section with 3 enabled sites including default site and set propagation method to propagate to all sites
2.  create a new entry
3. disable section for default site // in my case site id 1
4. there is a failed job
5. thanks to queue manager in 3.4:
**error:** 
The section 'test' is not enabled for the site '1' 
**job data:**
{
    "elementType": "craft\\elements\\Entry",
    "criteria": {
        "sectionId": 1,
        "siteId": "*",
        "unique": true,
        "status": null,
        "enabledForSite": false
    },
    "description": "Resaving test entries"
}

**Additional info**
it seems there are some open issues like mine
https://github.com/craftcms/cms/issues/3767 //some comments say they have errors on deleting site id 1
https://github.com/craftcms/cms/issues/3725

- Craft version: 3.4 RC3 //also on 3.3
- PHP version: 7.2

**Comment by brandonkelly** [comment]
Thanks for reporting that! It’s now fixed for the next 3.4 release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "3.4.x-dev#e8d9d726988feec9b620bb7a234a2752039d46ad as 3.4.0-RC3",
  "...": "..."
}
```

Then run `composer update`.
