### ISSUE TITLE
Feature Request: Read only mode for project.yaml

### ISSUE THREAD

**Issue by henrypenny** [craftcms/cms#5491]
### Description

The way I use Craft involves making CMS changes on my local set up and getting them into production via git and project.yaml. I don't want clients to make changes that end up in project.yaml in production.
It would be nice to have the production environment be able to read project.yaml but not update it.

Currently it seems like the only option is use it (read and write) or don't use it at all.

**Comment by brandonkelly** [comment]
This is exactly hat the [allowAdminChanges](https://docs.craftcms.com/v3/config/config-settings.html#allowadminchanges) config setting is for :) In fact we [recommend](https://docs.craftcms.com/v3/project-config.html#production-changes-may-be-forgotten) that you disable that setting for all non-development environments.
