### ISSUE TITLE
Multiple Queues to Handle Custom Tasks

### ISSUE THREAD

**Issue by matthewmrotter** [craftcms/cms#5492]
It's be great if Craft supported a multi-queue setup so that first-party craft tasks could be handled by one worker and our custom tasks were handled by a totally separate worker.

**Comment by brandonkelly** [comment]
It’s already possible to define additional queues using [other queue drivers](https://github.com/yiisoft/yii2-queue/blob/master/docs/guide/README.md#queue-drivers), but our own [craft\queue\Queue](https://docs.craftcms.com/api/v3/craft-queue-queue.html) driver didn’t support it.

I’ve just fixed that for Craft 3.4. So now you will be able to do this from `config/app.php`:

```php
use craft\queue\Queue;

return [
    'components' => [
        'customQueue' => [
            'class' => Queue::class,
            'channel' => 'custom',
        ],
    ],
];
```

Then from your own code, you will be able to push new jobs to your `customQueue` component like this:

```php
Craft::$app->customQueue->push(/* ... */);
```

Note that only Craft’s main `queue` component is affected by the [runQueueAutomatically](https://docs.craftcms.com/v3/config/config-settings.html#runqueueautomatically) config setting, you will need to bring your own queue worker. (Though your custom queue should automatically get its own CLI commands, e.g. `./craft customQueue/run`.)

Also, the new Queue Manager component in 3.4 will only look at the main `queue`.

**Comment by Mosnar** [comment]
@brandonkelly Looks like the queue changes are breaking the in-browser migration runner.

Getting this error on all CP pages:
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'channel' in 'where clause'
The SQL being executed was: UPDATE `craft_queue` SET `dateReserved`=NULL, `timeUpdated`=NULL, `progress`=0, `progressLabel`=NULL WHERE ((`channel`='queue') AND (`fail`=FALSE)) AND (`timeUpdated` < 1580155546 - `ttr`)
```

Seems to be happy again if I run the migrations manually:
` ./craft migrate --type=app`

**Comment by brandonkelly** [comment]
@Mosnar Whoops, forgot to bump the schema version. Run `composer clear-cache` and then `composer update` again, or just run `./craft migrate/up --type=app` to force the new migration to run.

**Comment by mikemeadeuk** [comment]
is there any way to make FeedMe use a custom queue without modifying the core code?

**Comment by brandonkelly** [comment]
@mikemeadeuk Just made that possible for the next Feed Me release. Going forward you can do this from `config/app.php`:

```php
return [
    'components' => [
        'plugins' => [
            'pluginConfigs' => [
                'feed-me' => [
                    'queue' => 'customQueue',
                ],
            ],
        ],
    ],
];
```

If you want to test that now, change your `craftcms/feed-me` constraint in `composer.json` to `dev-develop`, and then run `composer update`.

**Comment by mikemeadeuk** [comment]
Amazing! Will give it a go!

**Comment by mikemeadeuk** [comment]
seems to be stuck in the queue manager on pending, do i need to setup a separate cron or should this use runQueueAutomatically?

**Comment by jwrudzin** [comment]
@brandonkelly Any idea when this will be officially released? Looking forward to this feature, will be really useful for our workflow. Thanks!

**Comment by brandonkelly** [comment]
@jwrudzin You can start using it right now by setting `craftcms/feed-me` to `dev-develop`. I’m not sure exactly when the next release will go out.

**Comment by brandonkelly** [comment]
Nevermind… Feed Me 4.4.3 has been tagged!

**Comment by bruno-canada** [comment]
Great idea and solution guys. I have implemented that and works like a charm.

The only add-on to this would be to somehow show the custom queue channels in the Queue Manager as an quick and easy way to give visibility of their progress. (`CMS > Utility > Queue Manager)

I have posted as an idea here: https://github.com/craftcms/cms/discussions/13347
