### ISSUE TITLE
[3.4] Matrix blocks not propagated to new sites

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#5494]
### Description

When adding new sites to a 3.4.0-RC3 install and enabling the sites for an entry section, Matrix fields (“owned” by that section) aren’t getting propagated to the new sites.

Propagation method for the field is set to “Save blocks to all sites the owner element is saved in”.

### Steps to reproduce

1. Start with a single site install, with an entry section that has a Matrix field added and a couple of entries created in that section
2. Add new sites
3. Enable the section with the Matrix field for the new sites
4. Inspect the entried in that section and see how the Matrix blocks exist for the primary site only

### Additional info

- Craft version: 3.4.0-RC3
- PHP version: 7.3.7
- Database driver & version: Postgres 11.6.1
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "3.4.x-dev as 3.4.0-RC3,
  "...": "..."
}
```

Then run `composer update`.

Once you’ve updated, run this command to fix your entries:

```bash
./craft resave/entries --section=yourSectionName --update-search-index
```
