### ISSUE TITLE
JSON encoding of DateTimeInterfaces is broken with PHP 7.4

### ISSUE THREAD

**Issue by sjadema** [craftcms/cms#5500]
### Description

I encountered [an issue](https://github.com/nystudio107/craft-seomatic/issues/530#issuecomment-578516516) while using the SEOMatic plugin for Craft 3. This is basically a bug in PHP / Yii which wrongly JSON encodes instances of `DateTimeInterface`. The bug is fixed in Yii 2.0.32 but Craft 3 uses 2.0.31. Would it be possible to update Yii to 2.0.32 so i can run PHP 7.4? :)

### Steps to reproduce

1. Try to `\yii\helpers\BaseJson::encode()` an instance of `DateTimeInterface`
2. Notice that the encoded value is an empty array (`[]`) 

### Additional info

- Craft version: 3.3.20.1
- PHP version: 7.4.2
- Database driver & version: MySQL 5.7
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Craft 3.4 (coming tomorrow) uses Yii 2.0.32. It’s pretty stable at this point, so if you are affected by nystudio107/craft-seomatic#530, you’re probably best off just updating to that now.

To update to 3.4 before the GA is released tomorrow, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "3.4.x-dev as 3.4.0-RC3",
  "...": "..."
}
```

Then run `composer update`.
