### ISSUE TITLE
3.4 - cannot enter database credentials during browser install

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#5501]
### Steps to reproduce

1. Install composer packages using `composer create-project craftcms/craft` command
2. Change craft version to `3.4.0-beta.5` in `composer.json` and run `composer upgrade`.
3. Try to install craft using a browser - there is no installation step when you enter database credentials.

**Comment by brandonkelly** [comment]
The installation step will only show up if Craft isn’t able to connect to the database already.
