### ISSUE TITLE
[3.4] Matrix Changes Not Merging

### ISSUE THREAD

**Issue by matthewmrotter** [craftcms/cms#5503]
### Description
When using the new merging functionality of 3.4, if you edit content in different matrix blocks the changes will not merge.

https://drive.google.com/file/d/1kCCgyW_ocWpfOy3_-bvxYUNuaRn6vJ8K/view?usp=sharing

### Steps to reproduce

1. Change current entry and create a draft
2. Go back to current entry and make a change in a different matrix block, then hit save. 
3. Return to the draft and merge in changed from current entry. 
4. Nothing Happens

### Additional info

- Craft version: 3.4.0 - RC
- PHP version: 7.1.33
- Database driver & version: MySQL 5.5.62
- Plugins & versions: Supertable 2.3.3

**Comment by brandonkelly** [comment]
This is expected; currently field value changes can only be merged in for an entire field, not sub-field blocks/fields. And if you’ve modified a Matrix field at all anywhere within a draft, then it will be protected from being overwritten.

**Comment by matthewmrotter** [comment]
Will this be more obvious on release? I'm sure this is going to cause confusion with our client when they click "Merge" and nothing happens.

If it's unable to merge, should the button be there at all? Or can the block be labeled something outside of a yellow "M"? Maybe a white "P" inside of a red block for protected.

**Comment by brandonkelly** [comment]
Yeah we probably could work to improve the UX. I’ll reopen and mark this as an enhancement.

**Comment by jsunsawyer** [comment]
Would be nice if a matrix field could be flagged that it has been changed in some way, and only get overridden at merge if it has been adjusted. I don't think I could explain the current functionality to most clients.

**Comment by brandonkelly** [comment]
I had hoped to get this into 3.5 but I’ve been looking into it and it’s a bit trickier than I’d hoped. Will keep working on it, but for 3.6 instead of 3.5.

**Comment by sterrym** [comment]
We've been monitoring this issue for a while now. We came here from spicywebau/craft-neo#355.

Essentially, we have a multilingual customer website and when they use the Preview function (almost always) their entry sometimes gets mixed up with the other language when they Save the entry.

In essence, I wonder if you have any sense of timing on it? It's becoming increasingly painful for us!

**Comment by brandonkelly** [comment]
@sterrym That sounds unrelated to this issue, and more like an actual bug. Make sure you’re running the latest versions of everything, and if you are still able to reproduce the issue reliably, please post a new issue over at https://github.com/spicywebau/craft-neo/issues explaining it and how to reproduce it.

**Comment by sterrym** [comment]
You could be right, though I've been under the impression for the past few months that they were intrinsically linked. We'll look more into it on our end.

**Comment by green17** [comment]
This is a problem for us too, clients are getting confused. Any timings on the updated @brandonkelly?

**Comment by brandonkelly** [comment]
@green17 We’re working on 4.0 and expect we’ll have a beta ready in 6-9 months.

**Comment by green17** [comment]
Thanks @brandonkelly

**Comment by brandonkelly** [comment]
Excited to say that this is now resolved for Craft 3.7 – see #7710.

**Comment by green17** [comment]
@brandonkelly great news that’s fantastic, will make a lot of our clients happy that one.
