### ISSUE TITLE
Login Error with Queue

### ISSUE THREAD

**Issue by TonyDeStefano** [craftcms/cms#5504]
### Description

We currently have over 230,000 items in the queue table and each ajax call that the site makes to process the queue returns this error:

> [yii\web\HttpException:403] yii\web\ForbiddenHttpException: Login Required in /var/www/html/vendor/yiisoft/yii2/web/User.php:454

The ajax endpoint that is called is:

> /index.php?p=admin/actions/queue/get-job-info&dontExtendSession=1

This happened about the time we enabled Redis.

### Steps to reproduce

1. Save an entry
2. Refresh the page

### Additional info

- Craft version: 3.3.20.1
- PHP version: 7.3.14
- Database driver & version: MySql 5.7.12
- Plugins & versions:

**Comment by brandonkelly** [comment]
This issue is already covered by #4533, and it’s been fixed by Craft 3.4 (which is being released tomorrow).

**Comment by TonyDeStefano** [comment]
Thank you.
