### ISSUE TITLE
[3.4] Queue Manager jobs list 

### ISSUE THREAD

**Issue by ctmaloney** [craftcms/cms#5506]
### Description

When using the priority feature of the queue is it possible for jobs to be added above the currently running job in the jobs list. This causes the currently running job to be pushed off the index page of the queue manager.  So it appears as if the queue is stalled since all jobs are just "pending" when in reality there is still a job running.

### Steps to reproduce

1.  Enqueue a long running job with a lower priority than normal craft tasks.
2. As entries are saved the craft tasks, i.e. "updating search index", will be enqueued with higher priority and push the running job off the list.

Once the total jobs goes over 50 in the image below the running job will fall of the list:

![image](https://user-images.githubusercontent.com/552606/73221054-c7797a80-4114-11ea-8b66-a213d4047c5f.png)

### Additional info

- Craft version: 3.4.0-RC3

**Comment by brandonkelly** [comment]
True… although that only lasts until that one job is done, and you should still see the active job in the global sidebar, right?

**Comment by ctmaloney** [comment]
You _do not_ see the active job the sidebar.  So, I guess that is really the issue that makes it seem like nothing is happening.

**Comment by brandonkelly** [comment]
Ah right, ok.

**Comment by brandonkelly** [comment]
Alright, this is fixed for the next release! Now the active queue job(s) will always be sorted to the top of the results.

![The Queue Manager utility with an active queue job visible](https://user-images.githubusercontent.com/47792/73691757-d10c6080-4687-11ea-9619-27e333d559c1.png)

**Comment by ctmaloney** [comment]
👍

**Comment by brandonkelly** [comment]
3.4.3 is out now with this change.
