### ISSUE TITLE
Add support for a `deleteFailMessage` property on Craft.VueAdminTable

### ISSUE THREAD

**Issue by BenParizek** [craftcms/cms#5507]
### Description

Currently, if a delete action fails no message appears to the user. It would be nice to have a property like the `reorderFailMessage` so that we can display the user a message if an item in the VueAdminTable fails to delete.

### Steps to reproduce

1. Create a VueAdminTable
2. Return `return $this->asJson(['success' => false]);` from the delete action
3. Nothing visible happens in user experience

### Additional info

- Craft version: 3.4 RC.3

**Comment by nfourtythree** [comment]
Hi @BenParizek 

Thanks for this, have added the `deleteFailMessage` param as well as a default fallback.

This will be included in the next release.

Thanks!

**Comment by brandonkelly** [comment]
Craft 3.4.2 is out with that param.

**Comment by BenParizek** [comment]
Great!
