### ISSUE TITLE
"Save as a new entry" doesn't work when maxSlugIncrement is set to 1

### ISSUE THREAD

**Issue by jamiewade** [craftcms/cms#5510]
### Description
For our projects, we have `maxSlugIncrement` set to `1`, which prevents URLs from being incremented:

`test-page`, `test-page-1`, `test-page-2` etc.

This works absolutely fine, until we try and use Crafts "Save as a new entry" feature, which returns an error:

![Screenshot_2020-01-28 Test Page - Craft Playground](https://user-images.githubusercontent.com/6672331/73275334-e0e6f900-41de-11ea-92f6-6135723af16d.png)

If we disable this config option, the page does duplicate as expected, and we can see the new URL it has generated:

![Screenshot_2020-01-28 Test Page - Craft Playground(1)](https://user-images.githubusercontent.com/6672331/73275414-f3f9c900-41de-11ea-8c85-16dacb9fd29d.png)

It seems that this feature duplicates the entry and increments the new slug, however this would always fail if your config option was set to avoid duplicate URLs.

To get around this, what if entries were duplicated **with an empty slug value?** That way, if the author renamed the new entry and hit save, it would automatically generate a slug from that title. Otherwise, they could enter their own slug manually.

In both situations, saving the entry for the first time with an empty slug would run it through the normal URL validation, which would _then_ check if `maxSlugIncrement` is defined?

---

Tested on a fresh Craft install with `maxSlugIncrement` set to `1`.

Entries are created inside a Structure, and `Entry URI Format` is set to `{parent.uri ?? ''}/{slug}`

### Additional info

- Craft version: 3.3.20.1
- PHP version: 7.3.8
- Database driver & version: MySQL 5.7.24

**Comment by brandonkelly** [comment]
I don’t think allowing empty slugs is the answer here, but perhaps we could stop validating that elements have a unique URI, if they are disabled. Combined with setting entries’ statuses to disabled by default when duplicating them (which may be more desirable).

**Comment by jamiewade** [comment]
Thanks Brandon. That sounds like a sensible approach to me, and does make a lot of sense in hindsight. If a user was working through a content entry process that involved duplicating an entry and then modifying it, they might not want the entry going live straight after duplication, before they have a chance the change the content.

**Comment by brandonkelly** [comment]
This has been resolved for the next 3.4 release:

- First, Craft no longer requires URIs to be unique unless the element is actually enabled.
- Second, when duplicating an element, if Craft can’t assign a unique URI to the new element, it will just be created as disabled, to get around the unique URI requirement.

**Comment by brandonkelly** [comment]
Craft 3.4.6 is out now with this change.

**Comment by jamiewade** [comment]
That works great, thanks for sorting.

**Comment by samhibberd** [comment]
> Second, when duplicating an element, if Craft can’t assign a unique URI to the new element, it will just be created as disabled, to get around the unique URI requirement.

@brandonkelly does this also apply when saving (not duplicating) new elements, if trying to save a new enabled element in the cp, with a non unique slug, it looks like it currently disables it, rather throwing the non unique uri error i expected??

**Comment by brandonkelly** [comment]
@samhibberd This is an old issue and the behavior has changed since then (e.g. #12303). Can you please post a new issue with specific steps to reproduce and expected/actual behaviors?
