### ISSUE TITLE
Setting Week Start Day to Sunday doesn't work.

### ISSUE THREAD

**Issue by olivierbon** [craftcms/cms#5513]
### Description

Under your user preferences, if you set your **Week Start Day** to Sunday , the value is not being respected in date pickers on Entry forms. 

This is only an issue with Sundays (value being saved is `0` and should be `7`). All other days are ok.

### Steps to reproduce

1. Go to your user account
2. Under the **Preferences** tab, set **Week Start Day** to Sunday
3. Go to an entry and open a date picker (post date for example)
4. Wrong start day is being used

### Additional info

- Craft version: 3.3 & 3.4

**Comment by brandonkelly** [comment]
Fixed, thanks Oli!
