### ISSUE TITLE
GraphQL support for dropdown labels

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/cms#5514]
### Description
Currently it is only possible to get the dropdown value from a GraphQL endpoint. In my specific use case I need both the value as the handle.

### Additional info

- Craft version: 3.4.0

**Comment by andris-sevcenko** [comment]
Thank you for reporting that! This has been fixed for the next release.

**Comment by Wiejeben** [comment]
Thanks @andris-sevcenko, looks great!

**Comment by brandonkelly** [comment]
Craft 3.4.6 is out now  with this change.

**Comment by Thomas-b-wm** [comment]
Hi there, i found the same issue, but i have the latest craftcms version installed.
I use.a dropdown field in my entries and when i query the entries by section, i get all of them and also get the dropdownfield. But i only get the option-value, not the label.
Is this not possible or is any additional code needed in the graphql request ?

```
{
    entries(section: "testproducts", siteId: "1") {
        ... on testproducts_Entry{
            title
            intro
            slug
            products_disclaimer{
               title
            }
            products_productGroup
        }        
    }        
} 
```
"products_productGroup" is the dropdownfield, but it only contains a string with the option-value, no chance to get the label.

**Comment by andris-sevcenko** [comment]
@Thomas-b-wm to get the label you should do
```graphql
{
    entries(section: "testproducts", siteId: "1") {
        ... on testproducts_Entry{
            title
            intro
            slug
            products_disclaimer{
               title
            }
            products_productGroup (label: true)
        }        
    }        
} 
```
