### ISSUE TITLE
[3.4] No assets show up in any field (locally and in production)

### ISSUE THREAD

**Issue by jdsimcoe** [craftcms/cms#5516]
### Description

Since upgrading to `3.4.0` from `RC3` assets are no longer viewable/selectable in any S3 asset field:

![image](https://user-images.githubusercontent.com/275617/73298962-272e5f00-41c3-11ea-8cc8-2f87fdcff055.png)

Assets are still there and viewable when navigating to Assets:

![image](https://user-images.githubusercontent.com/275617/73299029-44632d80-41c3-11ea-9007-be7139533acf.png)

### Steps to reproduce

1. Navigate to any Entry with an S3 asset field.
2. Click the button to add/select assets.
3. No assets show up.

### Additional info

- Craft version: `3.4.0`
- PHP version: `7.4.0`
- Database driver & version: MySQL `5.7`
- Plugins & versions:
```json
    "craftcms/cms": "^3.4.0",
    "vlucas/phpdotenv": "^2.4.0",
    "craftcms/aws-s3": "^1.2.7",
    "mikestecker/craft-videoembedder": "^1.1.4",
    "craftcms/redactor": "^2.5.0",
    "ether/simplemap": "^3.7.7",
    "craftcms/element-api": "^2.6.0",
    "spicyweb/craft-embedded-assets": "^2.1.1.1",
    "verbb/super-table": "^2.3.3",
    "superbig/craft3-templateselect": "^2.0.2",
    "craftcms/feed-me": "^4.2.0.1",
    "nystudio107/craft-typogrify": "^1.1.18",
    "nystudio107/craft-seomatic": "^3.2.39",
    "craftcms/contact-form": "^2.2.6",
    "nesbot/carbon": "^2.7.0",
    "nystudio107/craft-retour": "^3.1.33",
    "wrav/oembed": "^1.2.0",
    "lukeyouell/craft-sentry": "^1.5.1",
    "nystudio107/craft-webperf": "^1.0.17",
    "clubstudioltd/craft-asset-rev": "^6.0.2",
    "venveo/craft-bulkedit": "^2.0.0",
    "zendframework/zend-feed": "^2.12.0"
```

**Comment by brandonkelly** [comment]
What is your Assets field’s Default Upload Location set to?

**Comment by jdsimcoe** [comment]
@brandonkelly is this what you mean?

![image](https://user-images.githubusercontent.com/275617/73299425-04e91100-41c4-11ea-85fc-2b953833d2f1.png)

**Comment by andris-sevcenko** [comment]
Thanks for the info! Just pushed the fix for this.

**Comment by brandonkelly** [comment]
Craft 3.4.0.1 is out with the fix!

**Comment by jdsimcoe** [comment]
Thanks so much @andris-sevcenko and @brandonkelly!!! Migrated to production and everything is back in order.
