### ISSUE TITLE
[3.4] Images in Control Panel entries are cropped to a circle, obfuscating aspect ratio and full image content

### ISSUE THREAD

**Issue by andreimoment** [craftcms/cms#5518]
### Description
Prior to 3.4, images in CP entries were presented as a miniature version of the full image. This allows seeing the aspect ration and visually recognizing the image content, being able to know what the image is at a glance.

In 3.4, this was changed. Now all image assets appear cropped as a circle, which makes it impossible to see the aspect ratio and the content of the full image. This obfuscates useful information and makes it necessary to now double click the asset to open the image edit window in order to obtain this information which was previously available effortlessly, at a glimpse.

Please revert to the pre 3.4 behavior so that the asset content and aspect ratio are visible.

#### Example: 3.3 asset in a control panel entry: represents the full image

<img width="258" alt="craft-3 3--image-is-visible" src="https://user-images.githubusercontent.com/6190/73302726-f30a6c80-41c9-11ea-977c-b77ef8a03b3e.png">

#### Example: 3.4 asset in a control panel entry: cropped to a circle. 

<img width="258" alt="craft-3 4--image-is-cropped" src="https://user-images.githubusercontent.com/6190/73302741-f9004d80-41c9-11ea-9ac2-69253779d2f4.png">

It is now necessary to double-click the asset in order to see the image aspect ration and content.

<img width="405" alt="craft-3 4--user-needs-to-open-for-editing-in-order-to-inspect-the-image" src="https://user-images.githubusercontent.com/6190/73302742-f998e400-41c9-11ea-9dc9-9092ce134839.png">

### Steps to reproduce

1. Upgrade to CraftCMS 3.4
2. Re-save assets (./craft resave/entries --update-search-index)

### Additional info

- Craft version: 3.4
- PHP version: 7.3.9
- Database driver & version:
- Plugins & versions: none related to images

**Comment by adrienne** [comment]
+1 because i also completely hate this change and it removes useful at-a-glance info. Maybe it could be a configurable setting, at least?

**Comment by andreimoment** [comment]
Yes, please consider reverting this or making it an option. Images are also cropped in the asset selection screen which makes them near impossible to identify. 

<img width="1128" alt="asset-selection-screen--image-crop" src="https://user-images.githubusercontent.com/6190/73307379-f9511680-41d2-11ea-90fa-73360e36d907.png">

**Comment by aelvan** [comment]
> It is now necessary to double-click the asset in order to see the image aspect ration and content.

@andreimoment Interesting, I don't even see the correct aspect ratio there, as described in #5515

**Comment by andreimoment** [comment]
@aelvan I do see the regular image edit popup when clicking on the asset. In my case it is a single asset per entry. 

<img width="398" alt="image-asset-now-cropped-in-circle--with-edit-popup" src="https://user-images.githubusercontent.com/6190/73310498-4c2dcc80-41d9-11ea-8d05-342658c7ae86.png">

**Comment by darylknight** [comment]
+1. It looks fancy, but it's less useful. Please add a config setting for this or remove it.

**Comment by dubcanada** [comment]
I personally prefer the more zoomed in thumbnail of the image in a circle.

The image is small enough to really not make out any difference between them anyways, so this is only an issue if you have a variety of images with different sizes that you are trying to find a specific one. All other instances the zoomed in circle will provide more detail (assuming the image detail is not on the edges).

My preference is config setting.

**Comment by andreimoment** [comment]
I won't be able to upgrade until this is resolved, because it removes the ability of my clients to select images visually. Our image library has many abstract images in multiple crops and this makes it practically impossible to visually determine which one is which, both in the selector, and in the entry.

**Comment by MattWilcox** [comment]
It'd be nice if there was a way to default asset buckets to thumbnail view for clients too. Doesn't suit all buckets and clients, but it does for others. Either way though - never re-crop or otherwise obfuscate source images in an asset picker UI.

**Comment by matthillco** [comment]
In addition, the grid asset view now crops images to squares which is also less useful. Sometimes I want to know the ratio of the source image when selecting it, now I have no idea which images have which ratio. These collective changes have made asset image viewing and selection much worse and I'd appreciate a way of reverting.

**Comment by andreimoment** [comment]
@brandonkelly any idea on rough timing for 3.5? This issue is what will block my clients upgrades' and it would be helpful to know. 

Or, do you think a workaround would be possible via admin section CSS customization?

Is the crop done server-side?

**Comment by brandonkelly** [comment]
We’re working on it now. You should be able to get on a 3.5 branch with something in place to resolve this issue in the next couple weeks.

**Comment by aelvan** [comment]
I created a small plugin which fixes this while we wait for 3.5: 
https://github.com/aelvan/more-fit-images

**Comment by matthillco** [comment]
Thank you very much @aelvan, this works perfectly for me. Great job.

**Comment by ryanmasuga** [comment]
We were discussing the rounded (not just rounded... but full on _circular_) thumbs today and I'm glad we found this thread so we didn't have to start one. +100 for at least making this configurable, otherwise it's just hiding/manipulating /having fun with the content, which is more the job of a social media platform (like infinite scrolling!), not a CMS. 

Perhaps @dubcanada has never worked on a site with 1000's of images with "less-than-perfect naming and a busy office manager trying to navigate to the correct one" as @andreimoment and we both have. _But we can all agree:_ make this configurable at least. 

( I think there is way too much rounding of things in 3.4 overall, but I'll settle for solving this one).

**Comment by ryanmasuga** [comment]
If @aelvan can solve this with a plugin in a day, why do we have to wait for 3.5 release? (I'm sure there's something I don't know, but with the breakneck pace Craft updates are kicked out, and the seemingly small amount of CSS needed to fix, this feels like it could go out in a minor release)

**Comment by matthillco** [comment]
Unfortunately it's not just a CSS problem. Under the hood, Craft now crops all dashboard asset thumbnails to squares. It was a design decision, and the plugin fixes it by replicating the previous behaviour to leave images in their natural ratio.

**Comment by brandonkelly** [comment]
I’ve adjusted the large image thumbnails and preview thumbs for Craft 3.5, to use the real image aspect ratio (see https://github.com/craftcms/cms/issues/5515#issuecomment-595917234). Going to leave the table view / small thumbnails as-is though, as I think with such a small image, being able to make out some detail of the image is more important than knowing the aspect ratio.

**Comment by proimage** [comment]
"Going to leave the table view / small thumbnails as-is though" — could you make this a per-volume setting? I just spent 5 minutes trying to find an image for a header that wasn't natively circular, only to realize that they were all being rendered as such. :-/

It's all fine and dandy to force-crop avatar-esque images to be circular and mess with their aspect ratios when they're being presented decoratively (i.e. in a website frontend), but it's really not ok to do in a backend interface used to _manage_ said images. Form _follows_ function, and this is putting that the other way around.

Suggestion: display those small thumbs as they were in 3.3, with their native aspect ratio and no CSS-based cropping, as the default view. Then if you want, show a zoomed-in crop of the image on mouse-over.

**Comment by dubcanada** [comment]
Having two crops for every image is not an option. If you don't like the current setup there is a plugin posted above which fixes it.

There does seem to be a lot of angry people complaining about this change. They need to understand that there is no single solution, it may be that the 4-5 people angry in this thread are the only people complaining about it and the other 1000's like it better. I'm not saying it is, it's just something to keep in mind.

I think in the long term a setting would probably be best.

**Comment by ryanmasuga** [comment]
> Going to leave the table view / small thumbnails as-is though, as I think with such a small image, being able to make out some detail of the image is more important than knowing the aspect ratio.

I would think that a square (or even _slightly_ rounded square) would make more sense than a circle if showing more detail is the important thing. Why hide any of it?

**Comment by proimage** [comment]
> Having two crops for every image is not an option.

You don't need two separate crops; you just need the slightly larger one that's big enough for the zoomed-in view. Then you use CSS to manipulate it to display how you want it (smaller) in the non-mouseover view.

**Comment by brandonkelly** [comment]
@ryanmasuga Fair point. I just implemented that and personally don’t care for it, but went ahead and made it a user preference for Craft 3.5.

<img width="176" alt="An Assets field with an image selected, with a non-rounded icon" src="https://user-images.githubusercontent.com/47792/76872504-be11b200-6829-11ea-9a02-2ce9dac5591d.png">

**Comment by andreimoment** [comment]
@brandonkelly thank you for the work on this. 

I am still not sure if the final change resolves the issue and reverts the forced crop on assets in the CP? 

The issue as submitted targets the sudden loss of the ability to see the full image and thus determine its aspect ration and full content.

Do all images in the CP have their full content and aspect ration fully visible?

None of my clients have ever expressed the need to see cropped/scaled assets in the CP. All of my clients were confused and hindered by the inability to select the correct image which came from this change.

Thank you.

**Comment by proimage** [comment]
Sorry @brandonkelly, but I really gotta second @andreimoment in this. It's the backend; we're looking to manage assets efficiently. This means making the differences between one asset and the next as obvious as it can reasonably be. When they all have a uniform appearance, that eradicates those crucial differences and makes things needlessly confusing.

Please don't get me wrong—I _love_ the effort and care you all put in to making Craft a beautiful system to look at as well as use. It's a joy to show the backend to clients and hear their remarks about how clean and straightforward everything is. It's just that in this case, that beautification interferes with the functionality.

To be fair, I've certainly had clients and websites whose asset structure is a sufficiently organized that this change would not be problematic. They are the kind of sites where all the assets in a particular volume always have a specific aspect ratio, and there's no chance of accidentally selecting a portrait asset when you really really needed a landscape one instead.

However, I've also had (still have TBH) clients that have _all_ their images in one single volume (not to mention _horrific_ naming conventions for those images), which is where this kind of change makes things very difficult.

Please, make this a per-volume (or perhaps even per-Asset field) setting at the very least.

**Comment by brandonkelly** [comment]
I think you guys maybe missed https://github.com/craftcms/cms/issues/5515#issuecomment-595917234. If you are trying to identify an image primarily by its thumbnail, then you should be using the thumbnail view, and as of 3.5 that will show the correct aspect ratio.

**Comment by proimage** [comment]
Whoops, yes, I had missed that indeed. 👍 

The last bit that's got me tilting my head is those rounded corners. I'd guess quite a few of us would have clients that "hardcode" various "frames" into their images, rounded corners among them. The CSS-based rounded corners would then make it difficult to discern between the hard-coded ones and the sharp-cornered ones (I'm getting [BSG 2003 flashbacks](https://scifi.stackexchange.com/questions/12335/why-does-the-paper-in-battlestar-galactica-have-the-corners-cut-off) here...). I'm wondering if a reasonable solution would be to transition the thumbnails to `border-radius: 0` on mouseover...?

**Comment by brandonkelly** [comment]
@proimage sounds like an easy thing to add with the CP CSS plugin if you feel strongly about it :)

**Comment by leevigraham** [comment]
@brandonkelly Is there anyway to make this is a system wide config?

**Comment by brandonkelly** [comment]
I changed my mind on how we should be handling small thumbnails. Showing them at the correct aspect ratio isn’t really the end of the world. So I was able to implement the change for 3.4 with significantly less work than what I had done on the 3.5 branch. Will be in the next 3.4 release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#8f6e9e8945d4df9627f0237dd47b0e66e4d52541 as 3.4.20",
  "...": "..."
}
```

Or if you’re already running Craft 3.5 Beta, then change your `craftcms/cms` requirement to `"3.5.x-dev"`.

Then run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.4.21 is out now with this change.

**Comment by darylknight** [comment]
This is a hundred times better, thank you!

**3.4.20**
![image](https://user-images.githubusercontent.com/1250017/83239692-fd04a200-a1a0-11ea-93ed-39bc9ac7bd7a.png)

**3.4.21**
![image](https://user-images.githubusercontent.com/1250017/83239716-02fa8300-a1a1-11ea-8b6f-0018d31ff0fd.png)

**Comment by andreimoment** [comment]
@brandonkelly thank you for staying with this issue, for working with us, and for being as open-minded as you are.
