### ISSUE TITLE
[3.4] The sidebar site name sits close to the edge

### ISSUE THREAD

**Issue by jamiewade** [craftcms/cms#5524]
### Description
![Screenshot_2020-01-29 Settings - Craft CMS Playground Lorem(1)](https://user-images.githubusercontent.com/6672331/73343818-21935080-4279-11ea-9a3e-1e03e1e3df35.png)

### Additional info

- Craft version: 3.4.0.2
- Browser: Firefox 72.0.2 (64-bit)

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just added some padding to the right, and also managed to add a multi-line overflow ellipsis with that farcy new [-webkit-line-clamp](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp) property 😍

![The system name displayed in the global sidebar, with added right-hand padding and an ellipsis on the second line](https://user-images.githubusercontent.com/47792/73385470-12fd6700-4282-11ea-869c-0ec539520da8.png)

**Comment by jamiewade** [comment]
No worries! Looks great 😍
