### ISSUE TITLE
latest stable version

### ISSUE THREAD

**Issue by atdotslashdot** [craftcms/cms#5526]
Is the latest stable version  3.0.41 ?
i.e. the one that is available here [https://docs.craftcms.com/v3/installation.html#step-1-download-craft] https://docs.craftcms.com/v3/installation.html#step-1-download-craft

I was grabbing the latest from this page but something changed this morning to break my migration.
(it was changes in .env and the conf table that broke my setup)
I've gone back to 3.0.41
I've got my migration working again but the admin update page is saying
```
You’ve reached a breakpoint!
 More updates will become available after you install Craft CMS 3.0.41.1.
```
I need to be able to grab the newest stable version so terraform scripts will work for a while.
Also, is the a mailing list I can join which will alert me when the latest stable version changes?

Many thanks

**Comment by remcoov** [comment]
Hi @atdotslashdot,

The current latest version is 3.4.0.2. I suggest looking at [https://github.com/craftcms/cms/blob/develop/CHANGELOG-v3.md](https://github.com/craftcms/cms/blob/develop/CHANGELOG-v3.md) for the latest release info.

**Comment by atdotslashdot** [comment]
I appreciate that's the latest version that came out today but is that considered stable? - it broke the world since yesterday's 'latest'  version I was grabbing.  

Is there a reason the docs page points to 3.0.41?
https://docs.craftcms.com/v3/installation.html#step-1-download-craft

I was hoping there'd be a stable along with the latest? or do you consider these to be the same thing?

**Comment by atdotslashdot** [comment]
https://download.craftcdn.com/craft/3.0/Craft-3.4.0.2.tar.gz

doesn't appear to be a thing, I'm looking to grab a stable version via wget in a bash script

**Comment by remcoov** [comment]
How about [https://craftcms.com/latest-v3.tar.gz](https://craftcms.com/latest-v3.tar.gz). This downloads Craft-3.4.0.2.tar.gz for me.

**Comment by atdotslashdot** [comment]
That's what I was grabbing but  the change from yesterday to today broke my migration script (the contents of .env appear to have changed in a way that isn't reflected in the site documentation ), hence my question about a stable version.

**Comment by atdotslashdot** [comment]
from the activity on github I'm assuming
3.3.20.1 was living in 'latest' yesterday
is the release version of that tar.gz still available somewhere until 3.4.* settles down?

**Comment by remcoov** [comment]
Yes, some .env changes have definitely been made in 3.4.
Older versions can be found at [https://github.com/craftcms/cms/releases](https://github.com/craftcms/cms/releases), with 3.3.20.1 specifically at [https://github.com/craftcms/cms/archive/3.3.20.1.tar.gz](https://github.com/craftcms/cms/archive/3.3.20.1.tar.gz)

**Comment by atdotslashdot** [comment]
Thanks but that's the source code rather than the structure that appears in https://craftcms.com/latest-v3.tar.gz.

**Comment by atdotslashdot** [comment]
I'm guessing
https://docs.craftcms.com/v3/config/db-settings.html
needs updating with a 3.4 version of the docs at some point
I'm hoping , eventually, to be able to grab something in the terraform world when I spin up  a new server and restore a backup but this will be dependant on me being able to find a stable, non breaking version of craftcms. the 3.3.20.1 that was in 'latest' yesterday is not what is in the git archive
is https://download.craftcdn.com now  not in use?

**Comment by brandonkelly** [comment]
I’ve just updated the [Database Connection Settings](https://docs.craftcms.com/v3/config/db-settings.html) doc to reflect the new default environment variables/settings you’ll get with new Craft projects. Though both the old and new connection settings  will work with both 3.4 and older versions of Craft 3. We’re just pushing `DB_DSN` over `DB_DRIVER`, `DB_SERVER`, `DB_DATABASE`, and `DB_PORT` as of Craft 3.4.

So to create a new project using Craft 3.3:

- Run `composer create-project craftcms/craft` like you normally would.
- Before running the `setup` command or installing Craft, open up `composer.json` and change your `craftcms/cms` requirement to `~3.3.20.1`, and then run `composer update`.
- Then you will need to manually set your `DB_DSN` environment variable in `.env`, **or** if you prefer to set your database connection settings via the `./craft setup` command, replace your `config/db.php` file with the [pre-3.4 version](https://raw.githubusercontent.com/craftcms/craft/8a681017f381590ec77c94ea5132e2f5ab1d5fb0/config/db.php).
