### ISSUE TITLE
select assets button in entries

### ISSUE THREAD

**Issue by jangidgirish** [craftcms/cms#5528]
### Description
select assets button is not working after update new version.

### Steps to reproduce

1. the assets field wth selected volumes
2. when click on "add an assets" in entries then the js error is emerged on select asset in popup 
![image](https://user-images.githubusercontent.com/4018017/73358712-3f86a280-42c5-11ea-83da-c63a53dc7acb.png)

### Additional info

- Craft version: 3.4.0.2
- PHP version: 7.2
- Database driver & version: 5.7.29

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you please send your `composer.json` and `composer.lock` files, plus a database backup, over to support@craftcms.com ?

**Comment by brandonkelly** [comment]
(And please reference this issue in the email body.)

**Comment by jangidgirish** [comment]
i cleaned cpsources after that it seems working

**Comment by brandonkelly** [comment]
Alright, glad you got it working!
