### ISSUE TITLE
Add a way to specify encoding for MySQL DB backup (mysqldump)

### ISSUE THREAD

**Issue by ockam** [craftcms/cms#5529]
### Description

To use emojis in a field values, you need to set the charset in DB config to `utf8mb4`. This works fine except when you export the DB where `mysqldump` defaults to `utf8`.

If you add `--default-character-set = utf8mb4` to `mysqldump` command, it works fine.

I know I can use the `backupCommand` config to override, but I found it risky considering the number of options used by the default command (which could change over time). The example from [this guide](https://craftcms.com/guides/database-backups-in-craft-3-with-mamp) suggest there’s a lot.

### Steps to reproduce

1. set db config charset to `utf8mb4`
2. add emoji in a field definition
3. go to Utilities and backup DB

### Additional info

- Craft version: 3.3.20.1
- PHP version: 7.3
- Database driver & version: MySQL
- Plugins & versions:

**Comment by ockam** [comment]
If someone ever stumble on this ticket and want to try the MAMP/config solution, be aware that it defines **TWO** `mysqldump` commands and that you need to specify the charater set on both.
```
BACKUP_COMMAND="
/Applications/MAMP/Library/bin/mysqldump -h localhost -u root -proot --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --default-character-set=utf8mb4 --set-charset --triggers --single-transaction --no-data --result-file=\"{file}\" {database}
&& 
/Applications/MAMP/Library/bin/mysqldump -h localhost -u root -proot --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --default-character-set=utf8mb4 --set-charset --triggers --no-create-info --ignore-table={database}.assetindexdata --ignore-table={database}.assettransformindex --ignore-table={database}.cache --ignore-table={database}.sessions --ignore-table={database}.templatecaches --ignore-table={database}.templatecachecriteria --ignore-table={database}.templatecacheelements {database} 
>> \"{file}\""
```

**Comment by angrybrad** [comment]
Just fixed this for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#a9a58b0d78d4aa234d2ddff6e532ff1866204b12",
  "...": "..."
}
```

Then run `composer update`.

**Comment by brandonkelly** [comment]
3.4.1 is out now with this fix.

**Comment by ockam** [comment]
You guys rocks!
