### ISSUE TITLE
Custom plugins can conflict with store plugins

### ISSUE THREAD

**Issue by dubcanada** [craftcms/cms#5536]
### Description
If you have a custom plugin with the handle notifications it would conflict with https://plugins.craftcms.com/notifications and if you went to the CraftCMS admin panel and Utilities -> Updates you would see your plugin with possible updates for https://plugins.craftcms.com/notifications.

It would be nice if there was a way to set custom plugins as not updatable/don't show in the Updates page.

### Steps to reproduce

1. Create a custom plugin with handle notifications (or anything that is the same as a store plugin handle)
2. Install it
3. Go to CraftCMS Admin -> Utilities -> Updates
4. See possible updates for your plugin related to a completely different plugin.

### Additional info

- Craft version: 3.3
- PHP version: 7.2
- Database driver & version: MySQL 5.6
- Plugins & versions: None

**Comment by brandonkelly** [comment]
This is covered by #3054. See my comment there for an explanation.
