### ISSUE TITLE
[3.4] Quotes in field names get encoded on overview

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#5540]
### Description
The field name is set to `Show "Collection" tab first`, which is displayed correctly when editing the field or editing an entry that has the field, but on the fields overview, the quotes get encoded:

![Screenshot 2020-01-30 at 10 12 44](https://user-images.githubusercontent.com/755428/73435687-6d152f80-4349-11ea-9dad-99b950dcfa9f.png)

### Additional info

- Craft version: 3.4.02
- PHP version: 7.3

**Comment by brandonkelly** [comment]
This is the same underlying bug covered in #5532, and it’s been fixed for the next release :)

**Comment by brandonkelly** [comment]
Craft 3.4.2 is out now with the fix.
