### ISSUE TITLE
craft.app.request.segments|first depreciation warning

### ISSUE THREAD

**Issue by mark-chief** [craftcms/cms#5542]
### Description
Using `{{ craft.app.request.segments|first }}` to retrieve the first url segment in a template is triggering a depreciation warning in the CP.

> The first() function used to query for elements is now deprecated. Use one() instead.

- Craft version: 3.4.1
- PHP version: 7.4

**Comment by brandonkelly** [comment]
That deprecation error occurs when an element query’s [first()](https://docs.craftcms.com/api/v3/craft-elements-db-elementquery.html#method-first) method is called, e.g.:

```twig
{% set entry = craft.entries()
    .section('news')
    .first() %}
```

The deprecation warning should provide a stack trace that will help you find the offending template/PHP code.

(There’s nothing wrong with typing `craft.app.segments|first`.)
