### ISSUE TITLE
[3.4] GraphQL | include directive not functioning? 

### ISSUE THREAD

**Issue by stereomyth** [craftcms/cms#5543]
### Description
3.4 seems to have disrupted the `@include(if:Boolean)` directive. The directive works with a `false` value and doesn't return the entry but errors with a `true` value. This code worked before the update.

### Steps to reproduce

1. Conditional directive in basic query:
```gql
query page($ifTrue: Boolean!) {
  entries @include(if: $ifTrue) {
    id
  }
}
```
2. Returns errors of :
```js
{
  "debugMessage": "Undefined property: GraphQL\\Language\\AST\\VariableNode::$value",
  "message": "Internal server error",
  "category": "internal",
  "locations": [{"line": 2, "column": 3}],
  "path": ["entries"]
}

```

### Additional info

- Craft version: 3.4.1
- PHP version: 7.3.8

**Comment by andris-sevcenko** [comment]
Thanks for spotting this! Pushed a fix for the next release!

**Comment by brandonkelly** [comment]
Craft 3.4.2 is out now with this fix.
