### ISSUE TITLE
Craft 3.4 - Matrix fields clearing content after failed validation

### ISSUE THREAD

**Issue by engram-design** [craftcms/cms#5544]
### Description
Refer to the video - https://d.pr/free/v/vLDfzj - which shows saving a Matrix field with a required field, and failing validation. As expected. Saving again with, or without a value wipes the block's content away.

**Comment by brandonkelly** [comment]
Thanks, fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 3.4.2 is out now with the fix.
