### ISSUE TITLE
[3.4] Update: Table fields only works in first tab

### ISSUE THREAD

**Issue by mini71** [craftcms/cms#5549]
### Description

After updating to 3.4. all Table fields placed in an other tab than the first one lost their functionality.
Buttons "Add a row" and "x" do not work.

Table fields in the first tab still work fine.

### Additional info

- Craft version: 3.4.1
- PHP version: 7.3.13

**Comment by brandonkelly** [comment]
Thanks for reporting that! It’s been fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.2 is out now with the fix.
