### ISSUE TITLE
CP select dropdowns in Craft 3.4 are not scrollable in Firefox

### ISSUE THREAD

**Issue by petehjfd** [craftcms/cms#5550]
### Description

In the Craft 3.4 CP, the select dropdowns are not scrollable in Firefox (72.0.2).

For example, on the create field page, the Field Type dropdown cannot be scrolled so not all field types can be selected.

### Steps to reproduce

1. Open Firefox (72.0.2)
1. Go to the new field page in the CP
2. Attempt to select a field type near the bottom of the list, e.g. URL.

![create-field](https://user-images.githubusercontent.com/29060670/73470492-e3cd1f80-437f-11ea-885d-ce7993dda330.png)

### Additional info

- Craft version: 3.4.1
- PHP version: 7.4.1
- Database driver & version: MySQL 5.7.28
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Weird, I’m not able to reproduce that, also using 72.0.2.

![The Field Type menu, expanded with a scrollbar shown](https://user-images.githubusercontent.com/47792/73496175-d8242d80-436c-11ea-9905-36fe7b85bea7.png)

Can you try clearing your browser caches and delete all the files in `web/cpresources/` and see if that helps?

**Comment by petehjfd** [comment]
I just tested in incognito mode and the issue didn't occur. So I'm guessing it's being caused by an extension.

Apologies for the false alarm!

**Comment by brandonkelly** [comment]
No worries! If you end up figuring it out, please post about it in case anyone else runs into the same issue.
