### ISSUE TITLE
Applying CSS filter to body element breaks Craft's scrolling behaviour

### ISSUE THREAD

**Issue by matthillco** [craftcms/cms#5551]
### Description

Adding a CSS `filter` property to the control panel `body` element breaks' Craft's scrolling. I use the Control Panel CSS plugin to improve the new 3.4 UI to my tastes, and part of that is to desaturate the entire UI using a simple CSS filter declaration.

### Steps to reproduce

1. Override the control panel CSS for the body element (using browser dev tools, or the Control Panel CSS plugin) by adding `body { filter: saturate(75%); }`
2. Navigate to any long page where the content is longer than the viewport.
3. Scroll the page. Notice that the sidebar(s) now scroll out of sight. They should be fixed in place.

### Additional info

- Craft version: 3.4.1
- PHP version: 7.2.14
- Database driver & version: MySQL 5.7.24
- Plugins & versions:

```
Asset Usage         2.0.1
Blitz               3.1.1
Child Me!           1.0.6
Cloner              1.1.0
Control Panel CSS   2.2.0
CP Clear Cache      1.0.5
Element Map         1.2.1
Expanded Singles    1.0.7
Feed Me             4.2.0.1
Field Manager       2.1.1
Footnote            2.0.0-beta.5
Imager              2.3.1
Matrix Colors       2.0.1
Matrix Toolbar      1.0.6
Preparse Field      1.1.0
Redactor            2.5.0
SEOmatic            3.2.41
Sequential Edit     1.0.8.2
Similar             1.0.6
SuperSort           3.0.1
Super Table         2.4.1
Typogrify           1.1.18
```

**Comment by brandonkelly** [comment]
This doesn’t seem like our problem :)

Probably a browser bug. We’re not doing anything too far off the beaten path in the 3.4 CP styles.

**Comment by wsydney76** [comment]
I am glad that I am not the only one who has fallen into this trap. (in a non Craft project)

From the spec: 

`A value other than none for the filter property results in the creation of a containing block for absolute and fixed positioned descendants unless the element it applies to is a document root element in the current browsing context. `

So you could try applying the filter to the root like `html { filter: saturate(75%); }` instead and it should work. Or to the fixed element itself + any containers not having 'fixed' descendants.

/Mel

**Comment by matthillco** [comment]
Thanks @wsydney76 ! It's not a problem I've seen before in any other context, so when I tried this in Craft I jumped to a false assumption that Craft was doing something weird with scrolling. Thanks for clearing this up.
