### ISSUE TITLE
Login pages with a logo uploaded have a min-margin on login form

### ISSUE THREAD

**Issue by remcoov** [craftcms/cms#5552]
### Description
Login pages (f.e. `admin/login`) with a logo uploaded, have min-marges scripted on the `form#login-form`, resulting the login form going out of the window. This is happening since the Craft 3.4 update. All my Craft CMS sites with a logo uploaded have this same issue. Deleting the logo fixes the problem.

### Steps to reproduce

1. Upload a logo for the login panel
2. See the login window have a min-margin

### Additional info

- Craft version: 3.4.1

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.2 is out now with the fix.
