### ISSUE TITLE
Feature: display asset path/url in asset view

### ISSUE THREAD

**Issue by JayBox325** [craftcms/cms#5555]
### Description
A client of mine needs access to the image urls and using the “share” button doesn’t work too well for some of their team (not sure why).

Where you are displaying the image file name, it could be really handy to just show the image path, too.

### Steps to reproduce

1.
2.

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
As of the next release (coming later today), image/PDF/text assets will get a “View” button next to the “Download” button.

![View and Download buttons for an asset](https://user-images.githubusercontent.com/47792/73565633-ceef9b00-4416-11ea-8036-902d285ecf2d.png)

> using the “share” button doesn’t work too well for some of their team (not sure why).

Probably related to #5517 (also fixed for the next release)

**Comment by brandonkelly** [comment]
Craft 3.4.2 is out now with the View button.
