### ISSUE TITLE
Log-in layout issue on Craft 3.4 (possibly also on lower versions)

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#5556]
Craft 3.4, layout issue when Remember Me is disabled trough `rememberedUserSessionDuration`

<img width="353" alt="Schermafbeelding 2020-01-31 om 10 51 47" src="https://user-images.githubusercontent.com/23024452/73529895-c51a6780-4417-11ea-9ff2-850fdc796996.png">

**Comment by brandonkelly** [comment]
Craft 3.4.2 is out now with a fix for this.
