### ISSUE TITLE
Export button doesn't work on custom URL

### ISSUE THREAD

**Issue by martinhellwagner** [craftcms/cms#5558]
### Description

Similar to https://github.com/craftcms/cms/issues/4737, the export of entries is not working when using Craft CMS with a custom URL (e.g. https://cms.customurl.com/admin). When trying to export directly from the server URL (e.g. http://serverurl.com/admin), everything works as expected. I might be good to note that the custom URL has an SSL certificate, while the server URL does not.

### Steps to reproduce

1. Export arbitrary entries by using the "Export" button.
2. After clicking the export button, the user is redirected either to the dashboard or to a random Channel / Structure etc.

### Additional info

- Craft version: 3.3.20.1
- PHP version: 7.1.5
- Database driver & version: MySQL 5.7.25

**Comment by brandonkelly** [comment]
Hm, in this case it should definitely work correctly, since element exporting happens via control panel URLs (whereas in #4737, the real issue there is that GraphQL API requests are technically considered “site” requests – so site URLs are used for action URLs).

Try opening up your browser console and outputting the following things: `Craft.baseCpUrl` and `Craft.actionUrl`. What do they output?

**Comment by martinhellwagner** [comment]
@brandonkelly 

The URLs seem to correspond to the custom URL of the dashboard:

![Screenshot 2020-02-03 at 13 23 48](https://user-images.githubusercontent.com/19146752/73653072-ab338b80-4688-11ea-8b56-8e1a480c6d72.png)

**Comment by brandonkelly** [comment]
Yeah that looks right. Keep an eye on your Network tab when you click the Export button inside the export modal. Can you tell me which request is going to the wrong domain?

**Comment by martinhellwagner** [comment]
Seems like none of the request go to the wrong domain. However, the reload (without the export) seems to be happening after the `entries` request:

![Screenshot 2020-02-04 at 09 20 38](https://user-images.githubusercontent.com/19146752/73726491-f81e6d00-472f-11ea-971f-4bc9cff10f0b.png)
![Screenshot 2020-02-04 at 09 21 40](https://user-images.githubusercontent.com/19146752/73726492-f81e6d00-472f-11ea-8d2c-06f330e96716.png)
![Screenshot 2020-02-04 at 09 21 47](https://user-images.githubusercontent.com/19146752/73726493-f81e6d00-472f-11ea-908a-d3f38800c911.png)
![Screenshot 2020-02-04 at 09 21 52](https://user-images.githubusercontent.com/19146752/73726494-f8b70380-472f-11ea-975e-c54e4fa7fc23.png)
![Screenshot 2020-02-04 at 09 22 01](https://user-images.githubusercontent.com/19146752/73726496-f8b70380-472f-11ea-8db4-d2c24548c398.png)

**Comment by martinhellwagner** [comment]
For what it's worth, the "reset password URL" button shows a wrong URL on our production environment. This doesn't happen on our staging environment (where exporting fails too) – but it is possible that some root URL / asset URL etc. is set incorrectly?

**Comment by brandonkelly** [comment]
In your console, what does this output?
```js
var url = Craft.getCpUrl('', {token: 'test'});
```

**Comment by martinhellwagner** [comment]
Also outputs the correct URL:

![Screenshot 2020-02-04 at 19 34 13](https://user-images.githubusercontent.com/19146752/73775030-63def500-4785-11ea-8987-708da3aa2b3e.png)

**Comment by brandonkelly** [comment]
Huh, I wonder why that is 301’ing then. Try running this from your terminal – what is returned?

```bash
curl -I https://kebap-1068.cms.staging.karriere.at/admin?token=test
```

**Comment by martinhellwagner** [comment]
Correct URL, but also 301 apparently. 🤔 

![Screenshot 2020-02-04 at 22 30 47](https://user-images.githubusercontent.com/19146752/73788894-2470d280-479e-11ea-8f60-544ac9ce68ec.png)

**Comment by brandonkelly** [comment]
Very weird. That seems to be the root of your issue though.

Here’s how it’s _supposed_ to work:

1. The JS receives the token to download the export CSV, and sets the window location to that:

https://github.com/craftcms/cms/blob/4d11acc31e4820a56fcc4f9f6b15e6936fe0f174/src/web/assets/cp/src/js/BaseElementIndex.js#L1806-L1809

2. That causes the browser to send a request to https://kebap-1068.cms.staging.karriere.at/admin?token={token}, which **should** route to the ExportController, which will generate the CSV, and return it as the response body, along with a `Content-Disposition: attachment` header which instructs your browser to _download_ the response body as a file, rather than open it in the main browser window, thus having no impact on the current request.

In your case though, instead of getting routed to the ExportController, something is causing that 301 response to come back instead, which is causing the browser to actually redirect itself, rather than downloading a file.

Is there anything in your web server config that could be causing that 301 to be returned, that you can think of?

**Comment by martinhellwagner** [comment]
Seems like the request fails in the first "step" of the cURL request – it's actually okay in the other "steps":

![Screenshot 2020-02-05 at 14 12 05](https://user-images.githubusercontent.com/19146752/73844818-a0f8c500-4821-11ea-9567-c13fd4583f23.png)

I've forwarded this issue to our DevOps.

**Comment by martinhellwagner** [comment]
Turns out the first "step" returns a `301` error because `/admin` is forwarded to `/admin/` in the NGINX configuration:
```
location = /admin {
    return 301  /admin/;
}
```

DevOps changed that, and now the first "step" returns a `302` already:

![Screenshot 2020-02-05 at 15 24 18](https://user-images.githubusercontent.com/19146752/73850234-9b07e180-482b-11ea-8268-67bdfbbfa243.png)

Might be interesting to include the number of "steps" that Craft should try for a request before "giving up" as a config parameter? We're probably not the only ones running Craft with a custom URL and a specific NGINX configuration.

Anyways, thanks for much for the help @brandonkelly! Much appreciated.

**Comment by brandonkelly** [comment]
> Turns out the first "step" returns a `301` error because `/admin` is forwarded to `/admin/` in the NGINX configuration:
> 
> ```
> location = /admin {
>     return 301  /admin/;
> }
> ```

Ah, that makes sense. You might have better luck if you enable the [](https://docs.craftcms.com/v3/config/config-settings.html#addtrailingslashestourls) config setting, so Craft-generated URLs have trailing slashes to begin with.

> Might be interesting to include the number of "steps" that Craft should try for a request before "giving up" as a config parameter? We're probably not the only ones running Craft with a custom URL and a specific NGINX configuration.

Yeah… currently it’s just relying on typical browser behavior of not redirecting the request if the link is for a file download. But there’s probably a better way.

**Comment by brandonkelly** [comment]
(Leaving this open as I do think we can improve it.)

**Comment by martinhellwagner** [comment]
Sorry! 🙈

**Comment by narration-sd** [comment]
n.b. am sure it's obvious, but curl's -L could be a good model - it's very useful in cases like this, for example when there's an http->https bump in the road...

**Comment by brandonkelly** [comment]
@martinhellwagner I believe I’ve just fixed this for the next release. Would you mind testing on your end?

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#b6bd1c4148ea402059d5c0fe168382863cf7c30f as 3.4.3",
  "...": "..."
}
```

Then run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.4.4 is out now with that fix. Let me know if it works for you.

**Comment by martinhellwagner** [comment]
@brandonkelly Looks good! Thank you! 👍

**Comment by brandonkelly** [comment]
Sweet!
