### ISSUE TITLE
UsersController::_handleLoginFailure returns incorrect headers

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#5561]
Failed logins currently return 200 responses, with error/errorCode.
They should return 40x!

This becomes especially important if you are trying to `.catch` a failed response (eg w/ axios/fetch), and expecting failures to throw errors.

Related: https://github.com/craftcms/cms/issues/2495, https://github.com/craftcms/cms/issues/815

Not sure if this is a more widespread problem, but just noticed it with the login controller.

**Comment by brandonkelly** [comment]
Déjà vu! (#3890)

**Comment by timkelty** [comment]
Hah I knew it sounded familiar! AM I THE ONLY HTTP NAZI OR WHAT?!

**Comment by brandonkelly** [comment]
Haha… I’m still all for it, but it‘s still a breaking change that needs to wait for v4.
