### ISSUE TITLE
Multi-site matrix save error

### ISSUE THREAD

**Issue by justinvandenberg** [craftcms/cms#5562]
### Description

In a multi-site matrix field with 1 min causes entry to error on save.  

### Steps to reproduce

1. Add matrix field with 1 min/1 max translatable by site group
2. Add to entry type
3. Try to save entry (was an existing entry in my case)

### Additional info

- Craft version: 3.4.0-beta.5
- PHP version: 7.3.13
- Database driver & version: MySQL 5.7.29
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
This was already reported in #5455, and fixed in Craft 3.4.0-RC2. There’s also a similar bug (#5544) that was just fixed in 3.4.2.
