### ISSUE TITLE
500 error after latest upgrade to 3.4.2

### ISSUE THREAD

**Issue by jamielaughton** [craftcms/cms#5563]
### Description
I have the following errors when trying to upgrade to 3.4.2

### Steps to reproduce

1. ./craft update all

### Additional info

- Craft version: 3.4.1
- PHP version: 7.1.31
- Using MAMP 

### Output
$ ./craft update all
Fetching available updates ... done
Performing 3 updates:

    - craft 3.4.1 => 3.4.2
    - navigation 1.3.0 => 1.3.1
    - super-table 2.4.1 => 2.4.2

Backup the database? (yes|no) [yes]:y
Backing up the database ... done
Performing update with Composer ... error: The "https://codeload.github.com/craftcms/cms/legacy.zip/658755fb36447e1f690d17d5126e556f97754b45" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
Failed to enable crypto
failed to open stream: operation failed

Output:

<warning>Package "craftcms/vue-asset" listed for update is not installed. Ignoring.</warning>
<warning>Package "danielstjules/stringy" listed for update is not installed. Ignoring.</warning>
Loading composer repositories with package information
Updating dependencies
Package operations: 0 installs, 10 updates, 0 removals
  - Updating craftcms/cms (3.4.1 => 3.4.2): Downloading (connecting...)
Downloading (connecting...)
Downloading (connecting...)

Revert the Composer changes? (yes|no) [yes]:y
Reverting Composer changes ... error: The command "'/Users/useradmin/Documents/repos/spacecentre/craft' 'update/composer-install'" failed.

Exit Code: 255(Unknown error)

Additionally i get the following errors after trying  composer install:

[Composer\Downloader\TransportException]
  The "https://codeload.github.com/craftcms/cms/legacy.zip/9a9d5a5d1f512105042edb55b2d0468de4e72f3d" file co
  uld not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
  error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
  Failed to enable crypto
  failed to open stream: operation failed

**Comment by angrybrad** [comment]
> SSL operation failed with code 1. OpenSSL Error messages:
> error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
> Failed to enable crypto
> failed to open stream: operation failed

If you update to the latest version of MAMP, that should fix it for you.
