### ISSUE TITLE
Ability to duplicate entry even though "Create entries" unticked in permissions

### ISSUE THREAD

**Issue by kevadamson** [craftcms/cms#5566]
As the title says, I don't wish my client to be able to create new entries, yet when an entry in a structure is ticked, the drop down allows them to duplicate, thus in a way they are creating a new entry.

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

PS - in the future, please fill out the full issue template when posting new bug reports, so we have more info like what version of Craft you’re using.

**Comment by brandonkelly** [comment]
3.4.3 is out with this fix.
