### ISSUE TITLE
[3.4.2] graphQL : @formatDateTime doesn't work

### ISSUE THREAD

**Issue by wuhhh** [craftcms/cms#5569]
### Description

Using @formatDateTime no longer works using graphQL - the date format string itself is returned instead of a formatted date/time. E.g. "d/m/Y" returns "d/m/Y"

### Steps to reproduce

1. Using the graphQL explorer, query any entry with @formatDateTime specified, e.g.: `dateCreated @formatDateTime(format:"m/Y")`

### Additional info

- Craft version: 3.4.2
- PHP version: 7.3

**Comment by andris-sevcenko** [comment]
Wow, that was a rookie mistake and I hang my head in shame. Pushed a fix for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#c18d6d5f003e5829f9f4c73f04bf95f649008cb1",
  "...": "..."
}
```

Then run `composer update`.

**Comment by brandonkelly** [comment]
3.4.3 is out with this fix.
