### ISSUE TITLE
Unable to write to web generated files with ./craft CLI command

### ISSUE THREAD

**Issue by neilwhitespace** [craftcms/cms#5570]
### Description
We are having issues with an implementation of Craft 3 in that when the `craft` command is run on the CLI, there are permissions issues with certain files in `compiled_classes`.

The command we're running is `php craft project-config/sync` as the SSH user who manages the deployment.

The error we get is:

```
DEBUG [8e6acd4b] 	error: fopen(/var/www/vhosts/[website]/releases/20200131085600/storage/runtime/compiled_classes/CustomFieldBehavior.php): failed to open stream: Permission denied
```

(This is a deployment managed by Capistrano but as far as Craft is concerned, the `storage` folder is just as normal)

Simply setting 777 on the directory as per the installation guide won't work long term, as when PHP runs via the `apache` user, it is creating files that only it owns (such as `storage/runtime/compiled_classes/CustomFieldBehavior.php` with `apache:apache 600`)

Here are all of the files within that folder:

```
-rwxrwxrwx+ 1 apache apache 2011 Jan 21 15:43 ContentBehavior.php
-rw-------+ 1 apache apache 5851 Feb  3 09:43 CustomFieldBehavior.php
-rwxrwxrwx+ 1 apache apache  952 Jan 21 15:43 ElementQueryBehavior.php
```

I've tried using ACLs and that has worked for the most part, but the acl for that one file ends up being this: 

```
# file: CustomFieldBehavior.php
# owner: apache
# group: apache
user::rw-
user:apache:rwx            #effective:---
user:[SSH USER]:rwx        #effective:---
group::rwx            #effective:---
mask::---
other::---
```

This is the ACL for `storage/runtime/compiled_classes/` (note the `default` parts which sub-files should be inheriting):

```
# file: .
# owner: apache
# group: apache
user::rwx
user:apache:rwx
user:[SSH USER]:rwx
group::rwx
mask::rwx
other::rwx
default:user::rwx
default:user:apache:rwx
default:user:[SSH USER]:rwx
default:group::rwx
default:mask::rwx
default:other::rwx
```

Here's what a "good" ACL looks like on another file in that same folder: 

```
# file: ElementQueryBehavior.php
# owner: apache
# group: apache
user::rwx
user:apache:rwx
user:[SSH USER]:rwx
group::rwx
mask::rwx
other::rwx
```

We're at a loss as to how we can resolve this, with the CLI user being different from the web user. ACLs seem to be the way to go, but our experience is leaving us wondering.

### Steps to reproduce

1. Install craft, user from web.
2. Attempt to run commands from CLI that alter files generated by web user.

### Additional info

- Craft version: 3.4.2
- PHP version: 7.2.17
- Database driver & version: MariaDB 10.2.10 (MySQL 5.5.5)
- Plugins & versions: (Likely not relevant but a list can be provided if needed)

**Comment by brandonkelly** [comment]
`CustomFieldBehavior.php` was introduced in Craft 3.4, as a replacement for the other two, which explains the difference there – you must have manually set the other two files to 777 permissions previously.

As far as fixing this in the long run goes, you could try setting the [defaultFileMode](https://docs.craftcms.com/v3/config/config-settings.html#defaultfilemode) config setting to `0777`, but that will depend on what your `apache` user is allowed to do.

**Comment by narration-sd** [comment]
Basic question comes up every time I see this 0777 advice: is this necessary or wise?

It may not seem to matter on a single-user by  admin only droplet, but even there, doing this lays open wider possibilities of takeover by nefarious actors, doesn't it?

The stock-standard *ni/ux way was always 0770 if you need to make perms wide open on a web-based app.  That way, only some owner or group, plus the webserver components themselves, whichever way you choose owner and group, can modify the files.

Key: no-one not included in the user or group can modify them. That's secure control..

I may be missing something, as ever, but this is the history that three level perms were created to solve.

**Comment by narration-sd** [comment]
A little praise to go with that...I keep opening the edit pages on 3.4, and just smile for the beauty and clarity you've achieved here - the red Publish Changes when apropos is crowning touch :)

**Comment by brandonkelly** [comment]
@narration-sd I believe file permissions are only a real concern on multiuser systems, which would be the case if you’re using shared hosting. 

Glad you’re liking the 3.4 improvements!

**Comment by narration-sd** [comment]
Most welcome!

On other point, consider though the 'isolated droplet'.  Only admin gets in.
- Except, maybe others can get in for some local reason, who don't have admin permission/permitted groups. But with 0777, they can go straight into the website and make changes. Nefarious or unintended...
- And then, suppose an actual nefarious actor manages to log in to the droplet, from all the scripted attacks. Once again, with 0777, they are free to alter anything about the Craft site, with any degree of silent or otherwise damage.

This sort of thing is why all *nix control in /etc for example, and all certs info, as letsencrypt does it, is torally locked up -- 'others' --- 0

**Comment by narration-sd** [comment]
Also, I've always run my Craft sites in this 0770 way -- handy, allows setting up sftps, etc., and never has any problem for Craft, contributing parts like php-fpm, or any web content like SPAs itself. 

I use www-data:myadmingroup 0770, and works fine

**Comment by narration-sd** [comment]
Correction -- just looked to assure and actually I run 0775, which lets anyone _read_ whatever's in the website folder. 

Truly, if that's a need, should be 0774, safe side though I don't know any danger in letting them execute something. With 0774, that would allow copying to execute elsewhere, given you think reading and copying by 'others' is ok.

So I'm not entirely consistent myself, but am very sure I don't want to allow over-writing  ('w')

**Comment by brandonkelly** [comment]
Yeah I’m not going to assume that the `apache` user and the SSH user are in the same group though, so having world-write permissions could be needed.

**Comment by narration-sd** [comment]
That's why I have the admin group. The user/s who should come in on SSH just get that admin group added to their group list. All good.

**Comment by neilwhitespace** [comment]
@brandonkelly That is exactly our situation. `apache` is not in the same group as our SSH user, and we'd obviously rather not go with 777 on the files. 

Even if we _did_, the file `CustomFieldBehavior.php` was created with a `600` mode, subverting the ACL or modes applied to the containing folder. If I delete or rename the file, it is re-created when using the site, with the same permissions mode as before.

What would you advise in this instance? It is essentially preventing us from using the CLI command `craft` as when `apache` creates that file, it cannot be written to by the SSH user.

**Comment by narration-sd** [comment]
@neilwhitespace  Late here, but as was getting into above, I think if you 
- make a group, let's say 'admins', 
- and chmod -R  that as the group for what's in the website, 
- and then add the 'admins' group to the login(s) used for SSH, then you'll have access through SSH without 777. 

This is simpler and safer than setting up sudo access for the SSHer/s, as they just can get at the website or anything else you set to admins group with permissions -- not /etc configs, etc..

**Comment by narration-sd** [comment]
added explanation on github for last message, if you're just reading by mail

**Comment by neilwhitespace** [comment]
Interesting idea @narration-sd but that would mean we'd need to `chown` as part of the deployment process, otherwise it wouldn't fix the issue that `storage/runtime/compiled_classes/CustomFieldBehavior.php` has a mode of 600, and is owned by `apache:apache`

The `chown` command would only work for files that exist when the command is run, and won't stop new files from being made inaccessible by Craft when run via apache. It would also have to be combined with a `chmod 77x` command as the group mode would be ineffective if the file had anything other than `6` or `7` for the group bit. (I think!)

What I can't get my head around is just generally how this is expected to work, regarding having a cli `craft` command that needs to touch files owned and operated by the web server. Especially those created with `600` permissions.

**Comment by neilwhitespace** [comment]
@brandonkelly it would be useful if you can confirm whether the mode `600` on this file is actually working as intended or a bug, and in the case of the latter, allow us to re-open this issue if relevant.

(Keeping in mind that both `ContentBehavior.php` and `ElementQueryBehavior.php` in the same folder are created with a full `777` mode).

**Comment by narration-sd** [comment]
Well, I do exactly that - chown the website as part of the deployment process. It's just the one command.

I think, here, that the operative point is that apache is running as _user_ apache.  
- then if the website files are rwx for user apache, it can do anything with them, and the same for processes it forks like php-fpm
- setting the _group_ according to the group you'd give SSHers and any others needing to do website admin, can be to any group name you prefer and create. 
- now, if I understand your point about files 'made inaccessible by Craft'. I think that must mean files _created_ by Craft, thus under the operating user & group of Apache. 
- I was thinking of some ways to do this, but apparently lost in the mists of memory about the setgid bit which will automatically assure files written get the group you prescribe, much easier and more bulletproof than fooling with Apache's execution
- Here's what looks like a very sound procedure for setting that up -- the find step is for sure essential I suspect you'll see:  https://serverfault.com/a/65416

**Comment by neilwhitespace** [comment]
I've done this:
```
[root@xxxx compiled_classes]# usermod -a -G www-pub [SSH-USER]
[root@xxxx compiled_classes]# usermod -a -G www-pub apache
```

Then verified with this:
```
[root@xxxx compiled_classes]# groups apache && groups [SSH-USER]
apache : apache www-pub
[SSH-USER] : [SSH-USER] www-pub
```

Then chowned and verified:
```
[root@xxxx compiled_classes]# chown -R root:www-pub .
[root@xxxx compiled_classes]# ls -al
drwxrwxrwx+ 2 root   www-pub   96 Feb  4 09:30 .
drwxrwxrwx+ 8 apache apache   126 Jan 22 10:28 ..
-rwxrwxrwx+ 1 root   www-pub 2011 Jan 21 15:43 ContentBehavior.php
-rw-------+ 1 root   www-pub 5851 Feb  4 09:30 CustomFieldBehavior.php
-rwxrwxrwx+ 1 root   www-pub  952 Jan 21 15:43 ElementQueryBehavior.php
```

Then set the sticky bit:
```
[root@xxxx compiled_classes]# chmod -R 2775 .
[root@xxxx compiled_classes]# ls -al
total 16
drwxrwsr-x+ 2 root   www-pub   96 Feb  4 09:30 .
drwxrwxrwx+ 8 apache apache   126 Jan 22 10:28 ..
-rwxrwsr-x+ 1 root   www-pub 2011 Jan 21 15:43 ContentBehavior.php
-rwxrwsr-x+ 1 root   www-pub 5851 Feb  4 09:30 CustomFieldBehavior.php
-rwxrwsr-x+ 1 root   www-pub  952 Jan 21 15:43 ElementQueryBehavior.php
```

Then I deleted the file `CustomFieldBehavior.php` and loaded the site, letting Craft re-create that file:

```
[root@xxxx compiled_classes]# ls -al
total 16
drwxrwsr-x+ 2 root   www-pub   96 Feb  4 09:36 .
drwxrwxrwx+ 8 apache apache   126 Jan 22 10:28 ..
-rwxrwsr-x+ 1 root   www-pub 2011 Jan 21 15:43 ContentBehavior.php
-rw-------+ 1 apache www-pub 5851 Feb  4 09:36 CustomFieldBehavior.php
-rwxrwsr-x+ 1 root   www-pub  952 Jan 21 15:43 ElementQueryBehavior.php
```
And there it is again, owned by apache (although in the right group at least), but still with the mode of `600`.

If I `su` to the SSH user and touch a file, it is made correctly:

```
[root@xxxx compiled_classes]# su [SSH-USER]
[[SSH-USER]@xxxx compiled_classes]$ touch testperms.txt
[[SSH-USER]@xxxx compiled_classes]$ ls -al
total 16
drwxrwsr-x+ 2 root    www-pub  117 Feb  4 09:45 .
drwxrwxrwx+ 8 apache  apache   126 Jan 22 10:28 ..
-rwxrwsr-x+ 1 root    www-pub 2011 Jan 21 15:43 ContentBehavior.php
-rw-------+ 1 apache  www-pub 5851 Feb  4 09:36 CustomFieldBehavior.php
-rwxrwsr-x+ 1 root    www-pub  952 Jan 21 15:43 ElementQueryBehavior.php
-rw-rw-rw-+ 1 [SSH-USER] www-pub    0 Feb  4 09:45 testperms.txt
```

Which hugely implies that Craft is specifically setting the permissions and owner of `CustomFieldBehavior.php`. Whether that is expected or even desired behaviour is something I'd like to clarify.

I'm at a loss here, and it looks like `chmod`-ing the entire of `storage` and `cpresources` to 777 at deployment time is the only solution unless someone at P&T can weigh in.

**Comment by neilwhitespace** [comment]
(I forgot to thank you for your help so far @narration-sd, so — thanks!)

**Comment by narration-sd** [comment]
Most welcome. I wish it was as easy to untangle some surprise javascript graphql module and webpacked client-side real oddities I'm chasing :)

600 -- yes, somebody is setting the perms value or range allowed (umask) when the file is created. 

This could happen at many levels, from Apache downwards, and is best taken up with Brandon, if you need to be fooling with those files. 

I'm not sure just where you are with them (I was thinking of more public things like image assets), but if they're Craft's on-the-fly precompiles or such, you may not need to do anything with them to deploy successfully, as they'd always be (re-)created...

Best fortune - I think you're most of the way there.

**Comment by neilwhitespace** [comment]
>  I wish it was as easy to untangle some surprise javascript graphql module and webpacked client-side real oddities I'm chasing :)

I'd rather have _this_ problem any day ;)

> This could happen at many levels, from Apache downwards, and is best taken up with Brandon, if you need to be fooling with those files.

We have verified with absolute certainty that a test file created with a standard `file_put_contents` command in PHP was made with expected permissions. It seems to be only this one file (so far) which is the odd one out. I'm hoping @brandonkelly can weigh in in that respect!

> I'm not sure just where you are with them (I was thinking of more public things like image assets), but if they're Craft's on-the-fly precompiles or such, you may not need to do anything with them to deploy successfully, as they'd always be (re-)created...

The thing is, we as a dev team don't care about the files — it's the `craft` command line tool that does. We assume it interacts with them in some way when the cli command is run, same as through apache. However, if the command is run as the SSH user (which it always will be), then PHP inherently has no access to that one file, and the whole deployment fails.

(Just to clarify: the command we run is `php craft project-config/sync`, to ensure our `project.yml` file changes are updated on the server.)

**Comment by narration-sd** [comment]
Ah, see where you're at.  
Yes, Brandon for sure :)  (this is why he and I are friends...)
Or possibly you could get Andris @andris-sevcenko to have a look, on your  timezone, very speakable (you'll find out) and I think he deals with project config : andris@pixelandtonic.com

**Comment by narration-sd** [comment]
@neilwhitespace , I just made a pass through the Craft source (with good tool) including where that file is constructed, but also where umask(2) may be used.

Conclusion: Craft itself is unlikely to be causing your problem in completing this exercise.

In fact, what seems most likely is that umask may be getting set for your SSH'd login.

- you can see what it is by just typing umask into the shell
- normal values would be 0002 or 0022, so that perms resulting on creating files would be missing th the w write bit on others or others and group.
- but another possible value is 0077, which would give you the only-owner-access file as you've gotten by running the craft command.
- if that's the case, you'll likely see you can test by first entering umask 0002, and next re-tryhng that craft sync command. 
- and a fix would be to search out a umask command in shell startup files (.profile, .bashrc, etc.) for your SSH user and replace it appropriately. Or just put a umask [appropriate] in one of those startups that's run late -- .bashrc perhaps if it's a bash shell.

Now one more run of my debug output, and off to Nod

**Comment by narration-sd** [comment]
once again, more content added....

**Comment by neilwhitespace** [comment]
@narration-sd that's interesting, and would likely have been the issue but in this case the file in question is being created by `apache`, not my SSH user.

There are other files in that folder, also created by `apache` which have appropriate permissions, so this cannot be anything other than an issue coming from the apache-based workflow. Whether it's Craft or not, I don't know, however!

Thank you for your reply anyway :)

**Comment by narration-sd** [comment]
Ok, it's late, and I seem to be under the impression from what you said that you created the file by running project config sync. Maybe the problem comes instead when you run sync in presence of that file. 

So yes, you'll have to track it down. I still think my analysis of what Craft does and doesn't do is likely correct, so the umask may be happening or need to be non-default in Apache config.

**Comment by narration-sd** [comment]
Or again, umask be positively set and recovered in Craft so that they know the file perms will be correct for all uses...

**Comment by neilwhitespace** [comment]
> So yes, you'll have to track it down. I still think my analysis of what Craft does and doesn't do is likely correct, so the umask may be happening or need to be non-default in Apache config.

That's also possible, and I'll have a hunt for Apache doing something weird, but it doesn't explain why one file would be like this, and the other two are ok!

Sounds I should let you get on ;) Thanks for all the help so far!

**Comment by narration-sd** [comment]
Again, you're quite welcome, Neil.

And, the problem here is resolved, so, rest transpires...

Clive

**Comment by brandonkelly** [comment]
> (Keeping in mind that both `ContentBehavior.php` and `ElementQueryBehavior.php` in the same folder are created with a full `777` mode).

As said, those files are from pre-3.4. The way `CustomFieldBehavior.php` is created in `3.4+` is basically identical to the way that `ContentBehavior.php` and `ElementQueryBehavior.php` were created in `3.3-` (only difference being that we now initially write the file in a temp location and then move it into place in `storage/runtime/compiled_classes/` after – to avoid a race condition where other requests could end up reading a partially-written file).

So either your environment changed, or someone manually changed the file mode on those files at some point, and that same thing needs to be redone for `CustomFieldBehavior.php`.

From Craft 3.3.20.1 (last 3.3 release):

https://github.com/craftcms/cms/blob/4d11acc31e4820a56fcc4f9f6b15e6936fe0f174/src/Craft.php#L429

From Craft 3.4.3 (latest 3.4 release):

https://github.com/craftcms/cms/blob/8436bfe373e81a2cc9d551feb4f9bad8d0fbdefb/src/Craft.php#L280-L281

**Comment by narration-sd** [comment]
@brandonkelly , I believe Neil said he let Craft recreate the file, in one of his tests above - https://github.com/craftcms/cms/issues/5570#issuecomment-581832449 , ending up with the bogus permissions.

Given Craft pretty clearly doesn't mess with umask for this write, it's kind of got to be a umask set on apache/php-fpm, no?

**Comment by neilwhitespace** [comment]
Thanks guys, I'll do more testing and get back to you if I figure this out.

**Comment by neilwhitespace** [comment]
Hi all — So I've done some testing and it looks like this issue may be stemming from the fact that PHP creates a temporary file first.

I've played with umask/group/user settings within both apache and PHP-FPM and it has substantially helped permissiveness with the two users for both reading and writing files, but `CustomFieldBehavior.php` appears to stand alone in remaining unreadable by any user other than the creating user (`apache`) even with a group sticky bit, a umask `0002` on both apache and php-fpm, and default recursive ACL settings on the `storage` directory.

We think this is because the file `CustomFieldBehavior.php` is first created within `/tmp` and then moved to the correct location after being written. It is by nature of its creation within `/tmp` that it has more restrictive permissions applied. An example the contents of `storage/` after first load:

```
.
├── [drwxr-xr-x apache   www-pub ]  logs
│   └── [-rwxrwxr-- apache   www-pub ]  web.log
└── [drwxr-xr-x apache   www-pub ]  runtime
    ├── [drwxrwxr-x apache   www-pub ]  cache
    │   ├── [drwxrwxr-x apache   www-pub ]  2e
    │   │   └── [-rwxrwxr-- apache   www-pub ]  2e42faf3777c4a1ed20c0b98cd01f128.bin
    │   ├── [drwxrwxr-x apache   www-pub ]  54
    │   │   └── [-rwxrwxr-- apache   www-pub ]  54433387bed9eafab5c47737271619b7.bin
    │   ├── [drwxrwxr-x apache   www-pub ]  7a
    │   │   └── [-rwxrwxr-- apache   www-pub ]  7ab5b9701c726ee3cd940674b508d918.bin
    │   ├── [drwxrwxr-x apache   www-pub ]  98
    │   │   └── [-rwxrwxr-- apache   www-pub ]  9813d5c7ffecbfb4d54f8efbb6efa50b.bin
    │   ├── [drwxrwxr-x apache   www-pub ]  cb
    │   │   └── [-rwxrwxr-- apache   www-pub ]  cbcd8e2385b0f259a4f9690a08f238e6.bin
    │   ├── [drwxrwxr-x apache   www-pub ]  d0
    │   │   └── [-rwxrwxr-- apache   www-pub ]  d02e3c6a8fd8f1a75fb52206b6319e14.bin
    │   ├── [drwxrwxr-x apache   www-pub ]  da
    │   │   └── [-rwxrwxr-- apache   www-pub ]  da9c8c096fd90a38b57db53a0b1db3e5.bin
    │   ├── [drwxrwxr-x apache   www-pub ]  e5
    │   │   └── [-rwxrwxr-- apache   www-pub ]  e5760a0a998de6a7a3a84754dd84ccb0.bin
    │   ├── [drwxrwxr-x apache   www-pub ]  f2
    │   │   └── [-rwxrwxr-- apache   www-pub ]  f20f947019382b41f56fdbe961ddf7dd.bin
    │   └── [drwxrwxr-x apache   www-pub ]  us
    │       └── [-rwxrwxr-- apache   www-pub ]  useFileLocks.bin
    ├── [drwxrwxr-x apache   www-pub ]  compiled_classes
    │   └── [-rw------- apache   www-pub ]  CustomFieldBehavior.php
    ├── [drwxrwxr-x apache   www-pub ]  compiled_templates
    │   ├── [drwxrwxrwx apache   www-pub ]  07
    │   │   └── [-rw-rw-r-- apache   www-pub ]  07218a321d24eb15371f43133c431e4e24b5c54d17483dba90b914551af32fea.php
    │   ├── [drwxrwxrwx apache   www-pub ]  10
    │   │   └── [-rw-rw-r-- apache   www-pub ]  10538b58491c14ea2a320c0416732f65a138ec355c6cab38f69a412e71cd64d6.php
    │   ├── [drwxrwxrwx apache   www-pub ]  18
    │   │   └── [-rw-rw-r-- apache   www-pub ]  182b8081dca8b4bc86f1ed003f9f3da69b0f59bd6e59a39be7b89f642d1dc46d.php
    │   ├── [drwxrwxrwx apache   www-pub ]  51
    │   │   └── [-rw-rw-r-- apache   www-pub ]  51eccc97bcedab168455b4a1295483c4111631692114d9d441ff0bc1f7231022.php
    │   ├── [drwxrwxrwx apache   www-pub ]  59
    │   │   └── [-rw-rw-r-- apache   www-pub ]  594d5cf744454198037bdd88692116e90f041edb066581ec4f410f417b574759.php
    │   ├── [drwxrwxrwx apache   www-pub ]  67
    │   │   └── [-rw-rw-r-- apache   www-pub ]  6762495a1d6ef9f0c0d9a8a4798fd02fc2266c75dbc3d3837a9a067fc4517708.php
    │   ├── [drwxrwxrwx apache   www-pub ]  7e
    │   │   └── [-rw-rw-r-- apache   www-pub ]  7e6a47cba9ab960ad12282964bff7153edaff6f4212793949e2cc5ddd88ccf4e.php
    │   ├── [drwxrwxrwx apache   www-pub ]  87
    │   │   └── [-rw-rw-r-- apache   www-pub ]  8733bbed2a2798bc9fa82899b1eb812297ebe80f65d610bb488ea6aae0fbde46.php
    │   ├── [drwxrwxrwx apache   www-pub ]  d3
    │   │   └── [-rw-rw-r-- apache   www-pub ]  d3b455b6263e1b50031e0b6758cff1a24c0ef05495accb07720e88ef3ff130cf.php
    │   ├── [drwxrwxrwx apache   www-pub ]  e9
    │   │   └── [-rw-rw-r-- apache   www-pub ]  e9b82dc9eaf0ce7a27e2b127b561885b5af735703050cb24300efd556fa21662.php
    │   └── [drwxrwxrwx apache   www-pub ]  fc
    │       └── [-rw-rw-r-- apache   www-pub ]  fc151ebb7cfd37e48d346fd4c748b98603c0cb708dc0fc77d6fe0b71a9fe0844.php
    └── [drwxrwxr-x apache   www-pub ]  mutex
```

Within this list, you can see that `CustomFieldBehavior.php` is the *only* file which can't be affected by users other than apache, despite the FS settings to the contrary.

I'm very reluctant to mess with ACLs or sticky bits on the `/tmp` directory as it is shared by the system and other users, so I think there are two options here and would appreciate if you could explore them:

1) Consider create temporary files within `storage` instead of `/tmp`.

2) Make use of `defaultFileMode` to ensure a mode is enforced on the `CustomFieldBehavior.php` file once it is moved to the correct location.

I realise 2 might not work for those who haven't set a `defaultFileMode` setting so option 1 might be most viable.

Possibly related:
https://stackoverflow.com/questions/40695803/change-permission-for-a-file-created-using-tempnam-from-600-to-644

**Comment by narration-sd** [comment]
Smart moves. Yes, that's *nix protecting everyone from everyone as you'd expect, though I don't remember if it was done by setgid bits in the early days.

It's for Brandon to work out with you solutions, but feels you've got some pretty good suggestions, so this whole thing leaves me with a pleasant feeling.

**Comment by brandonkelly** [comment]
Interesting, ok, so that change is in fact the culprit here.

We modeled that change after how Twig’s compiled template classes get generated. Can you check your files in `storage/runtime/compiled_templates/` and let me know if those PHP files have the same permissions as `CustomFieldBehavior.php`?

**Comment by neilwhitespace** [comment]
Hi @brandonkelly — of course! They're listed above too, but here's a recent sample of that folder:

```
.
├── [drwxrwxrwx apache   apache  ]  01
│   └── [-rw-rw-r-- apache   apache  ]  010534afb0bb4bdab5f46015cb88116a750962c2075f2748cc086b36d70166c2.php
├── [drwxrwxrwx apache   apache  ]  04
│   └── [-rw-rwxr-- apache   apache  ]  047d504cd501af45eeae656637516e6eccd0053774f779831ad6d499294d4aea.php
├── [drwxrwxrwx apache   apache  ]  05
│   ├── [-rw-rwxr-- apache   apache  ]  050a659c751cf833ec01ec8a1a828950a00617ea2df8a5969888f35801fd31f6.php
│   ├── [-rw-rw-r-- apache   apache  ]  0535b0d4eaa3fbb7882ac2ae61716841047552f6db7f5802c7aeb05aca252f59.php
│   ├── [-rw-rw-r-- apache   apache  ]  054d9dcd77e0ba67fb5655b178e157530a13c957bfdc45d604591977ca7e99f5.php
│   ├── [-rw-rw-r-- apache   apache  ]  05540f2f2d792c44398c99a1e42bd974f3918c355dadc36f7fad5c04d992daa7.php
│   └── [-rw-rwxr-- apache   apache  ]  058c0999e45b5188c290f7d9c00a45626000b6f96734d8062b5b2ce2afc9f1da.php
├── [drwxrwxrwx apache   apache  ]  06
│   ├── [-rw-rw-r-- apache   apache  ]  063ef4876c5ebb70643ce43f12ccccda09b183ce191921f2f257ce1ced6b5a7e.php
│   └── [-rw-rw-r-- apache   apache  ]  068da4e6dda7de4d0db120913c4feb5b269a835b46b1e54185e36eca1242ef72.php
├── [drwxrwxrwx apache   apache  ]  07
│   ├── [-rw-rwxr-- apache   apache  ]  07218a321d24eb15371f43133c431e4e24b5c54d17483dba90b914551af32fea.php
│   ├── [-rw-rw-r-- apache   apache  ]  077395ba337b1a210d9d6bdcf5e5f1b011634da48b9a0e4e1fd0909991f90084.php
│   └── [-rw-rwxr-- apache   apache  ]  07f16db9bca89c6ded74cefb296b450788f8a46fc4658748637d5a21d0508eb9.php
```

(We've since reverted the `www-pub` group change so everything's apache:apache but the permissions would allow group read/write if we needed it in this case.)

Is it possible that twig is then `chmod`ing the files after they are created?

**Comment by brandonkelly** [comment]
Thanks @neilwhitespace. I just tweaked it so the temp file gets created directly in the `compiled_classes` folder rather that `tmp`. Can you please update to a43b6d99392f0360c48d3be7746626fa0785b793 on your end and see if that helps?

To do that, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#a43b6d99392f0360c48d3be7746626fa0785b793 as 3.4.3",
  "...": "..."
}
```

Then run `composer update`.

**Comment by brandonkelly** [comment]
> Is it possible that twig is then `chmod`ing the files after they are created?

It is; if that last commit doesn’t solve this, we can try that as well.

**Comment by brandonkelly** [comment]
Craft 3.4.4 is out now with that change. Let me know if we have more work to do.

**Comment by neilwhitespace** [comment]
Thanks @brandonkelly — we'll give it a go and report back!

**Comment by neilwhitespace** [comment]
Word from the devs is that the fix worked as expected, so thanks for that!

**Comment by brandonkelly** [comment]
Good to hear, thanks!
