### ISSUE TITLE
Bug? Filtering Matrix field by type changes content of the matrix field in the template.

### ISSUE THREAD

**Issue by TomDeSmet** [craftcms/cms#5572]
### Description
I have a matrix field in an entry. The matrix field consists of a few block types.
I want to count the number of blocks from a certain type and afterwards I want to loop over every block inside that matrix field.
But whenever I filter the matrixblock by type or do a count of those types, the contents of the matrix field change. So it seems that ```.type('blockType')``` changes the matrix in that template.

### Steps to reproduce

```
{{ dump(entry.contentGrid.all()|length) }}
{# Returns 10 -> correct #}

{# Count all blocks with a certain type:
 # I have tried .count() also and it returns the same just as type String instead of type Number 
 #}
{% set advantageTotal = entry.contentGrid.type('blockAdvantage').all()|length %}

{{ dump(advantageTotal) }}
{# Returns 5 -> correct #}

{{ dump(entry.contentGrid.all()|length) }}
{# Returns 5 -> HUH?!?! Why doesn't this return 10 again? #}
```

If I do another filter by type in another Twig template which I include on the same page template, that one overwrites my matrix field also!
### Additional info

- Craft version: 3.4.2
- PHP version: 7.2
- Database driver & version: MySQL
- Plugins & versions (related To Matrix Field): MatrixMate, Cloner
But disabeling them didn't change anything.

**Comment by andris-sevcenko** [comment]
You can't re-use the queries like that in Craft 3. You should [clone them](https://docs.craftcms.com/v3/changes-in-craft-3.html#cloning-element-queries), instead.

**Comment by TomDeSmet** [comment]
I didn't know that, thanks.

I just want to add that it is kind of annoying that this behavior works across templates.
Let me explain:

I have the _layout template which includes first template A and than template B.
In both I use the same Matrix field but I want to show different types.

So I set the ```allBlocks``` variable in template A which I than clone to filter on block types.
The ```allBlocks``` isn't known in template B of course, so I can't re-use that one, but the element query with the filtered types is remembered in that template, so I need to do a clone there as well.

So, is that query remembered through the whole site? Do I need to remember in every template that I need to clone that query from now one because it's being changed somewhere in another template? Or is it just because they are included within the same _layout template that the query is remembered?

**Comment by andris-sevcenko** [comment]
@TomDeSmet I'm not sure that relying on a query that is defined in a different template is an idea that is easy to maintain in long-term. (If I'm understanding correctly that you originally define your query in the `_layout` template.

A cleaner approach would be to define a macro that returns a fresh query with all the parameters you need and then call that macro in each template where you need to query for matrix blocks with predefined parameters.

**Comment by TomDeSmet** [comment]
@andris-sevcenko I'm not. It was just an example. I'm also not storing the query in any reusable variable.

To be more clear: when I call ```entry.matrixfield.type('blockTypeA')``` in TemplateA that query is still filtered with those A type blocks in TemplateB when I call ```entry.matrixfield.all()```.

That's weird to me. It seems the ElementCriteria Model is stored globally?

**Comment by andris-sevcenko** [comment]
Is `entry` the same variable in both templates?

That would also explain it because relational fields on elements are actually element queries, so, in a technical sense, you would still be accessing a query that is in a reused variable (_if_ the `entry` variable is defined in the parent template).  I think.

Pinging @brandonkelly to elaborate and to see if I'm misunderstanding something (which wouldn't be the first time)

**Comment by brandonkelly** [comment]
@TomDeSmet Let me try to explain.

When you have an entry (e.g. `entry`), and you access `entry.contentGrid` multiple times, the same Matrix block query object will be returned **each time**. If you end up setting a parameter on the query (e.g. `entry.contentGrid.type('blockAdvantage')`), that parameter change will stay in effect until you “undo” it (e.g. `entry.contentGrid.type(null)`).

The easiest way to work around this is by using that [clone()](https://docs.craftcms.com/v3/dev/functions.html#clone) function, which will clone the Matrix query, before you start customizing the parameters:

```twig
{{ dump(entry.contentGrid.count()) }}
{# Returns 10 -> correct #}

{# Count all blocks with a certain type: #}
{% set advantageTotal = clone(entry.contentGrid).type('blockAdvantage').count() %}
{{ dump(advantageTotal) }}
{# Returns 5 #}

{{ dump(entry.contentGrid.count()) }}
{# Returns 10 again #}
```

**Comment by brandonkelly** [comment]
> So, is that query remembered through the whole site? Do I need to remember in every template that I need to clone that query from now one because it's being changed somewhere in another template? Or is it just because they are included within the same _layout template that the query is remembered?

The query is remembered as long as you are working with the same entry object. Objects are not automatically duplicated when including/extending a template – the same object is passed around from template to template as long as you don’t redefine it.

**Comment by brandonkelly** [comment]
All that said, this has admittedly been a common point of confusion in Craft 3, and we have an idea of how to resolve it in Craft 4.
