### ISSUE TITLE
Fabric.js violates "Content Security Policy" headers

### ISSUE THREAD

**Issue by rob-baker-ar** [craftcms/cms#5573]
### Description

fabric.js seems to be used somewhere in the control panel, but falls foul of `Content-Security-Policy` headers. Specifically, it want's `eval()` enabled.

As described here too:

https://github.com/fabricjs/fabric.js/issues/1621

### Steps to reproduce

1. Set CSP headers like (i.e. in NGNIX): `script-src 'self' 'unsafe-inline'`
2. Load the control panel, browser console error like:

```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' ... 'unsafe-inline'".
```

### Additional info

- Craft version: 3.3.19
- PHP version: N/A
- Database driver & version: N/A
- Plugins & versions: N/A

**Comment by andris-sevcenko** [comment]
Duplicate of #3122
