### ISSUE TITLE
Craft 3.4 : Large tables in CP can't scroll horizontally

### ISSUE THREAD

**Issue by rtrudel** [craftcms/cms#5574]
### Description

The data tables in CP (Garnish) with a lot of columns do not allow to scroll horizontally. That makes the right columns out of viewport and not visible. It's impossible to scroll using the horizontal scroll on Mac Magic Mouse (nor touch screen) neither.

In previous versions, if something like this occured, Craft was changing to an alternate display, table-less, to show all selected columns in a block of information. From 3.4, it seems the behavior changed.

At least, if a horiontal scrollbar could be shown at botton of the table, would be great, but the best would be to allow the  first column (title) to be fixed at left and other columns would scroll horizontally. 

ex: https://getbootstrap.com/docs/4.0/content/tables/#responsive-tables
or: https://codepen.io/paulobrien/pen/gWoVzN

### Steps to reproduce

1. Go in CP, Entries
2. Click the gear to select columns to show
3. Select at least 8, 10 or more  just to be sure.
4. Save this, then resize down the browser window if needed. At some point, it will be impossible to see columns at right, without any way to scroll right.

### Additional info

- Craft version: 3.4.2
- PHP version: 7.2

![image](https://user-images.githubusercontent.com/18495095/73688085-43397100-4699-11ea-93cb-61cd0abdab0d.png)

**Comment by brandonkelly** [comment]
The table’s `div.tablepane` wrapper does in fact have `overflow-x: auto` on it, so it should scroll horizontally for you. From your screenshot, it looks like the real culprit is that it’s not being locked down to the pane’s width.

Can you try disabling your custom control panel styles, to see if that’s the culprit?

**Comment by rtrudel** [comment]
i tried disabling every plugin who may affect CP, such as Child Me, CP Field Inspect and Sidebar Themes.

But I found something more to help you reproduce (maybe):

The behavior is good (scroll works) if viewport width < 976
The problem begins if viewport width >=976 AND table width > space for tablepane

**Comment by brandonkelly** [comment]
Thanks! I was able to reproduce in Firefox, and just got this fixed for the next release.

**Comment by rtrudel** [comment]
Yeah this could be useful for you to know, sorry. I'm on Firefox 72 indeed :).

Glad it helped. Thank you and keep up the great work, I'm loving my job even more since I'm using Craft and my clients are very happy with it!

**Comment by brandonkelly** [comment]
Craft 3.4.4 is out now with this fix.
