### ISSUE TITLE
[Feature Proposal] Ability to pass parameters to element's getUrl() method

### ISSUE THREAD

**Issue by benface** [craftcms/cms#5579]
Looking at the [`getUrl()` method](https://github.com/craftcms/cms/blob/master/src/base/Element.php#L1588-L1596) of `craft\base\Element`, it would be nice if it accepted parameters that would then be passed into `UrlHelper::siteUrl()` (second argument). One use case is having an entry that uses GET parameters to filter results, and wanting to link to a specific set of results. It is possible to do it like this:

```twig
<a href="{{ entry.url ~ '?new=1' }}">New posts</a>
```

but I feel like this would be cleaner:

```twig
<a href="{{ entry.getUrl({ new: true }) }}">New posts</a>
```

**Comment by brandonkelly** [comment]
I don’t think all element types should have to worry about appending URL parameters onto their element URLs. You can easily append additional params dynamically using the global [url()](https://docs.craftcms.com/v3/dev/functions.html#url) function though:

```twig
<a href="{{ url(entry.url, {new: '1'}) }}">New posts</a>
```

Or use the [tag()](https://docs.craftcms.com/v3/dev/functions.html#tag) function so you don’t have to type any HTML here:

```twig
{{ tag('a', {
    url: url(entry.url, {new: '1'})
    text: 'New posts'
}) }}
```

**Comment by benface** [comment]
@brandonkelly Ah, I didn't realize I could pass a fully qualified URL to `url()`. That works then, thanks!
