### ISSUE TITLE
Enhancement: Schema that can query drafts without live preview token by draft last updated date..

### ISSUE THREAD

**Issue by simeon-smith** [craftcms/cms#5580]
For static site generators like Gatsby, it would be great to be able to set up a GraphQL schema that allows the user to query drafts. Particularly being able to query by the draft's last updated date. I've got a live preview server setup for Gatsby and need to be able to query entries that have drafts that were updated today. This would allow for draft preview without having to re-query every page.

If it could work similarly to this GraphQL query that would be very helpful.

```graphql
query previewDraft($today: [String]) {
  entries(section: "pages", dateUpdated: $today, drafts: true) {
    id
    slug
    uri
    title
  }
}
```

@dangayle

**Comment by dangayle** [comment]
Yeah, being able to limit queries to just drafts would  really help speed
up previews that would otherwise require a full build if you’re using
gatsby-node.js to query pages.

**Comment by dangayle** [comment]
Presumably this will be a non-issue once the rumored CraftCMS source plugin
gets released, and/or Gatsby releases some form of partial builds that is
compatible with the gatsby-node APIs.

Until that time however, it would be great to have a flag of some sort to
limit queries to only items that are being previewed.

**Comment by andris-sevcenko** [comment]
Alright, so I pushed the changes to the `feature/graphql-draft-support` branch which should allow for this.

Please note, that the branch in question will get merged into the `3.5` release, not 3.4

**Comment by simeon-smith** [comment]
Thank you for doing this!

**Comment by andris-sevcenko** [comment]
Merged into 3.5

**Comment by dangayle** [comment]
@andris-sevcenko Is there a pr for the code that I can turn into a patch for 3.4?

**Comment by andris-sevcenko** [comment]
@dangayle no PR, but it was done on a separate branch. Here's the diff: https://github.com/craftcms/cms/compare/develop...feature/graphql-draft-support

**Comment by brandonkelly** [comment]
To access the change early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "3.5.x-dev",
  "...": "..."
}
```

Then run `composer update`.

But beware, you’ll then be running Craft from its 3.5 branch, which isn’t going to be as stable as we are working on additional 3.5 features.
