### ISSUE TITLE
PDF assets outside of web root can't be previewed

### ISSUE THREAD

**Issue by mikewink** [craftcms/cms#5581]
### Description

We save sensible documents in our Craft installation. Therefore we put those assets outside the web directory. I wrote a dedicated controller action that handles all aspects for those documents like viewing and downloading. 

I can get an image preview in the asset manager, but not for pdf files. This results in a 404 Template not found error.

### Steps to reproduce

1. Create an asset directory outside of webroot
2. Upload a PDF file
3. Open details for that file
4. Click preview while hovering over the preview pane in the top right corner

### Additional info

- Craft version: 3.4.2
- PHP version: 7.4.2
- Database driver & version: 5.7.28
- Plugins & versions: multiple, the only I could think of being relevant are: imageOptimize 1.6.8, Asset usage 2.0.1 and my custom plugin which is already turned of

**Comment by brandonkelly** [comment]
PDFs in volumes without base URLs shouldn’t have been previewable in the first place. Just fixed that for the next release. Thanks for reporting!

**Comment by brandonkelly** [comment]
Craft 3.4.4 is out now with that fix.
