### ISSUE TITLE
After update  3.4.3 useres who has access to GLOBALS get > User not permitted to edit global set > everthing is same about that user permission group

### ISSUE THREAD

**Issue by Djive** [craftcms/cms#5583]
### Steps to reproduce

1.
2.

### Additional info

- Craft version: 3.4.3 (Pro)
- PHP version: 7.2.26
- OS version: Linux 3.10.0-962.3.2.lve1.5.25.10.el7.x86_64
- Database driver & version: MySQL 5.6.45
- Image driver & version: GD 7.2.26
- Plugins & versions: 
    - Admin Bar 3.1.8.1
    - Advanced Url Field 1.0.0
    - Button Box 2.0.4
    - Colour Swatches 1.2.3
    - Comments 1.3.3
    - Connect 1.0.0
    - Content Stats 2.1.1
    - Control Panel Body Classes 2.1.1
    - Control Panel CSS 2.2.0
    - Control Panel JS 2.2.0
    - craft-reports 1.0.7
    - Craft Cheat Sheet 2.0.3
    - Dark Sky Weather 1.0.6
    - Default Dashboard 1.0.6
    - Do It Yourself widget 2.0.1
    - Eager Beaver 1.0.4
    - Element API 2.6.0
    - Entry Instructions 1.0.7
    - Feed Me 4.2.0.1
    - Field Manager 2.1.1
    - Guest Entries 2.2.4
    - Hide Admin 1.1.0
    - HTTP2 Server Push 1.0.1
    - Imager v2.3.1
    - Image Resizer 2.0.6
    - Imager Pretransform 2.0.3
    - Minifier 2.0.3
    - Minify 1.2.9
    - OpenWeather 1.0.2
    - Portal 1.1.3
    - Query 2.0.3
    - Queue Manager 1.2.0
    - Redactor 2.5.0
    - Redactor Custom Styles 3.0.2
    - Redirektovi 3.1.33
    - Retcon 2.0.12
    - Rich Variables 1.0.24
    - Section Field 1.1.0
    - Sentry 1.5.1
    - SEO 3.2.41
    - Sidebar Themes 1.1.0
    - Single Site Publisher 1.0.0
    - Sites Field 1.0.0
    - Smart Map 3.2.2.1
    - Tags 1.0.6
    - Tools 2.1.8
    - Typogrify 1.1.18
    - Webhooks 2.2.0
    - Webperf 1.0.17
    - Width Fieldtype 1.0.6
    - Wordsmith 3.1.1

**Comment by brandonkelly** [comment]
I’m not able to reproduce that. Just created a test user with only two permissions: “Access to the control panel”, and access to a global set. Then logged in as that user and have no problem accessing or making changes to that global set.

Is this a multi-site install? If so, make sure your user has permission to access at least one site.

If that doesn’t help, please send a database backup and your `composer.json` and `composer.lock` files over to support@craftcms.com and we’ll see if we can reproduce it with those.

**Comment by Djive** [comment]
its multisite...

user have permission and he can do everythign as until now...
only cant acces globals..
and nothing changed on globals permissions..

**Comment by brandonkelly** [comment]
Alright, so please send in those files to support@craftcms.com then.

**Comment by fantasticmachine** [comment]
Was there a resolution to this? I feel I've just encountered the same issue after upgrading a Multisite Craft 2 site to Craft 3

**Comment by brandonkelly** [comment]
@fantasticmachine Not sure, but if you send your Composer files + DB backup into support@craftcms.com, we can help look into it.

**Comment by fantasticmachine** [comment]
I managed to resolve it by resaving the global field layouts.
Sorry, meant to come back here and say so!

**Comment by tomdavies** [comment]
Will come back with a test case for you but might be a week or so
