### ISSUE TITLE
Asset link disappears after saving entry

### ISSUE THREAD

**Issue by alexjcollins** [craftcms/cms#5584]
### Description
As of 3.4, when an asset is uploaded the user gets a link to that asset page in the form of the link coloured image title. Note this is only if an asset is freshly uploaded, not merely attached via the asset modal.

For example:

![Screenshot 2020-02-05 at 08 25 52](https://user-images.githubusercontent.com/12031196/73823935-3334a500-47f1-11ea-9f03-052a9b2bd231.png)

After saving the entry, the link is returned to plain text:

![Screenshot 2020-02-05 at 08 26 12](https://user-images.githubusercontent.com/12031196/73824096-7858d700-47f1-11ea-9eb2-ff27491b6e37.png)

Intentional or not, the fact the asset text is linked is super useful. It negates the need to install an inline asset downloading plugin as clients can simply click the link and download the asset from the resulting page.

### Steps to reproduce

1. Upload an asset
2. Notice the blue linked text
3. Save entry
4. Notice the linked text is gone

### Additional info

- Craft version: 3.4.3

**Comment by brandonkelly** [comment]
I’m not able to reproduce that. Looks like “Hero” may be a Super Table field – can you make sure that is up-to-date? Looks like there have been a few recent 3.4 bugfix releases – https://github.com/verbb/super-table/blob/craft-3/CHANGELOG.md

**Comment by alexjcollins** [comment]
Nothing to do with SuperTable as far as I can see.

https://youtu.be/mvDl01wECt0

If you would be open to keep the link as a feature, it would be appreciated as it makes the attached state infinitely more useful...

**Comment by brandonkelly** [comment]
Ah, I missed that this happens when you drag-upload the file. I’m able to reproduce when I do that.

> If you would be open to keep the link as a feature, it would be appreciated as it makes the attached state infinitely more useful...

The gist of that suggestion is covered by #1057. Just put it on the 3.5 list.

**Comment by brandonkelly** [comment]
Craft 3.4.4 is out now with that fix.

**Comment by alexjcollins** [comment]
Cool, thanks
