### ISSUE TITLE
Collapsing a matrix block makes it render wider than the viewport in Firefox

### ISSUE THREAD

**Issue by mtnorthrop** [craftcms/cms#5586]
### Description
When you collapse a matrix block, the `.matrixblock > .titlebar > .preview` element stretches to contain all the preview content on a single line. It does not hide the overflow nor keep its original width.

This stretches the containing `#main-content` element, and pushes the `#details-container` element off the screen to the right.

I have only seen this behavior in Firefox. When I collapse matrix blocks in Chrome, everything works correctly and as expected.

I started seeing this bug after the Craft 3.4 upgrade. I've tested collapsing matrix blocks on an older version (Craft 3.3.18.2) and am not seeing this problem.

This seems to be the same issue as was reported in #4987.

### Steps to reproduce

1. Create an entry with a matrix block containing a multi-line text field.
2. Enter long text into the multi-line text field
3. Collapse the matrix block in Firefox

### Additional info

- Craft version: 3.4.3

**Comment by brandonkelly** [comment]
Thanks for reporting! This is the same underlying issue as #5574, which has been fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.4 is out now with that fix.
