### ISSUE TITLE
GraphQL unfinished migration after 3.4.3 upgrade

### ISSUE THREAD

**Issue by wbrowar** [craftcms/cms#5588]
### Description

I've caught this on two sites now, where after upgrading to 3.4.0+ the GraphQL CP page throws and exception, stating "Changes to the project config are not possible while in read-only mode." The first site was coming from the beta, but the second was from a version of 3.3.

Both sites are using Project Config files and they both run `./craft migrate/all` and `./craft project-config/sync` during deployment.

During the upgrade’s migration, this error can be found in the `console.log` file:
```
[-][-][-][warning][craft\db\mysql\Schema::releaseSavepoint] Tried to release a savepoint, but it does not exist: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT LEVEL1 does not exist
The SQL being executed was: RELEASE SAVEPOINT LEVEL1
```

### Steps to reproduce

1. Turn on project config
2. Create a GraphQL Schema
3. Upgrade to 3.4.3
4. Click on GraphQL CP nav link

### Additional info

- Craft version: 3.4.3
- PHP version: 7.2.27
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

Admin Bar	3.1.8.1
Beam	2.1.5
Blitz	3.2.0
Content Stats	2.1.1
CP Field Inspect	1.0.7
Dumper	2.0.0
Element API	2.6.0
Guide	2.1.3.3
ImageOptimize	1.6.8
Imager	v2.3.1
Image Resizer	2.0.6
Inventory	2.0.3
Minify	1.2.9
Preparse Field	v1.1.0
Redactor	2.5.0
SEO	3.2.41
Smart Map	3.2.2.1
Store Hours	2.1.1.1
Super Table	2.4.4
Table Maker	2.0.1
Typed link field	1.0.19
Typogrify	1.1.18
URL Redirects	3.1.33

**Comment by brandonkelly** [comment]
Did you pull a recent backup from production before updating locally, per the warning in [changelog](https://github.com/craftcms/cms/blob/master/CHANGELOG-v3.md#340---2020-01-28)?

> {warning} If `useProjectConfigFile` is enabled and you are using the GraphQL API, restore a fresh database backup from your production environment before updating your development environment. Otherwise you may lose your GraphQL schema data when updating production.

**Comment by brandonkelly** [comment]
Are you able to find the `Changes to the project config are not possible while in read-only mode` error in your logs? Can you post the stack trace that led to it?

**Comment by wbrowar** [comment]
Sure thing:

```
2020-02-03 09:52:57 [-][1][...][error][yii\base\NotSupportedException] yii\base\NotSupportedException: Changes to the project config are not possible while in read-only mode. in /vendor/craftcms/cms/src/services/ProjectConfig.php:437
Stack trace:
#0 /vendor/craftcms/cms/src/services/Gql.php(711): craft\services\ProjectConfig->set('graphql.schemas...', Array, 'Save GraphQL sc...')
#1 /vendor/craftcms/cms/src/services/Gql.php(1248): craft\services\Gql->saveSchema(Object(craft\models\GqlSchema))
#2 /vendor/craftcms/cms/src/services/Gql.php(476): craft\services\Gql->_createPublicSchema(2)
#3 /vendor/craftcms/cms/src/controllers/GraphqlController.php(202): craft\services\Gql->getPublicSchema()
#4 [internal function]: craft\controllers\GraphqlController->actionGraphiql()
#5 /vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#7 /vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('graphiql', Array)
#8 /vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('graphiql', Array)
#9 /vendor/craftcms/cms/src/web/Application.php(290): yii\base\Module->runAction('graphql/graphiq...', Array)
#10 /vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('graphql/graphiq...', Array)
#11 /vendor/craftcms/cms/src/web/Application.php(275): yii\web\Application->handleRequest(Object(craft\web\Request))
#12 /vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#13 /web/index.php(21): yii\base\Application->run()
#14 {main}
```

I was able to get these sites working again by doing the following:

1. Pulled the upgraded production DB down to a local install (which has `allowAdminChanges` set to `true`
1. Deleted the old GraphQL token tied to the existing schema (the GraphQL schema was no longer listed)
1. Create a new GraphQL schema on the local install
1. Exported the local DB and imported it back into production
1. Pushed project.yaml up
1. Create a new token using the new schema setting

Hope this helps,
Will

**Comment by brandonkelly** [comment]
Aha, thanks. Issue is that various parts of Craft were assuming it still had free reign to create a public schema if one didn’t exist yet, without worrying about whether `allowAdminChanges` was enabled. It’s a side effect of us pulling schemas into the project config in 3.4, where now `allowAdminChanges` actually matter.

I’ve just fixed this for the next release by making the code a bit more defensive for when `allowAdminChanges` is disabled. In that case a public schema just won’t be created at all, so you’ll have to go create it on a local environment where `allowAdminChanges` is still enabled, and then push it to production.

**Comment by wbrowar** [comment]
Awesome. Thank you, Brandon!

**Comment by brandonkelly** [comment]
Craft 3.4.5 is out now with that fix.
