### ISSUE TITLE
Matrix block buttons display glitch

### ISSUE THREAD

**Issue by nilsenpaul** [craftcms/cms#5591]
### Description
Please see attached gif. When using a matrix field with a lot of block, the 'add a matrix block' button doesn't get displayed correctly. Then, after saving (cmd-s) the page, the entire page is positioned incorrectly.

![Craft_CP_layout-fu](https://user-images.githubusercontent.com/6794819/73852629-d0163300-482f-11ea-8bc8-53723a00b197.gif)

### Steps to reproduce

1. Create a bunch of matrix blocks for a field
2. Put 'm on tab 2 (<-- not sure about this?)

### Additional info

- Craft version: Craft Pro 3.4.3
- Browser: Firefox 72.0.2

**Comment by brandonkelly** [comment]
Thanks for reporting that! Suspect this is the same underlying issue as #5574, which is fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.4 is out now with that fix.
