### ISSUE TITLE
[3.4] Date/Time fields don't display the relevant information in the list entries view

### ISSUE THREAD

**Issue by jamiewade** [craftcms/cms#5603]
### Description
If you add a Date/Time field to an entry and give it a value, the field will always show the time when it has been added to the list entries table:

![screenshot](https://user-images.githubusercontent.com/6672331/73937668-753b1500-48dd-11ea-8427-e4ff52d73d31.jpg)

This particular Date/Time field is restricted to date input, so it will never have a time value, but Craft is displaying the time rather than the date.

### Additional info

- Craft version: Craft CMS 3.4.4
- PHP version: 7.3.8
- Database driver & version: MySQL 5.7.24

**Comment by jamiewade** [comment]
I think this might have been an issue with upgrading from `3.3` to `3.4`.

The entries were unsaved _after_ we migrated from `3.4`, and the screenshot above is what I saw to begin with. Now I have gone through and edited the values of those fields and re-saved the entries, everything is showing fine on the list entries page.

**Comment by brandonkelly** [comment]
Do you have a database backup from before you updated to 3.4? If so can you please send that and your `composer.json` and `composer.lock` files over to support@craftcms.com?

**Comment by jamiewade** [comment]
Unfortunately I don't. I just quickly set-up a playground site running `3.3`, added a Date field to some entries, gave them values, updated that site to `3.4`, and (un)fortunately everything is working as expected:

![Screenshot_2020-02-06 Entries - Craft CMS Playground(2)](https://user-images.githubusercontent.com/6672331/73951728-e4bcfe80-48f5-11ea-8cb0-22bddf04611f.png)

So I'm not sure what happened last time round. Obviously _something_ did go wrong, but I can't seem to replicate it again.

**Comment by brandonkelly** [comment]
Alright, well let me know if it crops up again.
