### ISSUE TITLE
./craft restore does not empty existing database before importing the database mentioned in the command

### ISSUE THREAD

**Issue by architchandra** [craftcms/cms#5606]
### Description
When I run `./craft restore path/to/database`, I get errors referring to tables that already exist in the existing database. Since the purpose of importing a new database almost always is to completely replace the existing database, it seems logical that the `restore` command would be doing that. The request, thus, it to make that standard behavior of the `restore` command or at least add an option that lets one do it.

### Steps to reproduce
I noticed the problem properly when trying to downgrade from Craft version `3.3.7` to `3.2.10`.
1. Have Craft `3.2.10` set up and take a database backup.
2. Downgrade to Craft `3.2.10`.
3. Run `composer install`
4. Import the database from step 1.

### Additional info
Example error thrown: `Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'gqlschemas' already exists`

- Craft version: 3.2.10
- PHP version: 7.2.23
- Database driver & version: mysql  `Ver 14.14 Distrib 5.7.28, for macos10.14 (x86_64)`
- Plugins & versions: Screenshot attached.
![Screenshot 2020-02-06 at 9 01 22 PM](https://user-images.githubusercontent.com/8830075/73951670-e00f3f00-4923-11ea-8197-2f9a9d329417.png)

**Comment by brandonkelly** [comment]
This is actually a migration bug – the migration should have been more defensive by dropping the table if it already existed, before attempting to (re-)create it. And that’s exactly what it does as of Craft 3.3.15+, per 0e53c41f102b951367bfe198146dc66286806aab.

**Comment by architchandra** [comment]
Sure that fixes the issue with this particular migration, but then philosophically it feels wrong that the DB restore command does not bring the DB to the exact state as in the file being restored from. Perhaps, we should at least have an option in the `restore` command to drop all tables instead of just the ones that already exist.

**Comment by brandonkelly** [comment]
Craft won’t do that because there’s a potential that could remove DB tables you didn’t intend it to, perhaps completely unrelated to your Craft installation.

As long as we remember to call `dropTableIfExists()` before creating new tables in migrations (which we do now), then it’s not a problem.
