### ISSUE TITLE
[Question] Graphql performance

### ISSUE THREAD

**Issue by stephanedemotte** [craftcms/cms#5607]
Hello,

How we can optimise our craft setup to reduce the first time graphql load ?

Each new save in the backend, graphql cache was deleted and the first render of our website become very slow.

Cached -------
<img width="651" alt="Screen Shot 2020-02-06 at 10 56 58 AM" src="https://user-images.githubusercontent.com/2158130/73954433-d2c86500-48cf-11ea-96d8-16b9c67be250.png">

After a save
<img width="652" alt="Screen Shot 2020-02-06 at 10 57 15 AM" src="https://user-images.githubusercontent.com/2158130/73954461-da880980-48cf-11ea-87a5-61cd38bb37bb.png">

We miss something ? we have ~ 70 fields, and we will add more.
We have to reduce the amount of fields ?

thanks !

**Comment by andris-sevcenko** [comment]
@stephanedemotte is this on Craft 3.4.x?

**Comment by brandonkelly** [comment]
We just released Craft 3.4.5, which drastically improves GraphQL API performance.

**Comment by stephanedemotte** [comment]
whouuaaa thanks !
