### ISSUE TITLE
Reduce padding on the left side of CP fields in Craft 3.4 

### ISSUE THREAD

**Issue by simonkuran** [craftcms/cms#5608]
Very minor UI nitpick incoming. In my opinion in Craft 3.4 the padding on the left side of CP fields is too large. For the past week I've often thought that there's a space character at the start of my field name.

Craft 3.4:
<img width="249" alt="Craft 3-4" src="https://user-images.githubusercontent.com/41410727/73966858-70299600-48dc-11ea-92f2-ceb40b5a5995.png">

For comparison, Craft before 3.4:
<img width="288" alt="Craft pre 3-4" src="https://user-images.githubusercontent.com/41410727/73966883-7d468500-48dc-11ea-9564-4cf7c6cb82e2.png">

I'm talking a few pixels here and I thought I'd get used to it, but I'm still doing a double take multiple times a day.

**Comment by brandonkelly** [comment]
Agree that is a bit excessive! Just shaved 4px off the horizontal padding for the next release.

**Comment by narration-sd** [comment]
I think you should past that 4px answer up on the wall someplace around 
'Pixel&Tonic House' (British way of naming offices), with some title 
like 'Degree of Service we offer from P&T' :)

**Comment by simonkuran** [comment]
Wow, that was fast! Thanks @brandonkelly!

**Comment by brandonkelly** [comment]
Welcome :) And 3.4.5 is out now with that change.
