### ISSUE TITLE
Order Fields: Matrix field missing top padding in CP

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/cms#5609]
### Description

A real small point and not much of a deal breaker...when you view an order and it contains a matrix field, it doesn't appear to have any top padding. The first field sits very close to the top. If you edit the order, everything looks great.

**Title field almost touching the top of the delegates box**
![Screen Shot 2020-02-04 at 12 42 22](https://user-images.githubusercontent.com/2373940/73742051-d7641080-474b-11ea-9a09-b457ff0fc8d0.png)

### Steps to reproduce

1. Add a matrix field to your Commerce Order Fields
2. View an order and notice how the first field sits close to the top

### Additional info

- Craft version: 3.4.2
- PHP version: 7.3.13
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Commerce 3.0.5

**Comment by brandonkelly** [comment]
Just got this fixed for the next Craft 3.4 release.

**Comment by brandonkelly** [comment]
Craft 3.4.5 is out now with that fix.
