### ISSUE TITLE
Table field with multi-line text column crops to 1 line in the CP

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/cms#5611]
### Description

I am using a table field to store who is booked on to a conference.

One of the fields in the table is a multi-line text field called "Notes". If this field contains more than 1 line, the content is cropped with no way to access the "complete" content unless the order is edited and you have the permissions todo so.

It would be great if the row height was defined by the content inside this field.

I appreciate this may be by design or i'm using the wrong field type for this data.

**Initial View (Content in the Notes column is cropped to 1 line)**
![Screen Shot 2020-02-04 at 12 09 58](https://user-images.githubusercontent.com/2373940/73739858-54d95200-4747-11ea-8c65-d0edabc09ef9.png)

**Edit Order View**
![Screen Shot 2020-02-04 at 12 12 04](https://user-images.githubusercontent.com/2373940/73740014-a2ee5580-4747-11ea-9796-9d17f043924b.png)

### Steps to reproduce

1. Create a table field and add a multi-line text field column called "Notes"
3. Add your table field to `Order Fields`
4. Edit an existing order and add lots of text to the "Notes" field
5. Update order
6. Notice the content is cropped to 1 line

### Additional info

- Craft version: 3.4.2
- PHP version: 7.3.13
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Commerce 3.0.5

**Comment by brandonkelly** [comment]
Just got this fixed for the next Craft 3.4 release.

**Comment by brandonkelly** [comment]
Craft 3.4.5 is out now with that fix.

**Comment by jonleverrier** [comment]
@brandonkelly Looks like something has gone astray with this update.

Multi-line content is no longer cropped, but now the table field is wider than usual:

![Screen Shot 2020-02-09 at 13 31 27](https://user-images.githubusercontent.com/2373940/74102094-a7987c80-4b40-11ea-8d99-54bc4b9d9cbb.png)

I've tried clearing my cache and running `./craft clear-caches/all` but the problem persists.

**Comment by jonleverrier** [comment]
Just to note - this only seems to happen in Commerce > Orders on initial view. When you edit an order (or entry) the table field displays fine.

**Comment by brandonkelly** [comment]
@jonleverrier Thanks. I’m seeing it on entry revisions as well.

**Comment by brandonkelly** [comment]
All fixed now for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.6 is out now with this fix.
