### ISSUE TITLE
SuperTable field cannot get added to Global set

### ISSUE THREAD

**Issue by xavianaxw** [craftcms/cms#5613]
### Description

I have a SuperTable field to add a CTA block to my globals but I keep getting a "Couldn't save global set" error.

Here's the setup of my field.

```
heading - PlainText
page - Entries
```

### Steps to reproduce

1. Create a field with the setup as mentioned above
2. Create a global set
3. Add SuperTable field to the global set
4. Click save

### Additional info

- Plugin version: `2.3.3`
- Craft version: Craft Pro `3.3.20.1`
- PHP version: `7.2.26`
- Database driver & version: PostgreSQL `11.6`
- Plugins & versions: SuperTable `2.3.3`

**Comment by brandonkelly** [comment]
Are you able to make other changes to the global set?

**Comment by xavianaxw** [comment]
Hmm I tried saving it without making any changes but I can give it a try on Monday and let you know again

**Comment by xavianaxw** [comment]
That's a yikes from me. I edited another global set and it worked. Gonna close this for now.

**Comment by brandonkelly** [comment]
Alright, may be a bug with Super Table then.
