### ISSUE TITLE
URL field validation fails on surrounding whitespace

### ISSUE THREAD

**Issue by rungta** [craftcms/cms#5614]
### Description

URL fields complain about invalid URLs if the entered value has any extra whitespace characters before or after the URL. It is not unusual for authors to leave an extra space or two while entering values in fields, and I feel it would be better AX if the URL field cleverly trimmed surrounding whitespace before saving, or before validation.

### Steps to reproduce

1. Add a URL field to an Entry Type
2. Create a new Entry with that Entry Type
3. Enter <code>https://craftcms.com&nbsp;</code> into the URL field
4. Save the entry

### Additional info

- Craft version: 3.4.4
- PHP version: 7.1.19

**Comment by rungta** [comment]
Observed the same behavior with the Email field.

**Comment by brandonkelly** [comment]
Good call. Just released 3.4.5, which now trims whitespace from URL/Email field values, as well as textual Table field cells.
