### ISSUE TITLE
Vertical alignment of fields inside the table field

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/cms#5615]
### Description

A small point... Would you consider vertically aligning all field content in the table field to the top?

When a `multi-line text`, `single line text` or `number` field is in play, it makes it harder to scan the data in the table because of the different vertical alignments:

![Screen Shot 2020-02-04 at 12 12 04](https://user-images.githubusercontent.com/2373940/73740014-a2ee5580-4747-11ea-9796-9d17f043924b.png)

**Table field**
|Field type  |Vertically aligned   |
|---|---|
|Checkbox   | Center  |
|Colour  | Center  |
|Date  | Center  |
|Dropdown   |Center   |
|Email   |Center   |
|Lightswitch   |Center   |
|Multi-line text   |Top   |
|Number   |Top   |
|Single line text   |Top   |
|Time   |Center   |
|URL   |Center   |

Apologies - I should of mentioned this in https://github.com/craftcms/cms/issues/5611

### Steps to reproduce

1. Create a table field
2. Add an `email` and `multi-line` text field
3. Assign field to an entry
4. Add lots of content to the `multi-line` field and complete the `email` field
5. Notice how the `email` field is vertically aligned to the center, not to the top

### Additional info

- Craft version: 3.4.2
- PHP version: 7.3.13
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Commerce 3.0.5

**Comment by brandonkelly** [comment]
Good call. Just made that change for the next release.

![A Table field with a lot of column types, all vertically top-aligned](https://user-images.githubusercontent.com/47792/74058075-1687a100-499a-11ea-98c3-464859207760.png)

> Apologies - I should of mentioned this in #5611

No apology needed – this is a separate issue, so better reported separately :)

**Comment by brandonkelly** [comment]
3.4.5 is out now with that change.
