### ISSUE TITLE
[3.4] Live Preview target selector occludes Iframe in Chrome

### ISSUE THREAD

**Issue by michaelhue** [craftcms/cms#5616]
### Description

In Chrome the preview target header in Live Preview is positioned on top of the Iframe, occluding parts of the page. Firefox shows the target header correctly above the Iframe.

#### Chrome Screenshot
<img width="1172" alt="Bildschirmfoto 2020-02-07 um 10 57 25" src="https://user-images.githubusercontent.com/31861/74020314-336ba680-4991-11ea-8ef5-b26612260bf8.png">

#### Firefox Screenshot
<img width="1177" alt="Bildschirmfoto 2020-02-07 um 10 57 24" src="https://user-images.githubusercontent.com/31861/74020276-1f27a980-4991-11ea-8e6e-3fb8fece921d.png">

### Steps to reproduce

1. Create section with two or more preview targets
2. Open Live Preview in Chrome 

### Additional info

- Craft version: 3.4.4.1
- Chrome version: 80.0.3987.87

**Comment by michaelhue** [comment]
While on the subject: does the preview target selector really need to take up that much space? Maybe it could be moved to the left column, next to the "Close Preview" button?

**Comment by brandonkelly** [comment]
This is already covered by #5547.

> While on the subject: does the preview target selector really need to take up that much space? Maybe it could be moved to the left column, next to the "Close Preview" button?

Can you post a separate issue suggesting that?
