### ISSUE TITLE
Exporting Users in Dashboard results in 400/500 error (possibly CSRF)

### ISSUE THREAD

**Issue by billythekid** [craftcms/cms#5617]
### Description
Trying to export Users in the control panel is giving me an unable to verify data submission error

### Steps to reproduce

1. Go to users
2. Hit the export button
3. choose a format and hit the export button in the HUD
4. Observe the red flash message and open developer tools to inspect the network traffic and see the CSRF issue

### Additional info

- Craft version: 3.4.4.1
- PHP version: 7.4.2 & 7.3.10
- Database driver & version: MySQL 8.0.18 and MySQL 5.5.5
- Plugins & versions: 
Amazon S3 	1.2.7
Bugsnag 	2.0.6
Control Panel JS 	2.2.0
Dumper 	2.0.0
Element API 	2.6.0
Mailgun 	1.4.2
Minify 	1.2.9
Mix 	1.5.2
Navigation 	1.3.3
Redactor 	2.5.0
SEO 	3.6.3
Super Table 	2.4.4
Video Embedder 	1.1.4

**Comment by brandonkelly** [comment]
Yep you’re right. Didn’t realize I had been testing with CSRF protection disabled. Fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 3.4.5 is out now with that fix.
