### ISSUE TITLE
[3.4] Accessing matrix blocks from plugin results in empty array

### ISSUE THREAD

**Issue by Stalex89** [craftcms/cms#5618]
### Description

After updating Craft from 3.3.15 to 3.4.2, I have an issue with retrieving matrix blocks in plugin.

In my plugin, I'm using `$entry-><FieldHandle>->all()` to retrieve an array of MatrixBlock elements, 
and it was working prior to the update.

However, those blocks are accessible through the templating: 
`{% dd entry.<FieldHandle.all() %}` returns me an array of MatrixBlock elements

All other fields of the entry except matrix fields are completely accessible and i can retrieve their values.

### Steps to reproduce

1. Install Craft version 3.3.15
2. Create Matrix field with blocks
3. Create Section containing this matrix field
4. Create Plugin which performs action after saving entry:
`Event::on(
    SaveController::class,
    SaveController::EVENT_AFTER_SAVE_ENTRY,
    function(SaveEvent $e) {
        $matrix = $e->entry->matrixHandle->all();
        var_dump($matrix);
        die();
}`
5. Update Craft to version 3.4.2
6. Watch for the dumped value

### Additional info

- Craft version: 3.4.2
- PHP version: 7.3.12
- Database driver & version: MySQL 5.7.28
- Plugins & versions: 
Control Panel CSS 2.2.0
Element API 2.6.0
Field Manager 2.1.1
Guest Entries 2.2.4
Navigation 1.3.2
Redactor 2.5.0
Redirects 3.1.33
Retcon 2.0.12
SEO 3.2.41
Super Table 2.4.4

**Comment by brandonkelly** [comment]
Still working on my end. And behind the scenes, `$entry->matrixField->all()` and `entry.matrixField.all()` do the exact same thing.

You must be doing _something_ in PHP that’s affecting the results. Perhaps you are setting a param on the MatrixBlockQuery returned by `$entry->matrixFieldHandle` before you later call `$entry->matrixFieldHandle->all()`?

**Comment by Stalex89** [comment]
I have double checked the code and created a fresh version of craft 3.4 with fresh database, and still I have this issue. 
I've uploaded the example code with the issue along with the database, which is accessible by this link: 
[https://github.com/Stalex89/craft-cms-matrix-issue-example](url)
Also attaching screenshots of the issue:
![Screenshot 2020-02-10 at 15 03 57](https://user-images.githubusercontent.com/23526237/74156474-af2a5500-4c16-11ea-9154-53cec7ffe73e.png)
![Screenshot 2020-02-10 at 15 04 18](https://user-images.githubusercontent.com/23526237/74156482-b3ef0900-4c16-11ea-8602-80ee3133b505.png)

**Comment by brandonkelly** [comment]
Do you have a corresponding database backup to go with those files?

**Comment by brandonkelly** [comment]
And once installed, what should I do to reproduce?

**Comment by Stalex89** [comment]
@brandonkelly  I have uploaded a database to the repository (database.zip), just forgot to mention it in readme file.  There is an instruction in repository readme file how to set up everything. 

Once installed: 
1) Open main page, along with chrome devtools
2) type any number and then click on submit button
3) Look for dumped value in response of submitted request (I use the test plugin to dump saved entry)
The dumped value returns  `array(0) {}` in response , but should return an array of MatrixBlock (the issue is shown on the screenshot 1)

4) If you go to Control Panel and preview the saved entry using preview, it shows the array of MatrixBlock (screenshot 2)

The problem is that the same matrix field doesn't return the array of MatrixBlocks in php in backend plugin, while there is no problem with getting MatrixBlocks in templating

**Comment by brandonkelly** [comment]
Thanks! Was able to reproduce with that, and just got this fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#7e45f8f965fb09f0938f72657b9f479471d589f3 as 3.4.5",
  "...": "..."
}
```

Then run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.4.6 is out now with this fix.

**Comment by boboldehampsink** [comment]
@brandonkelly this results in errors on multiple of my sites. It seems to be doing COUNT queries on elements that don't have matrix fields on them (so existing element without matrix) resulting in the following error:

```
2020-02-19 10:46:50 [-][-][-][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Setting unknown property: craft\elements\MatrixBlock::count in /app/user/vendor/yiisoft/yii2/base/Component.php:209
web_1         | Stack trace:
web_1         | #0 /app/user/vendor/craftcms/cms/src/base/Element.php(1116): yii\base\Component->__set('count', 0)
web_1         | #1 /app/user/vendor/yiisoft/yii2/BaseYii.php(558): craft\base\Element->__set('count', 0)
web_1         | #2 /app/user/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(craft\elements\MatrixBlock), Array)
web_1         | #3 /app/user/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1790): yii\base\BaseObject->__construct(Array)
web_1         | #4 /app/user/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2798): craft\elements\db\ElementQuery->createElement(Array)
web_1         | #5 /app/user/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1442): craft\elements\db\ElementQuery->_createElements(Array)
web_1         | #6 /app/user/vendor/yiisoft/yii2/db/Query.php(238): craft\elements\db\ElementQuery->populate(Array)
web_1         | #7 /app/user/vendor/craftcms/cms/src/db/Query.php(152): yii\db\Query->all(NULL)
web_1         | #8 /app/user/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1471): craft\db\Query->all(NULL)
web_1         | #9 /app/user/vendor/craftcms/cms/src/services/Matrix.php(882): craft\elements\db\ElementQuery->all()
web_1         | #10 /app/user/vendor/craftcms/cms/src/fields/Matrix.php(944): craft\services\Matrix->duplicateBlocks(Object(craft\fields\Matrix), Object(craft\elements\Entry), Object(craft\elements\Entry), true)
web_1         | #11 /app/user/vendor/craftcms/cms/src/base/Element.php(2547): craft\fields\Matrix->afterElementPropagate(Object(craft\elements\Entry), true)
web_1         | #12 /app/user/vendor/craftcms/cms/src/elements/Entry.php(1274): craft\base\Element->afterPropagate(true)
web_1         | #13 /app/user/vendor/craftcms/cms/src/services/Elements.php(851): craft\elements\Entry->afterPropagate(true)
web_1         | #14 /app/user/vendor/craftcms/cms/src/services/Revisions.php(160): craft\services\Elements->duplicateElement(Object(craft\elements\Entry), Array)
web_1         | #15 /app/user/vendor/craftcms/cms/src/elements/Entry.php(1278): craft\services\Revisions->createRevision(Object(craft\elements\Entry), NULL, NULL)
web_1         | #16 /app/user/vendor/craftcms/cms/src/services/Elements.php(2143): craft\elements\Entry->afterPropagate(true)
web_1         | #17 /app/user/vendor/craftcms/cms/src/services/Elements.php(530): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false, true)
web_1         | #18 /app/user/vendor/craftcms/cms/src/test/fixtures/elements/ElementFixture.php(111): craft\services\Elements->saveElement(Object(craft\elements\Entry))
web_1         | #19 /app/user/vendor/yiisoft/yii2/test/FixtureTrait.php(96): craft\test\fixtures\elements\ElementFixture->load()
web_1         | #20 /app/user/vendor/yiisoft/yii2/console/controllers/FixtureController.php(159): yii\console\controllers\FixtureController->loadFixtures(Array)
web_1         | #21 [internal function]: yii\console\controllers\FixtureController->actionLoad(Array)
web_1         | #22 /app/user/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
web_1         | #23 /app/user/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
web_1         | #24 /app/user/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('load', Array)
web_1         | #25 /app/user/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('load', Array)
web_1         | #26 /app/user/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('fixture/load', Array)
web_1         | #27 /app/user/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('fixture/load', Array)
web_1         | #28 /app/user/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('fixture/load', Array)
web_1         | #29 /app/user/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
web_1         | #30 /app/user/craft(23): yii\base\Application->run()
web_1         | #31 {main}
```

Commenting these added lines fixes the errors and returns everything to normal.

**Comment by brandonkelly** [comment]
@boboldehampsink Do you have anything in your code that is manually setting `select('count(*)')` or `select(['count(*)'])`, or something like that, on a Matrix block query? Looks like maybe that is being left in there.

**Comment by boboldehampsink** [comment]
@brandonkelly nope. I saw it referenced the Typed Link plugin but that doesn't do any counts either. It occurs in multiple different projects and it is fixed by commenting your added lines.

**Comment by brandonkelly** [comment]
@boboldehampsink Yeah the nature of this bug could likely be that the culprit isn’t going to be obvious from the stack trace. Can you send a database backup and your `composer.json` and `composer.lock` files over to support@craftcms.com, along with steps to reproduce?

**Comment by rtrudel** [comment]
I also experiment the problem. I just sent you an email to support@craftcms.com about this.

**Comment by rtrudel** [comment]
This is the stack trace when using a custom controler from a custom module:

```yii\base\UnknownPropertyException: Setting unknown property: craft\elements\MatrixBlock::COUNT(*) in /home/user/path/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /home/user/path/vendor/craftcms/cms/src/base/Element.php(1116): yii\base\Component->__set('COUNT(*)', '0')
#1 /home/user/path/vendor/yiisoft/yii2/BaseYii.php(558): craft\base\Element->__set('COUNT(*)', '0')
#2 /home/user/path/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(craft\elements\MatrixBlock), Array)
#3 /home/user/path/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1790): yii\base\BaseObject->__construct(Array)
#4 /home/user/path/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2798): craft\elements\db\ElementQuery->createElement(Array)
#5 /home/user/path/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1442): craft\elements\db\ElementQuery->_createElements(Array)
#6 /home/user/path/vendor/yiisoft/yii2/db/Query.php(238): craft\elements\db\ElementQuery->populate(Array)
#7 /home/user/path/vendor/craftcms/cms/src/db/Query.php(152): yii\db\Query->all(NULL)
#8 /home/user/path/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1471): craft\db\Query->all(NULL)
#9 /home/user/path/vendor/craftcms/cms/src/services/Matrix.php(882): craft\elements\db\ElementQuery->all()
#10 /home/user/path/vendor/craftcms/cms/src/fields/Matrix.php(944): craft\services\Matrix->duplicateBlocks(Object(craft\fields\Matrix), Object(craft\elements\Entry), Object(craft\elements\Entry), true)
#11 /home/user/path/vendor/craftcms/cms/src/base/Element.php(2547): craft\fields\Matrix->afterElementPropagate(Object(craft\elements\Entry), true)
#12 /home/user/path/vendor/craftcms/cms/src/elements/Entry.php(1274): craft\base\Element->afterPropagate(true)
#13 /home/user/path/vendor/craftcms/cms/src/services/Elements.php(851): craft\elements\Entry->afterPropagate(true)
#14 /home/user/path/vendor/craftcms/cms/src/services/Revisions.php(160): craft\services\Elements->duplicateElement(Object(craft\elements\Entry), Array)
#15 /home/user/path/vendor/craftcms/cms/src/elements/Entry.php(1278): craft\services\Revisions->createRevision(Object(craft\elements\Entry), '1', NULL)
#16 /home/user/path/vendor/craftcms/cms/src/services/Elements.php(2143): craft\elements\Entry->afterPropagate(true)
#17 /home/user/path/vendor/craftcms/cms/src/services/Elements.php(530): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, true, true)
#18 /home/user/path/modules/sitemodule/src/controllers/AgendaController.php(678): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#19 [internal function]: modules\sitemodule\controllers\AgendaController->actionSetPresence()
#20 /home/user/path/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#21 /home/user/path/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#22 /home/user/path/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('set-presence', Array)
#23 /home/user/path/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('set-presence', Array)
#24 /home/user/path/vendor/craftcms/cms/src/web/Application.php(290): yii\base\Module->runAction('site-module/age...', Array)
#25 /home/user/path/vendor/craftcms/cms/src/web/Application.php(558): craft\web\Application->runAction('site-module/age...', Array)
#26 /home/user/path/vendor/craftcms/cms/src/web/Application.php(269): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#27 /home/user/path/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#28 /home/user/path/web/index.php(23): yii\base\Application->run()
#29 {main}
```

This seems to occur only when creating a new entry having a matrix field. Even if the field is not filled along `setFieldValues`.

**Comment by rtrudel** [comment]
Can it be related to this? https://github.com/craftcms/cms/blob/0487d37125d78845ed52855c33697757e069ac2b/src/controllers/ElementIndexesController.php#L152-L166

**Comment by rtrudel** [comment]
@boboldehampsink can you tell me which lines in which file you commented to make it works? 

As my Craft site is an intranet, all my suers can't create new entries and I did not got any news from support yet, so I'm looking for a fast patch/workaround waiting for a real patch.

Thank you!

**Comment by boboldehampsink** [comment]
@rtrudel remove these lines: https://github.com/craftcms/cms/commit/7e45f8f965fb09f0938f72657b9f479471d589f3

**Comment by boboldehampsink** [comment]
> Can it be related to this?
> 
> https://github.com/craftcms/cms/blob/0487d37125d78845ed52855c33697757e069ac2b/src/controllers/ElementIndexesController.php#L152-L166

no

**Comment by rtrudel** [comment]
Oh yes! Thanks a lot. This fixes all the small issues my clients are reporting with features.
You saved my day!

**Comment by brandonkelly** [comment]
Technically this ended up being due to a Yii bug, which I’ve PR’d a fix for (yiisoft/yii2#17881), but I’ve also applied the same fix directly to Craft for the next release, so we’re not waiting around for Yii 2.0.33 to drop.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#a49de72afcf18349617bff20b82c7c197218af42 as 3.4.6",
  "...": "..."
}
```

Then run `composer update`.

**Comment by rtrudel** [comment]
Thanks for the explanation. This works fine now.

**Comment by boboldehampsink** [comment]
Thanks @brandonkelly, must've been a hard one to debug

**Comment by brandonkelly** [comment]
Craft 3.4.7 is out now with the fix!

@boboldehampsink Yeah it was a tricky one :)
