### ISSUE TITLE
Exporting Entries - 400 Server Error

### ISSUE THREAD

**Issue by michaelmolchan** [craftcms/cms#5619]
### Description

I am getting a 400 server error (Bad Request - Unable to verify your data submission) when I attempt to export an entry in the Craft admin panel. All export types / export formats give the same error. I have also tested the export feature on a Craft demo site generated at https://demo.craftcms.com/ and still receive this error.

**Note** - We rolled Craft version back to 3.4 and the feature appears to work fine.

### Steps to reproduce

1. Entries
2. Select Entry
3. Click 'Export...'
4. Select any Export Type / Format
5. Click Export

### Additional info

- Craft version: Craft Solo 3.4.4.1
- PHP version: 7.1.20
- Database driver & version: MySQL 5.7.23
- Plugins & versions: Navigation 1.3.3, Redactor 2.5.0, Super Table 2.4.4

<img width="1450" alt="Screen Shot 2020-02-07 at 12 55 52 PM" src="https://user-images.githubusercontent.com/34256915/74053318-8d786600-49a9-11ea-82ff-1719aef240b4.png">

**Comment by brandonkelly** [comment]
Thanks for reporting! This was already covered by #5617, and we just released Craft 3.4.5 with a fix :)
