### ISSUE TITLE
Parse template input as Twig/object template

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#5620]
It would be nice if, like you can with the URI format, you could input twig in the **Site Settings → Template** field for Sections, Category group, or any element sources with URLs/templates.

E.g. I could do something like: 
![Uploading Screen Shot 2020-02-07 at 3.15.45 PM.png…]()

It would cut down on the routing/template juggling in the actual twig templates, which would be nice.

**Comment by brandonkelly** [comment]
This is already requested by #5351. See my comment there on why it’s not already implemented.

**Comment by timkelty** [comment]
Thanks and sorry - I swear I searched before posting :)
