### ISSUE TITLE
The update notes for Craft 3.4 do not seem accurate

### ISSUE THREAD

**Issue by importantcoding** [craftcms/cms#5621]
### Description
In the notes for updating to craft 3.4 it says that we can no longer set custom field values directly.

> // Bad
> $entry->myTextField = 'Hello';
> 
> // Good
> $entry->setFieldValue('myTextField', 'Hello');
> 

However, in my plugin I set the values the bad way `$order->orderStatusId = 19`; and it works in craft 3.4.5. Yet, if I try to set it the good way `$order->setFieldValue('orderStatusId', 19;)`, I get this in return.

> Setting unknown property: craft\behaviors\CustomFieldBehavior::orderStatusId

Maybe I'm missing something?

### Additional info

- Craft version: 3.4.5
- PHP version: 7.2
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
I’m assuming you are referring to [craft\commerce\elements\Order::$orderStatusId](https://docs.craftcms.com/commerce/api/v3/craft-commerce-elements-order.html#orderstatusid), which is an actual property, not a custom field.
