### ISSUE TITLE
Keep getting message that add-on licenses need to be resolved even though they've been purchased.

### ISSUE THREAD

**Issue by jonlongnecker** [craftcms/cms#5623]
### Description
Just finished upgrading my whole site to Craft 3 from Craft 2. I bought several plugins locally while developing. I can see them in my Craft ID account.

But when logging in to the live server, I see a red bar across the top that says I need to resolve license issues. When I click the button it takes me to plugins without highlighting anything. I cannot see serial numbers for purchased add-ons, though.

After clicking through to the plugins page this seems to go away until the next login.

### Additional info

- Craft version: 3.4.4.1
- PHP version: 7.1
- Plugins & versions: Analytics (4.0.10), SEOMatic(3.2.42), Sprout Forms(3.8.02)

**Comment by brandonkelly** [comment]
Hey @jonlongnecker, here’s a couple things to check;

- Make sure your `config/license.key` file is the same as on your local install.
- If you have multiple web servers, make sure they all have the same `config/license.key` file as well.
- Check if you’re getting any JavaScript errors on the Settings → Plugins page.

**Comment by jonlongnecker** [comment]
Hey @brandonkelly, 

- license keys are the same on local and live and only have one web server.
- My local copy also doesn't show the serial numbers for the plugins I purchased. In fact, if I go to the Plugin Store page it shows them as trials in both local and live environments. 
- If I login to Craft ID and view the CraftCMS license, I can see both plugin licenses attached correctly.
- There is one error on the Plugins page: `[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (axios.min.map, line 0)`

**Comment by brandonkelly** [comment]
OK, does your local environment show the license key inputs on the Settings → Plugins page, for your commercial plugins?

**Comment by jonlongnecker** [comment]
Nope:
![Screenshot 2020-02-11 15 42 16](https://user-images.githubusercontent.com/2390/74286498-1f071100-4ce5-11ea-97f1-a6aaa6c9822c.png)

**Comment by brandonkelly** [comment]
Are you using Safari? Just noticed there’s a bug where plugin license key inputs aren’t showing up in Safari for some reason. Looking into that.

**Comment by jonlongnecker** [comment]
Yeah I'm on Safari. I can see the license key inputs in Chrome, but they still say I need to buy them...

**Comment by brandonkelly** [comment]
This should be fixed now (no Craft update needed). Apparently Safari doesn’t accept `*` as a value for the `Access-Control-Expose-Headers` CORS header.

You will just need to reenter your plugin license keys in the Settings → Plugins page, which you can get from https://id.craftcms.com.
