### ISSUE TITLE
GraphQL entry queries for sibling retrieval

### ISSUE THREAD

**Issue by roelvanhintum** [craftcms/cms#5627]
It looks like GraphQL entry queries are missing search parameters for sibling retrieval like:
- positionedBefore
- positionedAfter
- nextSiblingOf
- prevSiblingOf

- Craft version: 3.4.5

**Comment by andris-sevcenko** [comment]
Thanks for reporting that! This has been fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.6 is out now  with this change.
