### ISSUE TITLE
Bad request in IE11 when accessing the admin

### ISSUE THREAD

**Issue by petertindemans** [craftcms/cms#5628]
### Description

We experienced that the admin isn't accessible anymore in IE11. It will how an error right after the login (check out the screenshot).

We did a clean install for testing, no additional extensions, same problem.

### Steps to reproduce

1. Clean install Craft CMS 3.4.5
2. Login to the admin (login will show, login and a error is shown)

### Additional info

- Craft version: Craft CMS 3.4.5
- PHP version: 7.2.27
- Database driver & version: MySQL 5.6.45
- Plugins & versions: None, testen with clean install

Screenshot:
![screenshot](https://user-images.githubusercontent.com/19586163/74151245-07a82500-4c0c-11ea-9855-0e52be6d3a3f.jpg)

**Comment by brandonkelly** [comment]
Craft [doesn’t support](https://docs.craftcms.com/v3/requirements.html#control-panel-browser-requirements) IE 11 anymore, however I’d be very surprised if you’re only getting a _server error_ like this on IE and not other browsers. Have you tried going to the exact same URL in other browsers, such as [Microsoft Edge](https://www.microsoft.com/en-us/edge), [Firefox](https://www.mozilla.org/en-US/firefox/), or [Chrome](https://www.google.com/chrome/)?

**Comment by petertindemans** [comment]
Have tried it, Firefox, Chrome works fine except EI11 and Edge. (clean installation)

Edge:
![foutmelding ie11 na login](https://user-images.githubusercontent.com/19586163/74329916-fdfbfa00-4d90-11ea-89bc-80eefeeb387a.png)

**Comment by narration-sd** [comment]
A point might be that there is a new replacment Edge, Chromium-based....

**Comment by FreekVR** [comment]
Possibly the same as #5671

**Comment by nordentwickler** [comment]
@brandonkelly we can confirm this issue - you are right on skipping the support for IE11 on the control panel. The problem we are facing is: we have contracts with a big health insurance in germany and we need to guarantee a secure cms with a support of IE11 for the backend - cause they are using IE11 in their organisation and they are not willing to update it. Now we are captured in a pretty bad situation.

**Comment by RitterKnightCreative** [comment]
@nordentwickler Yikes, yeh IE11 is very much alive in some corporate environments. 

While this doesn't affect my clients, this seems a little shortsighted to drop IE11 without any warning though, especially as Craft 3.3 worked with it just fine. I would fully expect Craft 4 to drop IE11 like a hot potato though.

Looks like Craft is relying on some ES6 stuff which is breaking IE11.  Did some limited testing and was able to log into the CP with IE11 after transpiling Craft.js via Babel. Looks like Axios still needs to be polyfilled though.

**Comment by brandonkelly** [comment]
I started transpiling the CP JS code with Bower, which fixed some Safari 9/10 ES6 issues (#5671), however even when I explicitly configure Bower to target IE11, it still doesn’t work. Considering we dropped support for IE11 with Craft 3.0, and even Microsoft basically has it on life support these days (security fixes only; not included by default with Windows anymore), I’m not inclined to start going through and manually changing a bunch of JavaScript code for it at this point.
