### ISSUE TITLE
Complex Project Config slows down 

### ISSUE THREAD

**Issue by markhuot** [craftcms/cms#5630]
I've got a rather complex project for a site we're working on and the back-end is taking 2-3 seconds to load per-page, which is slower than I've experienced in Craft before. I did some lo-fi debugging and found that loading the project config out of the database is taking half of that load time.

This is happening on every page load and I haven't yet determined what is calling or why it's slowing down like this.

### Steps to reproduce

1. Build a Craft site with 492 fields and 44 sections (woah…)
2. Try to load an admin page

The simple `var_dump` just used `microtime` to see how much of that load was taken up by the project config loading and parsing.

![Screen Shot 2020-02-10 at 1 39 09 PM](https://user-images.githubusercontent.com/48975/74182271-c0706300-4c10-11ea-8269-77bad4049bb5.png)

### Additional info

- Craft version: 3.4.3
- PHP version: 7.2 (or 7.3)
- Database driver & version: MySQL 5.7
- Plugins & versions: all of them, I can provide a complete list if necessary.

**Comment by andris-sevcenko** [comment]
Any chance you can clear out any credentials that may have accidentally entered the `project.yaml` file and send it over to support@craftcms.com, referencing this issue in the email?

There's definitely a case for caching just want to have an instance where I can benchmark things.

**Comment by markhuot** [comment]
Yup, emailed support. Thank you @andris-sevcenko!

**Comment by brandonkelly** [comment]
Craft 3.4.6 is out now with improved project config performance.
