### ISSUE TITLE
No search results due tag/space-stripping in searchindex table

### ISSUE THREAD

**Issue by rbrv** [craftcms/cms#5631]
### Description

Content gets stripped of all tags before it is saved to the `searchindex` table.

#### Example: 
```
<p>
  <strong>First title</strong><br>
  <a href="mailto:example@mail.com">example@mail.com</a>
</p>
<p>
  <strong>Second title</strong><br>
  <a href="mailto:anotherexample@mail.com">anotherexample@mail.com</a>
</p>
```

is being stripped and saved in `searchindex` as 

```
First titleexample mail comSecond titleanotherexample mail com
```

### Problem
This means there will be no result when searching for `Second`. There will be results when searching `comsecond`.

### Additional info

- Craft version: 3.3.20.1
- PHP version: 7.3
- Database driver & version: MariaDB 10.3.16

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just got that fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.6 is out now with this fix.

**Comment by rbrv** [comment]
@brandonkelly I've updated to 3.4.6.1 and ran `./craft resave/entries`. Bug is still there.

**Comment by brandonkelly** [comment]
@rbrv Craft no longer updates search indexes by default when you run `resave/entries`. You have to include the `--update-search-index` flag.

**Comment by rbrv** [comment]
@brandonkelly Didn't get that memo ;) All is working now, thanks!
