### ISSUE TITLE
First selection in dropdown doesn't save in 3.4.x

### ISSUE THREAD

**Issue by danethomas** [craftcms/cms#5632]
This has just started happening after upgrading to 3.4.5 (from a version prior to 3.4). 

We have a `dropdown` field and and when that's used in an entry the first option is selected in the control. If you save that entry the `dropdown` field is saved as empty. 

I can go in, select the second option, save, edit and select the first option and save and it will work. 

Changing the order of the options in the `dropdown` field doesn't change the behaviour. 

### Steps to reproduce

1. Add an entry and leave the `dropdown` field on the default (first) value
2. Save entry
3. First option in the `dropdown` field isn't persisted

### Additional info

- Craft version: Craft CMS 3.4.5
- PHP version: 7.3.13
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Default `dropdown` field

**Comment by cherrykoda** [comment]
Also having this issue - at first I thought it was an issue with setting the field as "required", but I've confirmed danethomas is correct.

Craft version: Craft CMS 3.4.5
PHP version: 7.3.11

**Comment by danethomas** [comment]
For the record, our's isn't within a matrix block - it just appears to be an issue with the dropdown field itself and the default value.

**Comment by brandonkelly** [comment]
Thanks for reporting that! This is now fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#d13a51f1faa80192b949471bb9ddd802ca861935 as 3.4.5",
  "...": "..."
}
```

Then run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.4.6 is out now with this fix.
