### ISSUE TITLE
[3.4.5] Error on "Deleting Stale Template Caches"

### ISSUE THREAD

**Issue by icreatestuff** [craftcms/cms#5633]
### Description
I get the following error in the Queue Manager when this job is being run

```
craft\elements\db\ElementQuery::_joinContentTable(): 
The script tried to execute a method or access a property of an incomplete object. 
Please ensure that the class definition &quot;craft\behaviors\ElementQueryBehavior&quot; of 
the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an
autoloader to load the class definition
```

### Additional info
- Craft version: 3.4.5
- PHP version: 7.2.27
- Database driver & version: 5.6.47

**Plugins & versions**
- Algolia: 2.0.0
- Contact Form: 2.2.6
- Imager: v2.3.1
- Mailchimp Subscribe: 3.0.1
- Redactor: 2.5.0
- Super Table: 2.4.4

**Comment by brandonkelly** [comment]
Thanks for reporting that, just got it fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#a8fdf52fd3bd6a5dd6e71d7755bf55dc972ecb9b as 3.4.5",
  "...": "..."
}
```

Then run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.4.6 is out now with this fix.
