### ISSUE TITLE
Sort order of sections preview targets is no longer stored in the correct order

### ISSUE THREAD

**Issue by kringkaste** [craftcms/cms#5634]
### Description
After upgrading from 3.3.15 to 3.4.5 and saving a section with preview targets, we saw, that the previous sort order of the preview targets is resetted and changing the sort order is not being saved either.

The project.yaml does not represent the changed order. Here you can also see, that it is always ordered by the ID. Old project.yaml respects the order correct.

### Steps to reproduce

1. Create two or more preview targets in a section
2. Save section
3. Re-open section for editing
4. Change order of preview targets
5. Save section
6. Re-open section for editing

The sort order of the preview targets is not saved. It's always sorted by the ID.

### Additional info

- Craft version: 3.4.5
- PHP version: 7.2

**Comment by lukeholder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ensure sections’ preview targets get stored in the correct order in project config](https://trello.com/c/sd2YVW1c/1-ensure-sections-preview-targets-get-stored-in-the-correct-order-in-project-config)

**Comment by andris-sevcenko** [comment]
Thanks for reporting that! This issue has been fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.6 is out now with this fix.
