### ISSUE TITLE
Should running ./craft setup pre-populate values from .env file if they exist?

### ISSUE THREAD

**Issue by kylecotter** [craftcms/cms#5635]
### Description

When running `./craft setup` from the command line, in previous versions I'm pretty sure if there was an .env file with values already filled in for things like DB connection, Site Name, etc, the CLI would pre-populate those values. This seems to have stopped since 3.4 Was that a deliberate change?

Thanks!

### Steps to reproduce

1. Have an .env file with some default values already in
2. Run `./craft setup` and follow the prompts, values from the .env file aren't populated

### Additional info

- Craft version: 3.4.5
- PHP version: 7.4
- Database driver & version: Mysql 5.7
- Plugins & versions:

**Comment by brandonkelly** [comment]
We changed up which settings it looks for in 3.4. Now instead of `DB_DRIVER`, `DB_SERVER`, `DB_DATABASE`, and `DB_PORT`, it looks for `DB_DSN`. Guessing that’s why you’re seeing a difference in behavior. (See https://docs.craftcms.com/v3/config/db-settings.html.)
