### ISSUE TITLE
Solution for Module\Yii2 not found during Codeception run

### ISSUE THREAD

**Issue by keyurshah** [craftcms/cms#5636]
### Description
I went through the installation steps provided in the Testing section for codeception.

I encountered the error:

```
Fatal error: Class 'Codeception\Module\Yii2' not found in D:\myfiles\laragon\www\mysite\vendor\craftcms\cms\src\test\Craft.php on line 65
```

To fix this,  I had to run 

```
composer require --dev codeception/module-yii2
```

This solved the issue for me and allowed me to run my tests.

I also got the error below when trying to add this to acceptance.suite.yml per the instructions. 
```
    - \craft\test\Craft
```

```
  PhpBrowser module conflicts with craft\test\Craft                                                    
                                                                                                       
  --                                                                                                   
  This usually happens when you enable two modules with the same actions but with different backends.  
  For instance, you can't run PhpBrowser, WebDriver, Laravel5 modules in one suite,                    
  as they implement similar methods but use different drivers to execute them.                         
  You can load a part of module (like: ORM) to avoid conflict. 
```

It worked when the `craft\test\Craft` line was not in `acceptance.suite.yml`

### Additional info

- Craft version: 3.4.5
- PHP version: 7.3.6
- Database driver & version: mysql 5.7.24
- Plugins & versions: codeception 4.1

**Comment by angrybrad** [comment]
This is because Codeception 4 moved a bunch of modules that used to be internal to separate packages (like the Yii2 module).

The next release of Craft will be using Codeception 4 with this adjustment. https://github.com/craftcms/cms/commit/295c370dee52c8dc8307762f0c4c2d93f2768091

**Comment by widewebpro** [comment]
This problem still exists. When I use WebDriver (hrome) with \craft\test\Craft in acceptance tests.
actor: AcceptanceTester
modules:
    enabled:
        - Asserts
        - WebDriver:
            url: http://solar_ww.test/
            browser: chrome
        - \Helper\Acceptance
        - \craft\test\Craft:
            cleanup: false
            transaction: false
step_decorators: ~  

This return:
In ModuleContainer.php line 543:
                                                                                                       
  WebDriver module conflicts with craft\test\Craft                                                     
                                                                                                       
  --                                                                                                   
  This usually happens when you enable two modules with the same actions but with different backends.  
  For instance, you can't run PhpBrowser, WebDriver, Laravel5 modules in one suite,                    
  as they implement similar methods but use different drivers to execute them.                         
  You can load a part of module (like: ORM) to avoid conflict.

**Comment by anvart** [comment]
I also have the same `craft\test\Craft module conflicts with PhpBrowser` error. Even with `codeception/module-yii2` installed.

Craft 3.6.13 / Codeception 4.1.20 / PHP 7.3.27

**Comment by angrybrad** [comment]
@widewebpro @anvart Don't think this is related to the original issue but try removing the Craft module from your acceptance.suite.yaml file?

i.e.

```
actor: AcceptanceTester
modules:
    enabled:
        - Asserts
        - WebDriver:
            url: http://solar_ww.test/
            browser: chrome
        - \Helper\Acceptance
```

**Comment by anvart** [comment]
@angrybrad thank you for the suggestion.

It does not work though:

`In Request.php line 852: Unable to determine the entry script URL.`.

Tried with both `WebDriver` and `PHPBrowser`.

**Comment by angrybrad** [comment]
@anvart hrm... I'm not sure. Just tested this using this acceptence.suite.yaml in the root of my tests folder:

```
actor: AcceptanceTester
modules:
    enabled:
        - PhpBrowser:
            url: https://e3018c3d3e4d.ngrok.io
        - \Helper\Acceptance
```

(nevermind the ngrok part - that URL is just so I can expose the site I wasn't it to use from my tests repo, which are in separate containers. behind the scenes, it's forwarding to http://localhost)

With this in `tests/acceptence/HomePageCest.php`

```
<?php
namespace crafttests\acceptance;

use AcceptanceTester;

class HomePageCest
{
    public function checkHomePage(AcceptanceTester $I)
    {
        $I->amOnPage('/');
    }
}
```

And when I run `./vendor/bin/codecept run acceptence`, I get this as the result:

<img width="600" alt="CleanShot 2021-05-13 at 14 40 11@2x" src="https://user-images.githubusercontent.com/61869/118191265-2ee63700-b3f9-11eb-9090-95bb22e66dd2.png">

**Comment by brianjhanson** [comment]
@acalvino4, any chance the `codeception/module-yii2` package didn't get installed for some reason? If you run `comopser update` or `composer install`, does it quiet the error? 

If not, is there any other information about your setup you can provide?
