### ISSUE TITLE
the cp header should be sticky

### ISSUE THREAD

**Issue by aquafun** [craftcms/cms#5641]
### Description

in the cp the header in the main-container get a class with `position: fixed;`. It would be better to remove this js part and set the header to `position: sticky;`

### Steps to reproduce

1. open your entries in the cp
2. scroll down

### Additional info

- Craft version: 3.4.5
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Not sure there’s any real benefit to doing this. We’d still need to monitor the window scroll position in JS, as other things change when the header gets fixed-positioned as well, such as its own CSS styles (drop shadow added, semi-transparent BG applied), and the position of the sidebar and details pane are affected.
