### ISSUE TITLE
GraphQL deprecation warning when accessing children of parent

### ISSUE THREAD

**Issue by weotch** [craftcms/cms#5642]
### Description

This may be related to #5068, the deprecation message looks like this:

>  Looping through element queries directly has been deprecated. Use the all() function to fetch the query results before looping over them.

Here's a portion of the stack trace:

![Screen Shot 2020-02-12 at 9 00 35 AM](https://user-images.githubusercontent.com/77567/74358345-29bdb680-4d76-11ea-83f1-5956c5ea03ad.png)

### Steps to reproduce

I have a Structure section called "Products" where I have two Entry types with handles of `brand` and `flavor`.  The first level of the Structure are `brands` and the second level is all `flavors`.

I've simplifed the erroring graphql query to this:

```gql
query getFlavor {
  entry(type:"flavor", slug:"milk-chocolate-bar") {
    ... on products_flavor_Entry {

      brand: parent {
        ... on products_brand_Entry {
          flavors: children {
            id
          }
        }
      }

    }
  }
}
```

This query looks up a `flavor` and then returns _all_ of the `flavors` of its `brand`.  I'm _guessing_ the issue relates to going back a level and then in again.

FWIW, this query _does_ work, returning this:

```json
{
  "data": {
    "entry": {
      "brand": {
        "flavors": [
          {
            "id": "69"
          },
          {
            "id": "840"
          }
        ]
      }
    }
  }
}
```

### Additional info

- Craft version: Craft Pro 3.4.5
- PHP version: 7.4.1
- Database driver & version: MySQL 8.0.19
- Plugins & versions:
  ![Screen Shot 2020-02-12 at 9 12 08 AM](https://user-images.githubusercontent.com/77567/74359232-c16fd480-4d77-11ea-8385-bb25900cad9b.png)

**Comment by andris-sevcenko** [comment]
I fixed this for the next release, thanks for reporting!

Word of warning, though - it's currently not possible to eager-load parents, so, instead of being executed as one query, you'll get two more queries executed for each result returned by the top level query.

**Comment by andris-sevcenko** [comment]
Related: #1382

**Comment by brandonkelly** [comment]
Craft 3.4.6 is out now with this fix.

**Comment by weotch** [comment]
Nice, I've been so impressed by the rate of addressing issues by your team, btw 🍻
