### ISSUE TITLE
Current site not maintained on multisite

### ISSUE THREAD

**Issue by JustJarethB** [craftcms/cms#5643]
### Description
We have a 4x multisite setup running in 3.4. It consistently reverts to the "main" site in the CP which makes editing entries frustrating and I keep putting entries/data in the wrong site. 
This issue seems to occur from the main entries page `cpTrigger/entries/entryType` and also from within an entry. Say for example, editing the homepage single on "site b", I want to add an entries field, it 
will open up the entries from the main site instead.

Similar to https://github.com/craftcms/cms/issues/2844 but Craft 3.4

### Steps to reproduce
Unsure, but can provide db if needed.

### Additional info

- Craft version: Craft Pro 3.4.4.1
- PHP version: 7.3.3
- Database driver & version: MySQL 5.7.25

**Comment by brandonkelly** [comment]
> Say for example, editing the homepage single on "site b", I want to add an entries field, it
will open up the entries from the main site instead.

I’ve just changed this for the next release. Now the element selector modal will open to the source element’s site by default.

**Comment by brandonkelly** [comment]
Craft 3.4.6 is out now with this change.
