### ISSUE TITLE
Longer author names wrap over multiple lines, which doesn't look pretty

### ISSUE THREAD

**Issue by FreekVR** [craftcms/cms#5646]
### Description
Users with even a slightly longer name will have their names wrapped over multiple lines in the edit/add entry sidebar, it doesn't really look pretty with all the other lines doing their best to have the same height.

I would suggest hyphenating longer names, with the original name as a "title" attribute, so it's visible on hover. In addition, perhaps the sidebar could do with being slightly wider, like ~50px, on the largest viewports.

![Screenshot 2020-02-13 at 14 52 13](https://user-images.githubusercontent.com/417416/74442017-0c214780-4e71-11ea-891e-d8a65edd9d42.png)

The issue doesn't seem to occur on smaller viewports as the sidebar then takes on the full page width and there's plenty of space.

### Steps to reproduce

1. Enter a first and last name for a user which exceeds ~12 chars in total
2. The author name now doesn't fit

### Additional info

- Craft version: 3.4.5
- Browser: Chromium Edge 80.0.361.50

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.6 is out now with this fix.
