### ISSUE TITLE
Vertical alignments in the sidebar seem to be slightly off 

### ISSUE THREAD

**Issue by FreekVR** [craftcms/cms#5647]
### Description
While I'm loving the style updates in 3.4x, in the add/edit entry sidebar,  it looks like the rows in the box vary slightly in height, and the labels/values aren't completely vertically aligned with each other or within the center of their row.

Additionally, the very first row (Entry Type) seems to have significantly less height than the others, causing that label to appear to be positioned too high instead of being in the center.

It seems the rows vary between 41px and 49px in height, so I'd suggest working from a base height of 49/50px so they're all equal heights, and then fixing positioning from there.

![Screenshot 2020-02-13 at 15 03 11](https://user-images.githubusercontent.com/417416/74442890-95854980-4e72-11ea-8660-22f2e5c7e6f9.png)

### Additional info

- Craft version: 3.4.5
- Browser: Chromium Edge 80.x.x

**Comment by brandonkelly** [comment]
Whoops, unintended side effect of a945518377c6c61f3901c1f2f936a94c7e32bc60. Thanks for noticing and reporting!

**Comment by brandonkelly** [comment]
Craft 3.4.6 is out now with this fix.
