### ISSUE TITLE
It seems like some general setting properties aren't picked

### ISSUE THREAD

**Issue by dominikkrulak** [craftcms/cms#5648]
I'll be short.

### What did I do?
Before I run install I set up my environment properties defined in _config/general.php_.

### What did I expect to happen?
- **`'postCpLoginRedirect'  => 'home',`** 

- **`'timezone' => 'Europe/Bratislava',`** - ~~wasn't set to desired zone for example `'Europe/Bratislava'`~~.  Instead NOT default value `null` is applied but probably hardcoded value `America/Los_Angeles`.  I see in control panel under _settings/general -> Time Zone_ the message `This is being overridden by the timezone config setting.` ~~which isn't~~ which IS. My bad. Had a bad day :disappointed:. 

### What happened instead?
- **`'postCpLoginRedirect'  => 'home',`** - when I logged in I wasn't redirected to`me/home` but `me/dashboard`. So when I visit _www.cp.site.test/me/home_ Craft gives `404 Yii error message`. I must retype it to _www.cp.site.test/me/dashboard_ to see the dashboard. 
> Maybe, in the future would be nice to omit 'postCpLoginRedirect' slug in case if control panel lives in subdomain?

- **`'timezone' => 'Europe/Bratislava',`** - ~~wasn't set to desired zone for example `'Europe/Bratislava'`~~. Instead NOT default value `null` is applied but probably hardcoded value `America/Los_Angeles`.  I see the message `This is being overridden by the timezone config setting.` in control panel under _settings/general -> Time Zone_  ~~which isn't~~ which IS. My bad. Had a bad day :disappointed:.
> Maybe, in the future would be nice to show current settings from _config/general.php_ file?

It isn't big issue but it bothers me.

### Additional info

- Craft version: 3.4.5
- PHP version: 7.4.2
- Database driver & version: PostgreSQL 11.6
- Plugins & versions: No plugins are enabled.

**Comment by brandonkelly** [comment]
Hi @dominikkrulak, sorry but I’m not sure I’m following you. Can you please elaborate?

- What did you do?
- What did you expect to happen?
- What happened instead?

**Comment by dominikkrulak** [comment]
@brandonkelly I see this is still open and now I have no idea what I was talking about. I've reacted with eyes emoji. Hmm probably I wanted to look into it again but later. I think I was just fooling around. I have no reason to keep the issue open. Thanks!

**Comment by brandonkelly** [comment]
Ah shoot, looks like you edited the issue a couple days after I asked for more details, but didn’t comment so I was never notified about it:

![A diff of the edits made on the original post](https://user-images.githubusercontent.com/47792/106320740-2130eb00-6228-11eb-914b-502f3219a353.png)

I was able to reproduce the `postCpLoginRedirect` issue, and just fixed that for the next release.

**Comment by brandonkelly** [comment]
Craft 3.6.2 is out with that change ✨
