### ISSUE TITLE
Plain text field with character limit incorrectly counting special characters

### ISSUE THREAD

**Issue by davist11** [craftcms/cms#5649]
### Description
When special characters are entered into plain text fields with a character limit set, they are incorrectly counted when validated by PHP. The JavaScript character count works correctly, but after trying to save an entry, the PHP validation fails.

![image](https://user-images.githubusercontent.com/199985/74478248-fdd82900-4e7a-11ea-9a75-fb2beddba2d0.png)

![image](https://user-images.githubusercontent.com/199985/74478282-134d5300-4e7b-11ea-99e3-1c5e3cbfef05.png)

It seems like maybe it's converting special characters before counting.

### Steps to reproduce

1. Create a plain text field with a 255 character limit
1. Add field to an entry type
1. Enter the following text: Elit magna aliquip ex sit duis incididunt aliquip nostrud est voluptate ullamco aliquip. Duis ipsum do non pariatur consequat proident mollit mollit commodo voluptate amet anim est et. Adipisicing voluptate velit nisi et tempor officia. Sint ea anim molli
1. See that there are 0 characters remaining, and save the entry successfully.
1. Now replace that text with the following text: Elit magna aliquip ex sit duis incididunt aliquip nostrud est voluptate ullamco aliquip. Duis ipsum do non pariatur consequat proident mollit mollit commodo voluptate amet anim est et. Adipisicing voluptate velit nisi et tempor officia. Sint ea anim moll”
1. See that there are 0 characters remaining, and see that the entry will not save successfully

### Additional info

- Craft version: 3.3.18.4
- PHP version: 7.2.14
- Database driver & version: MySQL 5.7.25

**Comment by brandonkelly** [comment]
This was fixed in Craft 3.4 (see #5099).
