### ISSUE TITLE
UX: Improve matrix field bar visibility issues introduced in 3.4 theme updates

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#5652]
With Craft 3.4, matrix field "settings" dropdowns and "move" icons are only visible on hover. Also, the color fades into the field, so the bar that you can double click to collapse a block isn't clearly defined.

**Craft 2**
![Screen Shot 2020-02-13 at 8 29 05 PM](https://user-images.githubusercontent.com/1007191/74501608-8b2d7480-4e9f-11ea-8861-7c45598bfbc9.png)

**Craft 3.4**
![Screen Shot 2020-02-13 at 8 29 13 PM](https://user-images.githubusercontent.com/1007191/74501636-9f717180-4e9f-11ea-8388-cf3d184d4aeb.png)

**Craft 3.4 (hovered)**
![Screen Shot 2020-02-13 at 8 29 20 PM](https://user-images.githubusercontent.com/1007191/74501643-a304f880-4e9f-11ea-8d01-e9065afd7a6b.png)

I feel like this is a downgrade in usability and the icons should always be visible, and that the bar should stand out against the rest of the field.

**Comment by jsunsawyer** [comment]
This should also affect the "status" icon when a block is disabled.

**Comment by jonleverrier** [comment]
Felt relevant to post this here. 

Would you consider adjusting the bottom spacing when a block is collapsed so it appears to be vertically aligned? At the moment it looks top aligned.

![Screen Shot 2020-02-20 at 10 25 30](https://user-images.githubusercontent.com/2373940/74919776-653a2f80-53cb-11ea-8eb1-c5eff4730f2c.png)

**Comment by brandonkelly** [comment]
Just improved the look of Matrix fields for the next 3.4 release (probably dropping later today).

<img width="621" alt="A Matrix block" src="https://user-images.githubusercontent.com/47792/74944535-0d8bcc00-53ab-11ea-91cf-a315c99ec9c0.png">

@jonleverrier Thanks for pointing that out – fixed that extra padding as well.

**Comment by brandonkelly** [comment]
3.4.7 is out now with that change.

**Comment by darylknight** [comment]
Thank you!
