### ISSUE TITLE
Updating Plugins for Craft 3.4

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#5653]
### Description
Not really sure if it really belongs here but I don't know where to submit this one. Please include your breaking change of ActiveRecords to the [Updating Plugins for Craft 3.4](https://craftcms.com/guides/updating-plugins-for-craft-34).
It took me some time to update all of my ActiveRecords to exclude Crafts ActiveRecord. I have to extend Yii's ActiveRecord directly since I use them to store arrays and other datatypes and work with them but that's not possible anymore.

I would rather suggest to include a config setting to not always change the value of magic methods but I guess that won't be the case.

Before someone else has the same trouble as me it would be a good move to add the new behavior to the docs and update notes

Edit: I'm talking about this https://github.com/craftcms/cms/commit/33e305ac74bf11bc0918f64a6a14b48446e017f1#diff-ba344546b1ebd7380e9d0ed9a44331f8 not sure why it was included but it destroys many things for me

**Comment by brandonkelly** [comment]
Just updated that page to mention this change: https://craftcms.com/guides/updating-plugins-for-craft-34#setting-active-record-values

You should only be using ActiveRecord clasess for database-storable data though; otherwise perhaps storing the data on a Model would be more appropriate. Yii’s own ActiveRecord class don’t support saving array data, so what you’re doing will lead to trouble if you ever attempt to `save()` the records.

**Comment by Anubarak** [comment]
Well that's not entirely correct https://www.yiiframework.com/doc/guide/2.0/en/db-active-record#attributes-typecasting

> Since 2.0.14, Yii ActiveRecord supports complex data types, such as JSON or multidimensional arrays.

Anyway, I used to do the same thing as you did before this commit and converted the data before the record is stored. That way I was able to work with the array/dateTime/complex data type and convert it in the before save function.

**Comment by brandonkelly** [comment]
Ah ok, I missed that. Well moving away from Craft JSON-encoding values altogether (and letting Yii handle it) would be more of a breaking change than what we did in 3.4, so will have to reevaluate that in Craft 4.
