### ISSUE TITLE
Search index not properly updated in multi-site environments

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#5654]
### Description

In a setup with 2 sites with languages en/de we are seeing missing search results after publishing drafts.

### Steps to reproduce

1. Create a new entry and enter content for both sites.
2. Save

==> The search index db table only contains records for one site.

Running resave/entries --site=* --update-search-index fixes that.

1. Create a draft from existing entry
2. Change content
3. Publish

=> The search index gets only updated for one site.

### Additional info

- Craft version: 3.4.5
- PHP version:  7.2.14
- Database driver & version: MySQL 5.7.14
- Plugins & versions: None

/Aylin

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Try making sure your search indexes are all set correctly to begin with by running `./craft resave/entries --update-search-index`, and then see if you can still reproduce your issue. If so, please send a database backup and your `composer.json` & `composer.lock` files into support@craftcms.com, with specific steps to reproduce.

**Comment by wsydney76** [comment]
@brandonkelly Will do.

But it is actually a fresh install with one draft entry in it. 

Will describe the steps here as it is easier to insert screenshots here:

Content site en:

![image](https://user-images.githubusercontent.com/60010597/74594438-bbf3e200-5036-11ea-9f08-b76858126d83.png)
 
Content site de:

![image](https://user-images.githubusercontent.com/60010597/74594458-fd848d00-5036-11ea-9a73-eae1fdca6581.png)

Save from site en (1)

`SELECT * FROM `searchindex` where elementId <> 1`

![image](https://user-images.githubusercontent.com/60010597/74594482-63711480-5037-11ea-991d-cda10ba7021a.png)

`.\craft resave/entries --site=* --update-search-index`

![image](https://user-images.githubusercontent.com/60010597/74594499-a7fcb000-5037-11ea-9228-22126bad4849.png)

Create a new draft, change content in both sites, publish from site en

![image](https://user-images.githubusercontent.com/60010597/74594546-1e011700-5038-11ea-8477-e2b0c59485d3.png)

Only the changes in site en (1) are picked up.

`.\craft resave/entries --site=* --update-search-index`

![image](https://user-images.githubusercontent.com/60010597/74594605-9e277c80-5038-11ea-8100-afa618d32784.png)

Thanks for looking into it.

**Comment by brandonkelly** [comment]
Thanks! Was able to reproduce, and just got this fixed for today’s 3.4.6 update.

**Comment by brandonkelly** [comment]
Craft 3.4.6 is out now with this fix.
