### ISSUE TITLE
CP search: previous requests should be cancelled on type, not queue

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#5655]
When dealing with large datasets, search can be pretty slow.

This means the type-as-you-search can get behind, which is expected, but it should be canceling previous requests, but instead it queues them up which results in odd behavior where the results don't match what you're searching for.

Similar but different…when you use the sidebar filtering (eg changing member groups) if you click another sidebar filter before the current one is finished, your results get out of whack.

Related: https://github.com/craftcms/cms/issues/1243

**Comment by brandonkelly** [comment]
Just made this change for the next release, along with a couple other changes we’ve made recently that will help improve performance for large projects.

**Comment by brandonkelly** [comment]
Craft 3.4.6 is out now  with this change.
