### ISSUE TITLE
Many-columned tables don't fit on Entry edit pages

### ISSUE THREAD

**Issue by rbaud** [craftcms/cms#5656]
### Description

Tables with many columns overflow, and flow under the sidebar, on the Entry edit page. The page and table/wrapper aren't horizontally-scrollable and with the overlap of the sidebar, it makes large tables unusable.

![image](https://user-images.githubusercontent.com/2589656/74552096-18151400-4f1a-11ea-90d0-d1d308b4bc19.png)

### Steps to reproduce

1. Add a table field with many columns
2. View it on an Entry edit page

### Additional info

- Craft version: 3.4.5
- PHP version: 7.2.24
- Database driver & version: MySQL 5.7.29
- Plugins & versions: None

**Comment by rbaud** [comment]
Please ignore the CP Field Inspect cogs here, I took the picture above before testing on a fresh, plugin-free install.

**Comment by jonleverrier** [comment]
@rbaud I think this has been fixed for the next release. See https://github.com/craftcms/cms/issues/5611#issuecomment-583840394

**Comment by brandonkelly** [comment]
Looks like this is a slightly different but related bug. Will look into it…

**Comment by brandonkelly** [comment]
Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.6 is out now with this fix.
