### ISSUE TITLE
Value of checkbox and light switch fields reset via jQuery no longer persist after save

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/cms#5657]
### Description

Prior to 3.4, I had been loading some custom JS via a module. The module reset certain checkbox and light switch fields, back to there un-selected state (selected = false). If a user then saved an entry, the selected value for the fields would be reset back to `false`.

Whilst this visually still works in the CP - when the fields get reset via JS, the values do not persist when a user saves an entry. This worked pre 3.4 - so i'm just trying to understand what changed. It wasn't a great solution, so maybe I'll find a better one.

**Reset multi-option checkbox:**
```
if ($('body.entriessection-conferences')[0]){
    $("input[name='fields[generatePages][]']").prop('checked', false);
}
```

**Reset lightswitch:**
```
 if ($('body.entriessection-brochure')[0]){
     $("input[name='fields[generatePdf]']").val('0');
     if( $('#fields-generatePdf').hasClass('lightswitch on') ) {
        $('#fields-generatePdf').removeClass('lightswitch on').addClass('lightswitch off');
     }
 }
```

### Steps to reproduce

1. Create a section called `Brochure`
2. Create a multi-value checkbox field with 3 options called `A, B & C` and assign it to your `Brochure` section
3. Create an entry in the `Brochure` section and tick checkbox `A` then save and exit
4. Add my first code example (Reset multi-option checkbox) to an asset bundle (change selector to match your field and remove if statement if required)
5. Go back to the entry - checkbox `A` should no longer be ticked because the JS has "reset" it. Now edit another field, save and exit
6. Comment out or remove the JS in the asset bundle
7. Now when you go back to the previous entry, checkbox `A` is still ticked, even though it was reset and the entry was saved in Step 5 

### Additional info

- Craft version: Craft Pro 3.4.5
- PHP version: 7.3.13
- Database driver & version: MySQL 5.5.5
- Plugins & versions: n/a

**Comment by jonleverrier** [comment]
Strange, but adding a timeout function makes it work again!

```
if ($('body.entriessection-conferences')[0]){
    window.setTimeout(function(event) {
        $("input[name='fields[generatePages][]']").prop('checked', false);
    }, 500);
}
```

**Comment by brandonkelly** [comment]
Probably happening because you were changing the lightswitch value before Craft had a chance to take note of the fields’ initial values, which it will compare against to find the delta changes that should actually be submitted when saving the entry.

**Comment by jonleverrier** [comment]
Thanks @brandonkelly. Is there an elegant way to trigger js when craft has finished loading ?

For example, if garnish has loaded, do something?

**Comment by brandonkelly** [comment]
What you’re doing is probably about as elegant as you can get for now, since only entry forms support delta updates currently. We’ll probably make it more consistent in Craft 4.

**Comment by narration-sd** [comment]
@jonleverrier  It did occur to me when this first came by that you might gain by doing an event-based response, such as is pretty clearly outlined in the example here: https://stackoverflow.com/questions/39155645/multiple-window-onload-functions-with-only-javascript/39155698#39155698

In general, event-based is much preferable to timeouts, yes -- I'm just not sure this event will quite be fully post-Garnish's actions, but you could try it.  If not quite sufficient, a smaller timeout might get you there, and with higher reliability...

**Comment by jonleverrier** [comment]
Thanks for the idea @narration-sd.

Garnish still seems to win the race when I tried using an event listener. Keeping with the timeout solution for the time being :)

**Comment by narration-sd** [comment]
@jonleverrier  sounds good info.  What I'd personally do on this basis is as last suggested, use both:
- event listener takes care of variable potential wire delays, etc.  however long they are
- timeout you can then set more reliably to handle browser execution delays for the Garnish activities -- of course with its own safety margin, but this way it will be much shorter for being safe.
