### ISSUE TITLE
!important in cp css foils overriding that css

### ISSUE THREAD

**Issue by marionnewlevant** [craftcms/cms#5658]
### Description
https://github.com/craftcms/cms/commit/07ff758d3828e665920a9bb8d656e3877dd0aa99 changes add !important to css directives (e.g. _main.scss line 1235, for the background-color of .btn.submit).
I used to use cpcss plugin to change that color, now am unable to.

### Additional info

- Craft version: overrides work in 3.3.19, not in 3.4.5

**Comment by brandonkelly** [comment]
We hope to reduce the need for `!important` in Craft 4. In the meantime you’ll just need to add your own, along with an equal or more-specific CSS selector.
