### ISSUE TITLE
Multisite asset field propagating to the wrong language

### ISSUE THREAD

**Issue by AndrewMac** [craftcms/cms#5659]
### Description

I have a field attached to asset volumes that is set to translate across languages, and content in those asset volumes is being propagated to the wrong language. It's all a bit confusing to explain, but I'll try below ...

### Steps to reproduce

1.  I have a multisite setup, with three sister domains in three site groups that each have two language sites (English and Thai).
2. I have an 'Alt Text' field that is set up to translate between languages.
3. That field is attached to a number of asset volumes (which are, by default, available to all sites).
4. I add a description into the 'alt text' field for an asset in the first site language (eg, English) and save. The field data for that asset is copied across into the English language sites in each of the other groups, which is correct.
5. I then switch to one of the Thai language sites, add a description into the 'alt text' field for that asset, and save. The description in the 'alt text' field for that language disappears—the field is still empty in the Thai language site in each group. 
6. I check 'alt text' field in each the three English language sites. They now contain the description I had entered in Thai, which is obviously incorrect. The English version entered before has gone.
7. And if I then fix the English version, it in turn gets deleted in each of the English language sites and the English description gets copied into the Thai language sites ... etc, etc.

### Additional info

- Craft version: 3.4.5
- PHP version: 7.4.2
- Database driver & version: MySQL, Maria
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed it for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#b29eb687c4cb0f2f2d0052f4029f4351a347cebc as 3.4.5",
  "...": "..."
}
```

Then run `composer update`.

**Comment by AndrewMac** [comment]
Thanks so much for that! :-)

**Comment by brandonkelly** [comment]
Craft 3.4.6 is out now with this fix.
