### ISSUE TITLE
Setting element fields by handle no longer works

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#5666]
### Description
The following code worked in 3.3 but not in 3.4

```
$entry = new Entry();
$entry->readyForReview = true;
```

In 3.4, it works when I do 
```
$entry = new Entry();
$entry->setFieldValue('readyForReview', true);
```

Is this the expected behavior? I remember seeing something about this recently but I can't find it in the changelog.

### Additional info

- Craft version: 3.4.5
- PHP version: 7.3.12
- Database driver & version: 5.7.28
- Plugins & versions:

**Comment by aelvan** [comment]
That's intentional, see https://craftcms.com/guides/updating-plugins-for-craft-34#setting-custom-field-values.

**Comment by brandonkelly** [comment]
Yep. See #5449 for a related discussion.
