### ISSUE TITLE
Country code from address field not showing in email 

### ISSUE THREAD

**Issue by ClaireSer** [craftcms/cms#5667]
### Description

Hi,

I use sprout form and I have an address field in which I have the country data I want to show in my email template like this :  {country.countryCode}.
I had the version 3.6.6 of Sprout and it was working fine. But since I upgraded it, the field is no longer showing.

Thank you for you help.

### Additional info

- Craft version: 3.4.5 (Solo)
- PHP version: 7.1.31
- Plugins & versions: 
    - Sprout Forms 3.8.2

**Comment by brandonkelly** [comment]
Sounds like this is an issue with the [Sprout Fields](https://plugins.craftcms.com/sprout-fields) plugin, not Craft CMS directly. Please post this over at https://github.com/barrelstrength/craft-sprout-fields/issues.
