### ISSUE TITLE
Dynamic Slugs Problem when Entry will duplicated

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#5668]
We have a project where we create most of the slugs dynamic.
Now the problem is when an Author duplicate an entry the slug is the same and does not change on save (add a -1 at the end)

With normal slugs the behaviour is fine. It adds a `-1` at the end.

would be nice if dynamic slugs would be work the same.

Craft CMS: 3.1.17.2

**Comment by brandonkelly** [comment]
What do you mean by “dynamic slugs”?

Craft will only increment the slug automatically (e.g. `foo-1`) if it is trying to give an entry a unique URI, and its URI format contains `{slug}`.

If your URI format doesn’t contain `{slug}`, then take a look at #4759, which is now fixed for the next release.

**Comment by davidhellmann** [comment]
@brandonkelly ah sorry,

mean Dynamic Titles that creates the slug:
![image](https://user-images.githubusercontent.com/764292/74831340-5db84f00-5315-11ea-85a3-e8038512bd8f.png)


When I duplicate an Entry with an Title like this, it creates the same slug twice. 

But maybe this issue above fix that problem

**Comment by brandonkelly** [comment]
Yeah so to be clear, slugs will only be incremented when Craft is attempting to find a unique URI for the entry, and only if all of these things are true:

- The section has an Entry URI Format.
- The section’s Entry URI Format contains `{slug}`.
- Another entry with the exact same _URI_ already exists. (It doesn’t matter if another entry with the same _slug_ already exists, unless that results in a duplicate URI.)
