### ISSUE TITLE
Plugin license using .env variable not "nullable"

### ISSUE THREAD

**Issue by FreekVR** [craftcms/cms#5669]
### Description
Our project uses project config with admin changes disabled on local and staging environments.
Our acceptance environment domains contain the "acc"-prefix as used by the Craft CMS license to then allow an indefinite trial. The staging domain is however **not** a subdomain of the production domain.

I am struggling with how to set up paid plugin licenses to work in "trial" mode on our acceptance environment -- or have it accept the license we use as valid at least.

I've already set my license keys to use .env values like so:
**.env:**
`NEO_LICENSE_KEY=null`

**project.yaml:**
```
  neo:
    enabled: '1'
    licenseKey: $NEO_LICENSE_KEY
    schemaVersion: 2.2.0
```

All good so far.

However, with this setup, with the license key in .env set to NULL or any nullish value I would expect it to revert the plugin to "trial"-mode, as it does when you don't enter any license key value in the admin CP.

Currently, it seems my options are limited to:
- Setting the null value as above, however, I now get warnings in the admin CP about "Invalid license keys" being set
- Setting the value in `.env` to the actual license key in every environment. However, as the domain names are not the same, I will get warnings in the admin CP about the license "Not being valid for this domain"

In #4604 it is mentioned that you "shouldn't set your license keys to empty values". In that case, I'd appreciate some advice on how to otherwise tackle this multi-environment license issue I'm facing ;)

### Additional info

- Craft version: 3.4.5
- PHP version: 7.2

**Comment by brandonkelly** [comment]
> I've already set my license keys to use .env values like so:
> **.env:**
> `NEO_LICENSE_KEY=null`

I think that will literally set the license key to the string `"null"`, not an empty value like you think it does. Try just setting it to a blank value instead:

```
NEO_LICENSE_KEY=""
```

Or, set it to the actual license key, and then ensure that `config/license.key` is also set to the correct Craft license key. As long as you’re accessing Craft on a dev domain where trials are allowed, you’re also allowed to use a Craft license that doesn’t belong to the same domain.

**Comment by FreekVR** [comment]
Hi Brandon,

Using the same and filled-in license keys combined with the craft license (which was missing in my dev and acceptance envs) everywhere does fix the issue, thanks :)

However, I would still expect any nullish or non-existent value for the .env variable to have the same behaviour as not filling anything in.

I've tried the following values, each of them giving the "invalid license" errors:

`=""`
`=" "`
`=false`
`="null"`

**Comment by brandonkelly** [comment]
Just looked into this a bit, but it’s a little complicated and I don’t think this is worth adding a bunch of special case exceptions over. So just keep storing the correct plugin license keys & Craft `license.key` file across all of your environments :)

**Comment by FreekVR** [comment]
No worries, thanks for looking into it, figure it was an edge case to begin with :)
