### ISSUE TITLE
Craft 3.4 admin CP broken in Safari 9.x due to JS errors

### ISSUE THREAD

**Issue by FreekVR** [craftcms/cms#5671]
### Description
The current Craft Admin CP requirements list Safari 9.0+ as a supported browser. However, I am unable to log-in to the CMS due to the following console errors on the login page, which I would guess prevent the CSRF checks from working.

![Screenshot 2020-02-18 at 15 09 48](https://user-images.githubusercontent.com/417416/74743767-4881e880-5261-11ea-89a8-78c22b1a5ec9.png)

--------

And my client, who uses a custom SSO form to log in, sent me the following screenshot, with some broken CSS and missing content areas (again, I would venture to guess caused by broken JS). 

![Screenshot 2020-02-18 at 15 15 01](https://user-images.githubusercontent.com/417416/74743874-7830f080-5261-11ea-80eb-6f5dee5a73e5.png)

---------
### Steps to reproduce

1. Open a Safari 9.1 window (tested via browserstack on OSX el capitan)
2. Navigate to the Craft login form
3. Enter the correct credentials
4. You get the CSRF error screen

### Additional info

- Craft version: 3.4.5
- PHP version: 7.2
- Database driver & version:n/a
- Plugins & versions:n/a

**Comment by FreekVR** [comment]
I did some additional testing and the same issue also occurs in Safari 10.x

Starting from Safari 11.1, the issue seems fixed.

**Comment by RitterKnightCreative** [comment]
Looks like Craft 3.4 is using ``let`` statements other things which [Safari 9](https://caniuse.com/#search=let) doesn't support.  Safari 10 supports ``let`` but support is buggy (getting a slightly different JS error).

Apple doesn't even support El Cap anymore either, can your client upgrade to Firefox?

**Comment by FreekVR** [comment]
Sure, but in that case the docs should need an update, as it indicates
support for browsers which are not currently working (issue also affects
edge)

**Comment by brandonkelly** [comment]
We just released Craft 3.4.7 with Safari 9/10 compatibility fixes. Should be good now!

**Comment by brandonkelly** [comment]
Heads up: we have a use for ES6 module support in Craft 3.5, so I’ve undone this change for that release (896fa50c7ac4938fd193915e28f7a1138b4af687).

**Comment by FreekVR** [comment]
@brandonkelley certainly get why you'd want to drop older browsers but would it be at all possible to include a banner to warn when using an incompatible browser? A lot of our clients will be getting this update and this would greatly help in terms of communicating compatibility issues

**Comment by brandonkelly** [comment]
@FreekVR good idea! Just added a blocking message if the browser doesn’t support ES6 modules.

<img width="656" alt="A Craft CMS login form, with a blocking message displayed over it saying that a newer browser is required to access the control panel" src="https://user-images.githubusercontent.com/47792/82699349-56108b00-9c21-11ea-980f-570aa31b5749.png">
