### ISSUE TITLE
maxSlugIncrement vs 'save as new entry'/duplicate

### ISSUE THREAD

**Issue by SayChi** [craftcms/cms#5673]
### Description
The maxSlugIncrement setting in general.php and duplicating (or saving as new entry, which I assume uses most of the same code?) don't seem to cooperate that well. If I set `'maxSlugIncrement' => 0` and do either of those actions it does actually create a new entry with the same slug (which shouldn't be possible), which then, ofcourse, is not possible to edit without changing the slug manually.

What I would expect to happen is getting an error that duplicating the entry is not possible, instead of just creating a new entry with a duplicate slug.

Also, if you do actually change the title and either change or remove the slug before clicking 'save as new entry' it also just creates a new entry with the old slug (instead of either using the new slug or generating a new one based on the new title)

Hope this description is somewhat understandable, had a hard time wrapping my head around what is actually happening because there are some weird behaviours here, so the description might not be the clearest

### Steps to reproduce

1. 'maxSlugIncrement' => 0
2. duplicate entry or save as new (either with or without changing title and slug)
3. now there should be entries with duplicate slugs

### Additional info

- Craft version: 3.4.5
- PHP version: 7.1.33
- Database driver & version: MySQL 5.5.64

**Comment by SayChi** [comment]
and ofcourse I couldn't find a similar issue before I post this, but now I do #5510, oops

**Comment by brandonkelly** [comment]
Not only that, but I happened to fix that same issue earlier today :) See https://github.com/craftcms/cms/issues/5510#issuecomment-587675920

**Comment by brandonkelly** [comment]
Craft 3.4.6 is out now with this fix.
