### ISSUE TITLE
[Feature Request] Offer a way to disable `pathParam`

### ISSUE THREAD

**Issue by benface** [craftcms/cms#5676]
It seems `pathParam` is not needed in some setups. For instance, on Apache I can simply do this:

```
RewriteRule (.+) index.php [QSA,L]
```

instead of this:

```
RewriteRule (.+) index.php?p=$1 [QSA,L]
```

and everything still works. In fact, I'm not sure when it is ever needed other than when `omitScriptNameInUrls` and `usePathInfo` are both `false`, which I'm pretty sure is not common at all for a production website. For that reason, I would like to be able to set `pathParam` to `null` in order to completely disable it, so that users cannot inadvertently change the route via a GET parameter.

Thank you! :)

**Comment by brandonkelly** [comment]
How would that work? You need a way to tell Craft what the requested path is.

**Comment by benface** [comment]
Hey @brandonkelly, well I guess I'm misunderstanding then. How is it that it works when I don't pass a `p` parameter? I thought Craft  inferred the path based on the current URL and the site's base URL but perhaps I'm mistaken?

**Comment by brandonkelly** [comment]
The whole point of that redirect is so Apache can set the `p` parameter before the request makes its way over to Craft. So when you go to `/foo/bar`, behind the scenes that will get redirected to `index.php?p=foo/bar`.

**Comment by benface** [comment]
Yes yes I understand that. Sorry for explaining badly... what I'm saying is that somehow this is not needed in my current (and all of my sites') setup, but perhaps there's something else going on that I don't understand. Are you saying that this should NOT usually work:

```
RewriteRule (.+) index.php [QSA,L]
```
?

**Comment by brandonkelly** [comment]
Correct. Are you sure you’re actually using Apache, and not Nginx?

**Comment by benface** [comment]
I am using both actually haha. Apache in local dev, Nginx on the server. In neither environment am I passing a `p` param, yet Craft is able to route the request properly. :/

**Comment by benface** [comment]
Hey @brandonkelly, I think I understand why it is not needed. Look at this line here: https://github.com/craftcms/cms/blob/develop/src/web/Request.php#L286

It looks like if `omitScriptNameInUrls` and `usePathInfo` are false, it will still use the path info if no path is set with `pathParam` (as returned by `_getQueryStringPath()`). Indeed, if I comment out that line, then the routing stops working until I add back the `?p=$1` in my `.htaccess`.

I still think it makes sense for `pathParam` to be disabled, since the path info seems to be a working alternative. I tried setting it to an empty string, but it makes "A server error occurred" appear in the CP so I suppose it's not actually supported. In the meantime I set it to some long random string to prevent conflicts with any real query string param I might need.

**Comment by brandonkelly** [comment]
`_getQueryStringPath()` returns the path set by the path param (`p`). So I suspect the requested URI is still making its way to the `p` param somehow.

Try going to `/admin/utilities/php-info` and search for `admin/utilities/php-info`. What server variable(s) do you see that string show up in?

**Comment by benface** [comment]
@brandonkelly `$_ENV['REQUEST_URI']`

And yes, I know `_getQueryStringPath()` returns the path set by the path param, and I was saying that because it's empty it's going into the `if (!$this->_fullPath) {` block and setting `$this->_fullPath` to `$this->getPathInfo(true)`. Again, sorry if I'm not clear. 😅

**Comment by benface** [comment]
@brandonkelly Do you see what I mean?

**Comment by brandonkelly** [comment]
Sorry for the delay. Yeah I see what you mean :) Not sure how it took this long for me to realize that mod_rewrite doesn’t actually redirect the request if you don’t specify a domain name in the RewriteRule.

As of Craft 3.5 you will be able to set the `pathParam` config setting to `null`, to completely disable it.

**Comment by benface** [comment]
> Not sure how it took this long for me to realize that mod_rewrite doesn’t actually redirect the request if you don’t specify a domain name in the RewriteRule.

I'm not exactly sure what you mean by that, but cool. :) Thanks Brandon!
