### ISSUE TITLE
[Question / Feature Request] Does Craft Graphql support Query Batching ?

### ISSUE THREAD

**Issue by stephanedemotte** [craftcms/cms#5677]
Does Craft Graphql support Query Batching ?

I try with my [client](https://logaretm.github.io/villus/guide/query-batching.html#basic-batching) and this is craft response
```
{
	"name":"Bad Request",
	"message":"No GraphQL query was supplied",
	"code":0,
	"status":400,
	"type":"yii\\web\\BadRequestHttpException"
}
```

**Comment by andris-sevcenko** [comment]
Not currently, no.

However, the underlying library we're using supports them, so I'll keep this open to re-visit for 3.5.

**Comment by andris-sevcenko** [comment]
Timing on this ended up being pretty good, as I also encountered https://github.com/logaretm/villus/issues/26 :)

This has been added for Craft 3.5.
