### ISSUE TITLE
Integrity constraint violation after update to 3.4.6.1

### ISSUE THREAD

**Issue by elfacht** [craftcms/cms#5678]
### Description

dev and staging looks fine, but after deploying to production my navigation has duplicate entries in the Matrix field. Saving the fields is throwing this exeption:

![Screenshot 2020-02-19 um 11 45 13](https://user-images.githubusercontent.com/529443/74828582-a967fa00-530f-11ea-9252-b7479b4b51cf.jpg)

Happens only on production. Updated from 3.45 to 3.4.6.1. I'm trying to rollback now …

### Additional info

- Craft version: 3.4.6.1

**Comment by brandonkelly** [comment]
Can you please send a database backup, plus your `composer.json` and `composer.lock` files, over to support@craftcms.com?

**Comment by elfacht** [comment]
done

**Comment by brandonkelly** [comment]
Just got this fixed for today’s release 🎉

**Comment by brandonkelly** [comment]
Craft 3.4.7 is out now with the fix.
