### ISSUE TITLE
reaaaally long titles in cp

### ISSUE THREAD

**Issue by SayChi** [craftcms/cms#5681]
### Description
Got some long titles, but they take up a lot of space since I just updated.
I think it's because of the fix for #5646 which might be affecting more than just the username display.
![image](https://user-images.githubusercontent.com/12159362/74850854-be0db780-533a-11ea-8c13-80d3e3c0b510.png)

It's pushing away all the other columns to the point where I get a horizontal scroll bar

### Steps to reprouce

1. create entry with long title
2. look at entries index page

### Additional info

- Craft version: 3.4.6.1

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just got this fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#16d5a98ddf5bd81df3460a872a82767c82d9f350 as 3.4.6",
  "...": "..."
}
```

Then run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.4.7 is out now with the fix.
