### ISSUE TITLE
PHP Error when accessing admin: Module 'memcached' already loaded

### ISSUE THREAD

**Issue by MLCochrane** [craftcms/cms#5685]
### Description
Hey there,

When going to the /admin endpoint, or clicking, "Go to your control panel" from the welcome page I see the Craft "Interal Server Error" message. We're using Craft "headless-ly" and haven't needed to access the admin in a while so this was just noticed recently.

Current log and stack trace for this issue is: 
```
yii\base\ErrorException: Module 'memcached' already loaded in Unknown:0
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
```

The previous item in the log was back in August which looks like craft updated from 3.2.10 to 3.3.0 which I have to assume was done through the control panel as I don't recall doing so with composer. Unfortunately I don't know if the issue actually started then or not.

My understanding is the error is related to extensions being loaded multiple times in `.ini` files however that and extensions are handled through our hosting. Despite this, things were working fine for a while.

Any insight on what might be the culprit?
Is the issue more likely to do with the hosting rather than something not playing nice with Craft?
### Steps to reproduce

1. Visit the /admin endpoint of the control panel.

### Additional info

- Craft version: 3.3.0.1
- PHP version: PHP 7.1.33
- Database driver & version: MySQL 5.7.25 (I believe)
- Plugins & versions: 
   - Element-API 2.6.0

**Comment by brandonkelly** [comment]
Sounds like a server misconfiguration to me. And that’s a fatal PHP error, so not something that’s caused by Craft. Try bringing it up with your host.
