### ISSUE TITLE
Issue on default Site ordering

### ISSUE THREAD

**Issue by minyangu-bgl** [craftcms/cms#5686]
### Description
Currently, the site ordering seems uses the auto increment site ID in the table. It would be much better to order by Site Name instead, so when Content Editor goto entries, in the dropdown he can view the site list in alphabetical order.

- Craft version: 3.3
- PHP version:7.2.26

**Comment by aelvan** [comment]
Or better yet, that the list of sites was sortable. :)

**Comment by brandonkelly** [comment]
Actually the sites *are* user-sortable, but you have to click on a site group first to control it.

**Comment by minyangu-bgl** [comment]
Ah, that's cool! Didn't know it exists.
