### ISSUE TITLE
Calling Craft::$app->globals in a plugins config file causes global fields to return as NULL

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/cms#5688]
### Description

I'm having a weird issue under Craft 3 where if I call `Craft::$app->globals->getSetByHandle('handle')` in a plugins config file, in this case: https://github.com/sjelfull/craft3-restrict `config/restrict.php`. When trying to return the value of a global field in from another set in an unrelated component i.e. a module, the value is always NULL even though it's a populated and valid field. It seems to be happening on PlainText fields, entry and category fields still seem to work fine, it's possible happening with other field types too.

I didn't think calling `Craft::$app->globals->getSetByHandle()` in a config file would be a problem, but it seems to cause issues.

To debug, I created a copy of `index.php` and called it `debug.php` and simply removed the last line `$app->run();` line so I can execute Craft:: without the full app being run and I can see the NULL behaviour happening. If I disable the restrict plugin or simply remove the Craft::$app->globals call in the config file, the global field values are all returned correctly.

I'm not sure if this is a Craft bug or related to this specific plugin, I have found information eluding to a potential loading/initialisation problem previously, which seemed to be a bit of both scenario.

* https://github.com/craftcms/cms/issues/3028
* https://github.com/nystudio107/craft-seomatic/issues/108

I have also logged the issue with the plugin developer directly:

* https://github.com/sjelfull/craft3-restrict/issues/9

### Steps to reproduce

1. Install restrict CP plugin
2. Call Craft::$app->globals->getSetByHandle('handle') in `config/restrict.php`. It would appear, this doesn't need to be assigned into the config itself for this issue to occur.
3. Try and get a global field that is plaintext in another part of Craft, the returned output will return NULL, unless the restrict plugin is disabled or the Craft::$app->globals call is removed from the config file.

### Additional info

- Craft version: 3.3.20.1
- PHP version: 7.2
- Database driver & version: MySQL 5.6
- Plugins & versions:

**Comment by brandonkelly** [comment]
That config file is loaded before Craft is fully initialized, and there are always going to be weird bugs like this if any element queries (such as loading a global set) are executed before Craft is finished initializing.

Instead, maybe create a custom [module](https://docs.craftcms.com/v3/extend/module-guide.html) which listens for [EVENT_INIT](https://docs.craftcms.com/api/v3/craft-web-application.html#event-init), and sets the Restrict settings from there.

```php
use craft\web\Application;
use superbig\restrict\Restrict;

Craft::$app->on(Application::EVENT_INIT, function() {
    $global = Craft::$app->globals->getSetByHandle('handle');
    $plugin = Restrict::getInstance();
    $plugin->settings->settingName = $global->fieldHandle;
    // ...
});
```

**Comment by jamesmacwhite** [comment]
@brandonkelly Thanks for taking the time to reply and for confirming it's related to the initialisation process, 

Is it a general recommendation to avoid calling Craft::$app in config files due to potential issues like this?

I'll look at using a module to set these settings instead.

Thanks again!

**Comment by brandonkelly** [comment]
Mainly just make sure you’re avoiding element queries there, since those rely on the application being fully initialized.

**Comment by jamesmacwhite** [comment]
Good to know, thank you!
