### ISSUE TITLE
Renaming a field group doesn't (always) update the project.yaml

### ISSUE THREAD

**Issue by aNickzz** [craftcms/cms#5693]
### Description
Just noticed this, and it seems to be inconsistent.

I had `project.yaml` open (in watch mode) and tried renaming a group around 15 times and the yaml only updated once every 3 or 4 changes, so maybe this is working as intended if there is some timeout on how often it will write to the yaml?

After testing some more it does look like it could be a debounce on updating the yaml, but i'll lodge this anyway in case it's not.

### Steps to reproduce

1. Enable using the project.yaml
2. Create a field group
3. Rename the field group
4. Go to step 3.

### Additional info

- Craft version: 3.4.7
- PHP version: 7.1
- Database driver & version: N/A
- Plugins & versions: N/A?

**Comment by brandonkelly** [comment]
Just tested this and not able to reproduce. I renamed a field group 10 times and each time the `project.yaml` file immediately reflected the change. Suspect it’s just an issue with the file watcher.
