### ISSUE TITLE
Double clicking image asset in CP causes 500 error

### ISSUE THREAD

**Issue by jlapan** [craftcms/cms#5694]
Double clicking on an image asset (either on an entry layout field or in the assets section) causes a 500 server error. However, if when in the Assets section I click the checkbox and then choose edit image, everything works as expected.

Craft version: Craft Pro 3.4.6.1

**Comment by brandonkelly** [comment]
I suspect this may have been related to #5678, which was just fixed in Craft 3.4.7. Can you try updating and see if it helps?

**Comment by loqus** [comment]
I see this occur also for others that have rights for the assets and the sites in Craft Pro 3.4.10.1.
They can edit assets in the asset menu, but not upon double clicking in the entry itself. The console gives a 403 (forbidden) on a post to ?p=admin/actions/elements/get-editor-html

**Comment by brandonkelly** [comment]
@loqus This issue is for a 500 error; can you please post yours as a new issue?

Will close this one due to inactivity. @jlapan if you have a chance to test after updating to 3.4.7+, please let me know how it goes.

**Comment by jlapan** [comment]
@brandonkelly Sorry I forgot to respond. Updating to 3.4.7+ resolved my issue. Thanks!
