### ISSUE TITLE
Inefficient search SQL query?

### ISSUE THREAD

**Issue by my2ter** [craftcms/cms#5696]
### Description

Hi,

My application is running Craft commerce and our **craft_searchindex** table contains around 3 millions entries. I thought at first Commerce might be the main problem when we use the following logic in our template because the table is big due to commerce data:

`craft.entries.search(query).limit(10).orderBy('score');
`

but after enabling the debug tools on the frontend I realised what SQL queries is used under the hood. I'm no SQL expert but running a quick test by comparing two similar SQL queries, I'm questioning if the Search service is not optimised...?

Running those two queries shows a massive time difference, the first one generated by Craft Search service, the second being a generic query I used:

`SELECT * FROM craft_searchindex WHERE MATCH(keywords) AGAINST('+contact*' IN BOOLEAN MODE);`

Returns 25 893 rows in **20.9s**

`SELECT * FROM craft_searchindex WHERE keywords LIKE '%contact%';`

Returns 31 928 rows in **15.3ms**

The second query is even returning more rows in less time and less than 20ms... VS a whopping 20s for Craft search SQL...

I've even run a test by changing the function **_sqlFullText** in **src/services/Search.php:726** to

```
    private function _sqlFullText($val, bool $bool = true, string $glue = ' AND '): string
    {
        if (Craft::$app->getDb()->getIsMysql()) {
            $val = (is_array($val) ? implode(' ', $val) : $val);
            $val = trim($val, "+*");
            return Craft::$app->getDb()->quoteColumnName('keywords') . "LIKE '%" . $val ."%'";
        }
```

Result are shocking! My page used to throw 504 and never load, I get my results now in less than one second.

Would love to get your thoughts!
Cheers

### Additional info

- Craft version: 3.4
- PHP version: 7.3
- Database driver & version: MySQL 5.7 (Running AWS db.r5.4xlarge)
- Plugins & versions: Commerce 2

FYI: This is also affecting the CMS search

**Comment by angrybrad** [comment]
Can you swap the storage engine on the `searchindex` table from MyISAM to InnoDB (which does row level locking) and see if that helps performance?

**Comment by my2ter** [comment]
Hi Brad,

I'm already running InnoDB.

**Comment by brandonkelly** [comment]
Hey Romain,

Just added a new `$useFullText` property to `craft\services\Search`, which can be set to `false` from `config/app.php` to completely disable fulltext searching.

```php
return [
    'components' => [
        'search' => [
            'useFullText' => false,
        ],
    ],
];
```

**Comment by brandonkelly** [comment]
3.4.10 is out with this change.

**Comment by jamiewade** [comment]
@brandonkelly Thanks for releasing this Brandon. We were having some serious search issues with MySQL, but setting `useFullText` to `false` fixes it.

However, has your release now set `useFullText` to true _by default_? In the sense that we now need to go through all Craft 3.4 sites and set it to `false` in order to get our search working properly?

**Comment by brandonkelly** [comment]
@jamiewade No, it’s still `true` by default, and we don’t plan on changing that. Fulltext is generally preferred because it’s faster.
