### ISSUE TITLE
Where does the "token" url param come from?

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#5698]
### Description
A client recently reported that their website that one of the links that Google indexed for their site had "token" url param (eg: `?token=hf99qvd6wzplenuo3nddzijm4079ej2a`)and asked where that came from.

When sharing entries from the CP there's a `craft-preview-token` param but that's not this one.
Does Craft add this anywhere and if so when? 
Thanks!

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
If you visit a page with a `token` param, then any generated URLs on the page will also include the `token` param – which is how you are able to navigate around your site within Live Preview and continue seeing the previewed entry showing up in different places.

But Google wouldn’t ever see those URLs by default. My guess is that someone posted a tokenized URL someplace where Google crawled, and then it discovered the tokenized URLs from there. 

Maybe it would be a good idea for Craft to automatically send a `X-Robots-Tag: noindex` header to any request that contains a URL token.

**Comment by brandonkelly** [comment]
Just went ahead and did that. Going forward all tokenized requests will get `X-Robots-Tag: none` (equivalent of `noindex, nofollow`).

**Comment by brandonkelly** [comment]
Craft 3.4.8 is out now with that change.

**Comment by janhenckens** [comment]
Thanks @brandonkelly!
