### ISSUE TITLE
Matrix count error when saving to entries/save-entry with empty matrix field.

### ISSUE THREAD

**Issue by shornuk** [craftcms/cms#5699]
### Description
When saving an entry from the front end with an ajax call to `entries/save-entry` and a Matrix field is not being populated, it returns a count error on the matrix field.

`Setting unknown property: craft\\elements\\MatrixBlock::COUNT(*)`

I'm need to set `<input type="hidden" name="fields[matrixField]" value="">` to bypass this error.

### Steps to reproduce

1. Section contains at least one matrix field.
2. Save an entry via front end form, posting to `entries/save-entry` and don't include any value for a matrix field at all and it will throw the above error. 

### Additional info

- Craft version: 3.4.6.1
- PHP version: 7.2

**Comment by brandonkelly** [comment]
That error was already reported by #5690, and we released Craft 3.4.7 yesterday with a fix :)
