### ISSUE TITLE
Duplicate key name 'plugins_handle_unq_idx'

### ISSUE THREAD

**Issue by joshuabaker** [craftcms/cms#5701]
I’m getting a SQL error whilst trying to update Craft.

Updating from `3.3.20.1` → `3.4.7.1`.

```
    > update in {{%migrations}} ... done (time: 0.001s)
    > create unique index plugins_handle_unq_idx on {{%plugins}} (handle) ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'plugins_handle_unq_idx'
The SQL being executed was: ALTER TABLE `plugins` ADD UNIQUE INDEX `plugins_handle_unq_idx` (`handle`)
```

**Comment by joshuabaker** [comment]
Might be a duplicate of #2807. The problem migration is also `m150403_184247_plugins_table_changes`.

There are _no_ `app` migrations logged in the `migrations` table.

@brandonkelly This project was created 22 May 2019, which post dates [your comment](https://github.com/craftcms/cms/issues/2807#issuecomment-386748556) regarding permissions fluke.

**Comment by joshuabaker** [comment]
I think this was a result of copying the `project.yaml` from another project. The migration rows weren’t created based on the schema value when syncing and are therefore absent from the database.

**Comment by brandonkelly** [comment]
> I think this was a result of copying the `project.yaml` from another project. The migration rows weren’t created based on the schema value when syncing and are therefore absent from the database.

Yeah don’t do that. It’s only safe to use another project’s `project.yaml` file as a _starting point_ for a new project, and even then, only if you are using the exact same `composer.json` & `composer.lock` files and run `composer install`, so Craft and plugins are all installed at the exact same versions as `project.yaml` is expecting.

**Comment by joshuabaker** [comment]
To clarify, that is what I did. Same composer dependencies, project.yaml, templates, and everything else. Just a blank database.

**Comment by brandonkelly** [comment]
Hm, that should definitely not have been the case. Craft is supposed to prepopulate the `migrations` table with all discoverable Craft/plugin migrations on install, so it knows not to run them “again” in the future.

Can you please send your `composer.json`, `composer.lock`, and `project.yaml` files into support@craftcms.com so we can try to reproduce on our end?

**Comment by brandonkelly** [comment]
Just tested installing Craft using an existing `project.yaml` file, and verified that all the project config stuff was in place after install, and also the `migrations` table was full with all expected migration records.

**Comment by joshuabaker** [comment]
It’s got to be something else this end then. Thanks for checking, @brandonkelly.
