### ISSUE TITLE
Why are methods like "_requirePermissionByAsset" in AssetsController Class private?

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#5702]
I am working on module that has controller that extends `AssetsController` class. Unfortunately some methods, like `_requirePermissionByAsset` are set to private and i cannot use them in child class (unless I copy-paste them). 

What is the reason for setting these methods to private?

**Comment by brandonkelly** [comment]
No reason in particular. Just made those protected for the next release :)

**Comment by piotrpog** [comment]
@brandonkelly Thanks!

**Comment by brandonkelly** [comment]
Craft 3.4.8 is out with those changes.
