### ISSUE TITLE
Pruning revisions on Postgresql not working: `HAVING count` should be a subquery

### ISSUE THREAD

**Issue by renzo-s** [craftcms/cms#5712]
While using Postgresql and running `./craft  utils/prune-revisions/index` ` ERROR:  column "count" does not exist`.  Generated sql is;

```sql
SELECT "e"."type", "e"."id", (SELECT count(*)
FROM "revisions" "r"
WHERE "r"."sourceId" = "e"."id") AS "count"
FROM "elements" "e"
HAVING "count" > 10
```

Also per SQL spec, the referenced table should be grouped.

My silly patch to get it working is changing this:
https://github.com/craftcms/cms/blob/c75acb570df35b4593b89e06239f59f772e937b4/src/console/controllers/utils/PruneRevisionsController.php#L59

To this:

```sql
$elements = (new Query())
    ->select([
        'e.type', 'e.id', 'count' => (new Query())
            ->select(['count(*)'])
            ->from(['r' => Table::REVISIONS])
            ->where('[[r.sourceId]] = [[e.id]]')
    ])
    ->from(['e' => Table::ELEMENTS])
    ->groupBy('e.id')
    ->having([
        '>',
        (new Query())
            ->select(['count(*)'])
            ->from(['r' => Table::REVISIONS])
            ->where('[[r.sourceId]] = [[e.id]]')
        ,
        $this->maxRevisions]
    )
    ->all();
```

But you probably shouldn't want the double subquery in there.

PS. This shouldn't break MySQL compatibility.

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just got this fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.9 is out now with the fix.
