### ISSUE TITLE
Layout issues in CP after updating to 3.4

### ISSUE THREAD

**Issue by joshuabaker** [craftcms/cms#5713]
### Description

Layout issues in CP after updating to 3.4.

![craftcms-cp-issues-globals](https://user-images.githubusercontent.com/160484/75162749-ee2bd080-5715-11ea-8689-585dc3ada99c.png)

![craftcms-cp-issues-login](https://user-images.githubusercontent.com/160484/75162755-f08e2a80-5715-11ea-86e4-1f26f4abeb01.png)

It looks like JavaScript is choking trying to find a non-existent `#header-container` element.

### Additional info

- Craft version: 3.4.7.1
- PHP version: 7.3.10

**Comment by joshuabaker** [comment]
The issue was template compilation. The element wasn’t present as a result. The templates weren’t recompiling after deployment.

Should compiled templates be cleared automatically when a version changes like this?

**Comment by brandonkelly** [comment]
Whoa, trippy.

Templates should get recompiled automatically whenever the template file’s modify time is more recent than the compiled version’s. Perhaps your server’s clock is off.

**Comment by joshuabaker** [comment]
Good to know. Thanks, @brandonkelly. 😊 

Will chat to the Fortrabbit guys.
