### ISSUE TITLE
Include DateTime to ContentBehavior or use \DateTime

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#5716]
### Description
The current generated `ContentBehavior` does not `use DateTime;` but generates

```php
    /**
     * @var DateTime|null Value for field with the handle “startDate”.
     */
    public $startDate;
```

so the class `DateTime` cannot be resolved. Would you mind changing that, you only have to include the slash as you do it for other classes

```php

    /**
     * @var \craft\elements\db\UserQuery Value for field with the handle “user”.
     */
    public $user;
```

I know the next thing actually belongs to a separate issue and is not related to the ContentBehavior, but to the `ElementQueryBehavior` but I'll mention it anyway. It has the properties 

```
 * @method self headline(mixed $value) Sets the [[headline]] property
```

So when I do
```php
Entry::find()->headline('foo')->all();
```

PHPStorm cannot resolve `all` because the behavior does not have such a method.
This can be fixed via 
``` 
* @method \craft\elements\db\ElementQuery headline(mixed $value) Sets the [[headline]] property
```
So PHPStorm knows at least an ElementQuery is returned. Same goes for the new "merged" CustomFieldsBehavior

**Comment by brandonkelly** [comment]
Whoops, thanks for pointing that out! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.9 is out now with the fix for this. Note that you will need to delete your current `CustomFieldBehavior.php` file before the change will take effect.
