### ISSUE TITLE
JS error when trying to set click asset crop constraint button

### ISSUE THREAD

**Issue by zizther** [craftcms/cms#5718]
### Description
When trying to crop an image by using the current default options (Unconstrained, Original, Square, 16:9, ...) nothing happens.
When looking at the console log it says

```
Uncaught ReferenceError: $target is not defined at s.constructor._handleConstraintClick (Craft.js:5842)
```

### Steps to reproduce

1. Within the assets section click an asset
2. Click edit, which will open the edit modal
3. Click the crop tab
4. Click on of the preset options within the crop tab

### Additional info

- Craft version: 3.4.8
- PHP version: 7.3.13
- Database driver & version: 
- Plugins & versions:

**Comment by andris-sevcenko** [comment]
Yikes, sorry about that! I just pushed a fix for the next release.

**Comment by zizther** [comment]
Top work @andris-sevcenko 
I say you added the custom crop feature, but is there ability to add any as a custom crop sizes via a config to have as an option for the client to select?

**Comment by andris-sevcenko** [comment]
We discussed it but, ultimately, decided against it. I'll have a dig through conversation archives to see why we ended up discarding that idea and I'll ping back.

**Comment by andris-sevcenko** [comment]
I think we decided not to do it for now because this is really more of a job for image transforms at the template/GraphQL level, and nobody has really requested it. If you feel strongly that you’d like to supply custom crop ratios, go ahead and open a new issue about it.

**Comment by zizther** [comment]
Appreciate you looking into it.

Makes sense, when using the transform and using a focal point.
Was just thinking it maybe easier for the client or content editor to select the correct ratio when looking to crop from the start from within the CMS, this way you know what you are getting, instead of seeing what the transform outputs.

I will have a think and it is seems like it is something of value for the client I will submit a new issue.

**Comment by brandonkelly** [comment]
Craft 3.4.9 is out now with the fix for the JS error.
