### ISSUE TITLE
General config's integer values won't accept environment variable.

### ISSUE THREAD

**Issue by dominikkrulak** [craftcms/cms#5720]
### Description
I have some config settings that is good to set to environment variables in my _.env_ file.

### Steps to reproduce

1. Define environment variable in _.env_ file like `CACHE_DURATION=15778476`
2. Define config setting `'cacheDuration' => getenv('CACHE_DURATION'),`

When saved I get this on page reload:
```
An Error occurred while handling another error:
Exception: DateInterval::__construct(): Unknown or bad format (15778476) in /app/vendor/craftcms/cms/src/helpers/ConfigHelper.php:45
Stack trace:
#0 /app/vendor/craftcms/cms/src/helpers/ConfigHelper.php(45): DateInterval->__construct()
#1 /app/vendor/craftcms/cms/src/config/GeneralConfig.php(1057): craft\helpers\ConfigHelper::durationInSeconds()
#2 /app/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\config\GeneralConfig->init()
#3 /app/vendor/craftcms/cms/src/config/GeneralConfig.php(997): yii\base\BaseObject->__construct()
...
```
### Additional info

- Craft version: Craft Pro 3.4.8
- PHP version: 7.4.3
- Database driver & version: PostgreSQL 12.2
- Plugins & versions: No plugins are enabled.

**Comment by brandonkelly** [comment]
Just typecast it to an int:

```php
'cacheDuration' => (int)getenv('CACHE_DURATION'),
```
