### ISSUE TITLE
Increase 'Time to reserve' for Queue manager

### ISSUE THREAD

**Issue by ryanpcmcquen** [craftcms/cms#5721]
### Description

The default timeout of `300` is not enough to complete resaving all entries, which is necessary for the Craft 3.4.x upgrade.

![Screen Shot 2020-02-25 at 12 14 35 PM](https://user-images.githubusercontent.com/772937/75283900-8edac880-57c8-11ea-9812-00643978f488.png)

I can't seem to find where this is set.

### Steps to reproduce

1. Have a lot of entries.
2. Upgrade to Craft 3.4.x

### Additional info

- Craft version: 3.4.8

**Comment by brandonkelly** [comment]
The 3.4 changelog suggests running `./craft resave/entries --update-search-index` to improve your entries’ search indexes. But that doesn’t run over the queue.

But you can increase the default TTR for queue jobs, by adding this to `config/app.php`:

```php
return [
    'components' => [
        'queue' => [
            'ttr' => 600,
        ],
    ],
];
```
