### ISSUE TITLE
setPasswordPath for front end requests with custom template path

### ISSUE THREAD

**Issue by samhibberd** [craftcms/cms#5722]
For front end set password requests (users without access to the cp) where the URI is defined in general config:
`'setPasswordPath' => 'set-password'`,

And the route in routes.php:
`'set-password' => ['template' => '_views/auth/setPassword'],`

Returns false when hits the template exists check in UsersController and as a result defaults to the cp version of set password.
https://github.com/craftcms/cms/blob/2cb9180c2bed9173133890cf836bb5ab13735a9c/src/controllers/UsersController.php#L1669

Referred to this https://github.com/craftcms/cms/issues/4925#issuecomment-530825752, but it doesn't appear to be playing ball for me. Missing something or potential bug?

- Craft version: 3.4.8

**Comment by brandonkelly** [comment]
99% sure that route is your issue. Try renaming that template to `set-password.twig` at the root of your `templates/` folder.

**Comment by samhibberd** [comment]
It does work if I move it to templates root. 

Should (can) it work with routes defined in routes.php? We have all our auth templates in sub folders `_views/auth/...`  and would be preference not to move them to root if possible.

**Comment by brandonkelly** [comment]
Not currently possible, but I just made it so for Craft 3.5.

I wouldn’t recommend running the 3.5 dev branch unless the project is still in development and will be for the next couple months, but if you want to test this early, change your `craftcms/cms` requirement in `composer.json` to `3.5.x-dev`, and then run `composer update`.

**Comment by samhibberd** [comment]
Thanks @brandonkelly
