### ISSUE TITLE
The users/get-remaining-session-time action is deprecated. Use users/session-info instead.

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#5723]
### Description

I get randomly this deprecated error in production: `The users/get-remaining-session-time action is deprecated. Use users/session-info instead.`.

After reading the stack trace below, it doesn't seems to be related to any template or third-party plugin, so I guess it could be a Craft CMS issue.

```
11	Deprecation error: The users/get-remaining-session-time action is deprecated. Use users/session-info instead.
Called from /deploy-dev/vendor/craftcms/cms/src/controllers/UsersController.php:216
10	craft\controllers\UsersController::actionGetRemainingSessionTime()
9	call_user_func_array([craft\controllers\UsersController, "actionGetRemainingSessionTime"], [])
Called from /deploy-dev/vendor/yiisoft/yii2/base/InlineAction.php:57
8	yii\base\InlineAction::runWithParams(["p" => "admin/actions/users/get-remaining-session-time", "dontExtendSession" => "1"])
Called from /deploy-dev/vendor/yiisoft/yii2/base/Controller.php:157
7	craft\controllers\UsersController::runAction("get-remaining-session-time", ["p" => "admin/actions/users/get-remaining-session-time", "dontExtendSession" => "1"])
Called from /deploy-dev/vendor/craftcms/cms/src/web/Controller.php:178
6	craft\controllers\UsersController::runAction("get-remaining-session-time", ["p" => "admin/actions/users/get-remaining-session-time", "dontExtendSession" => "1"])
Called from /deploy-dev/vendor/yiisoft/yii2/base/Module.php:528
5	craft\web\Application::runAction("users/get-remaining-session-time", ["p" => "admin/actions/users/get-remaining-session-time", "dontExtendSession" => "1"])
Called from /deploy-dev/vendor/craftcms/cms/src/web/Application.php:291
4	craft\web\Application::runAction("users/get-remaining-session-time", ["p" => "admin/actions/users/get-remaining-session-time", "dontExtendSession" => "1"])
Called from /deploy-dev/vendor/craftcms/cms/src/web/Application.php:559
3	craft\web\Application::_processActionRequest(craft\web\Request)
Called from /deploy-dev/vendor/craftcms/cms/src/web/Application.php:270
2	craft\web\Application::handleRequest(craft\web\Request)
Called from /deploy-dev/vendor/yiisoft/yii2/base/Application.php:386
1	craft\web\Application::run()
Called from /deploy-dev/htdocs/index.php:21
```

### Steps to reproduce

1. Visit several CP or front-end pages
2. Check `/admin/utilities/deprecation-errors`

### Additional info

- Craft version: Craft Pro 3.4.8
- PHP version: 7.3.11
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Agent 1.1.6, Control Panel Body Classes 2.1.1, Control Panel CSS 2.2.0, Dashboard Begone 1.0.1, Dumper 2.0.0, Embedded Assets 2.2.1, Expanded Singles 1.0.9, Field Manager 2.1.1, Imager v2.4.0, Mandrill 1.3.1, Minify 1.2.9, Neo 2.6.1, Redactor 2.6.0.1, Retcon 2.0.12, Typogrify 1.1.18, Wishlist 1.2.1

**Comment by brandonkelly** [comment]
This is a duplicated of #5392 – though we never really got to the bottom of it. Can you read through that thread and follow up if you have any additional info to add?

**Comment by romainpoirier** [comment]
Sorry for the duplicated.

As far as I can tell:
- This also happened to me in production only;
- This also happened suddenly after an update;
- After another deployment, the error is gone (I didn't had to delete `vendor/` neither `web/cpresources/` folders);

So yep, this could be an issue related old cached files.
