### ISSUE TITLE
Make ActiveRecord _prepareValue optional

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#5725]
### Description

I know I already mentioned that here https://github.com/craftcms/cms/issues/5653#issuecomment-586630446 and I do not think you'll do it, but I kindly ask again for a feature request to make ActiveRecords `_prepareValue` function optional right now. I made the mistake and used your `ActiveRecords` plus all my own `ActiveRecords` exends yours directly as well and it is much work to change it. I tried to update my current Craft instance to 3.4 but it requires many changes in many classes and much work.

I'm working with the [Yii2 Rest API ](https://www.yiiframework.com/doc/guide/2.0/en/rest-quick-start) that uses `ActiveRecords` to provide/create/change data and the values of those ActiveRecords are returned directly via [Serializer](https://www.yiiframework.com/doc/guide/2.0/en/rest-response-formatting#data-serializing). Before your update everything worked very well together with Yii2, their data wrappers and `TypeSettingBehaviors`. The REST API in yii2 works directly with those records and the two of them are coupled.

[Quote from Yii2](https://www.yiiframework.com/doc/guide/2.0/en/rest-quick-start#summary)
> Resources are represented as data models which extend from the yii\base\Model class. If you are working with databases (relational or NoSQL), it is recommended you use ActiveRecord to represent resources.

The [Resources](https://www.yiiframework.com/doc/guide/2.0/en/rest-resources#resources) should be yii\base\Model or its child classes (e.g. yii\db\ActiveRecord) as well
> yii\db\ActiveRecord provides powerful DB data access and manipulation support, which makes it a perfect fit if your resource data is stored in databases.

Now I have to remove every instance of Craft out of my `ActiveRecords` because of the way you understand them is quite different than the way Yii2 handles them.
Plus I need to copy your `ActiveRecords` as well and let them extend Yii2 or mine instead of yours. I'm not really sure what the real benefit of this function is or if there might be a work around without that much effort for you.

**Comment by brandonkelly** [comment]
`craft\db\ActiveRecord` doesn’t really do anything besides the `_prepareValue()` stuff, so why not just update your active record classes to extend `yii\db\ActiveRecord` instead? The effort would be about the same as adding a `protected $prepareValues = false;` property to them.
