### ISSUE TITLE
 PHP Warning – yii\base\ErrorException preg_match(): Internal pcre_fullinfo()

### ISSUE THREAD

**Issue by zzseba78** [craftcms/cms#5726]
### Description
Getting this error constantly in the Admin section. It´s a clean new installation

![Captura de Pantalla 2020-02-27 a la(s) 09 39 19](https://user-images.githubusercontent.com/5558563/75446018-514f7a00-5945-11ea-9768-ffde63b10e2a.png)

### Additional info

- Craft version: 3.4.8
- PHP version: 7.2.22
- Database driver & version: MySQL 5.7.26
- Plugins & versions: Redactor

**Comment by brandonkelly** [comment]
Please find that error in `storage/logs/web.log`, and post the full stack trace that follows it.

**Comment by zzseba78** [comment]
It´s quite huge...

[web.log](https://github.com/craftcms/cms/files/4261862/web.log)

**Comment by brandonkelly** [comment]
I don’t see anything about `preg_match()` in there. Can you search through the other `web.log.X` files and see if you can find the error in them? If not check `phperrors.log`.

**Comment by zzseba78** [comment]
In phperrors.log i found this ( github doesn´t let me upload the file ).
`[27-Feb-2020 13:35:58 UTC] PHP Warning:  preg_match(): Internal pcre_fullinfo() error -4 in /Applications/MAMP/htdocs/BestTravel/vendor/craftcms/cms/src/helpers/DateTimeHelper.php on line 684
[27-Feb-2020 13:35:58 UTC] PHP Warning:  preg_match(): Internal pcre_fullinfo() error -4 in /Applications/MAMP/htdocs/BestTravel/vendor/craftcms/cms/src/helpers/DateTimeHelper.php on line 684
[27-Feb-2020 13:36:29 UTC] PHP Warning:  preg_match(): Internal pcre_fullinfo() error -4 in /Applications/MAMP/htdocs/BestTravel/vendor/craftcms/cms/src/helpers/DateTimeHelper.php on line 684`

**Comment by brandonkelly** [comment]
Try placing a `test.php` file in your webroot with this code:

```php
<?php
preg_match('@([0-9]{1,2}).([0-9]{1,2}).([0-9]{1,2})@', phpversion(), $match);
echo 'PHP version : '.$match[1].'-'.$match[2].'-'.$match[3];
```

Then access it from your browser (e.g. `http://example.test/test.php`). Does it output a version number such as `7-4-1`, or do you get a warning?

**Comment by zzseba78** [comment]
@brandonkelly It output `PHP version : 7-2-22`

**Comment by angrybrad** [comment]
Guessing this is a PHP bug?  Can you try changing to a newer version of PHP in MAMP and see if that helps?

**Comment by zzseba78** [comment]
Hi @angrybrad ! I will try tomorrow, the error is random, now i´m working with sections and fields and everything works fine by now. I will update MAMP tomorrow!
Thanks.

**Comment by zzseba78** [comment]
@angrybrad Update current mamp to php 7.4.1, if everthing goes right i will close this issue, thanks!
