### ISSUE TITLE
Plugin payment issue

### ISSUE THREAD

**Issue by Moucky** [craftcms/cms#5728]
I'm having trouble paying for some plugin licenses after making the website public. After clicking "Resolve" on the top bar and going through the payment process Craft seems to just get stuck and the errors in the images below are displaying in the console (this is from 2 seperate attempts).

![Screen Shot 2020-02-28 at 9 06 12 AM](https://user-images.githubusercontent.com/18316383/75482655-1fecb200-5a0a-11ea-9a8d-11adedf8bce0.png)
![Screen Shot 2020-02-28 at 8 46 18 AM](https://user-images.githubusercontent.com/18316383/75482661-224f0c00-5a0a-11ea-981e-809e4e15d8f9.png)

Craft Version: Craft Solo 3.4.7.1

**Comment by Moucky** [comment]
Update on this, I ended up successfully paying through the plugin store in the browser from the Craft ID site. I was not adding any of the billing information and when on the plugin store it told me first name and last name were required. This was not showing when paying through the craft admin so I suspect this is why the payment may not have been working.

**Comment by benjamindavid** [comment]
Thank you for reporting this issue, it should be fixed in the next release.

**Comment by brandonkelly** [comment]
3.4.10 is out now with the fix.
