### ISSUE TITLE
Relations: :empty: / :notempty: won't work on sourceElement

### ISSUE THREAD

**Issue by JeanLucEsser** [craftcms/cms#5730]
### Description

It looks like this kind of related query won't work forcing us to make a first query to get all articles ids and then passing those ids in the sourceElement (those ids can be a lot and it could be a problem when working with pagination):

```
{% set authorsWithArticles = craft.entries({
  section: 'authors',
  relatedTo: [{ sourceElement: ':notempty:', field: 'author' }]
}).all() %}
```

This could be related to issue https://github.com/craftcms/cms/issues/3538

Another thing, would be nice (maybe I missed something) to be able to pass a query in the sourceElement/targetElement of a relation as Craft already seems to be joining the necessary tables... for instance, something like `{sourceElement: {section: 'articles', lead: true, where: {...}}}`.

Thoughts ?

**Comment by brandonkelly** [comment]
`relatedTo` doesn’t support `:empty:` / `:notempty:` keywords – that’s exactly what #3538 is requesting.

> Another thing, would be nice (maybe I missed something) to be able to pass a query in the sourceElement/targetElement of a relation as Craft already seems to be joining the necessary tables... for instance, something like `{sourceElement: {section: 'articles', lead: true, where: {...}}}`.

You can pass an element query into `element`/`sourceElement`/`targetElement`, yes:

```twig
{% set authorsWithArticles = craft.entries()
    .section('authors')
    .relatedTo({
        sourceElement: craft.entries().section('articles').lead(true).where('...'),
        field: 'author'
    })
    .all() %}
```
