### ISSUE TITLE
Element query equivalent of "filter" filter

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#5734]
Currently, if we use [filter](https://twig.symfony.com/doc/2.x/filters/filter.html) filter on element query object, array is returned - instead of another element query object that can other element query methods chained to it.

**Comment by brandonkelly** [comment]
Not sure I’m following. `|filter` is meant to work with an array, so there’s no way it could work with an element query besides having the query actually execute itself and return an array of elements, then you filter out the results you don’t want, into a new array.

If you want to define an element query, and then define a new element query with additional parameters on it, you should use the [clone()](https://docs.craftcms.com/v3/dev/functions.html#clone) function.

```twig
{% set newsQuery = craft.entries()
    .section('news') %}

{% set recentArticles = clone(newsQuery)
    .orderBy('postDate desc')
    .limit(5)
    .all() %}
```
