### ISSUE TITLE
Running project-config/sync --force on a migrated craft 2 project results in MySQL duplicate errors

### ISSUE THREAD

**Issue by FreekVR** [craftcms/cms#5735]
### Description
I've recently migrated a Craft 2 site to Craft 3.4(.8) and am in the process of enabling project config for the project. However, after first enabling project config and having run project-config/rebuild, I am running into an issue where it appears that `project-config/sync` with "`--force`" is trying to insert duplicate records for my singles in the `craft_elements_sites` table.

Running the command gives me errors like these:
```
 error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '61483-2' for key 'craft_elements_sites_elementId_siteId_unq_idx'
The SQL being executed was: INSERT INTO `craft_elements_sites` (`elementId`, `siteId`, `slug`, `uri`, `enabled`, `dateCreated`, `dateUpdated`, `uid`) VALUES (61483, 2, 'apply', 'apply', 1, '2020-02-28 15:44:03', '2020-02-28 15:44:03', '3d6b9fc4-97b0-4bd1-828b-f1e1b276e534')
```

```
error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '61484-1' for key 'craft_elements_sites_elementId_siteId_unq_idx'
The SQL being executed was: INSERT INTO `craft_elements_sites` (`elementId`, `siteId`, `slug`, `uri`, `enabled`, `dateCreated`, `dateUpdated`, `uid`) VALUES (61484, 1, 'workshops-overview', 'werkplaatsen', 1, '2020-02-28 15:46:43', '2020-02-28 15:46:43', '7e8393ad-1b75-4150-a89b-ec7c78dba572')
```

These slugs correspond to singles on my site, so it appears that it isn't properly detecting existing records here for some reason.

### Steps to reproduce

1. Create a site in Craft 2
2. Configure the site with at least two languages
3. Create some singles
4. Translate some of these singles with different slugs and other texts per language
5. Migrate the site to craft 3
6. Enable project-config and run project-config/rebuild
7. Now run project-config/sync --force

### Additional info

- Craft version: 3.4.8
- PHP version: 7.2
- Database driver & version: MySQL 5.7
- Plugins & versions: Neo, Seomatic, Seo et al (doesn't seem to be related to plugins)

**Comment by FreekVR** [comment]
I'm doing some further inspections of this issue.

It seems that the elementId that project config is trying to use DOES exist in `craft_elements_sites`, however there is NO CORRESPONDING RECORD in `craft_elements` with the same ID.

I'm doing some checks on the pre- and post Craft DB dumps to see where this orphaned record is coming from. It may be a database issue in the old Craft 2 dump or something that was created in the Craft 2>3 migration rather than being an issue with the project-config.

**Comment by FreekVR** [comment]
It looks like there's tons of orphaned records in `craft_elements_sites` after applying the migration from Craft 2 to 3. I have to do some more isolated testing as this database is quite huge, but I'm finding about 55k records where the elementId in this table doesn't exist as `elements.id`, using this query:

```
SELECT elements.id AS elements_id, elementId, slug, uri FROM craft_elements_sites 
LEFT JOIN craft_elements elements ON elements.id = craft_elements_sites.id
WHERE elements.id IS NULL
```

The old `craft_elements_i18n` table had 35k records. The new `craft_elements_sites` now has about 105k, of which at least 55k seem to serve no purpose.

Any ideas what may be causing these duplicates?

**Comment by jamesmacwhite** [comment]
Might not help, but have you verified the DB dump at all? I've had some funky errors on Craft 3 migrations which had me chasing ghosts for a while, before realising the DB export itself was either corrupt or captured during when an element may have been updated/saved (given it's a live Craft 2 project currently), before you go chasing things, maybe confirm the DB snapshot is good.

**Comment by FreekVR** [comment]
Hey James,

I'm pretty sure about the integrity of the dump, but I'll do a smaller scale test with the migration over the weekend, as it's pretty hard to debug where things are coming from on this scale. I WAS able to verify in the C2 site/dump all the `elements_i18n` are using an elementId that exists in `elements`, so it doesn't seem to be anything on that end.

**Comment by brandonkelly** [comment]
Sounds a bit like https://github.com/craftcms/cms/issues/5604#issuecomment-590499567 . Running `./craft project-config/rebuild` ended up solving it for him, before updating, but that won’t help here if you’re coming from Craft 2. Can you please send that database backup over to support@craftcms.com, so we can try to reproduce from our end?

**Comment by FreekVR** [comment]
I just re-did the entire migration and project config generation and was unable to reproduce the issues I was having earlier with the forced sync failing.

I will re-check on my work laptop after the weekend to see if I can backtrace the issue, I was having some timeouts/failures with the post-migration entry-resave, so maybe that corrupted the DB somehow.

Thanks for thinking along thus far ;)

**Comment by brandonkelly** [comment]
Alright, will close this for now. Let me know if you discover any new info.
