### ISSUE TITLE
Make appending elements to Twig arrays/objects easier

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#5737]
To append element to Twig array/object, we need to use `merge` filter.

```
{% set array = array|merge({key: value}) %}
````

This is far from perfect. I realize this is probably intentional on part of Twig creators - to discourage people from using complicated logic in templates and make them use other parts of frameworks that handle PHP code. In Craft however we write more Twig code than in for example Symfony. Many sites dont use any custom PHP at all.

So, i think that Craft should mimic php functionality for appending stuff to arrays/objects:
```
{% set array['key'] = value %}
```
Or:
```
{% set array[] = value %}
```

**Comment by brandonkelly** [comment]
That is a language-level change, so something you would need to request over at https://github.com/twigphp/twig/issues

**Comment by benface** [comment]
@brandonkelly Any chance you could revisit this, as Twig has made it clear in the past that they don't want to add this feature?

- https://github.com/twigphp/Twig/issues/825
- https://github.com/twigphp/Twig/issues/1252

^ About that second one: Craft added `|push` recently-ish, so I guess you're not completely against it. :P

**Comment by brandonkelly** [comment]
It’s not something we could do without completely overwriting the `set` token parser and node classes – something I don’t want to do.

**Comment by benface** [comment]
Ah, I apologize, I didn't understand the reason was a technical one, but that makes sense. Well, there's still #5976 to be considered. 😇
