### ISSUE TITLE
"Save as new entry" should modify the title the same way duplicating an entry does

### ISSUE THREAD

**Issue by andreimoment** [craftcms/cms#5739]
### Description

Duplicating an entry by Save new entry results in a different title from when doing so by duplicating it in the list. Also, the slug gets modified differently from the title.

* Make the title naming consistent for both types of duplication: `Original title - Copy`
* Make the slug name change reflect the title name change: `original-slug-copy`

`Original title - Copy` is already used as the convention in most filenaming systems and will be easily recognized by CMS users.

### Steps to reproduce

Right now, if I open an entry and click on Save as a new entry:
- the new entry gets created and saved
- the title is identical to the original entry
- the slug is like the original entry with an added "-1" at the end.

example: 
 
I open `Corgi Day at Huntington Dog Beach` with `corgi-day-at-huntington-beach` slug and Save as a new entry, I get a new entry with the exactly same title: `Corgi Day at Huntington Dog Beach` and this slug: `corgi-day-at-huntington-beach-1`

The new title is identical to the old one and if left unchanged that's a problem. The slug gets a silently added "-1" at the end (which is very often out of sight and not ideal but a different issue). 

If instead of opening an entry and saving it as a new one, I check an entry in the entries list and do gear icon > duplicate, i will get " copy" at the end of the title and the same slug modification:

`Corgi Day at Huntington Dog Beach copy` and an "-1" added to the slug: `corgi-day-at-huntington-beach-1`

which is better, but the title should get ` - Copy` instead of ` copy` and the slug should get `-copy` and not `-1` for consistency.

So, ideally, in both cases (duplicating via Save as a new entry and CP list > check content item + gear icon > create duplicate) we will see

`Corgi Day at Huntington Dog Beach - Copy` as the title, and
`corgi-day-at-huntington-beach-copy` as the slug

### Additional info

- Craft version: 3.4.8
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Craft does in fact add “copy” to the title when you duplicate an entry from the Entries index page.

When you click “Save as new entry”, that is doing two things: 1) duplicates the entry; and 2) applies the posted form data to the duplicate, and then re-saves it. The title is included in that post data. So it wouldn’t be appropriate for Craft to assume that you want “copy” appended to the title, when you have already told it what the title should be, per the form data.

Craft will only append `-1` to the slug in an effort to give the entry a unique URI, and only if the section’s Entry URI Format setting contains `{slug}`. (If the Entry URI Format doesn’t contain `{slug}` and the duplicate entry doesn’t have a unique slug, then it will just be saved as disabled instead, as of Craft 3.4.6.)
