### ISSUE TITLE
new Categories seem now to refuse to be hierarchical

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#5741]
### Steps to reproduce

1. Create new Category Group
2. Add a Category - Cheese
3. Add another - Dutch, selecting Cheese as parent
4. Dutch is added, but at top level rather than as child
5. No markers appear to left of names to allow shifting hierarchy
6. no js errors
7. no web.log errors, at least with devMode false
8. originally this was on dev-master, but I switched to 3.4.9 released; didn't change or help

### Additional info

PHP version	7.2.25
OS version	Linux 4.15.0-72-generic
Database driver & version	MySQL 5.7.28
Image driver & version	Imagick 3.4.4 (ImageMagick 6.9.7-4)
Craft edition & version	Craft Pro 3.4.9
Yii version	2.0.32
Twig version	2.12.5
Guzzle version	6.5.1
Imagine version	1.2.3-dev

**Comment by brandonkelly** [comment]
Still working on my end. Verify that when you click “Create a new child entry”, the “Parent” setting is already preselected when the New Entry form loads.

**Comment by narration-sd** [comment]
Yes, I'd tried all variations of that sort of thing before raising an issue.

As well had neglected to mention I was getting a validation error in the entry Editor: 'This field is not set to a valid Category group', though of course all looked well with that.

However.  

This morning I thought of an old issue that continues to show up, which is that after some buildup of cache of its own, particular around screens that might fail at times in developing, Chrom(ium) can often lose its mind in strange ways. And it was Canary, which is worst at this.

Thus:
- tried changing the field to an Asset, save, change back to a Category.
- now the validation error in entry edit went away
- tried adding one more child, hard parent specify in create dialog. Saves, exists, but still no hierarchy in Categories
- however, the (Vue) app shows that there is indeed hierarchy
- cleared entire Canary browser cache
- now Craft CP shows hierarchy properly again, including all creations of Friday. Nice map.

Conclusion: all of this caused by browser, if with no Console action (there never is for these kinds of Chromium foul-up). Browser in this state didn't allow your CP js to create the Category Group (or add to it) correctly, thus the validation problem on it. Same browser state didn't allow _display_ of hierachy of Categories, even though it was present, thus the hard fail for issue.

Side point: of course I checked a very similar other project on slightly different Craft version, and hierarchy was fine there. Again, think I've seen this before, and not without its logic since it's to do with cache -- bad browser state can be for just a particular site, not affect others. 

Cheers
