### ISSUE TITLE
Cannot share database between localhost and remote staging

### ISSUE THREAD

**Issue by joshua-martin** [craftcms/cms#5744]
### Description

We share a database for localhost + staging (as the client or our content editors might be modifying/editing content at the same time as development). This used to work fine, but now one of them is 'authoritative', so as soon as I run any migrations or project sync on the staging environment, it throws `The craft_info table is missing its row` on the localhost, and vice-versa.

If I pull the database down from the remote and install it locally and use that local db in the .env file, it's fine. So there is complete parity in the code and complete parity in the db, just if I try to connect my localhost to the remote DB it wont work, even though it works with an identical DB locally.

### Steps to reproduce

1. Connect from localhost to a remote db in your .env file
2. Run a composer update or project sync on the remote

### Additional info

- Craft version: 3.4.8
- PHP version: 7.2.28
- Database driver & version: MySQL 5.7.29

**Comment by angrybrad** [comment]
The only time Craft will throw that error is it if can 1) connect to the database fine with the given database settings in `config/db.php` 2) find the `craft_info` table fine, but 3) it gets no results when querying for a row in that table (there should always be one rows on a Craft installation.

https://github.com/craftcms/cms/blob/develop/src/base/ApplicationTrait.php#L621-L624

Are you able to take the credentials for staging that you're using locally and connect via a standalone MySQL client outside of Craft?

**Comment by joshua-martin** [comment]
Yeah that’s what so strange about this one! I can connect to it remotely from a GUI fine—I can also connect to it on the remote fine from localnost but only if it’s a *fresh* import of the DB, as soon as I run composer update or project sync on the remote it stops working and starts returning that error. I’ll try to get a full steps for you tomorrow just to double check that is what I’m doing.

**Comment by joshua-martin** [comment]
I've set up a new database on our remote and left it empty.

- If I access the instance from local and go through the `Install Craft` procedure, I can access the database locally, but if I try to connect to it from the instance on staging it throws `The craft_info table is missing its row`
- If I delete the database, access the instance from staging and go through the `Install Craft` procedure, I can access the database on staging, but If I try to connect to it from the instance locally it throws `The craft_info table is missing its row`

Some thoughts:

If I update the `->one()` to `->all()[0]` in `ApplicationTrait.php` then it starts throwing `No primary site exists`.

I checked the lines https://github.com/craftcms/cms/blob/develop/src/services/Sites.php#L1158-L1162 and dumped `$results` which is an empty array. If I comment out the `->andWhere()` then it starts to return the primary site result correctly, but then the database just hangs until it times out.

**Comment by angrybrad** [comment]
> If I access the instance from local and go through the Install Craft procedure, I can access the database locally, but if I try to connect to it from the instance on staging it throws The craft_info table is missing its row

So in theory, if you provided us access to the staging site along with the necessary credentials, we should be able to reproduce this locally, correct?  If so, could you send those access creds over to support@craftcms.com?

**Comment by msbit** [comment]
@angrybrad 

> it gets no results when querying for a row in that table

Actually when searching for a row with id 1; if the table is emptied then re-filled, might the id still autoincrement, pushing the lowest id up?

**Comment by angrybrad** [comment]
@msbit ahhh... fair point. Do you have a row in the `info` table, but it has an `id` other than `1`, @joshua-martin?

**Comment by brandonkelly** [comment]
@msbit as of Craft 3.4 the `info` row **must** have an ID of `1` – see #5222.

**Comment by msbit** [comment]
@brandonkelly That doesn't bother me so much; did you want to wait until @joshua-martin has confirmed that this is the actual issue before closing?

**Comment by joshua-martin** [comment]
It does have an ID of 1, so it’s not that.

**Comment by angrybrad** [comment]
@joshua-martin Here's the underlying error message that's occurring when you try to connect remotely. It should be getting logged in the Craft `storage/logs` files, but kind of gets swallowed in the UI:

    SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

That occurs when Craft is trying to query the info table with a very simple query:

    SELECT * FROM `craft_info` WHERE `id`=1 LIMIT 1

Unfortunately, it's one of those unhelpful MySQL error messages that could come from a hundred different things, but there's a whole page in their docs for debugging why it might occur: https://dev.mysql.com/doc/refman/8.0/en/gone-away.html

**Comment by joshua-martin** [comment]
Thanks for the investigation, Brad. Feels weird it would be a MySQL error though given the thoughts from my investigations below. Can you think of any reason why using `one` would cause it to go awry but `all` wouldn’t?

> Some thoughts:
> 
> Locally, I updated the `->one()` to `->all()[0]` in `ApplicationTrait.php`, but then it starts throwing `No primary site exists`.
> 
> I checked the lines https://github.com/craftcms/cms/blob/develop/src/services/Sites.php#L1158-L1162 and dumped `$results` which is an empty array. If I comment out the `->andWhere()` then it starts to return the primary site result correctly, but then the database just hangs until it times out.

**Comment by angrybrad** [comment]
Other than MySQL is bonkers sometimes? :)

Your change would change the query from:

    SELECT * FROM `craft_info` WHERE `id`=1 LIMIT 1

to:

    SELECT * FROM `craft_info` WHERE `id`=1

Why that would work remotely from PHP whereas the other one doesn't I have no idea.

**Comment by joshua-martin** [comment]
Just wanted to drop a line and say thanks for the investigation + summary, @angrybrad. Turns out there was a mis-configuration on the server so it was half-allowed/half-denied (hence why the server was going awry). We've got the issue resolved now and can connect to staging from localhost again :)

J
