### ISSUE TITLE
Issue updating to 3.4

### ISSUE THREAD

**Issue by phillmorgan28** [craftcms/cms#5747]
### Description

I am unable to complete an update from Craft 3.3 to 3.4. I am receiving a migration error when attempting to update the database. This is the first attempt to update from 3.3.11

`One of Craft CMS’s migrations failed.

Database Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'channel' in 'field list'
The SQL being executed was: INSERT INTO craft_queue (channel, job, description, timePushed, ttr, delay, priority) VALUES ('queue', 'O:34:\"craft\\queue\\jobs\\UpdateSearchIndex\":7:{s:11:\"elementType\";s:20:\"craft\\elements\\Entry\";s:9:\"elementId\";s:1:\"2\";s:6:\"siteId\";s:1:\"1\";s:12:\"fieldHandles\";a:0:{}s:11:\"description\";N;s:30:\"\0craft\\queue\\BaseJob\0_progress\";i:0;s:35:\"\0craft\\queue\\BaseJob\0_progressLabel\";N;}', 'Updating search indexes', 1583227400, 300, 0, 1024)

Migration: craft\migrations\m190913_152146_update_preview_targets

Output:

Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'channel' in 'field list'
The SQL being executed was: INSERT INTO craft_queue (channel, job, description, timePushed, ttr, delay, priority) VALUES ('queue', 'O:34:\"craft\\queue\\jobs\\UpdateSearchIndex\":7:{s:11:\"elementType\";s:20:\"craft\\elements\\Entry\";s:9:\"elementId\";s:1:\"2\";s:6:\"siteId\";s:1:\"1\";s:12:\"fieldHandles\";a:0:{}s:11:\"description\";N;s:30:\"\0craft\\queue\\BaseJob\0_progress\";i:0;s:35:\"\0craft\\queue\\BaseJob\0_progressLabel\";N;}', 'Updating search indexes', 1583227400, 300, 0, 1024) (/app/craft/vendor/yiisoft/yii2/db/Schema.php:674)
#0 /app/craft/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO cr...')
#1 /app/craft/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('INSERT INTO cr...')
#2 /app/craft/vendor/craftcms/cms/src/queue/Queue.php(536): yii\db\Command->execute()
#3 /app/craft/vendor/yiisoft/yii2-queue/src/Queue.php(196): craft\queue\Queue->pushMessage('O:34:"craft\\que...', 300, 0, NULL)
#4 /app/craft/vendor/craftcms/cms/src/queue/Queue.php(173): yii\queue\Queue->push(Object(craft\queue\jobs\UpdateSearchIndex))
#5 /app/craft/vendor/craftcms/cms/src/services/Elements.php(2168): craft\queue\Queue->push(Object(craft\queue\jobs\UpdateSearchIndex))
#6 /app/craft/vendor/craftcms/cms/src/services/Elements.php(524): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false, true)
#7 /app/craft/vendor/craftcms/cms/src/services/Sections.php(1545): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#8 /app/craft/vendor/craftcms/cms/src/services/Sections.php(755): craft\services\Sections->_ensureSingleEntry(Object(craft\models\Section), Array)
#9 /app/craft/vendor/craftcms/cms/src/services/ProjectConfig.php(1083): craft\services\Sections->handleChangedSection(Object(craft\events\ConfigEvent))
#10 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#11 /app/craft/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#12 /app/craft/vendor/craftcms/cms/src/services/ProjectConfig.php(657): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#13 /app/craft/vendor/craftcms/cms/src/services/ProjectConfig.php(1073): craft\services\ProjectConfig->processConfigChanges('sections.eb06d5...')
#14 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#15 /app/craft/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#16 /app/craft/vendor/craftcms/cms/src/services/ProjectConfig.php(654): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#17 /app/craft/vendor/craftcms/cms/src/services/ProjectConfig.php(478): craft\services\ProjectConfig->processConfigChanges('sections.eb06d5...', true, '')
#18 /app/craft/vendor/craftcms/cms/src/migrations/m190913_152146_update_preview_targets.php(54): craft\services\ProjectConfig->set('sections.eb06d5...', Array)
#19 /app/craft/vendor/craftcms/cms/src/db/Migration.php(52): craft\migrations\m190913_152146_update_preview_targets->safeUp()
#20 /app/craft/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#21 /app/craft/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m190913_152146_update_preview_targets))
#22 /app/craft/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#23 /app/craft/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(510): craft\services\Updates->runMigrations(Array)
#24 /app/craft/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#25 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#26 /app/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#27 /app/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#28 /app/craft/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('migrate', Array)
#29 /app/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#30 /app/craft/vendor/craftcms/cms/src/web/Application.php(290): yii\base\Module->runAction('updater/migrate', Array)
#31 /app/craft/vendor/craftcms/cms/src/web/Application.php(645): craft\web\Application->runAction('updater/migrate')
#32 /app/craft/vendor/craftcms/cms/src/web/Application.php(222): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#33 /app/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#34 /app/craft/web/index.php(21): yii\base\Application->run()
#35 {main}`

### Steps to reproduce

1. Update from Craft 3.3.11 to 3.4
2. Attempt to access admin area and update database

### Additional info

- Craft version: 3.3.11 to 3.4
- PHP version: 7.4
- Database driver & version: 10.4.11-MariaDB-1:10.4.11+maria~bionic-log - mariadb.org binary distribution
- Plugins & versions: From composer.json: 
```
    "vlucas/phpdotenv": "^2.4.0",
    "aelvan/inlin": "^2.1.1",
    "craftcms/redactor": "^2.4.0",
    "nystudio107/craft-seomatic": "^3.2.28",
    "craftcms/commerce": "^2.1.10",
    "spicyweb/craft-neo": "^2.5.7",
    "craftcms/commerce-stripe": "^2.1.0",
    "dolphiq/redirect": "^1.0.23",
    "barrelstrength/sprout-forms": "^3.5.1",
    "mpdf/mpdf": "^8.0",
    "wrav/simplesharing": "^1.0.5",
    "yiisoft/yii2-redis": "^2.0",
```

**Comment by mtwalsh** [comment]
If you're able to start over perhaps try upgrading to the latest version of 3.3 so `3.3.20.1` and then upgrading from that to 3.4.

**Comment by phillmorgan28** [comment]
Hi,

Thanks for the response. That was my first thought as well, but I'm afraid that didn't work. However, I was able to go from 3.3.11 to 3.4.9 directly without the issue. It must have been fixed in a release since 3.4.

Closing as the issue is resolved, however it may be worth keeping as a guide for others trying the same thing!

**Comment by brandonkelly** [comment]
@phillmorgan28 Do you remember what version you were trying to upgrade to originally?

**Comment by engram-design** [comment]
@brandonkelly Came across this when going from Craft 2 to Craft 3.4.0, trying to a Neo migration (as per https://github.com/spicywebau/craft-neo/blob/master/docs/craft3.4.md) working. Would've loved to go straight to 3.5.x, but there's content issues with that.
