### ISSUE TITLE
Entry Type tabs do not get their translations

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#5748]
### Description

When editing the `Entry Type` (`/admin/settings/sections/{id}/entrytypes/{id}`), the tab titles are not getting their translations from `translations/{locale}/site.php` (neither `translations/{locale}/cp.php`). Whereas when editing the Entry, these tab titles are translated.

### Steps to reproduce

1. Add a tab's CP translation in a locale file
2. Edit the `Entry Type` and compare the tabs when editing an `Entry`

### Additional info

- Craft version: Craft Pro 3.4.9
- PHP version: 7.1.30
- Database driver & version: MySQL 5.7.26
- Plugins & versions: Agent 1.1.6, Control Panel Body Classes 2.1.1, Control Panel CSS 2.2.0, CP Field Inspect 1.1.3, Dashboard Begone 1.0.1, Dumper 2.0.0, Embedded Assets 2.2.1, Expanded Singles 1.0.11, Field Manager 2.1.1, Imager v2.4.0, Mandrill 1.3.1, Minify 1.2.9, Neo 2.6.2, Redactor 2.6.0.1, Retcon 2.0.12, Typogrify 1.1.18, Wishlist 1.2.1, XML Sitemap 1.2.0

**Comment by brandonkelly** [comment]
This is expected, because that is where you define the tab names in the first place.
