### ISSUE TITLE
When an Asset fails to save, `null` is returned, instead of a Response

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/cms#5750]
Well, the title isn't really the _issue_, it's more that the method signature wants a `Response` returned, but the action still uses `null` to fall back to the original URL.

https://github.com/craftcms/cms/blob/249462063be8129e9cf1f074502e3863d5a4a3c3/src/controllers/AssetsController.php#L206

This should probably just be relaxed, to not specify a return type?

FYI, [first reported](https://discordapp.com/channels/456442477667418113/456442867163070466/684528370280693842) by `abuer` on Discord.

**Comment by andris-sevcenko** [comment]
This has been fixed in Craft 3.4.10.1
