### ISSUE TITLE
Account activation system message is missing

### ISSUE THREAD

**Issue by michaelhue** [craftcms/cms#5753]
### Description

While adding user registration to an existing Craft 3 project, I noticed registering new accounts (with email confirmation enabled) results in an error. Craft tries to compose a message from the `account_activation` template but the template is missing, producing the error.

Checking __Utilities > System Messages__ I can see only three templates:
- `verify_new_email`
- `forgot_password`
- `test_email`

### Steps to reproduce

1. Create a register form
2. Enable user registration and email confirmation
3. Try to register a new user via the frontend

### Additional info

- Craft version: `Craft Pro 3.4.9`
- PHP version: `7.4.1`
- Database driver & version: `MySQL 5.5.5`

### Stack Trace

```
yii\base\ErrorException: Trying to get property 'subject' of non-object in /src/vendor/craftcms/cms/src/mail/Mailer.php:99
Stack trace:
#0 /src/vendor/craftcms/cms/src/web/ErrorHandler.php(74): craft\web\ErrorHandler->handleError()
#1 /src/vendor/craftcms/cms/src/mail/Mailer.php(99): craft\web\ErrorHandler->handleError()
#2 /src/vendor/yiisoft/yii2/mail/BaseMessage.php(49): craft\mail\Mailer->send()
#3 /src/vendor/craftcms/cms/src/services/Users.php(336): craft\mail\Message->send()
#4 /src/vendor/craftcms/cms/src/controllers/UsersController.php(1160): craft\services\Users->sendActivationEmail()
#5 /src/vendor/yiisoft/yii2/base/InlineAction.php(57): craft\controllers\UsersController->actionSaveUser()
#6 /src/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/src/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#7 /src/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#8 /src/vendor/craftcms/cms/src/web/Controller.php(178): craft\controllers\UsersController->runAction()
#9 /src/vendor/yiisoft/yii2/base/Module.php(528): craft\controllers\UsersController->runAction()
#10 /src/vendor/craftcms/cms/src/web/Application.php(291): craft\web\Application->runAction()
#11 /src/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction()
#12 /src/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest()
#13 /src/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#14 /src/web/index.php(21): craft\web\Application->run()
#15 {main}
```

**Comment by brandonkelly** [comment]
> Checking **Utilities > System Messages** I can see only three templates:
> 
> * `verify_new_email`
> * `forgot_password`
> * `test_email`

Well that seems wrong… there should be 4 messages listed on that page:

- When someone creates an account
- When someone changes their email address
- When someone forgets their password
- When you are testing your email settings

Do you have a module or plugin that is doing something with the [EVENT_REGISTER_MESSAGES](https://docs.craftcms.com/api/v3/craft-services-systemmessages.html#event-register-messages) event?

**Comment by michaelhue** [comment]
Welp you are right, I had a custom module adding a message in a bad way. Sorry about that.
