### ISSUE TITLE
The button "add category" still shows when branch limit is reached

### ISSUE THREAD

**Issue by michtio** [craftcms/cms#5762]
### Description

When you set a branch limit for the user in the control panel, and they reach their maximum selected categories the "add category" button will still display. This leaves users more often than not confused as in that they think they can add multiple categories, but then are left even more confused that when the popup opens and they select an additional one, it doesn't show up in the list.

### Steps to reproduce

1. Set branch limit of a category entry field
2. Add the maximum allowed number of categories, and still see the "add category" button

<img width="384" alt="category-branch-limit" src="https://user-images.githubusercontent.com/5818021/76012803-310c5600-5f17-11ea-8a86-5e9bb6f46b22.png">
<img width="278" alt="category-entry-field" src="https://user-images.githubusercontent.com/5818021/76012810-336eb000-5f17-11ea-9944-9319ea765109.png">

### Additional info

- Craft version: 3.4.9

**Comment by brandonkelly** [comment]
This is covered by #2423 already :)
