### ISSUE TITLE
mailer/test command reports wrong transport type when mailer configuration is overriden

### ISSUE THREAD

**Issue by nstCactus** [craftcms/cms#5763]
### Description
When overriding the mailer configuration in _config/app.php_, the `craft mailer/test` command "lies" about the transport type in the test email: it gives the transport type from the Craft config (stored in database & project config) instead of the actual transport type.

### Steps to reproduce
1. Go to the control panel > Settings > Email and set the transport type to sendmail.
1. override the mailer configuration in _config/app.php_. Set a valid configuration using any transport type but sendmail
2. in a terminal, run `craft mailer/test`
3. Enter your email when prompted
4. Answer yes to the question "Do you want to test using the current email settings?"
5. Check you emails, you should have one from your Craft site
6. Open it, it should mention the transport type used to send the email is sendmail

### Additional info

- Craft version: 3.4.4.1
- PHP version: 7.2

### Analysis

`MailerController::actionTest()`, uses the output of `App::mailSettings()` (the Craft email configuration stored in the database & project config) to determine the transport type to report.  
When the email is actually sent, in `MailerController::_testEmailSending()`, the `Craft::$app->getMailer()` call will instantiate the mailer component using the configuration in _config/app.php_.

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just got this fixed for Craft 3.5.
