### ISSUE TITLE
Change preview button into a menu button

### ISSUE THREAD

**Issue by raptureaid** [craftcms/cms#5764]
### Description
Ever since the changes that introduced auto-saving of drafts, I've observed a number of users inadvertently create a multitude of drafts for an entry because they clicked the preview button multiple times while on the current entry. This then leads to user confusion and frustration as they have many drafts and uncertainty over which draft has the edits they want when returning to the entry at a later time.

Since _current_ is the standard starting point when accessing an entry, it is not always clear to users when entries may have drafts available. It would be best if the user had more control to select from existing drafts or create a new draft when interacting with the live preview feature.

### Suggested fix:

1. Change preview button into a menu button (similar to _share_ when there are multiple preview targets)
2. List existing drafts for the user to select as options to preview
3. Provide option to create a new draft (from current)

**Comment by brandonkelly** [comment]
As of Craft 3.4, simply visiting an entry and clicking “Preview” won’t create a draft anymore, until the user starts actually changing content (see #5201). So make sure you’re running that.

**Comment by raptureaid** [comment]
I just checked again, following the steps below without selecting/editing any fields, and ended up with multiple drafts. 

Steps followed::
1. Navigate to an entries structure
2. Open the entry
3. Click 'Preview'
4. Once preview loads, click 'Close Preview'
5. Click entries to return to the entries list
6. Repeat steps 2-5

### Additional info

- Craft version: Craft Pro 3.4.9
- PHP version: 7.2.27
- Database driver & version: MySQL 5.6.43

**Comment by brandonkelly** [comment]
Just noticed that I could reproduce that as well, on entries with a Redactor field that contained 2+ paragraphs. Looks like it was (re-)introduced in craftcms/redactor@270a4998920536dd8a159ee2fd7941bbdb46ffb9. Just pushed e3a3b96cc16d950274a8f1b923083c8e19a87b37 for the next Craft release which fixes it.
