### ISSUE TITLE
Default Value not saving

### ISSUE THREAD

**Issue by willard** [craftcms/cms#5765]
### Description
we created a custom module to add default value on creating a new entry, this was working before 3.4.9, when expecting 'Form Data' in params, the fields with default value are not present

`Event::on(
      View::class,
      View::EVENT_BEFORE_RENDER_TEMPLATE,
      function (TemplateEvent $event)
      { 
          ...
          $event->variables['entry']->setFieldValues($somevalues);
      }
    );`

![image](https://user-images.githubusercontent.com/544756/76122939-4c359f00-5fc5-11ea-8a17-0d7b980a2493.png)

![image](https://user-images.githubusercontent.com/544756/76122997-7c7d3d80-5fc5-11ea-8ec4-c4b3e6c14189.png)

### Steps to reproduce

1.
2.

### Additional info

- Craft version: 3.4.9
- PHP version: 7.2.21
- Database driver & version: MySQL 8.0.17
- Plugins & versions:

**Comment by brandonkelly** [comment]
How are you setting the default value?

**Comment by willard** [comment]
We are listening on the event **EVENT_AFTER_RENDER_TEMPLATE** and check if this is new entry, then we set the default values using **setFieldValues** 

`$event->variables['entry']->setFieldValues($somevalues)`

the form inputs is showing with the default values, but i think the data are not recognize, im investigating the javascript's formData and the default value are missing..

**Comment by brandonkelly** [comment]
Yeah so as of Craft 3.4, entry forms will only submit the values that _changed_. Since you are setting the value before JavaScript initializes the form, as far as it knows, the default value you’ve set is what the field was _already_ set to, so it gets excluded from the save request.

You can force Craft to compare your default value to the real empty value by doing this:

```php
Craft::$app->view->setInitialDeltaValue('fieldHandle', null);
```

**Comment by willard** [comment]
thank you @brandonkelly.. appreciate your help
