### ISSUE TITLE
Routes not working/visible until clearing caches

### ISSUE THREAD

**Issue by TimvanDijkhuizen** [craftcms/cms#5766]
### Description
First of all I'm not sure what caused this to happen but I do know what fixed it. 

So I was trying to create a new route from the CP settings page and it all seemed to work fine. However, my route didn't work and I didn't understand why. After a while I refreshed my routes page and noticed all of my routes were gone. I placed some debug statements and found out Craft was using an (outdated) cached version of the project config. After clearing my caches the new routes appeared (I created it multiple times lol).

As far as I can tell Craft doesn't clear that cache unless you're working with the (yml) file. It doesn't seem to reach the cache clearing code when the project config is disabled.

### Steps to reproduce

1. Create a new route under some unknown condition
2. Refresh the routes page and the route will be gone because of a outdated project config.
3. Clear caches and the route(s) appear and work on the frontend.

### Additional info

- Craft version: 3.4.9
- PHP version: 7.2.18
- Database driver & version: Mysql 5.7.26

**Comment by brandonkelly** [comment]
Did this happen locally or on a production environment?

**Comment by TimvanDijkhuizen** [comment]
> Did this happen locally or on a production environment?

This happened on my local installation. I have not yet experienced this bug ever since I cleared my caches. It all seems to work fine now.

I recently cloned this repo so maybe caused it.

**Comment by brandonkelly** [comment]
Very strange. Not really sure what to make of it… routes are updating immediately as expected on my local environment. Will close, but let me know if you uncover any additional info.

**Comment by John1128** [comment]
Hi brandonkelly. How are you?
Yesterday, I deployed craftcms project 2.9.2 on my locally. But the route is not working for me.
For example, if I type as localhost in my browser(http://localhost), it's working but if I click any item on home page(http://localhost/collection), it's not working, I'm facing Not Found page as default. This project is working on cloud server.
I'm not sure why it's not working when routing.
Please help me.
Thanks!

**Comment by brandonkelly** [comment]
@John1128 Try http://localhost/index.php?p=collection. If that works, then the issue is that you are either missing a `.htaccess` file in your web root that redirects 404 traffic to `index.php` ([example](https://github.com/craftcms/craft/blob/master/web/.htaccess)), or Apache’s [AllowOverride](https://httpd.apache.org/docs/2.4/mod/core.html#allowoverride) directive is disabled.
