### ISSUE TITLE
Author Keyword Not Reserved

### ISSUE THREAD

**Issue by JustJarethB** [craftcms/cms#5769]
### Description
`author` is not a reserved keyword, but there is a default `author` field so it probably should be?

### Additional info

- Craft version: 3.4.9

**Comment by JustJarethB** [comment]
https://github.com/craftcms/cms/issues/2797

**Comment by brandonkelly** [comment]
For posterity, this is [resolved for Craft 3.7](https://github.com/craftcms/cms/issues/2797#issuecomment-859155102).
