### ISSUE TITLE
Add padding-top to .lp-preview-container .lp-preview when @supports(backdrop-filter)

### ISSUE THREAD

**Issue by weotch** [craftcms/cms#5771]
### Description

In https://github.com/craftcms/cms/commit/eca5803c7f368baaac8b8c70c08be026947f4c53 the `header` in the preview UI was changed `position:absolute` when the the browser `@supports` `backdrop-filter`.  The `.lp-preview` also needs a padding top (`54px` looks good to me) because the preview iframe currently is positioned underneath the header.

![](https://p-9WF55W9.t1.n0.cdn.getcloudapp.com/items/mXuqrQ76/Image+2020-03-09+at+9.52.52+AM.png?v=9df16a799f4a159c3add5e72c560e612)

### Steps to reproduce

1. Preview a page

### Additional info

- Craft version: 3.4.9

**Comment by brandonkelly** [comment]
This was already requested in #5547, and fixed for Craft 3.5 via e52e8bd846f57aefbd83757aba755b129aab8052.
