### ISSUE TITLE
New Matrix block doesn't focus on the first field if it's Redactor

### ISSUE THREAD

**Issue by jonlongnecker** [craftcms/cms#5773]
### Description
When I add a new Matrix block while publishing, the text cursor focuses on the text input field even though it's the second field in the block. It's driving my wife crazy when she writes because she just starts typing and realizes later it's not in the right field.
<img width="778" alt="Screenshot 2020-03-09 12 39 36" src="https://user-images.githubusercontent.com/2390/76251557-6c06d600-6204-11ea-8c3b-eacf8c9e7ab9.png">

I believe this is related specifically to the Redactor field, as I have another matrix block with only a Redactor and it isn't focused at all upon creating the new block.
### Steps to reproduce

1. Create a Matrix block with a Redactor field in it
2. Try to publish content with the matrix block

### Additional info

- Craft version: 3.4.9
- PHP version: 7.2.27

**Comment by brandonkelly** [comment]
Fixed for the next release!

**Comment by brandonkelly** [comment]
3.4.10 is out now with the fix.
