### ISSUE TITLE
Matrix fields in categories do not get translated when new sites are added

### ISSUE THREAD

**Issue by hiasl** [craftcms/cms#5775]
### Description
Rows in matrix fields, which are assigned to categories, do not get the existing blocks copied to a new site, which is added at a later time. I would expect it to get the same blocks as the default site.

### Steps to reproduce

1. Create a matrix field e.g. with a single block and a single text field, translation method is default (copy to all sites)
2. Create a new category type and add the matrix field to its fields
3. Manage this new category type and add at least one category
4. Make sure the new category has blocks added in the matrix field
5. Now add a new (multi) site
6. Have a look at the translation of the category in the new site. The matrix field will be empty. I would expect it to get the same blocks as the default site.

### Additional info

- Craft version: tried in 3.4.6.1. and 3.4.9
- PHP version: 7.2

**Comment by brandonkelly** [comment]
What is the Matrix field’s Propagation Method setting set to?

**Comment by hiasl** [comment]
"Save blocks to all sites the owner element is saved in"

**Comment by brandonkelly** [comment]
Thanks, was able to reproduce this, and just fixed it for the next release. The fix will only effect new sites created going forward though. To get the Matrix blocks to get propagated across all existing sites, run this terminal command:

```bash
./craft resave/categories
```

**Comment by brandonkelly** [comment]
3.4.10 is out with the fix for this.
