### ISSUE TITLE
Entry URI format problem

### ISSUE THREAD

**Issue by ljfreelancer88** [craftcms/cms#5778]
### Description
When i created the ff. settings below and try to access site.dev/events or site.dev/events/first-event. It's working fine. But when I changed the "events settings" to "news settings" and try to access site.dev/news/first-event, it's working fine but when I tried to access site.dev/news I got only blank.

[Events Settings]
Entry URI format: events/{slug} 
Templates: events\_single
Events folder files: _single.html, index.html

[News Settings]
Entry URI format: news/{slug} 
Templates: news\_single
Events folder files: _single.html, index.html

### Steps to reproduce

1. Create the [Events Settings]
2. Change the  [Events Settings] to [News Settings]

### Additional info

- Craft version: 3
- PHP version: 7.2
- Database driver & version: MySQL
- Plugins & versions:

**Comment by brandonkelly** [comment]
The events/news index page is going to be unrelated to the URI format you are using for the individual entries.

That is either being routed via a Single section, or just a `news/index.twig` template (or something like that) which is being accessed directly.
