### ISSUE TITLE
Deleting a matrix block removes the button to add one

### ISSUE THREAD

**Issue by rickbergmans** [craftcms/cms#5781]
When both the min and max blocks of a matrix field are set to '1', it is still possible to remove that matrix block _(figure 1)._ When the matrix block is removed, the button to add a matrix block again doesn't show _(figure 2)._

<img width="1171" alt="afbeelding" src="https://user-images.githubusercontent.com/17927472/76423995-eb80da80-63a7-11ea-9e5b-5c2466e9e529.png">

<img width="1144" alt="afbeelding" src="https://user-images.githubusercontent.com/17927472/76424185-313da300-63a8-11ea-9725-099138a52c2e.png">

**Comment by brandonkelly** [comment]
Do you have more than one block type?

**Comment by rickbergmans** [comment]
No, only got one block type

**Comment by brandonkelly** [comment]
Thanks for reporting that. Just got this fixed for the next release.

**Comment by brandonkelly** [comment]
3.4.10 is out now with the fix for this.
