### ISSUE TITLE
Remove package dependency for yiisoft/yii2-shell

### ISSUE THREAD

**Issue by bertoost** [craftcms/cms#5783]
### Description

The package `yiisoft/yii2-shell` is added since Craft v3.4.0 as a dependency in the composer.json. Therefore this package is using other packages which are marked for development. This should not be included in a production environment. Checkout https://psysh.org/ (which is being used).

I encountered this because I mostly use `symfony/var-dumper` as a dev requirement in my projects and I can't update to Craft 3.4 since I use a newer package for VarDumper than this dependency is.

It also should not be included as dev-dependency, since I think this is up to a developer.

**Comment by brandonkelly** [comment]
I have removed this for Craft 3.5, and just released a new `craftcms/craft` starter project update which adds it as a dev dependency (craftcms/craft@b3d2e9ec83326450eb117b01e5e9029ffd24b055).

> It also should not be included as dev-dependency, since I think this is up to a developer.

Everything you get with the `craftcms/craft` project is yours to change, so if you don’t want it you can just remove it from your `composer.json` file after creating a new project. Or fork that repo and start maintaining your own custom starter project, as some people have started doing.

**Comment by bertoost** [comment]
Sounds good to me. Thanks!
