### ISSUE TITLE
Call to undefined method craft\helpers\Stringy::langSpecificCharsArray()

### ISSUE THREAD

**Issue by laurabennett** [craftcms/cms#5785]
### Description
My Craft CMS license has expired but I was attempting to update some plugins and get an error each time I try to run a Composer update from command line.

### Additional info

- Craft version: 3.3.0.1
- PHP version: 7.0.33
- Database driver & version: MYSQL
- Plugins & versions:
"vlucas/phpdotenv": "^2.4.0",
        "craftcms/ckeditor": "1.0.0-beta.2",
        "aelvan/imager": "v2.3.0",
        "barrelstrength/sprout-fields": "3.4.4",
        "ether/seo": "3.6.2",
        "sebastianlenz/linkfield": "1.0.20",
        "verbb/expanded-singles": "1.0.7",
        "craftcms/redactor": "2.4.0",
        "svenjungnickel/redactor-font-awesome": "2.1.1",
        "mmikkel/child-me": "1.1.0",
        "charliedev/advanced-url-field": "1.0.0",
        "doublesecretagency/craft-cpcss": "2.2.0",
        "page-8/craft-manytomany": "1.0.2.2",
        "born05/craft-assetusage": "2.0.1",
        "selvinortiz/patrol": "3.1.3",
        "putyourlightson/craft-dashboard-begone": "1.0.1",
        "nystudio107/craft-minify": "1.2.9",
        "hillholliday/craft-user-manual": "v2.0.2",
        "verbb/cp-nav": "2.0.9",
        "spicyweb/craft-embedded-assets": "2.2.1",
        "verbb/field-manager": "2.1.1"

**Comment by brandonkelly** [comment]
This was fixed in Craft 3.3.1.1, via 417fbbc13a79aa3ae17375a28187c257fe80d5b9.

If you are unable to update due to this error, go into `composer.json` and add this to your `require` object:

```json
"require": {
  "...": "...",
  "voku/stringy": "~5.1.0"
}
```

Then run `composer update`.

Try to remember to remove that line whenever you get around to updating Craft CMS though.
