### ISSUE TITLE
Allow URI site settings for Categories when in Headless Mode

### ISSUE THREAD

**Issue by simeon-smith** [craftcms/cms#5786]
### Description

When you are in headless mode the Site Settings for a category are not displayed. This prevents you from setting URI formats for categories when in headless mode.

This is would be helpful similar to the following previous issues about entries:
https://github.com/craftcms/cms/issues/4520
https://github.com/craftcms/cms/issues/5265
https://github.com/nystudio107/craft-seomatic/issues/485
https://github.com/craftcms/cms/issues/4934
https://github.com/craftcms/cms/issues/4888

### Steps to reproduce

1. Turn on headless mode.
2. Create a category group.
3. No Site Settings are displayed

### Additional info

- Craft version: 3.4.9
- PHP version: 7.2
- Database driver & version: MySQL

**Comment by brandonkelly** [comment]
Whoops, this should have been addressed alongside 51ef26bef8b2aac145b42e237c7b6a1f216e79a3. Fixed now for the next release.

**Comment by brandonkelly** [comment]
3.4.10 is out now with this change.
