### ISSUE TITLE
Template error when using |multisort with arrow functions

### ISSUE THREAD

**Issue by samhibberd** [craftcms/cms#5787]
### Description
Running into a template error when using the `|multisort` filter example in the docs:

``` twig
{% set entries = entries|multisort([
    e => e.author.fullName,
    'title',
]) %}
```

https://docs.craftcms.com/v3/dev/filters.html#multisort

> An array element must be followed by a comma. Unexpected token "arrow function" of value "=>" ("punctuation" expected with value ",").

### Additional info

- Craft version: 3.4.9
- PHP version: 7.3.14

**Comment by brandonkelly** [comment]
Sorry, I guess I just assumed that was possible. Fixed the docs.
