### ISSUE TITLE
Better way to toggle template modes via callback

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#5797]
This seems really clunky:

```
$oldMode = Craft::$app->view->getTemplateMode();
Craft::$app->view->setTemplateMode(View::TEMPLATE_MODE_SITE);
// do stuff
Craft::$app->view->setTemplateMode($oldMode);
```

**Comment by brandonkelly** [comment]
As of Craft 3.4.0, you can pass the template mode directly into `renderTemplate()`, `renderPageTemplate()`, `renderTemplateMacro()`, `doesTemplateExist()`, and `resolveTemplate()`, as an additional argument.

**Comment by timkelty** [comment]
ah perfect!
