### ISSUE TITLE
status('disabled') not working on entries query.

### ISSUE THREAD

**Issue by shornuk** [craftcms/cms#5800]
### Description
I have a disabled entry which I'm trying to get in an entries query.

I though this would do it...

```
{% set entries = craft.entries()
    .status('disabled')
    .all() %}
```
But it doesn't get returned. The only way I can return it is by using `anyStatus()`...
```
{% set entries = craft.entries()
    .anyStatus()
    .all() %}
```

Even trying to get it directly via it's ID doesnt return it.
```
{% set entries = craft.entries()
    .id(29850)
    .one()
%}
```

unless I pass `anyStatus()` to that query.
```
{% set entries = craft.entries()
    .id(29850)
    .anyStatus()
    .one()
%}
```

### Additional info

- Craft version: 3.4.9
- PHP version: 7.2

**Comment by brandonkelly** [comment]
If you have multiple sites, then disabling an entry will disable it at the site level. Unfortunately there’s not a great way to specifically find entries that are _disabled_ at the site level though. There’s the [enabledForSite](https://docs.craftcms.com/v3/dev/element-queries/entry-queries.html#enabledforsite) param, but that will only determine whether to _exclude_ elements that are disabled for the current site when set to `true`; if set to `false` it will not do anything.

`anyStatus()` is just a shortcut for setting `status(null)` and `enabledForSite(false)` – in other words, don’t filter elements based on their status at all, including their site status.

So if you specifically want to only find entries that are _disabled_, you’d have to use `anyStutus()` combined with manually adding a DB condition.

```twig
{% set entries = craft.entries()
    .anyStatus()
    .andWhere(['or', ['elements.enabled' => false], ['elements_sites.enabled' => false])
    .all() %}
```

Spent some time seeing if we could make this better, but unfortunately not having any success.

**Comment by shornuk** [comment]
OK, thanks for the update. Thought I was going mad. I've moved to a custom field that gets a custom status string generated on save. Simpler and does the job. Thanks for the update.

**Comment by rolfkokkeler** [comment]
this worked for me without creating extra fields:

	{% set cond = [
  			  'or',
  				  'elements.enabled = false', 
  				  'elements_sites.enabled = false'
        ] %}
				
        {% set newEvents = craft.entries
            .section('events')
            .anyStatus()
            .andWhere(cond)
            .authorGroupId(['4','5']) 
            .controle(0)
            .orderBy('id')              
        %}
