### ISSUE TITLE
TypeError Exception while saving asset from control panel

### ISSUE THREAD

**Issue by rob-baker-ar** [craftcms/cms#5801]
### Description

`\craft\controllers\AssetsController::actionSaveAsset()` is defined as returning an instance of `\yii\web\Response` but when the call `Craft::$app->getElements()->saveElement($asset)` (around line 244 of `\craft\controllers\AssetsController`) returns false, `actionSaveAsset()` ends up returning `null` if the request does not support JSON causing a TypeError.

This happened for me in the control panel when changing a filename for an asset and hitting "Save" and prevents seeing the error that caused the element to fail in the save process.

### Steps to reproduce

1. Save an asset from the control panel that would trigger an error condition as above when saving the asset (I changed filename, but anything that makes `Craft::$app->getElements()->saveElement($asset)` return false world work)
2. Exception thrown

### Additional info

- Craft version: 3.4.9
- PHP version: 7.2.24
- Database driver & version: MySQL 5.7.29
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
Thank for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
3.4.10.1 is out now with the fix for this.

**Comment by brandonkelly** [comment]
Oops, turns out this was a duplicate of #5750.
