### ISSUE TITLE
Cannot delete matrix blocks

### ISSUE THREAD

**Issue by john-henry** [craftcms/cms#5803]
### Description
Upgraded to 3.4.10 and cannot delete Matrix blocks or fields inside matrix blocks. Flash message says it has but upon reload after save they appear again.

Reverted to 3.4.9 and working again

### Steps to reproduce

1. Delete Matrix block or block -> field and save field
2. They are not deleted and remain in place

### Additional info

- Craft version:3.4.10
- PHP version: 7.2.14
- Database driver & version:MySQL 5.7.24
- Plugins & versions: na

I am not using project config

**Comment by billythekid** [comment]
I have some additional info on this (or a workaround for now @john-henry) If you toggle the top-level "use values as keyword search" before saving, it'll take your changes I think I had it re-save earlier with a change to the top-level description fields too. Seems like it's just not watching for block-level field changes unless there's also a field-level change. HTH

**Comment by niektenhoopen** [comment]
Probably the same cause/issue: I cannot add fields to matrix blocks in 3.4.10. 
In 3.4.9 everything works fine.

**Comment by brandonkelly** [comment]
We’ve tracked this down to bc2cdab938d000c19d92883a0529cd4db1acc716 being the culprit, which is preventing field types’ `afterSave()` methods from getting called, which is where Matrix & Super Table do all their block type saving. We’ll get a hotfix out ASAP, but in the meantime, if you change any of the top-level field settings (Name, Handle, etc.) at the same time, then the block type settings will be saved as well.

**Comment by brandonkelly** [comment]
3.4.10.1 is out now with the fix for this.
