### ISSUE TITLE
Unable to edit matrix fields in 3.4.10

### ISSUE THREAD

**Issue by samhibberd** [craftcms/cms#5807]
### Description

Unable to edit matrix fields after upgrading from Craft 3.4.9 to 3.4.10. Downgraded back to 3.4.9 and was able to save again.

### Steps to reproduce

1. Edit an existing matrix field
2. Add a new field to any block type
3. Save it and it appears to have save correctly (It does prevent save if validation fails)
4. Go back to to the field and changes have not been saved.

### Additional info

- Craft version: 3.4.10
- PHP version: 7.3
- Database driver & version: mariadb

**Comment by brandonkelly** [comment]
This was already reported by #5803, and we just released 3.4.10.1 with a fix.
