### ISSUE TITLE
Degraded performance in CP Assets view for folders with many subfolders

### ISSUE THREAD

**Issue by monachilada** [craftcms/cms#5809]
### Description

The performance of the assets page in the CP when it is asked to open a folder with a lot of subfolders in it is resulting page crashes in Chrome, Firefox and Safari on a recent MacBook Pro. Estimate is about 15k sub folders in the Assets volume that can be seen in the screenshots below.

If the folder has never been opened in the particular browser of choice the page will load ok, but as soon as the attempt to expand the folder is made, this will result in the freeze. Subsequent page loads will then also freeze, as the browser appears to attempt to remember the user preference and have that folder opened, making the assets page essentially unusable 😫.

![Chrome](https://user-images.githubusercontent.com/613183/76983311-7aa86800-693d-11ea-9eb6-c860138822ad.png)
![Firefox](https://user-images.githubusercontent.com/613183/76983318-7da35880-693d-11ea-8778-5f9e1157b604.png)

### Steps to reproduce

1. Have a lot of sub folders in a volume or folder
2. Attempt to expand the folder to show its contents

### Additional info

- Craft version: 3.4.10.1 (Pro)
- PHP version: 7.3.11
- OS version: Linux 4.19.0-0.bpo.6-amd64
- Database driver & version: MySQL 5.5.5
- Image driver & version: Imagick 3.4.3 (ImageMagick 7.0.8-58)
- Plugins & versions: 
    - Control Panel Nav 3.0.8.1
    - CP Field Inspect 1.1.3
    - CraftQL dev-master
    - Do It Yourself widget 2.0.1
    - Embedded Assets 2.2.1
    - Entry Instructions 1.0.7
    - Feed Me 4.2.1.1
    - Mailjet 1.2.0
    - MatrixMate 1.2.5
    - Preparse Field v1.1.0
    - Queue Manager 1.2.0
    - Redactor 2.6.1
    - Relabel 1.3.4
    - SEO 3.2.48
    - Servd Assets and Helpers 1.2.8
    - Tags 1.0.6
    - Typed link field 2.0.0-beta.7
    - Webhooks 2.2.0

**Comment by monachilada** [comment]
Also affects modal asset windows triggered from asset fields, making them also unusable.

**Comment by brandonkelly** [comment]
This is a known issue. We’re considering a couple ways to solve it, such as #1629. I’ll leave this open and update it once we have a solution.

**Comment by brandonkelly** [comment]
This will be resolved in Craft 3.8 and 4.4, thanks to a bit of an asset index redesign that moves subfolders into the element listing, and paginates them alongside your assets. (See the [Rethinking Volume Subfolders](https://craftcms.com/blog/rethinking-volume-subfolders) blog post and PR #12558 for more info.)

**Comment by brandonkelly** [comment]
Craft 3.8 and 4.4 are both out now, with the aforementioned volume folder navigation improvements 🎉
