### ISSUE TITLE
Add a new craft cli command which checks if craft is installed.

### ISSUE THREAD

**Issue by urbantrout** [craftcms/cms#5810]
This would make things easier for automated setups and custom scripts.

For example: Check if craft installed and only then run `./craft migrate/all`

**Comment by urbantrout** [comment]
The PR allows us to create composer scripts like this one:

`"@php craft setup/is-installed && @php craft migrate/all || return 0"`

**Comment by khalwat** [comment]
This would be really useful for CI and for Docker-ized setups

**Comment by brandonkelly** [comment]
Good idea! Just added an `install/check` command for Craft 3.5.
