### ISSUE TITLE
[Feature Request] Add a link to the canonical element edit page on element HUDs

### ISSUE THREAD

**Issue by benface** [craftcms/cms#5812]
There are a few things you can't do directly from an element's HUD but that you can do on the canonical element edit page in the CP, such as:

- View and edit the "metadata" (slug, author, post date, expiry date, created at, updated at, etc.)
- For assets: download and replace the file
- For users: [view and edit the email address](https://github.com/craftcms/cms/issues/4942) and the photo

For that reason, and just as a way to keep a reference to an element or to share it with another author, it would be very useful to link to that page from an element's HUD.

**Comment by Mosnar** [comment]
Duplicates https://github.com/craftcms/cms/issues/3448

**Comment by benface** [comment]
Ah, thanks @Mosnar! I searched before creating this issue but I used the wrong keywords apparently. Just thumb'ed up yours.
