### ISSUE TITLE
[FR] CLI command to uninstall a plugin

### ISSUE THREAD

**Issue by rungta** [craftcms/cms#5817]
### Description

A Craft command to uninstall plugins from the command line, a compliment to the `craft install/plugin [handle]` would be handy.

**Comment by brandonkelly** [comment]
Just added new `plugin/install`, `plugin/uninstall`, `plugin/enable`, and `plugin/disable` actions for Craft 3.5. I’ve also deprecated the old `install/plugin` action in favor of the new one.

**Comment by rungta** [comment]
Super! Thanks Brandon.
