### ISSUE TITLE
SortableFieldInterface for Text Fields

### ISSUE THREAD

**Issue by kerns** [craftcms/cms#5819]
### Description

I've been struggling with a way to enter and store the model year of a car in some way to make it col sortable in cp entries view. My understanding is it lacks this ability, and I don't know if it's an oversight or a technical limitation we can't overcome now. But I thought I would raise the need.

Alternatively, if there was an option to prevent numbers from being comma separated I could use a number field for the year, and then I think it would become sortable? But seeing the year 1974 displayed as 1,974 is a bridge too far. ;)

This is just a feature request and I'm sure I've put it in the wrong place – please admonish/flag/close/relocate accordingly.

**Comment by brandonkelly** [comment]
Just made Plain Text fields sortable for Craft 3.5.
