### ISSUE TITLE
[REQUEST] Add control over compression to the backup systems

### ISSUE THREAD

**Issue by proimage** [craftcms/cms#5822]
Currently the only way to get the DB backups compressed is to select "Download backup" in the backend (or, obviously, to DIY it). But that doesn't affect the file saved on the server, and with MySQL backups often taking up ~10x more space uncompressed than compressed, it would make a huge difference if the admin could elect to have them stored in compressed format server-side:

![image](https://user-images.githubusercontent.com/1027523/77169485-37c3cd00-6ac2-11ea-8231-9b139d5f8382.png)

For the backend, another checkbox would do it:

![image](https://user-images.githubusercontent.com/1027523/77169315-f6332200-6ac1-11ea-9f95-57fa92b9f5d6.png)

And for the terminal, something like `./craft backup/db-tar` or `./craft backup/db-zip`, perhaps?

**Comment by brandonkelly** [comment]
Honestly this probably shouldn’t even be a config setting. Craft should probably just be compressing all backups on save.

**Comment by proimage** [comment]
Works for me. ¯\_(ツ)_/¯

**Comment by brandonkelly** [comment]
Done for Craft 3.5!
