### ISSUE TITLE
Status dropdown does not account for "Enabled Globally"

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#5825]
This entry is disabled globally, but the status dropdown still shows it as green, which is a bit confusing:

![Screen Shot 2020-03-20 at 1 11 53 PM](https://user-images.githubusercontent.com/18329/77188858-07256880-6aad-11ea-9aa7-a06f5637371b.png)

**Comment by timkelty** [comment]
Just realized this is on a 3.1.27 build, so it could be this is fixed?

**Comment by brandonkelly** [comment]
As of Craft 3.4 we aren’t even really ever setting the global status anymore (except to enable it if disabled) when saving multi-site entries. See https://github.com/craftcms/cms/issues/2899#issuecomment-573330898.
