### ISSUE TITLE
Access Current field value within the Field class

### ISSUE THREAD

**Issue by samhibberd** [craftcms/cms#5829]
Does the current field class allow you to access the currently saved value for use throughout the class. in normalizeValue() for example. 

I need to handle things differently/ run some checks on any new data, based on what’s currently saved. I have hunted through the craft source code for an example of something similar but can't see an example of where / how you would achieve this properly, or if it is something that should even be done. 

The normalizeValue() function creates additional complexity as any value accessed creates an infinite loop.

**Comment by andris-sevcenko** [comment]
Are you trying to fetch the previous value of the same field or the value of a different field? Can you elaborate a little bit more on the scenario, please?

**Comment by samhibberd** [comment]
@andris-sevcenko the first one, we are looking to get the previous (currently saved) value of the same field (the field that we are working with) so that we can run some logic if a certain value has changed.

The scenario is a custom field in which we want to use a commerce address (if selected) to populate some of the values on save. The values saved on our custom field do not update if the commerce address that was used to populate the values subsequently changes, although we want to store a reference to commerce address used so we can check the various scenarios when our field is saved.

**Comment by andris-sevcenko** [comment]
Well, the field as an entity is just a container for a given value and does not keep track of much. And I don't think an element itself keeps a track of field history over its lifetime.

I'm not sure I entirely follow your scenario, but have you tried using the [beforeElementSave()](https://docs.craftcms.com/api/v3/craft-base-fieldinterface.html#method-beforeelementsave) method? There you could check the dirty fields on the element using the [getDirtyFields()](https://docs.craftcms.com/api/v3/craft-base-element.html#method-getdirtyfields) method, see if your field changed and then fetch the existing value from the DB.

**Comment by samhibberd** [comment]
I had tried using `beforeElementSave()` to check if the field is dirty and get the value and tweak values if required, but didn't have and success, assume it would look something like:

Grabbing existing element (if not `$isNew`):

``` php
$existingElement = Craft::$app->getElements()->getElementById($element->id);
$existingValue = $existingElement->getFieldValue($this->handle);
$newValue = $element->getFieldValue($this->handle);
```

Updating value:

```
$element->setFieldValue($this->handle, $updatedValue);
```

A quick test does allow me to update values before they are commited to the db, but returning a boolean `false` does not prevent the element save, it should right? (The element is a matrix block owned by an order element, not sure if that related)

**Comment by brandonkelly** [comment]
Yeah looks like you’re on the right path.

If you want to actually abort the block saving, your best chance to do that is during validation, so you can set an error on the field that explains why the save was aborted.

You can do that by adding a [getElementValidationRules()](https://docs.craftcms.com/api/v3/craft-base-fieldinterface.html#method-getelementvalidationrules) method on your field type. For example,

```php
public function getElementValidationRules(): array
{
    return [
        ['validateValue'],
    ];
}

public function validateValue(ElementInterface $element)
{
    // ...
    if (!$validates) {
        $element->addError($this->handle, $error);
    }
}
```

**Comment by samhibberd** [comment]
Thanks @brandonkelly, thats how i've been handling errors to date, i was just expecting it to kill the save if i returned false in from `beforeElementSave()`.

All working nicely on element save, but i also need to run a quick sanity check on the data each time it's accessed. Where is best to check that? Would it be possible in `normalizeValue()`? 

In this case I know that if the value passed to `normalizeValue()` is an array then it must be posted, and if it is a string then it must be from the database. Is that a reliable way to determine where the data is being normalized from? And as such i could then adjust what action i take based on that?

I do have an alternative idea (which involves hooking into a separate element event form elsewhere) and updating the values stored in my field, but it would be nice if possible to handle everything from within the field class.

**Comment by brandonkelly** [comment]
> i was just expecting it to kill the save if i returned false in from `beforeElementSave()`.

Returning `false` from `beforeElementSave()` will prevent the current element from being saved. But if the current element is a Matrix block as in your case, that’s only going to stop _that one block_ from saving; not the entire entry. The only way to prevent the entire entry from being saved is through validation.

> All working nicely on element save, but i also need to run a quick sanity check on the data each time it's accessed. Where is best to check that? Would it be possible in `normalizeValue()`?

`normalizeValue()` will get called whenever a field’s value is _first accessed_. Which is probably close enough to what you’re looking for?

> In this case I know that if the value passed to `normalizeValue()` is an array then it must be posted, and if it is a string then it must be from the database. Is that a reliable way to determine where the data is being normalized from? And as such i could then adjust what action i take based on that?

Sure.

**Comment by samhibberd** [comment]
Thanks @brandonkelly
