### ISSUE TITLE
Accidental double-click detection for element modals

### ISSUE THREAD

**Issue by mildlygeeky** [craftcms/cms#5831]
### Description

If two elements are clicked in quick succession (for example, when quickly removing a number of relationships to assets or entries) the inline element modal is accidentally triggered

### Steps to reproduce

1. See video - quickly remove multiple assets or related entries for the easiest way to see this

### Additional info

- Craft version: 3.x

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/273266/77424247-2a9b2c80-6da7-11ea-9d03-aafa2cc0106c.gif)

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.11 is out now with the fix for this.
