### ISSUE TITLE
Translation method doesn't save properly when creating a new Date/Time field

### ISSUE THREAD

**Issue by benface** [craftcms/cms#5832]
### Steps to reproduce

1. CP > Settings > Fields > New field
2. Name: Test
3. Handle: test
4. Field Type: Date/Time
5. Translation Method: Translate for each site group
6. Save the field.
7. Go back to the field's edit page.

**Expected result:** The Translation Method is still "Translate for each site group"
**Actual result:** The Translation Method is now "Translate for each site"

### Additional info

- Craft version: 3.4.10.1
- PHP version: 7.4.2
- Database driver & version: MySQL 5.7.26

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.
