### ISSUE TITLE
Craft.js error blocking creation of new entries

### ISSUE THREAD

**Issue by roberttolton** [craftcms/cms#5834]
### Description
I have updated an install of Craft 3.3 to Craft 3.4 and I am experiencing an issue when trying to create/save fresh entries.

Within the JS Console is the error:
```
TypeError: Cannot read property 'split' of undefined
```
Relating to: https://github.com/craftcms/cms/blob/2bd24e66d74742ead9a5c18f28e1fa5f0ad5bea3/src/web/assets/cp/src/js/Craft.js#L730

This is blocking a lot of other JS on the same page, meaning the create/save button doesn't work and just has the error: `Cannot read property 'abort' of null`

### Steps to reproduce

I'm unsure of how to reproduce it, since it works locally. But, it was an update from 3.3 to 3.4

### Additional info

- Craft version: 3.4.10.1
- PHP version: 7.4.2
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

```
"require": {
    "craftcms/cms": "3.4.10.1",
    "vlucas/phpdotenv": "^3.4.0",
    "clubstudioltd/craft-asset-rev": "6.0.2",
    "wbrowar/contentstats": "2.1.1",
    "aelvan/imager": "v2.4.0",
    "fruitstudios/linkit": "1.1.11",
    "aelvan/preparse-field": "v1.1.0",
    "nystudio107/craft-seomatic": "3.2.48",
    "craftcms/simple-text": "2.0.2",
    "verbb/super-table": "2.4.6",
    "craftcms/redactor": "2.6.1",
    "aelvan/craft-cp-element-count": "v1.0.1",
    "verbb/navigation": "1.3.6",
    "supercool/buttonbox": "2.0.4",
    "putyourlightson/craft-blitz": "3.5.0",
    "pierrestoffe/craft-language-redirector": "1.3.4",
    "topshelfcraft/environment-label": "3.2.0",
    "nystudio107/craft-minify": "1.2.9",
    "mmikkel/cp-clearcache": "1.0.6",
    "ether/logs": "3.0.3",
    "barrelstrength/sprout-fields": "3.6.1",
    "nystudio107/craft-cookies": "1.1.12",
    "culturejapanmirai/mirai": "*", // custom plugin
    "ether/tags": "1.0.6",
    "doublesecretagency/craft-cpcss": "2.2.0",
    "craftcms/element-api": "2.6.0",
    "superbig/craft3-bugsnag": "2.0.6",
    "indigoviking/jsond": "1.05",
    "ether/simplemap": "3.8.2",
    "nystudio107/craft-retour": "3.1.35",
    "verbb/social-poster": "2.1.0",
    "monachilada/craft-matrixtoolbar": "1.0.6",
    "verbb/smith": "1.1.1",
    "angellco/spoon": "3.5.2"
  },
```

**Comment by roberttolton** [comment]
Seem to have found the culprit.

I was doing `$('#tabs #tab-0').click();` while setting up something in a custom plugin, to make sure the content tab was selected. But doing this too early was causing the error, so moved it into a `setTimeout`.

**Comment by Friksel** [comment]
Having the same issue with Craft 3.4.17.1 (TypeError: Cannot read property 'split' of undefined) 
Should this be fixed in this version, or is a new version with this fix coming in a later release?

**Comment by brandonkelly** [comment]
@Friksel How are you registering your JS code?

**Comment by Friksel** [comment]
@brandonkelly I am not. I only have js on the website frontend, but I am seeing this issue when I'm on the Craft Control Panel only. This project doesn't have my own modules nor plugins. There are third party plugins installed though: Contact Form (2.2.7, Pixel & Tonic), Minify (1.2.10) and Redactor (2.6.1). SEOmatic (3.3.1) is installed as a trial, but disabled, so that shouldn't do anything I'd say.

**Comment by brandonkelly** [comment]
@Friksel Please send your `composer.json` and `composer.lock` files, plus a database backup, over to support@craftcms.com, and we will try to look into it with those.
