### ISSUE TITLE
FR: Option to Set Date Format in the Control Panel

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#5835]
It would be great to have an option to specify the date format for entry post and expiry dates displayed when creating a new entry or viewing entries in the entries index.

Currently dates display in the fixed format of MM/DD/YYYY and it would be nice to be able to change this to YYYY/MM/DD or DD/MM/YYYY.

When you are use to viewing dates in a particular format it can take a bit of mental adjustment to remind yourself that within the craftCMS control panel a date displayed as 1/12/2019 for example is the 12th of January not the 1st of December. This has caught me out a number of times.

**Comment by brandonkelly** [comment]
Hey Rich,

The date format is based on your user account’s preferred language. If you go to the Preferences tab of your account settings, you can change that to “English (United Kingdom)” for example, which will give you a format of DD/MM/YYYY.

By default the available options are based on the languages we translate the control panel into, but if you want to go with Australian English, you can do that by setting your [extraAppLocales](https://docs.craftcms.com/v3/config/config-settings.html#extraapplocales) config setting to:

```php
'extraAppLocales' => ['en-AU'],
```

Then you will be able to select “English (Australian)”.

**Comment by richhayler** [comment]
Hey Brandon,

Apologies, I completely missed this. Thanks for taking the time to point out the config change and also option for Australian English.
