### ISSUE TITLE
Activation email not sent after registration, if “Verify email addresses” is disabled

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/cms#5836]
### Description

If the “Verify email addresses” user setting is disabled, then new users are never sent an account activation email after being registered from the control panel. To access their account, they would need to go through the reset-password flow (initiated either by themselves or an administrator).

### Steps to reproduce

1. Go to Settings → Users → Settings, and disable “Verify email addresses”
2. Register a new user from the control panel, or from a front-end public registration form (if [deferPublicRegistrationPassword](https://docs.craftcms.com/v3/config/config-settings.html#deferpublicregistrationpassword) is enabled)

### Expected result

If registering in the control panel, the registration form should give the user the option to send an activation email immediately. If registering via a front-end public registration form (if [deferPublicRegistrationPassword](https://docs.craftcms.com/v3/config/config-settings.html#deferpublicregistrationpassword) is enabled), an activation email should be sent automatically.

### Additional info

- Craft version: 3.4.10.1

**Comment by bzin** [comment]
Not sure if I am getting this right, but I believe that this forces the `verify` email to be send. 

I am working on an `onboarding` flow on a closed platform where I do not want users to activate their accounts. This should be done explicitly by a CP user. New accounts should always be `pending`.

**Comment by bzin** [comment]
Forget the previous comments, just realise I have control over this by setting `sendVerificationEmail` in my request.

https://craftcms.com/docs/3.x/dev/controller-actions.html#supported-params-3

:)
