### ISSUE TITLE
I can't change the plugin status to enable or disable.

### ISSUE THREAD

**Issue by DandeSuen** [craftcms/cms#5837]
### Description
I can't enable or disable any plugin in my test website.
I tried drop database and delete folder vendor, reinstall databases and plugin, But the plugins still can not disable or enable. I don't know why?

*** installing geomate
*** failed to install geomate: No plugin exists with the handle "geomate".

### Additional info

- Craft version: 3.4.9
- PHP version: PHP 7.3.13-1 ( NTS )
- Database driver & version: mysql 5.7.29-0ubuntu0.18.04.1
- Plugins & versions: All

**Comment by brandonkelly** [comment]
Is this specific to the GeoMate plugin? Are you able to install Redactor, etc.?

**Comment by DandeSuen** [comment]
Hi @brandonkelly ,Not specific to the GeoMate plugin, The redactor was install before heppen this BUG. So, The redactor can not change to disable for now. 
Click the disable button of the redactor, Craft will pop-up, Say `Plugin disabled.`, And Craft console will be refresh. Then the status is still enable of the redactor.

**Comment by brandonkelly** [comment]
The plugins are working as expected though? Besides the fact that you can’t disable them?

**Comment by DandeSuen** [comment]
@brandonkelly The enabled plugins are normal working. But I can't install new plugin, Because I can't enable them.

**Comment by brandonkelly** [comment]
Guessing this is going to be permissions related, or something like that. Please write into support@craftcms.com and we can help you from there.
