### ISSUE TITLE
Need some explanation for how Drafts and Auto-Save Work

### ISSUE THREAD

**Issue by jonlongnecker** [craftcms/cms#5840]
### Description
I am completely confused by what is happening with drafts, versions, and auto-save in the latest version of Craft. 

Right now if I go to edit an entry in normal edit mode and change pieces of content, the "current" dropdown never changes, and there is no indication that anything is being saved.

But if I go into live preview edit mode and edit the same content, then the dropdown starts to show drafts and a green checkmark showing me it's been saved.

Why would editing the entry with or without live preview make a difference here? Why are my changes not being saved or drafts created in the normal edit mode? 

### Additional info
- Craft version: Craft CMS 3.4.10.1
- PHP version: 7.3
- Browser: Safari 13.0.5

**Comment by brandonkelly** [comment]
As of Craft 3.2, entries use a new version of Live Preview which requires that you are editing a draft for changes to show up in the preview pane. So, once you have both A) made any changes to the entry, and B) clicked the Preview button (order is not important), then Craft will automatically create a draft for the entry and start saving changes to the draft.

It’s admittedly a bit confusing since you never manually chose to create a draft, but the benefits are that you no longer have to make a bunch of special logic for Live Preview in your templates anymore, plus it enables the Preview Targets feature and the ability to generally click around throughout your site within the preview pane, and still see your draft content no matter where you are on the site.

**Comment by jonlongnecker** [comment]
Yeah that's pretty confusing. But not really the live preview drafts part. That all makes sense and sounds great. I'd like to know why a new draft isn't automatically created when you start editing in normal mode? Why add another button at the top (that I never even noticed was there, btw) and create more complication for the user to decide if they'd like to save it as a draft or not?

This ties back to one of my original questions that I'm still not clear on. If I am in normal editing mode and start changing content, is that being saved in the background? It looks like it's not right now. Is a draft the only mode that starts live saving? If so why wouldn't it make more sense for the draft to get created by default for all editing (normal or live preview) so that both modes work the same?

**Comment by brandonkelly** [comment]
> Is a draft the only mode that starts live saving?

Correct.

> If so why wouldn't it make more sense for the draft to get created by default for all editing (normal or live preview) so that both modes work the same?

That’s actually how I originally implemented the feature in 3.2.0, but a lot of people complained because there’s a bit of a lag when the draft is first created, and it was getting in the way of quick edits.

**Comment by narration-sd** [comment]
Seems worthwhile to mention #5661 here.

https://github.com/craftcms/cms/issues/5661#issuecomment-589330198 is the last focused comment, while the overall discussion gives a picture of how the Drafts ability could clarify, would think.

**Comment by jonlongnecker** [comment]
@brandonkelly weird - what kind of lag?
@narration-sd yeah I read through that thread before posting and saw other people were confused, too - just not quite about the same thing even though it did sort of up there in the end. From what I can tell in the latest version, it uses the "publish" terminology which I'm ok with. It makes more sense than create.

**Comment by brandonkelly** [comment]
@jonlongnecker depends on the complexity of the content model & number of sites, but even for a simple use case, maybe ~300ms. Enough that it gets in the way of quick edits.

**Comment by johandouma** [comment]
I sent an email recently to Craft support. Brad asked me to post here as well: 

After clicking on save as draft, many times I have pressed ctrl+s, out of habit, to save a draft, and it published it! I also find it confusing that it only enables autosave for entries after saving as a draft or previewing.

I also find that a lot of my clients, even colleagues often don't notice that there are drafts in progress, and people end up modifying the published page, and saving that as a new draft, and we end up with many new drafts, which makes merging very tricky. 

I'm wondering if Craft should always auto save drafts, and then ask which draft/current entry the user would like to edit when they click on an entry.
