### ISSUE TITLE
[GraphQL] relatedTo variable type [Int] and [QueryArgument] conflict

### ISSUE THREAD

**Issue by samput** [craftcms/cms#5841]
### Description
Querying an entry by ID requires that the variable type be [QueryArgument]. However related entries require the variable type to be [Int]

##### Query variable
```graphql
{
  "id": 173
}
```

##### Query [QueryArgument]
```graphql
query Series($id: [QueryArgument]) {
  entry(section: "series", id: $id) {
    id
    title
  }
  pipeline: entries(section:"pipeline", type: ["ongoing", "monthly"], relatedTo: $id) {
    id
    title
  }
}
```
##### Error [QueryArgument]
```json
{
  "errors": [
    {
      "message": "Variable \"$id\" of type \"[QueryArgument]\" used in position expecting type \"[Int]\".",
      "category": "graphql",
      "locations": [
        {
          "line": 1,
          "column": 14
        },
        {
          "line": 6,
          "column": 82
        }
      ]
    }
  ]
}
```

##### Query [Int]
```graphql
query Series($id: [Int]) {
  entry(section: "series", id: $id) {
    id
    title
  }
  pipeline: entries(section:"pipeline", type: ["ongoing", "monthly"], relatedTo: $id) {
    id
    title
  }
}
```
##### Error [Int]
```json
{
  "errors": [
    {
      "message": "Variable \"$id\" of type \"[Int]\" used in position expecting type \"[QueryArgument]\".",
      "category": "graphql",
      "locations": [
        {
          "line": 1,
          "column": 14
        },
        {
          "line": 2,
          "column": 32
        }
      ]
    }
  ]
}
```

### Additional info

- Craft version: 3.4.10.1
- PHP version: 7.3.15
- Database driver & version: MySQL 5.7.24
- Plugins & versions:  Feed Me | 4.2.1.1,  Redactor | 2.6.1

**Comment by andris-sevcenko** [comment]
Yes, that's correct. This is because the `id` can be in the form of `["not", 1, 2, 3]` while the `relatedTo` accepts only ids of elements that must be related.

If you know the field the relationship is used on, you can, however, use that field as the argument instead of using `relatedTo`, and that should also be expecting an array of `QueryArgument` values.

**Comment by samput** [comment]
@andris-sevcenko ah ok that makes sense. Using the field as an argument works perfectly. Thanks for the help!

**Comment by mediabeastnz** [comment]
Can we have an example maybe in the docs. I'm having a similar issue and can't find a good solution / explanation.
For example i'm trying to do this.

```gql
query($id: [Int!], $entryID: [Int!]) {
    entries(section: "items", relatedTo: $id, id: ["not", $entryID]) {
    ...
```

**Comment by mediabeastnz** [comment]
Never mind... figure it out 🤦‍♂️

I've now got 

```gql
query($id: [Int!], $entryID: QueryArgument) {
    entries(section: "items", relatedTo: $id, id: ["not", $entryID]) {
    ...
```

**Comment by andris-sevcenko** [comment]
@mediabeastnz glad you figured it out! I agree that there are some murky things we should clear up in GraphQL. I'll see how soon we can fill those gaps.

**Comment by divsync-nomi** [comment]
query($id: ID!, $entryID: QueryArgument) {
    entries(section: "items", relatedTo: $id, id:$entryID) {
    ...

well like this also works for me
