### ISSUE TITLE
relatedTo doesn't filter out disabled Matrix blocks blocks

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/cms#5849]
### Description

If you are fetching related elements via a Matrix field, such as:

```twig
{% set images = craft.assets().relatedTo([
  { sourceElement: entry, field: 'articleBody.image' }
]).all() %}
```

…the results will include elements that are related via disabled Matrix blocks. Those should be ignored, though.

### Steps to reproduce

1. Create a Matrix field with a nested relational field
2. Attach the Matrix field to a field layout
3. Create two blocks that each contain selected relations
4. Disable one of those blocks
5. Run similar code in the description within a template

The result should only contain relations from the enabled block, not the disabled one.

### Additional info

- Craft version: 3.4.11

**Comment by narration-sd** [comment]
...excellent catch @brandonkelly 🏆

**Comment by architchandra** [comment]
Thanks for fixing this!

**Comment by brandonkelly** [comment]
@narration-sd hah, credit goes to @architchandra for [discovering](https://craftcms.stackexchange.com/questions/33997/additional-criteria-to-filter-status-of-field-passed-into-relatedto) the bug :)

**Comment by narration-sd** [comment]
emojis awarded :)

**Comment by brandonkelly** [comment]
Craft 3.4.12 is out now with this fix.
