### ISSUE TITLE
Html <video> tag UI is missing when page is opened in Chrome

### ISSUE THREAD

**Issue by Stalex89** [craftcms/cms#5850]
### Description

I got UI partially missing (play/pause button, volume, fullscreen mode etc.) while using <video> tag in twig template. The following issue is happening in the Chrome browser. 
Meanwhile the video tag is working properly in Chrome when used, for example, in the Codepen.
The tag was also tested in Firefox and Safari, everything is fine.
Also tried to clear cache and check the browser permissions for the page, but nothing helps.

Can it be some twig issue/incompatibility?  

### Steps to reproduce

1. Install Craft
2. Put the following code inside the body tag of the page:
`<video width="320" height="240" controls><source src="http://media.w3.org/2010/05/sintel/trailer.mp4" type="video/mp4"></video>`
3. Open the page in Chrome browser
4. Check if video controls are visible (play/pause button, volume etc.)

### Additional info

- Craft version: 3.4.11
- PHP version: 7.3.12
- Database driver & version: MySQL 5.7.28
- Plugins & versions: Craft clean installation, no side plugins used

### Screenshots
Screenshot of the video from twig template (taken in Chrome)
![Screenshot 2020-03-28 at 16 37 09](https://user-images.githubusercontent.com/23526237/77826875-8866a600-7112-11ea-8bbb-3176f9746fa6.png)
Screenshot from Codepen (taken in Chrome)
![Screenshot 2020-03-28 at 16 37 44](https://user-images.githubusercontent.com/23526237/77826897-b0560980-7112-11ea-9e10-6862b6f7ebb3.png)
Code
![Screenshot 2020-03-28 at 16 41 44](https://user-images.githubusercontent.com/23526237/77826936-0dea5600-7113-11ea-9204-84e5f5831eb4.png)

**Comment by brandonkelly** [comment]
Craft/Twig won’t make any changes to your HTML. Since there’s no actual Twig code in your template, you could try copying the same HTML into a `video.html` file inside your webroot (the `web/` folder) alongside your `index.php` file, and access that with your browser instead.
