### ISSUE TITLE
.env file format changed but db.php stayed the same

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#5851]
Some time ago, `.env` file format was changed - `DB_DSN` replaced few separate variables. Unfortunetly `config/db.php` file that takes values from env file by default still looks for these old variables. 

This causes problems when we update system and then try to install it on other server, thus generating new `.env` file. Maybe installer should check `db.php` file and if it sees old variable, it should generate `.env` file in old format?

**Comment by brandonkelly** [comment]
We switched to setting `DB_DSN` in Craft 3.4, but [config/db.php](https://github.com/craftcms/craft/blob/master/config/db.php) in the starter project did in fact change at the same time. If you’re maintaining your own starter project, then you will just need to update your `config/db.php` file to set the `dsn` setting, **or** you can stop using the `craft setup` command, and just configure the connection settings in your `.env` file manually. (Craft itself does still support the old `driver`, `server`, `database`, and `port` connection settings, if they are being used.)
