### ISSUE TITLE
Show more verbose error message when project config doesnt match system version

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#5852]
Today i was in situation when old project config file didn't matched system version and installed plugins. 

`craft cms HTTP 503 – Service Unavailable error` showed up, without further explanation what was happening. Eventually I discovered that it was project config issue, but maybe in such case some more verbose error message should be displayed?

**Comment by andris-sevcenko** [comment]
This is in line with how Craft sites react if there are migrations to run, which is also HTTP 503. Was this because you had to sync the incoming `project.yaml` changes?

**Comment by piotrpog** [comment]
@andrelopez Actually, there was message about needing to sync changes. 

I had these situations, and that was not one of them - because I opened the control panel URL and still saw only a generic error message.

I solved this by just removing the old project config file.

**Comment by brandonkelly** [comment]
This has been resolved in Craft 3.5.6. Now Craft only checks for incompatible schema versions when it’s applying YAML changes (which is optional in the first place now), and clearly lists which things have issues.
