### ISSUE TITLE
[feature request] Add support for webp image transforms.

### ISSUE THREAD

**Issue by wrux** [craftcms/cms#5853]
### Description
When creating image transforms you can select image format, but there is no option for webp images. Is there any plans for implementing this in core?

I am aware that there are other plugins for this but they introduce a lot of extra code. It also looks like Imager is no longer maintained.

**Comment by Mosnar** [comment]
This is a great idea - webp has wide adoption at this point and is essentially a requirement for a good page speed score. The plugins available right now are great; but, can be a bit overkill if we're just looking to support webp.

Should this feature be implemented, I think there would need to be some additional Twig helpers to ensure the browser supports webp and the asset should be converted to a webp (i.e. not a gif)

@wrux For what it's worth, Imager has evolved into [Imager X](https://plugins.craftcms.com/imager-x)

**Comment by brandonkelly** [comment]
This has come up before (#1545), but I agree at this point we should have built-in support for it.

**Comment by doifeellucky** [comment]
Will this also allow for the creation of png, jpg or gif from a webp as part of a transform?  I'm currently having to use a dedicated second field using png's for this in conjunction with <picture> to support Safari.  Unless there's a way I can do this already.  Thanks.

**Comment by lpbouvier** [comment]
@brandonkelly Adding this feature for [3.5](https://github.com/craftcms/cms/milestone/5) would be awesome!

**Comment by piotrpog** [comment]
@brandonkelly 
Will there also be helper functions for detecting webp server support and webp browser support, like these imager plugin has?

**Comment by timrosskamp** [comment]
Just a sidenote: Transforming images to webp isn't mentioned in the docs, but we've been transforming jpeg images to webp for a while now and it seems to work well in Craft as long as your server has the required php extensions (gd libraray if I'm not mistaken).

Using `image.getUrl({ width: 800, height: 600, format: 'webp' })` in our templates created a webp version from a jpeg image just fine and has a noticeable decrease in filesize.

**Comment by piotrpog** [comment]
@timrosskamp @brandonkelly 
Just tested it - and indeed, it works!
So, why it is in open issues? :)

**Comment by andris-sevcenko** [comment]
There are [browsers that don't support it yet](https://caniuse.com/#feat=webp), and you'd need to generate fallback images for them, anyway, and having two transforms to generate the same transformed image in two different formats is not a pattern we'd like to encourage.

So, we'll have to discuss this internally a bit to figure out the _best_ approach here. For now, you can still specify that directly in templates using unnamed transforms, keeping in mind that the server might not support it.

**Comment by piotrpog** [comment]
@andris-sevcenko 
About browser without webp support - personally, I just use `<picture>` element with two `<source>` elements - one for webp, one for another format. Sources have `type` attribute set, so browsers can pick format they support. For example:

```
<picture>
<source type="image/webp" srcset="x.webp">
<source type="image/jpeg" srcset="x.jpg">
<img src="x.jpg">
</picture>
```

By the way, I remember that some time ago `webp` transforms didn't worked in native Craft. Was this support added recently?

**Comment by andris-sevcenko** [comment]
> By the way, I remember that some time ago webp transforms didn't worked in native Craft. Was this support added recently?

The support is determined by underlying capabilities of GD/Imagick (whichever Craft is using), so it's probable that your server configuration has changed since then.

> About browser without webp support - personally, I just use unnamed transforms and <picture> element with two <source> elements - one for webp, one for another format. Sources have type attribute set, so browsers can pick format they support. 

Right, this is possible and doable with unnamed transforms and you can reduce transform setting duplication in the template with Twig, but to pull this off with a _named_ transform (which is the real issue here, I think), you would have to create two transforms in the control panel, which is far from ideal.

**Comment by andris-sevcenko** [comment]
> I guess the only thing we need is some function that would inform us if the current server supports webp - like serverSupportsWebp that Imager (x) uses.

That's not related to the exact issue here but makes total sense to me. I'll make sure this makes it into Craft, soon!

**Comment by timrosskamp** [comment]
> to pull this off with a named transform (which is the real issue here, I think), you would have to create two transforms in the control panel, which is far from ideal.

That's a good point. A possible solution could be an option to override the named transform in your template. For example:

```html
<source type="image/webp" srcset="{{ asset.getUrl('namedtransform', { format: 'webp' }) }}">
<source type="image/jpeg" srcset="{{ asset.getUrl('namedtransform') }}">
```

That way we avoid the duplication of named transforms.

**Comment by piotrpog** [comment]
> That's not related to the exact issue here but makes total sense to me. I'll make sure this makes it into Craft, soon!

Great! I'm working on plugin that simplifies `<picture>` element creation, and such function would simplify my code a bit, I would not need to do it manually.

**Comment by andris-sevcenko** [comment]
Alright.

@piotrpog a04df43dc17ac2ae26898d37e24cc92891eea65d adds the `getSupportsWebP()` method to the `Images` service.

@timrosskamp I just implemented your suggestion for extending transforms.

So, as of a04df43dc17ac2ae26898d37e24cc92891eea65d, it's possible to do 

```twig
{% set transform = {handle: 'myTransform'} %}

<picture>
	<source type="image/jpeg" srcset="{{ asset.url(transform) }}">	

	{% if craft.app.images.supportsWebP %}
		<source type="image/webp" srcset="{{ asset.url(transform, {format: 'webp'}) }}">
	{% endif %}
	
	<img src="asset.url(transform)">
</picture
```

* The transform to extend does not need to be a named transform.
* Extending a transform returns a new transform object.

With all of this, I feel it's safe to close this issue.

This will be a part of Craft 3.5.

**Comment by brandonkelly** [comment]
Just tweaked the way you override transform settings a bit. Now instead of specifying the overrides as a 2nd argument on `getUrl()`, you can specify it inline from the 1st argument, like so:

```twig
<source type="image/webp" srcset="{{ asset.getUrl({
    transform: 'namedtransform',
    format: 'webp',
}) }}">
```

**Comment by NixonGit** [comment]
@brandonkelly Could this be extended to the new `getSrscet` (https://github.com/craftcms/cms/issues/5774) method and possibly the transform eager loading?

Can open as a separate issue if you prefer.

**Comment by brandonkelly** [comment]
@NixonGit Probably, if you could open a new issue that would be helpful though.
