### ISSUE TITLE
Getting gateway time-out error when trying to install a large project.yaml file

### ISSUE THREAD

**Issue by nmsdvid** [craftcms/cms#5855]
### Description
Hello there, I'm getting gateway time-out error when trying to install a large project.yaml file. After trying to refresh the page a couple of times its seems the installation finished and everything works as expected.  My project yaml file is around 4000 lines. 

<img width="733" alt="Screenshot 2020-03-29 at 11 07 19" src="https://user-images.githubusercontent.com/1606990/77846886-1beeb400-71b1-11ea-9da7-21a35946f02e.png">

### Steps to reproduce

1. Install Craft 
2. Add content into project.yaml
3. Sync changes

### Additional info

- Craft version: 3.4.11
- PHP version: 7.4.3
- Database driver & version: MySQL 8.0.19

**Comment by brandonkelly** [comment]
“Gateway” here will either mean the web server (nginx) or a load-balancer—but not PHP. Which means its out of PHP/Craft’s control.

I’d recommend reverting to a database backup from before the sync, if you can, and trying again, but this time use the `./craft project-config/sync` command in your terminal, so you can bypass this time limit.
