### ISSUE TITLE
Making Element Link Plugin part of core?

### ISSUE THREAD

**Issue by terryupton** [craftcms/cms#5857]
### Description
Just a question - would you consider making this little plugin <https://github.com/marionnewlevant/craft-element_link> as part of Craft core?
https://github.com/marionnewlevant/craft-element_link

Simply it creates a link the element if clicked.
it works in conjunction with crafts native double click for in situ popup editor for element links.

<img width="570" alt="Screenshot 2020-03-29 at 13 46 58" src="https://user-images.githubusercontent.com/5698596/77849480-c7a0ff80-71c3-11ea-8f69-44e20cd5d080.png">

**Comment by benface** [comment]
Related: https://github.com/craftcms/cms/issues/3448

**Comment by brandonkelly** [comment]
This is basically resolved for 3.7! The edit links aren’t directly inline in the relation fields, but the editor slideouts now have them. See #8017.
