### ISSUE TITLE
[Improvement Request] Automatically redirect to `baseCpUrl` if accessing the CP from another domain

### ISSUE THREAD

**Issue by benface** [craftcms/cms#5860]
I have a multi-site install with different domain names for different sites, and right now it seems that I am able to access the CP from any of them, which is less than ideal because:

1. It seems to confuse Craft's license enforcement mechanism, which displays a red banner saying that I'm "running Craft Pro with a Craft Solo license" (this doesn't happen when I visit the CP from the primary site's domain name).
2. It can be confusing to clients, because it kinda gives the impression that they are editing the content of the site whose domain name they're on, but that's not necessarily true.

I tried setting the `baseCpUrl` config setting to the primary site's domain name, but the result is far from perfect: you can still go to any domain's CP URL (`/admin`) and it doesn't redirect to the `baseCpUrl`, so the two issues mentioned above are still issues for the first request to the CP. Also (and I just discovered this while typing this issue), there seems to be a major problem with `baseCpUrl` if you're not logged in: trying to login at `/admin` from any domain other than the one used in the `baseCpUrl` doesn't work. The spinner appears but you are never redirected to the dashboard. Looking at the console, I see this error:

```
XMLHttpRequest cannot load http://dev.primary-domain.com/index.php?_path=admin/actions/users/login due to access control checks.
```

Thank you!

**Comment by brandonkelly** [comment]
> 1. It seems to confuse Craft's license enforcement mechanism, which displays a red banner saying that I'm "running Craft Pro with a Craft Solo license" (this doesn't happen when I visit the CP from the primary site's domain name).

The only way I can reproduce this is when running Craft Pro as a trial, and it happens because the permission to run Craft as a trial is cached on a per-hostname basis.

> I tried setting the `baseCpUrl` config setting to the primary site's domain name, but the result is far from perfect: you can still go to any domain's CP URL (`/admin`)

I can’t reproduce that. If `baseCpUrl` is set to `http://cms.craft3.test` and I visit `http://craft3.test/adin`, I’m immediately redirected to `http://cms.craft3.test/dashboard`. You’re not seeing the same thing? What version of Craft are you using?

**Comment by benface** [comment]
> The only way I can reproduce this is when running Craft Pro as a trial, and it happens because the permission to run Craft as a trial is cached on a per-hostname basis.

Ah, you're right, I had it running as a trial. Just switched to a valid Pro license and I'm not getting this error anymore. But I'm in local dev (with a `dev.` subdomain); wouldn't I be getting an error that the license belongs to another domain name in production?

> I can’t reproduce that. If baseCpUrl is set to http://cms.craft3.test and I visit http://craft3.test/admin, I’m immediately redirected to http://cms.craft3.test/admin/dashboard. You’re not seeing the same thing? What version of Craft are you using?

No, not seeing a redirect at all, and any request made to the `baseCpUrl` (including logging in but if I'm already logged in: checking for updates, fetching the "Craft News", etc.) results in a CORS error (`XMLHttpRequest cannot load ... due to access control checks`). And if I "Disable Cross-Origin Restrictions" in my browser, these requests then result in a CSRF error:

> 2020-03-31 11:31:00 [-][-][-][error][yii\web\HttpException:400] yii\web\BadRequestHttpException: Unable to verify your data submission. in /project/vendor/yiisoft/yii2/web/Controller.php:190

Please note that I'm using two completely different domain names; one is not a subdomain of the other. But I did try with your example of a `cms.` subdomain for the `baseCpUrl` and then accessing the CP from a non-subdomain URL, and the result was the same: no redirect, all AJAX requests fail due to CORS or CSRF.

I am using Craft CMS 3.4.11. Thanks Brandon!

**Comment by benface** [comment]
Ugh, sorry @brandonkelly, I just re-read what you wrote:

> I can’t reproduce that. If baseCpUrl is set to http://cms.craft3.test and I visit http://craft3.test/admin, I’m immediately redirected to http://cms.craft3.test/admin/dashboard.

And yes, I'm seeing the same thing, because it looks like `/admin` always redirects somewhere (whether it's `/admin/login` or `/admin/dashboard`), and of course it would use the `baseCpUrl` then. For some reason I thought that's what I was doing when I wrote my first post, but looks like what I was actually doing to reproduce the issue is replace the domain of a "final" (non-redirect) CP URL. For instance, assuming `baseCpUrl` is `http://dev.primary-domain.com` and I had a secondary `secondary-domain.com` site, I would go to `http://secondary-domain.com/admin/dashboard`, and then there is no redirect and you can see all the issues I describe above. Sorry about that!

**Comment by brandonkelly** [comment]
> But I'm in local dev (with a `dev.` subdomain); wouldn't I be getting an error that the license belongs to another domain name in production?

Yeah, if Craft happened to make any API requests while you were on the wrong domain.

> looks like what I was actually doing to reproduce the issue is replace the domain of a "final" (non-redirect) CP URL.

Right ok, that makes sense. And in that case I can see how that CORS issue would occur, since the action URLs that Ajax requests use will be based on the `baseCpUrl`, not the current URL. So yeah, I’ll look into getting the request redirected automatically. Will do it for 3.5 though, as it would be a bit of a change in behavior that could have unexpected consequences.

**Comment by benface** [comment]
Thanks Brandon! In the meantime, I wrote the following code in a custom module to do the redirect myself:

```php
// Force the CP to use the primary site's domain
if (Craft::$app->getRequest()->getIsCpRequest()) {
    $primarySiteBaseUrl = Craft::$app->getSites()->getPrimarySite()->getBaseUrl();
    if (strpos(Craft::$app->getRequest()->getAbsoluteUrl(), $primarySiteBaseUrl) !== 0) {
        Craft::$app->getResponse()->redirect($primarySiteBaseUrl . 'admin');
        Craft::$app->end();
        return;
    }
}
```

**Comment by brandonkelly** [comment]
I got this working, but then realized this is probably the wrong approach. If Craft definitively knows what the base CP URL is, then it should _only_ be recognizing URLs that begin with it as control panel requests, completely ignoring the `cpTrigger` config setting for other base URLs.

So going forward, if `baseCpUrl` is set to `http://cms.example.com` for example, then the _only_ way to access the control panel will be through `http://cms.example.com`.

**Comment by benface** [comment]
Haha that's a clean `diff`! Thanks Brandon.
