### ISSUE TITLE
Querying lightswitch returns Null

### ISSUE THREAD

**Issue by beeldr** [craftcms/cms#5866]
### Description

After adding a lightswitch field the following query won't work. It always returns null.

```
craft.entries
        .section('articles, events, projects, stories')
        .with(['mainImage'])
        .relatedTo(category)
        .showInGrid(true)
        .orderBy('stickyPost desc, postDate desc')
        .limit(9)
```
I tried  showInGrid(1), showInGrid('1'),  showInGrid('not 1') etc etc

When I remove the 'showInGrid' parameter and loop through all entries. The showInGrid parameter is returning correcly. And returns 1 or null. 

Any clue?

### Additional info

- Craft version: 3.4.11
- PHP version: 7.1.12
- Database driver & version:

**Comment by brandonkelly** [comment]
Do you have any entries where the `showInGrid` Lightswitch field is actually enabled?

**Comment by beeldr** [comment]
Yes, I enabled a few entries (different sections: articles, events, projects, stories) with showInGrid `Lightswitch` field settings enabled. Still no luck.

**Comment by brandonkelly** [comment]
It’s working fine on my end. You sure the field handle is spelled correctly in the template and the field settings? (It’s case-sensitive, too.)

**Comment by beeldr** [comment]
I have created a screencapture.  I guess that's the easiest way. Maybe you can help me out? :-)

https://www.dropbox.com/s/iliyveg3ju1ygd5/screencapture.mp4?dl=0

**Comment by brandonkelly** [comment]
Are you using MySQL or Postgres?

**Comment by beeldr** [comment]
I am using MySQL DB

**Comment by brandonkelly** [comment]
I’m a little stumped. Can you please email support@craftcms.com with your `composer.json` and `composer.lock` files, as well as a database backup?

**Comment by brandonkelly** [comment]
Issue here ended up being that the lightswitch values were in fact not set to `1` in the DB – they were still `null` – so their values in the templates only _looked_ like the field was enabled, per the field’s default value (see #2404).

As of the next release, Lightswitch field params will now include `null` results so long as the param value matches the default value. So if you pass `.myLightswitchField(true)` and the default value is enabled, then any `null` DB values will be included in the results.

**Comment by brandonkelly** [comment]
Craft 3.4.13 is out now with this fix.
