### ISSUE TITLE
Feature Request: Make field's getInputHtml() template name a variable

### ISSUE THREAD

**Issue by timmyomahony** [craftcms/cms#5867]
Every field has a `getInputHtml` method that renders the template snippet corresponding to that particular field.

Unfortunately, the template path to the fields is set statically, for example:

```php
    public function getInputHtml(...) {
        return $view->renderTemplate('_components/fieldtypes/Matrix/input', [ ... ]);
    }
```

If this was replaced with a variable, i.e.

```php
    public inputTemplate = '_components/fieldtypes/Matrix/input';

    public function getInputHtml(...) {
        // ...
        return $view->renderTemplate($this->inputTemplate, [ ... ]);
    }
```

It would make it possible to overwrite the input templates from a plugin (maybe using a behavior). 

This is useful where you want to augment/adjust a default field in the CP (instead of replacing it). 

Bear in mind I'm new to developing with PHP, so not 100% sure on whether behaviors will allow for easy overrides with this approach, but being able to change the default templates of fields/inputs would be really useful.

**Comment by brandonkelly** [comment]
It’s true that every field type has a `getInputHtml()` method, as that is required by the [FieldInterface](https://github.com/craftcms/cms/blob/develop/src/base/FieldInterface.php), but not every field type renders a template within it – that’s a personal choice for the field type. And I think field types should have full control over what that HTML is going to be. If you need to adjust something, you should be able to do that with JavaScript on the client.

**Comment by Mosnar** [comment]
@timmyomahony One option to consider is just minimally extending the settings template to prepend or append your changes. I just made a repository I had been experimenting with a few days ago public that does just this.

Essentially, I just wanted to add a field to set an input mask on a plain text field without having to re-implement everything already done in Craft and worry about re-implementing new features.

Take a look at the field class and settings template:
https://github.com/venveo/craft-masked-plain-text/blob/master/src/fields/MaskedPlainText.php
https://github.com/venveo/craft-masked-plain-text/blob/master/src/templates/_settings.twig

**Comment by timmyomahony** [comment]
@brandonkelly I'm following up on this quite late so this may be missed, but you mentioned:

> you should be able to do that with JavaScript on the client.

This is actually quite difficult. Because of the above shortcoming, I can't render my own template. I therefore can't add an asset bundle via `{% do view.registerAssetBundle(...) %}`

This means I need to add my asset bundle with my custom JavaScript another way, but it has to be added to the control panel template on a particular page (that contains the field I'm interested in adjusting) as well as _after_ that field has finished rendering, and has therefore added all its own asset bundles. 

I don't see anyway of doing this.

- There is no event to track the rendering of a field or the addition of another asset bundle
- There is no way to control dependencies or initialisation when it comes to asset bundles. 

Currently I'm using `View::EVENT_AFTER_RENDER_TEMPLATE` event but this is a very crude approach as:

- It happens on every view whether in the control panel or not
- Even when restricted to the control panel using `Craft::$app->request->isCpRequest`it will still be fired on all pages within the control panel

**Comment by brandonkelly** [comment]
@timmyomahony what sorts of changes are you looking to make?

**Comment by timmyomahony** [comment]
Thanks again for following up. The TLDR here is that everything is working OK, this is really just a request for documentation/best practises on working with existing fields. 

I'm working on this plugin:

https://plugins.craftcms.com/matrix-field-preview

Which adds screenshot/description previews of matrix field blocks to make it easier to identify what they'll look like when published. This requires adding functionality to the _existing_ matrix input field, as opposed to creating a new field. 

My first thought was to extend the default matrix input template to add what I need. This approach was my intuition coming from Django where there is an explicit API for overriding and extending default fields and tempaltes (this is encouraged). As mentioned, this isn't supported with Craft. 

After that, I then looked into doing everything in JS by injecting an asset bundle as suggested. Although I have this working as mentioned above, it felt like I was fighting against Craft and Yii to get it up and running. The end result requires me to conditionally check _every_ request before injecting the asset bundle which doesn't feel ideal. For example, it would be nice to have more granular events that I could listen to instead of `EVENT_BEFORE_RENDER_PAGE_TEMPLATE`. It was also just tricky to get the rendering correct so that my JS was guaranteed to load _after_ the default field's JS.

It's very possible that I'm just missing some docs somewhere, or just approaching this wrong, but it would be good to get some broad guidelines on "this is the Craft way of doing ____" when developing plugins. In this case it might just be "extending existing fields is a bad idea".

**Comment by brandonkelly** [comment]
I just added a new `EVENT_DEFINE_INPUT_HTML` to the base field’s `getInputHtml()` method, which all built-in field types will now trigger. You can use that to modify the resulting input HTML for the field, or simply register some JavaScript from there, knowing for certain that this is a request for a page that includes that field input.

```php
use craft\base\Field;
use craft\events\DefineFieldHtmlEvent;
use craft\fields\Matrix;
use yii\base\Event;

Event::on(
  Matrix::class,
  Field::EVENT_DEFINE_KEYWORDS,
  function(DefineFieldHtmlEvent $event) {
    /** @var Matrix $field */
    $field = $event->sender;

    // ...
  }
);
```

For other field types to start supporting this new event, they will need to change this line:

```php
public function getInputHtml($value, ElementInterface $element = null): string
```

To:

```php
protected function inputHtml($value, ElementInterface $element = null): string
```

**Comment by timmyomahony** [comment]
This is great, I appreciate taking the time to read through and implement it
