### ISSUE TITLE
'X-Requested-With' header no longer present in CP requests for elements

### ISSUE THREAD

**Issue by cscomfort** [craftcms/cms#5868]
### Description
On our hosting platform, as a workaround to an earlier issue where we couldn't log in to Craft 3, we settled on a solution that sets an accept header when `X-Requested-With: XMLHttpRequest` header is present in the request:

```
SetEnvIf X-Requested-With "XMLHttpRequest" JSONREQ
RequestHeader set Accept "application/xhtml+xml,application/xml,application/json,text/javascript; charset=UTF-8" env=JSONREQ
```

This continues to work for logging in, but when viewing elements (entries, assets, etc.) the CP reports an "Internal server error" -- resulting from a 400 error on the request to `index.php?p=admin/actions/element-indexes/get-elements&v=XXXXXXXXX`. Looking at the request itself, I see that the `X-Requested-With: XMLHttpRequest` header is absent.

This header was present in back in Craft 3.3.20.1, so perhaps this expected behavior as part of a recent change? If indeed intentional, any suggestions on how we might adjust accordingly?

### Steps to reproduce

1. Viewed the request headers to verify the absence of `X-Requested-With: XMLHttpRequest`.
2. Looking back at an install with Craft 3.3.20.1 to verify that the header is present.

### Additional info

- Craft version: 3.4.12
- PHP: 7.0.27

**Comment by brandonkelly** [comment]
> Looking at the request itself, I see that the `X-Requested-With: XMLHttpRequest` header is absent.

Where are you looking? In the browser’s Network tab for the Ajax request, or on Craft’s end?

Craft wouldn’t ever be the one to set that header itself – that would be up to whatever is sending the actual request.

If you can see from the browser’s Network tab that the header is in fact being sent in the request, then it must be getting lost on its way to Craft. If you have a load balancer or other gateway/proxy in front of the web server, that would be the first place to check.

**Comment by cscomfort** [comment]
Hi Brandon,

Thanks for the quick reply.

Just to make sure I'm not missing something, when I visit`https://mydomain.com/admin/entries/channel-name` and view the XHR request to `https://mydomain.com/index.php?p=operations/actions/element-indexes/get-elements&v=1585697012638` the request includes the `X-Requested-With: XMLHttpRequest` header.

I rolled back to 3.3.20.1 on our test server and see that `X-Requested-With: XMLHttpRequest` is present; after re-updating to 3.4.12, it's again absent. I get the same results in my local environment: Laravel Homestead (Apache).

Any insight into what could be driving the change?

**Comment by brandonkelly** [comment]
Ahh, ok, I see. I didn’t realize that `jQuery.ajax()` was setting that header automatically, and certain Ajax requests have started using `axios.request()` instead, like element index actions.

**Comment by brandonkelly** [comment]
Just added an `X-Requested-With` header to the Axios-based Ajax requests going forward.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#731d3dc7adc0944795ae13ab7e257ce267c911ae as 3.4.12",
  "...": "..."
}
```

Then run `composer update`.

**Comment by cscomfort** [comment]
> Ahh, ok, I see. I didn’t realize that `jQuery.ajax()` was setting that header automatically, and certain Ajax requests have started using `axios.request()` instead, like element index actions.

Thanks, Brandon -- this is what I started looking at late last night. Appreciate the quick commit. Hope you and the rest of the Craft gang are staying healthy.

**Comment by brandonkelly** [comment]
Craft 3.4.13 is out now with this change.

Hope you’re staying safe & healthy as well!
