### ISSUE TITLE
Hide Decimal Formatting for Numbers Fieldtype in the Entries View

### ISSUE THREAD

**Issue by kerns** [craftcms/cms#5873]
### Description
There are many instances where you do not want data from number fields to be displayed with decimal separation in an entries col listing.

I am working specifically now with two fields of numeric data – a vehicle identification number (VIN), and a model year – where in both cases, these are useful as columns in the entries listing and really should be input-constrained as numbers, ...but the commas are so disruptive that the data either needs to be collected as plain text or banished from the entries view entirely.

An option on the field to "Hide decimal formatting in the entries view" would be very nice.

**Comment by brandonkelly** [comment]
Just added a new “Preview Format” setting to Number fields for the next release, which can be set to “Unformatted” to prevent values from getting formatted on element indexes.

<img width="395" alt="The new Preview Format setting, set to “Unformatted”" src="https://user-images.githubusercontent.com/47792/93362081-6c5adc00-f7fa-11ea-8327-e547a7e42555.png">

Additional options are “As decimal numbers” (same behavior as before), and “As currency values”.

**Comment by brandonkelly** [comment]
Craft 3.5.11 is out now with that new setting 🎉
