### ISSUE TITLE
Allow custom HTML element in htmlpurifier config

### ISSUE THREAD

**Issue by thisanimus** [craftcms/cms#5875]
I'm using the IonIcons web component in my site, and it requires the following markup:
`<ion-icon name="checkmark-outline"></ion-icon>`
Obviously HTMLPurifier strips this out because it's not an actual HTML element.  I've added 'ion-icon' to the HTMLAllowed config string, and loaded the config, but get this error: 
`Element 'ion-icon' is not supported`
And it shows where HTMLPurifier is filtering the config options through htmlspecialchars().

My questions: 
- Is it possible to configure HTMLPurifier to allow a custom html element.
- Is this possible using the craft-supplied .json config, or do I need to write a plugin and extend HTMLPurifier?

**Comment by brandonkelly** [comment]
HTML Purifier is provided by Craft itself, so moved this over to the Craft repo.

To answer your question, it’s not currently possible, but something we intend to add support with, alongside custom attributes (#5736), so will mark this as a feature request.
