### ISSUE TITLE
Queue priority with Redis

### ISSUE THREAD

**Issue by jerome2710** [craftcms/cms#5876]
### Description
With the [commit](https://github.com/craftcms/cms/commit/781d40f42fa817c066457f23867df1bf684a274a) of @brandonkelly 3 days ago, multiple of our Craft websites are now broken. When using the Yii Redis queue, it does not support prioritizing and throws an exception. Now all our events will break. Could this be fixed ASAP?

### Additional info

- Craft version: Craft Pro 3.4.12
- PHP version: 7.2.24
- Database driver & version: MySQL 5.5.64
- Plugins & versions: not relevant

**Comment by brandonkelly** [comment]
Looking at the code and it’s not obvious what would cause the exception. `yii\queue\redis\Queue` extends `yii\queue\Queue`, which is where `priority()` is defined, and it’s not overriding that method or anything.

Can you find the exception in your `storage/logs/web.log` file (search for `[error]`) and post the full error message and stack trace?

**Comment by jerome2710** [comment]
Ah, I forgot to reference the line to the `yii\queue\redis\Queue` class where the exception is being thrown: https://github.com/yiisoft/yii2-queue/blob/master/src/drivers/redis/Queue.php#L191.

**Comment by brandonkelly** [comment]
Thanks! Craft 3.4.13 is out now with a fix for that.
