### ISSUE TITLE
Issue with forms.checkboxGroupField

### ISSUE THREAD

**Issue by sidedwards** [craftcms/cms#5880]
### Description
When a checkboxGroupField has more than 10 options, it will auto-select multiple values if the form values are over 10. I also tested with non-numerical values and got the same result. forms.checkboxSelectField had the same results as well.

### Steps to reproduce

1. Create a checkboxGroupField with > 10 options
2. Set the form values to any single value over 10
3. Form will select multiple values with a base of 10 (i.e. a value of 11 would also "check" 1)

<img width="366" alt="Screen Shot 2020-04-02 at 2 26 55 PM" src="https://user-images.githubusercontent.com/11489608/78298535-b459a100-74ef-11ea-867e-98daf090c997.png">

```
{{ forms.checkboxGroupField({
    labels: 'Checkbox Group',
    options: [
        {
            label: '1',
            value: '1',
        },
        {
            label: '2',
            value: '2',
        },
        {
            label: '3',
            value: '3',
        },
        {
            label: '4',
            value: '4',
        },
        {
            label: '5',
            value: '5',
        },
        {
            label: '6',
            value: '6',
        },
        {
            label: '7',
            value: '7',
        },
        {
            label: '8',
            value: '8',
        },
        {
            label: '9',
            value: '9',
        },
        {
            label: '10',
            value: '10',
        },
        {
            label: '11',
            value: '11',
        },
        {
            label: '12',
            value: '12',
        },
        {
            label: '13',
            value: '13',
        },
    ],
    values: '11',
    name: 'checkboxGroup',
    id: 'checkboxGroup'
}) }}
```

### Additional info

- Craft version: 3.4.12
- PHP version: 7.2
- Database driver & version: N/a
- Plugins & versions: N/a

**Comment by brandonkelly** [comment]
Your issue is that `values` is supposed to be an array. If you change it to `['11']`, it will work as expected for you.
