### ISSUE TITLE
Double clicking image asset in entry causes a 403 error if user does not belong to the main site

### ISSUE THREAD

**Issue by loqus** [craftcms/cms#5883]
### Description
Double clicking on an image asset on an entry layout field causes a error for users that belong to a different site than the main site. In the Assets section everything works as expected.
The console gives a 403 (forbidden) on a post to ?p=admin/actions/elements/get-editor-html

To clarify: 
User is in a group that only has rights to a certain subdomain info.domain with 4 languages
The user has no rights to edit something on the www.domain (also 4 languages)
The main site is 1 language on the www.domain
The image is a shared asset for info.domain and www.domain

If I add the user to the main site, everything works as expected

### Steps to reproduce

1. Add user to role with access to sites excluding main site
2. Add entry not belonging to main site and choose image shared between sites
3. Double click chosen asset to edit the title (error occurs)

### Additional info

- Craft version: Craft Pro 3.4.12
- PHP version: 7.4.4
- Database driver & version: MySQL 5.5.64
- Plugins & versions:

**Comment by brandonkelly** [comment]
I’ve followed your steps to a T, but I’m not able to reproduce the 403 error.

Can you please send your `composer.json` and `composer.lock` files, and a database backup, over to support@craftcms.com? We might have better luck reproducing with those.

**Comment by loqus** [comment]
I think I have to close this and see it as (again) a glitch in the matrix, since update to Craft Pro 3.4.13 and a composer update it seems to have been solved.

**Comment by brandonkelly** [comment]
Glad to hear! :)
