### ISSUE TITLE
Using apostrophe in Volume name is not decoded properly in field dropdown settings

### ISSUE THREAD

**Issue by bertoost** [craftcms/cms#5885]
### Description

I have created a volume named "Video's" (which is the way to write it in Dutch), but it's not decoded properly in the assets volume dropdown list

![image](https://user-images.githubusercontent.com/398492/78376775-14734480-75cf-11ea-853b-f2f2067bdf88.png)

### Additional info

- Craft version: 3.4.11
- PHP version: 7.4.4

**Comment by brandonkelly** [comment]
The fix for this ended up being a bit involved, and introduces a slight breaking change for plugins (HTML within checkbox options is now going to be HTML-encoded by default), so I fixed it on the `3.5` branch.
