### ISSUE TITLE
Improve UX of drafts by adding dates and sorting by date. Currently named drafts are nearly unusable.

### ISSUE THREAD

**Issue by andreimoment** [craftcms/cms#5889]
### Description

Currently drafts seem to be sorted by some invisible criteria, and at first sight the opposite of revisions. If worried about adding dates introducing noise in the UI, then please at least sort the drafts descending by date.

Please add dates to the drafts and sort them newest on top, like the revisions. This will resolve multiple issues.

### Named drafts create a mess
If we name the drafts (best practice at my company so it's clear what the changes are), they get rendered in an unpredictable way which renders the draft feature next to useless.

Which draft is more recent below? No way to tell.

<img width="251" alt="which draft is more recent?" src="https://user-images.githubusercontent.com/6190/78404260-dbc57200-75b2-11ea-819c-d7b2174ba017.png">

A simple change would solve for the issues below.

1. Drafts are sorted differently from revisions
2. It is unclear which draft is from when? Before a certain revision? After?

I am proposing:

![craftcms-drafts-request](https://user-images.githubusercontent.com/6190/78593844-238b0a00-77fc-11ea-9547-865dffe87491.jpg)

### Steps to reproduce

1. Save a new draft
2. Name it
3. Exit editing
4. Come back to editing
5. Repeat the step with another draft
6. Now we have two named drafts with unknown order and date which renders them next to useless in the case of tracing the timeline of changes.

### Additional info

- Craft version: 3.4.13

Related to #4768 but with more detail.

**Comment by brandonkelly** [comment]
Do you think they should be ordered by their _creation_ date, or the date they were last _updated_?

**Comment by andreimoment** [comment]
Date last time updated. I presume it’s the same for revisions?

The idea is to provide actionable document history. 

Another thought: the ability to overwrite drafts also creates a level if possible confusion. 

A cleaner solution could be always saving a new version (“draft”) and marking some “versions” as published, or “revisions”. 

Then no one can rewrite history and thus history is clearly defined. 

And, you could list drafts and revisions in one list with date/draft:title or date/revision:id.

UX-wise we would get the emotional safety and clarity we get from committing to git (in the simplest, single local branch scenario). 

This is the approach we took for an internal app. It also helped with the situation where multiple authors might edit the same document — each save results in a new version, neatly labeled with author and timestamp. We also required a short description of changes on save but that may be too much for craft.

Thank you for looking into this and being open to a conversation. I appreciate your commitment to quality.

**Comment by brandonkelly** [comment]
You are describing revisions, which do work that way. Basecamp doesn’t have to worry about multiple potentially in-progress drafts, though, any of which could end up being the next actual revision once published.

**Comment by andreimoment** [comment]
What I'm saying is that it is still more useful to have the drafts ordered descending by update date because that would make it clear which latest touched draft is. Compared to no date indication and no clear sorting that would be a huge improvement. 

As for multiple in-progress drafts, that would result in overwriting viable content, no? Unless a draft somehow merges only the changed items into the last revision which I don't think is the case?

Ideally, with multiple editors, there would be 

1. Document lock / check-in
2. Diff so that it's easy to determine changes

These features are significant changes which might take a lot of time. Having consistent sorting and date indication for drafts would be a step in the right direction which I imagine would require minimal changes to the codebase.

My team produces 1100+ new posts per year, with up to 25 versions each(!). Ordering drafts would be a lifesaver. The current ordering and labeling of drafts is quite confusing which prevents us from utilizing the feature.

**Comment by brandonkelly** [comment]
> As for multiple in-progress drafts, that would result in overwriting viable content, no? Unless a draft somehow merges only the changed items into the last revision which I don't think is the case?

That is in fact the case as of Craft 3.4 :)

**Comment by brandonkelly** [comment]
Alright, Craft 3.4.15 will have the following changes:

- Drafts will be sorted by date updated, descending
- Drafts will show their updated timestamps
- Fixed a bug where it was possible for revisions to be out of order

<img width="253" alt="The entry revision menu changes coming in Craft 3.4.15" src="https://user-images.githubusercontent.com/47792/78828458-9bdb0200-7999-11ea-812d-f8e57cb4447a.png">

The wording will also be changing in Craft 3.5 (requires us ordering some new translations, so can’t bring it into 3.4.x):

<img width="304" alt="The entry revision menu changes coming in Craft 3.5" src="https://user-images.githubusercontent.com/47792/78828689-f2e0d700-7999-11ea-802b-a0746cf4faed.png">

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#1e69b91ae44acde1becbccd592b250ba47003685 as 3.4.14",
  "...": "..."
}
```

Then run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.4.15 is out now with this change.

**Comment by andreimoment** [comment]
Thank you so much, @brandonkelly!!
