### ISSUE TITLE
Config option for disabling minification of js code appended using {% js %} tag

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#5890]
There are sometimes situations where having minified JS is detrimental, for example, while debugging errors.

Right now we can disable minification using `app.php` file, but it would be quicker and more comfortable doing that using `general.php` config file.

**Comment by brandonkelly** [comment]
I forgot this was already the case when we talked on Discord. You can use the [useCompressedJs](https://docs.craftcms.com/v3/config/config-settings.html#usecompressedjs) config setting to disable JS minification.

```php
'useCompressedJs' => false,
```
