### ISSUE TITLE
Upgrading from Craft 2 projectconfig database error

### ISSUE THREAD

**Issue by bantros** [craftcms/cms#5892]
### Description
Upgrading from Craft CMS `2.9.2` => `3.14.13` (locally) fails with the following error:

```
Database Exception – yii\db\Exception
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'DB_NAME.projectconfig' doesn't exist
The SQL being executed was: SELECT `value`
FROM `projectconfig`
WHERE `path`='dateModified'
LIMIT 1
Error Info: Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'DB_NAME.projectconfig' doesn't exist
)
↵
Caused by: PDOException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'DB_NAME.projectconfig' doesn't exist
in /CMS_PATH/public/vendor/yiisoft/yii2/db/Command.php at line 1293
```

### Steps to reproduce

1. Existing installation of Craft CMS 2.9.2
2. Follow steps listed at https://docs.craftcms.com/v3/upgrade.html#performing-the-upgrade
3. Upgrade completes "successfully" but on being forwarded to /admin/dashboard get error shown above
4. No project config as this feature unavailable in previous installation, cannot use the command `./craft project-config/rebuild` to create one as I get the same database error:

```
Exception 'yii\db\Exception' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'DB_NAME.projectconfig' doesn't exist
The SQL being executed was: SELECT `value`
FROM `projectconfig`
WHERE `path`='dateModified'
LIMIT 1'

in /CMS_PATH/public/vendor/yiisoft/yii2/db/Schema.php:674

Error Info:
Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'DB_NAME.projectconfig' doesn't exist
)
```

### Additional info

- Craft version: 3.14.13
- PHP version: 7.2.14
- Database driver & version: MySQL `5.7.25`
- Plugins & versions:

**Comment by andris-sevcenko** [comment]
Does this happen every time you attempt this?

**Comment by bantros** [comment]
@andris-sevcenko I've must've tried upgrading half a dozen times from the same database, always the same error

**Comment by andris-sevcenko** [comment]
@bantros Does your `migrations` table have an entry for the "m180521_172900_project_config_table" migration after the upgrade?

**Comment by bantros** [comment]
@andris-sevcenko Yes the entry "m180521_172900_project_config_table" is present in the `migrations` table

**Comment by brandonkelly** [comment]
Hey @bantros, can you please send your Craft 2 database backup over to support@craftcms.com ?

**Comment by bantros** [comment]
Sent @brandonkelly

**Comment by bantros** [comment]
Clearing the `storage/runtime` directory fixed the issue, thanks for the support
