### ISSUE TITLE
Remove field inside of migration?

### ISSUE THREAD

**Issue by ryanpcmcquen** [craftcms/cms#5897]
### Description

Is it still possible to remove a matrix field inside of a migration?

Seems like with Project Config this wouldn't be possible, and I cannot seem to find examples or docs on how to do this. The scenario is that we have a field we want to remove, but we need to first run a migration that migrates data out of that field into new fields, _then_ delete the old field.

### Steps to reproduce

1. Have a field you need data from for a migration.
2. Intend to delete that field after the data is transferred out of it.

### Additional info

- Craft version: 3.4.x
- PHP version: 7.x

**Comment by brandonkelly** [comment]
You could write your migration to handle the content changes, but leave the actual field removal up to the project config sync.

If you do this, you will need to be very careful to run `./craft migrate/up` (not `migrate/all`!) **before** `./craft project-config/sync`. Unfortunately there’s no way to enforce this though.
