### ISSUE TITLE
Guidance for Adding a New Dropdown with a Default Selection to Existing Content

### ISSUE THREAD

**Issue by jonlongnecker** [craftcms/cms#5898]
### Description
I'm having to add several new dropdowns to a bunch of existing entries (dealing with the new event attributes for Google). But what I'm noticing is that even if I set a "default" selection on the new fields, existing entries don't have a value saved for the new dropdowns until the entry is brought up and saved again.

With hundreds of entries, this isn't really feasible to re-open and re-save every one. I've tried re-saving the entire section, but that doesn't seem to have worked. Is there another way to get those defaults saved to existing entries without doing them one by one?

**Comment by brandonkelly** [comment]
You could write a SQL query that sets the default values.

```sql
UPDATE content AS c
INNER JOIN entries AS e ON e.id = c.elementId
SET c.field_f1 = 'foo', c.field_f2 = 'bar'
WHERE e.sectionId = 5
```

That assumes two fields need default values applied; add more values to the `SET` clause if you have more than that.

Replace `f1` / `f2` with your actual dropdown field handles, `foo` / `bar` with your desired default values, and `5` with the actual section ID you want to update. If multiple sections, replace `= 5` with `in (5, 6, 7)`.

(We plan to implement a better solution for this in the future – see #2446.)
