### ISSUE TITLE
Saving an entry is very slow when max revisions are hit

### ISSUE THREAD

**Issue by martinhellwagner** [craftcms/cms#5902]
### Description

When saving an entry (even a big one), saving is usually fast. However, when the maximum number of revisions (e.g. 10) are hit, saving becomes very slow – this might be due to the "old" revisions having to be deleted/pruned. Is there any way the pruning can be carried out in a queue job after the entry has been saved? It is rather difficult for the Content Editors to wait that long to save an entry. With bigger entries and more revisions, we even got MySQL errors related to this problem (see https://github.com/craftcms/cms/issues/5872).

Maybe related to that is the fact that when pruning revisions manually via the new CLI task, some entries have revisions being pruned that shouldn't even be there (for example 16 revisions of an entry were pruned when only 10 are allowed and a pruning task has already been carried out).

### Steps to reproduce

1. Save an entry where maximum number of revisions is hit

### Additional info

- Craft version: 3.4.14
- PHP version: 7.2
- Database driver & version: MySQL 8.0

**Comment by brandonkelly** [comment]
Just implemented this for Craft 3.5 – all automatic revision pruning will now happen via a background job.

Another thing you might consider for now is, you could set your `maxRevisions` config setting to `0`, and set up a cron job to call this each night:

```
craft utils/prune-revisions --max-revisions=10
```



> Maybe related to that is the fact that when pruning revisions manually via the new CLI task, some entries have revisions being pruned that shouldn't even be there (for example 16 revisions of an entry were pruned when only 10 are allowed and a pruning task has already been carried out).

Craft will only prune extra revisions automatically for an entry when it’s saved, and only if its section has versioning enabled. So my guess is you have recently decreased your `maxRevisions` setting, and you hadn’t actually saved the entry since that happened (or perhaps you had disabled versioning for the section before changing the config setting, so even though you have been saving the entry, the config setting just hasn’t been getting applied).

**Comment by martinhellwagner** [comment]
> Just implemented this for Craft 3.5 – all automatic revision pruning will now happen via a background job.

Sweet, thank you so much! 😍 

> So my guess is you have recently decreased your `maxRevisions` setting

Yes, in fact we had no `maxRevisions` setting in our config file, but introduced it recently in order to be able to control the complexity of our system. Would it work to "resave" all the entries with the new `maxRevisions` setting (for example by running the respective CLI task), and then prune the revisions again (again via CLI)?

**Comment by brandonkelly** [comment]
Sorry maybe I’m getting confused. Are you continuing to see the `utils/prune-revisions` command pruning more revisions than you were expecting? In theory, once you have set `maxRevisions` to something besides `0`, and then run the `utils/prune-revisions` command once with the same max revision value, going forward you shouldn’t ever have to run that again, as Craft will start pruning extra revisions automatically whenever it’s creating new ones for an entry.

**Comment by martinhellwagner** [comment]
Yes, we were seeing exactly that: we set `maxRevisions` to `10`, then ran the `utils/prune-revisions` to prune the extra revisions. In my understanding, now every entry should have a maximum of 10 revisions. However, when we ran the command again a few days later, it seemed to prune as many as 16 revisions for one entry, while the same limit was set.

**Comment by brandonkelly** [comment]
Hm, yea that’s not right. If you continue to see this happen, can you post a new issue about it with steps to reproduce?

**Comment by martinhellwagner** [comment]
Sure thing! Still, might it be that these entries that continuously show too many revisions just haven't been saved after we've introduced the `maxRevisions` parameter? Or is this independent thereof?

Steps to reproduce are really just running the `utils/prune-revisions` CLI command _after_ introducing the parameter.

**Comment by martinhellwagner** [comment]
@brandonkelly 

I did a little test to see if the `utils/prune-revisions` command works fine. I pruned the revisions down to 5, expecting a maximum of 5 revisions to be pruned since our `maxRevisions` parameter is set to 10. That indeed worked as expected, but when I ran the whole thing again, the revisions of two entries were being pruned all over again. Turns out these entries were deleted in the Control Panel but no in the DB – neither were there revisions. I removed them manually, and now there's nothing to prune. 🙂 

I think we could give your solution a shot then – setting the `maxRevsions` parameter to 0 (just to double-check: this means unlimited revisions?) and pruning the revisions with a Cron Job each night.

Just out of curiosity: when is the ETA for Craft 3.5? Is there any timeline for this release already?

**Comment by brandonkelly** [comment]
Sorry I’m not sure I’m following. Can you please post a new issue with all of the specific steps to reproduce, as well as identify the exact moment something isn’t working as expected for you?

**Comment by brandonkelly** [comment]
> Just out of curiosity: when is the ETA for Craft 3.5? Is there any timeline for this release already?

No ETA quite yet, sorry.

**Comment by martinhellwagner** [comment]
@brandonkelly 

So far, I don't see any problems with the `utils/prune-revisions` any more. I'll open a new issue if something comes up. Thanks for your help – much appreciated! 😍
