### ISSUE TITLE
GraphQL: Getting checkbox/dropdown labels within tables

### ISSUE THREAD

**Issue by gregorterrill** [craftcms/cms#5903]
GraphQL support for the label argument was added to Checkbox, Dropdown etc. fields here: #5514 but this doesn't seem to extend to checkboxes, dropdowns etc. inside Table field rows. Is it possible for this to be extended so we can grab the labels from fields within Table fields as well?

**Comment by brandonkelly** [comment]
It’s not even possible to access Table dropdown option labels within Twig, and not sure it’s worth the effort. But I’ll leave this open.
