### ISSUE TITLE
Search for Plugins not Showing All

### ISSUE THREAD

**Issue by simeon-smith** [craftcms/cms#5904]
The search for plugins is not showing all of them. 

For example:
Search for "colour".

This plugin doesn't show up:
https://plugins.craftcms.com/colour-swatches

But it does have a page:
https://plugins.craftcms.com/colour-swatches

And if you go directly to it's url you can install it:
{siteUrl}/admin/plugin-store/colour-swatches

**Comment by brandonkelly** [comment]
That plugin is no longer available. Just fixed a bug that was allowing it to continue showing up when accessed directly.
