### ISSUE TITLE
Color Fields in Graphql Not Returning Default

### ISSUE THREAD

**Issue by simeon-smith** [craftcms/cms#5905]
### Description

The color picker field is not returning the default value in graphql when nothing is selected.

### Steps to reproduce

1. Create a color picker filed.
2. Set a default for that field.
3. Add it to a section.
4. Save an entry in that section without setting a color.
5. Query that field in graphql.

### Additional info

- Craft version: 3.4.14
- PHP version: 7.2
- Database driver & version: MySQL 5
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
The default value only applies to completely new elements. We’re planning to make it possible to apply that to existing elements down the road (see #2446), but for now you’d need to manually execute a SQL query to make that happen (example here: https://github.com/craftcms/cms/issues/5898#issuecomment-610108206).
