### ISSUE TITLE
Feature Request: be able to see last user to edit entry in Entries list

### ISSUE THREAD

**Issue by bzin** [craftcms/cms#5907]
### Description

On a project where you have multiple authors and many Users that are content editors it will be interesting to be able to see the latest user that made an update to an entry in the Entries list.

This seems to be already available to see on the Entry revisions dropdown. 

With adding this functionality to the Entries list you could:

- Enable and see the latest user that updated the Entry;
- Filter the Entries by this user even if this is not the author of the entry (this could be enabled if the user added the latest revision user to the Entries list);
- Probably only users with a specific permission would be able to see this functionality;

### Additional info

- Craft version: Craft Pro 3.4.9
- PHP version: 7.1.18
- Database driver & version: MySQL 5.6.10
- Plugins & versions:

**Comment by brandonkelly** [comment]
Just added this for Craft 3.5, as well as a “Revision Notes” column:

<img width="408" alt="An entry index table showing Revision Notes and Last Edited By columns" src="https://user-images.githubusercontent.com/47792/78903965-b90edf80-7a30-11ea-910a-bb0f28b28a20.png">
