### ISSUE TITLE
Wrong plugin updates because of similar name

### ISSUE THREAD

**Issue by superpikar** [craftcms/cms#5908]
### Description
I made custom plugin named `pikarlabs/usermanual`, when I open Utilities >> Updates a package named `Usermanual` need to be updated.

It seems taken from another plugin https://plugins.craftcms.com/usermanual which I didn't install, both of the plugin have different namespace. 

**my plugin**
![Capture2](https://user-images.githubusercontent.com/2832280/78887525-3450af80-7a8a-11ea-9a87-5c691cd808f7.JPG)

**utilites >> updates page**
![Capture](https://user-images.githubusercontent.com/2832280/78887267-c0160c00-7a89-11ea-803c-6e96c3e3b846.JPG)

### Steps to reproduce

1. install custom plugin with package name `usermanual`
2. open utilities >> updates

### Additional info

- Craft version: 3.4.13
- PHP version: 7.2
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Yeah this is expected behavior. See https://github.com/craftcms/cms/issues/3054#issuecomment-402006340 for an explanation.
