### ISSUE TITLE
Filtering in MatrixBlockQuery does not work with Lightswitch fields

### ISSUE THREAD

**Issue by Saboteur777** [craftcms/cms#5909]
### Description

Trying to filter a MatrixBlockQuery, like this: 

```
{% set content = entry.pageContent ?? null %}
{% set toc = clone(content).includeInTableOfContent(true).all() %}
```

The result is an empty array. Filtering for block type works though: 

```
{% set content = entry.pageContent ?? null %}
{% set toc = clone(content).type('text').all() %}
```

`includeInTableOfContent` is a Lightswitch field in some of the available Matrix block types (but it is not present in all of them). 

### Additional info

- Craft version: 3.4.14
- PHP version: 7.3.11
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you send your `composer.json` and `composer.lock` files, plus a database backup, over to support@craftcms.com?

**Comment by Saboteur777** [comment]
Sure, thanks!

**Comment by Saboteur777** [comment]
This has been resolved: I was using the same field handle in multiple blocks, so filtering did not work. 

Solution: 

```
{# Base matrix block #}
{% set matrix = entry.pageContent.all() %}

{# Filter matrix blocks - THIS DID NOT WORK! #}
{% set filteredMatrix = clone(matrix).fieldHandle(true).all() %}

{# Craft can understand commonly named field on the block level only, so this will work - it is a little bit ugly though.  #}
{% for block in matrix %}

    {% if block.fieldHandle == 1 %}
        {{ block.heading }}
    {% endif %}

{% endfor %}
```

**Comment by brandonkelly** [comment]
Thanks for the update!
