### ISSUE TITLE
Following the activation URL doesn't change a user's status from "pending" to "active"

### ISSUE THREAD

**Issue by benface** [craftcms/cms#5911]
### Steps to reproduce

1. In a controller:
```php
$user = new User();
$user->pending = true;
$user->username = $email;
$user->email = $email;
$user->password = 'test1234';
Craft::$app->getElements()->saveElement($user);
Craft::$app->getUsers()->sendActivationEmail($user);
```
2. Click on the activation URL in the received email, which should be in the form `http://base.url/verifyemail?code=[some-long-string]&id=[some-long-string]` (I'm assuming the path is `verifyemail` instead of `setpassword` because we set a password programmatically, which is exactly what I want)
3. Get redirected to `activateAccountSuccessPath`.

**Expected result:** The user is now active (`$user->pending` = `false`).
**Actual result:** The user is still pending (`$user->pending` = `true`).

### Additional info

- Craft version: 3.4.15
- PHP version: 7.4.2
- Database driver & version: MySQL 5.7.26

**Comment by benface** [comment]
After some digging, this seems to be caused by this block here: https://github.com/craftcms/cms/blob/88c70352054004e79ac2ba0639ea287b0d702b0b/src/services/Users.php#L612-L615

For some reason `unverifiedEmail` is empty even though I never verified the email.

**Comment by brandonkelly** [comment]
Can you confirm that email verification is enabled at Settings → Users → Settings?

How exactly are you setting the password programmatically? And if you disable that code, does it work as expected?

**Comment by benface** [comment]
@brandonkelly Yes I have both "Verify email addresses?" and "Allow public registration?" checked.

I am setting the password programmatically like in the above code, except I'm setting it to a random string, not `test1234`:

```php
$user->password = \craft\helpers\StringHelper::randomString();
```

I'm doing this because the site I'm working on is a WIP and I want users to be able to confirm their email address without having to set a password, or even being aware that they are creating a user account. There is no front-end login at the moment; there is only a form to subscribe to a mailing list with a custom controller action. We will most likely email all users at some point in the future for them to set a password if they want to.

**Comment by benface** [comment]
> And if you disable that code, does it work as expected?

If I remove the `$user->password =` line, yes it "works" but then the activation path is `setpassword` instead of `verifyemail`. Like I said, I don't want them to set a password.

**Comment by brandonkelly** [comment]
Alright, this should be fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#149f5f216c3074ba708ff49300d954899b1e2493 as 3.4.15",
  "...": "..."
}
```

Then run `composer update`.

**Comment by benface** [comment]
Thanks Brandon!

**Comment by brandonkelly** [comment]
Craft 3.4.16 is out now with that fix.
