### ISSUE TITLE
Permissions not respected when trying to create a new entry via a modal

### ISSUE THREAD

**Issue by olivierbon** [craftcms/cms#5917]
### Steps to reproduce

1. Create two sections and add an Entries field to one of them.

2. Create a user with all permissions on the channel with the related field and only Edit entries, Create entries, and Edit other authors’ entries on the second section.

3. Create a new entry in the section the user has full permissions on, open the relational field's modal and try to create a new entry from there. You will get a 403 forbidden error.

Creating entries in the restricted channel directly (via entry form rather than modal) works fine

### Additional info

- Craft version: 3.4.15

**Comment by brandonkelly** [comment]
Craft 3.4.16 is out now with a fix for this.

**Comment by chasegiunta** [comment]
@brandonkelly What was the reasoning for flagging all Singles as not editable?

https://github.com/craftcms/cms/blob/e7750cc36099183bba9cfcf18144ee6efb31716f/src/elements/Entry.php#L975
