### ISSUE TITLE
[GraphQL] Query with localization

### ISSUE THREAD

**Issue by lucasvallenet** [craftcms/cms#5919]
### Description
I have a localized website and I'm using GraphQL to retrieve data. 
I haven't found a way to specify in which language I want to fetch the data in my query.
For now, every query return the data of the primary site.

### Steps to reproduce

1. Setup a localized website
2. Generate a graphQL query:
```
{
  entry(id: 1) {
    title
  }
}
```
3. How can I specify the language/site in the query ?

### Additional info

- Craft version: 3.4.15
- PHP version: 7.1.26
- Database driver & version: MySQL 5.7.25

Thanks !

**Comment by lucasvallenet** [comment]
I found an answer on my own !!
You can specify the `site` or the `siteId` parameter in the query :

```
{
  entry(id: 1, site: "mySite2", siteId: 2) {
    title
  }
}
```

**Comment by yasin7044** [comment]
How can i know the siteId dyamically

**Comment by andris-sevcenko** [comment]
@yasin7044 what do you mean? `siteId` is a property that all entries have.

**Comment by yasin7044** [comment]
I mean that when i change language from english to netherland..What should be pass in query?

**Comment by andris-sevcenko** [comment]
@yasin7044 depends on how you are building your site. 

Typically, you'll have a language selector on the site hard-coded, so there is some assumed knowledge there.
I would also then add the site id or site handle on some HTML attribute there, so you have that information available.

If you are looking for this information in an entry context, then the following GraphQL query will get you the localization information for a specific element:
```graphql
{
  entries {
    title
    localized {
      siteId
      language
    }
  }
}
```

Does this help?

**Comment by yasin7044** [comment]
In the graphql playground i am getting the correct data when sending site id..but when i am calling from nuxt not getting correct data as per siteId.
