### ISSUE TITLE
Allow database backups to be placed into Asset volumes

### ISSUE THREAD

**Issue by aaronbushnell** [craftcms/cms#5920]
### Description
I've seen some rumblings in the codebase about `CRAFT_EPHEMERAL` being a constant to handle a Craft install where storage is ephemeral. I'd love to expand on issue #4699 and give database backups the same treatment that User Photos received in #933—where database backups can be placed into a Asset volume. 

This is especially useful when you have the CMS in a load balanced environment and the backup file might be on server "1" but you've been bounced to servers "2", "3", "4", etc and don't have access to that file.

### Steps to reproduce
N/A

### Additional info

- Craft version: 3.4.15
- PHP version: 7.2.23
- Database driver & version: MySQL 5.7.29
- Plugins & versions: No plugins installed

**Comment by brandonkelly** [comment]
Agree we should do this, but it’s not possible right now because you wouldn’t want Craft to have to start managing your database backups as assets. Just posted #5926 with a plan to decouple volumes from assets, which would pave the way for this.

**Comment by aaronbushnell** [comment]
Makes total sense—thanks @brandonkelly!
