### ISSUE TITLE
Function for namespacing ids and classes in HTML strings

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#5921]
`svg()` function has an option to namespace classes and IDs in SVG markup to avoid conflicts. I think it would be useful to have other function that would do that for non-SVG HTML strings.

Today I ran into a situation where client wanted to upload HTML files in asset fields, to output their contents on the frontend. And each file had its own `<style>` tag.  I just copied part of `svg()` function responsible for namespacing  to custom php module and created my own function. But it would be useful to have such function built-in.

**Comment by brandonkelly** [comment]
Just beefed up the [{% namespace %}](https://docs.craftcms.com/v3/dev/tags.html#namespace) tag and [|namespace](https://docs.craftcms.com/v3/dev/filters.html#namespace) filter for Craft 3.5 with the following improvements:

- They now apply the namespace to ID selectors within `<style>` tags.
- The tag has a `withClasses` flag you can set on it, and the filter has a `$withClasses` argument. If set, then class names and class CSS selectors within `<style>` tags will also get namespaced.

So for example, this:

```twig
{% namespace 'foo' withClasses %}
<style>
  .title { font-weight: bold; }
</style>
<input class="title" name="title" type="text">
{% endnamespace %}
```

would result in this:

```html
<style>
  .foo-title { font-weight: bold; }
</style>
<input class="foo-title" name="foo[title]" type="text">
```

**Comment by piotrpog** [comment]
@brandonkelly Thanks!
