### ISSUE TITLE
Include sourceId and sourceUid in GraphQL Entry schema

### ISSUE THREAD

**Issue by ugrupp** [craftcms/cms#5927]
### Description
When querying a draft entry via GraphQL (by appending `?token=XYZ` to the endpoint), `sourceId` and `sourceUid` can't be included in the result. They seem to be missing from the Entry schema.

This is less of a problem when querying by `entry(sourceId)`, since the source ID is known at the time of querying. However, when using `entries()`, the source ID may not be known, so there's no way to find the source entry from the returned draft entry data. 

Would it be possible to add `sourceId` and `sourceUid` to the Entry schema?

### Additional info
- Craft version: 3.4.12

**Comment by andris-sevcenko** [comment]
Thanks for reporting that! This issue has actually already been covered by #5580, and it’s been merged into the 3.5 branch of Craft.
