### ISSUE TITLE
Order custom fields not displaying field instructions

### ISSUE THREAD

**Issue by rob-baker-ar** [craftcms/cms#5928]
### Description

_(Upgraded to Commerce 3 from 2)_

I have various custom fields attached to orders - the field names and their data is visible when clicking an order in CMS Interface > Commerce > Orders > [click an order for it's detail]. However, instructions set on the custom fields (that normally appear below the field name but above the form element) are not showing.

### Steps to reproduce

1. Add custom field to order with instructions
2. View an order details screen - instructions not showing.

### Additional info

- Craft version: 3.4.14
- Commerce (Pro) Version: 3.0.12
- PHP version: 7.2.24
- Database driver & version: MySQL 5.7.29
- Plugins & versions:
Amazon S3	1.2.7
Asset Rev	6.0.2
CP Field Inspect	1.1.3
Digital Download	2.1.5
Digital Products	2.3.1
Dumper	2.0.0
Imager	v2.4.0
Inlin	2.1.1
Logs	3.0.3
Minify	1.2.10
Navigation	1.3.8
PayPal for Craft Commerce	2.1.0.1
Redactor	2.6.1
SEOmatic	3.2.51
Stripe for Craft Commerce	2.2.3
Template Select	2.0.2
Wordsmith	3.1.2
Worldpay for Craft Commerce	2.1.0.1

**Comment by rob-baker-ar** [comment]
Thanks @lukeholder, 

Edit order mode is new to me -  I think before I started updating to Commerce 3 (i.e. in Commerce 2) edit mode was either the default or there was no read-only mode.

It would be helpful to show instructions when in read-only mode as the text contained does not always refer to edits.

**Comment by brandonkelly** [comment]
Just fixed this for the next Craft release.

**Comment by brandonkelly** [comment]
Craft 3.4.16 is out now with that change.
