### ISSUE TITLE
Problem querying lightswitch fields via GraphQL

### ISSUE THREAD

**Issue by olivierbon** [craftcms/cms#5930]
### Description

When querying entries via GraphQL using a lightswitch field as a condition, Craft will only and always return entries where the field is set to `1`/`true`.

Note: The same query in Twig runs just fine.

### Steps to reproduce

1. Create a section with a lightswitch field
2. Switch some entries to true, some to false
3. Try to query for entries where ` lightswitchField: "0"`

Complete query:

```
query {
  entries(
    section: "yourSection"
    lightswitchField: "0"
  ) {
    id,
    title
    ... on yourSection_yourEntryType_Entry {
      lightswitchField
    }
  }
}
```

### Additional info

- Craft version: 3.4.15

**Comment by andris-sevcenko** [comment]
It's definitely a bug in parsing the arguments. However, if implemented haphazardly in 3.4, it might not play nicely with mutations that are coming in 3.5, so I feel much more comfortable adding that for Craft 3.5 alongside mutations.

**Comment by harrymee123** [comment]
Hi Andris, 

Great news to know a fix is coming in 3.5. Do you have an estimated due date for 3.5?

We have a project which is being effected by this and it is supposed to be launching pretty soonish. The only work around we have atm is to remove the field from the query and then filter out the entries based on the value on the frontend, which we would prefer to avoid on the production site.

Knowing we could let the client know the issue will be resolved before we go live would be great.

Cheers,
Harry

**Comment by andris-sevcenko** [comment]
I'll see if we have a date or an estimate we can share and I'll get back to you!

Also, this has been fixed for 3.5

**Comment by brandonkelly** [comment]
Hey @harrymee123, we’re going to get a 3.5 Beta out early next week.

**Comment by harrymee123** [comment]
That’s great. Thanks for letting me know @brandonkelly !

**Comment by denisyilmaz** [comment]
any updates when 3.5 will be released? we are having a project launch next week and this is one of the last issues we need to solve before the launch.

**Comment by denisyilmaz** [comment]
@brandonkelly is there no way to publish a workaround that can be implemented in 3.4 ?
we have a project that needs this feature so we are able to launch, and I can't use a beta version for production.

**Comment by andris-sevcenko** [comment]
While it's definitely in the realm of possible, fixing this bug involved some architectural changes, so it would make more sense for it to be in 3.5.

@denisyilmaz what's your timeline for this project? 3.5 GA could be closer than you think :)

**Comment by denisyilmaz** [comment]
We are currently in final bug fixing stage, besides this bug we only have one other bug related to angular that keeps us from publishing. So we aim to go live in the next 10 days or so…

**Comment by harrymee123** [comment]
To get around this issue on a production build, we swapped the Lightswitch field for a Radio Buttons field with the values 1 & 0 or Yes & No.

This required minimal changes within the GraphQL variables, then also should require minimal changes for when 3.5 has been released.

**Comment by denisyilmaz** [comment]
@harrymee123 thanks for that tip, I actually did not think about that. but I just tested it on my local installation. i can successfully query for a section with that field in it ("1", "not 0", ":empty" are all working correctly).

But for my case it still does not hold the correct behavior, as we have two sections I want to query at the same time where only one of the sections has this field.
1. Blog Entry 
2. Project (this has the field "showInBlog")

so my query should show all blog entries + all projects with a "showInBlog" set to true)…

```gql
{
entries(
    type: ["project", "blogEntry"]
    orderBy: "postDate desc"
    limit: 10
    offset: 0
    showInBlog_temp: ["1", "or", ":empty:"] // ":empty: or 1" // ":empty: or not 0" all are not working
  ) {
    title
    typeHandle
    ... on projects_project_Entry {
      showInBlog
      showInBlog_temp
    }
  }
}
```
this query results in 0 results. but when "showInBlog_temp" (this is the radio field I created after your comment) is only set to "1" / "0" / "not 0" / ":empty" it shows projects depending on the field settings, but ignoring all blogEntries……

Or is this something GraphQL can't handle at all?

**Comment by andris-sevcenko** [comment]
@denisyilmaz glad you got a decent working solution without any hacks involved!

**Comment by toddpadwick** [comment]
Hi @andris-sevcenko ... I get the following error with a lightswitch field when I try @denisyilmaz suggestion:
```
"Field \"entries\" argument \"showInCategoryListing\" requires type Boolean, found [\":empty:\", \"not 0\"].",
```

The only thing it seems to allow is `showInCategoryListing: true`. However, some of my entry types do not have a showInCategoryListing field and are therefore always visible in the listing. So is there a way to check both **_if not defined_** and  **_if defined and is true_**?

**Comment by howells** [comment]
@toddpadwick I need to do exactly this, how did you resolve it? cc @andris-sevcenko

**Comment by brandonkelly** [comment]
There’s no way to differentiate between Lightswitch fields that don’t have a value set, and ones set to the default value.

Their query params [only support](https://craftcms.com/docs/4.x/lightswitch-fields.html#querying-elements-with-lightswitch-fields) `true` or `false` values; `:empty:` will get normalized to `false`:

https://github.com/craftcms/cms/blob/567bed4ca6b49e1b4f183b7ce7d2c7cdf7156b42/src/helpers/Db.php#L645

So if you only want to select entries that actually have a Lightswitch field, you will need to limit the query to only select entries with certain entry types, via the `type` argument.

**Comment by toddpadwick** [comment]
In the end @howells  I had to add a `showInCategoryListing` field to all my entries that were queried. That way, none are undefined. Not ideal but as @brandonkelly says I think it's the only way.
