### ISSUE TITLE
Custom aliases not working with test framework

### ISSUE THREAD

**Issue by mtwalsh** [craftcms/cms#5932]
### Description

Custom aliases are not loaded from the general config when using the test framework.

### Steps to reproduce

1. Setup a test as per the [Getting Started](https://docs.craftcms.com/v3/testing/testing-craft/getting-started.html) guide
2. Run an acceptance test where the Twig template uses a custom alias and notice the following output:

`[Twig\Error\RuntimeError] An exception has been thrown during the rendering of a template ("Invalid path alias: @aliasNameHere").`

I seem to have been able to fix the issue by adding the following code:

```
        $configService = self::createConfigService();
        $generalConfig = $configService->getConfigFromFile('general');

        // Set any custom aliases
        $customAliases = $generalConfig['aliases'] ?? $generalConfig['environmentVariables'] ?? null;
        if (is_array($customAliases)) {
            foreach ($customAliases as $name => $value) {
                if (is_string($value)) {
                    Craft::setAlias($name, $value);
                }
            }
        }
```

Here:

https://github.com/craftcms/cms/blob/develop/src/test/TestSetup.php#L346

### Additional info

- Craft version: Craft Pro 3.3.20.1
- PHP version: 7.3.14
- Database driver & version: MySQL 5.7.28

**Comment by brandonkelly** [comment]
Craft 3.4.20 is out now with this change.
