### ISSUE TITLE
Ability to limit allowed origins for GraphQL API requests

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/cms#5933]
Currently the `graphql/api` action will set an `access-control-allow-origin: *` header on the response, leaving the API wide open for any JS script to call it regardless of origin.

It’s possible to restrict that header to a single hostname by setting the header at the server level, overriding Craft’s header. However that’s a little hacky and not clear it will work in every environment, and that solution is limited to a single hostname. (The `access-control-allow-origin` header can only be set to a single hostname, so if you want to allow 2 or more, you need to dynamically set it in code.)

Craft should solve this by adding a `allowedGraphqlOrigins` config setting, which could be set to `null` (default – meaning allow all), or an array of specific origins to allow. An empty array or `false` should mean that the header should never be sent.

**Comment by brandonkelly** [comment]
Added this for 3.5.

**Comment by steveDL** [comment]
This has just saved me, adding graphql headers has been very annoying trying to debug, causing duplicated headers in nginx config when trying to use axios to call login/send contact form. This should be in the docs!

**Comment by mattstein** [comment]
Noted [in docs](https://github.com/craftcms/docs/commit/421844c0e3909810ec85d04de04546be6ef0a8e9) for the next release.
