### ISSUE TITLE
getFolderTreeByFolderId doesn't return a tree

### ISSUE THREAD

**Issue by olivierbon** [craftcms/cms#5939]
### Description

When trying to get a folder tree using `getFolderTreeByFolderId` Craft only return the folder being passed to the method.

### Steps to reproduce

1. Call `Craft::$app->assets->getFolderTreeByFolderId(folderId)`

### Additional info

- Craft version: 3.4.15

**Comment by brandonkelly** [comment]
Craft 3.4.16 is out now with a fix for this.
