### ISSUE TITLE
[FR] Let me make fields invisible

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#5940]
### Description

Sometimes we need to hide a field from the editor but still need the data structure available for things like:

- Extracting complex relations out of Blocks into relations fields on the owner element for easier filtering
- Hiding deprecated fields we're not ready to part with yet
- Generating custom search terms that shouldn't be edited by the end-user

Ideally, I think this would be an option on the field layout editor to mark a field as invisible; however, I think it's also enough of an edge-case that just adding events to the Fields service to control what fields are returned from a layout tab would also be just as useful. 

### Additional info

- Craft version: 3.4.15

**Comment by piotrpog** [comment]
If you just need text field, you can use incognito field plugin:
https://plugins.craftcms.com/incognito-field

**Comment by Mosnar** [comment]
@piotrpog I know there are a few solutions out there such as Incognito and Preparse; however, usually I need to hide a relation field. I also think it's small enough of a feature that we may as well generalize it for all fields.

**Comment by brandonkelly** [comment]
This could be solved with field permissions (#947) – you’d just set these fields up so no user groups are allowed to access them. They’d still be visible to admins, but most of the time content managers should not be admins.

**Comment by Mosnar** [comment]
Works for me!
