### ISSUE TITLE
Token's "GraphQL Schema" is misleading when a schema was deleted

### ISSUE THREAD

**Issue by benface** [craftcms/cms#5942]
### Steps to reproduce

1. Create two GraphQL schemas in the CP: Schema 1 and Schema 2.
2. Create a GraphQL token, select Schema 1 in the "GraphQL Schema" field, and save.
3. Delete Schema 1.
4. Visit the token's edit page again.

**Expected result:** The token appears to have no schema associated to it (because it doesn't, the schema was deleted).
**Actual result:** The token appears to be associated with Schema 2.

### Additional info

- Craft version: 3.4.15
- PHP version: 7.4.2
- Database driver & version: MySQL 5.7.26

**Comment by brandonkelly** [comment]
Funny, just fixed the exact same sort of bug in our Guest Entries plugin a few days ago (https://github.com/craftcms/guest-entries/issues/56).

**Comment by brandonkelly** [comment]
Got this fixed up for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.16 is out now with that fix.
