### ISSUE TITLE
get-editor-html with wrong siteId - response 403

### ISSUE THREAD

**Issue by jules1091** [craftcms/cms#5949]
### Steps to reproduce

1. Login with a user, who is an subsiteEditor
2. Try to edit an entry image on a page of this subsite by double click on the image 
3. the get-editor-html request is sent with the wrong siteId (always with ID 1, which is the ID from the main page) and responses 403 "The user doesn’t have permission to edit this element"
![Bildschirmfoto 2020-04-21 um 08 30 56](https://user-images.githubusercontent.com/59639959/79832795-7a6f1280-83aa-11ea-9db1-34ad00829a22.png)

### Additional info
Craft version: 3.4.14
PHP version: 7.2
Database driver & version: MySQL 8.0

**Comment by brandonkelly** [comment]
Hi @jules1091, unfortunately I’m not able to reproduce this.

Please try updating to the latest release and see if that helps. If not, send your `composer.json` and `composer.lock` files into support@craftcms.com along with a database backup, and we can try to reproduce it with your setup.

**Comment by jules1091** [comment]
I sent everything to support@craftcms.com. Thank u!

**Comment by brandonkelly** [comment]
@jules1091 Thanks! Just got this fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#f15fa4ae86862500532635dcb49616c5f4752276 as 3.4.18",
  "...": "..."
}
```

Then run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.4.19 is out now with this fix.
