### ISSUE TITLE
relatedTo still isn't filtering out disabled Matrix blocks

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#5951]
### Description
I thought this issue was fixed in 3.4.12 (https://github.com/craftcms/cms/issues/5849), so I updated the site from 3.3.20.1 to 3.4.16, but the issue persists.

I've got a Materials section and a Disposal Sites section. Disposal Sites have a matrix field where they select which materials the disposal site is related to (so they can add notes to the relation), and I'm displaying the related Disposal Sites on the Material page.

The client just disabled one of the matrix blocks on the disposal site, and that disposal site is still showing up on the Material entry page.

Relation code:

```twig
{% set sites = craft.entries()
    .section('sites')
    .relatedTo({ targetElement: entry, field: 'siteRelatedMaterials' })
    .orderBy('title asc')
    .all() %}
```

Screenshot of Disposal Site in Craft:
![image](https://user-images.githubusercontent.com/1250017/79861526-36e1cc00-83dd-11ea-9e5d-3097e44723d1.png)

Screenshot of the Material entry page on the front end:
![image](https://user-images.githubusercontent.com/1250017/79861616-57118b00-83dd-11ea-9355-6c6b4c9fb46d.png)

Am I missing anything?

### Additional info

- Craft version: 3.4.16
- PHP version: 7.3
- Database driver & version: MySQL

**Comment by brandonkelly** [comment]
Thanks for reporting that, @darylknight!

My [prior fix](https://github.com/craftcms/cms/commit/aae04544ae5eb777dcf9901d4bf563550b08bd8e) was only focussed on the reverse scenario – for example if you already had the Site entry, and you wanted to fetch all of its related Materials. This other direction is fixed now too, for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#dc008610ad709ac5295188af57d025326164001f as 3.4.16",
  "...": "..."
}
```

Then run `composer update`.

**Comment by darylknight** [comment]
Awesome, thank you!

**Comment by brandonkelly** [comment]
Craft 3.4.17 is out now with this fix.
