### ISSUE TITLE
Cannot uninstall plugin if it's not active

### ISSUE THREAD

**Issue by olsp** [craftcms/cms#5953]
### Description

I have some plugins which are not active, when clicking on the settings icon, the only option is to activate it. I need no activate it in order to uninstall it. Why is it not possible to uninstall it while it's not active?

### Steps to reproduce

1. Install a plugin
2. Deactivate it

### Additional info

- Craft version: 3.4.16
- PHP version: 7.3.7

**Comment by brandonkelly** [comment]
Because the plugin itself is responsible for its own deinstallation, and Craft won’t run any plugin code on a disabled plugin. So the only way Craft can call the plugin’s deinstallation code is if it is enabled first.
