### ISSUE TITLE
[FR] Provide Twig Method to Add to End Body

### ISSUE THREAD

**Issue by davist11** [craftcms/cms#5955]
The `css` and `js` Twig tags already exist, but it would be really cool if there were a generic tag to add any code/string before the `</body>` and didn't do any processing to the string being passed in. This is useful for stuff like modals, etc. This is kind of why the <a href="https://plugins.craftcms.com/twig-portal">Twig Portal plugin</a> was created, except you can choose where the contents gets output too. We solved this by creating a custom Twig function `addToEndBody` that hooks into `EVENT_END_BODY`, but it would be pretty cool to see this be a part of core.

```php
public static function add(string $code)
{
    Event::on(
        View::class,
        View::EVENT_END_BODY,
        function(Event $e) use ($code) {
            echo $code;
        }
    );
}
```

**Comment by brandonkelly** [comment]
Just added a new `html` tag, similar to the current [css](https://docs.craftcms.com/v3/dev/tags.html#css) and [js](https://docs.craftcms.com/v3/dev/tags.html#js) tags, but for arbitrary HTML, for Craft 3.5.

```twig
{% html %}
    <p>This will be placed right before the <code>&lt;/body&gt;</code> tag.</p>
{% endhtml %}
```

It will inject the HTML right before `</body>` by default, but you can change the position by adding `at head` or `at beginBody` to the end of the opening tag.

**Comment by piotrpog** [comment]
While we are at it, why not just allow users to insert content into hooks from within Twig template?

https://docs.craftcms.com/v3/extend/template-hooks.html

Never really used these, so maybe there is some obvious reason why :)

**Comment by piotrpog** [comment]
@brandonkelly would it be possible to include this change already to 3.4? I feel i would find a good use for it in my current project but 3.5 seems bit far away.

**Comment by brandonkelly** [comment]
@piotrpog 3.5 is very close.
