### ISSUE TITLE
Set password link doesn't work in headless mode

### ISSUE THREAD

**Issue by FreekVR** [craftcms/cms#5960]
### Description

When running Craft in headless mode, the email sent to users will contain a set password link that returns a 404, if the primary site URL is not the same as the domain the DNS is on or doesn't contain the '/admin' suffix in the site URL.

### Steps to reproduce
There are actually several use cases that don't work.

Decoupled frontend, site URL is set to some other domain than Craft, eg. 
```
'siteUrl'=> 'https://locahost:3000'
'baseCpUrl' => 'https://cms.digitalnatives.test'
'cpTrigger' => 'admin'
```

The activation e-mail upon creating a new account will have this URL:
`https://localhost:3000/setpassword?code=xxx`

However, even with the siteUrl set as follows it won't work, as the 'setpassword'-route doesn't exist in headless mode.

```
'siteUrl'=> 'https://cms.digitalnatives.test'
'baseCpUrl' => 'https://cms.digitalnatives.test'
'cpTrigger' => 'admin'
```
`https://cms.digitalnatives.test/setpassword?code=xxx`

It seems the only workaround for this is to set the siteUrl to "https://cms.digitalnatives.test/admin" but that doesn't make a lot of sense, as I think the siteUrl reflects a frontend rather than the CMS itself?

### Suggested solution
Generate the link using the CpURL + CPTrigger instead of the site URL?

### Additional info
- Craft version: 3.4.x
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Craft will provide a CP activation link if the user has permission to access the control panel. Make sure you are granting that permission, and it will work as expected.
