### ISSUE TITLE
[FR] Create Assets from URL

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#5963]
### Description
I'd love to see an option to upload an asset from a URL rather than selecting a file. This excites me less from the perspective of the UX but more from an extensibility perspective. Creating Assets from a remote source isn't uncommon and it can get pretty nasty if you're having to deal with Asset Fields.

Really, if we could just plop Feed Me's [AssetHelper](https://github.com/craftcms/feed-me/blob/develop/src/helpers/AssetHelper.php) into Craft, that'd get us 90% of the way there.

### Additional info

- Craft version: 3.4.x

**Comment by brandonkelly** [comment]
This idea is covered by #3861 :)

**Comment by Mosnar** [comment]
Love it!
