### ISSUE TITLE
Author isn't a reserved field name, but it should be

### ISSUE THREAD

**Issue by jakedohm** [craftcms/cms#5964]
### Description
Currently you can create a field with the handle `author` and add it to an entry, which can cause confusion because it will conflict with the default `author` alias to `getAuthor()`. I've done this twice in the past week, which says more about me than Craft 😂

### Steps to reproduce

1. Create a field called `author`
2. Add it to an entry
3. Call `entry.author` assuming you'll be accessing your field, and be very confused 😄 

### Additional info
- Craft version: 3.4

**Comment by brandonkelly** [comment]
See #2797

**Comment by brandonkelly** [comment]
For posterity, this is [resolved for Craft 3.7](https://github.com/craftcms/cms/issues/2797#issuecomment-859155102).
