### ISSUE TITLE
Save as draft / Auto save throws error

### ISSUE THREAD

**Issue by Simon-00** [craftcms/cms#5965]
### Description

Hey together,

since a undefinable time range a strange error occurs in the backend when working with entries and it's drafts. The issue appears in complete empty sections and even in sections where no field is attached to. It's throwing an undefined server error when actively clicking on Save Draft or changing field content within the preview mode.

The only error feedback happens in the console log:
`Craft.js:13251 Uncaught (in promise) undefined`

### Steps to reproduce

1. Clicking on 'Save as draft' or changing field content in the preview mode

### Additional info

- Craft version:  Craft Pro 3.4.16
- PHP version: 7.2.10
- Database driver & version: MySQL 5.7.28
- Plugins & versions:

FacebookConnector | 1.4.0
Fix FKs | 1.0.2.1
Linkit | 1.1.11
Navigation | 1.2.3
Neo | 2.7.8
Redactor | 2.6.1
Video Embedder | 1.1.

**Comment by Simon-00** [comment]
Updated the description. The initial error throwing was based on attempted fixes.
So far NO error feedback in logs or debug console.

**Comment by brandonkelly** [comment]
Hi, please write into support@craftcms.com – we can help you from there.
