### ISSUE TITLE
Asset modal optional field data not saved when validation is triggered on a required field

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#5966]
### Description
When attempting to save an asset within a modal window and field validation is triggered, new or changed data that was entered (i.e. in another custom field associated with the same asset) is not saved (despite being displayed) when the validation error is corrected and asset resaved. 

### Steps to reproduce
You will need to have an entry setup that has an asset field and that asset has at least two custom fields one with validation (i.e. "required field").

1. Select an asset (e.g. an image) within an entry and then double click the asset to display the asset modal window
2. Add data within the custom field that is "optional"
3. Save the asset
4. Validation will be triggered on the required custom field (note that data entered into the "optional" field is still displayed as was entered.
5. Correct the validation error (enter data in the required field)
6. Resave the asset
7. Reopen the asset modal (note that the data entered into the "optional" field is now blank and was not saved.

### Additional info

- Craft version: 3.4.16

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just released Craft 3.4.17 with a fix for this.

**Comment by brandonkelly** [comment]
Sorry, there was a bug with that fix (#5970). Just released 3.4.17.1 with a fix for that.
