### ISSUE TITLE
Debug Toolbar - other login methods beside session

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#5967]
### Description
I use the Yii2 Rest API for my project so in certain requests and for those the session is turned off, luckily the debug toolbar itself is able to work without a session.
Unfortunately Craft does not include the modul in case there is no session https://github.com/craftcms/cms/blob/develop/src/web/Application.php#L378-L380, thus I cannot (by default) profile those API requests via toolbar from other machines.

My current work around was to copy your code into a behavior/filter for my [ActiveController ](https://www.yiiframework.com/doc/api/2.0/yii-rest-activecontroller) to make it work.
So my feature request would be either to provide an opportunity to include it by users after the [authmethod](https://www.yiiframework.com/doc/api/2.0/yii-filters-auth-authmethod) was done to check against an identity or at least include the configuration via `craft\helpers\App::debugConfig()`

### Steps to reproduce

1. Use Yii2 `AuthMethod` instead of session based login
2. Try to debug a request in the CP and see the requests are not accessible via debug toolbar

### Additional info

- Craft version: 3.4.x

**Comment by brandonkelly** [comment]
We’ve added basic authentication support for the next 3.5 release (see https://github.com/craftcms/cms/issues/5303#issuecomment-657918281), and I just shuffled things around a bit so that the user is authenticated in time for debug module registration.

**Comment by brandonkelly** [comment]
I’ve decided to make basic HTTP auth something you have to opt into, as it was conflicting with server authorization (#6421). So if you want to use it going forward, you will need to add this to `config/general.php`:

```php
'enableBasicHttpAuth' => true,
```
