### ISSUE TITLE
Installation fails behind HTTPS → HTTP reverse proxy

### ISSUE THREAD

**Issue by blieque** [craftcms/cms#5968]
### Description

I'm using Craft behind a proxy. The public server terminates HTTPS, and forwards just HTTP to Craft's server. I'm doing this so that I can run Craft in it's own Docker container, and terminate HTTPS in the host. My workaround is to run HTTPS between the host and container, which isn't ideal. It's pretty common to terminate HTTPS at some sort of edge node, and forward HTTP to the worker nodes, which I imagine this issue would also apply to.

```
( Client ) --https:443--> ( Server: [ nginx ] --http:8000--> ( Craft Docker container: [ nginx, php-fpm, MariaDB ] ))
```

When the application attempts to call `action/validate-db`, it does so over HTTP. This causes the browser to block the call, as the page was loaded over HTTPS. The root of the cause is relying on Yii's `getIsSecureConnection()`, I think:

- [`Craft.Installer.handleScreenSubmit()`](https://github.com/craftcms/cms/blob/62b9b99fc78b69a127db2d2c9003fd4072f15d3b/src/web/assets/installer/dist/install.js#L67)
- [`Craft.Installer.validate()`](https://github.com/craftcms/cms/blob/62b9b99fc78b69a127db2d2c9003fd4072f15d3b/src/web/assets/installer/dist/install.js#L187)
- [`Craft.postActionRequest()`](https://github.com/craftcms/cms/blob/62b9b99fc78b69a127db2d2c9003fd4072f15d3b/src/web/assets/cp/src/js/Craft.js#L508)
- [`Craft.getActionUrl()`](https://github.com/craftcms/cms/blob/62b9b99fc78b69a127db2d2c9003fd4072f15d3b/src/web/assets/cp/src/js/Craft.js#L447)
- *Assuming `Craft.actionUrl` is populated by [`CpAsset.php`](https://github.com/craftcms/cms/blob/a798b966b1e8200e94e68bc2eb974a786abecde4/src/web/assets/cp/CpAsset.php)*
- [`Craft.actionUrl`](https://github.com/craftcms/cms/blob/a798b966b1e8200e94e68bc2eb974a786abecde4/src/web/assets/cp/CpAsset.phhttps://github.com/craftcms/cms/blob/a798b966b1e8200e94e68bc2eb974a786abecde4/src/web/assets/cp/CpAsset.php)
- [`UrlHelper::actionUrl()`](https://github.com/craftcms/cms/blob/62b9b99fc78b69a127db2d2c9003fd4072f15d3b/src/helpers/UrlHelper.php#L352)
- [`yii\Web\Request.getIsSecureConnection()`](https://www.yiiframework.com/doc/api/2.0/yii-web-request#getIsSecureConnection()-detail)
- [`$_SERVER['HTTPS']`](https://www.php.net/manual/en/reserved.variables.server.php)

Ultimately, I filed this as a bug in Craft because it's not possible for the client or server alone to determine whether or not the connection is secure. Yii should probably also include a note that `getIsSecureConnection()` is not reliable behind a proxy. 

I think the real bug in Craft is that the server is providing a base URL to the client with protocol and domain included. I think this should instead be calculated by JavaScript, using [`Location`](https://developer.mozilla.org/en-US/docs/Web/API/Location).

### Steps to reproduce

1. Set up any situation where the user loads the page over HTTPS in the browser, but the server running the application receives HTTP.
2. Attempt installation. This will fail at the `action/validate-db` step.

### Additional info

- Craft version: 3.4.16
- PHP version: 7.3.17 (fpm-fcgi) from Alpine Linux package
- Database driver & version: MySQL 5.5.5 driver, 10.4.12-MariaDB database
- Plugins & versions: none

**Comment by jasonmccallister** [comment]
@blieque that is strange that you are seeing that error. I have run a very similar setup on AWS ECR and have not experienced issues with the update/project config sync issue. 

One thing that may cause this, if I remember correctly, is to ensure the `$DEFAULT_SITE_URL` is set properly on the docker container. Can you verify that those settings match up?

**Comment by blieque** [comment]
I've updated the issue to clarify the set up a bit better I have two nginx instances, one proxying to the other. It's a weird set-up, I'll grant you, but load balancing could involve something similar.

What are you referring to by "update/project config sync issue"? I wasn't able to get an initial installation going until I changed things around so that the internal proxy used HTTPS as well.

`DEFAULT_SITE_URL` is not set, no, but are you certain that's used? When debugging, I set all of these:

```php
return [
  '*' => [
    // ...
    'aliases' => [ '@web' => 'https://<domain>' ],
    'siteUrl' => 'https://<domain>',
    'cpBaseUrl' => 'https://<domain>',
    'useSslOnTokenizedUrls' => true,
  ],
];
```

Setting these fixed the URLs for loading scripts and images, but the installation broke later on when trying to make an AJAX request.

**Comment by CodeNoir** [comment]
I'm having the same issue with AJAX / XHR requests logging into the CP.  Converting XHR request to HTTP and getting a blocked:mixed-content error.

Has anyone had any luck solving this?

**Comment by benbenbenbenbenben** [comment]
Same issue here. We inherited a project from another agency, and we can't login when we run HTTPS behind an nginx reverse proxy.

**Comment by angrybrad** [comment]
I'm guessing in some/all of these cases, it's because the load balancer/reverse proxy isn't forwarding the https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto header to the Craft installation, which is the standard way to identifying the protocol of the original request (regardless of if HTTPS terminates or not).

**Comment by benbenbenbenbenben** [comment]
@angrybrad yes, I was going to write the same. 

This is exactly what was missing for us.

**Comment by blieque** [comment]
I've just been playing around with nginx config in the proxy server. Adding the following does indeed fix the issue.

```patch
 # Forward admin requests to Craft
 location ~ ^/(admin|cpresources|static|favicon.ico|index.php) {
     proxy_set_header Host $host;
     proxy_set_header X-Forwarded-For $remote_addr;
+    proxy_set_header X-Forwarded-Proto $scheme;
+    proxy_set_header Forwarded "for=$remote_addr;proto=$scheme";
     proxy_pass https://127.0.0.1:10080;
 }
```

I added the [`Forwarded`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded) header as well, which appears to be a standardised replacement for `X-Forwarded-For`, `X-Forwarded-Host`, and `X-Forwarded-Proto`. Craft/Yii still requires the `X-Forwarded-*` headers, but I'll leave the `Forwarded` one in there.

**Comment by angrybrad** [comment]
Glad to hear!  Sounds like it's safe to close this out, then, and thanks for the follow-up.
