### ISSUE TITLE
Ensure cache clear succeeds before proceeding with migrations

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#5969]
As discovered in https://github.com/craftcms/cms/issues/5962, if the cache clearing triggered by a migration fails for some reason, it can be quite catastrophic.

As a safety precaution, perhaps the migration should bail early if the cache-clearing fails?

**Comment by brandonkelly** [comment]
Yii is the one that is doing the cache clearing, so this would need to be fixed there. Make sure to post specific steps to reproduce.
