### ISSUE TITLE
[3.4.17] Saving asset data in HUD fails

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#5970]
### Description

Trying to save image data from HUD fails with this javascript error:

![image](https://user-images.githubusercontent.com/60010597/80275906-e6bc7f80-86e4-11ea-8123-f41b90bc5956.png)

Set up with one custom field like this:

![image](https://user-images.githubusercontent.com/60010597/80275891-c1c80c80-86e4-11ea-8ff0-6bd22d4a91a8.png)

### Steps to reproduce

1. Open asset in HUD
2. Click Save

### Additional info

- Craft version: 3.4.17
- PHP version:
- Database driver & version:
- Plugins & versions:

/Aylin

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just released 3.4.17.1 with a fix.
