### ISSUE TITLE
mail transport types in different environments.

### ISSUE THREAD

**Issue by timrosskamp** [craftcms/cms#5975]
### Description

In one of the sites I develop with Craft, I have a special case: The staging server doesn't support sendmail, so we use SMTP, but I can't use SMTP on the production server, because of hosting restraints. Unfortunately I couldn't find a way to define the mail transport type in an environment variable.

What I'd like to accomplish is to define the setting `transportType` as an enviroment variable, so that I could use Smtp in one environment and sendmail in another.

### Additional info

- Craft version: 3.4
- PHP version: 7.3

**Comment by brandonkelly** [comment]
This is possible by [overriding the `mailer` component](https://docs.craftcms.com/v3/config/app.html#mailer-component) in `config/app.php` – which supports setting values on a per-environment basis:

```php

use craft\helpers\App;

return [
    '*' => [
        // global config here...
    ],
    'staging' => [
        'components' => [
            'mailer' => [
                // Get the stored email settings
                $settings = craft\helpers\App::mailSettings();

                // Override the transport adapter class
                $settings->transportType = craft\mail\transportadapters\Smtp::class;

                // Override the transport adapter settings
                $settings->transportSettings = [
                    'host' => getenv('SMTP_HOSTNAME'),
                    'port' => getenv('SMTP_PORT'),
                    'useAuthentication' => (bool)getenv('SMTP_USE_AUTH'),
                    'username' => getenv('SMTP_USERNAME'),
                    'password' => getenv('SMTP_PASSWORD'),
                    'encryptionMethod' => getenv('SMTP_ENCRYPTION_METHOD') ?: null, // 'ssl' or 'tls' or nothing
                    'timeout' => getenv('SMTP_TIMEOUT') ?: 10,
                ];

                // Create a Mailer component config with these settings
                $config = craft\helpers\App::mailerConfig($settings);

                // Instantiate and return it
                return Craft::createObject($config);
            ],
        ],
    ],
];
```

That said, if email sending is important to you for this site, I’d encourage you to use a transactional email service like [Postmark](https://postmarkapp.com/), which offers a lot of benefits over using your own mail server, and you’d be able to use across all your environments. We even have a [plugin](https://plugins.craftcms.com/postmark) for it.

Here’s a full list of mail adapter plugins to check out: https://plugins.craftcms.com/categories/mailer-adapters

**Comment by alexroper** [comment]
I had trouble getting this code to work. This change worked for me:

```diff
return [
    'staging' => [
        'components' => [
-            'mailer' => [
+            'mailer' => function() {
        ...
-           ],
+           },
        ],
    ],
];

```

**Comment by brandonkelly** [comment]
Doh! Thanks @alexroper. Just updated the example.
