### ISSUE TITLE
`$user->lastPasswordChangeDate` is always `null`

### ISSUE THREAD

**Issue by aNickzz** [craftcms/cms#5978]
### Description

```php
$user = Craft::$app->getUsers()->getUserById($id);
var_dump($user->lastPasswordChangeDate);
// NULL
```

I put a breakpoint here and can see that the value is being set when saving via `{{ actionInput('users/save-user') }}`; https://github.com/craftcms/cms/blob/102c6e3ca7e32f978ed19a594b506efe5914cfb0/src/elements/User.php#L1349
Inspecting `$this->lastPasswordChangeDate` shows a `\DateTime` object and `$record->lastPasswordChangeDate` contains a text version of the same date.

As a workaround, I'm using the Record class instead:

```php
// $user = Craft::$app->getUsers()->getUserById($id);
$userRecord = \craft\records\User::findOne($id);
var_dump($userRecord->lastPasswordChangeDate);
// yyyy-mm-dd hh:mm:ss
```

### Steps to reproduce

1. Get a user account from the `Users` service (see first code block above)

### Additional info

- Craft version: Craft Pro 3.4.9
- PHP version: 7.1.33
- Database driver & version: MySQL 5.7.29
- Plugins & versions: Available on request

**Comment by brandonkelly** [comment]
That value is just not included in the default `SELECT` clause for user queries, since there’s a pretty low chance you’d actually need it.

You can add it in your self by doing this, though:

```php
$user = \craft\elements\User::find()
    ->id($id)
    ->anyStatus()
    ->addSelect('lastPasswordChangeDate')
    ->one();
```

**Comment by aNickzz** [comment]
I'm actually getting the user from an `EVENT_BEFORE_VALIDATE` event, so I'm not able to change the selected fields.

https://github.com/born05/craft-enforcepassword/blob/master/src/Plugin.php#L61

**Comment by brandonkelly** [comment]
In that case you’ll just have to query for it manually, sorry. Not worth adding to every user query in the off chance something needs it.
