### ISSUE TITLE
.env variables not available in control panel

### ISSUE THREAD

**Issue by jwrudzin** [craftcms/cms#5984]
### Description
Variables that I define in my .env file are not appearing in the autocomplete window in the Craft control panel and they are not being replaced properly on the front end when I use them.

### Steps to reproduce

1. Install a fresh copy of Craft CMS 3.4.17.1
2. Add a variable to the .env file
3. In the control panel, enter a $ in a field (such as the general -> system name field), and no autocomplete suggestions come up. Also, if you just enter in an environment variable name anyway (such as $ENVIRONMENT), the variable isn't replaced properly on the frontend.

I was able to fix this issue by going into index.php and replacing lines 15-16:

> $factory = new Dotenv\Environment\DotenvFactory([
>     new Dotenv\Environment\Adapter\PutenvAdapter(),
> ]);
> Dotenv\Dotenv::create(CRAFT_BASE_PATH, null, $factory)->load();

With:

> Dotenv\Dotenv::create(CRAFT_BASE_PATH)->load();

### Additional info

- Craft version: 3.4.17.1
- PHP version: 7.1
- Database driver & version: MariaDB 10.4.12

**Comment by bryantAXS** [comment]
I was also running into this issue!

**Comment by brandonkelly** [comment]
Doh, this is an unintended consequence of craftcms/craft#55. Reverted that so it won’t happen on new projects going forward.
