### ISSUE TITLE
Internal Server Error When Saving Admin Settings

### ISSUE THREAD

**Issue by strandofgenius** [craftcms/cms#5985]
### Description
I'm getting an internal server error every time I save a setting in the admin. I've noticed the error when saving fields and entry types when the environment is in **Staging** or **Production** mode on AWS. Locally I can have it set to staging or production and don't get an error.

I have another site that is still on Craft 3.3.18.1 and this error does not happen. It seems as though it has started happening since we upgraded to Craft 3.4.x.

**Internal Server Error**
Server Error

### Steps to reproduce

1. Add a field or entry type
2. Select any type of field or entry type
3. Save the setting

### Additional info

- Craft version: Craft Pro 3.4.16
- PHP version: 7.2.24
- Database driver & version: MySQL 5.6.40
- Plugins & versions:
Amazon S3 -- 1.2.7
Asset Rev -- 6.0.2
Freeform -- 3.6.5
ImageOptimize -- 1.6.11
Minify -- 1.2.9
Navigation -- 1.3.6
Position Fieldtype -- 1.0.14
Redactor -- 2.6.1
Retour -- 3.1.35
SEOmatic -- 3.2.48
Spoon -- 3.5.2
Sprout Active -- 2.2.0
Super Table -- 2.4.6
Twigpack -- 1.2.0
Video Embedder -- 1.1.4
Wordsmith -- 3.1.2

**Comment by brandonkelly** [comment]
Search `storage/logs/web.log` for `[error]`. Please post the full error message as well as the stack trace that follows it.

**Comment by strandofgenius** [comment]
@brandonkelly I think I sorted it out. This is the first time I've seen an error log in the browser.
Error `file_put_contents(/srv/www/c_lock_craft/releases/20200429145037/storage/config-deltas/delta.yaml): failed to open stream: Permission denied`

It looks like I just need to update the permissions for `/storage/config-deltas`

**Comment by angrybrad** [comment]
Glad you're sorted, @strandofgenius. Some other folders you might want to check for permissions while you're in there: https://docs.craftcms.com/v3/installation.html#step-2-set-the-file-permissions

**Comment by ermradulsharma** [comment]
[1641][-][error][barrelstrength\sproutbaseemail\services\NotificationEmailEvents::handleDynamicEvent] When an entry is saved event does not validate: {"event":["The `EntriesSave` Notification Event only triggers when an Entry is saved in a live scenario.","Saved Entry Element does not match any selected Sections."]} 

this error in my error log file when we save user permission

**Comment by brandonkelly** [comment]
@ermradulsharma That’s unrelated to this GitHub issue. It’s coming from Sprout Email. I asked @BenParizek about it, and he said:

>  That's not necessarily an error. That's just Sprout Email's Notification Event logging that it didn't match a particular request. If multiple Sprout Email Events exist, it logs every one that doesn't match – another thing I'm cleaning up in the next release.

Please post over at https://github.com/barrelstrength/craft-sprout-email/issues if you have any additional comments on it.
