### ISSUE TITLE
[RFC] Propagation per entry

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#5988]
### Description
We're working on a complex multisite/multilanguage set-up with 100 sites from one Back-end.
What would really improve the user experience is an option to set propagation per entry with a ligthswitch. E.g: "Sync this entry with all other sites?"

You can disable them per site using the lightswitches on the right hand site, but in our use case this gives a lot of clutter in the cms and also unnecessary db calls. In some cases, disabling might not be what you want, especially if you have this many sites you probably want the entry not to exists in the other sites it's not supposed to for performance and sanity reasons.

**Comment by brandonkelly** [comment]
Just added a new Propagation Method option for Craft 3.5: “Let each entry choose which sites it should be saved to”.

<img width="542" alt="A section’s Propagation Method setting, with the new “Let each entry choose which sites it should be saved to” option selected." src="https://user-images.githubusercontent.com/47792/80821343-5fac5300-8b8d-11ea-9e95-bb5673000f68.png">

This works much like the “Only save entries to the site they were created in” option – when you initially create an entry, it will only be saved to the site you were looking at on the previous screen. But when you expand the status selector, you will find a new “Add a site…” option, which lets you add additional sites to the entry.

<img width="374" alt="An entry’s expanded status selector, highlighting the new “Add a site…” option" src="https://user-images.githubusercontent.com/47792/80821690-14df0b00-8b8e-11ea-8b20-78a3a5a41132.png">

If you are editing a draft, the new site will be added to the draft immediately, but won’t be added to the source entry until you’ve published the draft.

Here’s a video of it in action:

![Video of the new propagation method in action](https://user-images.githubusercontent.com/47792/80821999-a51d5000-8b8e-11ea-9be6-bad4d98da3be.gif)

**Comment by lenvanessen** [comment]
You are: tha bomb

**Comment by jan-dh** [comment]
Looks great!

**Comment by puck3000** [comment]
Thank you, great feature!

**Comment by vnali** [comment]
thanks @brandonkelly this is awesome! this commit closes [my issue](https://github.com/craftcms/cms/issues/5386) too.  
one question:
if the author of 'off the vine' site is another person and restricted to edit only that 'off the vine' site, if he/she want to has this entry on 'happy lager', i suppose the only way is to ask author of 'happy lager'  to add 'off the wine' site? 
it is not a bad thing though, specially if 'happy lager' is main site and author in 'happy lager' has control over entries and sites. 
actually i am thinking about a way for author of 'happy lager' and other enabled sites for that section to be informed about the entry and ask to have the entry for their sites via CP.

**Comment by brandonkelly** [comment]
@vnali Whoops, sorry I forgot about that issue. It does indeed seem like the same request.


The answer to your question is yes – users are only able to add sites that they have permission to edit. So you would need someone with permission to edit two sites to be the one to add the entry to the second site.

**Comment by seidtgeist** [comment]
@brandonkelly Is it possible to remove entries from sites they’re disabled in? We changed the propagation method of one of our pre-3.5 sections and are on a clean up mission. If there’s no UI for it, any other ideas for a database query or a migration?

**Comment by brandonkelly** [comment]
@seidtgeist Yep it’s possible as of the upcoming 3.6 release – see #7190.

**Comment by seidtgeist** [comment]
@brandonkelly Amazing, thank you and sorry for missing this!
