### ISSUE TITLE
Dropdown UI clipped by screen (inaccessible)

### ISSUE THREAD

**Issue by rjhewitt3** [craftcms/cms#5992]
### Description

When a dropdown has a bunch of options, it runs off of the screen and in-accessible. I've noticed this, particularly where the dropdown is a part of the sticky navigation, like on the Dashboard and in Orders (Commerce only, of course)—this issue applies to all dropdowns of this nature.

<img height="200" alt="Example of Orders Screen" src="https://user-images.githubusercontent.com/6742828/80602950-c864c580-89fd-11ea-9cbd-346c71346a94.png">

### Steps to reproduce

This is a tricky one because you can't just add options to these dropdowns on a whim. However, the following steps should reproduce it reliable for any length dropdown: 

1. Resize your browser height so that it clips the dropdown in question
2. Try and scroll the dropdown (ie you can't).

### Additional info

- Craft version: Craft Pro 3.4.17.1
- PHP version: 7.3.17
- Database driver & version: MySQL 5.7.29

**Comment by rjhewitt3** [comment]
For the time being, I'm going to fix this issue with some custom CSS in the CP:

```
.menu {
    max-height: 80vh !important;
}
```

Presently the max-height is set to the full height of the dropdown, which is forcing it off-screen. Looks like this is being calculated by JavaScript and the equation for max-height just needs to be refactored.

**Comment by brandonkelly** [comment]
This must have been fixed somewhere along the way, as I’m not able to reproduce. If you remove your custom CSS, is it still broken for you?

![A dropdown menu with a scrollbar](https://user-images.githubusercontent.com/47792/89112280-61e4ae80-d415-11ea-9643-4967d980e23d.png)

**Comment by rjhewitt3** [comment]
@brandonkelly This is still happening for me actually...nothing seems to have changed.

**Comment by brandonkelly** [comment]
@rjhewitt3 What browser are you using?

**Comment by rjhewitt3** [comment]
@brandonkelly I'm running Chrome 84.0.4147.105 on MacOS 10.15.5

**Comment by brandonkelly** [comment]
Hm, we aren’t able to reproduce. Can you try on another computer, and within a private window (to rule out Chrome extensions)?

**Comment by rjhewitt3** [comment]
@brandonkelly After trying a couple of different installs, it does appear to be isolated to this one in particular. As we continue to work on it, I'll keep you posted if we uncover anything that implicates native code.

**Comment by brandonkelly** [comment]
Cool, thanks for checking. Maybe some custom CSS is interfering, e.g. via the [Control Panel CSS](https://plugins.craftcms.com/cp-css) plugin.
