### ISSUE TITLE
Modal UI clipped by screen (inaccessible)

### ISSUE THREAD

**Issue by rjhewitt3** [craftcms/cms#5993]
### Description

Modal vertical positioning has been an issue for quite a while now, where models are running completely off-screen, or in some cases only partially off-screen. _This problem seems to be more often an issue on small screens._

### Steps to reproduce

1. On any table-view click the "Customize" button to customize the table columns.

### Additional info

- Craft version: Craft Pro 3.4.17.1
- PHP version: 7.3.17
- Database driver & version: MySQL 5.7.29

**Comment by brandonkelly** [comment]
Related to #3781

**Comment by brandonkelly** [comment]
This was fixed in Craft 4.3, released earlier this week 🎉
