### ISSUE TITLE
Validate Matrix block fields on save

### ISSUE THREAD

**Issue by joshuabaker** [craftcms/cms#5996]
When you don’t add a block type loading the entry editor results in an exception; `At least one block type is required.`

Please can we validate this when saving the field and not on the output of the field.

Edge case would be deploying this without checking and preventing people from accessing other fields.

**Comment by brandonkelly** [comment]
Good call. Added for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.18 is out now with this change.
