### ISSUE TITLE
Feature Request / Enhancement: Add configuration option which allows you to disable HTTP/500 page when CraftCMS determines that project-sync needs to be ran

### ISSUE THREAD

**Issue by BradyBonnette** [craftcms/cms#5997]
Would it be possible to add a configuration option that would allow you to disable the HTTP/500 page (and subsequent Call To Action page on /admin) when CraftCMS determines that project-sync needs to be ran?

Here is my use case which led to the feature request. I currently have a CraftCMS project that is hosted in AWS ECS. When a deploy is started, part of the deploy process is to run migrations and then subsequently project-sync. If those run successfully, the build process continues and launches the new CraftCMS instances into the load balancer. However, during this period of time, there's still a chance that the old CraftCMS instances still on the load balancer (pre-connection-draining) will still serve traffic. As a result, if a user ends up on one of the old instances before connection draining starts and after project-sync has ran, Craft will determine that project-sync needs to be ran and throws HTTP/500's. They will continue to see HTTP/500 from those old instances until the load balancer transfers their connections to one of the new instances, where the error message will no longer show up. The window of time between the old instances fall out of rotation and the new instances start taking over can be at least 30 seconds, so there's a decent chance that someone would see it at some point.

I suppose the only caveat here would be if your site throws non-project-sync-related HTTP/500 messages because of lacking fields or the addition of new fields or the like.

**Comment by brandonkelly** [comment]
As of Craft 3.5, the site no longer goes down when there are pending project config changes, so this can be safely closed.

**Comment by BradyBonnette** [comment]
Awesome, thanks for following up :)
