### ISSUE TITLE
Forgot password not handling email errors properly

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#6]
#### Environment:

- Craft version: 3.x
- PHP version: 7.x
- Database driver & version: n/A
- Plugins & versions:

#### Description:

If email isn't configured properly (phpmail, can't connect to SMTP, etc.), using the "forgot password" logic on the login page won't gracefully display an error, but a 500 ISE will be generated for the request.

#### Steps to reproduce:

1. Set SMTP to invalid credentials under Settings->Gereral.

2.  Try to use "forgot password" logic on login page.

**Comment by brandonkelly** [comment]
Looks like this was fixed by 98a75020f0235237ed1e2fcde1fcdec6a91d3d12
