### ISSUE TITLE
Security - Improve user enumeration protection

### ISSUE THREAD

**Issue by pierrestoffe** [craftcms/cms#6000]
### Description

A penetration test we had this week revealed that it was possible to know whether a user existed or not in the CMS even if _preventUserEnumeration_ is set to _true_. What they noticed is that the response after submitting the login form with a username that exists (even if the password is wrong) was always longer than for a username that does not match any user.

For example, if john@doe.com matches an existing account, the response will take 1 second to be available even if the password is wrong, while the response for a login attempt with doe@john.com, an account that does not exist, will be available within 700ms (these response times are inaccurate, I'm using them as an illustration).

The solution that they gave us is to include a random timer during the verification. This means that any login attempt would be responded to after 1.2s, 1.6s, 1.4s, 1.3s, 1.2s, 1.8s,... and you wouldn't be able to tell whether an account exists based on the response duration.

This is far fetched and obviously doesn't look like a priority thing to address, but still wanted to mention it in case anyone had very high security concerns.

### Additional info

- Craft version: 4.5.x-beta

**Comment by angrybrad** [comment]
I'm not able to reproduce this, @pierrestoffe.  You can see a random sampling of requests with a combination of existing users with bad passwords and non-existing users with no consistency between them.

We add a random delay between 0 and 1.5 seconds for _all_ login attempts to help mitigate vectors like this: https://github.com/craftcms/cms/blob/develop/src/controllers/UsersController.php#L141

Plus, for users that don't actually exist (or no password is supplied), we run a known password hash through the same logic that a valid login attempt would do to make it even harder to tell the difference:

https://github.com/craftcms/cms/blob/develop/src/controllers/UsersController.php#L143-L147

<img width="1782" alt="CleanShot 2020-05-01 at 20 24 13@2x" src="https://user-images.githubusercontent.com/61869/80854024-cbbca480-8be9-11ea-9ec6-cc9c22342ece.png">

If they are able to provide additional info or steps on how we could reproduce, just reply back here and I can re-open the ticket.

**Comment by Leeroy-agency** [comment]
There is still an issue with the user enumeration, if the Lost password email cannot be sent then it's displaying an error and we then know that the user exists.

![image](https://user-images.githubusercontent.com/65175280/146817801-515291d5-0a6c-4d1e-9b7d-d371b1664846.png)

**Comment by brandonkelly** [comment]
@Leeroy-agency Thanks for pointing that out! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.27 is out now with that fix.
