### ISSUE TITLE
User account reverts to original email after activating with new email

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/cms#6001]
### Description

Had a user contact us yesterday because he had created his account with an incorrect email address. Updated the user account with the correct email and resent the activation email, but after activating the account reverted to the original email address.

### Steps to reproduce

1. Create an account with one email address and send activation email, but do not activate.
2. Update account with a new email address, then send new activation email.
3. Activate account using new activation email, then view CP edit user page. Email address has reverted to the first one used to register.

### Additional info

- Craft version: Pro 3.4.17.1
- PHP version: 7.4.5
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
Fixed this for the next release. Thanks for reporting!

**Comment by brandonkelly** [comment]
Craft 3.4.18 is out now with this change.
