### ISSUE TITLE
Cannot update Craft - Composer

### ISSUE THREAD

**Issue by circa1977** [craftcms/cms#6003]
### Description

I've run `composer clearcache` and deleted the `vendor` dir and `composer.lock`. I've run `composer install -vvv` and `composer update -vvv`.

It hangs here:

```
Reading /Users/markreeves/.composer/cache/repo/https---repo.packagist.org/provider-vlucas$phpdotenv.json from cache
Resolving dependencies through SAT
Looking at all rules.
Something's changed, looking at all rules again (pass #44)
```

I updated `phpdotenv` to the latest version in my `composer.json` (or 3.0, per the latest Craft `composer.json`) and Composer breezes past it then. But then it hangs on the next one:

```
Reading /Users/markreeves/.composer/cache/repo/https---repo.packagist.org/provider-phpoption$phpoption.json from cache
Resolving dependencies through SAT
Looking at all rules.
Something's changed, looking at all rules again (pass #44)
```

I don't see `phpoption` in `composer.json` to specify a version, or how many more of these I'm going to encounter.

### Additional info

- Craft version: 3.4.2
- PHP version: 7.4.2
- Database driver & version:
- Plugins & versions:

```
"craftcms/aws-s3": "1.2.7",
"craftcms/cms": "3.4.2",
"craftcms/commerce": "3.0.5",
"craftcms/commerce-stripe": "2.2.3",
"craftcms/feed-me": "4.2.0.1",
"craftcms/redactor": "2.5.0",
```

**Comment by circa1977** [comment]
I increased PHP's `memory_limit` from `2G` to `4G`, though Activity Monitor's not showing more than `800MB` consumed. After reading [this thread](https://github.com/composer/composer/issues/7051), I rolled Composer back to `1.7.3`. Still stuck on `pass #44`.

**Comment by circa1977** [comment]
I did a find in my `vendor` folder for `phpoption`. Aside from Craft & Craft Commerce, there was one other instance, in [a dependency](https://packagist.org/packages/zbateson/mail-mime-parser) of one of [my plugins](https://packagist.org/packages/clearbold/craft-campaignmonitor-transactional).

I updated the dependency's version to the latest in my plugin. Still stuck on `pass #44`. I removed my plugin from `composer.json`. Still stuck on `pass #44`.

After removing all my plugins from `composer.json`, I was able to run `composer install`. I'm hoping to add those one by one to see where things break down.

However, I now have no output when I run `./craft` :)

**Comment by circa1977** [comment]
OK, that was `Dotenv` failing. I switched my `composer.json` back to just the following and can access Craft. Now I need to troubleshoot plugin conflicts.

```
  "require": {
    "craftcms/aws-s3": "1.2.7",
    "craftcms/cms": "3.4.17.1",
    "craftcms/commerce": "3.1.3",
    "craftcms/commerce-stripe": "2.3.0",
    "craftcms/feed-me": "4.2.2",
    "craftcms/redactor": "2.6.1",
    "vlucas/phpdotenv": "^2.4.0"
  },
``

**Comment by circa1977** [comment]
Adding this one and `dotenv` is hung on `pass #89`: https://github.com/clearbold/craft-pay-invoice-stripe

Taking that back out, I'm getting this every time I run `composer update`:

```
[340.2MB/6.87s] Reading /Users/markreeves/.composer/cache/repo/https---repo.packagist.org/provider-vlucas$phpdotenv.json from cache
[820.6MB/21.75s] Resolving dependencies through SAT
[820.7MB/21.76s] Looking at all rules.
[822.3MB/23.14s] [822.5MB/24.45s] Something's changed, looking at all rules again (pass #2)[822.5MB/24.45s]
```

I got my other plugins installed and then removed the `stripe/stripe-php` dependency from my plugin's `composer.json`, as this site has Commerce installed, with its own dependency.

I was then able to install the plugin.

I do have this plugin installed on another site that doesn't have Commerce. I'm wondering if there's going to be a `dotenv` conflict there with my `stripe/stripe-php` dependency?

**Comment by brandonkelly** [comment]
Seems like a Composer bug. Can you post an issue over at https://github.com/composer/composer/issues?
