### ISSUE TITLE
Default values for "Number" type fields do not get checked/normalized, causing an error when creating a new entry draft 

### ISSUE THREAD

**Issue by rhlt** [craftcms/cms#6006]
### Description

When you create a "Number" type field and give it a default value, that value does get saved into the database as-is, without any form of check or normalization whatsoever.

If the default value is not a valid number, (try "asdf" or whatever, or even "1,99" and things like that), then when you try to create a new entry of a type that has that field, you will get an error: either simply "Internal server error" (Dev mode disabled, as on demo.craftcms.com), or something that translates to "Could not save draft: (Field name) must be a number" (Dev mode enabled). This completely prevents you from creating new entries of this type.

### Steps to reproduce

1. Create a new field of type "Number" and give it a default value that is not a valid number;
2. Link that field to an entry type;
3. Try to create a new entry of that type;

### Workaround

Make sure that the default value of a "Number" field is a valid number, using a period as decimal separator regardless of language setting.

### Some background, and a suggested solution

The project I am working on is in Dutch. Keep in mind that Dutch officially uses a comma as a decimal separator, like "1,99". The thousand separator, if used--officially, it should only be used for numbers over _ten_ thousand--is a period or a (narrow) space. Normally, Craft CMS accepts values like "1,99" in number fields when its language is set to anything other than English, and automatically displays those numbers with a comma.

However, in practice, using a period like "1.99" is extremely common in the Netherlands, and one headache that Craft's way of handling numbers causes, is that it converts "1.99" to "199,00"! (Assuming a number field with 2 decimals and Craft being set to a language other than English.) This is important to note, because it quickly teaches users like me and my customers to _always_ use a comma as a decimal separator, and never a period. But then you need set a default value for a number field, which you enter with a comma like you're taught, and here we are.

So, to fix this, please:

- Properly check and normalize whatever is entered in the "Default value" box when a "Number" field is created, and also whenever it is edited;
- For backward compatibility: When creating a new entry (including as draft), check and normalize the default values, and if the default value is not valid: ignore it and create the entry with an empty value without explicitly throwing an error that would prevent creation (even if the field is "required", at least for drafts);
- Change normalization logic to allow both the period and comma to be used as decimal separator, regardless of language setting. (I have had to handle this myself, changing number fields to plaintext fields and writing additional logic to normalize numbers, in a previous project where the customer would not accept Craft's current behavior.) If you expect problems with people intending something to be a thousand separator, you could keep current behavior ("1,000" or "1.000" = "1000" instead of "1") if, and _only_ if, (1) the entered value has at least three digits after the last period or comma (there is no way "1.99" or "1,99" could have been intended as "199"), (2) the field allows values of 1000 or over, and (3) the field allows no more than two decimals. I would not consider this last part _strictly_ necessary (telling people not to expect good things to happen when they use thousand separators, i.e. "1.000" or "1,000" is always "1", is good enough for me) but adding it might be the better for backward compatibility.

Thank you very much for your consideration!

### Additional info

- Craft version: 3.4.9 (that's what you get on demo.craftcms.com, though I found no mention of this in release notes for newer versions), also encountered on 3.4.2 (my current project).
- PHP version: (whatever demo.craftcms.com runs)
- Database driver & version: (same)
- Plugins & versions: (none, I assume)

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just fixed this for the next release.

- You can now set Default Value, Min Value, and Max Value settings to localized number formats, and they will be normalized accordingly.

- You’ll get a validation error if a non-numeric number is entered in the Default Value setting.

**Comment by brandonkelly** [comment]
Craft 3.4.18 is out now with this change.
