### ISSUE TITLE
[FR] fetch sites through graphQL

### ISSUE THREAD

**Issue by michtio** [craftcms/cms#6009]
### Description

Currently there is no option to fetch all the sites the Craft instance has. This can be useful to creating better faceted searches where a site has multiple divisions / subsites, but on the mainsite you want to offer a search with the possibility to select/filter per branch/site.

Similar to `craft.app.sites.getAllSites()`

**Comment by andris-sevcenko** [comment]
Thanks for reporting that! This issue is pretty much the same as #5082 so I'll close this in favor of that issue, where you can track the progress of this!

**Comment by rtrudel** [comment]
Sorry to reopen this issue, but this seems to have never been implemented, at least it still doesn't seem to be possible via the documentation and the explorer. Still planned?

**Comment by davidhellmann** [comment]
It would still be interesting to have that. It would be possible to get all sites in general, and also to have a site object at the entry itself to access certain things. I currently have a use case where I would need the base URL of the site.
