### ISSUE TITLE
[FR] Ability to use a relationship field title as an orderBy option

### ISSUE THREAD

**Issue by gdubois414** [craftcms/cms#6010]
### Description
Currently, trying order an entry query by a relationship field results in a Database Exception error. There are times however, when there is a need to do exactly that. For instance, I have an app that let's users create quotes. When they create the quote, they choose a dealer. The dealers are in a separate section and set as a relationship field. Now, when the user is looking at a table of quotes, they cannot sort the data by that dealer field.

The ability pass in something like 'dealer.title' into the orderBy parameter would b extremely helpful.

### Additional info

- Craft version: 3.4.16

**Comment by brandonkelly** [comment]
To do that, you’d have to join the dealer entry into the query, first:

```twig
{% set dealerField = craft.app.fields.getFieldByHandle('dealer') %}
{% set quotes = craft.entries()
  .section('quotes')
  .innerJoin('{{%relations}} dealer_relation', [
    'and',
    '[[dealer_relation.sourceId]] = [[elements.id]]',
    {
      'dealer_relation.fieldId': dealerField.id,
      'dealer_relation.sortOrder': 1
    }
  ])
  .innerJoin('{{%content}} dealer_content', '[[dealer_content.elementId]] = [[dealer_relation.targetId]]')
  .orderBy('dealer_content.title')
  .all() %}
```

Alternatively, you could create a [Preparse](https://plugins.craftcms.com/preparse-field) field that stores the first related dealer’s title, and then order by the Preparse field instead. That would have the added benefit of making the quotes sortable by dealer in the control panel as well.

Here’s the template you would use for that field:

```twig
{%- set dealer = element.dealer.one() -%}
{{- dealer.title ?? '' -}}
```
