### ISSUE TITLE
Preview action disabled when Uploaded By column not empty

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/cms#6012]
### Description

In asset indexes, when the *Uploaded By* column is visible and not empty for the selected asset, the *Preview* action is disabled.

### Steps to reproduce

1. From an asset index, click the *Customize* button and enable the *Uploaded By* column.
2. Select an image that has an empty *Uploaded By* column, then view the actions menu. *Preview* is available as expected.
3. Select an image that has a user associated in its *Uploaded By* column, then view the actions menu. *Preview* is disabled.

### Additional info

- Craft version: Pro 3.4.17.1
- PHP version: 7.4.5
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 3.4.18 is out now with a fix.
