### ISSUE TITLE
Date fields in tables maintain data even after deletion

### ISSUE THREAD

**Issue by kerns** [craftcms/cms#6017]
### Description
When I clear a date from a date field in a table I would expect that field to eval `null` or `0` or `false` ...or do basically anything but return the last stored date value, which it does now for some reason.

Here is a quick test for giggles wherein {{endDate}} is rendered and I feel it should not be. This is after a save.

<img width="1140" alt="Screen Shot 2020-05-04 at 11 36 19" src="https://user-images.githubusercontent.com/20254/80955116-f3d12100-8dfe-11ea-8200-9ce785b309c1.png">

### Additional info
PHP 7.4.4
MySQL 5.6.47
Craft Pro 3.4.17.1

**Comment by brandonkelly** [comment]
The cell value will in fact be `null`. How are you defining that `endDate` variable?

**Comment by andris-sevcenko** [comment]
@kerns you're probably running into a quirk in how Twig applies the `date` filter.
> If the value passed to the date filter is null, it will return the current date by default. If an empty string is desired instead of the current date, use a ternary operator

(from https://twig.symfony.com/doc/3.x/filters/date.html)

**Comment by kerns** [comment]
> @kerns you're probably running into a quirk in how Twig applies the `date` filter.
>  If the value passed to the date filter is null, it will return the current date by default. If an > empty string is desired instead of the current date, use a ternary operator

Thank you @andris-sevcenko! This was of course exactly the issue. And it makes sense that it is this way but I am so used to seeing a date filter on a date field that I think I was blind to it.

> The cell value will in fact be `null`. How are you defining that `endDate` variable?

@brandonkelly Sorry, Brandon! All good. But hey, maybe another opportunity to expand the docs ;-)? https://docs.craftcms.com/v3/dev/filters.html#date A colored call-out "TIP" noting this behaviour with date filters might be good.

A similar call-out "tip" saved my life yesterday.

<img width="862" alt="Screen Shot 2020-05-07 at 10 08 35" src="https://user-images.githubusercontent.com/20254/81270602-443cbe80-904b-11ea-939d-673f899caf82.png">
