### ISSUE TITLE
Admin table persists reference to deleted row in checked items

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/cms#6018]
### Description

After deleting an address from a CP customer page, it remains selected if its checkbox was selected when deleted, preventing actions on other orders until the page is reloaded. Probably not a common problem, but a little confusing when it does occur.

### Steps to reproduce

1. From CP customer page, select the checkbox of an address, then delete the selected address.
2. Select the checkbox of another address, then try to select one of the *Set as Primary* actions. Both are grayed out and disabled. Will be reenabled after reloading.

### Additional info

- Craft version: Pro 3.4.17.1
- PHP version: 7.4.5
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Commerce Pro 3.1.3

**Comment by nfourtythree** [comment]
Hi @jmauzyk 

Thank you for bringing this to our attention. This was an issue with something within Craft rather than Commerce.

A fix has been pushed and will be included in the next release.

Thanks!

**Comment by brandonkelly** [comment]
Craft 3.4.18 is out now with this fix.
