### ISSUE TITLE
Allow testToEmailAddress directly via constant

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#6019]
Sending emails can often be quite sensitive between environments.
In my config I usually end up with something like:

```
<?php

return [
    '*' => [
        'testToEmailAddress' => getenv('TEST_TO_EMAIL_ADDRESS'),
    ],
    'local' => [

        // Ensure we don't send emails locally
        'testToEmailAddress' => getenv('TEST_TO_EMAIL_ADDRESS') ?: 'developer@domain.com',
    ],
    'development' => [],
    'production' => [],
];
```

Even with this, I'm always triple checking between my env, and `general.php` to make sure nothing is missed.

Since it can be so sensitive (eg accidentally sending emails while testing), I thought making this set via a `CRAFT_` php constant would be a nice addition. 

```
<?php
define('CRAFT_ENVIRONMENT', getenv('CRAFT_ENVIRONMENT') ?: 'production');
define('CRAFT_TEST_TO_EMAIL_ADDRESS', getenv('CRAFT_TEST_TO_EMAIL_ADDRESS'));
```

Would just make it dead-simple to check without having to match up config with env.
Open to any other suggestions as well.

**Comment by brandonkelly** [comment]
In general we try to avoid relying on additional PHP constants whenever there’s a decent alternative. As this is already a config setting, what exactly is the benefit to adding a PHP constant for it?

Not sure how this would help you, but you could go with your PHP constant and then just pull that into your config setting value.

```php
return [
    '*' => [
        'testToEmailAddress' => CRAFT_TEST_TO_EMAIL_ADDRESS,
    ],
    // ...
];
```

**Comment by timkelty** [comment]
Yeah, fair point.
