### ISSUE TITLE
Can't delete an asset from its detail page

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#6020]
<img width="462" alt="Screen Shot 2020-05-04 at 3 11 25 PM" src="https://user-images.githubusercontent.com/18329/81003958-aa41ff80-8e19-11ea-853f-ae6c8f33b212.png">

I would expect "Delete Asset" in the dropdown, like on entries:

<img width="421" alt="Screen Shot 2020-05-04 at 3 12 47 PM" src="https://user-images.githubusercontent.com/18329/81004032-c2b21a00-8e19-11ea-9191-268b6a2ab5a4.png">

**Comment by brandonkelly** [comment]
Thanks for the suggestion! Just added this for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.18 is out now with this change.
