### ISSUE TITLE
Storing plugin settings in DB

### ISSUE THREAD

**Issue by hannahwoodward** [craftcms/cms#6027]
### Description

I'm writing a plugin and I'd like to be able to store two of the settings in the DB, so that they can be edited by users (and so I wouldn't want to store the settings in project.yaml). I can't find much on this in the docs & it looks like the settings column has been removed from the plugins table. Adding a new table just for two settings seems a little excessive (and maybe it would almost be worth going down the route of just storing the data in a new Global set)... Is there anything I've missed from the docs?

### Additional info

- Craft version: 3.4.17.1

**Comment by brandonkelly** [comment]
Yeah you are pretty limited with how plugin settings are accessed & stored if you use the built-in plugin settings system.

You are free to add your own settings page and set up the storage of it yourself though. It would just be built like other control panel views, and the form would need to post to your own controller.

Alternatively, sure you could manage the settings in a global set, and just pull in the global set’s values when they are needed from your plugin.
