### ISSUE TITLE
Discrepancy between plain text Field Limit & Column Type

### ISSUE THREAD

**Issue by proimage** [craftcms/cms#6030]
### Description
When creating a plain text field with no defined "Field Limit", but with the "Column Type" set to `varchar (255B)`, I can save 255 characters of text into the field. Trying to save more results in a (proper) field error in the Edit Entry form.

When I go to edit the field to give it a "Field Limit" of 255 characters, I get the error: "Field Limit is too big for your chosen Column Type." I have to take the "Field Limit" down to 63 characters before I am allowed to save it.

Why the discrepancy?

### Steps to reproduce

1. See above

### Additional info

- Craft version: 3.4.5
- PHP version: 7.0.28
- Database driver & version: MySQL 5.5.5
- Plugins & versions: irrelevant

**Comment by brandonkelly** [comment]
Because the column type setting is in _bytes_, not characters, and many unicode characters are multi-byte. To be completely safe, Craft will require the column has enough room for each character to be 4 bytes long (which is what is needed if storing emoji or glyphs).
