### ISSUE TITLE
Feature Request: Theme Selector

### ISSUE THREAD

**Issue by jarendogma** [craftcms/cms#6033]
I it would be great to have something like a theme selector.

That means in the backend, a theme is not more than a shortcut to a folder inside the templates folder. 
From the visual point of view – very similar to the current sites creation.

The following fields would be required:
- A title field
- A handle field 
- A template folder path field 
- A screenshot upload field
- primary light switch (which theme is usually loaded)

Wherever you choose a template for a page, you would just select the file inside the theme folder.
Craft then searches for this template in the selected theme folder. If it don't exist, the main template folder is searched.

The user can change the theme if he has the rights.

Here are some scenarios, for what it would be great:
- You are planning a redesign. To do this, you can create a special user group that can change the theme. You add some users to that user group so they can activate the new design for discussion.
- You want to give your users more personalization options. So they have a few themes where they can select from.
- You want to change just a specific thing with another theme. For that you could do a simple twig if request. For example, you want to add a new block to the page, which should only be seen by those with the "Beta" theme activated.

These are just a few ideas, I am sure there are many more out there!

**Comment by brandonkelly** [comment]
What you are describing here could be pulled off with custom [template roots](https://docs.craftcms.com/v3/extend/template-roots.html), especially with a couple changes coming in 3.5 (see #6015).
