### ISSUE TITLE
./craft resave/entries --limit=1 behaving weirdly

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#6036]
### Description

Running `./craft resave/entries --limit=1` shows 12568 results. I think this is becuase the Yii count method doesn't take into limit or any other filter?

![Screen Shot 2020-05-07 at 18 05 25](https://user-images.githubusercontent.com/25124/81270180-ae765300-908d-11ea-9b6c-140364a4a446.png)

![Screen Shot 2020-05-07 at 18 06 27](https://user-images.githubusercontent.com/25124/81270198-b504ca80-908d-11ea-8022-e95ee8278617.png)

### Steps to reproduce

1. run `./craft resave/entries --limit=1`
2.

### Additional info

- Craft version: 3.5 beta 1
- PHP version: 7.4
- Database driver & version:
- Plugins & versions:

---

Possibly related: https://github.com/yiisoft/yii2/issues/13846

**Comment by brandonkelly** [comment]
Fixed the output for the next release - thanks!

**Comment by brandonkelly** [comment]
Craft 3.4.19 is out now with this fix.
