### ISSUE TITLE
Craft does not account for daylight savings

### ISSUE THREAD

**Issue by hascoulijn** [craftcms/cms#6037]
### Description

When I output the current date in Twig using the date filter `{{ now|date('H:i') }}` I get the time of my timezone minus one hour, so without daylight savings being taken into account. My server time is set correctly to my current timezone taking into account daylight savings. My timezone in the CP is set to UTC+2 Europe/Amsterdam but differs from my actual server time.

### Steps to reproduce

This may be hard to reproduce as every environment might differ and I'm not sure if this is a Craft related problem or  a server issue, but as it stands it seems to be related to Craft where it does not correctly take daylight savings into account for each timezone. This might also influence when postdates are set into the future.

1. Set timezone on server to Europe/Amsterdam.
2. Set timezone in General Settings to UTC+2 (CEST) - Europe/Amsterdam.
3. Output current time with the twig date filter in your template `{{ now|date('H:i') }}`.
4. See difference.

### Additional info

- Craft version: 3.4.18
- PHP version: 7.4.5
- Database driver & version: MySQL 14.14
- Plugins & versions: Wordsmith, Asset  Rev, Minify, Imager-X

**Comment by zizther** [comment]
It would be interesting to see how others manage this one, does everyone update each site based on the timezone change when functionality of the site requires accurate timezone matching.

**Comment by hascoulijn** [comment]
> It would be interesting to see how others manage this one, does everyone update each site based on the timezone change when functionality of the site requires accurate timezone matching.

That's a very interesting point you make. The issue here was that I wanted to output the amount of time ago a post was published. So it would take the publish date (server time) and compare it to your current system time, which is not the right way since the publish date would also have to be converted to the user's system time since a post is globally published at one time and should be visible in a timezone that's 6 hours behind for example.

**Comment by zizther** [comment]
Mine is similar in the sense we have some caching based on an entries expiry date, and depending on if we are GMT or BST it can be an hour out depending on what the setting in Craft is.

I don't know if there is a way to match is against what the server is, or if this has to be manually managed for the time being.
Just wondering how this could be automated so it takes out the worry from having to updated multiple sites on the day of the timezone change between standard and summer timezones.
