### ISSUE TITLE
Date only custom fields on element indexes show 00:00 for today's date

### ISSUE THREAD

**Issue by circa1977** [craftcms/cms#6038]
### Description

I have a Delivery Date field that I've configured to show "Date only." (Delivery Time is a separate field.) I've enabled this in the Orders screen. It's showing 12:00am for orders with today's date as delivery date. Can this respect the "date only" configuration so it does not show a time?

- Craft version: 3.4.17.1

**Comment by brandonkelly** [comment]
Just fixed this for the next Craft release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#c0b2cfc9becce2b00f7ea5a1c85cf0c45ffcd2f9 as 3.4.18",
  "...": "..."
}
```

Then run `composer update`.

**Comment by circa1977** [comment]
Thanks, @brandonkelly!

**Comment by brandonkelly** [comment]
Craft 3.4.19 is out now with this fix.
