### ISSUE TITLE
Jquery 3.5.0 breaking bootstrap collapse, fixed in 3.5.1

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#6039]
### Description
Jquery 3.5.0 has a problem that breaks the bootstrap collapse we are using. It's fixed in 3.5.1.
Can you please update to that version asap?

### Additional info

- Craft version: 3.4.18

**Comment by brandonkelly** [comment]
The copy of jQuery that is bundled with Craft is only meant to be used as a control panel dependency. It’s not intended to be used on the front-end. I’d suggest you start including your own copy in your project, at the very least so you don’t have to worry about stuff like this.

That said, I just updated Craft’s jQuery version to 3.5.1 for the next release.

You can get it early by changing your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#13919e62e1e6e97a1f13b25e9cf9a664ed2ed699 as 3.4.18",
  "...": "..."
}
```

Then run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.4.19 is out now with jQuery 3.5.1.
