### ISSUE TITLE
Problem with saving assets in mutlisite setup

### ISSUE THREAD

**Issue by sarahschuetz** [craftcms/cms#6040]
### Description
We have a project with two language specific sites (englisch and german), with english being our primary site.
This project has a lot of images, so we decided to structure them and use the _Restrict uploads to a single folder?_ option for all our asset fields.
Our upload location is `{section.handle}/{slug}`
_Relate asset from a specific site?_ and _Manage relations on a per-site basis_ are both off.

So for most of our entries this work great, and all the images are saved to the correct folders. However we are experiencing problems as soon as the slug of the german and the englisch site differ:

1. We create a new  **german** entry (not primary site!)
2. Select an asset for one of the asset fields:
3. Asset List is empty -> expected since we just created the entry and haven't uploaded any assets to the slug-specific folder yet.
4. We upload and select an image.
5. On the same entry, we want to select the same image again for a different asset field.
6. The asset list is again empty and we cannot select the image we just uploaded.

When editing assets on the englisch site (primary site) everything works fine.

On further investigation we found out that in _Assets_ both folders (one for the german slug and one for the english slug) are created, but images are always saved to the folder with the english slug. Since we are not managing our assets on a per site basis, it makes perfect sense to save the images to the folder using the slug of the primary site. However, when reading the list of available images it seems that the slug of the current language is used which results in no images being found.

For now we are fine selecting and updating our assets only on the primary site, but it would be nice to be able to do it in either language since it should make no difference. Or am I missing something?

### Additional info

- Craft version: 3.4.17.1
- PHP version: 7.2.24
- Database driver & version: MySQL 8.0.20

**Comment by brandonkelly** [comment]
Try changing your upload location to:

```twig
{{ section.handle }}/{{ craft.entries().id(object.getSourceId()).site('en').anyStatus().one().slug ?? slug }}
```

(Replace `en` with your actual primary site handle, if different.)

That will fetch the entry in the primary site (using the source entry ID in the event that it’s a draft), and use its slug, regardless of which language is currently selected.

Alternatively, you could just group assets by their entry source ID rather than their slug:

```
{section.handle}/{sourceId}
```
