### ISSUE TITLE
Broken admin password reset in 3.5 beta 2?

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#6042]
### Description

<img width="410" alt="image" src="https://user-images.githubusercontent.com/25124/81498189-c7d60400-9306-11ea-959f-fe3f4dfd6bed.png">

- Craft version: 3.5 beta 2
- PHP version: 7.4

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by leevigraham** [comment]
Cool… wasn't sure if I broke something locally :)
