### ISSUE TITLE
Single's entry type handle not renamed when renaming section

### ISSUE THREAD

**Issue by howells** [craftcms/cms#6044]
### Description

When a section that is a single is renamed, its associated entry type is renamed with it, but the entry type's handle isn't and there is no way to update it via the CP.

### Steps to reproduce

1. Rename a Single.

### Additional info

- Craft version:  3.4.18

**Comment by brandonkelly** [comment]
The intent in the code was for both the name and the handle of the entry type to be updated to match the section’s, but there was a bug where only the name would be updated, if both changed at the same time.

Just fixed that for the next release. In the meantime, if you just re-save your section one more time (without making any changes to it), the entry type’s handle should get updated properly.

**Comment by brandonkelly** [comment]
Craft 3.4.19 is out now with this fix.
