### ISSUE TITLE
Can't add widgets to dashboard

### ISSUE THREAD

**Issue by CMeldgaard** [craftcms/cms#6049]
### Description
I can't add any widgets that requires settings. I can see in Chrome Dev tools, that the HTML is inserted, but it's not visible. If i go into the html i Chrome dev tools, and undo the CSS flip, this is how it looks then:

<img width="1436" alt="Screenshot 2020-05-12 at 01 22 54" src="https://user-images.githubusercontent.com/14794642/81621614-24145300-93ef-11ea-9a98-47ce934a55ed.png">

It only happens on widgets which have settings. I have tried clicking on the save button that i can make visible, but nothing is saved. The page just reloads.

### Steps to reproduce

1. Install Craft 3.4.18
2. Try to add widget that has settings, like the Recent Entries widget

### Additional info

- Craft version: 3.4.18
- PHP version: 7.3
- Database driver & version: MariaDB 10.4
- Plugins & versions: None installed

**Comment by brandonkelly** [comment]
Thanks for reporting that! Seems like it was a jQuery bug (we just updated the control panel to jQuery 3.5). Just worked around it for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.19 is out now with the fix.
