### ISSUE TITLE
Disabled related entries show a green 'dot' in the element index table (Craft 3.4.18)

### ISSUE THREAD

**Issue by thijskaspers** [craftcms/cms#6052]
### Description

Disabled related entries show a green 'dot' in the element index table, and clicking on them opens the entry in a different site/language (a site/language where the entry is still enabled).

**Update:** see latest comments, this was introduced in 3.4.18, not on older versions.

### Steps to reproduce

1. Create 2 sites (languages), for example EN and NL
2. Create a section 'Books' and 'Authors' for both languages and propagate entries to all sites
3. Link some books to authors
4. Edit the element index settings and add an 'Author' column to the Books index table
5. Disable an author for the EN site

When you now view the Books index table for the English site, it will show the Author with a green dot stating it is enabled. Clicking on the author will open the enabled version of the author in the NL site instead of the EN site you're currently viewing.

### Expected behavior

You are watching the index table for the EN site, and the author is disabled on the EN site, so the dot should show a disabled state? Or am I missing something?

Hope it helps

### Additional info

- Craft version: 3.4.18
- PHP version: 7.2.24
- Database driver & version: MySQL 5.5.5

**Comment by thijskaspers** [comment]
Thinking of it: this is probably a complex one, since you are technically allowed to select entries from a different site, and the entry can be enabled in the other site while being disabled in the current site. It is still confusing though when viewing the element index for site 1 and you think the related entry you selected (and disabled) is also in site 1, but you still see the enabled dot.

**Comment by thijskaspers** [comment]
I just found out that on an old staging environment for the same site and with the same data, this 'bug' is not present. The dots are greyed out correctly as they should.

The only thing I can think of that might have caused this in the current environment is that we changed the propagation method yesterday from "Save entries to other sites in the same site group" to "Only save entries to the site they were created in" and back again. After we disabled some sites for a section and set the propagation method to "Save entries to other sites in the same group", it created a queue task to apply the new propagation method, but that task failed, so we reverted everything.

**Comment by thijskaspers** [comment]
**Update:** the staging environment was running Craft 3.4.17.1, while the other environment is running 3.4.18. So this bug is introduced in the latest Craft update.

To confirm: After updating our staging environment from 3.4.17.1 to 3.4.18 just now, it changed the disabled entries in the element index to an enabled entry from a different site.

**Comment by brandonkelly** [comment]
Thanks for reporting! This was introduced by ca6eaeac7d0491381f243046a432542779b5a524 in Craft 3.4.18.

Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.19 is out now with the fix.
