### ISSUE TITLE
Style error in delete site modal

### ISSUE THREAD

**Issue by thijskaspers** [craftcms/cms#6053]
See:

![Schermafbeelding 2020-05-12 om 12 49 23](https://user-images.githubusercontent.com/1608184/81675510-3a51fb80-944f-11ea-8912-1987dea2371b.png)

The position of the selectbox is off.

Craft 3.4.18

**Comment by brandonkelly** [comment]
Thanks for reporting that. Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.19 is out now with the fix.
