### ISSUE TITLE
When changing the propagation method from "Save entries to other sites in the same group" to "only save entries to the site they were created in" disabled entries become enabled

### ISSUE THREAD

**Issue by thijskaspers** [craftcms/cms#6054]
### Description

When changing the propagation method from "Save entries to other sites in the same group" to "only save entries to the site they were created in" disabled entries become enabled.

### Steps to reproduce

1. Have multiple sites
2. Have a channel with propagation method set to "Save entries to other sites in the same group"
3. Create some entries in this channel on site 1
4. Disable an entry
5. Change the propagation method to "Save entries to other sites in the same group"
6. Wait for the queue task to finish (updating propagated entries)

The entry that used to be disabled for site 1, is now set to enabled.

### Additional info

- Craft version: 3.4.18
- PHP version: 7.2.24
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.19 is out now with the fix.
