### ISSUE TITLE
Craft Live Previews: Failed to execute ‘postMessage’ on ‘DOMWindow’:

### ISSUE THREAD

**Issue by Jones-S** [craftcms/cms#6057]
### Description
I have a headless craft installation with a Vue app.
Since Craft 3.5 things have changed and my preview can't received any updates anymore because sending information via `postMessage` fails:

> Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://xxx.netlify.app’) does not match the recipient window’s origin (‘https://cms.xxx.xxx.build’).

I realize there is some documentation on that:
https://github.com/craftcms/docs/blob/3.5/sections-and-entries.md#preparing-external-front-ends-for-live-preview.

But even if I include `iframeSizer.contentWindow.min.js` I still get that error. (I see the iframerSizer script being loaded in the browsers network tab 👍 ) but I still would get the target origin error.

Then I thought by providing the target origin before loading the contentWindow script:
https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/iframed_page/options.md#iframe-page-options
It should work...

If I load my page normally (outside of crafts live preview iframe) I see this in the console:

<img width="484" alt="Screenshot 2020-05-12 at 19 27 33" src="https://user-images.githubusercontent.com/7059580/81725802-ae5bc600-9486-11ea-9ee6-afed61091c46.png">

But if let Craft load my page inside the iframe I can see the script being loaded:

<img width="863" alt="Screenshot 2020-05-12 at 19 29 10" src="https://user-images.githubusercontent.com/7059580/81726018-faa70600-9486-11ea-9f01-30f454f373d3.png">

But `window.iFrameResizer.targetOrigin` is not defined... 
<img width="293" alt="image" src="https://user-images.githubusercontent.com/7059580/81726139-2fb35880-9487-11ea-8240-07d2567ed705.png">

I don't even know if this would be correct way to allow cross-domain stuff.
I would prefer if there was an option to disable cross domain restrictions:
I think by setting https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/parent_page/options.md#checkorigin `checkOrigin` to `false` that could maybe do the trick?!

Anyway, if somebody has some hints how to get this thing to run, I would definitely be happy to hear them.
Cheers

### Steps to reproduce

1. Headless Craft with detached frontend app on different domain
2. Open live preview

### Additional info

- Craft version: "craftcms/cms": "3.5.x-dev", (newest commit at time of writing)
- PHP version: 7.2
- Database driver & version: mysql
- Plugins & versions: ...

<br><br><br><br><br>
======== Edit: ========

I added some logging to see what is happening:

First I load:
/js/iframeResizer.options.js
```js

window.iFrameResizer = {
  targetOrigin: 'https://[URL-AS-CRAFT-BACKEND].build
}
console.log('window', window)
console.log('window.iFrameResizer: ', window.iFrameResizer)
```

I load this script before loading the 
`/js/iframeResizer.contentWindow.min.js` file.

I do see the following logs:
<img width="841" alt="Screenshot 2020-05-12 at 22 53 37" src="https://user-images.githubusercontent.com/7059580/81744582-b1b17a80-94a3-11ea-9662-86175cd65cfd.png">
Which seem to be alright. Still it does not work.

When inspecting the `window.iFrameResizer` object in the browsers console it is undefined though...

<img width="213" alt="image" src="https://user-images.githubusercontent.com/7059580/81744552-a78f7c00-94a3-11ea-84bc-1688b89cf1e4.png">

Which seems very odd to me. just a few lines above I do see that `window.iFrameResizer` is defined. 

I am not super experienced with iframes, but could it be that we have somehow two representations of the window object?

Could it be a problem that my whole app is reloaded on change? So every context of the iframeresizer is lost?

Oh and one more thing: I just realized that the [`targetOrigin` is set to `*` by default](https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/iframed_page/options.md#targetorigin)... So why is this even a problem?!

<br><br><br><br><br>
======== Edit 2: ========
I manually edited:
`/vendor/craftcms/cms/src/web/assets/cp/dist/js/Craft.min.js`
and changed:
`...,iFrameResize({scrolling:!0,onInit:function(t)...`
to
`...,iFrameResize({checkOrigin:false,scrolling:!0,onInit:function(t)...`

Now the error went away. So no cross-domain-problems anymore. But I still don't get the draft content... :(

(I do locally, and I used to do so in the past, I assume before `iFrameResizer` was introduced...

Anyway, I think having an option to disable `checkOrigin` would be nice.
I try to find out why I don't get the draft data. If anyone has any hints, they are very welcome...

**Comment by brandonkelly** [comment]
Thanks for digging into that. Just went ahead and set `checkOrigin: false` for the next release.

Suspect this is unrelated to your draft content not loading. That should work identically to Craft 3.3 / 3.4 – see https://docs.craftcms.com/v3/sections-and-entries.html#preparing-external-front-ends-for-live-preview.

**Comment by Jones-S** [comment]
Thank you. I realized that it is indeed an issue on the frontend side. Anyway the error confused me, and I was looking in the wrong place for quite some time. I think `checkOrigin: false` is a good thing to do 👍
