### ISSUE TITLE
entry.getIsEditable() returns `false` for all single entry types

### ISSUE THREAD

**Issue by chasegiunta** [craftcms/cms#6058]
### Description
Looks like 3.4.16 changed the behavior of `getIsEditable()` for entries which are singles. I'm guessing this wasn't intentional.

https://github.com/craftcms/cms/commit/a798b966b1e8200e94e68bc2eb974a786abecde4

### Additional info

- Craft version: 3.4.18

**Comment by brandonkelly** [comment]
Whoops, yeah that was not an intentional change. Thanks! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.19 is out now with the fix.

**Comment by chasegiunta** [comment]
Next time, please delay support. Now I have to continue working... 😉
