### ISSUE TITLE
[RFC] Automatically set preview target to correct site

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#6059]
### Description
Currently, You can manually set preview-targets for each specific site. But this requires the user to choose from a dropdown.

In our case, we have sections that don't propagate their content, so an entry by definition will only work on the site it was created in, and therefore it makes sense that the preview should automatically target that site.

We currently solved it by using an alias called previewBaseUrl and then the following method creating that preview url
```

    /**
     * @return string|null
     * @throws \craft\errors\SiteNotFoundException
     * @throws \yii\base\Exception
     */
    public function getPreviewUrl()
    {
        $request = Craft::$app->getRequest();
        $sites = Craft::$app->getSites();

        if(! $request->isCpRequest || ! $siteHandle = $request->get('site')) {
            return $sites->getPrimarySite()->getBaseUrl();
        }

        $site = $sites->getSiteByHandle($siteHandle);

        return UrlHelper::siteUrl(
            '',
            null,
            null,
            $site->id
        );
    }
```

But it would be nice if this was handled by Craft by default.

**Comment by brandonkelly** [comment]
What is your preview URL?

**Comment by lenvanessen** [comment]
@brandonkelly 

companyname.com > primary
companyname.com/de > german

So preview is set to the same URL also the regular site.

**Comment by brandonkelly** [comment]
And is this for your Homepage single entry, then?

If you change the preview target URL to just `{url}`, then it will always go straight to the correct URL for the entry/site you are editing.
