### ISSUE TITLE
[bug] - Live preview throws 404 for drafts

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#6060]
### Description
When trying to use the live-preview for drafts it throws a 404 instead of showing the preview of the entry.

### Additional info

- Craft version: 3.4.19

**Comment by mattandrews** [comment]
Are you using Twig templates or a custom/headless setup (eg. Element API or GraphQL)? This sounds like an issue correctly forwarding the `token` and `x-craft-live-preview` parameters along.

**Comment by brandonkelly** [comment]
Yeah will need more info about how you have it set up.

If using a decoupled front-end, see https://docs.craftcms.com/v3/sections-and-entries.html#preparing-external-front-ends-for-live-preview for more details about passing the `token`.

**Comment by lenvanessen** [comment]
Using the regular twig templates to accomplish this. And they work for non-draft live-previews.

**Comment by brandonkelly** [comment]
Do disabled entries work?

What is your preview target URL?

**Comment by lenvanessen** [comment]
@brandonkelly I'll close this in shame now. It seems that cache was the culprit and not Craft

**Comment by brandonkelly** [comment]
Hah, no worries :)
