### ISSUE TITLE
Cannot read property 'menu' of undefined in CP after upgrading to Craft Commerce 3, and Craft 3.4.

### ISSUE THREAD

**Issue by isjackwild** [craftcms/cms#6061]
### Description
After upgrading to Craft Commerce 3, and Craft 3.4, I am having errors in certain control panel views. This causes fields such as LightSwitch not to be initialised.

After upgrading to Craft Commerce 3, and Craft 3.4, I am having errors in certain control panel views. This causes fields such as LightSwitch not to be initialised.

Console logs:

```
Craft.js:11440 Uncaught TypeError: Cannot read property 'menu' of undefined
    at proto.constructor.initTabs (Craft.js:11440)
    at proto.constructor.init (Craft.js:11288)
    at proto.constructor.constructor (garnish.js?v=1587654776:768)
    at proto.constructor (garnish.js?v=1587654776:40)
    at new proto.constructor (garnish.js?v=1587654776:40)
    at Craft.js:11998
    at Craft.js:14
```

I then have other logs about field constructors being undefined.

```
deliverySchedule:1151 Uncaught TypeError: Craft.SlugGenerator is not a constructor
    at deliverySchedule:1151
```

```
jquery.js:3850 Uncaught TypeError: Craft.LightSwitch is not a constructor
    at HTMLDivElement.<anonymous> (Craft.js:1867)
    at Function.each (jquery.js:367)
    at S.fn.init.each (jquery.js:202)
    at S.fn.init.lightswitch (Craft.js:1855)
    at Object.initUiElements (Craft.js:1494)
    at HTMLDocument.<anonymous> (Craft.js:1938)
    at e (jquery.js:3557)
    at t (jquery.js:3625)
```

I believe the second errors are being caused by the first issue

### Steps to reproduce

1. Upgrade to Craft 3.4 and Commerce 3
2. In some views (the Calander plugin specifically) the interactive fields are broken and console errors show.

### Additional info

- Craft version: 3.4.16 (Pro)
- PHP version: 7.2.24
- OS version: Linux 4.15.0-58-generic
- Database driver & version: MySQL 8.0.18
- Image driver & version: Imagick 3.4.3RC2 (ImageMagick 6.9.7-4)
- Plugins & versions: 
    - Asset Rev 6.0.2
    - Calendar 2.0.25
    - Commerce Widgets 2.0.20
    - Contact Form 2.2.6
    - Control Panel CSS 2.2.0
    - Control Panel Nav 2.0.9
    - Cookies 1.1.11
    - CP Field Inspect 1.0.7
    - Craft Commerce 3.1.3
    - DigitalOcean Spaces Volume 1.1.2
    - Entry Instructions 1.0.6
    - Expanded Singles 1.0.7
    - Facebook Product Catalog 1.2.0
    - Field Manager 2.1.1
    - GDPR Cookie Consent 1.2.8
    - Google Shopping Feed 1.2.1
    - Imager v2.3.1
    - Imager Storage Driver for DigitalOcean Spaces 1.0.0
    - Incognito Field 1.1.1.1
    - Klarna Checkout for Craft Commerce 1.1.8
    - Mailchimp Commerce 1.2.1
    - Mailgun 1.4.2
    - PayPal Checkout for Craft Commerce 1.1.0
    - PayPal for Craft Commerce 2.1.0.1
    - Pic Puller for Craft 3.0.15
    - Redactor 2.4.0
    - Sprout SEO 4.2.12
    - Stripe for Craft Commerce 2.2.3
    - Web Payments 1.0.4
    - XML Sitemap 1.2.0

**Comment by brandonkelly** [comment]
I suspect this was fixed in Craft 3.4.19. per 07d135b6b32cb3ed8089eba99265792f94f16b6b. Can you make sure you’re on the latest release?

**Comment by brandonkelly** [comment]
Sorry just realized you’re still on 3.4.16, so that’s before the jQuery 3.5 change. In that case it sounds like maybe Craft just wasn’t fully installed correctly to begin with. Try nuking your `vendor` folder and then running `composer install`. And also clear out the contents of your `web/cpresources/` folder

**Comment by isjackwild** [comment]
This didn't work, however I updated the plugin and it's fixed it. I guess
they had an incompatibility with Craft 3.4 which wasn't listed in any
change log.
