### ISSUE TITLE
Live Preview token missing in iFrame

### ISSUE THREAD

**Issue by Jones-S** [craftcms/cms#6062]
### Description
I just realized that the `token` is missing in the iFrame url:
<img width="771" alt="Screenshot 2020-05-13 at 19 50 56" src="https://user-images.githubusercontent.com/7059580/81847090-66ef3b80-9553-11ea-9ae9-d227866d9b7f.png">

I just installed the newest `"craftcms/cms": "3.5.x-dev"`...
But locally it works and I have the exact same project config on the remote.

I see this behaviour in two different remote craft installations...
Do you have any idea why this is missing?

### Additional info

- Craft version: "craftcms/cms": "3.5.x-dev",
- PHP version: 7.2
- Database driver & version: mysql

**Comment by brandonkelly** [comment]
A token is only used when you are previewing a draft, or a disabled/expired/pending entry.

**Comment by Jones-S** [comment]
Ah, sry my bad. Was a bit tired already. It is there, as soon as I change some data. Sorry for having had to look into this. Thx anyway and cheers

**Comment by brandonkelly** [comment]
No worries :)
