### ISSUE TITLE
Deprecation Notice after running composer update

### ISSUE THREAD

**Issue by dejanyy** [craftcms/cms#6064]
Deprecation Notice: Class HTMLPurifier_Language_en_x_test located in ./vendor/ezyang/htmlpurifier/library/HTMLPurifier/Language/classes/en-x-test.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

**Comment by brandonkelly** [comment]
This was already reported on the library’s GitHub repo: https://github.com/ezyang/htmlpurifier/issues/252
