### ISSUE TITLE
Question: How to handle site-specific url prefixes in live previews?

### ISSUE THREAD

**Issue by Jones-S** [craftcms/cms#6065]
Hi there

This is a question concerning the topic of url prefixes (e.g. language related like `/en/mypage` for English or `/fr/ma-page` for French and so on...

My current setup looks like this:
I have two sites, one in German one in English, with a headless Craft installation.

I setup the sites and the URI formats like:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/7059580/81869555-7e8aec00-9574-11ea-804f-857e429cfc36.png">
So for both of my sites the same:

```
{parent.parent ? parent.parent.slug : ''}/{parent ? parent.slug : ''}/{slug}
```

This allows me to have nested pages (structures) with corresponding URIs.
<br>
I have a frontend Vue app which fetches data via GraphQL depending on site-handle (like `default` and `germanPage`) and the slug of the page.

For example: `{"site": "germanPage", "slug": "my-page"}`

<img width="242" alt="image" src="https://user-images.githubusercontent.com/7059580/81869721-d45f9400-9574-11ea-8d2b-c09a54986b7e.png">

I had a discussion with Andrew Welch on how to handle language prefixes in here:
https://github.com/nystudio107/craft-seomatic/issues/565#issuecomment-591569328

I first had the language prefixes as a part of the entries URI, which was the wrong way to go.
So this is why I have the setup described above.

But now there is another thing to take into account:
It is true, that I can fetch the data (and also the preview data) just with the page slug.
But right now I do have a difference in the URL dependent on if I am visiting a preview-url or a live-url.

For example
I have the page `/de/meine-deutsche-seite`. So the frontend app will serve the page on this route.
But Craft will use my previewUrl defined within my preview Targets (where I can only define one URL format for both sites – OK, I could add a target but then the user would have to switch the target just to get the proper language prefix...):
`@previewUrl/{parent.parent ? parent.parent.slug ~ '/' : ''}{parent ? parent.slug ~ '/' : ''}{slug}?site={site.handle}`

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/7059580/81870910-1be71f80-9577-11ea-93e1-9d93ec4b13f9.png">

So I do have nested pages, but for the site specific part like `/de` I don't have a representation within my preview Url.

I now would like to have
`@previewUrl/{language-shortform ? 'language-shortform/' : '' {parent.parent ? parent.parent.slug ~ '/' : ''}{parent ? parent.slug ~ '/' : ''}{slug}?site={site.handle}`

Or something similar. Just to make the live url equal to the preview url...

Is there a way to define my Preview Url to support this kind of format? Or what would your approach look like in this kind of headless, multilang-setup?

Thanks for your input.

Cheers

Jones

### Additional info

- Craft version: "craftcms/cms": "3.5.x-dev",

<br><br>
<br><br>------- Edit --------

Oh and also a related question:
I am not super happy with the URI format yet:
```
{parent.parent ? parent.parent.slug : ''}/{parent ? parent.slug : ''}/{slug}
```
I would rather like to write something like:
```
{parent.parent ? parent.parent.slug . '/' : ''}{parent ? parent.slug . '/' : ''}{slug}
```
Although I see that the slashes in between are not saved, I still think it would make more sense...
But this notation of `parent.slug . 'and-a-string'` does not work. The string is ignored.
Is there some documentation on how to write the Preview Target format and Entry URI formats?

**Comment by brandonkelly** [comment]
For your Entry URI Formats, you should do this:

```
{parent.uri ?? ''}/{slug}
```

That will output the full URI of the parent entry if one exists (including its slug), followed by the current entry’s slug.

So for example if you have the following entry hierarchy/slugs:

- `foo`
  - `bar`
    - `baz`

You will end up with the following URIs:

- `foo`
  - `foo/bar`
    - `foo/bar/baz`

As for the language segment, that should be defined by your sites’ base URLs. Give your English site a base URL of either `/en/` or `http://example.tld/en/`, and give your French site a base URL of either `/fr/` or `http://example.tld/fr/`.

**Comment by Jones-S** [comment]
> {parent.uri ?? ''}/{slug}
👍 

Ok, perfect. And what about the case, where I want to have the same url structure in my iframe (craft preview) as on the FE app?

So if I give my English site a base URL of `http://example.tld/en/`
My FE app will call a route like:
`http://example.tld/en/page-slug` but my preview iframe will call:
`http://example.tld/page-slug?x-craft-live-preview=19876v8765&token=876tzugiz678`

It would be best for me if the iframe is also calling
`http://example.tld/en/page-slug` (incl. lang prefix).

So I thought I may have access to the prefix somewhere where I define my preview target URI...

like:
```
@previewUrl/{siteprefix ?? '}/{parent.uri ?? ''}/{slug}
```

**Comment by brandonkelly** [comment]
Set your preview target URL to just `{url}`.
