### ISSUE TITLE
Could page URIs could be updated for all children pages when saving a parent?

### ISSUE THREAD

**Issue by Jones-S** [craftcms/cms#6066]
### Description
I have structures (in my case just pages) which the editor can nest.
I use nesting to build some kind of a navigation structure for my page.

I then use this Entry URI Format:
```
{parent.parent ? parent.parent.slug : ''}/{parent ? parent.slug : ''}/{slug}
```

The URI for an entry is only saved when I save the entry itself.
But let's assume that I have following nesting structure
```
- parent-page
    - child-page-1
    - child-page-2
```

This will result – if I just create these entries one after another – in the following URIs:

```
- parent-page
    - parent-page/child-page-1
    - parent-page/child-page-2
```

But now I change the parent-pages slug to 
`parent` and I only save this entry, I will be left with these URIs which I fetch via GraphQL:

```
- parent
    - parent-page/child-page-1
    - parent-page/child-page-2
```
So you see the children's uri is not updated...

Is there a way to do that?

### Additional info

- Craft version: 3.5.x-dev

**Comment by brandonkelly** [comment]
Craft goes through and updates child URIs via a background job in the queue, with the description, “Updating element slugs and URIs”. So it does happen, you just have to wait a bit for that job to complete.

**Comment by Jones-S** [comment]
Oh alright. Neat. So I was to quick.
Thank you
