### ISSUE TITLE
Touch Support for Sorting Asset Fields

### ISSUE THREAD

**Issue by kerns** [craftcms/cms#6068]
### Description

Just a feature request.

I am in a situation where in order to make the UI/editing workflow as simple as possible for editors, there is only one asset field. This means the first image in the sort order of a field (in large thumbnail display mode) is used as the primary image, and subsequent images (if any) populate a gallery.

The inability to drag/re-order assets makes it impossible to fully edit the layout of a page away from the desktop, and undermines the other work you've otherwise done to make the page mobile/iPad friendly.

This is particularly troublesome because the ability to create entries _from the field_ is essential in this case... and they can actually do everything they need to do. Except decide which images should be where.

I know there are better options/approaches being planned for C4 but I would love to see some stop-gap in 3.5. Craft 3x will be with us for some time still, and being able to re-order assets away from the desktop feels essential.

And I know there is some work in this, but _maybe_ less than you would think. https://draggabilly.desandro.com

**Comment by brandonkelly** [comment]
This request is already covered by #2332.
