### ISSUE TITLE
Action (heading + settings and move) in Block Still Shown

### ISSUE THREAD

**Issue by dharnell-abluyen** [craftcms/cms#6072]
Hello Craft team,

Can you help me with this issue on where the Heading with Actions still exist even if I set the Max block to 1.

Screenshots:
1. I created a Neo field where my Content Cards (SuperTable) and Key Talking Points (Matrix Field) block exist
<img width="1428" alt="Screen Shot 2020-05-14 at 7 39 57 PM" src="https://user-images.githubusercontent.com/48315691/81931369-9027ce80-961c-11ea-8022-5d6e435bb101.png">
<img width="1175" alt="Screen Shot 2020-05-14 at 7 37 24 PM" src="https://user-images.githubusercontent.com/48315691/81931376-93bb5580-961c-11ea-925d-0e90bed0a93d.png">

2. I set their  Min and Max rows settings to 1 but still heading and the actions exist.

Matrix: <img width="584" alt="Screen Shot 2020-05-14 at 7 54 48 PM" src="https://user-images.githubusercontent.com/48315691/81931567-e85ed080-961c-11ea-8d11-b3628b4edc44.png">
SuperTable: <img width="661" alt="Screen Shot 2020-05-14 at 7 54 38 PM" src="https://user-images.githubusercontent.com/48315691/81931583-ec8aee00-961c-11ea-84b0-435aaea1a94c.png">

3. But still I get this,
<img width="1060" alt="Screen Shot 2020-05-14 at 7 49 42 PM" src="https://user-images.githubusercontent.com/48315691/81931657-088e8f80-961d-11ea-8b8f-50b87dd3e9cd.png">

Thanks in advance.

**Comment by brandonkelly** [comment]
Matrix doesn’t ever hide those based on the number of blocks.
