### ISSUE TITLE
Sort options in element index views are not translated

### ISSUE THREAD

**Issue by sebastian-lenz** [craftcms/cms#6073]
### Description

Craft translates field names in the control panel using the site translation file. This works in almost every place and is a great feature. Unfortunately the field names in the sort dropdown are not translated leading to an inconsistent label: 

![Bildschirmfoto 2020-05-14 um 16 25 37](https://user-images.githubusercontent.com/2273359/81946854-2d283e80-9600-11ea-8916-fcbe06edd02d.png)

### Steps to reproduce

1. Create a field and attach to an element.
2. Create a site translation file and add a translation for the field name.
3. Open the control panel, switch the cp language to the translated language.
4. Visit an index page in the control, open the sort dropdown

### Code

The sort option is returned by `Field::getSortOption()` here: https://github.com/craftcms/cms/blob/develop/src/base/Field.php#L413. Maybe all we need is a translation wrapper here?

### Additional info

- Craft version: 7.4.5
- PHP version: 7.4.5
- Database driver & version: MySQL 5.7.29

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.20 is out now with this fix.
