### ISSUE TITLE
Feature Request: CLI - resave/entries/sectionhandle

### ISSUE THREAD

**Issue by CreateSean** [craftcms/cms#6075]
### Description

I'm working ona  very large site and the CLI resave/entries command is taking 10+ minutes to complete. I only needed to resave one particular section. It would be good if it were possible to limit resave to sections like this:

`./craft resave/entries/sectionHandle`

### Steps to reproduce

1.
2.

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by Mosnar** [comment]
You can already do this with the `--section` option.

e.g.
```
./craft resave/entries --section blog
```

**Comment by CreateSean** [comment]
looks like I should read the docs more closely.
