### ISSUE TITLE
Text Search returning no results despite existing

### ISSUE THREAD

**Issue by CreateSean** [craftcms/cms#6076]
### Description

When searching for some words such as, **Before**, in either the control panel or a front end search no results are obtained.

For example I have a an entry titled:  _Before All Memory Is Lost: Women's Voices from the Holocaust_ If I search using the word **before** I get no results however if I search for **memory, lost, or voices** the entry shows up. If I search for the whole title I get no results.

My client found this issue just before launching a site that's taken the last 5 months to build and now we're on hold. Please advise.

### Steps to reproduce

1.
2.

### Additional info

- Craft version: 3.4.18
- PHP version:3.4.18
- Database driver & version: MySQL 5.7.28
- Plugins & versions:

**Comment by brandonkelly** [comment]
That’s happening because `before` is one of the default MyISAM stop words (see https://dev.mysql.com/doc/refman/5.7/en/fulltext-stopwords.html). As noted there you can provide a custom [ft_stopword_file](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_ft_stopword_file) to override the defaults.

Alternatively you can configure Craft to never use fulltext searching – see #5696 for an example. Or you can switch your front-end search to something else like Algolia.

**Comment by brandonkelly** [comment]
Sorry, one other option – you can switch your `searchindex` table engine over to InnoDB, which as you can see on that page has a significantly smaller list of default stop words.

To do that, run this query from a SQL client:

```sql
ALTER TABLE searchindex ENGINE = InnoDB;
```

**Comment by CreateSean** [comment]
Oli suggested this  in discord

```
'defaultSearchTermOptions' => [
    'subLeft' => true
],
```

and this worked for me.

**Comment by brandonkelly** [comment]
Yeah he just mentioned. So yes that will technically work, but it will also change the behavior of search: now all searches will be fuzzy on _both sides_ of the search term. See our [Enabling Fuzzy Search](https://craftcms.com/knowledge-base/enabling-fuzzy-search) KB article for an explanation.

If that seems like an improvement for your needs, great. In general I think people would expect search terms to only be fuzzy on the right though, which is what you’d get with the default `defaultSearchTermOptions` config value.

Implementing the change outlined at https://github.com/craftcms/cms/issues/5696#issuecomment-593706550 would give you the same result of avoiding fulltext search (so avoiding fulltext stop words like `before`), without changing the actual behavior of search terms. Or switch the table to InnoDB if you are running MySQL 5.7+, so you continue to get the performance benefits of fulltext searching, with a reduced list of stopwords to worry about.

**Comment by CreateSean** [comment]
@brandonkelly Thank you for the better explanation. I have run the sql query you posted above and that works. I'll remove the config setting so that search works as it normally does
