### ISSUE TITLE
Plugin store license in env vars means all come up as trials

### ISSUE THREAD

**Issue by bossanova808** [craftcms/cms#6079]
### Description

I note when I buy a new plugin in the plugin store, any plugin where I am using an env variable for the license (`$LICENSE_CAMPAIGN` or whatever) - does not seem to be recognised as a previously bought one during checkout.

These therefore all come up as 'trials' to buy...which is kind of confusing and might lead to anxiety about the state of one's existing plugin purchases.

### Steps to reproduce

1. Use an env var for a plugin license
2. Have some bought plugins, go to buy another, observe issue in checkout modal

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
I think this was just a general bug with the Plugin Store, not specific to using environment variables for plugin license keys. Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.20 is out now with this fix.
