### ISSUE TITLE
Unable to save entry as a draft: Could not generate a unique URI based on the URI format.

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#6080]
### Description

Encountered this issue when creating a new entry. 

I have a dynamic title that uses related entities:

`{{ object.masterMug[0].title }}{{ object.productionNumber ? ' #' ~ object.productionNumber }}{{ object.artistProofNumber ? ' AP ' ~ object.artistProofNumber }}`

![image](https://user-images.githubusercontent.com/25124/81997252-8771df80-9692-11ea-9c2f-59562f9b70f5.png)

GIven there's no title the slug is probably empty and therefore the url is empty and not unique. 

Here's my Entry URI Format.

![image](https://user-images.githubusercontent.com/25124/81997371-dddf1e00-9692-11ea-90b1-f14f59ae98d4.png)

I actually think that this is becuase `{sourceId}` is not available until after save. I found this to be an issue when I was trying to generate titles on new entries. Resaving the entry added the sourceId.

### Additional info

- Craft version: 3.5.0.beta2
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by leevigraham** [comment]
Checking for a sourceId first kinda works… but I'm not sure of the side effects are saving the entry as a draft then publishing and changing the URL. 

![image](https://user-images.githubusercontent.com/25124/81997790-1f23fd80-9694-11ea-801d-bac67954a1fa.png)

**Comment by leevigraham** [comment]
Using the single curly brace syntax also seems to address the issue:

![image](https://user-images.githubusercontent.com/25124/81998354-a756d280-9695-11ea-9c89-c5a39e9eb6ca.png)

![image](https://user-images.githubusercontent.com/25124/81998369-ade54a00-9695-11ea-860b-d6dbde6d8998.png)

![image](https://user-images.githubusercontent.com/25124/81998389-b63d8500-9695-11ea-8174-ca5bd314fba4.png)

**Comment by john-henry** [comment]
@leevigraham This may help https://github.com/craftcms/cms/issues/5637

**Comment by brandonkelly** [comment]
Probably easiest for us to debug this if you can send your DB backup and composer files into support@craftcms.com.

**Comment by leevigraham** [comment]
I think the main issue here was I was using {sourceId} in the site settings Entry Uri Format. This isn't set until the entry is saved.

**Comment by brandonkelly** [comment]
Ahh, was able to reproduce that. Had to create two separate entries before I hit the error. There was a workaround in place for `{id}` in the event that it wasn’t set yet when the URI was being generated, and I just extended that to `{sourceId}` as well. So this is now fixed for the next 3.4 release, and also merged into the 3.5 branch.

**Comment by brandonkelly** [comment]
Just re-fixed this for `{canonicalId}`, which is a replacement for `sourceId` in 3.7.
