### ISSUE TITLE
Selecting Entries on Multisites broken since 3.4.19

### ISSUE THREAD

**Issue by jules1091** [craftcms/cms#6081]
### Description
Since I updated to 3.4.19 I can't select entries with a multisite user.
I tried to downgrade to 3.4.18 and 3.4.14 and it works in both versions.

This is how it looks in 3.4.14 and 3.4.18 
![image](https://user-images.githubusercontent.com/59639959/82016668-d4998580-9681-11ea-9d94-a186a0ac9d94.png)

and it's empty with 3.4.19
![image](https://user-images.githubusercontent.com/59639959/82016707-eaa74600-9681-11ea-8f5f-c2ea8030339c.png)

### Steps to reproduce

1. Login with a subsite user
2. Try to add an entry to your page

### Additional info

- Craft version: 3.4.19
-PHP version: 7.2.24
- Database driver & version: MySQL 8.0.19

**Comment by jules1091** [comment]
Fixed with 3.4.19.1 :)

**Comment by brandonkelly** [comment]
Yep! Sorry for the inconvenience.
