### ISSUE TITLE
Issue saving custom properties on Assets

### ISSUE THREAD

**Issue by olivierbon** [craftcms/cms#6086]
### Steps to reproduce

1. Create a new volume and add a custom field to it (any type)
2. Create an asset field with *Restrict uploads to a single folder* checked, set a dynamic upload location (i.e. `{author.id}`) and attached field to an entry type
3. Create an new entry
4. Upload an asset and select it
5. Double click the asset in its field to edit the custom field(s), hit save
6. Double click to edit again, data is gone

Couple of things:

- Changing the asset's standard properties works fine (Title and filename)
- This only happens if the custom location (`assets/{author.id}`) doesn't exist yet, once the entry is saved and the custom folder is created, subsequent updates are fine.

### Additional info

- Craft version: 3.4.19.1

**Comment by andris-sevcenko** [comment]
This has been fixed for the next Craft 3.4 release.

**Comment by brandonkelly** [comment]
Craft 3.4.21 is out now with that fix.
