### ISSUE TITLE
New UI is lagging, considerably slowing data entry

### ISSUE THREAD

**Issue by MattWilcox** [craftcms/cms#6087]
### Description

Recent versions of Craft seem to have produced a much laggier UI which is becoming an irritant when trying to do fast data entry. Not only are pages slow to get an interactive state, they feel clunkier than the old style as sections of a page slowly load in and hold up the use of other UI elements that seem to already be loaded.

### Steps to reproduce

1. Use the CMS and go to any "new" layout e.g., Settings is fine, but Entries > Entry isn't.

### Additional info

- Craft version: 3.4.19.1

Video of interaction lag (when it's being reasonably fast): https://www.youtube.com/watch?v=UMuiLVfjnAY

**Comment by brandonkelly** [comment]
I’m not able to reproduce that – even on significantly more complex pages those buttons are almost immediately interactive. And the UI has gotten snappier in 3.4 than previous versions of 3.x, not slower.

That said, JS is single-threaded, so if you have plugins or custom JS code (e.g. via the CP JS plugin), that could be interfering. Are you able to reproduce this on a fresh install?

**Comment by MattWilcox** [comment]
Interesting!

I'll try and get this tested on a fresh install Brandon - we're a little busy at the moment but I'll keep you posted, thanks.

**Comment by brandonkelly** [comment]
Should have also mentioned browser extensions, which could also be a culprit.

**Comment by MattWilcox** [comment]
Looking further, this appears to be something OSX specific. All three developers (myself included) are seeing very delayed domain resolution on `anything.local`, and I assume that a lot of the new UI is sending multiple http requests requiring that when previously it did not - which stacks up and reveals the underlying issue when single https requests were masking it. This delay seems to happen regardless of whether we are running on a native MAMP stack or with the new Nitro thing - so I don't think this is actually Craft/PHP/MySQL related.

I've tried adding IPv6 addresses in the hosts file and a few other things that seem to be common complaints about OSX's DNS lookup speed and `hosts` but none are seeming to fix the lag.

We don't see that lag on our staging or live servers though.
