### ISSUE TITLE
Better local volume path setup

### ISSUE THREAD

**Issue by frank-laemmer** [craftcms/cms#6088]
Sorry for a long issue, discussing multiple somehow related topics:

## Problem

When creating a volume in Craft CMS, the user is left a bit guessing about how to set up the local path:

* The hint `/path/to/folder` is not super helpful.
* Does it have to be an absolute path (system) or can and it be relative path? What best to use and why, relative or absolute?
* How and why to use aliases or ENV vars?

There is an autocomplete to show existing aliases and ENV vars, but that does not include any useful defaults for the local path.

When you click on "learn more" you will get to this help doc: https://docs.craftcms.com/v3/config/environments.html — which is not helping much in that regard. There are some hints on using @assetBasePath here: https://docs.craftcms.com/v3/config/#aliases

## Suggestions

Some opinionated defaults, plus some JS magic to autocomplete fields as used in other parts of the control panel already might help to master and understand the situation better.

* Pre-deploy an `web/assets` folder (in craftcms/craft)
* Pre-populate the @assetBasePath alias with assets as default
* Pre-populate the field with `@assetBasePath/[handle]`
* ( Create the folder afterwards (so there are no file permission errors) )

(alternatively pre-populate `ASSET_BASE_PATH` in .env.example, like you do already in craftcms/demo)

I have not put too much thought about it, just an idea for a direction. Please see the attached screenshot for some explanation.

<img width="1079" alt="assets-ideas" src="https://user-images.githubusercontent.com/962736/82058495-1f88bc80-96c5-11ea-8ce2-bf46203d7214.png">

### Handle autocomplete

The given title will pre-populate the handle field. Maybe it can also prepopulate the local path field to highlight the connection.

### How to make original uploads inaccessible?

This is a side case: I am a building a  portfolio website for photographer. The photographer will be uploading hi-res images to the control panel. On the website itself, lower resolution images will be shown only (of course). For this saved image transformations will be used. 

How can I make sure that the original photos are not accessible in public? Only the transformations should be public. What is the recommendation here (obscure names / non-public volumes) ? I was not able to find a good documentation on that.

Here is an example:

```
# within:
assetFolder/volumeFolder

# you can see:
image-32424.jpg
imageTransformFolder/image-32424.jpg
# the original file get's uploaded to the base of the Volume, the transformations have dedicated folders.
```

That means that the final URL of the converted images is something like: `{url}/assetFolder/volumeFolder/imageTransformFolder/image-32424.jpg`. By leaving out the `imageTransformFolder` anyone in the internet can easily guess the path to the original image.

Maybe I am missing some fundamental concepts here?

### Alias or ENV var?

AFAIK aliases will naturally persist over multiple environments. Let's say I have a local development environment and a remote production App. ENV vars are best used for environment specific definitions (which this is not).

For the paths, it's likely to be the same, in case it can be relative, path, so an alias might be better than an ENV var here? 

I have to admit, that I am having some trouble understanding why and when to use an ENV var or when to use an alias. At first I thought the @alias syntax is Craft 2 related and the $env syntax is just newer better Craft 3 way to go. But more and more I see there are good use cases for @alias (stays the same over all envs) and $ENVs. I can imagine that some other users might get confused about the two concepts. Maybe I am missing a good link to the docs about this?

## Some background on the one assets folder to include volumes

We are preparing [Craft Copy](https://github.com/fortrabbit/craft-copy) for initial release. It can sync (uses rsync) assets up and down. It currently does not take volumes into account, rather it expects that there is one folder which contains all volumes. 

So we wonder if a global folder which contains all volumes can be a suggested best practice. The Happy Lager demo and other examples are using a folder called `assets` for that. I have found `resources` another common name. The name actually doesn't matter, it's more about the concept of putting all volumes in one folder under `web`.

This is actually an extra question. To re-phrase: We'd like to see one assets folder pre-populated to include the volumes, not multiple folders on root level containing the volumes.

### What we would like to expect

```
# all volumes are in one folder
web 
  assets        < @assetBasePath
    images      < volume 1
    downloads   < volume 2
```

### What we would like to avoid

```
# volumes are on top level or even somewhere else
web 
  images      < volume 1
  downloads   < volume 2
```

What do you think about this? What are the use cases for different cases? What do you suggest, how should Craft Copy best handle this?

**Comment by michtio** [comment]
@frank-laemmer even tho you make some good suggestions, the creation of base folders and auto populating those assets fields an aliases I'm not a fan of. 

I personally, and I know many other use a completely different setup, including many projects working with S3. I'm not a fan of going and change all those default options.

Guidance or better documentation could be definitely useful, but pre-filled volume assets or pre-created folders? Not really. Then we can go on, and every time we create a section that automagically some fields will be added and created, which when not needed just gives extra work of changing / removing them. 

Also, for all of the above stuff, we do have the project.yaml that can scaffold your new Craft Projects. 

Also your expectations ... I do prefer my volumes to be completely configurable and not bound to one single folder at all. Sometimes there are a lot of different folders used, and we run a lot of projects where it's simple not possible or not desired to organise all assets in one single folder...

To me it feels like "limiting" the Craft setup, just to make it more "Click & Play" which imho is limiting Craft's strength.

But that's just my 2 cents.

**Comment by frank-laemmer** [comment]
Sorry again for posting a multi-topic ticket. I think these things are related. For michtio's 2cent: Not sure if we understand each other here correctly: This is not about pre-filled volume paths, this is not about removing any functionality that you would like to have.

We propose to have: 

* one base path containing all other volume paths by default
* simplify UI and work and documentation so that the setup is more clear

**Comment by brandonkelly** [comment]
> Does it have to be an absolute path (system) or can and it be relative path? What best to use and why, relative or absolute?

It can be relative from the webroot, if you want. That will lead to issues if your project contains multiple webroots though, such as a dedicated webroot for the control panel, so I wouldn’t recommend it.

> How and why to use aliases or ENV vars?

That should be covered by the [Environmental Configuartion](https://docs.craftcms.com/v3/config/environments.html) page, but to clear it up (hopefully):

- Environment variables should be used to define environment-specific values, such as database connection info, or the path to a directory you are going to store your asset volumes.

- Aliases are a way of abstracting a base path or URL, and they can be set to an environment variable:

  ```php
  'aliases' => [
    '@assetBasePath' => getenv('ASSET_BASE_PATH'),
  ],

  The advantage of aliases is that you can add a subpath to them, whereas environment variables must be standalone. For example you could not set a volume’s base path to `$ASSET_BASE_PATH/user-photos`, but you could set it to `@assetBasePath/user-photos`.

> There is an autocomplete to show existing aliases and ENV vars, but that does not include any useful defaults for the local path.

No, it’s up to you to define the environment variables & aliases first.

> Some opinionated defaults, plus some JS magic to autocomplete fields as used in other parts of the control panel already might help to master and understand the situation better.

I don’t really like the idea of pre-filling the Path and URL settings personally, since that is dealing with Front End Land, which Craft doesn’t & shouldn’t make any assumptions about. Everyone has their own ways of structuring their front-end files.

> (alternatively pre-populate `ASSET_BASE_PATH` in .env.example, like you do already in craftcms/demo)

There’s little chance that an environment variable will actually exist called `ASSET_BASE_PATH`. That is merely used as an example in the docs, based on the demo project, but it’s not a convention.

> How to make original uploads inaccessible?

Currently there‘s not a good way of doing this, unfortunately. Either you want the volume to be publicly accessible, or you don’t. We are going to solve this in Craft 4, though (see #5926).

> So we wonder if a global folder which contains all volumes can be a suggested best practice.

I would say no.

If Craft Copy is a plugin, you can come up with your list of volume base paths to avoid like this:

```php
use craft\base\LocalVolumeInterface;

$rootPaths = [];

foreach (Craft::$app->volumes->getAllVolumes() as $volume) {
  if ($volume instanceof LocalVolumeInterface) {
    $rootPaths[] = $volume->getRootPath();
  }
}
```

**Comment by frank-laemmer** [comment]
Thanks for the answers. Helps us planning ahead.
