### ISSUE TITLE
Non public files on s3 are stored public in web/cpresources

### ISSUE THREAD

**Issue by nettum** [craftcms/cms#6093]
Not sure how this could (or if it even should) be resolved by this plugin or craft cms at all, but I'm posting it anyway so you can see what the challenge is:

* I've created a s3 volume in Craft. This volume is responsible to hold files that should only be accessible to certain user groups in CP. The volume have "Assets in this volume have public URLs" and "Make Uploads Public" set to false. A normal user should not be able to request files inside this volume either from craft or the s3 public URL.
![image](https://user-images.githubusercontent.com/798156/74851992-49d41380-533c-11ea-8094-950a5129b479.png)

* When clicking the "Preview" button (or doing other stuff that will fire yii2s AssetManager with files inside this volume) Craft will generate a file inside web/cpresources:
![image](https://user-images.githubusercontent.com/798156/74852623-2067b780-533d-11ea-8810-8e51efa82cdc.png)

I don't want these files to be public available on my webserver as this can be accessed by normal users and not just logged in users. Of course the URL itself is not easy to guess as the foldername are crc32 hashed (e.g. `/cpresources/1c879c47/2992.jpg?v=1582129611`), but it's still online and _could_ be indexed or shared to "unauthorized" users.

Can I somehow tell craft to not store a local copy of the files in this volume? 
Should Craft or aws-s3 plugin handle this scenario? Should files inside volumes that have "Make Uploads Public" disabled not be stored inside web/cpresources in the first place?

As of now the only solution I see is to avoid using Volumes in the first place. But then I would need to handle the upload to s3 myself and I would not benefit from the user permissions already on place in craft.

This is somewhat related to https://github.com/craftcms/cms/issues/2712 as the removal of local FS storage requirement would solve this (and hopefully make horizontal scaling easier/more performant)

**Comment by brandonkelly** [comment]
We could definitely switch to having Craft be the thing that serves the asset thumbnails, by reading out the image file from the local volume or from `storage/runtime/assets/thumbs/` if the user is authorized. As long as they get revved URLs  and are served with proper cache headers, it shouldn't have too much of an impact either way.

**Comment by andris-sevcenko** [comment]
Alright. Pushed a commit that changes this behavior in 3.5. Craft will stop storing anything from non-public volumes in the `cpresources` folder.
