### ISSUE TITLE
Query for lightswitch ":empty:" does not return entries that do not have the field.

### ISSUE THREAD

**Issue by ccsantos23** [craftcms/cms#6098]
### Description
I have a section whose entries may or may not be publicly visible.  A lightswitch field "disableActionLinkToThisEntry" controls this for me.  The other sections don't have that field defined.

On a site search, I need to query all entries that either have disableActionLinkToThisEntry undefined/empty, or false.  This used to work:
```
  craft.entries({
    disableActionLinkToThisEntry: ':empty:'
  })
```
But that stopped working recently. Now I'm hardly getting any results from my query. 

When I checked the raw sql:
```
  craft.entries({
    disableActionLinkToThisEntry: ':empty:',
  }).getRawSql()
```
it returned:
```
... WHERE ... (`content`.`field_disableActionLinkToThisEntry`=FALSE) ...
``` 

When I tried this instead:
```
  craft.entries({
    disableActionLinkToThisEntry: ':empty:' or false,
  }).getRawSql()
```
then it gave me what I thought I needed:
```
... WHERE ... ((`content`.`field_disableActionLinkToThisEntry`=TRUE) OR (`content`.`field_disableActionLinkToThisEntry` IS NULL)) ...
```
But it needs to be FALSE or NULL.

Possibly related to #5896.

### Additional info
- Craft version: 3.4.19.1
- PHP version: 7.0.33
- Database driver & version: MySQL 5.7.29
- Plugins & versions:
Azure Blob Remote Volume	1.0.2
Field Reveal	1.0.1
Fractal	1.0.8
Logs	3.0.3
Matrix Toolbar	1.0.6
Recaptcha Verify	1.0.0
Redactor	2.6.1
Redirect plugin for Craft 3	1.0.23
SEOmatic	3.3.3
Smith	1.1.3
Snitch	3.0.1
Workflow	1.4.8

**Comment by brandonkelly** [comment]
What is the Lightswitch field’s default value set to in its settings?

**Comment by ccsantos23** [comment]
It's default setting is TRUE.

**Comment by brandonkelly** [comment]
I think that may be your issue, any elements that don’t have an explicit value set (`null`) will default to that value. Try flipping it to the off position.

**Comment by ccsantos23** [comment]
That's how it needs to work for that section.  The problem is that :empty: doesn't find any entries in the other sections that don't have that lightswitch in their entry types.

Wait, are you saying that the lightswitch is considered to be in all the entry types, if it's defaulted to true?

**Comment by brandonkelly** [comment]
That the way Lightswitch query params work is this:

1. The passed-in value will be normalized to either `true` or `false`. (So `':empty:'` will normalize to `false`, for example).
2. The element query will be modified to return elements that are set to that normalized param value, whether they were _explicitly_ set to that value, or _implicitly_ (because they don’t have a value set yet, _and_ the default value is equal to the normalized param value). _Elements that don’t have the Lightswitch field would assume the implicit default value._

**Comment by ccsantos23** [comment]
Oooh.  I thought `':empty:'` meant `WHERE (myfield=FALSE) OR (myfield IS NULL)` regardless of the default.
It would be good to have this info on the [Lightswitch Fields doc](https://docs.craftcms.com/v3/lightswitch-fields.html).

**Comment by brandonkelly** [comment]
Sorry for the confusion… in most cases it means `null` or a blank string value so it was reasonable for you to think that. Lightswitch fields are a bit of an exception. I’ve updated the docs to clarify the behavior.
