### ISSUE TITLE
Anonymous/Offline access isn't working

### ISSUE THREAD

**Issue by paullegrand** [craftcms/cms#6100]
### Description
In cms/src/web/Controller.php, there is broken syntax which breaks anonymous access when the site status is offline

### Steps to reproduce

1. Set `$allowAnonymous` to be true for something
2. Set the site status offline
3. Try to access it

### Additional info

- Craft version: newest
- PHP version: 7.x
- Database driver & version: n/a
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
That’s not broken syntax; it’s a [bitwise `&` operator](https://www.php.net/manual/en/language.operators.bitwise.php).

See the [$allowAnonymous](https://docs.craftcms.com/api/v3/craft-web-controller.html#allowanonymous) docs for a list of supported values.
