### ISSUE TITLE
[FR] add loading="lazy" to element thumbnails

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#6104]
### Description

Small performance improvement. Element thumbnails and assets could have the `loading="lazy"` attribute applied so they load just in time when scrolling through element index tables.

**Comment by brandonkelly** [comment]
Easier said than done, since we have a JS-based thumbnail image loader, to prevent the browser from hanging when attempting to navigate away from the current page while the server finishes processing all current thumbnail requests. But I was able to mimic `loading="lazy"` based on scroll events :)

**Comment by brandonkelly** [comment]
Craft 3.4.21 is out now with that change.

**Comment by darylknight** [comment]
Looks like this just broke in live preview

![image](https://user-images.githubusercontent.com/1250017/83258010-30a1f500-a1be-11ea-990c-e13650c32935.png)

**Comment by brandonkelly** [comment]
@darylknight Whoops, thanks for pointing that out. Just released Craft 3.4.22 with a fix.

**Comment by darylknight** [comment]
Thank you 🙂
