### ISSUE TITLE
Amend public domain detection?

### ISSUE THREAD

**Issue by fThues** [craftcms/cms#6105]
Would it be possible to add the string `preview` to the list of subdomain parts that count as non-public domains? We're hosting all of our sites that are under development under a `preview.ourcompany.tld` subdomain, so for example `sitename.preview.ourcompany.tld`.

The documentation says:

> Does it have a dev-sounding subdomain (e.g. ‘craftdemo’, ‘dev’, ‘local’, ‘loc’, ‘test’, ‘testing’, ‘sandbox’, ‘stage’, ‘staging’, ‘acc’ or ‘acceptance’)?

I think `preview` would qualify here as well.

**Comment by leevigraham** [comment]
You can submit a PR here for custom domains: https://github.com/pixelandtonic/craftnet/blob/master/config/dev-domains.php

**Comment by fThues** [comment]
Awesome, thanks!
