### ISSUE TITLE
Color field picker doesn't work with Safari 

### ISSUE THREAD

**Issue by howells** [craftcms/cms#6107]
Using Craft CMS 3.4.20 in Safari 13.1, the color picker doesn't seem to appear when clicking on the round colour preview. It does work fine in Chrome, however.

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.21 is out now with that fix.

**Comment by howells** [comment]
@brandonkelly thanks Brandon
