### ISSUE TITLE
Allow hiding of Title field in element index

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#6110]
Currently, you are forced to keep the "Title" field in element indices, which doesn't make sense in many cases.

When things are ID-based (e.g. "orders"), the ID is the relevant identifier. If a title format of something like `Order #{id}` were possible, that would be a solution, but that doesn't work for initial saves.

So, I'm forced to just just put something meaningless in there, e.g. `{postDate|date('U')}`.

…which is fine, except that I can't hide that from the element index, when I really just want to uncheck `title` column, and show `id` instead.

<img width="206" alt="Screen Shot 2020-05-19 at 2 39 55 PM" src="https://user-images.githubusercontent.com/18329/82365440-a6e47180-99de-11ea-9d83-edf51419fb50.png">

**Comment by timkelty** [comment]
FWIW - I started a PR for this, got it working, but it gets hairy fast because of how much part of element indexes rely on a title column (e.g. structure controls, edit links)

So after that attempt, I'm thinking it might make more sense to make `{id}` work for initial saves in the title format.

**Comment by brandonkelly** [comment]
Yeah… you definitely need _some sort_ of header column, that links off to the element edit page. I just added a new “Header Column Heading” setting (see #3814), making it possible to customize the “Title” label for each element source.

So going forward you can change your entry type’s Title Format to `{id}`, and then change the source’s Header Column Heading to “ID”, and drop the normal ID column.

**Comment by timkelty** [comment]
@brandonkelly Things still get awkward when you set a title format to `{id}`:

It doesn't in the CP, but only because entries are never saved directly, they're first a draft. So by the time they're saved as an entry, they have an id to parse.

If, e.g. you are submitting entries on the frontend via `entries/save-entry`, you'll validation errors (title cannot be blank).

**Comment by brandonkelly** [comment]
@timkelty I’d consider that a bug, so just reposted your comment as a new issue: #6452
