### ISSUE TITLE
Translation "Publish changes"

### ISSUE THREAD

**Issue by kringkaste** [craftcms/cms#6112]
### Description

The button "Publish changes" is not translated in all circumstances.

### Steps to reproduce

1. Edit an existing entry.
2. Click the button "Save as a draft".
3. The primary button is now renamed to "Publish changes", but it is not translated.

### Additional info

- Craft version: 3.4.20
- PHP version: 7.4

**Comment by kringkaste** [comment]
Thanks for merging my PR yesterday. We (our customer) found some more missing translations, added in #6111 . How do you keep the translations in all the languages up-to-date? Is there something we can do better to support you in translations?

**Comment by brandonkelly** [comment]
Translations are managed in a [CrowdIn project](https://crowdin.com/project/craft-cms).

**Comment by kringkaste** [comment]
Hey @brandonkelly, we will using the CrowdIn project in the future. But this issue is not a typical missing translation. It's a bug in the UI, the existing translation for the button isn't used here. It's always English. Please have a look.

**Comment by brandonkelly** [comment]
Sorry, I misunderstood. Just fixed that for the next release. Looks like it was only an issue immediately after you click “Save as a draft”, but the translation showed up correctly after reloading the page.

**Comment by brandonkelly** [comment]
Craft 3.4.21 is out now with that fix.
