### ISSUE TITLE
Add the option to add it's own entry in a entry type field.

### ISSUE THREAD

**Issue by Osze** [craftcms/cms#6113]
### Description
I've build all my sites using NEO block structure. Before the last Craft update (because of a bug I wasn't aware of)  I was able to choose the own entry in an entry type.

I think it was great and I've build many blocks with it. Now I can't because you've fixed the "bug". I hope you could add a setting so I can use that feature again. 

When do I use it?

1. Article List Block - For example in an article I have a block to create top ranking list of the best articles. Sometimes I want its own article in that list. 

2. Breadcrumbs Block - I have a block to make the breadcrumbs list and I want the option to add it's own entry in that list. (I know I can build it differently but it makes most sense to the administrator to add them all, and also now they have the option to customize it more.)

I use it in many more blocks but you get the point :)

**Comment by brandonkelly** [comment]
Just added a new “Allow self relations” setting to relational fields, under “Advanced”, for the next release.

To get the change early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#0b1d25b7128521d5d179ae2ab22e4702a334fc09 as 3.4.20",
  "...": "..."
}
```

Then run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.4.21 is out now with this new field setting.
