### ISSUE TITLE
craft.app.request.absoluteUrl returns encoded slug in case of accents

### ISSUE THREAD

**Issue by timbertens** [craftcms/cms#6114]
### Description
Not sure if this is intentional or not, but {{craft.app.request.absoluteUrl}} output the full url but encodes the last segment in case there are accents appearing in it.  When outputting the url of an entry this encoding of the last segment does not occur. It is very much an edge case, but as a result in my setup the corresponding navigation item is not highlighted in the use case as we these 2 variables to determine this.  This works fine of course in all other 99% of the cases where urls don't have any accents.  

### Steps to reproduce
Output those 2 variables on page that has a word with an accent in the slug (eg. bibliothèque)
Then you'll see
```
{{entry.url}} => HTTPS://BOOTSTRAP.KBC-AGENT.TEST/FR/BIBLIOTHÈQUE
{{craft.app.request.absoluteUrl}} => HTTPS://BOOTSTRAP.KBC-AGENT.TEST/FR/BIBLIOTH%C3%A8QUE
```

### Additional info
PHP version | 7.4.4
Linux 4.15.0-91-generic
MySQL 5.7.29
Imagick 3.4.4 (ImageMagick 6.9.7-4)
Craft Pro 3.4.18
2.0.35
2.12.5
6.5.3
1.2.3-dev

**Comment by brandonkelly** [comment]
Hm, this is a tricky one – your browser is actually the one doing the encoding, per [RFC 3986](https://tools.ietf.org/html/rfc3986). Note how if you access https://bootstrap.kbc-agent.test/FR/BIBLIOTHÈQUE in your browser with the Network tab already open, the request URL that gets logged will be:

```
Request URL: https://bootstrap.kbc-agent.test/FR/BIBLIOTH%C3%88QUE
```

We could technically solve this by having all generated URLs get properly URL-encoded, so in this case `entry.url` would give you `https://bootstrap.kbc-agent.test/FR/BIBLIOTH%C3%88QUE`. But that would also result in browsers starting to _show_ those encoded URLs in the address bar, which wouldn’t look as nice, so not sure that’s the right approach.

>  It is very much an edge case, but as a result in my setup the corresponding navigation item is not highlighted in the use case as we these 2 variables to determine this.

Maybe you should just stop relying on a URL match, and compare the navigation entry with the `entry` variable that is automatically defined for single-entry pages.

The easiest way to do that without worrying about a bunch of `entry` variable name conflicts would be to set this at the top of each of your single entry templates (the ones specified by your section settings):

```twig
{% set requestedEntryId = entry.id ?? null %}
```

Then in your navigation code, replace your `entry.url == craft.app.request.absoluteUrl` condition with:

```twig
{% if entry.id == requestedEntryId %}
```
