### ISSUE TITLE
Changing Propagation method from multi to one site, entry parent/child structure gone

### ISSUE THREAD

**Issue by GaryReckard** [craftcms/cms#6115]
### Description
I have two sites, and a structure section. Initially, the section is only enabled in one site, and propagation method is "Only save entries to the site they were created in". When I change it to propagate to other sites, my entries are cloned, and everything looks good. But if I change it back to "Only save entries to the site they were created in", the structure is flattened, with no parent/child relationship intact.

### Steps to reproduce

1. Create two sites
2. Add a structure section to Site 1, with propagation method as "Only save entries to the site they were created in"
3. Add entries to that section, and add some structure hierarchy
4. Change the propagation method to "Save entries to all sites enabled for this section" and enable it for Site 2. This should clone the entries in Site 2, and their hierarchy should match site 1.
5. Change the propagation method back to "Only save entries to the site they were created in", and the hierarchy of the entries on Site2 is flattened. 

### Additional info

- Craft version: both 3.4.20 and 3.4.17.1
- PHP version: 7.3
- Database driver & version: MySQL
- Plugins & versions:

**Comment by brandonkelly** [comment]
Took a bit of hair-pulling, but jut got this fixed for the next release.

**Comment by GaryReckard** [comment]
Thanks for getting to this one so quick! Appreciate it.

**Comment by brandonkelly** [comment]
Craft 3.4.21 is out now with that fix.
