### ISSUE TITLE
Allow reference tags in URL fields

### ISSUE THREAD

**Issue by danbrellis** [craftcms/cms#6117]
### Description
When entering a reference tag into a URl field (eg `{entry:about-us:url}`) as per the [reference tag documentation](https://docs.craftcms.com/v3/reference-tags.html), the UrlValidator rejects it as "not a valid URL" on save. Since this reference tag would return a valid url in a template, it stands to reason it could be used here.

Ideally, we could use an Entries field for this, but in some cases, such as within a table or when a content editor should have the ability to link to an entry OR an external url, an Entries field is not possible.

Likely, this would be something added to the UrlValidator::validateValue() method. I can take a stab at a PR if you'd like. I imagine something like 1) detect if a reference tag has been entered, 2) resolve the reference tag, 3) run that value through the validator.

### Steps to reproduce

1. Create a new field with field type "URL".
2. Enter a reference tag that would return a url and save the entry. An error message is displayed.

### Additional info

- Craft version: 3.4.19.1
- PHP version: 7.3.8

**Comment by brandonkelly** [comment]
Unfortunately this wouldn’t be possible without us changing the normalized field data to an object, which keeps track of the original value while still allowing the template to output the parsed URL. Which would be a breaking change, and feels overly complicated for a simple URL field.

Maybe just stick with a plain text field instead, and then add your own `|parseRefs` tag in the template when outputting its value? Or if you really want you could write your own improved URL field type.
