### ISSUE TITLE
Requesting improvements for inserting table field rows via PHP

### ISSUE THREAD

**Issue by jakepm** [craftcms/cms#6119]
### Description

When inserting rows to a table field using PHP (plugin/module), the array key values must much the column header (eg. col1, col2, col3). This requires you to know the column header IDs which can only be found (I think) by inspecting the markup in the control panel.

I think it would be far better if you could use the table column header *handle* rather than the column ID. Failing that, it should be more obvious what the column ID for each column header is, when viewing the field in the control panel. It seems that the ID is set based on the order of creation, rather than the sort order of the fields.

### Steps to reproduce

1. Create a table field and assign to an entry
2. Insert values into table field using a plugin/module;

$entry->setFieldValues([
  'tableFieldName' => [  [ 'col1' => 'value', 'col2' => 'value'], ... ],
]);

### Additional info

- Craft version: 3.x
- PHP version: 7.2
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
You can get the column IDs from the Table field’s `columns` setting, but yeah, agree setting by handle would be better. Just made that change for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#02e66872dd7fa262988e11b5d8a3df88b422ed8b as 3.4.20",
  "...": "..."
}
```

Then run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.4.21 is out now with that change.

**Comment by jakepm** [comment]
Thanks Brandon :)
