### ISSUE TITLE
Clearing data caches immediately invalidates project config when !!float values are present

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#6121]
I'm not sure when this manifested itself, but just noticed it on `3.4.18`.

Essentially, as the project config is cached via the cache component, clearing the cache immediately prompts for a project config sync (serving a 503).

This seems like it could be very bad for lots of people, as it essentially brings you site down with one click.

Running migrations, project-config/sync, and clearing data caches are all fairly common things to do on a deploy. However, this would result in your site going down (503 project config):

```
craft project-config/sync
craft clear-caches/data
```

…since clearing the data caches immediately invalidates the project-config. You would need to clear caches first.

Likewise, clearing data caches from the CP will immediately start serving 503s (until project config is synced again).

I haven't gone back through the commits yet, but I'm fairly certain this newly introduced, as we only just started experiencing it and we clear caches on deploys regularly.

Update:

- I'm experiencing this with redis as cache (`yii\redis\Cache`), however, I also reproduced it with the default cache component.
- reproduced this on 3.4.20 as well.
- here's the behavior in action: https://drive.google.com/file/d/1VfU8tcn0EqK7qLtadhgXWN5TL47Kug73/view
- Tested this on a couple other apps using 3.4.18 and 3.4.20 and couldn't reproduce, so perhaps it isn't as widespread as I thought…but still not sure what would cause it

Bigger update:

After some debugging, I discovered this happened after installing a plugin (in this case `nystudio107/craft-webperf`), however, I'm not convinced it is specific to that plugin. What I discovered is the behavior starts after I install the plugin and save settings (saving them to `project.yaml`). Furthermore, I discovered that removing some settings the `project.yaml` eliminated the issue, however – it didn't appear to matter which, only how many. So, I presume this is an issue related to the size of serialized data a plugin is sticking into the cache for settings?

Others mentioned they've seen similar issues with other plugins, such as Freeform. I imagine Freeform also has a large amount of settings, so that may be the same problem there.

/cc @khalwat

**Comment by khalwat** [comment]
So strange... I'm confused as to how Webperf could be doing something wrong here but... ya never know.

**Comment by timkelty** [comment]
Ok - got down to the specifics of what is causing it:

Anytime a value gets written to project json like this, this behavior occurs:

```
!!float 2
```

This will happen, e.g. if you have a plugin setting with a value of `2.0`.
It's valid YAML, but for whatever reason, once those are in there and you clear the cache…Craft insists it needs a project-config sync.

**Comment by andris-sevcenko** [comment]
@timkelty any chance of getting access to a site where this can be reproduced?

I can't reproduce neither value manifesting as `!!float X`nor Craft wanting to sync config on cache clear if I add that value manually :/

As usual - if possible, hit us up via support@craftcms.com.

**Comment by timkelty** [comment]
@andris-sevcenko I can reproduce locally, with a bare craft install, using Nitro, so you should be able to as well…emailed details.

**Comment by andris-sevcenko** [comment]
Fixed for both 3.4 and 3.5!

**Comment by timkelty** [comment]
Confirmed. Thanks @andris-sevcenko!

**Comment by brandonkelly** [comment]
Craft 3.4.21 is out now with that fix.
