### ISSUE TITLE
Add a button to clear the expiry date

### ISSUE THREAD

**Issue by pablofernandezgh** [craftcms/cms#6124]
Some users have issues to delete the expiry date of an entry. You need to select the expiry date and delete it like it's text. Not very obvious for everyone

Maybe a small button could appear next to the expiry date to delete it. If the user has set one

**Comment by brandonkelly** [comment]
Good idea. Just added a close button for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.21 is out now with that change.
