### ISSUE TITLE
Nav tag - allow using "ifchildren" without "children" inside and multiple "ifchildren"

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#6125]
Today I wanted to create something like this:

```
    {% nav node in nodes %}
        <li>
            <a href="{{node.url}}">
            {{node.title}}
            {% ifchildren %}
                <i class="fas fa-caret-down"></i>
            {% endifchildren %}
            </a>
            {% ifchildren %}>
                <ul>
                    {% children %}
                </ul>
            {% endifchildren %}
        </li>
    {% endnav %}
```

As you can see, with first `ifchildren`, i just wanted to display a downward arrow icon inside the link. This was however impossible - without `children` tag inside `ifchildren` i got error:

```
Unexpected "endifchildren" tag (expecting closing tag for the "nav" tag defined near line 10).
```

It also seems that two instances of `ifchildren` inside `nav` tag were causing problems as well.

**Comment by brandonkelly** [comment]
This isn’t possible unfortunately. The `nav` tag is an abstracted way of creating tree-like HTML non-recursively ([example](https://github.com/yiiext/nested-set-behavior#non-recursive-tree-traversal). The `ifchildren` and `endifchildren` tags are not normal `if` tags; they are only there to help identify the HTML that should be output when going down a level (code between `ifchildren` and `children` and when going up a level (code between `children` and `endifchildren`.

So by the time the code between `ifchildren` and `children` are being run, the array pointer is actually on the next element already - which established that we’re now going down a level.

There are various ways you could do what you want to do, but not with the `nav` tag. If you only need these `<i>` elements on the top level entries, you could do:

```twig
{% set entries = craft.entires()
  .level(1)
  .with(['descendants'])
  .all() %}

{% for entry in entries %}
  <li>
    <a href="{{ entry.url }}">
      {{ entry.title }}
      {% if entry.hasDescendants %}
        <i class="fas fa-caret-down"></i>
      {% endif %}
    </a>
    {% nav node in entry.descendants %}
      ...
    {% endnav %}
  </li>
{% endfor %}
```

**Comment by piotrpog** [comment]
@brandonkelly 
Thank you for your comprehensive explanation.
