### ISSUE TITLE
[3.5 beta 2] Error when saving entries that have Matrix fields

### ISSUE THREAD

**Issue by clowerweb** [craftcms/cms#6128]
### Description

The following error appears in the admin section when attempting to publish an entry after adding content via a Matrix field:
![image](https://user-images.githubusercontent.com/885727/82739052-8d0e9b80-9d0a-11ea-8607-9066c035b1c1.png)

### Steps to reproduce

1. Create a multi-site setup.
2. On 3.5.0-beta.2, create a matrix field with any number of sub-fields, their type doesn't seem to matter, and add it to one of your entry types.
3. Create a new entry, and add a field from your matrix block to it.
4. Attempt to publish the entry (it also errors when trying to save a draft as soon as you add a field from your matrix block).

### Additional info

- Craft version: 3.5.0-beta.2
- PHP version: 7.3.11
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
![image](https://user-images.githubusercontent.com/885727/82739018-5d5f9380-9d0a-11ea-8e16-ef995a765841.png)

**Comment by clowerweb** [comment]
May also be of use: The propagation method on the matrix field is "Only save blocks to the site they were created in".

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "3.5.x-dev",
  "...": "..."
}
```

Then run `composer update`.

**Comment by richardegil** [comment]
@brandonkelly this may be poor form, but I am getting this same issue in 3.4.20 https://github.com/craftcms/cms/issues/6142

**Comment by brandonkelly** [comment]
@richardegil This particular error was definitely introduced by a Craft 3.5 change that wouldn’t affect 3.4.
