### ISSUE TITLE
Sharing project config between sites doesn't work due to plugin licenses stored in project.yaml

### ISSUE THREAD

**Issue by jcherniak** [craftcms/cms#6129]
We offer a simple Craft hosting service for a number of clients who all share the same site configuration.  This works great, especially since we can reference ENV variables in settings (such as asset configuration) and since we can also set a CRAFT_LICENSE_KEY constant (pulled from .env).

The one issue we have is that plugin licenses are stored in the project config, meaning we cannot share the config between installs, even though everything else works.

Given that plugin licenses are linked to your craft license, is there a reason those are stored in the project config at all?  If there is, is there some way we could move those to accepting environmental variables?

**Comment by brandonkelly** [comment]
You can store your plugin licenses as environment variables, yes. Just save the environment variable name in the plugin’s license key input, beginning with a `$` (for example, `$COMMERCE_LICENSE`).

**Comment by jcherniak** [comment]
@brandonkelly, to be clear, $COMMERCE_LICENSE in project.yaml, correct?

**Comment by brandonkelly** [comment]
@jcherniak Yes, you can either add it manually to project.yaml, or enter it into the license input on your Settings → Plugins page.
