### ISSUE TITLE
Element 'isNew' condition now only present in SCENARIO_ESSENTIALS

### ISSUE THREAD

**Issue by BenParizek** [craftcms/cms#6130]
### Description

I haven't been able to figure out what changed yet but some plugin functionality that used to trigger when a new entry was saved is no longer triggering.

What I think I know:

I believe I used to be able to trigger an event when a new entry was created based on the following criteria:

- `craft\base\Element::EVENT_AFTER_SAVE::$isNew` = `true`
- `$element->getScenario()` = `SCENARIO_LIVE`

And it appears the values that are now present when a new entry is created are 

- `craft\base\Element::EVENT_AFTER_SAVE::$isNew` = `true`
- `$element->getScenario()` = `SCENARIO_ESSENTIALS`

I'm a bit concerned to update the code to target `SCENARIO_ESSENTIALS` as I've run into problems with that before as that's the scenario used when Resave Elements events are taking place and it can trigger for all elements. I expect limiting it to the `isNew` condition would be safe, but I'd like to understand what changed before updating to target an entirely different scenario.

Did this behavior change recently? Perhaps when Drafts/Revisions were updated? Is `SCENARIO_ESSENTIALS` now the best one to be targeting for events that want to only take action when new Entries are created?

### Additional info

- Craft version: 3.4.20
- PHP version: 7.3
- Database driver & version: MySQL
- Plugins & versions: Sprout Email

**Comment by brandonkelly** [comment]
This is expected, as noted on the call. We’ll be sure to explain clearly when we address https://github.com/craftcms/docs/issues/97.
