### ISSUE TITLE
Running console commands with required input with a non-TTY stdin causes an infinite loop

### ISSUE THREAD

**Issue by mattgrayisok** [craftcms/cms#6132]
### Description
Running any console commands which have a required or validated input that isn't included as a command line argument causes a prompt to appear asking the user for input. When this happens with a non-TTY stdin the prompt is immediately returned as empty which triggers a validation error and re-prompt resulting in an infinite loop.

This has caught me out in 2 places: 
- Running commands from CI
- Running commands in docker without attaching a TTY

EDIT:

I stopped being lazy and tracked down the bug. It's actually in Yii here:

https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseConsole.php#L800

(Nice to see an oldschool `goto` in there)

So maybe a Yii2 PR would be better than overriding the prompt() method...

### Steps to reproduce

1. echo "loop" | ./craft install

### Additional info

- Craft version: 3.4
- PHP version: 7.3

**Comment by brandonkelly** [comment]
Yeah, this would need to be addressed in Yii.
