### ISSUE TITLE
FR: Disable the cp login page

### ISSUE THREAD

**Issue by aNickzz** [craftcms/cms#6134]
Add an option to disable the `/admin/login` page. We have a custom login page at `/login` and we want to disable the built-in login page. I looked through the documentation and the code and couldn't find any way to disable the `/admin/login` page or how to use a custom template for the page that I could use to redirect to the `/login` page. I also tried setting a custom route but that didn't work.

**Comment by Anubarak** [comment]
You can use the event to redirect to another route

```php
Event::on(
    UrlManager::class,
    UrlManager::EVENT_REGISTER_CP_URL_RULES,
    static function(RegisterUrlRulesEvent $event){
        $event->rules[] = [
            'pattern' => 'login',
            'route' => 'module-id/controller-id/action-id'
        ];
});
```

**Comment by RitterKnightCreative** [comment]
I'd use a server side redirect for this. You still need to access the CP right?

**Comment by brandonkelly** [comment]
Yeah either of those are good suggestions.

**Comment by aNickzz** [comment]
I tried adding a route via `routes.php`, but I don't have a controller for this, its just a template in the templates directory. The form on that page still sends a POST to the built-in `actionLogin` method though.

The way I got this working is with the following event hook

```php
Event::on(Controller::class, Controller::EVENT_BEFORE_ACTION, function (ActionEvent $e) {
    $request = Craft::$app->getRequest();

    if (!$request->getIsConsoleRequest() && $request->getFullPath() === 'admin/login' && !$request->getIsPost()) {
        $e->handled = true;
        $e->isValid = false;

        return Craft::$app->getResponse()->redirect(Craft::$app->getUrlManager()->getBaseUrl() . '/login');
    }
});
```

**Comment by brandonkelly** [comment]
@aNickzz Your `routes.php` routes can point to a template file using the syntax:

```php
'my/url/rule' => ['template' => 'foo/bar'],
```

(https://docs.craftcms.com/v3/routing.html#advanced-routing-with-url-rules)

**Comment by aNickzz** [comment]
Yes, I tried that but it doesn't work for the urls I need it for like `admin/login` and `/admin/set-password`.

```
    'admin/login' => [
        'template' => 'login',
    ],
    'admin/set-password' => [
        'template' => 'set-password',
    ],
```

**Comment by brandonkelly** [comment]
Ah right, OK. Then I’d say @Anubarak’s solution is probably the best: https://github.com/craftcms/cms/issues/6134#issuecomment-633395451
