### ISSUE TITLE
Unable to enter localized data for localized custom user fields

### ISSUE THREAD

**Issue by Friksel** [craftcms/cms#6137]
### Description
After adding localized fields to the user there seems to be no way to switch the current site/locale to another to enter the localized data. I might be missing something but I searched everywhere and couldn't find any switch in the user account ui.

### Steps to reproduce

1. Create localized fields
2. Add these fields to a tab on the user
3. Goto My Account and switch to the new tab
4. You can enter values for the custom fields, but there's no site switch to switch to another site/locale so don't know which site we enter data for here and can't enter localized data for other sites. At least, I couldn't find anything that switches the locale/site for the user account fields

![localized-user-fields](https://user-images.githubusercontent.com/3089978/82857774-44c1ca00-9f12-11ea-81b6-38c4da284e9b.jpg)

### Additional info

- Craft version: 3.4.20 solo

**Comment by brandonkelly** [comment]
Users aren’t localized currently. We’re considering it though – see #1058.
