### ISSUE TITLE
Assets causing n+1 queries, even with eager-loading

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/cms#6140]
### Description

Accessing asset URLs causes n+1 queries, even if you are eager-loading the assets and using the `withTransforms` param.

Reason is because assets are getting their folder path through `getFolder()->path` rather than using the `$folderPath` value already set on the assets. This happens in at least two places:

- `craft\helpers\Assets::generateUrl()` – called when no transform is applied:

  https://github.com/craftcms/cms/blob/a4e4ae5ce7b067f31d00c27770bc3e7c8434ba91/src/helpers/Assets.php#L88

- `craft\services\Assets::getAssetUrl()` in Craft 3.5 (f78ee107fa72d69f81b719968a4cc33f3eb562e2).

Possibly other places as well. We should check usages of `craft\models\VolumeFolder::$path` and see if there are any other places where `craft\elements\Asset::$folderPath` could be used instead.

### Additional info

- Craft version: 3.4.20, 3.5.x-dev

**Comment by BigglesZX** [comment]
@brandonkelly Off the top of your head, any chance this might still be happening when using [aws-s3](https://github.com/craftcms/aws-s3)? I'm currently trying to debug a situation where it appears that using `withTransforms` is having no effect on the number of queries being run, and the queries debug panel shows a bunch of duplicates that appear to be related to asset transforms. We're using an S3 asset volume. If it sounds plausible to you that there might be an issue here, I can attempt to provide more specific info. Thanks!

**Comment by brandonkelly** [comment]
@BigglesZX `withTransforms` will only help if the transforms have already been generated. You know if that’s the case?

**Comment by BigglesZX** [comment]
@brandonkelly Thanks for the reply – yes, already generated.

**Comment by brandonkelly** [comment]
Yeah something’s up. Will look into it.

**Comment by brandonkelly** [comment]
Alright, I’ve fixed this for Craft 3.6 (due out in a couple weeks). 3.6 because the fix involved adding a new ElementQueryInterface method, which could potentially be a minor breaking change, if an element query class is implementing that but not extending `craft\elements\db\ElementQuery`.

**Comment by BigglesZX** [comment]
@brandonkelly That's fantastic, thanks! Will await 3.6 👍

**Comment by brandonkelly** [comment]
Craft 3.6 has now been officially released ✨

**Comment by lenvanessen** [comment]
@brandonkelly it seems this issue has been re-intoduced or is still here:

Right here it calls the AssetsService `getAssetUrl` method:
https://github.com/craftcms/cms/blob/develop/src/elements/Asset.php#L1204

Which itself will call:
https://github.com/craftcms/cms/blob/develop/src/services/Assets.php#L611

Causing the same behavior as described before. It seems that just changing line 611 to: 
$transformPath = $asset->folderPath . $assetTransforms->getTransformSubpath($asset, $index);

Should fix the issue.

**Comment by lenvanessen** [comment]
@andris-sevcenko fyi
