### ISSUE TITLE
Add shortcut for "Create and add another" entry action

### ISSUE THREAD

**Issue by bertoost** [craftcms/cms#6141]
### Description

The "Create and continue editing" action exists with a shortcut. Very useful, since I love to work with shortcuts.
Therefore at initial build of a website I am using "Create and add another" a lot. It would be great to have a shortcut for that one as well. Something like "cmd + shift + s" ?

### Additional info

- Craft version: 3.4.20
- PHP version: 7.4.4

**Comment by brandonkelly** [comment]
This is already requested by #6141

**Comment by brandonkelly** [comment]
This is already requested by #2851

**Comment by bertoost** [comment]
I did search before but not found it 🙈 glad it's on the list already

**Comment by brandonkelly** [comment]
And for posterity, just added it for 3.5 :) https://github.com/craftcms/cms/issues/2851#issuecomment-634984935
