### ISSUE TITLE
Issue: Attempting to duplicate an unsaved element Error

### ISSUE THREAD

**Issue by richardegil** [craftcms/cms#6142]
### Description
I have a Craft instance that has been in development for a couple of months now. Ran all the latest updates for Craft and associated plugins only to get the "Attempting to duplicate an unsaved element." every time I try to save an entry after editing it. It seems to be an issue with Super Table and Neo according to the stack trace.

### Steps to reproduce

1. Edit an entry
2. Save changes
3. Error appears

### Additional info

- Craft version: 3.4.20
- PHP version: 7.3.17
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Super Table 2.4.9 Neo 2.7.12
- Other Plugins: Activity Log 1.01 Conditional Fields 0.0.6 DigitalOcean Spaces Volume 1.1.2 Element API 2.6.0 Entries Subset 1.2.2 Field Manager 2.16 Position Fieldtype 1.0.14 Preparse Field 1.1.0 Redactor 2.6.1 Redactor Custom Styles 3.0.3 Retour 3.1.37 SEOmatic 3.3.4 SendGrid 1.2.0 Simple Sharing 1.0.5 Workflow 1.5.1 oEmbed 1.3.1 Cloner 1.1.0

Stack trace: https://d.pr/n/sUs6Ee

**Comment by BSBjorn** [comment]
I'm having the same issue. If I edit an existing entry and save changes the error occurs. If I save without making changes, the entry is saved. I can also create a new entry, and the new entry is able to be edited and saved. 


PHP version | 7.3.12
MySQL 5.5.5
Craft Pro 3.4.20

Neo 2.7.12
SuperTable 2.4.9

**Comment by brandonkelly** [comment]
Have you updated Super Table and/or Neo recently? Nothing in Craft 3.4 has changed recently that would cause this, as far as I can tell.

**Comment by richardegil** [comment]
Yes, both Craft and Neo are up to date. Would you suggest trying to role them back?

**Comment by brandonkelly** [comment]
Do you have a database backup from before the update? And perhaps composer.json / composer.lock files stored in Git?

**Comment by richardegil** [comment]
Yes, I have both. I included both current and last working instance, notated in the folder names.
https://d.pr/f/lAesiK

Sorry that took a while, dealing with internet in the middle of nowhere Texas :)

**Comment by brandonkelly** [comment]
@richardegil Thanks. Deleted that commend because I’m guessing you don’t want other people downloading those files. Can you point me to a section where you’re experiencing this?

**Comment by richardegil** [comment]
@brandonkelly I appreciate that.

It is in the "Pages" section. All the other once seem to be working fine. But there is another user that posted here in the Neo repo experiencing the same thing. https://github.com/spicywebau/craft-neo/issues/352

**Comment by brandonkelly** [comment]
Ah ok, well then it sounds like Neo is the common denominator here. That issue says they’re seeing this regardless of whether Matrix or Super Table are involved. Will close this, but happy to reopen if it ends up being something we did, as opposed to a Neo bug.

**Comment by richardegil** [comment]
Thanks! I appreciate you looking into it @brandonkelly
