### ISSUE TITLE
[FR] Option to change default “add a tag” button text for tag fields

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#6143]
### Description
Just as you have the option to change the default “add a row” text for a table field it would be great to have the option to set custom text to override the “add a tag” button for tag fields.

My specific use case is we’re using tags to define meta keywords for each of our entry pages. Instead of “add a tag” it would be nicer to have the button label read “add a keyword”.

**Comment by andris-sevcenko** [comment]
I'm pretty sure that this is available in the field settings, though?

<img width="445" alt="Screen Shot 2020-05-27 at 08 45 19" src="https://user-images.githubusercontent.com/1891118/82982235-672d1380-9ff6-11ea-920e-b94411e67d34.png">

**Comment by richhayler** [comment]
Thanks @andris-sevcenko  My mistake. I mistakenly looked for this option in the tag group settings rather than the field settings. Appreciate the correction :)
