### ISSUE TITLE
Failed Image Upload

### ISSUE THREAD

**Issue by NixonGit** [craftcms/cms#6147]
Having an issue uploading new images.

Upload failed. The error message was: “The file “/var/www/vhosts/luxuryfamilyhotels.co.uk/httpdocs/portal/storage/runtime/temp/pjs5ece55d3170671.55359263.jpeg” does not appear to be an image.”

It seems to be an error writing the uploaded image to my uploads folder. The images present are all displaying on the frontend. I've cleared the cache and updated the indexes

PHP version | 7.0.33
OS | Linux 3.10.0-042stab140.4
Database | MySQL 5.5.65
Image driver | Imagick 3.4.3 (ImageMagick 6.7.8-9)
Craft version |Craft Pro 3.1.12

Plugins:

Asset Rev | 6.0.2
Cookies | 1.1.11
Expanded singles | 1.0.7
Phone number | 1.2.1
Redactor | 2.3.1

**Comment by andris-sevcenko** [comment]
There should be a stack trace in your log files (storage/logs/web.log) with more information.

**Comment by RitterKnightCreative** [comment]
Sounds like a generic system message.  Could be permission denied or out of space, etc. Did you recently deploy? Could be SELinux doing all kinds of funkiness too unless you whitelist folders and processes.

**Comment by brandonkelly** [comment]
Sometimes when we see this, it’s due to a misconfigured ImageMagick install on the server. You can work around that by explicitly setting your [imageDriver](https://docs.craftcms.com/v3/config/config-settings.html#imagedriver) config setting to `'gd'` in `config/general.php`:

```php
'imageDriver' => 'gd',
```

**Comment by NixonGit** [comment]
Setting the imageDriver to GD did the trick. 

Thanks all, appreciate the input.
