### ISSUE TITLE
Changing Dropdown Option Label or Value on a Matrix Field

### ISSUE THREAD

**Issue by adamski-g** [craftcms/cms#6148]
### Description
There’s a bug that’s popped up quite a few times for me and my team. It’s when you have a field name on a dropdown within a Matrix field and then change that name I.e from “x” to “y”. When you open a page entry to edit the new dropdown, the page throws an error. In order to get round this you have to then change all the dropdown fields to the new name. It feels like this should default to the new dropdown. It can mean a lot of work, and causes the client frustration - especially if it’s on a blog type entry where there can be hundreds of pages.

### Steps to reproduce

1. Create a new Matrix and add a new block
2. Make the block a dropdown
3. Give the option label a name and value and save
4. Add the Matrix to a page and choose a dropdown option
5. Go back into the Matrix dropdown and change the label / value
6. Open up the entry to edit and it will throw an error

### Additional info

- Craft version: Craft Pro 3.4.20
- PHP version: 7.1.30
- Database driver & version: MySQL 5.7.25
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
If by “throw an error”, you mean you get a validation error when saving the field, then this is fixed now for the next release.

![Screenshot 2020-05-27 at 16 20 17](https://user-images.githubusercontent.com/47792/83081801-5dc39b80-a036-11ea-8d5e-252ed2d071f6.png)

If you meant something else, please provide the error message and its stack trace (can be found in `storage/logs/web.log`) and I can look further into it.

**Comment by adamski-g** [comment]
Hi Brandon,
Yeah that error exactly. Thanks.

**Comment by brandonkelly** [comment]
Craft 3.4.21 is out now with that fix.
