### ISSUE TITLE
Converting channel to structure didn't work as expected

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#6150]
### Description

I converted a channel to a structure to allow the items to be re-ordered and everything appeared to go fine - except, not quite. I can now re-order the entries in the CP; however, my Entries field referencing that section is now mangled:
- Each pre-existing entry selected now appears twice
- The entries are still re-orderable in the field

Additionally, we were using GraphQL to query for some data and I found that the structure returned is not representative of what is shown in the CP. Specifically, the order does not match. 

### Steps to reproduce

1. Convert a channel to a structure (set max levels to 1 in my case)

### Additional info

- Craft version: Craft CMS 3.4.20
- PHP version: 7.3.13
- Database driver & version: MySQL 8.0.19
- Queue: 2 queue runners per this [article](https://nystudio107.com/blog/robust-queue-job-handling-in-craft-cms) (maybe this is the issue?)
- Plugins & versions:
```
Amazon S3	1.2.8
Bulk Edit	2.0.4
Cache Flag	1.0.3
CP Field Inspect	1.1.3
Element API	2.6.0
Element Map	1.2.1
Feed Me	4.2.3
Field Manager	2.1.6
Freeform	3.6.9
Imager	v2.4.0
Mailgun	1.4.3
Maps	3.8.3
MatrixMate	1.2.5
Minify	1.2.10
Preparse Field	v1.1.0
Redactor	2.6.1
Redactor Split	1.1.0
Redirects	3.0.6
Retcon	2.1.0
Reverse Relations	1.2.1
SEOmatic	3.3.4
Super Table	2.4.9
Twigpack	1.2.1
Typed link field	1.0.21
Typogrify	1.1.18
Video Embedder	1.1.4
```

Sent database to support@craftcms.com

Fixes I've tried:

- Resaved entries with the relation fields
- Disabled Reverse Relations
- Switched back to channel and back to structure
- Delete duplicates and resave (just adds duplicates back)
- Cleared caches

**Comment by Mosnar** [comment]
Oli and I worked on this over support (Case 6653) and weren't able to reproduce it. Somehow there was an extra structure row created that caused the duplicates - we deleted the extra structure row in the database and it removed the duplicates and solved the problem. My best guess is it has to do with the two queue workers, but I have no idea how that could have resulted in two structures. 

Feel free to close this out or shelve it.

**Comment by brandonkelly** [comment]
Did this happen on the initial environment you changed the section type for? Or on another environment, based off a `project.yaml` sync?

**Comment by Mosnar** [comment]
@brandonkelly Yes, this happened on the initial environment. We're not using project config on the project.

**Comment by brandonkelly** [comment]
Huh, ok. Not really sure what could have caused this then. Maybe double-clicking the Save button? (Tried but wasn’t able to reproduce.) The structure is created, and the entries are all added to it, all on that initial save-section request, not via a queue job. Will close, but if you or someone can come up with steps to reproduce, we can look into it again and get it fixed.

**Comment by ahockemeyer** [comment]
Same exact issue -- is there a fix for this?
