### ISSUE TITLE
White Transparent PNG's are invisible in Control Panel - UX issue

### ISSUE THREAD

**Issue by jonlongnecker** [craftcms/cms#6151]
### Description
I have a site that uses some line illustration images for pages. They happen to be white as the backgrounds they go on top of are dark.

Because the background of all images is completely white in the CP, choosing assets and displaying them in the entry means they are invisible. You can potentially see them on hover while choosing assets and after selecting the field in an entry, but neither of these are intuitive at all.

![craft3-transparent-invisible](https://user-images.githubusercontent.com/2390/83068741-9f941800-a01d-11ea-8738-fedbcc4813b5.png)
![craft3-selected](https://user-images.githubusercontent.com/2390/83068740-9efb8180-a01d-11ea-945a-af4490f2b3f2.png)

Craft 2 correctly showed a photoshop like grid behind transparent elements, but that seems to be missing in Craft 3. 

![craft2-transparent-grid](https://user-images.githubusercontent.com/2390/83068738-9dca5480-a01d-11ea-953d-85764f21da1c.png)

From a UX perspective, it's imperative that the client can actually see the image they've selected in all contexts so I'd like to see the Craft 2 behavior reinstated.

- Craft version: 3.4

**Comment by brandonkelly** [comment]
Just added that back for the next release!

**Comment by brandonkelly** [comment]
Craft 3.4.21 is out now with this change.
