### ISSUE TITLE
[Accessibility FR] Underline links in field instructions

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#6153]
Could we underline links in the field instructions in the control panel? I've never really used links in instructions before, but I tried it just now and wasn't sure it was working as the contrast difference is so low. Events is a linked word below:

![image](https://user-images.githubusercontent.com/1250017/83121090-8d2be400-a0da-11ea-91c5-10a2d0c5438c.png)

I know it's probably not vital information but it would still be useful, and encouraged by [WCAG 1.4.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-without-color.html).

**Comment by brandonkelly** [comment]
Just added a new “Underline links” user preference, for Craft 3.5 :)

**Comment by darylknight** [comment]
Awesome, thank you.
