### ISSUE TITLE
Content is being deleted after adding a matrix block to Preview

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#6154]
### Description

Sorry I have no idea how to reproduce this or what's causing it, but I've now seen the issue on two separate sites so I'm filing an issue about it with what info I have.

In the attached video [removed], you can see:

1. Clicking Preview
2. Scrolling through the preview section, showing all matrix blocks
3. Scrolling through the editor, showing all matrix blocks
4. Adding a new matrix block to the bottom of the page
5. All the other blocks are still in the editor on the left, but they disappear from the Preview on the right
6. When I close preview, all the matrix blocks are still there in the CMS
7. Click publish. All the blocks except the one I just added are deleted

### Additional info

- Craft version: 3.4.20
- PHP version: 7.4
- Database driver & version: MySQL

**Comment by brandonkelly** [comment]
Do you have any plugins or modules installed?

**Comment by darylknight** [comment]
My bad; I've traced this to Super Table I think (still really weird) - I'll file a new issue there.

**Comment by brandonkelly** [comment]
Josh looped me in, and this ended up being a Matrix bug. Fixed for the next release!
To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop as 3.4.22.1",
  "...": "..."
}
```

Then run `composer update`.

**Comment by darylknight** [comment]
Thanks for digging in and solving it Brandon & Josh!

**Comment by brandonkelly** [comment]
Craft 3.4.23 is out now with the fix for this.
