### ISSUE TITLE
Craft.js syntax error on 3.5

### ISSUE THREAD

**Issue by samhibberd** [craftcms/cms#6155]
Running into a javascript error in the minified version of `Craft.js` that is generated in the cpresources folder:

> Uncaught SyntaxError: Lexical declaration cannot appear in a single-statement context

Running 3.5 (6d045ea2fb74d5284879ab5cd3173a8975bdab79)

<img width="1070" alt="Screenshot 2020-05-28 at 14 43 24" src="https://user-images.githubusercontent.com/1846063/83159822-55369800-a0fe-11ea-9d34-7b7816e555ba.png">

**Comment by brandonkelly** [comment]
Able to reproduce. I’ll fix shortly. In the meantime you can work around it by adding this to `config/general.php`:

```php
'useCompressedJs' => false,
```

**Comment by brandonkelly** [comment]
Fixed now!
