### ISSUE TITLE
CP DB backup progress bar fills immediately / unmeaningfully

### ISSUE THREAD

**Issue by olets** [craftcms/cms#6156]
### Description

In 3.4.20 the CP backup progress bar doesn't seem to have an relation to the actual progress. I just upgraded from 3.1.24 so this could have been introduced anywhere in the last many versions.

Not shown in the GIF: a minute or so later, the time I'd expect, the db downloads.

![backup-progress](https://user-images.githubusercontent.com/3282350/83162602-f2caa100-a0d7-11ea-9a7e-663e6c957458.gif)

### Steps to reproduce

1. Download a db backup in the CP

### Additional info

This is Chrome 83

- Craft version: 3.4.20
- PHP version: 7.2.24
- Database driver & version: MySQL 5.7.29
- Plugins & versions:

<table class="data fullwidth fixed-layout" dir="ltr">
<tbody>
<tr>
<th class="light">Advanced Url Field</th>
<td>1.0.0</td>
</tr>
<tr>
<th class="light">Amazon S3</th>
<td>1.2.8</td>
</tr>
<tr>
<th class="light">Analytics</th>
<td>4.0.10</td>
</tr>
<tr>
<th class="light">Asset Rev</th>
<td>6.0.2</td>
</tr>
<tr>
<th class="light">Control Panel Nav</th>
<td>3.0.12</td>
</tr>
<tr>
<th class="light">Cookies</th>
<td>1.1.12</td>
</tr>
<tr>
<th class="light">CP Field Inspect</th>
<td>1.1.3</td>
</tr>
<tr>
<th class="light">Element Map</th>
<td>1.2.1</td>
</tr>
<tr>
<th class="light">Embedded Assets</th>
<td>2.2.4</td>
</tr>
<tr>
<th class="light">Entry Instructions</th>
<td>1.0.7</td>
</tr>
<tr>
<th class="light">Environment Label</th>
<td>3.2.0</td>
</tr>
<tr>
<th class="light">Expanded Singles</th>
<td>1.1.2</td>
</tr>
<tr>
<th class="light">Field Manager</th>
<td>2.1.6</td>
</tr>
<tr>
<th class="light">Flat Categories</th>
<td>2.0.0</td>
</tr>
<tr>
<th class="light">Image Resizer</th>
<td>2.0.8</td>
</tr>
<tr>
<th class="light">Inventory</th>
<td>2.1.0</td>
</tr>
<tr>
<th class="light">Matrix Colors</th>
<td>2.0.1</td>
</tr>
<tr>
<th class="light">Password Protect</th>
<td>1.0.0</td>
</tr>
<tr>
<th class="light">Redactor</th>
<td>2.6.1</td>
</tr>
<tr>
<th class="light">Redirect plugin for Craft 3</th>
<td>1.0.23</td>
</tr>
<tr>
<th class="light">SuperSort</th>
<td>3.0.1</td>
</tr>
<tr>
<th class="light">Super Table</th>
<td>2.4.9</td>
</tr>
<tr>
<th class="light">Twig Perversion</th>
<td>2.1.0</td>
</tr>
<tr>
<th class="light">Video Embed</th>
<td>1.2.1</td>
</tr>
</tbody>
</table>

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.21 is out now with that fix.
