### ISSUE TITLE
Allow blocking plugin updates

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#6157]
Would it be possible to add some hook/event/something else that would allow me to block plugin update?

Use case:
I am thinking of creating a plugin that would provide some basic template files by adding second template root. By default, plugin updates could be disabled, so devs don't wreck their page by updating template files that their "child theme" depends on. Basically, avoiding the thing that sometimes happens when one updates wordpress theme. If dev wanted to update the plugin, he would need to set a variable in plugin config file.

**Comment by brandonkelly** [comment]
Hm… not sure about this one. And even if we added something, it wouldn’t stop people from updating the plugin with `composer update`.
