### ISSUE TITLE
actionUpload controller - return full file URL

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#6158]
Thanks for recent update that shows duplicate filename :)

Would it also be possible to return the full file URL? So it could be immediately displayed.  Depending on field settings, file it can land in various places, so I need to check for these settings to construct URL in my frontend upload form. It would be easier if I just got ready to use URL.

**Comment by andris-sevcenko** [comment]
Why not? Just added for the next 3.4 release!

**Comment by piotrpog** [comment]
@andris-sevcenko 
In commit I see that you added `conflictingAssetUrl` - that's useful too, but what I meant is returning URL of file even if there is no conflict.
