### ISSUE TITLE
Config file updated on Matrix Field with not global context

### ISSUE THREAD

**Issue by andrelopez** [craftcms/cms#6161]
### Description
Stripe Payments make use of a couple of custom matrix fields, these fields are created with context = `enupalStripe:{plugin-uid}`, I did this way as users don't need to update these fields on the CP and also to avoid being loaded in the config file, I understand that only fields with context=global are loaded.

So when `'useProjectConfigFile' => true,` we noticed that the `project.yaml` file is updated with some `matrixBlockTypes` these matrixBlockTypes are related to the matrix fields with context `enupalStripe:{plugin-uid}` and should not be loaded here.

However the Matrix fields with context `enupalStripe:{plugin-uid}` are not loaded in the `project.yaml` file which is good but the `matrixBlockTypes` are loaded and this is causing the following error when applying existing project config on a different env:

```
> installing enupal-stripe ... done
    > applying existing project config ... Exception: The following config paths could not be processed successfully:
matrixBlockTypes.3bdd7809-9322-4183-8c9a-83a9e9c9e194
matrixBlockTypes.9dbcafa6-3d26-48f7-ba30-6555cc407d2d
matrixBlockTypes.ee5e88ea-4ab8-4e93-a31e-a2e0383ecad3
matrixBlockTypes.3c6d7273-2ed3-4b2d-833f-c1a3e5335af7
....
```

### Steps to reproduce

1. Set useProjectConfigFile' => false 
2. Install Stripe Payments
3. Set useProjectConfigFile' => true
4. Check the `project.yaml` has matrixBlockTypes related to matrix fields with not global context from Stripe Payments.

### Additional info

- Craft version: 3.4.10
- PHP version: 7.3
- Database driver & version: mysql
- Plugins & versions: Stripe Payments 2.6.2

**Comment by brandonkelly** [comment]
That’s a tricky one. I think you will just need to start storing your Matrix field in the config. To do that, instead of calling `Craft::$app->fields->saveField()`, do something like this:

```php
$field->context = 'yourCustomContext';

if (!$field->beforeSave($field->getIsNew())) {
    throw new Exception('The Matrix field doesn\'t want to be saved');
}

if (!$field->validate()) {
    throw new Exception('The Matrix field couldn\'t be saved due to a validation error');
}

Craft::$app->fields->prepFieldForSave($field);
$configData = Craft::$app->fields->createFieldConfig($field);

Craft::$app->projectConfig->set("enupalStripe.fields.$field->uid", $configData, "Save Enupal Stripe field “{$field->handle}”");
```

Then from your plugin’s `init()` method, add an event listener for project config changes to your fields’ configs:

```php
public function init()
{
    parent::init();

    Craft::$app->projectConfig
        ->onAdd("enupalStripe.fields.{uid}", [$this, 'handleChangedField'])
        ->onUpdate("enupalStripe.fields{uid}", [$this, 'handleChangedField'])
        ->onRemove("enupalStripe.fields.{uid}", [$this, 'handleDeletedField']);
}

// ...

public function handleChangedField(\craft\events\ConfigEvent $event)
{
    $data = $event->newValue;
    $fieldUid = $event->tokenMatches[0];
    Craft::$app->fields->applyFieldSave($fieldUid, $data, 'yourCustomContext');
}

public function handleDeletedField(\craft\events\ConfigEvent $event)
{
    $fieldUid = $event->tokenMatches[0];
    Craft::$app->fields->applyFieldDelete($fieldUid);
}
```

Hope that helps. Let me know if you have any questions.

**Comment by andrelopez** [comment]
@brandonkelly Thank you! that helped me a lot
