### ISSUE TITLE
3.4.21 Thumbnailpreview causes bug in PDF and Video Assets 

### ISSUE THREAD

**Issue by jbogendoerfer** [craftcms/cms#6162]
### Description
Trying to edit a PDF or Video-Asset in the backend causes:
TypeError
Argument 1 passed to craft\helpers\Assets::scaledDimensions() must be of the type integer, null given, called in /var/www/..../vendor/craftcms/cms/src/elements/Asset.php on line 1000

### Steps to reproduce
Upate to 3.4.21, in backend select Assets, click on a PDF or Video Asset

### Additional info

- Craft version: 3.4.21
- PHP version: 7.1.3
- Database driver & version: MySQL 5.5.5
- Plugins & versions: 
Complete Cookie Consent	1.0.8.3
Freeform	3.6.9
Maps	3.8.3
Neo	2.7.12
Redactor	2.6.1
SEO	3.6.5.1
Super Table	2.4.9
Typed link field	1.0.21

**Comment by zenbug** [comment]
Ugh. I just spent hours troubleshooting this, thinking it was just me. Glad I found this bug report before end-of-day Friday.

**Comment by brandonkelly** [comment]
Thanks for reporting that. Fixed, and will get a release out soon.

**Comment by brandonkelly** [comment]
3.4.22 is out now with the fix.
