### ISSUE TITLE
config/general.php merges Arrays

### ISSUE THREAD

**Issue by idleog** [craftcms/cms#6163]
### Description
If I have 

```
...
'*'=>['foo'=>['bar'=>['bar1]]] ...
'dev'=>['foo'=>['bar'=>['bar2']]] 
...
```
in config/general.php

I'll get 
`['bar1','bar2'] `
for 
`Craft::$app->config->general->foo['bar']`
when i'm in 'dev' environment.

Is that a bug or a feature?
Cheers
Peter

### Additional info

- Craft version: 3.4.9
- PHP version: 7.0.33
- Database driver & version: 
- Plugins & versions:

**Comment by brandonkelly** [comment]
That’s expected. We use [ArrayHelper::merge()](https://www.yiiframework.com/doc/api/2.0/yii-helpers-basearrayhelper#merge()-detail) to merge the arrays together.
