### ISSUE TITLE
Google drive storage adapter

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#6164]
Would it be possible to create plugin that adds google drive as storage adapter?

Google drive also uses flyststem standard and there are some existing php libs for handling this, for example this:

https://github.com/nao-pon/flysystem-google-drive

I even copied existing google cloud craft plugin and tinkered with it using this adapter i linked above - it kinda half-worked, for example could upload files, but not delete them :)

**Comment by brandonkelly** [comment]
Probably possible but I wouldn’t recommend it, since you should only use volumes that aren’t human-accessible. Otherwise Craft’s asset indexes will frequently go out of sync.
