### ISSUE TITLE
User verification Code Invalid

### ISSUE THREAD

**Issue by rohit-kk** [craftcms/cms#6165]
### Description
I am using Craft CMS as backend for react Next app. On our live site we are sometime getting complaints from the user about error when user try to verify code sent in the email.

This case doesn't happen with every user but only for some random users. For this reason I am not able to find the reason for the issue and fix it.  
Everytime I see following information in the log file.

> 2020-05-27 10:17:35 [-][-][-][warning][craft\services\Users::isVerificationCodeValidForUser] The verification code (gqkZpvgTZDMNSXRyNuXE4ksxpNOlBOl) given for userId: 99965 does not match the hash in the database.
2020-05-27 10:17:35 [-][-][-][info][application] $_GET = [
    'p' => 'ACT/craft-rest-api/user/verify-email'
    'code' => 'gqkZpvgTZDMNSXRyNuXE4ksxpNOlBOl'
    'id' => 'ef2156d6-306b-4a88-80bb-25ca26562702'
]

Here is the information about the system.

PHP version	7.4.5

OS version	Linux 3.10.0-1127.el7.x86_64

Database driver & version	MySQL 8.0.20

Image driver & version	GD 7.4.5

Craft edition & version	Craft Pro 3.4.21

Yii version	2.0.35

Twig version	2.12.5

Guzzle version	6.5.4

Imagine version	1.2.3-dev

Plugins:-

Amazon S3	1.2.8

Architect	2.3.3

CKEditor	1.0.0-beta.3

Comments	1.5.6

Contact Form	2.2.7

Craft-Rest-Api	1.1.0

Enforce password	1.0.0

Image Resizer	2.0.9

Klaviyo Connect	3.1.3.2

Redactor	2.6.1

SendGrid	1.2.0

 

### Steps to reproduce

1.
2.

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Verification codes are changed whenever a new email is added to the user. Maybe they are changing their email multiple times and then clicking on the link of an outdated email?
