### ISSUE TITLE
Graphql | asset inside supertable -> matrix is empty

### ISSUE THREAD

**Issue by stephanedemotte** [craftcms/cms#6167]
### Description

I've got a a matrix inside a supertable.
In my graphql response, all field are ok except the asset field

<img width="1433" alt="Screen Shot 2020-05-30 at 12 53 28 PM" src="https://user-images.githubusercontent.com/2158130/83334453-ae283c80-a274-11ea-90a2-8c4fb434fa0b.png">

As you can see, the first cover/asset field is ok.
But when my field is inside a supertable->matrix, boom empty :/

Thanks !

### Additional info

- Craft version: Craft Pro 3.4.21
- PHP version: 7.3.17
- Database driver & version: MySQL 5.7.30
- Plugins & versions: SuperTable (2.4.9)

**Comment by andris-sevcenko** [comment]
Thanks for reporting that! This issue has actually already been covered by #5998,
and it’s been improved for Craft 3.5.
