### ISSUE TITLE
New Structure entries are created at level 1, even if they have a parent entry selected

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#6168]
### Description

When creating a new Structure Entry, even if a parent Entry is selected in the "Parent" field, the new Entry is created at level 1 and at the bottom of the Structure.

This only applies to new Entries; selecting a parent Entry when editing an existing Entry works as expected.

I've tested this on both 3.4.20 and 3.4.22.1; it does not happen on the former (did not test 3.4.21 or 3.4.22).

The Craft install is not multi-site.

### Steps to reproduce

1. Create a Structure section, and add some entries to it
2. Click "New Entry" from the Entry index
3. Select a parent Entry in the Parent field, and save the new Entry
4. Confirm that the new Entry sits at level 1 at the bottom of the Structure, rather than being nested under the selected parent Entry

### Additional info

- Craft version: 3.4.22.1
- PHP version: 7.2.20
- Database driver & version: 5.6.43 Homebrew
- Plugins & versions: none

**Comment by tom-id-au** [comment]
Hey, I can confirm we're also experiencing this after applying recent updates - child items are ending up on top level, triggering template errors, including when disabling/undisabling items. We're on the latest Craft Pro 3.4.22.1.

**Comment by brandonkelly** [comment]
I’ve narrowed this down to any time a new draft is published (including the initial unsaved draft you get when creating a new entry), the source entry won’t pick up the new parent specified by the draft.

**Comment by brandonkelly** [comment]
This is now fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.23 is out now with the fix.
