### ISSUE TITLE
Control search input behavior

### ISSUE THREAD

**Issue by effer89** [craftcms/cms#6170]
### Description
Hi, I need to have more control over the search input.

I manage to only trigger the search when length >= 4, but another require it's to only trigger search when Enter is pressed.

There's an easy way to achieve this?

Thanks!

![image](https://user-images.githubusercontent.com/13169985/83455558-7f58c480-a434-11ea-9021-8384865423a8.png)

**Comment by brandonkelly** [comment]
Sorry, not currently possible, and we are going to be making some big changes to how searching works in the next couple releases, so I would recommend you avoid trying to hack in your own changes. 

If you have specific feature requests, feel free to post those as new issues (one issue per request, please).
