### ISSUE TITLE
Confusing error message after save if matrix field with minimum block count has no blocks

### ISSUE THREAD

**Issue by olets** [craftcms/cms#6173]
### Description

If a matrix field has fewer than the required number of blocks at the time of save, the save errors and the field is padded with new blocks to meet the minimum.

So far so good! But the error message that comes with it is potentially confusing. The message is "<field name> should contain at least <minimum> blocks." Because of the automatic-padding behavior (which again I would not want to see go away, it's great) the user is left looking at a field with the correct number of blocks and a message apparently saying 'the entry could not be saved because this field needs at least as many blocks as it in fact has.'

### Steps to reproduce

1. Create a matrix field with a minimum block count
1. Create a section
1. Add the field to the section
1. Create an entry in the section
1. In the entry, delete a block from the matrix field
1. Save the entry

### Additional info

This is Chrome 83

- Craft version: 3.4.20
- PHP version: 7.2.24
- Database driver & version: MySQL 5.7.29
- Plugins & versions:

<table class="data fullwidth fixed-layout" dir="ltr">
<tbody>
<tr>
<th class="light">Advanced Url Field</th>
<td>1.0.0</td>
</tr>
<tr>
<th class="light">Amazon S3</th>
<td>1.2.8</td>
</tr>
<tr>
<th class="light">Analytics</th>
<td>4.0.10</td>
</tr>
<tr>
<th class="light">Asset Rev</th>
<td>6.0.2</td>
</tr>
<tr>
<th class="light">Control Panel Nav</th>
<td>3.0.12</td>
</tr>
<tr>
<th class="light">Cookies</th>
<td>1.1.12</td>
</tr>
<tr>
<th class="light">CP Field Inspect</th>
<td>1.1.3</td>
</tr>
<tr>
<th class="light">Element Map</th>
<td>1.2.1</td>
</tr>
<tr>
<th class="light">Embedded Assets</th>
<td>2.2.4</td>
</tr>
<tr>
<th class="light">Entry Instructions</th>
<td>1.0.7</td>
</tr>
<tr>
<th class="light">Environment Label</th>
<td>3.2.0</td>
</tr>
<tr>
<th class="light">Expanded Singles</th>
<td>1.1.2</td>
</tr>
<tr>
<th class="light">Field Manager</th>
<td>2.1.6</td>
</tr>
<tr>
<th class="light">Flat Categories</th>
<td>2.0.0</td>
</tr>
<tr>
<th class="light">Image Resizer</th>
<td>2.0.8</td>
</tr>
<tr>
<th class="light">Inventory</th>
<td>2.1.0</td>
</tr>
<tr>
<th class="light">Matrix Colors</th>
<td>2.0.1</td>
</tr>
<tr>
<th class="light">Password Protect</th>
<td>1.0.0</td>
</tr>
<tr>
<th class="light">Redactor</th>
<td>2.6.1</td>
</tr>
<tr>
<th class="light">Redirect plugin for Craft 3</th>
<td>1.0.23</td>
</tr>
<tr>
<th class="light">SuperSort</th>
<td>3.0.1</td>
</tr>
<tr>
<th class="light">Super Table</th>
<td>2.4.9</td>
</tr>
<tr>
<th class="light">Twig Perversion</th>
<td>2.1.0</td>
</tr>
<tr>
<th class="light">Video Embed</th>
<td>1.2.1</td>
</tr>
</tbody>
</table>

**Comment by brandonkelly** [comment]
I’m not able to reproduce that – the validation error begins with the field name, e.g. “My Field should contain at least 2 blocks”. Have you provided a custom static translation for your field name that replaces it with an empty string, or something like that?

**Comment by olets** [comment]
🤦  I didn't account for Markdown's handling of angle brackets

<kbd><img src="https://user-images.githubusercontent.com/3282350/83647178-99a0b880-a582-11ea-86c4-40afaaeb0ec2.png"></kbd>


"\<field name> should contain at least \<minimum> blocks"

Confusing because, thanks to the auto-padding, it's possible to not see the message until the reported requirement is already satisfied. Might complicate the erroring setup's conditions but something like "\<field name> should contain at least \<minimum> blocks. You may now resave.", or "\<field name> should contain at least \<minimum> blocks. The necessary blocks have been added automatically but are emtpy", etc

**Comment by brandonkelly** [comment]
Ahh, gotcha. I just tweaked the behavior for the next release, so additional blocks will no longer be created if there is a validation error on the field.

**Comment by olets** [comment]
That works, thanks!

Lowest possible priority follow up question, feel free to never respond: after looking at the change (and I admit without reading through the whole file) and seeing all the many contexts where `createDefaultBlocks` will be false, I'd be interested to hear if there's some common context where it will be true.

**Comment by brandonkelly** [comment]
It is `true` whenever Min Blocks is set, and the field only has one block type (so we can safely assume which type of blocks to auto-create), and (as of the next release) there are no validation errors on the field.

**Comment by brandonkelly** [comment]
Craft 3.4.23 is out now with this change.

**Comment by olets** [comment]
Thanks!
