### ISSUE TITLE
Bug: Multi-site - entry index switch following entry save

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#6174]
### Description
In a multi-site setup I'm encountering an issue where upon saving an entry in site A I'm being sent to the entries index for site B. This happens specifically in the following scenario:

### Steps to reproduce

1. Create or edit an entry for site A that contains an entries field (within a matrix) set to "manage relations on a per site basis"
2. Click on the entries field and select an entry from site B
3. Save the original entry (Site A)
4. User is sent to Site B's entries index instead of site A's entries index

### Additional info

- Craft version: 3.4.22.1

_I haven't validated the above scenario if the entries field is not within a matrix to see if this results in the same behaviour._

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.23 is out now with the fix.
