### ISSUE TITLE
[FR] Add instructions for title

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#6175]
### Description

It would be nice if the title field also had instructions. That is all :)

This could be added to the entrytypes table as a new `titleInstructions` column.

@brandonkelly is this something a custom behaviour could achieve?

**Comment by brandonkelly** [comment]
That’s already been requested by #1518.

For the time being, you’d need to hide your Title field and use a custom field instead. Adding custom instructions shouldn’t be too hard to add though, so I’ll see if I can get to it for 3.5.

**Comment by brandonkelly** [comment]
For posterity, this has now been added for 3.5.
