### ISSUE TITLE
isSystemLive doesn't read environment variable value

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#6177]
### Description

In `config/general.php`, I have three arrays in addition to the  _Global settings_: one for _dev_, one for _staging_, and one for _prod_.

Inside each of these 3 environments, I have added the `isSystemLive` setting which should read value from the _.env_ file.

Even if `IS_SYSTEM_LIVE` is set in the _.env_ file with `IS_SYSTEM_LIVE=false` or `IS_SYSTEM_LIVE=false` or `IS_SYSTEM_LIVE=0`, and ` 'isSystemLive' => (bool) getenv('IS_SYSTEM_LIVE')` or just `'isSystemLive' => getenv('IS_SYSTEM_LIVE')`, the value isn't read. If `false`, the website remain visible (even when not logged in).

### Steps to reproduce

1. In `config/general.php`, set `isSystemLive` to `getenv('IS_SYSTEM_LIVE')`
2. In _.env_, set `IS_SYSTEM_LIVE` to `false`
3. In `/admin/settings/general`, do not edit: just re-Save

### Additional info

- Craft version: Craft Pro 3.4.22.1
- PHP version: 7.1.30
- Database driver & version: MySQL 5.7.26

**Comment by brandonkelly** [comment]
Setting it to `(bool)getenv('IS_SYSTEM_LIVE')` should work, but only if you set the variable to [an empty value](https://www.php.net/manual/en/function.empty.php), such as an empty string or `0`. Note that `IS_SYSTEM_LIVE=false` will set it to the string `"false"`, which is not considered an empty value.

Alternatively, you can run the environment variable through [filter_var()](https://www.php.net/manual/en/function.filter-var.php), which does in fact interpret `"false"` to mean `false`.

```php
'isSystemOn' => filter_var(getenv('IS_SYSTEM_LIVE'), FILTER_VALIDATE_BOOLEAN),
```
