### ISSUE TITLE
Console command clear-caches doesn't respect options

### ISSUE THREAD

**Issue by billythekid** [craftcms/cms#6178]
### Description

I've been getting a bunch of ansi color control characters in my logs when running `./craft clear-caches/all` so passed the `--color=0` flag but still get them.

After some investigating (I thought I'd just PR this but I've gotten a bit lost) it seems that the `\console\actions\ClearCacheAction ` calls a different `stdout()` (actually `Console::output()` wrapper)  than the regular controllers (which is why when you call `./craft clear-caches` you can add the `color=0` flag and it's respected. It uses the inherited `yii\console\Controller` `stdout` method in its messages, which calls `isColorEnabled()` which returns 1 or 0 depending on that option.

I tried accessing stuff inside the ClearCacheAction myself such as $this->color and $this->options but was going down a rabbit hole and debugging in the console was, err, troublesome.

I'm not actually sure if this is a Craft issue or a Yii issue as a lot of this seems to come from base classes.

### Steps to reproduce

1. in the console run the following commands and observe the differences.
- `./craft clear-caches`
- `./craft clear-caches --color=0`
- `./craft clear-caches/all`
- `./craft clear-caches/all --color=0`

### Additional info

- Craft version: 3.4.17.1
- PHP version: tested this in 7.3 and 7.4

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.23 is out now with the fix.
