### ISSUE TITLE
Disabling parent block in live preview causes children to save to top level

### ISSUE THREAD

**Issue by tom-id-au** [craftcms/cms#6180]
#### Description
When editing in live preview, if you disable a block, the child blocks are saved on the same level as the parent block, not child blocks. Does not occur outside of live preview.

#### Steps to reproduce
1. Create a page with a block with child blocks
2. Open in live preview and disable the parent block
3. Save, then check back to find the child blocks on same level as parent (top level)

#### Other information
- Craft version: Craft Pro 3.4.22.1
- Neo version: 2.7.13

It appears to be okay with Neo 2.7.13 and Craft 3.4.20, so I'm assuming it is an issue that has come out in Craft 3.4.21, Craft 3.4.22 or Craft 3.4.22.1. There are lots of changes relating to structures in those Craft updates.

Also reported to neo - unsure who is responsible for fix
https://github.com/spicywebau/craft-neo/issues/356

**Comment by ttempleton** [comment]
We found that this was happening when disabling the parent Neo block while editing any entry draft.  We've just updated Neo to make sure that block duplication applies the original block's level to the duplicated block, which fixes the issue with Neo blocks and entry drafts; but [Neo's block duplication method](https://github.com/spicywebau/craft-neo/blob/2.7.14/src/services/Fields.php#L307) uses the Craft elements service's `duplicateElement()`, so it looks like `duplicateElement()` isn't applying the correct level to the new element in this specific case.

**Comment by brandonkelly** [comment]
This may be fixed by 4b39c14b9fe2d1edb3315558975bd646bf35af18. Please change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop as 3.4.22.1",
  "...": "..."
}
```

Then run `composer update`, and see if that fixes this Neo issue.

**Comment by ttempleton** [comment]
Testing with `dev-develop` and removing the code that was added to Neo, the child blocks of the disabled parent block are saved at the top level again.

**Comment by brandonkelly** [comment]
Alright in that case it’s most likely a Neo bug. Has an issue already been reported over there? If not can you add one? I can offer to help from there.
