### ISSUE TITLE
[develop branch] Add new matrix block menu is appearing behind the Preview sidebar

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#6181]
### Description

I'm currently on the develop branch as a workaround for https://github.com/craftcms/cms/issues/6154 and just noticed that when adding a new Matrix block, the menu that pops up appears behind the Preview sidebar:

![image](https://user-images.githubusercontent.com/1250017/83736936-01c2cd80-a65b-11ea-8f5d-26eea48eea05.png)

Maybe this is fixed on master or just not an issue, but flagging anyway. I'd guess it's a z-index thing but I can't click on it with console to test as it disappears as soon as I un-focus it.

Same thing happens when trying to add an image. The modal that pops up is behind the content sidebar:

![image](https://user-images.githubusercontent.com/1250017/83737334-81e93300-a65b-11ea-8b37-abb096936f30.png)

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next release.
