### ISSUE TITLE
Export entries: Uncaught This view is not selectable.

### ISSUE THREAD

**Issue by carolineboeykens** [craftcms/cms#6183]
### Description
This user group has only permissions to edit entries for this section. When a user from this user group tries to export the entries from this section a console error occures. Which permission does he need to have to perform this action?
When we enable all permissions for this section it works, but we don't want them to change this content.

### Steps to reproduce

1. Create section
2. Create user group
3. Set permissions for user group for this section to: edit entries and nothing else
<img width="491" alt="Screen Shot 2020-06-05 at 10 19 48" src="https://user-images.githubusercontent.com/42932673/83857370-2d0cf180-a71b-11ea-84ca-640b24b54378.png">
4. Sign in as a user from this group
5. Try to export entries from this section
<img width="120" alt="Screen Shot 2020-06-05 at 10 57 01" src="https://user-images.githubusercontent.com/42932673/83857465-5168ce00-a71b-11ea-8cad-61e97202d9cc.png">
6. A console error occures
<img width="391" alt="Screen Shot 2020-06-05 at 10 54 48" src="https://user-images.githubusercontent.com/42932673/83857382-30a07880-a71b-11ea-966a-7ea2906c439d.png">

### Additional info

- Craft version: 3.4.22.1
- PHP version: 7.2.21

**Comment by brandonkelly** [comment]
I’m not able to reproduce this, and the error doesn’t seem related to permissions to me.

Is this happening on your production environment? Could you create a new user for support@craftcms.com in that user group, so we can try to reproduce it there?

**Comment by carolineboeykens** [comment]
Okay, I sent an activation mail to support@statik.be for our staging environment.

**Comment by brandonkelly** [comment]
@carolineboeykens We haven’t seen any account activation emails come in. Can you please resend it?

**Comment by carolineboeykens** [comment]
@brandonkelly, I sent the activation mail a while ago. Did you have time to take a look at it? Maybe it got lost, should I resend it again?

**Comment by brandonkelly** [comment]
Sorry for the delay, and thanks for giving us access! The piece I was missing is, the user has to have no bulk actions available – which means in addition to only having the basic editing permissions, the section couldn’t have a URI format so entries didn’t get public URLs.

Just got that fixed for the next release. To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop as 3.4.25",
  "...": "..."
}
```

Then run `composer update`.

**Comment by carolineboeykens** [comment]
Thank you!

**Comment by brandonkelly** [comment]
Craft 3.4.26 is out now with this fix.
