### ISSUE TITLE
When saving a new Entry or duplicating one, the altered Matrix values set in the EVENT_BEFORE_SAVE are overwritten

### ISSUE THREAD

**Issue by mellissageutskens-npo** [craftcms/cms#6191]
### Description
When I try to duplicate an Entry or save a new Entry, the values I've altered in the Matrix Block during the `EVENT_BEFORE_SAVE` are overwritten. 

For example: I have an Entry type named `Chart Edition`, which has a Matrix field `positions`. This Matrix field has a field `totalPositions`. When I duplicate another `Chart Edition`, I want the `totalPositions` increased by 1. I alter this field value in the `EVENT_BEFORE_SAVE`. When I log `$entry->positions->all()` before the return, I get the altered data. But when I save the Entry, the altered data is gone.

```php
Event::on(Entry::class, Element::EVENT_BEFORE_SAVE, function(ModelEvent $e) {
  $entry = $e->sender;

  // Prepare the positions field for adjustments.
  $field = Craft::$app->getFields()->getFieldByHandle('positions');
  $serializedMatrix = $field->serializeValue($entry->positions, $entry);

  // If the Entry is new and a duplicate, alter the data.
  if ($entry->duplicateOf instanceof Entry && $e->isNew) {
    // Increase the total positions with 1.
    foreach ($serializedMatrix as &$position) {
      $position['fields']['totalPositions']++;
    }
  }

  // Set the positions field value.
  $entry->setFieldValue('positions', $serializedMatrix);

  // Logging the $entry->positions->all() here returns the altered data.

  // After this event has been returned, the altered data is gone.
  return $e;
});
```

### Steps to reproduce

1. Create an Entry type with Matrix fields. 
2. Create a custom module.
3. Create an EVENT_BEFORE_SAVE method in your custom Module.php.
4. Alter the Matrix field value in the EVENT_BEFORE_SAVE method. 
5. Create a new Entry. Fill in the Matrix field. Save the entry.
6. Open the Entry. The altered data is gone.

### Additional info

- Craft version: Craft Pro 3.4.22.1
- PHP version: 7.3.7
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

**Comment by brandonkelly** [comment]
Yeah changing field values during duplication isn’t supported, because Matrix fields will re-query all of their old blocks before duplicating them for the new entry.

You could get this to work from `EVENT_AFTER_SAVE` though:

```php
Event::on(Entry::class, Element::EVENT_AFTER_SAVE, function(ModelEvent $e) {
  $entry = $e->sender;

  // If the Entry is new and a duplicate, alter the data.
  if ($entry->duplicateOf instanceof Entry && $e->isNew) {
    // Increase the total positions with 1.
    foreach ($entry->positions->all() as $position) {
      $position->setFieldValue('totalPositions', $position->totalPositions++);
      Craft::$app->elements->saveElement($block);
    }
  }
});
```

**Comment by mellissageutskens-npo** [comment]
@brandonkelly Thanks for the reply. Unfortunately this doesn't seem to work either. Maybe I'm doing something wrong, but it seems to be the same problem as in the before save. I even tried to save the whole entry after saving the matrix blocks, but still nothing changes. Could you take another look please?

```
// If the Entry is new and a duplicate, alter the data.
Event::on(Entry::class, Element::EVENT_AFTER_SAVE, function (ModelEvent $e) {
  $entry = $e->sender;

  if ($entry->section->handle !== 'chartEdition' || ElementHelper::isDraftOrRevision($entry)) {
    return $e;
  }

  if ($entry->duplicateOf instanceof Entry && $e->isNew) {
    // Increase the total positions with 1.
    foreach ($entry->positions->all() as $position) {
      $position->setFieldValue('lastPosition', $position->position);
      $position->setFieldValue('totalPositions', $position->totalPositions++);

      Craft::$app->elements->saveElement($position);
    }

    $success = Craft::$app->elements->saveElement($entry);

    if (!$success) {
      Craft::error("Couldn't save entry: " . print_r($entry->getErrors(), true));
    }
  }
});
```

**Comment by brandonkelly** [comment]
Just tested, and it’s working but there’s a slight logical bug: `$position->totalPositions++` is going to return the _old_ totalPositions value. Whenever you put `++` _after_ the variable, it will return the current value and _then_ increment the original value by 1. Whereas if you put the `++` _before_ the variable, then it will increment first, then return. So if you change that line to:

```php
$position->setFieldValue('totalPositions', ++$position->totalPositions);
```

then it works as expected. However since `++` can generally be a little confusing/hard to remember, and also since you have no reason to increment the old totalPositions value (you’re about to overwrite the value anyway), I’d change it to this instead:

```php
$position->setFieldValue('totalPositions', $position->totalPositions + 1);
```

Also, these lines aren’t necessary anymore, since we are saving the blocks directly now:

```php
$success = Craft::$app->elements->saveElement($entry);

if (!$success) {
    Craft::error("Couldn't save entry: " . print_r($entry->getErrors(), true));
}
```
