### ISSUE TITLE
Call to a member function getVolume() on null

### ISSUE THREAD

**Issue by thijskaspers** [craftcms/cms#6193]
Since updating to v1.4.0 and Craft 3.4.22.1 we are getting the following error:

`Upload failed. The error message was: “Call to a member function getVolume() on null”`

Strange, because I don't really see anything in the recent changes that could've caused this. I'm still in the dark, It might have something to do with project-config sync combined with 1.4.0, but not sure yet.

What we did was this:

- Update Craft and the Google Cloud plugin on local machine from 1.3 to 1.4 (uploads on localhost working fine)
- Deploy to server and run project/config sync command (uploads on server throw the error)

On my local machine it was still working with v1.4, but after downloading the database from the server and importing that on my local machine, it stopped working.

I've tried clearing all caches and resaving all volumes (this changes the 'keyFileContents' volume settings in the yaml file), but no luck yet.

What's worth mentioning: the error is thrown, but the upload to Google Cloud is working. Refreshing the page after the error shows the file has been uploaded.

**Comment by andris-sevcenko** [comment]
Fixed for the next Craft 3.4 release.

**Comment by brandonkelly** [comment]
Craft 3.4.23 is out now with the fix.
