### ISSUE TITLE
logoutUrl link is unintentionally logging out user on front-end

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#6195]
### Description

I found a really weird behaviour, and I had hard times finding it. On a website which has a login form on front end, if the `logoutUrl` is added to the template (example: `{% if currentUser %}<a href="{{ logoutUrl }}">Logout</a>{% endif %}`), it will unintentionally log out the user on the next page reload or page visit. The logout does not occur is the link is not present in the page.

### Steps to reproduce

1. Log in from front-end
2. Visit a page with a `logoutUrl` link (without clicking this link)
3. Reload the page or visit another page
4. User is now logged out :(

### Additional info

- Craft version: Craft Pro 3.4.22.1
- PHP version: 7.1.30
- Database driver & version: MySQL 5.7.26

**Comment by brandonkelly** [comment]
Do you have any sort of link preloading going on via JS on your site?

**Comment by romainpoirier** [comment]
Good point! Thank you! Yes, I was testing [Quicklink](https://getquick.link) and totally forgot it.
