### ISSUE TITLE
Cached 404s are not cleared when saving an entry that uses the same URL

### ISSUE THREAD

**Issue by pierrestoffe** [craftcms/cms#6197]
### Description

We like to cache 404s, especially during a few weeks after a big website has been launched, as many people and bots try and reach URLs that don't exist anymore. Today we finally found out why some of our clients sometimes had this issue where an entry would return a 404 even though they just published an entry that matched that URL.

Basically, if you cache 404s and someone visits a URL that does not match any entry today, the resulting 404 gets cached. The moment you create an entry with the same URL as that 404 you expect that the cached 404 gets cleared... but it actually isn't. This is because the 404 that was cached isn't related to any element ID while Craft only clears the caches that match the element ID of the entry that was saved, as explained [in the docs](https://docs.craftcms.com/v3/fr/dev/tags/cache.html#cache-clearing).

I never thought that this could be an issue, and I guess I'm not the only one that ran into it. An easy solution is to stop caching 404s of course, but maybe a real and better solution can be provided by the CMS?

### Steps to reproduce

1. Enable caching
3. Visit /test => the 404 page is returned ✅
4. Create an entry with the URL /test
5. Visit the URL of the entry => the 404 page is still returned ❌
6. Re-saving the entry doesn't change anything.

### Additional info

- Craft version: 3.4.22.1
- PHP version: 7.3.13
- Database driver & version: MySQL 5.7

**Comment by brandonkelly** [comment]
How are you caching the page? Using a `{% cache %}` tag or something else?

**Comment by pierrestoffe** [comment]
We use the following rule to create the caches, using the(% cache %}  tags:

```
{% set requestPathInfo = craft.app.request.pathInfo %}
{% set requestQueryString = craft.app.request.queryStringWithoutPath %}
{% set requestQueryStringHash = requestQueryString|length ? craft.businessLogic.createHash(requestQueryString) : '' %}
{% set cacheKey = (requestPathInfo|length ? '_' ~ requestPathInfo) ~ (requestQueryStringHash|length ? '_' ~ requestQueryStringHash) %}
{% set cacheKeyHash = cacheKey %}
{% cache using key now|date('Y-m-d') ~ cacheKeyHash if cacheEnabled %}
```

The resulting keys are something like this:
`2020-06-11_about`
`2020-06-11_about_dae4a5649bd1b3ebc260fdf6cdeeacc3`
`2020-06-12_about/subpage`

**Comment by brandonkelly** [comment]
And I take it that happens from your layout template or something?

Unfortunately there’s not really an elegant way for us to solve this in core. I’d suggest looking into the [Cache Flag](https://plugins.craftcms.com/cache-flag) plugin, or if you are using this for effectively full-page caching, check out [Blitz](https://plugins.craftcms.com/blitz).
