### ISSUE TITLE
[FR] Revert to draft

### ISSUE THREAD

**Issue by johandouma** [craftcms/cms#6198]
### Description

I don't seem to be able to revert an entry without publishing it. Can I revert to a draft, which I can then modify and publish? 

### Additional info

- Craft version: 3.4.23
- PHP version: 7.4

**Comment by brandonkelly** [comment]
This shouldn’t be necessary anymore since the underlying issue is fixed for 3.5. (#6199)

**Comment by johandouma** [comment]
Hi Brandon, I still think reverting to draft would be handy, to make changes before publishing for example.

**Comment by brandonkelly** [comment]
That’s what drafts are for though?
