### ISSUE TITLE
It's too easy to publish draft using Ctrl+S shortcut

### ISSUE THREAD

**Issue by johandouma** [craftcms/cms#6199]
### Description

I have, countless times, pressed ctrl+s or cmd+s inadvertently (reflex) on a draft, and published it when I wasn't done. It's is extremely annoying when I do so; I have to revert the entry to an older version, but then there is no option to revert to a draft (see #6198). Should the shortcut be ignored/disabled when editing a draft? 

### Additional info

- Craft version: 3.4.23
- PHP version: 7.4

**Comment by johandouma** [comment]
I think that would make sense.

**Comment by brandonkelly** [comment]
Just made that change for the next 3.5 Beta release.
