### ISSUE TITLE
[FR] GraphQL: parseRefs directive

### ISSUE THREAD

**Issue by MatthiasGrandl** [craftcms/cms#6200]
Would be cool to be able to query a markdown field and be able to use reference tags instead of using hard links.

**Comment by andris-sevcenko** [comment]
@MatthiasGrandl That is brilliant.

**Comment by andris-sevcenko** [comment]
Do you have any specific markdown field in mind?

**Comment by MatthiasGrandl** [comment]
So what I imagined this would look like is having just a plaintext field and I'd write something like
```
[link to an entry here]({entry:5})
```
And then once I query this plaintext field I do
```gql
query {
  entry {
    text @markdown @parseRefs
  }
}
```
Hope this makes things clear.

**Comment by andris-sevcenko** [comment]
Ah, gotcha.

**Comment by andris-sevcenko** [comment]
Just added this for Craft 3.5!

**Comment by MatthiasGrandl** [comment]
Very cool, thanks!
