### ISSUE TITLE
[FR] Add option to customise image editor constraints

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#6201]
### Description

It would be nice if we could add or even fully customise the cropping aspect ratios in the image editor. Adding a new custom value could easily be implemented with a hook or a config setting:

![image](https://user-images.githubusercontent.com/25124/84268403-eb40d880-ab6a-11ea-8a77-d8f6fb235bda.png)

Requested here: https://github.com/craftcms/cms/issues/4359#issuecomment-557728635

My use case which involves additional requirements is to show the user a "safe zone" in the "cropperGrid" by adding additional grid lines. I wonder if this would also be possible as an advanced custom config for the cropping aspect ratio.

Example: The blue guides would be the "cropperGrid" lines with an aspect ratio of 32:9

![image](https://user-images.githubusercontent.com/25124/84268690-686c4d80-ab6b-11ea-8ebc-8fbccb392015.png)

**Comment by andris-sevcenko** [comment]
> My use case which involves additional requirements is to show the user a "safe zone" in the "cropperGrid" by adding additional grid lines. I wonder if this would also be possible as an advanced custom config for the cropping aspect ratio.

@leevigraham can you post that as a separate issue, please?

**Comment by andris-sevcenko** [comment]
Just added this for Craft 3.5.
