### ISSUE TITLE
[FR] "linked" custom routes

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#6206]
We have a multi language site setup for a shop where we defined the checkout urls in the routes.php so we don't have to create entries for it. Via a language switcher we are making sure to redirect to the right slug, but here's a problem for these custom routes.

```
return [
   'siteNL' => [
      'winkelmand' => ['template' => '_shop/cart']
   ],
   'siteEN' => [
      'cart' => ['template' => '_shop/cart']
   ]
]
```
Where with normal entires/categories/products there is a relation between each other, I don't see how to let Craft know that `winkelmand` and `cart` are the "same" url but in a different language.

**Comment by brandonkelly** [comment]
I’m not sure how we could solve this; I think you’d just need to hard-code the alternate URLs into your language switcher logic.

**Comment by WHITE-developer** [comment]
Couldn't find the right solution myself but this plugin is close to what I need/a solution https://github.com/craftcms/cms/issues/3308#issuecomment-500815287

2 things that should make the solution complete:
1. the `services/Routes.php` function `getConfigFileRoutes` could get an optional siteHandle parameter so we can get the same named route but for another site
2. their should be an option to get the named route by uri. 

So that we first search for the namedRoute by a uri to then get the translated route by the namedRoute and siteHandle
