### ISSUE TITLE
/graphql endpoint in Craft 3.5 doesn't allow for 'X-Craft-Token'-headers

### ISSUE THREAD

**Issue by FreekVR** [craftcms/cms#6207]
### Description
Trying to query the GraphQL endpoint cross-origin and applying the 'X-Craft-Token'-header to fetch a specific entry preview doesn't work, because it doesn't allow this header, the response only contains:
```
access-control-allow-credentials: true
access-control-allow-origin: *
```

### Steps to reproduce

1. Run the CMS and domain on different domains
2. Attempt to fetch some data from the GraphQL endpoint with an "X-Craft-Token" header using XHR
3. ```Access to XMLHttpRequest at 'aaa/graphql' from origin 'bbb' has been blocked by CORS policy: Request header field x-craft-token is not allowed by Access-Control-Allow-Headers in preflight response.```

### Additional info

- Craft version: 3.5-beta3 (may also apply to 3.4x?)
- PHP version: 7.2
- Database driver & version: not applicable
- Plugins & versions: not applicable

**Comment by brandonkelly** [comment]
Just included `X-Craft-Token` to the `Access-Control-Allow-Headers` response header for `graphql/api` preflight requests, for the next Craft 3.4 and 3.5 releases.

**Comment by brandonkelly** [comment]
Craft 3.4.24 is out now with this change.
