### ISSUE TITLE
Missing spanish translation in "Save" button dropdown menu

### ISSUE THREAD

**Issue by zzseba78** [craftcms/cms#6208]
### Description
Missing spanish translation when creating a new entry and the "Save" dropdown menu, attach screenshot.

It should say: "Guardar y continuar editando" and "Guardar y añadir otra"

![Captura de Pantalla 2020-06-11 a la(s) 17 31 30](https://user-images.githubusercontent.com/5558563/84436365-b46dcf80-ac09-11ea-986d-15611d77cbda.png)

### Steps to reproduce

1. In spanish admin version, Create a new entry.
2. Open "Save" button dropdown menu.

### Additional info
- Craft version: latest

**Comment by brandonkelly** [comment]
We manage Craft’s translations [on Crowdin](https://crowdin.com/project/craft-cms). Would you mind submitting the translations there?
