### ISSUE TITLE
Combination of matrix field an image transform results in allowSelfRelations unknown Property error

### ISSUE THREAD

**Issue by johnny-gruber** [craftcms/cms#6210]
### Description

I have an issue when I use a matrix field in combination with a file field. As soon as I use the image field I get this error: 
```
Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: craft\fields\Assets::allowSelfRelations
```
For context: It only breaks on my local machine. There imagick is not running and I only use to transform all images to webp. Although the image im uploading in the matrix file will not be converted to webp. Even if I don't output anything, the error shows up.

### Steps to reproduce

1. Add Matrix field
2. Add file field and set it to image only (with image transforms)

### Additional info

- Craft version: Craft Solo 3.4.23
- PHP version: 7.1.33
- Database driver & version: MySQL 5.7.26
- Plugins & versions: Imager v2.4.0

**Comment by tommers-walker** [comment]
Ditto, having the same issue

**Comment by brandonkelly** [comment]
That error doesn’t make any sense; `craft\fields\Assets::$allowSelfRelations` definitely exists. Maybe there was an issue during the Composer update that prevented the new `src/fields/BaseRelationField.php` file from getting downloaded properly, or the old file is cached by OPcache or something.

Try nuking your `vendor/` folder and then running `composer install`.
