### ISSUE TITLE
Unexpected behavior for user permissions Deselect All button

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/cms#6211]
### Description

When a user has permissions applied by a user group and the *Deselect All* button is used, it can remove the `disabled` attribute from >1st level checkboxes, causing them to become editable.

### Steps to reproduce

1. Create a user group with a 2nd level permission enabled, e.g. *Moderate Users*.
2. Assign a user to that group and save.
3. Return to user's permissions and click *Select All* for the permissions group with 2nd level permission enabled.
4. Click *Deselect All* for same group. 2nd and 3rd level checkboxes that were applied by the user group now have the `disabled` attribute removed and can be checked/unchecked.

### Additional info

- Craft version: Pro 3.4.22.1
- PHP version: 7.4.5
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.24 is out now with this fix.
