### ISSUE TITLE
URL Slug and german umlauts

### ISSUE THREAD

**Issue by Jan10** [craftcms/cms#6214]
### Description
German umlauts (and probably other foreign characters) are not correctly converted to slug. "Hähnchengeschnetzeltes" becomes "hähnchengeschnetzeltes" instead of "haehnchengeschnetzeltes" oder "Bücher" becomes "bücher" instead of "buecher".

### Steps to reproduce

1. Create a new entry with "Bücher" or "Hähnchengeschnetzeltes"
2. The automatically generated slug is not correct.

![Markup 2020-06-14 at 09 44 52](https://user-images.githubusercontent.com/192557/84587953-c034de00-ae23-11ea-92a7-6b8be48acc5a.png)

### Additional info

- Craft version: 3.4.23

**Comment by angrybrad** [comment]
If you set the [limitAutoSlugsToAscii](https://docs.craftcms.com/v3/config/config-settings.html#limitautoslugstoascii) config setting to `true`, you'll get the behavior you're looking for.
