### ISSUE TITLE
GraphQL queries flyout has transparent background

### ISSUE THREAD

**Issue by elfacht** [craftcms/cms#6215]
### Description

A minor style bug: with multiple GraphQL queries the explorer shows a transparent background in the flyout.

![Screenshot 2020-06-14 um 17 55 54](https://user-images.githubusercontent.com/529443/84598097-75898500-ae68-11ea-841d-2899d8fa9347.jpg)

- Craft version: 3.4.23

**Comment by andris-sevcenko** [comment]
This has been fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 3.4.24 is out now with this fix.
