### ISSUE TITLE
[3.5 beta 3] Edit asset attributes from entry looses subfolder

### ISSUE THREAD

**Issue by JeanLucEsser** [craftcms/cms#6217]
### Description

If you try to edit let's say the title of an asset (or any other field) from within an entry (by double clicking the asset and saving it from the popup), if the asset is located in a subfolder, it gets moved back to the volume root.

### Steps to reproduce

1. Create an entry
2. Add an asset to the entry (make sure the asset is in a subfolder)
3. Without leaving the entry edit page, edit the just added asset and change its title
4. Save the asset and the entry
5. The asset has moved out of its original subfolder location to the volume root

Note: this does not happen when editing an asset from the asset view.

**Comment by andris-sevcenko** [comment]
I'm not able to reproduce this. Can you share the Asset field settings?

**Comment by JeanLucEsser** [comment]
Actually I'm wrong, sorry about that, I thought it was more complex than it is:

When saving an entry with assets in it, the assets in a subfolder get moved back to the volume root folder. 

My asset field setting is basic, it's in a matrix though.
Here's a capture.

<img width="795" alt="Capture d’écran 2020-06-15 à 16 47 18" src="https://user-images.githubusercontent.com/14908712/84671694-f6f41c80-af27-11ea-902d-4d2ac7cf0097.png">

**Comment by andris-sevcenko** [comment]
Gotcha. I'm able to reproduce this.

**Comment by samhibberd** [comment]
I think we are running into this also, although for us the asset is being moved off to the Temporary 
Uploads folder.

**Comment by brandonkelly** [comment]
Just fixed that for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "3.5.x-dev",
  "...": "..."
}
```

Then run `composer update`.
