### ISSUE TITLE
Craft::$app->session->setFlash() doesn’t work as expected since an update from 3.4.20 to 4.4.22.1

### ISSUE THREAD

**Issue by jesuismaxime** [craftcms/cms#6218]
### Description

I’m working on a custom module for a client and I need to give the user some feedback when updating an Entry (using the `EVENT_BEFORE_SAVE_ELEMENT` event). 

Everything was working properly since I update Craft (I am not the only dev on this project so I have to go on with the newer C version).

Note: An update to 3.4.23 **did’nt** fix the issue. 

### Steps to reproduce

I use this method (according to Yii documentation):
```
Craft::$app->session->setFlash($flash_type, $flash_message);
```

I try with static/harcoded string, with or without the 3rd parameter (`bool`): still not working.

If I dump the $event in the process, I can clearly see the actual Flash I try to set (`jobillico-success`) and my test (obviously `test`):

```
$_SESSION = [
    'bd62416aa8538ede709019a5e113eea5__flash' => [
        'jobillico-success' => -1
        'test' => -1
        'notice' => 1
    ]
    '1031b8c41dfff97a311a7ac99863bdc5__token' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    '1031b8c41dfff97a311a7ac99863bdc5__id' => '1252'
    'enableDebugToolbarForCp' => true
    'bd62416aa8538ede709019a5e113eea5__auth_access' => [
        0 => 'previewElement:4261'
        1 => 'previewElement:6330'
    ]
    'jobillico-success' => 'Jobillico: Job successfully published to Jobillico.'
    'test' => 'hello'
    'notice' => 'Entrée enregistrée.'
]
```

### Additional info

- Craft version: 3.4.23
- PHP version: 7.2.22

**Comment by brandonkelly** [comment]
The Craft control panel only cares about flash messages registered with the category `notice` or `error`. And you can use `Craft::$app->session->setNotice()` or `Craft::$app->session->setError()` to set them, and not worry about getting the category right.

**Comment by jesuismaxime** [comment]
I'm using `error` and `success` (can't find where I get that the 3 possible options was success, info and error). I can’t use setNotice because it seems to be override by the default "save with success" notice - that's why I move along with `setFlash()`.

When I was (last week when it was working) using `success` I was able to see the default notification and mine – maybe my memories are blur-ish but I was - for sure - able to see the "my" success notice (since it's a crucial part of my module and tells me if the action is properly called) and two blue "bubbles". 

Maybe the default "save with success" notice is now called later and override my `setFlash()` ?

Note: if I use the `error` type everywhere, I am able to see my flash

**Comment by brandonkelly** [comment]
There can only be one flash message per category at a time. If you are showing the flash messages on the front-end, then you are welcome to use categories besides `notice` and `error`. The control panel just won’t be able to show them.

> Note: if I use the `error` type everywhere, I am able to see my flash

That will conflict with Craft’s own error flash messages if there is a validation error, etc.

**Comment by icreatestuff** [comment]
When I use `Craft::$app->session->setFlash('test', '123');` inside a custom module controller I don't get anything output when I place `{{ craft.app.session.getFlash('test') }}` within a frontend template. 

If however I use `Craft::$app->session->setNotice()` and `{{ craft.app.session.getFlash('notice') }}` I do get the output. Are custom flash keys just not possible at all?

Craft: 3.4.27

**Comment by brandonkelly** [comment]
@icreatestuff It’s definitely possible; `setNotice()` and `setError()` are just wrappers for `setFlash()`.

**Comment by icreatestuff** [comment]
@brandonkelly That's what I though but not what I'm seeing. I presume running
```php
Craft::$app->session->setNotice('test notice');
Craft::$app->session->setFlash('test', '123');
```
should be fine too? In that one wouldn't overwrite another?

**Comment by brandonkelly** [comment]
> I presume running
> 
> ```
> Craft::$app->session->setNotice('test notice');
> Craft::$app->session->setFlash('test', '123');
> ```
> 
> should be fine too? In that one wouldn't overwrite another?

No, you can only store one flash message per unique key. So the second line would in fact overwrite the original message.

**Comment by icreatestuff** [comment]
@brandonkelly sorry for the wild goose chase! It is working as expected, but turns out my custom `UsersController` wasn't being picked up and everything was being sent to Craft's core UsersController. 🙄

**Comment by brandonkelly** [comment]
Hah, no worries, glad you got to the bottom of it!
