### ISSUE TITLE
FR: GraphQL slugs for other sites on the same entry (useful for i18n)

### ISSUE THREAD

**Issue by Marcuzz** [craftcms/cms#6224]
### Description

We're currently building a headless Craft CMS application with a Nuxt frontend, we're using Nuxt i18n and we have ran into a problem. Because the customer wants i18n we naturally need translateable slugs to work too, now our issue is that at the time of switching language in the frontend we don't know the slug for the same entry in a different site. 

This works fine if you could only switch language on the index page but if we want to switch language from a dynamic page we get a problem when attempting to fetch the entry with the slug for the previous "site". **As far as I can see there's no way for the front-end to know about the slug for a different site for the same entry.**

One obvious solution would be to fetch the data using the entry's ID instead of the slug and then replace the URL, but that is considerably harder to implement using Nuxt i18n and I'm not even sure if it's possible to do so.

That's why I propose a way to get the element sites associated with an entry in GraphQL. 
This _should_ be easily achievable through a relation on the `elements_sites` table and it would allow us to query something like:

```graphql
query ($site: [String], $section: [String], $slug: [String]) {
  entry (site: $site, section: $section, slug: $slug) {
    id
    slug
    sites {
      handle,
      slug
    }
  }
}
```

If the above feature is implemented we would easily be able to use [this](https://github.com/nuxt-community/nuxt-i18n/blob/master/docs/lang-switcher.md#dynamic-route-parameters) or [this](https://nuxt-community.github.io/nuxt-i18n/routing.html#custom-paths) in Nuxt i18n and I'm sure other frontend frameworks like React and Angular have equivalents where the same behaviour is preferred.

I hope you would consider this as it would help us tremendously!

**Comment by andris-sevcenko** [comment]
> As far as I can see there's no way for the front-end to know about the slug for a different site for the same entry.

That is actually covered by https://github.com/craftcms/cms/issues/6045 and implemented for Craft 3.5!

> That's why I propose a way to get the element sites associated with an entry in GraphQL.

That is, however, covered by https://github.com/craftcms/cms/issues/5082. It won't be making the cut for 3.5, however, but it's on the shortlist of things next up for GraphQL.

I hope this covers all the questions you had!

**Comment by Marcuzz** [comment]
Awesome, thank you for the quick answer! 

I forgot to search by closed issues and didn't find anything related to this 😅 but #6045 solves our problem 😄

**Comment by qikkeronline** [comment]
@Marcuzz - sorry to break open this topic; but I am currently trying to do the same (implementing a headless Craft CMS application with a Nuxt frontend and i18n), but I am struggling with passing the language to the query in a nice way. Did you find a way to pass the `i18n.locale` to every graphql query, without repeating code? Or are you passing this on every query manually?

**Comment by Marcuzz** [comment]
@qikkeronline I ended up just passing the chosen language as a variable to every single query. In my case I only have a couple of queries so it wasn't as much of a pain. We used Neo Matrix to build a website where every section could be moved wherever the client desires, so we ended up effectively only having one rather massive query making use of fragments 😅

**Comment by qikkeronline** [comment]
Thanks so much @Marcuzz - very helpful. I'll share here if I find a better way 👍

**Comment by qikkeronline** [comment]
@Marcuzz - I actually did find a way to abstract this, from within the apollo/clientConfig key inside nuxt.config.js:

```
apollo: {
    clientConfigs: {
        default: '~/apollo/config/default.js'
    }
},
```
And then:
```
import { ApolloLink } from 'apollo-link'
export default (context) => {
    return {
        link: new ApolloLink((operation, forward) => {
            operation.variables.lang = context.i18n.locale === 'nl' ? 'default' : context.i18n.locale
            return forward(operation)
        }),
        httpEndpoint: 'http://xxx.xxx.xxx/api'
    }
}
```

**Comment by Marcuzz** [comment]
That's a nice solution! Thanks for sharing @qikkeronline 😄

**Comment by yasin7044** [comment]
Can you please explain what it does
import { ApolloLink } from 'apollo-link'
export default (context) => {
    return {
        link: new ApolloLink((operation, forward) => {
            operation.variables.lang = context.i18n.locale === 'nl' ? 'default' : context.i18n.locale
            return forward(operation)
        }),
        httpEndpoint: 'http://xxx.xxx.xxx/api'
    }
}
