### ISSUE TITLE
User groups not accessible in user activation email

### ISSUE THREAD

**Issue by sweetroll** [craftcms/cms#6225]
### Description
As the title says, a user's groups are not available in the activation email if it is sent using the 'Send an activation email now?' checkbox.

### Steps to reproduce

1. Add reference to user.groups (or any method that uses groups) in activation email in system messages.
2. Create new user, assign them to a group and check 'Send an activation email now?'
3. Sending activation email again via the actions dropdown shows correct data.

### Additional info

- Craft version: 3.4.24
- PHP version: 7.4.6 (Nitro)
- Database driver & version: MySQL 5.7.30
- Plugins & versions: None

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop as 3.4.24",
  "...": "..."
}
```

Then run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.4.25 is out now with the fix for this.
