### ISSUE TITLE
[3.5.0-beta.3] Internal server error with "parent" selector in Element/GraphQL

### ISSUE THREAD

**Issue by Marcuzz** [craftcms/cms#6227]
### Description

When querying for `parent` in GraphQL in either version `3.5.0-beta.3` and the latest 3.5 commit (3c9f654) it will throw a 500 internal server error from PostgreSQL: `Invalid text representation: 7 ERROR:  invalid input syntax for type integer: \"\"\`

I believe the error is this, it's comparing an integer field to an empty string:

![image](https://user-images.githubusercontent.com/3168421/84940537-44b38500-b0e0-11ea-9347-43bd6f977239.png)

### Steps to reproduce

1. Make the following GraphQL query:

```graphql
query {
  entry {
    uri
    parent {
      uri
    }
  }
}
```

2. You'll now have an internal server error

### Additional info

- Craft version: 3.5.0-beta.3 AND 3.5.x-dev 3c9f544
- PHP version: 7.4
- Database driver & version: PostgreSQL 12.2
- Plugins & versions: Disabled all plugins

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Please send your `composer.json` and `composer.lock` files, as well as a database backup, into support@craftcms.com, and we can look into it from there.

**Comment by Marcuzz** [comment]
Of course, an email has been sent your way 📫

**Comment by stephanedemotte** [comment]
Same error here but when i use alias.

Work on v3.5 beta 5, but not with `3.5.x-dev`

![Uploading Screen Shot 2020-06-20 at 4.42.46 PM.png…]()

**Comment by andris-sevcenko** [comment]
@stephanedemotte that's a different error. Lemme open a new issue for that one and see if I can fix that real quick.

**Comment by andris-sevcenko** [comment]
@Marcuzz FWIW, it's not a GraphQL error exactly. With the files you sent over I can reproduce it with the following element query: `{% set entries = craft.entries.with(['parent']).one() %}`

**Comment by Marcuzz** [comment]
Yeah I figured it was actually an elements error rather than GraphQL, but didn't test it so I labelled the issue as a GraphQL error 😃

**Comment by brandonkelly** [comment]
Just got this fixed for the next release.
