### ISSUE TITLE
Tags are case-sensitive, even when allowSimilarTags is false

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#6229]
### Description

Tags are case-sensitive, even when `allowSimilarTags` is false.

### Steps to reproduce

1. Create a tag called FOO
2. Create another tag called foo

### Additional info

- Craft version: 3.4.24
- PHP version: 7.4.6
- Database driver & version: PostgreSQL 12.3
- Plugins & versions: -

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.25 is out now with the fix.
