### ISSUE TITLE
[Request] Change timestamp in backup filename to not make me think I traveled back in time 14 years

### ISSUE THREAD

**Issue by proimage** [craftcms/cms#6231]
### Description
Contrary to first glance, `[sitename]_200618_181431_[UID of some sort]_v3.4.23.sql` was not generated back in 2006. 😒

Didn't we learn not to 2-digit years about 20 years ago?

I hereby request the `YYYY-MM-DD_HH.MM.SS` format for the timestamp part of the filename, por favor. 😉 

### Steps to reproduce

1. Backup the Craft database using the built-in tools for doing so.
2. Stare at the filename in confusion for a while until your 2am brain realizes what's going on.
3. ????
4. PROFIT (from unambiguous date-time representations)!

### Additional info

- Craft version: 3.4.23.does-it-really-matter-in-this-case
- PHP version: 7.something

**Comment by brandonkelly** [comment]
Just switched it up for Craft 3.5.

Example: `happy-lager--2020-06-18-194131--v3.5.0-beta.3.sql`

**Comment by proimage** [comment]
That's definitely an improvement, although is there any particular reason not to have separators between the time segments?

**Comment by brandonkelly** [comment]
I did some googleing and YYYY-MM-DD-HHMMSS is the closest thing I could find to a convention, so went with that. Plus the time part is generally less important than the date part.
