### ISSUE TITLE
[FR] Entry URI Format in structure: retrieve slug from other (single) section

### ISSUE THREAD

**Issue by mdominguez** [craftcms/cms#6233]
We've been wondering this for a while, if it would be possible to have a dynamic Entry URI Format in a structure, based on the slug of another section.
Set up is like this:
Section A (single) that functions as an overview.
Section B (structure) that contains the items, which needs to "inherit" the slug of section A as the parent page, followed by the slug of an item

Example => [screenshot](https://share.getcloudapp.com/d5uWpodY)

Bottomline is that we'd like to set {craft.entries.section('sectionA').one().slug}/{slug} as the Entry URI Format for a structure or channel (sectionB).

We don't want to work with parent/child pages in the same section B, because there is no default way to only allow 1 specific entry type within that section and only allow another specific entry type as a child of that entry type. (the [entry level types](https://plugins.craftcms.com/level-entry-types) plugin could address this issue but doesn't work well with the [child me](https://plugins.craftcms.com/child-me) plugin, so that's not an option either.

Thanks!

**Comment by brandonkelly** [comment]
Possible! You just can’t use the single brace (`{...}`) syntax, since that is just a shortcut for accessing properties of the entry whose URI is being generated. This will work though:

```twig
 {{ craft.entries().section('sectionA').one().slug }}/{slug}
```

**Comment by mdominguez** [comment]
Hi @brandonkelly,
We've tested it like that, but experience that in a multisite / multi-locale setup the appropriate slug doesn't respect the locale. For example, items in structure sectionB, when we check them in French, we see the English slug of sectionA instead of the French slug of sectionA

Hope this is a clear explanation!

**Comment by brandonkelly** [comment]
You can pass the entry’s site ID along like this:

```twig
 {{ craft.entries().section('sectionA').siteId(siteId).one().slug }}/{slug}
```
