### ISSUE TITLE
Default values for newly added table-field not showing for existing Element/Entry

### ISSUE THREAD

**Issue by Tim-Wils** [craftcms/cms#6236]
### Description
Default values for newly added table-field not showing for existing Element/Entry. 
New entries do have the default values.

### Steps to reproduce
1. Make sure you have a section and a entry that exists already.

2. Create a tablefield with some default values.
![image](https://user-images.githubusercontent.com/90032/85110964-f69f9e00-b213-11ea-8fad-46e6b23b6f56.png)

3. Add the field to that section.

4. Edit an existing entry in that section and you'll see that no default value is showing.
![image](https://user-images.githubusercontent.com/90032/85111228-56964480-b214-11ea-8522-ca479974643d.png)

* The default values do show up at a new entry:
![image](https://user-images.githubusercontent.com/90032/85111416-96f5c280-b214-11ea-8727-c39a685c13b8.png)

### Additional info
- Craft version: 3.4.24
- PHP version: 7.1.33
- Database driver & version: MySQL 5.7.30
- Plugin: cp field inspect

**Comment by brandonkelly** [comment]
This is expected behavior for now – see #2446.
