### ISSUE TITLE
Element index settings are not applied when running a migration via CLI

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#6237]
### Description

This is a minor one:

While waiting for #3658 we try to use a migration for setting the element index order/attributes

Calling `Craft::$app->elementIndexes->saveSettings('craft\\elements\\Asset', $assetSettings);`

where `$assetSettings` is something like

```
[
    'sources' => [
        'folder:c14310c0-e490-4bd5-8dee-4635b50a8efe' => [
            'tableAttributes' => [
                0 => 'filename'
                1 => 'imageSize'
                2 => 'dateModified'
                3 => 'link'
            ]
        ]
        'folder:4a13237a-b3f8-43b0-b0ef-6c4f8f710509' => [
            'tableAttributes' => [
                0 => 'provider'
                1 => 'filename'
                2 => 'dateModified'
                3 => 'link'
            ]
        ]
        'folder:bf547f52-5533-4685-9781-836a23045a90' => [
            'tableAttributes' => [
                0 => 'filename'
                1 => 'imageSize'
                2 => 'dateModified'
                3 => 'link'
            ]
        ]
        'folder:66b748b2-267b-4024-9b28-8b6ac87fae2c' => [
            'tableAttributes' => [
                0 => 'filename'
                1 => 'imageSize'
                2 => 'dateModified'
            ]
        ]
    ]
    'sourceOrder' => [
        0 => [
            0 => 'key'
            1 => 'folder:c14310c0-e490-4bd5-8dee-4635b50a8efe'
        ]
        1 => [
            0 => 'key'
            1 => 'folder:4a13237a-b3f8-43b0-b0ef-6c4f8f710509'
        ]
        2 => [
            0 => 'key'
            1 => 'folder:bf547f52-5533-4685-9781-836a23045a90'
        ]
        3 => [
            0 => 'key'
            1 => 'folder:66b748b2-267b-4024-9b28-8b6ac87fae2c'
        ]
    ]
]
```

This works perfectly if running the migration from the CP utilities, however running `.\craft migrate/up` does not apply the `sources` section, the table attributes are reset to their defaults.

Here is the logged SQL, showing that `sources` is an empty array:

```sqI
NSERT INTO `elementindexsettings` (`settings`, `dateCreated`, `dateUpdated`, `uid`, `type`) VALUES ('{\"sources\":[],\"sourceOrder\":[[\"key\",\"folder:c14310c0-e490-4bd5-8dee-4635b50a8efe\"],[\"key\",\"folder:4a13237a-b3f8-43b0-b0ef-6c4f8f710509\"],[\"key\",\"folder:bf547f52-5533-4685-9781-836a23045a90\"],[\"key\",\"folder:66b748b2-267b-4024-9b28-8b6ac87fae2c\"]]}', '2020-06-19 10:20:50', '2020-06-19 10:20:50', '313cfe8b-7519-4561-a020-d47ea49acb59', 'craft\\elements\\Asset') ON DUPLICATE KEY UPDATE `settings`='{\"sources\":[],\"sourceOrder\":[[\"key\",\"folder:c14310c0-e490-4bd5-8dee-4635b50a8efe\"],[\"key\",\"folder:4a13237a-b3f8-43b0-b0ef-6c4f8f710509\"],[\"key\",\"folder:bf547f52-5533-4685-9781-836a23045a90\"],[\"key\",\"folder:66b748b2-267b-4024-9b28-8b6ac87fae2c\"]]}', `dateCreated`='2020-06-19 10:20:50', `dateUpdated`='2020-06-19 10:20:50', `uid`='313cfe8b-7519-4561-a020-d47ea49acb59'
```

### Additional info

- Craft version: 3.5.x-dev
- PHP version: 7.2.14
- Database driver & version: MySQL 5.7.14
- Plugins & versions: Embedded Assets 2.2.6

/Aylin

**Comment by brandonkelly** [comment]
`ElementIndexes::saveSettings()` will filter out any sources that aren’t defined by the element type, so I’m guessing that’s what’s going on here. Maybe these volumes didn’t exist quite yet when `migrate/up` was run?

**Comment by wsydney76** [comment]
@brandonkelly  Thanks for the quick reply, but i'm afraid there's some evidence that this not the case here.

* Both CP Utilites/CLI migrations are run against the same database, with all volumes set up.

* The folder uids that are required by the settings array are set up dynamically via `Craft::$app->assets->getRootFolderByVolumeId($volume->id)`, 

* After running `migrate/up` all sources show up in the correct new order, just with the default table attributes.

/Aylin

**Comment by brandonkelly** [comment]
Have you confirmed the folder UIDs are actually correct? Those are probably different on each of your environments.

**Comment by wsydney76** [comment]
Quite sure as the folder UIDs are dynamically retrieved.

Fyi, the migration code is in [this gist](https://gist.github.com/wsydney76/d0bc989b15992bf7ff2afda49d056daa)

/Aylin

PS
Not a high priority as it works via CP/Utilities, we were just wondering why the same code in the same environtment did not work via CLI.

**Comment by brandonkelly** [comment]
There really shouldn’t be any difference; your same code will get run either way. So not sure where to go from here. I’ll close this, but feel free to update if you are able to look into it further and find the culprit.

**Comment by wsydney76** [comment]
@brandonkelly Thanks, yes, we could look a bit into it and it looks like it comes down to `Asset::defineSources` where

https://github.com/craftcms/cms/blob/fedc3699b531f496ed9123b723326665d3e9efb4/src/elements/Asset.php#L260

returns an empty array when run as console request (no user - no permissions - no volumes i guess)

No idea if this is the correct way to do it, but adding these lines before saving the new settings solved the problem for now:

```
$adminUser = User::find()->admin()->one();
Craft::$app->user->setIdentity($adminUser);
```

**Comment by brandonkelly** [comment]
Ahhh, got it. Thanks! Just fixed that for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.25 is out now with the fix for this.
