### ISSUE TITLE
Frontend entry form - name of variable containing submission data

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#6240]
When we submit frontend entry form with errors, variable is injected in template that contains our submission data and errors information. 

Problem is, this variable is called `entry`, which conflicts with the existing `entry` variable (the page that contains entry form might have has its own `entry`).

I know that changing variable name would be breaking change, so why now allow changing its name using config setting?

**Comment by timkelty** [comment]
@piotrpog I swear I made this FR a couple years ago, but now can't find it…so I'm glad you posted!

**Comment by brandonkelly** [comment]
As of Craft 3.5 it will be possible to specify the variable names that the asset/category/entry/user should be passed back to the template as if they contain validation errors, like so:

```
{# asset forms #}
{{ hiddenInput('assetVariable', 'badAsset'|hash) }}

{# category forms #}
{{ hiddenInput('categoryVariable', 'badCategory'|hash) }}

{# entry forms #}
{{ hiddenInput('entryVariable', 'badEntry'|hash) }}

{# user forms #}
{{ hiddenInput('userVariable', 'badUser'|hash) }}
```

Thanks to @timkelty for the PR!
