### ISSUE TITLE
GraphQL sidebar link doesn't work when allowAdminChanges is false

### ISSUE THREAD

**Issue by daltonrooney** [craftcms/cms#6242]
### Description

Craft 3.5 beta 3, I've set allowAdminChanges to false and the GraphQL link is still visible in the CP sidebar. When I click the link, I get the "Administrative changes are disallowed in this environment." message. 

I'm able to get to the GraphicQL Explorer by directly typing in the URI. 

My preference would be for that menu item to link directly to the Explorer if allowAdminChanges is false, otherwise it should just be hidden altogether, shouldn't it?

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.
