### ISSUE TITLE
Add "letterbox" image transform mode 

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#6245]
Letterbox is a transform mode used in imager/imager-x plugin. It adds an empty area to top and bottom or left and right area of an image in order to fit it into specific dimensions.

Personally, I find it extremely useful, especially for things like product listings where each image needs to have same dimensions and images should not be cropped.

**Comment by brandonkelly** [comment]
Hm, this seems like it would be better handled with CSS that adds a background color to the image container or something, rather than adding additional pointless image data. I’ll leave it open though.
