### ISSUE TITLE
[FR] Include slug to entry HUD edit window

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#6247]
### Description

One of the most popular features in Craft's CP is to add entries from a relationshop field. However if you use this in a multi lingual environment, you can switch to another language to translate the created entry, but you can't edit (clear) the slug in the HUD window. 

![image](https://user-images.githubusercontent.com/60010597/85276950-df1a1c80-b482-11ea-891f-90a0fc35e4fd.png)

So you have to take additional steps, go to the element index, find the entry, open it , edit the slug, save, disrupting the workflow.

So just adding the slug would avoid these additional steps.

/Mel

### Steps to reproduce

1. Set up a multilingual system
2. Add a relational field
3. Add a new entry via HUD, save => a slug is created for all sites
4. Reopen HUD, switch to another language, translate title, save => the slug from step 3 persists

### Additional info

- Craft version: 3.5.x-dev
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by wsydney76** [comment]
Pushing this one a bit.

**Comment by brandonkelly** [comment]
Related: #6647

**Comment by brandonkelly** [comment]
This is resolved for 3.7! See #8017.
