### ISSUE TITLE
Changing advanced settings for an "Entries" field doesn't trigger a project.yaml update after deploying

### ISSUE THREAD

**Issue by pablofernandezgh** [craftcms/cms#6248]
### Description
Changing advanced settings for an "Entries" field doesn't trigger a project.yaml update after deploying

### Steps to reproduce
- Go to an **existing** "Entries" field type
- Click on "advanced", change a setting there
- The changes are registered in the Project.yaml file, including the advanced settings
- Deploy the code
- The changes aren't picked up. The project.yaml update window doesn't appear

I haven't tried this with a newly created "Entries" field type, but this happens with an already existing one

Edit: the changes do apply after manually running  `./craft project-config/sync`

![image](https://user-images.githubusercontent.com/16841468/85291376-b7cf4980-b49a-11ea-9ce1-c250f2b752f4.png)

- Craft version: 3.4.23
- PHP version: 7.3
- Database driver & version: PostgreSQL 10.6

**Comment by brandonkelly** [comment]
Try running `./craft project-config sync --force`.

**Comment by pablofernandezgh** [comment]
@brandonkelly Yes, even running `./craft project-config/sync` does the job, but the idea would be to trigger a database update without the need to manually run the command

**Comment by brandonkelly** [comment]
Craft does check whether `project.yaml` looks to be modified on each request, and if so, the site will be temporarily offline until that command has been run (or `/actions/app/migrate` is requested). If that’s not happening for you, check to make sure your `project.yaml` file modification date is getting updated as expected, and make sure the `dateModified` key within it is changing.
