### ISSUE TITLE
Session conflicts between sites hosted on the same server

### ISSUE THREAD

**Issue by aNickzz** [craftcms/cms#6249]
### Description

Opening more than one craft site hosted on the same server prevents all sites from staying logged in.

### Steps to reproduce

1. Start your webserver with the webroot at `/foo`
2. Install two independent copies of craft one in each of `/foo/bar` and `/foo/baz`
3. Open one in a browser at example.com/bar/web/admin and log in
4. Open another tab at example.com/baz/web
5. Notice that you've been forcibly logged out of example.com/bar/web. Logging into either only lasts a few 10s of seconds, With more tabs open, this time is reduced.

### Additional info

- Craft version: 3.4.22.1 & 3.3.11
- PHP version: 7.1.33
- Database driver & version: MySQL 5.7.30
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
There are a few steps you need to take to ensure multiple Craft installations can run smoothly on the same domain. I just dumped those into a new knowledge base article: https://craftcms.com/knowledge-base/running-multiple-craft-installations-from-the-same-domain
