### ISSUE TITLE
Publishing a Draft - loosing its position in the structure 

### ISSUE THREAD

**Issue by Osze** [craftcms/cms#6250]
### Description
When publishing an entry after it has become a draft (auto saved) it looses it's position in the structure. It gets positioned last in the structure. 

### Steps to reproduce

1. Work with an entry (let it auto save as a draft) or save as a draft.
2. Publish
3. Go back to your structure and you will see the entry last in the structure list. 

### Additional info

- Craft version: 3.4.24
- PHP version: 7.3

**Comment by brandonkelly** [comment]
We just released Craft 3.4.25 with a fix for this (7af2a900dc0fa20725fb949ffda672040d2a97ae). Thanks for reporting!

**Comment by Osze** [comment]
Hi again Brandon, 

Thanks for the fix with saving from a draft. 

I've found that it is the same bug when saving from a older revision. 

1. Change to older revision. 
2. Revert entry to this revision. 
3. Save

The entry is now placed last in the structure.
