### ISSUE TITLE
[Graphql] Filter by ':notempty:'

### ISSUE THREAD

**Issue by stephanedemotte** [craftcms/cms#6254]
Hello,

I try to filter my result with the `:notempty:` queryArgument but i can't make it work.

<img width="1680" alt="Screen Shot 2020-06-23 at 12 29 13 PM" src="https://user-images.githubusercontent.com/2158130/85430746-8b750500-b54e-11ea-88d4-94c5c8d60d73.png">

As you can see,
The `empty` and `notempty` alias are emtpy.
In the `all` alias i've got an empty `artworkGallery`...
infos: `artworkGallery` is a channel structure. 

Thank you !

**Comment by brandonkelly** [comment]
What is the relation between your `artwork` and `artworkGallery` sections? Do you have an Entries field that relates them? If so, what is its handle, and which section is the field attached to?

**Comment by stephanedemotte** [comment]
<img width="446" alt="Screen Shot 2020-06-23 at 6 44 39 PM" src="https://user-images.githubusercontent.com/2158130/85473768-b593ea80-b581-11ea-87f0-1dba0fcda7e9.png">

**Comment by brandonkelly** [comment]
Sorry for the lack of response on this. Going to close due to inactivity, but let me know if you are still struggling with it and we can reopen.
