### ISSUE TITLE
Relations can't be removed from drafts

### ISSUE THREAD

**Issue by aelvan** [craftcms/cms#6258]
### Description

There seems to be a bug related to relations (entries, assets, categories and matrix blocks tested) stored on drafts. If a relation is added to an empty relations field (for instance an entries field), a draft is saved, and then the relation is removed, leaving the field empty - the relation is still there if you save the element or preview the entry with live preview. 

Note that this only happens if a relations og matrix field is empty when you start editing. If it already has a relation, everything works as expected.

### Steps to reproduce

1. Create a new entry of an entry type that has an entries field.
2. Set a title, and select an entry in the entries field.
3. Wait for the green checkmark to indicate that a draft has been saved.
4. Remove the entry from the entries field.
5. Wait for the green checkmark to indicate that a draft has been saved.
6. Save the entry.
7. Observe that the entry is still selected in the entries field.

This can also be observed more visibly (and more critically for clients) when using the live preview, as things that are added can't be removed without saving and then removing.

### Additional info

- Craft version: 3.4.25 / 3.4.24 / 3.4.23
- PHP version: 7.3.14 / 7.4.7
- Database driver & version: MySQL 5.6.47 / MariaDB 10.3
- Plugins & versions: –

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.26 is out now with this fix.
