### ISSUE TITLE
Unable to set field as required in field layouts on latest 3.5

### ISSUE THREAD

**Issue by samhibberd** [craftcms/cms#6260]
Set a new field as required in an entry section settings and save.

Appears to save ok but the field is not set as required and there are no changes to the project config yaml file. 

The opposite 'Make not required' works as expected.

On Craft3.5 @ 28b01f8af519fabd6b2178d2e52aff448c5e76d1

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed now.
