### ISSUE TITLE
Nullable error with required GQL fields on global sets (possibly singles too?)

### ISSUE THREAD

**Issue by FreekVR** [craftcms/cms#6261]
### Description
When creating one-off entities like singles or global sets, this will insert a record in the Craft database with the respective fields for that entity all set to NULL as they have not (yet) been filled.

However, in a recent 3.5-commit, GQL types for required fields will always be non-nullable (eg. `String!` instead of `String`). This creates a bit of an issue for these types of entity, as the field may be required in the Craft CMS form itself, but in the database, can still be `NULL` as long as nobody bothers to fill in the global set / single fields

(I've actually only tested this on global sets, but I'd assume the same issue applies to singles as they share many of the same concepts)

As for a solution, either when creating a single / global set, it should be required to fill in the required fields before even creating that single / set (but this may be a bit of a rabbit hole with project-config syncing across environments) OR, for these types of entity, the GQL types should always be nullable.

### Steps to reproduce

1. Create a new global set with one or more required fields
2. Create a query in a frontend app to query this global sets' fields
3. You'll get an error about `null` values being returned by the API for non-nullable fields

### Additional info

- Craft version: 3.5-beta3
- PHP version: 7.2
- Database driver & version: Mysql 5.7
- Plugins & versions: n/a

**Comment by andris-sevcenko** [comment]
Related: #6139

**Comment by andris-sevcenko** [comment]
This has been fixed for the next 3.5 release.
