### ISSUE TITLE
Front-end asset uploading replaces rather than appends assets

### ISSUE THREAD

**Issue by codyjames** [craftcms/cms#6264]
In lines 496 and 497, the code uses `$query->id` rather than `$query->ids()`. This forces assets to be replaced rather than simply appending the new ones. I think this is accidental though I may be missing something.

https://github.com/craftcms/cms/blob/874dba4572f5ec81f9fad0570b889a0b2b0927be/src/fields/Assets.php#L496

Current:
```
                // Add the newly uploaded IDs to the mix.
                if (\is_array($query->id)) {
                    $query = $this->normalizeValue(array_merge($query->id, $assetIds), $element);
                } else {
                    $query = $this->normalizeValue($assetIds, $element);
                }
```

Fix:
```
                // Add the newly uploaded IDs to the mix.
                if (\is_array($query->ids())) {
                    $query = $this->normalizeValue(array_merge($query->ids(), $assetIds), $element);
                } else {
                    $query = $this->normalizeValue($assetIds, $element);
                }
```

**Comment by codyjames** [comment]
Also, is there a way to get this asset afterElementSave event to set the Uploader Id on the asset?

**Comment by brandonkelly** [comment]
Logic looks right to me. The intention is to work with the raw `id` param value there, not query for the related IDs, so that we can merge it with the uploaded assets’ IDs.

Are you seeing unexpected behavior?

**Comment by codyjames** [comment]
As-is it just replaces the assets I already have uploaded with new assets. Changing it to `-ids()` appends the new assets and keeps the ones previously uploaded, which is what I was hoping it would do.

**Comment by codyjames** [comment]
For me, `$query->id` seems to always be `null`.

**Comment by codyjames** [comment]
Let me know if this is working as-intended. If so, I can easily use what you have here as a jumping off point and it'll get me most of the way there.

**Comment by brandonkelly** [comment]
If `$query->id` is `null`, then you must not be including any IDs in the POST data.

Whenever you set a new value on your relation field – whether that’s via the POST data or by uploading a new file(s) to it – that will completely replace the existing value. So if you want to preserve the currently selected assets in addition to uploading a new file, you will need to include hidden inputs that define the currently selected asset IDs in your form, in addition to the file input.

**Comment by codyjames** [comment]
@brandonkelly Thanks so much for the info here. I got it to work as intended. Can't believe how easy y'all have made this. The fact that it works with my custom controller with almost not code for the asset stuff is amazing.
