### ISSUE TITLE
[3.5] FR: Bring back the ability to clear template caches without wiping the entire data cache

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#6279]
### Description

Craft 3.5 removes the "Template caches" option from the Clear Caches utility tool and the `clear-caches` console command – due to template caches now being stored in the data cache instead of the database.

I feel that retaining the ability to clear template caches somehow, without wiping the entire data cache, is valuable enough to explore. The data cache can potentially contain a lot of stuff, and it seems a bit heavy handed to have to nuke the entire thing just to clear the template caches (having `./craft clear-caches/template-caches` as part of a deploy script is probably not uncommon).

I haven't dug too deep into the new caching system yet, so I'm not sure how this feature could feasibly be re-introduced, but perhaps one option is to simply have Craft tag all caches created by the `{% cache %}` Twig tag with a special `"template"` tag or something? And then have the `clear-caches/template-caches` delete all caches with that tag, instead of the entire data cache.

### Steps to reproduce

1.
2.

### Additional info

- Craft version: 3.5-beta2
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Will have to think about the best way to do this UI-wise, but it’s not technically difficult – there’s already a PHP function for it.

```php
Craft::$app->elements->invalidateAllCaches();
```

**Comment by mmikkel** [comment]
In terms of UI, my immediate suggestion would be to simply restore the `clear-caches/template-caches` command and "Template caches" option in the Clear Caches utility as they exist pre-3.5 :) I get that this would be a bit awkward though, since template caches is just a part of the general data cache now (clearing out the data cache proper would also clear the template caches, etc). Perhaps it'd be possible to introduce some granularity to the clear cache utility and console command, where it was possible to clear only caches of a particular type (nested checkboxes, console command parameters)?

Concerning `Craft::$app->elements->invalidateAllCaches();` I also feel it's worth considering that template caches might not involve elements at all, so that method isn't really a reliable way to clear all template caches. For example, a custom routed template might wrap `{% cache %}` around an external API call, or something like that.

To be clear this certainly isn't the biggest thing in the world, I just feel like we lost a little bit of flexibility in this area, and if there was a good way to somehow introduce some granularity to clearing out data caches (that would restore the ability to specifically clear template caches only) that'd be great.

**Comment by brandonkelly** [comment]
The other sortof awkward thing is that you can’t _clear_ template/element caches; only invalidate them. Same end result (the cache will no longer be used) but technically different ways of getting there. Maybe I’me only one who would care about it being semantically incorrect though.

> Concerning `Craft::$app->elements->invalidateAllCaches();` I also feel it's worth considering that template caches might not involve elements at all,

All template caches will have an `element` tag dependency, regardless of whether elements were actually involved in the cache.

**Comment by mmikkel** [comment]
> All template caches will have an `element` tag dependency, regardless of whether elements were actually involved in the cache.

Hm, that doesn't seem to be the case. I did a test with a custom route and the resulting data cache's `TagDependency` contains a an empty `tags` array. The cache is also not invalidated if I call `Craft::$app->elements->invalidateAllCaches();`.

Unless I'm missing something, It looks like the `'element'` tag is only added if there's actually a matched element for the current route? https://github.com/craftcms/cms/blob/3.5/src/services/Elements.php#L341

> Maybe I’me only one who would care about it being semantically incorrect though.

No, I agree that it'd be awkward. Didn't really consider the difference between clearing and invalidating.

**Comment by brandonkelly** [comment]
> Hm, that doesn't seem to be the case. I did a test with a custom route and the resulting data cache's `TagDependency` contains an empty `tags` array. The cache is also not invalidated if I call `Craft::$app->elements->invalidateAllCaches();`.

Yeah you’re right, sorry about that. Going forward, all template caches will have a `template` tag, regardless of whether any elements were involved.

I’ve also added a new “Invalidate Data Caches” section to the Caches utility, which lists GraphQL and Template options:

![The new Caches utility options](https://user-images.githubusercontent.com/47792/88978898-6b371500-d275-11ea-86d9-4e29f28ca365.png)

And finally, there’s a new `invalidate-tags` CLI command, with `/all`, `/graphql`, and `/template` options.

Additional tag options can be registered via a new `craft\utilities\ClearCaches::EVENT_REGISTER_TAG_OPTIONS` event.

**Comment by brandonkelly** [comment]
Annnd just released Craft 3.5 RC5 with those changes.

**Comment by mmikkel** [comment]
That's a great solution, @brandonkelly - thanks a lot!

**Comment by khalwat** [comment]
Gonna leave my end of the discussion we had about this here...

Probably the most correct way to do it would be to have it work the way some other UI's in Craft work where the sub-options are hierarchically listed under the "Data caches" item, with All checked by default, and if you uncheck it, then you can individually check what you want to clear

@Mosnar had:
```
Clear caches [ ] All
- [ ] Asset cache
- [ ] Asset indexing data
- [ ] etc
- [ ] Data Caches
- - [ ] Template Caches
- - [ ] GraphQL Caches
```

Not too many Craft developers are using `TagDependency` in their plugins/modules (tho they are awesome) so I think the understanding of the difference between "Clearing" caches and "Invalidating" tag dependencies will be lost on most.

Not to mention that a huge majority of Craft developers never touch PHP/Yii2 at all

It's what SEOmatic, Retour, and a bunch of other plugins I've written use. So I guess I'll move the options out to this "Invalidating" UI

It's a minor thing; just saying, I think the way it is now is likely confusing to most people

My money is on people checking everything, and clicking on both buttons "Just to be sure" :)

**Comment by mmikkel** [comment]
@khalwat The nested checkboxes thing was how I initially pictured this solved, too - and I agree that on surface level, it would be simpler/more elegant than the current implementation. 

At the same time, I actually tend to agree with Brandon that mixing these concepts (clearing and invalidating) is a bit awkward/weird (even if I'm undecided if it'd be _more_ awkward than having the two different sections in the Clear Caches utility 🤷‍♂️  – I'm mostly just happy that the ability to nuke template caches, without deleting the entire data cache, has been reintroduced).

Maybe a compromise would be to merge the two different sections, using nested checkboxes like @khalwat suggests, but have each checkbox actually spell out their action? I.e. something like this:

```
Caches
- [ ] Clear all caches
- [ ] Clear Asset cache
- [ ] Clear Asset indexing data
- [ ] Clear ...
- [ ] Clear Data Caches
- - [ ] Invalidate Template Caches
- - [ ] Invalidate GraphQL Caches
```

**Comment by brandonkelly** [comment]
Another awkward thing about nesting Template/GraphQL caches under Data Caches is, it gives the impression that those ore the _only_ two things that Data Caches consists of, which isn’t true.

**Comment by khalwat** [comment]
Yeah I think it's not a big thing, but I do think that most people will be confused about the difference between Clear and Invalidate. And will be confused as to why they are separate.

There's really no practical difference to people between Clear & Invalidate either... that I can think of anyway, except for the additional fine-grain control.

But I think if you mixed them all in together, people would clear the Data Caches & some other cache that already uses the data cache as well, because they aren't aware of the relationship between the two.

Everything else is a peer relationship, this is a parent/child relationship.

**Comment by brandonkelly** [comment]
Well, we’ll release as-is and then see how it goes. I suspect most people will just scan and tick “Template caches”, and submit the form, without giving it much thought.
