### ISSUE TITLE
Image Transform alters image quality(imagick driver)

### ISSUE THREAD

**Issue by NikosDevPhp** [craftcms/cms#6282]
### Description
We have an issue with image transforms with imagick(also tried gd and gmagick).
![default](https://user-images.githubusercontent.com/52325060/86011276-283f1300-ba25-11ea-9f53-aeb459c35476.png)
and transformed is like that:
![default  transformed](https://user-images.githubusercontent.com/52325060/86011347-3db43d00-ba25-11ea-9a9e-831a3776be4a.png)

As you can see there is a difference (we have possibly narrowed it to very bright images, but can't be very sure)
The craft settings are crop, image quality Maximum, no interlacing and no transform to other picture format is done(png is saved as png) 

Probably, (from debugging) this could be an issue with ImageMagick as no other transformation of any kind seems to be happening, just instantiating an Imagick Object and then saving it.

It could be great if we had a setting to JUST crop and resize image with no changes in color profile, no transformation whatsoever etc.

### Steps to reproduce

1. Upload the specific picture
2. Set an Image transform 830x508
3. Observe difference (lady's forehead quality is reduced, darkened image overall and generally a little bit blurrier)

### Additional info

- Craft version: 3.4.23
- PHP version: 7.3.11
- Database driver & version: mysql 5.7
- Plugins & versions: no relevant
- ImageMagick Version: ImageMagick 6.9.8-3 Q16
- PHP Imagick version: 3.4.3
- Craft config:
        'defaultImageQuality' => 100,
        'optimizeImageFilesize' => false,
        'transformGifs' => false,
        'imageDriver' => 'imagick',
        'preserveCmykColorspace' => true,
        'preserveExifData' => true,

**Comment by brandonkelly** [comment]
> It could be great if we had a setting to JUST crop and resize image with no changes in color profile, no transformation whatsoever etc.

Unfortunately it’s just not as simple as that. The only way to crop/resize an image is to go through the standard image saving process, which is where the loss occurs.

You could try swapping transform generation over to the [Imager X](https://plugins.craftcms.com/imager-x) plugin combined with [imgix](https://www.imgix.com/), which you may have better luck with.
