### ISSUE TITLE
No CSRF token returned when auto login after register.

### ISSUE THREAD

**Issue by pieter-janDB** [craftcms/cms#6283]
### Description
I am trying to make a vue application with a craft backend. Users will be able to do public registration without verifying the email. So when you POST (axios) to the save user endpoint It creates the account and then returns the success and the ID .

Is it possible to also add CSRF token inside the return here.

It is allready added for the login/logout requests but I feel like this possible login is forgotten.
https://github.com/craftcms/cms/issues/3858

### Steps to reproduce

config: 'autoLoginAfterAccountActivation' => true,
Turn on public registration
Create a user over a POST request without refresh.

Wanted behaviour:
When user is created/logged in also include the CSRF token in return

### Additional info

- Craft version: 3.4.24
- PHP version: 7.2
- Database driver & version: mysql

**Comment by brandonkelly** [comment]
Just resolved this so `users/save-user` responses will start including `csrfTokenValue` keys for Ajax requests, if a user was logged in during the request.

**Comment by brandonkelly** [comment]
Craft 3.4.26 is out now with that change.

**Comment by pieter-janDB** [comment]
@brandonkelly I just had another use-case where I submit a user password update to `/users/save-user` this returns success and the ID of the user. But the csrf token also changes because of the password update.
Is it possible to include the new csrf token in this request aswel?
Thanks!

**Comment by brandonkelly** [comment]
@pieter-janDB Good point, just made that change for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.12 is out now with that change ✨
