### ISSUE TITLE
(3.5 Beta 3) Share link doesn't include parent.uri after publishing draft

### ISSUE THREAD

**Issue by daltonrooney** [craftcms/cms#6284]
### Description

I have a structure with URI format set up like `{parent.uri ?? ''}/{slug}`

When I publish a saved draft and click the Share link to the primary entry, the link that is opened does not include the parent URI and returns 404. This doesn't seem to happen when I edit an entry and hit CMD + S to save and continue editing. If I just hit save and get redirected to the entries list, the web link from there works fine as well.

### Steps to reproduce

1. Make a change to a child entry in a structure and Save as draft
2. Publish changes
3. Share -> Primary entry page
4. New tab opens to 404.

### Additional info

- Craft version: 3.5 Beta 3
- PHP version: 7.4.x

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you try changing your `craftcms/cms` requirement in composer.json to `3.5.x-dev` and then run `composer update`, then see if you’re still having the issue? If so, please send a database backup plus your composer.json & composer.lock files over to support@craftcms.com, with specific steps to reproduce, and we’ll look into it from there.
