### ISSUE TITLE
Craft mailer injects unwanted resources and javascript into template

### ISSUE THREAD

**Issue by RickKukiela** [craftcms/cms#6285]
[CP-Twig-Template-Partial.txt](https://github.com/craftcms/cms/files/4847289/CP-Twig-Template-Partial.txt)
[CP-email-example.txt](https://github.com/craftcms/cms/files/4847290/CP-email-example.txt)

### Description
I have custom site business logic code in a module. There are routes that result in an email being composed and sent from public routes and CP routes.

The same code and almost identical email template does not exhibit this behavior when executed from the public route, the issue only appears to happen when the controller code is executed from the CP route.

See attached samples for what is being injected into the email and where, and a sample of the template file that resulted in this insertion.

Here is the code I'm using to generate the email message and send it:

```
// get html
Craft::$app->getView()->setTemplateMode('site');
$html = Craft::$app->controller->renderTemplate('qr-delivery-email.twig', [
	'distName' => $_POST['distName'],
	'message' => $_POST['message'],
	'qr' => $qr
]);

// generate message
$message = Craft::$app
	->getMailer()
	->compose()
	->setFrom(['no-reply@domain.com' => "Widget Quote System"])
	->setTo($to)
	->setSubject("Widget Quote Request")
	->setHtmlBody($html->data);
if (is_array($cc)) {
	$message->setCc($cc);
}
if (is_array($bcc)) {
	$message->setBcc($bcc);
}

$message->send();
```

### Steps to reproduce

1. Create a CP route that executes code similar to above.
2. Ensure the rendered twig template has a full html / head / body structure.
3. Execute controller code via CP route and see if delivered message source includes unwanted code snippets

### Additional info

- Craft version: 3.4.25
- PHP version: 7.1
- Database driver & version: mysql (10.1.45-MariaDB)
- Plugins & versions:

**Comment by brandonkelly** [comment]
You should be using `Craft::$app->view->renderTemplate()` instead of `Craft::$app->controller->renderTemplate()`.

Change your code to:

```php
// get html
$html = Craft::$app->view->renderTemplate('qr-delivery-email.twig', [
	'distName' => $_POST['distName'],
	'message' => $_POST['message'],
	'qr' => $qr
], \craft\web\View::TEMPLATE_MODE_SITE);

// generate message
$message = Craft::$app
	->getMailer()
	->compose()
	->setFrom(['no-reply@domain.com' => "Widget Quote System"])
	->setTo($to)
	->setSubject("Widget Quote Request")
	->setHtmlBody($html);
if (is_array($cc)) {
	$message->setCc($cc);
}
if (is_array($bcc)) {
	$message->setBcc($bcc);
}

$message->send();
```

(Note that `$html` is just a string of HTML code now, not a `craft\web\Response` object, so we pass `$html` directly into `setHtmlBody()` now, rather than `$html->body`.)
