### ISSUE TITLE
Unable to revoke all user permissions, at least one must be set

### ISSUE THREAD

**Issue by johndwells** [craftcms/cms#6292]
### Steps to reproduce

1. Go to edit user, tick one or more permissions (group or quantity does not matter)
2. Click "Save and continue editing"
3. Un-tick all permissions set in step 1
4. Click "Save and continue editing"
5. All checkboxes from step 1 are still ticked.

If instead on step 3 you un-ticked all permissions _except for one_, then things are saved correctly. But it seems the case that as soon as *all* checkboxes are un-ticked, then no changes are saved.

From my tests, this issue does not apply when creating user groups.

### Additional info

- Craft version: 3.4.25
- PHP version: 7.4.6
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting! Just released Craft 3.4.26 with a fix for this.
