### ISSUE TITLE
Validating required fields(redactor, matrix) in the carftcms but through custom elements

### ISSUE THREAD

**Issue by chandamotiyani** [craftcms/cms#6293]
I have custom module created in the craftcms project named as Events, and it has some required fields but some custom fields as well, because of which while saving rather than craft's default functionality for saving the data, I'm calling my own function to save the data as per the custom requirement.

But the fields which are marked as required in the layout of the craft those are not getting validated because I'm saving it with custom function instead of using the craft's own function so for that reason, I'm not able to find solution where I can validate the fields ### (redactor, matrix fields, plain texts) which are marked as mandatory in the craft layout.

I hope there must be solution where can we put the validation in the custom function for the required fields which are set in the layout design.

Following is the code of the custom function where the event is being saved:

```php
public function actionEdit($id = null)
{
    $this->getView()->registerAssetBundle(EventsEditAssetBundle::class);
    if (!$id) {
        $id = Craft::$app->request->getParam('id');
    }
    $variables = [];
    $variables['event'] = Event::find()->anyStatus()->where(['yalumba_events.id' => $id])->one();
    $variables['tabs'] = $this->_getTabs($variables['event']);
    $apiField = new RezdyId([
        'name' => 'apiId',
        'id' => 'apiId-dropdown'
    ]);
    $variables['continueEditingUrl'] = 'events/{id}/edit';
    $variables['shareUrl'] = $variables['event']->getUrl();
    $variables['showPreviewBtn'] = false;
    $variables['rezdyField'] = $apiField;

    if (Craft::$app->request->isPost) {

        if ($variables['event']) {
            $failCount = 0;

            $variables = $this->updateFields($variables);

            if (Craft::$app->elements->saveElement($variables['event'], true)) {
                Craft::$app->session->setNotice("Event has been updated");
                //$this->redirect(UrlHelper::cpUrl('events'));
                return $this->redirectToPostedUrl($variables['event']);
            } else {
                Craft::$app->session->setError("The event cannot be updated");
                return $this->renderTemplate('events/edit', $variables);
            }
        } else {
            throw new Exception('Event not found.');
        }
    } else if (Craft::$app->request->isGet) {
        if (@$variables['event']) {
            return $this->renderTemplate('events/edit', $variables);
        } else {
            throw new Exception('Event not found.');
        }
    }
}
```

### Additional info

- Craft version: 3.4.20
- PHP version: 7.3
- Database driver & version: MySQL
- Plugins & versions:

**Comment by brandonkelly** [comment]
Required custom fields are only enforced when the element is saved using the `live` validation scenario. Add this line before calling `saveElement()`:

```php
$variables['event']->setScenario(\craft\base\Element::SCENARIO_LIVE);
```

**Comment by chandamotiyani** [comment]
Thanks a ton @brandonkelly cannot describe it, but I was like trying to fix it badly, but wasn't able to find the solution, could you please suggest where can we find documentation for such backend custom things.

**Comment by brandonkelly** [comment]
I’m not sure if that particular behavior is documented, besides Yii’s documentation on [scenarios](https://www.yiiframework.com/doc/guide/2.0/en/structure-models#scenarios) (cc @mattstein).

In order to make your custom attributes searchable, you will need to hook into the [EVENT_REGISTER_SEARCHABLE_ATTRIBUTES](https://docs.craftcms.com/api/v3/craft-base-element.html#event-register-searchable-attributes) event.

```php
use craft\base\Element;
use craft\commerce\elements\Order;
use craft\events\RegisterElementSearchableAttributesEvent;
use yii\base\Event;

Event::on(
    Order::class,
    Element::EVENT_REGISTER_SEARCHABLE_ATTRIBUTES,
    function(RegisterElementSearchableAttributesEvent $event) {
        $event->attributes[] = 'myCustomAttribute';
        // ...
    }
);
```

**Comment by chandamotiyani** [comment]
I really appreciate your response @brandonkelly it worked well for the orders module but for Users Module which is an #inbuilt craft module how to enable search for the custom columns or the columns which are in relation to them from other tables. For example in the screenshot below Yalumba Customer Id and Vend Customer Id

<img width="1252" alt="Screen Shot 2020-07-06 at 2 22 32 pm" src="https://user-images.githubusercontent.com/16190427/86557076-3dbbbc00-bf94-11ea-8295-52dc2e73a9eb.png">

**Comment by brandonkelly** [comment]
@chandamotiyani same idea, just make sure you are attaching the event to the right classes.

**Comment by chandamotiyani** [comment]
@brandonkelly but I'm not finding the class for Users module that is the reason I have asked you again because users module is inbuilt craft module how to hook event into it?

**Comment by brandonkelly** [comment]
User elements are provided by the `craft\elements\User` class.

**Comment by chandamotiyani** [comment]
But that's under vendor which I can't edit.

**Comment by andris-sevcenko** [comment]
@chandamotiyani you would use a practically identical code snippet, just switch out the class you are listening on.

```php
use craft\base\Element;
use craft\elements\User;
use craft\events\RegisterElementSearchableAttributesEvent;
use yii\base\Event;

Event::on(
    User::class,
    Element::EVENT_REGISTER_SEARCHABLE_ATTRIBUTES,
    function(RegisterElementSearchableAttributesEvent $event) {
        $event->attributes[] = 'myCustomAttribute';
        // ...
    }
);
```

**Comment by chandamotiyani** [comment]
But my question is where to place this code snippet in which file that it gets hooked into the users listing in CP?

@andris-sevcenko and @brandonkelly 

I tried to put this code snippet in the orders module by changing the class it listening on but it is not working

**Comment by chandamotiyani** [comment]
In which file do I need to place this code please suggest me properly because putting it in another file like orders module isn't working and I cannot put this in the Users module because it's in the Vendor 


use craft\base\Element;
use craft\elements\User;
use craft\events\RegisterElementSearchableAttributesEvent;
use yii\base\Event;

Event::on(
    User::class,
    Element::EVENT_REGISTER_SEARCHABLE_ATTRIBUTES,
    function(RegisterElementSearchableAttributesEvent $event) {
        $event->attributes[] = 'myCustomAttribute';
        // ...
    }
);

Please suggest something @brandonkelly, I'm stuck, thanks.

**Comment by andris-sevcenko** [comment]
You would put that in your custom module's init function.

**Comment by chandamotiyani** [comment]
But doing that isn't affecting, when I'm searching custom attributes in users listing then I'm seeing no results, hence it isn't working.

**Comment by brandonkelly** [comment]
You would need to resave your users for the change to take effect. Run this command:

```sh
./craft resave/users --update-search-index
```

**Comment by chandamotiyani** [comment]
Here you go @brandonkelly 
Cannot thank you enough :clap: :pray: :bow: :smile: :palms_up_together:
