### ISSUE TITLE
GraphQL: Empty result when using Fragment

### ISSUE THREAD

**Issue by holmey** [craftcms/cms#6294]
### Description
When using a FragmentSpreadNode the result for this specific node will be empty sometimes. 

When using a simple Query like this:

```gql
query getArticle($uri: [String], $site: [String]) {
  entry(uri: $uri, site: $site) {
    ...on stories_stories_Entry {
      embeds {
        ...Image
      }
    }
  }
}

fragment Image on embeds_image_BlockType {
  image {
    id
  }
}
```
As a result i will get:
```json
{
  "data": {
    "entry": {
      "embeds": [
        {
          "image": []
        },
        {},
        {},
        {
          "image": []
        }
      ]
    }
  }
}
```

I was expecting to receive a result like this:

```json
{
  "data": {
    "entry": {
      "embeds": [
        {
          "image": [
            {
              "id": "110071"
            }
          ]
        },
        {},
        {},
        {
          "image": [
            {
              "id": "80440"
            }
          ]
        }
      ]
    }
  }
}
```

While debugging i think i tracked this issue down to the `extractEagerLoadCondition` function in [Resolver.php](https://github.com/craftcms/cms/blob/develop/src/gql/base/Resolver.php). 
The context is not always valid when using a FragmentSpreadNode and calling `traverseNodes`.
This [line](https://github.com/craftcms/cms/blob/3.4.25/src/gql/base/Resolver.php#L130) of code resolves an `eagerLoadableFieldsByContext` from the global Fields array but it should resolve the `image` in a specific MatrixBlock since `embeds` is a MatrixBlock in my case.

Maybe this is part of the Problem because when using the same query without Fragment i will receive the expected response and also the eager-loadable field from the MatrixBlock will get resolved.

```gql
query getArticle($uri: [String], $site: [String]) {
  entry(uri: $uri, site: $site) {
    ...on stories_stories_Entry {
      embeds {
        ...on embeds_image_BlockType {
          image {
            id
          }
        }
      }
    }
  }
}
```
Also when renaming the handle of the global eager-loadable field in the settings the query will work as expected.

So i figured the issue appears when having a global Field with the same handle as the field handle in a MatrixBlock (Name `image` in MatrixBlock `embeds_image_BlockType`in my case) and then using a Fragment to get the contents.

### Steps to reproduce

1. Add an eager-loadable field with the handle `image` in the settings menu. In my case this was an Asset.
2. Add a Matrix with a MatrixBlock containing a field with the handle `image`. (Handle of the block type does not seem to be relevant).
3. Connect this Matrix to an entry.
4. Try to get the contents from the field by using a fragment
```gql
query getArticle($uri: [String], $site: [String]) {
  entry(uri: $uri, site: $site) {
    ...on stories_stories_Entry {
      embeds {
        ...Image
      }
    }
  }
}

fragment Image on embeds_image_BlockType {
  image {
    id
  }
}
```

### Additional info

- Craft version: Craft Pro 3.4.25
- PHP version: 7.4.6
- Database driver & version: MySQL 5.5.5

**Comment by andris-sevcenko** [comment]
That's incredibly thorough investigative work!

Unfortunately - I'm unable to reproduce this locally on Craft 3.4.25.

Any chance you could zip up a database dump + your composer.lock and composer.json files, and send them over to support@craftcms.com while referencing this issue?

**Comment by holmey** [comment]
The fastest way to reproduce this for me was to just use the "Happy Lager" Demo and using this query.

```gql
{
  entry(id: 126) {
    title
    ...on services_services_Entry {
      serviceBody {
        ...Image
      }
    }
  }
}

fragment Image on serviceBody_servicesPoint_BlockType {
  image {
    id
  }
}
```

When you try this on a fresh setup it will work. I just had to rename the handle from a global eager-loadable field to the same name as the MatrixBlock image field handle in `serviceBody`. I renamed the "Featured Image" Asset handle to `image`.
After this change the query will not return the image children anymore. 
Also when querying without fragment the result is correct as expected.
If you rename a not eager-loadable field like e.g. a text field this issue is not reproducible.

So i think it is not a problem with my specific setup/configuration but if it is helpful i could prepare a dump and send it to you.

**Comment by andris-sevcenko** [comment]
@holmey it would be more helpful, as I can't run the process through xdebug on a demo site :)

**Comment by holmey** [comment]
Could you use this setup? https://github.com/craftcms/demo
Thats the setup i used to reproduce the issue.
The SQL file is included https://github.com/craftcms/demo/blob/master/happylager.sql
You just have to rename one Asset field handle in the settings after the setup.

**Comment by andris-sevcenko** [comment]
Ah, my bad, I glanced over your message and I assumed that you used a demo site. I do apologize. And I realize that it makes me a silly person :)

I'll do that and get back to you!

**Comment by andris-sevcenko** [comment]
@holmey that was a tricky one, indeed.

I had never encountered this because it never occurred to me to write a fragment that went a level deeper and I never realized that was valid GraphQL. So, where you had
```graphql
fragment Image on serviceBody_servicesPoint_BlockType {
  image {
    id
  }
}
```
I would have written
```graphql
fragment Image on serviceBody_MatrixField {
  ...on serviceBody_servicesPoint_BlockType {
    image {
      id
    }
  }
}
```

Another reason why this would not trigger an error in most circumstances is the global field conflict. If there was not a field with the same handle in the global context, Craft would just discard that fragment from eager-loading and, in turn, just running a new element query when hitting that fragment on execution. This would result in a performance hit, but it would still work.

Anyway, thanks for your patience and investigative work. I added a fix to address this that correctly resolves field contexts with all fragment types.

**Comment by brandonkelly** [comment]
Craft 3.4.27 is out now with the fix for this.
