### ISSUE TITLE
ConfigHelper::localizedValue() - allow "or" statement

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#6303]
Right now in order to define settings per-site using `ConfigHelper::localizedValue()`, we can do something like that:

```
return [
    '*' => [
        'googleApiKey' => [
            'default' => 'foo',
            'site2' => 'bar',
            'site3' => 'bar',
        ]
    ]
];
```

I propose that we could use `||` to introduce "or" logic.

```
return [
    '*' => [
        'googleApiKey' => [
            'default' => 'foo',
            'site2 || site3' => 'bar',
        ]
    ]
];
```
`||` cannot be part of the site handle, so I don't see a problem there. Adding space before and after `||` would make statement more readable. Internally, string with site handles could be just stripped from all whitespace.

Reason? Although in this example, we didn't saved much typing, sometimes plugin settings can contain long multilevel arrays. If we wanted to have one settings for one group of sites and other for other group, we would need to duplicate these settings multiple times (or introduce our own logic for per-site settings instead using `ConfigHelper::localizedValue()`).

**Comment by brandonkelly** [comment]
This would have a negative performance impact since we’d have to start parsing each of the array keys, so don’t think it’s a good idea.

You could define the value before the `return` statement, and reference it multiple times in the returned array.

```php
$bar = 'bar';

return [
    '*' => [
        'googleApiKey' => [
            'default' => 'foo',
            'site2' => $bar,
            'site3' => $bar,
        ]
    ]
];
```

**Comment by piotrpog** [comment]
@brandonkelly 
goog idea - why didn't i thought it earlier? :)
