### ISSUE TITLE
/path/to/folder causes confusion

### ISSUE THREAD

**Issue by nordentwickler** [craftcms/cms#6304]
### Description

I have been working with Craft CMS for 4 years now and i got confused every time i add a new asset volume. The placeholder text is "/path/to/folder", which assumes to use an absolute path at this input field. In fact, in most "normal" installations, it is just a relative path to your public/web folder. If you could change the hint above the field or the placeholder itself, so it is clearly understandable for users, who don't use aliases for this configuration and just want to add a folder for the assets, this would be great!

The placeholder for the base URL is totally fine and easy to understand, but "/path/to/folder" causes confusion, i think.

What do you think, let us discuss this!

**Comment by brandonkelly** [comment]
It actually _should_ be an absolute path, or an environment variable/alias that references an absolute path. Using a relative path can lead to issues. See #6088 for a similar discussion, and my thoughts on it.
