### ISSUE TITLE
GraphQL to support federation

### ISSUE THREAD

**Issue by jaspertandy** [craftcms/cms#6307]
I was torn on whether to post this as a bug, but since the GraphQL implementation doesn't claim to support federation, it's not.

However, it would make Craft's GraphQL implementation so useful to support the [federation spec](https://www.apollographql.com/docs/apollo-server/federation/federation-spec/). Is this on the roadmap at all? I have a project coming up that would hugely benefit from it if it's at all possible.

At the moment, when I try to set Craft as a downstream in a federated config, I receive the following error:

```
Error checking for changes to service definitions: Couldn't load service definitions for "craft" at http://craft/graphql: Cannot query field "_service" on type "Query".
```

```
const gateway = new ApolloGateway({
  serviceList: [
    { name: 'users', url: 'http://users:4000' },
    { name: 'collections', url: 'http://collections:4000' },
    { name: 'craft', url: 'http://craft/graphql' }
  ]
});
```

This pointed me to [this issue](https://github.com/apollographql/apollo-server/issues/3419) on Apollo Server, which then links off to the federation spec.

Would this be something that's feasible to add?

**Comment by andris-sevcenko** [comment]
It would need to be supported by the library that we're using, but I'm not sure if that's on a workable timetable, there. There was some work going on regarding that at some point, but it seems like it stalled. (https://github.com/nuwave/lighthouse/pull/1051)

I'll keep this open, though, as it is a useful feature and maybe we can figure out a way of adding it.

**Comment by charlie-hadden** [comment]
Just to note: it appears that there is at least experimental support for this upstream now: https://lighthouse-php.com/5/federation/getting-started.html

**Comment by marjorg** [comment]
@andris-sevcenko Would be cool to have a way to plug into this using Craft
