### ISSUE TITLE
Cannot update plugin to version released before plugin licence expired

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#6311]
Maybe it's not a bug, but I admit, i didn't expected that.
I wanted to update one of the plugins on website that was no updated for a year. This plugin license expired very recently. One of the updates had critical fix, and it was update released before license expired. But still, i was not able to install any updates to these plugins - not only these released after the license expired.

I think it would be logical to be able to install updates that were released before license expired.

**Comment by brandonkelly** [comment]
This is indeed expected, and the Updates page in the control panel, as well as the `update` command, both reflect that. The goal is to reduce the support burden on developers for expired licenses. You are more likely to require support from the developer when you are updating the plugin.
