### ISSUE TITLE
Typo in FileHelper.php causing internal server error

### ISSUE THREAD

**Issue by bliswebagency** [craftcms/cms#6315]
### Description

We recently upgraded from 3.1 to 3.4 and on our production environment we were getting error 500's which we traced to this error below:

2020-07-02 18:42:25 [-][-][-][error][Error] Error: Class 'craft\helpers\ErrorExeption' not found in /var/www/vhosts/cityofadelaide/vendor/craftcms/cms/src/helpers/FileHelper.php:361

We suspected it was due to the spelling of ErrorExeption in FileHelper.php so we manually fixed the typo and the error was resolved.

Thank you.

### Steps to reproduce

1. Create condition to be unable to acquire file lock to raise exception
2. Error is produced

### Additional info

- Craft version: 3.4.25
- PHP version: 7.0.33-29
- Database driver & version:
- Plugins & versions:

**Comment by andris-sevcenko** [comment]
Thanks for that! Just fixed it for the next Craft 3.4 release.

**Comment by brandonkelly** [comment]
Craft 3.4.27 is out now with the fix.

**Comment by bliswebagency** [comment]
Thank you for the fix!
