### ISSUE TITLE
Tables fields editing Broken inside Matrix Fields

### ISSUE THREAD

**Issue by terryupton** [craftcms/cms#6319]
### Description
I have come across a bug that makes it impossible to edit table field columns when a table is used inside a matrix block.
The table type defaults back to checkbox even though single line was selected initially.
If the table type is edited then when you go back into the field to edit it again, it defaults back to checkbox.
The same occurs with handle names and column titles. These keep reverting back to previous state.

I have created the following video to illustrate the problem.
https://www.dropbox.com/s/thdos91jjiqe4hr/Screen%20Recording%202020-07-03%20at%2013.26.18.mov?dl=0

**This is stopping me in my tracks as I need to edit some table columns and handles inside this matrix field.**

### Steps to reproduce

1. Create a matrix field with a table inside a block.
2. Try to edit the table type, handle or column title, save and then go back to the field editor

### Additional info

- Craft version: Craft Pro 3.4.26
- PHP version: 7.2.31

**Comment by elodiegrondin** [comment]
Hello, I also get the same issue. I hope the problem will be fixed in the next update

**Comment by LauraMontgomery** [comment]
Also getting this

**Comment by OwenMelbz** [comment]
Also got this, was very confusing :(

I downgraded back to 3.4.25 and fixed it by changing the Field again

**Comment by brandonkelly** [comment]
Looks like this is a symptom of #6317. We just released Craft 3.4.27 with a fix.
