### ISSUE TITLE
Base URL of site with alias is displayed wrong

### ISSUE THREAD

**Issue by sjelfull** [craftcms/cms#6325]
### Description

In the Sites list, the base URL displayed is the same as where Craft is hosted.

![image](https://user-images.githubusercontent.com/10508/86532308-40051400-bec9-11ea-821f-0a441d04aebe.png)

However, the base URL is really set to another url via an alias.

![image](https://user-images.githubusercontent.com/10508/86532347-76429380-bec9-11ea-91e8-f13602553bb4.png)

### Additional info

- Craft version: 3.5.0-beta.2
- PHP version: 7.4

**Comment by brandonkelly** [comment]
What is `@siteUrlPublic` set to, exactly?

**Comment by sjelfull** [comment]
Its set to `https://www.site.com`.

**Comment by brandonkelly** [comment]
I’m not seeing the same behavior on my end. Can you try changing your `craftcms/cms` requirement to `3.5.x-dev`, and run `composer update`?

**Comment by sjelfull** [comment]
I still see the same behavior after updating. FYI I see the same on other sites.

The alias is set like this: `'siteUrlPublic' => getenv('SITE_URL_PUBLIC'),`

**Comment by brandonkelly** [comment]
If you run `./craft shell`, and then output `Craft::$app->primarySite->baseUrl`, what does that give you?
