### ISSUE TITLE
Improper CASCADE during AssetFolder deletion results in dangling Element records

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/cms#6326]
### Description

It looks like the `CASCADE` set up in the Install migration is enough to trash `{{%asset}}` table rows, but doesn't totally scrub their Element records:

https://github.com/craftcms/cms/blob/fe2030908d76a029190492e27febdb3c9461638e/src/migrations/Install.php#L936

If this is the intended behavior, there should probably be some kind of manual deletion for assets within the folder, and not just rely on the foreign key. In other words: it's not a suitable substitute for going through `Elements::deleteElement(…)`.

However: my general preference for this would be to have assets just leak out to the Volume root—though I do understand that it's not trivial to move the files (locally or on a cloud provider) to avoid them being trashed with the directory, wherever it lives!

### Steps to reproduce
Via the CP:

1. Create an Asset Volume;
2. Add a Folder;
3. Upload an Asset to that Folder, noting its `id` in the `{{%assets}}` table;
4. Delete the Folder created in step 2;
5. See missing row in `{{%assets}}` table;
6. See dangling row with the same ID in `{{%elements}}` table.

### Additional info
A little out of date, on this one…

- Craft version: 3.3.18.1
- PHP version: 7.2.31
- Database driver & version: PostgreSQL 10.13
- Plugins & versions: See below!

<table class="data fullwidth fixed-layout" dir="ltr">
            <tbody>
                                    <tr>
                        <th class="light">Colors</th>
                        <td>1.0.8</td>
                    </tr>
                                    <tr>
                        <th class="light">Cookies</th>
                        <td>1.1.11</td>
                    </tr>
                                    <tr>
                        <th class="light">Craft Commerce</th>
                        <td>2.2.8</td>
                    </tr>
                                    <tr>
                        <th class="light">Entry Instructions</th>
                        <td>1.0.7</td>
                    </tr>
                                    <tr>
                        <th class="light">Forms</th>
                        <td>2.5.27</td>
                    </tr>
                                    <tr>
                        <th class="light">Google Cloud Storage</th>
                        <td>1.3.0</td>
                    </tr>
                                    <tr>
                        <th class="light">Maps</th>
                        <td>3.8.2</td>
                    </tr>
                                    <tr>
                        <th class="light">Postmark</th>
                        <td>2.0.2</td>
                    </tr>
                                    <tr>
                        <th class="light">Redactor</th>
                        <td>2.4.0</td>
                    </tr>
                                    <tr>
                        <th class="light">Redactor Anchors</th>
                        <td>1.1.0</td>
                    </tr>
                                    <tr>
                        <th class="light">Redirects</th>
                        <td>3.1.37</td>
                    </tr>
                                    <tr>
                        <th class="light">Smart Map</th>
                        <td>3.2.2.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Stripe for Craft Commerce</th>
                        <td>2.2.2</td>
                    </tr>
                                    <tr>
                        <th class="light">Twigpack</th>
                        <td>1.2.0</td>
                    </tr>
                                    <tr>
                        <th class="light">Typogrify</th>
                        <td>1.1.18</td>
                    </tr>
                            </tbody>
        </table>

**Comment by brandonkelly** [comment]
We just released Craft 3.4.28 with a fix for this. Thanks for reporting!
