### ISSUE TITLE
Installing plugin via CLI with allowAdminChanges false

### ISSUE THREAD

**Issue by JeanLucEsser** [craftcms/cms#6329]
### Description

It looks like allowAdminChanges prevents the installation of plugins from the command line.

I would argue that we need a way to prevent admin changes from the cp while allowing for updates and plugin installations from the command line but that's not what this is about (I may be missing something though).

If I try to install a plugin via the cli while `allowAdminChanges` is set to `false` I get an error:
```
./craft install/plugin sendgrid
*** installing sendgrid
*** failed to install sendgrid: Changes to the project config are not possible while in read-only mode.
```

But a new line is added to the plugins table in the db nonetheless.

From there, whatever the value of `allowAdminChanges` is (change it back to `true`), I am unable to install the plugin.
```
./craft install/plugin sendgrid
*** installing sendgrid
*** failed to install sendgrid: No plugin exists with the handle "sendgrid".
```

Note that with `ostark/craft-plugin-commands` installed, I cannot uninstall the plugin, I get the same error saying no plugin with the corresponding handle exists.

The only way to get the plugin to be installed again via cli is to manually remove the line in the plugins table in the db.

### Additional info

- Craft version: 3.4.27 (latest)
- PHP version: 7.4
- Database driver & version: mysql 5.7
- Plugins & versions: only sendgrid (latest) for testing purpose

**Comment by brandonkelly** [comment]
Thanks for pointing that out. I’ve just added an exception to `allowAdminChanges=false` for plugin installation/uninstallation, for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.28 is out now with this change.
