### ISSUE TITLE
TypeError: Argument 1 passed to craft\services\Fields::getGroupById() must be of the type integer, null given

### ISSUE THREAD

**Issue by andrelopez** [craftcms/cms#6332]
### Description

This happens on a fresh install

### Steps to reproduce

1. Fresh install
2. Create a field (field group does not exist yet, and the UI does not mark this as required) CLick Save and go to the fields index
3. Got the error as the field was stored with `groupId` as null in the DB

### Additional info

- Craft version: 3.4.25
- PHP version: 7.3
- Database driver & version: Mysql
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
A fresh install will give you a default “Common” field group. Did you delete that or something?

**Comment by andrelopez** [comment]
@brandonkelly I'm unable to recreate this issue again. I'm able to see the `common` field group on a fresh install. It was something on my dev env.

**Comment by brandonkelly** [comment]
Alright, thanks for double-checking.
