### ISSUE TITLE
Offer a default "gzip" option for the DB backup/restore commands

### ISSUE THREAD

**Issue by FreekVR** [craftcms/cms#6335]
### Description
Currently Craft allows for a custom `backupCommand` and `restoreCommand` in the config.

I have a fairly large database which is over 1GB in size, which results in lots of disk space being used for the backups.

I can change the default command to pipe the `mysqldump` output to `gzip` but this is rather cumbersome as I have to copy-paste all the Craft defaults into my custom command. 

Furthermore, if I customize the output filename (eg. append `.gz`), I'll get errors when Craft is checking whether the file exists:
```
root@d2113421a82a:/var/www/craft3# ./craft backup/db
Backing up the database ... done
PHP Warning 'yii\base\ErrorException' with message 'filesize(): stat failed for /var/www/craft3/storage/backups/craft_200707_130011_c9xlxumqs9_v3.4.26.sql'
```

I think it would be great to have a `compressDatabaseBackup` boolean in the Craft config which would just pipe through the existing backup command to use `gzip` or `zip`, which would default to `false` for backwards compatibility.

**Comment by brandonkelly** [comment]
gzip isn’t an option without us starting to require the [Zlib](https://www.php.net/manual/en/book.zlib.php) extension, but we do already require the [Zip](https://www.php.net/manual/en/book.zip.php) extension, so I went ahead and added a `--zip` falg to the `backup` command for the next Craft 3.5 release, which you can pass to have the backup saved as a .zip file.

(Related to #5822.)
