### ISSUE TITLE
Asset Volume Permissions: Replace files without being able to remove files and folders

### ISSUE THREAD

**Issue by caseyreid** [craftcms/cms#6336]
As far as I can tell, in order for a user to be able to replace a file uploaded by another user, they also need to have the ability to "Remove files and folders". There is not currently a set of permissions that allows a user to replace a file but not remove it. Or to replace files and not delete folders.

![asset permissions](https://user-images.githubusercontent.com/133320/86817261-630b0180-c04a-11ea-9d08-ada28f3edfe8.png)

We have sites where we want to allow users to be able to replace files uploaded by other users, but we also do not want them to be able to delete entire folders or even files. It feels like "replace" and "remove" should not be so connected at the volume level. Instead, there should be separate permissions related to removing files and folders, and replacing files.

A possible modification to the Asset volume user permissions would be as follows.
-- View volume
---- Upload files
---- Create subfolders
---- Remove files and folders
---- **Replace files**
---- Edit images
---- View files uploaded by other users
-------- Edit files uploaded by other users
-------- Replace files uploaded by other users
-------- Remove files uploaded by other users
-------- Edit images uploaded by other users
 
Where Replace files and Remove files are separate permissions.

Another consideration would be to just not make "Remove files and folders" a requirement for a user to be able to "Replace files uploaded by other users". That may create some confusion if that is still required for "Remove files uploaded by other users" to work, but I think the distinction between Replace and Remove is still necessary.

Craft 3.4.27

**Comment by brandonkelly** [comment]
Seems reasonable.

**Comment by andris-sevcenko** [comment]
Just added this for the next 3.5 release!
