### ISSUE TITLE
A few mayor items in the Control Panel have wrong translations in Dutch

### ISSUE THREAD

**Issue by Friksel** [craftcms/cms#6337]
### Description
Some important translations in the Control Panel are wrong:

'New Entry' is translated into 'Nieuw bericht', which means 'New Message' in Dutch, so is something completely different.
Also related items are translated to corresponding, but wrong translations, like 'PostDate' is translated into 'Berichtdatum', which means 'MessageDate' in Dutch. A better name in Dutch would be 'Nieuw Item', which is half English, but I'm sure most if not all Dutch would understand that. And it's way better then something like 'Nieuw Artikel', which means 'New Article' in Dutch, because not all entries are always articles. But all entries are always items.

Also the 'Entries' menu is translated into 'Inhoud', which means 'content' in Dutch, which is not the same as 'entries'. I would suggest to use 'Artikelen' (which means 'Articles' in Dutch) or as mentioned above 'Items' instead. Content is way too general IMHO and in fact everything in the CMS is content as it's a CONTENT management system to begin with. Also categories and tags could be called content.

Translating 'Entries' into 'Inhoud' (so Content in Dutch) is even getting more confusing when looking in the User rights panel where it says 'Inhoud bewerken', meaning 'Edit content'.... uh... which content??? This is very confusing for customers and non-descriptive.
This should definitely be changed into something way more specific and describing what actually happens. Like 'Items bewerken' (which is also plural btw, where 'Inhoud' (content) is neither singular nor plural, which is confusing on its own).

Also 'Maak inhoud aan' means 'Create content'... same here. And so on.
![image](https://user-images.githubusercontent.com/3089978/86824357-56100180-c08e-11ea-953d-a45c6e3530c4.png)

Also under 'hulpprogramma's' (utilities) in the user rights menu it says 'Afschaffingsfouten'... but this item is only for developers. And all developers I know of work in English and it takes some while before you understand that 'Afschaffingsfouten' means 'Deprecation Warnings'. Not only does 'fouten' means 'faults', which is obviously different then 'warnings', please just leave this untranslated as 'Deprecation Warnings', or else 'Deprecation Waarschuwingen' (waarschuwingen means warnings in Dutch). I even needed to look up in the English version of the CP to understand what 'Afschaffingsfouten' was suppose to mean.

We Dutch have a lot of English words in our dayly language and when translated directly into Dutch some words, especially Development and computer-related words, sound pretty weird in our ears and we have to think twice to understand them. 

![image](https://user-images.githubusercontent.com/3089978/86819554-1cd49300-c088-11ea-8549-3103e90999c2.png)

![image](https://user-images.githubusercontent.com/3089978/86820645-a0db4a80-c089-11ea-95ab-6c3a8341b434.png)

![image](https://user-images.githubusercontent.com/3089978/86824910-0ed64080-c08f-11ea-99b2-ece8124689a3.png)

### Steps to reproduce

1. Open Control panel --> Look at the menu and read above notes from this issue-post
2. Open the Entries menu --> Look at the button and column texts
3. Open user rights panel --> same 

### Additional info

- Craft version: 3.4.27

**Comment by angrybrad** [comment]
Thanks for the feedback.  We manage our control panel translations over on crowdin.com (Dutch translations: https://crowdin.com/translate/craft-cms/all/en-nl)

Feel free to make suggestions/changes there, and they will make it back into Github as an automatic pull request.
