### ISSUE TITLE
craft setup/db-creds command ignores port parameter when run in non-interactive mode

### ISSUE THREAD

**Issue by PatrickMessierGoC** [craftcms/cms#6339]
### Description
We use a non-conventional port number (6432 instead of 5432) for our postgres database. When we use craft set/db-creds command to automate the webserver provisioning, we systematically get the following error: 
```
Testing database credentials ... failed: SQLSTATE[08006] [7] could not connect to server: Connection refused
Is the server running on host "localhost" (127.0.0.1) and accepting TCP/IP connections on port 5432?
```

### Steps to reproduce
1. Run the following command: 
`./craft setup/db-creds --interactive=0 --driver=pgsql --server=localhost --port=6432 --database=<dbname> --user=<username> --password=<password>
`
### Additional info
When running the same command in interactive mode,
`./craft setup/db-creds --interactive=1 --driver=pgsql --server=localhost --port=6432 --database=<dbname> --user=<username> --password=<password>
` 
all default values proposed by the wizzard match the corresponding parameters except for the port value which is always "5432".

- Craft version: Craft Pro 3.4.19.1
- PHP version: 7.2.24
- Database driver & version: PostgreSQL 10.11
- Plugins & versions:
 -- Breadcrumb	1.1.0
 -- CodeMirror	1.0.2
 -- Field Labels	1.1.10
 -- Field Manager	2.1.6
 -- Mix	1.5.2
 -- Neo	2.7.10
 -- Redactor	2.6.1
 -- SEO	3.6.4
 -- Super Table	2.4.9
 -- Table Maker	2.0.1
 -- Typed link field	1.0.21
 -- Workflow	1.4.8

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.28 is out now with this fix.
