### ISSUE TITLE
The `relatedToAll` argument does not work when used on a nested field

### ISSUE THREAD

**Issue by chadclark** [craftcms/cms#6343]
**What are you trying to do?**
I would like to filter product queries using GraphQL and return results if _all_ attributes are true.

I would like to have the ability to use the `relatedToAll` argument in a Commerce product query, specifically with GraphQL. Currently, only the `relatedTo` argument exists and there is not a clear way to return results _only_ if all attributes are true with GraphQL. There is a [Twig solution](https://docs.craftcms.com/v3/relations.html#passing-multiple-relation-criteria) using `and`, but it is unclear if this is possible to use in a GraphQL query.

**What's your proposed solution?**
Match the same GraphQL functionality that exists in [Craft CMS](https://docs.craftcms.com/v3/graphql.html#an-example-query-and-response).

**Comment by andris-sevcenko** [comment]
So the real issue here is that `relatedToAll` does not work correctly, when it's used at least one level deep, which is why you're hitting this error, @chadclark

**Comment by andris-sevcenko** [comment]
Thanks for that, @chadclark - just fixed it for the next 3.4 release!

**Comment by chadclark** [comment]
Fantastic! Thanks for looking into it, @andris-sevcenko and @nfourtythree!

**Comment by brandonkelly** [comment]
Craft 3.4.28 is out now with this fix.
