### ISSUE TITLE
Issue when starting project from existing composer.json/project.yaml

### ISSUE THREAD

**Issue by pnpaes** [craftcms/cms#6345]
### Description
When i want to run an existing setup into a new installation (a team member installing the project) pull the repository, run composer install, then the craft setup/install.
Even though all plugins and requirements get installed with composer when we sync the project yaml and craft is installing/activating all plugins it runs into dependencies issue. That is because Craft runs the plugins configuration in alphabetical order and if a plugin requires another plugin that is not yet activated due to the first letter of its name then it throws the error.
In my case this applies to a craft commerce 3 project and I also have a plugin called "cart notice". When craft tries to enable the "cart notice" plugin the "commerce" plugins hasn't been enabled yet and the sync fails.

So instead of finalizing the installation with the existing .yaml file it instead rename the existing one and place in the backup folder and create a new fresh one with only the basic setup in it.

This is the error thrown during the installation:
   ` > installing cart-notices ...     > can't apply existing project config: Commerce is required for this plugin to be installed! `

   ` > renaming project.yaml to project-20200707-074724.yaml and moving to config backup folder ... done `

One alternative would be for all plugins that require **commerce** to have the name starting with **commerce-**XYZ

Another (for me the best option) it would be to when there is a dependency mismatch like this that the system looks if by any chance the required plugin is also in the list to be enabled by the sync and sync that plugin before retrying to sync the list again.

### Steps to reproduce

1. Create a new Craft CMS with composer.
2. Run ./craft setup
3. Edit the config/general.php to use project.yaml config file
4. Update to pro in the plugins store
5. Install Craft Commerce Pro (trial) from the plugins store
6. Install the "Cart Notice" plugin
7. Duplicate the project folder and change the .env file to point to a fresh database
8. Access the folder in terminal and run:
-  `composer install` (not really necessary when cloning the folder, but needed if pulling from a repository since the vendor folder is not tracked)
- `./craft install` (No need to run the setup since all config info is properly set on the .env file)

### Additional info

- Craft version: 3.4.10
- PHP version: 7.4.6
- Database driver & version: mysql 5.7.3
- Plugins & versions: Commerce 3.1.11 and Cart Notice 1.0.2

**Comment by brandonkelly** [comment]
I would say this is a bug with your Cart Notice plugin. Plugins should be able to be installed in any order, and if a plugin’s functionality relies on another plugin, then it should check to make sure that other plugin is installed first.

(related: #6347)
