### ISSUE TITLE
Minor style enhancements to Matrix block titlebar styling

### ISSUE THREAD

**Issue by watershed** [craftcms/cms#6348]
When scrolling through vertically lengthy Matrix blocks it can be more difficult than it need be to see where one block ends and another begins. The 10px `margin-bottom` between blocks is easily overlooked.

I propose a default styling applied to `.titlebar` **when a block is expanded**, with a background colour equivalent to the `<body>`: 

```
.matrixblock:not(.collapsed) .titlebar {
    background: hsl(210, 50%, 93%);
}
```
![matrixblock-expanded-titlebar](https://user-images.githubusercontent.com/219060/86921143-915c1000-c122-11ea-891d-fb8749ef5591.png)

It would be good therefore if the text and symbolic elements within the title bar were authored with a translucent equivalent colour rather than the opaque hex value, so that they ‘add’ themselves to whatever the underlying `.titlebar` background currently is.

**Comment by brandonkelly** [comment]
I darkened the header ever so slightly in 5ad5cfc32fc1060af241bebe0325d129456f4e3e – see a screenshot here: https://github.com/craftcms/cms/issues/6346#issuecomment-658919451
