### ISSUE TITLE
Thumbnail background interferes with png's

### ISSUE THREAD

**Issue by bartrylant** [craftcms/cms#6349]
### Description

The new asset thumbnail has a Facebook-like "person" background. When someone uploads a png with transparent parts, or an image that simply isn't square, the default person-background is still visible on the sides, which isn't a nice sight at all.

**Comment by brandonkelly** [comment]
I’m not able to reproduce that anywhere. Can you post a screenshot of exactly where you’re seeing it? And check to make sure Craft is up-to-date, and that you don’t have any custom CSS styles.

**Comment by bartrylant** [comment]
Sorry, it seems to be a problem with the @putyourlightson Campaign plugin.

![Schermafbeelding 7](https://user-images.githubusercontent.com/1434451/87654044-ae15ca80-c756-11ea-9308-0c5f7024fabb.png)
