### ISSUE TITLE
Project config rebuild empties current config

### ISSUE THREAD

**Issue by olivierbon** [craftcms/cms#6350]
### Description

Running `./craft project-config/rebuild` on an install with `'useProjectConfigFile' => true,` but **without** a `config/project.yaml` in place empties the current config leaving only `dateModified` in both the file and `projectconfig` table.

### Steps to reproduce

1. Create a fresh Craft install (or on an existing site)
2. Set `'useProjectConfigFile' => true,` in `config/general.php` and immediately run `./craft project-config/rebuild`

### Additional info

- Craft version: 3.4.27

**Comment by andris-sevcenko** [comment]
Fixed this for the next 3.4 release.

**Comment by brandonkelly** [comment]
Craft 3.4.28 is out now with this fix.
