### ISSUE TITLE
Cannot replace SVGs in Assets

### ISSUE THREAD

**Issue by joshuabaker** [craftcms/cms#6351]
I just get the following error.

```
Failed to load the SVG string.
```

#### Versions

- Craft CMS 3.5.0-beta.3
- PHP 7.4.4
- Imagick 3.4.4 (ImageMagick 7.0.10-1)
- Imagine 1.2.3-dev
- Amazon S3 1.2.8

**Comment by joshuabaker** [comment]
Also applies to saving SVG assets it would seem.

**Comment by joshuabaker** [comment]
Found [a comment](https://github.com/craftcms/cms/issues/5435#issuecomment-574808983) from @mattstein about this in #5435.

This is happening on @fortrabbit for specific apps so _feels_ like it’d be software related.

**Comment by joshuabaker** [comment]
I’ve noted that the wrong mime type is assigned (`images/svg` not `image/svg+xml`), which correlates with an existing [PHP bug report](https://bugs.php.net/bug.php?id=79045).

> PHP when given an svg perhaps without the xml header, will return a mime type of image/svg instead of image/svg+xml, however IANA does not list image/svg as an existant mimetype, nor do browsers display it. 

@brandonkelly This looks like it’s just a mime type issue at the core. It’d be good to confirm though. As this is going to impact any install running PHP 7.4, please can we this in Craft, replacing instances of `image/svg` (invalid) with `image/svg+xml`.

**Comment by brandonkelly** [comment]
Craft 3.4.28 is out now with this fix. Thanks again for the PR!

**Comment by joshuabaker** [comment]
Thanks, Brandon! 🙏  Are we able to get this into 3.5 too without too much pain?

**Comment by brandonkelly** [comment]
It’s already there, you just need to be running from the 3.5 branch. Change your craftcms/cms requirement in composer.json to `3.5.x-dev`, and then run `composer update`.
