### ISSUE TITLE
Issue Querying Relational Fields in Craft 3.5.0-beta.3 

### ISSUE THREAD

**Issue by leobauza** [craftcms/cms#6352]
### Description

While testing out `"craftcms/cms": "3.5.x-dev"` to try mutations I was running into errors when querying for relational fields:

eg.
 
```
query {
  entries {
    ... on game_game_Entry {
      user {
        id 
      }
    }
  }
}
```

Where `user` is a relational field was giving me this error:

```
Class 'craft\\gql\\ElementResolver' not found
```

I believe the problem is a missing import in `craftcms/cms/src/gql/ElementQueryConditionBuilder.php` adding:

```
use craft\gql\base\ElementResolver;
```

Fixes the issue for me.

### Steps to reproduce

1. Query a relational field with Craft `3.5.0-beta.3` 
2. See Error

### Additional info

- Craft version: 3.5.0-beta.3

**Comment by andris-sevcenko** [comment]
Thanks for that! Just fixed it on the 3.5 branch!
