### ISSUE TITLE
In Control Panel entries search, structure titles are acting odd

### ISSUE THREAD

**Issue by sunscreem** [craftcms/cms#6354]
### Description

Pictures say a thousand words. Short version, the search stops working after 3 letters:

![image](https://user-images.githubusercontent.com/7523595/87032272-430b4780-c1dc-11ea-9a95-b52c779c0b02.png)

![image](https://user-images.githubusercontent.com/7523595/87032283-48689200-c1dc-11ea-9dec-e3735b70eb8e.png)

![image](https://user-images.githubusercontent.com/7523595/87032304-50c0cd00-c1dc-11ea-9eaa-2691c5229fca.png)

### Steps to reproduce

1. Create a structure
2. Try and search for it as above.

### Additional info

- Craft version: 3.4.27
- PHP version: 7.4.6
- Database driver & version: MySQL 8.0.20
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
4 characters is when Craft switches from a LIKE search to using the fulltext index, because it’s the default [ft_min_word_len](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_ft_min_word_len) value. Maybe yours is set to something higher.

**Comment by sunscreem** [comment]
Hey @brandonkelly 

![image](https://user-images.githubusercontent.com/7523595/87818256-2a490480-c862-11ea-8999-1afe5b33ef9a.png)

Looks like that was set to the default. Any other things I could try?

**Comment by angrybrad** [comment]
@sunscreem "about" is a full text search stop word for both MyISAM and InnoDB storage engines: https://dev.mysql.com/doc/refman/8.0/en/fulltext-stopwords.html

You'd have to modify your MySQL server config's stop word list if you want to remove it - nothing Craft can do for it.

**Comment by sunscreem** [comment]
@angrybrad We'll you learn something new every day. Thank you sir. That solves it :)
