### ISSUE TITLE
Preview will not open again after closing when refresh is false

### ISSUE THREAD

**Issue by Kethatril** [craftcms/cms#6356]
### Description
For preview targets where refresh is false the second time you try to preview the entry the preview frame does not show
I've tracked down the cause of the issue and it looks like the slideIn animation is not triggered when refresh is false. The first time it works because refresh is always true for the first preview trigger.

Refresh is false here on the second open of the preview:
https://github.com/craftcms/cms/blob/9a7a4caf057b797e683b2603e3490735bb8955dd/src/web/assets/cp/src/js/Preview.js#L302-L319

But the slideIn animation only gets triggered here when refresh is true
https://github.com/craftcms/cms/blob/9a7a4caf057b797e683b2603e3490735bb8955dd/src/web/assets/cp/src/js/Preview.js#L361-L375

So the preview does not show

### Steps to reproduce

1. Create a preview target where refresh is unticked
2. Open an entry and click preview then close the preview
3. Click on preview again and the preview frame will not slide out.

### Additional info

- Craft version: Craft Pro 3.4.27
- PHP version: 7.3.2
- Database driver & version: MySQL 5.7.26
- Plugins & versions:
    - Imager X v3.1.1
    - Redactor 2.6.1
    - Super Table 2.5.1
    - Typed link field 2.0.0-beta.9

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.28 is out now with this fix.
