### ISSUE TITLE
Asset transforms continuously generated for missing assets - Uses huge amount of PHP resources

### ISSUE THREAD

**Issue by sclander** [craftcms/cms#6357]
### Description

A client site from my company was recently hacked, and the uploads directory was wiped out. When trying to fix the site, attempts to generate asset transforms for the missing images were running constantly and throwing up a bunch of PHP errors. There were so many PHP scripts running that the site basically came to a halt, and nginx was even throwing out 502 errors and not loading pages at all sometimes.

The site was running so slowly that I wasn't able to add the assets back in through the admin panel, but once they were put back into place with scp, everything was immediately running normally again. I think there should be some sort of limit on how many times these can run and fail, then Craft should stop trying to generate them.

### Steps to reproduce

1. Add an asset transform
2. Upload an asset that uses that transform
3. Use that asset with the transform somewhere in your templates
4. Remove the uploaded file, but keep the reference to it in your template/db

### Additional info

- Craft version: Craft Pro 3.4.27
- PHP version: 7.2.24
- Database driver & version: MySQL 5.7.23
- Plugins & versions: Imager 2.4.0 (may be applicable here, I'm not sure)

**Comment by andris-sevcenko** [comment]
> were running constantly and throwing up a bunch of PHP errors.

Can you elaborate on what the errors were?

**Comment by andris-sevcenko** [comment]
Improved the behavior for future happenings. Now Craft will bail much sooner instead of mulling 30 seconds over whether or not a transform can be created. Logging in such cases is also now improved.

Just pushed this for Craft 3.4

**Comment by brandonkelly** [comment]
Craft 3.4.28 is out now with this change.
