### ISSUE TITLE
The drafts option of the status filter dropdown will only be available if there are drafts in the primary site

### ISSUE THREAD

**Issue by JoshCoady** [craftcms/cms#6370]
### Description
The query used to determine if there are any drafts only queries the primary site and not either all sites or the currently selected site in the control panel entries index page.

### Steps to reproduce

1. Install vanilla craft (I used the composer create-project method)
2. Create a second site with default settings
3. Create a section and set it to not propagate entries
4. Go to the entries index page and select the second site
5. Click the new entry button
6. Enter a title and wait for it to auto-save -- do not hit the create button
7. Go back to the entries index page and note there is no drafts option in the status menu even though you just created a draft
8. You can confirm this by editing `vendor/craftcms/cms/src/templates/_elements/toolbar.html` such that it always shows the Drafts option by changing line 43 to `{% if true or draftsExist %}` and then refreshing the page. Note that the Drafts option is now there. Select it and then the draft created in step 6 will show up.
9. Now revert that change to toolbar.html
10. Create a draft in the primary site
11. Now the Drafts option is available for all sites

### Additional info

- Craft version: 3.4.27
- PHP version: 7.4.4
- Database driver & version: MySQL 5.5.5
- Plugins & versions: No plugins are enabled.

**Comment by brandonkelly** [comment]
Thank for reporting that! Just fixed it for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.28 is out now with this fix.
