### ISSUE TITLE
3.4.23 -> 3.5: craft.app.request.segments includes empty string on homepage

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#6371]
In 3.4.23 and prior, on a homepage, `craft.app.request.segments` would return `[]`, so `craft.app.request.segments|length` was a sensible test for being on the homepage.

After upgrading to 3.5.x-dev (152f99c62c97ce96d5edfbc0d2aa3acc751be536), we're getting an array with an empty string`[""]`.

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next 3.5 release.
