### ISSUE TITLE
Yii 2.0.36 + Inline Validators

### ISSUE THREAD

**Issue by samhibberd** [craftcms/cms#6372]
### Description

Running into some odd behavior with inline validators, I think its related the to the changes in Yii 2.0.36.

https://www.yiiframework.com/news/293/yii-2-0-36

First noticed that a couple of my custom inline validators were throwing an `UnknownMethodException` when referencing the current class via `$this` from within the validator. Move the validator out into it's own public function and all good.

It looks like commerce is also running into the same issue when using an inline validator within the Variant element:

https://github.com/craftcms/commerce/blob/efc4219e69167df56f28006e7dc816894b23cef4/src/elements/Variant.php#L749

Saving an order with line items throws the `UnknownMethodException` within the cp for me:

> Calling unknown method: craft\commerce\models\LineItem::hasStock()

Not sure if / where Craft might run into this too and if this is still possible with the new version of Yii (or if it is a Yii bug), but figured best to post here as a possible issue with 3.5, before reporting to commerce. 

### Additional info

craftcms/cms 3.5.x-dev 5f03758
craftcms/commerce 3.1.11

**Comment by brandonkelly** [comment]
Thanks for looking into that. Added workarounds to Commerce (https://github.com/craftcms/commerce/compare/960af5f5398aa4fa771d74f14c789bc9cb1858c5...200f545fd53d3d3f0d67ce65795e69fd46ba742a) and Craft (9f4105ca265c2e778bd4c679f852dda2b18c5c9d), and also reported the behavior change to Yii (yiisoft/yii2#18175).
