### ISSUE TITLE
Eager loading custom fields on element fields

### ISSUE THREAD

**Issue by NixonGit** [craftcms/cms#6373]
### Description

Not 100% sure if a bug or a misunderstanding of eager loading but should eager loading work in the following situation?

```
{% set eagerAsset = entry.assetsField.with(['alt']).one() %}

{{ eagerAsset.alt }}
```

Where entry is the autoloaded `Entry` variable and `alt` is a text field. At the moment `eagerAsset.alt` returns an empty array which is incorrect.

### Additional info

- Craft version: 3.4.27, 3.5.x-dev
- PHP version: 7.4.2
- Database driver & version: MySQL 5.7.26

**Comment by andris-sevcenko** [comment]
Eager-loading can be applied to element relationships, so, in this case, you should eager-load the asset, not its fields.

```twig
{% set entries = craft.entries.<some criteria>.with(['assetsField']).all() %}

{% for entry in entries %}

    {% set asset = entry.assetsField[0] ?? null %}

    {% if asset %}
        <img src="{{ asset.url }}" alt="{{ asset.alt }}">
    {% endif %}

{% endfor %}
```

**Comment by NixonGit** [comment]
Probably a silly question as I don't fully understand the internals but is there potential for eager loading to be extended to work for the use case above? On our baseline without the asset query we have 28 db calls. With the query `assetQuery.one()` we get 30 db queries, accessing any attribute (width, url, custom field) on asset takes this to 32 calls.

The above is a simplified use case. We're passing an asset query to a macro and doing the heaving lifting in there. Whilst we could more of the heavy lifting in the main loop be it an entries loop or matrix block it all becomes a bit messy. With the improvements to eager loading asset transforms we're trying to find the balance between db queries and keeping things dry / dev experiance. 

```
{% macro img(assetQuery = null, options = []) %}
  {% set baseTransform = { width: options.width, height: options.height } %}

  {% set sizes = options.widths|map(width => "#{width}w") %}
  {% set asset = assetQuery.withTransforms([baseTransform]|merge(sizes)).one() ?? null %}

  {% do asset.setTransform(baseTransform) %}
   
   {{ tag('img', {
      width: options.width,
      height: options.height,
      src: asset.getUrl({ transform: baseTransform }),
      srcset: asset.getSrcset(sizes),
   }) }}
{% endmacro %}
```

**Comment by andris-sevcenko** [comment]
Eager-loading is not required for custom content fields unless they are relational fields.

At a glance, I think it's possible that your transform eager-loading is not working, as I'm not sure if Craft supports "#{width}w" notation. You can take a look at https://github.com/craftcms/cms/issues/5774#issuecomment-597304297 for more context.

**Comment by NixonGit** [comment]
I missed a variable declaration the result of sizes is just an array `['200w', '300w']` when simplifying the macro just to give context. But even in the most simple case of a raw html page with no includes the base line is 23 queries. Calling `{% set asset = entry.assetsField.one() %}` results in 24 queries and then accessing a field `{{ asset.alt }}` results in 26.

I was expecting to be able to eager loading the custom field when performing the asset query with `one()` to keep the number down but I think I have misconceptions on eager loadings purpose. We are eager loading relational fields elsewhere on the site.

**Comment by brandonkelly** [comment]
What type of field is `alt`?

**Comment by NixonGit** [comment]
Alt is a plain text field.

**Comment by brandonkelly** [comment]
Accessing a plain text value should definitely not add a query on its own. If you are 100% confident it does, please compare the list of queries you’re getting with and with out accessing it, and post the additional queries you’re seeing.

Accessing the URL could cause an additional query if you’re using a transform that doesn’t exist yet.

**Comment by NixonGit** [comment]
For the template below we've compared the queries when doing just the asset query `{% set asset = entry.assetsField.one() %}` and the asset query combined with outputting `{{ asset.alt }}`.

```
<html>
  <head></head>
  <body>
    {% set asset = entry.assetsField.one() %}
    {{ asset.alt }}
  </body>
</html>
```

We get these two additional queries when adding `{{ asset.alt }}`.

```
SELECT `id`, `type`, `uid`
FROM `craft_fieldlayouts`
WHERE (`dateDeleted` IS NULL) AND (`id`=1)
LIMIT 1
```

```
SELECT `fields`.`id`, `fields`.`dateCreated`, `fields`.`dateUpdated`, `fields`.`groupId`, `fields`.`name`, `fields`.`handle`, `fields`.`context`, `fields`.`instructions`, `fields`.`translationMethod`, `fields`.`translationKeyFormat`, `fields`.`type`, `fields`.`settings`, `fields`.`uid`, `fields`.`searchable`, `flf`.`layoutId`, `flf`.`tabId`, `flf`.`required`, `flf`.`sortOrder`
FROM `craft_fields` `fields`
INNER JOIN `craft_fieldlayoutfields` `flf` ON `flf`.`fieldId` = `fields`.`id`
INNER JOIN `craft_fieldlayouttabs` `flt` ON `flt`.`id` = `flf`.`tabId`
WHERE `flf`.`layoutId`=1
ORDER BY `flt`.`sortOrder`, `flf`.`sortOrder`
```

Happy to fire over a db etc via support.

**Comment by brandonkelly** [comment]
Ah, ok, so those are just loading the field layout + the related fields. Those should only happen once per unique field layout needed for the request – so not an n+1 problem.
