### ISSUE TITLE
Issue Deleting fields on latest 3.5

### ISSUE THREAD

**Issue by samhibberd** [craftcms/cms#6374]
Deleting fields in the cp looks to have broken for me after updating to the latest 3.5 release. Deleting the field appears successful in the cp, although only the dateModified key in the new `config/project/project.yaml` file is updated. The field then re-appears in the list when the project config is next updated (I ran a composer update, to grab an even newer commit). Can't see anything obvious in the logs, or any errors being thrown.

craftcms/cms 3.5.x-dev 6d6b8ae

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed.
