### ISSUE TITLE
redirectToPostedUrl query params not attaching if redirecting from main plugin init

### ISSUE THREAD

**Issue by joshua-martin** [craftcms/cms#6375]
### Description

I have a `Plugin.php` file something like the following:
```
Event::on(
    Users::class,
    Users::EVENT_AFTER_ASSIGN_USER_TO_DEFAULT_GROUP,
    function(UserAssignGroupEvent $event) {
        if (Craft::$app->request->getBodyParam('formId') == "bar") {
            $contactsGroup = Craft::$app->userGroups->getGroupByHandle('foo');
                    
            Craft::$app->users->assignUserToGroups($event->user->id, [$contactsGroup->id]);
            Craft::$app->users->activateUser($event->user);

            return Craft::$app->controller->redirectToPostedUrl(['foo' => 'bar']);
        }
     }
 );
```

And in the form I'm setting the redirect input

```
[..]
{{ csrfInput() }}
{{ actionInput('users/save-user') }}
{{ hiddenInput('formId', 'bar') }}
{{ redirectInput('/' ~ craft.app.request.pathinfo ~ '?foo={foo}') }}
[..]
```
The redirect happens successfully, but I'm only ever seeing `?foo=` in the URL, it isn't correctly setting the query param.

This only appears to happen if I am using this function from the main `Plugin.php` file–any of my controller actions using the function set the query param correctly.

### Additional info

- Craft version: 3.4.27

**Comment by brandonkelly** [comment]
Just tested this locally and I’m not able to reproduce.

My form:

```twig
<form method="post" action="">
  {{ csrfInput() }}
  {{ actionInput('foo/test/test') }}
  {{ redirectInput('/' ~ craft.app.request.pathinfo ~ '?foo={foo}') }}
  <button type="submit">Submit</button>
</form>
```

Controller action:

```php
public function actionTest()
{
    return $this->redirectToPostedUrl(['foo' => 'bar']);
}
```

Clicking the Submit button redirects to the same URL + `?foo=bar`, as expected.

So something else must be going on in your code that is preventing it from working as expected.

**Comment by joshua-martin** [comment]
I mention that controller actions work fine. It is not working if you try in the main plugin file.

**Comment by brandonkelly** [comment]
Sorry, I missed that. Makes sense, because nothing cares about what your `EVENT_AFTER_ASSIGN_USER_TO_DEFAULT_GROUP` handler function returns, so the respoonse’s redirect URL will be re-set by whatever controller action is actually handling the requset.

Try changing this line:

```php
return Craft::$app->controller->redirectToPostedUrl(['foo' => 'bar']);
```

to:

```php
$response = Craft::$app->controller->redirectToPostedUrl(['foo' => 'bar']);
Craft::$app->end(0, $response);
```

**Comment by joshua-martin** [comment]
Thanks Brad, that's got it 👍
