### ISSUE TITLE
[GraphQL Mutations]: Assets – newFolderId required?

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#6377]
The `newFolderId` arg seems to be required, even if you want the asset to go in the directly into the volume – is this correct?

Without it, I get:
> Impossible to create an asset without providing a folder

Because of the naming I expected that to only be required if I was moving the asset…In this case I just wanted it to go in the root of the specified volume.

**Comment by andris-sevcenko** [comment]
Good call - will add that!

**Comment by andris-sevcenko** [comment]
And added for 3.5.
