### ISSUE TITLE
[GraphQL Mutations]: FileInput.url still checks for file extension

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#6378]
An image URL may or may not have an actual file extension, despite its filetype.

So, if you try to pass a URL like: 
https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR70B4gwSexhJSUzrq46J63aAoBFsRDYyTdmA

```
mutation {
  save_orderAttachments_Asset(_file: {url: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR70B4gwSexhJSUzrq46J63aAoBFsRDYyTdmA"}, newFolderId: 5){
    id
  }
}

```

> "“” is not an allowed file extension."

…which means you can only ever upload files that are URLs with extensions.

**Comment by andris-sevcenko** [comment]
In that case, you should be using the `filename` field as well, when uploading.
