### ISSUE TITLE
MySQL 8.0.21: column names uppercase, leading to 'Undefined index: constraint_name'

### ISSUE THREAD

**Issue by DavidOliver** [craftcms/cms#6379]
### Description

This seems to be a Yii issue, but I'm adding an issue here in case that helps the fix be included in Craft sooner once it's available. (Or even perhaps be worked around in the meantime if you think that's appropriate.)

https://github.com/yiisoft/yii2/issues/18171

After updating to MySQL 8.0.21, the following is raised:

> PHP Notice 'yii\base\ErrorException' with message 'Undefined index: constraint_name'                                                                          
> in /path/to/vendor/yiisoft/yii2/db/mysql/Schema.php:394

As I understand it, MySQL now returns the field names in uppercase, meaning the lowercase array indexes used in Yii's Schema.php don't work.

[This](https://github.com/yiisoft/yii2/issues/18171#issuecomment-658155849) is a temporary workaround I'm using locally for development.

### Additional info

- Craft version: 3.4.27
- PHP version: 7.4.8
- Database driver & version: MySQL 8.0.21

**Comment by danleecpi** [comment]
I'm seeing the same thing after migrating a site to another server.

```
PHP Notice 'yii\base\ErrorException' with message 'Undefined index: constraint_name'
 in /home/forge/galileo.123innovation.co.uk/vendor/yiisoft/yii2/db/mysql/Schema.php at line 394
```

Craft version: 3.4.26
PHP version: 7.2
Database driver & version: Ver 8.0.21

**Comment by jonlongnecker** [comment]
Migrating an in-development Craft site to a fresh Forge provisioned server using MySQL 8 and same error. Whole site is unavailable :(

**Comment by brandonkelly** [comment]
Just fixed this for the next release, which I’ll get out asap, but in the meantime you can patch your local install by changing your `craftcms/cms` requirement in `composer.json` to:

```json
"require": {
  "craftcms/cms": "dev-develop as 3.4.27",
  "...": "..."
}
```

Then run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.4.28 is out now with this fix.

**Comment by gkbrown22** [comment]
I am running 3.4.30 and I am seeing this error. Did this fixed get dropped?

**Comment by JayBox325** [comment]
I'm getting this issue, but I'm not able to update the site yet due to the time it'll take to update from 3.1 and plugins that change too much over time (I know I shouldn't have let this go this long, but the client wasn't engaged on updating regularly....)

**Comment by brandonkelly** [comment]
@JayBox325 If you can’t update Craft, then just stick with MySQL < 8.0.21.
