### ISSUE TITLE
[3.5.0-beta3] Project Config files are not updated when deleting a section

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#6380]
### Description

When deleting a section via the Control Panel, the section's`.yaml` file isn't deleted from the `config/project` folder, and Craft re-creates the deleted section if/when applying project config changes.

If the data cache is cleared after deleting the section, Craft gates the Control Panel with a "Your project config files contain pending changes" modal (because there's a section in the project config files that doesn't exist anymore).

I assumed this might have something to do with the section being soft deleted. However, the Yaml file still persists after hard deleting the section via `./craft gc`, and Craft still re-creates the deleted section when PC changes are applied (though it does _not_ recreate section's entry types if the section was hard deleted, so at that point I had a zombie section with 0 entry types).

I also tried rebuilding the project config after deleting the section. This makes Craft no longer re-create the deleted section when applying changes, although the section's Yaml file still wasn't deleted from the config folder.

_Note: I also tested deleting a category group, and it behaves the same way. I assume this issue affects volumes, global sets, sites etc as well, but I didn't test those._

### Steps to reproduce

1. Delete a section from the Control Panel
2. Confirm that the section's `.yaml` file persists in the `config/project` folder
3. Click "Apply changes only" from the Project Config utility tool
4. Confirm that the deleted section has been re-created

_Optionally, hard delete the soft deleted section via `./craft gc` before applying project config changes. Confirm that the deleted section is still re-created when applying PC changes, but without any entry types._

### Additional info

- Craft version: 3.5.0-beta3
- PHP version: 7.2.20
- Database driver & version: 5.6.43 Homebrew
- Plugins & versions:

**Comment by mmikkel** [comment]
This turned out to be a duplicate of #6374, and appear to be resolved in https://github.com/craftcms/cms/commit/7a64d5415985f965ffb9a2b4e76308e0d74af06c

**Comment by brandonkelly** [comment]
Yep!
