### ISSUE TITLE
Self relation causes entry field to loose value after saving

### ISSUE THREAD

**Issue by medoingthings** [craftcms/cms#6385]
### Description
When setting "Allow self relation" to true for an entry field, the value gets lost after saving, if the selected entry is the one you are editing at that moment – but only in live preview mode. Kinda hard to explain, see the steps to reproduce.

### Steps to reproduce

1. Add a new entry field and activate the "Allow self relation" option let’s call it `entrySource`
2. Add that field to an entries field layout
3. Create a new entry and save it, let’s give it the title `Inception`
4. Edit that entry again and **use the live preview** to add the entry `Inception` to the field `entrySource` (so this is where the self relation option comes into play)
5. Close the live preview and save
6. **Result:** The `entrySource` field is empty, despite the fact that it wasn’t a second ago
7. Add the entry `Inception` to the `entrySource` field _without using the live preview_
8. **Result:** `entrySource` now holds the correct value as expected

This only happens if a self related entry was selected and only when it was selected through the live preview.

If you selected any other page, everything would work as expected.

So this is kind of an edge case, but it confused people and me too.

### Additional info

- Craft version: Craft CMS 3.4.27
- PHP version: 7.1.12
- Database driver & version: 5.6.38
- Plugins & versions: Quite a few, but I guess this has nothing to do with it as I was able to reproduce the behavior in two different projects.

**Comment by brandonkelly** [comment]
I’m not able to reproduce this, and I have no idea how it could happen. Are you able to reliably reproduce it? If so please send your composer.json & composer.lock files, plus a database backup, over to support@craftcms.com and we can look into it from there.

**Comment by medoingthings** [comment]
I digged a little further and couldn’t reproduce this in a fresh install either. It seems like the issue is related to the Neo plugin, as the field where I noticed the glitch first, was inside a Neo field. But I’m sure I tried it outside of a Neo field once and the behavior stayed the same, even though I can’t reproduce it now.

The Neo field related issue can be reproduced and I’ve send composer files and a database dump to support@craftcms.com. Even though I’m not sure if you are willing to spend time on this if it was related to Neo.

Cheers,
Mark

**Comment by brandonkelly** [comment]
Thanks. If you can reliably reproduce with Neo, please report over at https://github.com/spicywebau/craft-neo/issues.

**Comment by ttempleton** [comment]
I've reproduced this on the Happy Lager demo doing the following:

- Updated to 3.4.28.1 through the control panel
- Created an entry field which allows self-relation, and put it on the Homepage
- Opened the Homepage edit page, immediately saved as draft
- Added the Homepage entry to the new field and published changes
- The new field was empty

**Comment by brandonkelly** [comment]
This ended up being the same root issue as #6344, which is now fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.4.29 is out now with this fix.
