### ISSUE TITLE
[GQL]: transform directive does not respect generateTransformsBeforePageLoad 

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#6387]
The GQL api controller overrides the `generateTransformsBeforePageLoad` config setting, forcing it to `true`: https://github.com/craftcms/cms/blob/develop/src/controllers/GraphqlController.php#L116

So, to prevent it from generating, you _have_ to pass `immediate: false`.

In my case, I'm using a plugin to do image transforms off-premise via `Assets::EVENT_GET_ASSET_URL`, so I really NEVER want Craft to generate images. Without passing `immediate: false`, all my GQL requests timed out because it was trying to generate tons to transforms.

I would say GQL should either respect `generateTransformsBeforePageLoad`, or introduce a new setting that it did use (eg `generateTransformsBeforeGqlResponse`).

### Additional info
- Craft version: 3.5-beta.3

**Comment by andris-sevcenko** [comment]
Related: https://github.com/craftcms/cms/issues/5553

**Comment by brandonkelly** [comment]
This is currently working as expected, per #5553, and also consistent with the Element API plugin:

https://github.com/craftcms/element-api/blob/33da444d49950e5adc7aaa3b8e5b917993e6a40b/src/controllers/DefaultController.php#L119-L120

Will relabel this as an enhancement request.

**Comment by brandonkelly** [comment]
Closing this in favor of #6597.
