### ISSUE TITLE
Allow default for `Use this field’s values as search keywords?`

### ISSUE THREAD

**Issue by ryanpcmcquen** [craftcms/cms#6390]
Would love to see a configurable default for this field:

<img width="337" alt="Screen Shot 2020-07-15 at 1 21 25 PM" src="https://user-images.githubusercontent.com/772937/87592153-3c7a4580-c69e-11ea-9376-427e74761582.png">

We almost always disable it due to the performance hit, but it becomes a chore when creating a lot of new fields.

**Comment by ryanpcmcquen** [comment]
Relevant request:
https://craftcms.stackexchange.com/questions/30889/uncheck-use-this-field-s-values-as-search-keywords-by-default

**Comment by brandonkelly** [comment]
Leaving it unchecked is probably a better default choice, so just made that change for Craft 3.5.
