### ISSUE TITLE
Unable to sort categories using reorder icon

### ISSUE THREAD

**Issue by tonyespley-pa** [craftcms/cms#6392]
### Description

For a category when reordering it a message "A server error has occurred" is shown and the category order does not change.

### Steps to reproduce

1. Load up Admin ui (i.e. mysite/admin) and login
2. Go to categories
3. Select a category
4. Drag a reorder icon to an alternative order. 
5.  A message "A server error has occurred" is shown.

This is intermittent after about 30 tries it did work once but then continues to fail.  We have a production and development environment and both behave the same - we recently upgrade to Craft 3.4.27. 

### Additional info

- Craft version: Craft Pro 3.4.27
- PHP version:7.4.3
- Database driver & version:MySQL 5.7.25
- Plugins & versions:
Cookie Consent Banner	1.2.6
Feed Me	4.2.3
Fetch	1.3.0
Field Manager	2.1.6
Google Cloud Storage	1.4.0
Redactor	2.6.1
SEO	3.6.6
Tags	1.0.7

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Couple things to try:

Try running this command from your terminal:

```sh
./craft utils/repair/category-group-structure <categoryGroupHandle>
```

That will look for any problems with the structure of your category group, and stitch it back together.

If you’re still getting the error, then clear out your `storage/logs/` folder, then recreate the error, then open `storage/logs/web.log` in a text editor and search for `[error]`. Then please post the full error report including its stack trace here.

**Comment by tonyespley-pa** [comment]
@brandonkelly - thankyou or getting back to me so quickly.  We have resolved the issue - looking in the logs showed an authentication error.  We have multiple nodes running Craft with a load balancer in front of them.  We add the path /index.php?p=admin/* to our sticky persistence rules (we already had /admin) - otherwise when moving the category n the UI another node could be hit without the current users session.  

Cheers again and thank you for the amazing software we love it!
