### ISSUE TITLE
Ability to set lightswitch value to an environment variable

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#6403]
### Description

It would be great if there was some way to easily include a lightswitch input that has the ability to be set to a boolean-like environment variable. Admittedly, I'm having a hard time imagining what this UI would look like, but I think it's an important feature when project config makes plugin settings inaccessible. The most obvious use-case is for "dev mode" type lightswitches.

**Comment by brandonkelly** [comment]
I’m not sure I’m following… can you give me a more concrete example?

**Comment by Mosnar** [comment]
Sure - here are a couple of examples:

From the AvaTax plugin (note, using a config file to override these settings, ultimately achieving what I'm looking for)
![image](https://user-images.githubusercontent.com/3810939/87837850-01753f00-c863-11ea-9417-cd6674be0a60.png)

From a Commerce Gateway:
![image](https://user-images.githubusercontent.com/3810939/87837918-426d5380-c863-11ea-8768-1862570e135b.png)

In non-production environments, the gateway uses keys for a sandbox environment, but it only works if developer mode is enabled via the lightswitch.

The work-around is to do what the AvaTax plugin does, which is allow for overriding via a config file. That feels a little inconsistent/antiquated to me, since we have the ability to enter environment variables all over the control panel now.

**Comment by nettum** [comment]
This could also be useful for other fieldtypes.
E.g. if you want different email settings between envs in craft and using project config / allowAdminChanges.
All text fields can be set to env variables in the UI, but not the checkbox (useAuthentication) an the dropdowns (transport and encryption).
