### ISSUE TITLE
GraphQL querying entries for sites:"*" isn't working

### ISSUE THREAD

**Issue by e-roc** [craftcms/cms#6405]
### Description

When I use the sites wildcard  in the GraphQL Explorer, it will return entries for all sites correctly. In this case :

*My Query:* `entries(siteId: "*", id:"24621")`

*Result:*
```
{
  "data": {
    "entries": [
      {
        "id": "24621",
        "siteId": 1,
        "title": "Site 1 - title"
      },
      {
        "id": "24621",
        "siteId": 2,
        "title": "Site 2 - title"
      }
    ]
  }
}

```
However when I run the same graphQL query from my headless site `entries(siteId: "*", id:"24621")` , the return result is the same entry repeated:

```
{
  "data": {
    "entries": [
      {
        "id": "24621",
        "siteId": 1,
        "title": "Site 1 - title"
      },
      {
        "id": "24621",
        "siteId": 1,
        "title": "Site 1 - title"
      }
    ]
  }
}
```
I also tried `entries(siteId: "1,2", id:"24621")` and I get the same result -- works in graphql explorer but not from public endpoint.

### Steps to reproduce

1. Run a GraphQL query for a multisite setup with `sites: "*"` set for an entry outside of the admin GraphQL explorer

### Additional info

- Craft version: 3.4.28.1
- PHP version:7.1.33
- Database driver & version: MySQL
- Plugins & versions: using React Apollo

**Comment by andris-sevcenko** [comment]
What happens if you specifically request and set `siteId` to be `2`?

**Comment by e-roc** [comment]
Setting siteID to 2 returns the correct entry. I figured out that the issue is happening only with apollo requests, when the id is specified because the ID is the same for both entries, and I guess it expects the id to be unique. If I alias the id as entryId in the request, it works correctly.

**Comment by andris-sevcenko** [comment]
Hmm. Maybe it's worth setting the `id` type to `Int`, as opposed to `ID` that it is now. Just not sure yet about implications for existing implementations, yet.

**Comment by brandonkelly** [comment]
Looks like the same issue described at https://kamranicus.com/posts/2018-03-06-graphql-apollo-object-caching#non-idempotent-object-caching. Basically Apollo by default is going to cache all objects that contain an `id` or `_id` property (doesn’t look like the type is factored in). The easiest way to work around it is to alias the `id` as something else, like `entry_id`.

Also looks like you can customize Apollo’s cache key generation function, but that would be a bit trickier: https://github.com/apollographql/react-apollo/issues/1558#issuecomment-358364143
