### ISSUE TITLE
[GQL Mutations] Entry Author Id is required…make default author a setting?

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#6411]
Entry mutations that don't pass `authorId` will return an error, as it is required.

It thought maybe this could be an opportunity to have a "default author" setting in each GQL schema, similar to how Guest Entries does.

That said, I can't remember where Craft has landed on the possibility of not requiring an author, as it presents other issues, e.g. when importing, etc.

**Comment by brandonkelly** [comment]
I don’t think this is technically possible, since section & schema settings are stored in the project config, but users are not.

**Comment by andris-sevcenko** [comment]
Brandon is right here - user ids are content and, as such, cannot be transferred by project config, which makes storing them on the schema or anywhere else in there a highly volatile ordeal.

My recommendation here (as you have [already done](https://github.com/craftcms/cms/issues/6398#issuecomment-661136684)), would be to set the author ID using a mutation event.

**Comment by timkelty** [comment]
👍
