### ISSUE TITLE
On 'random' times when clicking on an entry to edit it the CMS switches to the dashboard instead

### ISSUE THREAD

**Issue by Friksel** [craftcms/cms#6414]
### Description

This happens a lot without any visible or obvious logical reason: when clicking on an entry in an entries list in the CP sometimes 'randomly' the control panel doesn't loads the edit page for that entry, but the dashboard instead.
It has nothing to do with timeouts or whatever and I'm sure nothing is, at least as we can tell by the interface, loading.
No error message is shown when this happens. This gives a very unstable feeling to the CP and can't call it else then frustrating as it happens a lot and doesn't make any sense to me.

### Steps to reproduce

Difficult to tell as it seems to happen at random times, but for example: 
1. CP --> Entries (--> Search for an item) --> Click on an item in the search results
2. Most of the times CP switches to the edit screen for that entry, but sometimes it just choses to switch to the dashboard instead without any logical reason to do so. Doing it another time after that suddenly it works (or again it fails, random)

PLEASE!! Look at these kinds of nasty issues (there are more strange issues like this) as this makes the CP so unreliable and I'd rather not explain customers about these weird kind of things and feel ashamed of advising this CMS. Believe me, I'd much rather like to be an advocate for your CMS, which looks great by interface and structure and I happen to like a lot for everything else. But these kind of things really should not happen!!

Also take a look at the other issue I just opened, which might be related:
https://github.com/craftcms/cms/issues/6415

### Additional info

- Craft version: 3.4.28.1
- PHP version: 7.1.16
- Database driver & version: MariaDb 10.4.10

**Comment by brandonkelly** [comment]
Entry links on entry index pages are just basic `<a>` tags, without any sort of JS interaction going on when clicked, so no idea how this could happen, and I don’t believe we’ve ever heard of anything like this before.

Do you have any plugins/modules installed that could be interfering?

**Comment by brandonkelly** [comment]
Might be something environmental, as well. Please send your web server logs into support@craftcms.com and we can take a look.

**Comment by Friksel** [comment]
Another blame to the environment instead of fixing the issues. I'm done with Craft.

I put my reaction here: https://github.com/craftcms/cms/issues/6434#issuecomment-663824974

**Comment by brandonkelly** [comment]
Closing for same general reasons as https://github.com/craftcms/cms/issues/6434#issuecomment-663850522. In this case my money would be on module interference, so gaining access to your environment would likely be necessary for us to look into it.
