### ISSUE TITLE
On 'Random' Times Craft shows an empty entry list. Only to show the list after a refresh

### ISSUE THREAD

**Issue by Friksel** [craftcms/cms#6415]
### Description
This looks like an ajax issue to me as Craft shows a loading icon in an entry list to indicate it's loading the entries to display in the list. But some times, for reasons that seem completely illogical to me, the list just doesn't load and stays empty after loading.
When we than refresh the page on the browser suddenly the list DOES load. This feels pretty unreliable.

It feels like this could be related to something is refreshing before loading is done or something. It only seems to happen here on dev-environment, which is slower than staging environment here. I don't believe I've seen this on the faster staging-environment (not shure though), so it might be an issue related to speed/timing. But eventhough the dev-environment is slower, it's not that slow and it's not running out of php timings.

### Steps to reproduce
Totally unclear when this happens and on what places it can occur, but it seems to happen on for example entry lists like the one on CP --> Entries
1. CP --> Entries
2. Wait 'till the loading icon dissapears. Most times the list will show entry-items, but sometimes it just doesn't load the items.
3. If items don't show; hard-refresh the page with a browser refresh

Also take a look at the other issue I just opened, which might be related:
https://github.com/craftcms/cms/issues/6415

### Additional info

- Craft version: 3.4.28.1
- PHP version: 7.1.16
- Database driver & version: MariaDb 10.4.10

**Comment by brandonkelly** [comment]
We haven’t seen this behavior ourselves. Are you interacting with the page at all leading up to this, or does it happen on initial page load, with no interaction?

Also please list any plugins / custom modules you are running, as they could be interfering as well.

**Comment by brandonkelly** [comment]
Couple other questions:

- Are you getting any JS errors when this happens?
- How many entries do you have?

**Comment by Friksel** [comment]
Again; questions questions to a customer, instead of even try to fix the nasty issues in basic code and test yourself. What does it matter how many entries there are? The software should just work with any amount of entries and should be tested first to begin with. I'm done with Craft.

I put my reaction here: https://github.com/craftcms/cms/issues/6434#issuecomment-663824974

**Comment by brandonkelly** [comment]
OK, going to close because you don’t seem willing to help, but we’re more than happy to pick this up again if you are!
