### ISSUE TITLE
[3.5] Incorrect sidebar styling for User settings

### ISSUE THREAD

**Issue by NixonGit** [craftcms/cms#6416]
Running Craft 3.5.x-dev and the styling for the user settings sidebar is a little off. All the other settings pages look fine.

![settings-users-sidebar](https://user-images.githubusercontent.com/17004710/88049491-26acca80-cb4d-11ea-9f59-95ba2aba4be2.png)

**Comment by evanwarner** [comment]
The same problem exists on the Assets settings page.

**Comment by brandonkelly** [comment]
Do you have any custom CP CSS atyles that could be affecting this? Or maybe try clearing browser caches?

**Comment by evanwarner** [comment]
Looks like the broken sidebar has a double level of `nav` elements. If I take the extra away it resolves the issue.

Broken sidebar:
```html
<div id="sidebar" class="sidebar">
  <nav>
    <nav><!-- this is the problem -->
      <ul>
        <li><a class="sel" href="http://example.local/manage/settings/assets">Volumes</a></li>
      </ul>
    </nav>
  </nav>
</div>
```

**Comment by brandonkelly** [comment]
Doh! Thanks for pointing that out. Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5 RC2 is out now with that fix.
