### ISSUE TITLE
3.5 RC1 - Basic http authentication on the server breaks the application.

### ISSUE THREAD

**Issue by rayboyd** [craftcms/cms#6421]
### Description

After upgrading from 3.5-beta3 we can no longer log into any instance that has basic authentication on the server. The application is trying to authenticate with the credentials for the server.

I believe the issue is related to this commit, which makes an assumption in regards to what information is in the request. https://github.com/craftcms/cms/commit/1e736e893b0b8801f60b47596fa50260d08c1f73

### Steps to reproduce

1. Add basic http authentication to the server on a Craft 3.5-RC1 install

### Additional info

- Craft version: Craft 3.5-RC1

**Comment by brandonkelly** [comment]
Thanks for pointing that out! I’ve just added a new `enableBasicHttpAuth` config setting, which is _disabled_ by default, so you have to explicitly enable that before Craft will start checking for basic auth credentials.
To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "3.5.x-dev",
  "...": "..."
}
```

Then run `composer update`.

**Comment by rayboyd** [comment]
Thank you

**Comment by brandonkelly** [comment]
Craft 3.5 RC2 is out now with that change.

**Comment by rayboyd2018** [comment]
Awesome, thanks for this.
