### ISSUE TITLE
3.5: narrow field layouts use incorrect width

### ISSUE THREAD

**Issue by evanwarner** [craftcms/cms#6423]
Between 500 and 1425px, fields set to layout at 25% or 50% width use incorrect width styles, resulting in fields that don't quite reach the right edge:

![craft-3_5-field-align](https://user-images.githubusercontent.com/6453842/88122458-84f1a180-cb7d-11ea-83c9-4f6326d51d4b.png)

`width: calc(50% - 24px);`
seems like it should be
`width: calc(50% - 14px);`

### Steps to reproduce

1. Lay out two columns next to each other at 50/50
2. Size the browser between 500 and 1425px

### Additional info

- Craft version: 3.5.0-RC1.1

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5 RC2 is out now with that fix.
