### ISSUE TITLE
3.5-RC1.1 - Windows - Upgrading Craft to pro delete all project-config files (2nd level)

### ISSUE THREAD

**Issue by smcyr** [craftcms/cms#6425]
### Description

On a brand new Craft 3.5-RC1.1 installation, upgrade from solo to pro. The `.yaml` inside those folders are deleted:
```
config/project/fieldGroups
config/project/siteGroups
config/project/sites
```
Then, after that, if I try to create a field, it creates the field yaml but returns a 404 (/admin/settings/fields/1) probably because the field group doesn't exist anymore.

I think the problem arises from `_getConfigurationFromYaml()` because in the loop, it expects a forward slash but there are only backward slashs in the paths (line `1263` and `1264` in `ProjectConfig.php`)

### Additional info

- Craft version: 3.5-RC1.1
- PHP version: 7.3 with FastCGI on IIS

**Comment by smcyr** [comment]
I tried changing the 2 forward slashs on `1263` and `1264` in `ProjectConfig.php` for `DIRECTORY_SEPARATOR` and it seemed to fix my problems!

**Comment by angrybrad** [comment]
Thanks... getting late here, but will look at this tomorrow!

**Comment by angrybrad** [comment]
Thanks... just pushed up a fix for this that will be included in the next release (which will be soon)!

**Comment by brandonkelly** [comment]
Craft 3.5 RC2 is out now with that fix.

**Comment by smcyr** [comment]
Thank you, it works great now, I upgraded a 3.4 site and it went perfectly. The additions are so nice!!!
