### ISSUE TITLE
[3.5] Generate transforms layout/html encoding bug

### ISSUE THREAD

**Issue by Jan10** [craftcms/cms#6427]
In admin/utilities/generate-transforms-utility

![Markup on 2020-07-22 at 09:19:53](https://user-images.githubusercontent.com/192557/88146790-9928b380-cbfc-11ea-8a83-da31882aa27d.png)

### Additional info

- Craft version: 3.5.0-RC1.1

**Comment by andris-sevcenko** [comment]
Thanks for reporting!

However, that utility is provided by Imager X. Please raise an issue with [the author of that plugin](https://github.com/spacecatninja/craft-imager-x).
