### ISSUE TITLE
3.5-RC1.1 - Codeception testsuite won't run with the new folder based project config

### ISSUE THREAD

**Issue by hjvvoorthuijsen** [craftcms/cms#6428]
### Description

We used the project config file for our project config. In 3.5 this became the default but our codeception testsuite now failes.

The output of codeception:

![image](https://user-images.githubusercontent.com/42176203/88151918-95e4f600-cc03-11ea-84c5-d0515c8b899d.png)

Our `_bootstrap.php` is doing nothings special. it fails on `TestSetup::configureCraft();`

### Steps to reproduce

1. Have the project config enabled
2. Run `codecept run unit --verbose`

### Additional info

- Craft version: 3.5-RC1.1
- PHP version: 7.4.2
- Database driver & version: PostgreSQL 12.2

**Comment by angrybrad** [comment]
Fixed this for the next release, updated the [knowledge base article](https://craftcms.com/knowledge-base/upgrading-to-craft-3-5) for updating to 3.5 as well as the [3.5 docs](https://github.com/craftcms/docs/blob/3.5/testing/framework/config-options.md#projectconfig) for testing and Project Config.

**Comment by brandonkelly** [comment]
Craft 3.5 RC3 is out now with the fix.
