### ISSUE TITLE
sortOrder (in project config) does not get modified upon removing entry types

### ISSUE THREAD

**Issue by architchandra** [craftcms/cms#6431]
### Description
When I remove an entry type from the control panel for a section, the `sortOrder` value does not get modified. Furthermore, if I add another entry type, its `sortOrder` takes the value higher than the number of entry types that previously existed (as if it's being picked from a database table). This get reset only upon changing the order of the entry types from the control panel.

### Steps to reproduce
1. Create a section with 3 entry types
2. Delete the first and last entry types from the control panel
3. Check the value of `sortOrder` for the entry type that still exists
4. Add a new entry type and notice its `sortOrder` value

### Additional info
- Craft version: 3.4.27
- PHP version: 7.2.23
- Database driver & version: Ver 14.14 Distrib 5.7.28, for macos10.14 (x86_64) using  EditLine wrapper

**Comment by brandonkelly** [comment]
It doesn’t really matter what values are used for `sortOrder`; they are only used by an `ORDER BY` SQL clause. So as long as they are headed in the right direction, they will work as intended.

I just tweaked it slightly, so soft-deleted entry types are not included when determining the current max sort order, when saving a new entry type. But beyond that it’s working as expected.
