### ISSUE TITLE
[3.5.0-RC1.1] Migration error generated by m200625_131100_move_entrytypes_to_top_project_config.php if no Sections exist

### ISSUE THREAD

**Issue by ademers** [craftcms/cms#6433]
### Description
Updating from a new installation of 3.4.29.1 to 3.5.0-RC1.1 generates migration error when running `m200625_131100_move_entrytypes_to_top_project_config.php` because no Sections exist yet.

Of course, an existing functional project would actually already contain at least one Section.

### Steps to reproduce
 
1. Create new 3.4.29.1 project via `composer create-project craftcms/craft`
2. Edit `composer.json` to contain `"craftcms/cms": "^3.5.0-RC1.1",`
3. Add `config/project` dir as per 3.5 update guide
3. Run `composer update`
4. See migration error related to [line 29](https://github.com/craftcms/cms/blob/a465272af54b83a88d64d75454d28a1ddb574171/src/migrations/m200625_131100_move_entrytypes_to_top_project_config.php#L29) in `m200625_131100_move_entrytypes_to_top_project_config.php`

### Additional info

I added conditional above [line 29](https://github.com/craftcms/cms/blob/a465272af54b83a88d64d75454d28a1ddb574171/src/migrations/m200625_131100_move_entrytypes_to_top_project_config.php#L29) to check if Sections exist and was successfully able to update to 3.5.0 RC1.1
```php
// For each section, remove the entry type for separate storage.
// Check if there are Sections
if ($sections) {
    foreach ($sections as $uid => &$section) {
        if (empty($section['entryTypes'])) {
            continue;
        }

        foreach ($section['entryTypes'] as &$entryType) {
            $entryType['section'] = $uid;
            ksort($entryType);
        }

        $entryTypes += $section['entryTypes'];
        unset($section['entryTypes']);
    }
}
```

- Craft version: 3.5.0 RC1.1
- PHP version: 7.2
- Database driver & version: mysql
- Plugins & versions: N/A

**Comment by andris-sevcenko** [comment]
Thanks for reporting that! Turna our it has already [been fixed](https://github.com/craftcms/cms/commit/2a32bb159fa501c5c1b8306e4b716595139f046e) for the next release!
