### ISSUE TITLE
Cannot perform element query in config file

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#6439]
I wanted to perform element query in `config/general.php` file in order to set `loginPath` value to login page URI:

```
'loginPath' => \craft\elements\Entry::find()->section('userLogin')->one()->uri,
```

However doing that, causes this error:

```
( ! ) Fatal error: Uncaught Error: Class 'Yii' not found in C:\xampp\htdocs\jaka-karma\vendor\yiisoft\yii2\base\BaseObject.php on line 107
```

**Comment by andris-sevcenko** [comment]
Craft is not initialized at that point yet, so it won't be possible to use much of Craft's functionality. Also, this would add overhead to _every_ request made to the site.

Why wouldn't you set it to an environment variable? This hardly seems like something that should be changed by content editors.

**Comment by piotrpog** [comment]
@andris-sevcenko 
Thanks for reply.
"Why wouldn't you set it to an environment variable? This hardly seems like something that should be changed by content editors."
One scenario is a page with multiple languages, where login url is different in each language.

**Comment by andris-sevcenko** [comment]
@piotrpog How are you figuring out which site you are using? Usually, that's accomplished by each site having its own `index.php` file. You can just use `putenv("LOGIN_URI=" . '<login uri specific for this site>');`

Or are you setting up your multisite in a different manner?
