### ISSUE TITLE
[3.5-RC1.1] Guzzle config issue

### ISSUE THREAD

**Issue by JeanLucEsser** [craftcms/cms#6440]
### Description

I'm not 100% sure but it looks like my proxy guzzle config which was working in beta.3 is not working anymore in RC1.1. I'm just posting this to ask if on the top of your head it might be something that changed on your side or if I should look on my side for something that I inadvertently changed.

For the record my Guzzle.php config is pretty straight forward:
```
<?php

return [
  '*' => [
    'proxy' => [
      'http' =>
        'http://user:pass@proxy.mydomain.fr:8080',
      'https' =>
        'http://user:pass@proxy.mydomain.fr:8080',
      'no' => ['.mydomain.fr'],
    ],
  ],
  'dev' => [
    'proxy' => [
      'http' => null,
      'https' => null,
      'no' => [],
    ],
  ],
];
```

### Additional info

- Craft version: 3.5-RC1.1

**Comment by brandonkelly** [comment]
Nothing changed recently with Guzzle. Are you getting any errors?

**Comment by JeanLucEsser** [comment]
No that's weird but I've been able to confirm that guzzle config is still being parsed. So it is probably happening on my end (default Craft News on Dashboard and Plugin Store won't load on the proxied environment).

I'll close this for now. Will report back if I find anything.
