### ISSUE TITLE
[3.5-RC1.1] "Let each entry choose which sites..." sporadic loss of sites/matrixblocks when publishing/creating drafts

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#6441]
### Description

Playing around with the new propagation method "Let each entry choose which sites it should be saved to" i am sometimes experiencing that site specific entries are lost and matrix blocks are not properly propagated. Unfortunately i can't reproduce every case i've seen, but there is one that is seemingly consistently reproducable:

### Steps to reproduce

Site Settings: 

![image](https://user-images.githubusercontent.com/60010597/88282716-5e9d4480-ccea-11ea-843d-c85af7d3fc1b.png)

Matrix field set to "Save blocks to all sites the owner element is saved in" with text field "Translate for each language"

1. Current entry with sites berlin_de and berlin_en and a matrix block
2. Create Draft
3. Add site berlin_tr and switch to that site
4. ==> No matrix blocks are propagated to the new site
5. Edit some fields and publish
6. ==> site berlin_tr is gone.

Also:
1.  Current entry with sites berlin_de, berlin_en, berlin_tr
2.  Edit, select current berlin_en
3. Create draft, refresh page
4. ==> site berlin_tr is gone
(However, if berlin_tr is selected before creating the draft all sites persist)

### Additional info

- Craft version: 3.5.x-dev 549b73e6acb508a882a93609dc1932d5cf765a38
- PHP version: 7.4.7
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just got it fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5 RC3 is out now with the fix.

**Comment by wsydney76** [comment]
@brandonkelly Thanks for the fix! Couldn't see any loss now, but it seems things can go wrong when done in a wrong sequence.

Example (sites settings from above):

Entry exists in berlin_de and berlin_en with translated content

a) select berlin_de, add new site munich_de => matrix blocks are propagated, field correctly has the german content
b) select berlin_en, add new site munich_de => matrix blocks are propagated, but field has english content. (so have other translateble fields too)

Looks like content is always propagated from the currently selected site and the fields translation settings are not respected.

Shoudn't be a problem in 'one-dimensional' site settings (german,english,italian/translated by language OR berlin,munich,kleinfinstenich/not translated), but in 'multi-dimensional' settings, unless you enforce a very strict workflow (first add sites, then add content)

(add translate by site group to the mix :-) )

**Comment by brandonkelly** [comment]
@wsydney76 FYI I’ve reposted your last comment as a new issue: #6455
