### ISSUE TITLE
Return index of structure item and support in queries

### ISSUE THREAD

**Issue by goellner** [craftcms/cms#6442]
### Description

It would be good to have a field for the index of a structured entry, currently the only way of getting the index is by taking `lft` and divide it by 2. 

Disclaimer: I am using Craft Headless with GraphQL, but couldn't find anything with Twig, only hacking around with the loop index.

Further it would be good to be able to query entries by this structure index. 

Example: 

```
query StructuredEntry {
  entry(section: "team", structureIndex: "4") {
    title
		url
		structureIndex
  }
}
```

**Comment by brandonkelly** [comment]
Entries don’t actually have a specific index within the structure, and dividing `lft` by two will only give you an accurate index up until you start getting into nested entries.
