### ISSUE TITLE
custom Craft `id` Twig function fails to work

### ISSUE THREAD

**Issue by adrienne** [craftcms/cms#6445]
### Description

The [custom Craft Twig function `id`](https://docs.craftcms.com/v3/dev/filters.html#id) just doesn't seem to work at all.

### Steps to reproduce

1. Try something like `{{ 'This is a Test'|id }}`
2. We expect the result to be `this-is-a-test`, but instead the input is simply returned without any changes.

### Additional info

- Craft version: Craft Pro 3.4.28.1
- PHP version: 7.3.20

**Comment by brianjhanson** [comment]
It sounds like you actually want the [`kebab`](https://docs.craftcms.com/v3/dev/filters.html#kebab) filter. The `id` filter only replaces `[`, `]` and `\` with `-` if I'm reading the [regex right](https://github.com/craftcms/cms/blob/master/src/web/View.php#L1489)

**Comment by brandonkelly** [comment]
I think @adrienne’s expectations are correct given the documentation. That code has been rewritten for Craft 3.5, and just verified it works as expected there. 🎉
