### ISSUE TITLE
Debug bar logo displayed at the wrong size

### ISSUE THREAD

**Issue by NixonGit** [craftcms/cms#6447]
### Description

The Craft logo in the debug bar displays at the wrong size when using a global responsive image reset on the frontend.

```css
img {
  width: 100%
}
```

![debug-toolbar](https://user-images.githubusercontent.com/17004710/88374781-42ed7900-cd92-11ea-91b5-2426c41e38f5.png)

This can be fixed on the user side by switching to `max-width: 100%` but I think it's common enough to use `width: 100%`. It could also be fixed on Yii's side by setting the width and height to 30px in the CSS.

I think the root issue is the data encoded SVG Craft is using. It doesn't look to set `width`, `height` or `viewbox` so I think the browser default sizing for SVG is stepping in? In my tests changing to use a true 30x30px image fixes things so assume reencoding the inline SVG with `width`, `height` and `viewbox` attributes should fix things.

I can't find the "C" by itself in your brand assets to PR.

### Steps to reproduce

1. Add responsive image reset to frontend.
2. Enable debug toolbar on frontend.
3. Go to frontend.

### Additional info

- Craft version: Craft Pro 3.5.0-RC2
- PHP version: 7.4.2

**Comment by brandonkelly** [comment]
I changed the SVG size to 30x30px, but didn’t help:

<img width="175" alt="The Craft logo within the debug toolbar" src="https://user-images.githubusercontent.com/47792/88400755-a1f4c300-cd7d-11ea-9603-80572837d2be.png">

Just submitted a PR to yii2-debug that sets the logo size from CSS, which does fix it: https://github.com/yiisoft/yii2-debug/pull/435

**Comment by brandonkelly** [comment]
yii2-debug 2.1.14 is out now with that fix. Run `composer update` to get it.
