### ISSUE TITLE
3.5 Remove the div wrapper from custom field layout templates

### ISSUE THREAD

**Issue by evanwarner** [craftcms/cms#6454]
Any template we place into our field layouts gets wrapped in a naked `<div>` element, which precludes us from being able to create a template that takes part in the column layout.

For example, my template ends up like so:
```html
<div id="fields-aRealField-field" class="width-50 field" data-type="craft\fields\Assets">...</div>

<div><!-- <<<< can we remove this? -->
  <div class="width-50 field"> <!-- I want this to be 50/50 with the above field -->
    My template code
  </div>
</div>
```

**Comment by evanwarner** [comment]
Or perhaps an even better idea is to add the column layout picker to template elements.

**Comment by brandonkelly** [comment]
Just added a width selector to Template elements, for the next release.

**Comment by evanwarner** [comment]
Thank you!!!

Also 👀 the timestamp on that commit...couldn't sleep?

**Comment by brandonkelly** [comment]
Hah… on vacation so I have to get creative with working hours :)

**Comment by brandonkelly** [comment]
Craft 3.5 RC4 is out now with that change.
