### ISSUE TITLE
[3.5-RC3] Some broken SVGs in plugin icons

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#6457]
### Description

Some plugin icons are partially or completely missing...

<img width="362" alt="missing-icons@2x" src="https://user-images.githubusercontent.com/5309692/88467952-97c3e900-ce91-11ea-8a29-b6afad751403.png">

You can see that the Twigpack icon is missing the inner stencil, and the Smart Map icon is missing completely. If you edit the DOM and delete the `mask`, you can make the Smart Map icon reappear (albeit still partially broken).

### Steps to reproduce

1. Install Craft 3.5-RC3
2. Install Smart Map (or Twigpack)
3. Witness the broken SVG icon

### Additional info

- Craft version: Craft 3.5-RC3
- Plugins & versions: Smart Map and/or Twigpack (latest of each)

**Comment by lindseydiloreto** [comment]
After doing a bit of troubleshooting with @Mosnar, it appears that this is an issue with how the `xlink` attributes are being handled. They seem to be missing the container hash that ties it all together.

Here are the before & after comparisons (Craft 3.4 vs 3.5)...

**Smart Map**
![xlinks@2x](https://user-images.githubusercontent.com/5309692/88468103-a01d2380-ce93-11ea-8418-b09416c41ea1.png)

**Twigpack**
![xlink-2@2x](https://user-images.githubusercontent.com/5309692/88468102-9e536000-ce93-11ea-9df5-a91e114e49e6.png)

**Comment by brandonkelly** [comment]
Just got this fixed for the next release. Thanks for reporting!

**Comment by lindseydiloreto** [comment]
Looks like that did the trick, thanks @brandonkelly! 👍

**Comment by brandonkelly** [comment]
Craft 3.5 RC4 is out now with the fix.

**Comment by lindseydiloreto** [comment]
Excellent, can confirm that everything is working as intended. 👌
