### ISSUE TITLE
[3.5RC3] Can't change entry type position

### ISSUE THREAD

**Issue by daltonrooney** [craftcms/cms#6458]
### Description
The notification says that the items have been reordered, but the position doesn't save on refresh. 

![2020-07-25 17-44-30 2020-07-25 17_46_18](https://user-images.githubusercontent.com/742045/88468930-90a3d780-ce9f-11ea-9302-ecb3819b2bbe.gif)

## Additional info

- Craft version: 3.5RC3
- PHP version: 7.4

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5 RC4 is out now with the fix.
