### ISSUE TITLE
Display current username inside CP's top right "My account" menu

### ISSUE THREAD

**Issue by j-greig** [craftcms/cms#6460]
### Description
When testing user account permissions, it would be helpful to know who you're currently logged in as (without having to hover over the menu to see the alt tag, or clicking through to the My Account page itself)

Maybe something like...

```
<div class="menu" data-align="right">
	<ul>
		<li class="light" style="font-size: 10px; padding: 8px 0">{{ currentUser.getName() }}</li>
		<li><a href="{{ url('myaccount') }}">{{ 'My Account'|t('app') }}</a></li>
		<li><a href="{{ url('logout') }}">{{ "Sign out"|t('app') }}</a></li>
	</ul>
</div>
```

![image](https://user-images.githubusercontent.com/616194/88474543-74477f80-cf1f-11ea-8af6-73b1208692a5.png)

Displaying the current username in the account dropdown is also an established design pattern — see examples below.

![image](https://user-images.githubusercontent.com/616194/88474503-fbe0be80-cf1e-11ea-9477-2c63a884fac1.png)
----
![image](https://user-images.githubusercontent.com/616194/88474506-0438f980-cf1f-11ea-809d-3458578d141f.png)

Thanks for considering my request :)

**Comment by brandonkelly** [comment]
Added for the next 3.5 release!

<img width="258" alt="An account menu that displays the logged in user’s username and email" src="https://user-images.githubusercontent.com/47792/88485009-bc6aa000-cf27-11ea-834c-ab923f22c6d3.png">

**Comment by j-greig** [comment]
That was quick ⚡️

**Comment by brandonkelly** [comment]
Craft 3.5 RC4 is out now with that change.
