### ISSUE TITLE
Add links to edit fields when displaying field handle

### ISSUE THREAD

**Issue by wbrowar** [craftcms/cms#6461]
### Description

The [CP Field Inspect](https://github.com/mmikkel/CpFieldInspect-Craft) plugin has been a  _very_ useful tool for templating and working on custom modules because of how quickly you can look up field handles right on element edit pages. It's also very handy when content modeling because you can start on an edit page, click a gear near the field title to go to the field’s settings page, then upon save you come back to the edit page you started on.

I really like the new 3.5 feature that displays the handle when holding down alt/option and it would be great if a gear could appear (for Admin’s only) next to the field handle that takes you to edit the field, just like CP Field Inspect would.

Finally, the other thing CP Field Inspect does is provides a button for admins to jump to the field layout of the specific entry type or element that you're currently editing. If this were implemented, too, it would completely remove the need for CP Field Inspect, and it would be a great feature to have native to Craft.

@mmikkel – I hope you wouldn't mind getting Sherlocked. This has been a great tool for the developer experience over the years.

**Comment by mmikkel** [comment]
I’d love it if CP Field Inspect was made completely redundant.

This FR is mostly a duplicate of https://github.com/craftcms/cms/issues/6133 (except for mentioning the edit source button that Field Inspect adds, which I also think also a big improvement to the content modeling experience along with the field links). 

As I mention in a comment on 6133, the final thing worth mentioning in terms of CP Field Inspect is that the plugin makes copying field handles less awkward than w/ the core “show handles” feature.

**Comment by wbrowar** [comment]
Ah, sorry for the duplicate. I'll close this issue and put in a comment about the edit source button to reduce the amount of tickets tracking this.
