### ISSUE TITLE
3.5.0-RC3: Matrixfield with a Redactor field

### ISSUE THREAD

**Issue by kobeaerts** [craftcms/cms#6462]
### Description

I have a Matrix field with a Redactor field inside it, it fails with this error message:
`Calling unknown method: craft\redactor\Field::getField()` in `src/templates/_components/fieldtypes/Matrix/settings.html` at lines 42 and 73

### Steps to reproduce

1.
2.

### Additional info

- Craft version: 3.5.0-RC3
- PHP version: 7.4
- Database driver & version: /
- Plugins & versions: Redactor field plugin

**Comment by brandonkelly** [comment]
Hm, something’s not right – the template should not be working with the `craft\redactor\Field` object directly there.

Can you email a database backup and your Composer files over to support@craftcms.com, so we can look into it further?

**Comment by brandonkelly** [comment]
This ended up being due to Super Table, and will be fixed in Super Table 2.5.3.

**Comment by brandonkelly** [comment]
Super Table 2.5.3 is out now with a fix for this.
