### ISSUE TITLE
[3.5.0-RC3] Title bars of collapsed matrix blocks do not show content snippets

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#6468]
### Description

![image](https://user-images.githubusercontent.com/60010597/88654643-efe72f00-d0cd-11ea-9db8-f1e13cc78d87.png)

### Steps to reproduce

1. Collapse matrix block
2.

### Additional info

- Craft version: 3.5.0-RC3
- PHP version: 7.4.7
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5 RC4 is out now with the fix.
