### ISSUE TITLE
Disabled entry is shown instead of 404

### ISSUE THREAD

**Issue by g1un** [craftcms/cms#6469]
### Description
Disabled entry is shown instead of 404
https://monosnap.com/file/l8tgvr5Fxpw0OXPbpcwiI57JmZjL51

### Steps to reproduce

1. Disable any entry
2. Open disabled entry page
3. See disabled page showing

### Additional info

- Craft version: Craft Solo 3.4.19.1
- PHP version: 7.2.24
- Database driver & version: MySQL 5.7.26
- Plugins & versions: 
  - Redactor 2.6.1
  - XML Sitemap 1.2.0

**Comment by brandonkelly** [comment]
Disabled entries won’t show up on the front end by default, unless you are overriding the `status` param or calling `anyStatus()` on an element query.

Besides that, could be a caching issue. I verified that disabling entries is definitely preventing their main URLs from working.
