### ISSUE TITLE
[3.5.0-RC3] Field layout issues with headings and custom field widths

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#6470]
### Description

The field layout breaks if a Heading UI element is added as the first element in a tab, and the heading is immediately followed by multiple fields with custom widths.

![image](https://user-images.githubusercontent.com/298510/88656608-ddbac000-d0d0-11ea-9ef5-fda2a79f84aa.png)  

![image](https://user-images.githubusercontent.com/298510/88657951-f330e980-d0d2-11ea-8df5-d8c827a130f8.png)

### Steps to reproduce

1. Add a Heading UI element to a field layout tab
2. Add two fields with 50% widths immediately after the heading

### Additional info

Only tested on Chrome 83.0.4103.116 (MacOS)

- Craft version: 3.5.0-RC3
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting! We just released Craft 3.5 RC4 with a fix for this.
