### ISSUE TITLE
[3.5.0-RC4] Calling unknown method: craft\fields\PlainText::getField()

### ISSUE THREAD

**Issue by harispepic** [craftcms/cms#6472]
### Description
When i try to edit the matrix field I get this error message:
Calling unknown method: craft\fields\PlainText::getField() in src/templates/_components/fieldtypes/Matrix/settings.html

### Additional info

- Craft version: 3.5.0-RC4
- PHP version: 7.4
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Sounds like the same issue as #6462, which ended up being due to a Super Table field (despite the template in the error message), and has been fixed for the next Super Table release – 2.5.3.

**Comment by brandonkelly** [comment]
Super Table 2.5.3 is out now with a fix for this.
