### ISSUE TITLE
Change exit() functions to exceptions in bootstrap.php for more flexible error handling?

### ISSUE THREAD

**Issue by aaronbushnell** [craftcms/cms#6475]
### Description
It looks like https://github.com/craftcms/cms/blob/master/bootstrap/bootstrap.php uses `exit()` when encountering an error with permissions and the like. One downside to this approach is that, AFAIK, it still returns a `200` status code to the browser. 

Would it be more valuable to throw an exception for these errors so the page returns a non `200` status code so that monitoring tools can infer the server is not in an OK state?

https://github.com/craftcms/cms/blob/master/bootstrap/bootstrap.php#L58
https://github.com/craftcms/cms/blob/master/bootstrap/bootstrap.php#L74
https://github.com/craftcms/cms/blob/master/bootstrap/bootstrap.php#L80
https://github.com/craftcms/cms/blob/master/bootstrap/bootstrap.php#L134

**Comment by aaronbushnell** [comment]
Or maybe there's a better way to monitor if Craft is "up" and we should use an entirely different way than simply checking for a `200` on the homepage?

**Comment by brandonkelly** [comment]
All but one of those were setting the status code to 503 on the line before. Just fixed the missing one.

**Comment by aaronbushnell** [comment]
Thanks, @brandonkelly!
