### ISSUE TITLE
[RC3.5.0-RC4] - Field Layout throwing server error

### ISSUE THREAD

**Issue by ljclark** [craftcms/cms#6476]
### Description

When trying to edit a section entry type on RC4, it's throwing a server error with the following stack trace message:

`Macro "fieldLayoutDesignerField" is not defined in template "_includes/forms". in /home/forg
e/xxxxx/vendor/craftcms/cms/src/templates/settings/sections/_entrytypes/edit.html:104`

I've nuked the vendor folder and done a fresh composer install on it but it's still throwing the same error.

### Steps to reproduce

1. Upgraded to RC5 from the latest 3.4
2. Settings > Section > Edit entry type
3. Error

### Additional info

PHP version | 7.3.15
Database driver & version | MySQL 5.7.30
Craft edition & version | Craft Pro 3.5.0-RC4
Yii version | 2.0.36

**Comment by ljclark** [comment]
I've somehow fixed this by nuking things a second time and reinstalling, which has done the trick - odd.

**Comment by brandonkelly** [comment]
Probably a caching issue. Glad reinstalling worked!
