### ISSUE TITLE
CP checkboxes not working with Matrix when editing fields in 3.5.0-RC4

### ISSUE THREAD

**Issue by howells** [craftcms/cms#6481]
### Description

With 3.5.0-RC4, I've found that checkboxes no longer work when trying to edit block types. When creating a new field, the checkboxes work but then don't when trying to edit. https://cln.sh/U7wBEE

There are no console errors.

### Steps to reproduce

1. Edit a Matrix field
2. Try to click any configuration checkboxes for a block's field

### Additional info

- Craft version: 3.5.0-RC4 (3.5.x-dev)

**Comment by brandonkelly** [comment]
Looks like this was introduced by 4f2b34cdf319afe70a703386e20deb48830d6ee1. The tagged 3.5.0-RC4 release doesn’t have this problem. Will get it fixed.

**Comment by howells** [comment]
Ah that was why I used the 3.5.x-dev branch ha, but cool thanks. 

(If the fix is simple any chance of letting me know how to quickly patch it just do I can getting working in my dev env?! No worries if it's more involved.)

**Comment by brandonkelly** [comment]
Was on the road today so couldn’t look into it until now. Just pushed up a fix to the 3.5 branch.

**Comment by howells** [comment]
@brandonkelly Ah great thanks. Not sure if this is related, but seems if an asset volume's name has square brackets in it (e.g. "Images [files]") the active checkbox won't appear to be pre-selected.

**Comment by brandonkelly** [comment]
@howells almost definitely unrelated, and most likely not a new 3.5 bug. Can you post as a new issue with more info?

**Comment by howells** [comment]
@brandonkelly sure!

**Comment by howells** [comment]
Created #6495 - it could be a weirder bug than it just containing square brackets, however
