### ISSUE TITLE
localhost:8888/admin/settings does not work

### ISSUE THREAD

**Issue by tfantina** [craftcms/cms#6483]
### Description
I've installed a few instances of Craft in the past month (both from existing projects and new installs).  I've consistently had a problem that whenever I navigate to `admin/settings` I get an error: 
```
This page isn’t working
localhost didn’t send any data.
ERR_EMPTY_RESPONSE
```

I have been unable to find any documentation on this except for [this question](https://craftcms.stackexchange.com/questions/33953/only-the-settings-page-is-broken).  Just this morning I went through a brand new install of Craft with both composer and just downloading the .zip file. Each time everything installed successfully with no hiccups but when I log into the admin panel and navigate to settings I get that error. 

### Steps to reproduce
(Unlikely to be reproducible for most otherwise, this would be a much larger issue).
1. Clean install of Craft
2. Navigate to `/admin/settings`

### Additional info

- Craft version: 3.4.30 
- PHP version: 7.4.1
- Database driver & version: MySQL  5.7.26
- Plugins & versions: none

**Comment by RickKukiela** [comment]
From the question you referneced:
"In that case, the request is likely not making it to Craft in the first place. Check your server configuration – you may have something like Suhosin installed that is interfering with the request. "

Which was sent from The man him self @brandonkelly, the creator of CraftCMS. I also concur that this sounds like a server configuration issue. These can be a pain to figure out. I googled "mamp ERR_EMPTY_RESPONSE" and found this, I hope it helps:

https://stackoverflow.com/questions/43319455/unable-to-open-up-localhost-in-chrome-using-mamp-getting-err-empty-response

**Comment by brandonkelly** [comment]
Yeah probably the same thing here – whatever the issue is, it’s going to be something weird with your environment config.

Maybe try [Craft Nitro](https://getnitro.sh/), which is our own development environment, coming out of beta very soon.

Feel free to write into support@craftcms.com if you need any further assistance with this :)
