### ISSUE TITLE
Craft::$app->users->deleteUserPhoto() does not remove photoId from user and causes issue when setting a new user photo

### ISSUE THREAD

**Issue by RickKukiela** [craftcms/cms#6491]
### Description

I have some module code that I'm porting from craft2 to craft3 and in the old code I delete the user's photo before setting the new photo (importing from gravatar but irrelevant). When I do this in craft3, setting the new user photo throws an exception here: https://github.com/craftcms/cms/blob/0f9d46a9033ed242cd90ab62a644e7b0c88c121b/src/services/Users.php#L440 because photoId is still set on the user object but since the element now has a deletedDate that is not NULL the call to `$assetsService->getAssetById($user->photoId)` returns `null` and that breaks `$assetsService->replaceAssetFile()`.

I was able to work around this by not deleting the user photo first, but I'm pretty sure the `deleteUserPhoto()` method should probably remove the photoId from the user.  

### Steps to reproduce

1. run `Craft::$app->users->deleteUserPhoto($user);` on a user.
2. attempt to set a new photo on the user: `Craft::$app->users->saveUserPhoto($filePath, $user, $filename);`

### Additional info

- Craft version: 3.4.27
- PHP version: 7.3
- Database driver & version: MariaDB 10.3
- Plugins & versions:

**Comment by andris-sevcenko** [comment]
Nice catch!

Fixed for the next 3.4 release!

**Comment by RickKukiela** [comment]
Glad I could help!
