### ISSUE TITLE
Asset volume checkbox not preselected if label contains square brackets

### ISSUE THREAD

**Issue by howells** [craftcms/cms#6495]
### Description

This is potentially a two-part bug. I have an asset volume that contains square brackets - "Images [files]" - and I've noticed that when I select this volume in an asset field, it isn't preselected when I go back to edit it (however, the change is saved and reflected in the project config). Another volume, named simple "Files", works as expected.

However things now get weird: I tried to rename the "Images [files]" volume to just "Images". The new names is reflected in the project config, asset settings CP, and everywhere else I can possibly think of, yet the old name is still shown in an Asset field's settings - https://cln.sh/REJRny

I have a volumes.php in config with just "Images" as the name, no brackets, but I've tried removing this, emptied all caches, removed Redis as a caching strategy, etc. A search for "Images [files]" returns nothing at all in any of my files or a database backup.

Not really sure how to suggest replication steps for this, it's a total mystery.

### Additional info

- Craft version: 3.5-dev

**Comment by howells** [comment]
Not sure if related but I use fortrabbit objectstorage for production, so my volumes.php looks like this:

```
<?php
$objectStorageAccess = [
    'url' => "https://" . getenv('OBJECT_STORAGE_HOST'),
    'endpoint' => "https://" . getenv('OBJECT_STORAGE_SERVER'),
    'keyId' => '$OBJECT_STORAGE_KEY',
    'secret' => '$OBJECT_STORAGE_SECRET',
    'bucket' => getenv('OBJECT_STORAGE_BUCKET'),
    'region' => getenv('OBJECT_STORAGE_REGION'),
];

return [

    '*' => [

    ],

    'dev' => [
        'images' => [
            'name' => 'Images',
            'handle' => "images",
            "type" => 'craft\volumes\Local',
            "url" => "@web/images",
            "settings" => [
                "path" => "@webroot/images",
            ],
            "hasUrls" => true,
        ],

        'files' => [
            'name' => 'Files',
            'handle' => "files",
            "type" => 'craft\volumes\Local',
            "url" => "@web/files",
            "settings" => [
                "path" => "@webroot/files",
            ],
            "hasUrls" => true,
        ],

    ],

    'production' => [
        'images' => array_merge($objectStorageAccess, [
            'type' => "fortrabbit\ObjectStorage\Volume",
            'name' => 'Images',
            'handle' => "images",
            'subfolder' => 'production/images',
        ]),

        'files' => array_merge($objectStorageAccess, [
            'type' => "fortrabbit\ObjectStorage\Volume",
            'name' => 'Files',
            'handle' => "files",
            'subfolder' => 'production/files',
        ]),

    ],

];

```
Because of a bug, I can't select Sync config file with settings for whatever reason - I raised that as bug here: https://github.com/fortrabbit/craft-object-storage/issues/6 - but I'm not sure how this could affect the naming of the volume.

**Comment by brandonkelly** [comment]
Super weird… I’m not able to reproduce either of these. What is the volume’s name set to in your `volumes` table in the database?

**Comment by howells** [comment]
@brandonkelly it's "Images"! https://cln.sh/XMt3Vj

I can't possibly see where "Images [files]" could be in the system, even though that's definitely the label - https://cln.sh/yV0WML - Any ideas?

**Comment by brandonkelly** [comment]
Do you have a custom module that could be interfering with this?

**Comment by howells** [comment]
Ah, sorry seems that the root `volumefolders` entry in the database was named "Images [files]", for some reason that hadn't updated to reflect the name change of volume itself. As soon as I manually changed that, the checkbox would show as selected. If you can replicate the problem let's close it, too obscure to be a real issue.

**Comment by brandonkelly** [comment]
Alright, cool. I bet what happened is, the folder did get renamed as expected, but the name change was influenced by your `volumes.php` file.
