### ISSUE TITLE
Import missing `yii\web\ForbiddenHttpException` in `craft\web\User`

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#6497]
### Description
https://github.com/craftcms/cms/blob/3.5/src/web/User.php#L200
please add

```PHP
use yii\web\ForbiddenHttpException;
```
or 
```PHP
throw new  yii\web\ForbiddenHttpException(Craft::t('app', 'Guest Required'));
```

to prevent a class not found exception

### Additional info

- Craft version: >=3.4.X

**Comment by brandonkelly** [comment]
Doh! Thanks for pointing that out. Just fixed on both `develop` and `3.5` branches.
