### ISSUE TITLE
[3.5.0-RC4] - Frontend User Register Form - Undefined index:suspendByDefault

### ISSUE THREAD

**Issue by hendrikeng** [craftcms/cms#6499]
### Description
Migration from older Craft versions doesn't add the `suspendByDefault` var to `users.yml`
Without manually adding or setting and unsetting the value in the cp registering a new user via front end form will fail with:
`Undefined index:suspendByDefault`

### Steps to reproduce

1. upgrade to 3.5
2. register via frontend form

### Additional info

- Craft version: 3.5.0-RC4
- PHP version: 7.4
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
I can’t find anywhere where this could be happening – everything in the codebase that references that setting is expecting that it may be undefined.

Can you please search your logs for that error message, and then post the stack trace that follows it?

**Comment by shornuk** [comment]
I've just run into this as well. Will try and find more info.

**Comment by codyjames** [comment]
Happened to me as well. Toggling the "suspendByDefault" value in the CP worked for me.

**Comment by brandonkelly** [comment]
Please search your logs for the error message and post the stack trace.

**Comment by rpeshnegi** [comment]
I've same issue

**Stack trace:**
[-][-][ilcosm85h0rt5haka3mjkpvs6f][error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined index: suspendByDefault in D:\xampp7\htdocs\craftapp\vendor\craftcms\cms\src\controllers\UsersController.php:987
Stack trace:
#0 D:\xampp7\htdocs\craftapp\vendor\craftcms\cms\src\web\ErrorHandler.php(75): yii\base\ErrorHandler->handleError(8, 'Undefined index...', 'D:\\xampp7\\htdoc...', 987)
#1 D:\xampp7\htdocs\craftapp\vendor\craftcms\cms\src\controllers\UsersController.php(987): craft\web\ErrorHandler->handleError(8, 'Undefined index...', 'D:\\xampp7\\htdoc...', 987, Array)
#2 [internal function]: craft\controllers\UsersController->actionSaveUser()
#3 D:\xampp7\htdocs\craftapp\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#4 D:\xampp7\htdocs\craftapp\vendor\yiisoft\yii2\base\Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#5 D:\xampp7\htdocs\craftapp\vendor\craftcms\cms\src\web\Controller.php(181): yii\base\Controller->runAction('save-user', Array)
#6 D:\xampp7\htdocs\craftapp\vendor\yiisoft\yii2\base\Module.php(528): craft\web\Controller->runAction('save-user', Array)
#7 D:\xampp7\htdocs\craftapp\vendor\craftcms\cms\src\web\Application.php(294): yii\base\Module->runAction('users/save-user', Array)
#8 D:\xampp7\htdocs\craftapp\vendor\craftcms\cms\src\web\Application.php(597): craft\web\Application->runAction('users/save-user', Array)
#9 D:\xampp7\htdocs\craftapp\vendor\craftcms\cms\src\web\Application.php(273): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#10 D:\xampp7\htdocs\craftapp\vendor\yiisoft\yii2\base\Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#11 D:\xampp7\htdocs\craftapp\web\index.php(22): yii\base\Application->run()
#12 {main}

**Comment by brandonkelly** [comment]
@rpeshnegi Thank you! Just got this fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.2 is out now with this fix.
