### ISSUE TITLE
Differentiate the site url from the preview url for headless mode

### ISSUE THREAD

**Issue by cyponthemic** [craftcms/cms#6500]
Hey guys, I'd love to be able to tell the CMS to check one domain on preview mode and another when it generates an entry link. 

It would be useful on a headless + full static architecture where you have an environment that run as a SPA (preview url) and a prod one that is fully static (site URL)

Thanks,
Alex

**Comment by brandonkelly** [comment]
If you’re using Craft Pro, you can set this up by changing your preview target’s URL to the custom domain.
