### ISSUE TITLE
isValid for EVENT_BEFORE_AUTHENTICATE event, like login events.

### ISSUE THREAD

**Issue by meredevelopment** [craftcms/cms#6501]
### Description

I think it would be really useful to be able to set an `isValid` boolean in an `EVENT_BEFORE_AUTHENTICATE` event. 
There are times when `EVENT_BEFORE_LOGIN` isn't early enough in the process to do some checks and cancel the return to a 'Invalid username or password' type state/response. 

e.g.
```
Event::on(
    User::class,
    User::EVENT_BEFORE_AUTHENTICATE,
    function (AuthenticateUserEvent $event) {
        // if some condition isn't right
        $event->isValid = false;
    }
)
```

The `performAuthentication` boolean already exists which can skip authentication altogether. At first I thought this meant 'do not authorise this user' if false, which made for one of the biggest bugs I've ever introduced into an app 😂

Thanks for listening.

**Comment by brandonkelly** [comment]
Can you give me an example of what you’re trying to add?

**Comment by meredevelopment** [comment]
I can't give you code or a PR, not skilled enough, if that's what you mean. 

I wrote up my question / issue [here](https://craftcms.stackexchange.com/questions/35928/how-how-can-i-restrict-fail-a-login-using-a-userevent-before-authenticate-hook) but I'm guessing posting to an external site in a GitHub issue is bad etiquette 😅

So... at the moment in one of my modules I'm doing this: 

```
Event::on(
    User::class,
    User::EVENT_BEFORE_AUTHENTICATE,
    function (AuthenticateUserEvent $event) {

        //Empty a session var to use.
        Craft::$app->getSession()->remove('myCheckInvalidUser');

        //Do my checks.
        $checksuccess = $this->doMyChecks($event->sender->username, $event->password);
        if (!$checksuccess) {
            // set a Session var to cancel the login in next event.
            Craft::$app->getSession()->set('myCheckInvalidUser', true);
        } else {
            // log the user in.
            $success = Craft::$app->user->loginByUserId($user->id);
            Craft::$app->response->redirect($referrer);
            return Craft::$app->end();
        }
    }
);

Event::on(
    WebUser::class,
    WebUser::EVENT_BEFORE_LOGIN,
    function (UserEvent $event) {
        $myCheckInvalidUser = Craft::$app->getSession()->get('myCheckInvalidUser');

        if (!$myCheckInvalidUser === false) {
            // cancel this login.
            $event->isValid = false;
        }
    }
);
```

I don't know if this is an ok way to do it. Seems to me it would be nice to be able to cancel the Authentication from the first event by setting some value (`isValid` for example).

**Comment by brandonkelly** [comment]
You can prevent authentication by setting `$authError` on the user:

```php
$event->performAuthentication = false;

// ...

if (!$authenticates) {
    $event->sender->authError = 'The auth error message';
}
```

I’ve updated the event docs for the next Craft release so that’s more clear.
