### ISSUE TITLE
Make new project config YAML files easier for humans to scan over?

### ISSUE THREAD

**Issue by mildlygeeky** [craftcms/cms#6504]
I am loving the new project config setup in 3.5, where all the `things` in Craft are now kept in their own YAML file — getting an idea of what has and hasn't changed on any given commit is so much easier now — thank you!

One thing that I am wondering — would it be possible for the filenames Craft uses in project config to be more human-friendly? Right now it appears that all of the filenames are `<uid>.yaml` — I haven't looked into the code that picks up the changes, but wondering if they could instead some sort of form of `<handleFieldOrIdThatCraftCompletelyIgnores>-<uid>.yaml`? As is the folders are an endless list of UIDs - it would be nice if there were a way these filenames could be both more human-friendly as well as still be performant for Craft to ingest.

**Comment by brandonkelly** [comment]
Great idea! Just made this change for the next release. (You’ll need to clear out your `config/project/` folder for the change to take effect.)

**Comment by mildlygeeky** [comment]
Thanks @brandonkelly! One of the reasons I love this CMS / community so much is how much y'all value the community's input — thank you!

**Comment by brandonkelly** [comment]
Craft 3.5 RC6 is out now with this change.
