### ISSUE TITLE
Craft CMS missing axios.min.map when deleting a field and sometimes throws a 500/4 error

### ISSUE THREAD

**Issue by richardegil** [craftcms/cms#6506]
### Description
We have an instance of Craft CMS running that has a lot of content entries and a lot of fields, using Neo and SuperTable. At some point, something changed, and now when we try to delete one of the fields the CMS will just hang until it eventually throws a 504 error, and sometimes seeing an error like MySQL timeout exceeded error. Any idea how to track this down?

Some additional info, I keep seeing this error in the logs yii\web\NotFoundHttpException: axios.min.map does not exist.

Also getting a failed POST request for /index.php?p=admin/actions/fields/delete-field

### Steps to reproduce

1. Go to Settings->Fields
2. Go into a Field Group
3. Click the 'x' next to the field I want to delete

### Additional info

- Craft version: 3.4.30
- PHP version: 7.3.20
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
-- NEO 2.7.25
-- Asset Rev 6.0.2
-- DigitalOcean Spaces Volume 1.1.2
-- Redactor 2.6.1
-- Sprout Forms 3.12.2
-- Super table 2.5.4
-- Craft Ajaxinate 2.0.1
-- Field Manager 2.1.8

**Comment by brandonkelly** [comment]
Just fixed the `axios.min.map` warning for the next Craft 3.5 release, though it’s inconsequential – map files are only used by browsers to aid in debugging compressed JavaScript; they never actually get executed (think CSS for the JavaScript debugger).

As for the 504 timeout error, try increasing PHP’s `max_execution_time` ini setting, as well as any web server timeout settings. If you need more help with that, write into support@craftcms.com and we can help sort it out.

**Comment by brandonkelly** [comment]
Craft 3.5 RC6 is out now with the `axios.min.map` fix.

**Comment by richardegil** [comment]
@brandonkelly what do I need to send to support to get more assistance?

**Comment by brandonkelly** [comment]
Send in your Composer files and a database dump as a starting point, so we can see if we can reproduce the long save time.
