### ISSUE TITLE
[3.5.x-dev] New Field Manager only searches on labels not on fieldHandles

### ISSUE THREAD

**Issue by michtio** [craftcms/cms#6507]
### Description

As said in the title, when you search for fields in the new layout manager, it will only search based on the labels not on the fieldHandle

### Steps to reproduce

1. Create a field with the label `Page Header` and give it the handle `heroBlock`
2. Search for `hero` and you'll not see the field showing up
3. Search for `Page` or `Header` or a combination and the field shows up

### Additional info

- Craft version: 3.5.x-dev

**Comment by mmikkel** [comment]
It would also be really helpful if the search filter would account for field group names.

**Comment by brandonkelly** [comment]
Just added both of those for the next 3.5 release!

**Comment by brandonkelly** [comment]
Craft 3.5 RC6 is out now with this change.
