### ISSUE TITLE
[3.5.x-dev] Project config rebuild looses settings

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#6509]
### Description

Running project-config rebuild and comparing the project config files, some settings seem to be lost (path to temporary uploads, entry types title translation settings)

### Steps to reproduce

1. Reapply config files, check settings are correct
2. Run rebuild
3. Compare files

Entry type:
![image](https://user-images.githubusercontent.com/60010597/89097411-fa137100-d3de-11ea-8591-4f55efbff41a.png)

project.yaml
![image](https://user-images.githubusercontent.com/60010597/89097434-27601f00-d3df-11ea-865b-66203c53a754.png)

### Additional info

- Craft version: 3.5.x-dev 3613b5f35ccb3413e3dbd74a32d82d2f5f784d56
- PHP version: 7.4.7
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5 RC6 is out now with this fix.
