### ISSUE TITLE
[3.5.x-dev] Status badges in drafts edit screens missing

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#6511]
### Description

Edits in drafts/current entry used to be indicated by status badges in 3.4

![image](https://user-images.githubusercontent.com/60010597/89101237-5c2f9e80-d3fe-11ea-9850-f35e2d7dfb5b.png)

Badges are missing in 3.5

![image](https://user-images.githubusercontent.com/60010597/89101289-d829e680-d3fe-11ea-9d11-70b60c8040f7.png)

### Steps to reproduce

1. Create draft for existing entry
2. Edit draft / current entry
3. Reload draft

### Additional info

- Craft version: 3.5.x-dev 3613b5f35ccb3413e3dbd74a32d82d2f5f784d56
- PHP version: 7.4.7
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5 RC6 is out now with this fix.
