### ISSUE TITLE
[3.5.0-RC6] Field groups in the FLD does not show up in search, if they have already been hidden

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#6512]
### Description

Seems like there's a minor issue with searching for field group names in the new FLD (this is probably related to https://github.com/craftcms/cms/issues/6507).  

After searching for something in the new FLD, if a field group has already been filtered out/hidden, that field group's name will not yield any results if/when the search query is changed to something that _should_ make the fields in that group appear.

Here's a GIF to explain:

![CleanShot 2020-08-02 at 10 57 14](https://user-images.githubusercontent.com/298510/89119482-15e64800-d4af-11ea-96d0-827be41b5686.gif)

In the GIF, I search for "common". The fields in the "Common" are visible, and all other fields are hidden, as expected (there are no other fields or groups matching this search string).

Then, I intentionally misspell "common" to "commonn". The fields in the "Common" field group disappear, also as expected (nothing matches the search query at this point).

Finally, I correct the spelling back to "common". At this point I'd expect the fields in the "Common" field group to reappear, but they don't.

Note that this behaviour doesn't seem to apply for field handles or labels, only group names. Also, completely wiping the search field seems to reset it, i.e. the search for "common" works as expected again at that point.

### Steps to reproduce

1. Search for something in the new FLD
2. Change the search query (without completely wiping the search field) to the name of a field group that has already been hidden
3. Confirm that the fields in the relevant field group do *not* appear

### Additional info

- Craft version: 3.5.0-RC6
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Whoops, thanks for reporting that! Fixed for the next release.
