### ISSUE TITLE
Request missing required body param

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#6515]
it seems [this commit ](https://github.com/craftcms/cms/commit/90f6c106cc0000e525b6eeac310f3654bc0c3037#diff-2683e53486d31ee627a499e4b42b1e07 ) causes some breaking changes.
for example when i delete a tag with tags plugin, element-indexes/perform-action returns 'Request missing required body param'  because in this case 'elementAction: ether\tagManager\elements\actions\Delete' is missing from sent request.

**Additional info**

- Craft version: Craft CMS 3.5.0-RC6

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next release.
