### ISSUE TITLE
Can add entry to another author's parent entry, even though permission un-ticked

### ISSUE THREAD

**Issue by kevadamson** [craftcms/cms#6516]
### Description

Even though I have "Edit other authors’ entries" un-ticked, when choosing a parent for my own authored entry in a structure, I am able to see different author's entries, and add it as a child to a parent entry created by a different author.

### Additional info

- Craft version: 3.4.30

**Comment by brandonkelly** [comment]
That’s expected… you’re not actually editing the other entry in the process.

**Comment by kevadamson** [comment]
Seems odd, as you can't see other author's entries in the normal view, and then when you do choose a parent not authored by the current user, it shows it on it's own in the list with no indication as to it's parent(s) ...

**Comment by brandonkelly** [comment]
Yeah that is admittedly a little awkward. Just posted a new enhancement request for adding read-only listings of other authors’ entries to the index (#6522).

**Comment by kevadamson** [comment]
Nice one. Could it be a config where items are either shown as read only, or hidden completely? That might be nice for systems where one user has no real business even seeing what other author's are creating.

**Comment by brandonkelly** [comment]
@kevadamson That will be covered when we add View permissions (see #887).

**Comment by kevadamson** [comment]
@brandonkelly Awesome. I've also commented on that thread about user permissions as well. Hope that's OK!
