### ISSUE TITLE
Dropdown field does not set default value

### ISSUE THREAD

**Issue by duskosobic** [craftcms/cms#6517]
### Steps to reproduce

1. Create a field of type: Dropdown
2. Select default value (e.g. second option)
3. Add field to Category field layout
4. Create a category and you will see default dropdown option is first one, not default (second one)

### Additional info

- Craft version: Craft Pro 3.4.30
- PHP version: 7.4.8
- Database driver & version: PostgreSQL 12.3
- Plugins & versions:
Asset Rev	6.0.2
Back In Stock	1.4.0
Barcode	1.0.3
Bundles	1.1.3
Craft Commerce	3.1.12
DigitalOcean Spaces Volume	1.1.2
Klarna Checkout for Craft Commerce	1.1.13
PayPal Checkout for Craft Commerce	1.1.1
QRCode	1.0.3
Redactor	2.6.1
Stripe for Craft Commerce	2.3.1.1
Vipps	1.0.3
Web Payments	1.0.4

**Comment by brandonkelly** [comment]
I’m not able to reproduce this – the default dropdown option is selected by default as expected for new categories.

Can you post a screenshot of your dropdown field settings?



> 4\. Create a category and you will see default dropdown option is first one, not default (second one)

Just to be sure, you are actually testing this with a _new_ category, right? It is expected that the default value would not be initially selected for _existing_ categories.

**Comment by duskosobic** [comment]
Hm, it works now when I test again. I do not understand how it did not work this morning.
Sorry for the time taken!

**Comment by brandonkelly** [comment]
No worries :) Glad it’s working as expected for you now!
