### ISSUE TITLE
Create static classes for each Field Layout with constant field handles

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#6518]
### Description

This might sound a little bit strange at first, but let me explain.
Now that it's possible to change the labels of fields by default I cannot use my custom Relabel Plugin anymore that kinda did the trick for me (in my custom Version)

After a field layout was created I created a class in `storage/runtime/compiled_classes` with 
```php
public const >>FIELD_UNIQUE_IDENTIFIER<< = '>>originalFieldHandle<<';
```

So in the End I had a structure like
```
- sections
-- section-handle-entry-type-handle.php
- users
-- users.php
- assets
....
```

Those files for example contained
```PHP
class Pages
{
    public const HERO_IMAGE = 'image';
}
```

That way I was able to get autocomplete working with
```PHP
$entry->getFieldValue(Pages::HERO_IMAGE):
```

Of course there is already the `CustomFieldsBehavior` for that but when you work with many relabeled fields that might be confusing in the future. 
If you decide against it, I'll include it in my own Plugin as I did with Relabel before. Just wanted to know if it's worth to start it

Sitenote: I do the same (manually) with sections, entrytypes, global sets [...] as well and create kinda "enums" for all. Changing a handle is much easier that way. Maybe others think this might be interesting as well

**Comment by brandonkelly** [comment]
If we were going to do this, it would have to involve adding a new field setting for defining the constant name, so that the handle can be changed independently of the constant name, and I don’t think enough people would use this for it to be worth the new setting. Could be done as its own plugin, though.
