### ISSUE TITLE
(3.5) New alt-key feature is a little confusing.

### ISSUE THREAD

**Issue by timrosskamp** [craftcms/cms#6532]
### Description

The new feature for viewing the field handles while editing entries is quite handy, but gets a little messy on Windows because its tied to the alt-key.

When pressing alt in Firefox on Windows, the Menu bar (File, Edit, View, ...) pops up and to hide it, you have to press alt again, which switches to field names again. This is a bit annoying as the entire page jumps everytime.

And pressing alt & tab on Windows to switch between apps triggers the feature as well and switches to field handles, which could be confusing for non-tech users. Also when switching back to the browser using alt-tab, the field handles stay, because the browser wasn't in focus, so the user still sees the field handles.

### Steps to reproduce

- Press alt in Firefox on Windows when editing an entry.
- Press alt & tab on Windows when editing an entry.

### Additional info

- Craft version: 3.5.0-RC6

**Comment by brandonkelly** [comment]
@timrosskamp is there another key/combo that would make more sense?

**Comment by timrosskamp** [comment]
@brandonkelly I'm not really sure. There could always be a browser or os that uses specific keys, so trying to find an unoccupied key combo doesn't seem very straight forward.

Since field names and handle are usually not very long, a debug option could be added to the user, which displays both the name and the handle of the field inline. Then any users that have problems with the alt-key can enable to view the field handle always next to the name and everybody else can use the enhanced feature with the alt-key. Like this:

![textfield-handle](https://user-images.githubusercontent.com/23245893/89323705-6fed3600-d686-11ea-8dd7-9176538b0241.png)

**Comment by proimage** [comment]
I'd recommend using <kbd>CTRL</kbd>: https://github.com/craftcms/cms/issues/5833

**Comment by brandonkelly** [comment]
@timrosskamp Good point. As of the next release (3.5.3), the handle will _always_ be shown, but only when Dev Mode is enabled. And when you click on it, it will automatically copy the value to your clipboard.

![Video of a cursor hovering over a field handle](https://user-images.githubusercontent.com/47792/89828684-3b59fe00-db0e-11ea-9efc-7931260c16f3.gif)

**Comment by brandonkelly** [comment]
Craft 3.5.3 is out now with that change.

**Comment by bzin** [comment]
Is there any way of disabling this even in devMode @brandonkelly ?

**Comment by brandonkelly** [comment]
@bzin not currently… I considered making it a preference but I figured the vast majority of the time you’ll want it is when developing locally where Dev Mode should be enabled, and the vast majority of the time you _wouldn’t_ want it is on production where Dev Mode should absolutely not be enabled. So it sortof doubles as a reminder to disable Dev Mode in production.

**Comment by bzin** [comment]
Understood @brandonkelly, the reason why I asked if there was a way to disable it is that sometimes when discussing and presenting the CP we still want to have the `devMode` enabled before this goes to a `test` server.

With this I mean that sometimes we do have a server that is not the developer machine but has the `devMode` set to `true`.

Anyway, this is a great feature, I was always going back and forth to the Fields settings page or using the Fields Manager plugin overview to see the handles.

**Comment by brandonkelly** [comment]
@bzin Thanks, that’s a good use case, but the developer could also change their `ENVIRONMENT` variable in `.env` from `dev` to something else (disabling Dev Mode) before the presentation.

**Comment by bzin** [comment]
Yes, that's how I solve it but wanted to give feedback here. :)

**Comment by brandonkelly** [comment]
@bzin Changed my mind and went ahead and made this a preference for the next release (see #6610).

**Comment by brandonkelly** [comment]
Craft 3.5.4 is out now with the new user preference.
