### ISSUE TITLE
3.5-RC6 - Assets in a subfolder aren't selectable

### ISSUE THREAD

**Issue by michtio** [craftcms/cms#6533]
### Description

In the assets when you're in a subfolder you can't do actions on the assets, not delete, don't select multiple, because we can't select them the cogwheel doesn't appear either making it impossible to do any action on the assets.

<img width="508" alt="Screenshot_2020-08-04_at_14 58 31" src="https://user-images.githubusercontent.com/5818021/89299245-adda6200-d666-11ea-8bd8-6b9a715b2c9a.png">

### Steps to reproduce

1. Navigate to assets
2. Go in a subfolder of an asset volume

### Additional info

- Craft version: 3.5 RC6

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.
