### ISSUE TITLE
GQL: Invalid schema from derived names

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#6535]
If you have, e.g. a dropdown field, with an empty value, (e.g. "Choose One": ""), or even a hyphen, the GQL schema will throw an error because it cannot build a valid enum.

```
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but '' does not (GraphQL::InvalidNameError)
```

```
          "enumValues": [
            {
              "name": "",
              "description": null,
              "isDeprecated": false,
              "deprecationReason": null
            },
```

Similar thread in CraftQL: https://github.com/markhuot/craftql/issues/129

---

Likewise, if you have a matrix block with no fields (which is currently valid as far as Craft is concerned), you'll get an error like:

```
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.

Input Object type sidebar_contactInfo_MatrixBlockInput must define one or more fields.
```

---

Something like this in `BaseOptionsField::getContentGqlMutationArgumentType` addresses options fields, but I'm not sure its the best solution, and doesn't address the empty matrix blocks:

https://github.com/craftcms/cms/compare/3.5...timkelty:invalid-schema-names?expand=1

**Comment by timkelty** [comment]
Actually, it looks like this is a problem with more than just empty vals, as any values that don't match the pattern will throw a similar error.

**Comment by timkelty** [comment]
Something like this in `BaseOptionsField::getContentGqlMutationArgumentType` addresses options fields, but I'm not sure its the best solution, and doesn't address the empty matrix blocks:

https://github.com/craftcms/cms/compare/3.5...timkelty:invalid-schema-names?expand=1

**Comment by andris-sevcenko** [comment]
Honestly, I think the best approach here would be to leave the empty matrix blocks and "empty" enum values out of schema altogether.

**Comment by andris-sevcenko** [comment]
Worth noting that this only happens when mutations are involved.

**Comment by andris-sevcenko** [comment]
Here's a proposed solution:

1) For enums, discard all leading underscores. If the value is empty after this step, replace it with `:empty:`. I'd love to use `__blank__`, but everything starting with two `_`'s is reserved for introspection.

2) For matrix field block types with no fields, change the type to be `String`. I'm assuming these are block types used as spacers or something?

We'll debate this internally, but, to be honest, I'm not happy about either of the solutions.

**Comment by andris-sevcenko** [comment]
Another idea instead of (1) can be just a string, not an enum. Not sure if relaxing this is better or worse, though.

**Comment by timkelty** [comment]
…just when you thought you loved strong typing. 🤣

> For matrix field block types with no fields, change the type to be String. I'm assuming these are block types used as spacers or something?

Yeah - stuff that indicates the template to do something, but w/o an real data other than the placement of the matrix block.

> Another idea instead of (1) can be just a string, not an enum

Hmmmmmm…right. Certainly seems more straightforward…not sure which is less of a compromise either.

**Comment by andris-sevcenko** [comment]
Matrix issue was fixed collaterally by adding an ID field to all Matrix Block inputs to allow modifying saved Matrix blocks.

**Comment by andris-sevcenko** [comment]
How about for dropdowns and the like be of type `String` and then throw some validation on top to make sure the submitted value is in the list of values defined for the type? (@timkelty)

**Comment by timkelty** [comment]
I think that sounds like a swell idea, @andris-sevcenko

**Comment by andris-sevcenko** [comment]
@timkelty waiting for some changes in how Craft validates option field values for this. Afterward, will implement this change, too.

**Comment by andris-sevcenko** [comment]
Alright, this one has been fixed for the next Craft 3.5 release.

**Comment by brandonkelly** [comment]
Craft 3.5.10 is out now with this fix.

**Comment by jamesedmonston** [comment]
Is there any way of pinning down where the error message might be coming from? I've just started seeing it on one of our projects, but there's nothing in the logs to indicate where it's going wrong.

I'm seeing:

```json
{
  "errors": [
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"1\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"3\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"4\" does not."
  ]
}
```

**Comment by andris-sevcenko** [comment]
What query are you running, @jamesedmonston?

**Comment by jamesedmonston** [comment]
![Screenshot 2021-12-01 at 12 31 30](https://user-images.githubusercontent.com/4851924/144234965-2b427203-26ec-4029-a9a6-3985687a012b.png)

I see it when going to GraphiQL, so I guess it's happening at the point of introspection.

**Comment by andris-sevcenko** [comment]
Can you provide a list of plugins that are installed and their versions?

**Comment by jamesedmonston** [comment]
![Screenshot 2021-12-01 at 14 13 18](https://user-images.githubusercontent.com/4851924/144249717-f762a309-b1e5-4b6a-8ffc-7671dc71173d.png)

@andris-sevcenko Sure, here you go. Thanks for the speedy replies!

**Comment by andris-sevcenko** [comment]
Eh, none of that rings a bell. Can you do `./craft graphql/dump-schema --fullSchema` and send the resulting file over to support@craftcms.com? Please reference this issue.

**Comment by jamesedmonston** [comment]
@andris-sevcenko Had a quick look at the generated schema before sending it over, I can see that it appears to be an issue with some of my Super Table blocks:

```
input differences_SuperTableBlockContainerInput {
  1: differences_SuperTableBlockInput
}

input theSpace_SuperTableBlockContainerInput {
  3: theSpace_SuperTableBlockInput
}

input keyPoints_SuperTableBlockContainerInput {
  4: keyPoints_SuperTableBlockInput
}
```

(Will send it over either way)

**Comment by engram-design** [comment]
Should be fixed in the next version of Super Table. To get the fix early, change your `verbb/super-table` requirement in `composer.json` to:

```
"require": {
  "verbb/super-table": "dev-craft-3 as 2.7.0",
  "...": "..."
}
```

Then run `composer update`.

**Comment by jamesedmonston** [comment]
Thanks @engram-design!
