### ISSUE TITLE
AssetIndexer::indexFile does not index assets in-place

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#6541]
Given an s3 object existing at `foo/bar/baz.png`, and an Asset Volume `$volume`:

I want to just index the s3 object in-place. I'm doing: `AssetIndexer::indexFile($volume, 'foo/bar/baz.png')`

That indexes the `Asset` and returns it, but always moves it to the `$volume` root, despite the fact that it created the `VolumeFolder`s.

So following indexing, I'm left file/dirs in my `$volume` root like:

- baz.png
- foo
  - bar (empty dir)

---

I also tested it with an asset that was already indexed in craft at `foo/bar/baz.png`, and got the same result: `indexFile` moved it to the volume root

**Comment by andris-sevcenko** [comment]
@timkelty unable to reproduce this. What version of Craft are you using? Anything else special about the volume, perhaps?

**Comment by timkelty** [comment]
@andris-sevcenko thanks for testing – turns out it was me. Immediately following indexing, I was saving the asset to a field with "Restrict uploads to a single folder".

Apparently, that will move the asset to the root…which is weird, but unrelated to the indexing.

**Comment by andris-sevcenko** [comment]
If the single folder for a given element resolved to `""`, one might say that it's the expected behavior :)
