### ISSUE TITLE
Cannot use Twig\Environment as Environment because the name is already in use

### ISSUE THREAD

**Issue by TRowbotham** [craftcms/cms#6544]
### Description

Twig\Environment is imported twice in https://github.com/craftcms/cms/blob/develop/src/web/twig/Extension.php#L55 causing a name resolution conflict.

```bash
yii\base\ErrorException: Cannot use Twig\Environment as Environment because the name is already in use in /usr/local/apache2/htdocs/vendor/craftcms/cms/src/web/twig/Extension.php:55
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
```

### Steps to reproduce

1. Install CraftCMS
2. Navigate to any page.

### Additional info

- Craft version: 3.5.0
- PHP version: 7.0.2
- Database driver & version: Mysql 5.6.48
- Plugins & versions: None

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just released Craft 3.5.1 with a fix.
