### ISSUE TITLE
Missing translation in CP Utilities page

### ISSUE THREAD

**Issue by watarutmnh** [craftcms/cms#6545]
It seems that the following strings are missing in the translation file.

#### /admin/utilities/system-report
'Application Info'
'Modules'
'Requirements'

#### /admin/utilities/project-config

'Apply File Changes'
'Apply changes in your project config files to the stored project config.'
'Apply changes only'
'Reapply everything'
'There aren’t any pending project config changes to apply.'
'Reapply everything'
'Rebuild the Config'
'Rebuild the project config based on the data stored throughout the database.'
'Rebuild'
'Project Config Data'

#### /admin/utilities/queue-manager
'Job Data'
'Restart'
'Retry'
'Release'
'No pending jobs.'

#### /admin/utilities/clear-caches
'Caches'
'Clear caches'
'Invalidate Data Caches'
'Template caches'
'GraphQL queries'
'Invalidate caches'

#### /admin/utilities/deprecation-errors
'No deprecation errors to report!'

#### /admin/utilities/db-backup
'Download backup'
'Backup'

#### /admin/utilities/find-replace
'Find Text'
'Replace Text'

#### /admin/utilities/migrations
'Apply new migrations'
'Apply Time'
'New'
'Applied'
'No content migrations.'

**Comment by angrybrad** [comment]
Thanks, @watarutmnh. These should all be up on Crowdin now and most of them are already translated (this was a bug where existing translated strings got accidentally removed for the 3.5 release that's been fixed).
