### ISSUE TITLE
Undocumented breaking change in Craft 3.5: class\web\Request::getFullPath() now includes the current site’s base path

### ISSUE THREAD

**Issue by benface** [craftcms/cms#6546]
Given these conditions:
- The site’s base URL is https://example.com/en
- The current URL is https://example.com/en/about
- I run the following code:
```php
echo Craft::$app->getRequest()->getFullPath();
```

This is the output on Craft 3.4.30:
```
about
```

And this is the output on Craft 3.5.0:
```
en/about
```

It looks like it happened in this commit: https://github.com/craftcms/cms/commit/917c9a73165c8f510159dd585719756567338454

**Comment by brandonkelly** [comment]
That was an unintended change, but in reviewing it, the current behavior is actually the correct one. The way to fetch the path _relative to the site’s base URL_ is by calling [craft\web\Request::getPathInfo()](https://docs.craftcms.com/api/v3/craft-web-request.html#method-getpathinfo).

I’ve just added a new [Check for calls to `getFullPath()`](https://craftcms.com/knowledge-base/upgrading-to-craft-3-5#check-for-calls-to-getFullPath) section to the upgrade guide, and will add a release note about this in the 3.5.0 changelog.

**Comment by benface** [comment]
Cool @brandonkelly, that makes sense. By the way, what’s the difference between `getFullPath()` and `getFullUri()`?

**Comment by brandonkelly** [comment]
If `index.php` lives within a subdirectory in the webroot, then the subdirectory would be included in `getFullUri()`, but not in `getFullPath()`.

So, let’s say that:
- your webroot is `web/`
- your index.php file is located at `web/foo/index.php`
- your base site URL is `/foo/bar`
- you access the URI `/foo/bar/baz`

then you would have the following:

Method | Value
-- | --
`getFullUri()` | `foo/bar/baz`
`getFullPath()` | `bar/baz`
`getPathInfo()` | `baz`

**Comment by benface** [comment]
@brandonkelly I noticed another difference between `getFullPath()` and `getPathInfo()`: the former includes the "page segment" (e.g. `p1` if `pageTrigger` is `p`), while the latter doesn't. Is there a method/property for the path relative to the site's base URL (so like path info), but that also includes the page segment?

**Comment by brandonkelly** [comment]
@benface There’s no specific method for that. I guess just manually combine the two?

```url
{% set page = craft.app.request.getPageNum() %}
{{ craft.app.request.getPathInfo ~ (page != 1 ? "/p#{page}") }}
```

**Comment by benface** [comment]
That's what I ended up doing. Thank you Brandon!
