### ISSUE TITLE
Lost translations after applying 3.5 update.

### ISSUE THREAD

**Issue by watarutmnh** [craftcms/cms#6547]
Many strings had been lost from translation file after applying 3.5 update.
The following strings are Examples

#### /admin/settings/general
'General Settings'
'This is being overridden by the {setting} config setting.'
'System Name'
'System Status'
'Time Zone'
'Are you sure you want to delete the logo?'
'Login Page Logo'
'SVG file recommended. The logo will be displayed at {size} wide.'
'Site Icon'
'SVG file recommended. The logo will be displayed at {size} wide.'
'Site Icon'
'Square SVG file recommended. The logo will be displayed at {size} by {size}.'
'Change logo'
'Delete logo'
'Upload logo'
'Change icon'
'Delete icon'
'Upload icon'

#### /admin/settings/sites
'New site'
'All Sites'
'New group'
'Rename selected group'
'You can only delete groups that have no sites.'
'Delete selected group'
'Primary'
'Group'
'No sites exist for this group yet.'

#### /admin/settings/routes
'New route',
'Add a token',
'Are you sure you want to delete this route?',
'Couldn’t save new route order.',
'Couldn’t save route.',
'Create a new route',
'Edit Route',
'Global',
'If the URI looks like this',
'Load this template',
'New route order saved.',
'Route deleted.',
'Route Saved.',
'The URI can’t begin with the {setting} config setting.',
'No routes exist yet.'

**Comment by angrybrad** [comment]
Thanks, @watarutmnh. These should all be up on Crowdin now and most of them are already translated (this was a bug where existing translated strings got accidentally removed for the 3.5 release that's been fixed).
