### ISSUE TITLE
Tests stopped working with Craft 3.5

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#6549]
### Description
After updating to Craft 3.5, my functional tests have stopped working. They don't seem to find routes anymore, as this is the error message I've been getting:

```
<pre>Not Found: Template not found: ./work/persoonlijke-financiële-dienstverlening</pre>
```

This is an entry, not a template. Yes it exists. Yes it works normally in the browser.

Is there anything updated in 3.5 that would cause this?

### Steps to reproduce

1. Run functional tests accessing entries in Craft 3.5

### Additional info

- Craft version: 3.5.0
- PHP version: 7.4.8
- Database driver & version: PostgreSQL 12.3
- Plugins & versions: -

**Comment by angrybrad** [comment]
@boboldehampsink Can you share the code for a functional test you're using?

**Comment by brandonkelly** [comment]
Maybe related to 074411d311f4d5ddbb0169cbbd262bd6a769767e ?

**Comment by boboldehampsink** [comment]
> @boboldehampsink Can you share the code for a functional test you're using?

```php
<?php

namespace tests\functional;

use Codeception\Example;
use FunctionalTester;

/**
 * Work Functional Test.
 */
class WorkCest
{
    /**
     * Test if work pages work.
     *
     * @param FunctionalTester $I
     * @param Example          $example
     *
     * @dataProvider pagesDataProvider
     */
    public function testWork(FunctionalTester $I, Example $example)
    {
        $I->amOnPage('?p='.$example['url']);
        $I->seeResponseCodeIs(200);
        $I->see($example['content']);
    }

    /**
     * @return array
     */
    protected function pagesDataProvider(): array
    {
        return [
            ['url' => '/work/persoonlijke-financiële-dienstverlening', 'content' => 'Persoonlijke financiële dienstverlening'],
            ['url' => '/work/e-commerce-met-beleving', 'content' => 'E-commerce met beleving'],
            ['url' => '/work/crm-pakket-op-maat', 'content' => 'CRM pakket op maat'],
        ];
    }
}
```

This works fine on < 3.5

**Comment by boboldehampsink** [comment]
> Maybe related to [074411d](https://github.com/craftcms/cms/commit/074411d311f4d5ddbb0169cbbd262bd6a769767e) ?

Updating to 3.5.1 didn't fix it

**Comment by boboldehampsink** [comment]
I found that in another project, even the direct controller (non-element) routes don't work anymore:

`$I->amOnPage("?p=/actions/plantingpower/client/get-client&id=8c9ae0d6-9...")`

`--> {"name":"Not Found","message":"Pagina niet gevonden.","code":0,"status":404,"type":"yii\\web\\NotFoundHttpException"}`

**Comment by angrybrad** [comment]
@boboldehampsink like https://github.com/craftcms/cms/issues/6579#issuecomment-670334513, do you have a parent .htaccess file?

Any chance this is happening on a public box we could get SSH access to? If so, could you send some creds over to support@craftcms.com

**Comment by boboldehampsink** [comment]
@angrybrad no .htaccess. It's a functional test so it doesn't use a real web server. And it's not happening on a public box either. It happens locally and on our CI server.

**Comment by brandonkelly** [comment]
@boboldehampsink Can you test a7967860d42eba10697ed7f8aea686c2ff354cb5 and see if that fixes your issue, as you suspected this may be related to #6579?

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop",
  "...": "..."
}
```

Then run `composer update`.

**Comment by boboldehampsink** [comment]
I tried, and I'm now seeing these errors on dev-develop:

```
[Twig\Error\RuntimeError] An exception has been thrown during the rendering of a template ("SQLSTATE[55000]: Object not in prerequisite state: 7 ERROR:  currval of sequence "assettransformindex_id_seq" is not yet defined in this session").
```

**Comment by brandonkelly** [comment]
Can you post the stack trace?

**Comment by boboldehampsink** [comment]
Don't see any usable stack trace as it's coming from twig templates. Here's a screenshot of how my CI looks:

<img width="1169" alt="Screen Shot 2020-08-11 at 09 36 00" src="https://user-images.githubusercontent.com/378974/89870442-2042c900-dbb6-11ea-9454-fdb2170fa6d7.png">

**Comment by angrybrad** [comment]
@boboldehampsink that's a new one... are you able to reproduce that one locally (outside of CI?) Is CI running Postgres 12.3?

**Comment by boboldehampsink** [comment]
@angrybrad yes happens both locally and on CI server. Both running Postgres 12.3

**Comment by boboldehampsink** [comment]
Happens on `Asset.getUrl(transform)`

**Comment by boboldehampsink** [comment]
Only happens in tests, not when I visit the page in the browser

**Comment by boboldehampsink** [comment]
Tried to upgrade a different project to 3.5.3, same error on the transforms

**Comment by angrybrad** [comment]
@boboldehampsink We should be able to reproduce that locall, then. Any chance we could get a db dump, composer.json/lock, your tests folder and codeception.yml?

**Comment by boboldehampsink** [comment]
@angrybrad it would also require template files. Mind if I add you to the github project so you can install it from there?

**Comment by brandonkelly** [comment]
This is now fixed for the next release, via storing a reference to the DB connection in the AssetTransforms service.

**Comment by boboldehampsink** [comment]
@angrybrad fixed via discord already ;-) thanks

**Comment by brandonkelly** [comment]
Craft 3.5.4 is out now with the fix for this.

**Comment by boboldehampsink** [comment]
@brandonkelly in an other project, I have found something similar:

```

1) ClubAccountProfileCest: Test existing member entry draft
--
  | Test  tests/functional/ClubAccountProfileCest.php:testExistingMemberEntryDraft
  |  
  | [PDOException] SQLSTATE[55000]: Object not in prerequisite state: 7 ERROR:  currval of sequence "drafts_id_seq" is not yet defined in this session
  |  
  |  
  | Scenario Steps:
  |  
  | 3. $I->click("Meld je aan voor Club") at tests/functional/ClubAccountProfileCest.php:73
  | 2. $I->amOnPage("?p=account/profiel") at tests/functional/ClubAccountProfileCest.php:72
  | 1. $I->amLoggedInAs("Robuust Digital") at tests/functional/ClubAccountProfileCest.php:70
  |  
  | #1  /app/user/vendor/yiisoft/yii2/db/Schema.php:368
  | #2  /app/user/vendor/craftcms/cms/src/db/pgsql/Schema.php:108
  | #3  /app/user/vendor/yiisoft/yii2/db/Connection.php:892
  | #4  /app/user/vendor/craftcms/cms/src/services/Drafts.php:519
  | #5  /app/user/vendor/craftcms/cms/src/services/Drafts.php:191
  | #6  /app/user/plugins/clubee/services/Account.php:241
  | #7  /app/user/plugins/clubee/controllers/AccountController.php:146
  | #8  plugins\clubee\controllers\AccountController->actionSave
  | #9  /app/user/vendor/yiisoft/yii2/base/InlineAction.php:57
  | #10 /app/user/vendor/yiisoft/yii2/base/Controller.php:180

```

**Comment by boboldehampsink** [comment]
@brandonkelly did you miss this new one? I can create a new issue if you'd like.

**Comment by boboldehampsink** [comment]
Added some more fixes: https://github.com/craftcms/cms/pull/6690

**Comment by brandonkelly** [comment]
Craft 3.5.7 is out now with the real fix for this.
