### ISSUE TITLE
Look for site-group specific templates

### ISSUE THREAD

**Issue by jan-dh** [craftcms/cms#6550]
### Description
Reading the [tweet](https://twitter.com/nystudio107/status/1275993262545911808) of @khalwat 

```
Craft CMS tip Thumbs up If you’re doing a multi-site setup, did you know that @CraftCMS automatically looks for site-specific templates, w/ global fallbacks? It’s true!

It’ll look in the following places:

- templates/<SiteHandle>/…
- templates/…

#craftcms https://github.com/craftcms/cms/blob/develop/src/web/View.php#L732
```

I was wondering this could be extended to:

```
- templates/<SiteHandle>/…
- templates/<SiteGroupHandle>/…
- templates/…
```

In my experience, in a multi-site setup the styling & functionality is often shared between multiple sites (languages) on a site-group base, rather then on a site base. Checking on a group base would be very handy to be able to target all the sites within a group, instead of having to dupicate them multiple times per handle, since this is very unmaintainable.

*Edit*: Since there's currently no Group handle, <SiteGroupId> would be a quick solution

**Comment by jan-dh** [comment]
Duplicate from this:  https://github.com/craftcms/cms/issues/3101#event-3568172606

**Comment by khalwat** [comment]
I was going to do this as a simple PR but... apparently Site Groups don't have handles...

```php
craft\models\SiteGroup#1
(
    [id] => '1'
    [name] => 'Craft3'
    [uid] => '0e46d87b-48e6-4869-b200-399596257526'
    [yii\base\Model:_errors] => null
    [yii\base\Model:_validators] => null
    [yii\base\Model:_scenario] => 'default'
    [yii\base\Component:_events] => []
    [yii\base\Component:_eventWildcards] => []
    [yii\base\Component:_behaviors] => []
)
```

So... it'd be a bit more involved.

**Comment by jan-dh** [comment]
Yeah got it to work with siteId, handle would be a bit cleaner since id's may differ between DB's.

https://docs.craftcms.com/api/v3/craft-records-site.html#method-getgroup

**Comment by khalwat** [comment]
You could turn the `name` into a handle via:

```
use yii\helpers\Inflector;

...

$handle = preg_replace('/\-{2,}/', '-', Inflector::camel2id($group->name));
```

...which is how Craft does it for elements.

**Comment by brandonkelly** [comment]
This FR is already covered by #3101. Lack of site group handles is the main reason we haven’t gotten around to it yet.

**Comment by jan-dh** [comment]
There's a [PR](https://github.com/ThomasDeMarez/cms/commit/aa5cee4a386576d4b8a1d0b82a327040bca17481) for this
