### ISSUE TITLE
Content (in super table) missing when saving after using a draft

### ISSUE THREAD

**Issue by andersaloof** [craftcms/cms#6553]
### Description
Unsure if the bug is in Craft og Super Table (or both), but the bug reported in #6154 is still present.

Our client has on several occacions noticed that some rows in a super table inside a matrix, is lost when saving content, but we've been unable to find the culprit, until today, when we found the #6154 issue and tried replicating the steps described and got the bug immediately. However, they did not remember using preview mode as the issue describes.

I downloaded the production database, and successfully reproduced the issue following the steps underneath.

The issue is not present on all entries, as I was only able to reproduce it on the entry the client recently noticed it with, and not another entry of the same content type.

While investigating this, I stumbled upon other related issues, like https://github.com/verbb/super-table/issues/367 and https://github.com/craftcms/cms/issues/6480.

### Steps to reproduce with preview

1. Open preview
2. Add a new row to the block with the super table field
3. Preview refreshes, but all other rows in super table field disappears. They are still present in the editor part of the browser.
4. Close preview, fields still seems to be there.
5. Publish changes
6. All rows except the new row are gone.

### Steps to reproduce with draft

1. Create a draft
2. Add a new row to the block with the super table field
3. Publish changes
4. All rows except the new row are gone.

### Network inspector

It seems that while updating existing fields in the supertable in the matrix block with a draft, the ID of the matrix block isn't updated correctly to the ID of the matrix block in the working draft. Auto-save changes to these fields is ignored (and I guess that's why nothing is updated in live preview when content changes, as described in https://github.com/craftcms/cms/issues/6480).

When adding a new row to the super table the ID of the matrix block seems to be updated correctly, but this clears out all the old rows, I guess since they don't match the correct ID of the matrix block in the draft anymore. And that's probably why all OLD content is cleared out when saving the draft, cause it was never correctly saved in the first place.

Below is a small excerpt of the post data when updating a field, and adding a row

Post data when updating a field in an existing row
```
fields[content_matrix][blocks][109586][fields][items][blocks][407898][fields][heading]: A new heading that won't be saved
```

Post data when adding new row (with empty heading)
```
fields[content_matrix][blocks][407887][fields][items][sortOrder][]: 407898
fields[content_matrix][blocks][407887][fields][items][sortOrder][]: new1
fields[content_matrix][blocks][407887][fields][items][blocks][new1][type]: 5
fields[content_matrix][blocks][407887][fields][items][blocks][new1][fields][heading]: 
```

The matrix block with ID 109586 seems the be the ID of the current revision (when I inspect regular entry updates). 

### Additional info

- Craft version: 3.4.30
- PHP version: 7.4.3
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
  - Super-Table: 2.5.4

**Comment by brandonkelly** [comment]
Can you please send your Composer files and a database backup over to support@craftcms.com, and direct us to the entry where you are seeing this happen?

**Comment by andersaloof** [comment]
Sure, I'll get on it right away.

**Comment by brandonkelly** [comment]
This ended up being the same issue as #6480. Fixed for the next release!

**Comment by andersaloof** [comment]
Great!

**Comment by brandonkelly** [comment]
Craft 3.5.6 is out now with that fix.
