### ISSUE TITLE
Mutations on Single Entry not working

### ISSUE THREAD

**Issue by MatthiasGrandl** [craftcms/cms#6554]
If you configure your schema so that it only has permissions to `edit` your single, it is not possible to actually edit it. You need a save permission for some other non-single entry type for it to work.

This behaviour has been confirmed by @andris-sevcenko on Discord.

**Comment by andris-sevcenko** [comment]
All fixed for the next relase!

**Comment by brandonkelly** [comment]
Craft 3.5.1 is out now with this fix.
