### ISSUE TITLE
Template support in Matrix Layout, not just Field Layout

### ISSUE THREAD

**Issue by MattWilcox** [craftcms/cms#6555]
### Description

Looove the idea with the new template partials that are part of the Field Layout. First thing I wanted to do was provide a preview of a linked YouTube video... but can't because I'd need the Template in the Matrix layout, not the Entry field layout.

Any chances?

<img width="619" alt="Screen Shot 2020-08-05 at 14 36 15" src="https://user-images.githubusercontent.com/814039/89419870-decf9b00-d729-11ea-9ef5-caa9ab38e6c2.png">

**Comment by brandonkelly** [comment]
This will be possible when we add UI element support to Matrix field layouts (#6494).
