### ISSUE TITLE
Fatal error while  updating to v3.5

### ISSUE THREAD

**Issue by zzseba78** [craftcms/cms#6556]
### Description

Fatal error while  updating to v3.5

### Steps to reproduce

1.Update to 3.5

First error:

```
yii\base\ErrorException: Undefined index: siteSettings

Migration: craft\migrations\m200620_230205_field_layout_changes
```

Second error while trying to restore db to previous version.

```
Database Exception: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'elements'
The SQL being executed was: ALTER TABLE `fieldlayouttabs` ADD `elements` text AFTER `name`

Migration: craft\migrations\m200620_230205_field_layout_changes
```

I had to restore the whole website from a backup.

### Additional info

- Craft version:
- PHP version: 7
- Database driver & version: libmysql - 5.6.43 
- Plugins & versions: Reasons 2.1.2 , Redactor 2.6.1 

## Note

Seems the same issue as this one, but i will leave it open until fixed: https://github.com/craftcms/cms/issues/6464

**New field layout designer it´s awesome** 🤯 , very smart features as always.

**Comment by zzseba78** [comment]
From support they confirmed they are aware of this bug and they are still trying to workout, so will be fixed in next release. I just leave this for information if someone else is running into this same problem.

**Comment by dangelion** [comment]
Same problem here. Hope they'll fix soon

**Comment by halvorsanden** [comment]
Same here. 
Looks like the same issue as: https://github.com/craftcms/cms/issues/6464

**Comment by zzseba78** [comment]
Problem fixed in 3.5.1. Closing this. Thank you!

**Comment by bartrylant** [comment]
I get this error when upgrading from craft 3.4.28.1 => 3.5.15.1

**Comment by brandonkelly** [comment]
@bartrylant Please send your Composer files and a database backup to support@craftcms.com, so we can look into it from there.
