### ISSUE TITLE
Cannot delete section in Craft 3.5

### ISSUE THREAD

**Issue by carolineboeykens** [craftcms/cms#6565]
### Description
<img width="1436" alt="Screen Shot 2020-08-06 at 11 05 34" src="https://user-images.githubusercontent.com/42932673/89513705-2f500280-d7d5-11ea-8900-7c448f584998.png">

### Steps to reproduce

1. Create a section
2. Try to delete the section

### Additional info

- Craft version: 3.5.1
- PHP version: 7.2.22

**Comment by andris-sevcenko** [comment]
I'm unable to reproduce this. Can you look for a stack trace in your log files for a stack trace?

**Comment by carolineboeykens** [comment]
`2020-08-06 14:06:25 [-][43][-][error][yii\base\ErrorException:8] yii\base\ErrorException: Trying to access array offset on value of type null in /data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/services/Sections.php:1122
Stack trace:
#0 /data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/web/ErrorHandler.php(75): yii\base\ErrorHandler->handleError()
#1 /data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/services/Sections.php(1122): craft\web\ErrorHandler->handleError()
#2 /data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/services/ProjectConfig.php(1089): craft\services\Sections->handleChangedEntryType()
#3 [internal function]: craft\services\ProjectConfig->handleChangeEvent()
#4 /data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/yiisoft/yii2/base/Component.php(627): call_user_func()
#5 /data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/services/ProjectConfig.php(667): yii\base\Component->trigger()
#6 /data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/services/ProjectConfig.php(475): craft\services\ProjectConfig->processConfigChanges()
#7 /data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/services/ProjectConfig.php(491): craft\services\ProjectConfig->set()
#8 /data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/services/Sections.php(1306): craft\services\ProjectConfig->remove()
#9 /data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/services/Sections.php(794): craft\services\Sections->deleteEntryType()
#10 /data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/services/Sections.php(766): craft\services\Sections->deleteSection()
#11 /data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/controllers/SectionsController.php(213): craft\services\Sections->deleteSectionById()
#12 [internal function]: craft\controllers\SectionsController->actionDeleteSection()
#13 /data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#14 /data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#15 /data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/web/Controller.php(181): yii\base\Controller->runAction()
#16 /data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#17 /data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/web/Application.php(294): yii\base\Module->runAction()
#18 /data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/web/Application.php(597): craft\web\Application->runAction()
#19 /data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/web/Application.php(273): craft\web\Application->_processActionRequest()
#20 /data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#21 /data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/public/index.php(23): yii\base\Application->run()
#22 {main}
2020-08-06 14:06:24 [-][43][-][info][application] $_GET = [
    'p' => 'admin/actions/sections/delete-section'
]`

**Comment by andris-sevcenko** [comment]
Huh. Can you try running project config rebuild?

If that does not help, can you send over the DB dump, and your composer.lock and composer.json files to support@craftcms.com and reference this issue?

**Comment by carolineboeykens** [comment]
Yes! That worked!

Thank you!
