### ISSUE TITLE
Cannot create new field in Craft 3.5.1 - deletes field group

### ISSUE THREAD

**Issue by mofman** [craftcms/cms#6567]
### Description
Upon trying to create a new field in craft 3.5.1 Craft crashes with 404 not found. 
It seems craft then deletes all or the fieldgroup that field was being added to as the group is gone in the db and I get the error `Argument 1 passed to craft\services\Fields::getGroupById() must be of the type integer, null given, called in /Users/andrew/Sites/knockbracken-fuels/vendor/craftcms/cms/src/base/Field.php on line 554` When trying to view the field page.

<img width="1088" alt="Screenshot 2020-08-06 at 12 09 19" src="https://user-images.githubusercontent.com/3038169/89525451-2152af80-d7de-11ea-9519-c6bc20fadccf.png">

<img width="1048" alt="Screenshot 2020-08-06 at 12 09 09" src="https://user-images.githubusercontent.com/3038169/89525458-23b50980-d7de-11ea-8ece-c9c0d9db0a2f.png">

### Steps to reproduce

1. Create a field

### Additional info

- Craft version: 3.5.1
- PHP version: 7.2
- Database driver & version:
- Plugins & versions:

**Comment by mofman** [comment]
I can replicate this very easily with database backup. If you would like access please let me know where to forward it to.

**Comment by brandonkelly** [comment]
Yeah please send your DB backup and Composer files to support@craftcms.com.

**Comment by mofman** [comment]
#5530
