### ISSUE TITLE
3.51 - Can't add entire Field Group in Field Layout

### ISSUE THREAD

**Issue by bkrsmanovic** [craftcms/cms#6568]
### Description

Before patch, you would put fields in specific fields groups, then you would be able to push entire group of fields with tab already called 'Group Field Name' and reorder / remove / add fields if necessary.
Now, you cannot add entire group of fields, so if I have 3 different groups that I want to add to 1 section, I need to manually create Tabs, rename them to proper field group, and then manually add all fields. It is really bothersome and time consuming.

Maybe this is not bug, but intentional change, but it for sure is unexpected behavior for someone who is dealing with this on daily basis.

### Steps to reproduce

1. Create 1 or multiple field groups with multiple fields inside
2. Try to assign that field group to section. It is not possible. (You cannot click on Common - Page Content or Common - Page Data and pull entire field group in field layout on left side, image 1).
3. Image 1:
![image](https://user-images.githubusercontent.com/15169280/89531256-38020200-d7f0-11ea-8226-66ca6892902a.png)

### Additional info

- Craft version: 3.51

**Comment by zzseba78** [comment]
Agree, be able to drag whole field group is great.

**Comment by brandonkelly** [comment]
Yeah this is an intended regression, but plan to improve the UX via batch field selection (#1674) + automatic tab creation (#3952).

**Comment by remcoov** [comment]
Hi guys,

Totally agree with this, extremely time consuming and to be honest I don't understand why you guys took this out. But, oh well. Any ETA on the batch field selection?
