### ISSUE TITLE
Dropdowns no longer set default value

### ISSUE THREAD

**Issue by sgtpenguin** [craftcms/cms#6576]
### Description
After updating to 3.5.1, dropdown fields do not default to the selected default value

### Steps to reproduce

1. Create a Dropdown field with a default option other than the first
2. Add it to an entry type and try it out

### Additional info

- Craft version: 3.5.1
- PHP version: 7.3.7
- Database driver & version: MySQL 5.7.26
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Dropdown default values only apply to *new* elements. If you create a new entry, it should get the default value. Just verified that it still works as expected on my end.

**Comment by sgtpenguin** [comment]
Thanks.  I'm aware of the behavior you're describing, however this was working fine before upgrading and I've made no changes regarding these dropdowns or their default values.  After playing with it more it appears that the problem is happening only when the dropdown is inside a neo field, regardless of whether the entry or fields are new.  I'll bring it up over there.
