### ISSUE TITLE
Craft 3.5 templates not loading

### ISSUE THREAD

**Issue by petestewartnz** [craftcms/cms#6579]
### Description
Since updating to Craft 3.5 I am getting 404 errors for all pages. This is only on staging and production environments, local is fine. Different is that I am using Deployer for deployment, so project files sit inside a folder and the htaccess takes care of routing to this folder. I am unable to set the document root so htaccess is a requirement.

### Steps to reproduce

1. Install Craft 3.5 inside folder such as 'root/current'
2. Use .htaccess in root folder to rewrite urls

```
RewriteEngine on
RewriteCond %{SERVER_PORT} 80
RewriteRule ^(.*)$ https://example.com/$1 [R=301,L,NE]
RewriteRule ^(.*)$ current/public/$1 [L]
```

3. Load page eg /about - 404 error Template not found: current/public/about

### Additional info

- Craft version: 3.5.1
- PHP version: 7.3.16
- Database driver & version: MYSQL 5.6.40
- Plugins & versions: SuperTable 2.5.4, Redactor 2.6.1

**Comment by brandonkelly** [comment]
Try changing that last line to:

```
RewriteRule ^(.*)$ current/public/index.php?p=$1 [QSA,L]
```

**Comment by petestewartnz** [comment]
> Try changing that last line to:
> 
> ```
> RewriteRule ^(.*)$ current/public/index.php?p=$1 [QSA,L]
> ```

That breaks the site completely. I think that rule already exists in the .htaccess file that sits inside the public folder. This .htaccess  file is at the root of the hosting account basically to set the document root to 'current/public'

I had no issues prior to 3.5 with this setup, so feel something has changed with the way template files being called?

**Comment by boboldehampsink** [comment]
Might be related to #6549 which also has 404's on Craft 3.5

**Comment by brandonkelly** [comment]
We just fixed this bug for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.3 is out now with this fix.

**Comment by petestewartnz** [comment]
> Craft 3.5.3 is out now with this fix.

Can confirm that the pages are loading up with v3.5.3

But now have an issue with the admin. Am getting a Chrome message - ...redirected you too many times.

I'm guessing this is something to do with the .htaccess, but didn't have this issue previously

**Comment by brandonkelly** [comment]
Hm, is there more to your `.htaccess` file than what you posted? We tested with the same file and didn’t see that error.

**Comment by petestewartnz** [comment]
> Hm, is there more to your `.htaccess` file than what you posted? We tested with the same file and didn’t see that error.

Nope. So when I navigate to **/admin** the browser address bar redirects to **/current/public/admin/login** but it also did this previously and worked fine pre 3.5

All front end routes are working fine

**Comment by petestewartnz** [comment]
Actually the /admin routes were working fine with 3.5.2

**Comment by brandonkelly** [comment]
Sorry, was able to reproduce that, and now fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop",
  "...": "..."
}
```

Then run `composer update`.

**Comment by brandonkelly** [comment]
(Sorry, committed the wrong change earlier.)

**Comment by brandonkelly** [comment]
Craft 3.5.4 is out now with a fix for the redirect bug.

**Comment by petestewartnz** [comment]
> Craft 3.5.4 is out now with a fix for the redirect bug.

Awesome. Can confirm all is working again, thanks for the quick turn around!
