### ISSUE TITLE
Matrix block fieldId returned as array instead of string

### ISSUE THREAD

**Issue by lukebailey** [craftcms/cms#6581]
### Description
We have noticed only one small issue during our upgrade to Craft 3.5.1 (otherwise looking great). Some of our templates access regular matrix block field ID's through the Twig directive `block.fieldId` which had previously returned a string. After the Craft 3.5 update this now appears to return an Array which is throwing a PHP error `Array to string conversion` 

![image](https://user-images.githubusercontent.com/3185073/89634360-262a6880-d89d-11ea-82c8-bc8cc56031e3.png)

This can easily be resovled with a `block.fieldId|first` but we do not see this documented anywhere in the changelog - is this expected? One would assume that the matrix block only has the one field ID so is there a reason this now returns an array?

### Steps to reproduce

1. Upgrade from Craft 3.4.30 to Craft 3.5.1
2. Load a page that uses a Twig template which access a matrix block field ID
3. 500 error returned `Array to string conversion

### Additional info

- Craft version: 3.5.1
- PHP version: 7.4.5
- Database driver & version: MySQL
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
The only thing I can think of is that the `fieldId` param of Matrix block _queries_ now gets normalized to an array when executing the query;

https://github.com/craftcms/cms/blob/19ff89bd870bab917e4d196bc943daac6a3fdb47/src/elements/db/MatrixBlockQuery.php#L521-L548

`craft\elements\MatrixBlock::$fieldId` will still always be an int though. Maybe you are accessing the query’s `fieldId` param when you meant to be accessing a block’s `fieldId` property?

**Comment by lukebailey** [comment]
Thanks Brandon, I assume thats the cause then as we are passing in a matrix query block to our Twig template. Seems like this might have also been an issue for Super Table in a recent update: https://github.com/verbb/super-table/commit/0b3d6d034065cfdf72c43d1c05b7910a1573dd76
