### ISSUE TITLE
GraphiQL URL query not applied to query editor

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/cms#6583]
### Description
I noticed when you alter the GraphiQL query the URL changes with it. This got me to an idea where you could be able to debug your GraphQL queries by opening a new window with the GraphiQL editor, however this didn't work as expected.

When I browse to `/admin/graphiql?query=...` with a query previously generated by the GraphiQL editor, it instead fills the editor with data from the last submission instead from the URL.

Not sure whether this was supposed to be a feature, but it would be neat to fill in the editor automatically by a URL query param.

### Steps to reproduce

1. Browse to GraphiQL
2. Write a query and execute it
3. Copy the new URL with the query param
4. Execute an altered query
5. Re-apply the previously generated URL

### Additional info

- Craft version: 3.5.1
- PHP version: 7.2
- Database driver & version: MySQL 5.7
- Plugins & versions: SEOmatic

**Comment by andris-sevcenko** [comment]
Fixed this for the next release!

**Comment by brandonkelly** [comment]
Craft 3.5.7 is out now with the fix.
