### ISSUE TITLE
GraphQL relation limit ignored

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/cms#6596]
### Description
Per entry I only want to retrieve the first asset.

### Steps to reproduce

1.
```gql
{
  entries(section: "blog") {
    ... on blog_blog_Entry {
      pageImages(limit: 1) {
        url @transform(handle: "card", immediately: false)
      }
    }
  }
}
```
2. `pageImages` will give back multiple assets for a single entry.
```json
{
  "data": {
    "entries": [
      {
        "pageImages": [
          {
            "url": "..."
          },
          {
            "url": "..."
          }
        ]
      }
    ]
  }
}
```

### Additional info

- Craft version: 3.5.2
- PHP version: 7.2.32
- Database driver & version: MySQL 5.7
- Plugins & versions: SEOmatic

**Comment by andris-sevcenko** [comment]
This seems to be a general Craft eager-loading bug, unrelated to GraphQL. Looking into this.

**Comment by brandonkelly** [comment]
Fixed for the next release. Thanks for reporting!

**Comment by brandonkelly** [comment]
Craft 3.5.3 is out now with this fix.
