### ISSUE TITLE
Unable to find the template

### ISSUE THREAD

**Issue by strandofgenius** [craftcms/cms#6598]
### Description
I have a matrix field used for a set of content blocks and using the following to loop through the block types. 

```
{% for block in entry.blocks.all() %}
     {% switch block.type %}

     {% case 'copy' %}

           {% include '_partials/blocks/_copy.html.twig' %}

     {% default %}

           {% include '_partials/blocks/_' ~ block.type ~ '.html.twig' %}

     {% endswitch %}
{% endfor %}
```

On local, all of the templates for each block loads just fine, but after pushing it to a staging site it is unable to find only one of the templates. I've added a screenshot of the file structure and highlighted the one that isn't able to be found. I've cleared the cache, synced the database, re-deployed a few times and still isn't registering.

### Additional info

- Craft version: Craft Pro 3.4.24
- PHP version: 7.2.24
- Database driver & version: MySQL 5.6.40
- Plugins & versions:

```
Amazon S3   1.2.8
Asset Rev   6.0.2
Feed Me  4.2.3
ImageOptimize  1.6.13
Mailgun  1.4.3
Minify   1.2.10
Navigation  1.3.16
Position Fieldtype   1.0.16
Redactor    2.6.1
Retcon   2.1.0
SEOmatic    3.3.5
Super Table    2.5.0
Video Embedder    1.1.4
Wordsmith   3.2.0
```
![Screen Shot 2020-08-10 at 9 05 45 AM](https://user-images.githubusercontent.com/11370639/89791346-d3dd8780-dae8-11ea-8694-5602868522ff.png)

**Comment by Wiejeben** [comment]
Have you checked the uppercases? Happened to me once where in Git the file was written with lowercase but locally it was with an uppercase.

**Comment by strandofgenius** [comment]
@Wiejeben that was it. Thanks
