### ISSUE TITLE
Feature requests: Some core features currently missing in Craft CMS 3

### ISSUE THREAD

**Issue by dejanyy** [craftcms/cms#6601]
Some basic mostly user-specific features:

1. Sort content by author
2. View / Search content by author
3. Transfer content ownership from user A to user B without deleting user A
4. View / Search assets by the person who uploaded

These are some more fundamental issues but also represent much needed features for any serious teamwork:

5. Built-in workflow (yes, there is a plugin but it keeps breaking with each major Craft update; such a core feature should be handled by Craft, not some third party plugin)
6. Built-in audit (yes, again, there is a plugin but is very limited and its output is confusing and of limited use)

Some fundamental but probably more difficult to implement features: 

7. Entry-based permission control (for entries and assets) 
8. Asset version control (just like with entries)

**Comment by daltonrooney** [comment]
Built in custom workflows and entry-level permissions have come up for me more than once, and I agree would be amazing core features. 

Workflows discussed:
https://github.com/craftcms/cms/issues/6022
https://github.com/craftcms/cms/issues/829
https://github.com/craftcms/cms/issues/877

Entry-based permission control discussed in https://github.com/craftcms/cms/issues/4238

**Comment by brandonkelly** [comment]
Going to close this because it’s too broad. Please focus on a single request per issue.

In addition to the existing issues @daltonrooney pointed out, filtering by entry author, asset uploader, etc. is covered by #1630, which is planned for 3.6.
