### ISSUE TITLE
Unable to enter custom Redactor config before saving the field

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#6604]
### Description

The new "Enter a custom config" setting doesn't actually expose the "Custom Redactor Config" text field when the dropdown is changed; the text area only appears after the field is saved.

This applies to both new and existing fields.

There are no JS errors in the console.

Tested on Chrome 84.0.4147.105 (Mac).

![CleanShot 2020-08-10 at 09 47 20](https://user-images.githubusercontent.com/298510/89761542-e3f86580-daee-11ea-945c-5a62f917c0b2.gif)

### Steps to reproduce

1. 
2.

### Additional info

- Craft version: 3.5.2
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Craft 3.5.3 is out now with this fix.
