### ISSUE TITLE
Live preview + viewport height

### ISSUE THREAD

**Issue by mmorkt** [craftcms/cms#6605]
### Description
Live preview isn't usable if a `<div>` has an CSS height set to viewport height. 
The height of the live preview panel will expand to thousand of pixels.   

### Steps to reproduce
1. Make some div's and set them to `<div style="height:80vh">test</div>`
2. Go to live preview 

### Additional info
Nearly the same template running Craft CMS 3.4.22.1 works in live preview.
Tested the height:80vh running another template but also Craft CMS 3.5, and I'm seeing the same behavior. The JS used in live preview is making the iframe height to long. 

- Craft version: 3.5.1 +
- PHP version: 7.4
- Database driver & version: mysql 8
- Plugins & versions: neo, blitz, supertable

**Comment by brandonkelly** [comment]
This is expected behavior – see #6388 for an explanation and solution.

**Comment by brandonkelly** [comment]
We just released Craft 3.5.5, which disables the new iFrame Resizer-based behavior by default (see #6645).
