### ISSUE TITLE
Custom config validation error in CP

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#6607]
### Description

The new UI introduced in in Craft 3.5 allows us to enter a custom redactor config directly in the CP. However, when I attempt to do so, the field returns a validation error as seen in the attached image.

![image](https://user-images.githubusercontent.com/19857599/89884442-3a8aa000-dbd2-11ea-8a92-33df14ca76cc.png)

### Steps to reproduce

1. Create a field with Redactor field type

2. Select "enter a custom config" and hit save

3. Open the field edit screen, enter a valid JSON object in the config field and hit save

### Additional info

- Craft version: Pro trial 3.5.2
- PHP version: 7.2.19
- Database driver & version: MySQL 5.7.24
- Plugins & versions: Redactor 2.7.0

**Comment by andris-sevcenko** [comment]
Thanks for reporting! This has been fixed for the next Craft release in 8e3c1867b3f6f29160359abccb9e8e4e2bc3e10f.

**Comment by brandonkelly** [comment]
Craft 3.5.3 is out now with this fix.

**Comment by knynkwl** [comment]
@brandonkelly I am running into this issue with `3.5.12.1`

![Screen Shot 2020-10-12 at 4 17 18 PM](https://user-images.githubusercontent.com/4225771/95787088-cb4f2c00-0ca6-11eb-8174-b6c20c195af2.png)

**Comment by knynkwl** [comment]
@brandonkelly having one space after the closing handle bar errors it out, but it's still valid JSON.

**Comment by brandonkelly** [comment]
@knynkwl Aha. Just posted your issue over at craftcms/redactor#279 and have fixed it for the next Redactor release. In the meantime just delete that extra space.
