### ISSUE TITLE
Ability to hide field labels and instructions from the field designer

### ISSUE THREAD

**Issue by bertoost** [craftcms/cms#6608]
### Description

As I'm used to use Field Labels plugin; https://plugins.craftcms.com/fieldlabels
Craft 3.5 now has a built-in feature. Which is really great!
The plugin also has made an update to migrate their stuff to the core's feature. Which is great thinking as well.

But often I use the plugin feature of hiding field labels and instructions. This is not possible in the core's feature. Would be really nice.

### Example usage

When I create a tab named "Content" and I only put a Redactor field in it, then a field label is not necessary.
Or when you create a tab "Slider" with a Matrix field to create slides, then a field label is not necessary, since the tab is already explaining by itself.

Hope it makes sense.

**Comment by brandonkelly** [comment]
There should be a more obvious UI for this, but if you set the field label to `__blank__` it will be hidden.

**Comment by bertoost** [comment]
Thanks @brandonkelly ! Could this also be used for instructions?
A better UI for this would be lovely! A simple checkbox sounds like a plan 😄

**Comment by brandonkelly** [comment]
Added that for the next release!

<img width="324" alt="A field’s settings HUD within a field layout designer, showing that the “Label” setting now has a “Hide” checkbox beside it, which is checked" src="https://user-images.githubusercontent.com/47792/90073592-5794a100-dcae-11ea-9fa4-1baaf73db679.png">


> Could this also be used for instructions?

Instructions are already optional, so doesn’t seem necessary. Just leave the value blank in the field settings.

**Comment by bertoost** [comment]
Nice job @brandonkelly 

About instructions...
Sometimes you already have defined instructions, and want them to be removed on a particular screen. But it's less important than the label indeed.

**Comment by brandonkelly** [comment]
Craft 3.5.4 is out now with the “Hide” checkbox for field labels.
