### ISSUE TITLE
[FR] Always display the show/copy field handle UI element for admin users

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#6610]
### Description

The revised "show field handle" implementation in 3.5.3 (https://github.com/craftcms/cms/issues/6532#issuecomment-671576419) is a huge improvement over the initial implementation in 3.5.0!  

One small suggestion: It'd be great if the feature didn't require `devMode`, but that instead, the handles were always visible for admin users.

In my opinion, the feature isn't so much a "dev" thing as an "admin" thing, in that the handles simply represent an extra piece of information that can be valuable to an admin user, regardless of environment or `devMode` status. Also, admin status and not devMode grants the user permission to actually _manage_ fields, so it seems a bit arbitrary to gate this feature behind the latter. I also don’t think allowAdminChanges should play into this, as this feature is not interactive - again, it’s simply useful info.

Beyond adding a bit of visual clutter (which probably won't be a problem for admin users), having the field handles visible everywhere wouldn't actually hurt any. **This would be especially helpful for teams that haven't yet adopted project config file syncing/applying, and who might be doing admin changes (including field management) manually across environments (e.g. in production, where `devMode` is typically `false`).**

**Comment by wsydney76** [comment]
I would advocate for having a user preference for that, i think it depends on your current task whether it is usefull or not.

Prepare a demo for your client: switch it on. Show the demo: switch it off.
Your IDE has auto-completion for fields: switch it off. It has not: switch it on

I'm not so happy with the visual clutter as it may break the layout when long titles in small columns get wrapped 

![image](https://user-images.githubusercontent.com/60010597/89989409-35385e80-dc81-11ea-9bdd-1e883a40072a.png)

**Comment by mmikkel** [comment]
Sure, a user preference would be nice.

**Comment by brandonkelly** [comment]
> This would be especially helpful for teams that haven't yet adopted project config file syncing/applying, and who might be doing admin changes (including field management) manually across environments (e.g. in production, where `devMode` is typically `false`).

I understand we can’t force everyone to adopt a project config-based workflow, but this change wouldn’t have any impact on field management, where you are _defining_ the field handles, not _referencing_ them. What sort of changes are you making in production that require you to _reference_ the field handles?

If you are editing templates on production, that is something we would want to actively discourage, and avoiding showing the field handles on element edit pages is a way of discouraging it.

**Comment by mmikkel** [comment]
I meant "field management" in terms of creating and/or editing fields. If the developer is not applying PC files, they're either syncing databases, or doing the content modelling twice. In the latter case, it's handy to be able to quickly reference/check field values. 

I'm sure there are other valid use cases, too – the handle is just a useful bit of info, and I don't really understand how showing it (to admin users and/or users who opt in through a user preference) is encouraging or discouraging any particular workflow.

**Comment by brandonkelly** [comment]
Fair enough. Just went ahead and made it an admin-only user preference for the next release.

**Comment by mmikkel** [comment]
That's great - thanks @brandonkelly

**Comment by brandonkelly** [comment]
Craft 3.5.4 is out now with the new user preference.
