### ISSUE TITLE
Can't save Images in some Multisites

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#6611]
### Description
Movies say more as words...
https://www.dropbox.com/s/388l364zlqpm9ik/cantsaveimages.mov?dl=0

Description:

I upload an Image and rename it in Multisite A > Fine
I switch to Multisite B to rename it > Doesn't work

No errors. Can reproduce it with other images too. 
The sites where saving is not possible are different.

### Additional info

- Craft version: 3.4.29.1
- PHP version: 7.1.33
- Database driver & version: 5.7.31

**Comment by andris-sevcenko** [comment]
> The sites where saving is not possible are different.

This definitely makes it sound environmental. Can you send over your composer.lock, composer.json file, and a DB backup as well to support@craftcms.com and reference this ticket?

**Comment by davidhellmann** [comment]
@andris-sevcenko send a mail few seconds ago with: Database, composer.json and composer.lock

Sorry for the delay!

**Comment by davidhellmann** [comment]
After writing with @angrybrad  it looks like it's more a problem with ImageOptimize (1.6.14) and maybe @khalwat can jump in here? When I deactivate the plugin the problem is gone. With activated plugin the problem is hard to reproduce. 99% it works.

**Comment by khalwat** [comment]
So I'm not gonna say never but... the way the plugin works, it'd be surprising if it had any effect here.

It just will automatically create transforms from the image you upload.

**Comment by brandonkelly** [comment]
Going to close this as it doesn’t seem to be a Craft bug.
