### ISSUE TITLE
Can't save a level 2 category, it always saves its parent instead

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#6612]
### Description

In a Categories field, when selecting a category that is level 2 (and thus has a parent) and saving the owner element, it results in the parent being selected instead of the child. See screenshots.

Before saving:
<img width="1244" alt="Screen Shot 2020-08-12 at 09 27 19" src="https://user-images.githubusercontent.com/378974/89987338-32883a00-dc7e-11ea-91b2-abaff249a132.png">

Categories element selector looks like this (correct)
<img width="320" alt="Screen Shot 2020-08-12 at 09 28 21" src="https://user-images.githubusercontent.com/378974/89987348-37e58480-dc7e-11ea-9a25-cb76a1c0636f.png">

After saving:
<img width="507" alt="Screen Shot 2020-08-12 at 09 27 58" src="https://user-images.githubusercontent.com/378974/89987352-3ae07500-dc7e-11ea-9837-b21f73d3d307.png">

Categories element selector looks like this (only parent selected)
<img width="419" alt="Screen Shot 2020-08-12 at 09 28 06" src="https://user-images.githubusercontent.com/378974/89987388-4895fa80-dc7e-11ea-92a1-40830fb3bf9a.png">

### Steps to reproduce

See screenshots

### Additional info

- Craft version: 3.4.30
- PHP version: 7.4.8
- Database driver & version: PostgreSQL 10.12
- Plugins & versions: -

**Comment by boboldehampsink** [comment]
This only seems to happen when newly creating an entry. When the entry is saved, selecting the level 2 again now works.

**Comment by boboldehampsink** [comment]
I tried to play with the branch limit but that didn't do anything

**Comment by brandonkelly** [comment]
Strange… I’m not able to reproduce this (testing in 3.5, but can’t think of anything that changed in 3.5 that would have helped improve this). Even if Branch Limit was set to `1`, you should still be able to select the child since it’s part of the same branch.

Can you test with 3.5 and see if that fixes it? And if not, please send your Composer files and a database backup to support@craftcms.com and we can look into it from there.

**Comment by boboldehampsink** [comment]
I found this to be on my end (sorry for that) - I queried the field on a BeforeSaveEntry event with `level(1)` on the criteria. Since the criteriamodel is by reference, this is what happened.

Fixed by changing `$entry->thisField->level(1)->one()` to `(clone $entry->thisField)->level(1)->one()` in the beforeSave event.

**Comment by brandonkelly** [comment]
Aha! Good catch.
