### ISSUE TITLE
Make field handle clipboard element tabindex -1

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/cms#6613]
### Description
I like the addition of showing the field handle a lot when devMode is enabled. However would you consider making it tabindex -1 so it is ignored when switching fields by using the tab key?

Don't get me wrong I think it does have its uses, however in my opinion I prefer it switching between fields instead of field -> handle -> field -> handle.

Thanks!

**Comment by brandonkelly** [comment]
No, as that would render it impossible to access via the keyboard. However I’ve just made the field handles optional via a new user preference for the next release (see #6610), so if you don’t like it you can just turn them off.
