### ISSUE TITLE
Site group heading in site dropdown shouldn't show if there are no sites to display in that group

### ISSUE THREAD

**Issue by benface** [craftcms/cms#6615]
### Steps to reproduce

1. Create two site groups, each with two sites: Group A with Site 1 and Site 2, and Group B with Site 3 and Site 4.
2. Create a new user and only give them permission to view and edit Site 1 and Site 2.
3. Log in as that user, and go edit an entry. Click on the site dropdown.

**Expected result:** There is a "Group A" heading in the dropdown, under which Site 1 and Site 2 appear as options. There is no "Group B" heading because the user doesn't have access to any site in that group.
**Actual result:** There is a "Group A" heading with the Site 1 and Site 2 options as expected, but there is also a "Group B" heading with no options under it.

### Additional info

- Craft version: 3.5.3
- PHP version: 7.3.13
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
Hm, I’m not able to reproduce this. Can you please send your Composer files, plus a database backup, over to support@craftcms.com?

**Comment by benface** [comment]
@brandonkelly Done! Zendesk ticket ID 8407.

**Comment by brandonkelly** [comment]
Fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 3.5.6 is out now with that fix.
