### ISSUE TITLE
duplicated 'delete permanently' button for trashed categories

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#6619]
there are two 'delete permanently' action buttons when trashed item in category admin page is selected.

**Additional info**
- Craft version: 3.5.3
- PHP version: 7.2

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by vnali** [comment]
Thanks @brandonkelly
I don't know if this is related or not but soft deleted users and assets don't have delete permanently action.  Does hard delete is implemented for users and assets?

**Comment by brandonkelly** [comment]
@vnali Just posted a new issue about that: #6628

**Comment by brandonkelly** [comment]
Craft 3.5.4 is out now with a fix for the duplicate buttons.
