### ISSUE TITLE
Field handles in quick-edit dialogs are cramped & unflattering

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#6620]
### Description

The new field handle utility doesn't fit very nicely on the inline editor and could really use some love.

![image](https://user-images.githubusercontent.com/3810939/90082984-3c8e5500-dcdf-11ea-9bc9-ad858acb36ba.png)

Related: #6587

### Additional info

- Craft version: 3.5.3

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.4 is out now with a fix for this.
