### ISSUE TITLE
Image thumbnails not loaded in live preview

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#6621]
### Description

Seems like image thumbnails are lazy loaded in edit forms, which works fine for me in the 'standard' screen, but not when using live preview or HUD modals:

![image](https://user-images.githubusercontent.com/60010597/90113320-75671200-dd51-11ea-97d6-b08c2e6696dd.png)

Happens also with the Embedded Assets plugin, not sure whether its a core or plugin issue here.

### Steps to reproduce

1. Open an entry with a lot of matrix blocks, with block containing an assets field (set to large thumbnails) somewhere at the bottom
2. Do not scroll
3. Open live preview
4. Scroll to the bottom
5. No thumbnail is loaded

Using latest Chrome (84.0.4147.105)

### Additional info

- Craft version: latest 3.5.3 dev
- PHP version: 7.4.7
- Database driver & version:
- Plugins & versions: Embedded Assets

**Comment by brandonkelly** [comment]
Working fine on my end, so guessing this is related to the Embedded Assets plugin.

**Comment by wsydney76** [comment]
Disabled the Embedded  Assets plugin, but assets field still miss thumbnails in preview in case they were not already loaded on the 'standard' page.

**Comment by brandonkelly** [comment]
Are you getting any JavaScript errors on the page?

**Comment by wsydney76** [comment]
No, no JavaScript Error. Can say that while we have entries always missing lazy loaded thumbnails in preview, there is another one working fine while the browser window is maximized (1920x1080 screen), but fails when the browser window is set to a smaller height (or having dev tools open at the bottom). The default view always works.

**Comment by brandonkelly** [comment]
Hm, just re-tested locally and it’s definitely working as expected on my end. Here’s what I did:

1. Loaded an Edit Entry page for an entry with an image pretty far down the page, with the browser dev tools open to ensure a small viewport.
2. Clicked “Preview”
3. Waited until the Network tab showed all requests were complete.
4. Cleared the Network tab.
5. Scrolled the editor pane down to the bottom.

As you can see, the act of scrolling resulted in additional images getting lazy-loaded, including the thumbnail I was expecting:

<img width="1188" alt="Screenshot of Live Preview within the Craft control panel, with the browser’s Network tab open" src="https://user-images.githubusercontent.com/47792/90333686-c1e26580-df7c-11ea-821e-f4dbffbd61f8.png">

Can you think of any other plugins/modules you have installed that could be interfering? Or perhaps some custom CSS/JS you’ve added?

**Comment by wsydney76** [comment]
Disabled all modules/plugins and the problem persists.

Could reproduce this on a fresh install (running into #6650...) though, adding some random selection of image/text blocks, and it sometimes works, sometimes it doesn't. Depending on ... no idea what, looks like it's not only the overall length, but also the number of images. 

Might be that lazy loading images in preview does not work at all for me.

![image](https://user-images.githubusercontent.com/60010597/90373723-a9ed0d80-e072-11ea-89de-a1f4cb503713.png)

Can confirm for Chrome / Firefox / Edge, also in incognito/private mode (so probably no extensions involved), on different machines (all Windows 10 though), devMode on/off.
 
Could send the database + the used images, if that helps.

PS.
Personally it's a minor problem, but it's that kind of things that make a system look unreliable for new users.

**Comment by brandonkelly** [comment]
Is this happening on a live website that we could check out? If so can you please send admin credentials over to support@craftcms.com ?

**Comment by wsydney76** [comment]
@brandonkelly Sorry nothing live yet (thanks to COVID-19, no festivals, no festival site relaunches, just trying to be prepared in case real live comes back..)

But as it happens also in a very basic fresh install, i'm quite sure there is nothing special going on server side.

Just sent database backup, composer files and images (for web/images) to support.

**Comment by wsydney76** [comment]
@brandonkelly Thanks for picking this issue up again.

One thing i noticed reproducing the issue in 3.7.0-beta.3: (Just add a lot of matrix block with an image )

![image](https://user-images.githubusercontent.com/60010597/123290114-4b55b300-d511-11eb-9c98-8a76485ebe52.png)

There is an  img tag inside div#elementthumb, which looks like it is inserted dynamically when scrolled into view.

However in live preview, there is no img tag inserted:

![image](https://user-images.githubusercontent.com/60010597/123290833-dfc01580-d511-11eb-937e-4bf106ef0755.png)

![image](https://user-images.githubusercontent.com/60010597/123290957-f8303000-d511-11eb-852c-4a9584b1b354.png)

**Comment by brandonkelly** [comment]
Try opening your browser’s Network tab, filter the requests to Images, then reload the page. Do you see any images that are hanging or failing to load, either before or after clicking on Preview and scrolling down the pane?

**Comment by wsydney76** [comment]
10 matrix blocks with 1 image each:

No live preview:

* Load page: the first 4 images load
* Scrolling down slowly: the rest of the images load one after the other

Live preview:

* Load page: the first 4 images load
* Click Preview
* Empty network log
* Scrolling down: no request is logged at all, also no script error in the console tab

**Comment by brandonkelly** [comment]
So weird. I’m just not seeing that same behavior locally.

![Screen recording of loading Live Preview on an entry, clearing the Network activity log, and showing how as I scroll down, additional images will get lazy-loaded.](https://user-images.githubusercontent.com/47792/123331469-2f8fe400-d4f4-11eb-9c3f-b8145c275271.gif)

Are you adding any custom JS code to the control panel that could be interfering in some way?

**Comment by wsydney76** [comment]
No custom js code, verified that on a fresh install.

But I don't know if  the following  explains or increases the weirdness:

Created a demo site, and there it works for me too, same with a local demo copy.

I think the difference is that the demo uses a Redactor field, which we usally try to avoid.

Added a Redactor field to my test cases and - hey, it works!  Removed the Redactor field again - it fails.

Changed all relevant occurrences of Redactor to Plaintext in the demo - and now it fails there too.

https://casual-roughy-a391d11.happylager-beta.craftdemos.io/admin/entries/news/2129-test-image-thumbnails-in-live-preview?draftId=1

**Comment by brandonkelly** [comment]
Aha! Good catch!

**Comment by brandonkelly** [comment]
Got it fixed for the next release 🎉 🎉

**Comment by brandonkelly** [comment]
3.7.0-beta.4 is out now with the fix. It will be in the next 3.6 release as well.
