### ISSUE TITLE
Consider showing UI elements/tabs in live preview / HUD modals

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#6622]
### Description

Great feature to hide a title when the context is obvious by tab or heading, however this context is gone when using live preview;  the input is orphaned, the user lost.

In general we would like to (optionally?) see tab names and ui elements also in preview, as it can be a long unstructured form, difficult to orientate yourself, and missing useful tips and warnings.

**Comment by brandonkelly** [comment]
Related: #6587

**Comment by mmikkel** [comment]
Really hope to see this at some point soon-ish. 

IMO the big problem with Preview has always been that the author loses all edit form context and focus when it opens. Having tabs and UI elements inside the Preview panel would be super helpful in this regard (especially if Craft was able to retain the currently active tab and/or focused field from the edit form), but the ideal solution would be if there was a way to open the preview panel without actually replacing the actual edit form.

**Comment by brandonkelly** [comment]
This is halfway resolved for 3.7 – we’ve solved it for element editors, but not Live Preview yet. See #8017.
