### ISSUE TITLE
[3.5.3] Enabled everywhere should turn off if one site is turned off

### ISSUE THREAD

**Issue by joshua-martin** [craftcms/cms#6623]
### Description

![2020-08-13 10 20 25](https://user-images.githubusercontent.com/1694957/90124003-9b8fb080-dd57-11ea-8e35-02cf9659d6d3.gif)

Semantically this feels wrong for me. `Enabled everywhere` is binary, so if you've turned the element off for one site, `Enabled everywhere` is no longer true, so it feels like it should be fully turned off instead of moved into the middle.

I propose changing the wording to `Enabled`, so that allows it to still show in the middle to indicate it's partly enabled, but doesn't come with the binary nature of the current label.

**Comment by brandonkelly** [comment]
Craft 3.5.4 is out now with this change.
