### ISSUE TITLE
about deprecation of assembleLayout()

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#6625]
**Description**
i used to call assembleLayout() in my code to create and save field layout programmatically like [this answer](https://craftcms.stackexchange.com/a/21570) from Stackoverflow.
it seems because of changes in Field layout designer in 3.5, some functionality of assembleLayout() is applied in assembleLayoutFromPost() with few changes and assemblelayout() is deprecated now.
i know that function is not removed yet but my question is can we have assemblelayout() back to call it and create field layouts again in our plugin? any special reason that this function is deprecated?

**Comment by brandonkelly** [comment]
It was deprecated because we are no longer using the method internally, and it only covers a fraction of the available field layout features now available in Craft 3.5.

See `assembleLayoutFromPost()` for an example of how to assemble the layout manually.
