### ISSUE TITLE
Naming Global Set "Errors" breaks recommended forgot-password/reset-password templates

### ISSUE THREAD

**Issue by spencech** [craftcms/cms#6626]
### Description
I created a global set called "Errors" with handle "errors" meant to store custom validation errors in a matrix block field, and inadvertently broke the forgot-password / reset-password templates that use the following twig template:
&lt;div class="errors"&gt;
    {% if errors is defined %}
        &lt;ul class="errors"&gt;
            {% for error in errors %}
            &lt;li&gt;{{ error }}&lt;/li&gt;
            {% endfor %}
        &lt;/ul&gt;
    {% endif %}
&lt;/div&gt;

because errors was defined in the global space, it was trying to print the global field instance into the DOM and breaking.

### Steps to reproduce

1. Create Global Set called "Errors" with handle "errors"
2. Add a matrix block that allows user to create multiple plain text error messages 
3. Visit the forgot-password / reset-password templates that use aforementioned snippet 
4. See server error

I'm assuming I'm not supposed to set the global set handle "errors", and should receive a "reserved" error when attempting to save that setting.

### Additional info

- Craft version: Craft Pro 3.4.25
- PHP version: 7.0.33
- Database driver & version: MySQL 5.7.26
- Plugins & versions: Feed Me | 4.2.3, Redactor | 2.6.1

**Comment by brandonkelly** [comment]
Thanks for reporting that. Just made `errors` a reserved handle for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.4 is out now with that change.
