### ISSUE TITLE
GraphQL transform quality setting doesn't affect webp images

### ISSUE THREAD

**Issue by weotch** [craftcms/cms#6629]
### Description

I'm using a query like this to create a crop of an asset:

```gql
query {
  asset(id:24458) {
    url @transform(
      width: 1800, 
      immediately: true, 
      format:"webp",
      quality:80)
  }
}
```

No matter what I change `quality` to, the resulting image is the same exact filesize, even though it gets created in a unique directory (like `_1800xAUTO_crop_center-center_80_none/24458`).  I've tried using both GD 7.4.3 and Imagick 3.4.4.  

JPGs are, correctly, affected by the quality setting.

### Steps to reproduce

1. Upload an image to assets (I was using [this one](https://clifbar.sfo2.digitaloceanspaces.com/cms/LUNA_EB_Homepage_Marquee_Desktop_2880x1500.jpg) to test with)
2. Make a graphql query like the above for a `webp` format and two different quality settings
3. The resultant images should be identical.

### Additional info

- Craft version: 3.5.3 and 3.4.29.1
- PHP version: 7.4.1
- Database driver & version: MySQL 8.0.19
- Plugins & versions: None

**Comment by andris-sevcenko** [comment]
Thanks! Turned out to be a Craft issue - just fixed it for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.5 is out now with that fix.
