### ISSUE TITLE
As a Website Manager, I Want to See All Entries with Drafts

### ISSUE THREAD

**Issue by PatrickMessierGoC** [craftcms/cms#6632]
### Description
As my website is being edited by many people at once, it is sometime hard to manage all the work in progress. It would be nice to have the hability to easilly list or filter all entries with draft. 
Maybe the "Drafts" view could be enhanced to included those drafts as well (instead of only filtering the entries that have never been saved) or an another view option could be added.
![drafts](https://user-images.githubusercontent.com/45016166/90189113-9b5cd880-dd8a-11ea-992a-714618040324.PNG)

**Comment by brandonkelly** [comment]
It will take a bit of UI changes to make this happen in a way that’s actually useful.

In the meantime, I’ve just made it possible (as of the next release) to register a custom “Drafts” entry source using the [EVENT_REGISTER_SOURCES](https://docs.craftcms.com/api/v3/craft-base-element.html#event-register-sources) event, which only returns entry drafts. To do it, create a [module](https://craftcms.com/docs/3.x/extend/module-guide.html) with the following code:

```php
use craft\elements\Entry;
use craft\events\RegisterElementSourcesEvent;
use yii\base\Event;

// ...

public function init()
{
    // ...

    Event::on(Entry::class, Entry::EVENT_REGISTER_SOURCES, function(RegisterElementSourcesEvent $e) {
        $e->sources[] = [
            'key' => 'drafts',
            'label' => 'Drafts',
            'criteria' => [
                'drafts' => true,
            ],
        ];
    });
}
```

You can customize the `criteria` beyond just setting `drafts = true` if desired.

**Comment by brandonkelly** [comment]
Craft 3.5.13 is out now with that change ✨

**Comment by brandonkelly** [comment]
The next release is going to allow you to add a “Drafts” column to entry indexes, which lists any active drafts for each entry (see #7473). Will leave this open as it’s still not possible to _filter_ entries depending on whether they have drafts, besides via the custom source solution mentioned above.

**Comment by brandonkelly** [comment]
This is fully resolved now – see https://github.com/craftcms/cms/issues/7517#issuecomment-776363856.

**Comment by PatrickMessierGoC** [comment]
@brandonkelly That looks great. Looking forward to test it. Thanks.

**Comment by brandonkelly** [comment]
Craft 3.6.5 is out now with that change.
