### ISSUE TITLE
Field Layout -> field -> instructions are displayed twice

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#6634]
### Description
In the latest version, field instructions are displayed twice. I don't have the time to dig through every line but I guess it's somewhere in this commit? https://github.com/craftcms/cms/commit/089d6b87236ada536422de59caa18543cda3773a#diff-738f284b7f4bc7d9db084464155ae5e4

### Steps to reproduce

1. set an instruction for a field
2. see it's rendered twice

![image](https://user-images.githubusercontent.com/6122122/90237696-fd6a1c00-de24-11ea-8371-38fb4b7baf49.png)

**Comment by Anubarak** [comment]
Uff forget it... it was caused by a plugin.
Sorry

**Comment by brandonkelly** [comment]
I moved the instructions out of the `<div class="heading">` in 3.5.4. Surprised it caused a plugin issue – what plugin was it?
