### ISSUE TITLE
JavaScript error on edit pages when using Safari

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#6635]
### Description

I’m getting an error on edit pages when using Safari 12.0

```
Error: Syntax error, unrecognized expression: label[for="enabled"
```

The revisions dropdown and save dropdown are not working and are also missing rounded borders at the right side.

### Additional info

- Craft version: 3.5.4
- PHP version: 7.3.7
- Database driver & version: PostgreSQL 11.6
- Plugins & versions: n/a
- Web browser: Safari 12.0

**Comment by brandonkelly** [comment]
Whoops, forgot a `]`. Wasn’t seeing that error in Safari 13 though, so I guess they got a little more lenient. Also not seeing the border radius issue in Safari 13; not sure what I could do to fix that. Sounds like a browser bug.

**Comment by carlcs** [comment]
The border radius was missing as a consequence of the JS error. Updating to 0a60678 fixed both issues.

**Comment by brandonkelly** [comment]
Oh… weird! But I’ll take it :)

**Comment by carlcs** [comment]
Because of that error the `.menu` element wasn’t moved in the DOM, and that broke the `last-child` selector logic within the `.btngroup` 😉

**Comment by brandonkelly** [comment]
Ah, that makes sense!

**Comment by brandonkelly** [comment]
Craft 3.5.5 is out now with that fix.
