### ISSUE TITLE
Fetching elements after manually setting different site doesn't work anymore on Craft 3.5

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#6636]
### Description

Fetching elements after manually setting different site doesn't work anymore on Craft 3.5

### Steps to reproduce

1. `Craft::$app->getGlobals()->getSetByHandle('globals')` -> GlobalSet::$siteId = 1 (default)
2. `Craft::$app->getSites()->setCurrentSite(2)`
1. `Craft::$app->getGlobals()->getSetByHandle('globals', 2)` -> GlobalSet::$siteId is still 1, expected 2 (manually set)

This worked in 3.4

### Additional info

- Craft version: 3.5.4
- PHP version: 7.4.9
- Database driver & version: PostgreSQL 11.8
- Plugins & versions: -

**Comment by brandonkelly** [comment]
Was able to reproduce & fix this for the next release. No idea how this would have worked in 3.4 though ¯\\\_(ツ)\_/¯

**Comment by brandonkelly** [comment]
Craft 3.5.5 is out now with that fix.

**Comment by boboldehampsink** [comment]
Thanks Brandon, this one prevented me from updating my last site to 3.5 (although it's now stuck again on https://github.com/craftcms/cms/issues/6549) ^^
