### ISSUE TITLE
Showing field handles in CP not working.

### ISSUE THREAD

**Issue by geenious** [craftcms/cms#6638]
### Description
Updated site from v3.5.2 -> v3.5.4 and the field handles don't show anymore in the CP. They don't show in devMode or when pressing Option/ALT key.

### Steps to reproduce

1. Install Craft v3.5.4

### Additional info

- Craft version: 3.5.4
- PHP version: 7.3.9
- Database driver & version: MySQL 5.7.26
- Plugins & versions: none

**Comment by brandonkelly** [comment]
They are now shown per a new user preference for admins.
