### ISSUE TITLE
[3.5] Instruction styles in "New block type" modal are a bit off

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#6640]
### Description

Not 100% sure when this was introduced, but one of the latest 3.5 releases. The instructions styles in the "New block type" modal seem to be broken/missing:

![image](https://user-images.githubusercontent.com/298510/90308690-c443b180-dee1-11ea-8ed7-785531e583b1.png)

### Steps to reproduce

1.
2.

### Additional info

- Craft version: 3.5.4
- PHP version:
- Database driver & version:
- Plugins & versions: none

**Comment by brandonkelly** [comment]
Thanks for reporting that. Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.5 is out now with that fix.
