### ISSUE TITLE
3.5.4: default instructions-field of field is not escaped in CP causing rendering of that and following fields to fail

### ISSUE THREAD

**Issue by bencresty** [craftcms/cms#6642]
### Description
When having instructions in a field, like 'This title will be used in the html <title> tag', and use that field in a global set (or entry?), that field and all following fields in that entry or globals are not rendered.
Looks like the instructions field is not escaped while rendering and the html in the description (which is meant be only text for the viewer as a description) disturbes the rendering of the page. This wasn't causing issues in 3.4.x so I guess these were escaped in 3.4.x.

### Steps to reproduce

1. Open CP
2. Add things like <title> in the instructions field of a field while setting up a field
3. Add that field to a globals set (and add some fields below it as a test)
4. Open that globals set and see that the field isn't rendered completely and all fields below aren't rendered at all

### Additional info

- Craft version: 3.5.4

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed now for the next release.

You can fix immediately by wrapping the `<html>` tag in backticks:

```md
This title will be used in the html `<title>` tag
```

**Comment by brandonkelly** [comment]
Craft 3.5.5 is out now with that fix.
