### ISSUE TITLE
[Preview Feature] CSS position fixed elements are no longer floating with respect to the viewport in the Preview of entries.

### ISSUE THREAD

**Issue by hsh3nl** [craftcms/cms#6643]
### Description
Our Entry twig page contains a CSS fixed positioned HTML element, allowing that HTML element to float with respect to the device's viewport. In the preview page of the entry (accessed via the Preview button in the Entry page), that HTML element is positioned correctly in Craft 3.4. With Craft 3.5.4, the supposed fixed element now hidden and appended at the end of the Preview page.

This could possibly be an issue with the iframe-resizer for the Preview's iframe. This is the current iframe.lp-preview HTML tag:
![Screen Shot 2020-08-16 at 4 38 36 PM](https://user-images.githubusercontent.com/43397388/90330629-d9ebd080-dfe0-11ea-9365-0026f9c74246.png)

In the iframe.lp-preview tag, removing the [scrolling]="no" attribute and changing the height attribute to "auto" fixes this issue:
![Screen Shot 2020-08-16 at 4 42 20 PM](https://user-images.githubusercontent.com/43397388/90330634-ef60fa80-dfe0-11ea-9a17-d760e8b0adcc.png)

### Steps to reproduce

1. Have a HTML tag in the Entry twig page to be positioned fixed (CSS).
2. Verify that the HTML tag is positioned correctly in any published entry page.
3. Go to the CraftCMS dashboard, click on any entry and attempt to Preview the entry.
4. The CSS positioned fixed element is not floating with respect to the viewport in the Preview's iframe.

### Additional info

- Craft version: Craft 3.5.4
- PHP version: 7.2.32
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
Contact form | 2.2.7
Contact form extensions | 1.2.1
Contact form honeypot | 1.0.2
Content stats | 2.1.2
Control panel nav | 3.0.13.1
Cookies | 1.1.12
Patrol | 3.1.3
Tags | 1.0.7
Wheel form | 2.5.0
XML Sitemap | 1.3.0

**Comment by mmikkel** [comment]
@hsh3nl Disabling Iframe Resizer might fix this issue for you – add this to your `config/general.php`:

```php
'previewIframeResizerOptions' => false,
```

**Comment by hsh3nl** [comment]
@mmikkel Thanks for the suggestion. I wasn't aware that this feature was added and enabled by default.

**Comment by brandonkelly** [comment]
Yeah, this is a duplicate of #6388, and fixed in Craft 3.5.5 (released today), by disabling the new iFrame Resizer-based behavior by default (see #6645).
