### ISSUE TITLE
Expanded HUD view

### ISSUE THREAD

**Issue by rynpsc** [craftcms/cms#6647]
### Description

The current HUD when inline editing can get a little cramped and is missing UI elements such as tabs along with sidebar meta information / fields. So would like to propose replacing the inline HUD with an expanded view (full element edit page) shamelessly ~~stealing~~ borrowing from [Statamic V3 stacks feature](https://v3.statamic.com/blog/stacks-on-stacks-on-stacks).

This would solve most of the current HUD related issues including but not limited to https://github.com/craftcms/cms/issues/6622, https://github.com/craftcms/cms/issues/6587, https://github.com/craftcms/cms/issues/4129.

**Comment by brandonkelly** [comment]
Hah… this is actually the plan for 3.6 ;)

**Comment by brandonkelly** [comment]
This is resolved for 3.7! See #8017.
