### ISSUE TITLE
Setup: Inconsistent environment variable names: PRIMARY_SITE_URL vs. DEFAULT_SITE_URL

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#6650]
### Description

Creating a fresh install sets this in .env:

`PRIMARY_SITE_URL="http://temp2.local"`

and this in cp site sittings:

![image](https://user-images.githubusercontent.com/60010597/90367134-a785b600-e068-11ea-9e15-16d92e90afb6.png)

Creates errors like `Template not found: $DEFAULT_SITE_URL/post/first-post`

As expected, changing the site settings to `$PRIMARY_SITE_URL` fixes that.

### Steps to reproduce

1 composer create craftcms/craft
2. .\craft setup

### Additional info

- Craft version: 3.5.4
- PHP version: 7.4.7
- Database driver & version: MySQL 5.7.14
- Plugins & versions: -

**Comment by brandonkelly** [comment]
Doh, not sure how I missed that in 7e18bc5f336181b40cfbdfea75ef60499e1c9a34. Fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 3.5.5 is out now with that fix.
