### ISSUE TITLE
Could not acquire a lock to save a revision for element

### ISSUE THREAD

**Issue by jerome2710** [craftcms/cms#6652]
### Description
Stumbled across this issue a few times now. I'm unable to `Save as a new {type}` when editing an entry. I can however duplicate an entry by checking it from the element index.

```
2020-08-14 14:46:47 [-][1][...][error][yii\db\Exception] yii\db\Exception: Could not acquire a lock to save a revision for element 11533 in /.../vendor/craftcms/cms/src/services/Revisions.php:78
Stack trace:
#0 /.../vendor/craftcms/cms/src/elements/Entry.php(1477): craft\services\Revisions->createRevision(Object(craft\elements\Entry), NULL, NULL)
#1 /.../vendor/craftcms/cms/src/services/Elements.php(2372): craft\elements\Entry->afterPropagate(false)
#2 /.../vendor/craftcms/cms/src/services/Elements.php(691): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false, true)
#3 /.../vendor/craftcms/cms/src/controllers/EntriesController.php(380): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#4 [internal function]: craft\controllers\EntriesController->actionSaveEntry(true)
#5 /.../vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /.../vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#7 /.../vendor/craftcms/cms/src/web/Controller.php(181): yii\base\Controller->runAction('save-entry', Array)
#8 /.../vendor/craftcms/cms/src/controllers/EntriesController.php(439): craft\web\Controller->runAction('save-entry', Array)
#9 [internal function]: craft\controllers\EntriesController->actionDuplicateEntry()
#10 /.../vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /.../vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#12 /.../vendor/craftcms/cms/src/web/Controller.php(181): yii\base\Controller->runAction('duplicate-entry', Array)
#13 /.../vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('duplicate-entry', Array)
#14 /.../vendor/craftcms/cms/src/web/Application.php(294): yii\base\Module->runAction('entries/duplica...', Array)
#15 /.../vendor/craftcms/cms/src/web/Application.php(597): craft\web\Application->runAction('entries/duplica...', Array)
#16 /.../vendor/craftcms/cms/src/web/Application.php(273): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#17 /.../vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /.../web/index.php(40): yii\base\Application->run()
#19 {main}
```

### Steps to reproduce

1. Edit an entry
2. Click `Save as a new {type}` in the save-button dropdown.

### Additional info

- Craft version: 3.5.3
- PHP version: 7.2.24

**Comment by jerome2710** [comment]
I just noticed there was another update, this issue is still active in 3.5.4.

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you please send a database backup and your Composer files over to support@craftcms.com so we can try reproducing it on your install?

**Comment by reachpriti12** [comment]
I am facing this error. Is this ticket solved? 

I am using craft 3.5.9

![image](https://user-images.githubusercontent.com/31907075/93285171-5c59f100-f828-11ea-8c93-728c41f8759d.png)

**Comment by paulgoodfield** [comment]
Have also just had a client report this problem on Craft 3.4.30 and PHP version 7.0.33

**Comment by brandonkelly** [comment]
If you are able to reproduce it, please send a database backup and your Composer files over to support@craftcms.com and we can look into it from there.

**Comment by masiorama** [comment]
Hello @brandonkelly, I am experiencing the same issue while trying to duplicate an entry.
I just sent the email to support@ with the required files. Thanks!

**Comment by brandonkelly** [comment]
At least in one case we’ve now looked into, this was due to an `EVENT_AFTER_SAVE` event handler which was trying to resave revision entries. The fix was to ensure that the entry being saved wasn’t a draft or revision:

```php
if (ElementHelper::isDraftOrRevision($entry)) {
    return;
}
```

**Comment by dimitrihilverda** [comment]
I still have this problem with Craft CMS 3.6.6 PRO

`yii\db\Exception: Could not acquire a lock to save a revision for element 7056 in /home/****/domains/****.nl/project/vendor/craftcms/cms/src/services/Revisions.php:78
Stack trace:
#0 /home/****/domains/****.nl/project/vendor/craftcms/cms/src/elements/Entry.php(1585): craft\services\Revisions->createRevision(Object(craft\elements\Entry), NULL, '')
#1 /home/****/domains/****.nl/project/vendor/craftcms/cms/src/services/Elements.php(2502): craft\elements\Entry->afterPropagate(false)
#2 /home/****/domains/****.nl/project/vendor/craftcms/cms/src/services/Elements.php(755): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, true, true)
#3 /home/****/domains/****.nl/project/vendor/craftcms/cms/src/controllers/EntriesController.php(382): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#4 [internal function]: craft\controllers\EntriesController->actionSaveEntry(true)
#5 /home/****/domains/****.nl/project/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /home/****/domains/****.nl/project/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#7 /home/****/domains/****.nl/project/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('save-entry', Array)
#8 /home/****/domains/****.nl/project/vendor/craftcms/cms/src/controllers/EntriesController.php(441): craft\web\Controller->runAction('save-entry', Array)
#9 [internal function]: craft\controllers\EntriesController->actionDuplicateEntry()
#10 /home/****/domains/****.nl/project/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /home/****/domains/********nce.nl/project/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#12 /home/****/domains/****.nl/project/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('duplicate-entry', Array)
#13 /home/****/domains/****.nl/project/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('duplicate-entry', Array)
#14 /home/****/domains/****.nl/project/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('entries/duplica...', Array)
#15 /home/****/domains/****.nl/project/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction('entries/duplica...', Array)
#16 /home/****/domains/****.nl/project/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#17 /home/****/domains/****.nl/project/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /home/****/domains/****.nl/project/web/index.php(22): yii\base\Application->run()
#19 {main}
Additional Information:
Array
(
)
`

**Comment by brandonkelly** [comment]
@dimitrihilverda Is that happening consistently? Are you overriding the `mutex` component in `config/app.php` by chance?

**Comment by mildlygeeky** [comment]
I ran into this - I have a DB backup if you're interested. It followed some aggressive DB clean-up by pruning revisions (telling Craft to limit max revisions to 0, followed by garbage collection).

Not sure if that's the reason, but reverting to a DB backup from before I did this made everything go back to normal.

**Comment by KavindaHarshana** [comment]
Untick this 
<img width="379" alt="Screenshot 2021-09-29 at 7 11 08 PM" src="https://user-images.githubusercontent.com/51896118/135283197-846aa6c5-6013-461c-b67a-36dcd08f5286.png">
