### ISSUE TITLE
Remove checkerboard in thumbs for non-image files

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#6653]
![image](https://user-images.githubusercontent.com/7516543/90395732-4c1ded00-e095-11ea-9fd7-ad74d6d9f62b.png)

_Originally posted by @carlcs in https://github.com/craftcms/cms/pull/6646#issuecomment-674850366_

**Comment by brandonkelly** [comment]
Done for the next release :) https://github.com/craftcms/cms/pull/6646#issuecomment-675039993
