### ISSUE TITLE
400 bad request when updating plugin license

### ISSUE THREAD

**Issue by bymayo** [craftcms/cms#6657]
I purchased plugins through the CMS on a production domain. It never left the popup where you enter your card details, it just kept spinning. I logged in to Craft ID and I could see the licenses appear in there, but the popup stayed.

When I try to manually input the license codes I get a `A server error occurred` message at the top of the CP and in console I can see:

```
POST https://website.co.uk/index.php?p=admin/actions/app/update-plugin-license 500 (Internal Server Error)
send @ jquery.js:10099
ajax @ jquery.js:9682
postActionRequest @ Craft.js:508
updateLicenseStatus @ PluginManager.js:344
o @ jquery.js:10771
setTimeout (async)
onKeyChange @ PluginManager.js:339
(anonymous) @ garnish.js:893
o @ jquery.js:10771
dispatch @ jquery.js:5429
v.handle @ jquery.js:5233
```

### Additional info

- Craft version: 3.5.5
- PHP version: 7.2.24
- Database driver & version: MySQL 5.7
- Plugins & versions: ...

**Comment by angrybrad** [comment]
Apologies for the delay on this, @bymayo.  If you're still able to reproduce, could you shoot an email over to support@craftmcs.com along with referencing this ticket along with your Craft ID account you were logged in with? We can dig in further from there.
