### ISSUE TITLE
3.5 Invalidate Data Caches errors because it's empty by default

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#6661]
### Description
Really minor thing I guess. When you go to the Caches section of 3.5, Template Caches is unchecked, but the button still works. If you click it, you get a server error:

`2020-08-18 03:20:01 [-][1][-][error][yii\web\HttpException:400] yii\web\BadRequestHttpException: Request missing required body param in /Users/dknight/Sites/boilerplate/vendor/craftcms/cms/src/web/Request.php:794`

![image](https://user-images.githubusercontent.com/1250017/90501736-73d48a00-e155-11ea-8a35-a7910287fa4b.png)

I'm guessing this is because that clear caches option needs to know _what_ to clear and it's blank.

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.6 is out now with that fix.
