### ISSUE TITLE
Composer Install issues

### ISSUE THREAD

**Issue by josefarrugia** [craftcms/cms#6663]
### Description

Is anyone having issues installing CraftCMS via Composer? It's taken 25 minutes and none of the packages have been installed. The process sort of hanged. I am running on a 2019 Mac Mini with 16GB RAM so I don't think it's a system requirement issue. 

I have downloaded the archive file [directly here](https://craftcms.com/latest-v3.zip).

### Steps to reproduce

1. `composer create-project craftcms/cms testproject`

**Comment by josefarrugia** [comment]
Looked like my antivirus was causing the extreme slowdown

**Comment by brandonkelly** [comment]
Glad you got to the bottom of it!
