### ISSUE TITLE
Template caches tables remain empty

### ISSUE THREAD

**Issue by elodiegrondin** [craftcms/cms#6664]
### Description

The 3 tables related to template caches (_craft_templatecaches, craft_templatecachequeries, craft_templatecacheelements_) remain empty while in the front-end toolbar, database requests seem to decrease as if the caches were working fine. So I'm guessing that caches is working but I can't control what is actually cached in the database.

Any idea where the issue is coming from ?

### general.php
`
'dev' => [
    'devMode' => false,
    'enableTemplateCaching' => true,
],
`

### Additional info

- Craft version: Craft CMS 3.5.5
- PHP version: 7.2.1
- Database driver & version: MySQL 5.6.38
- Plugins & versions:
1. CP Clear Cache	1.0.7
2. Embedded Assets	2.3.3
3. Imgix	2.0.5
4. Mandrill	1.3.1
5. Minify	1.2.10
6. Obfuscator	1.0.4
7. Redactor	2.7.1

**Comment by brandonkelly** [comment]
We rewrote how template caching works in Craft 3.5, and those tables are no longer used. We kept them around just in case any plugins were executing SQL queries against them, which would have started to cause SQL errors if we had removed them. We’ll remove them in Craft 4.
