### ISSUE TITLE
Changes to a Matrix field won't save

### ISSUE THREAD

**Issue by PaulCWoods** [craftcms/cms#6665]
### Description

Other field types in Settings saving works as normal. However, if I change something in a Matrix field and save it, the change isn't saved.

### Steps to reproduce

1. Go to a field of field type Matrix in the Fields list.
2. Make any change
3. Hit Save
4. Open the field again in edit mode. The change has reverted to what it was previously.

### Additional info

- Craft version: Craft Pro 3.5.5
- PHP version: 7.1.33
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Please send your Composer files and a database backup to support@craftcms.com and we can try to look into it from there.

**Comment by Djive** [comment]
@PaulCWoods If you use SPOON.. plugin >   that can be reason

**Comment by PaulCWoods** [comment]
@Djive I don't, but not ruling out the possibility it might be a plugin. @brandonkelly I've sent that on. Thank you for looking into this.

**Comment by PaulCWoods** [comment]
The issue appears to have been fixed in 3.5.7

**Comment by nicbou** [comment]
It is not closed. I experience the same issue with 3.5.7 and 3.5.9
