### ISSUE TITLE
Re-consider the UI for custom on/off states for lightswitches

### ISSUE THREAD

**Issue by MattWilcox** [craftcms/cms#6666]
### Description

This is visually ugly and confusing. It just doesn't work having two labels with an associated input in the middle.

Can I suggest that we keep the lightswitch to the left of the label, and we simply change the label text to match the currently selected value for the on/off state?

<img width="669" alt="Screen Shot 2020-08-18 at 15 57 51" src="https://user-images.githubusercontent.com/814039/90529801-05e78d00-e16c-11ea-8b48-919c303c2b3e.png">

**Comment by MattWilcox** [comment]
That said, suggested solution may _also_ be confusing. Hmmm.

**Comment by brandonkelly** [comment]
Ugly maybe – especially if placed beside another field as you’ve got it in the screenshot – but not sure I agree with it being confusing. Seems pretty straightforward to me. Only showing one label would lead to confusion though.

**Comment by MattWilcox** [comment]
Ugly a bad choice of word; "unexpected". Here, the position of the circle is supposed to indicate which label is active... but then we also have the green as a state indicator; which is confusing. What does that mean? This isn't an on:off switch.

I have never seen this style of UI component on a web form before - I also don't have a simple solution other than orientating the toggle vertically and having the on:off labels top and bottom, by the side of a vertical toggle - and ditching the green colour when these labels are used.

**Comment by brandonkelly** [comment]
I agree; my initial inclination was to only add the right-side label (see https://github.com/craftcms/cms/issues/3741#issuecomment-673169690). It’s been done before though (e.g. https://mdbootstrap.com/docs/jquery/forms/switch/).

**Comment by brandonkelly** [comment]
Just slightly restyled Lightswitch fields when they have ON/OFF labels. Looks less ugly now :)

<img width="184" alt="The “System Status” setting with “Offline” and “Offline” labels" src="https://user-images.githubusercontent.com/47792/91365918-1ffe1c80-e7b7-11ea-9a7d-09db45162110.png">

**Comment by MattWilcox** [comment]
Looks tidier, nice one thanks.

**Comment by brandonkelly** [comment]
Craft 3.5.8 is out now with that change.
