### ISSUE TITLE
Unescaped urls in image.getSrcset

### ISSUE THREAD

**Issue by app-solutions-pl** [craftcms/cms#6668]
### Description

I'm using config param filenameWordSeparator set to false. Basic idea is to keep spaces in assets library for nicer look. In this case images srcset doesn't work because of unescaped spaces in url. Chrome report it as:
"Failed parsing 'srcset' attribute value since it has an unknown descriptor." and "Dropped srcset candidate".
I've tried many ways to escape spaces but no luck so I report a bug.

### Steps to reproduce

1. Add 'filenameWordSeparator' => false to config general.php
2. Try to output any image using:
{{ tag('img', {
  src: image.url,
  srcset: image.getSrcset(['1.5x', '2x', '3x'])
}) }}

### Additional info

- Craft version: 3.5.5 (Solo)
- PHP version: 7.4.9
- OS version: WINNT 10.0
- Database driver & version: MySQL 5.5.5
- Image driver & version: Imagick 3.4.4 (ImageMagick 7.0.7-11)
- Plugins & versions: 
    - Admin Bar 3.1.8.1
    - Agent 1.1.8
    - Breadcrumb 1.1.0
    - Chunked File Uploads 1.0.2
    - Color Extractor 2.0.6
    - Cookie Consent Banner 1.2.6
    - Cookies 1.1.12
    - CraftNavigation 1.0.8
    - Craft reCAPTCHA 3 1.0.16
    - Craft Redactor Script Buttons 1.1.1
    - Customizable Radio Buttons Field 1.0.1
    - DB Dump 3.0.3
    - Do Not Track 1.0.0
    - Elements Panel 1.1.0
    - Embedded Assets 2.3.3
    - Express Forms 1.0.6
    - Feed Me 4.2.3
    - Freeform 3.7.4
    - Kint 1.0.0
    - Minify 1.2.10
    - Obfuscator 1.0.4
    - Pagination 1.0.2
    - Patrol 3.1.3
    - Phone Number 1.3.0
    - Picture 2.2.2
    - Queue Manager 1.2.0
    - Read-only Field 1.0.1
    - Reasons 2.2.1
    - Redactor 2.7.1
    - Redactor Anchors 1.1.0
    - Redactor Custom Styles 3.0.4
    - Redactor Font Awesome 2.1.1
    - Redactor Split 1.1.0
    - Redactor Tweaks 2.0.4
    - Route Map 1.1.6
    - Super Table 2.6.1
    - TinyMCE 2.0.0
    - Twig Perversion 2.1.0
    - Validateit 1.0.3
    - Video Embedder 1.1.4
    - Wheel Form 2.5.0

**Comment by app-solutions-pl** [comment]
Fixed by editing /vendor/craftcms/cms/src/elements/Asset.php method getSrcset:

$srcset[] = str_replace(' ', '%20', $this->getUrl($sizeTransform)) . ($size !== '1x' ? " {$value}{$unit}" : '');

**Comment by brandonkelly** [comment]
Thanks for reporting that. Just fixed for the next release.

**Comment by app-solutions-pl** [comment]
Thanks Brandon for lightspeed update!
I also believe same rule could be applied to getUrl. It will allow to create srcsets manually in twig templates by using getUrl(definedTransformName). When using defined transforms everything lands in same named folders like "_thumb320h", "_thumb640h", etc. Otherwise many auto generated subfolders are created during thumb generation.

Example (width: Auto):
{{ tag('img', {
	src: image.getUrl('thumb320h'),
	srcset: image.getUrl('thumb320h') ~ ', ' ~ image.getUrl('thumb640h') ~ ' 2x'
}) }}

**Comment by brandonkelly** [comment]
Yeah I’ve fixed it for all asset URLs, not just `getSrcset()`.

**Comment by brandonkelly** [comment]
Craft 3.5.6 is out now with that fix.
