### ISSUE TITLE
`./craft install` command should not ask for username if `useEmailAsUsername` is true

### ISSUE THREAD

**Issue by benface** [craftcms/cms#6669]
I noticed the `./craft install` command asks for both `Username` and `Email` to create an admin account, but technically if `useEmailAsUsername` is `true`, those should be set to the same, so it should only ask for `Email`.

**Comment by brandonkelly** [comment]
Good point. Just made that change for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.6 is out now with that change.
