### ISSUE TITLE
Use Button elements for accessibility purposes

### ISSUE THREAD

**Issue by JayBox325** [craftcms/cms#6670]
### Description
I use the tab key to navigate a lot when I'm populating forms and I found I couldn't navigate through the matrix block naming popup in this way because the buttons are not made with accessibile markup.

Rebuild these buttons with the <button> element instead so they are more accessible for people like myself that just prefer to navigate this way and for CraftCMS users that only navigate with the tab key or similar.

![image](https://user-images.githubusercontent.com/13233809/90544895-b7dc8480-e17f-11ea-8de4-66a54721a85d.png)

![image](https://user-images.githubusercontent.com/13233809/90544713-72b85280-e17f-11ea-9e66-4fec4144d964.png)

### Steps to reproduce

1. Create a matrix field
2. Add a block
3. Try to tab navigate through the popup

### Additional info

- Craft version: 3.5.5

**Comment by brandonkelly** [comment]
Done for the next 3.5 release 😅

**Comment by brandonkelly** [comment]
Craft 3.5.6 is out now with that change.

**Comment by JayBox325** [comment]
Hero, Brandon. Thanks, man!
