### ISSUE TITLE
GraphQL API doesn't return 'Access-Control-Allow-Origin: *' within the response of the main API call after the preflight one

### ISSUE THREAD

**Issue by sidm1983** [craftcms/cms#6674]
### Description

I have been playing around with Craft CMS in headless mode and trying to make a cross-origin request to the GraphQL API. I am using Nitro for local development and I am hitting a CORS issue.

I have seen the other issues here on GitHub that talk about issues with the CORS preflight (OPTIONS) call, but I think there is still an issue with a missing `Access-Control-Allow-Origin: *` header for the main API call after the preflight one. In my case, the preflight response definitely has this header and completes successfully with a `200 OK`, however, my browsers (tried Chrome, Edge and Firefox) then complain about a missing `Access-Control-Allow-Origin` header on the main POST request to the GraphQL API endpoint. I have definitely set up the GraphQL API on the Craft side correctly as I am able to query the public schema and fetch data from it using both GraphiQL and Postman.

Here is the error message I get in the browser:

`Access to fetch at 'http://portal-cms.test/api?token=nDlDngCTjWHHmiC8BvQ15ZjYqJwd0kHe' from origin 'http://localhost:5000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

I tried the suggestion in the error message to set the request's `mode` to `no-cors`, but that didn't work.

To test whether this was an issue with my front-end code or nginx, I changed the API URL string in my javascript fetch code to the public Star Wars API (https://swapi.dev/api/people/) and that worked without any other code changes on the front end. I inspected the requests sent to the Star Wars API and I could see that both the preflight as well as the main API call to the Star Wars API succeeded. Looking at the response headers for both calls, I noticed that both API calls return the `Access-Control-Allow-Origin` header.

Is it possible for me to configure nginx within nitro to return the `Access-Control-Allow-Origin: *` header for the main API call as well? Or is this something that needs to be fixed on the craft cms/nitro end?

Any ideas/help would be greatly appreciated 🙏 

Thank you!

### Additional info

- Craft version: 3.5.5
- PHP version: 7.4
- Database driver & version: pgsql 11

**Comment by brandonkelly** [comment]
`graphql/api` requests are in fact sending the `Access-Control-Allow-Origin` header for non-preflight requests; however they are only sending the `Access-Control-Allow-Headers` on preflight requests, which tells the browser which (other) headers it’s allowed to check. Just fixed that for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop",
  "...": "..."
}
```

Then run `composer update`.

**Comment by sidm1983** [comment]
@brandonkelly, thank you for the clarification. Unfortunately, that is not what I am seeing on my local Nitro dev environment running on Windows.

Here are my requests and responses for preflight and non-preflight calls.

**Preflight Request:**
```
OPTIONS /api?token=<some-token> HTTP/1.1
Host: portal-cms.test
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: */*
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type
Origin: http://localhost:5000
Sec-Fetch-Mode: cors
Referer: http://localhost:5000/article/my-first-article?x-craft-live-preview=<some-live-preview-token>&token=<some-token>
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,ja;q=0.8
```

**Preflight Response:**
```
HTTP/1.1 200 OK
Server: nginx/1.18.0 (Ubuntu)
Date: Fri, 21 Aug 2020 04:10:38 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Robots-Tag: none
X-Powered-By: Craft CMS
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization, Content-Type, X-Craft-Token
Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0
Content-Encoding: gzip
```
As you can see above, the preflight response on craft cms 3.5.5 does have the `Access-Control-Allow-Origin: *` header even without your fix.

**Main (non-preflight) Request:**
```
POST /api?token=<some-token> HTTP/1.1
Host: portal-cms.test
Connection: keep-alive
Content-Length: 184
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
Content-Type: application/json; charset=utf-8
Accept: */*
Origin: http://localhost:5000
Referer: http://localhost:5000/article/my-first-article?x-craft-live-preview=<some-live-preview-token>&token=<some-token>
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,ja;q=0.8
```

**Main (non-preflight) Response:**
```
HTTP/1.1 400 Bad Request
Server: nginx/1.18.0 (Ubuntu)
Date: Fri, 21 Aug 2020 04:10:39 GMT
Content-Type: application/json; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
```
And here you can see that I am not getting back any of the `Access-Control-Allow-*` headers in the response for the main (non-preflight) call. Not sure if that is because the main request in this case is not sending any `Access-Control-Allow-*` headers in the request or if there is some other reason, but I am definitely not seeing an `Access-Control-Allow-Origin` header for non-preflight requests.

The above output is from a React SPA running on Chrome (but Firefox & Edge Chromium have the same issue and are rejecting the API call due to a CORS issue).

Any thoughts/ideas on this? Will your fix address this issue I am seeing?

Thank you!

**Comment by brandonkelly** [comment]
No worries! Glad you got it working.
