### ISSUE TITLE
Preserve spaces in Asset volume subfolder names

### ISSUE THREAD

**Issue by NixonGit** [craftcms/cms#6675]
### Description

It would be nice if Craft preserved whitespace in subfolder names when displaying in the CMS. Looking at the `volumefolders` table Craft stores the name and path separately. I assume the name is only used for display purposes and path is the important part?

If that isn't the case could Craft do a text replace for the filenameWordSeparator when outputting in Twig?

**Comment by brandonkelly** [comment]
The path is made up of the parent folder path plus the name. Folders don’t have a “label” in addition to their folder name.
