### ISSUE TITLE
Unable to use select all checkbox on an admin table

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/cms#6678]
**Description**
The select all checkbox in the table header for customer addresses does not respond.

**To Reproduce**
How, and what happened?
1. From a Customer page or the Customer Info tab of a CP edit user page, scroll down to addresses.
2. Click the checkbox in the table header to select all.
3. Checkbox does not respond.

**Expected behavior**
Should select/deselect all customer addresses.

**Additional info**
- Craft version: Pro 3.5.5
- Commerce version: Pro 3.2.2.1
- PHP version: 7.4.5
- Database driver & version: MySQL 5.5.5

**Comment by nfourtythree** [comment]
Hi @jmauzyk 

This has been fixed and will be included in the next Craft release.

Thanks!

**Comment by brandonkelly** [comment]
Craft 3.5.6 is out now with that fix.
