### ISSUE TITLE
[FR] Change order of tabs when editing a User (move "Account" tab)

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#6680]
Simple enough request (I believe)... 🤞

When editing a User, can we change the order of the tabs? More specifically, **can we arrange them like so?**

```
|-----------|-----------------|---------|-------------|
| All of my | Own custom tabs | Account | Permissions |
```

I just want the **Account** tab to be moved over beside the **Permissions** tab. That's literally all I'm asking for.

It always drives my OCD crazy that my own tabs are nestled within two of Craft's tabs...

![user@2x](https://user-images.githubusercontent.com/5309692/90695699-c2eeed80-e22f-11ea-8e8b-368a99657c54.png)

Similarly, I always find it a little unnecessary to be viewing the "Account" details first. User login data doesn't change that frequently, and is often something that the users can change by themselves.

IMO, the "Account" information is actually the _least_ likely to change on a regular basis. Imagine the content editors who are responsible for managing user accounts... it's likely that they'll be managing their own custom fields far more frequently than any user login data (as it is in my case).

Let me know if that makes sense! 🙂

**Comment by lindseydiloreto** [comment]
Oh, I completely forgot to mention... I loooooove the fact that Users can now accept custom fields! ❤️

I know it's not a brand-new feature (Craft 3.0-ish?), but it was still a game-changer. I remember back in the day when Users couldn't even have fields beyond Account and Permissions. We had to do some ugly workaround back then to link Users to custom data. Just having custom fields at all has been a breath of fresh air.

**Comment by michaelrog** [comment]
fwiw - You can currently accomplish this using the `cp.users.edit` hook.

Craft generates its tabs from the `tabs` array, which is exposed from the Twig `$context`.

Maybe something like this...
```
function cpUsersEditHook(array &$context)
{

	$oldTabs = $context['tabs'];

	$context['tabs'] = [
		'Account' => $oldTabs[0],
		'Page' => $oldTabs[2],
		...
		'Permissions' => $oldTabs[1]
	];

}
```

Still, hijacking the Twig context like this is a bit hacky and maybe glitch-prone if you're not really careful.

It'd definitely be nifty if Craft's layout editor allowed re-ordering the default tabs alongside the custom ones...

**Comment by lindseydiloreto** [comment]
Good to know, thanks @michaelrog! I'll give that workaround a shot. 👍

I'm certainly not opposed to fully-rearrangable tabs, but at the very least, the Craft-managed tabs should be grouped together. Seems the problem is even more pronounced when a user is looking at _their own_ profile page, because that creates an additional "Preferences" tab...

![my-account@2x](https://user-images.githubusercontent.com/5309692/90804679-6ba05a00-e2cf-11ea-874f-f013eb6c7e9f.png)

**Comment by lindseydiloreto** [comment]
Here's my quick & dirty workaround, based on @michaelrog's recommendation...

```php
Craft::$app->view->hook('cp.users.edit', function(array &$context) {

    // Chop off the first item
    $tab = array_shift($context['tabs']);

    // Add it back at the end
    $context['tabs']['account'] = $tab;

});
```

**Disclaimer,** I did it the lazy way... instead of carefully moving "Account" to appear before "Permissions" (which would probably be the ideal way), I just chopped "Account" off the beginning and tagged it back onto the end of the array.

**Comment by lindseydiloreto** [comment]
Annoyingly, it still pre-selects the "Account" tab... what's the workaround for that?
