### ISSUE TITLE
Error when using list types in custom Graphql directive

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#6693]
### Description

I have registered a custom Graphql directive which takes an argument of type `[Int]`. When applying the directive in a query I’m getting the following error:

```
Undefined property: GraphQL\\Language\\AST\\ListValueNode::$value
```

### Additional info

- Craft version: 3.5.5
- PHP version: 7.3.7
- Database driver & version: PostgreSQL 11.6
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Craft 3.5.6 is out now with the fix for this. Thanks for the PR!
