### ISSUE TITLE
__blank__ cannot be blank.

### ISSUE THREAD

**Issue by lukasgeiter** [craftcms/cms#6699]
### Description

When making use of the new feature to hide the label of a required field, the validation error uses `__blank__` instead of the field label. I would expect the message to either use the field name or a generic message that's more user friendly. For example: `This field cannot be blank`

### Steps to reproduce

1. Create a custom plain text field
2. Add it in the field layout designer marking it as required and hiding the label
3. Attempt to save an entry without filling in the custom field
4. The validation error states `__blank__ cannot be blank.`

### Additional info

- Craft version: 3.5.5
- PHP version: 7.2.19
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
Craft 3.5.6 is out now with that fix.

**Comment by lukasgeiter** [comment]
Awesome! Thanks for fixing that so quickly.
