### ISSUE TITLE
Graphql Private Schemas not Working after Migrating from Fortrabbit to DigitalOcean

### ISSUE THREAD

**Issue by whoisjuan** [craftcms/cms#6700]
### Description

I recently migrated my website from Fortrabbit to DigitalOcean. Besides a couple of hiccups in the server configuration everything seems to work well, except Graphql.

For some reason the Private Schemas stopped working (at least in the expected way). I tried deleting everything (Schemas and Tokens) but that did nothing. 

What seems to be failing are the tokens. After re-creating them they don't register any contact and still list as never contacted, although I have attempted to use them several times.

When I do a request from insomnia with the token it only works if I have that query available in the public schema, so it seems that it's querying against the public schema once it can't reach the token-matched private schema (which I doubt it's an actual behavior, so it's indeed contacting). If I enable other sections in the public schema, then that same query with that same token returns a completely different result from another section that doesn't even match the fields that I'm querying.

Invalidating the graphql cache doesn't help. Seems like something in the database got broken but the gqltokens and gqlschemas tables look good to me including the foreign keys. Is there some other table I can inspect or flush that could fix it?

I'm completely lost on this one. Any hint or thoughts?

### Steps to reproduce

1. Try to do a simple read query for an enabled section against a private schema using the provided token.
2. Query fails.
3. Enable that same section in the public schema and query again.
4. Query works.
5. Enable other sections in the public schema and query again.
6. Query returns a completely unrelated result from another section.

### Additional info

- Craft version: 3.5.5
- PHP version: 7.4.9
- Database driver & version: MySQL 8.0.20
- Plugins & versions:  https://www.dropbox.com/s/hkg2i8323excfex/Screen%20Shot%202020-08-22%20at%2010.48.58%20PM.png?dl=0

**Comment by brandonkelly** [comment]
Craft will _only_ use the public schema if no token is supplied. So most likely the issue is that the token isn’t making it all the way to the web server. If you have a proxy server involved (e.g. CDN/load balancer), it may not be getting forwarded from there. Or it’s possible that some web server module / PHP extension is stripping it.

**Comment by whoisjuan** [comment]
@brandonkelly That's certainly possible since I'm running my server on RunCloud and it's possible that there's something stripping the authorization. I'm not entirely sure what would be the best way to test if that's the problem though. 

Is there some log where I can see how exactly is Craft receiving the payload? I'm sending requests to the API but the server access logs don't show those requests, but I'm definitely getting the responses.

**Comment by whoisjuan** [comment]
@brandonkelly Ok! Actually your comment was super helpful to find a solution. Seems that It happens sometimes in certain server configurations but can be solved by doing a small re-write in `.htaccess`:

```
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
```

For future readers, if this doesn't work, the StackOverflow question where I found the solution provides other potential solutions: https://stackoverflow.com/questions/26475885/authorization-header-missing-in-php-post-request

**Comment by brandonkelly** [comment]
Glad you got it sorted!
