### ISSUE TITLE
{% html at head %} tag not putting things in the <head></head>

### ISSUE THREAD

**Issue by marionnewlevant** [craftcms/cms#6702]
### Description
`{% html at head %} whatever {% endhtml %}` is supposed to put the whatever in the `<head>`. Instead, the whatever showed up at the beginning of the `<body>`

### Additional info

- Craft version: 3.5.5
- PHP version: 7.4.5
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
If you view the HTML source of the page (e.g. begin the URL with `view-source:` – **not** the same thing as viewing the DOM in the Elements tab), does it show up before `</head>`?

Browsers have a very limited list of tags that are allowed in the `<head>` section, and will automatically begin the `<body>` as soon as an unsupported tag is hit. (That’s why you never see new `<head>` HTML tags added to the spec and instead we just keep repurposing `<link>`, etc.)

**Comment by marionnewlevant** [comment]
Learn something everyday. What I had was
> {% html at head %}{{ g_global.textField }}{% endhtml %}

instead of
> {% html at head %}{{ g_global.textField|raw }}{% endhtml %}

So what I got in my head was
`&lt;link href=&quot;https://fonts.googleapis.com/css?family=Philosopher&quot; rel=&quot;stylesheet&quot;&gt;`
which the browser very reasonably did not think belonged in the head.

Thank you!!

**Comment by brandonkelly** [comment]
Sure thing! Glad you got it sorted.
