### ISSUE TITLE
Disable and / or delay auto-save for drafts

### ISSUE THREAD

**Issue by bliswebagency** [craftcms/cms#6704]
We have a client who has nearly a dozen editors working simultaneously on a very large website.

Their workflow requires they are predominantly editing content as a Draft.

Their primary Pages channel has a complex page builder which uses Matrix fields nested inside Super Tables.

This was all setup before auto-saving drafts were a thing. Now they are, the overheads of the save events are significant and it's proving to be a problem for some users with their browser tabs timing out.

If we could either delay how often a Draft auto-saves or completely disable it, it would really help us out.

**Comment by brandonkelly** [comment]
Just added a new `autosaveDrafts` config setting for the next release. Setting it to `false` will prevent autosave, except in Live Preview where autosaving is required. When autosaving is disabled, draft forms will have a “Save draft” button so authors still have a way of saving their changes, and they will also be able to continue using the <kbd>Command</kbd>/<kbd>Ctrl</kbd> + <kbd>S</kbd> keyboard shortcut to save their work.

**Comment by bliswebagency** [comment]
Thanks Brandon. Love your work.

**Comment by brandonkelly** [comment]
Craft 3.5.6 is out now with that new config setting.

**Comment by bliswebagency** [comment]
Thanks Brandon,

I've noticed that it still Auto-saves if I create a new matrix block even with auto-save disabled. Is it possible to stop it saving on that event too?

**Comment by brandonkelly** [comment]
Sorry about that. Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.8 is out now with that fix.
