### ISSUE TITLE
Set default sort order of categories to 'level' rather than 'dateCreated'

### ISSUE THREAD

**Issue by jkorff** [craftcms/cms#6705]
### Description

As per [the docs](https://craftcms.com/docs/3.x/categories.html#orderby) the default sort order of categories is 'dateCreated'.

This is very unintuitive. When I'm working in the CP I can clearly see a hierarchy that's informed by the **level**. While preparing templates I assumed this to be the case for looping over categories as well, until I found out otherwise.

While one would assume that generally any child category's creation date should be after that of its parent, I have an occasional entry where this seems not to be the case.

Changing the default prevents such cases and makes using the categories loop more intuitive.

**Comment by brandonkelly** [comment]
This is actually a documentation bug, which is now fixed.

- Categories: https://craftcms.com/docs/3.x/categories.html#orderby
- Entries: https://craftcms.com/docs/3.x/entries.html#orderby
