### ISSUE TITLE
yii\base\ErrorException: fseek(): stream does not support seeking

### ISSUE THREAD

**Issue by Saboteur777** [craftcms/cms#6706]
### Description

I don't know if this is a Craft or a volume driver implementation issue, so I open a ticket here, too. (original: https://github.com/vaersaagod/dospaces/issues/17)

Trying to download an asset through the Control Panel with the download button on Asset edit page, getting an internal server error with the following stack trace: 

```
2020-08-24 12:16:57 [-][1][sculjoq6uhh6cl0sdpk1bjhk55][error][yii\base\ErrorException:2] yii\base\ErrorException: fseek(): stream does not support seeking in /var/www/vendor/yiisoft/yii2/web/Response.php:586
Stack trace:
#0 /var/www/vendor/craftcms/cms/src/web/ErrorHandler.php(74): yii\base\ErrorHandler->handleError()
#1 [internal function]: craft\web\ErrorHandler->handleError()
#2 /var/www/vendor/yiisoft/yii2/web/Response.php(586): fseek()
#3 /var/www/vendor/craftcms/cms/src/controllers/AssetsController.php(1077): yii\web\Response->sendStreamAsFile()
#4 [internal function]: craft\controllers\AssetsController->actionDownloadAsset()
#5 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#6 /var/www/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#7 /var/www/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction()
#8 /var/www/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#9 /var/www/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction()
#10 /var/www/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction()
#11 /var/www/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest()
#12 /var/www/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#13 /var/www/web/index.php(21): yii\base\Application->run()
#14 {main}
```

### Steps to reproduce

1. Upload an asset to a volume set up with DO Spaces.
2. Try to download the asset by clicking on the Download button in the top right corner of the Asset edit page. 
3. Internal server error.

### Additional info

- Craft version: 3.4.30
- PHP version: 7.4.2
- Database driver & version: MySQL 5.5.5
- Plugins & versions: 
DigitalOcean Spaces Volume - 1.1.2

**Comment by andris-sevcenko** [comment]
This needs to be fixed in the DO Spaces plugin (cc @aelvan).

It's a rather simple fix with two distinct steps:

1) Bump the underlying Flysystem library's version to 1.0.28 (https://github.com/craftcms/aws-s3/commit/2cd433db7c2e4d2a19ffa66c40d78702808ee38b)
2) Slightly change the initialization of the adapter (https://github.com/craftcms/aws-s3/commit/1a49b314cfce7799261ef897edc32392760563c1)

**Comment by aelvan** [comment]
@andris-sevcenko Thanks for the pointers, fixed the issue.
