### ISSUE TITLE
Change capitalization field handle cause field to be removed from Project Config

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/cms#6708]
### Description
When renaming a fields capitalization, it removes it from the project config. Not sure if this ia matrix specific. If I edit the field again after this, field gets removed from my Craft setup.

### Steps to reproduce

https://share.getcloudapp.com/mXuyPAAP

### Additional info

macOS 10.15.6

- Craft version: 3.5.5
- PHP version: 7.2.33
- Database driver & version: MySQL 5.7

**Comment by brandonkelly** [comment]
Yikes, thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.6 is out now with that fix.
