### ISSUE TITLE
When field has been given a new label, it's not reflected in the table columns designer

### ISSUE THREAD

**Issue by johnwbaxter** [craftcms/cms#6709]
When an existing field has been given a new label in layout designer, it's then not reflected in the table columns designer.

### Steps to reproduce

1. Create field called 'foo'
2. Add foo to a section 'pages' and change label to 'bar'
3. Go to table columns designer for 'pages' section and see that table column is called 'foo' not 'bar'.

### Additional info

- Craft version: 3.5.4
- PHP version: 7.3
- Database driver & version: mysql 5.7
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
This is currently expected behavior. See #6683 for related feature request.
