### ISSUE TITLE
Suggestion dropdown doesn't close on blur

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#6710]
Suggestion dropdown (eg Templates, env vars) should close on blur, but it doesn't.

**Comment by brandonkelly** [comment]
(Waiting to heard back on https://github.com/darrenjennings/vue-autosuggest/issues/105#issuecomment-680145302 before I can implement a fix for this.)

**Comment by brandonkelly** [comment]
Craft 3.5.6 is out now with a fix for this.
