### ISSUE TITLE
LocalizeRelations tasks not triggered by project config

### ISSUE THREAD

**Issue by flynnt** [craftcms/cms#6711]
### Description
I am in the process of localizing some Assets fields, which involves updating those fields to "Manage relations on a per-site basis". Locally, when I save the field, it kicks off the `LocalizeRelations` task defined in `vendor/craftcms/cms/src/queue/jobs/LocalizeRelations.php`, and everything works great.

However, I am using project config, and while the boolean values for this setting do get exported to `project.yaml`, the `LocalizeRelations` tasks do not get added to the queue when the project config is synced on a target environment.

This then leads to issues on the environment to which the config changes were deployed. For example, if I update an image on one of the sites in the multisite environment, it removes the original images on all the other sites, which makes sense, since the `LocalizeRelations` tasks haven't been able to re-associate all the assets.

### Prereqs
There are a lot of prerequisites to test this:
- Project config needs to be enabled
- You need a multisite environment
- You need a target environment that you can push config changes to via `project.yaml`
- That target environment should already have an instance of the Assets field you're changing, and it should have data in it (that is, it should have an image or other asset saved to it)

### Steps to Reproduce
1. Update an existing Assets field to "Manage relations on a per-site basis"
2. Note that the change is exported to the config file
3. Sync this change to another environment that has the same field
4. Go to the above environment and update the value for the field on one site
5. Note that the original value gets wiped out for all the other sites

### Additional info
- Craft version: 3.4.30
- PHP version: 7.2.30
- Database driver & version: mysql 5.7.29
- Plugins & versions: Amazon S3 1.2.8, Asset Rev 6.0.2, Async Queue 2.1.1, Blitz 3.6.5, Environment Label 3.2.0, Field Manager 2.1.6, Image Optimize 1.6.14, LinkIt 1.1.11, Minify 1.2.10, Redactor 2.6.1, Redactor Custom Styles 3.0.3, Retour 3.1.39, SEOMatic 3.3.8, Super Table 2.5.2, Typogrify 1.1.18.

**Comment by brandonkelly** [comment]
Craft 3.5.6 is out now with a fix for this. Thanks for reporting!
