### ISSUE TITLE
3.5.5 (i.e. latest) ZIP Archive File Missing Directories

### ISSUE THREAD

**Issue by ademers** [craftcms/cms#6712]
### Description

The zip archive (https://craftcms.com/latest-v3.zip) linked to in docs at  https://craftcms.com/docs/3.x/installation.html#step-1-download-craft contains only a `vendor` directory. 

Also, the tar.gz archive (https://download.craftcdn.com/craft/3.5/Craft-3.5.5.tar.gz) generates a 404 for me at time of writing.

### Steps to reproduce

1. Visit https://craftcms.com/docs/3.x/installation.html#step-1-download-craft.
2. Click zip link to download.
3. Extract zip and see only a `vendor` directory.
4. Click tar.gz link to download.
5. See 404 error.

### Additional info

I'm able to download 3.5.4 zip via http://download.craftcms.com/craft/3.5/Craft-3.5.4.zip and see all the directories after extraction.

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Should be fixed now. Thanks for reporting!
