### ISSUE TITLE
Empty table column handle cause GraphQL schema problems

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/cms#6714]
### Description

I have found at least 2 scenarios where you would either get back a broken GraphQL schema or no schema at all (PHP exception)

### Steps to reproduce

1. When creating a field table without providing a table column handle, the GraphQL file would break:
```graphql
type tourIncluded_TableRow {
  col1: String
  : String
}
```

2. When providing a column handle that starts with a number, I'm unable to generate the schema at all:
```
Exception 'craft\errors\GqlException' with message 'Failed to validate the GQL Schema - tourIncluded_TableRow.123 field config must be an array, but got: String'

in /vendor/craftcms/cms/src/services/Gql.php:387
```

### Additional info

- Craft version: 3.5.5
- PHP version: PHP 7.2.33
- Database driver & version: MySQL 5.7

**Comment by andris-sevcenko** [comment]
We'll discuss this internally, but, at least for now, I'm leaning towards that both no handle and a handle that starts with a number should not be allowed as column handles and that this should have been caught by the Table field validation process.

**Comment by Wiejeben** [comment]
A column without a handle can still be accessed via `colX` (col1, col2, etc.) so making it optional isn't making accessing the column impossible.

However starting with a number should be made illegal, just like field handles, section handles, etc.

**Comment by andris-sevcenko** [comment]
Ah, that's a good point.

**Comment by andris-sevcenko** [comment]
Should be all fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 3.5.7 is out now with the fix.
