### ISSUE TITLE
FR: Set anyStatus by default in auto-generated titles from related entries

### ISSUE THREAD

**Issue by joshua-martin** [craftcms/cms#6715]
### Description

When auto-generating titles from related entry fields, the default is set to only pull `live` entries.

![Screenshot_2020-08-25_at_11 52 39](https://user-images.githubusercontent.com/1694957/91167457-e7354900-e6cb-11ea-9e4e-0f4c08c3e2bc.png)
![unknown](https://user-images.githubusercontent.com/1694957/91167459-e8ff0c80-e6cb-11ea-99fe-7bfa96448eca.png)

You have to use `anyStatus` to ensure that you pull the title of the related entry regardless of status. This might potentially be problematic if the entries ever get re-saved in the future and entries that were previously live are now expired (or have been updated and are now pending), as the title will become empty.

Can auto-generated titles be set to `anyStatus` by default without it needing to be explicitly specified?

**Comment by brandonkelly** [comment]
Sorry, this isn’t possible. That‘s just a Twig template (with an optional single-curly-brace syntax), which gets populated with variables based on all the custom field values, but the custom field has no way of knowing how the value is going to be used.

By the way, that template is going to give you a deprecation error. You should do this instead:

```twig
{showRelatedEvent.one().title} - {postDate|date('d M Y')}
```

**Comment by joshua-martin** [comment]
np, thanks Brandon. Yeah I have that now I was just trying different ways because I forgot to add `anyStatus`.

J
