### ISSUE TITLE
Cannot give users permission to access the GraphQL area of the CP

### ISSUE THREAD

**Issue by OwenMelbz** [craftcms/cms#6717]
### Description

Currently only "Full Admins" have access to this, which is a little tricky when you only want to give users GraphQL access.

e.g. When working with a team who will be creating an integration between their system and Craft - having access to the GraphiQL area is great, but to do this you need to give them full admin access.

Ideally just like the other permissions for utilities etc - You should be able to let them access it based off a permission.

Thanks

**Comment by andris-sevcenko** [comment]
As a workaround, there are standalone IDEs that can be used. Here are two I have have used:

- [GraphQL Playground](https://www.electronjs.org/apps/graphql-playground)
- [Insomnia](https://www.electronjs.org/apps/graphql-playground)

**Comment by OwenMelbz** [comment]
GraphQL Playground doesn't seem to play nicely with it, might be a super table conflict as it crashes when trying to use it due to:


```
input carousel_carousel-0_SuperTableBlockInput {
       |                        ^
  2374 |   image: [Int]
  2375 |   videoUrl: String

Uncaught SyntaxError: Syntax Error: Unexpected Int "-0" (2373:24)

```

Insomnia I tried and was OK... but the experience is pretty rubbish compared to the built in one where you can just click tick boxes to add it to the query and stuff like that.

**Comment by andris-sevcenko** [comment]
Gotcha. As it stands right now, it's a bit of a can of worms. GraphiQL currently has access to all schemas, so, in terms of content, it's pretty much like admin access.

To avoid that, we'd have to introduce permissions for each schema, too. And that feels like a sorry excuse for what we're planning down the road (which is layering user permissions on top of GraphQL tokens), so this is bound to be a low priority thing until 4.0, probably.

If you're willing to give PRing this a shot, I'd be happy to provide some goalposts for that, though!
