### ISSUE TITLE
Unable to delete Entry Type

### ISSUE THREAD

**Issue by johndwells** [craftcms/cms#6719]
### Description

After upgrading to 3.5.6, I've deleted an Entry Type. It was removed from the Project Config folder, yet it remains in the DB. I've tried re-applying project config, but the row in the DB table remains.

### Additional info

- Craft version: 3.5.6
- PHP version: 7.4.5
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

**Comment by johndwells** [comment]
FWIW I was able to overcome it by rebuilding the project config, and then going back into the CP and deleting the entry type.

**Comment by johndwells** [comment]
Hmm. Well that worked locally, but in production when the project config is _only_ applied, the entry type is still never deleted.

**Comment by brandonkelly** [comment]
Sounds like maybe the entry type wasn’t in the loaded project config to begin with, somehow. Just tested locally and entry type deletion is working as expected on my end.

On production, backup the database and and then try running `php project-config/apply --force` (or click the “Reapply everything” button in the Project Config utility).

**Comment by johndwells** [comment]
Re-applying isn't working.  Production still shows the deleted Entry Type...

When I look at my commit where 3.5.6 was installed (upgraded from 3.4.30), I can see that the YAML file pertaining to the entry type is created on the filesystem. Then it's the very next commit where the entry type is deleted.

I've tried re-doing everything: Pulled DB down from production, re-built project yaml, which re-created the entry type YAML file, as expected. Now when I locally try to delete the entry type, there is no change to the filesystem, and when I refresh the CP, the entry type comes back.

For kicks I renamed the handle to all lowercase (it was camelCase before), and that did for some reason manage to take hold in production.

I have no idea if that means anything... It's possible this was all just a fluke and there isn't an underlying bug.

But - I've just downloaded the production DB and had a look at the `entrytypes` table, and the deleted entry type is still there. So is an entry type from a section I had since deleted after the upgrade to 3.5.6. That since deleted section is in fact still in the `sections` table as well...

Is that expected?

**Comment by andris-sevcenko** [comment]
> But - I've just downloaded the production DB and had a look at the entrytypes table, and the deleted entry type is still there. So is an entry type from a section I had since deleted after the upgrade to 3.5.6. That since deleted section is in fact still in the sections table as well...

@johndwells is the `dateDeleted` column set to `null` for those rows?

**Comment by johndwells** [comment]
@andris-sevcenko Ah no, they have been set. So is this a GC thing?

**Comment by andris-sevcenko** [comment]
It's a soft-delete thing, yeah. GC will eventually get rid of those.

**Comment by johndwells** [comment]
OK. I am now suspecting this might be a deployment issue...

**Comment by andris-sevcenko** [comment]
![gif](https://user-images.githubusercontent.com/1891118/91298694-1ff72000-e7a9-11ea-9d79-82baab341b0b.gif)

**Comment by brandonkelly** [comment]
Are you saying that the row has a `dateDeleted` value, but the entry type is still showing up in the control panel / front end? Or were you only looking at the database?

**Comment by johndwells** [comment]
Eh. Yes but, in the end it may have just been a deployment issue. Sorry gang for the false alarm and wasted time.
