### ISSUE TITLE
Changing section type does not update 'Site settings' fields

### ISSUE THREAD

**Issue by jordanjmann1** [craftcms/cms#6721]
### Description
I am creating a new section through the dashboard and when I go to change the section type to single the site settings fields below do not change from the fields for a channel. This also happens when I change it to structure.

### Steps to reproduce
1. Create a new section
2. Change section type to Single or Structure
3. Site Settings does not update

### Additional info
- Craft version: 3.5.6
- PHP version: 7.4.9
- Database driver & version: MySQL 10.3.23
- Plugins & versions: Imager 2.4.0, SEO 3.6.6, Stamp 2.1.0, Super Table 2.6.2

**Comment by Wiejeben** [comment]
+1

The interface doesn't update on the create or edit section page

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just released Craft 3.5.7 with a fix.
