### ISSUE TITLE
Better indication of mandatory field status in field editor

### ISSUE THREAD

**Issue by simonleadbetter** [craftcms/cms#6725]
When working with the new field editor, it isn’t clear what fields have been assigned the required field status as the asterisks appears at the end of the field label:

<img width="286" alt="Screenshot 2020-08-26 at 08 36 47" src="https://user-images.githubusercontent.com/1379783/91319741-a1a07b00-e7b4-11ea-8ef3-bd9a9a9b6264.png">

In the example above, the second field SEO meta description is in fact assigned as required, however, there is no way of knowing this. Perhaps by simply placing the asterisks in the top-left corner (or something similar) is all that is needed to improve the UI:

![repositioned](https://user-images.githubusercontent.com/1379783/91320366-55096f80-e7b5-11ea-8e98-0b739225aade.png)

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Managed to fix this without changing the position of the asterisks. Also added the asterisk to the field handle in the event that the label is hidden.

![Two required field selectors within a field layout designer](https://user-images.githubusercontent.com/47792/91348845-401ee300-e799-11ea-8ddb-b082faff4e20.png)

**Comment by brandonkelly** [comment]
Craft 3.5.8 is out now with that change.
