### ISSUE TITLE
Unwanted behavior of CSS viewport units in Live Preview

### ISSUE THREAD

**Issue by theyve** [craftcms/cms#6726]
### Description
If I'm using CSS viewport units in my templates, the Live Preview gets pretty much unusable. 
Since the viewport height is equal to the height of the `.lp-preview`-iframe, viewport height units (`vh`) are rendered larger as the page gets longer.

The height of the Live Preview iframe should always stay the height of the actual viewport, to prevent this.

### Steps to reproduce

1. Use CSS viewport height unit in a template. e.g. `<div style="background:red;height:50vh"></div>`
2. Add content to the template so the page gets longer than the viewport height.
3. Open the live preview on an entry that uses this template
4. See that the viewport units are larger than expected.

### Additional info

- Craft version: 3.5.0
- PHP version: 7.4.8
- Database driver & version: MySQL 5.7.26

**Comment by theyve** [comment]
ah just found this: #6388 

Sorry!

**Comment by brandonkelly** [comment]
In Craft 3.5.5 we reverted the behavior to be more like Craft 3.4 by default, and added a new config setting if you have a reason to use iFrame Resizer (see #6645).
