### ISSUE TITLE
Special characters in User Group name not displayed correctly on User Permissions tab

### ISSUE THREAD

**Issue by j-greig** [craftcms/cms#6727]
### Description
Special characters in user group names are not being displayed correctly on the User Permissions tab (see ampersand in screenshot - only noticed because our client's name includes one!)

To the best of my knowledge this was not an issue prior to Craft 3.5.

### Steps to reproduce

1. Create a user group containing an ampersand
2. Edit a user's permissions

### Additional info

- Craft version: 3.5.7

![image](https://user-images.githubusercontent.com/616194/91327903-13c98d80-e7be-11ea-9f62-393d6ac24a73.png)

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.8 is out now with that fix.
