### ISSUE TITLE
Quick Post widget fields disabled

### ISSUE THREAD

**Issue by Jan10** [craftcms/cms#6738]
### Description
If I want to add a Quick Post widget to the dashboard, all fields checkboxes are disabled.

![image](https://user-images.githubusercontent.com/192557/91456109-2d80d880-e883-11ea-94f5-7460f093e3b5.png)

### Steps to reproduce

1. Add a Quick Post widget to the dashboard

### Additional info

- Craft version: 3.5.7 Trail
- PHP version: 7.3.20

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.8 is out now with that fix.

**Comment by Jan10** [comment]
Thanks @brandonkelly!
