### ISSUE TITLE
Live preview token forces template actionRender

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/cms#6740]
### Description
I'm working on a headless website and I'm working on getting the live preview to work. With GraphQL it was very easy so that works fine. However when I'm trying to call a custom action I always end up getting a 404 page.

Works
`/actions/module/entry-type`

Does not work
`/actions/module/entry-type?x-craft-live-preview=I9zvESq3Ot&token=Icg0w_51Z0xrm9wnnvRffvxL0yWIOM7R`

I need the token because inside the action I'm querying entries. Adding `X-Craft-Token` to the header gives the same result.

Even if I register the route it still wants to render a template when a token is provided.
```php
Event::on(
    UrlManager::class,
    UrlManager::EVENT_REGISTER_SITE_URL_RULES,
    function (RegisterUrlRulesEvent $event) {
        $event->rules['GET /entry-type'] = 'module/entry-type';
    }
);
```

The `NotFoundHttpException` is thrown by the `TemplatesController` even tho it executes my action without the `token` query param.

### Steps to reproduce

1. Open a custom route that works without token
2. Add `?token=...` to your URL and you should get a 404 (by `TemplatesController` if `headless` is set to `false`)

### Additional info

- Craft version: 3.5.7
- PHP version: 7.2.33
- Database driver & version: MySQL 5.7
- Plugins & versions: -

### Note

If this is the desired behaviour than I'm looking for a way to apply a live preview (or draft) token to an element query manually.

**Comment by brandonkelly** [comment]
This is a known limitation of Craft/Live Preview routing – each request is limited to one explicitly-defined controller action, and if the `token` param is set, that will override the action that is explicitly requested by the URI.

The way to get around it is to define a custom [URL rule](https://craftcms.com/docs/3.x/routing.html#advanced-routing-with-url-rules) in `config/routes.php` that points to your module’s action, **and point the request URI to that**. You’ve done the first half of that, but are you actually setting your request URI to `/entry-type`?

**Comment by Wiejeben** [comment]
Oeps... Yeah so after I registered the shorter URL via `RegisterUrlRulesEvent` I just manually added the token to the URL instead of testing it via live preview. Bit of an overzicht by me. I'm happy to report that my issue is fixed now!

Feel free to close this issue. Thanks again!

**Comment by brandonkelly** [comment]
Awesome, glad that worked!
