### ISSUE TITLE
Can't upload files anymore

### ISSUE THREAD

**Issue by Jones-S** [craftcms/cms#6741]
### Description
I just updated to craft v3.5.7 and since them I can't click the `Upload` button anymore within the files tab.
I see the colored strandball on mac for a short period and then nothing happens. The console does not show any errors.
Before I was on v3.5.2 and I know it worked, because I have images in the library.

### Steps to reproduce

1. Probably upgrade to v3.5.7

### Additional info

- Craft version: v3.5.2
- PHP version: 7.2
- Database driver & version: mysql
- Plugins & versions:
```
        "craftcms/element-api": "2.6.0",
        "craftcms/feed-me": "4.2.2",
        "craftcms/redactor": "2.6.0.1",
        "doublesecretagency/craft-cpcss": "2.2.1",
        "guzzlehttp/guzzle": "~6.0",
        "j7mbo/twitter-api-php": "1.0.6",
        "mmikkel/cp-field-inspect": "1.1.2",
        "nystudio107/craft-seomatic": "^3.2.43",
        "putyourlightson/craft-cp-style-guide": "1.0.2",
        "sebastianlenz/linkfield": "2.0.x-dev",
        "spicyweb/craft-neo": "^2.6.1",
        "verbb/field-manager": "2.1.1",
        "vlucas/phpdotenv": "^2.4.0"
```

**Comment by angrybrad** [comment]
Uploading working for me on 3.5.7. Likely an environmental issue on your setup and will follow-up in your existing ticket you have in support with us.
