### ISSUE TITLE
[GraphQL] No difference between number field value 0 and an empty field

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/cms#6743]
### Description

When retrieving an empty number field from GraphQL it is being provided as `null`, this is exactly as I expected. However if I store the field with a value of `0`, GraphQL still responds with `null`.

### Steps to reproduce

1. Save an entry with an empty number field, GraphQL output will be `null` (correct)
2. Save an entry with a number field with value of `0`, GraphQL output will be `null`

### Additional info

- Craft version: 3.5.7
- PHP version: PHP 7.2.33
- Database driver & version: MySQL 5.7
- Plugins & versions: -

**Comment by andris-sevcenko** [comment]
This has been fixed for the next Craft 3.5 release.

**Comment by brandonkelly** [comment]
Craft 3.5.9 is out now with this fix.
