### ISSUE TITLE
File Cache: keyPrefix prevents nested directories

### ISSUE THREAD

**Issue by ostark** [craftcms/cms#6746]
### Description

Before Craft 3.5.2 the cached files where nested in a subdirectory starting with the first two characters of the file name.
Example

```
cache/aa/
    aa34rfwefsdfsdf.bin
    aadsfddffsffsfssf.bin
cache/xz/
    xz43534534535.bin
    xzxzrrrrrrrrrrr5.bin
```

I think the idea behind this is to limit the number of files per directory.

With the introduction of the `keyPrefix`, which uses the `app.id`, which defaults to CraftCMS or uses the `APP_ID` env var, all cache files live in the `Cr` directory. 
Example:

```
cache/Cr/
    CraftCMSaa34rfwefsdfsdf.bin
    CraftCMSaadsfddffsffsfssf.bin
    CraftCMSxz43534534535.bin
    CraftCMSxzrrrrrrrrrrr5.bin
```
       
---

### Additional info

- Craft version: 3.5.2
- PHP version: 7.4

### Questions:

- Is this behavior intended?
- Am I missing something?

**Comment by brandonkelly** [comment]
That was not intended. Just fixed for the next release, and have also reported a Yii bug about it: yiisoft/yii2#18263

**Comment by brandonkelly** [comment]
Craft 3.5.8 is out now with that fix.
