### ISSUE TITLE
Matrix field creation - "Max blocks" input label is incorrect, says "Matrix Block"

### ISSUE THREAD

**Issue by andrewhawkes** [craftcms/cms#6751]
### Description

Pretty self-explanatory; but the input label says "Matrix Block" and I think it should say "Max Blocks".

Minor but thought it's worth noting! 

<img width="534" alt="Annotation 2020-08-29 161116" src="https://user-images.githubusercontent.com/4975742/91639978-6b603700-ea12-11ea-9e9f-af6076e7fd6d.png">

### Steps to reproduce

1. Create new matrix field
2. See incorrect label

### Additional info

- Craft version: 3.5.5

**Comment by brandonkelly** [comment]
Thanks for reporting that! The source string was in fact “Max blocks”, so this was caused by a bad translation.
