### ISSUE TITLE
user photo volume is deleted, 'upload a photo' is still available

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#6752]
**Description**
even though user photo volume is deleted, photoVolumeUid remains in project config file 
so user still see 'upload a photo' button in user profile page.

**Steps to reproduce**
1. create a volume
2. select that volume as user picture volume
3. delete that volume
4. 'upload a photo' button is still there

**Additional info**
- Craft version: 3.5.7

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.8 is out now with that fix.
