### ISSUE TITLE
"Replace" existing file option has stopped working

### ISSUE THREAD

**Issue by bliswebagency** [craftcms/cms#6753]
### Description
A client has reported that when they go to replace an existing file in assets, Craft no longer prompts them to ask if they want to "replace" the file or create a new version.

Instead, it automatically creates a new version.

### Steps to reproduce

1. Upload a file to assets
2. Upload the same file again... and watch what happens

### Additional info

- Craft version: 3.5.7
- PHP version: 7.0
- Database driver & version: MariaDB 10.0.38
- Plugins & versions: (numerous but nothing that I'd expect would affect this)

**Comment by andris-sevcenko** [comment]
There was a Javascript bug that caused the prompt for replacing the file to be displayed incorrectly and not really functioning.

The behavior that you observed is the correct one - on encountering a conflicting filename on upload, Craft pro-actively renames the new upload. This means that if you choose "replace", Craft doesn't have to re-upload the file to the server. Likewise, if you choose "keep both", Craft does not have to do anything at all.

This has been fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.8 is out now with that fix.
