### ISSUE TITLE
Craft CMS doesn't recognice Craft CMS

### ISSUE THREAD

**Issue by kaspar-allenbach** [craftcms/cms#6755]
### Description

I want to apply YAML changes in the Projectconfiguration Tool in the CP.

When I hit Apply changes I get the error: 

> The following plugins are listed in your project config YAML files, but appear to be missing or installed at the wrong version: Craft CMS

### Steps to reproduce

1. Update a craft page from 3.2.9 to 3.5.7
2. Go to the Projectconfig page on the cp.
3. Click Rebuild
3. Try to apply the data.

### Additional info

- Craft version: 3.5.7
- PHP version: 7.4

[composer.zip](https://github.com/craftcms/cms/files/5149974/composer.zip)
[project.zip](https://github.com/craftcms/cms/files/5149975/project.zip)

**Comment by szczups** [comment]
I do have the same exact issue, also for the `3.5.7` version.

**Comment by szczups** [comment]
Hey @kaspar-allenbach so I managed to track down the issue. More info is displayed in the terminal if you use `craft` cli. 

Bottom line: issue is with schema version of craft cms being used on the config yaml file `config/project/project.yaml` what worked for me was a set of following commands: 

`/craft migrate/up --type=app ` - this should fix the problem with incorrect schema version with the next command
`./craft project-config/rebuild`
`./craft project-config/apply `

Of course all the commands should be fun from project root, where `craft` is located. Hope this helps. CLI is pretty verbose, so you should get more info. schemaVersion is not equal to Craft CMS version. You can check schema version in https://github.com/craftcms/cms/blob/develop/src/config/app.php#L7

Cheers

**Comment by brandonkelly** [comment]
Sorry for the confusion; the message should not be labeling Craft CMS as a “plugin”. As of the next release, it will say:

> Your project config YAML files are expecting different versions to be installed for the following: [List of names]

or, if any plugins aren’t Composer-installed yet:

> Your project config YAML files are expecting the following plugins to be installed: [List of names]

The advice the message was giving was correct though – if you run `composer install` the message should go away.

**Comment by brandonkelly** [comment]
Craft 3.5.8 is out now with that change.
