### ISSUE TITLE
When removing subsites and resaving entries it errors out on "unknown site id"

### ISSUE THREAD

**Issue by michtio** [craftcms/cms#6756]
### Description

When you remove a few subsites, Craft wants to resave all the entries. Entries are set on a per site base. The subsite has been removed and the queue showed error, when running `./craft resave/entries --site="*"` errors show up.

<img width="731" alt="Screenshot_2020-08-31_at_13 04 59" src="https://user-images.githubusercontent.com/5818021/91723754-8ced2a00-eb9c-11ea-9ea6-b3ca707465c8.png">

The id's shown on the screenshot are the ID's of the sites being removed.

### Steps to reproduce

1. Have a site with multiple subsites
2. Remove one or more of said subsites
3. See the `resaving entries` error out

### Additional info

- Craft version: 3.4.29.1
- PHP version: 7.4

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.8 is out now with that fix.

**Comment by michtio** [comment]
That was quick @brandonkelly ! Thanks for that :)
