### ISSUE TITLE
Import / Export

### ISSUE THREAD

**Issue by nexflo** [craftcms/cms#6757]
I think it crazy, that there is no default/native import/exporter inside of Craft.

When i setup a new "clean" craft incl. a project yaml i do get all the structure, but to actually import and export the CMS content data - > i "only" have a complete DB dump, or go manual with FEEDMEE or so.

**Comment by nexflo** [comment]
Answering mysql....

Well actually....there is the new export button since 3.4
https://craftcms.com/docs/3.x/extend/element-exporter-types.html

**Comment by brandonkelly** [comment]
This is already requested by #994.

**Comment by nexflo** [comment]
And again....its my own ticket. ;)

**Comment by brandonkelly** [comment]
Ha! :)
