### ISSUE TITLE
Bug when using {% js %} tag pair in 3.5.7

### ISSUE THREAD

**Issue by fantasticmachine** [craftcms/cms#6762]
This has just popped up and I can only assume it's appeared during an update to 3.5.7

Some previously working Javascript that was included on a template using a `{% js %}` tag pair stopped working. 
It looks like the tag was being parsed incorrectly with the  enclosed javascript being used as a script src rather than as executable javascript.

Some experimentation showed that the problem stemmed from the need for a blank line before the javascript. Although it doesn't appear to effect some JS so perhaps it's because I'm declaring a variable?

### Steps to reproduce

Create a template and include the following (with some element on the template with a class of `.js-destination-select`)

```
{% js %}
	var destinationSelect = document.querySelector('.js-destination-select')

{% endjs %}
```

Examine the rendered source. The generated script tag has a src attribute containing the js.

Then add a blank line before the var declaration. The script tag is then rendered correctly.

However, replacing the var declaration with a simple `alert('test')` seems to work fine.

- Craft version: 3.5.7

**Comment by mightyfineyall** [comment]
Having the same issue, as I use gulp-file-inline to inline my production JS. It's rendering it all as a src="" attribute instead of proper JS.

**Comment by brandonkelly** [comment]
Thanks for reporting that. Craft 3.5.8 is out now with a fix.
