### ISSUE TITLE
Craft update method replaces private plugins with plugins from the plugin store

### ISSUE THREAD

**Issue by goraxan** [craftcms/cms#6765]
### Description

If by any chance you are using a plugin with the same handle as another plugin published in the plugin store, running `./craft update` (or updating via the CP) replaces that plugin with the one in the plugin store, with the only information of a version change (which is not useful in case the same version exists in both plugins, for example).

I think this behaviour is very dangerous and can lead to errors hard to detect. Is there any reason why the plugin vendor is not being check apart from the plugin name? That'd solve many problems.

**Comment by brandonkelly** [comment]
This is expected; see https://github.com/craftcms/cms/issues/3054#issuecomment-402006340 for an explanation.

**Comment by ileider** [comment]
Maybe the documentation should recommend private plugins or forks are prefixed. And/Or issue a warning when running craft update and the composer package is being changed. I understand the issue can't be fixed but warning the developer would be helpful.

**Comment by brandonkelly** [comment]
The docs recommend using a module for private things, as the only real benefit to using a plugin is the distribution via the Plugin Store.
