### ISSUE TITLE
File upload fails when the upload file name is too long

### ISSUE THREAD

**Issue by francoislevesque** [craftcms/cms#6766]
### Description

File upload fails when the uploaded file name is too long.

### Steps to reproduce

1. Upload a file in the craft panel with a very long name (ex: eyJidWNrZXQiOiJ3aXRpZnktdGVzdC1idWNrZXQiLCJrZXkiOiJiYWNrZ3JvdW5kSW1hZ2UvMjM5YzRkNWQtOWNlNy00MjMyLWE1NDYtNjk1NDcyNWE5MDE5L3NhcmEtZGFyY2FqLVl6YW1OQl9UNFdRLXVuc3BsYXNoLmpwZyIsImVkaXRzIjp7ImpwZWciOnsicXVhbGl0eSI6MTAwLCJwcm9ncmVzc2l2ZSI6dHJ1ZSw5f4eb1858ecde9.60264448.jpeg)
2. The upload will fail

### Additional info

- Craft version: 3.5.6
- PHP version: 7.3
- Database driver & version: mysql 8.0.20
- Plugins & versions: -

**Comment by brandonkelly** [comment]
Just resolved this for the next release. Going forward asset filenames will be automatically shortened to <= 255 characters.

**Comment by brandonkelly** [comment]
Craft 3.5.9 is out now with this fix.
