### ISSUE TITLE
twig search() on entry query doesnt return nested fields anymore since craft3.5

### ISSUE THREAD

**Issue by RainerZarth** [craftcms/cms#6771]
### Description
When searching through entries with twig query

```twig
{% set searchQuery = craft.app.request.getParam('q') %}
{% set result = craft.entries().section("sectionhandle").search(searchQuery).orderBy("score").all() %}
```

the result is no longer finding content of fields when nested in a Supertable. Normal matrix works fine.
this worked before at Craft version 3.4.25 and Supertable 2.5.1 (old version with postgres db)
with the new versions of craft and supertable it finds nothing, sadly.
i already tried to rebuild search index with `php craft resave/entries --update-search-index` didnt help

### Steps to reproduce

1. Put a supertable field inside a Matrix block
2. put a matrix field inside the supertable
3. put a texteditor (redactor) inside the nested matrix
4. create entry with that matrix and add richt text into the editor field
5. create search field like the documentation (https://craftcms.com/docs/3.x/dev/examples/search-form.html)
6. search a word in content, result will be null

### Additional info

- Plugin version: supertable 2.6.2, redactor 2.7.3
- Craft version: 3.5.7
- Multi-site: No
- Database: MySQL 5.7

**Comment by brandonkelly** [comment]
As of Craft 3.5, fields’ “Use this field’s values as search keywords?” settings are disabled by default (see #6390). Check to make sure that setting has been enabled for fields you wish to index – both for the Super Table and Matrix fields as well as their sub-fields. Then try running `php craft resave/entries --update-search-index` again.

**Comment by boboldehampsink** [comment]
@brandonkelly I'm seeing the same thing. The field's values are allowed as keywords. In my case the following:

1. I have a matrix field with two text fields
2. Try to search on any of the matrix content doesn't return the entry the matrix is on
3. Try to search in the matrix field specifically doesn't return any results either
4. I have resaved the entry, made sure search indexes are up to date (run queue job as well)

**Comment by brandonkelly** [comment]
@boboldehampsink Were the block type fields marked as not searchable to begin with? And if so, have the values changed since enabling search keywords?

**Comment by boboldehampsink** [comment]
@brandonkelly no they were marked as searchable to begin with

**Comment by boboldehampsink** [comment]
@brandonkelly do you need extra info?

**Comment by brandonkelly** [comment]
Sorry… nothing changed on Craft’s end that I can think of which would have affected Super Table but not Matrix. I suspect this is related to a Super Table change, since you say Matrix continues to work as expected.

**Comment by boboldehampsink** [comment]
I will debug some more and open a new issue, since I don't use super table here

**Comment by boboldehampsink** [comment]
See #11478

**Comment by brandonkelly** [comment]
Sorry @boboldehampsink, scrolled to the top and read the OP but didn’t realize it wasn’t you 🙃
