### ISSUE TITLE
FR - add notification number/icon to Utilities sidebar when Project Config has changes to apply

### ISSUE THREAD

**Issue by CreateSean** [craftcms/cms#6772]
Not a problem but more of an enhancement. I'd like to see a notification icon/number next to the project config when there are changes to apply similar to what you see with updates or deprecation warnings.

![Annotation 2020-09-02 112314](https://user-images.githubusercontent.com/6899490/92003449-0a38ac00-ed0f-11ea-9af1-d2b50f23333f.jpg)

**Comment by brandonkelly** [comment]
I thought about that, but knowing the exact number of pending changes is expensive and probably not worth it, and just putting a `1` there would be confusing. Will leave this open though.

**Comment by mmikkel** [comment]
I think the actual number of changes is pretty irrelevant - but something like a simple exclamation point to draw attention to the fact that _there are changes_, would be nice.

**Comment by piotrpog** [comment]
@mmikkel good idea.

**Comment by darylknight** [comment]
Just my 2 cents here... the expected workflow when you deploy a project config site is that you run `./craft project-config/apply` on deploy, so there should never be a number here. And when there _are_ pending changes, there's already a massive red bar across the top of the site.

**Comment by brandonkelly** [comment]
Yeah agreed @darylknight. And the red bar is necessary because those pending changes will get overwritten as soon as you make any other project config changes. It’s meant to be only slightly less urgent as the dialog that would block access to the control panel before 3.5, for good reason. Going to go ahead and close this.
