### ISSUE TITLE
Load uncompressed JS in the CP

### ISSUE THREAD

**Issue by thejoshsmith** [craftcms/cms#6778]
### Description
I'm trying to upgrade a plugin to work with Craft 3.5 which heavily extends the `Craft.js` Field Layout Designer. I used to be able to set the `useCompressedJs` config option to false but this no longer seems to work.

When I force Craft to load `Craft.js` in `CpAsset.php` the Field Layout Designer stops working (with no errors). I'd like to be able to do this so I can debug the main script, which makes it easier to extend and customise (as there's no docs!).

### Steps to reproduce

1. Set `useCompressedJs` to false in `general.php` 
2. Load a page with the Field Layout Designer and notice `Craft.min.js` is still served.
3. Force `CpAsset.php` to load the uncompressed `Craft.js` file by changing line 84 to `'js/Craft.js',`
4. Notice the uncompressed file is now loaded but the Field Layout Designer stops working.

### Additional info

- Craft version: 3.5.8
- PHP version: 7.4
- Database driver & version: MySQL 5.7
- Plugins & versions: Field and Tab Permissions 1.4.0

**Comment by brandonkelly** [comment]
We’ve stopped publishing the uncompressed CSS and JS to cut down on the front-end resources that need to be published into the `web/cpresources/` folder. We do publish source maps though, so you can still add breakpoints and debug the code.

If you _really_ want the uncompressed JS, you could clone this repo, comment out the following lines in the gulpfile:

https://github.com/craftcms/cms/blob/4d3dc03a787248c05f2e0dd3698aea55a9fe7680/gulpfile.js#L138
https://github.com/craftcms/cms/blob/4d3dc03a787248c05f2e0dd3698aea55a9fe7680/gulpfile.js#L147

… and then run the following commands:

```bash
npm install
gulp cp-js
```

Then copy the `src/web/assets` folder into to the `vendor/craftcms/cms/src/web/` directory of your project.

**Comment by thejoshsmith** [comment]
That's brilliant. Thanks @brandonkelly!

**Comment by leevigraham** [comment]
For my own notes… In Craft4 you can also:

```shell
cd vendor/craftcms/cms
# Install dependencies
npm install
# Run webpack watch
npx webpack watch -c ./src/web/assets/cp/webpack.config.js --mode=development
```

Now you can edit / debug files in the `vendor/craftcms/cms/src/web/assets/cp/src` directory.
