### ISSUE TITLE
Deleting a Super Table field inside a Matrix block: Invalid owner ID

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#6780]
### Description
I'm setting up a new client site based on my standard boilerplate, which includes a content matrix of some basic field types. If I edit the Matrix and add new things it works fine, but if I delete the Buttons block (which is a Super Table field @engram-design  ) then save the Matrix field, I get this error:

![image](https://user-images.githubusercontent.com/1250017/92085094-fbb2c900-edd0-11ea-9beb-50546926de5e.png)

I'm sending a database dump and composer file to support, as it's probably specific to this site - although I've never run into it before.

To reproduce on this specific site, edit the contentMatrix field, then inside the Call to Action block type, delete the Buttons block and hit save.

![image](https://user-images.githubusercontent.com/1250017/92085831-06219280-edd2-11ea-9925-c365c11ea4aa.png)

I can delete other block types, or fields inside other block types and it works fine - I only get this error if I delete the Super Table field inside the Matrix.

Oh, I also can't delete the entire Matrix field. Craft just does nothing, but I get the same error message in web.log.

### Additional info

- Craft version: 3.5.8
- PHP version: 7.4.8

**Comment by brandonkelly** [comment]
Just fixed this for the next release. Thanks for reporting and providing your files!

**Comment by brandonkelly** [comment]
Craft 3.5.9 is out now with this fix.
