### ISSUE TITLE
JS code blocks containing ".js" tries to load js files as embeds

### ISSUE THREAD

**Issue by lauraevoluted** [craftcms/cms#6781]
### Description

https://craftcms.com/docs/3.x/dev/tags.html#js

We have some elements named the like of `.js-paymentForm`, so adding a block of code inside `{% js %}{% endjs %}` containing that class turns it into a JS script src instead of a block.

The docs mention ending the file name in `.js` for it to be picked up and embedded, seems it isn't looking at the end of the code but for any occurences.

### Steps to reproduce

1. In a twig file, add a block like this:
```
{% js %}
        $('.js-payment-button').on('click', function (ev) {
            ev.preventDefault();
            $('.js-paymentSource-form').submit();
        });
{% endjs %}
```

2. It will generate source code like this:
```
<script src="        $(&#039;.js-payment-button&#039;).on(&#039;click&#039;, function (ev) {
--
  | ev.preventDefault();
  | $(&#039;.js-paymentSource-form&#039;).submit();
  | });
  | "></script>
```

We have changed the css classes of our elements to fix it.

### Additional info

- Craft version: 3.5.7
- PHP version: 7.3

**Comment by brandonkelly** [comment]
I guess you saw that this was fixed in 3.5.8 :)
