### ISSUE TITLE
Generating initial testing setup not working

### ISSUE THREAD

**Issue by qrazi** [craftcms/cms#6790]
### Description
Running the command `craft tests/setup` results in no files or directories to be copied. When inspecting the source in `./vendor`, the path `vendor/craftcms/cms/src/test/internal/example-test-suite` is empty. When downloading source as ZIP from github, that path is also empty. When doing a git checkout, that path is not empty.

### Steps to reproduce

1. Install Craft through steps in documentation at https://craftcms.com/docs/3.x/installation.html#downloading-with-composer
2. Run test setup command `craft tests/setup`

### Additional info

- Craft version: 3.5.8
- PHP version: 7.4.8
- Database driver & version: MySQL 5.7.31
- Plugins & versions: 
    "craftcms/redactor": "2.7.2",
    "misterbk/mix": "1.5.2",
    "nystudio107/craft-typogrify": "1.1.18",
    "vaersaagod/dospaces": "1.1.3",
    "vlucas/phpdotenv": "3.6.7"

<img width="332" alt="image" src="https://user-images.githubusercontent.com/7550540/92225710-e2c71800-eea3-11ea-9704-fe1c3f38c23e.png">

<img width="306" alt="image" src="https://user-images.githubusercontent.com/7550540/92226167-98926680-eea4-11ea-835c-c387b03b2e1c.png">

**Comment by abryrath** [comment]
I'm also seeing this issue. Temporary workaround is to clone the `craftcms/cms` repo using git and copy the files from `src/test/internal/` into the same path in vendor, like @qrazi noted.

**Comment by angrybrad** [comment]
Thanks for the report, all. Fixed in https://github.com/craftcms/cms/commit/5298dbc50d41afee652e276452489fcd16136f3f

**Comment by brandonkelly** [comment]
Craft 3.5.9 is out now with this fix.
