### ISSUE TITLE
Disable GraphQL result caching for queries returning drafts

### ISSUE THREAD

**Issue by JoshCoady** [craftcms/cms#6792]
### Description
Understandably, the GQL cache is not flushed for every draft change, but this means that previews based on GQL results do not reflect the most recent changes.

Just like there is an exemption from caching for mutations, could you do the same if the query contains any of the new draft arguments?

There is a workaround by having the request add a cache-busting timestamp comment to the query text, but that feels like a hack creating a tight coupling to the internal workings of the system.

**Comment by brandonkelly** [comment]
Thanks for reporting that. Just fixed this for the next release. We’ll still cache those queries, but will also start clearing them whenever drafts are saved/deleted.

**Comment by brandonkelly** [comment]
Craft 3.5.9 is out now with this fix.
