### ISSUE TITLE
Preview: {{ entry.id }} returns something thats not entry, draft, revision id

### ISSUE THREAD

**Issue by chanwhab** [craftcms/cms#6794]
### Description
in preview, {{ entry.id }} returns something that is not entry id, what is that, i tried to check  but not matching draftid, revisionid .. etc

To me, this should alwats return entry.id instead oc lther things

use case: i need to inject the entry.id in sprig component, and when in preview this will cause error as entry.id is not returning the right id

### Steps to reproduce

1.
2.

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
It’s the draft’s element ID. You can get the original entry ID using `sourceId` instead of `id`.

**Comment by chanwhab** [comment]
I got the reason why i have inconsistent result on it. Yet i am confused on how to properly code it.

When using preview,  I only checked `{% if craft.app.request.isPreview %}`, yet:

For `current` => `craft.entries.id(entry.id).one()` 
For `draft` =>  `craft.entries.drafts().id(entry.id).one()` works, but `craft.entries.draftId(entry.id).one()` not working
For `revision` => `craft.entries.revisions().id(entry.id).one()` works, `craft.entries.revisionId(entry.id).one()` not working

but then how can we know if the current preview is `current`, `draft` or `revision`?
or can i use one single query to find the entry without worrying whether it's `current`, `draft` or `revision`

**Comment by brandonkelly** [comment]
What are you actually trying to do? You already have the entry via the `entry` variable; you don’t have to re-fetch it.

**Comment by chanwhab** [comment]
i am building a entry page that will automatically load the next entry using `sprig` plugin.

*entry/_page.twig*
````
{{ sprig("_entry/_sprig", {'entryId': entry.id }) }}
````
*entry/_sprig.twig*
````
{% set entryId = entryId ?? entry.id %}
{% set entry = craft.entries.id(entryId).one() %}
{% set prevEntry = entry.getPrev({orderBy:'postDate' }) %}
...
...
<div sprig s-trigger="revealed">
<input  type="hidden" name="entryId" value="{{ prevEntry.id }}">
</div>
````
I can only pass string but not variable `entry` into `sprig component`

**Comment by brandonkelly** [comment]
Gotcha. Well if you just want to pass the main entry ID, then replace `entry.id` with `entry.sourceId`.

**Comment by chanwhab** [comment]
Work perfectly.
