### ISSUE TITLE
Wrong author after duplicate a entry

### ISSUE THREAD

**Issue by Jan10** [craftcms/cms#6798]
### Description
If user A creates a entry and user B duplicates it, user A is the author of the entry, although he didn't create the entry.

### Steps to reproduce

1. Create a entry with user A
2. Duplicate the entry with user B
3. The author of the new (duplicated) entry is user A

### Additional info

- Craft version: 3.5.8

**Comment by brandonkelly** [comment]
Well… the author is a configurable setting of the entry, not a historical record. So I’d say this is working as expected.

Note that if you go to an entry’s edit page, then change the Author value, then click Save → “Save as a new entry”, the newly selected Author will be saved to the duplicated entry immediately.
