### ISSUE TITLE
Spinner not moving while installing new plugin

### ISSUE THREAD

**Issue by vaughn-taylor** [craftcms/cms#6800]
### Description

I've noticed that the spinner is not spinning when I'm installing new plugins. I noticed this after I installed 3.5 and it continues to be the case in 3.5.8

### Steps to reproduce

1. Install plugin and view the spinner during installation

### Additional info

- Craft version: Since 3.5, but currently at 3.5.8
- PHP version: 7.3.4
- Database driver & version:
- Plugins & versions: Any plugin installation

**Comment by usmcgwg** [comment]
Sorry had phishing incident

**Comment by usmcgwg** [comment]
I'm resolving the issues now

**Comment by brandonkelly** [comment]
It’s just an animated GIF, so not sure what we could do to help here. Would likely be fixed for you when we implement #6783, as that would switch to a CSS animation.
