### ISSUE TITLE
Mailer component in config file not working anymore

### ISSUE THREAD

**Issue by jerome2710** [craftcms/cms#6801]
### Description
For our 30-ish Craft 3 websites we are overriding the mailer-component through the `config/app.php` file. This way, we can dynamically use our preferred mail service on staging & production environments while catching outgoing mails on our development environments.

I noticed some of the sites are sending mails with invalid settings now. After some investigation it seems that the `config/app.php` settings are now being ignored and the yellow notice mentioned in [this comment](https://github.com/craftcms/cms/issues/2554#issuecomment-375653736) by @brandonkelly is not present anymore.

It seems that the configuration now requires either `*` or a site handle. Placing the mailer-component in the root of the `app.php` does not work anymore! Is this a deliberate choice in one of the latest updates or some sort of bug? I have not seen a breaking warning in the changelog and this threatens the e-mail delivery of all our sites.

```php
// current/broken scenario
'components' => [
    'mailer' => function () {
        return DynamicConfiguration::getMailerSettings();
    },
],

// new/working scenario
'*' => [
    'components' => [
        'mailer' => function () {
            return DynamicConfiguration::getMailerSettings();
        },
    ],
],
    

```

### Additional info

- Craft version: 3.5.5
- PHP version: 7.2.24

**Comment by jerome2710** [comment]
I have reverted the "new/working scenario" from above. Moving the mailer-component in the `*`-array caused issues with our other settings in the `app.php`-file. Modules weren't being bootstrapped now as well. I am not sure if we should move all of our settings into the `*`-array or just the mailer-component?

Could someone of Pixel&Tonic/Craft look into this and possibly point out a change in one of the recent updates which seem to have broken this? This is an urgent issue for us and has not been mentioned as a breaking change in the changelog. The wiki-page seems to be insufficient as well: https://craftcms.com/docs/3.x/config/#mailer-component

**Comment by brandonkelly** [comment]
Nothing has changed recently. `config/app.php` is capable of being a [multi-environment config](https://craftcms.com/docs/3.x/config/#multi-environment-configs) if there is a `*` key at the top level of the returned array. So guessing at some point you added that, and didn’t update the rest of the config accordingly.

**Comment by jerome2710** [comment]
I understand the capability of the multi-environment config, but we are not using it nor have we made any changes to the `app.php`. Our websites use the mailer-component mentioned above, but after upgrading from 3.4 to 3.5 the following message disappeared on the /cp/settings/email page:

<img width="591" alt="Schermafbeelding 2020-09-09 om 09 26 22" src="https://user-images.githubusercontent.com/4600095/92567866-9d796080-f27e-11ea-837d-0738e3d659f8.png">

The defined settings are being ignored and will only start working if I place the mailer-component inside the `*` key.

**Comment by angrybrad** [comment]
@jerome2710 any chance we could get SSH/Craft CP access to one of the boxes this is happening on? If so, could you send the creds over to support@craftcms.com?

**Comment by brandonkelly** [comment]
Where was the `mailer` component being defined before moving it into the `*` key? And did a `*` key already exist?

**Comment by jerome2710** [comment]
@angrybrad Unfortunately, I cannot give you SSH-access to our companies servers due to security measurements. I could give you access to our CP, but I believe there's not much more to see than just the override-warning.

@brandonkelly The `mailer`-component was being defined in the `components`-key in the top level of the array, which is being returned in the `config/app.php`.

Using the `*`-key is not much of a disaster, but it's annoying that the initial setup doesn't seem to work anymore all of a sudden. Placing the `components`-key inside the `*`-key caused our modules not being bootstrapped. Do I need to move all keys (such as `modules` and `bootstrap`) inside the `*`-key as well, so this is the only root level that is being returned by `config/app.php`?

**Comment by brandonkelly** [comment]
Was there already a top-level `*` key in the same array? If so there’s no way that was working as expected to begin with. If a config contains a `*` key, then all other top-level keys in the array are matched against the current environment name.

https://github.com/craftcms/cms/blob/23a16c91afcdd2ec31491944de69593b6b27bd41/src/services/Config.php#L206-L223
