### ISSUE TITLE
 'Save as new product' not working as 'Save as new entry'

### ISSUE THREAD

**Issue by Bavixke** [craftcms/cms#6804]
**Description**
I have multisite installation. When I save a product as new product, the fields of the other sites are overwritten with the new content of the primary site. 
If I do the same thing with entries, the fields on other sites (languages) will show the content of the "original" entry.

Thought it maybe is a propagation method issue. Can we see/edit the method for products?

**To Reproduce**
How, and what happened?
1. In the CP go to Commerce -> Products
2. Open an existing product with content in different languages.
3. Edit title field and save as new product.
4. Switch site (language) for the product.

**Expected behavior**
Seeing the content of the "original" product for other sites (languages)

**Additional info**
- Craft version: 3.5.8
- Commerce version: 3.2.3
- PHP version: 7.4.5
- Database driver & version: MySQL 5.7.29

**Comment by brandonkelly** [comment]
This ended up being a bug that affected entries, assets, and categories as well. Just fixed within Craft CMS for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.9 is out now with this fix.
