### ISSUE TITLE
All fields shown as 'used as search keywords' on fields index page

### ISSUE THREAD

**Issue by DavidOliver** [craftcms/cms#6808]
### Description

Having updated to Craft 3.5.9 and got the new 'This field’s field’s values are used as search keywords' icon (should one of those 'field's' be removed?) on the Fields settings index page, I'm finding that all fields have the icon, including the ones which are not set to be used as search keywords.

I've tried re-saving a field's settings, but that doesn't make a difference.

![image](https://user-images.githubusercontent.com/192853/92585465-46cb5100-f295-11ea-978e-0b098199de2a.png)

![image](https://user-images.githubusercontent.com/192853/92585576-711d0e80-f295-11ea-9454-54ea16fbea95.png)

### Additional info

- Craft version: 3.5.9
- PHP version: 7.4.9
- Database driver & version: MySQL 8.0.21
- Plugins & versions: 
  - Amazon S3 1.2.11
  - Contact Form 2.2.7 
  - Cookies 1.1.12 
  - Element API 2.6.0
  - Feed Me 4.2.3 
  - Guest Entries 2.3.0 
  - Mailgun 1.4.3 
  - Redactor 2.7.4 
  - Redirect Manager 1.1.1 
  - Typogrify 1.1.18 
  - reCAPTCHA 1.5.0

**Comment by juban** [comment]
I can confirm that the icon is displayed in both case whether the field is marked as indexed or not.

**Comment by brandonkelly** [comment]
Just fixed this for the next release. Thanks for reporting!

**Comment by brandonkelly** [comment]
Craft 3.5.10 is out now with this fix.
