### ISSUE TITLE
Dropdowns - all options marked as default

### ISSUE THREAD

**Issue by raptureaid** [craftcms/cms#6809]
### Description
Just came across this issue with a matrix field we're using for content building across a site. On new entries, the dropdown options are not respecting the default value - it defaults to the first option in the list.

Upon reviewing the field settings for the matrix block, all of the options are checked as default. When editing the field to choose a single default value, the change is reverted back to all selected after saving.

![Screen Shot 2020-09-09 at 10 47 57 AM](https://user-images.githubusercontent.com/5720326/92614831-7aed4480-f28a-11ea-95f5-02c190b2e1ee.png)

This is just one of about 30 dropdowns within this matrix field with the issue.

### Additional info

- Craft version: Craft Pro 3.4.26
- PHP version: 7.1.33
- Database driver & version: MySQL 5.6.43

**Comment by raptureaid** [comment]
This is occurring on a standard dropdown field as well, so doesn't seem to be tied to matrix fields.

**Comment by Wiejeben** [comment]
These checkboxes should be radio checkboxes in my opinion, or am I overlooking something?

**Comment by brandonkelly** [comment]
I’m not able to reproduce this; only able to select one Default option at a time. Are you getting any JavaScript errors on the page?

> These checkboxes should be radio checkboxes in my opinion, or am I overlooking something?

@Wiejeben It’s not possible to deselect a radio button.

**Comment by raptureaid** [comment]
@brandonkelly I'm not seeing any errors upon loading, altering or saving the page. I've looked back at some backups and staging servers and found this started in the last 10 days - during which no Craft or plugin updates have been installed. A few new redactor and plain text fields were added, but no changes were made to any dropdown or matrix fields with dropdowns. So something seems to have gone amiss with the DB.

Is there a way to check the values in the DB?

**Comment by brandonkelly** [comment]
Not really sure what could go wrong in the DB. If you uncheck all the Default checkboxes and then start checking new ones, does it behave as expected (only one selected at a time)?

**Comment by raptureaid** [comment]
So I found the field in the DB. The settings are stored as follows, with the option value also being inserted as the default value:
```
{"optgroups":true,"options":[{"label":"1/4","value":"1-of-4","default":"1-of-4"},{"label":"1/3","value":"1-of-3","default":"1-of-3"},{"label":"1/2","value":"1-of-2","default":"1-of-2"},{"label":"2/3","value":"2-of-3","default":"2-of-3"},{"label":"3/4","value":"3-of-4","default":"3-of-4"}]}
```
Comparing this to a working version of the field, it looks as though the default value should be `"default":"1"` and blank for all other options. I can update the DB entry as such: 
```
{"optgroups":true,"options":[{"label":"1/4","value":"1-of-4","default":""},{"label":"1/3","value":"1-of-3","default":""},{"label":"1/2","value":"1-of-2","default":"1"},{"label":"2/3","value":"2-of-3","default":""},{"label":"3/4","value":"3-of-4","default":""}]}
```

This then shows the expected results in Craft:

<img width="919" alt="Screen Shot 2020-09-10 at 5 07 07 PM" src="https://user-images.githubusercontent.com/5720326/92806679-3647d300-f388-11ea-861b-4a69856c931b.png">

However, saving the field in the control panel (with or without making a change), cause all options to be marked as default again. With the first code block back in the DB settings.

**Comment by brandonkelly** [comment]
Weird… your option values are getting saved to the `default` keys. Not sure how that could be happening, and not able to reproduce. Can you try updating Craft CMS?

**Comment by raptureaid** [comment]
Upgrading Craft allowed the fields to be resaved with the correct default values, resolving the issue.
