### ISSUE TITLE
Eager loaded children/descendants returns empty past structure level 3

### ISSUE THREAD

**Issue by evanwarner** [craftcms/cms#6820]
### Description
Been staring at this for a bit and I think I've got the right diagnosis. I'm loading a set of entries, and eager loading `.with(['myCategoryField.children'])`. My intent was to use this to find out which of the related categories are the "deepest in branch" (i.e. which ones did I actually select for the entry) via this logic:

```twig
{% set relatedCategoryIds = entry.myCategoryField | map(c => c.id) %}
{% for category in entry.myCategoryField %}
    {% set skipCategory = false %}
    <p>checking {{ category.title }}</p>
    {% if category.children | length %} {# <--- This is 0 for level 3+ categories, though category.hasDescendants is still true #}
        <p>{{ category.title }} has children</p>
        {% for child in category.children %}
            {% if child.id in relatedCategoryIds %}
                {% set skipCategory = true %}
            {% endif %}
        {% endfor %}
    {% endif %}
    {% if not skipCategory %}
        <p>{{ category.title }} was selected</p>
    {% endif %}
{% endfor %}
```
However, every category at level 3 or deeper has an empty `.children` array (as if they were a leaf category), and so all categories at level 3 or deeper are seen as selected. **If I remove the eager loading of `children` and use `{% for child in category.getChildren() %}`, the logic works perfectly and only the deepest category per branch is picked out.**

### Steps to reproduce

1. Create a category structure >3 levels deep
2. Apply the deepest level category to an entry
3. Query the entry and eager load `myCategoryField.children`
4. Execute the above logic on the entry, and all categories level 3 and deeper will print "______ was selected."

### Additional info

- Craft version: 3.5.8
- PHP version: 7.4.2
- Database driver & version: MySQL 5.7.26
- Plugins & versions: Asset Rev 6.0.2, Preparse Field 1.2.1, Redactor 2.7.4, Tags 1.0.7

**Comment by evanwarner** [comment]
In thinking this through I figured out a _much_ more efficient logic to do what I want, but the bug still stands.

**Comment by brandonkelly** [comment]
Thanks for reporting this! Definitely was a bug there, and now fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.10 is out now with this fix.
