### ISSUE TITLE
Typo on search keywords icon title attribute

### ISSUE THREAD

**Issue by k7y6t5** [craftcms/cms#6824]
### Description
Settings > Fields - The search keywords icon's title says "field's" twice:"This field’s field’s values are used as search keywords."

### Steps to reproduce

1. Go to Settings > Fields and hover over the magnifying glass that alerts a user that the field's values are being used as search keywords.

### Additional info

- Craft version: 3.5.9 (Pro)
- PHP version: 7.4.9
- OS version: Darwin 18.7.0
- Database driver & version: MySQL 5.5.5
- Image driver & version: GD 7.4.9
- Plugins & versions: 
    - Amazon S3 1.2.11
    - Postmark 2.0.2
    - Redactor 2.7.4
    - Redactor Custom Styles 3.0.4
    - Super Table 2.6.2

**Comment by brandonkelly** [comment]
Whoops, thanks for pointing that out!
