### ISSUE TITLE
Field values are marked as search keywords regardless of settings

### ISSUE THREAD

**Issue by piperhaywood** [craftcms/cms#6825]
### Description

I’ve just set up a brand new installation of Craft v3.5.9. I added a plain text field with the “Use this field’s values as search keywords” unticked and saved. When I looked at it in the list of fields, there is an orange icon next to the field with the tooltip “This field’s field’s values are used as search keywords” (including the typo). When I tick the box, it looks the same. I then added a Redactor field, same behavior for this field.

This is the first database config step that I’ve taken on this site, so it is nearly empty. The only things I’ve done so far are install two plugins (see below) and enable the project config file.

### Steps to reproduce

1. Install Craft v3.5.9
2. Enable project config file.
3. Add a plain text field.

### Additional info

- Craft version: v3.5.9
- PHP version: v7.2.19
- Database driver & version: MySQL 5.7.26
- Plugins & versions: Redactor v2.7.4, Typogrify v1.1.18

**Comment by piperhaywood** [comment]
Related to #6824

**Comment by brandonkelly** [comment]
This was already reported by #6808, and is fixed for the next release :)

**Comment by piperhaywood** [comment]
Ah thanks! Sorry, tried to find already open issues and missed it! Thanks :)
