### ISSUE TITLE
Add a link on the single section settings page to the edit entry types page (and vice versa)

### ISSUE THREAD

**Issue by dgtlcrftrs** [craftcms/cms#6826]
### Description

I commonly find myself accidentally clicking on the 'settings' for a section instead of the 'edit entry types' link. 

It would be great if there was a button / link to go from the settings page for that section to the entry types page for it. (and vice versa).

It would be even better if these were all on one single page, showing you the entry types for the section and the settings in one place.

**Comment by brandonkelly** [comment]
Good idea. I just added tabs to the section settings page, so you can easily get to the section’s entry type index from there.

<img width="321" alt="The tabs on a section’s settings page" src="https://user-images.githubusercontent.com/47792/92999884-8a160180-f4d9-11ea-86bc-cb6bfa26502f.png">

**Comment by brandonkelly** [comment]
Craft 3.5.10 is out now with this change.

**Comment by piotrpog** [comment]
Great stuff, thanks for introducing that.

**Comment by dgtlcrftrs** [comment]
> Craft 3.5.10 is out now with this change.

Amazing thank you so much
