### ISSUE TITLE
Improve editor experience for editing elements in HUD by making it full-width

### ISSUE THREAD

**Issue by dgtlcrftrs** [craftcms/cms#6827]
### Description

Whenever changing content through the hud interface for inline editing the fields are always squashed and difficult to use. A lot of field plugins break in this view too. It would be great if there were a way to make this experience better. Instead of the hud attached to the field it's connected on, it could open a modal that fills the screen, giving more room to have a much improved authoring experience. 

It could even be a setting on elements like a section to designate the inline editing display type (so you can still use the hud for really simple content structures)

**Comment by brandonkelly** [comment]
Sorta looks like the same request as #6647, which we are planning to address in Craft 4 :)

**Comment by brandonkelly** [comment]
This is resolved for 3.7! See #8017.
