### ISSUE TITLE
Browser hangs when browsing assets using S3 plugin

### ISSUE THREAD

**Issue by bliswebagency** [craftcms/cms#6834]
### Description
Since upgrading to Craft 3.5 users have reported that Assets hangs after using it for a while.

Below is a video showing Assets in Craft 3.1 and Craft 3.5

http://shared.bl.ms/Z2ybh2

Note how in 3.1, changing back and forward between views is fast and reliable.

Craft 3.5 however slows down after around 9 interactions and hangs at 11 interactions.

The only difference between the two sites shown in the video is the version of Craft. All other factors (server, etc) are the same.

### Steps to reproduce

1. Go into Assets
2. Toggle between the two different views

### Additional info

- Craft version: 3.5.9
- PHP version: 7.0
- Database driver & version: MariaDB 10.0.38
- Plugins & versions: Amazon S3 1.2.11

**Comment by brandonkelly** [comment]
Hm, I’m not able to reproduce this; switching between the views is just as responsive on my end after toggling about 100 times, with varying speeds. Could perhaps be due to a plugin or custom module/JS code. Can you think of anything else that has changed besides the Craft update?

**Comment by bliswebagency** [comment]
Nothing else major has changed.

Are you using the S3 plugin when you do your tests?

**Comment by bliswebagency** [comment]
Thanks for your help Brandon. We've setup a clean 3.5.9 install on the same server and all seems ok. Given this, it's looking like the issue may be related to DB optimisation rather than anything 3.5.9 is doing. I'll close this ticket.
