### ISSUE TITLE
Craft 3.5+: ability to drag and drop field group as tab in Sections

### ISSUE THREAD

**Issue by ohbiko** [craftcms/cms#6840]
### Description

(under Settings > Sections > Edit Entry Type)
This used to be possible in Craft < 3.5.  Can you please bring this back?  The ability to drag and drop field group directly as tags saves tremendous amount of time.

**Comment by brandonkelly** [comment]
This is a duplicate of #6568. It will be resolved with #1674.

**Comment by ohbiko** [comment]
Sweet can't wait for this feature!
