### ISSUE TITLE
orderBy('customTimeField') is not working because of hidden MySQL date.

### ISSUE THREAD

**Issue by maxfrischknecht** [craftcms/cms#6842]
### Description
When you try to sort matrix blocks by a custom date/time field where you only use the time the order is wrong. Because in the background MySQL seems to create a complete date based on when you make the entry. This can not be solved with the additional `time()` parameter, probably because you can't submit a complete date in this context. This makes the `time` field useless in all cases where sorting is needed.

### Steps to reproduce

```
{% set allBlocks = entry.myMatrixField.orderBy('myMatrixDateField') %}

<ul>
    {% for block in allBlocks %}
        <li>{{block.myMatrixDateField|time()}}</li>
    {% endfor %}
</ul>
```

Ouput:
```
    07:00:00
    08:00:00
    12:10:00
    15:30:00
    16:00:00
    16:30:00
    17:00:00
    17:30:00
    18:10:00
    08:30:00 // => wrong from here
    12:00:00
```

Because if you output the complete date (altough there should be none) with `<li>{{block.myMatrixDateField|date('d F Y - H:i')}}</li>` you see why the order is wrong:

Output complete

```
    08 September 2020 - 07:00
    08 September 2020 - 08:00
    08 September 2020 - 12:10
    08 September 2020 - 15:30
    08 September 2020 - 16:00
    08 September 2020 - 16:30
    08 September 2020 - 17:00
    08 September 2020 - 17:30
    08 September 2020 - 18:10
    15 September 2020 - 08:30 // => wrong from here because of hidden date
    15 September 2020 - 12:00
```

### Additional info

- Craft version: Craft Pro 3.5.9
- PHP version: 7.4.10
- Database driver & version: MySQL 5.7.26

**Comment by brandonkelly** [comment]
Just fixed this for the next release. Going forward the date will always be set to 1970-01-01 if only the time is shown.

You will be able to apply this change to all existing values by running the following command:

```sh
php craft resave/entries
```

**Comment by brandonkelly** [comment]
Craft 3.5.11 is out now with that change.

**Comment by jasonleelab** [comment]
This causes all my time fields to be 1hr earlier.

Original video where I show the bug: https://share.getcloudapp.com/yAulPeWW 

Video showing this change as the culprit: https://share.getcloudapp.com/mXu6Z4Dp

Craft version: Craft Pro 3.5.11
PHP version: 7.4.2
Database driver & version: MySQL 5.7.26

**Comment by brandonkelly** [comment]
Well, shoot, forgot about time zones. I have reverted that change for the next release, and will think about a better way to fix this.

In the meantime, you should be able to solve the ordering issue by casting the value as a TIME.

```twig
{% set allBlocks = entry.myMatrixField
  .orderBy(expression('TIME(`field_blockTypeHandle_myMatrixDateField`) ASC'))
  .all() %}
```

**Comment by brandonkelly** [comment]
I’ve just added a new “Time” field type for the next release, which _only_ stores time info w/out worrying about dates and time zones. It’s possible to convert a Date field to Time, however you’ll need to update the existing values to account for your system’s time zone offset, if it’s not set to UTC. See https://github.com/craftcms/cms/issues/6775#issuecomment-702015558 for details.

**Comment by brandonkelly** [comment]
Craft 3.5.12 is out now with the Time field!
