### ISSUE TITLE
Allow assets to be added to table columns without their labels

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#6848]
I keep finding myself wanting to show something like a Featured Image in the table columns for quick visual reference on blog posts, products, or other things, but usually don't because of the label (image title) that is displayed alongside it. These tend to take up too much space, and are generally poorly named.

It'd be nice if there was an option to include asset fields without their label/title.

**Comment by brandonkelly** [comment]
Good idea! Just added a new “Preview Mode” setting to Assets fields that lets you choose whether to include related assets’ titles in element indexes.

**Comment by brandonkelly** [comment]
Craft 3.5.11 is out now with that new setting 🎉
