### ISSUE TITLE
GraphQL query not working with arguments

### ISSUE THREAD

**Issue by Digital-E** [craftcms/cms#6851]
### Description

I'm currently posting a GraphQl query with a `slug` argument. However it is always returning the same entry, regardless of the argument.

### This is the query

```
    query($slug:[String]) {
      entry(slug: $slug) {
        id
        title
        uid
        slug
      }
    }
```

### It is always returning this entry

```
{ id: '9',
  title: 'Test',
  uid: 'd70ea51a-248e-4004-b935-25148c740ca1',
  sourceUid: 'd70ea51a-248e-4004-b935-25148c740ca1',
  slug: 'test' }
```

### If I manually enter a different slug it returns the correct entry

Query:

```
    query {
      entry(slug: "test2") {
        id
        title
        uid
        sourceUid
        slug
      }
    }
```

Response:

```
{ id: '13',
  title: 'Test2',
  uid: '84748b22-074c-4821-910f-f2ebac9cd381',
  sourceUid: '84748b22-074c-4821-910f-f2ebac9cd381',
  slug: 'test2' }
```

I'm not quite sure why the argument isn't being taken into account?

### Additional info

- Craft version: Craft Pro 3.5.10
- PHP version: 7.3.8
- Database driver & version: MySQL 5.7.26

**Comment by brandonkelly** [comment]
Are you actually setting the `$slug` value via the Variables JSON?

**Comment by Digital-E** [comment]
Hi, @brandonkelly, It so happens that I wasn't! I referred back [here](https://craftcms.com/docs/3.x/graphql.html#sending-api-requests) in the docs and now it's working.

I totally forgot to set variables as I'm using Next.js in this project, and coming from Gatsby I didn't need to set variables in GraphQL requests.

Thanks a bunch!
