### ISSUE TITLE
console commands not working

### ISSUE THREAD

**Issue by rolfkokkeler** [craftcms/cms#6852]
we upgraded to craft 3.5.10.1 and none of the console commands are functional
for example
php craft

no error, no output

- Craft version: 3.5.10.1
- PHP version: 7.2.33
- Database driver & version: MySQL 5.5.5
- Plugins & versions: 
    "carlcs/craft-redactorcustomstyles": "3.0.4",
    "craftcms/aws-s3": "1.2.11",
    "craftcms/cms": "3.5.10.1",
    "craftcms/redactor": "2.7.4",
    "doublesecretagency/craft-cpjs": "2.2.1",
    "ether/seo": "3.6.6",
    "nystudio107/craft-cookies": "^1.1",
    "sebastianlenz/linkfield": "1.0.23",
    "spicyweb/craft-embedded-assets": "2.3.4",
    "verbb/super-table": "^2.0.7",
    "vlucas/phpdotenv": "^2.4.0",
    "xpertbot/craft-wheelform": "2.5.1"

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you try disabling those plugins and see if that helps?

**Comment by rolfkokkeler** [comment]
Brandon,

tried it, did not do anything.

I upgraded another project of ours, same issue.

Then I created a new craft project using composer.
This project gave me working console commands!
I compared the upgraded project with the newly installed and saw the upgraded is missing the file 'craft' in the craft root folder. I copied this manually to both upgraded projects and now the console commands are oke.

**Comment by brandonkelly** [comment]
Ah, yeah that makes sense. The [recommended upgrade process](https://craftcms.com/docs/3.x/upgrade.html#performing-the-upgrade) is to use a new Craft 3 installation as a starting point, which would give you that `craft` executable file.
