### ISSUE TITLE
"Template" UI Element breaks out of field editor if too long

### ISSUE THREAD

**Issue by knynkwl** [craftcms/cms#6854]
### Description
![Screen Shot 2020-09-17 at 10 04 40 AM](https://user-images.githubusercontent.com/4225771/93482148-61bd4700-f8cd-11ea-96d4-ec4fc05ff68a.png)

### Additional info
- Craft version: 3.5.8

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.11 is out now with that fix.
