### ISSUE TITLE
Widget settings dropdown are masked by other widgets

### ISSUE THREAD

**Issue by engram-design** [craftcms/cms#6860]
### Description
As per the below screenshot.

![Screen Shot 2020-08-06 at 12 10 13 pm](https://user-images.githubusercontent.com/1221575/89482725-d6389c80-d7dd-11ea-9ceb-2b8cffbba4fe.png)

Reported in https://github.com/dukt/analytics/issues/28.

### Additional info

Craft version: 3.4.23
PHP version: 7.2
Analytics 4.0.10

**Comment by benjamindavid** [comment]
I actually found a way to fix that from the widget's JS. 

Thanks, @engram-design!

https://github.com/dukt/analytics/commit/af508dc6371baf9176cebf34b82426eaf56492e6
