### ISSUE TITLE
GraphQL: Query multiple image transforms.

### ISSUE THREAD

**Issue by wrux** [craftcms/cms#6863]
### Description

I'm looking into rebuilding my blog using Gridsome and GraphQL. I cannot seem to find a decent way to pull multiple image transform sizes into an array.  The idea being, I can create a responsive image component and then parse in the array of image sizes. 

Here's the data structure I am trying to achieve:

```json
{
  "data": {
    "entry": {
      "title": "test",
      "url": "http://bloke.test/post/test",
      "teaserImage": [
        {
          "mimeType": "image/jpeg",
          "title": "test",
          "width": 540,
          "height": 300,
          "url": "/posts/test/_small/test.jpg"
        },
        {
          "mimeType": "image/jpeg",
          "title": "test",
          "width": 770,
          "height": 600,
          "url": "/posts/test/_medium/test.jpg"
        }
      ]
    }
  }
}
```

Is this possible in GraphQL? I've tested multiple ideas with fragments or trying to alias fragments but I cannot seem to get it to pull an array of transform sizes.

**Comment by brandonkelly** [comment]
That’s possible by [aliasing](https://graphql.org/learn/queries/#aliases) the `url` field:

```graphql
teaserImage {
  mimeType
  title
  url_small: url(transform:"small")
  url_medium: url(transform:"medium")
}
```

Result would end up looking like:

```json
{
  "teaserImage": [
    {
      "mimeType": "image/jpeg",
      "title": "test",
      "url_small": "/posts/test/_small/test.jpg",
      "url_medium": "/posts/test/_medium/test.jpg"
    }
  ]
}
```

If you need to fetch the widths/heights of those transforms, you can alias the `width` and `height` fields with the same `transform` argument applied.

**Comment by wrux** [comment]
@brandonkelly That's not a very elegant solution as there could be any number of transforms and prefixing the attributes seems like a workaround. Would it make sense to place the transformed images into an array?

```
{
  "teaserImage": [
    {
      "title": "test",
      "transforms": [
        {
          "url": "/posts/test/_small/test.jpg",
          "mimeType": "image/jpeg",
          "width": 600,
          "height: 400
        },
        {
          "url": "/posts/test/_medium/test.jpg",
          "mimeType": "image/webp",
          "width": 800,
          "height: 500
        },
      ]
    }
  ]
}
```

**Comment by andris-sevcenko** [comment]
@wrux this might also interest you: https://github.com/craftcms/cms/issues/6660#issuecomment-676838710

**Comment by andris-sevcenko** [comment]
@wrux wondering if this can be closed?

The query provided in the link is similar to what you were trying to achieve. If you're looking for the `srcset` functionality, that also has been implemented - https://github.com/craftcms/cms/issues/6660#issuecomment-718179846

**Comment by wrux** [comment]
@andris-sevcenko Yes I think so. Closing it 👍
