### ISSUE TITLE
Undefined class constant 'VERSION' error in SystemReport.php (related to Guzzle version)

### ISSUE THREAD

**Issue by daveyjones** [craftcms/cms#6864]
### Description

I'm seeing the following error when navigating to Utilities in the control panel. I ran `composer update` from the terminal but no luck. Any ideas?

<img width="1035" alt="Screen Shot 2020-09-18 at 12 34 15 PM" src="https://user-images.githubusercontent.com/2852617/93637994-648e6980-f9ab-11ea-826e-0901c1d5be12.png">

### Steps to reproduce

1. Open console.
2. Click on Utilities.

### Additional info

- Craft version: 3.5.8
- PHP version: 7.4.10
- Database driver & version: MySQL 8.0.21
- Plugins & versions: Maps 3.8.4.1

**Comment by brandonkelly** [comment]
Hm, strange. Can you try deleting your entire `vendor/` folder, and then running `composer install`?

**Comment by daveyjones** [comment]
@brandonkelly No luck I'm afraid...same error.

**Comment by daveyjones** [comment]
I went directly to the updates page in the control panel and updated. Everything worked except for the Craft 3.5.11.1 update. I get the following error when running that update (similar to above...missing a version number constant).

<img width="689" alt="Screen Shot 2020-09-18 at 3 13 57 PM" src="https://user-images.githubusercontent.com/2852617/93649893-e7222380-f9c1-11ea-82d5-020c0fea7b30.png">

**Comment by brandonkelly** [comment]
Can you please send your `composer.json` and `composer.lock` files over to support@craftcms.com? We can try to reproduce with those.

**Comment by daveyjones** [comment]
Done!

**Comment by angrybrad** [comment]
This was caused by a custom module that was manually autoloading Guzzle 7+ (where that class constant has been removed), thus breaking Craft's Guzzle 6.x requirements.
