### ISSUE TITLE
"Bad slug" on all entries in v3.5.11

### ISSUE THREAD

**Issue by TheFunkyMonk** [craftcms/cms#6866]
### Description

Slugs are errantly getting flagged with "Bad slug" in Craft v3.5.11

### Steps to reproduce

1. Update to 3.5.11
2. Load an entry within a structure

![unknown](https://user-images.githubusercontent.com/1728770/93647839-3a927280-f9be-11ea-9f31-c364b7b1047d.png)

### Additional info

- Craft version: 3.5.11
- PHP version: 7.3

**Comment by brandonkelly** [comment]
Doh! Thanks for reporting that! Just released 3.5.11.1 with a fix.
