### ISSUE TITLE
Setup procedure fails in both web & cli if database password contains `#` char.

### ISSUE THREAD

**Issue by sebastiannoell** [craftcms/cms#6867]
### Description
Was unable to get through the Setup procedure because my database password holds a `#`. The setup procedure itself reported that the connection was successful and finished it adding tables to my database. But when trying to access the site or cp, i kept redirected to the installer again. I was able to hotfix that, by wrapping the password in single-quotes. 

### Steps to reproduce

1. Run the installer with a db password holding a `#`
2. After successful install, try to access the site or the cp.

### Additional info

- Craft version: 3.5.11.1
- PHP version: 7.4
- Database driver & version: 10.5.5-MariaDB Homebrew
- Plugins & versions: none

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.12 is out now with that fix.
