### ISSUE TITLE
Scroll issue with Google Chrome and macOS

### ISSUE THREAD

**Issue by lesaff** [craftcms/cms#6868]
### Description
This is such a specific issue. I am not sure whether it is an issue with Craft or just Chrome and macOS on a specific MacBook Pro models. I am filing this report just in case someone else is having a similar problem. I tried it on a Firefox and it was fine.

I am having problem scrolling up/down in the admin panel (see attached screen recording)
https://www.dropbox.com/s/9zz8pau3g513601/craft-chrome-scroll-issue.mov?dl=0

EDIT: This only happens on my secondary monitor, connected to my MBP via a DVI to USB-C cable. I tried using DVI to HDMI and had the same issue as well.

### Steps to reproduce

1. Open admin panel using Google Chrome (85.0.4183.102 (Official Build) (64-bit)) and macOS Mojave (v10.14.6) 

2. Try to scroll up and down on a longer pages

### Additional info

- Craft version: Craft Pro 3.5.11.1
- PHP version: 7.4.10
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
- Google Chrome version: 85.0.4183.102 (Official Build) (64-bit)
- MacOS version: Mojave v10.14.6
- Hardware: MacBook Pro 15" 2018
- Graphics: Radeon Pro 555X 4gb

**Comment by brandonkelly** [comment]
That’s the exact same setup I’m on, and not able to reproduce.

Can you try to reproduce on a Happy Lager site created at https://demo.craftcms.com? If you can, I’d suspect maybe it’s due to a browser extension. Otherwise, perhaps something plugin related, or some custom CSS/JS you’ve added to the control panel.

**Comment by lesaff** [comment]
I just tested it on the Happy Lager site using Chrome incognito mode (no extensions), see link below
https://www.dropbox.com/s/0ol0t555g86t5y5/craft-chrome-incognito-happy-lager.mov?dl=0

Note, I added this to the initial issue report:

EDIT: This only happens on my secondary monitor, connected to my MBP via a DVI to USB-C cable. I tried using DVI to HDMI and had the same issue as well.

**Comment by lesaff** [comment]
Update: Tested on both Firefox (80.0.1) and Chrome (85.0.4183.102) on the same monitor and Chrome is the only one showing the scrolling issue. 

https://www.dropbox.com/s/n4fadi1ac52jz0r/craft-ff-chrome-comparison-scroll.mov?dl=0

**Comment by brandonkelly** [comment]
Does seem a bit like a graphics card issue from that video. Did you have a chance to test with your Mac mini?

**Comment by lesaff** [comment]
Finally got a chance to test on my Macmini (work got in the way) and I could not replicate. I will chalk it up as GD problem with my 2018 MBP 15". It's a problematic machine.

**Comment by brandonkelly** [comment]
I wonder if the background blur on the header is what’s causing it.

Try adding the following CSS via the [Control Panel CSS](https://plugins.craftcms.com/cp-css) plugin:

```css
body.fixed-header #header {
  backdrop-filter: none !important;
}
```

**Comment by lesaff** [comment]
It didn't do anything. Weirdly enough it's only on Chrome.

https://www.dropbox.com/s/59k7k2944nmutg5/craft-custom-css-scroll.mov?dl=0

**Comment by lesaff** [comment]
UPDATE: Turning off GPU acceleration seems to fix it.

![Screen Shot 2020-09-29 at 11 26 18 AM](https://user-images.githubusercontent.com/1151181/94571702-9ecaf700-0246-11eb-9fa4-f9fea57bb394.png)

**Comment by brandonkelly** [comment]
> Weirdly enough it's only on Chrome.

Yeah – you mentioned that, which is why I had suggested to disable the header blur, since that’s something that only happens in Chrome (FF doesn’t support it).

> Turning off GPU acceleration seems to fix it.

Ah cool, guessing that’s another thing FF doesn’t yet support. Glad you got it sorted!
