### ISSUE TITLE
Category field label in entries list displays additional categories count as a fraction vs whole number

### ISSUE THREAD

**Issue by andrewhawkes** [craftcms/cms#6869]
### Description

Very minor, but does look a little bit odd. 

As you can see if you have more than one category assigned to a category field, when it's displayed in the entries list the label says `+1.00` rather than `+1`

<img width="272" alt="Screenshot 2020-09-20 174347" src="https://user-images.githubusercontent.com/4975742/93716685-20e15e80-fb69-11ea-947d-5f908493a25b.png">

### Steps to reproduce

1. Enable display of categories field in admin list
2. Add more than one category to the field and see +1.00

### Additional info

- Craft version: 3.5.11.1

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.12 is out now with that fix.
