### ISSUE TITLE
ElementSelectorModal sidebar is incorrectly shown when the one selected source has a heading

### ISSUE THREAD

**Issue by gilleard** [craftcms/cms#6871]
### Description

When using an entries field with a single source, I expect the selection modal's sidebar to be hidden (it's redundant).

This is already the case prior to adding custom headings to the source list, but when added the "only show if more than once source" logic fails to account for headings:

https://github.com/craftcms/cms/blob/develop/src/controllers/ElementsController.php#L98

Pretty sure this isn't as expected, and I don't think the specified source having a heading adds enough context to warrant showing the sidebar.

### Steps to reproduce

1. Create a section
2. Customise the sources list with a heading prior to that section
3. Create an Entries field and only select the new section
4. Add the field to an entry type
5. Create an entry and open the fields element selector modal

### Additional info

- Craft version: 3.5.10

**Comment by brandonkelly** [comment]
Thanks for reporting that, and even looking into where the issue occurs :)

Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.12 is out now with that fix.
