### ISSUE TITLE
Plain text character limit indicator has disappeared

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#6872]
### Description
There used to be a small indicator in the bottom right of a plain text field that had a character limit. You could also keep typing over that limit, you just couldn't save it. Noticed today on 3.5.11.1 that the indicator has disappeared, and it's no longer possible to type past the limit. The hard limit is ok, but telling users WHY they can't type anymore is still important. Could we have it back please?

### Additional info

- Craft version: 3.5.11
- PHP version: 7.4.8
- Database driver & version: MySQL

**Comment by brandonkelly** [comment]
Thanks for reporting that! It was an unintended side effect of 4b411970c649988fb329197301f5346117080cd2. Fixed now for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.12 is out now with that fix.
