### ISSUE TITLE
Make EVENT_BEFORE_HANDLE_FILE cancelable

### ISSUE THREAD

**Issue by zizther** [craftcms/cms#6875]
### Description

The craft\elements\Asset::EVENT_BEFORE_HANDLE_FILE event extends the Cancelable event, however it is not actually cancelable.

Would it be possible to make the EVENT_BEFORE_HANDLE_FILE event cancelable?

**Comment by zizther** [comment]
@andris-sevcenko Just wondering if you had any indication when this issue maybe resolved?

**Comment by andris-sevcenko** [comment]
@zizther is there any particular reason why you don't want to use `craft\elements\Asset::EVENT_BEFORE_SAVE`?

The cancelable event there is used mainly to avoid code duplication and to re-use the class. If the event can really be canceled, it's noted in the event doc block itself.

**Comment by zizther** [comment]
In my use case we are moderating images, ideally I would like to use the EVENT_BEFORE_HANDLE_FILE event to as the asset is not handled by Craft at this point and moved on, so I can catch anything as early as possible, it remains in the temporary location and then periodically removed, rather than having inappropriate imagery being handled by Craft at the point of EVENT_BEFORE_SAVE.

**Comment by andris-sevcenko** [comment]
`craft\elements\Asset::EVENT_BEFORE_SAVE` fits your purposes in this scenario, though - it's fired before anything is saved - the only thing that happens between those events is some properties get assigned, but nothing gets saved anywhere, yet.

**Comment by andris-sevcenko** [comment]
Gonna go ahead and close this. I'll re-open if there is a case for it.
