### ISSUE TITLE
[FR] Make it easier/more intuitive to close element editor modals

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#6877]
### Description

Before Craft 3.4, element editor modals could be closed by hitting the ESC key, or by clicking outside the modal. Also, the scroll position was locked whenever an element editor modal was open.

In Craft 3.4+, the only way to close element editor modals is to click the "Cancel" button in the actual modal, and the page scroll is no longer locked.

This is especially annoying for authors who are used to be able to dismiss/close modals by clicking anywhere else on the page in previous Craft versions. It's also a problem that it's easy enough to scroll an open modal out of view – at which point the Control Panel is basically completely inaccessible and it's not at all clear to the user why they can't click anything.

To make matters worse, focus isn't set to the modal when it opens (and tabbing isn't restricted to the modal), so if the author is trying to close the modal using their keyboard, they typically need to tab through a large number of fields and buttons to find the "Cancel" button.

Some changes I think could help out with this would be to

1. Restore the ability to close modals by hitting the ESC key or clicking outside the modal. If the concern is losing content changes, perhaps some sort of confirm dialog could be introduced, if the user has edited the content inside the modal

2. Add a semi-transparent overlay between the modal and the CP, making it clearer to the user why they can't interact with the page when the modal is open (especially helpful if the modal itself is scrolled out of the viewport)

[I know that there are big changes coming](https://github.com/craftcms/cms/issues/6647) to the element editor modals in Craft 4, but since that is still at least 6 months out, it'd be great if the AX/accessibility of these modals could be somewhat improved in the meantime :)

**Comment by brandonkelly** [comment]
Good point. Just brought support for closing element editor HUDs by clicking out or pressing the <kbd>Esc</kbd> key; and if any content was changed, a confirmation dialog will be shown.

**Comment by mmikkel** [comment]
Wow, awesome. Thank you!

**Comment by brandonkelly** [comment]
Craft 3.5.12 is out now with that change ✨
