### ISSUE TITLE
DB backup fails after upgrade to 3.5.11.1 from 3.4..

### ISSUE THREAD

**Issue by mmc501** [craftcms/cms#6881]
### Description
I was able to take db backups via the Control Panel before the upgrade, but when I upgraded the backup no longer works.
I get the error message:

`2020-09-22 16:35:01 [-][1][644q7cadfhquvlff2adjb320oc][error][yii\base\Exception] yii\base\Exception: Could not create backup: The shell command "mysqldump --defaults-extra-file="C:\windows\TEMP\my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --default-character-set=utf8 --set-charset --triggers --no-tablespaces --single-transaction --no-data --result-file="C:\Users\path\craft\storage\backups/grant-manager--2020-09-22-153501--v3.5.11.1.sql" ccg-grants && mysqldump --defaults-extra-file="C:\windows\TEMP\my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --default-character-set=utf8 --set-charset --triggers --no-tablespaces --no-create-info --ignore-table=ccg-grants.craft_assetindexdata --ignore-table=ccg-grants.craft_assettransformindex --ignore-table=ccg-grants.craft_sessions --ignore-table=ccg-grants.craft_templatecaches --ignore-table=ccg-grants.craft_templatecachequeries --ignore-table=ccg-grants.craft_templatecacheelements --ignore-table=ccg-grants.craft_cache --ignore-table=ccg-grants.craft_templatecachecriteria ccg-grants >> "C:\Users\path\craft\storage\backups/grant-manager--2020-09-22-153501--v3.5.11.1.sql"" failed with exit code 1. in C:\Users\path\craft\vendor\craftcms\cms\src\controllers\UtilitiesController.php:345`

Local development on a Windows 10 machine.

**Comment by angrybrad** [comment]
What happens if you run this from the command line? (replace dbhost, dbuser, dbpassword with your actual database credentials):

```
mysqldump --host=dbhost --password=dbpassword --user=dbuser --result-file="craftbackup.sql" ccg-grants
```

**Comment by mmc501** [comment]
That backed up fine.

**Comment by angrybrad** [comment]
> The file does not exist in that location.

@mmc501 Craft will clean up that file after attempting to execute that command whether it succeeds or fails: https://github.com/craftcms/cms/blob/develop/src/db/Connection.php#L566

Maybe try commenting out this line as a test: https://github.com/craftcms/cms/blob/develop/src/db/Connection.php#L570

Reproduce the issue, then see if `C:\windows\TEMP\my.cnf` exists or not.

**Comment by mmc501** [comment]
Commented that out and checked the my.cnf file there is there.
Contents:

```
[client]
user=mysqluser
password="mysqlpassword"
host=localhost
port=3306
```

Which all look fine.

I tried this from the command line when the my.cnf file and it ran fine.
`mysqldump --defaults-extra-file="C:\windows\TEMP\my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --default-character-set=utf8 --set-charset --triggers --no-tablespaces --single-transaction --no-data --result-file="craftbackup5.sql" ccg-grants && mysqldump --defaults-extra-file="C:\windows\TEMP\my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --default-character-set=utf8 --set-charset --triggers --no-tablespaces --no-create-info --ignore-table=ccg-grants.craft_assetindexdata --ignore-table=ccg-grants.craft_assettransformindex --ignore-table=ccg-grants.craft_sessions --ignore-table=ccg-grants.craft_templatecaches --ignore-table=ccg-grants.craft_templatecachequeries --ignore-table=ccg-grants.craft_templatecacheelements --ignore-table=ccg-grants.craft_cache --ignore-table=ccg-grants.craft_templatecachecriteria ccg-grants >> "craftbackup5.sql"`

But still get the same error if I try to backup from the Control Panel

**Comment by mmc501** [comment]
Ah - may have sussed it - must have been a permissions issue on the C:\windows\TEMP\
Gave the IIS_IUSRS Groups full control of the folder and the backup has run fine from the Control Panel.
Thanks for your assistance.

**Comment by angrybrad** [comment]
Ahh, glad you're sorted. Odd that Craft/PHP was able to write the file to that folder, but when executing mysqldump from PHP, it could read from it.
