### ISSUE TITLE
Character count missing if line breaks is enabled on Plain text fields

### ISSUE THREAD

**Issue by terryupton** [craftcms/cms#6882]
### Description
Not sure if this is a bug, an oversight or intended behaviour. 
But I have noticed if you set a Field Limit (character count) and enable line breaks. Then the character count no longer shows up. 
<img width="1056" alt="Screenshot 2020-09-22 at 16 59 02" src="https://user-images.githubusercontent.com/5698596/93907783-b14caa00-fcf5-11ea-8cbb-87950b55d563.png">
<img width="1403" alt="Screenshot 2020-09-22 at 16 59 16" src="https://user-images.githubusercontent.com/5698596/93907788-b27dd700-fcf5-11ea-99fe-0419a3ef65f9.png">
<img width="1402" alt="Screenshot 2020-09-22 at 16 59 26" src="https://user-images.githubusercontent.com/5698596/93907792-b3166d80-fcf5-11ea-8b8a-19735d49142f.png">

### Steps to reproduce

1. Set a Field Limit (character count) on a plain text field.
2. Use the field on an entry and you will see the character count in the bottom corner.
3. Check the 'enable line breaks' setting on the field settings.
4.  Use the field on an entry and you will see the character count is no longer displayed.

**Comment by brandonkelly** [comment]
This was already reported by #6872, and fixed for the next release :)

**Comment by brandonkelly** [comment]
Craft 3.5.12 is out now with that fix.
