### ISSUE TITLE
Control Panel: A nonexistent column should not show a value in the entries list

### ISSUE THREAD

**Issue by andreimoment** [craftcms/cms#6891]
### Description
I have two entries listed in the same section. One of them has a "Publish Status" column, the other does not.

When listing both entries in CP, the entry type which lacks the column shows the default field value. 

This is confusing. The column does not exist on the entry. It should show blank value and not the default value. 

![Listed in the CP](https://user-images.githubusercontent.com/6190/93949291-561ab780-fcf5-11ea-9ad8-3ccd3d6a2eac.png)
![Site entry](https://user-images.githubusercontent.com/6190/93949293-56b34e00-fcf5-11ea-8835-e2471d1a779e.png)
![Page entry](https://user-images.githubusercontent.com/6190/93949296-574be480-fcf5-11ea-82cc-30e48904e75e.png)

### Steps to reproduce

1. Create a section Minisites
2. Create an entry type called Page
3. Create an entry type called Site
4. Create a dropdown field called Publish Status with two dropdown options: Active and Disabled.
5. Associate Publish Status with the Site entry type (but not with the Page entry type)
6. In the CP view, make the Publish Status visible in the entry list

### Additional info

- Craft version: 3.5.11
- PHP version: 7.3.22
- Database driver & version: MySQL 8
- Plugins & versions: none

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by andreimoment** [comment]
Thank you! Appreciate the opportunity to contribute to the improvement of CraftCMS.

**Comment by brandonkelly** [comment]
Craft 3.5.12 is out now with that fix.
