### ISSUE TITLE
Allow 'Use shapes to represent statuses' as an option for admin users to set for other others

### ISSUE THREAD

**Issue by terryupton** [craftcms/cms#6896]
### Description
The new setting 'Use shapes to represent statuses' is great and a lovely addition.
I have noticed however, this is only available as an option if the user is an 'admin'. 
It would be great if this could be extended to any user that has some level of control on the CMS. 
In fact the who preference panel is not available and I think some of those other settings could be equally valid to non-admin users who have some back-end CMS control/access. 

<img width="1130" alt="Screenshot 2020-09-24 at 13 52 00" src="https://user-images.githubusercontent.com/5698596/94147392-21ca0700-fe6d-11ea-8ab5-3652dee6c49f.png">
<img width="746" alt="Screenshot 2020-09-24 at 13 52 22" src="https://user-images.githubusercontent.com/5698596/94147444-2ee6f600-fe6d-11ea-878a-b101c242eb25.png">

**Comment by terryupton** [comment]
I have just realised that 'preferences' setting is only available to the current logged in user.
Having now logged in as this particular user I can see the additional tab.

So perhaps allowing these preferences to be controlled by 'admin' staff as well would be good. It would be ideal if these could be setup and added when I create a user account or group.

In my opinion the 'Use shapes to represent statuses' should be the default value anyway.

**Comment by brandonkelly** [comment]
@terryupton Just posted that suggestion as a new issue (#6905) and will close this one.
