### ISSUE TITLE
Checkbox options only outputting checked options

### ISSUE THREAD

**Issue by philipboomy** [craftcms/cms#6899]
### Description
I believe recent update (not sure which exactly) causes this:

```
{% for option in entry.myFieldHandle.options %}
    Checked: {{ option.selected ? 'Yes' : 'No' }}
{% endfor %}
```

to only output "Yes"

Before it would output "Yes" when checked and "No" for unchecked options. This causes my table to shift now. https://share.getcloudapp.com/NQu1kg0X

### Additional info
Craft CMS 3.5.11.1

**Comment by jakepm** [comment]
Also having this issue. Could use a workaround if possible.

**Comment by brandonkelly** [comment]
Thanks for reporting that. Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.12 is out now with that fix.

**Comment by jakepm** [comment]
Thanks for fixing so quickly @brandonkelly, much appreciated :)

**Comment by philipboomy** [comment]
Thank you for fixing so quick - We can never avoid bugs but how you handle them is important.... and you are handling them well
