### ISSUE TITLE
UrlHelper ignores/strips valueless parameters?

### ISSUE THREAD

**Issue by evanwarner** [craftcms/cms#6900]
I filed the following bug with Solspace and they responded that it's a Craft issue.

> It seems that an overridden [`returnUrl `](https://docs.solspace.com/craft/freeform/v1/template-functions/freeform.form.html#param-returnurl) property ignores/strips valueless query parameters. If I set the value (via a hidden field) to `{{ 'my/path/?thanks' | hash }}`, it shows correctly in the field, but the form only returns to `my/path/`. I have to give the parameter a value (e.g. `{{ 'my/path/?thanks=1' | hash }}`) in order for it to return to `my/path/?thanks=1`.
> 
> I can use a valueless parameter just fine if it is set within Craft on the form's **Return URL** field.

Their developer responded that it's an issue with `UrlHelper::url()` removing query params that have no value. A quick look at their source code only revealed use of `UrlHelper::cpUrl()`, but I wanted to lob this to you and see if the issue was an obvious fix in Craft.

### Additional info

- Craft version: 3.5.10
- PHP version: 7.4.2
- Database driver & version: MySQL 5.7.26
- Plugins & versions: Freeform 3.8.1

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.12 is out now with that fix.

**Comment by bencroker** [comment]
The fix in https://github.com/craftcms/cms/commit/7e2642cffef78fcd4f25a14daa797ce59c724da3 introduces a change that is breaking things in some plugins (https://github.com/putyourlightson/craft-campaign/pull/181). Previously when the value was a blank string, `?token=` was output instead of what is output since 3.5.12 which is`?token`.

Submitting a PR with a test now to fix this regression.

**Comment by bencroker** [comment]
FYI I applied a fix to the Campaign plugin in https://github.com/putyourlightson/craft-campaign/commit/b2c6e467ff37a5508ec71e14634cf6aae16cecfc as this introduced a rather nasty bug, so it is no longer affected by the issue.

**Comment by brandonkelly** [comment]
@bencroker Sorry about the unintended break. PHP will treat both `?lid=` and `?lid` the same though (as `$_GET['lid'] = ''`), so I’m confused on how the change would have broken anything?

**Comment by bencroker** [comment]
I was using `UrlHelper::siteUrl($path, ['lid' => '']);` to construct the base URL and appending a value with the assumption that the base URL ended in an `=`. As noted I've since changed this in the plugin which makes it less reliant on how the `url()` method works, thanks anyway for the response.

**Comment by brandonkelly** [comment]
Ahh, got it. Well sorry again for the unintended break.
