### ISSUE TITLE
Sort search results by multiple parameters

### ISSUE THREAD

**Issue by Saboteur777** [craftcms/cms#6901]
### Description

It would be beneficial if we could sort search results by additional parameters alongside their score. Right now you can do this: 

```
{% set entries = craft.entries.search('trolo').orderBy('score DESC') %}
```

OR this: 

```
{% set entries = craft.entries.search('trolo').orderBy('postDate DESC, customFieldHandle ASC') %}
```

But not this: 

```
{% set entries = craft.entries.search('trolo').orderBy('score DESC, postDate DESC') %}
```

**Comment by darylknight** [comment]
I don't understand. Aren't the second and third examples the same thing?

**Comment by Saboteur777** [comment]
@darylknight No, they are different queries: the first orders the results by their relevancy score, the second orders the results by their postDate and their custom field's value (in descending and ascending orders, respectively), and the third orders the results by their relevancy score and their postDate. 

They are effectively the same, but the third is not possible right now. (confirmed by @angrybrad )

**Comment by brandonkelly** [comment]
It wouldn’t be possible to mix them, as `score` is a special case, which is actually sorted by PHP code rather than by the DB.
