### ISSUE TITLE
User can delete its entry if he has not the "Publish live changes" permission

### ISSUE THREAD

**Issue by nflorentin** [craftcms/cms#6908]
Hi,

I'm not sure if it is a bug or a normal behaviour. 

I just found out that a user who has the permission "Delete entries" can't delete its own entry if he has not the "Publish live changes" permission checked. So he is not able to delete his own drafts.

Thanks!

### Additional info

Craft version: 3.5.10.1
PHP version: 7.4.9
Database driver & version: postgres 11.3

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed now for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.12 is out now with that fix.
