### ISSUE TITLE
Language character next to title

### ISSUE THREAD

**Issue by bymayo** [craftcms/cms#6910]
### Description

I'm getting a language character appear next to the title field (No other fields). The only language set is `en-GB` so there are no multi languages / sites.

![Screenshot 2020-09-28 at 09 53 03](https://user-images.githubusercontent.com/522877/94412359-9b197080-0171-11eb-93ab-811e1d5bce7b.png)

### Additional info

- Craft version: 3.5.10.1
- PHP version: 7.3
- Database driver & version: MySQL 5.7
- Plugins & versions:

**Comment by brandonkelly** [comment]
That was already reported by #6503, and we’ve fixed it for the next release :)

**Comment by bymayo** [comment]
@brandonkelly Whoops, sorry - I did check to see if an issue existed I promise! 🤭 Thanks!

**Comment by brandonkelly** [comment]
Craft 3.5.12 is out now with that fix.
