### ISSUE TITLE
[FR] Allow filtering of elements by other criteria in GraphQL queries

### ISSUE THREAD

**Issue by joshuabaker** [craftcms/cms#6911]
### Summary

We currently cannot filter elements by other criteria in GraphQL queries like we can in Twig.

### Example use case

A common use case is to return **all categories that are in use** (i.e. related to any entry). 

In Twig, we’d approach this using a subquery, like the following.

```twig
{% set allEntriesQuery = craft.entries.limit(null) %}

{% set usedCategoriesQuery = craft.categories.relatedTo(allEntriesQuery) %}
```

This is performant because we’re not actually getting the entries in the `allEntriesQuery` here, we’re just limiting the `usedCategoriesQuery` by the subquery. It’s also not limited, should we need to get all elements that are related to a set of elements, that are related to a set of elements, and so on.

In GraphQL, there’s currently no way of achieving this without actually getting _all_ of the entries first (potentially thousands) and then sending a subsequent request to get the categories (constrained by the `id` parameter).

### Proposal

I’ve spent some time thinking about how this could work in the context of Craft without having to implement reverse relations. 

If we allow full access to the criteria as an object (see below) and leverage [enumeration types](https://graphql.org/learn/schema/#enumeration-types) to define the different element types (`Category` and `Entry` below) it’d be possible to map to the existing element queries like Twig does, I believe.

```gql
{
  elements(
    criteria: {
      elementType: Category, 
      relatedTo: {
        criteria: {
          elementType: Entry, 
          limit: null
        }
      }
    }
  ) {
    ...categoryFragment
  }
}
```

This may not be the perfect schema, but I’d love to get your thoughts on how we could approach this.

**Comment by brandonkelly** [comment]
> This is performant because we’re not actually getting the entries in the `allEntriesQuery` here, we’re just limiting the `usedCategoriesQuery` by the subquery.

To clarify, when you pass an element query to `relatedTo`, it will execute the query’s `ids()` method internally – not include it as a subquery of the main query. So both of these lines are exactly the same, really:

```twig
{% set usedCategoriesQuery = craft.categories.relatedTo(allEntriesQuery) %}
{% set usedCategoriesQuery = craft.categories.relatedTo(allEntriesQuery.ids()) %}
```

So the only actual performance gain there could possibly be here would come from going from two HTTP requests down to one.

**Comment by brandonkelly** [comment]
We’ve made this possible for Craft 3.6. Going forward you will be able to do this:

```graphql
query {
  categories(relatedToEntries: {section: "mySection", ...}) {
    ...categoryFragment
  }
}
```

**Comment by joshuabaker** [comment]
Amazing! Thanks, @brandonkelly and @andris-sevcenko 🙏
