### ISSUE TITLE
View to look at empty roots key first

### ISSUE THREAD

**Issue by ryssbowh** [craftcms/cms#6917]
### Description

Related to this : https://github.com/craftcms/cms/commit/3938501a74742bc2ab22262403efebdf482fc63b

The template roots are sorted by longest first in the View class before finding templates, [there](https://github.com/craftcms/cms/blob/c8c4ae6fe954bd2fc0327d9f2022605091115a05/src/web/View.php#L1970)

in Craft 3.5 was added the possibility to add an empty root key, which is looked at last because of this sort. Wouldn't it make sense to move the empty root key at the beginning of the array so it's looked at first ?

It would give the possibility to override templates of plugins that define their own namespaces.

Thanks

**Comment by brandonkelly** [comment]
No, the current behavior is correct. The template root system is not meant to be a way of overriding core/plugin templates.
