### ISSUE TITLE
Please add a way to view the full location of an asset in an assets-field

### ISSUE THREAD

**Issue by bencresty** [craftcms/cms#6918]
### Description

I find myself wanting to know the full location of assets several times now from within the assets field of an entry, but there seems to be no way to see it from there.

When hovering over an image inside an asset field we only see a filename.
When doubleclicking on the asset we still only see the filename.

**Suggestion**
Show the full location on both the hover over an asset as well as a readonly label in the editform that appears when doubleclicking the asset.

**Comment by brandonkelly** [comment]
This could potentially be solved by #5857 – you’d be able to get the full URI of the asset from its edit page.

**Comment by bencresty** [comment]
@brandonkelly Not sure what you mean. #5857 talks about some plugin. But I'd rather don't install yet another plugin for such basic functionality as being able to check the url of an image or document.

Maybe we have a misunderstanding here. This is what I'm after, just to see the full Url of an asset from within the asset itself in an asset-field. Having to go to the Assets menu is not only way to cumbersome, but can't be done, as the whole thing in the first place is to be able to check if the image is in the right folder or just to see in which folder/location the asset is located, without the need to limit the folder.

The CP knows the Url already, so if just a readonly label could be added to view the url from the edit form like this, that would be fantastic to me:
![example](https://user-images.githubusercontent.com/69322733/94833372-5a3e8780-040f-11eb-8524-7b1107648c14.jpg)

**Comment by brandonkelly** [comment]
@bencresty We’re on the same page.

**Comment by brandonkelly** [comment]
This is resolved for 3.7! See #8017.
