### ISSUE TITLE
Remove wheelchair icon from the accessibility label on GitHub issues

### ISSUE THREAD

**Issue by philipboomy** [craftcms/cms#6919]
I had a client telling me this: _Not everyone who benefits from a11y is in a wheelchair and not everyone in wheelchair benefits from a11y_ which made me realise that I should mention this regarding the GitHub accessibility label here on Craft.

**Comment by brandonkelly** [comment]
Changed it to 👤 , which is the closest emoji I could find to the other popular Accessibility icon (<img src="https://user-images.githubusercontent.com/47792/94621316-ea8c9900-0264-11eb-8b68-8a8ed87dc9ef.png" width="24" alt="Standing human with arms stretched out">).
