### ISSUE TITLE
Minor style bug - account dropdown with scrollbar

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#6920]
### Description

On pages with a scrollbar, the account dropdown is too far over to the right

![image](https://user-images.githubusercontent.com/1250017/94553178-ca5adb00-0260-11eb-85bf-bac378a56a5c.png)

MacOS
Chrome
Mouse is plugged in

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.12 is out now with that fix.
