### ISSUE TITLE
Make the default sort order of Entry indexes configurable 

### ISSUE THREAD

**Issue by mellissageutskens-npo** [craftcms/cms#6924]
### Description
Is it possible to make the default sort order of Entry indexes configurable (e.g. in project config)? 

Currently the default sort order of Entries is by Post Date. When an Entry hasn't been posted (published) yet, the postDate  remains empty and the Entry ends up on the bottom of your Entry index. I've read that indexes will remember your last-selected setting, but manually changing the sort order for each user is not really convenient when you have 1000's of users.

**Comment by brandonkelly** [comment]
Post Date gets sorted in descending order by default. I just made it so in descending order, entries _without_ a Post Date get sorted at the top (and vise-versa).

**Comment by brandonkelly** [comment]
Craft 3.5.12 is out now with that change ✨
