### ISSUE TITLE
showCharsLeft on textarea removed in 3.5.6?

### ISSUE THREAD

**Issue by gglnx** [craftcms/cms#6929]
### Description

It's looks like that the refactoring of `forms.textarea` to include support for `inputAttributes` (this commit: https://github.com/craftcms/cms/commit/4b411970c649988fb329197301f5346117080cd2) removed the support for showing the characters left (`showCharsLeft`). Was this intended?

### Additional info

- Craft version: 3.5.6+

**Comment by gglnx** [comment]
It's a duplicate of #6872. Already fixed. Thanks!

**Comment by brandonkelly** [comment]
Craft 3.5.12 is out now with that fix.
