### ISSUE TITLE
[Question] Replacement for deprecated deleteCachesByKey() ?

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#6932]
### Description

We have a page section cached with `{% cache globally using key 'widgets' %}`

This contains some things  managed by a custom module, so when data changes we used to call 
`Craft::$app->getTemplateCaches()->deleteCachesByKey('widgets');` , which works fine (maybe by accident, that was just try and error).

This is now deprecated in 3.5, but no replacement is given. So what is the correct way to clear this type of cache, without invalidating everything else?

**Comment by brandonkelly** [comment]
I must have gone a little overboard by deprecating that method, since it is still the only way to delete caches by a specific key. Just un-deprecated it for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.12 is out now with that change.
