### ISSUE TITLE
Merging a property into _context recursively duplicates the entire _context

### ISSUE THREAD

**Issue by evanwarner** [craftcms/cms#6933]
While attempting to answer what initially seemed like a straightforward question on Discord, I ended up stumbling through a handful of wrong answers before finding a working solution that seems to reveal a bug. You can follow the whole rambling starting [here](https://discordapp.com/channels/456442477667418113/456442477667418115/760974738641256499) if you really want, but the punchline is that when calling `_context | merge()`, the entire `_context` object is duplicated as a child of itself, and the merged key is only found in the child.

### Steps to reproduce

```twig
{% set _context = _context | merge({
    'hello': 'world'
}) %}
{% dd _context | keys %}
```
This outputs an array where the last key is `'_context'`.
So then:

```twig
{% dd _context._context | keys %}
```
This outputs the _same_ array except that the last key is the merged `'hello'`.

### Additional info

- Craft version: 3.5.11.1
- PHP version: 7.4.2

**Comment by brandonkelly** [comment]
You’ll need to report this over at https://github.com/twigphp/Twig/issues, as Craft isn’t doing anything special with the `_context` (or `|merge` when not passing `recursive=true`).

Maybe try changing your `config.platform.php` value in `composer.json` to at least `7.1.3` and running `composer update` first, as that will give you Twig 2.13.1 (the latest version), whereas if it’s still set to `7.0` you’ll only be able to go up to 2.12.x. Then see if you can still reproduce.

**Comment by evanwarner** [comment]
Doh. 🤦‍♂️
Yep, should've filed this with Twig, sorry. Chalk that up to debugging at 1:30am.
