### ISSUE TITLE
Field content is not escaped

### ISSUE THREAD

**Issue by redzioch** [craftcms/cms#6935]
### Description

I have created plain text multiline field. It is rendered in HTML as textarea. When I include textarea closing in field content tag i.e. `<textarea></textarea>` and try to edit entry again, content including textarea closing tag is lost and also entry editing screen breaks.

Page source HTML looks like this - you can see that content is not escaped and breaks HTML:

```html
<div id="fields-body-field" class="field width-100" data-type="craft\fields\PlainText">
   <div class="heading"><label id="fields-body-label" for="fields-body">Body</label></div>
   <div class="input ltr">
      <textarea id="fields-body" class="nicetext code text fullwidth" name="fields[body]" rows="40" cols="50" placeholder="">
         <textarea></textarea>
      </textarea>
   </div>
</div>

```

Edit: disabling all the plugins didn't help.

### Steps to reproduce

1. Create plain text field with multi line option
2. Create new entry including newly created field, paste `<textarea></textarea>` as field content
3. Save entry
4. Edit it again

### Additional info

Application Info
PHP version	7.0.33
OS version	Linux 4.15.0-117-generic
Database driver & version	MySQL 5.7.31
Image driver & version	Imagick 3.4.0RC6 (ImageMagick 6.8.9-9)
Craft edition & version	Craft Solo 3.5.11.1
Yii version	2.0.38
Twig version	2.12.5
Guzzle version	6.5.5
Imagine version	1.2.3-dev

Plugins
CodeMirror	1.0.2
Contact Form	2.2.7
Contact Form Extensions	1.2.2
Contact Form Honeypot	1.0.2
Craft reCAPTCHA 3	1.0.16
Redirect Manager	1.1.1
Sprout Active	2.2.0
Sprout Email	4.4.7
Sprout Fields	3.8.3
Sprout Forms	3.12.2
Sprout SEO	4.6.3
Twig Perversion	2.1.0
Validateit	1.0.3
Wheel Form	2.5.1

Modules
sprout	barrelstrength\sproutbase\SproutBase
sprout-base-fields	barrelstrength\sproutbasefields\SproutBaseFields
sprout-base-redirects	barrelstrength\sproutbaseredirects\SproutBaseRedirects
sprout-base-sitemaps	barrelstrength\sproutbasesitemaps\SproutBaseSitemaps
sprout-base-uris	barrelstrength\sproutbaseuris\SproutBaseUris
sprout-base-email	barrelstrength\sproutbaseemail\SproutBaseEmail
sprout-base-reports	barrelstrength\sproutbasereports\SproutBaseReports
sprout-base-sent-email	barrelstrength\sproutbasesentemail\SproutBaseSentEmail

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.12 is out now with that fix.
