### ISSUE TITLE
User event after user is assigned perms and groups

### ISSUE THREAD

**Issue by mediabeastnz** [craftcms/cms#6937]
### Description

It would be great if there was an event in the Save/Edit Users controller that came after the user was assigned to groups and permissions.

Currently the only hook is `EVENT_AFTER_ACTIVATE_USER` but groups and permissions get attached after that.

#### Example

We're wanting to build a security feature that sends an email when a user is created with particular permissions.

**Comment by brandonkelly** [comment]
Just addressed this for the next release:

- The events that fire before/after assigning users to groups now includes `$newGroupIds` and `$removedGroupIds` properties, which are set to arrays of group IDs that are getting added/removed on the user.
- `craft\controllers\UsersController` now fires `EVENT_BEFORE_ASSIGN_GROUPS_AND_PERMISSIONS` and `EVENT_AFTER_ASSIGN_GROUPS_AND_PERMISSIONS` events before & after processing new user permissions and groups on the user getting saved.

So for example you could listen to `EVENT_BEFORE_ASSIGN_GROUPS_AND_PERMISSIONS`, make note of whether the current user has the permission you care about, and if not, listen to EVENT_AFTER_ASSIGN_GROUPS_AND_PERMISSIONS and see if they have it _now_.

**Comment by mediabeastnz** [comment]
Perfect! Thanks for the quick response  🙌

**Comment by brandonkelly** [comment]
Updated now: https://docs.craftcms.com/api/v3/craft-elements-user.html#event-before-authenticate

**Comment by brandonkelly** [comment]
Craft 3.5.13 is out now with those new events ✨
