### ISSUE TITLE
CP Trigger Path Returns 404

### ISSUE THREAD

**Issue by simeon-smith** [craftcms/cms#6938]
### Description
When using a custom cpTrigger path and having the CMS in headless mode the cpTrigger path returns a 404. It does not redirect to /login or /dashboard like it did previously.

### Steps to reproduce
1. Setup the CMS with a custom cpTrigger path.
2. Put the CMS in headless mode.
3. Go to the cpTrigger path.
4. It displays a JSON 404 response.

### Additional info
Craft version: 3.5.11.1
PHP version: 7.2
Database driver & version: MySQL 5.7

**Comment by brandonkelly** [comment]
Are you setting the `baseCpUrl` config setting?

**Comment by simeon-smith** [comment]
Yes, it's being set to the domain.

**Comment by brandonkelly** [comment]
And are you sure you’re accessing the control panel _exactly_ as specified by that setting? As of 3.5, if that setting is set, it’s the only way to get to the CP.

**Comment by simeon-smith** [comment]
So the cpTrigger is set to "edmo-admin" and the baseCpUrl is set to https://www.edmo.com/. I am accessing the admin panel through https://www.edmo.com/edmo-admin. This returns a 404. When I append /login it then provides me the login form, or if logged in if I append /dashboard. But it's not redirecting me to those urls like it used to do.

**Comment by brandonkelly** [comment]
I’m unfortunately not able to reproduce this. Any chance we can get SSH/FTP credentials so we can look into it on your server? If so please send to support@craftcms.com.

**Comment by simeon-smith** [comment]
I've sent over the access for the staging server which has the same issue.

**Comment by brandonkelly** [comment]
This ended up being due to CloudFront caching.

**Comment by ssmith-wombatweb** [comment]
For context the CloudFront config was set to not cache `/edmo-admin/*` when it should have been set to not cache `/edmo-admin*` so that /edmo-admin wasn't being cached.

Thank you Brandon.
