### ISSUE TITLE
[3.5.12] Can't open preview after uploading an asset via 'Upload a file' button

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#6940]
### Description

There is a JavaScript error when uploading a file via the new button and trying to click 'Preview'

![image](https://user-images.githubusercontent.com/60010597/94901818-83a2f600-0497-11eb-87f5-754954616cee.png)

### Steps to reproduce

1. Create a new entry
2. Upload a file using the 'Upload a file' button
3. Click preview

Edit: Same error with this sequence

1. Create a new entry
2. Click preview
3. Upload a file using the 'Upload a file' button => Preview is correct
4. Click 'Close preview' => Error

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 3.5.12.1 is out now with the fix for this.
