### ISSUE TITLE
Can't install Craft with existing project config, says No primary site exists

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#6943]
### Description

Can't install Craft with existing project config, says No primary site exists - while there is. This happens for me on multiple installations - with one and with multiple sites. But it also succeeds on some installations...

```bash
...
  | > add foreign key userpreferences_userId_fk: {{%userpreferences}} (userId) references {{%users}} (id) ... done (time: 0.002s)
  | > add foreign key users_id_fk: {{%users}} (id) references {{%elements}} (id) ... done (time: 0.004s)
  | > add foreign key users_photoId_fk: {{%users}} (photoId) references {{%assets}} (id) ... done (time: 0.002s)
  | > add foreign key volumefolders_parentId_fk: {{%volumefolders}} (parentId) references {{%volumefolders}} (id) ... done (time: 0.001s)
  | > add foreign key volumefolders_volumeId_fk: {{%volumefolders}} (volumeId) references {{%volumes}} (id) ... done (time: 0.002s)
  | > add foreign key volumes_fieldLayoutId_fk: {{%volumes}} (fieldLayoutId) references {{%fieldlayouts}} (id) ... done (time: 0.003s)
  | > add foreign key widgets_userId_fk: {{%widgets}} (userId) references {{%users}} (id) ... done (time: 0.004s)
  | > populating the info table ... done
  | > can't apply existing project config: No primary site exists
  | > renaming project.yaml to project-2020-10-01-225601.yaml and moving to config backup folder ... done
  | > saving default site data ... done
  | > saving the first user ... done
  | *** installed Craft successfully (time: 3.307s)
```

### Steps to reproduce

1. Create a multi site environment and save to project config
2. Try a fresh install with that project config

### Additional info

- Craft version: 3.5.10.1 to 3.5.12
- PHP version: 7.4.10
- Database driver & version: PostgreSQL
- Plugins & versions: -

**Comment by brandonkelly** [comment]
Not able to reproduce this on my end. Can you send your Composer and project config files over to support@craftcms.com so we can test with your setup?

**Comment by boboldehampsink** [comment]
@brandonkelly think I found it already - in `migrations/Install.php` on line 1063 you are calling `ProjectConfigHelper::ensureAllSitesProcessed()`. At this point `Craft::$app->projectConfig->getIsApplyingYamlChanges()` is always false, and thus no sites are processed (changed here: https://github.com/craftcms/cms/commit/6f6ba6241f6f6a67ad479f7a84a5659fb7c55581#diff-100ad843bc151c8d7358da24c6c30545)

**Comment by brandonkelly** [comment]
Alright, probably just fixed it. Can you update to `dev-develop` and see if that works for you?

**Comment by boboldehampsink** [comment]
@brandonkelly thanks, that fixed it :-)

**Comment by brandonkelly** [comment]
Craft 3.5.13 is out now with that fix.
