### ISSUE TITLE
Bug with new Time field: Argument 1 passed to craft\helpers\DateTimeHelper::_parseTime() must be of the type string, object given

### ISSUE THREAD

**Issue by benface** [craftcms/cms#6950]
# Steps to reproduce

1. Create a Time field with a "Translate for each site group" translation method and a 15-minute increment.
2. Add the field to an entry type.
3. Modify an entry of that type, and enter a time of "1:00 PM". Save the entry.
4. Boom:

> Argument 1 passed to craft\helpers\DateTimeHelper::_parseTime() must be of the type string, object given, called in /home/ubuntu/sites/my-site/vendor/craftcms/cms/src/helpers/DateTimeHelper.php on line 125

### Additional info

- Craft version: 3.5.12.1
- PHP version: 7.4.10
- Database driver & version: MySQL 5.7.31

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.13 is out now with that fix.
