### ISSUE TITLE
Add defined check for "limit" variable in elementSelect.html

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#6953]
### Description

I frequently use your `elementSelectField` but I don't always defined a `limit` setting for it (in case it's not needed).
Your latest changes don't check if the limit is set like before.

[Before ](https://github.com/craftcms/cms/blob/develop/src/templates/_includes/forms/elementSelect.html#L42)(first usage of "limit" var:
```twig
limit: limit ?? null,
``` 

[Now](https://github.com/craftcms/cms/blob/develop/src/templates/_includes/forms/elementSelect.html#L27)
```twig
<div class="flex{% if limit and elements|length >= limit %} hidden{% endif %}">
```

That will throw an exception in case it's not set. Could you please add it? 
```twig
{% set limit = limit ?? null %}
```

**Comment by brandonkelly** [comment]
Sorry about that. Fixed for the next release.

**Comment by Anubarak** [comment]
Awesome thank you.
Sorry for the trouble the last weeks 🙈

**Comment by brandonkelly** [comment]
Haha no worries at all.

**Comment by brandonkelly** [comment]
Craft 3.5.13 is out now with that fix.
