### ISSUE TITLE
FR: unique URLs for asset editor overlay

### ISSUE THREAD

**Issue by evanwarner** [craftcms/cms#6955]
I've started using custom field layout templates to show a transform's crop of an asset field, indicating to content editors that they may want to update the focal point. I can link this preview to the asset's `cpEditUrl` page, but there's no way to link directly to the asset editor overlay (as there's no unique URL for it).

#2331 talks about bringing the focal point editor to the image preview, and this request would handle it the other way: make the editor overlay deeplinkable. Either solution would resolve my immediate issue, but I also think a deeplink would help in other situations too.

**Comment by brandonkelly** [comment]
All it takes is a tiny bit of JavaScript to load up the Image Editor:

```js
new Craft.AssetImageEditor(assetId, {
  onSave: onSaveCallback
});
```

You can get an asset’s ID from its `data-id` attribute.
