### ISSUE TITLE
Joining two records with SoftDelete-trait may result in ambigious "where"-statement

### ISSUE THREAD

**Issue by FreekVR** [craftcms/cms#6957]
### Description
Joining two records both implementing the SoftDelete trait seems to cause ambigious where statements because the 'dateDeleted' column isn't prefixed with the table name.

### Steps to reproduce

1. Write a query in a module or plugin like the following:
```
$layoutId = 1;
$entryType = EntryType::findWithTrashed() // find() also doesn't work here
            ->joinWith('fieldLayout')
            ->where(['fieldlayouts.id' => $layoutId])
            ->all();
```
2. Results in an error:
```
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'dateDeleted' in where clause is ambiguous
The SQL being executed was: SELECT `entrytypes`.*
FROM `entrytypes`
LEFT JOIN `fieldlayouts` ON `entrytypes`.`fieldLayoutId` = `fieldlayouts`.`id`
WHERE (`fieldlayouts`.`id`=28) AND (`dateDeleted` IS NULL)
```

### Additional info

- Craft version: 3.5.11.1
- PHP version: 7.2
- Database driver & version: MySQL 5.7
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed this for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.13 is out now with that fix.
