### ISSUE TITLE
Trigger re-saving of Entries when Structure positions are changed

### ISSUE THREAD

**Issue by jrrdnx** [craftcms/cms#6959]
### Description

We are using Entry Types to determine which structure pages are used as listings, with the related section's settings using that Entry Type to determine the URI. For instance:

- Pages section (structure) used to determine the overall navigation
- News page within this section is using the "News Listing" entry type
- The News section (channel) is using the following Entry URI Format: `{{ craft.entries.type('newsListing').one().uri }}/{slug}`

![Screen Shot 2020-10-06 at 12 21 45](https://user-images.githubusercontent.com/4584671/95229679-d994d800-07ce-11eb-9f4f-c9f2cf872840.png)

This allows the News page to be reordered and nested/un-nested, but still allow the URI of each News entry to follow that page around. Unfortunately, when the News page itself is nested/un-nested, its own URI is updated but the News entries are not automatically re-saved so the URI is never updated. Each individual entry would need to be opened and saved in order to update this.

Is there another way I'm currently missing to "tie" a channel to a particular entry in this way so that the URIs are automatically updated?

**Comment by brandonkelly** [comment]
It’s not currently possible for Craft to understand the relationship between your News Listing entry’s URI and the News entries’ URIs. So you would need to write some code to trigger updating the News entries’ URIs.

You can do that by adding a [module](https://craftcms.com/docs/3.x/extend/module-guide.html) with this:

```php
use craft\elements\Entry;
use craft\events\ModelEvent;
use craft\helpers\Queue;
use craft\queue\jobs\UpdateElementSlugsAndUris;
use yii\base\Event;

// ...

public function init() 
{
    // ...

    Event::on(Entry::class, Entry::EVENT_AFTER_SAVE, function(ModelEvent $e){
        /** @var Entry $entry */
        $entry = $e->sender;

        // Was this the News Listing entry?
        if ($entry->getType()->handle === 'newsListing') {
            // Update all of the News entries’ URIs
            $newsEntryIds = Entry::find()->section('news')->ids();

            Queue::push(new UpdateElementSlugsAndUris([
                'elementId' => $newsEntryIds,
                'elementType' => Entry::class,
            ]));
        }
    });
}
```

**Comment by jrrdnx** [comment]
Thanks @brandonkelly !

Just thinking through this a bit more, we tend to have several of these (sometimes a dozen or more depending on the project size) so I'm trying to determine how to make this more dynamic for either a customizable plugin or a PR.

Is this too specific a use case to recommend a PR? I know I would need to add a dropdown field to the Entry Types edit template consisting of a list of sections, as well as a new DB table column to store selected values. Selected sections would have their slugs and URIs updated as you've shown.

-

**Comment by brandonkelly** [comment]
I think it would be more complicated than it’s worth right now. We are working on some related changes for Craft 4 that will help though.
