### ISSUE TITLE
Primary site with /en/ does not throw 404 if I go to the same page without /en/

### ISSUE THREAD

**Issue by SHoogland** [craftcms/cms#6961]
### Description

I have one craftcms installation with 2 configured sites:
- example.com/en/ (primary)
- example.com/nl/

If i create a single with the slug fissaen (en site) and fissanl (nl site)
I get the following result:

example.com/en/fissaen = 200
example.com/nl/fissanl = 200
example.com/fissaen = 200
example.com/fissanl = 404 

In my (our, including my colleagues) opinion, example.com/fissaen should also be a 404 as this is not a configured siteurl

Is this a bug? Or is there a very good reason this works the way it does?

In the latter case, we are very curious for the explanation.

### Steps to reproduce

1. setup craft with 2 sites as described above
2. go to the urls as described above

### Additional info

- Craft version: 3.5.12.1
- PHP version: 7.2.32
- Database driver & version: MySQL 5.5.5
- Plugins & versions: none

**Comment by brandonkelly** [comment]
This is expected because Craft will always fall back to the primary site, if it is unable to determine which site was actually requested.

You can force a 404 error by adding some code like this to your main layout template:

```twig
{% if currentSite.handle == 'primarySiteHandle' and not (craft.app.request.url matches '/^\\/en[\\/$]/') %}
    {% exit 404 %}
{% endif %}
```
