### ISSUE TITLE
Rename "share" button to "view" or similar

### ISSUE THREAD

**Issue by JayBox325** [craftcms/cms#6963]
### Description
I have had a few clients that have struggled to find the button that lets them view their entry on the site. Once they know it is this button, it's fine.

I think the "share" terminology is wrong for the function of this button as it is effectively 'view on the site' not making it super clear.

**Comment by brandonkelly** [comment]
I’ve seen a couple mentions of confusion over the “Share” label before as well, and agree that “View” is better. Went ahead and renamed it for the next release.

**Comment by JayBox325** [comment]
Legend, @brandonkelly. Taking some time off soon? 😂

**Comment by brandonkelly** [comment]
Craft 3.5.13 is out now with this change ✨

**Comment by stuntbox** [comment]
Only just noticed this issue, but omg _thank you_! The text label on this button has been a common source of anxiety + confusion for our internal users. Many of them thought it meant they were going to publish a draft before it was supposed to go live.
