### ISSUE TITLE
"Share" button not appearing on section entries

### ISSUE THREAD

**Issue by JayBox325** [craftcms/cms#6964]
### Description
I have a section for my core site structure and the super helpful "share" button isn't appearing at any stage.

### Steps to reproduce
1. Make a structure
2. Add an entry to this structure & Save it
3. Try to view the entry in the front end with the "share" button

### Additional info

- Craft version: 3.5.12.1
- PHP version: 7.4.10
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
Make sure that your section has at least one Preview Target defined in its settings.

**Comment by JayBox325** [comment]
Ah, thanks. Sorry!
