### ISSUE TITLE
Internal server error on Entries field in multisite

### ISSUE THREAD

**Issue by NixonGit** [craftcms/cms#6968]
### Description

We are getting an internal server error when trying to select an entry via the Entries HUD on a multisite install. Setup is as follows:

- Single enabled in site A
- Channel (C1) enabled on site B and C
- Entries field assigned to site A selecting entries from C1

Will send project config over to support@craftcms.com

### Steps to reproduce

1. Setup as per project config.
2. Create an entry in site B in C1.
3. Switch to the single and try to assign the created entry via entries field.

### Additional info

- Craft version: Craft Pro 3.5.12.1
- PHP version: 7.4.9
- Database driver & version: MySQL 5.7.31

**Comment by brandonkelly** [comment]
Someone else wrote into support reporting the same issue yesterday, coincidentally, and I’ve fixed it for the next release (68b275c7170288428671dffa2996119d90177cf3 + 68b275c7170288428671dffa2996119d90177cf3).

Would be awesome if you could test on your end and verify that it’s fixed for you, though. To do that, change your `craftcms/cms` requirement in `composer.json` to `"dev-develop"`, and then run `composer update`.

**Comment by angrybrad** [comment]
Confirmed that this is fixed in the upcoming release with these fixes.

**Comment by brandonkelly** [comment]
Craft 3.5.13 is out now with that fix.
