### ISSUE TITLE
Translatable matrixfield not displed as translatable on fields index

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/cms#6970]
### Description

When setting the propagation method to "Only save blocks to the site they were created in" it doesn't show the matrix field as translatable in the fields index. It does however show the translatable icon on the element edit page.

### Additional info

- Craft version: 3.5.12.1
- PHP version: 7.3.22
- Database driver & version: MySQL 5.7
- Plugins & versions: -

**Comment by brandonkelly** [comment]
Thanks for reporting that! This has been fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.13 is out now with that fix.
