### ISSUE TITLE
svg() Twig function does not namespaces markup by default

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#6971]
[documentation](https://craftcms.com/docs/3.x/dev/functions.html#svg_ os `svg()` mentions that:

> By default, if you pass an asset or raw markup into the function, the SVG will be sanitized of potentially malicious scripts using svg-sanitizer, and any IDs or class names within the document will be namespaced so they don’t conflict with other IDs or class names in the DOM. 

Hovewer, i needed to pass additional argument to make SVH markup namespaced, it does not work by default:

```
svg('file.svg', namespace=true)
```

Didnt tested sanitizing though.

**Comment by brandonkelly** [comment]
Passing a file path is not the same thing as passing an asset or raw markup.

Asset example:

```twig
{{ svg(entry.myAssetsField.one()) }}
```

Raw markup example:

```twig
{{ svg('<svg>....</svg>') }}
```
