### ISSUE TITLE
Hyphenated custom elements break when using "Html::modifyTagAttributes" compared to Twigs "attr" filter

### ISSUE THREAD

**Issue by marknotton** [craftcms/cms#6973]
### Description

Hyphenated custom element tags behave differently (break) when using "Html::modifyTagAttributes" via PHP compared to Twigs "attr" filter.

### Steps to reproduce

Writing the following Twig markup with [Crafts "attr" filter](https://craftcms.com/docs/3.x/dev/filters.html#attr)

```twig
<custom-element{{ attr({class:'foo'})}}></custom-element>
```

...will renders this: 

```html
✅ <custom-element class="foo"></custom-element>
````

Where-as writing this in PHP with [Crafts modifyTagAttributes static method](https://docs.craftcms.com/api/v3/craft-helpers-html.html#method-modifytagattributes)

```php
Html::modifyTagAttributes('<custom-element>', ['class'=>'foo']).'</custom-element>';
```

...will renders this: 

```html
❌ <custom class="foo" -element=""></custom>
```

It doesn't seem the handle the hyphen correctly, which is odd because is seems that the [Twig filter](https://docs.craftcms.com/api/v3/craft-web-twig-extension.html#public-methods) is using the same `Html::modifyTagAttributes` method [behind the scenes](https://github.com/craftcms/cms/blob/master/src/web/twig/Extension.php#L706-L714). 

I'm unable to find any related issues or restrictions further up the chain. [Yii's renderTagAttributes](https://www.yiiframework.com/doc/api/2.0/yii-helpers-basehtml#renderTagAttributes()-detail) doesn't mention anything about special behaviours when using hyphenated custom elements.

### Intermediary solution

```php
  private static function modifyTagAttributes($tag, $attributes, $content = '') {
    
    $_tag = str_replace('-', '_', $tag);

    $html = Html::modifyTagAttributes('<'.$_tag.'>', $attributes);
    $html = str_replace($_tag, $tag, $html);
    $html .= (string)$content;
    $html .= '</'.$tag.'>';

    return Template::raw($html);

  }
```
As-per my original example:
```php
echo static::modifyTagAttributes('custom-element', ['class' => 'foo']);
```
```html
🎉 <custom-element class="foo"></custom-element
```
### Additional info

- Craft version: 3.5.11.1
- PHP version: 7.3.1

**Comment by brandonkelly** [comment]
Thanks for reporting that, just fixed for the next release.

> It doesn't seem the handle the hyphen correctly, which is odd because is seems that the [Twig filter](https://docs.craftcms.com/api/v3/craft-web-twig-extension.html#public-methods) is using the same `Html::modifyTagAttributes` method [behind the scenes](https://github.com/craftcms/cms/blob/master/src/web/twig/Extension.php#L706-L714).

To clarify, your template code is calling the [`attr()` _function_](https://craftcms.com/docs/3.x/dev/functions.html#attr) (which calls [renderTagAttributes()](https://www.yiiframework.com/doc/api/2.0/yii-helpers-basehtml#renderTagAttributes()-detail) and is used to generate a string of standalone HTML attributes); not the [`|attr` _filter_](https://craftcms.com/docs/3.x/dev/filters.html#attr) (which calls [modifyTagAttributes()](https://docs.craftcms.com/api/v3/craft-helpers-html.html#method-modifytagattributes) and is used to _modify_ the HTML attributes on a passed-in HTML element). You would be able to reproduce the same bug in Twig if you did this instead:

```twig
{{ '<custom-element></custom-element>'|attr({class:'foo'}) }}
```

**Comment by marknotton** [comment]
Thank you @brandonkelly. Not just for a quick response, but also for the detailed explanation.... that makes a big difference.

**Comment by brandonkelly** [comment]
Craft 3.5.13 is out now with that fix.
