### ISSUE TITLE
Order of category children no longer respected by default

### ISSUE THREAD

**Issue by weotch** [craftcms/cms#6974]
### Description

I have a 2 level Category called Product Filters:

![image](https://user-images.githubusercontent.com/77567/95476994-bbe58100-093c-11eb-8600-81815389276a.png)

Until we recently updated to `3.5.12.1`, the following GraphQL query would return these categories in the order shown in the CMS:

```gql
query getProductFilters {
	entries: categories(group: "productFilters", level: 1) {
		title
		slug
		options: children {
			title
			slug
			shopifyTag
		}
	}
}
```

However, after updating to `3.5.12.1`, (we had been on `3.5.6`), the children were returned in alphabetical order.  I've found I can fix this by changing my query to:

```gql
query getProductFilters {
	entries: categories(group: "productFilters", level: 1) {
		title
		slug
		options: children(orderBy: "lft") {
			title
			slug
			shopifyTag
		}
	}
}
```

I'm _guessing_ this wasn't an expected change.  Maybe it was introduced in #6924 which had to do with order? 

### Steps to reproduce

1. Create a multiple level category
2. Make a graphql query like mine from the description.

### Additional info

- Craft version: 3.5.12.1
- PHP version: 7.4.3
- Database driver & version: MySQL 8.0.20
- Plugins & versions:

![image](https://user-images.githubusercontent.com/77567/95477808-973dd900-093d-11eb-9969-f8eb6996b50c.png)

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by weotch** [comment]
🍻

**Comment by brandonkelly** [comment]
Craft 3.5.13 is out now with that fix.
