### ISSUE TITLE
Image "Upload a file" breaks out of image editor tooltip

### ISSUE THREAD

**Issue by knynkwl** [craftcms/cms#6975]
We have a client that needs an image over an image,  we add this to the assets fieldset.

![Screen Shot 2020-10-08 at 11 39 47 AM](https://user-images.githubusercontent.com/4225771/95481650-37562b00-095b-11eb-9c6b-6152e8ea6742.png)

**Comment by knynkwl** [comment]
I changed the asset name, and it fixed itself

![Screen Shot 2020-10-08 at 11 47 54 AM](https://user-images.githubusercontent.com/4225771/95482464-235ef900-095c-11eb-972a-d9a78e752ee7.png)

**Comment by brandonkelly** [comment]
Just made a change for the next release, which should prevent this from happening in the future.

**Comment by brandonkelly** [comment]
Craft 3.5.13 is out now with that fix.
