### ISSUE TITLE
[FR] debugAllRequests config option for debug toolbar

### ISSUE THREAD

**Issue by OscarBarrett** [craftcms/cms#6978]
### Description

For the majority of our sites we use Craft in headless mode and have a node server hit the GraphQL API to perform server-side rendering. Because it's not a logged in user hitting GraphQL, the requests do not get logged to the debug toolbar.

It would be great to have a `debugAllRequests` config option that could skip the user checks in `debugBootstrap`:
https://github.com/craftcms/cms/blob/3de94fd5de3986116f571e50e003eff6f3b50946/src/web/Application.php#L400
https://github.com/craftcms/cms/blob/3de94fd5de3986116f571e50e003eff6f3b50946/src/web/Application.php#L405

**Comment by brandonkelly** [comment]
A lot of sensitive info could be leaked if we made it possible to enable the Debug extension on production, so I don’t feel comfortable making a config setting for this.

Instead I have added support for passing a new `X-Debug: enable` header, which will only be checked if Dev Mode is enabled.

**Comment by OscarBarrett** [comment]
Perfect, thanks!

**Comment by brandonkelly** [comment]
Craft 3.5.13 is out now with that change ✨
