### ISSUE TITLE
Running `php craft off` removes changes made to project config before they are applied

### ISSUE THREAD

**Issue by lassemt** [craftcms/cms#6984]
### Description
After updating to 3.5.12 project config changes are not applied as config (.yaml) files are being removed if running `php craft off` before `php craft project-config/apply`

### Steps to reproduce

1. Update to 3.5.12.
2. Create a new section single and see `config/project/section/` directory get new config file for section. 
3. Sync files to a production environment, make sure the new single .yaml file is among the synced files.
4. Run `php craft off` and see the new file disappear.

### Additional info
Downgrading to 3.5.11.1 fixes the problem. Creating a new single section in 3.5.11.1 and running `php craft off` before `php craft project-config/apply` for applying changes in the same production environment works as expected.

- Craft version: 3.5.12.0 and 3.5.12.1
- PHP version: 7.4.10
- Database driver & version: MySQL 8.0.21
- Plugins & versions: Minify:1.2.10 & Twigpack:1.2.6

**Comment by lassemt** [comment]
Reverting changes made in 502dde852e361ebc69a81cb75a4a1c9df115dc1d solves this, but reopens previous issue #6913 then.

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.13 is out now with that fix.

**Comment by lassemt** [comment]
> Craft 3.5.13 is out now with that fix.

Just tested, deployment is running silky smooth again. Thanks ✨
