### ISSUE TITLE
Template not found when an entry is 'pending'

### ISSUE THREAD

**Issue by noregt** [craftcms/cms#6990]
### Description
If I setup a channel with a entry I can view it in the template as long as the start date is not in the future. As soon as it becomes a 'pending' entry  I'm getting a 404 template not found.

### Steps to reproduce

1. Create an entry in a channel with a future start date
2. Try to view it in the template

Tested on a new Craft installation

### Additional info

- Craft version: 3.5.12.1
- PHP version: 7.2.33
- Database driver & version: mysqlnd 5.0.12
- Plugins & versions:

**Comment by brandonkelly** [comment]
That is expected behavior – the entry is not live until its Post Date has been reached.
