### ISSUE TITLE
Required fields can be submitted while empty - only works on existing entries

### ISSUE THREAD

**Issue by jan-dh** [craftcms/cms#6994]
### Description
I have some required fields that can be left empty and submitted. Asset fields, plain text fields, redactor fields,...
When creating a new entry the fields get validated and I can't create the entry. When updating an existing entry, I can leave those fields blank or create new blank fields (inside a matrix block) without any problem.

### Additional info

- Craft version: 3.4.30
- PHP version: 7.3.23
- Database driver & version: mysql 5.7

**Comment by brandonkelly** [comment]
Required fields are only enforced for enabled entries. Are you seeing this behavior on enabled entries?
