### ISSUE TITLE
Blocked migrations due to project config updates

### ISSUE THREAD

**Issue by johnnynotsolucky** [craftcms/cms#6995]
The project config updates in migration `m200620_230205_field_layout_changes` can block migrations on servers running in read-only mode:

https://github.com/craftcms/cms/blob/43ef5dad83a03a940cd28998c068389c0b33b014/src/migrations/m200620_230205_field_layout_changes.php#L36

The workaround was to temporarily turn off read-only for the site so that the migrations could run through.

The workflow is something like

```bash
...
./craft migrate/all
./craft project-config/apply
...
```

### Additional info

- Craft version: Upgrading from 3.4.23 to 3.5.12.1
- PHP version: 7.3
- Database driver & version: MySQL
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
I’m not able to reproduce that. Can you send in Composer files and a database backup for a project where you saw this happen? support@craftcms.com

**Comment by johnnynotsolucky** [comment]
@brandonkelly I'm unable to reproduce this either. I restored a backup locally and ran the migrations in read-only mode without a problem.

The error we had originally was "Changes to the project config are not possible while in read-only mode." and the stack trace pointed to this migration.

**Comment by brandonkelly** [comment]
Huh, weird. Maybe due to a plugin that was updated after you first ran the migration.
