### ISSUE TITLE
[FR] Change PruneRevisions queue job so maxRevisions is a parameter

### ISSUE THREAD

**Issue by rob-baker-ar** [craftcms/cms#6999]
The `craft\queue\jobs\PruneRevisions` class checks for `Craft::$app->getConfig()->getGeneral()->maxRevisions` in it's `execute()` method. It is also checked in the `createRevision()` method of `craft\services\Revisions` before the job is added to the queue.

It would be great if the Job did not get the `maxRevisions` value from Craft config directly and used a class property instead which of course could be injected in `craft\services\Revisions::createRevision()`. This property could be optional - if not set it defaults to `Craft::$app->getConfig()->getGeneral()->maxRevisions`.

This would allow people to Switch off automatic revision pruning (by setting maxRevisions in config to 0) but also allow them to trigger revision pruning from module code, or in fact anywhere else in a PHP context (which currently does not work because of this code in `craft\services\Revisions::createRevision()`:

```php
    // Make sure maxRevisions is still set
    $generalConfig = Craft::$app->getConfig()->getGeneral();
    if (!$generalConfig->maxRevisions) {
        return;
    }
```

**Comment by brandonkelly** [comment]
Just added that `craft\queue\jobs\PruneRevisions::$maxRevisions` property for the next release.

I’m not following you on the `createRevision()` change though; if your `maxRevisions` config setting is `0`, the job won’t get added by `createRevision()`, leaving it up to you to queue up that job yourself via a module, which seems like the behavior you want.

**Comment by rob-baker-ar** [comment]
>  if your maxRevisions config setting is 0, the job won’t get added by createRevision(), leaving it up to you to queue up that job yourself via a module, which seems like the behavior you want.

Yes, that's the behaviour I'm after but the chunk of code quoted above in the job's `execute()` method will make the job return without doing it's work, because I have maxRevisions in config set to zero (preventing the job from being queued in the first place but also preventing it doing it's work when it is queued by another mechanism i.e. from a module).

Thanks for looking at this - should help our site along quite a bit.

_P.S. The reason I raised this at all in the first place is I am getting a large number of SQL lock timeouts when running FeedMe feeds that import into structures - I am ending up with hundreds of failed prune revisions jobs when the feed completes - it seem they are locking each other out (as well as the feed at times) from modifying the structure table - I think they all end up waiting on each other until one fails and the rest can move on._

_I am talking about a feed that imports ~450 entries into a structure section. Because I cannot nail down the exact conditions under which it happens, I have not raised a bug for that yet. If I run the feed with a single queue runner process it works but the whole things takes a  lot longer to complete. If I disable prune revisions job the feed can run with 4 concurrent queue runner processes without any failures._

**Comment by brandonkelly** [comment]
Craft 3.5.13 is out now with that new `$maxRevisions` property ✨
