### ISSUE TITLE
Access entry edtior by uid?

### ISSUE THREAD

**Issue by ryanpcmcquen** [craftcms/cms#7000]
### Description

We would love to have a way to access an entry's edit page via its uid. This would allow us to tie our front end back to the relevant entry edit screen with something like a browser extension. Is this currently possible, or would there be a way to add this functionality?

This:
```
https://craft.foobar.com/admin/entries/foo/{element_id}
```

Would be made available as:
```
https://craft.foobar.com/admin/entries/{uid}
```

**Comment by brandonkelly** [comment]
Great idea, and very worthy of issue #7000 :)

Just added this for **all** element types, via the URI pattern `/admin/edit/X`, where `X` can be either an element’s ID or UID, provided that the logged-in user has permission to edit the element.

An optional `site` query string param can also be supplied, set to the handle of the site you wish to edit the element in. If not set, a site will be chosen based on the sites the element is saved in, and the sites the user is allowed to edit.

**Comment by ryanpcmcquen** [comment]
Thank you @brandonkelly!

**Comment by brandonkelly** [comment]
Craft 3.5.13 is out now with that new controller action ✨

**Comment by ryanpcmcquen** [comment]
Awesome times 7000!
