### ISSUE TITLE
Preventing authentication via AuthenticateUserEvent::performAuthentication not possible

### ISSUE THREAD

**Issue by fThues** [craftcms/cms#7005]
### Description

I'm hooking into `User::EVENT_BEFORE_AUTHENTICATE` in order to perform my own, additional authorization checks. The [docs](https://docs.craftcms.com/api/v3/craft-elements-user.html#events) say:

> You may set craft\events\AuthenticateUserEvent::$performAuthentication to false to prevent the user from getting authenticated

Setting `performAuthentication` to `false` has no effect though. 

I believe this is due to `$this->authError` never being set to any value in the [authenticate() function](https://github.com/craftcms/cms/blob/e7dae3d838344e913f80b33020e5354d278bc233/src/elements/User.php#L837) when `$event->performAuthentication`is true, since most of the function is [skipped](https://github.com/craftcms/cms/blob/e7dae3d838344e913f80b33020e5354d278bc233/src/elements/User.php#L845) in that case.

Since `$this->authError` is equal to null (has never been touched), the function always returns `true` and authorization continues as normal.

### Steps to reproduce

1. Hook into `User::EVENT_BEFORE_AUTHENTICATE`
2. Set `$event->performAuthentication` to `false`
3. Authorization continues anyway

### Additional info

- Craft version: Craft Pro 3.5.12.1
- PHP version: 7.4.11
- Database driver & version: MySQL 5.5.5
- Plugins & versions: n/a

**Comment by fThues** [comment]
Nevermind, turns out I totally misunderstood the purpose of `performAuthentication`: When it's set to `false`, the authentication process is skipped completely (meaning the user will _always_ be authenticated).

**Comment by fThues** [comment]
Amazing, thanks! I believe this also resolves #6501.

**Comment by brandonkelly** [comment]
Ah, yep, thanks for pointing that out!

**Comment by brandonkelly** [comment]
Updated now: https://docs.craftcms.com/api/v3/craft-elements-user.html#event-before-authenticate
