### ISSUE TITLE
`invalidUserTokenPath` not used if user is logged in when they use an invalid token link

### ISSUE THREAD

**Issue by GaryReckard** [craftcms/cms#7006]
I wanted to set up a page that a user would be directed to if they use an invalid or expired link in their email. I set `'invalidUserTokenPath' => 'link-expired',` in my general.php config file. However, the user only gets directed to this custom template if they are not logged in, due to the second conditional here:

https://github.com/craftcms/cms/blob/e7dae3d838344e913f80b33020e5354d278bc233/src/controllers/UsersController.php#L1985-L2010

I am currently building a feature allowing a user to change their email address, which requires email verification. They are logged in already. If they do this once and go check their email and click the link, all is good. But if they happened to do this more than once, only the most recent email verification will be valid. They could check their email, and click on the older of the emails, click the link, and then they would just be routed to the post-login url set by the config var `postLoginRedirect`. 

Not sure what the best solution is here, as I'm not sure why it was decided to redirect them to the `postLoginRedirect` if they are already logged in. If they got redirected to the `invalidUserTokenPath` regardless of if they were logged in or not, I could handle it appropriately in that template.

**Comment by brandonkelly** [comment]
The current behavior is there for users who use their verification links as shortcuts to access the control panel. I have just changed the behavior slightly, so users will only be redirected if they are already logged in **and** they don’t have an existing verification code on their account. (Verification codes go away once they have been successfully used, or expired.)

**Comment by brandonkelly** [comment]
Craft 3.5.14 is out now with that change ✨

**Comment by GaryReckard** [comment]
Thanks, Brandon. Great soluuuush
