### ISSUE TITLE
Minor style issue with checkboxes fields

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#7011]
### Description

Space between field title and the checkbox inputs is larger than it used to be.

<img width="512" alt="Bildschirmfoto 2020-10-15 um 14 34 41" src="https://user-images.githubusercontent.com/7516543/96127679-c384c700-0ef4-11eb-900f-7cd3f8aefb8d.png">

### Additional info

- Craft version: 3.5.12.1

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just released Craft 3.5.13 with a fix.
