### ISSUE TITLE
[3.5.13.1] After upgrading to 3.5.13.1 (from 3.5.12.1) entries dissapear after saving an entry

### ISSUE THREAD

**Issue by bencresty** [craftcms/cms#7017]
### Description

As title + this error message is shown in the console:
![image](https://user-images.githubusercontent.com/69322733/96226024-4740c100-0f92-11eb-863e-e170f89180d7.png)

This was no issue before in version 3.5.12.1.

![image](https://user-images.githubusercontent.com/69322733/96226073-60e20880-0f92-11eb-9960-e8c75d55ee17.png)

### Steps to reproduce

1. Save an entry
2. Look at the entries lists. None are shown. Refreshing the page doesn't help either. 

**The only thing to show entries again is to clear all browser cache and re-login!!**

**Please test better before releasing a new version! This is another error that could have been prevented doing some real life testing and errors like 'Cannot read property Children of null' mostly indicates to me there is a lack of defensive programming.**

### Additional info

It's a multi-site project

- Craft version: 3.5.13.1
- PHP version: 7.4.9
- Database driver & version: MySQL 5.5.5

**Comment by baumberger** [comment]
Same issue for my install. Also multi-site setup.

**Comment by brandonkelly** [comment]
Glad that fixed it for you!

**Comment by brandonkelly** [comment]
Thanks for reporting! Craft 3.5.13.2 is out now with a fix for this.

**Comment by baumberger** [comment]
Thank you.

**Comment by bencresty** [comment]
Thanks. Just upgraded and it's working now
