### ISSUE TITLE
BaseElementIndex tries to set a site before the rest of the variables are declared

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#7018]
### Description
I have a multisite setup and after the last update whenever I refresh the page with the siteId cookie value set, I receive a JS error because the BaseElementIndex is not fully set-up/initialized, but the cookie tries to set the site. 

You already [trigger ](https://github.com/craftcms/cms/blob/develop/src/web/assets/cp/src/js/BaseElementIndex.js#L186) `$storedSiteOption.trigger('click');` before the rest of the variables (eg `this.$sortMenuBtn` [here](https://github.com/craftcms/cms/blob/develop/src/web/assets/cp/src/js/BaseElementIndex.js#L253)) is declared. Thus in your `selectSource` function `this.$sortAttributesList` is still null since there is no menu yet.

Could you please fix that? A "Hotfix" was to remember the site and trigger the click event right at the end of initialization.

### Steps to reproduce

1. Update to Craft 3.5.13.1
2. Change the site and notice the events are triggert in the wrong order

### Additional info

- Craft version: Craft 3.5.13.1

**Comment by brandonkelly** [comment]
Thanks for reporting! It was also reported by #7017, and I’ve just released 3.5.13.2 with a fix.

**Comment by Anubarak** [comment]
Ah sorry, I saw the other topic but I thought that was not related to this one, since the entries didn't "disappear"
