### ISSUE TITLE
purgeUnsavedDraftsDuration not mixed type

### ISSUE THREAD

**Issue by chrisrowe** [craftcms/cms#7019]
https://github.com/craftcms/cms/blob/8d2974a378154fae7f35e569d683fbe3c2865dd7/src/services/Drafts.php#L478

Appears to be only accepting int of seconds instead of mixed as per docs https://craftcms.com/docs/3.x/config/config-settings.html#purgeunsaveddraftsduration

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just released 3.5.13.2 with a fix.
