### ISSUE TITLE
No entries after Update from 3.5.12.1 to 3.5.13.1 

### ISSUE THREAD

**Issue by pette87** [craftcms/cms#7020]
### Description
After update in development system via backend, now in entries section I become a console error:

Craft.min.js?v=1602844434:1 Uncaught TypeError: Cannot read property 'children' of null

and can't see any entrie, all empty now.

### Steps to reproduce

1. Update to 3.5.13.1 
2. go to entries section

### Additional info

- Craft version: 3.5.13.1 
- PHP version: 7.3

Sorry duplicate of #7020

**Comment by brandonkelly** [comment]
Thanks for reporting that! It was also reported by #7017, and we just released Craft 3.5.13.2 with a fix.
