### ISSUE TITLE
CP nav jumps when there are breadcrumbs

### ISSUE THREAD

**Issue by JayBox325** [craftcms/cms#7021]
### Description
I have viewed the CP in a smaller display and noticed that when the sidebar is hidden and accessible with the hamburger, this jumps when there are breadcrumbs.

![Screenshot 2020-10-16 at 12 40 32](https://user-images.githubusercontent.com/13233809/96254356-11f59c80-0fad-11eb-8c77-ff45fb877427.png)

### Additional info

- Craft version: 3.5.12.1

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.14 is out now with that fix.
