### ISSUE TITLE
Allow users to activate account with system is not live.

### ISSUE THREAD

**Issue by sunscreem** [craftcms/cms#7022]
### Description

We keep our staging website "not live" ie `'isSystemLive' => false,`.

We often need to add new users to staging site (usually a client while the site is in development), but they can't create a password when the system isn't live. 

Our workaround is to send them their activation URL, set the system live, wait for them to activate, and set it system not-live again.

Would be handy to have this as an option?

Maybe something like:

```
   // Staging environment settings
    'staging'    => [
        'devMode'           => false,
        'allowAdminChanges' => false,
        'isSystemLive' => false,
        'allowUserAccountActivation' => true <---
    ],
```

**Comment by brandonkelly** [comment]
When you create these users, are you enabling either of these permissions?

- Access the site when the system is off
- Access the control panel

**Comment by sunscreem** [comment]
Yes.. of course....

(he says... quietly closing the issue and hoping no-one notices how stupid he's been)
