### ISSUE TITLE
Group database commands in Craft CLI

### ISSUE THREAD

**Issue by frank-laemmer** [craftcms/cms#7023]
Currently there are two commands to work with the database in the Craft CLI: "backup" and "restore". But when running `./craft` to get a list of all the available commands it's easy to miss the connection of these since one is listed at the start, the other at the end.

## Proposal

Instead of `backup/db` and `restore/db` maybe use `db/backup` and `db/restore` so that the two commands are grouped together.

**Comment by leevigraham** [comment]
@brandonkelly If I was going to take a stab at this how would you go about making this a non-breaking change? Call the new commands from the existing commands?

**Comment by brandonkelly** [comment]
Yeah, no need though, I’ll be getting to it soon, we want to get 3.6 out asap for PHP 8 support.

**Comment by brandonkelly** [comment]
Just made this change on the `3.6` branch.

**Comment by brandonkelly** [comment]
Craft 3.6 has now been officially released ✨
