### ISSUE TITLE
Template MIME type-based Content-Type headers should work for `.x.twig` templates

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/cms#7025]
Currently if you create a `feed.rss` template and request it, Craft will automatically set the `Content-Type` response header to `application/rss+xml` based on the `.rss` template file extension.

However if you create a `feed.rss.twig` template (which is still accessible via `/feed.rss` per the [defaultTemplateExtensions](https://craftcms.com/docs/3.x/config/config-settings.html#defaulttemplateextensions) setting), the `Content-Type` response header will be `text/html`.

Craft can safely ignore trailing `.twig` template file extensions when determining the default `Content-Type` header, as `.twig` is meaningless in terms of describing the response content.

**Comment by brandonkelly** [comment]
Craft 3.5.14 is out now with this.

**Comment by KatieMFritz** [comment]
Does this work for email templates too? So `template.html.twig` will be `text/html`?

**Comment by brandonkelly** [comment]
If that email template were accessed directly, yes, but this change actually didn’t impact `.html.twig` specifically, as that would already have come back with a `text/html` MIME type.
