### ISSUE TITLE
[3.5.13.2] After copying project config to another project Project Config complains about plugins that were uninstalled long time ago

### ISSUE THREAD

**Issue by bencresty** [craftcms/cms#7026]
### Description

As title says: when trying to apply project config files to a database of another project an error messages shows it can only do that when some plugins are installed. But these plugins were uninstalled and removed a long time ago on the original project, so it doesn't make sense to still have references to them, let alone require them to apply the update.

### Steps to reproduce

See above

### Additional info

- Craft version: 3.5.13.2
- PHP version: 7.4.9
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
How were the plugins uninstalled? Guessing maybe they were only uninstalled via Composer, without actually uninstalling them from the Settings → Plugins page first (which would have removed them from the database and project config).

On the initial project, open up `config/project/project.yaml` and remove the “uninstalled” plugins from the `plugins` list. Then apply the changes from the Project Config utility or run the `php craft project-config/apply` command.
