### ISSUE TITLE
[3.5.13.2] Install doesn't work anymore

### ISSUE THREAD

**Issue by bencresty** [craftcms/cms#7027]
### Description

Running `craft install` throws an error `Undefined variable: configFile` in MigrationManager.php on line 252
![image](https://user-images.githubusercontent.com/69322733/96362684-5315ba00-112f-11eb-9ef1-1c8520a32832.png)

There are no migrations in this project.

Before install on this project was working fine. It looks like this is caused by the change in project config system when upgraded from 3.4.x to 3.5.x.

### Steps to reproduce

1. Run `craft install`
2. Look at the terminal

### Additional info

- Craft version: 3.5.13.2
- PHP version: 7.4.9
- Database driver & version: MySQL 5.5.5

**Comment by Epskampie** [comment]
Downgrading to craft 3.5.10 allowed me to run `craft install` again.

**Comment by timkelty** [comment]
Same issue!

**Comment by brandonkelly** [comment]
Not able to reproduce this with or without a `config/project/` folder in place.

Can you please search for that error in `storage/logs/console.log` and post the full stack trace(s) below it?

`MigrationManager.php:252` just re-throws a caught exception, so not really helpful.

**Comment by timkelty** [comment]
@brandonkelly https://github.com/craftcms/cms/blob/13f7a77ee0636a6ff3397f9ac862c892427b6ef3/src/migrations/Install.php#L1071

**Comment by brandonkelly** [comment]
Thanks. Just fixed that for the next release. Note that that line wouldn’t get executed unless there was an issue loading the existing project config data. Look for `> can't apply existing project config: [error message]` right above that error to see what the issue was.

**Comment by brandonkelly** [comment]
Craft 3.5.14 is out now with that fix.
