### ISSUE TITLE
[3.5.13.2] Craft throws exception on restoring database

### ISSUE THREAD

**Issue by bencresty** [craftcms/cms#7028]
### Description

When running `craft restore/db {dbfilename-here}`, which was used heavily last months without any issue, now suddenly throws an exception error `Base table or view not found: 1146 Table '{databasename-here}.info' doesn't exist`.

This happened to occur only since one of the last upgrades of Craft. Before this was working fine in the same project. Nothing has been changed to the database nor the project structure nor the workflow. So something must have been changed in one of the latest Craft upgrades causing this.

For the record: The sql file is fully up to date, created with Crafts own backup command line feature and does contain the `info` table. So there is no real reason for this exception to popup imho.

**To be honest I'm getting the strong impression this CMS isn't stable at all.** And as a user how do we know which version in the history IS stable? They all seem to have a lot of issues.
**Can we get a version where first all existing issues are fixed and no new features are added causing new issues? And seperate versions with new and tested features?**

### Steps to reproduce

1. Restore a database from the terminal
2. Look at the terminal

### Additional info

- Craft version: 3.5.13.2
- PHP version: 7.4.9
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
I suspect maybe this is related to #6718, where Craft now provides more helpful info as to why it thinks it’s “not installed”. I’m able to reproduce the same error when runnig any CLI commands if the DB tables are missing. However the error does not prevent the `restore` command from working properly:

```bash
$ php craft restore /home/ubuntu/dev/craft3.test/storage/backups/happy-lager--2020-10-19-211821--v3.5.13.2.sql

    Craft can’t fetch the `info` table row.                                                           
    Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'craft3.info' doesn't exist    

Restoring database backup ... done
```

Is that similar to what you’re seeing? If so, nothing to worry about.

> To be honest I'm getting the strong impression this CMS isn't stable at all. And as a user how do we know which version in the history IS stable? They all seem to have a lot of issues.

Sorry you’ve gotten that impression; I don’t believe that is the norm. But we are here to fix any issues that do come up.

> Can we get a version where first all existing issues are fixed and no new features are added causing new issues? And seperate versions with new and tested features?

Each release is considered stable. But I hear you, and we will be implementing a new versioning strategy starting with 4.0, which should at least help more cleary identify releases include more than just bug fixes / stability improvements.

**Comment by hiasl** [comment]
I still have this problem and can not confirm, that the restore command continues after the exception. When the `info` table is missing or empty, the restore command exits.

**Comment by brandonkelly** [comment]
Thanks @hiasl. It was working on my end if the whole table was missing, but not if the table existed but the row was missing. Just got that fixed for the next release.
