### ISSUE TITLE
Customizing Minute Increment on Time field

### ISSUE THREAD

**Issue by tinybeans** [craftcms/cms#7029]
I would like to customize "**Minute Increment**" on Time field. Currently, I can only choose `15` , `30` and `60`. However, I sometimes need to set `10`. I usually add an option to the select element using the Developer Tools on the browser. 

I would be happy if I can change the options on the General Config Setting.

**Comment by brandonkelly** [comment]
Just added 5 and 10 minute time increment options to Date and Time fields, for the next release.

**Comment by tinybeans** [comment]
@brandonkelly Awesome! Thank you so much!

**Comment by brandonkelly** [comment]
Craft 3.5.14 is out now with those new options ✨
