### ISSUE TITLE
Tag field drop down: Improve accessibility with keyboard control

### ISSUE THREAD

**Issue by tomkiss** [craftcms/cms#7031]
Hi there,

I know that Craft CMS is on an accessibility drive at the moment (also, congrats on winning the W3C CMS choice!).

So, with that in mind I wanted to suggest an accessibility improvement to the tag field.

When adding existing tags to an entry using a tag field, a drop down list of tags pops up, showing any tags already in the system matching the text, as you type. 

If there is a single result, you can tap _Enter_ for the suggested tag to be added.

However, when there are multiple tag suggestions, there doesn't presently appear to be any way to interact with the list, other that with a pointer device.

I am often adding many tags at once, from an existing pool and I think it would be a great improvement if the drop down list of suggested tags included keyboard control support. This would allow the user to navigate the list using without need for switching to an input device after typing. Similar to a [ComboBox](https://www.w3.org/TR/wai-aria-practices-1.2/) model.

If you've already got this on the list, 
please disregard. Otherwise, I hope this is helpful.

**Comment by brandonkelly** [comment]
Just added up and down arrow navigation for the next release. Thanks for pointing that out!

**Comment by brandonkelly** [comment]
Craft 3.5.14 is out now with that improvement ✨

**Comment by tomkiss** [comment]
Amazing! Great work, thank you!
