### ISSUE TITLE
Search indexes not updating after creating entry through GraphQL mutation

### ISSUE THREAD

**Issue by jamesedmonston** [craftcms/cms#7032]
### Description

When creating an entry through a `save_..._Entry` mutation, the search indexes are not updating until the admin interface is visited and the queue is fired.

Screen recording: https://youtu.be/fRk9N6Ywe8g.

Using https://github.com/ostark/craft-async-queue does fix the issue, though.

### Steps to reproduce

1. Create entry with `save_..._Entry` mutation
2. Run `entries` query with a `search` parameter that should return the new entry
3. Refresh admin panel
4. Run query again

### Additional info

- Craft version: 3.5.13.2
- PHP version: 7.3.23
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

1. DigitalOcean Spaces Volume 1.1.3
2. Imager v2.4.0
3. Imager Thumbor Transformer 1.0.5.1
4. Sentry SDK 1.0.6
5. Sidebar Entry Types 1.0.3
6. Super Table 2.6.3
7. TDE Emoji text v1.0.1

**Comment by brandonkelly** [comment]
You can solve this by setting up a daemonized queue runner, rather than leaving it up to the built-in queue runner (which is expected to only run on CP requests). See https://craftcms.com/docs/3.x/config/#queue-component.

**Comment by jamesedmonston** [comment]
@brandonkelly Neat, thanks Brandon.
