### ISSUE TITLE
Exclude plugin fields from project YAML

### ISSUE THREAD

**Issue by TomHell** [craftcms/cms#7033]
### Description
**Craft CMS:** 3.5.12
**PHP: 7.4**
**Environment:** Google Cloud Service (3 pods, load balancer, shared DB between pods)
**Plugin feature:** exclude fields form project.yaml

#### Problem
Our In-house Plugin has a field with a wrong value which occurs an PRODUCTION side an error while this field has a value for dev purposes and this value will be published with each release while the project.yaml will be updated. Currently we can not use the project config workflow.
Is there any tip or solution to exclude plugin fields. Other workarounds are welcome

#### Environment
We use Craft CMS behind a load-balancer on 3 pods. (Google Cloud Service)

#### Plugin
In-house plugin with a field which has a bearer-token as field value. This token/value expired after 1 hour and need to be saved in database while each pod can use the same token. So a key .env KEY for using as field-value is not an option.
Also a file base solution is not an option, because we have no shared file storage.

**Comment by brandonkelly** [comment]
Where is the value currently stored, exactly?

**Comment by TomHell** [comment]
Hi Brandon,

in the Plugin->Settings there is a field **bearer_token**.

**Comment by brandonkelly** [comment]
OK, so part of the plugin settings. How are you setting it dynamically?

**Comment by TomHell** [comment]
**1. Option** 
After saving of the plugin settings a new token will be fetched. (This is our fallback option)

**2. Option**
Crontab is running a console action to fetch each 45 minutes a new token only on the first pod/container in the environment.

**Comment by brandonkelly** [comment]
I would suggest you just find a different way to store the token. That could be in a custom database table, or even just in the data cache – especially if you are using [Redis](https://craftcms.com/docs/3.x/config/#application-configuration) or a [database driver](https://craftcms.com/docs/3.x/config/#database-cache-example). The plugin settings are not meant for storing dynamic data like this.

**Comment by Anubarak** [comment]
I guess the easiest "work-around" would be to store it in a custom table instead of the plugin settings in this case. 

A really dirty quick fix would be to make the field env aware and write your value into the env file instead of the DB - but I wouldn't suggest that 😅

**Comment by raitisg** [comment]
We also have this issue and we don't think storing plugin settings in config is appropriate.

We are using HTML Cache plugin (which has "Excluded URLs" that are not cached). Our editors are creating pages and adding appropriate URLs to this list and then it gets overwritten by dev environment. This has bitten us several times already.

**Comment by brandonkelly** [comment]
I would take that up with the plugin dev author. Plugins should be providing environment-specific ways to configure their plugins when appropriate.

**Comment by st-mcd** [comment]
I hope it's ok to resurrect this issue but one of my plugins settings is an Asset (element) and the ID is stored in the project.yaml. As authored content it is going to vary by environment, or is there a better way of handling Asset settings?
