### ISSUE TITLE
Move user photos (User Photo Location) on Resave Users (CP or CLI) and Change Asset Filename / Title

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#7034]
### Description
It would be nice when User Photos act same as other assets in craft.
My User Location Setting in this case is:
![image](https://user-images.githubusercontent.com/764292/96457524-2beae580-1220-11eb-957e-7e13642f2e45.png)

Now, we have to change that (in this case remove the `{id}` to have all in one folder). 
But on `./craft resave/users` the photos do not move. 

Anther FR related to this was to Rename the Title and Filename for this Asset. Maybe this can also act like normal Asset Fields (double click > modal)

@brandonkelly maybe you can say me if it's a little FR or something that takes a bit cause have to find a solution for the client.
Thanks!

**Comment by brandonkelly** [comment]
Going forward, Craft will ensure that user photos are in the right location each time a user is saved.

> Anther FR related to this was to Rename the Title and Filename for this Asset. Maybe this can also act like normal Asset Fields (double click > modal)

Please post that as a new feature request 🙏

**Comment by brandonkelly** [comment]
Craft 3.5.14 is out now with that change ✨
