### ISSUE TITLE
Diacritic chars in slug are not normalized

### ISSUE THREAD

**Issue by redzioch** [craftcms/cms#7035]
### Description

When diacritic chars like "ąęĘĆößšž" are used in slug they should be normalized (to i.e. "aeECossz"). This generates problems with SEO - sometimes it is displayed with URL-encoding in search engines (i.e. "ę" becomes "%C4%99".

It can be considered as improvement/new feature, but from my point of view it's more a bug. It leads to a lot of problems and personally I don't see any reason not to normalize slugs.

In JS I normalize to NFD and remove unnecessary chars:
`text.normalize("NFD").replace(/[\u0300-\u036f]/g, "")` 

### Steps to reproduce

1. Create entry with title/slug with chars from above
2. Check the slug :)

### Additional info

PHP version | 7.0.33
Linux 4.15.0-118-generic
MySQL 5.7.31
Craft Solo 3.5.13.2

**Comment by brandonkelly** [comment]
This is actually configurable, via the [limitAutoSlugsToAscii](https://craftcms.com/docs/3.x/config/config-settings.html#limitautoslugstoascii) config setting.
