### ISSUE TITLE
Disabled parent not returned when setting status to include disabled entries

### ISSUE THREAD

**Issue by weotch** [craftcms/cms#7036]
### Description

I have a structure with two levels:

1. Brand
2. Flavor

The flavor with an id of `35398` is disabled and so is its parent.  I am querying for the flavor and it's brand flavor with this query:

```graphql
query getFlavor($slug: [String!], $status: [String]) {
  entry(type: "flavor", slug: $slug, status: $status) {
    id
    title
    ... on products_flavor_Entry {
      id
      parent {
        ... on products_brand_Entry {
          id
          title
        }
      }
    }
  }
}
```

And I'm using these variables:

```json
{
  "slug": "my-product",
  "status": ["live", "pending", "disabled"]
}
```

I am getting this result:

```
{
  "data": {
    "entry": {
      "id": "35398",
      "title": "My Product",
      "parent": null
    }
  }
}
```

I expect `parent` to be an object but it's `null`.  I think the status condition that allows disabled entries isn't being applied to the `parent` lookup.

### Additional info

- Craft version: `3.5.12`
- PHP version: `7.4.1`
- Database driver & version: `MySQL 8.0.19`
- Plugins & versions:

![image](https://user-images.githubusercontent.com/77567/96505819-84fc4e80-120b-11eb-808f-b27446a4c5df.png)

**Comment by brandonkelly** [comment]
This is currently working as expected, but `parent` should be able to accept arguments like `status` that would make this possible:

```graphql
query getFlavor($slug: [String!], $status: [String]) {
  entry(type: "flavor", slug: $slug, status: $status) {
    id
    title
    ... on products_flavor_Entry {
      id
      parent(status: $status) {
        ... on products_brand_Entry {
          id
          title
        }
      }
    }
  }
}
```

So will mark this as an enhancement request.

**Comment by andris-sevcenko** [comment]
Just fixed this for the next release! Thanks!
