### ISSUE TITLE
Controlpanel font issue with Craft.woff

### ISSUE THREAD

**Issue by MisterMike** [craftcms/cms#7037]
### Description

I don't know if this is an issue, but starting some Craft versions ago, the speech bubbles in the CP, that denominate translatable fields, are gone. Instead, a Chinese character is displayed.
<img width="273" alt="screenshot_craft_cp-font-issue" src="https://user-images.githubusercontent.com/1379384/96554536-f513de80-12b6-11eb-84eb-0f14c219f5aa.png">

### Steps to reproduce

1. Login to CP
2. Edit an entry that has at least one multi-lingual field
3. The translation indicator is shown as some Chinese character instead of the speech bubbles (data-icon="language")

### Additional info

- Craft version:Craft CMS 3.5.13.2
- PHP version: 7.4.11
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
That is expected, and it’s not just a Chinese character; half of it is the letter `A`. The combination is a popular icon for “translation”, and arguably more appropriate than a chat bubble.

**Comment by MisterMike** [comment]
Hey Brandon, thanks for the clarification and sorry for the interruption. You can go on doing more useful stuff than my "bug reports" :-D

**Comment by piotrpog** [comment]
@brandonkelly 
To be honest, for non-technical people "chat" icon is more self-explanatory that new symbol. I bet some of my clients would also think it's Chinese character.
Would it be possible to add config option that brings back old icon?

**Comment by brandonkelly** [comment]
Not interested in making the icons configurable, but we will look out for a better alternative.

**Comment by MisterMike** [comment]
You could possibly „hack“ that in using CPcss from Doublesecret Agency, but I haven‘t tried that.

https://github.com/doublesecretagency/craft-cpcss

**Comment by khalwat** [comment]
Some other options here: https://thenounproject.com/search/?q=translate
