### ISSUE TITLE
Erroneous data format for unserializing 'craft\base\MemoizableArray' 

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#7038]
### Description

I made the mistake and stored an object in my job and that one contains one of your new `craft\base\MemoizableArray` instances. Of course the solution would be to not store that object in job to begin with and I'll remove that but could you eventually include the required functions to unserialize it?

This is kinda a breaking change (of course it's bad practice but it breaks previous "kinda" working code)
Everything worked before that update/object was included

**Comment by brandonkelly** [comment]
All class properties set to `MemoizableArray` objects are now excluded from serialization, for the next release.

**Comment by Anubarak** [comment]
Awesome, thank you. That's even better 👍

**Comment by brandonkelly** [comment]
Craft 3.5.14 is out now with that change ✨
