### ISSUE TITLE
User Photos Edit Asset like normal Assets

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#7040]
Would be nice to have the possibility to rename Title and Filename for User Photos same as on other Asset Fields. (double click on it opens the Asset Details). 

Also it would be nice to add additional fields on that assets. In our case we need a Photo Credit Field. Would be great to have it directly on the asset and not as separate Field. Connect whats belongs to each other.

**Comment by brandonkelly** [comment]
User photos _are_ normal assets, and you can assign custom fields to them and edit their filename/field values, from the Assets section. Just not from the Edit User page.

**Comment by davidhellmann** [comment]
Yes, thats the point. Our client have to edit round about 300 Users and the imported Filenames for the User Photos are very unspeaking. Would be nice they can edit all the stuff directly on the user page. And sure, you're right with the custom fields and edit within the assets menu point. :)
