### ISSUE TITLE
Update Twig to 2.14.0

### ISSUE THREAD

**Issue by oles** [craftcms/cms#7044]
### Description

I'd really like to see this update! 

It features a long awaited object initialisation shortcut: https://github.com/twigphp/Twig/pull/3277

Currently it is listed in `craftcms/cms/composer.json` as `"twig/twig": "~2.12.5 || ~2.13.1",`, so no matter how many `composer updates` I run, it will not come :broken_heart:

**Comment by brandonkelly** [comment]
Just added support for 2.14 for the next release!

Note that 2.14 dropped PHP 7.1 support, so you will need to make sure your environment is running at least PHP 7.2.5, and also check your `config.platform.php` value in `composer.json`.
