### ISSUE TITLE
Wrong result while ordering by lightswitch and DateTime field

### ISSUE THREAD

**Issue by Stalex89** [craftcms/cms#7045]
### Description

I have a list of entries, each entry has the lightswitch field that should put entry on the top of the query result list when the lightswitch is turned on, also I need to sort entries by post date. So, in the end there should be the following order: highlighted entries ordered by date, then unhighlighted entries also ordered by date

I am using orderBy: "<lightswitch_field> DESC, postDate DESC" query variable, the ordering by lightswitch is correct, but the postDate ordering is wrong in the middle of the list

### Steps to reproduce

1. Create multiple entries of the same entry type containing the lightswitch field
2. Turn on the lightswitch for several entries
3. Query the entries with using orderBy "<lightswitch_field> DESC, postDate DESC"

### Additional info

- Craft version: 3.5.12.1
- PHP version: 7.4.11
- Database driver & version: MySQL 5.6.49
- Plugins & versions: 
Guest Entries | 2.3.0 
Reasons | 2.2.2
Redactor | 2.8.2
Super Table | 2.6.3
Typed link field | 1.0.23
Video Embedder | 1.1.4

![Screenshot 2020-10-20 at 17 48 24](https://user-images.githubusercontent.com/23526237/96735883-4fe32e00-13bc-11eb-85b9-8402987d2b9d.png)

**Comment by brandonkelly** [comment]
If you remove `platformHighlighted DESC`, do the entries come back in the right order?

**Comment by Stalex89** [comment]
removing the `platformHighlighted DESC` give the right order by postDate:

![Screenshot 2020-10-22 at 16 09 32](https://user-images.githubusercontent.com/23526237/96883887-2b9d5500-1481-11eb-9c96-a5746314af5e.png)

what I've noticed is when I order only by `platformHighlighted DESC` it sorts properly by lightswitch, but both highlighted and unhighlighted entries are not ordered by postDate:

![Screenshot 2020-10-22 at 16 14 53](https://user-images.githubusercontent.com/23526237/96884798-34daf180-1482-11eb-8c8c-00e1bdc60c96.png)

but when I apply also `postDate DESC` it sorts only the highlighted part:

![Screenshot 2020-10-22 at 16 15 57](https://user-images.githubusercontent.com/23526237/96884924-5d62eb80-1482-11eb-8a2b-fa9732760562.png)

![Screenshot 2020-10-22 at 16 16 14](https://user-images.githubusercontent.com/23526237/96884938-605ddc00-1482-11eb-868c-541277d33d42.png)

Looks like the postDate ordering applies only to the first part of the result obtained by lightswitch ordering

**Comment by brandonkelly** [comment]
Can you try creating a Twig template with this?

```twig
{% set entries = craft.entries()
  .section('platform')
  .orderBy('platformHighlighted ASC, postDate DESC')
  .all() %}

{% dd entries|map(e => {
  postDate: e.postDate|date('Y-m-d Hi-i-s'), 
  platformHighlighted: e.platformHighlighted,
}) %}
```

Does it output entries in the same order?

**Comment by Stalex89** [comment]
Sorry for the long response, these are the results from the twig:

![Screenshot 2020-10-27 at 09 31 36](https://user-images.githubusercontent.com/23526237/97276582-ae366380-1837-11eb-8961-a10ed9fc90c3.png)

![Screenshot 2020-10-27 at 09 34 03](https://user-images.githubusercontent.com/23526237/97276854-09685600-1838-11eb-9537-f6989edae065.png)

Ordering is still incorrect for the unhighlighted items

**Comment by brandonkelly** [comment]
Aha, that makes sense. Unexpected side effect of Lightswitch fields trying to respect their Default Value setting for `null` values. If you run the `resave/entries` command, this will resolve itself.

```bash
php craft resave/entries --section=platform
```

**Comment by Stalex89** [comment]
Ok, thank you for the hint 👍
