### ISSUE TITLE
Field groupIds in UserGroupsAssignEvent is broken in 3.5.13

### ISSUE THREAD

**Issue by VBMart** [craftcms/cms#7046]
### Description
Users class method `assignUserToGroups` now use `'groupIds' => array_keys($groupIds),` instead `'groupIds' => $groupIds`. As result - we have unused groupIds field in this event.

### Steps to reproduce

1. Listen EVENT_BEFORE_ASSIGN_USER_TO_GROUPS Event
2. Get UserGroupsAssignEvent $event
3. Dump $event->groupIds

### Additional info

- Craft version: 3.5.14
- PHP version: 7.4
- Database driver & version: Doesn't matter
- Plugins & versions: Doesn't matter

**Comment by brandonkelly** [comment]
Whoops, thanks for reporting that! Just fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop",
  "...": "..."
}
```

Then run `composer update`.
