### ISSUE TITLE
Pass `$this` as sender to SetEagerLoadedElementsEvent

### ISSUE THREAD

**Issue by johndwells** [craftcms/cms#7047]
### Description

I may be doing this very wrong, but: I am building a site module that defines an eager loaded relationship which ties entries to rows a custom DB table.

I can easily define this eager query with `Element::EVENT_DEFINE_EAGER_LOADING_MAP`.

But because of how `Element::EVENT_SET_EAGER_LOADED_ELEMENTS` is triggered, I cannot attach the eagerloaded rows to their related entry.

Towards the end of method `Element::setEagerLoadedElements()`, on lines [2884-2889 of `base/Element.php`](https://github.com/craftcms/cms/blob/master/src/base/Element.php#L2885-L2889) are:

```
$event = new SetEagerLoadedElementsEvent([
    'handle' => $handle,
    'elements' => $elements,
]);
Event::trigger(static::class, self::EVENT_SET_EAGER_LOADED_ELEMENTS, $event);
```

It's the `static::class` bit that prevents the event's `sender` property from being set to `$this`, e.g. the entry.

If the trigger is changed to:

```
Event::trigger($this, self::EVENT_SET_EAGER_LOADED_ELEMENTS, $event);
```

Then I'd be good to go as I'd have `$this` passed to the event's `sender` property.

I don't know if this is a reasonable request, or if I'm going about this the wrong way!

**Comment by brandonkelly** [comment]
Whoops, that event should have been triggered via `$this->trigger()` rather than `Event::trigger()`. Just fixed for the next release, so going forward you will be able to access the sender via `$event->sender`.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop",
  "...": "..."
}
```

Then run `composer update`.
