### ISSUE TITLE
Allow only to select asset, not upload

### ISSUE THREAD

**Issue by knynkwl** [craftcms/cms#7052]
### Description
I've run into instances where I would like to client to select from a list of icons that have been added to a folder but would like to restrict them from uploading their own asset.

**Comment by andris-sevcenko** [comment]
I'm probably missing something, but is there a reason why permissions won't accomplish that for you?

**Comment by knynkwl** [comment]
Nope you are correct, brain wasn't working last week. Thanks!

**Comment by andris-sevcenko** [comment]
Happens to the best of us!
