### ISSUE TITLE
Broken IDE auto completion for Craft::$app

### ISSUE THREAD

**Issue by gglnx** [craftcms/cms#7057]
### Description

Since [this commit](https://github.com/craftcms/cms/commit/61f08f9cef8ebf71a8c762e59dadd162fed5af87) by @angrybrad the phpdoc for `Craft::$app` has moved into the `CraftTrait` and is back referenced with `@mixin`. But Intelephense for VS Code for example doesn't support the `@mixin` pattern (https://github.com/bmewburn/vscode-intelephense/issues/123), so at least for VS Code auto completion is now broken for `Craft::$app` 😢

### Steps to reproduce

1. Use VS Code
2. Try to auto complete `Craft::$app->getEle…`

### Additional info

- Craft version: 3.5.14

**Comment by brandonkelly** [comment]
We use the `@mixin` trick in a few other places as well, and that commit fixed a major testing bug, so I don’t want to revert it. I love VSCode, but it’s not a great PHP editor.

**Comment by gglnx** [comment]
I won't go into an editor discussion, because it's a personal choice.

My quick fix was to add `@property \craft\web\Application|\craft\console\Application $app` to the phpdoc for `Craft`. Maybe it's possible to add this? I think that I'm not alone using VS Code developing Craft and it would restore the great developer experience I had with Craft. Thank you ❤️

**Comment by brandonkelly** [comment]
Ah interesting, sure we can add that. That trick doesn’t actually work for PhpStorm, but can’t hurt.
