### ISSUE TITLE
Roles / Permissions - a user without permission can remove a file uploaded by another user

### ISSUE THREAD

**Issue by nflorentin** [craftcms/cms#7059]
Hi,

I just noticed that a user can remove a file uploaded by another user even though he has not the permission do it.

Screenshots:
![Capture d’écran 2020-10-26 à 09 39 15](https://user-images.githubusercontent.com/5750349/97151519-e3777e80-176f-11eb-854e-965d20ee23c1.png)

![Capture d’écran 2020-10-26 à 09 45 43](https://user-images.githubusercontent.com/5750349/97151630-0dc93c00-1770-11eb-927a-24308c0cb05b.png)

Thank you in advance for your feedback!

### Additional info

- Craft version: 3.5.12
- PHP version: 12

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by nflorentin** [comment]
Awesome, thanks for your reactivity!
