### ISSUE TITLE
Unable to share a category entry when disabled

### ISSUE THREAD

**Issue by DowleyDeveloped** [craftcms/cms#7060]
### Description

When a category entry has been created, if disabled, when you try and share the draft using tokens it gives a 403 error.

### Steps to reproduce

1. Create category entry and disable it.
2. Click Share & open in a private window, it displays a 403 error

### Additional info

- Craft version: 3.4.17.1
- PHP version: 7.2.24
- Database driver & version: MySQL 5.7.31

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.
