### ISSUE TITLE
Unstyled login & unable to log in after creating new Craft site with nitro

### ISSUE THREAD

**Issue by josephkmh** [craftcms/cms#7061]
### Description
I'm a new user, so apologies if I'm overlooking something obvious!

I've installed nitro 1.1.0 according to the instructions here: https://craftcms.com/docs/nitro/installation.html

Then, after installing craft on my local machine, I follow the link to log in (http://my-craft-site.test/admin/login). Here I am greeted with an unstyled page. In my network tab, all requests to css/js files in /cpresources are 404s, and indeed that folder is empty in my filesystem.

![image](https://user-images.githubusercontent.com/7550957/97187910-39b1e500-17a3-11eb-887d-e0f70b856cf3.png)

After entering the login details for the user I created during the installation of craft, I get the following error: 

![image](https://user-images.githubusercontent.com/7550957/97188876-4c78e980-17a4-11eb-873b-6e6844e07a55.png)

At this point I'm not sure how to debug. I found some threads mentioning CSRF errors, which led me to try various different browsers, clearing my cache, etc. Unfortunately none of this helped. I would really appreciate any help with this, I'm very keen to get started with Craft but unfortunately I've spent the last couple days struggling to install it.

### Steps to reproduce

1. Install nitro verison 1.1.0 (following these instructions: https://craftcms.com/docs/nitro/installation.html)
2. Add a new database: `nitro add db`
3. Install Craft CMS via composer: `composer create-project craftcms/craft my-craft-directory`
4. Add the site to nitro: `cd my-craft-directory && nitro add`
5. Install Craft CMS: `./craft setup` using IP from `nitro info` and db user: `nitro`, db password: `nitro`. Installation appears successful by all indicators in the CLI.
6. Visit local domain, attempt to login and get the 400 error 

### Additional info

- Craft version: 1.0.62
- PHP version: 7.4 (via nitro)
- Database driver & version: mysql (via nitro)
- Plugins & versions: n/a

Note: I'm using Composer version 2.0.2

**Comment by josephkmh** [comment]
I'd like to update that I followed the exact same steps on a different machine and got it to work :tada: 

I also have nitro 1.1.0 and PHP 7.4 on this machine. The only difference is that I have Composer 1.10.10 instead of Composer 2.0.2 that I was using previously. Is there any chance that Composer is the culprit?

**Comment by josephkmh** [comment]
I tested Composer 1.10.10 on the first machine, but this didn't seem to make a difference :man_shrugging: 

Since I'm able to get Craft working on my other machine I will close this ticket, but I'm still not sure what the issue was.

**Comment by brandonkelly** [comment]
Huh weird. Check the permissions of your `web/cpresources/` folder, as that is where all the CP’s front-end resources are supposed to get published.

**Comment by aditya-tribes** [comment]
I have same problem how can i fix that 
![image](https://user-images.githubusercontent.com/113181879/191038112-9853bc69-8f9a-4310-b665-7f1ea46049c7.png)
