### ISSUE TITLE
JavaScript MatrixInput "blockDeleted" fired before block is actually deleted

### ISSUE THREAD

**Issue by timmyomahony** [craftcms/cms#7064]
### Description

The [JavaScript `MatrixInput` has a `blockDeleted` event](https://github.com/craftcms/cms/blob/14f0fd652b7a99820f804ba6c0a0db762bf26206/src/web/assets/matrix/src/MatrixInput.js#L763) that you can listen to, for example:

```
$(".matrix-field").data("matrix").on("blockDeleted", function(ev){
  // ...
});
```

The problem is that the trigger for this event is fired _before_ the animation for removing the block finishes:

https://github.com/craftcms/cms/blob/14f0fd652b7a99820f804ba6c0a0db762bf26206/src/web/assets/matrix/src/MatrixInput.js#L763

This means that any code you put in the callback for the event handler will most likely run before the block has actually been deleted. This is a problem if you need to know how many blocks there are. For example `canAddMoreBlocks()` may not be correct if used within the callback.

Instead, the event should only be fired once the animation has completed, so within the `velocity` callback here:

https://github.com/craftcms/cms/blob/14f0fd652b7a99820f804ba6c0a0db762bf26206/src/web/assets/matrix/src/MatrixInput.js#L753

### Additional info

- Craft version: 3.5

**Comment by brandonkelly** [comment]
Good point. Just fixed that for the next release.
