### ISSUE TITLE
Add ./craft create/db command

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#7065]
### Description

As part of our CI pipeline we're creating a new DB on the fly for the feature branch we're previewing. Currently that is handled with a simple mysql command:  `mysql -e "CREATE DATABASE IF NOT EXISTS \`{{db_name}}\`"` but that involves loading the db_name as an environment and making sure theres a `.my.cnf` file setup to configure the mysql client.

It would be great if there was a `./craft create/db` that created an empty DB with the db.php configuration.

**Comment by brandonkelly** [comment]
Will get to this after renaming the `backup/db` and `restore/db` commands to `db/backup` and `db/restore` (#7023).

**Comment by brandonkelly** [comment]
Sorry, actually not going to add this. I thought that Yii had a built-in command for creating a DB but I was mistaken. And we can’t establish a DB connection without a database to connect to, so this would end up running a `mysql` command which will be error-prone (like backups/restore are, but without as much justification for it).

**Comment by angrybrad** [comment]
It'd also require new database create permissions that we currently don't require.

**Comment by michaelrog** [comment]
Perhaps a more general solution might be to give Craft a way to run ad-hoc CLI commands that are parsed for config/env vars...

```
./craft run "mysql -e 'CREATE DATABASE IF NOT EXISTS {$dbName}'" --dbName='$DB_NAME'
```
or even
```
./craft run/parsed "mysql -e 'CREATE DATABASE IF NOT EXISTS {{ craft.config.db.name }}'"
```

**Comment by brandonkelly** [comment]
Env vars are already available to CLI commands though.

**Comment by leevigraham** [comment]
> Env vars are already available to CLI commands though.

The reason for this request was to use the dotenv .env loading.

**Comment by brandonkelly** [comment]
Ah, well in that case you could run `source .env` before `mysql`.
