### ISSUE TITLE
Resetting admin password via console

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#7067]
Resetting password in case we forgot/lost it is a bit of a chore right now, we have to access DB, hash new password and replace old one.

I think this could be sped up with console commands. I propose adding two:

* change password by username - changes password of specific admin user.
* list admins - list usernames of admin users. I think it is also important because we might also forgot account username.

**Comment by brandonkelly** [comment]
Added for 3.6!

**Comment by brandonkelly** [comment]
Craft 3.6 has now been officially released ✨
