### ISSUE TITLE
Request for isApplyingMigrations

### ISSUE THREAD

**Issue by jerome2710** [craftcms/cms#7068]
Would it be possible to add an app-property like `Craft::$app->projectConfig->getIsApplyingYamlChanges()` for when migrations are being applied? Something like `Craft::$app->projectConfig->getIsApplyingMigrations()`?

The `getIsApplyingYamlChanges()` helps us skip Element-events when content is being saved when applying changes, we need something similar for the migrations to prevent errors in our project logic. We are now checking `Craft::$app->getIsInMaintenanceMode()`, but this is more generic than just the migrations.

**Comment by brandonkelly** [comment]
Just added a new `getAreMigrationsPending()` method to the Updates service, for the next release:

```php
if (!Craft::$app->updates->getAreMigrationsPending()) {
    // ...
}
```

By default it will only check for Craft and plugin migrations. If you want content migrations to be factored in as well, pass `true` to it.

(This will return `true` even if a migration is currently being applied.)

> We are now checking `Craft::$app->getIsInMaintenanceMode()`, but this is more generic than just the migrations.

Actually currently that is only used for migrations, but the nature of maintenance mode is likely to change in v4, so I wouldn’t recommend using it.

**Comment by jerome2710** [comment]
Woah, that was quick! Thanks a lot and for the explanation as well!
