### ISSUE TITLE
Progress label styling missing

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#7070]
### Description

I'm not sure when exactly this happened, but the styling for the progress label (`.progress-label`) is no longer in the CSS.

Here is where the progress label element is defined:
https://github.com/craftcms/cms/blob/3.5.14/src/web/assets/cp/src/js/CP.js#L1026

Here is where the styling _used to_ exist (this file no longer exists):
https://github.com/craftcms/cms/blob/2dae02cfb6b009b19522ead8f69336e64a9fda94/src/web/assets/cp/dist/css/_cp.scss#L1481-L1486

It looks like the CSS was restructured and the styling for `.progress-label` was lost in the process (perhaps during an accessibility review).

### Additional info

- Craft version: 3.5.14

**Comment by brandonkelly** [comment]
Whoops, it was accidentally discarded in a little rearranging done in 4cd6eac5b70ae5d3c7738a033218388733475071. Brought back for the next release. Thanks for reporting!
