### ISSUE TITLE
Inconsistent asset browser functionality regarding sub-directories

### ISSUE THREAD

**Issue by tomkiss** [craftcms/cms#7071]
There is an issue I've encountered a number of times when using the asset browser and I believe there is an inconsistency with the way in which it is presented that is a little confusing at times.

I think it can be boiled down to: _The asset browser does not show directories within the main window, which can lead to UI issues._

Here's a screenshot of an asset volume with some directories:

![asset-browser](https://user-images.githubusercontent.com/183310/97559774-c80dad00-19d5-11eb-96fb-12bf6ae611c6.png)

I'm currently selected on the left-hand side directory tree, with the "soundtracks" directory selected. This contains only sub-directories and no assets so nothing is shown in the right-hand side file listing. With the soundtracks directory still selected, I can search for files - and when I do this, a little checkbox appears, "_Search in subfolders_", which allows me to search for those files in sub-directories and view them within the right-hand side file listing.

This exact same UI is also used for the asset field type when browsing for files. And in this context, it's possible to "disable" the left-hand directory tree by choosing the option "_Restrict assets to a single folder"_.

However, this presents a problem - because there's now an inconsistency. It's possible to then search for files within the sub-directories, without being able to browse to the sub-directories themselves.

So, there's potentially a minor bug here, but also an opportunity for improvement in the asset browser design. I think the best outcome here would be two-fold:
- Enforce stricter meaning of the _Restrict assets to a single folder_ setting, to disable searching of sub-directories and therefore access to files outside of the defined folder.
- Display sub-directories in the file listing so that they can be browsed even when the directory tree is not present. This would make the file browser more similar to Finder or Windows Explorer, and I think this would be more expected behaviour.

This is quite subjective as to whether it's a bug or not, so feel free to move to feature request depending on your point of view.

**Comment by brandonkelly** [comment]
> Enforce stricter meaning of the Restrict assets to a single folder setting, to disable searching of sub-directories and therefore access to files outside of the defined folder.

This was definitely a bug, and I’ve just fixed that for the next release.

> Display sub-directories in the file listing so that they can be browsed even when the directory tree is not present. This would make the file browser more similar to Finder or Windows Explorer, and I think this would be more expected behaviour.

Going to make that possible in Craft 4 – see #979. (However subfolders will not be shown for Assets fields that are restricted to a single folder.)

**Comment by tomkiss** [comment]
Aha perfect, thanks for the response Brandon.
