### ISSUE TITLE
Remove Dropdown for Single Entry Type

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#7077]
### Description

For channel and structure sections where there is only one entry type it would be great if the dropdown could be replaced with the text "edit entry type" and link to the entry type (so it matches the UI pattern implemented for a single) as in the screenshot.

<img width="1190" alt="Screen Shot 2020-10-30 at 1 45 08 pm" src="https://user-images.githubusercontent.com/2505643/97654171-74bf5b80-1ab6-11eb-8c26-e774713721e4.png">

**Comment by brandonkelly** [comment]
We don’t want to rule out the possibility you’re there to go in and add a new entry type though.

**Comment by richhayler** [comment]
Fair point, I had not considered that. Now that there is a tab for entry types when you click to edit a section I suppose there is an alternative way to get to entry types but it’s an extra click away and not as obvious.
