### ISSUE TITLE
Use the Singular Name for a Section as the Default for an Entry Type

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#7078]
### Description

In my experience if I use a plural for the title of a section (e.g. stores, products, clinics, dogs, cats, etc) it makes sense that the logical default entry type for these (for each individual entry) is the singular version (store, product, etc). I appreciate this super low priority, a "nice to have" feature and one quite possibly that may have some technical challenges but one for your consideration as Craft continues to mature.

**Comment by brandonkelly** [comment]
Agree, but currently Craft doesn’t have any way of knowing what the singular section name is.

**Comment by davidhellmann** [comment]
We use mostly default as Entry Type. Maybe this is a other / better approach? 

In our entry router we have also default as fallback.

```twig
{% include [
  'entry/' ~ entry.section.handle ~ '/' ~ entry.type.handle,
  'entry/' ~ entry.section.handle ~ '/default',
  'errors/404',
  'errors/offline',
] %}
```

**Comment by Anubarak** [comment]
@brandonkelly I know this requires some code modifications, but in my opinion a good way to "solve" this would be to include the default entry type handle and name to the section settings in case it's a new section and create a JS script that copies the section handle to the entry type handle.

The user only needs to remove the "s" (in most cases).

**Comment by bencresty** [comment]
> We use mostly default as Entry Type. Maybe this is a other / better approach?

I like this idea. I will try this too on a next project. Calling the default entry 'Default' could also be an improvement for beginners to quickly understand that Sections aren't the same as Entry Types. I know it would have helped me to get the structure a little sooner years ago when using Craft for the first time.

**Comment by brandonkelly** [comment]
Alright I’m convinced. Just made that change for 3.7.
