### ISSUE TITLE
Category Field not parsing as expected.

### ISSUE THREAD

**Issue by michtio** [craftcms/cms#7080]
### Description

Category FIeld not showing specific children when looping through, but ALL children that the category group itself has.

### Steps to reproduce

We have an eager loaded category field on an entry, This Category Group exists out of 2 levels. The entry has a child categories assigned.

Category as followed:

```
- Online
--- 1-1
--- 1-2
--- 1-3
--- 1-4
```

The entry has the following from the above assigned:

```
- Online
--- 1-1
--- 1-3
```

When doing ( categories is eager Loaded ) - we get unexpected output.
```
{% for cat in entry.categories %}
  {% if cat.level == 1 %}
   {( cat.title }}
   {% for childCat in cat.children %} 
    {{ childCat.title }}
   {% endfor %}
 {% endif %}
{% endfor %)
```

The expected output:
```
- Online
--- 1-1
--- 1-3
```

The actual output:

```
- Online
--- 1-1
--- 1-2
--- 1-3
--- 1-4
```

The actual output doesn't make a lot of sense in this case, as I want to loop over the categories assigned to the entry, not all child categories that the category group contains.

### Additional info

- Craft version: 3.5.14

**Comment by brandonkelly** [comment]
`cat.children` is going to give you all of the category’s children, regardless of which ones are related by your Categories field, which explains what you’re seeing.

You can access all of the related categories just from looping through the Categories field:

```twig
{% for cat in entry.categories.all() %}
  {( cat.title }}
{% endfor %)
```

If you want to create nested `<ul>`s of categories, use the [nav](https://craftcms.com/docs/3.x/dev/tags.html#nav) tag:

```twig
<ul>
    {% nav cat in entry.category.all() %}
        <li>
            {{ cat.title }}
            {% ifchildren %}
                <ul>
                    {% children %}
                </ul>
            {% endifchildren %}
        </li>
    {% endnav %}
</ul>
```
