### ISSUE TITLE
Category Filtering not working as expected

### ISSUE THREAD

**Issue by michtio** [craftcms/cms#7084]
### Description

When adding category id's to an array ( either in GraphQL or through an element Query ) the array acts as `OR` rather than `AND` and doesn't reduce the results, which is expected behaviour.

### Steps to reproduce

Have entries with multiple categories, based on adding id's to different categories everything works fine and as `AND` , but when adding multiple id's to a single array that specific category starts working as `OR`

Example:

```
{%- set tutors =    craft.entries.section('tutors')
                    .subjectsCategory([24712])
                    .region([24748])
                    .phases([24907])
                    .optionCategories([27827])
                    .all() -%}
```

The above will give me 8 results in my case, when changing to the below, I'll get 11 results, rather than sticking to 8 or reducing.

```
 {%- set tutors =    craft.entries.section('tutors')
                     .subjectsCategory([24701, 24712])
                     .region([24748])
                     .phases([24907])
                     .optionCategories([27827])
                     .all() -%}
```

Tho when doing the following ( adding an `and` parameter into the id array ) then it works as expected, but this creates overhead and could lead to weird behaviour if you fill arrays with id's with integer in your javascript app that then parses to graphQL. I would expect the array to behave as 'and' in a standard way.

```
{%- set tutors =    craft.entries.section('tutors')
                            .subjectsCategory(['and', 24701, 24712])
                            .region([24748])
                            .phases([24907])
                            .optionCategories([27827])
                            .all() -%}
```

### Additional info

- Craft version: 3.5.14
- PHP version: 7.4

**Comment by brandonkelly** [comment]
This is currently working as expected, and it is clearly documented here: https://craftcms.com/docs/3.x/categories-fields.html#querying-elements-with-categories-fields

> ### Querying Elements with Categories Fields
> 
> When [querying for elements](https://craftcms.com/docs/3.x/element-queries.html) that have a Categories field, you can filter the results based on the Categories field data using a query param named after your field’s handle.
> 
> Possible values include:
> 
> | Value | Fetches elements…
> | - | -
> | `':empty:'` | that don’t have any related categories.
> | `':notempty:'` | that have at least one related category.
> | `100` | that are related to the category with an ID of 100.
> | `[100, 200]` | that are related to a category with an ID of 100 or 200.
> | `['and', 100, 200]` | that are related to the categories with IDs of 100 and 200.
> | an [Category](craft3:craft\elements\Category) object | that are related to the category.
> | an [CategoryQuery](craft3:craft\elements\db\CategoryQuery) object | that are related to any of the resulting categories.
