### ISSUE TITLE
Unit tests very slow when deleting tables before tests

### ISSUE THREAD

**Issue by sarahschuetz** [craftcms/cms#7088]
### Description

When I use the test configuration `dbSetup: { clean: true, setupCraft: true }` the test command takes very long before any tests are executed. When I delete all tables from the database manually and then run the same test command, the database setup and all tests are done in under one minute. When I run the test command again (without manually clearing the database) it takes very long again (over 10 minutes).

### Additional info

- Craft version: 3.5.14
- PHP version: 7.2.18 
- Database driver & version: MySQL 8.0.16

**Comment by angrybrad** [comment]
@sarahschuetz i'm not able to reproduce this - consistently getting < 20 seconds on a fresh install with a simple test using `dbSetup: { clean: true, setupCraft: true }`

<img width="641" alt="CleanShot 2020-11-04 at 20 32 54@2x" src="https://user-images.githubusercontent.com/61869/98198106-14c51c80-1edd-11eb-9b53-42aaee76d621.png">

Can you send your composer.json file, codeception.yml file, and a zip of your tests folder to support@craftcms.com so we can dig in further?
