### ISSUE TITLE
Using private property in child class

### ISSUE THREAD

**Issue by sarahschuetz** [craftcms/cms#7089]
### Description
`Getting unknown property: myproject\tests\fixtures\EntryFixture::_models` when using `grabFixture()` to load entries.

### Problem
`EntryFixture` inherits from `craft\test\fixtures\elements\EntryFixture` like stated in the docs. 
`craft\test\fixtures\elements\EntryFixture` inherits from `craft\test\fixtures\elements\ElementFixture` which overwrites the `getModel()` function. The problem is that `getModel()` references `$this->_models` which is a private member of `yii\test\BaseActiveFixture` and thus cannot be accessed at this point.

See https://github.com/craftcms/cms/blob/develop/src/test/fixtures/elements/ElementFixture.php
Line 67, 68 & 71

### Additional info

- Craft version: 3.5.14
- PHP version: 7.2.18
- Database driver & version: MySQL 8.0.16

**Comment by angrybrad** [comment]
Thanks for reporting! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.16 is out now with that fix.
