### ISSUE TITLE
Update button disappeared after update to 3.5.15

### ISSUE THREAD

**Issue by mark-chief** [craftcms/cms#7091]
### Description
<img width="1380" alt="Screenshot 2020-11-04 at 09 57 38" src="https://user-images.githubusercontent.com/18699249/98098021-b0c33980-1e85-11eb-800b-89a770947da9.png">

### Steps to reproduce

1. Updated craft via the CP to 3.5.15
2. Button no longer there

### Additional info

- Craft version: 3.5.15

**Comment by brandonkelly** [comment]
Thanks for reporting that. Just released 3.5.15.1 with a fix. You will need to update to it manually, though, by running one of these commands:

```bash
> php craft update craft
```
```bash
> composer update craftcms/cms
```

**Comment by mark-chief** [comment]
Hi Brandon, this is happening again for me with Craft 3.5.17.1. In addition to Craft + Plugin Update buttons not appearing, there is no install plugin button in the plugin store. See attached 
<img width="1472" alt="Screenshot 2021-01-06 at 11 35 18" src="https://user-images.githubusercontent.com/18699249/103764387-48264380-5013-11eb-813c-d8ee3d31f7ac.png">

**Comment by brandonkelly** [comment]
@mark-chief Make sure that `allowUpdates` isn’t disabled.
