### ISSUE TITLE
useProjectConfigFile is overwritten

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#7094]
### Description
Currently, with Craft 3.5.x we are forced to use project-config files, which for us is in some project far from ideal.
Can we allow `useProjectConfigFile` to be a regular setting again?

**Comment by brandonkelly** [comment]
See https://craftcms.com/docs/3.x/project-config.html#manual-yaml-file-generation for guidance on how you can avoid the collaborative aspect of project config.
