### ISSUE TITLE
Redactor doesn't load certain js-files if @web is set manually

### ISSUE THREAD

**Issue by jishi** [craftcms/cms#7095]
### Description
If I set @web alias to be "https:", redactor tries to load certain js-files from the wrong url, e.g 
 
`https://current.domain.com/https:/cpresources/206f196b/video.js`

Where-as most other js files are loaded correctly.

The reason for this maybe unorthodox setup, is because I want to support multi-site dev environment without having to set manual hosts entries. hence, for local development, I can access:

`http://localhost/sitename.com`

Which, in production will map to:
`https://sitename.com`

This works fine, except for this redactor bug. 

Maybe this can be worked around with `baseCpUrl` or `resourceBaseUrl`, I'm not sure. 

### Steps to reproduce

1. set base URL for a site to equal `@web//hostname.com`
2. set @web alias to be equal `https:`

### Additional info

- Craft version: 3.5.14
- PHP version: 7.4.12
- Database driver & version: MySQL 5.7.12
- Plugins & versions: 
Amazon S3 1.2.11
Redactor	2.8.3
Retcon	2.2.1

**Comment by jishi** [comment]
Seems like adding 

`'resourceBaseUrl' => '/cpresources'` to the config resolves it, but I don't think this should fail to begin with...

**Comment by brandonkelly** [comment]
`@web` must be set to an actual URL, whether that is absolute or root-relative. Setting it to `https:` is not supported.
