### ISSUE TITLE
GraphQL: fixedOrder look-alike, but for custom field(s) [QueryArgument]

### ISSUE THREAD

**Issue by jesuismaxime** [craftcms/cms#7096]
### Description

I need to search products through a custom field (`storefrontId`) and then have a result that match the order of the query

My query:
```
query ProductsByHandles($handles: [QueryArgument], $siteID: String, $fixedOrder: Boolean) {
    entries(section: "product", storefrontId: $handles, siteId: $siteID, fixedOrder: $fixedOrder) {
        title
    }
}
```

Variables:
```
{
  "handles":  ["agropoli-blouse-floral-striped", "abigail-blouse-beige", "acineta-blouse-beige"],
  "fixedOrder": true
}
```

> If the `fixedOrder` is set to false, I have a result, but ordered like the panel listing. When set to `true`, I got an empty array (`entries: []`) and no error.

Is there a way to achieved that already?

p.s. the `product` section is a Structure (the client ask to have the manual order..)

**Comment by andris-sevcenko** [comment]
Currently, that's not possible. GraphQL relies on element queries to do the actual querying and in element queries the `fixedOrder` tells the query to order the results as specified with the `id` argument.

First there needs to be support for this in element queries.

**Comment by brandonkelly** [comment]
Fixed ordering can be expensive, especially for a column that isn’t a primary key, so probably not a good idea for us to expose it to custom fields somehow. It would be better for you to reorder the results from your JS code or whatever.

**Comment by jesuismaxime** [comment]
Yes I had to work around this matter last week. Using the values of by Entries field (and map only the `storefrontId`) I was able to order everything in my JS.

Thank you tho for the follow up!
