### ISSUE TITLE
Update page displays wrong versions - does not recognize forks

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#7098]
### Description
A few days ago the update page in Craft started to break. There are way too many pending updates.
Those are all my forks from other repos and my custom versioning is as the default one. Some of mine are even far ahead.

However: I see a huge list for them from Version 1.0.0 initial release - x.x.x latest update (that I already have).
I would really appreciate if you could revert your latest changes in your internal code so I don't see those pending changes anymore or provide me a way / an event to let me filter those updates because it is confusing. The update page is incredible long now.

### Steps to reproduce

1. Fork a plugin, install it from your fork
2. See in your tools -> updates all versions are listed there as pending change

### Additional info

- Craft version: 3.5.14

**Comment by brandonkelly** [comment]
Check `vendor/craftcms/plugins.php` – what is the `version` listed for one of the plugins affected by this?

**Comment by Anubarak** [comment]
As always there are only the branches of the repos such as `dev-master` but that was also the case before last week.

**Comment by brandonkelly** [comment]
I’m just not really sure what would have changed that could have affected this. Did you recently update to Composer 2? Perhaps there is a bug with how the version is recorded.

**Comment by Anubarak** [comment]
I didn't change anything, furthermore this happens on dev, staging and production and those are all separate servers with different configurations.
We use this version on our dev Server
```
Composer version 1.7.1 2018-08-07 09:39:23
```

Maybe it will disappear automatically after some time, I'll keep an eye on it and update this issue.
It's not a number 1 problem so if you didn't change this on intention you don't need to bother. Especially because it might not affect a lot of people

**Comment by brandonkelly** [comment]
I was able to reproduce when setting a plugin’s version constraint in composer.json to a branch name, e.g. `develop` → `"dev-develop"` (however not when the branch name looks like a version, e.g. `v2` → `"v2.x-dev"`).

Just pushed up https://github.com/pixelandtonic/craftnet/commit/d6c7eee35aaa29b2137c461360c6ce074520a820, which fixes it by not looking up available updates when a dev-stability version is currently installed.
