### ISSUE TITLE
Storing the users data with some special characters

### ISSUE THREAD

**Issue by mostafasoufi** [craftcms/cms#7103]
I'm trying to store the emails which have some special characters but either craftcms or yii tries to encode the strings, this is OK with Vanilla PHP

![Capture](https://user-images.githubusercontent.com/701520/98384006-e3239100-2055-11eb-8a73-d9348bf1d372.PNG)

Also, I put a log in `src/controllers/UsersController.php:1022` to get the `$_POST` to see posted data and still was encoded.

**Comment by brandonkelly** [comment]
I’m not seeing any issues saving a user account with the email `aaa@äö.ee`. Can you be more specific as to what you are entering and where it is getting encoded?

**Comment by mostafasoufi** [comment]
I tested with the front sign-up form, not admin and the username filled automatically by CraftCMS and is encoded. @brandonkelly

**Comment by brandonkelly** [comment]
Got it, thanks. We’ve fixed this for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.16 is out now with that fix.
