### ISSUE TITLE
Add Matrix content to newly created entry with EVENT_AFTER_SAVE

### ISSUE THREAD

**Issue by wallacio** [craftcms/cms#7108]
### Description
I have come to a total dead end in being able to add matrix content to a newly created Entry such that I'm convinced it's a bug, or there's insufficient documentation for me to understand how it works.

I've used Brandon's examples here (A) https://craftcms.stackexchange.com/a/21865/11180 and (B) https://github.com/craftcms/cms/issues/5717#issuecomment-591058311 as the basis for my logic.

Here's a summary of what I've tried, using example (B) - which is probably safest, since the editor chooses to add matrix content before first save but example (A) gives the same results. I'm not adding an matrix content in the CP before hitting 'save' in either case.

```
Event::on(
    Entry::class,
    Entry::EVENT_AFTER_SAVE,
    new EntryCreated
);
```
EntryCreated::_invoke:
```
    $entry = $event->sender;
    $isNew = $event->isNew;
    if (ElementHelper::isDraftOrRevision($entry)) {
        // don’t do anything with drafts or revisions
        return;
    }

    // If it's a new Entry, go see if we need to auto-attach any assets
    if ($isNew) {
        // now add content to the Entry
    }
```

If I use Brandon's examples as the basis for my logic:

```
$sortOrder = (clone $this->_entry->$matrixFieldHandle)->anyStatus()->ids();
foreach ($assetIds as $assetId) {
	$sortOrder[] = 'new:'.$idx;
	$block = [
		'type' => $matrixBlockTypeHandle,
		'enabled' => true,
		'collapsed' => false,
		'fields' => [
		   $matrixBlockFieldHandle => [$assetId] // This is an Asset field
		]
	];
	$blocks['new:'.$idx] = $block;
	$idx++;
}
$newMatrixData = [
	'sortOrder' => $sortOrder,
	'blocks' => $blocks
];
// attach the new matrix data to the matrix field
$this->_entry->setFieldValue($matrixFieldHandle, $newMatrixData ); 
// save some regular Asset fields
$this->_entry->setFieldValue($assetFieldHandle, [$someOtherAssetIds]); 

Craft::$app->elements->saveElement($this->_entry);
```
In this case, the matrix field isn't saved/created, yet the regular asset field is. Dumping `$this->_entry` prior to saveElement shows me that the data is all there. No errors are returned, no exceptions. No rows added to `matrixblocks`.

So Plan B: manually create the matrixblock and save it to the Entry.
```
foreach ($assetIds as $assetId) {
	$mb = new craft\elements\MatrixBlock();
	$mb->siteId = $this->_entry->siteId;
	$mb->fieldId = $matrixField->id;
	$mb->typeId = $matrixBlockType->id;
	$mb->ownerId = $this->_entry->id;
	$mb->sortOrder = $idx;
	Craft::info("Setting new MatrixBlock field ". $matrixBlockFieldHandle, __METHOD__);
	$mb->setFieldValue($matrixBlockFieldHandle, [$asset]);
	Craft::$app->elements->saveElement($mb);
	Craft::info("Saved new MatrixBlock with id: ". $mb->id . " to entry (owner) with id: ". $this->_entry->id . ", and uid " . $this->_entry->uid, __METHOD__);
	$blockIds[] = $mb->id;
}
// attach the new matrix blocks to the matrix field
$this->_entry->setFieldValue($fieldHandle, $blockIds);
// save some regular Asset fields
$this->_entry->setFieldValue($assetFieldHandle, [$someOtherAssetIds]); 
```
This gives some, if bizarre progress. The matrix asset block is created, has a field with the asset attached to it, yet the matrix data is associated with the PREVIOUS revision of the entry. The bizarre thing is that the regular asset field gets added to the entry correctly.  I have all manner of debug logging to show that the element ID and UID is consistent throughout the process, before calling `saveElement()`. 

Possibly important, additional info: this is multi-site, with the entry not set to propagate to other sites. The matrix block is set to not propagate either.

### Expected result:
Either:
- A matrix block is created with the correct data to the Entry passed by the EVENT_AFTER_SAVE event
- An error or exception to indicate that there's a problem with the data being saved.

### Actual result
Matrix block is not created when submitting as an array of data to setFieldValue(), or a manually created MatrixBlock is associated with the wrong revision.

### Additional info

- Craft version: Craft Pro 3.5.15.1
- PHP version: 7.2.4
- Database driver & version: MySQL 5.7.21

**Comment by brandonkelly** [comment]
Kinda hard to help without having the site running locally. Can you please send your Composer files, database backup, and custom module code over to support@craftcms.com?

**Comment by monachilada** [comment]
I believe the fix for this introduced another bug for plugins or modules that might use `saveElement` in EVENT_AFTER_SAVE. See here: https://github.com/craftcms/cms/issues/7199
