### ISSUE TITLE
Ability to access reverse relations within entry query in GQL

### ISSUE THREAD

**Issue by andrewfairlie** [craftcms/cms#7110]
It would be really useful if when querying entries in GraphQL you could get _reverse_ related elements to that entry, which would avoid you having to do multiple GraphQL calls of "get the entry ID, and then run another GraphQL query with `relatedTo()` because this can quickly add up and become clunky. 

## Original comment from other thread

Just a thought, and apologies if this was covered in other thoughts above and I misunderstood, would a good syntax for this be something like `relatedEntries`, `relatedAssets` etc. which behave like a normal `entries` / `asset` loop but with the `relatedTo` pre-populated with the current entry. So you could do things like this very weird, but hopefully useful example...?

```
entry(section:"offices",slug:"london"){
   title,
   id,
   ... on offices_offices_entry {
      peopleInThisOffice: relatedEntries(section:"people"){
        title
      }
      facilitiesInThisOffice: relatedEntries(section:"facilities"){
        title
      }
      imagesTaggedInThisOffice: relatedAssets(source:"images"){
        title
      }
   }
}
```

_Originally posted by @andrewfairlie in https://github.com/craftcms/cms/issues/5143#issuecomment-721702205_

**Comment by andris-sevcenko** [comment]
This has been added for Craft 3.6

**Comment by andris-sevcenko** [comment]
Well, in its own branch for now.

**Comment by brandonkelly** [comment]
Merged now. Note that it’s `relatedToEntries`, etc., not `relatedEntries`.

**Comment by brandonkelly** [comment]
Craft 3.6 RC2 is out now with these new GraphQL arguments.

**Comment by brandonkelly** [comment]
Craft 3.6 has now been officially released ✨

**Comment by membla** [comment]
Just had a conversation on Discord with @andris-sevcenko on this – the actual issue at hand here is not resolved and even if it may not be feasible to do it in the GraphQL API without changes to the Element Query API or Element itself I think the issue should be reopened because the use case is very valid (and well explained in the original post above).

**Comment by brandonkelly** [comment]
Whoops, you’re right @membla. Guess we were on a different brainwave. We’re considering how to best address this.
