### ISSUE TITLE
Asset Indexes utility progress bar over completion modal

### ISSUE THREAD

**Issue by nstCactus** [craftcms/cms#7111]
### Description

The Asset Indexes utility progress bar (`.progressbar`) has a higher z-index than the success modal (`.confirmmodal`): 1000 vs 100

### Steps to reproduce

1. Go to **Utilities** / **Asset indexes**
2. Reindex all assets
3. See the progress bar floating over the modal

### Additional info

- Craft version: 3.5.15.1
- PHP version: 7.4
- Database driver & version: not relevant
- Plugins & versions: not relevant
<img width="1025" alt="Screenshot 2020-11-09 at 18 01 55" src="https://user-images.githubusercontent.com/353843/98573610-5841d100-22b7-11eb-934e-72508ded21bd.png">

**Comment by brandonkelly** [comment]
@andris-sevcenko Guessing this was caused by 5dfedf145dc1ef6af6cc57e0bcfcbe9dab3ee075.

**Comment by andris-sevcenko** [comment]
Thanks! Fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 3.5.16 is out now with that fix.
