### ISSUE TITLE
Add action/csrf endpoint

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#7113]
### Description

It would be great to have an action/csrf endpoint that returns a token for the user.

Blitz implements this: https://putyourlightson.com/plugins/blitz#csrf-controller-actions I believe solspace has a version as well. I've written a custom endpoint as a module.

We use this endpoint to create a CSRF token when running tests with Cypress that require a logged in session (login via an ajax post).

I'm thinking if the accept header is `application/json` you could return both the token and param (like blitz). If the accept header is not set (ie text/html fallback) it could just be the token.

Something as simple as:

```php
<?php

namespace craft\controllers;

class CsrfController extends Controller
{
    protected $allowAnonymous = true;

    public function actionIndex(): Response
    {
        $csrfToken = Craft::$app->getRequest()->getCsrfToken();
        $csrfTokenName = Craft::$app->getConfig()->getGeneral()->csrfTokenName;

        if (Craft::$app->getRequest()->getAcceptsJson()) {
            return $this->asJson(
                [
                    'name' => $csrfTokenName,
                    'value' => $csrfToken,
                ]
            );
        }

        return $this->asRaw($csrfToken);
    }
}
```

**Comment by leevigraham** [comment]
ping @putyourlightson thoughts?

**Comment by bencroker** [comment]
Sounds good, here's how Blitz does it:
https://github.com/putyourlightson/craft-blitz/blob/develop/src/controllers/CsrfController.php

**Comment by brandonkelly** [comment]
The `users/session-info` action includes a `csrfTokenValue` key in its JSON response :)

**Comment by leevigraham** [comment]
The what now!
