### ISSUE TITLE
Configurable aspect ratios for the image editor 

### ISSUE THREAD

**Issue by ursbraem** [craftcms/cms#7117]
While craft allows very granular "client-proofing" on field level, when it comes to image editing, that stops. 

Use case: say you have a nonstandard aspect ratio for all images on your site, let's say 10:7. It would be helpful to be able to configure the image editor so clients are only able to crop images 10:7

[discussed with Brad]

**Comment by andris-sevcenko** [comment]
In that case I would probably recommend using the [imageEditorRatios config setting](https://craftcms.com/docs/3.x/config/config-settings.html#imageeditorratios) :)

**Comment by ursbraem** [comment]
Thanks @andris-sevcenko – it works!
