### ISSUE TITLE
DB Backup fails when using unixSocket connection

### ISSUE THREAD

**Issue by bphippen** [craftcms/cms#7121]
### Description
Backup utility is failing when using a unixSocket db connection locally. Here is the error in the logs: mysqldump: [ERROR] mysqldump: Empty value for 'port' specified. in UtilitiesController.php:345

I went through and tried to find what the issue is and I found when I went to controllers > db > mysql > Schema.php on lines 381 and 382 it seems to be creating an empty string even though I am not using port or host for the db connection.

When I removed those lines (to test if that was the issue), the db backup utility worked without error.

### Steps to reproduce

1. Connect db via unix socket
2. Try to do a mysql backup

### Additional info

- Craft version: 3.5.12.1
- PHP version: 7.4.1
- Database driver & version: MySQL 5.7.28
- Plugins & versions:

**Comment by angrybrad** [comment]
Thanks for reporting! Fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#3d494ea694702ecfb2ec83c67f3bf0132370e1ea",
  "...": "..."
}
```

Then run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.5.16 is out now with that fix.
