### ISSUE TITLE
Deprecation Warnings, Looping through the `table` field queries directly has been deprecated?

### ISSUE THREAD

**Issue by dande-sun** [craftcms/cms#7122]
### Description
We looping a field on the twig template, it is table type. Then the craft cms output `Deprecation Warnings`, The output: `Looping through element queries directly has been deprecated. Use the all() function to fetch the query results before looping over them.`, But the table field can not use the all() function, It will output 500 error.

### Steps to reproduce
1. Create a table field.
2. Looping the table field on the twig template.
3. If use the all() function, Will be 500 error, else output massage `Deprecation Warnings`.

### Additional info

- Craft version: 3.5.15.1
- PHP version: 7.4
- Database driver & version: MySQL 5.7
- Plugins & versions:

**Comment by brandonkelly** [comment]
This must be coming from a different part of your template, rather than the table data loop. If you send a database backup, your Composer files, and templates over to support@craftcms.com, we can help identify where it’s coming from.
