### ISSUE TITLE
Add field to the existing block type of Matrix field in the migration 

### ISSUE THREAD

**Issue by mmikhalko** [craftcms/cms#7123]
### Description

When I add a new field to Matrix Block type it does not work in the migration script. 

### Steps to reproduce

1. Create the new migration 
2. Add the example script below  

    ```php
    <?php
    
    // ...
    
    public function safeUp()
    {
        // Get the matrix field
        $exampleContents = Craft::$app->fields->getFieldByHandle("exampleContents");

        // Get the block types
        $blockTypes = $exampleContents->getBlockTypes();

        // Find the one with `justText` as the handle
        foreach ($blockTypes as $blockType) {
            if ($blockType->handle == "justText") {
                // Get all the fields
                $fields = $blockType->getFields();

                // Add a new field to the fields array
                array_push(
                    $fields,

                    // Dropdown color select
                    new \craft\fields\Dropdown([
                        "name" => "Text Color",
                        "handle" => "textColor",
                        "instructions" => "Choose one of three amazing text colors",
                        "options" => [
                            [
                                "label" => "Red",
                                "value" => "#ff0000",
                                "default" => 1,
                            ], [
                                "label" => "Green",
                                "value" => "#00ff00",
                                "default" => "",
                            ], [
                                "label" => "Blue",
                                "value" => "#0000ff",
                                "default" => "",
                            ],
                        ],
                    ])
                );

                // And finally set the fields and then the blocktype
                $blockType->setFields($fields);
                return (Craft::$app->matrix->saveBlockType($blockType));
            }
        }
    }
    ```

### Additional info

- Craft version: 3.5.14
- PHP version: 7.3.15
- Database driver & version: MySQL 5.6.39
- Plugins & versions:

**Comment by brandonkelly** [comment]
You need to add the field to the block type’s field layout.

Here’s the proper way to do it in 3.5+:

```php
// Get the field layout
$fieldLayout = $blockType->getFieldLayout();

// Get the first tab
$tab = $fieldLayout->getTabs()[0];

// Add a new field to the elements array
$field = new \craft\fields\Dropdown([
    'name' => 'Text Color',
    'handle' => 'textColor',
    'instructions' => 'Choose one of three amazing text colors',
    'options' => [
        [
            'label' => 'Red',
            'value' => '#ff0000',
            'default' => 1,
        ], [
            'label' => 'Green',
            'value' => '#00ff00',
            'default' => '',
        ], [
            'label' => 'Blue',
            'value' => '#0000ff',
            'default' => '',
        ],
    ],
]);

$tab->elements[] = new \craft\fieldlayoutelements\CustomField($field);

// Save the block type
return \Craft::$app->matrix->saveBlockType($blockType);
```

**Comment by mmikhalko** [comment]
> You need to add the field to the block type’s field layout.
> 
> Here’s the proper way to do it in 3.5+:
> 
> ```
> // Get the field layout
> $fieldLayout = $blockType->getFieldLayout();
> 
> // Get the first tab
> $tab = $fieldLayout->getTabs()[0];
> 
> // Add a new field to the elements array
> $field = new \craft\fields\Dropdown([
>     'name' => 'Text Color',
>     'handle' => 'textColor',
>     'instructions' => 'Choose one of three amazing text colors',
>     'options' => [
>         [
>             'label' => 'Red',
>             'value' => '#ff0000',
>             'default' => 1,
>         ], [
>             'label' => 'Green',
>             'value' => '#00ff00',
>             'default' => '',
>         ], [
>             'label' => 'Blue',
>             'value' => '#0000ff',
>             'default' => '',
>         ],
>     ],
> ]);
> 
> $tab->elements[] = new \craft\fieldlayoutelements\CustomField($field);
> 
> // Save the block type
> return \Craft::$app->matrix->saveBlockType($blockType);
> ```

I've check your solution. 

`Exception: Return value of craft\fieldlayoutelements\CustomField::getFieldUid() must be of the type string, null returned (/app/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php:98)
#0 /app/vendor/yiisoft/yii2/base/BaseObject.php(136): craft\fieldlayoutelements\CustomField->getFieldUid()
#1 /app/vendor/yiisoft/yii2/base/ArrayableTrait.php(126): yii\base\BaseObject->__get('fieldUid')
#2 /app/vendor/craftcms/cms/src/models/FieldLayoutTab.php(189): craft\base\FieldLayoutElement->toArray()
#3 /app/vendor/craftcms/cms/src/models/FieldLayoutTab.php(175): craft\models\FieldLayoutTab->getElementConfigs()
#4 /app/vendor/craftcms/cms/src/models/FieldLayout.php(369): craft\models\FieldLayoutTab->getConfig()
#5 /app/vendor/craftcms/cms/src/models/MatrixBlockType.php(171): craft\models\FieldLayout->getConfig()
#6 /app/vendor/craftcms/cms/src/services/Matrix.php(244): craft\models\MatrixBlockType->getConfig()
#7 /app/migrations/m201111_103425_migration_add_switcher_cta_field.php(96): craft\services\Matrix->saveBlockType(Object(craft\models\MatrixBlockType))
#8 /app/vendor/craftcms/cms/src/db/Migration.php(52): craft\contentmigrations\m201111_103425_migration_add_switcher_cta_field->safeUp()
#9 /app/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(727): craft\db\Migration->up()
#10 /app/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(202): yii\console\controllers\BaseMigrateController->migrateUp('m201111_103425_...')
#11 /app/vendor/craftcms/cms/src/console/controllers/MigrateController.php(384): yii\console\controllers\BaseMigrateController->actionUp(0)
#12 [internal function]: craft\console\controllers\MigrateController->actionUp(0)
#13 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /app/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#15 /app/vendor/yiisoft/yii2/console/Controller.php(179): yii\base\Controller->runAction('up', Array)
#16 /app/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('up', Array)
#17 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/up', Array)
#18 /app/vendor/craftcms/cms/src/console/Application.php(88): yii\console\Application->runAction('migrate/up', Array)
#19 /app/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/up', Array)
#20 /app/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#21 /app/craft(22): yii\base\Application->run()
#22 {main}`


I guess it has to add code 
`"uid" => craft\helpers\StringHelper::UUID()`

**Comment by brandonkelly** [comment]
Sorry, safer to resave the entire Matrix field rather than just the block type. I’ve updated my example code above.

**Comment by mmikhalko** [comment]
> Sorry, safer to resave the entire Matrix field rather than just the block type. I’ve updated my example code above.

Thanks a lot!
