### ISSUE TITLE
allow custom number of rows for textareas in editableTable 

### ISSUE THREAD

**Issue by aloco** [craftcms/cms#7124]
### Description

Hi, we would like to set a custom row number for textareas when using editableTable. Seems like this is currently hardcoded and not configurable when using editableTable. It would be nice if we could set this as value in the `cols` configuration besides the `type`. 

eg.
```
{% set cols = cols|merge({
    colName: {
	type: 'textarea',
        rows: '3',
        ...
    }
}) %}
```
https://github.com/craftcms/cms/blob/3.6/src/templates/_includes/forms/editableTable.html#L133

**Comment by brandonkelly** [comment]
Just made that possible for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.16 is out now with that change.
