### ISSUE TITLE
Rebuild Project Config utility and allowAdminChanges config

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#7125]
### Description

Shouldn’t the Rebuild Config utility only be available when `allowAdminChanges` is enabled?

### Additional info

- Craft version: 3.5.12.1

**Comment by brandonkelly** [comment]
Good call, thanks for pointing that out. Fixed for the next release.

**Comment by carlcs** [comment]
I have yet used the Discard Changes button. Does this also make changes to the filesystem and therefore should be unavailable as well?

**Comment by brandonkelly** [comment]
Yep good point.

**Comment by brandonkelly** [comment]
Craft 3.5.16 is out now with that change.
