### ISSUE TITLE
Allow anonymous access to asset.getThumb()

### ISSUE THREAD

**Issue by dmatthams** [craftcms/cms#7126]
### Description

The depreciated asset action `actionGenerateThumb` allows anonymous access but not `getThumb`, I have a case where it makes sense to just use Craft's thumbnails on the front-end (A media library that outputs the contents of a volume).

**Comment by brandonkelly** [comment]
Thumbs are only generated for the control panel. You should use image transforms for the front-end.

**Comment by dmatthams** [comment]
What I'm building is a simple control panel on the front-end where it would be appropriate to pull in Craft's thumbs, including the file icons (pdf, zip) so there's some semblance with the back-end. It's a very edge-case I guess so will just duplicate the code 🙂

**Comment by andris-sevcenko** [comment]
@dmatthams please keep in mind that having a publicly accessible endpoint that takes arbitrary dimensions as parameters and uses them to generate an image is a rather nasty security oversight, that can lead to DOS attacks with very little effort.

This was one of the reasons why it is no longer allowed anonymously.

By all means, feel free to implement the same functionality, but do add some security layer on top of it.

**Comment by dmatthams** [comment]
Yes fair point @andris-sevcenko ! I knew there'd be a good reason. I will create something that will generate pre-defined sizes, thanks 🙂

**Comment by brandonkelly** [comment]
> What I'm building is a simple control panel on the front-end where

It’s still a separate front-end, regardless of how closely it may resemble Craft’s control panel.

**Comment by dmatthams** [comment]
@brandonkelly It doesn't resemble it at all, it's just set up to be extended by anyone – so I thought it would be nice that if for example someone extended Craft to support thumbnail generation for PDF's or videos, that they wouldn't also need to add support on front-end to show these.

I can see probably nobody else needing this functionality so understand why it's not there 😄 will just make a custom controller that generates a single size, that should work?

**Comment by brandonkelly** [comment]
Sure, or use transforms :)
