### ISSUE TITLE
Inconsistent type for IDs in GraphQL schema

### ISSUE THREAD

**Issue by ThijmenDeValk** [craftcms/cms#7128]
### Description

We're looking at adding middleware between the GraphQL API and our frontend. That resulted in an error due to a type mismatch.

The IDs for entries are returned as strings. However, when then using those IDs in a query, for example in `relatedTo`, an integer is expected. This requires a conversion from string to integer every time the results from a GraphQL query are used to make another one. Not a huge problem, but not super pretty either.

When directly connecting to the GraphQL endpoint, this actually works fine. However, once you start using something like Apollo Federation or even GraphiQL, the middleware does get strict about this type mismatch and throws an error.

This could be solved by returning the ID as an integer or tweaking the type expected for fields like `relatedTo` (maybe something like `QueryArgument`?).

### Steps to reproduce

1. Request `id` from entry in GraphiQL:
```graphql
query GetFirstEntry {
  entries(limit: 1) {
    id
  }
}
```
2. Use the exact response for `id` to try and make a request in GraphiQL for related entries:
```graphql
query GetRelatedEntry {
  entries(relatedTo: "276") {
    id
  }
}
```
3. GraphiQL will not let you make the request: it expects type `[int]` for `relatedTo`.

### Additional info

- Craft version: 3.5.15.1
- PHP version: 7.4.8
- Database driver & version: MySQL 8.0.15
- Plugins & versions: _lots, but none that are related to this_

**Comment by andris-sevcenko** [comment]
Thanks for reporting that! For the next release, I changed the type of `relatedTo` and `relatedToAll` to be `[QueryArgument]`.

It's more consistent, as [per the GraphQL Specification](https://spec.graphql.org/June2018/#sec-ID), the `ID` should serialize the same way a string does.

**Comment by brandonkelly** [comment]
Craft 3.5.16 is out now with that fix.
