### ISSUE TITLE
JavaScript MatrixInput "blockAdded" fired before block is actually added 

### ISSUE THREAD

**Issue by timmyomahony** [craftcms/cms#7130]
I added an issue previously regarding the MatrixInput `blockDeleted` event firing before the block has actually been deleted:

https://github.com/craftcms/cms/issues/7064

I just noticed that the same issue applies to the `blockAdded` event. 

You can see the event here:

https://github.com/craftcms/cms/blob/e851b77eac7b5783b750bb17f18c3ab598c40771/src/web/assets/matrix/src/MatrixInput.js#L281

fires before the animation runs and actually creates the new block:

https://github.com/craftcms/cms/blob/e851b77eac7b5783b750bb17f18c3ab598c40771/src/web/assets/matrix/src/MatrixInput.js#L293

**Comment by brandonkelly** [comment]
It’s added to the DOM, just not fully initialized in JS yet:

https://github.com/craftcms/cms/blob/523a2d915ec328d832bd2cf62df695a1eafb3ab7/src/web/assets/matrix/src/MatrixInput.js#L268-L283

Is that a problem for you?

**Comment by timmyomahony** [comment]
Hi @brandonkelly no it's not a huge problem, I've been able to get my use-case working with just the DOM element. Just my intuition when coming to it was to expect the JS object to be created and passed as opposed to the DOM element (as you can get access to the DOM element via the JS object). But it's not a big deal - happy for it to be closed
