### ISSUE TITLE
requireAjaxRequest 403 error when logged in

### ISSUE THREAD

**Issue by cjhill00** [craftcms/cms#7132]
### Description
In my custom plugin, I have a "savePost" action in my controller that saves some form data to the DB. At the top of that action function, I am using the craft `requireAjaxRequest()` method because all requests to this endpoint will come via AJAX. The issue that I am having is that whenever I am logged into the admin area (backend) and I submit the form on the frontend, I get a 403 error message about 20% of the time. However, when I am logged out of the admin area and submit the form, it seems to work just fine. Any idea what the issue is?

### Steps to reproduce

1. Create a custom plugin
2. In one of your controllers, create an action that utilized the `requireAjaxRequest()` method
3. In the frontend, create a form that makes a request to this endpoint, sending some data.
4. Submit the form while logged in (Sssue occurs about 20% of the time)
5. Submit the form while logged out (Seems to work just fine)

### Additional info

- Craft version: 2.6.2999
- PHP version: 7.1.33
- Database driver & version:
- Plugins & versions: Custom Plugin

**Comment by brandonkelly** [comment]
`requireAjaxRequest()` will give you a 400 error, not 403, so it must be something else. Strange that it’s only happening 20% of the time. Check `craft/storage/runtime/logs/` and see if you can find any mention of the error. If so that should include a stack trace that will shed light on what’s going on.

**Comment by cjhill00** [comment]
@brandonkelly Ok, yeah... Looks like the 403 error is coming from the Ajax request and not the plugin controller. For some reason when I pass this data in my request `{ comment: 'test' }`, the request goes through, but if I pass 
`{ comment: '--9-' }`  I get a 403 error. Strange.

**Comment by brandonkelly** [comment]
Huh, no idea what to make of that. If possible, try stepping through the request with Xdebug ([Nitro](https://getnitro.sh/) makes that pretty easy) and see if you can figure out why.

**Comment by cjhill00** [comment]
@brandonkelly I was able to figure it out. It was an issue with our dev environment. The server was blocking certain requests.

**Comment by brandonkelly** [comment]
Ah cool, glad you got it sorted!
