### ISSUE TITLE
Site switching not always persistent and can be confusing

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#7133]
### Description
Recently, changes have been made to attempt to keep the site set to the last version a user had switched to when navigating the CP.

One outlier that I found was when switching a site from within an entry. This results in the CP using whatever site was selected upon initially viewing the entry after a user goes back to view other entries, globals, or whatever.

In my opinion, switching the site should always save the setting. If it shouldn't, the intended functionality should be clearly outlined so we can explain it to our users to avoid confusion.

Ref: https://github.com/craftcms/cms/issues/2779

### Additional info

- Craft version: 3.5.14

**Comment by mmikkel** [comment]
I think the current behaviour is fine.

The site switchers in element indexes (and global sets) are typically perceived by authors as "global" site switchers – so it makes sense that changing the site here, also changes the "globally" selected site throughout the CP.

On the other hand, the site switcher in the entry edit form is used to edit/(pre)view a particular entry across different sites, independently of the currently selected site in the CP. The context here is a specific element, and I don't think most authors would expect _this_ site switcher to also change the "globally" selected site. In fact, I know that it would really mess with a lot of authors' workflow if it did.

One size doesn't necessarily fit all, though - potentially this is something that could be made configurable?

(In my opinion what _would_ be helpful in making site switchers' behaviour less confusing, would be to replace the element index and global set site switchers with an actual global site switcher)
