### ISSUE TITLE
FR: custom names for focal point coordinates.

### ISSUE THREAD

**Issue by bartrylant** [craftcms/cms#7134]
### Description

It would be cool if there would be an option to not only return focal point values as 0.5 or 50%, but e.g. also like "top", "left", ... A lot of image conversion services use those values:

center, top, left, bottom, right, top_left, top_right, bottom_left and bottom_right

So it would be nice that if a focal point in craft is e.g. 0.8 x 0.2 it could be returned as "top_right".

**Comment by brandonkelly** [comment]
To be clear are you referring to values that `craft\elements\Asset::setFocalPoint()` should accept?

**Comment by bartrylant** [comment]
I'm not talking about setting the focal point, but getting values of the focal point on template level. So setting a focal point would still work as it does now (just dragging the foal point on the right place in the control panel). However, I would like to be able to do something like this:

```
{% set fp = asset.getFocalPoint('asText') %}
```

that would e.g. return `top_right` when `0.66 < x < 1` and `0 < y < 0.33`. So I could use it like this:

`https://ik.imagekit.io/demo/img/plant.jpeg?tr=w-300,h-300,fo-{{ fp }}`

Yes, I could write a macro to do the math. I was just thinking it would be a nice default feature for working with focal points since a lot of image services (like imagekit, cloudinary, aws Serverless Image Handler, …) don't work with explicit values (0.2, 0.6) but with those jeywords (top, center, bottom, …)

**Comment by brandonkelly** [comment]
Ah ok. That would be a lossy representation of the focal point, so I think not. Easy enough to do in a macro, as you said.
