### ISSUE TITLE
Non-Translatable Asset Titles

### ISSUE THREAD

**Issue by samlising** [craftcms/cms#7135]
Non-Translatable titles for entries in Sections is currently possible, but Asset titles do not currently have the same functionality. It would be useful to port this same functionality to Assets. 

If a site is currently designed to be multilingual, but wants to use the same assets for all sites, having Title fields that are multilingual can be extremely confusing for users. Uploading a file with through an asset field creates the same title for all sites using its file name. However, when editing assets after the initial upload, if a user changes the title in one language the titles for the same file will be different for other languages.

This may cause some problems down stream when searching for assets, as the titles may be different in one language versus another. Over a long period of time and with a lot of assets, this can get very messy. Requiring users to change titles for all languages in order to have the same title in all languages is not a realistic solution. If sharing one asset across multiple-sites is possible, allowing the same behavior for titles should be possible, the title of the asset should be shared across all sites as well.

It would be useful and more consistent if the Asset titles could share the same functionality and options as Section titles.

**Comment by brandonkelly** [comment]
Just added this for the upcoming 3.6 release!

**Comment by samlising** [comment]
That's Awesome! Thanks Brandon

**Comment by brandonkelly** [comment]
Craft 3.6 has now been officially released ✨
