### ISSUE TITLE
Multiple URI created for one entry when Entry URI Format is changed for a channel

### ISSUE THREAD

**Issue by adamseabrook** [craftcms/cms#7137]
### Description
We added another site for Spanish language and then enabled the site inside our existing `guides` channel and set the entry uri format to `guias/{slug}` (note the lack of accent on the `i`) so the entries would look like `https://www.example.com/es/guias/something`

We decided to add in accents so we updated the Entry URI Format for the channel to `guías/{slug}` and entries now worked on `https://www.example.com/es/guías/something`

The issue is the old URI still works so the page is accessible on both:
`https://www.example.com/es/guias/something`
`https://www.example.com/es/guías/something`

We tried resaving the entry, disabling and reenabling, changing the entry URI and resaving but the old URI is still visible. We can't use Retour to redirect the old url to the new one as it does not cause a 404 that Retour can grab.

### Steps to reproduce
1. Create an entry in a channel
2. Save it
3. Change the Entry URI Format for the channel
4. Entry is now accessible on the old and new entry uri formats.

### Additional info

- Craft version:
Craft CMS 3.5.14
- PHP version:
7.4.8
- Database driver & version:
MySQL 5.5.5
- Plugins & versions:
Anchors	2.2.0
Architect	2.3.3
Feed Me	4.2.4
Field Manager	2.2.1
Google Cloud Storage	1.4.0
Linkit	1.1.11
Minify	1.2.10
Navigation	1.4.1
Position Fieldtype	1.0.16
Postmark	2.0.2
Retour	3.1.42
SEOmatic	3.3.22
Super Table	2.6.3

**Comment by brandonkelly** [comment]
Entries are only able to have a single URI per site, so this isn’t possible. Are you sure the old URI isn’t just already redirecting to the new URI? Retour creates redirects automatically for you whenever an entry’s URI changes.

**Comment by adamseabrook** [comment]
I did think that was the case but I deleted every redirect in Retour and it is still happening. Both urls are 200 response code so no redirect is happening. Here is a live example.
```
curl --head -L https://www.namesnack.com/es/guias/nombres-para-empresas-de-hierbas-y-especias
HTTP/2 200 
content-type: text/html; charset=UTF-8
strict-transport-security: max-age=15724800
access-control-allow-origin: *
accept-ranges: bytes
date: Tue, 17 Nov 2020 00:10:38 GMT
age: 0
x-served-by: cache-mdw17344-MDW, cache-syd10141-SYD
x-cache: MISS, MISS
x-cache-hits: 0, 0
x-timer: S1605571838.051291,VS0,VE875
vary: Accept-Encoding
cache-control: public, immutable, max-age=31557600
x-content-type-options: nosniff
referer-policy: strict-origin-when-cross-origin
content-length: 27729
```
```
curl --head -L https://www.namesnack.com/es/gu%C3%ADas/nombres-para-empresas-de-hierbas-y-especias
HTTP/2 200 
content-type: text/html; charset=UTF-8
strict-transport-security: max-age=15724800
access-control-allow-origin: *
accept-ranges: bytes
date: Tue, 17 Nov 2020 00:11:04 GMT
age: 0
x-served-by: cache-mdw17335-MDW, cache-syd10134-SYD
x-cache: MISS, MISS
x-cache-hits: 0, 0
x-timer: S1605571863.137982,VS0,VE901
vary: Accept-Encoding
cache-control: public, immutable, max-age=31557600
x-content-type-options: nosniff
referer-policy: strict-origin-when-cross-origin
content-length: 27732
```
Searching inside Craft there is only the one entry with the new correct entry URI format with the accent:
![image](https://user-images.githubusercontent.com/368555/99323178-c2fd9880-28c5-11eb-89e4-b85906b3588a.png)

The product site has Fastly infront of it so I also checked the production server directly to rule out caching and still have to two URI.

**Comment by brandonkelly** [comment]
Try running the following SQL query:

```sql
SELECT `e`.`id`, `es`.`siteId`, `es`.`uri`
FROM `elements_sites` `es`
INNER JOIN `elements` `e` ON `e`.`id` = `es`.`elementId`
WHERE `e`.`draftId` IS NULL
AND `e`.`revisionId` IS NULL
AND `es`.`uri` = 'guias/nombres-para-empresas-de-hierbas-y-especias'
```

Do you get a result? If so please copy the `id` and go to `/admin/edit/<the_id>` and see where it takes you.

**Comment by adamseabrook** [comment]
One Entry appears with an ID of 1211203 going to the admin/edit url shows the edit entry correctly.
![image](https://user-images.githubusercontent.com/368555/99329967-7c169f80-28d3-11eb-97da-31003c480634.png)

I had to modify the command a bit to:
```
SELECT `e`.`id`, `es`.`siteId`, `es`.`uri`
FROM `craft_elements_sites` `es`
INNER JOIN `craft_elements` `e` ON `e`.`id` = `es`.`elementId`
WHERE `e`.`draftId` IS NULL
AND `e`.`revisionId` IS NULL
AND `es`.`uri` = 'guias/nombres-para-empresas-de-hierbas-y-especias'
```

I ran it again with the accent and got the same ID:
```
SELECT `e`.`id`, `es`.`siteId`, `es`.`uri`
FROM `craft_elements_sites` `es`
INNER JOIN `craft_elements` `e` ON `e`.`id` = `es`.`elementId`
WHERE `e`.`draftId` IS NULL
AND `e`.`revisionId` IS NULL
AND `es`.`uri` = 'guías/nombres-para-empresas-de-hierbas-y-especias'
```

**Comment by adamseabrook** [comment]
Digging into `craft_elements_sites` I can see these with `hierbas` in the url. I don't really know what this is though but just pasting FYI.
![image](https://user-images.githubusercontent.com/368555/99331629-14ad1f80-28d4-11eb-9247-87dd9ea8bde0.png)

**Comment by adamseabrook** [comment]
Might not be anything to do with changing the Entry URI Format.
`https://www.namesnack.com/guídes/asian-business-names` that url works with the accented `i` when it should throw a 404 so maybe it is an encoding/collation issue somewhere where it sees `i` and `í` the same.

**Comment by angrybrad** [comment]
@adamseabrook yeah, i think this will come down to a MySQL encoding/collation issue. What are those set to for both the `craft_element_sites` table and the `uri` column?

**Comment by mattgrayisok** [comment]
Excuse the intrusion. The site is hosted on Servd so I'm interested in this too!

@angrybrad The collation for the table is `utf8_general_ci` and the columns don't have explicit collations set so will be inheriting that.

As the collation is case insensitive it's also accent insensitive hence the potentially inappropriate matches.

Does Craft explicitly set the desired collations on each individual table during install? Using a `_ci` collation is desirable for the majority of cases to allow case insensitive matching, but it seems as though `utf8[mb4]_bin` would potentially be better specifically for the `craft_elements_sites` table.

We can achieve this easily in this particular case by running `ALTER TABLE craft_elements_sites CONVERT TO CHARACTER SET utf8mb4 COLLATE 'utf8mb4_bin';` which I've tested and does indeed fix the URL matching issue.

I can't imagine this is particularly common practice though, and I also notice that https://craftcms.com/fe%C3%A1tures doesn't have the same issue. Did you guys set your collation on that table manually? Or perhaps this is something that has been resolved with MySQL8's new collations and you're using that?

**Comment by adamseabrook** [comment]
As a temporary fix I have Fastly returning a 404 for any of the old non-accented links that have `/guias/` in them on https://www.namesnack.com

Longer term fix would be whatever collation you end up deciding is the correct way to do it.

The main issue we want to fix with this is making sure google cant crawl both versions of the URL. When we switched from `/guias/` to `/guías/` google is ignoring the new accented path and still picking `/guias/` as the canonical in Search Console.

**Comment by angrybrad** [comment]
@mattgrayisok @adamseabrook 

> I also notice that https://craftcms.com/fe%C3%A1tures doesn't have the same issue. Did you guys set your collation on that table manually?

We're using PostgreSQL, which, thankfully, avoids a lot of MySQL wonkiness like this.

> Does Craft explicitly set the desired collations on each individual table during install?

No. In Craft 2, we used to have default `charset` and `collation` settings you could set in `config/db.php` and whatever was set there, Craft would use to create any tables/columns with (overwriting whatever the default charset/collation was set on the database).

We removed those settings in Craft 3 and exclusively go with whatever the default charset/collation of the database is (typically `utf8_general_ci`).

> but it seems as though utf8[mb4]_bin would potentially be better specifically for the craft_elements_sites table.

Possibly, but that wouldn't solve searching across fields that store content (in the content table, Matrix/Super Table tables, etc.) which would run into the same issue.

When this has come up in the past, we usually recommend that people tweak the collations on columns to their specific use-cases, exactly like what you've discovered.

FWIW, I vaguely recall us looking at explicitly setting the defaults to something like `utf8mb4` for everything, but that caused other problems like us running into index key length limitations.

Going to go ahead and close this out as we've discovered the underlying cause, but happy to continue the discussion.
