### ISSUE TITLE
Only entries from primary site are resaved.

### ISSUE THREAD

**Issue by Bavixke** [craftcms/cms#7145]
### Description

Entries that are not displayed on the primary site are not resaved.
Changing 'Entry URI Format' will not update the url as well because of this.

### Steps to reproduce

1. Create multiple sites
2. Create a section (e.g. a structure), toggle off the primary site.
3. Create entries for you new section
4. Run `./craft resave/entries` or change 'Entry URI Format'

### Additional info

- Craft version: Craft Pro 3.5.15.1
- PHP version: 7.4.11
- Database driver & version: MySQL 8.0.21

**Comment by brandonkelly** [comment]
You can specify which site to fetch elements from using the `--site` option.

```bash
php craft resave/entries --site=siteB
```

**Comment by Bavixke** [comment]
@brandonkelly What about changing the 'Entry URI Format' issue? I guess you can't specify this in the CMS?

It's exactly the same 'problem'. Changing the 'Entry URI Format' of a section will not update the url's of the sites if the primary site is not toggled.

**Comment by brandonkelly** [comment]
You positive about that? It’s set up to query existing entries across all enabled sites for the section:

https://github.com/craftcms/cms/blob/523a2d915ec328d832bd2cf62df695a1eafb3ab7/src/services/Sections.php#L720

**Comment by Bavixke** [comment]
My explanation may not have been clear enough. When I change something in the section the url is changed incorrectly.
https://imgur.com/V3dshqc

If the primary site is not the current site, the conditional part will be removed if I change the 'Entry URI Format'.
I guess I'll have to add .site() to the query. My bad.

**Comment by brandonkelly** [comment]
Yeah maybe `.siteId(object.siteId)`.
