### ISSUE TITLE
Plain text is not being validated

### ISSUE THREAD

**Issue by robinbraibant** [craftcms/cms#7147]
### Description
Hello,
I have created a section with a plain text field that is required. When I leave it blank and save it in the control panel, it throws an error that the field cannot be empty. In the frontend users can use this field to enter some text. When they leave it blank, the entry gets saved and no error appears. Before I save the entry in the code, I validate it and it returns true, regardless the empty value of the text input. 

The fieldlayout in the DB
![Screenshot 2020-11-17 at 13 57 03](https://user-images.githubusercontent.com/32429797/99393102-20e9aa80-28dd-11eb-807b-0484cc9d7016.png)

The entry before save in CP
![Screenshot 2020-11-17 at 13 57 45](https://user-images.githubusercontent.com/32429797/99393161-37900180-28dd-11eb-89ab-9208f7ce2480.png)

The entry after save in CP
![Screenshot 2020-11-17 at 13 58 13](https://user-images.githubusercontent.com/32429797/99393197-4676b400-28dd-11eb-90eb-178af0ccfc9a.png)

The code to save the entry from the frontend

```php
public function actionManage()
{
    $request = Craft::$app->getRequest();
    $uid = $request->getRequiredBodyParam('uid');
    $entry = Entry::find()->uid($uid)->one();
    $entry->setFieldValuesFromRequest('fields');
    if (!$entry->validate())
    {
        Craft::$app->getUrlManager()->setRouteParams([
            'request' => $entry,
        ]);
        return null;
    }
    Craft::$app->elements->saveElement($entry);
    $redirect = $request->getValidatedBodyParam('redirect');
    return $this->redirect(UrlHelper::siteUrl($redirect));
}
```

### Additional info

- Craft version: 3.5.14
- PHP version: 7.4
- Database driver & version: MySql - 5.7.26
- Plugins & versions:

**Comment by brandonkelly** [comment]
Add this before calling `$entry->validate()`:

```php
$entry->setScenario(Entry::SCENARIO_LIVE);
```

Also note that you are currently validating the entry twice, unnecessarily. Either start passing `false` to the second argument of `saveElement()`:

```php
Craft::$app->elements->saveElement($entry, false);
```

Or let `saveElement()` perform the validation and pay attention to what it returns:

```php
$entry->setScenario(Entry::SCENARIO_LIVE);
if (!Craft::$app->elements->saveElement($entry)) {
    Craft::$app->getUrlManager()->setRouteParams([
        'request' => $entry,
    ]);
    return null;
}
```

**Comment by robinbraibant** [comment]
Thank you Brandon!
