### ISSUE TITLE
ElementExporter stream data

### ISSUE THREAD

**Issue by alexandru-calinoiu** [craftcms/cms#7148]
### Description

I am writing a complex custom exporter for our data and its very ineficient now to build the data in memory in an array and they send it over to the client.

I was wondering if there is a way to stream the data to the client?

**Comment by brandonkelly** [comment]
There’s no elegant way to do this currently. I’ve made some changes for Craft 3.6 which will make it possible for `export()` to return a resource, which will be streamed, as well as added a new static `isFormattable()` method to the ElementExporterInterface, which can be overridden to return `false` if you don’t want the Format setting to show up.

If yiisoft/yii2#18394 is accepted, then this will be possible:

```php
public function export(ElementQueryInterface $query)
{
    return function() use ($query) {
        foreach ($query->each() as $element) {
            // output the formatted data for this element
            yield "$element->title\n";
        }
    };
}
```

**Comment by brandonkelly** [comment]
That PR was just merged for the upcoming Yii 2.0.40 release.

**Comment by brandonkelly** [comment]
Now that Yii 2.0.40 is out and pulled into the 3.6 branch, I’ve added support for `export()` returning a callable, for the next release.

**Comment by brandonkelly** [comment]
Craft 3.6 has now been officially released ✨
