### ISSUE TITLE
Project Config not assigning Global field?

### ISSUE THREAD

**Issue by MattWilcox** [craftcms/cms#7149]
### Description

Using project config, it doesn't seem reliable when assigning a field to a global?

See attached image. Having not worked as expected, I re-built the project config on local; got those files onto the live server, then `./craft project-config/apply`. The Newsletter Text field was created, but it was not assigned to the Global...

![bug](https://user-images.githubusercontent.com/814039/99425806-41286200-28fb-11eb-9b78-08c4d3368aba.jpg)

### Additional info

- Craft version: 3.5.15.1
- PHP version: 7.2 / 7.4

**Comment by brandonkelly** [comment]
Working as expected on my end. Can you try running `php craft project-config/apply --force` ?

**Comment by MattWilcox** [comment]
Not able to reproduce any more; had to get it working live so went and assigned the field on live. Will keep that in mind should it happen again, thanks Brandon.
