### ISSUE TITLE
Title fields don't format correctly when using a RTL language

### ISSUE THREAD

**Issue by GenMod** [craftcms/cms#7152]
### Description
When using an RTL language, such as Arabic, the title fields in the CMS have the text aligned as left to right, which results in the words coming out backwards in both the CMS and as a result, on the front end due to how it is saved into the database. 

### Steps to reproduce

1. Have a multilingual site
2. Set one of the languages to Arabic
3. Switch your site version to be the new Arabic translation
4. View an entry
5. Title fields within entries will display LTR instead of RTL

### Additional info

- Craft version: Craft Pro 3.5.15.1
- PHP version: 7.2
- Database driver & version: MariaDB 10.2
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.16 is out now with that fix.
