### ISSUE TITLE
Scroll to top after navigating element index pages

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#7154]
### Description

Element index pages don’t scroll to the top after navigating to a new (pagination) page.

Tested in Firefox 83 and Safari 14.

### Steps to reproduce

1. Click ”Next Page” link on an index page
2. See how the scroll position is still at the bottom of the page

### Additional info

- Craft version: 3.5.15.1

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Also wasn’t scrolling to the top when switching sections, etc. Fixed now for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.16 is out now with that fix.
