### ISSUE TITLE
Inconsistent user deletion behaviour 

### ISSUE THREAD

**Issue by tfantina** [craftcms/cms#7157]
### Description
I'm not 100% sure this is not intentional or I'm just not understanding something, feel free to close if I'm incorrect in my understanding of what should be happening.

If you have set ` 'allowAdminChanges' => false,`.  Go to delete an admin user, if you go to "users", click the user, hit the sprocket and select "delete" you see this error: "Unauthorized: Administrative changes are disallowed in this environment".

If however, you don't actually enter the user's page and just click the checkbox by their name and delete from the show all users page you will be able to delete them without issue. 

![craft-issue](https://user-images.githubusercontent.com/20165180/99685569-f49a6f00-2a3f-11eb-88c6-888df1514325.gif)
PS. Sorry for the poor quality video.

### Steps to reproduce

1. Set your general.php file with `'allowAdminChanges' => false,` 
2. Click on a specific admin and try to delete them 
3. Go to the Users section and try deleting an admin there.

### Additional info

- Craft version: 3.5.15.1
- PHP version: 7.0
- Database driver & version: MySQL

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.16 is out now with that fix.
