### ISSUE TITLE
Table Field: Consider hiding the table when there are no rows.

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#7158]
### Description

When there are no rows in a table…

Current UI:

![Screen Shot 2020-11-20 at 10 17 02](https://user-images.githubusercontent.com/25124/99736577-bf168400-2b1a-11eb-9ab0-6d53691dce1e.png)

Alternative UI options:

![Screen Shot 2020-11-20 at 10 18 07](https://user-images.githubusercontent.com/25124/99736596-c473ce80-2b1a-11eb-8d9c-6d270fb26d5e.png)

![Screen Shot 2020-11-20 at 10 17 54](https://user-images.githubusercontent.com/25124/99736601-c50c6500-2b1a-11eb-91e3-fc1eb89bc5fd.png)

Not sure which one of the alternatives I prefer. 

Styling for option 1 already exists if there is no table.

Option 2 works will with the default button label "Add a row" and is less visually intrusive.

**Comment by brandonkelly** [comment]
✅

**Comment by leevigraham** [comment]
35 minutes… 🔥💨

**Comment by carlcs** [comment]
I think it would be better for the UX, if the button didn’t stretch across the whole screen, with the button text far away from the field label. This works well when the table is shown, but when the table is missing it’d be better if it looked the same as “Add an asset”, “Add an entry”, and “Add a block” buttons.

![99736601-c50c6500-2b1a-11eb-91e3-fc1eb89bc5fd](https://user-images.githubusercontent.com/7516543/102264473-fb6cb280-3f15-11eb-8531-15465f4c2084.png)

**Comment by leevigraham** [comment]
@carlcs I initially though this as well but after using it for a while the full button feels ok.
