### ISSUE TITLE
Entries field should show entries from the current site if the site selector is disabled

### ISSUE THREAD

**Issue by OscarBarrett** [craftcms/cms#7164]
For the following situation:
- Three sites - 1, 2 and 3
- A Section that is only enabled for sites 2 and 3 (`section 1`) and only saves entries to the site they were created in.
- An Entries field for which section 1 is the source, `showSiteMenu` disabled
- Another Section that includes the above Entries field and is only enabled for sites 2 and 3

When you open the element selector modal no results are displayed. The query params to `get-elements` includes the `'siteId' => 1` in the criteria, which does not have any entries for this section as the section isn't enabled for it.

If `showSiteMenu` is enabled then the modal correctly shows entries for the current site. However it also lets users associate entries from another site which is undesirable.

Craft version: 3.5.15.1

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just fixed this for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.16 is out now with that fix.
