### ISSUE TITLE
Don't throw Exceptions in your Controller init functions

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#7168]
### Description

The Yii2 Debug toolbar started to enhance the routing data and some analytics, thus they started to create an instance for Controllers. You can see that [here ](https://github.com/yiisoft/yii2-debug/blob/master/src/models/router/ActionRoutes.php#L183) unfortunately many controllers have `requirePostRequests` in their init functions, so opening the toolbar to see routes/request params/ anything that has something to do with it will throw an exception.
I would really like to use the toolbar without pinning the version. Have you thought about removing your exceptions from there?

### Steps to reproduce

1. run composer update or install the latest Craft version
2. create an error
3. open the debug toolbar to see what happend
4. see you cannot navigate freely since Craft Controllers throw Exceptions on initialization

### Additional info

- Craft version: 3.5.15.1
-yiisoft/yii2-debug 2.1.15

**Comment by brandonkelly** [comment]
Fixed this for the next release by moving all of those checks into `beforeAction()` instead of `init()`.

**Comment by Anubarak** [comment]
Awesome thank you so much

**Comment by brandonkelly** [comment]
Craft 3.5.16 is out now with that fix.
