### ISSUE TITLE
Error with project config apply: No site settings exist for section ..

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#7169]
### Description
After we've created a single section, the first ./craft project-config/apply works fine. But then when the second deployment comes, throws a "Applying changes from your project config files ... error: No site settings exist for section 19"

It's trying to re-apply a section that is already there, and then fails in the special single section handeling. It's not really clear why though.

### Steps to reproduce
Had a simular issue in the past in the past, shall send over yaml files, composer and  and db if to debug?

### Additional info

- Craft version: 3.5.15.1
- PHP version: 7
- Database driver & version: mysql 8.x
- Plugins & versions:

**Comment by brandonkelly** [comment]
Something likely got out of sync at some point. Try running `php craft project-config/rebuild` on an environment where everything appears to be working correctly, and then `php craft project-config/apply --force` on other environments.

**Comment by lenvanessen** [comment]
@brandonkelly 

1. Did rebuild, commit and push
2. Pull, run `./craft project-config/apply --force` 
3. Same error

Applying on local environment doesn't cause the error, only production. Yaml files look good though

**Comment by brandonkelly** [comment]
@lenvanessen Did you figure it out?

**Comment by lenvanessen** [comment]
@brandonkelly it will remain a mystery, had the same problem a couple of times and then it just started working again, magically... Couldn't reproduce locally, so idea what was going on there, probably gnomes
