### ISSUE TITLE
Uploaded webp images not being transformed

### ISSUE THREAD

**Issue by TomDeSmet** [craftcms/cms#7170]
### Description
The client uploaded a `webp` image in the CP. In the twig code it is run through:
```
{% set imageTransform = {
    mode: 'crop',
    width: 520,
    height: 440
} %}
```

But unlike the other images, it keeps its original resolution. If I add `format: 'jpg'` a `webp` images is still being outputted.

### Additional info

- Craft version: 3.5.15.1
- PHP version: 7.4.11
- Database driver & version: MySQL 5.7.31

**Comment by brandonkelly** [comment]
Go to `/admin/utilities/php-info` and search for `WebP Support`. Does it say it’s enabled?

**Comment by TomDeSmet** [comment]
Yes it does!

**Comment by brandonkelly** [comment]
Craft 3.5.17 is out now with a fix for this. Thanks for reporting!
