### ISSUE TITLE
Dropdown and Radio buttons are not accessible over CraftQL API

### ISSUE THREAD

**Issue by nivanovic85** [craftcms/cms#7171]
### Description
Dropdown and Radio buttons are not accessible over CraftQL API
Schema is missing and data cannot be queried

This worked fine on Craft Pro 3.4.9

### Steps to reproduce

1. Create fields dropdown / radio buttons
2. Create new section and add created fields
3. Create new entries
4. Generate bearer token for user in Craft QL plugin section
5. Try to retrieve data of created entries and get dropdown / radio buttons

### Additional info

- Craft version: Craft Pro 3.5.15.1
- PHP version: 7.4.10
- Database driver & version: MySQL 5.5.5
- Plugins & versions: CraftQL:1.3.5

**Comment by brandonkelly** [comment]
CraftQL is a [third party plugin](https://plugins.craftcms.com/craftql). Each of those field types work fine in the [built-in GraphQL API](https://craftcms.com/docs/3.x/graphql.html) that we added in Craft 3.3.
