### ISSUE TITLE
One 'User' to rule them all

### ISSUE THREAD

**Issue by BrandKits** [craftcms/cms#7172]
Craft is a CMS, not a CRM. Or does that have to be the case? The purpose of many sites/apps is to build an audience, but the way Craft is architected splits that customer data across many channels. For a key client of mine, it's [Craft] Users, [Commerce] Customers, [Campaign] Contacts and [Freeform] submissions. And future plugins may be used which further splits the audience.

While we've developed a custom module to TRY to combine these, it would be a huge benefit if there was a model that Craft and plugin developers could use that could somehow integrated all these together. From a client's point of view, they just want to see who how many 'customers' they have, and then perhaps link off to the relevant part of the CMS. And perhaps be indicated if they have an account (the 'real' User).

I'm sure I'm not the first to desire this. And I respect the very clever people at Craft, who may already be thinking this (looking at you Craft 4).

Just putting it out there.

Cheers, Paul

**Comment by brandonkelly** [comment]
We’ve flirted with this idea a bit, as we’ve thought about how to unify Commerce customers and user accounts.

**Comment by bencroker** [comment]
The tricky thing is that Commerce customers, Campaign contacts and Freeform submissions need to be able to exist regardless of whether or not they are connected to users. Are you imagining a base element type (person/profile/entity) that all of the above would be able to extend, Paul? Or simply a more native way of connecting them together?

**Comment by brandonkelly** [comment]
What we have talked about, specifically, is decoupling users from authentication. So Commerce (or Campaign) could manage people in the centralized user list, regardless of whether they actually have an “account” (a means of authenticating themselves).

**Comment by BrandKits** [comment]
Brandon, that's exactly what I'm thinking... a centralised 'user' list of people, with indication of whether they have an account or not (vs a user being defined as having an account). Then being an account holder, or being a (Campaign) Contact, or a (Commerce) Customer is effectively a filter.

I think it would help the Craft ecosystem, and make life much simpler for authors.

Sorry for delay replying, didn't get notifications of your comments.

**Comment by brandonkelly** [comment]
We’ve continued talking about it internally and this should be making it into Craft 4. It’ll pair nicely with some authentication improvements we want to make.
