### ISSUE TITLE
Improve authoring experience when adding UI Elements to an entry type

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#7175]
I have one request (1) and a suggestion (2).

1. It'd be nice if, when clicking a UI Element's cog to edit content, the cursor focused the first input. This would save a click (a click that is further slowed by having the next click area hidden).
2. I keep finding myself wanting to reference the content under a "Heading" element that I add. It'd be preferred if these tooltips displayed above the placed content when possible.

**Comment by brandonkelly** [comment]
Just made the focus change for the next release.

Please post the second suggestion in a new issue (just one FR per issue please), and elaborate a bit on what you mean.

**Comment by brandonkelly** [comment]
Craft 3.5.17 is out now with the focus improvement.
