### ISSUE TITLE
Info icon and required star can awkwardly wrap when displaying instructions

### ISSUE THREAD

**Issue by BenParizek** [craftcms/cms#7181]
### Description

When a custom field is required or has instructions and is displayed in an Element Editor HUD or in the sidebar #details area, the icon and star can wrap awkwardly at certain lengths

See:
https://share.barrelstrength.co/6quxW9mE
https://share.barrelstrength.co/yAuZj8xX

### Steps to reproduce

1) Make a field in the sidebar #details area of a layout required

```
{% block details %}
<div class="meta">
	{{ forms.textField({
	  name: 'replyToEmail',
	  label: "Reply To"|t('sprout'),
	  value: '',
	  required: true
	}) }}
</meta>
{% endblock %}
```

OR 

2) Add instructions to an info bubble:

```
{% block details %}
<div class="meta">
	{{ forms.textField({
	  name: 'replyToEmail',
	  label: "Reply To <span class='info'>Instructions.</span>"|t('sprout'),
	  value: '',
	  required: true
	}) }}
</meta>
{% endblock %}
```

Adding instructions this was was only necessary because the instructions behavior currently doesn't work like the Element HUD. See https://github.com/craftcms/cms/issues/7180

### Additional info

- Craft version: 3.6.0-RC1
- PHP version: 8
- Database driver & version: mysql
- Plugins & versions: various

**Comment by brandonkelly** [comment]
This  has been fixed for Craft 3.6!
