### ISSUE TITLE
Updating Commerce and commerce-stripe plugins causes a hang.

### ISSUE THREAD

**Issue by martin-honcho** [craftcms/cms#7182]
### Description

Updating Commerce and commerce-stripe plugins.

Updating Commerce to version 2.2.24 so I can update commerce-stripe goes fine but then updating commerce-stripe just hangs for a long time ( gave up after 30mins ).
Tried this multiple times no luck.

Then I uninstalled commerce stripe. Updated commerce to 3.2.12. Then tried to reinstall commerce-stripe. This time it complained about "craftcms/commerce-stripe 2.3.2.1 requires stripe/stripe-php ^7.0".
So ran composer require stripe/stripe-php. But it then complained about another plugin ( freeform ) needing a lower version. Freeform is needing to be updated also but waiting on the client to buy a new license for that before continuing.

So the bug is that I got no warning or suggestions that it was another plugin with a conflicting stripe-php version. It just hung at the "performing update with composer" stage.

### Steps to reproduce

1. Update commerce from 2.1.8 => 2.2.24 ( cant update higher with commerce-stripe installed)
2. Update commerce-stripe ( from version 2.0.1.2 )

### Additional info

- Craft version: 3.5.16
- PHP version: 7.4
- Database driver & version:
- Plugins & versions: 
    - commerce-widgets 2.0.20 => 2.0.21 (EXPIRED)
    - commerce 2.1.8 => 3.2.12
    - freeform 3.6.5 => 3.9.6 (EXPIRED)
    - icon-picker 1.1.8 => 1.1.9 (EXPIRED)
    - instant-analytics 1.1.7 => 1.1.9 (EXPIRED)
    - linkit 1.1.11 => 1.1.12.1 (EXPIRED)
    - simplemap 3.8.4.1 => 3.8.5
    - navigation 1.3.21 => 1.4.3 (EXPIRED)
    - redactor 2.6.1 => 2.8.3
    - sprout-seo 4.6.3 => 4.6.5
    - commerce-stripe 2.0.1.2 => 2.3.2.1
    - super-table 2.5.1 => 2.6.3
    - view-count 1.0.3 => 1.0.4 (EXPIRED)

**Comment by brandonkelly** [comment]
Not sure what was going on here, but Craft 3.6 bundles Composer 2, which is dramatically faster than v1, so you should generally not see issues like this going forward. In the meantime, you’ll likely have better luck running `composer update` from the terminal instead – particularly if you have Composer 2 installed.
