### ISSUE TITLE
Select Dropdowns with long content overlap one another 

### ISSUE THREAD

**Issue by mjatharvest** [craftcms/cms#7183]
### Description
When dropdowns that contain long strings are positioned side by side in a field layout they overlap at some screen sizes.

### Steps to reproduce

1. Position dropdowns side by side
2. resize screen to observe

### Additional info
![Screen Shot 2020-11-20 at 1 10 10 PM](https://user-images.githubusercontent.com/285877/100257401-7f311180-2f0b-11eb-8555-8dae88f74701.png)
![Screen Shot 2020-11-20 at 1 10 22 PM](https://user-images.githubusercontent.com/285877/100257403-7f311180-2f0b-11eb-8280-023b1837998e.png)

- Craft version: 3.5.15.1
- PHP version: 7.2.27
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.17 is out now with this fix.

**Comment by mjatharvest** [comment]
Terrific! Thanks.
