### ISSUE TITLE
Eager Loading User Photos

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#7184]
### Description
Have a site with nearly 200 Users (Craft Users) and I have a page where all users listed with their photos.
```
{% set users = craft.users
    .group('team')
    .with(['photo', 'userScopeGroups', 'userPositionGroups', 'userLocations'])
    .relatedTo(positions)
    .limit(null)
    .orderBy('userPinned desc, firstName asc')
    .all() %}
```

Tried to load the user.photo eager but that did not work. 
`user[0].photo[0]` failed: `Key "0" in object with ArrayAccess of class "craft\elements\Asset" does not exist.`

Do is miss something?

### Additional info

- Craft version: 3.5.15
- PHP version: 7.4
- Database driver & version: MySQL 8

**Comment by davidhellmann** [comment]
When I get the image without `[0]` my Page loads 16 Seconds :( 

![image](https://user-images.githubusercontent.com/764292/100267188-546aab80-2f53-11eb-8d01-1ee25dd86af0.png)


If I remove this part (show the image) (props.avatar === user.photo): 
```
{% if props.avatar %}
      <div class="{{ props.cn ~ '__image' }}">
        {% include '_elements/image/image.twig' with {
          props: {
            image: props.avatar ??? null,
            transform: props.transform ??? null
          }
        } only %}
      </div>
    {% endif %}
```

its fast!
![image](https://user-images.githubusercontent.com/764292/100267332-8da31b80-2f53-11eb-82fd-c354dc451f67.png)

Any chance to handle that?

**Comment by andris-sevcenko** [comment]
`photo` is not an Asset field and cannot contain more than one Asset, so you should be using `{{ users[0].photo.url }}` instead of ` {{ users[0].photo[0].url }}`
