### ISSUE TITLE
3.6.0-RC1 element selector modal error

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#7186]
### Description

Getting `A server error occurred` error in 3.6.0-RC1 when opening the element selector modal. No errors are appearing in the logs and selecting elements no longer works.

<img width="978" alt="Screenshot 2020-11-25 at 19 47 15" src="https://user-images.githubusercontent.com/57572400/100271370-ad3d4280-2f59-11eb-8348-be7095983801.png">

### Steps to reproduce

1. Click on a related element field (entries, assets, etc.)
2. See error and try selecting an element.

### Additional info

I didn't find any errors in the logs or in the AJAX request, making troubleshooting quite tricky. I have all plugins disabled and @BenParizek has confirmed the issue as well.

- Craft version: 3.6.0-RC1
- PHP version: 7.4.2
- Database driver & version: MySQL 5.7.26

**Comment by bencroker** [comment]
Additionally, tried clearing the cache, no difference, not seeing any errors in the console nor in the AJAX responses and debug toolbar.

**Comment by bencroker** [comment]
Managed to track the issue down to `Craft.index()` throwing an exception:
```
TypeError: Cannot read property 'reduce' of undefined
```

This bug was introduced here: https://github.com/craftcms/cms/commit/0e4f34dd53219b5d02d34ce2bfff971ce88b2d92#diff-b9705a5250928f8dd378beb6ff7f2cc8cd708130275220eb153ee3278d2eb766

Wrapping the return statement in a condition fixes the issue:

```js
        index: function(arr, key) {
            if (arr) {
                return arr.reduce((index, obj, i) => {
                    index[typeof key === 'string' ? obj[key] : key(obj, i)] = obj;
                    return index;
                }, {});
            }
        },
```

**Comment by brandonkelly** [comment]
Thanks for reporting that, and for the PR! Fixed in a slightly different way.

**Comment by bencroker** [comment]
Thanks!

**Comment by brandonkelly** [comment]
Craft 3.6 RC2 is out now with that fix.
