### ISSUE TITLE
3.4 cache invalidating seemingly at random

### ISSUE THREAD

**Issue by jaspertandy** [craftcms/cms#7187]
### Description

I know this is going to be a super woolly one but I'm not looking for a solution as much as how to debug this. I am setting cache with `{% cache using key "keyname" for 86400 seconds %}` and the cache seems to last for random periods of time. I would expect a cache block set in this way to last for a day, but I suspect that something is happening somewhere that is invalidating my cache from another location. I am testing this by outputting a `{{ random() }}` and watching as it never lasts for a day.

So, I'm aware that this is an insufficient bug report. How can I make it a good one? I've looked in the cache token twig extension and `var_dump die`ing from various locations in there and nothing happens. I suspect some output buffering happens in there which is stopping this. It's definitely the right file as a syntax error in there crashes Craft! So how do I debug this?

Thank you!

**Comment by brandonkelly** [comment]
Template caches will be automatically cleared whenever an element that shows up inside the `{% cache %}` tag is updated or deleted. So I’m guessing that is what’s going on here. The `for` param is just a maximum amount of time before the cache will expire.
