### ISSUE TITLE
Allow for removing a site from an entry

### ISSUE THREAD

**Issue by JeanLucEsser** [craftcms/cms#7190]
### Description

I have logged an enhancement ticket to multisite here : https://github.com/craftcms/cms/issues/7189

But I think the premise of my ticket could be considered a bug, or at least an incongruity as you cannot undo or cancel something you may have done and change your mind afterwards. It's a one way ticket. Let me explain:

When the channel propagation method is to let each entry choose which site it should be saved to, we get a button to add a site in our entry form, but once added, we get no way to remove a site, only a way to deactivate, which is not the same.

If we are able to explicitly add a site to the entry so it can be activated / deactivated, we should be able to remove a site from the entry so that the entry is not listed anymore as a site element.

You can add a new Site to an Entry:
<img width="366" alt="image" src="https://user-images.githubusercontent.com/14908712/100366102-b33a2e80-3000-11eb-9d1a-9a07d8b04c15.png">

But once added, you cannot remove it, only disable it:
<img width="362" alt="image" src="https://user-images.githubusercontent.com/14908712/100366191-cf3dd000-3000-11eb-8ac1-5c66368d445e.png">

**Comment by brandonkelly** [comment]
It’s currently working as intended, so not a bug.

I didn’t add the ability to remove a site because I’m worried it will be too easily misunderstood, and authors will end up unintentionally deleting content.

Perhaps I can add an option alongside “Delete entry” in the Save menu dropdown, for deleting the entry for the currently selected site.

**Comment by brandonkelly** [comment]
Alright, this is added for Craft 3.6. Going forward, if both of these are true:

- you are editing an entry within a section whose propagation method is set to “Let each entry choose which sites it should be saved to”
- the entry is enabled for at least two sites

…and one of the following are true:

- the entry is an “unpublished draft” (see https://github.com/craftcms/cms/issues/5661#issuecomment-739084173)
- you are editing the source entry
- you are editing a draft, _for a site that was added to the entry in the draft, but not yet in the source entry_

…then the Save button will have a new “Delete [draft/entry] for this site” option:

![The Save button menu in Craft 3.6, for a draft, which shows the new “Delete draft for this site” option](https://user-images.githubusercontent.com/47792/101702817-7fb2c780-3a36-11eb-8e3e-a70ab5bcfd21.png)

Upon clicking it, you will be redirected back to the entry/draft in another site that is still active, or back to the Entries index if you didn’t have permission to access any of the other sites.

**Comment by JeanLucEsser** [comment]
Thanx for this Brandon. 

You’re so quick I haven’t had time to share my own proposition for this ;)

Give me a few hours to see what you did here and compare it to what I was about to share as a solution. But it looks like you nailed it as always. 

Just trying to see what you mean by « enabled » for at least 2 sites. Do you mean published (why then?) or existing (obvious)? And I was thinking about relocating the add site to the action bar. Let me finish thinking this through and getting back to you. 

And again, as always, this is some unbelievable great work you’re doing.

**Comment by brandonkelly** [comment]
Sorry for the confusion… I meant that the entry _exists_ for at least two sites; it doesn’t have to be enabled for them though. (It would be awkward to have the “Delete entry for this site” option on a single-site entry.)

**Comment by brandonkelly** [comment]
Craft 3.6 RC2 is out now with this change.

**Comment by brandonkelly** [comment]
Craft 3.6 has now been officially released ✨
