### ISSUE TITLE
Multisite Actions with XHR and Translations

### ISSUE THREAD

**Issue by jan-thoma** [craftcms/cms#7192]
### Description
When calling actions with XHR eg. something like

`/actions/users/login`

The error responses are allways in the locale of the primary site. If we try to call the action with XHR on the site path eg.

`/mysitepath/actions/users/login`

it results in an error 404.

I'm aware that there are error codes which could be static translated, but error codes are inconsitently. Example if the submission contains multiple errors no error codes are submitted.

**Comment by brandonkelly** [comment]
> If we try to call the action with XHR on the site path eg.
> 
> `/mysitepath/actions/users/login`
> 
> it results in an error 404.

I’m not able to reproduce that, FWIW.

![Screenshot of a 200 request to /site-b/actions/users/login](https://user-images.githubusercontent.com/47792/100547886-0f2dce80-321e-11eb-822c-41cc9561c18c.png)

As for error messages not getting translated, that’s up whatever is throwing the error. If the error is meant to be displayed to the end user, then it will typically be translated; however many exception errors are not intended to ever be seen by end users, so there’s no point in translating them – in fact it can make debugging _more_ difficult if they are translated, if the developer (or support) can’t read them.
