### ISSUE TITLE
Project config not finding settings during migration

### ISSUE THREAD

**Issue by BenParizek** [craftcms/cms#7196]
### Description

This could very well be me not understanding something but here's what I am seeing.

When I try to update from Craft 2 to Craft 3, at some point Craft 3 introduces the project config and moves the JSON stored in the `plugins.settings` column to the project config. This appears to happen fine, and if I use xdebug to pause the migration before I run a custom plugin migration, and look at the generated `project.yaml` file I see all of the plugin settings appear in the `project.yaml`. If I search the projectconfig db table for all rows that match my plugin, I see all of the settings there too.

BUT.

If I try to grab those settings in one of my migrations via the following code:

```
Craft::$app->getProjectConfig()->get('plugins.my-plugin.settings')

OR 

Craft::$app->getProjectConfig()->get('plugins.my-plugin.settings', true)
```

I don't get the values back that I see in the `project.yaml` or in the `projectconfig` db table. I get back a subset of those values. There are several migrations being run but I don't believe any of the others are targeting these settings.

What conditions might be present for me to see the settings I want to query in the `project.yaml` and db but get back different results? Could this have something to do with the timing of when these run in the migration? Craft runs it's db updates introducing project config. Then plugin migrations run get triggered and that is where I'm seeing the issue, before the full migration process is complete.

### Additional info

- Craft version: 3.6.x
- PHP version: 7.4
- Database driver & version: mysql
- Plugins & versions: various

**Comment by BenParizek** [comment]
If I query the db directly, I do see the values that I'm looking for:

```
(new Query())
            ->select('*')
            ->from('{{%projectconfig}}')
            ->where(['like', 'path', 'plugins.my-plugin'])
            ->all();
```

I'm not sure if I should be doing this in a migration. It feels like I'm missing something and creating more work for myself.

**Comment by brandonkelly** [comment]
If you’re able to reproduce this reliably, it very well could be a bug. Perhaps caching related, if multiple project config changes are happening in the same request or something. Can you send your Composer files and a database backup over to support@craftcms.com, with steps to reproduce?

**Comment by BenParizek** [comment]
I'll send things over as soon as I have a chance.

**Comment by BenParizek** [comment]
Alright, it seems this had to do with us grabbing our settings via the Craft API during the c2 to c3 upgrade and that behaved differently than expected after Project Config was introduced in 3.1. I believe I've solved things checking for Craft version where Project Config gets introduced in the migration:

```
if (version_compare(Craft::$app->getInfo()->version, '3.1.0', '>=')) {
  $projectConfig = Craft::$app->getProjectConfig();
  $settings = $projectConfig->get('plugins.sprout-seo.settings');
} else {
  $plugin = SproutSeo::getInstance();
  $pluginSettings = $plugin->getSettings();
  $settings = $pluginSettings->getAttributes();
}
```
