### ISSUE TITLE
Unable to add checkbox options when using GraphQL mutations

### ISSUE THREAD

**Issue by engram-design** [craftcms/cms#7197]
When trying to create an entry through GQL mutations, and assigning multiple values to a checkbox, it doesn't seem possible, and is throwing an error. (This is also to fix https://github.com/verbb/formie/issues/237 which Formie's field inherits from).

Take the following example into account for an Entry with a "checkboxes" checkbox field handle on it. We're trying to assign multiple values as checked, but it should be argued checkbox content should _always_ be provided as an array.

```
mutation saveEntry($title: String, $checkboxes: [String]) {
  save_gql_gql_Entry(title: $title, checkboxes: $checkboxes) {
    title
    checkboxes
  }
}

{
  "title": "Craft 3.5 Supports GraphQL Mutations",
  "checkboxes": ["option1", "option2"]
}
```

The below will produce an error:
```
{
  "errors": [
    {
      "message": "Variable \"$checkboxes\" of type \"[String]\" used in position expecting type \"String\".",
      "category": "graphql",
      "locations": [
        {
          "line": 1,
          "column": 36
        },
        {
          "line": 2,
          "column": 47
        }
      ]
    }
  ]
}
```

Pretty sure this can be fixed in https://github.com/craftcms/cms/blob/develop/src/fields/BaseOptionsField.php#L432 be replacing:

```
 'type' => Type::string(),
```
with
```
 'type' => $this->multi ? Type::listOf(Type::string()) : Type::string(),
```

As is the similar check for the GQL type. This fix at least works for me!

**Comment by andris-sevcenko** [comment]
Good call, just fixed this for the next release!

**Comment by brandonkelly** [comment]
Craft 3.5.17 is out now with this fix.
