### ISSUE TITLE
3.5.16 change to saveElement behaviour in EVENT_AFTER_SAVE breaks preparse field plugin, causing data loss

### ISSUE THREAD

**Issue by monachilada** [craftcms/cms#7199]
### Description

The change here: https://github.com/craftcms/cms/commit/67627d155c89fd9eaa14d0c276cc7d315c4496c4 that should close this bug https://github.com/craftcms/cms/issues/7108, in combination with any element with both a matrix field and a [preparse field](https://github.com/besteadfast/craft-preparse-field) provided by the preparse plugin will result in any matrix field content being stripped when attempting to resave the element without having made any changes to any fields within the matrix blocks.

I've uploaded a video better demonstrating the behaviour:
https://www.dropbox.com/s/y1x8iisbumuoskc/Screen%20Recording%202020-11-29%20at%2013.22.28.mov?dl=0

Digging under the hood, it appears the plugin relies on `Craft::$app->getElements()->saveElement` to resave the element if the preparse field attached specifies it should run after save, this is to allow the contents of a preparse field to be based on the "latest" content present in the element. See [relevant lines in the plugin here](https://github.com/besteadfast/craft-preparse-field/blob/43c240a17dab1fe1b2d936fd99dd831a81b7a0f5/src/PreparseField.php#L98-L128).

I haven't been able to discern preceisely why, but forcing a value of `null` for the `duplicateOf` attribute of the element being saved means that in the scenario above, the matrix fields will get stripped from the element as it is effectively saved the second time from within the plugin.

It seems to me this might also effect other plugins or modules with a similar pattern, though I haven't got any other reproducible examples to share currently.

### Steps to reproduce

1. Create an element with any number of matrix fields, as well as a preparse field.
2. Save the element with changes in the matrix field, observe correct behaviour.
3. Resave the element with either no changes made, or changes only in fields outside of the matrix field, observe matrix fields are now missing.

### Additional info

- Craft version: 3.5.16
- PHP version: 7.4.2
- Database driver & version: MySQL 5.7
- Plugins & versions: [craft-preparse-field](https://github.com/besteadfast/craft-preparse-field)

**Comment by mmikkel** [comment]
Can confirm. Issue only occurs if the Preparse field's "Parse before save" setting is disabled (i.e. the default setting).

**Comment by brandonkelly** [comment]
Should the Preparse field be nested within the Matrix field, or directly on the entry? And should the field’s template reference any values within the Matrix field?

**Comment by monachilada** [comment]
> Should the Preparse field be nested within the Matrix field, or directly on the entry?

Directly on the entry.

> And should the field’s template reference any values within the Matrix field?

Not necessarily.

**Comment by brandonkelly** [comment]
Thanks. I can reproduce, but in looking into it I also discovered besteadfast/craft-preparse-field#64. Just submitted PR besteadfast/craft-preparse-field#65 which fixes that as well as this bug.

**Comment by monachilada** [comment]
Thanks, that fixed it for me!
