### ISSUE TITLE
New required dropdown with default option makes entries unsaveable

### ISSUE THREAD

**Issue by ArrayKnight** [craftcms/cms#7205]
### Description

When a new required dropdown field with a default value selected was added to an existing matrix, entries became unsaveable. The workaround was to select an alternate value in the dropdown, save, then revert to the default value, and save again

### Steps to reproduce

1. Create a matrix with some fields
2. Add matrix to an entry type
3. Create an instance of that entry type and save it with some data
4. Create a new dropdown field in the matrix (should be required and have multiple options with one of them set as the default)
5. Go to the entry, see that the new dropdown field exists and shows the default value as selected, try to save (will fail)

To get around it:
6. Change dropdown value to any other value, save (will be successful)
7. Revert dropdown to default value, save (will be successful)

### Additional info

- Craft version: 3.5.16 (Pro)
- PHP version: 7.3.24
- OS version: Linux 4.19.128-microsoft-standard
- Database driver & version: MySQL 5.5.5
- Image driver & version: Imagick 3.4.3 (ImageMagick 6.9.10-23)
- Plugins & versions: 
    - MatrixMate 1.2.7
    - oEmbed 1.3.6
    - Position Fieldtype 1.0.16
    - Redactor 2.8.4
    - SEO 3.6.7
    - Servd Assets and Helpers 2.0.2
    - Super Table 2.6.4
    - Webhooks 2.3.2

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.17 is out now with this fix.
