### ISSUE TITLE
Using element query asArray with eager-loaded relations

### ISSUE THREAD

**Issue by rb1193** [craftcms/cms#7206]
### Description

This is a follow up to #2039. We are also attempting to pass the result of Craft queries into Vue components, and have adopted the method suggested using asArray, but the relations are not appearing in the output. I was hoping to get a nested array containing the relations. Is this possible in Craft? This [Yii issue](https://github.com/yiisoft/yii2/issues/1402) suggests it might be but I'm not sure if that applies to Craft.

Example code:

`{% set entries = craft.entries().section('section_name').with(['asset_field_handle']).asArray().all() %}`

The results do not include the asset field.

**Comment by brandonkelly** [comment]
Element queries’ `asArray()` does not support relations, no. It will just give you the raw result of the SQL query, which does not include related elements’ data. (`with` will load the related elements’ data in subsequent queries – but only if you haven’t called `asArray()`.)

A better way of getting the data these days would be via GraphQL. Either by sending an Ajax request to the [GraphQL API](https://craftcms.com/docs/3.x/graphql.html), or right from your template using the [gql()](https://craftcms.com/docs/3.x/dev/functions.html#gql) function:

```twig
{% set data = gql('{
  entries (section: "sectionHandle") {
    id
    postDate @formatDateTime (format: "Y-m-d")
    title
    url
    ... on sectionHandle_entryTypeHandle_Entry {
      assetFieldHandle {
        url
      }
    }
  }
}') %}
```

You can figure out the exact query that you should put it there from GraphQL → GraphiQL.

**Comment by rb1193** [comment]
Great, don't know how I missed the gql function in the docs. Thanks!
