### ISSUE TITLE
Project Config bug?

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#7208]
### Description

If you set the Base URL of a site to an **alias**, it will properly set that alias in the Project Config files.

<img width="307" alt="base-url@2x" src="https://user-images.githubusercontent.com/5309692/100680479-7d5db880-3326-11eb-95fd-b1c1ec764b37.png">

But when you "Rebuild the Config", it will actually change it to the _value_ of the alias.

<img width="431" alt="hardcoded@2x" src="https://user-images.githubusercontent.com/5309692/100680471-79319b00-3326-11eb-88ed-59c2dd0c36af.png">

### Steps to reproduce

1. Use an alias for the `baseUrl`
2. Run "Rebuild the Config"
3. Look at the changes in `default--***.yaml`

### Additional info

- Craft version: Craft Pro 3.5.16
- PHP version: 7.4.9

**Comment by brandonkelly** [comment]
Not able to reproduce this, and not sure how it could happen. Sites’ configs are rebuild from `craft\models\Site::getConfig()`, which returns the current `$baseUrl` value:

https://github.com/craftcms/cms/blob/1d69bfb0308d3b56990d7b257591071992d7a297/src/models/Site.php#L264-L277

Craft never stores the parsed base URL there – that only happens from `getBaseUrl()`:

https://github.com/craftcms/cms/blob/1d69bfb0308d3b56990d7b257591071992d7a297/src/models/Site.php#L128-L135

Maybe something in a module/plugin is overwriting the `$baseUrl` property with the parsed URL?

**Comment by lindseydiloreto** [comment]
Weirdly, this trick doesn't seem to be working for me either...

https://github.com/craftcms/cms/issues/5106#issuecomment-708718343

Can you reproduce that one?

**Comment by brianjhanson** [comment]
For what it's worth, I've noticed something similar with a project updating from Craft 2 to 3. When doing the upgrade on the DB, we throw out the project config values (in favor of the ones we've been working on for Craft 3), but Craft seem to _really_ want us to use the URL string rather than an environment variable.

Next time we run the process I'll see if I can narrow down the issue to anything more specific.

**Comment by brandonkelly** [comment]
@lindseydiloreto `'disabledPlugins' => '*'` is still working for me.

**Comment by lindseydiloreto** [comment]
Ah, my bad! I was doing it wrong, setting it as an array syntax (`['*']` instead of just `'*'`). 🤦

**Comment by lindseydiloreto** [comment]
Ok, I have:
 1. Disabled all plugins
 2. Disabled all modules

And I still get the same issue when I click the "Rebuild the Config" button...

<img width="534" alt="rebuild@2x" src="https://user-images.githubusercontent.com/5309692/100773600-f6f0b780-33b5-11eb-893a-e49c59a94afc.png">

---

<img width="443" alt="same@2x" src="https://user-images.githubusercontent.com/5309692/100773652-06700080-33b6-11eb-8991-0c08780a5fcd.png">

**Comment by lindseydiloreto** [comment]
It's worth noting that the `baseUrl` gets written to PC normally when you simply go edit that field directly.

<img width="261" alt="baseUrl@2x" src="https://user-images.githubusercontent.com/5309692/100774020-7c746780-33b6-11eb-80b2-b23748b95ac5.png">

After I go re-save the field normally, it corrects the PC mistake.

**Comment by brandonkelly** [comment]
And even now, after saving the site from the CP with `@baseUrl`, if you rebuild the project config, it will go back to `http://industrialassets.test` ?

**Comment by lindseydiloreto** [comment]
If I save the field normally (as if I were editing it), the PC value is set to `@baseUrl`.

If I rebuild it (via "Rebuild the Config"), the PC value changes to `http://industrialassets.test`.

**Comment by brandonkelly** [comment]
Alright, well I’m a bit stumped. If you can send in your Composer files, a database backup, and any custom module files, etc., we can try to reproduce it locally using those. support@craftcms.com

**Comment by lindseydiloreto** [comment]
You got it, thanks! I'll send that stuff over. 👍

**Comment by brandonkelly** [comment]
We ended up tracking this down to the `siteUrl` config setting. Same issue could occur with the `siteName` config setting as well. I’ve fixed this for the next release.

**Comment by lindseydiloreto** [comment]
Ok sweet, thanks @brandonkelly! 🍺

**Comment by brandonkelly** [comment]
Worth mentioning here that I’ve just deprecated the `siteUrl` config setting for Craft 3.6 (see #3205). So while this bug will be fixed in the next release, you’re best off moving away from that config setting to begin with, and setting your sites’ Base URL settings using aliases or environment variables instead.

**Comment by brandonkelly** [comment]
Craft 3.5.17 is out now with this fix.

**Comment by lindseydiloreto** [comment]
Brilliant, thanks dude! 👍
