### ISSUE TITLE
"craft backup" throws warning on php8

### ISSUE THREAD

**Issue by hiasl** [craftcms/cms#7209]
### Description
PHP8 on the console throws a warning when calling `./craft backup`

### Steps to reproduce

1. do a `./craft backup` on the console with php8
2. get the error (see below):

```
$ php -v
PHP 8.0.0 (cli) (built: Nov 27 2020 12:25:47) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.0, Copyright (c), by Zend Technologies
$ ./craft backup
Backing up the database ... error: usort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero

```
### Additional info
All plugins where disabled to make sure nothing is interfering via `"disabledPlugins"="*"`

- Craft version: 3.5.16
- PHP version: 8.0.0
- Plugins & versions: none

## one more notice:
plugin/install causes a Deprecation Warning
```
$./craft plugin/install whatever
12:27:39 PHP Deprecated Warning 'yii\base\ErrorException' with message 'Method ReflectionParameter::isArray() is deprecated'
```

**Comment by brandonkelly** [comment]
Craft 3.5 does not support PHP 8. We are close to finishing PHP 8 support for Craft 3.6 (see #7050), so if you want to test that, change your `craftcms/cms` requirement in `composer.json` to `"^3.6.0-RC1"` and run `composer update`.

If the error persists after updating to 3.6, please find the error in `storage/logs/console.log` and post the full stack trace, so we have a better idea of where to look.

**Comment by brandonkelly** [comment]
I was able to reproduce the same error with Craft 3.5 + PHP 8, and verified that the error doesn’t occur with Craft 3.6. So will close this.

**Comment by hiasl** [comment]
ok, good to know, thanks for trying. I twice tried upgrading to 3.6-RC1 but received an error on deployment both times. I will send a ticket to support with dump/composer.json.

**Comment by brandonkelly** [comment]
If it is related to the PHP version, see our [Resolving PHP Requirement Conflicts](https://craftcms.com/knowledge-base/resolving-php-requirement-conflicts) KB article.

**Comment by hiasl** [comment]
no, it happens between migrations and project-config/apply. p&t ticket-id is 10765.

**Comment by brandonkelly** [comment]
The error you’re getting is covered by #7174.
