### ISSUE TITLE
Feature Request: User Group column in Craft CP Users > All Users table + export

### ISSUE THREAD

**Issue by acantes** [craftcms/cms#7211]
A client with access to User managemeent features via the Control Panel would like to see a User Group column in the display of All Users, and ideally be able to create an export of all users that includes an additional column of the assigned User Group for each User as well.

The rationale being that for a website with hundreds of members, searching for a particular user in the CP doesn't reveal any details of their group assignment. My client then has to click each one of nine user groups in turn and search for the member's name each time to find the user in the single group they are in.

Unless I've missed something (and most times I have) then I can't add the User Group column to the All Users display in the CP using the Customize options.

**Comment by brandonkelly** [comment]
Just added the ability to show a “Groups” column on user indexes, for Craft 3.6.

> and ideally be able to create an export of all users that includes an additional column of the assigned User Group for each User as well.

That’s unfortunately not easily doable at the moment. Your best bet would be to [create a custom exporter](https://craftcms.com/docs/3.x/extend/element-exporter-types.html) with the exact data you need. Be sure to call the new `withGroups()` param on the user query before calling `all()`, so the groups get eager-loaded onto the users before you call `getGroups()` on each of them.

Or, feel free to repost that as its own issue and I can throw it on the v4 milestone.

**Comment by brandonkelly** [comment]
Craft 3.6 RC2 is out now with this change.

**Comment by acantes** [comment]
Thanks for such a quick update, Brandon!

**Comment by brandonkelly** [comment]
Craft 3.6 has now been officially released ✨

**Comment by acantes** [comment]
Thanks Brandon, I'll give it a whirl.
