### ISSUE TITLE
{site.handle} in Default Asset Location for asset fields are ignored in globals

### ISSUE THREAD

**Issue by lassemt** [craftcms/cms#7213]
### Description
Using `{site.handle}` in an assets field subfolder path works great when uploading assets in entries, but always end up in "default" site folder when uploading assets in globals no matter what site is selected. 

Exmaple: Uploading logo.svg in a global asset field for sites with the handles brand-a and brand-b, we expect output path to be `brand-a/assets/logo.svg` and `brand-b/assets/logo.svg`. Instead we get `default/assets/logo.svg` and `default/assets/logo_2020-12-01-173732.svg` (timestamp varies on duplicate file).

### Steps to reproduce
1. Create an asset field using `{site.handle}` variable in Default Asset Location. 
2. Add field to globals.
3. Upload files on different sites.
4. See they end up in the default site folder.

### Additional info
- Craft version: 3.5.16
- PHP version: 7.4.9
- Database driver & version: MySQL 5.7.30
- Plugins & versions: Tested on empty install.

**Comment by lassemt** [comment]
Can this be because "Show the site menu - Whether the site menu should be shown for asset selection modals." is not checked?

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.17 is out now with this fix.

**Comment by jamiematrix** [comment]
Still getting this issue with Craft 3.7.20
Only just having a little debug it looks like the incorrect `folderId` is being set in the body params - which I assume is encoded?
