### ISSUE TITLE
craft v2 -> v3 Cannot use twig filter in upload folder string for an asset-field-type

### ISSUE THREAD

**Issue by krizzzly** [craftcms/cms#7215]
### Description
In craft cms v.2.9 we were able to use twig filters to dynamically change the upload folder. In craft v.3.4.30 the pipe ```|``` is ignored.

![Bildschirmfoto 2020-12-02 um 14 45 37](https://user-images.githubusercontent.com/48832704/100881004-b8d6bf00-34ad-11eb-9680-41cc91f2620d.png)

this is not working anymore.

### Additional info

- Craft version: 3.4.30
- PHP version: 7.4.9
- Database driver & version: MySQL 5.7.26
- Plugins & versions:

**Comment by brandonkelly** [comment]
Filters definitely work there in general. What is defining the `|sectionhelper` filter? Have you verified it is still working in a normal Twig template?

**Comment by krizzzly** [comment]
```|sectionhelper``` is a twig filter, defined inside a module, but we also have tested twig filter function inside plugins. Both are not working in this place. Inside a template we have tested the twig filter to work correctly. In general you are right, native twig functions, like ```|replace``` are working here.

**Comment by brandonkelly** [comment]
So how are you registering the filter? You should be following this example: https://craftcms.com/docs/3.x/extend/extending-twig.html#register-a-twig-extension

**Comment by krizzzly** [comment]
yes i followed exactly this example now:

modules/Module.php
```
<?php
namespace modules;

use Craft;
use craft\elements\Entry;
use craft\events\ElementEvent;
use craft\feeds\GuzzleClient;
use craft\helpers\UrlHelper;
use craft\services\Elements;
use Kint\Kint;
use yii\base\Event;

/**
 * Custom module class.
 *
 * This class will be available throughout the system via:
 * `Craft::$app->getModule('my-module')`.
 *
 * You can change its module ID ("my-module") to something else from
 * config/app.php.
 *
 * If you want the module to get loaded on every request, uncomment this line
 * in config/app.php:
 *
 *     'bootstrap' => ['my-module']
 *
 * Learn more about Yii module development in Yii's documentation:
 * http://www.yiiframework.com/doc-2.0/guide-structure-modules.html
 */
class Module extends \yii\base\Module
{
    /**
     * Initializes the module.
     */
    public function init()
    {
        // Set a @modules alias pointed to the modules/ directory
        Craft::setAlias('@modules', __DIR__);

        // Set the controllerNamespace based on whether this is a console or web request
        if (Craft::$app->getRequest()->getIsConsoleRequest()) {
            $this->controllerNamespace = 'modules\\console\\controllers';
        } else {
            $this->controllerNamespace = 'modules\\controllers';
        }

        if (Craft::$app->request->getIsSiteRequest()) {
            // Add in our Twig extension
            $extension = new MyTwigExtension();
            Craft::$app->view->registerTwigExtension($extension);
        }

        parent::init();

        // Custom initialization code goes here...
    }
}
```

modules/MyTwigExtension.php
```
<?php

namespace modules;

use Twig\Extension\AbstractExtension;
use Twig\TwigFilter;

class MyTwigExtension extends AbstractExtension
{
    public function getFilters()
    {
        return [
            new TwigFilter('sectionhelper2', [$this, 'sectionhelper2']),
        ];
    }

    public function sectionhelper2($string)
    {
        return 'test';
    }
}
```

Settings > Fields

![Bildschirmfoto 2020-12-03 um 14 26 30](https://user-images.githubusercontent.com/48832704/101023798-90b19380-3573-11eb-9452-bd20c13810bb.png)

Error Message in Entry after Drag&Drop and image into the upload field

![Bildschirmfoto 2020-12-03 um 14 28 16](https://user-images.githubusercontent.com/48832704/101023994-ce162100-3573-11eb-9495-cb958c29bb73.png)

**Comment by brandonkelly** [comment]
You should remove this condition:

```php
if (Craft::$app->request->getIsSiteRequest()) {
```

As that is preventing the Twig extension from being registered for control panel requests, which is where you need it.

Also check `config/app.php` and make sure that your module is included in the `bootstrap` array.

**Comment by krizzzly** [comment]
🙈  😄 works like a charm. Thank you for support.

**Comment by brandonkelly** [comment]
Glad that worked!
