### ISSUE TITLE
Entry status not properly propagated to new sites

### ISSUE THREAD

**Issue by TimvanDijkhuizen** [craftcms/cms#7217]
### Description
Whenever you create a new site and enable sections for it the entries will be propagated, but some disabled entries will be enabled. I compared entries that did stay disabled and ones that got enabled and found that the enabled entries had at least one enabled site. So entries will only be propagated as disabled if the source entry is disabled for all sites.

I would assume that entries which are being propagated get their content and status from the primary site.

### Steps to reproduce

1. Create an entry, disable it for the primary site and enable it for any other site.
2. Create a new site.
3. Enable the section for the new site.
4. See how entries that were disabled in the primary site are propagated as enabled.

### Additional info

- Craft version: 3.5.16
- PHP version: 7.2.18
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
   - Redactor 2.8.4

**Comment by brandonkelly** [comment]
Craft will set the entries’ status on the new site based on the Default Status setting you selected in the section settings when enabling the new site for the section. 

> I compared entries that did stay disabled and ones that got enabled and found that the enabled entries had at least one enabled site. So entries will only be propagated as disabled if the source entry is disabled for all sites.

Correct, that is an exception. Entries that were disabled across all sites will continue to be for the new site.
