### ISSUE TITLE
Project-Config page in CMS admin times / crashes

### ISSUE THREAD

**Issue by mizziness** [craftcms/cms#7218]
### Description

When viewing the project-config section in the CMS (i.e. going to `/admin/utilities/project-config`), if there are changes to be reviewed in a significantly-large project, the page times out / stops loading / crashes.

This is a fairly annoying/significant issue because anyone who tries to view that page in any of our environments is met with a crashed tab or browser. We essentially can never visit that page.

### Steps to reproduce

1. Make changes to the `project-config` in your project
2. Navigate to the CMS admin dashboard
3. See notice: `Your project config YAML files contain pending changes. Review ->` and click to go review
4. Page `/utilities/project-config` begins loading, and does not finish. Buttons don't work, CPU on the server maxes out for a little bit, and eventually I can navigate away or the tab crashes and must be closed/re-opened.

![image](https://user-images.githubusercontent.com/4164335/101039759-ee30ea80-3549-11eb-871e-a213d9b4ba77.png)

### Additional info

- Craft version: 3.5.16
- PHP version: 7.4.3
- Database driver & version: MySQL 8.0.22
- Plugins & versions: 
The list is pretty long, but I did try after removing plugins, and there was no change in behavior so I don't believe plugins directly cause this. We have a significant number of fields in our system, and our DB on average is roughly 500mb.  List screenshot below, the crossed out plugins are either custom ones or removed.

![image](https://user-images.githubusercontent.com/4164335/101042506-44525d80-354b-11eb-8351-086a24531801.png)

**Comment by gbowne-quickbase** [comment]
I've seen the same behavior. And `./craft project-config/diff` also never resolves. If I just press 'Apply Changes Only,' or run a CLI apply, we're golden.

**Comment by brandonkelly** [comment]
Just resolved this for Craft 3.6 by implementing a custom diffing function, which works with the raw project config data rather than YAML.

**Comment by brandonkelly** [comment]
Craft 3.6 RC2 is out now with this change.

**Comment by brandonkelly** [comment]
Craft 3.6 has now been officially released ✨
