### ISSUE TITLE
Limit on number of assets customizable in field layout pages

### ISSUE THREAD

**Issue by proimage** [craftcms/cms#7219]
### Description
Sometimes an image field may only be set up to handle one file, and sometimes it's used for an entire gallery.

With the flexibility that configurable Title and Instruction fields provide, it would help reduce the number of custom fields required for a site if Asset fields could also have a custom number of selectable files. Something like this:

![image](https://user-images.githubusercontent.com/1027523/101065475-df742300-359d-11eb-8639-fe0342af4219.png)

**Comment by brandonkelly** [comment]
This idea was already requested by #4321.
