### ISSUE TITLE
Can no longer create new fields. Maximum table row size reached error warning. 

### ISSUE THREAD

**Issue by riusi88** [craftcms/cms#7221]
We just ran into an issue on one of our large Craft sites, and can no longer create text content fields (with the exception of "number" fields). The following error gets logged. 

`SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs`

Our temporary solution was to modify a mysql config, and set `innodb_strict_mode=0`, but we're concerned that this won't be a stable fix. We'd appreciate any guidance to resolve this problem any other way, and can provide additional info/db's if requested. 

### Additional info

- Craft version: 3.4.30
- PHP version: 7.1.33
- Database driver & version: MySQL 5.5.5

**Comment by angrybrad** [comment]
There are other MySQL config options to help, too: https://github.com/craftcms/cms/issues/2009#issuecomment-333394434

Ultimately, this is a MySQL limitation that you're running into. We hope to lower the chance that people actually hit it with the planned element content refactoring: https://github.com/craftcms/cms/issues/1524

**Comment by brandonkelly** [comment]
Row size limits are no longer an issue in Craft 5.
