### ISSUE TITLE
Cannot use Limit on entries field when entry has children

### ISSUE THREAD

**Issue by joshua-martin** [craftcms/cms#7224]
### Description

I have an entries field that has a limit of 1. If I select an entry that has children, I see the error '{FIELD} should contain at most 1 selection.'

![2020-12-04 09 39 26](https://user-images.githubusercontent.com/1694957/101147913-e5591b00-3614-11eb-9bf8-8489c7528794.gif)

### Steps to reproduce

1. Set entries field to limit of 1
2. Try to select an entry that has children

### Additional info

- Craft version: 3.5.16

**Comment by joshua-martin** [comment]
It actually appears it's because it's attaching the element twice. If I remove the limit then save, the entry gets attached to the field twice.

![2020-12-04 09 47 03](https://user-images.githubusercontent.com/1694957/101148695-de7ed800-3615-11eb-84db-1d5a01274742.gif)

I thought maybe I had two entries in the search index or something, but when inspecting it's got the same ID for both of the elements.

<img width="704" alt="Screenshot 2020-12-04 at 09 47 25" src="https://user-images.githubusercontent.com/1694957/101148677-daeb5100-3615-11eb-9926-b91cdedaf49d.png">

**Comment by joshua-martin** [comment]
Looks more like this was some sort of failure between 3.4 => 3.5 upgrade path. I've rolled back to the old version and run through the migrations again and it appears to be functioning correctly, now.

I've got the broken database backed up if it's of any value!

Thanks

**Comment by brandonkelly** [comment]
Glad you got it sorted! Not really sure what could have caused that.
