### ISSUE TITLE
Element `$query->getCrtiteria()` bug

### ISSUE THREAD

**Issue by samhibberd** [craftcms/cms#7225]
### Description

It doesn't look like the `getCriteria()` method picks up `relatedTo` criteria set by the field name eg.

`$query->customFieldHandle(100); `
vs
`$query->relatedTo([ 'targetElement' => 100, 'field' =>'customFieldHandle' ]);`

### Steps to reproduce

```php
// $criteria array does NOT contain any relatedTo criteria
$query = Entry::find();
$query->customFieldHandle(100);
$criteria = $query->getCriteria();
```

```php
// $criteria array does contain the relatedTo criteria
$query = Entry::find();
$query->relatedTo([ 'targetElement' => 100, 'field' =>'customFieldHandle' ]);
$criteria = $query->getCriteria(); 
```

### Additional info

- Craft version: 3.5.16
- PHP version: 7.3

**Comment by brandonkelly** [comment]
Good catch! Just fixed this for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.17 is out now with this fix.
