### ISSUE TITLE
GraphQL dump full access schema

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/cms#7226]
### Description

I would like to have the ability to dump the full access schema via`./craft graphql/dump-schema`, perhaps by adding a `--full`.

**Comment by andris-sevcenko** [comment]
Okay.

**Comment by andris-sevcenko** [comment]
Jokes aside - just added this for the next release.

**Comment by Wiejeben** [comment]
Thanks for the quick fix! Being in a meeting and trying to write out a new feature at the same time made me rush it haha. I already saw it could be as easy as using `Gql::createFullAccessSchema()`.

Thanks again

**Comment by brandonkelly** [comment]
Craft 3.5.17 is out now with the new `--full-schema` option.
