### ISSUE TITLE
Search: add $results array to the EVENT_AFTER_SEARCH event object

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#7237]
### Description

I would like to access/know what field matched via Craft search attribute in order to display that content of that field and highlight the term. Currently my only "known" method to do so without having to rewrite much is to extend your search, copy all private functions and return the `$result` parameter or extend the Event by myself.

All I actually need is to gain access to the `$results` array would you please include that?
I could create a pull request but I guess it's less effort for you to just include the line two times and add the property to the event.

**Comment by brandonkelly** [comment]
Easy enough – just added `SearchEvent::$results` for Craft 3.6.

**Comment by brandonkelly** [comment]
Craft 3.6 RC2 is out now with that new event property.

**Comment by brandonkelly** [comment]
Craft 3.6 has now been officially released ✨
