### ISSUE TITLE
craft\helpers\App\mutexConfig is deprecated but craft\helpers\App\dbMutexConfig breaks with isWindows option

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/cms#7242]
### Description

I have handling for a local development environment because it is a Windows host, with the Mutex config described here: https://github.com/craftcms/cms/issues/4355

In Craft 3.5 is appears mutexConfig is deprecated and should be dbMutexConfig, however, applying this causing the following error:

```
Exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: yii\mutex\MysqlMutex::isWindows'
```

The isWindows option exists in the FileMutex, not MySQL mutex. Does the Windows FS mutex config need a slight refactor for 3.5 to avoid the deprecation error?

![image](https://user-images.githubusercontent.com/8067792/101738726-7b31f180-3abe-11eb-9bb6-67b67c7f3413.png)

### Additional info

- Craft version: 3.5.16
- PHP version: 7.3
- Database driver & version: MySQL 5.7

**Comment by brandonkelly** [comment]
The DB mutex classes don’t care whether it’s a Windows file system or not – which is one of the reasons we’ve deprecated the file-based one.

You can safely delete that whole function now.

**Comment by jamesmacwhite** [comment]
@brandonkelly Thank you for clarifying. So isWindows isn't needed anymore in 3.5+?

I'm just thinking the file mutex is still likely going to benefit from being told it's a Windows file system: https://www.yiiframework.com/doc/api/2.0/yii-mutex-filemutex

Given various commands can fail because unix-like commands will tried to be executed on a Windows FS and it ends up in a bad time, I remember it back in 2019.

**Comment by brandonkelly** [comment]
> So isWindows isn't needed anymore in 3.5+?

Not if you’re going with the now-default DB-based mutex driver.

> I'm just thinking the file mutex is still likely going to benefit from being told it's a Windows file system: https://www.yiiframework.com/doc/api/2.0/yii-mutex-filemutex

That’s the file-based driver.

**Comment by jamesmacwhite** [comment]
Thanks! Makes sense. I'll test with the DB driver.

Perhaps the docs might need an update for Craft 3.5  where the file mutex isWindows option is mentioned at some point.

**Comment by brandonkelly** [comment]
I just improved the docblock for `craft\helpers\App::mutexConfig()`, for the next release.

**Comment by jamesmacwhite** [comment]
Thank you! That will be useful to others. Just as an additional note Craft Nitro has a direct reference to the older file mutex here: https://craftcms.com/docs/nitro/usage.html#adding-sites

Might be worth having a Craft 3.5+ specific note at some point.

**Comment by brandonkelly** [comment]
Doh, thanks for pointing that out! Just went ahead and removed the tip.
