### ISSUE TITLE
FolderCriteria change PHPDoc for name attribute

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#7243]
### Description

Your FolderCriteria Class contains the following
```PHP
/**
 * @var string|null Name
 */
public $name;
```
this implies you could actually search a folder by it's name and pass a string 

```PHP
$folderCriteria = new FolderCriteria();
$folderCriteria->volumeId = $volume->id;
$folderCriteria->name = $someName;
```

While the above works in 99% of the cases, passing a name like "A, B or C" will trigger the `Db::parseParam`
```PHP
if ($criteria->name) {
    $query->andWhere(Db::parseParam('name', $criteria->name));
}
```
So it splits the string and the folder cannot be found.
To get around this you need to pass an array 
```PHP
$folderCriteria = new FolderCriteria();
$folderCriteria->volumeId = $volume->id;
$folderCriteria->name = [$someName];
```

So it would be nice if you could either change the PHPDoc to `string|string[]|null` or remove the `Db::parseParam` in Craft 4.0 for it

**Comment by brandonkelly** [comment]
Just added `string[]` to the type list. Also added a tip that you can pass the value through [craft\helpers\Db::escapeParam()]](https://docs.craftcms.com/api/v3/craft-helpers-db.html#method-escapeparam) if searching for a folder name that contains a comma.
