### ISSUE TITLE
Please bring back plugin developer identification

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#7254]
I'm not sure exactly when they disappeared, but I've always found it really helpful that installed plugins would list the name of the developer who created them. I actually took it for granted that the name of the plugin developer would always appear beside the name of the plugin.

Now, without that information, it can actually be very confusing as to where each plugin came from...

![no-companies@2x](https://user-images.githubusercontent.com/5309692/101937612-f2d34f80-3b96-11eb-8bcc-3f0fc9e9da05.png)

The most immediate issue is that it makes it somewhat harder to track down the source of a plugin. Today I tried to recommend the Craftnet CP plugin to someone, but I couldn't find it in the plugin store. So I wanted to track down the original repo, to see if it still exists, but... ? I had to open up the `composer.json` file in order to figure out who made that plugin.

Would you mind bringing back the developer names? It was extremely helpful to be able to see them all at a glance.

Thanks! 🙂

**Comment by brandonkelly** [comment]
Added for 3.6!

<img width="510" alt="The Settings → Plugins page, showing that each plugin now lists who developed it." src="https://user-images.githubusercontent.com/47792/102102491-b98e2000-3de0-11eb-8b1e-c7a43d9a1de0.png">

**Comment by lindseydiloreto** [comment]
Amazing!! That looks fantastic, thanks @brandonkelly! 🍺

**Comment by brandonkelly** [comment]
Craft 3.6 RC2 is out now with this change.

**Comment by lindseydiloreto** [comment]
Excellent! Looking forward to it, thanks! 👏

**Comment by brandonkelly** [comment]
Craft 3.6 has now been officially released ✨
