### ISSUE TITLE
':empty:' not working when passed to array of elements

### ISSUE THREAD

**Issue by bransinanderson** [craftcms/cms#7256]
### Description
Simple relationships with entries field unable to pass ':empty:' to array. The goal is to query results where entries field **relatedDrinks** is ':empty:' **OR** is related to a specific entry ID.

### Steps to reproduce
Initially tried to achieve this in the Element API. Tried this in Twig as well and experiencing the same issue.

relatedDrinks is an entries field.

Element API example
```
// WORKS, results returned where relationship field is empty
'relatedDrinks' => ':empty:'

// DOES NOT WORK, no results returned where relationship field is empty
'relatedDrinks' => [':empty:']

// WORKS, results related to drink ID returned
'relatedDrinks' => [$myDrinkId]

// DOES NOT WORK, results related to drink ID returned, no results returned with empty
'relatedDrinks' => [':empty:', $myDrinkId]
```

Twig example - only returns entries related to myDrinkId, but not entries where relatedDrinks entries field is ':empty:'.
```
{% set entries = craft.entries()
	.section(mySections)
	.relatedDrinks([ 'or', ':empty:', myDrinkId ]).all()
```

### Additional info

- Craft version: 3.5.15.1
- PHP version: 7.4.9
- Database driver & version: MySQL 5.7.30
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
Not really a bug since the current behavior is expected; querying for `:empty:` / `:notempty:` relation fields works quite a bit differently than searching for the existence of specific relations.

That said, I managed to find a way to make this possible, so you will be able to pass `[':empty:', $myDrinkId]` in the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.17 is out now with that change.

**Comment by bransinanderson** [comment]
Thank you so much for this Brandon!

**Comment by cherrykoda** [comment]
@brandonkelly Im using this same scenario and it doesnt seem to be fixed for me in twig...

{% set results = craft.entries().section('events').eventRegistrationAccess'(['or', ':empty:', testCategory ]) %}

**Comment by brandonkelly** [comment]
@cherrykoda Remove the `'or',`.

**Comment by cherrykoda** [comment]
Works!! Thanks so much!

**Comment by samhibberd** [comment]
@brandonkelly this was super useful, although be great to see some detail in the docs, unless i missed it! Great work.
