### ISSUE TITLE
Field Creation on save go back to field listing page

### ISSUE THREAD

**Issue by CreateSean** [craftcms/cms#7262]
### Description

In the past when creating a new field on save you would end up back on the list page. However currently when saving it takes you to the field edit page, which I don't need to see again since I just created the field.

I'd like to see it so on saving a new field it takes you back to the listing page as it worked previously. Now I have to keep clicking out of the new field and it's annoying.

**Comment by brandonkelly** [comment]
If you click the Save button, or press Return when an input is focussed (except multiline text inputs), it will submit the form and take you back to the Fields index page.

**Comment by CreateSean** [comment]
Using the hotkeys `ctrl+s` does not take you back to the fields index page though. I always use the hotkeys as it's faster than using a mouse.

**Comment by brandonkelly** [comment]
Yeah but so is <kbd>Return</kbd>.
