### ISSUE TITLE
Asset bundle registration fails in 3.5.16 in module

### ISSUE THREAD

**Issue by justinholtweb** [craftcms/cms#7263]
### Description
I'm wondering if something changed between Craft 3.5.15.1 and 3.5.16 in registering asset bundles in modules. We have a module where we are including an asset bundle that contains some JS that writes out a button for a controller action on a Commerce orders list in the admin. In our module init method we are registering the asset bundle on a template event as so: 

```php
// Add custom export button to Commerce Orders screen
if (Craft::$app->getRequest()->getIsCpRequest()
    && Craft::$app->getRequest()->getSegment(1) === 'commerce'
    && Craft::$app->getRequest()->getSegment(2) === 'orders'
) {
    Event::on(
        View::class,
        View::EVENT_BEFORE_RENDER_TEMPLATE,
        function (TemplateEvent $event) {
            try {
                Craft::$app->getView()->registerAssetBundle(OrderExportAsset::class);
            } catch (InvalidConfigException $e) {
                Craft::error(
                    'Error registering AssetBundle - '.$e->getMessage(),
                    __METHOD__
                );
            }
        }
    );
}
```

This works totally fine in 3.5.15.1 but in 3.5.16 the registration fails, with no other changes. The catch returns an error Failed to instantiate component or class "modules\orderexport\assetbundles\OrderExportAsset"
I checked through the changelog but I'm not seeing any recent change that would have affected this, wondering if its a bug

### Steps to reproduce

1. Register an asset bundle in Craft 3.5.15.1. Include it when a template renders from a plugin init method.
2. Update to Craft 3.5.16, asset bundle no longer seems to register. 

### Additional info

- Craft version: 3.5.16
- PHP version: 7.2.24
- Database driver & version: MySQL 5.7.32
- Plugins & versions: Amazon S3 (1.2.11), Contact Form 2.3.2.1(2.2.7), Contact Form Honeypot (1.0.2), Control Panel CSS (2.2.1), Cookies (1.1.12), Craft Commerce (3.2.12), Linkit (1.1.12.1), Neo (2.8.14), Redactor (2.8.4), Shield (1.0.4), Stripe for Craft Commerce (2.3.2.1), Super Table (2.6.4), Table Maker (2.0.1), TaxCloud (1.0.5)

**Comment by brandonkelly** [comment]
That code works fine for me on my end, and the event is getting triggered before any asset bundles would need to have been registered. So not sure what to make of that. If you send your Composer files, a database backup, and your module files into support@craftcms.com we can try to look into it further.
