### ISSUE TITLE
Custom Header Column headings not translated on Element Index pages

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#7272]
### Description

When overriding the column heading via Element Index settings, the custom heading can’t be translated.

<img width="310" alt="Bildschirmfoto 2020-12-15 um 18 09 24" src="https://user-images.githubusercontent.com/7516543/102247831-c1dd7c80-3f00-11eb-9421-6f74fad4e254.png">

### Additional info

- Craft version: 3.5.16

**Comment by brandonkelly** [comment]
It’s working as expected on my end, and can see that the heading is in fact going through `|t('site')` here:

https://github.com/craftcms/cms/blob/1d69bfb0308d3b56990d7b257591071992d7a297/src/templates/_elements/sources.html#L49

Where exactly are you seeing it?

**Comment by carlcs** [comment]
No, not the headings in the sources list. I’m talking about the heading for title column (or header column is how you call it, I guess) in the elements table itself, which can be customized since https://github.com/craftcms/cms/commit/288fce1.

**Comment by brandonkelly** [comment]
Right, sorry, fixed now for the next release.

**Comment by brandonkelly** [comment]
3.5.17.1 is out now with that fix.
