### ISSUE TITLE
[3.6-RC2] Labels overly verbose & awkward

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#7275]
### Description

Some of the new accessibility labels are a little out of control. There's a lot of redundant text cluttering the UI now. I've also noticed there appears to be some issues with label text wrapping too early. Here are a few examples that could use some love:

![image](https://user-images.githubusercontent.com/3810939/102281301-a96b6300-3efc-11eb-8a45-f8de7c60980b.png)
![image](https://user-images.githubusercontent.com/3810939/102281430-e33c6980-3efc-11eb-94b2-112a635af115.png)
![image](https://user-images.githubusercontent.com/3810939/102281483-0404bf00-3efd-11eb-8042-4407cd3902ac.png)
![image](https://user-images.githubusercontent.com/3810939/102281502-0b2bcd00-3efd-11eb-902c-a0de15e21a3c.png)
![image](https://user-images.githubusercontent.com/3810939/102281535-1c74d980-3efd-11eb-94e0-d7c33bfee9f7.png)
![image](https://user-images.githubusercontent.com/3810939/102281604-41694c80-3efd-11eb-9ce0-cecdf5f31d2d.png)
![image](https://user-images.githubusercontent.com/3810939/102282755-1849bb80-3eff-11eb-9b7b-cc58d5a880d8.png)
![image](https://user-images.githubusercontent.com/3810939/102282699-fb14ed00-3efe-11eb-8a60-7305c298915f.png)

### Additional info

- Craft version: 3.6 RC2

**Comment by brandonkelly** [comment]
Doh, those were not intended. Will fix…

**Comment by brandonkelly** [comment]
Just released 3.6.0-RC2.1 with a fix for this.
