### ISSUE TITLE
Requesting an easier way to return to control panel after impersonating a user

### ISSUE THREAD

**Issue by sparkalow** [craftcms/cms#7281]
### Description
Impersonating a user is a great feature. Thank you! It's especially useful for some e-commerce administrators. Id like to request that getting back to the control panel as an admin, after impersonating a user, be improved if possible.

Currently, you impersonate a user from the control panel and are taken to the frontend. When you're ready to return to the control panel you must logout of the impersonated user's account and re-login to the admin.  

I'd like to request a way to get back to the admin without logging out and then logging back in. Not sure the best way to handle this, but perhaps a route and maybe an event/session var to allow developers to output a button returning to the control panel on the frontend would work.

**Comment by brandonkelly** [comment]
Just came up with what I think is a pretty nice solution to this.

In Craft 3.6 there will be a new user action after “Login as [username]”, called “Copy impersonation URL”:

<img width="371" alt="The user action menu, with the new “Copy impersonation URL” option highlighted" src="https://user-images.githubusercontent.com/47792/102502373-62cc5480-4033-11eb-8c14-4bf07f462233.png">

When you click it, Craft will generate a single-use tokenized URL, and then prompt you to copy it:

<img width="537" alt="The “Copy URL” prompt" src="https://user-images.githubusercontent.com/47792/102502483-82637d00-4033-11eb-8085-930849c0abbc.png">

You’ll then be able to copy the URL and paste it into a new private/incognito window, which will log you in as the user and redirect you to either the control panel or front end, depending on whether they have CP access.

**Comment by brandonkelly** [comment]
Craft 3.6 RC3 is out now with that change.

**Comment by brandonkelly** [comment]
Craft 3.6 has now been officially released ✨
