### ISSUE TITLE
Asset field error when upload image since Craft 3.5.17

### ISSUE THREAD

**Issue by j0h4n3s** [craftcms/cms#7284]
### Description
When uploading an asset (image) into my matrix field, I now get the following JavaScript prompt: 
Argument 1 passed to craft\services\Elements::getElementById() must be of the type int, string given, called in /Users/[myusername]/Sites/[mywebsite]/vendor/craftcms/cms/src/controllers/AssetsController.php on line 319

### Steps to reproduce

1. Create a Matrix field with an Asset field in it, assign to an entry
2. Upload an asset to the field
3. It will throw the error above.

### Additional info

- Craft version: 3.5.17
- PHP version: 7.4.2
- Database driver & version: MySQL 5.7.26
- Plugins & versions:

Amazon S3 1.2.11
Guest Entries 2.3.0
ImageOptimize 1.6.20
Mailjet 1.2.2
Mollie Payments 1.6.1
Redactor 2.8.5
Webhooks 2.3.2

**Comment by j0h4n3s** [comment]
This does not happen when I upload the images to the main assets section in Craft, /admin/assets/

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just released Craft 3.5.17.1 with a fix.
