### ISSUE TITLE
Error message loging screen

### ISSUE THREAD

**Issue by ajanec01** [craftcms/cms#7288]
### Error not communicated to screen reader users

There's an error message for giving incorrect username or password. It's treated as [status message by WCAG](https://www.w3.org/TR/WCAG21/#status-messages) so needs either `role="alert"` or `aria-live="polite"`.  

![error message saying Invalid username or password](https://user-images.githubusercontent.com/47136246/102556297-783b9000-40c0-11eb-8f9e-16ea5e2842da.png)

### Additional info

- Craft version: 3.5.17

**Comment by missmatsuko** [comment]
I happened to be working on the login page this week and opened PR #7276 including a fix for this issue. 🙂

**Comment by brandonkelly** [comment]
#7276 has been merged in for the next release!

**Comment by brandonkelly** [comment]
Craft 3.5.18 is out now with that fix ✨
