### ISSUE TITLE
Can't edit tab name after saving it as a long string with no spaces

### ISSUE THREAD

**Issue by missmatsuko** [craftcms/cms#7298]
### Description
I saved a really long gibberish tab name with no spaces and now I can't click the settings gear to change it to something reasonable. Oops 😅

![Screenshot of a very long tab name in the field layout editor.](https://user-images.githubusercontent.com/17884198/102677607-0ca50180-4158-11eb-816f-021826d867d4.png)

### Steps to reproduce
1. Save a very long tab name with no spaces

### Additional info
- Craft version: 3.5.17.1

**Comment by brandonkelly** [comment]
Fixed that for the next release.
