### ISSUE TITLE
Tabs redesign

### ISSUE THREAD

**Issue by missmatsuko** [craftcms/cms#7299]
### Description

Proposal to change the entry edit tab design so that the tabs order and position don't change depending on what's selected, and tab names don't need to be concatenated.

A design similar to the one used in Firefox could work:

<img width="587" alt="Screenshot of Firefox browser tabs." src="https://user-images.githubusercontent.com/17884198/102677277-8cca6780-4156-11eb-848e-c1a758c607cc.png">

Google Sheets uses a similar design:
<img width="1036" alt="Screenshot of Google Sheets tabs." src="https://user-images.githubusercontent.com/17884198/102729450-a817ad00-42e5-11eb-8952-1f8617d9fa5b.png">

**Related issues:**
- #6230
- #7140

**Comment by brandonkelly** [comment]
CP tabs have been redesigned for Craft 3.7.

Now all tabs are shown within a horizontal-scrollable tab bar, and whenever there’s not enough room to show them all, a menu button is shown which opens a menu that lists all available tabs:

<img width="678" alt="The “List all tabs” menu" src="https://user-images.githubusercontent.com/47792/119900816-e26f2100-bef9-11eb-9965-8b3ab8355328.png">

General tab focus behavior is the same as what we settled on for #7140, with the only significant different being you can now arrow the focus to tabs that are out of view (which will automatically scroll them into view).
