### ISSUE TITLE
Can't leave dropdown field empty even if it's optional

### ISSUE THREAD

**Issue by missmatsuko** [craftcms/cms#7307]
### Description
It seems to me that if a dropdown is not required, it should be allowed to be empty.

Currently the developer has to add an empty option and mark it as the default option in order to achieve this.

If they do that, they probably won't be able to use the same dropdown field as required in other areas since the first option will be read as a valid selection when it's actually "empty".

### Steps to reproduce
1. Create a dropdown field, leave it as not required.
2. When entering data in the field, the first option is already selected.

### Additional info
- Craft version: 3.5.17.1

**Comment by brandonkelly** [comment]
I think dropdown, checkbox, and lightswitch fields are special cases. They are generally considered “required” without being explicitly marked as required. If they are explicitly marked as required, the required indicator would just add extra UI noise for the author, as they didn’t have a way to submit the form without a value in the first place.

(Craft’s CP follows that convention; we never mark those field types as required even though they are.)

If Craft started adding a blank option to Dropdown fields, it would break all the forms where the developer had intended the field to be required even if not explicitly marked as such. So we’d need to make it something the field opts into. And we’d need to add another setting for defining the blank option’s label (e.g. “Choose a color…”). At which point, we’re not saving anyone any time over just manually creating the blank option themselves.



> Currently the developer has to add an empty option and mark it as the default option in order to achieve this.
> 
> If they do that, they probably won't be able to use the same dropdown field as required in other areas since the first option will be read as a valid selection when it's actually "empty".

Just tested this and that’s actually incorrect. Dropdown fields do in fact get a validation error if they are marked as required and an empty option was selected.

<img width="242" alt="A Dropdown field with a validation error saying that it was required." src="https://user-images.githubusercontent.com/47792/103354407-4a5f2f80-4a60-11eb-9ca7-1b4f6fc29c9f.png">

Relevant code:

https://github.com/craftcms/cms/blob/c4b999b325736968a05d3bcc1a5a2444dfbe9323/src/fields/BaseOptionsField.php#L361-L366

**Comment by missmatsuko** [comment]
> I think dropdown, checkbox, and lightswitch fields are special cases. They are generally considered “required” without being explicitly marked as required.

Hmm I don't really agree with that, except for lightswitch which is pretty much can only be on/off. I would agree with that for radio boxes, though. But anyways, the behaviour of the "required" toggle on dropdown fields is not really clear?

> If Craft started adding a blank option to Dropdown fields, it would break all the forms where the developer had intended the field to be required even if not explicitly marked as such. So we’d need to make it something the field opts into.

Yeah, I would suggest making such changes for 4.

> And we’d need to add another setting for defining the blank option’s label (e.g. “Choose a color…”). At which point, we’re not saving anyone any time over just manually creating the blank option themselves.

I would suggest not having a blank option label, since it has similar problems as described in #7303. Actually I think it's worse since it's coded and visually looks exactly like a valid option.

> Just tested this and that’s actually incorrect. Dropdown fields do in fact get a validation error if they are marked as required and an empty option was selected.

I mean the same field is not as reusable as other fields since it cannot be used as required in one section and optional in another by toggling the "required" option in the field layout manager. Since currently I have to explicitly add a "blank" option and the field cannot be saved with the blank option selected regardless if the field is "required" or not. Does that make sense?

**Comment by brandonkelly** [comment]
> I mean the same field is not as reusable as other fields since it cannot be used as required in one section and optional in another by toggling the "required" option in the field layout manager. Since currently I have to explicitly add a "blank" option and the field cannot be saved with the blank option selected regardless if the field is "required" or not. Does that make sense?

If you ignore the usability/accessibility issues with a blank option, then if you want your Dropdown field to be submittable w/out a value, you would add a blank option, and then mark it as required in contexts where another option **must** be selected to pass validation.

> Hmm I don't really agree with that, except for lightswitch which is pretty much can only be on/off. I would agree with that for radio boxes, though.

Curious why you agree for lightswitches and radio buttons, but not dropdowns? From a content modeling perspective, radio buttons and dropdowns (w/out a blank option) are identical (author has no choice but to submit the input with one of the options selected).

What would the benefit of marking any of those field types as required, if there’s no way to submit the form without them having a value in the first place?

In any case, I think this is going to be fully resolved once we add support for conditional fields (#805), at which point you could start adding a separate Lightswitch field, and only show/validate a subsequent Dropdown field in the event that the Lightswitch is enabled (for example).

**Comment by missmatsuko** [comment]
> If you ignore the usability/accessibility issues with a blank option, then if you want your Dropdown field to be submittable w/out a value, you would add a blank option, and then mark it as required in contexts where another option must be selected to pass validation.

> What would the benefit of marking any of those field types as required, if there’s no way to submit the form without them having a value in the first place?

Okayy I think I must've been doing something weird earlier. Getting the behaviour of how the required option on dropdowns now. I think I'll just add dropdown to the placeholder issue. 

> Curious why you agree for lightswitches and radio buttons, but not dropdowns? From a content modeling perspective, radio buttons and dropdowns (w/out a blank option) are identical (author has no choice but to submit the input with one of the options selected).

Ahh idk I'm just confusing myself more the more I think about it haha.
