### ISSUE TITLE
Undefined variable $e in console/Application.php:83

### ISSUE THREAD

**Issue by jellingsen** [craftcms/cms#7309]
### Description
We start our local development environment with docker by running `docker-compose up`, and we have a queue-worker that is running `php craft migrate/all` during startup. 
For some reason the action fails (might be that the database is not yet fully initialized), but the error is:
```
PHP Notice 'yii\base\ErrorException' with message 'Undefined variable: e'

in /srv/vendor/craftcms/cms/src/console/Application.php:83
```
Now this happens because the `Console::outputWarning()`-function is called outside the try-catch, and for some reason the SQL-query inside the try block does not fail, and the exception is not actually set.

### Steps to reproduce

This might be hard to reproduce, but the code should check if the exception variable is set before using it in the output.

### Additional info

- Craft version: Craft Pro 3.5.15.1
- PHP version: 7.4.2
- Database driver & version: MySQL 5.7.31

**Comment by brandonkelly** [comment]
Thanks for reporting that. Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.18 is out now with that fix ✨
