### ISSUE TITLE
Some Formatting Locale bugs

### ISSUE THREAD

**Issue by missmatsuko** [craftcms/cms#7312]
### Description
I think this is a bug... I changed my Formatting Locale to Japanese for testing, and the users table seems to display the "Date Created" value by each user's formatting locale, rather than the formatting locale I've set on my account.

<img width="983" alt="Screen shot of users list." src="https://user-images.githubusercontent.com/17884198/102816745-5f163600-4383-11eb-992e-f4a07124ccf4.png">

Additionally, I think the week start date values should be updated when the formatting locale is changed. Currently it only updates after saving and refreshing the page:
<img width="433" alt="Screenshot of Formatting Date and Week Start Day fields." src="https://user-images.githubusercontent.com/17884198/102817003-cb913500-4383-11eb-8891-b6a242bd3f61.png">

### Steps to reproduce
1. Change Formatting Locale value to something other than the current language.
2. See that the Week Start Day is unchanged until saving the settings.
3. Check the users table and see that the Date Created is in different formats.

### Additional info
- Craft version: 3.5.17.1

**Comment by brandonkelly** [comment]
Date values are rendered using [craft\i18n\Formatter::asTimestamp()](https://docs.craftcms.com/api/v3/craft-i18n-formatter.html#method-astimestamp) (same function that the [|timestamp](https://craftcms.com/docs/3.x/dev/filters.html#timestamp) filter uses), so the different formats you are seeing there are due to the different time scales the dates have relative to the current date/time. If each of the Date Created values were more than 7 days prior, they would each be output using a Japanese date format.

> Additionally, I think the week start date values should be updated when the formatting locale is changed. Currently it only updates after saving and refreshing the page:

Can you post a new issue (enhancement) about that?

**Comment by missmatsuko** [comment]
Hmm it seems weird to me that the weekday is translated to the formatting locale setting but "today" and "yesterday" stay in English regardless? Especially when comparing the dates in a column.

**Comment by brandonkelly** [comment]
Agree it’s a bit weird. Happening because weekday names are sourced from the locale data, whereas “Yesterday” is coming from the message translations (which are correctly sourced based on your preferred _language_ rather than your preferred formatting locale).

Maybe if the

**Comment by brandonkelly** [comment]
Just fixed this by changing `asTimestamp()` to pull the  week day name from the application language, rather than the formatting locale.

**Comment by missmatsuko** [comment]
Would that affect the date-picker calendar UI?

![Screenshot of date picker calendar UI with Japanese date formatting locale.](https://user-images.githubusercontent.com/17884198/103595773-290fa080-4eb1-11eb-89e8-e50fb75c9023.png)

**Comment by brandonkelly** [comment]
Doh, yeah the same change needed to happen there as well. Done.
