### ISSUE TITLE
Fields excluded from Project Config

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#7324]
### Description

The following **Settings > Sections** fields are being mistakenly excluded from the Project Config...

![excluded from PC@2x](https://user-images.githubusercontent.com/5309692/102944963-3bc9b480-4471-11eb-82a3-3697ed5ae2c9.png)

### Steps to reproduce

1. Make changes to the fields noted above.
2. Note that those changes are not reflected in the Project Config.

### Additional info

- Craft version: 3.5.17.1
- PHP version: 7.4.13

**Comment by brandonkelly** [comment]
They’re there, under `siteSettings`.

**Comment by brandonkelly** [comment]
Try running `php craft project-config/rebuild` if you’re definitely not seeing them.
