### ISSUE TITLE
Search for related category in entries index not working when name of category is not english (latin alphabet)

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#7328]
### Description

In the CP, when a user performs a search in the entries index with the name of a category that is related to some articles and the name of that category is not English, then the search comes up empty. The same search for a category with an English name works as expected.

In my case, the language of the category's name is **Greek**.

### Steps to reproduce

1. Create a field with type "Categories". Check the "Use this field’s values as search keywords" checkbox (not sure if this is needed but do it anyway).
2. Add this field to a section's layout.
3. Create a category with a name using an alphabet other than English, probably not using Latin characters.
4. Relate this category to some entries in the section from step 2.
5. Go to the entries' index and try to search with the name of the category from step 3.

### Additional info

- Craft version: Craft Pro 3.5.17.1
- PHP version: 7.4.13
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Contact Form 2.2.7, Contact Form Honeypot 1.0.2, Logs 3.0.3, Obfuscator 1.0.4, Redactor 2.8.5

**Comment by brandonkelly** [comment]
Can you provide an example category name?

**Comment by thupsi** [comment]
> Can you provide an example category name?

Yes, let's say "βιβλιοπαρουσίαση"

**Comment by brandonkelly** [comment]
I’m unable to reproduce this.

<img width="868" alt="A screenshot of the Entries index page, while searching for “Βιβλιοπαρουσίαση” and showing one result based on a related category title match" src="https://user-images.githubusercontent.com/47792/103594275-08dde280-4ead-11eb-8f9a-c359a636f32e.png">

Double-check that your Categories field’s “Use this field’s values as search keywords” setting is checked, and then run this terminal command:

```bash
> php craft resave/entries --update-search-index --section=yourSectionHandle
```

**Comment by thupsi** [comment]
Yep, that worked! I was almost certain that I had tried resaving the entries and clearing the search index, but obviously I missed something. 

Thanks a lot Brandon! Have a great new year! 🥇

**Comment by brandonkelly** [comment]
You too!
