### ISSUE TITLE
When creating a new tab in the field layout, pressing "Cancel" creates a new tab anyway

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#7333]
Not a huge issue, but figured it was something worth noting so it can get fixed.

### Steps to reproduce

1. Press `+ New Tab` from an entry type's field layout
2. Press `Cancel`

### Additional info

- Craft version: 3.5.17.1

**Comment by owldesign** [comment]
Ahhhh man after hours of this happening to me, I thought I was loosing it. Good thing I saw this, now I know I'm not alone!

**Comment by brandonkelly** [comment]
The prompting for the tab name automatically was added as a convenience (see #1956), but I can see how the behavior could be confusing. Just changed it for Craft 3.6, so if no tab name is entered or the Cancel button is pressed, the tab won’t get created in the first place.

**Comment by brandonkelly** [comment]
Craft 3.6 has now been officially released ✨
