### ISSUE TITLE
Modifying query limit "prepElementQueryForTableAttribute" doesn't update pagination on element index page

### ISSUE THREAD

**Issue by owldesign** [craftcms/cms#7334]
### Description

Hi, I noticed that when working with custom elements and trying to modify query limit via `prepElementQueryForTableAttribute` function, the pagination numbers are not reflected correctly.

In the example bellow I'm removing the limit completely, I get all elements as expected. However, the pagination at the bottom is still displaying with page numbers and arrows. Pagination will go to next page and load elements thinking that each page is 100 (default) limit.

```
protected static function prepElementQueryForTableAttribute(ElementQueryInterface $elementQuery, string $attribute)
    {
        $elementQuery->limit(null);

        parent::prepElementQueryForTableAttribute($elementQuery, $attribute);
    }
```

I've tested this with setting small limit (5 or so) and correct amount of elements get queried. 

### Additional info

- Craft version: 3.5.17.1
- PHP version: 7.4
- Database driver & version: My SQL 8.0

**Comment by brandonkelly** [comment]
The reason you’re seeing this behavior is because `prepElementQueryForTableAttribute()` doesn’t get involved in pagination, which is based on `count` queries. But you should not be modifying the limit in the first place; that’s not what that method was intended for.
