### ISSUE TITLE
Change the Attribute of the Entry Type Section in the migration

### ISSUE THREAD

**Issue by mmikhalko** [craftcms/cms#7346]
### Description
When I try to change the attribute of the Entry Type Section for instance hasTitleField it doesn't save   

### Steps to reproduce

1. Create the new migration
2. Add the example script below

```php
 public function safeUp() {
    $section = Craft::$app->sections->getSectionByHandle('nameOfSection');
    $types = $section->getEntryTypes();
    $entryType = $types[0];
    $entryType->hasTitleField = "0";
    Craft::$app->sections->saveEntryType($entryType);
}

```

### Additional info

- Craft version: 3.5.14
- PHP version: 7.3.15
- Database driver & version: MySQL 5.6.39
- Plugins & versions:

**Comment by brandonkelly** [comment]
What does `$entryType->getErrors()` return?

**Comment by mmikhalko** [comment]
> What does `$entryType->getErrors()` return?

`var_dump($entryType->getErrors());`

returns 

`array(0) {
}`

`$savedStatus = Craft::$app->sections->saveEntryType($entryType);`

And also $savedStatus is true

**Comment by brandonkelly** [comment]
Sounds like the change was in fact made then. Maybe you have project config changes that overrode it?

**Comment by mmikhalko** [comment]
> Sounds like the change was in fact made then. Maybe you have project config changes that overrode it?

Yes, it helped me. Thanks a lot!
