### ISSUE TITLE
Asset location and if statement

### ISSUE THREAD

**Issue by bleepsandblops** [craftcms/cms#7353]
### Description
 I have several sections sharing an Assets field. I'm trying to customise the asset location. This doesn't work
`{% if section.handle == 'exhibitions' %}{section.handle}/{slug}{% endif %}`
(*The Main asset field’s Asset Location setting has an invalid subpath* on non exhibitions entries when I resave all the entries)

but this does:
`test{% if section.handle == 'exhibitions' %}{section.handle}/{slug}{% endif %}`
and it also works if I replace 'test' by a space

### Steps to reproduce

1.
2.

### Additional info

- Craft version: 3.5.17.1
- PHP version: 7.2.33
- Database driver & version: MySQL 5.7.31
- Plugins & versions:
![Screenshot 2021-01-05 at 17 29 07](https://user-images.githubusercontent.com/1942313/103671710-938d1300-4f7b-11eb-81e6-0fb3f9c04fc2.png)

**Comment by brandonkelly** [comment]
Hm… definitely a bug but I’m not sure what the best way to fix this would be. As for as Craft is concerned, if that comes back as empty, it’s assumed that there was a variable that couldn’t be resolved yet.

You could fix this if you place all of your assets in a subfolder – something like:

```twig
foo{{ section.handle == 'exhibitions' ? "/#{section.handle}" }}
```

**Comment by bleepsandblops** [comment]
Thanks for having a look @brandonkelly. I feel like 'empty' should be considered a valid response, and that there should be another way to communicate that a variable couldn't be resolved - but I don't know how the internal piping works.

**Comment by brandonkelly** [comment]
Yeah it’s tricky since the subfolder setting accepts any sort of Twig code. The situation we’re concerned about is if the subfolder is set to a property that isn’t actually known yet for new entries, e.g. (`{id}`, `{uid}`, `{author.x}`, {myCategoriesField.one().slug}`, etc. In these cases. So when the rendered template comes back blank (or with an empty segment), the Assets field temporarily gets set to the user’s Temp Uploads volume.

**Comment by bleepsandblops** [comment]
Right... then maybe some kind of pseudo variable like :empty: 
`{% if section.handle == 'exhibitions' %}{section.handle}/{slug}{% else %}:empty:{% endif %}`

**Comment by brandonkelly** [comment]
Brilliant! Just implemented that for the next release. Went with `:ignore:` instead of `:empty:`.

**Comment by brandonkelly** [comment]
Craft 3.5.18 is out now with that change ✨
