### ISSUE TITLE
frontend register form + useEmailAsUsername => username cannot be blank

### ISSUE THREAD

**Issue by rauwebieten** [craftcms/cms#7357]
### Description

after enabling frontend user registration:
When using emails as usernames, and submitting a blank email in the form,
There is still a validation error "username cannot be blank". 

(This validation error does not occur when filling out a email adres in the form.)

I think this validation error should be surpressed when useEmailAsUsername=true.

Temporary fix: create module, listen for event, and manually supress username error on your registration form.

### Steps to reproduce

1. enable frontend user registration
1. set in config useEmailAsUsername: true
2. create frontend registration form (as explained in docs).
3. Submit empty form

### Additional info

- Craft version: Craft CMS 3.5.17.1
- PHP version: 7.3

**Comment by brandonkelly** [comment]
Just fixed that for the next release. Thanks for reporting!

**Comment by brandonkelly** [comment]
Craft 3.5.18 is out now with that fix ✨

**Comment by rauwebieten** [comment]
Thank you!
