### ISSUE TITLE
Wishlist Plugin Loads Empty Blocks Multiple Times Against User

### ISSUE THREAD

**Issue by chandamotiyani** [craftcms/cms#7358]
Version Info:
Craft CMS Version: 3.5.15.1
Wishlist Plugin: 1.4.3

The wishlist section is behaving weirdly:
/wishlist/lists/p6 - screen short is attached it shows 0 items multiple times against each user unnecessarily 

![Screen Shot 2021-01-07 at 1 36 55 pm](https://user-images.githubusercontent.com/16190427/103847646-aecd5f00-50f0-11eb-8d23-db619745ee7a.png)

In User details under wishlist the name of the logged in user is apearing instead of the user whose details are being viewed.
Multiple blank entries are coming for the wishlist section too. please find attachment - Go to the Login to Admin Panel --> Users --> Detail of User --> Under Wishlist tab

![Screen Shot 2021-01-07 at 2 05 52 pm](https://user-images.githubusercontent.com/16190427/103848341-1041fd80-50f2-11eb-9c49-73c58a2f9df6.png)

The query is that why multiple times the same user is listed with 0 items in wishlist! If the signed in user or guest user hasn't added anything in the wishlist then why does the records are being shown multiple times! Or even if they added anything then why does it appear multiple times!

Attaching more screenshots to elaborate!
![Screen Shot 2021-01-07 at 2 20 31 pm](https://user-images.githubusercontent.com/16190427/103848974-8eeb6a80-50f3-11eb-8a86-ca60842535f7.png)

![Screen Shot 2021-01-07 at 1 36 55 pm](https://user-images.githubusercontent.com/16190427/103849354-60ba5a80-50f4-11eb-8467-bfa4888d669f.png)

**Comment by brandonkelly** [comment]
Please report that over at https://github.com/verbb/wishlist/issues.
