### ISSUE TITLE
Incorrect focus on new entries when there is a Matrix field with min blocks set

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#7363]
### Steps to reproduce

On a fresh Craft installation:

1. Create a section
2. Create a Matrix field an set its minimum number of blocks to 1
3. Assign Matrix field to the section after the title.
4. Create a new entry in the section.

Notice that the focus is on the Matrix field and not the title.

Only happens with the minimum num of blocks set to 1 and only happens to new entries (existing entries have the correct focus on title).

### Additional info

- Craft version: 3.5.17.1
- PHP version: 7.4
- Database driver & version: MySQL 8.0
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Fixed for the next release.
