### ISSUE TITLE
Validate time field by minute increment

### ISSUE THREAD

**Issue by missmatsuko** [craftcms/cms#7364]
### Description
I was a bit confused when I could save any time in a time field, even though I had selected 30 minute increments. I guess the increments actually just determines what options show up in the dropdown, but I had expected it to be a validation constraint as well.

The decimal points option on number fields seems like it should behave the same way, but that one actually alters the saved value. No front-end validation, though. It's kind of unclear how these options affect validation and saved data.

**Comment by brandonkelly** [comment]
Just added instruction text to Minute Increment settings, which should clear it up:

<img width="803" alt="A “Minute Increment” setting" src="https://user-images.githubusercontent.com/47792/104254771-5f5a9c00-542c-11eb-85de-2f3a1d7ee750.png">

The setting is only intended to affect the timepicker UI, with no effect on the range of accepted values or validation.

> The decimal points option on number fields seems like it should behave the same way, but that one actually alters the saved value. No front-end validation, though. It's kind of unclear how these options affect validation and saved data.

Well `.0` is implied if you don’t enter a decimal, so no need to force decimals.

**Comment by missmatsuko** [comment]
> > The decimal points option on number fields seems like it should behave the same way, but that one actually alters the saved value. No front-end validation, though. It's kind of unclear how these options affect validation and saved data.
>
> Well .0 is implied if you don’t enter a decimal, so no need to force decimals.

Mm not sure if I get that? For example, if I set a numbers field to have 2 decimal places, I can then type into that number field `3.14159`. There is no front-end error when I save this value, but the value is automatically changes to `3.14`.

**Comment by brandonkelly** [comment]
Sorry, misunderstood. Do you think there should be a validation error in that case?

**Comment by missmatsuko** [comment]
Mm it's just the minute interval for time and number of decimals for numbers seem like similar concepts to me, yet they do different things?

**Comment by brandonkelly** [comment]
The minute increment is just a UI setting that doesn’t effect the possible values; the decimal setting determines how precise of a number can be stored. So not really, no.
