### ISSUE TITLE
Allow reordering user groups

### ISSUE THREAD

**Issue by benface** [craftcms/cms#7370]
### Description

It would be nice if there were some <img src="https://user-images.githubusercontent.com/1059139/103967168-6bdeac00-512f-11eb-9d50-3a2136bbf77a.png" width="14" height="14">s on this page:

![CleanShot 2021-01-07 at 21 26 35@2x](https://user-images.githubusercontent.com/1059139/103967028-15716d80-512f-11eb-821e-79613939e006.png)

**Comment by brandonkelly** [comment]
This was previously requested by #5033.
