### ISSUE TITLE
Make craft search better by removing stopwords from search query

### ISSUE THREAD

**Issue by texasbaptists** [craftcms/cms#7373]
### Description

I had a complaint about a page with the word "your" in the title not showing up in search results. Upon investigation I realized that if you omit the word "your" in the search query the result came back as expected. Then I learned about stopwords in MySQL via: https://craftcms.stackexchange.com/questions/35822/search-not-searching-certain-words-how-to-fix

I plan to look into Brad's suggestions, but I'm wondering if Craft by default could remove stopwords in queries so search would be more accurate.

**Comment by croxton** [comment]
MySQL has a default list of stopwords for full-text indexed tables. The MySIAM storage engine has a rather long list of them - including 'your' for example - whereas the list of stopwords for InnoDB is much shorter.

If you are running a relatively recent version of Craft (released after this workaround for a MySQL bug back in January 2020 https://github.com/craftcms/cms/commit/b39240a4b409b535cae7ea1acdf5880c0ef8cb2f) I would suggest changing the storage engine for your `searchindex` table to InnoDB. 

```sql
ALTER TABLE searchindex ENGINE = InnoDB;
```

Alternatively, you could reference a custom stopwords file in your `my.cnf` (containing a single stopword per line, or none at all if you don't want to exclude any words from the index).

https://dev.mysql.com/doc/refman/8.0/en/fulltext-stopwords.html#fulltext-stopwords-stopwords-for-myisam-search-indexes

**Comment by brandonkelly** [comment]
Yep what @croxton said.
