### ISSUE TITLE
groupBy not working with Postgres

### ISSUE THREAD

**Issue by pnpaes** [craftcms/cms#7383]
### Description
When i use groupBy in any query i got this type of error:

PDOException: SQLSTATE[42803]: Grouping error: 7 ERROR:  column "elements.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT "elements"."id", "elements"."fieldLayoutId", "element...
               ^ in /var/www/html/vendor/yiisoft/yii2/db/Command.php:1293

### Steps to reproduce

1. In twig I tried `{% set groupTest = craft.entries().groupBy('title').all() %}`
2. I also tried with craft commerce variant query `{% set groupTest = craft.variants().groupBy('productId').all() %}`

### Additional info

- Craft version: Craft Pro 3.5.17.1
- PHP version: 7.4.13
- Database driver & version: PostgreSQL 12.5
- Plugins & versions:
Asset Rev -> 6.0.2
Back In Stock -> 1.4.0
Barcode -> 1.0.3
Bundles -> 1.2
Craft Commerce -> 3.2.13.2
DigitalOcean Spaces Volume -> 1.1.3
Element API -> 2.6.0
Klarna Checkout for Craft Commerce -> 1.1.14
Nets Checkout for Craft Commerce -> 1.0.0
PayPal Checkout for Craft Commerce -> 1.2.0
PayPal for Craft Commerce -> 2.1.0.1
QRCode -> 1.0.5
Redactor -> 2.8.5
Stripe for Craft Commerce -> 2.3.2.1
Super Table -> 2.6.5
Vipps -> 1.0.6
Web Payments -> 1.0.7

**Comment by angrybrad** [comment]
That's not going to work in MySQL, either. The `groupBy` Twig method is a pass-thru for a SQL `GROUP BY` statement (https://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html) so the same limitations that apply there will apply here.

You'll need another piece of data to pivot on.  What exactly are you trying to achieve?

**Comment by pnpaes** [comment]
Hi Brad and thanks for the reply.

The goal is to pull all variants in craft commerce but group them by productId and 2 other custom fields (they are categories fields). In my case is a product grade (gradesCategories) and capacity (capacityCategories).

There is a third parameter in my products that is color. That way I can get the range of colors for each product/grade/capacity combination and display that in the variant card instead of listing each color on its own card. 

If there is a way to achieve that with graphql or a custom module using the queries server side, those are also options that I can explore.

Please let me know if you can point me in the right direction .

**Comment by brandonkelly** [comment]
Hey @pnpaes, this sounds like a case for the [group](https://craftcms.com/docs/3.x/dev/filters.html#group) filter?

For example this will group variants by unique product ID + category field combos:

```twig
{% set groupedVariants = craft.variants()
  .typeId(1)
  .with(['catFieldA', 'catFieldB'])
  .all()|group(v => v.productId ~ '-' ~ (v.catFieldA[0].id ?? '') ~ '-' ~ (v.catFieldB[0].id ?? '')) %}

{% for group in groupedVariants %}
  {% for variant in group %}
    ...
  {% endfor %}
{% endfor %}
```

Or if you want to start by grouping by product ID, then sub-group by category fields, you could do that instead:

```twig
{% set variants = craft.variants()
  .typeId(1)
  .with(['catFieldA', 'catFieldB'])
  .all() %}

{# group by product ID #}
{% for productId, variantsByProduct in variants|group(v => v.productId) %}
  {# now group by category fields #}
  {% for group2 in variantsByProduct|group(v => (v.catFieldA[0].id ?? '') ~ '-' ~ (v.catFieldB[0].id ?? ''))  %}
    {% for variant in group2 %}
      ...
    {% endfor %}
  {% endfor %}
{% endfor %}
```

**Comment by pnpaes** [comment]
Thanks Brad and Brandon.

Using the sample above I manage to achieve what I needed over here. I really appreciate the quick feedback.
