### ISSUE TITLE
Project Config Sync Lock not working

### ISSUE THREAD

**Issue by TheFox** [craftcms/cms#7384]
### Description

MySQL Lock is not working. When I run `./craft project-config/apply` it always says `error: Could not acquire a lock for the syncing project config.`. Even if there is no lock. If I run `SELECT IS_USED_LOCK('project-config-sync');` on MySQL 5.5.5 MariaDB 10.1.37 I get `NULL`, which means there is no lock.

### Steps to reproduce

1. Run `./craft project-config/apply`

### Additional info

- Craft version: 3.5.17.1
- PHP version: 7.2.34
- Database driver & version: MySQL 5.5.5 MariaDB 10.1.37

**Comment by andris-sevcenko** [comment]
The error message refers to a Mutex lock (https://www.yiiframework.com/doc/api/2.0/yii-mutex-mutex) that prevents two people/processes from applying project config changes at the same time, possibly breaking things, which explains why MySQL has no idea about it.

Are you hitting this every time you're trying to apply project config? Also, what is your deploy process?

**Comment by TheFox** [comment]
Thank you. This was helpful.

Can you change the original string? The problem is we have multiple CraftCMS installations on the same MariaDB server and the Lock is valid for the whole server, not attached to a specific database.

The `./craft project-config/apply` command takes very long since 3.5.16 (or maybe also before). We have about 64000 rows in `structureelements` table. Using `show processlist;` and console.log file I see that the most time takes to execute update SQL statements for `structureelements` table.

**Comment by brandonkelly** [comment]
> Can you change the original string? The problem is we have multiple CraftCMS installations on the same MariaDB server and the Lock is valid for the whole server, not attached to a specific database.

Ah, yeah that could be a problem. Just resolved that for Craft 3.6 by auto-prefixing lock names with the application ID.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "3.6.x-dev as 3.6.0-RC3",
  "...": "..."
}
```

Then run `composer update`.


Then make sure you’ve got a unique application ID for each of your Craft installs. Check your `.env` file (or wherever environment variables are defined) and make sure you are defining a unique `APP_ID` environment variable. If not, run the following command to add one to `.env`:

```bash
php craft setup/app-id
```

Finally, open up `config/app.php` and make sure you have this code:

```php
return [
    'id' => \craft\helpers\App::env('APP_ID') ?: 'CraftCMS',
    // ...
];
```

> Edit: also when a MariaDB connection gets stuck (or killed and it's in "clean up" phase) the lock is still there and take for ever.

I don’t think there’s anything we can do about that, unfortunately. Same could even happen with local file-based locks.

**Comment by brandonkelly** [comment]
Craft 3.6 has now been officially released ✨

**Comment by TheFox** [comment]
And 3.6.0.1 and 3.6.1. 

Thank you.
