### ISSUE TITLE
3.6 RC: Adjust info icon `nowrap` element

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#7385]
In Craft 3.6 RC3, any `<span class="info"></span>` element that is created outside of a field is automatically wrapped, along with the last word in the text preceding it, with a `<div class="nowrap"></div>` element. The logic for doing this makes sense to me, but shouldn't the `div` be an inline element such as a `span` so that it doesn't result in a line break?

![Screenshot 2021-01-13 at 17 32 13](https://user-images.githubusercontent.com/57572400/104481213-cc556980-55c5-11eb-8eaa-2695eaff44db.png)

The source code responsible for this:

https://github.com/craftcms/cms/blob/63c7144a337f8f201ff3c7a8db487b773d971ce1/src/web/assets/cp/src/js/InfoIcon.js#L31-L47

**Comment by brandonkelly** [comment]
Whoops, thanks for reporting! Fixed for the next release.

**Comment by bencroker** [comment]
Thanks!
