### ISSUE TITLE
Improve and enhance Customize Sources Modal per user and/or into project config

### ISSUE THREAD

**Issue by terryupton** [craftcms/cms#7388]
### Description

So I want to see if it would be possible to enhance the Customize Sources Modal.
![image](https://user-images.githubusercontent.com/5698596/104595858-16445b00-566b-11eb-9d8e-b6f07f8904b5.png)

1. Firstly, is there a reason why this is not part of the project config? 
Could this be something that could be offloaded, as it wills ave setting this up on multiple enviorments.

2. Can this be set on an individual user by user basis and if it can be per user?
If not then should this be a feature to allow individuals. to have different settings and for non full admin users control this for their own screens.

**Comment by brandonkelly** [comment]
Both of those topics have been addressed by #3658 – see that issue for our latest thinking on it.
