### ISSUE TITLE
Session not replaced when logging in as a different user

### ISSUE THREAD

**Issue by mattsbanner** [craftcms/cms#7390]
### Description
The current login method will [ignore](https://github.com/craftcms/cms/blob/develop/src/controllers/UsersController.php#L138-L141) further logins if a session is already underway. If I was to open two login pages for a site and login to one of them successfully, my session does not get replaced if I login on the other form as a different user.

Whilst this isn't a huge problem for ordinary functionality (you wouldn't show a login page to somebody that is already logged in) it's certainly possible for an end user to open a page twice and try to use different accounts.

We're experiencing an issue within a module that automatically logs in to 'guest' user account (minimum privileges) depending on the end users IP address. In this case, when a user logs out of the 'guest' account to try and access their own more privileged account, tabs can still be open making requests to the server, re-authenticating them as the 'guest'. Once they submit their actual login details, their session does not get replaced.

Could the above linked logic be changed to replace sessions when the user ID differs?

Thanks 😄

**Comment by brandonkelly** [comment]
I’m not sure about that… the current behavior seems expected to me.

You could create a new login controller action that ensures there’s not an active session first, though.

```php
public function actionLogin()
{
    // Make sure no one is logged in
    Craft::$app->user->setIdentity(null);

    // Now call the users/login action
    return Craft::$app->runAction('users/login');
}
```
