### ISSUE TITLE
Sorting element queries by title, with non-english characters

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#7392]
When sorting elements by titles, for example:

```
{{craft.entries.orderBy('title asc').all()}}
```
Titles with non-english characters are put at the end of the list.

For Example:

a
b
c
d
e
z
ą
ć
ę

Three last charasters are non-english, but should be not at end, for example "ą" should be right after "a" or "ć" right after "c".

**Comment by brandonkelly** [comment]
This is determined by your database’s selected collation; not something Craft has control over.

**Comment by wsydney76** [comment]
Maybe it helps to override the db collation in your query (MySQL):

`.orderBy('(title COLLATE utf8_german2_ci)')`

Sometimes you want to apply different sorting rules on a single db field (like content.title) for different languages/contexts.

See https://dev.mysql.com/doc/refman/5.6/en/charset-collate.html

**Comment by brandonkelly** [comment]
Oh nice, I didn’t know you could do that.
