### ISSUE TITLE
Custom date and time formats are overridden by date and time pickers

### ISSUE THREAD

**Issue by dralshehri** [craftcms/cms#7394]
### Description
Using custom date and time formats via the formatter component (set in `config/app.php`) does not have the expected  effect on date and time pickers.

In fact, the date and time pickers always use the locale's format. See this behavior for example:

![screenshot -20210116-161135](https://user-images.githubusercontent.com/542855/104815490-f0af8100-5825-11eb-9ac9-7b1cc6ea1e9c.gif)

Just after refreshing the page, you'll see the time format changes back to user's locale instead of the custom format. Also, for the date, when you select any date, the format changes back to user's locale.

### Steps to reproduce

1. Modify the `config/app.php` to be like:

```php
return [
    'components' => [
        'formatter' => function() {
            $formatter = Craft::$app->getLocale()->getFormatter();
            $formatter->dateTimeFormats = [
                'short' => [
                    'date' => 'd/M/y',
                    'time' => 'HH:mm',
                    'datetime' => 'd/M/y HH:mm',
                ],
            ];
            return $formatter;
        },
    ],
];
```

2. Set the user's locale to English (en-US)
2. Start creating any entry.
3. Observe the behavior mentioned above.

### Additional info

- Craft version: 3.6.0-RC3
- PHP version: 7.4.13

**Comment by brandonkelly** [comment]
This is happening because the JS gets the date format from the _locale_, not the formatter:

https://github.com/craftcms/cms/blob/59d3fbab3517f940510af92349e9f9d156509b29/src/web/assets/cp/CpAsset.php#L388

I’ve just made a couple changes for the next 3.6 release which make it possible to modify the date/time formats right at the source, which will end up getting passed to the formatter as well.

To get the change early, change your `craftcms/cms` requirement in composer.json to `3.6.x-dev as 3.6.0-RC3` (if it’s not already) and then run `composer update`.

Then from `config/app.php`, remove your `formatter` config and replace it with:

```php
return [
    'components' => [
        'formattingLocale' => function() {
            $locale = \craft\helpers\App::createFormattingLocale();
            $locale->setDateTimeFormats([
                'short' => [
                    'date' => 'd/M/y',
                    'time' => 'HH:mm',
                    'datetime' => 'd/M/y HH:mm',
                ],
            ]);
            return $locale;
        }
    ],
];
```

**Comment by dralshehri** [comment]
While testing the new changes, I tried to override the locale before rendering a template, but `\craft\helpers\App::createFormattingLocale` will always return the user's locale/language or the defaultCpLocale config setting.

For example, running the following code in a controller by a user with `en` as preferred language and locale:

```php
// override the locale
Craft::$app->set('locale', Craft::$app->getI18n()->getLocaleById('ar'));

// test date formatting
$date1 = Craft::$app->getFormatter()->asDate(new DateTime(), Locale::LENGTH_FULL);
$date2 = $this->view->renderString("{{ now|date('full')}}");

return $this->asJson([
    'date1' => $date1,
    'date2' => $date2,
]);
```

will result in:

```json
{
"date1": "Friday, January 22, 2021",
"date2": "Friday, January 22, 2021"
}
```

while it should be like:

```json
{
"date1": "الجمعة، ٢٢ يناير ٢٠٢١",
"date2": "الجمعة، ٢٢ يناير ٢٠٢١"
}
```

but it worked when I tried to add the following line to the top of `\craft\helpers\App::createFormattingLocale` function:

```php
return Craft::$app->getI18n()->getLocaleById('ar');
```

Is this the intended behavior? and is it possible to override the locale?

It worths mentioning also that when I have custom formatting like in your example, and used `"{{ now|date('full', locale='en')}}"`, the result date will be formatted by the original `en` locale formatting and not the custom one I added to `config/app.php`

**Comment by brandonkelly** [comment]
So in Craft 3.6, there are two locale app components:

- `locale` – Represent the selected language’s locale.
- `formattingLocale` – Represents the formatting locale, and is responsible for configuring the `formatter` component.

So when you override the locale, you should be overriding `formattingLocale` instead of `locale`.

You will also need to ensure that the `formatter` component isn’t set; otherwise it will already be configured based on the previous formatting locale.

```php
Craft::$app->set('formattingLocale', Craft::$app->getI18n()->getLocaleById('ar'));
Craft::$app->set('formatter', null);
```

**Comment by dralshehri** [comment]
Running `Craft::$app->set('formatter', null);` raised the following exception:
```
yii\base\InvalidConfigException: Unknown component ID: formatter
```

**Comment by brandonkelly** [comment]
Ah, sorry, looks like that would happen the next time the `formatter` component is accessed.

Do this instead:

```php
Craft::$app->set('formattingLocale', Craft::$app->getI18n()->getLocaleById('ar'));
Craft::$app->set('formatter', Craft::$app->formattingLocale->getFormatter());
```

**Comment by dralshehri** [comment]
After trying that, dates are translated but formatted using the locale's default formatting not the custom one I set in `config/app.php` under `formattingLocale` component which is like:

```php
return [
    'components' => [
        'formattingLocale' => function() {
            $locale = \craft\helpers\App::createFormattingLocale();
            if ($locale->id === 'ar') {
                $locale->setDateTimeFormats([
                    'short' => [
                        'date' => 'dd‏/MM‏/y',
                        'time' => 'hh:mm a',
                        'datetime' => 'dd‏/MM‏/y hh:mm a',
                    ],
                ]);
            }
            return $locale;
        }
    ],
];
```

**Comment by brandonkelly** [comment]
Yeah, ok so if you want to apply the same change in this case, do this:

```php
$locale = Craft::$app->getI18n()->getLocaleById('ar');
$locale->setDateTimeFormats([
    'short' => [
        'date' => 'dd‏/MM‏/y',
        'time' => 'hh:mm a',
        'datetime' => 'dd‏/MM‏/y hh:mm a',
    ],
]);
Craft::$app->set('formattingLocale', $locale);
Craft::$app->set('formatter', $locale->getFormatter());
```

**Comment by dralshehri** [comment]
I thought I could access my custom `formattingLocale` and use it for the override instead of rewriting it again.

Thanks for the solution and this helpful conversation! Very appreciated.

**Comment by brandonkelly** [comment]
Craft 3.6 has now been officially released ✨
