### ISSUE TITLE
Ability to set ssl/tls for smtp in mail settings with environment variable

### ISSUE THREAD

**Issue by EpocSquadron** [craftcms/cms#7398]
### Description

We can currently set the smtp credentials, server and port all with environment variables. However, it appears the dropdown to select ssl vs tls for the connection is not able to be set to an environment variable. We are currently using mailtrap.io for testing environments and a proper transactional email service in production (although not one of the common ones). Mailtrap requires the connection be over tls (mail settings test fails when set to ssl), while production requires ssl. This wouldn't be quite such a problem except that we are enforcing project config (and have admin changes off in all non-local environments), and this setting is tracked in that.  

I'm hesitant to override the transport in config/app.php as in #5975 as it seems kind of invasive, especially seeing as all of the other fields in the smtp settings are configurable with environment variables. Is it possible to add support for configuring this in a way that project config is compatible with?

**Comment by nordentwickler** [comment]
Completely agree with this. We are using laradock with maildev for our dev environment and the most small websites still user smtp with tls for sending emails. Maildev breaks with tls setting on - controlling this via environment variables would be great.

**Comment by Mosnar** [comment]
Related: #6403

**Comment by ryanirelan** [comment]
This takes on new meaning with Nitro's support for MailHog. MailHog doesn't support authentication nor encryption but those cannot be set via environment variables. 

[See docs:](https://craftcms.com/docs/nitro/2.x/services/mailhog.html)
> Transport Type: SMTP
> Host Name: mailhog.service.nitro
> Port: 1025
> Use Authentication: Unchecked (default)
> Encryption Method: None (default)
> Timeout: 10 (default)
