### ISSUE TITLE
Error After updating to Craft v3.5.18

### ISSUE THREAD

**Issue by wesleygooch** [craftcms/cms#7400]
### Description
The update worked locally but is crashing the server with "An internal server error occurred." on deployment. Looks like the composer didn't finish updating perhaps? 

### Steps to reproduce

1. Running PHP craft from the command line I get the following: 
php craft
PHP Notice 'yii\base\ErrorException' with message 'Undefined offset: 0'

in /srv/app/rmb-staging/htdocs/vendor/craftcms/cms/src/helpers/ProjectConfig.php:327

```
Stack trace:
#0 /srv/app/rmb-staging/htdocs/vendor/craftcms/cms/src/helpers/ProjectConfig.php(327): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '/srv/app/rmb-st...', 327, Array)
#1 /srv/app/rmb-staging/htdocs/vendor/craftcms/cms/src/helpers/ProjectConfig.php(306): craft\helpers\ProjectConfig::unpackAssociativeArray(Array)
#2 /srv/app/rmb-staging/htdocs/vendor/craftcms/cms/src/services/Plugins.php(1383): craft\helpers\ProjectConfig::unpackAssociativeArrays(Array)
#3 /srv/app/rmb-staging/htdocs/vendor/craftcms/cms/src/services/Plugins.php(206): craft\services\Plugins->_getPluginConfigData('formie')
#4 /srv/app/rmb-staging/htdocs/vendor/craftcms/cms/src/base/ApplicationTrait.php(1418): craft\services\Plugins->loadPlugins()
#5 /srv/app/rmb-staging/htdocs/vendor/craftcms/cms/src/console/Application.php(48): craft\console\Application->_postInit()
#6 /srv/app/rmb-staging/htdocs/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
#7 /srv/app/rmb-staging/htdocs/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#8 /srv/app/rmb-staging/htdocs/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#9 [internal function]: yii\console\Application->__construct(Array)
#10 /srv/app/rmb-staging/htdocs/vendor/yiisoft/yii2/di/Container.php(406): ReflectionClass->newInstanceArgs(Array)
#11 /srv/app/rmb-staging/htdocs/vendor/yiisoft/yii2/di/Container.php(165): yii\di\Container->build('craft\\console\\A...', Array, Array)
#12 /srv/app/rmb-staging/htdocs/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\console\\A...', Array, Array)
#13 /srv/app/rmb-staging/htdocs/vendor/craftcms/cms/bootstrap/bootstrap.php(246): yii\BaseYii::createObject(Array)
#14 /srv/app/rmb-staging/htdocs/vendor/craftcms/cms/bootstrap/console.php(51): require('/srv/app/rmb-st...')
#15 /srv/app/rmb-staging/htdocs/craft(21): require('/srv/app/rmb-st...')
#16 {main}
```

### Additional info

- Craft version: 3.5.18
- PHP version: 7.4.4
- Database driver & version: MySQL 5.7
- Plugins & versions: 
- "barrelstrength/sprout-active": "2.2.0",
    "barrelstrength/sprout-encode-email": "2.0.7",
    "barrelstrength/sprout-fields": "3.8.4",
    "craftcms/cms": "3.5.18",
    "craftcms/redactor": "2.8.5",
    "fortrabbit/craft-copy": "1.0.3",
    "fruitstudios/linkit": "1.1.12.1",
    "hashtagerrors/user-initials-photo": "1.1.1",
    "mmikkel/cp-field-inspect": "1.2.3",
    "monachilada/craft-matrixtoolbar": "1.0.6",
    "nystudio107/craft-cookies": "1.1.12",
    "nystudio107/craft-imageoptimize": "1.6.21",
    "nystudio107/craft-retour": "3.1.45",
    "nystudio107/craft-seomatic": "3.3.29",
    "nystudio107/craft-twigpack": "1.2.9",
    "nystudio107/craft-typogrify": "1.1.18",
    "supercool/tablemaker": "2.0.1",
    "vaersaagod/geomate": "v1.2.1",
    "verbb/default-dashboard": "1.0.8",
    "verbb/expanded-singles": "1.1.3",
    "verbb/field-manager": "2.2.2",
    "verbb/formie": "1.3.10",
    "verbb/icon-picker": "1.1.10",
    "verbb/knock-knock": "1.2.14",
    "verbb/navigation": "1.4.12",
    "verbb/smith": "1.1.12",
    "verbb/super-table": "2.6.5",
    "vlucas/phpdotenv": "^3.4.0"

**Comment by brandonkelly** [comment]
Try running the following command:

```bash
> php craft utils/repair/project-config
```

**Comment by wesleygooch** [comment]
I get the same error.

**Comment by brandonkelly** [comment]
Can you send a database backup and your Composer files into support@craftcms.com? We can help look into it from there.

**Comment by wesleygooch** [comment]
I was able to restore my database from a backup. Then I deleted the vendor's directory and the composer.lock file and ran composer update to start with a clean slate. That seemed to do the trick after a redeploy. Perhaps the error was caused by a deployment that was interrupted? Hard to say. I did however send you those files in case you wanted to investigate further. In any case, thanks for your time and prompt reply.

**Comment by brandonkelly** [comment]
Ah ok, glad you got it sorted! It does sound like `composer install` just didn’t finish or something, if nuking the `vendor/` folder and re-running `composer install` fixed it. There haven’t been any new database migrations recently so I’m guessing that restoring the database backup wasn’t actually necessary.
