### ISSUE TITLE
Craft 3.6-RC4: Entry counters in entry list paginator are incorrectly formatted

### ISSUE THREAD

**Issue by FreekVR** [craftcms/cms#7402]
### Description
After updating to Craft 3.6-RC4, the counters at the bottom of the entry listing are off. Seems like a number formatting mishap.

A few examples:
`1.00-2.002.00 of 2.002.00 entries` (22 items total) -- should be 1-22 of 22 entries
`1.00-1.001.00 of 1.001.00 entries` (11 items total) -- should be 1-11 of 11 entries

### Steps to reproduce

1.
2.

### Additional info

- Craft version: 3.6-RC4
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Go to your user preferences (`/admin/myaccount#prefs`). What are your Language and Formatting Locale preferences set to?

**Comment by FreekVR** [comment]
![image](https://user-images.githubusercontent.com/417416/105179933-39b74c00-5b2a-11eb-9cc1-cc8aec1b3c32.png)

**Comment by brandonkelly** [comment]
Was able to reproduce and got this fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"3.6.x-dev as 3.6.0-RC4"`and run `composer update`.
