### ISSUE TITLE
User(admin) not permitted to edit global set

### ISSUE THREAD

**Issue by dominikkrulak** [craftcms/cms#7407]
### Description
I'm logged in as admin (with admin privileges).
I have 2 sites and several global sets.

When I'm in tab menu "Globals" in CP under primary site say siteA, I'm able to see it all as expected.

When I switch to siteB I get 
server code 403 - forbidden, user not permitted to edit global set.

Here's some snippet of the warning message. 
I'm also happy to provide the stacktrace file of this message.

1. in /Applications/MAMP/craft/server/nginx/www/site.dev/vendor/craftcms/cms/src/controllers/GlobalsController.php 
at line 198
```php
if (empty($editableGlobalSets) || !isset($editableGlobalSets[$globalSetHandle])) {
     throw new ForbiddenHttpException('User not permitted to edit global set');
}
 
if ($globalSet === null) {
    $globalSet = $editableGlobalSets[$globalSetHandle];
}
```
2. craft\controllers\GlobalsController::actionEditContent('agreeTo', 'siteB', null)
3.  in /Applications/MAMP/craft/server/nginx/www/site.dev/vendor/yiisoft/yii2/base/InlineAction.php at line 57 – call_user_func_array([craft\controllers\GlobalsController, 'actionEditContent'], ['agreeTo', 'siteB', null])
```php
public function runAction($id, $params = [])
    {
        try {
            return parent::runAction($id, $params);
        } catch (\Throwable $e) {
            if ($this->request->getAcceptsJson()) {
                Craft::$app->getErrorHandler()->logException($e);
                if (!YII_DEBUG && !$e instanceof UserException) {
                    $message = Craft::t('app', 'A server error occurred.');
                } else {
```

### Steps to reproduce

1. Upgraded from Craft CMS v2 to Craft CMS v3
2. Created siteB as per documentation
3. In "Global" menu in CP I switched to siteB logged in with admin privileges (global sets were already created in v2)

### Additional info

- Craft version: 3.5.18
- PHP version: 7.4.2
- Database driver & version: mysql & 5.7.26
- Plugins & versions:  
    - Contact Form & 2.2.7
    - Contact Form Honeypot & 1.0.2
    - Cookies & 1.1.12
    - Feed Me & 4.3.4
    - Guest Entries & 2.3.0
    - Minify & 1.2.10
    - Redactor & 2.8.5

**Comment by brandonkelly** [comment]
Do you have any jobs in the queue that are still in progress, or which you may have cancelled?

**Comment by dominikkrulak** [comment]
Yes you're right @brandonkelly. It didn't occurred  to me right away that at the beginning of the Craft CMS's install I had in my `config/general.php` file, the setting set to `'runQueueAutomatically' => false,` and then I cancelled all pending jobs in CP which caused propagation failure. I will remember that now and I'm more encouraged to learn/understand the thing before you file a bug issue.

Perhaps we (you) could change the label of the issue as this isn't a bug.

**Comment by brandonkelly** [comment]
Cool, glad to hear that’s all it was :)
