### ISSUE TITLE
Default asset locations that end in a trailing ‘/’ are considered invalid

### ISSUE THREAD

**Issue by rungta** [craftcms/cms#7411]
### Description

If a template for the _Default Asset Location_ on an asset field resolves in a path with a trailing slash (such as `logos/`) Craft seems to consider that an invalid subpath.

https://github.com/craftcms/cms/blob/1fb7489d63b01f17e57eb8f99230bd7a8ff5b742/src/fields/Assets.php#L797-L804

### Steps to reproduce

1. Create an Asset Volume.
2. Create an Asset field with the _Default Asset Location_ set to `{ folderPath }`
3. Add the field to the Volume's field layout
4. Upload an asset anywhere in the volume
5. Try uploading a file to the field on the asset from step 4

### Additional info

- Craft version: 3.5.18

**Comment by brandonkelly** [comment]
Any leading/trailing slashes will be trimmed before rendering the subpath template:

https://github.com/craftcms/cms/blob/b307136753bac5b6adcc2e92bf56173417259f2e/src/fields/Assets.php#L784

This is because, per the code shown in your post, a leading/trailing slash (or an empty segment somewhere within the rendered subpath) indicates that some part of the subpath template didn’t render correctly.

You should be able to work around it by doing this:

```twig
{ folderPath|trim('/') ?: ':ignore:' }
```

**Comment by rungta** [comment]
The suggested code snippet `{ folderPath|trim('/') ?: ':ignore:' }` is _exactly_ how my field is configured currently. But it took me quite a bit of debugging to figure out why `{ folderPath }` wasn’t working. I’d do a `{ dump(folderPath) }` and that would work but strangely `{ folderPath }` would not. (This is independent of the recent `:ignore:` fix/feature because my initial test case was a path like `logos/`).

While uncommon, isn’t it risky to assume that a dynamically generated subpath _won’t_ end up with a leading or trailing slash? Perhaps this expectation should be communicated while creating the field, or at the very least, in the error message shown?

**Comment by brandonkelly** [comment]
Yeah there is room for improvement. Probably worth a full knowledge base article explaining the pitfalls of dynamic subfolder paths, and linking to that from the settings.

**Comment by brandonkelly** [comment]
Just added a warning about this to the [Dynamic Subfolder Paths](https://craftcms.com/docs/3.x/assets-fields.html#dynamic-subfolder-paths) section of the Assets field docs.
