### ISSUE TITLE
How to empty the Temporary Uploads folder and why can individual users not delete files within up this folder?

### ISSUE THREAD

**Issue by terryupton** [craftcms/cms#7420]
I am perhaps over looking something, but I cannot see anyway for an back-end user (not admin) to be able to remove/clean up their Temporary Uploads folder. As a full admin, I see the option to remove the assets.
[![enter image description here][1]][1] 

However, when logged in as a user that has full rights for all assets but is not a 'admin' user there is no option to delete the temporary assets.

[![enter image description here][2]][2]

I have looked through the user permission settings and I cannot see anything relating to Temporary Uploads or any settings that can be enabled for this.

Is this an oversight/feature request or am I over looking something?

The other thing I think worth mentioning is that the list in the CMS is not reflecting what is actually in the Temporary Uploads folder on the server. So I don't think the asset indexing is quite working for Temporary Uploads but it is not a folder than can be re-index.

[![enter image description here][3]][3] 

I would also like to know if there is an config setting or command that can be run periodically that would clean up all users Temporary Upload folders?

Thanks.

  [1]: https://i.stack.imgur.com/hvsPn.png
  [2]: https://i.stack.imgur.com/W6DFf.png
  [3]: https://i.stack.imgur.com/Yzb8W.png

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just fixed this for the next release.

**Comment by terryupton** [comment]
Thanks for this @brandonkelly although I am still seeing issues.
Logging in as the staff user, I can now see the delete option but it is disabled.

<img width="1095" alt="Screenshot 2021-02-13 at 18 13 57" src="https://user-images.githubusercontent.com/5698596/107857630-598b1880-6e27-11eb-83a4-c2bf5ed02860.png">

**Comment by brandonkelly** [comment]
Doh, sorry about that. Fixed that for the next releasse.

**Comment by brandonkelly** [comment]
Craft 3.6.6 is out now with that bugfix.
