### ISSUE TITLE
Stylesheet 404 error

### ISSUE THREAD

**Issue by shanewmurphy** [craftcms/cms#7421]
### Description
Utterly frustrating this CMS is. Trying to do the basics with it like add a link to stylesheet (index.twig) and just get 404 error (Not Found) My css file IS in the Public web folder. Using the global **site variable** {{ siteUrl }}style.css just gives me the 404 error (not Found). 

### Steps to reproduce

1.  link rel="stylesheet" href="{{ siteUrl }}styles.css"
2. folder file structure: **web**/styles.css

### Additional info

- Craft version: 3
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Are you able to access the CSS file directly in your web browser? (http://example.test/styles.css or whatever?)

What does the URL end up getting set to in the rendered index HTML?

**Comment by shanewmurphy** [comment]
Hi,
Thanks for getting back to me! 
No, I'm not able to access the CSS file in the browser by http://mysite/web/style.css - HTTP 404 - Not Found 

If I write the CSS link path like : link rel="stylesheet" href="styles.css" - CSS styles get rendered
But link rel="stylesheet" href="{{ siteUrl }}styles.css" - Failed to load resource: the server responded with a status of 404 (Not Found)

I'm working in a local environment

**Comment by brandonkelly** [comment]
Go to the web page, then add `view-source:` before the URL (e.g. `view-source:http://mysite/...`) and then find the `<link>` tag. What is the full rendered HTML for it?

**Comment by shanewmurphy** [comment]
Sorry, no idea what you are talking about in your last message. 

What web page? index.twig 
Where to insert? **view-source:** no idea where I must add this. in <link> tag to the stylesheet

**Comment by brandonkelly** [comment]
Go to the web page where the stylesheet URL is broken (`http://mysite` or whatever it is). Then in your browser’s address bar, add `view-source:` to the beginning of the URL.

For example, I have a local Craft site with the host name `craft3.test`. To view the homepage’s HTML source, I can go to `view-source:craft3.test` in my browser.

This will show you exactly what HTML is being rendered by your Twig template.

From there, please locale the `<link>` tag with the broken `href` attribute, and tell me what the full tag’s HTML is .

![The source view for a local web page, with the "view-source" URL highlighted, as well as the "link" tag](https://user-images.githubusercontent.com/47792/105644314-dc810a80-5e49-11eb-8e8b-c16293ea05b7.png)

**Comment by shanewmurphy** [comment]
Thanks for taking the time to explain in the above message. 

Here is the result of **view-source**: 
![Screenshot 2021-01-25 at 14 26 45](https://user-images.githubusercontent.com/3694619/105718672-66e46f80-5f19-11eb-9755-4a457a3585c0.png)


**Note:** My main.css file is in the **web** folder and NOT in any sub-folder within the Web folder itself. 


If I click on the `<link rel="stylesheet" href="http://devanew/anew-dev-website/web/main.css">` opens new tab with this:

![Screenshot 2021-01-25 at 14 30 31](https://user-images.githubusercontent.com/3694619/105719156-e1ad8a80-5f19-11eb-96cf-36d95a7dc305.png)

**Comment by brandonkelly** [comment]
And are you sure that `main.css` is saved at the root of your `web/` folder (alongside `index.php`, etc.)?

**Comment by shanewmurphy** [comment]
Yes, I'm sure
![Screenshot 2021-01-26 at 10 03 35](https://user-images.githubusercontent.com/3694619/105830851-e88dd900-5fbd-11eb-8c61-5989fe0f5149.png)

Don't know if it something to do with Mamp Pro setup but unlikely as accessing the dashboard etc fine. Anyway close this bug because I need to move on I'm using HTML syntax to call my stylesheet instead of global **site variable** 

Thanks for taking the time to fix my issue.

**Comment by brandonkelly** [comment]
I’m confused… how does your hard-coded HTML differ from what you were getting with `{{ siteUrl }}` ?

**Comment by shanewmurphy** [comment]
Yeah, I don't know it's odd.

**Comment by michtio** [comment]
@shanewmurphy which local development environment are you using? For me your site-url doesn't make a lot of sense , neither does the one you enter your browser. You should never "surf" to `/web`

All craft hosted files are in `/web` including the index.php, and craft things are underneath that folder. Your whatever local setup, should point to the `/web` directory as main truth of source. 

When I see your `http://devanew/anew-dev-website/web/main.css` That looks off to me ... the `/web` part doesn't belong in the site_url.

Even if everything is hosted in the `/web` folder your site-url will **not** be `http://localdev.test/web` but just `http://localdev.test` you should never add the `/web` folder to the site url.

If your site doesn't get served without adding web, then there is an issue with your local environment, and not with Craft CMS. Since whatever your front-end is, Craft isn't opinionated on what to use or where you host those front-end files.
