### ISSUE TITLE
3.6 - Suppress `deprecator` config during migrations

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#7446]
### Description

I have this in my `config/app.php` file...

```php
'components' => [
    // Throw hard errors on deprecation warnings
    'deprecator' => ['throwExceptions' => YII_DEBUG]
]
```

When I tried to update to Craft 3.6, it caused the migration to crash...

```
> @php craft migrate/all
Exception 'craft\errors\DeprecationException' with message 'The `siteUrl` config setting has been deprecated. You can set your site’s Base URL setting on a per-environment basis using an alias or environment variable. See [Environmental Configuration](https://craftcms.com/docs/3.x/config/#environmental-configuration) for more info.'

in /project/vendor/yiisoft/yii2/base/BaseObject.php:109

Stack trace:
#0 /project/vendor/craftcms/cms/src/config/GeneralConfig.php(1775): craft\services\Deprecator->log('siteUrl', 'The `siteUrl` c...')
#1 /project/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\config\GeneralConfig->init()
```

**What I would expect:**

I would expect that the `components.deprecator` option would be suppressed during a migration.

Turning deprecation warnings into hard errors is a "nice to have"... but crashing out in the middle of a migration could be a disaster.

### Additional info

- Craft version: Updating from 3.5 to 3.6
- PHP version: 7.4

**Comment by brandonkelly** [comment]
It’s doing what you’ve told it to do. I’d rather not overcomplicate it.

**Comment by lindseydiloreto** [comment]
I guess that's fair. I'd argue that it does more harm than good in this particular scenario, but time will tell if other folks bump into it as well.

Thanks.

**Comment by brandonkelly** [comment]
Well, that’s why it’s not the default behavior, and also not even a config setting :)

**Comment by lindseydiloreto** [comment]
Yeah. I guess if it's not documented, I can't complain. 🙂 

Just FYI, in case it comes up again, this combination seems to kill **all** migrations, as long as there is still a `siteUrl` value in your `config/general.php` file. Removing `siteUrl` from the config file allows the migration to proceed normally.
