### ISSUE TITLE
Staging site error after upgrade to 3.6 "Calling unknown method: craft\web\Request::getSiteToken()"

### ISSUE THREAD

**Issue by JordanMed** [craftcms/cms#7453]
### Description
I updated my local host to 3.6 today after testing I updated my staging site to 3.6 only to find this error "Calling unknown method: craft\web\Request::getSiteToken()"

Just looking for some insights on what the problem could be.

![Screen Shot 2021-01-27 at 12 36 09 PM](https://user-images.githubusercontent.com/54858742/106022660-7809b980-609c-11eb-8ace-7fb7aee7bd5a.png)

### Steps to reproduce

1. 
2.

### Additional info

- Craft version: 3.6.1
- PHP version: 7.4.11
- Database driver & version: 
- Plugins & versions:

**Comment by brandonkelly** [comment]
@JordanMed All good?
