### ISSUE TITLE
Hide unnecessary border around switch fields with on/off labels 

### ISSUE THREAD

**Issue by terryupton** [craftcms/cms#7456]
### Description
There seems to be an unnecessary border appeared around switch fields with on/off labels.
<img width="306" alt="Screenshot 2021-01-28 at 12 59 10" src="https://user-images.githubusercontent.com/5698596/106141964-c5535d00-6168-11eb-9804-10191e3296d8.png">

I think it would look better if this wasn't present.

### Additional info

- Craft version: Craft Pro 3.5.18

**Comment by brandonkelly** [comment]
It’s intentional (#6666). They look a little awkward without it.
