### ISSUE TITLE
Select category wont update UI

### ISSUE THREAD

**Issue by clieee** [craftcms/cms#7457]
### Description
I have a category field with branch limit of 1. The bug seems to be when changing to another category so it wont update the UI to the new selected category (and not when saving as well). 

Also - Using a category field with a limit of 1 branch still makes the "Add a category" button clickable when I have selected 1 category already. Maybe it could be grayed out? 

### Steps to reproduce

1. Create a category field with in Settings => Fields and limit it to 1 branch
2. Add it as a field to an entry
3. Edit entry and pick one of the categories and hit "Select". Dont save the entry.
4. Click again on the "Add a category" button and select a different category value, hit "Select"

### Additional info

- Craft version: Craft Pro 3.6.1
- PHP version: 7.3.26
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
Thanks for reporting that! It’s been covered over at #2423 and we plan to fix it in Craft 4 :)
