### ISSUE TITLE
Typo in Danish translation for “Title”

### ISSUE THREAD

**Issue by piperhaywood** [craftcms/cms#7462]
(This is a minor thing, but would be great to fix if possible!)

### Description

It seems like the Danish translation of the word “Title” (for example, in the table of entries in the CMS) is spelled incorrectly, as “Tittel” instead of the correct “Titel”. I’m working with a Danish organization on their site and they pointed this out to me, so I wanted to flag it here.

### Steps to reproduce

1. Access any up-to-date Craft CMS installation you have available.
2. Switch your user language to Danish (dansk) and take a look at the Entries control panel area.

### Additional info

I’m running Craft Pro v3.5.17.1.

**Comment by piperhaywood** [comment]
Thank you! ❤️

**Comment by brandonkelly** [comment]
Thanks for letting us know! I’ve just made that change for the next release :)
