### ISSUE TITLE
Project config utility - Error when applying

### ISSUE THREAD

**Issue by TimvanDijkhuizen** [craftcms/cms#7465]
### Description
Sometimes I get an error screen when applying project config changes but looking at the error everything seems to be ok. I'm not sure what is causing this error but it seems to be more common when applying a large amount of changes. This time nothing much should have been changed as I was applying a rebuilt config from the same database.

```
Status: error

Response: {"status":"All done!","finished":true,"returnUrl":"utilities/project-config","data":"6886c6c8140a3656e374cfd66a20615eeb86201d63cb3857b3d792381c898eda{\"force\":false,\"installPlugins\":[],\"uninstallPlugins\":[],\"returnUrl\":\"utilities/project-config\",\"postPrecheckState\":{\"nextAction\":\"apply-yaml-changes\",\"status\":\"Applying changes from the project config YAML files…\"}}"}
```

### Steps to reproduce

1. Go to the project config utility.
2. Apply your pending config changes.
3. An error screen is shown but everything seems to be ok.

### Additional info

- Craft version: 3.5.18
- PHP version: 7.3.26
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
Activity Log	1.0.1
Child Me!	1.2.0
Contact Form	2.2.7
Cookies	1.1.12
CP Field Inspect	1.2.3
Element API	2.6.0
Expanded Singles	1.1.3
Field Manager	2.2.2
Hide Admin	1.1.0
No-Cache	2.0.7
reCAPTCHA	1.5.1
Redactor	2.8.5
Redactor Custom Styles	3.0.4
Relabel	2.0.2
SEO	3.6.7
Super Table	2.6.5
Table Maker	2.0.1
Typed link field	1.0.24
Video Embedder	1.1.4
Wordsmith	3.3.0.1

**Comment by brandonkelly** [comment]
Sounds a bit like a gateway timeout issue (either your load balancer or web server gets impatient with PHP), but you typically won’t get a JSON response when that happens, so I’m not really sure what to make of that.

The next time you are applying a large number of project config changes, can you please make a database backup first, and if the error occurs, can you write into support@craftcms.com with the database backup, your Composer files, and the new `config/project/` files?

**Comment by brandonkelly** [comment]
Will go ahead and close this for the time being.
