### ISSUE TITLE
Documented element query method draftOf('*') says "Invalid draftOf value"

### ISSUE THREAD

**Issue by benface** [craftcms/cms#7470]
### Steps to reproduce

Call `craft.entries.draftOf('*').all()` (documented [here](https://docs.craftcms.com/api/v3/craft-elements-db-elementquery.html#draftof)). Get the following error:

```
Exception 'yii\base\InvalidArgumentException' with message 'Invalid draftOf value'
```

### Additional info

- Craft version: 3.5.16
- PHP version: 7.4.14
- Database driver & version: MySQL 5.7.32

**Comment by brandonkelly** [comment]
Doh, thanks for reporting. Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.6.3 is out now with that fix ✨
