### ISSUE TITLE
Postgresql is slower than mariadb (graphql, ping)

### ISSUE THREAD

**Issue by approached** [craftcms/cms#7478]
### Description
I was wondering why is graphql so slow. Than i make simple test. I installed two instances and simple ping request. The result is completely different. Just see screenshot:

MariaDB 10.3:
![Screen Shot 2021-02-01 at 15 23 32](https://user-images.githubusercontent.com/3439330/106472363-e38bc680-64a2-11eb-9089-4713a1829976.png)

PostgreSQL 13.1:
![Screen Shot 2021-02-01 at 15 28 53](https://user-images.githubusercontent.com/3439330/106472381-e8507a80-64a2-11eb-8e96-0c453b1dab9f.png)

If i work with real data queries. Than it took 300 - 800 ms. 👎 

### Steps to reproduce

1. Install two instance of craftcms (1 MariaDb, 1 Postgresql)
2. Send a request:
```
query MyQuery {
  ping
}
```

### Additional info

- Craft version: 3.6.2
- PHP version: 7.4
- Database driver & version: MariaDB 10.3 / PostgreSQL 13.1
- Plugins & versions: -

**Comment by brandonkelly** [comment]
We haven’t seen any significant differences in our own testing.

Were you testing with the exact same content structures (sections, entry types, fields, etc.)? If not, that is likely the main culprit. Most of GraphQL’s slowness can usually be attributed to its work defining the schema, which unfortunately [isn’t cacheable yet](https://github.com/craftcms/cms/issues/7222).

**Comment by approached** [comment]
Both installs are complete fresh. I used the command from docs: https://craftcms.com/docs/3.x/installation.html#downloading-with-composer


```shell
composer create-project craftcms/craft craft_mysql
and
composer create-project craftcms/craft craft_postgres
```

Both databases are in docker container.

BTW: It is just a ping call. Not a query for entries.

**Comment by brandonkelly** [comment]
Hm, in that case perhaps this is a network routing issue. We can’t reproduce this.

**Comment by approached** [comment]
BTW: Everything was runnning on local machine.

**Comment by brandonkelly** [comment]
Yeah I thought that could be the case, but that doesn’t rule out networking issues.
