### ISSUE TITLE
Running index-assets/one on the CLI gives a DateTime error.

### ISSUE THREAD

**Issue by michtio** [craftcms/cms#7480]
### Description

running the following command:

`./craft index-assets/one videos --delete-missing-assets` results in the following error:

```
Indexing assets in Videos ...
    > #0: 07-Brief-introduction-to-communities-of-practice.pdf ... error: Too few arguments to function craft\helpers\DateTimeHelper::toDateTime(), 0 passed in /home/forge/researchschool.org.uk/releases/30524f031c5077de5b27a3c325a004a283df7466/vendor/craftcms/cms/src/validators/DateTimeValidator.php on line 81 and at least 1 expected
```

The error thrown is on an asset that's not even in the volume ( so hence adding the `--delete-missing-assets` ) flag.
Initially I was thinking it was related to: [#7459](https://github.com/craftcms/cms/issues/7459) and did the update to Craft 3.5.19.1 but without success the CLI keeps on giving the same error.
  
  

### Steps to reproduce

1. Run the above command with a non-existing asset in place.

### Additional info

- Craft version: 3.5.19.1
- PHP version: 7.4

**Comment by brandonkelly** [comment]
This is certainly the same bug as #7459. If updating didn’t work, then you are not actually running 3.5.19.1.

Here is line 81 of DateTimeValidator.php – the line referenced in your error message:

https://github.com/craftcms/cms/blob/2c6ef1afa23aefaefc95b19ed823769cc2a8f8c5/src/validators/DateTimeValidator.php#L81

Clearly an argument is in fact being passed to `toDateTime()` now.

**Comment by michtio** [comment]
Yup, now everything seems to be working fine, had to trash the vendor folder for whatever reason. I will close.

Thanks @brandonkelly
