### ISSUE TITLE
Deprecation error doesn't specify origin

### ISSUE THREAD

**Issue by bengreenbank** [craftcms/cms#7484]
### Description

Deprecation error for '_Looping through element queries directly has been deprecated. Use the all() function to fetch the query results before looping over them._' doesn't specify where the error origin is.

![Screenshot 2021-02-02 at 17 04 57](https://user-images.githubusercontent.com/61185468/106635806-291ac300-6579-11eb-96b6-ec80a8f71f5c.png)

### Steps to reproduce

1. Go to utilities
2. Go to deprecation warnings
3. Unsure of exaclty what part of code is causing this, as it doesn't specify an origin

### Additional info

- Craft version: 3.5.18
- PHP version: 7.4.13
- Database driver & version: MySQL 5.7.32
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
What shows up in the stack trace modal?

**Comment by nicbou** [comment]
I didn't create this issue, but nothing useful appears in the stack trace that would help someone pinpoint the source of the problem.

**Comment by brandonkelly** [comment]
@nicbou Can you post it here anyway?

**Comment by nicbou** [comment]
Hello Brandon. I fixed the generic issues 3 days ago, so I don't have any screenshot to offer. However, the UI pointed to the wrong location in the right file. The stack trace did not offer meaningful information, unless I wanted to read compiled templates.

Nonetheless, having already fixed a few of those ".all()" warnings, I knew where to find the rest.
