### ISSUE TITLE
CraftCMS version 3.6.1 and 3.6.2 unavailable through CDN.

### ISSUE THREAD

**Issue by Andrew-Delaney** [craftcms/cms#7487]
### Description
We're currently using version 3.6.0.1 of Craft and we'd like to upgrade to the latest version (3.6.2 at time of writing), we usually fetch the releases from your CDN at: https://download.craftcdn.com/craft/3.x/Craft-3.x.x.zip but currently version 3.6.1 and 3.6.2 seem to be unavailable there.

![image](https://user-images.githubusercontent.com/42071608/106739883-a0039a80-6611-11eb-86c3-d0b5547411ec.png)
![image](https://user-images.githubusercontent.com/42071608/106739915-a85bd580-6611-11eb-9647-5d7219b306d3.png)

### Steps to reproduce

1. Attempt to fetch 3.6.1 or 3.6.2 release zip file from CDN at either https://download.craftcdn.com/craft/3.6/Craft-3.6.1.zip or https://download.craftcdn.com/craft/3.6/Craft-3.6.2.zip
2. Request fails with a 404 error.

### Additional information

Possibly similar to previous issue: https://github.com/craftcms/cms/issues/3743

**Comment by brandonkelly** [comment]
Craft-3.6.3.zip is up now. Appears there was some sort of caching issue preventing 3.6.1 and 3.6.2 from getting uploaded.

I wouldn’t recommend you update this way, though. Once Craft is installed, it can self-update via the `craft update craft` command, or you could use `composer update` if you have Composer installed. (`php vendor/bin/composer update` should also work even without Composer installed.)

The zips are provided as a convenience for getting Craft installed _initially_ if you want to do it without Composer, that’s all.
