### ISSUE TITLE
UX - Publish draft and save draft annoying as hell :S

### ISSUE THREAD

**Issue by zzseba78** [craftcms/cms#7488]
### Description

I found that now craft saves a draft instead of save and publish the entry, this is very annoying, since red action button across all the admin interface is the action button, and now you see that when you click it, it goes back to section list, without the entry published and content hidden, until you go to show draft to find it, this is terrible for UX of clients, what is the purpose of it? Why not put the save draft button on grey, and save entry on red ( as always )?? Is there a way to change this?

**Comment by brandonkelly** [comment]
We have addressed this for the next release (coming out later today) – see #7401.

**Comment by zzseba78** [comment]
@brandonkelly thanks!

**Comment by brandonkelly** [comment]
Craft 3.6.3 is out now with that change ✨
