### ISSUE TITLE
Matrix field content is lost if entry is modified and saved again in after-save-hook

### ISSUE THREAD

**Issue by linusschwab** [craftcms/cms#7489]
### Description
In one of our modules, we are using a simple after-save-hook that sets the post date to the current date the first time the entry is published and saves the entry again to apply the date change. In the past, this worked fine, without any problems. After we made an update from Craft CMS 3.5.12.1 to 3.5.17.1 (without any changes in the after save hook code), the content of the matrix field of the entry gets deleted, as soon as the entry is saved again. 

We found a workaround that basically reads the content of the matrix field and sets it again before saving the entry, but I don't think that this should be necessary.

The after-save-hook is registered like this in the module and only handles events for the correct section and if the entry is no longer a draft:
```
private function registerArticleSaveEvents() {
	Event::on(Entry::class, Element::EVENT_AFTER_SAVE,
		function(ModelEvent $e) {
			/** @var $entry Entry */
			$entry = $e->sender;
			$section = $entry->section->handle;

			if ($section !== 'articles') {
				// Not an article, not interesting here
				return;
			}

			if (ElementHelper::isDraftOrRevision($entry)) {
				// Article is draft, do nothing yet
				return;
			}

			$service = ArticlesService::instance();
			$service->addDefaultTags($entry);
			$service->updateEntryDate($entry);
		}
	);
}
```

The following function in the service handles the date update. Without the workaround (`$this->updateMatrixFieldContent($entry, 'blocks');`, see method below), the matrix field content is lost after the `Craft::$app->getElements()->saveElement($entry);` call:
```
public function updateEntryDate(Entry $entry) {
	$dateCreated = $entry->dateCreated->getTimestamp();
	$dateCreated -= ($dateCreated % 60); // round down to minutes since postDate doesnt store seconds

	if ($entry->postDate && $entry->dateCreated && $entry->postDate->getTimestamp() < $dateCreated) {
		$entry->postDate = $entry->dateCreated;
		$this->updateMatrixFieldContent($entry, 'blocks');
		Craft::$app->getElements()->saveElement($entry);

		Craft::info("Updating postDate of article $entry->id because it was published and dateCreated > postDate, "
			."new postDate: ".$entry->postDate->format(\DateTime::ATOM), 'DEV_Articles');
	}
}

/**
* Workaround to make sure that matrix field content does not get deleted on element save
*/
private function updateMatrixFieldContent(Entry $entry, $fieldHandle) {
	$field = Craft::$app->getFields()->getFieldByHandle($fieldHandle);
	$matrix = $entry->getFieldValue($fieldHandle);
	$matrixSerialized = $field->serializeValue($matrix, $entry);
	$entry->setFieldValue($fieldHandle, $matrixSerialized);
}
```

Can you please take a look at this? Or are we doing something wrong? Let me know if you need any additional information.

### Steps to reproduce

1. Create an after-save-hook for an entry type with a matrix field. The code in the hook should modify another entry field after the entry is published and save the modified entry again
2. Create a new entry in this section with some blocks in the matrix field - the matrix field content should still be there after the draft is saved (and a page refresh)
3. Publish the draft - in most cases, the content of the matrix field will be lost

### Additional info

- Craft version: 3.6.2 (happened after the update from 3.5.12.1 to 3.5.17.1)
- PHP version: 7.4.12
- Database driver & version: MySQL 5.7.23
- Plugins & versions: Element API (2.6.0), Google Cloud Storage (1.4.0), Redactor (2.8.5), Tags (1.0.7)

**Comment by brandonkelly** [comment]
This looks identical to #7455. The solution there was to switch to `EVENT_AFTER_PROPAGATE` – see https://github.com/craftcms/cms/issues/7455#issuecomment-769491619.

**Comment by linusschwab** [comment]
@brandonkelly Thanks for the information, this helps to unterstand why it happens. However, I think the naming is a bit confusing: the hook is called "after save", so as a user I would expect that the element is fully saved then and ready to be modified. Why is the third hook necessary?

So basically during the "after save" hook, the entry should not be saved? Or would it be possible to just update a field of the entry object that is passed in the hook (for example the postDate) without saving it and Craft CMS handles the save then in the "next step"? Maybe it would be good to add this information to the documentation, so that other developers don't run into the same issue, especially as it might break existing code.

**Comment by brandonkelly** [comment]
Agree we should do a better job documenting it – making a note. Here’s a quick and dirty order of events that happen in `craft\services\Elements::saveElement()`, and the events the entry will trigger in the process:

0. Pre-flight checks (`EVENT_BEFORE_SAVE`)
1. Validate the entry (`EVENT_BEFORE_VALIDATE`, `EVENT_AFTER_VALIDATE`)
2. Save the entry for the initial site (`EVENT_AFTER_SAVE`)
3. Propagate non-translatable changes to the entry’s other sites (repeat all steps for each site, then `EVENT_AFTER_PROPAGATE`)

Matrix blocks don’t actually get saved until the very end, right before `EVENT_AFTER_PROPAGATE` is triggered, which go through their own `saveElement()` calls – including propagating block content to other sites, which would fail if they were saved before the entry had actually finished saving across all sites.
