### ISSUE TITLE
The restore command is deprecated

### ISSUE THREAD

**Issue by jbrew30** [craftcms/cms#7490]
I received a deprecation error when I run `restore/db`. I just copied and pasted what was available in the commands list. It just needs to be flipped flopped.

<img width="587" alt="Screen Shot 2021-02-03 at 9 48 17 AM" src="https://user-images.githubusercontent.com/22452733/106764762-18645e80-6606-11eb-9bd8-a7240b064fd6.png">
<img width="518" alt="Screen Shot 2021-02-03 at 9 48 40 AM" src="https://user-images.githubusercontent.com/22452733/106764763-18645e80-6606-11eb-958f-6d74a1636c75.png">

### Steps to reproduce

1. Run ./craft restore/db storage/backups/<copyofdatabase>

### Additional info

- Craft version: 3.6.1
- PHP version: 7.3.2
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

**Comment by brandonkelly** [comment]
Just improved the help output for that command (and a couple others) so it’s more clear at the outset that the newer `db/restore` command should be used instead.

<img width="665" alt="The new help command output for the old `restore` command" src="https://user-images.githubusercontent.com/47792/106791083-52832f80-6609-11eb-83dd-636bfd7b70c8.png">
