### ISSUE TITLE
Cannot publish new entries after updating to version 3.6.0.1

### ISSUE THREAD

**Issue by Andrew-Delaney** [craftcms/cms#7492]
### Description
Updating our website to Craft version 3.6.0.1 seems to have broken some of the functionality around publishing new entries to the system. The "Publish draft" button does nothing when clicked, additionally the "Save draft" dropdown menu does not display when the dropdown arrow is clicked and the "Enabled" slider does not change when clicked, however drafts can be enabled and disabled in the entries page by checking the box next to the post and using the "Set status" dropdown menu.

### Steps to reproduce

1. Update to Craft 3.6.0.1
2. Create a draft entry
3. Attempt to publish draft entry by clicking the "Publish draft" button in the "Create a new entry" screen
4. "Publish draft" button does not respond to clicks

### Additional info
Issue tested in Firefox, Edge and Chrome on Windows and Ubuntu.

The version we updated from was: 3.5.17.1

- Craft version: Craft Pro 3.6.0.1
- PHP version: 7.3.26
- Database driver & version: MySQL 5.5.5
- Plugins & versions: 
Amazon S3 	1.2.11
Asset Rev 	6.0.2
Entries Subset 	1.2.3
Redactor 	        2.8.5
Sprout Email 	4.3.0
Sprout Fields 	3.7.0
Sprout Forms 	3.10.0.1
Sprout SEO 	4.5.0

**Comment by brandonkelly** [comment]
Are you getting any JavaScript errors on the Edit Entry page?

**Comment by Andrew-Delaney** [comment]
I get the following error in the console when I open the entry editing page:

`Uncaught TypeError: this.$icon[0].previousSibling is null
    init InfoIcon.js:31
    constructor garnish.js:768
    constructor garnish.js:40
    constructor garnish.js:40
    infoicon Craft.js:1926
    jQuery 2
    infoicon Craft.js:1925
    initUiElements Craft.js:1493
    <anonymous> Craft.js:2087
    jQuery 13`
    
I don't get any errors in the console when clicking the buttons, but we also don't see any network calls happen when clicking the "Publish draft" button.

I've also now tried updating craft to 3.6.3 in my local development environment but that's not fixed the issue.

**Comment by brandonkelly** [comment]
Do you have any plugins that could be interfering with the page?

**Comment by brandonkelly** [comment]
I’m guessing that JS error is the culprit. Just fixed that for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.6.3"`and run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.6.4 is out now with that fix ✨
