### ISSUE TITLE
craft\web\ServiceUnavailableHttpException on initial load

### ISSUE THREAD

**Issue by kylerits** [craftcms/cms#7494]
### Description

I am having issues with the initial load of my craft site. I am not able to access to home page by directly link, however I login through /admin and link to the homepage via the 'View Site' button, the site loads just fine. The stack trace is shown below:

craft\web\ServiceUnavailableHttpException in <project-path>/craft/vendor/craftcms/cms/src/web/Controller.php:165
Stack trace:
#0 <project-path>/craft/vendor/craftcms/cms/src/controllers/TemplatesController.php(71): craft\web\Controller->beforeAction(Object(yii\base\InlineAction))
#1 <project-path>/craft/vendor/yiisoft/yii2/base/Controller.php(178): craft\controllers\TemplatesController->beforeAction(Object(yii\base\InlineAction))
#2 <project-path>/craft/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('render', Array)
#3 <project-path>/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#4 <project-path>/craft/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('templates/rende...', Array)
#5 <project-path>/craft/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#6 <project-path>/craft/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
#7 <project-path>/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#8 <project-path>/craft/web/index.php(22): yii\base\Application->run()
#9 /Users/kylerits/.composer/vendor/laravel/valet/server.php(214): require('/Users/kylerits...')
#10 {main}

### Steps to reproduce

1. Directly rout to site url
2. Enjoy error

### Additional info

- Craft version: 3.5.18
- PHP version: 7.4.13
- Database driver & version: mysql v8.0.22
- Plugins & versions:
    "craftcms/aws-s3": "1.2.11",
    "craftcms/redactor": "2.8.5",
    "dolphiq/redirect": "1.1.1",
    "doublesecretagency/craft-cpcss": "2.3.0",
    "misterbk/mix": "1.5.2",
    "mmikkel/cp-field-inspect": "1.2.4",
    "nystudio107/craft-cookies": "1.1.12",
    "nystudio107/craft-seomatic": "3.3.30",
    "rynpsc/craft-phone-number": "1.4.2",
    "sebastianlenz/linkfield": "1.0.24",
    "solspace/craft-freeform": "3.10.5",
    "spicyweb/craft-embedded-assets": "2.4.5",
    "spicyweb/craft-neo": "2.8.18",
    "topshelfcraft/wordsmith": "3.3.0.1",
    "verbb/super-table": "2.6.6",
    "vlucas/phpdotenv": "^3.4.0"

**Comment by kylerits** [comment]
Adding `'isSystemLive' => true` to `craft/config/general.php` seems to have resolved this issue.

**Comment by brandonkelly** [comment]
Had it been set to `false` ?
