### ISSUE TITLE
Space (margin) to left of number field in CP

### ISSUE THREAD

**Issue by shornuk** [craftcms/cms#7498]
### Description
Couldn't see this reported elsewhere. Added a number field, no prefix/suffix. In the CP, it's showing with a little space to the left. 

<img width="307" alt="Screenshot 2021-02-04 at 09 50 33" src="https://user-images.githubusercontent.com/2061819/106875569-b7ed2400-66ce-11eb-89bb-5b479dad7296.png">

Empty div, presumably for the prefix has a margin left on it...

```css
body.ltr .flex > *:not(:last-child) {
margin-right: 7px !important;
}
```

```html
<div class="flex">
            <div aria-hidden="true">
            
        </div>
        <div>
            <input type="text" id="fields-phoneNumber" class="text fullwidth" name="fields[phoneNumber][value]" inputmode="numeric" autocomplete="off" aria-describedby="phoneNumber-instructions phoneNumber-desc">
    </div>
            <div aria-hidden="true">
            
        </div>
    </div>
```

### Additional info

- Craft version: 3.6.3

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.6.4 is out now with that fix ✨
