### ISSUE TITLE
Save draft on new entry does nothing

### ISSUE THREAD

**Issue by nitech** [craftcms/cms#7499]
### Description
After upgrading to 3.6 new entries that gets saved with the "Save Entry" button, does not get created. I have to click "Publish draft" to get the entry saved and published.

### Steps to reproduce
1. New entry
2. Fill in contents
3. Click "Save draft"
4. Expecting entry to be saved 

See video: https://vimeo.com/508410044/231add6feb 

### Additional info

- Craft version: 3.6
- PHP version: 7.3.3
- Database driver & version: MySQL 5.7.25
- Plugins & versions: 

Plugin | Version
-- | --
Amazon S3 | 1.2.11
Blitz | 3.7.0
Bulk Edit | 2.0.5
Category Groups Field | 1.2.2
Child Me! | 1.2.0
CKEditor | 1.0.0-beta.3
Cloner | 1.2.2
Control Panel CSS | 2.3.0
CP Field Inspect | 1.2.4
Craft Commerce | 3.2.14.1
Cryptographer | 1.0.3
Embedded Assets | 2.4.5
Enupal Backup | 1.5.0
Feed Me | 4.3.4
Imager X | v3.3.0
Kint | 1.0.0
Mailchimp Subscribe | 3.0.3
Migration Assistant | 3.2.4
Navigation | 1.4.13
Neo | 2.8.17
NSM Fields | 1.0.2
Reasons | 2.2.2
Redactor | 2.8.5
Retour | 3.1.45
Scout | 2.3.1
Section Field | 1.1.0
SendGrid | 1.2.2
SEOmatic | 3.3.30
Super Table | 2.6.6
Tags | 1.0.7
Two-Factor Authentication | 2.7.3.1
Typed link field | 1.0.24
Units | 1.0.4
Webhooks | 2.3.2

**Comment by thupsi** [comment]
Hi! There has been some confusion regarding this new behavior, but I think it’s a step in the right direction. The entry is not lost. It is saved as a draft (you will notice in your video the label says ‘save draft’, not ‘save entry’ or ‘publish’). It’s under the all —> drafts menu item in the entry index. In 3.6.3 this is improved: Drafts are immediately visible and tagged in the index.

**Comment by nitech** [comment]
Ah... took me a while to find them ;-) You are right that the UX is not immediately obvious (and I had even skimmed the release notes. 

![image](https://user-images.githubusercontent.com/1279436/107004561-c438b600-678e-11eb-93da-26a47493e1a6.png)

**Comment by brandonkelly** [comment]
Yeah this was already brought up in #7401 and we’ve addressed it in Craft 3.6.3.
