### ISSUE TITLE
Instead of showing the entry ID as the name of a draft, denote that it's an untitled draft

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#7500]
### Description

Currently if you create a new entry and save it as a draft without a title, it will appear in the element index labeled by its ID. Showing the ID is fine; however, I think it's important to also denote that it's untitled. Just showing the ID is ambiguous since it assumes that a section doesn't have titles that are numeric already.

I think the most important piece of information a user wants is that an entry is untitled, followed by an ID.

This could be as simple as adding the word "untitled" to the draft tag:
![image](https://user-images.githubusercontent.com/3810939/106900699-d2ba9b00-66c4-11eb-80bb-1097bd28dc02.png)

Or perhaps just using the title format: "*Untitled* (45)"

Craft 3.6.3

**Comment by mmikkel** [comment]
Hard agree on this one! ...although I'd prefer something like this:

![image](https://user-images.githubusercontent.com/298510/106910093-2d71e800-6701-11eb-858c-d178abf840f6.png)

**Comment by brandonkelly** [comment]
Good idea. Just changed that for the next release.

<img width="295" alt="A clipping of an entry index showing an unpublished draft with no title labelled as “(Untitled)”" src="https://user-images.githubusercontent.com/47792/107048889-4b316280-677e-11eb-886c-4306527cb0bc.png">

**Comment by brandonkelly** [comment]
Craft 3.6.4 is out now with that change ✨

Ended up changing it to “Untitled entry” to make it just a bit more clear.
