### ISSUE TITLE
When previewing published entry the main action switches to “save draft”

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#7502]
### Description

When I make changes to a published entry I can keep “saving” and the entry is updated. When I activate “preview” and make further changes, those changes are made in a newly created draft. I can only notice this if I see that the labels of the buttons on the top have changed. It’s a bit confusing (seems inconsistent), and can easily catch an editor off-guard. 

If this behavior is intentional (I’m sure you have thought of more workflow scenarios than I have), then one possible improvement would be to at least have a more prominent visual indicator that the entry screen has switched to “draft mode”.

### Steps to reproduce

1. Create a new entry and publish it.
2. Navigate back to the entry editing screen and start editing. The main action remains “save”.
3. Hit “preview” and continue editing. A draft is created and the main action switches back to “save draft”.
4. Hit Ctrl+S.
5. Go to front end and wonder why the entry has not been updated.

### Additional info

- Craft version: 3.6.3
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by thupsi** [comment]
Just discovered https://github.com/craftcms/cms/issues/6681, so there seems to be a technical reason for auto-creating drafts for preview. I like Brad’s suggestion of an “ephemeral” draft only for this case!

**Comment by brandonkelly** [comment]
Yeah same issue discussed in #6681.
