### ISSUE TITLE
Consider adding a config setting to make 'Use shapes to represent statuses' enabled for all Users by default

### ISSUE THREAD

**Issue by cakleimeier** [craftcms/cms#7504]
### Description
The 'Use shapes to represent statuses' preference setting is great! It removes ambiguity and adds clarity for _all_ Users, not just those with difficulty differentiating among colors. Why not add an option to make the Control Panel less ambiguous and more accessible by default?

**Comment by ryanmasuga** [comment]
I agree. If Craft wants to be an accessibility leader, why isn't that just on by default? Shapes+color doesn't hurt anyone. If you wanted to allow people to go back to just circles, maybe add a global general config setting: `addAmbiguity == true` 😁

**Comment by brandonkelly** [comment]
Great idea @cakleimeier! There’s also that “Underline links” preference, and likely will be more in the future, so just added a new `accessibilityDefaults` config setting for the next release, which can set both:

```php
'accessibilityDefaults' => [
    'useShapes' => true,
    'underlineLinks' => true,
],
```

(You don’t need to add both keys if you only want to set one of them. They’ll default to `false`.)

**Comment by cakleimeier** [comment]
Thank you @brandonkelly ; that's great! I'm sure this feature will be very helpful to a lot of users.

**Comment by brandonkelly** [comment]
Craft 3.6.4 is out now with that new config setting ✨
