### ISSUE TITLE
GraphQl returning empty entries array when using siteId="3" 

### ISSUE THREAD

**Issue by jlaughton87** [craftcms/cms#7513]
### Description
I have 3 sites in a headless Craft install and im using Apollo from my Vue app to grab the entries. siteId: "1" and siteId: "2" return entries just fine but when i try siteId: "3" it returns an empty entries array. All site have loads of entries.

### Steps to reproduce

1. Perform query with siteId="2"

```
entries(siteId: "2") {
    id
 }
```
Returns full array:
![image](https://user-images.githubusercontent.com/14894660/107076620-916cdd00-67e3-11eb-8f96-383b6fcd871c.png)

2. Perform query with siteId="3"

```
entries(siteId: "3") {
    id
 }
```
Returns empty array:
![image](https://user-images.githubusercontent.com/14894660/107076746-c6792f80-67e3-11eb-9e3f-09a8006e2b72.png)

_Note: All queries work using the explorer within craft CMS_

### Additional info

- Craft version: Craft Pro 3.5.17.1
- PHP version:7.4.13
- Database driver & version:MySQL 5.7.29

**Comment by jlaughton87** [comment]
Closing as i hadnt added the section to the publish schema in /graphql/schemas/public

**Comment by brandonkelly** [comment]
Glad you got it working!
