### ISSUE TITLE
"No site settings exist for section XX" for new section when creating first entry type

### ISSUE THREAD

**Issue by howells** [craftcms/cms#7521]
### Description

With Craft 3.6.4.1, when I create a new section and then immediately proceed to editing the entry type, I get an "No site settings exist for section XX" error when saving the new entry type. The section, and the new entry type, both seem to have saved successfully, however. I have to go back to the newly created section, re-save it, and then return to the entry type to save again, whereon it successfully saves.

### Steps to reproduce

1. Create a new section
2. Click save and edit entry types
3. Add fields and hit save
4. Error is shown
5. Go edit the new section, and save
6. Go edit the entry type, and save: it is saved successfully

### Additional info

- Craft version: 3.6.4.1

**Comment by brandonkelly** [comment]
I’m not able to reproduce this, and not really sure how it could have happened. Are you able to reproduce it?

**Comment by howells** [comment]
@brandonkelly Yeah, it's still happening. Would you like to take a look at a database dump? Something else odd is happening with this particular installation: matrix content disappears on publishing a draft every so often, which is very difficult to reliably replicate, so could be a wider problem with this specification instance.

**Comment by howells** [comment]
@brandonkelly when I just replicated these steps to create a new test section, and then tried to delete it, the section wouldn't delete: in the network request the error was "Trying to access array offset on value of type null" from line 1140 in services/Sections.php

**Comment by brandonkelly** [comment]
@howells Hm yeah something must be off with your install. If you send your Composer files and a database backup over to support@craftcms.com we can take a look at it.

**Comment by MattWilcox** [comment]
We are seeing this also.

**Comment by MattWilcox** [comment]
Additional info: The problem went away after I forced a rebuild of the full Project Config.

**Comment by howells** [comment]
@MattWilcox I tried rebuilding too, but doesn't resolve it for me. @brandonkelly I'll send these to you now.

**Comment by howells** [comment]
> @brandonkelly Yeah, it's still happening. Would you like to take a look at a database dump? Something else odd is happening with this particular installation: matrix content disappears on publishing a draft every so often, which is very difficult to reliably replicate, so could be a wider problem with this specification instance.

FYI I found the problem with the matrix content, and it's unrelated

**Comment by MattWilcox** [comment]
And just hit this issue again when saving a new Single entry type.

The Entry itself isd created, the fields are all right, I can save the Entry itself, but going back to Settings > Sections > Edit Enty Type and trying to save that...

<img width="1194" alt="Screen Shot 2021-02-11 at 09 38 13" src="https://user-images.githubusercontent.com/814039/107620644-ef1e8080-6c4c-11eb-8316-86162caefec1.png">

If I then go to Utilities > Project Config > Rebuild, wait for that to complete, and then go Settings > Sections > Edit Entry Type and save - it then works fine.

**Comment by howells** [comment]
@MattWilcox ah yes I just went through these steps and the same happens for me now.

**Comment by brandonkelly** [comment]
Guessing this is related to #7530.

**Comment by brandonkelly** [comment]
We just released 3.6.11.1 with a project config bugfix that I suspect may have been the culprit here. Going to close, but please let me know if you see similar behavior going forward.

**Comment by davist11** [comment]
Hmm I think we are experiencing this error

1. We upgraded to 3.6.11.1
2. Created a new single called Our Team
3. Commited and deployed the project config changes
4. Applied the changes on production

See this error

```
- adding entryTypes.3db09341-3e69-4c8f-bd12-593471d9d5d6.fieldLayouts.508e9d84-700e-4ff9-a9f4-4ace5b4e207a.tabs.0.elements.2 ... 
  - adding entryTypes.3db09341-3e69-4c8f-bd12-593471d9d5d6 ... 
error: No site settings exist for section 33
```

Looking in the production DB, 33 refers to this section:

```yaml
enableVersioning: true
handle: team
name: 'Our Team'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  13954b1a-55b1-48aa-bc59-cce731dde0ca: # MWI
    enabledByDefault: true
    hasUrls: true
    template: _elements/our-team
    uriFormat: our-team
type: single
```

And here is the entry type

```
fieldLayouts:
  508e9d84-700e-4ff9-a9f4-4ace5b4e207a:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 7ab913da-c5dc-43e7-a2ef-1ac54353fcd9 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 34a4735e-ddf5-497c-8c86-e403988c627e # Organization Chart
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: team
hasTitleField: true
name: 'Our Team'
section: 693cd98e-b318-4f8f-8bb8-4014693bfb60 # Our Team
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
```

I see this data in the `projectconfig` table on production

![image](https://user-images.githubusercontent.com/199985/112540901-1c506980-8d89-11eb-88b5-7ad3f16ebce9.png)

![image](https://user-images.githubusercontent.com/199985/112541015-4013af80-8d89-11eb-91e3-69c6100e60ad.png)


I tried force applying as well and got the same error. Let me know if there's any other info I can provide to help debug.

**Comment by brandonkelly** [comment]
@davist11 Probably easiest for us to debug if you send in your Composer files, a database backup, and your incoming `config/project/` folder, to support@craftcms.com.

**Comment by davist11** [comment]
Great thanks, email sent

**Comment by davist11** [comment]
In case anyone else comes across this issue, @andris-sevcenko helped me work it out via email. I had to `./craft clear-caches/data` before applying the project config on the target environment

**Comment by andris-sevcenko** [comment]
Also, updating to the next Craft release(3.6.12, most likely) will invalidate the relevant cached data via a migration, so this exact scenario won't be an issue anymore, then.
