### ISSUE TITLE
Autocomplete attribute for password

### ISSUE THREAD

**Issue by ajanec01** [craftcms/cms#7524]
The password input field on the login page needs `autocomplete="password"` to meet [sc 1.3.5](https://www.w3.org/TR/WCAG21/#identify-input-purpose).
![password](https://user-images.githubusercontent.com/47136246/107293512-a22b8600-6a63-11eb-8101-47b0b1d605d7.png)

It looks like the Username or Email input doesn't need the autocomplete attribute  for conformance but it wouldn't hurt I guess to give it `autocomplete="email"`

### Additional info

- Craft version: 3.6.4.1

**Comment by brandonkelly** [comment]
What exactly are you suggesting? That we add `autocomplete="email"` to the username input?

**Comment by ajanec01** [comment]
Yes. So, some input fields that collect information about the user need to have properties that will allow the inputs/ labels to be customised. 

At the moment, only autocomplete is letting you do that. The trouble is that there is no autocomplete for username input and the label for that form field is "username or email". I'm not 100% sure if that would be a WCAG failure if that input didn't have autocomplete (might be a subjective thing), so suggest to add autocomplete="email" to be on the safe side. 

By the way, if you're in any way concerned about the security (I know some people are), you can disable the auto filling by setting autocomplete="off" on the form element. It's not so much about the auto filling but being able to query a property, although auto filling would benefit people with motor and cognitive impairments.

**Comment by brandonkelly** [comment]
I’ll leave it to @missmatsuko to make the call :)
