### ISSUE TITLE
Project zip occasionally missing categoryGroups YAML files

### ISSUE THREAD

**Issue by jlawrence-yellostudio** [craftcms/cms#7530]
### Description

I had a strange issue the other day when pulling some changes from staging onto my local machine. I rebuilt the config and downloaded the zip, initially I didn't notice the zip file was 5KB smaller than one I had done a few minutes prior. When I removed the old project folder and added the new contents from the zip I found the source control was reporting several deletions, all category groups. When I re-downloaded the zip file, the category groups were back again. 

At first I wasn't going to report this as I only had it once, however today I managed to completely wipe out all my local category groups and associated relations.

If you need any more information I can try to provide as much as possible as I'm keen to discover what is causing this. 

As far as I can tell there doesn't appear to be any errors in the logs related to this.

### Steps to reproduce

1. Go to utilities, project config, rebuild
2. Download zip
3. File is occasionally entirely missing categoryGroups.

### Additional info

- Craft version: 3.6.4.1
- PHP version: 7.3.26

**Comment by brandonkelly** [comment]
Looks like category groups aren’t getting fully saved to the project config when created, for some reason. We’re looking into it and will fix.

You should be able to get your category groups and categories back if you revert the `config/project/` changes that removed the groups (assuming they were in fact there to begin with), and then run `php craft project-config/apply`.

**Comment by jlawrence-yellostudio** [comment]
@brandonkelly Thanks I had a copy of the data anyway so all good :)

**Comment by brandonkelly** [comment]
We just released 3.6.11.1 with a project config bugfix that I suspect may have been the culprit here. Going to close, but please let me know if you see similar behavior going forward.
