### ISSUE TITLE
Wrong Entry Returning when utilizing a route when the Slug contains a hyphen

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [craftcms/cms#7533]
### Description

So this one is quite the mystery to me. I have this route setup in the CP:

![Screen Shot 2021-02-09 at 8 27 54 PM](https://user-images.githubusercontent.com/39201467/107460424-59cca080-6b15-11eb-8d79-288ab52d4978.png)

We have urls like so `/activities/figure-skating/adult`

When I dump those values like:

```
<pre>{{ dump(slug) }}</pre>
    {# If slug is true then we are on an /activity/basketball/youth URL #}
    {% if slug is defined %}
        {% set entryId = craft.entries.slug(slug).one().id() %}
        <pre>{{ dump(entryId) }}</pre>{% exit %}
        {%- include '_organisms/entry-types/page--activity' ignore missing with {
            entry: craft.entries.id(entryId).one(),
            utilities: 'px-6',
        } -%}
    {% endif %}
```

I get this output:

```
string(14) "figure-skating"
int(46966)
```

The first is the `slug` and the other is a non-existent id.

Yet if I go to `activities/basketball/adult` I get the correct info outputting:

```
string(10) "basketball"
int(1637)
```

That is the case with every single entry. But once there's a `-` in the URL Craft doesn't return the correct results.

### Additional info

- Craft version: 3.5.18
- PHP version: 7.4.13
- Database driver & version: MySQL 5.5.5

This seems to be a legit bug but curious your thoughts on it and appreciate the help on this one!

**Comment by brandonkelly** [comment]
> The first is the `slug` and the other is a non-existent id.

What happens if you go to `/admin/edit/1637`?

**Comment by DynamiteGoesBoom** [comment]
@brandonkelly thanks for the quick response! `1637` isn't the issue, as that `slug` doesn't contain a hyphen, it's the output of the first item I mentioned, that contains a hyphen, that is the issue:

```
string(14) "figure-skating"
int(46966)
```
I have no idea why anything with a hyphen would not return the correct `id` and that's where I was hoping to get some help from you lovely folks :) It certainly seems like a bug that I'm hoping y'all can squash 🐛 

Thanks again for the help again!

**Comment by brandonkelly** [comment]
My guess is that there is in fact something else in the system with that same `figure-skating` slug, and it does in fact have an ID of  1637. (Entry queries don’t just make up non-existent IDs.) Going to `/admin/edit/1637` might even take you to it, if it’s a normal entry.

**Comment by DynamiteGoesBoom** [comment]
@brandonkelly Hmm yeah there is another entry with that slug for `figure-skating` and that's coming from another Channel. I guess I'll have to look into targeting those entries a bit more specifically. 

Thanks for the help!
