### ISSUE TITLE
Missing `/craft.bat` file in Craft root dir after `composer create-project craftcms/craft .`

### ISSUE THREAD

**Issue by proimage** [craftcms/cms#7536]
### Description
I ran `composer create-project craftcms/craft .` in a new project folder. When it was finished, there was no `craft.bat` file, so the post-install `./craft setup` command didn't work under Windows.

### Additional info

- OS: Windows 10
- Craft version: 3.6.4
- PHP version: 7.4.13
- Composer version: 2.0.9

**Comment by brandonkelly** [comment]
Sorry for the confusion; we recommend running the `craft` executable via your system’s `php` command now, but we forgot to update the `setup/welcome` command output to demonstrate that.

Run this instead:

```bash
php craft setup
```

**Comment by proimage** [comment]
Does that hold true for all the `craft *` commands, like `project-config/apply` and `db/backup --zip`, etc?

**Comment by brandonkelly** [comment]
Yep!
