### ISSUE TITLE
GraphQL image transform width and height don't match the actual image size with upscaling disabled

### ISSUE THREAD

**Issue by FreekVR** [craftcms/cms#7537]
### Description
When requesting a transformed images' width / height properties they don't match the actual dimensions of the image behind the URL if the uploaded image is smaller than the (max) size of the transform (and upscaling is disabled)

![image](https://user-images.githubusercontent.com/417416/107518384-39512480-6baf-11eb-997f-c907ec534323.png)

### Steps to reproduce

1. Upload an image, eg. 180x73 in dimensions
2. Request a transform via graphql, including the resized dimensions, eg
```
fragment companyLogoFragment on CompanyProfiles_companyProfile_Entry {
    logoimage {
        url @transform(mode: "fit", width: 250)
        width @transform(mode: "fit", width: 250)
        height @transform(mode: "fit", width: 250)
    }
}
```

The resized image behind "url" will be 180x73 (the original size, which makes sense, with upscaling disabled).

However, the width / height attributes will be 250x101, the likely size if upscaling were enabled.

This appears to be a regression in Craft somewhere, as I reported this bug earlier and it was fixed somewhere in the 3.4x/3.5x branches at the time iirc.

### Additional info

- Craft version: 3.6.4.1
- PHP version: 7.4
- Database driver & version: MySQL 8
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
That’s expected – it’s telling you the width and height that the image should be displayed at, per the transform `width` you passed.

If you want the actual image width/height, don’t add `width: 250`, or perhaps you can add additional `actualWidth` and `actionHeight` properties to the query (as aliases of `width` and `height` without transforms set), and do your own logic in JS to decide which set of widths/heights you care about.
