### ISSUE TITLE
Matrix / Supertable block fields seem to be inheriting the field group id of parent field and appearing the admin fields area since 3.6.5 update

### ISSUE THREAD

**Issue by jlawrence-yellostudio** [craftcms/cms#7540]
### Description
I just updated to 3.6.5 thinking it might fix this [issue](https://github.com/craftcms/cms/issues/7530) i was having with project config , but now when I save a matrix field, the block fields seem to be inheriting the field group id of the parent field and they are now visible in the CMS with this admin fields area if you select a field group. 

### Steps to reproduce

1. Create a field group
2. Create a matrix field with a block type and a field for that block type within that field group.
3. Now go to fields, select that group, the matrix block type field appears in the list (as if it had no context). Under all fields it does not appear.

![Screenshot 2021-02-10 at 21 04 51](https://user-images.githubusercontent.com/5747299/107572756-97e4c580-6be4-11eb-9bd7-2bf190d3297b.png)
![Screenshot 2021-02-10 at 21 11 42](https://user-images.githubusercontent.com/5747299/107572766-987d5c00-6be4-11eb-8829-08e3f6df8be3.png)
![Screenshot 2021-02-10 at 21 13 09](https://user-images.githubusercontent.com/5747299/107572939-d0849f00-6be4-11eb-83c2-b6af43c60382.png)

### Additional info

- Craft version: 3.6.5
- PHP version: 7.3.26

**Comment by brandonkelly** [comment]
Thanks for reporting that! It was introduced by 29cd8b2cfe94cd81915d09314505ef6602111579. Just released Craft 3.6.5.1 with a fix.
