### ISSUE TITLE
Redactor saving absolute URLs for links to entries

### ISSUE THREAD

**Issue by sidm1983** [craftcms/cms#7548]
### Description
**NOTE: I know the title says "Redactor", but this could be an issue with how my craft default site is set up.**

I have a Craft CMS site running in headless mode. The site has a section/entry type called `Article` which has a `Matrix` field with a `Redactor` field within it.

When I insert a link in the redactor field to another article entry, I can see that it saves the `<a>` tag with an `href` value of `http://localhost:5000/article/my-first-article#entry:35@1:url`.

How do I get redactor to save a relative URL (i.e. not save the `http://localhost:5000` part)? Like this `/article/my-first-article#entry:35@1:url`

As I mentioned above, the CMS is running in headless mode as a back-end to a SPA. Having an absolute URL will likely cause the SPA to do a full refresh instead of just updating a part of the view.

Apologies if this is a redactor issue. I thought I'd ask here first in case it was a configuration issue with my site's base URL.

Please let me know if this is a redactor issue and I will raise a new issue in the redactor repo.

Thank you.

### Additional info

- Craft version: v3.6.4.1
- PHP version: 7.3
- Database driver & version: PGSQL 11
- Plugins & versions: Redactor 2.8.5

**Comment by brandonkelly** [comment]
That’s just the URL you’re going to see within the Redactor editor. In the database it will be saved as a [reference tag](https://craftcms.com/docs/3.x/reference-tags.html), e.g. `{entry:35@1:url||http://localhost:5000/article/my-first-article}`. The URL to the right of the `||` is just the fallback value, which would only be output on your front end if Craft isn’t able to find an entry with an ID of 35, in site 1.
