### ISSUE TITLE
Entries Field - unable to change order of elements

### ISSUE THREAD

**Issue by iwe-hi** [craftcms/cms#7549]
### Description
Since CMS V3.6.5.1 I am unable to change the order of the elements in an entries field. Even the delete buttons is hidden underneath the status icon. The Image shows the same page in different CMS Versions.

![image](https://user-images.githubusercontent.com/78907655/107633752-cefcba80-6c68-11eb-978d-d3d0cdd7f218.png)

### Steps to reproduce

1. Create an entries field.
2. Add entries field to an entry.
3. Change the order

### Additional info

- Craft version: 3.6.5.1
- PHP version: 7.4.12
- Database driver & version: MySQL 5.7.32
- Plugins & versions: Element API 2.6.0, Expanded Singles 1.1.3, Field Manager 2.2.2, Linkit 1.1.12.1, Neo 2.8.19, Redactor 2.8.5

**Comment by brandonkelly** [comment]
Fixed for the next release. Sorry about that!

**Comment by brandonkelly** [comment]
Craft 3.6.6 is out now with this bugfix.
