### ISSUE TITLE
gqlTypePrefix should not prefix root Types

### ISSUE THREAD

**Issue by membla** [craftcms/cms#7552]
### Description

Setting `gqlTypePrefix` also prefixes the root query and mutation types – which is likely to have consequences for many GraphQL clients.

**Comment by brandonkelly** [comment]
Hey @membla, we just released Craft 3.6.6 with a new `prefixGqlRootTypes` config setting, which toggles whether `query`, `mutation`, and `subscription` types should be prefixed.

So if you add this to `config/general.php`, you’ll get the expected behavior:

```php
'prefixGqlRootTypes' => false,
```
