### ISSUE TITLE
Add ability to have a structure collapsed by default or by a button

### ISSUE THREAD

**Issue by 2mas** [craftcms/cms#7553]
### Description
Hi! It would be great if there was a way to have the top-level entries collapsed by default in a structure. Editors experience difficulty when navigating through entries when the structure becomes large, especially when they are selecting an entry from a relation-field and the window gets smaller. 

I noticed the collapsed entries are stored in local-storage and by default it's empty, perhaps the top-level entries could be put there on initialization? Or just have an option to never expand the structure automatically?

I made a quick temporary solution with a button to collapse items in the meanwhile that "works", but since elements are getting loaded continuosly one has to press the button multiple times and it's probably not the best way to do this.

If anyone is interested in this approach in the meanwhile, here it is:

![demo-structure-collapse](https://user-images.githubusercontent.com/372362/107641201-96161300-6c73-11eb-9d58-6771f105d399.gif)

And it's only js at the moment, running with Control Panel JS

```
var Myh = {

    init: function() {
        this.displayCollapseButton();
    },

    /**
    * Displays a button to collapse top-levels in a structure
    */
    displayCollapseButton: function() {
        if (Craft.path.search('entries') === 0) {
            if ($('.tableview [data-level=1] .toggle.expanded').length && !$('#myh-collapser').length) {
                $('<div id="myh-collapser"><button onclick="Myh.collapseAll()" type="button" class="btn statusmenubtn" tabindex="0">' + 
                  Craft.t('app', 'Collapse all') + '</button></div>').prependTo($('.toolbar, #toolbar'));
            }
        }
    },

    /**
    * Collapses top-level by triggering a click on each
    */
    collapseAll: function() {
        $('.tableview [data-level=1] .toggle.expanded').click();
    },

};

Garnish.$doc.ready(function() {
    Myh.init();
});
```

**Comment by jsunsawyer** [comment]
To add to this, a way to check/uncheck all blocks in a matrix field would be a fantastic addition.

Currently, you can check/uncheck all blocks through some really obscure hotkeys, but it's not clear to users. Being able to collapse all matrix blocks helps when working with content that needs to be sorted.

Current way to check/uncheck all:
_Note: Using mac hotkeys_

- **Select all:** Check a box, then click cmd + a
- **Deselect all:** Cmd + click a single checkbox, then click again to deselect it

This would allow users to toggle the collapsed and enabled/disabled states for multiple blocks more easily.
![Screen Shot 2021-02-11 at 9 21 32 AM](https://user-images.githubusercontent.com/1007191/107673183-9bab3300-6c4a-11eb-8525-c6740fd59945.png)

**Comment by brandonkelly** [comment]
This idea was previously requested by #7097.

@jsunsawyer That was requested by #1880.

**Comment by 2mas** [comment]
@brandonkelly Sorry about that. It seems #7097 is also closed now without resolution

**Comment by brandonkelly** [comment]
Doh, reopened.
