### ISSUE TITLE
Live preview not updating back to saved state

### ISSUE THREAD

**Issue by samuelbirch** [craftcms/cms#7554]
If i have an entry that is already saved with content, when editing this entry and viewing it in live preview, if i change the content the live preview updates with the changes, but if i change it back to what it was (the saved version) then the live preview doesn't update.

**Comment by brandonkelly** [comment]
What version of Craft are you running? Are you getting any JavaScript errors on the page?

**Comment by samuelbirch** [comment]
I'm using the latest version, and there are no js errors when the preview refreshes, but there is one when the live preview is closed (but looks unrelated to this issue)

```
jquery.js? [sm]:5004 Uncaught TypeError: Cannot read property 'createDocumentFragment' of undefined
    at xe (jquery.js? [sm]:5004)
    at Re (jquery.js? [sm]:6073)
    at b.fn.init.append (jquery.js? [sm]:6264)
    at b.fn.init.b.each.b.fn.<computed> [as appendTo] (jquery.js? [sm]:6398)
    at Object.handler (RedactorOverrides.js:410)
    at s.constructor.trigger (garnish.js? [sm]:840)
    at s.constructor.close (Preview.js:385)
    at s.constructor.<anonymous> (garnish.js? [sm]:893)
    at HTMLButtonElement.o (jquery.js? [sm]:10771)
    at HTMLButtonElement.dispatch (jquery.js? [sm]:5429)
```

**Comment by brandonkelly** [comment]
Do you have any plugins installed? Can you make sure they’re all up-to-date?

**Comment by samuelbirch** [comment]
neo is the main one (i've disabled all the others) and all plugins are up to date.

**Comment by brandonkelly** [comment]
Is this happening within a Neo field?

**Comment by samuelbirch** [comment]
yes it is. 
I've just created a simple test without the neo field and it works fine. Must be something with that plugin, i'll create an issue on that plugin repo.
thanks and sorry for wasting your time.

**Comment by brandonkelly** [comment]
Sounds good. Can you link me to it once you have? I might be able to offer some guidance.

**Comment by samuelbirch** [comment]
@brandonkelly There is an issue that's already been raised, so i've just added my bit to it: https://github.com/spicywebau/craft-neo/issues/419

Fingers crossed you can help :)
