### ISSUE TITLE
Plugin calling element->updateSearchIndex() doesn't clear GraphQL cache

### ISSUE THREAD

**Issue by weotch** [craftcms/cms#7556]
### Description

I am using [Scheduler](https://github.com/supercool/scheduler) with my headless Craft instance to trigger webhooks when an entry with a future-dated Post Date switches to being Enabled from Pending.  This is working, the webhook fires.  It works by resaving elements who had had a future-dated Post Date in order to trigger anything listening to those save events.  [Here is where](https://github.com/supercool/scheduler/blob/530eb5d3d197d331d0de42597e5d30fa24afb1e4/src/jobs/SchedulerReSaveElementJob.php#L50-L67) this happens in their source code: 

```php
// Re-save the element using the Element Types save method
// Now save it
if ( Craft::$app->elements->saveElement($element, false) )
{

	// Check if the element has an owner (MatrixBlock, SuperTableBlockElement)
	// and if so, then save that too
	if ($element instanceof \craft\elements\MatrixBlock || $element instanceof \verbb\supertable\elements\SuperTableBlockElement)
	{
		$owner = $element->getOwner();
		if ($owner)
		{
			Craft::$app->elements->saveElement($owner, false);
		}
	}

	return true;
}
```

However, the GraphQL cache is not cleared by this save and, when my static site generation process executes (as triggered by the webhook), it is using stale data which doesn't include the entry that _just_ became Enabled.   I'm posting this here rather than at the plugin because I feel like Craft _should_ be clearing it's cache on `saveElement()` calls.

As a workaround, I intend to use the `X-Craft-Gql-Cache` header to disable the cache on static site generation requests.

### Steps to reproduce

1. Make an entry with a future post date.
2. Execute a graphql query that would return it.  It should not show up in the response since it's not enabled yet.
3. Wait until that post date is in the past.
4. Resave the entry via plugin, like `Craft::$app->elements->saveElement($entry, false`)
5. Execute the same graphql query again.  I would expect the entry to show up in the response but it doesn't.

### Additional info

- Craft version: 3.5.18
- PHP version: 7.4.3
- Database driver & version: MySQL 8.0.20
- Plugins & versions:

![image](https://user-images.githubusercontent.com/77567/107676629-335e5080-6c4e-11eb-8dc7-ec119333f5a0.png)

**Comment by brandonkelly** [comment]
I feel like this should work, but even if it did, resaving elements is pretty overkill if you just want to clear their caches.

You could call `Craft::$app->gql->invalidateCaches()` to invalidate all GraphQL query caches, or `Craft::$app->elements->invalidateCachesForElement($elementId)` to invalidate caches for a specific element.

**Comment by weotch** [comment]
Oh nice, thanks for the pointers, I'll see about getting that PRed into that plugin.

The re-save isn't _just_ to clear caches, it's also to trigger [webhooks](https://github.com/craftcms/webhooks).  For our use case, a more focused plugin that fired webhooks and cleared the graphql cache when a future-dated entry became enabled would be 💯.
