### ISSUE TITLE
Cannot install PHP 7.3 plugin

### ISSUE THREAD

**Issue by blieque** [craftcms/cms#7558]
### Description

I'm unable to install a plugin which depends on PHP 7.3+ – based on the value of `require.php` in `composer.json`. See fortrabbit/craft-object-storage#14 for specifics.

Can Craft's [`config.platform.php` version in `composer.json`](https://github.com/craftcms/cms/blob/develop/composer.json#L90) be bumped up to PHP 7.3? It's been bumped to PHP 7.4 in the Craft 4.0 branch, and Craft is running fine on PHP 7.3.22. Would bumping the version cause problems for other plugins?

I'm running Craft in a way which doesn't give me shell access, so I can't run `composer install --ignore-platform-reqs`. I also feel like requiring manual installation with Composer isn't a proper solution.

### Steps to reproduce

1. Attempt to install, e.g., [fortrabbit-object-storage](https://plugins.craftcms.com/fortrabbit-object-storage) on a fresh Craft 3.x installation without using `composer install --ignore-platform-reqs`.

### Additional info

- Craft version: 3.6.5.1
- PHP version: 7.3.22
- Database driver & version: MariaDB, 5.5.5
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
We can’t change that value without increasing Craft’s minimum PHP requirement. Plugins should not be requiring a PHP version greater than Craft’s own minimum version.
