### ISSUE TITLE
Stuck on "To complete the update, some changes must be made to your database."

### ISSUE THREAD

**Issue by danieladarve** [craftcms/cms#7559]
### Description
Successfully updated craft via terminal, But the Admin login screen is stuck on the  "To complete the update, some changes must be made to your database." window... Once you click on the Finish up button, it throws the following error
```
HTTP 400 – Bad Request – yii\web\BadRequestHttpException
Unable to verify your data submission.
```

### Additional info

- Craft version:  3.6.5.1
- PHP version: 7.4.9 
- Database driver & version: MySQL

**Comment by danieladarve** [comment]
Fixed by running 
```
./craft update/composer-install
 ./craft project-config/rebuild
```

**Comment by brandonkelly** [comment]
Hm that’s strange. Can you tell me a bit about your environment? Are you using Docker, etc? Is PHP’s OPcache extension enabled?

**Comment by danieladarve** [comment]
Locally I'm using Laravel Valet, no OPcache


nginx version: nginx/1.19.6

PHP 8.0.2

where the same issue happened.

in production it is running a simple VPS nginx server, PHP 8.0.2, ubuntu,
mysql. I do have redis enabled tho on this one

**Comment by brandonkelly** [comment]
Alright, well let me know if you hit it again. Not able to reproduce on my end.

**Comment by danieladarve** [comment]
Will do, thanks!
