### ISSUE TITLE
Request->getUserIp() returns the first IP found in comma separated list.... should it?

### ISSUE THREAD

**Issue by GaryReckard** [craftcms/cms#7563]
We've recently run into an issue with an IP whitelisting feature we built for a client. We maintain a list of IP addresses and CIDR ranges that are whitelisted, and compare the request IP to see if the current request should be whitelisted.

For a client using a certain proxy, their `X-Forwarded-For` header contains a comma-separated-list of multiple IPs.

This code stops at the first valid IP it finds:
https://github.com/craftcms/cms/blob/a12ca9b06ed49501ee042970a56ec0f3ee643440/src/web/Request.php#L1112-L1116

According to Wikipedia (https://en.m.wikipedia.org/wiki/X-Forwarded-For#Format): " the left-most being the original client, and each successive proxy that passed the request adding the IP address where it received the request from"

So, by stopping at the first IP, Craft is returning the user's original IP. But I imagine in most cases where a proxy is being used, the user would rather be identified by the last proxy IP to be used. 

I could be way off here... as I'm not sure what the bulk of the use-cases are for getting the users IP, and which would be preferred. Perhaps it would be nice to have a new public method in the 'Request' class that returns the last IP rather than the first?

For my situation, I just stole the meat out of `getUserIP()`, and cross reference every IP found rather than stopping at the first.

OKBYE

**Comment by brandonkelly** [comment]
The function description is “Returns the user IP address”, so I’d say the closer we can get to the actual user IP, the better.

**Comment by GaryReckard** [comment]
Understood. 

Just want to note that, in this specific case, Craft's `getUserIP` was returning a different result than the client got when googling 'what is my ip' or visiting a site like https://www.whatismyip.com/. I'm not sure what criteria those tools use to determine the IP to output.

**Comment by brandonkelly** [comment]
Probably a proxy/gateway server misconfiguration.
