### ISSUE TITLE
Entries field UI broken

### ISSUE THREAD

**Issue by leightonhughes** [craftcms/cms#7565]
### Description
The x icon that removes an entry from the entries fieldtype is hidden behind the green status icon. This prevents reordering entries and double clicking on to view content.

### Steps to reproduce

1. Updated to 3.6.5.1

### Additional info

- Craft version: 3.6.5.1
- PHP version: 7.3.25
- Database driver & version: NA
- Plugins & versions: NA

**Comment by garycrane** [comment]
Same here. Looks like a CSS issue with body.ltr .element.small.hasstatus .icon
[http://recordit.co/LGoMQ3lweT]

**Comment by thupsi** [comment]
Is it this one? https://github.com/craftcms/cms/issues/7549

**Comment by garycrane** [comment]
> Is it this one? #7549

Ah, yeah. Looks like the same issue.

**Comment by brandonkelly** [comment]
Craft 3.6.6 is out now with a fix for this.
