### ISSUE TITLE
Setting the `ttr` higher than 1 hour, but jobs seem to stall out after 1 hour

### ISSUE THREAD

**Issue by aaronbushnell** [craftcms/cms#7566]
### Description
We currently have our `ttr` set to `14400` in our `config/app.php` file:
```php
<?php

return [
    '*' => [
        'modules' => [
            // Module mapping
        ],
        'bootstrap' => [
            // Modules
        ],
        'components' => [
            'queue' => [
                'ttr' => 14400,     // 4 hours
            ],
        ]
    ],

    'staging' => [
        // Staging config
    ],

    'production' => [
      // Prod config
    ],

    'local' => [
      // Local config
    ]
];

```

However we're seeing queued tasks that take longer than one hour stop running after one hour instead of the expected 4 hours. The job isn't marked as "cancelled". It continues to have a "Reserved" status and give the appearance it should be running but the last **Updated at** is approximately an hour after the feed started.

**Notable queue notes:**
- We have `runQueueAutomatically` set to `false` for this environment
- We have a cron job that fires `php craft queue/run` every minute
- I did a quick `CMD+F` in the "PHP Info" section for `3600` to see if there are any PHP config values set to an hour and it turned up nothing

### Steps to reproduce

1. Set the `ttr` to something higher than 1 hour (3600)
2. Run a queue job that takes more than one hour to complete (perhaps 1.5 hours)

### Additional info

- Craft version: Craft Pro 3.5.18
- PHP version: 7.0.33
- Database driver & version: MySQL 5.6.44
- Plugins & versions:
```
Algolia                  2.0.0
Amazon S3                1.2.11
Amplify                  1.0.10
Blitz                    3.7.0
Calendar                 3.0.15
Element API              2.6.0
Entry Instructions       1.0.7
Feed Me                  4.3.4
Formstack                2.0.1
Help                     2.0.5
Isolate                  1.4.3
Molecule                 1.2.0
Neo                      2.8.17
Redactor                 2.8.5
Retour                   3.1.45
SEOmatic                 3.3.29
Sidebar Entry Types      1.0.3
Smart Map                3.3.5
Store Hours              2.1.1.1
Visor                    3.0.1
Wordsmith                3.3.0.1
Workflow                 1.5.8
```

**Comment by brandonkelly** [comment]
> * We have `runQueueAutomatically` set to `false` for this environment

How exactly are you running the queue?

**Comment by aaronbushnell** [comment]
Hey @brandonkelly — we use a cron job to run `php craft queue/run` every minute

**Comment by brandonkelly** [comment]
SSH into the environment and run this command:

```bash
> php -i | grep max_execution_time
```

What does it output?

**Comment by aaronbushnell** [comment]
```sh
> php -i | grep max_execution_time
> max_execution_time => 0 => 0
```

And in the "PHP Info" within Craft:
>**max_execution_time**: 600

**Comment by brandonkelly** [comment]
Are you sure it’s getting cut off at exactly an hour? It could just seem like it’s about that long, but maybe PHP ends up running out of memory or something. Have you checked `storage/logs/phperrors.log` to see if anything is getting logged there?

**Comment by aaronbushnell** [comment]
Hey @brandonkelly — it's pretty consistently hitting about an hour! I'll run a process tonight, grab some screenshots and send them along.

Unfortunately this is happening in a load-balanced environment so it'll be tricky to pull the `phperrors.log` file. Though we do have this site dumping logs into New Relic. Do you have any suggestions on what I could search for when perusing through those? Should I do a search for anything with `[error]`?

**Comment by brandonkelly** [comment]
PHP fatal errors (such as running out of memory or running up to the max_execution_time) are logged separately from Craft logs, with this format:

```
[11-Feb-2021 23:21:22 UTC] Error message goes here
```

Not sure whether New Relic is capable of capturing those or what it would do with them, though.

**Comment by aaronbushnell** [comment]
Thanks! We use New Relic’s “logging” feature which is comparable to Papertrail’s logging aggregator. I’ll look in there which will aggregate all of Craft’s log files from the servers in the load balancer pool

**Comment by khalwat** [comment]
@aaronbushnell What queue job do you have that's taking over an hour to execute? Is it calling `->setProgress()` at various intervals during its execution?

In case it's useful: [Understanding TTR](https://nystudio107.com/blog/robust-queue-job-handling-in-craft-cms#understanding-ttr)

You could try setting the TTR to `null` which means "never timeout"

**Comment by aaronbushnell** [comment]
This particular task is a Feed Me import, @khalwat.

I’ll grab some logs and some screenshots for debugging to see if it helps crack the problem!

**Comment by aaronbushnell** [comment]
Hey @brandonkelly — I'll pull some logs ASAP but here's a sped up screen recording of this particular task (a Feed Me import) running for ~1 hour before it stops at 46% and never makes additional progress.

While this particular problem is occurring with Feed Me I've also see other tasks that are lengthy have the same effect (running for 1 hour and then never finishing)
![TTR Task](https://user-images.githubusercontent.com/315202/108006381-4ca62a80-6fc9-11eb-88cc-f46193730d51.gif)

**Comment by aaronbushnell** [comment]
Hey @brandonkelly — I couldn't find much in the way of logs. In fact, I checked every server in the load balancer pool and none of them had a `phperrors.log` file in `/storage/logs`. Is there something else I could check that might be of use to you all? Happy to pull anything or run any further diagnostics that might be helpful!

**Comment by angrybrad** [comment]
@aaronbushnell maybe your host is doing something unusual to terminate long-running connections? Have you tried contacting them?

**Comment by aaronbushnell** [comment]
I’ll ask, @angrybrad! Do you have a short list of which settings might impact this? PHP, MySQL or otherwise? Not sure which ones would be the most obvious to check in relation to the queue

**Comment by brandonkelly** [comment]
@aaronbushnell We’re a bit stumped unfortunately. The only one we could think of was `max_execution_time`, which seems to be set to `0` (no limit).

**Comment by aaronbushnell** [comment]
No sweat! I’ll drop a request over to them to see if they have anything. I’ll report back as we get closer to the solution here.

**Comment by aaronbushnell** [comment]
Hey everyone! This was a niche thing as you all suspected. Our host uses a custom service to allow us to run Craft commands (like the `queue/run` command). That custom service had a 3600 second timeout that caused this to pause and prevent longer tasks from completing.

Thanks for your help here!

**Comment by brandonkelly** [comment]
Aha! Glad you were able to get to the bottom of it!
