### ISSUE TITLE
Draggable area is very small when re-ordering items within an entries field

### ISSUE THREAD

**Issue by tomkiss** [craftcms/cms#7567]
### Description

A small bug, but I noticed that when dragging entries on an entries field to change their order, the hit area is very small which makes dragging very difficult. Also, the largest hit area is to remove the entry- which is not apparent in the UI/.

### Steps to reproduce

1. Add some entries to an entries field.
2. Try to reorder them without removing any, it can be tricky.

Articles in an entries field appear like this:
<img width="178" alt="Screenshot 2021-02-13 at 16 47 49" src="https://user-images.githubusercontent.com/183310/107855773-39099100-6e1c-11eb-844f-0a59ee41bd4b.png">

The green area here is the draggable area. Note that the cursor displayed is not a drag cursor, so it's not clear that this is a draggable area.

<img width="163" alt="Screenshot 2021-02-13 at 16 47 42" src="https://user-images.githubusercontent.com/183310/107855710-cbf5fb80-6e1b-11eb-84aa-60ac4ffdd260.png">

The area in blue here is the hit area for removing the entry from the field. Aside from the tooltip/title attribute, there's no indication that clicking it will remove it:

<img width="194" alt="Screenshot 2021-02-13 at 16 47 27" src="https://user-images.githubusercontent.com/183310/107855721-e203bc00-6e1b-11eb-8f69-b357b04e7327.png">

### Additional info

- Craft version: 3.6.5.1

**Comment by thupsi** [comment]
I think you are refering to the same issue as https://github.com/craftcms/cms/issues/7549

**Comment by tomkiss** [comment]
Hmmm, yes that does appear to be the same issue. Alas I did search but didn't find that issue. 

OK, thanks for the heads up!

**Comment by brandonkelly** [comment]
Craft 3.6.6 is out now with a fix for this.
