### ISSUE TITLE
Category fields display issue - remove button floats underneath

### ISSUE THREAD

**Issue by KarlBishop** [craftcms/cms#7571]
### Description
After selecting a category, the category's title is shown but the remove button ('x' button) is floating underneath the status dot. I can just see the bottom of the 'x' button peeking out from under the green circle, which makes it look like the stylesheet didn't load properly. It is at first unclear (a) where the remove button is and (b) that clicking the category's title will actually click the remove button.

I would normally expect clicking the title to re-open the category list to change my selection rather than remove it (kind of like a dropdown). And that a remove button would be separate and clearly visible.

Also, side note: double-clicking the status dot or anywhere within the category div that isn't over the text/remove button opens a mini-editor modal for the category - this is nice but hard to find!

### Steps to reproduce

1. Create a Category field
2. Add field to an Entry type
3. Edit an Entry that has the Category field and try adding a category

### Additional info

- Craft version: 3.6.5.1
- PHP version: 7.4.4
- Database driver & version: MySQL 8.0.2

**Comment by KarlBishop** [comment]
Actually, looks like same issue as #7565 and #7549 etc (but with Category fields instead of Entry fields)

**Comment by brandonkelly** [comment]
Craft 3.6.6 is out now with a fix for this.
