### ISSUE TITLE
Notification blocks breadcrumbs

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/cms#7572]
### Description

I was wondering why the hitbox of the breadcrumbs were so odd at times. Well I finally figured it out, the notification was blocking it!

![Screenshot 2021-02-15 at 14 56 32](https://user-images.githubusercontent.com/2922378/107955531-2e770500-6f9e-11eb-8e0d-a569c47a6a0b.png)

`pointer-events: none;` would probably be the right solution for this.

### Steps to reproduce

1. For example save a section type
2. Try to press the breadcrumbs, only the few pixels on the bottom will let you press it.

### Additional info

- Craft version: 3.6.5.1

**Comment by brandonkelly** [comment]
This has been fixed for the next release 🎉

**Comment by brandonkelly** [comment]
Craft 3.6.13 is out with this fix.
