### ISSUE TITLE
Be able to delete drafts by batch

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#7573]
### Description

Since Craft 3.6, I got tons of drafts mixed with published entries in my sections lists.

I never realized there're so much, and lots of them are totally empty (_Untitled entry_) and never published.

When I filter the entries view to only show _Drafts_, I can select all but unfortunately there's no option to delete them by batch (only the _Enable_ / _Disable_ option is showing up).

It would be very useful to be able to delete some of them from there, because going to each draft and click the _Delete_ draft button is time consuming.

**Comment by brandonkelly** [comment]
> Since Craft 3.6, I got tons of drafts mixed with published entries in my sections lists.

Some of those should be filtered out in Craft 3.6.6, as Craft now only shows unpublished drafts that have actually been updated with content.

> When I filter the entries view to only show _Drafts_, I can select all but unfortunately there's no option to delete them by batch (only the _Enable_ / _Disable_ option is showing up).

Guessing you had the “All entries” source selected, which historically has not allowed you to delete entries from. However that too has been improved in 3.6.6 (#7545).
