### ISSUE TITLE
Allow specifying inclusive sets of criteria when using the `relatedTo*` arguments in GraphQL

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/cms#7576]
### Description

As of #7528, it's possible to specify multiple sets of criteria which are then applied using "and" - namely, an element must be present in all of the criteria sets.

It would be great if it was possible to make this behave in an inclusive, rather an exclusive way, where an element has to be present in any of the criteria sets.

**Comment by joshuabaker** [comment]
Could this work as it does in Twig, where the first child is just a string (i.e. `["or", ...]`)? That works really nicely, including for nested criteria.

**Comment by andris-sevcenko** [comment]
That's not possible with GraphQL, unfortunately. It's possible to mix and match scalar values by some creative validation on the PHP end, but it's not possible to have a list of "scalar or complex" values.

The currently planned approach is to have a syntax like
``` graphql
{
    operation: "and", 
    criteria: [
        {entryCriteriaObject},
        {entryCriteriaObject}
    ]
}
```
