### ISSUE TITLE
Permissions Screwy after 3.6.6 upgrade

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#7578]
### Description
Here's what I've noticed so far:

- As an admin, I cannot reorder any structure (`admin/actions/structures/move-element` returns 403 with `{"error":"User is not authorized to perform this action"}`
- As an admin, when editing a user, I get "This action may only be performed with an elevated session."

I'll post more as I dig, just wanted to see if others had the same trouble, and if it was related to 3.6.6 upgrade.

**Comment by timkelty** [comment]
As hoped/expected, this didn't actually have anything to do with 3.6.6. Unrelated session issue. Carry on!

**Comment by richardcalahan** [comment]
What was the session issue? I'm experiencing this as well, and have tried clearing the session.

**Comment by timkelty** [comment]
@richardcalahan it was infrastructure related, not Craft/app.

In this case, there were multiple docker redis containers running, causing it to function as a load balancer, inadvertently spreading session data between them.

I've also seen this happen, if you don't have a centralized session store (eg redis), and the environment changes from something with 1 container to multiple. This can happen very easily on Heroku, eg.
