### ISSUE TITLE
Setting up Craft 3.6.5.1 with MYSQL version 5.7.29 (WITH SSL)

### ISSUE THREAD

**Issue by deepakwipfli** [craftcms/cms#7583]
### Description
I'm trying to install craft CMS with MYSQL but it fails with the following error

 failed: SQLSTATE[HY000] [9002] SSL connection is required. Please specify SSL options and retry.

### Steps to reproduce

1. Run "composer create-project craftcms/craft C:\wamp64\www\yourfolder"
2. Run command "php craft setup"

### Additional info

- Craft version: 3.6.5.1
- PHP version: 7.3
- Database driver & version: MySql

**Comment by angrybrad** [comment]
WAMP requires SSL to connect to the database?

Is there a way to disable that? I tried some quick Google searches with no luck and [their documentation is lacking](https://www.wampserver.com/en/).

If you can't disable it, then you'll have to generate SSL keys and certs, the use Craft's database [attributes](https://craftcms.com/docs/3.x/config/db-settings.html#attributes) config setting and pass in the paths to those files in order for Craft to connect over SSL.

But I'd try to find a way to disable database connections in WAMP first.

**Comment by deepakwipfli** [comment]
WAMP doesn't need SSL to connect to the database. Also this question is not regarding WAMP.

I'm using Azure database for MYSQL which will be used with Craft CMS. Azure database for MYSQL by default comes with SSL enabled. I can disable it but It's not recommended. 


So question is, How do I set up Craft with MYSQL where MYSQL has SSL.

**Comment by angrybrad** [comment]
Never tried it on Azure, but should be same basic steps, then.

> If you can't disable it, then you'll have to generate SSL keys and certs, the use Craft's database [attributes](https://craftcms.com/docs/3.x/config/db-settings.html#attributes) config setting and pass in the paths to those files in order for Craft to connect over SSL.

Looks like they might provide a key to use: https://docs.microsoft.com/en-us/azure/mysql/connect-php#step-1-connect-to-the-server

**Comment by deepakwipfli** [comment]
Thanks for you help Brad. I was to install craft successfully after I added the below line in dbConfig.php

public $attributes = [
             PDO::MYSQL_ATTR_SSL_CA     => 'C:\wamp64\www\vera\arrest-trends-craft\certs\BaltimoreCyberTrustRoot.crt.pem',
         ];
