### ISSUE TITLE
“Login Required” error when accessing GraphQL via custom route

### ISSUE THREAD

**Issue by joshuabaker** [craftcms/cms#7587]
### Description

I’m getting a “Login Required” exception when trying to access the `graphql/api` action from a custom route (defined in `routes.php`). Accessing the action directly via `/actions/graphql/api` works as expected.

#### routes.php

```php
<?php

return [
    "api/graphql" => "graphql/api",
];
```

#### GraphQL query

```gql
{ ping }
```

I’ve tested this in Insomnia with a few variations (e.g. different paths, queries, CSRF settings, headless mode on/off).

### Additional info

- Craft version: 3.6.6
- PHP version: 7.4.12

**Comment by brandonkelly** [comment]
All routes are custom; there’s no special case for `api`; that’s just a suggestion.

I just tested with `api/graphql` locally and it works fine:

<img width="1057" alt="Screenshot of my config/routes.php file showing that my GraphQL route is set to “api/graphql”, and that Paw (macOS app) is able to send a “ping” GraphQL query to it." src="https://user-images.githubusercontent.com/47792/108273294-3367c000-7128-11eb-9c84-33f283249bc7.png">

Make sure that you are sending your GraphQL request with a valid token, or that your public schema is enabled.

**Comment by brandonkelly** [comment]
Just saw #7586. Note that you pass the token via the `Authorization` header, **not** the `X-Craft-Token` query string param. See the schema settings – they demonstrate exactly how it should be sent.

**Comment by joshuabaker** [comment]
@brandonkelly I found the issue.

```php
define("CRAFT_CP", true);
```

It looks like setting `CRAFT_CP` complete disables `routes.php`, which I suspect is by design.

The desired outcome was to use the root path for CP requests and anything `/api` for any actions or controllers.

The config below doesn’t work without the `CRAFT_CP` constant though.

```php
"baseCpUrl" => getenv("BASE_API_URL"),
"cpTrigger" => null,
```

In [the docs](https://github.com/craftcms/cms/blob/df6f98e63e91b4c4389a89b89aea55e240b8f7fe/src/config/GeneralConfig.php#L397-L398) it looks like this should be possible, but perhaps I’m mistaken.

**Comment by brandonkelly** [comment]
Yeah if you set `CRAFT_CP` to `true`, you are explicitly telling Craft to treat the request as a control panel request, and CP requests don’t care about `config/routes.php`.

You’d have to just set that conditionally based on the incoming request URI.

```php
if (strpos($_SERVER['REQUEST_URI'], '/api') !== 0) {
    define('CRAFT_CP', true);
}
```

**Comment by joshuabaker** [comment]
Thanks, @brandonkelly. That’s a handy snippet. 🙏🏻
