### ISSUE TITLE
email-type URL field not validating + CP input value gets "http://" prefix

### ISSUE THREAD

**Issue by olets** [craftcms/cms#7588]
### Description

Having trouble with an email URL field. When I put an email address in the field and save the entry,

- I get "Couldn't save entry" on the page and "My Email Field Name is not a valid URL." on the field
- `http://` has been added to the start of the field value

### Steps to reproduce

1. Create an email URL field
2. Add to a field layout
3. In an entry with the field, fill in an email address
4. Save

Don't remember but thought maybe I first saved it as a website URL field and that the change to email went badly. But looking at the fields table it looks reasonable: type `craft\fields\Url`, settings `{"maxLength":"255","placeholder":null,"types":["email"]}`.

Tried entering a website URL, and that does not validate either (good). The identical "not a valid URL" gives me the idea that a nice error upgrade would be to include the allowed types (e.g. "email", "email or website", etc).

### Additional info

- Craft version: 3.6.6
- PHP version: 7.4.14
- Database driver & version: MySQL 5.7.29
- Plugins & versions:
    ```
    Amazon S3 1.2.11
    Asset Rev 6.0.2
    Classnames  1.0.2
    Command Palette 3.1.4
    Redactor 2.8.5
    ```

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

Note that if you _only_ want to allow emails, you may be better served with the Email field type, rather than URL.
