### ISSUE TITLE
404 pages per section type

### ISSUE THREAD

**Issue by rauwebieten** [craftcms/cms#7592]
### Description

I'd like to have different 404 pages, per section type.
Is this possible in craftcms 3 ?

**Comment by brandonkelly** [comment]
If you get a 404 page, that means no entry was requested, which means Craft doesn’t know which section that missing entry would have been in. (Sections’ entry URI formats are not actually referenced as part of request routing. They are only used to generate entries’ URIs, when entries are saved, and those generated URIs are then stored in the `elements_sites` table.)

So your only option here would be to add your own logic to your 404 template which checks the requested path and includes the appropriate sub-template from there.

For example, here’s what your `404.twig` file could look like:

```twig
{% set path = craft.app.request.pathInfo %}

{% if path starts with 'news/' %}
    {% include '404-news' %}
{% elseif path starts with 'gallery/' %}
    {% include '404-about' %}
{% else %}
    {% include '404-default' %}
{% endif %}
```

Then create additional `404-xxxxxxxx.twig` templates for each of those section-specific 404 pages.
