### ISSUE TITLE
Exception 'yii\di\NotInstantiableException' with message 'Failed to instantiate component or class "modules\custommodule"

### ISSUE THREAD

**Issue by joepagan** [craftcms/cms#7593]
### Description

Just migrated an app from 3.0.41.1 -> 3.6.6 (what a journey), and, when I finally got to 3.6.6, running a final `./craft update all` command to update the following: 

```
- redactor 2.6.1 => 2.8.5
- super-table 2.5.4 => 2.6.7
```

I get an error out because of a custom module.

To clarify, I never hit this error once before in this update process, the last craft update jump I went from `craft 3.4.30 => 3.6.6`

I [notice you suggest to specifically add namespaces for modules now](https://craftcms.com/docs/3.x/extend/module-guide.html#set-up-class-autoloading), rather than at a the parent directory level which I think used to be recommended, not sure if that's the reason for my issue?

strangely, trying to view the website I then get. the same stack trace as the error output from the console command below, but, if I am to `composer install`, the website loads fine shortly after.

I also want to highlight that I had specifically tried to `./craft update super-table` and `./craft update redactor` separately and in either case I got the same behavior.

I hope you can help, let me know if you need anything else

composer.json:

```json
"autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  },
```

app.php:

```php
$app = [
    'modules' => [
        'site-module' => \modules\Module::class,
        'business-logic-module' => [
            'class' => \modules\businesslogicmodule\BusinessLogicModule::class
        ]
    ],
    'bootstrap' => ['business-logic-module', 'site-module']
];
```

`./craft update all` output:
```sh
Fetching available updates ... done
Performing 2 updates:

    - redactor 2.6.1 => 2.8.5
    - super-table 2.5.4 => 2.6.7

Backup the database? (yes|no) [no]:
Skipping database backup.
Performing update with Composer ... done
Applying new migrations ... error: The command "'/var/www/site/craft' 'migrate/all' '--no-backup' '--no-content'" failed.

Exit Code: 1(General error)

Working directory: /var/www/site

Output:
================


Error Output:
================
Exception 'yii\di\NotInstantiableException' with message 'Failed to instantiate component or class "modules\businesslogicmodule\BusinessLogicModule".'

in /var/www/site/vendor/yiisoft/yii2/di/Container.php:510

Caused by: Exception 'ReflectionException' with message 'Class modules\businesslogicmodule\BusinessLogicModule does not exist'

in /var/www/site/vendor/yiisoft/yii2/di/Container.php:508

Stack trace:
#0 /var/www/site/vendor/yiisoft/yii2/di/Container.php(508): ReflectionClass->__construct('modules\\busines...')
#1 /var/www/site/vendor/yiisoft/yii2/di/Container.php(386): yii\di\Container->getDependencies('modules\\busines...')
#2 /var/www/site/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('modules\\busines...', Array, Array)
#3 /var/www/site/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('modules\\busines...', Array, Array)
#4 /var/www/site/vendor/yiisoft/yii2/base/Module.php(427): yii\BaseYii::createObject(Array, Array)
#5 /var/www/site/vendor/yiisoft/yii2/base/Application.php(321): yii\base\Module->getModule('business-logic-...')
#6 /var/www/site/vendor/craftcms/cms/src/console/Application.php(61): yii\base\Application->bootstrap()
#7 /var/www/site/vendor/yiisoft/yii2/base/Application.php(279): craft\console\Application->bootstrap()
#8 /var/www/site/vendor/yiisoft/yii2/console/Application.php(125): yii\base\Application->init()
#9 /var/www/site/vendor/craftcms/cms/src/console/Application.php(47): yii\console\Application->init()
#10 /var/www/site/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
#11 /var/www/site/vendor/yiisoft/yii2/base/Application.php(212): yii\base\BaseObject->__construct(Array)
#12 /var/www/site/vendor/yiisoft/yii2/console/Application.php(90): yii\base\Application->__construct(Array)
#13 [internal function]: yii\console\Application->__construct(Array)
#14 /var/www/site/vendor/yiisoft/yii2/di/Container.php(420): ReflectionClass->newInstanceArgs(Array)
#15 /var/www/site/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('craft\\console\\A...', Array, Array)
#16 /var/www/site/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\console\\A...', Array, Array)
#17 /var/www/site/vendor/craftcms/cms/bootstrap/bootstrap.php(246): yii\BaseYii::createObject(Array)
#18 /var/www/site/vendor/craftcms/cms/bootstrap/console.php(51): require('/var/www/site/v...')
#19 /var/www/site/craft(21): require('/var/www/site/v...')
#20 {main}


Output:




```

### Steps to reproduce

1. setup custom module on craft 3.6.6
2. use namespace technique for only targeting `modules` dir
3. try update all craft plugins to latest via craft cli
4. get console error
5. view website see error with stack trace
6. composer install again
7. website loads ok

### Additional info

- Craft version: 3.6.6
- PHP version: 7.2.21
- Database driver & version: mariadb:10.2.31
- Plugins & versions: 
```
"nystudio107/craft-seomatic": "3.3.32",
    "nystudio107/craft-minify": "1.2.10",
    "doublesecretagency/craft-cpcss": "2.3.0",
    "doublesecretagency/craft-cpjs": "2.3.0",
    "verbb/super-table": "2.6.7",
    "craftcms/fix-fks": "1.0.2.1",
    "fruitstudios/linkit": "1.1.12.1",
    "craftcms/contact-form": "2.2.7",
    "dukt/twitter": "2.1.4",
    "verbb/navigation": "1.4.13",
    "verbb/expanded-singles": "1.1.3",
    "matt-west/craft-recaptcha": "^1.3",
    "yiisoft/yii2-redis": "^2.0",
    "thoughtfulweb/lite-speed-cache": "1.2.7",
    "nystudio107/craft-retour": "3.1.46",
    "topshelfcraft/wordsmith": "3.3.0.1",
    "scaramangagency/craftagram": "^1.4"
```

**Comment by brandonkelly** [comment]
Where exactly does BusinessLogicModule.php live?

**Comment by joepagan** [comment]
`./modules/businesslogicmodule/src/BusinessLogicModule.php`

**Comment by brandonkelly** [comment]
In that case, your `autoload` setting in `composer.json` should be set to:

```
"autoload": {
  "psr-4": {
    "modules\\businesslogicmodule\\": "modules/businesslogicmodule/src/"
  }
},
```

If this was working before, it was only thanks to the fact that Composer 1 was pretty lenient about class locations / filename casing, and Composer 2 is strict about things being located where they’re supposed to be.

**Comment by joepagan** [comment]
Ah, thanks for taking a look and point this out, I’ll update that.

I am still using composer 1 in my php container so not sure why it would start complaining now.

**Comment by brandonkelly** [comment]
Craft 3.6 bundles Composer 2, which is used if you ever update Craft or a plugin from the Updates utility in the control panel, or if you use the `craft update` terminal command.

Composer 1 was equally strict if you weren’t using an [optimized autoloader](https://getcomposer.org/doc/articles/autoloader-optimization.md). So you could also run into the same issue if you ran `composer update` without the `-o` or `-a` flag, and your composer.json file didn’t have `"optimize-autoloader": true`.

**Comment by joepagan** [comment]
Ah that explains that! Yes my composer.json did have that setting.

Thanks
