### ISSUE TITLE
guzzle.php doesn't override User-Agent value for Craft::createGuzzleClient()

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/cms#7597]
### Description

The User-Agent value set in `config/guzzle.php` doesn't appear to be set when the array replace occurs. From a test by dumping out what $guzzleConfig is before and after the replace, I can see that the config options in the guzzle.php are present and have been obtained by the `getConfigFromFile()`, but once the array replace happens the User-Agent value is lost. Other properties like `debug` do appear to be merged however.

Am I doing something wrong?

guzzle.php:

```php
<?php

use craft\helpers\App;

return [
	'*' => [
		'debug' => filter_var(App::env('GUZZLE_DEBUG'), FILTER_VALIDATE_BOOLEAN),
		// Set our custom User-Agent value across all Guzzle requests.
		'headers' => [
			'User-Agent' => 'Cool User-Agent Bro',
		],
		// If HTTP_PROXY is set, apply it to Guzzle requests
		'proxy' => App::env('HTTP_PROXY') ?: null
	]
];
```

Line 347: Values obtained from getConfigFromFile()
Line 352: Dumping the contents of guzzleConfig after the merge

Then in a debug.php for testing, dump out a `Craft::createGuzzleClient()` request to see the values.

```php
/app/vendor/craftcms/cms/src/Craft.php:347:
array (size=3)
  'debug' => boolean true
  'headers' => 
    array (size=1)
      'User-Agent' => string 'Cool User-Agent Bro' (length=19)
  'proxy' => null
/app/vendor/craftcms/cms/src/Craft.php:352:
array (size=3)
  'debug' => boolean true
  'headers' => 
    array (size=1)
      'User-Agent' => string 'Craft/3.6.6 GuzzleHttp/6.5.5 curl/7.74.0 PHP/7.4.15' (length=51)
  'proxy' => null
/app/web/debug.php:44:
object(GuzzleHttp\Client)[2680]
  private 'config' => 
    array (size=10)
      'debug' => boolean true
      'headers' => 
        array (size=1)
          'User-Agent' => string 'Craft/3.6.6 GuzzleHttp/6.5.5 curl/7.74.0 PHP/7.4.15' (length=51)
      'proxy' => null
      'handler' => 
        object(GuzzleHttp\HandlerStack)[2681]
          private 'handler' => 
            object(Closure)[2688]
              ...
          private 'stack' => 
            array (size=4)
              ...
          private 'cached' => null
      'allow_redirects' => 
        array (size=5)
          'max' => int 5
          'protocols' => 
            array (size=2)
              ...
          'strict' => boolean false
          'referer' => boolean false
          'track_redirects' => boolean false
      'http_errors' => boolean true
      'decode_content' => boolean true
      'verify' => boolean true
      'cookies' => boolean false
      'idn_conversion' => boolean true
```

### Steps to reproduce

1. Create a config/guzzle.php with some options
2. Dump a Guzzle client from `Craft::createGuzzleClient()`
3. See the User-Agent is the default and not the one set in the config/guzzle.php

### Additional info

- Craft version: 3.6.6
- PHP version: 7.4
- Database driver & version: MySQL 8

**Comment by jamesmacwhite** [comment]
Looking at the PHP docs for: https://www.php.net/manual/en/function.array-replace-recursive.php

I think the issue might be:

> array_replace_recursive() replaces the values of array with the same values from all the following arrays. **If a key from the first array exists in the second array, its value will be replaced by the value from the second array**. If the key exists in the second array, and not the first, it will be created in the first array. If a key only exists in the first array, it will be left as is. If several arrays are passed for replacement, they will be processed in order, the later array overwriting the previous values.

So in order for User-Agent to be able to be overridden, the array values need to switched in `array_replace_recursive()` I believe.

**Comment by brandonkelly** [comment]
Just fixed this for the next release. Thanks for reporting!

**Comment by jamesmacwhite** [comment]
Thank you!

**Comment by brandonkelly** [comment]
Craft 3.6.7 is out now with that fix.
