### ISSUE TITLE
Duplicate entry '3216-10' for key 'revisions_sourceId_num_unq_idx'

### ISSUE THREAD

**Issue by truszko1** [craftcms/cms#7598]
### Description
We are encountering an integrity constraint violation when saving Entries. If the same entry is being saved by two users simultaneously, one of them will be shown a SQL error

```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3216-10' for key 'revisions_sourceId_num_unq_idx'
The SQL being executed was: INSERT INTO `revisions` (`sourceId`, `creatorId`, `num`, `notes`) VALUES (3216, 49, 10, '')
```

The exception is being thrown by ` in /var/www/vendor/craftcms/cms/src/services/Revisions.php at line 142– craft\helpers\Db::insert()` when the Revisions class is attempting to insert a revision.

Is this an expected behavior? This seems new with Craft 3.6. We could probably "fix" this error by removing the index, but surely the index was added intentionally to protect against _something_.

I don't see how this might be specific to our instance configuration, but maybe? I'd appreciate some feedback.

Thanks!

### Steps to reproduce

1. Open an existing entry in two tabs.
2. Click save in tab 1.
3. Quickly switch to tab 2 and also click save.
4. Tab 2 will see the exception.

### Additional info

- Craft version: 3.6.6
- PHP version: 7.4.2
- Database driver & version: MySQL 5.5.5
- Plugins & versions: N/A

**Comment by samhibberd** [comment]
We are also running into this integrity constraint violation when a resave task is being run in the queue. Has it been establish as a bug? Anything we can provide to help debug?

**Comment by brandonkelly** [comment]
Sorry, I missed the original post.

This shouldn’t be possible as `craft\services\Revisions::createRevision()` will create a mutex lock for the source entry before it goes on to determine a unique revision number:

https://github.com/craftcms/cms/blob/669dc0fddd0e258a3a11e42d4b39dc2053531da9/src/services/Revisions.php#L75-L79

Have either of you overridden the `mutex` component in `config/app.php`?

**Comment by samhibberd** [comment]
@brandonkelly not here no.

**Comment by brandonkelly** [comment]
Going to close this… @truszko1 Let me know if you’re still having issues on 3.6.10+.

**Comment by engram-design** [comment]
I'm seeing this behaviour on a 3.6.12 install. Anything I can do to help troubleshooting?

**Comment by brandonkelly** [comment]
@engram-design Can you provide steps to reproduce, starting with a fresh Craft install?

**Comment by engram-design** [comment]
@brandonkelly Damn, it's gonna be one of **those** issues. I couldn't replicate it locally, and now on the server it's no longer doing it. I was also using the [sitecopy plugin](https://github.com/Goldinteractive/craft3-sitecopy), and when disabling that, it seemed to save.

I'll keep an eye on it, but it seems environmental.
