### ISSUE TITLE
Temperamental front end email verification

### ISSUE THREAD

**Issue by jlaughton87** [craftcms/cms#7600]
### Description
This issue is only affecting a small percentage of users and i cannot replicate it. We have had feedback from a client that some of their users are not able to login after registering and clicking the verification link emailed to them. Feedback such as:

"I have set up account with my NHS email and created a password. My email has been verified but when I try to log in it is telling me it has not been verified.

I have tried several times without luck."
and 

"Hi there, I have registered for an account and have clicked the link to verify my email address but when I try to log in I keep getting an error saying my email address hasn’t been verified. "

Unfortunately this is all i have to go on.

The registration forms are all front end using headless cms and axios to call the site modules

In the cms i can see that the user has been created but there is no last logged in date.

Any help on this would be greatly appreciated

### Steps to reproduce

1.Register through the front end of the website
2.Click the verification email link
3. Try to log in

### Additional info

- Craft version: Craft CMS 3.5.17.1
- PHP version:7.2.24
- Database driver & version:MySQL 5.7.33
- Plugins & versions:
Bulk Edit	2.0.5
CP Field Inspect	1.2.3
Feed Me	4.3.4
Google Cloud Storage	1.4.0
Imager X	v3.2.6
Mailgun	1.4.3
Notifications	1.1.3
Redactor	2.8.5
Redirect Manager	1.1.1
Sentry	1.5.1
SEOmatic	3.3.29
Sprout Forms	3.13.1
Super Table	2.6.5

**Comment by brandonkelly** [comment]
Someone wrote into support recently and pointed out that their verification emails weren’t getting links at all. The culprit ended up being the `<` and `>` characters that Craft’s default email bodies wrap around URLs (e.g. `<{{link}}>`). We put those in there because they are required to get the Markdown parser to recognize the URLs and covert them to `<a>` tags. However it turns out that if the user prefers plain text email, Gmail was stripping the URLs out entirely because it confused the `<URL>`s fro HTML tags.

I wonder if maybe that’s the case here as well? Can you confirm with someone who is experiencing this whether their verification emails actually contain links?

If it’s the same issue, it’s been fixed for the next release (7dd108cda4984ab74e9ea1b20824158baaa466d2).

**Comment by jlaughton87** [comment]
Thanks for the quick response!

It would be great is that was the case, unfortunately not. Users who are experiencing the issue:

- Sign up on the front end
- Receive a verification email
- Click the link
- Are directed to the login page
- Submit credentials 
- Are told that either their username or password is wrong. 

It's like the password they input on registration isn't persisting past email verification, not that i can think why/how that would be a thing. Also it's only happening to about 20% of people who sign up.

**Comment by angrybrad** [comment]
@jlaughton87 for one of the accounts experiencing this, can you check the `passwords` column in the `users` table in the database and see if it has a hash stored for that user?

**Comment by jlaughton87** [comment]
Attached is the user data of a couple of users i know to be affected (i've taken out any identifying data), they currently cannot log in. 

Just fyi, to reset their password manually i sometimes have to set their user permissions as admin, change the password in the cms then change the permissions back. Otherwise i get stuck in the same loop they do (as described earlier).

[db extract.pdf](https://github.com/craftcms/cms/files/6038749/db.extract.pdf)

**Comment by angrybrad** [comment]
@jlaughton87 Is it a single database, or do you have database read/write splitting setup?

**Comment by jlaughton87** [comment]
Apologies for the delay on this, working on it in spare time.

It's a single database the site is using custom front end login forms. Pretty sure i have found what must be causing the issue. In the user login component we have: 

`if (!$user->lastLoginDate) {
     Craft::$app->users->sendActivationEmail($user);
    throw new ApiException(ApiException::ERROR_101, ['password' => 'auth.login.verifyError']);
}`

I inherited this site from the old dev without much of a handover so i have no idea why we would be cancelling login if the user hasn't logged in before... Out of interest can you think of any reason? 

Cheers,
Jamie

**Comment by brandonkelly** [comment]
@jlaughton87 Glad you got to the bottom of it! They may have done that as a way of having control over when newly-added users were allowed to start accessing their accounts.

I haven’t seen that specific approach to the problem, but it has been requested before. We addressed it in Craft 3.5 with a new “Suspend by default” user setting (see #5830).
