### ISSUE TITLE
Replace file button is missing

### ISSUE THREAD

**Issue by bitboxfw** [craftcms/cms#7601]
### Description
If a user does not have the "Remove files and folders" permissions on a volume, the "Replace file" button does not appear on a file's details page, even if the user has the permissions to replace a file. The problem exists only on the detail page of a file, in the list view he can replace files.

### Steps to reproduce

1. Create a user and give all rights to the volume, except the rights for "Remove files and folders"
2. Try to replace a file on the detail page of the file

### Additional info

- Craft version: 3.5.17.1
- PHP version: 7.4.13
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
CP Clear Cache	1.0.7
Dumper	2.0.0
Error Notifier	1.0.4
Logs	3.0.3
MatrixMate	1.2.7
Minifier	2.0.5
Redactor	2.8.5
Redactor Anchors	1.1.0
Smith	1.1.10
XML Sitemap	1.3.1

**Comment by brandonkelly** [comment]
Whoops, we were checking the wrong permission when determining whether to show the button. Just fixed for the next release. Thanks for reporting!

**Comment by brandonkelly** [comment]
Craft 3.6.7 is out now with that fix.
