### ISSUE TITLE
"You’re now editing a draft." not published in german language version

### ISSUE THREAD

**Issue by ballmannweber** [craftcms/cms#7602]
if a draft is autosaved the upcoming dialog/note is still in english even if the german language version is selected as primary language in the cp:

![Bildschirmfoto 2021-02-22 um 16 08 37](https://user-images.githubusercontent.com/5177628/108727103-79f25b80-7528-11eb-8065-8499220c5a01.png)

**Comment by brandonkelly** [comment]
It’s been translated for the next release, due out tomorrow (5ec5599a7638a27c0c520aa096a7f0dce9d8abd5).
