### ISSUE TITLE
show a folder contents even if files are only present in subfolders

### ISSUE THREAD

**Issue by ballmannweber** [craftcms/cms#7603]
At the moment, in "Files" folders that contain only subfolders but not files directly are shown as empty. It would be better to show directly the files displayed in the subfolders, so that a click on the main folder shows all files of this directory including the files in the subfolders. The search also works (optionally) across all folder levels.

**Comment by mmikkel** [comment]
I agree that these folders showing *nothing* is annoying, but I think I think the most effective (and least confusing) solution would be if sub folders actually appeared in the main view alongside any assets contained in whatever folder you're looking at – just like how Finder/Explorer displays files and folders on macOS/Windows.

**Comment by brandonkelly** [comment]
Agree with @mmikkel – and that’s something we’re planning to do in Craft 4 – #979.
