### ISSUE TITLE
Graphql mutation 'deleteEntry' returns true but doesn't delete entry multisite

### ISSUE THREAD

**Issue by jlaughton87** [craftcms/cms#7611]
### Description
I have 3 sites in my headless cms, if i run a 'deleteEntry' mutation on an entry in the 'default' site the api returns true and the entry is deleted. If i try with either of the other sites the api returns true but the entry is not deleted.
### Steps to reproduce

1. Within the Craft CMS GraphQl explorer call:
```
mutation deleteUserProject{
    deleteEntry(
      id: [entry id here]
    )
  }
```
for an entry in any site other than the default site.

2. Returns true but entry is not deleted

### Additional info

Craft version: Craft CMS 3.5.17.1
PHP version: 7.2.24
Database driver & version: MySQL 5.7.33

**Comment by jlaughton87** [comment]
@andris-sevcenko, any progression on this?

**Comment by andris-sevcenko** [comment]
Found the bug, fixed it, and pushed for the next Craft release. You'll have to specify the `siteId` argument for non-primary sites.

Also, since you're still running Craft 3.5, you'll have to update to Craft 3.6 in the process.

**Comment by brandonkelly** [comment]
Craft 3.6.8 is out now with this fix. Thanks for reporting, @jlaughton87!
