### ISSUE TITLE
Behaviors are missing from User

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#7613]
### Description
I wish I knew why, but we're running into a strange issue. We have a controller that saves items to a relationship field. The basic functionality is this:

```php
$user = Craft::$app->getUser()->getIdentity();
$user->setFieldValue('myList', $entries);
Craft::$app->getElements()->saveElement($user, true, false);
``` 

All works well, especially Locally. However, for some magical reason, when we run the same code on production or acc, some behaviors are attached to the User are missing, only crafts own CustomFieldBehavior is attached. This causes a problem in storing the user, because later in the execution trough an event a method is called that no longer exists.

I tried calling `ensureBehaviour`, but it will ever actually call ->behaviours() in this case, because the CustomFieldBehavior is pre-regisered I believe.

I have no idea where to look next, we "solved it" by adding the following lines:
```php
 foreach($user->behaviors() as $k => $behavior) {
        $user->attachBehavior($k, $behavior);
    }
```

Before saving, but of course, that's not the solution. What could cause the behaviors to behave so badly? 

### Additional info
Attached behavior like:
```php
      Event::on(
            User::class,
            User::EVENT_DEFINE_BEHAVIORS,
            static function(DefineBehaviorsEvent $event) {
                $event->behaviors['userBehaviour'] = UserBehaviour::class;
            });
    }
```

Registered route like:
```php
    Event::on(
            UrlManager::class,
            UrlManager::EVENT_REGISTER_SITE_URL_RULES,
            function (RegisterUrlRulesEvent $event) {
  
                $event->rules['api/user/list/add/<entryId>'] = 'site-module/user/list-add';
            }
        );
```
### Additional info

- Craft version: 3.6.7
- PHP version: 7.4.X

**Comment by brandonkelly** [comment]
Where does your `EVENT_DEFINE_BEHAVIORS` code live? Most likely something is fetching the user before that code is getting executed, so the behaviors have already been defined.

**Comment by lenvanessen** [comment]
@brandonkelly in the modules init() function

**Comment by brandonkelly** [comment]
Any code before it that could load the current user? Is your module ID listed in the `bootstrap` array in `config/app.php`?

**Comment by lenvanessen** [comment]
Module is in bootstrap, i'll cehck if there is any other code that could load the user.

**Comment by lenvanessen** [comment]
@brandonkelly it was due to Blitz;)
