### ISSUE TITLE
[ Class name must be a valid object or a string ] while installing a local plugin in craft cms

### ISSUE THREAD

**Issue by AmandeepSingh2048** [craftcms/cms#7621]
### Description
```
Error: Class name must be a valid object or a string in C:\xampp\htdocs\craft\vendor\craftcms\cms\src\services\Plugins.php:494
Stack trace:
#0 C:\xampp\htdocs\craft\vendor\craftcms\cms\src\controllers\PluginsController.php(49): craft\services\Plugins->installPlugin('temp-p', NULL)
#1 [internal function]: craft\controllers\PluginsController->actionInstallPlugin()
#2 C:\xampp\htdocs\craft\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\craft\vendor\yiisoft\yii2\base\Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\craft\vendor\craftcms\cms\src\web\Controller.php(190): yii\base\Controller->runAction('install-plugin', Array)
#5 C:\xampp\htdocs\craft\vendor\yiisoft\yii2\base\Module.php(534): craft\web\Controller->runAction('install-plugin', Array)
#6 C:\xampp\htdocs\craft\vendor\craftcms\cms\src\web\Application.php(274): yii\base\Module->runAction('plugins/install...', Array)
#7 C:\xampp\htdocs\craft\vendor\craftcms\cms\src\web\Application.php(577): craft\web\Application->runAction('plugins/install...', Array)
#8 C:\xampp\htdocs\craft\vendor\craftcms\cms\src\web\Application.php(253): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#9 C:\xampp\htdocs\craft\vendor\yiisoft\yii2\base\Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 C:\xampp\htdocs\craft\index.php(22): yii\base\Application->run()
#11 {main}
```

I created a plugin with pluginfactory.io 
My plugin is visible in craft cms plugin plage but when i am trying to install the plugin i am getting this error
Any help would be appreciated
### Additional info

PHP version | 7.4.13
-- | --
WINNT 10.0
MySQL 5.5.5
GD 7.4.13
Craft Solo 3.6.7
2.0.40
v2.14.3
7.2.0

**Comment by brandonkelly** [comment]
Looks like the only way that could happen is if your plugin class doesn’t extend `craft\base\Plugin`. Make sure that’s the case.

If you need additional help, please send your plugin source files over to support@craftcms.com.

**Comment by AmandeepSingh2048** [comment]
I tried this and few other solutions but nothing seems to work. I have sent the source code to support@craftcms.com
Thankyou

**Comment by AntoineMaillard06** [comment]
I have the same issue here, @AmandeepSingh2048 were you able to fix it ?

**Comment by malikhamari** [comment]
Facing same issue, if find any lead, please put it in this thread, thanks

**Comment by brianjhanson** [comment]
This is usually some kind of misconfiguration issue. If you're running into it, make sure you've followed all the steps [for loading your local plugin in the documentation](https://craftcms.com/docs/4.x/extend/plugin-guide.html#loading-your-plugin-into-a-craft-project) and are extending the base plugin class as Brandon.
