### ISSUE TITLE
Assetbundle timestamps gone?

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#7622]
### Description
I noticed that, I think since 3.6, the assetbundles nor cpresources are getting timestamped. Is this on purpose or did something change?

Example url now `https://white.nl/en/cpresources/654bcd49/ccc.js` vs then `https://white.nl/en/cpresources/654bcd49/ccc.js?v=1613655793`

### Additional info

- Craft version: 3.6.7
- PHP version: 7.4.10
- Database driver & version: MySQL 5.7

**Comment by brandonkelly** [comment]
Yeah you’re right. Looks like this is a Yii bug. I just reported it here: https://github.com/yiisoft/yii2/issues/18529

Will update this as I find out more.

**Comment by brandonkelly** [comment]
The Yii team has fixed the bug for the next release, which should be any day now.

**Comment by brandonkelly** [comment]
Yii 2.0.41 was just released, and I’ve merged it in for the next Craft release. Verified that the asset timestamps are back now 🎉
