### ISSUE TITLE
Publish as focus – rather than draft

### ISSUE THREAD

**Issue by alexanderloewe** [craftcms/cms#7623]
### Description
I would find it much more intuitive if new pages were primarily published rather than have the draft being in the focus. 

It was like this for about "6 Craft years" why changing it now?

From
<img width="450" alt="Bildschirmfoto 2021-02-25 um 18 53 43" src="https://user-images.githubusercontent.com/69263307/109195587-fee4ab80-779a-11eb-9b52-351a19efdccf.png">

To
<img width="470" alt="Bildschirmfoto 2021-02-25 um 18 54 18" src="https://user-images.githubusercontent.com/69263307/109195592-0015d880-779b-11eb-8f83-20a64fbbb377.png">

**Comment by brandonkelly** [comment]
We’re going to make this change in 3.7 – see https://github.com/craftcms/cms/issues/6681#issuecomment-782432064.
