### ISSUE TITLE
Remove Flash from Allowed File Types (Restrictions)

### ISSUE THREAD

**Issue by remcoov** [craftcms/cms#7626]
### Description
Since Flash support has ended in 2020, it seems logical to remove this _allowed file type_ from Asset fields.

See: https://www.adobe.com/nl/products/flashplayer/end-of-life.html

### Steps to reproduce

1. Create Asset field
2. Scrolll to "Restrict allowed file types"
<img width="247" alt="flash-lol" src="https://user-images.githubusercontent.com/48018834/109281351-7c9ccb80-781c-11eb-9748-92d79de35ae9.png">

**Comment by brandonkelly** [comment]
Yep, good call. Removed for 3.7.
