### ISSUE TITLE
Error messages difficult to see when testing site trial licenses.

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#7627]
I kept missing this error message, as it wasn't standing out to me.

![Screen Shot 2021-02-26 at 10 52 46 AM](https://user-images.githubusercontent.com/1007191/109342657-064e9800-7821-11eb-9954-0bc1f5b028f4.png)

**Comment by jsunsawyer** [comment]
Sorry, just found a related issue: #7142

Closing.

**Comment by brandonkelly** [comment]
This has been resolved for the next release.

**Comment by brandonkelly** [comment]
Craft 3.6.13 is out now.
