### ISSUE TITLE
Random server errors in dashboard

### ISSUE THREAD

**Issue by Stefenyo** [craftcms/cms#7628]
### Description
I'm developing a site locally using MAMP and from time to time as I am interacting with the dashboard I get a server popping up. I'm also not able to download a back up of DB from database. any reason as to why this could be happening ?

(all requirements in system report are checked off)

### Steps to reproduce

1.
2.

### Additional info

- Craft version: 3.6.7
- PHP version: 7.4.9
- Database driver & version: MySQL 5.7.30
- Plugins & versions:

**Comment by brandonkelly** [comment]
Next time you see it, open up your `storage/logs/web.log` file and search for `[error]`. Then please post the full error report, including the stack trace that follows it.
