### ISSUE TITLE
ProjectConfig stores field settings that throw an error when loaded

### ISSUE THREAD

**Issue by sebastian-lenz** [craftcms/cms#7630]
### Description

Due to how project configuration stores associative arrays, Craft can create field configuration files that cannot be loaded and throw an exception due to a PHP notice when trying to do so.

### Steps to reproduce

The following sample code shows the problem and triggers a PHP notice. When the code is run while saving a field, an exception is thrown due to the PHP notice.

```php
use \craft\helpers\ProjectConfig;
$config = [
  'mySettings' => [
    'myValues' => [],
  ],
];

$packed = ProjectConfig::packAssociativeArrays($config);
// Array is correctly packed:
// [ 'mySettings' => [
//   '__assoc__' => [ ['myValues', []] ],
// ]]

$cleaned = ProjectConfig::cleanupConfig($packed);
// Packed array value is removed
// [ 'mySettings' => [
//   '__assoc__' => [ ['myValues'] ],
// ]]

$restored = ProjectConfig::unpackAssociativeArrays($cleaned);
// PHP notice is triggered:
// Notice: Undefined offset: 1 in /vendor/craftcms/cms/src/helpers/ProjectConfig.php on line 328
```

### Additional info

- Craft version: Craft Pro 3.6.7
- PHP version: 7.4.15
- Database driver & version: MySQL 5.7.32
- Related: #5525

### Details

The test case reassembled what happens while a custom field is saved in [\craft\services\Fields::saveField](https://github.com/craftcms/cms/blob/e18321039c1a20529d4b80db0d3adb0dd339bf88/src/services/Fields.php#L782):
- On line 804 `$this->createFieldConfig()` is called which fetches the field settings and passes them to `ProjectConfig::packAssociativeArrays`.
- On line 809 `Craft::$app->getProjectConfig()->set()` is called which passes the settings to `ProjectConfig::cleanupConfig`.

There seem to be multiple breaking points here all playing together:
- `ProjectConfig::cleanupConfig` seems to be the culprit as it [removes empty values](https://github.com/craftcms/cms/blob/e18321039c1a20529d4b80db0d3adb0dd339bf88/src/helpers/ProjectConfig.php#L196) and therefore removes the empty packed array value.
- `ProjectConfig::unpackAssociativeArray` completely relies on the value passed in to be [an array with two members](https://github.com/craftcms/cms/blob/e18321039c1a20529d4b80db0d3adb0dd339bf88/src/helpers/ProjectConfig.php#L324). There is no check of whether this assumption is true. The missing value at index 1 triggers a notice when it has been removed by `ProjectConfig::cleanupConfig`.
- `Fields::saveField()` raises an exception when encountering PHP notices.

### Fix

The easiest solutions seems to be to check whether the unpacked value actually carries the second array member. When PHP notices are ignored, the method actually returns `NULL` in those cases, so maybe we can simply ensure that no notice is triggered?

in [helpers/ProjectConfig.php, line 322](https://github.com/craftcms/cms/blob/e18321039c1a20529d4b80db0d3adb0dd339bf88/src/helpers/ProjectConfig.php#L322)
```php
if (!empty($array[ProjectConfigService::CONFIG_ASSOC_KEY])) {
  foreach ($array[ProjectConfigService::CONFIG_ASSOC_KEY] as $items) {
    $associative[$items[0]] = isset($items[1]) ? $items[1] : null;
  }
}
```

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by sebastian-lenz** [comment]
Wow, that was fast. Thanks for looking into it!

**Comment by brandonkelly** [comment]
Craft 3.6.8 is out now with the fix. Thanks again for reporting!
