### ISSUE TITLE
Windows: CLI command 'craft update' fails to run migrations if craft.bat is missing

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#7644]
### Description

See screenshot below. Looks like since `craft.bat` is missing from the default project, subsequent craft commands fail on Windows.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/60010597/109941932-f1b44900-7cd3-11eb-84f9-c1c30f050d79.png)

('... ist entweder ...' translates to 'is either misspelled or could not be found.')
### Additional info

- Craft version:
- PHP version: 7.4.7
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting that. It should be fixed now for the next release.

**Comment by brandonkelly** [comment]
Craft 3.6.9 is out now with this fix.
