### ISSUE TITLE
"Unable to write new project config files" upgrading from 3.6.6 to 3.6.8

### ISSUE THREAD

**Issue by nickdunn** [craftcms/cms#7645]
I'm running 3.6.6 and have tried the upgrade to 3.6.8. I have run twice and both times I get a fatal error:

> Unable to write new project config files

    Response: {"name":"Exception","message":"Unable to write new project config files","code":0,"type":"yii\\base\\Exception","file":"/var/www/craft/vendor/craftcms/cms/src/services/ProjectConfig.php","line":1732,"stack-trace":["#0 /var/www/craft/vendor/craftcms/cms/src/services/ProjectConfig.php(834): craft\\services\\ProjectConfig->_updateYamlFiles()","#1 /var/www/craft/vendor/craftcms/cms/src/services/ProjectConfig.php(389): craft\\services\\ProjectConfig->saveModifiedConfigData()","#2 [internal function]: craft\\services\\ProjectConfig->craft\\services\\{closure}(Object(yii\\base\\Event))","#3 /var/www/craft/vendor/yiisoft/yii2/base/Component.php(628): call_user_func(Object(Closure), Object(yii\\base\\Event))","#4 /var/www/craft/vendor/yiisoft/yii2/base/Application.php(395): yii\\base\\Component->trigger('afterRequest')","#5 /var/www/craft/web/index.php(22): yii\\base\\Application->run()","#6 {main}"],"previous":{"name":"Exception","message":"Only variables can be passed by reference","code":0,"type":"Error","file":"/var/www/craft/vendor/craftcms/cms/src/helpers/ProjectConfig.php","line":221,"stack-trace":["#0 /var/www/craft/vendor/craftcms/cms/src/helpers/ProjectConfig.php(182): craft\\helpers\\ProjectConfig::_cleanupConfigValue(Array)","#1 /var/www/craft/vendor/craftcms/cms/src/helpers/ProjectConfig.php(237): craft\\helpers\\ProjectConfig::cleanupConfig(Array)","#2 /var/www/craft/vendor/craftcms/cms/src/helpers/ProjectConfig.php(182): craft\\helpers\\ProjectConfig::_cleanupConfigValue(Array)","#3 /var/www/craft/vendor/craftcms/cms/src/helpers/ProjectConfig.php(237): craft\\helpers\\ProjectConfig::cleanupConfig(Array)","#4 /var/www/craft/vendor/craftcms/cms/src/helpers/ProjectConfig.php(182): craft\\helpers\\ProjectConfig::_cleanupConfigValue(Array)","#5 /var/www/craft/vendor/craftcms/cms/src/helpers/ProjectConfig.php(237): craft\\helpers\\ProjectConfig::cleanupConfig(Array)","#6 /var/www/craft/vendor/craftcms/cms/src/helpers/ProjectConfig.php(182): craft\\helpers\\ProjectConfig::_cleanupConfigValue(Array)","#7 /var/www/craft/vendor/craftcms/cms/src/helpers/ProjectConfig.php(237): craft\\helpers\\ProjectConfig::cleanupConfig(Array)","#8 /var/www/craft/vendor/craftcms/cms/src/helpers/ProjectConfig.php(182): craft\\helpers\\ProjectConfig::_cleanupConfigValue(Array)","#9 /var/www/craft/vendor/craftcms/cms/src/services/ProjectConfig.php(1709): craft\\helpers\\ProjectConfig::cleanupConfig(Array)","#10 /var/www/craft/vendor/craftcms/cms/src/services/ProjectConfig.php(834): craft\\services\\ProjectConfig->_updateYamlFiles()","#11 /var/www/craft/vendor/craftcms/cms/src/services/ProjectConfig.php(389): craft\\services\\ProjectConfig->saveModifiedConfigData()","#12 [internal function]: craft\\services\\ProjectConfig->craft\\services\\{closure}(Object(yii\\base\\Event))","#13 /var/www/craft/vendor/yiisoft/yii2/base/Component.php(628): call_user_func(Object(Closure), Object(yii\\base\\Event))","#14 /var/www/craft/vendor/yiisoft/yii2/base/Application.php(395): yii\\base\\Component->trigger('afterRequest')","#15 /var/www/craft/web/index.php(22): yii\\base\\Application->run()","#16 {main}"]}}

It looks like all of the project config has been deleted, and not written back again.

Hitting any Craft URL after this yields an error:

> Error
> Only variables can be passed by reference

    php_1     | 2021-03-04 11:04:38 [172.18.0.1][-][-][error][Error] Error: Only variables can be passed by reference in /var/www/craft/vendor/craftcms/cms/src/helpers/ProjectConfig.php:221
    php_1     | Stack trace:
    php_1     | #0 /var/www/craft/vendor/craftcms/cms/src/helpers/ProjectConfig.php(182): craft\helpers\ProjectConfig::_cleanupConfigValue(Array)
    php_1     | #1 /var/www/craft/vendor/craftcms/cms/src/helpers/ProjectConfig.php(237): craft\helpers\ProjectConfig::cleanupConfig(Array)
    php_1     | #2 /var/www/craft/vendor/craftcms/cms/src/helpers/ProjectConfig.php(182): craft\helpers\ProjectConfig::_cleanupConfigValue(Array)
    php_1     | #3 /var/www/craft/vendor/craftcms/cms/src/helpers/ProjectConfig.php(237): craft\helpers\ProjectConfig::cleanupConfig(Array)
    php_1     | #4 /var/www/craft/vendor/craftcms/cms/src/helpers/ProjectConfig.php(182): craft\helpers\ProjectConfig::_cleanupConfigValue(Array)
    php_1     | #5 /var/www/craft/vendor/craftcms/cms/src/helpers/ProjectConfig.php(237): craft\helpers\ProjectConfig::cleanupConfig(Array)
    php_1     | #6 /var/www/craft/vendor/craftcms/cms/src/helpers/ProjectConfig.php(182): craft\helpers\ProjectConfig::_cleanupConfigValue(Array)
    php_1     | #7 /var/www/craft/vendor/craftcms/cms/src/helpers/ProjectConfig.php(237): craft\helpers\ProjectConfig::cleanupConfig(Array)
    php_1     | #8 /var/www/craft/vendor/craftcms/cms/src/helpers/ProjectConfig.php(182): craft\helpers\ProjectConfig::_cleanupConfigValue(Array)
    php_1     | #9 /var/www/craft/vendor/craftcms/cms/src/services/ProjectConfig.php(1903): craft\helpers\ProjectConfig::cleanupConfig(Array)
    php_1     | #10 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(yii\redis\Cache))
    php_1     | #11 /var/www/craft/vendor/yiisoft/yii2/caching/Cache.php(597): call_user_func(Object(Closure), Object(yii\redis\Cache))
    php_1     | #12 /var/www/craft/vendor/craftcms/cms/src/services/ProjectConfig.php(1904): yii\caching\Cache->getOrSet('projectConfig:i...', Object(Closure), NULL, Object(yii\caching\ExpressionDependency))
    php_1     | #13 /var/www/craft/vendor/craftcms/cms/src/services/ProjectConfig.php(1647): craft\services\ProjectConfig->_loadInternalConfigData()
    php_1     | #14 /var/www/craft/vendor/craftcms/cms/src/services/ProjectConfig.php(1636): craft\services\ProjectConfig->_getStoredConfig()
    php_1     | #15 /var/www/craft/vendor/craftcms/cms/src/services/ProjectConfig.php(438): craft\services\ProjectConfig->_getLoadedConfig()
    php_1     | #16 /var/www/craft/vendor/craftcms/cms/src/base/ApplicationTrait.php(1465): craft\services\ProjectConfig->get('system.timeZone')
    php_1     | #17 /var/www/craft/vendor/craftcms/cms/src/base/ApplicationTrait.php(1418): craft\web\Application->_setTimeZone()
    php_1     | #18 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(90): craft\web\Application->_preInit()
    php_1     | #19 /var/www/craft/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
    php_1     | #20 /var/www/craft/vendor/yiisoft/yii2/base/Application.php(212): yii\base\BaseObject->__construct(Array)
    php_1     | #21 [internal function]: yii\base\Application->__construct(Array)
    php_1     | #22 /var/www/craft/vendor/yiisoft/yii2/di/Container.php(420): ReflectionClass->newInstanceArgs(Array)
    php_1     | #23 /var/www/craft/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
    php_1     | #24 /var/www/craft/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
    php_1     | #25 /var/www/craft/vendor/craftcms/cms/bootstrap/bootstrap.php(246): yii\BaseYii::createObject(Array)
    php_1     | #26 /var/www/craft/vendor/craftcms/cms/bootstrap/web.php(51): require('/var/www/craft/...')
    php_1     | #27 /var/www/craft/web/index.php(21): require('/var/www/craft/...')

I'm running this inside a Docker container. Could it be permissions? I've done upgrades that have worked before fine and am using project config with multiple team members without issue.

**Comment by brandonkelly** [comment]
What version of PHP are you running?

**Comment by nickdunn** [comment]
7.3 (Docker image `php:7.3-apache`)

**Comment by nickdunn** [comment]
Before doing the upgrade, I had switched branches to pull in some other project config changes and manually applied them via the Craft CP (Utilities > Project config > Apply all) rather than using the Craft CLI via composer which I normally do. Would this maybe have set some bad permissions such that future updates won't be written?

**Comment by brandonkelly** [comment]
I’m thinking this is probably a PHP bug, but have just worked around it. Would be great if you could test – change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.6.8"` and then run `composer update`.

**Comment by nickdunn** [comment]
Should I do this after my 3.8.8 update has failed, or from my 3.6.6 baseline?

**Comment by brandonkelly** [comment]
It shouldn’t matter either way.

**Comment by nickdunn** [comment]
After making this change the CP tells me there's some finishing up to do, hit the button, yielded an error:

    Database Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'projectconfignames' already exists
    The SQL being executed was: CREATE TABLE projectconfignames (
    uid char(36) NOT NULL DEFAULT '0',
    name varchar(255) NOT NULL,
    PRIMARY KEY(uid)
    ) ENGINE = InnoDb DEFAULT CHARACTER SET = utf8

    Migration: craft\migrations\m210224_162000_add_projectconfignames_table

    Output:

    > create table {{%projectconfignames}} ...Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'projectconfignames' already exists
    The SQL being executed was: CREATE TABLE projectconfignames (
    uid char(36) NOT NULL DEFAULT '0',
    name varchar(255) NOT NULL,
    PRIMARY KEY(uid)
    ) ENGINE = InnoDb DEFAULT CHARACTER SET = utf8 (/var/www/craft/vendor/yiisoft/yii2/db/Schema.php:678)
    #0 /var/www/craft/vendor/yiisoft/yii2/db/Command.php(1304): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE p...')
    #1 /var/www/craft/vendor/yiisoft/yii2/db/Command.php(1099): yii\db\Command->internalExecute('CREATE TABLE p...')
    #2 /var/www/craft/vendor/yiisoft/yii2/db/Migration.php(323): yii\db\Command->execute()
    #3 /var/www/craft/vendor/craftcms/cms/src/migrations/m210224_162000_add_projectconfignames_table.php(22): yii\db\Migration->createTable('{{%projectconfi...', Array)
    #4 /var/www/craft/vendor/craftcms/cms/src/db/Migration.php(52): craft\migrations\m210224_162000_add_projectconfignames_table->safeUp()
    #5 /var/www/craft/vendor/craftcms/cms/src/db/MigrationManager.php(232): craft\db\Migration->up(true)
    #6 /var/www/craft/vendor/craftcms/cms/src/db/MigrationManager.php(148): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m210224_162000_add_projectconfignames_table))
    #7 /var/www/craft/vendor/craftcms/cms/src/services/Updates.php(250): craft\db\MigrationManager->up()
    #8 /var/www/craft/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(509): craft\services\Updates->runMigrations(Array)
    #9 /var/www/craft/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')

Maybe my build is in limbo. Expected?

**Comment by brandonkelly** [comment]
For posterity, the above error was resolved by manually deleting the `projectconfignames` table and running migrations again.
