### ISSUE TITLE
Base Field: getIsTranslatable() should consider 'custom' translation value

### ISSUE THREAD

**Issue by qbasic16** [craftcms/cms#7647]
### Description

Howdy,

In a Craft multi-language site there was a requirement to disable translation for some fields depending on the secion, the entry is in. I have created a custom function which returns a different translationKey depending on the section, which works great and the field value gets propagated correctly.

Now to my feature request:\
When editing an entry, the translatable icon of a field currently gets displayed depending on the return value of the method [Field::getIsTranslatable()](https://github.com/craftcms/cms/blob/develop/src/base/Field.php#L314).

It would be great, in the case of translation method 'custom', the return value of the `renderObjectTemplate` call considering the custom `translationKeyFormat`, similar to what is implemented in [ElementHelper::translationKey()](https://github.com/craftcms/cms/blob/develop/src/helpers/ElementHelper.php#L533).

My implementation proposal for `craft\base\Field`:

```php
    public function getIsTranslatable(ElementInterface $element = null): bool
    {
        // new additional behavior:
        if(
            $element !== null
            && $this->translationMethod === self::TRANSLATION_METHOD_CUSTOM
        ) {
            return '1' !== $this->getTranslationKey($element);
        }
        // current behavior:
        return $this->translationMethod !== self::TRANSLATION_METHOD_NONE;
    }
```

Cheers,
Peter

**Comment by brandonkelly** [comment]
Just made this possible on the `3.7` branch. Went with checking for an empty string rather than `'1'` as you did in #7648.

**Comment by qbasic16** [comment]
> Just made this possible on the `3.7` branch. Went with checking for an empty string rather than `'1'` as you did in #7648.

You are awesome, thank you! 😎
