### ISSUE TITLE
Project Config Never Applies

### ISSUE THREAD

**Issue by OwenMelbz** [craftcms/cms#7651]
### Description
Since updating to 3.6.8 our project config never applies, it says "done" but then then still says unmerged changes, so you just keep infinitely running it.

Watch the output: https://drive.google.com/file/d/1p2cCUkfxMcIib0mc_3LejiZQuvntF_mC/view

### Steps to reproduce

1. run `php craft project-config/apply`

### Additional info

![image](https://user-images.githubusercontent.com/1094740/110005101-08789100-7d10-11eb-8c0e-29fbf12bd70d.png)

**Comment by brandonkelly** [comment]
Strange. Can you try running `php craft project-config/apply --force` ?

**Comment by OwenMelbz** [comment]
Hi,

Nope, If i run that first, I can still run /apply multiple times.

**Comment by brandonkelly** [comment]
Do you have any plugins/modules that could be causing these requests to end prematurely? Project Config never actually commits the changes to the DB and YAML files until the very end of the request, so my best guess is that something is preventing that code from being run.

We can take a look at it on our end if you send your Composer files, incoming YAML files, and a database backup over to support@craftcms.com.

**Comment by OwenMelbz** [comment]
We have plenty of modules and plugins :D None that I know are terminating the request.

Will take a dig around disabling stuff and seeing if it makes a difference.

I've just sent a wetransfer.com request to the email provided referencing this ticket which contains the code and a database dump inside `scripts/install.sql`

Thanks :)

**Comment by OwenMelbz** [comment]
You know what... I just randomly disabled then enabled it again, it updated some yaml files now it's fine... Looks like it got itself stuck in a jam somehow and just needed a file rewritten xD
