### ISSUE TITLE
Craft logs 404s to web.log rather than web-404s.log

### ISSUE THREAD

**Issue by benjaminkohl** [craftcms/cms#7653]
### Description

After updating a site from Craft 3.5.19.1 to Craft 3.6.*, Craft no longer logs 404s to the web-404s.log and instead logs them to web.log resulting in cluttered logs that fill up quickly, making it harder to track down Exception stack traces for more critical site errors. High traffic sites lose their log content in a very short amount of time.

### Steps to reproduce

1. Install Craft 3.6.*
2. Navigate to a page that does not exist.
3. Look for a web-404s.log.

### Additional info

- Craft version: 3.6.8
- PHP version: 7.3.9
- Database driver & version: MySQL 5.7.26

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.6.9 is out now with that fix.
