### ISSUE TITLE
Yii debug toolbar: unable to find debug data

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#7656]
### Description
I think I'm having cache issues on a production env, and I am looking to check the Yii debug toolbar. But both on dev local MAMP server and remote production server, the Yii debug toolbar fails to load on front-end ok (CP is ok).

This is what I can find under the Chrome DevTools:
- Request URL: `/index.php?p=actions/debug/default/toolbar&tag=604240920c698`
- 404 error: `Not Found: Unable to find debug data tagged with '604240920c698'.`

I disabled every custom config in the htaccess file, and print out a the `tag` query param value on a Twig front-end template: this works as expected. I also deleted the `runtime` folder, reset the permissions (recursive to `777`), deleted the `vendor` folder then ran a `composer install`... But the toolbar still fails to load.

Any idea why?

### Additional info

- Craft version: 3.6.8
- PHP version: 7.4.5
- Database driver & version: MySQL 5.7.32 (dev) / MySQL 8.0.18 (prod)

**Comment by brandonkelly** [comment]
Are you seeing folders & files getting created in `storage/runtime/` after deleting + recreating it?

The debug data gets saved in `storage/runtime/debug/`.

**Comment by romainpoirier** [comment]
Yes, after emptying the runtime folder, I can see the brand new `cache`, `compiled_classes` and `compiled_templates` folders (both containing files and folders), both on `dev` and `production` environment.

However, in both environments there is no `debug` folder created inside.

**Comment by brandonkelly** [comment]
Any chance we could get SSH access to the box? If so please send credentials over to support@craftcms.com.

**Comment by romainpoirier** [comment]
I sent you an email about the credentials. Thank you.

However, I can add new details today:
- On production, I deleted again the `storage/runtime/debug` storage, reset the permissions (using `chmod -R 777`), and now I can see new files created within this folder after page reload. However, I still get a JS 404 error because of a missing cache key despite these new files are created;
- On dev (MAMP), I still got this 404 JS error and no new files are created, despite a deletion of this folder and a permissions reset;

**Comment by romainpoirier** [comment]
Thanks to @olivierbon from the Craft CMS support we finally found a reduced case to get the debug toolbar showing up again.

```
'disabledPlugins' => [
    'expanded-singles',
    'wishlist'
]
```

So the issue could be from `verbb/expanded-singles` (here using `1.1.3`) and `verbb/wishlist` (here using `1.4.5`). Both should be disabled to get the toolbar. I'm forwarding this to the Verbb support so they can investigate.
