### ISSUE TITLE
Bug in Dev Mode logging check

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#7659]
### Description

Craft 3.6.9 included a commit that breaks the check for `devMode` when logging, by incorrectly using `YII_DEBUG` (see the note in the code). This results in the `console.log` files getting bloated in production.

https://github.com/craftcms/cms/commit/8465a17ea3623cc56086dc7a0c310a0f147db45f#diff-b37403631eb937359e7657f7b4a35ee90eb0dd07b68b8b43b95655ad3d2af9daL85-L89

@brandonkelly there may be a reason you did this, hence the issue instead of a PR.

Original working code:

```php
// Only log errors and warnings, unless Craft is running in Dev Mode or it's being installed/updated
// (Explicitly check GeneralConfig::$devMode here, because YII_DEBUG is always `1` for console requests.)
if (!Craft::$app->getConfig()->getGeneral()->devMode && Craft::$app->getIsInstalled() && !Craft::$app->getUpdates()->getIsCraftDbMigrationNeeded()) {
```

New broken code:

```php
// Only log errors and warnings, unless Craft is running in Dev Mode or it's being installed/updated
// (Explicitly check GeneralConfig::$devMode here, because YII_DEBUG is always `1` for console requests.)
if (!YII_DEBUG && Craft::$app->getIsInstalled() && !Craft::$app->getUpdates()->getIsCraftDbMigrationNeeded()) {
```

**Comment by brandonkelly** [comment]
Doh – RTFC :)
