### ISSUE TITLE
Redirect template routed index to their entry

### ISSUE THREAD

**Issue by chrisrowe** [craftcms/cms#7663]
When you're using privateTemplateTrigger as `_` you tend to do `/blog/index` and `blog/_entry` for your single and channel urls which is great, but that means the path `/blog/index` gets caught by the template route and doesn't reach the entry route.

See https://craftcms.com/features/index and https://craftcms.com/pricing/index for example

I suppose this isn't a bug but a side effect that might want to be considered?

**Comment by chrisrowe** [comment]
I guess I was flagging it since it's a very common pattern which produces bad URLs as per my https://craftcms.com/pricing/index example. Totally agreed its not a bug though, we've switched to disabling the `privateTemplateTrigger` to avoid this ever happening.

**Comment by brandonkelly** [comment]
> we've switched to disabling the `privateTemplateTrigger` to avoid this ever accidentally happening

How would that help? That would just make it so all templates are publicly accessible.

**Comment by brandonkelly** [comment]
Ah right! Sorry, I forgot and thought it went the other way.
