### ISSUE TITLE
The comments havent been updated

### ISSUE THREAD

**Issue by dorineal** [craftcms/cms#7669]
It is written in the example section 

```
use craft\events\RegisterGqlTypeEvent;

and

RegisterGqlTypeEvent $event
```

But it is the event 
craft\events\RegisterGqlType**s**Event

Was that a mistake when editing the event name?

Source: 

https://github.com/craftcms/cms/blob/8228fa7d392fc388e8babdddf0b1d42d0903382f/src/services/Gql.php#L105
https://github.com/craftcms/cms/blob/8228fa7d392fc388e8babdddf0b1d42d0903382f/src/services/Gql.php#L109

**Comment by brandonkelly** [comment]
The `use` statement imports `craft\events\RegisterGqlTypeEvent` so that it can be referenced as simply `RegisterGqlTypeEvent`. You can learn about that here: https://www.php.net/manual/en/language.namespaces.importing.php

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed the comments for the next release.

**Comment by dorineal** [comment]
Thanks :)
