### ISSUE TITLE
"Globals" nav missing "sel" class on select/active

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#7670]
### Description
Selecting the "globals" nav In the control panel sidebar navigation doesn't attach the class "sel" to the nested anchor element.

The example below is what the code should look like when the nav item is selected.

```
<li id="nav-globals">
<a class="sel" href=".../globals/global">
<span class="icon icon-mask" aria-hidden="true"><span data-icon="globe"></span></span>
<span class="label">Globals</span></a>
</li>
```

### Additional info

- Craft version: 3.6.10

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you think of anything unique about your setup that could be messing with this?

**Comment by richhayler** [comment]
I went through my list of installed plugins and after disabling “Control Panel Nav” (despite not having a custom nav setup), the problem went away. I’ll look into this and report back to the Verbb team to see if they are able to reproduce the same.
