### ISSUE TITLE
Section parameter not working in entry queries

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#7678]
### Description

There seems to be an issue with some element query parameters in the latest 3.6 releases (starting with 3.6.7). The following query returns all entries, even though a section with handle `unknown-section` doesn’t exist.

```php
Entry::find()->section('unknown-section')->all()
```

### Additional info

- Craft version: 3.6.10
- PHP version: 7.4.15
- Database driver & version: PostgreSQL 11.10
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Whoops, looks like this happened as a result of a70903c9afecab7bc9e7fd7a5e5fa238b052d9a0. Fixed for the next release. Thanks for reporting.

**Comment by brandonkelly** [comment]
Craft 3.6.11 is out now with that fix.
