### ISSUE TITLE
Eager loading a 'author' field doesn't work

### ISSUE THREAD

**Issue by ryssbowh** [craftcms/cms#7679]
### Description

If I have a field with handle 'author' I can't eager-load it.
This is due to the handle 'author' being bypassed in the `craft\elements\Entry->setEagerLoadedElements()` method.
Should 'author' be a reserved handle ?

### Steps to reproduce

1. Create a field on an element with handle 'author'
2. Eager load it with `\Craft::$app->elements->eagerLoadElements(get_class($element), [$element], 'author');`

### Additional info

- Craft version: 3.6.6
- PHP version: 7.4
- Database driver & version: mysql 5.7
- Plugins & versions:

**Comment by andris-sevcenko** [comment]
Thanks for reporting that! This issue has actually already been covered by #2797.
Please follow along over there.

**Comment by brandonkelly** [comment]
For posterity, this is [resolved for Craft 3.7](https://github.com/craftcms/cms/issues/2797#issuecomment-859155102).
