### ISSUE TITLE
POSTed Date Format does not work with Twig Date()

### ISSUE THREAD

**Issue by MattWilcox** [craftcms/cms#7681]
### Description

I am developing a simple plugin. It has a CP section, which has a Form with a date field on it. The rest of the Twig on that page renders a table based on Commerce Orders from the date specified (or a default date on initial page load).

The form posts to itself, so that the page is reloaded...

```
<form action="" method="post">
	{{ csrfInput() }}
			
	{{ forms.dateTimeField({
		label: 'From',
		name: 'fromDate',
		value: fromDate ??? defaultFrom
	}) }}

	<input type="submit" class="submit btn" value="Run Report">
</form>
```

However, it seems impossible to work with the data posted:

```
{% set fromField  = craft.app.request.post('fromDate') %}{# is an array #}
{{ dd(fromField) }}
```

gives

```
array:3 [▼
  "date" => "15/01/2021"
  "timezone" => "Europe/London"
  "time" => "10:57"
]
```

And with that data the following code:
```
{% set fromDate = date("#{fromField['date']} #{fromField['time']}", fromField['timezone'] ) | atom %}
```

throws

```
DateTime::__construct(): Failed to parse time string (15/01/2021 10:57) at position 0 (1): Unexpected character
```

This seems to be that PHP treats any string where the date is separated with slashes as American format. And in American format, this is not a valid date.

However the site is in British, and it is a valid British format.

I can see no option in the macro to specify the format of the date you want to pass via POST, and I can see no Twig filter or parameter that will consume a British format date and convert it to a DateTime object I can work with later in the Twig?

I feel like I *must* be missing something obvious, but no Filters seem to apply, the date() filter seems to be ignoring the passed timezone as a method of interpolating the passed string, and all the docs relating to Date assume you're either using a keyword such as "now" or using a Date field pulled from Craft instead of a POSTed form field.

I've also tried

`{% set fromDate = "#{fromField['date']} #{fromField['time']}" | date("d/m/Y H:i", fromField['timezone'] ) | atom %}`

In case I'd misunderstood the way the date function works, but that also fails in the same way with the same message.

### Additional info

- Craft version: 3.6.10
- PHP version: 7.4

**Comment by brandonkelly** [comment]
The expectation is that the value will go through `craft\helpers\DateTimeHelper::toDateTime()` from a controller action, which would normalize the `date`/`time` array into a `DateTime` object.

I’ve just added support for passing a `date`/`time` array to the `date()` Twig function for Craft 3.7.
