### ISSUE TITLE
User logged out after password change on front-end

### ISSUE THREAD

**Issue by lennartlott** [craftcms/cms#7682]
### Description
User logged out after password change on front-end.
Is it possible for the user to stay logged in?

### Steps to reproduce

1. Change password on frontend
2. User will log out automatically

### Additional info

- Craft version: 3.6.10
- PHP version: 8.0
- Database driver & version: Aurora / MYSQL
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting that! This affected the control panel as well. Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.6.11 is out now with that fix.
