### ISSUE TITLE
Asset fields within Matrix fields reinitialise the asset viewer modal for each field instance 

### ISSUE THREAD

**Issue by bendesilva** [craftcms/cms#7683]
### Description

I have a client which has an extensive asset library hosted on S3 on a Craft install which is used daily, and as such have experienced the problems with the registry relating to large asset libraries with lots of folders as mentioned in issue #1629. While it does affect general productivity within the CMS, it's less of an issue on entries which have a single asset field as once the asset viewer is initialised it's quick to move around, and you can reopen the viewer and see a list of files/folders instantly.

This isn't the case with Matrix fields which contain the same assets field however, the asset viewer is reinitialised for each field when the viewer is pulled up. The 1-2 minute delay on large libraries is forgivable the first time, but if a matrix field with 50+ blocks is being used you quickly create a bottleneck on the cumulative time spent waiting for the viewer to load, which has started to become a real issue with this client's Craft install to the point of it being unusable in certain situations. Is there a way for the asset viewer instance to be shared between asset fields that appear in multiple matrix blocks? This would solve that issue and save hours of wasted time a week, and as the asset library increases in size the issue is steadily getting worse.

Possibly related to #6077.

### Steps to reproduce

1. Create a matrix field with a block that contains an asset field and add to a section.
2. Create an entry of the chosen section type, add a block and add an asset (or just open the viewer).
3. Create a new block of the same type, and add an asset (or just open the viewer). The viewer is initialised again.

### Additional info

- Craft version: 3.6.6
- PHP version: 7.4.2
- Database driver & version: MySQL 5.7.26
- Plugins & versions: (only including pertinent plugins as this issue is present in a clean Craft install) ImagerX 3.3.0, Amazon S3 1.2.11

**Comment by brandonkelly** [comment]
Yeah this is the same issue as #1629. Each individual Assets field instance needs to have its own selection modal, as they can each differ from block to block depending on the Assets field’s settings, and they each have their own unique states as well (which assets are selected already, etc.).

I’d suggest reevaluating the folder structure, so that assets are more deeply nested, rather than having a ton of folders living alongside each other. If you do that, it should load much quicker.
