### ISSUE TITLE
CP Access Session Duration

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#7688]
### Description
Hi There,

A client runs a site with both front-end users (which should have a looooooooong session) and CMS users, which should, for security reasons, have a short session. However, the current Config setting `userSessionDuration` only allows us to set a setting for all roles/users. 

It would be great if we could set this based on role name, or based on rights.

Current way:
`
[
    'userSessionDuration' => 31536000
]
`

Suggested (or whatever, you know best):
`
[
   'userSessionDurationByRole' => 
   [
        'accessCp' => 0,
   ]
]
`

Or perhaps some way to hook into the `actionLogin()` with a event?

**Comment by brandonkelly** [comment]
> Or perhaps some way to hook into the `actionLogin()` with a event?

Here’s how you could do that:

```php
use Craft;
use craft\controllers\UsersController;
use yii\base\ActionEvent;
use yii\base\Event;

Event::on(
    UsersController::class,
    UsersController::EVENT_BEFORE_ACTION,
    function(ActionEvent $event) {
        if (
            $event->action->id === 'login' &&
            Craft::$app->request->getIsCpRequest()
        ) {
            Craft::$app->config->general->userSessionDuration = 0;
            Craft::$app->config->general->rememberedUserSessionDuration = 0;
        }
    }
);
```

**Comment by lenvanessen** [comment]
Awesome, you're the best
