### ISSUE TITLE
Change the sortOrder attribute of fields in the migration

### ISSUE THREAD

**Issue by mmikhalko** [craftcms/cms#7690]
### Description

I would like to change the the Order of fields in the tab Field Layout, but after changing it does not apply. Maybe I doing something wrong

### Steps to reproduce

1. Create the new migration
2. Add the example script below

```php
 public function safeUp() {
    $section = Craft::$app->sections->getSectionByHandle('nameOfSection');
    $types = $section->getEntryTypes();
    $entryType = $types[0];
    $fields = $entryType->getFields();
    $order = 3;
    foreach ($fields as $field) {
            if ($field->handle == 'someField1') {
                $field->sortOrder = 2;
            } else if ($field->handle == 'someField2') {
                $field->sortOrder = 1;
            } else {
                $field->sortOrder = $order;
                $order++;
            }
        }
        
    Craft::$app->sections->saveEntryType($entryType);
}
```

### Additional info

- Craft version: 3.5.14
- PHP version: 7.3.15
- Database driver & version: MySQL 5.6.39
- Plugins & versions:

**Comment by brandonkelly** [comment]
You should just change it in the control panel UI, and then apply it to other environments using [project config](https://craftcms.com/docs/3.x/project-config.html).
