### ISSUE TITLE
[FR] Make all pending jobs visible in the Queue Manager

### ISSUE THREAD

**Issue by naboo** [craftcms/cms#7692]
### Description
Right now the Queue Manager only displayes the current running jobs. It would be nice to also be able to view all pending jobs. With "all pending jobs" I mean that jobs created with `->delay()` and added for the future should be included as well.

**Comment by brandonkelly** [comment]
Good call, just added this for the next release.

**Comment by brandonkelly** [comment]
Craft 3.6.11 is out now with that change.
