### ISSUE TITLE
First-party Microsoft Azure asset support

### ISSUE THREAD

**Issue by astuteo** [craftcms/cms#7693]
Considering how far Craft has come, it's frustrating to have no first-party asset volume support for Azure yet. We have enterprise clients that, operationally, have everything on Microsoft cloud, but we end up maintaining hundreds of MB of image and file assets across environments. Adding S3 or Google to the mix (for the website) isn't really a viable solution for them from the ops side.

Fully aware there's a free third-party solution for this, but considering how fundamental the requirement is for an enterprise website, we're not comfortable making that move given it could be abandoned at anytime. Not sure of the lift, but it would really help round out Craft as an enterprise solution.

**Comment by brandonkelly** [comment]
We should be able to get this into Craft 4 assuming https://github.com/thephpleague/flysystem/pull/1277 gets pulled in.

**Comment by brandonkelly** [comment]
We just went ahead and released an Azure plugin for Craft 3: https://plugins.craftcms.com/azure-blob
