### ISSUE TITLE
RFQ - Different post date per multisite entry

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#7694]
### Description

We're using "Let each entry choose which site it's active on" propagation setting heavily in our system, and it's great. However, we also schedule a lot of content, and the only downsite with this system is that you can't schedule a different postdate for a translation/other site. Possibly related to #2116. Would be great if this was possible somehow.

**Comment by lenvanessen** [comment]
@brandonkelly don't mean to push, but do you have an idea around the feasibility of implementing this? We're kind of in debating between a couple of paths, both are suboptimal in terms of implementation. But knowing if this can be addressed will help us put it into perspective and plan this on our timeline.

1. Create a translatable postDate field and not use the built in field. However, we run into a heap of problems there, for example:
- Blitz doesn't know when the cache should be invalidated
- There's multiple plugins (SEOmatic etc) that use this field for al heap of things.

2. Work around the problems of having no-propagation between the sites
- Allow for duplication between the sites using for instance the Duplicate Entries extension
- Manually set the SEOmatic settings for alternate links etc
- Override functionality for the Language switcher, getSupportedSites method etc.

**Comment by brandonkelly** [comment]
@lenvanessen This would be a relatively involved change, so not something we’d do outside of a major release (4.0/5.0/etc.), and only if it were to pick up some steam.
