### ISSUE TITLE
Craft Search service not working with russian text

### ISSUE THREAD

**Issue by MathiesG** [craftcms/cms#7696]
### Description

The craft search service does not work in Russian. The Russian characters are translated into a 'safe' version in the searchindex table after saving an entry. For example a field with the value `Серология` is stored in the table as `serologija`.
When using the Craft search service as follows:
 `{% set results = craft.entries().search('application:"Серология"').all() %}` no results are returned.
The logs show that the query being executed is this one:
`
SELECT 'elementId' FROM 'searchindex' WHERE (('fieldId' = '82') AND MATCH('keywords') AGAINST('serologiya*' IN BOOLEAN MODE)) AND ('siteId'='4')
`

So in the searchindex table the translated version of "**Серология**" is "**serologija**" and in the executed query, the translated version of "**Серология**" is "**serologiya**". 
The same russian text seems to be translated in 2 different ways, this seems to be the reason that no results are found by the search service

### Steps to reproduce

1. Set the language of the website to russian  
2. Add a field and enable search for this field
3. Enter russian text in the field (e.g. `Серология`)
4. Use the Craft search service to search for specific values of this field: `search(fieldname:"Серология")`

### Additional info

- Craft version:  Craft Pro 3.5.11.1
- PHP version: 7.2.34
- Database driver & version: MySQL 5.5.5
- Plugins & versions: 

<table class="data fullwidth fixed-layout" dir="ltr">
            <tbody>
                                    <tr>
                        <th class="light">Amazon S3</th>
                        <td>1.2.11</td>
                    </tr>
                                    <tr>
                        <th class="light">Contact Form</th>
                        <td>2.2.7</td>
                    </tr>
                                    <tr>
                        <th class="light">Contact Form Extensions</th>
                        <td>1.2.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Control Panel Nav</th>
                        <td>3.0.12</td>
                    </tr>
                                    <tr>
                        <th class="light">Cookies</th>
                        <td>1.1.12</td>
                    </tr>
                                    <tr>
                        <th class="light">Cypress Diagnostics</th>
                        <td>1.0.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Element API</th>
                        <td>2.6.0</td>
                    </tr>
                                    <tr>
                        <th class="light">Empty Coalesce</th>
                        <td>1.0.6</td>
                    </tr>
                                    <tr>
                        <th class="light">Entry Count</th>
                        <td>2.0.3</td>
                    </tr>
                                    <tr>
                        <th class="light">Expanded Singles</th>
                        <td>1.1.2</td>
                    </tr>
                                    <tr>
                        <th class="light">Feed Me</th>
                        <td>4.2.3</td>
                    </tr>
                                    <tr>
                        <th class="light">Icon Picker</th>
                        <td>1.1.8</td>
                    </tr>
                                    <tr>
                        <th class="light">Mailgun</th>
                        <td>1.4.3</td>
                    </tr>
                                    <tr>
                        <th class="light">Neo</th>
                        <td>2.7.20</td>
                    </tr>
                                    <tr>
                        <th class="light">oEmbed</th>
                        <td>1.3.4</td>
                    </tr>
                                    <tr>
                        <th class="light">reCAPTCHA</th>
                        <td>1.5.0</td>
                    </tr>
                                    <tr>
                        <th class="light">Redactor</th>
                        <td>2.6.1</td>
                    </tr>
                                    <tr>
                        <th class="light">SEO</th>
                        <td>3.6.7</td>
                    </tr>
                                    <tr>
                        <th class="light">Translations</th>
                        <td>2.3.2</td>
                    </tr>
                            </tbody>
        </table>

**Comment by brandonkelly** [comment]
Hm strange… ASCII character mappings are provided by 

ASCII character mappings differ depending on the language. If your entry’s site’s language is set to Russian **and** the current site [voku/portable-utf8](https://github.com/voku/portable-utf8), but I can’t find anything in there that would convert `я` to `ja` – only `ya` (or `ia` for `ru__passport_2013`).

Can you try updating to the latest version, and then run the following command:

```bash
> php craft resave/entries --update-search-index
```

**Comment by MathiesG** [comment]
After the update and the resave of the search indexes everything seems to work.
Thanks!

**Comment by brandonkelly** [comment]
Glad to hear it! Sorry I somehow mangled my last reply, but glad you made some sense of it :)
