### ISSUE TITLE
Unable to acquire a lock for the structure

### ISSUE THREAD

**Issue by GregoirBrent** [craftcms/cms#7702]
### Description
Hello, When I open a entry on my website en edit some pictures and try to save it. There is a internal server error.
is there a reason why it can't post the change and why when i refresh it will do it?
somebody know what te problem is?

![Screenshot 2021-03-18 at 16 31 10](https://user-images.githubusercontent.com/26543981/111667096-ab530400-8814-11eb-915b-d7173cbf130b.png)

![Screenshot 2021-03-18 at 16 36 09](https://user-images.githubusercontent.com/26543981/111667071-a42bf600-8814-11eb-9307-32a83e0b3400.png)

### Steps to reproduce

1. open a entriey
2. change a picture
3. save entry
4. internal server error (error see title)
5. refresh page, click continue en it wil save the entry

### Additional info

- Craft version: 3.6.10
- PHP version: 7.3.27
- Database driver & version: MySQL 5.7.31
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Try executing the following SQL query on your database:

```sql
SELECT RELEASE_ALL_LOCKS();
```

**Comment by GregoirBrent** [comment]
It says 0

![Screenshot 2021-03-18 at 19 03 10](https://user-images.githubusercontent.com/26543981/111674720-98dcc880-881c-11eb-926d-984911a522ef.png)

**Comment by brandonkelly** [comment]
That’s fine. Did it fix the error?

**Comment by GregoirBrent** [comment]
no thats the weird part...

**Comment by GregoirBrent** [comment]
Can it be that if there are to mutch images with a large size of mb (1mb - 5mb) that this will give the server error?

**Comment by GregoirBrent** [comment]
https://user-images.githubusercontent.com/26543981/111676598-9e3b1280-881e-11eb-8343-90dcb6ebb8f2.mov

**Comment by brandonkelly** [comment]
Hm, it’s hard to tell what’s going on from here. Can you please create an Admin user account for support@craftcms.com, and also send SSH credentials over to support@craftcms.com?

**Comment by GregoirBrent** [comment]
Ok i did.
