### ISSUE TITLE
Queue/listen not honoring exit signal

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/cms#7704]
### Description

Whilst working on a Docker setup that would exit the `queue/listen` process gracefully I noticed that `\yii\queue\cli\Signal::isExit` is returning `true` but the while loop used for `queue/listen` does not stop.

`\craft\queue\Queue::listen`
```php
public function listen(int $delay)
{
    do {
        $this->run();
    } while (!$delay || sleep($delay) === 0);
}
```
The `\craft\queue\Queue::run` method does check for the exit signal and does stop executing any jobs but the listen process isn't being stopped since the loop in `\craft\queue\Queue::listen` keeps continuing.

### Steps to reproduce

1. Make sure that the `pcntl` package is installed on your setup.
2. Run `queue/listen`.
3. Send `SIGTERM` stop signal.
4. The `isExit` method will now be `true` however the PHP process isn't ending because of the while loop in `\craft\queue\Queue::listen`.

### Additional info

- Craft version: 3.6.10
- PHP version: 7.4.16
- Database driver & version: MySQL 5.7

**Comment by Wiejeben** [comment]
Also in terms of kill signals, the official PHP FPM packages use `SIGQUIT` by default but the `\yii\queue\cli\Signal::isExit` only listens for `[SIGTERM, SIGINT, SIGHUP]`. I would like for the `SIGQUIT` to be added just like the RabbitMQ queue driver `\yii\queue\amqp_interop\Queue::init`.

**Comment by brandonkelly** [comment]
Thanks for reporting that! This is fixed now for the next release.

**Comment by brandonkelly** [comment]
Craft 3.6.11 is out now with that fix.
