### ISSUE TITLE
Uncaught TypeError: Garnish.preventOutlineOnMouseFocus is not a function

### ISSUE THREAD

**Issue by sebastian-lenz** [craftcms/cms#7705]
### Description

A customer reported that he is not able to revert to previous revisions because the gray "Revert entry to this revision" is completely unresponsive in the control panel. Upon investigation we noticed that on that page additional controls do not react as they should, e.g. the user menu in the upper right corner cannot be opened. The JavaScript console shows an error: `Uncaught TypeError: Garnish.preventOutlineOnMouseFocus is not a function`.

### Steps to reproduce

Unfortunately I am not able to reliably reproduce this issue. The issue appears on some pages within the control panel, but not on all. I currently see no pattern as of which entry type / field / element / ? is causing the issue.

### Exception

This is the complete exception shown in the JavaScript debugger:

```
jquery.js?v=1616009825:formatted:1547 Uncaught TypeError: Garnish.preventOutlineOnMouseFocus is not a function
    at s.constructor.init (garnish.js?v=1616099905:formatted:2393)
    at s.constructor.constructor (garnish.js?v=1616099905:formatted:353)
    at s.constructor (garnish.js?v=1616099905:formatted:29)
    at new s.constructor (garnish.js?v=1616099905:formatted:29)
    at HTMLDivElement.<anonymous> (Craft.min.js?v=1616009825:1)
    at Function.each (jquery.js?v=1616009825:formatted:173)
    at b.fn.init.each (jquery.js?v=1616009825:formatted:89)
    at b.fn.init.pill (Craft.min.js?v=1616009825:1)
    at Object.initUiElements (Craft.min.js?v=1616009825:1)
    at HTMLDocument.<anonymous> (Craft.min.js?v=1616009825:1)
```

The origin of the exception seems to be the constructor of the component `Garnish.Pill` (see https://github.com/pixelandtonic/garnishjs/blob/master/src/Pill.js#L29). The called function `preventOutlineOnMouseFocus` does not exist within the Garnish library but is added by Craft (see https://github.com/craftcms/cms/blob/develop/src/web/assets/cp/src/js/Craft.js#L1403). My current guess is that for some reason the scripts are loaded in a different order on the affected pages.

### Additional info

- Craft version: 3.6.10
- PHP version: 7.4.15
- Database driver & version: MySQL 5.7.32

**Comment by brandonkelly** [comment]
Nothing in Craft is actually using `Garnish.Pill`. What plugins do you have installed?

**Comment by sebastian-lenz** [comment]
Ah, should have thought of that, thanks for the hint. As it turns out we've used an element with the class `pill` in a template that we've included using the new template field layout element.

As it's our fault, I'll close this ticket. I think the pill component might need fixing nonetheless, in case it should be used somewhere.

**Comment by brandonkelly** [comment]
Yeah I’m going to just remove the code for it. Sounds like a half-baked feature we never got around to finishing.

**Comment by brandonkelly** [comment]
Craft 3.6.11 is out now with that `pill` stuff removed.

**Comment by sebastian-lenz** [comment]
Awesome, thanks for the heads up!
