### ISSUE TITLE
Unable to update entry after reducing field relationship limit and wrong char encoding in validation message

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/cms#7707]
### Description

Hello! See steps below. After reducing the relationship limit on a field that currently have the limit exceeded does not show the items that are above the limit. Because of this I cannot remove the unwanted relationship without removing a potentially wanted relationship first.

Also the validation message encodes the field name wrong. My field name is `USP's` but in the validation message it output as `USP&#039;s mag maximaal 2 selecties bevatten.`

![Screenshot 2021-03-19 at 11 52 38](https://user-images.githubusercontent.com/2922378/111769524-9e342480-88a9-11eb-8453-1b0049bd50ab.png)

### Steps to reproduce

1. Create a relationship field with limit 3
2. Attach field to entry
3. Create entry with 3 relations
4. Reduce limit to 2
5. Open update entry page, the relationship field will now only show 2 entries
6. Save entry: Validation error will show with message about max limit exceeded

### Additional info

- Craft version: 3.6.10
- PHP version: 7.4.16
- Database driver & version: MySQL 5.7

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.6.11 is out now with the validation fix. Just realized I forgot to look into the encoding bug though. Just posted that as a new issue (#7718) and will follow up over there.

**Comment by Wiejeben** [comment]
@brandonkelly Wasn't sure whether to report it as a separate issue at first. Thanks for picking it up a day later ;)!
