### ISSUE TITLE
Abandoned plugin shows incomplete notice

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#7712]
### Description
Spotted here: https://plugins.craftcms.com/entry-instructions

There appears to be something missing " The developer recommends using instead"

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/755428/111908894-3de4e480-8a5b-11eb-8514-833cdd77ab6f.png">

### Steps to reproduce

1.
2.

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by benjamindavid** [comment]
Thanks for reporting this issue @janhenckens!
