### ISSUE TITLE
Drag and drop users to assign order

### ISSUE THREAD

**Issue by kevadamson** [craftcms/cms#7713]
I have a user group called "Team" which gets shown on the front end. It seems the default order is alphabetically based on email address - is this correct?

Just thinking it would be nice if there was an option to have the users "drag and dropable" much like a single level structure. I know this could be done by having a user fieldtype, but seems like an unnecessary extra step for the user to create the user, allocate the permissions, then go to the team entry page, and choose them again, just to enable an ordering method.

Thoughts?

**Comment by brandonkelly** [comment]
Nah this is definitely something that should be defined via a Users field. There are sites with hundreds of thousands of users, and adding structure data for them all would be a big waste in storage and performance.
