### ISSUE TITLE
Changes to Matrix field are not being saved

### ISSUE THREAD

**Issue by jrrdnx** [craftcms/cms#7715]
### Description

We have a client is trying to update several entries to add new blocks to a Matrix field, but on save the changes disappear. This occurs whether they're trying to add a new block, update an existing block, and/or delete an existing block.

This seems to be the same issue as #3832, #6665, and #6821, but I'm unable to roll back to a version early enough to resolve this issue at the moment. I have tested and confirmed this is occurring on Craft 3.5.15.1, 3.5.19.1, and 3.6.10.

### Steps to reproduce

1. Open an existing entry
2. Add/update/delete one or more blocks in a Matrix field
3. Save the entry (either by pressing Cmd+S or clicking the Save button at the top-right of the page)
4. Re-open the entry. Changes have not been saved.

This action does not generate any additional logs in /storage/logs.

### Additional info

- Craft version: Pro v 3.5.15.1, 3.5.19.1, and 3.6.10
- PHP version: 7.4.13
- Database driver & version: MySQL 5.7.32
- Plugins & versions:
  - Amazon S3: 1.2.11
  - Chunked File Uploads: 1.0.2
  - Control Panel CSS: 2.3.0
  - Cookies: 1.1.12
  - CP Field Inspect: 1.2.4
  - Embedded Assets: 2.5.1
  - Freeform: 3.10.10
  - Inline SVG: 0.1.2
  - Mix: 1.5.2
  - Neo: 2.9.3
  - Phone Number: 1.4.3
  - RD Zendesk: 1.3.2
  - Redactor: 2.8.5
  - Redirect Manager: 1.1.1
  - SEO: 3.3.35
  - Super Table: 2.6.7
  - Typed link field: 1.0.25
  - User Group field: 1.0.3
  - Wordsmith: 3.3.0.1

**Comment by jrrdnx** [comment]
Did a little more investigating and testing. The example this is currently being used on is for Recipes, and this channel contains two Matrix fields: Ingredients and Directions.

The Ingredients field contains 2 blocks: Ingredient (which contains a single Redactor field named Body) and Headline (which contains a single Plain Text field named Headline). The Directions field contains 2 blocks: Step (which contains a single Redactor field named Step) and Headline (which contains a single Plain Text field named Headline).

**Previously:** this issue affected only the _first_ Matrix field (Ingredients). I am able to add/update/delete blocks in the 2nd (Directions) field successfully.

I thought there might be issues with having 2 Matrix Blocks named "Headline", so I renamed the Ingredients -> Headline handle from "headline" to "ingredientsHeadline". After saving the field then updating an existing entry to add a Headline block to the Ingredients field, every existing block (19 of them) in the Ingredients field has disappeared and I'm still unable to add/edit/delete blocks in that field.

Just in case, I also tried deleting the old Ingredients Matrix field and recreating it from scratch and the issue persists. I'm unable to add any new blocks to this field on any entry.

**Comment by brandonkelly** [comment]
Hey @jrrdnx, can you please send a database backup and your Composer files to support@craftcms.com? We can try to reproduce from there and figure out what’s going on.

**Comment by jrrdnx** [comment]
Email sent, thank you!

**Comment by jrrdnx** [comment]
Closing issue as it's due to a previously unknown custom module (older project) breaking the Element On Save functionality.
