### ISSUE TITLE
Renaming an empty asset folder fails and deletes the folder

### ISSUE THREAD

**Issue by JensvdHeydt** [craftcms/cms#7721]
### Description
When renaming an empty folder on a locale volume the folder gets deleted instead of being renamed. A folder can only be successfully renamed if it contains files. I've tracked down this behavior to the function renameDirectory() located in src/base/FlySystemVolume.php line 311. If the folder contains any file the rename does work.

### Steps to reproduce

1. Create a folder on a local volume
2. Rename the folder using the web interface

### Additional info

- Craft version: 3.6.10
- PHP version: 7.4.x
- Database driver & version: mariadb
- Plugins & versions: ImageOptimize, Neo

**Comment by JensvdHeydt** [comment]
I forgot to mention this: The folder gets deleted on the local filesystem but the web UI shows the folder as being renamed successfully.

**Comment by andris-sevcenko** [comment]
Well, that's not very good.

Thanks for reporting this - just pushed a fix for the next Craft release!

**Comment by brandonkelly** [comment]
Craft 3.6.11.2 is out now with this fix.

**Comment by JensvdHeydt** [comment]
@brandonkelly Thank you very much. I just checked it in my install.

**Comment by 2mas** [comment]
Sorry but this doesnt work properly for me. This is what happens now with v. 3.6.12:

1. I created a folderstructure of Folder/SubFolder
2. Renamed SubFolder to SubFolderRenamed
3. The SubFolder gets renamed but it also creates another SubFolderRenamed inside of SubFolderRenamed
4. Renamed SubFolderRenamed to SubFolderRenamed2
5. Folders get deleted on disk but still exists in database

```
/var/www/html $ ls web/assets/docs/Folder
SubFolder

# Empty folder as expected
/var/www/html $ ls web/assets/docs/Folder/SubFolder/

# Performing rename in Craft SubFolder -> SubFolderRenamed
# Checking for SubFolder, doesnt exist anymore, good.
/var/www/html $ ls web/assets/docs/Folder/SubFolder/
ls: web/assets/docs/Folder/SubFolder/: No such file or directory

# Checking the containing folder, renamed now. Good.
/var/www/html $ ls web/assets/docs/Folder/
SubFolderRenamed

# Checking inside of SubFolderRenamed, it also contains a folder named SubFolderRenamed now
/var/www/html $ ls web/assets/docs/Folder/SubFolderRenamed/
SubFolderRenamed

# Renaming SubFolderRenamed to SubFolderRenamed2 in Craft makes all the folders go away and get deleted
/var/www/html $ ls web/assets/docs/Folder/SubFolderRenamed/
ls: web/assets/docs/Folder/SubFolderRenamed/: No such file or directory

# Empty folder, but still exists in Craft/DB
/var/www/html $ ls -la web/assets/docs/Folder/
total 8
drwxrwxr-x    2 www-data www-data      4096 Apr 14 09:27 .
drwxrwxrwx   12 1000     1000          4096 Apr 14 09:21 ..

```

**Comment by andris-sevcenko** [comment]
Ah, well that's quite a mishap. Fixed it for the next release. Correctly, this time.

**Comment by brandonkelly** [comment]
Craft 3.6.12.1 is out now with the fix for this.
