### ISSUE TITLE
Add primary key to `templatecacheelements`

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/cms#7723]
### Description

Currently we are migrating a few of our projects to a new setup. This setup uses DigitalOcean managed databases. I believe because this is a scalable database with fallback nodes and readonly nodes it requires every table to have a primary key, which is enforced by the `sql_require_primary_key` rule.

`templatecacheelements` happens to be the only table to not have a primary key and in order to migrate our databases we are having to manually add it (which hurts my feelings). We have had to do this before when using Percona XtraDB Cluster which also required primary keys on every table, however we only used Percona for specific large scale websites so wasn't a big deal.

I would like the primary key to be there by default, of course unless there is a good argument it would save us some time manually changing the database schema.

Thanks!

**Comment by Wiejeben** [comment]
I was brought to the attention that this was already requested https://github.com/craftcms/cms/issues/6246. The `templatecacheelements` table has been deprecated since 3.5 but still exists. Am I safe to just remove it entirely?

**Comment by brandonkelly** [comment]
Removing the table entirely could lead to SQL errors if any plugins are still referencing it, though that’s unlikely. You could try removing it and see how it goes. Worst case, you can empty out the table and add an `id` column to id, set as the primary key.
