### ISSUE TITLE
Email errors not in logs

### ISSUE THREAD

**Issue by bossanova808** [craftcms/cms#7729]
### Description

I have been switching all our emails from Mailgun to Postmark.

This all went very well and was simple.  However, after a few days, I noticed a particular group of messages was not being delivered.

Digging in to this, the only information from Craft was `false` coming back from `$message->send()` - there were no errors ([error] or [warning] etc) - anywhere in any of the Craft logs to be found.  No way whatsoever so see/surface the error, without hacking in to Craft or even Yii code, that I could see.  I spoke with Josh Crawford about it, and he's run in to this frustration as well.  

A quick look at `Mailer` suggests it will catch exceptions, but not that it will 'bubble up' API errors.  The only feedback to the developer is that `false` and it would be really super helpful (and, I presume, not all that hard to implement), if more was made available.  Just a `$message->getErrors()` type of thing...

Postmark don't have an API log, and doesn't show anything for messages not accepted either, so in the end I had to spend a couple of hours just using good ol' trail and error to work out the actual issue.  Apparently Postmark rejects messages with an empty (`""`) body (which is another issue I will talk to them about, as there are plenty of legitimate uses for emails with only a subject, and all the other email services accept these without complaint).

Anyway, would be great if it were more possible to see errors with the email service.

**Comment by brandonkelly** [comment]
There should be _something_ in the logs, beginning with `Error sending email:` followed by the error message. We don’t log the stack trace as it could contain sensitive info:

https://github.com/craftcms/cms/blob/05f280380028c062efa5acfb42d35259804c6240/src/mail/Mailer.php#L179-L182

I guess the empty body thing is tricky, as that wouldn’t have been an issue when sending the test email. Not sure what more we could do about that though.

**Comment by bossanova808** [comment]
Yeah I saw that, but that is only if there is an exception raised, right?   If 

`            return parent::send($message);`

...simply returns `false`, i.e. the API at the other end has raised an error but that doesn't trigger an exception....`false` is all that comes back, I think?  I didn't dig in deeply, but I can be sure that all I got was false, and there was definitely nothing the logs (believe me I checked a _bunch_ of times ;) - and again just now).

This is not for issues with sending email in the general sense, that's for sure working - it's just if there is a specific API error in some circumstance.  Not denying it's probably an edge case of course - but the errors are getting swallowed somewhere and ideally, they wouldn't be.

**Comment by brandonkelly** [comment]
Yeah true, unfortunately we don’t have access to whatever error actually occurred, as Swift Mailer [swallows the exception](https://github.com/swiftmailer/swiftmailer/blob/15f7faf8508e04471f666633addacf54c0ab5933/lib/classes/Swift/Mailer.php#L70-L76).

**Comment by bossanova808** [comment]
Ergh, that's gross.

Ah well, probably not much to be done then - sorry for the noise!

Even the RFC says:
```
   A message consists of header fields (collectively called "the header
   of the message") followed, optionally, by a body.  
```

So really, it's ultimately Postmark who should fix this specific issue, anyway. 

Thanks Brandon, I'll close this...
