### ISSUE TITLE
Validation not running on empty custom fields on an entry (when creating programmatically)

### ISSUE THREAD

**Issue by millman2394** [craftcms/cms#7732]
### Description
I'm trying to save an entry via a controller. They are contact form submission. A few of the fields are required. 

```php
$section = Craft::$app->sections->getSectionByHandle('contactSubmissions');

$entry = new Entry();
$entry->sectionId = $section->id;
$entry->typeId = 2;
$entry->authorId = 1;
$entry->enabled = true;

$entry->setFieldValues([
    'contactName' => ucwords($data['contactName']),
    'contactEmail' => $data['contactEmail'],
    'contactCompany' => $data['contactCompany'],
    'contactMessage' => $data['contactMessage'],
    'contactHeardAbout' => $data['contactHeardAbout'],
    'contactWebsite' => $data['contactWebsite'],
    'contactTitle' => $data['contactTitle'],
]);


if ( Craft::$app->elements->saveElement($entry) ) {
    //$this->sendMail($entry);
}

die(var_dump($entry->getErrors()));

return $entry;
```

The only validation that runs if the missing title, which in this case is the `contactName`. All other keys in the $data array are empty strings. They do not trigger any validation and the empty entry saves into the database.

If I were to go into the control panel and try to save the entry, it would fail with the validation errors.

If I were to enter a value for the email field, but have an invalid email, that validation then gets triggered. But none of the empty fields do. 

### Additional info

- Craft version: 3.6.10
- PHP version: 7.3.13

**Comment by brandonkelly** [comment]
Required field validation will only run when the entry is set to the `live` scenario.

Add this line right before your `saveElement()` line:

```php
$entry->setScenario(Entry::SCENARIO_LIVE);
```

**Comment by millman2394** [comment]
@brandonkelly Thank you very much. Would have never figured that out
