### ISSUE TITLE
Gateway Timeout on uploading large images

### ISSUE THREAD

**Issue by aeu** [craftcms/cms#7734]
### Description
We are seeing Gateway Timeouts when large images are uploaded.  We use a CDN that resizes images down, so our base images that we upload to the media library are often quite large, going up to 20M.  We are encountering two failure modes.

1. When moderately large images are uploaded (4,000 x 4,000 approx), the progress bars typically will fail to go away, but if we click over to a different part of the admin and back you can see that the image has been successfully uploaded and the thumbnails are in place. 
2. When large images are uploaded (7,000 x 7,000 and up) we will often get gateway timeouts.  The site will eventually recover and it is apparent that thumbnails and so on are in place.  Files have successfully been uploaded.  

We originally thought it was due to us using S3 as a volume (and the timeout was from server -> S3) but we created a local volume and saw the same results.  We now suspect that it is caused by the progress of thumbnail generation which is taking too long for larger images.  We also did notice that the files were successfully transferred to S3 (even when there was a Gateway Timeout error) which strengthens our suspicion that it's the thumbnail resizes causing the issue.

We have increased the php max execution time to 3600 seconds, and we have also allowed max process RAM to be 1G.

### Steps to reproduce

1. Create a large image of at least 7,000 x 7,000
2. Upload it to your media library
3. Gateway timeout happens.

### Additional info

- Craft version: 3.6.10
- PHP version: v7.3.25
- Database driver & version: mysql  Ver 15.1 Distrib 10.3.17-MariaDB, f
- Plugins & versions: Craft Commerce, Verb.io Postie.

OS is CentOS 7, on a VPS with 4G ram total.  Currently it is setup as a development server with an IP whitelist, so we are 100% sure that there is no other load on the server other than one or two people uploading content at a time.

**Comment by andris-sevcenko** [comment]
Gateway Timeout sounds like you are using Nginx as a reverse proxy and it's timing out. By default, Nginx times out after 60 seconds, which is not affected by any PHP execution time.

Processing large images will be slow and, unless you have disabled the [sanitizeCpImageUploads](https://craftcms.com/docs/3.x/config/config-settings.html#sanitizecpimageuploads), Craft will sanitize the image before doing anything with it, to ensure no malicious code is embedded.

What image driver are you using?

**Comment by aeu** [comment]
Hello,
nginx is not installed. sanitizeCpImageUploads is not disabled, Server has GD 2.2.5.

**Comment by andris-sevcenko** [comment]
> nginx is not installed.
Ah, pardon me. My mistake, then!

Is it possible to update to Imagick in this case? It's much faster than GD and produces better results.

Even with that, though, you're processing rather large images. If you can trust your content editors to not upload images with malicious code embedded in them, you can disable the `sanitizeCpImageUploads` setting to skip re-saving images that are uploaded via Control Panel. Disclaimer: this is less secure than leaving it enabled as it allows people with access to CP to potentially upload files with embedded malicious code in them.

**Comment by nicbou** [comment]
This is a frequent issue for me. Images above ~3MB constantly fail to upload, but I've had issues with images as small as 300 kilobytes. Unfortunately, the issue is impossible to debug as it leaves no traces in the logs. Even the UI fails silently with a full upload bar.

**Comment by brandonkelly** [comment]
@nicbou ImageMagick can have a lot of trouble processing PNG images that contain photographic content, where a JPG would probably have been a better format choice. That could explain why you’re having issues with small files.

As for larger files, we’re planning to add chunked upload support at some point, which will improve large file handling (#9084).

**Comment by vitalijalbu** [comment]
Upload images also get crashing when trying to upload like 30-40 photos at once. Inside my php.ini I have 512MB of upload.

**Comment by brandonkelly** [comment]
@vitalijalbu Each image will be its own upload request, so I don’t suspect it’s the quantity. The more images you upload at once, the more likely one of them is going to be problematic.
