### ISSUE TITLE
upgrade to 3.6

### ISSUE THREAD

**Issue by masoudjahromi** [craftcms/cms#7736]
### Description

knock, knock CraftCMS! is there anybody to help?

I got this error when I want to upgrade craftcms. (3.4 to 3.6)

```
*** applying m150403_184729_type_columns
    > alter column type in table {{%assetsources}} to string NOT NULL ...Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'assetsources' doesn't exist
The SQL being executed was: ALTER TABLE `assetsources` CHANGE `type` `type` varchar(255) NOT NULL (/vendor/yiisoft/yii2/db/Schema.php:678)

```
### Steps to reproduce

1. php craft update all

I also tried to upgrade without plugins and I get that error again.

### Additional info

- Craft version: 3.4.14
- PHP version: 7.3.24
- Database driver & version:
- Plugins & versions: aws-s3, SEO, field-manager, incognito-field

**Comment by andris-sevcenko** [comment]
Can you tell me the number of records in the `migrations` table as well as the values for `version` and `schemaVersion`fields in the `info` table, please?

**Comment by masoudjahromi** [comment]
@andris-sevcenko 

migrations table =>

I have `39 rows` in the migrations table.

info table =>

version:` 3.4.14`
schemaVersion: `3.4.10`
