### ISSUE TITLE
inReverse being ignored in GQL asset query

### ISSUE THREAD

**Issue by Tam** [craftcms/cms#7737]
### Description
The `inReverse` argument appears to be ignored in a GraphQL asset query. Looking into it, it appears as though the images are being eager-loaded before the `inReverse` argument is applied. Other arguments (i.e. `limit`, `orderBy`) work fine.

### Steps to reproduce

1. Create an asset field on an element (a Variant in our case)
2. Query that field, setting `inReverse` to true or false
3. Notice the order isn't changing

### Additional info

- Craft version: Craft Pro 3.6.11.1
- PHP version: 7.4.14
- Database driver & version: MySQL 5.5.5

Plugins | Version
-- | -- 
Craft Commerce | 3.2.17.3
DigitalOcean Spaces Volume | 1.1.3
Feed Me | 4.3.6
Maps | 3.9.0.2
Redactor | 2.8.5
SEO | 3.6.7
Super Table | 2.6.7
Typed link field | 2.0.0-beta.12

**Comment by andris-sevcenko** [comment]
Thanks for the heads up! Just patched this for eager-loading for the next release!

**Comment by brandonkelly** [comment]
Craft 3.6.11.2 is out now with that fix.
