### ISSUE TITLE
Web queue runner action indexed when running queues with Redis

### ISSUE THREAD

**Issue by mattsbanner** [craftcms/cms#7738]
### Description
We're running queues on a Craft Commerce site using Supervisor, with the queues in Redis as the web servers are load balanced. At one point, the site was using web based runners (with `runQueueAutomatically` set to `true`).

`/index.php?p=actions/queue/run` has been indexed by Bing and is now being crawled, thus throwing an error. I would like to think that Bing will drop it from their crawl list at some point given the 500.
```
The queue class yii\queue\redis\Queue doesn’t support web-based runners.
```

I suppose ideally, Bing should be instructed not to index that path with the `X-Robots` header, but I can't see that being a good idea on the `index.php` file. Could those actions be on a route where indexing can be disabled?

### Additional info

- Craft version: 3.6
- PHP version: 7.3
- Database driver & version: MySQL 5.7

**Comment by brandonkelly** [comment]
Thanks for reporting that! All action requests should have been responding with an `X-Robots-Tag: none` header. Just fixed that and released the fix in Craft 3.6.11.2.
