### ISSUE TITLE
Date field Graphql mutation supported ?

### ISSUE THREAD

**Issue by bartroelands** [craftcms/cms#7740]
### Description

When performing an entry mutation with a date field following error occurred: 

    {
      "debugMessage": "Object of class DateTime could not be converted to string",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      }

Is the date field supported for mutations ?

### Steps to reproduce

1.  Create field with standard date field (actionDueDate)
2. Put field on section
3. Perform mutation 

mutation MyMutation {
  save_xxxxx_action_Entry(action: "test 2", siteId: 2, actionDueDate: "2021-03-29") {
    action
  }
}

### Additional info

- Craft version: Craft Pro 3.6.10
- PHP version: 7.4.16
- Database driver & version: PostgreSQL 11.10
- Plugins & versions:

**Comment by andris-sevcenko** [comment]
I'm unable to reproduce this locally, unfortunately.

If possible, can you send over your `composer.lock` and `composer.json` files as well as a database dump (or your `config/project` folder, if that's easier for you) to support@craftcms.com and reference this issue? That would help us reproduce the issue you're seeing.

**Comment by andris-sevcenko** [comment]
This was not a bug or GraphQL related at all - the title format was trying to use the date-time field value as a string, which it was not.
