### ISSUE TITLE
Craft CMS does not track volume folders in project config

### ISSUE THREAD

**Issue by mildlygeeky** [craftcms/cms#7742]
### Description

Craft does not seem to track volume folders in project config. If a plugin (we ran into this with @khalwat's Image Optimize) wants to map to a volume folder with a field mapping that gets kept in the field's project config, mapping via UID is not a dependable way to do so, as that UID will change when a project moves from one environment to another.

### Steps to reproduce

1. Create an asset folder on something like S3 in one environment.
2. Index assets on another environment.
3. See that the environments now have different UIDs for the volume folders, rendering a plugin's ability to map them via project config basically impossible.

**Comment by mildlygeeky** [comment]
@khalwat made a good point (weird) which is that maybe these are not part of project config because content authors can create/delete them outside of the Settings / admin screen. Which might call for plugins such as Image Optimize to not map them via UID, but rather by path name.

Folders can even be created on-the-fly as users upload assets that use a `{slug}`, so even more I think it makes sense that they not be managed in project config, and this might be something for Image Optimize to change rather than Craft.

**Comment by andris-sevcenko** [comment]
Seems like you have it all figured out! :)

**Comment by khalwat** [comment]
@mildlygeeky File an issue for me and I'll get it fixed
