### ISSUE TITLE
script tag cannot handle query parameters

### ISSUE THREAD

**Issue by aeu** [craftcms/cms#7743]
### Description
The script tag (`{% js %}`) breaks when query parameters are used.

### Steps to reproduce

1. put in a js file with a query string - Example: `{% js "foo.js?v=bar" %}`

Your rendered HTML will look like this:

```html
<script>/foo.js?v=bar;</script></body>
```

Instead of 

```html
<script src="/foo.js?v=bar"></script>
```

### Additional info

- Craft version: 3.6.10
- PHP version: 7.3
- Database driver & version: mariadb 10
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
The `{% js %}` tag is used for registering JavaScript _code_, not individual `<script>` tags. You can use `view.registerJsFile()` to pull in an external JS file.

```twig
{% do view.registerJsFile('/foo.js?v=bar') %}
```
