### ISSUE TITLE
Separate Language Config for Console Requests

### ISSUE THREAD

**Issue by dralshehri** [craftcms/cms#7747]
### Description

When I set the `defaultCpLanguage` config to `ar`, some console requests show Arabic translations. See this example when running queued jobs:

```shell
» docker-compose exec container_name ./craft queue/run --verbose
2021-03-30 23:54:00 [pid: 5327] - Worker is started
2021-03-30 23:54:00 [5225] جاري تحديث فهارس البحث (attempt: 1, pid: 5327) - Started
2021-03-30 23:54:00 [5225] جاري تحديث فهارس البحث (attempt: 1, pid: 5327) - Done (0.055 s)
2021-03-30 23:54:00 [pid: 5327] - Worker is stopped (0:00:00)
```

That will even get worse if the system/terminal does not fully support Arabic output.

![screenshot-20210331-000317](https://user-images.githubusercontent.com/542855/113056489-86677500-91b4-11eb-80c1-7cfdf309099e.png)

Therefore, for the console requests, it will be easier to read and interpret if it's in English but the `defaultCpLanguage` is controlling that in my case.

Is it possible to have a separate config for console requests language? e.g. `defaultConsoleLanguage`

**Comment by brandonkelly** [comment]
That’s pretty awkward, since the vast majority of strings in console commands aren’t actually translatable to begin with. So as of Craft 3.7, the `defaultCpLanguage` setting will no longer have any effect on console commands.
