### ISSUE TITLE
Restored, soft-deleted entries, deleted from user deletion prompt, are permanently deleted with gc

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#7751]
### Description
A user was deleted and the "Delete their content" was mistakenly selected. This was remedied by restoring those entries, as they were soft-deleted. Now, ~30 days later, the entries are gone. Given the time frame, garbage collection was a suspect, because `softDeleteDuration` is 30 days by default.

It looks like this is the same issue posted 7 months ago: https://craftcms.stackexchange.com/questions/36045/craft-cms-entries-disappearing

### Steps to reproduce

1. Delete a user, choosing to "Delete their content" when prompted.
2. Find one of the soft-deleted entries and restore it
3. run `craft gc --delete-all-trashed=1`
4. Weep, as you find your entries have been permanently deleted.

### Additional info

- Worth noting that it seems things were only deleted from `entries` table, `content` and `elements` were in-tact.
- I tested this specifically with entries, not sure if other element types are affected.

- Craft version: 3.6.11.2

**Comment by twosixcode** [comment]
Definitely of note as Tim mentioned...

> Now, ~30 days later, the entries are gone.

So in steps to reproduce #3, the `--delete-all-trashed=1` is not necessary if you are past the 30 day `softDeleteDuration`.

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
We just released Craft 3.6.12 with the fix for this.
