### ISSUE TITLE
[FR] Reference field for queue tasks

### ISSUE THREAD

**Issue by naboo** [craftcms/cms#7754]
### Description

I'm using the queue in Craft for multiple things within my own plugins and/or modules. It would be nice to have some sort of "reference" field in the queue table in which you basically could add any type of reference id/tag/value you like in order to keep track of your own queue items.

**For example** "_What queue tasks do I have for related item Y?_". Where related item could be an entry, a commerce order, some other type of table with items in your own implementation (I have a table with customers I send follow-ups to, would like to know what queue tasks I have currently for each customer).

**Comment by brandonkelly** [comment]
Agree it would be nice, but it’s not possible unfortunately, since not all queue drivers have a way of looking up specific messages in the queue. And if it were to happen, it would need to be implemented by yii2-queue and each of its drivers, not Craft.

**Comment by naboo** [comment]
Ah that's to bad, but understand what you mean.

I guess my own reference table will have to do for now :)

Den tors 1 apr. 2021 15:18Brandon Kelly ***@***.***> skrev:

**Comment by naboo** [comment]
If anyone ever finds this and need a solution I did a quick-n-dirty variant by adding a reference tag to my job description like `[12345]` then I can query the queue table and search for the specific tag to pull the jobs I need to display/show somewhere else.

**Comment by brandonkelly** [comment]
@naboo Wouldn’t recommend doing that anywhere besides in a project-specific module, where you have control over the queue driver. Only the built-in DB queue driver uses that DB table; other drivers (like Redis) will store queue messages elsewhere.

**Comment by naboo** [comment]
@brandonkelly yes true, this is only for the db queue driver.

Den ons 7 apr. 2021 00:36Brandon Kelly ***@***.***> skrev:
