### ISSUE TITLE
Live Preview scrolls to last position, not scrolling to change

### ISSUE THREAD

**Issue by gavinplatt** [craftcms/cms#7757]
### Description

When editing an entry in Live Preview mode, the preview pane reloads and scrolls to the last scroll position rather than to the changed element.

### Steps to reproduce

1. Open an entry in Live Preview
2. Make a change to any content. Preview pane reloads, no scrolling takes place.
3. Scroll half way down the page to position X
4. Make a change to an element at the top of the page. Preview pane reloads, then scrolls down to position X

### Additional info

- I'm seeing this in Safari, Chrome and Firefox on Mac, not tested in others.
- It happens on a reduced test case where the entry has just two standard Craft plain text fields, with a stripped back twig template where no JS or CSS is being loaded
- All plugins disabled
- The site isn't multi site
- It happens with drafts and with the published entry

- Craft version: Pro 3.6.11.2
- PHP version: 7.3.27
- Database driver & version: MySQL 5.7.32
- Plugins & versions: All removed for testing

**Comment by brandonkelly** [comment]
This is expected; Craft doesn’t actually know where anything is positioned on your page, so the best we can do is maintain the previous scroll position.
