### ISSUE TITLE
Feature Request: Control of position of new entries in Structure Section Types

### ISSUE THREAD

**Issue by johnfmorton** [craftcms/cms#7759]
### Description

When adding entries to a section of structured entries, new entries are currently appended to the end of the structured list of entries. When creating a section, I would like the option to choose between appending new entries to the front or end of the list of entries.

**Comment by lindseydiloreto** [comment]
It would be great if there were some sort of config setting to choose "add to top" vs "add to bottom". Not sure if that config setting would be better suited for the `config/general.php` file, or for each Structure individually.

**Comment by brandonkelly** [comment]
This was already requested by #870. Just resolved for 3.7 – see https://github.com/craftcms/cms/issues/870#issuecomment-812743064.

**Comment by aelvan** [comment]
Was this resolved with the context menu changes only, or was a setting also added for the default behaviour?

**Comment by brandonkelly** [comment]
Just the new action options. So I guess I will reopen this if there’s still a need for the section setting. Not sure how I feel about it though… the inconsistent behavior from one section to the next could be confusing.

**Comment by johnfmorton** [comment]
A per-section setting seems logical to me. I see ordering-priority as simply another option when modeling content to suit the needs of a site or app.

**Comment by mmikkel** [comment]
> Not sure how I feel about it though… the inconsistent behavior from one section to the next could be confusing.

Structures can be used to represent vastly different kinds of content, even within the same build. If prepending new entries feels like _the most natural or expected_ behaviour for a particular section, I doubt authors will be bothered by that inconsistency.

**Comment by lindseydiloreto** [comment]
I fully agree with @johnfmorton and @mmikkel, a section-level setting makes perfect sense to me. We can't guarantee that all sections in a site will require the same behavior.

**Comment by brandonkelly** [comment]
Would you agree that the setting should be applied in each of these cases?

- When creating a new entry via the “New entry” button
- When creating a new entry via the “Create a new child entry” action
- When repositioning an entry via its “Parent” field on the Edit Entry page

**Comment by lindseydiloreto** [comment]
1. Yes, absolutely.
2. Yes, probably, though it's an interesting question. It's probably easiest to have the logic "trickle down" to each branch, and theoretically it's a bit easier to rearrange a subset of entries within a given branch.
3. Yes, probably. I believe all of the same logic from 2 applies here as well, since it's a similar Parent/Child relationship.

**Comment by mmikkel** [comment]
The first two, definitely. If a section is configured to prepend new entries, I think it's reasonable to assume that authors and devs will expect this behaviour to apply regardless of level.

The third one is a bit more awkward, though I'd probably vote for keeping the behaviour internally consistent – i.e. if Craft at any time, for any reason, needs to insert an entry into a structure or child element hierarchy without a known position, it should put it either first or last depending on the setting.

Not completely sure though. I do think the first two use cases are probably the most prevalent, and it could make sense to only have the setting apply for new entries as well.

**Comment by brandonkelly** [comment]
Just added this for 3.7, for categories and entries. Went with a “Yes” for each of the cases [above](https://github.com/craftcms/cms/issues/7759#issuecomment-814339106).
