### ISSUE TITLE
Emails delivered as text when sent via the console

### ISSUE THREAD

**Issue by dralshehri** [craftcms/cms#7761]
### Description

Emails sent via the control panel are delivered correctly as HTML, however, when they are sent using the Craft console, they are delivered as text.

### Steps to reproduce

1. Send test email using the control panel
2. Send test email using the console command `./craft mailer/test`

### Additional info

- Craft version: 3.6.11.2
- PHP version: 7.4.16

**Comment by brandonkelly** [comment]
Just tested this locally and wasn’t able to reproduce. The email came in as HTML

Please email support@craftcms.com and we can help you further from there.

**Comment by dralshehri** [comment]
My bad. It was a module registering a twig filter used in email templates but the controller namespace was not set properly for console requests. Problem solved. Thanks!
