### ISSUE TITLE
Before send password reset email event

### ISSUE THREAD

**Issue by mattsbanner** [craftcms/cms#7781]
Could we get an event that fires before sending a users password reset email please.

We have a plugin providing SSO functionality via a custom CRM and OAuth2. We have kept things native to Craft by using Craft user accounts and synchronising the data from the CRM. Users should be unaware of having two accounts.

I need to block some users from requesting password resets on the control panel.

Thanks 😄

**Comment by brandonkelly** [comment]
You can already do this using the `EVENT_BEFORE_SEND` event on the mailer.

```php
use craft\elements\User;
use craft\mail\Mailer;
use craft\mail\Message;
use yii\base\Event;
use yii\mail\MailEvent;

Event::on(Mailer::class, Mailer::EVENT_BEFORE_SEND, function(MailEvent $event) {
    // Is this a forgot_password message?
    if ($event->message instanceof Message && $event->message->key === 'forgot_password') {
        // Is it being sent to a user we don't want to receive it?
        /* @var User $user */
        $user = $event->message->variables['user'];
        if ($user->isInGroup('ssoUsers')) {
            // Prevent the email from being sent
            $event->isValid = false;
        }
    }
});
```

Replace the `isInGroup()` check with whatever the appropriate code is to determine whether the user should receive the email or not.

**Comment by mattsbanner** [comment]
Awesome, thanks Brandon! 😄
