### ISSUE TITLE
Structure rebuild issues

### ISSUE THREAD

**Issue by michaelroper** [craftcms/cms#7784]
After having issues with my structures a few weeks back (#7699), I was able to get them back into shape by using `./craft utils/repair/section-structure pages`, and then rearranging them how they were originally.

Now similar issues have started reoccurring,  including in another structure as well, with entries missing and others showing under entries different to their assigned parent. I repaired the structure, but this completely messed the structure order up again, with entries all over the place. After I had rearranged them again, I ran the repair command with the `--dry-run` switch to check if it was okay now, but it looked like it was still going to mess things up again!

So, my question is - what could be the cause of my structures getting so messed up under the hood all the time? Is there a way for me to fix them once and for all?

### Additional info

- Craft version: v3.6.11.2
- PHP version: 7.4.16
- Database driver & version: postgres 12

**Comment by brandonkelly** [comment]
Have you paid attention to when exactly this happens?

Do you have any custom scripts (e.g. within a module) that is working with entries in some way? Any plugins installed that could be interfering?

**Comment by michaelroper** [comment]
I haven't noticed specific times/events as yet, I'm just getting random reports from my content editors when it plays up. 

No custom module code doing anything.. some plugins, but not that I can think would be interfering. Happy to send through db/composer/yaml files if that might help...

Once thing that I'm wondering if it might be related - I've had `maxRevisions` set to 3, and have noticed some [timeout/deadlock issues](https://discord.com/channels/456442477667418113/456442867163070466/830317360895361035) when saving entries. After searching through some older issues today, I have set that to 0 now, and will prune nightly instead. That seems to have solved the timeout issues..

**Comment by brandonkelly** [comment]
Can you ask your content editors to try to keep track of what they were doing immediately before they notice an issue? Without more context there’s just not enough to go on here.

**Comment by michaelroper** [comment]
While I can't quantify exactly, I'd say that it's most likely been when they are editing multiple entries in quick succession, and because I had `maxRevisions=3`, we were having a lot of "Pruning extra revisions" tasks filling up the queue and sometimes failing. After watching the process list on the Postgresql server, and seeing this process seemingly ongoing, this makes me think they could be related to having maxRevisions set too low.

https://user-images.githubusercontent.com/60287/114312664-fd422d80-9b25-11eb-8e16-4a7fac8dc2be.mov

I ended up sending through db+config to support@ - I'm interested to see if you might be able tell why, when i've _just_ repaired and reordered the structure, if I run the repair command again as a dry run, it reports like its going to mess up the order again?

**Comment by brandonkelly** [comment]
Sounds like this traces back to a bug introduced in 0724f64e501006a10e98d42ebe7ebae339c176e1 when fixing #7699. Sorry about that. Fixed now, and will get a release out later today.

**Comment by michaelroper** [comment]
Hah, bitten by my own bug report!  Thanks Brandon (and @olivierbon!), appreciate the fix.

**Comment by brandonkelly** [comment]
We just released Craft 3.6.12 with that fix. Thanks for the help :)
