### ISSUE TITLE
Craft Transform Quality issues

### ISSUE THREAD

**Issue by ljclark** [craftcms/cms#7785]
### Description

After updating to the latest version of Craft (3.6.11.2) from 3.6.10, I've noticed that any images being run through a transform are being output at a lower quality, despite having the quality setting at 100. It's particularly noticable on images with text and intricate illustrations.

Even on a transform where the crop is the same size as the raw image, it's effecting the quality, making all images blurrier than the original - I'm pretty sure it's never done this previously. 

### Steps to reproduce

1. Output a raw, uncropped image on template
2. Output the same image below it, but with a transform applied, set the quality to 100. 
3. Compare the difference. 

I actually noticed this from Image Optimise, thinking it was an issue with that, but it's happening outside of that too. 

### Additional info

- Craft version: Craft Pro 3.6.11.2
- PHP version: 7.3.27
- Database driver & version: MySQL 5.7.33
- Plugins & versions:

![Screenshot 2021-04-10 at 14 23 41](https://user-images.githubusercontent.com/8060816/114271249-5c118500-9a08-11eb-9289-50f132ebd8e6.png)

**Comment by brandonkelly** [comment]
Did anything change on the server? Perhaps you switched from ImageMagick to GD, or updated PHP / ImageMagick?

**Comment by ljclark** [comment]
Nope, not touched anything on the server or anything like that.

**Comment by khalwat** [comment]
Possible it's related to https://github.com/craftcms/cms/issues/3164 ?

**Comment by ljclark** [comment]
Andrew's nailed it - it needed `'maxCachedCloudImageSize' => 3000` setting due to me using S3 for the image storage.

Cleared caches, regenerated the transforms and all is well in the world. 

Thanks chaps.

**Comment by khalwat** [comment]
![blind-squirrel](https://user-images.githubusercontent.com/7570798/114277551-a3444980-99f9-11eb-8266-fefce12d4ef8.jpg)
