### ISSUE TITLE
[FR] Option to disable URL for selected entries in Structure

### ISSUE THREAD

**Issue by FoxtrotCZ** [craftcms/cms#7793]
### Description

Let's say I have Structure for my products. One product entry = 1 page on website.
I set Entry URI Format and Template so the products have URL and template.

I create following Structure entries:

- Base
 - - Category A
 - - - Product 1
 - - Category B
 - - - Product 2
 - - - Product 3

Base entry contains content shared by all products.
Categories contain content shared by products in its category.

Publicly I want to show only the products. The products pull content from Base and Categories (from its ancestors).
Base and Categories shouldn't be publicly accessible by URL.

Right now I can disable Base and Categories but then I cant pull content from them...

I guess this would be good addition when you merge Structures, Categories and Tags. #1949 

Thanks.

**Comment by brandonkelly** [comment]
You can already do this, by wrapping your section’s Entry URI Format in a condition, to prevent it from outputting anything for first and second-level entries:

```twig
{% if level > 2 %}...{% endif %}
```
