### ISSUE TITLE
General Observation and Feedback

### ISSUE THREAD

**Issue by 23d1** [craftcms/cms#7796]
### Description

Recently, Craft 3 has been very robust, almost as robust as Craft 2.6+. I have to say though, that at times, every update broke something across multiple websites for me. It began to be so frustrating that I just froze the code and addressed whatever I could personally on the front-end. I'm not sure what the reason for this is. I do appreciate fast and cutting edge updates, but now with the latest update yesterday some admin panel javascript is broken, and a simple composer version rollback is impossible. Some times database sync and backups are hours apart, and that can be the difference between life and death (not literally of course), so it feels like being back in beta when this happens. Is there any LTS plan or something in place to not completely break ecommerce sites which results in thousands of dollars of loss every 30-60 minutes, whenever there's an update? In the past, I've always felt that an update is completely safe unless there's that red warning text. Now we're back to 3.0 beta days. Sorry, this is part vent and part request for proper QA before pushing updates. I realize I am probably going about it the wrong way in some aspects, but do you at least acknowledge the inherent frustration with this?

**Comment by brandonkelly** [comment]
Sorry you had an issue. It can certainly be frustrating when an update doesn’t go smoothly. We do our own internal QA, and didn’t find any JavaScript errors on our end. Did you happen to catch the error? Perhaps you were hitting #7705 – a conflict between Craft 3.6.11+ and the Neo plugin (fixed in Neo 2.9.6)? Other than that we haven’t received any reports of new JS errors recently.

**Comment by 23d1** [comment]
Thanks Brandon, I did notice the Neo issue as well, and it seems that my own internal stuff had similar issues. Looking at the JS for Neo helped me solve those issues, thankfully. So it seems to be solved. Thanks again, and thanks for an amazing product, there's no going back once you go Craft. :)
