### ISSUE TITLE
Failed to instantiate component or class "modules\SiteModule\SiteModule" while upgrading craft to 3.6

### ISSUE THREAD

**Issue by chandamotiyani** [craftcms/cms#7798]
I tried to update the craft version from 3.5.19.1 to 3.6.x but found composer and PHP version were needing to be upgraded too.

1. I edited php version in composer.json file from 7.2 to 7.2.5
2. Upgraded composer version from 1.10.7 to 2.0.12
3. made the project psr4 compliant by changing the directory and namespaces to pascal case - did this because any composer command was skipping files because of the psr4 compliant
4. ran composer dump-autoload (this time worked fine)
5. ran php craft update all - this is throwing the error attached and have attached psr4 related stuff too
<img width="1248" alt="Screen Shot 2021-04-14 at 11 39 03 am" src="https://user-images.githubusercontent.com/16190427/114660279-2cc68500-9d34-11eb-8381-e1889172d365.png">
<img width="1280" alt="Screen Shot 2021-04-14 at 10 21 59 am" src="https://user-images.githubusercontent.com/16190427/114660286-318b3900-9d34-11eb-9e93-460ac823b701.png">

Also sending composer.json file too.
[composer.json.zip](https://github.com/craftcms/cms/files/6308439/composer.json.zip)

**Comment by brandonkelly** [comment]
Looks like we’re helping you in support – we’ll continue to help from there.
