### ISSUE TITLE
Server Error when Category is added to Table Columns in the Entry Overview

### ISSUE THREAD

**Issue by vasuhooda** [craftcms/cms#7799]
### Description

1. Create a page, leave the category empty 

![Screenshot 2021-04-14 at 12 14 42](https://user-images.githubusercontent.com/8009769/114694945-5921d780-9d1b-11eb-8bdc-f0fb7da441e2.png)

2. Add category to table column 
![Screenshot 2021-04-14 at 12 14 25](https://user-images.githubusercontent.com/8009769/114694987-63dc6c80-9d1b-11eb-87a4-e30560c7f26b.png)

3. Internal Server Error, Client unable to access entries 
![serverfehler](https://user-images.githubusercontent.com/8009769/114695088-8078a480-9d1b-11eb-8dd6-5c4e6e1659c7.png)

### Additional info

- Craft version: 3.5.12.1

**Comment by brandonkelly** [comment]
Hi @vasuhooda, as a starting point, please update to the latest version; 3.5.12.1 is several releases behind. Also be sure to update any plugins you may have installed.

If you’re still seeing this error after everything, try enabling [Dev Mode](https://craftcms.com/docs/3.x/config/config-settings.html#devmode), open your browser’s Network tool, and post the response body from the failed Ajax request that is triggering this error.

**Comment by vasuhooda** [comment]
@brandonkelly the issue persists even after updating to Craft CMS 3.6.15. Can you please check the problem

**Comment by brandonkelly** [comment]
@vasuhooda Can you please send a database backup and your `composer.json` + `composer.lock` files over to support@craftcms.com? We can try to reproduce from there.
