### ISSUE TITLE
CMS Backend Version history - Incorrect text in German

### ISSUE THREAD

**Issue by vasuhooda** [craftcms/cms#7800]
### Description

The CMS has a  problem with the version history. The word "am" is displayed twice! Here is a screenshot of the problem.

![Bildschirmfoto_2021-03-15_um_11 08 16](https://user-images.githubusercontent.com/8009769/114695566-13194380-9d1c-11eb-93ae-528d9b260122.png)

- Craft version: 3.6.11.2

**Comment by brandonkelly** [comment]
Looks like that is coming from the German translation for `saved {timestamp} by {creator}`. Please feel free to provide an alternate translation in CrowdIn: https://crowdin.com/translate/craft-cms/264/en-de#290102
