### ISSUE TITLE
Database backup: .my.cnf world readable

### ISSUE THREAD

**Issue by d--j** [craftcms/cms#7801]
Why do you change the file mode of `.my.cnf` to`0644`? 
https://github.com/craftcms/cms/blob/43dc0a6f1d406abfd6f33fa2d9ffb1a49e6d5257/src/db/mysql/Schema.php#L393

It should be sufficient to create it with `0600` mode. If users set the general config `backupCommand` (including `sudo` or something) then `getDefaultBackupCommand` never gets called and thus the `.my.cnf` file never gets created anyways.

Also you probably should either use (a) [`umask`](https://www.php.net/manual/en/function.umask.php)`(0077)` or (b) create an empty file, `chmod` this file to `0600` and append the sensitive information to it. 
Otherwise the code is susceptible to race condition attacks. 

https://tldp.org/HOWTO/Secure-Programs-HOWTO/avoid-race.html

**Comment by angrybrad** [comment]
> Why do you change the file mode of .my.cnf to 0644?

Mainly because that's why MySQL recommends: https://dev.mysql.com/doc/mysql-secure-deployment-guide/5.7/en/secure-deployment-permissions.html

![CleanShot 2021-04-14 at 16 21 19@2x](https://user-images.githubusercontent.com/61869/114792707-b2026780-9d3d-11eb-8b2f-f58f425988c4.png)

And that seems to be the general consensus of what it should be set to online from my research.

I'll have to do some testing on what changing it to 0600 might mean. Maybe none since PHP is the one both creating the temp my.cnf file as well as executing `mysqldump` from the CLI.

**Comment by d--j** [comment]
`/etc/my.cnf` is the main MySQL config file and does not hold any sensitive information (normally). The `.my.cnf` that CraftCMS creates stores the database password and should IMHO not be world-readable.

If you have access to a debian based system, have a look at the file system permissions of `/etc/mysql/debian.cnf` (it holds the password for the debian maintenance user)
```
$ ls -lah /etc/mysql/debian.cnf 
-rw------- 1 root root 317 Apr 13 22:57 /etc/mysql/debian.cnf
```

**Comment by angrybrad** [comment]
Gah, my bad. Will do some testing.

**Comment by leevigraham** [comment]
> The .my.cnf that CraftCMS creates stores the database password and should IMHO not be world-readable

Craft creates a `.my.cnf` file?

**Comment by leevigraham** [comment]
Should `_createDumpConfigFile` create a dump file in `storage/runtime` or something relative to craft site so it doesn't potentially conflict with existing files?

**Comment by d--j** [comment]
> Should `_createDumpConfigFile` create a dump file in `storage/runtime` or something relative to craft site so it doesn't potentially conflict with existing files?

Yes, that would be better, I think. I had a look at this code in the first place, because multiple parallel database backups (of different CraftCMS installs) on the same server were writing `/tmp/.my.cnf` and thus the one backup broke the other one. I fixed this with changing the `TMPDIR` environment variable to a install-uniq directory.

**Comment by angrybrad** [comment]
@leevigraham @d--j It actually used to write to `storage/runtime` and we changed it to sys temp dir here: https://github.com/craftcms/cms/commit/550da44fa471f41d8411e5608ceb11a7403c3c1e

I don't remember the specifics of the original issue, but will at this again.

**Comment by angrybrad** [comment]
@d--j @leevigraham thanks for that... both of the issues should be resolve for the next release now.

**Comment by brandonkelly** [comment]
Craft 3.6.12.1 is out now with the fix for this.
