### ISSUE TITLE
Custom site fields

### ISSUE THREAD

**Issue by TomDeSmet** [craftcms/cms#7804]
### Description
I think it would be nice to be able to add custom fields to sites.

### Use cases
- Select field to choose a theme
- Asset field to choose a logo

This would allow us to re-use templates for small changes to a site instead of having to create templates per site.

**Comment by michtio** [comment]
@TomDeSmet this can be done with translatable global fields.

**Comment by TomDeSmet** [comment]
I’ve chosen that route also for now. But it would be nice to have the option. We’re able to add fields to pretty much everything in Craft. So why not sites?

Maybe we could add fields to site groups because in my case every site group has its own logo. Sites are just the language variants. 

There’s always another way to go about it but custom fields is what makes craft so great. Everything is an element that can have a custom field so this would feel natural  for craft to be able to do.

**Comment by brandonkelly** [comment]
It wouldn’t be possible to do this, since Craft needs to fetch the sites **before** it can start querying for elements.
