### ISSUE TITLE
Clickable UI components now get an **ugh**gly outline during click

### ISSUE THREAD

**Issue by bencresty** [craftcms/cms#7805]
### Description

A lot of (clickable) components suddenly (since last version?) have a blue outline when clicking (active state) on it where it doesn't fit and looks uh... not meant to be... ouf of place... (kggakgkg... ugly... uhum... dkkddk), so I'm sure this is a bug.

Hope this change can be reversed sooner rather that later, the UI was so pretty as it was!! 

### Steps to reproduce

1. Use the CMS
2. Click a button 

Like one of these

![image](https://user-images.githubusercontent.com/69322733/115035649-14d63900-9ecd-11eb-8771-f5a2fd0e6403.png)

![image](https://user-images.githubusercontent.com/69322733/115036313-b2ca0380-9ecd-11eb-9a30-9fe9cf62d7da.png)

![image](https://user-images.githubusercontent.com/69322733/115036367-bd849880-9ecd-11eb-920a-39c6838486ce.png)

![image](https://user-images.githubusercontent.com/69322733/115036412-c9705a80-9ecd-11eb-8020-143db4d76bba.png)

![image](https://user-images.githubusercontent.com/69322733/115036520-e3aa3880-9ecd-11eb-9f47-84a191c389a7.png)

### Additional info

- Craft version: 3.6.12
- PHP version: 7.4.9
- Database driver & version: -
- Plugins & versions: -

**Comment by Wiejeben** [comment]
Become educated https://craftcms.com/accessibility/designing-custom-focus-indicators

**Comment by mmikkel** [comment]
Improving accessibility for everyone is a good thing, in my opinion.

If the outlines really bother you, they should be easily removed with a bit of custom CSS (for example using the [Control Panel CSS](https://plugins.craftcms.com/cp-css) plugin).

**Comment by bencresty** [comment]
You guys can't be serious. Really? What was wrong with the normal interface? Where there any complaints?

What does it add to accessibility when you see a highlight around a button only after you just clicked it? I don't see any point in compromising a layout with this blue glow that is not at all in line with the layout.

Next to accessibility there's also the User Experience, which is pretty important. And it feels broken now as this style fits not at all with the current design and gets all bells ringing saying; something is wrong here with the CSS. To than tell me to switch it off by using 'some custom css' is the other way around. It's like using text links from the 90s.

I'd rather see Craft fixing some front end issues to be honest, as when debugging with the live preview I get several error messages every time by Promise errors that aren't catched, stuff that cannot be found and months after asking to fix the 'duplicate menu button' issues in the console it's still not fixed, causing the console to be full of messages and errors of Craft, which is disturing when trying to test and debug own code while working in live preview.

Sorry, but this change is totally weird to me and ruins the user experience. And for what?

**Comment by khalwat** [comment]
I think they will be addressing this in https://github.com/craftcms/cms/issues/7790

I agree, though, make it available for people who need it, but let people who don't be able to turn it off

**Comment by bencresty** [comment]
> I think they will be addressing this in #7790
> 
> I agree, though, make it available for people who need it, but let people who don't be able to turn it off

Thanks!

Although I still feel the same, I should have lowered my voice a little in my previous message and chosen my words better. Especially on github. This way it didn't serve anybody, so sorry for that. I like Craft a lot, especially its user interface, and this fell to the wrong side for me and I really thought it was a bug, so the reactions here really surprised me. I just couldn't believe it.

As a designer and front end developer I'd really stick with the flat style and rethink the style as it is now. Blue doesn't fit directly well around a red button for instance. That's making colors interact. A blue shade doesn't work well in a flat style layout either most of the times. And borders around things that normally are borderless may perhaps let things stand out more, but is messing the style of the components, and at what cost?

Anyway, these were my 2cts. Way too many words by me here, but I am just very surprised by both the decisions and the reactions. But I can't change it.

When there would be a setting to turn it off at least that would really help!

Have a nice weekend!

**Comment by missmatsuko** [comment]
I think it's been covered by now, but we'll be adding a user preference to reduce the outline visibility.

**Comment by bencresty** [comment]
@missmatsuko Thanks!

**Comment by brandonkelly** [comment]
Worth mentioning here that a new “Reduce focus visibility” user preference has been added for 3.7 (#7790).
