### ISSUE TITLE
phperrors.log does not mask sensitive data

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/cms#7806]
### Description

I noticed that the `$_SERVER` dump usually masks sensitive data such as the database password in the log files, however this isn't the case for `phperrors.log`.

### Additional info

- Craft version: 3.6.12
- PHP version: 7.4.16
- Database driver & version: MySQL 5.7.32

**Comment by brandonkelly** [comment]
Craft doesn’t have any control over what gets written out there, unfortunately; it just has a say in _where_ they should be stored, via the `error_log` INI setting.

You can tell Craft to stop logging PHP fatal errors altogether, though. Add this to `index.php`:

```php
define('CRAFT_LOG_PHP_ERRORS', false);
```

And make sure that  `log_errors` isn’t enabled in your `php.ini` file.

If you do this, you should have some other way to capture fatal error logs, such as via [Sentry](https://sentry.io/welcome/) or [Papertrail](https://www.papertrail.com/).
