### ISSUE TITLE
Restricted logged in user group for franchise can see other franchise group asset folders

### ISSUE THREAD

**Issue by bradleyw92** [craftcms/cms#7814]
### Description

Restricted logged-in user groups for a franchise can see other franchise group asset folders.

While you can't see their assets the main base folder appears which isn't ideal.

Am I missing something here or is there a bug?

<img width="890" alt="Screenshot 2021-04-20 at 21 09 38" src="https://user-images.githubusercontent.com/55581484/115457725-c900f800-a21c-11eb-9b49-63740d6ece74.png">

### Steps to reproduce

1. Login on a multi-site that can only upload to one asset folder directory such as it (Italy)
2. Go to assets
3. You'll see different folders appear despite the user group assets are restricted to upload to one directory such as it

### Additional info

- Craft version: 3.6.12
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
The _field_ is restricted to that single folder, but users don’t have folder-level permissions; just volumes.

**Comment by bradleyw92** [comment]
Forgive me for not understanding but how would this be resolved?

**Comment by brandonkelly** [comment]
If you want users to have permission to view assets, but you only want them to have access to a single site’s assets, then you will need to create a separate Volume for each site, and assign users to the appropriate volume(s).

Note that your authors will still be able to work with your Assets fields, even if they don’t have view permissions for assets. So simply removing those permissions may be an option for you.
