### ISSUE TITLE
Craft Update from 3.4 to 3.6 Content Migrations reapplied

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#7818]
### Description

Edit:
An easy "fix" is to run `php craft migrate/all --noContent` but I'm not sure if that's intended or not. 
I was not able to find something in the update notes or changelog so I guess it's rather a bug than a layer8 issue.
If that's the case, please stop reading and just close the issue.

I'm trying to update from Craft 3.4 to the latest 3.6 but all my content Migrations run again.

The ckeck to grab all pending migrations will run **before** Craft internals migrations are done, so by the time Craft fetches the pending content migations my table looks like  

![image](https://user-images.githubusercontent.com/6122122/115527697-96ddad80-a291-11eb-9dd8-6642c12a0049.png)

Your [MigrationQuery](https://github.com/craftcms/cms/blob/develop/src/db/MigrationManager.php#L463) will then go into this branch 

```php
if ($this->db->columnExists($this->migrationTable, 'type', true)) {
    $query = (new Query())
        ->select(['name', 'applyTime'])
        ->from([$this->migrationTable])
        ->orderBy(['name' => SORT_DESC]);

    if ($this->track === 'craft') {
        $query->where(['type' => 'app']);
    } else {
        $pluginId = null;
        if (strpos($this->track, 'plugin:') === 0) {
            $pluginId = (new Query())
                ->select(['id'])
                ->from([Table::PLUGINS])
                ->where(['handle' => substr($this->track, 7)])
                ->scalar();
        }
        if ($pluginId) {
            $query->where(['pluginId' => $pluginId]);
        } else {
            $query->where(new Expression('1 = 0'));
        }
    }

    return $query;
}
```
resulting in the following Query

```SQL
SELECT `name`, `applyTime`
FROM `migrations`
WHERE 1 = 0
ORDER BY `name` DESC"
```
because pluginId is null (cause the track is set to `content`) -> thus it doesn't find any migrations in the table and will show all of them as pending.

### Steps to reproduce

1. Update from Craft 3.4 to Craft 3.6
2. see all content migrations will run again, resulting in errors

**Comment by brandonkelly** [comment]
Thanks for reporting that. Just fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.5.12"` (or `"3.5.13.x-dev as 3.5.12"` if you’re [already running that branch](https://github.com/craftcms/cms/issues/6226#issuecomment-820739932)) and run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.6.12.1 is out now with the fix for this. Thanks again!
