### ISSUE TITLE
[enhancement] resolve aliases in preview URIs or resolve queries in preview target URIs

### ISSUE THREAD

**Issue by olets** [craftcms/cms#7820]
### Description

I frequently want to say "section 1 is a preview target for section 2".

I'd be happy to be wrong but as far as I can tell my options are 

- set a string URI for section 1, and in section 2 create a preview target pointing to that same string
- set a string URI for section 1, create an alias with that string as its value, and in section 2 create a preview target using that alias as the URI

Would be great to set that value once. I can see this working two ways: 

1. Support queries in section URIs
    a. Section 1 handle 'mySingle'
    b. Section 2 URI: `{craft.entries().section('mySingle').one().url}` or similar
1. Support aliases in preview URIs
    a. `@myUri` = 'my-uri'
    b. Section 1 URI:  `@myUri`? `{@myUri}`?
    c. Section 2 preview target: `@myUri`

**Comment by brandonkelly** [comment]
Both of those are already possible :)

**Comment by olets** [comment]
On what version @brandonkelly?

I'm on 3.6.12 and neither is possible. If you're sure they should I'll open a new bug report

**Comment by brandonkelly** [comment]
Sorry, to be clear, both of those are possible within preview targets’ URI settings.

Custom preview targets are only available in the Pro edition, so make sure you’re running that first.
