### ISSUE TITLE
Change "Save" button label on matrix block type edit modal

### ISSUE THREAD

**Issue by johandouma** [craftcms/cms#7822]
Craft CMS 3.6.12

When editing a matrix field in the CP, we have to click on the little cog to modify a block type. 

In the modal that appears, the main button says Save. But it doesn't save that change yet, it just applied the change to the type, but we still need to click the save button. 

I think "Set" or "Apply" would be a better label than Save for the button that appears in the little modal window.

**Comment by johandouma** [comment]
I just noticed that the word Apply is used in the Field Layout builder.

**Comment by brandonkelly** [comment]
Just made this change for the next release. Thanks for the suggestion!

**Comment by brandonkelly** [comment]
Craft 3.6.13 is out with this change.
