### ISSUE TITLE
Use the edited field label instead of the default label in the table headings

### ISSUE THREAD

**Issue by kevadamson** [craftcms/cms#7823]
![CLk31](https://user-images.githubusercontent.com/1021744/115690366-e76a0f00-a354-11eb-9936-5d423f4f0921.png)

^ This is what I've edited the label to be

![PHQTo](https://user-images.githubusercontent.com/1021744/115690419-f3ee6780-a354-11eb-9eff-183491ac97e0.png)

^ This is what shows as the table heading - Can it not show as 'Telephone'?

**Comment by brandonkelly** [comment]
This isn’t possible, unfortunately, since element index sources can contain elements with multiple different field layouts (e.g. a section with multiple entry types). So Craft wouldn’t know which one to go with.
