### ISSUE TITLE
Nested `relatedTo*` criteria is broken in GraphQL

### ISSUE THREAD

**Issue by joshuabaker** [craftcms/cms#7824]
### Description

Nested `relatedTo*` (e.g. `relatedToCategories`) in GraphQL currently causes an unknown property error.

```
Setting unknown property: craft\\elements\\db\\EntryQuery::relatedToCategories
```

[Original comment](https://github.com/craftcms/cms/issues/6745#issuecomment-824219507)

### Steps to reproduce

```gql
# This works
{
  categories(
    group: "news"
    relatedToEntries: {
      section: "articles"
      relatedTo: 1366
    }
  ) {
    title
  }
}

# This doesn’t
{
  categories(
    group: "news"
    relatedToEntries: {
      section: "articles"
      relatedToCategories: { id: 1366 }
    }
  ) {
    title
  }
}
```

### Additional info

- Craft version: 3.6.12

**Comment by andris-sevcenko** [comment]
Thanks! This has been fixed for the next release!

**Comment by joshuabaker** [comment]
@andris-sevcenko Not sure if there’s another regression here. This might be a different issue (or design), but posting here because it’s related.

See the following...

```gql
{
  first: entries(
    site: "testSite"
    section: "articles"
    relatedToCategories: [
      { id: [1366] }
      { id: [382] }
    ]
  ) {
    title
  }
  
  second: entries(
    site: "testSite"
    section: "articles"
    relatedTo: [1366, 382]
  ) {
    title
  }
}
```

```json
{
  "data": {
    "first": [],
    "second": [
      {
        "title": "Test Article"
      }
    ]
  }
}
```

Both should yield the same result, right?

**Comment by brandonkelly** [comment]
Craft 3.6.12.1 is out now with the fix for this. Thanks again!
