### ISSUE TITLE
Cache twig tag until DateTime not working compared to using for

### ISSUE THREAD

**Issue by RedLucas** [craftcms/cms#7826]
### Description
For the sake of sane debugging I'm using seconds, but the until function of the cache twig tag doesn't appear to be working. From what I can see in the documentation, `{% cache for 30 seconds %}` and `{% cache until now|date_modify("+30 seconds") %}` should give the same results. 

The until version never seems to work for me, does anyone else see this?

### Steps to reproduce

1. Get an uncached twig, with template caching on.
2. Add a timestamp within a `{% cache for 30 seconds %}` tag, refresh page and observe the timestamp updating every 30 seconds.
3. Try the same with `{% cache until now|date_modify("+30 seconds") %}` and observe that the timestamp never changes. 

### Additional info

- Craft version: Craft Pro 3.6.12
- PHP version: 7.3.25
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.6.12.1 is out now with the fix for this. Thanks again!
