### ISSUE TITLE
queries in preview target URIs not resolving

### ISSUE THREAD

**Issue by olets** [craftcms/cms#7831]
### Description

According to https://github.com/craftcms/cms/issues/7820#issuecomment-825957157 queries in the form `{<query>}`should work in preview target uris. That's not what I'm seeing.

Given a section with the handle `about` and another section with a preview target

```
{craft.entries().section('about').one().url()}
```

the query-based target

- does not show up in Preview list (unexpected according to https://github.com/craftcms/cms/issues/7820#issuecomment-825957157)
- does not show up in View list (unexpected according to https://github.com/craftcms/cms/issues/7820#issuecomment-825957157)

### Steps to reproduce

1. Use a query in a preview target uri
2. See that the preview target is not available

### Additional info

- Craft version: 3.6.12 Pro
- PHP version: 7.4.15
- Database driver & version: MySQL 5.7.29
- Plugins & versions:

<table class="data fullwidth fixed-layout" dir="ltr">
            <tbody>
                                    <tr>
                        <th class="light">Amazon S3</th>
                        <td>1.2.11</td>
                    </tr>
                                    <tr>
                        <th class="light">Asset Rev</th>
                        <td>6.0.2</td>
                    </tr>
                                    <tr>
                        <th class="light">Classnames</th>
                        <td>1.0.3</td>
                    </tr>
                                    <tr>
                        <th class="light">Command Palette</th>
                        <td>3.1.4</td>
                    </tr>
                                    <tr>
                        <th class="light">Redactor</th>
                        <td>2.8.6</td>
                    </tr>
                                    <tr>
                        <th class="light">Video Embed</th>
                        <td>1.2.2</td>
                    </tr>
                            </tbody>
        </table>

**Comment by Mosnar** [comment]
@olets This is kind of a funny one that I've run into before. What I've found is that using double curly-braces works, but single braces do not. For example, this URI works:

`{{ craft.entries.section('about').one().uri }}/{slug}`

But this does not:

`{craft.entries.section('about').one().uri}/{slug}`

The same is true for using `{{ alias('@whatever') }}`

**Comment by mmikkel** [comment]
The single-brace syntax is basically shorthand for rendering attributes on the `object` (usually an element, like an entry) in the current Twig context. So for something like an entry title field, the "object" will be an entry, and something like `{title}` will render the same thing as `{{ object.title }}` would.

Beyond that – for example to pull off a `craft.entries` query or rendering an alias – you need to use the standard double curly braces.

**Comment by olets** [comment]
Thanks @Mosnar and @mmikkel. 

In sum its:
- `{{alias(@…)}}`, `{{craft.entries.section('mySection').one().slug}}` in entry uris
- `@alias`, `$ENV_VAR`, `{objectAttribute}`, and `{{query}}` in preview targets

I've proposed a docs update in https://github.com/craftcms/docs/pull/203

**Comment by brandonkelly** [comment]
Doh… sorry @olets, I should have caught that you were using single braces in your example in #7820. We’ll review that PR.
