### ISSUE TITLE
entry uri format: space after `{{` or before `}}` errors

### ISSUE THREAD

**Issue by olets** [craftcms/cms#7834]
### Description

Leading and trailing spaces inside double curly braces in section URI formats are currently an error. They should not be—

```
{{ … }}
```

should be equivalent to

```
{{…}}
```

as in preview target URIs and as per [the docs](https://craftcms.com/docs/3.x/entries.html#entry-uri-formats) example `{{ slug }}`.

### Steps to reproduce

1. Set a section's URI format to `{{ craft.entries.one().slug }}` (leading and trailing internal space)
2. Save the section. See that it errors "URI is not a valid URI"
3. Set the URI format to `{{ craft.entries.one().slug}}` (leading internal space)
4. Save the section. See that it errors "URI is not a valid URI"
5. Set the URI format to `{{craft.entries.one().slug }}` (trailing internal space)
6. Save the section. See that it errors "URI is not a valid URI"
7. Set the URI format to `{{craft.entries.one().slug}}` (no internal space)
8. Save the section. See that it saves

and

1. Set a section's URI format to `{ slug }` (leading and trailing internal space)
2. Save the section. See that it errors "URI is not a valid URI"
3. Set the URI format to `{ slug}` (leading internal space)
4. Save the section. See that it errors "URI is not a valid URI"
5. Set the URI format to `{slug }` (trailing internal space)
6. Save the section. See that it errors "URI is not a valid URI"
7. Set the URI format to `{slug}` (no internal space)
8. Save the section. See that it saves

### Additional info

- Craft version: 3.6.12 Pro
- PHP version: 7.4.15
- Database driver & version: MySQL 5.7.29
- Plugins & versions:

<table class="data fullwidth fixed-layout" dir="ltr">
            <tbody>
                                    <tr>
                        <th class="light">Amazon S3</th>
                        <td>1.2.11</td>
                    </tr>
                                    <tr>
                        <th class="light">Asset Rev</th>
                        <td>6.0.2</td>
                    </tr>
                                    <tr>
                        <th class="light">Classnames</th>
                        <td>1.0.3</td>
                    </tr>
                                    <tr>
                        <th class="light">Command Palette</th>
                        <td>3.1.4</td>
                    </tr>
                                    <tr>
                        <th class="light">Redactor</th>
                        <td>2.8.6</td>
                    </tr>
                                    <tr>
                        <th class="light">Video Embed</th>
                        <td>1.2.2</td>
                    </tr>
                            </tbody>
        </table>

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.6.12.1 is out now with the fix for this. Thanks again!

**Comment by olets** [comment]
Thanks for letting me know!
