### ISSUE TITLE
Password toggle misalignment in RTL language login page

### ISSUE THREAD

**Issue by dralshehri** [craftcms/cms#7835]
### Description
When using an RTL language as default CP language e.g. Arabic, the password toggle (Show/Hide) in the login page is not aligned correctly.

This:

![screenshot_2021-04-26_18 29 20](https://user-images.githubusercontent.com/542855/116112004-d48e6c00-a6bf-11eb-8818-8aa8b8391da2.png)

Supposed to be like:

![screenshot_2021-04-26_18 31 44](https://user-images.githubusercontent.com/542855/116112048-de17d400-a6bf-11eb-96b9-b9ab90cca1e0.png)

### Steps to reproduce

1. Change the variable `defaultCpLanguage` to `ar`
2. Go to the login page and enter any password

### Additional info

- Craft version: 3.6.12

**Comment by brandonkelly** [comment]
Fixed for the next release. Thanks for reporting!

**Comment by brandonkelly** [comment]
Craft 3.6.12.1 is out now with the fix for this. Thanks again!
