### ISSUE TITLE
Let getSrcset make different aspect ratio images.

### ISSUE THREAD

**Issue by dande-sun** [craftcms/cms#7839]
### Description
Just a idea, Could we let function `getSrcset` receive other params ( height or ratio ). Like this
`{{ asets.getSrcset([{width:375,ratio:3/2},'768w','1600w']) }}`
or
`{{ asets.getSrcset([{width:375,height:375},'768w','1600w']) }}`.

And change here
https://github.com/craftcms/cms/blob/85e0b75b88db512d70a1914f5d2dfa7c6440e93a/src/elements/Asset.php#L1002
To
![图片](https://user-images.githubusercontent.com/26000245/116200050-71a5df00-a76a-11eb-8f24-54ce42a85527.png)

Here
https://github.com/craftcms/cms/blob/85e0b75b88db512d70a1914f5d2dfa7c6440e93a/src/elements/Asset.php#L1015-L1022
To
![图片](https://user-images.githubusercontent.com/26000245/116200214-a74ac800-a76a-11eb-95fe-1babbd7cee24.png)

Then we can transform to different ratio images.

**Comment by brandonkelly** [comment]
Yeah this is reasonable considering `getWidth()` and `getHeight()` already accept a `$transform` argument.

So just added a `$transform` argument to `getSrcset()` as well.

```twig
{{ asset.getSrcset(['768w', '1600w'], {
  width: 375,
  height: 375,
}) }}
```

In the meantime, you can accomplish the same thing by applying the transform to the asset before calling `getSrcset()`:

```twig
{% do asset.setTransform({
  width: 375,
  height: 375
}) %}

{{ asset.getSrcset(['768w', '1600w']) }}
```

(Transforms currently don’t support ratios. Feel free to request that in a separate issue.)

**Comment by dande-sun** [comment]
I hope getSrcset can be output `/heros/_375x375_crop_center-center_none/bg-hero-screenhandgesture_gradient.jpg 375w, /heros/_768xAUTO_crop_center-center_none/bg-hero-screenhandgesture_gradient.jpg 768w,/heros/_1600xAUTO_crop_center-center_none/bg-hero-screenhandgesture_gradient.jpg 1600w`, 
Most picture width/height is 16/9, But in mobile, I just need the picture of 1/1.

**Comment by brandonkelly** [comment]
@dande-sun That’s beyond the scope for `getSrcset()`. At that point you should just build out the `srcset` value yourself.

**Comment by brandonkelly** [comment]
Craft 3.6.13 is out with the new `$transform` argument.

**Comment by stephanedemotte** [comment]
Hello ! can we imagine the same thing in graphql ?
I'm trying `srcset(sizes: ["400", "600"])@transform(width: 600, height: 600)` but without success

**Comment by brandonkelly** [comment]
@stephanedemotte Can you please request that in a new [discussion](https://github.com/craftcms/cms/discussions/9930)?
