### ISSUE TITLE
Performing upgrade and new project config changes at the same time, causes the changes to disappear

### ISSUE THREAD

**Issue by peimansh** [craftcms/cms#7840]
### Description
I tried to upgrade from Craft 3.4.30 to 3.6.12. Also there were some new changes in the project.yaml file which are not present in database. Migrations ran, project.yaml file gets deleted, and the new project config folder which is created, doesn't include the changes that were supposed to be applied to the database, but instead new project config folder only shows the changes already in the database.

### Steps to reproduce

1. Install Craft 3.4.x
2. Do some config changes (So project.yaml file gets changed) in local dev
3. Get a database dump from production (which doesn't include the changes you made to project config), and try to upgrade Craft to 3.6.x
4. Project.yml file gets deleted and the diff changes that are not present in the database, do not get propagated in the new Project Config folder

### Additional info

- Craft version: 3.6.12
- PHP version: 7.4
- Database driver & version: PostgreSQL 11

**Comment by brandonkelly** [comment]
This is expected. Any time a project config change is made, all of the YAML files will be overwritten. And there’s only one thing that will prevent Craft/plugin migrations from making project config changes from migrations: `schemaVersion` values in the incoming YAML files that are equal to or greater than the  DB’s corresponding project config values. (See our docs on writing [Project Config Migrations](https://craftcms.com/docs/3.x/extend/project-config.html#project-config-migrations) for an explanation.)

So going forward, you will need to make sure that all incoming project config YAML changes have been applied _before_ updating Craft or plugins (unless those changes include `schemaVersion` updates, which will be the case when pushing an update and its related project config changes to a new environment.)
