### ISSUE TITLE
Is there a reason to have rows in searchindex with empty keywords?

### ISSUE THREAD

**Issue by GaryReckard** [craftcms/cms#7841]
### Description
On a site I am working on, the searchindex has > 9 million rows, and I noticed that almost 2/3 of those rows have an empty 'keywords' column. Is this necessary? Curious if it would be safe to clear those with empty keywords from the index, or if those actually serve a purpose, like if searching on a particular field for an empty string?

**Comment by brandonkelly** [comment]
It’s necessary for supporting the `-fieldHandle:*` syntax, which returns results where `fieldHandle` is empty.
