### ISSUE TITLE
Unable to perform nested queries in GraphQL

### ISSUE THREAD

**Issue by seb-jones** [craftcms/cms#7842]
### Description

I'm fetching entries via GraphQL, and I am trying to filter them so that only entries with a certain field within a specified set of ranges are returned. Here is a simplified version of my GraphQL query, with the tail omitted for brevity:

```graphql
query ProductQuery($price: [QueryArgument] = null) {
  products: entries(price: $price) {
    ... on products_product_Entry {
      id
      title
```

 I am able to specify a single range by setting my GraphQL variables like so:

```json
{
    "price": ["and", ">= 0", "< 50"]
}
```

Which suggests to me that it works like the [Yii where clause operator format](https://www.yiiframework.com/doc/api/2.0/yii-db-queryinterface#where()-detail).

However, if I do the following to get any entries that lie within any of the given ranges:

```json
{
    "price": [
        "or",
        ["and", ">= 0", "< 50"],
        ["and", ">= 200", "< 250"]
    ]
}
```

An error is returned (trace omitted for brevity):

```json
"errors": [
    {
      "debugMessage": "QueryArgument must be either a string, an integer, or a boolean value.",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "trace": [
```

Is there a way to do complex queries such as this using GraphQL?

### Steps to reproduce

1. Set up an entry type with a numeric field and populate it with some entries.
2. Set up a GraphQL entry query and variables like the one above and run it.

### Additional info

- Craft version: Craft Pro 3.6.12
- PHP version: 7.3.27
- Database driver & version: MySQL 5.7.33
- Plugins & versions: Amazon S3 1.2.11, Feed Me 4.3.6, Seeder 3.3.1, SEOmatic 3.3.40

**Comment by brandonkelly** [comment]
> I am able to specify a single range by setting my GraphQL variables like so:
> 
> ```json
> {
>     "price": ["and", ">= 0", "< 50"]
> }
> ```
> 
> Which suggests to me that it works like the [Yii where clause operator format](https://www.yiiframework.com/doc/api/2.0/yii-db-queryinterface#where()-detail).

Unfortunately no; only a top-level `and` or `or` can be passed, and that’s where the similarities with Yii’s conditional syntax end.

We’d need to first add support for more advanced conditional syntax to element queries, before we could add it to GraphQL. I’ll mark this as an enhancement and we can look into the feasibility of it.

**Comment by seb-jones** [comment]
Okay, thanks Brandon. Do you think there is any other way to achieve the intended functionality in GraphQL at the moment, or would it only be possibly in Twig/PHP?

**Comment by brandonkelly** [comment]
It’s only possible via [yii\db\Query::andWhere()](https://www.yiiframework.com/doc/api/2.0/yii-db-query#andWhere()-detail) currently.

Twig:

```twig
{% set products = craft.entries()
  .andWhere([
    'or',
    ['and', 'field_price >= 0', 'field_price < 50'],
    ['and', 'field_price >= 200', 'field_price < 250'],
  ])
  .all() %}
```

PHP:

```php
$products = \craft\elements\Entry::find()
    ->andWhere([
        'or',
        ['and', 'field_price >= 0', 'field_price < 50'],
        ['and', 'field_price >= 200', 'field_price < 250'],
    ])
    ->all();
```

**Comment by joshuabaker** [comment]
#7576

**Comment by FreekVR** [comment]
Just came here after running into similar issues, and having this type of advanced where clause in GQL would be really great. I created an entry type "Event" with a "Start" and "End" date field. I wanted to create a listing of events either starting after today OR ending after today, but I cannot currently add this kind of grouped OR condition to the queries.

For reference, this is how the ligthouse gql package for Laravel approaches this:
https://lighthouse-php.com/5/eloquent/complex-where-conditions.html#usage

I believe it uses the same underlying gql php library as Craft does, so perhaps this could be implemented in a similar way.

Implementing that in Craft would make the example @brandonkelly posted above look something like this in GraphQL:

```graphql
{
  products(
    where: {
      OR: [
        {
          AND: [
            { column: FIELD_PRICE, operator: GTE, value: "0" }
            { column: FIELD_PRICE, operator: LT, value: "50" }
          ]
        },
       {
          AND: [
            { column: FIELD_PRICE, operator: GTE, value: "200" }
            { column: FIELD_PRICE, operator: LT, value: "250" }
          ]
        }
      ]
    }
  ) {
    id, title
  }
}
```
