### ISSUE TITLE
Desctuctive actions requiring confirmation through browser modal dialog not working in Safari

### ISSUE THREAD

**Issue by stuart-mccoy** [craftcms/cms#7844]
### Description
Deleting an entry or uninstalling a plug-in while using the Safari browser does not work at all. A browser-based modal dialog should appear to confirm the action but in Safari, none appear.

### Steps to reproduce
**For Entries**
1. Open Safari
2. Open to the Entries tab
3. Select an entry or entries and choose delete from the dropdown menu

**For Plug-ins**
1. Open Safari
2. Open to Setting -> Plug-ins 
3. Click the dropdown button next to the plug-in you want to uninstall and click the uninstall action

### Additional info
Craft version: 3.6.12
PHP version: 7.4.12
Database driver & version: MySQL 5.7.32
Plugins & versions:
- Analytics 4.0.13
- CKEditor 1.1.1
- Contact Form 2.2.7
- Entry Count 2.0.3
- Expanded Singles 1.1.3
- Field Manager 2.2.2
- Google Tags 1.3.0
- Logs 3.0.3
- Matrix Toolbar 1.0.6
- Minify 1.2.10
- Redactor 2.8.6
- Redactor Custom Styles 3.0.4
- Tags 1.0.7
- Twig Profiler 1.0.1

**Comment by brandonkelly** [comment]
This is working as expected on my end (Safari 14.0.3). What version of Safari are you using?

<img width="1195" alt="A screenshot of Safari showing a confirmation dialog when deleting an entry." src="https://user-images.githubusercontent.com/47792/116327504-c0a84000-a77b-11eb-8052-326121344402.png">

**Comment by stuart-mccoy** [comment]
Same here, 14.0.3. I restarted and the dialog is back.

**Comment by brandonkelly** [comment]
Very weird! Must be an intermittent Safari bug.
