### ISSUE TITLE
[graphql] asset urls are missing appendix

### ISSUE THREAD

**Issue by lukasIO** [craftcms/cms#7847]
### Description
I hope I'm not missing something obvious. 
When querying assets (we use graphQL) the returned asset URLs don't have any `mtime` or `focal` query parameters appended to their URL, which leads to the assets not being updated on client side (as they stay cached) after being modified.

sample from the query
```
media @transform(format: "jpg", width: 400, height: 250, immediately: true) {
        ... on assets_Asset {
          url
          srcset (sizes: ["400w", "800w", "1200w"])
        }
      }
```

### Steps to reproduce

1. Upload an asset in a local volume
2. query it via graphQL
3. modify it (focal point or another transformation) and save
4. query it again
5. no appendix is present on srcset or url 

### Additional info

- Craft version: Craft Pro 3.6.12
- PHP version: 7.4.16
- Database driver & version: MySQL 5.7.33
- Plugins & versions: Imagick 3.4.4 (ImageMagick 6.9.10-23)

**Comment by andris-sevcenko** [comment]
The `mtime` and `focal` parameters are only added if the Volume has the `Expires` setting set, which is not available for Local Volumes.

This was added before GraphQL was a thing for Craft CMS, however, so probably worth a re-visit. I'll bring this up internally!

**Comment by lukasIO** [comment]
@andris-sevcenko is your feeling this will be considered in the near future? For our customers it's breaking the possibility to update their images after the initial upload.
Would also be happy to hear about possible workarounds in the meantime. Thanks!

**Comment by andris-sevcenko** [comment]
Ah, this completely went under the rug, I apologize. 

I'll get back to you tomorrow regarding this!

It's likely for Craft 3.7

**Comment by lukasIO** [comment]
@andris-sevcenko I don't want to seem impatient, just a friendly reminder because you wrote that you were expecting an update about this last week.

**Comment by lukasIO** [comment]
great, thank you!

**Comment by andris-sevcenko** [comment]
All set for Craft 3.7. We'll be expiring the check for `expires` setting (haha), so you'll have to set the new `revAssetUrls` config setting to `true`, when updating to Craft 3.7!

**Comment by toyflish** [comment]
@andris-sevcenko we have some focal-point functionality in our frontend that extracts the focal query param from the 3.6 outdated format of asset-urls.
We now thinking of moving it to the new format by extraction the second and third part of the v query param that holds the focal parameter. Is this a stable way of getting the focalpoint from the asset or is this likely to change in the future so we better not use it?

**Comment by andris-sevcenko** [comment]
@toyflish there's no reason for us to change it until there's reason to change it :)

I don't expect it to change in the foreseeable future, so it should be safe to use for now!
