### ISSUE TITLE
Properly support PHP 8.0 Named Arguments (Fatal error: Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters)

### ISSUE THREAD

**Issue by gijsstegehuis** [craftcms/cms#7848]
### Description
Eager loading elements on Craft 3.6.12 causes issues on PHP 8 due to PHP 8.0's Named Arguments.

`ArgumentCountError: array_merge() does not accept unknown named parameters in /app/vendor/craftcms/cms/src/services/Elements.php:2224`

Suggested fix: https://github.com/craftcms/cms/pull/7849

### Additional info

- Craft version: 3.6.12
- PHP version: 8.0.3

**Comment by brandonkelly** [comment]
Hey there, I’m not able to reproduce that, and your proposed fix wouldn’t work here.

Can you send your Composer files and a database backup into support@craftcms.com along with steps to reproduce the error?

**Comment by gijsstegehuis** [comment]
It seems like the way named arguments work in PHP8, the spread operator causes it to think they're named arguments.
This [wiki](https://wiki.php.net/rfc/named_params#internal_apis) might be helpful.

We're just using regular eager loading, nothing special really.

**Comment by brandonkelly** [comment]
Can you try changing that line to this, and see if it fixes it for you?

```php
$query->afterPopulate(array_merge(...array_values($targetElements)))
```

**Comment by gijsstegehuis** [comment]
@brandonkelly yep that's working!

**Comment by brandonkelly** [comment]
Thanks for checking! Got that change in for the next release.

**Comment by brandonkelly** [comment]
Craft 3.6.13 is out with that fix.
