### ISSUE TITLE
CORS problem with Live Preview on multisites

### ISSUE THREAD

**Issue by martinhellwagner** [craftcms/cms#7851]
### Description

We're experiencing an issue with Live Preview on multisites. When trying to preview an entry on a multisite that uses the `LivePreviewController`, it is blocked because it doesn't comply with CORS requirements. We found this issue when trying to preview a multisite's newsletter on the Campaign plugin, and already opened an issue there:  https://github.com/putyourlightson/craft-campaign/issues/194.

I've already found a solution to the problem though, which requires setting additional headers in the NGINX config to allow the preflight request as well as changing the `LivePreviewController` to include the site's base URL instead of the wildcard in `Access-Control-Allow-Origin`: https://github.com/putyourlightson/craft-campaign/issues/194#issuecomment-828309247

### Steps to reproduce

1. Try to preview an entry on a multisite
2. Preview fails because of CORS

### Additional info

- Craft version: 3.6.7
- PHP version: 7.4
- Database driver & version: MySQL 8.0
- Plugins & versions: Campaign 1.19.0

**Comment by brandonkelly** [comment]
Entries don’t use `LivePreviewController` anymore; that’s part of the legacy Live Preview system used by other element types still, but not entries.

So to be clear, are you actually seeing this with _entries_, or just with campaigns?

**Comment by martinhellwagner** [comment]
It's actually just with Campaigns (and with Categories, when I last tested it with Categories in November last year). So I presume that the plugin needs to use the `PreviewController` instead of the `LivePreviewController`?

**Comment by brandonkelly** [comment]
Yeah ok, this is a known limitation of the legacy Live Preview implementation. It’s only really possible to avoid the CORS issues [across subdomains](https://craftcms.com/knowledge-base/using-live-preview-across-multiple-subdomains), but not separate naked domains.

Unfortunately moving to the new one is pretty comlpex, so not really a feasible option for other element types yet. I’m working to improve that going forward.

**Comment by martinhellwagner** [comment]
Thanks, much appreciated! In the meantime, I've found a workaround already. 🙂

**Comment by watarutmnh** [comment]
Hi, @martinhellwagner I've just come form the campaign plugin issue: https://github.com/putyourlightson/craft-campaign/issues/194
I have multi site and template preview only works when the campaign associated with the default site.
Will you share how to solved the problem?

**Comment by watarutmnh** [comment]
@martinhellwagner Okay I thought you'd found another solution without modifying the Craft core. But thanks!

**Comment by brandonkelly** [comment]
The LivePreviewController will only set those CORS headers if they haven’t been set already. You can override them by adding this code to your `modules/Module.php` file:

```php
// Place these imports at the top of the file:
use craft\controllers\LivePreviewController;
use yii\base\ActionEvent;
use yii\base\Controller;
use yii\base\Event;

// Place this at the end of the init() method:
Event::on(
    LivePreviewController::class,
    Controller::EVENT_BEFORE_ACTION,
    function(ActionEvent $event) {
        if ($event->action->id === 'preview') {
            Craft::$app->response->headers->set('Access-Control-Allow-Origin', 'https://my-domain.com');
        }
    }
);
```

Also, make sure that your module is actually getting loaded on every request by opening `config/app.php` and uncommenting [this line](https://github.com/craftcms/craft/blob/4a69bfe7a49019a240d00dd0920697e33d08930d/config/app.php#L27).

**Comment by bencroker** [comment]
@martinhellwagner @watarutmnh I've added @brandonkelly's suggestion to the live preview controller action in the Campaign plugin in https://github.com/putyourlightson/craft-campaign/commit/6255f58c18be6082b83119c35ea3b71625aafc36, can you please check if this resolves the issue for you?

**Comment by bencroker** [comment]
Hang on, still needs some tweaking and testing.

**Comment by bencroker** [comment]
Ok, https://github.com/putyourlightson/craft-campaign/commit/391dda2d8ebb89acad077f401db7dc151d46f0bf should do it.

**Comment by brandonkelly** [comment]
@bencroker We used to pull in `request->getOrigin()`, but it turned out that `getOrigin()` can potentially return multiple comma-delimited values (see https://github.com/craftcms/cms/issues/4830#issuecomment-614198643). So we switched to `*` in 3.4.16 (a9e07bf9d1eb65c1fd9f6c1ed76ada349a705687).

For GraphQL, we added the [allowedGraphqlOrigins](https://craftcms.com/docs/3.x/config/config-settings.html#allowedgraphqlorigins) config setting. You might want to just follow suit with that, or have people do the above module event.

**Comment by bencroker** [comment]
Thanks for the explanation @brandonkelly. I've opted for convention over configuration this time, ensuring that only the first origin is used if multiple values exist: https://github.com/putyourlightson/craft-campaign/commit/656e57fc19eb0bf015268ee59ca8428eb5c217d6
