### ISSUE TITLE
Entry query running from the start of the current minute, excluding seconds

### ISSUE THREAD

**Issue by mattsbanner** [craftcms/cms#7853]
### Description
I've got a plugin where we sync entries from an external source. Before creating a new entry, we first check if an existing entry with the same slug (as this is always unique in the source) already exists. If it does, we can then update the current entry, rather than create a duplicate.

I have found that `Entry::find()` always applies a `WHERE` on the `postDate`. The time sent through here is always at the start of the current minute, rather than to the current second. This means, existing entries cannot be found if they were created at `13:00:10` and I run the script again at `13:00:30`.

I also seem to be unable to override the `postDate`, this gets added as an `AND`.

### Steps to reproduce
1. `Entry::find()->getRawSql()`
2. See that query has a `postDate` where the seconds are always `00`.

### Additional info

- Craft version: 3.6.11.2
- PHP version: 7.3
- Database driver & version: MySQL 5.7

**Comment by mattsbanner** [comment]
I see the seconds are being stripped [here](https://github.com/craftcms/cms/blob/develop/src/elements/db/EntryQuery.php#L837), which is likely where this issue is coming from.

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.6.12.1 is out now with the fix for this. Thanks again!
