### ISSUE TITLE
Entry URI include multisite basepath segment?

### ISSUE THREAD

**Issue by jlaughton87** [craftcms/cms#7855]
### Description
Apologies if i am missing some fundamental knowledge here but i cant seem to find the solution i need. 

I have a multisite which uses a different uri for each site, I have set this up in the following way:

![image](https://user-images.githubusercontent.com/14894660/116520059-2276c000-a8ca-11eb-8e95-9009d6824a67.png)

In the section settings for a channel in my multisite i have: 

![image](https://user-images.githubusercontent.com/14894660/116520350-8305fd00-a8ca-11eb-9c48-878a70e9a271.png)

This works fine for navigating to a page from an entry within the CMS

My issue arrises when creating links throughout the frontend using the entry URI - they are not prefixed with the multisite basebath segment, just the slug.

As described in some forums i have tried setting the Entry URI Format in my sections e.g

![image](https://user-images.githubusercontent.com/14894660/116521762-49ce8c80-a8cc-11eb-8401-af3dc9249fcc.png)

This works for linking throughout the frontend but causes issues in the admin and with plugins which use the entry url (verbb navigation) for example:

![image](https://user-images.githubusercontent.com/14894660/116522483-25bf7b00-a8cd-11eb-877c-18ebb965af4e.png)

I want to avoid removing the path within the multisite base URL (as i use this to link throughout the site and for emails etc) and i also dont want to have to prefix all my paths on the frontend (e.g 'connect/') Is there a way that my entry URI can automatically include my multisite basepath segment?

Thanks in advance

### Additional info

- Craft version: Craft Pro 3.6.11.2
- PHP version: 7.4.13

**Comment by brandonkelly** [comment]
> My issue arrises when creating links throughout the frontend using the entry URI - they are not prefixed with the multisite basebath segment, just the slug.

How exactly are you creating the links?

You should be calling `entry.getUrl()`, **not** `entry.uri`. `getUrl()` will return the full URL to the entry, starting with its site’s base URL and then adding on its URI to it.

**Comment by jlaughton87** [comment]
Thanks Brandon, 

I guess it makes sense that identifier would only use the entry name but at the same time it could be argued (*I was hoping) that if a multisite is using a subpath rather than a subdomain or entirely unique URL, then that root segment would constitute part of the uri for the entries within it.

Anyway, thanks for the clarification.  I've inherited this site, it's huge and using the uri's throughout for links and even graph ql calls. 

Guess i better get refactoring!
