### ISSUE TITLE
Exception in migration when upgrading 3.4.30 to 3.5.19.1

### ISSUE THREAD

**Issue by kringkaste** [craftcms/cms#7862]
### Description

When running `./craft migrate/all` in the console after upgrading Craft 3.4.30 to 3.5.19.1 in the console, the migrations stops with the following exception:

```
> drop column titleLabel from table {{%entrytypes}} ... done (time: 0.091s)
Exception: Calling unknown method: craft\console\Request::getPathInfo() (/local/vendor/yiisoft/yii2/base/Component.php:300)
#0 /local/vendor/craftcms/cms/src/services/TemplateCaches.php(351): yii\base\Component->__call()
#1 /local/vendor/craftcms/cms/src/services/TemplateCaches.php(328): craft\services\TemplateCaches->_path()
#2 /local/vendor/craftcms/cms/src/services/TemplateCaches.php(260): craft\services\TemplateCaches->_cacheKey()
#3 /local/vendor/craftcms/cms/src/services/TemplateCaches.php(255): craft\services\TemplateCaches->deleteCachesByKey()
#4 /local/plugins/stylepark/src/Stylepark.php(199): craft\services\TemplateCaches->deleteCachesByKey()
#5 [internal function]: stylepark\Stylepark->stylepark\{closure}()
#6 /local/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()
#7 /local/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger()
#8 /local/vendor/craftcms/cms/src/base/Element.php(3202): yii\base\Component->trigger()
#9 /local/vendor/craftcms/cms/src/elements/Entry.php(1507): craft\base\Element->afterSave()
```

As you can see, we have an event handler registered, that wants to delete some template caches by their keys. But this function now requires getPathInfo() which is not available in console requests.

We assume, that this will also break, if we later call `Craft::$app->templateCahes->deleteCachesByKey()` in jobs running on an dedicated worker in a console by `./craft queue/listen`. Is this right?

How can we delete template caches in console requests in the Craft >= 3.5.0?

### Steps to reproduce

1. Add an plugin with an event handler for `Entry::EVENT_AFTER_SAVE` and call there something like `Craft::$app->templateCaches->deleteCachesByKey(['xyz']);` inside the closure/function.
2. Upgrade Craft 3.4.30 to 3.5.19.1 with `composer` in a console.
3. Run `./craft migrate/all` in the console.

### Additional info

- Craft version: 3.4.30 / 3.5.19.1
- PHP version: 7.4

**Comment by brandonkelly** [comment]
The template cache system was refactored a bit in 3.5 to be much faster (no more “Deleting stale template caches” background tasks), so as a starting point, you might want to verify whether you really need your code in the first place.

If you do, you’re going to be better off going through `craft\services\Elements::invalidateAllCaches()`, `invalidateCachesForElementType()`, or `invalidateCachesForElement()`, depending on what you want to do.

```php
Craft::$app->elements->invalidateAllCaches();
```
