### ISSUE TITLE
Unable to save entry as a draft: Could not generate a unique URI based on the URI format.

### ISSUE THREAD

**Issue by seandelaney** [craftcms/cms#7863]
### Description

Encountered this issue when creating a new entry.

### Steps to reproduce

1. Create a new section (in my case Videos)
2. Under Site Settings > Entry URI Format, remove the `{slug}` part from `videos/{slug}` so the URI looks like `videos`.

![Screenshot 2021-04-30 at 15 24 46](https://user-images.githubusercontent.com/580403/116709285-710a8400-a9c8-11eb-81fe-316a17ea59f5.png)

3. Save new section.
4. Attempt to create a new entry.
5. See attached screenshot with error.

![Screenshot 2021-04-30 at 15 18 50](https://user-images.githubusercontent.com/580403/116708693-de69e500-a9c7-11eb-8389-a40dcde8d64f.png)

FYI, if I add the `{slug}` part back into the URI again, the error goes away.

### Additional info

- Craft version: 3.6.12.1
- PHP version: PHP 7.4.2
- Database driver & version: MySQL 5.7.26
- Plugins & versions:

**Comment by brandonkelly** [comment]
The main issue here is that you can’t have two elements that share the same generated URI. So you will need to find a URI format that ensures each entry gets a unique URI (or none at all).

The exception message isn’t user friendly though. Just fixed that for the next release. Now you will be able to create the entry, but the entry’s status will automatically be set to disabled when you try to publish it, and you’ll get this error message near the Slug field if you try to re-save it as enabled:

> Could not generate a unique URI based on the URI format.

**Comment by brandonkelly** [comment]
Craft 3.6.13 is out with this fix.
