### ISSUE TITLE
Setting unknown property: craft\fields\Matrix::propagationKeyFormat

### ISSUE THREAD

**Issue by brambeekman** [craftcms/cms#7865]
### Description

After I ran `composer update` I get this error

### Steps to reproduce

1. remove vendor filter and run `composer install`

### Additional info

- Craft version: 3.6.12
- PHP version: 7.3

**Comment by brandonkelly** [comment]
Search for that error in your logs (`storage/logs/`). It should show more details including a stack trace in there. Can you post the full stack trace?

**Comment by brambeekman** [comment]
Reinstalling Craft was for me the fix.

**Comment by brandonkelly** [comment]
In that case, sounds like `composer update` ended up giving you the wrong Craft version.
