### ISSUE TITLE
Possible name conflicts when relocating user photos

### ISSUE THREAD

**Issue by samhibberd** [craftcms/cms#7866]
I'm not sure if this is by design, but we are running into name conflicts when relocating user photos, after changing the user photo location path.

https://github.com/craftcms/cms/blob/0821ff89be4ac4fd59ae28c921d8629d4223c059/src/services/Users.php#L463

Adding `$photo->avoidFilenameConflicts = true;` appears to handle name conflicts in the same way that the assets field does.

We identified this issue when resaving / relocating the assets for 100k+ users, even with `avoidFilenameConflicts` set `true`, we were still getting conflicts, I think this is because we are running the resave in batches and have concurrent tasks running. Assuming it's some sort of timing issue and the date time appended to the filename no longer being unique when subsequently saved. 

If this is the case I wonder if there is any way to make them even more unique?

**Comment by brandonkelly** [comment]
I might be wrong, but the issue here appears to be that the `AssetLocationValidator` isn’t getting applied for `SCENARIO_FILEOPS`. So no attempt is actually being made to ensure the filename is unique.

**Comment by samhibberd** [comment]
Ah, I didn’t see any scenario on the validator rule so assumed it was only being applied if the avoidFilenameConflicts property was true.

**Comment by andris-sevcenko** [comment]
Just pushed a fix that should help with this for the next release. 

In the end, it's a race condition, so we applied the speedy-yet-crude fix of adding a random 4-character string at the end of the timestamp, to avoid conflicts in scenarios such as yours.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#47a4cfe4489f35a6a4317f198369d217b8702134 as 3.6.12.1",
  "...": "..."
}
```

Then run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.6.13 is out with this fix.
