### ISSUE TITLE
Unable to delete folder from local assets volume when folder is renamed outside CP

### ISSUE THREAD

**Issue by bencresty** [craftcms/cms#7868]
### Description

When a subfolder of a local assets volume is renamed outside the CMS and all assets are re-indexed using the command line, the old foldername is still visible from within the CMS, but cannot be deleted from within the CMS by using rightclick/context menu 'Delete folder' on that folder in the Assets panel. The popup shows 'Couldn't delete {foldername}`.

I tried some things with the command line and within the CP to update so the non-existing folder would be gone from the listing, but it stays. I tried deleting all caches, garbage collect, log-out/log-in the CMS, do another re-indexing all assets, but none of these seem to work.

I understand I probably shouldn't have renamed the folder from outside the CP, but if we do I would expect it not to be an issue to just remove the virtual shortcut in the DB to the old, now non-existing, folder.
Looks like it's impossible to remove a virtual folder shortcut when the fysical folder doesn't exist, eventhough there are no files inside being used (also empty in the CMS list) and there are no entries using the assets currently either (even the trash is empty).

### Steps to reproduce

1. Rename a subfolder of a volume outside the CP
2. Try to remove the old foldername from the CP

### Additional info

- Craft version: 3.6.12.1
- PHP version: 7.4.9
- Database driver & version: MySQL 5.5.5

**Comment by bencresty** [comment]
Just did a test; when re-creating the non-existing folder again outside the CP again, the folder can be deleted from within the CP again instantly (no need for re-indexing or whatever) without any problem.

So the only issue here seems to be that Craft is checking if the fysical location exists before removing both the folder entry from the db as well as fysically removing the folder from the server.

I think it would be better and more flexible and prevent this kind of issues if it still would remove the folder entry from the db, even if the fysical folder could not be found. I believe in these cases it helps showing a message to the user that the fysical folder couldn't be deleted because it doesn't exist would be nice though, but it would be very helpful if it still removed the entry from the db.

**Comment by andris-sevcenko** [comment]
Yikes, thanks for reporting! Just fixed that for the next release!

**Comment by bencresty** [comment]
@andris-sevcenko Thanks for this quick action! Very much appreciated!

**Comment by brandonkelly** [comment]
Craft 3.6.13 is out with this fix.
