### ISSUE TITLE
Unable to click on the left & right sides of CP notification

### ISSUE THREAD

**Issue by benface** [craftcms/cms#7871]
### Description

This one has been bugging me for a *while* but I've always been too lazy to report it. Well this time I'm not!

When you execute any action that makes the top notification appear in the CP, you can't click on the breadcrumb links or basically anywhere on the left & right sides of the notification until it fades out. There seems to be an invisible overlay that prevents clicks to go through anywhere inside the red rectangles I added to this screenshot:

![CleanShot 2021-05-03 at 00 04 17@2x](https://user-images.githubusercontent.com/1059139/116840298-504a5600-aba3-11eb-886e-9adaf125661f.png)

### Additional info

- Craft version: 3.6.12.1
- PHP version: 7.4.14
- Database driver & version: MySQL 8.0.23

**Comment by brandonkelly** [comment]
Thanks for reporting! However the issue is already covered by #7572.
