### ISSUE TITLE
CustomFieldsBehavior methods declared as static

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#7873]
### Description
This is not really a "bug" report rather a question for your reasons to define all functions in the CustomFieldBehavior as static.
I would expect all those to be non static and I always remove the static keyword in order mute PHPStorm warnings.

The file looks currently like 

```PHP
/**
 * Custom field behavior
 *
 * This class provides attributes for all the unique custom field handles.
 *
 * @method static text(mixed $value) Sets the [[text]] property
```
The following is okay
```PHP
Entry::find()->text('foo');
```
But this one fails because of it
```PHP
$query = Entry::find();
$query->text('foo');
```
![image](https://user-images.githubusercontent.com/6122122/116862560-3c374080-ac05-11eb-9615-439722c7e8ff.png)

I would just like to know what the reason behind this is or if that's an issue with wrong IDE settings maybe (latest PHPStorm Version)

### Additional info

- Craft version: 3.6.x:

**Comment by brandonkelly** [comment]
`static` there refers to the method’s return type; it’s not meant to indicate the method is supposed to be static. It used to work but apparently doesn’t anymore. Just changed to `$this`, which works as expected in PhpStorm 2021.1.2.

**Comment by brandonkelly** [comment]
Craft 3.6.13 is out with this change.
