### ISSUE TITLE
Internal Server Error when trying to edit or create entries

### ISSUE THREAD

**Issue by timoschwarzer** [craftcms/cms#7874]
### Description

**Hint:** This is **NOT** a bug in Craft itself ([almost](https://github.com/craftcms/cms/blob/6825bb260d3d108f7d85289213361f0e4177ba1a/src/services/Elements.php#L689)) and Craft is [not the only application](https://github.com/php/php-src/pull/6801#issuecomment-828783810) where this error occurrs, but I think this issue helps Craft users experiencing the same error.

```
Next yii\db\Exception: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: boolean = integer
LINE 3: WHERE ("elementId"=$1) AND ("enabled"=$2)
```

### Solution

Don't use PHP 7.4.18 or 8.0.5 with PostgreSQL. Downgrade PHP to the previous patch (7.4.16 or 8.0.3 respectively) or wait for the next PHP patch update.

### Cause

https://bugs.php.net/bug.php?id=80892

### Additional info

- Craft version: 3.6.12.1
- PHP version: 7.4.18
- Database driver & version: PostgreSQL 12.6
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
Swapped that `'enabled' => 1` condition with `'enabled' => true`, which should fix this particular instance of the error. Please let me know if you see it anywhere else.

**Comment by timoschwarzer** [comment]
> Please let me know if you see it anywhere else.

Eventually:

- https://github.com/craftcms/cms/blob/c208dc4607914fbd5492d98fd4dd002c9f50bb8f/src/migrations/m160804_110002_userphotos_to_assets.php#L276 and following
- https://github.com/craftcms/cms/blob/c208dc4607914fbd5492d98fd4dd002c9f50bb8f/src/migrations/m160807_144858_sites.php#L105

**Comment by brandonkelly** [comment]
Updated those and a couple other ones as well, and got those changes into Craft 3.6.13.

**Comment by timoschwarzer** [comment]
Thank you! ❤️
