### ISSUE TITLE
currentSite.baseUrl always returns with trailing slashes, despite settings

### ISSUE THREAD

**Issue by mizziness** [craftcms/cms#7876]
### Description

With configuration in place to remove the trailing slash from `currentSite.baseUrl`, I expected the final string returned by the global variable would be without the trailing slash.  However, the slash is always included.  I expect to be able to customize this.

### Steps to Reproduce 

First, tweak or add these settings:

.env file:
```
  DEFAULT_SITE_URL="https://www.applause.com"
```
config/general.php:
```
    ...
    'aliases' => [
      '@defaultSiteUrl' => getenv('DEFAULT_SITE_URL'),
      '@baseUploadsUrl' => getenv('BASE_UPLOADS_URL'),
    ],

    'addTrailingSlashesToUrls' => false,
    ...
```

After this, the System Report shows the alias exists now and is correct:

![image](https://user-images.githubusercontent.com/4164335/116917045-208b6480-ac1c-11eb-9613-22a2d0d2114f.png)

And when you go into the CP to Settings > Sites to edit the site, you can choose the new alias, and it seems to have worked:

![image](https://user-images.githubusercontent.com/4164335/116916271-19b02200-ac1b-11eb-8e3f-d390ad91848d.png)

But then as soon as you save the page and it takes you back to the Settings > Sites page, there's the darn slash again!

![image](https://user-images.githubusercontent.com/4164335/116916421-49f7c080-ac1b-11eb-8af1-79e8cda864ed.png)

### Additional info

- Craft version: Craft Pro 3.6.12.1
- PHP version:  7.4.3
- Database driver & version: MySQL 8.0.23 
- Plugins & versions:

![image](https://user-images.githubusercontent.com/4164335/116917471-b626f400-ac1c-11eb-89da-3bd34b24daee.png)

**Comment by brandonkelly** [comment]
This was covered by #5675. Changing the behavior would be a breaking change, so we’ll look into it for 4.0.
