### ISSUE TITLE
SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: boolean = integer LINE 3: WHERE ("elementId"=$1) AND ("enabled"=$2)

### ISSUE THREAD

**Issue by ujanko** [craftcms/cms#7877]
### Description
Getting an sql error when trying to access any entry in the system:
![Screen Shot 2021-05-03 at 1 53 54 PM](https://user-images.githubusercontent.com/17748941/116919899-94773e00-ac17-11eb-8304-88dc671f95a1.png)

The error is not coming from out code, I have tried using an older snapshot fo the db but still getting the same issue. 

### Steps to reproduce

1. Go to the admin console.
2. Click any try to edit any entry.

### Additional info
PHP version	7.4.18
OS version	Linux 4.19.121-linuxkit
Database driver & version	PostgreSQL 9.6.21
Image driver & version	Imagick 3.4.4 (ImageMagick 6.9.10-23)
Craft edition & version	Craft Pro 3.6.12
Yii version	2.0.41.1
Twig version	v2.14.4
Guzzle version	7.3.0

### Here is the full stack trace:
PDOException: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: boolean = integer
LINE 3: WHERE ("elementId"=$1) AND ("enabled"=$2)
                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts. in /var/www/html/vendor/yiisoft/yii2/db/Command.php:1299
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1299): PDOStatement->execute()
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1165): yii\db\Command->internalExecute('SELECT "siteId"...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Command.php(450): yii\db\Command->queryInternal('fetchAll', 7)
#3 /var/www/html/vendor/yiisoft/yii2/db/Query.php(320): yii\db\Command->queryColumn()
#4 /var/www/html/vendor/craftcms/cms/src/db/Query.php(202): yii\db\Query->column(NULL)
#5 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(690): craft\db\Query->column()
#6 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1507): craft\services\Elements->getEnabledSiteIdsForElement(220785)
#7 /var/www/html/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\services\Elements), 'getEnabledSiteI...', Array, 'method', false, false)
#8 /var/www/html/storage/runtime/compiled_templates/28/28eed3970e369497518793c8e44be6099c37417a98007160ed26dbd61ae00b71.php(174): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\services\Elements), 'getEnabledSiteI...', Array, 'method')
#9 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_c787e9550ddf23e90f17dd70b227cbf50bff3b7a4a75c87332f8c3fc733605d7->doDisplay(Array, Array)
#10 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#11 /var/www/html/storage/runtime/compiled_templates/36/36e4016b544b2638b3bc058e138ebfc2f9576e53e2033abe6a51a1bfc8919f73.php(356): Twig\Template->display(Array)
#12 /var/www/html/vendor/twig/twig/src/Template.php(182): __TwigTemplate_ca94d4dc95f8c47237bc161c2ed367c1d7d8477fb3c64f2fe70ec39a1a88cab8->block_contextMenu(Array, Array)
#13 /var/www/html/storage/runtime/compiled_templates/36/36e4016b544b2638b3bc058e138ebfc2f9576e53e2033abe6a51a1bfc8919f73.php(331): Twig\Template->displayBlock('contextMenu', Array, Array)
#14 /var/www/html/vendor/twig/twig/src/Template.php(182): __TwigTemplate_ca94d4dc95f8c47237bc161c2ed367c1d7d8477fb3c64f2fe70ec39a1a88cab8->block_header(Array, Array)
#15 /var/www/html/storage/runtime/compiled_templates/be/bef08611f6f9c76d9412ab39388f8f9c431e114268f1a9405838dbfce7fe4e64.php(279): Twig\Template->displayBlock('header', Array, Array)
#16 /var/www/html/vendor/twig/twig/src/Template.php(182): __TwigTemplate_5f4fd8bf94bc72690e5e211ff5a47f885da4ea2802e78cb7255e9042d5be46e2->block_body(Array, Array)
#17 /var/www/html/storage/runtime/compiled_templates/99/993acdc5dd7897f63214365bf3b8471f8d85e205d6a24d5d0e7fa66abb4f9d6e.php(90): Twig\Template->displayBlock('body', Array, Array)
#18 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_33983fcdea7915d0de3b3f08174452dd9d80d767e5d73309a500673a840665bc->doDisplay(Array, Array)
#19 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#20 /var/www/html/storage/runtime/compiled_templates/db/db120dfc0ae5ed08efed4ec570f93189011a045195f8bd93e9c005eb285342fd.php(56): Twig\Template->display(Array, Array)
#21 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_466f5e6e8b5a024791d8f070dc2e5ea0dd45326ba372b4fdd1bff2b73fc2fcaf->doDisplay(Array, Array)
#22 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#23 /var/www/html/storage/runtime/compiled_templates/be/bef08611f6f9c76d9412ab39388f8f9c431e114268f1a9405838dbfce7fe4e64.php(158): Twig\Template->display(Array, Array)
#24 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_5f4fd8bf94bc72690e5e211ff5a47f885da4ea2802e78cb7255e9042d5be46e2->doDisplay(Array, Array)
#25 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#26 /var/www/html/storage/runtime/compiled_templates/36/36e4016b544b2638b3bc058e138ebfc2f9576e53e2033abe6a51a1bfc8919f73.php(314): Twig\Template->display(Array, Array)
#27 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_ca94d4dc95f8c47237bc161c2ed367c1d7d8477fb3c64f2fe70ec39a1a88cab8->doDisplay(Array, Array)
#28 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#29 /var/www/html/storage/runtime/compiled_templates/fa/fa9b712381a548a25411b2558805adf788e1c5f79dcc7ad6037c0835da8fe0d0.php(124): Twig\Template->display(Array, Array)
#30 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_95d37733d172e9b0474952b876a40d1e1c243c10b3139a7fa824c6e7f243a1cf->doDisplay(Array, Array)
#31 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#32 /var/www/html/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#33 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#34 /var/www/html/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#35 /var/www/html/vendor/craftcms/cms/src/web/View.php(390): Twig\Environment->render('entries/_edit', Array)
#36 /var/www/html/vendor/craftcms/cms/src/web/View.php(451): craft\web\View->renderTemplate('entries/_edit', Array)
#37 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(257): craft\web\View->renderPageTemplate('entries/_edit', Array, 'cp')
#38 /var/www/html/vendor/craftcms/cms/src/controllers/EntriesController.php(250): craft\web\Controller->renderTemplate('entries/_edit', Array)
#39 [internal function]: craft\controllers\EntriesController->actionEditEntry(Object(craft\models\Section), 220785, NULL, NULL, Object(craft\models\Site), Object(craft\elements\Entry))
#40 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#41 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#42 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('edit-entry', Array)
#43 /var/www/html/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('edit-entry', Array)
#44 /var/www/html/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('entries/edit-en...', Array)
#45 /var/www/html/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('entries/edit-en...', Array)
#46 /var/www/html/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
#47 /var/www/html/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#48 /var/www/html/web/index.php(39): yii\base\Application->run()
#49 {main}

Next yii\db\Exception: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: boolean = integer
LINE 3: WHERE ("elementId"=$1) AND ("enabled"=$2)
                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
The SQL being executed was: SELECT "siteId"
FROM "craft_elements_sites"
WHERE ("elementId"=220785) AND ("enabled"=1) in /var/www/html/vendor/yiisoft/yii2/db/Schema.php:678
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1304): yii\db\Schema->convertException(Object(PDOException), 'SELECT "siteId"...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1165): yii\db\Command->internalExecute('SELECT "siteId"...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Command.php(450): yii\db\Command->queryInternal('fetchAll', 7)
#3 /var/www/html/vendor/yiisoft/yii2/db/Query.php(320): yii\db\Command->queryColumn()
#4 /var/www/html/vendor/craftcms/cms/src/db/Query.php(202): yii\db\Query->column(NULL)
#5 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(690): craft\db\Query->column()
#6 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1507): craft\services\Elements->getEnabledSiteIdsForElement(220785)
#7 /var/www/html/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\services\Elements), 'getEnabledSiteI...', Array, 'method', false, false)
#8 /var/www/html/storage/runtime/compiled_templates/28/28eed3970e369497518793c8e44be6099c37417a98007160ed26dbd61ae00b71.php(174): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\services\Elements), 'getEnabledSiteI...', Array, 'method')
#9 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_c787e9550ddf23e90f17dd70b227cbf50bff3b7a4a75c87332f8c3fc733605d7->doDisplay(Array, Array)
#10 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#11 /var/www/html/storage/runtime/compiled_templates/36/36e4016b544b2638b3bc058e138ebfc2f9576e53e2033abe6a51a1bfc8919f73.php(356): Twig\Template->display(Array)
#12 /var/www/html/vendor/twig/twig/src/Template.php(182): __TwigTemplate_ca94d4dc95f8c47237bc161c2ed367c1d7d8477fb3c64f2fe70ec39a1a88cab8->block_contextMenu(Array, Array)
#13 /var/www/html/storage/runtime/compiled_templates/36/36e4016b544b2638b3bc058e138ebfc2f9576e53e2033abe6a51a1bfc8919f73.php(331): Twig\Template->displayBlock('contextMenu', Array, Array)
#14 /var/www/html/vendor/twig/twig/src/Template.php(182): __TwigTemplate_ca94d4dc95f8c47237bc161c2ed367c1d7d8477fb3c64f2fe70ec39a1a88cab8->block_header(Array, Array)
#15 /var/www/html/storage/runtime/compiled_templates/be/bef08611f6f9c76d9412ab39388f8f9c431e114268f1a9405838dbfce7fe4e64.php(279): Twig\Template->displayBlock('header', Array, Array)
#16 /var/www/html/vendor/twig/twig/src/Template.php(182): __TwigTemplate_5f4fd8bf94bc72690e5e211ff5a47f885da4ea2802e78cb7255e9042d5be46e2->block_body(Array, Array)
#17 /var/www/html/storage/runtime/compiled_templates/99/993acdc5dd7897f63214365bf3b8471f8d85e205d6a24d5d0e7fa66abb4f9d6e.php(90): Twig\Template->displayBlock('body', Array, Array)
#18 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_33983fcdea7915d0de3b3f08174452dd9d80d767e5d73309a500673a840665bc->doDisplay(Array, Array)
#19 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#20 /var/www/html/storage/runtime/compiled_templates/db/db120dfc0ae5ed08efed4ec570f93189011a045195f8bd93e9c005eb285342fd.php(56): Twig\Template->display(Array, Array)
#21 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_466f5e6e8b5a024791d8f070dc2e5ea0dd45326ba372b4fdd1bff2b73fc2fcaf->doDisplay(Array, Array)
#22 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#23 /var/www/html/storage/runtime/compiled_templates/be/bef08611f6f9c76d9412ab39388f8f9c431e114268f1a9405838dbfce7fe4e64.php(158): Twig\Template->display(Array, Array)
#24 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_5f4fd8bf94bc72690e5e211ff5a47f885da4ea2802e78cb7255e9042d5be46e2->doDisplay(Array, Array)
#25 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#26 /var/www/html/storage/runtime/compiled_templates/36/36e4016b544b2638b3bc058e138ebfc2f9576e53e2033abe6a51a1bfc8919f73.php(314): Twig\Template->display(Array, Array)
#27 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_ca94d4dc95f8c47237bc161c2ed367c1d7d8477fb3c64f2fe70ec39a1a88cab8->doDisplay(Array, Array)
#28 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#29 /var/www/html/storage/runtime/compiled_templates/fa/fa9b712381a548a25411b2558805adf788e1c5f79dcc7ad6037c0835da8fe0d0.php(124): Twig\Template->display(Array, Array)
#30 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_95d37733d172e9b0474952b876a40d1e1c243c10b3139a7fa824c6e7f243a1cf->doDisplay(Array, Array)
#31 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#32 /var/www/html/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#33 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#34 /var/www/html/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#35 /var/www/html/vendor/craftcms/cms/src/web/View.php(390): Twig\Environment->render('entries/_edit', Array)
#36 /var/www/html/vendor/craftcms/cms/src/web/View.php(451): craft\web\View->renderTemplate('entries/_edit', Array)
#37 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(257): craft\web\View->renderPageTemplate('entries/_edit', Array, 'cp')
#38 /var/www/html/vendor/craftcms/cms/src/controllers/EntriesController.php(250): craft\web\Controller->renderTemplate('entries/_edit', Array)
#39 [internal function]: craft\controllers\EntriesController->actionEditEntry(Object(craft\models\Section), 220785, NULL, NULL, Object(craft\models\Site), Object(craft\elements\Entry))
#40 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#41 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#42 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('edit-entry', Array)
#43 /var/www/html/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('edit-entry', Array)
#44 /var/www/html/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('entries/edit-en...', Array)
#45 /var/www/html/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('entries/edit-en...', Array)
#46 /var/www/html/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
#47 /var/www/html/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#48 /var/www/html/web/index.php(39): yii\base\Application->run()
#49 {main}
Additional Information:
Array
(
    [0] => 42883
    [1] => 7
    [2] => ERROR:  operator does not exist: boolean = integer
LINE 3: WHERE ("elementId"=$1) AND ("enabled"=$2)
                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
)

**Comment by timoschwarzer** [comment]
Duplicate of https://github.com/craftcms/cms/issues/7874

**Comment by ujanko** [comment]
Thanks for the quick reply, will close the issue. I can also confirm that downgrading to 7.2 fixes it.
