### ISSUE TITLE
Matrix block ID's change when publishing a draft

### ISSUE THREAD

**Issue by jamiewade** [craftcms/cms#7881]
### Description
When publishing a Draft for an entry, the ID of each matrix block on that entry changes.

We have inherited a Craft site where there is references to specific matrix block ID's in the code, but when a new Draft is published, the ID's are no longer valid. Simply making changes to the Entry and saving it do not change the ID's.

This is easily solved by not referencing the matrix block ID, and instead using some other unique identifier for each block. But is this expected behaviour? If so, could you help explain why?

I would have thought that the ID's would remain the same. They were there before the new Draft, and they are there once that Draft has been published. What is the benefit of changing their ID?

### Steps to reproduce

1. Add a matrix field to an Entry, and add a few blocks to that field. Save the Entry, and note the ID's for each block
2. Create a new Draft, make some changes, save and publish that Draft
3. Note how the ID's for each block have changed

### Additional info

- Craft version: 3.6.12.1 (fresh install)
- PHP version: 7.3.27
- Database driver & version: MySQL 5.7.32
- Plugins & versions: None (fresh install)

**Comment by brandonkelly** [comment]
This is expected for now, however it’s no longer the case in 3.7 (see #7710).

**Comment by jamiewade** [comment]
Thanks @brandonkelly, good to hear it.
