### ISSUE TITLE
Element Delete Action API doesn't support hard deleting

### ISSUE THREAD

**Issue by BenParizek** [craftcms/cms#7901]
### Description

If I attempt to implement the [Delete Action](https://github.com/craftcms/cms/blob/main/src/elements/actions/Delete.php) in a custom Element and set it to hard delete:

    protected static function defineActions(string $source = null): array
    {
        $actions = parent::defineActions();

        $actions[] = Craft::$app->getElements()->createAction([
            'type' => Delete::class,
            'hard' => true,
        ]);

        return $actions;
    }

The action succeeds but the element is only soft deleted in the database. This appears to be because the selected items are soft deleted on line 188 and then re-queried on line 194, which returns zero IDs because the query does not find the items that were just soft-deleted above:

https://github.com/craftcms/cms/blob/ba3b1e704194e7e6a056595d0d9cededc7e9b9c3/src/elements/actions/Delete.php#L175-L200

In looking into the issue I also noticed that this version of the hard delete does not take the extra step of deleting the related search index data, as the hard delete behavior in the service layer does:

https://github.com/craftcms/cms/blob/ba3b1e704194e7e6a056595d0d9cededc7e9b9c3/src/services/Elements.php#L1525-L1530

**Comment by brandonkelly** [comment]
Thanks for reporting! Merged your PR for the next release.
