### ISSUE TITLE
Error installing plugin from Project Config changes (via CP only)

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#7903]
### Description

When a plugin is installed, the plugin's details are recorded in the Project Config YAML file. It's worth noting that the plugin's version and/or schema numbers are not recorded...

<img width="404" alt="pc-changes@2x" src="https://user-images.githubusercontent.com/5309692/117556306-31711700-b01c-11eb-9d0a-6e8addf3725d.png">

Once you've pushed those PC files to production, you will need to apply the recent changes to install the plugin.

**This is where you have a branching path...**

1. If you run `project-config/apply` via command line, it is able to install the plugin as expected.
2. If you try to "Apply changes" by clicking the button in the CP, you will see the error message below...

<img width="814" alt="yaml-message@2x" src="https://user-images.githubusercontent.com/5309692/117556322-5cf40180-b01c-11eb-885b-47354986cc08.png">

The correct plugin package is already in place, so `composer install` does nothing. Seems like the issue is more that the PC file is _missing_ the plugin version number.

I'm assuming that the CLI command does not perform the same check against the plugin version. I'm not sure why the CP button would trigger an error, whereas the CLI command does not.

### Steps to reproduce

1. Install the Google Maps plugin.
2. Make sure it generated the correct PC file.
3. Reset your database.
4. Try to re-install the plugin from the PC files...
   - If you run the CLI command, it all works as expected.
   - If you click the button in the CP, you get an error message.

### Additional info

- Google Maps: 4.0.8
- Craft version: 3.6.13
- PHP version: 7.4.16

**Comment by brandonkelly** [comment]
> It's worth noting that the plugin's version and/or schema numbers are not recorded...

I’m not able to reproduce this. Here’s what I see under `plugins` after installing Google Maps:

```yaml
plugins:
  google-maps:
    edition: standard
    enabled: true
    schemaVersion: 4.0.0
```

**Comment by lindseydiloreto** [comment]
Interesting. I'll try to reproduce it in a more isolated environment.

**Comment by lindseydiloreto** [comment]
Looks like this was due to a migration issue in the plugin... I've fixed the bug, and will push the patch out shortly.

Sorry for the false alarm! 🙃

**Comment by bencroker** [comment]
@lindseydiloreto I'd like to see your fix for future reference, if you don't mind sharing.

**Comment by lindseydiloreto** [comment]
In an effort to migrate settings from the old plugin (Smart Map) to the new one (Google Maps), it needs to copy the old settings and then write them to Google Maps. So the migration runs a command like this...

```php
Craft::$app->getPlugins()->savePluginSettings(GoogleMapsPlugin::$plugin, $settings);
```

The problem is, it was running that _while the plugin was still being installed_. Which just confused Craft internally, forcing it to leave those values out of the Project Config file.

I moved the `savePluginSettings` call into an `AFTER_INSTALL_PLUGIN` event, and everything is running much more smoothly. I haven't pushed this fix live quite yet (it's bundled with other migration fixes), but I hope to have it out by the end of the week.

**Comment by bencroker** [comment]
Makes sense, thanks for sharing and good luck!
