### ISSUE TITLE
Error with Permissions-Policy header: Parse of permissions policy failed because of errors reported by structured header parser.

### ISSUE THREAD

**Issue by kevinmu17** [craftcms/cms#7915]
### Description
Somehow i'm getting this error since a few days. I saw something in the security change logs about craft sending a new policy by default. Can this be the case?

I'm setting additional headers in the .HTACCES
`Header always set Permissions-Policy "geolocation=(self); midi=(self); sync-xhr=(self); microphone=(self); camera=(self); magnetometer=(self); gyroscope=(self); speaker=(self); fullscreen=(self); payment=(self)"`

### Steps to reproduce
1. But the code above in your HTACCESS
2. Errors will follow

### Additional info
- Craft version: Craft Pro 3.6.13
- PHP version: 7.4.16
- Database driver & version: MariaDB 10.3
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
Yeah as of Craft 3.6.13 craft started sending a `Permissions-Policy: interest-cohort=()` header to prevent FLoC tracking, due to privacy concerns.

I just added a new `permissionsPolicyHeader` config setting, which can be set to override the default value or disable the header altogether.

```php
'permissionsPolicyHeader' => null,
```

**Comment by brandonkelly** [comment]
Annnnnnd 3.6.14 is out now.
