### ISSUE TITLE
Internal Server Error: Saving image in "" format is not supported

### ISSUE THREAD

**Issue by lukebailey** [craftcms/cms#7916]
### Description

Since upgrading to Craft 3.6.13 we are seeing an internal server error on some entries in the control panel. It looks like this might be because of the Dukt video plugin (https://github.com/dukt/videos/issues/54) but that has not been updated recently so wondering if the symptom is something Craft related?

![image](https://user-images.githubusercontent.com/3185073/117845186-39c58e00-b278-11eb-96f8-5e9ff133a20a.png)

### Steps to reproduce

1. Upgrade to Craft 3.6.13
2. Visit entry with a field that calls the following code:

https://user-images.githubusercontent.com/3185073/117845847-d0924a80-b278-11eb-88c2-1425c8614669.png

### Additional info

- Craft version: 3.6.13
- PHP version: 8.0.3
- Database driver & version: mysql
- Plugins & versions: Dukt 2.0.14

**Comment by brandonkelly** [comment]
Do you have any assets without file extensions?
