### ISSUE TITLE
Please add a `CRAFT_MODULES_PATH` constant

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#7921]
### Description

I've just been brought into a project with a very unusual directory structure. Several common folders are not where you would expect them to be. And for that, the `CRAFT_TEMPLATES_PATH` constant has been invaluable! This may be the first time I've ever used it, and it works flawlessly. 

https://craftcms.com/docs/3.x/config/#php-constants

Surprisingly, it seems like there is no `CRAFT_MODULES_PATH` constant available... How would I reach a `modules` folder which has been put in a weird location?

Would it be possible to add a constant for the `CRAFT_MODULES_PATH`?

**Comment by ccchapman** [comment]
I don't think Craft knows or needs to know where modules are located. It would look in `modules/` with a fresh installation only because that's [in the Composer autoload](https://github.com/craftcms/craft/blob/e6bcaa47ea4924837e2bdb53a89a7cfa7026c9d5/composer.json#L30).

**Comment by lindseydiloreto** [comment]
@ccchapman Ah, thanks, you are correct! The path is only relevant to the Composer autoload, and not to Craft itself.

I guess that's why it's never come up before! 😄
