### ISSUE TITLE
Normalize element-specific search attributes

### ISSUE THREAD

**Issue by mattstein** [craftcms/cms#7927]
### Description

The docs [previously recommended](https://github.com/craftcms/docs/commit/2f8a314744f1c706203c3f8c9098fb54473fe9b5) User-specific search attributes that do not work as advertised because of their case:

- `firstName`
- `lastName`
- `fullName`

You can observe this in the latest Craft version, using MySQL or PostgreSQL, by searching for something like `fullName:brandon` when a user named “Brandon” has an active account yet doesn’t appear as a search result. Searching instead for `fullname:brandon` works as expected.

This is because the `searchindex` table’s `attribute` values are all lowercased. You can manually rename the `fullname` attribute values to `fullName` in the database to reverse the behavior above.

So lowercasing those custom attributes before querying the database would be ideal.

**Comment by brandonkelly** [comment]
Fixed this!
