### ISSUE TITLE
Children of homepage getting __home__ in URIs

### ISSUE THREAD

**Issue by nickdunn** [craftcms/cms#7932]
Craft 3.6.13

I have an entry with slug of `__home__` to be the homepage. Recently children under this how get `__home__` in their URIs. I recently upgraded to 3.6.13 but can't be sure when this may have regressed. 

I'm using `{parent.uri}/{slug}` as the Entry URI Format.

<img width="897" alt="Screenshot 2021-05-13 at 15 10 20" src="https://user-images.githubusercontent.com/39560/118137870-9aca9e80-b3fd-11eb-9f97-5c0d269d2eb5.png">

**Comment by nickdunn** [comment]
> [BK via Discord] uri is just a property, not a method, so there’s not really an opportunity to change it. Maybe we could add a getParentUri() method that strips it out though. Can you create a GH issue requesting it? AFK at the moment

**Comment by brandonkelly** [comment]
Not a regression. Will look into adding that `getParentUri()` method for 3.7. In the meantime you can do:

```twig
{{ parent and parent.uri != '__home__' ? parent.uri }}/{slug}
```

**Comment by nickdunn** [comment]
Thanks for confirming!

**Comment by brandonkelly** [comment]
Added for 3.7.
