### ISSUE TITLE
Draft entry not returned when using relatedTo

### ISSUE THREAD

**Issue by degraaf** [craftcms/cms#7933]
### Description

Cannot query a draft via GraphQl when the entry query relies on a category relation

### Steps to reproduce

1. Create an Entry type with a category field "regions", allowing multiple category relations to a "Region" category
2. GraphQL query (see below) uses relatedTo query to return Entry related to a given region(s)
3. Same query also returns Entry regardless of region (availableRegions), used to identify if entry is available in other regions
4. When entry is published query returns correctly for regions in field
5. When a Draft is created referencing a new region category, the query returns null (availableRegions still returns the new region)

Perhaps it is by-design for drafts to not track relations? Would be good to clarification if this is expected behaviour.

### Additional info

- Craft version: 3.6.11.2
- PHP version: 7.4
- Database driver & version (local dev): 5.7.31 MySQL Community Server
- Database driver & version (qa, uat, prod): AWS Aurora 5.7.12 MySQL Community Server
- Plugins & versions: N/A

### GraphQl query:

```
query($uri: [String], $section: [String], $site: [String], $regions: [QueryArgument]) {
  availableRegions: entry(uri: $uri, section: $section, site: $site) {
    uri
    regions {
      id
    }
  }
  entry(uri: $uri, section: $section, site: $site, relatedTo: $regions) {
    type: typeHandle
    id
    slug
    uri
    title
    ...otherFields
  }
}
```

**Comment by brandonkelly** [comment]
Drafts aren’t included in query results by default. 

As a starting point, go to your GraphQL schema’s settings and make sure drafts are included:

![GraphQL schema settings showing “Allow listing element drafts” is checked](https://user-images.githubusercontent.com/47792/118264353-6e01a000-b46c-11eb-83a4-754304f4d6df.png)

Then, in your `entry` query, add `drafts: null` to the arguments list.

**Comment by degraaf** [comment]
Thanks Brandon, we had the listing settings correct but will now use the 'drafts' query param to ensure the draft is returned when previewing.

Here's my results when querying for drafts. Seeing some odd behaviour when testing with GraphiQl, could you confirm this is right?

`drafts: false` returns only published versions and relations (i.e. default behaviour)

`drafts: null` returns the latest "Draft 6" version when I query by the new related category (3 in total), but when querying by one of the existing categories it returns the latest published entry and categories (2 in total), not the draft

`draft: true` returns the new "Draft 6" when I query by the new relation, but returns the oldest "Draft 1" version when I query by an existing relation, or when I don't include relations in the query at all. This doesn't seem right. Would/should the GQL query be affected by one of the preview query params `token`, `x-craft-preview` or `x-craft-live-preview`?

**Comment by degraaf** [comment]
Actually have found that `drafts: null` returns the first thing that meets the criteria and `drafts: true` returns the oldest draft available that meets the criteria. So with multiple drafts, the oldest is always returned.

`entries()` queries are another matter though. I find that if I request drafts in `entries` queries, I get ever single draft available. This means you can't load a list of entries and just get the latest version or draft if they exist. Or, for example, a nav structure, you'll get multiple entries appear if you have more than one draft. Would be great if you could limit the number of drafts per entry that are returned.

**Comment by brandonkelly** [comment]
It sounds like things are working as expected. `entry` will only return one result. _Which one_ will depend on the `orderBy` argument. By default for entries, it’s based on their location in the structure if it’s a channel section, or the `postDate` value for channel sections. If your drafts share the same `postDate` as the main entry, it’s a crapshoot as to which one will end up getting returned.

If you add `orderBy:"id desc"` you’ll always get the entry/draft that was created most recently.

> I find that if I request drafts in `entries` queries, I get ever single draft available. This means you can't load a list of entries and just get the latest version or draft if they exist.

There’s no way we could build that logic into the SQL directly. However we could add a new `drafts` field, so you could select all the entries _with_ their latest draft. I’ve posted that FR as a new issue, with an example query that would work for your use case: #7950

**Comment by degraaf** [comment]
Thanks for the clarification
