### ISSUE TITLE
Support dotx files

### ISSUE THREAD

**Issue by wei2go** [craftcms/cms#7935]
### Description
Under `craft\helpers\Assets" -> _buildFileKinds()`, can you add "dotx" to `Asset::KIND_WORD['extensions']` please?

A .dotx is a Microsoft Word document template file, see [here](https://support.microsoft.com/en-us/office/save-a-word-document-as-a-template-cb17846d-ecec-49d4-82ea-a6f5e3e8b9ae).

**Comment by brandonkelly** [comment]
Added that for the next release. Thanks for the suggestion.

**Comment by brandonkelly** [comment]
Craft 3.6.16 is out now with `.dotx` support.
