### ISSUE TITLE
Confusing button colors saving vs publishing

### ISSUE THREAD

**Issue by bencresty** [craftcms/cms#7936]
### Description

(I am not sure if somebody already mentioned this before, I thought it was, but when searching now I can't find it anywhere, so sorry if this is a duplicate);

When creating a new entry there are these two buttons on top:
![image](https://user-images.githubusercontent.com/69322733/118238730-32c99600-b499-11eb-913e-86285f678350.png)

The colors here to me are counter intuitive as we might expect that a red button is something to think twice about before hitting and higher in critical/danger range (red = danger) and gray is, well, safe to press without much consequences. 
I would say that publishing an entry is way more critical/'danger' than saving a draft, while the colors are the other way around now.

Maybe the save-button is red in this case, because it's red everywhere, so that's probably why it's chosen to keep using the red color on the save button here too, but than at least the Publish button should be red also, or even better IMO: a color that's even more prominent and shows it being even more critical, as publishing an entry is obviously way more critical than just saving a draft. When using this is prone to mistakes as the attention gets attracted by and directed to the wrong button instinctively.

Please re-think the coloring here to something more intuitive fitting the 'danger'/critical-level of the action. Thanks for considering!

**Comment by brandonkelly** [comment]
Red identifies the _primary_ form action; it’s not meant to signify “danger” vs “safe”. Entries begin as drafts so it felt like the primary action should be to keep it in that state. That was clearly the wrong choice from a publishing workflow perspective though, and it has been changed for Craft 3.7 (see #7899).
