### ISSUE TITLE
GraphQL asset interface does not expose mp4/video dimensions

### ISSUE THREAD

**Issue by riccardolardi** [craftcms/cms#7939]
### Description

Is there any chance to implement this in near future and in the meantime is there any workaround to retrieve mp4/video dimensions in any other way? 
I'm working on a masonry frontend which consists of images and videos where every asset can have different dimensions. Currently I can't seem to get dimensions data on the mp4 video assets through GraphQL (width and height fields return null).

**Comment by andris-sevcenko** [comment]
That's not a GraphQL limitation, though, as Craft doesn't have the capability to figure out the dimensions for a video file, yet.

If the values are in the `assets` table, they will get returned, so a possible solution is to populate those fields manually in the database.
