### ISSUE TITLE
Double click on open matrix block to close it doesn't always work in preview mode

### ISSUE THREAD

**Issue by bencresty** [craftcms/cms#7940]
### Description

When adding and editing matrix blocks I constantly doubleclick the header of a block to collapse or open it. Unfortunately this isn't always working when the preview is open. Having multiple fields inside matrix blocks this makes having a good overview and a nice workflow difficult when not able to close blocks quickly. Especially because now it's scrolling 'everywhere' on double click, which is obviously unwanted.

The problem seems to be that the first click of the double click scrolls the window with the edit screen up making the second click of that double click to fail and causes two issues: 
1) It scrolled unwantedly up
2) It didn't close

### Steps to reproduce

1. open preview on an entry with matrix blocks
2. try to close a matrix blocks with a double click on its header

### Additional info

- Craft version: 3.6.13
- PHP version: 7.4.16

**Comment by brandonkelly** [comment]
This is fixed now for the next release.

**Comment by brandonkelly** [comment]
Craft 3.6.15 is out with a fix for this.

**Comment by bencresty** [comment]
@brandonkelly Thanks!
