### ISSUE TITLE
Show entries from all sites in the My Drafts widget

### ISSUE THREAD

**Issue by JoshCoady** [craftcms/cms#7942]
### Description
I dont know which site is used by default on the dashboard page, but the My Drafts widget doesnt show any drafts for our writers even though they have some. If I edit the widget's query to use `->site('*')` then their drafts are listed as expected.

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just fixed this for the next release.

**Comment by brandonkelly** [comment]
Craft 3.6.15 is out now with that fix.
