### ISSUE TITLE
Can't add matrix blocks after switching entry type (JS error?)

### ISSUE THREAD

**Issue by shornuk** [craftcms/cms#7943]
### Description
We have a blog section that has a couple of entry types. When creating a new entry everything is fine, but if you switch the entry type, you can't add any matrix blocks. (Click the block and nothing happens)

Getting a JS error in console

`undefined is not an object (evaluating 'this.$overflowTabBtn.data("menubtn").menu')`

### Additional info

- Craft version: 3.6.14
- PHP version: 7.4
- Database driver & version: MySQL 8

**Comment by brandonkelly** [comment]
Thanks for reporting! Just fixed this for the next release.

**Comment by brandonkelly** [comment]
Craft 3.6.15 is out now with that fix.
