### ISSUE TITLE
Provide method for plugins to check if Craft is currently being updated

### ISSUE THREAD

**Issue by BenParizek** [craftcms/cms#7946]
### Description

In Sprout Email I need to register dynamic events based on the triggers that users want to use to trigger email notifications. To avoid sending triggered email during Craft updates, I currently check to see if Craft is updating using some code that I copied from the web Application class:

https://github.com/craftcms/cms/blob/faa2591d22f59294241c9cbec59bee53104a112a/src/web/Application.php#L660-L671

In reviewing this code recently I noticed that Craft had updated the logic in these lines slightly. In order to stay in sync, it would be nice to have this method broken out so it stands alone and we can just call the method rather than have to periodically review the code to make sure the logic is in sync.

**Comment by brandonkelly** [comment]
Just released Craft 3.6.15 with a new `craft\services\Updates::getIsUpdatePending()` method.
