### ISSUE TITLE
Schema::TYPE_JSON fields aren’t saved to the database as JSON

### ISSUE THREAD

**Issue by joshuabaker** [craftcms/cms#7951]
### Description

I’m building a custom field using the JSON schema type and, no matter what I do, I can’t get the value to save in the database as raw JSON without it being encoded.

Currently data is encoded as `"{\"foo\": 1}"` and not `{"foo": 1}`, which prohibits any queries on that field (e.g. `foo` is always `null` for `select field_test, JSON_EXTRACT(field_test, '$.foo') as foo from content`).

I’ve tried a few things, including various encoding/decoding in both the `normalizeValue` and `serializeValue` methods. It looks like [this line](https://github.com/craftcms/cms/blob/5afff2f3c74c385f85d97217bd1d514dcf0dc12e/src/helpers/Db.php#L121) always overrides this though.

### Steps to reproduce

1. Create a custom field using `Schema::TYPE_JSON` for `getContentColumnType`
2. Save valid JSON to the field

### Additional info

- Craft version: 3.5.17.1
- PHP version: 7.4.12
- Database driver & version: MySQL 5.7.32

**Comment by brandonkelly** [comment]
Craft doesn’t currently support JSON columns, since MySQL didn’t get support for them until 5.7.8, but Craft supports as far back as 5.5.0. If/when we bump our MySOL requirement, we can add support for it.

**Comment by joshuabaker** [comment]
Ah, that would explain it. Thanks for the quick response, @brandonkelly.

**Comment by brandonkelly** [comment]
@joshuabaker updated my previous comment with how to compensate, ICYMI.
