### ISSUE TITLE
Detect and warn against running craft command line as root

### ISSUE THREAD

**Issue by rob-baker-ar** [craftcms/cms#7955]
### Description

Our servers are in a Linux environment (dev, staging and live) and so I often find myself running craft commands like this:

`sudo -u www-data ./craft update/info`

The command executes as the user that owns the project path, any files created have the right owner and it is able to modify / delete files if necessary. Executing in this way allows the server to quite rightly have `/usr/sbin/nologin` or similar as the shell for the `www-data` user.

When commands accidentally run as root, files created end up being owned by root and can cause issues if I don't remember to `chown` the files back to `www-data`.

Composer from the command line spots this and warns against doing anything as root.

This: https://www.php.net/posix_getuid  `posix_getuid() === 0` is a way of detecting the current user but is not present in Windows, but TBH, the check might not even be necessary in Windows.

**Comment by angrybrad** [comment]
Relevant Composer bits here: https://github.com/composer/composer/blob/master/src/Composer/Console/Application.php#L250-L274

**Comment by angrybrad** [comment]
Added this for 3.7 - you'll get a prompt warning you if you're running as root and asking if you want to continue. You can also set a `CRAFT_ALLOW_ROOT=true` env var to always allow it (thinking mainly for dockerized containers that run at root).

**Comment by jordikroon** [comment]
@brandonkelly would you mind re-intoducing the CRAFT_ALLOW_ROOT (or general.php) environment check? We have root enabled by-design on our local docker environment, and it would be helpful to have a way to suppress the confirmation by config setting.

**Comment by brandonkelly** [comment]
@jordikroon Fair enough. Just added support for `CRAFT_ALLOW_SUPERUSER` (to be consistent with `COMPOSER_ALLOW_SUPERUSER`), for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.8 is out now with that change.
