### ISSUE TITLE
Email Transport: SMTP, Sendgrid, Gmail Not working CRAFT 3.6.15

### ISSUE THREAD

**Issue by danieladarve** [craftcms/cms#7962]
Hello,
I am unable to send emails when using a transport type other Sendmail after upgrading to Craft 3.6.15.

When testing the configuration, craft returns:
```There was an error testing your email settings.```

I have tried many configurations and ruled out wrong passwords or API keys.
Same result on a clean installation of Craft 3.6.15 without any plugins installed.

There are no error logs generated that can indicate what the issue actually is. 

I am currently Using Craft 3.6.15 and tested using php 7.4 and 8

- Craft version: 3.6.15
- PHP version: 7.4.19 
- Database driver & version: MySQL 8.0.23
- Plugins & versions:  SendGrid 1.2.2 and also tested without any plugins

Thank you

**Comment by brandonkelly** [comment]
Unfortunately, SwiftMailer swallows the actual error which is why it doesn’t get output/logged. Most likely this is something environmental; can you please email support@craftcms.com and we can try to help from there?
