### ISSUE TITLE
View/Preview links for homepage yield 404

### ISSUE THREAD

**Issue by nickdunn** [craftcms/cms#7982]
### Description
When clicking "View" or "Preview" buttons for an entry with `__home__` as its slug, Craft renders a 404 rather than loading the page. The globe icon in entry indexes gives the correct URL.

The "View" and "Preview" links are going to `/__home__`, whereas the icon in entry indexes go to (correctly) `/`.

This is the case with both of these Entry URL Formats:

1. `{parent.uri}/{slug}`
2. `{{ parent and parent.uri != ''__home__'' ? parent.uri }}/{slug}`

### Additional info

- Craft version: 3.6.15
- PHP version: 7.4

**Comment by brandonkelly** [comment]
Are you using Craft Pro or Solo? If Pro, what is your preview target’s URL set to, in your section’s settings?

By the way, there is a syntax error in your second URI format example – those double-single quotes (`''`) should either be single quotes (`'`) or double quotes (`"`).

**Comment by nickdunn** [comment]
Weird, the quotes must have been munged by Github — I have this correctly as the Entry URL format:

```
{{ parent and parent.uri != '__home__' ? parent.uri }}/{slug}
```

And this as the Preview Target URL Format:

```
{uri}
```

**Comment by brandonkelly** [comment]
Try changing the preview target URL to `{url}` instead of `{uri}`.

**Comment by nickdunn** [comment]
> Try changing the preview target URL to {url} instead of {uri}.

Nailed it. Thanks!
