### ISSUE TITLE
Unable to scroll down pages - scrolls back to top

### ISSUE THREAD

**Issue by Coysh** [craftcms/cms#7983]
### Description
On some entries in Craft that have fields that stretch the page vertically, scrolling the page does not work and returns the user back to the top. See attached video

https://user-images.githubusercontent.com/5764356/119689491-ceb3b400-be40-11eb-801d-38328b1e304f.mp4

### Steps to reproduce

1. Open an entry in Craft
2. Scroll down the page

### Additional info

- Craft version:  Craft Pro 3.6.14
- PHP version: 7.4.16
- Database driver & version: MySQL 5.7.33
- Plugins & versions:
Amazon S3 | 1.2.11
Asset Rev | 6.0.2
AsyncQueue | dev-master
Bugsnag | 2.1.2
Bulk Edit | 2.0.5
Church Search | 1.0.0
Cookies | v1.x-dev
Crawler Detect | 1.0.1
Dumper | 2.0.0
Element API | v2.x-dev
Entry Instructions | 1.0.7
Environment Label | 3.2.0
Expanded Singles | 1.1.3
Feed Me | 4.3.6
Forms | 3.11.4.1
ImageOptimize | 1.6.25
Image Resizer | 2.1.0
Mailchimp Subscribe | 4.0.0
Mandrill | v1.x-dev
Minify | v1.x-dev
No-Cache | 2.0.7
Organisation Search | 1.0.0
Password Policy | 1.1.0
Position Fieldtype | 1.0.17
Reasons | 2.2.4
Redactor | 2.8.7
Retour | 3.1.53
SEO | 3.3.41
Stripe Payments | 3.3.3
Super Table | 2.6.7
Transcoder | 1.2.14
Twig Profiler | 1.0.1
Typed link field | 1.0.25
Typogrify | v1.x-dev
Video Embedder | 1.1.4
Webperf | v1.x-dev
Workflow | 1.5.9

**Comment by andris-sevcenko** [comment]
Thanks for reporting!

That issue has been fixed (https://github.com/craftcms/cms/commit/59c17576b7cd4cb9cc661f5a0ad14cde5786be26)  since Craft 3.6.15, so an update should do the trick!
