### ISSUE TITLE
search for exact match in table field

### ISSUE THREAD

**Issue by aloco** [craftcms/cms#7984]
### Description

I just noticed that keywords in the searchindex table are inserted with a leading and trailing whitespace. I am sure there is a reason for this. However, according to the docs, I can do this: `body::salty` to find an entry with a custom field named "body" exactly matching "salty" . This doesn´t return results. When searching for `body:: salty ` (including the whitespaces) it is working as expected. Is this a bug, "wrong" docs or am I missing something here?

I can reproduce this also in the control panel search.

Thank you!

### Steps to reproduce

1. Create a field called `body`
2. Make it searchable
3. Use an element query with "exact" match on this field and don´t include whitespaces
```
$results = \craft\elements\Entry::find()
    ->search('body::salty')
    ->all();
 ```
### Additional info

- Craft version: 3.6.7
- PHP version: 7.4
- Database driver & version: MySQL 5.7

**Comment by aloco** [comment]
Hi, 

I did further investigation on this and need to correct my initial report. It seems that adding a whitespace after `::` just searches in every field. This makes sense since you can add multiple search terms. I added some fields of different types and it seems like you can´t search in table fields with `::` - in contrast to that `:` works. I thought `::` would also work because I stumbled over this https://craftcms.stackexchange.com/a/28462

So searching for exact values in a table field is still not possible right?

Thank you

**Comment by brandonkelly** [comment]
Just fixed this for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.6.15"` and run `composer update`.

After updating, note that you will need to resave your entries via the `resave/entries` command in order to fix the search indexes for existing entries.

```bash
> php craft resave/entries --section=yourSectionHandle --update-search-index
```

**Comment by brandonkelly** [comment]
Craft 3.6.16 is out now with that fix.

**Comment by aloco** [comment]
Thanks @brandonkelly it is working perfect when having a table with only one column. As soon as you have two columns, it is not working at my side. Just for clarification what I am trying to achieve:

I have a table with two columns: codes and titles. I want to search for entries with specific codes in that table. The search request could have multiple codes and I try to search for them like this `code:salty OR code:dog` (https://craftcms.com/docs/3.x/searching.html#supported-syntaxes)

Thank you!

**Comment by brandonkelly** [comment]
That’s expected, because if you have multiple values in the table (whether via multiple columns, multiple rows, or both), then all of those values are going to get indexed as search keywords. So exact match searching (`::`) won’t really work anymore, unless you are searching for all of the values together.

**Comment by aloco** [comment]
thank you for your fast response - hmm ok I see .. so a table with two rows (salty, dog) and a column named `code` would be indexed as ` salty dog ` and therefore `::` would only work when search for `salty dog` and not `salty` alone. 

Initially we used `:` but we saw that searching for a code like `123456` also matches on `1234567` - do you see a way in solving this using tables or should we consider another data structure 😅

**Comment by brandonkelly** [comment]
That behavior is determined by the [defaultSearchTermOptions](https://craftcms.com/docs/3.x/config/config-settings.html#defaultsearchtermoptions) config setting, which has `subRight = true` by default.

You can override globally via the config setting, or you can override for one individual element query by passing a hash into the `search` param:

```twig
{% set entries = craft.entries()
  .section('mySection')
  .search({
    query: 'salty dog',
    subRight: false,
  })
  .all() %}
```
