### ISSUE TITLE
Super slow to create and save entries when environment=production

### ISSUE THREAD

**Issue by danielenstrom** [craftcms/cms#7985]
### Description
We recently changed servers and bumped craft to 3.6.15, after that it takes around 25-30 seconds to save an entry (or create a new). This problem is only when ENVIRONMENT is set to **production**, when changing the variable to **staging** everything is blazing fast as earlier. 

The only config difference between production and staging is the "isSystemLive" setting. 

### Additional info

- Craft version: 3.6.15
- PHP version: 7.3.27
- Database driver & version: MariaDB 10
- Plugins & versions: Blitz 3.9.0, Super Table 2.6.8, SEOmatic 3.3.42, Retour 3.1.53...

**Comment by brandonkelly** [comment]
@danielenstrom Take it you found the culprit? Mind sharing what it was?

**Comment by danielenstrom** [comment]
@brandonkelly, yes, it was the SEOmatic plugin that got CURL timeout, trying to ping google/bing about new sitemaps over port 80 (which is closed in our firewall), disabled "**Submit Sitemap Changes**" and everything works just fine.

Thanks for checking in (and sorry I didn't check my logs more carefully)
