### ISSUE TITLE
Don't show the "Delete with descendants" element action for structures with max level 1

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#7988]
### Description

It'd be nice if the "Delete with descendants" element action didn't render, if the structure is configured with a max level of 1. 

Alternatively, that it rendered in a disabled state, like the "Create new child entry" action does when it's n/a.

![image](https://user-images.githubusercontent.com/298510/119905034-b2506e00-bf4b-11eb-9a87-4707b3a42f44.png)

![image](https://user-images.githubusercontent.com/298510/119905288-3c98d200-bf4c-11eb-8f2e-9624b6af9477.png)

**Comment by brandonkelly** [comment]
Just fixed this for the next release. Going forward, “Create a new child entry” and “Delete (with descendants)” won’t be visible at all, for single-level structures.

**Comment by brandonkelly** [comment]
Craft 3.6.16 is out now with that change.
