### ISSUE TITLE
When `phpSessionName` is set, it's not possible to change panel language

### ISSUE THREAD

**Issue by anvart** [craftcms/cms#7994]
### Description

Basically, it's all in the title. I guess there are more side effects, but I haven't make any further research.

### Steps to reproduce

1. Set `phpSessionName` in `config/general.php`
2. Change panel user language
3. Observe panel falling back to a default one

### Additional info

- Craft version: 3.6.15
- PHP version: 7.3.27
- Plugins & versions: no plugins, tried on fresh installation

**Comment by anvart** [comment]
Well, I found the source of the problem: I used a dot in the value. 

It's somehow covered by PHP docs:

> if you try to name a php session "example.com" it gets converted to "example_com" and everything breaks.
> don't use a period in your session name.

Closing.

**Comment by brandonkelly** [comment]
Glad you got it sorted @anvart!
