### ISSUE TITLE
[FR] Don't display delayed queue jobs in CP sidebar

### ISSUE THREAD

**Issue by naboo** [craftcms/cms#7998]
### Description
Since the great update https://github.com/craftcms/cms/issues/7692 with having delayed queue jobs visible in the Manager another thing appeared which from a UX point of view is a little confusing. If you have a delayed job it's shown in the CP sidebar until it runs. Problem here is that you get the feeling something is wrong or a queue job is stuck.

Can it be changed so delayed jobs aren't visible in the CP sidebar? Only current running jobs.

**Comment by brandonkelly** [comment]
Good call. Just released Craft 3.6.16 with this change.
