### ISSUE TITLE
Valid email format

### ISSUE THREAD

**Issue by SayChi** [craftcms/cms#8000]
### Description
A client has brought to my attention that a certain format of email adres does not get accepted. My initial thought was "yeah that's invalid, how do they even have that adres?", but if wikipedia is to be believed, it seems to actually be valid.

The format in question:
example-@domain.com

The hyphen before the @ seems to be valid according to [this list](https://en.wikipedia.org/wiki/Email_address#Examples)

Is this on purpose or a simpel oversight somewhere in some library? And if it's on purpose, any chance i could overwrite it for a specific project?

### Steps to reproduce

1. Add user
2. Email: example-@domain.com
3. Save
4. Cry, because email formats are hell

### Additional info

- Craft version: 3.6.12.1
- PHP version: 7.4.18
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Email validation is provided by Yii. Can you please post over at https://github.com/yiisoft/yii2/issues/ instead?

**Comment by ccchapman** [comment]
I think the email does actually validate with Yii's email validator. You should find the stack trace for this exception (`./storage/logs/web.log`) to see which library it's coming from.

**Comment by SayChi** [comment]
Posted the [issue](https://github.com/yiisoft/yii2/issues/18693), thanks
