### ISSUE TITLE
allowAdminChanges option to make Settings read only

### ISSUE THREAD

**Issue by alexwybraniec** [craftcms/cms#8002]
### Description

After developing a few Craft sites in the last year, and having had a nightmare debugging changes in a production environment, would it be possible to allow a mode where Settings (and other things usually hidden by allowAdminChanges false) were viewable but not editable?

There are plenty of situations where seeing the Settings values is really important, even if you don't want clients to be able to edit them.

**Comment by brandonkelly** [comment]
This was previously requested by #4371. Our solution was to add the Project Config utility, with a read-only view of the entire project config data (added in Craft 3.5). Have you considered checking that?

If you still think it would be valuable, please comment over there, and we can reopen it.
