### ISSUE TITLE
Allow ConfigurableComponent::settingsAttributes() to pick up on behavior defined properties

### ISSUE THREAD

**Issue by myleshyson** [craftcms/cms#8004]
### Description

I'm trying to add a `searchWeight` setting to every field in craft using behaviors. Currently though I'm stuck because [ConfigurableComponent](https://github.com/craftcms/cms/blob/develop/src/base/ConfigurableComponent.php) is only using reflection to determine settings properties...which will ignore Behavior defined properties.

Something like this added to `settingsAttributes()` should sort it out.

```php
    if (!empty($this->getBehaviors())) {
            foreach ($this->getBehaviors() as $behavior) {
                $class = new \ReflectionClass($behavior);
                foreach ($class->getProperties(\ReflectionProperty::IS_PUBLIC) as $property) {
                    if (!$property->isStatic() && !$property->getDeclaringClass()->isAbstract() && !$property->getName() === 'owner') {
                        $names[] = $property->getName();
                    }
                }
            }
        }
```

**Comment by brandonkelly** [comment]
I’ll look into whether this is a safe change to make for 3.7.

**Comment by brandonkelly** [comment]
Decided to make this event-driven rather than automatically pull in public properties from all attached behaviors.

So this will be possible as of 3.7

```php
use yii\base\Event;
use craft\events\DefineValueEvent;

Event::on(SomeComponent::class, SomeComponent::EVENT_DEFINE_SETTINGS_ATTRIBUTES, function(DefineValueEvent $event) {
    $event->value[] = 'myBehaviorPropertyName';
});
```
