### ISSUE TITLE
Validation of number field inside of Matrix (0.00, Craft Pro 3.6.10)

### ISSUE THREAD

**Issue by bkrsmanovic** [craftcms/cms#8007]
### Description
When you have inside matrix, a block with a Number field, and you set min / max value (any integer), like 0 or 1 or 200, after saving the field, and when you open matrix again, you can see that fields are no longer 0, 1 or 200, but 0.00, 1.00 or 200.00. Two 0 are added in decimal place, which after trying to save matrix again, prompt an error: Must be an integer.
So you have to go through all number fields in matrix, and remove leading zeroes, so there is no validation error.

You can image how frustrating it can be (i will show image below).

### Steps to reproduce

1. Create matrix with 1 block and 1 number field
2. Add min / max value as any integer (0, 1, 200...).
3. Save field, open Matrix again and save it again. It will prompt an error.

### Additional info

- Craft version: 3.6.10
- PHP version: 7.4.14 (tried it also on 8.0.1)
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

![number_field_bug](https://user-images.githubusercontent.com/15169280/120472317-0624e200-c3a6-11eb-8325-672795f2ae39.png)

**Comment by bkrsmanovic** [comment]
Also, letting you know, I tried on latest craft pro version (.16) and it is bugged as well.

**Comment by brandonkelly** [comment]
Thanks for reporting that! Was able to reproduce on an environment without the Intl extension, and fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.6.16"` and run `composer update`.
