### ISSUE TITLE
Adding raw twig filter to errors in  _includes/forms/errorList.twig 

### ISSUE THREAD

**Issue by myleshyson** [craftcms/cms#8008]
### Description

I'm creating some validation for a custom field and wanting to make a validation message with something like `"This thing is already associated with the following entry: <link-to-that-other-entry>".` Currently though an anchor tag won't render because the [errorList template](https://github.com/craftcms/cms/blob/develop/src/templates/_includes/forms/errorList.html) isn't using the `raw` filter. 

Since it doesn't seem possible to straight override core twig templates I think it would be nice if the raw filter was used in that errorList template so that error messages can be more robust as needed.

**Comment by brandonkelly** [comment]
We don’t allow HTML for security reasons, however I’ve just added support for Markdown syntax. So your validation error could be:

```markdown
This thing is already associated with the following entry: [Entry Title](entry-url)
```

**Comment by myleshyson** [comment]
Awesome!
