### ISSUE TITLE
Customize "Publish" & "Save Draft" Button Labels

### ISSUE THREAD

**Issue by walame** [craftcms/cms#8009]
### Description

We are creating a custom workflow in Craft to accommodate different stages of editing a document, and we'd love to have the ability to customize the "Publish" & "Save Draft" buttons for different stages of an article.

As an entry goes from one person to the next, it isn't intuitive to click "publish" at each of these stages when the entry is really only getting published at the end.

**Comment by brandonkelly** [comment]
We’ve done away with “Publish” for the most part in 3.7. You might want to update to 3.7 and check out the [changes we’re making to the publishing workflow](https://github.com/craftcms/cms/pull/7899) before you go too far down the road of customizing it.

The 3.7 Beta will be launching in a couple weeks, or you can get on the alpha right now by changing your `craftcms/cms` version requirement in `composer.json` to `"3.7.x-dev as 3.7.0-alpha"`, then run `composer update`.

Will close this issue for now, but happy to reopen it if you think it’s still a valid feature request once you’re running 3.7.
