### ISSUE TITLE
Globals - Field Layout, field column width not respected

### ISSUE THREAD

**Issue by vonscriptor** [craftcms/cms#8010]
### Description

Changing the default field column width does not change the layout of those Globals fields.

### Steps to reproduce

1. Go to a Global Set (i.e. /admin/settings/globals ...) and modify field(s) column width (i.e. 25%, 50%, 75%).
2. View the modified Globals fields (i.e. /admin/globals ...) and notice that the width of the modified fields have not changed.

### Additional info

- Craft version: 3.6.15

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you double-check that the field width changes actually saved?

**Comment by vonscriptor** [comment]
My mistake, no bug.

Rather, a feature to set a Matrix Block Type column width could be useful.

Example: I have 1 Global set with a Matrix field. I was hoping to have each Matrix item take up 50% width and wrap.

Current:

<img width="1355" alt="matrix-block-col-width-current" src="https://user-images.githubusercontent.com/1682225/120939365-a04d9880-c6cc-11eb-8730-7eb2fe516276.png">

New:

<img width="1354" alt="matrix-block-col-width-new" src="https://user-images.githubusercontent.com/1682225/120939370-a6437980-c6cc-11eb-9dd9-978314f839e4.png">


Thoughts?

**Comment by brandonkelly** [comment]
Hm I dunno… not sure how well that would work with varying-height Matrix blocks. Feel free to post as a new GH issue though.
