### ISSUE TITLE
Add users/create console command

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#8014]
### Description

Would be especially helpful for project onboarding, when a dev may have a database dump and local running site, but no Craft user/CP access.

- [x] Should include a "Make them an admin?" prompt
- [x] Possibly an --admin flag to bypass
- [x] Non-interactive options?

**Comment by leevigraham** [comment]
@timkelty Any chance of adding a users/delete command in this PR? I would love a create / delete combo for automated testing.

**Comment by leevigraham** [comment]
@timkelty Maybe something like:

```php
<?php


namespace modules\site\console\controllers;


use Craft;
use craft\console\Controller;
use craft\helpers\Console;
use yii\console\ExitCode;

class UsersController extends Controller
{
    public ?string $transferTo = null;

    /**
     * @inheritdoc
     */
    public function options($actionID)
    {
        $options = parent::options($actionID);

        if ($actionID === 'delete') {
            $options[] = 'transferTo';
        }

        return $options;
    }

    public function actionDelete(string $usernameOrEmail): int
    {
        $user = Craft::$app->getUsers()->getUserByUsernameOrEmail($usernameOrEmail);

        if (!$user) {
            $this->stdout("No user exists with a username/email of “{$usernameOrEmail}”." . PHP_EOL);
            $this->stdout('done' . PHP_EOL, Console::FG_GREEN);
            return ExitCode::OK;
        }

        // Are we transferring the user's content to a different user?
        if($this->transferTo) {
            $transferToUser = Craft::$app->getUsers()->getUserByUsernameOrEmail($this->transferTo);
            if (!$transferToUser) {
                $this->stderr("No user (transfer to) exists with a username/email of “{$this->transferTo}”." . PHP_EOL, Console::FG_RED);
                return ExitCode::UNSPECIFIED_ERROR;
            }
            $user->inheritorOnDelete = $transferToUser;
        }

        if (!Craft::$app->getElements()->deleteElement($user)) {
            $this->stderr(Craft::t('app', 'Couldn’t delete the user.'));
            return ExitCode::UNSPECIFIED_ERROR;
        }

        $this->stdout('done' . PHP_EOL, Console::FG_GREEN);
        return ExitCode::OK;
    }
}
```

**Comment by timkelty** [comment]
> I would love a create / delete combo for automated testing.

@leevigraham just to clarify, the use case you're describing is _not_ testing via unit test (eg phpunit/codeception), right?

**Comment by leevigraham** [comment]
@timkelty 

> the use case you're describing is not testing via unit test (eg phpunit/codeception), right?

Correct. I'm running tests via cypress:

![image](https://user-images.githubusercontent.com/25124/121441460-346d7780-c9cd-11eb-8a4e-7e0b08c945dc.png)

Plus if we have create… why not have delete :)

**Comment by timkelty** [comment]
@leevigraham added `users/delete` in the latest PR 🎩

**Comment by timkelty** [comment]
@leevigraham give the 3.7 beta a try to test this out: https://craftcms.com/blog/craft-3-7-beta-released

Should have everything you requested 🤗

**Comment by leevigraham** [comment]
Nice one. Time to update our newism craft-boilerplate.

**Comment by leevigraham** [comment]
@brandonkelly @timkelty @mattstein  I've add a `--hard` argument to `users/delete` https://github.com/craftcms/cms/pull/8077

**Comment by timkelty** [comment]
> @brandonkelly @timkelty @mattstein I've add a `--hard` argument to `users/delete` #8077

@leevigraham LGTM, just tweaked the docblock: https://github.com/craftcms/cms/pull/8083
