### ISSUE TITLE
Volumes' field layouts erroneously change UID on every Project Config rebuild

### ISSUE THREAD

**Issue by michaelrog** [craftcms/cms#8020]
Each time we rebuild the Project Config, the UID for every Asset Volume's field layout changes.

Presumably, this implies that those field layouts are being destroyed and re-created on every Project Config rebuild.

At best, this makes noise in the commit history. At worst, it makes it harder to make sense of Volume settings when merging settings changes from multiple envs.

#### To reproduce:

1. Start from a fresh working directory
2. Rebuild the Project Config via CLI or CP
3. Git has noticed changed files for every Asset Volume. The UID has changed:

`userPhotos--a35713a1-7237-49a1-ac3e-0fa1d1b5bded.yaml`:
```fieldLayouts:
-  f8017d72-d47a-4715-91de-93ef22515ee4:
+  ea9c4d86-95af-453d-bb31-6e7fe48f7953:
    tabs:
      ...
```

#### Additional info:

- Craft version: 3.3.3
- PHP version: 7.4
- Database driver & version: MySQL
- Plugins: none
- @see #7115

**Comment by brandonkelly** [comment]
I’m not able to reproduce that. Can you try updating to the latest?

**Comment by michaelrog** [comment]
Yup — Confirmed that this is also an issue on the latest (`3.6.16`).

I poked around some more and discovered the following:

In the `fieldlayouts` table, there was no record of the Field Layout described by the YAML. (i.e. Neither the pre-Rebuild _nor_ post-Rebuild UID values matched a record in the database. In fact, there were no `craft\elements\Asset`-type field layouts in the database at all.)

I hit `Reapply everything` in the Project Config utility, and Craft _created_ a new Field Layout record that matched the UID from the YAML. From then on, the Rebuild action behaves normally (i.e. is no longer swapping in a random new value for the Field Layout UID every time).

So, probably, in some previous version, Craft added a Field Layout to this Volume _in the Project Config YAML_ but didn't actually write a record to the database. (I'm guessing this occurred around when `AssetTitleField` elements came on the scene, since that's the only element in this Field Layout.)

**The fix appears to be trivial: Just reapply the YAML via the Project Config utility, and Craft will create the missing record.**

**Comment by engram-design** [comment]
@michaelrog Thanks for the heads up, I can't say I tried a `apply --force` (which is "Reapply everything" I believe), so probably should've started with that.

Typically, for Craft 3.5 sites, I'm hitting `rebuild` due to all the type fixes and added comments to YAML files, because I'm treating the database as the source of truth (usually brought down from production).

We're getting closer to PC stability now!
