### ISSUE TITLE
Double-clicking selected elements in relational fields is unreliable

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#8021]
### Description

Lately, I've noticed that double-clicking elements in relational fields (i.e. to open element editor HUDs) seems unreliable.

Specifically, sometimes when I double-click an element in a relational field, the double-click won't register properly, and the HUD won't open. When this happens, the element will sometimes be selected and focused with a blue outline, and sometimes the element won't even receive focus. When the element doesn't receive focus, the browser will sometimes select a nearby text element on the page instead (like what happens when you double-click a webpage outside of any interactive element, and the browser selects text elements in close proximity to the where you clicked). 

It feels like instead of registering the double-click, it's sometimes either registering a single click or no click (on the element) at all – like I'm clicking _through_ the element, or that the element temporarily isn't responding to the pointer events for some reason. 

There are no JS errors in the browser console when this occurs.

The issue seems isolated to Craft 3.6.x+ (tested on 3.6.11 and 3.6.16), as I'm not able to reproduce at all on Craft 3.5. I've also tested this on the latest commit to the 3.7 dev branch, where I'm also able to reproduce.

My setup: Edge, Safari and Chrome on MacOS 10.14.6, using a standard Magic Mouse. I double-click fairly fast, FWIW 😄 

I'm also able to reproduce the issue using my MacBook's trackpad, though it seems to occur a bit less often than when using the Magic Mouse.

### Steps to reproduce

1. Select an entry in an Entries field
2. Double-click the element

_Attaching a video that hopefully demonstrates the issue as best I can:_

https://user-images.githubusercontent.com/298510/120854977-24453a80-c57e-11eb-9348-3ca551ebf4b3.mp4

### Additional info

- Craft version: 3.6.16 (able to reproduce), 3.6.11 (able to reproduce), 3.5.17.1 (**not** able to reproduce), 3.7.0 dev branch (able to reproduce)
- PHP version: n/a
- Database driver & version: n/a
- Plugins & versions: none

**Comment by brandonkelly** [comment]
Very strange. Absolutely nothing has changed related to this since… forever. We just use the `dblclick` event to trigger the editor.

Can you head over to https://codepen.io/brandonkelly/pen/BaWxdod and see if you can reproduce the same behavior there?

**Comment by mmikkel** [comment]
@brandonkelly Yeah, extremely strange. I'm able to reproduce with that Codepen though, so this is probably not a problem in Craft after all (...although it's hard to explain why it doesn't appear to happen on 3.5 🤷‍♂️ ). Feel free to close this issue; if I'm able to figure it out I'll update with whatever's causing this.

**Comment by brandonkelly** [comment]
I just gave it a test on my MacBook trackpad and I’m actually seeing similar behavior when I tap rather than actually push down. But yeah not sure what we could do about it; I’m sure the native `dblclick` event is going to generally be more reliable than any custom JS we could come up with.

Piotr recently [requested](https://twitter.com/piotrpogorzel/status/1399667720925364228?s=21) that we replace the double-click trigger with a dedicated edit button, which would solve this another way.

**Comment by mmikkel** [comment]
A single-click "edit" link in (addition to the existing double-click) would probably be a good idea – also in terms of accessibility.
