### ISSUE TITLE
Abilitiy to customize users’ `getName()` & `getFriendlyName()` values

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/cms#8027]
> In our case…
>
> * Users can have a screen name (like twitter) which is used in a Forum to keep anonymity (it's for mental health)
> * We also need their real name for communication and templated doctor letters
>
> If we use firstname / lastname for their real name there's a good chance that could be leaked in the templates if we're not super careful. There's also a chance that automated emails (comment reply notifications) could use `{{ currentUser }}` which would fall back to their real first name.

**Comment by SayChi** [comment]
To add to this topic, this could help with prepositions in names too (not sure if that's the correct word for it). In the Netherlands for example, there are a lot of names that have something like "van" between their first and last names. Currently in Craft there's no really convenient way to handle this as far as i know. What i usually do is put this preposition in the last name field, but this can be a problem with forms or sorting.

So if we could add a preposition field, and then have the possibility to change the __toString() (or maybe even just .name) to include it, that would be perfect

**Comment by brandonkelly** [comment]
Just added two new events, for customizing `getName()` and `getFriendlyName()`:

```php
use craft\elements\User;
use craft\events\DefineValueEvent;
use yii\base\Event;

Event::on(User::class, User::EVENT_DEFINE_NAME, function(DefineValueEvent $event) {
    /** @var User $user */
    $user = $event->sender;
    $event->value = $user->screenName;
});

Event::on(User::class, User::EVENT_DEFINE_FRIENDLY_NAME, function(DefineValueEvent $event) {
    /** @var User $user */
    $user = $event->sender;
    $event->value = $user->screenName;
});
```

Note that `getName()` **must** return a string, so if `EVENT_DEFINE_NAME` doesn’t set `$event->value` to a string, the user’s full name or username will have to be used as a fallback.

`getFriendlyName()` can return `null` though, so if you want to *force* a `null` response from `EVENT_DEFINE_FRIENDLY_NAME`, set `$event->handled = true`, which will cause the event-triggering code to return the event’s `value` regardless of whether it was actually set to something.

**Comment by brandonkelly** [comment]
@SayChi Please take a look at #1073 and let me know your thoughts.
