### ISSUE TITLE
Ability to link to draft entries from other drafts

### ISSUE THREAD

**Issue by chadcrowell** [craftcms/cms#8028]
I have a new section of a site, and it contains about 10 draft entries/pages. Many of them interlink but when I choose entries from an entries field, I can't choose draft entries.

What this means is that in order to have a complete looking draft preview for my client, I have to choose other non-correct entries/pages for these links, and then go back after the entries are published and change all of the selected entries to the now-live pages. Q/A nightmare.

**Comment by brandonkelly** [comment]
Assume you are specifically referring to _unpublished drafts_ (new draft entries where you haven’t clicked “Publish draft” yet). Those won’t be as common going forward thanks to some changes to the publishing workflow coming in 3.7 (see #7899), so this problem should resolve itself at that point.
