### ISSUE TITLE
Custom password page not showing up after upgrade to latest Craft

### ISSUE THREAD

**Issue by GaryReckard** [craftcms/cms#8030]
### Description
I just upgraded from Craft v3.4 to the latest v3.6.16. I have the config setting `setPasswordPath` set to '_pages/set-password', and when I click the link in the activation email, it shows this page rather than the custom template it used to display:

![image](https://user-images.githubusercontent.com/1679951/121261618-f105f280-c880-11eb-860e-515b15aa975f.png)

Has anything changed about that config variable?

### Additional info

- Craft version: 3.6.16
- PHP version: 7.3
- Database driver & version: MySQL 5.7

**Comment by brandonkelly** [comment]
Looks like the URL got set to `_pages/set-password` as expected. Craft will show the default set-password template if it can’t find a matching template in your `templates/` folder. Do you have a `templates/_pages/set-password.twig` file or something like that?

**Comment by GaryReckard** [comment]
Yep, that template exists, and hasn't moved. Our live site is still on the older version of Craft, and is bringing up my custom template, too.

**Comment by brandonkelly** [comment]
🤦🏻  Yes, the issue is that you shouldn’t have it in a private templates folder (one that begins with `_`).



> ...Or maybe it had something to do with me having this route in my routes.php?
> `'set-password' => ['template' => '_pages/set-password'],`

Yes, that would work, combined with setting `setPasswordPath` to `'set-password'`.
