### ISSUE TITLE
Assets volumes sort order changes when editing a volume

### ISSUE THREAD

**Issue by peimansh** [craftcms/cms#8033]
### Description
When trying to edit or make changes in assets volumes, the edited/changed volume comes to the top of the list, ignoring the sort order user has created before. Not sure if that's an expected behaviour but to me looks like a bug !

### Steps to reproduce

1. Sort assets volumes as you like
2. Make changes to a volume which is not at the top of the order
3. The edited volume comes into the top of the list

### Additional info

- Craft version: 3.6.15
- PHP version: 7.4
- Database driver & version: 11.10 PostgreSQL

**Comment by brandonkelly** [comment]
Fixed for the next release. Thanks for reporting!
