### ISSUE TITLE
Plugin developer link may render `<` and `>`

### ISSUE THREAD

**Issue by mattstein** [craftcms/cms#8036]
### Description

If composer.json supplies an `authors.name` value including auto-link hints [like gatsby-helper](https://github.com/craftcms/gatsby-helper/blob/main/composer.json#L20)...

```json
"authors": [
    {
        "name": "Pixel & Tonic, Inc. <support@pixelandtonic.com>",
        "homepage": "https://craftcms.com/"
    }
],
```

...it’s rendered verbatim in the control panel’s plugin listing:

<img width="993" alt="Screen Shot 2021-06-09 at 02 16 40 PM@2x" src="https://user-images.githubusercontent.com/2488775/121415454-5d3e3000-c92d-11eb-9c4f-9786daf08b22.png">

I would expect the `<` and `>` characters to be omitted, if not the entire email address since the developer name is already a hyperlink.

### Steps to reproduce

1. Install the [Gatsby Helper](https://plugins.craftcms.com/gatsby-helper) plugin.
2. Visit **Settings** → **Plugins**.
3. Observe the text `Pixel & Tonic, Inc. <support@pixelandtonic.com>` and consider how it makes you feel.

### Additional info

- Craft version: 3.7.0-alpha
- PHP version: 8.0.3
- Database driver & version: PostgreSQL 13.1
- Plugins & versions: Gatsby Helper

**Comment by brandonkelly** [comment]
This ended up being due to incorrect use of the [authors](https://getcomposer.org/doc/04-schema.md#authors) key in Gatsby Helper’s composer.json file. Fixed for its next release.
