### ISSUE TITLE
Allow for "resave/*" console commands to have an option or flag to send the resave work to the queue

### ISSUE THREAD

**Issue by BradyBonnette** [craftcms/cms#8040]
### Description

Is it possible to add an option or a flag to the `./craft resave/_____` commands that allow one to send the resave work to the queue instead of processing them all in the foreground of the `craft` process? For example, something such as:

 `./craft resave/entries --section someSection --queue`

If there's another way of doing this that I am unaware of I'd love to know about it!

**Comment by brandonkelly** [comment]
Just added that for Craft 3.7. Thanks for the suggestion!

**Comment by BradyBonnette** [comment]
Thanks for the quick return, @brandonkelly!
