### ISSUE TITLE
Add custom event for when enabling entry for a new site

### ISSUE THREAD

**Issue by lassemt** [craftcms/cms#8041]
### Description
When using the propagation method "Let each entry choose which sites it should be saved to" and enabling a existing entry in a new site/language there are no good way to detect if the saved entry was newly "created" for the site. The closest way I found is to check if all the fields are dirty.

### Why we want to check for this
When activating a entry for a new site, the field content of default site is copied over to the entry for the different site. A good way of avoiding content being copied over is to wipe the field data in the `EVENT_BEFORE_SAVE` event, but there are no good way of detecting if the entry was "newly activated". This is also useful when fetching content from an external API on entry activation.

#### 1. A custom event for when entries are enabled/disabled for sites
In a ideal world this would be a good solution as it would be a specific event for the specific "action", but it might be a bit to specific.

#### 2. Make a property on the entry model that tell it was newly activated for a new site.
Then one can use the `EVENT_BEFORE_SAVE` event to tell if the entry is a new entry for a specific site. This can be as easy as making `_allDirty` publicly available since this is always true when enabling a entry on a new site. Now one have to compare the number of fields with the number of dirty fields
```
count($entry->getDirtyFields()) !== count(ArrayHelper::getColumn($entry->getFieldLayout()->getFields(), 'handle'))
```
which don't feel like a nice solution when `_allDirty` is already stored on the object. Here is my temporary solution:

```
Event::on(
  Entry::class,
  Element::EVENT_BEFORE_SAVE,
  function(ModelEvent $e) {
    $entry = $e->sender;

    if (ElementHelper::isDraftOrRevision($entry)) {
      // don’t do anything with drafts or revisions
      return;
    }

    // Don't do anything if not the right section
    if($entry->sectionId != 5) {
      return;
    }

    // Skip if not is allDirty
    // This can't be the only way to check if the current event is
    // for the entry newly enabled for a site?? 
    if(count($entry->getDirtyFields()) !== count(ArrayHelper::getColumn($entry->getFieldLayout()->getFields(), 'handle'))) {
      return;
    }

    // Clean fields
    $entry->setFieldValue('field1', '');
    $entry->setFieldValue('field2', '');
  }
);
```

**Comment by brandonkelly** [comment]
You can determine this by element’s `siteSettingsId` property. If it’s `null`, then the element doesn’t exist yet in the site it’s being saved to.

**Comment by lassemt** [comment]
@brandonkelly Can't believe I missed this when comparing Entry models beeing saved yesterday 😅   Tested  `entry. siteSettingsId` now and it works like a charm to detect if it's about to be activated. Thank you for the quick response!
