### ISSUE TITLE
Using the Hash Filter on a value with string concatenation for hiddenInput('successMessage') causes BadRequestHttpException

### ISSUE THREAD

**Issue by curtismorte** [craftcms/cms#8042]
### Description
When using `{{ hiddenInput('successMessage', 'Added ' ~ product.title ~ ' to cart.' | hash) }}` the value of the input is not hashed properly.

For example, when using the `hiddenInput` from above within one of my templates, the following is produced:
```
<input type="hidden" name="successMessage" value="Added Speed, Alpine White - Blind Corner Base Cabinet (left)e61893cd31d38fe7b1a98e87552323bb38cb3f82579650046f1e8e1ae47705a9 to cart.">
```
If I use this value when updating my cart, I will get the following when sending the request via AJAX:
```
error: "Request contained an invalid body param"
exception: "yii\\web\\BadRequestHttpException"
file: "/home/vagrant/kitchen-logistics-craft/vendor/craftcms/cms/src/web/Request.php"
line: 934
```

Now if I use the following implementation, updating my cart via AJAX works properly:
```
{% set successMessage = 'Added ' ~ product.title ~ ' to cart.' %}
{{ hiddenInput('successMessage', successMessage | hash) }}
```
and the code within my markup is:
```
<input type="hidden" name="successMessage" value="50dab40f0e96e5703851a910bb0bb433c5014e3375343d1def3fb3e1ba103feeAdded Speed, Alpine White - Blind Corner Base Cabinet (left) to cart.">
```

### Steps to reproduce

1. Use any Craft CMS install (with or without Commerce), and create a `hiddenInput()` whose value is a string concatenation like the example above.
2. Load your template in the browser and inspect the hidden input. Notice the value has a hash that is within the middle of the string (between the variable, and the last concatenated string)

### Additional info

- Craft version: 3.6.14
- PHP version: 8.0.1
- Database driver & version: MySQL Ver 8.0.23
- Plugins & versions: Craft Commerce 3.2.14.1

**Comment by brandonkelly** [comment]
That’s actually working as expected, because Twig filters (e.g. `|hash`) only apply to the directly previous value. In your example that would be `' to cart.'`; nothing before it.

Wrap the full concatenated string in parentheses in order to has the entire value:

```twig
{{ hiddenInput('successMessage', ('Added ' ~ product.title ~ ' to cart.')|hash) }}
                                 ↑                                      ↑
```

Or use [string interpolation](https://twig.symfony.com/doc/3.x/templates.html#string-interpolation) (requires double quotes):

```twig
{{ hiddenInput('successMessage', "Added #{product.title} to cart."|hash) }}
```

You can simplify even further using the new [successMessageInput()](https://craftcms.com/docs/3.x/dev/functions.html#successmessageinput) function, added in Craft 3.6.6:

```twig
{{ successMessageInput("Added #{product.title} to cart.") }}
```

**Comment by curtismorte** [comment]
Thanks for the clarification @brandonkelly. When inspecting some of the source templates for commerce, it looks like we missed the parenthesis.
