### ISSUE TITLE
Environment variable support for Site Group name

### ISSUE THREAD

**Issue by timeverts** [craftcms/cms#8044]
### Description
It would be useful to change the displayed name of a Site Group on different environments. Would it be possible to make a change so that the name of a Site Group could be defined as an environment variable?

**Comment by timeverts** [comment]
I am considering sharing the same project config files across several different Craft installations, but because the Site Group names do not support environment variables, it means the Site Group names cannot be made installation specific.

**Comment by brandonkelly** [comment]
Just got this added for 3.7 ✨
