### ISSUE TITLE
Publish draft button without "Publish live changes" permission

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#8045]
### Description
With the following permissions set on a section:
![afbeelding](https://user-images.githubusercontent.com/755428/121640218-f1270d80-ca8d-11eb-8a0b-dbe58b898eb2.png)

The user can make a new entry and save it as a draft, but once that entry is published, any subsequent draft they create they can publish themselves:

![afbeelding](https://user-images.githubusercontent.com/755428/121640447-39dec680-ca8e-11eb-9e24-3a9d4e2620f1.png)

I get why this would work but the permission "Publish live changes" isn't checked so I'm not sure what the expected behavior is here.

### Additional info

- Craft version: 3.6.16

**Comment by brandonkelly** [comment]
I’m not able to reproduce that. Here’s what I just did:

1. Logged in with an admin account (“User A”)
2. Created a new user (“User B”) with the same permissions as above (plus “Access the control panel”)
3. Created an unpublished entry draft from User B’s account, with User B as the author
4. Published the draft as User A
5. Re-edited the entry and created a draft as User B.

From there, User B is only able to save the draft; not publish it:

<img width="986" alt="Screenshot of the top of the Entry Edit page, as seen by User B when editing the entry draft" src="https://user-images.githubusercontent.com/47792/121733090-e2e5eb00-caa7-11eb-8bab-8fc779fd799e.png">

Perhaps you are looking at a user group’s permission, but the individual user you are testing happens to have “Publish live changes” selected directly on their own user account’s permissions?

**Comment by janhenckens** [comment]
Can't reproduce this myself after having had a week off, I'll close for now :)
