### ISSUE TITLE
Longer entry preview URL duration

### ISSUE THREAD

**Issue by ItagMichael** [craftcms/cms#8053]
### Description

It would be nice to increase the time an unpublished entry can be visible using the preview URL (the one that looks like /`slug?x-craft-preview=xxx&token=yyy`). Use case is sharing unpublished pages with non logged in users.

Currently, this can be changed with [defaultTokenDuration](https://craftcms.com/docs/3.x/config/config-settings.html#defaulttokenduration), but I'm told this also affects any other tokens including user impersonation URLs that one might generate if this were to be changed. it would be helpful to change this preview time without worrying about any security implications of what else it may change.

I considered having some sort of condition in general.php to match the request that is generating such a link/token and set a different token duration, but am not sure how/if I could do this reliably.

**Comment by carlcs** [comment]
I’ve opened a similar issue back in 2018 (https://github.com/craftcms/cms/issues/2394). When I looked into the code back then it looked like `defaultTokenDuration` wasn’t really used for anything else than share links. It’d be good if docs would list which tokens are actually affected.

For share links I wonder if manual management of tokens would be a feature worth having. This could be a list in utilities where all share links are listed, with the ability to view and edit their expiry date.

**Comment by brandonkelly** [comment]
Going to close this as a duplicate. @carlcs Feel free to post the Tokens utility idea as a new issue.
