### ISSUE TITLE
Entry field - Disable sections from being listed as Entry Sources, if those sections don't have public URL available.

### ISSUE THREAD

**Issue by bkrsmanovic** [craftcms/cms#8059]
### Description

So, typically, you would use 'All' as sources inside Entry Field.
Then imagine you create buncha entries fields across the site.

Then, you add 1 new Section, that you use only for data (so they don't have public URL).
Now, when typical users, wants to add a link to some button, he sees an option to select entry even from that new non-public url Section, because if 'All' is selected, then all new sections become available as Sources.
And after selecting it, you get either error, or non-existing data inside templates, specifically {{ entrySource.url }}.
Workaround is to go through each of Entry Fields, and remove manually that specific Section from being a source. And that is quite a work.

So, my suggestion is, if entry doesn't have public URL, it should not belong to the sources list.

------

I imagine this should not be done automatically, because you want entries without URLs to be selectable inside Entry Field for various cases, but if I am using an entry field as a source for Link and Title, which is typically the case, and nothing else, I would like to have a button above sources that says `'Select only sources with Public URL?'` And in that case, when creating that button, we are kinda removing sections without public URL from options.

(button can be above sources).
![image](https://user-images.githubusercontent.com/15169280/122025737-e63fe600-cdc9-11eb-9e42-a671c4f7e7d7.png)

**Comment by brandonkelly** [comment]
If a section doesn’t have URLs, it’s all the _more_ likely to need to be related via Entries fields – because relations are just about the only way their content is ever going to end up on the website.
