### ISSUE TITLE
Ability to rename fields from the Field Layout Designer

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#806]
> Created by: Neal Stammers (neal@netgorilla.co.uk) on 2015/03/10 18:02:16 +0000
> Votes at time of UserVoice import: 232

-----------------------------------

Some fields can be re-used in many sections, but having a single label is often not ideal.

For example; you may create a simple 'plain text' field.

When adding to multiple sections you would be able to rename the label so the UI was clearer. e.g.

'Article excerpt' or 'Section intro'

Individual templates/macros could handle the different use cases, but would reduce the number of similar fields in the admin area

**Comment by brandonkelly** [comment]
This would be resolved by #1524.

**Comment by brandonkelly** [comment]
As of the next Craft 3.5 release, it will be possible to customize fields’ titles and instructions (including Title fields), from within the field layout designer.

<img width="353" alt="A screenshot of a field layout designer with visible Label and Instruction fields for a field" src="https://user-images.githubusercontent.com/47792/87213099-3e778980-c2d7-11ea-94ae-33c4a96e4a4c.png">
