### ISSUE TITLE
Updating element structure in element index does not update URI or Link table columns

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#8062]
### Description
In an element index's structure view in a section with URIs set to be dependent on an element's position (e.g. pages), updating the element's position does not update the links in the table row, such as the URI and Link options.

### Steps to reproduce
1. Create a structure section with URIs set to something dependent on the parent, such as:
`{% if object.level > 1 %}{parent.uri}/{% endif %}{slug}`
2. Enable the "Link" and "URI" columns in the element index for this section 
3. Create two level zero entries in this section with different slugs
4. Drag one entry under the other
5. Try to click the links in the element index row
6. Get 404

### Additional info

- Craft version: 3.6.16

**Comment by brandonkelly** [comment]
Updating entry URIs recursively is a little expensive, so it takes place via a queue job rather than during the initial move. If you wait for your queue to complete and reload the index, the links should be updated based on the new entry positions.
