### ISSUE TITLE
In Entry Editing: Preview is available, sharing is not (after Update 3.1 -> 3.6)

### ISSUE THREAD

**Issue by hiasl** [craftcms/cms#8063]
### Description
After an update to 3.6.16 (PRO): When editing an entry I have the preview option but not the sharing option. 

### Steps to reproduce

1. We updated from 3.1.14.1. to 3.6.16 (PRO)
2. My section "Seiten" (=pages) has a preview target configured
3. When editing an entry of this section the preview button is there, but there is no share button
4. Why?

### Additional info

- Craft version: 3.6.16 (PRO)
- PHP version: 7.4

**Comment by brandonkelly** [comment]
“Share” was renamed to “View”. Are you seeing a View button?

**Comment by hiasl** [comment]
Hey Brandon,
sorry I missed that. I even tried the "View" button but only looked for the "x-something" hash in the URL, which does not appear unless it's a draft.
Thanks.
