### ISSUE TITLE
Entry CSV Export - line ending encoding issue

### ISSUE THREAD

**Issue by rob-baker-ar** [craftcms/cms#8067]
### Description

I have a section with ~8,500 fairly complex entries. I am able to export this to CSV using the controls at the bottom of the entries listing screen for that section. However, the resulting CSV does not correctly import into software like Excel.

There are some redactor fields on the entries in question and whenever there is a line ending within this field, the line ending comes out in the CSV, tricking Excel into thinking that's the end of the row. It's not, so it import is corrupted.

I believe line endings should be encoded in CSV as `\n`.

### Steps to reproduce

1. Create a section containing entries with a redactor field
2. Add a few paragraphs to the field
3. Ensure there are line endings in Redactor's source
4. Export the entries to CSV like this: https://craftcms.com/docs/3.x/extend/element-exporter-types.html

### Additional info

This section was initially imported via Feed Me (all fields). It could be the case that for that reason, line endings are not getting properly encoded as they are not the _direct_ result of saving a Redactor field.

- Craft version: 3.5.14
- PHP version: 7.4.16
- Database driver & version: MySQL 5.5.5
- Plugins & versions
  - Redactor: 2.8.3
  - Feed Me: 4.2.4
  - Others: N/A

**Comment by brandonkelly** [comment]
I’m not able to reproduce this on my end. Can you please send a database backup and your `composer.json` and `composer.lock` files over to support@craftcms.com, and point out which entry(s) you are seeing this on?

**Comment by rob-baker-ar** [comment]
Hi @brandonkelly, that might be tricky, the database is well over 2Gb. 

I have been looking into this more though and I'm not so sure it's a Craft bug now. It might well be an Excel bug.

When I export CSV from Craft, if this is opened directly in Excel, all the columns appear correctly but Excel assumes the incorrect character set, so the UTF-8 data is corrupted.

If I start in Excel with a blank sheet and import the CSV (Data > Get Data > From Text / CSV) as Microsoft recommends, this allows selection of the correct character set **but** it seems to get confused with line endings (usually, but not exclusively in Redactor fields) and prematurely ends some CSV rows, causing subsequent columns to be all over the place.

I have been looking into the way `craft\web\CsvResponseFormatter` works and how that relates to some of the comments here: https://www.php.net/fputcsv.

Also, I have been looking into how it handles mixed line endings (`\n` for CSV l;ine endings but with `\r\n` in the data).

This lead me to try adding:

```php
fputs($fp, $bom =( chr(0xEF) . chr(0xBB) . chr(0xBF) ));
```
_Injecting a UTF-8 BOM_ directly after `$fp = fopen($file, 'wb');` in `craft\web\CsvResponseFormatter`.

After this patch, Excel knows the file is UTF-8 straight away and deals with the characters properly without having to do the import empty sheet import thing and everything appears to work as it should.

If this was to be adopted as a change, it would have to be a bit more clever and if / when it inserted the BOM.

**Comment by brandonkelly** [comment]
Jut went ahead and added that line for the next 3.7 beta release. Not seeing a difference and we still aren’t able to reproduce the original issue, but maybe it will help you. 🤷🏻

**Comment by brandonkelly** [comment]
3.7.0-beta.2 is out now with that change.
