### ISSUE TITLE
Database sync across multiple environments

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#807]
> Created by: Ben Parizek (ben@barrelstrengthdesign.com) on 2015/03/12 23:19:32 +0000
> Votes at time of UserVoice import: 230

-----------------------------------

Managing database changes across multiple environments is hard.

Make it easier!

This thread on Stack Exchange is a good discussion of different methods people are currently using:
http://craftcms.stackexchange.com/questions/10/whats-the-best-practice-for-handling-data-migration-and-organization-across-dev

**Comment by kruncher** [comment]
Is there any progress on this feature request / enhancement?

**Comment by angrybrad** [comment]
@kruncher Project Config is a step in this direction https://docs.craftcms.com/v3/project-config.html

**Comment by Jan10** [comment]
@kruncher i found a plugin for that: https://unionco.github.io/craft-plugin-docs/craft-sync-db/#overview

Works perfect :)
