### ISSUE TITLE
Some emojis are failing validation in plain text fields

### ISSUE THREAD

**Issue by daveyjones** [craftcms/cms#8072]
### Description
Some emojis pass validation in plain text fields while others don't. I'm using a MySQL database with `utf8mb4` character set.

### Steps to reproduce
1. Paste the 😀 emoji into a plain text field.
2. Save the entry.
3. No problems.
3. Paste the 🛌 emoji into a plain text field.
4. Save the entry.
5. Problems.

### Additional info
- Craft version: 3.6.17
- PHP version: 7.4.3
- Database driver & version: MySQL 8.0.25
- Plugins & versions:
Amazon SES 1.3.4
Blitz 3.9.0
Campaign 1.19.2
Imager X v3.4.0
Incognito Field 1.2.0
oEmbed 1.3.8
Redactor 2.8.7

**Comment by brandonkelly** [comment]
Emoji support for MySQL installs is limited to whatever the [LitEmoji](https://github.com/elvanto/litemoji) library supports. You can suggest that they add additional emoji from https://github.com/elvanto/litemoji/issues. (Postgres installs have full emoji support.)
