### ISSUE TITLE
[3.7-beta] Parent entry selection not working properly

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#8074]
### Description

The "Parent" selector doesn't appear to be working as expected.

There are two "Choose" buttons. On unpublished drafts, the first one is disabled and the 2nd does not work:
![image](https://user-images.githubusercontent.com/3810939/122270783-ab62ae80-ceac-11eb-8cb7-11f8a5256fa6.png)

On published entries, the first button works, but the other doesn't:
![image](https://user-images.githubusercontent.com/3810939/122273315-4b213c00-ceaf-11eb-873e-a6b9be0c6ca9.png)

### Additional info

- Craft version: 3.7-beta.1
- PHP version: 8.0
- Database driver & version: MariaDB
- Plugins & versions:

**Comment by brandonkelly** [comment]
Doh, thanks for reporting. Just fixed both of those for the next release.

**Comment by brandonkelly** [comment]
3.7.0-beta.2 is out now with the fix for this.
