### ISSUE TITLE
Using variables in twig attr function causes extra space in the output

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/cms#8080]
### Description

Appreciate this is a small one, but when using variables in twigs attr function, it causes an unwanted extra space in the output.

#### Case 1:

```
{% set attributes = {
    class: [
        'b-navigation__item', 
        isActive ? 'is-active' : '',
    ]
} %}
<li {{ attr(attributes) }}>
```
Outputs:
```
<li class="b-navigation__item ">
```
Versus
```
<li class="b-navigation__item">
````

#### Case 2

```
{% set isActive = '' %}
{% set attributes = {
    class: [
        'b-navigation__item', 
        isActive,
    ]
} %}
<li {{ attr(attributes) }}>
```
Outputs:
```
<li class="b-navigation__item ">
```
Versus
```
<li class="b-navigation__item">
````

#### Case 3
```
{% set attributes = {
    class: [
        'b-navigation__item', 
        '',
    ]
} %}
<li {{ attr(attributes) }}>
```
Outputs:
```
<li class="b-navigation__item">
```
### Additional info

- Craft version: 3.6.17
- PHP version: 7.4
- Database driver & version:
- Plugins & versions:

**Comment by MoritzLost** [comment]
You've probably made some error in your test cases. Actually,  the extra space will be present in all of your test cases. The `attr` filter uses [yii\helpers\BaseHtml::renderTagAttributes](https://www.yiiframework.com/doc/api/2.0/yii-helpers-basehtml#renderTagAttributes()-detail) ([see the twig function definition here](https://github.com/craftcms/cms/blob/4f86d4d4fed789be53a658060799b89609fd041f/src/web/twig/Extension.php#L1155)), which means the function only gets passed the array, it doesn't know if you used a variable or a string literal to define it.

Anyway, the function indeed doesn't filter out empty entries in a `class` array, see [the source code here](https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L1983-L1987). Not sure if it would be reasonable to expect that, might be worth opening an issue to the Yii2 framework.

Anyway, I use the following short snippet which gets rid of the space as well:

```twig
{% set attributes = {
    class: [
        'b-navigation__item', 
        isActive ? 'is-active' : '',
    ]|filter(v => v is not empty)
} %}
```

**Comment by brandonkelly** [comment]
Yeah this is working as expected. You can consider opening a PR with Yii to change it. In the meantime you will need to add `|filter` after the class array to filter out any empty values.
