### ISSUE TITLE
[3.7 Beta] Section type structure has two choose buttons

### ISSUE THREAD

**Issue by Jan10** [craftcms/cms#8082]
### Description

If you have a section with the type `structure`, you have two choose buttons in the sidebar bar.

![image](https://user-images.githubusercontent.com/192557/122414484-78411d80-cf87-11eb-9864-fe31df951441.png)

```
<div class="flex">
        <button type="button" class="btn add icon dashed disabled" disabled="">Choose</button>
        <button type="button" class="btn add icon dashed">Choose</button>
</div>
```

### Steps to reproduce

1. Add a section type `structure`
2. Create a new entry

### Additional info

- Craft version: 3.7.0-beta.1

**Comment by brandonkelly** [comment]
That was reported by #8074, and fixed for the next release :)

**Comment by brandonkelly** [comment]
For posterity, 3.7.0-beta.2 is out now with the fix for this.
