### ISSUE TITLE
[3.6.14] Address argument #2 must be passed by reference

### ISSUE THREAD

**Issue by richardhedges** [craftcms/cms#8084]
### Description

When viewing a customer using Pro on PHP 8.0 the following error is returned:
`craft\commerce\models\Address::craft\commerce\models\{closure}(): Argument #2 ($key) must be passed by reference, value given`

The error disappears when reverting to PHP 7.4.

I also raised this in the [commerce repository](https://github.com/craftcms/commerce/issues/2212).

### Steps to reproduce

1. Create a customer
2. View the customer in the admin panel

### Additional info

- Craft version: 3.6.14
- PHP version: 8
- Database driver & version: MySQL 5.7.23
- Plugins & versions: Commerce 3.2.17.4

**Comment by brandonkelly** [comment]
It looks like it’s coming from Commerce so I’m going to close this issue.
