### ISSUE TITLE
[3.7-beta] CLI commands fail on Windows

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#8089]
### Description

CLI commands fail with

```
Exception 'TypeError' with message 'Return value of craft\console\Controller::checkRootUser() must be of the type bool, none returned'

in E:\craft\temp1\vendor\craftcms\cms\src\console\ControllerTrait.php:73

Stack trace:
#0 E:\craft\temp1\vendor\craftcms\cms\src\console\Controller.php(170): craft\console\Controller->checkRootUser()
#1 E:\craft\temp1\vendor\yiisoft\yii2\base\Controller.php(179): craft\console\Controller->beforeAction(Object(yii\base\InlineAction))
#2 E:\craft\temp1\vendor\yiisoft\yii2\console\Controller.php(184): yii\base\Controller->runAction('', Array)
....
```

Looks like there is no return statement in ControllerTrait::checkRootUser in case of Windows.

/Mel

### Steps to reproduce

1. Run a cli command on Windows
2.

### Additional info

- Craft version: 3.7 beta 2
- PHP version: 7.4
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting! Just fixed that for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"3.7.x-dev as 3.7.0-beta.2"` and run `composer update`.

**Comment by brandonkelly** [comment]
3.7.0-beta.3 is out now with that fix. Thanks again.
