### ISSUE TITLE
A centralised place for Craft license management

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#809]
> Created by: Daryl (craft@codeknight.co.uk) on 2015/03/12 09:36:29 +0000
> Votes at time of UserVoice import: 159

-----------------------------------

I've built up a fair number of Craft licenses over the last 18 months, but there's no way of keeping track of which ones are being used, and which are spare (and there are a few that I know aren't being used).

Suggestion: There should be a "My Account" section on the buildwithcraft website, where we can login in see all our purchases, as well as which sites they're currently being used on.

Extra suggestion - The ability to limit a Craft license to a certain domain, so if someone gets hold of the license.key file, they can't just move it to another website. Currently, if anyone copies and moves the license.key file, you instantly lose ownership and control of that license.

**Comment by brandonkelly** [comment]
We just launched [Craft ID](https://id.craftcms.com), a portal for Craft developers, where you can manage your licenses, and soon you’ll be able to purchase Craft (and plugin) licenses from there too.
