### ISSUE TITLE
Saving an entry with no changes behaves differently between the edit popover and primary edit screen

### ISSUE THREAD

**Issue by amphibian** [craftcms/cms#8090]
### Description

I recently aded a dropdown new field to an entry type, and needed to go back to existing entries and re-save them to add the new default value. At first I tried quickly opening each in the entry popover, opening it and then saving - but the change did not take effect in my front-end templates.

Opening each entry in the full entry editor and saving them in exactly the same fashion (default dropdown value selected, no interaction on my part) worked as expected - the new values are saved in the database and rendered in my templates.

### Steps to reproduce

1. Create an entry.
2. Add a new dropdown field to that entry's entry type.
3. Open the existing entry in the popover editor and click "Save".
4. Render the entry's template and see that the new field's default field value has not been saved.

### Additional info

- Craft version: 3.6.17
- PHP version: 7.4.12
- Database driver & version: MySQL 5.7.32

**Comment by brandonkelly** [comment]
Thanks for reporting that! The fix was a little complicated and touches code that was refactored in 3.7, so I’ve just fixed it for the next 3.7 Beta release, rather than 3.6.x.

**Comment by brandonkelly** [comment]
3.7.0-beta.3 is out now with that fix.

**Comment by amphibian** [comment]
Excellent, thanks Brandon.
