### ISSUE TITLE
Imagine is incompatible with Imagick 3.5.0

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#8095]
### Description
Imagick 3.5 was just released with PHP 8 support; however, it introduced a breaking change in some method signatures. Parameters are now explicitly typed and thus incompatible with the Imagine classes that are extending the \Imagick classes.

See new method signatures here:

https://github.com/Imagick/imagick/blob/6fb660ec492834a546c7cc383a29ea3ce5b5cf17/Imagick.stub.php#L472

This is particularly problematic as automated provisioning tools that aren't locked to a specific version will grab the latest release and cause an error like this in Craft:

```
Declaration of Imagine\Imagick\Imagick::thumbnailImage($columns, $rows, $bestfit = false, $fill = false, $filter = Imagick::FILTER_TRIANGLE, $keepImageProfiles = false, $keepExifData = false) must be compatible with Imagick::thumbnailImage(?int $columns, ?int $rows, bool $bestfit = false, bool $fill = false, bool $legacy = false): bool
```

### Additional info

- PHP version: 8.0.x

**Comment by brandonkelly** [comment]
Fun stuff. Just posted an issue on Imagine’s repo (avalanche123/Imagine/issues/766) so we’ll see what they say.

**Comment by brandonkelly** [comment]
We just released an update to `pixelandtonic/imagine` which fixes this. Run `composer update` and you’ll get the fix.

Thanks for reporting!

**Comment by tonyclemmey** [comment]
Hi, I came across the same issue mentioned (using PHP 8.0.x, Imagick 3.5.0 and Craft 3.6.14)

```
yii\base\ErrorException: Declaration of Imagine\Imagick\Imagick::thumbnailImage($columns, $rows, $bestfit = false, $fill = false, $filter = Imagick::FILTER_TRIANGLE, $keepImageProfiles = false, $keepExifData = false) must be compatible with Imagick::thumbnailImage(?int $columns, ?int $rows, bool $bestfit = false, bool $fill = false, bool $legacy = false): bool in /var/www/vendor/pixelandtonic/imagine/src/Imagick/Imagick.php:88
```

I have updated Craft to the latest 3.7.4 but now get the following error when trying to upload a JPG, if I upload an MP4 (not using Imagick ?) the MP4 uploads fine.

```
yii\web\BadRequestHttpException: No file was uploaded in /var/www/vendor/craftcms/cms/src/controllers/AssetsController.php:275
Stack trace:
#0 [internal function]: craft\controllers\AssetsController->actionUpload()
#1 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#2 /var/www/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#3 /var/www/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#4 /var/www/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction()
#5 /var/www/vendor/craftcms/cms/src/web/Application.php(271): yii\base\Module->runAction()
#6 /var/www/vendor/craftcms/cms/src/web/Application.php(584): craft\web\Application->runAction()
#7 /var/www/vendor/craftcms/cms/src/web/Application.php(250): craft\web\Application->_processActionRequest()
#8 /var/www/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
#9 /var/www/web/index.php(22): yii\base\Application->run()
#10 {main}
2021-07-21 09:34:10 - info - application
$_GET = [
    'p' => 'admin/actions/assets/upload'
]

$_POST = []

$_FILES = []
```

Application Info
```
PHP version: 8.0.7
OS version: Linux 4.18.0-305.3.1.el8.x86_64
Database driver & version: PostgreSQL 13.2
Image driver & version: Imagick 3.5.0 (ImageMagick 6.9.12-15)
Craft edition & version: Craft Pro 3.7.4
Yii version: 2.0.42.1
Twig version: v2.14.6
Guzzle version: 7.3.0
```

**Comment by brandonkelly** [comment]
@tonyclemmey Have you tried running `composer update`?

**Comment by tonyclemmey** [comment]
@brandonkelly not long after I ran the `composer update` and cleared all cookies.  After that point, no error was outputted in logs but still upload for JPGs was failing. I have since reinstalled ImageMagick and uploads seem to work again.
