### ISSUE TITLE
Intelligent cropping for flexible images

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#810]
> Created by: Tom Bauer (tbauer49@gmail.com) on 2015/03/23 17:25:32 +0000
> Votes at time of UserVoice import: 147

-----------------------------------

Websites don't have a single layout any more. The handling of images is realy difficult. If you have to use the same image file in all contexts (mobile, desktop,...).
The built in Transformations are already a good solution, but it would be perfect to integrate a solution with a "focuspoint" for each image.
See more infos: https://github.com/jonom/jquery-focuspoint
or Demo: http://jonom.github.io/jquery-focuspoint/demos/grid/lizard.html

What do you think for including something like that?

Best regards from Switzerland

Tom

**Comment by brandonkelly** [comment]
We’ve added focal points to Craft 3, via the new Image Editor.
