### ISSUE TITLE
More Column Types in Table Fields

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#811]
> Created by: Phil Zelnar (phil@andphil.com) on 2015/03/18 20:09:09 +0000
> Votes at time of UserVoice import: 128

-----------------------------------

It'd be a great if table fields had a bit more variety in terms of column types.

I think the most critical would be an asset since it's pretty common to have some tabular data includes a thumbnail images. 

Honestly, I think a more robust set of columns in Tables would solve for a lot of the cases that lead to conversations about "matrix in matrix." The benefit I can see of using Tables is that the UI's already there and it'd be limited to one level (which seems a bit more practical then endless nesting).

**Comment by ritagya-meharishi** [comment]
Is there a way or a plugin that allows you to add columns and change column headings from within the entry ?

**Comment by brandonkelly** [comment]
@ritagya-meharishi Not that I’m aware of.

**Comment by ritagya-meharishi** [comment]
Thanks for replying @brandonkelly! I just found the [supercool table maker](http://plugins.supercooldesign.co.uk/plugin/table-maker/licence) plugin with which you can create dynamic tables.

**Comment by dougstjohn** [comment]
I'd vote for a Dropdown type. I need a Status column with 3+ options.

**Comment by brandonkelly** [comment]
@dougstjohn We currently don’t have a way to add settings to the columns (e.g. Dropdown Options), so that’s the holdup. Super Table is a great solution if you need that, though.

**Comment by kgrote** [comment]
Bump for a dropdown type. I've got a situation where I need a more robust table _inside_ a Super Table and I'm outta luck.

**Comment by kpamaran** [comment]
+1 for dropdown types in tables!

**Comment by brandonkelly** [comment]
Just added support for Dropdown columns for the next 3.2 release.

If you want to help test, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "3.2.x-dev#214a5703149eee33c7569fe045ca38154c345e9b as 3.2.0-alpha.2",
  "...": "..."
}
```

Then run `composer update`.

After choosing “Dropdown” for a new Table column type, you will need to click the cog icon to edit its available options.

<img width="731" alt="Screen Shot 2019-04-05 at 1 58 19 PM" src="https://user-images.githubusercontent.com/47792/55656202-f94ada80-57aa-11e9-8452-6ef517990c2e.png">

**Comment by richhayler** [comment]
Hi @brandonkelly, awesome about adding dropdown options to the native table field. I was wondering about the mention of adding the ability to include “assets” or potentially “entries”? I followed closed issues for these requests that lead me here so just wondering if this functionality is planned or whether a couple of FRs should be raised for these now that this one is closed?
