### ISSUE TITLE
Buy Neo and make it core

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#814]
> Created by: Anonymous (alan@theskyfloor.com) on 2015/03/10 17:00:50 +0000
> Votes at time of UserVoice import: 109

-----------------------------------

Y'all should buy Neo by Ben Fleming and make it the way Matrix works in core... 'nough said it works well and does everything I wish Matrix would do already.

https://github.com/benjamminf/craft-neo

**Comment by davidhellmann** [comment]
Do this or make the Matrix Field with a more Modular Approach :)
Neo + SuperTable is really awesome

**Comment by msimpson** [comment]
We always utilize Neo with Craft to create configurable Web components. If this was added to core, we could leverage the plugin API to make reusable Web components across multiple instances of Craft. Please add this to core or implement something similar.

**Comment by benjamminf** [comment]
@msimpson For the Craft 3 rebuild of Neo I'm going all out with making Neo very friendly to plugins. You can leverage the current API of Neo to create reusable components (we're currently doing it at our agency) but it's not the easiest thing right now.

For those interested here is a description of what I want to accomplish with Neo for Craft 3: https://github.com/benjamminf/craft-neo/issues/100#issuecomment-303936114

I still feel that this plugin is not suited for Craft's core, but Matrix definitely needs an update. For now I'll continue working on Neo and make it as stable as possible.

**Comment by msimpson** [comment]
@benjamminf 
I'll certainly take a look at that. Anything to make things more reusable is welcome.

**Comment by brandonkelly** [comment]
There are aspects of Neo that will have some crossover with future plans (#1524, etc.), but I agree with @benjamminf that Neo is better suited as a plugin than core features. Like Alfred vs. Spotlight.
