### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#815]
> Created by: Tom (t@klepl.com) on 2015/04/20 17:54:59 +0000
> Votes at time of UserVoice import: 101

-----------------------------------

It would be great to have a way to access content stored in Craft for use in mobile apps and other types of front ends or systems, other than  fudging a JSON feed using templates.

Ideally there would be a section in the admin panel to define API endpoints and what channels they map to. Arguments for pagination and searching/filtering would be provided out of the box.

**Comment by phoob** [comment]
Would you consider just going with GraphQL instead..? https://github.com/markhuot/craftql
