### ISSUE TITLE
Tag management

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#820]
> Created by: Brandon Kelly (brandon@pixelandtonic.com) on 2015/03/06 03:54:45 +0000
> Votes at time of UserVoice import: 81

-----------------------------------

It would be nice if there was a place in the CP where we could manage all of the existing tags.

**Comment by whoisgina** [comment]
Bumping this! Would love to see this become part of core.

**Comment by brandonkelly** [comment]
@whoisgina I don’t think @boboldehampsink has ported it to Craft 3 yet (not listed onhttps://github.com/craftcms/plugins). Maybe he’s hoping we’ll add it to Craft ourselves 🙃

**Comment by khalwat** [comment]
I'm hoping you'll add it to Craft yourselves, FWIW 🙃

**Comment by ktriek** [comment]
@angrybrad , any progress on this or is there a timeline?

**Comment by ipetrov87** [comment]
I hope it will be soon.

**Comment by brandonkelly** [comment]
Ether Creative just released a new tag management plugin: https://github.com/ethercreative/tags

Should work well while you wait for a built-in solution.

**Comment by kgrote** [comment]
Ether's plugin hasn't been updated in 6 months and issues go unanswered.

Tag management in Core would very much be appreciated.

**Comment by ryanpcmcquen** [comment]
Is this being worked on?

**Comment by brandonkelly** [comment]
No, the plan is to do away with Tags and Categories entirely, merging those concepts with Entries (and giving Entires field all the same features that Tags and Categories fields have currently. Plus make the Entries index page more customizable so you can still present certain sections as “categories” or “tags” if you want.

**Comment by kgrote** [comment]
I'm fine with that. Been using Categories to manage tags for a while and it's been working good, and honestly like Brandon said Categories are basically just channel-type sections anyway with slight UI differences.

**Comment by vnali** [comment]
> No, the plan is to do away with Tags and Categories entirely, merging those concepts with Entries (and giving Entires field all the same features that Tags and Categories fields have currently). Plus make the Entries index page more customizable so you can still present certain sections as “categories” or “tags” if you want.

@brandonkelly  i was searching for a way to translate tag for every site that i found this issue.
so in future it is not possible to add a tag field to custom elements via field layout for custom plugins :( ?  
IMHO maybe checkbox or radio field provide kind of same functionality, but tag provide far better UI.

**Comment by brandonkelly** [comment]
Giving Entries fields the ability have similar UIs as Categories and Tags fields is the main thing I meant by that.

**Comment by vnali** [comment]
@brandonkelly , so if  i use tag field in a **custom element type** to label  those custom elements -and this custom element type is not about entries at all-, can i do the same thing and tag my custom elements with entries field in future?

**Comment by brandonkelly** [comment]
@vnali Yes, there won’t be any authoring feature regressions with this change.

**Comment by Friksel** [comment]
@brandonkelly any news on this? Are these plans for v3.x or v4.x? And will there be a way to create new tags directly from within the field like we can now?

**Comment by brandonkelly** [comment]
@Friksel We’ve started planning it out a bit, but no news yet. Yes, part of the plan will be to add new UI modes to Entries fields, so they can behave like Tags/Categories fields do currently.
