### ISSUE TITLE
Ability create new fields from the Field Layout Designer

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#822]
> Created by: Keith Mancuso (keith@familiar-studio.com) on 2015/03/11 01:23:26 +0000
> Votes at time of UserVoice import: 77

-----------------------------------

Would love to see a way to add fields directly from the section designer, its often a little more cumbersome to add a new field when you have to currently

Create the field, go to the sections, select the entry type then drag and drop the field into place.

The other way to approach it would be to be able to assign a field to a section/entry type directly on creation (maybe even multiple).  

In that approach it would just add it to the bottom of the first tab i assume and you would have to go to the section designer to move it around.

**Comment by brandonkelly** [comment]
Closing this in favor of #2685.
