### ISSUE TITLE
Use fields accross multiple Matrix blocks

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#823]
> Created by: Ryan Shrum (ryan@ryanshrum.com) on 2015/03/10 19:11:37 +0000
> Votes at time of UserVoice import: 72

-----------------------------------

It would be very handy to allow sharing of fields across multiple blocks. i.e. I have a video block and an image block; both have captions so the caption field needs to be duplicated in each block. It would be nice to be able to pull from the all the custom fields in your Matrix blocks.

Likewise, I have several fields that support UI changes on the front-end, but this FR seems to address that. (margin/no margin; border/no border; background color; etc)

#865

**Comment by brandonkelly** [comment]
This would be resolved by #1524.
