### ISSUE TITLE
Add an alert or warning when multiple authors are editing the same entry

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#824]
> Created by: brad (brad@pixelandtonic.com) on 2015/03/06 19:07:45 +0000
> Votes at time of UserVoice import: 70

-----------------------------------

Currently if multiple authors are editing the same entry the last person to save is going to win and blow away any other author's changes.

It's not so bad if you're on Craft Pro because you can pull the other author's edits from past revisions (assuming they're enabled), but it would be nice to at least be warned if multiple people are editing the same entry.

**Comment by groe** [comment]
No more UserVoice? Can I **+1** here then? :slightly_smiling_face:

I've recently had this request from a client coming from the OpenCMS world (which allows users to "check out" pages, which are then locked for other users).

**Comment by takobell** [comment]
@groe Yup, no more UserVoice. You can +1/comment here, though and we imported the number of votes the issue had on UserVoice at the time of import in the initial request.

> Votes at time of UserVoice import: 70

**Comment by brandonkelly** [comment]
@groe to +1 this, add a 👍 reaction to the main post at the top of the page.

**Comment by groe** [comment]
@brandonkelly Done, thanks!

(Now that this is an official @brandonkelly -thumbs-upped issue it can be considered basically finished & almost shipped, RIGHT? :smile: )

**Comment by artoric** [comment]
+1 👍

**Comment by jkesler-va** [comment]
This is a pretty big issue for sites with multiple users

**Comment by j-greig** [comment]
+1 for this... actually a client asked about it during a demo and I had to run a test on the spot to find the answer :grimace:

**Comment by jan-dh** [comment]
+1 on this. Having clients asking for this as well.

**Comment by marionnewlevant** [comment]
[Snitch Plugin](https://plugins.craftcms.com/snitch) does exactly this.

**Comment by peteralewis** [comment]
This is still not baked into the core Craft then?!? :(

**Comment by sjelfull** [comment]
I hope this won't use polling but will rather use some kind of "presence" API, which we can use for other things too.

**Comment by brandonkelly** [comment]
PHP and WebSockets aren’t the best of friends, so we’ll likely do something using polling as the lowest-common-denominator implementation, and spruce it up with an optional server component down the road that uses WebSockets.

**Comment by sjelfull** [comment]
Yeah, I know that. A server component that could provide generic events over WS would be awesome, and highly appreciated. 

This ties into my question about: Will you support GraphQL subscriptions at some point, which will support live streaming updates to things like a official Gatsby source plugin? (please). If so, you will need something like a WS server. But I digress, its another thread.

**Comment by brandonkelly** [comment]
Yep. Work on all of this is already underway ;)

**Comment by ryanmasuga** [comment]
Client just ran into this today as 3 people were editing Matrix blocks on the same entry and apparently blowing away one another's changes. Will probably install Snitch for now, but core capability would be nice.
