### ISSUE TITLE
Arrange fields in rows rather than only vertically stacked

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#825]
> Created by: John Baxter (john@luckyturnmedia.co.uk) on 2015/03/11 09:07:25 +0000
> Votes at time of UserVoice import: 68

-----------------------------------

It would be good to be able to arrange fields in rows when adding them to tabs. If i have a bunch of fields that are switches/controls then having them stacked vertically doesn't make sense visually.

**Comment by brandonkelly** [comment]
Related to #1103 and #1138.
