### ISSUE TITLE
Built In Publication Approval Workflow

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#829]
> Created by: Anonymous (alan@theskyfloor.com) on 2015/03/10 17:00:50 +0000
> Votes at time of UserVoice import: 56

-----------------------------------

I think Craft would benefit greatly by extending the built in drafts system to include publication approval workflows. i.e. a user without publishing permissions would save a draft and send it for approval to be published by an admin with permissions - the admin would receive an email from the CP telling them there is content awaiting approval... also notification on the CP dashboard (or in the nav bar) and the ability to sort by items awaiting moderation in the entries list.

**Comment by bertoost** [comment]
I know this a new feature, but for projects with a huge amount of fields per user... at least the ability to separate them into tabs should be possible (and easy to fix) 😄

**Comment by brandonkelly** [comment]
@bertoost Not sure I’m following you there. Separate what into tabs?

**Comment by brandonkelly** [comment]
Going to close this in favor of #6022.
