### ISSUE TITLE
Landing pages for Channels

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#830]
> Created by: Hamish Taplin (hamish@bluegg.co.uk) on 2015/03/11 12:03:00 +0000
> Votes at time of UserVoice import: 54

-----------------------------------

Channels are great as they suit flat content such as News perfectly. However, if you need to create an (editable) landing page for that content, you have to either create a single for it or use a structure. 

The issue here is that it adds cognitive load to the users experience as they have to remember the single is elsewhere in the UI or use the slightly awkward workflow for structures whereby you have to tick the parent (landing page) and then select 'add childpage' from the dropdown. 

One solution would be to add an option to add a 'landing page' or 'index page' or whatever you want to call it to a channel (this would work great with structures too) which is visually separate from the 'listing' UI for that section. It could perhaps sit between the toolbar and the elements table.

**Comment by brandonkelly** [comment]
Idea duplicated by #1490 so closing this one.
