### ISSUE TITLE
Add PostgreSQL support

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#832]
> Created by: Bob Olde Hampsink (b.oldehampsink@itmundi.nl) on 2015/04/30 06:39:01 +0000
> Votes at time of UserVoice import: 53

-----------------------------------

PostgreSQL is the most innovative and hot database engine at the moment. It has better UTF-8 support and better overall performance.

Also, for example, on Heroku it is much cheaper to host with Postgres than with MySQL. Thus it becomes more attractive for people to pick a CMS/framework with Postgres support.

**Comment by brandonkelly** [comment]
Added in Craft 3.

**Comment by clarknelson** [comment]
Is this ticket the only reason it was added? Are there any performance improvements for everyday site? Is there a recommended database for new Craft 3 sites from P&T?

**Comment by angrybrad** [comment]
Lots of comparisons between the two, but it depends on your site's needs as well as your hosting options.  Here's a good overview: https://www.digitalocean.com/community/tutorials/sqlite-vs-mysql-vs-postgresql-a-comparison-of-relational-database-management-systems

If PostgreSQL is an option for you, in most cases we'd recommend it.
