### ISSUE TITLE
Exclude cache for dynamic data

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#835]
> Created by: Johannes Lamers (johanneslamers@gmail.com) on 2015/03/10 17:03:25 +0000
> Votes at time of UserVoice import: 49

-----------------------------------

Exclude parts of a cached item for dynamic user info.

In CE Cache for EE you have:

{exp:ce_cache:escape}
<p>{if logged_in}Hello {username}{if:else}Please log in{/if}</p>
{/exp:ce_cache:escape}

**Comment by skoften** [comment]
Any chance this will be implemented?

**Comment by brandonkelly** [comment]
There’s not really a clean way to do it that won’t lead to a lot of confusion, so not sure. You can do something like this though.

```twig
{% set cachedHtml %}
  {% cache %}
    <!-- ... -->
    GREETING_PLACEHOLDER
    <!-- ... -->
  {% endcache %}
{% endset %}

{% set greeting %}
  {% if currentUser %}
    <p>Hello, {{ currentUser.friendlyName }}</p>
  {% endif %}
{% endset %}

{{ cachedHtml|replace('GREETING_PLACEHOLDER', greeting)|raw }}
```
