### ISSUE TITLE
Cloud-based asset sources should support environmentVariables

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#836]
> Created by: Brandon Kelly (brandon@pixelandtonic.com) on 2015/03/06 03:54:45 +0000
> Votes at time of UserVoice import: 47

-----------------------------------

Currently it's only possible to set Asset Source settings on a per-environment basis for Local asset sources (using the environmentVariables config setting). It would be nice if the cloud-based sources (S3, Rackspace, Google) also supported environmentVariables.

**Comment by terbolous** [comment]
This is a huge issue for us, we replicate database between environments but use different buckets.

**Comment by andris-sevcenko** [comment]
Already possible via https://github.com/craftcms/docs/blob/master/en/configuration.md#overriding-volume-settings and `.env` file.
