### ISSUE TITLE
Image Assets Preview

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#837]
> Created by: Julian Rutherford (justjoolz@gmail.com) on 2015/04/19 11:42:02 +0000
> Votes at time of UserVoice import: 46

-----------------------------------

Whilst editing entires, when you double click an image asset it shows the file name and title etc., but there is no way to preview the image from here.

Even in the assets window you have to tick the asset then go to the top pull down menu to view it (and if multiple are selected you can't view them all)

A lightbox preview would be most welcome.... a basic editor too but that's another thing :)

**Comment by mediagirl** [comment]
When will this become reality takobell?

**Comment by brandonkelly** [comment]
This will be a thing starting with Craft 3 RC7 🎉

<img width="461" alt="screen shot 2018-01-20 at 6 35 52 am" src="https://user-images.githubusercontent.com/47792/35184685-bc431f1a-fdad-11e7-86ff-992567f99435.png">

**Comment by davidhellmann** [comment]
Is a step in the right direction but the focus point must be directly settable in the preview :)
