### ISSUE TITLE
Manage email settings from the config file

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#840]
> Created by: Hamish Taplin (hamish@bluegg.co.uk) on 2015/03/11 12:03:00 +0000
> Votes at time of UserVoice import: 45

-----------------------------------

Currently, it's not possible to defined environment-specific email settings. This makes things difficult if you want to test emails with a service such as MailTrap. 

Being able to define email settings in your config would makes things much more flexible.

**Comment by brandonkelly** [comment]
This is possible in Craft 3 via `config/app.php`: https://github.com/craftcms/docs/blob/master/en/configuration.md#mailer-component

**Comment by joshuabaker** [comment]
Now here: https://docs.craftcms.com/v3/config/#application-config

**Comment by joshuabaker** [comment]
@brandonkelly Is the documentation up to date? The referenced method is deprecated and I cannot get this to work.

**Comment by brandonkelly** [comment]
@joshuabaker Just updated that example to use the new method, but the old one will still work. One caveat with customizing the Mailer component from `config/app.php` is that those changes won’t be used when you test email settings from Settings → Email. (I also just updated the docs with a tip about that.) Is that where you’re finding that it’s not working?

**Comment by joshuabaker** [comment]
@brandonkelly Thanks for clarifying. I was indeed using the test function.

Is it hugely complex to get this working with the test email function? I think it’ll be confusing to be unable to see the final config on that page and be unable to test it.

In an ideal world, it’d be good to have settings from a `config/mailer.php` config file merge into the component. That’d be cleaner from a multi-environment perspective.

**Comment by brandonkelly** [comment]
That’s not possible, unfortunately. Though you can “test” your settings by creating a new user account with an email address you have access to, and check if the activation email reaches you.
