### ISSUE TITLE
Field instructions could be entered on the field layout designer

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#841]
> Created by: Trevor Davis (davist11@gmail.com) on 2015/03/25 21:20:35 +0000
> Votes at time of UserVoice import: 45

-----------------------------------

Instead of adding instructions when you are editing a field, it would be useful to add instructions when you add a field to a section (since fields can be shared across sections).

**Comment by brandonkelly** [comment]
Craft 3.5 is coming with a new field layout designer, which allows you to customize the instruction text for all fields (see https://github.com/craftcms/cms/issues/806#issuecomment-656954828).
