### ISSUE TITLE
Add support for PHP dotenv

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#843]
> Created by: Jason McCallister (themccallister@gmail.com) on 2015/03/20 17:34:31 +0000
> Votes at time of UserVoice import: 42

-----------------------------------

It would be a great idea for Craft 3.0 to support multiple environments using PHP dotenv (https://github.com/vlucas/phpdotenv). 

This is the same environment system that Laravel 5.0 uses and allows you to easily load a single file (thats different across environments).

Matt Stauffer has an excellent write up on his site here:

https://mattstauffer.co/blog/laravel-5.0-environment-detection-and-environment-variables

**Comment by themccallister** [comment]
This is technically completed and integrated with latest beta...

This could be closed @takobell!

**Comment by andris-sevcenko** [comment]
In a shocking twist of the events, I'll be the one doing the closing!
