### ISSUE TITLE
Max Image Width/Height settings

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#846]
> Created by: Brandon Kelly (brandon@pixelandtonic.com) on 2015/03/06 03:54:45 +0000
> Votes at time of UserVoice import: 40

-----------------------------------

It would be nice if it was possible to limit the width/height of images uploaded to Craft. That way if a really big image is uploaded, beyond any size you'd ever reasonably expect to serve on the website, Craft could automatically resize it down before saving, so they're not wasting so much space on the disk.

**Comment by piotrpog** [comment]
If anyone is interested, this plugin allows for resizing images upon upload:

https://plugins.craftcms.com/image-resizer
