### ISSUE TITLE
Make control panel language independent from locales

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#847]
> Created by: André Elvan (andre@vaersaagod.no) on 2015/08/27 16:07:59 +0000
> Votes at time of UserVoice import: 39

-----------------------------------

The language in the control panel is defined by the locale of the site, or the preferred locale of the user. This is fine as long as the developers and other control panel user speak the same language as the sites locale. But this isn't always the case, my english-speaking colleague creates sites that is supposed to be only in norwegian. And even though I speak both, I actually prefer having english in the control panel. 

In the case where we develop sites that are both in norwegian and english, I can set the preffered locale to english. But in addition to changing the control panel language, this also makes all new entries be created by default in the english locale. While most of the time, the norwegian site is actually the "main" site, so I usually want that to be the preferred locale, like today.

Please, can we get the option to select control panel language independently from locales. :)

**Comment by gsomoza** [comment]
Bump. Is there any chance of this happening for Craft 2 anytime soon?

**Comment by brandonkelly** [comment]
Not for Craft 2, which is mostly on a feature freeze, but just added it for Craft 3 RC1 ;)
