### ISSUE TITLE
Auto-generate Slug for Each Locale

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#849]
> Created by: Chris Comfort (chris@identity.utexas.edu) on 2015/03/31 22:13:42 +0000
> Votes at time of UserVoice import: 35

-----------------------------------

As we all know, Craft auto-generates a slug for an entry's initial title. However, after switching to a different locale and adding its locale-specific (i.e. translated) title, the slug does not auto-generate—instead, the original slug persists through each locale.

My initial expectation was that each locale would auto-generate a new slug based on its title. This seems to fall somewhere between a bug and a feature request, so I'm posting here for everyone's thoughts.

Cheers.

**Comment by ursbraem** [comment]
What about another option in the "Save" button: "Save and update slug"?

![image](https://user-images.githubusercontent.com/1446443/72943083-613bd300-3d75-11ea-89ee-ea3c870cff1a.png)

This would be loads more editor friendly than clearing it out manually. There could still be a "SEO-Warning" after clicking it to avoid over-usage by unknowing editors.

**Comment by ursbraem** [comment]
That said, it's a workaround... a possible more elegant solution would be to **clear out the slug automatically whenever an entry is opened that hasn't been manually edited once yet**. 

If no changes are made to the title, the same slug as before will be saved so no harm done. 

Wdy think?

**Comment by brandonkelly** [comment]
I don’t think people should have to worry about their entry’s URL possibly changing when they edit its title.

**Comment by ursbraem** [comment]
Sure, but on the other hand, now we have to tell the editors: whenever you translate an article, don't forget to clear out the slug before saving, else you'll have a half-french URL in your italian site.

**Comment by billmn** [comment]
Yeah I agree with @ursbraem, is annoying for editors remember to clear the slug field before save
