### ISSUE TITLE
Auto collapse left sidebar (2.5)

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#857]
> Created by: Nathan Doyle (natetronn@gmail.com) on 2015/03/11 04:20:14 +0000
> Votes at time of UserVoice import: 30

-----------------------------------

This FR was requested in Slack.

"Any thought on collapsing the sidebar by default? I feel this results in much less cognitive load when dealing with several columns and long lists!" -- jwb009

https://craftcms.slack.com/files/jwb009/F0E18PBHV/customized-entry-index_edit.png

Example: http://www.gv.com

**Comment by mark-chief** [comment]
Fantastic Idea and thanks for the cp.css! WOuld lvoe to see this rolled out.
