### ISSUE TITLE
Give Tasks the ability to continue processing if a step is unsuccessful

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#858]
> Created by: Brandon Kelly (brandon@pixelandtonic.com) on 2015/03/06 03:54:45 +0000
> Votes at time of UserVoice import: 29

-----------------------------------

It would be nice if a Task's runStep() could report that the step failed, but have the TasksService continue running the remaining steps.

Perhaps with a "$continueOnError" property on the task.

**Comment by fantasticmachine** [comment]
+ several million (hours of debugging stuck tasks)
