### ISSUE TITLE
Schedule Drafts to Publish Over Current Page

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#864]
> Created by: Ian Shea (ian@ianshea.me) on 2015/05/22 15:31:08 +0000
> Votes at time of UserVoice import: 26

-----------------------------------

With Craft there are a few ways you could setup some tricky templates/fields or matrix blocks that I can think of to accomplish scheduling content. However, I believe the easiest way would be to allow an entry to be republished with a different draft at a user specified post date. Here is a usage case scenario.

Site is for a theoretical contest.

1. Homepage Promotes Contest coming up with a countdown.
2. Admin creates a Hompeage draft set to publish at 8:00AM to begin promoting entries to contest.
3. Admin creates additional Homepage draft set to publish at 5:00PM noting the contest had ended.

This is a very simple example. But being able to schedule drafts to overtake current entries would be a powerfully awesome feature.

**Comment by raygers** [comment]
Will this feature be available in Craft 3?

**Comment by brandonkelly** [comment]
@raygers Craft doesn’t have built-in support for scheduled jobs (e.g. #1260), so it’s not a possibility yet, at least without a plugin.

**Comment by nmann4789** [comment]
Is there a timetable of when this feature will be added to Craft 3?

**Comment by brandonkelly** [comment]
@nmann4789 I was hoping to get something like this into 3.2 but ran out of time. Just added it to the `3.3` milestone.

**Comment by nmann4789** [comment]
That's great news! Any idea on a timetable for 3.3?

**Comment by brandonkelly** [comment]
Not yet, 3.2 is just in beta right now.

**Comment by sjcallender** [comment]
Similar FR here: https://github.com/craftcms/cms/issues/2116

**Comment by codyjames** [comment]
Our client is asking for this now so I am excited to see it coming in 3.3.

**Comment by timkelty** [comment]
Queue jobs currently accept a "delay", which is a little awkward for a scheduled DateTime like a publish date.

Implementing something like: https://github.com/yiisoft/yii2-queue/issues/111 seems like it would make sense.

With that in place, we could fire a "publish" event that would allow other integrations to perform necessary tasks (e.g. clear static caches).

**Comment by brandonkelly** [comment]
Going to close this in favor of #2116.
