### ISSUE TITLE
Config setting to hide blue "Updates" icon

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#866]
> Created by: Lindsey DiLoreto (lindsey@doublesecretagency.com) on 2015/03/11 04:48:18 +0000
> Votes at time of UserVoice import: 26

-----------------------------------

The `allowAutoUpdates` config setting is great! It ensures that our clients can't "accidentally" update the site in the production environment.

But they still see a giant blue icon, prompting them that updates are available. What a tease!

Would you be so kind as to add a `showUpdatesIcon` config setting as well? This way, we can hide the big blue icon from clients, and they won't feel like their website is constantly out of date.

To be perfectly clear, I'm not asking to remove the "1 update available" link at the bottom of the page. That one is subtle enough that it's reasonable to leave it in place.

Thanks! :)

**Comment by brandonkelly** [comment]
Craft 3 no longer has an update badge in the top of the sidebar.
