### ISSUE TITLE
A system wide "recycle bin" or "undelete" function

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#867]
> Created by: Keith Mancuso (keith@familiar-studio.com) on 2015/03/11 01:23:26 +0000
> Votes at time of UserVoice import: 24

-----------------------------------

I'd love to see Craft setup some way to "undelete" recently deleted items through some kind of recycling or trash bin.

A lot of systems will move data into the bin and then automatically clear out and actually delete items after 30 days or so.

We had some issues with clients accidentally deleting data and would love to see this instituted system wide

**Comment by groe** [comment]
This would be great!

**Comment by samdark** [comment]
https://github.com/yii2tech/ar-softdelete could be of help.

**Comment by RitterKnightCreative** [comment]
+ 1 for this, one thing that WP has Craft doesn't that makes sense.

**Comment by brandonkelly** [comment]
We’ve implemented soft-deletes for Craft 3.1.

@samdark Thanks for the tip! We don’t really ever use AR to delete things in Craft, but ended up using that library in case any plugins want to use it, as well as provided a trait that attaches the configured behavior.

**Comment by brandonkelly** [comment]
Soft Deletes are now a thing in Craft 3.1 Dev Preview. Announcement: https://craftcms.com/news/craft-3-1-dev-preview
