### ISSUE TITLE
Remember the last opened directory in assets

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#873]
> Created by: Anonymous (ben@fruitstudios.co.uk) on 2015/03/10 22:00:32 +0000
> Votes at time of UserVoice import: 21

-----------------------------------

So when adding multiple assets you go back to the last directory you had open. Saves multiple clicks for repetitive tasks!

**Comment by johanneslamers** [comment]
Is this in Craft 3.0?

**Comment by takobell** [comment]
This is in the latest Craft 3 beta.
