### ISSUE TITLE
Custom element statuses

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#877]
> Created by: Russ Back (russ@rallyagency.co.uk) on 2015/03/24 08:31:58 +0000
> Votes at time of UserVoice import: 20

-----------------------------------

Creating custom statuses would enable users to move entries from Draft to Ready for Review to Live etc.

The only way I can see of handling workflow like this at present is to create a field for an entry, rather than a custom system status.

**Comment by AbbeyDesign** [comment]
In EE, we were given 2-3 set statuses and then the ability to add custom ones. Freeform's Craft plugin has this ability now. Would really like this feature built into the core, it's a feature we missed from EE and installing Freeform only reminded us how indispensable this is.

**Comment by brandonkelly** [comment]
#1630 would help with this – then you could create a custom Dropdown field with your desired statuses, and create some Smart Sources for each of its possible values.

**Comment by carlcs** [comment]
I just ran into a situation where I could really benefit from overriding `Entry::getStatus()`. You think it’s reasonable to add new events for it @brandonkelly?

**Comment by brandonkelly** [comment]
I could see maybe allowing custom statues via an event.

**Comment by bymayo** [comment]
Similar, also need this for users so I can assign different user statuses. Any movement on this?

**Comment by philipboomy** [comment]
Building a real estate site where it would be nice to have custom status e.g. rented, sold, etc - Instead of having to build custom element type it would be nice to just use a channel and custom statues
