### ISSUE TITLE
Allow sections, categories and fields to be "scaffolded"

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#881]
> Created by: Jason McCallister (themccallister@gmail.com) on 2015/03/20 17:34:31 +0000
> Votes at time of UserVoice import: 18

-----------------------------------

There are quite a few situations where it would be great to have a simple file type (we could check into version control) that lets us setup a section, categories and fields. This leaves the concern that it could possibly overwrite the changes made in the CMS so a mechanism to “scaffold” the sections through the control panel, or more preferably during a Craft CMS installation, would be a great addition to our workflow.

This would also help Craft with CI. Being able to scaffold the main pieces of the CMS would allow testing critical pieces of the application (we would probably need a way to seed content into the CMS as well). 

------

Original idea:

Some CMSs - eg, Bolt and Kirby - require sections and fields to be created with a YAML file. This means that setting up a new site similar to a previous build is very quick: just a matter of copy+paste.

Whilst I don't think that the process of creating sections and fields in Craft should be like this, it would be great to have this as *one method* of setting up a site.

The way I imagine this working is that the Control panel has a section where you can upload a YAML file detailing some fields and/or sections that you'd like created. Craft would then read this file and generate the relevant tables and rows in the DB based on its content. These would then appear and be visible and usable like sections and fields generated in the usual manner.

In this way, this feature would not force current developers to change their method of setting up Craft sites, but would allow some developers to speed up their workflow.

**Comment by themccallister** [comment]
This is technically complete in the latest beta, although a complete "scaffold" might not be in place yet...

**Comment by takobell** [comment]
Technically done in a basic sense, but will leave open since we plan to flesh out the features more.

**Comment by andris-sevcenko** [comment]
Closed via 3878d16
