### ISSUE TITLE
Tags had slugs

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#883]
> Created by: Marion Newlevant (marion.newlevant@gmail.com) on 2015/03/10 22:04:02 +0000
> Votes at time of UserVoice import: 17

-----------------------------------

Life would be better if tags had slugs. Add a unique, url-friendly representation of tags. You could route to a tag page by its slug, and retrieve the original tag from the tag slug. Currently I am stuck using tag.id for this.

**Comment by Bronskiy** [comment]
this feature was in a 2.x version but now I see that it is doesn't work anymore

**Comment by Bronskiy** [comment]
so actually it is a bug. it is working if I manually create tag slug inside database

**Comment by brandonkelly** [comment]
Not possible in Craft 2 either, unless I’m missing something?

<img width="406" alt="screen shot 2018-01-28 at 10 58 36 am" src="https://user-images.githubusercontent.com/47792/35485875-45457796-041a-11e8-8a93-7152bb12d3f1.png">

**Comment by brandonkelly** [comment]
Also related: #820

**Comment by Bronskiy** [comment]
Here how it was in Craft 2:
```
{% if tag is defined %}

{% set tag = craft.tags.slug(tag).first() %}
{% set title = tag.title %}

{% set entriesToShow = craft.entries.section('scripts').relatedTo(tag) %}
{% for entry in entriesToShow %}
etc....
```
And it is still works if we have slug for existing tag

Example(sorry, it is in Russian language): https://questcorp.events/scripts/tags/gorodskie
![2018-01-28_22-18-58](https://user-images.githubusercontent.com/1948199/35486060-87e7108c-0479-11e8-8303-b30a406cb865.png)
How it was in database:
![2018-01-28_22-19-36](https://user-images.githubusercontent.com/1948199/35486054-7a1a502c-0479-11e8-9ff7-e2c679855d19.png)
If i'll create new tag after upgrade to 3.x:
![2018-01-28_22-20-08](https://user-images.githubusercontent.com/1948199/35486070-ab0f8dd2-0479-11e8-9242-be11282351b7.png)
And I just tested it on Craft 2 version:
![2018-01-28_22-26-14](https://user-images.githubusercontent.com/1948199/35486125-9bde43f2-047a-11e8-95e7-19bbd7eb32e4.png)

**Comment by brandonkelly** [comment]
Ah I see. Thanks for clarifying!
