### ISSUE TITLE
Add option to enable fuzzy search as default

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#886]
> Created by: Stephanie Socie (stephanie@fusionary.com) on 2015/06/17 15:42:56 +0000
> Votes at time of UserVoice import: 17

-----------------------------------

We have found that our content managers expect the search field to return results containing a word even if they don't include the asterisks before and after. For example, searching for the word bed should return the bedrock entry without having to type it in as *bed*.

Could this be added to the config settings to make searching a little more intuitive for our users?

**Comment by lindseydiloreto** [comment]
@takobell Would it be possible to make this the _actual_ default behavior in Craft 3? As in, you wouldn't need to change the config settings to allow it?

I think far more people would expect searching to be naturally fuzzy.

**Comment by takobell** [comment]
@lindseydiloreto sounds like a new FR. :)

**Comment by narration-sd** [comment]
It does, and I'll +1 ;)

**Comment by lindseydiloreto** [comment]
Done & done:

https://github.com/craftcms/cms/issues/1420

Upvote away! :)

**Comment by narration-sd** [comment]
+1 +1 :)

I think I already did; that's a star, right? Precognition, maybe...hmm

**Comment by narration-sd** [comment]
whoops, no, found it and did upvote...!

I guess an FR is 'a whole lot different' from an ordinary Issue -- or at least a closed one...or on Friday...!
