### ISSUE TITLE
Better Asset Permissions on Asset Fields, etc.

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#887]
> Created by: David Ritter (david.ritter@spinthis.com) on 2015/05/18 19:35:25 +0000
> Votes at time of UserVoice import: 16

-----------------------------------

Craft's permissions are pretty flexible, except when it comes to assets. 

When editing a field that allows users to choose an asset, all asset sources will appear in the modal, even ones the user has no View Source permission on. This happens on Redactor fields as well. 

The main Assets manager gets it right—and only shows the sources a user has permission to view or edit—but when it comes to editing entries or when choosing assets, everything is shown, which is not ideal.

The majority of the time, the current setup works well since most users probably want to be able to see others' content. But in  other cases, you simply don't want some users seeing other assets.

Just an example workflow. Big company launch, kind of hush hush. You have a few designers. Some of them are working up some designs. Some pages aren't ready to go live yet. The current situation makes it impossible to do something like that. 

I asked about this on support, Andris mentioned "This is to avoid situations where an Assets fields would be assigned a single source that would not be usable by some users, rendering the field unusable."

That's only part of the problem.  I would vote to disable/grey the field or let them pick another asset from a source they do have access to view. You don't want to be creating asset fields and locking down folders for every asset field, that gets to be ridiculous.

I've seen this come up a few times on SE where we need to be able to "jail" or silo a user to their own assets or at a least ones they are only supposed to see.

* http://craftcms.stackexchange.com/questions/8667/is-replace-file-a-potential-security-hole/8683#8683
* http://craftcms.stackexchange.com/questions/5046/why-cant-users-upload-files-in-this-asset
* http://craftcms.stackexchange.com/questions/10151/restricted-access-to-assets-in-redactor

**Comment by iainhenderson** [comment]
I've just run into problems with this behaviour as well.

The assets fields I'm having problems with appear in blocks as part of a 'page builder' style matrix.  

Currently the only way I can think of to properly lock down these sources is to duplicate the matrix, entry and structure multiple times with slightly different asset source settings for  each of the user groups, and then controlling access to those structures.

That would mean creating and maintaining 308 additional fields. Which as Brad stated is a bit ridiculous.

**Comment by oyvindostmo** [comment]
I'm having the same issue. It is kind of a deal breaker for the project that we are way into now, with multiple partners hosting a "partner site" on one portal. They should not be able to see each others assets, and duplicating every structure etc for each partner would be crazy time consuming. Any way this could make it to the top of the todo list? It was a total surprise, since I assumed a user without permissions for an asset source would never see it.

**Comment by brandonkelly** [comment]
Craft doesn't currently have the concept of "read" permissions; if a user has access to the Control Panel, they technically have read access to every element, whether or not they have an easy UI-based means to access them.

For example, anyone could open their JS console and paste this in:

```js
Craft.createElementSelectorModal('AssetFile', {criteria: {kind:'*'}})
```

…and an element selector will open up, revealing all the assets everywhere. They won't be able to do much with them, but the point is that Craft doesn't have any means of knowing whether any of them should absolutely not be visible, right now. And that would be a prerequisite before we could address this issue.

**Comment by brandonkelly** [comment]
We should look at this when we implement #1646.

**Comment by oyvindostmo** [comment]
Cool :)

Øyvind Østmo
Agency Manager / Advisor
Red Rabbits
—
Office: +47 24200048
Mobile: +47 90138781
Skype: red-rabbits
Web: www.redrabbits.com
Facebook: www.facebook.com/redrabbits

**Comment by BenParizek** [comment]
I find myself here after struggling with some asset permissions as well. Would love to see this improved. In the meantime, it may be a helpful first step to just clarify the existing asset permissions around Editing Assets.

Right now, it appears a user needs the following three permissions to edit assets with the Craft Image Editor:

- View source
-- Upload files
-- Remove files and folders

Nowhere in any of the permissions is image editing indicated and it took some guessing to figure out all three were needed to enable that image editor modal.

**Comment by brandonkelly** [comment]
@andris-sevcenko what do you think about adding an explicit “Edit Images” permission?

**Comment by andris-sevcenko** [comment]
@brandonkelly I've got nothing against it, but it's a bit ambiguous about what would that include. Edit and save as new or edit and overwrite? The former would be in essence an additive action, while the latter is destructive. Essentially the two different actions overlap with the permissions @BenParizek mentions, at least depending on with what purpose the permissions are used.

Maybe a rethink on the whole Asset permissions tree more in terms of scenarios, instead of actions, so that the purpose is more clear? Something like "Add files", "Modify existing files", "Remove files", "Modify folder structure" and "Edit images", which would allow whatever the editor allows (save as new and replace).

**Comment by brandonkelly** [comment]
@andris-sevcenko I think it would be obvious enough that an “Edit Images” permission means you are giving someone the ability to make destructive changes to the image. And there’s no harm done in saving as a new image. So I think if you have that permission, you will basically have full access to the Image Editor for images in that volume.

**Comment by BenParizek** [comment]
@andris-sevcenko, thinking out loud, perhaps `Upload files` and `Remove files` are both a sub-setting of `Edit Images` similar to `Create entries` and `Delete entries` being a subset of `Edit entries`.

```
- View source
- Create subfolders
- Edit Images (all sub-settings required for Edit Modal)
-- Upload files
-- Remove files and folders
```

It still may not be entirely clear that both `Upload` and `Remove` are required to see the Edit Images modal. But at least there is a more clear relationship of those sub-items being related to the `Edit Images` behavior. The parenthetical gets a little verbose, but I add it here to indicate what I struggled to understand with the current permissions as you consider options here.

**Comment by brandonkelly** [comment]
“Upload files” and “Remove files and folders” applies to things besides images, so don’t think that would make sense. I see them all as living side-by-side.

**Comment by brandonkelly** [comment]
I’ve just added a new “Show unpermitted volumes” setting for the next Craft 3.4 Beta release.

<img width="499" alt="The new “Show unpermitted volumes” setting on an Assets field" src="https://user-images.githubusercontent.com/47792/70742843-505a6500-1cd3-11ea-869d-96d5f55f9a4b.png">

The setting is disabled by default for new Assets fields, however to avoid an unexpected change in behavior, it is _enabled_ by default for existing fields. So if you want your Assets fields to respect volumes’ View permissions, just go through each of them and untick that checkbox.

**Comment by kevadamson** [comment]
Can I also throw in to the mix better permissions for users as well? i.e. the ability to hide users and user groups from other users, and also give users the ability to add users but then only see and manage the ones they have added (so it's like they have 'authored' those users). I have mentioned this in another issue: [#6280](https://github.com/craftcms/cms/issues/6280).

I have someone working on a possible plugin for this, but to have this out of the box would add an extra level of flexibility and awesomeness!
