### ISSUE TITLE
Exclude items from the indexer

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#891]
> Created by: Anonymous (dave@agilepixel.io) on 2015/03/06 22:12:59 +0000
> Votes at time of UserVoice import: 15

-----------------------------------

Add the ability to hide/exclude fields from the indexer to reduce indexer size/speed on larger sites with numerous custom fields that aren't used in search or navigation etc...

**Comment by tmulry** [comment]
The `RegisterElementSearchableAttributesEvent`  triggered by `craft\base\Element` allows modification of the searchable attributes for a given element.  This could be used to avoid indexing custom fields as needed.

**Comment by brandonkelly** [comment]
Yep, thanks for pointing that out @tmulry! Will close this now.
