### ISSUE TITLE
Tabs to separate user profile content

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#892]
> Created by: Chase Giunta (me@chasegiunta.com) on 2015/03/30 19:07:54 +0000
> Votes at time of UserVoice import: 15

-----------------------------------

Just like entries, there needs to be tabs in the user profile to separate content. This is especially useful for community driven sites, This also is somewhat of a workaround for the lack of locale-specific fields.

**Comment by johanneslamers** [comment]
Yes please. Strange this isn't core yet.

**Comment by lindseydiloreto** [comment]
Working on a project where Users will have around 30 profile fields... Splitting this into tabs would be _hugely_ helpful.

**Comment by takobell** [comment]
Users are currently the only place where field layouts are used that already have some pre-existing tabs (Account/Profile (where you can an avatar by default, but other custom fields can show up)/Permissions).

So for this to be addressed, it needs to be part of the larger field layout refactoring we want to do.

**Comment by yellostudio** [comment]
We've needed this from day one :)

**Comment by bertoost** [comment]
Still nothing on this. This is so needed now with more than 30 fields per user :$

**Comment by brandonkelly** [comment]
@bertoost Interesting idea. Related to #947 but at a tab level rather than field level. Can you please post as a new issue?

**Comment by bertoost** [comment]
@brandonkelly I have easily managed to get custom tabs for users. I will make a PR for that.
I will create a new issue for the permission idea 👍

**Comment by bertoost** [comment]
Created the update for this issue. Branched from the 2.6.2992 branche. How to merge now? Can't merge on develop, since this is 3.0 already.
https://github.com/bertoost/cms/tree/feature/custom-user-field-tabs
