### ISSUE TITLE
Install Craft using Composer

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#895]
> Created by: Potherca (potherca@hotmail.com) on 2015/05/02 21:27:13 +0000
> Votes at time of UserVoice import: 15

-----------------------------------

To enhance the developer experience it would be nice to be able to just run `composer create-project craft/craft-standard-edition my_project_name` to start working on a new Craft project.

Composer installers aren't that difficult to make and all of the other cool kids have 'm too! http://composer.github.io/installers/

**Comment by timkelty** [comment]
Oh happy day. Close it, @takobell!

**Comment by takobell** [comment]
Possible in the latest Craft 3 beta.  Thanks, Tim!
