### ISSUE TITLE
Keep user on selected field layout tab when saving content

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#897]
> Created by: Anonymous (brian@tippingmedia.com) on 2015/04/03 17:38:09 +0000
> Votes at time of UserVoice import: 14

-----------------------------------

When a user is editing content in a field layout tab I think it would make sense to keep the user on that tab when clicking "Save and continue editing".

This is especially helpful when the user forgets to populate a required field. They don't see the error message, and could assume the content is posted. But, if they are still on the active tab they will see the error message.

**Comment by brandonkelly** [comment]
This will be resolved when #1696 is implemented.
