### ISSUE TITLE
Compare Drafts / Diff Tool for Entries

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#898]
> Created by: David Ritter (david.ritter@spinthis.com) on 2015/05/18 19:35:25 +0000
> Votes at time of UserVoice import: 14

-----------------------------------

I love Craft's Drafts.  Compared to everything else out there, the live previewing, combined with sharing of unpublished drafts work extremely well.

The only thing missing is when comparing a couple drafts or a draft with the live version, it'd be great to see what the differences are.

One simple option I'd love to see is having a "compare drafts" mode; when invoked, it'd pull up a live preview with forwards and backwards buttons where you can flip between the versions and spot the differences yourself between versions. 

Looking at how other CMS do it, for example, ProcessWire has their upcoming ProDrafts feature where it shows only the fields that where changed (for example, in the case of an asset or relational field).

https://processwire.com/blog/posts/processwire-2.6.13-and-a-preview-of-prodrafts/

Some kind of diff tool for html / text fields would be superb. 

It would really interesting if it also worked with live preview. Use something like John Resig's javascript diff tool on the 2 versions and then show the differences in the live preview. 

http://ejohn.org/projects/javascript-diff-algorithm/

Handling the changed assets and matrix in the live preview would be the most challenging part I would guess, among other things, but I believe P&T could pull it off in a way that made sense.

**Comment by iamhutch** [comment]
Has this been added or will this be added soon?

**Comment by brandonkelly** [comment]
@justahutch Craft 3.4 is going to start showing which fields were edited within the draft (see https://craftcms.com/blog/craft-34). We would like to add a full-fledged comparison view down the road as well.

**Comment by binarymonkey84** [comment]
@brandonkelly Will there be audit trail type functionality to go with the diff view? Often we need to view a list of what has changed within a specific time frame, and who changed it. Filtering the list and clicking to view a diff in a quick view modal would be ideal.

**Comment by brandonkelly** [comment]
@binarymonkey84 That’s a possibility down the road.

**Comment by andreimoment** [comment]
Diff view on entry level would be very useful. 

We moved to Craft from an in-house CMS which had it and the editors who work on dozens of revisions for each document are feeling the pain of having to re-read the full content instead of just comparing the differences.

Looking forward to v.4
