### ISSUE TITLE
Structures: add option to include singles

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#899]
> Created by: Timothy Kelty (timkelty@gmail.com) on 2015/04/02 12:33:05 +0000
> Votes at time of UserVoice import: 14

-----------------------------------

I _want_ to use singles, but inevitably, I just end up with a "Home" and a "404" template.

This is because I end up with a "Pages" structure.
Entry types are great for this, except when something is truly a single and not a "type", it feels clumsy to have that listed in the entry types dropdown.

Singles don't work for me because I want to see the entries in the Structure tree, and also be able to include them with the output of nav tags.

My proposal is to add an option when creating a new Section to "Includes singles" where you could select singles to include when listing this structure. They would show in the CP Entries tab, and also output with nav tags. You would probably also want an indicator in the entries listing that the entry was actually a single.

Thoughts, ideas, comments?

**Comment by brandonkelly** [comment]
this will be implemented via #1662
