### ISSUE TITLE
Enhance the "Save" button in Live Preview

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#901]
> Created by: Christian (seelbach@gmx.de) on 2015/03/09 00:49:13 +0000
> Votes at time of UserVoice import: 14

-----------------------------------

The current implementation of the "Save" button in Live Preview would greatly benefit from some small modifications.

The first thing I wish it would do is to *not throw* you out of Live Preview when using the "Save and continue editing"​ keyboard shortcut cmd + s. The shortcut is a common way to quickly save your latest work while editing. It should not slow your workflow by throwing you out of the view.

This brings me to the next feature request, there probably should also be a "Save and continue editing" option available in the button's dropdown, to also have this feature available without making use of the keyboard shortcut. And while you're at it, what about also adding "Save and add another" and "Save as a new entry", with both actions keeping you in Live Preview.

**Comment by isnav** [comment]
This would be great 👍🏽
(Wrote to the Pixel & Tonic team over email about this and adding a thumbs up here)

**Comment by brandonkelly** [comment]
this is probably the "thumbs up" Brad was referring to: https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

**Comment by brandonkelly** [comment]
Craft 3.2 added draft autosaving, which works in both the main edit form as well as within Live Preview.
