### ISSUE TITLE
Title field as title above tabs

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#902]
> Created by: Rick (rick@thespaceinbetween.co.nz) on 2015/05/19 02:05:27 +0000
> Votes at time of UserVoice import: 13

-----------------------------------

Could the entry title field be removed from the tabbed field section (maybe make this configurable) and allow managing the title by click/double-clicking the orange title above the tabs? (if the title is editable, eg not auto-generated).

There could even be an edit icon beside it as a visual reinforcement.

This is similar to what Google Docs does..

**Comment by brandonkelly** [comment]
This isn’t really needed anymore, since titles can be placed in a specific place in the field layout since Craft 3.5.
