### ISSUE TITLE
Add asset transform events

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#905]
> Created by: brad (brad@pixelandtonic.com) on 2015/03/06 19:07:45 +0000
> Votes at time of UserVoice import: 13

-----------------------------------

It be great if onBeforeAssetTransform and onAssetTransform events were added to Craft allowing plugins to hook onto the asset transformation pipeline.

**Comment by khalwat** [comment]
This would be great, whether or not https://github.com/craftcms/cms/issues/845 is implemented

**Comment by takobell** [comment]
Honestly, I think this was already added, but I suppose not. Will look into it.

**Comment by timkelty** [comment]
👏
