### ISSUE TITLE
[3.7.0-beta.2] Can't click 'Add Asset'/'Add entry' in new matrix blocks

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#9056]
### Description

Adding a new matrix block with an assets field, the button 'Add...' is not clickable and the 'Upload files' button is missing.

![image](https://user-images.githubusercontent.com/60010597/122892426-aa66cc80-d345-11eb-9e63-7b3302c87fa4.png)

After reloading the page, everything works as expected:

![image](https://user-images.githubusercontent.com/60010597/122892747-f31e8580-d345-11eb-9135-e3673a2c51ad.png)

Same for entries fields, the button 'Add ..' is not  working until you reload the page.

Existing block can be edited as expected.

There is no error in the console. Tested in latest Chrome/Firefox/Edge

### Steps to reproduce

1. see above
2.

### Additional info

- Craft version: lates 3.7.x-dev
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by Mathias-Syversen** [comment]
I am also experiencing this, but only when there is a redactor field present in the matrix.

I get this error in the console:
![Screenshot 2021-06-22 at 16 15 20](https://user-images.githubusercontent.com/53942798/122940966-3ba16780-d375-11eb-93fb-b36fa77e0870.png)

if I save the entry, then go back to edit it, the redactor and asset field works as intended.

**Comment by adrienne** [comment]
I am also having this bug. (And there is a Redactor field present in my Matrix block as well.) I do not, however, get _any_ console errors, which I thought was weird.

**Comment by brandonkelly** [comment]
Fixed for the next release. Thanks all for reporting!

**Comment by brandonkelly** [comment]
3.7.0-beta.3 is out now with the fix.
