### ISSUE TITLE
Error on matrix field save: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '18-29' for key 'fieldlayoutfields_layoutId_fieldId_unq_idx'

### ISSUE THREAD

**Issue by brycekirk** [craftcms/cms#9061]
### Description
Adding any field to any matrix block type produces this error: `SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '18-29' for key 'fieldlayoutfields_layoutId_fieldId_unq_idx'` from `vendor/yiisoft/yii2/db/Schema.php`

### Steps to reproduce
I assume this is an error specifically with my database. Happy to provide it and logs if necessary.
1.  Add a field of any type to any block in the matrix field `contentBuilder`
2. Save > error shows after about 5 seconds

### Additional info
- My matrix field has 32 fields, some of those super tables
- Project config is set to false
- Tried running Fix FKs, does nothing

- Craft version: 3.6.17
- PHP version: 7.4.2 (tried on 7.3.9 as well)
- Database driver & version: MySQL 5.7.26
- Plugins & versions: Cookie Consent Banner, Copy, Fix FKs, Knock Knock, Redactor, Redactor Custom Styles, Redirect Manager, Site Switcher, Super Table, Typed link field, XML Sitemap

**Comment by brandonkelly** [comment]
Please send a database backup and your `composer.json` + `composer.lock` files into support@craftcms.com. We can look into it from there.
