### ISSUE TITLE
[3.7.0.beta-3] Live inline change tracking only appears for first edited element in matrix

### ISSUE THREAD

**Issue by joshua-martin** [craftcms/cms#9068]
### Description

The live inline change tracking only appears for the first edited matrix element rather than each individual matrix element. If you refresh it correctly marks the individually edited matrix elements. 

https://user-images.githubusercontent.com/1694957/123108058-fbec8580-d431-11eb-8814-6aea30ea2a02.mov

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
3.7.0-beta.4 is out now with that fix.
