### ISSUE TITLE
Slow local site; debug toolbar DB page mentions `traceLevel`?

### ISSUE THREAD

**Issue by proimage** [craftcms/cms#9069]
### Description
A local site is running very slowly (pages taking about 25 seconds to load). The Debug Toolbar on the frontend shows this:
![image](https://user-images.githubusercontent.com/1027523/123110938-36135280-d445-11eb-9350-499a9345532e.png)

What's "Check application configuration section [log] for **traceLevel**" mean?

### Steps to reproduce

1. Be me?
2. Have this site to work on?

### Additional info

- Craft version: 3.6.17
- PHP version: 7.4.16
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
	- Advanced Image Field	1.0.0
	- Azure Blob Storage	1.0.1
	- Button Box	2.0.4
	- Control Panel CSS	2.3.0
	- Craft Color Mixer	1.0.9
	- DigitalOcean Spaces Volume	1.1.3
	- Entry Instructions	1.0.7
	- Field Manager	2.2.3
	- Imager	v2.4.0
	- Imager Storage Driver for DigitalOcean Spaces	1.0.0
	- Mix	1.5.2
	- Navigation	1.4.17
	- Neo	2.10.2
	- oEmbed	1.3.9
	- Postmark	2.1.0
	- Redactor	2.8.7
	- Redactor Custom Styles	3.0.4
	- SEO	3.7.4
	- Site Switcher	2.2.0
	- Super Table	2.6.8
	- Typed link field	1.0.25

**Comment by brandonkelly** [comment]
Welp, tough to follow your steps to reproduce, and I’m not really sure what to make of that “Check application configuration…” message 🤪

People typically see significant DB performance improvements when they run the following command though:

```bash
php craft db/convert-charset utf8 utf8_unicode_ci
```

Let me know if that helps.

**Comment by proimage** [comment]
> People typically see significant DB performance improvements when they run the following command though:
> 
> ```shell
> php craft db/convert-charset utf8 utf8_unicode_ci
> ```
> 
> Let me know if that helps.

You're utterly unbelievable, you know that? How did you know?? That took requests down from the 25-30s range, to 2-3s. 😮

Incidentally, the DB was imported from a live site running MySQL 8. Not sure if that makes a difference.

**Comment by brandonkelly** [comment]
Glad to hear that! We added the command in Craft 3.6.4 after realizing that many projects had inconsistent charsets, depending on the various DB servers and Craft versions they were built on over time. 3.6.4 also started being explicit about using the utf8 charset, so it shouldn’t be something you ever need to run more than that once.
