### ISSUE TITLE
Server error occurred on background draft save

### ISSUE THREAD

**Issue by moondawg69** [craftcms/cms#9074]
Craft latest 3.6.17

I have a plain text field which serves as a place to enter a 3rd party iframe embed for an audio version of articles.

When pasting in the iframe code into the field, on a fresh new entry, the draft background save fails with a 'server error occurred' notice.

It's not a one off, happens every time. You can save the entry and everything works as it should. 

Sample embed: `<iframe src="https://app.site.blah/embed/999999999" frameborder="0" scrolling="no" style="width:100%;height:170px;overflow:hidden;"></iframe>`

<img width="858" alt="Screenshot 2021-06-24 at 08 54 17" src="https://user-images.githubusercontent.com/1304000/123226438-9220ba00-d4cb-11eb-9b42-5c2535e2676e.png">

**Comment by brandonkelly** [comment]
What is the field’s Column Type setting set to?

**Comment by moondawg69** [comment]
Automatic

**Comment by brandonkelly** [comment]
Does it have a Field Limit?

**Comment by moondawg69** [comment]
No Brandon, screenshot attached as it is for you.

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you please send a database backup and your `composer.json` + `composer.lock` files into support@craftcms.com, and point us to which section you are experiencing the issue on?

**Comment by tommysvr** [comment]
Resolved via support, was a `mod_security` issue.

**Comment by gracehcoote** [comment]
I am having this same issue, could you possibly elaborate on the mod_security fix? I can start editing an entry and then I get server errors, happens all the time. This is a live site, the issue never happened locally so I'm assuming it's server related.

**Comment by moondawg69** [comment]
> I am having this same issue, could you possibly elaborate on the mod_security fix? I can start editing an entry and then I get server errors, happens all the time. This is a live site, the issue never happened locally so I'm assuming it's server related.

Sorry, I passed this to my managed hosting and they saw the triggers in the logs and whitelisted it.

**Comment by gracehcoote** [comment]
> Sorry, I passed this to my managed hosting and they saw the triggers in the logs and whitelisted it.

No worries at all, I'll contact my hosting and see if they can assist, thanks!

**Comment by gracehcoote** [comment]
> > Sorry, I passed this to my managed hosting and they saw the triggers in the logs and whitelisted it.
> 
> No worries at all, I'll contact my hosting and see if they can assist, thanks!

Actually, I added a couple of lines to my .htaccess which for now (fingers crossed) seems to have made all the difference!

**Comment by gracehcoote** [comment]
Just incase it's of help to anyone else, my hosting company tried disabled mod_security with no success, but disabling mod_evasive actually did the trick, all seems good now at my end!
