### ISSUE TITLE
[3.7.0.beta-3] Edit button over assets disappears on smaller viewports

### ISSUE THREAD

**Issue by nickdunn** [craftcms/cms#9077]
### Description
When the slideout panel is for an asset, the "Edit" button that sits over the top of the thumbnail disappears if the slideout sidebar starts off hidden. This seems to be when the viewport is around 1535px or smaller.

### Additional info
- Craft version: 3.7-beta3

https://user-images.githubusercontent.com/39560/123286024-74704680-d505-11eb-8bee-adb71a3aa1eb.mov

**Comment by brandonkelly** [comment]
Thanks for reporting! This has already been fixed for the next release, via #9072 :)

**Comment by brandonkelly** [comment]
3.7.0-beta.4 is out now with that fix.
