### ISSUE TITLE
Option to disable (not delete) locales in settings

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#908]
> Created by: Christian Steger (christian.steger@me.com) on 2015/03/10 20:15:57 +0000
> Votes at time of UserVoice import: 12

-----------------------------------

We use always two or more locales in our projects and we have entered a lot of ready-made content in five languages.

However, sometimes we need to reduce the number of active locales.

There are two options to do that:
- disable unneeded locales in every section (error-prone)
- delete unneeded locales in settings (means deleted content)

A simple checkbox in locales settings would be great.

**Comment by piotrpog** [comment]
Yes, please. I have website with 25 sections and 12 languages. You can guess implications.

**Comment by brandonkelly** [comment]
Locales have been replaced by sites in Craft 3, so I’m going to close this in favor of #3005.
