### ISSUE TITLE
Make my amazon s3 login details available across all image sources

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#909]
> Created by: Joe Pagan (joepagan@gmail.com) on 2015/03/19 11:45:37 +0000
> Votes at time of UserVoice import: 12

-----------------------------------

Hey,

I just ran in to quite an annoying little task, I had about 20+ Image sources, and I had to add my s3 credentials to all of them.

I do like the flexibility of being able to set a different account for a different source, though 99% of the time (at least in my world) the s3 details will be the same for 1 website.

Could I suggest being able to set them in the general craft settings area? Maybe even as a matrix? Then you could select different S3 accounts to chose from a dropdown in the image source area?

also side note... The craft.request.logo could then maybe use s3 too?

**Comment by brandonkelly** [comment]
Possible in Craft 3.
