### ISSUE TITLE
[3.7.0-beta.4] Add Matrix block button adds two blocks on categories

### ISSUE THREAD

**Issue by ttempleton** [craftcms/cms#9091]
### Description

On the Craft 3.7 beta releases up to beta 4, when a Matrix field is added to a category group's field layout, trying to add a single new block to the field on a category will result in two blocks of that type being added.

### Steps to reproduce

1. Create a new category group, and add a Matrix field to its field layout
2. Create a new category in that category group
3. Add a new Matrix block

### Additional info

- Craft version: 3.7.0-beta.4
- PHP version: 8.0.3
- Database driver & version: PostgreSQL 13.2
- Plugins & versions: none

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
3.7.0-beta.5 is out now with that fix. Thanks again!
