### ISSUE TITLE
Bug/Freq id fields for Super Table matrix fields missing for GraphQL mutations

### ISSUE THREAD

**Issue by humandevs** [craftcms/cms#9092]
### Description
We're trying to update matrix blocks nested inside a super table matrix block via GraphQL, but in the GraphQL mutation the id field for the matrix block appears to be missing when it is nested inside a super table matrix block.  

The Graphiql interface shows the `id` and `sortOrder` fields for matrix fields, but the `id` field is missing for nested matrix fields inside a Super Table matrix field.

As an example, take a nested matrix field inside a Super Table Matrix field, where the outside matrix is a list of article steps, and the inside matrix is a list of content blocks within that step:

![image](https://user-images.githubusercontent.com/57273245/123531799-77f9fe00-d6bc-11eb-9696-b0712c096cd8.png)

For a normal non-nested matrix field (in this example, an article that only has one step and thus is not nested within a Super Table matrix field), to update a block you would pass in the id of the matrix itself, the sortOrder of the blocks, and a list of blocks you want to update, like this:
![image](https://user-images.githubusercontent.com/57273245/123362441-87930e80-d525-11eb-891f-a1e6a2a48fbc.png)

This will successfully update just that one block inside the matrix field, keeping the existing blocks in place.

For a nested matrix field, you would need to specify the outside matrix id and sortOrder (in addition to the inside id and sortOrder like with a normal matrix field), but the outer Super Table matrix id doesn't show as available to use for the mutation (there's no id under the parent 'blocks' node, only for the 'blocks' inside the nested 'blocks' node):
![image](https://user-images.githubusercontent.com/57273245/123547133-5fb5cd80-d714-11eb-87ce-9e749f8e37f0.png)

I'm not sure if this is a bug, or simply a limitation of the current GraphQL implementation that does not support the custom field types supplied by Super Table. In either case, we need some way to be able to mutate a nested matrix field.

### Steps to reproduce

1. Create a super table matrix that contains a normal matrix field
2. Open the graphiql UI interface and create a new mutation
3. Try to update a matrix field's block that is nested within the super table matrix block.

### Additional info

- Craft version: 3.6.17
- PHP version: 7.4
- Database driver & version:
- Plugins & versions: Super Table 2.6.8

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just assigned @andris-sevcenko to look into it, but he’s on vacation this week so expect a response next week.

**Comment by andris-sevcenko** [comment]
Looking at the SuperTable code, it looks to me it doesn't support updating blocks by their ID, yet. To be fair, we added that at a later point, too.

Can you open a new GH issue over at [verbb/super-table](https://github.com/verbb/super-table), so @engram-design can take care of it?

**Comment by humandevs** [comment]
Thanks for the quick response @andris-sevcenko!

For future googling reference, cross-posted bug at [verbb/super-table](https://github.com/verbb/super-table) is here:
[](https://github.com/verbb/super-table/issues/416)

**Comment by humandevs** [comment]
Moving discussion here, as this is more a Craft discussion rather than Super Table
From https://github.com/verbb/super-table/issues/416: 
> 
> Also, wouldn't the id of the inner block change too, in this case, still forcing you to query Craft for the ID, anyway?

Yep, you're totally right. In fact, I've considered perhaps just replacing the entire entry on each block update, for simplicity.

That still doesn't solve this nested mutation issue, though. But if the admin console and PHP can do it, I'm optimistic!

P.S.
Not to get too into the weeds on this, as this doesn't really apply to this bug/freq specifically, but I think we've mostly solved the problem of block sortOrder/id matching by pulling a fresh copy of the data just before mutation. This is helpful because it does get a little sticky if you try to specify blocks and the current block id's are now different. I don't think replacing the entire entry actually avoids the "bad stuff happens" consequences of this, because if your IDs in the mutation don't match the IDs in Craft, in my testing it does not create new blocks, but instead deletes those 'mutated' blocks with 'weird' IDs you tried to update, because your IDs were not specified as ['new']. This can be mostly solved by doing a fresh query before merging the changes into your fresh query data to use for the mutation, while checking if the sortOrder and blockType match for each atomic change. Of course, you still need to keep track of any changes that couldn't be seamlessly merged in and handle them in some other way (perhaps with a separate scorched-earth import process with lots of end-user warnings).

Normally, this wouldn't be a problem, as we'd in theory usually have fresh data already, but we're using this for import/export to/from CSV, so we have to assume the worst of our data. Thus the question "how exactly do we mutate data atomically with the least assumptions of what is around it?" And the answer was: re-export the data and merge in each of your changes atomically, as long as it matches the order and type found in the export you just made for this purpose. 

Of course, being able to just ignore block IDs and be able to pass in sortOrder as an index (like is given in queries) instead of an array of IDs would make this a bit simpler. It might make mutations even more confusing than they already are, though. sortOrder is an index on query results, but an array of IDs on mutations. Since block IDs are ephemeral, it would be handy to be able to say "whatever block in sortOrder index 2 is, mutate it to this".

**Comment by brandonkelly** [comment]
@humandevs Matrix block IDs won’t change each time an entry is saved, starting in Craft 3.7 (due out next week).
