### ISSUE TITLE
"View" button on multi-site installations always shows the primary site even when disabled

### ISSUE THREAD

**Issue by OwenMelbz** [craftcms/cms#9094]
### Description
When you create a draft entry on a multi-site installation, but only enable the new entry on one of the non-primary domains, then click the "View" button. You get taken to the primary domain which then 404s.

### Steps to reproduce

1. Setup Multi-site with at least 2 sites.
2. Create a new entry (keep as unpublished draft)
3. Disable the primary domain
4. Enable a secondary domain
5. Save it
6. Click "View"
7. Get 404 page

### Additional info

Application Info
PHP version	7.4.20
OS version	Darwin 20.5.0
Database driver & version	MySQL 8.0.25
Image driver & version	GD 7.4.20
Craft edition & version	Craft Pro 3.6.17
Yii version	2.0.42.1
Twig version	v2.14.6
Guzzle version	6.5.5

Plugins
Advance Link Field	1.1.4
CMS Guide	2.0.5
CP Field Inspect	1.2.5
Field Manager	2.2.3
Mailgun	1.4.3
Navigation	1.4.18
Neo	2.10.4
Recentchanges	1.1.3
Redactor	2.8.7
Redactor Anchors	1.1.0
Redactor Custom Styles	3.0.4
SEO	3.3.43
Super Table	2.6.8

**Comment by brandonkelly** [comment]
Couple questions:

- What are your sites’ Base URLs set to?
- What are the section’s Entry URI Format settings set to for each site?
- What is the section’s Preview Target URL setting set to?

**Comment by OwenMelbz** [comment]
Section Info:

![image](https://user-images.githubusercontent.com/1094740/123768817-94ff1e80-d8c0-11eb-87a6-75403af74f80.png)

Sites info:

![image](https://user-images.githubusercontent.com/1094740/123768942-af38fc80-d8c0-11eb-9880-233ca99e7bec.png)

**Comment by brandonkelly** [comment]
Your preview target’s URL Format isn’t an absolute URL. Just change it to `{url}` and it will start working as expected.
