### ISSUE TITLE
Transparent PNG to JPG background color

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#910]
> Created by: Ryan Payne (ryan@caddis.co) on 2016/05/06 17:57:17 +0000
> Votes at time of UserVoice import: 12

-----------------------------------

I’m currently working on a site where the client will be uploading transparent PNGs. However, I would like to convert those PNGs to JPGs for better site performance.

Currently, the image transform service adds a white background color when converting transparent PNGs to JPGs. I would like to be able to specify a different background color for the conversion.

**Comment by andris-sevcenko** [comment]
Seems very specific and can be solved with a plugin. Definitely since ba8fa7f.

**Comment by RitterKnightCreative** [comment]
Just bumped up against this today moving a Craft 2 to Craft 3 install. Transparent PNGs are turning black. I would have expected the default to be white, no?

**Comment by andris-sevcenko** [comment]
@RitterKnightCreative the color is not specified anywhere by Craft and is up to the image driver to decide when converting...

**Comment by brianjhanson** [comment]
@gglnx That's correct. As of 4.4 if you set the `mode` to `fill` and provide a fill color, that color will be used for the background fill.

**Comment by gglnx** [comment]
@brianjhanson But I want the letterbox mode, I want the crop mode, but filled with a colored background if I'm converting a transparent PNG to JPG.

**Comment by brianjhanson** [comment]
@gglnx ah yeah, the `fill` only applies to the `letterbox` mode a the moment. Can you open a new discussion about using it for other modes so we can keep it on the radar?

**Comment by gglnx** [comment]
@brianjhanson Done: https://github.com/craftcms/cms/discussions/12833 Thank you!
