### ISSUE TITLE
Mysql Timezone waring check? 

### ISSUE THREAD

**Issue by masiorama** [craftcms/cms#9101]
### Description
Hello, I recently migrated a website in craft to a webdock.io server. Everything is perfect except I have a warning message in craft panel system report:
![timezone](https://user-images.githubusercontent.com/731916/123969739-ca873300-d9b8-11eb-896d-839adc2e77ff.jpg)
as a Warning: "MySQL should be configured with full timezone support.

So far I just trid via shell on mysql user:
`SHOW GLOBAL VARIABLES LIKE 'time_zone';` which resulted in timezone = `SYSTEM`

I check ubuntu timezone and this is the result:

![systemdatectl](https://user-images.githubusercontent.com/731916/123973356-fbb53280-d9bb-11eb-9ef8-be6dfcc33b91.jpg)

I see no mysql error logs.

Any idea? As a warning is it safe to ignore it?

Thanks in advance!

- Craft version: 3.6.17
- PHP version: 7.4
- Database driver & version: mariadb 10.4
- Plugins & versions: -

**Comment by angrybrad** [comment]
@masiorama checking the global `time_zone` variable isn't a reliable check for this, but we have a KB article that explains what to look for and how to correct it here: https://craftcms.com/knowledge-base/populating-mysql-mariadb-timezone-tables

**Comment by masiorama** [comment]
Thanks! Totally missed that one.
