### ISSUE TITLE
Multisite entry issues: deletes entries from other sites, structure not translatable  

### ISSUE THREAD

**Issue by palomamtnez** [craftcms/cms#9102]
### Description

I have a Craft project with 6 different languages, each language is a different site.
The issues I have are when I duplicate entries from one site to another. 

All the structure entries are set up with the Propagation Method option _"Let each entry choose which sites it should be saved to"_, and the URI format like `{parent.uri}/{slug}`

So let's say that I have the "Our Team" and "About us" pages in the structure page list; and I enable them for the FR and ES sites. 

1. If I need the structure for the FR site "About us" as a parent, and "Our team" as a child, but for the ES site I need "About us"  and "Our team" in the same level (level 1, let's say), this seems not to be possible, is it right? 
As the site tree is not translatable (the structure is propagated to all the sites)? 

2. If I am on the entry list for the FR site, and I want to delete the pages selected (like in the image), they actually get deleted from the ES site as well, as it seems that it deletes the whole element but not just the relationship elements_sites right?  (there is not an option to just Delete for **this** site - neither warning nor anything)

![Screen Shot 2021-07-01 at 4 01 05 PM](https://user-images.githubusercontent.com/13962572/124062827-8d3ca700-da85-11eb-8532-a11ecebacbe8.png)

(For issue no. 2 I have developed temporarily a module but not sure how robust it is):
 ```
Event::on(Element::class, Element::EVENT_BEFORE_DELETE, function (ModelEvent $e) {

            // Delete the entries that just belong to the site requested (not Entity record but entity_site relationship)
            try {

                /** @var Entry $entry */
                $entry = $e->sender;

                if (! is_a($entry, Entry::class)){
                    throw new Exception("Not an entry");
                }

                $siteId = Craft::$app->getRequest()->post('criteria')['siteId'];

                if (!$siteId){
                    throw new Exception("Site was not provided");
                }

                $this->enforceSitePermission($siteId);

                $this->enforceDeleteEntryPermissions($entry);

                // Check if site is "enabled" for more than one site
                $enabledSiteIds = (new Query())
                    ->select('siteId')
                    ->from('{{%elements_sites}}')
                    ->where([
                        'enabled' => true,
                        'elementId' => $entry->id
                    ])
                    ->column();

                if (count($enabledSiteIds)  > 1) { // The entry exists in more than one site

                    // Delete the row in elements_sites
                    Db::delete(Table::ELEMENTS_SITES, [
                        'elementId' => $entry->id,
                        'siteId' => $siteId,
                    ]);

                    $e->isValid = false;
                }

            } catch (Exception $e) {
                // Dont proceed
            }

        });
```

### Additional info

- Craft version: 3.6.17
- PHP version: 7.3.27
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
![Screen Shot 2021-07-01 at 4 05 14 PM](https://user-images.githubusercontent.com/13962572/124063081-21a70980-da86-11eb-80e2-2626e4ee78fc.png)

**Comment by brandonkelly** [comment]
>     1. If I need the structure for the FR site "About us" as a parent, and "Our team" as a child, but for the ES site I need "About us"  and "Our team" in the same level (level 1, let's say), this seems not to be possible, is it right?
>        As the site tree is not translatable (the structure is propagated to all the sites)?

That’s correct. Entries can only have a single parent. If multiple parents is a requirement, you’d need to create completely separate entries for each site, rather than enabling a single entry across multiple sites.

>     2\. If I am on the entry list for the FR site, and I want to delete the pages selected (like in the image), they actually get deleted from the ES site as well, as it seems that it deletes the whole element but not just the relationship elements_sites right?  (there is not an option to just Delete for **this** site - neither warning nor anything)

Also correct. You can delete an entry for just one of its sites from the Edit Entry page via the “Delete entry for this site” option in the Save button’s context menu. The ability to delete entries for a single site has been requested – see #9022. I’ll see what I can  do to get that in for 3.7.

**Comment by brandonkelly** [comment]
Just got a new “Delete for site” element action in, for the next 3.7 Beta release ✨  #9119
