### ISSUE TITLE
Some outbound Craft requests don't respect `config/guzzle.php`

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#9105]
### Steps to reproduce

1. Create a `config/guzzle.php` file with this in it:

```
return [
    'proxy'   => 'https://google.com',
];
```

2. Load the updates page in the control panel and notice they still get loaded.

It appears that some calls (like cp-alerts) get an expected error:

> cURL error 56: Received HTTP code 404 from proxy after CONNECT (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

But that error is logged, the request continues and the updates page actually loads properly.

Guessing there's a JavaScript call to the API to fetch the results that doesn't go through Guzzle.

The Plugin Store also loads fine, which I would expect would error, too.

Note that other places (like the Feeds widget) error as expected.

### Additional info

- Craft version: 3.6.17
- PHP version: 7.4
- Plugins & versions: None

**Comment by brandonkelly** [comment]
Most API requests are sent from JS as of 3.3.16, specifically to avoid getting PHP/Craft/Guzzle involved (#5194).

Just added a new `httpProxy` setting for 3.7, which can be used instead of the `proxy` Guzzle request option, and will also affect API requests made via JS.

```php
'httpProxy' => 'https://123.456.789.0:1234',
```

**Comment by brandonkelly** [comment]
3.7.0-beta.6 is out now with that config setting.
