### ISSUE TITLE
Image assets with required fields can still be uploaded/saved with the field empty

### ISSUE THREAD

**Issue by turnstylerj** [craftcms/cms#9106]
### Description

If you have a required field on an Asset field layout (i.e. a plain text field for alt text), an asset can still be uploaded and saved to the assets folder without requiring the user to fill out said field.

Perhaps when an asset is uploaded, there should be a check for any additional required fields that would take the user to an interstitial/modal to provide the content for that field before the asset is actually uploaded and saved.

### Steps to reproduce

1. Create an asset bucket with an additional field set as required
2. Upload an image to this bucket

### Additional info

- Craft version: 3.6.17
- PHP version: 7.4.12

**Comment by darylknight** [comment]
I'm not sure this is a bug; the validation doesn't happen when the asset is saved, as it HAS to be uploaded first before it's possible to add the other required fields. If you want those fields to be validated, you need to update the options on the field on the entry. 
There's a guide for how that would work here: https://craftcms.com/accessibility/accessible-images-with-craft-cms#content-model-for-accessible-images. You need to enable the "Validate related assets" setting on the asset field.

**Comment by brandonkelly** [comment]
Sorry, this slipped through the cracks. @darylknight is correct – it’s not possible for us to fix this, so our solution is the “Validate related assets” setting on Assets fields.
