### ISSUE TITLE
[3.7.0-beta5] Multisite new category creation issue.

### ISSUE THREAD

**Issue by dreamseeker** [craftcms/cms#9107]
### Description

Only when I set up multisite, I get an error when creating a new category.

The following message will be displayed.
```
Argument 1 passed to craft\services\Elements::getEnabledSiteIdsForElement() must be of the type int, null given, called in /pathToCraftCore/vendor/twig/twig/src/Extension/CoreExtension.php on line 1511
```

### Steps to reproduce

1. Install Craft CMS 3.7.0-beta5.
2. Create a new category group.
3. Create a new category. (it's a success.)
4. Create a new site.
5. Create a new category. (it's an error.)

### Additional info

- Craft version: Craft Pro 3.7.0-beta.5
- PHP version: 7.4.20
- Database driver & version: MySQL 5.7.34
- Plugins & versions: No plugins are enabled.

**Comment by brandonkelly** [comment]
Thanks for reporting that! It’s now fixed for the next release.

**Comment by brandonkelly** [comment]
3.7.0-beta.6 is out now with that fix.
