### ISSUE TITLE
Configure new entry default status (to DRAFT)

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#911]
> Created by: migswd (miguel@silkwormdream.com) on 2015/07/20 06:07:09 +0000
> Votes at time of UserVoice import: 11

-----------------------------------

I have a client who is afraid to enter a new entry and make it live by accident when they save it. Without deliberately setting it to published. We got to understand that some clients are not tech-savvy and they have one million other things to do rather than managing their CMS website perfectly...

Previously asked here in SE : 
http://craftcms.stackexchange.com/questions/1217/is-there-any-way-to-set-a-default-status-for-entries-either-globally-or-per-sec 
http://craftcms.stackexchange.com/questions/9309/change-default-status-of-entry-publication-lightswitch-status

**Comment by groe** [comment]
There is already a setting to disable new entries by default (at least in Craft Pro). They are not saved as drafts, but as regular disabled entries then.

For my client it would be useful though to replace the "Save" button with "Save as a draft" button. Saving a draft is already possible via the save buttons dropdown menu, but they would like to prevent any accidental publishing of changes to **existing** pages as well, not only new ones.

So it would be great if there was a config setting to allow setting the default `saveEntryAction` to either `saveEntry` or `saveEntryDraft`, or something like that.

**Comment by brandonkelly** [comment]
It was always possible to specify a default entry status on localized sites, and we added the “Default Entry Status” setting for non-localized sites in v2.6.2771 (commit 89e66c1b235e6363f6a57713fbb9f6a9cac8fe04). So marking this as resolved.

@groe What you’re asking for is slightly different than what this issue is about. Can you please post as a new issue?

**Comment by groe** [comment]
Thanks for looking into it, @brandonkelly. I've created #2029 for the save as draft feature.
