### ISSUE TITLE
GraphQL : Unable to filter entries by date field comparison 

### ISSUE THREAD

**Issue by denisyilmaz** [craftcms/cms#9117]
### Description
I have a category of "dates" with a date-field attached to them.
For the list of upcoming dates i need to filter by the `date`field to only show dates that are in the future or equal to now.

### Steps to reproduce

```gql
query GetDates {
  categories(group: "dates", date: ">= now") {
    id
    language
    title
    ... on dates_Category {
      date @formatDateTime(timezone:"Europe/Berlin")
      timezone: date @formatDateTime(format:"O" timezone:"Europe/Berlin")
  }
}
```

The result is a list of all categories, even if the `date` fields is in the past.
If i change the comparison to `<= now` I get no categories returned, even with clearly having `date` fields in the past.

I tested the Plugin "Calendar" by Solspace and there this comparison is working as intended. But i can't use this plugin in my case as i have some more requirements the plugin does not cover.

### Additional info

- Craft version: 3.6.17
- PHP version: 7.4

**Comment by andris-sevcenko** [comment]
Craft does not support `now` in element queries. You would have to use today's date. For example, `{%  set categories = craft.categories.date('<= now').one() %}` would also result in an error.

I'm guessing that some settings for you are less strict, so the `false` that results from Craft parsing `now` gets interpreted as 0, so you end up with `<= 0`, which explains the all or nothing in result-set you're using.

Is it possible for you to use today's date in that expression?

I will also bring up the question internally whether we should also support "now" as a valid date in element queries (which GraphQL queries get translated in to, anyway).

**Comment by brandonkelly** [comment]
Just added support for passing date params relative to `now` for the next 3.7 Beta release ✨ 

Note that you’ll probably want to pass a `x-craft-gql-cache: no-cache` header on requests that use it, or set a relatively low [cache duration](https://craftcms.com/docs/3.x/config/config-settings.html#cacheduration) (e.g. `300` – 5 minutes). Otherwise you could get cached results that are relative to whatever time the cache was first created.

**Comment by brandonkelly** [comment]
3.7.0-beta.6 is out now with `now` support.
