### ISSUE TITLE
[3.7.0-beta.5] First time a plugin is disabled it doesn't fully disable

### ISSUE THREAD

**Issue by nickdunn** [craftcms/cms#9125]
### Description
Weird one this. I'm finding that the first time I disable a plugin it's not showing as disabled in the CP, even though the project.yaml file shows it as such. If I go to disable it a second time it appears properly disabled.

This seems to only be the _first_ time I disable each plugin. After re-enabling it, I can't then recreate the behaviour for that plugin again at all.

I also can't recreate it for all plugins. The ones that exhibit the behaviour seem to be plugins that offer field types. Plugins that don't offer custom field types seem fine.

https://user-images.githubusercontent.com/39560/124567755-31cf3800-de3c-11eb-83f6-e462e8d31cee.mov

### Additional info

- Craft version: 3.7.0-beta.5
- PHP version: 8.0.2

**Comment by brandonkelly** [comment]
For times when it doesn’t disable immediately as expected, what happens if you refresh the page after a few seconds?

**Comment by nickdunn** [comment]
I'm now not able to recreate this at all, and I'm questioning everything that's true in this world.

**Comment by brandonkelly** [comment]
Will go ahead and close this, then. We can pick it back up if you run into it again.
