### ISSUE TITLE
[3.7.0-beta.5] On multisite install, Matrix blocks not saved on all sites' revisions

### ISSUE THREAD

**Issue by ttempleton** [craftcms/cms#9128]
### Description

On a multisite Craft 3.7 beta install with a Matrix field set to a propagation method other than 'save blocks to all sites the owner element is saved in', when saving an entry on site A after a provisional draft is created, the created revision will have the Matrix blocks for site A, but if site B has different blocks then the revision will have no blocks in site B.

From my testing, it seems to be failing at this point in `craft\services\Matrix::duplicateBlocks()`...
https://github.com/craftcms/cms/blob/d2d02998aeff3f95c50cf636baa2f06927e6f43c/src/services/Matrix.php#L903-L919
...where it doesn't find any `$otherSources` or `$otherTargets`.  It may be worth noting that both the `$source` and `$target` had `isProvisionalDraft` set to `true` at this point.

### Steps to reproduce

1. Have two sites, both enabled for a section
2. Add a Matrix field to the entry type's field layout, that has its propagation method set to 'only save blocks to the site they were created in'
3. Add some Matrix blocks to both sites, save the entry a few times after provisional drafts are created
4. Check the revisions, and the blocks for the site that wasn't the one being saved when that revision was created should be missing

### Additional info

- Craft version: 3.7.0-beta.5
- PHP version: 8.0.3
- Database driver & version: PostgreSQL 13.2
- Plugins & versions: none

**Comment by brandonkelly** [comment]
Can you please provide more specific steps to reproduce – complete with clarifying which site you have selected at each step?

**Comment by ttempleton** [comment]
Sure, sorry about that.  Here are the steps I can take from a new install to reproduce this:

1. Create a new site, which I'll refer to as Site B and the default one as Site A.
2. Create a Matrix field with propagation method set to 'only save blocks to the site they were created in', with one block type containing one plain text field.
3. Create a new single section, and add the Matrix field to the entry type's field layout.
4. Edit the new entry on Site A, add one new block, save the entry.
5. Edit the entry on Site B, add one new block, save the entry.
6. Edit the entry on Site A, add some text to the block's plain text field so a provisional draft is created, then save the entry.
7. Repeat step 6 (still on Site A).
8. Open the most recent visible revision on Site A, and see that Site A's block was saved on the revision.
9. Open the most recent visible revision on Site B, and see that Site B's block was not saved on the revision.

**Comment by brandonkelly** [comment]
Thanks a lot! I was able to reproduce and get this fixed for the next release.

**Comment by brandonkelly** [comment]
3.7.0-beta.6 is out now with that fix.
