### ISSUE TITLE
`nav` Twig helper errors when entries are nested in non-consecutive order

### ISSUE THREAD

**Issue by nickdunn** [craftcms/cms#9129]
### Description
I am getting the following error using the `nav` helper:

```
Undefined array key 2
```

Here's an example:

```
{% set pages = craft.entries({ section: 'page', type: 'helpSection' }).all() %}
{% nav page in pages %} <<<<< the line that errors
{% endnav %}
```

I'm trying to revert back to a previous Craft version but this was working on latest 3.6.* before upgrading.

### Additional info

- Craft version: 3.7.0-beta.5
- PHP version: 8.0.2

**Comment by nickdunn** [comment]
More digging, I don't think this is a 3.7-beta issue, but an oddity in the way the `nav` helper works. I have a nested Structure "Pages" with a variety of entry types of which "Help Section" is one I am trying to build a navigation of.

When all of the Help Section entries are neatly nested together within the structure hierarchy all is good.

However if all of the help sections are deeply nested together under other entry types, and I then create a help section entry down at the root level of the section, I get the error. I presume this is Craft trying to make sense of the hierarchy and not able to, since one item is nested differently to the rest.

In this example it's the presence of the "aaaaaa" entry at the bottom that triggers the error. If I move "aaaaa" right above the first "Page" entry, or nest it under any other entry, the error goes away.

<img width="399" alt="Screenshot 2021-07-06 at 16 02 49" src="https://user-images.githubusercontent.com/39560/124623514-f7818d00-de73-11eb-8c1a-ea46a5c7a36a.png">

This is definitely an edge case and maybe not fixable... but it tripped us up when a CMS editor created a piece of test content and left it hanging in the tree.

**Comment by brandonkelly** [comment]
Yeah this is just a limitation of the `{% nav %}` tag – you can’t feed it an incomplete structure.
