### ISSUE TITLE
Search for fields and show field handles in the layout designer

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#913]
> Created by: Keith Mancuso (keith@familiar-studio.com) on 2015/03/11 01:23:26 +0000
> Votes at time of UserVoice import: 11

-----------------------------------

A constantly frustrating scenario is when we have a large number of fields and we're trying to find them in the layout designer interface.  

I find myself using CTRL+F in the browser every time to find them which works but isnt great.  Would love to see a great big search box above that would live filter the fields below.  

Even better if it could do things like filter the available fields by fieldtype so you could for example set a dropdown and see only the assets fields or only the rich text fields.

Would be SUPER helpful

**Comment by brandonkelly** [comment]
As of the next Craft 3.5 release, it will be possible to search for custom fields within field layout designers.

<img width="256" alt="A field search bar" src="https://user-images.githubusercontent.com/47792/87213125-6ff05500-c2d7-11ea-86d5-fe0cd969a246.png">
