### ISSUE TITLE
Categories "Set status>Disabled" action breaks individual Category Lightswitch controls and does not propagate

### ISSUE THREAD

**Issue by KarlBishop** [craftcms/cms#9135]
From the Categories structure view at /admin/categories/groupHandle, if I tick the checkbox next to one or more **enabled** Categories and choose `Set status>Disabled`, then the Categories become **disabled**.

But if I now click into one of the **disabled** Categories to edit it, the Enabled lightswitch in the sidebar shows the category is currently **enabled**. And if I leave this Lightswitch switched on and save, the Category status remains **disabled**, so the Lightswitch control does not work. (I have to `Set status` back to **enabled** to fix the Lightswitch).

Also, if I use the Lightswitch control to disable a Category, I find this change is propagated across my sites.
But if I use `Set status` to disable a Category, then the change is not propagated.

### Additional info

- Craft version: Craft Pro 3.6.17
- PHP version: 7.4.15
- Database driver & version: MySQL 8.0.23
- Plugins & versions:
  - Asset Usage	2.2.1
  - Blitz	3.10.0
  - Bulk Edit	2.0.5
  - Campaign	1.19.2
  - Cloner	1.2.2
  - Control Panel Nav	3.0.17
  - Copy	1.0.5
  - Dashboard Begone	1.0.1
  - Element API	2.7.0
  - Embedded Assets	2.7.0
  - Feed Me	4.3.6
  - fortrabbit Object Storage Volume	2.1.0
  - Freeform	3.11.9
  - Image Resizer	2.1.0
  - Minify	1.2.10
  - Patrol	3.1.3
  - Preparse Field	1.2.5
  - Redactor	2.8.7
  - Redirect Manager	1.1.1
  - Retcon	2.2.3
  - SEOmatic	3.3.43
  - Sherlock	3.1.3
  - Super Table	2.6.8

**Comment by brandonkelly** [comment]
This was reported recently via #7636, and we’ve fixed it for Craft 3.7 (due out in one week).
