### ISSUE TITLE
The sorting of currency types available to format a number field is suspect

### ISSUE THREAD

**Issue by stevecomrie** [craftcms/cms#9141]
### Description

Here is an example of the first 40 results:

- AFN
- EUR
- ALL
- DZD
- USD
- AOA
- XCD
- ARS
- AMD
- AWG
- AUD
- AZN
- BSD
- BHD
- BDT
- BBD
- BYN
- BYR
- BZD
- XOF
- BMD
- INR
- BTN
- BOB
- BOV
- BAM
- BWP
- NOK
- BRL
- BND
- BGN
- BIF
- CVE
- KHR
- XAF
- CAD
- KYD
- CLP
- CLF
- CNY

Trying to find CAD in that list was challenging. I'm not sure what these are being sorted by, but it doesn't appear to be the currency symbol. Perhaps the country name, with a couple common options floated to the top?

### Steps to reproduce

1. Create a new Number field type
2. Set the Preview format to "As currency value"
3. Look at the ordering of currencies types in the associated select field

### Additional info

- Craft version: 3.6.17

**Comment by brandonkelly** [comment]
Whoops, thanks for pointing that out. Fixed for the next release.

**Comment by stevecomrie** [comment]
No. Thank you :)
