### ISSUE TITLE
Image Editor: Can't select crop edges at small viewport width

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#9143]
### Description
At small viewport widths, the image editor shrinks to display the asset at full screen width. This results in the draggable edges of the image editor selecting my browser window instead of the edge of the image crop.

Adding some padding here would resolve this issue.

### Additional info

- Craft version: 3.6.17

**Comment by andris-sevcenko** [comment]
This has been adjusted in Craft 3.7!

**Comment by brandonkelly** [comment]
Whoops, forgot to update this, but we also got the change into 3.6.18, so you can update to that if you’re not ready to update to 3.7 yet. Just change your `craftcms/cms` requirement in `composer.json` to `"~3.6.18"` and run `composer update`.
