### ISSUE TITLE
HTML is not an allowed file extension. "Keep both/replace"

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#9147]
### Description
A client has an S3 bucket which I'm in the process of emptying. There are some HTML files in there, and when I try to move them either to a local volume or to a subfolder on S3, I get this modal:

![image](https://user-images.githubusercontent.com/1250017/125048677-d6ee4880-e0a8-11eb-82c3-1d73f80ebde1.png)

I know how to fix the 'not an allowed file extension', but it shouldn't asking me whether to keep/replace them. If I select either of those options, it just re-opens the modal window again and doesn't move the files.

**Comment by brandonkelly** [comment]
We just released Craft 3.7.1 with a fix for this. Thanks for reporting!
