### ISSUE TITLE
Craft::$app->request->isPreview returns false when using X-Craft-Token header

### ISSUE THREAD

**Issue by Zae** [craftcms/cms#9148]
### Description
When using the `X-Craft-Token` header, this flag on the request object still returns false, while I believe it should be returning true, because a token is set on the request.

### Steps to reproduce

1. use the `X-Craft-Token` header on the request
2. `Craft::$app->request->isPreview` returns false
3. `Craft::$app->request->getIsPreview()` returns false

### Additional info

- Craft version: 3.6.17
- PHP version: 7.4
- Database driver & version: MySQL 8.0.25
- Plugins & versions:

Related:
https://github.com/craftcms/element-api/issues/143

**Comment by brandonkelly** [comment]
Tokens can be used for more than just preview requests. The method will only return `true` if the request contains a `x-craft-preview` or `x-craft-live-preview` query string param.
