### ISSUE TITLE
"No primary site exists" when installing new project using project config

### ISSUE THREAD

**Issue by weotch** [craftcms/cms#9151]
### Description

Here's what I'm seeing when running `craft setup`

```
...
    > add foreign key fk_rrnqcdftpyggcrieacwecdowwbiatjkulnta: {{%widgets}} (userId) references {{%users}} (id) ... done (time: 0.009s)
    > populating the info table ... done
    > installing colorit ... done
    > installing cp-css ... done
    > installing cp-js ... done
    > installing dashboard-begone ... done
    > installing dospaces ... done
    > installing neo ... done
    > installing redactor ... done
    > installing sentry ... done
    > installing super-table ... done
    > installing webhooks ... done
    > applying existing project config ... done
Exception: No primary site exists (/Users/reinhard/Desktop/test8/craft-cms/vendor/craftcms/cms/src/services/Sites.php:518)
#0 /Users/reinhard/Desktop/test8/craft-cms/vendor/craftcms/cms/src/migrations/Install.php(1118): craft\services\Sites->getPrimarySite()
#1 /Users/reinhard/Desktop/test8/craft-cms/vendor/craftcms/cms/src/migrations/Install.php(74): craft\migrations\Install->insertDefaultData()
#2 /Users/reinhard/Desktop/test8/craft-cms/vendor/craftcms/cms/src/db/Migration.php(52): craft\migrations\Install->safeUp()
#3 /Users/reinhard/Desktop/test8/craft-cms/vendor/craftcms/cms/src/db/MigrationManager.php(232): craft\db\Migration->up(true)
#4 /Users/reinhard/Desktop/test8/craft-cms/vendor/craftcms/cms/src/console/controllers/InstallController.php(179): craft\db\MigrationManager->migrateUp(Object(craft\migrations\Install))
....
```

This sounds very similar to #6943.  My use case is i'm working [on a scaffolding project](https://github.com/BKWLD/create-cloak-app) and I want to hydrate my Craft instance with a number of common patterns of our organization.

I've noticed that after the `craft setup` fails, if I run `craft project-config/apply`, the site is created and I can access /admin, though I can't login because the admin user was never created.

### Steps to reproduce

1. Download https://github.com/BKWLD/create-cloak-app/tree/main/template/craft-cms
2. Run `composer install && ./craft setup`
3. You should run into the above error after supplying values for the initial setup prompts

### Additional info

- Craft version: Craft Pro 3.6.17
- PHP version: 7.4.20
- Database driver & version: MySQL 8.0.25
- Plugins & versions:

![image](https://user-images.githubusercontent.com/77567/125177471-d29d5a80-e190-11eb-8077-06006374b059.png)

**Comment by brandonkelly** [comment]
Can you email a zip of your `composer.json` and `composer.lock` files, as well as your whole `config/project/` folder you had in place during install, over to support@craftcms.com? We can try to reproduce / look into it from there.

**Comment by weotch** [comment]
Well, I tried many variations and the whole thing that dependably resolve this issue was splitting up the `craft setup` command into multiple steps.  Now my project generator runs these in a series:

- `./craft setup/app-id`
- `./craft setup/security-key`
- `./craft setup/db`
- `./craft install`
- `./craft migrate/all --no-backup=1 --interactive=0`

This is grasping, but one thought I had about why this works may be related to the changes to the `.env` were not all available to the subprocesses when run through `./craft setup` but, when separated out as different command, they are picked up in time?  🤷‍♂️

Anyway, this is resolved enough for me.

**Comment by brandonkelly** [comment]
Strange… glad that works though!
