### ISSUE TITLE
Config setting for cache disabling

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#917]
> Created by: Mats Mikkel Rummelhoff (mail@mmikkel.no) on 2015/03/09 00:12:31 +0000
> Votes at time of UserVoice import: 11

-----------------------------------

It would be nice if there was a config setting for completely disabling the {% cache %} tag.

**Comment by brandonkelly** [comment]
We added an `enableTemplateCaching` config setting in Craft 2.4.
