### ISSUE TITLE
Field handle validation should take place on an element level basis, not globally

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#918]
> Created by: brad (brad@pixelandtonic.com) on 2015/03/06 19:07:45 +0000
> Votes at time of UserVoice import: 11

-----------------------------------

Would go along well with the field layout refactoring involved in https://github.com/craftcms/cms/issues/806 and https://github.com/craftcms/cms/issues/822

Currently if you create a field with a handle of "postDate" (for example), you will get undesired behavior when dealing with entries because while "postDate" is a reserved word in the context of entries, it's perfectly valid to use in other element contexts (Assets, Users, Tags, etc).  Since field handle validation is currently handled globally, there isn't a clean way to warn the user about the possible conflict with entries.

If field handle validation was handled on a per-element basis, then you could give a validation error message in the context of entries and allow the handle in other element contexts.

**Comment by brandonkelly** [comment]
this will be implemented via #1524
