### ISSUE TITLE
Add ability to change default to Position Select field

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#920]
> Created by: Phil Zelnar (phil@andphil.com) on 2015/03/18 20:09:09 +0000
> Votes at time of UserVoice import: 11

-----------------------------------

A small-ish thing, but it'd be helpful if you could choose the default setting for a Position Select field.

**Comment by brandonkelly** [comment]
[Button Box](https://github.com/supercool/Button-Box) is a good alternative if you need this. Lets you specify the default option.

**Comment by admench** [comment]
+1 for this feature. Thanks guys

**Comment by brandonkelly** [comment]
@admench Please just add 👍 reactions to the original post rather than +1 comments, thanks!

**Comment by admench** [comment]
Ok! Duly noted, thanks!

**Comment by AbbeyDesign** [comment]
If the only alternative to fix this issue is to install a plugin, can Craft at least change the default position from "left" to "full"?
