### ISSUE TITLE
Rename Singles Option

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#921]
> Created by: Julian Rutherford (justjoolz@gmail.com) on 2015/04/19 11:42:02 +0000
> Votes at time of UserVoice import: 10

-----------------------------------

The ability to add headers in the entries section and rearrange the order of channels etc. in 2.5 is really great.

Continuing in this customizing direction the ability to change the title of 'singles' to something else from the gear panel would be really great.

**Comment by mdunnerstick** [comment]
Will this be done?  Has anyone found a plugin?

**Comment by matthewstick** [comment]
I figured out a work around.  You need to set up a translation file.

So in my case I made an "en" folder for English, and then re-mapped it.

This linked helped:
https://cl.ly/6e5132433d70

**Comment by daveyjones** [comment]
@angrybrad I have the same issue. I always tell clients to read "Singles" as "Pages", because that's almost always what singles represent in my projects.

@matthewstick Great workaround!
