### ISSUE TITLE
Deprecations errors shouldn't alarm all users who don't understand them

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#925]
> Created by: Ben Parizek (ben@barrelstrengthdesign.com) on 2015/03/12 23:19:32 +0000
> Votes at time of UserVoice import: 10

-----------------------------------

Currently, Craft boasts the presence of all deprecation errors at the top of the dashboard as the first thing that any admin sees when they log into Craft.  The design of the notice is not too loud, but it's position makes it front-and center; the message uses the word "error"; and the logo of a warning sign is used, which is the same sign that is used on sinuous mountain roads to alert drivers that their cars can spin out of control, crash through the traffic barrier, roll over the cliff, and submerge all passengers at the bottom of the ocean.

Not all users understand that these messages usually only matter to plugin developers and are meant to indicate that an update to the plugin needs to be made to address the issue before the next major release of the software, which doesn't happen very often.

This misunderstanding is reasonable, as are the actions taken due to it, but it results in lots of unnecessary support requests and managing expectations for plugin developers and the users concern could be avoided if the message were designed better.  Plugin developers will still no what it means, and the average user can go happily about their day without worrying about the critical issue that is unlikely to matter by the time the next major version of the software gets released.

**Comment by brandonkelly** [comment]
In Craft 3, deprecation errors are only shown to admins with the Debug Toolbar enabled, or users with access to the Deprecation Errors utility in the Control Panel.
