### ISSUE TITLE
Add 'default' option to the number field

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#927]
> Created by: Neal Stammers (neal@netgorilla.co.uk) on 2015/03/10 18:02:16 +0000
> Votes at time of UserVoice import: 10

-----------------------------------

When adding a number field you can currently set the min and max, but it would be useful to also be able to set a default value.

Thanks, Neal.

**Comment by Visiluna** [comment]
Yes, please, please, please!

**Comment by brandonkelly** [comment]
@Visiluna feel free to add a 👍 reaction to the original post ;)

**Comment by Visiluna** [comment]
Not sure how to do that

**Comment by narration-sd** [comment]
@Visiluna  he just means to use the little emoji button on the upper right corner of the original posting. When you click it, you get some choices, including  👍 , which means +1. 

These are counted, so yours will be added fairly and visibly. And this way also, not a string of comments added to do it. Take care.

**Comment by brandonkelly** [comment]
https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

**Comment by Visiluna** [comment]
I was view it on my phone, where apparently adding reactions is not an option. I've added it now, thanks.

**Comment by benface** [comment]
I believe this can be closed? :P
