### ISSUE TITLE
Change User Photo to be an 'Asset' and allow for external storage capabilities

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#933]
> Created by: Nate Iler (nate@flipboxdigital.com) on 2015/03/11 14:29:14 +0000
> Votes at time of UserVoice import: 9

-----------------------------------

The UserModel has a 'photo' attribute and several methods to get photo urls, but it doesn't follow any of the existing Asset model functionality.  It would be great if we could handle user photos the same way Assets are handled: external storage, etc.

**Comment by brandonkelly** [comment]
This is a thing in Craft 3.
