### ISSUE TITLE
Option to keep CP language in English

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#943]
> Created by: MISC (ost@misc.ch) on 2015/03/13 11:06:11 +0000
> Votes at time of UserVoice import: 8

-----------------------------------

Unfortunately, 'defaultCpLanguage' does not overwrite the localization. My idea is to have a possiblity the keep the CP language in general in English (independently from locales). Most of the developpers work in English, even it they create website in other languages. Someone who is not able read the English documentation will not be able to use Craft.

**Comment by benface** [comment]
@takobell That link doesn't work anymore, but from the slug in the URL I can tell it's probably the same thing, and it's something I would like too. Also read the comments in the accepted answer here: https://craftcms.stackexchange.com/questions/9784/how-do-i-have-my-control-panel-in-english-but-my-site-locale-to-dutch/12636. I think it explains the problem very well.

**Comment by takobell** [comment]
@benface Updated to previous link to the equivalent issue on Github.

**Comment by benface** [comment]
Ah! Yes that's the same thing. I'm not ost@misc.ch but I'm pretty sure that's what he meant. I'm going to go +1 that issue. :)
