### ISSUE TITLE
Plugin unit testing was an easy thing to integrate

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#944]
> Created by: Russ Back (russ@rallyagency.co.uk) on 2015/03/24 08:31:58 +0000
> Votes at time of UserVoice import: 8

-----------------------------------

Unit testing can be hard, and although there's a plugin out there that aims to help, the name of it kind of gives away how hard this is right now (loath).

Integration of something like PhpSpec would be great as part of the core.

**Comment by themccallister** [comment]
Craft 3 beta has a lot of bootstrapping setup in the main repository now, but some extra help on bootstrapping/testing plugins would be amazing!

**Comment by gtettelaar** [comment]
As of Craft [3.2 BETA-1](https://github.com/craftcms/cms/blob/3.2/CHANGELOG-v3.md#320-beta1---2019-06-04), there is now a formalized testing Framework for Craft. Based on Codeception with support for sites, modules and plugins in various testing styles.
