### ISSUE TITLE
Allow to assign other members to a user group, but not set individual permissions

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#945]
> Created by: Visiluna (pjones@visiluna.com) on 2015/06/16 22:04:13 +0000
> Votes at time of UserVoice import: 8

-----------------------------------

Currently when assigning privileges to a user or user group, "Assign user groups and permissions" is a single assignable option. This should be two separate options, "Assign user groups" and "Assign permissions."

There are many cases when I set up an administrative group that needs to be able to create users and assign them to an existing group, but I do not want them to be able to modify individual permissions.

I also would like to be able to say, "Members of Group A can assign other users to Groups B and C, but not to Groups D, E or F."

**Comment by joelzerner** [comment]
Looks like this one might be resolved.

**Comment by brandonkelly** [comment]
Good catch, this was resolved in [Craft 2.6.2996](https://github.com/craftcms/cms/blob/master/CHANGELOG-v2.md#262996---2017-11-08) per #2087.
