### ISSUE TITLE
Field-level permissions

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#947]
> Created by: Visiluna (pjones@visiluna.com) on 2015/06/16 22:04:13 +0000
> Votes at time of UserVoice import: 8

-----------------------------------

I'd like to be able to restrict certain fields to specific member groups. 

Example: A user profile that contains a bunch of fields for contact information and a field for a "commission rate." A user should be able to edit the fields for their contact information, but only a member of a "management" user group should be able to see/edit the "commission rate" field.

**Comment by thejoshsmith** [comment]
@angrybrad I've written a plugin which should do what you're after (although we're a couple of years on!): https://plugins.craftcms.com/craft-fab-permissions

I'd be happy to hear any feedback you might have!
