### ISSUE TITLE
Specify a default for the Color fieldtype

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#949]
> Created by: Lewis Jenkins (mail@lewisjenkins.uk) on 2015/03/10 23:47:17 +0000
> Votes at time of UserVoice import: 8

-----------------------------------

A simple request. Currently the color fieldtype always defaults to black. It would be great if we could choose a default color / colour.

**Comment by McCrisp** [comment]
+1 for this.

Have a lot of customers with their own colors, being able to set a default value here would be great!

**Comment by brandonkelly** [comment]
Just implemented this for Craft 3 RC1.
