### ISSUE TITLE
URL Field Type

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#953]
> Created by: Tom (t@klepl.com) on 2015/04/20 17:54:59 +0000
> Votes at time of UserVoice import: 8

-----------------------------------

A native field type for validating a URL would be very good to have. Until then I am going to try the VZ URL plugin - https://github.com/elivz/VzUrl-Craft

**Comment by proimage** [comment]
I'd like to see this as well; it feels like Redactor fields get special treatment as far as linking capabilities go, with the options to select either an entry to link to, or input the URL directly. A native custom field to accomplish the same would be wonderful.

**Comment by benface** [comment]
Looks like this can be closed: https://github.com/craftcms/cms/commit/5e4288ffdadab930425445ab15352a832d8ad0dc

**Comment by brandonkelly** [comment]
Yep!
