### ISSUE TITLE
Content from default site are duplicated to new site when enabling singles.

### ISSUE THREAD

**Issue by lassemt** [craftcms/cms#9552]
### Description
When enabling a single section for a new site, contents of fields from the default site are copied to the newly enabled single. There are no propagation method option for singles, so one might expect the new single would be empty when created.

### Steps to reproduce
1. Fill contents of fields on a single for the default site.
2. Create a new site, and enable the single section for new site.
3. See that content from the single on the default site are duplicated over to the newly enabled single.

### Additional info
- Craft version: Craft Pro 3.6.17
- PHP version: 8.3
- Database driver & version: MySQL 8.0.25
- Plugins & versions: None

If one is using {site.handle} in asset locations, asssets will be moved over to the new folder for the newly created site when the single is enabled.

**Comment by brandonkelly** [comment]
This is working as expected; the existing content is just there for convenience as a starting point. You can make site-specific changes from there, depending on your fields’ Translation Method settings.

**Comment by lassemt** [comment]
@brandonkelly Okay, that is registered. I'll wipe the fields with `Element::EVENT_BEFORE_SAVE` when enabled instead. Thank you for the quick response!

**Comment by ezawadzki** [comment]
@brandonkelly thanks for you tips : changing "Translation Method" works for textual fields. This is not the case for "Assets" fields. They are duplicated and common for all sites. Can't change them individually. Do you have a solution for that ?

**Comment by lassemt** [comment]
> @brandonkelly thanks for you tips : changing "Translation Method" works for textual fields. This is not the case for "Assets" fields. They are duplicated and common for all sites in a single. Can't change them individually for each single per site. Do you have a solution for that ?

In my case, we had a multi-site installation where we wanted each new site to start fresh. We ended up moving all singles into structures instead. After this, we have stopped using singles on the new project as well since we are a lot more flexible with structures.
