### ISSUE TITLE
category issues on multisite

### ISSUE THREAD

**Issue by adrienne** [craftcms/cms#9555]
I have a multisite setup with category groups that are enabled across sites, but the categories are different per-site. Categories show up as "disabled" for sites that they are disabled for, which would be okay except there's no way in the normal status dropdown to limit to Enabled -- the only options are "All" or "Trashed": 
![image](https://user-images.githubusercontent.com/89705/125498173-00d6153b-4226-4267-bfb2-3aa3e5d2253f.png)

There's also no way to "Delete for This Site" as there is with entries, only to enable or disable per-site, which means i can't remove them that way either.

At a minimum, "Enabled" needs to be an option on that dropdown menu (and probably should be the default.) **Ideally** you would be able to delete categories from inapplicable sites instead of just disabling them.

- Craft version: 3.7b6

**Comment by brandonkelly** [comment]
Found & fixed the culprit. I guess when we first launched categories in Craft 2, they must not have supported statuses yet, so the index page was intentionally disabling the status options:

https://github.com/craftcms/cms/blob/8dde6b591ed0f6b317bf46df1233e118cb944af9/src/templates/categories/index.html#L4

**Comment by brandonkelly** [comment]
Craft 3.7.1 is out now with that change. Thanks for reporting!

**Comment by disco666** [comment]
Hi, we have just noticed in a multisite setup that if a user adds a category it will also be added and enabled in all sites even though access rights are only granted for two specific sites. We would expect that the categories are only enabled in sites where the user has access/editing rights.

**Comment by brandonkelly** [comment]
@disco666 That’s intended. All categories exist across all sites. The permissions only determine which sites a user is allowed to edit.

**Comment by adrienne** [comment]
@brandonkelly - I continue to maintain that it would be really good to have a way to *disable* and to *delete* categories per-site.
