### ISSUE TITLE
Sitetree changed for multisite entries when they are cloned

### ISSUE THREAD

**Issue by palomamtnez** [craftcms/cms#9558]
### Description
When cloning/enabling pages between multisites (eg enabling a page ‘history’ from one site to another) and then turning the cloned page off on the new site it creates an issue where the original entry moves out of place in the site tree- or it moves into trash (both happen in a seemingly random order). 

The expected behaviour would be just to disable it

### Steps to reproduce

1. Enter ‘our values’ page on global english, press enable for europe - dutch and then save

<img width="1246" alt="Screen Shot 2021-07-14 at 8 14 14 PM" src="https://user-images.githubusercontent.com/13962572/125587888-02f0433f-3223-4e0c-bb9b-cbd419e79f46.png">

2. Go to europe dutch multisite, disable page and hit save 
<img width="777" alt="Screen Shot 2021-07-14 at 8 15 52 PM" src="https://user-images.githubusercontent.com/13962572/125588070-7494c37d-a220-4898-af13-ec7caf4c34fa.png">

3. Go back to global english site and the page is still there but has been moved out of the correct structure and is now not nestled under its parent page 

4. The original page on global english also has content wiped (see example from same steps on another page) where all test revisions to test cloning have wiped content blocks. Revision 7 is what I had to revert back to in order to get content blocks back. 

<img width="842" alt="Screen Shot 2021-07-14 at 8 19 12 PM" src="https://user-images.githubusercontent.com/13962572/125588553-e6d4d68c-b440-422f-8a57-f903c0557413.png">

Is this entry for the English site saved as new one? or is there a reason why it changed the sitetree position for that site?

 
### Additional info

PHP version	7.4.19
OS version	Linux 5.4.0-51-generic
Database driver & version	MySQL 5.7.32
Image driver & version	Imagick 3.4.4 (ImageMagick 6.9.10-23)
Craft edition & version	Craft Pro 3.7.0
Yii version	2.0.42.1
Twig version	v2.14.6
Guzzle version	7.3.0

Plugins
Colour Swatches	1.4.1.1
Field Manager	2.2.4
Freeform	3.11.9
Imager X	v3.4.1
Navigation	1.4.19
Neo	2.11.0
Redactor	2.8.7
SEO	3.3.44
Typed link field	2.0.0-rc.1

**Comment by brandonkelly** [comment]
Guessing this is related to spicywebau/craft-neo#479.

**Comment by palomamtnez** [comment]
Yip,that was the issue:) thanks
