### ISSUE TITLE
Database Exception "could not acquire a lock to save a revision for element" when updating entry without a revision

### ISSUE THREAD

**Issue by bliswebagency** [craftcms/cms#9559]
### Description

When updating an existing entry that has had it's revisions removed, the below exception is raised. Subsequent saves do not produce the exception, unless the revisions are pruned again.

This is from a newly created craft install from command line ./craft install/craft , with a single structure section for pages, 2 entry types, and a single plain text field for testing.

We had noticed this issue occur intermittently on 3.6 but it appears to happen consistently with 3.7

Thanks

```
Could not acquire a lock to save a revision for element 16

in /craft/vendor/craftcms/cms/src/services/Revisions.php at line 77

    {
        // Make sure the source isn't a draft or revision
        if ($source->getIsDraft() || $source->getIsRevision()) {
            throw new InvalidArgumentException('Cannot create a revision from another revision or draft.');
        }
 
        $lockKey = 'revision:' . $source->id;
        $mutex = Craft::$app->getMutex();
        if (!$mutex->acquire($lockKey)) {
            throw new Exception('Could not acquire a lock to save a revision for element ' . $source->id);
        }
 
        $db = Craft::$app->getDb();
 
        $num = ArrayHelper::remove($newAttributes, 'revisionNum');
 
        if (!$force || !$num) {
            // Find the source's last revision number, if it has one
            $lastRevisionNum = $db->usePrimary(function() use ($source) {
```

### Steps to reproduce

1. Run craft utils/prune-revisions --max-revisions 0
2. Open existing entry, make edit to entry
3. Save- exception raised
4. Return to existing entry, make edit to entry
5. Save- no error

### Additional info

- Craft version: 3.7.0
- PHP version: 7.4.21
- Database driver & version: MySQL 5.6.16
- Plugins & versions: No plugins installed

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Are you overriding the `mutex` component in `config/app.php` by chance?

**Comment by bliswebagency** [comment]
Hi Brandon, no we're not overriding the mutex in config/app.php. It is the default one from the craft repo.

**Comment by brandonkelly** [comment]
Is it happening on an environment we could get access to by chance? If so can you please send SSH credentials over to support@craftcms.com?

**Comment by bliswebagency** [comment]
Thank you Brandon.. We were in the process of testing on a new environment and found that this error stopped occuring. Both use the same PHP versions but the MySQL versions are different. Does getMutex depend on mysql when it acquires a lock?

old envrionment:
PHP version 	7.4.21
OS version 	Linux 4.4.0-170-generic
Database driver & version 	MySQL 5.6.16

new environment:
PHP version 	7.4.21
OS version 	Linux 4.4.0-119-generic
Database driver & version 	MySQL 5.7.33

**Comment by brandonkelly** [comment]
Yeah the locks are handled by MySQL by default. Shouldn’t be any difference between 5.6 and 5.7; perhaps your 5.6 DB just got into a weird state internally. Glad it’s working with 5.7 though!
