### ISSUE TITLE
Deprecation warnings from within vendor/craftcms/cms after upgrading to Craft CMS 3.7

### ISSUE THREAD

**Issue by realjoshharrison** [craftcms/cms#9560]
### Description

After upgrading to Craft 3.7, two deprecation warnings are logged after accessing the entry editor screen:

| Message | Origin |
| --- | --- |
| Elements’ `getSourceId()` method has been deprecated. Use `getCanonicalId()` instead. | `.../app/vendor/craftcms/cms/src/templates/_layouts/element.html:521` |
| Elements’ `getSourceId()` method has been deprecated. Use `getCanonicalId()` instead. | `.../app/vendor/craftcms/cms/src/templates/_layouts/element.html:363` |

### Steps to reproduce

1. Update to Craft 3.7
2. Access entry edit screen
3. Check deprecation warnings

### Additional info

- Craft version: 3.7
- PHP version: 7.4.21
- Database driver & version: MySQL 10.3.29
- Plugins & versions: Redactor 2.8.7

**Comment by realjoshharrison** [comment]
Just seen you're already aware of this, with a fix in PR #9556. Thanks

**Comment by brandonkelly** [comment]
Craft 3.7.1 is out now with that fix.
