### ISSUE TITLE
Slugs not saved on new entries in 3.7.0

### ISSUE THREAD

**Issue by dmatthams** [craftcms/cms#9561]
### Description

Slugs do not seem to save on the first save of a new entry, but do on subsequent saves.

### Steps to reproduce

1. Create a new entry
2. Save with cmd + s or clicking button
3. Get a message saying 'Draft applied'
4. If you enable the slug column in the entry listing it shows a temporary slug
5. View the entry again and the slug field will be empty
6. Press save again, and the slug will now be correct

### Additional info

- Craft version: 3.7.0
- PHP version: 7.4
- Database driver & version: Mysql
- Plugins & versions: None

**Comment by dmatthams** [comment]
I believe this only happens when using **Title Format**

**Comment by brandonkelly** [comment]
That’s working as expected. The only time the JavaScript can auto-suggest a Slug for you is when the Title field is visible.

**Comment by brandonkelly** [comment]
Sorry for the misunderstanding. Just released Craft 3.7.1 with a fix for this. Thanks for reporting!
