### ISSUE TITLE
Tabs duplicating when toggling entry type in 3.7

### ISSUE THREAD

**Issue by jamesedmonston** [craftcms/cms#9562]
### Description

As you can see below, the tab bar is duplicating when switching between different entry types as of Craft 3.7.

![Screenshot 2021-07-14 at 14 05 54](https://user-images.githubusercontent.com/4851924/125627254-6cc3fa8a-3caf-4377-9b35-91a6eb46c847.png)

https://user-images.githubusercontent.com/4851924/125627300-0630e054-b244-471a-9560-214c7239686d.mov

### Steps to reproduce

1. Create a section with multiple entry types
2. Switch between entry types

### Additional info

- Craft version: 3.7.0
- PHP version: 7.4.20
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

1. Control Panel JS	2.3.0
2. Control Panel Nav	3.0.17
3. DigitalOcean Spaces Volume	1.1.3
4. Easy Search	1.0.2
5. Field Manager	2.2.4
6. Formie	1.4.9
7. GraphQL Authentication	1.10.3
8. Inventory	2.1.1
9. Jason	2.0.1
10. Maps	3.9.1
11. Notes	1.0.5
12. Redactor	2.8.7
13. Searchit	1.0.8
14. Super Table	2.6.8

Cheers!

**Comment by brandonkelly** [comment]
Just released 3.7.1 with a fix for this. Thanks for reporting!
