### ISSUE TITLE
Users not able to create drafts

### ISSUE THREAD

**Issue by DarkstarNik** [craftcms/cms#9570]
### Description

Users, who do not have admin access, cannot save pages as drafts outright. They are able to edit and save changes from drafts created by admin users.

### Steps to reproduce

1. Create a user who can edit entries, create entries, edit other author's entries, and edit other author's drafts. The user must not be an admin.
2. With an already created page and the page set to the Current version, make a change on the page and click the orange Create A Draft button.
3. The page will refresh with no Draft made but a warning under the Current version will say there is unsaved changes.

### Additional info

- Craft version: 3.7.0
- PHP version: 7.4
- Database driver & version: Mysql 8.0.23
- Plugins & versions: 
Control Panel CSS - 2.3.0 
ImageOptimize - 1.6.35 
Patrol - 3.1.3 
Redactor - 2.8.7 
Redirect Manager - 1.1.1 
Sprout Active - 2.2.0 
Super Table - 2.6.8

**Comment by brandonkelly** [comment]
Just released Craft 3.7.1 with a fix for this. Thanks for reporting!
