### ISSUE TITLE
Project Config doesn't update `schemaVersion` for disabled plugins

### ISSUE THREAD

**Issue by mattgrayisok** [craftcms/cms#9576]
### Description

When a **disabled** plugin is updated via `composer update` Craft doesn't update the project config with any new `schemaVersion` but it **does** check that it matches when subsequently running a project config apply. This causes the PC apply to fail with:

```
can't apply existing project config: [PLUGIN] is installed at the wrong schema version
```

The fix is pretty straight forward, either:

- Delete the plugin locally and try deploying again, or
- Enable the plugin locally, rebuild PC, disable the plugin again

but this caught me off guard during a deployment and took a few mins to figure out.

### Steps to reproduce

1. Install a plugin locally, enable it, make sure PC has updated
2. Deploy 
3. Disable plugin locally
4. Deploy 
5. Update plugin to a new schema version locally (composer.lock is updated, PC files aren't updated)
6. Deploy
7. Project config apply fails due to the mismatched schema version

### Additional info

- Craft version: 3.6.17
- PHP version: 7.4

**Comment by brandonkelly** [comment]
Disabled plugins are basically treated as uninstalled. We assume they were disabled for a reason – maybe because they were causing errors or something – so it would be risky to re-enable them even for a short time. No plugin code should ever be executed while it’s disabled.

So I’m not really sure how this could be improved, besides maybe a note that you shouldn’t be disabling plugins on a per-environment basis (which should only be possible with the `disabledPlugins` config setting anyway).

**Comment by brandonkelly** [comment]
Added a warning to the [disabledPlugins](https://craftcms.com/docs/3.x/config/config-settings.html#disabledplugins) config setting docs.

**Comment by mattgrayisok** [comment]
Small crossed wire I think - the plugin was disabled on both environments, but the PC sync was rejected due to the version mismatch even though the plugin was disabled.

I've just attempted to recreate and didn't experience the same symptoms so perhaps something weird going on on my side. If I manage to find a reproducible test case I'll reopen. Thanks for having a look!

**Comment by brandonkelly** [comment]
Hm yeah that _shouldn’t_ be possible, since plugin schema versions are only enabled in the project config _after_ their migrations are run, and migrations are only run for enabled plugins.
