### ISSUE TITLE
"Save as new entry" only available if user has publish rights

### ISSUE THREAD

**Issue by nickdunn** [craftcms/cms#9577]
### Description
I have some users who don't have "Publish live change" access in a section.

For these users the "Save as new entry" option isn't available in a dropdown, so they are unable to duplicate entries. I've had to tick "publish to live" so they can see the option.

This feels like a bug — users should be able to duplicate (save as new) without having "publish to live" access.

<img width="246" alt="Screenshot 2021-07-15 at 11 54 07" src="https://user-images.githubusercontent.com/39560/125777050-b6f56001-d26c-4be8-842b-4e831498f423.png">

<img width="251" alt="Screenshot 2021-07-15 at 11 56 26" src="https://user-images.githubusercontent.com/39560/125777110-daa6fb76-8371-43e8-ac94-7433af8ca92e.png">

### Additional info

- Craft version: 3.7.0
- PHP version: 8.0.2

**Comment by brandonkelly** [comment]
Agree, any user with “Create” permissions should be able to duplicate an entry into a new unpublished draft. Unfortunately this could result in a breaking change for some plugins, so will need to make the change in 4.0.

**Comment by MoritzLost** [comment]
@brandonkelly This was originally on the list for 4.0, but it has been removed from the 4.0 milestone. Was this feature more difficult to implement than anticipated, or is there a reason it was delayed? Is there a new ETA for this change?

This is still a pain-point for one of my clients. See the related discussion for details: #10244

**Comment by MoritzLost** [comment]
@brandonkelly That's too bad, but thanks for the info! This definitely has my vote for a highly anticipated feature 🙃

**Comment by brandonkelly** [comment]
We just got to this for Craft 5 (#12303) 🎉  Going forward, any user with the “Create entry” permission will have the option to “Save as a new entry” for any entry they have permission to view, and the newly-created entry will start off in an unpublished draft state rather than a fully-saved entry.

**Comment by anchovy** [comment]
We've had issues with this as well on v4 - a user saved an entry as a new entry and then mistakenly updated and modified the original entry rather than the 'new' entry which caused a lot of issues.

Is there anything on the EVENT_BEFORE_SAVE (or any other events) hook that indicates that the 'new' entry is being generated by clicking on Save > 'Save as a new entry' or 'Duplicating' (from the list view)?
![image](https://github.com/user-attachments/assets/99f504ce-c367-46d4-bfb9-d60b99d1bf26)

**Comment by brandonkelly** [comment]
@anchovy That action triggers the `elements/duplicate` controller action, so you could check for that:

```php
if (
    Craft::$app->request->isCpRequest &&
    Craft::$app->request->actionSegments === ['elements', 'duplicate']
) { 
    // ... 
}
```
