### ISSUE TITLE
New asset index deeplinks throw a 404 template not found if asset subfolder name contains dashes

### ISSUE THREAD

**Issue by rocknrolaf** [craftcms/cms#9579]
### Description

If subfolders created within the assets contain dashes, the new deeplink route causes a 404 template not found error

### Steps to reproduce

1. Create a new subfolder in an assets via right click on the main directory (E.g. "My-Subfolder")
2. Reload/open the browser with the new url path including the subfolder

### Additional info

- Craft version: 3.7.1
- PHP version: 7.4.21
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
Craft 3.7.2 is out now with a fix for this. Thanks for reporting!
