### ISSUE TITLE
Alert when uploading file is not displaying correct limit

### ISSUE THREAD

**Issue by kevinmu17** [craftcms/cms#9580]
### Description
my upload_max_filesize = 512M

When trying to upload a file of 600+MB the alart says:
The file “FILE.zip” could not be uploaded, because it exceeds the maximum upload size of 16.0 MB.

### Steps to reproduce
1. Upload something in an asset folder

### Additional info
- Craft version: Craft Pro 3.6.17
- PHP version: 7.4.16
- Database driver & version: MySQL 5.7.33
- Plugins & versions: N/A

**Comment by angrybrad** [comment]
You'll also need to increase Craft's https://craftcms.com/docs/3.x/config/config-settings.html#maxuploadfilesize as well as potentially this in php.ini: https://www.php.net/manual/en/ini.core.php#ini.post-max-size
