### ISSUE TITLE
Email template parse error

### ISSUE THREAD

**Issue by shwaze** [craftcms/cms#9582]
Getting failed jobs in Queue manager with error message:
"Email template parse error for email “Order Confirmation”. Order: “cf69b14”. Template error: “An exception has been thrown during the rendering of a template ("session_set_cookie_params(): Cannot change session cookie parameters when headers already sent").” /var/www/mecca.coffee/templates/_emails/order-confirmation.twig:18"

### Additional info

- Craft version: Craft Pro 3.5.16
- PHP version: 7.4.12
- Database driver & version: MySQL 5.7.32
- Craft Commerce: 3.2.12

**Comment by brandonkelly** [comment]
Hi, can you please write into support@craftcms.com with the following?

- A database backup
- Your `composer.json` and `composer.lock` files
- Your `templates/` folder

**Comment by olivierbon** [comment]
Helping in support.
