### ISSUE TITLE
Clicking on asset to view details causes refresh of asset listing

### ISSUE THREAD

**Issue by bliswebagency** [craftcms/cms#9583]
### Description

After updating to Craft 3.7.2 while in assets listing. When trying to click on asset to view the details, it will cause the listing page to refresh. This happens to all the files except for the first asset at the top of the listing.

### Steps to reproduce

1. Load assets listing
2. Click on second item in list
3. Instead of loading Asset details, listing page reloads

### Additional info

- Craft version: 3.7.2
- PHP version: 7.4.21
- Database driver & version: MySQL 5.7.33
- Plugins & versions:

Azure Blob Storage 1.0.1
Breadcrumb 1.1.0  
Communicator 1.0.2
Embedded Assets 2.7.0
Pitch 1.1.0
Redactor 2.8.7
Retcon 2.2.3
Super Table 2.6.8

**Comment by vnali** [comment]
it happens for me for first asset on the list too. clicking on the title of all assets causes redirect to '/admin/assets/{volume handle}/'

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 3.7.3 is out now with a fix for it.

**Comment by bliswebagency** [comment]
Thank you for the prompt fix 👍
