### ISSUE TITLE
Draft change highlight bar overlapping with previous field

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#9585]
### Description

Starting with Craft 3.7, changed fields in drafts are highlighted with a light-blue border to the left of the field. But if you have multiple fields in one row, the highlight bar overlaps with the field to the left of it:

![highlight-bar-overlap](https://user-images.githubusercontent.com/10146880/125928698-caef866a-15c1-465d-8155-2bb240267598.png)

![highlight-bar-overlap-2](https://user-images.githubusercontent.com/10146880/125928706-d53da07e-05f6-4c9d-9c25-71dad318d352.png)

### Steps to reproduce

1. Create a new entry using any entry type that has multiple fields next to each other in the field layout.
2. Create a draft, change some field values and save.

### Additional info

- Craft version: 3.7.2
- PHP version: 8.0

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 3.7.3 is out now with a fix for it.
