### ISSUE TITLE
Field Type Number allows you to enter letters

### ISSUE THREAD

**Issue by MattWilcox** [craftcms/cms#9586]
### Description

With a field type set to Number, I'd exect an HTML input element of type Number in the CMS, so only numbers are allowed, and so there's the browser native UI for increasing and decreasing numbers.

Doesn't seem that happens, and you're able to type letters into number fields, which does not give any error except when trying to save - and even then it's not an error on the field itself (see screenshot)

<img width="376" alt="Screenshot 2021-07-16 at 16 07 30" src="https://user-images.githubusercontent.com/814039/125969960-a62e7e7a-c490-42ce-b672-0483d928ae48.png">

When you DO try to save the Entry with a leter in the Number field, it "saves" and takes you back to the Entry Listing page, but when you go in, it'll have reverted to whatever number had been in there previously.

- Craft version: 3.7.2

**Comment by brandonkelly** [comment]
We can’t use `type="number"` because it doesn’t have great localization support, but I’ve just added some key code checks on keypress that restrict the value to numeric characters.
