### ISSUE TITLE
Category with branch limit still visually allowing choice

### ISSUE THREAD

**Issue by gazlawn22** [craftcms/cms#9587]
### Description

Only tested on a category field within a matrix, but category field is limited to 1, however when using the field, you select one category as expected, but the 'Add a category' button is no longer greyed out, and can still be clicked, you can then select another category, though the actual selection is ignored and the original remains.

### Steps to reproduce

1. Create a Matrix with a block containing a category field, set to a branch limit of 1
2. In the editor add a category
3. Expected behaviour is 'Add category' button to no longer be clickable and visibly disabled but allows selection.

### Additional info

- Craft version: Pro 3.7.2
- PHP version: 7.4.2

**Comment by brandonkelly** [comment]
This was reported by #2423 – see the discussion over there.
