### ISSUE TITLE
Undo behavior inconsistent on Plain Text fields with "Allow line breaks" enabled

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#9588]
### Description
`CMD + Z` (Undo) only undoes one character at a time in Plain Text fields with the "Allow line breaks" option enabled.

This differs from other fields (even single line Plain Text) in that others will undo bulk selections of recently typed text.

### Additional info

- Craft version: 3.7.1 (also seen in 3.6.17, so not new)
- PHP version: 7.3.26

**Comment by brandonkelly** [comment]
I’m not able to reproduce this, and Craft doesn’t get involved at all in <kbd>Command</kbd> <kbd>Z</kbd> behavior. It’s left up to the browser/OS to worry about how to handle that.
