### ISSUE TITLE
Focus states (blue outlines) in CP can feel broken in places

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#9590]
### Description

Here's an instance where this occurs on a table field:

![Screen Shot 2021-07-16 at 11 38 08 AM](https://user-images.githubusercontent.com/1007191/125995880-7a18f3fb-23d7-4011-b2e8-759d20efe266.png)

There may be some other instances where outlines don't render well, or are otherwise too aggressive when "Always show focus rings" is disabled.

### Additional info

- Craft version: 3.7.1

**Comment by brandonkelly** [comment]
Hey @jsunsawyer, just released 3.7.3.1 with a fix for this. Thanks for the report!
