### ISSUE TITLE
Inconsistent results with `Element->isFieldDirty`

### ISSUE THREAD

**Issue by chrismlusk** [craftcms/cms#9591]
### Description

I'm getting inconsistent results for when a field is marked as dirty.

I have a custom behavior on entries in a specific section that has some logic to re-save related entries if that particular field is dirty. Example:

```php
if ($this->owner->isFieldDirty('relatedEntries')) {
  $relatedEntries = $this->owner->getFieldValue('relatedEntries')->all();
  foreach ($relatedEntries as $entry) {
    Craft::$app->getElements()->saveElement($entry);
  }
}
```
I can open an entry in the CP and click save without touching anything else (so the `relatedEntries` field is unchanged), and the related entries are not re-saved. This is expected. But when I run `./craft resave/entries --element-id=123`, the related entries are re-saved — each related entry's updated date is changed. If I comment out the above code and run this console command for another entry, its related entries are not re-saved. So the `isFieldDirty` check seems to be the culprit.

This also happens when processing a FeedMe feed. (This is the primary way entries in this section with the custom behavior are updated.) The `relatedEntries` field is not mapped in this feed, so when these entries are updated when running a feed, I would expect the `relatedEntries` field to not be marked as dirty.

### Additional info

- Craft version: 3.6.17
- PHP version: 7.4.16
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
> But when I run `./craft resave/entries --element-id=123`, the related entries are re-saved — each related entry's updated date is changed. If I comment out the above code and run this console command for another entry, its related entries are not re-saved. So the `isFieldDirty` check seems to be the culprit.

This is working as expected. Entries will consider all fields to be dirty when being resaved via `resave/entries`, as the command is often run to force field values to get re-processed.

https://github.com/craftcms/cms/blob/cb8bf6a101ad87e7b28499c05a0c879f7dc6d9b0/src/base/Element.php#L3344-L3347

> This also happens when processing a FeedMe feed. (This is the primary way entries in this section with the custom behavior are updated.) The `relatedEntries` field is not mapped in this feed, so when these entries are updated when running a feed, I would expect the `relatedEntries` field to not be marked as dirty.

This is a side effect of the way Feed Me mappings work. Technically all fields are included in the mapping, even if a field isn’t being assigned a new value from the feed.

If this code is triggered from `EVENT_BEFORE_SAVE`, you could fetch the existing entry and compare its value to the new one, rather than relying solely on `isFieldDirty()`:

```php
use craft\elements\Entry;
use craft\helpers\ArrayHelper;
use craft\helpers\ElementHelper;

if (
    $this->owner->id &&
    !ElementHelper::isDraftOrRevision($this->owner) &&
    $this->owner->isFieldDirty('relatedEntries')
) {
    // Don't rely solely on isFieldDirty(). Make sure the relations have actually changed
    $newRelatedEntries = $this->owner->relatedEntries->all();
    $newRelatedIds = ArrayHelper::getColumn($newRelatedEntries, 'id');

    $oldEntry = Entry::find()
        ->id($this->owner->id)
        ->siteId($this->owner->siteId)
        ->status(null)
        ->one();
    $oldRelatedIds = $oldEntry->relatedEntries
        ->status(null)
        ->ids();

    if ($newRelatedIds != $oldRelatedIds) {
        // The relations have changed
        foreach ($newRelatedEntries as $entry) {
            Craft::$app->getElements()->saveElement($entry);
        }
    }
}
```

**Comment by chrismlusk** [comment]
That'll do the trick. Thanks for the explanation and suggestion!
