### ISSUE TITLE
UI elements style errors

### ISSUE THREAD

**Issue by zzseba78** [craftcms/cms#9592]
### Description
There are some style errors on UI elements from updates from 3.7.x
![Captura de Pantalla 2021-07-17 a la(s) 13 36 54](https://user-images.githubusercontent.com/5558563/126043832-6195df38-e5bf-465e-a4e6-bfbffe230ef5.png)

![Captura de Pantalla 2021-07-17 a la(s) 13 40 23](https://user-images.githubusercontent.com/5558563/126043844-c2a89b57-5245-4a2e-9791-e72bfc26fe99.png)

### Additional info
Firefox: 90.0 (64-bit) Not checked other browsers

PHP version | 7.4.2
Darwin 19.6.0
MySQL 5.7.26
Craft 3.7.3

**Comment by brandonkelly** [comment]
Whoops, thanks for pointing that out! Just released 3.7.3.1 with a fix.

**Comment by zzseba78** [comment]
@brandonkelly Amazing! thanks
