### ISSUE TITLE
{{siteUrl}} Links on site being changed

### ISSUE THREAD

**Issue by dbrown199747** [craftcms/cms#9594]
### Description
We are having an issue with one of our sites, and every now and then we are finding that the links on our site are being changed to a subdomain link. We have done security scans on our server etc and nothing has come up, so I wondered if it's anything anyone has experienced with Craft.

We are using {{siteUrl}} to generate all the links on the site, but for some reason, after clicking around sometimes, this gets changed from https://domain.com to https://mail.domain.com for example.

We are completely unsure why it's happening so any help would be appreciated. We have found saving the navigation file via FTP does make all the links go bak to normal again.

Example of this happening: You can see in the bottom left, the link has been changed to a subdomain.

![Screen Shot 2021-07-15 at 13 12 42](https://user-images.githubusercontent.com/83223160/126065813-1a053b75-9e2d-4366-94b5-c8d1526db0b9.png)

### Steps to reproduce

1. It's very hit and miss of when it happens so hard to reproduce. Hopefully the screenshot shows what is happening.

### Additional info

- Craft version: 3.7.0
- PHP version: 7.4.21
- Database driver & version: MySQL 5.7.34
- Plugins & versions:
- Feed Me - 4.3.6
- Freeform - 3.11.9
- Redactor - 2.8.7
- SEOmatic - 2.6.8
- WheelForm - 2.5.8

**Comment by lenvanessen** [comment]
@dbrown199747 what have you set as a baseUrl for the site?
If you use @web, the domain is determined by the webserver. If nginx/apache for whatever reason is misconfigured, you might end-up with the behavior you're describing.

Best thing to do here, is probably to set a value using environment variables. This also removes the risk of poisoning. 
https://craftcms.com/docs/3.x/sites.html#site-url

In your .env file:
`SITE_BASE_URL=https://xxxx.yz`

And under Settings > Site > SiteName in the baseUrl field:
`$SITE_BASE_URL`

**Comment by dbrown199747** [comment]
Hi,

Yes it was set to @web! Thanks for getting back to me on that. I have now changed it to a variable in the .env file like you have described.

Hopefully that will fix the issue :)

Many thanks!

**Comment by brandonkelly** [comment]
Thanks for pitching in @lenvanessen!

Rather than switching to an environment variable, you can keep using `@web` so long as you’re explicitly setting it to an environment variable via the [aliases](https://craftcms.com/docs/3.x/config/config-settings.html) config setting:

```php
'aliases' => [
    '@web' => \craft\helpers\App::env('SITE_BASE_URL'),
],
```
