### ISSUE TITLE
andRelatedTo() doesn't return any results if set to an empty string

### ISSUE THREAD

**Issue by terryupton** [craftcms/cms#9599]
### Description
So I am chaining a few relatedTo parameters together on an element query (for use with Sprig) and where as if you pass in an empty string to the `relatedTo()` parameter, it continues to serve results as though it is not set. However, I am finding that if you pass in empty string to the `andRelatedTo()` parameter, it returns no results at all.

My expectation here is that if either or both of these are set to empty strings '', it just passes over it.

### Steps to reproduce

Here is a simplified version.

```twig
This returns results as normal

  {% set allVehiclesQuery = craft.entries
    .section('vehicles')
    .search(search)
    .with( [
      'vehicleBrand',
      'vehicleModel',
    ])
    .orderBy('Title ASC')
    .limit(null)
    .relatedTo('')) %}
  ``` 
```
This returns results no results (empty)

  {% set allVehiclesQuery = craft.entries
    .section('vehicles')
    .search(search)
    .with( [
      'vehicleBrand',
      'vehicleModel',
    ])
    .orderBy('Title ASC')
    .limit(null)
    .relatedTo('')) 
    .andRelatedTo('') %}
  ``` 

  The actual code I am using:
  ``` twig
    {% set allVehiclesQuery = craft.entries
    .section('vehicles')
    .search(search)
    .with( [
      'vehicleBrand',
      'vehicleModel',
    ])
    .orderBy('Title ASC')
    .limit(null)
    .relatedTo(vehicleBrand)
    .andRelatedTo(vehicleModel) 
  %}
  ```

So if no `vehicleBrand` or `vehicleModel` are set, then I expect it to just returns all vehicles unless there is a current `search` and then filter them. 

### Additional info

- Craft version: Craft Pro 3.6.17
- PHP version: 7.4.13

**Comment by brandonkelly** [comment]
Thanks for reporting! Just released 3.7.4 with a fix.
