### ISSUE TITLE
Losing all content on page - Critical bug

### ISSUE THREAD

**Issue by JordanMed** [craftcms/cms#9601]
### Description
Any time I make an update, add a new block/remove/make an edit, all of my content is deleted from my page. Revisions are also losing all of their content on reverting to an older version. 

### Steps to reproduce

1. Make any change in an entry wait until it auto saves, then manual save.
2. All blocks are now empty. 
3. Revert to older version (ex. revision 18). 
4. Revision 18 is now empty
5. Content from Revision 18 is now placed into current version and my page is back. 

### Additional info

- Craft version: 3.7.3.2
- PHP version: 7.4.15
- Database driver & version: MySQL 5.7.12
- Plugins & versions: Neo 2.11.1

**Comment by brandonkelly** [comment]
Guessing from https://github.com/spicywebau/craft-neo/issues/480 that this is happening specifically with Neo fields.

Are you able to reproduce with a Matrix field?

**Comment by JordanMed** [comment]
The only matrix Fields I'm using are within Neo's

**Comment by brandonkelly** [comment]
I’m asking you to try reproducing with a Matrix field (standalone; not within a Neo field). You can create one if none exist yet.

**Comment by lenvanessen** [comment]
@brandonkelly Not sure if related, We're experiencing the same issues with a regular Redactor field. I haven't gotten a good set of steps to reproduce from the team, but we've had multiple articles where somewhere in publication content was lost

**Comment by JordanMed** [comment]
The same thing is happening with matrix fields. I've added a couple of redactor matrix fields, saved (they were all there), then added two more and saved. only the new ones stayed.

**Comment by brandonkelly** [comment]
Thanks all! Just released 3.7.4 with a fix for this.
