### ISSUE TITLE
'discard changes' button returns an Http 403 'User is not permitted to perform this action' warning.

### ISSUE THREAD

**Issue by erbertian** [craftcms/cms#9602]
When editing entries, if I click the 'discard changes' button I get an Http 403 'User is not permitted to perform this action' warning. This happens on both my local environment and on a dev server with full admin control panel permissions.

### Additional info

- Craft version: 3.7.3.2 (Pro)
- PHP version: 7.4.3
- OS version: Linux 5.4.0-74-generic
- Database driver & version: MySQL 8.0.25
- Image driver & version: Imagick 3.4.4 (ImageMagick 6.9.10-23)
- Plugins & versions: 
    - Cookies 1.1.15
    - Field Manager 2.2.4
    - oEmbed 1.3.9
    - Reasons 2.2.5
    - Redactor 2.8.7
    - Redactor Custom Styles 3.0.4
    - Relabel 2.0.2
    - SEO 3.7.4
    - Sprig 1.7.0
    - Typed link field 1.0.25
    - Typogrify 1.1.18
    - XML Sitemap 1.3.2

**Comment by brandonkelly** [comment]
What permissions does the user have?

**Comment by erbertian** [comment]
Full admin in the control panel

**Comment by brandonkelly** [comment]
I’m not able to reproduce that. Please send your `composer.json` and `composer.lock` files, plus a database backup, into support@craftcms.com, and we can try to look into it from there.

**Comment by erbertian** [comment]
Sure will do thank you.

**Comment by dgsiegel** [comment]
Got the same issue and can reproduce it. Here's what I currently have:

- the edited page has to be a single
- the user is **not** admin. In my case I've assigned them to a group which has enabled all possible permissions
- edit a field or the title in the page as a draft and click on "revert changes"

It might has to do with this line https://github.com/craftcms/cms/blob/develop/src/controllers/EntryRevisionsController.php#L363, as a user wouldn't be able to delete a single, regardless or their permissions.

Setup is pretty similar, but with Craft 3.7.4 and fewer plugins.

Here's the stack trace:
```
yii\web\ForbiddenHttpException: User is not permitted to perform this action in vendor/craftcms/cms/src/controllers/BaseEntriesController.php:116
Stack trace:
#0 vendor/craftcms/cms/src/controllers/EntryRevisionsController.php(363): craft\controllers\BaseEntriesController->enforceDeleteEntryPermissions()
#1 [internal function]: craft\controllers\EntryRevisionsController->actionDeleteDraft()
#2 vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#3 vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#4 vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#5 vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction()
#6 vendor/craftcms/cms/src/web/Application.php(271): yii\base\Module->runAction()
#7 vendor/craftcms/cms/src/web/Application.php(584): craft\web\Application->runAction()
#8 vendor/craftcms/cms/src/web/Application.php(250): craft\web\Application->_processActionRequest()
#9 vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
#10 htdocs/index.php(22): yii\base\Application->run()
#11 {main}
```

**Comment by brandonkelly** [comment]
Thanks both! Just got this fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.4"` and run `composer update`.

**Comment by erbertian** [comment]
Thanks for the speedy fix Brandon, nice one!
 <https://www.silkpearce.com/>

**Comment by brandonkelly** [comment]
Craft 3.7.5 is out now with that fix.

**Comment by erbertian** [comment]
Thanks for the update Brandon.

Best,
Ian
 <https://www.silkpearce.com/>
