### ISSUE TITLE
Images overflow when looking at a revision

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#9603]
### Description
When viewing a revision, The images overflows the HTML preview.
![Schermafbeelding 2021-07-19 om 17 05 08](https://user-images.githubusercontent.com/23024452/126184288-a6273584-e3e2-467d-98d6-86cb980ab827.png)

### Additional info

- Craft version: 3.7.3.2

**Comment by brandonkelly** [comment]
What type of field is “Body”? Redactor?

**Comment by lenvanessen** [comment]
@brandonkelly yes, redactor

**Comment by brandonkelly** [comment]
Thanks! Just released 3.7.4 with a fix.
