### ISSUE TITLE
Matrix field handle can be saved above `Schema::$maxObjectNameLength` limit

### ISSUE THREAD

**Issue by mattstein** [craftcms/cms#9609]
### Description

It’s possible to save a Matrix field resulting in a 65-character column name even though MySQL’s [limit should be 64](https://dev.mysql.com/doc/refman/8.0/en/identifier-length.html) as reflected by [Schema::$maxObjectNameLength](https://github.com/craftcms/cms/blob/0eff1aadb1110f0f35c92b6d8c86a0740c34a5fc/src/db/mysql/Schema.php#L45-L45). This could presumably result in `craft project-config/apply` failing in other environments, or maybe other weird side effects.

I’m wondering if [this line](https://github.com/craftcms/cms/blob/0eff1aadb1110f0f35c92b6d8c86a0740c34a5fc/src/base/Field.php#L212-L212) is responsible since I’m not sure where `- 9` comes from.

### Steps to reproduce

Start with your favorite MySQL-based project or whip one up with `nitro create`.

1. Create a Matrix field or edit an existing one. (Its handle doesn’t matter.)
2. Create a block type with the handle `testBlockWithLongHandleBecauseTesting`, and add a Plain Text field to that block with a handle of `aLongHandle`. Save the field.
3. Inspect the database’s relevant `matrixcontent_*` table structure and observe a column name similar to `field_testBlockWithLongHandleBecauseTesting_aLongHandle_pptxumnd`, which is 65 characters long.

I can successfully take this project’s YAML and sync it into an identical environment without issue—with [collation](https://craftcms.com/docs/3.x/config/db-settings.html#collation) set to `utf8` or `utf8mb4`—but I’m aware of a situation where someone’s getting an error like this trying to run `project-config/apply`:

> error: SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'field_testBlockWithLongHandleBecauseTesting_aLongHandle_pptxumnd' is too long

I also noticed a related UI bug when the block type handle is much longer. Changing it to `testBlockWithLongHandleBecauseTestingAndTestingIsImportant`, for example, displays the following validation error on the block _field’s_ handle input:

<img width="1004" alt="Screen Shot 2021-07-19 at 05 02 03 PM@2x" src="https://user-images.githubusercontent.com/2488775/126233333-c1bda982-6206-4983-b347-338cb927e837.png">

### Additional info

- Craft version: 3.7.3.2
- PHP version: 8.0.3
- Database driver & version: MySQL 8.0.24

**Comment by brandonkelly** [comment]
> I’m wondering if [this line](https://github.com/craftcms/cms/blob/0eff1aadb1110f0f35c92b6d8c86a0740c34a5fc/src/base/Field.php#L212-L212) is responsible since I’m not sure where `- 9` comes from.

That comes from f86ac030c5526f65b503c76bafb2e161f90fb216, which is when field column suffixes were added, which take up 9 characters. Tested locally and the logic there is working as expected. So it’s not clear how a longer handle could have gotten through.

**Comment by angrybrad** [comment]
@brandonkelly my guess is it's because Matrix field validation is separate from field validation and isn't taking into account the extra `_` between the block handle and field handle.

**Comment by brandonkelly** [comment]
I tested saving the “Contact Methods” Matrix field in Happy Lager. Fields within the `contactMethod` block type had `$maxHandleLength` set to 35, as expected (`64 - 20 - 9`, where `20` is the string length of `field_contactMethod_`).

**Comment by angrybrad** [comment]
@mattstein 

> Inspect the database’s relevant matrixcontent_* table structure and observe a column name similar to field_testBlockWithLongHandleBecauseTesting_aLongHandle_pptxumnd, which is 65 characters long.

`field_testBlockWithLongHandleBecauseTesting_aLongHandle_pptxumnd` is 64 characters long by my math.

There is a UI bug where the math is off for fields that do generate a column name that is over 64 characters long, though.

![CleanShot 2021-07-20 at 11 22 27](https://user-images.githubusercontent.com/61869/126375861-bd19e527-52e4-44af-b7e2-4994c64ec4e8.png)

That's on a fresh install with a block handle of `testblockwithlonghandlebecausetestingaaaaaaaaaa` and a plain text field with a handle of `alonghandle`.

**Comment by mattstein** [comment]
> `field_testBlockWithLongHandleBecauseTesting_aLongHandle_pptxumnd` is 64 characters long by my math.

Oh no, you’re right and I can’t count. Good thing this isn’t public. 🤦 

I’ll close this and file a separate issue for the UI bug—sorry!
