### ISSUE TITLE
Allow twig in field instructions

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#961]
> Created by: James Coleman (james@supercooldesign.co.uk) on 2015/03/11 12:10:02 +0000
> Votes at time of UserVoice import: 7

-----------------------------------

Would allow you to conditionalize instructions per field layout, add links to further information, js pop-outs etc.

**Comment by narration-sd** [comment]
whoom!  :)

**Comment by brandonkelly** [comment]
hah, the FR is too broad to be taken seriously.
