### ISSUE TITLE
Edit entry views scroll to top of page after editing an image via slideout editor

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#9612]
### Description
When using quick edit for assets on an entry, you can edit asset fields and keep your position on the edit view.

If you go one step further and edit the actual asset via slideout -> edit, then canceling or saving from the edit asset view closes the slideout and returns you to the top of the entry, losing your scroll position. This is especially frustrating when working with lots of content/fields, as it can be difficult to find where you left off.

### Steps to reproduce

1. Edit an entry with a large amount of content
2. Find an image that requires scrolling down in the editor
3. Double click image to open slideout
4. Click "Edit" on asset
5. Close or save asset
6. Notice scroll position

### Additional info

- Craft version: 3.7.4

**Comment by andris-sevcenko** [comment]
Fixed that for the next release. Thanks for reporting!

**Comment by brandonkelly** [comment]
Craft 3.7.5 is out now with that fix.
