### ISSUE TITLE
Warning "Recent changes to the Current revision have been merged into this draft." inconsistent

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#9615]
### Description

When changes to the current version are automatically merged into a draft (ouch), there is a warning

![image](https://user-images.githubusercontent.com/60010597/126503809-421585da-26cb-4ad3-b47b-17885f6f78e9.png)

However if such changes are merged into a provisional draft, the warning is not shown.

### Steps to reproduce

See above

### Additional info

- Craft version: 3.7.4
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.5 is out now with that fix.
