### ISSUE TITLE
RTL sites' text fields are set to LTR if current user's preference is LTR

### ISSUE THREAD

**Issue by proimage** [craftcms/cms#9616]
### Description
https://github.com/craftcms/cms/issues/20 LIVES! 😕

I'm working on an RTL (Hebrew) site. I have the backend set to render in English for my user. When I do so, text fields don't render in RTL (which they should due to their content being RTL), but instead render in LTR. If I switch my user preference to an RTL language, the text fields properly render in RTL.

I would expect that content directionality would obey the language direction of the current site, regardless of the interface language.

Site is set to Hebrew:
![image](https://user-images.githubusercontent.com/1027523/126544512-7d0104b8-9725-45da-984c-ea52bfb2b4c2.png)

User settings set to show backend in English:
![image](https://user-images.githubusercontent.com/1027523/126544364-18f1460f-6325-4059-ad63-da84169a56e9.png)

Textual content has incorrect direction assigned:
1. The text field with left-aligned Hebrew content
2. The text field element in dev tools (notably, inside a `div.input.ltr`)
3. Styles filtered by the (partial) `direc` keyword
4. The `direction` CSS property showing an inherited `ltr` value.
![image](https://user-images.githubusercontent.com/1027523/126545029-67e6d650-535a-4336-a706-816b59642790.png)

### Steps to reproduce

1. Create a site where the language is an RTL language such as Hebrew or Arabic.
2. Set your user preference to render the backend in English (or presumably any other LTR language you prefer).
3. Create a plain text field, assign it to a section, and create an entry in that section.
4. Paste in some RTL content into the text field, and note that it aligns to the left.

### Additional info

- Craft version: 3.7.4
- PHP version: 7.4.16
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
  - Asset Rev	6.0.2
  - Cookies	1.1.15
  - Craft Color Mixer	1.0.9
  - Maps	3.9.1
  - Neo	2.11.1
  - Typed link field	1.0.25

**Comment by brandonkelly** [comment]
Just tested locally and this is actually working as expected.

The current logic is:

- If a field **IS** marked as translatable, use the _current site’s language’s_ orientation.
- If a field **IS NOT** marked as translatable, use the _user’s preferred language’s_ orientation.

So to get the field to respect the site’s language’s orientation, you will need to mark it as translatable.

The only issue is, you don’t have the option to mark a field as translatable for single-site installs. So I’ve just tweaked this for the next release: going forward, for single-site installs, the primary site’s language’s orientation will always be used.

**Comment by brandonkelly** [comment]
Craft 3.7.5 is out now with that change.

**Comment by proimage** [comment]
Ahh, interesting! Thanks for that fix, BK.

I suspect it would make sense to have the ability to override the directionality/language of specific fields to something other than the site language. For example, even in an RTL site, with an RTL user preference, text fields for computer code (for display or for embedding) should 99.99% of the time be LTR. Should I make a new issue about that?

**Comment by brandonkelly** [comment]
@proimage Ah good point. Sure, create a new issue for that.

**Comment by proimage** [comment]
@brandonkelly Done: https://github.com/craftcms/cms/discussions/9639
