### ISSUE TITLE
Field Layout Designer let you see the field handle, not just the uppercased name

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#962]
> Created by: Marion Newlevant (marion.newlevant@gmail.com) on 2015/03/10 22:04:02 +0000
> Votes at time of UserVoice import: 7

-----------------------------------

I have multiple fields with the same name but different handles, and picking the right one in the field layout designer is a challenge.

**Comment by brandonkelly** [comment]
Not quite the same, but as of 2.6.3006, field handles are now shown as tooltips when you hover over field names in Field Layout Designers. (And field names are no longer all-uppercased.)

**Comment by brandonkelly** [comment]
Craft 3.5 has a new field layout designer, which shows the field handles.
