### ISSUE TITLE
[3.7] Image Transforms dont regenerate on transform edit menu save.

### ISSUE THREAD

**Issue by cherrykoda** [craftcms/cms#9620]
### Description

When editing an image transform, images are not regenerating. When a project config is applied that changes the image transform settings, images do not regenerate.

### Steps to reproduce

1. Create and implement the use of an image transform for a basic craft image field output.
2. Edit the settings for the transform (height, width) and save
3. Reload the page where images are in use

### Additional info

We did all cache purging, asset re-indexing, resaving entries actions available. There is no caching on our site. The only thing that worked to retrigger the asset update was to go to each entry, remove the image, save the entry. Then go back in and re-select the images. Replacing the asset with the same file also worked.

- Craft version: 3.7.3.2
- PHP version: 7.4
- Database driver & version: MySQL
- Plugins & versions: N/A

**Comment by cherrykoda** [comment]
edit: Fully replacing the image seems to be the only trigger for transform rebuild.

**Comment by andris-sevcenko** [comment]
I'm unable to reproduce this and this should not be happening. The most likely scenario (if using a local volume) is that the webserver is sending the files back with a cache header or something else in-between is caching this.

One thing you can definitely do is enable the [revAssetUrls setting](https://craftcms.com/docs/3.x/config/config-settings.html#revasseturls).

Let me know how that goes!

**Comment by cherrykoda** [comment]
Im using a CDN (Digital Ocean Spaces) using Vaersagod’s spaces plugin. 

I’ll give the rev setting a try and report back!

**Comment by cherrykoda** [comment]
Using rev assets fixed the issue. Thanks!
