### ISSUE TITLE
Login path and `X-Robots-Tag: none`

### ISSUE THREAD

**Issue by iainsaxon** [craftcms/cms#9621]
### Description

We recently found that our index page was un-indexable by crawlers after updating from Craft 3.6.7 to Craft 3.6.18.

After stepping through the code we found that the change causing the unexpected behaviour was the added `$request->getIsActionRequest()` when checking for action requests.
See: https://github.com/craftcms/cms/blob/3.6/src/web/Application.php#L167

The home page acts as the login screen for a members-only site so when the `_checkRequestType()` method performs the URL matching for special paths the home page is considered as an action request.
See: https://github.com/craftcms/cms/blob/00020398b2a7c9b080c6cafd844ad76557f8a2ef/src/web/Request.php#L1622

Is there a reason the login path has this `X-Robots-Tag` header set?

### Steps to reproduce

1. Set `loginPath` under General Configuration file to `/`
2. Check response headers of site root and the `X-Robots-Tag: none` will be added
3. Set `loginPath` under General Configuration file to `/account/login`
4. Check response headers of site root and the `X-Robots-Tag: none` will not be added

### Additional info

- Craft version: 3.6.18
- PHP version: 7.4.18
- Database driver & version: 10.5.9-MariaDB Homebrew
- Plugins & versions: NA

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.5"` and run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.7.5 is out now with that fix.
