### ISSUE TITLE
Getting unknown property error after deleting/recreating section

### ISSUE THREAD

**Issue by jwrudzin** [craftcms/cms#9623]
### Description

Deleting a section (and subsequently deleting all of the fields that were attached to that section), then recreating the section using the same name and handle results in a `Getting unknown property` error when trying to save an entry in the newly created section.

This seems to be related specifically to assets fields. When I delete the section then delete a text field that was attached to that section, I can still properly save an entry after recreating the section. However, once I delete an assets field that was attached to the deleted section, I can no longer save a new entry and I get the aforementioned error.

Changing the handle of the newly created section makes the error go away.

### Steps to reproduce

1. Create a section.
2. Create an assets field and add it to the newly created section's default entry type.
3. Delete the section.
4. Delete the assets field.
5. Create another new section using the same section name and handle used in step 1.
6. Attempt to create and save an entry to the new section.
7. This results in an error `Getting unknown property: craft\elements\Entry::assetFieldHandle`

### Additional info

- Craft version: 3.7.4
- PHP version: 7.4.4
- Database driver & version: MariaDB 10.4.12

![Screenshot of error](https://user-images.githubusercontent.com/18213990/126656077-75d295fc-c77d-4a71-bf39-c571af3be9c3.jpg)
[Full error info](https://github.com/craftcms/cms/files/6862924/fullError.txt)

**Comment by brandonkelly** [comment]
Looks like the error is coming from the Imager X plugin.

**Comment by jwrudzin** [comment]
@brandonkelly Ah yep, sorry I missed that. Thanks for pointing me in the right direction here!
