### ISSUE TITLE
Default views for Singles show Author columns by default

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#9627]
### Description
I feel like this was never the case before, but entry view columns now seem to include Author by default, even though singles don't have authors.

Here's a screenshot from the Spoke and Chain demo showing the Author column there as well.

![Screen Shot 2021-07-22 at 3 11 17 PM](https://user-images.githubusercontent.com/1007191/126716293-64d48213-f73b-472c-8da9-0addf34abe5e.png)

P.S. Sorry if this isn't technically a bug, but I'm still a bit confused on the whole issues vs discussions aspect of things. Just felt like this was an unintentional change, not an enhancement request.

### Additional info

- Craft version: 3.7.4

**Comment by brandonkelly** [comment]
Doesn’t seem to have ever been any different, but agree it’s a bug since singles don’t have authors. Fixed for the next release.

**Comment by jsunsawyer** [comment]
Ah, cool. I must've just been hiding it without ever giving it a 2nd thought. Thanks!

**Comment by brandonkelly** [comment]
Craft 3.7.5 is out now with that fix.
