### ISSUE TITLE
On Firefox, entry edit page header stays fixed to top after opening/closing preview

### ISSUE THREAD

**Issue by ttempleton** [craftcms/cms#9630]
### Description

Very small issue, but on Firefox (seems to be fine on Safari and Chrome), when editing an entry and scrolling down so the page header is fixed to the top of the window, after opening and closing the entry preview, the header remains fixed despite the page having auto-scrolled back to the top, making it cover the global header.  Any scroll down will then return everything back to normal.

### Steps to reproduce

1. Edit an entry in Firefox
2. Scroll down until the header is fixed to the top
3. Click the 'Preview' button
4. Click the 'Close Preview' button

### Additional info

- Craft version: 3.7.4
- PHP version: 8.0.8
- Database driver & version: PostgreSQL 13.3
- Plugins & versions: none
- Firefox version: 90.0.2

**Comment by brandonkelly** [comment]
Thanks for reporting that! Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.5 is out now with that fix.
