### ISSUE TITLE
Allow uploading files that contain an "-" as base64

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#9632]
### Description
I would like to upload an asset as base64 with 
```
data:application/octet-stream;base64,xxxxxxxx
```
But the [Assets ](https://github.com/craftcms/cms/blob/3.4/src/fields/Assets.php#L675) field has a regex with 
```PHP
preg_match('/^data:(?<type>[a-z0-9]+\/[a-z0-9\+]+);base64,(?<data>.+)/i', $dataString, $matches)
```
due to the `-` in `octet-stream` it is not recognized.
Adding a last `-` into the 2nd block will fix the issue
```PHP
preg_match('/^data:(?<type>[a-z0-9]+\/[a-z0-9\+-]+);base64,(?<data>.+)/i', $dataString, $matches)
```

### Steps to reproduce

1. Search for an Asset with type `octet-stream` as base64 
2. try to upload it via the code below

```PHP
$entry = new Entry();
// insert a valid section and type with an Assets field
$entry->sectionid = 1;
$entry->typeId= 1;

// insert a valid datastring here...
$dataString = 'data:application/octet-stream;base64,xxxxxxxx';
$fileName = 'some-filename.png';
$entry->setFieldValue('assetFieldHandle', [
    'data' => [$dataString],
    'filename' => [$fileName]
]);

Craft::$app->getElements()->saveElement($entry);
```

### Additional info

- Craft version: 3.4.13 and larger

**Comment by brandonkelly** [comment]
Thanks for pointing that out. Just released Craft 3.7.5 with a fix for that.
