### ISSUE TITLE
Assets can't be moved between folders

### ISSUE THREAD

**Issue by RyanRoberts** [craftcms/cms#9633]
### Description
Assets dragged and dropped between folders aren't moved to the destination folder.

### Steps to reproduce

Video of it: https://media.yep.digital/pDYeDY

### Additional info

- Craft version: 3.7.4
- PHP version: 7.4.21 and 8
- Database driver & version: MySQL 5.7.34
- Plugins & versions: n/a

**Comment by aelvan** [comment]
Seeing the same thing. Tested both local, AWS and DO Spaces volumes.

**Comment by brandonkelly** [comment]
This was the same underlying bug that caused #9619, so it’s also fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.5 is out now with the fix.
