### ISSUE TITLE
Matrix block field handle validation can require negative character limit

### ISSUE THREAD

**Issue by mattstein** [craftcms/cms#9636]
### Description

Adding a Matrix block type with an obscenely long handle can force its field handles to require “at most [negative number] characters.”

<img width="1004" alt="long-handle" src="https://user-images.githubusercontent.com/2488775/126834227-3e4744c1-1c53-459f-a9e4-cd62aa7ccdbe.png">

Clearly this is due to a limited [Schema::$maxObjectNameLength](https://github.com/craftcms/cms/blob/0eff1aadb1110f0f35c92b6d8c86a0740c34a5fc/src/db/mysql/Schema.php#L45-L45) and block handle not leaving sufficient room for field handles.

A limit of `-10` characters is impossible to satisfy, but I’m not sure what behavior I would expect since the field handle’s length is limited by the block type handle’s length, and it doesn’t make much sense to put an arbitrary limit on the block type handle’s length.

Originally mentioned in [this issue](https://github.com/craftcms/cms/issues/9609).

### Steps to reproduce

Start with your favorite MySQL-based project or whip one up with `nitro create`.

1. Create a Matrix field or edit an existing one.
2. Create a block type with the handle `testBlockWithLongHandleBecauseTestingAndTestingIsImportant`, and add a Plain Text field to that block with a handle of `aLongHandle`. Attempt to save the field.
3. Observe the validation error:
    > Handle should contain at most -10 characters.

### Additional info

- Craft version: 3.7.3.2
- PHP version: 8.0.3
- Database driver & version: MySQL 8.0.24

**Comment by brandonkelly** [comment]
Just released 3.7.5 with a 47-character limit on block type handles. If it’s maxed out, then its sub-fields’ handles will have a max length of one character.
