### ISSUE TITLE
Save drafts not working as expected

### ISSUE THREAD

**Issue by jugsvn** [craftcms/cms#9643]
Steps to reproduce

1. Add an image asset to say Home page.
2. Create a new entry for Home page.
3. Add an asset and this will save the draft automatically.
4. Now delete the added asset and wait for the save-draft to return.
5. Reload the page without saving, the image is still there.

I believe the issue is in findDeltaData method where the groupedOldParams is not saving the updated data after the first save-draft request returns successfully from the server. So when the first save-draft request goes to the server, groupedOldParams is empty as expected and since groupedNewParams is not empty, the parameter name is added to the modifiedDeltaNames parameter. When the second request is prepared, groupedNewParams is empty as the image has been removed but groupedOldParams should have had the value which was sent in the first request. But it's also empty and hence modifiedDeltaNames is not sent in the second request. 

I tested in 3.7.5 Pro version

**Comment by jugsvn** [comment]
More evidence

https://user-images.githubusercontent.com/228429/127160263-96b3a31a-3c94-4558-b92b-404274532e4c.mov

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 3.7.6 is out now with a fix.
