### ISSUE TITLE
Author can be added as a field but not added to a section

### ISSUE THREAD

**Issue by laurabennett** [craftcms/cms#9644]
### Description
"author "is a reserved word. Would be nice if the error was given when trying to add the field rather than when adding the field to the section.

### Steps to reproduce

1. Create field named "Author"
2. Create Section
3. Drag the "Author" field into the field layout of the entry type
4. Attempt to save

### Additional info

- Craft version: 3.7.5

**Comment by brandonkelly** [comment]
Sorry that’s a little confusing. The reason it works this way is because `author` is only a problem for entries, which already have an `author`. There’s no reason you couldn’t add an `author` field to any other element type though, such as assets or categories.
