### ISSUE TITLE
Time fields inside Matrix and created before 3.7 upgrade no longer work correctly in 3.7+

### ISSUE THREAD

**Issue by tomdavies** [craftcms/cms#9650]
### Description

I have a production site with a Matrix field where the blocks contain two required time fields. On Craft 3.6.17 this field works as expected (I can save time values and edit existing ones).

After updating the site to Craft 3.7.0, it is no longer possible to update / save new values for these fields, and the bug still exists as of Craft 3.7.6. Reverting back to 3.6.17 removes the issue.

The issue presents as follows:

When attempting to save an entry with new / updated time values, the save fails. The edited fields are blank and a `<time field name> cannot be blank.`error is shown.

I'm not 100% sure if the fact that the time fields are in a Matrix is relevant or not.

If I create an equivalent field  _after_ upgrading to 3.7.x everything works fine, so it _feels_ like perhaps something is going awry in the migration step.

If you aren't able to reproduce I can provide a SQL dump + repo via private channel

### Steps to reproduce

1. On a Craft 3.6.17 install, create a matrix field with a required time field, and attach to an entry type or similar
2. Update to Craft 3.7.x
3. Attempt to save values in time field matrix

### Additional info

- Craft version: 3.7.6
- PHP version: 7.4.16
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Element API, Redactor

**Comment by brandonkelly** [comment]
@tomdavies Yeah if you could send a database backup plus your Composer files over to support@craftcms.com, we can look into it.

**Comment by tomdavies** [comment]
@brandonkelly 👍. Sent

**Comment by tomdavies** [comment]
Looking at this further as I look to work around it, the field in question is a date field, set to display time only. 

Am going to follow the docs on [Converting from a Date Field](https://craftcms.com/docs/3.x/time-fields.html#converting-from-a-date-field), but I think the issue still remains for date fields set up this way

**Comment by brandonkelly** [comment]
Just released 3.7.7 with a fix for this. Thanks for reporting!
