### ISSUE TITLE
GD and sanitizeCpImageUploads makes image quality bad.

### ISSUE THREAD

**Issue by watarutmnh** [craftcms/cms#9656]
### Description
When I use GD Image driver, uploaded jpg images will be significantly degraded unless I set 'sanitizeCpImageUploads' to false.

![screenshot 2021-07-29 at 18 29 53](https://user-images.githubusercontent.com/6081378/127579945-8d4a2d85-c6db-48fa-aaa2-0972740afcf8.png)

### Steps to reproduce

1. Set 'sanitizeCpImageUploads' => true (it's default value)
2. Upload jpg image from Assets > upload files and check

### Additional info

- Craft version: 3.6.1
- PHP version: 7.4.21
- Database driver & version: MySQL 5.5.5
- Database driver & version: GD 7.4.20

**Comment by angrybrad** [comment]
You can try setting https://craftcms.com/docs/3.x/config/config-settings.html#defaultimagequality to a higher value (100 is the max) and see if that helps.

Alternatively, you can try installing Imagick on the server (if it's not already installed). Craft will use it by default if it sees it's installed and it tends to produce higher-quality output.

The reason the image quality can change is that when an image is uploaded, Craft loads it into memory and saves it back out to disk to strip any potentially malicious embedded code as a security measure.  Setting `sanitizeCpImageUploads` to `false` disables that behavior, which might be OK for your site if you're sure you trust everyone that's uploading images in the control panel.

**Comment by watarutmnh** [comment]
@angrybrad defaultImageQuality: 100 is not solved it but ImageMagick does.
I will disable sanitizeCpImageUploads when difficulty installing ImageMagick on a server.

**Comment by angrybrad** [comment]
@watarutmnh awesome... glad to hear.
