### ISSUE TITLE
File Upload not working - no error

### ISSUE THREAD

**Issue by cstoerzer** [craftcms/cms#9659]
### Description

I set up a new form and use a file upload field - everything gets displayed correctly and I don't get any errors. Entries are not strored in the DB - just notification. Mail is sent, but the field is missing completely. Asset is also not stored in selected volume. So it seems that it is just ignored.

### Additional info

Reload Page

- Craft version:Craft Pro 3.6.17
- PHP version: 7.4.20
- Database driver & version: MySQL 5.7.34
- Plugins & versions: Sprout Forms | 3.13.5 / Sprout redirects 1.5.3

**Comment by brandonkelly** [comment]
What type of form is this? Are you using a plugin for it?

**Comment by cstoerzer** [comment]
omg sorry - wanted to post this in sprout forms plugin and not here
