### ISSUE TITLE
“Discard changes” action redirects to another site

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#9663]
### Description

When we click on the “Discard changes” action changes are discarded but we’re redirected to a different site.

### Steps to reproduce

https://user-images.githubusercontent.com/7516543/127702210-34e7f7cd-08ec-427d-9b88-6b275efb2c49.mov

### Additional info

- Craft version: 3.7.7
- PHP version: 7.3.14
- Database driver & version: MySQL 5.5.5
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.8 is out now with the fix for this.
