### ISSUE TITLE
CraftCMS version 3.7.x unavailable through CDN

### ISSUE THREAD

**Issue by jankohlbach** [craftcms/cms#9670]
### Description
I want to use version 3.7.x of Craft and I fetch the releases from your CDN at: https://download.craftcdn.com/craft/3.x/Craft-3.x.x.zip but currently version 3.7.x is not accessible for me from there.

### Steps to reproduce

1. Attempt to fetch 3.7.x release zip file from CDN at either https://download.craftcdn.com/craft/3.7/Craft-3.7.7.zip
2. Request fails with a 404 error.

I know this is not the most recommended way to get the source files, but downloading the github releases it gives me a different folder structure and it's not installing in the setup I have available.

**Comment by angrybrad** [comment]
@jankohlbach this should be resolved now... thanks!

**Comment by nicolasboschert** [comment]
Hey @angrybrad
currently the version 3.7.43 is not available at https://download.craftcdn.com/craft/3.7/Craft-3.7.43.tar.gz for download.

**Comment by jankohlbach** [comment]
3.7.41 and 3.7.42 are also not available via this method  @brandonkelly

**Comment by angrybrad** [comment]
@nicolasboschert @jankohlbach should be fixed now!

**Comment by angrybrad** [comment]
@nicolasboschert the CDN should have all of the 3.7.x releases now.

**Comment by joshuakeck** [comment]
Hello @angrybrad
the version 3.7.52 is not available at https://download.craftcdn.com/craft/3.7/Craft-3.7.52.tar.gz. The newest version on the CDN is 3.7.51. Can you take a look :)?

**Comment by angrybrad** [comment]
@joshuakeck done

**Comment by nicolasboschert** [comment]
Hello @angrybrad could you publish the newest craft 3 version on the cdn? Thank you.

**Comment by angrybrad** [comment]
@nicolasboschert we’ve discontinued the automatic generation of new releases to download.craftcms.com.

You can generate the exact files that are in the zip by running these commands, though:

Craft 3:

```
composer create-project craftcms/craft=^1 /path/to/dir --no-dev
cd /path/to/dir && composer require craftcms/cms:3.7.46.1 --update-with-dependencies
```

Craft 4:

```
composer create-project craftcms/craft /path/to/dir --no-dev
cd /path/to/dir && composer require craftcms/cms:4.3.7.1 --update-with-dependencies
```

Swapping out the Craft version for the one you specifically want.

It’s on our short-term list to add these releases as official Github releases (https://github.com/craftcms/cms/releases) where we’ll probably do something similar and add a zip as a release artifact.
