### ISSUE TITLE
"Save and add another" doesn't remember the selected parent for Categories

### ISSUE THREAD

**Issue by jamiewade** [craftcms/cms#9677]
### Description
When creating a new Entry, if you select a parent then click "Save and add another", Craft will remember which parent Entry you have selected when it creates the new Entry.

This doesn't apply for Categories. I have to keep selecting the parent again each time. 

### Additional info

- Craft version: Craft CMS 3.7.7
- PHP version: 7.3.28
- Database driver & version: MySQL 5.7.12

**Comment by brandonkelly** [comment]
I noticed this a couple days ago as well, and it’s already fixed for the next release :) 117e83703948a1488fdce341da937d9974985dbc

**Comment by jamiewade** [comment]
Thanks Brandon 🍻

**Comment by brandonkelly** [comment]
Craft 3.7.8 is out now with the fix for this.
