### ISSUE TITLE
Matrix Block Query Doesn't Return Results When Field ID and Search are Used

### ISSUE THREAD

**Issue by cakleimeier** [craftcms/cms#9679]
### Description
I have a site with a Matrix Block field whose ID is **262**. Each Type in this field has a subfield with the handle `menuText`. I'm looking for all Matrix Blocks in that field belonging to the current entry whose `menuText` field is not empty.

I can return results if _either_ the `fieldId` parameter _or_ a search parameter is used in the `matrixBlocks` query. However, I cannot return results if both parameters are used. Additionally, using any kind of search seems to return all the blocks, rather than actually applying that search.

For reference, here's my query. The variable `page` is defined in the loop in which this query exists.
`{% set matchingBlocks = craft.matrixBlocks.owner(page).fieldId(262).menuText('*').all() %}`

Also note that, for the search parameter, I've tried many variations with either all results or no results. Some variations I've tried include:
```
.menuText(':notempty:')
.search('menuText:*')
.search('menuText:notempty:')
.search({query : 'menuText:*'})
```

Finally, I've ensured that the setting "Use this field’s values as search keywords" is **on** for the Matrix field itself _and_ for the `menuText` subfield.

My main concern here is that `fieldId` and `search` don't seem to work together, as I need to specify `fieldId` in order to access the custom field content of the results, according to the [docs](https://craftcms.com/docs/3.x/matrix-blocks.html#example). Without being able to combine these parameters, I won't be able to search for the matching blocks _and_ return the contents of those matches with the same query.

### Steps to reproduce

1. Create a matrix field with several block types, each containing a subfield of the same name
2. In the template, write a matrixBlocks query to search for matches in the subfield, using `fieldId`

### Additional info

- Craft version: 3.7.7
- PHP version: 7.3.7

**Comment by brandonkelly** [comment]
Thanks for reporting that! Not really sure how we’ve made it this far without anyone noticing, but apparently we never added support for `fieldHandle:keyword` search syntax for Matrix block queries.

I’ve just fixed that for the next release. To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop"` and run `composer update`.

**Comment by cakleimeier** [comment]
Thanks for the reply; I'm glad to know I wasn't missing something. :)

**Comment by brandonkelly** [comment]
Craft 3.7.8 is out now with the fix for this.

**Comment by cakleimeier** [comment]
Awesome, thank you!
