### ISSUE TITLE
"Let each entry choose which sites it should be saved to" - does not create entries in all selected sites

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#9680]
### Description

For sections set to "Let each entry choose which sites it should be saved to", content is lost when creating a new entry.

May it depends on the order you are doing things, but this is reproducable for me:

### Steps to reproduce (fresh install)

1. Create two sites: English (primary) /Deutsch
2. Create a section with a propagation method  set to "Let each entry choose which sites it should be saved to"
3. Create a new entry from element index "English"
4. Add a title
5. Add a site "Deutsch"
6. Select site "Deutsch" and update the title - everything looks ok:
![image](https://user-images.githubusercontent.com/60010597/128345600-4125a801-5c4c-4cb5-9f9c-26c187fbdf3c.png)
7. "Create Entry"
8. The entry is only created for "Deutsch"
9. Reopen the entry: 
![image](https://user-images.githubusercontent.com/60010597/128346894-65e8bd6d-520d-40c5-9b55-f07b9a2eee68.png)

### Additional info

- Craft version: 3.7.7
- PHP version: 7.4.16
- Database driver & version:  MySQL 5.7.33
- Plugins & versions: None

**Comment by brandonkelly** [comment]
Thanks for reporting that! This has been fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.8 is out now with the fix for this.
