### ISSUE TITLE
"Save as a new entry" saves changes to the original instead of the new item

### ISSUE THREAD

**Issue by FlorisDerks** [craftcms/cms#9681]
### Description
When changing an entry and saving it using "Save as a new entry" to create a new entry with the changes it seems that the changes are saved to the wrong entry and partially to the new entry, which is unwanted behavior.

The expected result would be to make a copy of the original, save the changed content to the new item and don't save any changes on the original entry. This was the case until our upgrade to 3.7.x.

### Steps to reproduce

1. Create an entry named "Item 1" with at least a matrixfield with a textfield with the text "This is item 1"
2. Click "Create entry"
3. Open the entry again
4. Change "Item 1" to "Item 2" in the title, matrix-textfield and slug
5. Choose "Save as a new entry"
6. You will land in the new "Item 2" but with the old matrixfield-content
7. Go back to the overview and open "Item 1"
8. You will see this will have gotten "Item 2" as a title (even though it's still named "Item 1" in the overview), has the new matrix-content and the new slug, which all should've been changed on the new entry instead of this original.

### Additional info

- Craft version: 3.7.7
- PHP version: 7.4.20
- Database driver & version: 10.5.8-MariaDB
- Plugins & versions: None

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just released Craft 3.7.8 with a fix.
