### ISSUE TITLE
Block Code in field instructions should have scrollbar instead of overflowing

### ISSUE THREAD

**Issue by proimage** [craftcms/cms#9683]
### Description
When I add block code using triple backticks to the instructions of a custom field, it renders using `<pre><code> … </code></pre>`. If there are decently-long lines of code therein, they will overflow the above HTML elements instead of triggering a horizontal scrollbar:

![image](https://user-images.githubusercontent.com/1027523/128369934-b5e1c83f-39b3-4529-829f-16df772ac247.png)

### Steps to reproduce

1. Create a custom field and add a code block to its instructions field with decently-long lines of code.
2. Add the custom field to a section's field layout, perhaps restricting the width to a certain number of columns.
3. Create a new entry in that section.

### Additional info

- Craft version: 3.6.11.1
- PHP version: Irr…
- Database driver & version: …ele…
- Plugins & versions: …vant

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just released Craft 3.7.8 with a fix.
