### ISSUE TITLE
front-end `users/set-password` validation error can cause infinite loop

### ISSUE THREAD

**Issue by mattstein** [craftcms/cms#9684]
### Description

If you copy and paste our [example Reset Password Forms](https://craftcms.com/knowledge-base/front-end-user-accounts#reset-password-forms) verbatim, a validation error for `setpassword.twig` will cause an infinite loop leading to a gateway timeout.

The reset and validation error flow works as expected via the control panel (`/admin/set-password`).

### Steps to reproduce

1. Create `reset-password.twig` and `setpassword.twig` as described [on this page](https://craftcms.com/knowledge-base/front-end-user-accounts#reset-password-forms).
2. Initiate a password reset, then grab the token and visit the URL that uses `/setpassword` from step 1.
3. Enter a single character in the _New Password_ field and press **Submit**.
4. Observe that the site hangs and eventually times out.
5. Remove or comment out `{{ actionInput('users/set-password') }}` from `setpassword.twig` and repeat steps 2-3.
6. Observe that without specifying that action in a form input, the template is rendered with the validation error.

### Additional info

- Craft version: 3.7.7
- PHP version: 7.4.16
- Database driver & version: PostgreSQL 13.1

**Comment by brandonkelly** [comment]
Fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 3.7.8 is out now with the fix for this.
