### ISSUE TITLE
"Download" button on the asset page downloads an HTML version of the page

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#9688]
### Description
Clicking **Download** on an asset page downloads an HTML file of the whole page, not the asset itself.

![image](https://user-images.githubusercontent.com/1250017/128487643-6f9f7786-af8c-44ef-ac4b-7e672910ae7f.png)

Asset page:

![image](https://user-images.githubusercontent.com/1250017/128487672-07a1661e-99df-4287-98e4-a0efaca20952.png)

When I click download, I get this file:

![image](https://user-images.githubusercontent.com/1250017/128487706-46c1c989-699c-4b2c-8959-0ff59636fda4.png)

![image](https://user-images.githubusercontent.com/1250017/128487715-9ba6ebf5-839c-49e0-be63-72ad91083671.png)

### Steps to reproduce

1. Open an asset
2. Click download

### Additional info

- Craft version: 3.7.7
- PHP version: 8.0.8

**Comment by brandonkelly** [comment]
Strange… I’m not able to reproduce that. Can you reach out to support@craftcms.com about it? We might be able to help look into it from there.

**Comment by darylknight** [comment]
Weird; looks like it was only doing it for this one specific file on my local boilerplate. I deleted and re-uploaded a different screenshot and that works fine - sorry!
