### ISSUE TITLE
[3.7.8] Search index not properly populated when creating new entries

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#9699]
### Description

When a new entry is created, the searchindex table is not properly populated.

E.g
![image](https://user-images.githubusercontent.com/60010597/128907320-9b520d5e-5269-4505-839b-14ce582a40f9.png)
only title/slug are present.

After editing the title in one language (not touching anything else) and resaving the entry, it looks ok:
![image](https://user-images.githubusercontent.com/60010597/128907909-c9f7bbb3-7f18-4952-9663-8c7d5fb05a7f.png)

### Steps to reproduce

1. New entry - add some content (2 sites, in case that matters..)
2. Create entry
3. Check search - nothing except title can be found
4. Edit entry - Save
5. Check search again - it works.

### Additional info

- Craft version: 3.7.8
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.9 is out now with the fix. Note that the fix isn’t retroactive though, so you will need to manually update search indexes if it’s important to you, by running the following CLI commands:

```php
> php craft resave/entries --update-search-index
> php craft resave/entries --provisional-drafts --update-search-index
```
