### ISSUE TITLE
No progress bar when replacing a file via the Asset edit page, and image previews are not updated

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#9700]
### Description

When using the "Replace file" action on dedicated Asset edit pages, there is no progress bar displayed while the new file is uploading. The only clue that the file was successfully replaced, is that a "Updating search indexes" job will be triggered, and that the file meta data (file title, file size, image dimensions) is updated. The sidebar image preview is _not_ updated, though (the old image is displayed until the page is refreshed in the browser).

This feels a bit broken, especially compared to the "Replace file" element index action, which displays a progress bar while uploading and refreshes the Asset thumbnail once the file has been successfully replaced.

### Steps to reproduce

1. Visit a dedicated image Asset edit page
2. Replace the file via the "Replace file" button in the top right corner

### Additional info

- Craft version: 3.7.8
- PHP version: 7.4
- Database driver & version:
- Plugins & versions:

**Comment by andris-sevcenko** [comment]
Just pushed a fix for this for the next release!

**Comment by brandonkelly** [comment]
Craft 3.7.9 is out now with the fix.
