### ISSUE TITLE
Unable to edit filenames with weird tokens, results in Corrupted path detected

### ISSUE THREAD

**Issue by MrHesus** [craftcms/cms#9703]
### Description
Some asset filenames contain weird tokens, which result in a `error: Corrupted path detected`. Which makes pages unable to load. 

Running these filenames through regex, confirms the weird tokens. 

The main issue is that we are unable to edit these filenames:

1. Editing by hand results in the same error.
2. Running `./craft utils/ascii-filenames/index` also results in the same error. I think this command is not yet compatible with these changes: https://github.com/thephpleague/flysystem/commit/a3c694de9f7e844b76f9d1b61296ebf6e8d89d74.

### Steps to reproduce

1. Create a asset with this filename: `Stella-Kim​-​winner-Keep-an-Eye-Textile-Fashion-Award-2019.jpg`
See regex: 
![CleanShot 2021-08-11 at 15 33 40](https://user-images.githubusercontent.com/25330441/129038356-ec6596cd-a9c6-4c4f-9ac3-37f75b260e74.png)

2. Try loading in the image / edit the filename by hand / running the command above

### Additional info

- Craft version: Craft Pro 3.7.7
- PHP version: 7.4.3
- Database driver & version: MySQL 8.0.26
- Plugins & versions: 
    1. Admin Bar | 3.1.11
    2. Asset Rev | 6.0.2
    3. Bugsnag | 2.1.2
    4. Cookies | 1.1.15
    5. Craft Report | 1.12.3
    6. Embedded Assets | 2.8.0
    7. Freeform | 3.11.10
    8. Image Resizer | 2.1.0
    9. Maps | 3.9.1
    10. Neo | 2.11.5
    11. Redactor | 2.8.8
    12. SEO | 3.7.4
    13. SEOmatic | 3.7.4

**Comment by andris-sevcenko** [comment]
The core problem is, indeed, Flysystem flat out rejecting funky paths since 1.1.4. Unfortunately, it performs that check before any file operation, so you won't be able to rename it with Craft. The straightforward way would be to rename the file in the filesystem and then re-indexing. This will lose all the relations for the Asset though, so it might be a bit tricky.

How did the file end up there in the first place?

**Comment by FreekVR** [comment]
Not entirely sure, it was uploaded through Craft for sure, but we also did an upgrade from Craft 2 to 3 last year, so it might have been uploaded all the way back in Craft 2 :)

Perhaps we could try rolling back the flysystem update, running the ascii-filenames cmd,  and then updating again :P

**Comment by andris-sevcenko** [comment]
Yeah, sorry for the run-around, but besides running a PHP script that explicitly does not use Flysystem, there's not much that can be done programmatically.

**Comment by brandonkelly** [comment]
> The straightforward way would be to rename the file in the filesystem and then re-indexing. This will lose all the relations for the Asset though, so it might be a bit tricky.

After renaming the file, you could manually update its `filename` in the `assets` rather than re-indexing the volume.

**Comment by Zae** [comment]
Hi Brandon,

Fixing the name locally and updating the database seems to work, but it's a lot of work finding and updating all the files sadly.

Would be very nice to have a command like `ascii-filenames` to fix this automatically.

**Comment by brandonkelly** [comment]
@Zae There actually is a [utils/ascii-filenames](https://craftcms.com/docs/3.x/console-commands.html#utils-ascii-filenames) CLI command, but it’s going to be affected by this same bug unfortunately.
