### ISSUE TITLE
Fix admintable title/name links showing as bold for items that have a status

### ISSUE THREAD

**Issue by nfourtythree** [craftcms/cms#9704]
### Description
In an admintable it is possible to have a title/name with a status indicated (small coloured circle). Currently, these are being shown with a bold font-weight:

![](https://p191.p3.n0.cdn.getcloudapp.com/items/bLuqJe2r/d0105b52-5d57-47cf-8f54-24b1c0dd29fb.png?v=b0260521969f2279764d07b326bc3631)

However, they should appear in the same way as element title's are displayed in element index tables

![](https://p191.p3.n0.cdn.getcloudapp.com/items/z8urqxgz/506366fe-8065-4c7d-b6dc-d622b961a56c.png?v=8824eee86d5305e84c2b41c48410e684)

Admintable rows with titles/names that do not have a status indicator will continue to appear in the current bold font-weight e.g. Sections

![](https://p191.p3.n0.cdn.getcloudapp.com/items/NQuYdD6o/c8e9e095-b085-4c83-9cb5-c0ffe94bec52.png?v=5fe2c30ec67e81532b72b9ec5e3fddfe)

**Comment by brandonkelly** [comment]
Guessing this is happening due to a `<th>`? In which case bold would be expected.
