### ISSUE TITLE
Pro License reports mismatched domain, but it is correct and has not changed recently

### ISSUE THREAD

**Issue by abryrath** [craftcms/cms#9707]
### Description
I am seeing the error/warning 'The license located at config/license.key belongs to <domain> [Learn More]' when logging into our CMS, but we have not recently changed anything about the license. The domain has not changed in 5+ years. 

I just logged in to id.craftcms.com and tried to add the `www` prefix to the domain, just in case that had something to do with it, but no change in behavior.

I can happily provide screenshots via private email, but would prefer to not mention our clients domain name/URL on this public forum.

### Steps to reproduce

1. Login to the CMS

### Additional info

- Craft version: 3.6.17
- PHP version: 7.4.22
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Can provide, but doubt it is necessary

**Comment by angrybrad** [comment]
Can you try clearing Craft's caches (Utilities->Caches) and if that doesn't resolve it, shoot an email over to support@craftcms.com with the license.key and domain(s) in question.

**Comment by abryrath** [comment]
Thanks @angrybrad, clearing the cache resolved the issue. I should have tried that before filing a bug report!
