### ISSUE TITLE
CRAFT_NITRO/App::isNitro() doesn't work

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#9709]
Looks like it was added here, but then later removed:
https://github.com/craftcms/nitro/search?q=CRAFT_NITRO&type=commits

`App::isNitro()` will always return `false`, as `CRAFT_NITRO` isn't set (nginx or cli).

**Comment by timkelty** [comment]
I can work on a PR if he doesn't get to it first.

**Comment by brandonkelly** [comment]
Just deprecated `App::isNitro()` and updated any code that called it.
