### ISSUE TITLE
Cache-busting Asset URLs while using CloudFront no longer works due to missing GET-key

### ISSUE THREAD

**Issue by FlorisDerks** [craftcms/cms#9716]
For our assets we're using an S3 bucket with a CloudFront CDN in front of it. This used to work fine when we whitelisted the 'mtime', 'tmtime' and 'focal' GET-parameters in CloudFront to bust through the cache and get a fresh copy of the file when anything had changed (`?mtime=20210525133757&focal=51.92%25+33.33%25&tmtime=20210525133805`).

However, since 3.7 this has changed to only a dynamically filled key without a value (`?1628838452,0.5186,0.1988`), which makes it a lot harder to properly configure CloudFront to allow that specific value to be used to circumvent the cache, and I would prefer to not make it a free-for-all.

This is what the CloudFront documentation has as options, where I would prefer to use the last option instead of the middle one which is currently our only choice:

> You can configure CloudFront to do one of the following:
> - Don't forward query strings to the origin at all. If you don't forward query strings, CloudFront doesn't cache based on query string parameters.
> - Forward query strings to the origin, and cache based on all parameters in the query string.
> - Forward query strings to the origin, and cache based on specified parameters in the query string.

Would it be possible to re-add a query string key to these revved asset URLs, or add an option to add our own key-name with a setting (`'revAssetUrlsWithKey' => 'v'` to create `?v=1628838452,0.5186,0.1988` for example)?

**Comment by brandonkelly** [comment]
Good point. Just changed it to use a `v` query string param, for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.9 is out now with that change.
