### ISSUE TITLE
Time zone not respected in Date field

### ISSUE THREAD

**Issue by clowerweb** [craftcms/cms#9719]
### Description
I have a standard Date field which allows the user to select a time and time zone:
![image](https://user-images.githubusercontent.com/885727/129384534-3e886b92-b1ff-4f67-bff9-e840e9ee978e.png)

When a time zone is set on the field in the entry, it always comes back in UTC:
![image](https://user-images.githubusercontent.com/885727/129384710-1ca8f407-c2d1-4f28-ad8c-7bb985272dac.png)
![image](https://user-images.githubusercontent.com/885727/129384831-a4cb1c51-b14a-402b-b20a-182af30136c5.png)

### Steps to reproduce

1. Create a Date field and enable "Show date and time" and "Show Time Zone", and add that field to an entry
2. Select a date and time, and set the Time Zone field to anything other than UTC
3. Save and check the output in GraphiQL (as _this may be specific to GraphQL_; I haven't tested it in Twig/PHP)
4. Notice that the returned date and time is in UTC regardless of which time zone you've selected

### Additional info

- Craft version: 3.7.7
- PHP version: 7.4.19
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
![image](https://user-images.githubusercontent.com/885727/129385512-9b56a650-65d6-42f7-87fb-81d538619c1c.png)

**Comment by clowerweb** [comment]
I see that it converts the time zone from the selected one to UTC, but is this intended just as a convenience for authors? The client for this site has various events all over the world and wants to display times for the events in the local time zone for the venue, so we were hoping this would somehow return the selected time zone (otherwise we still don't know what time zone they selected for front-end display and ICS exporting).

**Comment by brandonkelly** [comment]
Yeah I would consider this a bug. Date fields with explicit timestamps will have the selected timestamp automatically applied to it when retrieving the field value in Twig, so GraphQL should follow suit.

**Comment by andris-sevcenko** [comment]
I agree that the behavior should follow what Twig does, but it's a little trickier in the case of GraphQL since it is an external API and a 3rd party might be relying on the data.

It has to be a way that doesn't affect any existing queries simply by updating Craft, so it will either have to be a config setting that affects every date field (such as https://craftcms.com/docs/3.x/config/config-settings.html#setgraphqldatestosystemtimezone) or a per-field argument.

**Comment by andris-sevcenko** [comment]
Okay, was able to come up with a way that should not affect existing any fields that don't specify the timezone in the settings, All primed for the next release!

**Comment by brandonkelly** [comment]
Craft 3.7.9 is out now with the fix. Thanks for reporting, @clowerweb!

**Comment by romainpoirier** [comment]
Look like I have the same kind of issue using a Date field within a Table field + timezone set in `general/config.php` + using the `.where()` query. Please see #12670 for reference.
