### ISSUE TITLE
When viewing an asset's edit page there is an extra breadcrumb arrow

### ISSUE THREAD

**Issue by kylecotter** [craftcms/cms#9720]
### Description

When viewing an asset's edit page, the top breadcrumb bar has either an extra arrow or a missing item.

<img width="192" alt="Screen Shot 2021-08-13 at 11 55 14 AM" src="https://user-images.githubusercontent.com/505894/129386340-461c4e2a-45ae-47da-a810-6166c860268e.png">

### Steps to reproduce

1. View an asset's edit page

### Additional info

- Craft version: Reproduced on 3.7.4 and 3.7.8 but is not a bug on 3.6.17
- PHP version: 7.4
- Database driver & version: MySQL 8
- Plugins & versions: ImagerX, AWS S3 - same setup across all 3 Craft versions

**Comment by brandonkelly** [comment]
Good catch, thanks for reporting! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.9 is out now with the fix. Thanks again.
