### ISSUE TITLE
Creating a category on a non-primary site can result in a 404

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#9722]
### Steps to reproduce

1. Make a fresh Craft 3.7.8 installation
2. Add a 2nd site
3. Create a Category Group and make the Category URI Format blank for both sites
4. Click Category and swap to the 2nd site, then click "New Category"
5. You'll get a 404 "Template not found: categories/testCategory/new/site2" error message

This works fine if you create the category on site 1.

### Additional info

- Craft version: 3.7.8
- PHP version: 8.0
- Database driver & version: MySQL 8
- Plugins & versions: None

**Comment by brandonkelly** [comment]
Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.9 is out now with the fix.
