### ISSUE TITLE
Bug in file browser with folder names containing special chars (ä,ö,ü,...)

### ISSUE THREAD

**Issue by luke-nehemedia** [craftcms/cms#9723]
### Description
My client reported that he uploaded a file into a folder, then opened it to change its title and other field. On pressing `save` he received an error:

> Template not found: assets/bilder/folder1/folder2/foldername_with_ö/folder4

I was able to resolve the issue by renaming the folder, replacing the `ö` with `oe`. 

### Steps to reproduce
1. Create some folders, at least one containing `ä`,`ö`, or `ü`.
2. Upload a file into the folder (or a subfolder)
3. Open the file and edit its title
4. Press save

### Info
- Craft version: 3.7.8
- PHP version: 7.3.29
- Database driver & version: MySQL 5.7.22
- Plugins & versions: -

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.
