### ISSUE TITLE
Installing via CLI with existing valid env variable always creates `PRIMARY_SITE_URL`

### ISSUE THREAD

**Issue by engram-design** [craftcms/cms#9724]
As some background, we have our own command-line wrapper around `setup/db-creds` and `install/craft` which is pretty neat to seed in some things that's standard to our team:

```
$dbOptions = [
    'driver' => 'mysql',
    'user' => 'root',
    'server' => 'localhost',
    'port' => '3306',
    'tablePrefix' => 'none',
];

$installOptions = [
    'password' => StringHelper::randomString(18, true),
    'siteName' => 'Base',
    'siteUrl' => '$BASE_URL',
    'language' => 'en-AU',
];

Craft::$app->runAction('setup/app-id');
Craft::$app->runAction('setup/security-key');
Craft::$app->runAction('setup/db-creds', $dbOptions);
Craft::$app->runAction('install/craft', $installOptions);
```

Part of our starter sets up a `.env` from `.env.example` and bring along a `$BASE_URL` variable. I suppose we could rename this to `PRIMARY_SITE_URL` as it seems that's now a standard variable for Craft - but muscle-memory.

The issue - whenever we run our script it always adds a `PRIMARY_SITE_URL` which is kind of annoying. This is due to this check:
https://github.com/craftcms/cms/blob/5b1fcec4f1729b5e40d368d983770088fd3e75e9/src/console/controllers/InstallController.php#L159-L166

And a quick debug with a `$BASE_URL="http://base-craft.test/"` env variable.

```
echo print_r($this->siteUrl) . PHP_EOL;
echo print_r($site->baseUrl) . PHP_EOL;

// Outputs:
$BASE_URL
http://base-craft.test/
```

This is because the `$site->baseUrl[0]` uses the parsed variable, which resolves to `http://base-craft.test/`. Hence, `$site->baseUrl[0] = 'h'`.

Changing these checks to `$site->getBaseUrl(false)[0]` does the trick.

**Comment by brandonkelly** [comment]
Doh, thanks for reporting! And for the PR, though I decided to go with an `in_array()` call rather than call `getBaseUrl(false)` twice.

**Comment by brandonkelly** [comment]
Craft 3.7.9 is out now with the fix.
