### ISSUE TITLE
BadgeCount update on Save Element

### ISSUE THREAD

**Issue by mortscode** [craftcms/cms#9728]
### Description

In my plugin, I'm using the Craft Element Class to create "Feedback" items from the users on our site. These could be questions or reviews, but I'm using the `badgeCount` property in my `defineSources` method to show how many "pending" items are in need of approval:

<img width="542" alt="Pasted_Image_8_16_21__2_43_PM" src="https://user-images.githubusercontent.com/3239582/129664030-106c3b5c-f359-46e2-9317-b790619363d3.png">

The issue I'm having is that when I select these elements and update their statuses via the dropdown (image below), the statuses update without a browser reload as expected, but the `badgeCount` number remains the same. If I then manually refresh the browser, the `badgeCount` numbers update as I'd hope.

![image](https://user-images.githubusercontent.com/3239582/129664289-e2d33b0a-0902-46ce-8115-6f2c89228cba.png)

Please let me know if there is a way I can update them with an event trigger, or if there is an example of this being done correctly somewhere that I can dig into. 

### Additional info

- Craft version: 3.7.8
- PHP version: 8.0
- Database driver & version: MariaDB 10.5
- Plugins & versions: mortscode/feedback 1.0.9: https://github.com/mortscode/feedback-plugin

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just released Craft 3.7.9 with a fix for this.

**Comment by mortscode** [comment]
@brandonkelly works like a dream! Thank you!!
