### ISSUE TITLE
Saving with shortcut cmd+s triggering "Uncaught in promise" error from saveDraft.

### ISSUE THREAD

**Issue by turnstylerj** [craftcms/cms#9737]
### Description

We're experiencing what appears to be [this issue](https://github.com/craftcms/cms/issues/4761) on Craft 3.7.

### Steps to reproduce

1. Create and save a new entry
2. Open browser console to observe error
3. Make an edit to the entry, and save changes with the keyboard shortcut cmd/ctrl+s.

![Screen Shot 2021-08-18 at 10 19 10 AM](https://user-images.githubusercontent.com/42223501/129948579-e56eaf3e-341b-4ddc-9e0a-635b607ee157.png)

### Additional info

Looking at the previous issue, it appeared to be related to an older version of the Neo plugin, which we are using, but I've tested this on a new entry type with no Neo fields and experienced the same behavior. Let me know if there's anything else I can provide that would be helpful.

- Craft version: 3.7.7
- PHP version: 7.4
- Database driver & version: MySQL 5.7
- Plugins & versions: Neo 2.11.5

**Comment by rob-baker-ar** [comment]
I'm getting this too - I think I duplicated this issue. There is a little more info over here: https://github.com/craftcms/cms/issues/9741
