### ISSUE TITLE
Broken cpresources behaviour in load balanced environments without a shared filesystem

### ISSUE THREAD

**Issue by meestaben** [craftcms/cms#9738]
### Description

This change in 3.6.18:

https://github.com/craftcms/cms/commit/9f13b36828e5dc57573aae234b6b45096b5f645d

breaks cpresources URLs in load balanced environments where code is deployed independently to each box, and cpresources directory is not on a shared filesystem. 

The change was originally discussed on #9140, with the aim to prevent old assets from being incorrectly cached downstream during a rolling deployment. 

In versions prior to 3.6.18 everything worked fine, even though you'd in theory end up with as many copies of each logical asset as you have application servers running (all with different hashes in their path). 

Reverting the above change fixes the issue for us.

### Steps to reproduce

1. Be running a load balanced environment with Craft >=3.6.18 and no shared filesystem except for `./storage`
2. Visit the admin CP
3. Reload the page repeatedly and observe that on each load several cpresources assets will 404, depending on which server is being hit.

### Additional info

- Craft version: >= 3.6.18
- PHP version: 7.4.15
- Database driver & version: MySQL 5.7 (AWS Aurora)
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting that. Just released Craft 3.7.10 which reverts the changes made for #9140.

**Comment by andygrn** [comment]
@brandonkelly Is there a way to fix this without losing the cache headers? Our control panels on 3.7.10+ have become unacceptably slow again, for the same reason outlined in #9140.

**Comment by brandonkelly** [comment]
@andygrn I’ll have to think about it some more. We can’t blindly add the cache headers because that risks browsers caching an outdated file if the deployment hadn’t hit the current server yet (https://github.com/craftcms/cms/issues/9140#issuecomment-877521916), and we can’t validate based on the hash because that can change from server to server (as pointed out by this issue). So it’s tricky. Ideally we could start allowing you to use an S3 bucket or something.

**Comment by andygrn** [comment]
@brandonkelly Presumably you could force browsers to re-request changed assets using a change to the ?v= string between Craft versions, although I'm not certain that would prevent jmortlock's problem from #9140.

Some sort of native cpresources volume would be very welcome! I suspect we'll have to figure out a workaround in the meantime, I've seen some people using custom AssetManager components to handle it...
