### ISSUE TITLE
"Your changes could not be stored" when a provisional draft saves

### ISSUE THREAD

**Issue by rob-baker-ar** [craftcms/cms#9741]
### Description

After making an edit to an entry (any entry it seems) an automatic save (as provisional draft) occurs. I get a JS error `Uncaught (in promise)` in the console looking like:

 _(I have some custom CSS to highlight the site selector in red to help our content editors!)_

![image](https://user-images.githubusercontent.com/39988088/130075723-2843c293-e9b6-43ad-af2a-025c3025ad6a.png)

The save does in fact work as looking at the JSON response, it seems fine and when reloading the browser, I get all the saved field data in the various fields.

It looks like the JS is mis-interpreting the response.

The reponse:

```json
{
  "sourceId":189440,
  "draftId":2570,
  "timestamp":"at 14:12",
  "creator":"[my name!]",
  "draftName":"Draft 6",
  "draftNotes":"",
  "docTitle":"[entry title] — Edited",
  "title":"[entry title] (Mozambique)",
  "duplicatedElements":[],
  "previewTargets":[
    {
	  "label":"Primary entry page",
	  "refresh":"1",
	  "url":"[the correct front end url for the entry]"
	},
	{
	  "label":"📣 Social Media Preview",
	  "url":"[the correct url for the seomatic social media preview]",
	  "refresh":true
	}
  ],
  "modifiedAttributes":[]
}
```

### Steps to reproduce

1. Open an existing entry
2. Make an edit
3. Un-focus the field so an automatic save happens
4. Get the error

### Additional info

- Craft version: 3.7.9
- PHP version: 7.4.3
- Database driver & version: MySQL 5.5.5
- Plugins & versions: 
  - Activity Log	dev-master
  - Asset Rev	6.0.2
  - Category Groups Field	1.2.2
  - CP Field Inspect	1.2.5
  - Dumper	2.0.0
  - Field Manager	2.2.4
  - Freeform	3.11.10
  - Imager	v2.4.0
  - Maps	3.9.1
  - Navigation	1.4.20
  - Redactor	2.8.8
  - Retcon	2.2.3
  - Retour	3.1.60
  - Section Field	1.1.0
  - SEOmatic	3.3.48
  - Snitch	3.0.4.1
  - Super Table	2.6.8
  - Template Select	2.0.2
  - Wordsmith	3.3.0.1

**Comment by brandonkelly** [comment]
The status code must not be 200 though,  which is why it would be hitting the `catch` block of the promise and giving you that error.

Try clearing your `storage/logs/` folder, reproduce the error, and then search for `[error]` in `storage/logs/web.log`. Any results? If so what is the log message + stack trace?

**Comment by rob-baker-ar** [comment]
Just replicated this again in our dev environment. The status code is `200` when this happens - having cleared the log dir, there are no errors.

Looking at DraftEditor.js `saveDraft()` invokes and returns a `Promise` it does not look to me like that promise is rejected until `reject()` is called in the `catch()` - Chrome thinks the `reject()` on line ~ 829 is being called. There could be an error coming from the Axios request via `Craft.sendActionRequest()`, it could also be something else in the `then` function following `Craft.sendActionRequest()`. Unfortunately, I can't tell because the `catch()` function does not have a parameter to look at the error when debugging in Chrome.

**Comment by brandonkelly** [comment]
You can see what was passed to `catch()` by running `console.log(arguments)`.

**Comment by rob-baker-ar** [comment]
`console.log(arguments)` returns `undefined` in the context of the catch() function when paused at a break-point in the catch function .

I can't convince any of the browsers I'm working on to show an error with greater detail than Chrome _(as above)_ .  As far as I have traced through, I can't see any errors thrown or calls to `reject()` that are being reached in _Craft_ JS code - it seems to be coming from Axios (perhaps this call: `axios.request(options).then(resolve).catch(reject);` in `Craft.sendActionRequest()`) or from a JS error thrown somewhere without a message? Stepping through the axios code trying to find an error trigger is kind of challenging and Chrome seems to get lost maybe due to a source map issue - axios is more abstract than the Craft JS to allow for middleware etc.

Not sure how I can make headway on this - it's not a critical issue, but it's causing lots of our users to report "random server errors" (of course technically not what's happening as the auto save works, the browser is just reporting that it doesn't). Which in turn is creating unnecessary support "noise".

**Comment by brandonkelly** [comment]
Is the error reliably reproducible on your end? If so can you send your `composer.json` and `composer.lock` files, plus a database backup, into support@craftcms.com? We can look into it from there.

**Comment by rob-baker-ar** [comment]
Yes, every time an autosave happens on any entry (i.e. when changing any field and triggering blur event) . I sent exactly those bits for a different email based support request _(subject: Duplicated Matrix blocks)_ earlier today.

Thanks!

**Comment by jonathanmelville** [comment]
I'm now getting this on all draft saves as well.

<img width="401" alt="Image 2021-09-08 at 1 33 38 PM" src="https://user-images.githubusercontent.com/7415693/132557282-2234a3cf-18d0-4c1e-a308-3473f7f5a8a8.png">

**Comment by brandonkelly** [comment]
@jonathanmelville Can you send in a database backup and your Composer files to support@craftcms.com?

**Comment by jonathanmelville** [comment]
Hey @brandonkelly, I nuked the storage directory on this site and it resolved the issue for me!

**Comment by iwe-hi** [comment]
Having the same problem as @jonathanmelville . Clearing the storage directory didn't help. I sent a database backup and the composer files to support@craftcms.com.

**Comment by rob-baker-ar** [comment]
Unfortunately, emptying storage  directory did not help here either.

**Comment by rob-baker-ar** [comment]
OK, I have updated Craft to `3.7.13` and this issue is still occurring, but due to a change or two in that release, there is now more to go on. The `catch()` condition above now has a parameter containing an error where it did not before:

![image](https://user-images.githubusercontent.com/39988088/133600885-8da6afc1-2079-4245-8bf0-db3d0c088df4.png)

Strangely (very strangely!), when I delve into what triggered this (following the `VM929:1` link) it reveals the browser is being asked to parse the `content-type: application/x-www-form-urlencoded` POST data being POSTed to `admin/actions/entry-revisions/save-draft` as JSON and, understandably, failing.

The thing that is confusing about this development though is when I look at the network tab in Chrome, the above request looks normal and the response does too - a well formed, `200` status code, JSON response that Chrome has no issue parsing and showing as such.

The trace attempts to refer to a line in the HTML which is JS, but probably a red herring - that maps to some jQuery code that is listening to `keydown` to decide whether is cancels the event via `ev.preventDefault()` for a specific field inside a Matrix block.

My gut is telling me there is something inside Axios that is trying to parse form / URL encoded POST data as JSON, perhaps due to a particular HTTP header being or not being set. On the other hand, if that were the case, it would probably be hitting more people.

**Comment by rob-baker-ar** [comment]
_Deleted a comment as it was no longer relevant._

I think this can be closed, certainly our case of this specific issue is sorted.

This is why:

We have been using Axios on the front-end of the site and at variors points, for various different reasons, we use Axios interceptors to enhance it's functionality, provide loading graphics, etc. One of these bits of code was accidentally being included via a call in a module on the control panel as well at the front end. Up until version `3.7.*` this was having no effect - something changed in the Craft source so that one of our interceptors looking at the requests / responses was throwing an error with the save draft request. Unfortunately, we could not find that until version `3.7.13` where the text of the error became available in the `catch` clause of `DraftEditor.saveDraft()` referred to above.

It's a problem compounded by the fact that Chrome / any browser can find it very difficult to trace back to causal code when the error has a `setTimeout()` call, a couple of different `Promise`s in it's trace and a piece of middleware attached to a library a few steps removed fromthe 1st party code, all while trying to map to source maps.

So the good news is our case is fixed. It's also good that error visibility is increased so it should be much easier to spot and fix something like this in the future. Thank you for your attention looking at this.

I just hope that this issue thread can help someone in the future!

**Comment by brandonkelly** [comment]
Glad you got it sorted @rob-baker-ar!

(Here’s what he means by the increased error visibility, for anyone who’s following along:)

<img width="445" alt="A heads-up display showing details of a failed draft save" src="https://user-images.githubusercontent.com/47792/133665422-7ac25a7c-0d69-4a1d-9ede-be6cc993381f.png">
