### ISSUE TITLE
Editing Matrix field throws Database exception - Column not found - for a field that exists outside of the Matrix

### ISSUE THREAD

**Issue by stuartmitchelhill** [craftcms/cms#9749]
### Description
Since upgrading to craft 3.7 whenever I try to edit an existing matrix field, the CMS throws a Database Exception for Column not found, referencing a field that exists separately to the matrix field itself. If I remove the fields that are referenced in the Database exception error the matrix field saves as expected. Creating new fields does not cause any errors.

## Steps to reproduce

1. Navigate to matrix field in Settings > Fields
2. Edit matrix field
2. Save edits

### Additional info

- Craft version: 3.7.10
- PHP version: 7.4.19
- Database driver & version: MySQL 5.7.26
- Plugins & Versions:
    - Amazon S3 1.2.15
    - CP Clear Cache 1.1.0
    - Expanded Singles 1.1.4
    - Gridsome Nogn 0.1.5
    - Redactor 2.8.8
    - Super Table 2.6.8
    - Typed link field 2.0.0-beta.12
    - Webhooks 2.3.3 

<img width="1444" alt="Screen Shot 2021-08-23 at 10 39 20 am" src="https://user-images.githubusercontent.com/13814948/130375815-b83bc594-181f-48f9-8788-7dea1ca4eecc.png">
<img width="1858" alt="Screen Shot 2021-08-23 at 10 39 37 am" src="https://user-images.githubusercontent.com/13814948/130375819-2376c1b0-fd6a-41db-be59-8b924083e6c7.png">

**Comment by brandonkelly** [comment]
Do you have a database backup from before updating to 3.7? If so can you please send it, as well as your `composer.json` and `composer.lock` files, into support@craftcms.com so we can look into it?

**Comment by stuartmitchelhill** [comment]
@brandonkelly unfortunately there is no backup from before the 3.7 update. I can send through a current backup and the composer files if that will help, or is it pointless without the backup from 3.6?

**Comment by brandonkelly** [comment]
Current backup is fine if that’s all you have.

**Comment by stuartmitchelhill** [comment]
@brandonkelly I have sent over the files. Thanks for your help :)

**Comment by tommysvr** [comment]
I was able to reproduce the error. Disabling Type Linked Field or Expanded Singles let the Matrix field be saved, and seems to be related to this: https://github.com/sebastian-lenz/craft-linkfield/issues/163

**Comment by brandonkelly** [comment]
Not exactly sure what caused this (maybe 68416ecdee8?), but neither of those plugins are doing anything concerning leading up to the error, so consider it a Craft bug.

Just fixed for the next release. To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.10"` and run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.7.11 is out with that fix.
