### ISSUE TITLE
Elements' sourceUid is deprecated since 3.7.7, but what is the replacement to use in Preview Target URLs?

### ISSUE THREAD

**Issue by LizZerrG** [craftcms/cms#9757]
### Description
We use elements' `sourceUid` in the preview target URL for our headless front-end. Since Craft 3.7.7 `sourceUid` is deprecated. The proposed replacement is `canonicalId`, except that contains the ID of the source entry, and not the UID (which we need). There is however a method `getCanonical(true)->uid`, but I haven't found a way to use this in the preview target URL since it uses Twig notation.

Also the documentation still says to use `sourceUid` on these places: 
* https://craftcms.com/docs/3.x/entries.html#preview-targets
* https://craftcms.com/docs/3.x/graphql.html#the-entryinterface-interface
* https://docs.craftcms.com/api/v3/craft-base-element.html#method-getsourceuid

### Steps to reproduce

1. Create a section "Article".
2. Add `{site.getBaseUrl()}/preview/{sourceUid}` as the preview target URL.
3. Create a new entry and preview it.
4. Go to `admin/utilities/deprecation-errors` and you will see the deprecation error: "Deprecation error: Elements’ getSourceUid() method has been deprecated. Use getCanonical(true)->uid instead."

### Additional info

- Craft version: > 3.7.7
- PHP version: 7.4
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Sorry about this… I overlooked that we were actually calling out `getSourceId()`/`sourceId` in the docs, and didn’t think it was necessary to create a new `getCanonicalUid()` method, but clearly that was wrong. Just fixed for the next release, so going forward you can just use `{canonicalUid}`.

To get the change early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.10"` and run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.7.11 is out now with `{canonicalUid}` support.
