### ISSUE TITLE
Add max amount to fields: tags, checkboxes, table

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#976]
> Created by: Rob (rob@layermade.com) on 2015/07/19 22:22:24 +0000
> Votes at time of UserVoice import: 6

-----------------------------------

I've come up with this issue a couple of times, where from a UX point of view we need to limit how many options a user can select: tags, checkbox, table rows. I have the specific use-case where the client wants selectable tags, but limiting them within a user group.

Ideally you'd be able to do this depending on it's context (admin, user-group, section), but I guess that's going to be difficult to achieve.

The only option I can think of at the moment is to use something like Chosen on a front-end template: http://bit.ly/1VuMdy9

**Comment by brandonkelly** [comment]
This is still a valid feature request, but in the meantime, you can add your own custom validation rules to entries using the [EVENT_DEFINE_RULES](https://docs.craftcms.com/api/v3/craft-base-model.html#event-define-rules) event from a custom [module](https://docs.craftcms.com/v3/extend/module-guide.html).

And Craft provides an [ArrayValidator](https://docs.craftcms.com/api/v3/craft-validators-arrayvalidator.html) validation class, which makes it easy to validate based on the size of an array (or element query result, as in the case of a Tags field).

```php
use craft\elements\Entry;
use craft\events\DefineRulesEvent;
use craft\validators\ArrayValidator;
use yii\base\Event;

Event::on(Entry::class, Entry::EVENT_DEFINE_RULES, function(DefineRulesEvent $e) {
    /** @var Entry $entry */
    $entry = $e->sender;

    // Only worry about entries in the News section
    if ($entry->section->handle !== 'news') {
        return;
    }

    $e->rules[] = ['field:myTagsField', ArrayValidator::class, 'max' => 5];
    $e->rules[] = ['field:myCheckboxesField', ArrayValidator::class, 'max' => 5];
    $e->rules[] = ['field:myTableField', ArrayValidator::class, 'max' => 5];
});
```
