### ISSUE TITLE
Error when deleting siteId 1

### ISSUE THREAD

**Issue by cecilehabran** [craftcms/cms#9763]
I copied a craft install to a new website using the same sections, templates and assets.
I added 3 sites (3 languages) with different urls (set in .env), enabled them in the section settings and disabled the old sites, set up everything and it's working correctly.
I set one of the new site as primary, and when I deleted the other sites, I get and error on the front:
```
Exception – yii\base\Exception
Invalid site ID: 1
```
I couldn't find any solution so I changed the dateDeleted in the database to NULL so I could see the site again and continue working. Same error happens if I disabled the site. I cleared the caches and everything.

What should I do ?

Config:

PHP version	7.4.23
Database driver & version	MySQL 5.7.34
Craft edition & version	Craft Pro 3.7.10
Yii version	2.0.43

Field Manager	2.2.4
Formie	1.4.14
Maps	3.9.1
Navigation	1.4.20
Neo	2.11.7
Redactor	2.8.8
SEO	3.7.4
Super Table	2.6.8
Trending Posts	1.0.2

**Comment by brandonkelly** [comment]
How exactly did you copy the site? Was your previous site’s `config/project/` folder in place _**before**_ you ran Craft’s installer? Or did you install Craft normally, and then swap out the `config/project/` folder? (It needs to be the former.)

**Comment by cecilehabran** [comment]
Actually I installed craft normally and copied the database

**Comment by brandonkelly** [comment]
OK, same basic issue – there was a conflict between your `config/project/` folder and the project config stored in the database, which Craft wasn’t able to resolve correctly.

Here’s what you should do if you want to clone an existing site’s structure but not its content:

1. Make sure Craft and your plugins are all up-to-date on the original site.
2. On the original site, go to **Utilities** → **Project Config** and press **Rebuild**.
3. Create a new project directory for the new site.
4. Copy the `composer.json`, `composer.lock`, `config/project/*`, `craft`, `web/index.php`, `.env`, `.env.example`, and whatever other files you wish to carry over, from the original site to the new project folder.
5. Run `composer install` on the new project folder. (**NOT** `composer update`. When you run `composer install` combined with an existing `composer.lock` file, you can be sure you are going to get the _exact_ same software versions as the original site, which is important here.)
6. Run `php craft setup` and run through the setup + install wizards.

Toward the end of installation, you should see this console output:

```
    > applying existing project config ... done
```

If that works as expected, your new Craft install will share the exact same project config as the original site.
