### ISSUE TITLE
Pushed queue job ID not returning anymore

### ISSUE THREAD

**Issue by jerome2710** [craftcms/cms#9764]
### Description
Due to 641778c by @brandonkelly fixing #7719, queue jobs pushed to the queue do not return their created job-ID anymore, as per Docblock: 

> @return string|null The new job ID

### Additional info

- Craft version: 3.7.10
- PHP version: N/A
- Database driver & version: N/A
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just released Craft 3.7.11 with a fix.
