### ISSUE TITLE
Gear icon (settings) and dropdown are too small and confusing

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#977]
> Created by: Timothy Kelty (timkelty@gmail.com) on 2015/04/02 12:33:05 +0000
> Votes at time of UserVoice import: 6

-----------------------------------

A few issues:

- It's been confusing to users that the "Users" link is one button, while the "Settings (gear)" is two, yet they look identical.

- Furthermore, if the buttons are split, the dropdown target is _tiny_

- I also find it confusing that there is dropdown, but there are many things you can't get to from it (anything under Tools).

**Comment by timkelty** [comment]
Fixed in Craft 2.something.
@takobell go ahead and close!

**Comment by takobell** [comment]
Thanks, Tim!
