### ISSUE TITLE
Not possible to set site-specific enabled state via GraphQL mutation

### ISSUE THREAD

**Issue by weotch** [craftcms/cms#9771]
### Description

It doesn't appear possible to set a site-specific enabled state withGraphQL mutations.

### Steps to reproduce

From the GraphQL explorer, first run something like this to create an entry:

```gql
mutation {
  save_products_flavors_Entry(
    title: "Example"
    enabled: false
  ) { id }
}
```

Then, run a follow up migration to enable the entry in one of the sites:

```gql
mutation {
  save_products_flavors_Entry(
    id: 123
    siteId: 2
    enabled: true
  ) { id }
}
```

Since the second, updating query includes a siteId, my expectation was that the change to the `enabled` state would only apply to the one site.  Instead, the enabled state changes for all sites.\

### Additional info

- Craft version: Craft Pro 3.7.10
- PHP version: 7.4.22
- Database driver & version: MySQL 8.0.26
- Plugins & versions: 

![image](https://user-images.githubusercontent.com/77567/131238048-07ba1bbb-4fac-4773-b00b-4875ae46b55b.png)

**Comment by andris-sevcenko** [comment]
Just fixed this for Craft 4.0. Unfortunately, I can't push the fix for 3.7, as this is a change in behavior that some people might be unintentionally relying on.
