### ISSUE TITLE
setPasswordPath with headlessMode on not working when using an absolute URL

### ISSUE THREAD

**Issue by jornwildenbeest** [craftcms/cms#9773]
### Description

I am using Craft 3.6.15 with headless mode on and I want to change the setPasswordPath so users can reset their password through the frontend, because the backend is redirecting them to /admin after they successfully reset their password.

So figured i would redirect them to the frontend to reset their password so i can change the redirect url myself. 
According to the docs (https://craftcms.com/docs/3.x/config/config-settings.html#setpasswordpath), setPasswordPath accepts an absolute URL. But when I use this in my general.php:

```
 'setPasswordPath' => 'https://testurl.com/reset-password',
```

it still uses the baseCpUrl with /set-password.

I am using the jamesedmonston/graphql-authentication plugin to send the reset-password mail through the frontend.

### Additional info

- Craft version: 3.6.15
- PHP version: 7.4
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Does the user you’re testing this on have access to the control panel?

**Comment by jornwildenbeest** [comment]
@brandonkelly Thanks, the user had indeed access to the control panel. Tested it with another use without access to the cp and it worked fine.

**Comment by brandonkelly** [comment]
Cool, that’s working as expected then.
