### ISSUE TITLE
Multisite - Specific site group users cannot edit sections (Single) in site assigned to them (Craft v3.7.10)

### ISSUE THREAD

**Issue by bkrsmanovic** [craftcms/cms#9774]
### Description
Aight, so this is hard to describe, try to follow me. 
We have multisite structure, and for each site, we have created specific admin groups dedicated to only edit their specific sites.
Example:
Sites:
![Screenshot from 2021-08-31 09-20-56](https://user-images.githubusercontent.com/15169280/131460333-dc2e83b2-19ff-4836-8f92-5b8e0a06550f.png)

User Groups:
![Screenshot from 2021-08-31 09-22-35](https://user-images.githubusercontent.com/15169280/131460506-c5d1edaa-c743-4b80-aff7-6af8650cdb07.png)

Each user group, has permission to edit all sections types (structure, single, channels) for that specific site, for example Enida Admins:
![Screenshot from 2021-08-31 09-23-02](https://user-images.githubusercontent.com/15169280/131460864-cee60df2-56c8-478a-91c2-f7868def18e1.png)

End for section in question (Single section - Home), rules for Enida admins are all selected:
![Screenshot from 2021-08-31 09-26-17](https://user-images.githubusercontent.com/15169280/131461073-e0e0f4af-e034-4f78-9518-456034ce9a4d.png)

All fields inside of it, and it consists of multiple normal fields, matrixes, super tables etc, are selected to be translated via **Translate for each site.**

Now issue:
Everything was working fine, until we updated to some patch after 3.7. We are now on 3.7.10 (latest at moment).
Content was edited both by Enida Admin, and by our main Admin account (1 that has access to all sites).
At some point, when Enida admin tries to go to backend and edit Home page, he is getting an error:
![Screenshot from 2021-08-31 09-34-53](https://user-images.githubusercontent.com/15169280/131462096-df3d1abc-7a7a-40f6-a773-3052394974f2.png)

web.log (previously cleaned):
![Screenshot from 2021-08-31 09-36-06](https://user-images.githubusercontent.com/15169280/131462270-79011e24-df01-4de2-9b0d-9d1a53db3370.png)

I am not sure why is it trying to duplicate this entry on this site, when we are opening to edit it.
Maybe it has something to do with new Streamlined Entry Publishing Flow, which also causes saving / editing entries to be significantly slower than before, but again, it might be different issue completely.

### Steps to reproduce

Described above.

### Additional info

- Craft version: 3.7.10
- PHP version: 8.0.3
- Database driver & version:  10.3.31-MariaDB Ubuntu 20.04
- Plugins & versions: 
Redactor: 2.8.8
Super Table: 2.6.8

**Comment by brandonkelly** [comment]
Any chance you can send a database backup plus your `composer.json` + `composer.lock` files to support@craftcms.com? It would help immensely with trying to track this down.

**Comment by bkrsmanovic** [comment]
Yes I will send you asap. Thank you.

**Comment by bkrsmanovic** [comment]
@brandonkelly I have sent you an email with all information I think you need. Please let me know if you need anything else.

**Comment by brandonkelly** [comment]
Thanks! Was able to reproduce with your files and get this fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.11"` and run `composer update`.

**Comment by bkrsmanovic** [comment]
Awesome, thank you so much. :)

**Comment by brandonkelly** [comment]
Craft 3.7.12 is out now with that fix.
