### ISSUE TITLE
Changing propagation method of a structure breaks nesting for non-default site

### ISSUE THREAD

**Issue by i-just** [craftcms/cms#9782]
### Description
When changing propagation method of a structure from "Save entries to all sites enabled for this section" to "Only save entries to the site they were created in" the nesting of the non-default site breaks (default site is absolutely fine). It looks as if all top-level entries were shifted by one within a level. If I have a structure like this:
```
Page 1
    Page 1.1
        Page 1.1.1
    Page 1.2
Page 2
```

then after changing the propagation method the result for the non-default site is:
```
        Page 1.1.1
    Page 1.1
    Page 1.2
Page 1
Page 2
```

If I then go and edit `Page 1.1.1` or `Page 1.1` or `Page 1.2` they are all missing a parent. 
Tried this for multiple structures (small and very large) and the result is always the same. It used to work fine around mid-June 2021. I don't remember the exact version of Craft CMS I used back then but it was definitely one of the 3.6, most likely 3.6.13.

### Steps to reproduce
1. Create 2 sites.
2. Create a structure with at least 2 levels, enable it for both sites and set propagation method to "Save entries to all sites enabled for this section"
3. Create entries for this section with at least 2 levels. Make sure entries exist for both sites.
4. Change propagation method for this section to "Only save entries to the site they were created in"
5. Go to entries list for the default site - all should be fine. Switch to the second site - the nesting should be messed up as described above and if you edit any of the entries for the non-default site they won't have a parent saved against them.

### Additional info

- Craft version: 3.7.10
- PHP version: 7.4
- Database driver & version: mysql
- Plugins & versions: loads, but tested with all of them turned off too and got the same result

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

Unfortunately the fix isn’t retroactive, but if you want to redo the propagation method change with the fix in place, follow these steps:

1. While the section’s Propagation Method is still set to “Only save entries to the site they were created in”, select the site the entries were duplicated into (where the structure is messed up), select all of them and delete them.
2. Go to your section’s settings and change the Propagation Method back to “Save entries to all sites enabled for this section”.
3. Wait for the “Applying new propagation method” job to complete, and verify that the entries exist in both sites, with the same structure.
4. Change your section’s Propagation Method to “Only save entries to the site they were created in” once again. This time, the duplicate entries’ structure should resemble the original structure.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.11"` and run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.7.12 is out now with that fix.

**Comment by shoored** [comment]
I seem to be having the same ordering issue on 3.7.13 after an upgrade from 3.5.19.1. Ran the upgrade process on Staging twice. Also `php craft utils/repair/section-structure` did not seem to help. My Section propagation setting change is the same as @i-just.

Would you recommend I also do the steps you mentioned above?

**Comment by brandonkelly** [comment]
@shoored Had you already made the Propagation Method change, before updating to 3.7.12+?

**Comment by shoored** [comment]
@brandonkelly Actually, no, only after the upgrade did I make that change.

**Comment by brandonkelly** [comment]
@shoored Then no, you shouldn’t have to do anything special. If you can send your `composer.json` + `composer.lock` files and a database backup (ideally from before you made the change) over to support@craftcms.com and point out which section you changed, we can look into it from there.

**Comment by brandonkelly** [comment]
@shoored Got that fixed for the next release. If you want to patch your structure up, follow the same instructions as [before](https://github.com/craftcms/cms/issues/9782#issuecomment-912105646).

**Comment by brandonkelly** [comment]
Craft 3.7.14 is out now with that fix.
