### ISSUE TITLE
Resaving entry in cp takes very long (~30sec)

### ISSUE THREAD

**Issue by FabioIaderosa** [craftcms/cms#9789]
### Description
Saving an entry takes about 30 to 60 seconds with a lot of duplicated queries (262 duplicated queries found out of 545). Most SELECT `id`, `parentId`, `volumeId`, `name`, `path`, `uid` FROM `craft_volumefolders` .....

Most duplicated queries come from craft_volumnfolders table.

in the queue.log we found the following lines, which gets repeated for the next ~30sec. 
Updating the search index and stoping it right away (time.: 0.081s) 5:34 2021-09-02 17:25:54 [-][101][-][info][craft\queue\QueueLogBehavior::afterExec]  [915959] Aktualisiere Suchindexe (attempt: 1, pid: 26012) - Done (time: 0.044s)
2021-09-02 17:25:54 [-][101][-][info][craft\queue\QueueLogBehavior::beforeExec]  [915961] Aktualisiere Suchindexe (attempt: 1, pid: 26012) - Started
...

### Steps to reproduce
1. Save an entry in the control panel

### Additional info
- Craft version: 3.7.10
- PHP version: 7.4.23
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Expanded Singles 1.1.4, Neo 2.11.9, Freeform 3.11.10, Redactor 2.8.8, Redirect Manager 1.1.1, SEOmatic 3.4.5, Sprig 1.8.1,

**Comment by brandonkelly** [comment]
We are looking into a Neo-related performance issue (https://github.com/spicywebau/craft-neo/issues/496), which may be related to your performance issue. Subscribe there to follow along.

**Comment by turnstylerj** [comment]
It sounds like people are experiencing this issue with matrix fields as well ([here](https://github.com/spicywebau/craft-neo/issues/494#issuecomment-912588831) and [here](https://github.com/spicywebau/craft-neo/issues/496#issuecomment-908281940)). Both linked tickets in the Neo repo are closed, seems like this should maybe be re-opened.

**Comment by edwwaarrdd** [comment]
@brandonkelly Hey I think I also send a message to support regarding the same issues.
What @turnstylerj says is correct. Seems like everyone is closing the issues regarding this.
So it's not really clear on where we can follow along for progress on this issue, as it makes some actions in the control panel unbearably slow and sometimes also crashes the control panel.

**Comment by Harry-Harrison** [comment]
I've also got clients concerned and it's managed to bring a shared staging server to a halt with the issue.

**Comment by turnstylerj** [comment]
I was able to repro this on a fresh test install with no plugins and matrix blocks alone. Submitted a new issue with some more information, hope it's helpful! https://github.com/craftcms/cms/issues/9802

**Comment by brandonkelly** [comment]
For posterity, Craft 3.7.12 is out now with some performance improvements for saving entries (per #9802). If it’s still too slow, you may want to consider disabling draft autosaving, by setting the [autosaveDrafts](https://craftcms.com/docs/3.x/config/config-settings.html#autosavedrafts) config setting to `false`, which will basically return Craft to pre-3.7 behavior except when Live Preview is open.
