### ISSUE TITLE
Display sub folders in Asset tables

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#979]
> Created by: Mats Mikkel Rummelhoff (mail@mmikkel.no) on 2015/03/09 00:12:31 +0000
> Votes at time of UserVoice import: 6

-----------------------------------

It'd be nice if clickable sub folders were displayed above files in the Asset tables.

It'd be a boost to usability, particularly in cases where you have folders with no files, only sub folders.

See attached file for mockup.

**Comment by khalwat** [comment]
I *think* this issue is what I'm looking for. Basically, clients can never seem to find the sub-folders for Assets, that little `>` just doesn't seem to be enough of a visual cue.

Something like this by default, or as a setting would be nice:

https://github.com/nystudio107/disclosedassets

**Comment by brandonkelly** [comment]
@khalwat Similar, but this issue is requesting the folders to show up in the main element index table/grid view (alongside the files). You’re looking for #1842, which is already resolved for Craft 3.

**Comment by rungta** [comment]
Clients struggle with discovering and accessing asset subfolders on every single site we deploy. And this is even after making them aware of the `>` icon and the right-click for "New subfolder" actions.

**Comment by benface** [comment]
I was going to create this exact issue, when I saw this one from ~2017~ 2015. This would be awesome:

![folders](https://user-images.githubusercontent.com/1059139/53703024-19b5fc80-3ddb-11e9-8c0b-f3f3cf85642b.jpg)
