### ISSUE TITLE
Released queue jobs still run

### ISSUE THREAD

**Issue by davist11** [craftcms/cms#9790]
### Description

We have a background worker setup to process the queue and is running the `./craft queue/listen` command. It's running jobs no problem. We have some very long jobs (importing data from a third party system) that sometimes we want to release so that we can have a different job run, but it appears like the released job still continues to run until completion (or error). Does the release method need to do something more to halt the execution of the job aside from just deleting the record from the DB?

### Steps to reproduce

1. Setup a background worker to listen and process the queue
2. Start a very long job (our job logs a message, so we can tell it's still running)
3. Release the job
4. See that the job is still running

### Additional info

- Craft version: 3.6.18
- PHP version: 7.4.23
- Database driver & version: MySQL 8.0.23
- Plugins & versions:

<table class="data fullwidth fixed-layout" dir="ltr">
            <tbody>
                                    <tr>
                        <th class="light">Amazon S3</th>
                        <td>1.2.11</td>
                    </tr>
                                    <tr>
                        <th class="light">Asset Rev</th>
                        <td>6.0.2</td>
                    </tr>
                                    <tr>
                        <th class="light">Avatax</th>
                        <td>2.1.6</td>
                    </tr>
                                    <tr>
                        <th class="light">Classnames</th>
                        <td>1.0.3</td>
                    </tr>
                                    <tr>
                        <th class="light">Command Palette</th>
                        <td>3.1.4</td>
                    </tr>
                                    <tr>
                        <th class="light">Craft Commerce</th>
                        <td>3.3.0.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Feed Me</th>
                        <td>4.3.5.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Imgix</th>
                        <td>2.1.0</td>
                    </tr>
                                    <tr>
                        <th class="light">Linkit</th>
                        <td>1.1.12.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Navigation</th>
                        <td>1.4.14</td>
                    </tr>
                                    <tr>
                        <th class="light">Postie</th>
                        <td>2.4.7</td>
                    </tr>
                                    <tr>
                        <th class="light">Ray</th>
                        <td>1.1.4</td>
                    </tr>
                                    <tr>
                        <th class="light">Redactor</th>
                        <td>2.8.5</td>
                    </tr>
                                    <tr>
                        <th class="light">Retour</th>
                        <td>3.1.53</td>
                    </tr>
                                    <tr>
                        <th class="light">Scout</th>
                        <td>dev-master</td>
                    </tr>
                                    <tr>
                        <th class="light">SEOmatic</th>
                        <td>3.3.41</td>
                    </tr>
                                    <tr>
                        <th class="light">Stripe for Craft Commerce</th>
                        <td>2.3.2.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Style Inliner</th>
                        <td>2.3.0</td>
                    </tr>
                                    <tr>
                        <th class="light">Super Table</th>
                        <td>2.6.7</td>
                    </tr>
                                    <tr>
                        <th class="light">Table Maker</th>
                        <td>2.0.1</td>
                    </tr>
                            </tbody>
        </table>

**Comment by brandonkelly** [comment]
It’s not possible to halt the execution of an already-running job, short of terminating the PHP process (something Craft can’t do). Releasing a job just prevents it from getting picked up in the future.

**Comment by clarknelson** [comment]
So we can't add a "cancel queue" job like in the dashboard?

![Screenshot from 2022-01-09 17-46-23](https://user-images.githubusercontent.com/4106671/148708054-5c6455eb-5a26-4dc2-89a6-b7e12498a485.png)

My queue manager page will 504 on long tasks, it would be nice to quit them from the CLI.
