### ISSUE TITLE
Validation Errors for Related fields on Category

### ISSUE THREAD

**Issue by magnessjo** [craftcms/cms#9796]
### Description

A system error is presented when users save a category entry containing an image field with validated related assets turned on.  

On an entry, the UX guides the user to the issue.  

Note: this could be an enhancement, but I set it as a bug since the behaviors between entry types are different.  

<img width="399" alt="Screen Shot 2021-09-03 at 2 50 52 PM" src="https://user-images.githubusercontent.com/856595/132053419-aaae0166-7934-4e60-b3fc-2a573643ba92.png">
<img width="190" alt="Screen Shot 2021-09-03 at 2 50 13 PM" src="https://user-images.githubusercontent.com/856595/132053421-5953338a-5528-4220-a132-896a6baabf76.png">

### Steps to reproduce

1.  Set a required field on asset
2. Add the field to a category entry with validated related turned on
3.  Try and save an entry without filling in the field 

### Additional info

- Craft version: 3.7.11
- PHP version: 8
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
This will happen if the “Validate related assets” setting is enabled on your Assets field. It is a way of ensuring that the asset meets its minimum content requirements (e.g. required Alt Text field) before it can be related to other elements via that field.

**Comment by magnessjo** [comment]
@brandonkelly, thanks.  My question is the experience is different between categories and entries.  Entries provides a good UX that informs the user that validation error occurs (see 2nd screenshot).  For categories, the UX experience isn't the same (or ideal).  It just states that the category couldn't saved (see first screenshot).  Ideally, these two experiences should be the same right?

**Comment by brandonkelly** [comment]
@magnessjo Sorry I guess I missed that.

**Comment by brandonkelly** [comment]
Sorry, following you now. Just fixed this for the next release. Thanks for reporting!

**Comment by magnessjo** [comment]
No problem @brandonkelly!  I should have provided better images for example.  Thanks again!

**Comment by brandonkelly** [comment]
Craft 3.7.12 is out now with that fix. Thanks again!
