### ISSUE TITLE
Search doesnt work for labels of dropdowns, only values

### ISSUE THREAD

**Issue by mikemeadeuk** [craftcms/cms#9799]
When a dropdown field is set to "Use this field’s values as search keywords", it only adds the value to the index and not the label. this can be confusing as the label is shown in the control panel but nothing is return of your search for it.

example:

dropdown item label is set to " Network Cam", value is "networkCam"

searching for "network cam" returns nothing.

**Comment by brandonkelly** [comment]
Fair enough, just made that change for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.12 is out now with that change.

Note that you will need to re-index your entries before the change will take effect. You can do by running this command:

```bash
> php craft resave/entries --section=mySectionHandle
```

**Comment by mikemeadeuk** [comment]
I think this fix may have broken feedme, when a dropdown field is used and is checked to use search indexes, the import fails with:

Attempt to read property "value" on string - BaseOptionsField.php: 327.

If i turn off seachable indexes for the dropdown field, the import works again.

**Comment by brandonkelly** [comment]
@mikemeadeuk I’m not able to reproduce that. Can you please send your `composer.json` + `composer.lock` files, a database backup, and a feed data file over to support@craftcms.com? We can try to reproduce it from there.
