### ISSUE TITLE
Can not paste value from clipboard to the numeric input field with Ctrl+V shortcut

### ISSUE THREAD

**Issue by julpat** [craftcms/cms#9803]
### Description
On OSX with Cmnd+V it's working fine, but on Windows Ctrl+V, no matter what browser I am using, is not. Probably because of javascript which is blocking typing different characters than numbers (and `.,- `).

Context navigation (right-click) paste option is working fine.

### Steps to reproduce

1. Create a numeric field
2. Copy to clipboard whatever value (number, text)
3. Try to paste with Ctrl+V on Windows the value into the input field

### Additional info

- Craft version: 3.7.10
- PHP version: 7.4.6
- Database driver & version: MySQL 8.0.21

Plugins & versions:
- Guest Entries 2.4.0
- Guest Entries Notification 1.0.1
- Mailgun 1.4.3
- Neo 2.11.9
- Redactor 2.8.8
- Sprout Email 4.4.10

**Comment by brandonkelly** [comment]
Just released Craft 3.7.12 with a fix for this. Thanks for reporting!
