### ISSUE TITLE
Craft 3.7.12 contains breaking change

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#9811]
### Description
Also posted it in the repo for SEOmatic, because I don't know where it exactly belongs. But it seems Craft 3.7.12 has a breaking change.

https://github.com/nystudio107/craft-seomatic/issues/974

After upgrading from 3.7.11 to 3.7.12 in the context the index 'category' is missing. Feel free to close if it's purely a plugin issue, but since it's a minor version change I think something might have changed that wasn't intended.

![Schermafbeelding 2021-09-09 om 09 55 57](https://user-images.githubusercontent.com/23024452/132646363-31a6d274-5b4f-43cd-88b2-6e4a95136594.png)

**Comment by brandonkelly** [comment]
Just fixed that for the next release. 
To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.12"` and run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.7.13 is out now with that SEOmatic compatibility fix.
