### ISSUE TITLE
Issue with emoji and searchindex

### ISSUE THREAD

**Issue by jlachancekffein** [craftcms/cms#9813]
### Description
A problem arises when the search index tries to insert emojis.

Specifically, in Craft Commerce, the **commerce_addresses** table contains the **notes** field. In my case, this field can contain emoji. Example:: love_you_gesture :: tone_light:

The problem is, during a query, the response crashes because the search index tries to insert this information into the **searchindex** table.

The solution in my opinion would be to simply not decode it before inserting it into the **searchindex** table.

In the meantime, I don't have the option in Craft Commerce not to index this field.

### Error example

`
The SQL being executed was: INSERT INTO searchindex (elementId, attribute, fieldId, siteId, keywords) VALUES (172959, billingaddresslines, 0, 1, [[address line hidden]] 🤟🏻  )' WHERE id=916953
`

### Additional info

- Craft version: 3.7.11
- PHP version: 7.3

**Comment by brandonkelly** [comment]
Just fixed this for the next release. Now all emoji are going to be stripped out of indexed search keywords.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.12"` and run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.7.13 is out now with that fix.
