### ISSUE TITLE
Add an Element fieldtype

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#982]
> Created by: Mats Mikkel Rummelhoff (mail@mmikkel.no) on 2015/03/09 00:12:31 +0000
> Votes at time of UserVoice import: 6

-----------------------------------

I often have the need to select elements from multiple Element Types in a single field (i.e.; a grid of "featured" content, which can be entries, images/videos, category listings etc).

Obviously, the ElementsService is hard wired to only pull elements from a single Element Type, so I realize this might be difficult to pull off (also; not sure how the UI for the element selector modal should look), but it'd be awesome to have an Element FieldType that allowed selection of elements from multiple Element Types.

My current workaround is using a Matrix field, but it has its drawbacks – chief among them is not being able to select multiple elements at once.

**Comment by brandonkelly** [comment]
duplicated of #1125
