### ISSUE TITLE
Applying a revision doesn't change the UI and entry status

### ISSUE THREAD

**Issue by peimansh** [craftcms/cms#9821]
### Description
When applying an old revision to the entry, the status popup is showed that "The revision has been applied successfully" and disappears. But the "Revert entry to this revision" button is still there and doesn't change the entry status to current. So it still shows the Revision page (Which is already been applied and is the current "current") which is really confusing and if the user misses the popup he wouldn't know if the revision has been applied or not. Not sure if this is expected or not but I guess the right approach would be to change to current entry page after successful revision applied.

### Steps to reproduce

1. Open an entry
2. Open an older revision of the entry
3. Apply the revision
4. After successful apply, the page doesn't change/update and still shows "Revert entry to this revision" button

### Additional info

- Craft version: 3.7.12
- PHP version: 7.4

**Comment by peimansh** [comment]
And another bug that I just noticed now is that applying different revisions, like applying and changing between two different revisions back and forth, causes the CMS to create additional duplicate revisions!
Isn't the process to suppose just to change "current" to the selected revision ? So why applying a previous revision to current, creates a new revision? I guess this is totally unnecessary as it only results in a growing list of revisions which are basically the same and unnecessary load for DB.

**Comment by brandonkelly** [comment]
The bug here was that, after reverting a prior revision, the URL wasn’t redirected back to the entry’s new-Current revision. That’s fixed now.



> And another bug that I just noticed now is that applying different revisions, like applying and changing between two different revisions back and forth, causes the CMS to create additional duplicate revisions!

That’s expected. There could be other changes, such as new sites added to the entry, which aren’t fully covered by the revision, so instead of simply rolling back time to the prior revision, the revision’s changes are merged into the current entry settings/content, and a new revision is created in the process.

**Comment by peimansh** [comment]
Thanks @brandonkelly , That makes sense.

> so instead of simply rolling back time to the prior revision, the revision’s changes are merged into the current entry settings/content, and a new revision is created in the process

In this case I'd personally prefer some other label for the button though instead of saying "Revert entry to this revision" as the current label gives this feeling that everything in the entry will be reverted back to the state where it has been in that revision. Something like "Merge changes from this revision" or "Apply this revision" would make more sense.

**Comment by brandonkelly** [comment]
Yeah that’s probably a good call. Just made that change for Craft 4 (dae2ad07fbb9e6b897b4fe3fd839e2a07a7ed580).
