### ISSUE TITLE
Suppressed error in Asset.php hides actual error

### ISSUE THREAD

**Issue by chrismou** [craftcms/cms#9824]
### Description

`/path/to_project/vendor/craftcms/cms/src/fields/Assets.php`
Method: `_resolveVolumePathToFolderId`
Line 810 (as of 3.7.11)

Error message with description of the problem is caught, and re-thrown with a somewhat more cryptic error

Saving a commerce Variant, a CLI job kept erroring out with the following exception:

```
Error: The Images field’s Asset Location setting has an invalid subpath (“products/{id}”)
```

This was only happening on the staging server, so after a while following the code I traced it to the line mentioned above. The actual error was:

```
Unable to write in the cache directory (/path/to/project/storage/runtime/compiled_templates/4b)
```

Which once tracked down was a fairly simple fix!

### Steps to reproduce

1. Change permissions of contents of `storage/runtime/compiled_templates` to be unwritable
2. In CLI job: `$variant = Variant::find()->id(SOME_ID)->one();` followed by `Craft::$app->getElements()->saveElement($variant);`
3. 

### Additional info

- Craft version: 3.7.11
- PHP version: 7.3

**Comment by brandonkelly** [comment]
Thanks for pointing that out. Craft 3.7.13 is out now with a fix.
