### ISSUE TITLE
Virus scan sees malicious code in test file

### ISSUE THREAD

**Issue by medoingthings** [craftcms/cms#9826]
### Description
My website hoster contacted me, because it found "malicious code" in the following file (in multiple projects):
https://github.com/craftcms/cms/blob/3.7/tests/_data/assets/files/no-ihdr.png

### Steps to reproduce

I’ve checked it with another virus scanner, but that found nothing. The png seems to be broken though, it can’t be displayed, so there seems to be some kind of issue with it, that triggers their virus scanner.

### Additional info

- Craft version: 3.7.10
- PHP version: 7.4
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
That file is used in a test case, to ensure that Craft correctly cannot determine its file type, due to being corrupt.
