### ISSUE TITLE
Assets relocating in draft state to volumes via the upload file button

### ISSUE THREAD

**Issue by leightonhughes** [craftcms/cms#9827]
### Description

In relation to #9619

What I've found is if I save the draft entry first and then add an image via the "Upload a file" button as opposed to "Add an asset" button the asset goes to the correct volume even in the draft state. Is this correct functionality or should it be going to the temp folder? If I try by the "Add an asset" button it stays in the temp folder.

In my scenario this is causing workflow to fail when a publisher approves as the image is still in temp, but in some cases it also gets approved with editors adding assets via the "Upload a file" button.

### Additional info

- Craft version: 3.7.12
- PHP version: 7.4.23
- Database driver & version: MySQL 5.7.35
- Plugins & versions: Workflow 1.6.2

**Comment by brandonkelly** [comment]
Do you have the **Restrict assets to a single folder** Assets field setting checked?

If you don’t, then the only time the **Default Asset Location** setting is used is when you use the Upload button (or drag a file directly onto the field).

**Comment by leightonhughes** [comment]
Yes the restrict assets setting is checked.

**Comment by andris-sevcenko** [comment]
Pretty sure we resolved this over Discord, @leightonhughes!
