### ISSUE TITLE
Edit page scrolls to top when entering Preview

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#9828]
### Description

Entering Preview always scrolls the edit page to the top, rather than retaining the browser's current scroll position. Not sure if this would be considered a bug or a FR, but if possible it'd be great if the scroll position was retained as the users enters and leaves Preview.

### Steps to reproduce

1. Open an entry's edit page. Scroll down a bit, so the header (with the Preview and Save buttons) are fixed and overlaying the edit page content
2. Click the Preview button and notice that the edit page jumps to the top before Preview opens

### Additional info

- Craft version: 3.7.12
- PHP version: 
- Database driver & version:
- Plugins & versions: None

Reproducable on Edge 93.0.961.38, macOS Big Sur 11.5.2

**Comment by brandonkelly** [comment]
In order for Craft to retain the scroll position, one of these must be true:

- The `useIframeResizer` config setting is enabled
- The preview target URL uses the same host name as the main window

Are either of those the case?

**Comment by mmikkel** [comment]
Yes, the second one – the preview target URL uses the same host as the main window.

To be clear, I'm not referring to Craft retaining the scroll position for the actual Preview iframe – that works fine. I'm talking about the actual edit page being scrolled to the top when the preview button is clicked:


https://user-images.githubusercontent.com/298510/133336378-5efd4513-698c-4981-87df-e6f386fa5788.mp4

**Comment by brandonkelly** [comment]
Ahhh, sorry for the misunderstanding. Just released 3.7.13 with a fix for that.

**Comment by mmikkel** [comment]
Awesome, thank you!
