### ISSUE TITLE
Very slow GraphQl queries (5-50+seconds)

### ISSUE THREAD

**Issue by cankahya** [craftcms/cms#9830]
### Description
GraphQl queries take a long time. Even a very simple query, e.g.:

`
query {
	entry(slug:"entryslug") {
    id
  }
}
`

takes about 5-7 seconds on average. A complex query even takes around 21 seconds. Sometimes the requests even take up to a minute to respond. I disabled graphql caching to make this reproducable.

The craft instance has around 1100 entries and three languages. Also, there are quite a lot of fields, populating the entries.
But even very simple queries take a huge amount of time.

Another craft installation on the same web server does'nt show this behavior: there, the same query takes only 200-300 milliseconds.

I've already found [https://craftcms.com/knowledge-base/why-is-my-site-slow](url).
Using the Craft Debugger, I am seeing a lot of subsequential queries being made. But I don't know where to start looking at.
As we are using craft for most of our projects and the projects also grow constantly, it would be super important to understand why this slow-down is happening.

Any help would be greatly appreciated.
Thanks,
Can

### Additional info

- Craft version: 3.7.12
- PHP version: 7.4.12
- Database driver & version: MySQL 5.7.32
- Plugins & versions:
nethooks	1.1.2
Redactor	2.8.8
Super Table	2.6.8

**Comment by andris-sevcenko** [comment]
That's odd. Are you in a position where you could run a Blackfire.io profiler and see what the holdup is?

**Comment by cankahya** [comment]
I didn't use Blackfire.io before but I just installed it and to run the profiler (together with craft run locally) and got some results. Not sure what to make of it, but it looks like there are way too many sql commands being executed. 

E.g. yii\base\Event::trigger being quite deep in the call-tree seems to be executed 17193 times... I have no real insight in the craftcms internals but that seems waaaay too much for a query that simple :)

Here is the link the the Blackfire.io profiler result:
https://blackfire.io/profiles/91b1328e-1525-414a-8a18-3f8a91364da0/graph

Can you make good sense of it?

**Comment by andris-sevcenko** [comment]
How many different entry types do you have? In other words, how complex/big is your content model?

**Comment by cankahya** [comment]
It's definetly the most complex site we have built with craft so far. And we have built quite a lot during the last years (Thanks for the amazing work on craft by the way :)

So the site has 21 different Sections with 25 different Entry Types. There are approximately 130 Fields. And three sites (languages).

So yes, it's pretty complex I'd say. Do you think that is the reason? Could this be too much complexity for craft?

**Comment by andris-sevcenko** [comment]
Okay, so the complexity is contributing to it, but, looking at the profiling results, I see where we can definitely improve things. I'll get some improvements in place and I'll let you know how to try them out.

For some background - for every query executed, the GraphQL schema needs to be generated for query validation purposes. Unfortunately, the generated schema cannot (should not?) be cached, due to reasons [explained here](https://github.com/craftcms/cms/discussions/8968).

**Comment by cankahya** [comment]
That's very interesting, thank you!! After reading the other thread, I start understanding the problem.

Some improvements sound amazing, I'm more than happy to try anything :)

**Comment by cankahya** [comment]
Just to throw in some more meat, that may give more insights:
I just made the observation, that deleting an unused field (reproducibly) also takes about a minute to be executed. Here is the Blackfire profile for the request: 
https://blackfire.io/profiles/25400357-1088-4db4-bf63-6634933f0b5d/graph

We also have observed craft actions sometimes take a long time, like saving a new entry. 
So the problem doesn't seem to be limited only to GraphQl. Let me know if more profiling helps :)

**Comment by andris-sevcenko** [comment]
@cankahya I pinged you on Craft CMS Discord to follow up a little bit on this issue.

**Comment by andris-sevcenko** [comment]
This has been [fixed](https://github.com/craftcms/cms/commit/1036aadd91fb7db62543381a84e532f391690067) as of Craft 3.7.14
