### ISSUE TITLE
Email has already been taken

### ISSUE THREAD

**Issue by jerome2710** [craftcms/cms#9835]
### Description
After receiving some questions about users being unable to save their account, we started digging what could be wrong. They were reporting messages of "Email X has already been taken", which would be triggered if there already is an account for that e-mail address. Picking some e-mail addresses of these reports, all of them are having more than 1 account.

Running the following query:

```sql
SELECT email, COUNT(*) AS count FROM craft_users GROUP BY email HAVING count > 1
```

we found out that 75 e-mail addresses have more than 1 account. Some even having up to 6. Some of these accounts were not yet activated through the confirmation e-mail and having the status "pending", some were (all) already activated. Some were all created within the hour, some over the course of multiple days/months. Some were created back in 2019, some were created this week.

We are only having one user registration page. When trying to register myself twice before clicking the first confirmation email, I already receive the error message. Our registration page (minus some styling) looks like this:

```twig
<form method="post">
	{{ actionInput('users/save-user') }}
	{{ redirectInput('register/check-email') }}
	
	<input id="email" type="email" name="email" required="required"{%- if user is defined %} value="{{ user.email }}"{% endif %}>
	
	<input id="password" type="password" name="password" required="required">
	
	<input id="confirm-password" type="password" name="confirm-password" required="required" data-bouncer-match="#password">
	
	<input type="checkbox" id="termsConditions" name="termsConditions" required="required">
	
	<input type="checkbox" id="newsletter" name="newsletter">
	
	<input type="checkbox" id="partners" name="partners">
	
	<button type="submit">
		Register
	</button>
</form>
```

I am unsure where to start. We are having a few plugins and custom modules enabled which are narrowly integrated in the website. I am unable to reproduce this issue at the moment, which is essential before I could start stripping them out to narrow down the cause. Does anyone have a clue? Does some user-status allow the user to register under the same e-mail address twice?

### Additional info

- Craft version: Craft Pro 3.7.10
- PHP version: 7.2.34
- Database driver & version: MySQL 5.5.68
- Plugins & versions:
    - Advanced Url Field	1.0.0
    - Asset Rev	6.0.2
    - Commerce Product Bundles	dev-develop-v2
    - Control Panel CSS	2.3.1
    - Craft Commerce	3.4.2
    - Expanded Singles	1.1.4
    - Gift Voucher	2.6.1
    - Image Resizer	2.1.0
    - Inventory	2.1.1
    - Mollie for Craft Commerce	3.0.0
    - Neo	2.11.7
    - Position Fieldtype	1.0.17
    - Read-only Field	1.0.1
    - Redactor	2.8.8
    - Relabel	2.0.2
    - Sentry Logger	1.1.7
    - SEOmatic	3.4.2
    - Sprout Forms	3.13.7
    - and various custom modules

**Comment by brandonkelly** [comment]
Check the `dateDeleted` column on these duplicates. Craft will only validate email uniqueness against other users where `dateDeleted` is still set to `NULL` (not yet deleted).

**Comment by jerome2710** [comment]
> Check the `dateDeleted` column on these duplicates. Craft will only validate email uniqueness against other users where `dateDeleted` is still set to `NULL` (not yet deleted).

@brandonkelly, our `craft_users` table does not have a `dateDeleted` column. Are you referring to the `craft_elements` table? All corresponding rows have `NULL` values.

All duplicate users are also showing up in the CP users overview.

**Comment by brandonkelly** [comment]
Sorry, yes, that’s what I meant.

How are these users getting registered in the first place? From the control panel, a front-end registration form, or some other way (e.g. Freeform)?

**Comment by jerome2710** [comment]
No worries! The users are registering theirselves through a single front-end registration. I have added a stripped version (without styling) of the registration form in the original post.

**Comment by brandonkelly** [comment]
Are you able to consistently register new users with an existing email address?

**Comment by jerome2710** [comment]
> We are only having one user registration page. When trying to register myself twice before clicking the first confirmation email, I already receive the error message.

This was also mentioned in the original post. I am unable to reproduce this issue by registering myself more than once.

**Comment by brandonkelly** [comment]
What about using one of the emails that already have multiple user accounts? (You could test locally with the [testToEmailAddress](https://craftcms.com/docs/3.x/config/config-settings.html#testtoemailaddress) config setting set to your own email address, so if it works, the email notification is sent to your own email address instead.)

**Comment by jerome2710** [comment]
I tried a few, but this will also result in the error "Email X has already been taken" on our registration page. It's strange, I'm not sure whether it's caused by specific e-mail addresses / accounts, specific input or maybe even users submitting the form more than once...

I understand this is a rather difficult issue to solve as we are unable to reproduce it until now. It does seem to be an ongoing issue which is causing us trouble. Please do let me know if there is anything else I could check.

**Comment by brandonkelly** [comment]
Without some way to reproduce it, there’s not much here for me to go on. We haven’t seen any other reports of this happening, and I’m not seeing any way for it to happen. My best guess is that either these duplicate users were created during an import, or if it’s ongoing, then there may be some plugin/module code that is causing it.

Maybe you can follow up with some of the users that have multiple accounts, and ask if they have any thoughts.

**Comment by brandonkelly** [comment]
We’ve found the culprit for this while investigating #10661. Fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 3.7.37 is out with this fix.
