### ISSUE TITLE
Column suffix appears to be inconsistently present in content tables

### ISSUE THREAD

**Issue by jlawrence-yellostudio** [craftcms/cms#9836]
### Description

In some cases my fields in the content tables have column suffixes and others they do not. In third party fields (supertable) it appears to be occasionally removing the column suffix for no reason. Note that I've observed this behaviour several times and it does appear to happen more commonly with supertable (@engram-design). But please note that in my screenshots you can see that field_summary in the content table has no column suffix.

Apologies that this is not a very definitive report as I've not figured out what is causing it yet. I've attached a couple of screenshots.

![Screenshot 2021-09-15 at 12 44 34](https://user-images.githubusercontent.com/5747299/133427658-cfb8893f-123d-41ba-820c-5b1957375619.png)

![Screenshot 2021-09-15 at 12 39 20](https://user-images.githubusercontent.com/5747299/133427715-e32cb99e-90ae-4d17-9b7b-ba722e5e3dd1.png)

![Screenshot 2021-09-15 at 12 44 59](https://user-images.githubusercontent.com/5747299/133427743-70cd8494-7408-493e-81c1-e95ca24e56bc.png)

### Steps to reproduce

1. I added a new field to a supertable block and it wiped out the column suffix, it has happened several times, however this doesn't seem to be happening very consistently.

### Additional info

- Craft version: 3.7.12
- PHP version: 7.4.21
- Database driver & version:
- Plugins & versions: super-table 2.6.8

**Comment by brandonkelly** [comment]
If this is only happening in Super Table DB tables, then it must be a Super Table issue.

Worth mentioning that column suffixes should only be added to _new_ field columns; not any that predate Craft 3.7.
