### ISSUE TITLE
Re-usable Field Layouts

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#984]
> Created by: Besim (besim@40digits.com) on 2015/12/28 20:18:27 +0000
> Votes at time of UserVoice import: 6

-----------------------------------

I come from using Advanced Custom Fields in the WP environment, and one feature that was great about ACF was being able to define the templates a field grouping would/can show on.

Take Craft for example. I have a grouping of fields that when combined form the banner "field layout" for a section. However, that "field layout" can be used on multiple other sections and even single pages. Without me having to re-create it on every single or section, is there a way that's much more efficient?

I am also using the Reasons plugin https://github.com/mmikkel/Reasons-Craft which enables me conditional fields. And I believe this is where the efficiency concerns are coming from. Because I am having to set the conditionals on each field layout. And if I decide to change something, I will need to change it across all other field layouts.

**Comment by brandonkelly** [comment]
Seems like this would be addressed by #1524
