### ISSUE TITLE
Slow asset uploading to volume with 20+ records

### ISSUE THREAD

**Issue by BrandonJamesBorders** [craftcms/cms#9840]
### Description
Have a S3 Volume with 20k+ assets and growing. When I upload a file to it the execution time can take 30+ seconds. Using the debugger I can see the bulk of the time is down to this query. 

![Screen Shot 2021-09-15 at 7 45 29 PM](https://user-images.githubusercontent.com/6044898/133527729-04e1908f-e409-48f1-a9e4-5c942ffb821c.png)

When I execute the same query when connected to the database through Navicat (MySQL GUI) the same query takes 1.5s to 2s.

This happens locally too (still using an S3 Volume). 

### Steps to reproduce

1. Load up a volume with 20k plus assets
2. Upload a file and observe slow processing. 

### Additional info

- Craft version: 3.4.23
- PHP version: 7.2.33
- Database driver & version: MySQL 5.7.28
- Plugins & versions: Amazon S3	1.2.11

**Comment by brandonkelly** [comment]
That query was improved in Craft 3.4.26. Can you please try updating, at least to 3.4.30 (the latest 3.4 release)?

**Comment by BrandonJamesBorders** [comment]
@brandonkelly Much improved indeed! Thanks for the response.
