### ISSUE TITLE
DraftEditor.js promise rejection not caught

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#9841]
### Description

`checkForm` calls `saveDaft` but doesn't handle promise rejection

Call: https://github.com/craftcms/cms/blob/develop/src/web/assets/cp/src/js/DraftEditor.js#L673
Rejection: https://github.com/craftcms/cms/blob/develop/src/web/assets/cp/src/js/DraftEditor.js#L696-L698

- Craft version: 3.7.13
- PHP version: 8

**Comment by brandonkelly** [comment]
Fixed for the next release!

**Comment by leevigraham** [comment]
Thought it would be an easy one to clear up.

**Comment by brandonkelly** [comment]
Craft 3.7.14 is out now with that fix.
