### ISSUE TITLE
Block Type in Matrix field (with SuperTable) Gets Erased On Field Settings Edit

### ISSUE THREAD

**Issue by cakleimeier** [craftcms/cms#9848]
### Description
I have a Matrix field called Columns. It has a Max Blocks setting of 3. It has one block type, Column. In Column, there is a SuperTable field, Column Links. In Column Links, there is a LinkIt field, Column Link. When I attempt to edit the Max Blocks setting (_by increasing it to 4_), the block type, Column, and all its subfields disappear.

In the `web.log` file, I see this error 6 times, with a varying `SAVEPOINT LEVEL` for each error:
```
2021-09-17 08:42:53 [-][49041][uh76f5qp0gf3hmq8dh4e1pirio][warning][craft\db\mysql\Schema::releaseSavepoint] Tried to release a savepoint, but it does not exist: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT LEVEL4 does not exist
The SQL being executed was: RELEASE SAVEPOINT LEVEL4
```

#### A bit more background
This database is being carried over from an earlier version of the project and has been a problem the entire time. It's unusually slow, plugins will occasionally uninstall themselves for seemingly no reason, and so on. We do not make use of project config or GraphQL, but the previous version did use the Element API. The current code does not, and we don't have that plugin installed. I'm not sure if this information will be helpful, but it seemed potentially relevant. 

Finally, the Columns field is only used in a Global Set.

### Steps to reproduce

1. Set up a field that is a Matrix containing a SuperTable containing a LinkIt field, with a limit of 3 Matrix blocks
2. After field is saved, go into field settings, edit Max Blocks, save
3. The block type and all its information is erased.

### Additional info

- **Craft version**: 3.7.13
- **PHP version**: 7.3.7
- **Database driver & version**: MySQL 5.7.2.6
- **Plugins & versions**:
```"craftcms/aws-s3": "1.2.15",
"craftcms/cms": "3.7.13",
"craftcms/feed-me": "4.4.0",
"craftcms/redactor": "2.8.8",
"doublesecretagency/craft-cpcss": "2.3.1",
"doublesecretagency/craft-inventory": "2.1.1",
"fruitstudios/linkit": "1.1.12.1",
"mmikkel/cp-field-inspect": "1.2.5",
"mustasj/expanded-search": "1.3.7",
"nystudio107/craft-minify": "1.2.10",
"nystudio107/craft-retour": "3.1.61",
"nystudio107/craft-seomatic": "3.4.6",
"nystudio107/craft-twigpack": "1.2.15",
"presseddigital/colorit": "1.1.2.1",
"putyourlightson/craft-blitz": "3.10.3",
"spacecatninja/imager-x": "v3.5.2",
"vaersaagod/matrixmate": "1.2.7",
"verbb/super-table": "2.6.8"
```

**Comment by brandonkelly** [comment]
Any chance you can send your `composer.json` + `composer.lock` files and a database backup to support@craftcms.com?

**Comment by cakleimeier** [comment]
I'll do that; thanks!

**Comment by brandonkelly** [comment]
This appears to be the same root issue as #9660 – the `config/project/` folder contained out-of-date project config YAML, and that was being unexpectedly applied as part of the field-save operation.
