### ISSUE TITLE
Table field default values not working

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#9852]
### Description
The Table field's default values do not work (anymore).

### Steps to reproduce

1. Create a table field with default values and add it to an entry type
2. Create a new entry of that type, table field is empty

### Additional info

- Craft version: 3.7.13
- PHP version: 8.0.10
- Database driver & version: PostgreSQL 13.3
- Plugins & versions: -

**Comment by brandonkelly** [comment]
I was able to reproduce this with a Table field that wasn’t included in the primary entry type. Just fixed for the next release.

**Comment by boboldehampsink** [comment]
Nice find @brandonkelly. I was indeed using multiple entry types and this happenend on the non-primary one.

**Comment by brandonkelly** [comment]
Craft 3.7.14 is out now with that fix.

**Comment by carolineboeykens** [comment]
When we create a new entry the defaults are filled in, but after saving they are empty again:
<img width="787" alt="Screenshot 2022-02-28 at 11 23 06" src="https://user-images.githubusercontent.com/42932673/155966618-46501643-55e1-42aa-b5ec-f129809857b4.png">

**Comment by brandonkelly** [comment]
@carolineboeykens I just tested and the default row values are getting populated correctly for new entries.

Are you testing with freshly-created entries? That’s the only time the Default Values setting comes into play.

**Comment by carolineboeykens** [comment]
Hm weird, I tested it again and now it is working. Don't know what happened before.
Thank you for your answer! Sorry for the inconvenience!
