### ISSUE TITLE
Asset deleted when deleting an entry's matrix field block while using Entry::EVENT_BEFORE_DELETE in a custom module

### ISSUE THREAD

**Issue by ademers** [craftcms/cms#9853]
### Description

I have the following code in a custom module that deletes an entry's asset when deleting the entry:

```php
// Delete image files when entry is deleted
Event::on(
    Entry::class,
    Entry::EVENT_BEFORE_DELETE,

    function(ModelEvent $event) {
        /** @var Entry $entry */
        $entry = $event->sender;

        // Delete image files in DR Photos section
        if ($entry->siteId === '1' && $entry->section->handle === 'photos' && $entry->type->handle === 'photo') {
            /** @var Asset $asset */
            $asset = $entry->imageFile->one();
            Craft::$app->elements->deleteElement($asset);
        }
    }
);
```
However, while testing a new Matrix field that I added to the entry type, I noticed that the asset also gets deleted when I delete one of the Matrix field's blocks and resave the entry. I'm not sure if this is a bug or if I need to change my code. If the latter, please let me know what to change in my code.

### Steps to reproduce

1. Add above code to a custom module.
2. Create at least two blocks in a Matrix field.
3. Delete one of the Matrix blocks and resave the entry.
4. Notice that the asset has been deleted.

### Additional info

- Craft version: 3.7.11
- PHP version: 7.2.34
- Database driver & version: MySQL 5.5.5
- Plugins & versions: See screenshot: https://cln.sh/JwaFYXfuFQwEAQbR6SWo

**Comment by michaelrog** [comment]
One thing to check —just a hunch — Maybe the `sender` that's triggering the event is an autosaved draft or other non-canonical copy of the entry. Checking getIsCanonical() in your conditional would cover that.

i.e. you're going about your business, editing the entry, making changes... and Craft is saving those incremental changes as a draft... and then you Save the entry and Craft discards the draft(s).... and the `beforeDeleteEntry` event gets fired from the draft copy (which itself is an Entry object).

**Comment by michaelrog** [comment]
(In any case, try replacing your `deleteElement()` line with a debug breakpoint, and inspect the `$entry` object. You'll be able to see if it's canonical, saving, draft, revision, whatever.)

**Comment by brandonkelly** [comment]
As @michaelrog mentioned, the `EVENT_BEFORE_DELETE` event is going to get triggered for drafts and revisions, as well as normal entry deletes. So you should make sure you are working with a normal entry before deleting the assets:

```php
// Delete image files when entry is deleted
use craft\elements\Asset;
use craft\elements\Entry;
use craft\events\ModelEvent;
use craft\helpers\ElementHelper;
use yii\base\Event;

Event::on(
    Entry::class,
    Entry::EVENT_BEFORE_DELETE,

    function(ModelEvent $event) {
        /** @var Entry $entry */
        $entry = $event->sender;

        // Delete image files in DR Photos section
        if (
            !ElementHelper::isDraftOrRevision($entry) &&
            $entry->siteId == 1 &&
            $entry->section->handle === 'photos' &&
            $entry->type->handle === 'photo'
        ) {
            /** @var Asset $asset */
            $asset = $entry->imageFile->one();
            Craft::$app->elements->deleteElement($asset);
        }
    }
);
```

**Comment by ademers** [comment]
@brandonkelly Thank you! 🙏
