### ISSUE TITLE
Allowed memory size on autoload_static.php

### ISSUE THREAD

**Issue by ezawadzki** [craftcms/cms#9854]
### Description

Hi,

I started my new job and try to figure out why craft is slow, why upload not working. But know I am facing this issue :

Got 500 error on `/` or `/admin` url.
The only log I get is from apache :

`[Mon Sep 20 15:10:13.727352 2021] [php7:error] PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 36864 bytes) in /var/www/html/craft/vendor/composer/autoload_static.php on line 2742`

Of course, I tried to incread `memory_limit` without luck.

### Steps to reproduce

I don't know, I started my new job 3 days ago :)

### Additional info
Craft: 3.5.17.1
Yii : 2.0.38
Composer: 1.10.1 (upraded to 2.1.8)
php 7.4

Thanks for your help

**Comment by angrybrad** [comment]
If you put a `phpinfo.php` in public HTML folder with this as the contents:

    <?php phpinfo();

Then load yoursite.com/phpinfo.php and search for `memory_limit`, what is the value set to?

**Comment by ezawadzki** [comment]
@angrybrad 

Thanks for you suggestion : 2048MB

**Comment by angrybrad** [comment]
It should be `2048M` or `2G`, not `MB`. See the last note on this page: https://www.php.net/manual/en/faq.using.php#faq.using.shorthandbytes

Either way, that's a _ton_ of memory for a PHP request. If you set it to `512M` that should be enough for any Craft operation.

**Comment by ezawadzki** [comment]
thanks @angrybrad it works !
