### ISSUE TITLE
Redirect with array parameters won't work since Craft 3.6.18

### ISSUE THREAD

**Issue by drifteaur** [craftcms/cms#9857]
### Description

Craft's `craft\web\Controller::redirect()` method could take arrays as parameters, it's documented here, and I have been relying on it:

https://docs.craftcms.com/api/v3/craft-web-controller.html#public-methods

From the documentation:

     an array in the format of [$route, ...name-value pairs...] (e.g. ['site/index', 'ref' => 1]) 
     yii\helpers\Url::to() (opens new window) will be used to convert the array into a URL.

In Craft 3.6.18 `craft\web\Response::redirect()` was introduced, it will only allow strings for the `$url `parameter. Passing in array results in:

    TypeError
    Argument 1 passed to craft\helpers\UrlHelper::url() must be of the type string, array given, called in 
    [....]/vendor/craftcms/cms/src/web/Response.php on line 177

### Steps to reproduce

1. Have a controller action that redirects using an array for the first parameter, such as:

```
    public function actionTest() {
        return $this->redirect(['an/other/action', 'foo' => 'bar']);
    }
```

### Additional info

- Craft version: 3.7.13
- PHP version: 7.4

**Comment by brandonkelly** [comment]
Thanks for reporting that, and for the PR! Merged for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.14 is out now with that fix.
