### ISSUE TITLE
Migrations applying but project config won't apply

### ISSUE THREAD

**Issue by bengreenbank** [craftcms/cms#9860]
### Description
I'm upgrading from 3.6.17 3.7.13. There are 10 migrations to run, 8 from Craft and 2 from plugins. See below:
```
Total 8 new Craft migrations to be applied:
    - m210302_212318_canonical_elements
    - m210329_214847_field_column_suffixes
    - m210405_231315_provisional_drafts
    - m210602_111300_project_config_names_in_config
    - m210611_233510_default_placement_settings
    - m210613_145522_sortable_global_sets
    - m210613_184103_announcements
    - m210829_000000_element_index_tweak

Total 1 new Feed Me migration to be applied:
    - m210317_000000_search_indexes

Total 1 new SEOmatic migration to be applied:
    - m210817_230853_announcement_v3_4
```
They appear to run fine using the `php craft migrate/all` CLI command.
```
10 migrations were applied.

Migrated up successfully.
```
However when I try to apply project config, it tells me that I have pending migrations to run:
```
Craft has pending migrations. Please run `craft migrate/all` first.
```
If I then go into the CMS it gives me the 'finish up' button. When I click that, it tells me that the migrations are complete. After that, the `project-config/apply` command works fine. However this is not possible to manually go in and click the button on a remote environment, as technically our deploy 'fails'.

Is there any way to fix this? Other than clicking the `finish up` button locally and then pushing the DB to our remote servers?

### Additional info

- Craft version:  3.6.17 > 3.7.13
- PHP version: 7.4
- Database driver & version: MySQL 5.7

**Comment by bengreenbank** [comment]
As the issue was fixed when I created it, I have closed the ticket

**Comment by brandonkelly** [comment]
That message is a little cryptic. It could mean there are pending plugin migrations. Do you happen to have any plugins that are disabled via the `disabledPlugins` config setting?

**Comment by bengreenbank** [comment]
Thanks for getting back to me. There are currently no disabled plugins in `general.php` and when I look in the CMS, they are all installed.

**Comment by bengreenbank** [comment]
I've sent a WeTransfer with the required files. Thanks for looking into it!

**Comment by bengreenbank** [comment]
This was an issue with a dependency: https://github.com/percipioglobal/craft-colour-swatches/issues/70. Thanks Oli for the support.

**Comment by brandonkelly** [comment]
I just updated the `migrate/all` command to be defensive about the possibility of a plugin having an updated schema version but no new migrations, so this won’t be a problem going forward.

To get the change early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.13"` and run `composer update`. You should then be able to deploy the updated `composer.lock` file to production without migration issues.

**Comment by michtio** [comment]
Thanks @brandonkelly for offering a defensive strategy for this, and our sincere apologies for accidentally bumping the scheme version with the plugin update.

Definitely wasn't the intention! @bengreenbank

**Comment by bengreenbank** [comment]
No worries @michtio. Thanks for the swift response.

**Comment by brandonkelly** [comment]
Craft 3.7.14 is out now with that `migrate/all` fix.

**Comment by bengreenbank** [comment]
Thank you @brandonkelly
