### ISSUE TITLE
Performance issue on an entries page due to count query

### ISSUE THREAD

**Issue by magnessjo** [craftcms/cms#9861]
### Description

When loading an entries page in the admin, we see a significant load time.  Profiling states the query is taking > 25 seconds to complete (see attached).  

I ran the query outside of Craft, and it still takes > 21 seconds.  

I've run `php craft db/convert-charset utf8 utf8_unicode_c`, turned off autosaving in the config, and did a mysqlcheck to ensure that tables were ok.  

I can provide a DB dump.  

<img width="1568" alt="Screen Shot 2021-09-21 at 9 50 54 AM" src="https://user-images.githubusercontent.com/856595/134187997-83ae5ea2-8185-41ff-ada8-0b8a60101a80.png">

### Additional info

- Craft version: Pro 3.7.13
- PHP version: 7.4.23 
- Database driver & version: MySQL 8.0.26
- Plugins & versions: Neo(2.11.13), SEOmatic (3.4.10), redactor (2.8.8), Feed Me (4.4.0).

**Comment by magnessjo** [comment]
```
SELECT
	COUNT(*) 
FROM
	(
	SELECT
		`elements`.`id` AS `elementsId`,
		`elements_sites`.`id` AS `elementsSitesId`,
		`content`.`id` AS `contentId`,
		`structureelements`.`structureId` 
	FROM
		`elements` `elements`
		INNER JOIN `entries` `entries` ON `entries`.`id` = `elements`.`id`
		INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
		INNER JOIN `content` `content` ON `content`.`elementId` = `elements`.`id`
		LEFT JOIN `structureelements` `structureelements` ON ( `structureelements`.`elementId` = `elements`.`id` ) 
		AND (
			EXISTS (
			SELECT
				* 
			FROM
				`structures` 
			WHERE
				( `id` = `structureelements`.`structureId` ) 
			AND ( `dateDeleted` IS NULL )))
		LEFT JOIN `drafts` `drafts` ON `drafts`.`id` = `elements`.`draftId` 
	WHERE
		(
			`entries`.`sectionId` IN (
				'5',
				'12',
				'28',
				'26',
				'30',
				'6',
				'27',
				'2',
				'13',
				'29' 
			)) 
		AND ( `entries`.`sectionId` = '5' ) 
		AND ( `elements`.`type` = 'craft\\elements\\Entry' ) 
		AND ( `elements`.`archived` = FALSE ) 
		AND ( `elements`.`dateDeleted` IS NULL ) 
		AND ( `elements`.`canonicalId` IS NULL ) 
		AND ((
				`elements`.`draftId` IS NULL 
				) 
		OR ( `drafts`.`provisional` = FALSE )) 
		AND ((
				`elements`.`draftId` IS NULL 
				) 
			OR (
			NOT ( `elements`.`canonicalId` IS NULL )) 
		OR ( `drafts`.`saved` = TRUE )) 
	AND ( `elements`.`revisionId` IS NULL )) `subquery`
	INNER JOIN `entries` `entries` ON `entries`.`id` = `subquery`.`elementsId`
	INNER JOIN `elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
	INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
	INNER JOIN `content` `content` ON `content`.`id` = `subquery`.`contentId`
	LEFT JOIN `structureelements` `structureelements` ON ( `structureelements`.`elementId` = `subquery`.`elementsId` ) 
	AND ( `structureelements`.`structureId` = `subquery`.`structureId` )
	LEFT JOIN `drafts` `drafts` ON `drafts`.`id` = `elements`.`draftId`
```

**Comment by brandonkelly** [comment]
That’s the reason we made it a separate query. Do you have any suggestions for how we could improve the query performance?

**Comment by magnessjo** [comment]
Hi @brandonkelly , thanks for taking a look at this ticket.  

I poked at the query yesterday, but I didn't have a ton of time to dig into the schema.  I can find some time early next week to learn more, but I doubt I will have a ton to offer for it.  

I think my understanding of the problem might have been wrong, and I mislabeled this ticket as a result.  The main issue is content editors see the loading indicator for ~30 seconds for entry type (see attached example).  I don't think the query is the cause of the delay (it was the first thing I identified when profiling).  I think this ticket can be closed out based on that.  

Do you have guidance on issues using RDS?  Our production/staging environments are using RDS, and that is where we see the delay.  I made a cloned copy with the DB using a local MySQL instance, and I don't see the issue.  I assume there is a misaligned my.cnf setting that I need to work on. 

Thanks! 

<img width="1463" alt="Screen Shot 2021-09-22 at 9 07 07 AM" src="https://user-images.githubusercontent.com/856595/134360165-e8d45cf9-92ea-4d7e-bac2-68f3649e46fd.png">

**Comment by brandonkelly** [comment]
I’m not sure what the cause would be off the top of my head, but feel free to write into support@craftcms.com with details on the environment, and our DevOps team can offer some suggestions.

**Comment by magnessjo** [comment]
Thanks @brandonkelly!
