### ISSUE TITLE
`dump` only available in devMode, how to test?

### ISSUE THREAD

**Issue by nickdunn** [craftcms/cms#9870]
### Description

I use the `dump` method in some templates when I need to investigate API responses from third parties using the Fetch plugin (i.e. using Guzzle directly from Twig). I have left this debug code in my template and only show it if in devMode:

```
  {% if craft.app.config.general.devMode %}
    {{ dump(fundMetadata) }}
  {% endif %}
```

However this errors in production:

> Twig\Error\SyntaxError: Unknown "dump" function. 

Is there a reason Craft doesn't add the `dump` function the whole time? How should I get around this?

### Additional info

- Craft version: 3.7.13

**Comment by brandonkelly** [comment]
It’s provided by Twig’s Debug extension, which is recommended to only run in development environments due to security concerns.

That said, you can use Craft’s [{% dd %}](https://craftcms.com/docs/3.x/dev/tags.html#dd) tag instead, which is always available.

**Comment by nickdunn** [comment]
I wasn't aware of `dd`, that looks perfect thanks!

For the record, I ended up with something like this:

    {# debugging #}
    {% if fundMetadata.error is defined and craft.app.config.general.devMode %}
      {% dd {
          fundMetadataApi: fundMetadata,
         ... (other helpful objects here)
        } %}
    {% endif %}
