### ISSUE TITLE
Validation does not work on publish of entries when Entry URI format contains custom field

### ISSUE THREAD

**Issue by dreamseeker** [craftcms/cms#9873]
### Description

The custom field is set to Entry URI format.
When I publish another entry with the same URL, it redirects to the Element Index and the draft disappears.

I expect it to show a validation error and stay at the edit screen.

### Steps to reproduce

1. Install Craft 3.7.13
2. Create a Plain Text field, handle named 'serialNumber'.
3. Create a Section, handle named 'products'.
4. Entry URI Format sets `products/{serialNumber}`.
5. Add the 'serialNumber' field to Field Layout in the 'products' section. This field is required.
6. Create two live entries with the same Serial Number, and the new one will disappear when Craft applies the draft.

### Additional info

- Craft version: Craft Solo 3.7.13 / Craft Pro 3.7.13
- PHP version: 7.4.23
- Database driver & version: MySQL 5.7.35
- Plugins & versions: None

**Comment by brandonkelly** [comment]
Yikes, thanks for reporting that. Just fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.13"` and run `composer update`.

**Comment by dreamseeker** [comment]
> To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.13"` and run `composer update`.

Thanks. I'll try it.

**Comment by brandonkelly** [comment]
Craft 3.7.14 is out now with that fix.
