### ISSUE TITLE
Entry queries with a relation to a matrix block always return empty results

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#9875]
### Description

I'm trying to find all entries that have a specific type of matrix block on them. According to [this question](https://craftcms.stackexchange.com/a/27297/11705), this can't be done without custom join/where conditions. So instead I thought I could just find matrix blocks with that type first and then find the entries they relate to (based on [this question](https://craftcms.stackexchange.com/a/4237/11705)).

However, the entry query always returns an empty result:

```php
$contactFormMatrixBlocks = MatrixBlock::find()->type('contact_form')->ids();
$contactPages = Entry::find()->anyStatus()->relatedTo($contactFormMatrixBlocks)->all();
```

I've verified that `$contactFormMatrixBlocks` contains the correct array of matrix block IDs. However, `$contactPages` is always an empty array.

To check if I'm just missing something I've generalized the query a bit, and it appears that passing matrix blocks into an entry query using `relatedTo` will *always* return an empty result:

```php
$matrixBlocks = MatrixBlock::find()->limit(20)->ids();
$results = Entry::find()->anyStatus()->relatedTo($matrixBlocks)->all(); // []
```

Are matrix blocks not supported in relation queries at all? And is there a better way to do this? I know I could go through the `owner` property of the matrix blocks, but then I'd have to check all conditions I want to add to the entry query manually.

### Additional info

- Craft version: 3.7.13
- PHP version: 8.0.9
- Database driver & version: MySQL 8

**Comment by brandonkelly** [comment]
The `relatedTo` param only applies to many-to-many relationships, created via Assets/Categories/Entries/Tags/Users fields. Matrix blocks are _owned_ by their parent elements, so the relationship is stored in a different way that is incompatible with `relatedTo`.

That said, there didn’t seem to be a good way to filter entries based on those which own a set of Matrix blocks, so I just made that possible for the next release. Now Matrix fields’ element query params support passing in an array of Matrix block IDs, so going forward you will be able to do this:

```php
$contactFormMatrixBlocks = MatrixBlock::find()->type('contact_form')->ids();
$contactPages = Entry::find()->anyStatus()->myMatrixFieldHandle($contactFormMatrixBlocks)->all();
```

To get the change early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.13"` and run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.7.14 is out now with that change.

**Comment by pdaleramirez** [comment]
@brandonkelly I get an error when using the method on CMS 4 ```Database Exception – [yii\db\Exception](http://www.yiiframework.com/doc-2.0/yii-db-exception.html)
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'elements.id' in 'on clause'```
![Screen Shot 2022-07-08 at 6 32 33 PM](https://user-images.githubusercontent.com/4172750/177979482-fd39990e-84b6-4b28-8747-76bb7f3e818c.png)

CMS version 3 works
