### ISSUE TITLE
Can't update current user's Entry or Assets field using setFieldValue just before or after creating a new Entry

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#9876]
### Description

```
use Craft;
use craft\elements\Entry;
use craft\helpers\ElementHelper;
use craft\services\Elements;
use yii\base\Event;

Event::on(
	Elements::class,
	Elements::EVENT_BEFORE_SAVE_ELEMENT, // Same result using EVENT_AFTER_SAVE_ELEMENT
	function (Event $event) {
		if ($event->element instanceof Entry) {
			if (ElementHelper::isDraftOrRevision($entry)) {
				$user = Craft::$app->getUser()->getIdentity();
				$user->setFieldValue('plainTextField', 'Lorem ipsum'); // ✅  Ok
				$user->setFieldValue('entriesField', [$event->element->id]); // 🛑  Not ok
				Craft::$app->elements->saveElement($user);
			}
		}
	}
);
```

If `myEntriesField` is an Entries (or an Assets) field, it never get updated after an Entry is saved _for the first time_.
I can't even see the field in the `craft_content` table, where the others users' custom fields belongs.
Update another kind of field is ok (like `plainTextField` in the example).
I tried to move the `entriesField`'s update to a service, but with the same result: no update.

This issue is following this Github ticket [#38341](https://craftcms.stackexchange.com/questions/38).

### Additional info

- Craft version: Craft Pro 3.7.13
- PHP version: 7.4.14
- Database driver & version: MySQL 5.7.32

**Comment by brandonkelly** [comment]
You should use `getCanonicalId()` rather than the `id` property. `id` will be the draft ID, which is about to go away once the draft is applied to the canonical entry.

```php
$user->setFieldValue('entriesField', [
    $event->element->getCanonicalId(),
]);
```
