### ISSUE TITLE
App::env() doesn't always return the value of the env-variable inside a controller-action

### ISSUE THREAD

**Issue by bencresty** [craftcms/cms#9880]
### Description

While requesting an environment variable, like `CP_TRIGGER` with `App::env('CP_TRIGGER')`, from within a controller action method inside a module, it doesn't always return a value. Eventhough the environment variable never changes in the `.env` file. 

This happens quite a lot, which makes the controller action unreliable and causes an action here to be unusable for obvious reasons.

### Steps to reproduce

1. Create a controller with an action
2. Use App:env('ENV_VAR')

### Additional info

- Craft version: 3.7.13
- PHP version: 7.4.9

**Comment by brandonkelly** [comment]
If `App::env()` isn’t working sporadically, that means that the environment variable itself isn’t getting set sporadically, which  is a common issue with PHP Dotenv in high-traffic environments (see https://github.com/vlucas/phpdotenv/issues/219, https://github.com/vlucas/phpdotenv/issues/248, etc.).

You can try getting on a more recent version of PHP dotenv (that is a project dependency; not mandated by Craft itself), however your best bet is going to be to avoid using a `.env` file in production, and define those variables as part of your server configuration instead.
