### ISSUE TITLE
Dynamic title format issue with custom attributes name containing extra fields names

### ISSUE THREAD

**Issue by juban** [craftcms/cms#9891]
### Description
In a section layout, I have the following title format definition: 
`{testimonials_authorName} {testimonials_authorAge} {{"years old"|t}}`

It works pretty well as expected in a normal editing workflow.
However, when adding a new entry as a relation of another entry and using the slideouts interface, an server error is thrown when saving the relation.
Looking at the logs, it looks like that the 'author' field is somehow evaluated and because it is undefined at that moment, an error occurs:

```
#0 /var/www/html/vendor/craftcms/cms/src/elements/Entry.php(1162): craft\services\Users->getUserById('')
#1 /var/www/html/vendor/yiisoft/yii2/base/Component.php(140): craft\elements\Entry->getAuthor()
#2 /var/www/html/vendor/craftcms/cms/src/base/Element.php(1660): yii\base\Component->__get('author')
#3 /var/www/html/vendor/yiisoft/yii2/base/ArrayableTrait.php(126): craft\base\Element->__get('author')
#4 /var/www/html/vendor/craftcms/cms/src/web/View.php(614): yii\base\Model->toArray(Array, Array, false)
#5 /var/www/html/vendor/craftcms/cms/src/elements/Entry.php(1501): craft\web\View->renderObjectTemplate('{{testimonials_...', Object(craft\elements\Entry))
```

Digging a bit in Craft code, the reason for this is that `author` is part of the custom fields names used in the title format. In the `renderObjectTemplate` method of `craft\web\View` class, line 610 to 612, `author` field is wrongly added to the variables because of this (string comparison issue) and produce an error, because author is not defined at this point.

A more strict variables name detection should be use here.

### Steps to reproduce

1. Create a section layout with a custom field name containing `author`
2. For that layout, uncheck 'Show the Title field' and set the title format of that layout to use the custom field as dynamic value
3. Create another section layout using a entry type custom field related to the previous section
4. Try editing an entry of the second section and add a new relation entry of the first section (leaving the author attribute empty)

### Additional info

- Craft version:  3.7.13
- PHP version: 7.4
- Database driver & version: mysqlnd 7.4.20
- Plugins:
  * Elements Panel	1.1.1
  * Field Manager	2.2.4
  * Formie	1.4.17
  * Image Resizer	2.1.0
  * Image toolbox	1.1.1
  * Maps	3.9.2
  * oEmbed	1.3.10
  * PDF Transform	1.0.5
  * Redactor	2.8.8
  * Retcon	2.2.3
  * Sentry SDK	1.1.2
  * SEO	3.7.4
  * Sprout Fields	3.8.5
  * Super Table	2.6.8
  * Tags	1.0.7
  * Typogrify	1.1.18
  * UI Element fields	1.0.0
  * Vite	1.0.15

**Comment by brandonkelly** [comment]
Thanks for reporting! Craft 3.7.14 is out now with a fix.

**Comment by juban** [comment]
Thank you @brandonkelly
