### ISSUE TITLE
GraphQL mutation on provisional draft creates a new published element rather than mutating draft

### ISSUE THREAD

**Issue by membla** [craftcms/cms#9892]
### Description

When running draft mutations using the `draftId` of a provisional draft the draft is not mutated, rather a completely new entry seem to be created.

### Steps to reproduce

1. Query for provisional draft entries
2. Run a draft entry mutation using the draftId of the provisional draft to target
3. Observe that no errors are thrown – but that the returned result does not contain the mutated data
4. Observe that instead a new entry (published!) has been created

**Comment by andris-sevcenko** [comment]
Fixed for the next release, thanks!

**Comment by brandonkelly** [comment]
Craft 3.7.15 is out now with this fix.
