### ISSUE TITLE
GraphQL draft mutation fails when not passing all required entry fields

### ISSUE THREAD

**Issue by membla** [craftcms/cms#9893]
### Description

When using the `save_<sectionHandle>_<entryTypeHandle>_Draft` mutations it seems to be necessary to pass all required fields for the element, not just the `draftID` as specified by the schema, so for example not explicitly passing a `title` results in:

`"message": "Title cannot be blank.\nSlug cannot be blank."`

**Comment by andris-sevcenko** [comment]
Fixed for the next release, thanks!

**Comment by brandonkelly** [comment]
Craft 3.7.15 is out now with this fix.
