### ISSUE TITLE
Propagating entries to new site do not honor the default status

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#9896]
### Description
When you have set Propgation method to "let each entry choose". Each entry you create will automatically be enabled, even though that you have set the default status to false.

Right after creating a new entry, you can see that "enabled for german" is set tot true
![Schermafbeelding 2021-09-29 om 11 42 26](https://user-images.githubusercontent.com/23024452/135253025-027da6be-1c91-4d9f-853e-4c9f9a9aabde.png)

While the following settings should apply:
<img width="1508" alt="Schermafbeelding 2021-09-29 om 12 38 47" src="https://user-images.githubusercontent.com/23024452/135253172-61e61e53-7e74-4c81-b281-75bf4e425ebe.png">

### Additional info

- Craft version: 3.7.12
- PHP version: 8.x
- Database driver & version: 8.x

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.15 is out now with this fix.
