### ISSUE TITLE
Reorder singles in the CP

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#990]
> Created by: Andy Harris (andy@pepperdigital.com) on 2015/03/19 11:03:06 +0000
> Votes at time of UserVoice import: 6

-----------------------------------

We have some sites with quite a lot of singles, and ordering by date or title doesn't really have any relevance - it'd be nice to be able to control the order, so home is always at the top and the rest matched the site itself as closely as possible.

Purely a cosmetic CP thing.

**Comment by leowebguy** [comment]
agree, let's have an option to organize singles in blocks

**Comment by ryanmasuga** [comment]
Every time we have a site with any number of singles, we see them in a natural hierarchy - and it's different for every site. Home at top, maybe "About" is next, and so on. Every time I want to drag/drop to reorder them like we do for Structures, just to be organized. I think this would be a nice enhancement, if Singles are going to remain their own separate list.
