### ISSUE TITLE
Project-config/apply aborts without console error

### ISSUE THREAD

**Issue by gbowne-quickbase** [craftcms/cms#9900]
### Description
When we run a `project-config/apply` from the command line we regularly see the process abort without a `Finished applying changes` message. Sometimes running it again will fix it, but often 3-4 runs will still get the abort. Since we rely on this process for deploys in addition to merging in other devs changes, we want to know if this is our DB/project and/oor  how to consistently get it to run. The problem has been happening for us for a few months now, and it's slowing us down enough we can't ignore it.

I realize you may need a bunch of evidence to see what's going on, so I'm glad to zip up as much as you need to. 
![image](https://user-images.githubusercontent.com/39066452/135330155-bd022bf7-3435-40e8-a0db-2ae4291d78ee.png)

NOTE: Just to be sure, I'm going to try this again right now on with a fresh DB and try the `./craft up` command to see if it gives us better info.

### Steps to reproduce

1. Check out peer's branch, run the `./craft project-config/apply`
2. Have the process run and pause during the `updating meta.__names__.`  section, then abort with a `%` after the `done` without a completion message

### Additional info

- Craft version: 3.7.13
- PHP version: 7.3.20
- Database driver & version:  Ver 14.14 Distrib 5.7.29, for osx10.15
- Plugins & versions:

1. Amazon S3	1.2.15
2. Asset Usage	2.2.1
3. Calendar Links	1.0.1
4. Canary	3.0.4
5. Cloudflare	1.0.1
6. Cookie Consent Banner	1.2.8
7. Element API	2.8.2
8. Feed Me	4.4.0
9. Field Manager	2.2.4
10. GeoMate	v1.3.1.2
11. Icon Picker	1.1.11
12. ImageOptimize	1.6.36
13. Linkit	1.1.12.1
14. Matrix Finder	1.1.0
15. quickbase-process	1.0.12
16. Read Time	1.6.0
17. Redactor	2.8.8
18. Redactor Anchors	1.1.0
19. Retour	3.1.61
20. SEOmatic	3.4.8
21. Similar	1.1.5
22. Simple Sharing	1.0.8
23. Smith	1.1.14
24. Sprig	1.8.1
25. Super Table	2.6.8
26. Tags	1.0.7
27. Twigpack	1.2.15
28. Workflow	1.6.2

**Comment by gbowne-quickbase** [comment]
[console.log](https://github.com/craftcms/cms/files/7254739/console.log)
this is a console log of me applying changes to the production db. It seems there are a few instances of trying to release a loclkthat isn't there.

**Comment by brandonkelly** [comment]
@andris-sevcenko any ideas?

**Comment by andris-sevcenko** [comment]
@gbowne-quickbase The "%" sign you see is something that gets output if the command ends without a newline and that's the shell adding that, not Craft.

Is there anyhing in the phperrors.log file, perhaps? The output in the console.log also ends rather abruptly, too. One second it's updating the project config names, but the next one it just stops, as if the script was killed or something.

**Comment by gbowne-quickbase** [comment]
@andris-sevcenko There's nothing in the phperrors.log at all, and I didn't see anything in the apache errors either. I did notice that the `web-404s.log` was getting hit pretty hard, and found a few lines that shows an exception is being thrown. I do have `nystudio107/craft-retour` installed, which is pretty common, and I can't imagine how the `./craft up` process would trigger a 404, but it looks like a `message` template is being called and isn't found, and `Retour` is grabbing it. 

```UPDATE `craft_retour_stats` SET `id`=307335, `siteId`=1, `redirectSrcUrl`='/message', `referrerUrl`='', `remoteIp`='::1', `userAgent`='', `exceptionMessage`='Template not found: message',```

Here's a longer dump of the surrounding logs
```2021-10-04 18:54:24 [-][-][2ctm50l1tkki7ab2s3jrhtqf19][info][yii\db\Command::execute] UPDATE `craft_retour_stats` SET `id`=307335, `siteId`=1, `redirectSrcUrl`='/message', `referrerUrl`='', `remoteIp`='::1', `userAgent`='', `exceptionMessage`='Template not found: message', `exceptionFilePath`='/Users/gbowne/sites/quickbase3/vendor/craftcms/cms/src/controllers/TemplatesController.php', `exceptionFileLine`=92, `hitCount`=1572, `hitLastTime`='2021-10-04 18:54:24', `handledByRetour`=0, `dateUpdated`='2021-10-04 18:54:24' WHERE `id`=307335
2021-10-04 18:54:24 [-][-][2ctm50l1tkki7ab2s3jrhtqf19][profile begin][yii\db\Command::execute] UPDATE `craft_retour_stats` SET `id`=307335, `siteId`=1, `redirectSrcUrl`='/message', `referrerUrl`='', `remoteIp`='::1', `userAgent`='', `exceptionMessage`='Template not found: message', `exceptionFilePath`='/Users/gbowne/sites/quickbase3/vendor/craftcms/cms/src/controllers/TemplatesController.php', `exceptionFileLine`=92, `hitCount`=1572, `hitLastTime`='2021-10-04 18:54:24', `handledByRetour`=0, `dateUpdated`='2021-10-04 18:54:24' WHERE `id`=307335
2021-10-04 18:54:24 [-][-][2ctm50l1tkki7ab2s3jrhtqf19][profile end][yii\db\Command::execute] UPDATE `craft_retour_stats` SET `id`=307335, `siteId`=1, `redirectSrcUrl`='/message', `referrerUrl`='', `remoteIp`='::1', `userAgent`='', `exceptionMessage`='Template not found: message', `exceptionFilePath`='/Users/gbowne/sites/quickbase3/vendor/craftcms/cms/src/controllers/TemplatesController.php', `exceptionFileLine`=92, `hitCount`=1572, `hitLastTime`='2021-10-04 18:54:24', `handledByRetour`=0, `dateUpdated`='2021-10-04 18:54:24' WHERE `id`=307335
2021-10-04 18:54:24 [-][-][2ctm50l1tkki7ab2s3jrhtqf19][error][yii\web\HttpException:404] yii\web\NotFoundHttpException: Template not found: message in /Users/gbowne/sites/quickbase3/vendor/craftcms/cms/src/controllers/TemplatesController.php:92
Stack trace:
#0 [internal function]: craft\controllers\TemplatesController->actionRender('message', Array)
#1 /Users/gbowne/sites/quickbase3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /Users/gbowne/sites/quickbase3/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#3 /Users/gbowne/sites/quickbase3/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('render', Array)
...
```

I disabled Retour at the command line and ran the `./craft up`  again. It failed at the same place, and the error was caught by Craft instead of Retour, and after this snippet, had the same stacktrace 
```2021-10-04 19:03:27 [-][-][2ctm50l1tkki7ab2s3jrhtqf19][trace][craft\web\UrlManager::_getMatchedElementRoute] [
    'rule' => 'Element URI: message',
    'match' => false,
    'parent' => null,
]```

Some `message` isn't getting to me!

**Comment by brandonkelly** [comment]
Can you please send your `composer.json` + `composer.lock` files, a database backup from the server where this is happening, and a zip of the incoming `config/project/` folder, over to support@craftcms.com? We can try to look into it from there.

**Comment by gbowne-quickbase** [comment]
Thanks! Email's been sent off.

**Comment by michaelrog** [comment]
I got the exact same issue just yesterday: Console log just ends, abruptly, during the `updating meta.__names__.` section.

fwiw, immediately thereafter, running the "Apply" from the CP utility completed without issue.

**Comment by jalendport** [comment]
Same issue and here's the underlying error from the console.log file:
```
2021-10-06 15:25:45 [-][-][-][error][yii\base\Exception] yii\base\Exception: Invalid field layout ID: 78 in /app/vendor/craftcms/cms/src/services/Fields.php:1454
Stack trace:
#0 /app/vendor/spicyweb/craft-neo/src/services/BlockTypes.php(374): craft\services\Fields->saveLayout(Object(craft\models\FieldLayout))
#1 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1189): benf\neo\services\BlockTypes->handleChangedBlockType(Object(craft\events\ConfigEvent))
#2 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#3 /app/vendor/yiisoft/yii2/base/Component.php(628): call_user_func(Array, Object(craft\events\ConfigEvent))
#4 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(749): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#5 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1179): craft\services\ProjectConfig->_processConfigChangesInternal('neoBlockTypes.7...')
#6 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#7 /app/vendor/yiisoft/yii2/base/Component.php(628): call_user_func(Array, Object(craft\events\ConfigEvent))
#8 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(749): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#9 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1308): craft\services\ProjectConfig->_processConfigChangesInternal('neoBlockTypes.7...', false, NULL, true)
#10 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(573): craft\services\ProjectConfig->_applyChanges(Array)
#11 /app/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(174): craft\services\ProjectConfig->applyYamlChanges()
#12 [internal function]: craft\console\controllers\ProjectConfigController->actionApply()
#13 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /app/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#15 /app/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('apply', Array)
#16 /app/vendor/craftcms/cms/src/console/Controller.php(221): yii\console\Controller->runAction('apply', Array)
#17 /app/vendor/yiisoft/yii2/base/Module.php(534): craft\console\Controller->runAction('apply', Array)
#18 /app/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('project-config/...', Array)
#19 /app/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('project-config/...', Array)
#20 /app/vendor/yiisoft/yii2/console/Application.php(148): craft\console\Application->runAction('project-config/...', Array)
#21 /app/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(craft\console\Request))
#22 /app/craft(25): yii\base\Application->run()
#23 {main}
```

**Comment by brandonkelly** [comment]
@jalendport https://github.com/craftcms/cms/issues/9900#issuecomment-934411289 - same to you.

**Comment by Wiejeben** [comment]
Seeing the same thing, no error level logs are being generated. Running it again exists nicely with `Finished applying changes`.

```
- adding matrixBlockTypes.7bfc9d1e-c569-43ba-b5e9-f33fec45dfa5.fields.9e8517cb-bab3-4b96-b36a-e2727aa0f87b.settings.options.3.__assoc__.1 ... done
- adding matrixBlockTypes.7bfc9d1e-c569-43ba-b5e9-f33fec45dfa5.fields.9e8517cb-bab3-4b96-b36a-e2727aa0f87b.settings.options.3.__assoc__.2 ... done
Finished applying changes

- updating meta.__names__.7bfc9d1e-c569-43ba-b5e9-f33fec45dfa5 ... done
- updating meta.__names__.9e8517cb-bab3-4b96-b36a-e2727aa0f87b ... done
- updating meta.__names__.d94d61e1-4812-47f6-93d4-c5bff8e98d77 ... done%
                                                                                                              
craft on  master
➜ dcraft project-config/apply
Applying changes from your project config files ...
Finished applying changes
```

**Comment by andris-sevcenko** [comment]
Just (finally) fixed this for the next release!

**Comment by brandonkelly** [comment]
Craft 3.7.32 is out now with the fix.
