### ISSUE TITLE
CSS bug: CP breadcrumbs on mobile

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#9902]
### Description
Hi,

In the entry edit view, on mobile,  when there are multiple breadcrumb levels, the user profile thumbnail and dropdown get "squished" as can be seen in the attached screenshot:

![image](https://user-images.githubusercontent.com/19857599/135424880-bbbaff7f-4c7f-46ed-9fdf-bd3361b7eeeb.png)

### Steps to reproduce

1. Edit via mobile an entry deeply nested in a structure

### Additional info

- Craft version: 3.7.14
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.15 is out now with this fix. Thanks again!
