### ISSUE TITLE
Consistent Save Button Location (2.5)

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#991]
> Created by: Chase Giunta (me@chasegiunta.com) on 2015/03/30 19:07:54 +0000
> Votes at time of UserVoice import: 6

-----------------------------------

With Craft 2.5, it looks like the save button has been pretty consistently located to the page header, except for the user profiles (and possibly some other locations I haven't found), where it's found at the bottom of each profile tab, which means scrolling to the bottom of long user profiles to save. To avoid confusion, it would be great to have them all in the same location.

To piggyback on this, a fixed Save Button location would also be very helpful for long entries, so there is no need to scroll *all* the way to the very top (first world problems).

**Comment by brandonkelly** [comment]
This was resolved in Craft 3 RC1.
