### ISSUE TITLE
Matrix content lost when propagating an entry to a new site, if you disable the entry immediatly

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#9910]
### Description
We have a section that has a matrix field, containing images/description. All standard Craft fields.
The section propagation settings are set to: "Let each entry choose which sites it should be saved to".

When you propagate the entry to a new site, all seems good at first glance. You save the entry, all the matrix blocks are there and you're happy. But once you save, leave the entry, go back, everything is gone.

As far as I can tell, it's somehow related to us disabling the entry right after add it to a new site. We do this because we don't want the entry to be published before it has been localized.

Screenshare:
https://backspace.stackstorage.com/s/md5cSfEmMM6DYeF2

### Additional info

- Craft version: 3.7.14
- PHP version: 8.0

**Comment by brandonkelly** [comment]
Hey @lenvanessen, can you please send a database backup and your `composer.json` + `composer.lock` files into support@craftcms.com? We can try to look into it from there.

**Comment by brandonkelly** [comment]
Thanks for your help, @lenvanessen. Just got this fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.14"` and run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.7.15 is out now with the fix for this. Thanks again for reporting!
