### ISSUE TITLE
Export does not include children that are hidden in the UI

### ISSUE THREAD

**Issue by chrismlusk** [craftcms/cms#9913]
### Description
I have a structure with about 1,000 entries, most of which are children of about 30 entries. The element table is sorted by structure, which allows me to show/hide children. Because of the large number of entries, all of the children groups are hidden.

When I try to export the entries to a CSV, the generated file does not include any of the children.

Regardless of what I have toggled to show/hide in the table, I would expect the exporter to give me all entries.

### Additional info

- Craft version: 3.7.14
- PHP version: 7.4.16
- Database driver & version: MySQL 5.7.32

**Comment by brandonkelly** [comment]
Thanks for reporting that. Just fixed it for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.14"` and run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.7.15 is out now with this fix.
