### ISSUE TITLE
Unic slug leads to a validation error

### ISSUE THREAD

**Issue by abuerin** [craftcms/cms#9914]
### Description
I upgraded Craft CMS from 2.9.2 to Craft 3.7 but now i have the problem that i can't save any new entry because of the error that the slug is not unic even if it is unic.

<img width="371" alt="Bildschirmfoto 2021-10-01 um 22 20 51" src="https://user-images.githubusercontent.com/85960512/135682062-6b62c2ae-ed2e-4fed-801d-b9756c7ccb25.png">

### Additional info
It sames very similar to this one: https://github.com/craftcms/cms/issues/4791

- Craft version: 3.7.14

**Comment by brandonkelly** [comment]
The error message is saying that it can’t find a unique _URI_ for the entry, based on the section’s Entry URI Format. It’s not actually an issue with your Slug per-se; that’s just the closest thing to a URI field on the page.

Check your section’s settings, and ensure that the Entry URI Format includes `{slug}`, if that works for your use case.
