### ISSUE TITLE
New FieldLayout models returned without `type` when using getLayoutByType()

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/cms#9918]
### Description

This very well could just be my responsibility, but it seems odd that a new `FieldLayout` model instantiated by `Craft::$app->getFields()->getLayoutByType(User::class)` would come back with `$layout-> type === null`.

This is the block in question:
https://github.com/craftcms/cms/blob/develop/src/services/Fields.php#L1111

I would expect the model to be instantiated with the `type` argument passed. While I can patch this in our application ~~in each element type's `getFieldLayout()` method~~ in each relevant Controller/Action, I _can't_ assign the `type` in, say, the UsersController.

### Steps to reproduce

1. Add a listener for `FieldLayout::EVENT_DEFINE_STANDARD_FIELDS` and check/dump `$event->sender->type` at some point in the closure
1. On a new installation, visit a User’s edit page (or call `Craft::$app->getFields()->getLayoutByType(User::class)` in another context)

This wouldn't matter for globally-registered `FieldLayoutElements` that don't care about the element type the `FieldLayout` is for, but anything scoped to a specific one (i.e. `if ($event->sender->type === User::class) { … }`) will be missing.

### Additional info

- Craft version: 3.7.13
- PHP version: 7.4.23
- Database driver & version: MySQL 5.7
- Plugins & versions: None, 2 x Custom Modules

**Comment by brandonkelly** [comment]
Looks like this is only an issue when no user field layout exists yet. Just fixed that for the next release.

**Comment by brandonkelly** [comment]
Craft 3.7.15 is out now with the fix for this.
