### ISSUE TITLE
No reserved words for Matrix fields

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#992]
> Created by: Katrin Kerber (katrinkerber@gmail.com) on 2015/06/09 17:44:40 +0000
> Votes at time of UserVoice import: 6

-----------------------------------

I like to keep field names of Matrix blocks as simple possible, but I am very often tripping up with the 'XXX is a reserved word' error whenever I want to use words like 'name', 'title', 'link' or 'url'.

I am sure there is a very valid reason for certain words being reserved, but maybe there is a workaround where that isn't necessary for Matrix block fields?

**Comment by brandonkelly** [comment]
This will be fixed via #1524.

**Comment by kobeaerts** [comment]
Hey @brandonkelly, is this issue fixed with #1524 ?

**Comment by brandonkelly** [comment]
Not yet; we will be implementing changes based on that in Craft 4.
