### ISSUE TITLE
[Matrix] Propagation Method (only save blocks to the site they were created in) has no effect

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#9924]
### Description
My Matrix field has this propagation method setting:
![image](https://user-images.githubusercontent.com/764292/135969318-67b40953-39d7-4c0f-b392-a63fad02e412.png)

So, no we have some multisites and when create an entry in multisite A all matrix blocks are propagated to Site B
Site A:
![image](https://user-images.githubusercontent.com/764292/135969396-70805c9a-576b-4569-ac76-812d945d39c4.png)

Site B:
![image](https://user-images.githubusercontent.com/764292/135969421-1fedf446-3207-474a-8b14-941a0905ea9d.png)

My understanding here is there should be no blocks in Site B, right?

### Steps to reproduce

1. Create an entry in Site A and create a Matrix Block
2. Switch to Site B and the blocks are there

### Additional info

- Craft version: 3.7.14
- PHP version: 7.4

**Comment by brandonkelly** [comment]
When you first create a new entry, any Matrix blocks you create will be _cloned_ to other sites, however they each should have their own unique IDs, and you can delete them if you don’t want them.

That behavior will only last until you navigate away from the page, change the selected site, click Save, etc.

**Comment by davidhellmann** [comment]
OK, but is it awesome from a performance perspective? We have 20 multisites and that makes saving initially quite slow because of course he has to save them away everywhere. 

And second question: Is it always like this? I imagine that it was different once and the blocks were not saved when creating the entry?
