### ISSUE TITLE
'Someone tried to load a template outside the templates folder' error

### ISSUE THREAD

**Issue by ryssbowh** [craftcms/cms#9929]
I've got a few Craft sites on Sentry and I keep receiving that error on some of them :
`Someone tried to load a template outside the templates folder: ../../../../../../../../../../../../../../../../../../etc/passwd`
Which is more than likely triggered by bots.

I don't really see this as an error, just a security layer doing its job, and I would ignore them before they are sent to Sentry but it comes in the category `application`, I don't want to ignore all the errors that may come under this category.

Would it make sense to give that error a different category ? Or remove the error altogether given that an exception follows ?

That's where it's thrown :
https://github.com/craftcms/cms/blob/a645cb382ee28c7527bca9629a92528677e1f073/src/web/View.php#L1940

Craft version : 3.7.13
PHP version : 7.4.24
Sentry plugin : https://github.com/diginov/craft-sentry-logger 1.1.7

Thank you

**Comment by brandonkelly** [comment]
What is the stack trace leading up to this?

**Comment by ryssbowh** [comment]
Very strange, I can't find any trace of it in the logs,
```
logs$ grep -rnw . -e 'Someone'
logs$ grep -rnw . -e 'passwd'
```
return nothing.

The query string is filtered out in Sentry but I can reproduce it by visiting `https://domain.co.uk?p=../../../../../../../../../../../../../../../../../../etc/passwd` which is sent to Sentry and logged properly

I've got 3 others like this on that site, about 50 of them this month :
`../pixfir~1/how_to_login.html`
`../../../../../usr/bin/id|`
`../../../../../../../../etc/passwd`

**Comment by brandonkelly** [comment]
Craft 3.7.17 is out now with change.
