### ISSUE TITLE
Time fields revert from PM to AM when the user has "Greek" as the selected Formatting Locale in the CP

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#9942]
### Description
In the CP I have selected Greek `Ελληνικά (Ελλάδα)` as a Formatting Locale for my user account (had to add it to the config first of course).

In Greek:
`'amName' => 'π.μ.'`
`'pmName' => 'μ.μ.'`

I noticed that when any time field is set to PM (eg. 10:30 μ.μ.), it does get saved correctly, but when I revisit (or just save) the entry in the CP it gets reverted to AM (eg. 10:30 π.μ.). I also noticed that while the page is still loading the correct time is displayed. The value of the field in the db remains correct, it's just the appearance that changes.

I suppose it's a JS bug.

### Steps to reproduce

1. Change user Formatting Locale to `Ελληνικά (Ελλάδα)`
2. Create an entry with a time field (even the default post time field) and set a PM time
3. Save the entry.
4. In the entry page the time has changed from PM to AM.

### Additional info

- Craft version: Craft Pro 3.7.16
- PHP version: 7.4.14
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

**Comment by thupsi** [comment]
I've registered it in `general.php` (in global settings) like this:

```
 'extraAppLocales' => [
            'el_GR',
        ],
```

**Comment by thupsi** [comment]
Any updates on this @brandonkelly?

I see that your bug report (https://github.com/wvega/timepicker/issues/136) remains open and unanswered and it's still an issue in Craft 4.4.8.

**Comment by brandonkelly** [comment]
Sorry, we had some browser support issues with native date/time inputs, so that ended up not making it into v4. We’ll see if it’s something we can work around.

**Comment by brandonkelly** [comment]
Craft 4.5.0 is out with a fix for this 🎉

**Comment by thupsi** [comment]
Hmm, it's not working on my end, tested on two projects (Craft 4.5). It got worse actually: Now when I update a time field and then save, the field content is discarded (it becomes empty). 🤷

Sorry for not testing this at the beta level, I was on vacation 🙂

**Comment by brandonkelly** [comment]
Doh, I guess I forgot to test saving new time values 🤦🏻 

Craft 4.5.1 is out with a fix for that.
