### ISSUE TITLE
PHP ErrorException: deleteAllTransformData is unable to delete the temp file

### ISSUE THREAD

**Issue by gddotorg** [craftcms/cms#9957]
### Description
We have developed our own API for one of our clients. The customer can upload new assets via a URL. Furthermore, existing assets can be updated.

To track our exceptions, we use Sentry. We get the following exception when an asset is updated via API: 
`Warning: unlink(/app/current/storage/runtime/assets/sources/116406.jpg): No such file or directory.`

Generally the upload works and the new data is present in Craft BE. By searching the log files I found the following warning: `craft\services\AssetTransforms::deleteAllTransformData Unable to delete the file "/app/storage/runtime/assets/sources/116406.jpg"`

During the process no file is saved to the sources folder. Instead the uploaded file is stored in storage/runtime/temp folder. Is this a bug or am I missing something?

If you need more information, just let me know.

Best regards,
Georg

### Steps to reproduce

1. $uploadedFile = UploadedFile::getInstanceByName('imageData');
2. $asset =  Asset::find()->volumeId($volumeId)->title($title)->one();
3. $asset->tempFilePath = $uploadedFile->saveAsTempFile();
    $asset->title = $title;
    $asset->filename = $uploadedFile->name;
4. $result = Craft::$app->getElements()->saveElement($asset, true, true, false);

### Additional info

- Craft version: 3.7.16
- PHP version: 7.4
- Database driver & version: MySQL

**Comment by andris-sevcenko** [comment]
All fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 3.7.19 is out now with the fix.
