### ISSUE TITLE
Template is expecting an array but getting null instead, breaking the template

### ISSUE THREAD

**Issue by eduardoalonsoalbella** [craftcms/cms#9969]
### Description

Template is expecting an array but getting null intead, throwing an error.

The function prepFormActions found in src/web/twig/variables/Cp.php:692 may return a null value

```php
return $event->formActions ?: null;
```

Template:

        src/templates/_layouts/cp.html

```twig
{% set formActions = craft.cp.prepFormActions(formActions ?? null) %}
```

In the following template, it's expected an array

        src/templates/_layouts/components/form-action-menu.twig:30

```twig
{% set safeActions = formActions|filter(a => not (a.destructive ?? false)) %}
{% set destructiveActions = formActions|filter(a => a.destructive ?? false) %}
```

![Captura de pantalla 2021-10-14 a las 19 10 29-fullpage](https://user-images.githubusercontent.com/90317987/137392971-b7f6d179-3ebe-48a4-b84f-277705d6d2e8.png)

### Steps to reproduce

1.
2.

### Additional info

- Craft version: latest
- PHP version: 8.0
- Database driver & version: Mysql
- Plugins & versions:

**Comment by brandonkelly** [comment]
Craft 3.7.17 is out now with that fix.

**Comment by eduardoalonsoalbella** [comment]
I've just tested craft 3.7.17 and the error is gone! Thanks!
