### ISSUE TITLE
EVENT_BEFORE_HANDLE_EXCEPTION not triggered for application/json

### ISSUE THREAD

**Issue by swey** [craftcms/cms#9973]
### Description
For request with header `Accepts: application/json` the `EVENT_BEFORE_HANDLE_EXCEPTION` will never be triggered. Exceptions will be logged, but not handled as the other errors. 

Error handling for exceptions in context of `application/json`:
https://github.com/craftcms/cms/blob/c2ea860eb2e060cb1224756dfe81efa06e49167d/src/web/Controller.php#L192-L193
Error handling for other exceptions:
https://github.com/craftcms/cms/blob/389017e0bac76f90277a5036a3fa5d5794724f5d/src/web/ErrorHandler.php#L39-L47

Probably the `handleException` method in `ErrorHandler` should also handle the JSON case (and not `runAction` in `Controller`). Then within `runAction` the `handleException` instead of `logException` method should be called.

### Steps to reproduce

1. Listen for `EVENT_BEFORE_HANDLE_EXCEPTION`
2. Create controller action which throws an exception
2. Make HTTP request with `Accepts: application/json` header

### Additional info

- Craft version: 3.7.16
- PHP version:  8.0.10

**Comment by brandonkelly** [comment]
Good point. I’ve just moved the JSON response code over to ErrorHandler, so `EVENT_BEFORE_HANDLE_EXCEPTION` will get triggered for JSON requests.

**Comment by swey** [comment]
Thanks @brandonkelly !

Please double check the `bark` in your commit

**Comment by brandonkelly** [comment]
Hah yeah I forgot to remove that. Force-pushed to overwrite it immediately after :)
