### ISSUE TITLE
Add "View Asset" link in asset modal

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#999]
> Created by: Timothy Kelty (timkelty@gmail.com) on 2015/04/02 12:33:05 +0000
> Votes at time of UserVoice import: 6

-----------------------------------

I think there should be a "View Asset" link, that opened the original asset in a new window from the modal (double clicking asset)

- Clients have found it confusing to select asset, then go to gear to view asset
- as it is only accessible from the gear, there is no way to view the original asset from an entry/field. If it were in the modal, problem solved.

**Comment by timkelty** [comment]
Please!

**Comment by brandonkelly** [comment]
Now that assets have their own dedicated edit pages, I think ideally there should just be a way to access the full Edit Asset page from relational fields, and you can view the asset from there. So will close this in favor of #1057.
